### ISSUE TITLE
Handle Formula renames and deletions

### ISSUE THREAD

**Issue by mxcl** [Homebrew/homebrew#14374]
The git diff tells us what has been renamed. So we need to watch that and rename kegs and update symlinks. We need this for taps too.

The git diff tells us what has been deleted. So we need to watch that and look in Aliases to see if a new one is created and if so treat it as a "dupe" being deleted and do the above. Not for taps: taps don't have Aliases (yet).

When we can do this we need to delete one of

* lastfm_fplib and lastfmfpclient (dupes of each other).

When we can do this we need to rename:

* mosh -> mosh-scheme
* cmu-sphinxbase and cmu-pocketsphinx (remove the cmu prefix)
* yuicompressor -> yui-compressor or even just yui

This thread serves as official renames thread. Please research the Debian names also as this is the canonical naming DB.

**Comment by guoxiao** [comment]
`stash-cli` => `atlassian-cli`
see #40909

**Comment by mikemcquaid** [comment]
Support for this has been implemented in #41006. I'm going to leave this issue open until we've migrated more of the mentioned formulae in here to new names.

**Comment by jhass** [comment]
That's great news, can we have `crystal` renamed to `crystal_generator` then, to reduce confusion with the much more popular Crystal language? See the discussion in #40530.

Are there plans for any process around requesting renames, especially from non-maintainers?

**Comment by mikemcquaid** [comment]
@jhass We'll be considering each rename on a case-by-case basis. You can request renames but obviously we can't make any promises either way right now.

**Comment by jhass** [comment]
Well, consider the above a request then.

**Comment by wesbland** [comment]
As mentioned way above and in a closed ticket (#16298), `mpich2` --> `mpich`.

**Comment by mikemcquaid** [comment]
Closing this now that this is implemented and we've migrated a few formulae without end-user issues. There are a few open PRs for renames but if there isn't one open for your chosen rename: please submit a pull request following the documentation in https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Rename-A-Formula.md and format in e.g. https://github.com/Homebrew/homebrew/issues/14374. Thanks @vladshablinsky!
