### ISSUE TITLE
Homebrew goes ahead with installation after warning dev tools aren't installed

### ISSUE THREAD

**Issue by mistydemeo** [Homebrew/homebrew#19580]
As reported by a user on IRC:

```
Warning: No developer tools installed
You should install the Command Line Tools: http://connect.apple.com
==> Downloading http://git-core.googlecode.com/files/git-1.8.2.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/git-1.8.2.2.tar.gz
==> make prefix=/usr/local/Cellar/git/1.8.2.2 CC=cc CFLAGS=-Os -w -pipe   -march=native -Qunused-arguments -mmacosx-version-min=10.8 LDFLAGS=-L/usr/local/lib install
Failed to execute: make
Error: Homebrew doesn't know what compiler versions ship with your version
of Xcode (dunno). Please `brew update` and if that doesn't help, file
an issue with the output of `brew --config`:
```

Even though Homebrew warns the user that the dev tools aren't installed, the installer moves ahead with installation anyway, which predictably fails. Looks like this happens because of this: https://github.com/mxcl/homebrew/blob/master/Library/Homebrew/cmd/install.rb#L42-L49

We borrow the `brew doctor` check for Xcode, which just returns a string and doesn't let us determine whether a) no dev tools are installed, b) outdated dev tools are installed.

I'll probably replace this with something like:

```ruby
  def check_xcode
    require 'cmd/doctor'
    checks = Checks.new
    # if there are no dev tools, don't bother proceeding with the build
    odie checks.send(:check_for_latest_xcode) if !(MacOS::Xcode.installed? or MacOS::CLT.installed?)
    # these two are informative but not fatal
    opoo checks.send(:check_for_latest_xcode) if MacOS::Xcode.version < MacOS::Xcode.latest_version
    out = checks.send(:check_xcode_license_approved)
    opoo out unless out.nil?
  end
```

Still borrowing the message from the doctor, but performing the tests we really care about ourselves.

**Comment by mikemcquaid** [comment]
Homebrew can now work in some cases without development tools so closing this out.
