### ISSUE TITLE
document pkg-config configuration 

### ISSUE THREAD

**Issue by hhugo** [Homebrew/homebrew#21129]
I had to put the following in my bashrc/bashprofile

```
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/X11/lib/pkgconfig/
for i in `ls /usr/local/opt/`;
do
    if [ -d "/usr/local/opt/$i/lib/pkgconfig" ];
    then export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:"/usr/local/opt/$i/lib/pkgconf\
ig";
    fi;
done
```

**Comment by fish2000** [comment]
For the record I, too, found `pkgconfig` directories containing `*.pc` files in the `lib` subdirectories of at least two installed kegs: LibTIFF and OpenEXR. Both of these are *not* keg-only. 

Just to make sure I wasn’t working with old versions, I uninstalled both of these packages just now and reinstalled them; `/usr/local/opt/${keg}/lib/pkgconfig` was still where the `pkg-config` data wound up in both cases, poured right from the current bottles.

(I manually fixed both of these on my install by relocating the errant folders in question to `/usr/local/opt/${keg}/share/pkgconfig` – in both cases I could use e.g. `pkg-config --exists ${pkgname} && echo "I Found It"`to test that things were where `pkg-config`’s own configuration expects to find them.

**Comment by jacknagel** [comment]
It's perfectly fine for there to be pkgconfig files in the `lib/pkgconfig` location. In fact, the vast majority of packages use that location. You should not need to move anything.

**Comment by mangotv** [comment]
help

 sudo brew install pkg-config
==> Downloading http://pkgconfig.freedesktop.org/releases/pkg-config-0.28.tar.gz
Already downloaded: /Library/Caches/Homebrew/pkg-config-0.28.tar.gz
==> ./configure --prefix=/usr/local/homebrew/Cellar/pkg-config/0.28 --disable-host-tool --with-internal-glib --with-pc-path=/usr/local/homebrew/lib/pkgconfig:/usr/local/homebrew
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/tmp/pkg-config20150505-84092-cyb1qf/pkg-config-0.28':
configure: error: C compiler cannot create executables
See `config.log' for more details
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
document pkg-config configuration  (https://github.com/Homebrew/homebrew/issues/21129)
Missing pkg-config directory in path causes pkg-config lookup for Homebrew packages to fail from Homebrew's build environment (https://github.com/Homebrew/homebrew/issues/39384)

**Comment by DomT4** [comment]
I'm not sure the concept of `keg_only` isn't well documented enough by now to consider this still an issue.

There's also the [How-to-build-software-outside-Homebrew-with-Homebrew-keg-only-dependencies](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-build-software-outside-Homebrew-with-Homebrew-keg-only-dependencies.md) document that talks about `PKG_CONFIG_PATH` and touched upon in the [FAQ](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md#what-does-keg-only-mean).

I'll re-open if anyone protests, but I don't know if there's much more on our side to do here.
