### ISSUE TITLE
GTK+ searches for modules in the wrong path

### ISSUE THREAD

**Issue by philippelatulippe** [Homebrew/homebrew#21412]
I installed the package gtk-engines so that GTK applications installed with homebrew don't look ugly, but GTK searches for modules in its Cellar path.  Of course, the engines from the gtk-engines package are not present at that path.

The simplest fix is to set libdir to #{HOMEBREW_PREFIX}/lib when calling configure, but I'm not sure if that's acceptable.

See #11445, which has more details and a link to the code that determines the search path.

**Comment by ipeacocks** [comment]
@DomT4 

Tried to export variable in such way:

export GTK_PATH=/usr/local/lib/gtk-2.0

And everything is cool now. Thank you!

**Comment by mikemcquaid** [comment]
I'm closing this out as people seem to have various solutions and Homebrew itself probably doesn't want to change the current behaviour.
