### ISSUE TITLE
Ctrl-C while installing confuses the install script

### ISSUE THREAD

**Issue by Ahti** [Homebrew/homebrew#23557]
I just tried to install brew on a new machine. While it was doing the git checkout (`Downloading and Installing Homebrew...`), I noticed the network was way to slow, so I killed the installation with Ctrl-C.

After I fixed the network and re-tried to install brew, the installer script told me brew seemed to be installed already.

The installer script should catch being aborted and clean up after itself when this happened.

(Am I to blind to find it or is that script not under version control?)

**Comment by jacknagel** [comment]
This issue was moved to Homebrew/install#11
