### ISSUE TITLE
Add an option to brew upgrade (and/or brew reinstall) to reinstall dependencies

### ISSUE THREAD

**Issue by aaronadamsTO** [Homebrew/homebrew#23649]
The OS X 10.9 Mavericks upgrade has left my Homebrew setup in an annoying state; every time I try to upgrade something, the libstdc++/libc++ issue repeatedly rears its ugly head, notifying me of yet another dependency that needs `brew reinstall`.

Ideally, there would be some way for me to tell Homebrew to handle this for me, rather than individually reinstalling dependency after dependency.

Keeping in mind that I'm only an end user of Homebrew, and therefore not terribly familiar with the dark magic that makes it work so wonderfully, it seems to me there would be two potential approaches to ease the pain:

1. Add a `--reinstall-dependencies` option to `brew upgrade`. Ideally this would only reinstall the dependencies that actually need reinstalling, but I don't know how realistic this is.
2. Add a `--recursive` option to `brew reinstall`.

These do seem like somewhat useful functions for more than just this situation, so hopefully they merit some consideration.

**Comment by mikemcquaid** [comment]
I'm passing on this feature request; I think we've got a lot better at avoiding this being needed and you can always just uninstall and reinstall all your formula with `brew bundle` now.
