### ISSUE TITLE
gsettings-desktop-schemas crashes under current configure options

### ISSUE THREAD

**Issue by ohookins** [Homebrew/homebrew#26455]
gsettings-desktop-schemas (version tested: 3.10.1) currently crashes when configured with the option included in the formula: ```--disable-schemas-compile```. It also causes apps dependent on it (for example gst-inspect from gstreamer) to crash. For example:

```
$ gst-launch-1.0 souphttpsrc location="http://localhost:5644/hello.mp3" ! testsink
Setting pipeline to PAUSED ...

(gst-launch-1.0:13833): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
Trace/BPT trap: 5

$ gsettings list-schemas
Segmentation fault: 11
```

When the ```--disable-schemas-compile``` configure option is removed, the problem goes away:

```
$ gsettings list-schemas
org.gnome.desktop.privacy
org.gnome.desktop.notifications
org.gnome.desktop.default-applications
org.gnome.desktop.datetime
...
<many more>
```

gst-launch from gstreamer is also now working for me. Unfortunately I don't know the history of this option to decide whether it was required for some reason, so I'll leave that up to a Homebrew maintainer.

**Comment by bfontaine** [comment]
Is this still an issue?

**Comment by DomT4** [comment]
Closing because there's been no update here for a very long time, ever after Baptiste's ping. If it's still an Issue please feel free to shout.
