### ISSUE TITLE
Postgis sql files not found

### ISSUE THREAD

**Issue by springmeyer** [Homebrew/homebrew#26604]
OS X 10.9, updated homebrew, freshly installed postgres/postgis.

```
$ brew --prefix
/Users/dane/.homebrew
```

The `create EXTENSION postgis;` fails with:

```
ERROR:  could not open extension control file "/Users/dane/.homebrew/Cellar/postgresql/9.3.2/share/postgresql/extension/postgis.control": No such file or directory
```

Something appears broken with the manual moving of files after installing to DESTDIR.

I can fix the build if I change [this line](https://github.com/Homebrew/homebrew/blob/2ff6ebd89f524530d1823501291f0a9aa7a799ff/Library/Formula/postgis.rb#L62):

```diff
-   system 'make', 'install', "DESTDIR=#{buildpath}/stage"
+   system 'make', 'install'
```

**Comment by clhenrick** [comment]
was this ever resolved? I'm also running into the same issue as @springmeyer with PostgreSQL 9.4.3 and PostGIS 2.1.7_1

**Comment by springmeyer** [comment]
@clhenrick I think there are a few factors that can cause this that are potentially both in play in reports above:

 - one is that brew by default does some fancy symlinking/fancy moving of files that may lead to an incomplete install. 
 - another is that as of PostGIS 2.0 the install of PostGIS will seem to succeed but the control file will not have been created or installed. This is because PostGIS only generates th control file if raster support is enabled (if GDAL can be found). So not building with raster support will mean that your PostGIS install will not support the 'create extension' syntax although the majority of the rest of PostGIS will work.

**Comment by springmeyer** [comment]
more details: http://trac.osgeo.org/postgis/ticket/3027. To recap: make sure your gdal install is working and PostGIS is built against it.

**Comment by hahla** [comment]
I was able to install postgis and I did not manually install gdal previously. It clearly does show up in my postgis version though so maybe something auto-installed it as a dependency when I brew installed postgis? 

postgres: 9.4.1
gis=# SELECT PostGIS_full_version();
 POSTGIS="2.1.5 r13152" GEOS="3.4.2-CAPI-1.8.2 r3921" PROJ="Rel. 4.8.0, 6 March 2012" GDAL="GDAL 1.11.1, released 2014/09/24" LIBXML="2.9.2" LIBJSON="UNKNOWN" TOPOLOGY RASTER

**Comment by mikemcquaid** [comment]
> was this ever resolved? I'm also running into the same issue as @springmeyer with PostgreSQL 9.4.3 and PostGIS 2.1.7_1

No, it seems not.

**Comment by robe2** [comment]
@hahla  when you installed, were you able to do it with 

```
CREATE EXTENSION postgis;

```

or did you have to resort to using the contrib/postgis scripts?

If you have GDAL, then the extension scripts should have been installed too.  If they didn't the only other culprit I can think of is the doc/*_comments.sql files that get packaged in as part of the extension build and I think if it can't find them extension build fails or doesn't try.  

The postgis tar balls have the doc/*_comments.sql files pre-built which get packaged into the extension install files.  So if you built from tar ball, you wouldn't need xsltproc, but if you built from SVN and don't have XSLTPROC available or for some reason the tar you have didn't include those files, then extension install will probably fail as well.

**Comment by ZachLiuGIS** [comment]
I think I run into a similar situation if not exactly the same. PostGIS will force install postgresql 9.4.4 when the machine is running 9.4.3, and postgis will not be installed in 9.4.3. 

I have to delete the whole 9.4.3 and reinstall to 9.4.4 to get it right.

**Comment by mikemcquaid** [comment]
To fix these `postgis` needs to be modified to instead be an option on the `postgresql` formula. We'll review a PR.

**Comment by lanrion** [comment]
Same to me, I install without brew:
```sh
$ wget http://download.osgeo.org/postgis/source/postgis-2.1.6.tar.gz
$ tar zxvf postgis-2.1.6.tar.gz
$ cd postgis-2.1.6
$ ./configure --with-pgconfig=/usr/local/bin/pg_config --with-geosconfig=/usr/local/Cellar/geos/3.4.2/bin/geos-config --with-projdir=/usr/local/Cellar/proj/4.9.2
$ make 
$ make install
```

**Comment by DomT4** [comment]
Pretty sure we fixed this recently with the `postgresql` sandbox-related PR. Feel free to shout at me if that wasn't the case.

**Comment by rreusser** [comment]
@DomT4 can you clarify how the fix solves this? If I `brew update` and start uninstalling and reinstalling postgres/postgis, is it expected to magically work? It's not a business-critical query for us, so I'm weighing the pros and cons of just using elasticsearch instead.

**Comment by DomT4** [comment]
There should be no noticeable changes for end users, as far as I'm aware. The changes were mostly packaging orientated. @xu-cheng wrote the PR and changes involved and may be able to comment further.
