### ISSUE TITLE
Create a way to easily uninstall Homebrew

### ISSUE THREAD

**Issue by jackiekazil** [Homebrew/homebrew#28174]
I recently had a lot of issues with the upgrade to Maverick on Mac. See https://github.com/Homebrew/homebrew/issues/28165#issuecomment-39637802. 

Having a way to cleanly uninstall Homebrew would have been nice. 
Instead I followed the instructions here: http://superuser.com/a/203740

If someone wants to come along and close this ticket, I will be okay with it. It just seemed like something that others would be interested in. I do not follow the dev of homebrew closely enough, so I don't know that I am the best person to make that decision.

**Comment by jacknagel** [comment]
There's an uninstall script in the homebrew-install repo now.

**Comment by jackiekazil** [comment]
:star2: :clap: :clap: :clap: :star2:
