### ISSUE TITLE
Nodenv variant

### ISSUE THREAD

**Issue by maxnordlund** [Homebrew/homebrew#28955]
There are two mayor variants of the nodenv script/handler, [OiNutters][1] and [wfarrs][2]. Currently the [wafarr][2] variant is in homebrew, see #28830. This is also the variant used by [Boxen][3]. However, it hasn't been updated in a year, unlike [OiNutter][1] who updated 13 days ago at the time of this writing.

I believe both should be in homebrew, but the [OiNutters][1] variant being the default since it's actively being worked upon. Perhaps [wfarrs][2] variant could be renamed to something like `nodenv-boxen` or `boxen-nodev`. Another possiblility is to put it in [homebrew-versions][4]. Either way, it'll be good to have a discussion about this so future people wondering why X was chosen over Y knows the reasons.

[1]: /OiNutter/nodenv
[2]: /wfarr/nodenv
[3]: /boxen/puppet-nodejs
[4]: /Homebrew/homebrew-versions

**Comment by jasonkarns** [comment]
> I'm fine with this change, personally.

It appears that both @wfarr and @OiNutter are okay with this change? (to make @OiNutter 's variant the default and give @wfarr 's variant a different name). I realize that everyone involved would like to see @OiNutter 's variant be updated to support precompiled binaries. However, I don't think precompiled-binaries should be a blocker for moving forward with the rename/change-default-formula. Granted, it's slightly annoying that each install of node now requires a full compile, but I think it's *more* harmful to the homebrew/nodenv community that the name confusion continue for much longer.

I would like to see the rename occur ASAP and let work continue in parallel for adding precompiled-binary support to @OiNutter 's variant. There is already a https://github.com/OiNutter/node-build/issues/11 for getting precompiled binary support into node-build.

**Comment by mikemcquaid** [comment]
> It appears that both @wfarr and @OiNutter are okay with this change?

Sorry, I'm maybe being stupid but is there a citation for `wfarr` saying this somewhere?

**Comment by jasonkarns** [comment]
@mikemcquaid https://github.com/Homebrew/homebrew/issues/28955#issuecomment-45901207

> I'm fine with this change, personally.

**Comment by i-c** [comment]
It sounds like there's consensus from both project owners about this - so should the change be made, then?

**Comment by mikemcquaid** [comment]
Yes, I'm OK with this. Can someone open a PR? Thanks!

**Comment by jasonkarns** [comment]
I can open a PR to swap @wfarr 's version with @OiNutter's. But what should happen to @wfarr's version? Renamed? Moved to one of the homebrew taps?

(And per @wfarr 's concern above, we have just deployed binary-installation support!)

**Comment by mikemcquaid** [comment]
@jasonkarns It can be left as-is; it's fine for us to just change the version. If you can open a PR that'd be good.

**Comment by jasonkarns** [comment]
@mikemcquaid pr here #45578

**Comment by jasonkarns** [comment]
This can be closed now (by #45576)
