### ISSUE TITLE
cmake builds fail on CLT-only with --env=std

### ISSUE THREAD

**Issue by jacknagel** [Homebrew/homebrew#29101]
```
==> cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/avro-cpp/1.7.6 -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
-- The C compiler identification is Clang 5.1.0
-- The CXX compiler identification is Clang 5.1.0
CMake Error at /usr/local/Cellar/cmake/2.8.12.2/share/cmake/Modules/Platform/Darwin.cmake:211 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.9' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/2.8.12.2/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:37 (project)


-- Configuring incomplete, errors occurred!
See also "/tmp/avro-cpp-ey0P/avro-cpp-1.7.6/CMakeFiles/CMakeOutput.log".
```

Digging into it, cmake assumes that if `MACOSX_DEPLOYMENT_TARGET` is set, then the corresponding SDK is present.

We set `MACOSX_DEPLOYMENT_TARGET` in stdenv, but I don't know that it's actually necessary. We never set it in superenv.

**Comment by luzpaz** [comment]
Perhaps this is the problem:
If one is on 10.10 then they should have a 10.10 SDK installed. But Xcode 7.1 installs a 10.11 SDK. You can see that by invoking: 
```
🍎 Test:Desktop blah$ ls /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
MacOSX10.11.sdk/
 ```

**Comment by mikemcquaid** [comment]
@luzpaz Do you experience it without `--env=std`?

**Comment by luzpaz** [comment]
@mikemcquaid I have no idea. are you saying that i should try to ```cmake --env=std``` ?

**Comment by mikemcquaid** [comment]
No, I'm saying unless you're using `brew instal --env=std` then it's not the same problem. If it's not the same problem: please create a new issue.

**Comment by luzpaz** [comment]
Apologies. I'll make a new issue

**Comment by ilovezfs** [comment]
This is still happening on 10.11.3: https://github.com/Homebrew/homebrew/issues/40401#issuecomment-187643549

**Comment by mikemcquaid** [comment]
Closing this out as I don't think we want or need to support `--env=std` for formulae that work with superenv.
