### ISSUE TITLE
Varnish with config files

### ISSUE THREAD

**Issue by andreasemer** [Homebrew/homebrew#29754]
I have installed Varnish https://github.com/Homebrew/homebrew/blob/master/Library/Formula/varnish.rb with "brew install varnish" after updating my brew repo with "brew update". After a successfull installation i was expecting configuration options under "/usr/local/etc/varnish", but my etc folder is without an varnish folder. 

I can reprouce this also on another osx mashine. (both OSX Mountain Lion)

Is there a issue in the brew formula, or do i something wrong?

**Comment by jmrepetti** [comment]
I was having this error when trying to install Varnish 4.0.2:

    raise ValueError, 'unknown locale: %s' % localename
    ValueError: unknown locale: UTF-8
    make[1]: *** [varnishd.1] Error 1
    make[1]: *** [varnishhist.1] Error 1
    make: *** [install-recursive] Error 1

The error was fixed after setting this env variables:

    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8

**Comment by jmagnusson** [comment]
Anyone?

**Comment by AnastasiaSulyagina** [comment]
Tried to reproduce this issue on OSX 10.11.3 with varnish 4.1. 
Ran "brew install varnish", file "/usr/local/etc/varnish/default.vcl" was successfully created. Also no problems after deleting file and reinstalling varnish (reinstall and reinstall --build-from-source). 
Guess the issue can be closed.

**Comment by DomT4** [comment]
Looks like it was resolved by https://github.com/Homebrew/homebrew/commit/24714135. Nice work hunting that down @AnastasiaSulyagina; these old Issues can tend to get left behind even when the problem has been solved.

**Comment by mikemcquaid** [comment]
Thanks @AnastasiaSulyagina!
