### ISSUE TITLE
UnitTest++ doesn't pass unit tests

### ISSUE THREAD

**Issue by laurent22** [Homebrew/homebrew#29937]
Building UnitTest++ fails at it seems it cannot pass its own unit tests:

    Running unit tests...
    :107: error: Failure in test: Expected 2 but was 0
    FAILURE: 1 out of 174 tests failed (1 failures).

Unfortunately the error message doesn't specify the file where the test is failing so I wasn't able to fix it. I don't know if this is just on my machine or if it's a recent update of OSX or XCode that broke it (since the lib hasn't been updated in 6 years it's possible).

Full gist here: https://gist.github.com/anonymous/3b0f65899054cfe2e771

**Comment by adamv** [comment]
If a 1.5 release becomes available we can update to it; closing this ticket in the meanwhile.
