### ISSUE TITLE
byobu: Python crashes when executing the program on 10.9

### ISSUE THREAD

**Issue by peppelakappa** [Homebrew/homebrew#30252]
While installing from the standard formula goes well, running byobu leads to Python crashes, probably related to the inability to import the `snack` module, with a window saying that Python has crashed.

Trying to import the module into the Python shell, the output is:

    >>> import snack
    Fatal Python error: PyThreadState_Get: no current thread
    [1]    86923 abort      python

With the crash window appearing again.

[Here's](https://gist.github.com/anonymous/56972eb8a5fc0d3bf0a5) the output of `brew gist-logs --config --doctor byobu`.

**Comment by isamuelson** [comment]
any news on this fix?

**Comment by isamuelson** [comment]
I believe i found the problem with the newt package. if someone can help out on a patch that will be great.... https://github.com/Homebrew/homebrew/issues/36256

**Comment by jacknagel** [comment]
@tdsmith can you tell if there is something Homebrew should address here, or...?

**Comment by tdsmith** [comment]
Yeah, libnewt links with flags from python-config which means it gets -lpython.

**Comment by tdsmith** [comment]
`brew update && brew upgrade` should resolve this issue for anyone still experiencing it.

**Comment by primedirective** [comment]
I'm on 10.10 and just ran into this. Update and upgrade did not help the situation. As far as I can tell, https://github.com/Homebrew/homebrew/blob/master/Library/Formula/byobu.rb still is referencing `newt --with-python`

**Comment by tdsmith** [comment]
Yes, that's correct. If brew reinstall newt doesn't resolve for you, can you open a new issue with more details about the crash you're experiencing and the output of `brew gist-logs newt` and `otool -L` run against the _snack.so that newt installs? `brew ls -v newt` will tell you where to find it. Thanks!
