### ISSUE TITLE
protobuf-c needs c++11 option

### ISSUE THREAD

**Issue by scpeters** [Homebrew/homebrew#30320]
I just installed protobuf with c++11 support and then installed protobuf-c, which was bottled. I received a warning that protobuf-c was built with a different C++ standard library:
~~~
$ brew install protobuf --c++11
…
$ brew install protobuf-c
…
==> Pouring protobuf-c-0.15.mountain_lion.bottle.tar.gz
Warning: protobuf-c dependency protobuf was built with a different C++ standard
library (libc++ from clang). This could cause problems at runtime.
~~~
That warning is surprising since protobuf-c does not have any c++ code, and its library doesn't link against libc++ or libstdc++:
~~~
$ otool -L /usr/local/Cellar/protobuf-c/0.15/lib/libprotobuf-c.dylib 
/usr/local/Cellar/protobuf-c/0.15/lib/libprotobuf-c.dylib:
	/usr/local/lib/libprotobuf-c.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
~~~

**Comment by mikemcquaid** [comment]
@scpeters Was there ever any update on this? If you no longer care: feel free to close this out. Thanks!

**Comment by scpeters** [comment]
It was probably only relevant on mountain lion and earlier. Closing.
