### ISSUE TITLE
installer recommends removing entire cellar when homebrew is already installed

### ISSUE THREAD

**Issue by shamansir** [Homebrew/homebrew#30450]
When you already have _brew_ installed and try to run `ruby -e $(curl ..../install)`, it says:

```
It appears Homebrew is already installed. If your intent is to reinstall you
should do the following before running this installer again:
    rm -rf #{HOMEBREW_PREFIX}/Cellar #{HOMEBREW_PREFIX}/.git && brew cleanup
```

Which actually substitutes to `/usr/local/Cellar`, at least at my system, and if user performs it, the most of _brew_-installed soft-links in `/usr/local/bin` become totally not reachable (even after the "proper" re-installation of _brew_). It also may silently kill python and some pretty important stuff for system functionality like `automake`, `openssl` or any kind of VCS-s, installed with _brew_.

For example, it may kill [`fish`](http://fishshell.com) shell out of the system and you can't start Terminal again, since it suicides with `login: /usr/local/bin/fish: No such file or directory`. Yes, if user is smart enough to re-install brew from command line, he will find a Terminal settings and replace a shell path with, i.e., `/bin/bash`, but I suppose anyway it's not the very best and kind advice from any installer in general. 

So, as a suggestion, at least the installer should hardly remind user that all brew-related software will become inaccessible after the execution, and (it will be even more careful with respect to user) to provide her/him the list of binaries which (s)he will kill with this command, and even more polite will be to store that list in some temporary file in user home-directory and suggest user to re-install all of this with new version of _brew_ automatically.

P.S. I was required to reinstall _brew_ because previous _brew_ version broke due to Xcode console tools update.

**Comment by jacknagel** [comment]
This issue was moved to Homebrew/install#12
