### ISSUE TITLE
Need a method to remove crontab entry on uninstall

### ISSUE THREAD

**Issue by raggi** [Homebrew/homebrew#30546]
See https://github.com/raggi/homebrew-ale/issues/1.

The formula in question is: https://github.com/raggi/homebrew-ale/blob/master/openssl-osx-ca.rb

There may also be a better way to install a periodic job that homebrew is "aware of", if so, please advise.

**Comment by ChicagoDev** [comment]
Considering the annoying script is running every hour, I don't see much harm in adding an additional small cronjob and script. The script would check if openssl was uninstalled. If it is uninstalled, delete the annoying emailing cron job. Then it would need to delete the removal cronjob and the executing script itself. This isn't a fully implemented solution, but I wrote it quickly to get the point across and to get your feedback. What do you think? 

    #!/bin/bash
    # The skeleton of a script which checks to see if brew's openssl was uninstalled. If it was uninstalled,
    # remove the cron job which sends the buggy email every hour. Additionally remove the cronjob which will be
    # running this script itself.
    if [ -f /usr/local/Cellar/openssl-osx-ca/1.0.3/bin/openssl-osx-ca]
    then
            exit 0
    else
            (crontab -l | grep -v openssl-osx-ca) | crontab -
            #(crontab -l | grep -v remove-openssl-cronjob | crontab -
            rm $remove-openssl-cronjobPATH/remove-openssl-cronjob.sh
            exit 0
    fi

**Comment by raggi** [comment]
I'd still like a better recommendation.

**Comment by mikemcquaid** [comment]
Symlink the cronjob to something inside the Cellar which means when the formula goes away so does the cronjob.

**Comment by raggi** [comment]
@mikemcquaid on darwin, from userspace, I've read the man pages. I must be missing something, how can I achieve this?

**Comment by mikemcquaid** [comment]
@raggi I'm afraid this is beyond the scope of Homebrew itself and I don't really have time to flesh out a detailed solution. Sorry!

**Comment by raggi** [comment]
Hardly seems that out of scope. No one has come up with a working solution. You've told me there is one, but I can't see it.

**Comment by mikemcquaid** [comment]
@raggi I'm saying it's possible but I don't have the time to dig in and work out what to do. Sorry.

**Comment by raggi** [comment]
Twoddle.
