### ISSUE TITLE
.gitignore error for others in same group

### ISSUE THREAD

**Issue by roryk** [Homebrew/homebrew#30710]
We use homebrew as one of the automated installers for tools and we'd like to allow anyone in a group to be able to update the tools. If I chgrp -R the homebrew directory to the group, when anyone other than me tries to update, they get an Operation not permitted error on the .gitignore file. For example:

```
[localhost] local: /opt/bcbio/local/bin/brew update
Error: Operation not permitted - /opt/bcbio/local/Library/Formula/.gitignore
```

Do you have any suggestions for using homebrew as part of a group instead of an individual user?

Thanks!

**Comment by xu-cheng** [comment]
This should be fixed now, since `Library/Formula/.gitignore` doesn't exist anymore.

**Comment by roryk** [comment]
Thank you!
