### ISSUE TITLE
Issue with readline 6.3.6

### ISSUE THREAD

**Issue by vsbuffalo** [Homebrew/homebrew#30751]
I discovered a rather annoying bug with the the [readline 6.3.6 library](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/readline.rb) — the current homebrew version. I have submitted this to the readline bug mailing list. However, given how important readline is to many Homebrew packages (R, Python, etc.) I think it would be wise to roll readline back to a past version until a patch is made. 

Here is the issue: in both iTerm2 and Terminal, resizing a window containing any interactive process with readline will cause text to wrap over itself on the next line. This is an incredibly irritating behavior, especially for R users that often enter long lines interactively. At first I thought this might be a shell or terminal issue, but as mentioned this happens in both terminals. Downgrading to 6.2.4 with the following (and then recompiling R and Python to use this version) solves the issue:

    brew install https://raw.githubusercontent.com/Homebrew/homebrew/4237ea1c2c4c10a4c5288d11c0f0311e97f30473/Library/Formula/readline.rb

I have made a video of the issue here: https://www.youtube.com/watch?v=A9tvPhehB-0

**Comment by jacknagel** [comment]
I don't think this will be addressed unless someone takes initiative and raises this issue upstream again. The original report was in July, I don't think the readline dev will come back to it without some prompting.

**Comment by jbiel** [comment]
+1

**Comment by vsbuffalo** [comment]
I have just emailed the readline list again. Thanks for the reminder @jacknagel—

**Comment by jbiel** [comment]
FWIW I've tested the latest readline (6.3 patch 8) and the issue still occurs.

**Comment by vsbuffalo** [comment]
Here's an update: http://lists.gnu.org/archive/html/bug-readline/2015-04/msg00005.html

and this is a great overview of what's going on: http://lists.gnu.org/archive/html/bug-readline/2015-03/msg00012.html

**Comment by luzpaz** [comment]
bump

**Comment by mikemcquaid** [comment]
I'm closing this out as it's an upstream readline issue and not a Homebrew one we can really do anything about.

@luzpaz Please avoid "bump" comments; they don't achieve anything except email a bunch of people who already get too much email.
