### ISSUE TITLE
Feature request: brew install --minimal-dependencies

### ISSUE THREAD

**Issue by davidchall** [Homebrew/homebrew#31158]
I think it would be very useful to have a new option:

    brew install [formula] --minimal-dependencies

This would ignore dependencies which are `:recommended`. The effect would be somewhere between `--ignore-dependencies` and no option. This would be useful in automating build tests.

Thanks, David

**Comment by bfontaine** [comment]
Could you try a pull-request? Thanks!

**Comment by bfontaine** [comment]
Ping?

**Comment by mikemcquaid** [comment]
Passing on this.
