### ISSUE TITLE
mariadb: missing /usr/local/etc/my.cnf.d, removed by brew prune

### ISSUE THREAD

**Issue by ActionScripted** [Homebrew/homebrew#31760]
When installing MariaDB and trying to start things via `mysql.server start` the following error is returned:

```
mysql.server start
/usr/local/Cellar/mariadb/10.0.13/bin/my_print_defaults: Can't read dir of '/usr/local/etc/my.cnf.d' (Errcode: 2 "No such file or directory")
Fatal error in defaults handling. Program aborted
Starting MySQL
. ERROR!
```

Debug info: https://gist.github.com/ActionScripted/cc9f6b83f0b55239833b

The fix is to manually create the directory:

```
mkdir /usr/local/etc/my.cnf.d
```

And things work great! However if you run `brew prune` it removes this directory and you have to manually create it again. I'm not sure if the issue is `brew prune` dropping an empty directory or `mkpath` in the formula removing things or what.

I've completely removed mariadb, cleaned things up and reinstalled to see if maybe something got weird on my system but it's always the same issue. If there's anything I can do to help or any other information I can contribute that would be useful I'd be glad to help.

**Comment by vkolodrevskiy** [comment]
Btw where's my.cnf file located in Yosemite?

**Comment by ActionScripted** [comment]
@ricardo85x 

The brew doctor errors don't seem to be MariaDB specific as they reference things like `mcrypt` and `sqlite` which aren't part of MariaDB. You can check MariaDB dependencies via `brew deps mariadb`. It's possible that there is something going on outside of MariaDB with your homebrew setup that is leading to issues with MariaDB.

@vkolodrevskiy 

Depending on what you've done on your system these are the places it/they could be:

* `/usr/local/etc/my.cnf` (homebrew default)
* `/etc/my.cnf`
* `/etc/mysql/my.cnf`
* `~/.my.cnf`

It's probably at `/usr/local/etc/my.cnf` and I'm not sure that this is Yosemite-specific.

**Comment by ActionScripted** [comment]
Another fix for my original issue is to edit `/usr/local/etc/my.cnf` and remove or comment out the line looking for `/usr/local/etc/my.cnf.d`.

**Comment by vkolodrevskiy** [comment]
@ActionScripted

I've got folder /usr/local/etc/my.cnf.d/
Does it mean I need to copy one of *.cnf files from /usr/local/Cellar/mariadb/support-files e.g my-medium.cnf and rename it as my.cnf under that folder?

**Comment by ActionScripted** [comment]
@vkolodrevskiy 

`/usr/local/etc/my.cnf.d/` can be empty and `/usr/local/etc/my.cnf` is mostly empty by default except for an include directive for `/usr/local/etc/my.cnf.d/`

Are you getting any errors when you try to start MariaDB? Can you try doing a full reload as mentioned in `brew info mariadb`?

    launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.mariadb.plist
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mariadb.plist

**Comment by denji** [comment]
```
$ tree /etc/mysql
/etc/mysql
├── conf.d
│   ├── mariadb.cnf
│   ├── mysqld_safe_syslog.cnf
│   └── tokudb.cnf
├── debian.cnf
├── debian-start
└── my.cnf
```

my.cnf -> /usr/local/etc/my.cnf
/etc/mysql/conf.d/{mariadb,mysqld_safe_syslog,tokudb}.cnf

**Comment by patrickomeara** [comment]
Had this trouble updating to El Capitan from Yosemite. 

`mkdir /usr/local/etc/my.cnf.d` fixed the issue

**Comment by BookOfGreg** [comment]
Should this issue be closed?
I ran into this issue today where maria would mysteriously not load, no output from launchctl.
Only when I ran `mysqld --verbose --help` did it start saying 
```
/usr/local/Cellar/mariadb/10.1.14/bin/my_print_defaults: Can't read dir of '/usr/local/etc/my.cnf.d' (Errcode: 2 "No such file or directory")
Fatal error in defaults handling. Program aborted
Usage: mysql.server  {start|stop|restart|reload|force-reload|status|configtest|bootstrap}  [ MySQL server options ]
```
Fixed by `mkdir /usr/local/etc/my.cnf.d` but also fixed by removing the include line in `my.cnf`

**Comment by nmarley** [comment]
I got this issue today also, after a ```brew prune```. These band-aid fixes technically work (e.g. re-creating the dir), but they don't solve the root problem, so I don't think this should be closed.

For a more permanent fix for this issue, the ```brew prune``` command needs to stop removing this directory (or whatever the correct solution would be). But this shouldn't be closed just because band-aid fixes exist. This issue will continue to pop up for people until a real solution is found.
