### ISSUE TITLE
Error: 407 "Proxy Authentication Required" when brew search ...

### ISSUE THREAD

**Issue by kkdd** [Homebrew/homebrew#32041]
Hello,
"brew search ..." causes
```Error: 407 "Proxy Authentication Required" ```
behind through our proxy environment with authentication as follows:

https://gist.github.com/kkdd/fa9dc816973b4e20ee9f

```
$ brew search gcc
gcc
Error: 407 "Proxy Authentication Required"
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:119:in `error!'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:128:in `value'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:913:in `connect'
:
:
:
```

The following are environment variables:
```
$ env |grep proxy 
http_proxy=http://username:password@proxy.example.com:8080
ftp_proxy=http://username:password@proxy.example.com:8080
https_proxy=http://username:password@proxy.example.com:8080
```

**Comment by brunobatista** [comment]
+1

**Comment by ryber** [comment]
Rather than having to parse the environmental variable Would it be OK to add a .homebrewrc file where you could keep the individual params (url, username and password). I know it's not ideal and yet another thing that doesn't just use http_proxy but it would be a better alternative to hacking ruby classes.

**Comment by mikemcquaid** [comment]
Sorry, we're not going to add a `.homebrewrc` file but may consider environment variables for configuration.

**Comment by ryber** [comment]
How would you see that working? Keep http_proxy for the main url and then support http_proxy_username and_password? Or parse the original http_proxy for the params? 

I'm willing to issue a pull request to get this resolved, curious on what direction you guys might be looking for,

One advantage to the individual params is you could support some kind of encryption for the password, although what that might be I don't know?

**Comment by mikemcquaid** [comment]
@ryber I don't think encryption is necessary; environment variables are reasonably secure. I'd just have individual params. Thanks!

**Comment by jackmaney** [comment]
@kkdd: Thanks! That hack worked like a charm. For reasons I don't understand, Homebrew has only recently thrown this error.

**Comment by crd** [comment]
For others who experience this issue but don't want to try hacking ruby:

Alternatively, run a local proxy like cntlm or squid and let it handle the authentication with your upstream proxy. If this sounds daunting [squidman] (http://squidman.net/squidman/) is pretty foolproof.

**Comment by mikemcquaid** [comment]
Closing this out as a feature request but we'd review a PR to improve this.
