### ISSUE TITLE
chicken installs egg programs in an inaccessable place

### ISSUE THREAD

**Issue by eraserhd** [Homebrew/homebrew#32398]
If I use `chicken-install` to install an egg which has command-line tools, (e.g. `salmonella`), the tools are installed into `/usr/local/Cellar/chicken/4.9.0.1/bin`, which doesn't help.

Temporary solution is to `brew unlink chiken && brew link chicken`, which feels icky.

I'm not sure how to fix.  Ideas?

**Comment by bfontaine** [comment]
@jacknagel Would wrapping the real `chicken-install` in a script be an acceptable (hacky) solution?

Something like:

```bash
#!/bin/bash
real-chicken-install -prefix /usr/local $*
```

If it’s symlinked as `bin/chicken-install` it then works as expected:

```bash
# installs with -prefix /usr/local
chicken-install salmonella

# install with another prefix (override the first one)
chicken-install -prefix /foo salmonella
```

**Comment by mikemcquaid** [comment]
This is something we'd accept a pull request to improve but probably needs fixed in the software itself.
