### ISSUE TITLE
Cassandra 2.1.0 is not launching

### ISSUE THREAD

**Issue by schrepfler** [Homebrew/homebrew#32488]
I'm getting a strange error if I launch cassandra

/usr/local/opt/cassandra/bin/cassandra -f
objc[10370]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Error opening zip file or JAR manifest missing : /usr/local/Cellar/cassandra/2.1.0/jamm-0.2.5.jar
Error occurred during initialization of VM
agent library failed to init: instrument

the jamm version in the distro is jamm-0.2.6 however so I'm not sure where is 0.2.5 coming from, perhaps from pervious launcher?

**Comment by darkaico** [comment]
thanks @hellysmile works your solution on my environment!

**Comment by cemmersb** [comment]
Since I came across the same issue with the latest update, I made a simple grep to find out which config files may be affected. The following list seems to be complete:
```
/usr/local/etc/cassandra/cassandra-env.ps1
/usr/local/etc/cassandra/cassandra-env.ps1.default
/usr/local/etc/cassandra/cassandra-env.sh
```
Could we filter the version number during the brew install and replace it with the great `*` regex solution which seems to be working just perfectly fine?

**Comment by mikemcquaid** [comment]
Someone needs to submit a pull request.

**Comment by DomT4** [comment]
We'll take a PR here if this is still relevant, Thanks!

**Comment by sankalpanand** [comment]
That worked for my Mac as well. Thanks.
