### ISSUE TITLE
autossh '-f' option does not work

### ISSUE THREAD

**Issue by anagogue** [Homebrew/homebrew#32599]
Autossh builds and installs without issue. It then works as expected with one exception: the `-f` option, which is meant to put autossh into the background before calling ssh, causes further command parsing to cease. Ssh is never called. This happened for me (running OS X 10.8.5, even after fixing most brew doctor issues and reinstalling autossh) and to a colleague (who set up a brand new Mac, installed homebrew and then installed autossh).

Here is comparison output, with `AUTOSSH_DEBUG` enabled for the same command with and without the `-f`.

No `-f`:
```
autossh -M0 -q -N -o "ServerAliveInterval 60" -o "ServerAliveCountMax 3" -i id_rsa -R 10022:localhost:22 user@host
Sep 24 10:31:00 alt.local autossh[3852] <Info>: port set to 0, monitoring disabled
Sep 24 10:31:00 alt.local autossh[3852] <Debug>: checking for grace period, tries = 0
Sep 24 10:31:00 alt.local autossh[3852] <Info>: starting ssh (count 1)
Sep 24 10:31:00 alt.local autossh[3852] <Info>: ssh child pid is 3853
Sep 24 10:31:00 alt.local autossh[3852] <Debug>: check on child 3853
Sep 24 10:31:00 alt.local autossh[3852] <Debug>: set alarm for 600 secs
Sep 24 10:31:00 alt.local autossh[3853] <Debug>: execing /usr/bin/ssh
```

ps ax | grep ssh:
```
3992 s001  S+     0:00.00 autossh -M0 -q -N -o ServerAliveInterval 60 -o ServerAliveCountMax 3 -i id_rsa -R 10022:localhost:22 user@host
3993 s001  S+     0:00.03 /usr/bin/ssh -q -N -o ServerAliveInterval 60 -o ServerAliveCountMax 3 -i id_rsa -R 10022:localhost:22 user@host
```

Adding in `-f`:
```
autossh -M0 -f -q -N -o "ServerAliveInterval 60" -o "ServerAliveCountMax 3" -i id_rsa -R 10022:localhost:22 user@host
Sep 24 10:32:19 alt.local autossh[3895] <Info>: port set to 0, monitoring disabled
```

ps ax | grep ssh:
```
4060   ??  Ss     0:00.02 autossh -M0    -q -N -o ServerAliveInterval 60 -o ServerAliveCountMax 3 -i id_rsa -R
```
So autossh runs either way, but command parsing gets screwed up, and further action never gets taken when using `-f`. Must manually kill -9 to get rid of the autossh process that's just sitting there doing nothing.

Gist: https://gist.github.com/anonymous/51f87d1568c9f7b50d10

**Comment by Habbie** [comment]
autossh is at 1.4e now in brew - still broken for you when brewed?

**Comment by DomT4** [comment]
Closing as dead. Please feel free to ping if this is still an issue.
