### ISSUE TITLE
rubber stops prematurely after running bibtex (patch available)

### ISSUE THREAD

**Issue by reidpr** [Homebrew/homebrew#32616]
This bug is for formula `rubber.rb`.

`rubber` stops prematurely after running `bibtex` because it uses a full path, which confuses `bibtex`. Under the hood, what is happening is roughly this:

```
$ bibtex /foo/bar/mydoc

bibtex: Not writing to /foo/bar/mydoc.blg (openout_any = p).
I couldn't open file name `/foo/bar/mydoc.blg'
```

This is Debian bug [684228](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=684228). There is [a simple patch](http://sources.debian.net/src/rubber/1.1%2B20100306-6/debian/patches/02_rubber_bibtext_20120807.diff/), which I've confirmed fixes the problem when manually applied.

My request is to update the `rubber.rb` formula to apply the above patch. Some of the other patches in the [same directory](http://sources.debian.net/src/rubber/1.1%2B20100306-6/debian/patches/) may also be desirable.

Thank you for your hard work on Homebrew.

**Comment by jacknagel** [comment]
Eight months without activity; closing as stale. Would review a PR.
