### ISSUE TITLE
git-flow-clone has stopped working...

### ISSUE THREAD

**Issue by melriffe** [Homebrew/homebrew#32701]
First: I'm not sure if this is the right place but I'm hoping someone can help me find the problem.

Second: https://gist.github.com/anonymous/d129ee9cc14fa4a3ede6

Third: I'm not sure what changed as I remember git flow clone working before and after I updated to Mac OS X 10.9.

I'm out of ideas. I've reinstalled git-flow-clone but it still doesn't work.

Thanks for any assistance.

**Comment by adamv** [comment]
Should we boneyard this at this point?

**Comment by jacknagel** [comment]
Yeah.
