### ISSUE TITLE
brew install Devil stuck

### ISSUE THREAD

**Issue by Henrilin28** [Homebrew/homebrew#32830]
I used Homebrew to install Devil and it stuck at the process below for more than an hour.

patching file src-ILU/ilur/ilur.c
==> ./configure --prefix=/usr/local/Cellar/devil/1.7.8_1 --enable-ILU --enable-I

My system is OSX 10.9.5
Thanks !

**Comment by gilcel** [comment]
I had exactly the same problem installing the devil lib with brew on OS X 10.8.5 and here's a fix:

If you don't need gcc4.9, uninstall it and install gcc4.7, it will work:
#brew tap homebrew/versions
#brew install gcc47

I've not tried with gcc4.8 yet...

**Comment by shordley** [comment]
I'm seeing the same problem  (on OS X Yosemite), config.log copied below:

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by DevIL configure 1.7.8, which was
generated by GNU Autoconf 2.61.  Invocation command line was

  $ ./configure --disable-debug --disable-dependency-tracking --prefix=/usr/local/Cellar/devil/1.7.8_1 --enable-ILU --enable-ILUT

## --------- ##
## Platform. ##
## --------- ##

hostname = Steves-MacBook-Pro-2.local
uname -m = x86_64
uname -r = 14.0.0
uname -s = Darwin
uname -v = Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64

/usr/bin/uname -p = i386
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
	 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64
Kernel configured for up to 4 processors.
2 processors are physically available.
4 processors are logically available.
Processor type: x86_64h (Intel x86-64h Haswell)
Processors active: 0 1 2 3
Primary memory available: 16.00 gigabytes
Default processor set: 226 tasks, 913 threads, 4 processors
Load average: 1.94, Mach factor: 2.05
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/Library/ENV/4.3
PATH: /usr/local/opt/libpng/bin
PATH: /usr/local/opt/jpeg/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin
PATH: /usr/local/opt/gcc/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2234: checking build system type
configure:2252: result: i386-apple-darwin14.0.0
configure:2274: checking host system type
configure:2289: result: i386-apple-darwin14.0.0
configure:2359: checking for gcc
configure:2386: result: gcc-4.9
configure:2624: checking for C compiler version
configure:2631: gcc-4.9 --version >&5
gcc-4.9 (Homebrew gcc 4.9.2) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:2634: $? = 0
configure:2641: gcc-4.9 -v >&5
Using built-in specs.
COLLECT_GCC=/usr/local/bin/gcc-4.9
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/4.9.2/libexec/gcc/x86_64-apple-darwin14.0.0/4.9.2/lto-wrapper
Target: x86_64-apple-darwin14.0.0
Configured with: ../configure --build=x86_64-apple-darwin14.0.0 --prefix=/usr/local/Cellar/gcc/4.9.2 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-4.9 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-cloog=/usr/local/opt/cloog --with-isl=/usr/local/opt/isl --with-system-zlib --enable-version-specific-runtime-libs --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --disable-werror --with-pkgversion='Homebrew gcc 4.9.2' --with-bugurl=https://github.com/Homebrew/homebrew/issues --enable-plugin --disable-nls --enable-multilib
Thread model: posix
gcc version 4.9.2 (Homebrew gcc 4.9.2) 
configure:2644: $? = 0
configure:2651: gcc-4.9 -V >&5
gcc-4.9: error: unrecognized command line option '-V'
configure:2654: $? = 1
configure:2677: checking for C compiler default output file name
configure:2704: gcc-4.9    conftest.c  >&5
configure:2707: $? = 0
configure:2745: result: a.out
configure:2762: checking whether the C compiler works
configure:2772: ./a.out
configure:2775: $? = 0
configure:2792: result: yes
configure:2799: checking whether we are cross compiling
configure:2801: result: no
configure:2804: checking for suffix of executables
configure:2811: gcc-4.9 -o conftest    conftest.c  >&5
configure:2814: $? = 0
configure:2838: result: 
configure:2844: checking for suffix of object files
configure:2870: gcc-4.9 -c   conftest.c >&5
configure:2873: $? = 0
configure:2896: result: o
configure:2900: checking whether we are using the GNU C compiler
configure:2929: gcc-4.9 -c   conftest.c >&5
configure:2935: $? = 0
configure:2952: result: yes
configure:2957: checking whether gcc-4.9 accepts -g
configure:2987: gcc-4.9 -c -g  conftest.c >&5
configure:2993: $? = 0
configure:3092: result: yes
configure:3109: checking for gcc-4.9 option to accept ISO C89
configure:3183: gcc-4.9  -c -g -O2  conftest.c >&5
configure:3189: $? = 0
configure:3212: result: none needed
configure:3230: checking for a sed that does not truncate output
configure:3309: result: /usr/local/Library/ENV/4.3/sed
configure:3327: checking for grep that handles long lines and -e
configure:3401: result: /usr/bin/grep
configure:3406: checking for egrep
configure:3484: result: /usr/bin/grep -E
configure:3489: checking for fgrep
configure:3567: result: /usr/bin/grep -F
configure:3602: checking for ld used by gcc-4.9
configure:3669: result: /usr/local/Library/ENV/4.3/ld
configure:3678: checking if the linker (/usr/local/Library/ENV/4.3/ld) is GNU ld
configure:3693: result: no
configure:3705: checking for BSD- or MS-compatible name lister (nm)
configure:3754: result: /usr/bin/nm
configure:3876: checking the name lister (/usr/bin/nm) interface
configure:3883: gcc-4.9 -c -g -O2  conftest.c >&5
configure:3886: /usr/bin/nm "conftest.o"
configure:3889: output
0000000000000198 S _some_variable
configure:3896: result: BSD nm
configure:3899: checking whether ln -s works
configure:3903: result: yes
configure:3911: checking the maximum length of command line arguments
configure:4031: result: 196608
configure:4048: checking whether the shell understands some XSI constructs
configure:4058: result: yes
configure:4062: checking whether the shell understands "+="
configure:4068: result: yes
configure:4103: checking for /usr/local/Library/ENV/4.3/ld option to reload object files
configure:4110: result: -r
configure:4137: checking how to recognize dependent libraries
configure:4327: result: pass_all
configure:4387: checking for ar
configure:4403: found /usr/bin/ar
configure:4414: result: ar
configure:4496: checking for strip
configure:4512: found /usr/bin/strip
configure:4523: result: strip
configure:4599: checking for ranlib
configure:4615: found /usr/bin/ranlib
configure:4626: result: ranlib
configure:4720: checking command to parse /usr/bin/nm output from gcc-4.9 object
configure:4838: gcc-4.9 -c -g -O2  conftest.c >&5
configure:4841: $? = 0
configure:4845: /usr/bin/nm conftest.o \| sed -n -e 's/^.*[	 ]\([BCDEGRST][BCDEGRST]*\)[	 ][	 ]*\([_A-Za-z][_A-Za-z0-9]*\)$/\1 \2 \2/p' \> conftest.nm
configure:4848: $? = 0
cannot find nm_test_var in conftest.nm
configure:4838: gcc-4.9 -c -g -O2  conftest.c >&5
configure:4841: $? = 0
configure:4845: /usr/bin/nm conftest.o \| sed -n -e 's/^.*[	 ]\([BCDEGRST][BCDEGRST]*\)[	 ][	 ]*_\([_A-Za-z][_A-Za-z0-9]*\)$/\1 _\2 \2/p' \> conftest.nm
configure:4848: $? = 0
configure:4902: gcc-4.9 -o conftest -g -O2   conftest.c conftstm.o >&5
configure:4905: $? = 0
configure:4943: result: ok
configure:5233: checking for dsymutil
configure:5249: found /usr/bin/dsymutil
configure:5260: result: dsymutil
configure:5329: checking for nmedit
configure:5345: found /usr/bin/nmedit
configure:5356: result: nmedit
configure:5425: checking for lipo
configure:5441: found /usr/bin/lipo
configure:5452: result: lipo
configure:5521: checking for otool
configure:5537: found /usr/bin/otool
configure:5548: result: otool
configure:5617: checking for otool64
configure:5647: result: no
configure:5696: checking for -single_module linker flag
gcc-4.9 -g -O2  -o libconftest.dylib -dynamiclib -Wl,-single_module conftest.c
configure:5723: result: yes
configure:5725: checking for -exported_symbols_list linker flag
configure:5755: gcc-4.9 -o conftest -g -O2   -Wl,-exported_symbols_list,conftest.sym conftest.c  >&5
configure:5761: $? = 0
configure:5780: result: yes
configure:5822: checking how to run the C preprocessor
configure:5862: gcc-4.9 -E  conftest.c
configure:5868: $? = 0
configure:5899: gcc-4.9 -E  conftest.c
conftest.c:8:28: fatal error: ac_nonexistent.h: No such file or directory
 #include <ac_nonexistent.h>
                            ^
compilation terminated.
configure:5905: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "DevIL"
| #define PACKAGE_TARNAME "devil"
| #define PACKAGE_VERSION "1.7.8"
| #define PACKAGE_STRING "DevIL 1.7.8"
| #define PACKAGE_BUGREPORT "bubla@users.sourceforge.net"
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:5938: result: gcc-4.9 -E
configure:5967: gcc-4.9 -E  conftest.c
configure:5973: $? = 0
configure:6004: gcc-4.9 -E  conftest.c
conftest.c:8:28: fatal error: ac_nonexistent.h: No such file or directory
 #include <ac_nonexistent.h>
                            ^
compilation terminated.
configure:6010: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "DevIL"
| #define PACKAGE_TARNAME "devil"
| #define PACKAGE_VERSION "1.7.8"
| #define PACKAGE_STRING "DevIL 1.7.8"
| #define PACKAGE_BUGREPORT "bubla@users.sourceforge.net"
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:6048: checking for ANSI C header files
configure:6078: gcc-4.9 -c -g -O2  conftest.c >&5
configure:6084: $? = 0
configure:6183: gcc-4.9 -o conftest -g -O2   conftest.c  >&5
configure:6186: $? = 0
configure:6192: ./conftest
configure:6195: $? = 0
configure:6212: result: yes
configure:6236: checking for sys/types.h
configure:6257: gcc-4.9 -c -g -O2  conftest.c >&5
configure:6263: $? = 0
configure:6279: result: yes
configure:6236: checking for sys/stat.h
configure:6257: gcc-4.9 -c -g -O2  conftest.c >&5
configure:6263: $? = 0
configure:6279: result: yes
configure:6236: checking for stdlib.h
configure:6257: gcc-4.9 -c -g -O2  conftest.c >&5
configure:6263: $? = 0
configure:6279: result: yes
configure:6236: checking for string.h
configure:6257: gcc-4.9 -c -g -O2  conftest.c >&5
configure:6263: $? = 0
configure:6279: result: yes
configure:6236: checking for memory.h
configure:6257: gcc-4.9 -c -g -O2  conftest.c >&5
configure:6263: $? = 0
configure:6279: result: yes
configure:6236: checking for strings.h
configure:6257: gcc-4.9 -c -g -O2  conftest.c >&5
configure:6263: $? = 0
configure:6279: result: yes
configure:6236: checking for inttypes.h
configure:6257: gcc-4.9 -c -g -O2  conftest.c >&5
configure:6263: $? = 0
configure:6279: result: yes
configure:6236: checking for stdint.h
configure:6257: gcc-4.9 -c -g -O2  conftest.c >&5
configure:6263: $? = 0
configure:6279: result: yes
configure:6236: checking for unistd.h
configure:6257: gcc-4.9 -c -g -O2  conftest.c >&5
configure:6263: $? = 0
configure:6279: result: yes
configure:6295: checking for dlfcn.h
configure:6316: gcc-4.9 -c -g -O2  conftest.c >&5
configure:6322: $? = 0
configure:6338: result: yes
configure:6522: checking for objdir
configure:6537: result: .libs
configure:6833: checking if gcc-4.9 supports -fno-rtti -fno-exceptions
configure:6851: gcc-4.9 -c -g -O2  -fno-rtti -fno-exceptions conftest.c >&5
cc1: warning: command line option '-fno-rtti' is valid for C++/ObjC++ but not for C
configure:6855: $? = 0
configure:6868: result: no
configure:6888: checking for gcc-4.9 option to produce PIC
configure:7145: result: -fno-common -DPIC
configure:7157: checking if gcc-4.9 PIC flag -fno-common -DPIC works
configure:7175: gcc-4.9 -c -g -O2  -fno-common -DPIC -DPIC conftest.c >&5
configure:7179: $? = 0
configure:7192: result: yes
configure:7216: checking if gcc-4.9 static flag -static works
configure:7244: result: no
configure:7259: checking if gcc-4.9 supports -c -o file.o
configure:7280: gcc-4.9 -c -g -O2  -o out/conftest2.o conftest.c >&5
configure:7284: $? = 0
configure:7306: result: yes
configure:7314: checking if gcc-4.9 supports -c -o file.o
configure:7361: result: yes
configure:7394: checking whether the gcc-4.9 linker (/usr/local/Library/ENV/4.3/ld) supports shared libraries
configure:8449: result: yes
configure:8688: checking dynamic linker characteristics
configure:9379: result: darwin14.0.0 dyld
configure:9481: checking how to hardcode library paths into programs
configure:9506: result: immediate
configure:10319: checking whether stripping libraries is possible
configure:10333: result: yes
configure:10359: checking if libtool supports shared libraries
configure:10361: result: yes
configure:10364: checking whether to build shared libraries
configure:10385: result: yes
configure:10388: checking whether to build static libraries
configure:10392: result: yes
configure:10757: checking for a BSD-compatible install
configure:10813: result: /usr/bin/install -c
configure:10824: checking whether build environment is sane
configure:10867: result: yes
configure:10895: checking for a thread-safe mkdir -p
configure:10934: result: build-aux/install-sh -c -d
configure:10947: checking for gawk
configure:10977: result: no
configure:10947: checking for mawk
configure:10977: result: no
configure:10947: checking for nawk
configure:10977: result: no
configure:10947: checking for awk
configure:10963: found /usr/bin/awk
configure:10974: result: awk
configure:10985: checking whether make sets $(MAKE)
configure:11006: result: yes
configure:11036: checking for style of include used by make
configure:11064: result: GNU
configure:11257: checking dependency style of gcc-4.9
configure:11348: result: none
configure:11424: checking build system type
configure:11442: result: i386-apple-darwin14.0.0
configure:11464: checking host system type
configure:11479: result: i386-apple-darwin14.0.0
configure:11508: checking whether gcc-4.9 and cc understand -c and -o together
configure:11543: gcc-4.9 -c conftest.c -o conftest2.o >&5
configure:11546: $? = 0
configure:11552: gcc-4.9 -c conftest.c -o conftest2.o >&5
configure:11555: $? = 0
configure:11566: cc -c conftest.c >&5
configure:11569: $? = 0
configure:11577: cc -c conftest.c -o conftest2.o >&5
configure:11580: $? = 0
configure:11586: cc -c conftest.c -o conftest2.o >&5
configure:11589: $? = 0
configure:11607: result: yes
configure:11749: checking for C++ compiler version
configure:11756: g++-4.9 --version >&5
/tmp/iromu/VisualSFM.app/Contents/Resources/Library/ENV/4.3/g++-4.9:340:in `exec': Argument list too long - /tmp/iromu/VisualSFM.app/Contents/Resources/Library/ENV/4.3/xcrun (Errno::E2BIG)
	from /tmp/iromu/VisualSFM.app/Contents/Resources/Library/ENV/4.3/g++-4.9:340:in `<main>'
configure:11759: $? = 1
configure:11766: g++-4.9 -v >&5
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:8:in `require': Interrupt
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:8:in `<top (required)>'
	from <internal:gem_prelude>:1:in `require'
	from <internal:gem_prelude>:1:in `<compiled>'

**Comment by jacknagel** [comment]
I think this may have been fixed by 7c92f38b1dad961cb719007f13b2a9b15773dcdf.
