### ISSUE TITLE
document options-with-values in the cookbook

### ISSUE THREAD

**Issue by durka** [Homebrew/homebrew#32859]
This came up on IRC just now. The Formula Cookbook doesn't mention the feature whereby you can use options to pass values into the formula (rather than just yes/no).

I wrote a few sentences of documentation: https://github.com/durka/homebrew/wiki/Formula-Cookbook#options-with-values

I can't send a pull request on a wiki, but I guess you can [manually merge](http://roman-ivanov.blogspot.com/2013/11/how-to-merge-github-wiki-changes-from.html). Or just copy and paste :)

**Comment by adamv** [comment]
Formula cookbook is in the repo itself now: https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew

Would review pull requests to improve the cookbook documentation, but closing this in the meanwhile.
