### ISSUE TITLE
request: brew search taps

### ISSUE THREAD

**Issue by blunet** [Homebrew/homebrew#32853]
Print the list of available official taps (or a link to the wiki listing), to make them discoverable from the command line. Alternatively list them in `brew search`.

**Comment by tdsmith** [comment]
I think being able to search for formulas in taps accomplishes the goal of giving visibility to taps. This hasn't caught anybody's eye yet so I think we're unlikely to implement it but if another maintainer thinks we should do this please feel free to reopen.
