### ISSUE TITLE
Packages with --with-mysql option not satisfied by mariadb

### ISSUE THREAD

**Issue by justsomeone1001** [Homebrew/homebrew#32973]
Mariadb and mysql have a conflict, but mariadb provides everything to satisfy any dependency on mysql, including mysql_config.  Packages that depend on mysql, or have a --with-mysql option, however, try to pull in mysql even though mariadb is installed.  An example is gdal.  After discussing this with tdsmith in the irc, changing the "mysql" dependency to :mysql in the formula resolved the problem.  

I'm not sure how many packages this affects, but the problem had arisen every time I tried to use the --with-mysql option.  I think its pretty broad.

**Comment by mikemcquaid** [comment]
`--with-mysql` uses MySQL. This is intentional but we'll accept pull requests to make this more configurable on a per-formula basis.
