### ISSUE TITLE
PySide/PyQt: how to get Phonon support? 

### ISSUE THREAD

**Issue by Argon-** [Homebrew/homebrew#33102]
How are we supposed to get Phonon support with PySide/PyQt installed via homebrew? There was a discussion about the problem in https://github.com/Homebrew/homebrew/issues/21847 but without result.

Is there a suggested course of action other than using Macports (which seems to provide PySide/PyQt with proper Phonon support)?

**Comment by gsportelli** [comment]
I've found this bug report https://bugreports.qt-project.org/browse/QTBUG-37209, I hope this will be solved with Qt 4.8.7.

**Comment by tdsmith** [comment]
That Qt bug report (problems building Qt) is unrelated to this issue (phonon support in PyQt).

**Comment by mikemcquaid** [comment]
This is a feature request so: passing on this in favour of a pull request in future.
