### ISSUE TITLE
tcc won't build on Mac OS X Mountain Lion

### ISSUE THREAD

**Issue by raphaelcohn** [Homebrew/homebrew#33261]
I'm no expert on this, but the error 'tcc: error: -run is not available in a cross compiler' looks suspicious.

brew install tcc
==> Downloading http://download.savannah.gnu.org/releases/tinycc/tcc-0.9.26.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/tcc/0.9.26 --source-path=/private/tmp/tcc-e4einy/tcc-0.9.26 --sysincludepaths=/usr/local/include:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include:{B}/i
==> make
==> make install
==> make test
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/sys/_types.h:32:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/sys/cdefs.h:81: warning: #warning "Unsupported compiler detected"
tcc: error: -run is not available in a cross compiler
make[1]: *** [hello-run] Error 1
make: *** [test] Error 2

**Comment by jacknagel** [comment]
tcc is bottled now and has a working test.
