### ISSUE TITLE
Remove command-line emacs wrapper

### ISSUE THREAD

**Issue by adamv** [Homebrew/homebrew#33423]
Added in https://github.com/Homebrew/homebrew/commit/55dbcc15905664092b805e7822fb8c66d5ca0f8e, replaced guidance to make an alias.

I must have had Emacs installed prior to this, as "emacs" on my box always opens windowed.

I'd like to revert this `emacs` wrapper being added automatically, but I won't revert this if the community thinks adding the wrapper is the way to go.

**Comment by jacknagel** [comment]
Closing. If there's anything immediately actionable here, please reopen.

**Comment by ethanluoyc** [comment]
@timgilbert I am experiencing the same issue here

**Comment by mikemcquaid** [comment]
@ethanluoyc Open a new issue.
