### ISSUE TITLE
percona-server failed to build on 10.10

### ISSUE THREAD

**Issue by keewek** [Homebrew/homebrew#33439]
https://gist.github.com/keewek/1fa14b2b1f4bd1e4d8f4

**Comment by robrecord** [comment]
Sorry guys, can I bump this? How do I help get this sorted? Haven't been able to build persona server for some time now.

**Comment by jacknagel** [comment]
It's an upstream bug (shared by all mysql derivatives). Either bump an upstream bug report or build without memcached support. Sorry :/

**Comment by robrecord** [comment]
Okay, thank you - I will do both! And will maybe check out virtualisation for my dev environment.
