### ISSUE TITLE
d-bus usage with a 3rd party application

### ISSUE THREAD

**Issue by dabrain34** [Homebrew/homebrew#33526]
Hi everyone
it could be good to add in the  formula documentation, the way to use dbus in a shell
Before launching the 3rd party application using dbus:

$ export DBUS_SESSION_BUS_ADDRESS="unix:path=`launchctl getenv DBUS_LAUNCHD_SESSION_BUS_SOCKET`"

If you need i can do it but i dont know the guidelines to submit a patch.
BR

**Comment by bfontaine** [comment]
Sorry for the delay, see here: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md
Don’t hesitate to ask any question.

**Comment by mikemcquaid** [comment]
I think this is up to `dbus` to document rather than Homebrew.
