### ISSUE TITLE
lilypond failed to build on 10.10 ("yosemite")

### ISSUE THREAD

**Issue by gabriel-striewe** [Homebrew/homebrew#33523]
https://gist.github.com/fe4a29c2aab2c1d09056

I checked that XCode as well as the command line tools are up to date.

**Comment by piotr2b** [comment]
Hi there, I also get the same. I'm trying to install lilypond 2.19.15-1 on ArchLinux. Sorry if I post at the wrong place, I've searched for similar problem and I've found this page wherein issue seems rather similar to mine.

```
ERROR: Please install required programs:  International New Century Schoolbook fonts
(make sure the fc-list utility can see them, or use --with-ncsb-dir) /usr/bin/fontforge >=
20110222 (installed: 4cea471798c92848170c2f47311979805966093)
```

But methinks it should work. Here is what I've got:

```
$ yaourt -Qs fontforge
extra/fontforge 20141126-2
    Outline and bitmap font editor
$ fc-list | grep "Century"
/usr/share/fonts/Type1/c059036l.pfb: Century SchoolBook URW:style=Bold Italic
/usr/share/fonts/Type1/c059016l.pfb: Century SchoolBook URW:style=Bold
/usr/share/fonts/Type1/c059013l.pfb: Century SchoolBook URW:style=Roman
/usr/share/fonts/Type1/c059033l.pfb: Century SchoolBook URW:style=Italic
```

I haven't found any free fonts names « International New Century Schoolbook » to download.

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-tex#10
