### ISSUE TITLE
Kafka installation fails without a warning that Java 7 is required

### ISSUE THREAD

**Issue by piotrj** [Homebrew/homebrew#33712]
Even though there is a dependency on java 1.7 in kafka formula, it seems like it does not work.
Here is how it looked on my machine when I had only Java 8 installed.

```
brew install kafka
==> Downloading http://mirrors.ibiblio.org/apache/kafka/0.8.1.1/kafka-0.8.1.1-src.tgz
Already downloaded: /Library/Caches/Homebrew/kafka-0.8.1.1.tgz
==> ./gradlew jar
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 25.471 secs
```

**Comment by jpemberthy** [comment]
+1

**Comment by messense** [comment]
Ran into this problem minutes ago.

**Comment by elbryan** [comment]
Same happening to me

**Comment by damieng** [comment]
Just had this happened but then ran *brew update* and *brew install kafka* again and this time it worked - presumably because 0.8.2.0 doesn't have the same problem with Java 1.8.

**Comment by adamv** [comment]
Looks like this is no longer an issue as per above: https://issues.apache.org/jira/browse/KAFKA-1624

Does anyone still have installation problems after `brew update`?

**Comment by jacknagel** [comment]
Presuming fixed.
