### ISSUE TITLE
Brew python problem with gtk

### ISSUE THREAD

**Issue by ipeacocks** [Homebrew/homebrew#33804]
Hello, guys.
First of all, thank you, guys, for such great tool as Homebrew.

I tried to install gtk apps ZIM http://zim-wiki.org/

And with Apple`s python it launches fine but crashes on two-fingers tap (right mouse click).

With Hombrew python I cant launch ZIM and any other gtk apps at all.

```bash
md760@mac-air:~$ /usr/local/bin/python /Users/md760/my_apps/zim-0.62/zim.py
/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gtk-2.0/gio/__init__.py:23: Warning: g_str_has_prefix: assertion `str != NULL' failed
  from _gio import *
Segmentation fault: 11
```

To be clear I am using Hombrew python:

```bash
md760@mac-air:~$ ls -la /usr/local/bin/python
lrwxr-xr-x  1 md760  admin  35 Nov  1 17:10 /usr/local/bin/python -> ../Cellar/python/2.7.8_2/bin/python
md760@mac-air:~$
```

This is full error output https://www.dropbox.com/s/d2tgrlfnqbqhyil/brew_python_gtk_error.txt?dl=0

PS. It is some brew diagnostic commands

```bash
md760@mac-air:~$ brew update
Already up-to-date.

md760@mac-air:~$ brew doctor
Your system is ready to brew.

md760@mac-air:~$ brew list
ansible			gdbm			harfbuzz		libssh2			openssl			pygobject		sdl_mixer
atk			gdk-pixbuf		icu4c			libtiff			pango			pygtk			sqlite
cairo			gettext			jpeg			libyaml			pixman			python			tcptraceroute
cmake			glib			libffi			mercurial		pkg-config		readline		vim
fontconfig		gobject-introspection	libnet			midnight-commander	portmidi		s-lang			xz
freetype		gtk+			libpng			mtr			py2cairo		sdl
md760@mac-air:~$
```

**Comment by tdsmith** [comment]
Are you still having trouble with this?

**Comment by ipeacocks** [comment]
You can close this ticket. That error was due to few pygtk libs in system.
Thanks.

**Comment by farhaanbukhsh** [comment]
I am facing the same trouble can you please tell the solution

**Comment by tdsmith** [comment]
Please open a new issue and describe fully the problem you're having and what you've done to try and resolve it; thanks!

**Comment by ipeacocks** [comment]
@farhaanbukhsh http://stackoverflow.com/a/28465283/2971192
