### ISSUE TITLE
opam on older Intel CPUs

### ISSUE THREAD

**Issue by hnfmr** [Homebrew/homebrew#33930]
OS: Yosemite
Machine: Mid 2010 MacBook Pro

Please refer to this issue reported for OPAM:
https://github.com/ocaml/opam/issues/1853

The bottled opam doesn't work on my machine. Error is: Illegal instruction: 4

opam if --build-from-source works though.

**Comment by bfontaine** [comment]
Is this still an issue now that #36482 got merged?
