### ISSUE TITLE
brew doctor doesn't detect stale dynamic link instructions in libraries

### ISSUE THREAD

**Issue by ahmadia** [Homebrew/homebrew#33968]
Apologies ahead of time if this has already been proposed or implemented somewhere.

I found myself in a situation where trying to link with a broad collection of libraries led to a mysterious linker failure due to a missing dynamic dependency.  Scanning `/usr/local/lib` with `otool -L` and grep, I was able to locate the guilty library.  It seems this would be a useful function to have in `brew doctor`.  I imagine that it would be implemented by dynamically creating a list of all, "available" libraries, either as symlinks or kegs.  It would then scan each library for dependencies in `/usr/local`  that are *not* in homebrew's list of known libraries.  I don't know how to write this (yet) in Ruby, but I'd be willing to give it a shot if the maintainers are interested in having this functionality available.

**Comment by jacknagel** [comment]
Closing this as stale.

My feelings are that this isn't necessary, and if anyone works on it, it should be prototyped as a separate command rather than bolted on to `brew doctor`.

**Comment by ahmadia** [comment]
Yup, sorry I didn't get to this sooner.  Thanks for answering and I'll open a PR if I need something like this in the future.
