### ISSUE TITLE
When creating a bottle, bump revision iff replacing an older bottle

### ISSUE THREAD

**Issue by staticfloat** [Homebrew/homebrew#34091]
`brew bottle` automatically bumps the revision number if a bottle stanza is found, regardless of whether or not the previous bottle stanza actually contained a bottle for the platform being built.  E.g. if I have a bottle for 10.8 and 10.9, and I build one for 10.10, it bumps the revision number.  I don't think it would hurt to use the same revision number when there's no previous bottle.  What do you guys think?

**Comment by mikemcquaid** [comment]
This was (somewhat) fixed by https://github.com/Homebrew/homebrew/pull/43766.
