### ISSUE TITLE
Collect download statistics

### ISSUE THREAD

**Issue by StevenACoffman** [Homebrew/homebrew#34101]
Currently, homebrew does not collect download statistics, so it is impossible to know what are popular and what are not, and crowdsource recommended formula. This would allow [making the website nicer as well](https://github.com/Homebrew/homebrew.github.io/issues/45).

**Comment by jkarneges** [comment]
I'd love to see bottle download stats. Sourceforge stats would have been great except now Bintray is used to host the bottles. However, I think it may be possible to reveal statistics in Bintray. Has anyone looked into it?

If I view the statistics of a particular package on Bintray, I see percentage values and the message: "download numbers were not made public".

**Comment by tdsmith** [comment]
The Sourceforge stats were also desperately wrong for months at a time. :/ I'll look into opening stats on Bintray.

**Comment by DomT4** [comment]
It can be done on Bintray. Percentages are always published and made public, but you can open that up further as desired. There's nothing personally identifying about the general statistics, so those should be fine to open unless any other @Homebrew/owners object.

**Comment by mikemcquaid** [comment]
I've emailed Bintray to ask them if they can open the stats as it's not visible anywhere in the UI I can see.

**Comment by bfontaine** [comment]
It can be enabled on a per-package basis in the settings: there’s a “Make download numbers in stats public” checkbox at the bottom. It would be great if Bintray could do this for all our packages instead of us manually checking thousands of checkboxes.

**Comment by jkarneges** [comment]
Does the per-package setting apply to all releases of the package, and thus presumably future releases? If so, then it may be practical to handle this by special request because the feature only needs to be set once per package.

If this is the case, then it would be great if the feature could be enabled for the packages I maintain (``zurl`` and ``pushpin``).

Automatically enabling this for all packages would be great, but if nobody else is asking, then doing it by special request could work in the interim (but only if it applies to ALL releases of a package. I wouldn't expect you to manually check a box for me after every release!).

Thanks. :)

**Comment by bfontaine** [comment]
Yes it’s for all releases.

**Comment by mikemcquaid** [comment]
I got this in an email from Bintray:
> There is currently no such batch operation available.
> However, you can write a script utilizing Bintray’s REST API to perform such action.
> For example, you can use Get Repositories to get all the repositories in the Homebrew organization. Then, for each repository use Get Packages to get the all the packages in the repository. For each package, use Update Package sending JSON { "public_stats": true } to only enable public stats for the package.

So, what we'd want to do is:
- write a script to batch update all existing packages
- set the `public_stats` for all new packages we create (in `brew-test-bot.rb`)

**Comment by DomT4** [comment]
> set the public_stats for all new packages we create (in brew-test-bot.rb)

Would this work for new releases of existing formulae/bottles? Or does the package actually have to be "new"? If the former I think setting the tag in `brew-test-bot.rb` is reasonable - A lot of the more popular packages get fairly regular updates/bottle bumps, so.

**Comment by mikemcquaid** [comment]
> Would this work for new releases of existing formulae/bottles? Or does the package actually have to be "new"? If the former I think setting the tag in brew-test-bot.rb is reasonable - A lot of the more popular packages get fairly regular updates/bottle bumps, so.

We should do both the script and the `brew-test-bot.rb` change.

**Comment by jkarneges** [comment]
Maybe this ticket should be reopened now that there's a pending task?

**Comment by ben-albrecht** [comment]
Just wondering, is this still a pending task?

**Comment by DomT4** [comment]
Yes. Various stats have been made public, but there hasn't been any major work on this yet. It's not near the top of my list for now to be honest. We'd review a PR on the `brew-test-bot.rb` change if anyone really wanted to nudge this forwards.

**Comment by mikemcquaid** [comment]
It's near the top of mine but requires a fair bit of work. Still looking for a good "server" solution that we can use to aggregate this data without compromising user privacy.

**Comment by qw3rtman** [comment]
@mikemcquaid What about creating a public API that aggregates this data and provides it to the Homebrew command-line client?

For example, the API would gather (and cache?) information about a package such as download count, [size](https://github.com/Homebrew/homebrew/issues/45088), etc from the Bintray API and other sources. If someone needs that data, they can pass a flag to the `brew info [FORMULA...]` such as `--stats` (or more specifically, `downloads` and `size`).

**Comment by mikemcquaid** [comment]
@qw3rtman Yeh, that would be nice but it requires a lot of work here and we want to lean on another service rather than hosting our own server.

**Comment by jkarneges** [comment]
What is meant by a "server" solution? Some months ago we talked about just making the bintray data public which seems like enough.

**Comment by mikemcquaid** [comment]
It needs to be done somewhat manually. It's also not very scientific as it doesn't include packages that aren't bottled or users that are installing a package with a bottle that can't be installed in their prefix.

**Comment by mroth** [comment]
Is there an established procedure for getting the bintray download stats made public for specific/new formulae?  (As a project maintainer, being able to see download stats on my projects would be highly motivating.)

**Comment by tdsmith** [comment]
Ping me in a week if you don't hear back; I'm working on publishing stats and I accidentally already did the work necessary to enumerate package and flip switches on Bintray. I'll try to enable this repo-wide in the next few days and send a test-bot PR; this should be pretty straightforward.

**Comment by tdsmith** [comment]
Creating new packages with visible download stats is #49620.

**Comment by tdsmith** [comment]
Statistics should be visible for all bottles in all Homebrew repos now.

**Comment by qw3rtman** [comment]
@tdsmith :tada:

Thanks for your work!

**Comment by jkarneges** [comment]
Great to see this!

**Comment by mroth** [comment]
@tdsmith cheers!

**Comment by DomT4** [comment]
Fixed by Tim's PR & follow-up, I believe.

**Comment by mikemcquaid** [comment]
I think this is only partially closed as we're currently only handling bottle downloads.

**Comment by DomT4** [comment]
My POV on closing was that we've covered the "user-facing" side of stats, and leaving an Issue open on page ~7 of the Issues isn't doing anything to remind maintainers there's a desire to explore a fuller level of stats at some point.

**Comment by mikemcquaid** [comment]
@domt4 :+1:

**Comment by ben-albrecht** [comment]
Am I understanding correctly that @tdsmith's patch (#49620) has now made download statistics available via `https://bintray.com/homebrew/bottles/<project>/view#statistics`?

The Bintray [API docs on download statistics](https://bintray.com/docs/api/#_statistics) state the following: "Statistics can only be retrieved for Professional repositories, and require a publish permission or higher." 

Are Homebrew packages published on Bintray as 'Professional repositories'?

**Comment by tdsmith** [comment]
Yes and yes, though we are not going to make write privileges for our repositories generally available. :)

**Comment by ben-albrecht** [comment]
Has anyone been able to retrieve statistics via the Bintray API? I'd be interested to hear how they did it.

We tried the following:

    > curl -u<user>:<key> -H "Content-Type: application/json" https://api.bintray.com/packages/homebrew/bottles/chapel/versions/1.13.0/stats/total_downloads/
    {"message":"forbidden"}`

We inquired Bintray about accessing the download stats through the API, and they told us that our username needs to join Homebrew's Bintray organization in order to access professional repository features.

**Comment by tdsmith** [comment]
> Has anyone been able to retrieve statistics via the Bintray API?

No, you should not have permissions for that.

**Comment by jkarneges** [comment]
I wrote some scraping code: https://gist.github.com/jkarneges/ded7631f5782f06eb609b204bffd4efd

Of course it's not using the official API and may break at anytime but it has worked for us so far. Use something like `/homebrew/bottles/foopackage` as the package path.

**Comment by mikemcquaid** [comment]
Note that https://github.com/Homebrew/brew/pull/78 will enable some download counts beyond just Bintray too.
