### ISSUE TITLE
gtk+3 fails to build on 10.7.5

### ISSUE THREAD

**Issue by kristapsdz** [Homebrew/homebrew#34191]
With all the newest homebrew goodness, gtk+3 fails.

GIST: https://gist.github.com/anonymous/695d98510870165aac82

Command:

% brew install gtk+3
==> Downloading http://ftp.gnome.org/pub/gnome/sources/gtk+/3.14/gtk+-3.14.4.tar.xz
Already downloaded: /Library/Caches/Homebrew/gtk+3-3.14.4.tar.xz
==> Downloading https://git.gnome.org/browse/gtk+/patch/?id=7d3991f2757de8374e11891e21e82f61242b4034
Already downloaded: /Library/Caches/Homebrew/gtk+3--patch-66dc9d63ba6d2f9219d0dbe27f2dd8343b07ab0c
==> Downloading https://git.gnome.org/browse/gtk+/patch/?id=830a72b307b33815179aa0b03dad498c9ac1bb14
Already downloaded: /Library/Caches/Homebrew/gtk+3--patch-5a39469d8923ac9ce1f6511c4e304f7e1cba781c
==> Patching
patching file gdk/quartz/GdkQuartzNSWindow.c
patching file gdk/quartz/GdkQuartzNSWindow.h
patching file gdk/quartz/gdkwindow-quartz.c
==> ./configure --prefix=/usr/local/Cellar/gtk+3/3.14.4 --disable-glibtest --enable-introspection=yes --disable-schemas-compile --enable-x11-backend
==> make install
Command '['/private/tmp/gtk+3-uVZsEI/gtk+-3.14.4/gtk/tmp-introspectcGh8u2/Gtk-3.0', '--introspect-dump=/private/tmp/gtk+3-uVZsEI/gtk+-3.14.4/gtk/tmp-introspectcGh8u2/functions.txt,/private/tmp/gtk+3-uVZsEI/gtk+-3.14.4/gtk/tmp-introspectcGh8u2/dump.xml']' returned non-zero exit status -5
make[3]: *** [Gtk-3.0.gir] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

**Comment by jacknagel** [comment]
We don't bottle for 10.7 anymore, so this shouldn't be a problem.
