### ISSUE TITLE
Trouble installing Gource with xcode 5.0.2

### ISSUE THREAD

**Issue by Relequestual** [Homebrew/homebrew#34372]
I know the troubleshooting section says make sure xcode is up to date, and install the updates from the app store, but I cannot in this instance (I'm siloed away from the app store).

Would trying to install gource with an old version of xcode cause the problem 

`configure: error: Could not link against -lGLU !`

Also my homebrew install is in a different location. Anyone aware if this will cause installing gource to fail?

brew gist-logs gource...
https://gist.github.com/eed082b1803b6903ac8a

**Comment by lunks** [comment]
Just got hit by the same issue. I am also using Boxen.

**Comment by mikemcquaid** [comment]
Seems like the buildsystem needs coaxed to work with Boxen's paths.

**Comment by amateurhuman** [comment]
As a temporary fix/hack, you can create a symlink to `/opt/boxen/homebrew` for `/usr/local` to get Gource installed.

**Comment by dreww** [comment]
same problem here, though @amateurhuman's symlink trick didn't help me.

**Comment by amateurhuman** [comment]
So my solution solves the problem on Yosemite. But if you already have a /usr/local, then you'll need to symlink both:

+ `sudo ln -s /opt/boxen/homebrew/lib /usr/local/lib`
+ `sudo ln -s /opt/boxen/homebrew/include /usr/local/include`

This fixed @dreww's problem.
