### ISSUE TITLE
homebrew, universal python and wxpython

### ISSUE THREAD

**Issue by aodj** [Homebrew/homebrew#34470]
Has anyone had any luck getting Python installed via `brew install python --universal` to start in 32 bit mode via `arch -i386 python` and run wxpython?

Everything installs fine, and I can `import wx` when I just run the brew installed Python, but running it under `arch -i386` results in this:

```
dev:workspace jenkins$ arch -i386 python -c "import wx;print wx.version()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 4, in <module>
    import _core_
ImportError: dlopen(/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core_.so, 2): no suitable image found.  Did find:
	/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core_.so: mach-o, but wrong architecture
```

**Comment by aodj** [comment]
Just chiming in again to say this is still a problem. Just tried `brew install wxpython` on a new Mac Mini running Yosemite and you just get an unusable version of wxpython in cases where you're running a universal application.

**Comment by jacknagel** [comment]
Action items:

 * add universal option to wxpython
 * ??
