### ISSUE TITLE
mysql-connector-c++ cannot build with mariadb 

### ISSUE THREAD

**Issue by guoxiao** [Homebrew/homebrew#34578]
CMake Error at FindMySQL.cmake:541 (message):
  Could not find "mysql.h" in
  "/usr/local/Cellar/mariadb/10.0.15/include/mysql;/usr/local/Cellar/mariadb/10.0.15/include/mysql/.."
  found from running "/usr/local/bin/mysql_config"
Call Stack (most recent call first):
  CMakeLists.txt:202 (INCLUDE)

-- Configuring incomplete, errors occurred!

**Comment by shnode** [comment]
`brew install curl homebrew/dupes/libedit cmake`
and restart the terminal
run:
`brew install mariadb`

this works for me

**Comment by guoxiao** [comment]
The following patch can fix the `mysql_get_option` error in Linux. It should also work for OSX.
```patch
diff -rupN -Nur mysql-connector-c++-1.1.6.orig/driver/nativeapi/libmysql_static_proxy.cpp mysql-connector-c++-1.1.6/driver/nativeapi/libmysql_static_proxy.cpp
--- mysql-connector-c++-1.1.6.orig/driver/nativeapi/libmysql_static_proxy.cpp	2015-09-09 20:34:11.746308368 +0800
+++ mysql-connector-c++-1.1.6/driver/nativeapi/libmysql_static_proxy.cpp	2015-09-09 20:39:42.406453354 +0800
@@ -319,7 +319,7 @@ LibmysqlStaticProxy::options(MYSQL * mys
 int
 LibmysqlStaticProxy::get_option(MYSQL * mysql, enum mysql_option option, const void *arg)
 {
-#if MYSQL_VERSION_ID >= 50703
+#if MYSQL_VERSION_ID >= 50703 && !defined(MARIADB_BASE_VERSION)
 	if (::mysql_get_option(mysql, option, arg)) {
 		throw sql::InvalidArgumentException("Unsupported option provided to mysql_get_option()");
 	} else {
```

**Comment by mikemcquaid** [comment]
@guoxiao Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by guoxiao** [comment]
@mikemcquaid Sorry. I don't have a OS X device at hand and I'm using Linux now. So maybe someone can help to test the patch and create a pull request.

**Comment by mikemcquaid** [comment]
Closing this as there's no real good solution here without upstream patching and the original opener no longer has this problem as they are on Linux.
