### ISSUE TITLE
brew cannot download python

### ISSUE THREAD

**Issue by ejmolinelli** [Homebrew/homebrew#34619]
Hi all,
This is a two parter!

(1)
I've removed macports and am trying to convert to Brew. I've fixed all of the "brew doctor" warnings related to my installation of R as recommended by [this post] (http://azaleasays.com/2014/08/25/homebrew-warnings-about-unbrewed-dylibs-installed-by-r/). I've backed up all the tcl and tk files that brew was complaining about, and I upgraded my xcode to 4.6.3 on my mac os 10.7.5.  

The only remaining issues from brew doctor are 'unbrewed headers' which I see can be ignored.

I'm trying to run:
``` 
brew tap homebrew/dupes
brew install tcl-tk --with-tk
```
which gives the following error:
==> Installing tcl-tk from homebrew/homebrew-dupes
==> Downloading https://downloads.sourceforge.net/project/tcl/Tcl/8.6.3/tcl8.6.3-src.tar.gz

curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 54
Error: Failed to download resource "tcl-tk"
Download failed: https://downloads.sourceforge.net/project/tcl/Tcl/8.6.3/tcl8.6.3-src.tar.gz

Any thoughts?

(2)
Ultimately, I'm trying to get brew working so i can (re-)install python, which is not working yet. I get the following error with brew install python:

==> Downloading https://www.python.org/ftp/python/2.7.8/Python-2.7.8.tgz
Already downloaded: /Library/Caches/Homebrew/python-2.7.8.tgz
==> Downloading http://bugs.python.org/file30805/issue10910-workaround.txt
Already downloaded: /Library/Caches/Homebrew/python--patch-9926640cb7c8e273e4b451469a2b13d4b9df5ba3.txt
==> Patching
patching file Include/pyport.h
Hunk #1 succeeded at 713 (offset 14 lines).
Hunk #2 succeeded at 736 (offset 14 lines).
Error: integer 4294967294 too big to convert to `int'
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/extend/pathname.rb:123:in `atomic_write'
/usr/local/Library/Homebrew/utils/inreplace.rb:26:in `inreplace'
/usr/local/Library/Homebrew/utils/inreplace.rb:14:in `each'
/usr/local/Library/Homebrew/utils/inreplace.rb:14:in `inreplace'
/usr/local/Library/Formula/python.rb:110:in `install'
/usr/local/Library/Homebrew/build.rb:137:in `install'
/usr/local/Library/Homebrew/formula.rb:282:in `brew'
/usr/local/Library/Homebrew/formula.rb:623:in `stage'
/usr/local/Library/Homebrew/resource.rb:66:in `unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:21:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:63:in `unpack'
/usr/local/Library/Homebrew/resource.rb:56:in `stage'
/usr/local/Library/Homebrew/formula.rb:621:in `stage'
/usr/local/Library/Homebrew/formula.rb:279:in `brew'
/usr/local/Library/Homebrew/build.rb:117:in `install'
/usr/local/Library/Homebrew/build.rb:186

**Comment by jacknagel** [comment]
Closing as stale. I don't think there's anything Homebrew can act on here.

**Comment by riemers** [comment]
Late to the party, but i just experienced the same issue. Changing my groupid in advanced options back to staff id (in my case 20) solved the issue after opening a new terminal after that.
