### ISSUE TITLE
ghc: $HOMEBREW_PREFIX search path breaks user's linker options

### ISSUE THREAD

**Issue by mkscrg** [Homebrew/homebrew#34626]
#33690 added `-L$HOMEBREW_PREFIX` to GHC's linker options. Unfortunately, that's passed as an early option in linker calls, superseding any user-defined library search path.

For example, a GHC user might link against a different library version by passing `optl-L$SOME_PATH`:

```shell
ghc -optl-L/my/library/path Main.hs
```

but the linker invocation now looks like

```shell
clang ... -L/usr/local/lib ... -L/my/library/path ...
```

with the Homebrew search path ahead of the user's search path.

Is this cause for reverting #33690? I'm not familiar with the problem it solved. (cc @rhendric)

**Comment by rhendric** [comment]
I think this can be closed; the new formula in #39134 righteously undoes my hackery in #33690.
