### ISSUE TITLE
rpmbuild & libmagic

### ISSUE THREAD

**Issue by nefilim** [Homebrew/homebrew#35062]
original issue: #22930

I'm still running into this issue with a fresh brew installation. I'm not familiar with the details here but this looks like a problem (the referenced /usr/local/share/misc/magic does not exist):

```
==> Downloading http://rpm5.org/files/rpm/rpm-5.4/rpm-5.4.14-0.20131024.src.rpm
rpm-5.4.14.tar.gz
27361 blocks
==> ./configure --prefix=/usr/local/Cellar/rpm/5.4.14 --localstatedir=/usr/local/var --with-path-cfg=/usr/local/etc/rpm --with-path-magic=/usr/local/share/misc/magic --with-extra-path-macros=/usr/local/Cellar/rpm/5.4.14/lib/rpm/macros.*
==> make
```

```
[peter@nefilim s]$ ls -l /usr/local/share/misc
lrwxr-xr-x  1 peter  admin  34 Dec 12 14:29 /usr/local/share/misc -> ../Cellar/libmagic/5.20/share/misc
[peter@nefilim s]$ ls -l /usr/local/share/misc/
total 5752
-rw-r--r--  1 peter  admin  2944752 Oct 19 11:45 magic.mgc
```

Earlier in the original issue someone mentioned that it requires the text format magic file? It looks like the one installed by lib magic is in a binary format. 

I'm not really sure how this relates to bash on OSX not supporting the --rpm-requires option like it does on RHEL variants? 

```
[peter@nefilim s]$ brew info rpm
rpm: stable 5.4.14
http://www.rpm5.org/
/usr/local/Cellar/rpm/5.4.14 (186 files, 11M) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/rpm.rb
==> Dependencies
Build: rpm2cpio ✔
Required: berkeley-db ✔, libmagic ✔, popt ✔, beecrypt ✔, libtasn1 ✔, neon ✔, gettext ✔, xz ✔, ossp-uuid ✔, pcre ✔
[peter@nefilim s]$ brew info libmagic
libmagic: stable 5.20 (bottled)
http://www.darwinsys.com/file/
/usr/local/Cellar/libmagic/5.20 (15 files, 3.0M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libmagic.rb
```

**Comment by fiorix** [comment]
+1 for not patching bash. Just doesn't make any sense to have rpm-related options in bash.

**Comment by afb** [comment]
It's possible to provide a "rpmbash", if you don't want to provide the new feature system-wide ?
Anyway, the only thing you lose is that your packages will be missing a couple of auto-deps...

**Comment by fiorix** [comment]
Yeah I don't care to be honest. I'd rather patch rpm to remove the invocation of bash than to provide a bash with this option.

**Comment by afb** [comment]
Yeah, suggested that to be the default last year. But the rpm prefix still needs patching, I suppose...
i.e. if you look at the output `rpm --eval %configure` you will probably spot the problem mentioned ?

**Comment by fiorix** [comment]
Correct. `--prefix=/usr/local/Cellar/rpm/5.4.14` is set.

**Comment by afb** [comment]
Wonder if something like this would help ? c23b15ff16d8cf845985aeb9a6137d66e7ece1b8 (afb/rpm-build)

**Comment by afb** [comment]
Probably would be better with the same (changing default configuration) for macros.rpmbuild than the horrible `--with-extra-path-macros=#{lib}/rpm/macros.*` configure parameter currently used.

**Comment by afb** [comment]
@fiorix: what are you trying to use rpmbuild for ? that amd64-redhat-linux seems pretty confused

**Comment by fiorix** [comment]
I use it to build packages for centos and redhat with cross-compiled Go software in it.

**Comment by afb** [comment]
I created a new pull request #39054, with an upgrade and all the changes mentioned above.

**Comment by afb** [comment]
@jacknagel: changed the macros in the new pull request, same as in 8fb10627224a45a886006a1f42cac77d359ab34e.
This means that rpmbuild will *not* generate any automatic requires for darwin...

The executable requires is only available for ELF format so far (not Mach-O),
and the scriplet requires needs the `bash --rpm-requires` feature mentioned.

**Comment by jacknagel** [comment]
Pulled the rpm update.
