### ISSUE TITLE
Build PyPy and PyPy3 using PyPy instead of CPython

### ISSUE THREAD

**Issue by alex** [Homebrew/homebrew#35176]
Right now whenever PyPy or PyPy3's formulas are touched, the CI machine churns for a good long while.

This is *extremely* exacerbated by the fact that CPython is used for translation; PyPy is on the order of 2x faster at compiling PyPy than CPython is.

What would it take to get the CI using PyPy for this?

**Comment by jacknagel** [comment]
Closing per #35248.
