### ISSUE TITLE
pip 6 is out

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew#35194]
pip 6 will solve a lot of problems Homebrew python users have reported, which is great! I want to wait a few days to see if any bugfix releases emerge, migrate CPython 3 away from ensurepip, and bundle the pip and setuptools sdists into the bottles for CPython3, pypy, and pypy3 like we do for CPython 2.

**Comment by bcomnes** [comment]
Should the formula Caveats be updated to reflect `pip install --upgrade --no-use-wheel pip`?

**Comment by methane** [comment]
@bcomnes I think it's a bit late.  `--no-use-wheel` is not required after pip6 is installed.

**Comment by bcomnes** [comment]
The bottle is still installing `pip 1.5.6`.

**Comment by DomT4** [comment]
All the Python formulae should now come with the new major ` pip ` and ` setuptools ` releases. ` brew update && brew reinstall xyz ` will get you them immediately.
