### ISSUE TITLE
problem with installing fontconfig

### ISSUE THREAD

**Issue by smergler** [Homebrew/homebrew#35244]
I'm trying to install hhvm, this required fontconfig, when installing that I came across an error that resulted in the following gist.  

https://gist.github.com/smergler/ef02201949c08ff5bfe8

**Comment by jacknagel** [comment]
ping?

**Comment by aerostitch** [comment]
I had a similar issue when trying to install mplayer (which depends on fontconfig).
A `sudo chown -R $(whoami) /usr/local` followed by a `brew update` and `brew upgrade` got me all set up.
Did you try that?

Thanks.

**Comment by charleyf** [comment]
Following @aerostitch directions fixed this issue for me (MacOS 10.10.1) thanks!

**Comment by smergler** [comment]
Hey all, 

I finally got around to checking on this and `sudo chown -R $(whoami) /usr/local` didn't work, so I tried `rm -rf /usr/local/etc/fonts/` and it installed.
