### ISSUE TITLE
Move `eigen` and `dgtal` to homebrew/science?

### ISSUE THREAD

**Issue by dpo** [Homebrew/homebrew#35245]
From [the Eigen homepage](http://eigen.tuxfamily.org/index.php?title=Main_Page)
> Eigen is a C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms.

This was discussed [a long time ago](https://github.com/Homebrew/homebrew/issues/20314#issuecomment-19867975) . There might have been a good reason against moving `eigen` to homebrew/science; sorry if I missed it.

`brew uses eigen` reveals
````
ceres-solver  cufflinks	    openbr	  pcl		statismo
cppad	      dgtal	    opencv	  shogun
````
all of which are already in `homebrew/science` except for `dgtal` (Digital Geometry Tools and Algorithms).

From [the DGtal homepage](http://libdgtal.org):
> [...] generic, efficient and reliable digital geometry data structures, algorithms and tools.

So perhaps `dgtal` should move as well?!

**Comment by dcoeurjo** [comment]
Pending PR in homebrew/science for DGtal (https://github.com/Homebrew/homebrew-science/pull/1835)

**Comment by dcoeurjo** [comment]
Pending PR in homebrew core (https://github.com/Homebrew/homebrew/pull/37094)

**Comment by dpo** [comment]
Thank you!

**Comment by DomT4** [comment]
`dgtal` was moved to Homebrew/science. Will review PRs on the others if the Science team want them, and moving them doesn't break other Homebrew/homebrew formulae (Which cannot have mandatory cross-tap dependencies).
