### ISSUE TITLE
Migrate tex related formulae into a standalone tap?

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew#35335]
There're quite a few tex related formulae inside homebrew core. Such as `auctex`, `chktex`, `latex-mk` etc. Most of them are already included in TeXLive/MacTeX. And without a tex environment, it's almost impossible to run test case for them on CI.

I suggested we migrate them into a standalone tap.

Any comments?

**Comment by DomT4** [comment]
There's an update for ` auctex ` available. Seems to be bug-free from checking with Debian and upstream, but I don't want to bump it since I don't have ` :tex ` on my system to personally check.

**Comment by xu-cheng** [comment]
Or we can install [`BasicTeX`](https://tug.org/mactex/morepackages.html) on CI bot. It's only 96M in size and should be enough to test tex formula.

**Comment by mikemcquaid** [comment]
I don't want to install other software on the bot unless it's really widely used. Currently that is basically just: XQuartz, Java.

**Comment by xu-cheng** [comment]
I'm planning to dig in to check all of TeX related formulae in homebrew core this weekend. 

> unless it's really widely used.

As far as I can tell, TeX user group is as broad as x11's. While x11 becomes deprecated as it's an ancient tech, TeX is not. The major point is, even we migrate all TeX formulae into standalone repo, we still need some kind of CI to test them.

Or maybe we use Travis-CI like `homebrew-nginx`?

**Comment by DomT4** [comment]
I can understand where Mike's coming from on this. I also feel like if we allow ` TeX ` related things to install on the bot and be built against, there's probably cause to install ` tuntap ` and ` osxfuse ` binaries to build against and perhaps bottle against for Yosemite as well. It's a bit of a slippery slope in what to support, what not to :/.

**Comment by dpo** [comment]
A Travis VM could `brew cask install mactex` and test the few TeX-related utilities that are now in core (some of them are redundant with `mactex`, e.g., `latex-mk`). A policy could be that users are expected to brew the `mactex` cask, and a TeX tap only supplies utilities that aren't in there already.

**Comment by xu-cheng** [comment]
Closed as https://github.com/Homebrew/homebrew-tex
