### ISSUE TITLE
autojump signals complaint

### ISSUE THREAD

**Issue by jasonhemann** [Homebrew/homebrew#35342]
Seemingly harmless error, as far as I can tell. Upon updating and upgrading, I now receive the following error after brew commands

-bash: /Users/jasonhemann/.local/share/autojump/autojump_errors: No such file or directory

I don't recall installing this; I assume it came with homebrew installation itself?

**Comment by tadayosi** [comment]
The following command removed the error in my laptop:
`$ mkdir .local/share/autojump`
Give it a try. HTH.

**Comment by jasonhemann** [comment]
I did not create that directory, but I am no longer able to replicate the issue. I'll re-open if I can reproduce it again.
