### ISSUE TITLE
Node installation never completes

### ISSUE THREAD

**Issue by Rnhmjoj** [Homebrew/homebrew#35341]
`brew install node` never completes. I waited for hours but it's just stuck. If I leave with ctrl-c npm won't be installed. This is the [log](http://hastebin.com/oyamiduruc).

So far I tried:

```sh
$ rm -rf /usr/local/lib/node_modeuls
$ rm -rf ~/.npm
$ rm /usr/local/include/node/* && sudo rm -rf /usr/local/include/node/* && sudo rm -rf /usr/local/lib/dtrace
$ sudo chown -R `whoami` /usr/local
$ brew rm node
$ brew cleanup --force
```

`brew doctor` says:
Your system is ready to brew.

**Comment by listochkin** [comment]
I had an issue with `/usr/local/lib/node_modules/npm` being owned by `nobody` and not by `<exact user>` (`andrey` in my case). Once I ran `sudo chown -R andrey:staff /usr/local/lib/node_modules/npm` I could run `brew postinstall node` fine.

**Comment by Nivl** [comment]
I jut got the exact same issue than @listochkin.

**Comment by DomT4** [comment]
The permissions for ` npm ` should *always* be ` user:staff `. Homebrew's installation itself shouldn't be causing this issue, theoretically. Have either of you installed from the upstream Node ` .pkg ` before now? Or have you been purely Homebrew-node this time and freshly encountered this issue? 

Once the newest ` npm ` version lands, I'm going to stick it in the formula because it fixes some nasty race conditions, but it's not out of ` pre-release ` just yet, alas.

**Comment by Rnhmjoj** [comment]
Sorry, I have been out the last few days.
Ok:
@DomT4 No, my computer is not headless and I don't see any dialog box during the process.
@listochkin I don't have your problem. The permissions for `/usr/local/lib/node_modules/npm` are correct.
@DomT4 I tried disabling complete `pyenv` and tried installing node with the brewed python. Same issue.

**Comment by cristianelias** [comment]
Dude, why don't you try:

sudo chown -R whoami /usr/local
brew link --overwrite node

Worked for me.

**Comment by Rnhmjoj** [comment]
@cristianelias Node is already linked but npm is not.
With just `ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm` npm seems work fine but I have to do this on every update since the install hangs.

**Comment by DomT4** [comment]
Does the problem still exist with the latest bump we pushed through last night? Upstream basically suggested installing ` xcode ` and trying again, but I didn't want to go suggest you try a 6GB download for the sake of testing :/.

**Comment by Rnhmjoj** [comment]
I have just updated and tried again. It still hangs.

**Comment by DomT4** [comment]
Blurgh. If you don't have too many packages installed/the inconvenience doesn't suck, I'd suggest trying my [nuke the damn thing](https://github.com/DomT4/scripts/tree/master/OSX_Node_Removal) script and then building Node afresh. It's possible there's a wedged cog somewhere, I guess.

If that doesn't work, I'm scratching my head a bit here. AFAIK, this is the first report we've had in recent memory of ` npm ` hanging during install, but being present and usable with a manual symlink. It's a curious error.

**Comment by Rnhmjoj** [comment]
I don't have many package, just a few utilities so I run the script and... it still hangs.
Is there a way to see what node is doing? I'm curious: the npm process is taking 110% of the cpu.

**Comment by Aaron-Hartwig** [comment]
I seem to be having the same issues as @Rnhmjoj .

**Comment by DomT4** [comment]
@Aaron-Hartwig Are you also CLT-only?

@mikemcquaid Any chance we could bottle the ` npm ` element as well? Is that a possibility here if it turns out CLT-only systems have ` npm ` issues?

**Comment by mikemcquaid** [comment]
@DomT4 We bottle the tarball. We could potentially bottle their `make install` process but only if it doesn't store its prefix anywhere inside itself (as we'd need to install into the Cellar and then postinstall into HOMEBREW_PREFIX).

**Comment by Aaron-Hartwig** [comment]
@DomT4 Yup. I'd be more than happy to give you any logs/output, just let me know what you need.

**Comment by DomT4** [comment]
Thanks. I'm going to try playing with npm tonight to see if we can install it and bottle the installed product without breaking everything.

If you manually complete the install by doing the symlink yourself and then do 'npm install -g npm@latest' does that work for you or does that hang as well? It looks like Node has an Xcode dep for building completely, thanks to node-gyp but as far as npm upstream are concerned, that dep shouldn't be on npm as well. 

Curiously, I asked further up in this thread for people to try building Node with '--build-from-source' and they managed to successfully, so if the Xcode requirement didn't flare up then I'm a little puzzled. It's usual for upstream to be puzzled by these bugs as well, heh.

**Comment by DomT4** [comment]
Curiously, I asked further up in this thread for people to try building Node with '--build-from-source' and they managed to successfully, so if the Xcode requirement didn't flare up then I'm a little puzzled. It's usual for upstream to be puzzled by these bugs as well, heh.

**Comment by mikemcquaid** [comment]
@DomT4 Well, the easiest quick check: do a `npm` install somewhere and grep for the prefix you've installed it into in the installed files. If it's present: we're out of luck.

**Comment by Rnhmjoj** [comment]
@DomT4 It works.
```sh
$ npm install -g npm@latest
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@2.1.17 /usr/local/lib/node_modules/npm
```

**Comment by DomT4** [comment]
@mikemcquaid Looks good so far. All of the installed files grepped so far only make mention of one prefix, which is calling ` #!/usr/bin/env node ` in the scripts.

**Comment by DomT4** [comment]
Going to try a full rebuild of the local new Node script with bottled ` npm ` and see what happens.

**Comment by DomT4** [comment]
Took 5 hours, but I have a working, functional, (*hopefully*) bottleable *(that's not a word)* formulae, including ` npm `.

If anyone above having trouble could remove their ` Node ` installation, and preferably use my script that I referenced further above to completely remove all traces of it, and then do ` brew install -v https://raw.githubusercontent.com/DomT4/homebrew/193df4e5b5c86e40424e3a02fdfd1d8b04eb45d2/Library/Formula/node.rb ` and see if everything goes smoothly and you can ` npm install -g something@latest ` etc.

*Full disclaimer*: I created a test bottle so we can check the bottle mechanism as well. When you run that command, you will pull my new bottle off of my Github mirror directly. This is in no way sanctioned by Homebrew, and if you didn't want to trust me to not screw with your binaries for this test, I fully understand.

You can see the contents of the bottle yourself by downloading ` https://raw.githubusercontent.com/DomT4/LibreMirror/master/Homebrew/Tap_Bottles/node-0.10.35_2.yosemite.bottle.tar.gz ` and untarring it. There's no other way to test the bottle function has worked other than to have someone use the bottle to install and test, but if people are jumpy about me I understand entirely.

Obviously, if this gets merged, it will revert back to using official Homebrew-provided bottles :smile_cat:.

**Comment by DomT4** [comment]
@mikemcquaid If you could look over [the new formula](https://raw.githubusercontent.com/DomT4/homebrew/193df4e5b5c86e40424e3a02fdfd1d8b04eb45d2/Library/Formula/node.rb) and let me know your thoughts, that'd be awesome :heart:.

**Comment by DomT4** [comment]
```ruby
      if build.with? "completion"
        bash_completion.install_symlink \
          libexec/"npm/lib/node_modules/npm/lib/utils/completion.sh" => "npm"
      end
```

This tiny section is broken right now; an artifact from an earlier test. I'll fix the path again before any final version is submitted as a PR, but it works with the fixed path locally, I just forgot to re-fix the path there before I pushed again. It's inconsequential to the bottle test.

**Comment by Rnhmjoj** [comment]
@DomT4 I have just cleaned everything and installed your new formula: it works fine. I have installed a few packages and everything seems ok.

**Comment by DomT4** [comment]
This should all be fixed now after a ` brew update && brew upgrade ` if people want to try out the new Brew build. Let me know if you hit any hiccups along the way :).
