### ISSUE TITLE
Mono 3.10 FIX for GdipCreateFromContext_macosx EntryPointException

### ISSUE THREAD

**Issue by StEvUgnIn** [Homebrew/homebrew#35364]
Hello everyone,
I built Mono on my machine thank homebrew and I noticed I never used to be able to launch any Windows.Forms application. I know Windows.Forms Mono implementation is based on libgdiplus and is tricked with dllmap in a config file which is right in my installation. So I took a look on the internet and I understood with this post :
http://forums.xamarin.com/discussion/27011/fix-for-gdipcreatefromcontext-macosx-and-other-macios-gdi-issues

There was a problem from project side.

So the news are, is there anybody running in the same trouble ? Does someone thinking it would be good to apply the new fix ?

Thanks in advance.

**Comment by xu-cheng** [comment]
[This](https://github.com/Homebrew/homebrew/pull/34973) is an incomplete fix I worked before. But since I have very little experience on mono, I gave up. You are very welcome to dive in to submit a PR to fix it.

**Comment by haf** [comment]
Unless we're backporting fixes to 3.10, then https://github.com/Homebrew/homebrew/pull/36283 ought to fix it - @StEvUgnIn can you verify that?

**Comment by StEvUgnIn** [comment]
After updating, I've got a SIGSEGV.
Did nobody run into the same problem with Mac OS X 10.6.8 32 bits?

**Comment by haf** [comment]
it might be 64 bit vs 32 bit? Homebrew installs 64 bit, XS installer doesn't.

**Comment by StEvUgnIn** [comment]
What do you mean by "Homebrew installs 64 bit, XS installer doesn't."

XS : Xamarin Studio ?
Homebrew compiles from any compatible code, doesn't it ?

**Comment by haf** [comment]
XS = Xamarin Studio

Homebrew compiles what your computer's native arch is, yes.

**Comment by DomT4** [comment]
If this is still relevant we'd take a PR on a fix to review. We barely support OS X 10.6 at this point though, for what it's worth, due to having a lack of regular contributors using it who can help debug problems on an ongoing basis.
