### ISSUE TITLE
brew test-bot --ci-main silently removes all installed packages

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew#35409]
Perhaps test-bot could check that it's running in the CI environment before taking any drastic actions.

**Comment by mikemcquaid** [comment]
> in the CI environment

How would you suggest it do this? Should this just apply to `--ci-*` or `--cleanup` too?

**Comment by sjackman** [comment]
PR #35424 fixes this. It applies to both `--cleanup` and `--ci-*`.
