### ISSUE TITLE
firmware-mod-kit modded for OSX

### ISSUE THREAD

**Issue by denji** [Homebrew/homebrew#35434]
Gives the opportunity to work with firmware on OSX
URL: https://github.com/cinquemb/firmware-mod-kit-osx

> Firmware Modification Kit forked from https://code.google.com/p/firmware-mod-kit/ modded for OSX 10.9

**Comment by jacknagel** [comment]
The maintainers typically do not field formula requests, but you can try to [create one yourself](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md) and then [open a pull request](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md). Thanks!
