### ISSUE TITLE
Why not the current version of the AWS EB CLI?

### ISSUE THREAD

**Issue by orome** [Homebrew/homebrew#35473]
Is there a reason for not supporting the current [AWS EB CLI](http://aws.amazon.com/code/6752709412171743)?

Just curious (new to Homebrew and AWS): I was getting what seemed like weird behavior that didn't match Amazon's documentation, until I realized I had 2.6.4 rather than 3.x.

**Comment by DomT4** [comment]
The download link on the page you linked to is https://s3.amazonaws.com/elasticbeanstalk/cli/AWS-ElasticBeanstalk-CLI-2.6.4.zip

Have they moved it elsewhere, or is 3.x not stable yet, or?

**Comment by bfontaine** [comment]
I found [this page](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-getting-set-up.html) which mentions a `pip` package for the 3.x versions.

**Comment by DomT4** [comment]
Interesting. Looks like they may have moved to ` pip `. Their (allegedly) official Twitter supports this [statement](https://twitter.com/aws_eb/status/527893347592318976). I'll look into bumping it with the new build shortly.

**Comment by bfontaine** [comment]
The version has been bumped in 1c1e7d1.
