### ISSUE TITLE
Confusing error handling with xcode/install

### ISSUE THREAD

**Issue by foxx** [Homebrew/homebrew#35475]
```
$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
```

```
$ sudo ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
Password:
Don't run this as root!
```

Lol - had to load xcode manually and accept user agreement there instead.

**Comment by jacknagel** [comment]
There is not enough information here to even speculate about the problem. Please post some details about your system (follow the [troubleshooting guide](http://git.io/brew-troubleshooting)).

**Comment by xu-cheng** [comment]
I think `Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.` comes from Xcode not homebrew.

**Comment by foxx** [comment]
Attempt to install brew for the first time on a clean system that has only just had xcode installed, and it will give you this error about "Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo". However if you run as sudo, it gives the error of "Don't run this as root!".

The fix would be to change the error message to say "Please run xcode manually and accept the user agreement", or to allow the script to run as root.

Does this make more sense?

**Comment by jacknagel** [comment]
>The fix would be to change the error message to say "Please run xcode manually and accept the user agreement", or to allow the script to run as root.

Neither of these changes should be necessary. On a clean system, the installer can be run without root (it will later call sudo which will ask for your password). What you've encountered is an exceptional case, not the norm.

However, we won't be able to debug the issue unless you can provide some information about your system and hopefully a way to reproduce it :/

**Comment by foxx** [comment]
OS X 10.10.1 (Yosemite) - totally clean install, no upgrade. Can reproduce it in a VM easily.

**Comment by steakknife** [comment]
No CLT.  Might need to run `xcode-select --install` or similar first.

**Comment by kenzierocks** [comment]
I don't know if this has regressed or not, but I just got this today with `brew install qt5`.

**Comment by orip** [comment]
Only the license acceptance needs to run as root. Try running

    sudo xcodebuild -license
