### ISSUE TITLE
groonga formula seems not to enable mruby support

### ISSUE THREAD

**Issue by arika** [Homebrew/homebrew#35508]
we should configure with '--enable-mruby'.

https://gist.github.com/arika/38a8d7bc5ba456bf1829

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!
