### ISSUE TITLE
nimrod formula doesn't compile nimfix 

### ISSUE THREAD

**Issue by mrzv** [Homebrew/homebrew#35505]
[`nimfix`](http://nim-lang.org/nimfix.html) comes as part of nim distribution, but it's not built by the formula.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!

**Comment by mrzv** [comment]
The pull request that I opened for an unrelated issue (#35249) has been sitting in limbo. I'd rather just leave the issue for whoever has the power to commit to just fix it.

**Comment by mikemcquaid** [comment]
@mrzv It's not clear from this description how to fix it. Also, if you're the person who would like it added it makes more sense for you to investigate it. I've commented on that PR, hope that helps. Thanks!

**Comment by mrzv** [comment]
Nothing to investigate there. Instructions are clear as day. Whoever has commit access could fix the issue in less time than it takes to write this comment. To make it clear, I do not intend to go through the pain of dealing with a pull request. If you don't want to fix this issue, that's up to you.

**Comment by mikemcquaid** [comment]
I have commit access and the instructions are not clear (and I read them before writing the previous comment). This is open-source software; if you're not willing to go through the "pain" of a pull request then I'm not sure why you expect others to do so either.
