### ISSUE TITLE
brew upgrade x downgrades devel to stable

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew#35523]
If you've a devel formula installed, ` brew upgrade x ` will nudge that formula from devel to stable, which is contrary to what people expect to happen, I suspect.

` brew upgrade nginx --devel ` does work, but there may be merit to a discussion about whether ` brew upgrade ` should automatically detect, catch and bump devel versions consistently automatically, rather than expecting users to remember ` brew upgrade x --devel `.

To reproduce:

```
brew install -v --debug --build-from-source https://raw.githubusercontent.com/Homebrew/homebrew/8a4947061d959bbdb4ef2ad87b612b2db6b7a0b7/Library/Formula/nginx.rb --devel
==> Summary
🍺  /usr/local/Cellar/nginx/1.7.7: 7 files, 952K, built in 44 seconds
```

```
brew upgrade nginx
==> Upgrading 1 outdated package, with result:
nginx 1.6.2
==> Upgrading
==> Summary
🍺  /usr/local/Cellar/nginx/1.6.2: 7 files, 920K
```

Already looking at a couple ways to fix/detect/etc this, but happy for maintainers and others to chuck advice on, discuss the idea more, etc.

**Comment by jacknagel** [comment]
Users should really continue to use `--devel` to do this. Consider the opposite scenario, where you are using the devel version for a specific reason, but *don't* want to be pegged to devel versions forever.

Changing it would require nontrivial architectural changes to Homebrew internals, akin to implementing https://github.com/Homebrew/homebrew/issues/13197.

**Comment by jacknagel** [comment]
Forget what I wrote, I misread part of the issue.

**Comment by jacknagel** [comment]
`brew upgrade` without arguments won't do the downgrade, so I think this should be fixed.

However, if I have devel version "1.1" installed and the formula is bumped to stable version "1.2", and devel version "1.3", I think it should continue to upgrade to "1.2" rather than "1.3".

**Comment by jacknagel** [comment]
Maybe something like:

```diff
diff --git a/Library/Homebrew/cmd/upgrade.rb b/Library/Homebrew/cmd/upgrade.rb
index 352a4d3..70b8905 100644
--- a/Library/Homebrew/cmd/upgrade.rb
+++ b/Library/Homebrew/cmd/upgrade.rb
@@ -9,15 +9,14 @@ def upgrade
       outdated = Homebrew.outdated_brews
       exit 0 if outdated.empty?
     else
-      outdated = ARGV.formulae.select do |f|
-        if f.installed?
-          onoe "#{f.name}-#{f.installed_version} already installed"
-          false
-        elsif not f.rack.directory? or f.rack.subdirs.empty?
-          onoe "#{f.name} not installed"
-          false
+      outdated = ARGV.formulae & Homebrew.outdated_brews
+
+      (ARGV.formulae - outdated).each do |f|
+        if f.rack.directory?
+          version = f.rack.subdirs.map { |d| Keg.new(d).version }.max
+          onoe "#{f.name} #{version} already installed"
         else
-          true
+          onoe "#{f.name} not installed"
         end
       end
       exit 1 if outdated.empty?
```

**Comment by DomT4** [comment]
> brew upgrade without arguments won't do the downgrade, so I think this should be fixed.

Yeah, it doesn't update the installed ` devel ` formula, but it doesn't downgrade them either. You have to actually do ` brew upgrade x ` for it to shunt you from devel to stable. The ` --devel ` flag prevents that, but I don't know if we should detect the ` devel ` status and then upgrade accordingly for the ` brew upgrade x ` situation?

> However, if I have devel version "1.1" installed and the formula is bumped to stable version "1.2", and devel version "1.3", I think it should continue to upgrade to "1.2" rather than "1.3".

Fair enough. This makes sense. There are plenty of situations where people install ` devel ` as a temporary thing and we shouldn't assume they want to permanently remain there.

The diff looks good. More than happy to see that committed if you're content with it.

**Comment by DomT4** [comment]
Patch seems to work great.

```
==> Summary
🍺  /usr/local/Cellar/nginx/1.7.7: 7 files, 952K, built in 36 seconds
brew upgrade nginx
Error: nginx 1.7.7 already installed
brew upgrade nginx --devel
==> Upgrading 1 outdated package, with result:
nginx 1.7.9
```
