### ISSUE TITLE
Add a way to list linked kegs and to tell if a formula is linked or not?

### ISSUE THREAD

**Issue by ladislas** [Homebrew/homebrew#35547]
Do you think something like the following could be useful?

```
# to list all linked kegs 
brew ls --linked
# to tell if a formula is linked
brew ls --linked name_of_forumla
```

It could be similar to `brew ls --versions name_of_formula`

**Comment by adamv** [comment]
See https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Querying-Brew.md

**Comment by ladislas** [comment]
Thanks @adamv for the quick reply and link to documentation.

I just installed `jq` to test with `brew info --json=v1 --installed | jq "map(select(.keg_only == false and .linked_keg == null) | .name)"` but got the following error:

```bash
# ladislas @LadBookAir.local in ~
→ brew info --json=v1 --installed | jq "map(select(.keg_only == false and .linked_keg == null) | .name)"
Error: invalid byte sequence in UTF-8
parse error: Invalid numeric literal at line 1, column 7
```

Also, even if I can make an alias, it seems hella complicated where I could *just* use the following which is just basic shell script:

```bash
if [ $(ls $(brew --prefix)/Library/LinkedKegs | grep "name_of_formula") &> /dev/null ] ; then
    echo "yeah"
else
    echo "nooo"
fi
```

**Comment by jacknagel** [comment]
I think the idea is that by providing access to "raw" information, people can build useful tools that are tailored to their use case on top of it, rather than have the core implement and maintain separate commands or options for each piece of information.
