### ISSUE TITLE
Rubocoping

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew#35556]
Lines 10-12:

```
    system "./configure", "--prefix=#{libexec}", "--sysconfdir=#{etc}",
                          "--localstatedir=#{var}", "--disable-dependency-tracking"
    system "make", "install"
```

```
C:  1:  1: Missing top-level class documentation comment.
C:  2: 12: Prefer single-quoted strings when you don't need string interpolation or special symbols.
C:  3:  7: Prefer single-quoted strings when you don't need string interpolation or special symbols.
C:  3: 93: Line is too long. [93/80]
C:  4: 10: Prefer single-quoted strings when you don't need string interpolation or special symbols.
C: 10: 12: Prefer single-quoted strings when you don't need string interpolation or special symbols.
C: 11: 27: Align the parameters of a method call if they span more than one line.
C: 11: 53: Prefer single-quoted strings when you don't need string interpolation or special symbols.
C: 11: 81: Line is too long. [83/80]
C: 12: 12: Prefer single-quoted strings when you don't need string interpolation or special symbols.
C: 12: 20: Prefer single-quoted strings when you don't need string interpolation or special symbols.
C: 27: 28: Prefer single-quoted strings when you don't need string interpolation or special symbols.
```

Is it telling me to... use single quotes instead of double quotes? And it's not ignoring the url length, like it's supposed to. Is this a bug, or is the local ` brew audit --strict ` supposed to ignore the restrictions we put in place around double quotes and url length? :crying_cat_face:

**Comment by DomT4** [comment]
Just cropped up in #35552 as well, re the URL issue.

**Comment by jacknagel** [comment]
It would be helpful to see the full contents of the formula in question.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-devel-only/pull/5

**Comment by jacknagel** [comment]
How are you invoking rubocop? Using `brew style`, or running it directly? What directory are you in when doing so?

**Comment by DomT4** [comment]
Invoking it from inside the devel tap locally, or inside my local Homebrew fork. Tried both, same error.

It's running the brew style command as part of 'brew audit --strict'. It looks like the bot didn't flag the quotes, but did flag the url length. Not sure why the difference is occurring just yet.

**Comment by DomT4** [comment]
Apologies, email reply cut me off. It's running the brew style command as part of 'brew audit --strict'. It looks like the bot didn't flag the quotes, but did flag the url length. Not sure why the difference is occurring just yet.

**Comment by jacknagel** [comment]
However it's being invoked, it's being done in a way that doesn't pick up our rubocop.yml config file. I can't reproduce this locally, though:

```
jacknagel@haswell:homebrew(master=) $ curl -L https://raw.githubusercontent.com/DomT4/homebrew-devel-only/shadowvpn/Formula/shadowvpn.rb -o Library/Formula/shadowvpn.rb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1047  100  1047    0     0   2632      0 --:--:-- --:--:-- --:--:--  2630
jacknagel@haswell:homebrew(master %=) $ bin/brew audit --strict shadowvpn
==> brew style shadowvpn
== Library/Formula/shadowvpn.rb ==
C:  3: 93: Line is too long. [93/80]
C: 11: 81: Line is too long. [83/80]
C: 27: 81: Line is too long. [85/80]

1 file inspected, 3 offenses detected
```

**Comment by DomT4** [comment]
Was that ran from a particular directory, or just the ` $HOME ` folder?

**Comment by jacknagel** [comment]
`~/src/homebrew`

**Comment by DomT4** [comment]
Ah, found it. Looks like the ` brew audit --strict ` has to be run on formulae inside ` /Library/Homebrew/Formula `, and not anywhere else, otherwise it doesn't pick up on the config and just flags everything. Moving it anywhere else breaks the config detection.

I presumed, probably foolishly, that it would hook the correct config file even on formulae not existing inside the ` /Library/Homebrew/Formula ` directory, so long as you inspected the file with ` brew audit --strict ` or ` brew style `.

I guess the solution is to test formulae inside the Homebrew Formula prefix, rather than externally?

Alright. That's that issue solved.

Do you want me to leave this open for the URL misdetection, or is this closable?

**Comment by jacknagel** [comment]
Maybe the style command should pass `--config <path to our config file>` when invoking rubocop.

**Comment by DomT4** [comment]
I'd be :+1: on that. It'd make life easier in terms of not having to pollute the main Homebrew directory for the sake of running audits.

**Comment by mikemcquaid** [comment]
> Maybe the style command should pass --config <path to our config file> when invoking rubocop.

It should, on it.

**Comment by DomT4** [comment]
Yup, works great outside the Homebrew prefix now, Thanks Jack & Mike :+1:
