### ISSUE TITLE
SHA256 mismatch on perforce

### ISSUE THREAD

**Issue by kevwil** [Homebrew/homebrew#35565]
==> Upgrading perforce
==> Downloading http://filehost.perforce.com/perforce/r14.2/bin.macosx105x86_64/p4
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: ce0e80f29813159a0384fafb77d85590e57e2d3deea3a42ad55ee9b70c842002
Actual: 0d2ad21ecc03493a9b429907fb49209369ca09fd87340c03812dc1d1748dc562
Archive: /Library/Caches/Homebrew/perforce-2014.2.962050

**Comment by mikemcquaid** [comment]
Please report this to homebrew-binary: https://github.com/Homebrew/homebrew-binary/issues/new
