### ISSUE TITLE
undefined method `any?' for ".":String

### ISSUE THREAD

**Issue by disenchant** [Homebrew/homebrew#35566]
As soon as I'm using ```brew [non-existing command]``` or ```brew cask``` (cask is installed), I'm getting the following error message:

    $ brew x
    Error: undefined method `any?' for ".":String
    Please report this bug:
        http://git.io/brew-troubleshooting
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1394:in `contains_requirable_file?'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:865:in `block in find_inactive_by_path'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:823:in `block in each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:864:in `find'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:864:in `find_inactive_by_path'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:175:in `try_activate'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    /usr/local/Library/brew.rb:59:in `require?'
    /usr/local/Library/brew.rb:118:in `<main>'

I've already tried ```brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup```. My version of Homebrew is _0.9.5_ and my brew-cask version is _0.52.0_ and before you ask, yes this was already submitted as an issue to the homebrew-cask team caskroom/homebrew-cask#8630 :smiley:

And for the sake of completeness:

    $ brew doctor
    Your system is ready to brew.
    $ sw_vers # my OS X version
    ProductName:    Mac OS X
    ProductVersion: 10.10.1
    BuildVersion:   14B25

**Comment by jacknagel** [comment]
The exception is being raised inside rubygems on line 1394 of
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb

It seems like you have a gem that has its require_paths set to a string rather than an array.

I don't know how to figure it out other than uninstalling gems one at a time, but in any case it's not a Homebrew bug.

**Comment by jacknagel** [comment]
Rubygems addressed this in https://github.com/rubygems/rubygems/pull/904, so it can also be fixed by upgrading rubygems.
