### ISSUE TITLE
Why won't brew install the older version of postgresql?

### ISSUE THREAD

**Issue by TechFounder** [Homebrew/homebrew#35571]
I have an old  ```postgresql 9.3.5_1``` file in my  ```/library/caches/homebrew``` folder. I want to install this version rather than the newer ```9.4```.

Everytime I run ```brew install /library/caches/homebrew/postgresql-9.3.5_1.yosemite.bottle.1.tar.gz```

I get

    ==> Pouring postgresql-9.3.5_1.yosemite.bottle.1.tar.gz
    Error: /usr/local/Cellar/postgresql/9.4.0 is not a directory
    Warning: Bottle installation failed: building from source.
    ==> Downloading http://ftp.postgresql.org/pub/source/v9.4.0/postgresql-9.4.0.tar.bz2
    Already downloaded: /Library/Caches/Homebrew/postgresql-9.4.0.tar.bz2
    ==> Patching
    ==> ./configure --prefix=/usr/local/Cellar/postgresql/9.4.0 --datadir=/usr/local/Cellar/postgresql/9.4.0/share/postgresql

Which make no sense to me as it starts to load the new version? What am I doing wrong? Why is it saying ```Error: /usr/local/Cellar/postgresql/9.4.0 is not a directory```?

**Comment by TechFounder** [comment]
ok, i was somehow able to git it to install but now when i run 
```postgres -D /usr/local/var/postgres```

I get
```
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/openssl/lib/libssl.1.0.0.dylib
Referenced from: /usr/local/bin/postgres
Reason: image not found
```

**Comment by mikemcquaid** [comment]
Submit a PR to `homebrew-versions` to install `postgresql93`. The way you're trying to do it is not supported.
