### ISSUE TITLE
Brewing from custom formulas that have dependencies is broken

### ISSUE THREAD

**Issue by chdiza** [Homebrew/homebrew#35572]
Sometime in the last couple of days, brewing custom formulas broke.

E.g., I have a custom formula for msmtp.  I brew it with `brew install -d /whatever/thepath/to/my/customformula/is/msmtp.rb`.

Suddenly, when I do this, Homebrew believes that it needs to install `xz`.  This is (a) new, and (b) incorrect, because I already have `xz` installed.  Now, this existing installation of `xz` was done with my custom formula for `xz`, which I suspect is the ultimate source of the problem.

Homebrew used to "know" that I already have `xz` on my system and use it.

I tried to workaround this by explicitly declaring, in my custom `msmtp` formula, a `depends_on "/thepathtomycustom/xz.rb"`, but that merely resulted in Homebrew believing that it first needed to install the official `xz`, followed by my custom `xz`:

````
==> Installing dependencies for msmtp: xz, /thepathtomycustom/xz.rb
==> Installing msmtp dependency: xz
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Formula/xz.rb
````

**Comment by jacknagel** [comment]
`depends_on "a path"` was never intentionally supported. It only worked by accident of implementation.
