### ISSUE TITLE
Overriding bottle root urls

### ISSUE THREAD

**Issue by staticfloat** [Homebrew/homebrew#35586]
Over at [JuliaLang/Julia](https://github.com/JuliaLang/julia), we hit the sourceforge mirrors for build dependencies multiple times a day for our continuous integration testing on OSX.  We've setup Travis to download the build dependencies via Homebrew, which works great, except when the sourceforge mirrors refuse our queries, which is often enough that we'd like to do something about it.

We realize that you guys don't necessarily have the resources to pay for S3 for all the bottles in the world, and mirroring everything would be extra effort for all involved.  We do, however, have some S3 resources we can spare to host the packages we're most interested in.  There are a few different ways this could work, which I'll outline and note why I prefer one over the other:

* I could copy all of the necessary dependencies to a tap, change the `root_url` in the bottle stanza, and copy all the necessary bottles over to my own S3 server.  This is doable right now, but involves some work in that I'd need to update the deps whenever new versions of the formulae make their way into Homebrew, which I'm not excited about.

* We could ask you guys to add a `mirror` line to specific bottles where we can host them.  This has so many organizational and logistical problems, I can't take it seriously, but I thought I'd include it since every good list has at least three items.

* I could somehow coerce Homebrew into asking a different server for Bottles, perhaps by the tantalizingly-named[ `--root-url=` option](https://github.com/Homebrew/homebrew/blob/ccc130c51d5b4e8db8f02993ab5f6051c1ad602e/Library/Homebrew/cmd/bottle.rb#L180), where I could override the server used to serve bottles.  This would solve our problems in that it becomes zero overhead for you guys, and all we have to do is faithfully mirror the bottles of the formulae we're interested in.

What do you guys think?

**Comment by mikemcquaid** [comment]
I don't think is something we can really support. As SourceForge downtime is becoming a problem we are investigating moving bottles to somewhere else. Thanks anyway though!

**Comment by staticfloat** [comment]
Is it possible to configure `brew` to use an HTTP proxy?  If so, we could setup a server to transparently redirect the requests to our bottle server.

Come to think of it, something like the [Coral Cache](http://www.coralcdn.org/) might be right up your alley; keep hosting on sourceforge, but set the root url to `http://downloads.sf.net.nyud.net/project/machomebrew/Bottles/`, which will transparently cache files that.are requested frequently on local-er servers.  You lose HTTPS though, not sure if you really care about that

**Comment by mikemcquaid** [comment]
> You lose HTTPS though, not sure if you really care about that

We do, yeh. If you can find a company to sponsor our S3 hosting that'd be the best approach moving forward.

**Comment by staticfloat** [comment]
Second note for posterity; there was a much simpler way of getting at what I wanted here, so if anyone else ever wants to replicate what we're doing, it's automatic and super-easy.  Here's [the issue](https://github.com/JuliaLang/julia/pull/9653) where I hashed all this out, but I'll summarize the steps;

First, `sed` the default bottle URL:
```
sed -i '' -e "s@https://downloads.sf.net/project/machomebrew/Bottles@http://your_cache_server@" /usr/local/Library/Homebrew/software_spec.rb
```

Next, either manually copy over the bottles you want to mirror, or use something akin to [this guy](https://github.com/staticfloat/cache.julialang.org/blob/master/www/cache.py), which transparently clones bottles it's asked for to S3 and redirects clients accordingly.
