### ISSUE TITLE
emacs fails to build on OSX 10.10.1 "make[1]: *** [bootstrap-emacs] Illegal instruction: 4"

### ISSUE THREAD

**Issue by kplimack** [Homebrew/homebrew#35617]
==> ./configure --prefix=/usr/local/Cellar/emacs/HEAD --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs/HEAD/share/info
==> make
Loading /private/tmp/emacs-Wzj5PF/lisp/international/mule-cmds.el (source)...
Loading /private/tmp/emacs-Wzj5PF/lisp/case-table.el (source)...
Loading /private/tmp/emacs-Wzj5PF/lisp/international/characters.el (source)...
make[1]: *** [bootstrap-emacs] Illegal instruction: 4
make: *** [src] Error 2

https://gist.github.com/anonymous/b1e11eb431149edf5488

**Comment by tonyday567** [comment]
https://gist.github.com/3f70442d16b3d8c4aa37

Me too.  Formulae was:
    brew gist-logs emacs --HEAD --use-git-head --cocoa --srgb

brew doctor, brew update, xcode, command line tools all ok and up-to-date.

**Comment by kplimack** [comment]
https://gist.github.com/kplimack/c21a2c68b73ada227ccb

**Comment by tonyday567** [comment]
`brew install emacs --cocoa -srgb` installed fine so it's probably an emacs HEAD issue.

**Comment by jacknagel** [comment]
Yeah, very likely.

Given head is always changing, we can't really provide support for it, sorry.

You may want to report this upstream, if it hasn't been already.

**Comment by kplimack** [comment]
is there a brew argument to specify a tag/release to install?
