### ISSUE TITLE
Brew install of youtube-dl fails

### ISSUE THREAD

**Issue by caryhartline** [Homebrew/homebrew#35616]
The gist is here: https://gist.github.com/df8a369eb6a60fca9722

The tried installing youtube-dl twice which is why youtube-dl was already downloaded.  The failure happens during the `make` process.

**Comment by jaimeMF** [comment]
This should be fixed in the next version of youtube-dl (with https://github.com/rg3/youtube-dl/commit/c5d666d3741d076d668c16f0dd3601589484b7c3)

**Comment by phihag** [comment]
youtube-dl 2015.01.08 should contain the necessary fixes.
