### ISSUE TITLE
Error: undefined method `deprecated_option' for Findutils:Class

### ISSUE THREAD

**Issue by starmatt** [Homebrew/homebrew#35633]
Hello, I have this error after updating brew, couldn't find anything on it :(
Thanks for the help!

$> brew install tmux
Error: undefined method `deprecated_option' for Libevent:Class
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/nfs/zfs-student-2/users/2014/mborde/.brew/Library/Formula/libevent.rb:30
/usr/local/Library/Homebrew/formulary.rb:65:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:192:in `factory'
/usr/local/Library/Homebrew/formula.rb:397:in `factory'
/usr/local/Library/Homebrew/dependency.rb:32:in `to_formula'
/usr/local/Library/Homebrew/dependency.rb:91:in `expand'
/usr/local/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Library/Homebrew/dependency.rb:79:in `expand'
/usr/local/Library/Homebrew/formula.rb:434:in `recursive_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:94:in `verify_deps_exist'
/usr/local/Library/Homebrew/formula_installer.rb:88:in `prelude'
/usr/local/Library/Homebrew/cmd/install.rb:116:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:105:in `send'
/usr/local/Library/brew.rb:105

$> brew doctor
Error: undefined method `deprecated_option' for Findutils:Class
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/nfs/zfs-student-2/users/2014/mborde/.brew/Library/Formula/findutils.rb:16
/usr/local/Library/Homebrew/formulary.rb:65:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:192:in `factory'
/usr/local/Library/Homebrew/formula.rb:397:in `factory'
/usr/local/Library/Homebrew/tab.rb:50:in `for_name'
/usr/local/Library/Homebrew/cmd/doctor.rb:1003:in `check_for_non_prefixed_findutils'
/usr/local/Library/Homebrew/cmd/doctor.rb:1130:in `send'
/usr/local/Library/Homebrew/cmd/doctor.rb:1130:in `doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1129:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1129:in `doctor'
/usr/local/Library/brew.rb:105:in `send'
/usr/local/Library/brew.rb:105

**Comment by starmatt** [comment]
Brew update tells me that everything is up to date.

**Comment by mikemcquaid** [comment]
`cd /usr/local; git fetch; git reset --hard origin/master; brew update` may help.

**Comment by starmatt** [comment]
Hi, thanks but I tried that already, unfortunately it does not work :(

**Comment by jacknagel** [comment]
>Hi, thanks but I tried that already, unfortunately it does not work :(

What part of it doesn't work? Do the git operations fail?

**Comment by starmatt** [comment]
The git operations fail when in /usr/local, but I don't have root permission anyway (I think it says that git is not initialized, I'll have to check the errors tomorrow). They otherwise work ~/.brew but to no effect.

**Comment by mikemcquaid** [comment]
If you can't write to `/usr/local` then you can't use Homebrew there I'm afraid. A `sudo chown -R $USER /usr/local` will probably help.

**Comment by starmatt** [comment]
Hi, I do not have to root password, and I am not in the sudo group. It used to work though, and there is a .brew in my home which is where the package are supposed to get installed. For instance, if I rm -rf the .brew folder, and I then run brew upgrade, it'll recreate the .brew in my home.

**Comment by starmatt** [comment]
So if I understand the errors correctly, there actually issues with the .rb in the /usr/local/ installation of brew, right? Cause I'm guessing the .brew folder in my home is symlinked to the usr/local or something.

**Comment by mikemcquaid** [comment]
Basically your Homebrew Git repository is not in a consistent state.

**Comment by starmatt** [comment]
Welp, I managed to use the install command by commenting the 30th line of the libevent.rb file. I am guessing it is not a good idea, but it worked :o

**Comment by mikemcquaid** [comment]
I thought you didn't have write access to that directory?

**Comment by starmatt** [comment]
I wrote in ~/.brew/Library/Formula/libevent.rb

**Comment by mikemcquaid** [comment]
Then you should add `~/.brew/bin` to the front of your PATH and run `brew update`.

**Comment by starmatt** [comment]
Yup that's already there.

**Comment by mikemcquaid** [comment]
Please provide your `brew config` output.

**Comment by starmatt** [comment]
There you go!

HOMEBREW_VERSION: 0.9.5
ORIGIN: (none)
HEAD: (none)
HOMEBREW_PREFIX: /nfs/zfs-student-2/users/2014/mborde/.brew
HOMEBREW_CELLAR: /nfs/zfs-student-2/users/2014/mborde/.brew/Cellar
CPU: quad-core 64-bit ivybridge
OS X: 10.9.5-x86_64
Xcode: 5.0.2
CLT: 6.1.1.0.1.1416017670
Clang: 5.0 build 500
X11: 2.7.5 => /opt/X11
System Ruby: 1.8.7-358
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby

Thanks for taking the time!

**Comment by mikemcquaid** [comment]
I recommend doing `rm -rf ~/.brew` and reinstalling it into that folder at this point. I can't understand why it'd be looking in `/usr/local` unless there's some bad symlinks to there.

**Comment by starmatt** [comment]
I was thinking that the symlinks would be at fault. I tried installing brew to another folder and using new symlinks but I couldn't because they were already use. I then a git clone in an empty .brew folder but it doesn't work either.

**Comment by mikemcquaid** [comment]
Run `echo $PATH`?

**Comment by starmatt** [comment]
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin:/nfs/zfs-student-2/users/2014/mborde/.brew/bin

**Comment by mikemcquaid** [comment]
You need to move `/nfs/zfs-student-2/users/2014/mborde/.brew/bin` from the end to the beginning of your PATH.

**Comment by starmatt** [comment]
Cool, looks like that worked! Thanks a lot. What does it actually changes?

**Comment by mikemcquaid** [comment]
It means you are running the Homebrew in your home directory rather than `/usr/local` when you type `brew`.

**Comment by starmatt** [comment]
Welp, thanks again for the help, I actually learned a lot :)
