### ISSUE TITLE
Pillow fails to build

### ISSUE THREAD

**Issue by captivus** [Homebrew/homebrew#35634]
I'm trying to install pillow after having uninstalled it in hopes to resolve this same issue.  Please see output from the failed build below:

==> Installing pillow from homebrew/homebrew-python
==> Downloading https://github.com/python-pillow/Pillow/archive/2.7.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/pillow-2.7.0.tar.gz
==> Patching
==> python setup.py build_ext --disable-jpeg2000
Building using 4 processes
clang -bundle -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/sqlite/lib build/temp.macosx-10.10-x86_64-2.7/_imagingtk.o build/temp.macosx-10.10-x86_64-2.7/Tk/tkImaging.o -L/usr/local/Cellar/jpeg/8d/lib -L/usr/local/Cellar/libtiff/4.0.3/lib -L/usr/local/Cellar/freetype/2.5.5/lib -L/usr/local/Cellar/little-cms2/2.6/lib -L/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib -L/opt/X11/lib -L/usr/local/lib -L/usr/lib -o build/lib.macosx-10.10-x86_64-2.7/PIL/_imagingtk.so -framework Tcl -framework Tk
clang: error: no such file or directory: 'build/temp.macosx-10.10-x86_64-2.7/_imagingtk.o'
clang: error: no such file or directory: 'build/temp.macosx-10.10-x86_64-2.7/Tk/tkImaging.o'
error: command 'clang' failed with exit status 1

I am running Xcode 6.1.1 and CLT 6.1.1.

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by captivus** [comment]
Apologies.  I think I see what I missed.

**Comment by captivus** [comment]
Here is the gist:  https://gist.github.com/anonymous/51dbcbb3f27fb9c886d2

**Comment by jacknagel** [comment]
>==> Installing pillow from homebrew/homebrew-python

Please file this at https://github.com/Homebrew/homebrew-python, thanks.
