### ISSUE TITLE
More sane ffmpeg defaults

### ISSUE THREAD

**Issue by jonathanong** [Homebrew/homebrew#35636]
can we have more sane defaults for ffmpeg? i hate writing 5 `--with`s every time.

i'd at least like:

- `--with-libvpx`

but also all the formats supported by browsers:

- `--with-theora`
- `--with-libvorbis`

**Comment by mikemcquaid** [comment]
What are the other two?

**Comment by jacknagel** [comment]
A pull request is a great way to start discussion about changes of this nature. Thanks!
