### ISSUE TITLE
python failst to take the letter 'b'

### ISSUE THREAD

**Issue by xychix** [Homebrew/homebrew#35659]
I can type all letters on the python prompt apart from the 'b'
native python bins are working fine problem occurs in python2.7 and python binary (which are the same binaries) in /usr/local/Cellar/python/2.7.9/bin

acdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%^&*()_+-=[]{}\|;':",.<>/?

note the 'b' is missing. US INT keyboard on osx 10.10.1, MacBook Pro (Retina, 13-inch, Mid 2014)

https://gist.github.com/5be0cd571b1ea78dc268

issue in https://downloads.sf.net/project/machomebrew/Bottles/python-2.7.9.yosemite.bottle.8.tar.gz

if I cut 'n paste the word Compatible this happens:
   
 ```
$ python
Python 2.7.9 (default, Jan  7 2015, 11:49:12) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> Compatile
```

this does work, so it's really the 'keystroke' that gives the issue:
```
python -c "print 'bb'"
bb
```

**Comment by patrickfree** [comment]
#27900 seems like it might be similar? Maybe that will help you.

**Comment by xychix** [comment]
The solution is in there :) however it's still odd that the native /usr/bin/python is OK and the brew version /usr/local/bin/python is broken.

issue can be closed
