### ISSUE TITLE
quiet option for brew update?

### ISSUE THREAD

**Issue by fxlb** [Homebrew/homebrew#35662]
I use brew update via Travis-CI.
The command display many lines.

```
$ brew update
Updated Homebrew from 77e2b755 to 98dd6ed6.
==> New Formulae
abi-compliance-checker jenv
aescrypt-packetizer jooby-bootstrap
afl-fuzz jsoncpp
[...]
```
Is there a way to have a quiet command, like `apt-get -qq`?

**Comment by DomT4** [comment]
Given ` brew ` leans on ` git ` to pull changes, and unless you ` brew update ` verbosely ` -q ` from git is already invoked, I'm not sure how much quieter it can get. I guess it could, perhaps/theoretically, be possible to do something like:

```ruby

ARGV.flag? "--quiet"

    if report.empty?
      puts "Already up-to-date."
    else
      puts "Updated Homebrew from #{master_updater.initial_revision[0,8]} to #{master_updater.current_revision[0,8]}."
      report.dump unless ARGV.quiet?
    end
```

**Comment by jacknagel** [comment]
`brew update >/dev/null` :trollface:

**Comment by fxlb** [comment]
@DomT4 Thanks, I don't have an OSX setup to test your idea. I only use the brew command on a Travis-CI builder VM via GitHub.
@jacknagel Thanks, why not, if this is the only way?

**Comment by mikemcquaid** [comment]
Passing on this given @jacknagel's possible workaround.
