### ISSUE TITLE
GHC fails to compile on OSX 10.9 due to dtrace problem

### ISSUE THREAD

**Issue by smarek** [Homebrew/homebrew#35666]
Hello,

same problem with DTrace as in Ruby ( https://github.com/Homebrew/homebrew/issues/32910 )

https://gist.github.com/2f3d581128c090bf9f61

**Comment by jacknagel** [comment]
If the issue is the same, let's not open duplicate issues. Just note that GHC also failed in the other thread.

**Comment by smarek** [comment]
@jacknagel well I'm not perfectly sure the reason is the same, that's why I included logs, and note that it looks similar to DTrace compile `probes.d`, which is issue when compiling Ruby, and cannot be solved the same way as ruby, as this one doesn't have the formula/config level switch to not use dtrace.

You should probably consider reopening this issue, until logs will be reviewed and issue will be confirmed duplicate.

**Comment by smarek** [comment]
Solved the same way as Ruby issue

```
sudo chmod -s /usr/sbin/dtrace
```
