### ISSUE TITLE
Openssl fails to build on 10.10

### ISSUE THREAD

**Issue by dannyfallon** [Homebrew/homebrew#35670]
It seems that both mirrors for openssl-1.0.1j have removed the source because 1.0.1k is available now. I'm not sure whether to upgrade to 1.0.1k or just use the Github source mirror (https://github.com/openssl/openssl/archive/OpenSSL_1_0_1j.tar.gz).

This was working an hour ago so I don't think there's anything major wrong.

```
[danny@helios ~]$ brew install openssl
Warning: Building source; cellar of openssl's bottle is /usr/local/Cellar
==> Downloading https://www.openssl.org/source/openssl-1.0.1j.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://raw.githubusercontent.com/DomT4/LibreMirror/master/OpenSSL/openssl-1.0.1j.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "openssl"
Download failed: https://raw.githubusercontent.com/DomT4/LibreMirror/master/OpenSSL/openssl-1.0.1j.tar.gz
```

======
 Brew Doctor

```
[danny@helios ~]$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have uncommitted modifications to Homebrew
If this a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
    cd /opt/boxen/homebrew/Library && git stash && git clean -d -f

Warning: Your Homebrew is not installed to /usr/local
You can install Homebrew anywhere you want, but some brews may only build
correctly if you install in /usr/local. Sorry!
```

The warnings relate to the use of boxen and not native homebrew.

**Comment by dannyfallon** [comment]
Linking with PR #35665 which I didn't see before opening the issue

**Comment by tdsmith** [comment]
Should be resolved after `brew update`; thanks for reporting.

**Comment by dannyfallon** [comment]
Indeed, works a treat now; thanks for the prompt fix :+1:

**Comment by DomT4** [comment]
Yeah, OpenSSL have started actively killing off their previous version links. I think to reduce the burden on them, and to move people more actively off the old OpenSSL versions.

**Comment by dannyfallon** [comment]
Sure, I can see the rationale for it too. Unfortunately, for several hours today no version of OpenSSL was available via Homebrew because both the openSSL direct link and the sole mirror removed the old source before the formula was updated and merged. 

As a suggestion, could we add the Github source I linked as a third version or could you delay the killing of the old source @DomT4 until after the updated formula gets merged to master?

I'm not sure what the right path is here but it feels bad to break Homebrew OpenSSL even for a few hours, people are depending on it being there (that's the point of the mirror in the first place). What are your own thoughts?

**Comment by DomT4** [comment]
The Homebrew bottles should have still be available and functional, but obviously, yeah, in your case the non-/usr/local brew did cut you off.

In future, I will leave a 24 hour buffer before killing off the old mirror links entirely. Apologies for the breakage.

**Comment by dannyfallon** [comment]
That sounds like a very reasonable solution, thanks @DomT4
