### ISSUE TITLE
Cmake (Sphinx) fails install on Snow Leopard

### ISSUE THREAD

**Issue by nikolaosinlight** [Homebrew/homebrew#35674]
I installed Xcode 4.2 for Snow Leopard (latest Snow Leopard compatible Xcode version) and then ran:
~ > brew update
~ > brew doctor

Although there were some warnings concerning sqlite3 I didn't think they would cause issues...
I then did the following to uninstall Cmake 3.0.1 and attempt to install Cmake 3.1.0
~ > brew uninstall cmake
~ > brew install cmake

However I keep getting this error:
==> make
[100%] sphinx-build man: see Utilities/Sphinx/build-man.log
/bin/sh: /private/tmp/cmake-5y7rxU/cmake-3.1.0/sphinx/bin/sphinx-build: No such file or directory
make[2]: *** [Utilities/Sphinx/doc_format_man] Error 127
make[1]: *** [Utilities/Sphinx/CMakeFiles/documentation.dir/all] Error 2
make: *** [all] Error 2

I tried following some other tips like reinstalling curl but it didn't work.

Anyone know how to solve this issue???

===========================================================================

Full output below
----------------------

~-> brew update
Updated Homebrew from 227463fc to 65f7c8fa.
==> Updated Formulae
dnscrypt-proxy     freeradius-server  lastpass-cli       openssl            tor

~ > brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/sqlite3.h
    /usr/local/include/sqlite3ext.h   

 ~ > brew uninstall cmake
Uninstalling /usr/local/Cellar/cmake/3.0.1...

~ > brew install cmake
==> Downloading http://www.cmake.org/files/v3.1/cmake-3.1.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/cmake-3.1.0.tar.gz
==> Patching
==> Downloading https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.23.tar.gz
Already downloaded: /Library/Caches/Homebrew/cmake--markupsafe-0.23.tar.gz
==> python -c import setuptools... install --prefix=/private/tmp/cmake-5y7rxU/cmake-3.1.0/sphinx --single-version-externally-managed --record=installed.txt
==> Downloading https://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.7.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/cmake--jinja2-2.7.3.tar.gz
==> python -c import setuptools... install --prefix=/private/tmp/cmake-5y7rxU/cmake-3.1.0/sphinx --single-version-externally-managed --record=installed.txt
==> Downloading https://pypi.python.org/packages/source/P/Pygments/Pygments-2.0.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/cmake--pygments-2.0.1.tar.gz
==> python -c import setuptools... install --prefix=/private/tmp/cmake-5y7rxU/cmake-3.1.0/sphinx --single-version-externally-managed --record=installed.txt
==> Downloading https://pypi.python.org/packages/source/d/docutils/docutils-0.12.tar.gz
Already downloaded: /Library/Caches/Homebrew/cmake--docutils-0.12.tar.gz
==> python -c import setuptools... install --prefix=/private/tmp/cmake-5y7rxU/cmake-3.1.0/sphinx --single-version-externally-managed --record=installed.txt
==> Downloading https://pypi.python.org/packages/source/S/Sphinx/Sphinx-1.2.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/cmake--sphinx-1.2.3.tar.gz
==> python -c import setuptools... install --prefix=/private/tmp/cmake-5y7rxU/cmake-3.1.0/sphinx --single-version-externally-managed --record=installed.txt
==> ./bootstrap --prefix=/usr/local/Cellar/cmake/3.1.0 --system-libs --parallel=2 --no-system-libarchive --datadir=/share/cmake --docdir=/share/doc/cmake --mandir=/share/man --sphinx-man --sphinx-build=/private/tmp
==> make
[100%] sphinx-build man: see Utilities/Sphinx/build-man.log
/bin/sh: /private/tmp/cmake-5y7rxU/cmake-3.1.0/sphinx/bin/sphinx-build: No such file or directory
make[2]: *** [Utilities/Sphinx/doc_format_man] Error 127
make[1]: *** [Utilities/Sphinx/CMakeFiles/documentation.dir/all] Error 2
make: *** [all] Error 2

READ THIS: http://git.io/brew-troubleshooting

These open issues may also help:
cmake builds fail on CLT-only with --env=std (https://github.com/Homebrew/homebrew/issues/29101)

**Comment by nikolaosinlight** [comment]
The end goal is to install avidemux with the following however it fails in the same way on cmake:
brew install avidemux

**Comment by mistydemeo** [comment]
> READ THIS: http://git.io/brew-troubleshooting

Please read this and post all of the requested diagnostics, thanks! In particular, we need the output of `brew gist-logs cmake`.

**Comment by nikolaosinlight** [comment]
Thanks.  I did look over that link.  In any event here is a link to the logs:
https://gist.github.com/0ee07b969f636096d29c

**Comment by mistydemeo** [comment]
```
Installing sphinx-apidoc script to /usr/local/share/python
Installing sphinx-build script to /usr/local/share/python
Installing sphinx-quickstart script to /usr/local/share/python
Installing sphinx-autogen script to /usr/local/share/python
writing list of installed files to 'installed.txt'
```

It looks like setup.py is ignoring the passed prefix and installing a global copy of sphinx, which means it's missing from the expected location.

Ping @tdsmith

**Comment by tdsmith** [comment]
Do you have a [distutils configuration file](https://docs.python.org/2.5/inst/config-syntax.html), in e.g. `~/.pydistutils.cfg`? Something is overriding the options we're passing to setup.py.

We can and probably should ask setup.py to ignore those.

You can work around the problem immediately with `brew install cmake --without-docs`.

**Comment by nikolaosinlight** [comment]
No.  I don't have anything with ~/.py*

In fact, I even tried installing sphinx and it still failed (see below).

I imagine --without-docs will solve the issue.  Is there anything anyone wants me to try to further pinpoint the problem before trying that.  Let me know.

brew install sphinx
==> Downloading http://sphinxsearch.com/files/sphinx-2.2.5-release.tar.gz
Already downloaded: /Library/Caches/Homebrew/sphinx-2.2.5.tar.gz
==> Patching
==> Cloning https://github.com/snowballstem/snowball.git
Updating /Library/Caches/Homebrew/sphinx--stemmer--git
==> Checking out revision 9b58e92c965cd7e3208247ace3cc00d173397f3c
==> make dist_libstemmer_c
==> tar xzf dist/libstemmer_c.tgz -C /private/tmp/sphinx-FLyCZM/sphinx-2.2.5-release
==> ./configure --prefix=/usr/local/Cellar/sphinx/2.2.5 --localstatedir=/usr/local/var --with-libstemmer --without-mysql --without-pgsql
==> make install
searchd.cpp:15664: error: 'strnlen' was not declared in this scope
make[2]: *** [searchd.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

READ THIS: http://git.io/brew-troubleshooting

These open issues may also help:
Cmake (Sphinx) fails install on Snow Leopard (https://github.com/Homebrew/homebrew/issues/35674)

**Comment by tdsmith** [comment]
That sphinx is not related to this sphinx; they're different pieces of software.

You're using a very old version of Python and I think we configure it differently now; `brew upgrade python` is probably the most durable fix for you if you don't really need 2.7.3.

**Comment by nikolaosinlight** [comment]
Success.

brew install cmake --without-docs
==> Downloading http://www.cmake.org/files/v3.1/cmake-3.1.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/cmake-3.1.0.tar.gz
==> Patching
==> ./bootstrap --prefix=/usr/local/Cellar/cmake/3.1.0 --system-libs --parallel=2 --no-system-libarchive --datadir=/share/cmake --docdir=/share/doc/cmake --mandir=/share/man

==> make
==> make install
/usr/local/Cellar/cmake/3.1.0: 1800 files, 32M, built in 6.9 minutes

**Comment by nikolaosinlight** [comment]
Okay.  All good.  Thanks.  I was able to install cmake and moreover avidemux.

**Comment by Psithief** [comment]
Had this in my install (trying to install cmake) on Snow Leopard too. Thanks for the workaround.
