### ISSUE TITLE
thrift missing non-blocking libs

### ISSUE THREAD

**Issue by rtjoseph11** [Homebrew/homebrew#35683]
```
uname -a
```
```
Darwin tucker 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64
```

when installing thrift using
```
brew install thrift
```
the installation is missing libthriftnb.dylib, libthriftnb.a, and libthriftnb.la.  This causes things like scribe which depend on the nb library to fail to build.

**Comment by jacknagel** [comment]
I think you want `brew install thrift --with-libevent`.

This can be expressed as a dependency: `depends_on "thrift" => "with-libevent"`
