### ISSUE TITLE
brew breaks because /usr/local/ and /usr/local/etc/ reset to root ownership

### ISSUE THREAD

**Issue by dmullerd** [Homebrew/homebrew#35692]
Hi,

Seems like I need to chown /usr/local/ and /usr/local/etc/ from root to my user name often. Then after a awhile I when I run brew doctor it says:
"
Warning: /usr/local/etc isn't writable.

This can happen if you "sudo make install" software that isn't managed by
by Homebrew. If a formula tries to write a file to this directory, the
install will fail during the link step.

You should probably `chown` /usr/local/etc

Warning: The /usr/local directory is not writable.
Even if this directory was writable when you installed Homebrew, other
software may change permissions on this directory. Some versions of the
"InstantOn" component of Airfoil are known to do this.

You should probably change the ownership and permissions of /usr/local
back to your user account."

When I check ownership it says root.

What could be reseting the directories back to root?

I'm I've got a MacBook Air
OS X 10.9.5

**Comment by dmullerd** [comment]
Must be asking my question improperly. Anyone have any ideas what causes this issue?

**Comment by mikemcquaid** [comment]
Don't know what might be setting them back but try `sudo chown -R $USER /usr/local`.
