### ISSUE TITLE
gcc fails on not finding ISL

### ISSUE THREAD

**Issue by EconGeo** [Homebrew/homebrew#35691]
```
 checking for the correct version of the gmp/mpfr/mpc libraries... yes
checking for version 0.10 of ISL... no
checking for version 0.11 of ISL... no
checking for version 0.12 of ISL... no

configure: error: Unable to find a usable ISL.  See config.log for details. 
```

Can someone please clarify the policy for homebrew.  Shouldn't a formula, particularly one as important as gcc, be a head version and not be put out as THE formula until it successfully installs and the bugs are worked out??  

```brew info isl ``` confirms that I have ISL 0.12.2 installed
https://gist.github.com/0bc9362ef5d8ab613957

**Comment by EconGeo** [comment]
``` 
$ brew missing
grass: gcc
matplotlib: numpy
scipy: numpy
```
numpy won't install because it doesn't have a fortran compiler from gcc

**Comment by EconGeo** [comment]
This is the output when gcc fail and then ISL info
```
checking for the correct version of the gmp/mpfr/mpc libraries... yes
checking for version 0.10 of ISL... no
checking for version 0.11 of ISL... no
checking for version 0.12 of ISL... no
configure: error: Unable to find a usable ISL.  See config.log for details.

READ THIS: http://git.io/brew-troubleshooting

These open issues may also help:
gcc fails on not finding ISL (https://github.com/Homebrew/homebrew/issues/35691)
gcc 4.9.2 fails to produce debugging information (https://github.com/Homebrew/homebrew/issues/34976)
--cc=gcc-4.9 gets me in an infinite loop (https://github.com/Homebrew/homebrew/issues/33731)
MacOS.(gcc|clang|llvm)_version can return nil (https://github.com/Homebrew/homebrew/issues/18781)
$ brew info isl
isl: stable 0.12.2 (bottled), HEAD
http://freecode.com/projects/isl
/usr/local/Cellar/isl/0.12.2 (55 files, 3.1M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/isl.rb
==> Dependencies
Required: gmp ✔
```

**Comment by mistydemeo** [comment]
Try reinstalling isl. If that doesn't work, can you please `brew install -d`, drop to a shell, and grab a copy of the relevant config.log?

**Comment by EconGeo** [comment]
how do I find where the relevant config.log is generated?

**Comment by EconGeo** [comment]
Here is the ISL config.log.  gcc doesn't make it to config.log.  It appears ISL is version 0.14 and gcc is looking for 0.10, 0.11, or 0.12

https://gist.github.com/EconGeo/bb71f8265e68019cd485

**Comment by mistydemeo** [comment]
You have the `HEAD` version of isl installed? We don't explicitly support using isl's `HEAD` version with gcc. Can you please try installing the stable version and see if it works?

**Comment by EconGeo** [comment]
```
brew remove isl
Uninstalling /usr/local/Cellar/isl/0.12.2...
$ brew install isl
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/isl-0.12.2.
Already downloaded: /Library/Caches/Homebrew/isl-0.12.2.mavericks.bottle.2.tar.gz
==> Pouring isl-0.12.2.mavericks.bottle.2.tar.gz
🍺  /usr/local/Cellar/isl/0.12.2: 55 files, 3.1M
$ brew info isl
isl: stable 0.12.2 (bottled), HEAD
http://freecode.com/projects/isl
/usr/local/Cellar/isl/0.12.2 (55 files, 3.1M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/isl.rb
==> Dependencies
Required: gmp ✔
```
it looks like the bottled version is HEAD.  Ive never explicitly installed a head version.  It says its 0.12.2.  How do i get off the head version, do i have to install from source?

**Comment by mistydemeo** [comment]
No, the first line simply lists all available versions. The copy that was installed for you is the stable version, 0.12.2. It should be fine!

**Comment by EconGeo** [comment]
I get a successful install if I ```brew install gcc49``` which points to ISL0.11.  However, when I can't then get any links between gcc and gcc49 to install other programs.  I also have to manually set ```HOMEBREW_CC``` and ```HOMEBREW_CXX``` manually to get brew to install, for example ```brew install r```` .   A ```brew install gcc ``` still fails with the same error as above, not finding ISL.  Any guidance???

**Comment by terrycojones** [comment]
I'm getting the same error on OS X Yosemite 10.10.1:

```
$ brew upgrade gcc
==> Upgrading 1 outdated package, with result:
gcc 4.9.2_1
==> Upgrading gcc
==> Installing gcc dependency: mpfr
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/mpfr-3.1.2-p10.yosemite.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring mpfr-3.1.2-p10.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/mpfr/3.1.2-p10: 24 files, 3.5M
==> Installing gcc
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2
######################################################################## 100.0%
==> ../configure --build=x86_64-apple-darwin14.0.0 --prefix=/usr/local/Cellar/gcc/4.9.2_1 --libdir=/usr/local/Cellar/gcc/4.9.2_1/lib/gcc/4.9 --enable-languages=c,c++,objc,ob
checking for the correct version of the gmp/mpfr/mpc libraries... yes
checking for version 0.10 of ISL... no
checking for version 0.11 of ISL... no
checking for version 0.12 of ISL... no
configure: error: Unable to find a usable ISL.  See config.log for details.
```

Uninstalling / re-installing isl doesn't help, and I already had version 0.12 installed:

```
$ brew install isl
Warning: isl-0.12.2 already installed
$ brew uninstall isl
Uninstalling /usr/local/Cellar/isl/0.12.2...
$ brew install isl
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/isl-0.12.2.yosemite.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring isl-0.12.2.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/isl/0.12.2: 55 files, 3.1M
```

Let me know how/if I can help.

**Comment by terrycojones** [comment]
OK, I fixed this - mainly by following instructions.  My xcode was out of date. So I updated that (to 6.2.2 I think) from the App Store. Then, run `xcode-select --install` to install the command line tools. Then, `open /Applications/XCode.app` and accept the end user agreement. Then, `brew uninstall --force gcc` and `brew install gcc`. Following that I get:

```
$ gcc --version
gcc (Homebrew gcc 4.9.2_1) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

And can compile code without error.

**Comment by alphaparticle** [comment]
I followed the steps mentioned by @terrycojones  , but still unsuccessful . Facing the same errors reported above.

**Comment by pierrewrs** [comment]
Same problem found, it seems 0.12.2(installed) does not match 0.12(requirement), so checking failed.  
`Homebrew 0.9.5` on `OSX10.10.1 (14B25)`

**Comment by jacknagel** [comment]
I think we really need to see the config.log from the failed gcc build. I'm not sure what directory it will be in (either the root or the `build` subdirectory most likely), but if configure is failing it will definitely be somewhere.

**Comment by EconGeo** [comment]
I get a successful build on Mavericks with ```brew install gcc --with-all-languages --without-multilib```

**Comment by shiumachi** [comment]
I hit the same issue but @terrycojones 's solution fixed the problem. Thanks!

**Comment by hustcalm** [comment]
By updating Xcode, issue fixed, thanks for the hint! @terrycojones

**Comment by tuzhucheng** [comment]
Thanks @terrycojones, your solution also works for me on Yosemite and I am using XCode 5.1.1. The trick for me was `xcode-select --install`.

**Comment by JoseAlban** [comment]
@terrycojones tip worked here as well: updated Xcode 5.x to 6.4 (BTW that's what `brew doctor` has told me to do, but I didn't listen to Dr. brew :/ ) (also, updated command line tools)

**Comment by nikolasburk** [comment]
Had the same issue, updating the command line tools using `xcode-select --install` solved it for me.

**Comment by tigerneil** [comment]
Thanks @terrycojones  `xcode-select --install` solved this same problem.

**Comment by ssoto** [comment]
:+1:  I fixed it updating XCode version

**Comment by Alexorz** [comment]
Thanks @terrycojones  :+1:
