### ISSUE TITLE
poco libraries linking against libraries in /private/tmp

### ISSUE THREAD

**Issue by quantumsteve** [Homebrew/homebrew#35702]
I am trying to build an .app bundle that includes several libraries built using Homebrew. In doing so I noticed that many of the poco libraries link against libraries in the directory /private/tmp/poco-I4ZjYj/poco-1.4.7p1-all/lib, which doesn't exist on my computer. For example,
```
$ otool -L libPocoNet.dylib 
libPocoNet.dylib:
	/usr/local/lib/libPocoNet.17.dylib (compatibility version 0.0.0, current version 0.0.0)
	/private/tmp/poco-I4ZjYj/poco-1.4.7p1-all/lib/Darwin/x86_64/libPocoFoundation.17.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
```
CMake's BundleUtilties therefore cannot trace the dependencies and instead generates an error message. May we change the poco formula so all shared poco libraries link against the libraries in /usr/local/lib?

**Comment by mikemcquaid** [comment]
Good idea! Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!

**Comment by quantumsteve** [comment]
I created a pull request that changes the path to lib. 

https://github.com/Homebrew/homebrew/pull/35716
