### ISSUE TITLE
Node Installation Not working

### ISSUE THREAD

**Issue by ezmiller** [Homebrew/homebrew#35719]
When I try to install node via brew, the installation fails with these errors: 

    npm verb exit [ 1, true ]
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /usr/local/lib/node_modules/npm/npm-debug.log
    make: *** [install] Error 1

The npm-debug-log contains these errors:

    26 error Darwin 13.4.0   
    27 error argv "node" "/usr/local/lib/node_modules/npm/cli.js" "install" "-g" "-f"
    28 error node v0.10.35 
    29 error npm  v2.1.17
    30 error Attempt to unlock /usr/local/lib/node_modules/npm, which hasn't been locked 
    31 error If you need help, you may report this error at:
    31 error     <http://github.com/npm/npm/issues>
    32 verbose exit [ 1, true ]

Anyone have any idea what might be going on here? This error at line 30 seems key: "Attempt to unlock /usr/local/lib/node_modules/npm, which hasn't been locked". But it also quite nonsensical: the script is trying to "unlock" a directory that is not "locked"?

**Comment by DomT4** [comment]
[Kill it entirely](https://github.com/DomT4/scripts/tree/master/OSX_Node_Removal) and then try again. There's something lingering around borking the install, by the looks of it.

**Comment by mocerinoj** [comment]
This worked for me
