### ISSUE TITLE
icu4c SHA seems to have changed

### ISSUE THREAD

**Issue by petems** [Homebrew/homebrew#35713]
```
brew install icu4c
Warning: Building source; cellar of icu4c's bottle is /usr/local/Cellar
==> Downloading http://download.icu-project.org/files/icu4c/54.1/icu4c-54_1-src.tgz
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: 8c752490bbf31cea26e20246430cee67d48abe34
Actual: a2fd3379ea944f6b2f97fb0f79b7b85cb3e14d0b
Archive: /opt/boxen/cache/homebrew/icu4c-54.1.tgz
To retry an incomplete download, remove the file above.
```

Sourceforge was a little flaky the last few hours:

```
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/libtool-2.4.4.yosemite.bottle.tar.gz

curl: (56) SSLRead() return error -9806
Error: Failed to download resource "libtool"
```

so it might have a different SHA now.

**Comment by mistydemeo** [comment]
The downloaded content is actually an HTML page from Sourceforge, noting that the site is in "Disaster Recovery mode". You'll need to wait until Sourceforge returns, sorry! You can refetch the content by doing `brew fetch -f icu4c`, or remove the file from your cache.

**Comment by petems** [comment]
Ah I see!

I think I can manually get it by going to http://sourceforge.net/projects/icu/files/ICU4C/54.1/icu4c-54_1-src.tgz in a browser, I'll try that! :)
