### ISSUE TITLE
Subversion fails install on Snow Leopard

### ISSUE THREAD

**Issue by nikolaosinlight** [Homebrew/homebrew#35710]
After getting cmake and avidemux installed through homebrew for some reason something broke with libsqlite i.e. when I tried running the svn client just to see the version I get:

svn -version
dyld: Library not loaded: /usr/local/opt/sqlite/lib/libsqlite3.0.8.6.dylib
  Referenced from: /usr/local/bin/svn
  Reason: image not found
Trace/BPT trap

So I figured I might as well use home as well re-install subversion make javahl failed.

See output below:

brew install --universal --with-java subversion
==> Downloading http://www.apache.org/dyn/closer.cgi?path=subversion/subversion-1.8.10.tar.bz2
Already downloaded: /Library/Caches/Homebrew/subversion-1.8.10.tar.bz2
==> Patching
patching file configure
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
==> Downloading https://serf.googlecode.com/svn/src_releases/serf-1.3.7.tar.bz2
Already downloaded: /Library/Caches/Homebrew/subversion--serf-1.3.7.tar.bz2
==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion/1.8.10_2/libexec/serf GSSAPI=/usr CC=/usr/bin/llvm-gcc CFLAGS=-Os -w -pipe -march=core2 -msse4.1 -mmacosx-version-min=10.6 -arch i386 -arch x86_6
==> /usr/local/opt/scons/bin/scons install
==> ./configure --prefix=/usr/local/Cellar/subversion/1.8.10_2 --with-zlib=/usr --with-sqlite=/usr/local/opt/sqlite --with-serf=/usr/local/Cellar/subversion/1.8.10_2/libexec/serf --disable-mod-activation --disable-nl
==> make
==> make install
==> make tools
==> make install-tools
==> make javahl
subversion/bindings/javahl/native/Array.cpp:45: error: template argument 2 is invalid
subversion/bindings/javahl/native/Array.cpp:51: error: variable or field 'init' declared void
subversion/bindings/javahl/native/Array.cpp:51: error: 'jobjectArray' was not declared in this scope
lipo: can't open input file: /var/folders/DA/DA91I53NH+io5VDIetEmiE+++TQ/-Tmp-//ccs10xeV.out (No such file or directory)
make: *** [subversion/bindings/javahl/native/Array.lo] Error 1

READ THIS: http://git.io/brew-troubleshooting

These open issues may also help:
Subversion fails on 10.10 --with-python (https://github.com/Homebrew/homebrew/issues/34119)

**Comment by nikolaosinlight** [comment]
brew gist-logs subversion
https://gist.github.com/f5002b15efb0b2bea31b

**Comment by nikolaosinlight** [comment]
java -version
java version "1.7.0_25"
Java(TM) SE Runtime Environment (build 1.7.0_25-b15)
Java HotSpot(TM) 64-Bit Server VM (build 23.25-b01, mixed mode)

**Comment by nikolaosinlight** [comment]
I have been doing a lot of research and have yet to find a solution.

Anyone know how to move through the problem of not being able to install javahl.  I am using Coda 2 which is using subversion client to connect to our svn repository and this is causing quite the headache.  Any help would be appreciated.  Thanks.

==> make javahl
subversion/bindings/javahl/native/Array.cpp:45: error: template argument 2 is invalid
subversion/bindings/javahl/native/Array.cpp:51: error: variable or field 'init' declared void
subversion/bindings/javahl/native/Array.cpp:51: error: 'jobjectArray' was not declared in this scope
lipo: can't open input file: /var/folders/DA/DA91I53NH+io5VDIetEmiE+++TQ/-Tmp-//ccs10xeV.out (No such file or directory)
make: *** [subversion/bindings/javahl/native/Array.lo] Error 1

**Comment by DomT4** [comment]
Your ` sqlite ` seems to be out of date? ` /usr/local/opt/sqlite/lib/libsqlite3.0.8.6.dylib ` doesn't exist in the sqlite I have installed via brew recently, I have ` libsqlite3.0.dylib ` and ` libsqlite.dylib `. Maybe there's a difference between newer and older systems in the install, @mistydemeo will probably know more if there is.

```
Unexpected header files:
    /usr/local/include/sqlite3.h
    /usr/local/include/sqlite3ext.h
```

It may be hooking into these *and* the brewed ` sqlite3 ` libs, and causing a mismatch. Try ` rm /usr/local/include/sqlite3.h && rm /usr/local/include/sqlite3ext.h `. After that, do you encounter the same error?

**Comment by mistydemeo** [comment]
The actual error appears to be coming from the Java bindings:

```
/usr/bin/javah -force -d subversion/bindings/javahl/include -classpath subversion/bindings/javahl/classes: org.apache.subversion.javahl.ClientException org.apache.subversion.javahl.ClientNotifyInformation org.apache.subversion.javahl.CommitInfo org.apache.subversion.javahl.CommitItem org.apache.subversion.javahl.CommitItemStateFlags org.apache.subversion.javahl.ConflictDescriptor org.apache.subversion.javahl.ConflictResult org.apache.subversion.javahl.DiffSummary org.apache.subversion.javahl.ISVNClient org.apache.subversion.javahl.ISVNRepos org.apache.subversion.javahl.JNIError org.apache.subversion.javahl.NativeException org.apache.subversion.javahl.NativeResources org.apache.subversion.javahl.ProgressEvent org.apache.subversion.javahl.ReposNotifyInformation org.apache.subversion.javahl.SVNClient org.apache.subversion.javahl.SVNRepos org.apache.subversion.javahl.SubversionException
/usr/bin/javah -force -d subversion/bindings/javahl/include -classpath subversion/bindings/javahl/classes: org.apache.subversion.javahl.callback.BlameCallback org.apache.subversion.javahl.callback.ChangelistCallback org.apache.subversion.javahl.callback.ClientNotifyCallback org.apache.subversion.javahl.callback.CommitCallback org.apache.subversion.javahl.callback.CommitMessageCallback org.apache.subversion.javahl.callback.ConflictResolverCallback org.apache.subversion.javahl.callback.DiffSummaryCallback org.apache.subversion.javahl.callback.ImportFilterCallback org.apache.subversion.javahl.callback.InfoCallback org.apache.subversion.javahl.callback.InheritedProplistCallback org.apache.subversion.javahl.callback.ListCallback org.apache.subversion.javahl.callback.LogMessageCallback org.apache.subversion.javahl.callback.PatchCallback org.apache.subversion.javahl.callback.ProgressCallback org.apache.subversion.javahl.callback.ProplistCallback org.apache.subversion.javahl.callback.ReposFreezeAction org.apache.subversion.javahl.callback.ReposNotifyCallback org.apache.subversion.javahl.callback.StatusCallback org.apache.subversion.javahl.callback.UserPasswordCallback
/usr/bin/javah -force -d subversion/bindings/javahl/include -classpath subversion/bindings/javahl/classes: org.apache.subversion.javahl.types.ChangePath org.apache.subversion.javahl.types.Checksum org.apache.subversion.javahl.types.ConflictVersion org.apache.subversion.javahl.types.CopySource org.apache.subversion.javahl.types.Depth org.apache.subversion.javahl.types.DiffOptions org.apache.subversion.javahl.types.DirEntry org.apache.subversion.javahl.types.Info org.apache.subversion.javahl.types.Lock org.apache.subversion.javahl.types.LogDate org.apache.subversion.javahl.types.Mergeinfo org.apache.subversion.javahl.types.NodeKind org.apache.subversion.javahl.types.Property org.apache.subversion.javahl.types.Revision org.apache.subversion.javahl.types.RevisionRange org.apache.subversion.javahl.types.Status org.apache.subversion.javahl.types.Tristate org.apache.subversion.javahl.types.Version org.apache.subversion.javahl.types.VersionExtended
/bin/sh /private/tmp/subversion-2uigtf/subversion-1.8.10/libtool --tag=CXX --silent --mode=compile /usr/bin/llvm-g++ -std=c++98 -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/readline/include -F/usr/local/Frameworks -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -Os -w -pipe -march=core2 -msse4.1 -mmacosx-version-min=10.6 -arch i386 -arch x86_64 -arch i386 -arch x86_64 -DNDEBUG -I./subversion/include -I./subversion -I/usr/include/apr-1 -I/usr/include/apr-1 -I/usr/local/Cellar/subversion/1.8.10_2/libexec/serf/include/serf-1 -I/usr/local/opt/sqlite/include -I/usr/include -I/System/Library/Frameworks/JavaVM.framework/Headers -I/private/tmp/subversion-2uigtf/subversion-1.8.10/subversion/bindings/javahl/include -o subversion/bindings/javahl/native/Array.lo -c subversion/bindings/javahl/native/Array.cpp
In file included from subversion/bindings/javahl/native/Array.cpp:27:
subversion/bindings/javahl/native/Array.h:30:17: error: jni.h: No such file or directory 
```

It looks like it's unable to find the JNI headers from your Java installation.

**Comment by mistydemeo** [comment]
Do you have the Java for Mac OS X Developer Package installed? The native framework headers aren't provided with Apple's Java.

**Comment by nikolaosinlight** [comment]
For Java versions 6 and below, Apple supplies their own version of Java. For Java versions 7 and above their supplied by Oracle.  I have 1.7.0_25 installed (as per above) hence that doesn't apply.

In addition, I can install subversion 1.8 without using the --universal --with-java.

So I decided to go a different route and install subversion 1.7 and not bother with the --universal --with-java options for now as this is really impeding my work.  I'll re-attempt later this year.  Thanks.

**Comment by mistydemeo** [comment]
The logs indicate it's looking for headers in `/System/Library/Frameworks/JavaVM.framework/Headers`, so it appears to be using Apple Java and not your newer Oracle Java. When you reattempt this, you may need to try exporting `JAVA_HOME` in your environment to make sure Homebrew picks up the correct Java.
