### ISSUE TITLE
Error message even with "brew doctor"

### ISSUE THREAD

**Issue by zhangbright1986** [Homebrew/homebrew#35715]
bright$ brew doctor
Error: user Code doesn't exist
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/utils.rb:203:in `expand_path'
/usr/local/Library/Homebrew/utils.rb:203:in `block in which'
/usr/local/Library/Homebrew/utils.rb:202:in `each'
/usr/local/Library/Homebrew/utils.rb:202:in `which'
/usr/local/Library/Homebrew/os/mac/xcode.rb:78:in `uncached_version'
/usr/local/Library/Homebrew/os/mac/xcode.rb:69:in `version'
/usr/local/Library/Homebrew/os/mac/xcode.rb:126:in `provides_autotools?'
/usr/local/Library/Homebrew/cmd/doctor.rb:879:in `check_for_autoconf'
/usr/local/Library/Homebrew/cmd/doctor.rb:1243:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1241:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1241:in `doctor'
/usr/local/Library/brew.rb:135:in `<main>'

**Comment by zhangbright1986** [comment]
However it is able to do "brew search" and "update", but nothing else

Liangs-MacBook-Pro:~ bright$ brew search wget
wget	   wgetpaste
Liangs-MacBook-Pro:~ bright$ brew doctor
Error: user Code doesn't exist
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/utils.rb:203:in `expand_path'
/usr/local/Library/Homebrew/utils.rb:203:in `block in which'
/usr/local/Library/Homebrew/utils.rb:202:in `each'
/usr/local/Library/Homebrew/utils.rb:202:in `which'
/usr/local/Library/Homebrew/os/mac/xcode.rb:78:in `uncached_version'
/usr/local/Library/Homebrew/os/mac/xcode.rb:69:in `version'
/usr/local/Library/Homebrew/os/mac/xcode.rb:126:in `provides_autotools?'
/usr/local/Library/Homebrew/cmd/doctor.rb:879:in `check_for_autoconf'
/usr/local/Library/Homebrew/cmd/doctor.rb:1243:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1241:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1241:in `doctor'
/usr/local/Library/brew.rb:135:in `<main>'
Liangs-MacBook-Pro:~ bright$ brew update
Already up-to-date.

**Comment by mistydemeo** [comment]
What is your `PATH`?

**Comment by zhangbright1986** [comment]
Hi mistydemeo,
Here is my PATH:

 bright$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Thanks for help !

**Comment by mistydemeo** [comment]
Is it possible that something in your environment is exporting a path containing `~Code` in `PATH` to brew's process? For example, `~Code/some/location`? The error message you pasted is occurring because Ruby's file path expansion is trying to expand `~Code` to the home directory of a user named `Code`, and there's no such user on your system.
