### ISSUE TITLE
Question: what does `brew pin` mean?

### ISSUE THREAD

**Issue by eccstartup** [Homebrew/homebrew#35714]
I am confused with the `pin` command. I see that, even if I pin one formula, I can still reinstall that pinned formulas. Is there a documentation for these commands and the homebrew methodology?

**Comment by DomT4** [comment]
There's a few words on ` brew pin ` [here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md). AFAIK, ` brew pin ` doesn't stop you removing or reinstalling formulae, it is intended purely as an instruction to ` brew ` itself to not update that particular formulae. It's not a firm lock on the end-user, it's just a firm lock on ` brew update/upgrade ` mechanism itself, I believe.

**Comment by eccstartup** [comment]
This FAQ page is really helpful. Thanks!
