### ISSUE TITLE
libpng SHA1 mismatch

### ISSUE THREAD

**Issue by yomexzo** [Homebrew/homebrew#35729]
Already downloaded: /Library/Caches/Homebrew/libpng-1.6.16.yosemite.bottle.tar.gz
	Error: SHA1 mismatch
	Expected: f7b47fcf9d4111075745b04b6fbdb63062982bca
	Actual: 2d0c3d9f99c6d5620230a43bb76b75c12736a8a1
	Archive: /Library/Caches/Homebrew/libpng-1.6.16.yosemite.bottle.tar.gz
	To retry an incomplete download, remove the file above.
	Warning: Bottle installation failed: building from source.
	==> Downloading https://downloads.sf.net/project/libpng/libpng16/1.6.16/libpng-1.6.16.tar.xz
	Already downloaded: /Library/Caches/Homebrew/libpng-1.6.16.tar.xz
	Error: SHA1 mismatch
	Expected: 31855a8438ae795d249574b0da15b34eb0922e13
	Actual: 2d0c3d9f99c6d5620230a43bb76b75c12736a8a1
	Archive: /Library/Caches/Homebrew/libpng-1.6.16.tar.xz
	To retry an incomplete download, remove the file above.

**Comment by mikemcquaid** [comment]
Can't reproduce this; try `brew fetch --force libpng`. You may also want to examine the downloaded file to make sure it's not e.g. an HTML page.

**Comment by yomexzo** [comment]
Thanks @mikemcquaid . Turns out sf.net was blocked on my internet. Checked by pasting download URL in the browser. It worked after switching ISP.
