### ISSUE TITLE
oath-toolkit failed to build on 10.9.5

### ISSUE THREAD

**Issue by ttecon** [Homebrew/homebrew#35731]
https://gist.github.com/9e1f30ca64104f88a89d

```
==> Downloading http://download.savannah.gnu.org/releases/oath-toolkit/oath-toolkit-2.4.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/oath-toolkit-2.4.1.tar.gz
==> Patching
==> ./configure --prefix=/usr/local/Cellar/oath-toolkit/2.4.1
==> make
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in gl
make[2]: *** No rule to make target `all'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

READ THIS: http://git.io/brew-troubleshooting
```

**Comment by ttecon** [comment]
Note: Brew doctor mentions broken symlinks but pruning these doesn't help. I recently reinstalled homebrew and tried to reinstall my formulas. All the formulas that failed resulted in broken symlinks. I already tried to prune and reinstalled but same problems.

**Comment by jacknagel** [comment]
```
(B[mecho 2.4.1 > .version-t && mv .version-t .version
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making (B[mall in gl
make[2]: *** No rule to make target `(B[mall'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

It looks like something is emitting terminal escape sequences in an inappropriate place. The usual culprit is a common unix tool (e.g. grep) that is being configured in your shell config files.

**Comment by ttecon** [comment]
What is the suggested fix?

**Comment by ttecon** [comment]
I found out that removing my `.bash_prompt` which controls the coloring and formatting of my bash prompt fixes the issue. I still don't know what exactly is the problem, though. I do want to keep my customized prompt and if I can pinpoint the problem it will be much helpful.

**Comment by jacknagel** [comment]
Can you narrow it down by commenting some stuff out?

**Comment by jacknagel** [comment]
Closing since the problem has been traced to your dotfiles.
