### ISSUE TITLE
Installing httpd24 has an error

### ISSUE THREAD

**Issue by noelfranc** [Homebrew/homebrew#35737]
https://gist.github.com/d219db434f64d17083e7

brew install httpd24
==> Installing httpd24 from homebrew/homebrew-apache
==> Downloading https://archive.apache.org/dist/httpd/httpd-2.4.10.tar.bz2
Already downloaded: /Library/Caches/Homebrew/httpd24-2.4.10.tar.bz2
==> Patching
==> ./configure --enable-layout=Homebrew --enable-mods-shared=all --enable-uniqu
==> make
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [ab] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

**Comment by jacknagel** [comment]
>==> Installing httpd24 from homebrew/homebrew-apache

Please report this to https://github.com/Homebrew/homebrew-apache, thanks.

**Comment by kppullin** [comment]
For what it's worth, I just ran in to this issue and fixed it by using the `--with-homebrew-openssl` option.

`brew install httpd24 --with-homebrew-openssl`
