### ISSUE TITLE
Can't install npm (asks root/Administrator)

### ISSUE THREAD

**Issue by aristidesfl** [Homebrew/homebrew#35732]
Context: npm was installed before. Tried a `npm update -g` which failed with unavailable npm (I know `npm install -g npm@latest` should be used instead now). Uninstalled npm and node. Now npm doesn't install.

https://gist.github.com/aristidesfl/36f63add87fd6505b340

**Comment by DomT4** [comment]
You might be able to get away with doing ``` sudo chown -R `whoami` ~/.npm && sudo chown -R `whoami` /usr/local ``` but there's a solid 50% chance that won't work.

[If that fails, kill it entirely](https://github.com/DomT4/scripts/tree/master/OSX_Node_Removal) and then try again.

**Comment by aristidesfl** [comment]
Just killed everything, thanks!
