### ISSUE TITLE
Add option for elinks to build with spidermonkey

### ISSUE THREAD

**Issue by secrettriangle** [Homebrew/homebrew#35739]
See [elinks.rb#L36](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/elinks.rb#L36)

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!

**Comment by jacknagel** [comment]
Would review a pull request.
