### ISSUE TITLE
Subversion fails install on Yosemite

### ISSUE THREAD

**Issue by barryhippo** [Homebrew/homebrew#35744]
I have to install subclipe to myeclipse,but javahl not available.

I found homebrew to install javahl,when the last step "brew install --universal --with-java subversion",an error appeared.
Any help would be appreciated. Thanks.

This is the logs:
bogon:~ wh$ brew install --universal --with-java subversion
==> Downloading http://www.apache.org/dyn/closer.cgi?path=subversion/subversion-
Already downloaded: /Library/Caches/Homebrew/subversion-1.8.10.tar.bz2
==> Patching
patching file configure
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
==> Downloading https://serf.googlecode.com/svn/src_releases/serf-1.3.7.tar.bz2
Already downloaded: /Library/Caches/Homebrew/subversion--serf-1.3.7.tar.bz2
==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion/1.8.10_2/
    env.ParseConfig('$APU --ldflags --includes --link-ld --libs')
  File "/usr/local/Cellar/scons/2.3.4/libexec/scons-local/SCons/Environment.py", line 1579:
    return function(self, self.backtick(command))
  File "/usr/local/Cellar/scons/2.3.4/libexec/scons-local/SCons/Environment.py", line 597:
    raise OSError("'%s' exited %d" % (command, status))

READ THIS: http://git.io/brew-troubleshooting

These open issues may also help:
Subversion fails install on Snow Leopard (https://github.com/Homebrew/homebrew/issues/35710)
Subversion fails on 10.10 --with-python (https://github.com/Homebrew/homebrew/issues/34119)

**Comment by jacknagel** [comment]
>READ THIS: http://git.io/brew-troubleshooting

**Comment by barryhippo** [comment]
I have tried all of the method("READ THIS: http://git.io/brew-troubleshooting"),but no solution.

**Comment by mistydemeo** [comment]
We need the debug logs listed in that link, such as the output of `brew gist-logs subversion`.

**Comment by barryhippo** [comment]
the debug logs link:https://gist.github.com/anonymous/2f372be33c29fc5e6c86

**Comment by mistydemeo** [comment]
Try reinstalling apr and apr-util, then installing subversion again.

**Comment by barryhippo** [comment]
Thanks for you help.This problem been resolved.But another appeared,this is the logs:
https://gist.github.com/6bae0bc8f2649ad2ff43
