### ISSUE TITLE
cntlm failed to build on OS 10.6.8

### ISSUE THREAD

**Issue by giskard22** [Homebrew/homebrew#35750]
On OS 10.6.8 with last available Xcode (4.2), cntlm fails to build. This error appears multiple times:

    cc1: error: unrecognized command line option "-Wno-unused-but-set-variable"

See https://gist.github.com/d93de192bdaa332ac7a3 for full output.

Quick uninformed research seems to indicate this option requires a newer version of GCC than you get with Xcode 4.2. I'm not sure this is actually a homebrew issue because you get the same error if you manually download and compile. If this is more properly reported to the cntlm project, please let me know.

**Comment by herau** [comment]
same issue on MAC OS 10.10.1 with Xcode 5.1.1

**Comment by giskard22** [comment]
Do you mean Xcode 6.1.1? That's what I have on my 10.10.1 system.

I was just able to `brew install cntlm` on 10.10.1 with no errors. The resulting binary is working as expected.

**Comment by mistydemeo** [comment]
Fixed by making superenv filter out this flag - thanks for the report!

**Comment by giskard22** [comment]
Cool, thanks!

**Comment by herau** [comment]
@mistydemeo what is the next version of Homebrew which will contains the fix please ?

**Comment by mikemcquaid** [comment]
> @mistydemeo what is the next version of Homebrew which will contains the fix please ?

run `brew update`

**Comment by herau** [comment]
Already done. but i have another issue (brew version 0.9.5) :

==> Downloading
https://downloads.sourceforge.net/project/cntlm/cntlm/cntlm%200.92.3/cntlm-0.92.3.tar.bz2

==> Patching

==> ./configure

==> make CC=clang SYSCONFDIR=/usr/local/etc

http.c:22:10: fatal error: 'sys/types.h' file not found

#include <sys/types.h>

         ^

1 error generated.

make: *** [http.o] Error 1

READ THIS: http://git.io/brew-troubleshooting

These open issues may also help:

cntlm formula generates launchd plist with problematic file path (
https://github.com/Homebrew/homebrew/issues/35878)

**Comment by mikemcquaid** [comment]
> READ THIS: http://git.io/brew-troubleshooting

Please do and create a new issue.

**Comment by herau** [comment]
sorry, the issue was the version of Xcode. no problem with XCode 6.1
