### ISSUE TITLE
Solr fails to start due to nonexisting log directory

### ISSUE THREAD

**Issue by cygri** [Homebrew/homebrew#35775]
$ brew install solr

This installs 4.10.2. I follow the caveat instructions for starting Solr manually:

    $ solr start

```
/usr/local/bin/solr: line 892: /usr/local/Cellar/solr/4.10.2/example/logs/solr-8983-console.log: No such file or directory
Waiting to see Solr listening on port 8983 [-]  Still not seeing Solr listening on 8983 after 30 seconds!
tail: /usr/local/Cellar/solr/4.10.2/example/logs/solr.log: No such file or directory
```

It turns out that the directory `/usr/local/Cellar/solr/4.10.2/example/logs` doesn't exist. The parent directory is there. Let's try to fix it:

    $ mkdir /usr/local/Cellar/solr/4.10.2/example/logs
    $ solr start

```
Waiting to see Solr listening on port 8983 [/]  
Started Solr server on port 8983 (pid=18445). Happy searching!
```

So, creating the directory solved the problem. Should the formula create the directory?

**Comment by mikemcquaid** [comment]
> So, creating the directory solved the problem. Should the formula create the directory?

Yes. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!

**Comment by jsamoocha** [comment]
Created pull request #35999
