### ISSUE TITLE
Maven Installation Issue

### ISSUE THREAD

**Issue by lloy0076** [Homebrew/homebrew#35773]
# Brew Version

Mordor:storm-starter lloy0076$ brew --version
0.9.5

# What's Wrong

```
Mordor:storm-starter lloy0076$ brew install maven30
==> Installing maven30 from homebrew/homebrew-versions
==> Downloading http://www.apache.org/dyn/closer.cgi?path=maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz
Error: Failed to download resource "maven30"
```
# Possible Fix

This is a kludge but from [this link](http://stackoverflow.com/questions/12757694/brew-install-maven-404-error) and using one of Australia's local mirrors and changing the sha1 to md5, like this:

```
  1 require 'formula'
  2 
  3 class Maven < Formula
  4   homepage 'http://maven.apache.org/'
  5   #url 'http://www.apache.org/dyn/closer.cgi?path=maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz'
  6   url 'http://apache.mirror.digitalpacific.com.au/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz'
  7   md5 'b2d88f02bd3a08a9df1f0b0126ebd8dc'
```

# What I Think is Wrong

I don't think the original URL (with the 'dyn' in it) seems to be working. Tried with plain Firefox and it just brought me to the mirror list page.

# Proposed Fix

Not sure, to be honest. Hard coding the mirror would defeat the purpose of the mirror list but it seems something upstream might have unexpectedly changed.

**Comment by lloy0076** [comment]
All the maven brews available seem to be affected (maven maven30 maven31).

**Comment by jacknagel** [comment]
Working OK here:

```
$ brew fetch maven
==> Downloading http://www.apache.org/dyn/closer.cgi?path=maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz
==> Best Mirror http://mirror.tcpdiag.net/apache/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz
######################################################################## 100.0%
Downloaded to: /Library/Caches/Homebrew/maven-3.2.5.tar.gz
SHA1: 41009327d5494e0e8970b25b77ffed8934cd7ca1
SHA256: 8c190264bdf591ff9f1268dc0ad940a2726f9e958e367716a09b8aaa7e74a755
```

Probably just a temporary network issue.
