### ISSUE TITLE
htop does not work (should be built with -m32) 

### ISSUE THREAD

**Issue by msmummy** [Homebrew/homebrew#35798]
htop does not work with a rmbp 15 with yosemite, displays:

malloc: *** error for object 0x7fab32e06800: incorrect checksum for freed object - object was probably modified after being freed.
                                                                 
After a few googling, it seems that it should be built with CFLAGS="-m32", as seen here https://github.com/AndyA/htop-osx/issues/1

**Comment by mikemcquaid** [comment]
It was updated yesterday, can you see if that fixes it?

**Comment by mikemcquaid** [comment]
Also: sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!
