### ISSUE TITLE
gcc with fortran only?

### ISSUE THREAD

**Issue by davydden** [Homebrew/homebrew#35807]
I was thinking that it would be nice to have an option to build `gcc` with `Fortran` language only, as it is often installed to have `fortran` compiler to compliment `clang`.

I tried playing with `language` parameter in the Formula, but `configure` always decides to add `c,c++` languages if those only `fortran` was requested. 

If this idea make sense, would be nice if it is implemented.

**Comment by mikemcquaid** [comment]
We'll pass on this as it will make it more complex to handle this case where we need GCC to build C/C++ code but it's been built without that support.
