### ISSUE TITLE
version restrictions / .rb file name and class name / homebrew-versions?

### ISSUE THREAD

**Issue by davydden** [Homebrew/homebrew#35813]
I suppose if a particular formula requires certain version of dependencies the only way currently is to look for it in homebrew-versions? 

In such a case, say, `Boost149` is installed in `Cellar/Boost149/1.49.0`. 
Would not that be better to allow "custom name" so that those specific versions could be installed, say, to `Cellar/Boost/1.49.0` and the the user could switch later on between different versions?
To my understanding this is related to a constrain of `.rb` script to have the same name as the class name inside. Could this constrained be dropped at some point?
I suppose that could also made it easier not to rewrite some formulas to, say, `depends_on boost149` and keep it, say, `depends_on boost`. 
Perhaps even some simple way to add version dependency check could be implemented. 
Currently if one calls `brew info XXX` then the info on all versions installed and current one linked is there. So i suppose one could do some checks that the currently active version is >= or == etc (parse the string of the folder)? 

The question of versioning in Homebrew arise quite often (e.g. https://github.com/Homebrew/homebrew-science/issues/1602 and the discussion on Petsc mailing list: http://lists.mcs.anl.gov/pipermail/petsc-dev/2014-December/016601.html ). It would be very nice to have some version checks so that Homebrew fills that gap with MacPorts. The discussion above is related to the version checking, but maintainance of different versions is another story, of course. IMHO homebrew-versions is enough as long as those Formulae install in the same `Cellar/name` as the current `HEAD` versions. 
Which is also consistent to cases when users do not clean-up Cellar, and all formulas accumulate different versions in `/Cellar/MyFormula/`: `x.x.x`, `y.y.y`, `z.z.z`, etc.

**Comment by mikemcquaid** [comment]
There's two issues here:
- handling packages with different `option`s
- handling packages which require an old `version` of a package than the one in core.

We do support the prior and we explicitly try not to support the latter (although `homebrew-versions` is indeed our solution to that).

**Comment by davydden** [comment]
Don't you think that handling package which require and olderer version of a package than the one in core is actually a requirement for a robust package manager? If you read the discussion in the mailing list related to scientific software, then it is obvious that this is the main reason why some people avoid Homebrew. 

I just think that the solution above could be an easy-to-do workaround, of course, given that the authors consider this as an important feature. IMHO it is really a shame if Homebrew authors explicitly avoid any versioning dependence even when this is required to have a software working. 

At the end of the day, users need to have a robust installation / tool-chain of some software, be it scientific-related or not. And this might require some version limitations/control. For example, `petsc` (if I am not mistaken) will not compile with `superlu_dist` of the most recent version `4.0`, but needs `3.3`. Same was the case for `deal.II 8.2.0` which fails to build with `cmake` `3.1.0` as there is a bug there compared to `cmake` `3.0.2`. These are just some examples I saw related to scientific software. 

Could you please explain what are your rationale for avoiding this feature in Homebrew or linking to relevant discussion elsewhere?

**Comment by mikemcquaid** [comment]
> Don't you think that handling package which require and olderer version of a package than the one in core is actually a requirement for a robust package manager?

As I've said: we do handle that through `homebrew-versions`. I don't think having these things in the main repository is a requirement, no.

> I just think that the solution above could be an easy-to-do workaround

Without meaning to be too rude: it's rather arrogant to assume that there's a really easy workaround that people working on Homebrew for 7 years haven't spotted. Also, if it's really easy then an pull-request implementing it would be more useful than an issue.

> Could you please explain what are your rationale for avoiding this feature in Homebrew or linking to relevant discussion elsewhere?

I've explained this above. The further case where we handle this is just vendoring a newer or older version inside the package's prefix so the older version is installed just for that one piece of software.

I don't think further discussion would be particularly valuable, honestly. You can browse through our issue tracker and mailing list to read more about these discussions.
