### ISSUE TITLE
gnuplot 5.0 --with-wxmac fails to compile wxt terminal

### ISSUE THREAD

**Issue by silberzwiebel** [Homebrew/homebrew#35815]
Hi there,

don't know if I missed the appropriate line in `brew options gnuplot`, but if I compile gnuplot 5.0 with the following line, I expected that the wxt terminal would be available:
`brew install gnuplot --with-wxmac`
However, there is no wxt terminal available in gnuplot. During the preparation of this issue I found the message in the [log](https://gist.github.com/anonymous/0afcefbf36ccefbd76f0), that cairo is also needed. So, compiling gnuplot with `brew install gnuplot --with-wxmac --with-cairo`  resulted in a gnuplot version with the wxt terminal. Maybe you could consider adding informations on how to obtain the wxt terminal?

Thanks, 
silberzwiebel

**Comment by DomT4** [comment]
Seems to be there already?

```
brew info gnuplot
==> Options
--with-aquaterm
	Build with AquaTerm support
--with-cairo
	Build the Cairo based terminals
--with-latex
	Build with LaTeX support
--with-pdflib-lite
	Build with pdflib-lite support
--with-qt
	Build with qt support
--with-tests
	Verify the build with make check (1 min)
--with-wxmac
	Build with wxmac support
--with-x11
	Build with x11 support
--without-emacs
	Do not build Emacs lisp files
--without-gd
	Build without gd support
--without-lua
	Build without the lua/TikZ terminal
--HEAD
	Install HEAD version
```

Unless you were looking for a more verbose option? Such as ` --with-cairo, "Build the Cairo based terminals, i.e. wxt terminal" `?

**Comment by silberzwiebel** [comment]
I was confused that the `--with-wxmac` option did not compile the wxt terminal. I'm not into all of gnuplot's dependencies and just thought that this is the right option. However, the warning that the wxt terminal will not be built due to missing cairo dependency is not passed on the `brew install gnuplot --with-wxmac` command. I just found this by accident.

**Comment by DomT4** [comment]
I submitted #35833 as a proposed fix, if that's any good?

**Comment by jacknagel** [comment]
The wxmac option [introduces a dependency on pango](https://github.com/Homebrew/homebrew/blob/73ede54b7156fd66d79480f0e5c6b9f22f047f6d/Library/Formula/gnuplot.rb#L52), which itself depends on cairo. However we [explicitly disable cairo](https://github.com/Homebrew/homebrew/blob/73ede54b7156fd66d79480f0e5c6b9f22f047f6d/Library/Formula/gnuplot.rb#L83) unless `with-cairo` is passed. That seems wrong to me.

Maybe this?

```diff
diff --git a/Library/Formula/gnuplot.rb b/Library/Formula/gnuplot.rb
index 75f485a..4d9b374 100644
--- a/Library/Formula/gnuplot.rb
+++ b/Library/Formula/gnuplot.rb
@@ -80,7 +80,7 @@ def install
     args << "--with-pdf=#{pdflib}" if build.with? "pdflib-lite"
     args << ((build.with? "gd") ? "--with-gd=#{gd}" : "--without-gd")
     args << "--disable-wxwidgets"  if build.without? "wxmac"
-    args << "--without-cairo"      if build.without? "cairo"
+    args << "--without-cairo"      if build.without? "cairo" and build.without? "wxmac"
     args << "--enable-qt"          if build.with? "qt"
     args << "--without-lua"        if build.without? "lua"
     args << "--without-lisp-files" if build.without? "emacs"
```

**Comment by DomT4** [comment]
Oh, blurgh. Never noticed that. That's a strange mix of conflicting instructions. Your patch looks like a good fix.
