### ISSUE TITLE
Python 3.4 is too new

### ISSUE THREAD

**Issue by sc68cal** [Homebrew/homebrew#35829]
Hi,

As an OpenStack developer, I use python3 for some of the projects, with Tox. However, OpenStack is currently targeting only the stable branch of Python 3, which is still [currently only Python 3.3.6](https://docs.python.org/3.3/), while Python 3.4 is still under development. Can we please stick to stable releases of the Python 3 language, or at least provide a formula for the stable versions?

Thanks

**Comment by mikemcquaid** [comment]
Python 3.4 is a stable version. If you'd like a formula for Python 3.3 I'd suggest submitting a pull-request in `homebrew-versions` to add it.

**Comment by mistydemeo** [comment]
Python 3.4 is the current Python 3 release advertised by python.org; we tend to use the latest stable version released by the upstream project, except in exceptional circumstances.

We do maintain packages for previous versions of many languages (and packages) in `homebrew-versions`, and while we don't have 3.3 there we'd certainly accept a PR to add it.

**Comment by sc68cal** [comment]
OK, thanks - that is a sufficient answer :)
