### ISSUE TITLE
grep -P does not work on OS X 10.8.5

### ISSUE THREAD

**Issue by stantonk** [Homebrew/homebrew#35848]
I have two laptops with OS X 10.8.5. I've installed coreutils and grep using the instructions here:

http://www.topbug.net/blog/2013/04/14/install-and-use-gnu-command-line-tools-in-mac-os-x/

On my 2nd laptop, the grep installed to /usr/local/bin/grep doesn't work when supplying the -P argument, e.g.

$ echo "duck" | grep -P "uc"

usage: grep [-abcDEFGHhIiJLlmnOoPqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]

Any ideas?

**Comment by mistydemeo** [comment]
That error message comes from the OS's `grep`. Homebrew's grep is installed as `ggrep` by default; we recently transitioned the `default-names` option to `with-default-names` for consistency with other software in Homebrew, and it looks like the blog suggests using the old name. You can confirm by doing:

```sh
$ echo "duck" | ggrep -P "uc"
```

You can either alias `ggrep` to `grep`, or reinstall `grep` using the `--with-default-names` option.

**Comment by stantonk** [comment]
That doesn't work on my machine. Moreover, grep is actually coming from /usr/local/bin/grep, which is symlinked to:

lrwxr-xr-x  1 stantonk  admin     28 Jan 13 21:02 grep -> ../Cellar/grep/2.21/bin/grep

$ echo "duck" | ggrep -P "uc"
-bash: ggrep: command not found
$ which grep
/usr/local/bin/grep

:-(

**Comment by stantonk** [comment]
@mistydemeo oddly enough, reinstalling with the flag fixed it. the old flag must do something mysterious :).

thanks
