### ISSUE TITLE
Error: SHA256 mismatch

### ISSUE THREAD

**Issue by liboshi** [Homebrew/homebrew#35858]
When I try to update perforce with brew, the SHA256 mismatch error pop-up.
I have tried following actions:
1. Uninstall perforce and then re-install perforce. -- Error reproduced 
2. brew clean up && brew uninstall perforce && brew update && brew install perforce -- Error reproduced

I think maybe the downloading process is not finished indeed.

Could you help on this?

Thanks in advance.
-Boush

**Comment by liboshi** [comment]
More information:
1. Mac XOS Version: 10.10.1 64bit
2. Ruby Version: 2.0.0p481
3. Git Version: 1.9.3

-Boush

**Comment by DomT4** [comment]
Afraid this needs reporting to [Homebrew-binary](https://github.com/Homebrew/homebrew-binary) as they're the ones shipping that particular formulae. The link has been broken for a while by the looks of #35565.
