### ISSUE TITLE
set go environment automatically

### ISSUE THREAD

**Issue by muhasturk** [Homebrew/homebrew#35869]
Please set go-lang environment **GOROOT** and **GOPATH** automatically after `brew install go`

![goroot and gopath on idea](https://downloader-ams1.disk.yandex.com.tr/rdisk/f599a148467f84278bd3b1e1698f9786/mpfs/cBlTn2mtWIOFCh5dCM5nplPOnyyUq1DSO2MC19-Y8xHHrYADhjmGbU84vpbMtm419qsstrCOK3n_-GiCf7mU7A==?uid=0&filename=2015-01-14%2011-31-55%20misc.xml%20-%20%5Buntitled1%5D%20-%20untitled1%20-%20%5B%20tmp%20untitled1%5D.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&rtoken=e0c6a0971526e0c1e9d10530e0f74627&rtimestamp=54b63796&force_default=no)

Discussed here
- https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/Missing%20ENV.md#--mac-os-x
- http://stackoverflow.com/questions/7970390/what-should-be-the-values-of-gopath-and-goroot
- http://stackoverflow.com/questions/12843063/install-go-with-brew-and-running-the-gotour
- https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/318#issuecomment-31303939

**Comment by mikemcquaid** [comment]
We can't set environment variables automatically, you need to do that in your e.g. `.bashrc`.
