### ISSUE TITLE
bash-completion: special character in filename breaks completion

### ISSUE THREAD

**Issue by elferink** [Homebrew/homebrew#35872]
This was bugging me for a while but I finally found the reason I was getting these errors.

This is the error:
bash: eval: line -848: syntax error: unexpected end of file
bash: eval: line -849: unexpected EOF while looking for matching `''

It gets triggered by line 106 in bash_completion:
complete -f -X '*.@(o|so|so.!(conf)|a|[rs]pm|gif|jp?(e)g|mp3|mp?(e)g|avi|asf|ogg|class)' vi vim gvim rvim view rview rgvim rgview gview emac

The error occurs when using one of these commands and a file with one of these extensions is present but has a special character in the filename.
Example:

~/test $ ls
test'.mp3
~/test $ vim **{Press tab}** *bash: eval: line -849: unexpected EOF while looking for matching `''
bash: eval: line -848: syntax error: unexpected end of file*
~/test $ mv test\'.mp3 \'.gif
~/test $ ls
'.gif
~/test $ view **{Press tab}** *bash: eval: line -849: unexpected EOF while looking for matching `''
bash: eval: line -848: syntax error: unexpected end of file*
~/test $ cp \'.gif \'.jpg
~/test $ ls
'.gif '.jpg
~/test $ view **{Press tab}**
now nothing happens and tab completion is broken for that directory

This also fails in the same way with " and `, with a : tab completion is broken.

If needed/wanted, my gist-log:
https://gist.github.com/anonymous/1ca0e5f656a422c5dada

**Comment by jacknagel** [comment]
Does this also happen with bash-completion2 from homebrew-versions (requires bash from homebrew)?

**Comment by elferink** [comment]
I get a different error but it happens before even using completion.
This is what I did, error is at the end.

~ $ brew install bash
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/bash-4.3.33.yosemite.bottle.tar.gz
...
==> Summary
🍺  /usr/local/Cellar/bash/4.3.33: 59 files, 7,4M
~ $ brew tap homebrew/versions
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-versions'...
...
Tapped 171 formulae
~ $ brew install bash-completion2
==> Installing bash-completion2 from homebrew/homebrew-versions
Error: Cannot install bash-completion2 because conflicting formulae are installed.

  bash-completion

Please `brew unlink bash-completion` before continuing.
...
~ $ brew unlink bash-completion
Unlinking /usr/local/Cellar/bash-completion/1.3... 184 symlinks removed
~ $ brew install bash-completion2
==> Installing bash-completion2 from homebrew/homebrew-versions
==> Downloading http://ftp.de.debian.org/debian/pool/main/b/bash-completion/bash-completion_2.1.orig.tar.bz2
...
Add the following to your ~/.bash_profile:
  if [ -f $(brew --prefix)/share/bash-completion/bash_completion ]; then
    . $(brew --prefix)/share/bash-completion/bash_completion
  fi
...
==> Summary
🍺  /usr/local/Cellar/bash-completion2/2.1_2: 387 files, 2,6M, built in 23 seconds
~ $ which bash
/usr/local/bin/bash
~ $ bash --version
GNU bash, versie 4.3.33(1)-release (x86_64-apple-darwin14.1.0)


added the following to .bashrc
  if [ -f $(brew --prefix)/share/bash-completion/bash_completion ]; then
    . $(brew --prefix)/share/bash-completion/bash_completion
  fi

opened new window, it immediately shows this:

bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
bash: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]
~ $

**Comment by jacknagel** [comment]
You would have to manually enter a bash 4 shell (i.e. run `/usr/local/bin/bash`); your default shell is still set to /bin/bash.

**Comment by elferink** [comment]
It seems my default shell indeed was /bin/bash.
The error does not occur in bash-completion2, tab completion fails silently when there is a file a quote present.
Meaning there is no tab completion whatsoever when a special character is present.
Doesn't seem like the proper solution.

**Comment by jacknagel** [comment]
I think this is an upstream issue. Probably there won't be a fix for bash-completion 1.x, but 2.x can probably be fixed if you file a bug with the bash-completion project.

**Comment by jacknagel** [comment]
Needs to go upstream. Bash-completion 1.x is legacy software at this point, and is only provided due to the very old version of bash that ships with OS X. 2.x can probably be patched, but that patch isn't going to come from us, unfortunately.
