### ISSUE TITLE
Objective-caml install: bug in symlinks

### ISSUE THREAD

**Issue by toots** [Homebrew/homebrew#35898]
After a fresh install from the `objective-caml` `yosemite` bottle, I get:

```
✗ ls /usr/local/lib/ocaml
site-lib -> ../../Cellar/objective-caml/4.02.1_1/lib/ocaml/site-lib

✗ ls /usr/local/Cellar/objective-caml/4.02.1_1/lib/ocaml/
site-lib -> ../../../../../lib/ocaml/site-lib
```

Which loops back to `/usr/local/lib/ocaml`...
Which is a

**Comment by jacknagel** [comment]
This should be resolved by 178763c5f0c7b9b0000baff7c5bdab681fbeab13. You may want to manually remove /usr/local/lib/ocaml before upgrading.
