### ISSUE TITLE
Question: How Hombrew handles `conflicts_with`?

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew#35891]
I used to think if I add `conflicts_with "B"` in formula A, the formula B will be automatically aware of that without the need of adding `conflicts_with "A"` in formula B. Therefore, I offered a wrong suggestion [here](https://github.com/Homebrew/homebrew/pull/35853#discussion_r22949288). But a simple test shows me wrong. The `conflicts_with` only works for one way not the other way around. The associated code is [here](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/formula_installer.rb#L191-L200).

So the question is should we keep this as it is or adding the ability to homebrew core to make `conflicts_with` work for both formulae. Of course, there are pros and cons.

* **Pros**: It's more nature. A formula can never be aware of all of other formulae who conflicts with itself. Especially if the conflict occurs in different taps.
* **Cons**: How we implement it without the sacrifice of performance?

**Comment by jacknagel** [comment]
This was discussed in the past, and it was decided that we want the declaration to be present in both formulae for discoverability reasons.
