### ISSUE TITLE
pyqt5.3.1 failed to build on 10.10.1

### ISSUE THREAD

**Issue by AdrienGiboire** [Homebrew/homebrew#35912]
Here is the gist: https://gist.github.com/anonymous/e1b520a67dc66dfc6f7a
Tell me if I can bring more infos.

**Comment by tdsmith** [comment]
Is your python a framework build or a unix layout build? This may be a pyqt5 issue with non-framework builds on darwin.

**Comment by AdrienGiboire** [comment]
@tdsmith How can I know this?

**Comment by tdsmith** [comment]
If ``otool -L `which python` `` contains the string Python.framework it's probably a framework build.

**Comment by tdsmith** [comment]
Googling "pyenv framework," it looks like you don't get one unless you ask for one. Here is how to ask for one: https://github.com/yyuu/pyenv/issues/99#issuecomment-35045985

I think this is not a Homebrew issue, so closing.
