### ISSUE TITLE
typesafe-activator 2.1.12 Permission denied on running activator

### ISSUE THREAD

**Issue by povman** [Homebrew/homebrew#35922]
I have installed typesafe-activator as user lukeworth, then tried to run `activator` as user lukeworthdm (different user!), and I get this error:

```
ravel:~ lukeworthdm$ activator
/usr/local/bin/activator: line 2: /usr/local/Cellar/typesafe-activator/1.2.12/libexec/activator: Permission denied
/usr/local/bin/activator: line 2: exec: /usr/local/Cellar/typesafe-activator/1.2.12/libexec/activator: cannot execute: Undefined error: 0
ravel:~ lukeworthdm$ ls -l /usr/local/Cellar/typesafe-activator/1.2.12/libexec/activator
-rwxrw-r--  1 lukeworth  wheel  9507  5 Dec 02:15 /usr/local/Cellar/typesafe-activator/1.2.12/libexec/activator
```

**Comment by mikemcquaid** [comment]
Are both users in the `wheel` group? We don't really support multiple-user setups; you may need to mess around with permissions on a package-by-package basis.

**Comment by jacknagel** [comment]
Closing due to no response.

**Comment by povman** [comment]
Everything else I have installed on homebrew has worked fine in both users, and the FAQ says "If you need to run Homebrew in a multi-user environment, consider creating a separate user account especially for use of Homebrew." - implying that it does support multi-user.

AFAICT the problem is "-rwxrw-r--" rather than what user the file belongs to.

```
ravel:~ lukeworthdm$ ls -l /usr/local/Cellar/typesafe-activator/1.2.12/bin/activator
-r-xr-xr-x  1 lukeworth  admin  86 Jan 16 10:36 /usr/local/Cellar/typesafe-activator/1.2.12/bin/activator
```

lukeworthdm has no trouble executing bin/activator, only libexec/activator.

**Comment by povman** [comment]
Changing the permissions of /usr/local/Cellar/typesafe-activator/1.2.12/libexec/activator to -rwxrwxr-x make activator run under lukeworthdm
