### ISSUE TITLE
Update sip/pyqt/pyqt5

### ISSUE THREAD

**Issue by The-Compiler** [Homebrew/homebrew#35934]
The following packages are outdated:

* sip: 4.16.3 packaged, 4.16.5 available upstream
* pyqt: 4.11.1 packaged, 4.11.3 available upstream
* pyqt5: 5.3.2 packaged, 5.4 available upstream

I tried to update pyqt5 to submit a pull request, but it also needs sip to be updated, and pyqt uses bottles, so I'm unsure what to do exactly - probably it'd make more sense if someone more knowledgeable would update this.

**Comment by mikemcquaid** [comment]
Just ignore the bottles, they are updated when we pull. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!

**Comment by The-Compiler** [comment]
Okay, so what I have to do is basically this, correct?

* Update versions and (source-) checksums for all three packages
* See if they install properly and the tests pass
* Submit a pull request

**Comment by mikemcquaid** [comment]
@The-Compiler Yup, exactly :+1:

**Comment by tdsmith** [comment]
Closing in favor of the PR; thanks!
