### ISSUE TITLE
Homebrew not honoring build flags for dependencies

### ISSUE THREAD

**Issue by fran6co** [Homebrew/homebrew#35948]
I'm hitting a bug because of this change https://github.com/Homebrew/homebrew/commit/e5589b6cd6780481144b28c3dcb78ce1155e9756#diff-8783bcea32de23d83793348b802ab052L32 (maybe it had the same problem before too). If I'm installing a formula from scratch that sets a flag for a dependency, that dependency ignores that flag when calculating its dependencies.

I'm hitting this bug with the formula ```homebrew/science/pcl```, it can be reproduced by not having the ```sip``` and ```vtk``` packages installed and making a simple install ```brew install homebrew/science/pcl```. It will complain that ```sip``` is not installed without trying to installing it in the first place.

The rundown is something like this:

1.  ```Dependency``` calculates the dependencies of ```pcl```
2.  When it gets to the ```vtk``` dependency, it converts it to a formula and then injects the build option ```--with-qt```
3. The build options goes to the formula but not to the underlying active_spec, that has it's own empty BuildOption object
4. ```Dependency``` asks for the formula deps that, in turn, asks the active_spec for the deps
5. active_spec calculates the deps using dependency_collector, but the formula was evaluated already without the ```--with-qt``` flag, so it gets the wrong data. ```vtk``` includes the ```sip``` dependency only if ```--with-qt``` is passed

Not sure what is the best fix for this, but active_spec needs the options injected before evaluating the formula.

The discussion is here: https://github.com/Homebrew/homebrew-science/pull/1629

**Comment by jacknagel** [comment]
I'll explain why this happens on the homebrew-science issue, but the short answer is it's not something that can currently be fixed.

**Comment by gpakosz** [comment]
I'm facing this issue with `imagemagick`:

    ~ brew deps imagemagick --with-librsvg
    atk
    cairo
    fontconfig
    freetype
    gdk-pixbuf
    gettext
    glib
    gobject-introspection
    gtk+
    harfbuzz
    icu4c
    intltool
    jpeg
    libcroco
    libffi
    libpng
    librsvg
    libtiff
    libtool
    pango
    pixman
    pkg-config
    python
    xz

Eventhough I installed `librsvg` up-front with `brew install cairo pango librsvg --without-x11 --without-gtk+`, `brew install imagemagick --with-librsvg` tries to install `gtk+` because it believes it's a dependency of `librsvg` (**which is already installed**):

    ~ brew install cairo pango librsvg --without-x11 --without-gtk+
    Warning: cairo-1.14.2 already installed
    Warning: pango-1.36.8 already installed
    Warning: librsvg-2.36.3_1 already installed

    ~ brew install imagemagick --with-librsvg
    gtk+: XQuartz 2.3.6 is required to install this formula.
    You can install with Homebrew Cask:
      brew install Caskroom/cask/xquartz

    You can download from:
      https://xquartz.macosforge.org
    Error: An unsatisfied requirement failed this build.
