### ISSUE TITLE
gcc fails to build with "cannot compute suffix of object files: cannot compile"

### ISSUE THREAD

**Issue by jzwolak** [Homebrew/homebrew#35952]
I have the CLT and the bottle failed to download so homebrew tries to build from source.

When building from source I get the error in the title of this issue and here are the logs:

https://gist.github.com/ff3c625cf8055a66cab3

**Comment by mikemcquaid** [comment]
You've got a bunch of `brew doctor` warnings that need attention:
https://gist.githubusercontent.com/jzwolak/ff3c625cf8055a66cab3/raw/doctor.out

> and the bottle failed to download

Try `brew fetch --retry gcc` which may fix the bottle download.

**Comment by jzwolak** [comment]
The bottle is downloading now and gcc installs, thanks for your quick reply!

I did not realize that homebrew will only try the download once and requires an explicit user command to retry.

You'll notice there's nothing in the `brew doctor` that would interfere with homebrew or gcc.  But I'll take the time and effort to remove them and retry compile from source to prove unequivocally that there is a problem.  I'll get back to you shortly

**Comment by jzwolak** [comment]
Here it is: https://gist.github.com/d4f8f0a1ddcb03bd7f24

`brew doctor` now outputs `Your system is ready to brew.` and the command `brew install gcc --build-from-source` gives the error in the title of this issue as originally reported.

I have the latest CLT and latest Yosemite: 6.1.1 and 10.10.1, respectively.

**Comment by mistydemeo** [comment]
It looks like this happened when building libgcc. `brew gist-logs` didn't include the appropriate config.log; do you mind doing `brew install gcc -sd`, dropping to a shell, and grabbing libgcc's config.log? That'll have the debug info we need. Thanks!

**Comment by jzwolak** [comment]
https://gist.github.com/jzwolak/380185c443bf0bece9b3

**Comment by mistydemeo** [comment]
Looks like the same problem as your other issue - should be resolved now!
