### ISSUE TITLE
gfortran "Library not loaded: /usr/local/lib/libcloog-isl.4.dylib"

### ISSUE THREAD

**Issue by jzwolak** [Homebrew/homebrew#35956]
Typing `brew install gcc` and then `gfortran hello.f90` gives error that a library cannot be found.  It seems clear this library should have been installed with gcc or gfortran.  Here's the output:

$ brew install gcc
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/gcc-4.9.2_1.yosemite
Already downloaded: /Library/Caches/Homebrew/gcc-4.9.2_1.yosemite.bottle.tar.gz
==> Pouring gcc-4.9.2_1.yosemite.bottle.tar.gz
==> Caveats
GCC has been built with multilib support. Notably, OpenMP may not work:
  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60670
If you need OpenMP support you may want to
  brew reinstall gcc --without-multilib
==> Summary
🍺  /usr/local/Cellar/gcc/4.9.2_1: 1156 files, 203M
$ gfortran hello.f90 
dyld: Library not loaded: /usr/local/lib/libcloog-isl.4.dylib
  Referenced from: /usr/local/Cellar/gcc/4.9.2_1/libexec/gcc/x86_64-apple-darwin14.0.0/4.9.2/f951
  Reason: image not found
gfortran: internal compiler error: Trace/BPT trap: 5 (program f951)
Abort trap: 6

And here's the logs: https://gist.github.com/a78e54ed20f703fc31bc

**Comment by mikemcquaid** [comment]
I can't reproduce this. `brew info cloog`?

**Comment by jzwolak** [comment]
I realize that you also may want to know that I've done a `brew update` and `brew upgrade`.

Here is the output of `brew info cloog`.
```
$ brew info cloog
cloog: stable 0.18.1 (bottled), HEAD
http://www.cloog.org/
/usr/local/Cellar/cloog/0.18.1 (33 files, 560K) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cloog.rb
==> Dependencies
Build: pkg-config ✔
Required: gmp ✔, isl ✔
```

And

```
$ ls /usr/local/lib/libclo*
ls: /usr/local/lib/libclo*: No such file or directory
```

**Comment by mistydemeo** [comment]
Try `brew unlink cloog && brew link cloog`.

**Comment by jzwolak** [comment]
Hmm... I wonder how that went missing.

Your suggestion works, thank you very much!
