### ISSUE TITLE
node.rb creates a symlink file if man directory is absent

### ISSUE THREAD

**Issue by miheerdew** [Homebrew/homebrew#35969]
Check https://github.com/Homebrew/homebrew/blob/master/Library/Formula/node.rb#L99-L102.

If any one of directories man{1,3,5,7} is absent(which is by default), then the code will create a symbolic link of the form `share/man/man3 --> libexec/npm/share/man/man3/npm`.

**Comment by DomT4** [comment]
Nice spot! Cheers for the report :+1:. Should be fixed in #35971.
