### ISSUE TITLE
undefined method `deprecated_option' for Findutils:Class

### ISSUE THREAD

**Issue by agesnoui** [Homebrew/homebrew#35983]
This happens when i run brew doctor :
$ brew doctor
Error: undefined method `deprecated_option' for Findutils:Class
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/nfs/zfs-student-5/users/2013/agesnoui/.brew/Library/Formula/findutils.rb:16
/usr/local/Library/Homebrew/formulary.rb:65:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:192:in `factory'
/usr/local/Library/Homebrew/formula.rb:397:in `factory'
/usr/local/Library/Homebrew/tab.rb:50:in `for_name'
/usr/local/Library/Homebrew/cmd/doctor.rb:1003:in `check_for_non_prefixed_findutils'
/usr/local/Library/Homebrew/cmd/doctor.rb:1130:in `send'
/usr/local/Library/Homebrew/cmd/doctor.rb:1130:in `doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1129:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1129:in `doctor'
/usr/local/Library/brew.rb:105:in `send'
/usr/local/Library/brew.rb:105

Same goes when i try to install something :
$ brew install qt
Error: undefined method `deprecated_option' for Qt:Class
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/nfs/zfs-student-5/users/2013/agesnoui/.brew/Library/Formula/qt.rb:37
/usr/local/Library/Homebrew/formulary.rb:65:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:192:in `factory'
/usr/local/Library/Homebrew/formula.rb:397:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:12:in `formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:12:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:12:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:105:in `send'
/usr/local/Library/brew.rb:105

**Comment by DomT4** [comment]
What's your ` brew config `?

**Comment by agesnoui** [comment]
$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: (none)
HEAD: (none)
HOMEBREW_PREFIX: /***/*************/*****/****/********/.brew
HOMEBREW_CELLAR: /***/*************/*****/****/********/.brew/Cellar
CPU: quad-core 64-bit ivybridge
OS X: 10.9.5-x86_64
Xcode: 5.0.2
CLT: 6.1.1.0.1.1416017670
Clang: 5.0 build 500
X11: 2.7.5 => /opt/X11
System Ruby: 1.8.7-358
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby

**Comment by DomT4** [comment]
```
ORIGIN: (none)
HEAD: (none)
```

This is odd. It should be something like:

```
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 9f12f70e721c56c8eaf76c262d226a29c6ae2f90
```

Have you done a ` brew update ` recently?

There's a mismatch here as well:

```
Xcode: 5.0.2
CLT: 6.1.1.0.1.1416017670
Clang: 5.0 build 500
```

You seem to have the newest CLT, but a significantly outdated Xcode and Clang version. I don't think that's causing the issue here, but it's probably not going to help with builds.

**Comment by agesnoui** [comment]
Yes I've ran a brew update just before the error showed up.
I can't control the Xcode and Clang versions : I'm only a modest user here. ^^

**Comment by DomT4** [comment]
If you do ` cd $(brew --prefix) && git remote -v ` what does it say?

> I can't control the Xcode

You can update Xcode through the App Store, which will update your ` Clang ` version :).

**Comment by agesnoui** [comment]
$ cd $(brew --prefix) && git remote -v
fatal: Not a git repository (or any of the parent directories): .git

I'm in an IT school. They compile some of our projects via clang. Not shure they'd like me changing versions :/

**Comment by DomT4** [comment]
Ah. Okay, do:

```
cd $(brew --prefix) && git remote add origin https://github.com/Homebrew/homebrew.git && git fetch && git reset --hard origin/master && brew update
```

Let me know if that works.

> I'm in an IT school. They compile some of our projects via clang. Not shure they'd like me changing versions :/

Fair enough. Yeah, you should probably clear that with the IT school first. It might be interesting to them that they have a mismatch between CLT and Xcode/Clang versions though.

**Comment by agesnoui** [comment]
cd $(brew --prefix) && git remote add origin https://github.com/Homebrew/homebrew.git && git fetch && git reset --hard origin/master && brew update
fatal: Not a git repository (or any of the parent directories): .git

/usr/local/ $ git remote add origin https://github.com/Homebrew/homebrew.git
fatal: Not a git repository (or any of the parent directories): .git

Do you think git cloning the homebrew somewhere else then copying only the .git could do the trick?

**Comment by agesnoui** [comment]
$ ls `brew --prefix`
CODEOFCONDUCT.md README.md        git              munki
CONTRIBUTING.md  SUPPORTERS.md    include          sal
LICENSE.txt      bin              lib              share
Library          cuda             libexec

-> no homebrew ..

**Comment by DomT4** [comment]
Oh, It's not a ` git ` repo at all. Alright. Do the same command as before, but between ` cd $(brew --prefix) ` and ` && git remote add origin https://github.com/Homebrew/homebrew.git ` do a ` git init `.

**Comment by DomT4** [comment]
Homebrew will be hidden inside ` Library ` under brew prefix btw, so it should still be there. It's not in the top-level dir.

**Comment by agesnoui** [comment]
$ cd $(brew --prefix) && git init && git remote add origin https://github.com/Homebrew/homebrew.git && git fetch && git reset --hard origin/master && brew update
/usr/local/.git: Permission denied

:(

**Comment by DomT4** [comment]
Heh. Okay, If you do ` ls -1 /usr/local/.git ` does anything show up?

**Comment by agesnoui** [comment]
no such file or dir

**Comment by agesnoui** [comment]
drwxr-xr-x    17 root  wheel    578 Dec 22 20:56 local

I can't write in it..

**Comment by DomT4** [comment]
Is your ` brew prefix ` in ` /usr/local `? Your initial post seemed to suggest both ` /usr/local ` and your ` $HOME/.brew ` directory?

**Comment by agesnoui** [comment]
Yes brew prefix is /usr/local/
and ~/.bre/ does contain a .git
How can I redefine brew prefix ?

**Comment by DomT4** [comment]
Did you put the Brew into ` ~/.brew ` in addition to ` /usr/local ` or was one pre-installed or did it somehow spread across to the two locations?

Your ` brew config ` seems to think it's placed in the ` $HOME/.brew ` dir:

```
 /nfs/zfs-student-5/users/2013/agesnoui/.brew/Library/Formula/findutils.rb
HOMEBREW_PREFIX: //*******///***/.brew
HOMEBREW_CELLAR: //**********///******/.brew/Cellar
```

(FWIW, Disclosing your ` brew prefix ` isn't a security risk). How is your ` $PATH ` setup? And what do you get in the Terminal when you do ` which brew `?

**Comment by agesnoui** [comment]
I think I installed brew before my school did. So it might explain why he thinks he's in my home.

in /usr/local/ their is a git rep but not a .git , maybe it has to be renamed.. ( but I can't :( )

PATH= /......./$(HOME)/.brew.bin -> it's their

$ which brew
/usr/local/bin/brew

**Comment by DomT4** [comment]
I presume the school has locked down ` /usr/local ` with root privileges, and made students non-root accounts, which would explain why you can't write to ` /usr/local `. I presume you don't have access to ` sudo `?

Are you allowed to modify your ` $PATH ` for sessions? If you are allowed, try something like export ` PATH=/nfs/zfs-student-5/users/2013/agesnoui/.brew/bin:/nfs/zfs-student-5/users/2013/agesnoui/.brew/sbin:$PATH ` and then try ` which brew ` again.

**Comment by agesnoui** [comment]
It did the trick !
Thanks :)

**Comment by DomT4** [comment]
Awesome! :).

If you don't have a ` zshrc ` or a ` bash_profile ` or similar that you can stick that command in, you may need to run the command for every new terminal session. Sadly modifying the ` $PATH ` in that way doesn't persist across sessions, which is why it's usually most practical to stick it in a ` bash_profile ` or similar so it gets run automatically for you, but I don't know if you're able to create/use one of those in your setup. If you can, I'd recommend it :).

**Comment by agesnoui** [comment]
already added to `zshrc` :)
Thank you for helping, I appreciate. :)

**Comment by DomT4** [comment]
Cool. Feel free to shout again if you run into any further issues :). There should be a "Close issue" button somewhere towards the bottom of this page; If you're happy feel free to hit that - Saves the maintainers having to do so later :).
