### ISSUE TITLE
Ask confirmation before install and upgrade

### ISSUE THREAD

**Issue by nicolas-brousse** [Homebrew/homebrew#35985]
I think ask confirmation before install and upgrade could be something nice. I explain me.

I use [`bubu`](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/brew/brew.plugin.zsh#L2) alias of oh-my-zsh. This alias do brew update, upgrade and cleanup. It's an easier and quicker way to update my homebrew.
But recently it make me an annoying situation.

I use `postgresql` and there is few days the new version 9.4 has been published. And this new version need to do some operations to [migrate the datas of the databases](http://stackoverflow.com/questions/24379373/how-to-upgrade-postgres-from-9-3-to-9-4-without-losing-data). Obviously I viewed this after and the old postgresql version was missing because I `brew cleanup` everytime.

Because of this situation I was thinking that it could be interesting to ask confirmation before:
* installation with none installed dependencies (if more than one formulae will be install)
* upgrade any formulae

Like `apt-get` do, it could be something like this.
```bash
$ brew install -y postgresql
$ brew upgrade -y
```

Sure ask confirmation before upgrade does not really avoid some problem like mine but it could be nice to take care about what it will upgrade. May be it also could be a param into the formula instead of ask every time.

I can understand that it is the alias must be more smart than now instead of ask a confirmation into homebrew. But I think it's something that could be nice to do, so I wrote this issue :smile:

**Comment by mikemcquaid** [comment]
I don't think `install` is necessary. I think `upgrade` (without arguments, at least) may be a good idea or require an option `--all`. @Homebrew/owners: thoughts?

**Comment by nicolas-brousse** [comment]
@mikemcquaid In the two cases I think it's nice to know what will happened.

**Comment by DomT4** [comment]
Somewhat concerned personally about how many people's Travis, upgrade, launch etc scripts this will break, unless confirmation is an optional choice.

**Comment by mikemcquaid** [comment]
What I'd propose would be to redirect people to `upgrade --all` with a deprecation warning and stop it upgrading all formulae with just `brew upgrade` after a while.

**Comment by DomT4** [comment]
That sounds fair to me. A reasonable deprecation period would lessen any issues dramatically.

**Comment by tdsmith** [comment]
I guess another option, as @DomT4 alludes, could be that `brew upgrade --confirm` prints a list of outdated packages and asks for a y/n response before proceeding.

Another interesting case for interactivity in upgrade is if a package foo depends on package bar and a user has outdated versions of both foo and bar, `brew upgrade [--confirm?] foo` could interactively confirm that `bar` should also be updated.

**Comment by jacknagel** [comment]
>Another interesting case for interactivity in upgrade is if a package foo depends on package bar and a user has outdated versions of both foo and bar, brew upgrade [--confirm?] foo could interactively confirm that bar should also be updated.

Since we don't support not upgrading dependencies, if you choose to upgrade `foo`, then you also *must* upgrade `bar`. This assumption is pretty deeply ingrained into the codebase.

During a `brew upgrade`, the installer instantiated for `foo` will upgrade `bar` (this is the same mechanism that upgrades dependencies during a normal `brew install`). The installer instantiated for `bar` will raise a special exception that tells us that we already attempted to install bar once, [which is caught here](https://github.com/Homebrew/homebrew/blob/4dd0b31ace1d716d3d0ed835f866eeb423065197/Library/Homebrew/cmd/upgrade.rb#L79-81).

**Comment by mikemcquaid** [comment]
Yeh, I think the only case we should handle it `brew upgrade` to `brew upgrade --all` as (anecdata ahoy) that's the one I've heard by far the most complaints about accidental breakage.

**Comment by DomT4** [comment]
This was implemented for `upgrade`. Safe to close?

**Comment by mikemcquaid** [comment]
Yup.
