### ISSUE TITLE
php56 php56-mcrypt

### ISSUE THREAD

**Issue by TangoDog** [Homebrew/homebrew#35981]
I get this error when trying to install both php56 and php56-mcrypt
brew install -v php56
==> Installing php56 from homebrew/homebrew-php
Error: invalid byte sequence in UTF-8
Please report this bug:
    http://git.io/brew-troubleshooting

**Comment by jacknagel** [comment]
Please report php formula issues to https://github.com/Homebrew/homebrew-php

**Comment by TangoDog** [comment]
I just re-installed homebrew, and it worked - thanks for your time and effort
 Gerald P. Clarke, M.D.509 S. Washburn St.PO Box 2623Oshkosh, WI 54903www.optivisioneyecare.comLUTFA  

     On Saturday, January 17, 2015 1:45 PM, Jack Nagel <notifications@github.com> wrote:
   

 Please report php formula issues to https://github.com/Homebrew/homebrew-php—
