### ISSUE TITLE
Brew install on Yosemite requires wheel group privileges but will not run under su

### ISSUE THREAD

**Issue by camerojo** [Homebrew/homebrew#35992]
Brew install (https://raw.githubusercontent.com/Homebrew/install/master/install) needs wheel group privileges (at least on my brand new Yosemite laptop)
eg
fatal: cannot create directory at 'Library/ENV/pkgconfig/10.10': Permission denied

Normally a normal Mac admin user gets the required privilege as needed by running su. However the install script explicitly checks for and disallows running as root.

So the script does not work at all for me.

**Comment by jacknagel** [comment]
`/usr/local` doesn't exist on a clean install of OS X, so you shouldn't run into permissions problems. What does `find /usr/local` look like? Did you install any other software before attempting to install Homebrew?

**Comment by camerojo** [comment]
I have a lot of stuff under /usr/local - eg PHP, ant etc

I said it was a clean Yosemite install but it was upgraded from my existing dev machine.

I imagine other developers might do the same.

**Comment by camerojo** [comment]
Assuming that this is a situation that you don't want to deal with, can I suggest that you check for it in the script and give the user some useful feedback - as you do already for some common error conditions.

abort <<-EOABORT if File.directory? /usr/local...
  Sorry, you need to install this into your home directory - or ??? etc
EOABORT

It will save users, like me, coming to Homebrew for the first time a lot of confusion.

**Comment by mikemcquaid** [comment]
`sudo chown -R $USER /usr/local` should sort you out.

**Comment by jacknagel** [comment]
>I said it was a clean Yosemite install but it was upgraded from my existing dev machine.

For future reference, this not what one would refer to as a "clean install".

**Comment by camerojo** [comment]
Thank you for the fix. I understand better now what Homebrew actually does,

Sorry for my "clean install" comment - of course it wasn't clean any more after Apple had automatically migrated my previous set up (a nice Apple feature). It just "seemed" clean to me because I hadn't done any reinstalls myself.

I have seen other reports of this problem, so hopefully this post will help others.

Thank you for your quick and helpful responses.
