### ISSUE TITLE
MTR not linking to /usr/local/bin

### ISSUE THREAD

**Issue by raldred** [Homebrew/homebrew#36005]
Can't get mtr to link in /usr/local/bin
Warning: Already linked: /usr/local/Cellar/mtr/0.86

    lrwxr-xr-x    1 rob   admin    36 13 Aug 19:28 mysqltest -> ../Cellar/mysql/5.6.20/bin/mysqltest
    lrwxr-xr-x    1 rob   admin    45 13 Aug 19:28 mysqltest_embedded -> ../Cellar/mysql/5.6.20/bin/mysqltest_embedded
    lrwxr-xr-x    1 rob   admin    31 30 Oct 14:34 node -> ../Cellar/node/0.10.30/bin/node
    lrwxr-xr-x    1 rob   admin    38 30 Oct 14:35 npm -> ../lib/node_modules/npm/bin/npm-cli.js
    lrwxr-xr-x    1 rob   admin    39 13 Oct 22:05 oid2name -> ../Cellar/postgresql/9.3.5/bin/oid2nam

tried `brew unlink mtr && brew link mtr` had to manually add

(Edit it's link into /usr/local/sbin)

**Comment by jacknagel** [comment]
The mtr executable is installed into sbin, so it is linked into /usr/local/sbin.

**Comment by mikemcquaid** [comment]
@jacknagel Is it worth adding a check for something similar to `audit --strict`?
