### ISSUE TITLE
python failed to build on 10.10.1

### ISSUE THREAD

**Issue by dinks** [Homebrew/homebrew#36004]
I have a fresh Yosemite 10.10.1 and tried to install python via `brew install python`. The postinstall gives me this https://gist.github.com/anonymous/64e9fd9721618cf6f265 message. I have no freaking clue how to fix this !

**Comment by dinks** [comment]
Sorry I fixed this by uninstalling all the packages and installing it again
`pip freeze | grep -v "^-e" | xargs pip uninstall -y`
`sudo pip install version`

**Comment by tdsmith** [comment]
The gist you posted doesn't seem to include the postinstall failure; what did it look like?

**Comment by dinks** [comment]
@tdsmith Please have a look at https://gist.github.com/anonymous/64e9fd9721618cf6f265#file-01-python-L50
