### ISSUE TITLE
How to solve conflicts_with 'hive', :because => 'both install `beeline` binaries'

### ISSUE THREAD

**Issue by sota0805** [Homebrew/homebrew#36036]
After installing apache-spark, I tried to install hive and I could not install both. 

I know why I could not do because [codes](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/apache-spark.rb) below:
    
    conflicts_with 'hive', :because => 'both install `beeline` binaries'

 Is there any solution? Thanks in advance.

**Comment by jacknagel** [comment]
The error message gives instructions:

```
$ brew install hive
Error: Cannot install hive because conflicting formulae are installed.

  apache-spark: because both install `beeline` binaries

Please `brew unlink apache-spark` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.
```

You can then switch between them using `brew link` and `brew unlink` as appropriate.

**Comment by tdsmith** [comment]
FWIW it looks like Hive beeline is the same as Spark beeline: https://spark.apache.org/docs/1.1.0/sql-programming-guide.html#running-the-thrift-jdbc-server so "--force" is probably okay.
