### ISSUE TITLE
nvm 0.23.0

### ISSUE THREAD

**Issue by kriswill** [Homebrew/homebrew#36049]
Version Bump.  This version introduces support for io.js v1.0.x

see https://github.com/creationix/nvm/pull/616

**Comment by paultrott** [comment]
Is there anything I need to do, in homebrew, to install the latest version of nvm (with iojs support)?
I've tried 'brew upgrade nvm', but I get this message: Error: nvm 0.22.2 already installed
Thanx in advance 
?=oD

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!

**Comment by mikemcquaid** [comment]
In future you can just create the PR rather than creating an issue too. Thanks!

**Comment by kriswill** [comment]
Thanks @mikemcquaid, my first commit, a noob mistake. =)

**Comment by kriswill** [comment]
@paultrott you'll need to `brew update` to retrieve latest formulas, then `brew upgrade nvm` to install latest nvm.
