### ISSUE TITLE
brew list should optionally show the options the formula was brewed with

### ISSUE THREAD

**Issue by tfeldmann** [Homebrew/homebrew#36069]
I regularly pipe `brew list` into a textfile to remember which packages I need in case of a fresh OS installation. It would be nice to see the install options for each package so I don't have to look them up every time.

**Comment by tdsmith** [comment]
You can read them from `INSTALL_RECEIPT.json` using `jq`:

`OPT_PREFIX="$(brew --prefix)/opt"; for keg in $(ls $OPT_PREFIX); do printf "brew install %s " $keg; jq -r '.used_options | join(" ")' < $OPT_PREFIX/$keg/INSTALL_RECEIPT.json; done`

**Comment by jacknagel** [comment]
`brew info <formula> --json=v1`

**Comment by jacknagel** [comment]
More specifically: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Querying-Brew.md

**Comment by tfeldmann** [comment]
@tdsmith Thank you, works great.
@jacknagel Cool stuff, didn't know that. But I'd still prefer something like `brew list --show-options`.

**Comment by jacknagel** [comment]
There are a lot of different things that could be added to `brew list`. The idea behind the JSON output is that people can build scripts that are useful to them on top of it, rather than have core maintain an option for every possible combination of data.

**Comment by tfeldmann** [comment]
I'm happy with that, thanks a lot!
