### ISSUE TITLE
Suggested feature: Automagically build bottled brews if their formula has been edited

### ISSUE THREAD

**Issue by DylanLacey** [Homebrew/homebrew#36068]
Something I'd like to see and am happy to work up a PR for if'n you all like it;  I'd like to see Homebrew automatically know I don't want to use the bottle if I've edited the formula.

I'm thinking this could be a `git status` or `git diff` done on the formula at install-time, and if it `diff`ers, then prefer to build from scratch rather then use the bottle.  Add in a `--no-srsly-bottle-me` flag for over-riding the edited formula.

**Comment by mikemcquaid** [comment]
Yeh, this is a pretty good idea actually, something I'd probably find useful too.

**Comment by DylanLacey** [comment]
KK!  Give me a few days and I'll send a PR.

**Comment by dunn** [comment]
If this happens it'd be nice if it applied to `fetch`/`unpack` as well.

**Comment by apjanke** [comment]
:+1:

**Comment by dunn** [comment]
Proposed an implementation in #41397.
