### ISSUE TITLE
Formula/go.rb Error: SHA1 mismatch

### ISSUE THREAD

**Issue by rkutin** [Homebrew/homebrew#36070]
Hello,

Golang archive looks like has a different sha sum that declared in formula:

==> Installing boot2docker dependency: go
==> Downloading https://storage.googleapis.com/golang/go1.4.1.src.tar.gz
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: d77dbbb06d7a005966ced0b837bc6c97d541210f
Actual: c7a683e8d39b835e333199d68d0c0baefcd24a68
Archive: /Library/Caches/Homebrew/go-1.4.1.tar.gz
To retry an incomplete download, remove the file above.

Tested manually - same c7...68 shasum

Best regards,
Roman

**Comment by daincredibleholg** [comment]
Same here. Don't now why, but it looks like the Go package was altered in the last days. The actual checksum equals the one given on the official download page (https://golang.org/dl/).

**Comment by mikemcquaid** [comment]
Fixed in fdac8ec. Can you complain to Go upstream about this? It's pretty bad form on their part.
