### ISSUE TITLE
saltstack: update formula for 2014.7.1

### ISSUE THREAD

**Issue by mwinche** [Homebrew/homebrew#36072]
They have tagged their 2014.7.1 release, which has a fix we need to put on all developer machines and we use brew to do that. Can we get the formula updated?

https://github.com/saltstack/salt/archive/v2014.7.1.tar.gz

Thanks!

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!

**Comment by mwinche** [comment]
So I created my fork and my branch, but to be honest, I'm not sure how to proceed changing the formula. https://github.com/mwinche/homebrew/tree/saltstack2014.7.1

**Comment by mikemcquaid** [comment]
Use `brew edit saltstack` and push the changes to your branch from your local system or edit the `url` and `sha256` of the `Library/Formula/saltstack.rb` file and then create a pull request.

**Comment by mwinche** [comment]
Pull request made: https://github.com/Homebrew/homebrew/pull/36083
