### ISSUE TITLE
elasticsearch launchagent file in wrong directory

### ISSUE THREAD

**Issue by dominik42** [Homebrew/homebrew#36097]
Hi,
after upgrading to elasticsearch 1.4.2 , the installer print the following command line as hint:

Then to load elasticsearch now:
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.elasticsearch.plist

But the mentioned homebrew.mxcl.elasticsearch.plist isn't copied into ~/Library/LaunchAgents. It's located in the elasticsearch install dir /usr/local/opt/elasticsearch which is linked to /usr/local/Cellar/elasticsearch/1.4.2

**Comment by jacknagel** [comment]
I see

```
To have launchd start elasticsearch at login:
    ln -sfv /usr/local/opt/elasticsearch/*.plist ~/Library/LaunchAgents
Then to load elasticsearch now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.elasticsearch.plist
```

**Comment by hacfi** [comment]
@dominik42 You must have had a `~/Library/LaunchAgents/homebrew.mxcl.elasticsearch.plist` already. In that case
```sh
To have launchd start elasticsearch at login:
    ln -sfv /usr/local/opt/elasticsearch/*.plist ~/Library/LaunchAgents
```
isn’t shown when upgrading. I just doublechecked and I think everything works fine.

**Comment by jacknagel** [comment]
Closing due to no response.

**Comment by hacfi** [comment]
I’m pretty sure it’s all fine..it just doesn’t mention to create the symlink when it’s already there.
