### ISSUE TITLE
Caching binary file of the dependent packages

### ISSUE THREAD

**Issue by Liooo** [Homebrew/homebrew#36093]
Here's the issue:

Say I'm installing a package A that depends on package B and C. Run brew install A, download and build of B succeeds, but build of C fails. I fix the error, and execute brew install A again. Here, what happens is HomeBrew builds package B again.

I saw it caches source code and reuses it to avoids re-download, but they don't try to reuse already built binary file. Are there any options to make HomeBrew do this? Otherwise, anyone come up with any reasons it doesn't support this feature? It's really annoying especially when the re-done build takes long.

I've made this question before but forgot to work on this. Here's the link of the question in stackoverflow.  (it's just same as what's mentioned above)

http://stackoverflow.com/questions/27184446/caching-binary-file-of-the-dependent-packages-in-homebrew

**Comment by jacknagel** [comment]
> Here, what happens is HomeBrew builds package B again.

You'll need to to provide a specific failure case, because in general this isn't true. If the installation of B succeeded, it won't be removed if a later installation fails.

**Comment by Liooo** [comment]
Ok. and sorry it happened a bit long ago, and it might take time to reproduce, because listening to what you guys say, I'm feeling like it was my misundestanding.

Anyways, I'll check it out again soon. and I'll post another issue if it reproduces.

Thanks for your response, and I'll close this issue so far.
