### ISSUE TITLE
Deprecate GithubGistFormula

### ISSUE THREAD

**Issue by jacknagel** [Homebrew/homebrew#36094]
`GithubGistFormula` is `ScriptFileFormula` plus logic for extracting a version string from the commit ID in the gist URL.

Unfortunately, this completely breaks upgrades, because commit IDs do not increase monotonically.

I worked around this in the homebrew-completions repo by inheriting directly from `Formula` and artificially defining the current version to be "1". Future updates will just increment that number.

I don't think that approach is appropriate for core, though, so we should probably recommend `ScriptFileFormula` plus an explicit version instead. In core, only `browser` current uses `GithubGistFormula`.

Really we could deprecate `ScriptFileFormula` as well, I don't think it is used very often.

**Comment by mikemcquaid** [comment]
:+1: I'm pretty down on the level of "magic" in most of the formulae subclasses.
