### ISSUE TITLE
easy-git install error ( Unknown SSL Protocol error )

### ISSUE THREAD

**Issue by kswope** [Homebrew/homebrew#36096]
kevin@walnut Downloads $ brew install easy-git
    ==> Downloading http://people.gnome.org/~newren/eg/download/1.7.5.2/eg

    curl: (35) Unknown SSL protocol error in connection to people.gnome.org:-9824
    Error: Failed to download resource "easy-git"
    Download failed: http://people.gnome.org/~newren/eg/download/1.7.5.2/eg

Manually running curl to download the file is not a problem.

**Comment by mistydemeo** [comment]
What version of OS X are you on? Do you have a `~/.curlrc`?

**Comment by kswope** [comment]
kevin@walnut ~ $ sw_vers 
    ProductName:	Mac OS X
    ProductVersion:	10.9.5
    BuildVersion:	13F34

    kevin@walnut ~ $ ls ~/.curlrc
    ls: /Users/kevin/.curlrc: No such file or directory

Does it look weird that every protocol mentioned in the error is http but the error is SSL?

Both of these download the eg script just fine (note -L because its a redirect)

    curl -L http://people.gnome.org/~newren/eg/download/1.7.5.2/eg
    curl -L https://people.gnome.org/~newren/eg/download/1.7.5.2/eg

**Comment by jacknagel** [comment]
>Does it look weird that every protocol mentioned in the error is http but the error is SSL?

It's a redirect.

```
$ curl -LI http://people.gnome.org/~newren/eg/download/1.7.5.2/eg
HTTP/1.1 302 Found
Date: Wed, 21 Jan 2015 18:13:22 GMT
Server: Apache/2.2.15 (Red Hat)
Location: https://people.gnome.org/~newren/eg/download/1.7.5.2/eg
Connection: close
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 200 OK
Date: Wed, 21 Jan 2015 18:13:22 GMT
Server: Apache/2.2.15 (Red Hat)
Last-Modified: Mon, 08 Apr 2013 15:26:48 GMT
ETag: "bdbda22b3cd1330a-454ef-4d9db10b1de00"
Accept-Ranges: bytes
Content-Length: 283887
Content-Type: text/plain; charset=UTF-8
Connection: close
```

**Comment by jacknagel** [comment]
Probably a temporary network issue.

**Comment by kswope** [comment]
Temporary network issue that's lasted 11 days so far.  But don't worry about it, this version of easy-git seems to be broken with the current version of git anyway.

Doesn't look like a network issue unless its non-obvious.  Maybe some weird http configs over at people.gnome.org 

```
kevin@walnut Downloads $ brew install easy-git
==> Downloading http://people.gnome.org/~newren/eg/download/1.7.5.2/eg

curl: (35) Unknown SSL protocol error in connection to people.gnome.org:-9824
Error: Failed to download resource "easy-git"
Download failed: http://people.gnome.org/~newren/eg/download/1.7.5.2/eg
```

(http)
```
kevin@walnut Downloads $ curl -sL http://people.gnome.org/~newren/eg/download/1.7.5.2/eg|head 
#!/usr/bin/perl -w

## Easy GIT (eg), a frontend for git designed for former cvs and svn users
## Version 1.7.5.2
## Copyright 2008-2013 by Elijah Newren and others
## Licensed under GNU GPL, version 2.

## To use eg, simply stick this file in your path.  Then fire off an
## 'eg help' to get oriented.  You may also be interested in
##   http://www.gnome.org/~newren/eg/git-for-svn-users.html
```

(https)
```
kevin@walnut Downloads $ curl -sL https://people.gnome.org/~newren/eg/download/1.7.5.2/eg|head 
#!/usr/bin/perl -w

## Easy GIT (eg), a frontend for git designed for former cvs and svn users
## Version 1.7.5.2
## Copyright 2008-2013 by Elijah Newren and others
## Licensed under GNU GPL, version 2.

## To use eg, simply stick this file in your path.  Then fire off an
## 'eg help' to get oriented.  You may also be interested in
##   http://www.gnome.org/~newren/eg/git-for-svn-users.html

```
