### ISSUE TITLE
Open-MPI does not compile with GCC

### ISSUE THREAD

**Issue by danielfmva** [Homebrew/homebrew#36108]
Hi,

I have been trying compile Open-MPI with gcc instead of the Clang compiler without success so far.

I have already set the HOMEBREW_CC and HOMEBREW_CXX variables and it isn't working. I have also edited its formula and added the following code, also without success:

```ruby
 def install

    # Force compilation with gcc-4.9
    ENV['CC'] = '/usr/local/bin/gcc-4.9'
    ENV['LD'] = '/usr/local/bin/gcc-4.9'
    ENV['CXX'] = '/usr/local/bin/g++-4.9'

    # Compiler complains about link compatibility with FORTRAN otherwise
    ENV.delete('CFLAGS')
    ENV.delete('CXXFLAGS')
```

Any ideas of what is going on?

**Comment by mistydemeo** [comment]
Can you specify what the problem is, please? Can you provide the output of `brew gist-logs open-mpi` for when you attempt to build it without the changes you made to the formula?

**Comment by danielfmva** [comment]
Hi,

the problem is that brew is using clang regardless the env variables you pass.

Here is an example:
(dev)dmva:~/Development/lib/libmesh$ mpicc
clang: error: no input files
(dev)dmva:~/Development/lib/libmesh$ which mpicc
/usr/local/bin/mpicc

It seems that the log was not generated.
(dev)dmva:~/Development/lib/libmesh$ brew gist-logs open-mpi
Error: No logs.

**Comment by mistydemeo** [comment]
You're probably getting Homebrew's binary packages installed. Those are built using clang. What happens if you try this, without your changes to the formula file:

```
brew install open-mpi --cc=gcc-4.9
```

**Comment by danielfmva** [comment]
The same problem... Seems that any argument we pass is ignored.

```shell
(dev)dmva:~/Development/lib/libmesh$ brew install open-mpi --cc=gcc-4.9
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/open-mpi-1.8.4.yosemite.
Already downloaded: /Library/Caches/Homebrew/open-mpi-1.8.4.yosemite.bottle.tar.gz
==> Pouring open-mpi-1.8.4.yosemite.bottle.tar.gz
(dev) /usr/local/Cellar/open-mpi/1.8.4: 776 files, 22M
(dev)dmva:~/Development/lib/libmesh$ mpicc
clang: error: no input files
```

**Comment by danielfmva** [comment]
I need that openmpi is compiled with gcc because of compatibility with libMesh.

**Comment by mistydemeo** [comment]
Sorry, also add `--build-from-source` to that commandline.

**Comment by danielfmva** [comment]
It worked! Thank you! : )

Is there anyway to rebuild all the dependencies of the libraries that depend on open-mpi? Or at least a way to check the dependencies of a lib?

**Comment by mistydemeo** [comment]
Here's the list of software in the main repo and in homebrew/science that use MPI (generated via `grep -rl :mpi $(brew --repository)/Library/Formula | sed -e s,$(brew --repository)/Library/Formula/,, -e s,.rb,,`:

```
abyss
arpack
boost
boost149
bsponmpi
elemental
fftw
garli
getdp
gmsh
gromacs
hdf5
hyphy
hypre
konoha
lammps
lis
maker
mumps
nonpareil
p4est
paraview
parmetis
pastix
petsc
ray
scalapack
scotch
scotch5
slepc
sundials
superlu_dist
trilinos
zoltan
```

(Normally `brew uses` would be useful here, but that won't work for `open-mpi` since Homebrew supports the use of alternate MPI implementations.)
