### ISSUE TITLE
GnuPG 2.1

### ISSUE THREAD

**Issue by superlukas** [Homebrew/homebrew#36104]
Do we have somebody here who's smart enough to update the GnuPG 2 formula from 2.0 to 2.1? I tried doing it last year but I stopped working on it at some point (not just because I'm not smart enough).

Looks like a lot of the internal dependencies have changed, which wouldn't be a problem except that Homebrew seems to want to offer these libraries as their own formulas.

The formulas themselves aren't as complex as I expected them to be. I actually started from scratch just because I wanted to see how much simpler they can get.

Anyway, I'd appreciate it if somebody would take a look at them.

**Comment by DomT4** [comment]
We decided not to update to 2.1 in Homebrew/Homebrew yet, due to the major breaking changes and difficulties in reverting if end-users then changed their mind about using it.

You can find 2.1 in [Homebrew/Versions](https://github.com/Homebrew/homebrew-versions/blob/master/gnupg21.rb).

**Comment by DomT4** [comment]
See #34501 and #35106.

**Comment by jacknagel** [comment]
Closing per the above.
