### ISSUE TITLE
brew install causes a fork bomb when using bundler

### ISSUE THREAD

**Issue by sometimesfood** [Homebrew/homebrew#36103]
When I run `brew install` from within a Ruby process using bundler and the default gemspec generated by bundler, homebrew causes a fork bomb by spawning a huge number of processes (`/usr/bin/ruby -W0 /usr/local/Library/ENV/4.3/git ls-files -z`).

This seems to be caused by the following line in the default bundler gemspec:

```ruby
spec.files         = `git ls-files -z`.split("\x0")
```

Steps to reproduce:

```bash
bundle gem brew-bomb
cd brew-bomb
bundle install --path .bundle 
bundle exec ruby -e '`brew install cd-discid`'
```

On my system, this forks a huge number of processes:

```
37914 ttys005    0:00.19 /usr/bin/ruby -W0 /usr/local/Library/ENV/4.3/git ls-files -z
37915 ttys005    0:00.20 /usr/bin/ruby -W0 /usr/local/Library/ENV/4.3/git ls-files -z
# ...
38042 ttys005    0:00.18 /usr/bin/ruby -W0 /usr/local/Library/ENV/4.3/git ls-files -z
38043 ttys005    0:00.18 /usr/bin/ruby -W0 /usr/local/Library/ENV/4.3/git ls-files -z
38044 ttys005    0:00.19 /usr/bin/ruby -W0 /usr/local/Library/ENV/4.3/git ls-files -z
38045 ttys005    0:00.18 /usr/bin/ruby -W0 /usr/local/Library/ENV/4.3/git ls-files -z
38046 ttys005    0:00.16 /usr/bin/ruby -W0 /usr/local/Library/ENV/4.3/git ls-files -z
```

Apparently, there is an exec function in `/usr/local/Library/ENV/4.3/git` that is supposed to prevent this type of behaviour, but for some reason it does not seem to do so in this case.

When I undefine the `RUBYOPT` environment variable first, everything seems to be working properly:

```bash
bundle exec ruby -e 'ENV.delete("RUBYOPT"); `brew install cd-discid`'
```

Just for the record: `RUBYOPT` is set to `-rbundler/setup` by bundler.

**Comment by jacknagel** [comment]
>Apparently, there is an exec function in /usr/local/Library/ENV/4.3/git that is supposed to prevent this type of behaviour, but for some reason it does not seem to do so in this case.

That's probably because it never reaches that code. The git wrapper script is written in ruby, so the require of `bundler/setup` in RUBYOPT happens before the script is executed. I assume git is re-exec'd when that happens.

**Comment by jacknagel** [comment]
If you have to do it from a bundler-managed ruby process, I would suggest always unsetting RUBYOPT first. Since Homebrew itself is written in ruby, it may have other unintended consequences.

**Comment by jacknagel** [comment]
This is actually documented by bundler itself: http://bundler.io/v1.7/man/bundle-exec.1.html

It looks like the supported way to do this is to wrap shell commands like this:


```rb
Bundler.with_clean_env { `brew install wget` }

Bundler.clean_system('brew install wget')
```

**Comment by sometimesfood** [comment]
Sorry, I was so wrapped up in trying to understand the way brew and the git shim were supposed to work in this scenario that I did not think to check bundler's documentation. Thanks for the prompt reply! :+1:
