### ISSUE TITLE
Add `--versions` support to `brew leaves`

### ISSUE THREAD

**Issue by sedm0784** [Homebrew/homebrew#36106]
It'd be nice if the `brew leaves` command supported the `--versions` option, as `brew list` does.

**Comment by jacknagel** [comment]
See https://github.com/Homebrew/homebrew/issues/33473.

tl;dr do `brew list --versions $(brew leaves)`.

**Comment by sedm0784** [comment]
Sorry! Should have searched first.

Thanks!
