### ISSUE TITLE
brew for distribution?

### ISSUE THREAD

**Issue by scottdraves** [Homebrew/homebrew#36111]
Is it possible to use brew to create binaries suitable for distribution?  My application (https://github.com/twosigma/beaker-notebook) uses and includes nginx in its distribution.
Brew seems like the easiest way to get nginx compiled for mac and so I used that.
But the resulting executable does not run on old macs because it compiles with -march=native.
I could not find an easy way to change these compiler options in the formula.
And I realized I would have to make similar changes to each of the dependencies (openssl and pcre).
It just feels like I am barking up the wrong tree here.

I looked into bottles and it seems like a bottle would be what i want but i don't see any way to request one, maybe one is not defined for nginx (even though i see some hashes in the formula).  hard to say.  and it also looks like bottles are OS version specific.  I just want a binary that runs on any mac.  You know, good old fashioned binary compatibility?  Seems like it should be a trivial subset of what brew does, if I just knew how to ask for it... help?

**Comment by jacknagel** [comment]
You're looking for `brew install --build-bottle`. It's what we use to build our binaries.

**Comment by scottdraves** [comment]
Thanks!  Seems to have done the trick, I can see -march=core2 in the logs.
It will take me some time to find an old laptop to test on.

**Comment by mikemcquaid** [comment]
Note that if you're being really careful you probably also need to build on the oldest version of OSX you support as e.g. libraries/SDKs change across versions.

**Comment by scottdraves** [comment]
mike thanks for the tip -- how important is this?  is it known to be necessary even for nginx which seems relatively self-contained? i don't have an old machine handy...  do you have a link to a good discussion of this situation for os x developers?  thanks.

**Comment by mikemcquaid** [comment]
> mike thanks for the tip -- how important is this? is it known to be necessary even for nginx which seems relatively self-contained? i don't have an old machine handy... do you have a link to a good discussion of this situation for os x developers? thanks.

I don't have any links I'm afraid and I'm not sure of the specifics of nginx here, sorry!

**Comment by scottdraves** [comment]
I tried nginx built with --build-bottle on a Mac with 10.7 and it fails with

    3/10/15 11:50:10.453 AM ReportCrash: Failed to create CSSymbolicatorRef for jspawnhelper[88454]
    3/10/15 11:50:10.561 AM ReportCrash: Failed to create dSYM-less CSSymbolicatorRef for jspawnhelper[88454]

so it sounds like mike is right the SDK is also a problem and we need to be "really careful".  can brew  build an executable that works on old macs?

**Comment by mistydemeo** [comment]
Unfortunately, we don't currently provide a way to build against specific SDKs. I'd suggest building in a 10.6 or 10.7 VM if you need the binaries to run against those OS versions.

**Comment by mikemcquaid** [comment]
Yup, what @mistydemeo said. That's the only way to guarantee it'll work. Generally things are much happier when built on the oldest hardware and OS you support and they'll work on newer hardware and OSs.

**Comment by scottdraves** [comment]
are there bottles with binaries for old OSes that I could download?

how do I get an old version of the OS running in a VM?  I have VMware and I have an extra VM of 10.9 (because that's what my laptop had at the time) but I need 10.7 and ideally 10.6.

**Comment by mistydemeo** [comment]
I believe Apple will still sell you a DVD of 10.6, though you probably have to phone them about it.

**Comment by mistydemeo** [comment]
> are there bottles with binaries for old OSes that I could download?

Unfortunately we stopped building for 10.7 when 10.10 came out, so we don't have current bottles for it.

**Comment by scottdraves** [comment]
Thanks Misty.

**Comment by mikemcquaid** [comment]
There's even bottles for some old versions of 10.6 stuff if you go back through our Git history.
