### ISSUE TITLE
Unable to compile macvim / vim with python support 

### ISSUE THREAD

**Issue by paulhybryant** [Homebrew/homebrew#36118]
brew reinstall --override-system-vim --with-python --without-python3 --with-lua --with-luajit macvim
==> Reinstalling macvim with --with-lua, --with-python3, --override-system-vim, --with-luajit
==> Downloading https://github.com/b4winckler/macvim/archive/snapshot-73.tar.gz
Already downloaded: /Library/Caches/Homebrew/macvim-7.4-73.tar.gz
==> Patching
...

It always choses python3 regardless of the options.

**Comment by jacknagel** [comment]
You'll need to uninstall it entirely (`brew rm macvim`), otherwise the existing options will always be persisted.

**Comment by paulhybryant** [comment]
Thanks. uninstall first and then install works.

This behavior is a bit unintuitive though.

**Comment by jacknagel** [comment]
Unfortunately there's no mechanism to "unpersist" a persisted option. Perhaps it's something to think about for the future.
