### ISSUE TITLE
Depend on NVM's node

### ISSUE THREAD

**Issue by leoj3n** [Homebrew/homebrew#36114]
I don't like that Homebrew installs node as a dependency when node is already installed via nvm.

#31461 sort of touches on the issue.

Homebrew should use node/npm managed by nvm because Homebrew-installed node is redundant, confusing, and clutters my system!

Maybe symlink `/usr/local/opt/node/bin/node` to nvm's node?
Can Homebrew be smarter about this? Or is it necessary that Homebrew installs raw node?

**Comment by leoj3n** [comment]
Could check for NVM-installed node with `$NVM_BIN/node` or `nvm which $(nvm current)`

**Comment by jacknagel** [comment]
Locating a node executable on disk is not a problem. Using a non-Homebrew node if it's available means affected users would have to build things from source instead of downloading pre-compiled binaries, among other issues.

**Comment by leoj3n** [comment]
Ah, thanks for the explanation. No biggie.
