### ISSUE TITLE
unable to install mariadb 

### ISSUE THREAD

**Issue by 7stud** [Homebrew/homebrew#36126]
Mac OSX 10.6.8

Last login: Fri Jan 16 03:28:09 on ttys001 ~$ brew install mariadb
==> Installing mariadb dependency: pidof ==> Downloading http://www.nightproductions.net/downloads/pidof_source.tar.gz

################################################################## 100.0%
==> Patching ==> make all CC=gcc-4.2 CFLAGS= /Users/7stud/.homebrew/Cellar/pidof/0.1.4: 3 files, 24K, built in 3 seconds ==> Installing mariadb ==> Downloading http://ftp.osuosl.org/pub/mariadb/mariadb-10.0.15/source/mariadb-10.0.15.tar.gz

################################################################## 100.0%
==> Patching ==> cmake . -DCMAKE_INSTALL_PREFIX=/Users/7stud/.homebrew/Cellar/mariadb/10.0.15 -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE ==> make cd /tmp/mariadb-0ocIfC/mariadb-10.0.15/storage/innobase && /Users/7stud/.homebrew/Cellar/cmake/3.1.0/bin/cmake -E cmake_link_script CMakeFiles/innobase.dir/link.txt --verbose=1 /Users/7stud/.homebrew/Library/ENV/3.2.6/g++-4.2 -Wall -Wall -Wno-unused-parameter -fno-exceptions -fno-rtti -O2 -g -DNDEBUG -DDBUG_OFF -bundle -Wl,-headerpad_max_install_names -o ha_innodb.so CMakeFiles/innobase.dir/api/api0api.cc.o CMakeFiles/innobase.dir/api/api0misc.cc.o CMakeFiles/innobase.dir/btr/btr0btr.cc.o CMakeFiles/innobase.dir/btr/btr0cur.cc.o CMakeFiles/innobase.dir/btr/btr0pcur.cc.o CMakeFiles/innobase.dir/btr/btr0sea.cc.o CMakeFiles/innobase.dir/buf/buf0buddy.cc.o CMakeFiles/innobase.dir/buf/buf0buf.cc.o CMakeFiles/innobase.dir/buf/buf0dblwr.cc.o CMakeFiles/innobase.dir/buf/buf0checksum.cc.o CMakeFiles/innobase.dir/buf/buf0dump.cc.o CMakeFiles/innobase.dir/buf/buf0flu.cc.o CMakeFiles/innobase.dir/buf/buf0lru.cc.o CMakeFiles/innobase.dir/buf/buf0rea.cc.o CMakeFiles/innobase.dir/data/data0data.cc.o CMakeFiles/innobase.dir/data/data0type.cc.o CMakeFiles/innobase.dir/dict/dict0boot.cc.o CMakeFiles/innobase.dir/dict/dict0crea.cc.o CMakeFiles/innobase.dir/dict/dict0dict.cc.o CMakeFiles/innobase.dir/dict/dict0load.cc.o CMakeFiles/innobase.dir/dict/dict0mem.cc.o CMakeFiles/innobase.dir/dict/dict0stats.cc.o CMakeFiles/innobase.dir/dict/dict0stats_bg.cc.o CMakeFiles/innobase.dir/dyn/dyn0dyn.cc.o CMakeFiles/innobase.dir/eval/eval0eval.cc.o CMakeFiles/innobase.dir/eval/eval0proc.cc.o CMakeFiles/innobase.dir/fil/fil0fil.cc.o CMakeFiles/innobase.dir/fsp/fsp0fsp.cc.o CMakeFiles/innobase.dir/fut/fut0fut.cc.o CMakeFiles/innobase.dir/fut/fut0lst.cc.o CMakeFiles/innobase.dir/ha/ha0ha.cc.o CMakeFiles/innobase.dir/ha/ha0storage.cc.o CMakeFiles/innobase.dir/ha/hash0hash.cc.o CMakeFiles/innobase.dir/fts/fts0fts.cc.o CMakeFiles/innobase.dir/fts/fts0ast.cc.o CMakeFiles/innobase.dir/fts/fts0blex.cc.o CMakeFiles/innobase.dir/fts/fts0config.cc.o CMakeFiles/innobase.dir/fts/fts0opt.cc.o CMakeFiles/innobase.dir/fts/fts0pars.cc.o CMakeFiles/innobase.dir/fts/fts0que.cc.o CMakeFiles/innobase.dir/fts/fts0sql.cc.o CMakeFiles/innobase.dir/fts/fts0tlex.cc.o CMakeFiles/innobase.dir/handler/ha_innodb.cc.o CMakeFiles/innobase.dir/handler/handler0alter.cc.o CMakeFiles/innobase.dir/handler/i_s.cc.o CMakeFiles/innobase.dir/ibuf/ibuf0ibuf.cc.o CMakeFiles/innobase.dir/lock/lock0iter.cc.o CMakeFiles/innobase.dir/lock/lock0lock.cc.o CMakeFiles/innobase.dir/lock/lock0wait.cc.o CMakeFiles/innobase.dir/log/log0log.cc.o CMakeFiles/innobase.dir/log/log0recv.cc.o CMakeFiles/innobase.dir/mach/mach0data.cc.o CMakeFiles/innobase.dir/mem/mem0mem.cc.o CMakeFiles/innobase.dir/mem/mem0pool.cc.o CMakeFiles/innobase.dir/mtr/mtr0log.cc.o CMakeFiles/innobase.dir/mtr/mtr0mtr.cc.o CMakeFiles/innobase.dir/os/os0file.cc.o CMakeFiles/innobase.dir/os/os0proc.cc.o CMakeFiles/innobase.dir/os/os0sync.cc.o CMakeFiles/innobase.dir/os/os0thread.cc.o CMakeFiles/innobase.dir/page/page0cur.cc.o CMakeFiles/innobase.dir/page/page0page.cc.o CMakeFiles/innobase.dir/page/page0zip.cc.o CMakeFiles/innobase.dir/pars/lexyy.cc.o CMakeFiles/innobase.dir/pars/pars0grm.cc.o CMakeFiles/innobase.dir/pars/pars0opt.cc.o CMakeFiles/innobase.dir/pars/pars0pars.cc.o CMakeFiles/innobase.dir/pars/pars0sym.cc.o CMakeFiles/innobase.dir/que/que0que.cc.o CMakeFiles/innobase.dir/read/read0read.cc.o CMakeFiles/innobase.dir/rem/rem0cmp.cc.o CMakeFiles/innobase.dir/rem/rem0rec.cc.o CMakeFiles/innobase.dir/row/row0ext.cc.o CMakeFiles/innobase.dir/row/row0ftsort.cc.o CMakeFiles/innobase.dir/row/row0import.cc.o CMakeFiles/innobase.dir/row/row0ins.cc.o CMakeFiles/innobase.dir/row/row0merge.cc.o CMakeFiles/innobase.dir/row/row0mysql.cc.o CMakeFiles/innobase.dir/row/row0log.cc.o CMakeFiles/innobase.dir/row/row0purge.cc.o CMakeFiles/innobase.dir/row/row0row.cc.o CMakeFiles/innobase.dir/row/row0sel.cc.o CMakeFiles/innobase.dir/row/row0uins.cc.o CMakeFiles/innobase.dir/row/row0umod.cc.o CMakeFiles/innobase.dir/row/row0undo.cc.o CMakeFiles/innobase.dir/row/row0upd.cc.o CMakeFiles/innobase.dir/row/row0quiesce.cc.o CMakeFiles/innobase.dir/row/row0vers.cc.o CMakeFiles/innobase.dir/srv/srv0conc.cc.o CMakeFiles/innobase.dir/srv/srv0mon.cc.o CMakeFiles/innobase.dir/srv/srv0srv.cc.o CMakeFiles/innobase.dir/srv/srv0start.cc.o CMakeFiles/innobase.dir/sync/sync0arr.cc.o CMakeFiles/innobase.dir/sync/sync0rw.cc.o CMakeFiles/innobase.dir/sync/sync0sync.cc.o CMakeFiles/innobase.dir/trx/trx0i_s.cc.o CMakeFiles/innobase.dir/trx/trx0purge.cc.o CMakeFiles/innobase.dir/trx/trx0rec.cc.o CMakeFiles/innobase.dir/trx/trx0roll.cc.o CMakeFiles/innobase.dir/trx/trx0rseg.cc.o CMakeFiles/innobase.dir/trx/trx0sys.cc.o CMakeFiles/innobase.dir/trx/trx0trx.cc.o CMakeFiles/innobase.dir/trx/trx0undo.cc.o CMakeFiles/innobase.dir/usr/usr0sess.cc.o CMakeFiles/innobase.dir/ut/ut0bh.cc.o CMakeFiles/innobase.dir/ut/ut0byte.cc.o CMakeFiles/innobase.dir/ut/ut0crc32.cc.o CMakeFiles/innobase.dir/ut/ut0dbg.cc.o CMakeFiles/innobase.dir/ut/ut0list.cc.o CMakeFiles/innobase.dir/ut/ut0mem.cc.o CMakeFiles/innobase.dir/ut/ut0rbt.cc.o CMakeFiles/innobase.dir/ut/ut0rnd.cc.o CMakeFiles/innobase.dir/ut/ut0ut.cc.o CMakeFiles/innobase.dir/ut/ut0vec.cc.o CMakeFiles/innobase.dir/ut/ut0wqueue.cc.o ../../libservices/libmysqlservices.a -Wl,-bundle_loader,/tmp/mariadb-0ocIfC/mariadb-10.0.15/sql/mysqld /usr/local/lib/libz.dylib /usr/local/lib/libz.dylib /Users/7stud/.homebrew/Cellar/cmake/3.1.0/bin/cmake -E cmake_progress_report /tmp/mariadb-0ocIfC/mariadb-10.0.15/CMakeFiles 19 20 21 22 23 24 25 26 27 28 [ 95%] Built target innobase make: *** [all] Error 2

READ THIS: http://git.io/brew-troubleshooting

These open issues may also help: mysql-connector-c++ cannot build with mariadb (https://github.com/Homebrew/homebrew/issues/34578) Packages with --with-mysql option not satisfied by mariadb (https://github.com/Homebrew/homebrew/issues/32973) mariadb: missing /usr/local/etc/my.cnf.d, removed by brew prune (https://github.com/Homebrew/homebrew/issues/31760) ~$
```

**Comment by bfontaine** [comment]
As http://git.io/brew-troubleshooting says:

> Please run `brew update` and `brew doctor` *before* creating an issue!
>
> If you create an issue, please also create a [Gist][] by running
>
> ```
> brew gist-logs <formula name>
> ```
>
> and include a link to the gist in the issue.
>

[Gist]:https://gist.github.com

**Comment by jacknagel** [comment]
Closing due to no response.
