### ISSUE TITLE
minidlna: linking to path & run as user

### ISSUE THREAD

**Issue by tristan-k** [Homebrew/homebrew#36130]
Hi there,

it seems minidlna isnt linking correctly, because it never shows up in my $PATH. Further more it isnt possible to start it as a single-user. I followed the instructions inside the formula:

```
mkdir -p ~/.config/minidlna
cp #{sample_config_path} ~/.config/minidlna/minidlna.conf
ln -s YOUR_MEDIA_DIR ~/.config/minidlna/media
minidlnad -f ~/.config/minidlna/minidlna.conf -P ~/.config/minidlna/minidlna.pid
```
But doing 
```
/usr/local/Cellar/minidlna/1.1.4_1/sbin/minidlnad -f ~/.config/minidlna/minidlna.conf -P ~/.config/minidlna/minidlna.pid
```
gives me 
```
[2015/01/22 11:44:14] utils.c:277: warn: make_dir: cannot create directory '/Users/brew/'
[2015/01/22 11:44:14] minidlna.c:655: fatal: Database path not accessible! [/Users/brew/.config/minidlna/cache
```
I know that it is possible to define the running user in the conf-files, but this doesnt work with the mac version: https://wjwoodrow.wordpress.com/2014/07/23/running-minidlna-on-ubuntu/

Any suggestions?

**Comment by mikemcquaid** [comment]
> in my $PATH

What is your $PATH?

Other than that I think you're better addressing this with the `minidlna` developers.

**Comment by jacknagel** [comment]
Closing due to no response.
