### ISSUE TITLE
Slimerjs OS X version problem

### ISSUE THREAD

**Issue by ccorcos** [Homebrew/homebrew#36149]
I get this error:

```
❯❯❯ brew install slimerjs
xulrunner: OS X Mavericks or older is required.
Error: An unsatisfied requirement failed this build.
```

But I'm running OS X Yosemite.

**Comment by mistydemeo** [comment]
That's correct: as noted, Mavericks or *older* (not newer) is required to install xulrunner. See #33558 for details.

You can install slimerjs `--without-xulrunner`, if you don't need that functionality.

**Comment by ccorcos** [comment]
haha touché! sorry about that.
