### ISSUE TITLE
AICCU formula is not linked

### ISSUE THREAD

**Issue by kenzierocks** [Homebrew/homebrew#36143]
`brew link aiccu` tells me `Already linked: /usr/local/Cellar/aiccu/20070115`, but the `aiccu` executable actually resides in `/usr/local/Cellar/aiccu/20070115/sbin`. Is it possible to link the correct path?

**Comment by jacknagel** [comment]
Check `brew doctor`. Is `sbin` in your path?

**Comment by kenzierocks** [comment]
brew doctor said everything was fine, only /usr/local/bin and /usr/sbin are in my path. Should /usr/local/sbin be there?

**Comment by kenzierocks** [comment]
Oh, it just reported the sbin thing. Okay, I'll add that
