### ISSUE TITLE
test-bot should only test the runtime dependencies

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew#36154]
So I just update `cmake` to 3.1.1, and CI bot spends lots of time to test all of formulae which depend on `cmake`.

We shouldn't do this. Instead, we should only test the formulae which depend on `cmake` on runtime as most of them only use `cmake` in building time.

**Comment by jacknagel** [comment]
Agreed.

**Comment by mikemcquaid** [comment]
Yup, makes sense. Will take a look at this when I get the chance.

**Comment by mikemcquaid** [comment]
Or you could give it a go @xu-cheng (on vacation so I'll be a few days before I can get at this).

**Comment by mikemcquaid** [comment]
So, the trickier bit here is it's just using `brew uses` which doesn't care/know about `:build`. Could/should it?
