### ISSUE TITLE
`brew cleanup` isn't working

### ISSUE THREAD

**Issue by tjbenton** [Homebrew/homebrew#36164]
I ran this to make sure I was up to date and there weren't any problems
``` bash
tylerbenton[ 9:01] ~$ brew update && brew doctor
Already up-to-date.
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have a curlrc file
If you have trouble downloading packages with Homebrew, then maybe this
is the problem? If the following command doesn't work, then try removing
your curlrc:
  curl http://github.com
```
Then running this returns an error
``` bash
tylerbenton[ 9:01] ~$ brew cleanup --verbose
Error: Unknown command: find
Kernel.exit
```

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by tjbenton** [comment]
https://gist.github.com/tjbenton/d3fc2577337dab5ea8fe

**Comment by tdsmith** [comment]
Does `/usr/bin/find` exist?

**Comment by tenzan** [comment]
It seems this is because of the `~/.curlrc` file. If you rename (not sure if it's OK to remove) it, the warning will disappear.
