### ISSUE TITLE
mitmpoxy upgade 0.11.1 -> 0.11.3

### ISSUE THREAD

**Issue by skandragon** [Homebrew/homebrew#36168]
It requires configargparse, which would have to be added as well.  That's as far as I got.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!

**Comment by jacknagel** [comment]
Will review a pull request.
