### ISSUE TITLE
Include source in Rust formula

### ISSUE THREAD

**Issue by alem0lars** [Homebrew/homebrew#36189]
A lot of times you also need the Rust source code, e.g. when using `racer` or with any editor which provides autocompletion.

Is it possible to include the sources?

PS: I saw that in the makefile there is a way to include source code by using `dist`.

Thanks

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!

**Comment by jacknagel** [comment]
Will review a pull request, assuming upstream recommends this practice for packagers.
