### ISSUE TITLE
fig will be replaced by docker-composer

### ISSUE THREAD

**Issue by hacfi** [Homebrew/homebrew#36182]
Just an issue so we don’t forget to add docker-compose as soon as 1.1.0 is out.

More info at https://github.com/docker/fig/releases/tag/1.1.0-rc1

**Comment by jacknagel** [comment]
Thanks; we don't really like to keep placeholder issues open, though.

**Comment by hacfi** [comment]
Sorry..was more a personal reminder that a real issue! Will create a PR as soon as it’s out. Should the PR replace `fig` entirely or just add `docker-composer` additionally?

**Comment by mxsb** [comment]
http://docs.docker.com/compose/install/ ;)

**Comment by andrewhao** [comment]
Seems like Homebrew should maintain both - for legacy scripts that invoke `fig `.

**Comment by seaneking** [comment]
fig officially deprecated in favour of compose as of today (http://fig.sh)

**Comment by tdsmith** [comment]
Yes, thanks. Accepted in b19b52f; discussion in #37206.
