### ISSUE TITLE
`brew test -v apache-spark` on command-line leaves terminal in non-echo state

### ISSUE THREAD

**Issue by adamv** [Homebrew/homebrew#36192]
Doing `brew test -v apache-spark` on the command-line succeeds, but the terminal is then set to "no echo" for some reason.

Not sure which component (brew, spark, Java 8?) is at fault yet.

**Comment by adamv** [comment]
Entering spark-shell, pasting in our test code, then typing "exit" does not leave the terminal in a weird state.

**Comment by jacknagel** [comment]
I can reproduce by running `spark-shell <<<'sc.parallelize(1 to 1000).count()'` at the command line.

**Comment by adamv** [comment]
Same; not a homebrew problem.
