### ISSUE TITLE
Homebrew does not provide PyQt5.Qsci

### ISSUE THREAD

**Issue by mrloam** [Homebrew/homebrew#36195]
Homebrew now has a formula for PyQt5, and the ``qscintilla2`` formula provides ``PyQt4.Qsci``, but Homebrew does not currently provide a way to install ``PyQt5.Qsci``.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!

**Comment by mrloam** [comment]
Unfortunately I don't have access to a Mac system myself, so I'll contact some QScintilla/PyQt users and ask if any of them are interested in updating the formula.

**Comment by mikemcquaid** [comment]
If it's not an issue you have personally we'll pass on this until there's a PR, sorry.
