### ISSUE TITLE
mysql55 failed to build on 10.10.1

### ISSUE THREAD

**Issue by baocaixiong** [Homebrew/homebrew#36202]
[gist-logs](https://gist.github.com/anonymous/e61c326498305f6bd5bb)

```
-- Performing Test HAVE_PEERCRED - Failed
-- Library mysqlclient depends on OSLIBS z;/usr/local/opt/openssl/lib/libssl.dylib;/usr/local/opt/openssl/lib/libcrypto.dylib
-- Configuring incomplete, errors occurred!
See also "/tmp/mysql55-JfQovT/mysql-5.5.40/CMakeFiles/CMakeOutput.log".
See also "/tmp/mysql55-JfQovT/mysql-5.5.40/CMakeFiles/CMakeError.log".

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-versions/issues
```

**Comment by DomT4** [comment]
Was this a plain build? Looks [similar](https://gist.github.com/anonymous/e61c326498305f6bd5bb#file-01-cmake-L647-L674) to the blowup in #36205. Hmm.

**Comment by DomT4** [comment]
Yup. Fails against the newer OpenSSL. Sigh. Looking into it. There's nothing reported upstream.

**Comment by DomT4** [comment]
Oh, this is fun. ` MySQL55 ` actually builds fine for me without patching:

```
-- Found OpenSSL: /usr/local/opt/openssl/lib/libssl.dylib;/usr/local/opt/openssl/lib/libcrypto.dylib (found version "1.0.2")
-- Looking for SHA512_DIGEST_LENGTH
-- Looking for SHA512_DIGEST_LENGTH - found
```

I'd try updating your ` Xcode ` and trying again. Your CLT and Xcode versions are mismatched. If you're still having trouble after updating, I'll re-open https://github.com/Homebrew/homebrew-versions/pull/630 and work on it some more.

**Comment by baocaixiong** [comment]
@DomT4  thanks, I will try.
:smile:

**Comment by baocaixiong** [comment]
XCode version, 6.1.1, up to date.

1. run `brew doctor` => `Your system is ready to brew.`
2. run `brew update`
3. run `brew install mysql55`

```
==> Installing mysql55 from homebrew/homebrew-versions
==> Downloading http://dev.mysql.com/get/Downloads/MySQL-5.5/mysql-5.5.40.tar.gz
Already downloaded: /Library/Caches/Homebrew/mysql55-5.5.40.tar.gz
==> cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/mysql55/5.5.40 -DMYSQL_DATADIR=/usr/local/var/mysql55 -DINSTALL_MANDIR=/usr/local/Cella
-- Performing Test HAVE_PEERCRED - Failed
-- Library mysqlclient depends on OSLIBS z;/usr/local/opt/openssl/lib/libssl.dylib;/usr/local/opt/openssl/lib/libcrypto.dylib
-- Configuring incomplete, errors occurred!
See also "/tmp/mysql55-gpeISl/mysql-5.5.40/CMakeFiles/CMakeOutput.log".
See also "/tmp/mysql55-gpeISl/mysql-5.5.40/CMakeFiles/CMakeError.log".

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-versions/issues

These open issues may also help:
mysql55 failed to build on 10.10.1 (https://github.com/Homebrew/homebrew/issues/36202)
```

[gist-logs](https://gist.github.com/ef2241548f4ccc5b3d7d)

**Comment by DomT4** [comment]
Thanks. I'll take a look at some point today. It's probably a similar fix to the one Mike wrote up in Homebrew/Homebrew.

**Comment by DomT4** [comment]
#36361 should contain the fix you need.

**Comment by DomT4** [comment]
Can you do ` brew update && brew upgrade -v ` and then attempt to install that ` mysql ` formula again please? It should work now.

**Comment by jacknagel** [comment]
Assuming fixed.

**Comment by baocaixiong** [comment]
ok. hmm.

thank you. @DomT4
