### ISSUE TITLE
brew moo?

### ISSUE THREAD

**Issue by nn2242** [Homebrew/homebrew#36238]
When I execute `brew moo` I get the following:
`Error: Unknown command: moo`

Is this intended behavior? I was expecting to see this:

```         (__) 
         (oo) 
   /------\/ 
  / |    ||   
 *  /\---/\ 
    ~~   ~~   
...."Have you mooed today?"...```

**Comment by mikemcquaid** [comment]
This is intended.

**Comment by iggyvolz** [comment]
You're probably thinking of apt-get moo.
