### ISSUE TITLE
Best strategy to add neo4j-shell-tools

### ISSUE THREAD

**Issue by mindrones** [Homebrew/homebrew#36232]
To install [neo4j-shell-tools](https://github.com/jexp/neo4j-shell-tools) you need to copy some .jar file inside `Cellar/neo4j/<version>/libexec/lib/`, so this requires `neo4j` being installed.

Should I make a separate formula that has `neo4j` as a dependency or an option of the `neo4j` formula, like `--with-shell-tools` and in that case download the jar files and add them to the right location after `neo4j` has been installed correctly?

I'd see fit the second option but I prefer asking. Thanks!

**Comment by mikemcquaid** [comment]
Second option makes sense, thanks!

**Comment by mindrones** [comment]
OK thanks, should I add this to #36230 or wait for it to be merged and do this in another branch/pull-request?

**Comment by mikemcquaid** [comment]
Feel free to add it to #36230.

**Comment by mindrones** [comment]
Done, thanks for the advice!
