### ISSUE TITLE
Your local changes to the following files would be overwritten 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [Homebrew/homebrew#36231]
I don't understand what are these errors. Please explain me why I get this message. Doesn't `brew update`  works like `apt-get update` in linux? Please explain me these error. Basically I want to update all those packages which I installed using homebrew. Thanks.

(removed large screenshots - jack)

**Comment by mikemcquaid** [comment]
Try: `cd /usr/local; git fetch; git reset --hard origin/master; brew update`

**Comment by AbhimanyuAryan** [comment]
@mikemcquaid can you explain what was basically that error? and what are you saying in those commands. Being a computer science student I feel so stupid following them blindly :+1:  (just asking out of curiosity)

**Comment by mikemcquaid** [comment]
@AbhimanyuAryan Homebrew uses a Git repository for managing the files in `/usr/local` and updates to those files. The commands I gave you changed to the Homebrew repository's working directory (`cd /usr/local`), downloaded the latest changes from our GitHub repository (`git fetch`), reset the local state to match the latest remote state (`git reset --hard origin/master`) and then used Homebrew's updater to try and update everything that way too (`brew update`).

**Comment by AbhimanyuAryan** [comment]
@mikemcquaid i tried to update everything again this time i did `git reset --hard origin/master`

`Abhimanyus-MacBook-Pro:local abhimanyuaryan$ git reset --hard origin/master`
`error: unable to unlink old 'share/doc/homebrew/Formula-Cookbook.md' (Permission denied)`
`error: unable to unlink old 'share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md' (Permission denied)`
`error: unable to unlink old 'share/doc/homebrew/Interesting-Taps-&-Branches.md' (Permission denied)`
`error: unable to unlink old 'share/doc/homebrew/Python-for-Formula-Authors.md' (Permission denied)`
`error: unable to unlink old 'share/doc/homebrew/The-brew-command.md' (Permission denied)
fatal: Could not reset index file to revision 'origin/master'.`
`Abhimanyus-MacBook-Pro:local abhimanyuaryan$ sudo git reset --hard origin/master`
`Password:`
`HEAD is now at eb41d05 Use ternary instead of inline rescue`

i got this error what does it say and how to fix it.....I am very annoyed by not knowing much about how exactly homebrew works. I was trying to update everything and then i wanted to install wget via homebrew but that also showed me a lot errors.

`Abhimanyus-MacBook-Pro:local abhimanyuaryan$ brew install wget`
`Error: You must `brew link pkg-config' before wget can be installed`
`Abhimanyus-MacBook-Pro:local abhimanyuaryan$ brew link pkg-config`
`Linking /usr/local/Cellar/pkg-config/0.28... `
`Error: Could not symlink share/doc/pkg-config`
`/usr/local/share/doc is not writable.`
`Abhimanyus-MacBook-Pro:local abhimanyuaryan$`

**Comment by tdsmith** [comment]
These permission errors can occur if you used sudo to install something to /usr/local and left root with ownership of some of the folders there. You can reset ownership of /usr/local/share (or other paths as necessary) to your current user with `sudo chown -R $(whoami) /usr/local/share`.

**Comment by AbhimanyuAryan** [comment]
@tdsmith can you link me to a guide where i can learn homebrew usage more easily ?

**Comment by AbhimanyuAryan** [comment]
@tdsmith also what that whoami? is that some username...should i change it to mine's

**Comment by AbhimanyuAryan** [comment]
@mikemcquaid  also i was trying to install git using brew i get an error: 

==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/git-2.3.0.y
`Already downloaded: /Library/Caches/Homebrew/git-2.3.0.yosemite.bottle.tar.gz`
`Error: SHA1 mismatch`
`Expected: 53177456ab367faa30e1d49104e8e2c065ac5613`
`Actual: 0c558c2f7963e2912f0d6f476a6478bbd987004d`
`Archive: /Library/Caches/Homebrew/git-2.3.0.yosemite.bottle.tar.gz`
`To retry an incomplete download, remove the file above.`
`Warning: Bottle installation failed: building from source.`

**Comment by mikemcquaid** [comment]
Run `sudo chown -R $USER /usr/local /Library/Caches/Homebrew`.

**Comment by AbhimanyuAryan** [comment]
fixed errors and installed wget @mikemcquaid  thanks a million. One last question can you please tell me 

what's you doing in the above command. As far i know chown command is to change permissions but what's that $USER and /usr/local /Library/Caches/Homebrew. Why do you need to change permissions?

**Comment by mikemcquaid** [comment]
Because you were getting `permissions denied`.
