### ISSUE TITLE
Can't install valgrind on Yosemite

### ISSUE THREAD

**Issue by boyanpenkov** [Homebrew/homebrew#36234]
Hey folks -- 

When on Yosemite:
```
brew install valgrind
```
yields:
``` 
valgrind: OS X Mavericks or older is required.
Error: An unsatisfied requirement failed this build.
```

I suspect this is because `valgrind.rb` hasn't been updated.

Cheers!

**Comment by mikemcquaid** [comment]
It's because Valgrind's current stable release doesn't support Yosemite.

**Comment by boyanpenkov** [comment]
Hmm, "there's your' problem..."

Installing it from --HEAD (here: https://stackoverflow.com/questions/26564125/yosemite-and-valgrind) does work for me.

Thanks for the catch!
