### ISSUE TITLE
Upgrade terraform to 0.3.6

### ISSUE THREAD

**Issue by dicato** [Homebrew/homebrew#36245]
0.3.6 was released on January 6, 2015. See their [changelog](https://github.com/hashicorp/terraform/blob/918ba4c3be634170e95e757e8edef24393ccb03f/CHANGELOG.md).

I will work on a pull request!

**Comment by dicato** [comment]
Any recommendations on how to check if terraform's dependencies should be updated?

I can't find it anywhere obvious, such as the referenced changelog above. I can install go and the appropriate tooling locally and use their [makefile](https://github.com/hashicorp/terraform/blob/918ba4c3be634170e95e757e8edef24393ccb03f/Makefile) but wanted to make sure that was the best approach before doing so.

**Comment by mikemcquaid** [comment]
I think it's generally safe to try and just update the `sha1` and `url` and add dependencies only if it breaks without them.

**Comment by dicato** [comment]
Thanks @mikemcquaid - I'll take that approach. I briefly noticed tests not passing as well, which I believe are related to the `ATLAS` environment variable discuss in the pull request for 0.3.5 - #34849

Thanks again, I'll try to get a PR up soon.
