### ISSUE TITLE
sphinx-2.1.9 failed to build on Max OS X v.10.10.1

### ISSUE THREAD

**Issue by nehagjain15** [Homebrew/homebrew#36246]
Hi,
I tried to install sphinx version 2.1.9 on my machine, but it fails due to sha mismatch error.

$git checkout a03e090 Library/Formula/sphinx.rb
$brew install sphinx --mysql
==> Downloading http://sphinxsearch.com/files/sphinx-2.1.9-release.tar.gz
######################################################################## 100.0%
==> Downloading http://snowball.tartarus.org/dist/libstemmer_c.tgz
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: 9b0f120a68a3c688b2f5a8d0f681620465c29d38
Actual: 1ac6bb16e829e9f3a58f62c27047c26784975aa1
Archive: /Library/Caches/Homebrew/sphinx--stemmer-c.tgz
To retry an incomplete download, remove the file above.
$ brew gist-logs sphinx
Error: No logs.

I can install latest version of sphinx without any issues. Bur I need this version for my app.

P.S: I did run brew update and brew doctor before installation.
Thanks.

**Comment by jacknagel** [comment]
Sorry, we can't support checking out old versions from the history. You'll need to manually update any checksums that no longer match.
