### ISSUE TITLE
phantomjs 2.0.0

### ISSUE THREAD

**Issue by KrauseFx** [Homebrew/homebrew#36240]
Not sure about the current status of `phantomjs`, but there is a new 2.0.0 release: https://github.com/ariya/phantomjs/releases/tag/2.0.0

There is no working pre-built package available yet.

More information: https://github.com/ariya/phantomjs/issues/12897

**Comment by mikemcquaid** [comment]
It doesn't build, unfortunately.

**Comment by horribleperson** [comment]
I can build phantomjs2 on my system.
Ubuntu 12.04.1 LTS x64 
gcc 4.8.2
using build.sh --confirm --qtdeps=system

**Comment by ariya** [comment]
Yosemite doesn't build yet, ref: https://github.com/ariya/phantomjs/issues/12630

**Comment by mikemcquaid** [comment]
Thanks @ariya.

**Comment by alex88** [comment]
Wouldn't be easier to include phantomjs to https://github.com/Homebrew/homebrew-binary ?

**Comment by mikemcquaid** [comment]
@alex88 Yeh, perhaps. I'd love if we can help PhantomJS get CI so that it keeps building on the current version of OS X, though CC @ariya.
