### ISSUE TITLE
sphinx-2.0.6 failed to build on 10.10.1

### ISSUE THREAD

**Issue by nehagjain15** [Homebrew/homebrew#36244]
Hi,

I am trying to install an old version os sphinx 2-0.6 and its failing with following error.

brew install sphinx --mysql
==> Downloading http://sphinxsearch.com/files/sphinx-2.0.6-release.tar.gz
######################################################################## 100.0%
Error: wrong number of arguments (0 for 3)
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula.rb:86:in `initialize'
/usr/local/Library/Formula/sphinx.rb:38:in `new'
/usr/local/Library/Formula/sphinx.rb:38:in `install'
/usr/local/Library/Homebrew/build.rb:136:in `block in install'
/usr/local/Library/Homebrew/formula.rb:402:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:757:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:91:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:21:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:755:in `stage'
/usr/local/Library/Homebrew/formula.rb:398:in `brew'
/usr/local/Library/Homebrew/build.rb:114:in `install'
/usr/local/Library/Homebrew/build.rb:185:in `<main>

There is no log file or anything extra to report.
I did run brew update and brew doctor and everything is good.

I can successfully install sphinx v. 2.2.6 and 2.2.5

**Comment by jacknagel** [comment]
Sorry, we don't support checking out old versions from the history. They may use API or reference constants that no longer exist.

The best bet is to simply change the current formula to point at the version you need.
