### ISSUE TITLE
byobu 2.90

### ISSUE THREAD

**Issue by isamuelson** [Homebrew/homebrew#36255]

**Comment by tdsmith** [comment]
It would be great if you could open a pull request for this change. We have some guidance here: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Let me know if you have any questions; we're happy to help!

**Comment by isamuelson** [comment]
https://github.com/Homebrew/homebrew/pull/36287

hopefully its right...

**Comment by asparagui** [comment]
@isamuelson Looks good, thanks!
