### ISSUE TITLE
Unable to install mp3splt

### ISSUE THREAD

**Issue by JESii** [Homebrew/homebrew#36266]
Started this install on Mavericks after updating brew and upgrading all outdated formulae; eventually got this error:
```bash
==> Installing mp3splt dependency: flac
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/flac-1.3.1.mavericks.bottle.tar.gz

curl: (56) SSLRead() return error -9806
Error: Failed to download resource "flac"
Download failed: https://downloads.sf.net/project/machomebrew/Bottles/flac-1.3.1.mavericks.bottle.tar.gz
Warning: Bottle installation failed: building from source.
Error: /usr/local/opt/xz not present or broken
Please reinstall xz. Sorry :(
```

**Comment by iggyvolz** [comment]
The error is with flac and not with mp3split.  Try again - it may have been a temporary network error.

If the download still fails, try to download https://downloads.sf.net/project/machomebrew/Bottles/flac-1.3.1.mavericks.bottle.tar.gz in your browser - if it doesn't work then it looks like you may be behind a proxy of some sort.  The file download worked for me so it seems to be up.

**Comment by jacknagel** [comment]
Yes, this is almost certainly a temporary network error.
