### ISSUE TITLE
Can't not re-install brew on OSX 10.10 

### ISSUE THREAD

**Issue by i4han** [Homebrew/homebrew#36262]
Homebrew was previously installed but broken so I had to reinstall. Permission error occurs when 'git reset --hard origin/master' runs.
This is steps I took.

    $ brew update
    /usr/local/bin/brew: /usr/local/Library/brew.rb: /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby: bad interpreter: No such file or directory
    /usr/local/bin/brew: line 26: /usr/local/Library/brew.rb: Undefined error: 0

    $ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    It appears Homebrew is already installed. If your intent is to reinstall you
    should do the following before running this installer again:
    rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup

    $ rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
    rm: /usr/local/Cellar/apple-gcc42: Permission denied
    rm: /usr/local/Cellar/freetype: Permission denied
    rm: /usr/local/Cellar/mongodb/2.4.10/bin/bsondump: Permission denied
    rm: /usr/local/Cellar/mongodb/2.4.10/bin/mongo: Permission denied
    rm: /usr/local/Cellar/mongodb/2.4.10/bin/mongod: Permission denied
    rm: /usr/local/Cellar/mongodb/2.4.10/bin/mongodump: Permission denied
    rm: /usr/local/Cellar/mongodb/2.4.10/bin/mongoexport: Permission denied
    rm: /usr/local/Cellar/mongodb/2.4.10/bin/mongofiles: Permission denied
    rm: /usr/local/Cellar/mongodb/2.4.10/bin/mongoimport: Permission denied
    rm: /usr/local/Cellar/mongodb/2.4.10/bin/mongooplog: Permission denied
    rm: /usr/local/Cellar/mongodb/2.4.10/bin/mongoperf: Permission denied
    rm: /usr/local/Cellar/mongodb/2.4.10/bin/mongorestore: Permission denied
    rm: /usr/local/Cellar/mongodb/2.4.10/bin/mongos: Permission denied
    rm: /usr/local/Cellar/mongodb/2.4.10/bin/mongosniff: Permission denied
    rm: /usr/local/Cellar/mongodb/2.4.10/bin/mongostat: Permission denied
    rm: /usr/local/Cellar/mongodb/2.4.10/bin/mongotop: Permission denied
    rm: /usr/local/Cellar/mongodb/2.4.10/bin: Permission denied
    ... and continues

    $ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    ==> This script will install:
    /usr/local/bin/brew
    /usr/local/Library/...
    /usr/local/share/man/man1/brew.1
    ==> The following directories will be made group writable:
    /usr/local/.
    /usr/local/bin
    /usr/local/etc
    /usr/local/include
    /usr/local/lib
    /usr/local/Library
    /usr/local/share
    /usr/local/var
    /usr/local/share/man
    /usr/local/share/man/man1
    /usr/local/share/man/man8
    /usr/local/share/doc
    /usr/local/share/aclocal
    ==> The following directories will have their group set to admin:
    /usr/local/.
    /usr/local/bin
    /usr/local/etc
    /usr/local/include
    /usr/local/lib
    /usr/local/Library
    /usr/local/share
    /usr/local/var
    /usr/local/share/man
    /usr/local/share/man/man1
    /usr/local/share/man/man8
    /usr/local/share/doc
    /usr/local/share/aclocal

    Press RETURN to continue or any other key to abort
    ==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/. /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/Library /usr/local/share /usr/local/var /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man8 /usr/local/share/doc /usr/local/share/aclocal
    ==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/. /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/Library /usr/local/share /usr/local/var /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man8 /usr/local/share/doc /usr/local/share/aclocal
    ==> /usr/bin/sudo /bin/mkdir /Library/Caches/Homebrew
    ==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
    ==> Downloading and installing Homebrew...
    remote: Counting objects: 227467, done.
    remote: Compressing objects: 100% (59755/59755), done.
    remote: Total 227467 (delta 166488), reused 227430 (delta 166461)
    Receiving objects: 100% (227467/227467), 52.25 MiB | 527.00 KiB/s, done.
    Resolving deltas: 100% (166488/166488), done.
    From https://github.com/Homebrew/homebrew
     * [new branch]      master     -> origin/master
    error: unable to unlink old 'Library/Homebrew/extend/ENV/shared.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/extend/ENV/std.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/extend/ENV/super.rb' (Permission denied)
    error: unable to create file Library/Homebrew/language/go.rb (Permission denied)
    error: unable to create file Library/Homebrew/language/haskell.rb (Permission denied)
    error: unable to unlink old 'Library/Homebrew/language/python.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/utils/inreplace.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/utils/json.rb' (Permission denied)
    error: unable to create file Library/Homebrew/utils/popen.rb (Permission denied)
    error: unable to unlink old 'Library/Homebrew/vendor/okjson.rb' (Permission denied)
    fatal: Could not reset index file to revision 'origin/master'.
    Failed during: git reset --hard origin/master

    $ rm -rf /usr/local/Cellar /usr/local/.git 
    $ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    ==> This script will install:
    /usr/local/bin/brew
    /usr/local/Library/...
    /usr/local/share/man/man1/brew.1

    Press RETURN to continue or any other key to abort 
    ==> Downloading and installing Homebrew...
    remote: Counting objects: 227503, done.
    remote: Compressing objects: 100% (59787/59787), done.
    remote: Total 227503 (delta 166512), reused 227434 (delta 166464)
    Receiving objects: 100% (227503/227503), 52.36 MiB | 410.00 KiB/s, done.
    Resolving deltas: 100% (166512/166512), done.
    From https://github.com/Homebrew/homebrew
     * [new branch]      master     -> origin/master
    error: unable to unlink old 'Library/Homebrew/extend/ENV/shared.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/extend/ENV/std.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/extend/ENV/super.rb' (Permission denied)
    error: unable to create file Library/Homebrew/language/go.rb (Permission denied)
    error: unable to create file Library/Homebrew/language/haskell.rb (Permission denied)
    error: unable to unlink old 'Library/Homebrew/language/python.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/utils/inreplace.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/utils/json.rb' (Permission denied)
    error: unable to create file Library/Homebrew/utils/popen.rb (Permission denied)
    error: unable to unlink old 'Library/Homebrew/vendor/okjson.rb' (Permission denied)
    fatal: Could not reset index file to revision 'origin/master'.
    Failed during: git reset --hard origin/master

    $ sudo chown $USER /usr/local
    $ rm -rf /usr/local/Cellar /usr/local/.git 
    $ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" 
    ==> This script will install:
    /usr/local/bin/brew
    /usr/local/Library/...
    /usr/local/share/man/man1/brew.1

    Press RETURN to continue or any other key to abort
    ==> Downloading and installing Homebrew...
    remote: Counting objects: 227503, done.
    remote: Compressing objects: 100% (59787/59787), done.
    remote: Total 227503 (delta 166512), reused 227434 (delta 166464)
    Receiving objects: 100% (227503/227503), 52.36 MiB | 1.10 MiB/s, done.
    Resolving deltas: 100% (166512/166512), done.
    From https://github.com/Homebrew/homebrew
     * [new branch]      master     -> origin/master
    error: unable to unlink old 'Library/Homebrew/extend/ENV/shared.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/extend/ENV/std.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/extend/ENV/super.rb' (Permission denied)
    error: unable to create file Library/Homebrew/language/go.rb (Permission denied)
    error: unable to create file Library/Homebrew/language/haskell.rb (Permission denied)
    error: unable to unlink old 'Library/Homebrew/language/python.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/utils/inreplace.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/utils/json.rb' (Permission denied)
    error: unable to create file Library/Homebrew/utils/popen.rb (Permission denied)
    error: unable to unlink old 'Library/Homebrew/vendor/okjson.rb' (Permission denied)
    fatal: Could not reset index file to revision 'origin/master'.
    Failed during: git reset --hard origin/master

    $ cd /usr/local
    $ git reset --hard origin/master
    error: unable to unlink old 'Library/Homebrew/extend/ENV/shared.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/extend/ENV/std.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/extend/ENV/super.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/language/go.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/language/haskell.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/language/python.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/utils/inreplace.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/utils/json.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/utils/popen.rb' (Permission denied)
    error: unable to unlink old 'Library/Homebrew/vendor/okjson.rb' (Permission denied)
    fatal: Could not reset index file to revision 'origin/master'.

**Comment by mikemcquaid** [comment]
`sudo chown -R $USER /usr/local`

**Comment by i4han** [comment]
Yep. I works fine. Thanks.

**Comment by i4han** [comment]
$ sudo chown -R $USER /usr/local
    Password:
    $ cd /usr/local
    $ git reset --hard origin/master
    HEAD is now at f0b33e0 erlang: update 17.4_1 bottle.
