### ISSUE TITLE
Upgrade mono to 3.12

### ISSUE THREAD

**Issue by haf** [Homebrew/homebrew#36279]

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!

**Comment by haf** [comment]
I will.

**Comment by haf** [comment]
Mono installs 32 bits by default.

I want to install with 64 bits. Something I can find in docs: http://www.mono-project.com/docs/compiling-mono/mac/#building-mono-from-a-release-package

I'm thinking of doing:

``` ruby
option 'with-64bit', 'Compile Mono in 64-bit mode'
````

However, I have three questions:

One; How do I make sure that this installation doesn't override the 'defaults' as installed with [Xamarin Studio](http://xamarin.com/studio)? Default `mono`, default `fsharpi` binaries, that is. Or should it override by default and be possible to 'un-link'?
Two, is this the right way to check for the option inside `#install`?

``` ruby
  3     unless build.with? '64bit'¬
  2       args << "--build=" + (MacOS.prefer_64_bit? ? "x86_64": "i686") + "-apple-darwin"¬
  1     end
```

Three; with now the formula says `MacOS.prefer_64_bit? ? "x86_64": "i686"`, but `$ arch => i386` on my system (Mavericks for stability) -- what should it be?

**Comment by mikemcquaid** [comment]
Yep, that's the right way. I do wonder if it should default to build in 64-bit by default, though?

**Comment by haf** [comment]
Given that XS installs 32 bits and keeps it up to date, the most likely contender to install with homebrew should be 64 bits, right?

What's with the `prefer_64_bit` flag?

**Comment by haf** [comment]
And how do I make sure it doesn't override already installed binaries on `install`?

**Comment by mikemcquaid** [comment]
> Given that XS installs 32 bits and keeps it up to date, the most likely contender to install with homebrew should be 64 bits, right?
> 
> What's with the prefer_64_bit flag?

That flag is just to work out whether an OS supports 64-bit builds.

> And how do I make sure it doesn't override already installed binaries on install?

Sorry, I'm not sure what you mean here.

**Comment by haf** [comment]
Here's a sample PR, I'm going to test it first, before it gets merged.

**Comment by haf** [comment]
@mikemcquaid I mean that this is the state of my system before installing the formula:

```
➜  Formula git:(upgrade/mono) ✗ ls -lah /usr/bin/fsharpi
lrwxr-xr-x  1 root  wheel    51B Sep 11 11:06 /usr/bin/fsharpi -> /Library/Frameworks/Mono.framework/Commands/fsharpi
```

So there are existing binaries; I just was wondering how homebrew handles existing binaries which are in the same location as those that are getting installed?

**Comment by haf** [comment]
I'd be interested in feedback on this PR.

**Comment by haf** [comment]
Done.

Now it's a question of how to handle fsharpi. Any suggestions from @rneatherway ? Or someone from the mono project could weigh in?

**Comment by haf** [comment]
So, there's the https://github.com/Homebrew/homebrew/blob/master/Library/Formula/fsharp.rb formula - let's use that instead.

I've remade the fsharp test commit to be a keg_only commit. I hope I understand the terminology correctly.

**Comment by jacknagel** [comment]
Closing in favor of #36279.
