### ISSUE TITLE
Duplicity fails to find Crypto.PublicKey

### ISSUE THREAD

**Issue by boyanpenkov** [Homebrew/homebrew#36278]
Installing duplicity, and then running 
```
duplicity --encrypt-key me@me.com test sftp://boyan@machine.com/backups
```
yields this
```
Duplicity 0.6 series is being deprecated:
See http://www.nongnu.org/duplicity/

BackendException: Could not initialize backend: No module named Crypto.PublicKey
```
I have paramiko and pycrypt installed, they `import` fine, and Crypto.PublicKey is in the correct `site-packages` directory.

Reinstalling duplicity, including `--build-from-source` didn't help.

Any thoughts?

**Comment by tdsmith** [comment]
We use system Python for apps like this so the relevant site-packages isn't what you'd expect. The problem is that duplicity isn't very good about declaring its dependencies and we have a few missing from the several that we install, sorry! pycrypto got left out; looks like we also need ecdsa.

**Comment by boyanpenkov** [comment]
I have ecdsa 0.11 and pycrypto 2.6.1 installed, both via pip.  

Should I look at another version of ecdsa?
--
Boyan Penkov
www.boyanpenkov.com

**Comment by tdsmith** [comment]
`brew update && brew reinstall duplicity` should resolve this.

**Comment by boyanpenkov** [comment]
Yep, confirmed; works great!  Thanks!
