### ISSUE TITLE
python does not create symlink to include dir

### ISSUE THREAD

**Issue by isamuelson** [Homebrew/homebrew#36290]
symlink should be created for $(brew --prefix)/include

**Comment by mikemcquaid** [comment]
Why?

**Comment by isamuelson** [comment]
because i don't want to reference directly to the celler dir

 check https://github.com/Homebrew/homebrew/issues/36256

**Comment by mistydemeo** [comment]
We recommend using `python-config`, which is installed, to get the path to the include directory from inside the framework. e.g. `python-config --includes`. (This is consistent with how the OS's Python is installed, too.)

**Comment by isamuelson** [comment]
thanks...will use that
