### ISSUE TITLE
SFML 2.2

### ISSUE THREAD

**Issue by tioover** [Homebrew/homebrew#36311]
https://github.com/Homebrew/homebrew/blob/d3327217701500cc372f3e05996b7e57e70e6752/Library/Formula/sfml.rb#

2.2 fixed Yosemite compile.

    # Please remove this block with the next stable release.
    depends_on MaximumMacOSRequirement => :mavericks

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!

**Comment by DomT4** [comment]
Unless anything has changed, there's the outstanding issues to resolve in #35479.

**Comment by adamv** [comment]
Closing as duplicate.
