### ISSUE TITLE
Upgrade nodejs to 0.10.36

### ISSUE THREAD

**Issue by EloB** [Homebrew/homebrew#36322]
The newest stable version is 0.10.36. http://nodejs.org/

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!

**Comment by EloB** [comment]
I would love too but I have deadline from hell right now... The new version has a fix for the broken debugger in node thats why I want it...

**Comment by DomT4** [comment]
There's one open already in #36280 :)

**Comment by adamv** [comment]
Closing as duplicate.
