### ISSUE TITLE
formula for libguestfs

### ISSUE THREAD

**Issue by tristan-k** [Homebrew/homebrew#36334]
I recently discovered libguestfs (http://libguestfs.org/). It seems it is possible to compile it for Mac OS X. Is someone brave enough to make a formula?

http://comments.gmane.org/gmane.comp.emulators.guestfs/3348
https://rwmj.wordpress.com/2010/03/21/libguestfs-now-works-on-mac-os-x/

**Comment by tdsmith** [comment]
Would you like to give it a shot? We don't really take requests but the [formula cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md) and [how to open a PR and get it merged](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md) guides should help. This looks like a useful tool and it'd be great to have a formula for it. To the extent that patches are needed to build on OS X, we'd like to see upstream have a plan for integrating them into the main tree in most cases, so reaching out to them might be a part of the process.

**Comment by shulima** [comment]
@tristan-k I'm working on a formula, just ironing out the patches and getting as many options to compile as I can before I submit a request. Should be a few days (assuming my formula gets approved).

**Comment by tristan-k** [comment]
Awesome! Please notify me. I appreciate your efforts.
