### ISSUE TITLE
post-install doesn't always respect build options

### ISSUE THREAD

**Issue by xaka** [Homebrew/homebrew#36335]
To reproduce the issue please follow the steps:

1. Install node.js without npm: `brew install --without-npm node`
2. Install npm: `curl -L https://npmjs.com/install.sh | sh`
3. Try to upgrade to latest node.js version or simply run postinstall script: `brew postinstall node`

The following error is given:

```
Error: No such file or directory - /usr/local/Cellar/node/0.10.36/libexec/npm/lib/node_modules/npm
```

I added debug output around https://github.com/Homebrew/homebrew/blob/b64d9b9c431642a7dd8d85c8de5a530f2c79d924/Library/Formula/node.rb#L97 and it doesn't pass the `return if build.without? "npm"` check which means `--without-npm` option wasn't persisted. I might be wrong :)

**Comment by DomT4** [comment]
Ah, yes.

If you do ` brew edit node ` and then change ` return if build.without? "npm" ` to ` next if build.without? "npm" ` does it help at all? If it doesn't, try changing it to just ` if build.with "npm" `.

**Comment by xaka** [comment]
When I use `next`, I'm getting the following error:

```
Error: /usr/local/Library/Formula/node.rb:97: Invalid next
```

When I use `if build.with "npm"`, it passes the check and runs the code.

Is there any kind of database I could look inside and see what options are persisted?

**Comment by DomT4** [comment]
` brew info node ` should show you which options you build with. Example:

```
Built from source with: --with-c-ares
```

**Comment by xaka** [comment]
It gives me back 
```
Built from source with: --without-npm
...
==> Caveats
If you update npm itself, do NOT use the npm update command.
The upstream-recommended way to update npm is:
  npm install -g npm@latest
```

and that caveats confirms that something is wrong because the message would only show up when `if build.with? "npm"` passes

**Comment by mistydemeo** [comment]
`brew info` does not apply used options, for reference.

**Comment by DomT4** [comment]
I've pushed #36339 which should stop the problem reoccurring.

> does not apply used options

Used options?

**Comment by jacknagel** [comment]
I think there is a more subtle issue. The proposed changed shouldn't have any effect. I can't look at it in detail right now but I'll try to this weekend.

**Comment by DomT4** [comment]
Thanks Jack, Appreciate that.
