### ISSUE TITLE
gd failed to bulid on OSX 10.9.5

### ISSUE THREAD

**Issue by gokikamukow** [Homebrew/homebrew#36349]
Wine failed to build while installing gd.  The error message is:

==> Installing dependencies for wine: gd, libgphoto2, little-cms2, jasper, libicns, makedepend, openssl, sane-backends
==> Installing wine dependency: gd
==> Downloading https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/gd-2.1.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/gd/2.1.0_2 --with-png=/usr/local/opt/libpng --with-fontconfig=/usr/local/opt/fontconfig --with-freetype=/usr/local/opt/freetype --with-jpe
==> make install
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I/usr/local/Cellar/libpng/1.6.16/include/libpng16 -I/Users/pholm/Development/Tools/android/android-ndk-r8e/platforms/android-14/arch-arm/usr/local/Cellar/freetype/2.5.5/include/freetype2 -I/usr/local/opt/fontconfig/include -I/usr/local/opt/libtiff/include -g -O2 -I/usr/X11/include -I/usr/local/opt/jpeg/include -fvisibility=hidden -c gd_filter.c -o gd_filter.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I/usr/local/Cellar/libpng/1.6.16/include/libpng16 -I/Users/pholm/Development/Tools/android/android-ndk-r8e/platforms/android-14/arch-arm/usr/local/Cellar/freetype/2.5.5/include/freetype2 -I/usr/local/opt/fontconfig/include -I/usr/local/opt/libtiff/include -g -O2 -I/usr/X11/include -I/usr/local/opt/jpeg/include -fvisibility=hidden -c gd_bmp.c -o gd_bmp.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I/usr/local/Cellar/libpng/1.6.16/include/libpng16 -I/Users/pholm/Development/Tools/android/android-ndk-r8e/platforms/android-14/arch-arm/usr/local/Cellar/freetype/2.5.5/include/freetype2 -I/usr/local/opt/fontconfig/include -I/usr/local/opt/libtiff/include -g -O2 -I/usr/X11/include -I/usr/local/opt/jpeg/include -fvisibility=hidden -c gd_interpolation.c -o gd_interpolation.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I/usr/local/Cellar/libpng/1.6.16/include/libpng16 -I/Users/pholm/Development/Tools/android/android-ndk-r8e/platforms/android-14/arch-arm/usr/local/Cellar/freetype/2.5.5/include/freetype2 -I/usr/local/opt/fontconfig/include -I/usr/local/opt/libtiff/include -g -O2 -I/usr/X11/include -I/usr/local/opt/jpeg/include -fvisibility=hidden -c gd.c -o gd.o >/dev/null 2>&1
make: *** [install-recursive] Error 1

READ THIS: http://git.io/brew-troubleshooting

These open issues may also help:
failed to install wine when configuring gd (https://github.com/Homebrew/homebrew/issues/35831)

**Comment by gokikamukow** [comment]
Gist is here:
https://gist.github.com/a534e326681f3b6672ea.git

**Comment by jacknagel** [comment]
Can you try `brew reinstall freetype`?

**Comment by gokikamukow** [comment]
Hi Jack,

I did so, but still receive the same error when gd installs.

Thanks,
Paul

**Comment by jacknagel** [comment]
This seems bad:

```
-I/Users/pholm/Development/Tools/android/android-ndk-r8e/platforms/android-14/arch-arm/usr/local/Cellar/freetype/2.5.5/include/freetype2
```

I've never seen that, but it looks like there is some homebrew stuff installed inside the android-ndk that is being picked up?

**Comment by gokikamukow** [comment]
Indeed it does, why didn't I see that?  The problem was a leftover Android
NDK configuration in my bash_profile ported over from a previous laptop.
Thanks for your help, all fixed now!
