### ISSUE TITLE
mercurial failed to brew on linux

### ISSUE THREAD

**Issue by alexpenson** [Homebrew/homebrew#36360]
https://gist.github.com/anonymous/5f65a80a667cea6fcf11

**Comment by chdiza** [comment]
I think maybe you meant to raise this issue to Linuxbrew, not Homebrew (which is Mac-only)?

**Comment by mistydemeo** [comment]
Yes, please report this to [linuxbrew](https://github.com/Homebrew/linuxbrew) - thanks!
