### ISSUE TITLE
Cant update 'gem update --system' or 'gem install cocoapods' it gets me error

### ISSUE THREAD

**Issue by delmarz** [Homebrew/homebrew#36374]
ERROR:  Loading command: update (LoadError)
	dlopen(/usr/local/Cellar/ruby/2.2.0/lib/ruby/2.2.0/x86_64-darwin14/openssl.bundle, 9): Library not loaded: @@HOMEBREW_PREFIX@@/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/ruby/2.2.0/lib/ruby/2.2.0/x86_64-darwin14/openssl.bundle
  Reason: image not found - /usr/local/Cellar/ruby/2.2.0/lib/ruby/2.2.0/x86_64-darwin14/openssl.bundle
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

-------------------------------------------------------------------------------------------------------------
here is my 'brew config' 

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: (none)
Last commit: never
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit core2
OS X: 10.10-x86_64
Xcode: 6.1.1
CLT: 6.1.1.0.1.1415683689
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.0/bin/ruby
Java: 1.6.0_65

-------------------------------------------------------------------------------------------------------------
and heres my 'brew doctor'

Warning: /usr/local/bin isn't writable.

This can happen if you "sudo make install" software that isn't managed by
by Homebrew. If a formula tries to write a file to this directory, the
install will fail during the link step.

You should probably `chown` /usr/local/bin

Warning: The /usr/local directory is not writable.
Even if this directory was writable when you installed Homebrew, other
software may change permissions on this directory. Some versions of the
"InstantOn" component of Airfoil are known to do this.

You should probably change the ownership and permissions of /usr/local
back to your user account.

Warning: You have an outdated version of /usr/bin/install_name_tool installed.
This will cause binary package installations to fail.
This can happen if you install osx-gcc-installer or RailsInstaller.
To restore it, you must reinstall OS X or restore the binary from
the OS packages.

Warning: You have uncommitted modifications to Homebrew
If this a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
    cd /usr/local/Library && git stash && git clean -d -f

-------------------------------------------------------------------------------------------------------------

Im using Xcode 6.1 and Yosemite 10.10 Hackintosh build, I want badly need cocoapods for my project but sucessfully loaded it when I 'pod install' its keep me error (Analyzing dependencies
[!] Unable to find a specification for `Parse`)

this is my Podfile inside 

platform :ios, '8.1'

pod 'Parse'

Please help me to fix these issue i want badly finish my project :(

**Comment by mistydemeo** [comment]
```
Warning: You have an outdated version of /usr/bin/install_name_tool installed.
This will cause binary package installations to fail.
This can happen if you install osx-gcc-installer or RailsInstaller.
To restore it, you must reinstall OS X or restore the binary from
the OS packages.
```

This is the source of your problem - it's preventing your packages from being configured correctly on installation. You will need to fix this, and then reinstall your Homebrew packages. Sorry for the inconvenience!

**Comment by delmarz** [comment]
can I restore it without reinstall my osx?.. cause this is hackintosh build whenever if I reinstall maybe I get some error in my kext .. so if there are any ways to restore the binary without reinstalling that would be nice :(

**Comment by mistydemeo** [comment]
If you know someone else with a copy of OS X, they can give you the file. Or if you have the installer packages, you can extract it from there. Otherwise, I don't know of another way to restore it.

**Comment by mistydemeo** [comment]
Sorry. :(

**Comment by delmarz** [comment]
i have an Installer here in yosemite, but im afraid to reinstall it, What file should I extracted? really appreciated in your response :)

**Comment by mistydemeo** [comment]
I'm not sure which package within the installer contains it, I'm afraid. The file you're looking for is `/usr/bin/install_name_tool`.

**Comment by delmarz** [comment]
I just check the installer package but I cannot see the exactly install_name_tool file. :( ..

**Comment by tdsmith** [comment]
You can use a tool named Pacifist to extract install_name_tool from the installation package but I can't give much guidance on using it, sorry.

**Comment by jacknagel** [comment]
Closing as the necessary steps to resolve this have been outlined.
