### ISSUE TITLE
inkscape: dyld: Library not loaded: .../opt/gettext/lib/libintl.8.dylib

### ISSUE THREAD

**Issue by jab** [Homebrew/homebrew#36392]
On my system running brew-installed inkscape gives the following error:

```
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/gettext/lib/libintl.8.dylib
  Referenced from: /usr/local/lib/libgiomm-2.4.1.dylib
  Reason: image not found
```

This occurs with freshly run `brew update && brew upgrade`. `brew doctor` reports no issues. Uninstalling and reinstalling does not help. Please see https://gist.github.com/jab/ced853146fb8be219bc2 for verbose (and `brew --env`) output.

**Comment by mistydemeo** [comment]
Can you try reinstalling gettext and glibmm, then retry installing inkscape?

**Comment by mistydemeo** [comment]
Note that due to the current Sourceforge outage, you may need to wait a bit if you want to use the prebuilt binaries.

**Comment by jab** [comment]
Thank you for the suggestion @mistydemeo, unfortunately no dice:
https://gist.github.com/jab/f560e3545b739df29c56

**Comment by jacknagel** [comment]
Try reinstalling pango (you may need to reinstall other dependencies as well if the also exhibit this problem).

**Comment by jab** [comment]
Thanks @jacknagel, after uninstalling and reinstalling pango and atk it finally worked.

Any idea how it got into this state / how to prevent it happening again?
