### ISSUE TITLE
SlimerJS should use -without-xulrunner by default on Yosemite

### ISSUE THREAD

**Issue by skycaptain** [Homebrew/homebrew#36399]
Since there are some really issues with firefox and xulrunner on Yosemite (See #33558 and #36348) I suggest that SlimerJS should be build without xulrunner by default on Yosemite. This requires Firefox to be installed admittedly, but I think it's better to point out installing Firefox, than providing a non-working version. Any thoughts on this?

**Comment by mikemcquaid** [comment]
I think this is potentially interesting but we'll need to keep the options the same across OSX versions.

If you agree: could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!
