### ISSUE TITLE
GitDownloadStrategy does not handle submodule changes correctly

### ISSUE THREAD

**Issue by chrmoritz** [Homebrew/homebrew#36395]
*first of all: yes I know this is a little corner case which shouldn't affect many formulas, but I had trouble with a custom formula because of this issue*

**Steps to reproduce:**
* create a formula with a GitDownloadStrategy, which checks out a repository with a least one git submodule
* install the formula a least once (this issue only happens if there is a old version of the repository inside the homebrew cache and homebrew tries to update it)
* change the submodule in your repository (e.g. change it to a fork of the old submodule), release a new version and update the formula
* now try to update the formula and you will get this error: `Failure while executing: git submodule -q update --init --recursive` because homebrew tries to checkout the new revision from within the old submodule and not the new one

**Possible fix:**
* run `git submodule sync --recursive` before [`git submodule update --init --recursive`](https://github.com/Homebrew/homebrew/blob/b07847607480e478565f4e7616252c6611cc4354/Library/Homebrew/download_strategy.rb#L649)

**Comment by chrmoritz** [comment]
I have fixed this issue by using a custom download strategy for the affected formula
```ruby
class GitSubmoduleDownloadStrategy < GitDownloadStrategy
    def update_submodules
        quiet_safe_system "git", "submodule", "sync", "--recursive"
        super
    end
end
```
But it would be nice if submodule changes would be supported by the default GitDownloadStrategy.

**Comment by mikemcquaid** [comment]
@chrmoritz Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!

**Comment by chrmoritz** [comment]
sure, btw: you should change the link to the doc inside the repo instead of the old wiki

**Comment by mikemcquaid** [comment]
Good point, thanks.

**Comment by jacknagel** [comment]
Closing in favor of #36466.
