### ISSUE TITLE
update to latest inkscape

### ISSUE THREAD

**Issue by jab** [Homebrew/homebrew#36403]
A major new release of Inkscape just came out today: https://inkscape.org/en/news/2015/01/30/inkscape-version-091-is-released/
Let's get it into brew!

**Comment by mistydemeo** [comment]
Do you mind taking a stab at submitting a pull request? We have a [guide to it here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-%28and-get-it-merged%29.md#how-to-open-a-homebrew-pull-request-and-get-it-merged), and if you need any help just ping us and we'd be glad to help out. Thanks!

**Comment by jacknagel** [comment]
Additionally, the inkscape formula now lives in https://github.com/Homebrew/homebrew-x11, so any issues or pull request should be opened there. Thanks!
