### ISSUE TITLE
Is it possible to make a dependency conditionally need to be have been built with a certain flag?

### ISSUE THREAD

**Issue by metacollin** [Homebrew/homebrew#36407]
I know I can do

```
require "formula"

class Petcat < Formula
  depends_on "kittens" => [:optional, "with-extra-fuzziness"] 
```

which I understand will make kittens an optional dependency, but should the user choose `--with-kittens`, it will require that the formula uses kittens only if it was built with extra-fuzziness.  

Is there a way to make kittens a required dependency, but only require the kittens to be extra fuzzy (with-extra-fuzziness) if, say, a `build.with? "extra-fluffy"` was passed to the main formula.  Example: `brew install petcat` would depend on kittens, regardless of how fuzzy they are, but `brew install petcat --extra-fluffy` would require that the kitten dependency was built with extra fuzziness, and will behave as expected and not build if the kittens aren't extra fuzzy.

Is there a way to do this? I'm wondering if its built in and my poor command of ruby syntax is the only issue here.  Anyway, thanks!

**Comment by tdsmith** [comment]
You can do something like:

```ruby
kitten_opts = [:optional]
kitten_opts << "with-extra-fuzziness" if build.with?("extra-fluffy")
depends_on "kittens" => kitten_opts
```

Having logic in the class definition is kind of an antipattern for architectural reasons but sometimes it can't be avoided.

Also, instead of declining to build petcat if kittens aren't extra-fuzzy, this will rebuild the kittens with-extra-fuzziness and then proceed with the petcat build.

**Comment by metacollin** [comment]
Thank you!  I feel like an idiot - this is so obvious.  And is nothing unique to ruby.  I was caught up thinking of this is a self-contained build system with depends_on being something akin to #include.  Which is silly,  it's still ruby, and depends_on is a method in the Formula parent class =P.  If you can pass an array of keys, you can do whatever you want to construct that array before passing it.  Duh.   Ugh, I can't believe that never occurred to me.

Anyway, thank you for your help and having the patience to answer such a basic question.  Now I can add all the functionality I wanted to my tap! :)
