### ISSUE TITLE
SHA1 mismatch for unittest-cpp

### ISSUE THREAD

**Issue by clarkcb** [Homebrew/homebrew#36400]
$ sudo brew install unittest-cpp
==> Downloading https://downloads.sourceforge.net/project/unittest-cpp/UnitTest++/1.4/unittest-cpp-1.4.zip
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: dad944159e2e135aea74039987490eaaee00f2ad
Actual: 557d4c4b3d420911b16c1c477e68403bcebbb717
Archive: /Library/Caches/Homebrew/unittest-cpp-1.4.zip
To retry an incomplete download, remove the file above.
$

**Comment by DomT4** [comment]
I presume SF is still feeling a little cranky. I get a different SHA completely:

` 91cc977d613f90cb50d094c6eed6bb0c0d96c0f3 ~/Downloads/unittest-cpp-1.4.zip `

**Comment by clarkcb** [comment]
Hi, was there an issue with Sourceforge? Anyway, how long should I wait before it should work? It's been 18 hours and I'm still having the same problem.

**Comment by DomT4** [comment]
Yeah, they had some major issues [last night](https://twitter.com/sfnet_ops/status/561228107630129153).

Oddly, I'm still seeing the problem today as well:

```
brew fetch unittest-cpp
==> Downloading https://downloads.sourceforge.net/project/unittest-cpp/UnitTest++/1.4/unittest-cpp-1.4.zip
######################################################################## 100.0%
Downloaded to: /Library/Caches/Homebrew/unittest-cpp-1.4.zip
SHA1: fb4647f58cb026a3899bd2afa9cd3de79aa62d34
SHA256: fce6b6945f5f2d2d27ca7e48dfe5bf7d98ba3e17d1a15bf63382a511c02c2d5d
Warning: Formula reports different SHA1: dad944159e2e135aea74039987490eaaee00f2ad
```

What SHA are you seeing with that command?

**Comment by clarkcb** [comment]
Strangely I'm getting a different actual SHA every time I try, some examples:

==> Downloading https://downloads.sourceforge.net/project/unittest-cpp/UnitTest++/1.4/unittest-cpp-1.4.zip
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: dad944159e2e135aea74039987490eaaee00f2ad
Actual: 585edfdec04ae45f715bb468792681927a06e82c

==> Downloading https://downloads.sourceforge.net/project/unittest-cpp/UnitTest++/1.4/unittest-cpp-1.4.zip
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: dad944159e2e135aea74039987490eaaee00f2ad
Actual: 752e0fc51652dd5824e0742a3c586a364a240ee8

==> Downloading https://downloads.sourceforge.net/project/unittest-cpp/UnitTest++/1.4/unittest-cpp-1.4.zip
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: dad944159e2e135aea74039987490eaaee00f2ad
Actual: b8fb20eacb62f520b4e86396f104232c23f16b3d

**Comment by DomT4** [comment]
Yup. Still getting mismatched SHAs. Suspect SF is probably having issues, still.

```
SHA1: daf5f1806dfdf55b0f295617bf1bb9e9d41e0a4a
SHA256: cfa7c03a0f7fde930821dc46ee384ae82f1056da0d46e386ab9a833d72c2a575
Warning: Formula reports different SHA1: dad944159e2e135aea74039987490eaaee00f2ad
```

**Comment by jacknagel** [comment]
The sourceforge project pages for unittest-cpp seem to have disappeared entirely; it may have been removed.

**Comment by DomT4** [comment]
Ah. It's been moved to Github. Teeing up a PR now.

**Comment by clarkcb** [comment]
For some reason it's still trying to download from sourceforge when I try to install it. Do I need to wait for the change to propagate, or is there something I need to do on my end? I ran brew update/upgrade but that did not change the outcome for me.

**Comment by DomT4** [comment]
#36433 hasn't been merged yet. The change won't happen till it or something similar to it is merged :)

**Comment by clarkcb** [comment]
Ok, thanks.
