### ISSUE TITLE
qemu failed to install: gcc-4.2 does not work

### ISSUE THREAD

**Issue by sookyungp** [Homebrew/homebrew#36426]
I am trying to install qemu and apparently it is not working right. It reports the error:
ERROR: "/usr/local/bin/gcc-4.2" either does not exist or does not work

I did check gcc exists at the location specified above. What can I do about this?

Here is the log:
https://gist.github.com/anonymous/e560a0ef42d7f1d0fecf

Thanks.

**Comment by mistydemeo** [comment]
```
/var/folders/dy/hpcwsnk120dggx8qymdxg77m0000gn/T//qemu-conf-18644-51132-15971.c:2:2: error: #error __HAIKU__ not defined
/usr/local/bin/gcc-4.2 -m64 -arch x86_64 -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wstrict-prototypes -Wredundant-decls -Wall -Wundef -Wwrite-strings -Wmissing-prototypes -fno-strict-aliasing -c -o /var/folders/dy/hpcwsnk120dggx8qymdxg77m0000gn/T//qemu-conf-5211-51132-28166.o /var/folders/dy/hpcwsnk120dggx8qymdxg77m0000gn/T//qemu-conf-18644-51132-15971.c
<built-in>:0: error: Unknown value '10.10' of -mmacosx-version-min 
```

It looks like your gcc-4.2 install may not be compatible with 10.10.

**Comment by sookyungp** [comment]
How can I fix this? should i use another version of gcc?

**Comment by sookyungp** [comment]
This is another way that I have tried: not specifying the gcc
https://gist.github.com/anonymous/4cea6af8c9c50752ea6a

It still failed, but it proceed farther. Is it facing the same problem as above?

Thanks.

**Comment by sookyungp** [comment]
So what can I do about it? Should I update gcc?

On the other side, I tried it with no "--cc=gcc-4.2" option, which still failed but showed different errors: global register variable problem. How can I solve this problem?
Here is the log: https://gist.github.com/04317d8d5a4b0149a348

Thanks.

**Comment by bfontaine** [comment]
Can you try compiling with something other than gcc 4.2 (e.g. `brew install qemu --cc=gcc-4.9`)? I recently had a [similar issue with Yap](https://github.com/Homebrew/homebrew/issues/35859#issuecomment-70180242) and using a newer gcc fixed it.

**Comment by sookyungp** [comment]
I just tried with gcc 4.9 which didn't work either. But it looks weird because it's complaining that pkg-config is not found, which doesn't make sense because I did. I even uninstall and re-install pkg-config (brew uninstall/install pkg-config). Here is the log:
https://gist.github.com/anonymous/536d969a95a78138cec3

And I also realized that it keeps showing "couldn't understand kern.osversion `14.1.0'". What is it supposed to mean?

Thank you.

**Comment by bfontaine** [comment]
You can `export MACOSX_DEPLOYMENT_TARGET=10.10` in your `~/.bashrc` to remove this `kern.osversion` thing.

**Comment by sookyungp** [comment]
kern.osversion thing is now out of the scene after editing ~/.bashrc. Thanks.

But I'm still encountering a new error regarding unexpected token in a header file:
https://gist.github.com/anonymous/fdf798be90234875fd07

I also realized that there are so many "not-defined" error found in config.log. Is this the cause of the this problem?

Thanks.

**Comment by sookyungp** [comment]
I did some reading about this error and the explanation on this link seems relevant that it does not support global register variables and that Yosemite (10.10) does not support gcc 4.2.
http://forum.gns3.net/topic5148.html
https://trac.macports.org/ticket/45449

I would like some way to know what the problem is, whether it is due to homebrew or something else, or just me missing something. Thank you.

**Comment by jacknagel** [comment]
qemu can't be compiled with GNU gcc on OS X, because some of the OS X frameworks it requires use OS X-only features (like blocks).

**Comment by jacknagel** [comment]
Are you trying to compile qemu 1.1.0 on purpose? The currently packaged version is 2.2.0: https://github.com/Homebrew/homebrew/blob/3f4c455072e204a0689a60802399fa947c6b6c63/Library/Formula/qemu.rb

**Comment by jacknagel** [comment]
ping.

**Comment by sookyungp** [comment]
Sorry, i was trying with macport instead of homebrew because i couldnt find an answer. I am gonna try 2.2.0 version, once i get the current qemu uninstalled. I will get back here as soon as i gotta try the other version (probably early next week). Thank you so much for the help!

**Comment by slavarybalka** [comment]
up

**Comment by tijwelch** [comment]
thanks @jacknagel
