### ISSUE TITLE
`brew untap $(brew tap)` should untap all tapped taps

### ISSUE THREAD

**Issue by chdiza** [Homebrew/homebrew#36421]
Doing `brew untap $(brew tap)` should, I think, untap any tapped taps in succession, much like how `brew rm $(brew list)` will clean out your Cellar.

But it doesn't do that.  Instead, it only untaps the first tap in the list generated by `brew untap $(brew tap)`.

I could hack at this myself if someone points me.  I looked at untap.rb, and it doesn't loop over ARGV.  It calls `tap_args` which only looks at the first element of ARGV.  I'd be afraid to mess up something unconnected (to untapping) by putting an `each` block in `tap_args`.

EDIT: Sorry for the extra dollar-signs; I've been LaTeXing all day :)

**Comment by chdiza** [comment]
Not that I know what I'm doing, but:

I'm thinking that the `tap_args` method in `tap.rb` could be changed so that it takes an argument directly, rather than looking at the first thing in `ARGV`.  E.g.:
````ruby
def tap_args(foo)
  foo.something_or_other =~ HOMEBREW_TAP_ARGS_REGEX
  # etc.
end
````
Then `untap` could roll through:
````ruby
ARGV.each do |arg|
  user, repo = tap_args(arg)
 # Then the rest of what it does now
end
````

I don't know enough to say whether this would mess up the `*tap_args` in line 10 of `tap.rb`.

**Comment by xu-cheng** [comment]
`brew tap | xarges brew untap`

**Comment by mikemcquaid** [comment]
This seems reasonable to me. We'd review a PR.

**Comment by chdiza** [comment]
> brew tap | xargs brew untap

@xu-cheng Doesn't work; same problem that motivated me to open the issue in the first place.  `untap` refuses to consider more than one piece of input.

> This seems reasonable to me. We'd review a PR.

@mikemcquaid What is the referent of "This"?  The goal of having `brew untap $(brew tap)` untapping all tapped taps, or my particular sketch for achieving that goal?  Or both?

**Comment by mikemcquaid** [comment]
> @mikemcquaid What is the referent of "This"? The goal of having brew untap $(brew tap) untapping all tapped taps, or my particular sketch for achieving that goal? Or both?

The goal. Find it hard to visualise the sketch from text alone (my personal failing).

**Comment by chdiza** [comment]
> The goal. Find it hard to visualise the sketch from text alone (my personal failing).

OK.  I'll try to work it up.

**Comment by xu-cheng** [comment]
@chdiza How about: `brew tap | xargs -L 1 brew untap`?

**Comment by chdiza** [comment]
Well *that* works, but we still need a fix, because (a) that is too long, cumbersome, and hard to remember, and (b) the same problem that prompted my opening of this issue also makes the following fail to work:
````
brew untap homebrew/dupes homebrew/versions
````
I think that *should* work, but it doesn't. Because `untap` won't look at more than one argument.
