### ISSUE TITLE
gnuplot failed to build on 10.10.2

### ISSUE THREAD

**Issue by Frank73** [Homebrew/homebrew#36435]
I cannot install gnuplot:

~$ brew install gnuplot --wx --cairo --pdf --with-x --nolua
Warning: gnuplot: --with-x was deprecated; using --with-x11 instead!
Warning: gnuplot: --pdf was deprecated; using --with-pdflib-lite instead!
Warning: gnuplot: --wx was deprecated; using --with-wxmac instead!
Warning: gnuplot: --cairo was deprecated; using --with-cairo instead!
Warning: gnuplot: --nolua was deprecated; using --without-lua instead!
==> Downloading https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.0/gnuplot-5.0.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/gnuplot-5.0.0.tar.gz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/gnuplot/5.0.0 --with-readline=/usr/local/o
==> make
make[4]: *** [term.o] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

READ THIS: http://git.io/brew-troubleshooting

~$

I created a gist:

~$ brew gist-logs gnuplot
https://gist.github.com/5bcce142bc4204b441cc
~$

What can I do?

**Comment by tdsmith** [comment]
Failure is:
``clang -DHAVE_CONFIG_H -I. -I..  -I../term -I../term -DBINDIR=\"/usr/local/Cellar/gnuplot/5.0.0/bin\" -DX11_DRIVER_DIR=\"/usr/local/Cellar/gnuplot/5.0.0/libexec/gnuplot/5.0\" -DQT_DRIVER_DIR=\"/usr/local/Cellar/gnuplot/5.0.0/libexec/gnuplot/5.0\" -DGNUPLOT_SHARE_DIR=\"/usr/local/Cellar/gnuplot/5.0.0/share/gnuplot/5.0\" -DGNUPLOT_PS_DIR=\"/usr/local/Cellar/gnuplot/5.0.0/share/gnuplot/5.0/PostScript\" -DGNUPLOT_JS_DIR=\"/usr/local/Cellar/gnuplot/5.0.0/share/gnuplot/5.0/js\" -DGNUPLOT_LUA_DIR=\"/usr/local/Cellar/gnuplot/5.0.0/share/gnuplot/5.0/lua\" -DCONTACT=\"gnuplot-bugs@lists.sourceforge.net\" -DHELPFILE=\"/usr/local/Cellar/gnuplot/5.0.0/share/gnuplot/5.0/gnuplot.gih\" -DGNUPLOT_X11=\"`echo gnuplot_x11 | sed 's,x,x,'`\" -DXAPPLRESDIR=\"/etc/X11/app-defaults/\"  -I/usr/local/opt/readline/include -I/usr/local/Cellar/gd/2.1.0_2/include -I/usr/local/Cellar/pdflib-lite/7.0.5p3/include -D_REENTRANT -I/usr/local/Cellar/libpng/1.6.16/include/libpng16 -I/usr/local/Cellar/freetype/2.5.5/include/freetype2 -I/usr/local/Cellar/fontconfig/2.11.1/include -I/usr/local/Cellar/freetype/2.5.3_1/include/freetype2 -I@@HOMEBREW_CELLAR@@/glib/2.42.1/include/glib-2.0 -I@@HOMEBREW_CELLAR@@/glib/2.42.1/lib/glib-2.0/include -I@@HOMEBREW_PREFIX@@/opt/gettext/include -I/usr/local/Cellar/pixman/0.32.6/include/pixman-1 -I/usr/local/Cellar/cairo/1.14.0/include/cairo -I/usr/local/Cellar/pango/1.36.8/include/pango-1.0 -I/opt/X11/include  -D_REENTRANT -I/usr/local/Cellar/libpng/1.6.16/include/libpng16 -I/usr/local/Cellar/freetype/2.5.5/include/freetype2 -I/usr/local/Cellar/fontconfig/2.11.1/include -I/usr/local/Cellar/freetype/2.5.3_1/include/freetype2 -I@@HOMEBREW_CELLAR@@/glib/2.42.1/include/glib-2.0 -I@@HOMEBREW_CELLAR@@/glib/2.42.1/lib/glib-2.0/include -I@@HOMEBREW_PREFIX@@/opt/gettext/include -I/usr/local/Cellar/pixman/0.32.6/include/pixman-1 -I/usr/local/Cellar/cairo/1.14.0/include/cairo -I/usr/local/Cellar/pango/1.36.8/include/pango-1.0 -I/opt/X11/include   -g -O2 -c -o term.o term.c``

```
In file included from term.c:1185:
In file included from ./term.h:410:
../term/cairo.trm:89:10: fatal error: 'glib.h' file not found
#include "glib.h"               /* For guint32 */
```

It looks like the @@HOMEBREW's are coming from cairo: https://gist.github.com/anonymous/5bcce142bc4204b441cc#file-config-log-L4853-L4858

`brew reinstall cairo` is the first thing I'd try. After that, you can do `for i in $(find /usr/local/lib -name \*.dylib); do otool -L $i | grep -q HOMEBREW && echo $i; done` to see if there are other libraries that need to be reinstalled.

**Comment by Frank73** [comment]
Hi Tim,

thanks for the answer. I tried the reinstall of cairo, but the error is
still there:

clang -DHAVE_CONFIG_H -I. -I..  -I../term -I../term
-DBINDIR=\"/usr/local/Cellar/gnuplot/5.0.0/bin\"
-DX11_DRIVER_DIR=\"/usr/local/Cellar/gnuplot/5.0.0/libexec/gnuplot/5.0\"
-DQT_DRIVER_DIR=\"/usr/local/Cellar/gnuplot/5.0.0/libexec/gnuplot/5.0\"
-DGNUPLOT_SHARE_DIR=\"/usr/local/Cellar/gnuplot/5.0.0/share/gnuplot/5.0\"
-DGNUPLOT_PS_DIR=\"/usr/local/Cellar/gnuplot/5.0.0/share/gnuplot/5.0/PostScript\"
-DGNUPLOT_JS_DIR=\"/usr/local/Cellar/gnuplot/5.0.0/share/gnuplot/5.0/js\"
-DGNUPLOT_LUA_DIR=\"/usr/local/Cellar/gnuplot/5.0.0/share/gnuplot/5.0/lua\"
-DCONTACT=\"gnuplot-bugs@lists.sourceforge.net\"
-DHELPFILE=\"/usr/local/Cellar/gnuplot/5.0.0/share/gnuplot/5.0/gnuplot.gih\"
-DGNUPLOT_X11=\"`echo gnuplot_x11 | sed 's,x,x,'`\"
-DXAPPLRESDIR=\"/etc/X11/app-defaults/\"  -I/usr/local/opt/readline/include
-I/usr/local/Cellar/gd/2.1.0_2/include
-I/usr/local/Cellar/pdflib-lite/7.0.5p3/include -D_REENTRANT
-I/usr/local/Cellar/libpng/1.6.16/include/libpng16
-I/usr/local/Cellar/freetype/2.5.5/include/freetype2
-I/usr/local/Cellar/fontconfig/2.11.1/include
-I/usr/local/Cellar/freetype/2.5.3_1/include/freetype2
-I@@HOMEBREW_CELLAR@@/glib/2.42.1/include/glib-2.0
-I@@HOMEBREW_CELLAR@@/glib/2.42.1/lib/glib-2.0/include
-I@@HOMEBREW_PREFIX@@/opt/gettext/include
-I/usr/local/Cellar/pixman/0.32.6/include/pixman-1
-I/usr/local/Cellar/cairo/1.14.0/include/cairo
-I/usr/local/Cellar/pango/1.36.8/include/pango-1.0 -I/opt/X11/include
-D_REENTRANT -I/usr/local/Cellar/libpng/1.6.16/include/libpng16
-I/usr/local/Cellar/freetype/2.5.5/include/freetype2
-I/usr/local/Cellar/fontconfig/2.11.1/include
-I/usr/local/Cellar/freetype/2.5.3_1/include/freetype2
-I@@HOMEBREW_CELLAR@@/glib/2.42.1/include/glib-2.0
-I@@HOMEBREW_CELLAR@@/glib/2.42.1/lib/glib-2.0/include
-I@@HOMEBREW_PREFIX@@/opt/gettext/include
-I/usr/local/Cellar/pixman/0.32.6/include/pixman-1
-I/usr/local/Cellar/cairo/1.14.0/include/cairo
-I/usr/local/Cellar/pango/1.36.8/include/pango-1.0 -I/opt/X11/include   -g
-O2 -c -o term.o term.c

In file included from term.c:1185:

In file included from ./term.h:410:

../term/cairo.trm:89:10: fatal error: 'glib.h' file not found

#include "glib.h"               /* For guint32 */

         ^

1 error generated.

make[4]: *** [term.o] Error 1

make[3]: *** [all-recursive] Error 1

make[2]: *** [all] Error 2

make[1]: *** [all-recursive] Error 1

make: *** [all] Error 2


Running your otool commands resulted in:

~$ for i in $(find /usr/local/lib -name \*.dylib); do otool -L $i | grep -q
HOMEBREW && echo $i; done

/usr/local/lib/libgio-2.0.0.dylib

/usr/local/lib/libgio-2.0.dylib

/usr/local/lib/libglib-2.0.0.dylib

/usr/local/lib/libglib-2.0.dylib

/usr/local/lib/libgmodule-2.0.0.dylib

/usr/local/lib/libgmodule-2.0.dylib

/usr/local/lib/libgobject-2.0.0.dylib

/usr/local/lib/libgobject-2.0.dylib

/usr/local/lib/libgthread-2.0.0.dylib

/usr/local/lib/libgthread-2.0.dylib

~$

So I reinstalled glib, which removed all the HOMEBREWs and gnuplot DID
finally install:

~$ brew reinstall glib

*==>** Reinstalling glib*

*==>** Downloading
https://downloads.sf.net/project/machomebrew/Bottles/glib-2.42.1.yosemite.bottle.tar.gz
<https://downloads.sf.net/project/machomebrew/Bottles/glib-2.42.1.yosemite.bottle.tar.gz>*

Already downloaded:
/Library/Caches/Homebrew/glib-2.42.1.yosemite.bottle.tar.gz

*==>** Pouring glib-2.42.1.yosemite.bottle.tar.gz*

🍺  /usr/local/Cellar/glib/2.42.1: 410 files, 17M

~$ for i in $(find /usr/local/lib -name \*.dylib); do otool -L $i | grep -q
HOMEBREW && echo $i; done

~$

~$ brew install gnuplot --wx --cairo --pdf --with-x --nolua

Warning: gnuplot: --with-x was deprecated; using --with-x11 instead!

Warning: gnuplot: --pdf was deprecated; using --with-pdflib-lite instead!

Warning: gnuplot: --wx was deprecated; using --with-wxmac instead!

Warning: gnuplot: --cairo was deprecated; using --with-cairo instead!

Warning: gnuplot: --nolua was deprecated; using --without-lua instead!

*==>** Downloading
https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.0/gnuplot-5.0.0.tar.gz
<https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.0/gnuplot-5.0.0.tar.gz>*

Already downloaded: /Library/Caches/Homebrew/gnuplot-5.0.0.tar.gz

*==>** ./configure --disable-silent-rules
--prefix=/usr/local/Cellar/gnuplot/5.0.0 --with-readline=/usr/local/o*

*==>** make*

*==>** make install*

🍺  /usr/local/Cellar/gnuplot/5.0.0: 46 files, 2.8M, built in 50 seconds

~$


Although I don't understand why the reinstalling of cairo didn't do the
trick but reinstalling glib did, I am happy now :)
So thanks a lot! You are my wizard of the day.

**Comment by tdsmith** [comment]
Great; glad it's working.

**Comment by garymoon** [comment]
I had the same issue just now, and can confirm reinstalling glib fixed it. Thanks a bunch @Frank73!
