### ISSUE TITLE
Cassandra 2.1.0 and 2.1.2 does not include sstable2json

### ISSUE THREAD

**Issue by JensRantil** [Homebrew/homebrew#36441]
**Background:** I have three installations of Cassandra in my `/usr/local/Cellar/cassandra`:
 * 2.0.8.
 * 2.1.0.
 * 2.1.2

(**Problem**) However, only the first includes `sstable2json` utility:
```bash
$ cd /usr/local/Cellar/cassandra
$ find . -name sstable2json
./2.0.8/bin/sstable2json
```
**Expected** is that it should be included in every Cassandra version. AFAIK it has not been deprecated (looked through [changelog](https://github.com/apache/cassandra/blob/trunk/CHANGES.txt)).

Looks like other utilities tools also are missing:
```bash
$ pwd
/usr/local/Cellar/cassandra
$ ls -l
total 0
drwxr-xr-x  46 jens  admin  1564 Jun  9  2014 2.0.8
drwxr-xr-x  49 jens  admin  1666 Jan 15 12:08 2.1.0
drwxr-xr-x  50 jens  admin  1700 Feb  1 22:42 2.1.2
$ ls */bin/
2.0.8/bin/:
cassandra         cassandra-shuffle debug-cql         nodetool          sstablekeys       sstablescrub      sstableupgrade
cassandra-cli     cqlsh             json2sstable      sstable2json      sstableloader     sstablesplit

2.1.0/bin/:
cassandra                     cassandra.logdir_IS_UNDEFINED debug-cql                     sstablekeys                   sstablescrub
cassandra-cli                 cqlsh                         nodetool                      sstableloader                 sstableupgrade

2.1.2/bin/:
cassandra      cassandra-cli  cqlsh          debug-cql      nodetool       sstablekeys    sstableloader  sstablescrub   sstableupgrade
```

**Additional information:**
```bash
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:

    ruby
```

Let me know if I can assist you more in any way.

**Comment by tdsmith** [comment]
Looks like upstream moved them to `tools/bin` in the tarball.

This is a list of tools/bin; which of these are useful?
> cassandra-stress
cassandra-stressd
cassandra.in.sh
json2sstable
sstable2json
sstablelevelreset
sstablemetadata
sstablerepairedset
sstablesplit
token-generator

**Comment by JensRantil** [comment]
> cassandra-stress
> cassandra-stressd
> cassandra.in.sh
> json2sstable
> sstable2json
> sstablelevelreset
> sstablemetadata
> sstablerepairedset
> sstablesplit
> token-generator

@tdsmith All of the above, except `cassandra.in.sh`.

**Comment by gonzaloserrano** [comment]
Hey guys, i was looking for ```cassandra-stress``` to be able to benchmark a cluster so it would be nice to have it.

**Comment by kemist** [comment]
On my brewed version of 2.1.4 `sstable2json` and a few others are missing.

```
ls /usr/local/Cellar/cassandra/2.1.4/bin
-r-xr-xr-x 1 greg staff 7.5K  cassandra
-r-xr-xr-x 1 greg staff 1.8K  cassandra-cli
-r-xr-xr-x 1 greg wheel  74K  cqlsh
-r-xr-xr-x 1 greg staff 2.2K  debug-cql
-r-xr-xr-x 1 greg staff 2.9K  nodetool
-r-xr-xr-x 1 greg staff 1.9K  sstablekeys
-r-xr-xr-x 1 greg staff 1.8K  sstableloader
-r-xr-xr-x 1 greg staff 1.9K  sstablescrub
-r-xr-xr-x 1 greg staff 1.9K  sstableupgrade
```

**Comment by tdsmith** [comment]
It would be great to have a PR that installs these tools to bin! This document can help: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged and I'm happy to answer any questions anyone has, either here or on IRC.

**Comment by DomT4** [comment]
A PR would be very welcome on this, Thanks!
