### ISSUE TITLE
Feature Request: More stats in progress section

### ISSUE THREAD

**Issue by akagr** [Homebrew/homebrew#36449]
Currently the only progress which we can see looks like
```
#################################                                              60.0%
```
It would be really helpful if more stats like download speed, ETA and size etc. were mentioned here. I am pointing towards incorporating some if not all elements of curl. I'll try to see if this is possible via some hidden flag. If not, I'll see if I can't implement this.

**Comment by jacknagel** [comment]
Fetching or installing with `--verbose`/`-v` will invoke curl verbosely.
