### ISSUE TITLE
ghc(devel) install issue

### ISSUE THREAD

**Issue by eccstartup** [Homebrew/homebrew#36453]
There is issue upgrading ghc(bottled) to ghc(devel). I have ghc installed with homebrew(ghc-7.8.4), but upgrading/reinstalling ghc(devel) version requires `ghc-7.8.3` not the bottled ghc. I have trouble downloading ghc source because ssl error(60). This is not the problem in this issue.

[1] https://github.com/Homebrew/homebrew/commit/82356040ae5c7a6cd860143c6e8a1d4b7a60a66a
[2] https://gist.github.com/eccstartup/26af77aeca6798b47105

**Comment by mikemcquaid** [comment]
If you can't download the `ghc` source then that is the problem as you can't install it otherwise as we don't currently provide bottles for `devel` software.

**Comment by eccstartup** [comment]
I don't mean `bottling devel`. AFAIK, after downloading ghc-7.8.3 source, it uses the `7.8.3` to compile the `rc` version `7.10.1-rc2`. But I have already got `7.8.4` from homebrew, who can comple `7.10.1-rc2` as well. Isn't it?

**Comment by mikemcquaid** [comment]
I see. We don't support using bottles to build later versions like that currently but would review a pull request to do so.

**Comment by eccstartup** [comment]
Sounds reasonable.
Thanks.
