### ISSUE TITLE
Unable to guess PHP branch for Formulary::Formulae::Php54Redis

### ISSUE THREAD

**Issue by Eric0808** [Homebrew/homebrew#36451]
Unable to guess PHP branch for Formulary::Formulae::Php54Redis

I get the following error running  "brew update" .
fatal: unable to access 'https://github.com/Homebrew/homebrew/': SSLRead() return error -9806
Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master

How do I fix this?

**Comment by mikemcquaid** [comment]
That's an issue with connecting to GitHub itself. I suggest your ISP or network provider may be at fault here.

**Comment by Eric0808** [comment]
@mikemcquaid  Thanks for your suggestion! I came home to solve the problem.
