### ISSUE TITLE
OpenMPI: gfortran dies

### ISSUE THREAD

**Issue by milicchio** [Homebrew/homebrew#36460]
Dear all, I am trying to build OpenMPI without success. I had first to remove an old gfortran formula, then reinstalled gcc (bottle). Unfortunately, it dies even with the new gcc. 

Here's the gist:

https://gist.github.com/anonymous/d3dca37e71d9b7fdd6d2

Thanks!

**Comment by jacknagel** [comment]
```
dyld: Library not loaded: /usr/local/lib/libgmp.10.dylib
  Referenced from: /usr/local/Cellar/gcc/4.9.2_1/libexec/gcc/x86_64-apple-darwin13.4.0/4.9.2/f951
  Reason: Incompatible library version: f951 requires version 13.0.0 or later, but libgmp.10.dylib provides version 12.0.0
```

Try `brew reinstall gmp`.

**Comment by milicchio** [comment]
Thanks Jack, it worked. Thanks!
