### ISSUE TITLE
xctool run test fail with SDK 8.2

### ISSUE THREAD

**Issue by AymenFarrah** [Homebrew/homebrew#36467]
Hi,

I have the last xctool (xctool -v => 0.2.1)
I have the last XCode Version 6.2 (6C107a)
I try to run test target with xctool on command line :

xctool -project MyApp.xcodeproj -scheme MyAppTests -configuration Debug -sdk "iphonesimulator8.2" clean test

I got this logs :

** CLEAN SUCCEEDED ** (8896 ms)
0 errored, 0 warning (135403 ms)
[Info] Collecting info for testables... (5056 ms)
run-test MyAppTests.xctest (iphonesimulator8.2, logic-test)
-[FAILED_BEFORE TESTS_RAN]

Test did not run: the test bundle stopped running or crashed before the test suite started.
2015-02-02 18:26:14.854 sim[37616:295878] Failed to find SDK: '8.1'

I got this problem only when i use sdks 8.2, is xctool not yet updated with the last beta SDK 8.2 ??

Thank you

**Comment by mistydemeo** [comment]
I see you also [filed this bug against xctool](https://github.com/facebook/xctool/issues/468). It doesn't sound like a Homebrew-specific bug; I'm closing this bug for now, but please feel free to reopen if this turns out to be a Homebrew issue.
