### ISSUE TITLE
Build for screen

### ISSUE THREAD

**Issue by symbiat** [Homebrew/homebrew#36470]
Not really a bug or issue per se but a question:
The GNU `screen` utility is already included with MacOS X, however it doesn't have full support for 256 color terminals, even though Terminal supports 256 colors. The result is that apps running inside screen (e.g. `vim`) that *do* support 256 colors too can't actually use those colors. From Googling around it seems that one of the "fixes" for this is to download and install a local copy of `screen` built with a `--enable-colors256` configure flag. But I'd much rather use Homebrew to manage something like this, so can we include a formula for `screen` instead of `brew` telling me screen is already installed? We could probably just name it "screen256" if we want to keep the existing setup.

**Comment by mistydemeo** [comment]
Homebrew does provide a version of `screen` with that option enabled! You can find it in the [homebrew-dupes](https://github.com/Homebrew/homebrew-dupes) tap, which provides formulae for software that already comes with the OS. You can install via: `brew install homebrew/dupes/screen`.
