### ISSUE TITLE
hdf5/szip fails with ac_cv_prog_make_Executing: command not found

### ISSUE THREAD

**Issue by jwholl** [Homebrew/homebrew#36479]
$ brew install hdf5
==> Installing hdf5 from homebrew/homebrew-science
==> Installing hdf5 dependency: szip
==> Downloading http://www.hdfgroup.org/ftp/lib-external/szip/2.1/src/szip-2.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/szip-2.1.tar.gz
==> ./configure --prefix=/usr/local/Cellar/szip/2.1
./configure: line 2234: ac_cv_prog_make_Executing: command not found
./configure: line 2240: test: too many arguments
no
checking whether to enable maintainer-specific portions of Makefiles... no
configure: error: cannot run /bin/sh bin/config.sub

READ THIS: http://git.io/brew-troubleshooting

Trying to install szip itself (brew install szip) has the same issues
Gist-log: https://gist.github.com/686ac7874e8e1f04a670

**Comment by mistydemeo** [comment]
From config.log:

> Executing ~/.profile...

What's the contents of your `~/.profile`? It looks like something may be interfering.

**Comment by mistydemeo** [comment]
I see the same text in the configure output in the place that failed:

> checking whether make sets $(MAKE)... ./configure: line 2224: ${ac_cv_prog_make_Executing ~/.profile...

**Comment by jwholl** [comment]
I actually removed that file (it had my shell aliases in it)…. now I get:

./configure --prefix=/usr/local/Cellar/szip/2.1
make_set+set}: bad substitution
./configure: line 2234: ac_cv_prog_make_Aliases!: command not found
yes
checking whether to enable maintainer-specific portions of Makefiles... no
configure: error: cannot run /bin/sh bin/config.sub

**Comment by mistydemeo** [comment]
Can you please provide the output of `brew gist-logs szip` again?

**Comment by jwholl** [comment]
Sure: https://gist.github.com/efeb8b669108e62523ce

Thanks for the help!

-Jack

**Comment by mistydemeo** [comment]
Looks like a similar problem:

> hostname = Aliases!
> Jacks-MacBook-Air.local 
> uname -m = x86_64

The file setting up your aliases is echoing text, and it's messing up configure

**Comment by jwholl** [comment]
Yep. ~/.bash_profile was exporting that file as the BASH_ENV variable. Thanks.
-J

**Comment by mistydemeo** [comment]
Is the problem resolved, then?

**Comment by jwholl** [comment]
Yes, thank you very much. 

-
Jack W. Holloway
