### ISSUE TITLE
Unable to: brew install rpm

### ISSUE THREAD

**Issue by joelittlejohn** [Homebrew/homebrew#36472]
When I attempt `brew install rpm` I get the following error:

```
==> Downloading http://rpm5.org/files/rpm/rpm-5.4/rpm-5.4.14-0.20131024.src.rpm
Already downloaded: /Library/Caches/Homebrew/rpm-5.4.14.src.rpm
Malformed UTF-8 character (unexpected non-continuation byte 0xee, 2 bytes after start byte 0xed, expected 3 bytes) in unpack at /usr/local/opt/rpm2cpio/bin/rpm2cpio.pl line 49.
Malformed UTF-8 character (unexpected non-continuation byte 0x03, immediately after start byte 0xdb) in unpack at /usr/local/opt/rpm2cpio/bin/rpm2cpio.pl line 49.
Not an RPM
0 blocks
tar: Error opening archive: Failed to open 'rpm-5.4.14.tar.gz'
Error: Failure while executing: /usr/bin/tar -xzf rpm-5.4.14.tar.gz && rm rpm-5.4.14.tar.gz
```

I tried removing /Library/Caches/Homebrew/rpm-5.4.14.src.rpm just in case the file downloaded was corrupt, but the file redownloads and I get exactly the same error.

I'm using OS X 10.10.1, brew 0.9.5.

**Comment by tdsmith** [comment]
WFM on 10.10.1. Could you share the link `brew gist-logs rpm` provides?

**Comment by joelittlejohn** [comment]
```
$ brew gist-logs rpm
Error: No logs.
```

**Comment by joelittlejohn** [comment]
I use the GNU tools as described here: https://www.topbug.net/blog/2013/04/14/install-and-use-gnu-command-line-tools-in-mac-os-x/ Maybe this is causing me a problem?

**Comment by jacknagel** [comment]
Can you try without them and see?

**Comment by joelittlejohn** [comment]
Sorry, I'm a bit of an OS X noob so I'm afraid it's unclear to me how I
would do that.

Feel free to close this and we'll assume that the GNU tools are the cause.
It seems a strange error though and I presume that we'd quite like this to
work even with those tools enabled.

If anyone else has the same problem then at least they may find their way
here via Google.

**Comment by jacknagel** [comment]
Testing without them is as simple as running `brew unlink` on those formulae.

Running the GNU tools with tools with unprefixed executables is an "at your own risk" thing, for reasons like this.

**Comment by joelittlejohn** [comment]
Did a bit more digging and finally found the problem. I had `export PERL_UNICODE="S"` in my .bash_profile. Un-setting this env var fixed the problem.
