### ISSUE TITLE
go.rb: tools package should be in base install

### ISSUE THREAD

**Issue by ringods** [Homebrew/homebrew#36475]
Hello,

I configured my Homebrew setup to install tools using an admin account, and use all the tools from a non-admin account.

Running ``go get golang.org/x/tools/cmd/vet`` using the non-admin account fails writing to the ``GOTOOLDIR``:

```
ringods$ go get -u golang.org/x/tools/cmd/vet
go install golang.org/x/tools/cmd/vet: open /usr/local/Cellar/go/1.4.1/libexec/pkg/tool/darwin_amd64/vet: permission denied
```

After asking help on the #go-nuts IRC channel, I got the answer that the tools package should be part of the base install:

```
<Tv`> ringods: the tools are kinda considered as part of the actual go install, just run that as the admin
<ringods> Tv`: shouldn't these be part of the base install then?
<Tv`> ringods: the tools *should* be part of any packaged Go binary distribution; complain to your distribution maker
```

Could this be added to the ``go.rb`` file and/or bottle?

**Comment by ringods** [comment]
Also on other platforms, ``vet`` seems to be part of the base Go installation:

https://github.com/hashicorp/terraform/pull/910

**Comment by mikemcquaid** [comment]
> Could this be added to the go.rb file and/or bottle?

Seems sensible. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by ringods** [comment]
If I had the knowledge of Homebrew packaging, I would do it. Unfortunately...

**Comment by jacknagel** [comment]
We will happily review a pull request, the instructions Mike linked to should get you started if you're interested.
