### ISSUE TITLE
Empty brewery has inconsistent "brew list" behaviour

### ISSUE THREAD

**Issue by bildzeitung** [Homebrew/homebrew#36484]
After a fresh install of brew, running `brew list <x>` has an exit code of 0.

However, after installing any brew, running a `brew list <x>` (for `<x>` that isn't installed) has an exit code of 1.

Ideally, if there are no brews installed, the return value for `brew list <X>` should be 1 in both cases, since in both cases the brew isn't installed.

[edit: fixed formatting of angle brackets -jn]

**Comment by mikemcquaid** [comment]
Sorry, I'm not sure on the command you're running here to get an exit code of 1?

**Comment by bildzeitung** [comment]
Awesome! Thank you!
