### ISSUE TITLE
rocket formula out of date

### ISSUE THREAD

**Issue by jzelinskie** [Homebrew/homebrew#36490]
The latest version of rkt is [0.2.0](https://github.com/coreos/rocket/releases/tag/v0.2.0) whereas 0.1.0 is in the homebrew library. As this is pre-release software, it is going to be updated every few months.

If you could point me to the correct docs, I wouldn't mind trying to keep it up to date. However, I have no idea how to update a formula with precompiled bottles.

**Comment by mikemcquaid** [comment]
This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Updating the bottles we'll just do when we pull your changes.

Thanks!

**Comment by asparagui** [comment]
The bottle will be taken care of by BrewTestBot, so don't worry about it.  Here is the rest of the process:

    https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Good luck!
