### ISSUE TITLE
open-scene-graph (OSG) failed to build on 10.10.1

### ISSUE THREAD

**Issue by Zeitsperre** [Homebrew/homebrew#36502]
Hey, I recently installed homebrew as I was having difficulties installing all the dependencies for QGIS 2.6.1 manually. A previous owner had installed fink so I uninstalled it in the process. Letting homebrew install the QGIS dependencies was running fine until it tried to do OSG.

> /usr/local/Cellar/cmake/3.1.1_1/bin/cmake -E cmake_progress_report /tmp/open-scene-graph-j7L0Ji/OpenSceneGraph-3.2.0/build/CMakeFiles  57 58 59 60 61 62 63 64 65
[ 69%] Built target osgdb_ive
make: *** [all] Error 2

Lots of errors involving CMake. Ran brew update/doctor and manually removed an NCARG library that wasn't brew-installed and reinstalled NCL. Since then I've been scouring the net. 

Despite this hiccup, love how homebrew works. Would love to know where I've gone wrong (oh and any fixes/workarounds). 

gist-log: https://gist.github.com/32c6511b273db7de3e56

**Comment by asparagui** [comment]
WFM. I would guess you need to uninstall more libraries/frameworks, see also #34260.

**Comment by jacknagel** [comment]
ping.
