### ISSUE TITLE
Homebrew installation failed: fatal: Could not switch to '.git': Permission denied Failed during: git init -q

### ISSUE THREAD

**Issue by teresalin** [Homebrew/homebrew#36504]
Lungs-MacBook-Pro-2:~ LungLin$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/man/man1/brew.1

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
fatal: Could not switch to '.git': Permission denied
Failed during: git init -q

**Comment by mikemcquaid** [comment]
Try running `sudo chown -R $USER /usr/local`

**Comment by thegreatmichael** [comment]
@mikemcquaid thanks for the suggestion. I have been helping @teresalin and unfortunately we have tried that. do you know which `.git` directory it's referring to? what should the groups (as we `ls` around, we see `staff` and `wheel` often) be? does it matter that her username is capitalized?

**Comment by mikemcquaid** [comment]
> @mikemcquaid thanks for the suggestion. I have been helping @teresalin and unfortunately we have tried that. do you know which .git directory it's referring to? what should the groups (as we ls around, we see staff and wheel often) be? does it matter that her username is capitalized?

Most likely `/usr/local/.git`. Capitals and groups shouldn't matter.

**Comment by thegreatmichael** [comment]
frig. all the googling suggests that same fix with either `$USER` or `` `whoami` `` but it was literally the command before the output on the paste above. does it matter what version of ruby she has?

**Comment by mikemcquaid** [comment]
You could try manually running `sudo rm -rf /usr/local/.git; cd /usr/local; git clone https://github.com/Homebrew/homebrew .` which might give you more output.

**Comment by thegreatmichael** [comment]
so that'd be (all on one line):

    sudo rm -rf /usr/local/.git; cd /usr/local; git clone https://github.com/Homebrew/homebrew .

**Comment by jclusso** [comment]
I've got the same problem :(

**Comment by thegreatmichael** [comment]
ok, so she cloned it successfully and `/usr/local/bin` is on her `$PATH`. is it better to `ln` the binary into `/usr/local/bin` or to `cp` it there?

**Comment by mikemcquaid** [comment]
Which binary? You shouldn't need to manually `ln` or `cp` anything.

@jclusso Follow the same steps, thanks!

**Comment by thegreatmichael** [comment]
your suggestion above (https://github.com/Homebrew/homebrew/issues/36504#issuecomment-72719012 ) ended in cloning. this succeeded. now what?

**Comment by mikemcquaid** [comment]
If `/usr/local/bin` is in your PATH then that should be it; you should be able to run `brew` now (I'd suggest starting with `brew update`)

**Comment by thegreatmichael** [comment]
ah! i missed the `.` in the clone cmd (-:

**Comment by thegreatmichael** [comment]
ok, shucks, she gets `fatal: destination path '.' already exists and is not an empty directory.` when including that trialing `.`

**Comment by mikemcquaid** [comment]
Ok, let's try `sudo rm -rf /usr/local/.git; cd /usr/local; git init; git remote add origin https://github.com/Homebrew/homebrew; git fetch; git checkout -fb master origin/master`

**Comment by thegreatmichael** [comment]
is her git maybe installed funny/wrong permissions?

    Lungs-MacBook-Pro-2:local LungLin$ sudo rm -rf /usr/local/.git; cd /usr/local; git init; git remote add origin https://github.com/Homebrew/homebrew; git fetch; git checkout -fb master origin/master
    Password:
    fatal: unable to access '/usr/local/.git/config': Permission denied
    fatal: Not a git repository (or any of the parent directories): .git
    fatal: Not a git repository (or any of the parent directories): .git
    fatal: Not a git repository (or any of the parent directories): .git

**Comment by mikemcquaid** [comment]
I don't understand how you're getting these permission denied errors. You definitely ran the `chown`, yeh? Can you clone a git repository in the home directory?

**Comment by jacknagel** [comment]
What are the permissions on `/usr/local` itself (`ls -ld /usr/local`)?

**Comment by thegreatmichael** [comment]
hmmm

    Lungs-MacBook-Pro-2:local LungLin$ ls -all /usr/local
    total 8
    drwxrwxr-x  12 LungLin  admin  408 Feb  3 17:01 .
    drwxr-xr-x@ 12 root     wheel  408 Oct 22 10:52 ..
    drwxr-xr-x  11 LungLin  admin  374 Feb  3 17:01 .git
    drwxrwxr-x   3 LungLin  admin  102 Feb  3 11:52 Library
    drwxrwxr-x   6 LungLin  admin  204 Oct 22 02:31 MacGPG2
    drwxrwxr-x   4 LungLin  admin  136 Feb  3 11:52 bin
    drwxrwxr-x   3 LungLin  admin  102 Feb  3 11:22 include
    drwxrwxr-x   6 LungLin  admin  204 Feb  3 11:31 lib
    drwxrwxr-x   3 LungLin  admin  102 Oct 22 02:32 man
    lrwxr-xr-x   1 LungLin  admin   27 Sep 16 09:08 mysql -> mysql-5.6.20-osx10.8-x86_64
    drwxrwxr-x  17 LungLin  admin  578 Oct 22 02:33 mysql-5.6.20-osx10.8-x86_64
    drwxrwxr-x   4 LungLin  admin  136 Oct 22 02:32 share`

    teresal [6:14 PM]
    Lungs-MacBook-Pro-2:local LungLin$ ls -ld /usr/local
    drwxrwxr-x  12 LungLin  admin  408 Feb  3 17:01 /usr/local

**Comment by DomT4** [comment]
Any issues remaining here?

**Comment by joekwong7** [comment]
thanks for the help. fixed my install.
