### ISSUE TITLE
Unable to install Boost Version 1.55 or earlier

### ISSUE THREAD

**Issue by katerakelly** [Homebrew/homebrew#36512]
in $(brew --prefix)....

brew versions boost  
git checkout a252214 Library/Formula/boost.rb
brew install boost

==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.55.0/boost_1_55_0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/boost-1.55.0.tar.bz2
Error: SHA1 mismatch
Expected: cef9a0cc7084b1d639e06cd3bc34e4251524c840
Actual: 0dc9f0db453453fb6b6b5b396f217f4cc086d4cd
Archive: /Library/Caches/Homebrew/boost-1.55.0.tar.bz2
To retry an incomplete download, remove the file above.

=============================================
I have tried: brew update, brew doctor, brew cleanup.
When I manually download the boost1.55 tar file from SourceForge (link: https://downloads.sourceforge.net/project/boost/boost/1.55.0/boost_1_55_0.tar.bz2) and de-tar it, I get a warning that the tar is corrupted.  When I run bzip2 -tvv boost-1.55.0.tar.bz2 to find out how, it says one of the files ends unexpectedly.
What's going on here?

**Comment by jacknagel** [comment]
Sorry, but we don't support formulae that are checked out from the history, because it's not possible to apply fixes.
