### ISSUE TITLE
htop not resizing properly

### ISSUE THREAD

**Issue by mohamedakhalik** [Homebrew/homebrew#36517]
htop doesn't seem to be resizing according to the window size.

Thanks.
![screen shot 2015-02-04 at 12 38 31 am](https://cloud.githubusercontent.com/assets/7555175/6032854/2ce4a6d2-ac06-11e4-80c1-beb37fd62322.png)

**Comment by jacknagel** [comment]
Report it to https://github.com/max-horvath/htop-osx please.
