### ISSUE TITLE
mpv failed to build on 10.9.5 - python waf error

### ISSUE THREAD

**Issue by drogers141** [Homebrew/homebrew#36515]
gist of the logs created with:
$ brew gist-logs mpv
is:
https://gist.github.com/deb2c248fe48447e420e

Trying to upgrade my existing mpv installation, I first did
$ brew rm mpv
Then tried to install with:
$ brew install --HEAD --with-bundle --with-bluray-support --with-libdvdread --with-libquvi --with-little-cms2 --with-lua --with-official-libass --with-libdvdnav --with-libaacs --with-libmpv    mpv

This failed while trying to configure waf:
**************
==> python waf configure --prefix=/usr/local/Cellar/mpv/HEAD --enable-libmpv-shared --disable-client-api-example

  standalone app:
    --disable-apple-remote
                        disable Apple Remote support [autodetect]
waf: error: no such option: --disable-client-api-examples
**************
Looking at the formula for mpv I see that the offending option is only included in the args if --with-libmpv is specified.  Since I can live without it, I am just going to try that for now.

Let me know if I can be of other help - thanks..

Dave Rogers

**Comment by drogers141** [comment]
Sorry - just looking at this - note that the output of the error message copied from the console is:
==> python waf configure --prefix=/usr/local/Cellar/mpv/HEAD --enable-libmpv-shared --disable-client-api-example
which has --disable-client-api-example instead of --disable-client-api-examples
but this appears only to be an artifact of the command line output.
The error itself has the plural form:
waf: error: no such option: --disable-client-api-examples

Just making sure that you don't think this is the source of the error..

**Comment by jacknagel** [comment]
Please report this to https://github.com/mpv-player/homebrew-mpv
