### ISSUE TITLE
Empty installation error when installing a dependency

### ISSUE THREAD

**Issue by kwkelly** [Homebrew/homebrew#36536]
I'm creating a new formula for [pdfsandwich](http://www.tobias-elze.de/pdfsandwich/) which depends on the development version of tesseract. I can install tesseract with `brew install --verbose tesseract --devel` and it [works fine](http://pastebin.com/GzfgM43d). However, when I try to use the [formula I'm creating](http://pastebin.com/KqW7esKC) by invoking `brew install --verbose pdfsandwich` I get [Error: Empty installation](http://pastebin.com/PP9DUBw4) at the very end of installing the dependency tesseract.

[`brew doctor` output](http://pastebin.com/kvjYeXua) (the unlinked tesseract is from the recent failed install as a dependency)

[`brew config` output](http://pastebin.com/GjLh0XaE)

**Comment by jacknagel** [comment]
Your error is here:

```rb
depends_on "tesseract" => "devel"
```

Passing `--devel` to a dependency isn't supported (yet), and is causing the problem. It will be supported in the future, but the implementation isn't ready yet.
