### ISSUE TITLE
Always build with --without-x11

### ISSUE THREAD

**Issue by MisterTea** [Homebrew/homebrew#36542]
Hey all,

I recently switched from macports to homebrew.  I hate the xquartz experience on OS/X with a passion.  Can I set some environment variable / file so that every brew I install is --without-x11?  This way I don't have to worry about forgetting to put it when I am installing something.

**Comment by jacknagel** [comment]
No, there isn't a mechanism for setting global flags, sorry.

>This way I don't have to worry about forgetting to put it when I am installing something.

Homebrew doesn't install XQuartz for you (install will error out if it's required but not installed), so it won't be accidentally installed.

**Comment by MisterTea** [comment]
@jacknagel The problem isn't installing xquartz by accident.  The problem is this:

```
brew install gtksourceview3 --without-x11
```

This still installs cairo, gtk, etc.  with x11.  I have to explicitly enumerate all of the dependencies and list them on the command line to ensure that they are built without x11:
```
brew install gtksourceview3 gtk3 cairo ..... --without-x11
```

**Comment by mikemcquaid** [comment]
@jacknagel I'd probably advise you to not use `gtk`/`gtk3` applications. I also hate XQuartz and my longer-term plan is to move everything that uses it as `:recommended` into the [homebrew-x11 tap](https://github.com/Homebrew/homebrew-x11) (like I already did with hard dependencies).

**Comment by MisterTea** [comment]
@mikemcquaid I don't agree with this statement for gtk3. Gtk3 has native support for Quartz and there are some very useful applications that work fine with gtk3 + Quartz (Meld, Inkscape, synfigstudio, Wireshark). If homebrew didn't keep trying to install dependencies without the --without-X11 flag, this wouldn't be a problem. Also, there is another bug where py2cairo uses a bottle even when Cairo is built from source using --without-X11, then py2cairo can't find the Cairo x11 libs. These issues are worth fixing to be able to use gtk3 applications in os/x.

**Comment by mikemcquaid** [comment]
> @mikemcquaid I don't agree with this statement for gtk3. Gtk3 has native support for Quartz and there are some very useful applications that work fine with gtk3 + Quartz (Meld, Inkscape, synfigstudio, Wireshark). If homebrew didn't keep trying to install dependencies without the --without-X11 flag, this wouldn't be a problem. Also, there is another bug where py2cairo uses a bottle even when Cairo is built from source using --without-X11, then py2cairo can't find the Cairo x11 libs. These issues are worth fixing to be able to use gtk3 applications in os/x.

I'm open to moving stuff that depends on GTK+3 to be `--without-x11` by default.

**Comment by MisterTea** [comment]
@mikemcquaid Can we re-open this issue with the intention of making --without-x11 the default?  Is there a way to do this without changing every brew that depends/builds gtk3?

**Comment by MisterTea** [comment]
Please look at https://github.com/Homebrew/homebrew/pull/36566 which addresses part of this issue.

**Comment by jacknagel** [comment]
>Can we re-open this issue with the intention of making --without-x11 the default? Is there a way to do this without changing every brew that depends/builds gtk3?

Each time someone asks this, I outline what I believe are very reasonable minimum requirements for making this change across Homebrew. It is summarized here: https://github.com/Homebrew/homebrew/pull/29691#issuecomment-44762142

I think managing X11 and non-X11 variants of gtk and its dependencies in the same set of formulae is a bad idea. I would much rather see work done externally on quartz versions, and then eventually merge that into core and move the x11 variants out into the X11 tap as gtk+-x11, etc.

I don't think that's unreasonable.
