### ISSUE TITLE
protobuf.rb:119: syntax error, unexpected end-of-input, expecting keyword_end

### ISSUE THREAD

**Issue by nirupama** [Homebrew/homebrew#36543]
/usr/local/Library/Formula/protobuf.rb:119: syntax error, unexpected end-of-input, expecting keyword_end

occurs when trying to run brew doctor 
Error: /usr/local/Library/Formula/protobuf.rb:119: syntax error, unexpected end-of-input, expecting keyword_end: 
This occurs on OS 10.10

Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/formula.rb:495:in `block in each'
/usr/local/Library/Homebrew/formula.rb:493:in `each'
/usr/local/Library/Homebrew/formula.rb:493:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:931:in `check_for_linked_keg_only_brews'
/usr/local/Library/Homebrew/cmd/doctor.rb:1256:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1254:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1254:in `doctor'
/usr/local/Library/brew.rb:135:in `<main>'

**Comment by tdsmith** [comment]
If you haven't made any changes to any formulas that you want to keep, you can reset your formulas by running `cd /usr/local && git reset --hard origin/master`.

**Comment by jacknagel** [comment]
Assuming fixed.
