### ISSUE TITLE
Error: No available formula for numpy

### ISSUE THREAD

**Issue by suzumakes** [Homebrew/homebrew#36556]
brew doctor -> Error: No available formula for numpy

Forgive me for not knowing how everything works and just being glad it all does work, but I got this error this morning.

gist-logs give the same error. Is numpy gone?

**Comment by DomT4** [comment]
` numpy ` currently resides in ` homebrew/python/numpy `. You can access it by doing ` brew tap homebrew/python ` and then ` brew install numpy `.

**Comment by suzumakes** [comment]
Thanks, perfect.

**Comment by tdsmith** [comment]
(FWIW, though, `pip install numpy` works great on OS X now!)
