### ISSUE TITLE
brew search devhelp erroneously returns the brew help overview

### ISSUE THREAD

**Issue by moreaki** [Homebrew/homebrew#36559]
Almost any brew command followed by the package name containing the string "help" erroneously returns the brew help overview. I haven't dug into the code, however I imagine that this is easy to fix. I hit this nuisance trying to first search for Gnome's devhelp package (https://download.gnome.org/sources/devhelp/3.14/) and then subsequently trying to build a package for it.

Example:

```bash
$ brew search devhelp
Example usage:
  brew [info | home | options ] [FORMULA...]
  brew install FORMULA...
  brew uninstall FORMULA...
  brew search [foo]
  brew list [FORMULA...]
  brew update
  brew upgrade [FORMULA...]
  brew pin/unpin [FORMULA...]

Troubleshooting:
  brew doctor
  brew install -vd FORMULA
  brew [--env | config]

Brewing:
  brew create [URL [--no-fetch]]
  brew edit [FORMULA...]
  open https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md

Further help:
  man brew
  brew home
```

Quoting also does not help.

**Comment by DomT4** [comment]
Heh. Yeah, seems to affect everything. ` brew updatehelp `, ` brew doctorhelp `, ` brew audithelp `, ` brew install opensslhelp `. All trigger help.

**Comment by moreaki** [comment]
Just had a quick look at it, and my approach to fixing it would be the following:

```diff
diff --git a/Library/brew.rb b/Library/brew.rb
index 8438533..4235807 100755
--- a/Library/brew.rb
+++ b/Library/brew.rb
@@ -82,7 +82,7 @@ begin
              }

   empty_argv = ARGV.empty?
-  help_regex = /(-h$|--help$|--usage$|-\?$|help$)/
+  help_regex = /(-h$|--help$|--usage$|-\?$|^help$)/
   help_flag = false
   cmd = nil
```
