### ISSUE TITLE
mailutils failed to build on 10.10.2

### ISSUE THREAD

**Issue by MattSherwood** [Homebrew/homebrew#36564]
Hi All,

Here is a link to the gist report for my build failure of mailutils.

https://gist.github.com/anonymous/d3b887d118a21dc3bfd5

I do a lot of development work on this MacBook Pro, so it isn't always easy to conform with all of Brew Doctor's suggestions.  If any of those are critical to the success of this build, then I'l try to resolve them.

Cheers,
Matt

**Comment by DomT4** [comment]
Looking at the failures, updating your Xcode could be a good bet.

**Comment by MattSherwood** [comment]
Yes, that did the trick. Thanks for the assist.
