### ISSUE TITLE
plplot failed to build on 10.10.2

### ISSUE THREAD

**Issue by jhcsu** [Homebrew/homebrew#36569]
plplot fails to build on 10.10.... here is the [Gist](https://gist.github.com/anonymous/18cb90dff62ab2525619).

I see several errors related to ada and the d compiler, but those features are apparently disabled as a result of those errors.

**Comment by DomT4** [comment]
Failure is reproducible here as well. Same reason.

**Comment by asparagui** [comment]
+1 as well, weird.  Report upstream?

**Comment by mankoff** [comment]
plplot development seems to have stopped. There are important fixes performed after the last release (5.10). It would be nice to see plplot head be accessible via brew, so that software that depends on those post-release fixes can be built (gdl).

**Comment by joshwalawender** [comment]
I also get this.  Here's my [gist](https://gist.github.com/joshwalawender/513768552ba08c52f2e4).  Looks similar to the gist linked above.

**Comment by sirpercival** [comment]
Same problem...

**Comment by XhrisPhillips** [comment]
For what its worth, it also fails to compile on osx 10.9.5

**Comment by XhrisPhillips** [comment]
OK While not directly helpful for those trying to use the brew version, I have now got the 5.10.0 version of plplot working downloaded directly The problems I had seem very similar to above.

First I edited cmake/modules/pkg-config.cmake and changed

  `_pkg_check_modules_internal(0 0 ${_prefix} "${_package}")`

to

  `_pkg_check_modules_internal(0 0 0 0 ${_prefix} "${_package}")`

See

http://sourceforge.net/p/plplot/plplot/ci/772223c638ecf5dc740c9f3dd7a6883c6d2c83d2/


I then ran cmake as  (I compiled from a subdir called build after unpacking plplot)

  `cmake .. -DENABLE_ada=OFF`

cmake did not find pango even though it is installed. This does not seem to matter for what I am doing so I have ignored that problem

**Comment by XhrisPhillips** [comment]
Actually a better fix would have been (pinched from the plplot git)

    -  _pkg_check_modules_internal(0 0 ${_prefix} "${_package}")
    +  if(CMAKE_VERSION VERSION_LESS "3.1")
    +    _pkg_check_modules_internal(0 0 ${_prefix} "${_package}")
    +  else(CMAKE_VERSION VERSION_LESS "3.1")
    +    _pkg_check_modules_internal(0 0 0 0 ${_prefix} "${_package}")
    +  endif(CMAKE_VERSION VERSION_LESS "3.1")
    +

**Comment by tschoonj** [comment]
I have submitted a pull request that should fix this #37398

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by mankoff** [comment]
plplot just released a new version, 5.11.0, which may impact this (closed) issue: http://sourceforge.net/p/plplot/news/2015/04/plplot-5110-has-been-released/
