### ISSUE TITLE
brew install rsync fails on 10.10.2 fresh brew install

### ISSUE THREAD

**Issue by scubachristopher** [Homebrew/homebrew#36565]
New Mac.  10.10.2.  Fresh brew install. 

Daras-iMac:~ scubachristopher$ brew gist-logs 
usage: brew gist-logs [--new-issue|-n] <formula>
Daras-iMac:~ scubachristopher$ brew update
Already up-to-date.
Daras-iMac:~ scubachristopher$ brew tap homebrew/dupes
Warning: Already tapped!
Daras-iMac:~ scubachristopher$ brew update
Already up-to-date.
Daras-iMac:~ scubachristopher$ brew -v install rsync
Homebrew 0.9.5
==> Installing rsync from homebrew/homebrew-dupes
==> Downloading https://rsync.samba.org/ftp/rsync/rsync-3.1.1.tar.gz
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-481; Mac OS X 10.10.2) https://rsync.samba.org/ftp/rsync/rsync-3.1.1.tar.gz -C 0 -o /Library/Caches/Homebrew/rsync-3.1.1.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to rsync.samba.org port 443: Connection refused
Error: Failed to download resource "rsync"
Download failed: https://rsync.samba.org/ftp/rsync/rsync-3.1.1.tar.gz
Daras-iMac:~ scubachristopher$ uname -a
Darwin Daras-iMac 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64

Is Samba.org down or is this end point wrong?

**Comment by chdiza** [comment]
It appears to be down.

**Comment by jacknagel** [comment]
It's down.

Issues about this formula should be filed at https://github.com/Homebrew/homebrew-dupes
