### ISSUE TITLE
boost_1_57_0 SHA1 mismatch

### ISSUE THREAD

**Issue by joeheald85** [Homebrew/homebrew#36599]
When installing postgis, a dependency, boost fails, even after a brew update.

$ brew install postgis --with-gui
==> Installing dependencies for postgis: boost, gmp, mpfr, cgal, sfcgal
==> Installing postgis dependency: boost
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/boost-1.57.0.mountain_lion.bottle.tar.gz
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: 4ba6d875fe24548b8af3c0b6631ded562d2da40f
Actual: a206d4ed749173e015dd5343e95cb66cf2128b93
Archive: /Library/Caches/Homebrew/boost-1.57.0.mountain_lion.bottle.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.57.0/boost_1_57_0.tar.bz2
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: e151557ae47afd1b43dc3fac46f8b04a8fe51c12
Actual: 81346020f72fd26eb2249d4ee77cbcbd1759b4f4
Archive: /Library/Caches/Homebrew/boost-1.57.0.tar.bz2
To retry an incomplete download, remove the file above.

**Comment by DomT4** [comment]
SF might be having problems again, but just in case, it'll help the maintainers if you can provide a ` brew doctor ` readout.

**Comment by joeheald85** [comment]
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: A newer Command Line Tools release is available.
The standalone package can be obtained from
  https://developer.apple.com/downloads
or it can be installed via Xcode's preferences.

Warning: Your XQuartz (2.7.4) is outdated
Please install XQuartz 2.7.7:
  https://xquartz.macosforge.org

**Comment by iggyvolz** [comment]
I'm getting the correct shasum on my machine.  It may have been just a temporary network error - you may want to try again and see if it works now.

**Comment by joeheald85** [comment]
Thanks guys! Tried again, and it works. We have been experiencing packet loss recently at the office, which could have been the culprit.

**Comment by DomT4** [comment]
Great! :smiley_cat:. Always a relief when it's nothing too serious.

**Comment by aksharbonu** [comment]
Having this issue right now...

==> Installing boost-python dependency: boost
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/boost-1.57.
Already downloaded: /Library/Caches/Homebrew/boost-1.57.0.yosemite.bottle.tar.gz
Error: SHA1 mismatch
Expected: 5eaa834239277ba3fabdf0f6664400e4e2ff29b4
Actual: a2fd3379ea944f6b2f97fb0f79b7b85cb3e14d0b
Archive: /Library/Caches/Homebrew/boost-1.57.0.yosemite.bottle.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.57.0/boo
Already downloaded: /Library/Caches/Homebrew/boost-1.57.0.tar.bz2
Error: SHA1 mismatch
Expected: e151557ae47afd1b43dc3fac46f8b04a8fe51c12
Actual: a2fd3379ea944f6b2f97fb0f79b7b85cb3e14d0b
Archive: /Library/Caches/Homebrew/boost-1.57.0.tar.bz2
To retry an incomplete download, remove the file above

**Comment by DomT4** [comment]
Sourceforge is down again. Either pass ` --build-from-source ` to your build, such as ` brew install python --build-from-source ` or wait a few hours for SF to recover from the issues on their end.

**Comment by aksharbonu** [comment]
No luck... 

brew install rdkit --build-from-source
==> Installing rdkit from rdkit/homebrew-rdkit
==> Installing dependencies for rdkit: boost, boost-python
==> Installing rdkit dependency: boost
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.57.0/boo
Already downloaded: /Library/Caches/Homebrew/boost-1.57.0.tar.bz2
Error: SHA1 mismatch
Expected: e151557ae47afd1b43dc3fac46f8b04a8fe51c12
Actual: a2fd3379ea944f6b2f97fb0f79b7b85cb3e14d0b
Archive: /Library/Caches/Homebrew/boost-1.57.0.tar.bz2
To retry an incomplete download, remove the file above.

**Comment by DomT4** [comment]
Heh. Same issue - Looks like Boost host on Sourceforge as well. Afraid you'll have to wait for SF to recover :cry:.
