### ISSUE TITLE
deprecated_option Error with brew install go

### ISSUE THREAD

**Issue by ftabarie** [Homebrew/homebrew#36597]
brew install go
Error: undefined method `deprecated_option' for Go:Class
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/nfs/zfs-student-2/users/2013/ftabarie/.brew/Library/Formula/go.rb:22
/usr/local/Library/Homebrew/formulary.rb:65:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:192:in `factory'
/usr/local/Library/Homebrew/formula.rb:397:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:12:in `formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:12:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:12:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:105:in `send'
/usr/local/Library/brew.rb:105

/////////////////////////

brew doctor
Error: undefined method `deprecated_option' for Findutils:Class
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/nfs/zfs-student-2/users/2013/ftabarie/.brew/Library/Formula/findutils.rb:16
/usr/local/Library/Homebrew/formulary.rb:65:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:192:in `factory'
/usr/local/Library/Homebrew/formula.rb:397:in `factory'
/usr/local/Library/Homebrew/tab.rb:50:in `for_name'
/usr/local/Library/Homebrew/cmd/doctor.rb:1003:in `check_for_non_prefixed_findutils'
/usr/local/Library/Homebrew/cmd/doctor.rb:1130:in `send'
/usr/local/Library/Homebrew/cmd/doctor.rb:1130:in `doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1129:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1129:in `doctor'
/usr/local/Library/brew.rb:105:in `send'
/usr/local/Library/brew.rb:105

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem. Particularly running `brew update` will probably fix this.

Thanks!

**Comment by ftabarie** [comment]
I'm sorry but I dont get it for <formula name>
Error: Unknown command: gist-logs

///////////

brew update
Already up-to-date.

**Comment by DomT4** [comment]
It looks like you have two Homebrew's on the system?

` /nfs/zfs-student-2/users/2013/ftabarie/.brew/Library/Formula/go.rb:22 `

` /usr/local/Library/Homebrew/formulary.rb:65:inrequire' `.

**Comment by ftabarie** [comment]
the first one (/nfs/zfs-student-2/users/2013/ftabarie/.brew) is just the app folder

**Comment by ftabarie** [comment]
http://s12.postimg.org/m39r3nil9/Screen_Shot_2015_02_06_at_16_48_46.png

**Comment by mikemcquaid** [comment]
What do you mean "just the app folder"? Your problem is having two installs of Homebrew that are interfering with each other.

**Comment by ftabarie** [comment]
I made a screenshot to gives you more inf
when i delete this folder and i make a brew update, it creates a new .brew on my ftabarie folder. that's all.

**Comment by mikemcquaid** [comment]
I think you may need to speak to your university and ask how you are meant to use Homebrew with their setup.
