### ISSUE TITLE
gtypist fails to build on 10.10.2

### ISSUE THREAD

**Issue by rafiks** [Homebrew/homebrew#36590]
install exits with missing libncursesw

**Comment by rafiks** [comment]
https://gist.github.com/7f7e1f2138c0edb11a8f

**Comment by jacknagel** [comment]
It's almost certainly caused by the ncurses headers and libraries you have installed in /usr/local.

**Comment by rafiks** [comment]
ok will test it again.

thanks .

**Comment by rafiks** [comment]
it worked!
