### ISSUE TITLE
error in installing hadoop

### ISSUE THREAD

**Issue by prakashn27** [Homebrew/homebrew#36607]
brew install hadoop               [ruby-2.0.0p481]
==> Downloading http://www.apache.org/dyn/closer.cgi?path=hadoop/common/hadoop-2
==> Best Mirror http://mirror.nexcess.net/apache/hadoop/common/hadoop-2.5.1/hado

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "hadoop"
Download failed: http://mirror.nexcess.net/apache/hadoop/common/hadoop-2.5.1/hadoop-2.5.1.tar.gz

**Comment by adamv** [comment]
The formula should be updated to 2.5.2.

**Comment by adamv** [comment]
Oh; it's already updated to 2.6.0; you'll want to `brew update`.

**Comment by jacknagel** [comment]
Closing per the above.

**Comment by prakashn27** [comment]
thanks a lot it worked. 
I got Hadoop 2.6.0. by any chance can you let me know how to install hadoop 2.5.1
