### ISSUE TITLE
postgres failed to build on 10.10.2

### ISSUE THREAD

**Issue by mountriv99** [Homebrew/homebrew#36613]
Hi, got the following error when trying to install postgres

gist: https://gist.github.com/anonymous/548b4bc239420b3e3aec

brew install postgres
==> Installing postgresql dependency: openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.1g.tar.gz
Already downloaded: /Library/Caches/Homebrew/openssl-1.0.1g.tar.gz
==> perl ./Configure --prefix=/usr/local/Cellar/openssl/1.0.1g --openssldir=/usr
==> make depend
==> make
==> make test
==> make install MANDIR=/usr/local/Cellar/openssl/1.0.1g/share/man MANSUFFIX=ssl
cms.pod around line 465: Expected text after =item, not a number
cms.pod around line 470: Expected text after =item, not a number
cms.pod around line 474: Expected text after =item, not a number
POD document had syntax errors at /usr/bin/pod2man5.18 line 72.
make: *** [install_docs] Error 255

READ THIS: http://git.io/brew-troubleshooting

These open issues may also help:
bip: system openssl linkage fix (https://github.com/Homebrew/homebrew/pull/36531)
openssl: removing sslv3 (https://github.com/Homebrew/homebrew/pull/35060)
Installing Elixir fails due to OpenSSL errors. (https://github.com/Homebrew/homebrew/issues/33218)

**Comment by DomT4** [comment]
Your Homebrew is *way* out of date. Do a ` brew update && brew upgrade ` and then try again.

**Comment by mountriv99** [comment]
My bad.  Yep that fixed it, thanks!
