### ISSUE TITLE
Warning: Setting DYLD

### ISSUE THREAD

**Issue by vjuloux** [Homebrew/homebrew#36624]
Hello !

Mac OS X 10.10.1 Yosemite. I am a beginner in shell. I was before working with MAMP before Yosemite.

I run brew doctor from my shell. I have managed to correct a lot of warning, except one : 
<code sh>Warning: Setting DYLD_* vars can break dynamic linking.
Set variables: 
    DYLD_LIBRARY_PATH: /usr/local/mysql/lib:</code>

In my .bash_profile, I have: 
<code sh>export PATH=~/bin:/usr/local/bin:/usr/local/mysql/bin:$PATH
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib:$DYLD_LIBRARY_PATH</code>

Any idea where is my mistake ?

In advance, thanks,

Vanessa

**Comment by iggyvolz** [comment]
There's no problem at all.  You're setting the DYLD path.  The brew doctor
warnings are only if something goes wrong, it believes those may be a cause.

**Comment by vjuloux** [comment]
Thank you iggyvolz.
