### ISSUE TITLE
brew install causes bash script failure when package is already installed.

### ISSUE THREAD

**Issue by mattdarveniza** [Homebrew/homebrew#36663]
Have been attempting to write some bootstrapping bash scripts that incorporate homebrew, however since brew sends a failure signal when it tries to install a package which is already installed, it causes any bash script to fail.

Currently getting around this by just ignoring any errors brew install might generate, however would be nice if there was some kind of flag/option to stop it from erroring for already installed packages.

**Comment by mikemcquaid** [comment]
`brew list $PACKAGE &>/dev/null || brew install $PACKAGE` should work.

**Comment by jacknagel** [comment]
Closing per the above recommendation (see previous issues about this for rationale).

**Comment by mattdarveniza** [comment]
Yeah I guess that'll work. Sorry I should've checked the previous issues a bit more thoroughly!
