### ISSUE TITLE
fontconfig failed to install and build on 10.10

### ISSUE THREAD

**Issue by Garfeild** [Homebrew/homebrew#36668]
Hello, I was trying to install fontconfig and it failed with following error
> => Downloading https://downloads.sf.net/project/machomebrew/Bottles/fontconfig-2.11.1.yosemite.bottle.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/fontconfig-2.11.1.yosemite.bottle.3.tar.gz
==> Pouring fontconfig-2.11.1.yosemite.bottle.3.tar.gz
Error: No such file or directory - /usr/local/etc/fonts/conf.d/20-unhint-small-vera.conf
Warning: Bottle installation failed: building from source.
==> Downloading http://fontconfig.org/release/fontconfig-2.11.1.tar.bz2
Already downloaded: /Library/Caches/Homebrew/fontconfig-2.11.1.tar.bz2
==> Patching
patching file fc-cache/fc-cache.c
patching file fontconfig/fontconfig.h
patching file src/fccache.c
patching file src/fcdir.c
patching file src/fcfs.c
patching file src/fcint.h
patching file src/fcpat.c
==> ./configure --disable-silent-rules --with-add-fonts=/System/Library/Fonts,/Library/Fonts,~/Library/Fonts --prefix=/usr/local/Cellar/fontconfig/2.11.1 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc
==> make install RUN_FC_CACHE_TEST=false
make[3]: *** [install-configDATA] Error 71
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [install-am] Error 2
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

Output from gist-logs command: https://gist.github.com/anonymous/577371ddea3ebb5f9134

**Comment by mistydemeo** [comment]
Try running `brew prune`, then try installing fontconfig again.

**Comment by Garfeild** [comment]
Thank you, it works!
