### ISSUE TITLE
htop-osx version 0.8.2.3 does not show right column in header

### ISSUE THREAD

**Issue by mattmartini** [Homebrew/homebrew#36694]
After upgrading to htop 0.8.2.3 (from 0.8.2.2) the right column in the header no longer shows up in the header.  This happens in both xterm, terminator (X11), and iTerm2.  

I think the problem is that htop is not calculating the width of the window properly and makes the left column expand to the full width of the window.  If you expand the size of the xterm after htop is running to double the original size the right header column becomes visible.  

Reverting back to 0.8.2.2 makes htop behave properly.

**Comment by tdsmith** [comment]
ping @max-horvath; is there an issue tracker or a mailing list?

**Comment by max-horvath** [comment]
Of course, here at GitHub: https://github.com/max-horvath/htop-osx

**Comment by tdsmith** [comment]
@mattmartini, can you report your issue there, please? Thanks, all!

**Comment by mattmartini** [comment]
Just did
