### ISSUE TITLE
Downgrade libevent?

### ISSUE THREAD

**Issue by craigcarnell** [Homebrew/homebrew#36698]
I'm trying to compile hhvm, I have libevent 2 (latest) installed by brew. But it requires 1.4.3+

See comment below:

We require libevent 1.4.x; libevent2 is not compatible.

https://github.com/facebook/hhvm/issues/4028

**Comment by mikemcquaid** [comment]
I'd suggest adding it to `homebrew-versions` and using that instead.

**Comment by craigcarnell** [comment]
@mikemcquaid Makes sense, however when I download the source to libevent 1.4.14b, it seems to create dylibs with version 1.4.2, which is rather odd?

**Comment by mikemcquaid** [comment]
No idea there, I'm afraid. Closing this out.
