### ISSUE TITLE
Installing CoffeeScript - Error on Macbook Pro 10.10.2: No available formula for coffee-script Searching formulae... Searching taps...

### ISSUE THREAD

**Issue by Feroniba** [Homebrew/homebrew#36705]
Hello, 
I'm trying to install CoffeeScript on my MacBook Pro 10.10.2 - did already the following:
• Went to http://brew.sh/
• Copied: 
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
• Pasted code to Terminal
• Installed and opened Xcode because Terminal was asking to do so
• Pasted code again to Terminal - worked fine
• Update as recommended via Terminal: brew update - answers: Already up-to-date.
• Command to Terminal: brew install coffee-script
• Error: No available formula for coffee-script
Searching formulae...
Searching taps...
• Read Troubleshooting page
https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme
Says: Fixing build issues is easier than you think: try brew edit $FORMULA and see how you fare.
• Did it - to Terminal: brew edit $FORMULA - Terminal writes:
F...-MacBook-Pro:~ Feroniba$ brew edit $FORMULA
Warning: Using vim because no editor was set in the environment.
This may change in the future, so we recommend setting EDITOR, VISUAL,
or HOMEBREW_EDITOR to your preferred text editor.
Warning: Using vim because no editor was set in the environment.
This may change in the future, so we recommend setting EDITOR, VISUAL,
or HOMEBREW_EDITOR to your preferred text editor.

" ===============================================================
" Netrw Directory Listing
" /usr/local
" Sorted by name
" Sort sequence: [\/]$,\,\.h$,\.c$,\.cpp$,*
" Quick Help: :help -:go up dir D:delete R:rename s:sor
" ===============================================================
../
.git/
Library/
bin/
share/
.gitignore
.yardopts
CODEOFCONDUCT.md
CONTRIBUTING.md
LICENSE.txt
README.md
SUPPORTERS.md
~
~
~
~
"/usr/local" is a directory
• Try Terminal: brew doctor - Terminal writes:
Your system is ready to brew.
• Try Terminal: brew gist-logs <formula name> - Terminal:
-bash: syntax error near unexpected token `newline'
• Open Xcode app again - try again: brew install coffee-script - again same Error message:
Error: No available formula for coffee-script
Searching formulae...
Searching taps...

Can someone help?

Thanx :-))
Feroniba

**Comment by tdsmith** [comment]
Homebrew doesn't package coffeescript but you can use Homebrew to install node and npm, which does.

Try:
```
brew install node
npm install -g coffee-script
```

Let us know if you have any more questions!

**Comment by Feroniba** [comment]
Thank you for your quick answer, tdsmith.

Did following:

brew install node

Terminal:
==> Installing node dependency: icu4c
==> Downloading https://downloads.sf.net/project/machomebrew

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "icu4c"
Download failed: https://downloads.sf.net/project/machomebrew/Bottles/icu4c-54.1.yosemite.bottle.1.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading http://download.icu-project.org/files/icu4c/
Already downloaded: /Library/Caches/Homebrew/icu4c-54.1.tgz
Error: SHA1 mismatch
Expected: 8c752490bbf31cea26e20246430cee67d48abe34
Actual: a2fd3379ea944f6b2f97fb0f79b7b85cb3e14d0b
Archive: /Library/Caches/Homebrew/icu4c-54.1.tgz
To retry an incomplete download, remove the file above.

Tried then: npm install -g coffee-script

Terminal:
-bash: npm: command not found

What to do now?

**Comment by Feroniba** [comment]
Thank you for your quick answer, tdsmith.

Did following:

brew install node

Terminal:
==> Installing node dependency: icu4c
==> Downloading https://downloads.sf.net/project/machomebrew

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "icu4c"
Download failed: https://downloads.sf.net/project/machomebrew/Bottles/icu4c-54.1.yosemite.bottle.1.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading http://download.icu-project.org/files/icu4c/
Already downloaded: /Library/Caches/Homebrew/icu4c-54.1.tgz
Error: SHA1 mismatch
Expected: 8c752490bbf31cea26e20246430cee67d48abe34
Actual: a2fd3379ea944f6b2f97fb0f79b7b85cb3e14d0b
Archive: /Library/Caches/Homebrew/icu4c-54.1.tgz
To retry an incomplete download, remove the file above.

Tried then: npm install -g coffee-script

Terminal:
-bash: npm: command not found

What to do now?

**Comment by mistydemeo** [comment]
Sourceforge (which is where the prebuilt binaries are stored) is currently down - try again in a few hours. Sorry for the inconvenience!

**Comment by Feroniba** [comment]
Thank you mistydemeo - will do that :-)
