### ISSUE TITLE
libpng 502 bad gateway

### ISSUE THREAD

**Issue by kxxoling** [Homebrew/homebrew#36702]
I'm using brew to install PlantUML which depends on libpng, and got 502 erorr.

I tried manually downloading the link given: https://downloads.sourceforge.net/project/machomebrew/Bottles/libpng-1.6.16.yosemite.bottle.tar.gz but also get 502.

I think there's some problem with sf.net or because of Chinese special network status, but I'm not sure.
But this one could be OK : http://downloads.sourceforge.net/project/machomebrew/Bottles/libpng-1.6.16.yosemite.bottle.tar.gz

**Comment by nbibler** [comment]
See Homebrew/homebrew#36703.

**Comment by kxxoling** [comment]
@nbibler Got it!
