### ISSUE TITLE
<0.9.5> unexcepteds(?) when installing on Mac 10.9.5

### ISSUE THREAD

**Issue by Ben4a** [Homebrew/homebrew#36714]
I don't know what happened. I'mnot 100% what I'm actually doing....

Warning: You have leftover files from an older version of Xcode.
You should delete them using:
  /Developer/Library/uninstall-developer-folder

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libical.0.0.0.dylib
    /usr/local/lib/libicalss.0.0.0.dylib
    /usr/local/lib/libicalvcal.0.0.0.dylib
    /usr/local/lib/libltdl.3.1.0.dylib
    /usr/local/lib/libmad.0.2.1.dylib
    /usr/local/lib/libmad.0.dylib
    /usr/local/lib/libMonoPosixHelper.dylib
    /usr/local/lib/libogg.0.5.0.dylib
    /usr/local/lib/libogg.0.dylib
    /usr/local/lib/libSFFileMonitor.32.dylib
    /usr/local/lib/libSFIPC.32.dylib
    /usr/local/lib/libSFIPC.I.dylib
    /usr/local/lib/libSFsqlite3.7.4.dylib
    /usr/local/lib/libSFSyncEngine.I.dylib
    /usr/local/lib/libvorbis.0.3.0.dylib
    /usr/local/lib/libvorbis.0.dylib
    /usr/local/lib/libvorbisenc.2.0.0.dylib
    /usr/local/lib/libvorbisfile.3.1.0.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/mad.h
    /usr/local/include/ogg/config_types.h
    /usr/local/include/ogg/ogg.h
    /usr/local/include/ogg/os_types.h
    /usr/local/include/vorbis/codec.h
    /usr/local/include/vorbis/vorbisenc.h
    /usr/local/include/vorbis/vorbisfile.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libical.la
    /usr/local/lib/libicalss.la
    /usr/local/lib/libicalvcal.la
    /usr/local/lib/libltdl.la
    /usr/local/lib/libmad.la
    /usr/local/lib/libogg.la
    /usr/local/lib/libvorbis.la
    /usr/local/lib/libvorbisenc.la
    /usr/local/lib/libvorbisfile.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/ogg.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libdevkit.a
    /usr/local/lib/libical.a
    /usr/local/lib/libicalss.a
    /usr/local/lib/libicalvcal.a
    /usr/local/lib/libkld.a
    /usr/local/lib/libltdl.a
    /usr/local/lib/libmad.a
    /usr/local/lib/libogg.a
    /usr/local/lib/libredo_prebinding.a
    /usr/local/lib/libvorbis.a
    /usr/local/lib/libvorbisenc.a
    /usr/local/lib/libvorbisfile.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:

    libtool
Leahs-iMac:~ benjaminfaure$ brew update
Already up-to-date.
Leahs-iMac:~ benjaminfaure$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 4a4ecc0460baec04ec895500ff11d26aa2582b16
Last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: dual-core 64-bit core2
OS X: 10.9.5-x86_64
Xcode: 6.1.1
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: N/A

**Comment by tdsmith** [comment]
What's the problem you're having?

**Comment by Ben4a** [comment]
the unexpected files, how do I deal with them? thanks!

**Comment by tdsmith** [comment]
The easiest option is to leave them alone unless you run into build or link failures. They may never cause problems. If you intend to install some of the same libraries with Homebrew later you may get a message that you need to run `brew link --overwrite` after the installation finishes, which is probably safe. If you don't think you need them for anything you can remove them.

After all:

> Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Thanks for trying Homebrew! Let us know if you have any more questions.

**Comment by Ben4a** [comment]
thank you! I think you're right I installed rails without any probelms so what could go wrong? thanks td
