### ISSUE TITLE
Handle Sourceforge falling over gracefully

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew#36710]
We could improve the Sourceforge-is-down UX in any of a few ways:

* detect the bad certificate from the curl error level and print a nice explanatory error message instead
* start mirroring bottles (Internet Archive?), detect download failures, and fail over to a mirror

I can spend some time on this but later rather than sooner unfortunately.

**Comment by mistydemeo** [comment]
+1 on mirroring bottles on the Internet Archive. I've had good experience with hosting the Tigerbrew bottles there.

**Comment by tdsmith** [comment]
What has to happen before we start pushing files there?

**Comment by jacknagel** [comment]
Does the Internet Archive use a CDN?

**Comment by lhoBas** [comment]
Are there perhaps commercial CDN's willing to sponsor bandwidth for bottles? Might not be a great thing burdening the Internet Archive with all bottle downloads

**Comment by tdsmith** [comment]
Probably; [Fastly](http://www.fastly.com/about/open-source/) and [MaxCDN](https://www.maxcdn.com/open-source/) both have F/OSS goodwill programs.

**Comment by terinjokes** [comment]
@tdsmith I also emailed Mike.

**Comment by DomT4** [comment]
> detect the bad certificate from the curl error level

It'd also be nice to catch and guard the other failure we see in these situations where the SHA is flagged as bad. Perhaps for Sourceforge only, if a SHA comes back as bad from SF, and the formula has a mirror available, rather than just fatally erroring out on the bad SHA we automatically remove the downloaded file and try the mirror instead. I don't think that would be a security threat, if we targeted it narrowly to SF.

**Comment by iml** [comment]
SourceForge already mirrors bottles, e.g. http://heanet.dl.sourceforge.net/project/machomebrew/Bottles/eigen-3.2.4.yosemite.bottle.tar.gz. There is   `HOMEBREW_SOURCEFORGE_MIRROR`, which as I recall passes a mirror to the selector URL `downloads.sourceforge.net`. Perhaps there could be a mechanism to swap out the primary `sf.net` used by bottles.

It would be great to have a proper reliable CDN but SF might not work as an origin server.

**Comment by orospakr** [comment]
Hey, in case this was triggered by https://downloads.sourceforge.net URIs failing today, this is because a CloudFront certificate is being served now.  However, if you accept the certificate, the CloudFront CDN does indeed seem to be hosting the SF content.  I suspect that SF has in fact just switched to CloudFront as a CDN and is probably now issuing different download URIs with a different domain name.

So, I don't think the issue is that SF is down.

**Comment by tdsmith** [comment]
The current failure is discussed at #36703.

**Comment by nikolay** [comment]
Is there any workaround at the moment?

**Comment by DomT4** [comment]
` --build-from-source ` will work, providing the source tarball isn't also hosted on Sourceforge.

**Comment by tdsmith** [comment]
A workaround is described at https://github.com/Homebrew/homebrew/issues/36703#issuecomment-73809207.

**Comment by mikemcquaid** [comment]
I think we should just change the primary bottle source, SourceForge have proven too unreliable. I'm in contact with @terinjokes from CloudFlare for CDN hosting and a university in the Netherlands about being a primary mirror (or we could consider the Internet Archive for that too).

**Comment by mikemcquaid** [comment]
I've contacted CloudFlare, MaxCDN and Fastly about providing CDN access and Bintray and several universities about being the primary mirror. The Internet Archive would also be an option as a primary mirror.

**Comment by mikemcquaid** [comment]
@mistydemeo How do you upload to the internet archive?

**Comment by DomT4** [comment]
Down again :cry:

**Comment by codeurge** [comment]
Very unreliable, SF down again indeed.

**Comment by mikemcquaid** [comment]
We didn't expect downtime again so quickly. I'm actively working on setting up another host. Reminder that none of the Homebrew maintainers are paid to work on this stuff and have full-time jobs they need to fit it aroud.

**Comment by codeurge** [comment]
Absolutely understood - and it isn't said often enough, but thanks to all who do contribute to any open source project.

I wasn't stating that homebrew is unreliable or that the open source efforts aren't up to par; I'm not a developer of adequate skill or I'd offer my time as well. Someday...

On Feb 16, 2015, at 2:00 PM, Mike McQuaid <notifications@github.com<mailto:notifications@github.com>> wrote:


We didn't expect downtime again so quickly. I'm actively working on setting up another host. Reminder that none of the Homebrew maintainers are paid to work on this stuff and have full-time jobs they need to fit it aroud.

-

**Comment by mikemcquaid** [comment]
> I wasn't stating that homebrew is unreliable or that the open source efforts aren't up to par; I'm not a developer of adequate skill or I'd offer my time as well. Someday...

:heart:, thanks!

**Comment by mistydemeo** [comment]
> @mistydemeo How do you upload to the internet archive?

They use an S3-like API, which S3 client libraries can connect to. I primarily use a commandline tool, [internetarchive](https://pypi.python.org/pypi/internetarchive), to upload.

**Comment by jacknagel** [comment]
Is this considered resolved or are there action items left here?

**Comment by tdsmith** [comment]
We still need to migrate taps to Bintray but I think this issue has been mooted; thanks for the nudge.
