### ISSUE TITLE
couchdb recipe LaunchAgents caveats results in `Could not find domain for` error when run headless

### ISSUE THREAD

**Issue by cesine** [Homebrew/homebrew#36720]
from https://github.com/Homebrew/homebrew/issues/19733#issuecomment-73729327

Environment:
* SSHed remotely into a Yosemite machine

Goal
* [follow the couchdb instructions](http://docs.couchdb.org/en/latest/install/mac.html) to start the daemon on boot

Problematic commit
* https://github.com/Homebrew/homebrew/commit/75bdc45396e9735257ca5086b8e93bc14a71846e

Debugging try 1:
We will try to do what the caveats say first. 

```bash
==> Caveats
To test CouchDB run:
    curl http://127.0.0.1:5984/

The reply should look like:
    {"couchdb":"Welcome","uuid":"....","version":"1.6.1","vendor":{"version":"1.6.1-1","name":"Homebrew"}}

To have launchd start couchdb at login:
    mkdir -p ~/Library/LaunchAgents
    ln -sfv /usr/local/opt/couchdb/*.plist ~/Library/LaunchAgents
Then to load couchdb now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.couchdb.plist
Or, if you don't want/need launchctl, you can just run:
    couchdb

$ mkdir -p ~/Library/LaunchAgents
$ ln -sfv /usr/local/opt/couchdb/*.plist ~/Library/LaunchAgents
~/Library/LaunchAgents/homebrew.mxcl.couchdb.plist -> /usr/local/opt/couchdb/homebrew.mxcl.couchdb.plist
$ launchctl load ~/Library/LaunchAgents/homebrew.mxcl.couchdb.plist
Could not find domain for 
```

indeed, couch is not on:
```bash
$ curl https://127.0.0.1:5984
curl: (7) Failed to connect to 127.0.0.1 port 5984: Connection refused
```

When we do what the caveats say, we get an error: `Could not find domain for`
* Possibly similar: http://stackoverflow.com/questions/27189296/homebrew-mxcl-mysql-plist-launchctl-load-error

**Comment by asparagui** [comment]
What do you mean when you say run headless?

**Comment by cesine** [comment]
sorry, "headless" means without a monitor or a machine which only has remote login (ie the script cant rely on any x windows or graphics user interface or mouse etc)

http://whatis.techtarget.com/definition/headless-server

Headless, in this context, basically means that the computing device has no monitor or peripherals, such as a keyboard and mouse. Depending on the type of device they run in, headless systems may largely run autonomously or be remotely controlled.

**Comment by mikemcquaid** [comment]
In OSX a lot of things don't work headless. I'd be very surprised if this is a Homebrew-specific issue rather than a CouchDB one.

**Comment by mikemcquaid** [comment]
Closing this out due to the reason above but please let me know if it's something that doesn't affect upstream CouchDB and I'll reopen.

**Comment by cesine** [comment]
CouchDB installs fine headless, both via brew and from source. 

Since a ~/Library/LaunchAgent isnt our end goal, ill leave this closed until someone else votes to re-open.

we did get the /Library/LaunchDaemon plist running with some help from @dch , so i submitted a pull request #36785 which would satisfy our qualm with  https://github.com/Homebrew/homebrew/commit/75bdc45396e9735257ca5086b8e93bc14a71846e
