### ISSUE TITLE
PHP54 --with-imap fails to install

### ISSUE THREAD

**Issue by ghkdev** [Homebrew/homebrew#36728]
As the title suggests "brew install php54 --with-imap" fails to build. Remove the "--with-imap" flag and all is well. https://gist.github.com/anonymous/e186db5ce0bb6ae2b291

Build fails with "/bin/sh: line 1: 90243 Segmentation fault: 11"

Output from 'brew info php54"
======================
php54: stable 5.4.37, HEAD
https://php.net
Not installed
From: https://github.com/homebrew/homebrew-php/blob/master/Formula/php54.rb
==> Dependencies
Build: libtool ✔
Required: freetype ✔, gettext ✔, icu4c ✔, jpeg ✔, libpng ✔, unixodbc ✔, homebrew/dupes/zlib ✔
Optional: enchant ✘, gmp ✘
==> Options
--disable-opcache
	Build without Opcache extension
--homebrew-apxs
	Build against apxs in Homebrew prefix
--with-apache
	Enable building of shared Apache 2.0 Handler module, overriding any options which disable apache
--with-cgi
	Enable building of the CGI executable (implies --without-apache)
--with-debug
	Compile with debugging symbols
--with-enchant
	Build with enchant support
--with-fpm
	Enable building of the fpm SAPI executable (implies --without-apache)
--with-gmp
	Build with gmp support
--with-homebrew-curl
	Include Curl support via Homebrew
--with-homebrew-libxslt
	Include LibXSLT support via Homebrew
--with-homebrew-openssl
	Include OpenSSL support via Homebrew
--with-imap
	Include IMAP extension
--with-libmysql
	Include (old-style) libmysql support instead of mysqlnd
--with-mssql
	Include MSSQL-DB support
--with-pdo-oci
	Include Oracle databases (requries ORACLE_HOME be set)
--with-phpdbg
	Enable building of the phpdbg SAPI executable (PHP 5.4 and above)
--with-postgresql
	Build with postgresql support
--with-thread-safety
	Build with thread safety
--with-tidy
	Include Tidy support
--without-bz2
	Build without bz2 support
--without-mysql
	Remove MySQL/MariaDB support
--without-pcntl
	Build without Process Control support
--without-pear
	Build without PEAR
--without-snmp
	Build without SNMP support
--HEAD
	Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php5_module    /usr/local/opt/php54/libexec/apache2/libphp5.so

The php.ini file can be found in:
    /usr/local/etc/php/5.4/php.ini

✩✩✩✩ PEAR ✩✩✩✩

If PEAR complains about permissions, 'fix' the default PEAR permissions and config:
    chmod -R ug+w /usr/local/Cellar/php54/5.4.37/lib/php
    pear config-set php_ini /usr/local/etc/php/5.4/php.ini system

✩✩✩✩ Extensions ✩✩✩✩

If you are having issues with custom extension compiling, ensure that
you are using the brew version, by placing /usr/local/bin before /usr/sbin in your PATH:

      PATH="/usr/local/bin:$PATH"

PHP54 Extensions will always be compiled against this PHP. Please install them
using --without-homebrew-php to enable compiling against system PHP.

✩✩✩✩ PHP CLI ✩✩✩✩

If you wish to swap the PHP you use on the command line, you should add the following to ~/.bashrc,
~/.zshrc, ~/.profile or your shell's equivalent configuration file:

      export PATH="$(brew --prefix homebrew/php/php54)/bin:$PATH"

To have launchd start php54 at login:
    ln -sfv /usr/local/opt/php54/*.plist ~/Library/LaunchAgents
Then to load php54 now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.php54.plist

**Comment by mikemcquaid** [comment]
Please report this to the homebrew-php tap, thanks.
