### ISSUE TITLE
problem with brew install texmacs

### ISSUE THREAD

**Issue by esjmb** [Homebrew/homebrew#36736]
date: Feb 11 2015

gist: https://gist.github.com/2b7fc893d89a1454e42a

console output: 
````
brew install texmacs==> Installing texmacs from homebrew/homebrew-boneyard
==> Downloading http://www.texmacs.org/Download/ftp/tmftp/source/TeXmacs-1.99.1-
Already downloaded: /Library/Caches/Homebrew/texmacs-1.99.1.tar.gz
==> ./configure --prefix=/usr/local/Cellar/texmacs/1.99.1 --enable-guile2=yes
==> make
1 error generated.
make[1]: *** [Objects/QTMGuiHelper.o] Error 1
1 error generated.
make[1]: *** [Objects/QTMMenuHelper.o] Error 1
make: *** [TEXMACS] Error 2

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-boneyard/issues
````

brew doctor, brew update etc. all performed.

Any help appreciated,

Stephen.

**Comment by mikemcquaid** [comment]
> If reporting this issue please do so at (not Homebrew/homebrew):
>   https://github.com/homebrew/homebrew-boneyard/issues

Formulae are only moved to the boneyard when they are known to be broken so I don't think this can be fixed, sorry.

**Comment by mikemcquaid** [comment]
@Homebrew/owners think we should consider hiding this report message for the boneyard? Presumably we don't really want issues about those formulae.

**Comment by jacknagel** [comment]
I think that would be fine, or maybe even specifically say "we don't accept issues about this formula"
