### ISSUE TITLE
Cached formula plus broken tap results to homebrew picking up wrong formula

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew#36731]
Recently, neovim/homebrew-neovim receives multiple fail installtion reports (https://github.com/neovim/homebrew-neovim/issues/17, https://github.com/neovim/neovim/issues/1573).  Neovim used to put formula in the neovim main repo, and download it through url. This results to homebrew cached the outdated formula. And from unknown reason, the new tap is broken among some users. All of these result to homebrew picking up wrong formula.

In the benefit of user experience, I hope we can somehow improve the situation from homebrew's end:
* Adding formula origin into `gist-logs`. Currently, such information will only be seen in the `stdout` not the file log. #36730.
* Is there way to let homebrew pick up the right formula in the broken tap even a cached one is presented?
* The problem here is pervasive. `brew tap` did break quite often. I found I need to run `brew tap --repair` many occasions. Should we consider to implement new way to handle taps in homebrew 2.0? IMHO, symlinks are fragile.

**Comment by mikemcquaid** [comment]
> The problem here is pervasive. brew tap did break quite often. I found I need to run brew tap --repair many occasions. Should we consider to implement new way to handle taps in homebrew 2.0? IMHO, symlinks are fragile.

There won't be a Homebrew 2.0 ever in so far as a big rewrite. In terms of making taps not use symlinks: yes, I agree. It's on my TODO list but if you'd like to try and start working on it I think that'd be great. What I have in mind is to keep taps where they are currently but stop using symlinks and instead read the contents of the tap directories directly. Even longer-term we want to split the `Formula` directory into a separate repository from the core code.
