### ISSUE TITLE
Unable to install Homebrew

### ISSUE THREAD

**Issue by ncalitz** [Homebrew/homebrew#36735]
Earlier this morning I formatted my Mac, but now it seems that I am unable to install homebrew. The following error is displayed:

```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

My understanding was that SourceForge was temporarily down yesterday, but has come online again since. Any ideas as to why I am unable to install homebrew?

**Comment by mikemcquaid** [comment]
This is unrelated to SourceForge. What version of OS X are you running? What's the output of `which curl`?

**Comment by ncalitz** [comment]
I am running OSX 10.10.2, clean install. Running `which curl` returns `/usr/bin/curl`

**Comment by mikemcquaid** [comment]
What happens when you run `curl https://github.com`?

**Comment by ncalitz** [comment]
`curl https://github.com` returned the correct data. Surprisingly, without any further changes on my part, I was now able to install homebrew without any issues. Not sure what the issue was, but it seems to have fixed itself. Thank you for your help!
