### ISSUE TITLE
muParser formula

### ISSUE THREAD

**Issue by sofianehaddad** [Homebrew/homebrew#36738]
muParser fails compiling on maverick
The reason is that with formula, do_grouping changes and #include<clmits> is missing

Best regards

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by sofianehaddad** [comment]
Sorry I forgot to answer. 

On the one hand, muParser was linked to libc++. On the other hand, my lib was linked to libstdc++. This is the reason why compilation failed.

I'm sorry for the late reply and thank you for taking  time to look at my request which was basically inappropriate

Regards
