### ISSUE TITLE
Emacs.app randomly hangs when launching

### ISSUE THREAD

**Issue by imrehorvath** [Homebrew/homebrew#36737]
This is the same issue as the closed #25003
Unfortunately this still happens and is real.

When I launch the cocoa built Emacs.app on Mac OS X Yosemite sometimes it hangs and fails to open. The GUI is not loaded and the process hogs the CPU. After force quitting it and launching again, most of the times works fine. But when I try to launch it again after some time, the problem comes back. However there are times when it opens normally without any problem for the first time. The issue never occurred to me when using emacs in Terminal.

```
Date/Time:       2015-02-10 19:00:20 +0100
OS Version:      10.10.2 (Build 14C109)
Architecture:    x86_64
Report Version:  21

Command:         Emacs
Path:            /usr/local/Cellar/emacs/24.4/Emacs.app/Contents/MacOS/Emacs
Version:         Version 24.4 (9.0)
Parent:          launchd [1]
PID:             11449

Event:           hang
Duration:        4.70s (process was unresponsive for 24 seconds before sampling)
Steps:           48 (100ms sampling interval)
```

```
$ brew info emacs
emacs: stable 24.4 (bottled), devel 24.4-dev, HEAD
https://www.gnu.org/software/emacs/
/usr/local/Cellar/emacs/24.4 (3922 files, 117M) *
  Built from source with: --cocoa
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/emacs.rb
==> Dependencies
Build: xz ✔, pkg-config ✔
Optional: d-bus ✘, gnutls ✘, librsvg ✘, imagemagick ✘, mailutils ✘, glib ✘
```

```
$ brew --version
0.9.5
```

**Comment by jacknagel** [comment]
Sorry, but I don't think the answer has changed: https://github.com/Homebrew/homebrew/issues/25003#issuecomment-34786557

Please try to compile emacs outside of Homebrew and see if the problem remains. If it does, then it isn't something we can fix here.

**Comment by imrehorvath** [comment]
@jacknagel Thanks! Yes, I see. You're probably right and it's not a Homebrew related issue.
