### ISSUE TITLE
`brew outdated` calls "HEAD" an older version than the stable version number

### ISSUE THREAD

**Issue by chdiza** [Homebrew/homebrew#36741]
E.g., I have `screenresolution`'s HEAD installed.

Suddenly (within the last few days), `brew outdated` gives me:
````
screenresolution (HEAD < 1.6)
````

This is new, and also seems to me to be incorrect.  I think that in this example, `brew outdated` should do what it used to do, namely, it shouldn't say anything at all about `screenresolution`.

The story is parallel for the other formulas of which I brewed the HEAD.

**Comment by chdiza** [comment]
Relevant wrinkle, just realized: all the formulas for which I brewed the HEAD, and exhibit the aforementioned behavior, are brewed from custom formulas.

The issue goes away if I `brew install --HEAD screenresolution` with the official formula.

Yet, the new behavior is still incorrect.  I'm unclear where to start poking around for a fix.

**Comment by jacknagel** [comment]
https://github.com/Homebrew/homebrew/commit/2d96b48970feff15774e04ae01cec11716f8b7f4

**Comment by mikemcquaid** [comment]
Yeh, I didn't handle the "formula installed from path or URL" case when implementing this and probably need to tweak this so `HEAD` is always assumed to be the newest change.

The motivation for the change is hopefully explained in #36699. I'm open to suggestions on what the most sensible situation is for this case.

**Comment by mikemcquaid** [comment]
Fix in https://github.com/Homebrew/homebrew/pull/36760.
