### ISSUE TITLE
gdal --with-python always installs numpy into prefix

### ISSUE THREAD

**Issue by dschneiderch** [Homebrew/homebrew#36744]
I can't get gdal to recognize netcdf files. I have netcdf, hdf5 and gdal all installed via homebrew. Is there a special flag I need to get gdal to recognize my netcdf libarary?  I also have ncview installed and this works fine.
I'm running 10.9.5

**Comment by iml** [comment]
I think you need to reinstall GDAL with the `--complete` option.

**Comment by dschneiderch** [comment]
I forgot to mention, I had tried brew upgrade gdal --with-python --complete without success. However now when I try `brew upgrade gdal --with-python --complete` I get the following error message:

iMac:~ $ brew reinstall  gdal --with-python --complete
==> Reinstalling gdal with --with-python, --complete
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://download.osgeo.org/gdal/1.11.1/gdal-1.11.1.tar.gz
######################################################################## 100.0%
==> Downloading https://github.com/OSGeo/gdal/commit/12d3b984a052c59ee336f952902b82ace01ba31c.diff
######################################################################## 100.0%
==> Patching
patching file ogr/ogrsf_frmts/sqlite/ogrsqlitevirtualogr.cpp
==> Downloading http://downloads.sourceforge.net/project/numpy/NumPy/1.8.1/numpy-1.8.1.tar.gz
######################################################################## 100.0%
==> python setup.py build --fcompiler=gnu95 install --prefix=/usr/local/Cellar/gdal/1.11.1_3/libexec
  File "/private/tmp/gdal--numpy-789zPt/numpy-1.8.1/numpy/distutils/fcompiler/gnu.py", line 197, in get_flags_opt
    v = self.get_version()
  File "/private/tmp/gdal--numpy-789zPt/numpy-1.8.1/numpy/distutils/fcompiler/__init__.py", line 434, in get_version
    raise CompilerNotFound()
numpy.distutils.fcompiler.CompilerNotFound

**Comment by dschneiderch** [comment]
just tested brew reinstall gdal --complete  and netcdf is now recognized. thoughts on the python error?

**Comment by iml** [comment]
I'm a bit confused on the formula's approach to Python but you can install an up-to-date NumPy via `homebrew/python/numpy`. The `--with-python` option only builds that sandboxed NumPy.

**Comment by dschneiderch** [comment]
iMac:~ $ brew install  homebrew/python/numpy
    Warning: numpy-1.9.1 already installed

is there a way to get `--with-python` to accept this numpy i already have?

**Comment by iml** [comment]
Not exactly. Post `brew gist-logs gdal` to help troubleshoot the above numpy/fortran error. You can also try `brew reinstall gdal --with-python --env=std` to see if it picks up your existing brewed numpy.

**Comment by tdsmith** [comment]
Oh, we definitely should not unconditionally stage numpy into `prefix`; I'll work on that. It won't work with `--env=std`, either.

What's `which gfortran` and `gfortran -v`? Is the environment variable `FC` set? How did you install gfortran?

**Comment by iml** [comment]
Whoops, I meant `brew reinstall gdal --env=std`.

**Comment by dschneiderch** [comment]
gfortran is brewed. here are `which gfortran` and `gfortran -v`  . I'm not sure how to check the FC environment variable but `brew reinstall gdal --with-python --complete --env=std` seems to have installed without errors. `gdalinfo --format netCDF` works as does `gdal_merge.py` and qgis.

    iMac:~ $ which gfortran
    /usr/local/bin/gfortran

    iMac:~ $ gfortran -v 
    Using built-in specs.
    COLLECT_GCC=gfortran 
    COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/4.9.2/libexec/gcc/x86_64-apple-darwin13.4.0   /4.9.2     /lto-wrapper
    Target: x86_64-apple-darwin13.4.0
    Configured with: ../configure --build=x86_64-apple-darwin13.4.0 --prefix=/usr/local/Cellar/gcc/4.9.2     --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-4.9 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-cloog=/usr/local/opt/cloog --with-isl=/usr/local/opt/isl --with-system-zlib --enable-version-specific-runtime-libs --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --disable-werror --with-pkgversion='Homebrew gcc 4.9.2' --with-bugurl=https://github.com/Homebrew/homebrew/issues    --enable-plugin --disable-nls --enable-multilib
    Thread model: posix
    gcc version 4.9.2 (Homebrew gcc 4.9.2)

**Comment by tdsmith** [comment]
Interesting, okay; sorry for lying. :p I've known about a bad numpy/fortran interaction for a while and it's good to know that --env=std helps that.

**Comment by dschneiderch** [comment]
--env=std doesn't seem to help anymore. any suggestions?

Khione:~ $ brew install gdal --with-complete --with-python --with-libkml --env=std
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://download.osgeo.org/gdal/1.11.2/gdal-1.11.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/gdal-1.11.2.tar.gz
==> Downloading https://downloads.sourceforge.net/project/numpy/NumPy/1.8.1/numpy-1.8.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/gdal--numpy-1.8.1.tar.gz
==> python setup.py build --fcompiler=gnu95 install --prefix=/usr/local/Cellar/gdal/1.11.2_3/libexec
  File "numpy/core/setup.py", line 42, in check_types
    out = check_types(*a, **kw)
  File "numpy/core/setup.py", line 289, in check_types
    "Cannot compile 'Python.h'. Perhaps you need to "\
SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
gdal 2.0.0 https://github.com/Homebrew/homebrew/pull/42845
gdal 1.11.2 on OS X 10.6 https://github.com/Homebrew/homebrew/issues/42056
Latest update to poppler, 0.34.0 breaks gdal --with-complete https://github.com/Homebrew/homebrew/issues/42031
gdal --with-python always installs numpy into prefix https://github.com/Homebrew/homebrew/issues/36744
Khione:~

**Comment by tdsmith** [comment]
gdal no longer installs numpy into prefix.
