### ISSUE TITLE
cmake should install its emacs mode to /usr/local/share/emacs/site-lisp

### ISSUE THREAD

**Issue by abique** [Homebrew/homebrew#36758]

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
