### ISSUE TITLE
mono make fails

### ISSUE THREAD

**Issue by haf** [Homebrew/homebrew#36766]
Hi,

I can't get homebrew to properly make mono.

Doing it outside of the temporary directory works fine.

Repro:

 1. Merge https://github.com/Homebrew/homebrew/pull/36764
 2. `brew upgrade --HEAD mono`
 3. Fails on mcs bootstrap.
 4. `less ~/Library/Logs/Homebrew/mono/02.make`

Outside Homebrew:

 1. Same
 2.  `cd /Library/Caches/Homebrew/mono--git`
 3. `./autogen.sh --prefix=/usr/local/Cellar/mono/HEAD --enable-nls=no --build=x86_64-apple-darwin && make`
 4. Successfully compiles.

**Comment by mistydemeo** [comment]
Sorry, to clarify, does this only happen when building the `--HEAD` build in #36764?

**Comment by haf** [comment]
Yes, to my knowledge

**Comment by mistydemeo** [comment]
Let's follow up on it in that issue then; thanks!

**Comment by haf** [comment]
No, why?

This is a separate issue.

Obviously I wouldn't file that PR unless it fixed another problem; and doing --HEAD without the PR has other obvious errors that I didn't catch when I built the original formula.

So it's not a question of solving this before the merge of the PR, the PR is ready to merge, from the basis that it has the 'correct' invocation.

Hence, this is an issue on its own.

**Comment by haf** [comment]
So, what's up? Are you going to comment on the PR or reopen this one?

**Comment by mistydemeo** [comment]
If we're making improvements to `HEAD` builds, I think it makes sense to keep that conversation in one place - that way, the whole set of fixes can happen at once.
