### ISSUE TITLE
go formula - can't compile c source files

### ISSUE THREAD

**Issue by eranb** [Homebrew/homebrew#36776]
After installing go via brew using this command:
` brew install go --with-cc-common`

I can't compile go projects that contains c files, get this message:
`C source files not allowed when not using cgo`

I ran `brew update && brew upgrade && brew cleanup` and this is my config
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 0588ec1d04b67dd42978afddbe501d97ab1fadcc
Last commit: 88 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit haswell
OS X: 10.10.1-x86_64
Xcode: 6.1.1
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/eran/.rvm/rubies/ruby-2.1.3/bin/ruby
Java: 1.7.0_51
```
gist are at:
https://gist.github.com/4d84bd34f944219f5051

**Comment by mistydemeo** [comment]
Are you trying to build a go project for Darwin, or cross-compile for another platform?

**Comment by eranb** [comment]
@mistydemeo yea I'm trying to build executable for linux amd64

**Comment by mistydemeo** [comment]
Homebrew's go isn't built with support for cross-compiling cgo, because cgo requires a C cross-compiler that can target the requested platform and Homebrew does not currently provide that. Sorry!
