### ISSUE TITLE
Move ticcutils, timbl, wopr to Homebrew/Science?

### ISSUE THREAD

**Issue by dpo** [Homebrew/homebrew#36773]
* `timbl`: memory-based learning algorithms
* `ticcutils`: helper library for `timbl`
* `wopr`: word prediction and language modeling

There are a few related PRs over at Homebrew/Science from the same lab: https://github.com/Homebrew/homebrew-science/pull/1469, https://github.com/Homebrew/homebrew-science/pull/1470, https://github.com/Homebrew/homebrew-science/pull/1471, https://github.com/Homebrew/homebrew-science/pull/1472, etc.

```
$ brew uses timb --recursive
wopr
$ brew uses ticcutils --recursive
timbl  wopr
````

**Comment by asparagui** [comment]
+1 from me.
