### ISSUE TITLE
installing python 2.6 on mac OSX Lion (10.7.5)

### ISSUE THREAD

**Issue by ChrisBail** [Homebrew/homebrew#36783]
Hi

I need an older version of python to run a program. How can I do to install the 2.6 version of Python and activate it (I've not seen the python26 formulae)?

Cheers,

Ch.

**Comment by mikemcquaid** [comment]
There's no `python26` in https://github.com/Homebrew/homebrew-versions but you could submit a pull request to add one. I'm afraid we don't support anything beyond that, sorry!
