### ISSUE TITLE
trying to reinstall gerbv with homebrew on Mac Yosemite

### ISSUE THREAD

**Issue by thomasmacpherson** [Homebrew/homebrew#36786]
Hello,

gerbv stopped working when I upgraded to Yosemite, so I uninstalled it and updated various things to keep brew happy, now when I run
`brew install gerbv`
I get
`Error: No available formula for gerbv 
Searching formulae...
Searching taps...
homebrew/x11/gerbv`

Sorry I realise this probably isn't an issue, just unsure where else to ask this.

**Comment by DomT4** [comment]
Looks like it got moved. You can do ` brew tap homebrew/x11 ` and then ` brew install gerbv `.

**Comment by thomasmacpherson** [comment]
Thank you :), then had a problem with libpng16 but sorted it. Thanks
