### ISSUE TITLE
trying to install octave with docs

### ISSUE THREAD

**Issue by samfu1994** [Homebrew/homebrew#36791]
after i run the instruction:           brew install octave --with-docs
it kept running until the procedure:       make all
then it reported:

rm octave-value/ov-fcn-handle.df-t
rm octave.df-t
mv operators/ops.cc-t operators/ops.cc
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues
----------------
How can i fix this?

**Comment by mikemcquaid** [comment]
> READ THIS: http://git.io/brew-troubleshooting
> If reporting this issue please do so at (not Homebrew/homebrew):
> 
> https://github.com/homebrew/homebrew-science/issues

Please do these things, thanks.
