### ISSUE TITLE
ncmpcpp fails to build on OS X 10.7.5

### ISSUE THREAD

**Issue by reicheltd** [Homebrew/homebrew#36796]
https://gist.github.com/anonymous/0f463f54e1859dd150f7

**Comment by jacknagel** [comment]
See https://github.com/Homebrew/homebrew/issues/34787

**Comment by reicheltd** [comment]
$ brew reinstall boost taglib --c++11 --cc=gcc-4.9                                                            
    ==> Reinstalling boost with --c++11
    ==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.57.0/boost_1_57_0.tar.bz2
    Already downloaded: /Library/Caches/Homebrew/boost-1.57.0.tar.bz2
    ==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost/1.57.0 --libdir=/usr/local/Cellar/boost/1.57.0/lib --without-icu --without-libraries=pyth
    ==> ./b2 --prefix=/usr/local/Cellar/boost/1.57.0 --libdir=/usr/local/Cellar/boost/1.57.0/lib -d2 -j2 --layout=tagged --user-config=user-confi
    cp: /usr/local/Cellar/boost/1.57.0/lib/libboost_wave.a: Permission denied
    ...failed common.copy /usr/local/Cellar/boost/1.57.0/lib/libboost_wave.a...
    ...removing /usr/local/Cellar/boost/1.57.0/lib/libboost_wave.a
    ...failed updating 118 targets...
    ...updated 1639 targets...
    
    READ THIS: http://git.io/brew-troubleshooting
    
    brew reinstall boost taglib --c++11 --cc=gcc-4.9  4304.26s user 455.74s system 169% cpu 46:41.67 total

**Comment by reicheltd** [comment]
`brew upgrade boost taglib --c++11 --cc=gcc-4.9` worked. thx
