### ISSUE TITLE
Cannot install wine because of OpenSSL

### ISSUE THREAD

**Issue by flaker** [Homebrew/homebrew#36800]
Hi,

I was trying to install Wine and it failed bacause OpenSSL fails when running the `test` target.

    2698605080:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:187:filename(libz.dylib): dlopen(libz.dylib, 2): image not found
    2698605080:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:232:
    2698605080:error:29064065:lib(41):BIO_ZLIB_NEW:zlib not supported:c_zlib.c:462:
    2698605080:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:187:filename(libz.dylib): dlopen(libz.dylib, 2): image not found
    2698605080:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:232:
    2698605080:error:29064065:lib(41):BIO_ZLIB_NEW:zlib not supported:c_zlib.c:462:
    cmp: EOF on ./p.zlib.clear
    make[1]: *** [test_enc] Error 1
    make: *** [tests] Error 2

I am pretty new to macs and brew so maybe I am missing something.

Gist file: https://gist.github.com/anonymous/288dd7a903a5f8decdff

Maybe this is related to https://github.com/Homebrew/homebrew/issues/33218

Thanks for your help.

**Comment by DomT4** [comment]
Hmm. What happens if you do ` file /usr/lib/libz.1.dylib ` in your terminal application?

**Comment by flaker** [comment]
Here it is:

 $ file /usr/lib/libz.1.dylib
 /usr/lib/libz.1.dylib: Mach-O universal binary with 2 architectures
 /usr/lib/libz.1.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
 /usr/lib/libz.1.dylib (for architecture i386):	Mach-O dynamically linked shared library i386

**Comment by DomT4** [comment]
Meh, nothing unexpected there. The readout from the failure looks like it's not finding that dylib at all, which is weird. Do you hit the same failure if you run ` brew install openssl --universal ` outside of the ` brew install wine ` process?

**Comment by flaker** [comment]
weird ... it is already installed ... why is wine trying to build it again.

    $ brew install openssl --universal
    Warning: openssl-1.0.2 already installed

**Comment by DomT4** [comment]
That's expected, sadly. It's likely you have a non-universal ` openssl ` installed and Wine requires all of its dependencies to be built as Universal dylibs (Supporting x86_64 and i386), so it forces a reinstallation of all of the deps with the ` --universal ` tag enforced.

**Comment by flaker** [comment]
Ok, good to know. Anyway I uninstalled OpenSSL and proceeded to run the previous test. It failed with the same error message, so building universal OpenSSL is not building.

**Comment by DomT4** [comment]
No issues here:

```
==> Summary
/usr/local/Cellar/openssl/1.0.2: 459 files, 23M, built in 16.0 minutes
```

Makes me wonder if there's a stealth ` xcode ` requirement to building OpenSSL, as that's the only difference I can see between our configs. Will let one of the maintainers chime in on this.

**Comment by tdsmith** [comment]
What's in /Users/fdelgado/lib? Does it help to unset DYLD_FALLBACK_LIBRARY_PATH?

**Comment by justinclift** [comment]
As @tdsmith pointed out, your output from "brew doctor" looks unusual:

```
Warning: Setting DYLD_* vars can break dynamic linking.
Set variables:
    DYLD_FALLBACK_LIBRARY_PATH: :/Users/fdelgado/lib
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!
```

The "normal" output from brew doctor is:

```
$ brew doctor
Your system is ready to brew.
$
```

**Comment by flaker** [comment]
Hi,

Sorry for the delay. I was without this computer for the long weekend.

You are right about the `brew doctor` output. I have added the  `DYLD_FALLBACK_LIBRARY_PATH` on purpose so that python-mysql can find `libmysqlclient.18.dylib`. That file is the only content of the fallback library path.

I have no clue whatsoever on why is that variable messing with the build if only that lonely lib is there but after unsetting it, the --universal version of openssl built successfully.

Should I close this or someone needs logs or more information?

**Comment by justinclift** [comment]
Hmmm, this bug is probably "close-able".  But you're right it's kind of strange.  Maybe the real bug is in python-mysql needing that path?

**Comment by flaker** [comment]
Something with the mysql installer for Mac leaves a couple of things out of the regular path. On Linux, python-mysql works without any manual intervention. Of course as I have stated, I am new to Mac and Brew so maybe it would have been wiser to use a brewed mysql instead of the official dmg installer. I will close the issue. Let me know if someone needs a log or some step to reproduce the issue.

Thank you everyone.

**Comment by DelightRun** [comment]
Yes, I meet this problem, too.And I'm setting `DYLD_FALLBACK_LIBRARY_PATH` for `anaconda`'s lib.

So is this a bug because of `DYLD_FALLBACK_LIBRARY_PATH` but not only for `python-mysql` ?

**Comment by tdsmith** [comment]
Yes, that's right.

**Comment by miagao** [comment]
Same thing happened here, I tried to export an empty DYLD_FALLBACK_LIBRARY_PATH and it still fails.. 
the solution: 

# unset DYLD_FALLBACK_LIBRARY_PATH  
and then 

# brew install openssl --universal

**Comment by Silkshake** [comment]
Thanks everyone! This worked for me on a relatively locked-down work computer. Those two lines from miagao seem to have fixed my issues I was having with homebrew and some other software (namely the Haskell ghc build here https://ghcformacosx.github.io )

**Comment by hughes** [comment]
I didn't have `DYLD_FALLBACK_LIBRARY_PATH` set, but `brew install openssl --universal` worked for me. Thanks.
