### ISSUE TITLE
doc readability 

### ISSUE THREAD

**Issue by zicai** [Homebrew/homebrew#36809]
hi,

when i was reading [https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/manpages/brew.1.md]

i find some word are missing

these word in < >  in markdown

**Comment by mikemcquaid** [comment]
Sorry, can you elaborate a bit?

**Comment by zicai** [comment]
for example:

in markdown:

![cc2ff877-0798-4dff-bb66-eedbee41a280](https://cloud.githubusercontent.com/assets/2225683/6202039/c9661baa-b50a-11e4-9fea-9bb1b9714640.png)

in preview:

![eb261d7c-9978-487a-905a-7756a7a13bf5](https://cloud.githubusercontent.com/assets/2225683/6202044/f4be801c-b50a-11e4-9e2a-a85d7e272c72.png)

these words in < > are hidden

**Comment by jacknagel** [comment]
How will escaping the angle brackets affect the generated man page?

**Comment by zicai** [comment]
hmm,sorry ,i don't know how to test the affect of man page ~~~~(>_<)~~~~

**Comment by mikemcquaid** [comment]
You can test it by running `brew man` and then `man brew`.

**Comment by jacknagel** [comment]
I looked into this and there doesn't seem to be a way to make the angle brackets render correctly in both markdown and the generated roff. Open to suggestions (or patches) that fix this, but if we have to choose, then the generated man page is more important.
