### ISSUE TITLE
OpenSSL loop

### ISSUE THREAD

**Issue by LoneStarMac** [Homebrew/homebrew#36816]
When I try to install any formula, I get the error 
`You must brew install openssl to compute sha256 hashes on Tiger`

When I try to `brew install openssl` I get the same error.

I followed the advice in issue #108 and executed mistydemeo's workaround formula, and that installed openssl 1.0.1 just fine since re-executing that code tells me it's already installed. I also installed the certs as instructed by brew following mistydemeo's openssl formula.

I performed executed `brew uninstall openssl`, and it successfully removed openssl 1.0.1, but `brew install openssl` is still failing because I don't have openssl installed. :) 

Is there a way to skip computation of hashes on openssl installation, just so it will install?

**Comment by mikemcquaid** [comment]
@mistydemeo @LoneStarMac I pushed a commit to use `sha1` in the OpenSSL formula which should fi this.

**Comment by DomT4** [comment]
Long term it might be worth vendoring ` coreutils ` on the older OS X versions, since the direction is moving away from SHA1 *(slowly)* rather than towards it. It's a reasonable size for the utilities provided.

**Comment by mikemcquaid** [comment]
You mean `openssl`?

**Comment by mistydemeo** [comment]
@mikemcquaid For reference, I already made this change in Tigerbrew, and Tiger users shouldn't be able to use Homebrew!

**Comment by mikemcquaid** [comment]
@mistydemeo Ah ok, feel free to revert.

**Comment by LoneStarMac** [comment]
I'm sorry, should I have posted this elsewhere? My apologies.

**Comment by DomT4** [comment]
@mikemcquaid No, my thoughts were we could vendor the ` coreutils ` library on older OS X versions and then use that to verify the SHA256 checksums where they exist. 

That would (presumably) save Tigerbrew from having to tweak the checksums on formulae. Coreutils is a more compact library than ` openssl `. I guess we could vendor ` openssl `, but it's a significantly longer compile time than ` coreutils `. Just thinking that we could compile ` coreutils ` on the older systems when Homebrew is installed, and then use that to compute all the checksums.

But I guess with the amount we depend on ` openssl ` now, it's probably not worthwhile I guess. Ignore me, just pondering :smile_cat:.

**Comment by chdiza** [comment]
>  we could vendor the coreutils library on older OS X versions

There is already WAY too much stuff to have to build on Tiger or Leo PPC before one can even begin brewing basics.  Most of it takes forever to build on the kind of old machines that use Tigerbrew.  I am loathe to add one more, especially since @mistydemeo has already taken care of this.

**Comment by chdiza** [comment]
@LoneStarMac If you're on Tiger, you should be using Tigerbrew.  Homebrew doesn't support 10.4.

**Comment by LoneStarMac** [comment]
Thanks all, and @chdiza, I went ahead and opened an issue on Tigerbrew (https://github.com/mistydemeo/tigerbrew/issues/306). Sorry about the confusion, but thanks for taking a look. The machine I'm using is an iMac G4 1.25ghz 20" with 2gb of RAM. It has a little more oomph than a 700mhz clamshell, but it does still take some time to build some of these larger packages. These older machines pose some fun challenges, as shown here. :) Thanks again for the help, everyone; what a cool community!
