### ISSUE TITLE
berkeley-db install with java and sql support

### ISSUE THREAD

**Issue by atikinn** [Homebrew/homebrew#36817]
Installation failed https://gist.github.com/atikinn/d3a006d8b919084216ff

Would appreciate some help

**Comment by newhook** [comment]
The forumula seems to be incorrect. The jni headers are in $JAVA_HOME/include. For me with JDK 1.7 they are in /Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home/include or they are in /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/include depending on what JDK I'm using.

**Comment by DomT4** [comment]
Let us know if we can help further here, Thanks!
