### ISSUE TITLE
Lion bottles from non-Lion boxes?

### ISSUE THREAD

**Issue by Noctem** [Homebrew/homebrew#36814]
### Problem
Some Macs are unfortunate enough to be stuck on OS X Lion. These machines are usually relatively slow so it can take them a while to compile large projects, and bottles are no longer provided for them (as discussed in #35049), apparently due to resource limitations. 
Furthermore, the compiler on Lion is out of date: ```Apple LLVM 4.2 (clang-425.0.28) (based on LLVM 3.2svn)``` as opposed to ```Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)``` on Yosemite.

### Idea 
Build Lion bottles on one of the newer bots with the deployment target set to 10.7. It could be done on Mountain Lion to be as similar to the target as possible, or Yosemite to benefit from the latest build environment (by that same logic, all bottles could be built from Yosemite with various deployment targets, which also seems worth considering/testing).

So after the bot completes its native bottle, it could start over and rebuild with ```MACOSX_DEPLOYMENT_TARGET=10.7``` and any other environmental tweaks that are deemed necessary. I've tested this by removing the deployment target environment sanitizer from Homebrew and then bottling formulas for Lion from Yosemite, so far they have all built and run correctly. I thought that perhaps there would be issues with C++ libraries on builds from Mavericks or later, but in the formulas I've tested it appears that simply setting the deployment target environment variable to Lion leads the compiler to choose stdc++ unless it's forced to do otherwise (with ```ENV.cxx11``` for example). 

To be extra cautious, perhaps building from source could remain the default for Lion systems, but users that don't have time for building or that want the benefits of more recent compiler advancements could force bottle usage with an argument to ```brew install``` or an environment variable like ```HOMEBREW_BUILD_FROM_SOURCE=0```.
##### Pros
* Performance enhancements and fixes from more recent compilers
  * I got better hashing performance in ```openssl speed``` with a Yosemite-compiled bottle than a native Lion build.
  * ffmpeg 2.5.x failed to build on Lion for me (which I haven't investigated yet), but a Lion-targeted bottle from my Yosemite system works just fine.
* Save older machines from lengthy build times
* Distributing binaries for versions of OS X older than the build system is very common and seems to work well for many applications

##### Cons
* Deviates from the usual Homebrew philosophy of staying as native as possible
* More work for the bots
* I could be underestimating the complications, I haven't done extensive testing (yet!).
  * A potential increase in the support burden could perhaps be alleviated by skipping bottles by default on Lion and providing a warning about installing non-native binaries.
* Build-bots wouldn't be able to test the binaries in the same environment as the target
  
If anyone has also tried testing anything like this or thinks I'm missing something, feel free to share your results or thoughts.

Paging @mikemcquaid.

**Comment by mikemcquaid** [comment]
Sorry, this is a level of complexity I don't really want to get into here (but I appreciate the research). It's partly just I personally don't consider Homebrew to support more than 10.10, 10.9 and 10.8 which is a big reason we don't provide binary packages for them (as well as resource constraints).
