### ISSUE TITLE
New Version of CMake

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew#36829]
Just wanted to let you guys know that Kitware looks like its on track to release CMake 3.2.0 today.  It's not out just yet, but I think we should keep an eye on the CMake repository so that `cmake.rb` can be updated to references this new release as soon as it comes out.

**Comment by jacknagel** [comment]
Thanks; feel free to open a pull request when it's available.

**Comment by RandomDSdevel** [comment]
Oh, wait; never mind, that was release candidate one.  I'll let you guys know when the final release is available.
