### ISSUE TITLE
python _ssl module fails to build on 10.6

### ISSUE THREAD

**Issue by jarah** [Homebrew/homebrew#36825]
New to this, so probably doing something wrong.   Console log below, not sure if this is what you need.

"brew doctor" has no issues
done both 'brew update'' and "brew upgrade" as well

Have attached the 2 logs at end too.

[logs snipped -tdsmith]

**Comment by jacknagel** [comment]
Please follow the instructions at http://git.io/brew-troubleshooting

**Comment by jarah** [comment]
Have created a gist https://gist.github.com/e6085818804b34ccb509

**Comment by jarah** [comment]
brew update run twice, brew doctor run "ready to brew"
Xcode is as up to date as Snow Leopard will allow

**Comment by tdsmith** [comment]
This looks like the problem where building the _ssl module during the Python install fails on 10.6, similar to #36295 and #35195.

Can you `brew uninstall python`, `brew install python`, and `brew gist-logs python`?

**Comment by jarah** [comment]
Here you go
https://gist.github.com/124632e5030c2014d88e

**Comment by tdsmith** [comment]
Looks clean. Does node work now?

**Comment by jarah** [comment]
Working great now.  Many thanks

**Comment by tdsmith** [comment]
How long ago did you first install python? Was it recent or have you been using Homebrew for a while?

**Comment by jarah** [comment]
only just started to use home brew on very old machine, do imagine Python out of date

**Comment by tdsmith** [comment]
Mysterious! Thanks for reporting.
