### ISSUE TITLE
No formula for Meld?

### ISSUE THREAD

**Issue by akras14** [Homebrew/homebrew#36824]
I am not sure if I am missing something. I can't find a formula for meld.
```
$ brew install meld
Error: No available formula for meld 
Searching formulae...
Searching taps...
```
Looking through the issues I see that it was moved to `homebrew/x11/meld`, but if thats the case shouldn't the search point to it?

`brew install homebrew/x11/meld` does not work for me, but not sure if that's the right way to install meld now.

**Comment by jacknagel** [comment]
Hmm, works as expected here:

```
$ brew install meld
Error: No available formula for meld
Searching formulae...
Searching taps...
homebrew/x11/meld
$ brew install homebrew/x11/meld
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-x11'...
remote: Counting objects: 135, done.
remote: Total 135 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (135/135), 56.00 KiB | 0 bytes/s, done.
Resolving deltas: 100% (24/24), done.
Checking connectivity... done.
Tapped 89 formulae
==> Installing meld from homebrew/homebrew-x11
```

**Comment by willbuck** [comment]
Works for me as well! Thanks @jacknagel

**Comment by vasvasvas** [comment]
Yes, but the formula as of now installs Meld 1.8. The current version of Meld is 3.12.

**Comment by adamv** [comment]
Someone will need to submit a pull request for the updated version to https://github.com/Homebrew/homebrew-x11

**Comment by Paget** [comment]
@akras14 I ran into the same issue. For whatever reason i couldn't ```brew install homebrew/x11/meld``` directly. I had to break it up into steps:

```brew install homebrew/x11```

and then I could 

```brew install meld```

**Comment by akras14** [comment]
Interesting,  I also get this:

```
$: brew install homebrew/x11/
Error: No available formula for homebrew/x11/
Searching formulae...
Searching taps...
$:
$: brew doctor
Your system is ready to brew.
```

As a work around, I got it working without brew: http://www.alexkras.com/how-to-run-meld-on-mac-os-x-yosemite-without-homebrew-macports-or-think/

Seems to be a one of issue that not a lot of people run into.

**Comment by vasvasvas** [comment]
I used the same workaround that akras14 mentions. Works well.

**Comment by tdsmith** [comment]
The correct commands are either
```
brew install homebrew/x11/meld
```
or
```
brew tap homebrew/x11
brew install meld
```

`brew install homebrew/x11` does not do anything useful, with or without a trailing slash; homebrew/x11 is a tap and install only operates on formulas (formulas reside within a tap; taps are repositories).

Let us know if we can help with anything else.

**Comment by garidan** [comment]
I had the same problem, and I resolved it.
It was due to wrong permissions on folder /usr/local/Library/Taps.
So I did sudo chown -R xxxUSERxxx:admin  /usr/local/Library/Taps
