### ISSUE TITLE
cmake --build-from-source fails on OS X 10.9 (brewed python)

### ISSUE THREAD

**Issue by NikolausDemmel** [Homebrew/homebrew#36831]
It seems to fail because setuptools is not found.

```
$ brew install cmake --build-from-source
==> Downloading http://www.cmake.org/files/v3.1/cmake-3.1.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/cmake-3.1.2.tar.gz
==> Downloading https://pypi.python.org/packages/source/S/Sphinx/Sphinx-1.2.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/cmake--sphinx-1.2.3.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/cmake-2meG2b/cmake-3.1.2/sphinx --single-version-externally-managed --record=installed.txt
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named setuptools

READ THIS: http://git.io/brew-troubleshooting

These open issues may also help:
cmake builds fail on CLT-only with --env=std (https://github.com/Homebrew/homebrew/issues/29101)
```

`brew gist-logs cmake` ==> https://gist.github.com/anonymous/5677e8e024e2ba14c37f

Setuptools is installed for the python I use (brewed python), but not for system python.

Is the formula supposed to use system python rather than the user-configured python (brewed python)?

**Comment by DomT4** [comment]
As far as I understand it, Homebrew consistently prefers using the system Python where possible. The system Python should have ` setuptools ` available. @tdsmith is the expert.

**Comment by NikolausDemmel** [comment]
How can I install setuptools for system python if pip is installed for brewed python?

**Comment by tdsmith** [comment]
setuptools should be installed to /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python by the OS.

To reinstall, you ought to be able to download [get-pip.py](https://bootstrap.pypa.io/get-pip.py) and invoke it with `sudo -H /usr/bin/python -s get-pip.py`. This will probably overwrite the `pip` and `easy_install` stubs in /usr/local/bin; sudo chowning them back to you and running `brew postinstall python` ought to put things back to normal.

**Comment by tdsmith** [comment]
(you'll want to make sure the /usr/local site-packages is out of your sys.path; if you added it with a .pth file in your user site-packages, the -s switch will accomplish that by keeping python from looking at your user site-packages.)

**Comment by NikolausDemmel** [comment]
@tdsmith thanks, that worked.

For the record, the `pip` and `easy_install` stubs in `/usr/local/bin` were not overwritten.
