### ISSUE TITLE
gpg2 update to 2.1.2

### ISSUE THREAD

**Issue by simmel** [Homebrew/homebrew#36848]
Would be nice to upgrade gpg2 to the new "modern" (their wording, not mine) version 2.1.2.

Compiles nicely and works in my very limited testing. Not sure how to update this beast of a brew though so I thought I'd ask you if you wanted to redo something with the packaging or so?

**Comment by mikemcquaid** [comment]
See https://github.com/Homebrew/homebrew/pull/35106 for discussion here.
