### ISSUE TITLE
Feature suggestion: excludes for brew cleanup

### ISSUE THREAD

**Issue by rainerfrey** [Homebrew/homebrew#36847]
I regularly upgrade my installed formulae to the newest versions, but I need to keep a specific old version of one formula around. Therefore it'd be very convenient to be able to cleanup everything but this one formula.
I use the old version installation explicitly in an IDE integration, and therefore keep it in addition to the current version. So I don't need to exclude it from upgrading, just from cleanup.

**Comment by mikemcquaid** [comment]
brew cleanup $(brew list | grep -v imagemagick) will skip imagemagick. I don't think we'll add anything to core beyond that I'm afraid, sorry!

**Comment by rainerfrey** [comment]
Ah I overlooked that cleanup can take multiple formulae in one invocation - thanks, this is sufficient for me.
