### ISSUE TITLE
Issues with little-cms2

### ISSUE THREAD

**Issue by mccartyn** [Homebrew/homebrew#36861]
Trying to install wine and I can't download little-cms2
OS X 10.10.1

Is this an issue with sourceforge?

console log:

$ brew fetch little-cms2
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/little-cms2

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "little-cms2"
Download failed: https://downloads.sf.net/project/machomebrew/Bottles/little-cms2-2.6.yosemite.bottle.1.tar.gz

**Comment by ZacharyDuBois** [comment]
Yep, issue with SourceForge. Most formula have a backup download link that it will try. But some don't.

**Comment by DomT4** [comment]
Yeah, Sourceforge is down *again*.

**Comment by jacknagel** [comment]
known issue
