### ISSUE TITLE
Building pinentry-mac executes remote code

### ISSUE THREAD

**Issue by Midar** [Homebrew/homebrew#36873]
From the included Makefile:
`        @bash -c "$$(curl -fsSL https://raw.github.com/GPGTools/GPGTools_Core/master/newBuildSystem/prepare-core.sh)"`

This just executes unverified remote code.

EDITED

**Comment by Midar** [comment]
Oh, btw, this script then goes on to download more code via git (not via https://, via git://). That is, for now it does that. That might change at any moment.

In any case, this shows that the developer(s) completely ignore any security practice that is basically common in all projects, even non security projects, these days and that they are not to be trusted at all. (I mean, common, this is a security project and they fail to even follow the most basic security practices.)

**Comment by jacknagel** [comment]
I would prefer that our issue tracker not be a platform for ranting about other projects. In the future, please just describe the issue in technical terms and save the rest for twitter or something. Thank you!

**Comment by chdiza** [comment]
I've noticed this too, because it causes the brewing of `pinentry-mac` to fail when one's internet connection is off, even when the stable tarball and the HEAD repo are already cached.

I don't know what to do about it, though. Perhaps a fork?

**Comment by DomT4** [comment]
If anyone's super-bored and wants to tear a 30 minute ponder to shreds, I've opened #36887 for discussion on this. Feel free to laugh heartily at the general nightmarish messiness of me working around the remote execution.

**Comment by Midar** [comment]
@jacknagel: I just wanted to explain why I think the problem is that severe that it justifies deleting the Formula.

@chdiza: I agree that a fork would be a good idea. But that alone's not enough. Since the developers demonstrated lack of security knowledge, it all needs to be audited very thoroughly. I'd be willing to help with that.

**Comment by DomT4** [comment]
> I just wanted to explain why I think the problem is that severe that it justifies deleting the Formula.

We can work to address the issues, either here or upstream, or both. Enough people were happy that we added the formula that erasing it would raise complaints.

> Since the developers demonstrated lack of security knowledge, it all needs to be audited very thoroughly.

This is a little unfair. GPGTools is a tiny team with a stupidly small amount of funding available to them. GPG isn't an easy codebase to work with at the best of times. We've reported security issues upstream to them before and they've fixed them. They, like most open-source projects, need better funding, or more people willing to give their time and skill.

GPGTools are already working on [some of the issues](https://github.com/GPGTools/GPGTools_Core/commit/5186bade36acedfdc0b76f9f5ddfcfc004ec698b) you raised in this issue.

**Comment by sneak** [comment]
How did this get into homebrew in the first place?!

**Comment by DomT4** [comment]
A tiny dev team working incredibly hard to screen hundreds of active issues and PRs on a weekly basis despite the fact Homebrew doesn't pay anyone's bills. And the guy who submitted it does security work, and is well known for that.

It's a crappy situation, but nobody noticed it was remotely executing code, not even prior discussion upstream on the GnuPG mailing lists.

**Comment by mistydemeo** [comment]
Again, as @jacknagel requested, please keep ranting about other projects out of this issue, and please keep all discussion civil and respectful. Thanks.

**Comment by DomT4** [comment]
Apologies if my tone was abrasive. Not intentional.

**Comment by sneak** [comment]
Perhaps "spend 30 seconds reading the makefile of formula added to the repo" is an appropriate policy.

Homebrew is generally installed sgid admin (though why anyone would permit this is beyond me - but that's the default).  There needs to be an interlock to prevent these sort of mistakes from happening.  Humans make mistakes, but we're also capable of learning from them.  The workflow that resulted in this ending up in the repo is the root cause, not one person missing one line in a Makefile.

**Comment by mikemcquaid** [comment]
If other people want to do work here rather than barking instructions at Homebrew maintainers: feel free to start reviewing our code. I've edited a bunch of comments about to tone down the hyperbole, deleted some that aren't constructive and am locking down this thread. @DomT4 is the only person who cared enough about this issue to create a PR. In future: create PRs instead of ranting on issues.
