### ISSUE TITLE
pkgconfig path incorrect when installing zeromq --HEAD

### ISSUE THREAD

**Issue by minrk** [Homebrew/homebrew#36874]
It is failing to find libsodium, which is in /usr/local/lib/pkgconfig. This is the default path for pkgconfig, but explicitly excluded from PKG_CONFIG_LIBDIR in the Superenv. Stdenv includes this location, but I don't know when that's used.

From discussion on other issues, such as #27666, it seems that the omission of /usr/local from PKG_CONFIG_LIBDIR is intentional, but I can't find the reason for it. `libsodium.pc` should definitely be found via pkg-config when setting up zeromq, but it's unclear what the fix for this is. It seems like either `/usr/local/lib/pkgconfig` should be on PKG_CONFIG_LIBDIR or PKG_CONFIG_PATH, or `libsodium.pc` should be copied into `/usr/local/Library/ENV/pkgconfig/X.Y`. A workaround can be added to the zeromq Formula, but it seems like a generic issue that pkg-config is entirely disabled for locating dependencies installed via homebrew.

I see several `.pc` files in /usr/local/lib/pkgconfig not in `/usr/local/Library/ENV/pkgconfig`, and I cannot figure out why homebrew is explicitly disabling packages finding their dependencies via pkg-config. Is there an explanation for the different roles of `/usr/local/lib/pkgconfig` and `/usr/local/Library/ENV/pkgconfig/X.Y`, and what files should be where, and what state Formulae should be expecting pkg-config to be in?

`brew install zeromq --build-from-source` *does* find libsodium, but I think that's because libzmq-4.0 looks for libsodium without pkg-config, and libzmq-4.1 only uses pkg-config to find libsodium.

**Comment by jacknagel** [comment]
`/usr/local/Library/ENV/pkgconfig/X.Y` will never contain any files from Homebrew-installed software. It exists purely to provide a handful of pkgconfig files that OS X doesn't provide anymore.

Rather than use `/usr/local/lib/pkgconfig`, superenv adds pc file directories for each individual dependency (in the form of `/usr/local/opt/dependency_name/lib/pkgconfig`). This helps prevent unlisted deps from leaking into the build environment.

So let's step back and go through the normal troubleshooting steps (provide build logs, etc).

**Comment by DomT4** [comment]
I presume you did ` brew install zeromq --HEAD --with-libsodium `? It's an optional dep, which means it doesn't get pulled in unless you call it. It was bumped down from recommended in https://github.com/Homebrew/homebrew/commit/e82781388f3bca303a428f69a137d0684a27d57e.

**Comment by minrk** [comment]
Arg, I left out `--with-libsodium`. So the issue is that `brew install zeromq --HEAD` depends on libsodium regardless of whether `--with-libsodium` is passed. Either it's an upstream bug that it checks for libsodium when it shouldn't, or it should be a change in the Formula that `zeromq --HEAD` always depends on libsodium.

I didn't realize that `--with-libsodium` would change whether `libsodium.pc` is available in the build env. That's very surprising.

**Comment by minrk** [comment]
Note that `brew install zeromq --build-from-source` *does* find and link libsodium, while `brew install zeromq --HEAD` does not. So the library isn't unavailable if `--with-libsodium` is not specified, it's just that the pkgconfig environment isn't manipulated.


[Build log](https://gist.github.com/6536bf6f4bed80671c28) of `brew install zeromq --HEAD`.

Actual output without `-v`:

```
==> ./configure --prefix=/usr/local/Cellar/zeromq/HEAD
installed software in a non-standard prefix.

Alternatively, you may set the environment variables sodium_CFLAGS
and sodium_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

READ THIS: http://git.io/brew-troubleshooting
```

**Comment by jacknagel** [comment]
>So the library isn't unavailable if --with-libsodium is not specified, it's just that the pkgconfig environment isn't manipulated.

Correct, this is by design. Optional deps are not added to the environment unless you specifically request them.

As you noted earlier, the stable build may be finding it by some other means than pkgconfig. It's possible that `--HEAD` now *requires* libsodium, in which case the dependencies in the formula need to be adjusted to reflect that.

**Comment by DomT4** [comment]
Yeah, It's opportunistically finding and linking ` libsodium `, even when a ` --without-libsodium ` or ` --with-libsodium=no ` flag is passed, which is kinda irritating. It does this even without the dependency in the formula.

```
otool -L /usr/local/bin/curve_keygen:
	/usr/local/Cellar/zeromq/4.0.5_2/lib/libzmq.4.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/local/lib/libsodium.13.dylib (compatibility version 15.0.0, current version 15.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

**Comment by minrk** [comment]
It looks like the upstream change is intentional - libzmq depends on libsodium by default now. I opened #36875 to add `--with-libsodium=no` as the default behavior in homebrew. Hopefully a proper fix for #33677 can be worked out, and libsodium can go back to being a recommended dependency for libzmq.

**Comment by minrk** [comment]
@DomT4 `--with-libsodium=no` is respected in libzmq master, but not 4.0.

**Comment by DomT4** [comment]
@minrk Ah. That could be a problem, because that means anyone with ` libsodium ` already installed is getting a ` zeromq ` linked to it which causes issues such as #33677 - Which kinda defeats the point of downgrading the dep from recommended. Bleh. I wonder if we can backport the fix from master, in that case.

**Comment by DomT4** [comment]
On the upside, because the Brew test-bot is a clean machine, at least anyone who has installed ` zeromq ` from the bottle is protected. It's just ` -fs ` builds that have the error.

**Comment by minrk** [comment]
> I wonder if we can backport the fix from master, in that case.

Should be easy enough. I can try to send the patch upstream to zeromq-4.0

**Comment by minrk** [comment]
patch sent upstream: https://github.com/zeromq/zeromq4-x/pull/105
#36875 updated to backport the patch, so brew can use it.
