### ISSUE TITLE
freeradius-server 2.2.6_1 and openssl different then 1.0.1_k

### ISSUE THREAD

**Issue by dpenezic** [Homebrew/homebrew#36889]
Hi,
i spend some time playing with brew (I am new with this software) and found issue with freeradius-server and openssl package.

From my foundlings it is look like freeradius-server bottled package is compiled with dependency to openssl version 1.0.1k (i found in git history that point) and is not able to work with latest openssl.

Basicaly : 
brew update
brew doctor
brew install openssl
brew install freeradius-server 

when openssl is different from 1.0.1_k will not work.

Workaround : 
brew update
brew doctor
brew install openssl
brew install --build-from-source freeradius-server

Very probably someone need to rebottled freeradius-server package :)

**Comment by DomT4** [comment]
Yup. Needs a revision. It usually does, but I presume I forgot last time - My apologies.
