### ISSUE TITLE
Error installing gs

### ISSUE THREAD

**Issue by ozagordi** [Homebrew/homebrew#36906]
Hi,
while installing gs (ghostscript), I have

    [user@host ~]$  brew install gs
    ==> Installing dependencies for ghostscript: jbig2dec, little-cms2
    ==> Installing ghostscript dependency: jbig2dec
    ==> Downloading https://downloads.sourceforge.net/project/jbig2dec/jbig2dec/0.11/jbig2dec-0.11.tar.gz

    curl: (60) SSL certificate problem: Invalid certificate chain
    More details here: http://curl.haxx.se/docs/sslcerts.html

    curl performs SSL certificate verification by default, using a "bundle"
     of Certificate Authority (CA) public keys (CA certs). If the default
     bundle file isn't adequate, you can specify an alternate file
     using the --cacert option.
    If this HTTPS server uses a certificate signed by a CA represented in
     the bundle, the certificate verification probably failed due to a
     problem with the certificate (it might be expired, or the name might
     not match the domain name in the URL).
    If you'd like to turn off curl's verification of the certificate, use
     the -k (or --insecure) option.
    Error: Failed to download resource "jbig2dec"
    Download failed: https://downloads.sourceforge.net/project/jbig2dec/jbig2dec/0.11/jbig2dec-0.11.tar.gz

Same problem installing jbig2dec.

Output of `brew config` is
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 1580f8b8b4beabc95af4b527e4a832970958e26d
Last commit: 63 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit sandybridge
OS X: 10.10.2-x86_64
Xcode: N/A
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
X11: 2.7.6 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.6.0_65

and of `brew doctor` is

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your XQuartz (2.7.6) is outdated
Please install XQuartz 2.7.7:
  https://xquartz.macosforge.org

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:

    brew install xz

Run `brew missing` for more details.

and there is no log for the formula in `~/Library/Logs/Homebrew/`

Thanks, and thanks for homebrew!

**Comment by xu-cheng** [comment]
SourceForge's SSL is down at the moment.

**Comment by mistydemeo** [comment]
This is a known issue; it should be resolved on Sourceforge's side in the near future.

**Comment by gnzlbg** [comment]
It might be better to leave one of this issues open, instead of closing them before they are fixed. I almost reported this again.
