### ISSUE TITLE
s3cmd formula error due to invalid certificate

### ISSUE THREAD

**Issue by ricardodelagarza** [Homebrew/homebrew#36907]
While trying to install s3cmd using brew install s3cmd, I had the following error:

==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/s3cmd-1

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
of Certificate Authority (CA) public keys (CA certs). If the default
bundle file isn't adequate, you can specify an alternate file
using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
the bundle, the certificate verification probably failed due to a
problem with the certificate (it might be expired, or the name might
not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
the -k (or --insecure) option.
Error: Failed to download resource "s3cmd"
Download failed: https://downloads.sf.net/project/machomebrew/Bottles/s3cmd-1.5.0.yosemite.bottle.2.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://downloads.sourceforge.net/project/s3tools/s3cmd/1.5.

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
of Certificate Authority (CA) public keys (CA certs). If the default
bundle file isn't adequate, you can specify an alternate file
using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
the bundle, the certificate verification probably failed due to a
problem with the certificate (it might be expired, or the name might
not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
the -k (or --insecure) option.
Error: Failed to download resource "s3cmd"
Download failed: https://downloads.sourceforge.net/project/s3tools/s3cmd/1.5.0/s3cmd-1.5.0.tar.gz

**Comment by DomT4** [comment]
Sourceforge had some downtime. It should be available again soon, if it isn't already.
