### ISSUE TITLE
Should openssh install a version of sshd-keygen-wrapper?

### ISSUE THREAD

**Issue by Julian** [Homebrew/homebrew#36911]
Would it be reasonable to ship a version of `/usr/libexec/sshd-keygen-wrapper` for the `openssh` package, allowing users to set up the `sshd` if they prefer to use the updated one over the one installed OOTB. Obviously this would be opt-in, and probably should be completely manual, but for reference, I've created `/usr/local/sbin/sshd-keygen-wrapper` with contents:

```
#!/bin/sh

[ ! -f /usr/local/etc/ssh_host_key ]     && /usr/local/bin/ssh-keygen -q -t rsa1 -f /usr/local/etc/ssh_host_key     -N "" -C "" < /dev/null > /dev/null 2> /dev/null
[ ! -f /usr/local/etc/ssh_host_rsa_key ] && /usr/local/bin/ssh-keygen -q -t rsa  -f /usr/local/etc/ssh_host_rsa_key -N "" -C "" < /dev/null > /dev/null 2> /dev/null
[ ! -f /usr/local/etc/ssh_host_dsa_key ] && /usr/local/bin/ssh-keygen -q -t dsa  -f /usr/local/etc/ssh_host_dsa_key -N "" -C "" < /dev/null > /dev/null 2> /dev/null

exec /usr/local/sbin/sshd $@
```

which was necessary even after modifying the sshd Launch Daemon.

**Comment by jacknagel** [comment]
openssh is packaged in https://github.com/Homebrew/homebrew-dupes, so this ticket should be reopened there.

**Comment by Julian** [comment]
Erm, whoops, apologies.
