### ISSUE TITLE
Conditional dependencies improperly handled

### ISSUE THREAD

**Issue by TingPing** [Homebrew/homebrew#36915]
In gtk+3 for example it has this dependency: ```depends_on "at-spi2-atk" if build.with? "x11"```

The issue is that if you build ```--without-x11``` it will still do the checks for it to be installed which
will fail if you do not have XQuartz installed (which you shouldn't need).

**Comment by jacknagel** [comment]
Conditional (vs. `=> :optional` and `=> :recommended`) dependencies are broken by their very nature, but if you `brew install gtk+3 --without-x11`, Then `depends_on "at-spi2-atk" if build.with? "x11"` will not activate. The X11 requirement is probably coming from a transitive dependency. See https://github.com/Homebrew/homebrew/issues/36542 and https://github.com/Homebrew/homebrew/pull/36566.

**Comment by TingPing** [comment]
Ok thanks. Do you have any more info on this, has work on it started or just ideas:

>it will have to wait until the new dependency implementation is finished (which, not coincidentally, will have first class support for this type of dependency).
