### ISSUE TITLE
When sourceforge is down everything gets installed from source

### ISSUE THREAD

**Issue by gnzlbg** [Homebrew/homebrew#36928]
When a service that homebrew heavily depends on, like sourceforge, is down, homebrew should (in my opinion):

- Check this: is sourceforge down?

If sourceforge is down, 
- report to the user that:
  - sourceforge is down, 
  - some formulas (whose source is not in sourceforge) can be installed from source.
- Ask the user:
  - Do you want to install/upgrade that formula (or the whole system) now, or try again later?  
  - Provide a way for the user to check if sourceforge is down: e.g. a link to sourceforge service status page.

Right now: if sourceforge is down, everything is automatically compiled from source (if the sources are available, otherwise something will just fail). Consider a user doing a `brew upgrade`. In the normal scenario, this takes a couple of minutes with almost no CPU time. When everything gets pulled from source, we are talking about possibly hours, with the CPU maxed out.

Finally, multiple issues are reported per package (since each issue is closed as: "sourceforge is down").

**Comment by pbosetti** [comment]
Sourceforge "disaster recovery" mode is down since more than one week... Wouldn't it be nice to replace curl with PhantomJS for downloading bottles?

**Comment by mikemcquaid** [comment]
We are working on this. The solution is not checking is SourceForge is down but instead moving our binary packages elsewhere.

**Comment by pbosetti** [comment]
Indeed! cleverly simple 😉

**Comment by gnzlbg** [comment]
Yes.. until that service goes down temporarily too...

**Comment by pbosetti** [comment]
It might be a subjective sensation, but in my experience sf is not ranking very high in terms of service reliability.

**Comment by mikemcquaid** [comment]
@gnzlbg Yes and when GitHub goes down you can't `brew update` too. We'll review a PR for this; it's really a much harder problem than just describing something in an issue. Again, we're working on it and for every comment in threads like this I have to read it'll take me longer to get it done.
