### ISSUE TITLE
Homebrew should have a .pkg installer

### ISSUE THREAD

**Issue by iankronquist** [Homebrew/homebrew#36945]
`curl | ruby` may be normal in the ruby community, but it looks incredibly sketchy to anyone else.
A .pkg installer is the recommended way to install software like homebrew on macs (if I understand correctly). It is also the way most users are acquainted with.

**Comment by DomT4** [comment]
You can already do ` cd /usr/local && git clone https://github.com/Homebrew/homebrew.git ` if that makes you feel any easier about installation. ` .pkg ` have problems of their own, primarily around the fact `.pkg` files have pretty free reign to do whatever and the user has little idea what that whatever is until it has finished.

**Comment by jacknagel** [comment]
This isn't really feasible right now, given that formula updates happen in the same repository as the application code.

There are some alternative ways to install described here: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Installation.md
