### ISSUE TITLE
gcc -v fails with gcc: warning: couldn't understand kern.osversion '14.1.0 Using built-in specs.

### ISSUE THREAD

**Issue by Arkioss** [Homebrew/homebrew#36944]
Until now I've used the Xcode version of gcc, but now I need OpenMP which Xcode sadly doesn't support. I've tried installing brew gcc with

    brew install gcc --without-multilib

However, when running "gcc -v" I get the error:

    gcc: warning: couldn't understand kern.osversion '14.1.0
    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-apple-darwin13.0.0/4.9.0/lto-wrapper
    Target: x86_64-apple-darwin13.0.0
    Configured with: ../gcc-4.9-20130929/configure --enable-languages=c,c++,fortran
    Thread model: posix
    gcc version 4.9.0 20130929 (experimental) (GCC) 

brew update gives me

    Already up-to-date.
and brew doctor

    Your system is ready to brew.

I've tried searching for similar issues, but have only found suggestions that I need to install CLT (which I already have and are updated) or that I might have an old version of Xcode also installed (which I don't think is the case).

I'm running OSX 10.10.2

It should be said that the first time I ran brew doctor it gave me a long list of things to fix. Among them were relics of an old MacPorts install and GEOS (http://trac.osgeo.org/geos/) unbrewed header files. I cleaned up what brew doctor asked me to, and tried doing a

    brew reinstall gcc --without-multilib

But I get the exact same error as before.

Gist here: https://gist.github.com/a38cc8a473d40d958f89

This is my first post, so if there's any information that you need or steps I need to take that I haven't tried yet, just let me know.

**Comment by mistydemeo** [comment]
Homebrew installs GCC with a version suffix; it would be installed as `gcc-4.9`, rather than `gcc`. Does `gcc-4.9` work?

The version output of your GCC version shows that it's a GCC 4.9.0 prerelease from 2013, which Homebrew hasn't distributed for quite some time.

**Comment by Arkioss** [comment]
Many thanks for the swift response!

Yes, gcc-4.9 works and g++-4.9 (which is really the one I need) is now compiling perfectly as well.

Just for good measure, is there a way to clean up that old gcc installation so it doesn't cause any more conflicts in the future? Running which gcc gives me

    /usr/local/bin/gcc

Where which gcc-4.9 gives me

    /usr/local/bin/gcc-4.9

Can I safely remove that now obsolete gcc folder?

**Comment by jacknagel** [comment]
Yes, you can remove it (it's a file rather than a directory though), though you may want to figure out how it got there first.
