### ISSUE TITLE
cmake v3.1.2: Bottled Mavericks download fails - SHA1 mismatch

### ISSUE THREAD

**Issue by mw9** [Homebrew/homebrew#36969]
Screen dump:

    ==> Downloading https://homebrew.bintray.com/bottles/cmake-3.1.2.mavericks.bottle.tar.gz
    ######################################################################## 100.0%
    Error: SHA1 mismatch
    Expected: 9b363c8694d38348f7ab647abae848850aba4236
    Actual: 78274ae1e05f1509a961609523234cac41fd6074
    Archive: /Library/Caches/Homebrew/cmake-3.1.2.mavericks.bottle.tar.gz
    To retry an incomplete download, remove the file above.

The downloaded file appears to be valid, it satisfies `gzip -t`.

**Comment by DomT4** [comment]
It's the Yosemite [bottle](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cmake.rb#L29), rather than the Mavericks one, which is the issue.

```
 78274ae1e05f1509a961609523234cac41fd6074  /Users/Dominyk/Downloads/cmake-3.1.2.mavericks.bottle.tar.gz
```

Give the maintainers a bit and they'll fix it.

**Comment by mikemcquaid** [comment]
Should be fixed now, try `brew fetch --retry cmake`. Thanks for the report!

**Comment by mw9** [comment]
That poured perfectly, thanks.
