### ISSUE TITLE
boot2docker cask is a duplicate name in Homebrew-cask

### ISSUE THREAD

**Issue by zchee** [Homebrew/homebrew#36968]
boot2docker cask is a duplicate name in Homebrew-cask.

[homebrew-cask/Casks/boot2docker.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/boot2docker.rb)
[Homebrew/homebrew/Library/Formula/boot2docker.rb](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boot2docker.rb)

`homebrew-cask/Casks/boot2docker.rb` is will install the boot2docker.
`Homebrew/homebrew/Library/Formula/boot2docker.rb` is will install the boot2docker-cli.

I think that there is better to rename the [homebrew-cask/Casks/boot2docker.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/boot2docker.rb) cask from `boot2docker` to `boot2docker-cli`.
What do you think ?

**Comment by tdsmith** [comment]
Thanks for the report! There are several overlaps; you can choose which one to install by using either `brew install` or `brew cask install` as appropriate.
