### ISSUE TITLE
mp3splt not working - Library not loaded: dylib

### ISSUE THREAD

**Issue by marlun** [Homebrew/homebrew#36966]
When I try to use mp3splt after installing it (which didn't produce any errors) I get the following

    $ mp3splt -t 4.10 1.mp3
    dyld: Library not loaded: /usr/local/lib/libltdl.7.dylib
      Referenced from: /usr/local/lib/libmp3splt.0.dylib
      Reason: image not found
    Trace/BPT trap: 5

Not sure about what is wrong.

**Comment by mikemcquaid** [comment]
`brew update`, `brew install libtool` and 88149b8 should fix this.

**Comment by DomT4** [comment]
It works okay here, including from bottle. Try ` brew update && brew upgrade && brew reinstall libtool `.

**Comment by DomT4** [comment]
Ah, Mike beat me to the comment. Apologies for my double post :smile:

**Comment by marlun** [comment]
Worked like a charm. Very fast response, thanks! :smile:
