### ISSUE TITLE
glib fails to build on 10.7.5

### ISSUE THREAD

**Issue by reicheltd** [Homebrew/homebrew#36978]
https://gist.github.com/anonymous/42a8a5c2d7a7491116d3
    
    ==> Installing dependencies for mpd: glib, ffmpeg
    ==> Installing mpd dependency: glib
    ==> Downloading http://ftp.gnome.org/pub/gnome/sources/glib/2.42/glib-2.42.1.tar.xz
    Already downloaded: /Library/Caches/Homebrew/glib-2.42.1.tar.xz
    ==> Downloading https://gist.githubusercontent.com/jacknagel/af332f42fae80c570a77/raw/7b5fd0d2e6554e9b770729fddacaa2d648327644/glib-hardcoded
    Already downloaded: /Library/Caches/Homebrew/glib--patch-78bbc0c7349d7bfd6ab1bfeabfff27a5dfb1825a.diff
    ==> Downloading https://gist.githubusercontent.com/jacknagel/9835034/raw/371fd57f7d3823c67dbd5bc738df7ef5ffc7545f/gio.patch
    Already downloaded: /Library/Caches/Homebrew/glib--patch-b947912a4f59630c13e53056c8b18bde824860f4.patch
    ==> Patching
    patching file gio/gdbusprivate.c
    patching file gio/xdgmime/xdgmime.c
    patching file glib/gutils.c
    patching file gio/Makefile.am
    patching file gio/Makefile.in
    patching file gio/gnextstepsettingsbackend.c
    patching file gio/gnextstepsettingsbackend.m
    ==> ./configure --disable-maintainer-mode --disable-silent-rules --disable-dtrace --disable-libelf --prefix=/usr/local/Cellar/glib/2.42.1 --l
    ==> make
    make[4]: *** Waiting for unfinished jobs....
    make[3]: *** [all-recursive] Error 1
    make[2]: *** [all] Error 2
    make[1]: *** [all-recursive] Error 1
    make: *** [all] Error 2

**Comment by jacknagel** [comment]
The logs you posted are for `mpd`, but the formula that failed was `glib`. Please `brew gist-logs glib`

**Comment by reicheltd** [comment]
https://gist.github.com/anonymous/42a8a5c2d7a7491116d3

**Comment by shrx** [comment]
Not sure if it's the same issue, but `brew install glib --build-from-source` fails on OS X 10.10.2: https://gist.github.com/e9b6ea7753de82649c90

**Comment by jacknagel** [comment]
@shrx it's not the same; pelase open a different issue (but try `brew reinstall libffi` first)

**Comment by reicheltd** [comment]
@jacknagel I did a `brew reinstall libffi` and a `brew reinstall glib`. This worked! Thx
