### ISSUE TITLE
Newlisp fails to download

### ISSUE THREAD

**Issue by tjl** [Homebrew/homebrew#36972]
In trying to install newlisp, it fails to download.

Installing newlisp
==> Downloading http://www.newlisp.org/downloads/newlisp-10.6.0.tgz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "newlisp"
Download failed: http://www.newlisp.org/downloads/newlisp-10.6.0.tgz

Checking the newlisp downloads at http://www.newlisp.org/downloads/ it seems like it should be,

http://www.newlisp.org/downloads/newlisp-10.6.2.tgz

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by tjl** [comment]
I've opened a pull request at 

https://github.com/Homebrew/homebrew/pull/36975

It passes tests and the audit.

**Comment by jacknagel** [comment]
PR was pulled
