### ISSUE TITLE
uninstall instruction deleted default Ruby from OS X Yosemite (10.10.2)

### ISSUE THREAD

**Issue by gigaimage** [Homebrew/homebrew#36983]
I used (as suggested) : rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
and default  Ruby (Ruby 2.0.0p481 I guess!) that comes with mac (OSX Y 10.10.2) is also gone!!!

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" 
returns 
-bash:/usr/local/bin /bin/ruby: No such file or directory.

How to get it back?

**Comment by DomT4** [comment]
After you removed Homebrew did you close your Terminal application and reopen it before doing ` ruby ` again? It can take that to refresh where the ` $PATH ` expects to find things.

What's the output in your Terminal of ` which /usr/bin/ruby ` and/or ` ls -l /usr/bin | grep ruby `?

**Comment by gigaimage** [comment]
Thanks! please close this issue.
