### ISSUE TITLE
freeradius-server plist suggestion

### ISSUE THREAD

**Issue by dpenezic** [Homebrew/homebrew#36988]
Hi,
I do not have enough knowledge of homebrew to made follow change.

Add plist for start freeradius-server  as follow:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>KeepAlive</key>
  <true/>
  <key>Label</key>
  <string>homebrew.mxcl.freeradius-server</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/bin/radiusd</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>WorkingDirectory</key>
  <string>/usr/local/var</string>
</dict>
</plist>

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by jacknagel** [comment]
Would review a pull request per the above.
