### ISSUE TITLE
Homebrew Install Problem

### ISSUE THREAD

**Issue by McDandal** [Homebrew/homebrew#37005]
Hey, I have been looking around for a similar problem, but sinceI cannot find one, here is my question.

I am quite new to Homebrew, and was following the directions listed on the page. 

Cellar/wget/1.16.1/bin/wget
wget: missing URL
Usage: wget [OPTION]... [URL]... 

What am I supposed to use for URL?

**Comment by lethosor** [comment]
The installation command is at the bottom of the page:
```sh
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

**Comment by DomT4** [comment]
Yeah, as above. There's a PR open about the site at the moment in an effort to make the install script a little clearer in terms of positioning and surrounds, so it's being worked on :).

**Comment by McDandal** [comment]
I did as lethosor put, but was I supposed to go down the line of instructions typing everything there? Like, the Cellar things? Or did the command at the bottom do it all?

**Comment by McDandal** [comment]
Homebrew installs packages to their own directory and then symlinks their files into /usr/local.

this one specifically

**Comment by DomT4** [comment]
No, you just pop open your Terminal application and copy:

```bash
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

And then it'll provide you step-by-step instructions, but it's mostly automated so you shouldn't have to do too much :).

**Comment by lethosor** [comment]
No, those are examples. (Also, all example commands are prefixed with the `$` prompt - `Cellar/wget/1.15/bin/wget` is not a command).

**Comment by McDandal** [comment]
Well. You guys are awesome. Thanks for answering my newbie questions with haste!

**Comment by DomT4** [comment]
No worries at all! Feel free to create another issue (or comment in this one) if you run into anything else! :smiley_cat:
