### ISSUE TITLE
Warning: You have a non-Homebrew 'pkg-config' in your PATH:

### ISSUE THREAD

**Issue by alduxvm** [Homebrew/homebrew#37017]
Hi! 

I was having problems with numpy and opencv, so I wanted to start fresh, so, I uninstall homebrew and the cellar, then reinstall, and when running the doctor I have this:

```
Warning: You have a non-Homebrew 'pkg-config' in your PATH:
  /usr/bin/pkg-config

`./configure` may have problems finding brew-installed packages using
this other pkg-config.
```

My $PATH is:

```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```

And my brew --config:

```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 49a39fe2456acea77591dd6632bb52abe7e165fa
Last commit: 34 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit ivybridge
OS X: 10.10.2-x86_64
Xcode: 6.1.1
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.6.0_65
```

I do not know what to do to remove the warning...

Cheers!

**Comment by mistydemeo** [comment]
Do you know what installed the `/usr/bin/pkg-config` file? If not, it should probably be removed; it may interfere with Homebrew, as noted by the `doctor` warning.

**Comment by alduxvm** [comment]
I just remove the warning by `brew install pkg-config`

now my brew doctor states: 

```
Your system is ready to brew.
```

I do not know what installed originally the pkg-config.. should I be concerned??

cheers!

**Comment by tdsmith** [comment]
I wouldn't be concerned. Let us know if we can help with anything else!

**Comment by mistydemeo** [comment]
You may still need to remove the `/usr/bin/pkg-config` file; it can interfere with builds. However, if you don't encounter any issues, you can leave it.

**Comment by alduxvm** [comment]
Thanks a lot everyone! this is really nice help :)
