### ISSUE TITLE
libgphoto2 failed to build on 10.10.2

### ISSUE THREAD

**Issue by lorebiga** [Homebrew/homebrew#37018]
I can't upgrade to 2.5.7.
I guess it depends on a few unbrewed packages I installed in the past (ImageMagick, Ghostscript, ntfds-3g...)
I'd like to get rid of them (and possibly install the brewed versions), but not really sure how to.

Thanks for helping.

https://gist.github.com/76aa57093df8638e8d4b

**Comment by asparagui** [comment]
brew deps libgphoto2

should get you started, or do you need to remove more things?

**Comment by lorebiga** [comment]
I mean that upgrading to 2.5.7 results in a failure (see the gist), maybe because of incompatibility with unbrewed packages (which I'd like to get rid of).

The dependencies of libgphoto2 seem all ok, but thanks for pointing me there anyway.

**Comment by ashea20** [comment]
So I just got an error while trying to install wine through homebrew... this is my first time really using the command lines and ive been going through some tutorials but bottom line is i have ended up here and was wondering if anyone knows what this error is?
![screen shot 2015-03-01 at 7 59 39 pm](https://cloud.githubusercontent.com/assets/11263897/6434807/83373918-c04d-11e4-8427-396a1ab5dffe.png)

**Comment by lorebiga** [comment]
FYI, I managed to update libgphoto2.
'brew upgrade' wouldn't work, so I tried uninstalling and reinstalling, and this worked.
@ashea20 I had a msg similar to yours, to you may try the same approach...
