### ISSUE TITLE
Bottles failing for new formulae in Versions

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew#37043]
Reported this to Mike already, so it's a known thing, but thought it may be worth flagging here as well so we can keep track of it.

New formulae for Homebrew-Versions (and potentially other taps too) are currently having their downstream bottle build fail. This seems to have started at some point in the last week, but I haven't yet completely narrowed down the break point. We managed to locally resolve the issues I was seeing on my machine around ` Error: No available formula for xxx ` as displayed on the bot for new formulae by running a ` brew tap --repair `, but that could have been luck/unrelated.

This is the failure for Lua53's downstream [bottle build](http://bot.brew.sh/job/Homebrew%20Bottles/16113/console) from the test-bot:

```
cp /Users/brew/Jenkins/jobs/Homebrew Versions Pull Requests/configurations/axis-version/mavericks/builds/2015-02-22_01-43-48/archive/lua53-5.3.0.mavericks.bottle.rb /Users/brew/Jenkins/jobs/Homebrew Versions Pull Requests/configurations/axis-version/mavericks/builds/2015-02-22_01-43-48/archive/lua53-5.3.0.mavericks.bottle.tar.gz /Users/brew/Jenkins/jobs/Homebrew Versions Pull Requests/configurations/axis-version/mountain_lion/builds/2015-02-22_01-43-48/archive/lua53-5.3.0.mountain_lion.bottle.rb /Users/brew/Jenkins/jobs/Homebrew Versions Pull Requests/configurations/axis-version/mountain_lion/builds/2015-02-22_01-43-48/archive/lua53-5.3.0.mountain_lion.bottle.tar.gz /Users/brew/Jenkins/jobs/Homebrew Versions Pull Requests/configurations/axis-version/yosemite/builds/2015-02-22_01-43-48/archive/lua53-5.3.0.yosemite.bottle.rb /Users/brew/Jenkins/jobs/Homebrew Versions Pull Requests/configurations/axis-version/yosemite/builds/2015-02-22_01-43-48/archive/lua53-5.3.0.yosemite.bottle.tar.gz /Users/brew/Jenkins/jobs/Homebrew Bottles/workspace
git am --abort 2>/dev/null 
git rebase --abort 2>/dev/null 
git checkout -f master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git reset --hard origin/master
HEAD is now at 7fe20ae appledoc22: add 2.2.1 bottle.
brew update
Already up-to-date.
brew pull --clean https://github.com/Homebrew/homebrew-versions/pull/640
==> Applying patch
Applying: lua53 5.3.0 (new formula)
==> Patch changed:
 lua53.rb | 152 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 152 insertions(+)
Error: No available formula for lua53 
Build step 'Execute shell' marked build as failure
```

Lua53's actual build process passed the test-bot, as can be seen [here](http://bot.brew.sh/job/Homebrew%20Versions%20Pull%20Requests/183/version=mavericks/console).

If you pull the formulae locally with ` brew pull --bottle xxx ` and then open the file, you see it has a bottle block, but for SF:

```ruby
  bottle do
    root_url "https://downloads.sf.net/project/machomebrew/Bottles/versions"
    sha1 "a95be0cb5515542f1e13b24eb41f484a0f0ad218" => :yosemite
    sha1 "0656a67772ae176d9a21f6994670874f4c6f1a82" => :mavericks
    sha1 "01c0f55890fb661f912510c8eb3feb1084dae651" => :mountain_lion
  end
```

If you then do ` brew fetch --force-bottle lua53 ` you get ` No available formula for lua53 `. If you do ` brew fetch --force-bottle lua53.rb ` (inside the versions repo) you get:

```ruby
==> Fetching lua53 from homebrew/homebrew-versions
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/versions/lua53-5.3.0.yosemite.bottle.tar.gz
######################################################################## 100.0%
Downloaded to: /Library/Caches/Homebrew/lua53-5.3.0.yosemite.bottle.tar.gz
SHA1: a95be0cb5515542f1e13b24eb41f484a0f0ad218
SHA256: cc1503ad8c8e19b516a36eb8285793953bf15bfa5c42f293957660fc94ce94f1
```

If at this point you do ` rm /Library/Caches/Homebrew/lua53-5.3.0.yosemite.bottle.tar.gz && brew tap --repair ` you can then do ` brew fetch lua53 ` fine without issue. *(Although it's still pulling from SF)*.

No huge pressure on a fix. Just wanted to create this issue so it's easier to keep tabs on, and because the test bot ditches reports relatively quickly (understandably).

**Comment by DomT4** [comment]
Thanks for looking into this @mikemcquaid. Didn't want to pressure you into an immediate fix, just wanted to put the reports somewhere since the Bot bins them relatively quickly - Appreciate the commit on the issue though.

Looks like we now have a slightly different error, which is a somewhat strange one:

```
brew pull --clean https://github.com/Homebrew/homebrew-versions/pull/640
==> Applying patch
Applying: lua53 5.3.0 (new formula)
Error: Failure while executing: brew tap --repair
Error: Failure while executing: brew pull --clean https://github.com/Homebrew/homebrew-versions/pull/640
Build step 'Execute shell' marked build as failure
```

**Comment by mikemcquaid** [comment]
Actually fixed by https://github.com/Homebrew/homebrew/commit/be5dafdc363454cace3bab286a14f64946f28b9e now.

**Comment by DomT4** [comment]
Thanks! I was just about to comment that the bottles seemed to have been fixed by your commits today. Massively appreciated! :smiley_cat:

**Comment by mikemcquaid** [comment]
@DomT4 ~~today~~ a few minutes before my comment but yeh :wink:

**Comment by DomT4** [comment]
@mikemcquaid I think I triggered a test build in Versions literally a few seconds after your last commits on the issue, so it just seemed to me like it'd been fixed earlier :wink:. I'm currently having to manually confirm some bottle additions on Bintray's website, is that expected?

**Comment by mikemcquaid** [comment]
@DomT4 If you use `brew pull` you shouldn't have to ever do it manually. The additions on the website is  only for currently unbottled stuff as deciding to keep bottles for a newly bottled package should be a somewhat manual process (that `brew pull` does for you).

**Comment by DomT4** [comment]
@mikemcquaid Ah, maybe I'm just being too impatient with ` brew pull ` at times then. I'm using ` brew pull ` with the ` --bottle ` switch when bottles are appropriate, but sometimes I get a ` Permissions Denied ` message. I verified my API and username several hundred times, but run into that every now and again.

**Comment by mikemcquaid** [comment]
Yeh, it's probably the bottles haven't uploaded yet.

**Comment by DomT4** [comment]
Ah. I shall work on having a little more patience then :smile_cat:, Thanks!
