### ISSUE TITLE
previous version of hadoop

### ISSUE THREAD

**Issue by prakashn27** [Homebrew/homebrew#37090]
is there any way to install hadoop version 2.5.1 by using brew?

**Comment by jacknagel** [comment]
Old versions go into homebrew-versions; looks like someone has opened a PR for 2.5.2: https://github.com/Homebrew/homebrew-versions/pull/587

**Comment by prakashn27** [comment]
Thanks jacknagel. but the pull request has not been merged i guess. 252 is not getting listed in brew.
