### ISSUE TITLE
Brew commands fail because of wget formula

### ISSUE THREAD

**Issue by iBeliever** [Homebrew/homebrew#37113]
After running `brew update` today (which I haven't run in a long time), several brew commands, including `brew doctor`, `brew uninstall wget`, and `brew upgrade wget`, fail because Homebrew encounters a syntax error in `/usr/local/Library/Formula/wget.rb`.

Here is the output of several `brew` commands: https://gist.github.com/iBeliever/b83497b06e1b124d74ac

**Comment by xu-cheng** [comment]
Should fix in https://github.com/Homebrew/homebrew/commit/8c26246591d087adef01352404557c9a50787995. Please run `brew update`.

**Comment by iBeliever** [comment]
Yes, that commit fixed it. Thanks for the quick response!
