### ISSUE TITLE
python3 --HEAD gets ${xy} wrong

### ISSUE THREAD

**Issue by bukzor** [Homebrew/homebrew#37118]
This function needs to return "3.5" in the case of --HEAD:

```
  def xy                                                                                                            
    version.to_s.slice /(3.\d)/                                                                                    
  end                                                                                                               
```

Otherwise, the site-packages end up in a "/python/" which causes all sorts of errors.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by bukzor** [comment]
My ruby-foo isn't strong enough to correct the function. I've simply commented out the current body and replaced it with `3.5`.
