### ISSUE TITLE
libgphoto2 failed to build on wine install

### ISSUE THREAD

**Issue by Quantumboost** [Homebrew/homebrew#37126]
This does not appear to occur on my machine while running "brew install libgphoto2", but does when performing "brew install wine" under "Installing wine dependency: libgphoto2" during the make install step.

https://gist.github.com/anonymous/e801f2e4f08535fb0a42

**Comment by tdsmith** [comment]
Failure is
> libtool: compile:  clang -DHAVE_CONFIG_H -I. -DLOCALEDIR=\"/usr/local/Cellar/libgphoto2/2.5.7/share/locale\" -DIOLIBS=\"/usr/local/Cellar/libgphoto2/2.5.7/lib/libgphoto2_port/0.12.0\" -D_GPHOTO2_INTERNAL_CODE -I. -I/usr/local/Cellar/libusb/1.0.19/include/libusb-1.0 -D_DARWIN_C_SOURCE -Wall -Wmissing-declarations -Wmissing-prototypes -c libusb1/libusb1.c  -fno-common -DPIC -o .libs/usb1_la-libusb1.o
> libusb1/libusb1.c:70:20: error: static declaration of 'libusb_strerror' follows non-static declaration
static const char *libusb_strerror(int r)
                   ^
/usr/local/Cellar/libusb/1.0.19/include/libusb-1.0/libusb.h:1313:26: note: previous declaration is here
const char * LIBUSB_CALL libusb_strerror(enum libusb_error errcode);

configure says "checking for libusb_strerror in -lusb-1.0... no" which is wrong, I guess. It looks like we didn't capture that config.log.

Could you run the install with the -d switch and when it fails, open a shell in the build environment from the menu, copy libgphoto2_port/config.log somewhere, and then gist that?

**Comment by ashea20** [comment]
So I just got an error while trying to install wine through homebrew... this is my first time really using the command lines and ive been going through some tutorials but bottom line is i have ended up here and was wondering if anyone knows what this error is?
![screen shot 2015-03-01 at 7 56 00 pm](https://cloud.githubusercontent.com/assets/11263897/6434797/4f339ff8-c04d-11e4-92fa-22922acde43b.png)

**Comment by whollypetfood-dot-com** [comment]
Has anyone come up with a workaround for this yet?

**Comment by thenexxuz** [comment]
This seems to work for me:

```
brew link --overwrite libusb
brew install libgphoto2
brew install wine
```

It's still compiling I will update when it's done.

**Comment by lantrix** [comment]
@thenexxuz this worked for me too

**Comment by tdsmith** [comment]
Assuming that this is resolved by the above suggestion. Thanks!

**Comment by Tidus26** [comment]
When I try to overwrite libusb it says "Error: No such keg: /usr/local/Cellar/libusb" ... Prior, I was just trying to install wine and I got the "Error: Failed to download resource "libusb"
