### ISSUE TITLE
Ansible 1.8.3 has a breaking bug when using ec2 core module

### ISSUE THREAD

**Issue by kostecky** [Homebrew/homebrew#37125]
Hi Folks,

Ansible 1.8.3 is broken when using the ec2 cloud core module due to https://github.com/ansible/ansible-modules-core/issues/808.

This has been corrected in 1.8.4 which was released shortly after. Can the brew formula be updated accordingly @ https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ansible.rb

**Comment by mikemcquaid** [comment]
> This has been corrected in 1.8.4 which was released shortly after. Can the brew formula be updated accordingly @ https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ansible.rb

Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by kostecky** [comment]
Thanks @mikemcquaid. I'll see if I can take a look at this when I have a moment.
