### ISSUE TITLE
brew go should install godoc into bin

### ISSUE THREAD

**Issue by lloydde** [Homebrew/homebrew#37133]
brew go should install godoc into bin.

brew users expect as complete an experience as any distribution and the binary downloads from golang.org include bin/godoc:

```
$ pkgutil --expand go1.4.2.darwin-amd64-osx10.8.pkg tmp
$ cd tmp/com.googlecode.go.pkg/
$ lsbom Bom | fgrep "/bin/" | cut -f 1
./usr/local/go/bin/go
./usr/local/go/bin/godoc
./usr/local/go/bin/gofmt
./usr/local/go/misc/nacl/testdata/bin/placeholder
```

I've reviewed #25210 and the earlier #23281. I also considered golang/go#6654
discussion https://groups.google.com/forum/#!topic/golang-nuts/L9hHfsQ6_QE
and blog posts like https://ruin.io/2014/godoc-homebrew-go/ and http://www.adamisrael.com/blog/2014/11/13/making-os-x-go-and-brew-play-happy/ .

This will continue to be an issue particularly because documentation and blog posts assume it is installed. Few people go back to look at the homebrew package info.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by drewwells** [comment]
Why even build go? There are precompiled binaries that include `godoc` out of the box on golang.org: https://golang.org/dl/

Only thing you lose is cross-compiling, which is much easier managed with `goxc` than trying to do it yourself with a brew installed go.

**Comment by mikemcquaid** [comment]
@drewwells because people like to use Homebrew and easily handle their updates.

**Comment by drewwells** [comment]
I mean why build go from source, when there are precompiled binaries with `godoc` already on the website. `brew install go` pulls the tarball from golang.org and lays that in `/usr/local/opt/go/`

**Comment by drewwells** [comment]
Also, 1.5 will require go to build from source so this setup will get further complicated to build from source. https://github.com/Homebrew/homebrew/blob/master/Library/Formula/go.rb#L3

**Comment by mikemcquaid** [comment]
The above was a gentle nudge. I'd rather you didn't post "why even use Homebrew?" on the Homebrew issue tracker. There's plenty of other places on the internet for those discussions.

**Comment by drewwells** [comment]
`Why even build go?` 

I was not referring to Homebrew, but the process of compiling go. Sorry if that was unclear.

I took a stab at installing godoc with the current bootstrap process. There's several environment variables that are needed to get that working which isn't setup as part of any bootstrapping right now. It's probably simpler to use the compiled tarballs than spin up a mini Go environment in the bootstrap script to get godoc installed in there.

**Comment by DomT4** [comment]
> Also, 1.5 will require go to build from source so this setup will get further complicated.

Pretty sure we'll be able to use a Mountain Lion or Mavericks bottle (Whichever is the lowest supported-with-bottles OS X when 1.5 lands) to bootstrap the 1.5 build. That was my general line of thought when I scribbled the notation there anyway.

**Comment by drewwells** [comment]
What benefits are there to building over pulling the built binaries? I'm thinking we can skip building entirely and use the prebuilt. The one concern is cross-building, but `goxc` has made that process very easy to do and even builds to the toolchain for you!

**Comment by DomT4** [comment]
* We can support a wider range of setups and cater to unusual errors/builds quicker than Go can.
* We can verify the contents of the bottle.
* We're largely protected against upstream repacks suddenly breaking everyone's compile.
* Not everyone loves binaries.
* People can be wary about Google. *(Rightly or wrongly)*

Various reasons. Package managers remain popular, and all three OS X package managers support building from source if desired, and Homebrew supports self-generated binaries for people who don't want to use x location to get y tool when they can just do ` brew install ducks `, and know ` ducks ` will get updates without any further work from them.

**Comment by drewwells** [comment]
Fair enough.

This will install godoc into $GOPATH. Requiring go be in the $PATH and
$GOPATH be defined. $GOROOT is not necessary

system "go", "install", "code.google.com/p/go.tools/cmd/godoc"

**Comment by DomT4** [comment]
Have a PR ready locally already :). Just testing it a bit prior to pushing.

**Comment by DomT4** [comment]
#37159

**Comment by lloydde** [comment]
Thanks @DomT4!

**Comment by lloydde** [comment]
@DomT4 , @mikemcquaid this might need to be reopened, because 'go vet' does not work.

ENV
$ brew --version
0.9.5
$ brew update
Updated Homebrew from 7e031275 to d94e7fa5

$ brew install go
$ go vet
can't load package: package .: no buildable Go source files in /usr/local/Library/Formula

$ brew install --build-from-source go
$ go vet
can't load package: package .: no buildable Go source files in /usr/local/Library/Formula
$ export PATH=$PATH:/usr/local/opt/go/libexec/bin
$ go vet
can't load package: package .: no buildable Go source files in /usr/local/Library/Formula

**Comment by mistydemeo** [comment]
This is normal behaviour for `go vet`. You need to either be in the working directory of the project you want to vet, or specify the import path of a package that's in your `GOROOT` or `GOPATH`.

**Comment by lloydde** [comment]
Phew, thanks @mistydemeo .

**Comment by DomT4** [comment]
Yeah, additionally ` vet ` isn't placed in the ` GOROOT ` path. Upstream place it several levels deep inside a tool directory, which we've replicated. I vetted a few projects to ensure it was coughing out the expected output, so it should be okay, theoretically :smile_cat:.
