### ISSUE TITLE
Suggestion: Homebrew workflow manager for Alfred 2

### ISSUE THREAD

**Issue by N4M3Z** [Homebrew/homebrew#37130]
Would you consider implementing a package manager for Alfred workflows along similar lines to homebrew-cask? It would essentially only require to download the Alfred workflow from http://www.packal.org and open the file, Alfred takes over from there. I am available to help with testing.

**Comment by mikemcquaid** [comment]
I don't think we would. If you wanted to and it got traction we would consider linking to yours. Thanks!
