### ISSUE TITLE
Emacs 24.4.1: Symbol's function definition is void: defile-key

### ISSUE THREAD

**Issue by srustamo** [Homebrew/homebrew#37145]
`brew install emacs --HEAD --use-git-head --cocoa --with-gnutls --with-rsvg --with-imagemagick`
fails with the following error:

`Symbol's function definition is void: defile-key
make[2]: *** [calendar/cal-loaddefs.el] Error 255
make[1]: *** [../lisp/loaddefs.el] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [src] Error 2Symbol's function definition is void: defile-key
make[2]: *** [calendar/cal-loaddefs.el] Error 255
make[1]: *** [../lisp/loaddefs.el] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [src] Error 2`

**Comment by jacknagel** [comment]
You need to follow http://git.io/brew-troubleshooting

However, we typically don't provide support for `--HEAD` builds because they are constantly changing.

We suggest either using the stable release, or reporting any build issues upstream.
