### ISSUE TITLE
Problem installing git on yosemite

### ISSUE THREAD

**Issue by markaduffy** [Homebrew/homebrew#37150]
Having problems installing git with homebrew on yosemite 10.10.2. Tried every past solution available. I do have write permissions on /usr/local. I can do brew update and brew doctor with no issues, but it says I have git-git (whatever that is) already installed. I have oh-my-zsh shell. i have xcode with git and atom installed if that may be relevant. I tried using bash shell, and got same issue.

	Last login: Tue Feb 24 09:56:18 on console
	    You have new mail.

	# user at mymac in ~ [9:57:48]
	$ brew install git
	Error: git-git already installed
	To install this version, first `brew unlink git'

	# user at mymac in ~ [9:57:54]
	$ brew unlink git
	Error: No such keg: /usr/local/Cellar/git

	# user at mymac in ~ [9:58:04]
	$ brew update
	Updated Homebrew from b33e8a75 to cf5325ac.
	==> New Formulae
	deisctl         gcovr       pdf-redact-tools
	==> Updated Formulae
	activemq    couchdb-lucene  hamsterdb   libgadu     redpen
	avian       datomic     httpie      libmpdclient    unittest
	berkeley-db gtk-gnutella    ice     mysql
	cctools     h2o     ipsumdump   mysql-cluster

	# user at mymac in ~ [10:01:04]
	$ brew doctor
	Your system is ready to brew.

	# user at mymac in ~ [10:01:25]
	$ brew install git
	Error: git-git already installed
	To install this version, first `brew unlink git'

	# user at mymac in ~ [10:01:30]
	$ brew unlink git
	Error: No such keg: /usr/local/Cellar/git

	# user at mymac in ~ [10:01:35]
	$ brew link git
	Error: No such keg: /usr/local/Cellar/git

	# user at mymac in ~ [10:01:44]
	$ git --version
	zsh: command not found: git

	# user at mymac in ~ [10:02:01]
	$ brew --version
	0.9.5

	# user at mymac in ~ [10:06:17]
	$ git-git --version
	zsh: command not found: git-git

	# user at mymac in ~ [10:11:32]
	$ which git-git
	git-git not found

With Bash

	mymac:~ user$ git --version 
        -bash: git: command not found 
        mymac:~ user$ brew install git 
        Error: git-git already installed To install this version, first `brew    unlink git' 
        mymac:~ user$ –

**Comment by markaduffy** [comment]
So you know the whole picture, i reinstalled git successfully from the git website, and it worked again from bash. I had to add the following path in .zshrc which was /usr/local/git/bin.

**Comment by xu-cheng** [comment]
What's the result of `ls /usr/local/Cellar`? And can you try `brew prune`

**Comment by markaduffy** [comment]
# user at mymac in ~/dev/myhubot on git:master o [13:50:22]
$ ls /usr/local/Cellar

# user at mymac in ~/dev/myhubot on git:master o [13:55:35]
$ brew prune
Pruned 0 dead formulae
Tapped 1 formula

**Comment by jacknagel** [comment]
Take a look at the resolution in #37250, this looks like the same issue.

**Comment by jacknagel** [comment]
Presuming fixed per this comment https://github.com/Homebrew/homebrew/issues/37250#issuecomment-76506080
