### ISSUE TITLE
brew install wine fails on OS X 10.10.2 on dependency gd

### ISSUE THREAD

**Issue by mrampton** [Homebrew/homebrew#37152]
brew install wine fails while installing dependency gd

brew update has been run
brew doctor returns '...ready to brew'

brew gist-logs wine says
Error: No logs

So here is a gist (https://gist.github.com/6b09e8760ec02617cfa0) created from:
1. brew install gd --universal
2. brew gist-logs gd

I have run the following in an attempt to ensure all dependencies for wine are installed --universal
` for PKG in $(brew deps wine); do brew reinstall $PKG --universal; done`

localhost ~ $ brew install wine
==> Installing dependencies for wine: gd, libgphoto2
==> Installing wine dependency: gd
==> Downloading https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.0.tar.gz
Already downloaded: /Users/Mark/Library/Caches/Homebrew/gd-2.1.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/gd/2.1.0_2 --with-png=/usr/local/opt/libpng --with-fontconfig=/usr/local/opt/fontconfig --with-freetype=/usr/local/opt/freetype --with-jpeg=/usr/local/opt/jpeg --with-tiff=/usr/local/opt/libtiff --without-vpx
==> make install
      _do_convert in gdkanji.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libgd.la] Error 1
make: *** [install-recursive] Error 1

**Comment by jacknagel** [comment]
You have a non-universal libiconv installed. libiconv ships with OS X, so we don't package it in core anymore.

You'll need to either remove it or `brew unlink` it.

**Comment by mrampton** [comment]
Ugh -- thanks! 

Should I have spotted that on my own? It's not something that jumped out at me looking through the logs.

**Comment by tdsmith** [comment]
We won't hold it against you! The relevant lines in the log are the reference to `/usr/local/Cellar/libiconv/1.13.1/lib/libiconv.dylib` in the compiler invocation just before the error message followed by

```
Undefined symbols for architecture i386:
  "_iconv", referenced from: ...
```

which suggests that the i386 iconv symbols are missing from that dylib. You can use a command like `lipo -info /usr/lib/libiconv.dylib` to see if libraries are fat (multi-arch) or not. Let us know if we can help with anything else.

**Comment by mrampton** [comment]
Thanks Tim!
