### ISSUE TITLE
brew should allow installation of packages like sshpass with a flag

### ISSUE THREAD

**Issue by dwt** [Homebrew/homebrew#37154]
I fully get that it is mostly a bad software - but sometimes it is actually required even by advanced users.

For example unusable requires it when initially setting up hosts to allow forcing it to login via password until key based auth is setup.

I propose a flag like  ```--i-know-what-i-am-doing-please-destroy-my-system``` to allow advanced users to override the package managers opinion for those times when the admin really does know better than the tool.

**Comment by mikemcquaid** [comment]
You can create your own tap and install it from there instead.

**Comment by dwt** [comment]
Please reopen.

While this is true, a security critically package like this should really be maintained inside the homebrew package and give all the same security and patch guarantees as the rest of home-brew.

I as a user cannot accurately consider the trustworthiness of random taps on the internet, wich is the precise reason this bug was opened.

The central bug tracker and ability to review this package within the framework of the home-brew project is vital for a security critical piece of software such as this.

So please reconsider and reopen.

**Comment by mikemcquaid** [comment]
No, sorry, maintain your own tap.
