### ISSUE TITLE
Build failure: missing module giscanner.scannermain

### ISSUE THREAD

**Issue by Teugon** [Homebrew/homebrew#37168]
It's my first issue and I can assure you I did everything it was suggested to do before annoying others..

Yosemite 10.10.2

Gist link at https://gist.github.com/anonymous/a0cfdb3ae3d36d159a03

I had a problem due to a missing header file when installing gtk+3 from a bottle instead of building it from source. In particular I was missing glibconfig.h so I decided to reinstall gtk+3 from source instead. Terminal error is on the end of the issue..

I've Already found a workaround on this. Install gtk+3 from the bottle then reinstall ONLY glib by source.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$ brew reinstall --build-from-source gtk+3
==> Reinstalling gtk+3
==> Downloading http://ftp.gnome.org/pub/gnome/sources/gtk+/3.14/gtk+-3.14.6.tar.xz
Already downloaded: /Library/Caches/Homebrew/gtk+3-3.14.6.tar.xz
==> ./configure --prefix=/usr/local/Cellar/gtk+3/3.14.6 --disable-glibtest --enable-introspection=ye
==> make install
ImportError: No module named giscanner.scannermain
make[3]: *** [Gdk-3.0.gir] Error 1
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

PS: I've encountered similar problems (mostly missing .dylib) for many dependencies from gtk+3 when installing them by brew install --build-from-source.

**Comment by tdsmith** [comment]
Does reinstalling `gobject-introspection` help?

**Comment by Teugon** [comment]
no it didn't helped. As I said I worked around that by reinstalling just glib

**Comment by tdsmith** [comment]
Okay, thanks for the report!
