### ISSUE TITLE
llvm --with-lld requires an out-of-source build

### ISSUE THREAD

**Issue by alexchandel** [Homebrew/homebrew#37167]
As of the past ~4 days, I get the following errors when building LLVM:

```bash
brew install llvm --HEAD --with-lld                                                                                                     [130]
==> Cloning http://llvm.org/git/llvm.git
Updating /Library/Caches/Homebrew/llvm--git
==> Checking out branch master
==> Patching
patching file Makefile.rules
Hunk #1 succeeded at 598 (offset -1 lines).
==> Cloning http://llvm.org/git/lld.git
Updating /Library/Caches/Homebrew/llvm--lld--git
==> Checking out branch master
==> ./configure --prefix=/usr/local/Cellar/llvm/HEAD --enable-optimized --disable-bindings --enable-targets=host --enable-shared
==> make
llvm[4]: Building Release+Asserts Archive Library liblldCore.a
llvm[4]: Building Release+Asserts Archive Library liblldDriver.a
make[2]: *** [all] Error 1
make[1]: *** [lld/.makeall] Error 2
make: *** [all] Error 
```

Brew doctor is clean, and I can usually build LLVM with `brew install llvm --HEAD --with-all-targets --with-clang --with-lld --with-python` with no problems. Any ideas?

**Comment by jacknagel** [comment]
You need to follow http://git.io/brew-troubleshooting; what you've posted doesn't contain any information about the build error.

However, we typically don't provide support for --HEAD builds because they are constantly changing.

We suggest either using the stable release, or reporting any build issues upstream.

**Comment by alexchandel** [comment]
The full output: https://gist.github.com/alexchandel/380a32e911816cb5486b
Upstream says this isn't a bug in LLVM. Please reopen.

**Comment by tamird** [comment]
This is a bug in that `lld` requires an out-of-source build: http://lld.llvm.org/getting_started.html#on-unix-like-systems

Some other formulae do this by creating a subdir and then building in there, but LLVM's cmake does not allow this; it has to be out-of-source. Anyway, this should probably be reopened.

Here's what I tried:
```diff
diff --git a/Library/Formula/llvm.rb b/Library/Formula/llvm.rb
index 5f58024..eb64c78 100644
--- a/Library/Formula/llvm.rb
+++ b/Library/Formula/llvm.rb
@@ -84,6 +84,7 @@ class Llvm < Formula
   else
     depends_on :python => :optional
   end
+  depends_on "cmake" => :build
   depends_on "swig" if build.with? "lldb"
 
   keg_only :provided_by_osx
@@ -117,6 +118,9 @@ class Llvm < Formula
 
     ENV["REQUIRES_RTTI"] = "1" if build.with?("rtti") || build.with?("clang")
 
+    mkdir "build" do
+      system "cmake", "..", "-G", "Unix Makefiles", *std_cmake_args
+
       args = [
         "--prefix=#{prefix}",
         "--enable-optimized",
@@ -152,6 +156,7 @@ class Llvm < Formula
       (lib+"python2.7/site-packages").install buildpath/"bindings/python/llvm"
       (lib+"python2.7/site-packages").install buildpath/"tools/clang/bindings/python/clang" if build.with? "clang"
     end
+  end
 
   test do
     system "#{bin}/llvm-config", "--version"
```

Running through this by hand yields:
```
$ cmake .. -G "Unix Makefiles"
-- No build type selected, default to Debug
CMake Error at CMakeLists.txt:119 (message):
  In-source builds are not allowed.

  CMake would overwrite the makefiles distributed with LLVM.

  Please create a directory and run cmake from there, passing the path

  to this source directory as the last argument.

  This process created the file `CMakeCache.txt' and the directory
  `CMakeFiles'.

  Please delete them.
```

So we're going to need a whole new tempdir, I think. I don't know enough about brew internals to implement this. @jacknagel can you lend a hand?

**Comment by tdsmith** [comment]
Do you know if this affects stable builds as well?

**Comment by tamird** [comment]
No, stable builds are not affected (at least on LLVM 3.5.1; [homebrew doesn't support 3.6 yet](https://github.com/Homebrew/homebrew/pull/37260))

**Comment by jacknagel** [comment]
```rb
def install
  # do some stuff

  mktemp do
    # do other stuff in a new temporary directory
  end

  # do even more stuff
end
```

**Comment by DomT4** [comment]
Is this problem likely to be the cause of any of the [several](https://github.com/Homebrew/homebrew-versions/issues) Homebrew/versions bug reports outstanding on LLVM?

**Comment by tamird** [comment]
Yeah, at least [this one](https://github.com/Homebrew/homebrew-versions/issues/520) seems to be.

By the way, in-source builds are being deprecated upstream, see:
http://llvm.org/docs/CMake.html#id6
https://github.com/llvm-mirror/llvm/commit/7dda4c92e4718c624e2bb91d8cf31685710c5f09

**Comment by DomT4** [comment]
> Yeah, at least this one seems to be.

If you wanted to duplicate the measures in this PR for the Versions formulae I'd :tada:, but no worries otherwise. Is the deprecation being applied to all branches or only the more recent releases?

**Comment by tamird** [comment]
The official deprecation is not yet in any released version. I'll see what I can do about the Versions formula. Can you help move this PR along in the meantime?

**Comment by DomT4** [comment]
Thanks for clarification, and for anything you can do with the versions formulae in advance! Would be appreciated a lot. Afraid I can't do anything with the PR in Homebrew/homebrew - The core is outside my "authority" :wink:.

**Comment by alexchandel** [comment]
`brew install --HEAD --with-clang --with-lld llvm` successfully compiles now.
