### ISSUE TITLE
Not a Valid Keg Error

### ISSUE THREAD

**Issue by gcortes** [Homebrew/homebrew#37160]
Installed git using home on OS X a version or two ago and one machine ago. I did a migration from the old machine to the new one. I was getting pretty far behind on the version of git I was running so I ran: brew upgrade git. I got the following output:

==> Upgrading 1 outdated package, with result:
git 2.3.0
Error: /usr/local/Library/LinkedKegs/git is not a valid keg

I've done brew doctor and got a few warnings none of which appeared to have anything to do with git. I also ran brew cleanup. It cleaned up, but didn't fix the error. An Internet search on the error didn't turn up anything specific. Git is working so I don't want to do anything to break it. How might I fix this problem? I'm on brew 0.9.5

**Comment by jacknagel** [comment]
What does `ls -l /usr/local/Library/LinkedKegs/git` and `ls -l /usr/local/Cellar/git` say?

**Comment by gcortes** [comment]
=> ls -l /usr/local/Library/LinkedKegs/git
total 56
drwxrwxr-x  11 curt  wheel    374 Nov 24 19:59 .
drwxrwxr-x  20 curt  wheel    680 Feb 24 17:08 ..
-rw-r--r--   1 curt  wheel  18765 Jul 22  2013 COPYING
-rw-r--r--   1 curt  admin    258 Aug 13  2013 INSTALL_RECEIPT.json
drwxrwxr-x   3 curt  wheel    102 Nov 24 19:59 Library
-rw-r--r--   1 curt  wheel   2625 Jul 22  2013 README
drwxrwxr-x  11 curt  wheel    374 Nov 24 19:17 bin
drwxrwxr-x   3 curt  wheel    102 Nov 24 19:15 etc
drwxrwxr-x   4 curt  wheel    136 Nov 24 19:15 lib
drwxrwxr-x   3 curt  wheel    102 Nov 24 19:13 libexec
drwxrwxr-x   9 curt  wheel    306 Nov 24 19:15 share

=> ls -l /usr/local/Cellar/git
total 0
drwxrwxr-x   4 curt  wheel  136 Nov 24 19:13 .
drwxrwxr-x  22 curt  wheel  748 Feb 24 17:08 ..
drwxrwxr-x  10 curt  wheel  340 Nov 24 19:59 1.8.2
drwxrwxr-x  11 curt  wheel  374 Nov 24 19:59 1.8.3.4

**Comment by jacknagel** [comment]
Is `/usr/local/Library/LinkedKegs/git` a symlink or a directory? It should be a symlink. Does the discussion in #37250 help?

**Comment by gcortes** [comment]
Well, I don't know if I made it better or worse. Git was a directory so I deleted it as the poster in the other issue did. I had to approve the deletion of a lot more files than were in the git directory. When it was done, I did a brew upgrade git. I got the following error:

| /usr/local/Library/LinkedKegs @ Yamadoshi (curt)| => brew upgrade git
==> Upgrading 1 outdated package, with result:
git 2.3.0
==> Upgrading git
==> Downloading https://homebrew.bintray.com/bottles/git-2.3.0.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring git-2.3.0.yosemite.bottle.tar.gz
==> Caveats
The OS X keychain credential helper has been installed to:
  /usr/local/bin/git-credential-osxkeychain

The "contrib" directory has been installed to:
  /usr/local/share/git-core/contrib

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink etc/bash_completion.d/git-completion.bash
Target /usr/local/etc/bash_completion.d/git-completion.bash
is a symlink belonging to git. You can unlink it:
  brew unlink git

To force the link and overwrite all conflicting files:
  brew link --overwrite git

To list all files that would be deleted:
  brew link --overwrite --dry-run git

Possible conflicting files are:
...

As it suggested, I tried:

| /usr/local/Library/LinkedKegs @ Yamadoshi (curt)| => brew link --overwrite git
Linking /usr/local/Cellar/git/2.3.0... Error: Directory not empty - /usr/local/opt/git
________________________________________________________________________________

I deleted the directory, which again asked me to delete a lot more files than it contained.
When I ran brew upgrade git, it said 2.3.0 was already installed. I than ran brew link --overwrite git. It said it was already linked. I then ran git --version and it said no such file or directory. It appears I've deleted the application. How do I reinstall git? It looks like I have to get brew to think it's gone first. I'm hesitant to try anything else at this point that might make the situation worse.

**Comment by gcortes** [comment]
I tried to delete git and reinstall it. No luck:

| /usr/local/Cellar/git/2.3.0 @ Yamadoshi (curt)| => brew uninstall git
Uninstalling /usr/local/Cellar/git/2.3.0...
git 1.8.2, 1.8.3.4 are still installed.
Remove them all with `brew uninstall --force git`.
________________________________________________________________________________
| /usr/local/Cellar/git/2.3.0 @ Yamadoshi (curt)| => git -version
-bash: /usr/local/bin/git: No such file or directory
________________________________________________________________________________
| /usr/local/Cellar/git/2.3.0 @ Yamadoshi (curt)| => brew uninstall --force git
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
The current working directory doesn't exist, cannot proceed.
________________________________________________________________________________
| /usr/local/Cellar/git/2.3.0 @ Yamadoshi (curt)| => brew install git
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
The current working directory doesn't exist, cannot proceed.

**Comment by mistydemeo** [comment]
It looks like you uninstalled git 2.3.0 while you were in its prefix, so the directory no longer exists; you need to be `cd`ed to a directory that exists to use Homebrew.

**Comment by gcortes** [comment]
You're right. I did an ls. It didn't say I wasn't in a directory. It also didn't list anything. I backed out to Cellar and did the following:

| /usr/local/Cellar @ Yamadoshi (curt)| => brew uninstall --force git
Uninstalling git...
________________________________________________________________________________
| /usr/local/Cellar @ Yamadoshi (curt)| => brew install git
==> Downloading https://homebrew.bintray.com/bottles/git-2.3.0.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/git-2.3.0.yosemite.bottle.tar.gz
==> Pouring git-2.3.0.yosemite.bottle.tar.gz
==> Caveats
The OS X keychain credential helper has been installed to:
  /usr/local/bin/git-credential-osxkeychain

The "contrib" directory has been installed to:
  /usr/local/share/git-core/contrib

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
Error: An unexpected error occurred during the `brew link` step
The formula built, but is not symlinked into /usr/local
Directory not empty - /usr/local/opt/git
Error: Directory not empty - /usr/local/opt/git

I checked and got this:

________________________________________________________________________________
| /usr/local/opt/git @ Yamadoshi (curt)| => ls
.                    COPYING              Library              bin                  lib                  share
..                   INSTALL_RECEIPT.json README               etc                  libexec

Do I need to delete this directory? If so how exactly? I don't want to delete too much.

**Comment by gcortes** [comment]
Additional info: opt/git is a directory.

| /usr/local/opt @ Yamadoshi (curt)| => ls -l
total 152
...
drwxrwxr-x  11 curt  wheel  374 Nov 24 19:59 git

**Comment by mistydemeo** [comment]
`opt/git` should be a symlink to the currently-installed version; if it's a directory, you'll need to delete it.

**Comment by gcortes** [comment]
I had to delete a whole bunch more files. After I did:

| /usr/local/opt @ Yamadoshi (curt)| => brew install git
Warning: git-2.3.0 already installed, it's just not linked
________________________________________________________________________________
| /usr/local/opt @ Yamadoshi (curt)| => brew link --overwrite --dry-run git
Would remove:
________________________________________________________________________________
| /usr/local/opt @ Yamadoshi (curt)| => brew link git
Linking /usr/local/Cellar/git/2.3.0... 209 symlinks created
________________________________________________________________________________
| /usr/local/opt @ Yamadoshi (curt)| => git --version
git version 2.3.0
________________________________________________________________________________
| /usr/local/opt @ Yamadoshi (curt)| => brew list
autoconf	dartium		jpeg		mcrypt		openssl		pkg-config	ssh-copy-id
cmake		freetype	libpng		mhash		passenger	rbenv		xz
dart		git		libxml2		mysql		pcre		ruby-build
________________________________________________________________________________

It looks like I'm set on this one. I have a few more old outdated installs. There not very far behind so I'm going to leave them alone. Thanks for the help.
