### ISSUE TITLE
Brew Install Fail for all Packages

### ISSUE THREAD

**Issue by lettuchead** [Homebrew/homebrew#37170]
Brew doctor is all clear. Brew and NPM are up to date.

At least two npm packages do not install:

brew install godot
and
brew install statsd

Both give the following messages:

Error: No available formula for godot 
Searching formulae...
Searching taps...

However, running brew install nvm did work. This may be related to an accidental installation of node prior to running brew doctor after downloading brew.

**Comment by lettuchead** [comment]
Xcode and Java are also up to date.

**Comment by mistydemeo** [comment]
Homebrew doesn't have packages by those names. If you're looking to install them using npm, you'll need to use `npm install` - for example, `npm install godot`.

**Comment by lettuchead** [comment]
Thank you.
