### ISSUE TITLE
brew linking to older xcode on another partition 

### ISSUE THREAD

**Issue by Intimaria** [Homebrew/homebrew#37185]
Hi all -- I have two partitions on my mac, one is a clean dev partition with 10.10. The other has snow leopard because it has some old work stuff on it. It has an old version of xcode on it. I was confused because in the beginning I was getting this:

<code><strong>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks! </strong></code>
<br />
<code>
Warning: Your Xcode (5.1) is outdated
Please update to Xcode 6.1.1.
Xcode can be updated from the App Store.
</code>

Confused, I looked for bits of xcode that it might be linking to and ended up downloading the whole xcode , which didn't fix it. 

I found the problem when I did brew --config and saw that xcode was being found in the other partition automatically.

I fixed it by unmounting the other partition in disk utilities, but as soon as I mount it, brew defaults to the older xcode in the other partition rather than the one on it's own partition. 

So I guess I want to know

1) How to I fix this without unmounting my other partition/ how to I point homebrew to xcode 6.1.1?

2) More out of curiosity, why does it do this?

**Comment by jacknagel** [comment]
What does `xcode-select -print-path` say? Does it point where you expect?

**Comment by Intimaria** [comment]
Yes, that's fine luckily

It says <code>/Library/Developer/CommandLineTools</code>

(I did <code>sudo xcode-select -switch /Library/Developer/CommandLineTools</code>)

**Comment by jacknagel** [comment]
So if you don't have Xcode selected (keep in mind the standalone CLT and Xcode are entirely separate packages as of 10.9), then Homebrew uses `mdfind` (spotlight) to locate Xcode. So what's probably happening is the older Xcode is being found first.

I don't really know what to suggest, and I don't know how much effort we can really put into supporting such a configuration.

**Comment by jacknagel** [comment]
Closing per the above.
