### ISSUE TITLE
Upgrading fish is not shell independent

### ISSUE THREAD

**Issue by Pfeil** [Homebrew/homebrew#37194]
I'm using fish as my shell and as the new version 2.1.2 was released, I had some issues upgrading:

    ==> Summary
    🍺  /usr/local/Cellar/fish/2.1.2: 670 files, 5,5M
    fish: Could not connect to universal variable server, already tried manual restart (or no command supplied). You will not be able to share variable values between fish sessions. Is
    fish properly installed?
    fish: Could not connect to universal variable server, already tried manual restart (or no command supplied). You will not be able to share variable values between fish sessions. Is
    fish properly installed?

I switched to the old version of fish, removed the directory of version 2.1.2 and simply executed to /bin/bash and tried `brew upgrade fish` again. The result:

    ==> Summary
    🍺  /usr/local/Cellar/fish/2.1.2: 670 files, 5,5M
    bash-3.2$

The new version of fish seems to work fine. My default system shell (changed with `chsh`) is fish, not bash. I'm on OSX 10.9.5. Unfortunately, I have no clue why it has to be upgraded from a bash session. Even when I used a bash session, fish was still my default shell. So it has to be dependent on the session which called the `brew upgrade fish` command. I see some `system` calls in the formula, maybe there is a problem with that.

**Comment by DomT4** [comment]
Homebrew has some known issues with Fish, amongst other non-Bourne-esque shells, I believe. This might be the root cause here. Also the current & version before this one ` Fish ` formula kills ` fishd ` post-install per instructions from upstream, which might cause an issue when you're already using Fish. Could be either of those things.

**Comment by mistydemeo** [comment]
The messages you're seeing are coming from your existing shell processes noticing that `fishd` has been killed by the upgrade process; it's not indicative of an actual installation issue, and isn't coming from Homebrew. The fish upgrade has still succeeded. Sorry for the confusing error message.
