### ISSUE TITLE
Python v3.4.3 is now released

### ISSUE THREAD

**Issue by cclauss** [Homebrew/homebrew#37193]
`brew install python3` currently installs Python v3.4.2.

https://www.python.org/downloads/release/python-343

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
