### ISSUE TITLE
Is there a way to use the manually downloaded source file?

### ISSUE THREAD

**Issue by chengguangnan** [Homebrew/homebrew#37191]
I have networking problems with sf.net and I have file downloaded manually. 

I tried put the bz2 file into /Library/Caches/Homebrew and run `brew install` but homebrew will still try to download. 

Is there a way to use the manually downloaded source file?

```
==> Downloading https://upx.sourceforge.net/download/upx-3.91-src.tar.bz2

curl: (7) Failed to connect to upx.sourceforge.net port 443: Operation timed out
Error: Failed to download resource "upx"
Download failed: https://upx.sourceforge.net/download/upx-3.91-src.tar.bz2
```

**Comment by mikemcquaid** [comment]
You need to name the file the same as what Homebrew is trying to download e.g. probably `upx-3.9.1.tar.bz2` or something in this case.

**Comment by chengguangnan** [comment]
The filename does match.

**Comment by jacknagel** [comment]
It needs to match exactly the output of `brew --cache <formula name>`.

**Comment by chengguangnan** [comment]
Thanks! I didn't noticed the difference!
