### ISSUE TITLE
vim failed to build on 10.10.2

### ISSUE THREAD

**Issue by sirreal** [Homebrew/homebrew#37200]
Trying to build vim reports error:

```
checking --with-tlib argument... ncurses
checking for linking with ncurses library... OK
checking for tgetent()... configure: error: NOT FOUND!
      You need to install a terminal library; for example ncurses.
      Or specify the name of the library with --with-tlib.
```

# brew gist-logs vim
```
https://gist.github.com/a47e9655547135058881
```

# brew doctor
```
Your system is ready to brew.
```

# brew config
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: c5709064d4c66de739481b9ca9f37ea8cfc9f719
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit nehalem
OS X: 10.10.2-x86_64
Xcode: 6.1.1
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.0/bin/ruby
Java: openjdk version "1.7.0-ea"
```

**Comment by chdiza** [comment]
Try the remedy herein: https://github.com/Homebrew/homebrew/pull/33687

**Comment by tdsmith** [comment]
If you open a `brew sh` session and run `echo 'int main() { return 0; }' > main.c && clang -lncurses main.c && otool -L a.out`, what do you see?

`nm /usr/lib/libncurses.5.4.dylib | grep tgetent` produces output, right?

**Comment by chdiza** [comment]
I have a feeling @sirreal has the chefdk conflict problem mentioned in #33687, and if so, we're gonna have to do something about that conflict.  We should probably do something about it whether or not it's @sirreal's particular affliction.

**Comment by sirreal** [comment]
As soon as I have access to the machine, I'll provide some feedback.

**Comment by adamv** [comment]
May need to write a doctor check for chefdk?

**Comment by sirreal** [comment]
Ok, I do not appear to have anything chef related installed on this machine, nor any recollection of installing anything. No signs of chefdk, which seems to rule out #33687.

@tdsmith here's the output:

```
$ echo 'int main() { return 0; }' > main.c && clang -lncurses main.c && otool -L a.out
ld: warning: ignoring file /usr/local/lib/libncurses.dylib, file was built for unsupported file format ( 0xFE 0xED 0xFA 0xCE 0x00 0x00 0x00 0x12 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x06 ) which is not the architecture being linked (x86_64): /usr/local/lib/libncurses.dylib
a.out:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)

$ nm /usr/lib/libncurses.5.4.dylib | grep tgetent
000000000001599c T _tgetent
```

A note, possibly unrelated, I've just discovered a new error I'd never seen before. While debugging this, I used bash again, which had some garbled output. On running `reset`, I get the following error:

```
-bash: /usr/local/bin/reset: Bad CPU type in executable
```

**Comment by tdsmith** [comment]
Odd! Out of curiosity, what's `file /usr/local/lib/libncurses.dylib` tell you? How about `file /usr/local/bin/reset`?

Anyway, moving `/usr/local/lib/*curses*.dylib` out of /usr/local/lib (and probably any curses-related include files from /usr/local/include) at least temporarily might fix your vim build. Do you know how those files got there?

**Comment by sirreal** [comment]
I am on an intel mac, so these `ppp` references are strange:

```
$ file /usr/local/bin/reset 
/usr/local/bin/reset: Mach-O executable ppc
```

```
$ file /usr/local/lib/libncurses.dylib
/usr/local/lib/libncurses.dylib: Mach-O dynamically linked shared library ppc
```

Removal of `libcurses.dylib` and `libncurses.dylib` fixed the build. Hopefully I won't run into other problems down the line.

**Comment by tdsmith** [comment]
Glad it's resolved! Let us know if we can help with anything else.

**Comment by sirreal** [comment]
I appreciate your help!
