### ISSUE TITLE
Is there any way to switch default bootle download source back to SourceForge?

### ISSUE THREAD

**Issue by xdqi** [Homebrew/homebrew#37210]
Few days ago, I ran `brew update` and `brew upgrade` command as usual to update my formulas.
But I found it extremely slow to download a bottle at only about 70KB/s while it was 1.5+M/s to download a bottle before.
Later I noticed the default bottle source has switched to BinTray for dealing with probable SourceForge down problem, but it does not benefit me.

So is there possible to give *me* a way to switch back to SourceForge instead of BinTray?
I would be greatly appreciated if you could give me a way to do so.

**Comment by tdsmith** [comment]
Setting the environment variable `HOMEBREW_SOURCEFORGE_TESTING` should let you use bottles from Sourceforge but we may not support that much longer. Your profile says you're in Beijing? Perhaps Bintray's CDN does not have good service to China. :/

**Comment by mikemcquaid** [comment]
Bintray's CDN is Akamai. There's no way to switch back to SourceForge really as that variable is a temporary stop-gap which will be removed shortly. I'm sorry for the inconvenience.
