### ISSUE TITLE
cask install --force fails without explicit 'cask'

### ISSUE THREAD

**Issue by OJFord** [Homebrew/homebrew#37217]
`brew install Caskroom/cask/mactex` was quit early; on repeat gave:

> Warning: A Cask for mactex is already installed. Add the "--force" option to force re-install.

So adding the `--force` option:

> `$ brew install Caskroom/cask/mactex --force`
> Warning: A Cask for mactex is already installed. Add the "--force" option to force re-install.
> `$ brew install --force Caskroom/cask/mactex`
> Warning: A Cask for mactex is already installed. Add the "--force" option to force re-install.

Figured I'd try to uninstall:

> `$ brew uninstall Caskroom/cask/mactex`
Error: No such keg: /usr/local/Cellar/mactex

Not far enough along. Only at this point did I notice from the output that `brew install Caskroom/cask` was implicitly `brew cask install`, so I tried:

> `$ brew cask install Caskroom/cask/mactex --force`

Which worked.

**Comment by jacknagel** [comment]
@mikemcquaid Mike, how much integration do you intend there to be between `brew install` and `brew cask install`? Given that identical command line flags given to `brew install` and `brew cask install` may do different things, I'm not sure what to suggest as a way forward here.

**Comment by mikemcquaid** [comment]
> @mikemcquaid Mike, how much integration do you intend there to be between brew install and brew cask install? Given that identical command line flags given to brew install and brew cask install may do different things, I'm not sure what to suggest as a way forward here.

I don't really intend there to be much beyond `install` and `search` as after that point I'd suggest people switch over to using `brew cask` properly. I'm not sure the best way of communicating that, though.

**Comment by OJFord** [comment]
@mikemcquaid From my perspective, I'd suggest an 'all or nothing' approach.

If it had failed at `brew install Caskroom/...` I would have presumably identified the issue much sooner (first time using `brew cask`), and never would have made the mistake with `--force` and associated cryptic error.

**Comment by mikemcquaid** [comment]
An all-or-nothing approach isn't going to happen, sorry. Passing the arguments correctly may, though.

**Comment by OJFord** [comment]
That's what I mean by 'all' - I meant either go all-in on allowing ommision of `cask`, or never allow it. Supporting it in some circumstances and not others just asks for confusion IMO.
