### ISSUE TITLE
bpython requires.txt not synchronized with latest version of curtsies

### ISSUE THREAD

**Issue by ztomer** [Homebrew/homebrew#37239]
After updating bpython to 0.14 (using python 3.4.3) running bpython fails with the following message:

`pkg_resources.ContextualVersionConflict: (curtsies 0.2.3 (/usr/local/lib/python3.4/site-packages), Requirement.parse('curtsies<0.2.0,>=0.1.18'), {'bpython'})`

Can be easily fixed by modifying
`/usr/local/lib/python3.4/site-packages/bpython-0.14-py3.4.egg-info/requires.txt`

and changing the line
`curtsies >=0.1.18, <0.2.0`
to 
`curtsies >=0.1.18, <0.2.4`

**Comment by tdsmith** [comment]
Thanks for the report. This doesn't appear to be either a bug or Homebrew-specific but you may want to discuss this with the bpython developers.
