### ISSUE TITLE
Dovecot and brew-services

### ISSUE THREAD

**Issue by nkgm** [Homebrew/homebrew#37245]
Just installed `dovecot` hoping [brew-services](https://github.com/gapple/homebrew-services) would do the plumbing for me, but as the formula rightfully warns, you have to create a configuration in `usr/local/etc` and create a `plist` manually. Now, I've never written a formula, so forgive me if I'm out to lunch here, but would it make sense to have a default configuration so all you have to do is `brew install dovecot && brew services start dovecot`? I'm only using it for local web development, so my requirements are rather simple, but I'm sure a lot of people will have similar requirements.

**Comment by jacknagel** [comment]
Please feel free to submit a pull request adding a plist. See https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md for instructions to get started.
