### ISSUE TITLE
Failure to install git because of some environment problem

### ISSUE THREAD

**Issue by fstorr** [Homebrew/homebrew#37250]
Hi

I'm having a problem installing the git on homebrew. It used to work fine but when I used migration assistant to move my profile to a new machine, something went wrong. If I try to install git I get:

`Error: git-git already installed
To install this version, first 'brew unlink git'`

If I do `brew unlink git` I get:

`Error: No such keg: /usr/local/Cellar/git`

The only version of git I have is the one packaged with Yosemite. I've gone through instructions online to completely remove it from my system, and have tried several uninstallers. I've also tried to uninstall homebrew, and have followed instructions online for doing that.

After reinstalling homebrew, I still can't install git. I've tried to create a gist for you, but just get this: `Error: No logs.`.

So, I'm stuck and don't know what to do now.

**Comment by adamv** [comment]
Possibly the same issue as #37150.

**Comment by fstorr** [comment]
I've looked at that issue and downloaded and installed git. The problem remains.

**Comment by mistydemeo** [comment]
Do you have anything at `/usr/local/Library/LinkedKegs/git`? If so, what is the output of `ls -ld /usr/local/Library/LinkedKegs/git`?

**Comment by fstorr** [comment]
I've got `drwxrwxr-x  11 fstorrx  wheel  374 Jan 25 11:23 /usr/local/Library/LinkedKegs/git`

**Comment by fstorr** [comment]
Okay, I trashed `/usr/local/Library/LinkedKegs/git` then managed to successfully `brew install git`. All seems good now. Thanks :)

**Comment by mistydemeo** [comment]
Looks like you ended up with a directory there somehow - the contents of `LinkedKegs` are meant to be symlinks. That threw off Homebrew's attempt to detect if git was installed and misreport the version. Glad you're all good now!

**Comment by markaduffy** [comment]
i had the same directory in there also.

**Comment by Gailbear** [comment]
This was super helpful to me :)
