### ISSUE TITLE
brew install grc fails with 404 Not Found

### ISSUE THREAD

**Issue by robmcguinness** [Homebrew/homebrew#37257]
Looks like url http://korpus.juls.savba.sk/~garabik/software/grc/grc_1.5.tar.gz is no longer valid. 

The new url seems to be http://korpus.juls.savba.sk/~garabik/software/grc/grc_1.7.orig.tar.gz 

Old url is http://korpus.juls.savba.sk/~garabik/software/grc/old/grc_1.5.tar.gz

**Comment by tdsmith** [comment]
Thanks for the report! Closing in favor of PR.

**Comment by qcho** [comment]
Broken again:

brew install grc                                                 [ruby-2.0.0p481]
==> Downloading http://korpus.juls.savba.sk/~garabik/software/grc/grc_1.7.orig.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "grc"
Download failed: http://korpus.juls.savba.sk/~garabik/software/grc/grc_1.7.orig.tar.gz
