### ISSUE TITLE
Better default config for kafka

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew#37251]
Homebrew kafka can't delete topics out of the box, but with a config tweak:

```
### Allow topic deletion ###

delete.topic.enable=true
```

This becomes possible.

Could we include this snippet by default, so that Mac users have a more intuitive Kafka setup out of the box?

**Comment by tdsmith** [comment]
[Heh](http://blog.confluent.io/2014/12/02/whats-coming-in-apache-kafka-0-8-2/): "This is our third try releasing a working delete topic feature. You would think deleting the data would be easy and not deleting it would be the hard part. But each of our previous attempts had flaws that appeared with usage. This time significant testing has been done and we are hopeful that your data will really be gone."

The docs are pretty clear that it's off by default; should Homebrew behave differently?

**Comment by mikemcquaid** [comment]
> The docs are pretty clear that it's off by default; should Homebrew behave differently?

This makes sense to me. Passing on this.
