### ISSUE TITLE
nghttp2 - install C++ library by default since header files are

### ISSUE THREAD

**Issue by tee3** [Homebrew/homebrew#37277]
This patch ensures that the C++ libraries are installed as well.  I don't know if there are larger implications, but this does what was necessary to build C++ programs using the `nghttp2_asio` library.

```patch
diff --git a/Library/Formula/nghttp2.rb b/Library/Formula/nghttp2.rb
index 7ae0f88..84b138c 100644
--- a/Library/Formula/nghttp2.rb
+++ b/Library/Formula/nghttp2.rb
@@ -82,6 +82,7 @@ class Nghttp2 < Formula
       --disable-threads
       --enable-app
       --with-boost=#{Formula["boost"].opt_prefix}
+      --enable-asio-lib
       --disable-python-bindings
     ]
```

**Comment by tdsmith** [comment]
Thanks for the report! Could you try and open a pull request? [This guide](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'll be happy to walk you through any questions you run in to, either here or on IRC.

**Comment by tee3** [comment]
See the pull request here: https://github.com/Homebrew/homebrew/pull/37287
