### ISSUE TITLE
glib failed to build on 10.10.3

### ISSUE THREAD

**Issue by GuanshanLiu** [Homebrew/homebrew#37288]
I was trying to install Pebble SDK, and failed to install glib. I don't have /usr/lib/libiconv.la file, but in /user/lib, there are libiconv.2.4.0.dylib, libiconv.2.dylib, libiconv.dylib. I have no idea why it needs .la file while .dylib exists. Help, please!

Thanks in advance.

https://gist.github.com/0dc7be1909c8cf3edab4

**Comment by jacknagel** [comment]
To start, it's probably best to remove (at least temporarily) the files that `brew doctor` is complaining about.
