### ISSUE TITLE
gtk+3 builds on 10.9, but not 10.10

### ISSUE THREAD

**Issue by oakes** [Homebrew/homebrew#37286]
I ran `brew install gtk+3 --without-x11` on two different machines, one with 10.9.5 and the other with 10.10.2. The older machine built and installed the library, but the newer one failed with the following error:

```
$ brew install gtk+3 --without-x11
==> Downloading http://ftp.gnome.org/pub/gnome/sources/gtk+/3.14/gtk+-3.14.6.tar.xz
Already downloaded: /Library/Caches/Homebrew/gtk+3-3.14.6.tar.xz
==> ./configure --prefix=/usr/local/Cellar/gtk+3/3.14.6 --disable-glibtest --enable-introspection=yes --disable-schemas-compile --enable-quartz-backend --enable-quartz-relocation
==> make install
make[3]: *** [GdkQuartzView.lo] Error 1
make[3]: *** [gdkdisplaymanager-quartz.lo] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1
```

Things of note:
* My [gist-logs](https://gist.github.com/anonymous/5b809c73ed1cdc89b9f7) from the 10.10 machine
* `vte3` also fails to build on 10.10
* To even get the build to begin, I had to install [XQuartz](http://xquartz.macosforge.org/landing/) and run `sudo chmod -R 777 /usr/local`. The former is due to an [existing issue](https://github.com/Homebrew/homebrew/issues/36915) with the formulas, and the latter is possibly due to 10.10's default file permissions being too restrictive.

**Comment by jacknagel** [comment]
`brew reinstall gdk-pixbuf`

**Comment by oakes** [comment]
That worked, thank you.
