### ISSUE TITLE
protobuf --with-python does not properly depend on gflags

### ISSUE THREAD

**Issue by Midar** [Homebrew/homebrew#37296]
Just noticed that during installation, it would suddenly start downloading gflags. Not only does this break offline builds, but it also seems only an MD5 hash is verified (if it is at all - not sure if PIP actually does that, but the URL it downloads ends in #md5=somehash).

**Comment by tdsmith** [comment]
setuptools probably doesn't verify the hash (which is learned from pypi anyway) but should use https to transfer the eggs. We should fix this, though; thanks for the report.
