### ISSUE TITLE
Newer tapped formula results outdated

### ISSUE THREAD

**Issue by youtux** [Homebrew/homebrew#37317]
I have installed the formula `pebble-sdk` with version `3.0-dp1` from my tap [homebrew-youtux](https://github.com/youtux/homebrew-youtux) using:
```
brew tap youtux/youtux
brew install youtux/youtux/pebble-sdk
```
The formula installs correctly, but when I ask brew if its outdated, it gives a wrong result:
```
brew outdated pebble-sdk
> pebble-sdk (3.0-dp1 < 2.8.1)
```
I think that the problem is within the `Homebrew/cmd/outdated.rb` module:
```ruby
[...]
      if same_tap_versions.all? { |version| f.pkg_version > version }
        yield f, all_versions if block_given?
        f
      end
[...]
```
in which the condition is satisfied since `same_tap_versions` is empty.

**Comment by mikemcquaid** [comment]
What happens if you `brew upgrade pebble-sdk`?

**Comment by youtux** [comment]
```
brew upgrade pebble-sdk                                                                      [13:57:04]
==> Upgrading 1 outdated package, with result:
pebble-sdk 2.8.1
==> Upgrading pebble-sdk
==> Downloading https://homebrew.bintray.com/bottles/pebble-sdk-2.8.1.yosemite.bottle.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/pebble-sdk-2.8.1.yosemite.bottle.1.tar.gz
==> Verifying pebble-sdk-2.8.1.yosemite.bottle.1.tar.gz checksum
==> Pouring pebble-sdk-2.8.1.yosemite.bottle.1.tar.gz
tar xf /Library/Caches/Homebrew/pebble-sdk-2.8.1.yosemite.bottle.1.tar.gz
==> Caveats
Documentation and examples can be found in
  /usr/local/Cellar/pebble-sdk/2.8.1/share/doc/pebble-sdk
==> Finishing up
ln -s ../Cellar/pebble-sdk/2.8.1/bin/pebble pebble
ln -s ../../Cellar/pebble-sdk/2.8.1/share/doc/pebble-sdk pebble-sdk
==> Summary
🍺  /usr/local/Cellar/pebble-sdk/2.8.1: 3262 files, 202M
 youtux ⮀ /usr/local/Cellar/pebble-sdk ⮀ ⭠ master± ⮀
❯ ls                                                                                           [13:57:19]
2.8.1   3.0-dp1
 youtux ⮀ /usr/local/Cellar/pebble-sdk ⮀ ⭠ master± ⮀
❯ brew outdated pebble-sdk
```

**Comment by mikemcquaid** [comment]
That output is a bit confusing but is correct in that case. `brew outdated pebble-sdk` and `brew outdated youtux/youtux/pebble-sdk` will produce different output because they are installing/checking different packages.

**Comment by youtux** [comment]
Oh, I see. But there is another problem then: if I type `brew upgrade` without any formula, it tries to upgrade `pebble-sdk` to `2.8.1`, while it should be aware that I've installed the tapped formula (`3.0-dp1`) and not the homebrew version (`2.8.1`):

```
❯ brew upgrade                                                                                 [14:06:07]
==> Upgrading 1 outdated package, with result:
pebble-sdk 2.8.1
==> Not upgrading 2 pinned packages:
tomcat 8.0.20, wildfly-as 8.2.0.Final
==> Upgrading pebble-sdk
==> Downloading https://homebrew.bintray.com/bottles/pebble-sdk-2.8.1.yosemite.bottle.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/pebble-sdk-2.8.1.yosemite.bottle.1.tar.gz
==> Verifying pebble-sdk-2.8.1.yosemite.bottle.1.tar.gz checksum
==> Pouring pebble-sdk-2.8.1.yosemite.bottle.1.tar.gz
tar xf /Library/Caches/Homebrew/pebble-sdk-2.8.1.yosemite.bottle.1.tar.gz
==> Caveats
Documentation and examples can be found in
  /usr/local/Cellar/pebble-sdk/2.8.1/share/doc/pebble-sdk
==> Finishing up
ln -s ../Cellar/pebble-sdk/2.8.1/bin/pebble pebble
ln -s ../../Cellar/pebble-sdk/2.8.1/share/doc/pebble-sdk pebble-sdk
==> Summary
🍺  /usr/local/Cellar/pebble-sdk/2.8.1: 3262 files, 202M
 youtux ⮀ /usr/local/Cellar/pebble-sdk ⮀ ⭠ master± ⮀
❯ ls                                                                                           [14:06:38]
2.8.1   3.0-dp1
```

**Comment by davidcelis** [comment]
I'm having the same problem with [one of my own tapped formulae](https://github.com/davidcelis/homebrew-spark) where I'm installing a custom version of [spark](https://github.com/davidcelis/spark). My tapped formula ends up being overridden by the Spark formula in Homebrew proper, and it installs the old, original version over my own.

**Comment by davidcelis** [comment]
Thanks for fixing this so quickly, @mikemcquaid!

**Comment by mikemcquaid** [comment]
@davidcelis Thanks for the clearly reproducible test case!

**Comment by paulhybryant** [comment]
Hi,

I still run into the same issue. The problem I have here is that my own tap's version is "head" and brew outdated seems to think head is older than a specific version.

This is the output from brew outdated
zsh-completions (head < 0.12.0)

Shouldn't head always be the newest version?

Thanks!

**Comment by mikemcquaid** [comment]
@paulhybryant Can you link to the tap formula? Thanks.

**Comment by paulhybryant** [comment]
Here it is. Thanks

https://github.com/paulhybryant/homebrew-myformulae/blob/master/zsh-completions.rb

**Comment by mikemcquaid** [comment]
@paulhybryant The issue is you should use `head` rather than `url` with the `version` set to "head".

**Comment by paulhybryant** [comment]
Thanks for the reply. It is resolved after changing it to head.
