### ISSUE TITLE
mkvtoolnix 7.7.0 failed to build on 10.10.2

### ISSUE THREAD

**Issue by guoxiao** [Homebrew/homebrew#37314]
mkvtoolnix 7.7.0 failed to build, which complains Boost::FileSystem is not found. But I have installed boost.
Gist-logs is as following:
https://gist.github.com/anonymous/eb736172dac19e5e93b7

I try to extract the source code and run `./configure` with the same arguments. It can find boost correctly. So I think it may be related to homebrew itself.

**Comment by jacknagel** [comment]
The actual thing that causes the failure in configure's boost usability test is:

```
In file included from /Applications/Xcode-Beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstddef:36:
/Applications/Xcode-Beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:227:20: error: cannot combine with previous 'char16_t' declaration specifier
typedef __char16_t char16_t;
                   ^
/Applications/Xcode-Beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:228:20: error: cannot combine with previous 'char32_t' declaration specifier
typedef __char32_t char32_t;
                   ^
```

so it seems like an incompatibility with the latest libc++ headers.

**Comment by guoxiao** [comment]
@jacknagel So why I can build the program outside homebrew? It seems that when building in homebrew it cannot find system libs.

**Comment by guoxiao** [comment]
I've found the problem. I installed `ccache` and `clang++` is a symbolic link to `ccache`, which caused the problem.
I removed the symbolic link, and it works well now. Thanks for your help.
