### ISSUE TITLE
Need to set cmake absolute path in formula to brew install

### ISSUE THREAD

**Issue by d0nn13** [Homebrew/homebrew#37335]
When trying to do : 
`brew install -v --ignore-dependencies --build-from-source --cc=gcc-4.9 --c++11 yaml-cpp`

Homebrew fails to execute `cmake`.

First :
```
% which cmake
/usr/local/bin/cmake

% cmake --version
cmake version 3.1.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
(this is a brewed cmake)

I tried to `brew edit yaml-cpp`, to edit the `install` method and set the absolute `"/usr/local/bin/cmake"` path to the `system` call instead of the sole `"cmake"`, and it solved the problem.

So it seems that brew fails to locate the `cmake` executable...

I have experienced the exact same behaviour 2 days ago with formula `mysql-connector-c++`, and these are the only 2 formulae I needed to install with `--ignore-dependencies`.

Any help is welcome!

EDIT:
Just felt the need to mention that I have already completed many `brew install`s of a bunch of cmake-based formulae... (but without the option `--ignore-dependencies`)

https://gist.github.com/anonymous/7d6ba2c16222b3cc8246

**Comment by jacknagel** [comment]
By passing `--ignore-dependencies` you are telling Homebrew to forgo all of the environment setup that is normally done for dependencies, including adding per-dependency directories to PATH, which is otherwise sanitized to prevent unlisted dependencies from leaking into the build environment.

Why do you "need" to use `--ignore-dependencies`? This flag is meant only as a debugging tool, and not as a general usage thing. Most formula will not build with it turned on.

**Comment by d0nn13** [comment]
Thanks Jack.
I need `--ignore-dependencies` because I had some issues with brewed `boost` linking many weeks ago, and I fixed these issues by removing brewed `boost` and installing a manually-built-from-sources version. That was probably a compiler-related issue (I build the most of my projects with brewed `gcc-4.9`) and at that time I didnt knew about the `--cc<compiler>` option, so the brewed `boost` were probably compiled with Apple's `clang`, hence the linking issues...

I plan to clean all this stuff (switching back to a brewed `boost`) as I now know about using `brew` with a specific compiler.... But I have to rush on a project and need these 2 `boost`-based formulae.

So I thought `--ignore-dependencies` would be a simple solution that would let me to avoid spending time on downloading and installing a 'non-necessary-yet' `boost` extra version.

**Comment by jacknagel** [comment]
Well, the behavior you've come across is by design, as I noted above. Sorry!
