### ISSUE TITLE
libgit2 is a Debug build by default, can cause SIGABRTs

### ISSUE THREAD

**Issue by jefferai** [Homebrew/homebrew#37332]
By default, libgit2 defines CMAKE_BUILD_TYPE=Debug.

In practice, however, asserts are not hard to hit and in many languages SIGABRTs are impossible to ignore.

It'd be nice if Homebrew either changed the build type to RelWithDebInfo, or allowed the user to toggle a flag at build time to control this behavior.

**Comment by mistydemeo** [comment]
Homebrew passes `-DCMAKE_BUILD_TYPE=Release` to cmake; is this not sufficient to override the default?

**Comment by jefferai** [comment]
@mistydemeo I didn't see that being set in libgit2.rb (perhaps Homebrew does that by default), so your comment surprised me since I'm seeing this debug behavior.

After thinking about it more, I think the problem is that it normally comes as a bottle, and the bottle is built with Debug.

**Comment by mistydemeo** [comment]
Sorry, my mistake - it's setting `-DCMAKE_BUILD_TYPE=None` (defined [here](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/formula.rb#L479))

**Comment by jefferai** [comment]
Interesting. That's not a meaningful value for CMake (according to my knowledge, and I just double-checked it in the [documentation](http://www.cmake.org/cmake/help/v3.0/variable/CMAKE_BUILD_TYPE.html)

This makes me think that the default of libgit2 of "Debug" is then being used, both for normal builds and in the bottle build.

**Comment by DomT4** [comment]
There's no mention of ` Debug ` in the entire CMake build log. There's one mention of ` None `, aside the configure options Homebrew supplies:

```
Install the project...
/usr/local/Cellar/cmake/3.1.3/bin/cmake -P cmake_install.cmake
-- Install configuration: "None"
```

**Comment by jefferai** [comment]
@DomT4 I'm not sure what to tell you. Using libgit2 from the bottle, my program was asserting. Editing the formula to explicitly specify -DCMAKE_BUILD_TYPE=RelWithDebInfo stopped the asserts.

My guess is still that "None" is being overridden (since the default of the underlying software is "Debug", and "None" has no actual meaning to CMake), but CMake simply isn't telling you this.

**Comment by DomT4** [comment]
Yes, I agree. The CMake documentation doesn't state the existence of ` None ` as an option. [Debian](http://anonscm.debian.org/cgit/users/arrsim-guest/libgit2.git/tree/debian/rules) are building it with ` -DCMAKE_BUILD_TYPE:STRING=Release ` or ` -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo `, depending on circumstance.

**Comment by mikemcquaid** [comment]
We should perhaps think of changing our default to `Release` for all packages and ensuring we override the default CMake CFLAGS.

**Comment by DomT4** [comment]
Looks like this block of code is the issue in ` libgit ` itself:

```
IF( NOT CMAKE_CONFIGURATION_TYPES )
	# Build Debug by default
	IF (NOT CMAKE_BUILD_TYPE)
		SET(CMAKE_BUILD_TYPE "Debug" CACHE STRING "Choose the type of build, options are: Debug Release RelWithDebInfo MinSizeRel." FORCE)
	ENDIF ()
```

So it it isn't recognising ` None ` it just defaults to ` Debug `, presumably hence the debug output @jefferai is seeing. I'll tee up a PR to change the default to ` Release ` and include ` libgit2 ` in that. We can do some testing on ` libgit2 ` and then press ahead with any further changes necessary from that point, I guess.

**Comment by DomT4** [comment]
Ensuring we kill off the other CMake flags that usually come with `Release` is the part of this that's going to be *fun*.

**Comment by jefferai** [comment]
Awesome -- thanks!

**Comment by scpeters** [comment]
+1 on moving to `Release` and away from `None`; that was causing some issues in some of my tapped formulae, but I just worked around it. Thanks!
