### ISSUE TITLE
Curl 7.41.0 failed to build on 10.9.5

### ISSUE THREAD

**Issue by jackmaney** [Homebrew/homebrew#37330]
https://gist.github.com/anonymous/2f000954aa2de7198408

This happened when I tried a `brew upgrade` today and Homebrew attempted to install curl 7.41.0. I tried uninstalling Homebrew's previous version of Curl (7.40.0), but that didn't change the error message (and uninstalling it was the cause for the "missing" portion of the `brew doctor` output). I even installed all of the optional dependencies for Curl and specified `--with-<dependency_name>` for each of them in the `brew install` command. No dice.

Note that the `brew doctor` issues (save the aforementioned "missing" portion) in the above gist, including the DYLD_* libraries, were present before this issue, and everything was working fine.

Any help would be greatly appreciated. Thank you for your time.

**Comment by tdsmith** [comment]
What's happening here? Is configure just crashing?

Can you try unsetting `DYLD_LIBRARY_PATH` and then running `brew install curl` again?

**Comment by jackmaney** [comment]
My apologies, I thought the stack trace was in the gist. Apparently it's not...

The stack trace of what happens with a simple `brew install curl` is below. Note that you can ignore the warning about the initial failed download from `homebrew.bintray.com`: our corporate proxy at work is blocking it (I'm working on getting the block removed, but politics is, alas, a slow game). I've been able to install and upgrade several things (by building from source) since the proxy block started.

Anyway, here' s the stack trace. The error is in the `make` step:

```
==> Downloading https://homebrew.bintray.com/bottles/curl-7.41.0.mavericks.bottle.tar.gz

curl: (22) The requested URL returned error: 403
Error: Failed to download resource "curl"
Download failed: https://homebrew.bintray.com/bottles/curl-7.41.0.mavericks.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading http://curl.haxx.se/download/curl-7.41.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/curl-7.41.0.tar.bz2
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/curl/7.41.0 --with-darwinssl --without-libssh2 --without-libidn --without-libmetalink --without-gss
==> make install
grep: /Users/build/gsherry/tools/openldap/2.3.38/dist/osx105_x86/lib/liblber.la: No such file or directory
sed: /Users/build/gsherry/tools/openldap/2.3.38/dist/osx105_x86/lib/liblber.la: No such file or directory
libtool: link: `/Users/build/gsherry/tools/openldap/2.3.38/dist/osx105_x86/lib/liblber.la' is not a valid libtool archive
make[1]: *** [libcurl.la] Error 1
make: *** [install-recursive] Error 1

READ THIS: http://git.io/brew-troubleshooting

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:256:in `open_http': Non-HTTP proxy URI: https://dt203199:FuckYou2345@dstproxy.dstcorp.net:9119 (RuntimeError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
	from /usr/local/Library/Homebrew/utils.rb:343:in `open'
	from /usr/local/Library/Homebrew/utils.rb:375:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:403:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:145:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:141:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:186:in `dump'
	from /usr/local/Library/brew.rb:162:in `rescue in <main>'
	from /usr/local/Library/brew.rb:65:in `<main>'
```

Looking over the stack trace again, who the hell is `gsherry` (in `/Users/build/gsherry`)? There's no user on my system with that username.

**Comment by jackmaney** [comment]
Huh....unsetting `DYLD_LIBRARY_PATH` and then another `brew install curl`, and all is right again. I take it there was some kind of conflict with existing libraries in that path? This is possibly a silly question, but would there be a way to manually register pre-existing libraries with Homebrew (as a way to say "please don't link to libraries in these directories if you can find them elsewhere")?

**Comment by jacknagel** [comment]
>This is possibly a silly question, but would there be a way to manually register pre-existing libraries with Homebrew (as a way to say "please don't link to libraries in these directories if you can find them elsewhere")?

There's not; we don't really have that level of control over the linker.

We don't really support running with `DYLD_LIBRARY_PATH` set. That's not to say that you can't both (a) use Homebrew and (b) use `DYLD_LIBRARY_PATH`, rather, just that we disclaim responsibility for build failures when it is set. Hence the doctor warning.
