### ISSUE TITLE
brew install nu failed

### ISSUE THREAD

**Issue by AthrunZala** [Homebrew/homebrew#37341]
I want to install nu language, but failed. What is my problem?

$ ./brew install nu
==> Downloading https://github.com/timburks/nu/archive/v2.1.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/nu-2.1.1.tar.gz
==> make
==> ./mininush tools/nuke
nuke: cp 'nu/nibtools.nu' 'Nu.framework/Versions/A/Resources/nibtools.nu'
nuke: cp 'nu/template.nu' 'Nu.framework/Versions/A/Resources/template.nu'
nuke: mkdir 'Nu.framework/Versions/A/Headers'
nuke: /usr/bin/clang -Wall -g -fPIC -O2 -DMACOSX   -DHAVE_CONFIG_H -fobjc-exceptions -fobjc-gc -arch x86_64  -I/usr/include  -I./include  -I./include/Nu  -I/usr/include/ffi -c -o build/x86_64/Nu.o objc/Nu.m
nuke: terminating on command error (return code 1)

READ THIS: http://git.io/brew-troubleshooting

$ ./brew gist-logs nu
https://gist.github.com/5cef851698a3da2505a6

**Comment by tdsmith** [comment]
We may need to pull in this commit: https://github.com/timburks/nu/pull/74

**Comment by tdsmith** [comment]
This should be fixed in dc50d2b; it should work after `brew update`. Thanks for the report!

**Comment by AthrunZala** [comment]
It seems error: garbage collection is no longer supported, -fobjc-gc needs to be deleted.

**Comment by AthrunZala** [comment]
Thank you! I will try!

**Comment by AthrunZala** [comment]
It is OK now.:)
