### ISSUE TITLE
Cannot compile JavaHL without a suitable JDK.

### ISSUE THREAD

**Issue by kid0416** [Homebrew/homebrew#37351]
when I install JavaHL on my macbook with the command: 
 brew install --universal --java subversion
 this following error appears:
  configure: error: Cannot compile JavaHL without a suitable JDK.
                  Please specify a suitable JDK using the --with-jdk option.
the whole logs are as following:
   chilajiaodediudiudeMacBook-Pro:local kid$ brew install --universal --with-java subversion
==> Downloading http://www.apache.org/dyn/closer.cgi?path=subversion/subversion-
Already downloaded: /Library/Caches/Homebrew/subversion-1.8.11.tar.bz2
==> Patching
patching file configure
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
==> Downloading https://serf.googlecode.com/svn/src_releases/serf-1.3.8.tar.bz2
Already downloaded: /Library/Caches/Homebrew/subversion--serf-1.3.8.tar.bz2
==> /Users/kid/JAVA/homebrew/opt/scons/bin/scons PREFIX=/Users/kid/JAVA/homebrew
==> /Users/kid/JAVA/homebrew/opt/scons/bin/scons install
Warning: JAVA_HOME is set. Try unsetting it if JNI headers cannot be found.
==> ./configure --prefix=/Users/kid/JAVA/homebrew/Cellar/subversion/1.8.11 --wit
checking where to install Ruby extensions... /Library/Ruby/Site/2.0.0/universal-darwin13
checking how to use output level for Ruby bindings tests... normal
checking for ctypesgen.py... none
configure: error: Cannot compile JavaHL without a suitable JDK.
                  Please specify a suitable JDK using the --with-jdk option.

READ THIS: http://git.io/brew-troubleshooting

These open issues may also help:
Subversion fails on 10.10 --with-python (https://github.com/Homebrew/homebrew/issues/34119)

Any body who knows how to fix it?  Thanks a lot for sending me an email or reply the issue.

**Comment by mistydemeo** [comment]
> READ THIS: http://git.io/brew-troubleshooting

Cuould you please follow these instructions and provide the requested diagnostics? Thanks!

**Comment by xu-cheng** [comment]
I will look into this late of today. It relates to my current Java work.

**Comment by xu-cheng** [comment]
I tested it locally. It builds fine with me. Can you follow the http://git.io/brew-troubleshooting ? Thanks.
