### ISSUE TITLE
unison crashes during sync

### ISSUE THREAD

**Issue by DavidCWGA** [Homebrew/homebrew#37378]
During a sync with a FreeBSD machine over ssh:

```
Unison failed: Uncaught exception Failure("input_value: bad bigarray kind")
Raised by primitive operation at file "/wrkdirs/usr/ports/net/unison/work/unison-2.48.3/remote.ml", line 453, characters 18-45
Called from file "/wrkdirs/usr/ports/net/unison/work/unison-2.48.3/remote.ml", line 459, characters 23-61
Called from file "/wrkdirs/usr/ports/net/unison/work/unison-2.48.3/lwt/lwt.ml", line 75, characters 20-23
Re-raised at file "/wrkdirs/usr/ports/net/unison/work/unison-2.48.3/lwt/lwt.ml", line 135, characters 12-13
Called from file "list.ml", line 73, characters 12-15
Called from file "/wrkdirs/usr/ports/net/unison/work/unison-2.48.3/lwt/lwt.ml", line 31, characters 2-37
Called from file "/wrkdirs/usr/ports/net/unison/work/unison-2.48.3/lwt/lwt.ml", line 83, characters 17-46
Called from file "/wrkdirs/usr/ports/net/unison/work/unison-2.48.3/lwt/generic/lwt_unix_impl.ml", line 147, characters 6-40
Called from file "/wrkdirs/usr/ports/net/unison/work/unison-2.48.3/main.ml", line 202, characters 6-24
Called from file "/wrkdirs/usr/ports/net/unison/work/unison-2.48.3/main.ml", line 131, characters 4-9
```

This is the same error as #33719, except that in that case, the error prevented you from running unison at all. Now, the sync starts, a few files are copied, and then the above error occurs.

**Comment by DavidCWGA** [comment]
This may in fact be the same bug. :( Ocaml on FreeBSD is older than the one in Homebrew. Is there any way to tell Homebrew to build Unison with an older version of Ocaml?

**Comment by tdsmith** [comment]
Are you sure the crashes are similar? This is an exception during operation and that was a segfault at launch.

Unless you think this is Homebrew-specific I would try exploring unison's community for support; you can launch the website with `brew home unison`. I'll close this ticket for now; please give a shout if I'm wrong or if you discover that a fix is available. Thanks!

**Comment by DavidCWGA** [comment]
I manually rebuilt unison with an old version of ocaml (not using Homebrew) and the problem went away.

It would be nice if there was a way to do this inside Homebew.

**Comment by tdsmith** [comment]
There isn't, sorry. Would you mind filing an issue with unison about this? If they report that they've committed a fix we can apply the patch to our formula.

**Comment by DavidCWGA** [comment]
After some further research, it turns out there is a kinda-sorta way to do this in Homebrew.

"brew versions ocaml" shows:
````
4.01.0   git checkout 924387b /usr/local/Library/Formula/objective-caml.rb
````
(The version I want)

Then:
````
cd `brew --prefix`/Library
git checkout 924387b `brew --prefix`/Library/Formula/objective-caml.rb
brew install ocaml
````

This gets you the required version of ocaml. You do still have to build unison from source manually, but this at least makes the intermediate step easier.

Upstream bug is here already: http://caml.inria.fr/mantis/view.php?id=6621 - though it's already marked fixed.

**Comment by tdsmith** [comment]
I do not believe that's the same issue since the crash is different. Please file a new issue with unison if you'd like to see this bug fixed. Thanks!

**Comment by tdsmith** [comment]
In fact, we're already serving the "fixed" version, so the fix for that bug is not fixing the problem you're observing.

**Comment by sje30** [comment]
Thank you David for your recipe for installing ocaml 4.01.  I used this, and then could build Unison from source to talk to unison on linux also built using 4.01.

**Comment by mahmoudimus** [comment]
@DavidCWGA @sje30 just got this same error.

# linux
```bash
ocaml -vnum
4.01.0
```

**Comment by sje30** [comment]
If it is any help, my binary for mac built with 4.01 (v 2.48.3, built 2015-06-17) is available at http://alan.petitepomme.net/unison/index.html

**Comment by tseven** [comment]
@sje30 Thank you for this. It saved me a lot of headache.

**Comment by sje30** [comment]
you're welcome!  Thanks in turn to the others in the thread who pointed out the ocaml version problem.

**Comment by tseven** [comment]
@sje30 I use unison exclusively in the command line and am running into to configuration issues when using the UI version with the `-ui text` flag. It's difficult to tell which .prf file it's loading. It also seems to be ignoring my attempts to disable syncing permissions and chmod settings.

Can you add a text only version of 2.48.3?

Thanks

**Comment by sje30** [comment]
Hi @tseven  I'm not sure how to build a text-only version.  Do you have any pointers as to why it might solve your problem?  I would have thought the UI would not affect the things you are seeing.

**Comment by tseven** [comment]
I don't, sorry. It may not be an issue with how Unison was built after all.
I installed it on a Yosemite VM via brew and copied the binary to my El Capitan system and observed the same issues.

Unison seems to ignore my attempts to have it not chmod the files being transferred.
I'm using for web development and the file ends up getting chmod'd to 600 despite setting the command line options:
`-perms=0 -dontchmod`
and

> perms=0
> group=false
> owner=false
> dontchmod=true

in the default.prf file.

**Comment by thallada** [comment]
@sje30 your link to the 2.48.3 binary isn't loading for me.

**Comment by sje30** [comment]
@thallada it looks like they have now moved to a dedicated site:

http://unison-binaries.inria.fr/

http://unison-binaries.inria.fr/files/Unison-OS-X-2.48.3.zip
