### ISSUE TITLE
graphviz does not build with --with-bindings

### ISSUE THREAD

**Issue by halloleo** [Homebrew/homebrew#37388]
On Yosemite I cannot build `graphviz` with the option `--with-bindings`.

Verbose log at https://gist.github.com/halloleo/d821f08d7f8f03ff3cfe#file-brew-graphviz-withbindings-failure-log

**Comment by halloleo** [comment]
I should add, that `graphviz` builds fine without `--with-bindings` (and even with `--with-freetype --with-librsvg --with-pango --with-app`).

**Comment by tdsmith** [comment]
Looks like we should declare a java dependency for the bindings. Does this work after installing java? You can install it (using homebrew-cask) with `brew install Caskroom/cask/java` if you like.

**Comment by halloleo** [comment]
Indeed, once I have installed the caskroom-java I do not get the error anymore.

**However**: I was surprised to see that cask installs stuff outside `/usr/local/`. But I guess, that's just what it is...
