### ISSUE TITLE
<boost-oldversions> 1.47.0, 1.49.0 failed to build on 10.10

### ISSUE THREAD

**Issue by lesnerchen** [Homebrew/homebrew#37381]
Hi all.
I was tried to install boost from old version, and failed at 1.47.0 and 1.49.0
here's the output
LlesnerreydeMBP:build llesneraaudrey$ brew versions boost
Warning: brew-versions is unsupported and will be removed soon.
You should use the homebrew-versions tap instead:
  https://github.com/Homebrew/homebrew-versions

1.57.0   git checkout ab47508 /usr/local/Library/Formula/boost.rb
1.56.0   git checkout c7dd3f5 /usr/local/Library/Formula/boost.rb
1.55.0   git checkout a252214 /usr/local/Library/Formula/boost.rb
1.54.0   git checkout c7cf75e /usr/local/Library/Formula/boost.rb
1.53.0   git checkout ce0b989 /usr/local/Library/Formula/boost.rb
1.49.0   git checkout 112c433 /usr/local/Library/Formula/boost.rb
1.47.0   git checkout 6f7dffe /usr/local/Library/Formula/boost.rb
1.46.1   git checkout 83ed494 /usr/local/Library/Formula/boost.rb
1.46.0   git checkout 0476235 /usr/local/Library/Formula/boost.rb
1.45.0   git checkout c65892f /usr/local/Library/Formula/boost.rb
1.44.0   git checkout a18c756 /usr/local/Library/Formula/boost.rb
1.43.0   git checkout 3640fb9 /usr/local/Library/Formula/boost.rb
1.42.0   git checkout c5d56bc /usr/local/Library/Formula/boost.rb
1.40.0   git checkout 928317d /usr/local/Library/Formula/boost.rb
LlesnerreydeMBP:build llesneraaudrey$ cd $(brew --prefix)
LlesnerreydeMBP:local llesneraaudrey$ git checkout 6f7dffe Library/Formula/boost.rb
LlesnerreydeMBP:local llesneraaudrey$ brew install boost
==> Downloading http://downloads.sourceforge.net/project/boost/boost/1.47.0/boos
Already downloaded: /Library/Caches/Homebrew/boost-1.47.0.tar.bz2
Warning: MD5 support is deprecated and will be removed in a future version.
Please switch this formula to SHA1 or SHA256.
==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost/1.47.0 --libdir=/usr/local/C
==> ./bjam --prefix=/usr/local/Cellar/boost/1.47.0 --libdir=/usr/local/Cellar/bo
...skipped <pbin.v2/libs/wave/build/darwin-4.2.1/release/link-static/threading-multi>libboost_wave-mt.a for lack of <pbin.v2/libs/wave/build/darwin-4.2.1/release/link-static/threading-multi>instantiate_cpp_exprgrammar.o...
...skipped <p/usr/local/Cellar/boost/1.47.0/lib>libboost_wave-mt.a for lack of <pbin.v2/libs/wave/build/darwin-4.2.1/release/link-static/threading-multi>libboost_wave-mt.a...
...failed updating 30 targets...
...skipped 20 targets...
...updated 10072 targets...

READ THIS: http://git.io/brew-troubleshooting

**Comment by jacknagel** [comment]
Sorry, but we don't provide support for arbitrary versions pulled from the git history, because we can't make changes to them, among other reasons.

Your best bet is to take the current formula and try to modify it for the version you need.

There is a boost149 formula in homebrew-versions: https://github.com/Homebrew/homebrew-versions
