### ISSUE TITLE
gnuradio has a mis-spelled depencency

### ISSUE THREAD

**Issue by poggs** [Homebrew/homebrew#37391]
Error: undefined method `deponds_on' for Formulary::Formulae::Gnuradio:Class

At a guess, this should be 'depends_on', unless we're talking in a pseudo-French accent

**Comment by pkmoore** [comment]
I could be wrong but I don't see an official formula for gnuradio. Have you tapped a third party repository? Perhaps this one https://github.com/metacollin/homebrew-gnuradio (this formula has the typo you're referring to). If this is the case, you'll need that formula's maintainer to fix it.

**Comment by mikemcquaid** [comment]
Yup, this is from a non-Homebrew tap so please submit it there instead. Thanks!
