### ISSUE TITLE
Ganglia install not working on Macosx Yosemite.

### ISSUE THREAD

**Issue by karpia** [Homebrew/homebrew#37422]
installing Ganglia with be on Yosemite (Darwin Kernel Version 14.1.0) brings this error:

==> ./configure --prefix=/usr/local/Cellar/ganglia/3.6.0 --sbindir=/usr/local/Ce
==> make install
#include <apr_pools.h>
         ^
1 error generated.
make[1]: *** [libgmond.lo] Error 1
make: *** [install-recursive] Error 1

READ THIS: http://git.io/brew-troubleshooting

brew doctor and update already run without errors.

**Comment by mikemcquaid** [comment]
> READ THIS: http://git.io/brew-troubleshooting

Please do.

**Comment by karpia** [comment]
https://gist.github.com/cb34adf4a2d3678fe35b

**Comment by karpia** [comment]
Sorry missed some words from original error:

brew install ganglia
==> Downloading https://downloads.sourceforge.net/project/ganglia/ganglia%20moni
Already downloaded: /Library/Caches/Homebrew/ganglia-3.6.0.tar.gz
==> Downloading https://github.com/ganglia/monitor-core/commit/ba942f.diff
Already downloaded: /Library/Caches/Homebrew/ganglia--patch-f79c4973634d127052e262c22d11e1fec82b5677.diff
==> Patching
patching file libmetrics/darwin/metrics.c
==> ./configure --prefix=/usr/local/Cellar/ganglia/3.6.0 --sbindir=/usr/local/Ce
==> make install
#include <apr_pools.h>
         ^
1 error generated.
make[1]: *** [libgmond.lo] Error 1
make: *** [install-recursive] Error 1

**Comment by asparagui** [comment]
WFM, for what it's worth.

**Comment by jacknagel** [comment]
Probably needs `depends_on :apr => :build`.
