### ISSUE TITLE
gnuplot failed to build on 10.8.5

### ISSUE THREAD

**Issue by ftram** [Homebrew/homebrew#37423]
I wanted to install gnuplot on my mac (Os X 10.8.5) with the interactive terminal wxmac (with option --with-wxmac), but after the installation
1) when I start gnuplot it doesn't set any terminal... it set to "unknow"
2) when I try to plot something it fails giving a malloc error

Then I uninstalled gnuplot and installed again with also the option --with-tests to perform a make check and it failed...
Here the gist I've created:
https://gist.github.com/672bb620ac8f4f5050d3

**Comment by DomT4** [comment]
Try ` brew install gnuplot --with-x11 --with-wxmac `.

**Comment by ftram** [comment]
I've just tried, it doesn't work... almost same errors. Now it recognises the term 'wxt', but if I try to plot something it fails, and gives this error message:
gnuplot(21385,0x7fff743df180) malloc: *** error for object 0x7fff73cc5ef0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

It is the same error message that appears during the building when I install with the option --with-tests in addition to "brew install gnuplot --with-x11 --with-wxmac"

**Comment by DomT4** [comment]
Looks like this [has popped up before](http://earthwithsun.com/questions/441655/gnuplot-on-lion-using-homebrew).

**Comment by ftram** [comment]
Well, I've tried to install with the .configure option "--with-readline=builtin" by editing the formula (I've substituted the existing readline option).
So I've tried with "brew install gnuplot --with-x11 --with-wxmac", with and without "--with-tests".
Same errors I reported before.

**Comment by DomT4** [comment]
Does the problem reproduce if you do a ` gnuplot ` build outside of Homebrew?

**Comment by ftram** [comment]
No, if I do a gnuplot build with MacPorts it works.
Il 12/Mar/2015 03:10 "Dominyk Tiller" <notifications@github.com> ha scritto:

**Comment by DomT4** [comment]
I can't see any significant differences between the MacPorts and Homebrew way of building GnuPlot, so that's a little puzzling. I'll let the maintainers take a swing at this when they see it - I'm a little stumped.

**Comment by jacknagel** [comment]
As a first step, any non-Homebrew libraries and headers that `brew doctor` warns about need to be addressed (i.e., removed, at least temporarily), and the issue reproduced afterwards.
