### ISSUE TITLE
Error: could not find a temporary directory

### ISSUE THREAD

**Issue by Snorvarg** [Homebrew/homebrew#37432]
I created a gist with a decsription of the error here:
https://gist.github.com/83bb0178f118a935eb5d

**Comment by DomT4** [comment]
That's a funky error. What does ` ls -l /tmp ` say for you?

**Comment by Snorvarg** [comment]
Hi, thanks for your quick reply. 

ls -l /tmp gives me this: 
lrwxr-xr-x@ 1 root  wheel  11 Oct 22 11:53 /tmp -> private/tmp

**Comment by DomT4** [comment]
Well, that looks perfectly normal and expected. I presume you don't have a ` tmp ` variable set in your ` bashrc ` or anything similar?

**Comment by mistydemeo** [comment]
Do you have `TMPDIR` set?

**Comment by Snorvarg** [comment]
If I run 'open /tmp', the private/tmp folder pops up as expected. Is there something I can do to temporarily fix this issue, and make homebrew execute 'brew search something' without this error?

**Comment by Snorvarg** [comment]
Thanks for your feedback.

I run "echo $PATH" and get 
/sw/bin:/sw/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

I am not sure how I check if TMPDIR or tmp variables are set.

**Comment by Snorvarg** [comment]
I found it. I run 'printenv' and go this output: 

MANPATH=/sw/share/man:/usr/share/man:/opt/X11/share/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man:/sw/lib/perl5/5.18.2/man
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/d9/wp7s__d52k583k5dp5s43z4m0000gn/T/
PERL5LIB=/sw/lib/perl5:/sw/lib/perl5/darwin
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.BRbP5CxHep/Render
TERM_PROGRAM_VERSION=343.6
OLDPWD=/
TERM_SESSION_ID=AE9EF88A-7D4F-4154-81AA-3E46A961F49C
SGML_CATALOG_FILES=/sw/etc/sgml/catalog
USER=myusername
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.XfdWoDlLTz/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/sw/bin:/sw/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
XML_CATALOG_FILES=/sw/etc/xml/catalog
PWD=/sw
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/myusername
LOGNAME=myusername
LC_CTYPE=UTF-8
INFOPATH=/sw/share/info:/sw/info:/usr/share/info
DISPLAY=/private/tmp/com.apple.launchd.sX1ltWqMVO/org.macosforge.xquartz:0
_=/usr/bin/printenv

**Comment by DomT4** [comment]
Don' t know if that is the problem here. I get a similar reading but no ` brew ` issues around ` tmpdir `.

**Comment by Snorvarg** [comment]
Ouch, this is difficult. I guess the best way would be to uninstall liip, then fink, and then probably make a clean install of apache. As these three different packages probably has been messing around with settings in apache. Problem is I have no idea how to do that on a mac... 

Anyone know how to reset apache to 'factory settings' without also reinstalling the entire os?

**Comment by DomT4** [comment]
Not to my knowledge. Apple doesn't make it terribly easy to restore factory settings to specific parts of the OS. You could theoretically download the app store package, extract it, use something like Pacifist to pull out the Apache elements and then replace them manually, but there's no guarantee that'll work sadly.

You could try the standard Disk Utility Repair Disk/Repair Disk Permissions combo, to see if that irons out any ` /tmp ` access problems, but beyond that I'm really not sure what could have thrown you off here. Your setup and env readout *appears* normal.

**Comment by Snorvarg** [comment]
Thank you for your advices DomT4, I will try your tips just to learn some more about this terrible OS. :) 
Just because I have to say it, I tried to install PHP and xCache in Windows 8, IIS. I got it working in less than two hours. (Next time I just install any linux-distro instead of trying to force the mac to do things it is not supposed to do.)
