### ISSUE TITLE
unable to brew freeglut

### ISSUE THREAD

**Issue by ahromero** [Homebrew/homebrew#37445]
I have tried to brew freeglut, first of all, i did try
brew install freeglut
and it did not find it, then I did try
brew create http://sourceforge.net/projects/freeglut/files/freeglut/2.8.1/freeglut-2.8.1.tar.gz
and then
brew install freeglut
but I am finding a lot of problems for compilation... is there any advise on this?

Thanks!

**Comment by jacknagel** [comment]
Available in homebrew-x11, `brew install homebrew/x11/freeglut`

**Comment by ahromero** [comment]
thanks! very nice.
