### ISSUE TITLE
Add ability to download digits from upstream

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew#37441]
for example get [mac/en-US/Firefox 37.0b2.dmg](http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/37.0b2/mac/en-US/Firefox%2037.0b2.dmg) and verify it with corresponding checksum from [SHA512SUMS](http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/37.0b2/SHA512SUMS), which is previously verified by [SHA512SUMS.asc](http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/37.0b2/SHA512SUMS.asc). And of course set the public part of gpg key is saved in formulae or some variable like ${mozilla-release-key}

Same [issue in Cask](https://github.com/caskroom/homebrew-cask/issues/9910)

**Comment by yurikoles** [comment]
Sorry, it's for cask

**Comment by mikemcquaid** [comment]
Sorry, I think relying on upstream download of these files is a security risk so passing on this.

**Comment by yurikoles** [comment]
>gpg key is saved in formulae or some variable 
Why we can define well known public key in formula or some other **resource supplied by homebrew**. And check the sums file against .asc that is signed with private key.

**Comment by mikemcquaid** [comment]
We may do that for Homebrew's packages now that Bintray supports it but there are no plans at the current time, sorry!

**Comment by DomT4** [comment]
GPG verification of a tarball (or bottle) with a ` .asc ` or `.sig` file against a known upstream key when the user already has GPG available on their system is something I've been playing with for a while. I wrote a basic framework in entirely shell initially, and have been working *slowly* on porting it to Ruby. It's a WIP. I've just kept it private so far to hide my typically super-ugly code :wink:. No promises at all, but it's something I'll get around to proposing to the maintainers one day if nobody beats me to it.

**Comment by yurikoles** [comment]
@DomT4, please share this code with me, let's finish it.

**Comment by DomT4** [comment]
It currently looks a bit like a four year old got quite drunk and scribbled wildly :smile_cat:. It's my side-project as motivation to learn Ruby more, which is why I haven't put it anywhere publicly yet. I've no objections if people want to write up their own (and better) code, but afraid I've locked the code in a cupboard until I'm happier with it. I work on it a little more every few days, It's coming along.

**Comment by yurikoles** [comment]
@DomT4, up?

**Comment by DomT4** [comment]
This will happen at some point, but I'm not going to start working on it again until we handle the core/formula split that is ongoing. I haven't forgotten though and it remains one of my top priorities in regards to core code.
