### ISSUE TITLE
how install python3.3 ? 

### ISSUE THREAD

**Issue by juanpabloaj** [Homebrew/homebrew#37488]
with

    brew install python3

I get python3.4, how I can install python3.3 ?

**Comment by xu-cheng** [comment]
@tdsmith Should we support python 3.x in `homebrew-version`?

**Comment by juanpabloaj** [comment]
I will like have python versions (3.x) because when I use [tox](tox.readthedocs.org) I test the python code over some versiones of python

```bash
$ tox
GLOB sdist-make: /Users/pablo/src/package_name/setup.py
______________________________________________ summary
  py26: commands succeeded
  py27: commands succeeded
ERROR:   py33: InterpreterNotFound: python3.3
  py34: commands succeeded
```

**Comment by tdsmith** [comment]
Please use pyenv: https://github.com/yyuu/pyenv

You can install it with `brew install pyenv`.

pyenv is a good solution for having multiple pythons installed and I think it offers advantages over trying to do the same thing in -versions. If someone set up a useful homebrew-deadsnakes tap (like the Debian deadsnakes PPA) I'd be happy.
