### ISSUE TITLE
Open CV - There is no version 2.4.4 on sourceforge anymore. Brew Install doesn't work.

### ISSUE THREAD

**Issue by lukeschantz** [Homebrew/homebrew#37495]
host:ros_catkin_ws user$ brew info opencv
opencv: stable 2.4.4
http://opencv.org/
Not installed
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/opencv.rb
==> Dependencies
Build: cmake ✔, pkg-config ✔
Required: libpng ✔
Optional: eigen ✔, libtiff ✘, jasper ✘, tbb ✘, qt ✘
==> Options
--32-bit
	Build 32-bit only
--with-eigen
	Build with eigen support
--with-jasper
	Build with jasper support
--with-libtiff
	Build with libtiff support
--with-opencl
	Enable gpu code in OpenCV using OpenCL
--with-qt
	Build the Qt4 backend to HighGUI
--with-tbb
	Enable parallel code in OpenCV using Intel TBB
Error: undefined local variable or method `site_package_dir' for #<Formula opencv (stable) /usr/local/Library/Formula/opencv.rb>
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Formula/opencv.rb:98:in `caveats'
/usr/local/Library/Homebrew/caveats.rb:10:in `caveats'
/usr/local/Library/Homebrew/caveats.rb:22:in `empty?'
/usr/local/Library/Homebrew/cmd/info.rb:137:in `info_formula'
/usr/local/Library/Homebrew/cmd/info.rb:31:in `block in print_info'
/usr/local/Library/Homebrew/cmd/info.rb:28:in `each'
/usr/local/Library/Homebrew/cmd/info.rb:28:in `each_with_index'
/usr/local/Library/Homebrew/cmd/info.rb:28:in `print_info'
/usr/local/Library/Homebrew/cmd/info.rb:18:in `info'
/usr/local/Library/brew.rb:135:in `<main>'
host:ros_catkin_ws user$ brew install opencv
==> Downloading http://sourceforge.net/projects/opencvlibrary/files/opencv-unix/2.4.4/OpenCV-2.4.4.tar.bz2

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "opencv"
Download failed: http://sourceforge.net/projects/opencvlibrary/files/opencv-unix/2.4.4/OpenCV-2.4.4.tar.bz2
host:ros_catkin_ws user$ 

There is no version 2.4.4 on sourceforge anymore.

**Comment by DomT4** [comment]
Your Homebrew is out-of-date. ` opencv ` was moved to Homebrew/Science sometime before April 2013.  ` brew update && brew upgrade && brew install homebrew/science/opencv `.

**Comment by lukeschantz** [comment]
Not the case!  Brew is up to date. 

"Already up-to-date."

**Comment by lukeschantz** [comment]
Thanks.
