### ISSUE TITLE
Error: macvim 7.4-73 did not build

### ISSUE THREAD

**Issue by harshs08** [Homebrew/homebrew#37492]
I am trying to install macvim on OSX 10.10 Yosemite, but I getting the following error:
https://gist.github.com/harshs08/5a7414938bbfbb80a004

I have already looked around and tried to build by using system python and also unlinking brew python, but still I get the same error.

**Comment by tdsmith** [comment]
can you give the output of `brew gist-logs macvim` please?

**Comment by harshs08** [comment]
here are the logs @tdsmith.
https://gist.github.com/dec191cfa541a05c7b2d

**Comment by tdsmith** [comment]
Including `<Python/Python.h>` is relying on clang to find a `Python.framework/Headers/Python.h`. It should look in `/System/Library/Frameworks` first. Does `/System/Library/Frameworks/Python.framework/Headers/Python.h` exist?

**Comment by tdsmith** [comment]
We could consider adding -F `distutils.sysconfig.get_config_vars("PYTHONFRAMEWORKPREFIX")` to PYTHON_CFLAGS to put the active python's framework directory in the header search path.

**Comment by harshs08** [comment]
@tdsmith  it seemed like the Current python was have symlinked to the `Frameworks/Python.framework/ ` but there was no header files present. So created the symlink to brew python installation and macvim is now installed. But now I am wondering, why is the `/System/Library/Frameworks/Python.framework/` empty.

**Comment by tdsmith** [comment]
Something must have happened to your system Python installation. You might consider restoring it from install media.

Glad it's working; let us know if we can help with anything else.
