### ISSUE TITLE
Brew just screwed it all

### ISSUE THREAD

**Issue by highacid** [Homebrew/homebrew#37496]
Kosmos:icu kosmos$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
    echo export PATH='/usr/local/sbin:$PATH' >> ~/.bash_profile
Kosmos:icu kosmos$ echo export PATH='/usr/local/sbin:$PATH' >> ~/.bash_profile
After running the recommendations from brew I get this:

Kosmos:~ kosmos$ ls
-bash: ls: command not found
Kosmos:~ kosmos$ brew
/usr/local/bin/brew: line 10: readlink: command not found
/usr/local/bin/brew: line 25: uname: command not found
/usr/local/bin/brew: line 25: tr: command not found
/usr/local/bin/brew: line 30: exec: ruby: not found
Kosmos:~ kosmos$ ps aux
-bash: ps: command not found
Kosmos:~ kosmos$ 

None of my CMD lines are working anymore. Any workaround this?

**Comment by xu-cheng** [comment]
OK, you incorrectly set the PATH environment variable. To fix this, open  `~/.bash_profile` file. Change ` export PATH='/usr/local/sbin:$PATH' ` to ` export PATH="/usr/local/sbin:$PATH"`.
