### ISSUE TITLE
qtbrowserplugin for mac complie  error: use of undeclared identifier 'GetWindowProperty'

### ISSUE THREAD

**Issue by robinsen** [Homebrew/homebrew#37493]
when i complie  qtbrowserplugin demo on mac,several  compilation errors occur

In file included from ../../src/qtbrowserplugin_mac.mm:60:
../../src/qtbrowserplugin_mac.mm:80:28: error: use of undeclared identifier 'HIViewGetWindow'
        WindowRef window = HIViewGetWindow(root);
                           ^
../../src/qtbrowserplugin_mac.mm:83:37: error: use of undeclared identifier 'MacGetTopLevelWindow'
        WindowPtr temp = (WindowPtr)MacGetTopLevelWindow()->MacGetWindowRef();
                                    ^
../../src/qtbrowserplugin_mac.mm:85:15: error: use of undeclared identifier 'GetWindowProperty'
        err = GetWindowProperty(window,
              ^
../../src/qtbrowserplugin_mac.mm:92:13: error: use of undeclared identifier 'RemoveWindowProperty'
            RemoveWindowProperty(window, kWidgetCreatorQt, kWidgetPropertyQWidget);
            ^
../../src/qtbrowserplugin_mac.mm:97:15: error: use of undeclared identifier 'SetWindowProperty'
        err = SetWindowProperty(window,
              ^
../../src/qtbrowserplugin_mac.mm:276:51: error: use of undeclared identifier 'adjustCursorEvent'
    if(event->what == nullEvent || event->what == adjustCursorEvent) {
                                                  ^
../../src/qtbrowserplugin_mac.mm:284:9: error: use of undeclared identifier 'GetMouse'
        GetMouse(&currentPosition);
        ^
../../src/qtbrowserplugin_mac.mm:285:24: error: redefinition of 'currentPosition' with a different type: 'HIPositioning (&)' (aka 'HIPositioning &') vs 'Point'
        HIPositioning(&currentPosition);
                       ^
../../src/qtbrowserplugin_mac.mm:283:14: note: previous definition is here
       Point currentPosition;
             ^
../../src/qtbrowserplugin_mac.mm:285:24: error: declaration of reference variable 'currentPosition' requires an initializer
        HIPositioning(&currentPosition);
                       ^~~~~~~~~~~~~~~
../../src/qtbrowserplugin_mac.mm:290:13: error: use of undeclared identifier 'FindWindow'
            FindWindow(currentPosition, &wp);
            ^
../../src/qtbrowserplugin_mac.mm:292:22: error: use of undeclared identifier 'GetWindowFromPort'
            if(wp == GetWindowFromPort((CGrafPtr)This->window->port))
                     ^
../../src/qtbrowserplugin_mac.mm:303:63: warning: 'Button' is deprecated: first deprecated in OS X 10.6 [-Wdeprecated-declarations]
                QMouseEvent qme(QEvent::MouseMove, plocal, p, Button() ? Qt::LeftButton : Qt::NoButton,
                                                              ^
/Applications/Xcode6-Beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/Events.h:402:1: note: 'Button' has been explicitly marked deprecated here
Button(void)                                                  AVAILABLE_MAC_OS_X_VERSION_10_0_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_6;
^
../../src/qtbrowserplugin_mac.mm:365:13: error: use of undeclared identifier 'FindWindow'
            FindWindow(event->where, &wp);
            ^
../../src/qtbrowserplugin_mac.mm:392:31: error: use of undeclared identifier 'GetWindowFromPort'
                else if(wp == GetWindowFromPort((CGrafPtr)This->window->port))
                              ^
../../src/qtbrowserplugin_mac.mm:512:27: error: use of undeclared identifier 'GetWindowFromPort'
    WindowPtr windowptr = GetWindowFromPort((CGrafPtr)This->window->port);
                          ^
../../src/qtbrowserplugin_mac.mm:515:11: error: use of undeclared identifier 'GetRootControl'
    err = GetRootControl(windowptr,&root);
          ^
../../src/qtbrowserplugin_mac.mm:517:16: error: use of undeclared identifier 'HIViewGetRoot'
        root = HIViewGetRoot(windowptr);
               ^
../../src/qtbrowserplugin_mac.mm:530:27: error: use of undeclared identifier 'GetWindowFromPort'
    WindowPtr windowptr = GetWindowFromPort((CGrafPtr)This->window->port);
                          ^
../../src/qtbrowserplugin_mac.mm:532:5: error: use of undeclared identifier 'GetWindowBounds'
    GetWindowBounds(windowptr, kWindowContentRgn, &content_r);
    ^
../../src/qtbrowserplugin_mac.mm:534:5: error: use of undeclared identifier 'GetWindowBounds'
    GetWindowBounds(windowptr, kWindowStructureRgn, &structure_r);
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
make: *** [qtbrowserplugin_mac.o] Error 1
10:51:53: 进程"/usr/bin/make"退出，退出代码 2 。
Error while building/deploying project grapher (kit: Desktop Qt 5.3 clang 64bit)
When executing step "Make"
10:51:53: Elapsed time: 00:04.

findwindow() was not supporet on 64bits mac, what function can replace it?

**Comment by mikemcquaid** [comment]
This doesn't seem to be a question about Homebrew. You're probably better off addressing this somewhere with Qt itself.

**Comment by robinsen** [comment]
thanks @mikemcquaid
