### ISSUE TITLE
moc failed to build on 10.10.2

### ISSUE THREAD

**Issue by chrismulderza** [Homebrew/homebrew#37501]
Trying to build moc-2.5.0 with command: brew install moc --with-faad2 --with-libmagic --with-libsndfile --with-mad --with-musepack --with-ncurses --with-speex --with-timidity --with-wavpack

Gist here: https://gist.github.com/anonymous/2b591f2da6e89b398ac6

**Comment by asparagui** [comment]
Can confirm.  Relevant bits:

>glibtoolize: Remember to add 'LT_CONFIG_LTDL_DIR([libltdl])' to 'configure.in'.
>glibtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.in,
>glibtoolize: and rerunning glibtoolize and aclocal.
>autoreconf: glibtoolize failed with exit status: 1

Edit: Jack is fixing, just wait: #37505.
