### ISSUE TITLE
brew upgrade: Don't exit failure when a formula is already up to date

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew#37538]
As a scripter, I want `brew upgrade [<formula>]` to exit with a shell success state when formulas are already up to date, so that provisioning scripts are easier to write.

**Comment by jacknagel** [comment]
We can't change the CLI interface in this way, since people have scripts written against the existing behavior and changing it will break those scripts. See #27048 (among many others) for previous discussion.

You can do things like `brew outdated <formula> || brew upgrade <formula>` instead.
