### ISSUE TITLE
fail2ban needs patch to prevent jails going idle when a log file takes >2 seconds to rotate

### ISSUE THREAD

**Issue by dancriel** [Homebrew/homebrew#37534]
fail2ban by default waits only 2 seconds when attempting to read a log file that has been rotated, before throwing a "too many errors" message and setting all jails idle.  There is a patch on MacPorts which increases this timeout to 20 seconds.  I am submitting here for consideration to include this patch in the brew formula for v0.8.14 as well.
https://trac.macports.org/ticket/46546

**Comment by mikemcquaid** [comment]
Please submit this patch to the upstream project.

**Comment by jacknagel** [comment]
Closing as something that needs to happen upstream rather than in Homebrew.
