### ISSUE TITLE
When running BREW DOCTOR

### ISSUE THREAD

**Issue by highacid** [Homebrew/homebrew#37558]
Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
    echo export PATH='/usr/local/sbin:$PATH' >> ~/.bash_profile

I tried several times to make the ECHO command, useless brew still same thing back at me, without ECHO, it breaks cmd line, this is a bit dangerous guys to play with outside there in masses. This is far beyond a HUGE glitch or even BUG.

Enjoy

**Comment by mikemcquaid** [comment]
If you run `brew update` and then `brew doctor` you'll see it doesn't say that any more. If you remove the echo, it won't work. If you run the command as-is (even in your older version) it will work.

Also, your tone both here and your comment on the previous pull request are not in keeping with our Code of Conduct: https://github.com/Homebrew/homebrew/blob/master/CODEOFCONDUCT.md

Please read it before posting again, thanks.

**Comment by highacid** [comment]
Kosmos:~ kosmos$ brew update
Updated Homebrew from 9bbd6637 to eec62ee3.
==> Updated Formulae
android-ndk		cairo			chkrootkit		commonmark		google-sql-tool		ld64			moc			st			tor			yuicompressor
android-platform-tools	capstone		collectd		denominator		jboss-forge		macvim			mvnvm			stklos			vegeta
android-sdk		checkstyle		colorsvn		fzf			juju-quickstart		mmv			rush			tig			yconalyzer
==> Deleted Formulae
xar
Kosmos:~ kosmos$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
    echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
Kosmos:~ kosmos$

**Comment by mikemcquaid** [comment]
Yes, see, the quoting has changed.
