### ISSUE TITLE
moc install against latest berkeley-db and jack fails to run

### ISSUE THREAD

**Issue by justinpitts** [Homebrew/homebrew#37569]
I installed Moc today, which also installed dependencies berkeley-db 6.1 and jack.
Mocp fails to start; it seems to want to specifically link to libdb version 5.3 and libjack.0.

I can downgrade berkeley-db, but not jack:
    curl: (22) The requested URL returned error: 404 Not Found
    Error: Failed to download resource "jack"
    Download failed: http://jackaudio.org/downloads/jack-audio-connection-kit-0.121.3.tar.gz

**Comment by jacknagel** [comment]
>Download failed: http://jackaudio.org/downloads/jack-audio-connection-kit-0.121.3.tar.gz

`brew update`; we're packaging a newer version than this.

**Comment by justinpitts** [comment]
My apologies, I failed to make this clear before.

jack: stable 0.124.1 is what I tried first. I tried falling back to .121.3, which brew could not even download.

I don't think this is a jack problem, I think it is a moc or moc.rb issue. I'm unsure which.

**Comment by mistydemeo** [comment]
Could you please provide some additional information about the error you're having with moc (like the error message itself), as well as follow the [troubleshooting guide](http://git.io/brew-troubleshooting)? Thanks!

**Comment by justinpitts** [comment]
Will provide more when I get home, but moc is attempting to load the libdb
5.3 dylib instead of the 6.x one that is installed by brew.

**Comment by mistydemeo** [comment]
I can reproduce, it looks like the bottle's bad.

**Comment by mistydemeo** [comment]
Pushed a new set of bottles; these ones are fine.

**Comment by justinpitts** [comment]
Thank you @mistydemeo this fixes my issue. Moc fits my use case perfectly.
