### ISSUE TITLE
grails-2.3.11

### ISSUE THREAD

**Issue by ma-silveira** [Homebrew/homebrew#37594]
New Formula grails-2.3.11.

url 'http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.3.11.zip'
sha1 'f483bcf938f6fc5a9e4913b83d4da3c3f94d8785'

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
