### ISSUE TITLE
Related to brew doctor & brew update repeating the echo ...

### ISSUE THREAD

**Issue by highacid** [Homebrew/homebrew#37606]
Kosmos:~ kosmos$ brew update
Updated Homebrew from 9bbd6637 to eec62ee3.
==> Updated Formulae
android-ndk		cairo			chkrootkit		commonmark		google-sql-tool		ld64			moc			st			tor			yuicompressor
android-platform-tools	capstone		collectd		denominator		jboss-forge		macvim			mvnvm			stklos			vegeta
android-sdk		checkstyle		colorsvn		fzf			juju-quickstart		mmv			rush			tig			yconalyzer
==> Deleted Formulae
xar
Kosmos:~ kosmos$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
    echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
Kosmos:~ kosmos$

**Comment by highacid** [comment]
Kosmos:~ kosmos$ brew install cask
Warning: cask-0.7.2 already installed
Kosmos:~ kosmos$ brew cask install soundcleod
Error: Unknown command: cask
Kosmos:~ kosmos$

**Comment by DomT4** [comment]
Please note the ` cask ` formula in Homebrew/Homebrew is *not* for Caskroom/homebrew-cask. To install the Caskroom you want ` brew install caskroom/cask/brew-cask `.

**Comment by highacid** [comment]
@DomT4 got that working, still the brew update followed by brew doctor and the anoying warning even after running the PATH is a issue.

**Comment by mikemcquaid** [comment]
`echo $PATH` please so we can see it. Alternatively, don't run `brew doctor` if it annoys you.

**Comment by highacid** [comment]
Kosmos:~ kosmos$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
Kosmos:~ kosmos$

**Comment by highacid** [comment]
Kosmos:~ kosmos$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
    echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
Kosmos:~ kosmos$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
Kosmos:~ kosmos$ nano ~/.bash_profile
Kosmos:~ kosmos$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
Kosmos:~ kosmos$

**Comment by mikemcquaid** [comment]
The message is as expected; `/usr/local/sbin` is not in your PATH but it should be. If you follow the command printed it'll be added.
