### ISSUE TITLE
missing gen-msg.map file

### ISSUE THREAD

**Issue by Drewshg312** [Homebrew/homebrew#37609]
Hi!
In the latest version of **snort** missing gen-msg.map file
That causing this kind of problem when running barnyard2:

ERROR: Unable to open Generator file "/etc/snort/gen-msg.map": No such file or directory
ERROR: [Barnyard2Init()], failed while processing [/etc/snort/gen-msg.map]
Fatal Error, Quitting..
Barnyard2 exiting
...

It can be downloaded from here:
https://www.snort.org/configurations

**Comment by jacknagel** [comment]
>In the latest version missing gen-msg.map file

the latest version of what?

Please provide more details, thanks.

**Comment by DomT4** [comment]
They ship those files in the tarball; They just aren't installed by ` make install ` for some reason. Have a fix locally, just ironing out a couple of unrelated things before pushing.

**Comment by DomT4** [comment]
Submitted in #37614.

@Drewshg312 Although we're installing the necessary files with the #37614 PR you may need to tell Barnyard2 where those are located, since it's looking in ` /etc/snort/ ` rather than ` HOMEBREW_PREFIX/etc/snort `.

**Comment by Drewshg312** [comment]
K! thanx!
