### ISSUE TITLE
node: npm_modules folder permissions error (nobody:staff)

### ISSUE THREAD

**Issue by thedannywahl** [Homebrew/homebrew#37618]
I had previously installed node via homebrew, and used `brew switch node 0.10.36`.  Today I switched to 0.12 using `brew switch 0.12.0`.  After switching I followed the caveats `npm install -g npm@latest` but it throws an error about postinstall not running successfully.  I run postinstall manually and it reveals a permissions error on the `AUTHORS` file in /node_modules/npm/.  Turns out the whole /node_modules/ folder and all contained files are owned by nobody instead of \<username\>.  Manually changing recursive folder ownership and re-running resolves the issue.

gist: https://gist.github.com/thedannywahl/8ff71e8f536089dd1e3e#file-gistfile1-sh

brew stuff: 

```language-shell
dannywahlmbp:~ dannywahl$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: eec62ee3a74dec29eefb1cb7d263f23f8cf329e9
Last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit ivybridge
OS X: 10.10.2-x86_64
Xcode: 6.2
CLT: 6.2.0.0.1.1424975374
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.1/bin/ruby
Java: 1.8.0_25
```

**Comment by jacknagel** [comment]
Not sure we can suggest anything; certainly switching between older versions has the potential to result in hard to debug things like this. Closing for now.
