### ISSUE TITLE
hydra lacks afp support

### ISSUE THREAD

**Issue by mig-hub** [Homebrew/homebrew#37631]
Hello,

This is a question about the Hydra formula, but I guess it is related to any formula which potentially has AFP support.

Basically I cannot seem to be able to compile Hydra with AFP support.
I tried `brew install hydra --with-libafp` but it doesn't do anything —which is not that surprising because this option is not in the info.

The thing is that I might be wrong but on a mac, I expect the system to already have libafp somewhere. And anyway I did not find a libafp formula.

So my question is:
Is there a way —like a path to specify— in order to install hydra with afp support? or can the formula be changed in order to be able to compile with afp support?

Before asking, I tried to find and mimic another formula which uses afp already, but I couldn't find one.

Thank you in advance for your help,
mig

**Comment by tdsmith** [comment]
It looks like the library it's looking for is [afpfs-ng](https://sites.google.com/site/alexthepuffin/home); we would accept a pull request if you can get it to build! It's unlikely that the system already provides this interface.

**Comment by mig-hub** [comment]
Alright. Thank you for having a look. I will work on it this week end.

**Comment by mig-hub** [comment]
@tdsmith , sorry this is the first time I contribute to Homebrew, so I'd like to do it as correctly as possible and I have a few questions.

The first one is regarding the fact that `afpfs-ng` does not seem to be maintained. It seems the last version is quite old, and I found [this fork on Github](https:/github.com/simonvetter/afpfs-ng) which keeps on fixing bugs. I made a Formula for this one. Is it okay? or should I stick to the standard version?

My other question is regarding the build. I managed to create a formula for `afpfs-ng` and it seems to build correctly. I can use the binaries. Then I changed the `hydra` in order to have an optional `--with-afpfs-ng`. When I reinstall `hydra` with it, it doesn't complain but it does not work. I checked the code of both libraries and came to the conclusion that —apparently— my formula for `afpfs-ng` puts the lib directory in the cellar, but not the include directory. I even tried to manually put the includes I found in the project into `/usr/local/include`, and then reinstall `hydra` with the option, and it works fine.

So I guess my question is how am I supposed to deal with this problem?
Is there something I should do in the formula to make sure it saves the includes in the cellar and symlinks them?
I checked other formulas with includes symlinked in `/usr/local/include` and they do not seem to have something special.

Thanks in advance for your help.

**Comment by mikemcquaid** [comment]
> The first one is regarding the fact that afpfs-ng does not seem to be maintained. It seems the last version is quite old, and I found this fork on Github which keeps on fixing bugs. I made a Formula for this one. Is it okay? or should I stick to the standard version?

Stick to the standard version. If it's unmaintained though I think we're unlikely to accept it.

**Comment by DomT4** [comment]
Closing here. I don't think there's much actionable - We'd be reluctant to accept an unmaintained library, and we don't accept unofficial forks. If we can work around those two problems, feel free to submit a PR for review. Thanks!
