### ISSUE TITLE
brew update fails with `error: you need to resolve your current index first`

### ISSUE THREAD

**Issue by doque** [Homebrew/homebrew#37637]
I'm trying to run `brew update` after installing homebrew, but am faced with this error:

    me@mbp /usr/local ±master » brew update                                            1 ↵
    README.md: needs merge
    ansible14.rb: needs merge
    appledoc22.rb: needs merge
    bind99.rb: needs merge
    erlang-r16.rb: needs merge
    gcc43.rb: needs merge
    gcc44.rb: needs merge
    gcc45.rb: needs merge
    gcc46.rb: needs merge
    gcc47.rb: needs merge
    gcc49.rb: needs merge
    glfw3.rb: needs merge
    gmp4.rb: needs merge
    gnupg21.rb: needs merge
    go12.rb: needs merge
    hdf4.rb: needs merge
    jenkins-lts.rb: needs merge
    libuv0.rb: needs merge
    llvm35.rb: needs merge
    mkvtoolnix58.rb: needs merge
    node04.rb: needs merge
    node06.rb: needs merge
    node08.rb: needs merge
    percona-server55.rb: needs merge
    postgresql8.rb: needs merge
    postgresql9.rb: needs merge
    postgresql91.rb: needs merge
    postgresql92.rb: needs merge
    postgresql93.rb: needs merge
    solr14.rb: needs merge
    solr36.rb: needs merge
    tomcat7.rb: needs merge
    unison232.rb: needs merge
    error: you need to resolve your current index first
    Error: Failed to update tap: homebrew/versions
    Already up-to-date.
I already tried reinstalling homebrew completely (using this [homebrew_uninstall.sh](https://gist.github.com/mxcl/1173223)), which didn't help. I'm still facing the same issue. I'm running OS X 10.10.2.

**Comment by mikemcquaid** [comment]
Try `cd /usr/local/Library/Taps/homebrew/homebrew-versions; git reset --hard origin/master` and then rerun `brew update`.

**Comment by doque** [comment]
Thank you!
