### ISSUE TITLE
installation of DGTal with option --with-libqglviewer fails

### ISSUE THREAD

**Issue by Tpt** [Homebrew/homebrew#37632]
The installation fails with the error:

```
CMake Error at cmake/CheckDGtalOptionalDependencies.cmake:371 (message):
  libQGLViewer not found.  Check the cmake variables associated to this
  package or disable it.
Call Stack (most recent call first):
  CMakeLists.txt:40 (INCLUDE)
```

With OS X 10.10.2 and XCode 6.2

It looks like the root cause is that the libqglviewer formula is built as an OS X .framework and that DGtal cmake files are not able to link to it.

CC @dcoeurjo

**Comment by dcoeurjo** [comment]
Yes I agree... I'm not really familiar with OSx framework stuff in cmake. 
In the FindQGLVIEWER.cmake, is it sufficient to add a `/Library/Frameworks/ to the path lists ?

**Comment by mikemcquaid** [comment]
You should be able to pass something like e.g. `-DCMAKE_PREFIX_PATH` rather than editing any files.

**Comment by dcoeurjo** [comment]
Agree @mikemcquaid but it seems to be related to an issue in the DGtal project I'd like to solve. 
Before I make any change to the formula, can you please handle this PR (https://github.com/Homebrew/homebrew/pull/37094) which migrates DGtal to homebrew-science ?

**Comment by mikemcquaid** [comment]
@dcoeurjo Done!

**Comment by dcoeurjo** [comment]
Thanks @mikemcquaid !
I've created an issue on homebrew-science (I've new version of the formula with the bug fix): https://github.com/Homebrew/homebrew-science/issues/1963

Can someone close this one ?
