### ISSUE TITLE
MongoDB resource limits are too low

### ISSUE THREAD

**Issue by fmela** [Homebrew/homebrew#37655]
With the release of MongoDB 3.0 and the WiredTiger 3.0 storage engine, the number of open files limit specified in the MongoDB launchctl script is set too low.

WiredTiger puts each collection in its own file, and each index in its own file as well. This means that the number of open files limit currently specified in the launchctl script (1024) is easy to run into. The MongoDB process crashes with an assertion failure when this takes place.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by fmela** [comment]
Closing this (opened #37656 instead)
