### ISSUE TITLE
Question: How can I set a tag to a group of formulae?

### ISSUE THREAD

**Issue by eccstartup** [Homebrew/homebrew#37675]
I mean, if I install a few formulae at once, I want to remember which formulae are installed "together". This is often true because those formulae are installed as dependencies. I wonder if I can add a tag for them so that `I can uninstall them together` when I no longer need them.

Or, if I can see the install history, it is also fine. BTW, I would feel happy when there is a mechanic that `autoremove` unnecessary formulae.

Please help.

**Comment by mikemcquaid** [comment]
There's no support for this currently, I'm afraid. You can use `brew leaves` to identify formulae that you have nothing installed depending on them so you either installed yourself or are left behind. Sorry!
