### ISSUE TITLE
brewed ruby symlinks lib/ruby/gems if it doesn't exist, which shouldn't

### ISSUE THREAD

**Issue by liudangyi** [Homebrew/homebrew#37685]
Brewed ruby installs all gems into `Cellar`. (Although it shows that gems are installed into `/usr/local/lib/ruby/gems/2.2.0`, however, `/usr/local/lib/ruby/gems` is a symbol link for `../../Cellar/ruby/2.2.1/lib/ruby/gems`.)

I think it should use a common lib directory for all versions like python. If it's a bug, I would like to make a PR.

**Comment by mikemcquaid** [comment]
Yeh, it'd be good to keep shared gems in `var`.

**Comment by liudangyi** [comment]
What if I do not want to link some directory? I haven't found in any documents.

**Comment by jacknagel** [comment]
This was already fixed, but if there was a pre-existing symlink from an old install, you may need to `rm -rf /usr/local/lib/ruby/gems` and then reinstall ruby and reinstall the gems for the fix to take effect.

/cc @mistydemeo

**Comment by liudangyi** [comment]
I'm sorry but it hasn't.

```
➜  local git:(master) ✗ ls lib/ruby*
zsh: no matches found: lib/ruby*
➜  local git:(master) ✗ brew install ruby
[snip]
➜  local git:(master) ✗ l lib/ruby  
total 16
lrwxr-xr-x  1 Leedy  admin    38B Mar 14 00:23 2.2.0@ -> ../../Cellar/ruby/2.2.1/lib/ruby/2.2.0
lrwxr-xr-x  1 Leedy  admin    37B Mar 14 00:23 gems@ -> ../../Cellar/ruby/2.2.1/lib/ruby/gems
```

**Comment by mistydemeo** [comment]
The intended configuration is (from my machine):

```
$ ls -l /usr/local/lib/ruby/
total 8
lrwxr-xr-x  1 mistydemeo  admin   38  4 Mar 14:11 2.2.0 -> ../../Cellar/ruby/2.2.1/lib/ruby/2.2.0
drwxrwxr-x  6 mistydemeo  admin  204  4 Mar 14:11 gems
drwxr-xr-x  3 mistydemeo  admin  102  8 Jun  2014 ruby
drwxr-xr-x  4 mistydemeo  admin  136 18 Nov 09:37 site_ruby
```

As Jack mentioned, if you had a pre-existing Ruby install you may need to delete the `/usr/local/lib/ruby/gems` symlink first and then reinstall Ruby.

**Comment by xu-cheng** [comment]
> As Jack mentioned, if you had a pre-existing Ruby install you may need to delete the /usr/local/lib/ruby/gems symlink first and then reinstall Ruby.

I can confirm that a fresh install will still result to gem symlink.

**Comment by liudangyi** [comment]
Gem symlink won't be created only when you already have something under `lib/ruby/gems` (due to a historical version).

**Comment by jacknagel** [comment]
I think this is a more correct patch:

```diff
diff --git a/Library/Homebrew/keg.rb b/Library/Homebrew/keg.rb
index 25656f2..a4d43bc 100644
--- a/Library/Homebrew/keg.rb
+++ b/Library/Homebrew/keg.rb
@@ -288,7 +288,7 @@ def link mode=OpenStruct.new
       when /^perl5/ then :mkpath
       when 'php' then :mkpath
       when /^python[23]\.\d/ then :mkpath
-      when 'ruby' then :mkpath
+      when /^ruby/ then :mkpath
       # Everything else is symlinked to the cellar
       else :link
       end
```

**Comment by liudangyi** [comment]
Both are OK. However, I think homebrew should try to do less formula-specific work. If something can be done in `post_install` then it shouldn't bother main homebrew code.

**Comment by jacknagel** [comment]
I don't think it's really formula-specific (consider the rubyXY formulae in homebrew-versions). And if someone accidentally blows away `/usr/local/lib/ruby`, `brew link` won't re-create the bad links if we fix it in the linking code.
