### ISSUE TITLE
brew install cufflinks failing

### ISSUE THREAD

**Issue by sarahpyfrom** [Homebrew/homebrew#37687]
I had previously had cufflinks installed via homebrew and ran into a Segmentation Fault 11 error. In an attempt to fix the problem I uninstalled and reinstalled cufflinks. My first attempt to reinstall failed with the following error: 

$ brew install cufflinks 
==> Installing cufflinks from homebrew/homebrew-science
==> Downloading http://cufflinks.cbcb.umd.edu/downloads/cufflinks-2.1.1.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "cufflinks"
Download failed: http://cufflinks.cbcb.umd.edu/downloads/cufflinks-2.1.1.tar.gz

I'm not sure why it's attempting to install version 2.1.1. When I go to https://github.com/Homebrew/homebrew-science/blob/master/cufflinks.rb it specifies version 2.2.1.

Any advice would be appreciated as I am baffled as to why I brew install cufflinks worked beautifully a few weeks ago when I first installed it and is now failing.

**Comment by dunn** [comment]
You might be trying to install from an outdated formula. Did you `brew update` first?

**Comment by sarahpyfrom** [comment]
I did run `brew update` first, which is part of why I'm confused.

**Comment by tdsmith** [comment]
Can you try `brew tap --repair`? Failing that, having your `brew config` and `brew doctor` outputs (use a pastebin like [gist](https://gist.github.com)) could be helpful.

**Comment by tdsmith** [comment]
Closing as stale; if you continue to have problems with cufflinks specifically, please raise them at https://github.com/Homebrew/homebrew-science/issues. Thanks!
