### ISSUE TITLE
lastpass-cil version miss match

### ISSUE THREAD

**Issue by vendion** [Homebrew/homebrew#37684]
When trying to install the [Lastpass CLI client](https://github.com/lastpass/lastpass-cli) homebrew says it is pulling 0.4.0_1 but actually installs 0.3.0.

```
╭─vendion@Oden.local ~
╰─➤  lpass --version                                                                                                                                             
LastPass CLI v0.3.0
╭─vendion@Oden.local ~
╰─➤  brew uninstall --force lastpass-cli
Uninstalling lastpass-cli...
╭─vendion@Oden.local ~
╰─➤  which lpass
lpass not found
╭─vendion@Oden.local ~
╰─➤  rm -rf /Library/Caches/Homebrew/lastpass-cli-*                                                                                                              
╭─vendion@Oden.local ~
╰─➤  brew install lastpass-cli --with-pinentry --with-doc
==> Downloading https://github.com/lastpass/lastpass-cli/archive/v0.4.0.tar.gz
######################################################################## 100.0%
==> make PREFIX=/usr/local/Cellar/lastpass-cli/0.4.0_1 install
==> make MANDIR=/usr/local/Cellar/lastpass-cli/0.4.0_1/share/man install-doc
🍺  /usr/local/Cellar/lastpass-cli/0.4.0_1: 5 files, 128K, built in 59 seconds
╭─vendion@Oden.local ~
╰─➤  lpass --version
LastPass CLI v0.3.0
```

Note that I did a ```brew update``` earlier in the day so my local formulas are not out of date.

**Comment by mikemcquaid** [comment]
Are you sure it's not a bug with their version printing?

**Comment by DomT4** [comment]
There's a new version out. I'll bump it locally shortly and see if the error reproduces in the new release.

**Comment by mistydemeo** [comment]
It looks like it's just a bug in lastpass-cli - `version.h` defines the version as 0.3.0, though Homebrew does install 0.4.0.

**Comment by DomT4** [comment]
Looks like they snagged the bug upstream for the new release:

```
lpass -v
LastPass CLI v0.5.0
```

**Comment by vendion** [comment]
What caused me think it was a homebrew issue is on my Linux boxes with lastpass-cli installed printing the version properly displayed ```0.4.0``` so it seemed odd to get two different results.  Looking at the upstream repo they set the version in ```version.h``` to be v0.4.0 on January 8 of this year, but was done after they already tag the v0.4.0 release [link to commit](https://github.com/lastpass/lastpass-cli/commit/e42e8e9930ee489e867ef45e7f9e3ffe7b31cc71).  I guess the Arch package maintainer saw the new commit and pull that instead of the tagged release that had the incorrect version number.

Anyways I'll go ahead and close this then.
