### ISSUE TITLE
Correction to common issue "Python: Fatal Python error: PyThreadState_Get: no current thread"

### ISSUE THREAD

**Issue by gbirke** [Homebrew/homebrew#37698]
When I encountered the error while trying to use the "pyhash" pip module, I've followed the step explained in the "Common Issues" document. However, after removing boost and then reinstalling boost with `brew install boost --build-from-source`, the installation of pyhash did not work, there was this error: 

     ld: library not found for -lboost_python-mt

The solution should read  `brew install boost --build-from-source --with-python` instead. After removing and then reinstalling boost with the additional `--with-python` option the pyhash installation went flawlessly.

**Comment by tdsmith** [comment]
Interestingly, `--with-python` is a no-op; boost-python is provided by the `boost-python` formula now, unless you haven't run `brew update` for a few months. It should still be corrected! Thanks for writing in.

**Comment by DomT4** [comment]
Boost doesn't have a Python option any more. The two were separated out a few months ago, into ` boost ` and ` boost-python `.

**Comment by DomT4** [comment]
Boost doesn't have a Python option any more. The two were separated out a few months ago, into ` boost ` and ` boost-python `.Boost doesn't have a Python option any more. The two were separated out a few months ago, into ` boost ` and ` boost-python `.

**Comment by DomT4** [comment]
Garg. Commented right on top of Tim. Sorry Tim :cry:

**Comment by gbirke** [comment]
Sorry, my fault. I did indeed not update brew for several months :(

**Comment by tdsmith** [comment]
It's no problem! The docs did need updating.
