### ISSUE TITLE
brew-bot CAcert

### ISSUE THREAD

**Issue by denji** [Homebrew/homebrew#37738]
Please implement the CAcert certificates in Jenkins of repositories/url which are used to develop free certifcate from CAcert. Sometimes there are problems, as GNU developers use CAcert

- http://wiki.cacert.org/FAQ/ImportRootCert#Using_the_Keychain_GUI

Thanks in advance.

**Comment by mikemcquaid** [comment]
I don't think it's included in enough places to be worthwhile: http://wiki.cacert.org/InclusionStatus

**Comment by jacknagel** [comment]
I don't understand exactly what is being requested.
