### ISSUE TITLE
Brew update gives errors from Casks that are not installed.

### ISSUE THREAD

**Issue by tjsoftworks** [Homebrew/homebrew#37747]
I have tried all the tricks I know and read thru the troubleshooting docs. I went as far as removing my last remain cask which was vagrant and actually not need as vagrant does it's own install at this point.

>>brew cask list
Warning: nothing to list
>>brew update
error: Your local changes to the following files would be overwritten by merge:
	Casks/dbvisualizer.rb
	Casks/drobo-dashboard.rb
	Casks/launchcontrol.rb
	Casks/myo-connect.rb
	Casks/playonmac.rb
	Casks/thunderbird.rb
Please, commit your changes or stash them before you can merge.
Aborting
Error: Failed to update tap: caskroom/cask
Already up-to-date.
	Casks/thunderbird.rb
The

 >>brew upgrade
 >>brew prune
brew Pruned 0 dead formulae
Tapped 235 formulae

The following fixed the issues. I did not find this fix for a few hours. Perhaps this should be added to the troubleshoot page for cask issues - and a note that is is probably overkill but should do the job.

brew untap caskroom/cask
brew update
brew cleanup --force -s
rm -rf "$(brew --cache)"
brew tap caskroom/cask

**Comment by jacknagel** [comment]
Feel free to send a pull request against the documentation, however I think it is probably an exceptional case.
