### ISSUE TITLE
Some newbie questions regarding Homebrew. Sorry for asking here.

### ISSUE THREAD

**Issue by qbektrix** [Homebrew/homebrew#37746]
I am well aware that this question is in the wrong place but I am a newbie to Mac & *nix systems in general. I have 3 questions and I am sure that is the place where I can find the right answer.
1. What is  __homebrew-cask__  ? Please explain in simple english. Checking the site did not help me.
2. Should I use __sudo brew install app_name__?
3. I want to install VLC, is there a list where I can check if VLC is supported by Homebrew?

**Comment by mikemcquaid** [comment]
You'd be better asking `homebrew-cask` what they are but here goes: `brew cask` is a way of using a Homebrew-like interface (e.g. `brew cask install vlc`) to install software that is already shipped in a compiled form by their developers e.g. VLC or Google Chrome. You should never use (or need to use) `sudo brew` anything. Homebrew does not install VLC but you can install it with `brew cask install vlc` or, if you have Homebrew already installed but not `brew cask`: `brew install Caskroom/cask/vlc`.

Let me know if that helps!
