### ISSUE TITLE
malloc error with ccmake 3.2.1

### ISSUE THREAD

**Issue by quantumsteve** [Homebrew/homebrew#37770]
After upgrading cmake from 3.1.3 to 3.2.1, ccmake crashes with the error below. I got the same error with multiple projects and on both osx 10.9 and 10.10. 

```
ccmake(12487,0x7fff742c3300) malloc: *** error for object 0x7fd8c2c2fa98: incorrect checksum for freed object - object was probably modified after being freed.
                                                                                                                                                               *** set a breakpoint in malloc_error_break to debug
      Abort trap: 6
```

**Comment by iMichka** [comment]
Hi. I got also the same error today and wanted to also report the problem (OS X 10.10). Though it seems to happen only with ccmake to me.

I rebuilt homebrew's cmake 3.2.1 from source, which is also failing.
I built cmake 3.2.1 from source outside of homebrew and that one worked.

Previous versions of cmake were working.

**Comment by mikemcquaid** [comment]
> I built cmake 3.2.1 from source outside of homebrew and that one worked.

@iMichka did you use identical command-line arguments? If not: which did you use/omit? Thanks!

**Comment by hellno** [comment]
I'm getting the same error on 10.10.2 while trying to build different projects.

**Comment by iMichka** [comment]
I did not use any special options. Just ./bootstrap, make and make install.

**Comment by mikemcquaid** [comment]
@iMichka Can you try matching the options used in the CMake formula?

**Comment by iMichka** [comment]
Yes. And I tested them all until I found the one which breaks cmake: --system-libs

**Comment by ilpincy** [comment]
I have the same problem on Yosemite (10.10.2). iMichka's solution works for me too.

**Comment by mikemcquaid** [comment]
@iMichka Could you try and narrow it down to one of these:
```
  --system-curl           use system-installed curl library
  --no-system-curl        use cmake-provided curl library (default)
  --system-expat          use system-installed expat library
  --no-system-expat       use cmake-provided expat library (default)
  --system-jsoncpp        use system-installed jsoncpp library
  --no-system-jsoncpp     use cmake-provided jsoncpp library (default)
  --system-zlib           use system-installed zlib library
  --no-system-zlib        use cmake-provided zlib library (default)
  --system-bzip2          use system-installed bzip2 library
  --no-system-bzip2       use cmake-provided bzip2 library (default)
  --system-libarchive     use system-installed libarchive library
  --no-system-libarchive  use cmake-provided libarchive library (default)
```

Thanks!

**Comment by kazimuth** [comment]
Fix also works for me.
Also, the problem isn't --system-expat, testing others now.

**Comment by iMichka** [comment]
--no-system-libs is the default. --no-system-libarchive --no-system-jsoncpp are set in the formula so that we use cmake's version. I rebuilt everything each time from a fresh build tree:

Failing:
> ./bootstrap --system-libs --no-system-libarchive --no-system-jsoncpp
./bootstrap --system-libs --no-system-libarchive --no-system-jsoncpp --no-system-curl
./bootstrap --system-libs --no-system-libarchive --no-system-jsoncpp --no-system-curl --no-system-expat
./bootstrap --system-libs --no-system-libarchive --no-system-jsoncpp --no-system-curl --no-system-expat --no-system-zlib
./bootstrap --system-libs --no-system-libarchive --no-system-jsoncpp --no-system-curl --no-system-expat --no-system-zlib --no-system-bzip2

Not failing:
> ./bootstrap --system-curl --system-expat --system-zlib --system-bzip2

Conclusion: I have no clue what is going on here.

**Comment by mikemcquaid** [comment]
I'm just gonna set `--no-system-libs`, I think. I don't see an advantage of using our versions.

**Comment by mikemcquaid** [comment]
PR in https://github.com/Homebrew/homebrew/pull/37987.
