### ISSUE TITLE
brew deps should show all dependencies somehow

### ISSUE THREAD

**Issue by joernhees** [Homebrew/homebrew#37802]
`brew deps graph-tool`currently doesn't show dependencies such as matplotlib, numpy, scipy as they are "special python libraries", it seems.

this can be somewhat confusing as not everyone will know that dependencies that can either be fulfilled with pip or with brew might be missing in the normal output of `brew deps`.

it would be cool if brew showed them, maybe with some special markup indicating that they are special in that respect

**Comment by dunn** [comment]
I'd like to see this implemented, but I think it should be with a non-default flags like `--resources`.

**Comment by mikemcquaid** [comment]
> I'd like to see this implemented, but I think it should be with a non-default flag like --resources.

:+1:

**Comment by mikemcquaid** [comment]
Passing on this feature request. We'd accept a pull request in future.
