### ISSUE TITLE
 undefined method `resolve_alias' for Formula:Class

### ISSUE THREAD

**Issue by rahdev** [Homebrew/homebrew#37809]
I get this error when I run 
brew services start rabbitmq.

Error: undefined method `resolve_alias' for Formula:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/bin/brew-services.rb:154:in `service'
/usr/local/bin/brew-services.rb:203:in `check'
/usr/local/bin/brew-services.rb:193:in `run!'
/usr/local/bin/brew-services.rb:397:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'

Note:
I previously ran(to get the services command):
curl -o /usr/local/bin/brew-services.rb https://gist.githubusercontent.com/lwe/766293/raw/75a7907004bbff0eb3b072d1d951be2cfe7e5020/brew-services.rb
chmod +x /usr/local/bin/brew-services.rb

**Comment by jacknagel** [comment]
We don't support `brew-services` here, but that looks like a pretty old version and it is using functionality that no longer exists in the Homebrew codebase.

You'll need to remove it and then get brew-services from wherever it is being maintained these days (I don't know off the top of my head).

**Comment by rahdev** [comment]
Thanks,

I found a way around it, without using brew services.

**Comment by Nayigiziki** [comment]
Would you be so kind to share your work around?

**Comment by rahul-desai3** [comment]
@rahdev Can you please tell us how did you resolve this error? I have been stuck on that.

**Comment by lucianosilva** [comment]
Hey there,

I've been faced this same issue and I figured out this way.

#1
I got this message when I ran brew doctor :
Warning: You have external commands with conflicting names. 
Found command `brew-services` in following places:
    /usr/local/bin/brew-services.rb
    /usr/local/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb

I've been getting this message when I tried to check brew services available  

$ brew services list
Warning: No user-space services controlled by `brew services` running...

#2
So, I decided to remove the first installation that was out of Library/Taps directories.
rm -rf /usr/local/bin/brew-services.rb

#3
Now, to be sure that everything is okay, I ran
brew update && brew upgrade

#4 Finally, brew services is working fine now.

$ brew services list
Name    Status  User    Plist
dnsmasq started root    /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
httpd22 started root    /Library/LaunchDaemons/homebrew.mxcl.httpd22.plist
mysql   started luciano /Users/luciano/Library/LaunchAgents/homebrew.mxcl.mysql.plist
php56   started luciano /Users/luciano/Library/LaunchAgents/homebrew.mxcl.php56.plist

\o/

**Comment by lucianosilva** [comment]
Hey there,

I've been faced this same issue and I figured out this way.

#1
I got this message when I ran brew doctor :
Warning: You have external commands with conflicting names. 
Found command `brew-services` in following places:
    /usr/local/bin/brew-services.rb
    /usr/local/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb

I've been getting this message when I tried to check brew services available  

$ brew services list
Warning: No user-space services controlled by `brew services` running...

#2
So, I decided to remove the first installation that was out of Library/Taps directories.
rm -rf /usr/local/bin/brew-services.rb

#3
Now, to be sure that everything is okay, I ran
brew update && brew upgrade

#4 Finally, brew services is working fine now.

$ brew services list
Name    Status  User    Plist
dnsmasq started root    /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
httpd22 started root    /Library/LaunchDaemons/homebrew.mxcl.httpd22.plist
mysql   started luciano /Users/luciano/Library/LaunchAgents/homebrew.mxcl.mysql.plist
php56   started luciano /Users/luciano/Library/LaunchAgents/homebrew.mxcl.php56.plist

\o/
