### ISSUE TITLE
postgis fails at lib.install, not a formula bug

### ISSUE THREAD

**Issue by CaledoniaProject** [Homebrew/homebrew#37855]
I'm seeing this in logs:

`mv: cannot resolve stage/usr/local/lib/liblwgeom.dylib: /Users/XX/Library/Caches/shm/cache/homebrew/postgis-jWRnxe/postgis-2.1.5/stage/usr/local/lib/liblwgeom-2.1.5.dylib`

I then checked the formula and found out it crashed here:
`lib.install Dir["stage/**/lib/*"]`

Sounds like a homebrew bug rather than the formulas

**Comment by CaledoniaProject** [comment]
Same result after update

**Comment by CaledoniaProject** [comment]
I commented that line out, not sure about the consequences, but it seems to work without these libraries

**Comment by tdsmith** [comment]
Can you share `brew gist-logs postgis`?

**Comment by CaledoniaProject** [comment]
https://gist.github.com/anonymous/fc351bb6bd780fb12559

**Comment by DomT4** [comment]
We fairly drastically changed the `postgis` install recently. Please feel free to open a new issue if that didn't resolve the issue for you, Thanks!
