### ISSUE TITLE
cufflinks failed to build on OS X 10.10, Xcode 6.2

### ISSUE THREAD

**Issue by bslugsc** [Homebrew/homebrew#37876]
Hello, I tried to build cufflinks on a brand new brew install on my MacBook Pro with OS X 10.10. Xcode and CLT are updated to the newest version 6.2. 
Dependencies homebrew/versions/boost149, samtools-0.1, eigen installed fine. 
Installing cufflinks reported:
==> Installing cufflinks
==> Downloading http://cole-trapnell-lab.github.io/cufflinks/assets/downloads/cufflinks-2.2.1.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/cufflinks/2.2.1 --mandir=/usr/local/Cellar/cufflinks/2.2.1/share/man
==> make
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [gtf_to_sam] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

brew updated was run before
brew doctor reported
Your system is ready to brew.

A Gist is available ehre:
https://gist.github.com/1639834c83c2792bc17e

Thank you!

**Comment by DomT4** [comment]
Needs reporting to [Homebrew/Science](https://github.com/Homebrew/homebrew-science) - It's their formula.

**Comment by mikemcquaid** [comment]
This issue was moved to Homebrew/homebrew-science#1983

**Comment by mikemcquaid** [comment]
@Homebrew/owners You can move issues pretty easily between repos with this tool: https://github-issue-mover.appspot.com

It's well worth checking out.

**Comment by bslugsc** [comment]
Thank you DomT4 and mikemcquaid!
