### ISSUE TITLE
brew install cannot run headless

### ISSUE THREAD

**Issue by simonkuhn** [Homebrew/homebrew#37896]
brew install cannot run headless (via a launchd job for instance), because of the tilde expansion required to locate the homebrew cache dir:

    /usr/local/Library/Homebrew/global.rb:25:in `expand_path': couldn't find HOME environment -- expanding `~' (ArgumentError)
	from /usr/local/Library/Homebrew/global.rb:25:in `expand_path'
	from /usr/local/Library/Homebrew/global.rb:25:in `cache'
	from /usr/local/Library/Homebrew/global.rb:41:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:16:in `<main>'

Since the comment indicates this is a historical location for cache data, maybe it's time to just remove this block from global.rb?

    # we do this for historic reasons, however the cache *should* be the same
    # directory whichever user is used and whatever instance of brew is executed
    home_cache = Pathname.new("~/Library/Caches/Homebrew").expand_path
    if home_cache.directory? and home_cache.writable_real?
      home_cache
    else

Or if you want to continue to support this mode of operation, catch the potential error from:

    Pathname.new("~/Library/Caches/Homebrew").expand_path

**Comment by DomT4** [comment]
Does it work if you set the ` HOMEBREW_CACHE ` variable with ` export ` to somewhere tildeless?

**Comment by simonkuhn** [comment]
Yep, my workaround is to set HOMEBREW_CACHE=/Library/Caches/Homebrew. Since the subsequent block is skipped if HOMEBREW_CACHE is set, it works.

**Comment by mikemcquaid** [comment]
I'd be surprised if that's the only place that fails with `$HOME` unset. Perhaps you could just set `$HOME` instead?
