### ISSUE TITLE
Usability issue: ambiguity between `brew update` and `brew upgrade`

### ISSUE THREAD

**Issue by groue** [Homebrew/homebrew#37902]
Hi, homebrew is an awesome tool, and this issue contains a suggestion to improve its usability.

Whenever I want to fetch latests formulas, or upgrade installed formulas, I *never* remember whether I should run `brew upgrade` or `brew update`. *Every time*, I have to type `brew` alone, read the examples, before I can type the command I need.

Why is it so? Both verbs are too close, almost synonyms, since both are used to bump their target to their latest version. Plus, `gem update` is a command that performs the same job as `brew upgrade`. Ouch.

Since homebrew is deeply linked to git, I would suggest adding the `brew fetch` or `brew pull` command. That one would, without any possible ambiguity, "fetch the newest version of Homebrew from GitHub using git" (quoting `man brew`).

That would still let the user confused when she wants to upgrade installed formulas, I agree.

Thanks for reading!

**Comment by mikemcquaid** [comment]
Sorry, both `brew fetch` and `brew pull` are already commands and `apt-get` similarly uses `update` and `upgrade` the same way we do.

**Comment by groue** [comment]
OK, I'll keep hesitating :-)

**Comment by DomT4** [comment]
You could always set an alias in your ` .bash_profile ` or similar, so you only ever have to type one thing to update and upgrade.
