### ISSUE TITLE
some optional dependencies listed as "missing" despite being explicitly disabled after install

### ISSUE THREAD

**Issue by stal888** [Homebrew/homebrew#37900]
When homebrew/science/opencv is installed --without-brewed-numpy, numpy becomes a missing dependency despite being disabled, i.e:
```sh
$ brew install --without-brewed-numpy homebrew/science/opencv
$ brew missing
opencv: numpy
```

A side-effect of this (probably) is that any formula that `depends_on "homebrew/science/opencv" => "without-brewed-numpy"` will not honour that flag.

Apologies if this issue is in the wrong repo.

`brew config`:
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: e54cab533744fe9912e5afa9557106bc94308654
Last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit nehalem
OS X: 10.10.3-x86_64
Xcode: 6.1.1
CLT: N/A
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.7.0_71
```

**Comment by jacknagel** [comment]
https://github.com/Homebrew/homebrew/issues/31374#issuecomment-51292043 provides a technical explanation. The tl;dr is that this is a known issue that is being worked on.
