### ISSUE TITLE
Consider merging fork of sshuttle with Yosemite support

### ISSUE THREAD

**Issue by verdurin** [Homebrew/homebrew#37907]
The fork of sshuttle at https://github.com/sshuttle/sshuttle is intended to address the breakage of this application in Yosemite, owing to the change in firewalls. Please consider supporting this fork, at least until it is merged upstream.

**Comment by mikemcquaid** [comment]
We don't support forks I'm afraid. If the changes are merged upstream we'll be happy to patch the older versions with their backports.

**Comment by Fil** [comment]
I second that, the main tree seems abandoned — and https://github.com/sshuttle/sshuttle works whereas the original apenwarr doesn't

**Comment by tdsmith** [comment]
There was some discussion on the sshuttle mailing list about this: https://groups.google.com/d/msg/sshuttle/pipk8HV7rw4/OeqVbmGwFS0J

Brian May's been performing maintainer duties convincingly at sshuttle/sshuttle. What do we want to have to bless this fork? A note in the apenwarr/sshuttle readme?

**Comment by mikemcquaid** [comment]
> Brian May's been performing maintainer duties convincingly at sshuttle/sshuttle. What do we want to have to bless this fork? A note in the apenwarr/sshuttle readme?

Yeh, ideally something like that.

**Comment by ulope** [comment]
Please, can we have some pragmatism here?

The current release of sshuttle available in Homebrew is completely non-functional on Yosemite. 

It seems rather obvious from looking at the the original repo that the author is no longer interested or able to maintain the project (last commit is over 2 years old). The community has stepped in and picked up the burden.

What possible reason could there be to refuse this PR?

**Comment by mikemcquaid** [comment]
@ulope Has this comment below been addressed?

> Brian May's been performing maintainer duties convincingly at sshuttle/sshuttle. What do we want to have to bless this fork? A note in the apenwarr/sshuttle readme?

**Comment by ulope** [comment]
No, but the above linked google groups discussion does include a post from the creator (apenwarr) that basically gives permission.

**Comment by mikemcquaid** [comment]
I've emailed him.

**Comment by justinkim** [comment]
Did apenwarr ever respond to the email?

**Comment by mikemcquaid** [comment]
No, he didn't. If someone submits a PR to update this to use the fork then I'll merge it.

**Comment by verdurin** [comment]
I've submitted PR  https://github.com/Homebrew/homebrew/pull/39968.

**Comment by DomT4** [comment]
Closing this in favour of #39968 and/or #38581.
