### ISSUE TITLE
The `brew link` step did not complete successfully

### ISSUE THREAD

**Issue by alfista-sk** [Homebrew/homebrew#37911]
When I have used Brew to instal mcrypt i have this error:

The formula built, but is not symlinked into /usr/local
Could not symlink include/mutils/mglobal.h
/usr/local/include/mutils is not writable.

and 

configure: error: "You need at least libmhash 0.8.15 to compile this program.

**Comment by mikemcquaid** [comment]
`sudo chown -R $USER /usr/local` to fix the permission error then `brew reinstall mcrypt`

**Comment by alfista-sk** [comment]
I have done it, restarted apache and have this error:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/extensions/no-debug-non-zts-20121212/mcrypt.so' - dlopen(/usr/lib/php/extensions/no-debug-non-zts-20121212/mcrypt.so, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/extensions/no-debug-non-zts-20121212/pgsql.so' - dlopen(/usr/lib/php/extensions/no-debug-non-zts-20121212/pgsql.so, 9): image not found in Unknown on line 0

**Comment by alfista-sk** [comment]
this the error by making:

Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/libmcrypt-config
Target /usr/local/bin/libmcrypt-config
already exists. You may want to remove it:
  rm '/usr/local/bin/libmcrypt-config'

To force the link and overwrite all conflicting files:
  brew link --overwrite mcrypt

To list all files that would be deleted:
  brew link --overwrite --dry-run mcrypt

Possible conflicting files are:
/usr/local/bin/libmcrypt-config
/usr/local/include/mcrypt.h
/usr/local/include/mutils/mcrypt.h
/usr/local/share/aclocal/libmcrypt.m4
/usr/local/lib/libmcrypt.4.4.8.dylib
/usr/local/lib/libmcrypt.4.dylib -> /usr/local/lib/libmcrypt.4.4.8.dylib
/usr/local/lib/libmcrypt.dylib -> /usr/local/lib/libmcrypt.4.4.8.dylib
==> Summary
🍺  /usr/local/Cellar/mcrypt/2.6.8: 15 files, 452K, built in 54 seconds

I have tried to do:

brew link --overwrite mcrypt

but still doesn't see it by:

php -m

**Comment by alfista-sk** [comment]
please can you tell me if you have this modules too:

gmp (for SFTP storage)
apc
apcu
xcache
imagick
smbclient (for SMB storage)
intl (increases language translation performance and fixes sorting of non-ASCII characters)
mb multibyte

thanks.

**Comment by mikemcquaid** [comment]
I don't know what you're asking, sorry. If you're trying to install stuff for PHP you might be better asking in homebrew-php.

**Comment by alfista-sk** [comment]
ok I will, thanks and hope you can help me with the errors by installing mcrypt.

**Comment by jacknagel** [comment]
Per the above output, `mcrypt` is installed. If you have questions about the php formula, file them here: https://github.com/Homebrew/homebrew-php

**Comment by ccjon** [comment]
Not running brew as root and changing the ownership of all files in /usr/local/bin to some user other than root are recommendations that at odds with one another.
