### ISSUE TITLE
A bug?

### ISSUE THREAD

**Issue by jasonw580** [Homebrew/homebrew#37912]
When I run "brew info pcl",I get the informations below:
pcl: stable 1.7.2 (bottled), HEAD
http://www.pointclouds.org/
Not installed
From: https://github.com/homebrew/homebrew-science/blob/master/pcl.rb
==> Dependencies
Build: cmake ✘, pkg-config ✔
Error: invalid attribute: version (nil)
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula.rb:129:in `validate_attributes!'
/usr/local/Library/Homebrew/formula.rb:96:in `initialize'
/usr/local/Library/Homebrew/formulary.rb:71:in `new'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/dependency.rb:32:in `to_formula'
/usr/local/Library/Homebrew/dependency.rb:38:in `installed?'
/usr/local/Library/Homebrew/cmd/info.rb:146:in `block in decorate_dependencies'
/usr/local/Library/Homebrew/cmd/info.rb:145:in `collect'
/usr/local/Library/Homebrew/cmd/info.rb:145:in `decorate_dependencies'
/usr/local/Library/Homebrew/cmd/info.rb:127:in `block in info_formula'
/usr/local/Library/Homebrew/cmd/info.rb:125:in `map'
/usr/local/Library/Homebrew/cmd/info.rb:125:in `info_formula'
/usr/local/Library/Homebrew/cmd/info.rb:31:in `block in print_info'
/usr/local/Library/Homebrew/cmd/info.rb:28:in `each'
/usr/local/Library/Homebrew/cmd/info.rb:28:in `each_with_index'
/usr/local/Library/Homebrew/cmd/info.rb:28:in `print_info'
/usr/local/Library/Homebrew/cmd/info.rb:18:in `info'
/usr/local/Library/brew.rb:135:in `<main>'

Is there someone can tell me what happened ?

**Comment by DomT4** [comment]
Should really be reported to [Homebrew/science](https://github.com/homebrew/homebrew-science) as it's their formula. That said, ` brew readall ` should help work out what is broken.

**Comment by jacknagel** [comment]
Can't reproduce, but yes, this report belongs on homebrew-science.

**Comment by mikemcquaid** [comment]
@DomT4 @jacknagel Let's use this to move issues now: https://github-issue-mover.appspot.com

**Comment by mikemcquaid** [comment]
This issue was moved to Homebrew/homebrew-science#2006

**Comment by DomT4** [comment]
@mikemcquaid Wasn't sure if the closing of the issues was automated by that tool, which I'd presumably run into problems with in Homebrew/homebrew. If the closing isn't automated though, I'll use that in future for misplaced issues :smiley_cat:

**Comment by mikemcquaid** [comment]
@DomT4 Yeh, it automatically copies the issue and all copies and then closes it.

**Comment by DomT4** [comment]
@mikemcquaid Presumably I'll have to leave a comment and let a maintainer handle the actual issue move for Homebrew/homebrew then? I can do versions and devel though, although thankfully the amount of misplaced issues there is relatively small.

**Comment by mikemcquaid** [comment]
@DomT4 Yeh, I think so, thanks.

**Comment by DomT4** [comment]
Cool. Will do :+1:
