### ISSUE TITLE
patch for low-risk DoS in quassel

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew#37920]
> The following commit fixed a denial of service in quassel:
https://github.com/quassel/quassel/commit/b5e38970ffd55e2dd9f706ce75af9a8d7730b1b8

> It allows a connected client to cause a core crash by sending a CTCP
request which would be too long and multibyte.

> This is mitigated by the fact that it requires an authed user.

http://www.openwall.com/lists/oss-security/2015/03/20/12

**Comment by DomT4** [comment]
#38165

Patch applies cleanly.
