### ISSUE TITLE
python3 has wrong LINKFORSHARED in module sysconfig

### ISSUE THREAD

**Issue by tnilanon** [Homebrew/homebrew#37923]
I have `python3` built by Homebrew with `--with-quicktest`.
When run:
```python
import distutils.sysconfig
distutils.sysconfig.get_config_var('LINKFORSHARED')
```
it returns `'-Wl,-stack_size,1000000  -framework CoreFoundation Python.framework/Versions/3.4/Python'`

I have graph-tool's `configure` script that calls this method. Then it looks for `Python.framework/Versions/3.4/Python` in `/System/Library/Frameworks`. This directory does not exist since it is in `#{HOMEBREW_PREFIX}/Cellar/python3/3.4.3/Frameworks` instead.

Please advise. I think `sysconfig` is not supposed to return these settings.

**Comment by tnilanon** [comment]
Nevermind. Seems to be an outdated method: http://bugs.python.org/issue3588

**Comment by mistydemeo** [comment]
Closing based on the upstream report - thanks!

**Comment by tdsmith** [comment]
We try to fix this in siteconfig; it looks like we're failing, so I'd like to fix it, even if other tools should know better.

**Comment by tdsmith** [comment]
I guess the mechanism changed:
```
>>> _sysconfigdata.build_time_vars["LINKFORSHARED"]
'-u _PyMac_Error /usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/Python'
>>> import distutils.sysconfig
>>> distutils.sysconfig.get_config_var("LINKFORSHARED")
'-Wl,-stack_size,1000000  -framework CoreFoundation Python.framework/Versions/3.5/Python'
```

It looks like we should inreplace /usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/config-3.5m/Makefile instead of doing tricks in siteconfig.

**Comment by tnilanon** [comment]
Thanks for taking care of this
