### ISSUE TITLE
brew install zenity fails because of scrollkeeper

### ISSUE THREAD

**Issue by pkoppstein** [Homebrew/homebrew#37953]
The gist created by "brew gist-logs scrollkeeper" is https://gist.github.com/pkoppstein/d183f1e062bbc13506df

Here is the tail-end of the output produced by "brew install zenity":
```
==> Installing zenity dependency: scrollkeeper
==> Downloading https://downloads.sourceforge.net/project/scrollkeeper/scrollkeeper/0.3.14/scrollkeeper-0.3.14.tar.gz
Already downloaded: /Library/Caches/Homebrew/scrollkeeper-0.3.14.tar.gz
==> ./configure --prefix=/usr/local/Cellar/scrollkeeper/0.3.14 --mandir=/usr/local/Cellar/scrollkeeper/0.3.14/share/man --with-xml-catalog=/usr/local/etc/xml/catalog
==> make
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [scrollkeeper-tree-separate] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by mistydemeo** [comment]
Take a look at your `brew doctor` - it looks like you have a non-homebrew libintl, which is interfering with the build. Try removing that.

**Comment by pkoppstein** [comment]
@mistydemeo - Actually, when I first tried to install zenity, it complained about the ABSENCE of libintl.a, so I reinstated it, and sent the results you see.

Here's what happens with libintl.a removed:
```
make
clang -g -O2 -o .libs/scrollkeeper-tree-separate separate.o  -L../libs/.libs -lscrollkeeper -lxml2 -lxslt /usr/local/lib/libintl.a -liconv -lc
clang: error: no such file or directory: '/usr/local/lib/libintl.a'
make[2]: *** [scrollkeeper-tree-separate] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
``` 

In case you're thinking of asking me to "brew install libintl":

```
$ brew search libintl
Error: No available formula for libintl 
```

Thanks.

**Comment by jacknagel** [comment]
Do the following:

```
rm -f /usr/local/lib/libintl.*
brew reinstall gettext
brew install zenity
```

**Comment by pkoppstein** [comment]
Thanks, @jacknagel -- reinstalling gettext solved the problem -- though I can't help wondering whether doing so hasn't created another one for another day....
