### ISSUE TITLE
scantailor won't import

### ISSUE THREAD

**Issue by AllanKinnaird** [Homebrew/homebrew#37958]
Running brew doctor produces the error message 
Error: Failed to import: scantailor
version '{"0.9.11"=>Formulary::Formulae::Scantailor::Version}' should be a string

brew install scantailor produces the same message, as does brew info scantailor
Note also that this package does not appear on braumeister.org

**Comment by mikemcquaid** [comment]
This issue was moved to Homebrew/homebrew-x11#42
