### ISSUE TITLE
innotop 1.9.1 doesn't support mysql 5.6 (but github checkout does)

### ISSUE THREAD

**Issue by santagada** [Homebrew/homebrew#37952]
the released version of innotop doesn't support mysql >= 5.6 (which is the current version on homebrew). I did a simple patch to get the master archive on github for it which at least does support mysql 5.6. Is this a good contribution or not?

```diff
--- a/Library/Formula/innotop.rb
+++ b/Library/Formula/innotop.rb
@@ -2,8 +2,9 @@ require "formula"

 class Innotop < Formula
   homepage "http://code.google.com/p/innotop/"
-  url "https://innotop.googlecode.com/files/innotop-1.9.1.tar.gz"
-  sha1 "6b0b5f492e7188152727f6c157043be180ba516a"
+  url "https://github.com/innotop/innotop/archive/master.zip"
+  sha1 "d0f924f6a848085ff4d18acae8e034023eafa946"
+  version "1.9.2-alpha"

   depends_on :mysql
```

**Comment by mikemcquaid** [comment]
Sorry, we'll need to wait for a stable release or apply an upstream patch to the innotop formula.

**Comment by santagada** [comment]
They say in the docs that there are no plans for a new release... but I guess it is ok :(

**Comment by jacknagel** [comment]
As another alternative, please feel free to submit a PR that adds a `head` version to innotop.
