### ISSUE TITLE
Set PostgreSQL + MySQL to start as needed

### ISSUE THREAD

**Issue by tejasmanohar** [Homebrew/homebrew#37969]
When I instaled PostgreSQL + MySQL (separately) before, I ran the command provided to start them on login. Since I don't use them that both too often, it's a waste of memory and would rather start each on a command when I need to use it.

How do I change this setting? Also, how can I tell what other software I've installed via brew or in general (not applications, that's in system preferences) begin on login?

**Comment by nickborromeo** [comment]
From what I understand, homebrew is isolated in the /usr/local/Cellar directory, and uses symlinks to the necessary directories for the app to work. 

Also, the Cellar directory is in git so you can go into the mysql or postgres folders and play around with the files there to solve your specific problem. :smile: (and rever if you break things :smile: )

**Comment by tejasmanohar** [comment]
Ah, but are you aware what causes a program to start on login / not. I recall using services before and systemctl before on different linux distros. If I can get some basic help on how to control if one of those softwares (psql or mysql) starts on login, I can do rest myself :smile:

**Comment by MerelyAPseudonym** [comment]
You can tell what other software you've installed via Homebrew that begins on login with the following command:

```shell
ls ~/Library/LaunchAgents/homebrew.mxcl.*.plist
```

The simplest way to stop MySQL and PostgreSQL from starting on login is by removing the related files:

```shell
rm ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
rm ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
```

If you'd like to learn more, you might find http://launchd.info/ to be helpful.

**Comment by tejasmanohar** [comment]
@MerelyAPseudonym Alright. But how can I start the MySQL and PostgreSQL services when I want to?

**Comment by tejasmanohar** [comment]
Nvm

**Comment by DomT4** [comment]
> How do I change this setting?

Presuming I understand you:

```
launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
rm ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
rm ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
```

And then you'd just start them the normal manual way:

```
postgres -D /usr/local/var/postgres
mysql.server start
```

> Also, how can I tell what other software I've installed via brew or in general (not applications, that's in system preferences) begin on login?

If they're non-GUI and handled by ` launchctl ` you can find them with a simple ` launchctl list `, where they'll be displayed with something like ` com.apple.powerchime `.

**Comment by tejasmanohar** [comment]
I got it, yeah

**Comment by tejasmanohar** [comment]
thanks though
