### ISSUE TITLE
Allow to install older versions of phantomjs

### ISSUE THREAD

**Issue by Holek** [Homebrew/homebrew#37989]
Currently PhantomJS formula only allows to install the latest version of the package.

`cucumber-rails` gem depends on 1.8, which is [available in older revisions of Homebrew](https://raw.githubusercontent.com/Homebrew/homebrew/1a69283250d53c01fe018fa816cb523363de192b/Library/Formula/phantomjs.rb).

I've seen it is possible to allow installation of different version of formulas. Can that be done for PhantomJS?

**Comment by DomT4** [comment]
There are various alternative versions of it in [Homebrew/Versions](https://github.com/Homebrew/homebrew-versions). Feel free to open a PR with another there if none of those serve your need.

**Comment by mikemcquaid** [comment]
As @DomT4 said, thanks!
