### ISSUE TITLE
Install dependency with the most build arguments

### ISSUE THREAD

**Issue by Max13** [Homebrew/homebrew#37991]
Hi there!

Sorry for my ambiguous title. I have 3 packages (sample names): `dep.rb`, `exec.rb` and `libfoo.rb`.

```ruby
# dep.rb

option "with-opt1", "Force option 1"
option "with-opt2", "Force option 2"
```

```ruby
# exec.rb

depends_on "dep"
```

```ruby
# libfoo.rb

option "with-opt1", "Force option 1"
option "with-opt2", "Force option 2"

if build.with?("opt1")
  b = "opt1"
elsif build.with?("opt2")
  b = "opt2"
else
  b = "opt1"
end

depends_on "dep" => "with-" + b
```

From here, `exec` needs `dep` to be installed, no matter build option passed. But `libfoo` needs `dep` to be build with either options (not none). What I have observed so far is that installing both at the same time installs `dep` with no options (as specified by `exec`) and reinstalls it with the build options specified in `libfoo`:

    % brew install exec libfoo --with-opt1

What I would expect, is that either the dependencies passed options are merged or a message is raised to warn me that there is a conflict, shouldn't it ?

**Comment by jacknagel** [comment]
Corner cases like this will be addressed in the new dependency implementation (TBA).
