### ISSUE TITLE
brew install doesn't compute dependencies properly

### ISSUE THREAD

**Issue by gpakosz** [Homebrew/homebrew#37993]
I can't install `imagemagick` with `librsvg` without bringing Xquartz to the party.

    ~ brew deps imagemagick --with-librsvg
    atk
    cairo
    fontconfig
    freetype
    gdk-pixbuf
    gettext
    glib
    gobject-introspection
    gtk+
    harfbuzz
    icu4c
    intltool
    jpeg
    libcroco
    libffi
    libpng
    librsvg
    libtiff
    libtool
    pango
    pixman
    pkg-config
    python
    xz

Eventhough I installed `librsvg` up-front with `brew install cairo pango librsvg --without-x11 --without-gtk+`, `brew install imagemagick --with-librsvg` tries to install `gtk+` because it believes it's a dependency of `librsvg` (**which is already installed**):

    ~ brew install cairo pango librsvg --without-x11 --without-gtk+
    Warning: cairo-1.14.2 already installed
    Warning: pango-1.36.8 already installed
    Warning: librsvg-2.36.3_1 already installed

    ~ brew install imagemagick --with-librsvg
    gtk+: XQuartz 2.3.6 is required to install this formula.
    You can install with Homebrew Cask:
      brew install Caskroom/cask/xquartz

    You can download from:
      https://xquartz.macosforge.org
    Error: An unsatisfied requirement failed this build.

**Comment by tdsmith** [comment]
I think the underlying issue is the same as #37900.

**Comment by jacknagel** [comment]
https://github.com/Homebrew/homebrew/issues/31374#issuecomment-51292043 provides a technical explanation. The tl;dr is that this is a known issue that is being worked on.
