### ISSUE TITLE
SSHguard misses common attack patterns on OS X - patch available

### ISSUE THREAD

**Issue by chrisjcameron** [Homebrew/homebrew#38006]
The linked message contains a patch for SSH Guard so it can recognize the "via IP-address" part of the authentication error messages on Mac OS X. Without this patch, SSHGuard misses most attacks targeting my system (2-3 per second). I am not sure if it is appropriate to include the patch in homebrew yet but it is a month old at this point and would make SSHGuard much more useful on Mac OS X systems. 

The message thread explains the patterns missed in detail:
http://sourceforge.net/p/sshguard/mailman/message/33333200/

**Comment by tdsmith** [comment]
Committed here: https://bitbucket.org/sshguard/sshguard/commits/fc01ad308c10ceb4164e23967b4713b9e7e533d7

The new? maintainer promises a release soon: https://sourceforge.net/p/sshguard/mailman/message/33544487/

I would be happy to consider a pull request that either adds this patch or adds a `head` URL pointing to the bitbucket repository.

If you aren't familiar with pull requests this guide can help you get started: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged -- if you have any questions, we'll be happy to help either here or on IRC.

**Comment by jacknagel** [comment]
Looks like this was added to the formula.
