### ISSUE TITLE
updating home-brew breaks py3cairo/circos

### ISSUE THREAD

**Issue by gaming-hacker** [Homebrew/homebrew#38011]
git stash
No local changes to save

ran brew upgrade
the thing is I don't have py3cairo installed

py3cairo: stable 1.10.0
http://cairographics.org/pycairo/
Not installed
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/py3cairo.rb
==> Dependencies
Build: pkg-config ✔
Required: cairo ✔

Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
Warning: Could not create link for homebrew/x11/py3cairo, as it
conflicts with Homebrew/homebrew/py3cairo. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/x11/py3cairo
error: Your local changes to the following files would be overwritten by merge:
	circos.rb
Please, commit your changes or stash them before you can merge.
Aborting
Error: Failed to update tap: homebrew/science
Updated Homebrew from 98818395 to 2ec86641.

is there a way to unroll this version of homebrew?

**Comment by tdsmith** [comment]
You can ignore the py3cairo warning; it won't appear again. To fix your homebrew-science tap, run `cd $(brew --prefix)/Library/Taps/homebrew/homebrew-science && git checkout master circos.rb`.

**Comment by tdsmith** [comment]
Let us know if we can help with anything else.

**Comment by mahshadul** [comment]
```
$ brew update
error: The following untracked working tree files would be overwritten by checkout:
	Library/Formula/py3cairo.rb
Please move or remove them before you can switch branches.
Aborting
could not detach HEAD
Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master
```
I don't have any file like "Library/Formula/py3cairo.rb"

**Comment by RyanSinger** [comment]
I have the same problem.

**Comment by RyanSinger** [comment]
I fixed this by hunting down /usr/local/Library/Formula/py3cairo.rb and deleting it.

**Comment by DomT4** [comment]
` brew tap --repair ` should work - If it doesn't: ` git fetch; git reset --hard origin/master ` will, although that will also remove any local changes you've made to Homebrew's master branch, so be wary of that. Usually isn't a problem for most people though.

**Comment by mahshadul** [comment]
@RyanSinger I don't have this file exist.. so I can't hunt it delete and @DomT4 I did not find any luck to resolve my issue by using your tips. Thanks for your help though.

But I did this and now brew update is working
```
rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
```

**Comment by Vorob-Astronaut** [comment]
@RyanSinger hey. thx, it works!

**Comment by cesards** [comment]
+1 here
```
$ brew update
error: The following untracked working tree files would be overwritten by merge:
	Library/Formula/py3cairo.rb
Please move or remove them before you can merge.
Aborting
Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master
```
Fixed as @RyanSinger says

**Comment by xypaul** [comment]
@RyanSinger thanks worked for me
