### ISSUE TITLE
autoconf should depend on automake

### ISSUE THREAD

**Issue by sparr** [Homebrew/homebrew#38015]
$ autoreconf -i
	-bash: autoreconf: command not found
	$ brew install autoconf
	==> Downloading https://homebrew.bintray.com/bottles/autoconf-2.69.mavericks.bottle.1.tar.gz
	Already downloaded: /Library/Caches/Homebrew/autoconf-2.69.mavericks.bottle.1.tar.gz
	==> Pouring autoconf-2.69.mavericks.bottle.1.tar.gz
	🍺  /usr/local/Cellar/autoconf/2.69: 69 files, 2.0M
	$ autoreconf -i
	Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
	autoreconf: failed to run aclocal: No such file or directory
	$ brew install automake
	==> Downloading https://homebrew.bintray.com/bottles/automake-1.15.mavericks.bottle.tar.gz
	######################################################################## 100.0%
	==> Pouring automake-1.15.mavericks.bottle.tar.gz
	🍺  /usr/local/Cellar/automake/1.15: 130 files, 3.2M
	$ autoreconf -i
	[it works now]

**Comment by jacknagel** [comment]
automake itself depends on autoconf, and we can't introduce a circular dependency.

**Comment by sparr** [comment]
is there an open feature request or issue about implementing circular dependency handling?

**Comment by jacknagel** [comment]
Nope (the dependency code is currently being rewritten, so it wouldn't be considered until after that is done).

How do other package managers handle this? Does installing autoconf install automake as well?

**Comment by sparr** [comment]
in debian/ubuntu, autoconf recommends automake, automake depends on autoconf.

in centos, autoconf does not refer to automake, and I'm not sure how the need for aclocal is rectified there. automake depends on autoconf.

**Comment by petere** [comment]
`autoreconf` only runs `aclocal` if the package you are working on uses aclocal. That package should then build-depend on `automake`.  Or, if you are working on source code, you need to do it yourself.  Similar, if your package uses Libtool, then `autoreconf` will run `libtoolize`.  But that doesn't mean `autoconf` should depend on `libtool`.  The error message you saw is actually valuable: It says, the package you are working on uses Automake, but you don't have it installed.  Autoconf is just the messenger.
