### ISSUE TITLE
Audit --strict conflicting instructions

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew#38018]
` brew audit coq83 --strict `

```ruby
class TransitionalMode < Requirement
  def message; <<-EOS.undent
    camlp5 must be compiled in transitional mode (instead of --strict mode):
      brew install camlp5
    EOS
  end
  def satisfied?
    # If not installed, it will install in the correct mode.
    return true if not which('camlp5')
    # If installed, make sure it is transitional instead of strict.
    `camlp5 -pmode 2>&1`.chomp == 'transitional'
  end
  def fatal?
    true
  end
end
```

Error message 2: ` C: 10:  5: Favor unless over if for negative conditions. `.

Changed in response to:

```ruby
  def satisfied?
    # If not installed, it will install in the correct mode.
    return true unless !which("camlp5")
    # If installed, make sure it is transitional instead of strict.
    `camlp5 -pmode 2>&1`.chomp == "transitional"
  end
```

And now...

Error message: ` C: 10:  5: Favor if over unless for negative conditions. `

:cry: 

Should be easy enough to fix. Just want some idea on what @Homebrew/owners actually prefer given the audit conflict :smile_cat:

**Comment by DomT4** [comment]
Screwed up the formatting in my original post. Blame not having had a cup of :coffee: yet. Fixed now.

**Comment by mikemcquaid** [comment]
In this case you've flipped the logic; what it's saying is rather than `if not` use `unless` and rather than `unless !` use `if`.

**Comment by DomT4** [comment]
Welp. Of course. I really should look at these things again after dosing myself up with tea before I submit issues. Thanks!
