### ISSUE TITLE
ICE does not compile (OMERO dependency)

### ISSUE THREAD

**Issue by apocryphx** [Homebrew/homebrew#38029]
I am trying to install OMERO server on OS X Yosemite 10.10.3 with Xcode 6.2 (6C131e). I execute "brew doctor" and "brew update" before installing. I get no error messages.

Compiling OMERO get the following error message:

==> Installing omero dependency: ice
==> Downloading http://www.zeroc.com/download/Ice/3.5/Ice-3.5.1.tar.gz
######################################################################## 100.0%
==> Patching
patching file cpp/config/Make.rules.Darwin
patching file py/config/Make.rules.Darwin
patching file cpp/src/IceGrid/DescriptorHelper.h
==> Downloading http://download.oracle.com/berkeley-db/db-5.3.28.tar.gz
######################################################################## 100.0%
==> ../dist/configure --disable-debug --prefix=/usr/local/Cellar/ice/3.5.1_1/libexec --mandir=/usr/local/Cellar/ice/
==> make install
==> make prefix=/usr/local/Cellar/ice/3.5.1_1 install_mandir=/usr/local/Cellar/ice/3.5.1_1/share/man/man1 install_sl
==> make install prefix=/usr/local/Cellar/ice/3.5.1_1 install_mandir=/usr/local/Cellar/ice/3.5.1_1/share/man/man1 in
==> make prefix=/usr/local/Cellar/ice/3.5.1_1 install_mandir=/usr/local/Cellar/ice/3.5.1_1/share/man/man1 install_sl
         ^
1 error generated.
make[2]: *** [Communicator.o] Error 1
make[1]: *** [all] Error 1
make: *** [all] Error 1

READ THIS: https://git.io/brew-troubleshooting

Any suggestions?

Best,
Kolja

**Comment by mistydemeo** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please read this link and post all of the requested diagnostics, thanks!

**Comment by apocryphx** [comment]
I tried "brew gist-logs omero" but only get "Error: No logs." I did "brew gist-logs ice" and got "https://gist.github.com/62548c483c16465acb25" as output. Not sure how to proceed ....

**Comment by apocryphx** [comment]
I forgot to install the Xcode command line tools. Sorry for the bug report.

Thanks for your help.

Best,
Kolja
