### ISSUE TITLE
fossil source download broken

### ISSUE THREAD

**Issue by axtens** [Homebrew/homebrew#38046]
==> Upgrading fossil
==> Downloading https://www.fossil-scm.org/download/fossil-src-20150223162734.ta

curl: (22) The requested URL returned error: 404
Error: Failed to download resource "fossil"
Download failed: https://www.fossil-scm.org/download/fossil-src-20150223162734.tar.gz

gist: https://gist.github.com/axtens/e49c260bc97b6b4bb2a2

**Comment by jacknagel** [comment]
Pending #38073

**Comment by tdsmith** [comment]
Fixed in c64d6cc6f6c99096fc370f26e8a6a51780e19ed3.
