### ISSUE TITLE
Warning: Xcode is installed to a directory with a space in the name. This will cause some formulae to fail to build.

### ISSUE THREAD

**Issue by liuxiangyu-kx** [Homebrew/homebrew#38049]
I have xcode5.1.1,xcode6.1.1,xcode6.2,when i "brew doctor",show warning like this:
"Warning: Xcode is installed to a directory with a space in the name.
This will cause some formulae to fail to build."
How do I solve the problem？

**Comment by mikemcquaid** [comment]
Move Xcode to a directory without a space in the name.

**Comment by liuxiangyu-kx** [comment]
Thanks! I will try it !

**Comment by troyleak** [comment]
What worked for me was:

$ sudo xcode-select --switch /Applications/Xcode.app

I had pointed it to "/Volume/Macintosh\ HD/Applications/Xcode.app" during the setup process

**Comment by mikemcquaid** [comment]
Assuming @troyleak's approach fixes it.
