### ISSUE TITLE
Error with brew update

### ISSUE THREAD

**Issue by neuwirthe** [Homebrew/homebrew#38051]
Moritz:~ neuwirth$ brew update
Error: undefined method `close!' for nil:NilClass
Please report this bug:
    https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/usr/local/Library/Homebrew/extend/pathname.rb:129:in `ensure in atomic_write'
/usr/local/Library/Homebrew/extend/pathname.rb:129:in `atomic_write'
/usr/local/Library/Homebrew/cmd/untap.rb:42:in `unlink_tap_formula'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:136:in `<main>'

**Comment by mikemcquaid** [comment]
It's OK to ignore this; it will not happen again.
