### ISSUE TITLE
sendEmail password in plaintext

### ISSUE THREAD

**Issue by xelio91** [Homebrew/homebrew#38064]
I would like to report a security problem in this repo, when I send an email (following the example in FAQ here: http://caspian.dotconf.net/menu/Software/SendEmail/#faq ) I must use the parameter -xp typing DIRECLTY and in plaintext my password.

sendEmail -o tls=yes -f YourEmail@gmail.com -t SomeoneYoureEmailing@domain.com -s smtp.gmail.com:587 -xu YourEmail@gmail.com -xp YOURPASSWORD -u "Hello from sendEmail" -m "How are you? I'm testing sendEmail from the command line." 

I can type this without -xp, but I must put it (obviously) after I send [ENTER]. So I ask if is possible to hide the password in the next step?

**Comment by mikemcquaid** [comment]
Sorry, is this a package you've installed from Homebrew?

**Comment by xelio91** [comment]
Yes ofc, I did brew install sendemail
Clearly I'm on Mac OS

**Comment by DomT4** [comment]
Probably needs kicking upstream, given the plaintext password entry is actually recommended by them. As a workaround, you could do something like this:

```
echo "mypassword" >> ~/.sendemail.key

sendEmail -o tls=yes -f YourEmail@gmail.com -t SomeoneYoureEmailing@domain.com -s smtp.gmail.com:587 -xu YourEmail@gmail.com -xp `cat ~/.sendemail.key` -u "Hello from sendEmail" -m "How are you? I'm testing sendEmail from the command line."
```

Should work.

**Comment by mistydemeo** [comment]
We don't provide technical support for software installed with Homebrew - if you need support for sendEmail, please check [its website](http://caspian.dotconf.net/menu/Software/SendEmail/) for information about support. Thanks!

**Comment by xelio91** [comment]
che zoccola che sei

**Comment by xelio91** [comment]
I wrote there, i hope someone will answer me...Btw @DomT4 it doesn't work

**Comment by mistydemeo** [comment]
Please refer to our [code of conduct](https://github.com/Homebrew/homebrew/blob/master/CODEOFCONDUCT.md). The comment you left (and deleted) earlier is not acceptable.
