### ISSUE TITLE
gnuplot 750GB log file

### ISSUE THREAD

**Issue by walkloud** [Homebrew/homebrew#38071]
Hi All,

I have Mavericks (10.9.5) and have been using home-brew happily for a while.
I have two issues now, maybe related.  The first, reported with no details at the moment, is that I installed SWIG, but when compiling some C-code, then trying to import, I got a conflicting python dylib problem (Fatal Error no thread type abort).

I also installed gnu plot via home-brew cause of the software I was using.  This resulted in a 750GB log file - yes that is correct, 750GB.  This is one of 3 .make files - I deleted it.  I am willing to try and get helpful info, but this clogged my startup disk with error messages about serious problems with my computer, so I could only delete the log file.  I have all the others.

Thanks,

Andre

**Comment by walkloud** [comment]
an update: I just noticed gnuplot was running nonstop since yesterday - which might be what was creating the log file

**Comment by walkloud** [comment]
correction - the log file was definitely coming from my attempted installation.  When I brewed gnuplot, I used the option --with-tests, and it was the make check portion that was creating this 750GB log file.  When I deleted it, the following message popped up

tail: /Users/walkloud/Library/Logs/Homebrew/gnuplot/03.make: No such file or directory

andre

**Comment by jacknagel** [comment]
Can you reproduce this?

That is, if you try and install gnuplot again, does it hang and continue writing to that log file?

If not, I'm not sure there's anything we can do.
