### ISSUE TITLE
svn version inconsistency

### ISSUE THREAD

**Issue by twh** [Homebrew/homebrew#38082]
On a vanilla homebrew install on a new Yosemite host, svn is showing some strange version information:
[21:53:49 twh@x.local:~]$ brew upgrade svn
Error: subversion 1.8.11 already installed
[21:53:55 twh@x.local:~]$ svn --version
svn, version 1.7.19 (r1643991)
[21:54:03 twh@x.local:~]$ which svn
/usr/local/bin/svn
[21:55:03 twh@x.local:~]$ svn update
svn: E155021: This client is too old to work with the working copy at
'/Users/twh' (format 31).
You need to get a newer Subversion client. For more details, see
  http://subversion.apache.org/faq.html#working-copy-format-change
I've run brew doctor etc but everything appears to be fine.

**Comment by mistydemeo** [comment]
Can you try opening a new shell and see if this persists?

**Comment by twh** [comment]
Ywp, now it all matches up.
