### ISSUE TITLE
PyPy 2.5.1 has been released

### ISSUE THREAD

**Issue by cclauss** [Homebrew/homebrew#38088]
http://morepypy.blogspot.ch/2015/03/pypy-251-released.html  Now 6.98 times faster than CPython.

The [current PyPy formula](https://github.com/Homebrew/homebrew/blob/c8f53d4720a918b27d14388a3483905fdbb3ecc6/Library/Formula/pypy.rb) installs v2.5.0.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by tdsmith** [comment]
Closing in favor of Alex's PR.
