### ISSUE TITLE
Ran brew doctor. Got this error.

### ISSUE THREAD

**Issue by alexbuzzbee** [Homebrew/homebrew#38108]
Error: undefined method \`homebrew_site_packages' for Language::Python:Module
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/cmd/doctor.rb:439:in \`check_access_site_packages'
/usr/local/Library/Homebrew/cmd/doctor.rb:1210:in \`block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1209:in \`each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1209:in \`doctor'
/usr/local/Library/brew.rb:136:in `<main>'

**Comment by jacknagel** [comment]
```
cd $(brew --repository)
git fetch origin master
git reset --hard origin/master
brew update
```
