### ISSUE TITLE
installing gcc does not create symlinks that are called "gcc", "g++", etc...

### ISSUE THREAD

**Issue by pcantalupo** [Homebrew/homebrew#38106]
Hello,

After installing gcc with `brew install gcc`, it created a bunch of symlinks in /usr/local/homebrew/bin such as  `gcc-4.9@ -> ../Cellar/gcc/4.9.2_1/bin/gcc-4.9`. Since `gcc-4.9` or `g++-4.9` is never found in Makefiles, I had to manually create these symlinks in /usr/local/homebrew/bin. Why doesn't homebrew do this automatically or am I missing something?

Thank you,

Paul

**Comment by DomT4** [comment]
It can't create a symlink to ` gcc `, because there's already a `gcc` in the `$PATH` (Which is actually Clang these days on modern OS X versions). That's the reasoning, I believe.

**Comment by mistydemeo** [comment]
Buildsystems generally provide options to override the default compiler. You can ensure this GCC is picked up by setting the `CC` and `CXX` environment variables to `gcc-4.9` and `g++-4.9`, or by checking what options your Makefiles provide.

**Comment by pcantalupo** [comment]
@DomT4 it should not matter that there is a `gcc` in the path already. I was hoping that Homebrew would install a `gcc` in its `bin` directory and then all I would have to do is add that directory to my $PATH before any of the system directories that may contain `gcc`.

**Comment by pcantalupo** [comment]
@mistydemeo Seems a bit clunky to me to have to set env vars. Can Homebrew be set up to create these symlinks automatically in `/usr/local/homebrew/bin`?

**Comment by mikemcquaid** [comment]
> @mistydemeo Seems a bit clunky to me to have to set env vars. Can Homebrew be set up to create these symlinks automatically in /usr/local/homebrew/bin?

It cannot, sorry, no.
