### ISSUE TITLE
Unsupported special dependency :libusb

### ISSUE THREAD

**Issue by DragonFired** [Homebrew/homebrew#38128]
This is the result of running 'brew doctor' which "asks" me to report this... No gist logs were created, since I don't have a formula to create them for. 

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libdvdcss.2.1.0.dylib
Error: Unsupported special dependency :libusb
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/dependency_collector.rb:136:in `parse_symbol_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:81:in `parse_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:65:in `build'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `block in fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:38:in `add'
/usr/local/Library/Homebrew/software_spec.rb:129:in `depends_on'
/usr/local/Library/Homebrew/formula.rb:921:in `block in depends_on'
/usr/local/Library/Homebrew/formula.rb:921:in `each'
/usr/local/Library/Homebrew/formula.rb:921:in `depends_on'
/usr/local/Library/Formula/pyusb.rb:12:in `<class:Pyusb>'
/usr/local/Library/Formula/pyusb.rb:6:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/formula.rb:519:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:517:in `map'
/usr/local/Library/Homebrew/formula.rb:517:in `installed'
/usr/local/Library/Homebrew/cmd/doctor.rb:977:in `check_missing_deps'
/usr/local/Library/Homebrew/cmd/doctor.rb:1256:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1254:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1254:in `doctor'
/usr/local/Library/brew.rb:135:in `<main>'

**Comment by DomT4** [comment]
Try ` brew readall `. Does that cough out anything?

**Comment by DragonFired** [comment]
It surely does!

arana$ brew readall
Error: problem in /usr/local/Library/Formula/pyusb.rb
Unsupported special dependency :libusb
Tranquility:arana arana$

**Comment by DomT4** [comment]
What does ` brew info pyusb ` cough out?

**Comment by DragonFired** [comment]
arana$ brew info pyusb
Error: Unsupported special dependency :libusb
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/dependency_collector.rb:136:in `parse_symbol_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:81:in `parse_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:65:in `build'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `block in fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:38:in `add'
/usr/local/Library/Homebrew/software_spec.rb:129:in `depends_on'
/usr/local/Library/Homebrew/formula.rb:921:in `block in depends_on'
/usr/local/Library/Homebrew/formula.rb:921:in `each'
/usr/local/Library/Homebrew/formula.rb:921:in `depends_on'
/usr/local/Library/Formula/pyusb.rb:12:in `<class:Pyusb>'
/usr/local/Library/Formula/pyusb.rb:6:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/cmd/info.rb:31:in `block in print_info'
/usr/local/Library/Homebrew/cmd/info.rb:28:in `each'
/usr/local/Library/Homebrew/cmd/info.rb:28:in `each_with_index'
/usr/local/Library/Homebrew/cmd/info.rb:28:in `print_info'
/usr/local/Library/Homebrew/cmd/info.rb:18:in `info'
/usr/local/Library/brew.rb:135:in `<main>'

**Comment by DomT4** [comment]
Heh, okay. Try ` ls -l /usr/local/Library/Formula/pyusb.rb `.

**Comment by DragonFired** [comment]
arana$ ls -l /usr/local/Library/Formula/pyusb.rb
-rw-r--r--@ 1 arana  503  928 Aug 17  2012 /usr/local/Library/Formula/pyusb.rb

**Comment by DomT4** [comment]
Welp. Was hoping that would point to a tap or something. Alright. Try ` brew tap --repair `. If ` brew info pyusb ` is still broken after that, just do ` rm /usr/local/Library/Formula/pyusb.rb `. I can't find any reference to the formula in Homebrew's history, so I'm presuming it came from a tap at some point and got stuck there, somehow.

**Comment by DragonFired** [comment]
Great! Thanks. If you have no record of it, then there is nothing to be concerned about. :-) I can now happily ignore the error message or delete it if I find out that I am not using it anywhere…

**Comment by jacknagel** [comment]
Either remove the file, or edit it and change `:libusb` to `"libusb"` if it's something you need.

**Comment by DragonFired** [comment]
Thanks Jack!
