### ISSUE TITLE
python3 and pkg-config

### ISSUE THREAD

**Issue by zenzike** [Homebrew/homebrew#38121]
I've installed python3using brew, but it seems that `pkg-config` isn't picking up the .pc files that are placed in `/Library/Frameworks/Python.framework/Versions/3.4/lib/pkgconfig`.

I'm not a brew master, nor do I know about the details of python, but I would have imagined that something like the following line (from https://github.com/Homebrew/homebrew-x11/blob/master/hexchat.rb) should be present in the brew file:

    ENV.append_path "PKG_CONFIG_PATH", "#{HOMEBREW_PREFIX}/Frameworks/Python.framework/Versions/#{py_ver}/lib/pkgconfig/

I can't tell if that's me suggesting something wrong, or if it's just missing from https://github.com/Homebrew/homebrew/blob/master/Library/Formula/python3.rb

Does anybody know?

**Comment by DomT4** [comment]
One for you @tdsmith :heart:.

> following line (from https://github.com/Homebrew/homebrew-x11/blob/master/hexchat.rb) should be present in the brew file:

This only applies for the formula at compile time - i.e. We tell Hexchat where to find Python3's pkg-config file. Inserting it into the Python3 formula wouldn't resolve the issue you're discussing here.

**Comment by tdsmith** [comment]
Hmm, we don't install pkg-config files for either python or python3 into a useful prefix. I guess we may as well. FWIW, using `python-config` and `python3-config` is probably more common.

**Comment by zenzike** [comment]
Ah I see. I happen to be working with some other tool that's interfacing with python, and is using pkg-config as well as requiring Python.h: incidentally, I couldn't find where Python.h was placed by brew (though it is present when installed with brew cask).

**Comment by tdsmith** [comment]
That's fair; they ought to be available. Thanks for raising the issue.

`python3-config --includes` should tell you where Python.h is.

**Comment by DomT4** [comment]
Symlinking them into ` lib/pkgconfig ` would work, I presume? That's not too painful a fix if it works.
