### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by neno76** [Homebrew/homebrew#38129]
Hi,
today i had some issues with the update... i remove brew and reinstall,but i have the same issue just after a new fresh install ( without other package )

nenobook:~ moreno$ brew update
error: Your local changes to the following files would be overwritten by merge:
	Abstract/abstract-php-version.rb
	Formula/php53-blitz.rb
	Formula/php53-imagick.rb
	Formula/php54-blitz.rb
	Formula/php54-imagick.rb
	Formula/php54-xdebug.rb
	Formula/php54.rb
	Formula/php55-blitz.rb
	Formula/php55-imagick.rb
	Formula/php55-opcache.rb
	Formula/php55-xdebug.rb
	Formula/php55.rb
	Formula/php56-blitz.rb
	Formula/php56-imagick.rb
	Formula/php56-opcache.rb
	Formula/php56-xdebug.rb
	Formula/php56.rb
	README.md
Please, commit your changes or stash them before you can merge.
Aborting
Error: Failed to update tap: homebrew/php
error: Your local changes to the following files would be overwritten by merge:
	coq83.rb
	erlang-r15.rb
	gawk3.rb
	giflib5.rb
	git-tf-2.0.2.rb
	glfw2.rb
	gsl114.rb
	gst-ffmpeg010.rb
	gst-plugins-bad010.rb
	gst-plugins-base010.rb
	gst-plugins-good010.rb
	gst-plugins-ugly010.rb
	gst-python010.rb
	gst-rtsp010.rb
	gstreamer010.rb
	node010.rb
Please, commit your changes or stash them before you can merge.
Aborting
Error: Failed to update tap: homebrew/versions
error: Your local changes to the following files would be overwritten by merge:
	py3cairo.rb
Please, commit your changes or stash them before you can merge.
Aborting
Error: Failed to update tap: homebrew/x11
Already up-to-date.

Some suggestions ?

**Comment by DomT4** [comment]
``` cd `brew --prefix` && git fetch; git reset --hard origin/master ```. Try that.

**Comment by DomT4** [comment]
Try it inside the individual tap directories as well if you need to. They have their own git links.

A succession of ` brew untap TAPNAME && brew tap TAPNAME && brew tap --repair ` should iron out a decent chunk of stuff as well.

**Comment by neno76** [comment]
thanks working !
nenobook:~ moreno$ brew tap homebrew/versions
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-versions'...
remote: Counting objects: 3459, done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 3459 (delta 18), reused 0 (delta 0), pack-reused 3413
Receiving objects: 100% (3459/3459), 1.13 MiB | 317.00 KiB/s, done.
Resolving deltas: 100% (2005/2005), done.
Checking connectivity... done.
Tapped 208 formulae
nenobook:~ moreno$ brew update
Already up-to-date.
nenobook:~ moreno$ brew tap homebrew/x11
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-x11'...
remote: Counting objects: 152, done.
remote: Total 152 (delta 0), reused 0 (delta 0), pack-reused 152
Receiving objects: 100% (152/152), 58.84 KiB | 0 bytes/s, done.
Resolving deltas: 100% (34/34), done.
Checking connectivity... done.
Tapped 89 formulae
nenobook:~ moreno$ brew update
Already up-to-date.
nenobook:~ moreno$ brew tap homebrew/php
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-php'...
remote: Counting objects: 8380, done.
remote: Total 8380 (delta 0), reused 0 (delta 0), pack-reused 8380
Receiving objects: 100% (8380/8380), 1.72 MiB | 668.00 KiB/s, done.
Resolving deltas: 100% (5598/5598), done.
Checking connectivity... done.
Tapped 446 formulae
nenobook:~ moreno$ brew update
Already up-to-date.

now i try install php :)

**Comment by DomT4** [comment]
Cool! Shout if you hit any further issues :).
