### ISSUE TITLE
libuv builds but does not pass all tests

### ISSUE THREAD

**Issue by vielmetti** [Homebrew/homebrew#38138]
libuv has a `make check` set of tests when you build it from http://github.com/libuv/libuv . I built and tested libuv on OS X Mavericks (10.9.5) and ran into this test error: https://github.com/libuv/libuv/issues/30 where `fs_event_watch_dir` fails.

There is a 'test' target in the homebrew system, but it doesn't do the exhaustive set of tests, so the homebrew test for libuv passes.

**Comment by xu-cheng** [comment]
We can add `make check` during the build. But let's wait this issue get solved by upstream first.

After it's solved. Could you try and open a pull request? This [document](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help. Thanks!
