### ISSUE TITLE
Install subversion --with-java failing

### ISSUE THREAD

**Issue by smrobinson** [Homebrew/homebrew#38133]
Trying "brew install subversion --universal --with-java" but it silently fails.

I have found several similar issues from Dec/Jan/Feb but all seem to have been resolved by installing universal binaries of apr/apr-util. I have already done that, yet installing subversion --with-java silently fails. I've dutifully run 'update' and 'doctor' as you can see in the log.

Log: https://gist.github.com/298c036afb39b306a059

apr/apr-util info: https://gist.github.com/smrobinson/ec42dd152e80ac7b7b42

I can install subversion without specifying --with-java (and without --universal) but I want the JavaHL extensions.

**Comment by bfontaine** [comment]
Is it still an issue?

**Comment by smrobinson** [comment]
No. I ran the installation again today --with-java and it built 1.8.13 fine. Thanks.
