### ISSUE TITLE
Can't update Git, outdated XQuartz, Python installed to /Library

### ISSUE THREAD

**Issue by cat-j** [Homebrew/homebrew#38137]
I'm just getting started with web development, I'm trying to get my environment up and running and I'm scared to mess anything up. The Git issue is pretty straightforward – I can't download the .gz – but the others are more of a 'what would be the safest course of action' thing.

**Comment by cat-j** [comment]
...I also can't find an option to just have plain text instead of this already formatted thing despite looking over and over, so I'll link to the gists instead:
https://gist.github.com/cat-j/a582f5b61509fe85c4e1 <- this is just brew doctor right after I open Terminal
https://gist.github.com/cat-j/403430cc742da1aa8a1f <- brew upgrade git failed
https://gist.github.com/cat-j/9801218418edf367d31f <- upgrade git successful, I guess my internet must have gone down for a nanosecond when I first tried to install it

I actually solved the Git issue by myself as I tried to document my troubles but I still don't know what to do about XQuartz and Python (I'd like to have both 2.x and 3.x installed and I need guidance with how to handle both versions). Here's my brew configuration: https://gist.github.com/cat-j/3e1a0bcc65671637927a

**Comment by chdiza** [comment]
XQuartz is not part of Homebrew.  If it's out of date, you can go [here](http://xquartz.macosforge.org/landing/) and get a newer version like 2.7.7.

Also, be aware that Homebrew no longer officially supports Snow Leopard.  (That said, most stuff should still work).

**Comment by cat-j** [comment]
I updated XQuartz, it was as simple as downloading a .dmg and installing a package and it caused no other issues. I still need help with Python (and with saving up for a computer with a 64 bit processor that can run an OS newer than Snow Leopard but I don't think Github would be of use in that).

**Comment by chdiza** [comment]
Does `brew install python python3` not work?

**Comment by cat-j** [comment]
I haven't tried it. My problem isn't that the commands don't work, it's that I don't know if it's safe to delete a bunch of Python frameworks that I already have installed.

**Comment by chdiza** [comment]
> I don't know if it's safe to delete a bunch of Python frameworks that I already have installed.

OK.  The Homebrew issues page is probably not the place to ask this.  Homebrew is just about getting these things installed.  This sounds like a question for a python mailing list or stackoverflow or something like that.

Possibly someone here will in fact offer you some advice anyway, because this is a friendly community.  I can't offer you such advice since I'm not a Python expert :)

**Comment by cat-j** [comment]
Thanks for pointing that out! I'll go to more Python-focused communities for those kinds of issues from now on.

**Comment by DomT4** [comment]
I thought the ` /Library/Frameworks/Python.framework ` path was created from the binary Python installation, i.e. by user, so it should be safe to remove and replace with Homebrew's. I'm not the Python genius around here though :smile_cat:.

**Comment by cat-j** [comment]
Yeah, if I remember correctly it was actually made a couple of years ago when I first installed Python. I'm having some trouble after removing it but I'm pretty sure it won't be hard to fix.
