### ISSUE TITLE
mitmproxy won't build because libpng 1.6.13 has moved

### ISSUE THREAD

**Issue by danielcompton** [Homebrew/homebrew#38134]
```
$brew install mitmproxy
==> Installing dependencies for mitmproxy: libpng, freetype
==> Installing mitmproxy dependency: libpng
==> Downloading https://downloads.sf.net/project/libpng/libpng16/1.6.13/libpng-1

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "libpng"
Download failed: https://downloads.sf.net/project/libpng/libpng16/1.6.13/libpng-1.6.13.tar.xz
~
$
```

It looks like libpng have moved 1.6.13 so it's no longer available from the previous route. We either need to update to a new version of libpng, or update the path to http://sourceforge.net/projects/libpng/files/libpng16/older-releases/

**Comment by DomT4** [comment]
Your Homebrew is out of date. Homebrew's installation of ` libpng ` is currently on version ` 1.6.16 `. Do a ` brew update && brew upgrade ` and try again.

**Comment by danielcompton** [comment]
Sorry, I assumed that mitmproxy specified the libpng version it needed.
