### ISSUE TITLE
fontforge formula misses dependency on python

### ISSUE THREAD

**Issue by lemzwerg** [Homebrew/homebrew#38144]
[OS X 10.7.5]

If you just say

    brew install fontforge

you get a failure if `python` wasn't installed before.  Maybe the system's python is good enough, but the formula seems not to set up the proper environment variables.

**Comment by DomT4** [comment]
Can you give me a full ` brew gist-logs fontforge ` please? The error is indeed an error, but a full readout will help narrow down the best fix.

**Comment by lemzwerg** [comment]
Will do as soon as I'm sitting again in front of the Mac, which will take a few days.

**Comment by DomT4** [comment]
99% sure this problem was fixed by https://github.com/Homebrew/homebrew/commit/8c5b41ba07b79727add548be0c3d45e075c7ddf4. Feel free to poke me if it wasn't.

**Comment by lemzwerg** [comment]
It was fixed, thanks!  Uninstalling python and upgrading to latest fontforge version brewed just fine.
