### ISSUE TITLE
Elasticsearch download url

### ISSUE THREAD

**Issue by meeas** [Homebrew/homebrew#38142]
Elasicsearch has changed their official name to Elastic and their domain to elasic.co instead of elasticsearch.org.  While installing today, it tool 3-4 attempts to get the file after getting a bad url error.  Apparently elasticsearch.com still works but it wasn't consistent for me, perhaps because of their redirect.  The resource path is the same, just the domainname changed.

**Comment by xu-cheng** [comment]
Could you try and open a pull request? This [document](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should be helpful. Thanks!
