### ISSUE TITLE
unable to remove old kegs via 'brew cleanup' & 'brew cleanup --force'

### ISSUE THREAD

**Issue by shaunstanislaus** [Homebrew/homebrew#38143]
shaunstanislaus@Master ~/workspace/webapp_rails (featurefoodmenu) $ brew cleanup
Warning: Skipping (old) /Users/shaunstanislaus/homebrew/Cellar/git-extras/2.0.0 due to it being linked
Removing: /Users/shaunstanislaus/Library/Logs/Homebrew/wget...

**Comment by chdiza** [comment]
What about `brew unlink git-extras` followed by `brew cleanup`?

**Comment by shaunstanislaus** [comment]
Hi Chdiza, it worked, thanks!

**Comment by DomT4** [comment]
I think ` --force ` as in ` brew cleanup --force ` may work as well.
