### ISSUE TITLE
Can't update Python 3.x with brew install python

### ISSUE THREAD

**Issue by cat-j** [Homebrew/homebrew#38155]
I ran `brew install python python3` and I had no issues updating Python 2.6.1 to 2.7.9, but the same can't be said for Python 3. This is what I got:

```==> Downloading https://www.python.org/ftp/python/3.4.3/Python-3.4.3.tar.xz```
```Already downloaded: /Library/Caches/Homebrew/python3-3.4.3.tar.xz```
```==> ./configure --prefix=/usr/local/Cellar/python3/3.4.3 --enable-ipv6 --dataroo```
```checking for gcc... gcc-4.2```
```checking whether the C compiler works... no```
```configure: error: in `/private/tmp/python320150328-84149-kxwm4s/Python-3.4.3':```
```configure: error: C compiler cannot create executables```
```See `config.log' for more details```

https://gist.github.com/cat-j/2046934cec79de147eaa <- this is config.log (warning, HUGE. I'd look through it myself to save you lot the trouble but I'm new to Homebrew so I don't even know where to start).

**Comment by DomT4** [comment]
` brew doctor ` and ` brew config ` may be helpful to the maintainers as well.

**Comment by cat-j** [comment]
`brew doctor` doesn't see anything wrong.

`$ brew config`
`Mac-2:bin mac$ brew --config`
`HOMEBREW_VERSION: 0.9.5`
`ORIGIN: https://github.com/Homebrew/homebrew.git`
`HEAD: 7c5d4969818ac40bcd9df80fa2de63ba217b61d1`
`Last commit: 4 hours ago`
`HOMEBREW_PREFIX: /usr/local`
`HOMEBREW_CELLAR: /usr/local/Cellar`
`CPU: dual-core 64-bit core2`
`OS X: 10.6.8-i386`
`Xcode: 4.2`
`CLT: N/A`
`GCC-4.2: build 5666`
`LLVM-GCC: build 2336`
`Clang: 3.0 build 211`
`X11: 2.7.7 => /opt/X11`
`System Ruby: 1.8.7-p249`
`Perl: /usr/bin/perl`
`Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7`
`Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby`
`Java: 1.6.0_65`

**Comment by mistydemeo** [comment]
Could you provide the output of `brew gist-logs python3`, please? The config.log doesn't have the error in it.

**Comment by cat-j** [comment]
https://gist.github.com/anonymous/ede787bcaf71c9d4146b <- Here's the output.

**Comment by mistydemeo** [comment]
The error:

```
configure:3957: checking whether the C compiler works
configure:3979: gcc-4.2 -I/usr/local/include -I/usr/local/opt/sqlite/include -L/usr/local/lib -L/usr/local/opt/sqlite/lib conftest.c >&5
i686-apple-darwin10-gcc-4.2.1: error trying to exec 'cc1': execvp: No such file or directory 
```

**Comment by cat-j** [comment]
Thanks for finding that! Is there any way to fix it that doesn't involve installing Python 3 in `/Library/Frameworks/Python.framework`? Sorry if this is a really dumb beginner question.

**Comment by jacknagel** [comment]
I don't know what to suggest besides reinstalling Xcode and the CLT.

**Comment by jacknagel** [comment]
Noting that support for Xcode 4.2 is spotty, due to its short lifespan. You may have more luck with 3.2.6.

**Comment by cat-j** [comment]
Jack, you can probably close this issue as well since I have recently updated to 10.7 and will probably try to install everything I need when I have the time, which I'm guessing won't be that difficult since compatibility is usually better with Lion. Thanks for the help though.
