### ISSUE TITLE
brew warning caused by greenlet

### ISSUE THREAD

**Issue by edonyM** [Homebrew/homebrew#38152]
I installed greenlet on my Mac with `pip install greenlet`. But when I use `brew doctor` to check my home-brew , it comes with warning.
```py
Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/python2.7/greenlet/greenlet.h
    /usr/local/include/python3.4m/greenlet/greenlet.h
```
My OS is OSX10.10.2. Is there any way to fix it?

**Comment by tdsmith** [comment]
These are not errors and you do not need to fix them. brew doctor prints these messages because they can be helpful if you encounter build problems and ask us to help you resolve them. Please let us know if we can help with anything else!

**Comment by jcrben** [comment]
This was reported to python-greenlet at https://github.com/python-greenlet/greenlet/issues/75 - it is installed by pip and necessary.

Allowing these types of message to be expected and build up even though they triggers the user to do some research doesn't seem sustainable. As I continue using homebrew along with other tools, I could end up with dozens of these types of messages.

I suppose there's two ways to avoid it: (1) stop using homebrew and look at something like Nix more seriously or (2) change the homebrew install location from /usr/local altho that is unfortunately not well-documented.

**Comment by tdsmith** [comment]
Please take the message printed at the top of the `brew doctor` output to heart. :)

> Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

This is discussed ad nauseum elsewhere on the tracker; stray headers can and do cause build problems and these messages are genuinely useful for debugging.
