### ISSUE TITLE
Ruby and cURL commands not found

### ISSUE THREAD

**Issue by ASBaumgarten** [Homebrew/homebrew#38170]
While trying to reinstall Homebrew, I have encountered and error where the default install script will not work. The system gives me a response saying it can't find Ruby or cURL in its list of commands. Please help or advise.
![screen shot 2015-03-29 at 2 12 16 am](https://cloud.githubusercontent.com/assets/7777147/6884305/485ee53a-d5b9-11e4-9870-68991ad9eb55.png)

**Comment by mikemcquaid** [comment]
Are you on OS X? Please show the output of running `echo $PATH`

**Comment by ASBaumgarten** [comment]
![screen shot 2015-03-29 at 9 32 15 am](https://cloud.githubusercontent.com/assets/7777147/6885621/97bef74a-d5f6-11e4-8010-9c3b4f43e878.png)

**Comment by chdiza** [comment]
Your $PATH is corrupt.  It's supposed to be `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`.

**Comment by jacknagel** [comment]
Yes, you'll need to adjust your PATH (this is done in your shell configuration files).

**Comment by HamzaS** [comment]
Im having the same problem, how do I change the PATH with iTerm? Cannot seem to find it.
