### ISSUE TITLE
error in OS X 10.10.2 with brew install --HEAD --use-gcc netpbm

### ISSUE THREAD

**Issue by AstroFenster** [Homebrew/homebrew#38178]
https://gist.github.com/f2df787c9ef0b1c3f85a

Getting 2 erros in first step building Astrometry.net with home-brew in
http://astrometry.net/doc/build.html#build 
after brew update and brew doctor.

Regards
Michael

**Comment by tdsmith** [comment]
Those instructions look old and you're probably encountering an upstream error; please try just `brew install netpbm` without any other options and see if you run into trouble with the rest.

**Comment by AstroFenster** [comment]
Thank You,
no problem with installing netpbm now.
Next steps later.

Regards
Michael

**Comment by AstroFenster** [comment]
Next step installing astrometry.net  from http://astrometry.net/doc/build.html#build need:
pip install pyfits &   pip install numpy
->OK with warnings: Installing collected packages: numpy, pyfits
->Successfully installed numpy-1.9.2 pyfits-3.3

Next step
->brew install astrometry.net
got warnings and problems with links to fits copy and cfitsio
------------snipp------------------------------
https://gist.github.com/3c323539eb659720804b

The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/fitscopy
Target /usr/local/bin/fitscopy
is a symlink belonging to cfitsio. You can unlink it:

  brew unlink cfitsio
  brew link --overwrite astrometry.net

-> I did the first command and got:
Unlinking /usr/local/Cellar/cfitsio/3.370... 24 symlinks removed
->and after it the second:
->brew link --overwrite  astrometry.net
-> with the message:
Linking /usr/local/Cellar/astrometry.net/0.44... 221 symlinks created

-> Now brew doctor respond:
You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:

    cfitsio

-> is this the beginning of an endless loop ?

Regards
Michael
