### ISSUE TITLE
Maven formula overrides JAVA_HOME

### ISSUE THREAD

**Issue by samskivert** [Homebrew/homebrew#38202]
The recommended way to run Maven using a different version of Java is to set the `JAVA_HOME` environment variable and then run Maven. But the Maven formula installs an `mvn` script which overwrites `JAVA_HOME` with the default Java installation per the OS, which breaks this process:

```
% cat /usr/local/bin/mvn
#!/bin/bash
JAVA_HOME="${JAVA_HOME:-$(/usr/libexec/java_home)}" exec "/usr/local/Cellar/maven/3.3.1/libexec/bin/mvn" "$@"
```

It would be preferable to either:

a) Don't do this at all. Put Maven's bin/mvn into /usr/local/Cellar/maven/3.3.1/bin/mvn and link to that from /usr/local/bin. I don't know what the motivation is for overwriting JAVA_HOME in the first place.

b) Check that JAVA_HOME is not set before overwriting it. I don't know where the code is that generates this script file, it seems to be related to this line in the formula:

```ruby
      (bin/basename).write_env_script file, Language::Java.overridable_java_home_env
```

**Comment by DomT4** [comment]
I thought the override was a deliberate thing. @xu-cheng?

**Comment by xu-cheng** [comment]
> b) Check that JAVA_HOME is not set before overwriting it. 

That's exactly what we do. We only set JAVA_HOME if it's not set.

**Comment by samskivert** [comment]
OK, maybe my bash-fu is bad, and indeed I didn't notice the `${JAVA_HOME:-$(/usr/libexec/java_home)}` but I did actually run the code and when I ran via that quoted script above, it failed to use my JAVA_HOME, but when I replaced the symlink in /usr/local/bin to point straight to the mvn in libexec/bin, it worked. So I'll debug further.

**Comment by samskivert** [comment]
OK, my bad. I swear I ran `mvn -v` with different JAVA_HOME settings and it always showed the default JVM, but now that I try it again, it's showing the JVM specified via JAVA_HOME.

Apologies for wasting your time.

**Comment by xu-cheng** [comment]
> Apologies for wasting your time.

No problem. It's my pleasure to help you out. :wink:

**Comment by bondolo** [comment]
A breadcrumb for people encountering similar problems and come across this bug:

If you have an /etc/mavenrc file and it contains a JAVA_HOME line then it will override whatever you specify on the command line.
