### ISSUE TITLE
Package `awscli` is 10 versions behind, current is 1.7.18

### ISSUE THREAD

**Issue by ms-ati** [Homebrew/homebrew#38205]
Hi folks, can we get `awscli` upgraded to 1.7.18?

I see that there is an old open PR to 1.7.12. Can that one be abandoned and just catch up to current?

**Comment by xu-cheng** [comment]
Could you try and open a pull request? This [document](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should be helpful. Thanks!
