### ISSUE TITLE
Question: homebrew-binary manual merge

### ISSUE THREAD

**Issue by vpmedia** [Homebrew/homebrew#38210]
Hi,
I've a pull request which I'm still depending, is it possible that someone can merge it?
https://github.com/Homebrew/homebrew-binary/pull/197

Thank you!

**Comment by mistydemeo** [comment]
In the future, could you please leave comments on the issue thread itself? Thanks! I've merged the PR.

**Comment by vpmedia** [comment]
Hi,
I've opened the request more than two weeks ago with comment. Thanks anyway!

**Comment by mikemcquaid** [comment]
@vpmedia One of the reasons we have the homebrew-binary tap is because not all the maintainers of this tap (myself included) are interested in maintaining binary software. As a result it's better to continue discussion over there, thanks!
