### ISSUE TITLE
brew-outdated/brew-upgrade overwrite tap-installed formula with default

### ISSUE THREAD

**Issue by jasonkarns** [Homebrew/homebrew#38255]
I use nodenv (0.2.0) as installed from jawshooah's tap. I realize the name conflicts with the nodenv formula that's default in homebrew. What i did *not* expect, was for `brew upgrade` to install the default nodenv formula over the tapped install. This virtually makes `brew outdated/brew-upgrade` virtually useless to me for it will continue to overwrite my nodenv install every time.

**Comment by mikemcquaid** [comment]
The alternative is not upgrading things from taps even when core has a newer version. That seems more annoying for most users than the nodenv case. As I've said before: the tap should be using a different name for `nodenv` to avoid this behaviour and/or a higher version number.

**Comment by jasonkarns** [comment]
Is the `name` the only identifying information that brew has for installed apps? I would imagine that it would be helpful for homebrew to have more meta information about installed apps, like the source formula. If homebrew knew the source of the formula that installed the app, it could show the correct 'outdated' info and also upgrade from the same source.

**Comment by DomT4** [comment]
Fair bit of data stored in ` INSTALL_RECEIPT.json `, including tap. Tap is a recent addition to that ` RECEIPT ` information, I think.

**Comment by mikemcquaid** [comment]
> If homebrew knew the source of the formula that installed the app, it could show the correct 'outdated' info and also upgrade from the same source.

It does. The problem is that I don't think it's a safe assumption that all users want to stay on the version from the tap even when it's older.

**Comment by jasonkarns** [comment]
Ah, I see. So it's generally assumed that any formulas with the same names are literally the same app, regardless of the source. (This particular naming conflict already has a discussion, #28955) While it's frustrating in this particular case, I think that's perfectly reasonable in the large.

OTOH, users installing a duplicated app from a tap instead of core are usually doing it for a very particular reason. Perhaps different build options or some other subtle difference (aside from just version). Perhaps an additional note in the `brew outdated` output would help clarify?

``` sh
$ brew outdated 
nodenv (0.2.0 from xyz tap < 0.3.3 from core)
```

I'm still thinking that a general `brew upgrade` without args should be conservative by default and not upgrade across sources. They can then be upgraded manually (per formula) or with a flag? `--force` or something?

I'm curious about other related situations and how homebrew handles them. What happens if I have an app installed from core, but a tap has a newer version? I'm assuming homebrew *wouldn't* upgrade using the tap, correct? So this is special behavior that only applies if core has the newer version?

Alternatively, what would happen if I have two different taps with the same-named app, but it doesn't exist in core at all? Would homebrew try to upgrade by switching taps? That doesn't seem intuitive, either.

**Comment by mikemcquaid** [comment]
> So it's generally assumed that any formulas with the same names are literally the same app, regardless of the source.

Yes. The way to avoid this is give them different names.

> Perhaps an additional note in the brew outdated output would help clarify?

Yeh, I'm open to changing the `outdated` output.

> Alternatively, what would happen if I have two different taps with the same-named app, but it doesn't exist in core at all? Would homebrew try to upgrade by switching taps? That doesn't seem intuitive, either.

This isn't intuitive because of how tap names are handled. In the longer term perhaps we should just add the tap name automatically to apps prefixes so you have `jawshooah-nodenv` or whatever instead. I do keep suggesting to tap authors to use different names but no-one listens so I guess we'll need to workaround that.

**Comment by jasonkarns** [comment]
> add the tap name automatically to apps prefixes so you have jawshooah-nodenv or whatever instead

I think this sounds like a good idea. To install a duped app from a tap, you need the fully qualified name anyhow, so it seems reasonable for any tap install to (almost?) always be referenced using the fully qualified name? I'm not sure what other implications this has, though.

**Comment by jasonkarns** [comment]
closing this in favor of #39991
