### ISSUE TITLE
could PPL be packaged?

### ISSUE THREAD

**Issue by UnixJunkie** [Homebrew/homebrew#38262]
http://bugseng.com/products/ppl/
tarball:
ftp://ftp.cs.unipr.it/pub/ppl/releases/1.1/ppl-1.1.tar.xz

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by jacknagel** [comment]
See also https://github.com/Homebrew/homebrew/commit/97973f5ec737a72aef729263a4e830ecc3a1bfea

**Comment by tdsmith** [comment]
There are examples in http://bugseng.com/products/ppl/download/ftp/releases/LATEST/README.configure of using gmp 5 so maybe this can move back to core.

**Comment by UnixJunkie** [comment]
I have a mac only at home ...

**Comment by DomT4** [comment]
Welcome a PR here if still interested.

**Comment by UnixJunkie** [comment]
I am still interested, but not time to do this.
I don't know why the PPL developpers don't package it for homebrew.

**Comment by UnixJunkie** [comment]
I think the issue should be loeft open.

**Comment by mikemcquaid** [comment]
@UnixJunkie We don't have time to create new formulae either, I'm afraid. If you're the person who would like it in Homebrew then you need to make time, sorry.

**Comment by UnixJunkie** [comment]
Can you assign it to me, then I will not forget about it and try to do it when at home in front
of a Mac.

**Comment by mikemcquaid** [comment]
@UnixJunkie Please manage it in your own todo list, thanks.
