### ISSUE TITLE
OpenAL-soft does not build on OSX Yosemite 10.10.2

### ISSUE THREAD

**Issue by seclorum** [Homebrew/homebrew#38274]
See https://gist.github.com/59e3c48f9c973c9cecbf

**Comment by tdsmith** [comment]
wfm. Does invoking brew like `HOMEBREW_MAKE_JOBS=1 brew install openal-soft` help?

**Comment by seclorum** [comment]
Alas, no:

https://gist.github.com/seclorum/92347fedcaed2b6640fa

**Comment by DomT4** [comment]
WFM too FWIW on 10.10.3: https://gist.github.com/anonymous/ea3860ec11c95999a8e5

**Comment by tdsmith** [comment]
Looking at the cmake output more closely, openal-soft has a thicket of undeclared optional dependencies and finds things we don't tell it about.

I can reproduce the failure after `brew install sdl2 sdl_sound`. If you unlink either of those with e.g. `brew unlink sdl_sound` the build should complete. I don't know what functionality they contribute but mixing SDL versions seems to cause the problem.

**Comment by seclorum** [comment]
Thanks for spotting that - openal-soft installed just fine!

**Comment by DomT4** [comment]
Should be solved by the next version of ` superenv ` if most recent discussions remain unchanged, but don't know if we want to ` conflicts_with ` or something in the mean time.

**Comment by jacknagel** [comment]
Action items:

 * tell the openal-soft cmake build to disable dependencies we aren't using

**Comment by DomT4** [comment]
Thanks for the nudge. Fix in #39563.
