### ISSUE TITLE
brew upgrade to node 0.12.1 failing at npm make install

### ISSUE THREAD

**Issue by natorojr** [Homebrew/homebrew#38279]
Upgrade to node 0.12.1 seems to be failing at npm make install.

I've double checked all permissions; I do not believe it's a permissions issue.

I would upload the npm-debug.log file, as suggested in the error output, but that file doesn't actually exist.

Any suggestions/workarounds?

```pre
==> Upgrading node
==> Downloading https://nodejs.org/dist/v0.12.1/node-v0.12.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/node-0.12.1.tar.gz
==> ./configure --prefix=/usr/local/homebrew/Cellar/node/0.12.1 --without-npm --without-ssl2 --without-ssl3
==> make install
==> Downloading https://registry.npmjs.org/npm/-/npm-2.7.3.tgz
Already downloaded: /Library/Caches/Homebrew/node--npm-2.7.3.tgz
==> ./configure --prefix=/usr/local/homebrew/Cellar/node/0.12.1/libexec/npm
==> make install
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/node20150401-13251-1d7l1vz/node-v0.12.1/npm_install/npm-debug.log
make: *** [install] Error 1
```

**Comment by DomT4** [comment]
Can you ` brew gist-logs node ` please?

**Comment by natorojr** [comment]
Here you go:

https://gist.github.com/anonymous/dcec290f0a6fdb9d7aec

If it helps at all, I'm currently running:
node v0.12.0
npm 2.7.3

**Comment by DomT4** [comment]
Unusual error. Don't think I've seen that one before. Does it reproduce if you upgrade again? If it does - Does it reproduce if you ` brew remove node && brew install node `?

**Comment by natorojr** [comment]
I've tried brew reinstall, but not remove & install separately. I was under the impression it did the same thing, but I'll just try to manually remove and reinstall and let you know.

Thanks for your help and timely responses.

**Comment by DomT4** [comment]
To a very large degree, they do the same thing. One shouldn't magically resolve what the other didn't, but it happens from time to time, and at worst it gives us another opportunity to generate a new ` gist-logs ` and see what changed.

It's odd that there's a minor ` ERR ` at the start, and then nothing until the end when we hit the fatal `ERR!`.

**Comment by natorojr** [comment]
Still erroring out in a similar fashion:

https://gist.github.com/anonymous/65cfafb3777c7923541a

**Comment by DomT4** [comment]
Gah. Alright. I haven't seen this before so I'm going to hunt around upstream's bug reports and see if anything similar has popped up.

For reference, the two errors in the ` npm ` make process are:

```
npm verb addLocalDirectory /private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/home/.npm/npm/2.7.3/package.tgz not in flight; packing
npm verb getCacheStat cache creation not in flight; initializing
npm ERR! makeCacheDir homeless?
npm verb tar pack [ '/private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/home/.npm/npm/2.7.3/package.tgz',
npm verb tar pack   '/private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install' ]
npm verb tarball /private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/home/.npm/npm/2.7.3/package.tgz
npm verb folder /private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install
npm info prepublish npm@2.7.3
npm WARN cannot run in wd npm@2.7.3 node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*/node_modules && make -j8 doc (wd=/private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install)
npm verb stack TypeError: Cannot read property 'uid' of undefined
npm verb stack     at WriteStream.<anonymous> (/private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install/lib/cache/add-local.js:102:33)
npm verb stack     at WriteStream.emit (events.js:129:20)
npm verb stack     at WriteStream.<anonymous> (/private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install/node_modules/fs-write-stream-atomic/index.js:93:37)
npm verb stack     at process._tickCallback (node.js:355:11)
npm verb cwd /private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install/cli.js" "install" "-g" "-f"
npm ERR! node v0.12.1
npm ERR! npm  v2.7.3

npm ERR! Cannot read property 'uid' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]
```

and

```
npm info install npm@2.7.3
npm info postinstall npm@2.7.3
npm verb unlock done using /private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/home/.npm/_locks/npm-75374983a7c00b34.lock for /usr/local/homebrew/Cellar/node/0.12.1/libexec/npm/lib/node_modules/npm
npm@2.7.3 /usr/local/homebrew/Cellar/node/0.12.1/libexec/npm/lib/node_modules/npm
npm verb stack Error: Callback called more than once.
npm verb stack     at errorHandler (/private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install/lib/utils/error-handler.js:108:16)
npm verb stack     at save (/private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install/lib/install.js:411:12)
npm verb stack     at /private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install/lib/install.js:137:7
npm verb stack     at /private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install/lib/install.js:264:7
npm verb stack     at /private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install/node_modules/read-installed/read-installed.js:138:5
npm verb stack     at /private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install/node_modules/read-installed/read-installed.js:251:14
npm verb stack     at cb (/private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install/node_modules/slide/lib/async-map.js:47:24)
npm verb stack     at /private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install/node_modules/read-installed/read-installed.js:251:14
npm verb stack     at cb (/private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install/node_modules/slide/lib/async-map.js:47:24)
npm verb stack     at /private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install/node_modules/read-installed/read-installed.js:251:14
npm verb cwd /private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/private/tmp/node20150401-44944-1xu6bmb/node-v0.12.1/npm_install/cli.js" "install" "-g" "-f"
npm ERR! node v0.12.1
npm ERR! npm  v2.7.3

npm ERR! Callback called more than once.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]
```

**Comment by DomT4** [comment]
@othiym23 Any chance the second error above is a race of some sort?

**Comment by natorojr** [comment]
@DomT4  Thanks for taking time to look into this.

Unfortunately my Node development environment is broken since I removed the previously installed version of node and npm. Any way to explicitly reinstall node 0.12.0? I did some quick Google/StackOverflow searching, but did not see a command for installing specific versions.

I'll keep searching.

**Comment by DomT4** [comment]
` brew install node ` should work - I'm not quite sure why it's building from source for you. Unless it's a lack of CLT thing, given that all our build machines have the CLT installed. Does ` brew install node ` always install the source build or have you explicitly enabled the source build somewhere?

It's not technically a supported mechanism, but:

```
brew install --build-from-source https://raw.githubusercontent.com/Homebrew/homebrew/ce29dbc587ec863743086d03865cb71371d8ce01/Library/Formula/node.rb && brew pin node
```

Should work.

**Comment by DomT4** [comment]
Oh I see. You've very very slightly moved your Homebrew installation from ` /usr/local ` to ` /usr/local/homebrew `. That's why it's building from source each time. Forgive my inability to read there, It's like 2am :smile_cat:. Try the second command though, see whether the 0.12.0 works for you.

**Comment by natorojr** [comment]
Thanks for the suggestion. I will give it a shot.

Yes I am using the alternative installation under /use/local/homebrew. Sorry I did not mention that previously. It has never been an issue for me before.

I'll have more time to debug deeper this evening (PST). Thanks again for your help.

**Comment by natorojr** [comment]
The only way I was able to get things working again was to completely wipe out my Homebrew installation and reinstall Homebrew per recommendation in the installation guide and FAQs.

Apparently when I initially setup brew, I went against the recommended installation instructions and opted to install it in an alternative location (/usr/local/homebrew) as well as using my root user. I guess I did this out of habit (I'm a long time Linux user). Surprisingly, I've never run into any issue with Homebrew until now. I've been using this unrecommended installation/setup for several years.

Anyhow, I appreciate your guidance @DomT4. I'll close the ticket for now and let you decide whether the errors I was seeing previously are worth looking into further.

**Comment by DomT4** [comment]
Ah. It's very possible the ` root ` aspect of that *was* causing problems. The location shouldn't have mattered though - Location should have just meant you had to build most things from source rather than using Homebrew's bottles.

If you hit further issues, feel free to reopen this. Otherwise I'll presume (and hope) having not seen it before it was environmental rather than systemic.

**Comment by alanquigley** [comment]
This issue is back in 0.7.3? Is bug closed?
