### ISSUE TITLE
gearmand: Could not open log file "/usr/local/Cellar/gearman/1.1.12/var/log/gearmand.log"

### ISSUE THREAD

**Issue by Krinkle** [Homebrew/homebrew#38290]
First time installing Gearman on OSX 10.10.2 Yosemite. Immediately after, per instructions, started it with `gearmand -d`. But yielded the following error:

> gearmand: Could not open log file "/usr/local/Cellar/gearman/1.1.12/var/log/gearmand.log"

**Comment by DomT4** [comment]
It's trying to place its ` var ` files in the wrong location. They shouldn't be in the ` Cellar `. Working on a fix now.
