### ISSUE TITLE
brew install gnutls --with-guile fails

### ISSUE THREAD

**Issue by smarek** [Homebrew/homebrew#38298]
Hi,

Is this known issue with GnuTLS or problem with my build environment?
I've been able to compile **3.3.13** without problems, but **3.3.14** in the same environment fails as shown in logs.

gisted logs: https://gist.github.com/smarek/b8d93db78031cebc97b4
apple debug files (core-68374c.c and core-68374c.sh) attached in revision 2 of this gist submit

Interesting section from logs:
```
Making install in doc
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../guile/src built-sources &&			\
	GUILE_AUTO_COMPILE=0 /usr/local/opt/guile/bin/guile -L ../guile/modules -l "./extract-guile-c-doc.scm"	\
	   -e '(apply main (cdr (command-line)))'			\
	   -- "../guile/src/core.c" "clang -E" "-I.. -I.. -I../lib/includes -I../lib/includes -I../extra/includes -I../guile/src -I../guile/src -D_THREAD_SAFE -I/usr/local/Cellar/guile/2.0.11_1/include/guile/2.0 -I/usr/local/Cellar/gmp/6.0.0a/include -I/usr/local/Cellar/readline/6.3.6/include -I/usr/local/Cellar/bdw-gc/7.4.2/include  "		\
	   > "core.c.texi"
GUILE_AUTO_COMPILE=0 /usr/local/opt/guile/bin/guile -L ../../guile/modules "make-enum-map.scm" > "enum-map.i.c.tmp"
GUILE_AUTO_COMPILE=0 /usr/local/opt/guile/bin/guile -L ../../guile/modules "make-smob-types.scm" > "smob-types.i.c.tmp"
GUILE_AUTO_COMPILE=0 /usr/local/opt/guile/bin/guile -L ../../guile/modules "make-enum-header.scm" > "enums.h.tmp"
GUILE_AUTO_COMPILE=0 /usr/local/opt/guile/bin/guile -L ../../guile/modules "make-smob-header.scm" > "smobs.h.tmp"
mv "smobs.h.tmp" "smobs.h"
mv "smob-types.i.c.tmp" "smob-types.i.c"
mv "enums.h.tmp" "enums.h"
mv "enum-map.i.c.tmp" "enum-map.i.c"
/usr/local/opt/guile/bin/guile-snarf -o core.x core.c -DHAVE_CONFIG_H  -I../../lib/includes -I../../lib/includes -I../../extra/includes -I../.. -I.  -g -O2 -I/usr/local/Cellar/libtasn1/4.4/include  -Wall -Wextra -Wno-strict-prototypes -Wno-unused-parameter  -I../../gl -I../../gl -D_THREAD_SAFE -I/usr/local/Cellar/guile/2.0.11_1/include/guile/2.0 -I/usr/local/Cellar/gmp/6.0.0a/include -I/usr/local/Cellar/readline/6.3.6/include -I/usr/local/Cellar/bdw-gc/7.4.2/include 
/usr/local/opt/guile/bin/guile-snarf -o errors.x errors.c -DHAVE_CONFIG_H  -I../../lib/includes -I../../lib/includes -I../../extra/includes -I../.. -I.  -g -O2 -I/usr/local/Cellar/libtasn1/4.4/include  -Wall -Wextra -Wno-strict-prototypes -Wno-unused-parameter  -I../../gl -I../../gl -D_THREAD_SAFE -I/usr/local/Cellar/guile/2.0.11_1/include/guile/2.0 -I/usr/local/Cellar/gmp/6.0.0a/include -I/usr/local/Cellar/readline/6.3.6/include -I/usr/local/Cellar/bdw-gc/7.4.2/include 
extracting Texinfo doc from `../guile/src/core.c'...  Backtrace:
In ice-9/boot-9.scm:
 157: 10 [catch #t #<catch-closure 105f782c0> ...]
In unknown file:
   ?: 9 [apply-smob/1 #<catch-closure 105f782c0>]
In ice-9/boot-9.scm:
  63: 8 [call-with-prompt prompt0 ...]
In ice-9/eval.scm:
 432: 7 [eval # #]
 386: 6 [eval # #]
 432: 5 [eval # #]
 411: 4 [eval # #]
 387: 3 [eval # #]
 387: 2 [eval # #]
In ice-9/boot-9.scm:
 702: 1 [map #<procedure parse-documentation-item (a)> #]
In unknown file:
   ?: 0 [scm-error misc-error #f ...]
 
ERROR: In procedure scm-error:
ERROR: invalid documentation item "arglist(void)"
make[1]: *** [core.c.texi] Error 1
clang: error: unable to execute command: Broken pipe: 13
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
make: *** [install-recursive] Error 1
clang: note: diagnostic msg:
```

**Comment by arnested** [comment]
I managed to install it using `gcc-4.9`:

    brew reinstall gnutls --cc=gcc-4.9

**Comment by smarek** [comment]
@arnested thank you for suggestion, it works, just it could probably have runtime problems, the warning shows

>Warning: gnutls dependency gmp was built with a different C++ standard library (libc++ from clang). This may cause problems at runtime.

**Comment by DomT4** [comment]
Funky. Works fine with everything except the ` guile ` optional dep enabled. Wonder what that's about.

**Comment by mistydemeo** [comment]
I can also repro this when building with Guile and clang, even when not using Homebrew. This should be reported to GnuTLS themselves - this looks like it's a problem with GnuTLS rather than Homebrew.

**Comment by DomT4** [comment]
I kicked it to Apple this morning along with various debug and compile logs, and just [filed with GnuTLS](https://gitlab.com/gnutls/gnutls/issues/6).

**Comment by smarek** [comment]
@DomT4 thank you, leaving the ticket closed, until solution will be provided either from GnuTLS or Apple.

**Comment by DomT4** [comment]
Apple's response:

> Engineering has determined that this is an issue for a third party to resolve.
This is a crash in the texinfo tool (or at least something related to that). It is piping its output to clang as a preprocessor. When texinfo crashes, clang complains with: clang: error: unable to execute command: Broken pipe: 13

GnuTLS have acknowledged the bug upstream, which is progress, hopefully :smile_cat:.

**Comment by smarek** [comment]
@DomT4 can you please link apple support link / gnutls issue link? Just for tracking purposes

**Comment by DomT4** [comment]
Apple's support links are all internal. Nothing I could do on that I'm afraid. The GnuTLS one is the one linked in [this comment above](https://github.com/Homebrew/homebrew/issues/38298#issuecomment-89447797).

It's also here: https://gitlab.com/gnutls/gnutls/issues/6

**Comment by DomT4** [comment]
Upstream seem to have left the issue open, but the latest release compiles fine against Guile.
