### ISSUE TITLE
How to commit a maintenance version?

### ISSUE THREAD

**Issue by mindrones** [Homebrew/homebrew#38294]
The recent commit history for the `neo4j` formula is: `2.1.7`, ... some `2.2.0` devel versions..., then `2.2.0` (stable).
Now they have released a maintenance version `2.1.8`: I'd like to update the formula but I don't know how: is it possible to commit this version in between `2.1.7` and `2.2.0`? Maybe as a `devel` version?

**Comment by mikemcquaid** [comment]
If the stable is 2.2.0 we can't add older versions than that. You could create a PR to add it into homebrew-versions, though.
