### ISSUE TITLE
Xcode 5 on 10.10

### ISSUE THREAD

**Issue by vronin-okta** [Homebrew/homebrew#38314]
If you had 10.9 with Xcode 5 and upgrade to Yosemite, your Xcode will still be Xcode 5.

xcode-select --print-path will be
" /Applications/Xcode.app/Contents/Developer"

And it won't contain usr/bin/git under it.
As result, this code " if developer_dir.empty? || !File.exist?("#{developer_dir}/usr/bin/git")" will determine that xcode command utilities needs to be installed. However, they are already installed and it will fail.

It makes sense to modify check to handle Xcode 5  or check explicitly for Xcode version and show more clear message that Xcode should be 6

**Comment by mistydemeo** [comment]
Does `brew doctor` state that Xcode is outdated?

**Comment by jacknagel** [comment]
`/Applications/Xcode.app/Contents/Developer/usr/bin/git` should exist under Xcode 5.
