### ISSUE TITLE
phash failing on OS X 10.10.2

### ISSUE THREAD

**Issue by shamoons** [Homebrew/homebrew#38316]
```
✗ brew install phash
==> Downloading http://phash.org/releases/pHash-0.9.6.tar.gz
Already downloaded: /Library/Caches/Homebrew/phash-0.9.6.tar.gz
==> ./configure --prefix=/usr/local/Cellar/phash/0.9.6_1 --enable-shared
==> make install
1 error generated.
make[1]: *** [audiophash.lo] Error 1
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I.. -D_THREAD_SAFE -I/usr/local/include -Dcimg_use_png -Dcimg_use_jpeg -O2 -ffast-math -O3 -c cimgffmpeg.cpp -o cimgffmpeg.o >/dev/null 2>&1
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I.. -D_THREAD_SAFE -I/usr/local/include -Dcimg_use_png -Dcimg_use_jpeg -O2 -ffast-math -O3 -c pHash.cpp -o pHash.o >/dev/null 2>&1
make: *** [install-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting
```

See Gist at: https://gist.github.com/2af9bdea5f038f21984f

**Comment by mistydemeo** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please read this and post the troubleshooting output it requests, thanks!

**Comment by shamoons** [comment]
@mistydemeo sounds good. updated the post

**Comment by jacknagel** [comment]
This will need to be patched to support Xcode-only systems; in the interim, you can install the CLT (`xcode-select --install`).

**Comment by jacknagel** [comment]
```diff
diff --git a/Library/Formula/phash.rb b/Library/Formula/phash.rb
index 9987945..5c46512 100644
--- a/Library/Formula/phash.rb
+++ b/Library/Formula/phash.rb
@@ -32,6 +32,8 @@ class Phash < Formula
   end
 
   def install
+    inreplace "src/ph_fft.h", "/usr/include/complex.h", "#{MacOS.sdk_path}/complex.h"
+
     args = %W[--disable-debug
               --disable-dependency-tracking
               --prefix=#{prefix}
```

I don't know why we need the full path, but compilation fails without it.

**Comment by mistydemeo** [comment]
Looks like the change was in response to these discussions: http://lists.phash.org/pipermail/phash-support-phash.org/2010-January/000032.html http://lists.phash.org/pipermail/phash-support-phash.org/2010-July/000083.html

Which occurred because a Macports-installed GCC had installed a `complex.h` in a place the phash build process had picked it up.

**Comment by robbiet480** [comment]
@jacknagel's fix worked for me, although the line that I had to use was `inreplace "src/ph_fft.h", "/usr/include/complex.h", "#{MacOS.sdk_path}/usr/include/complex.h"` (added `/usr/include/`)
