### ISSUE TITLE
CWE-327: Use of a Broken or Risky Cryptographic Algorithm (Medium Risk)

### ISSUE THREAD

**Issue by TheRook** [Homebrew/homebrew#38311]
It was observed that some formula use a dangerous combination of downloading packages over HTTP which is susceptible to MITM,  and using SHA1 for integrity checking. Multiple weaknesses have been found in SHA1 over the years.  The most concerning vulnerability in SHA-1 is the prefixing attack which permits an attacker to generate a 2nd pre-image that results in the same hash value. (http://en.wikipedia.org/wiki/SHA-1#Attacks).  The use of SHA-1 for validating the integrity of executable code in a security context is a violation of CWE-327(https://cwe.mitre.org/data/definitions/327.html).

The following Formula is vulnerable to this attack:
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/a2ps.rb#L5 

For **ALL** newly created packages,  consider enforcing the following rules:
- Disallow the use of SHA-1 in favor of any member of the SHA-2 family. 

- Disallow the use of HTTP as a package source.  (This is an information disclosure vulnerably,  no one should know what packages are installed on my system.)

**Comment by mistydemeo** [comment]
> Disallow the use of SHA-1 in favor of any member of the SHA-2 family. 

We are already doing this; we are in the process of migrating from sha1 to sha256, and any updated formulae are using sha256.

> Disallow the use of HTTP as a package source. (This is an information disclosure vulnerably, no one should know what packages are installed on my system.)

We use HTTPS wherever possible; however, some software is not distributed via HTTPS.

**Comment by TheRook** [comment]
It appears as though the majority of HTTP sources have a valid HTTPS source,  but the author of the formula chose to use HTTP.  For example, a2ps package can easily be changed to HTTPS:

https://ftp.gnu.org/gnu/a2ps/a2ps-4.14.tar.gz

**Comment by tdsmith** [comment]
I am comfortable with the strength of SHA-1 and disagree that hash collision attacks are practical. We are migrating to SHA-256 for future-proofing.

We are upgrading package URLs to https as new versions are released in the spirit of respecting pervasive monitoring as an attack. FWIW, other package management systems like apt use insecure transport and post-download validation as well. You may find this thread interesting: http://www.openwall.com/lists/oss-security/2015/03/22/2

**Comment by TheRook** [comment]
The source of your apt repository is important.  Clearly Ubuntu has a
stronger security posture than Kali.  That being said, the widespread use
of HTTP in Brew's formula is quite concerning, and playing off this problem
as "well we aren't the smelliest kid in the classroom",  doesn't make me
feel better about Brew's security posture.

**Comment by tdsmith** [comment]
Not a defense, just a data point. We're aware of and responding to the issues that you've identified.

**Comment by TheRook** [comment]
Thank you.

**Comment by DomT4** [comment]
> It appears as though the majority of formula that rely upon HTTP have a valid HTTPS source, but the author of the formula chose to use HTTP. For example, a2ps package can easily be changed to HTTPS

There are ` brew audit ` checks in place for SSL/TLS links at this point. If it's a common domain, the audit will kick up a fuss if you submit an update to something that should have an SSL/TLS protected link but doesn't. GNU, Apache, GNOME, Debian, Google Code, Github, Freedesktop, Fossies, ietf all have checks in place.

> we are in the process of migrating from sha1 to sha256, and any updated formulae are using sha256.

For anyone particularly interested, started keeping some specific numbers recently:

```
March 27th 2015:

SHA1 references in Homebrew formulae = ~2750
SHA256 references in Homebrew formulae = ~490

April 2nd 2015:

SHA1 references in Homebrew formulae = ~2740
SHA256 references in Homebrew formulae = ~565
```

The number of SHA256 sums in use has already doubled from the start of the year.

Fink still uses MD5, MacPorts offers a variety of MD5, SHA1, SHA256 and RMD160. Microsoft have recommended people migrate completely away from SHA1 for codesigning and verification purposes no later than 2016 - Homebrew is well on track for that. Compromising one SHA1 sum is still estimated to cost $700,000 - Not wildly affordable outside of state actors.

**Comment by TheRook** [comment]
@DomT4 Thats very cool, and I am happy to see these improvements.   It looks like there are 356 `brew audit` violations in the package system, which is roughly 10% of packages.  I very curious to see if this number goes down over time:

brew audit | grep "\*" | wc -l
356

**Comment by TheRook** [comment]
Here is a different approach:  What if instead of `brew audit`,  the audit procedures are enforced by the package manager.  If you know the source supports HTTPS,  just override the naive formula.

**Comment by DomT4** [comment]
There's a more invasive check under some discussion already. Long-term I'd like to scrap the individual checks and automatically check whether a website supports SSL/TLS or not with a ` curl ` ping - Effectively replacing two mountains worth of code with one simpler check. @bfontaine has a nice implementation of that already.

Complete formulae override is a more complicated topic - Especially because a lot of domains that work fine over SSL/TLS break on certain protocols - ` svn ` being the firm favourite for breaking on a normally securable link. Not a huge problem to workaround, but troublesome.

I don't know though - The maintainers here generally prefer actions over words (much to my frequent dismay :wink:) so if someone works on a PR that does that and tests it for a while and can prove it works and doesn't break on people and doesn't involve code that's likely to break, it may go somewhere.

**Comment by TheRook** [comment]
@DomT4 My only concern with a `curl` ping would be a downgrade attack similar to the TLS downgrade attack used in POODLE and other SSL/TLS cryptographic oracles.  Just because brew can't establish an SSL/TLS connection doesn't necessarily mean that one can't be established.

**Comment by DomT4** [comment]
Perfectly valid point - And a solid example of why getting security right is such a hard thing to do, all too often filled with half-compromises and best-efforts. Debian are probably the stand-up example of package-management security, but even they aren't perfect. We'll all keep working towards that elusive promise land :smile_cat:.

**Comment by mikemcquaid** [comment]
> It appears as though the majority of formula that rely upon HTTP have a valid HTTPS source, but the author of the formula chose to use HTTP. For example, a2ps package can easily be changed to HTTPS:
> 
> https://ftp.gnu.org/gnu/a2ps/a2ps-4.14.tar.gz

@TheRook Please submit a pull request to do so.

> @DomT4 Thats very cool, and I am happy to see these improvements. It looks like there are 356 brew audit violations in the package system, which is roughly 10% of packages. I very curious to see if this number goes down over time:

It will go down when people submit pull-requests and up when we add additional checks. The most helpful thing you could do would be to submit pull-requests.

> I don't know though - The maintainers here generally prefer actions over words (much to my frequent dismay ) so if someone works on a PR that does that and tests it for a while and can prove it works and doesn't break on people and doesn't involve code that's likely to break, it may go somewhere.

Indeed. We're all volunteers so if you think changes should be made the best way of showing us that is with (again) a pull request.

**Comment by jacknagel** [comment]
To summarize:

Here are the checksum numbers today.

```
$ git grep -l " sha1 " | wc -l
    2376
$ git grep -l " sha256 " | wc -l
     987
```

So we are steadily moving away from SHA1.

We are also merging patches which add https URLs every day.

Beyond that, any proposals can be discussed on the [mailing list](https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#community-forums), or in pull requests if they are at the code stage.

In the future, if you believe you have identified a security issue, please send it to our security list before posting it to the issue tracker: https://github.com/Homebrew/homebrew#security

Thanks!

**Comment by hubdotcom** [comment]
About to submit a batch of HTTPS urls for those that exist

**Comment by TheRook** [comment]
Awesome.
