### ISSUE TITLE
Erlang 17.5 package broke Elixir

### ISSUE THREAD

**Issue by jeffweiss** [Homebrew/homebrew#38345]
Erlang 17.5 was merged w/ #38295. However, this broke the latest packaged version of Elixir (v1.0.3) in the way illustrated in elixir-lang/elixir#3228. This should be fixed when upstream Elixir v1.0.4 is released and then included in homebrew.

I don't expect any action on this issue until upstream Elixir v1.0.4 is released. This issue is mostly an acknowledgement of the current state of brokenness, that it should only be broken for a few days, and that if Elixir devs upgrade Erlang ahead of Elixir v1.0.4, they can revert to a working system with 
```shell
$ brew switch erlang 17.4.1
Cleaning /usr/local/Cellar/erlang/17.4.1
Cleaning /usr/local/Cellar/erlang/17.5
11 links created for /usr/local/Cellar/erlang/17.4.1
$
```

**Comment by aforward** [comment]
For Ubuntu, I ran the following downgrade erlang to 17.4

```bash
$ wget http://packages.erlang-solutions.com/site/esl/esl-erlang/FLAVOUR_1_esl/esl-erlang_17.4-2~ubuntu~precise_amd64.deb
$ dpkg -i esl-erlang_17.4-2~ubuntu~precise_amd64.deb
$ apt-get update
$ apt-get install -y erlang
```

And then things worked again!  Thanks!

```
$ iex -v
Erlang/OTP 17 [erts-6.3] [source-f9282c6] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.0.3
```

**Comment by tdsmith** [comment]
Oops! We didn't catch this because elixir doesn't have a direct dependency on the erlang formula.

**Comment by mikemcquaid** [comment]
Can we add a direct dependency and something to the `test do` block that would catch this in future?

**Comment by jeffweiss** [comment]
From what I could tell of the Elixir formula, it currently relies on Erlang's major version number being 17, 18 or 19 (https://github.com/Homebrew/homebrew/blob/7bb66a8c0a947b8c6d9257da64bb3babb00574f8/Library/Formula/elixir.rb#L10).
I don't know the Homebrew philosophy in maintaining the minutia of dependencies that closely.
Right now (I think) we have a case of
Elixir v1.0.3 needs Erlang 17.x where x >= 0 && x < 5
Elixir v1.0.4 needs Erlang 17.x where x >= 0 || 18-rc1

I've never contributed to Homebrew before, but if you have an example formula where this fine-grained dependency management exists, I can take a stab at adding it to the Elixir formula.

Erlang 18 is the next major release, so I think it's safe to, for now, remove the possibility of an Erlang 19 as an acceptable dependency. (I'll submit a PR at least for that).

**Comment by mikemcquaid** [comment]
If you can produce a command that you can run with `elixir` which produces a reproduction of your test (e.g. succeeds/fails when expected) then that would be the best bet and we can add it to the elixir `test do` block along with a `depends_on "erlang"`

**Comment by tdsmith** [comment]
The version test does actually detect the breakage but something that exercises elixir a little more would be great.

**Comment by mikemcquaid** [comment]
Ah, ok. In that case shall we just add the dependency?

**Comment by dmarkow** [comment]
FYI, Elixir 1.0.4 was released a couple hours ago: https://github.com/elixir-lang/elixir/releases/tag/v1.0.4

**Comment by DomT4** [comment]
Someone already teed up a PR in #38447. Could always ask them to add the dep.

**Comment by mikemcquaid** [comment]
This should be sorted by 8e2015f instead which will correctly identify the dependency from the requirement.
