### ISSUE TITLE
Use hashpipe in the documentation

### ISSUE THREAD

**Issue by lookfirst** [Homebrew/homebrew#38349]
This may be overkill, but it seems like a good general idea. I've always been bothered by the initial install docs.

https://github.com/jbenet/hashpipe/#use-case

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install | hashpipe HASH)"

> It would require somehow getting hashpipe onto the users computer first though. So it might be too much trouble.

**Comment by jacknagel** [comment]
As you say, the user would have to install this tool somehow. The installer can't really have dependencies that aren't present on a clean system.
