### ISSUE TITLE
gcc4.9 compile fail on 10.10.2

### ISSUE THREAD

**Issue by mailletf** [Homebrew/homebrew#38343]
can't get gcc ton compile. I've tried what is suggested in the troubleshooting but I can't get it to work. Any help appreciated. logs here: https://gist.github.com/7190c98624fc81963a5e

brew install gcc
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc-4.9.2.tar.bz2
==> ../configure --build=x86_64-apple-darwin14.1.0 --prefix=/Users/mailletf/Documents/dev/homebrew/Cellar/gcc/4.9.2_1 --libdir=/Users/mailletf/Documents/dev/homebrew/Ce
==> make bootstrap
make[3]: *** [cc1plus] Error 1
rm gcc.pod
make[2]: *** [all-stage1-gcc] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2

**Comment by jacknagel** [comment]
It looks like you will need to address at least some of the `brew doctor` warnings, particularly regarding zlib. These files are interfering:

```
/usr/local/lib/libz.1.dylib
/usr/local/lib/libz.dylib
/usr/local/lib/libz.a
```
