### ISSUE TITLE
wine failing on 32bit 10.6.8 due to bad architecture detection for openssl

### ISSUE THREAD

**Issue by p3r7** [Homebrew/homebrew#38357]
When trying to install wine on a 32bit 10.6.8, I get the following:

https://gist.github.com/p3r7/48083d13f2d479bac368

It seems that brew tries to install twice openssl dependency, the second time for a  64bit architecture.

`arch` command seems to work correctly:
```
$ arch
i386
```

Also, when trying to gist-logs I get:
```
$ brew gist-logs wine
Error: No logs.
```

**Comment by tdsmith** [comment]
Could you share `brew config` and `brew doctor`?

**Comment by mistydemeo** [comment]
I've pushed a fix for this - can you `brew update` and try again?

**Comment by p3r7** [comment]
It did the trick, thanks a bunch!
