### ISSUE TITLE
encfs - no  target `encfs-man.html' - (with cask) yosemite 

### ISSUE THREAD

**Issue by xenomorpheus** [Homebrew/homebrew#38359]
Hi,

make[2]: *** No rule to make target `encfs-man.html', needed by `all-local'.  Stop.

At a guess, it looks like the Makefile requires encfs-man-html, but only creates the Makefile target if BUILD_MANHTML is true, so if BUILD_MANHTML target is false, there is no target, so the build fails.

Code:
https://github.com/vgough/encfs/blob/master/encfs/Makefile.am

all-local: encfs-man.html

if BUILD_MANHTML
encfs-man.html: encfs.pod
	@POD2HTML@ encfs.pod > $@
endif

My install output:

brew install encfs
==> Downloading https://github.com/vgough/encfs/archive/v1.8.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/encfs-1.8.1.tar.gz
==> make -f Makefile.dist
==> ./configure --prefix=/usr/local/Cellar/encfs/1.8.1 --with-boost=/usr/local
==> make
/usr/local/Library/ENV/4.3/pod2man --section=1 --release=1.8.1 --center="Encrypted Filesystem" encfsctl.pod encfsctl.1
make[2]: *** No rule to make target `encfs-man.html', needed by `all-local'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
(I did read that)

My System:
brew update has been done - twice
brew doctor reports ready to brew
Yosemite 10.10.2

**Comment by xenomorpheus** [comment]
Please see pull request #75

**Comment by xenomorpheus** [comment]
My patch has been merged in encfs - see https://github.com/vgough/encfs/pull/75

I'm sorry, but I don't know what happens now.

Does brew just wait for an update of encfs to be released?
Does brew need updating ?

**Comment by tdsmith** [comment]
Works for me without a patch.

We can pull a fix ahead of a release if we have evidence that it solves a problem but I don't think we have that. Can you share `brew gist-logs encfs` after a failing build?

**Comment by xenomorpheus** [comment]
https://gist.github.com/anonymous/e8fee2821895de697764

Nice feature gist-logs.

**Comment by mclare** [comment]
No idea if this patch solves things, but there's my gist logs from encfs not building last week https://gist.github.com/anonymous/a76be6d00be60035adbc - Thanks xenomorpheus for investigating.

**Comment by xenomorpheus** [comment]
I have to sleep now, but I note @mclare that you had these the other way round to me.
BUILD_MANHTML_FALSE=''
BUILD_MANHTML_TRUE='#'

**Comment by xenomorpheus** [comment]
brew updated.
All OSX patches installed.

BUILD_MANHTML_FALSE=1 brew gist-logs encfs

https://gist.github.com/5f8655fc55f6ae815835

**Comment by xenomorpheus** [comment]
Hi @tdsmith, @mclare and @jabley.  Thanks for your interest so far.

Do you have any suggestions that I may try?

I did a fresh brew update but I still get the same issue.

brew update
Already up-to-date.

brew gist-logs encfs
https://gist.github.com/66535ee886c2fbc524cd

I hope someone can help me.  Thanks.

**Comment by haggis310** [comment]
I had the same problem list above, before I realized I hadn't yet install OSXFuse (2.7.5).  Installed OSXFuse and reran install and success.  The error above was simply masking the real error earlier in the compile.

**Comment by rlhelinski** [comment]
I am having this problem now after updating to Brew 7e70d89, a clean bill of "brew doctor" health, and OSXFuse 2.8.2. It started with brew updating and upgrading. Please help! Thanks

$ brew gist-logs encfs
https://gist.github.com/fe5ca11182c1fddf7377

**Comment by hvisage** [comment]
Also having this on Yosemite 10.10.5

**Comment by DomT4** [comment]
Let's relocate this discussion to https://github.com/Homebrew/homebrew-fuse/issues/21, since the formula has moved over to that tap now.
