### ISSUE TITLE
Installing dependencies multiple times

### ISSUE THREAD

**Issue by snarkDoe** [Homebrew/homebrew#38409]
Homebrew installs things I've installed on my system earlier. For example, I installed OpenSSL some time earlier, now when I install python, it downloads and installs it again, also I don't think the versions differ so there's no sole purpose. Also, this clutters up free space and installation time due to repeated downloading what *I already have.*

**Comment by DomT4** [comment]
Likely situations are:

1) You inadvertently have an old dependency installed and when you ` brew install ` something new it'll drag in the new version.
2) You're building things with the ` --universal ` tag and consequently *all* dependencies must also be built with the ` --universal ` tag.

Some further details will be useful to maintainers regardless. ` brew doctor && brew config ` and perhaps a ` brew gist-logs python `.

**Comment by jacknagel** [comment]
Please provide a reproducible example, otherwise we have to assume that it's intentional (either a revision bump, or an old version, or a formula is passing options to a dependency that is missing them).

**Comment by snarkDoe** [comment]
@jacknagel @DomT4 see here https://gist.github.com/snarkDoe/9130cb904c9a8c852c5e

One question, does homebrew support linking to a package if a dependency is already installed, but as one for some other program or individually ?

**Comment by tdsmith** [comment]
Can you clarify? If you install python on a clean system, openssl will be installed as a dependency. If you subsequently install another formula that depends on openssl like wget, wget will use the installed openssl and will not install openssl again—unless the installed openssl is outdated, in which case openssl will be upgraded before wget is installed.

**Comment by jacknagel** [comment]
Closing as this is expected behavior. If you can provide reproduction steps that show otherwise, we can reopen the issue.
