### ISSUE TITLE
Calling cleanup should display filesizes of purged formulae

### ISSUE THREAD

**Issue by Alhadis** [Homebrew/homebrew#38404]
Just a small suggestion for a minor enhancement. =)

Pouring new brews will display the filesize of the installed formulae:
```bash
==> Upgrading imagemagick
==> Downloading https://homebrew.bintray.com/bottles/imagemagick-6.9.1-0.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring imagemagick-6.9.1-0.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/imagemagick/6.9.1-0: 1442 files,  22M
```
So why not do the same when invoking Homebrew's `cleanup` command? It might look like this:
```bash
Johns-MacBook-Pro:Desktop johngardner$ brew cleanup
Removing: /usr/local/Cellar/imagemagick/6.9.0-10... (1442 files, 22M)
Removing: /usr/local/Cellar/little-cms2/2.6... (16 files, 1.1M)
Removing: /Library/Caches/Homebrew/imagemagick-6.9.0-10.mavericks.bottle.tar.gz...
Removing: /Library/Caches/Homebrew/little-cms2-2.6.mavericks.bottle.1.tar.gz...
Removed: 1458 files, 23.1M total
```
Might be nice to see how much disk space was saved after a clean-up; some formulae can be pretty hefty in volume (here's looking at *you*, MongoDB).

**Comment by tdsmith** [comment]
That'd be cute. Care to submit a pull request? It would be interesting to know if it costs much time to compute, especially on magnetic disks.

**Comment by DomT4** [comment]
I worked on an implementation this morning after seeing this and going "Ooh, that'd be neat". I'll submit a PR shortly with it, but if OP wants to submit his own I'll close mine out and let @Alhadis work his magic.

**Comment by DomT4** [comment]
Pro-tip: Separate your finder windows so you don't end up overriding a morning's work copying and pasting between `cmd` folders to do benchmarks. *Kicks self in face repeatedly*.

**Comment by DomT4** [comment]
#38413

**Comment by Alhadis** [comment]
Haha, be my guest! :D I have barely any spare time these days (well... actually, *none*), which is why I've opened an issue instead of submitting a pull request.

**Comment by DomT4** [comment]
I definitely should have spent my morning catching up on uni work, but instead I saw this issue and thought "That sounds cool" and cool code ideas are essentially "shiny things" to me :smile_cat:
