### ISSUE TITLE
fontforge --with-x11 failed to build from source on 10.8.5 

### ISSUE THREAD

**Issue by yrammos** [Homebrew/homebrew#38402]
See https://gist.github.com/anonymous/155fe814fdf88fb7331c, generated by `git gist-logs fontforge`.

**Comment by tdsmith** [comment]
Failure is
```
In file included from ./macobjective.m:28:
In file included from ./macobjective.h:28:
In file included from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:43:
In file included from /System/Library/Frameworks/AppKit.framework/Headers/NSCIImageRep.h:10:
In file included from /System/Library/Frameworks/QuartzCore.framework/Headers/CIImage.h:1:
In file included from /System/Library/Frameworks/QuartzCore.framework/Headers/../Frameworks/CoreImage.framework/Headers/CIImage.h:9:
In file included from /System/Library/Frameworks/CoreVideo.framework/Headers/CoreVideo.h:25:
/System/Library/Frameworks/CoreVideo.framework/Headers/CVDisplayLink.h:27:10: fatal error: 'OpenGL/OpenGL.h' file not found
#include <OpenGL/OpenGL.h>
         ^
```

while building
```
clang called with: -I../inc -I../osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Headers -g -arch x86_64 -arch i386 -c ./macobjective.m -o macobjective.o
superenv removed:  -g -arch x86_64 -arch i386
superenv added:    -pipe -w -Os -march=native -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -I/usr/local/opt/gettext/include -I/usr/local/opt/icu4c/include
superenv executed: clang -pipe -w -Os -march=native -I../inc -I../osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Headers -c ./macobjective.m -o macobjective.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/opt/X11/include -isystem/opt/X11/include/freetype2 -I/usr/local/opt/gettext/include -I/usr/local/opt/icu4c/include
```

Does `/System/Library/Frameworks/OpenGL.framework/Headers/OpenGL.h` exist?

**Comment by yrammos** [comment]
> Does `/System/Library/Frameworks/OpenGL.framework/Headers/OpenGL.h` 
> exist?

No, actually even the `Headers` subdirectory does not exist. The output 
of `ls /System/Library/Frameworks/OpenGL.framework/` is:

```
total 40
drwxr-xr-x    8 root  wheel   272 Jan 31 15:46 ./
drwxr-xr-x  114 root  wheel  3876 Jan 31 15:46 ../
-rwxr-xr-x    1 root  wheel  6148 Jan 31 15:46 .DS_Store
lrwxr-xr-x    1 root  wheel    26 Jan 31 15:46 Libraries -> 
Versions/Current/Libraries
lrwxr-xr-x    1 root  wheel    23 Jan 31 15:46 OpenGL -> 
Versions/Current/OpenGL
lrwxr-xr-x    1 root  wheel    24 Jan 31 15:46 PlugIns -> 
Versions/Current/PlugIns
drwxr-xr-x   15 root  wheel   510 Jan 31 15:46 Resources/
drwxr-xr-x    4 root  wheel   136 Jan 31 15:46 Versions/
```

**Comment by yrammos** [comment]
> Does `/System/Library/Frameworks/OpenGL.framework/Headers/OpenGL.h` 
> exist?

No, actually even the `Headers` subdirectory does not exist. The output 
of `ls /System/Library/Frameworks/OpenGL.framework/` is:

    total 40
    drwxr-xr-x    8 root  wheel   272 Jan 31 15:46 ./
    drwxr-xr-x  114 root  wheel  3876 Jan 31 15:46 ../
    -rwxr-xr-x    1 root  wheel  6148 Jan 31 15:46 .DS_Store
    lrwxr-xr-x    1 root  wheel    26 Jan 31 15:46 Libraries -> 
    Versions/Current/Libraries
    lrwxr-xr-x    1 root  wheel    23 Jan 31 15:46 OpenGL -> 
    Versions/Current/OpenGL
    lrwxr-xr-x    1 root  wheel    24 Jan 31 15:46 PlugIns -> 
    Versions/Current/PlugIns
    drwxr-xr-x   15 root  wheel   510 Jan 31 15:46 Resources/
    drwxr-xr-x    4 root  wheel   136 Jan 31 15:46 Versions/

**Comment by yrammos** [comment]
(To which I should add that `OpenGL.h` does not exist anywhere on my system.)

**Comment by tdsmith** [comment]
Oh, well that'll do it. The other place you might look is with `find $(xcode-select -p) -name OpenGL.h`. I'm not sure whether should OpenGL.h come with the OS or if it's installed with Xcode.

**Comment by yrammos** [comment]
Very useful! I always forget that Spotlight does not search within app packages.
```
$ find $(xcode-select --print-path) -name OpenGL.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/OpenGL.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/OpenGL.h
```

**Comment by yrammos** [comment]
Is this something to add to `LDFLAGS`?

**Comment by DomT4** [comment]
Try ` ls -l /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers/ `.

**Comment by yrammos** [comment]
No, the last subdir in the path (`./Headers/`) does not exist. That path however is valid all the way up to and including `./Current`.

**Comment by DomT4** [comment]
Funky. @jacknagel I think you said a couple months back that you have a 10.8 box, is the ` OpenGL.framework ` lack of headers a regular thing?

**Comment by apjanke** [comment]
I have a 10.8 box that's from a recent fresh installation. Xcode hasn't been installed yet. The OpenGL headers are present.

```
kaw:~ janke$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.8.5
BuildVersion:	12F45
kaw:~ janke$ ls -l /System/Library/Frameworks/OpenGL.framework/
total 32
lrwxr-xr-x  1 root  wheel   24 Nov 14 00:08 Headers -> Versions/Current/Headers
lrwxr-xr-x  1 root  wheel   26 Nov 13 22:47 Libraries -> Versions/Current/Libraries
lrwxr-xr-x  1 root  wheel   23 Nov 13 22:47 OpenGL -> Versions/Current/OpenGL
lrwxr-xr-x  1 root  wheel   26 Nov 13 22:47 Resources -> Versions/Current/Resources
drwxr-xr-x  4 root  wheel  136 Nov 13 22:47 Versions
kaw:~ janke$ ls -l /System/Library/Frameworks/OpenGL.framework/Versions/
total 8
drwxr-xr-x  7 root  wheel  238 Nov 14 00:08 A
lrwxr-xr-x  1 root  wheel    1 Nov 13 22:47 Current -> A
kaw:~ janke$ ls /System/Library/Frameworks/OpenGL.framework/Versions/Current
Headers		Libraries	OpenGL		Resources	_CodeSignature
kaw:~ janke$ ls /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers/
CGLContext.h	CGLIOSurface.h	CGLTypes.h	gl3.h		gliContext.h	glu.h
CGLCurrent.h	CGLMacro.h	OpenGL.h	gl3ext.h	gliDispatch.h	gluContext.h
CGLDevice.h	CGLRenderers.h	gl.h		glext.h		gltypes.h	gluMacro.h
kaw:~ janke$
```

**Comment by DomT4** [comment]
> Xcode hasn't been installed yet.

Presumably no CLT either? Just bare 10.8.x?

**Comment by apjanke** [comment]
Wait, false alarm: Xcode *has* been installed on this box. Sorry.

**Comment by DomT4** [comment]
Strange. So a bare 10.8.5 installation with ` Xcode ` installed definitely has the headers for you, but not for @yrammos. Wonder whether it's worthwhile @yrammos removing Xcode and reinstalling it, but I'm hesitant to suggest it given the size of the ` Xcode ` download.

**Comment by apjanke** [comment]
I just tested this by building a new 10.8.5 box. Upon a fresh installation, the `Headers` directory and files do not exist. The `Libraries` and `Resources` dirs do. Which makes sense, since those are runtime parts of the framework and `Headers` is a compile time tool.

I installed Xcode from the App Store, ran it once so it could do its initial setup, and then downloaded its Command Line Tools. The `Headers` appeared when I installed the CLT, but not before. I think we can conclude the headers are part of the Xcode CLT.

So I think you're right: @yrammos, check to make sure the Command Line Tools from the current version of Xcode are installed. (Maybe there's some confusion due to an upgrade from an older Xcode that used `/Developer`?) And if that doesn't do it, removing and reinstalling Xcode is all I can see to do.

**Comment by DomT4** [comment]
If it's CLT lack that's the problem we may be able to cater to that circumstance. We have a few no-CLT-present hacks around. I *thought* Homebrew pointed out the Xcode paths to the compiler when the headers/tools didn't exist in the usual system directories though. Could have been wrong. Unless Fontforge have hardcoded it themselves, of course.

**Comment by DomT4** [comment]
Yeah, this *should* be being handled by superenv, seen in [this block](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/extend/ENV/super.rb#L159-L171). Not sure why it wouldn't be. @jacknagel @mikemcquaid Thoughts welcome.

**Comment by DomT4** [comment]
It looks like ` superenv ` is handing off [the wrong](https://gist.github.com/anonymous/155fe814fdf88fb7331c#file-02-configure-cc-L2-L3) paths to the compile, when it should be diving inside Xcode. Strange.

**Comment by DomT4** [comment]
Ah! I see. Okay. So user has the CLT installed, and when CLT is available superenv doesn't provide the inside-xcode paths. So why has the CLT not installed the headers necessary?

**Comment by yrammos** [comment]
I am sorry for the delay in reporting back. Xcode provides no way to uninstall or reinstall the CLT, and I didn't want to risk deleting something irrecoverable. So I just copied the `Headers` folder from the Xcode installation image into `/System/Library/Frameworks/OpenGL.framework/`, and indeed Fontforge was built successfully. I am puzzled by the issue as I have no idea why the headers were missing originally.

**Comment by jacknagel** [comment]
I think this can be closed, then? Holler if not.
