### ISSUE TITLE
Thank you for removing versions!

### ISSUE THREAD

**Issue by jwaldrip** [Homebrew/homebrew#38414]
I want to thank you for removing `homebrew versions`. After all, its not like ***certain libraries have dependencies on older versions***. In addition, we have been **very happy** with the additional **5-6 hours** you have added to our dev cycle. Also, we believe dealing with the homebrew-versions tap has everything we need and it's ***super intuitive***.

I hope you see that I am being extremely sarcastic here.... now please either give me a ***very rational*** reason for removing the feature, or add it back...

**Comment by tomchapin** [comment]
Seriously, though... why was it removed???

**Comment by mikemcquaid** [comment]
> I want to thank you for removing homebrew versions.

A pleasure.

> After all, its not like certain libraries have dependencies on older versions.

You're right, libraries in Homebrew core do not depend on older versions outside Homebrew core.

> In addition, we have been very happy with the additional 5-6 hours you have added to our dev cycle.

I'm glad that I've made you happy. Presumably it's because you're happy that you're learning to do these things yourself rather than relying on a team of volunteers to provide you with something for free.

> Also, we believe dealing with the homebrew-versions tap has everything we need and it's super intuitive.

I'm glad it has everything you need. If you find anything missing please consider submitting a pull request!

> I hope you see that I am being extremely sarcastic here

Oh! My mistake.

> now please either give me a very rational reason for removing the feature, or add it back...

No. You have not paid for this software and you are in no position to make demands.

> Seriously, though... why was it removed???

You can search through our issue tracker and read the discussions about why. In short: it didn't work consistently, we have no way of fixing bugs with older versions of formulae and because the `homebrew-versions` tap does not have these problems and can have binary packages.

**Comment by mikemcquaid** [comment]
Relatedly, lovely messages like this are why open-source maintainers burn out and stop working on software altogether. Something worth considering, I think.

**Comment by DomT4** [comment]
> Also, we believe dealing with the homebrew-versions tap has everything we need and it's super intuitive.

What's your problem with ` homebrew-versions `? In what was does it not cater to you, out of interest? If it's lacking stuff you want, submit PRs.

**Comment by tomchapin** [comment]
Today, I was trying to install the latest version of glib, but it had compile errors on OSX with the latest version (2.4.4)

To get things to work, I had to do the following commands:

cd /usr/local
brew versions glib
git checkout a569cc3 /usr/local/Library/Formula/glib.rb
brew install glib

This enabled me to install glib 2.4.2, which compiled successfully on my machine.

Without the brew versions command, how would I have done this? The homebrew-versions tap doesn't have glib?

**Comment by mikemcquaid** [comment]
> Today, I was trying to install the latest version of glib, but it had compile errors on OSX with the latest version (2.4.4)

`glib` has a bottle that should mean you don't need to compile it from source. If that's happening it's a bug and you should open a separate issue about it.

> Without the brew versions command, how would I have done this? The homebrew-versions tap doesn't have glib?

Various ways:

1. submit a pull-request to `homebrew-versions` for the older version of `glib` so others can benefit
2. copy and/or modify the old `brew versions` command and use that
3. `brew log glib`

**Comment by mikemcquaid** [comment]
@jwaldrip @tomchapin Please read our [Code of Conduct](https://github.com/Homebrew/homebrew/blob/master/CODEOFCONDUCT.md) before opening any new issues, pull requests or commenting in the Homebrew GitHub organisation in future. Thanks!

**Comment by jwaldrip** [comment]
Well @mikemcquaid I am now paying for your software. $10/wk, almost what I pay for adobe. :-) Keep up the good work.

**Comment by mikemcquaid** [comment]
> Well @mikemcquaid I am now paying for your software. $10/wk, almost what I pay for adobe. :-) Keep up the good work.

Well, you're not actually paying for our software, you're donating/tipping to help the project to actually be able to run at all. No Homebrew maintainer has ever received any money for working on the project for the last 7 years.

**Comment by jwaldrip** [comment]
@mikemcquaid All in all, I love Homebrew and I am happy to support it. Apologies for my sarcastic way of getting an answer to why it was removed in the first place. Is there anything I can do to find a way to make installing specific package versions more intuitive?

**Comment by mikemcquaid** [comment]
I appreciate the apology, thanks. The reply to @tomchapin above details a few ways. Also, if you can't create a pull request to `homebrew-versions` then an issue there requesting a particular version might be just as well received. Another option for your organisation is to copy older versions of formulae to a tap and then maintain that separately. That's the approach taken by Boxen and GitHub internally.
