### ISSUE TITLE
Formula name conflict omega and homebrew/game/omega

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew#38432]
I don't know how to resolve this situation. These are two different formulae and have been existing for quite a long time.

**Comment by mikemcquaid** [comment]
We should rename the formula in `homebrew/games`, I think, and just add a `caveat` explaining this.

**Comment by L2G** [comment]
Looks like this came up once before, back in September (Homebrew/homebrew-games#150). @jacknagel's response to the issue was to say it wasn't an issue.

**Comment by mikemcquaid** [comment]
CC @vladshablinsky who might be interested

**Comment by vladshablinsky** [comment]
:+1:
