### ISSUE TITLE
Wrong paths in binaries installed

### ISSUE THREAD

**Issue by arcz** [Homebrew/homebrew#38458]
I installed kafka with zookeeper but paths in binary are wrong, this happened also for ansible
```
zkServer start                                                     
/usr/local/bin/zkServer: line 2: @@HOMEBREW_PREFIX@@/etc/zookeeper/defaults: No such file or directory
/usr/local/bin/zkServer: line 3: cd: @@HOMEBREW_CELLAR@@/zookeeper/3.4.6_1/libexec/bin: No such file or directory
/usr/local/bin/zkServer: line 4: ./zkServer.sh: No such file or directory
```
```
cat /usr/local/bin/zkServer 

#!/usr/bin/env bash
. "@@HOMEBREW_PREFIX@@/etc/zookeeper/defaults"
cd "@@HOMEBREW_CELLAR@@/zookeeper/3.4.6_1/libexec/bin"
./zkServer.sh "$@"
```

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by arcz** [comment]
Hey, sorry for no details, I found solution in other issues, reinstalling OS X helped. Thanks anyway.
