### ISSUE TITLE
openssl-osx-ca fails under 10.10.3

### ISSUE THREAD

**Issue by tkrajacic** [Homebrew/homebrew#38462]
Upgrading to 10.10.3 will result in a terminal that says "You have Mail".
Checking out, what message the system sends you gives the following output:

    From username@MacbookPro.lan  Wed Apr  8 19:00:02 2015
    X-Original-To: username
    Delivered-To: username@MacbookPro.lan
    From: username@MacbookPro.lan (Cron Daemon)
    To: username@MacbookPro.lan
    Subject: Cron < username@MacbookPro> /usr/local/Cellar/openssl-osx-ca/1.0.4/bin/openssl-osx-ca     /usr/local/bin/brew
    X-Cron-Env: <SHELL=/bin/sh>
    X-Cron-Env: <PATH=/usr/bin:/bin>
    X-Cron-Env: <LOGNAME= username>
    X-Cron-Env: <USER= username>
    X-Cron-Env: <HOME=/Users/username >
    Date: Wed,  8 Apr 2015 19:00:01 +0200 (CEST)

    Usage error; try -help.
    rehash failed to verify, something is wrong
    check /tmp/openssl-osx-ca.5ipFC41Z/cert.pem for problems

which indicates trouble with openssl-osx-ca. So i tried re-installing the formula and this results in:

    ==> make install PREFIX='/usr/local/Cellar/openssl-osx-ca/1.0.4' BREW='/usr/local/bin/brew'
    /usr/local/Cellar/openssl-osx-ca/1.0.4/bin/openssl-osx-ca /usr/local/bin/brew
    Usage error; try -help.
    rehash failed to verify, something is wrong
    check /var/folders/7h/btk7zp2s6mv1d7sjr55q_vy80000gn/T/openssl-osx-ca.PcWVDiUm/cert.pem for problems
    make: *** [install] Error 1

The console also shows the problem:

    8.4.2015 19:38:27,620 openssl-osx-ca[1801]: /usr/local/etc/openssl/cert.pem updated failed, see cron

**Comment by mistydemeo** [comment]
We don't have a formula by this name; could you report it to the place you got this formula, please? Thanks!
