### ISSUE TITLE
problem with `brew linkapps fontforge`

### ISSUE THREAD

**Issue by lemzwerg** [Homebrew/homebrew#38477]
I've just upgraded brew to recent fontforge on my OS X 10.7.5.  brew recommends to call `brew linkapps fontforge`.  OK, doing this.  However, now clicking on the fontforge icon in the application folder gives me a window with an error message.

    FontForge is in the wrong folder on your computer.
    Please move the FontForge.app to your system /Applications folder.

Note that calling fontforge from the command line works.

**Comment by DomT4** [comment]
This isn't our "bug" I'm afraid. It's not technically a bug at all. Upstream have designed their App to run from ` /Applications `, the way Homebrew's ` brew linkapps ` works is to create symlinks from ` prefix/someapp.app ` to ` /Applications `.

The compromise reached with FontForge some time ago was that we'd make the App symlink and available, and in return they'd insert a message into the app on startup that if you want to use the app itself you should ` mv ` it to ` /Applications ` manually.

**Comment by lemzwerg** [comment]
Ah, ok.  How shall I know :-) @davelab6, can the wording of this message be improved?

On the other hand, `brew linkapps` could be more verbose for FontForge IMHO, probably explaining that more work is necessary to make it actually work...

**Comment by DomT4** [comment]
I suspect FontForge are also using the message for the situation where someone sticks the App bundle on their desktop or something, which is why it'll be generalised at their end. It's generalised on our end because the ` you should brew linkapps fontforge ` etc message you see is actually automatically generated; It doesn't come from within the Fontforge formula. I guess it wouldn't hurt too much to insert a conditional caveat into the formula on our end for clarity.

**Comment by erichuang1994** [comment]
I think I have the same problem.
I want to use the vim-powerline font.So I install fontforge as the tutorial.But when I ran it,it says that images doesn't find.

**Comment by davelab6** [comment]
https://github.com/fontforge/fontforge/commit/0c4087825faf7b0bb074729adac5b04c9507324a introduced this.

I agree there could be a caveat message appended; however, also, the above script could be changed to no longer notice that it isn't _actually_ in `/Applications`.

**Comment by DomT4** [comment]
> however, also, the above script could be changed to no longer notice that it isn't actually in /Applications.

If this would work and the app will run outside of ` /Applications ` and you're happy with it, that's pretty much the dream solution.

**Comment by davelab6** [comment]
I mean that the app may run if the symlink works to make the fontforge app
bundle THINK it is in /Applications when it actually is not; that's not the
same as it running outside of /Applications.

**Comment by DomT4** [comment]
Homebrew's ` linkapps ` mechanism is pure ` ln -sf `, nothing fancier than that, if that's useful information.

**Comment by DomT4** [comment]
Homebrew no longer supplies the Fontforge GUI. The command-line tools part of FontForge remains supported, but the GUI has been outsourced to `Caskroom/Homebrew-cask`.

If you want the GUI you should `brew tap caskroom/cask && brew cask install fontforge`, Thanks!

**Comment by apjanke** [comment]
Maybe the fontforge formula description should be updated to note that it's command-line only? `brew install fontforge`still includes a `share/fontforge/osx/FontForge.app` bundle; it just doesn't work. (If run outside `/Applications`, it gives me that "wrong location" error; if run inside `/Applications`, it just won't launch, and produces no error.) (I lost a decent amount of time this evening tracking it down.)

And/or have it not build the `FontForge.app` at all?
