### ISSUE TITLE
Installing aspell with language fails

### ISSUE THREAD

**Issue by jehrhardt** [Homebrew/homebrew#38484]
I tried to install aspell with

```sh
brew install aspell --with-lang-en --with-lang-de
```

It failed on `make install`

```
1 error generated.
1 error generated.
make[1]: *** [modules/filter/tex.lo] Error 1
make[1]: *** [modules/filter/sgml.lo] Error 1
make: *** [install-recursive] Error 1
```

Installing without languages works.

I am on Mac OS X 10.10.3.

https://gist.github.com/0a1e64a8e254d3f182d1

**Comment by dunn** [comment]
Might be a CLT vs Xcode problem, I have no problem on 10.10.3 with Xcode installed.

**Comment by jehrhardt** [comment]
Ok, it seems to be a problem with the commandline tools version 6.3. There is a discussion on Stackoverflow about the problem http://stackoverflow.com/questions/29529455/missing-c-header-debug-after-updating-osx-command-line-tools-6-3. Downgrading the commandline tools should work.

**Comment by jacknagel** [comment]
More information on #38514, where this issue is being tracked.
