### ISSUE TITLE
Please update the formula for autossh

### ISSUE THREAD

**Issue by treblam** [Homebrew/homebrew#38480]
Autossh have updated to version 1.4e(http://www.harding.motd.ca/autossh/), and fixed a bug, but the formula for autossh still install version 1.4d, please update it.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by tdsmith** [comment]
Closing in favor of #38487 (awesome, thanks!)
