### ISSUE TITLE
problems with cert verification by openssl on 10.10.3

### ISSUE THREAD

**Issue by chdiza** [Homebrew/homebrew#38491]
I'm wondering if anyone else who has `openssl` brewed, and has 10.10.3 installed, is finding that programs bound to the brewed openssl are flaking out and spewing "cert verification failure" warnings.

I'm getting this, and it happened instantly after upgrading to 10.10.3.

Experiment showed it doesn't matter whether the `openssl` was brewed prior to upgrading to 10.10.3, or brewed after the upgrade.

**Comment by mikemcquaid** [comment]
I've also seen this but I wrote it off as a random failure. @DomT4, mind digging in if you have a bit?

**Comment by DomT4** [comment]
Crap. This ain't pretty. Can you give me some URLs you tried so we're hitting the same targets in terms of judging what's reproducible consistently? I haven't hit it yet trying a few GNU URLs.

**Comment by DomT4** [comment]
They’ve removed the Equifax Secure CA.

**Comment by DomT4** [comment]
Just to check this fixes things for everyone else:

Open this in your browser: https://www.geotrust.com/resources/root_certificates/certificates/Equifax_Secure_Certificate_Authority.pem

Stick it in ` HOMEBREW_PREFIX/etc/openssl/certs ` and do ` HOMEBREW_PREFIX/opt/openssl/bin/c_rehash ` and then do ` brew test --verbose wget `.

**Comment by chdiza** [comment]
Gmail via imap won't work for this reason.

At first I thought that maybe the system certs with 10.10.3, that get generated automatically when one brews openssl, were to blame.  But then I poured the openssl bottle, which should have the certs from a 10.10.2 build, and the same problem exists.

I can also confirm this connection problem on three different machines, and on all of them the problem disappears upon booting back into 10.10.2.

**Comment by DomT4** [comment]
> But then I poured the openssl bottle, which should have the certs from a 10.10.2 build, and the same problem exists.

I believe postinstall is always done on the machine, never via the bottle.

**Comment by chdiza** [comment]
Workaround: Take the `osx_cert.pem` from a 10.10.2 brew of `openssl` and copy it to the relevant location on a 10.10.3 box.  Solved the problem for me.

**Comment by chdiza** [comment]
So is this a bug in 10.10.3?

**Comment by DomT4** [comment]
Looks like it. They've for some reason killed one of the most popular root certs on the planet from the Keychain. Add that one cert back, and everything rolls happiness again. I've kicked it to Apple. We may want to look at a workaround in the mean time.

**Comment by chdiza** [comment]
Ye gods.

:apple: :rage: :facepunch:

**Comment by DomT4** [comment]
Yeah, the missing Equifax root cert is being reported pretty widely this afternoon. Impacts iOS 8.3 as well apparently, which is fun.

Apple did state they'd made certificate changes in [this security update](https://support.apple.com/en-us/HT204659) but they don't explain the missing Equifax and given how extremely prevalent it is IMO we don't have much choice but to put it back and wait for Apple to explain why and then decide where we go from there.

**Comment by DomT4** [comment]
PR #38495

**Comment by mistydemeo** [comment]
The certificate in #38495, D2:32:09:AD:23:D3:14:23:21:74:E4:0D:7F:9D:62:13:97:86:63:3A, is a 1024-bit key that Mozilla is [also removing](https://bugzilla.mozilla.org/show_bug.cgi?id=986019#c9). I'm guessing this was on purpose, and not an accident - in which case we should not work around it.

**Comment by DomT4** [comment]
The cert is old, and weak, and should die. But the breakage removal is causing is pretty major, and I get the feeling Homebrew's going to get shoved by issues along the lines of "Why did Homebrew break wget, put it back", which sucks. Problem is compounded by CAs typically having long expiry dates and being expensive to replace prematurely, so there's this general lack of urgency in moving away from the old certs.

There's no happy solution here, and I'm generally thankful it's not my call to make. Whatever is decided, I have no moans on. If we do go ahead it'll need to be applied to LibreSSL as well.

**Comment by chdiza** [comment]
Gmail is broken until this is fixed.  Should I leave a bug report asking Google to stop requiring the cert in question?

**Comment by chdiza** [comment]
Gmail is broken until this is fixed.  Should I leave a bug report asking Google to stop requiring the cert in question?

**Comment by chdiza** [comment]
Gmail is broken until this is fixed.  Should I leave a bug report asking Google to stop requiring the cert in question?

**Comment by chdiza** [comment]
Sorry for the spam, the github web interface went wonky.

**Comment by felixbuenemann** [comment]
I've had the same problem with rails-assets.org (see rails-assets/rails-assets#239) and fixed it by importing the popular [curl ca bundle](http://curl.haxx.se/ca/cacert.pem). I'm not sure why apple is dropping this root, because most warnings for sha1 signatures are only aimed at servers certs and intermdiated, while sha1 roots are generally considered ok, because they are already in the key stores. At least that's how [ssllab's ranking](https://community.qualys.com/blogs/securitylabs/2014/09/09/sha1-deprecation-what-you-need-to-know) works.

**Comment by tdsmith** [comment]
> I'm not sure why apple is dropping this root, because most warnings for sha1 signatures are only aimed at server certs and intermdiates

The key size is the issue, not the signing algorithm.
