### ISSUE TITLE
maven formula fails on OS X 10.10.3

### ISSUE THREAD

**Issue by consulthys** [Homebrew/homebrew#38505]
```
> brew install maven
Error: Mac OS X '10.1' is invalid
```

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by jacknagel** [comment]
Start with `brew update`.
