### ISSUE TITLE
sudo access proposed changes

### ISSUE THREAD

**Issue by anantshri** [Homebrew/homebrew#38509]
I have a setup where the user with brew setup doesn't have sudo access. While mac takes it gracefully by allowing a username as well as password prompt, brew assumes that sudo is enabled for user and the step fails after a long download of file.

Here are two options i am suggesting.
1) We check for sudo access before hand or via variable and don't download the file if sudo is needed when user does'nt have sudo access.
2) find a way to prompt a username and password to use for privilege elevation.

**Comment by anantshri** [comment]
looks like wither i am confused or my statement confused people.

The user doesn't have sudo but some software might want to change system settings and need sudo access. that's the point where we need those suggested options.

example if you install say virtualbox via brew then it need to install a couple of drivers which require them to have sudo access or i suppose any .pkg file is executed via installer with sudo permission. I hope this makes it a bit more clear.

**Comment by mikemcquaid** [comment]
Nothing in Homebrew should require `sudo` to be installed. Some may require `sudo` to run but when that's the case it's noted in their caveats. I agree it'd be nice if the installer didn't require `sudo` but I don't think there's a way around that.

**Comment by anantshri** [comment]
I agree there might not be a way around. thats where we can make a check if the user doesn't have sudo why bother downloading the package. its just a waste of bandwidth and extra time. 
Also correct me if i am wrong, i am using brew cask command to install those software do you think it would be more appropriate to raise this concern at https://github.com/caskroom/homebrew-cask instead of here. My idea was that they also use homebrew and hence a issue here might make more sense.

**Comment by mikemcquaid** [comment]
> Also correct me if i am wrong, i am using brew cask command to install those software do you think it would be more appropriate to raise this concern at https://github.com/caskroom/homebrew-cask instead of here. My idea was that they also use homebrew and hence a issue here might make more sense.

Yup, raising there would be better as they rely more on `sudo` I think.

**Comment by anantshri** [comment]
Thanks for the tip raised issue in homebrew-cask
