### ISSUE TITLE
ffmpeg fails

### ISSUE THREAD

**Issue by ronag** [Homebrew/homebrew#38515]
```
brew uninstall --force ffmpeg
brew update
brew install ffmpeg
ffplay --version
```

Gives me:

```
dyld: Library not loaded: /usr/local/lib/libx264.142.dylib                           │
  Referenced from: /usr/local/bin/ffplay                                             │
  Reason: image not found    
```

**Comment by DomT4** [comment]
Try ` brew reinstall x264 `. You may need to reinstall ` ffmpeg ` afterwards as well.

**Comment by ronag** [comment]
Didn't help. ffmpeg seems to be looking for an older x264 version than what is installed.

**Comment by jacknagel** [comment]
>You may need to reinstall ffmpeg afterwards as well.

**Comment by ronag** [comment]
@jacknagel: Yes, I have done that as well. Both default and from HEAD. Still looking for 144.

**Comment by ronag** [comment]
Also run brew doctor and fixing all warnings. Still no success.

**Comment by jacknagel** [comment]
The current ffmpeg package is linked to `/usr/local/lib/libx264.144.dylib`.

What does `brew info ffmpeg` say?

**Comment by ronag** [comment]
Fixed after update.
