### ISSUE TITLE
brew can not be install in macosx 10.10

### ISSUE THREAD

**Issue by epiphyllum** [Homebrew/homebrew#38516]
remote: Total 3525 (delta 34), reused 1513 (delta 18), pack-reused 0
Receiving objects: 100% (3525/3525), 2.63 MiB | 28.00 KiB/s, done.
Resolving deltas: 100% (34/34), done.
From https://github.com/Homebrew/homebrew
 * [new branch]      master     -> origin/master
error: unable to unlink old 'Library/Aliases/0mq' (Permission denied)
error: unable to unlink old 'Library/Aliases/4store' (Permission denied)
error: unable to unlink old 'Library/Aliases/Secret Rabbit Code' (Permission denied)
error: unable to create symlink Library/Aliases/actor-framework (Permission denied)
error: unable to create symlink Library/Aliases/adwaita-icon-theme (Permission denied)
error: unable to unlink old 'Library/Aliases/ag' (Permission denied)
error: unable to unlink old 'Library/Aliases/alut' (Permission denied)

**Comment by epiphyllum** [comment]
```
remote: Total 3525 (delta 34), reused 1513 (delta 18), pack-reused 0
Receiving objects: 100% (3525/3525), 2.63 MiB | 28.00 KiB/s, done.
Resolving deltas: 100% (34/34), done.
From https://github.com/Homebrew/homebrew
 * [new branch]      master     -> origin/master
error: unable to unlink old 'Library/Aliases/0mq' (Permission denied)
error: unable to unlink old 'Library/Aliases/4store' (Permission denied)
error: unable to unlink old 'Library/Aliases/Secret Rabbit Code' (Permission denied)
error: unable to create symlink Library/Aliases/actor-framework (Permission denied)
error: unable to create symlink Library/Aliases/adwaita-icon-theme (Permission denied)
error: unable to unlink old 'Library/Aliases/ag' (Permission denied)
error: unable to unlink old 'Library/Aliases/alut' (Permission denied)
```

**Comment by epiphyllum** [comment]
mayflower:~ hary$ 
mayflower:~ hary$ which brew
/usr/local/bin/brew
mayflower:~ hary$ brew update
/usr/local/bin/brew: /usr/local/Library/brew.rb: /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby: bad interpreter: No such file or directory
/usr/local/bin/brew: line 21: /usr/local/Library/brew.rb: Undefined error: 0
mayflower:~ hary$ which ruby
/usr/bin/ruby
mayflower:~ hary$

**Comment by mikemcquaid** [comment]
It seems you already had it installed on your system. Try `sudo chown -R $USER /usr/local; cd /usr/local; git fetch; git reset --hard origin/master; brew update`.

**Comment by epiphyllum** [comment]
thanks;  it's ok now

**Comment by Spritefarmer** [comment]
thanks!
