### ISSUE TITLE
installation failure after uninstallation

### ISSUE THREAD

**Issue by sjin09** [Homebrew/homebrew#38551]
To whom it may concern,

I have tried uninstalling homebrew, following these commands:

```
cd `brew --prefix`
git checkout master
git ls-files -z | pbcopy
rm -rf Cellar
bin/brew prune
pbpaste | xargs -0 rm
rm -r Library/Homebrew Library/Aliases Library/Formula Library/Contributions 
test -d Library/LinkedKegs && rm -r Library/LinkedKegs
rmdir -p bin Library share/man/man1 2> /dev/null
rm -rf .git
rm -rf ~/Library/Caches/Homebrew
rm -rf ~/Library/Logs/Homebrew
rm -rf /Library/Caches/Homebrew
```

after that I tried re-installing homebrew using the following command, available on the website 

```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

I get the following error. It seems to be echoing all the installation scripts... Would you be able to help with what I should do? 

Warm Regards,
Jin

```
Bad escape character '#!/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby
```

[edit: removed contents of install script]

**Comment by jacknagel** [comment]
What does `ruby -e "puts :hi"` say? What about `/usr/bin/ruby -e "puts :hi"`?

**Comment by sjin09** [comment]
You are an absolute lift savior! How dumb of me not to think of that simple solution!
