### ISSUE TITLE
"brew install sip --with-python3" installs with system python if python brew is not installed

### ISSUE THREAD

**Issue by LunarLanding** [Homebrew/homebrew#38560]
Possibly related to https://github.com/ehershey/homebrew/commit/070a8a7862af12e00f8cca4c123e2490bca1230e
?

After making "brew install python" and "brew install --without-python -with-python3", it worked (linked to python 3 and not system python 2), but the warning that the commit above would have given me would have spared me a lot of time.

**Comment by tdsmith** [comment]
The warning is no longer correct. `brew install sip --with-python3` will build twice -- once for python2 (against system Python, if that's the installed `python`), and again for python3.

**Comment by LunarLanding** [comment]
Ahh, sorry, now I see... I think I got confused by expecting with-python3
to build for python3 only,  and,  as I didn't have python2 installed with
brew, the warning about not being able to  find python2 site-packages
convinced me brew wasn't building for python3.

**Comment by tdsmith** [comment]
Okay, great. Sorry for the confusion! Let us know if we can help with anything else.
