### ISSUE TITLE
syncthing won't autostart 

### ISSUE THREAD

**Issue by nathan-thenut** [Homebrew/homebrew#38593]
Syncthing won't autostart due to not having admin rights for /usr/local/var/log/syncthing.log. Changed
the logpath in the plist file to /tmp/syncthing.log and it works fine. Here is my old plist file: https://paste.xinu.at/iAq/
The plist file is created via the formula.

**Comment by DomT4** [comment]
` sudo chown -R $(whoami) /usr/local ` should resolve the errors by making sure ` var ` is owned by you.

**Comment by nathan-thenut** [comment]
But is it really a good idea to own /usr/local as a normal user?

**Comment by DomT4** [comment]
Nothing is normally in ` /usr/local `, so it's not like you're suddenly unrooting system utilities. If you're strongly against ` /usr/local ` though you shouldn't install Homebrew there. Without the correct permissions to write across directories you'll run into endless pain.

**Comment by mikemcquaid** [comment]
> But is it really a good idea to own /usr/local as a normal user?

Yes. You can write to `/Applications` as a normal user too.

**Comment by jacknagel** [comment]
Closing per the above.
