### ISSUE TITLE
PostGIS fails to find libCGAL.10.dylib

### ISSUE THREAD

**Issue by lukehorvat** [Homebrew/homebrew#38597]
Recently installed the `postgis` package (2.1.7), which has a dependency on `cgal` (4.6) and `sfcgal` (1.0.5). It installs successfully via Homebrew, but any attempts to use it fail:

```sh
psql -d test_db -c "create extension postgis"
```

```sh
ERROR:  could not load library "/usr/local/Cellar/postgresql/9.4.1/lib/postgis-2.1.so": dlopen(/usr/local/Cellar/postgresql/9.4.1/lib/postgis-2.1.so, 10): Library not loaded: /usr/local/lib/libCGAL.10.dylib
  Referenced from: /usr/local/lib/libSFCGAL.1.dylib
  Reason: image not found
```

This is on OSX 10.9.5.

**Comment by lukehorvat** [comment]
Hmmm. It seems reinstalling `sfcgal` with the `--build-from-source` flag specified resolves the error. So it seems there may be an issue with the bottled version...?

**Comment by moonshadow** [comment]
Same problem for me .

**Comment by schmijos** [comment]
I can confirm that. @lukehorvat: Your hint did it also for me.

**Comment by arturoherrero** [comment]
I have the same error. This works for me:

```
$ brew install cmake
$ brew reinstall sfcgal --build-from-source
```

**Comment by rebelliard** [comment]
Reinstalling `sfcgal` from source worked for me too.

**Comment by joaoponceleao** [comment]
Just a heads up.... I wasn't having this problem until the latest .5_1 update - Now I'm building from source....

**Comment by klappradla** [comment]
Had the same problem after updating postgres/postgis today. @arturoherrero's solution works. Thanx!

**Comment by charlax** [comment]
Same problem & solution.

**Comment by rizumu** [comment]
Same problem, but solution is not working on OSX 10.10.3.

```
$ brew reinstall cmake && brew reinstall sfcgal --build-from-source
==> Reinstalling cmake
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.2.1.yosemite.bottle.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/cmake-3.2.1.yosemite.bottle.2.tar.gz
==> Pouring cmake-3.2.1.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/cmake/3.2.1: 1847 files, 32M
==> Reinstalling sfcgal
==> Downloading https://github.com/Oslandia/SFCGAL/archive/v1.0.5.tar.gz
Already downloaded: /Library/Caches/Homebrew/sfcgal-1.0.5.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/sfcgal/1.0.5_1 -DCMA
==> make install
make[2]: *** [src/CMakeFiles/SFCGAL.dir/SFCGAL/algorithm/area.cpp.o] Error 1
1 error generated.
make[2]: *** [src/CMakeFiles/SFCGAL.dir/SFCGAL/algorithm/BoundaryVisitor.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/SFCGAL.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting

$ psql -d postgres -c "create extension postgis"
ERROR:  could not load library "/usr/local/Cellar/postgresql/9.4.1/lib/postgis-2.1.so": dlopen(/usr/local/Cellar/postgresql/9.4.1/lib/postgis-2.1.so, 10): Library not loaded: /usr/local/lib/libCGAL.10.dylib
  Referenced from: /usr/local/lib/libSFCGAL.1.dylib
  Reason: image not found
```

**Comment by basdergruene** [comment]
I do have the same issue, half a year later. And building sfcgal from source fails (on 10.8.5).

    $ brew install sfcgal --build-from-source 
    ==> Downloading https://github.com/Oslandia/SFCGAL/archive/v1.0.5.tar.gz
    Already downloaded: /Library/Caches/Homebrew/sfcgal-1.0.5.tar.gz
    ==> cmake . -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/sfcgal/1.0.5_2 -DCMAKE_BUILD
    ==> make install
    Last 15 lines from /Volumes/1000er Intern/Users/Janne/Library/Logs/Homebrew/sfcgal/02.make:
          boost::archive::binary_oarchive_impl<boost::archive::binary_oarchive, char, std::char_traits<char> >::binary_oarchive_impl(std::ostream&, unsigned int) in Serialization.cpp.o
      "boost::archive::basic_binary_oprimitive<boost::archive::binary_oarchive, char, std::char_traits<char> >::~basic_binary_oprimitive()", referenced from:
          SFCGAL::io::BinarySerializer::BinarySerializer(std::ostream&) in Serialization.cpp.o
          SFCGAL::io::writeBinaryGeometry(SFCGAL::Geometry const&) in Serialization.cpp.o
          SFCGAL::io::writeBinaryPrepared(SFCGAL::PreparedGeometry const&) in Serialization.cpp.o
          SFCGAL::io::BinarySerializer::~BinarySerializer() in Serialization.cpp.o
          SFCGAL::io::BinarySerializer::~BinarySerializer() in Serialization.cpp.o
          boost::archive::binary_oarchive_impl<boost::archive::binary_oarchive, char, std::char_traits<char> >::binary_oarchive_impl(std::ostream&, unsigned int) in Serialization.cpp.o
          boost::archive::binary_oarchive_impl<boost::archive::binary_oarchive, char, std::char_traits<char> >::~binary_oarchive_impl() in Serialization.cpp.o
          ...
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[2]: *** [src/libSFCGAL.1.0.5.dylib] Error 1
    make[1]: *** [src/CMakeFiles/SFCGAL.dir/all] Error 2
    make: *** [all] Error 2

https://gist.github.com/anonymous/8fbf49ae73d5f89cb5cf

I have almost no clue what I am doing here. But it started when pgAdminIII reported this issue with postgis:

![bildschirmfoto 2015-10-30 um 10 47 55](https://cloud.githubusercontent.com/assets/2720460/10845290/ecc8cd06-7f06-11e5-8f36-edca894bb1f3.png)

When I install sfcgal from bottle I get a warning about a different c++ standard. No clue if this is important?

    ==> Pouring sfcgal-1.0.5_2.mountain_lion.bottle.tar.gz
    Warning: sfcgal dependency boost was built with a different C++ standard
    library (libc++ from clang). This may cause problems at runtime.
    🍺  /usr/local/Cellar/sfcgal/1.0.5_2: 112 files, 10M

And `brew info` tells me, that I build boost 1.58.0 from source - is that an issue?

    $ brew info boost
    boost: stable 1.58.0 (bottled), HEAD
    Collection of portable C++ source libraries
    http://www.boost.org
    /usr/local/Cellar/boost/1.54.0 (9865 files, 576M)
      Built from source with: --with-icu
    /usr/local/Cellar/boost/1.57.0 (10572 files, 418M)
      Built from source with: --with-icu4c
    /usr/local/Cellar/boost/1.58.0 (10718 files, 455M) *
      Built from source with: --c++11 --with-icu4c
    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boost.rb

Is there anything I can do to fix it? Or should I just wait for the postgis 2.2.0 update? https://github.com/Homebrew/homebrew/pull/44728

(when it comes to homebrew and compiling I consider myself only being an enduser with almost no bug fixing skills...)

**Comment by jannefleischer** [comment]
(sorry for double post; wrong account, earlier)

I do have the same issue, one and a half year later. And building sfcgal from source fails (on 10.8.5).

    $ brew install sfcgal --build-from-source 
    ==> Downloading https://github.com/Oslandia/SFCGAL/archive/v1.0.5.tar.gz
    Already downloaded: /Library/Caches/Homebrew/sfcgal-1.0.5.tar.gz
    ==> cmake . -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/sfcgal/1.0.5_2 -DCMAKE_BUILD
    ==> make install
    Last 15 lines from /Volumes/1000er Intern/Users/Janne/Library/Logs/Homebrew/sfcgal/02.make:
          boost::archive::binary_oarchive_impl<boost::archive::binary_oarchive, char, std::char_traits<char> >::binary_oarchive_impl(std::ostream&, unsigned int) in Serialization.cpp.o
      "boost::archive::basic_binary_oprimitive<boost::archive::binary_oarchive, char, std::char_traits<char> >::~basic_binary_oprimitive()", referenced from:
          SFCGAL::io::BinarySerializer::BinarySerializer(std::ostream&) in Serialization.cpp.o
          SFCGAL::io::writeBinaryGeometry(SFCGAL::Geometry const&) in Serialization.cpp.o
          SFCGAL::io::writeBinaryPrepared(SFCGAL::PreparedGeometry const&) in Serialization.cpp.o
          SFCGAL::io::BinarySerializer::~BinarySerializer() in Serialization.cpp.o
          SFCGAL::io::BinarySerializer::~BinarySerializer() in Serialization.cpp.o
          boost::archive::binary_oarchive_impl<boost::archive::binary_oarchive, char, std::char_traits<char> >::binary_oarchive_impl(std::ostream&, unsigned int) in Serialization.cpp.o
          boost::archive::binary_oarchive_impl<boost::archive::binary_oarchive, char, std::char_traits<char> >::~binary_oarchive_impl() in Serialization.cpp.o
          ...
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[2]: *** [src/libSFCGAL.1.0.5.dylib] Error 1
    make[1]: *** [src/CMakeFiles/SFCGAL.dir/all] Error 2
    make: *** [all] Error 2

https://gist.github.com/anonymous/8fbf49ae73d5f89cb5cf

I have almost no clue what I am doing here. But it started when pgAdminIII reported this issue with postgis:

![bildschirmfoto 2015-10-30 um 10 47 55](https://cloud.githubusercontent.com/assets/2720460/10845290/ecc8cd06-7f06-11e5-8f36-edca894bb1f3.png)

When I install sfcgal from bottle I get a warning about a different c++ standard. No clue if this is important?

    ==> Pouring sfcgal-1.0.5_2.mountain_lion.bottle.tar.gz
    Warning: sfcgal dependency boost was built with a different C++ standard
    library (libc++ from clang). This may cause problems at runtime.
    🍺  /usr/local/Cellar/sfcgal/1.0.5_2: 112 files, 10M

And `brew info` tells me, that I build boost 1.58.0 from source - is that an issue?

    $ brew info boost
    boost: stable 1.58.0 (bottled), HEAD
    Collection of portable C++ source libraries
    http://www.boost.org
    /usr/local/Cellar/boost/1.54.0 (9865 files, 576M)
      Built from source with: --with-icu
    /usr/local/Cellar/boost/1.57.0 (10572 files, 418M)
      Built from source with: --with-icu4c
    /usr/local/Cellar/boost/1.58.0 (10718 files, 455M) *
      Built from source with: --c++11 --with-icu4c
    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boost.rb

Is there anything I can do to fix it? Or should I just wait for the postgis 2.2.0 update? https://github.com/Homebrew/homebrew/pull/44728

(when it comes to homebrew and compiling I consider myself only being an enduser with almost no bug fixing skills...)

**Comment by bgentry** [comment]
I ran into similar issues on OS X El Capitan today after running a `brew update && brew upgrade`:

```
/usr/local/opt/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec': PG::InternalError: ERROR:  could not load library "/usr/local/Cellar/postgresql/9.4.5/lib/postgis-2.1.so": dlopen(/usr/local/Cellar/postgresql/9.4.5/lib/postgis-2.1.so, 10): Symbol not found: __ZN5boost7archive21basic_binary_iarchiveINS0_15binary_iarchiveEE13load_overrideERNS0_15class_name_typeEi (ActiveRecord::StatementInvalid)
  Referenced from: /usr/local/lib/libSFCGAL.1.dylib
  Expected in: /usr/local/lib/libboost_serialization-mt.dylib
 in /usr/local/lib/libSFCGAL.1.dylib
```

In my case, I was able to get things working again by reinstalling postgis, and then reinstalling sfcgal from source:

```sh
$ brew reinstall sfcgal --build-from-source
```

**Comment by adrianmarino** [comment]
This has worked for me:
```
$ brew reinstall sfcgal --build-from-source
```

**Comment by lukehorvat** [comment]
C'mon guys, read the previous comments in the thread.
