### ISSUE TITLE
perforce binary sha-256 mismatch

### ISSUE THREAD

**Issue by methou** [Homebrew/homebrew#38604]
What I tried:
brew tap homebrew/binary
brew install perforce

What I got:
==> Installing perforce from homebrew/homebrew-binary
==> Downloading http://filehost.perforce.com/perforce/r14.2/bin.macosx105x86_64/
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 0d2ad21ecc03493a9b429907fb49209369ca09fd87340c03812dc1d1748dc562
Actual: fe01f8b613bb72d63e1a5bd278e5020d8bcd0c618f4f74ca2060cf9041581816
Archive: /Library/Caches/Homebrew/perforce-2014.2.978861
To retry an incomplete download, remove the file above.

What I expected:
get p4 binary as the one I got on perforce website:
$ openssl dgst -sha256 p4_latest
SHA256(p4)= 405d7777b4afe37b78e036b406668826c12ce551d1f638fefd55e96a89794db4

btw. latest version is 15.1 with sha-256:
openssl dgst -sha256 p4
SHA256(p4)= a8959d8431879ae87dfb7a3f02c5bb2b876ec6e883d695e93880e3e9cbcda0c7

**Comment by tdsmith** [comment]
This issue was moved to Homebrew/homebrew-binary#209
