### ISSUE TITLE
mhash

### ISSUE THREAD

**Issue by imlcl** [Homebrew/homebrew#38606]
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/mhash.rb#L5

`Download failed: https://downloads.sourceforge.net/project/mhash/mhash/0.9.9.9/mhash-0.9.9.9.tar.gz`
I think it is `http://downloads.sourceforge.net/project/mhash/mhash/0.9.9.9/mhash-0.9.9.9.tar.gz`

**Comment by xu-cheng** [comment]
It works for me.

```
$ brew fetch mhash
==> Downloading https://downloads.sourceforge.net/project/mhash/mhash/0.9.9.9/mhash-0.9.9.9.tar.gz
######################################################################## 100.0%
Downloaded to: /Library/Caches/Homebrew/mhash-0.9.9.9.tar.gz
SHA1: c898de5ea60d9e0873a1b73caa031bb1b5797c03
SHA256: 3dcad09a63b6f1f634e64168dd398e9feb9925560f9b671ce52283a79604d13e
```

**Comment by DomT4** [comment]
Yup. Working here too.

**Comment by jacknagel** [comment]
Assuming a temporary network issue.

**Comment by imlcl** [comment]
Maybe the company network issue : )
