### ISSUE TITLE
plplot/5.10.0 can't locate nonexistent glib/2.42.1 and cairo/1.14.0

### ISSUE THREAD

**Issue by raw915** [Homebrew/homebrew#38613]
I used brew to install the latest version of plplot/5.10.0 and tried to compile one of the examples. I got the following errors:

gcc `pkg-config --cflags --libs plplotd` test_PLplot.c -o PLplot_fig
ld: warning: directory not found for option '-L/usr/local/Cellar/glib/2.42.1/lib'
ld: warning: directory not found for option '-L/usr/local/Cellar/cairo/1.14.0/lib'
ld: library not found for -lgobject-2.0
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I verified that glib/2.42.1 and cairo/1.14.0 are not installed on my computer. What I have installed are:
ls /usr/local/Cellar/glib
2.36.3		2.38.2		2.40.0_1	2.42.2		2.44.0 

ls /usr/local/Cellar/cairo
1.12.14		1.12.16		1.12.16_1	1.14.2

Why is PLplot looking for nonexistent glib/2.42.1 and cairo/1.14.0, and how do I fix this problem?

I am using OS X Yosemite Version 10.10.2 on a MacBook Pro (15-inch, Mid 2012)

I have updated brew and upgraded everything. I have uninstalled PLplot and reinstalled it. Nothing made a difference.

I would install the requested older versions of glib and cairo, but it seems this is no longer an option in brew. https://github.com/Homebrew/homebrew/issues/38414

For more information I am using OS X 10.10.3 and Xcode Version 6.3 (6D570), which are up to date. I did brew update and brew doctor. Before doing this I had also done brew upgrade, which upgraded everything brew-related on my computer. Then I did a brew uninstall plplot and brew install plplot. After installing plplot I entered brew gist-logs plplot and received Error: No logs. 

Then I entered HOMEBREW_MAKE_JOBS=1 brew install -v plplot 2>&1 and obtained:

Downloading https://homebrew.bintray.com/bottles/plplot-5.10.0.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/plplot-5.10.0.yosemite.bottle.tar.gz
==> Verifying plplot-5.10.0.yosemite.bottle.tar.gz checksum
==> Pouring plplot-5.10.0.yosemite.bottle.tar.gz
tar xf /Library/Caches/Homebrew/plplot-5.10.0.yosemite.bottle.tar.gz
==> Finishing up
ln -s ../Cellar/plplot/5.10.0/bin/plserver plserver
ln -s ../Cellar/plplot/5.10.0/bin/pltcl pltcl
ln -s ../Cellar/plplot/5.10.0/bin/pltek pltek
ln -s ../Cellar/plplot/5.10.0/include/plplot plplot
ln -s ../../Cellar/plplot/5.10.0/share/doc/plplot plplot
ln -s ../../../Cellar/plplot/5.10.0/share/man/man1/plserver.1 plserver.1
ln -s ../../../Cellar/plplot/5.10.0/share/man/man1/pltcl.1 pltcl.1
ln -s ../../../Cellar/plplot/5.10.0/share/man/man1/pltek.1 pltek.1
ln -s ../Cellar/plplot/5.10.0/share/plplot5.10.0 plplot5.10.0
ln -s ../Cellar/plplot/5.10.0/lib/libcsirocsa.0.0.1.dylib libcsirocsa.0.0.1.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libcsirocsa.0.dylib libcsirocsa.0.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libcsirocsa.dylib libcsirocsa.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libplplotcxxd.11.0.0.dylib libplplotcxxd.11.0.0.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libplplotcxxd.11.dylib libplplotcxxd.11.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libplplotcxxd.dylib libplplotcxxd.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libplplotd.12.0.1.dylib libplplotd.12.0.1.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libplplotd.12.dylib libplplotd.12.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libplplotd.dylib libplplotd.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libplplottcltk_Maind.0.0.0.dylib libplplottcltk_Maind.0.0.0.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libplplottcltk_Maind.0.dylib libplplottcltk_Maind.0.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libplplottcltk_Maind.dylib libplplottcltk_Maind.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libplplottcltkd.11.1.0.dylib libplplottcltkd.11.1.0.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libplplottcltkd.11.dylib libplplottcltkd.11.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libplplottcltkd.dylib libplplottcltkd.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libqsastime.0.0.1.dylib libqsastime.0.0.1.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libqsastime.0.dylib libqsastime.0.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libqsastime.dylib libqsastime.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libtclmatrixd.9.2.0.dylib libtclmatrixd.9.2.0.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libtclmatrixd.9.dylib libtclmatrixd.9.dylib
ln -s ../Cellar/plplot/5.10.0/lib/libtclmatrixd.dylib libtclmatrixd.dylib
ln -s ../../Cellar/plplot/5.10.0/lib/pkgconfig/plplotd-c++.pc plplotd-c++.pc
ln -s ../../Cellar/plplot/5.10.0/lib/pkgconfig/plplotd-tcl.pc plplotd-tcl.pc
ln -s ../../Cellar/plplot/5.10.0/lib/pkgconfig/plplotd-tcl_Main.pc plplotd-tcl_Main.pc
ln -s ../../Cellar/plplot/5.10.0/lib/pkgconfig/plplotd.pc plplotd.pc
==> Summary
🍺  /usr/local/Cellar/plplot/5.10.0: 326 files, 4.1M

There is no log subdirectory for installing plplot: ls ~/Library/Logs/Homebrew/plplot
ls: /Users/raw915/Library/Logs/Homebrew/plplot: No such file or directory

Output from brew config:

brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: e31bf9cfb76dfcf1774ac2ccd29c07b7fb0302b4
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit ivybridge
OS X: 10.10.3-x86_64
Xcode: 6.3
CLT: N/A
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.8.0_40

Output from brew doctor:

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:

  /Users/raw915/anaconda/bin/curl-config
  /Users/raw915/anaconda/bin/freetype-config
  /Users/raw915/anaconda/bin/libdynd-config
  /Users/raw915/anaconda/bin/libpng-config
  /Users/raw915/anaconda/bin/libpng15-config
  /Users/raw915/anaconda/bin/python3-config
  /Users/raw915/anaconda/bin/python3.4-config
  /Users/raw915/anaconda/bin/python3.4m-config
  /Users/raw915/anaconda/bin/xml2-config
  /Users/raw915/anaconda/bin/xslt-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libcdt.5.dylib
    /usr/local/lib/libcgraph.6.dylib
    /usr/local/lib/libdoublefann.2.2.0.dylib
    /usr/local/lib/libfann.2.2.0.dylib
    /usr/local/lib/libfixedfann.2.2.0.dylib
    /usr/local/lib/libfloatfann.2.2.0.dylib
    /usr/local/lib/libgvc.6.dylib
    /usr/local/lib/libgvpr.2.dylib
    /usr/local/lib/liblab_gamut.1.dylib
    /usr/local/lib/libmca_common_sm.3.dylib
    /usr/local/lib/libmpi.1.dylib
    /usr/local/lib/libmpi_cxx.1.dylib
    /usr/local/lib/libmpi_f77.1.dylib
    /usr/local/lib/libompitrace.0.dylib
    /usr/local/lib/libopen-pal.4.dylib
    /usr/local/lib/libopen-rte.4.dylib
    /usr/local/lib/libopen-trace-format.1.dylib
    /usr/local/lib/libotfaux.0.dylib
    /usr/local/lib/libpathplan.4.dylib
    /usr/local/lib/libvt-hyb.0.dylib
    /usr/local/lib/libvt-mpi-unify.0.dylib
    /usr/local/lib/libvt-mpi.0.dylib
    /usr/local/lib/libvt-mt.0.dylib
    /usr/local/lib/libvt.0.dylib
    /usr/local/lib/libxdot.4.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/compat_time.h
    /usr/local/include/doublefann.h
    /usr/local/include/fann.h
    /usr/local/include/fann_activation.h
    /usr/local/include/fann_cascade.h
    /usr/local/include/fann_cpp.h
    /usr/local/include/fann_data.h
    /usr/local/include/fann_error.h
    /usr/local/include/fann_internal.h
    /usr/local/include/fann_io.h
    /usr/local/include/fann_train.h
    /usr/local/include/fixedfann.h
    /usr/local/include/floatfann.h
    /usr/local/include/GL/freeglut.h
    /usr/local/include/GL/freeglut_ext.h
    /usr/local/include/GL/freeglut_std.h
    /usr/local/include/GL/glut.h
    /usr/local/include/libavcodec/opt.h
    /usr/local/include/libavcore/audioconvert.h
    /usr/local/include/libavcore/avcore.h
    /usr/local/include/libavcore/imgutils.h
    /usr/local/include/libavcore/parseutils.h
    /usr/local/include/libavcore/samplefmt.h
    /usr/local/include/libavutil/sha1.h
    /usr/local/include/mpi-ext.h
    /usr/local/include/mpi.h
    /usr/local/include/mpi_portable_platform.h
    /usr/local/include/mpif-common.h
    /usr/local/include/mpif-config.h
    /usr/local/include/mpif-mpi-io.h
    /usr/local/include/mpif.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libmca_common_sm.la
    /usr/local/lib/libmpi.la
    /usr/local/lib/libmpi_cxx.la
    /usr/local/lib/libmpi_f77.la
    /usr/local/lib/libmpi_f90.la
    /usr/local/lib/libompitrace.la
    /usr/local/lib/libopen-pal.la
    /usr/local/lib/libopen-rte.la
    /usr/local/lib/libopen-trace-format.la
    /usr/local/lib/libotfaux.la
    /usr/local/lib/libvt-hyb.la
    /usr/local/lib/libvt-mpi-unify.la
    /usr/local/lib/libvt-mpi.la
    /usr/local/lib/libvt-mt.la
    /usr/local/lib/libvt.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/fann.pc
    /usr/local/lib/pkgconfig/libcdt.pc
    /usr/local/lib/pkgconfig/libcgraph.pc
    /usr/local/lib/pkgconfig/libgvc.pc
    /usr/local/lib/pkgconfig/libgvpr.pc
    /usr/local/lib/pkgconfig/liblab_gamut.pc
    /usr/local/lib/pkgconfig/libpathplan.pc
    /usr/local/lib/pkgconfig/libxdot.pc
    /usr/local/lib/pkgconfig/ompi-c.pc
    /usr/local/lib/pkgconfig/ompi-cxx.pc
    /usr/local/lib/pkgconfig/ompi-f77.pc
    /usr/local/lib/pkgconfig/ompi-f90.pc
    /usr/local/lib/pkgconfig/ompi.pc
    /usr/local/lib/pkgconfig/orte.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libmpi_f90.a
    /usr/local/lib/libopen-trace-format.a
    /usr/local/lib/libotfaux.a
    /usr/local/lib/libvt-hyb.a
    /usr/local/lib/libvt-mpi-unify.a
    /usr/local/lib/libvt-mpi.a
    /usr/local/lib/libvt-mt.a
    /usr/local/lib/libvt.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:

    fann
    gfortran
    gnupg2
    gpg-agent
    open-mpi

**Comment by jacknagel** [comment]
Please follow https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

**Comment by tdsmith** [comment]
`brew reinstall plplot --build-from-source` should work around this. If you can contribute a `test do

**Comment by tdsmith** [comment]
`brew reinstall plplot --build-from-source` should work around this; it looks like plplot needs to be rebottled. If you can contribute a `test do` block that tries to compile an example script, we'll be able to catch this in the future.
