### ISSUE TITLE
sigrok fail to install on 10.9.5 

### ISSUE THREAD

**Issue by Guavazo** [Homebrew/homebrew#38630]
Hello I ran into this issue follow sigrok  OS X install guide running the command 
$ brew install --HEAD --with-libserialport sigrok-cli
and can not proceed, any idea what I'm doing wrong? 

https://gist.github.com/anonymous/e7726f2fa9245d447b24

**Comment by jacknagel** [comment]
This should be reported at https://github.com/Homebrew/homebrew-science.

I did look at it, though; the stable version builds while the head version does not. Typically this means it needs to be reported upstream.
