### ISSUE TITLE
yuicompressor.rb: please add -Xss5m command-line option

### ISSUE THREAD

**Issue by ujay68** [Homebrew/homebrew#38654]
Many people report a StackOverflowError when running yuicompressor with Java's default memory settings. In the yuicompressor script generated by yuicompressor.rb, please add ```-Xss5m``` to the java command line:

```exec java -Xss5m -jar /usr/local/Cellar/yuicompressor/2.4.8/libexec/yuicompressor-2.4.8.jar "$@"```

**Comment by mikemcquaid** [comment]
What does that setting do?

**Comment by ujay68** [comment]
It increases the JVM's stack size to 5 MB, see https://docs.oracle.com/javase/8/docs/technotes/tools/unix/java.html

**Comment by mikemcquaid** [comment]
Do you work on the `yuicompressor` customer? Which people have reported this and where?

**Comment by ujay68** [comment]
No I don't work for the project, I was just one of those who experienced that problem. It doesn't seem to be related to some exotic CSS usage. For me, it happened with a small and completely standard CSS of 5.6 KBytes.

As for who is having that problem: https://www.google.de/search?q=yuicompressor%20stackoverflowerror

**Comment by DomT4** [comment]
Will welcome a PR to discuss here.

**Comment by ujay68** [comment]
I'd like to submit a PR, but I'm sorry I don't program in Ruby and I don't know about the inner workings of brew and brew formulas.
