### ISSUE TITLE
 c=gzgetc(image->blob->file);

### ISSUE THREAD

**Issue by OhCoder** [Homebrew/homebrew#38659]
![screen shot 2015-04-15 at 9 10 56 am](https://cloud.githubusercontent.com/assets/890676/7150588/772e2346-e34f-11e4-8d08-d15c37e7a113.png)
Hey, I got an issue when I install imagemagick-ruby186
My system is ubuntu 14.04 and I use linux-brew tool to install. 
I don't know why, can some body help me?

**Comment by mistydemeo** [comment]
Please report this to [linuxbrew](https://github.com/Homebrew/linuxbrew), and include the troubleshooting info requested in the link in your output when you do. Thanks!
