### ISSUE TITLE
Sandbox & Autojump

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew#38652]
Seems to be a sandbox thing. I've never hit it before. Reproduces across multiple formulae with the same method.

Essentially, with ` autojump ` installed, start to build something, interrupt the build, go into the shell, do ` cd [hit-your-tab-key-here] ` => ` cd [the-first-two-letters-of-a-folder-the-first-tab-revealed] ` => ` hit your tab key to let it autocomplete the folder name and hit enter `

My config is zsh, with oh-my-zsh and autojump, but it happens with autojump and system ` sh ` as well, at least.

Not particularly easy to describe, so:

![2015-04-14 22_36_06](https://cloud.githubusercontent.com/assets/6998367/7147945/ab608298-e2f6-11e4-826a-60607476be8f.gif)

CC: @xu-cheng

**Comment by xu-cheng** [comment]
This is an expected behavior. When you enable sandbox, all subporcess will be inside sandbox. And that includes the interactive shell. Although, it's s bit annoying, I do think it's trivial to turn off the sandbox when you need to debug.

**Comment by DomT4** [comment]
Trivial in which way? To escape that, I'm having to cancel the build, open up my ` zshrc ` and comment out the ` HOMEBREW_SANDBOX ` line, and then reload my shell, and then start the build again. Am I missing something wildly obvious?

**Comment by xu-cheng** [comment]
Oh, I think we need to add a new argument to turn off it. 

In the meaning time, you can just run `unset HOMEBREW_SANDBOX`.

**Comment by DomT4** [comment]
An easier way to disable it, particularly in the middle of debugging, would be great :+1:. ` unset ` didn't pop into my mind, I tried exporting a blank variable to cancel out the enabled variable, but no dice :smile_cat:

**Comment by jacknagel** [comment]
I think `--interactive` should disable the sandbox automatically. I think an argument could be made either way for `--debug`.

You can also just do

```
$ HOMEBREW_SANDBOX= brew install ...
```

to unset the variable for just that one command.

**Comment by DomT4** [comment]
` $ HOMEBREW_SANDBOX= brew install ... `

Doesn't seem to work for me.

```
HOMEBREW_SANDBOX= brew install --verbose --debug postgis20

/usr/bin/sandbox-exec -f /tmp/homebrew20150415-54877-qx8qzv.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/build.rb /usr/local/Library/Taps/homebrew/homebrew-versions/postgis20.rb --verbose --debug

Errno::EPERM: Operation not permitted - (stage/usr/local/Cellar/postgresql92/9.2.8_1/lib/postgis-2.0.so, /usr/local/Cellar/postgresql92/9.2.8_1/lib/postgis-2.0.so)
```

**Comment by DomT4** [comment]
Closing here since #38792 is on the table as a fix/permanent workaround.
