### ISSUE TITLE
request for package: libepoxy - a library for handling OpenGL function pointer management

### ISSUE THREAD

**Issue by andrewrk** [Homebrew/homebrew#38650]
brew has a glew package, and libepoxy is a recognized better alternative.

https://github.com/anholt/libepoxy

**Comment by mikemcquaid** [comment]
We don't really do package requests. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
