### ISSUE TITLE
gst-validate has "python2" in shebangs

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew#38669]
There's no /usr/bin/python2; this only worked because Homebrew python was installed (unnecessarily) as a downstream dependency. Ref http://bot.brew.sh/job/Homebrew%20Pull%20Requests/24252/version=mavericks/testReport/junit/brew-test-bot/mavericks/test_gst_validate/

**Comment by chul0812** [comment]
I think shebang should be changed like `#!/usr/bin/env python` and gst-validate also add python dependency in configure. Is it make sense?

**Comment by dunn** [comment]
This was fixed in b1417c3fb9c3e23687f6de4181596d35e891e385.
