### ISSUE TITLE
look only for requested --with-foo when deciding on (un)fulfilled dependencies

### ISSUE THREAD

**Issue by davydden** [Homebrew/homebrew#38665]
Here is a situation:
I have 
```
$ brew info netcdf
netcdf: stable 4.3.3.1 (bottled)
http://www.unidata.ucar.edu/software/netcdf
/usr/local/Cellar/netcdf/4.3.2_1 (72 files, 6.6M) *
  Built from source with: --with-cxx-compat, --with-fortran
```
and I try to install another formula which has 
```
depends_on "netcdf"       => ["with-fortran", :recommended]
```
This in turn leads to re-installation of `netcdf` and, what's worse, possibly breaking some other formulae which previously installed it with the above mentioned keys. 

It would be good if the decision of fulfilled/not-fulfilled dependencies could take those scenarios into account. That would imply an agreement that every `--with-foo` only extends a particular library. So if we need `--with-abc`, but the library is compiled `--with-abc --with-foo`, then it shall be ok and no rebuild shall be invoked.

If default application of that logic is not desired, perhaps an additional key to `brew install` to enforce it is another option.

**Comment by tdsmith** [comment]
> netcdf: stable __4.3.3.1__ (bottled)
> /usr/local/Cellar/netcdf/__4.3.2\_1__ (72 files, 6.6M) *

It's rebuilding because a newer version is available and only the newest version satisfies a dependency. I expect that depends_on options do always extend the options previously used to build the formula; please let me know if you're sure I'm wrong.

**Comment by davydden** [comment]
you are absolutely right! my bad, sorry.

Great to know that this feature is already in homebrew ;-)

**Comment by tdsmith** [comment]
No problem!
