### ISSUE TITLE
qpdf fails to build on 10.10.3

### ISSUE THREAD

**Issue by ozagordi** [Homebrew/homebrew#38670]
Hi!
I cannot build pdf, the error being

    ==> ./configure --prefix=/usr/local/Cellar/qpdf/5.1.2
    ==> make
    #include <__debug>
             ^
    1 error generated.
    /bin/bash: libqpdf/build/FileInputSource.tdep: No such file or directory
    make: *** [libqpdf/build/FileInputSource.lo] Error 1

Full log is [here](https://gist.github.com/1a8d99b6a062468d588f)

Thanks.

**Comment by tdsmith** [comment]
We're tracking this in #38514; the CLT headers are broken.

**Comment by ozagordi** [comment]
Ok, thanks. With a simple search for "pdf" I didn't realise they were related.

**Comment by tdsmith** [comment]
No worries!
