### ISSUE TITLE
Emacs formula does not create the .app version

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [Homebrew/homebrew#38695]
Here is [the gist](https://gist.github.com/84017b880640590f7762) from the installation.

I am having this problem with both:

* `brew install emacs --with_cocoa --with-gnutls --with-rsvg --with-imagemagick`
and
* `brew install emacs --HEAD --use-git-head --with_cocoa --with-gnutls --with-rsvg --with-imagemagick`

Also, whenever notice that if I run:
```
> brew linkapps emacs
Finished linking. Find the links under /Applications.
```
but:
```
$ ls  /Applications/Emacs.app/
ls: /Applications/Emacs.app/: No such file or directory
```

Here are the contents of the installation path:
```
$ l /usr/local/Cellar/emacs/24.5
total 976
-rw-r--r--  1 avazquez  wheel   435K Apr  5 07:04 ChangeLog
-rw-r--r--  1 avazquez  wheel    34K Apr  8 16:39 COPYING
-rw-r--r--  1 avazquez  wheel   5.7K Apr  2 03:23 README
-rw-r--r--  1 avazquez  admin   416B Apr 15 20:39 INSTALL_RECEIPT.json
-rw-r--r--  1 avazquez  admin   412B Apr 15 20:39 homebrew.mxcl.emacs.plist
drwxr-xr-x  8 avazquez  admin   272B Apr 15 20:39 bin/
drwxr-xr-x  7 avazquez  admin   238B Apr 15 20:39 share/
drwxr-xr-x  3 avazquez  admin   102B Apr 15 20:39 libexec/
drwxr-xr-x  3 avazquez  admin   102B Apr 15 20:39 var/
```

**Comment by DomT4** [comment]
As far as I can see, the incorrect ` brew ` argument is causing you to not get the Application built. The message you see is the standard message, when something is actually available to link you see this message:

```
brew linkapps fontforge
Linking /usr/local/opt/fontforge/FontForge.app
Finished linking. Find the links under /Applications.
```

Try this instead: ` brew install emacs --with-cocoa --with-gnutls --with-rsvg --with-imagemagick `

**Comment by amelio-vazquez-reina** [comment]
Thank you @DomT4 . Good to know. In case anyone wonders about the difference:

I used: `--with_cocoa `, but should have used `--with-cocoa` (underscore should have been a dash).
