### ISSUE TITLE
`veclibfort` formula is missing

### ISSUE THREAD

**Issue by amirmasoudabdol** [Homebrew/homebrew#38705]
Upgrading `armadillo` produces this error:

```
❯ brew upgrade armadillo 
==> Upgrading 1 outdated package, with result:
armadillo 4.650.4
Error: No available formula for veclibfort (dependency of armadillo)
```

**Comment by xu-cheng** [comment]
Please run `brew update`. If not work, follow the [troubleshooting](https://git.io/brew-troubleshooting) and provide the necessary diagnostic information. Thanks.

**Comment by DomT4** [comment]
Wrong repo. You want [Homebrew/science](https://github.com/Homebrew/homebrew-science).

**Comment by mikemcquaid** [comment]
This issue was moved to Homebrew/homebrew-science#2112
