### ISSUE TITLE
torsocks has no checksum

### ISSUE THREAD

**Issue by Midar** [Homebrew/homebrew#38719]
The current torsocks formula only specifies a tag, but no hash or anything else that could be checksummed. How about getting that tag as an archive from GitHub and checking the hash of that?

**Comment by mikemcquaid** [comment]
We should add a `:revision` to it. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
