### ISSUE TITLE
running brew throws ArgumentError

### ISSUE THREAD

**Issue by philippnagel** [Homebrew/homebrew#38710]
I just wanted to run brew update and instead I got this error:

```
/usr/local/Library/Homebrew/global.rb:109:in `split': invalid byte sequence in UTF-8 (ArgumentError)
	from /usr/local/Library/Homebrew/global.rb:109:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'
```

I had the same error a week ago and basically reinstalled ruby and it worked again. Changing nothing I just got this again. Any hints?

**Comment by xu-cheng** [comment]
What's you `$PATH` variable? You can get it by running `echo $PATH`.

**Comment by philippnagel** [comment]
It throws

```
/usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin /usr/local/MacGPG2/bin /usr/texbin  /usr/local/bin/fish /usr/local/git/bin /usr/local/go/bin /opt/local/bin/node /opt/local/bin/npm
```

**Comment by jacknagel** [comment]
>I had the same error a week ago and basically reinstalled ruby and it worked again.

Can you elaborate on this? Did you modify the system ruby?

**Comment by philippnagel** [comment]
As I am not a Ruby dev I hope not. I also deinstalled Macports. Everything runs fine now. I will try to recreate what happened with a backup in a VM.

**Comment by jacknagel** [comment]
Closing for now, let us know if you can reproduce it.
