### ISSUE TITLE
missing plist for activemq

### ISSUE THREAD

**Issue by vegaed** [Homebrew/homebrew#38713]
A plist file is not generated for activemq. Would be very useful to have one.

**Comment by xu-cheng** [comment]
Could you try and open a pull request? This [document](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should be helpful. Thanks!

**Comment by southwolf** [comment]
I'm working on it. Should the broker port 61613 be changed to avoid possible conflicts with other MQ?

**Comment by vegaed** [comment]
Southwolf thanks for working on this. I would say leave it as default 61616. A user could just change it in the xml config file.

**Comment by xu-cheng** [comment]
Fixed by 69d918a6a3f4fd8eef30034908afe04a01f7ee46
