### ISSUE TITLE
wget doesn't work properly in shell script

### ISSUE THREAD

**Issue by hu6360567** [Homebrew/homebrew#38739]
```
wget https://class.coursera.org/algo2-003/lecture/subtitles?q=5_en&format=srt --output-document="Application: Sequence Alignment (9 min).srt"
```

I've installed wget vis homebrew.
Should always write output-document options before url?
 However, the command written upon works fine in terminal, but not rename file when I wrote it into a shell script file.

How this happened?

**Comment by jacknagel** [comment]
`&` is a shell metacharacter. You need to quote the URL:

```
wget "https://class.coursera.org/algo2-003/lecture/subtitles?q=5_en&format=srt" --output-document="Application: Sequence Alignment (9 min).srt"
```
