### ISSUE TITLE
gcc failed to build

### ISSUE THREAD

**Issue by mohithingorani** [Homebrew/homebrew#38731]
I was trying to install openCV today but it seems like GCC is unable to compile it:

Mohit:~ mohithingorani$ brew install opencv
==> Installing opencv from homebrew/homebrew-science
==> Installing dependencies for opencv: gcc, eigen, libpng, ilmbase, openexr, homebrew/python/numpy
==> Installing opencv dependency: gcc
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc-4.9.2.tar.bz2
==> ../configure --build=x86_64-apple-darwin14.1.0 --prefix=/usr/local/Cellar/gcc/4.9.2_1 --libdir=/usr/local/Cellar/gcc/4.9.2_1/lib/gcc/4.9 --enable-languages=c,c++,objc,obj-c++,fortr
==> make bootstrap
configure: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details.
make[2]: *** [configure-stage1-target-libgcc] Error 1
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
GCC fails to build with Xcode 6.3 (https://github.com/Homebrew/homebrew/issues/38501)
Object files deleted during build of gcc needed by gdb (https://github.com/Homebrew/homebrew/issues/35734)
--cc=gcc-4.9 gets me in an infinite loop (https://github.com/Homebrew/homebrew/issues/33731)
gcc 4.9.2 fails to produce debugging information (https://github.com/Homebrew/homebrew/issues/34976)
MacOS.(gcc|clang|llvm)_version can return nil (https://github.com/Homebrew/homebrew/issues/18781)
Mohit:~ mohithingorani$ 

any work arounds/suggestions?

**Comment by DomT4** [comment]
> READ THIS: https://git.io/brew-troubleshooting

:wink:

**Comment by tdsmith** [comment]
This issue was moved to Homebrew/homebrew-science#2115

**Comment by tdsmith** [comment]
Unmoving the issue; upon closer reading this is a gcc issue, oops.

**Comment by themicmac** [comment]
Same problem here. There must be a better answer to this problem than "this is a gcc issue". Respectfully, what does that even mean? I tried to brew install gcc and I also received pretty much the exact same output as above. Updating xcode is out of the question for me, but surely there's a way to install these compilers without xcode. (like in linux). Here is my config:

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 09fdce7318b676eb9005d3001d00f524f8619582
Last commit: 23 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit penryn
OS X: 10.6.8-i386
Xcode: 4.2
CLT: N/A
GCC-4.0: build 5494
GCC-4.2: build 5666
LLVM-GCC: build 2336
Clang: 3.0 build 211
X11: 2.3.6 => /usr/X11
System Ruby: 1.8.7-p358
Perl: /Applications/MAMP/Library/bin/perl
Python: /Applications/MAMP/Library/bin/python => /Applications/MAMP/Library/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: 1.6.0_65

**Comment by tdsmith** [comment]
@themicmac Please open a new issue with the output of `brew gist-logs gcc` and a statement about what you were intending to do; thanks.

"It's a GCC issue" means "the problem was encountered while building gcc."

> but surely there's a way to install these compilers without xcode

Not with Homebrew.

**Comment by themicmac** [comment]
@tdsmith Got it. Will do. Thanks. Also, to anyone interested in this issue, there's a few links here which might be helpful regarding GCC:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61407 and https://github.com/Homebrew/homebrew/issues/29845

**Comment by jacknagel** [comment]
Closing due to no response.
