### ISSUE TITLE
Install wine error: libpng configure problem

### ISSUE THREAD

**Issue by Nuk9** [Homebrew/homebrew#38752]
Environment:
OSX Yosemite 10.10.3
XCode 6.3

Already run `brew update` and `brew upgrade` before I run `brew install wine`.

Error log:

    ==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libpng/1.6.17
    checking for memset... yes
    checking for pow... yes
    checking for zlibVersion in -lz... no
    checking for z_zlibVersion in -lz... no
    configure: error: zlib not installed
    couldn't understand kern.osversion `14.3.0'
    READ THIS: https://git.io/brew-troubleshooting

**Comment by DomT4** [comment]
Works okay here. It's odd ` zlib ` isn't detected for you - It's shipped by OS X so everyone should have it.

` checking for zlibVersion in -lz... yes `

> READ THIS: https://git.io/brew-troubleshooting

` brew gist-logs libpng ` will help the maintainers here.

**Comment by Nuk9** [comment]
Here is the output of `brew gist-logs libpng`

    couldn't understand kern.osversion `14.3.0'

**Comment by DomT4** [comment]
That can't be the only thing. ` gist-logs ` shows a whole ton of system and compile information. There'd be more than that, surely. The most likely culprit here from prior issues is Xcode/CLT version mismatch.

**Comment by bfontaine** [comment]
I have the same issue, [here are the logs](https://gist.github.com/689f8a2ad63a6f9602ba). `brew doctor` only tells me I should unlink `openssl`, and the commands posted by @Nuk9 above didn’t solve the issue.

**Comment by Nuk9** [comment]
I actually looked deeper into my problem.
The root cause is: brew use some .a file which not belongs to the brew system. (installed by other commands like `make install`). I deleted all the non-brew files given by brew doctor after which it works.
