### ISSUE TITLE
Installing executables to sbin is confusing if sbin isn't in PATH

### ISSUE THREAD

**Issue by wmbutler** [Homebrew/homebrew#38767]
I know this has something to do with `sbin` and I've seen workarounds, but I think it would make a lot of sense for this script to be written properly so it works the first time. Is anybody interested in making the fix?

`brew install mtr`

**Comment by tdsmith** [comment]
The formula is written properly but we can nag about configuration.

**Comment by tdsmith** [comment]
Closing as duplicate of #37040.
