### ISSUE TITLE
gnuplot 5.0 fails (missing LUA dependency?)

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew#38772]
https://gist.github.com/8df50a6ba075cbadc286

```
checking for LUA... no
checking for LUA... no
configure: WARNING: Could not find support for lua using pkg-config.
```

```
isystem/bio/linuxbrew/include -I/bio/linuxbrew/opt/readline/include -I/bio/linuxbrew/Cellar/gd/2.1.1/include  -Os -w -pipe -march=core2 -c -o term.o term.c
In file included from term.h:414:0,
                 from term.c:1185:
../term/lua.trm:113:17: fatal error: lua.h: No such file or directory
 #include <lua.h>
```

Also possibly missing QT5 dependency?

**Comment by DomT4** [comment]
` gnuplot ` has some specialised language on the Lua dep. Given you're using Linuxbrew though, you probably need to report this to them rather than Homebrew/homebrew - The solutions best for Linux and best for OS X can tend to differ.

**Comment by tseemann** [comment]
@DomT4 

On Linux, the problem is solved with "brew install lua" first, then it builds from source without problem. 

The formula has some funky sub-classing to handle the LUA dependency:
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gnuplot.rb

I assume this isn't working properly in LinuxBrew. I've filed it: https://github.com/Homebrew/linuxbrew/issues/354

**Comment by tseemann** [comment]
The problem is that if the Linux system LUA is installed it doesn't work.
