### ISSUE TITLE
Cannot get gcc42 to upgrade to a higher version of gcc49 on Mac Os 10.6.8

### ISSUE THREAD

**Issue by themicmac** [Homebrew/homebrew#38782]
Here is the gist log: https://gist.github.com/anonymous/9afb78ce93d8656f719b

I just can't seem to be able to get gcc to upgrade via homebrew. Was going to look for an alternative route outside of homebrew but decided to post this when I found following link: 

Situation very similar to that in https://github.com/Homebrew/homebrew-versions/issues/382.

I get the same errors and pretty much same output:
```
ismaelrivera@Ismael-Riveras-Mac-Pro-2:~$ brew install gcc49
==> Installing gcc49 from homebrew/homebrew-versions
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc49-4.9.2.tar.bz2
==> ../configure --build=x86_64-apple-darwin10.8.0 --prefix=/usr/local/Cellar/gcc49/4.9.2_1 --libdir=/u
==> make bootstrap
mkdir common
mkdir common/.deps
config.status: executing default commands
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2
```

**Comment by mistydemeo** [comment]
Looks like the problem is:

```
checking how to run the C++ preprocessor... In file included from ../../../libiberty/../include/libiberty.h:48,
                 from ../../../libiberty/alloca.c:49:
/usr/include/stdarg.h:4:25: error: stdarg.h: No such file or directory
make[3]: *** [alloca.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [cp-demangle.o] Error 1
make[3]: *** [cplus-dem.o] Error 1
```

I see that your listed Xcode version is 4.2. How did you install Xcode?

**Comment by themicmac** [comment]
Not the conventional way. It was a huge headache in what began to make me very dissatisfied with Apple up to this day still. When I bought Snow Leopard(2 years ago, more or less), my Dev tools would not install. From there on it was like 5 to 6 months trying to get them to send me an archive or a download link but I was out of the country on business and apple store apparently has strict rules about accounts downloading while on servers located outside US. I did pay for my copy of Snow Leopard but Apple still wouldn't allow me to re-download what I had already bought. Because I was on a deadline, I downloaded a copy from a url that had all these archived versions of Xtools recompiled from source and installed that.
If you're asking me how. I honestly cannot remember. It was a hacky situation but I was able to install it and right up until now never had a single problem with it.  

Why do you ask? What does that output mean? Sorry, my UNIX is a bit rusty. I don't really understand.
Is this solvable?

**Comment by mistydemeo** [comment]
It looks like something's wrong with the OS's headers, which come from Xcode. Can you try reinstalling Xcode using an official package?

**Comment by themicmac** [comment]
No. I know for a fact that Apple won't allow me to do this without upgrading my OS first. I think Lion is for free now, but I really don't want to do that since this is essentially a dying computer(and my last Mac). Too much hassle at this point. Thank you @mistydemeo so much for the info and the diagnostic. It's been really helpful. I think I'm just going to use Vagrant. Thank you again, take care.

**Comment by mistydemeo** [comment]
For reference, you can get all versions of Xcode (going back to 1.0 for OS X 10.3!) at http://developer.apple.com/downloads. Xcode 3.2.6, the final regular release for OS X 10.6.8, is still available - you should be able to install it from there.

Good luck whatever route you take!

**Comment by themicmac** [comment]
Hi there, on second thought, I changed my mind. I want install Xcode 3.2.6. Questions: having already installed Xcode 4.2, How do I uninstall it? Should I even try to uninstall it? Do I just install 3.2.6 on top without uninstalling the one I have already?

**Comment by mistydemeo** [comment]
Installing Xcode 3.2.6 on top should be safe; however, there is most likely an uninstall script in `/Developer/Library`, which you can run by doing:

```
sudo /Developer/Library/uninstall-devtools --mode=all
```
