### ISSUE TITLE
libvpx failed to build on 10.7

### ISSUE THREAD

**Issue by mcnesium** [Homebrew/homebrew#38790]
==> Upgrading 1 outdated package, with result:
    libvpx 1.4.0
    ==> Upgrading libvpx
    ==> Downloading https://github.com/webmproject/libvpx/archive/v1.4.0.tar.gz
    ######################################################################## 100,0%
    ==> ../configure --prefix=/usr/local/Cellar/libvpx/1.4.0 --enable-pic --disable-unit-tests --disable-examples
    ==> make install
                   ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 errors generated.
    make[1]: *** [vp9/common/x86/vp9_subpixel_8t_intrin_avx2.c.o] Error 1
    make[1]: *** Waiting for unfinished jobs....
    make: *** [.DEFAULT] Error 2

https://gist.github.com/094107b339fca67b9f9b

**Comment by jacknagel** [comment]
This patch fixes the build: https://hg.mozilla.org/mozilla-central/raw-file/5515fa5ba20d/media/libvpx/apple-clang.patch

but it's not present in upstream libvpx.

**Comment by lallen** [comment]
Is it possible to manually apply the patch. Could someone please explain how I do that?

**Comment by mgk** [comment]
Had same issue on 10.7.5

Patch worked for me. Thanks @jacknagel PR on the way.

@lallen if PR is accepted you can just `brew update` and reinstall. If it is not or you want it before then you should be able to `brew edit libvpx`, replace the contents with the [updated formula](https://github.com/mgk/homebrew/blob/3da6b78cc6b743f3ed260b257330f0a9646394f4/Library/Formula/libvpx.rb), save and reinstall.
