### ISSUE TITLE
Error: Failed to download resource "android-sdk"

### ISSUE THREAD

**Issue by cnyyk** [Homebrew/homebrew#38847]
➜  ~  brew upgrade
==> Upgrading 1 outdated package, with result:
android-sdk 24.1.2
==> Upgrading android-sdk
==> Downloading https://dl.google.com/android/android-sdk_r24.1.2-macosx.zip

curl: (7) Failed to connect to dl.google.com port 443: Operation timed out
Error: Failed to download resource "android-sdk"
Download failed: https://dl.google.com/android/android-sdk_r24.1.2-macosx.zip

➜  ~  ping dl.google.com
PING dl.google.com (203.208.46.142): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
^C

It's really difficult to get access to dl.google.com in China mainland.
So, is there a config file to change the android SDK download url?
That I can download the same SDK archive file from alternative url.

**Comment by mikemcquaid** [comment]
If you can find a mirror URL we can add it as a `mirror` line.

**Comment by cnyyk** [comment]
Thanks for your reply.
So sad, there's no full synced mirror to dl.google.com/android repository.
But I manually get the android-sdk_r24.1.2-macosx.zip file via download tool.
Could I use the local zip file as a mirror for brew install?
If it does, what should I do?

**Comment by mikemcquaid** [comment]
@cnyyk I think there's a way but I'm not 100% sure how.

**Comment by DomT4** [comment]
If you can grab the download from somewhere, you can cache it locally with ` mv /path/to/android-sdk_r24.1.2-macosx.zip /Library/Caches/Homebrew/android-sdk-24.1.2.zip ` and then do ` brew install android-sdk ` that should work.

**Comment by jacknagel** [comment]
You can do `cp <path to downloaded file> $(brew --cache android-sdk)`, that way you don't have to figure out exactly how to format the filename so that Homebrew will pick it up.

**Comment by cnyyk** [comment]
Thank you all.
Finally, I figured this out with @jacknagel 's guiding.
