### ISSUE TITLE
error: option --no-user-cfg not recognized

### ISSUE THREAD

**Issue by Rochvellon** [Homebrew/homebrew#38852]
Hi,

I wanna install cmake but I get "error: option --no-user-cfg not recognized"

Gist:
https://gist.github.com/anonymous/873f3977037298f4d0fb

Any ideas?

**Comment by DomT4** [comment]
Needs to be filed at [Homebrew/linuxbrew](https://github.com/Homebrew/linuxbrew) :).

**Comment by xu-cheng** [comment]
This issue was moved to Homebrew/linuxbrew#358
