### ISSUE TITLE
homebrew.mxcl.mongodb.plist needs to be adjusted to prevent 

### ISSUE THREAD

**Issue by bmike** [Homebrew/homebrew#38869]
Using the current homebrew.mxcl.mongodb.plist yields a warning each time you run mongo:

    ** WARNING: soft rlimits too low. Number of files is 256, should be at least 1000

The current plist file sets the limits too high for OS X 10.10

I've changed the soft limit to 1000 and the hard limit to 1023 so that both OS X and mongod are happy

**Comment by bmike** [comment]
Hopefully this PR is sufficient to move this change along.

I've tested this on 10.10.3 and don't see any problems - and it removes the warning listed above

https://github.com/Homebrew/homebrew/pull/38871

**Comment by adamv** [comment]
Closing as a duplicate of #38871; typically we don't need both an issue and a pull request.

**Comment by bmike** [comment]
@adamv Thanks - I'm still learning the ropes on how to work in git. Thanks for any tips on how to not noob too much.
