### ISSUE TITLE
glib fails to build

### ISSUE THREAD

**Issue by dagoar** [Homebrew/homebrew#38874]
glib 2.44 fails to build in Snow Leopard with error: redefinition of typedef 'GListModel'
https://gist.github.com/anonymous/98b79c635c0ddcd42cf6

it's already reported upstream https://bugzilla.gnome.org/show_bug.cgi?id=744473 and there is a patch for this in gstreamer bugzilla https://bugzilla.gnome.org/show_bug.cgi?id=744485

**Comment by dagoar** [comment]
it's already patched upstream in commit 4a292721bcf2943bfc05c6a1c859992f28e3efec

https://mail.gnome.org/archives/commits-list/2015-March/msg10287.html

**Comment by dagoar** [comment]
I confirm that adding this patch https://git.gnome.org/browse/glib/patch/?id=4a292721bcf2943bfc05c6a1c859992f28e3efec to the formula works OK

**Comment by DomT4** [comment]
Fancy submitting a PR with the patch? :)

**Comment by DomT4** [comment]
Formula Cookbook is [here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md) if you want a helpful reference. Plenty of examples of using external patches in-formula as well via a Github search. The latter involves less reading to find the answer :wink:

**Comment by jacknagel** [comment]
Pulled the fix.
