### ISSUE TITLE
Error: Empty Archive when trying to install wine for OSX Yosemite

### ISSUE THREAD

**Issue by Jokertyf** [Homebrew/homebrew#38884]
The only brew doctor error I get is 

Warning: Setting DYLD_* vars can break dynamic linking.
Set variables:
    DYLD_FALLBACK_LIBRARY_PATH: /usr/X11/lib

And I don't think this would affect installation. Besides, I don't know how to fix it. Anyway, when I try brew install wine, I get the following text:

==> Installing dependencies for wine: libpng, freetype, jpeg, pkg-config,
==> Installing wine dependency: libpng
==> Downloading https://downloads.sourceforge.net/project/libpng/libpng16/1.6.17
Already downloaded: /Library/Caches/Homebrew/libpng-1.6.17.tar.xz
Error: Empty archive

Any insight on this issue would be appreciated.

**Comment by dunn** [comment]
Try removing `/Library/Caches/Homebrew/libpng-1.6.17.tar.xz` so Homebrew has to download it again before installing.

**Comment by Jokertyf** [comment]
I removed it, but I still get the same error.

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by jacknagel** [comment]
try `brew reinstall xz`
