### ISSUE TITLE
missing plist for kafka

### ISSUE THREAD

**Issue by vegaed** [Homebrew/homebrew#38898]
A plist file is not generated for kafka. Would be very useful to have one.

**Comment by DomT4** [comment]
Fancy opening a PR to add one?

[Formula Cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md) and [this example](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/mpdscribble.rb#L28-L52) should help. Thanks!
