### ISSUE TITLE
Phantomjs fails to build on 10.6

### ISSUE THREAD

**Issue by agrimm** [Homebrew/homebrew#38916]
On a 10.6.8 OS X box, phantomjs isn't installing.

This gist-logs for the installation is

https://gist.github.com/b9c33003658c926c0187

The output while it was trying to install was

    ==> Downloading https://github.com/ariya/phantomjs/archive/2.0.0.tar.gz
    Already downloaded: /Library/Caches/Homebrew/phantomjs-2.0.0.tar.gz
    ==> Downloading https://gist.githubusercontent.com/mikemcquaid/db645f7cbeec4f3b1b2e/raw/e664ecc5c259344d5a73a84b52e472bf8ad3733e/phantomjs-yosemit
    Already downloaded: /Library/Caches/Homebrew/phantomjs--patch-1e723f055ef5df9a2945cbce3e70322105313f47.patch
    ==> Patching
    patching file src/qt/qtbase/src/plugins/platforms/cocoa/qcocoaapplicationdelegate.mm
    patch unexpectedly ends in middle of line
    ==> ./build.sh --confirm --jobs 2 --qt-config -openssl-linked
    
    Info: creating stash file /private/tmp/phantomjs20150422-81675-qa02ni/phantomjs-2.0.0/.qmake.stash
    cd src/ && ( test -e Makefile.phantomjs || /private/tmp/phantomjs20150422-81675-qa02ni/phantomjs-2.0.0/src/qt/qtbase/bin/qmake /private/tmp/phantomjs20150422-81675-qa02ni/phantomjs-2.0.0/src/phantomjs.pro -o Makefile.phantomjs ) && /usr/bin/make -f Makefile.phantomjs 
    Project ERROR: Unknown module(s) in QT: webkitwidgets network gui core
    make: *** [sub-src-phantomjs-pro-make_first-ordered] Error 3
    
    READ THIS: https://git.io/brew-troubleshooting

**Comment by jacknagel** [comment]
Looks like the error is:

```
cc1plus: error: unrecognized command line option "-stdlib=libstdc++"
```

while building Qt. The out of the box compilers on 10.6 do not support that option.

**Comment by dayvsonlima** [comment]
install via nodejs
npm install phantomjs -g
