### ISSUE TITLE
Update Squid to 3.5.3

### ISSUE THREAD

**Issue by dejl** [Homebrew/homebrew#38922]
http://www.squid-cache.org/Versions/

**Comment by asparagui** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!

**Comment by JasonBoyles** [comment]
It looks like Yosemite support for Kerberos is only on dev on the 3.5 series.

See these messages from the relevant thread on the dev list:

http://lists.squid-cache.org/pipermail/squid-dev/2015-April/002190.html
http://lists.squid-cache.org/pipermail/squid-dev/2015-April/002194.html

I can get 3.5.3 to build, but only if I disable the kerberos auth helpers. Is disabling kerberos auth acceptable, or should we just wait until official Yosemite krb5 auth lands in 3.5?

**Comment by mikemcquaid** [comment]
> I can get 3.5.3 to build, but only if I disable the kerberos auth helpers. Is disabling kerberos auth acceptable, or should we just wait until official Yosemite krb5 auth lands in 3.5?

Let's wait for it :+1:

**Comment by jacknagel** [comment]
Closing for now, per the above.

**Comment by dejl** [comment]
Is this what you were waiting for?
http://www.squid-cache.org/Versions/v3/3.5/changesets/SQUID_3_5_4.html

	+108 -40		Add Kerberos support for MAC OS X 10.x

**Comment by dejl** [comment]
When compiling 3.5.4 and getting:

[ ... truncated ... ]
basic_ldap_auth.cc:758:9: error: 'ldap_unbind' is deprecated: first deprecated
      in OS X 10.10 - use ldap_unbind_ext [-Werror,-Wdeprecated-declarations]
        ldap_unbind(bind_ld);
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/ldap.h:1963:1: note: 
      'ldap_unbind' has been explicitly marked deprecated here
ldap_unbind LDAP_P(( /* deprecated, use ldap_unbind_ext */
^
10 errors generated.
make[3]: *** [basic_ldap_auth.o] Error 1

Is this a different issue or is this related to the kerberos one earlier?
