### ISSUE TITLE
Make UnsignedKextRequirement optional

### ISSUE THREAD

**Issue by wodim** [Homebrew/homebrew#38973]
Currently if a formula includes UnsignedKextRequirement there is no way to install it on Yosemite.

Some of us have kext signature checks disabled and would like this check to be optional somehow.

**Comment by DomT4** [comment]
See:

#36181
#31164

**Comment by wodim** [comment]
Oh! This sucks. And it looks like it is some kind of religious thing by one of the project leaders. I don't like to have to edit the formulae by hand 😭
