### ISSUE TITLE
dpkg/1.17.25 broken - Can't locate Dpkg.pm in @INC, version 1.17.21 OK

### ISSUE THREAD

**Issue by bedge** [Homebrew/homebrew#38990]
I started seeing this using dpkg-scanpackages:
```
Can't locate Dpkg.pm in @INC (you may need to install the Dpkg module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /usr/local/Cellar/dpkg/1.17.25/bin/dpkg-scanpackages line 27.
BEGIN failed--compilation aborted at /usr/local/Cellar/dpkg/1.17.25/bin/dpkg-scanpackages line 27.
```
I tested it with the other version in had in the Cellar and that worked:
```
%> /usr/local/Cellar/dpkg/1.17.21/bin/dpkg-scanpackages binary binary/override | gzip -9c > binary/Packages.gz
...
info: Wrote 33 entries to output Packages file.
```
while explicitly specifying 1.17.25 does not:
```
%> /usr/local/Cellar/dpkg/1.17.25/bin/dpkg-scanpackages binary binary/override | gzip -9c > binary/Packages.gz
Can't locate Dpkg.pm in @INC (you may need to install the Dpkg module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /usr/local/Cellar/dpkg/1.17.25/bin/dpkg-scanpackages line 27.
BEGIN failed--compilation aborted at /usr/local/Cellar/dpkg/1.17.25/bin/dpkg-scanpackages line 27.
```

**Comment by DomT4** [comment]
`dpkg` is such a pain in the neck to configure on any non-linux system, sigh. Working on the fix.

**Comment by bedge** [comment]
I can imagine, but it's soooo cool having it even be an option. thank you many times over.

**Comment by bedge** [comment]
Does this need a pull request? Still not showing up in the default branch.
```
%> brew search dpkg
dpkg
```
No other taps available, and no version after 1.17.25:
```
%> brew info dpkg
dpkg: stable 1.17.25 (bottled)
https://wiki.debian.org/Teams/Dpkg
/usr/local/Cellar/dpkg/1.17.21 (218 files, 5.1M)
  Poured from bottle
/usr/local/Cellar/dpkg/1.17.25 (218 files, 5.1M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/dpkg.rb
```

**Comment by DomT4** [comment]
No. We didn't add a ` revision ` which would have forced everyone to rebuild because ` revision `s are generally intended for special situations. You were the only person to notice the error at all.

You can grab the new version by doing ` brew update && brew reinstall dpkg `. The version number will remain the same - That's an upstream thing.

**Comment by bedge** [comment]
OK, got it. Thanks. Reinstalling does indeed make a difference.

Unfortunately I'm hitting something else with this version:
```
%> /usr/local/Cellar/dpkg/1.17.25/bin/dpkg-scanpackages binary binary/override | gzip -9c > binary/Packages.gz
dpkg-scanpackages: error: checksum program gave bogus output `MD5 (binary//callas-pdfengine-sdk_7.2.261_amd64.deb) = e9c31dc2145cf1d1a9e7c848bb07657b
'
```
The old version is still OK:
```
%> /usr/local/Cellar/dpkg/1.17.21/bin/dpkg-scanpackages binary binary/override | gzip -9c > binary/Packages.gz
dpkg-scanpackages: warning: Packages in archive but missing from override file:
dpkg-scanpackages: warning:   callas-pdfengine-sdk jetty-hightide-server ..... sling-server
dpkg-scanpackages: info: Wrote 34 entries to output Packages file.
```

Should I file a new bug?
Let me know if you need any additional debug data.

**Comment by DomT4** [comment]
It's reasonably possible the different outputs between ` md5 ` and ` md5sum ` is confusing it. We didn't change the patch though, so unless upstream changed something, 1.17.25 should be working the same as 1.17.21.

 Can you give me a step by step reproducible test case?

**Comment by kausters** [comment]
I have the same issue with 1.17.25. I managed to fix the "Can't locate Dpkg.pm in @INC" error by reinstalling dpkg, but now am stuck at the same MD5 error as @bedge.

**Comment by DomT4** [comment]
> Can you give me a step by step reproducible test case?

Need the above. I'm not a regular user of the `dpkg-scanpackages` tool.

**Comment by kausters** [comment]
Ok, I'm using it in this project: [kausters/repo](https://github.com/kausters/repo)
Check it out and run `make` — all it does is compile the (already included) packages to a child folder.

**Comment by DomT4** [comment]
Thanks, that looks like a perfect test case. I'll take a look later this evening.

**Comment by DomT4** [comment]
#39666
