### ISSUE TITLE
Lua changes and cleanup

### ISSUE THREAD

**Issue by telemachus** [Homebrew/homebrew#39000]
With the changes to the Lua formula (particularly this one: https://github.com/Homebrew/homebrew/commit/06e2a38236544d74eb672d6dd7ba40a03da72ef3), the placement of items installed by `luarocks` has changed. I've just uninstalled and upgraded, and everything seems to work well, but the old `/usr/local/lib/lua` and `/usr/local/lib/luarocks` directories and all their contents were left.

I'm wondering if it would be good to put a caveat (maybe on the `lua` formula itself), telling users that those directories are no longer in use and that they can (should?) remove them and their contents. But I'm unsure if that might have any unintended side-effects.

**Comment by DomT4** [comment]
The Luarocks directories should have been killed by making the ` luarocks ` formula ` keg_only ` a week or so ago, unless a manual ` brew prune ` is required to tidy those up. You could try a ` brew prune ` and see what happens.

` /usr/local/lib/lua ` should still exist if you have Lua51 installed - Otherwise it's safe to remove. ` /usr/local/lib/luarocks ` - You can remove all and any contents that aren't nested inside a ` rocks-5.2 ` or ` rocks-5.1 ` folder.

**Comment by telemachus** [comment]
Ah, I hadn't done that last `luarocks` update and I completely forgot about `brew prune`. I already deleted things here manually, but I will test this later on my home machine and then probably close this issue. Thanks.

**Comment by telemachus** [comment]
@DomT4 Just tried `brew prune` and it left `/usr/local/lib/lua` and `/usr/local/lib/luarocks`. I've only had lua 5.2 installed.

I'm not so much worried about what I can remove as whether there should be a caveat urging people to clean up after the change. Thanks.

**Comment by DomT4** [comment]
> /usr/local/lib/luarocks

You should still have this even after a ` brew prune ` - It will contain the new Luarocks directories and modules, similar to ` lib/python2.7/site-packages ` and such.

I'm not overly worried about leaving small elements behind personally. The Lua installations are tiny, and old files shouldn't interfere given the way the new setup is configured. The difficulty is in phrasing a caveat, i.e.

```
If you have Lua51 installed, don't touch anything. If you have Lua installed, but not Lua51, you can remove the /usr/local/lib/lua directory. If you have any Lua installed you can remove anything within /usr/local/lib/luarocks that isn't nested in a directory named rocks-luaversion.
```

We can find out what formulae users have installed and cater caveats to that, but that's a decent chunk of code to write in. I don't know. I don't consider it something that's going to cause Homebrew or the user problems.

Ultimately though, I have zero power over what caveats we want and don't want. I'll punt on that to @Homebrew/owners.

**Comment by telemachus** [comment]
>> /usr/local/lib/luarocks
>
> You should still have this even after a brew prune - It will contain the new Luarocks directories and modules, similar to lib/python2.7/site-packages and such.

Right, I didn't specify: It still had all the old installs. I'm not worried about the folders, I'm worried that the update leaves behind however many modules I've installed under the old Lua setup.

I understand what you're saying in terms of the size of what's left behind, but the principle of it bothers me. It seems wrong for a package manager to leave behind junk. I'll leave this here and see if anyone else weighs in. Thanks.

**Comment by mikemcquaid** [comment]
> I understand what you're saying in terms of the size of what's left behind, but the principle of it bothers me. It seems wrong for a package manager to leave behind junk. I'll leave this here and see if anyone else weighs in. Thanks.

I think we'd rather err on the side of caution where user-installed/modified data is concerned. I'd rather leave duplicates than have Homebrew delete stuff that may break other things.

**Comment by mikemcquaid** [comment]
In short: I think Homebrew should only be responsible for cleaning up the stuff it creates.

**Comment by telemachus** [comment]
> In short: I think Homebrew should only be responsible for cleaning up the stuff it creates.

A fair point. I'll close this. Thanks for responses.
