### ISSUE TITLE
Throw an error for installing imagemagic

### ISSUE THREAD

**Issue by hemedani** [Homebrew/homebrew#39004]
I want's to install imagemagic in ubuntu 15.04 with linuxbrew but this error was apear :
 `  brew install imagemagick
==> Installing dependencies for imagemagick: xz, libtool, jpeg, libpng, freetype
==> Installing imagemagick dependency: xz
==> Downloading https://fossies.org/linux/misc/xz-5.2.1.tar.gz
Already downloaded: /home/amir/.cache/Homebrew/xz-5.2.1.tar.gz
==> ./configure --disable-silent-rules --prefix=/home/amir/.linuxbrew/Cellar/xz/5.2.1
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Doxyfile
gawk: symbol lookup error: /home/amir/.linuxbrew/lib/libreadline.so.6: undefined symbol: UP
config.status: error: could not create Doxyfile`

`READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting`

**Comment by DomT4** [comment]
Wrong repo I'm afraid. Linux support is provided [here](https://github.com/Homebrew/linuxbrew/issues), Please open an issue there. Thanks!
