### ISSUE TITLE
Brew not finding passenger formula

### ISSUE THREAD

**Issue by secondstreetmedia** [Homebrew/homebrew#39017]
When I execute the "brew search passenger" command, the response is:

     No formula found for "passenger".  Searching pull requests... Closed pull requests:

followed by a long list of closed pull requests (see below).  I can find other formulae, such as nginx, but for some reason not passenger.

My OS is Yosemite 10.10.3, I ran "brew update", "brew upgrade", and "brew cleanup".  My Xcode and CLT's are up to date.

I ran "brew doctor", which returns two warnings: 

     Warning: "config" scripts exist outside your system or Homebrew directories. (this config script is ~/.rvm/gems/ruby-2.2.2/bin/passenger-config - which I installed via RVM)

     Warning: You have a curlrc file (I ran the "curl http://github.com" command and got a command prompt in response, so I'm assuming that means this isn't a problem).

I could not create a Gist file because it cannot find the formula.

While I was able to install passenger using RVM, I still need to be able to find its formula because I cannot run "brew install nginx --with-passenger" without it.

Any suggestions?
Thanks!
Tim Edwards

~>> brew search passenger
No formula found for "passenger".
Searching pull requests...
Closed pull requests:
passenger 5.0.4 (https://github.com/Homebrew/homebrew/pull/37610)
Update passenger to version 5.0.6 (https://github.com/Homebrew/homebrew/pull/38227)
passenger 5.0.1 (https://github.com/Homebrew/homebrew/pull/37393)
Update passenger to version 5.0.5 (https://github.com/Homebrew/homebrew/pull/38021)
...etc.

**Comment by jacknagel** [comment]
Does `/usr/local/Library/Formula/passenger.rb` exist?

**Comment by secondstreetmedia** [comment]
Thanks for the reply.  No, it doesn't exist in that directory.  I did a 

     sudo find ./ -name "passenger.rb"

search and it doesn't appear to be in any directory.  When I do 

     passenger -v

however, I get "Phusion Passenger version 5.0.6".

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by secondstreetmedia** [comment]
Apologies.  Let me know if I missed anything.

Gist:  https://gist.github.com/secondstreetmedia/9eb8b79bb75e80668510#file-homebrew_passenger_formula_troubleshooting

Thanks,
Tim

**Comment by jacknagel** [comment]
Well, there should be a file named `passenger.rb` in `/usr/local/Library/Formula`.

Do this:

```
cd $(brew --prefix)
git reset --hard origin/master
```

**Comment by secondstreetmedia** [comment]
That worked perfectly!  I was able to brew install both passenger and nginx --with-passenger.  And there is now a passenger.rb file in /usr/local/library/Formula.
Is there something I should have known to do that I didn't do or that would have caused the need for the git reset command?  Also, what should have placed the passenger.rb file in /usr/local/library/formula in the first place -- installing passenger using RVM?

Thanks so much, Jack, for the assistance!

**Comment by jacknagel** [comment]
>Also, what should have placed the passenger.rb file in /usr/local/library/formula in the first place

It's part of the Homebrew repository, so if it was missing, the local checkout was modified somehow. It's hard to say why.
