### ISSUE TITLE
bash-completion2- compopt: command not found

### ISSUE THREAD

**Issue by tejasmanohar** [Homebrew/homebrew#39014]
```bash
tejas at Tejass-MacBook-Pro in ~
$ cd dot-bash: compopt: command not found
files

tejas at Tejass-MacBook-Pro in ~
$ cd Repo-bash: compopt: command not found
s
```

Just installed bash-completion2 and it's acting super funky. Every time I hit [tab] for cd completion, whatever I typed (ex: dot, Repo) is followed by "-bash: compopt: command not found\n" and on the next line, it actually finishes autocompletion (ex: dot -> dotfiles, Repo -> Repos). This seems to just be with `cd` though I haven't tested much more. It doesn't act like this when I just do like `cla` [tab] -> `clang`. Here's my `brew leaves` https://gist.github.com/tejasmanohar/69c4776e2561f5c3194e

This is really irritating behavior but not sure how to resolve it. Any advice? I'll run any commands and get more details- just ask :smile:

**Comment by tejasmanohar** [comment]
```bash
-bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
-bash: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]
```

that's printed at the top of every shell of mine. my dotfiles are located here- https://github.com/tejasmanohar/dotfiles

**Comment by tejasmanohar** [comment]
vim autocompletion is also goofing. for example...
`$ vim brew-bash: $matchop($xspec|${xspec^^}): bad substitution`

I did `vim brew[TAB]` where [TAB] is hitting the key, intending to make that `vim brew.sh` but instead, this nonsense came up.

**Comment by jacknagel** [comment]
bash-completion2 does not work with the system bash (3.2.x), you need to install bash 4.x `(`brew install bash` or through other means). This is why it's in the homebrew-versions tap and not in core.

**Comment by DomT4** [comment]
> ou need to install bash 4.x

Should it have a ` depends_on "bash" ` then?

**Comment by tejasmanohar** [comment]
@jacknagel, but I already have bash 4.x.x installed! What's that git stuff in the bottom of when I ran the command, my bash seems to be goofy right now.

@DomT4 Yeah, I think so...

```bash
$ bash --version
bash --version
GNU bash, version 4.3.33(1)-release (x86_64-apple-darwin14.1.0)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
prompt_git " on "
git rev-parse --is-inside-work-tree &>/dev/null; echo "${?}"
```

```bash
$ brew install bash
brew install bash
Warning: bash-4.3.33 already installed
prompt_git " on "
git rev-parse --is-inside-work-tree &>/dev/null; echo "${?}"
```

**Comment by tejasmanohar** [comment]
these are my dotfiles- https://github.com/tejasmanohar/dotfiles

this issue should definitely be re-opened.

**Comment by mikemcquaid** [comment]
> Should it have a depends_on "bash" then?

The problem is that alone isn't really enough.

**Comment by DomT4** [comment]
Ah, rats. Thanks for the clarification.

**Comment by tejasmanohar** [comment]
@mikemcquaid Am I missing another dep that you know of?

**Comment by mikemcquaid** [comment]
I just mean that you need to have it installed and then have your shell configured to actually use it.

**Comment by tejasmanohar** [comment]
@mikemcquaid so there's some configuration i need before its usable?

any more than this? https://github.com/tejasmanohar/dotfiles/blob/master/.bash_profile#L25

**Comment by jacknagel** [comment]
`bash --version` doesn't tell you what your login shell is. Did you use the `chsh` command to switch it to `/usr/local/bin/bash`?

**Comment by tejasmanohar** [comment]
@jacknagel ran `chsh -s /usr/local/bin/bash` and restarted terminal, but the same issues continue.

```bash
-bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
-bash: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]
```bash

Additionally, this is erred at the top of every new shell.

**Comment by jacknagel** [comment]
It's still not configured correctly.

```
$ /bin/bash -c 'declare -A'
/bin/bash: line 0: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
jacknagel@haswell:~ $ /usr/local/bin/bash -c 'declare -A'
declare -A BASH_ALIASES='()'
declare -A BASH_CMDS='()'
```

**Comment by tejasmanohar** [comment]
I got it :) - had to change the login shell in terminal emulator.

**Comment by tejasmanohar** [comment]
I'll fix that, too. thanks

**Comment by CodeMaxx** [comment]
I'm getting the same error

`bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
-bash: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]`

Can I get help on this? I'm using OS X. 
Used `brew install bash` and `chsh -s /usr/local/bin/bash` already

**Comment by bfontaine** [comment]
@CodeMaxx Please open a new issue.
