### ISSUE TITLE
Datomic config directory

### ISSUE THREAD

**Issue by neverfox** [Homebrew/homebrew#39015]
Is there a reason that the Datomic cask doesn't install the `config` directory (which contains sample transactor.properties files)?

**Comment by DomT4** [comment]
Formula, not ` cask `, if you're talking about Homebrew/homebrew - Differing terminology between the two projects :smile_cat:.

Probably not. It's possibly just the case nobody thought to put it in yet. Feel free to [Open a PR](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md) to add the desired files. There's documentation [here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md) on how to write formulae if you find that helpful.

**Comment by neverfox** [comment]
Sorry. Had cask on the brain for some reason. Ok, good to know it's not related to licensing or technical hurdles.

**Comment by neverfox** [comment]
Ah, it was all under the libexec directory!

**Comment by DomT4** [comment]
Oh it's a Java thing I presume? Yeah, It would be. If it'd be useful to have those files installed or symlinked into ` share ` or something, feel free to open a PR still.
