### ISSUE TITLE
gcc-4.9.2 failed build on 10.9.5

### ISSUE THREAD

**Issue by leedx1** [Homebrew/homebrew#39030]
i try to build gcc-4.9.2 on 10.9.5,but got this logs

gist here:
https://gist.github.com/7a97ff8507febbe01816

configure: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details.
make[2]: *** [configure-stage1-target-libgcc] Error 1
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2

Any suggestions?
Thanks!

**Comment by jacknagel** [comment]
>dyld: Library not loaded: /usr/local/lib/libmpfr.4.dylib

`brew reinstall mpfr`

**Comment by leedx1** [comment]
solved,thanks.
