### ISSUE TITLE
Brew Update Error

### ISSUE THREAD

**Issue by ssabat** [Homebrew/homebrew#39063]
I was trying to update homebrew. I got error.

Here it is.

Users-MacBook:~ user$ brew update
Checking out files: 100% (3566/3566), done.
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 972 and retry the command.
Error: undefined method `to_sym' for nil:NilClass
Please report this bug:
    https://github.com/mxcl/homebrew/wiki/troubleshooting
/usr/local/Library/Homebrew/cmd/update.rb:111:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:109:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:109:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:23:in `update'
/usr/local/Library/brew.rb:95:in `send'
/usr/local/Library/brew.rb:95

**Comment by DomT4** [comment]
` brew config ` and ` brew doctor ` here may be useful. It *looks* like your Homebrew is *way* out of date.

**Comment by jacknagel** [comment]
This is a one time bug that you won't see the next time you update.
