### ISSUE TITLE
Bash completion installed from cmake bottle gives errors for new terminal sessions

### ISSUE THREAD

**Issue by jrabbe** [Homebrew/homebrew#39083]
**Steps:**
1. install cmake `brew install cmake`
2. open a new shell

**Expected:**
No errors

**Actual:**
```bash
bash: /usr/local/etc/bash_completion.d/ctest: line 44: syntax error in conditional expression: unexpected token `('
bash: /usr/local/etc/bash_completion.d/ctest: line 44: syntax error near `@(E'
bash: /usr/local/etc/bash_completion.d/ctest: line 44: `            if [[ $cur == @(Experimental|Nightly|Continuous)* ]]; then'
```

Let me know if you need any debugging information aside from what is provided below.

---

**System info:**
- Mac OS X 10.10.3 with newest XCode and CLI tools
- iTerm 2

**Installed formulae:**
- autoconf
- czmq
- gettext
- icu4c
- libtiff
- pango
- texi2html
- automake
- docker
- gfortran
- imagemagick
- libtool
- pixman
- ttfautohint
- bison
- elasticsearch
- git
- isl
- libvo-aacenc
- pkg-config
- x264
- boost
- faac
- glib
- jpeg
- libyaml
- postgresql
- xvid
- boot2docker
- ffmpeg
- gmp
- jq
- makedepend
- python
- xz
- brew-cask
- fontconfig
- gnu-tar
- lame
- maven
- python3
- yasm
- cairo
- fontforge
- go
- libffi
- mpfr
- readline
- zeromq
- cloc
- freetds
- gobject-introspection
- libmpc
- node
- redis
- cloog
- freetype
- graphviz
- libpng
- openssl
- sbcl
- cmake
- gdbm
- harfbuzz
- libsodium
- ossp-uuid
- sqlite

**Comment by jacknagel** [comment]
Looks like the completion script uses syntax that the system bash does not support. Try installing bash-completion2 from homebrew-versions, or report it upstream to cmake.

**Comment by jacknagel** [comment]
@Homebrew/owners if the completion is indeed incompatible with the system bash and/or bash-completion 1.x., should we even be installing it?

**Comment by mikemcquaid** [comment]
@jacknagel Optionally probably makes more sense to me if it does to you?

**Comment by DomT4** [comment]
Is this still an issue? I can't reproduce.

**Comment by apolunin** [comment]
I can reproduce it exactly as written by @jrabbe.
Installation of bash from homebrew and bash-completion2 did not helped. The same problem is still reproducible.
