### ISSUE TITLE
Brew install Devil stuck in loop?

### ISSUE THREAD

**Issue by Noobidoo** [Homebrew/homebrew#39082]
I do brew install --verbouse devil and get stuck at (full log below):
"checking whether gcc-4.9 and cc understand -c and -o together... yes"

/tmp/iromu/VisualSFM.app/Contents/Resources/bin/brew --version returns: 0.9.5

In "~/Library/Logs/Homebrew/devil/01.configure.cc" i see: [extracted: https://gist.github.com/tdsmith/6fa1c3666073a3b43241 -tdsmith]

/tmp/iromu/VisualSFM.app/Contents/Resources/bin/brew install --verbose devil
==> Downloading https://downloads.sourceforge.net/project/openil/DevIL/1.7.8/DevIL-1.7.8.tar.gz
Already downloaded: /Library/Caches/Homebrew/devil-1.7.8.tar.gz
==> Verifying devil-1.7.8.tar.gz checksum
tar xf /Library/Caches/Homebrew/devil-1.7.8.tar.gz
==> Patching
patching file src-ILU/ilur/ilur.c
==> ./configure --disable-debug --disable-dependency-tracking --prefix=/private/tmp/iromu/VisualSFM.app/Contents/Resources/Cellar/devil/1.7.8_1 --enable-ILU --enable-ILUT
checking build system type... i386-apple-darwin14.0.0
checking host system type... i386-apple-darwin14.0.0
checking for gcc... gcc-4.9
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc-4.9 accepts -g... yes
checking for gcc-4.9 option to accept ISO C89... none needed
checking for a sed that does not truncate output... /private/tmp/iromu/VisualSFM.app/Contents/Resources/Library/ENV/4.3/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc-4.9... /private/tmp/iromu/VisualSFM.app/Contents/Resources/Library/ENV/4.3/ld
checking if the linker (/private/tmp/iromu/VisualSFM.app/Contents/Resources/Library/ENV/4.3/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm
checking the name lister (/usr/bin/nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /private/tmp/iromu/VisualSFM.app/Contents/Resources/Library/ENV/4.3/ld option to reload object files... -r
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm output from gcc-4.9 object... ok
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking how to run the C preprocessor... gcc-4.9 -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc-4.9 supports -fno-rtti -fno-exceptions... no
checking for gcc-4.9 option to produce PIC... -fno-common -DPIC
checking if gcc-4.9 PIC flag -fno-common -DPIC works... yes
checking if gcc-4.9 static flag -static works... no
checking if gcc-4.9 supports -c -o file.o... yes
checking if gcc-4.9 supports -c -o file.o... (cached) yes
checking whether the gcc-4.9 linker (/private/tmp/iromu/VisualSFM.app/Contents/Resources/Library/ENV/4.3/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin14.0.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking dependency style of gcc-4.9... none
checking build system type... (cached) i386-apple-darwin14.0.0
checking host system type... (cached) i386-apple-darwin14.0.0
checking whether gcc-4.9 and cc understand -c and -o together... yes
^C
toms-MBP:Library noobs$ rm ~/Library/Logs/Homebrew/devil/*
toms-MBP:Library noobs$ /tmp/iromu/VisualSFM.app/Contents/Resources/bin/brew install --verbose devil
==> Downloading https://downloads.sourceforge.net/project/openil/DevIL/1.7.8/DevIL-1.7.8.tar.gz
Already downloaded: /Library/Caches/Homebrew/devil-1.7.8.tar.gz
==> Verifying devil-1.7.8.tar.gz checksum
tar xf /Library/Caches/Homebrew/devil-1.7.8.tar.gz
==> Patching
patching file src-ILU/ilur/ilur.c
==> ./configure --disable-debug --disable-dependency-tracking --prefix=/private/tmp/iromu/VisualSFM.app/Contents/Resources/Cellar/devil/1.7.8_1 --enable-ILU --enable-ILUT
checking build system type... i386-apple-darwin14.0.0
checking host system type... i386-apple-darwin14.0.0
checking for gcc... gcc-4.9
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc-4.9 accepts -g... yes
checking for gcc-4.9 option to accept ISO C89... none needed
checking for a sed that does not truncate output... /private/tmp/iromu/VisualSFM.app/Contents/Resources/Library/ENV/4.3/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc-4.9... /private/tmp/iromu/VisualSFM.app/Contents/Resources/Library/ENV/4.3/ld
checking if the linker (/private/tmp/iromu/VisualSFM.app/Contents/Resources/Library/ENV/4.3/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm
checking the name lister (/usr/bin/nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /private/tmp/iromu/VisualSFM.app/Contents/Resources/Library/ENV/4.3/ld option to reload object files... -r
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm output from gcc-4.9 object... ok
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking how to run the C preprocessor... gcc-4.9 -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc-4.9 supports -fno-rtti -fno-exceptions... no
checking for gcc-4.9 option to produce PIC... -fno-common -DPIC
checking if gcc-4.9 PIC flag -fno-common -DPIC works... yes
checking if gcc-4.9 static flag -static works... no
checking if gcc-4.9 supports -c -o file.o... yes
checking if gcc-4.9 supports -c -o file.o... (cached) yes
checking whether the gcc-4.9 linker (/private/tmp/iromu/VisualSFM.app/Contents/Resources/Library/ENV/4.3/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin14.0.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking dependency style of gcc-4.9... none
checking build system type... (cached) i386-apple-darwin14.0.0
checking host system type... (cached) i386-apple-darwin14.0.0
checking whether gcc-4.9 and cc understand -c and -o together... yes

**Comment by jacknagel** [comment]
What is this:

```
/tmp/iromu/VisualSFM.app/Contents/Resources/bin/brew
```

We don't support that. Can you reproduce the issue on a standard homebrew installation?

**Comment by Noobidoo** [comment]
Yes it's the same with installed brew, It's a brew that is not installed at the standard place and i thought that was supported.

**Comment by Noobidoo** [comment]
Hmm it fixed it self now. All i did was that the computer had crashed so i had to hard restart it.
