### ISSUE TITLE
gnumeric failed to build on 10.10.3

### ISSUE THREAD

**Issue by longwdl** [Homebrew/homebrew#39096]
#### update gnumeric failed.    
````
==> Installing gnumeric from homebrew/homebrew-x11
==> Downloading http://ftp.gnome.org/pub/GNOME/sources/gnumeric/1.10/gnumeric-1.10.17.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gnumeric-1.10.17.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/gnumeric/1.10.17
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBSPREADSHEET_CFLAGS
and LIBSPREADSHEET_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
couldn't understand kern.osversion `14.3.0'
````

#### link to the [gist](https://gist.github.com/a6b9f10f3fc0766f83fb)

**Comment by tschoonj** [comment]
The gnumeric formula is badly outdated and does not match the goffice and libgsf formula versions, which are released alongside it.

**Comment by DomT4** [comment]
@tschoonj Fancy submitting a PR to update it?

**Comment by geoffreak** [comment]
I tried out the formula used by @tschoonj. While it allows Gnumeric to compile, both the `gnumeric` and `ssconvert` commands will error with `Bus error: 10`.
