### ISSUE TITLE
Installing php55

### ISSUE THREAD

**Issue by dramalcolm** [Homebrew/homebrew#39106]
brew install php55 --with-mssql
Error: cannot load such file -- /Library/Caches/Homebrew/Abstract/abstract-php
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Caches/Homebrew/Formula/php55.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:140:in `<main>'

**Comment by dunn** [comment]
This should probably be filed at [Homebrew/homebrew-php](https://github.com/Homebrew/homebrew-php), but either way your `brew gist-logs php55` will help to figure things out.

**Comment by mikemcquaid** [comment]
This issue was moved to Homebrew/homebrew-php#1689
