### ISSUE TITLE
Upgrading Ruby gem wipes out any installed gems

### ISSUE THREAD

**Issue by moreindirection** [Homebrew/homebrew#39113]
Over the last few months, whenever I run "brew upgrade ruby", I have to reinstall all of the gems I had installed in the previous version.

**Comment by jacknagel** [comment]
This bug was fixed, I think you just need to do this:

```
brew rm ruby --force
rm -rf $(brew --prefix)/lib/ruby
brew install ruby
gem install <your gems>
```

then they should persist on the next upgrade.

**Comment by moreindirection** [comment]
Thanks, @jacknagel - just tried that, will be able to confirm that it worked the next time there's a new Ruby upgrade :)

**Comment by jacknagel** [comment]
Closing for now.
