### ISSUE TITLE
Homebrew Mono updated but want to current release 3.12.1

### ISSUE THREAD

**Issue by teledong** [Homebrew/homebrew#39127]
15 hours ago, homebrew mono updated 4.0.1
but some reason (http problem), i want to use current release (3.12.1) mono.
please add options for install current release version.

**Comment by jacknagel** [comment]
Did you `brew update`?

**Comment by teledong** [comment]
Of course.
Already up-to-date.

**Comment by teledong** [comment]
Some program not support 4.0.1 (Because It's not current release). Running program with Mono 3.12.1 is working fine, but 4.0.1 contains error..... I don't know why but i want to use 3.12.1 version...

**Comment by DomT4** [comment]
Might not be updated on the upstream website yet, but aye:

![screen shot 2015-04-28 at 01 40 38](https://cloud.githubusercontent.com/assets/6998367/7360848/c93f13f0-ed47-11e4-9a01-a50b6fab458f.png)

**Comment by teledong** [comment]
Hmm... But I confirmed working perfectly using mono 3.12.1, (errors using mono 4.0,1)
make a options to select version is more comfortable i guess :)

**Comment by DomT4** [comment]
My point there was you may be right in that we *may* have merged a pre-release or similar instead of a production release. The Mono website is usually pretty quickly updated, but the current version and the News sections still highlight 3.12.1 as the current version.

**Comment by jacknagel** [comment]
Sorry, I misunderstood the question.

**Comment by xu-cheng** [comment]
Sorry my bad. I have revert mono to the stable release.

**Comment by directhex** [comment]
Frankly, at 1am, updating the website was not my top priority.

4.0.1 is the new stable release.

We haven't done the release announcement yet, for various reasons (it should happen later today once the US wakes up) - but we wanted to get packages ready and in place for a big announcement at Microsoft BUILD tomorrow. Homebrew was going to be part of the announcement, but I can request that they remove that part of the announcement, if Homebrew plans on sticking with the old version long term.

**Comment by xu-cheng** [comment]
If that's the case, I can restore mono 4.0.1 back. However, I do have a question on whether we should keep mono 3.x in homebrew/version? cc @mikemcquaid what's our policy on pre-shipping in this condition?

**Comment by directhex** [comment]
Does Homebrew have a mechanism for offering historic versions of the same software? if so, that's the correct way to offer legacy software to users (similarly, in our apt repository, we have "snapshot" apt repositories which offer the packages that were state of the art at a given moment, as well as the main repository which is always $latest)

**Comment by xu-cheng** [comment]
> Does Homebrew have a mechanism for offering historic versions of the same software? 

Yes, by adding it into [homebrew/versions](https://github.com/Homebrew/homebrew-versions).

**Comment by mikemcquaid** [comment]
> @mikemcquaid what's our policy on pre-shipping in this condition?

I don't consider it preshipping if the Mono team says it's a stable version.

> Frankly, at 1am, updating the website was not my top priority.
> 4.0.1 is the new stable release.

We have no way of knowing that information. It'd be good if you could let us know and provide a bit more context for these things in future. I'm happy for us to go back to 4.0.1 in this case.

**Comment by xu-cheng** [comment]
OK, I have restore mono 4.0.1 in f303993d81cd5a263997505ff923faf76a9ceece. 

@directhex Thanks for your understanding and patient. If you are willing, can you send PR to add mono3.rb in homebrew/versions.
