### ISSUE TITLE
brew audit and JAVA_HOME

### ISSUE THREAD

**Issue by pauldaustin** [Homebrew/homebrew#39125]
brew audit fails if the keyword JAVA_HOME is found in the formula.

This means there is no way to pass in the JAVA_HOME to a make command or change the JAVA_HOME defined in a configuration file used by a makefile.

For example in the gdal formula the swig/java/java.opt file needs to have the JAVA_HOME set to a correct value. For some reason it won't pick up the JAVA_HOME from the environment. I think it pulls in another file that defines JAVA_HOME= (empty string). That would override the environment.

**Comment by xu-cheng** [comment]
That audit rule intents to find formula who uses `JAVA_HOME` but fails to `depends_on :java`. However, in your case, `depends_on :java` is shadowed inside the condition statement. If you use below code, you should be able work around it.
```ruby
option "with-java", "Build the swig java bindings"
depends_on :java => ["1.7+", :optional]
```

This also means we fail to audit all the dependencies inside the condition statement. I wonder whether it's possible to test all combinations of options when auditing formula. ping @jacknagel  for some thoughts.

**Comment by jacknagel** [comment]
The solution moving forward is to not declare things inside conditionals in the class body. Part of the new dependency implementation will make this easier but for now `=> :optional` and `=> :recommended` are what we have as an alternative.

**Comment by pauldaustin** [comment]
````
depends_on :java => ["1.7+", :optional, :build]
````
Did the trick

Now the following passes the audit check

````
inreplace "java.opt", "#JAVA_HOME = /usr/lib/jvm/java-6-openjdk/", 'JAVA_HOME=$(shell echo $$JAVA_HOME)'
````

I'm going to work with the GDAL project to see if I can get the swig java bindings to be built without requiring the java.opt file
