### ISSUE TITLE
Cannot upgrade outdated formulas

### ISSUE THREAD

**Issue by cojoj** [Homebrew/homebrew#39136]
Whenever I try to run `brew upgrade` I get:

> Warning: brew upgrade with no arguments will change behaviour soon!
It currently upgrades all formula but this will soon change to require '--all'.
Please update any workflows, documentation and scripts!

What does it mean that I need to update **workflows, documentation and scripts**? Other homebrew commands work fine but this one... Any idea what migh be wrong or there is some kind of bug?

**Comment by xu-cheng** [comment]
It's just a warning that you should use `brew upgrade --all` in the future.

**Comment by eccstartup** [comment]
It is a terrible feature for me.

**Comment by DomT4** [comment]
Please see #38572. The reasons for the change haven't moved, and there's plenty of time to update scripts/etc before the previous command is phased out.

**Comment by eccstartup** [comment]
What I don't understand is what is the difference between former `brew upgrade` and now `brew upgrade --all`. If it doesn't change, will there be any conflict? Adding `--all` is really harder than before. So if there were not difference, why change? I don't get your methodology.

**Comment by DomT4** [comment]
Upgrading everything at once has broken things for people before. `brew upgrade --all` actually makes users confirm they're happy to upgrade *everything* they've installed and has an update pending. It's a confirmation of their intention. Long-term `brew upgrade --all` or `brew upgrade formula` will be the default - `brew upgrade` will eventually do nothing.

This is unlikely to be reversed. The positives outweigh the negatives in this situation.

**Comment by eccstartup** [comment]
You can ask people to confirm by clicking [Enter].

**Comment by bfontaine** [comment]
> You can ask people to confirm by clicking [Enter].

This breaks non-interactive scripts.

**Comment by mikemcquaid** [comment]
I've locked this issue and deleted the discussion. Let's take discussions like this to the mailing list.
