### ISSUE TITLE
<formula mhash> failed to build on 10.10.3

### ISSUE THREAD

**Issue by yuerthe9** [Homebrew/homebrew#39172]
lifangdeMacBook-Air:~ eye$ brew install mcrypt
==> Installing mcrypt dependency: mhash
==> Downloading https://downloads.sourceforge.net/project/mhash/mhash/0.9.9.9/mhash-0.9.9.9.tar.gz
Already downloaded: /Library/Caches/Homebrew/mhash-0.9.9.9.tar.gz
==> ./configure --prefix=/usr/local/Cellar/mhash/0.9.9.9
==> make install
Error: parent directory is world writable but not sticky
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:481:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:184:in `install'
/usr/local/Library/Homebrew/formula_installer.rb:358:in `install_dependency'
/usr/local/Library/Homebrew/formula_installer.rb:316:in `block in install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:316:in `each'
/usr/local/Library/Homebrew/formula_installer.rb:316:in `install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:221:in `compute_and_install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:149:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:165:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `install'
/usr/local/Library/brew.rb:140:in `<main>'

**Comment by yuerthe9** [comment]
lifangdeMacBook-Air:~ eye$ ls -la /usr/local/Cellar
total 0
drwxr-xr-x  19 eye   admin  646  4 29 14:07 ./
drwxrwxr-x  20 root  admin  680  4 24 21:33 ../

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by jacknagel** [comment]
Follow https://github.com/Homebrew/homebrew/issues/39170#issuecomment-97367623 or repair disk permissions using Disk Utility.
