### ISSUE TITLE
Gitorious sunset "end of May"

### ISSUE THREAD

**Issue by L2G** [Homebrew/homebrew#39176]
"System notice: Gitorious is being acquired by GitLab and gitorious.org will shut down end of May."
—banner on Gitorious

Affected formulæ in core:
- [x] cdimgtools
- [x] deheader (see #39180)
- [x] dfu-util (see #39181)
- [x] freetds (see #39255)
- [x] git-latexdiff (migrating to homebrew/tex; see #39463 and Homebrew/homebrew-tex#8)
- [ ] itstool :snake: 
- [x] lmdb (see #39268)
- [x] pdfgrep (see #39301)
- <del>phantomjs</del> (false alarm)
- [ ] pyside :snake:
- [ ] pyside-tools :snake:
- [x] qt (see #39203)
- [x] qt5 (see #39204)
- [x] safe-rm (fixed in 9f2d631e6b44254f1dd90bf6ebc39a7e0ad80361)
- [ ] shiboken :snake:

Affected Homebrew code:
- [ ] `audit` command

Formulæ marked with :snake: have [special needs](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Python-for-Formula-Authors.md).

**Comment by L2G** [comment]
As pointed out by @mistydemeo, [Archive Team](http://archiveteam.org/) (not to be confused with the Internet Archive?) has [announced](http://archiveteam.org/index.php?title=Gitorious) that it will keep a read-only archive of the Gitorious repos available at the same domain name. So a number of these may end up being resolved simply by verifying that they are still accessible after the official closure.

**Comment by DomT4** [comment]
`qt` and `qt5` have been transitioned. Can cross those off the list.

**Comment by L2G** [comment]
@DomT4 Thanks. :+1: :+1:

**Comment by L2G** [comment]
At this writing, Gitorious.org is showing the following message: "Gitorious.org is migrating all the repositories to [Internet Archive](https://archive.org/)."

**Comment by DomT4** [comment]
Yeah, they're offline at the moment. Going to leave the current remaining HEADs in place for now - They should start working again soon, and nobody has filed an issue complaining yet.

**Comment by DomT4** [comment]
Wrapped up the last few transitions. Closing here. Thanks for working on this @L2G :beer:
