### ISSUE TITLE
sdl_mixer: "Error: parent directory is world writable but not sticky"

### ISSUE THREAD

**Issue by khouli** [Homebrew/homebrew#39170]
When I tried to install sdl_mixer homebrew gave an error message and asked me to report it.

https://gist.github.com/khouli/c9fff492e49b83ca4bc1

**Comment by jacknagel** [comment]
What are the permissions on `/tmp`? e.g.

```
$ ls -ld /tmp
lrwxr-xr-x@ 1 root  wheel  11 Oct 16  2014 /tmp -> private/tmp
$ ls -ld /private/tmp
drwxrwxrwt  6 root  wheel  204 Apr 27 19:52 /private/tmp
```

**Comment by khouli** [comment]
$ ls -ld /tmp
    lrwxr-xr-x@ 1 root  wheel  11 Oct 22  2014 /tmp -> private/tmp
    $ ls -ld /private/tmp
    drwxrwxrwx  61 root  wheel  2074 Apr 29 03:32 /private/tmp/

Just ask for whatever else might help, thanks.

**Comment by edbentinck** [comment]
I just received the same error trying to install Tidy HTML. Below are my permissions:

    $ ls -ld /tmp
    lrwxr-xr-x@ 1 root  wheel  11 28 Jan 17:46 /tmp -> private/tmp
    $ ls -ld /private/tmp
    drwxrwxrwx  17 root  wheel  578 29 Apr 04:07 /private/tmp

**Comment by jacknagel** [comment]
I wonder if a recent OS X update broke this? In any case, you can either restore the sticky bit manually as is shown above, or repair permissions using disk utility.

**Comment by jacknagel** [comment]
On a related note, I would like to change the default temporary directory from `/tmp` to `Dir.tmpdir` , which will respect the per-user `$TMPDIR` used on OS X.

https://github.com/Homebrew/homebrew/blob/b0bbe3ecd3a969e479cd6c337840db1955aa3b2b/Library/Homebrew/global.rb#L70

 That would resolve this issue as well, though it seems pretty bad that `/private/tmp` lost the sticky bit.

**Comment by khouli** [comment]
Setting the sticky bit on /private/tmp manually worked.

**Comment by ascooper57** [comment]
Hello Jack,

First of all, thank you. You were correct. sudo chmod +t /private/tmp/ fixed my issue. Odd since I use brew quite often:

ls /usr/local/Cellar

ant		berkeley-db	gettext		libtasn1	mysql		node		openssl		pkg-config	pwgen		rpm		tomcat
awscli		gawk		icu4c		libtool		neon		nspr		ossp-uuid	popt		python		rpm2cpio	wget
beecrypt	gdbm		libmagic	mongodb		nmap		nss		pcre		postgresql	readline	sqlite		xz

**Comment by RoomArchitect** [comment]
$ sudo chmod +t /private/tmp/     


good!
