### ISSUE TITLE
Php53 failed to build on 10.9.5

### ISSUE THREAD

**Issue by Etroid** [Homebrew/homebrew#39188]
System: MAC OS X 10.9.5
Homebrew: 0.9.5
XCode: 6.2

Getting an error when executing "brew install php53 --without-apache --with-fpm --with-intl --with-xdebug"

Installing PHP CLI binary:        /usr/local/Cellar/php53/5.3.29/bin/
cp: /usr/local/Cellar/php53/5.3.29/bin/#INST@42658#: No such file or directory
make: *** [install-cli] Error 1

More information can be found here:
<a href="https://gist.github.com/3550beca6fefdcfd7b19">https://gist.github.com/3550beca6fefdcfd7b19</a>

**Comment by mikemcquaid** [comment]
This issue was moved to Homebrew/homebrew-php#1694
