### ISSUE TITLE
MongoDB installation fails: parent directory is world writable but not sticky

### ISSUE THREAD

**Issue by immo-huneke-zuhlke** [Homebrew/homebrew#39182]
See also https://gist.github.com/7ea27dbc46faf2ad3232

$ brew install mongodb --with-openssl
==> Downloading https://fastdl.mongodb.org/src/mongodb-src-r3.0.2.tar.gz
######################################################################## 100.0%
==> Cloning https://github.com/mongodb/mongo-tools.git
Cloning into '/Library/Caches/Homebrew/mongodb--github.com-mongodb-mongo-tools--git'...
remote: Counting objects: 1167, done.
remote: Compressing objects: 100% (931/931), done.
remote: Total 1167 (delta 189), reused 804 (delta 143), pack-reused 0
Receiving objects: 100% (1167/1167), 1.81 MiB | 632.00 KiB/s, done.
Resolving deltas: 100% (189/189), done.
Checking connectivity... done.
Note: checking out 'a914adfcea7d76f07512415eec5cd8308e67318e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

==> Checking out tag r3.0.2
==> ./build.sh ssl
==> /usr/local/opt/scons/bin/scons install --prefix=/usr/local/Cellar/mongodb/3.
Error: parent directory is world writable but not sticky
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:481:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:184:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:165:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `install'
/usr/local/Library/brew.rb:140:in `<main>'
$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 6763ef1ff1e694befd7275222928cf0ab9f1b0c4
Last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.10.3-x86_64
Xcode: N/A
CLT: 6.3.1.0.1.1429149539
Clang: 6.1 build 602
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.8.0_45
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some directories in /usr/local/share/man aren't writable.
This can happen if you "sudo make install" software that isn't managed
by Homebrew. If a brew tries to add locale information to one of these
directories, then the install will fail during the link step.
You should probably `chown` them:

    /usr/local/share/man/man3

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libecomlodr.dylib

**Comment by immo-huneke-zuhlke** [comment]
Solved by running Mac OS X's Disk Utility to repair permissions on the main hard drive.

**Comment by lucke84** [comment]
Repairing permission with Disk Utility worked for me too, thanks!
