### ISSUE TITLE
Rate limit error message

### ISSUE THREAD

**Issue by mrjbq7** [Homebrew/homebrew#39214]
This error message on rate limits:

```
Error: GitHub API rate limit exceeded...
Try again in 26 minutes 4 seconds, or create an API token:
  https://github.com/settings/applications
and then set HOMEBREW_GITHUB_API_TOKEN.
```

Might be improved by suggesting that GitHub users can generate personal access tokens on this URL (with default permissions):

https://github.com/settings/tokens

Rather than registering new applications...

**Comment by mikemcquaid** [comment]
Good idea, fixed!
