### ISSUE TITLE
Please do not version bump the nimrod formula.

### ISSUE THREAD

**Issue by philip-wernersbach** [Homebrew/homebrew#39217]
I'd like to ask the Homebrew maintainers to not version bump the [nimrod formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/nimrod.rb) for now. The upstream Windows installer now packages [nimble](https://github.com/nim-lang/nimble), so we have to figure out how to package that with our formula. There is at least one [upstream issue](https://github.com/nim-lang/nimble/issues/80) that may be blocking this.

@Araq and @dom96: How should we proceed?

**Comment by philip-wernersbach** [comment]
#39272 updated the nimrod formula to 0.11.2, but the issue of not packaging nimble with nim still stands. Need guidance from upstream.

Also, I've updated the title to reflect the current status of the nimrod formula, but apparently I can't reopen the issue.

**Comment by philip-wernersbach** [comment]
Ping @Araq and @dom96

**Comment by dom96** [comment]
I'm not familiar with how Homebrew operates but I think that Nimble should be a separate formula.

**Comment by philip-wernersbach** [comment]
Thanks for the quick response @dom96. How can we accomplish that, with regards to nim-lang/nimble#80?

**Comment by dom96** [comment]
I suppose I will need to implement https://github.com/nim-lang/nimble/issues/80.

**Comment by Araq** [comment]
I have no idea what it takes to package Nimble on "Homebrew" and I have no opinion either.
