### ISSUE TITLE
Updating ICU4C to v55.1 Seems to Break Composer

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew#39221]
I tried to run Composer in order to update the PHP dependencies of my local copy of MediaWiki after I updated ICU4C to version 55.1 using Homebrew, but all I got upon doing so was the following error message:  
```
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.54.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
/usr/local/bin/composer: line 3: 12526 Trace/BPT trap: 5       /usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/composer/1.0.0-alpha10/libexec/composer.phar "$@"
```
What does this mean, and what do I do about it?

**Comment by DomT4** [comment]
Tell Homebrew-php to revision their ` php ` formula, by the looks of it.

**Comment by RandomDSdevel** [comment]
Right, will do.

**Comment by RandomDSdevel** [comment]
Looks like they may have noticed this already!
