### ISSUE TITLE
saltstack (HEAD) failed to test

### ISSUE THREAD

**Issue by ykomatsu** [Homebrew/homebrew#39236]
Since saltstack/salt@dfd606a36558046dc39d5d22d0f8d90dd24d9978 saltstack (HEAD) failed to test.

    % brew test --HEAD saltstack
    Testing saltstack
    ==> /usr/local/Cellar/saltstack/HEAD/bin/salt --version
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 673, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: tornado>=4.0
    Error: saltstack: failed
    Failed executing: /usr/local/Cellar/saltstack/HEAD/bin/salt --version
    /usr/local/Library/Homebrew/formula.rb:843:in `block in system'
    /usr/local/Library/Homebrew/formula.rb:800:in `open'
    /usr/local/Library/Homebrew/formula.rb:800:in `system'
    /usr/local/Library/Formula/saltstack.rb:115:in `block in <class:Saltstack>'
    /usr/local/Library/Homebrew/formula.rb:743:in `block in run_test'
    /usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
    /usr/local/Library/Homebrew/formula.rb:739:in `run_test'
    /usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
    /usr/local/Library/Homebrew/test.rb:27:in `<main>'

**Comment by jacknagel** [comment]
Closing in favor of the pull request.
