### ISSUE TITLE
Formula for slap

### ISSUE THREAD

**Issue by secrettriangle** [Homebrew/homebrew#39249]
Please add a formula for slap-editor/slap. The [install script](https://github.com/slap-editor/slap/blob/master/install.sh#L15-L17) is brew-aware so this formula might be as easy as simply running the install script.

**Comment by DomT4** [comment]
Fancy creating a PR? [Formula Cookbook is here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md), there's an example of using `npm install` inside a formula [here](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/tegh.rb). New formulae should ensure no issues are raised by ` brew audit --strict `.

> The install script is brew-aware so this formula might be as easy as simply running the install script.

It won't be `brew` aware inside Homebrew. Homebrew hides the `bin` directory from formulae, only selectively giving access to certain stated dependencies. Using `npm install` will be necessary (But actually easier to deal with).

**Comment by tdsmith** [comment]
We don't really take requests but we'll be happy to review a pull request. We often discourage self-submits, especially for new projects, but I'm convinced that slap meets our notability requirements. Thanks!
