### ISSUE TITLE
Should luarocks-5.2 get symlinked as luarocks like lua-5.2 is symlinked as lua?

### ISSUE THREAD

**Issue by hanleybrand** [Homebrew/homebrew#39247]
I just installed lua for the first time to check it out, and was surprised when `luarocks install moonscript` didn't work because, well,  to be brief I knew I hadn't installed lua with the --without-luarocks flag because I read the directions sometimes, so i expected luarocks to be installed with lua by the formula. 

After some brief going around I found that it was installed, just as luarocks-5.2. So no big deal, but I thought I would mention it since the formula symlinks lua-5.2 as lua, and it would make sense to also create the luarocks symlink 

Actually, from reading over https://github.com/Homebrew/homebrew/blob/master/Library/Formula/lua.rb it looks like it's supposed to be, but at least on my system it didn't (I'll stick my terminal output below - no error generated for the test, even though the test seems to use luarocks as a command (which should be failing on my machine)

```bash
$ brew install lua
==> Downloading https://homebrew.bintray.com/bottles/lua-5.2.3_2.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring lua-5.2.3_2.yosemite.bottle.tar.gz
==> Caveats
Please be aware due to the way Luarocks is designed any binaries installed
via Luarocks-5.2 AND 5.1 will overwrite each other in /usr/local/bin.

This is, for now, unavoidable. If this is troublesome for you, you can build
rocks with the `--tree=` command to a special, non-conflicting location and
then add that to your `$PATH`.

If you have existing Rocks trees in $HOME, you will need to migrate them to the new
location manually. You will only have to do this once.
==> Summary
🍺  /usr/local/Cellar/lua/5.2.3_2: 77 files, 1.0M
$ luarocks install moonscript
-bash: luarocks: command not found
$ brew info luarocks
Error: No available formula for luarocks 
$ ls -al /usr/local/Cellar/lua/5.2.3_2/bin
total 128
drwxr-xr-x  10     340 Apr 20 10:21 .
drwxr-xr-x   9     306 May  1 11:52 ..
-r-xr-xr-x   1   19936 May  1 11:52 lua
lrwxr-xr-x   1      37 Apr 20 10:21 lua-5.2 -> /usr/local/Cellar/lua/5.2.3_2/bin/lua
lrwxr-xr-x   1      37 Apr 20 10:21 lua5.2 -> /usr/local/Cellar/lua/5.2.3_2/bin/lua
-r-xr-xr-x   1   18788 May  1 11:52 luac
lrwxr-xr-x   1      38 Apr 20 10:21 luac-5.2 -> /usr/local/Cellar/lua/5.2.3_2/bin/luac
lrwxr-xr-x   1      38 Apr 20 10:21 luac5.2 -> /usr/local/Cellar/lua/5.2.3_2/bin/luac
lrwxr-xr-x   1      27 Apr 20 10:21 luarocks-5.2 -> ../libexec/bin/luarocks-5.2
lrwxr-xr-x   1      33 Apr 20 10:21 luarocks-admin-5.2 -> ../libexec/bin/luarocks-admin-5.2
```

**Comment by DomT4** [comment]
We symlink the Python pip's as `pip` and `pip3` and we're using roughly the same method for Luarocks these days, so it's a valid point & use case.

Feel free to open a PR that does something like this:

```diff
  bin.install_symlink libexec/"bin/luarocks-5.2"
  bin.install_symlink libexec/"bin/luarocks-admin-5.2"
+ bin.install_symlink libexec/"bin/luarocks" => "luarocks"
+ bin.install_symlink libexec/"bin/luarocks-admin" => "luarocks-admin"
```

**Comment by hanleybrand** [comment]
Ah ok - I haven't done much ruby, but it seems like a easy first stab into a PR.

**Comment by DomT4** [comment]
Great! Feel free to ping if you have any questions.
