### ISSUE TITLE
libvpx 1.4.0 Tigerbrew

### ISSUE THREAD

**Issue by roadtechy** [Homebrew/homebrew#39263]
Hello,

I am having an issue installing the libvpx formula.  I've tried the brew sh option as well.  Any help is greatly appreciated.

Thanks,
Cevin 

Detailed information follows:

System Info:
----------
brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/mistydemeo/tigerbrew.git
HEAD: 752436e19a81f824712662ab39a50a6a1adab5a4
Last commit: 3 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: single-core 32-bit g4
OS X: 10.4.11-Power Macintosh
Xcode: 2.5
CLT: N/A
GCC-4.0: build 5370
Clang: N/A
X11: N/A
System Ruby: 1.8.2 => /usr/bin/ruby
Perl: /usr/bin/perl
Python: /usr/bin/python => /System/Library/Frameworks/Python.framework/Versions/2.3/bin/python
Ruby: /usr/bin/ruby
Java: N/A

----------
brew doctor
Your system is ready to brew.

----------
brew --env
CC: gcc-4.2
CXX: g++-4.2
OBJC: gcc-4.2
OBJCXX: g++-4.2
CFLAGS: -Os -w -pipe -mcpu=7400 -faltivec -mmacosx-version-min=10.4
CXXFLAGS: -Os -w -pipe -mcpu=7400 -faltivec -mmacosx-version-min=10.4
LDFLAGS: -L/usr/local/lib -Wl,-headerpad_max_install_names
MAKEFLAGS: -j1
MACOSX_DEPLOYMENT_TARGET: 10.4
PKG_CONFIG_LIBDIR: /usr/local/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.4:/usr/lib/pkgconfig
PATH: /usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/Library/ENV/scm:/usr/local/Library/ENV/scm
CPATH: /usr/local/include

##------##

Errors:

----------
Download & Install of libvpx:

brew install libvpx
==> Downloading https://github.com/webmproject/libvpx/archive/v1.4.0.tar.gz
######################################################################## 100.0%
==> ../configure --prefix=/usr/local/Cellar/libvpx/1.4.0 --enable-pic --disable-
==> make install

make install

../libs.mk:273: *** missing `endif'.  Stop.
make: *** [.DEFAULT] Error 2
shell-init: could not get current directory: getcwd: cannot access parent directories: No such file or directory
Error: No such file or directory - /usr/sbin/pkgutil

----------
Second attempt to install libvpx:

brew install libvpx
==> Downloading https://github.com/webmproject/libvpx/archive/v1.4.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/libvpx-1.4.0.tar.gz
==> ../configure --prefix=/usr/local/Cellar/libvpx/1.4.0 --enable-pic --disable-
==> make install

make install

../libs.mk:273: *** missing `endif'.  Stop.
make: *** [.DEFAULT] Error 2
shell-init: could not get current directory: getcwd: cannot access parent directories: No such file or directory
Error: No such file or directory - /usr/sbin/pkgutil

----------

brew sh
Your shell has been configured to use Tigerbrew's build environment:
this should help you build stuff. Notably though, the system versions of
gem and pip will ignore our configuration and insist on using the
environment they were built under (mostly). Sadly, scons will also
ignore our configuration.
When done, type `exit'.

brew install libvpx
==> Downloading https://github.com/webmproject/libvpx/archive/v1.4.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/libvpx-1.4.0.tar.gz
==> Verifying libvpx-1.4.0.tar.gz checksum
/usr/bin/tar xzf /Library/Caches/Homebrew/libvpx-1.4.0.tar.gz
==> ../configure --prefix=/usr/local/Cellar/libvpx/1.4.0 --enable-pic --disable-unit-tests --disable-examples
  enabling pic
  disabling unit_tests
  disabling examples
Configuring selected codecs
  enabling vp8_encoder
  enabling vp8_decoder
  enabling vp9_encoder
  enabling vp9_decoder
Configuring for target 'generic-gnu'
  enabling generic
  enabling webm_io
  enabling libyuv
Creating makefiles for generic-gnu libs
Creating makefiles for generic-gnu docs
==> make install
../libs.mk:273: *** missing `endif'.  Stop.
make: *** [.DEFAULT] Error 2
shell-init: could not get current directory: getcwd: cannot access parent directories: No such file or directory
Error: No such file or directory - /usr/sbin/pkgutil

----------

**Comment by DomT4** [comment]
Needs reporting [here](https://github.com/mistydemeo/tigerbrew).
