### ISSUE TITLE
audit command should catch `depends_on :autoconf` and `depends_on :automake`

### ISSUE THREAD

**Issue by L2G** [Homebrew/homebrew#39303]
Per <del>@tdsmith</del>, these dependencies are deprecated in favor of `depends_on "autoconf" => :build` and `depends_on "automake" => :build`. The `audit` command does not catch them, though.

**Comment by tdsmith** [comment]
(I'm not sure I said this but it sounds right to me!)

**Comment by L2G** [comment]
I could be wrong. _Someone_ had to tell me about this twice before it got through my thick head. :smile_cat:

**Comment by DomT4** [comment]
Threw together a proposal in #39322.

**Comment by L2G** [comment]
@DomT4 :+1: (with notes attached thereto).
