### ISSUE TITLE
Why does "brew diy" need a build system?

### ISSUE THREAD

**Issue by johnhawkinson** [Homebrew/homebrew#39302]
I wanted to "brew diy" a small package (agrep: https://github.com/Wikinaut/agrep) which uses neither configure nor CMake. "brew diy" raises an error:

    Error: Couldn't determine build system

Clearly because of this code in diy.rb:

    if File.file? "CMakeLists.txt"
      puts "-DCMAKE_INSTALL_PREFIX=#{prefix}"
    elsif File.file? "configure"
      puts "--prefix=#{prefix}"
    else
      raise "Couldn't determine build system"
    end

But why? In this "build system," I just want to copy the executable to /usr/local/Cellar/PROG/VER/bin/PROG by hand ,and then brew link it. Why does homebrew need to know anything about the build system to permit this? It feels wrong for me to mkdir directories in /usr/local/Cellar by hand -- ABSTRACTION VIOLATION.

In any event, workaround is "touch configure" :)

Thanks.

**Comment by jacknagel** [comment]
`brew diy` needs a build system because its output format is arguments for an autotools-alike configure script (`--prefix=<prefix path>`) or cmake `"-DCMAKE_INSTALL_PREFIX=<prefix path>"`.

In other words, it's meant to be used like:

```
$ ./configure --prefix=$(brew diy)
$ cmake $(brew diy)
```

> It feels wrong for me to mkdir directories in /usr/local/Cellar by hand -- ABSTRACTION VIOLATION.

On the contrary, the cellar structure was designed to make it easy for people to do things by hand.

**Comment by johnhawkinson** [comment]
I guess I'd like it to say

  "Please save your binary in /usr/local/cellar/PROG/VER/bin."

in the case of being unable to determine a build system. Maybe that's
too...simplistic?

**Comment by lewisbrown** [comment]
+1 for a different message. Must everyone with this issue google for this thread?

**Comment by mikemcquaid** [comment]
@lewisbrown Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
