### ISSUE TITLE
gnustep-make: update or boneyard?

### ISSUE THREAD

**Issue by L2G** [Homebrew/homebrew#39314]
I was updating gnustep-make—the formula for [GNUstep](http://gnustep.org/)'s Make utility—when I noticed that nothing else in core is depending on it, and it seems to be the lone GNUstep-related formula in core. So I wasn't sure if updating it from 2.6.2 to 2.6.6 would be worth the trouble, and maybe it'd be better off retired to the boneyard.

**Comment by tdsmith** [comment]
ref #14645

It doesn't bother me that it exists but it's probably not one of our most popular packages.

**Comment by DomT4** [comment]
Would prefer to keep it if it still works post-update (there's potential merit to :fire: a whole lot of formulae otherwise), but don't care about it that much.

**Comment by L2G** [comment]
All righty. Thanks for the input. See #39431.
