### ISSUE TITLE
prokka.rb failed to build on Mac OS 10.10.3

### ISSUE THREAD

**Issue by ajabrams** [Homebrew/homebrew#39335]
######################################################################## 100.0%
Error: /Library/Caches/Homebrew/Formula/prokka.rb:4: syntax error, unexpected '<'
<!DOCTYPE html>
 ^
/Library/Caches/Homebrew/Formula/prokka.rb:5: syntax error, unexpected '<'
<html lang="en" class="">
 ^
/Library/Caches/Homebrew/Formula/prokka.rb:5: syntax error, unexpected keyword_class, expecting end-of-input
<html lang="en" class="">
                     ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:151:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:140:in `<main>'

**Comment by mistydemeo** [comment]
It looks like you've downloaded an HTML file instead of the formula - maybe Github's web view of it?

The prokka formula is in the [homebrew/science](https://github.com/homebrew/homebrew-science) tap. Try:

```
brew install homebrew/science/prokka
```

**Comment by ajabrams** [comment]
Thanks for the help! It works!
