### ISSUE TITLE
libexosip 4.1.0 (in the works, having build problems)

### ISSUE THREAD

**Issue by L2G** [Homebrew/homebrew#39355]
I'm working on an upgrade to libexosip, partly to get `brew audit --strict` to pass, partly to upgrade it to version 4.1.0 in order to match up with its dependency, libosip.

https://github.com/Homebrew/homebrew/compare/master...L2G:formula/libexosip

**Comment by L2G** [comment]
For the record, here's what I'm running into:

https://gist.github.com/L2G/423b21593a5feea7b94d

**Comment by tdsmith** [comment]
Submitting this as a PR will make it easier to comment on.

Fix described here: http://growingshoot.blogspot.com/2013_02_01_archive.html

```
LDFLAGS="-framework CoreFoundation -framework CoreServices -framework Security" ./configure

CoreFoundation is for _CFRelease, CoreServices is for _Gestalt and Security for the others (keychain access).
```

This seems like a bug that should be submitted upstream, if you're willing.

**Comment by L2G** [comment]
I'm sorry. I thought it was poor form to submit a PR if I knew for a fact that it was broken.

**Comment by L2G** [comment]
Continued at #39433.

**Comment by xu-cheng** [comment]
FYI, you can use `hub` to turn issues to PR.

**Comment by L2G** [comment]
And if I don't want to, should I do it anyway?
