### ISSUE TITLE
Error Reinstalling Python

### ISSUE THREAD

**Issue by PatrickEGorman** [Homebrew/homebrew#39356]
I tried to reinstall python using Homebrew but got the following error:

dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /Users/patrickgorman/Envs/Rocktribe/bin/python2.7
  Reason: image not found

I've tried downloading and installing python again from the website but that doesn't seem to work.  Any ideas?

**Comment by tdsmith** [comment]
It looks like you're using a virtualenv. Does this persist after deactivating the virtualenv? You may need to recreate it.

**Comment by PatrickEGorman** [comment]
I've tried creating a new virtual environment and installing a new version of python on it but it didn't seem to work.  Am I doing something wrong?

**Comment by tdsmith** [comment]
Does `$(brew --prefix)/bin/python` launch the interpreter correctly?

I would need to know more about "it didn't seem to work" to help.

**Comment by PatrickEGorman** [comment]
I'm kind of new to working with homebrew so I'd appreciate it if you could give me a guide to using this command.

It seems to be basing all of my virtual environments off of one that is broken.  I've tried selecting a different version of python but it still gives me the same error.

**Comment by tdsmith** [comment]
Please open a terminal and type, exactly, `$(brew --prefix)/bin/python` and let me know what happens.

**Comment by PatrickEGorman** [comment]
-bash: syntax error near unexpected token `/bin/python'

**Comment by tdsmith** [comment]
That's an unusual output. Does `brew --prefix` print `/usr/local` (or wherever you installed Homebrew)?

**Comment by PatrickEGorman** [comment]
It does

**Comment by tdsmith** [comment]
If you run `/usr/local/bin/python`, does the interpreter work okay?

**Comment by PatrickEGorman** [comment]
This also works

**Comment by tdsmith** [comment]
That's good, thanks. I think that your issue is probably not Homebrew-related. If you need help with virtualenv, they have a list of contact avenues on [their documentation website](https://virtualenv.pypa.io/en/latest/).

**Comment by PatrickEGorman** [comment]
Sounds good!  Thanks for the help
