### ISSUE TITLE
ctags HEAD failed to patch on 10.10

### ISSUE THREAD

**Issue by naegelejd** [Homebrew/homebrew#39351]
One of the patches to `ctags` fails when installing the HEAD version. To reproduce, uninstall `ctags` as necessary and reinstall with `brew install --HEAD ctags`.

[Relevant gist](https://gist.github.com/naegelejd/45b50e0c0ca86334c073)

**Comment by tdsmith** [comment]
Ah, I see; since one of the patches was committed upstream, the patch needs to be split for the HEAD build to work.

**Comment by naegelejd** [comment]
Yep I see now. That's an easy fix. I'd be happy to submit a PR as needed.

**Comment by jacknagel** [comment]
Closing in favor of https://github.com/Homebrew/homebrew/pull/39358
