### ISSUE TITLE
brew install vim --with-lua  configure: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by An0nymous0** [Homebrew/homebrew#39369]
https://gist.github.com/anonymous/593e10301dea73688db4

configure: creating cache auto/config.cache
checking whether make sets $(MAKE)... yes
checking for gcc... /usr/bin/llvm-gcc
checking whether the C compiler works... no
configure: error: in `/private/tmp/vim20150505-5064-sl8md5/vim-7.4.712/src':
configure: error: C compiler cannot create executables
See `config.log' for more details

How to solve?

System:
os x 10.10.3 
xcode: 6.3.1 (6D1002)

Thanks!

**Comment by DomT4** [comment]
You seem to have a [custom compiler](https://gist.github.com/anonymous/593e10301dea73688db4#file-01-configure-L52-L55) installed which has overwritten the default symlink from `/usr/bin/llvm-gcc` to `/usr/bin/clang`.

**Comment by An0nymous0** [comment]
@DomT4 Thank you! How do I get it to cover the original？

**Comment by tdsmith** [comment]
You can try un-setting `$CC` with e.g. `unset CC`. To restore the original shims, you can reinstall OS X, borrow them from a friend's installation, or use a tool like Pacifist to recover them from the installation media.

**Comment by An0nymous0** [comment]
unless reinstall OS X ,No other solution？

**Comment by tdsmith** [comment]
You can copy them from another OS X machine but they are not available for download AFAIK.

**Comment by An0nymous0** [comment]
@tdsmith Thanks!
