### ISSUE TITLE
Jmeter links to an incorrect download link and fails to install

### ISSUE THREAD

**Issue by thorrsson** [Homebrew/homebrew#39364]
The formula uses:
https://www.apache.org/dyn/closer.cgi?path=jmeter/binaries/apache-jmeter-2.13.tgz

Which results in:

brew install jmeter
==> Downloading https://www.apache.org/dyn/closer.cgi?path=jmeter/binaries/apache-jmeter-2.13.tgz
Error: Failed to download resource "jmeter"
Download failed: Couldn't determine mirror, try again later.

This is not a valid download link, but any of the mirrors listed on that page are, editing the formula locally to use one of those works fine.

**Comment by DomT4** [comment]
Works fine here:

```
==> Downloading https://www.apache.org/dyn/closer.cgi?path=jmeter/binaries/apache-jmeter-2.13.tgz
==> Best Mirror http://apache.mirrors.spacedump.net/jmeter/binaries/apache-jmeter-2.13.tgz
######################################################################## 100.0%
Downloaded to: /usr/local/var/homebrew/cache/jmeter-2.13.tgz
```

Probably a local issue. The `dyn` path is Apache's geolocation URL - Fairly common across Apache formulae.

**Comment by thorrsson** [comment]
Odd, let me try it from where I am now... I'll update shortly

**Comment by thorrsson** [comment]
brew install jmeter
==> Downloading https://www.apache.org/dyn/closer.cgi?path=jmeter/binaries/apache-jmeter-2.13.tgz
==> Best Mirror http://apache.claz.org/jmeter/binaries/apache-jmeter-2.13.tgz
######################################################################## 100.0%
🍺  /usr/local/Cellar/jmeter/2.13: 1859 files, 82M, built in 9 seconds

Yup seems OK at home..
I'll check at the office again tomorrow
