### ISSUE TITLE
emacs-mac failed to build on 10.10.3

### ISSUE THREAD

**Issue by saghaulor** [Homebrew/homebrew#39365]
Installation logs can be found here: https://gist.github.com/222aabf2669c1cf58e92

**Comment by jacknagel** [comment]
>Formula: emacs-mac
Tap: railwaycat/homebrew-emacsmacport
Path: /usr/local/Library/Taps/railwaycat/homebrew-emacsmacport/Formula/emacs-mac.rb

Please report this to the above repo.

**Comment by saghaulor** [comment]
@jacknagel my bad, I thought that I done my due diligence but clearly I missed the fact that this wasn't part of the homebrew repo. Thank you for your time.

**Comment by saghaulor** [comment]
In the event that anyone else makes the same mistake that I made, the issue has already been reported here: https://github.com/railwaycat/homebrew-emacsmacport/issues/24
