### ISSUE TITLE
brew install apr fails

### ISSUE THREAD

**Issue by paxos1977** [Homebrew/homebrew#39362]
> Praxis:~ austirg$ brew install apr
> ==> Downloading http://www.apache.org/dyn/closer.cgi?path=apr/apr-1.5.1.tar.bz2
> ==> Best Mirror http://apache.mirrors.tds.net/apr/apr-1.5.1.tar.bz2

> curl: (22) The requested URL returned error: 404 Not Found
> Error: Failed to download resource "apr"
> Download failed: http://apache.mirrors.tds.net/apr/apr-1.5.1.tar.bz2

Pulling up the apache mirror in the browser shows the problem is 1.5.2 is out and 1.5.1 is not present on the mirror.

**Comment by tdsmith** [comment]
Thanks for the report! Could you try and open a pull request to bump the apr version? [This guide](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'll be happy to walk you through any questions you run in to, either here or on IRC.

**Comment by tenshibe** [comment]
I'm afraid this broke httpd24 for me. Removing httpd24 and reinstalling, some items still look in 1.5.1 directory for static libraries. Have removed apr, apr-utils, reinstalled them and then tried to install httpd24, build failed with "Cannot find the library `/usr/local/Cellar/apr/1.5.1/libexec/lib/libapr-1.la" Guess this is an issue in httpd24

**Comment by tenshibe** [comment]
Removing and reinstalling apr-util with --build-from-source fixed this for me, maybe a new bottle of apr-util built against apr should be provided as well ?

**Comment by DomT4** [comment]
Confirmed. Fixed in #39557.
