### ISSUE TITLE
Install all packages into user dir?

### ISSUE THREAD

**Issue by intel352** [Homebrew/homebrew#39367]
Our IT dept has locked down our computers, which is really messing up our ability to function as developers when we have app dependencies that are necessary to do our jobs...

Is it possible to configure brew to function completely out of a path relative to the user home directory?
Globally, not per-package?

**Comment by jacknagel** [comment]
You can install Homebrew anywhere (including your home directory): just `git clone` it omewhere. 

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Installation.md#alternative-installs

**Comment by intel352** [comment]
Thanks for that!
