### ISSUE TITLE
the HEAD for `fpp` is a 404

### ISSUE THREAD

**Issue by chdiza** [Homebrew/homebrew#39387]
`https://github.com/facebook/pathpicker` seems to not exist.

**Comment by jacknagel** [comment]
Known, it's not public yet. https://github.com/Homebrew/homebrew/pull/39324

**Comment by pcottle** [comment]
Yep sorry about this -- http://facebook.github.io/PathPicker/ works though. the repo will be public hopefully next week! This PR was one of our last blocking items
