### ISSUE TITLE
`brew install thrift --with-java` fails to install java libraries correctly

### ISSUE THREAD

**Issue by kalaxy** [Homebrew/homebrew#39397]
I recently tried to install thrift with java support.  And came across two issues. 
* Building `--with-java` requires ant.  So I suppose that needs to be added as a dependency for building the java support.
* `make install` installs java libraries directly to /usr/local/lib.  It looks like this is configurable by setting the `JAVA_PREFIX` env variable when calling configure.

**Comment by DomT4** [comment]
Will review a PR on this. Thanks!

**Comment by robertodormepoco** [comment]
please re-open this, we need the PR first, i've had the same issue as the OP and i was just lucky to search not only for open issue (0 results for thrift related), but also the closed once

**Comment by DomT4** [comment]
The issue was open for over 49 days and nobody else commented, or opened a PR. Reopening an issue that was ignored for ~50 days isn't going to guarantee it doesn't get ignored for another ~50 days.

If this is still an issue, someone needs to open a PR to resolve it.
