### ISSUE TITLE
gcc-4.9 has no link to gcc

### ISSUE THREAD

**Issue by francispoulin** [Homebrew/homebrew#39392]
Hello,

I am very new to homebrew and I have installed a bunch of compilers, for example gcc.  I noticed that it is called gcc-4.9 and there is no link for gcc.  I can create a link to it but as it updates I thought it might be convenient if homebrew does this automatically.  Is there a way to set this up?  If not I'll just manually link it in the future.

Thanks,
Francis

**Comment by tdsmith** [comment]
There is not; OS X installs a `/usr/bin/gcc` which is really clang and we want to avoid accidentally changing the compiler that builds outside Homebrew use. There was some discussion in #28855.
