### ISSUE TITLE
Text alignment issues after running `brew update && brew outdated`

### ISSUE THREAD

**Issue by mhart** [Homebrew/homebrew#39446]
Running in iTerm:

![screen shot 2015-05-06 at 1 39 02 pm](https://cloud.githubusercontent.com/assets/367936/7499398/5578f21a-f3f5-11e4-87f9-cf608e1ead1f.png)

Don't remember ever seeing this before?

**Comment by jacknagel** [comment]
I've seen something similar in the past, but I don't think we ever tracked it down. It may be an environment issue.

Let us know if it happens consistently.
