### ISSUE TITLE
activemq plist does not work

### ISSUE THREAD

**Issue by vegaed** [Homebrew/homebrew#39477]
Running brew services start activemq then ps -ax | grep activemq but active mq is not running.

**Comment by jacknagel** [comment]
We don't support `brew services` in this repository (see https://github.com/Homebrew/homebrew-services), but if you can suggest changes to the plist we can make them.

**Comment by vegaed** [comment]
So I manually did

ln -sfv /usr/local/opt/activemq/homebrew.mxcl.activemq.plist ~/Library/LaunchAgents/
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.activemq.plist
launchctl start homebrew.mxcl.activemq

and then I look for activemq to be started ( ps -ax | grep activemq ) and nothing is found. Am I doing something wrong or is it not working correctly?

**Comment by bobby** [comment]
I'm having a similar issue.  loading/unloading/starting the service via `/usr/local/opt/activemq/homebrew.mxcl.activemq.plist` and `launchd` don't seem to work.  I can run it fine via `activemq start`.

By changing the `.plist` file slightly to log stdout and stderr, as follows:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>homebrew.mxcl.activemq</string>
    <key>ProgramArguments</key>
    <array>
      <string>/usr/local/opt/activemq/bin/activemq</string>
      <string>start</string>
    </array>
    <key>StandardErrorPath</key>
    <string>/usr/local/var/log/activemq/error.log</string>
    <key>StandardOutPath</key>
    <string>/usr/local/var/log/activemq/output.log</string>
    <key>RunAtLoad</key>
    <true/>
  </dict>
</plist>
```

I see the following when I `cat /usr/local/var/log/activemq/output.log`:

```
INFO: Loading '/usr/local/Cellar/activemq/5.11.1/libexec/bin/env'
INFO: Using java '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java'
INFO: Starting - inspect logfiles specified in logging.properties and log4j.properties to get details
INFO: pidfile created : '/usr/local/Cellar/activemq/5.11.1/libexec/data/activemq.pid' (pid '25998')
```

So it looks like the JVM starts, logging initializes, and PID file is created (verified by `cat`-ing the pidfile to see that it matches the value logged above).  But then...nothing.  No error message, no stacktrace, no logging in the application logs.

Again, I can run the service just fine via `activemq start`.  Any ideas?

**Comment by sbglasius** [comment]
@bobby I have the same issue. Did you resolve this?

**Comment by bobby** [comment]
@sbglasius I did not resolve, am running via `activemq start` for now.

**Comment by mikemcquaid** [comment]
Maybe we should just remove the `plist` until someone can fix it or add a working version?

**Comment by dunn** [comment]
Went ahead and removed the plist; if anyone wants to open a PR for a fixed version that would be great!

**Comment by moraygrieve** [comment]
Isn't this related to the fact that the activemq script that starts the daemon, and then exists, so launchctl gets confused on what it's tracking - see http://stackoverflow.com/questions/18440575/mac-daemon-for-activemq

**Comment by dunn** [comment]
You'll want to change `/usr/local/Cellar/activemq/5.11.1/libexec` to `#{opt_libexec}` and `/usr/local/opt/activemq/bin/activemq` to `#{opt_bin}/activemq`, but if it works then we'd be very happy to take a PR!

**Comment by douglasjose** [comment]
I tested the solution suggested by @moraygrieve and it works. I reverted the original `plist` file instructions, adding the `AbandonProcessGroup=true` key and it worked without issues.

Submitted pull request https://github.com/Homebrew/homebrew-core/pull/2825.
