### ISSUE TITLE
different binaries for `brew install` depending on the availability of a bottle

### ISSUE THREAD

**Issue by Optiligence** [Homebrew/homebrew#39495]
If no bottle is available for a package, brew builds it from source with `march=native` – without mentioning it anywhere. 
Bottles are built for compatibility for a reason. 
For the sake of consistency `brew install` should create a default bottle if there’s none available or explicitly stress that the to-be-built package is only meant to be used on the current machine. 
I like the idea of default `march=native` for `--build-from-source` though.

**Comment by tdsmith** [comment]
The `--build-bottle` install option will generate portable bottles: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Bottles.md

Local installation (and not building for redistribution) is the driving use case.

**Comment by Optiligence** [comment]
We had one package which wasn’t pre-bottled and had to invest quiet a bit of time to figure out why it was built to not work on another machine because this behavior is __not even mentioned anywhere__. 
`--build-bottle` should be the default to be consistent with downloaded packages. 
Optimizing for the local machine is nice for explicit `--build-from-source`. 

Either way, it should be mentioned.

**Comment by tdsmith** [comment]
It's mentioned in the documentation I linked; where would you have liked to see it?

**Comment by Optiligence** [comment]
Where is it mentioned that `brew install` does create machine specific binaries different from a pre-packaged version when that is not available. 
Stating it after `brew install` is done would be reasonable too.

**Comment by jacknagel** [comment]
>We had one package which wasn’t pre-bottled and had to invest quiet a bit of time to figure out why it was built to not work on another machine because this behavior is not even mentioned anywhere. 

If you use `brew bottle` to create a portable package (which is the supported method of doing so), it will refuse to create the package if it wasn't installed with `--build-bottle`.

Even then, though, the packages are only meant to be portable across systems running the same version of OS X.

Just to set some expectations here, the default build settings aren't going to be changed.

**Comment by Optiligence** [comment]
I don’t want to create bottles though. I just want portable binaries. 

So here’s my expected workflow: 
`brew install` all dependencies → build application → collect libraries and deploy

And now that i know of this undocumented behavior, i have to check if there is a dependency which appears to be build from source and: 
interrupt/remove it → `brew install --build-bottle` instead
That’s reasonable? 

> Even then, though, the packages are only meant to be portable across systems running the same version of OS X.

Well, both machines where running Yosemite but only the deploy machine had AVX2 capability. 

> Just to set some expectations here, the default build settings aren't going to be changed.

Your decision… I’m just presenting some inconsistencies/issues here. If you think there’s no problem…

**Comment by tdsmith** [comment]
I would be happy to have the documentation (probably the FAQ) clarify that this use case is unsupported.

**Comment by Optiligence** [comment]
>that this use case is unsupported

Creating a package without having the user install homebrew? 
Sad to hear. 

>have the documentation (probably the FAQ) clarify

please go ahead

**Comment by mikemcquaid** [comment]
Closing this as we don't state that we support this and you should use `brew install --build-bottle` as mentioned. Will review a PR to update documentation,
