### ISSUE TITLE
Consider including clang-format.py in clang-format bottle

### ISSUE THREAD

**Issue by fasiha** [Homebrew/homebrew#39505]
The clang-format bottle, version 2015-04-21, installs binaries. 

Please consider including `clang-format.py` and `clang-format.el` (included with the Clang source download at llvm.org, under tools/clang-format) for vim and emacs interoperability, as advised by the [clang-format](http://clang.llvm.org/docs/ClangFormat.html) documentation.

**Comment by tdsmith** [comment]
Thanks for the report! Could you try and open a pull request? [This guide](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'll be happy to walk you through any questions you run in to, either here or on IRC.

**Comment by DomT4** [comment]
Status update?

**Comment by fasiha** [comment]
Sorry, I've been hoping to get to this but it's not been a priority 😖
