### ISSUE TITLE
terraform 0.5.0

### ISSUE THREAD

**Issue by number5** [Homebrew/homebrew#39516]
https://github.com/hashicorp/terraform/releases/tag/v0.5.0

Can anyone please update the formula?

I would like to do it myself and send in a PR but I have no idea how those bottles work.

Cheers,

**Comment by xu-cheng** [comment]
Could you try and open a pull request? This [document](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should be helpful. Thanks!

You can leave the bottle block as it is, it will be auto regenerated when a PR is merged.

**Comment by number5** [comment]
@xu-cheng pull request is ready to merge.
