### ISSUE TITLE
Gradle/JDK build from source support

### ISSUE THREAD

**Issue by smarek** [Homebrew/homebrew#39552]
Hello,

before commiting any effort to provide this, is Homebrew community interested in support of Java applications build from source (through maven,ant or gradle) if such tools are available locally and projects have support for automated builds ?

My idea is to detect, whether machine has capability of building Java projects (probing installed status and version of JDK), optionally checking availability of specific tools (such as [gradle](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gradle.rb), [maven](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/maven.rb), [ant](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ant.rb) and adding new section of Formula, that would be used for building from source when such environment is available.

There are already formulas that could use this support, see this [search](https://github.com/Homebrew/homebrew/search?utf8=%E2%9C%93&q=%22depends_on+%3Ajava%22&type=Code)

**Comment by jacknagel** [comment]
What would be the advantages? With natively-compiled projects, there are advantages to compiling for specific targets, but for Java projects I don't think that is relevant.

>adding new section of Formula, that would be used for building from source when such environment is available.

We would either want to choose a prebuilt install or source install, not both. So we wouldn't need to detect anything.

**Comment by DomT4** [comment]
Presuming interest has waned here.
