### ISSUE TITLE
boost 1.58 rebottling

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew#39568]
Some formulas were unbottled on Mountain Lion in #39323:

* [x] cpp-netlib http://bot.brew.sh/job/Homebrew%20Testing/838/
* [x] freeling http://bot.brew.sh/job/Homebrew%20Testing/839/
* [x] libswiften http://bot.brew.sh/job/Homebrew%20Testing/840/
* [x] points2grid http://bot.brew.sh/job/Homebrew%20Testing/841/
* [x] rcssserver http://bot.brew.sh/job/Homebrew%20Testing/842/

**Comment by DomT4** [comment]
`boost-python` never got a bottle added for any OS X version.

**Comment by tdsmith** [comment]
That's intentional pending resolution of #38738.

**Comment by DomT4** [comment]
Ah, thanks! Missed that issue.
