### ISSUE TITLE
Formula for Ghost?

### ISSUE THREAD

**Issue by andyboutte** [Homebrew/homebrew#39562]
Would a formula for Ghost be accepted into the repository? Or is Ghost outside the scope of homebrew?

https://ghost.org/

**Comment by DomT4** [comment]
Looks fine to me at least. It's a commercial product, but licensed under MIT with free source code availability, use and download. A formula that does a slight variation of their [Quick start install](https://github.com/TryGhost/Ghost#quick-start-install) should work well.

**Comment by tdsmith** [comment]
Would it be useful? Some blog tools like Wordpress would suck with Homebrew because Wordpress expects e.g. templates and media to be in the same directory tree as the Wordpress scripts. Keeping content in the Cellar is bad because it doesn't persist across upgrades. If it's easy to maintain ghost and the website it powers in separate directory trees, maybe it's worth doing. I can't think of anything like it in core at the moment.

**Comment by DomT4** [comment]
Looks like there's a fairly easily manipulated configuration file. We could inreplace [this method](http://support.ghost.org/config/#paths) to `var/"www"` or something?

**Comment by andyboutte** [comment]
I personally would use it regularly....but my use case does not include upgrades to Ghost.  I am regularly needing to test a Ghost feature or a theme and pull down a new copy of Ghost each time.  Currently I just use a bash script to handle all of this and I thought somebody else in the community could benefit from it.  

I like @DomT4 idea of storing the `content` directory outside of Ghost so we can manage upgrades.  

I will take a crack at writing this.  Does anybody have an objection to installing Ghost into `/var/www/ghost`?

**Comment by DomT4** [comment]
> Does anybody have an objection to installing Ghost into /var/www/ghost?

You shouldn't install Ghost into that prefix - At least not the executable and such. Only the content that we wouldn't want to destroy across updates. Using the standard config file but `inreplace` the `paths` element should work well.

I'd probably use `var/"ghost"` or something similar for now, `www` will clash with various servers and may raise complaints. Make sure you use `var/"ghost"` and not `/var/"ghost"` - Homebrew won't write to the latter.

**Comment by jacknagel** [comment]
I think the question to ask here is, will people want one single system-wide version of this for all of their sites, or might they have one site on version A and others on version B? If it's the latter, this probably isn't a good fit for core.

**Comment by DomT4** [comment]
Closing here. Happy to further review/discuss a PR if one is submitted. Thanks!
