### ISSUE TITLE
Updated ngrok formula available from Caskroom

### ISSUE THREAD

**Issue by joewiz** [Homebrew/homebrew#39573]
Having installed ngrok via homebrew a few months ago, I ran ngrok tonight again (v1.7) and noticed ngrok saying that an updated version was available from ngrok's website. Checking the website, I saw that v2.0 is available. I did a brew update but didn't see an updated formula for ngrok. 

Then I googled and noticed that ngrok is available from Caskroom: https://github.com/caskroom/homebrew-cask/blob/master/Casks/ngrok.rb. 

I uninstalled the original version, and then installed via Caskroom. This worked.

I'm not sure why ngrok was in caskroom and not here, but I figured I'd raise the issue that the latest formula for this app isn't in the main homebrew cask.

**Comment by xu-cheng** [comment]
Ngrok 2.x is not opensourced. Sorry, there is no thing we can do.

**Comment by joewiz** [comment]
Ah! Didn't realize this about ngrok. Thanks.

**Comment by Xavdidtheshadow** [comment]
It's worth noting that the ngrok readme says "The code for ngrok 2.0 is not yet open source." which means it possible that'll change.

**Comment by cbetta** [comment]
You can now install it using: `brew cask install ngrok`

**Comment by joewiz** [comment]
@cbetta Thanks for making that clear to everyone! Ngrok was available via Caskroom even when I filed the issue. My question was why it was relegated to Homebrew *Caskroom* rather than the regular Homebrew repository. Then @xu-cheng answered that by saying ngrok 2.x had to be in Caskroom since it's not open sourced - a requirement for projects in the regular Homebrew repository.

**Comment by cbetta** [comment]
Ah apologies. I just tried to make it easier for people trying to find ngrok in homebrew via google (that's how I ended up here) and missed that this was said at the start already.

**Comment by joewiz** [comment]
Super, thanks!

**Comment by thayneclark** [comment]
Awesome. Thanks @cbetta.

**Comment by ivancarrancho** [comment]
@cbetta. U're the fucking master!!! thanks for existing :)
