### ISSUE TITLE
Cleanup gtk relatived formulae test

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew#39584]
The tests of below formulae require serious fix. There are lots of redundant/incorrect arguments.

* [x] `gtk`
* [x] `gtk3`
* [x] `gtkmm`
* [x] `gtkmm3`
* [x] `glibmm`
* [x] `cairomm`
* [x] `atk`

@DomT4 can you help to fix it? (I would do it, but I'm not familiar to Gtk/x11) Thanks.

**Comment by xu-cheng** [comment]
A [tool](https://gist.github.com/xu-cheng/04a353ad7b5667e4f4fe) I just write should be help to cleanup these code.

**Comment by xu-cheng** [comment]
@tschoonj If possible, can you update these formulae as well? Thanks.

**Comment by tschoonj** [comment]
I will take care of it tomorrow or so. Thanks again for writing this great tool!

**Comment by DomT4** [comment]
Let me know if you still need any help, but if @tschoonj wants it I'm happy to not step on his toes.

**Comment by tschoonj** [comment]
all 7 packages have been updated but I expect them to fail building properly on the bot due to the same issue as in #39581

**Comment by tschoonj** [comment]
All are done.

Found one more problem with the script, mentioned it in #39578
