### ISSUE TITLE
Fix the updating process in android-sdk

### ISSUE THREAD

**Issue by 1zaman** [Homebrew/homebrew#39599]
The android-sdk formula currently stores it's downloaded resources in `#{prefix}/var/lib/android-sdk` by creating symlinks in the keg that point to the relevant directories there. However, it can't do that for updatable resource directories present at the top level such as platform-tools and docs, as the SDK Manager basically does an `rm -rf` on these before updating them, which would cause the symlink to be replaced by a new folder and all the files in the source folder to be deleted. Thus the formula currently requires these resources to be re-downloaded upon each upgrade. The build tools also seem to not be supported even though they don't face this issue as far as I know, possibly because no one updated the formula to handle them after their introduction in 2013.

The comment describing this issue in the formula suggests that we could create a wrapper script that calls the actual android tool, and repairs the directory structures when it exits. This seems to be a fragile solution though, and it would fail if the process was forcefully terminated.

My idea was that upon upgrading, we could hardlink all the files in these directories from the previous version of the keg. This would be a more expensive operation that just creating a directory symlink, but much cheaper than copying or downloading.

I am not too familiar with Homebrew conventions, or at all with Ruby development, so I am opening this issue to get further opinions on this. If no one else does this, I'll try to implement this myself in a few weeks when I get some time. I also have some further ideas about interoperability with the android-platform-tools formula (and potentially a future android-docs formula), and I might open an issue or pull request on that when this is resolved.

**Comment by jacknagel** [comment]
Unfortunately issues like this tend to get buried pretty fast. You might try soliciting feedback on the mailing list (homebrew@librelist.com). We certainly will welcome a pull request when you have time, though. Thanks for the information!
