### ISSUE TITLE
SHA1 mismatch on two-lame dependency

### ISSUE THREAD

**Issue by oschrenk** [Homebrew/homebrew#39606]
The formula is downloading an html page from sourceforge instead of the actual archive.

```
brew install two-lame
==> Downloading https://downloads.sourceforge.net/twolame/twolame-0.3.13.tar.gz
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: 3ca460472c2f6eeedad70291d8e37da88b64eb8b
Actual: e87bcd23d32a79e0afc164b614aaed9ae6b1b4f0
Archive: /Library/Caches/Homebrew/two-lame-0.3.13.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by jacknagel** [comment]
Working here:

```
$ brew fetch two-lame -f
==> Downloading https://downloads.sourceforge.net/twolame/twolame-0.3.13.tar.gz
######################################################################## 100.0%
Downloaded to: /Library/Caches/Homebrew/two-lame-0.3.13.tar.gz
SHA1: 3ca460472c2f6eeedad70291d8e37da88b64eb8b
SHA256: 98f332f48951f47f23f70fd0379463aff7d7fb26f07e1e24e42ddef22cc6112a
```

Run `brew fetch --force two-lame` to clear the cache and re-download.

If the issue persists, it's a problem on sourceforge's side.

**Comment by oschrenk** [comment]
Ugh. I have 

```
referer = ";auto"
```

in `.curlrc`. I never had problems but it seems that this settings breaks a few source download urls like

```
https://downloads.sourceforge.net/twolame/twolame-0.3.13.tar.gz
````

It works with this type of url though

```
 'https://downloads.sourceforge.net/project/twolame/twolame/0.3.13/twolame-0.3.13.tar.gz
````

Let's have a look in the library

```
cd /usr/local/Library/Formula
grep -R sourceforge * | grep -v "#" | grep url | wc -l
623

grep -R sourceforge * | grep -v "#" | grep url | grep "net/pr" | wc -l
535

grep -R sourceforge * | grep -v "#" | grep url | grep -v "net/pr" | wc -l
88
```

So it seems that I wouldn't be able to install around 88 formulas. Let's try `brew install ttf2pt1`. Jup. Also fails with the offending `.curlrc` line.

Seeing that `brew doctor` warns about having a `.curlrc` file, I removed the setting for now.

**Comment by DomT4** [comment]
Closing on this because there's nothing actionable on the Homebrew side sadly; the various issues with `.curlrc` files are well known.
