### ISSUE TITLE
Building exact-image failed with freetype/libagg dependency

### ISSUE THREAD

**Issue by hanxue** [Homebrew/homebrew#39622]
When building `exact-image` with `free-type`, I see this error

```
lib/vectorial.cc:44:10: fatal error: 'agg_font_freetype.h' file not found
#include "agg_font_freetype.h"
         ^
1 error generated.
make: *** [objdir/lib/vectorial.o] Error 1
make: *** Waiting for unfinished jobs....
```

Searching through `/usr/local/Cellar/libagg/2.5`, I cannot find the file `agg_font_freetype.h`

Gist logs at https://gist.github.com/hanxue/b695940e1ffd99c58d34

**Comment by alistairmcmillan** [comment]
The dependency libagg also has a --with-freetype option. If you tell libagg to build with that option then the `agg_font_freetype.h` file is created in `/usr/local/Cellar/libagg/2.5/include/agg2` and the build of exact-image continues past the compilation of vectorial.cc. This is a simple change to exact-image.rb:

    -  depends_on "libagg"
    +  depends_on "libagg" => 'with-freetype'

However that option is only needed if you are specifying the `--with-freetype` option on exact-image. I'm not sure if it is possible to tell brew "build libagg with freetype only if we are building exact-image with freetype". Someone more experienced should be able to answer that question.

However once you are over that hurdle, the build then fails with a completely different set of issues.

    codecs/png.cc:74:39: error: use of undeclared identifier 'png_infopp_NULL'
        png_destroy_read_struct(&png_ptr, png_infopp_NULL, png_infopp_NULL);
                                          ^
    codecs/png.cc:74:56: error: use of undeclared identifier 'png_infopp_NULL'
        png_destroy_read_struct(&png_ptr, png_infopp_NULL, png_infopp_NULL);
                                                           ^
    codecs/png.cc:85:50: error: use of undeclared identifier 'png_infopp_NULL'
        png_destroy_read_struct(&png_ptr, &info_ptr, png_infopp_NULL);
                                                     ^
    codecs/png.cc:102:20: error: use of undeclared identifier 'int_p_NULL'
                    &interlace_type, int_p_NULL, int_p_NULL);
                                     ^
    codecs/png.cc:102:32: error: use of undeclared identifier 'int_p_NULL'
                    &interlace_type, int_p_NULL, int_p_NULL);
                                                 ^
    codecs/png.cc:107:23: error: member access into incomplete type 'png_info' (aka 'png_info_def')
      image.spp = info_ptr->channels;
                          ^
    /usr/local/include/png.h:598:16: note: forward declaration of 'png_info_def'
    typedef struct png_info_def png_info;
                   ^
    codecs/png.cc:126:17: error: member access into incomplete type 'png_info' (aka 'png_info_def')
        if (info_ptr->num_trans)
                    ^
    /usr/local/include/png.h:598:16: note: forward declaration of 'png_info_def'
    typedef struct png_info_def png_info;
                   ^
    codecs/png.cc:199:44: error: use of undeclared identifier 'png_bytepp_NULL'
          png_read_rows(png_ptr, row_pointers, png_bytepp_NULL, 1);
                                               ^
    codecs/png.cc:203:48: error: use of undeclared identifier 'png_infopp_NULL'
      png_destroy_read_struct(&png_ptr, &info_ptr, png_infopp_NULL);
                                                   ^
    codecs/png.cc:227:40: error: use of undeclared identifier 'png_infopp_NULL'
        png_destroy_write_struct(&png_ptr, png_infopp_NULL);
                                           ^
    codecs/png.cc:242:13: error: use of undeclared identifier 'Z_BEST_COMPRESSION'
      quality = Z_BEST_COMPRESSION * (quality + Z_BEST_COMPRESSION) / 100;
                ^
    codecs/png.cc:242:45: error: use of undeclared identifier 'Z_BEST_COMPRESSION'
      quality = Z_BEST_COMPRESSION * (quality + Z_BEST_COMPRESSION) / 100;
                                                ^
    codecs/png.cc:244:22: error: use of undeclared identifier 'Z_BEST_COMPRESSION'
      else if (quality > Z_BEST_COMPRESSION) quality = Z_BEST_COMPRESSION;
                         ^
    codecs/png.cc:244:52: error: use of undeclared identifier 'Z_BEST_COMPRESSION'
      else if (quality > Z_BEST_COMPRESSION) quality = Z_BEST_COMPRESSION;
                                                       ^
    codecs/png.cc:247:3: error: use of undeclared identifier 'png_info_init'
      png_info_init (info_ptr);
      ^
    15 errors generated.

Based on the use of `png_info_init()` exact-image seems to have been developed against older versions of libpng and hasn't been updated for newer versions like the current 1.6 where "png_info_init" and related were deprecated. You can see [here](https://sourceforge.net/projects/libpng/files/OldFiles/libpng-stable/1.2.7rc1/) mention of png_info_init being ifdef'd out in 1996 and then removed in beta versions in 2006. I'm not sure what the long term solution is here. Ask the maintainers of exact-image to update the code to talk to a more recent version of libpng?

**Comment by alistairmcmillan** [comment]
Someone has posted a gist that might have the changes request to allow exact-image to build against current versions of libpng. I haven't tested this though. :)

https://gist.github.com/royshil/7752114

**Comment by DomT4** [comment]
Would review a PR here.
