### ISSUE TITLE
Heroku Toolbelt suddenly ignores Ruby in Rbenv install

### ISSUE THREAD

**Issue by liquid** [Homebrew/homebrew#39649]
bd6736040508f10846971d83826b8a4c30412225 introduces a change in behaviour on my machine where Ruby is in fact available, only via Rbenv. This used to work without having to install Ruby via a Brew formula.

See my brew conf in the gist: https://gist.github.com/liquid/26dfdd539f0e3a3c174c

Thank you for your help in advance and let me know if I can somehow help debugging the issue.

**Comment by xu-cheng** [comment]
What's the output of following commends? 
```
which ruby
ruby --version 2>/dev/null
````

**Comment by liquid** [comment]
```
➜ ~ (home) which ruby
/usr/local/var/rbenv/shims/ruby
➜ ~ (home) ruby --version 2>/dev/null
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
```

@xu-cheng ^^

**Comment by xu-cheng** [comment]
It's not related to requirement but to bottle. So question is why the requirement's default formula will be installed when pouring bottle? cc @tdsmith @jacknagel

**Comment by DomT4** [comment]
I thought bottles were always built against the default formula? So it'd be necessary to install the default formula to use the bottle?

**Comment by xu-cheng** [comment]
Actually I was thinking that can we be more distinguishable on the requirement of default formula. Like checking the whether bottle has fixed linkage?

**Comment by DomT4** [comment]
As in if there's no dynamic linkage actually present in the bottle, don't require the default formula to install/use the bottle? Interesting notion. We already look through keg contents to look for system OpenSSL linkage amongst other checks so it wouldn't be an unprecedented probe.

Presumably we'd have to check the correct Ruby version existed on the machine before pouring the bottle, but the requirement may already be doing that (?).

**Comment by tdsmith** [comment]
I think it would be hard to know what the package is memorizing about its dependency in addition to linkage -- paths, versions, capabilities? I'm sure there are cases where it doesn't matter.

**Comment by mikemcquaid** [comment]
Ugh, yeh, my bad here. Thanks for the fix.
