### ISSUE TITLE
fzf missing /usr/local/Cellar/fzf/HEAD/shell/completion.zsh

### ISSUE THREAD

**Issue by slhck** [Homebrew/homebrew#39669]
I installed fzf with

    brew install fzf --HEAD
    /usr/local/Cellar/fzf/HEAD/install

When reloading Zsh, I get:

    /Users/werner/.fzf.zsh:source:15: no such file or directory: /usr/local/Cellar/fzf/HEAD/shell/completion.zsh

Indeed, the file is not there. 

Shouldn't there be a

```rb
(prefix/"shell").install "shell/completion.zsh"
```

in [the formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/fzf.rb#L41)?

**Comment by slhck** [comment]
I guess this patch should fix it — I unfortunately have no time to fork/create a PR now.

```
diff --git a/Library/Formula/fzf.rb b/Library/Formula/fzf.rb
index 0c9b757..f33ae68 100644
--- a/Library/Formula/fzf.rb
+++ b/Library/Formula/fzf.rb
@@ -38,7 +38,7 @@ class Fzf < Formula

     prefix.install %w[install uninstall LICENSE]
     (prefix/"shell").install %w[bash zsh fish].map { |s| "shell/key-bindings.#{s}" }
-    (prefix/"shell").install "shell/completion.bash"
+    (prefix/"shell").install %w[bash zsh].map { |s| "shell/completion.#{s}" }
     (prefix/"plugin").install "plugin/fzf.vim"
     man1.install "man/man1/fzf.1"
     bin.install "bin/fzf-tmux"
```

**Comment by junegunn** [comment]
@slhck Hi, I'm the maintainer of fzf. Unfortunately the patch alone will cause an error during non-HEAD installation, and I'll have to release a new version and make a PR. I'll let you know of the progress.

**Comment by JikkuJose** [comment]
Am getting this issue with version `0.10.0`; This is what I get when I source my `zshrc`:

`/Users/jikkujose/.fzf.zsh:source:19: no such file or directory: /usr/local/Cellar/fzf/0.9.12/shell/key-bindings.zsh`

**Comment by DomT4** [comment]
@JikkuJose I think your issue is just that the version was updated and now the version your source is referencing doesn't exist. Should be fixed in https://github.com/Homebrew/homebrew/commit/0695316fc25b5bd7d6e5b586d0b32b1d62183fa3, if you tweak your local lines accordingly.
