### ISSUE TITLE
audit should warn about deprecated_option's

### ISSUE THREAD

**Issue by scpeters** [Homebrew/homebrew#39672]
The ability to propagate `deprecated_option`'s via the `depends_on` tag was recently fixed (#38069) thanks to efficient work by @jacknagel . I just noticed that if a formula depends on another formula with deprecated options, then `brew audit` will not recognize those options:

~~~
$ brew tap scpeters/bug
$ brew audit child_deprecated
child_deprecated:
 * Dependency parent does not define option "option"

Error: 1 problems in 1 formulae
~~~

It should probably provide a warning that deprecated options are being used, but currently it just doesn't recognize them as valid options at all.

**Comment by jacknagel** [comment]
IMO the current warning is sufficient. It indicates to the user that they need to double check this option in the "parent" formula, at which time they will see that the option has been deprecated. So I don't think we need to separate the two cases.

**Comment by jacknagel** [comment]
I also think the complexity it would introduce in the audit code is probably not worth it (it's more involved than the other fix).

**Comment by scpeters** [comment]
Sounds reasonable.
