### ISSUE TITLE
Cannot install formula since mktmpdir can't cleanup dir with leftover socket file.

### ISSUE THREAD

**Issue by yesimon** [Homebrew/homebrew#39691]
I think this change is the culprit: https://github.com/Homebrew/homebrew/commit/9c928a431b5945ed8c9e82e257119a71e54ca667

I'm not a ruby programmer so I'll defer the most idiomatic solution for this cleanup.

Also in this case as a temporary workaround I should just checkout an older commit?

```
yesimon@node1748:~/idi$ brew install ack -d
/idi/sabeti-scratch/yesimon/linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /idi/sabeti-scratch/yesimon/linuxbrew/Library/Formula/ack.rb
/idi/sabeti-scratch/yesimon/linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /idi/sabeti-scratch/yesimon/linuxbrew/Library/Formula/glibc.rb
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /idi/sabeti-scratch/yesimon/linuxbrew/Library/Formula/ack.rb
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /idi/sabeti-scratch/yesimon/linuxbrew/Library/Formula/glibc.rb
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /idi/sabeti-scratch/yesimon/linuxbrew/Library/Formula/gcc.rb
Error: Directory not empty @ dir_s_rmdir - /idi/sabeti-scratch/yesimon/tmp/homebrew20150512-8939-rj66hr
/idi/sabeti-scratch/yesimon/linuxbrew/Cellar/ruby/2.2.1/lib/ruby/2.2.0/fileutils.rb:1444:in `rmdir'
/idi/sabeti-scratch/yesimon/linuxbrew/Cellar/ruby/2.2.1/lib/ruby/2.2.0/fileutils.rb:1444:in `block in remove_dir1'
/idi/sabeti-scratch/yesimon/linuxbrew/Cellar/ruby/2.2.1/lib/ruby/2.2.0/fileutils.rb:1455:in `platform_support'
/idi/sabeti-scratch/yesimon/linuxbrew/Cellar/ruby/2.2.1/lib/ruby/2.2.0/fileutils.rb:1443:in `remove_dir1'
/idi/sabeti-scratch/yesimon/linuxbrew/Cellar/ruby/2.2.1/lib/ruby/2.2.0/fileutils.rb:1436:in `remove'
/idi/sabeti-scratch/yesimon/linuxbrew/Cellar/ruby/2.2.1/lib/ruby/2.2.0/fileutils.rb:778:in `block in remove_entry'
/idi/sabeti-scratch/yesimon/linuxbrew/Cellar/ruby/2.2.1/lib/ruby/2.2.0/fileutils.rb:1493:in `postorder_traverse'
/idi/sabeti-scratch/yesimon/linuxbrew/Cellar/ruby/2.2.1/lib/ruby/2.2.0/fileutils.rb:776:in `remove_entry'
/idi/sabeti-scratch/yesimon/linuxbrew/Cellar/ruby/2.2.1/lib/ruby/2.2.0/tmpdir.rb:94:in `ensure in mktmpdir'
/idi/sabeti-scratch/yesimon/linuxbrew/Cellar/ruby/2.2.1/lib/ruby/2.2.0/tmpdir.rb:94:in `mktmpdir'
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/formula_installer.rb:488:in `build'
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/formula_installer.rb:190:in `install'
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/cmd/install.rb:165:in `install_formula'
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/cmd/install.rb:83:in `block in install'
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/cmd/install.rb:83:in `each'
/idi/sabeti-scratch/yesimon/linuxbrew/Library/Homebrew/cmd/install.rb:83:in `install'
/idi/sabeti-scratch/yesimon/linuxbrew/Library/brew.rb:140:in `<main>'
```

**Comment by DomT4** [comment]
This isn't causing any ill-effects on OS X, so you'll need to report this to [Linuxbrew](https://github.com/Homebrew/linuxbrew). Jack may still do something to tweak it, but usually Linuxbrew-exclusive issues need to be punted there.

**Comment by chdiza** [comment]
I did not understand why there are all these Linuxbrew problems being reported to us.  But then I looked at their repo, where their troubleshooting links often point people here.  I entered a bug report [there](https://github.com/Homebrew/linuxbrew/issues/401).

**Comment by yesimon** [comment]
I don't think it's correct on homebrew necessarily. Looking at Ruby 2.2
docs (http://ruby-doc.org/stdlib-2.2.1/libdoc/socket/rdoc/UNIXServer.html),
there is no promise that `UNIXServer` will delete the socket file on close.
Just "because it works" on OS X doesn't necessarily mean that it's correct
and won't break in the future.

In general I would appreciate it if issues weren't automatically dismissed
out of hand just because they came from linuxbrew.

**Comment by chdiza** [comment]
> In general I would appreciate it if issues weren't automatically dismissed out of hand just because they came from linuxbrew.

It wasn't dismissed out of hand.  It was dismissed because @DomT4 couldn't reproduce it on a Mac.

**Comment by jacknagel** [comment]
We aren't depending on UNIXSocket to clean up the socket file. We are depending on the [documented behavior of `Dir.mktmpdir` when given a block](http://ruby-doc.org/stdlib-2.2.0/libdoc/tmpdir/rdoc/Dir.html#method-c-mktmpdir), which is to remove the temporary directory and its contents, which in this case includes the socket.

If this doesn't work, then it needs to be reported elsewhere.

**Comment by yesimon** [comment]
No, you are depending on OS X specific implementation of UNIX sockets where sockets are not files, and as such are deleted once the socket is closed, for example:
```
srwxr-xr-x  1 simon  wheel     0B Apr  9 17:59 /tmp/fish.simon/fishd.socket
```

On linux sockets have inodes so the user is responsible for cleaning them up. Furthermore, ruby's test suite does manual cleanup of sockets in tmpdirs, and that's the way `safe_fork` in homebrew did it previously. Is it that bad to do it?

**Comment by jacknagel** [comment]
>where sockets are not files, and as such are deleted once the socket is closed

```rb
$ irb
irb(main):001:0> require "socket"
=> true
irb(main):002:0> UNIXServer.open("/tmp/socket") { }
=> nil
irb(main):003:0> File.exist? "/tmp/socket"
=> true
```

**Comment by yesimon** [comment]
Wow I was so wrong that it's not even funny.

The real problem was that I'm using an NFS filesystem for my `HOMEBREW_TEMP`. Ruby recursively deletes every file in a directory with a postorder traversal. In the case of the `socket` file, it left behind a `.nfsXXXX...` file since the fd was not closed. (https://uisapp2.iu.edu/confluence-prd/pages/viewpage.action?pageId=123962105). Later on in the postorder traversal, `Dir.rmdir` fails because the directory is not empty - indeed it has an `.nfs` file in it. To fix this, I added `socket.close()` to `safe_fork` so there were no hanging fds during tmpdir's cleanup.

Indeed this is actually a homebrew bug, but you need to have `HOMEBREW_TEMP` on an NFS mount to reproduce it.

**Comment by jacknagel** [comment]
I still don't understand. `UNIXServer.open` with a block closes the socket before the returning (that's the point of the block form), so it should not leak a file descriptor.

```
$ irb
irb(main):001:0> require "socket"
=> true
irb(main):002:0> UNIXServer.open("/tmp/socket") { |s| s }.closed?
=> true
irb(main):003:0>
```

Where is the fd leak?

**Comment by jacknagel** [comment]
Oh, now I see, [this](https://github.com/Homebrew/homebrew/blob/d4c470b478b5e06f27758624f5ff5ec4c1f7bf01/Library/Homebrew/utils/fork.rb#L28) is what is leaked.
