### ISSUE TITLE
Suggestion: Overridable HOMEBREW_PREFIX

### ISSUE THREAD

**Issue by dcrodman** [Homebrew/homebrew#39696]
It wouldn't surprise me if this has been requested before, but I think that there are legitimate use cases for formulas to not want to install to /usr/local. For example, source installations of larger toolchains will often have you set the prefix to something within /usr/local (go, mysql, etc.) for various reasons. It would also be really useful for environment bootstrapping for groups/companies/whatever that use specific versions of tools that aren't present in the Homebrew core or Versions repository.

In my case, I'm writing a handful of Formulas that I'd like to be able to keep in /usr/local/company to avoid version conflicts with the core Formulas and allow software to make assumptions about the locations of libraries and tools. I get the argument for sticking to /usr/local, but I have to be able to override HOMEBREW_PREFIX either way so I thought I'd see if it were a feature useful outside of what we're trying to do.

**Comment by jacknagel** [comment]
A single Homebrew installation won't handle multiple prefixes for a variety of reasons. But you can just install Homebrew itself in a different location (i.e. in `$HOME`) and then invoke that `brew` instead when you want to install to the alternate location.

**Comment by dcrodman** [comment]
I was going to ask if there is a better or preexisting way to do this, you beat me to it. Thanks!
