### ISSUE TITLE
Cowardly refusing to 'sudo brew install'

### ISSUE THREAD

**Issue by hwbrill** [Homebrew/homebrew#39701]
https://gist.github.com/hwbrill/bb2808d34933df26339e

$ sudo brew install openssl
Error: Cowardly refusing to `sudo brew install`
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.

**Comment by DomT4** [comment]
Homebrew doesn't use or need `sudo`, see the [FAQ](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md#why-does-homebrew-say-sudo-is-bad-). You can force Homebrew to use `sudo` if you really want, but it isn't advised.

**Comment by tdsmith** [comment]
Let us know if we can help with anything.

**Comment by tdsmith** [comment]
Just in case it isn't clear, you should just run `brew install openssl` as your logged-in user; you shouldn't use su or sudo.

**Comment by hwbrill** [comment]
Yesterday, I tried it without sudo and it returned the same Error; then I tried it with sudo having the same result.  I am following the install instruction given to install the spark-cli... please refer to:
https://github.com/spark/spark-cli/blob/master/README.md#installing-on-mac-os-x
Today, after receiving your reply (thanks DomT4 and tdsmith), I ran the brew install openssl and I got this result:
Herbs-iMac:~ hwbrill$ brew install openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2a-1.yosemite.b
######################################################################## 100.0%
==> Pouring openssl-1.0.2a-1.yosemite.bottle.1.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2a-1: 463 files, 18M

What the Heck?!  I've been trying to install this since last Friday...  Can anyone explain what the heck happened?

**Comment by DomT4** [comment]
I'm not sure why `spark-cli` are instructing users to use `sudo` when it isn't supported here. It may be worth asking them what the desired end result of that instruction is.

I'm not sure why it wouldn't have worked before now (the `brew install openssl` command), does `brew doctor` say anything?

**Comment by jacknagel** [comment]
https://github.com/spark/spark-cli/pull/193

**Comment by hwbrill** [comment]
Herbs-iMac:~ hwbrill$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:

  /Library/Frameworks/Python.framework/Versions/2.7/bin/python-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/node/android-ifaddrs.h
    /usr/local/include/node/ares.h
    /usr/local/include/node/ares_version.h
    /usr/local/include/node/libplatform/libplatform.h
    /usr/local/include/node/nameser.h
    /usr/local/include/node/node.h
    /usr/local/include/node/node_buffer.h
    /usr/local/include/node/node_internals.h
    /usr/local/include/node/node_object_wrap.h
    /usr/local/include/node/node_version.h
    /usr/local/include/node/openssl/opensslconf.h
    /usr/local/include/node/pthread-fixes.h
    /usr/local/include/node/smalloc.h
    /usr/local/include/node/stdint-msvc2008.h
    /usr/local/include/node/tree.h
    /usr/local/include/node/uv-aix.h
    /usr/local/include/node/uv-bsd.h
    /usr/local/include/node/uv-darwin.h
    /usr/local/include/node/uv-errno.h
    /usr/local/include/node/uv-linux.h
    /usr/local/include/node/uv-sunos.h
    /usr/local/include/node/uv-threadpool.h
    /usr/local/include/node/uv-unix.h
    /usr/local/include/node/uv-version.h
    /usr/local/include/node/uv-win.h
    /usr/local/include/node/uv.h
    /usr/local/include/node/v8-debug.h
    /usr/local/include/node/v8-platform.h
    /usr/local/include/node/v8-profiler.h
    /usr/local/include/node/v8-testing.h
    /usr/local/include/node/v8-util.h
    /usr/local/include/node/v8.h
    /usr/local/include/node/v8config.h
    /usr/local/include/node/v8stdint.h
    /usr/local/include/node/zconf.h
    /usr/local/include/node/zlib.h
Herbs-iMac:~ hwbrill$

**Comment by jacknagel** [comment]
Can you clarify which issues you are still having? Based on the output you provided, openssl was installed successfully.

**Comment by DomT4** [comment]
From the `brew doctor` output there's nothing unexpectedly bad. Node can cause permissions issues for itself, but otherwise there's nothing bad there for Homebrew's permissions. Unless you encounter further issues, you're probably safe to not worry about it.

**Comment by hwbrill** [comment]
Thanks guys!  I'm new in using this process... old Control Systems Integrator/Engineer trying to get up to date on new application development.  I'm used to Microsoft DOS/Windows OS's and just now using Mac OS X Terminal.  A lot to learn fast, multitasking, App Development, Spark Device and GitHub...  I appreciate the help...
