### ISSUE TITLE
Arping is not recognized after install with Brew

### ISSUE THREAD

**Issue by maparker21** [Homebrew/homebrew#39713]
I used homebrew to install the arping package (brew install arping), and it appeared to install as expected. However, when attempting to execute an arping command it outputs the following:

-bash: arping: command not found

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by DomT4** [comment]
`arping` is installed in the `sbin` and you may not have that in your `$PATH`.

**Comment by jacknagel** [comment]
Make sure to add `$(brew --prefix)/sbin` to your path. `brew doctor` will warn about this, and there will be a post-install warning once https://github.com/Homebrew/homebrew/issues/37040 is fixed.
