### ISSUE TITLE
Sleuth kit should not require java but does...

### ISSUE THREAD

**Issue by sean925** [Homebrew/homebrew#39715]
I might be missing something, but sleuthkit should only require java if you want to be able to call bindings from a java program. Unfortunately it seems the current scripts to install it default to requiring java to install. I have successfully compiled sleuthkit manually by running ./configure with the built-in option --disable-java. Is there a way to add this option to brew's interface?

**Comment by bfontaine** [comment]
How did you see it requires Java? `brew deps` doesn’t show it:

```
$ brew deps sleuthkit
afflib
ant
autoconf
automake
expat
libewf
libtool
makedepend
openssl
pkg-config
xz
```

**Comment by sean925** [comment]
When I try to install on my machine without java installed, I get errors related to not having java. It seems sleuth kit builds with Java bindings by default, for use with Autopsy I believe, even though it does not say it is a dependency. Below is the output I get.

$ brew install sleuthkit 
==> Installing sleuthkit dependency: ant
==> Downloading https://www.apache.org/dyn/closer.cgi?path=ant/binaries/apache-ant-1.9.4-bin.tar.bz2
==> Best Mirror http://mirrors.gigenet.com/apache/ant/binaries/apache-ant-1.9.4-bin.tar.bz2
######################################################################## 100.0%
🍺  /usr/local/Cellar/ant/1.9.4: 1597 files, 39M, built in 5 seconds
==> Installing sleuthkit
==> Downloading https://downloads.sourceforge.net/project/sleuthkit/sleuthkit/4.1.3/sleuthkit-4.1.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/sleuthkit-4.1.3.tar.gz
==> Downloading https://github.com/sleuthkit/sleuthkit/commit/39c62d6d169f8723c821ca7decdb8e124e126782.diff
Already downloaded: /Library/Caches/Homebrew/sleuthkit--patch-9da053e839ef8c4a454ac2f4f80b368884ff959c.diff
==> Patching
patching file bindings/java/ivy.xml
patching file bindings/java/ivysettings.xml
==> ./configure --prefix=/usr/local/Cellar/sleuthkit/4.1.3
checking for kaffe... no
checking for java... java
checking for uudecode... yes
checking if uudecode can decode base 64 file... yes
checking if java works... configure: error: The Java VM java failed (see config.log, check the CLASSPATH?)

**Comment by mikemcquaid** [comment]
Yeh, looks like it needs a `depends_on :java` I guess.

**Comment by sean925** [comment]
The configure file takes a option labeled --disable-java. Can this be integrated into the extra options for brew? This should allow people the ability to install without java.

**Comment by sean925** [comment]
For example the we could use the command:
$brew install sleuthkit --disable-java

**Comment by bfontaine** [comment]
Yes Homebrew supports options like that, but from my tests passing `--disable-java` isn’t sufficient if you have Java installed. Even with this flag it builds the bindings if Java is installed, but it doesn’t fail if it’s not.
