### ISSUE TITLE
undefined method `to_sym' for nil:NilClass on 10.9.4

### ISSUE THREAD

**Issue by evanniedojadlo** [Homebrew/homebrew#39727]
I was originally attempting to update my version of Git using homebrew on this laptop which runs 10.9.4 and returned several warnings, one of them being: 

Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours, this is a long time in brewland!
To update Homebrew, run `brew update`.

From here, I followed the instructions and attempted to run a brew update within my projects directory but returned the following error:

warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 1101 and retry the command.
Error: undefined method `to_sym' for nil:NilClass
Please report this bug:
    https://github.com/mxcl/homebrew/wiki/troubleshooting
/usr/local/Library/Homebrew/cmd/update.rb:103:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:101:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:101:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:23:in `update'
/usr/local/Library/brew.rb:95:in `send'
/usr/local/Library/brew.rb:95

In the meantime I am going to update my OS to the latest version of OS X and try again, let me know if any further information is required

**Comment by mikemcquaid** [comment]
Try to just run `brew update` again.

**Comment by evanniedojadlo** [comment]
@mikemcquaid Thanks, it took two tries but this has resolved the issue.

end result:

brew update
Already up-to-date.
