### ISSUE TITLE
expand yara.rb formula by building and installing yara-python

### ISSUE THREAD

**Issue by frbapolkosnik** [Homebrew/homebrew#39724]
Please see the notes about building and installing yara-python at:
http://yara.readthedocs.org/en/latest/gettingstarted.html#compiling-and-installing-yara

The reason why I'm asking is that yara-python is actually present in the source code of yara, and having the versions of yara and yara-python at the same version is pretty important.
Also, yara-python depends on the yara library built in the yara formula.

**Comment by jacknagel** [comment]
Closing in favor of the pull request; note that pull requests are also issues.
