### ISSUE TITLE
Error when running brew doctor

### ISSUE THREAD

**Issue by medullaskyline** [Homebrew/homebrew#39738]
Error: cannot load such file -- requirements/unsigned_kext_requirement
		Please report this bug:
		    https://github.com/Homebrew/homebrew/wiki/troubleshooting
		/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
		/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
		/usr/local/Library/Homebrew/requirements.rb:9:in `<top (required)>'
		/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
		/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
		/usr/local/Library/Homebrew/dependency_collector.rb:4:in `<top (required)>'
		/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
		/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
		/usr/local/Library/Homebrew/software_spec.rb:7:in `<top (required)>'
		/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
		/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
		/usr/local/Library/Homebrew/formula.rb:9:in `<top (required)>'
		/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
		/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
		/usr/local/Library/Homebrew/cmd/missing.rb:1:in `<top (required)>'
		/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
		/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
		/usr/local/Library/Homebrew/cmd/doctor.rb:1:in `<top (required)>'
		/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
		/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
		/usr/local/Library/brew.rb:59:in `require?'
		/usr/local/Library/brew.rb:118:in `<main>'

**Comment by DomT4** [comment]
A local modification to the repository seems a likely cause. `git fetch; git reset --hard origin/master` may resolve the issue, at your own risk.
