### ISSUE TITLE
pwgen Error: parent directory is world writable but not sticky

### ISSUE THREAD

**Issue by ascooper57** [Homebrew/homebrew#39735]
$ uname -a
Darwin MBP.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
$ brew update
Already up-to-date.
$ brew doctor
Your system is ready to brew.
$ brew install pwgen 
==> Downloading https://downloads.sourceforge.net/project/pwgen/pwgen/2.07/pwgen-2.07.tar.gz
Already downloaded: /Library/Caches/Homebrew/pwgen-2.07.tar.gz
==> ./configure --prefix=/usr/local/Cellar/pwgen/2.07 --mandir=/usr/local/Cellar/pwgen/2.07/share/man
==> make install
Error: parent directory is world writable but not sticky
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:482:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:184:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:165:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `install'
/usr/local/Library/brew.rb:140:in `<main>'

**Comment by DomT4** [comment]
See #39170.

**Comment by jacknagel** [comment]
We should add a doctor check to ensure that if HOMEBREW_TEMP is world writable it is also sticky, and if it isn't then we should recommend the user repair permissions with disk utility.

**Comment by DomT4** [comment]
I presume we can't use the actual Ruby `world_writable` method since it doesn't exist on anything prior to the 1.9.x releases?

**Comment by ascooper57** [comment]
It would be great if brew doctor checked for this condition. However the
error message itself was ambiguous to me. When it said that the parent
directory was not sticky, I thought it referred to /usr/local/Cellar/ where
pwgen was being installed, not /private/tmp/

Alan S. Cooper
<http://www.linkedin.com/in/ascooper1>

**Comment by jacknagel** [comment]
The error message is generated by Ruby's tmpdir standard library rather than Homebrew.

@DomT4, the following should work:

```rb
world_writable = HOMEBREW_TEMP.stat.mode & 0777 == 0777
```

**Comment by DomT4** [comment]
@jacknagel Thanks. Just finished testing locally. PR coming up.

**Comment by DomT4** [comment]
#39739
