### ISSUE TITLE
Problem with Postinstall

### ISSUE THREAD

**Issue by troytully** [Homebrew/homebrew#39770]
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/cmd/postinstall.rb:18:in `run_post_install'
/usr/local/Library/Homebrew/cmd/postinstall.rb:5:in `block in postinstall'
/usr/local/Library/Homebrew/cmd/postinstall.rb:5:in `each'
/usr/local/Library/Homebrew/cmd/postinstall.rb:5:in `postinstall'
/usr/local/Library/brew.rb:140:in `<main>'

**Comment by jacknagel** [comment]
You didn't post what the actual error is (it would have been above the stack trace).
