### ISSUE TITLE
Node 0.12.3

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew#39780]
It'll end up being submitted as a PR at some point if I don't stick this here. There's a new Node out, `0.12.3`, but it contains an undeclared breaking change to `v8`.

I've been holding off teeing up a PR whilst waiting to see what the Node team do, whether there'll be a quick fix/release, etc. They've stuck a high priority on the issue and are moving quickly on it.

General request that we don't merge the new Node version until upstream have a fix for the breakage. It seems likely that if we merge it sans fix we'll end up getting hit with Node issues that aren't actually Homebrew's issues and we'll have to revert.

References:
* https://github.com/joyent/node/issues/25324
* https://github.com/joyent/node/pull/25328

**Comment by jrnewell** [comment]
It looks like 0.12.4 is out with the breakage fix.

**Comment by DomT4** [comment]
Aye, they merged the V8 fix last night :tada:. There's a PR pending in #39825 for the previous version, I've asked the owner of that PR to rebase and rebump.
