### ISSUE TITLE
ledger does not build

### ISSUE THREAD

**Issue by gcv** [Homebrew/homebrew#39793]
Errors:

    $ brew install ledger
    ==> Downloading https://github.com/ledger/ledger/archive/v3.1.tar.gz
    Already downloaded: /Library/Caches/Homebrew/ledger-3.1.tar.gz
    ==> Downloading https://github.com/ledger/ledger/commit/5f08e27.diff
    Already downloaded: /Library/Caches/Homebrew/ledger--patch-064b0e64d211224455511cd7b82736bb26e444c3af3b64936bec1501ed14c547.diff
    ==> Patching
    patching file CMakeLists.txt
    Hunk #1 succeeded at 216 (offset -9 lines).
    ==> Downloading https://downloads.sourceforge.net/project/utfcpp/utf8cpp_2x/Release%202.3.4/utf8_v2_3_4.zip
    Already downloaded: /Library/Caches/Homebrew/ledger--utfcpp-2.3.4.zip
    ==> Downloading https://downloads.sourceforge.net/project/utfcpp/utf8cpp_2x/Release%202.3.4/utf8_v2_3_4.zip
    Already downloaded: /Library/Caches/Homebrew/ledger--utfcpp-2.3.4.zip
    ==> ./acprep opt make --jobs=4 --output=build --prefix=/opt/brew/Cellar/ledger/3.1 --boost=/opt/brew/opt/boost --python -- -DB
    ^Z
    [1]  + 46336 suspended  brew install ledger
    [athena:/opt/brew git:master] fg
    [1]  + 46336 continued  brew install ledger
    make[2]: *** [src/CMakeFiles/libledger.dir/stats.cc.o] Error 1
    make[2]: *** [src/CMakeFiles/libledger.dir/convert.cc.o] Error 1
    make[1]: *** [src/CMakeFiles/libledger.dir/all] Error 2
    make: *** [all] Error 2
    acprep: ERROR: Execution failed: make -j4

Looking a little deeper:

    /private/tmp/ledger20150515-46357-3qimm3/ledger-3.1$ ./acprep opt make --jobs=4 --output=build --prefix=/opt/brew/Cellar/ledger/3.1 --boost=/opt/brew/opt/boost --python -- -DB
    acprep: INFO: Invoking primary phase: make
    acprep: INFO: Executing phase: make
    acprep: INFO: Executing phase: config
    acprep: INFO: Executing phase: submodule
    acprep: INFO: Executing phase: configure
    acprep: INFO: System type is => Darwin
    acprep: INFO: Setting up build flavor => opt
    [  1%] [  2%] [  4%] [  5%] Building CXX object src/CMakeFiles/libledger.dir/stats.cc.o
    Building CXX object src/CMakeFiles/libledger.dir/csv.cc.o
    Building CXX object src/CMakeFiles/libledger.dir/generate.cc.o
    Building CXX object src/CMakeFiles/libledger.dir/convert.cc.o
    The build-tool has reset ENV. --env=std required.
    make[2]: *** [src/CMakeFiles/libledger.dir/stats.cc.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    The build-tool has reset ENV. --env=std required.
    make[2]: *** [src/CMakeFiles/libledger.dir/csv.cc.o] Error 1
    The build-tool has reset ENV. --env=std required.
    make[2]: *** [src/CMakeFiles/libledger.dir/generate.cc.o] Error 1
    The build-tool has reset ENV. --env=std required.
    make[2]: *** [src/CMakeFiles/libledger.dir/convert.cc.o] Error 1
    make[1]: *** [src/CMakeFiles/libledger.dir/all] Error 2
    make: *** [all] Error 2
    acprep: ERROR: Execution failed: make -j4

I do *not* use `/usr/local` for brew, I use `/opt/brew` instead. Not sure if this is relevant to this problem.

**Comment by gcv** [comment]
This might be related to the new version of Boost (1.58.0)?

**Comment by tdsmith** [comment]
It is, yes. There's a fix in #39571 I need to apply.

**Comment by gcv** [comment]
Thanks, @tdsmith. Installing ledger worked with your patched formula.
