### ISSUE TITLE
Building subversion fails

### ISSUE THREAD

**Issue by fraserphysics** [Homebrew/homebrew#39796]
This is my first "contribution" here and on github.  I am working without root or sudo.  I discovered linuxbrew this week and I hope it will enable me to build and use newer tools.  I've installed a few formulas, but "brew install subversion" dies with an error from scons as it tries to build subversion-1.8.13.

I ran brew gist-logs subversion and got https://gist.github.com/anonymous/2ea475ed31127471917d which tells the story that I see in my terminal.

**Comment by jacknagel** [comment]
Please report linux issues to https://github.com/Homebrew/linuxbrew. Thanks!
