### ISSUE TITLE
[formula request] CopyQ

### ISSUE THREAD

**Issue by a-b** [Homebrew/homebrew#39804]
I'd love to see formula for http://hluk.github.io/CopyQ/

Thanks!

**Comment by xu-cheng** [comment]
Could you try and open a pull request? This [document](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should be helpful. Thanks!

**Comment by DomT4** [comment]
Closing per the above. Will happily review a PR.
