### ISSUE TITLE
Transparent redirect handling HTTPS->HTTP, CURL, Homebrew core

### ISSUE THREAD

**Issue by smarek** [Homebrew/homebrew#39822]
Hi,

I noticed today, upgrading `glib` new version was to be fetched from `https://download.gnome.org/sources/glib/2.44/glib-2.44.1.tar.xz` (notice HTTPS) however the it's just a proxy to load balancing servers, and request was redirected to `http://ftp.acc.umu.se/pub/GNOME/sources/glib/2.44/glib-2.44.1.tar.xz` (notice HTTP)

I don't think, this information should be invisible to user, can you make the CURL downloads log redirects so it's clear to user, from which final location the file was fetched?

I know the archives are verified by locally stored SHA256 sum, however still the way redirects are handled is not nice to user (and especially to power-users / admins / developers / ...)

**Comment by DomT4** [comment]
Lol. Track the 120 comment PR ongoing in #38835.

**Comment by smarek** [comment]
Ok, thank you very much. Closing this one.
