### ISSUE TITLE
npm man pages don't install properly

### ISSUE THREAD

**Issue by diroussel** [Homebrew/homebrew#39823]
I just installed node via homebrew, and no man pages are avaiable.  I have node 0.12.2_1 installed, and I can see a mention of some man logic in /usr/local/Library/Formula/node.rb, but when I run `man npm`, I get "No manual entry for npm".  

So since #35969 was fixed the issue has been reintroduced.

I can see that some symlinks have been created:
```
~ $ ls -l /usr/local/Cellar/node/0.12.2_1/libexec/npm/share/man/man1/npm-update.1
lrwxr-xr-x  1 dave  admin  86 15 May 17:19 /usr/local/Cellar/node/0.12.2_1/libexec/npm/share/man/man1/npm-update.1 -> /private/tmp/node20150515-11777-1a99bv9/node-v0.12.2/npm_install/man/man1/npm-update.1

~ $ ls -l /private/tmp/node20150515-11777-1a99bv9/node-v0.12.2/npm_install/man/man1/npm-update.1
ls: /private/tmp/node20150515-11777-1a99bv9/node-v0.12.2/npm_install/man/man1/npm-update.1: No such file or directory
```

So the symlinks are there, but ulimately the don't point at any real files. 

homebrew git version is 00ff327dc0bf0312cedec3ac8a0eccdf8edef2ff

brew gist log
* node: https://gist.github.com/2e96ba07f8645a41426e
* npm: https://gist.github.com/067da389f05657a5aaa2

**Comment by diroussel** [comment]
Strangly the gist log is showing "--without-npm", but I didn't choose that option myself, and npm was installed by brew as a consquence of "brew install node".

```
~ $ history | grep "brew install"
brew install node --with-openssl
brew install mongodb
brew install tmux
brew install ansible
```

**Comment by DomT4** [comment]
> Strangly the gist log is showing "--without-npm"

This is just passed because we don't want to install the `npm` that ships with Node. We ship an `npm` tarball and use that instead - It gives us better control, which in turn allows us to prevent Node randomly breaking quite so often :wink:.

> I get "No manual entry for npm".

I can't reproduce this, nor your odd symlinking problem. Can you do `brew gist-logs node`, Thanks!

**Comment by DomT4** [comment]
Whoops, I can't read. You already did the `gist-logs`. Thanks :smile_cat:.

**Comment by DomT4** [comment]
Oh, I see your problem. You have a mountain of dead `npm` symlinks which for some reason Homebrew isn't able to overwrite. Run a `brew prune` and then `brew reinstall node`. That should fix the problem.

**Comment by diroussel** [comment]
The good news is that `brew prune` removed the bad symlinks.  The bad news is that `brew reinstall node` added them back in again.

I tried the following, twice:
* try `man npm`, not working
* `brew doctor` shows dangling symlinks
* run `brew reinstall node`
* same problem as before, in `man npm` and `brew doctor`

See https://gist.github.com/diroussel/dfe183a44ed88249e51f

I did a `brew update && brew upgrade` but that didn't help either.

**Comment by DomT4** [comment]
Can you try `brew prune && brew remove node`, and then change into `bash`, `sh` or `zsh` temporarily and then try reinstalling Node? I can't reproduce this at all, on any machine, and Fish is the only variable I haven't stuck my head in yet :smile_cat:. Run a `brew doctor` after the `brew prune` to see if all the errors have cleared up and not revealed anything else.

**Comment by diroussel** [comment]
That did it!  Thanks Dom.  Removing, then installing from bash did the trick.  I guess the environment variables are different somehow?
I don't have anything in ~/.bashrc or ~/.bash_profile, and in fact in bash there is nothing brew specific in `env`.

Maybe `/usr/local/bin/brew` should specify #!/bin/bash, but from my first inspection I don't see what could be wrong with it.  Maybe we should run [checkbashisms](http://manpages.ubuntu.com/manpages/natty/man1/checkbashisms.1.html) on it.

**Comment by DomT4** [comment]
Great! I'm not quite sure how best to implement it, but we should probably require `Fish` to not be the active shell during compile. `ps $$` doesn't work in Fish. `echo $SHELL` only prints the login shell which doesn't cover 100% of situations. I guess looking at the `env` and seeing if Fish has inserted its variables into the `env` is a decent enough way.

I don't think this is technically a Homebrew problem, at least in terms of our internal mechanisms. There have been some Fish problems upstream [before](https://github.com/npm/npm/issues/8092), and the upstream `npm` Make stage does use Bashisms, and is [supposed to switch over](https://github.com/npm/npm/commit/64b4d65161ff91597c27e0b19797ae101ca9bd85) to the `bash` shell for the `make` stage. Perhaps that isn't switching over properly.

**Comment by mikemcquaid** [comment]
@DomT4 I'd be open to a PR to change `bin/brew` to `#!/bin/bash` if that fixed things.

**Comment by DomT4** [comment]
Hmm. This also reproduces using `zsh` now when installed `-fs`, and reproduces locally with `fish`. Checking `bash` from source now. The bottle doesn't have any problems. `zsh` worked fine prior to the last bump, so perhaps we've done something to accidentally bork non-bash-builds for specific formulae, or upstream have.

**Comment by DomT4** [comment]
And reproduces locally via `bash` for me from-source, but using `bash` fixed the problem for @diroussel. Okay, maybe we did accidentally break something somewhere then, although I'm not quite sure what given the test-bot is producing bottles which are free from the *"You have mountains of dead symlinks"* problem.

**Comment by jacknagel** [comment]
The shebang line in bin/brew should not have any effect on shells spawned by subprocesses. It doesn't modify the environment, and that shell process doesn't even exist at the time formula code is executing (it has been replaced by the exec'd Library/brew.rb process).

**Comment by DomT4** [comment]
Yeah, didn't make any difference. I'm probably going to partially rewrite the mechanism we use to install the `npm` man documentation, again. Working on it.

**Comment by DomT4** [comment]
#39947
