### ISSUE TITLE
Better Emacs icon

### ISSUE THREAD

**Issue by lunaryorn** [Homebrew/homebrew#39824]
https://github.com/cg433n/emacs-yosemite-icon has a much nicer Emacs icon for Yosemite.  How could I integrate that in the Emacs formula?

**Comment by DomT4** [comment]
Unless upstream integrate it, you probably won't have much luck getting it into Homebrew. It's something much better dealt with on an individual user basis rather than in a Homebrew formulae.

**Comment by jacknagel** [comment]
Yes, we typically don't make those type of changes to our packages.

**Comment by lunaryorn** [comment]
I'm sorry, but I think there's a misunderstanding.  I didn't ask that the Homebrew Formula for Emacs be changed.  I'd just like to know how I could add the icon to the formula *locally*, for my personal builds only.  I know that I can add it manually but I use Emacs head and typically re-build once a week at least :)

**Comment by DomT4** [comment]
If you're installing via Homebrew to my knowledge there isn't a way to manipulate the `head` to suit individuality. If you want something that allows you to add the icon in some automated way you'll either need to write a custom formula or a shell script for your own personal use. Otherwise it's the usual manual drag & drop to replace the icon.

**Comment by lunaryorn** [comment]
@DomT4 Well, I'd like to do exactly that: Write a custom formula, or more specifically, just modify the Emacs formula accordingly.  My problem is that I don't know how to do that :) I'm familiar with Ruby, that's not the issue, but essentially I'd need to know how the Homebrew Formula equivalent of dragging and dropping an icon into the info window is :)

**Comment by xu-cheng** [comment]
> I'd need to know how the Homebrew Formula equivalent of dragging and dropping an icon into the info window is :)

You need find a proper command line tool to do this. And let your custom formula invoke that tool using `system`. This may be helpful: http://superuser.com/questions/133784/manipulate-mac-os-x-file-icons-from-automator-or-command-line
