### ISSUE TITLE
Duplicate: deis/deisctl

### ISSUE THREAD

**Issue by alias1** [Homebrew/homebrew#39834]
* [deisctl](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/deisctl.rb)
* [deis](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/deis.rb)
  * Seems to be most up to date (1.5.1, 29 days ago).

**Comment by DomT4** [comment]
I believe they install different elements of the same base project? See #34967.

**Comment by alias1** [comment]
Hrmm.. Fair enough. The download paths implied otherwise.. But I don't really have enough contextual knowledge to say one way or the other.



—

**Comment by DomT4** [comment]
It's not uncommon for the same tarball to contain multiple compartmentalised project elements. It's possible the `deisctl` needs updating, which would explain the version difference.

**Comment by jacknagel** [comment]
Will welcome pull requests to update this/these.
