### ISSUE TITLE
Error: parent directory is world writable but not sticky Please report this bug:

### ISSUE THREAD

**Issue by sherryhadoop** [Homebrew/homebrew#39847]
brew install hadoop
==> Downloading https://www.apache.org/dyn/closer.cgi?path=hadoop/common/hadoop-
Already downloaded: /Library/Caches/Homebrew/hadoop-2.7.0.tar.gz
Error: parent directory is world writable but not sticky
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:482:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:184:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:165:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `install'
/usr/local/Library/brew.rb:140:in `<main>'

**Comment by DomT4** [comment]
`brew doctor`, providing you're up-to-date, will tell you to run `Repair Disk Permissions` in the Disk Utility application.

**Comment by sherryhadoop** [comment]
After I did the repair, fixed issue

Thanks
