### ISSUE TITLE
Harfbuzz not built with its introspection typelib

### ISSUE THREAD

**Issue by gilbahat** [Homebrew/homebrew#39841]
Hi,

Harfbuzz is not built with its typelib, meaning introspection is not allowed and thus python wrapping is unusable:

$ pwd
/usr/local/Cellar/gobject-introspection/1.44.0/lib/girepository-1.0
$ ls -l *HarfBuzz*
ls: *HarfBuzz*: No such file or directory

this needs dependencies on libffi (note, keg-only), gobject-introspection and enabling the following configuration ooptions:

--enable-introspection=yes
--with-gobject=yes

this will create the typelib in the harfbuzz distro location, I am not sure how to add/link it to the location in gobject-introspection package.

**Comment by luzpaz** [comment]
watching this issue

**Comment by luzpaz** [comment]
Yes, this would be nice to know

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by cosmo0920** [comment]
Hi there, I've registered the pull request to enable Harfbuzz building with its typelib. 
How about this one?

**Comment by gilbahat** [comment]
@cosmo0920 the reason I opened the issue in the firstplace without submitting this pullreq is because I am unsure how to cause the harfbuzz package to put the typelib into the introspection dir, which belongs in gobject-introspection (e.g. on my system, /usr/local/Cellar/gobject-introspection/1.44.0lib/girepository-1.0). the typelib won't get loaded from its default location.

**Comment by cosmo0920** [comment]
`gobject-introspection` typelibs are usually symlinked into `$(brew --prefix)/lib/girepository-1.0/`.

harfbuzz's typelib is also symlinked when one installs it with gobject-introspection feature:

```bash
ls $(brew --prefix)/lib/girepository-1.0/ | grep HarfBuzz
HarfBuzz-0.0.typelib
```

And its entity is placed in each Cellar directory. 
(e.g. `$(brew --prefix)/Cellar/gtk+/2.24.27/lib/girepository-1.0/`)
HarfBuzz's typelib entity:

```bash
$ ls /usr/local/Cellar/harfbuzz/0.9.40/lib/girepository-1.0/
HarfBuzz-0.0.typelib
```

**Comment by gilbahat** [comment]
strange, when I checked my version of the formula it didn't seem to do that. maybe my environment was tainted. when the pull request gets committed I'll test this too.
