### ISSUE TITLE
mysql failed to build on 10.6.8

### ISSUE THREAD

**Issue by rreimche** [Homebrew/homebrew#39853]
Hi. Here's the problem:

--------
brew install mysql 
...
=> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/cmake20150517
   or: -c --help [cmd1 cmd2 ...]
   or: -c --help-commands
   or: -c cmd --help

error: option --no-user-cfg not recognized
clang version 1.0 (http://llvm.org/svn/llvm-project/cfe/tags/Apple/clang-23 exported)
Target: x86_64-apple-darwin10
------------
Full listing is here: http://www.codeshare.io/XAPbN

you can also read "cat /Users/rreimche/Library/Logs/Homebrew/cmake/01.python": http://www.codeshare.io/pWRr6

I've tried brew update, upgrade and doctor already, no effect.

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by jacknagel** [comment]
>error: option --no-user-cfg not recognized

Looks python packaging related

/cc @tdsmith

**Comment by tdsmith** [comment]
I think this means you have a version of Python 2.7 installed with a very old setuptools. 10.6 should have come with Python 2.6.

Running either of these will work around this:

1. `brew install cmake --without-docs` (to install cmake without documentation)
2. `python -m easy_install -U setuptools` (to upgrade your version of setuptools)

You may need to use `sudo` with option 2, depending on how you installed Python.

**Comment by rreimche** [comment]
I've run the first one and it solved the problem.
