### ISSUE TITLE
xhprof install error

### ISSUE THREAD

**Issue by jk2K** [Homebrew/homebrew#39866]
brew install php56-xhprof

php -v

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-xhprof/xhprof.so' - dlopen(/usr/local/opt/php56-xhprof/xhprof.so, 9): Symbol not found: _executor_globals
  Referenced from: /usr/local/opt/php56-xhprof/xhprof.so
  Expected in: flat namespace
 in /usr/local/opt/php56-xhprof/xhprof.so in Unknown on line 0
PHP 5.6.9 (cli) (built: May 18 2015 16:16:00) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by mikemcquaid** [comment]
This issue was moved to Homebrew/homebrew-php#1748
