### ISSUE TITLE
sslscan linker missing symbols for x86_64 on 10.10.3

### ISSUE THREAD

**Issue by Bombenleger** [Homebrew/homebrew#39867]
Compiling sslscan failes due to missing x86_64 symbols.

    $ brew install sslscan

results in:
```
==> make
      _testHost in sslscan-367a2f.o
      _main in sslscan-367a2f.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [all] Error 1
```
gist-logs: https://gist.github.com/anonymous/0de50c0cfb2a2196f317

**Comment by DomT4** [comment]
The true failure is that you've force-linked Homebrew's OpenSSL which doesn't support SSLv2, and `sslscan`'s make looks for SSLv2 methods. Unlink OpenSSL, reload your shell, and it should work. That said, I'm likely going to boneyard it because of the breakage against Homebrew's OpenSSL.
