### ISSUE TITLE
nginx-full with LDAP ld error (OS X 10.10.3)

### ISSUE THREAD

**Issue by jesse-gallagher** [Homebrew/homebrew#39873]
I've run into trouble trying to install nginx-full with the auth-ldap module, specifically encountering this error near the end:

	Undefined symbols for architecture x86_64:
	  "_ber_sockbuf_add_io", referenced from:
	      _ngx_http_auth_ldap_connection_established in ngx_http_auth_ldap_module.o

I've tried a number of troubleshooting techniques I've seen with similar problems - re-running xcode-select, reinstalling the openldap package, `brew update`, and a couple others, though my inexperience in these matters means I'm not sure if I'm following the right paths. I've tried including --HEAD in the command, but that fails with this same problem.

It looks like there exist libldap.dylib (and similar) files in both /usr/lib and /usr/local/lib, all of which include x86_64.

The specific command I'm executing is `brew install nginx-full --with-auth-ldap-module -v` and I've created a Gist of the four log files, the last bit of the output here, and the listings of the ldap lib files here: https://gist.github.com/jesse-gallagher/53d7f33ab1e4d757198b

If there's any other useful information I can cull, I'll be glad to track it down.

**Comment by mikemcquaid** [comment]
This issue was moved to Homebrew/homebrew-nginx#93

**Comment by denji** [comment]
```
~ nm /usr/lib/*ldap* | grep ber_sockbuf_add_io
0000000000006073 T _ber_sockbuf_add_io
0000000000006073 T _ber_sockbuf_add_io
```
