### ISSUE TITLE
djview4 launch error

### ISSUE THREAD

**Issue by samuelandjw** [Homebrew/homebrew#39896]
Mac OS 10.10.3
`djview4` installed via `brew install djview4`
However, when I attempted to launch `djview4`, I got the following error message:
````
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/lib/libdjvulibre.21.dylib
  Referenced from: /usr/local/Cellar/djview4/4.10.3/djview.app/Contents/MacOS/djview
  Reason: Incompatible library version: djview requires version 26.0.0 or later, but libdjvulibre.21.dylib provides version 25.0.0
````

**Comment by DomT4** [comment]
Can't reproduce here. Try `brew reinstall djvulibre`. If that doesn't work, providing a `brew doctor` may help.

**Comment by DomT4** [comment]
Closing per no response. Please feel free to leave a comment here if the issue persists.
