### ISSUE TITLE
libxml2 should revert keg-only status

### ISSUE THREAD

**Issue by schwa** [Homebrew/homebrew#39907]
libxml2 is currently marked as "keg-only" due to conflicts with the system provided libxml2.

However on a standard install of Mac OS X 10.10 libxml2 is only present either inside Xcode (deep inside SDKs) or if the user has installed the Command Line Tools (inside /usr).

Keg-only libxml2 is causing a world of hurt for anyone trying to install python's lxml package (which is an extremely popular and power xml package).

Does home-brew consider "Installed along with the Command Line Tools" enough for a package to be marked as keg-only? And if not would removing the keg-only brand on libxml2 be possible?

Thanks.

**Comment by jacknagel** [comment]
>Keg-only libxml2 is causing a world of hurt for anyone trying to install python's lxml package (which is an extremely popular and power xml package).

Why not use the system libxml2?

Also, it's possible to use a keg-only package without linking it, you just need to add `/usr/local/opt/libxml2/{lib,include,bin}` to the appropriate paths.

>Does home-brew consider "Installed along with the Command Line Tools" enough for a package to be marked as keg-only?

Yes, and additionally, `/usr/lib/libxml2.dylib` exists even without the command line tools installed.

From our point of view, nothing has changed. Apple still provides libxml2, so it is still a duplicate.

**Comment by schwa** [comment]
Well my point is there is no system libxml2 unless the user has installed the Command Line Tools. The .dylib might be there - but its obviously not useful without includes. 

In my experience very few users install the Command Line Tools.

Because of the way lxml is installed by python it's almost comically impossible to get it to use the keg only libxml2. (As mentioned lxml is a very well known and widely used python module).

If you search the web for "libxml2 mavericks/yosemite" you'll see a lot of people are having trouble with this.

**Comment by DomT4** [comment]
> Because of the way lxml is installed by python it's almost comically impossible to get it to use the keg only libxml2

`CFLAGS=-I$(brew --prefix)/opt/libxml2/include LDFLAGS=-L$(brew --prefix)/opt/libxml2/lib pip install lxml`?

**Comment by jacknagel** [comment]
>Well my point is there is no system libxml2 unless the user has installed the Command Line Tools. The .dylib might be there - but its obviously not useful without includes.

You need the command line tools (or Xcode) installed to compile things anyway. Both provide the headers.

**Comment by schwa** [comment]
Xcode provides the headers in a way that (again) it's almost impossible for lxml to use.

**Comment by jacknagel** [comment]
Apple's `xml2-config` will give the correct paths whether the CLT or Xcode is installed.

**Comment by schwa** [comment]
Ah ok - thanks for the pointer to xml2-config. It seems like this is the best workaround for now (posting in case this appears in anyone's google search"

pip install lxml --install-option="--with-xml2-config=/usr/bin/xml2-config"

It doesn't help if lxml is listed as a dependency of something (well you'd need to install lxml by hand first) but it's better than  nothing.

**Comment by schwa** [comment]
@DomT4 Exactly: almost comically impossible. That's not the kind of stuff I would want to put in a INSTALL file for end-users to deal with. The pip install method above is a bit better.

**Comment by mikemcquaid** [comment]
Perhaps worth submitting a PR to lxml to fix it's buildsystem to look in the default OS X locations for these files.
