### ISSUE TITLE
Better handling of Apache mirrors

### ISSUE THREAD

**Issue by acdha** [Homebrew/homebrew#39935]
Tika 1.8 is currently uninstallable (see #39934 for a hack to avoid the issue for that formula). The larger problem is that [a number of recipes use the Apache mirror selection URLs](https://github.com/Homebrew/homebrew/search?utf8=%E2%9C%93&q=%27http%3A%2F%2Fwww.apache.org%2Fdyn%2Fcloser.cgi%27&type=Code) and but the closer.cgi script returns an HTML page rather than redirecting, causing installs to fail unless they also specify `mirror` URLs.

The Apache [closer.cgi script](http://svn.apache.org/viewvc/infrastructure/site/trunk/content/dyn/mirrors/mirrors.cgi?view=markup) is fairly limited but it does support JSON output by putting `as_json=1` in the URL. Given how many Homebrew projects use the Apache infrastructure, it might be useful create a generic version of e.g. https://raw.githubusercontent.com/acdha/pysolr/master/get-solr-download-url.py so those could all use something like an `ApacheFormula` which knows how to retrieve the list of mirrors for a given file and them in order of decreasing preference.

**Comment by DomT4** [comment]
> but the closer.cgi script returns an HTML page rather than redirecting, causing installs to fail unless they also specify mirror URLs.

This isn't true. We already [handle this](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/download_strategy.rb#L326-L361). If that mechanism wasn't working consistently across the user base we'd be getting hammered with issues.

```
~> brew fetch tika
==> Downloading https://www.apache.org/dyn/closer.cgi?path=tika/tika-app-1.8.jar
==> Best Mirror http://apache.mirrors.spacedump.net/tika/tika-app-1.8.jar
```

What's happening for you locally?

**Comment by acdha** [comment]
`brew install <apache.org project>` will fail on the initial download with something like this:

```
==> Downloading https://www.apache.org/dyn/closer.cgi?path=tika/tika-app-1.8.jar
Error: Failed to download resource "tika"
Download failed: Couldn't determine mirror, try again later.
```

If a mirror is coded in the formula, that will succeed. This is true of Tika, Solr, apr, maven, pylucene, etc. – after testing with `ack -l closer.cgi /usr/local/Library/Formula/ | xargs basename | sed -e 's/[.]rb//' | xargs -n 1 brew fetch` the only projects which succeed are the ones like hadoop which specify a mirror in the formula or the ones like couchdb which are available as bottles.

**Comment by acdha** [comment]
Looking closer, this was caused by a curlrc with `remote-name-all` set. Apparently all of the other downloads I do on a regular basis work with that but the mirror-detection step does not. Not sure if that's worth adding `-q` to the curl invocation but it's working now.

**Comment by DomT4** [comment]
> Not sure if that's worth adding -q to the curl invocation

Per Jack's comments the other day we used to, but people got grumpy. `brew doctor` does throw a warning that the `curlrc` can interfere with certain formulae, but that's about as strong as we go.

**Comment by acdha** [comment]
Yeah, I had a clean `brew doctor` report a week ago but then I was testing something for a different project… Sorry about the chatter.
