### ISSUE TITLE
configure: error: Please reinstall the BZip2 distribution

### ISSUE THREAD

**Issue by xqpmjh** [Homebrew/homebrew#39949]
I got the following error when installing php：
$ brew install php56 --without-apache --with-fpm --with-mysql 

......
checking for BZip2 support... yes
checking for BZip2 in default path... not found
configure: error: Please reinstall the BZip2 distribution
......

I found the bzip2 in：
/usr/bin/bzip2

How can I solve this?

**Comment by DomT4** [comment]
This should be reported at Homebrew/php, but the answer is you need to install Apple's CLT package.

**Comment by xqpmjh** [comment]
Yes, I had tried install CLT, but seems already installed.
# xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

**Comment by DomT4** [comment]
Funky. Can you open a new issue in https://github.com/Homebrew/homebrew-php with an included readout of the failed configure stage and a `brew config`? Thanks!

**Comment by xqpmjh** [comment]
Hi DomT4, Here is the link https://github.com/Homebrew/homebrew-php/issues/1753

**Comment by DomT4** [comment]
This is safe to close now whenever one of the maintainers sees it. Issue was resolved at Homebrew/php.
