### ISSUE TITLE
homebrew bug when installing profanity

### ISSUE THREAD

**Issue by santosomar** [Homebrew/homebrew#39944]
Error: parent directory is world writable but not sticky
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:482:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:184:in `install'
/usr/local/Library/Homebrew/formula_installer.rb:359:in `install_dependency'
/usr/local/Library/Homebrew/formula_installer.rb:317:in `block in install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:317:in `each'
/usr/local/Library/Homebrew/formula_installer.rb:317:in `install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:222:in `compute_and_install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:149:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:165:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `install'
/usr/local/Library/brew.rb:140:in `<main>'

**Comment by santosomar** [comment]
bash-3.2$ uname -a
Darwin OSANTOS 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

**Comment by DomT4** [comment]
`brew doctor` will tell you to run `Repair Disk Permissions` in the Disk Utility application to fix this.

**Comment by santosomar** [comment]
It worked. Thanks a million!
