### ISSUE TITLE
Installing php56-xdebug: Cannot find build files at '@@HOMEBREW_CELLAR@@/php56/5.6.9/lib/php/build'.

### ISSUE THREAD

**Issue by adityapurwa** [Homebrew/homebrew#39946]
I am trying to install php56-xdebug but I got this reply.
    
    Adityas-MBP:~ adityapurwa$ brew install php56-xdebug
    Warning: You have an outdated version of /usr/bin/install_name_tool installed.
    This will cause binary package installations to fail.
    This can happen if you install osx-gcc-installer or RailsInstaller.
    To restore it, you must reinstall OS X or restore the binary from
    the OS packages.
    ==> Installing php56-xdebug from homebrew/homebrew-php
    ==> Downloading http://xdebug.org/files/xdebug-2.3.2.tgz
    Already downloaded: /Library/Caches/Homebrew/php56-xdebug-2.3.2.tgz
    ==> /usr/local/opt/php56/bin/phpize
    
    /usr/local/opt/php56/bin/phpize
    
    Cannot find build files at '@@HOMEBREW_CELLAR@@/php56/5.6.9/lib/php/build'. Please check     your PHP installation.
    
    READ THIS: https://git.io/brew-troubleshooting
    If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues    

Here's what I got when running `brew update` and `brew doctor`:

    Adityas-MBP:~ adityapurwa$ brew update
    Updated Homebrew from ae882743 to bd76bd45.
    ==> Updated Formulae
    aws-elasticbeanstalk			homebrew/versions/qt52
    drake					homebrew/versions/raptor1
    homebrew/versions/bash-completion2	homebrew/versions/syncthing010
    homebrew/versions/gcc5			homebrew/versions/tomcat6
    homebrew/versions/gnupg21		homebrew/versions/tomcat7
    homebrew/versions/protobuf240a		sqlite
    homebrew/versions/protobuf241		youtube-dl
    homebrew/versions/protobuf250
    Adityas-MBP:~ adityapurwa$ brew doctor
    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry and just ignore them. Thanks!
    
    Warning: You have an outdated version of /usr/bin/install_name_tool installed.
    This will cause binary package installations to fail.
    This can happen if you install osx-gcc-installer or RailsInstaller.
    To restore it, you must reinstall OS X or restore the binary from
    the OS packages.
    
    Warning: Unbrewed header files were found in /usr/local/include.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.
    
    Unexpected header files:
        /usr/local/include/node/android-ifaddrs.h
    /usr/local/include/node/ares.h
    /usr/local/include/node/ares_version.h
    /usr/local/include/node/libplatform/libplatform.h
    /usr/local/include/node/nameser.h
    /usr/local/include/node/node.h
    /usr/local/include/node/node_buffer.h
    /usr/local/include/node/node_internals.h
    /usr/local/include/node/node_object_wrap.h
    /usr/local/include/node/node_version.h
    /usr/local/include/node/openssl/opensslconf.h
    /usr/local/include/node/pthread-fixes.h
    /usr/local/include/node/smalloc.h
    /usr/local/include/node/stdint-msvc2008.h
    /usr/local/include/node/tree.h
    /usr/local/include/node/uv-aix.h
    /usr/local/include/node/uv-bsd.h
    /usr/local/include/node/uv-darwin.h
    /usr/local/include/node/uv-errno.h
    /usr/local/include/node/uv-linux.h
    /usr/local/include/node/uv-sunos.h
    /usr/local/include/node/uv-threadpool.h
    /usr/local/include/node/uv-unix.h
    /usr/local/include/node/uv-version.h
    /usr/local/include/node/uv-win.h
    /usr/local/include/node/uv.h
    /usr/local/include/node/v8-debug.h
    /usr/local/include/node/v8-platform.h
    /usr/local/include/node/v8-profiler.h
    /usr/local/include/node/v8-testing.h
    /usr/local/include/node/v8-util.h
    /usr/local/include/node/v8.h
    /usr/local/include/node/v8config.h
    /usr/local/include/node/v8stdint.h
    /usr/local/include/node/zconf.h
    /usr/local/include/node/zlib.h

    Warning: You have unlinked kegs in your Cellar
    Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
    those kegs to fail to run properly once built. Run `brew link` on these:

    php55

    Warning: Homebrew's sbin was not found in your PATH but you have installed
    formulae that put executables in /usr/local/sbin.
    Consider setting the PATH for example like so
        echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

    Warning: Some keg-only formula are linked into the Cellar.
    Linking a keg-only formula, such as gettext, into the cellar with
    `brew link <formula>` will cause other formulae to detect them during
    the `./configure` step. This may cause problems when compiling those
    other formulae.

    Binaries provided by keg-only formulae may override system binaries
    with other strange results.

    You may wish to `brew unlink` these brews:

    gettext
    openssl

**Comment by mistydemeo** [comment]
```
Warning: You have an outdated version of /usr/bin/install_name_tool installed.
This will cause binary package installations to fail.
This can happen if you install osx-gcc-installer or RailsInstaller.
To restore it, you must reinstall OS X or restore the binary from
the OS packages.
```

This is the source of your problem - you'll need to fix this, then reinstall php56.

**Comment by adityapurwa** [comment]
@mistydemeo Thank you for your response. So I won't reinstall OSX because it is time consuming and a lot of other thing for me to consider. How about restoring the binary? How do I do it?

**Comment by jacknagel** [comment]
>How about restoring the binary? How do I do it?

The officially supported way is to reinstall the OS. Otherwise, you'll need to find the OS package that it came from and extract the file. I don't know how to do this, but you can probably find some information by googling. Other than that we can't really help.
