### ISSUE TITLE
pandoc failed to build on 10.7.5

### ISSUE THREAD

**Issue by silberzwiebel** [Homebrew/homebrew#39950]
Here is the [gist](https://gist.github.com/silberzwiebel/11d24cd93c08c94eedf1).

Compiling via
`cabal install --flags="embed_data_files" pandoc pandoc-citeproc`
as [recommended on pandoc.org](http://pandoc.org/installing.html) works fine.

Let me know if you need more information.

Thanks for fixing.

**Comment by mikemcquaid** [comment]
Can you try to `brew update` and then try again?

**Comment by silberzwiebel** [comment]
Still does not work, same error.

**Comment by c-rack** [comment]
@silberzwiebel Thanks for the workaround. Had the same issue and your cmd line worked like a charm.

**Comment by mistydemeo** [comment]
I see what the issue is. This line here: https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/language/haskell.rb#L15

This isn't being evaluated in the context of the formula object (nor is a formula passed in), so it's impossible for the `fails_with` statement to work.

**Comment by mistydemeo** [comment]
`cabal_sandbox` is included on `Formula` though.

**Comment by mistydemeo** [comment]
Fixed, by moving the compiler setup into a class method.
