### ISSUE TITLE
Installing Old Version of Python3

### ISSUE THREAD

**Issue by seantrott** [Homebrew/homebrew#39965]
Hello,

Brew used to enable a "brew versions" command, which would allow you to checkout the version of a Formula you wanted to install. I used brew to install python3 (v 3.4.0) as well as Morse (a robotics simulator).

Recently, I ran brew upgrade and brew update, and I had to uninstall and reinstall python3 for an unrelated reason. The new version of python3 is v.3.4.3, which isn't compatible with my versions of Blender/Morse. I'd like to install python3.4.0 instead - is there a way to access the git number for that, and check it out? I've tried tapping the boneyard, as well as viewing the log history, and going to this link (https://github.com/Homebrew/homebrew-versions). Is there a Formula for python3.4.0?

Thanks.

**Comment by DomT4** [comment]
> is there a way to access the git number for that, and check it out?

There is, but it's really not recommended. Can cause some fairly major problems. The idea of stashing old Pythons in Versions has been discussed before, the idea isn't totally off the table but the formula would need some rewriting from Homebrew/homebrew. You can see Tim's comments on what needs to be done [here](https://github.com/Homebrew/homebrew-versions/pull/513).

**Comment by seantrott** [comment]
Thanks for the reply. I see the potential issue with having multiple versions of python3 installed, but would it be problematic to uninstall 3.4.3, and then install 3.4.0 (or 3.4.2)? Would modifying line 3 on python3.rb be sufficient for this?

**Comment by DomT4** [comment]
I suspect it depends what your use case is as to what issues that could cause. I can't imagine major problems per se, but I'll defer to @tdsmith who is the expert.

**Comment by seantrott** [comment]
Great, thanks for your help. I tried this, and it seems to be working fine so far.

**Comment by tdsmith** [comment]
Oughta work; isn't supported. :) `pyenv` is a great way to tame multiple python versions, and you can install it with brew!
