### ISSUE TITLE
Allow a manually-built library to satisfy dependencies

### ISSUE THREAD

**Issue by rcombs** [Homebrew/homebrew#39970]
If I hand-build a library, install it into the Cellar, and `brew link` it, currently it'll be switched away from if I try to install another package that depends on it. Could we have a more sticky form of `brew pin` that avoids that?

**Comment by jacknagel** [comment]
If it's up-to-date with (or newer than) the formula in core, it will be used. Otherwise, no, we can't support using just any arbitrary version of a package. The potential support burden is too great.

**Comment by rcombs** [comment]
How does it tell what version I've installed manually? I generally install into  `/usr/local/Cellar/<package>/master`.

**Comment by jacknagel** [comment]
name it `HEAD` instead of master and it will always be used.
