### ISSUE TITLE
Check for R dependencies via Homebrew formula

### ISSUE THREAD

**Issue by gawbul** [Homebrew/homebrew#39981]
Just as you would do a `depends_on 'rpy2' => :python` to check for a Python dependency, is there any plan to support checking for R dependencies, e.g. `depends_on 'ggplot2' => :r`?

**Comment by mikemcquaid** [comment]
No, sorry. The Python dependency method has been deprecated in favour of vendoring in the formula.

**Comment by gawbul** [comment]
Okay, no problem! What do you mean by vendoring in the formula, sorry? Adding appropriate tests and such forth? Is there anywhere with details/best practices on how one should convert their formula to work around the depreciation of the dependency checking?

**Comment by mikemcquaid** [comment]
See e.g. `ansible.rb` where all the Python dependencies are duplicate for a formula.

**Comment by gawbul** [comment]
Excellent, thank you :+1:

**Comment by gawbul** [comment]
Does this seem to be a reasonable attempt at a new formula? https://gist.github.com/gawbul/17de72ef7a22db8de4c9

**Comment by mikemcquaid** [comment]
@gawbul Yeh, makes sense :+1:
