### ISSUE TITLE
Installing PolarSSL breaks compilation

### ISSUE THREAD

**Issue by Aorimn** [Homebrew/homebrew#39983]
Hi,
Since PolarSSL changed its name to mbedTLS due to ARM rebrand, the library name changed from libpolarssl.so to libmbedtls.so.

Is it possible to add a symbolic link to the brew formula of polarssl in order not to break compatibility?

**Comment by DomT4** [comment]
> Is it possible to add a symbolic link to the brew formula of polarssl in order not to break compatibility?

Can you be more explicit? As in symlink the libraries from the new names to the old names?

**Comment by Aorimn** [comment]
As the mbedtls/polarssl formula provides libmbedtls.so, it should be easier to make a symlink named libpolarssl.so pointing to libmbedtls.so.

**Comment by DomT4** [comment]
I'm semi-reluctant to rub up against upstream's choice here, but will let @Homebrew/owners :+1: or :-1: the idea.

**Comment by Aorimn** [comment]
The problem is I'm not sure against which library I should link, and it depends on the version installed by homebrew. Another solution would be to require brew to be up-to-date on clients, but I'm not sure that's really applicable or something one would want to enforce -- I'm not, for my part.

**Comment by tdsmith** [comment]
Is it a bad idea to make your build scripts smart enough to figure this out? It would be a small change but this isn't unique to Homebrew's packaging; you'd run into the same problem on other platforms.

**Comment by DomT4** [comment]
Going to close here. I agree these things should be handled upstream, and I'm concerned putting in a temporary Homebrew hack is going to cause more problems than it'll solve, especially since once we add these things they tend to stick around.
