### ISSUE TITLE
feature request: include note in `outdated` output for tap-installed formulas

### ISSUE THREAD

**Issue by jasonkarns** [Homebrew/homebrew#39991]
From https://github.com/Homebrew/homebrew/issues/38255#issuecomment-88562701:

Use case: In order to help prevent inadvertent upgrades that cause a tap-installed formula to be replaced by a same-named formula from core.

Presently, Given:
1. Two formulas (one in core, one from a tap) share the same name
2. The installed formula is from the tap version
3. The formula in core has a higher version number than the tap version

When `brew outdated` is run, Then it lists the formula as outdated.
And when `brew upgrade <formula>` is run, Then it installs the core version; replacing the tap version.

This feature request is not meant to change the behavior of `brew upgrade`. Rather, I would like to see something in the `brew outdated` output that indicates when a formula is listed as outdated *but the upgrade would not come from the same source* (core vs tap).

Suggestions?

**Comment by jacknagel** [comment]
I think the current behavior of upgrade is actually going to change when https://github.com/Homebrew/homebrew/pull/39524 lands. At that point, if something was installed from a tap, the formula loaded by `upgrade` will be the formula from the tap.

At that point we may be able to remove some of the hacks from `outdated` as it should "just work".

**Comment by jasonkarns** [comment]
Sweet. I'll keep this open, then, just in case there's any issue with #39524. But I'll close this once it lands.

**Comment by jacknagel** [comment]
I think this is fixed on master now.

```
$ brew install homebrew/games/omega
==> Installing omega from homebrew/homebrew-games
==> Downloading http://www.alcyone.com/binaries/omega/omega-0.80.2-src.tar.gz
Already downloaded: /Library/Caches/Homebrew/omega-0.80.2.tar.gz
==> make
/usr/local/Cellar/omega/0.80.2: 50 files, 748K, built in 2 seconds
```

`homebrew/games/omega` conflicted with `omega` from core. Before #39524, we would see:

```
$ brew outdated
omega (0.80.2 < 1.2.18)
```

This is wrong, as the two versions are from different formulae. Now, after #39524, `brew outdated` yields nothing in this situation.

**Comment by jasonkarns** [comment]
Perfect! I just verified as well. Prior to the update, `brew outdated` was showing:
```
nodenv (0.2.0 < 0.3.3)
```

which was 'wrong' and especially dangerous because not only are the two versions from different taps, they aren't technically the same app. (So I couldn't safely `brew upgrade`)

After updating brew, `brew outdated` now shows:
```
$ brew outdated 
git (2.4.1 < 2.4.2)
python (2.7.9 < 2.7.10)
```

and after a nice, safe, `brew upgrade`, no more issues with nodenv conflicts. Thanks! and congrats to everyone who worked on #39524!
