### ISSUE TITLE
node failed to build on 10.10.3 

### ISSUE THREAD

**Issue by bytenel** [Homebrew/homebrew#39996]
Here's my [gist](https://gist.github.com/bytenel/c65e96dbfbebee8e56e4). Where did I go wrong?

**Comment by DomT4** [comment]
Can you either `brew gist-logs node` or try `brew postinstall node` again and see what the error message is? That's just the generic error message which doesn't narrow down the potential problem sadly. I recommend following up on the Doctor messages as well.

**Comment by bytenel** [comment]
Yeah I can do that. I did a brew gist-logs node and it didn't give me anything and then I tried the postinstall and got the same error message. I'll redo those commands again later though since I had just downloaded node from the source and installed it since I needed it to work as a dependency for some other software.

**Comment by DomT4** [comment]
I suspect it's a permissions problem somewhere, but hard to say without a fuller build log. If you still have no joy with the post-install do a full build `-fs` and then `gist-logs node` again. The full from-source build should contain a lot more information.

**Comment by DomT4** [comment]
Any further issues here?

**Comment by bytenel** [comment]
I'll close this so I don't leave you guys hanging but I just haven't had time to try and rebuild from homebrew.

**Comment by DomT4** [comment]
No worries. Please feel free to create a new issue if you run into any further problems.
