### ISSUE TITLE
SlimerJS flag description confusing

### ISSUE THREAD

**Issue by lvh** [Homebrew/homebrew#40003]
```
--without-xulrunner
	Build with xulrunner
```

Which one is it? Also, it may be worth documenting what that does precisely, i.e. if it embeds xulrunner, and if/how that works on OS X Yosemite, since xulrunner is currently not brewable on Yosemite.

**Comment by DomT4** [comment]
The option is actually dead. It should have been cut when we changed the dependencies around for Yosemite's problem.

> xulrunner is currently not brewable on Yosemite.

You need to have a Firefox installation in one of the Applications directories for SlimerJS to install on Yosemite.
