### ISSUE TITLE
gazebo4

### ISSUE THREAD

**Issue by xtrntr** [Homebrew/homebrew#40024]
[ 56%] Built target gazebo_physics_simbody
make: *** [all] Error 2
==> Formula
Tap: osrf/homebrew-simulation
Path: /usr/local/Library/Taps/osrf/homebrew-simulation/gazebo4.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 45bc689b2a1af15c798fa01481b38da062e47e3f
Last commit: 43 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.10.3-x86_64
Xcode: 6.3.2
CLT: 6.3.2.0.1.1431401888
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.7.0_71
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/opt/X11/include:/opt/X11/include/freetype2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /opt/X11/lib:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/qt/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/libzzip/lib/pkgconfig:/usr/local/opt/ogre/lib/pkgconfig:/usr/local/opt/protobuf/lib/pkgconfig:/usr/local/opt/protobuf-c/lib/pkgconfig:/usr/local/opt/qt/lib/pkgconfig:/usr/local/opt/tinyxml/lib/pkgconfig:/usr/local/opt/sdformat/lib/pkgconfig:/usr/local/opt/bullet/lib/pkgconfig:/usr/local/opt/simbody/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10:/opt/X11/lib/pkgconfig:/opt/X11/share/pkgconfig
ACLOCAL_PATH: /usr/local/share/aclocal:/opt/X11/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/cmake/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/doxygen/bin:/usr/local/opt/libtar/bin:/usr/local/opt/libpng/bin:/usr/local/opt/freetype/bin:/usr/local/opt/libzzip/bin:/usr/local/opt/ogre/bin:/usr/local/opt/protobuf/bin:/usr/local/opt/protobuf-c/bin:/usr/local/opt/qt/bin:/opt/X11/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: gazebo4 4.1.3 did not build
Logs:
     /Users/kangrenchia/Library/Logs/Homebrew/gazebo4/01.cmake
     /Users/kangrenchia/Library/Logs/Homebrew/gazebo4/01.cmake.cc
     /Users/kangrenchia/Library/Logs/Homebrew/gazebo4/02.make
     /Users/kangrenchia/Library/Logs/Homebrew/gazebo4/02.make.cc

**Comment by DomT4** [comment]
Please report this [to the tap itself](https://github.com/osrf/homebrew-simulation), we don't have control over non-core tap formula. It'll be useful to them if you do a `brew gist-logs gazebo4` first. Thanks!

**Comment by xtrntr** [comment]
https://gist.github.com/anonymous/3cc5d2753cc45c3991d4

**Comment by DomT4** [comment]
Add that link to the report you file in the tap :)
