### ISSUE TITLE
slimerjs --HEAD build is broken

### ISSUE THREAD

**Issue by lvh** [Homebrew/homebrew#40029]
```
➜  slimerjs--git git:(master) brew install slimerjs --HEAD                                                                                                                15:34:57
==> Cloning https://github.com/laurentj/slimerjs.git
Updating /Library/Caches/Homebrew/slimerjs--git
==> Checking out branch master
==> zip -r omni.ja chrome/ components/ modules/ defaults/ chrome.manifest -x@package_exclude.lst
Error: No such file or directory - application.ini
```

Looks like that command should be executed in the `src/` directory, not the root of the git repo.

**Comment by lvh** [comment]
[Interestingly, the formula does *look* like it's doing that...](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/slimerjs.rb#L37)

**Comment by lvh** [comment]
I'm guessing it's the next line that's erroring: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/slimerjs.rb#L41

I don't know why homebrew doesn't show it's trying to execute that line.

**Comment by DomT4** [comment]
Should be fixed in #40030. Feel free to test that PR out.

**Comment by lvh** [comment]
Sorry I didn't get a chance to test this; family's in town. Happy to report this fixes the bug though!

**Comment by DomT4** [comment]
No worries at all, Thanks for the confirmation!
