### ISSUE TITLE
tomcat-native Java 1.7 requirement failed 

### ISSUE THREAD

**Issue by alastairandrew** [Homebrew/homebrew#40023]
Since homebrew bumped up to the latest version of tomcat-native (1.1.33) I've been unable to upgrade it.  I'm running Mac OS X 10.10.3 with the Java JDK 1.8.0_40 as my default JVM. The previous upgrades of tomcat-native (up to and including 1.1.32) installed fine under this setup. Any suggestions on what I can do to get the formula to recognise Java 1.8 as valid? Or, alternatively, does anyone know why Java 1.7 is definitely required and 1.8 won't do?

**Comment by xu-cheng** [comment]
Fixed in 315f043d29248344086801c40cd797aee69e0a6e

**Comment by alastairandrew** [comment]
Brilliant. Thank you for all your hard work, much appreciated.
