### ISSUE TITLE
Searching OpenSceneGraph doesn't return open-scene-graph.rb

### ISSUE THREAD

**Issue by luzpaz** [Homebrew/homebrew#40048]
> 🍎 Test:~ $ **brew search openscenegraph**
No formula found for "openscenegraph".
Searching pull requests...
Closed pull requests:
OpenSceneGraph 3.0.1 and Collada (https://github.com/Homebrew/homebrew/pull/8094)
Added devloper release to the OpenSceneGraph formula (https://github.com/Homebrew/homebrew/pull/11923)
OpenSceneGraph 3.1.2 clang c++11 compiler support (https://github.com/Homebrew/homebrew/pull/19999)  

------

> 🍎 Test:~ $ **brew search open-scene-graph**
open-scene-graph
🍎 Test:~ $ brew info open-scene-graph
open-scene-graph: stable 3.3.3 (bottled), HEAD
http://www.openscenegraph.org/projects/osg
/usr/local/Cellar/open-scene-graph/3.3.3 (741 files, 36M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/open-scene-graph.rb
==> Dependencies
Build: cmake ✔, pkg-config ✔
Required: jpeg ✔, wget ✔, gtkglext ✔, freetype ✔
Optional: gdal ✘, jasper ✘, openexr ✔, dcmtk ✘, librsvg ✘, collada-dom ✘, gnuplot ✘, ffmpeg ✔, qt5 ✔, qt ✘
==> Options
--c++11
	Build using C++11 mode
--with-collada-dom
	Build with collada-dom support
--with-dcmtk
	Build with dcmtk support
--with-docs
	Build the documentation with Doxygen and Graphviz
--with-ffmpeg
	Build with ffmpeg support
--with-gdal
	Build with gdal support
--with-gnuplot
	Build with gnuplot support
--with-jasper
	Build with jasper support
--with-librsvg
	Build with librsvg support
--with-openexr
	Build with openexr support
--with-qt
	Build with qt support
--with-qt5
	Build with qt5 support
--HEAD
	Install HEAD version

**Comment by mikemcquaid** [comment]
Would adding an alias suffice?

**Comment by luzpaz** [comment]
I think so. There are 2 projects of OpenSceneGraph so I'm not sure if this was done purposely. Maybe someone who understands can comment ?

**Comment by iml** [comment]
It's openscenegraph on Debian FWIW.

**Comment by mikemcquaid** [comment]
> There are 2 projects of OpenSceneGraph so I'm not sure if this was done purposely. Maybe someone who understands can comment ?

Sorry, not sure I understand about there being two projects?

**Comment by luzpaz** [comment]
@mikemcquaid I'm referencing @casallas comment: https://github.com/Homebrew/homebrew/pull/8094#issuecomment-3713496
