### ISSUE TITLE
Fomula update required to cover the release of Python 2.7.10

### ISSUE THREAD

**Issue by cclauss** [Homebrew/homebrew#40050]
[Python 2.7.10](https://www.python.org/downloads/release/python-2710/) has been [officially released](https://hg.python.org/cpython/raw-file/15c95b7d81dc/Misc/NEWS) but the [current Python formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/python.rb) installs 2.7.9

**Comment by DomT4** [comment]
#40034
