### ISSUE TITLE
Byobu is broken on 10.10.3

### ISSUE THREAD

**Issue by timothybasanov** [Homebrew/homebrew#40056]
Recently updated to Mac OS X 10.10.3
Today I discovered that `byobu` is broken.

1. Install brew
1. `brew install byobu`
1. `byobu`
1. Press <kbd>F1</kbd>

* *Expected:* Help window appears
* *Actual:* nothing happens

Brew gist-logs fails, here are logs displayed: https://gist.github.com/timothybasanov/d1f9e316388d84da679b

I've checked that I don't have any configuration files left for tmux and byobu.
Uninstalled and reinstalled brew.

**Comment by tdsmith** [comment]
Is this Homebrew-specific? You may have better luck raising this directly with the byobu project.

**Comment by timothybasanov** [comment]
Looks like all my problems are related to changes in Yosemite that kinda broke tmux which affected byobu indirectly.
http://superuser.com/questions/231130/unable-to-use-pbcopy-while-in-tmux-session

There is a chance that somebody want to try to change byobu formula to install brew dependency mentioned by default.
I'll close this ticket for now as I'm not sure that this is the right place to fix it.
