### ISSUE TITLE
Homebrew forumula for emacs' VM (View Mail)

### ISSUE THREAD

**Issue by DiagonalArg** [Homebrew/homebrew#40051]
The script for installing VM (http://www.nongnu.org/viewmail/) is quite simple:
```bash
    bzr get lp:vm
    cd vm
    ./configure --with-emacs=~/.homebrew/bin/emacs --prefix=~/.homebrew 
    make
    make install
```
Making a formula for this is unclear to me as there is no target for the "url" or "sha1" methods.
```ruby
    require "formula"
    class ViewMail < Formula
      homepage "http://www.nongnu.org/viewmail/"
      url "what do I do with this when download uses bzr get ...?"
      sha1 "ditto"

     depends_on :emacs
     depends_on :bzr

      def install
        system "bzr", "get", "lp:vm"
        system "cd", "vm"
        system "./configure", "--with-emacs=#{prefix}/bin/emacs", "--prefix=#{prefix}" 
        system "make"
        system "make", "install"
      end
    end
```
Also, this needs to be updated whenever emacs is or "bzr get ..." returns a new version.

Any input would be appreciated.  Go easy on me, as I'm a homebrew and ruby noob!  :)

/DA

**Comment by DomT4** [comment]
If there's no stable download (i.e. a tag or tarball) available this will need to be filed in [Homebrew/head-only](https://github.com/Homebrew/homebrew-head-only).

Rather than use `system "bzr", "get", "lp:vm"` you would use a `head` line, similar to [here](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/percona-toolkit.rb#L7). You wouldn't need to `cd` into the path either, Homebrew switches to a temporary path for compile. `require "formula"` is no longer necessary :).

**Comment by DiagonalArg** [comment]
DomT4 - Thanks for the input.  

Regarding *Why is head-only bad?*, at that first link:  Since VM doesn't actually *have* to be updated until emacs is, and since emacs is updated much more often than VM anyway, it actually seems preferable to me to use "head only".  That way, I don't have to keep tending to the formula, changing the "url" and "shaxxx" when a new version comes out.  Am I missing anything?  

So am I understanding correctly that this should work:

```ruby
    class ViewMail < Formula
      homepage "http://www.nongnu.org/viewmail/"

      head "lp:vm", :using => :bzr

      depends_on :emacs

      def install
  	    system "./configure", "--with-emacs=#{prefix}/bin/emacs", "--prefix=#{prefix}" 
	    system "make"
	    system "make", "install"
      end
    end
```

(I'll try to wade through those docs if I find myself creating more formulae...)

**Comment by DomT4** [comment]
>  Am I missing anything?

`head-only` can't be bottled, so you'll have to build it from source every time. It's also difficult to provide technical support to `head` builds given upstream can fix/break/change/etc them at any moment.

Ultimately though, if there's no working stable version and you're happy to use a `head` version everything is great. It looks like upstream [has stable versions](https://launchpad.net/vm) but you'd need to check the latest stable version builds.

**Comment by DiagonalArg** [comment]
DomT4 - Ok, since you've been so helpful, one last question.

If I used the standard approach:

```ruby
url "https://launchpad.net/vm/8.2.x/8.2.0b/+download/vm-8.2.0b.tgz"
```

When 8.2.0b becomes 8.2.0b1, will I have to update the homebrew formula?  Or is there some automatic way that homebrew does that?  Updating is a headache I don't want, since I'll have to keep track of vm updates.  How am I going to do that?  Check the web site every two days?  *No.*  :-P

/D

**Comment by DomT4** [comment]
I presume the `a` and `b` releases are alpha and beta? In which case we want the last "stable" build.

> will I have to update the homebrew formula?

Whilst updates to formulae are always appreciated, we don't glue new formulae authors to their formulae :wink:. If you don't want to keep it updated past initial submission, there's no obligation.

**Comment by DiagonalArg** [comment]
> If you don't want to keep it updated past initial submission, there's no obligation.

Well, while I get that, the question was really whether Homebrew has some *automated* means of recognizing the presence of a new version, or whether it's up to the formula author to keep modifying the download URL.  I'm gathering it's up to the author.  In which case, if the author doesn't take up that task, someday it'll break and ... probably just be removed, right?

**Comment by DomT4** [comment]
>  whether Homebrew has some automated means of recognizing the presence of a new version

No, we don't.

>  someday it'll break and ... probably just be removed, right?

It's more likely someone will report it broken, we'll check and see there's an update available and ask the person who reported the issue to open a PR to bump the version. Removal is the last option on the table.

Am going to close this issue as it's not something that needs "fixing" by us, but please feel free to submit a PR with the formula to either here or head-only.
