### ISSUE TITLE
brew postinstall failing

### ISSUE THREAD

**Issue by ruffiem** [Homebrew/homebrew#40072]
Above mentioned. Here's a screen shot of the php56-suhosin upgrade. It's the same with ffmpeg.

Sequence :
![screenshot](https://cloud.githubusercontent.com/assets/1785492/7796961/c7212564-02e5-11e5-83b5-9dddc84499f4.png)

**Comment by DomT4** [comment]
`brew doctor` will tell you to run `Repair Disk Permissions` in the Disk Utility app. Try again after that.

**Comment by ruffiem** [comment]
I just did but why this has to be a fatal `error` ? It could be a warn just as the `brew doctor` output.

**Comment by DomT4** [comment]
It's not our failure message, so we don't control it sadly. It's actually coming from Ruby.

**Comment by ruffiem** [comment]
Thanks for the info :+1:
