### ISSUE TITLE
WIP Formula help

### ISSUE THREAD

**Issue by zbeekman** [Homebrew/homebrew#40102]
Hi,
I’d like to submit a formula for https://github.com/jacobwilliams/json-fortran and have started working on a formula using the formula cookbook and the example in contrib. I think I’m nearly at a point were I can open a PR, but I had a few questions. To see the formula I have cooked up so far check out the [gist](https://gist.github.com/zbeekman/b45e2a2f914f2820e72e)

1) Since it’s a Fortran project, I know I need the `depends => :fortran` specification, but is there a way to specify that it should be built with gfortran >= 4.9.2? I see the `fails with <:c-compiler> do … end` blocks in the `example-formula.rb` but is there a similar specification or  declaration that I can make for  Fortran compilers? I think it only really makes sense to install this with Homebrew if the default Homebrew gfortran compiler >= 4.9.2 is being used.

2) Is there a way to check if the FC environment variable has been set and issue a warning? What about testing if FC is set to gfortran >= 4.9.2? If someone is going to install this with the Intel or NAG compilers they should probably just do so directly from source themselves, rather than use Homebrew.

**Comment by dunn** [comment]
I don't know about the Fortran issue, but you don't need `mktemp` in the install block—Homebrew moves to a temporary directory automatically during the install.

**Comment by zbeekman** [comment]
@dunn Thanks for the tip, however, I do need it because by default the project disallows in source CMake builds. The purpose of the `mktemp` in the install block is to create an out-of-source build-directory for CMake to follow the usual convention.

Feedback on the two questions regarding Fortran compilers would still be much appreciated.

**Comment by iml** [comment]
`depends_on :fortran` defaults to the `gcc` formula, which is currently 5.1 It's probably safe to assume the user has a sufficiently new gfortran.  `fails_with` won't affect the Fortran compiler selection.

> 2) Is there a way to check if the FC environment variable has been set and issue a warning?

`:fortran` does display a warning if `FC`

**Comment by mikemcquaid** [comment]
> @dunn Thanks for the tip, however, I do need it because by default the project disallows in source CMake builds. The purpose of the mktemp in the install block is to create an out-of-source build-directory for CMake to follow the project’s convention.

You should just be able to create a `b` or `build` subdirectory.

> depends_on :fortran defaults to the gcc formula, which is currently 5.1 It's probably safe to assume the user has a sufficiently new gfortran.

I agree.

**Comment by zbeekman** [comment]
> You should just be able to create a b or build subdirectory.

@mikemcquaid what is the advantage of this over `mktemp`?

@iml On my system, even if FC is *NOT* set I get the warning about building with a non-standard fortran compiler. I have the Intel fortran compiler installed, and CMake finds this before it finds gfortran, so my formula has started to build with `ifort`, despite `FC` *NOT* being set. I added some hackery to work around this but something smells fishy regarding Homebrew’s Fortran configuration. See for example #31156

I have updated the latest [Gist](https://gist.github.com/zbeekman/b45e2a2f914f2820e72e) with what I have in my open PR, #40128 any tips and help would be much appreciated

**Comment by iml** [comment]
#31156 is a known bug, but it should only spam warnings for each fortran-using dependency and not actually affect the compiler. For reference this happens in `ENV.fortran`: https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/extend/ENV/shared.rb#L156-L192. 

Not sure about CMake, though.

**Comment by zbeekman** [comment]
OK, thanks for all the help everyone, especially @iml. I’m going to close this issue, because I have learned a lot and feel good about the current state of my PR, #40128
