### ISSUE TITLE
New formulas created via Cookbook are not tappable

### ISSUE THREAD

**Issue by timothybasanov** [Homebrew/homebrew#40108]
I followed Hombrew formula cookbook and now I have a non-tappable formula.

*Steps:*

1. Forking `Hombrew/homebrew` repo into `username/homebrew`
2. Creating new formula according to cookbook
3. Pushing into fork repo: `username/homebrew/Library/Formula/foo.rb`

*Expected result:* I can use formula via `brew tap username/tap ; brew install foo`

*Actual result:* Forked repo can not be accessed as a tap as it's not in `homebrew-bar` format. When renamed it still can not be accessed as `foo.rb` is not in the root directory for that repo.

*Why do I need this?* As I'm working on my formula I want to use it from different machines for testing. I also want to be able to ask my friends to test it out easily.

*Proposed solutions:*

* Create a separate `username/homebrew-foo` github repo in `/usr/local/Library/Formula`, which would be accessible
* Hack `tap` command to support finding formulas in `Library/Formula` directories as well.
* Add a separate paragraph to a cookbook to document existing behaviour.
* Encourage people to create pull requests earlier, when formula is not yet tested.

What do you think?

**Comment by bfontaine** [comment]
> Forking `Hombrew/homebrew` repo into `username/homebrew`

This is useful only if you want to make a pull-request. For taps you can just create a GitHub repository and dump your formulae in it, either directly at its root or in a `Formula/` directory.

**Comment by jacknagel** [comment]
Yeah, I think this may be overcomplicating things. Homebrew core forks aren't meant to be used as taps. We certainly aren't going to add tap support for subdirectories of Library/Formula; the long-term goal is to decouple formula from core entirely, so that would be a step backwards.

Can you just make a separate tap repo? Perhaps what would actually be useful here is a command that creates a new tap?

**Comment by mikemcquaid** [comment]
Note if you're asking friends to test this out you can ask them to install using a full URL like e.g. `brew install https://raw.githubusercontent.com/Homebrew/homebrew/master/Library/Formula/gwt.rb`

**Comment by timothybasanov** [comment]
Hi, guys, thanks all for your responses and help!
Here is a solution that I've ended with:

`~/homebrew-tap/foo.rb` where `homebrew-tap` is a github repo,
And `cp ./foo.rb /usr/local/Library/Formula/` during *build* stage in my IDE.
This way I can edit things, they are available to people outside and my local brew uses the right formula. More than that, when I'll be ready to push upstream I would be able to do it as well.

You could consider changing wiki in such a way that it would be less frustrating for the next guy like me.
(Or I can do it, but let's agree on what the changes should be)

At this point my own problems are resolved and I"m a happy brewer. This bug may be closed.

**Comment by bfontaine** [comment]
> And `cp ./foo.rb /usr/local/Library/Formula/` during build stage in my IDE.

You could avoid this step by taping your own repo.

**Comment by DomT4** [comment]
Closing per OP's request. Using a tap is the easiest way to handle situations like these - If you're duplicating Homebrew/homebrew formulae you can install using a full path, i.e. `brew install bob/example/openssl`.
