### ISSUE TITLE
vim: picks up unexpected ruby and segfaults if rug pulled

### ISSUE THREAD

**Issue by lloeki** [Homebrew/homebrew#40125]
When building vim, ruby gets statically linked. The build system picks up whatever is the active ruby, including homebrew's or a user-installed one (e.g via rbenv). Unfortunately things blow up with a segfault as soon as the linked ruby disappears or is changed. Alternatively, doing a `brew install/update vim` could silently produce surprising results since it may build against an unexpected ruby depending on your PWD. Interestingly enough, given the nature of how things get built and installed, this always seems to happen at the worst possible moment.

Test case:
```
brew install rbenv ruby-build
rbenv install 2.1.6
rbenv global 2.1.6
brew install vim
vim +':ruby puts RUBY_VERSION' +':sleep 1' +:q
rbenv uninstall 2.1.6
vim +':ruby puts RUBY_VERSION' +':sleep 1' +:q
# segfault
```

To prevent this, I'm force-building against system (or homebrew) ruby by way of stripping my `PATH` from rbenv stuff:

```
# $RBENV_ROOT is set for me, so this works
# it can be extracted from `rbenv init - | grep 'export PATH'`
export PATH=$(echo $PATH | perl -ne 'print join(":", grep(!/$ENV{"RBENV_ROOT"}/, split(":")))')
brew install vim
```

Is that a worthy task for superenv? At the very least this behaviour should be hinted at upon install with a stern warning.

**Comment by jacknagel** [comment]
>When building vim, ruby gets statically linked

You mean dynamically, right?

>Is that a worthy task for superenv? At the very least this behaviour should be hinted at upon install with a stern warning.

The vim formula uses the old build environment, intentionally so that it picks up custom ruby, perl, etc.

You can force it to use superenv: `brew install --env=super vim` (this is how I use it).

**Comment by lloeki** [comment]
> You mean dynamically, right?

For some reason `otool -L $(which vim) | grep ruby` was returning void. Found that weird indeed. I guess I should take some rest ;-)

> You can force it to use superenv: brew install --env=super vim (this is how I use it).

Great! Am I right in saying that this argument will survive a `brew update`?

**Comment by jacknagel** [comment]
`--env=super` is not a per-formula option and is thus not persisted.

I don't think there is anything for Homebrew to fix here, if you uninstall a library, things that depend on it will break.
