### ISSUE TITLE
mongodb --with-openssl failed to build on 10.10.3

### ISSUE THREAD

**Issue by cdorer** [Homebrew/homebrew#40136]
https://gist.github.com/cdorer/4c31ed2f28e16bd410ad

I also *brew cleanup; brew uninstall openssl; brew uninstall go*, and then I reinstalled mongodb --with-openssl with the same exact errors.

mongodb installed fine without the --with-openssl flag

**Comment by cdorer** [comment]
I even wiped out brew and reinstalled everything, just in case it was an issue of the Mac OS X upgrade.

**Comment by bfontaine** [comment]
It seems to be an issue with mongo-tools using `git` in its build process (see [build.sh](https://github.com/mongodb/mongo-tools/blob/master/build.sh#L22),) but we download it as an archive and not a git repo, hence the failure.

**Comment by DomT4** [comment]
>  but we download it as an archive and not a git repo, hence the failure.

We use a [go resource](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/mongodb.rb#L10-L13), which should contain the `git` folder AFAIK.

**Comment by bfontaine** [comment]
Right @DomT4, but I still think it comes from `mongo-tools`. The build log starts with:

```
2015-05-27 11:27:20 -0400
 
./build.sh
ssl
 
Building bsondump...
fatal: Not a git repository (or any of the parent directories): .git
```

This `./build.sh` and its output match `mongo-tools`’s [build.sh](https://github.com/mongodb/mongo-tools/blob/3f3078e129ac5bf01a087818109af00f4f677a35/build.sh#L19-L23). I also found [a patch](https://github.com/matijaskala/ports-2013/blob/d23ffabc9bb137390cea1ea7cb96f61ff5854379/app-admin/mongo-tools/files/mongo-tools-3.0.0-build.patch) that seems to be related to this issue.

**Comment by DomT4** [comment]
Yeah, the issue is with `mongo-tools`. I'm just not quite sure why; I thought we were permanently installing the `git` folders with the `go_resource`s now to deal with Syncthing and various other formulae hitting similar issues.

I guess we should look into applying the patch, but we may also want to file an issue upstream if the `git` folders do exist and `mongo-tools` isn't finding that for some reason.

Interestingly the build log goes on to say things like:

```
/usr/include/openssl/bio.h:279:8: note: 'bgets' has been explicitly marked deprecated here
In file included from vendor/src/github.com/spacemonkeygo/openssl/verify.c:16:
vendor/src/github.com/spacemonkeygo/openssl/bio.go:58:5: warning: 'ctrl' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
/usr/include/openssl/bio.h:280:9: note: 'ctrl' has been explicitly marked deprecated here
In file included from vendor/src/github.com/spacemonkeygo/openssl/verify.c:16:
vendor/src/github.com/spacemonkeygo/openssl/bio.go:59:5: warning: 'create' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
/usr/include/openssl/bio.h:281:8: note: 'create' has been explicitly marked deprecated here
In file included from vendor/src/github.com/spacemonkeygo/openssl/verify.c:16:
vendor/src/github.com/spacemonkeygo/openssl/bio.go:60:5: warning: 'destroy' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
```

So it doesn't actually seem to be linking into our OpenSSL.

**Comment by DomT4** [comment]
#40217 works for me from source with the SSL option enabled. Feel free to take it for a test :car:.
