### ISSUE TITLE
Elasticsearch Formula doesn't use alternate homebrew path in config

### ISSUE THREAD

**Issue by larkin** [Homebrew/homebrew#40141]
When running homebrew from a nonstandard brew directory (e.g. a `.homebrew` directory in the user's home directory), the caveats section of the install says that the data, logs, plugin, and config directories are properly set to that folder, but the actual elasticsearch config file continues to point to /usr/local/var.

`brew info elasticsearch` shows correct paths:
```bash
› brew info elasticsearch
elasticsearch: stable 1.5.2 (bottled), HEAD
https://www.elastic.co/products/elasticsearch
/Users/larkin/.homebrew/Cellar/elasticsearch/1.5.2 (34 files, 29M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/elasticsearch.rb
==> Caveats
Data:    /Users/larkin/.homebrew/var/elasticsearch/elasticsearch_larkin/
Logs:    /Users/larkin/.homebrew/var/log/elasticsearch/elasticsearch_larkin.log
Plugins: /Users/larkin/.homebrew/var/lib/elasticsearch/plugins/
Config:  /Users/larkin/.homebrew/etc/elasticsearch/

To reload elasticsearch after an upgrade:
    launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.elasticsearch.plist
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.elasticsearch.plist
Or, if you don't want/need launchctl, you can just run:
    elasticsearch --config=/Users/larkin/.homebrew/opt/elasticsearch/config/elasticsearch.yml

```

`/Users/larkin/.homebrew/etc/elasticsearch/elasticsearch.yml` shows paths as being the same as before:

```
#################################### Paths ####################################

# Path to directory containing configuration (this file and logging.yml):
#
#path.conf: /path/to/conf

# Path to directory where to store index data allocated for this node.
#
path.data: /usr/local/var/elasticsearch/
#
# Can optionally include more than one location, causing data to be striped across
# the locations (a la RAID 0) on a file level, favouring locations with most free
# space on creation. For example:
#
#path.data: /path/to/data1,/path/to/data2

# Path to temporary files:
#
#path.work: /path/to/work

# Path to log files:
#
path.logs: /usr/local/var/log/elasticsearch/

# Path to where plugins are installed:
#
path.plugins: /usr/local/var/lib/elasticsearch/plugins
```

The result of this is elasticsearch doesn't load fully, doesn't log errors, and it's not easy to figure out why it's not responding to requests.

Let me know if I can provide any additional information.

**Comment by bfontaine** [comment]
Is `etc/elasticsearch/elasticsearch.yml` the only file affected by this issue?

**Comment by larkin** [comment]
@bfontaine it looks like it, the only other two files processed by `inreplace` have proper substitutions.  

Though to be fair, none of them are trying to use `var` in paths; they're just using `prefix`.  But the caveat uses `var` as well and gets the proper value; I'm not sure why the `var` value would be different during `install` and during `caveat`?

**Comment by mikemcquaid** [comment]
Fixed, the issue was with the bottle so I removed it.
