### ISSUE TITLE
pygobject  SHA1 mismatch

### ISSUE THREAD

**Issue by liuyuqiang** [Homebrew/homebrew#40154]
brew install Meld
==> Installing dependencies for meld: pygobject, py2cairo, pygtk, gtksourceview, pygtksourceview
==> Installing meld dependency: pygobject
==> Downloading http://ftp.gnome.org/pub/GNOME/sources/pygobject/2.28/pygobject-2.28.6.tar.bz2
Already downloaded: /Library/Caches/Homebrew/pygobject-2.28.6.tar.bz2
==> Downloading http://git.gnome.org/browse/pygobject/patch/gio/gio-types.defs?id=42d01f060c5d764baa881d13c103d68897163a49
Already downloaded: /Library/Caches/Homebrew/pygobject--patch-6976bbad5212ae775e6715405e0e70e592356db2.defs
Error: SHA1 mismatch
Expected: 6976bbad5212ae775e6715405e0e70e592356db2
Actual: 66411f0251ac036f33239591cf3c4c0a50ccab30
Archive: /Library/Caches/Homebrew/pygobject--patch-6976bbad5212ae775e6715405e0e70e592356db2.defs
To retry an incomplete download, remove the file above.

**Comment by mistydemeo** [comment]
Please `brew update` - this issue has been fixed. Thanks for the report!
