### ISSUE TITLE
loading same name formulae from different taps should be possible

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew#40151]
Since we load all formulae class inside the same namespace, we cannot load formulae with same class name. For example.
```
$ head -4 /tmp/tree.rb
require 'formula'

class Tree < Formula
  version "1.8.0"

$ brew pry
==> Interactive Homebrew Shell
Example commands available with: brew pry --examples
[1] brew(main)> f1 = Formulary.factory("tree")
=> #<Formula tree (stable) /usr/local/Library/Formula/tree.rb>
[2] brew(main)> f2 = Formulary.factory("/tmp/tree.rb")
=> #<Formula tree (stable) /tmp/tree.rb>
[3] brew(main)> f1.version
=> #<Version::FromURL:0x007f8f943029f8 @version="1.7.0">
[4] brew(main)> f2.version
=> #<Version::FromURL:0x007f8f943029f8 @version="1.7.0">
```

The solution would be loading them in separate namespace. Instead of making `Tree` class inside `Formulary::Formulae`, we could load them inside `Formulary::Formulae::NS#{sha1_of_path[0..7]}`.

Another advantage is that it will resolve the custom `Requirement` name conflicts problem.

ping @jacknagel

**Comment by jacknagel** [comment]
https://github.com/Homebrew/homebrew/compare/master...jacknagel:namespace

**Comment by xu-cheng** [comment]
:+1:

**Comment by jacknagel** [comment]
Simplified the implementation (caching formula classes directly rather than the parent modules).
