### ISSUE TITLE
Find a way to detect formulae with name conflicts inside official Taps

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew#40152]
Since #39524 is merged, formulae with name conflicts inside official Taps would be hard to detect. We need to find a way to detect that. Maybe adding into `brew audit` or `brew readall`. The trick part is how to suppress such error during the formula migration? Any thoughts @Homebrew/owners @bfontaine @DomT4.

**Comment by mikemcquaid** [comment]
I'm thinking we add a mode to `brew audit` that does online queries (and is off by default) that could work for stuff like this.
