### ISSUE TITLE
sqlitebrowser options?

### ISSUE THREAD

**Issue by dmofot** [Homebrew/homebrew#40161]
Is it possible to have an option for the sqlitebrowser formula to install the sqlitebrowser-with_sqlcipher_support version?

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by jacknagel** [comment]
Would review a PR.
