### ISSUE TITLE
htop needs suid bit set and root ownership to actually work.  

### ISSUE THREAD

**Issue by alanhoyle** [Homebrew/homebrew#40166]
htop, as currently installed, doesn't actually work to show details on currently running processes unless you run "sudo htop". This can be fixed permanently by running the following commands post-build:
```
[alanh@MyMac ~]$ sudo chown root /usr/local/Cellar/htop-osx/0.8.2.5/bin/htop
[alanh@MyMac ~]$ sudo chmod u+s /usr/local/Cellar/htop-osx/0.8.2.5/bin/htop
```
which leads to:
```
[alanh@MyMac ~]$ ls -l /usr/local/Cellar/htop-osx/0.8.2.5/bin/htop
 -r-sr-xr-x 1 root 112304 May  6 10:19 /usr/local/Cellar/htop-osx/0.8.2.5/bin/htop*
``` 

and htop actually displays information about all running processes.

**Comment by bfontaine** [comment]
Homebrew doesn’t use `sudo`, we’re showing this issue in the caveats:

```
$ brew info htop
(…)
==> Caveats
htop-osx requires root privileges to correctly display all running processes.
so you will need to run `sudo htop`.
You should be certain that you trust any software you grant root privileges.
```

**Comment by mistydemeo** [comment]
See also the previous discussion in #23150. We can't change this within Homebrew, because Homebrew doesn't run as root. Sorry!
