### ISSUE TITLE
phpenv package kind of deploys rbenv files?

### ISSUE THREAD

**Issue by ydesgagn** [Homebrew/homebrew#40164]
Hi,

The following commands kind of installs rbenv instead of phpenv?

Yves-MBP:~ yves$ rm -rf ~/.phpenv
Yves-MBP:~ yves$ brew install phpenv
==> Installing phpenv from homebrew/homebrew-php
==> Downloading https://github.com/CHH/phpenv/archive/01a2c1e25096f8ff10f2f78142
Already downloaded: /Library/Caches/Homebrew/phpenv-01a2c1e.tar.gz
==> /usr/local/Cellar/phpenv/01a2c1e/bin/phpenv-install.sh
==> Caveats
To finish installing phpenv:
 * Add ~/.phpenv/bin to your $PATH
 * Add "eval $(phpenv init -)" at the end of your ~/.bashrc
 * Restart your shell
==> Summary
🍺  /usr/local/Cellar/phpenv/01a2c1e: 6 files, 24K, built in 2 seconds

Yves-MBP:~ yves$ ls ~/.phpenv
LICENSE		bin		libexec		src
README.md	completions	rbenv.d		test
Yves-MBP:~ yves$ ls ~/.phpenv/libexec/
rbenv				rbenv-sh-rehash
rbenv---version			rbenv-sh-shell
rbenv-commands			rbenv-shims
rbenv-completions		rbenv-version
rbenv-exec			rbenv-version-file
rbenv-global			rbenv-version-file-read
rbenv-help			rbenv-version-file-s
rbenv-hooks			rbenv-version-file-write
rbenv-init			rbenv-version-name
rbenv-local			rbenv-version-origin
rbenv-local-s			rbenv-versions
rbenv-prefix			rbenv-whence
rbenv-rehash			rbenv-which
rbenv-root

**Comment by mistydemeo** [comment]
>  ==> Installing phpenv from homebrew/homebrew-php

Please report this to [homebrew-php](https://github.com/Homebrew/homebrew-php) - thanks!
