### ISSUE TITLE
`brew doctor` suggests linking a keg-only formula (libffi)

### ISSUE THREAD

**Issue by jh2858** [Homebrew/homebrew#40171]
I'll report this one just in case it turns out to be a symptom of a bigger issue.  It's a weird thing where `brew doctor` recommends linking a keg-only formula, libffi, then (rightly) becomes unhappy when you do.

    > brew doctor
    [...clipped...]

    Warning: You have unlinked kegs in your Cellar
    Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
    those kegs to fail to run properly once built. Run `brew link` on these:

    libffi
Okay, let's link it.

    > brew link libffi
    Linking /usr/local/Cellar/libffi/3.0.13... 9 symlinks created
Now `brew doctor` again:

    > brew doctor
    [...clipped...]

    Warning: Some keg-only formula are linked into the Cellar.
    Linking a keg-only formula, such as gettext, into the cellar with
    `brew link <formula>` will cause other formulae to detect them during
    the `./configure` step. This may cause problems when compiling those
    other formulae.

    Binaries provided by keg-only formulae may override system binaries
    with other strange results.

    You may wish to `brew unlink` these brews:

    libffi

**Comment by mistydemeo** [comment]
Fixed, thanks for the report!
