### ISSUE TITLE
Packer fails to acquire dependencies

### ISSUE THREAD

**Issue by tduehr** [Homebrew/homebrew#40199]
I get the following when attempting to install packer

```
Cloning into '/Library/Caches/Homebrew/packer--golang.org-x-crypto--git'...
fatal: unable to access 'https://go.googlesource.com/crypto.git/': SSL: certificate verification failed (result: 5)
Error: Failed to download resource "packer--golang.org-x-crypto"
Failure while executing: git clone https://go.googlesource.com/crypto.git /Library/Caches/Homebrew/packer--golang.org-x-crypto--git
```

That's both with and without brew's curl installed and not linked to openssl.

If I have brew's curl linked to brew's openssl I get:

```
Cloning into '/Library/Caches/Homebrew/packer--golang.org-x-crypto--git'...
fatal: unable to access 'https://go.googlesource.com/crypto.git/': SSL certificate problem: unable to get local issuer certificate
Error: Failed to download resource "packer--golang.org-x-crypto"
Failure while executing: git clone https://go.googlesource.com/crypto.git /Library/Caches/Homebrew/packer--golang.org-x-crypto--git
```

I am able to use system git and curl directly to grab this repo.

**Comment by bfontaine** [comment]
I’m not able to reproduce this locally

```
$ brew fetch packer --build-from-source
…snip…
Cloning into '/Library/Caches/Homebrew/packer--golang.org-x-crypto--git'...
remote: Total 1893 (delta 1199), reused 1893 (delta 1199)
Receiving objects: 100% (1893/1893), 1.38 MiB | 739.00 KiB/s, done.
Resolving deltas: 100% (1199/1199), done.
Checking connectivity... done.
```

Could you run `brew gist-logs packer` and post a link to the gist here? Thanks!

**Comment by mistydemeo** [comment]
Homebrew's git uses the system certificate chain. Do you have any custom certificates installed in Keychain? What version of OS X are you on?

**Comment by DomT4** [comment]
> If I have brew's curl linked to brew's openssl I get:

This is likely going to be the behaviour we hit before with Google's cert issues post 10.10.3 release. Try `brew reinstall openssl` and see if the issue persists on this particular configuration.

**Comment by tduehr** [comment]
```
Deneb:~ eroot$ brew gist-logs packer
Error: No logs.
```

after reinstalling curl, libressl, openssl and git.

 * `git --with-brewed-curl $$ curl --with-libressl` fails
 * `git --with-brewed-curl $$ curl --with-openssl` succeeds
 * `git --with-brewed-curl --with-brewed-openssl $$ curl --with-openssl` succeeds
 * `git` without curl or openssl fails
 * `git --with-openssl` fails
 * no git, no curl succeeds
 * `HOMEBREW_GIT=/usr/bin/git brew install packer` succeeds
 * `git --with-brewed-curl --with-brewed-openssl $$ curl --with-[everything]` succeeds
 * `git --with-[everything] $$ curl --with-[everything]` succeeds

**Comment by DomT4** [comment]
> git without curl or openssl fails

This is the only surprise out of everything you posted there. Theoretically, `git` should be fine natively because it hooks the Security Framework.

There's a new OpenSSL landing later today which should shake off any remaining OpenSSL issues. LibreSSL will continue to fail on Google domains until they do something with that upstream - It has been reported.

**Comment by tduehr** [comment]
git without curl or openssl is working for me now.
