### ISSUE TITLE
Fortran doesn't naively install appropriately

### ISSUE THREAD

**Issue by People-Places-and-Things** [Homebrew/homebrew#40193]
I did not know where to post this, so sorry if I fail you, excuse me, my english is not so great.  *Homebrew* does not properly install a number of libraries with the current version of *GCC* (4.2.1) available via *Homebrew*  because *Homebrew* has probably not accounted for the *GCC* exclusion of *Fortran*.  As such to properly run a number of "taps" or "kegs" (or whatever the generic term for Octave and LAMMPS) it is necessary to install Fortran by hand with the following command:
`<brew install gcc --with-fortran>`
Edit: this was on Os X Yosemite

**Comment by DomT4** [comment]
The current version of `gcc` shipped by Homebrew/homebrew is GCC-5. Are you referencing the Apple-gcc42 formula in [Homebrew/dupes](https://github.com/Homebrew/homebrew-dupes/blob/master/apple-gcc42.rb)?

**Comment by tdsmith** [comment]
`brew install gcc` will install gfortran. If this does not appear to be the case for you, please be sure you've run `brew update` recently.

**Comment by tdsmith** [comment]
Let us know if we can help with anything.
