### ISSUE TITLE
Use maintained fork of ctags

### ISSUE THREAD

**Issue by ptzz** [Homebrew/homebrew#40200]
There are ancient bugs still present in the official 5.8 release (from 2009) e.g. http://sourceforge.net/p/ctags/bugs/264/. It is solved in HEAD but perhaps the formula could be switched to a maintained fork such as https://github.com/fishman/ctags instead?

**Comment by mistydemeo** [comment]
This was previously discussed in #27413. The other project has not made any stable releases and isn't an "official" fork, so we decided not to make a change at that time. Looks like there haven't been any stable releases there in the past year, either.

**Comment by ptzz** [comment]
Sorry for the duplicate and thanks for the prompt reply :+1:
