### ISSUE TITLE
Unable to use yara-python with brew'd yara

### ISSUE THREAD

**Issue by blacktop** [Homebrew/homebrew#40254]
@sroberts I think this might be because of where brew'd yara is storing it's files yara.so etc? 

If I install yara from source on my Mac it works fine.

I wonder if it is possible for you to also install yara-python with yara in one brew formula?

formula ref: https://github.com/Homebrew/homebrew/blob/570671735272b4a6be9746b65d2f58b8eac08042/Library/Formula/yara.rb

yara issue: https://github.com/plusvic/yara/issues/317

**Comment by tdsmith** [comment]
The yara formula already installs yara-python. You can use it in your virtualenv with --system-site-packages.

**Comment by tdsmith** [comment]
I can't reproduce this:

```
rocketman:homebrew tim (master)$ mktmpenv
New python executable in tmp-3412705945af49de/bin/python2.7
Also creating executable in tmp-3412705945af49de/bin/python
Installing setuptools, pip, wheel...done.
This is a temporary environment. It will be deleted when you run 'deactivate'.

(tmp-3412705945af49de)rocketman:tmp-3412705945af49de tim$ pip -V
pip 7.0.1 from /Users/tim/.virtualenvs/tmp-3412705945af49de/lib/python2.7/site-packages (python 2.7)
(tmp-3412705945af49de)rocketman:tmp-3412705945af49de tim$ pip install -q yara
(tmp-3412705945af49de)rocketman:tmp-3412705945af49de tim$ python -c "import yara"
(tmp-3412705945af49de)rocketman:tmp-3412705945af49de tim$ brew info yara
yara: stable 3.3.0 (bottled), HEAD
https://github.com/plusvic/yara/
/usr/local/Cellar/yara/3.3.0 (36 files, 1.2M) *
  Poured from bottle
...
```

**Comment by blacktop** [comment]
@tdsmith You are right if I use --system-site-packages it does work!  Thanks!

I was able to have it error again the other way:
```bash
$ brew install yara
$ mkvirtualenv yara-test
(yara-test)$ cd yara/yara-python
(yara-test)$ python setup.py build install
(yara-test)$ python
>>> import yara
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/user/.virtualenvs/yara-test2/lib/python2.7/site-packages/yara.so, 2): Symbol not found: _yr_rules_load_stream
  Referenced from: /Users/user/.virtualenvs/yara-test2/lib/python2.7/site-packages/yara.so
  Expected in: flat namespace
 in /Users/user/.virtualenvs/yara-test2/lib/python2.7/site-packages/yara.so
```

**Comment by blacktop** [comment]
Oh I think why you couldn't recreate it is because the version of yara in pip is **VERY** old, 1.7, the current version is 3.3.0.

**Comment by tdsmith** [comment]
Weird; I can't reproduce this installing from the 3.3.0 tarball either.

**Comment by blacktop** [comment]
I am using virtualenvwrapper, would that make any difference?

**Comment by tdsmith** [comment]
So am I; it shouldn't.

**Comment by blacktop** [comment]
python 2.7.10, OSX Yosemite?

**Comment by tdsmith** [comment]
[Yep](https://gist.github.com/a364ba9140748c68c5da)!

**Comment by tdsmith** [comment]
I'm using a clean yara source tree to build the Python module from so the linker is finding the one that Homebrew installed; maybe that makes a difference?

**Comment by blacktop** [comment]
you mean you are python setup.py install -ing from a folder that has never been .configure/make/make installed? Or do you mean you are running on a Mac that has never had yara installed via non-brew ?

**Comment by tdsmith** [comment]
The former.

**Comment by Grazfather** [comment]
I think this I still an issue: We shouldn't need to use `--system-site-packages` to get this to work. Not sure if this is more of a brew bug or a yara bug. plusvic/yara#317 was also filed by @blacktop, I'm just voting to re-open it.

**Comment by tdsmith** [comment]
It is not a bug that you need to use --system-site-packages to access a module that was installed to a system location by Homebrew. If something else is amiss please open a new ticket against homebrew-core. Thanks!
