### ISSUE TITLE
brew doctor Error: No available formula for findutils

### ISSUE THREAD

**Issue by MatzFan** [Homebrew/homebrew#40266]
Just ran `brew doctor` and got this error, brew, CLT up to date.
[Gist](https://gist.github.com/MatzFan/0a1010601d04fb77b4ab).

**Comment by tdsmith** [comment]
If you don't have any local changes to your Homebrew formulae that you want to keep, I think `cd $(brew --repository) && git reset --hard origin/master` should resolve this.

**Comment by MatzFan** [comment]
Yup, that did it, many thanks Tim - ready to brew again :smile:
