### ISSUE TITLE
could the sed recipe also install an alias gsed to sed ?

### ISSUE THREAD

**Issue by UnixJunkie** [Homebrew/homebrew#40267]
I think the sed recipe installs GNU sed.
Installing a soft link to it called gsed would allow users
to force using GNU sed on macs easily.

I think the make recipe installs gmake; this is in the same vein.

**Comment by jacknagel** [comment]
The only sed in homebrew is the gnu-sed formula that installs itself as `gsed`, not `sed`. It has a `--with-default-names` option that installs it as `sed`.
