### ISSUE TITLE
pup.rb recipe is wrong

### ISSUE THREAD

**Issue by ericchiang** [Homebrew/homebrew#40270]
There are no outside dependencies when building for a single architecture besides Go [problem here](
https://github.com/Homebrew/homebrew/blob/629e291dddc6eda1449a98f6de701c33daec846d/Library/Formula/pup.rb#L19-L51)

1) You don't need gox to compile for a single architecture.
2) All import paths are rewritten through [godep](https://github.com/tools/godep), you just need to run `go install` or `go build -o pup`.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by DomT4** [comment]
Closing here. Welcome a PR to resolve the issues highlighted.
