### ISSUE TITLE
mongodb --with-openssl failed to build on 10.10.3

### ISSUE THREAD

**Issue by cdorer** [Homebrew/homebrew#40278]
The problem still exists: https://github.com/Homebrew/homebrew/issues/40136

https://gist.github.com/cdorer/5aea5c5481ced03de68f

I also brew cleanup; brew uninstall openssl; brew uninstall go, and then I reinstalled mongodb --with-openssl with the same exact errors.

mongodb installed fine without the --with-openssl flag

**Comment by DomT4** [comment]
Try reinstalling `go`. I couldn't reproduce this problem on two different machines, one of which was clean beforehand.

**Comment by cdorer** [comment]
I have.  After brew uninstall and then install mongodb --with-openssl and bew install go.  Still no go.

What's the best to wipeout and cleanest way aside from rm -Rfv-ing the entire /usr/local dir?

**Comment by DomT4** [comment]
Are you building `go` from source or from-bottle? `brew remove go --force && brew cleanup && brew prune` would remove go, clean up any old versions you have lying around and prune any dead symlinks, etc.

**Comment by cdorer** [comment]
From bottle.

Followed your instructions and then I ```brew install mongodb --with-openssl```. Still failure.  This time a little more weirdness.

Prompt commands and output.
https://gist.github.com/cdorer/5707e8d03c50756e5e52

**Comment by cdorer** [comment]
Ok.  Found the issue by accident, really.  A colleague said he didn't have issues compiling.  He tried again after Digital Guardian(https://digitalguardian.com) was installed, and it failed for some reason in conflict with go.

The solution:

Check if you have it running: ```kextstat | grep dg```
You should see something like: 
```  138    0 0xffffff7f82f4c000 0x35000    0x35000    com.verdasys.dgagent (3046.23.6) <23 5 4 3 1>```
If you have it, turn it off ```sudo kextunload -b com.verdasys.dgagent```

Then run: ```brew install mongodb --with-openssl```

Success!

**Comment by cdorer** [comment]
Ooops.  Re-opening.  Project admins, you close it if you feel this is sufficient and you've talked it through.

**Comment by cdorer** [comment]
https://groups.google.com/forum/#!topic/golang-nuts/HtcZc3wO-rw relates to this issue. They provide a different solution but at the end of the day dg crashes go with the same error you were getting "fatal error: runtime: bsdthread_register error"

**Comment by tdsmith** [comment]
I don't think we should do anything at this point. It would be good to report this to Digital Guardian. Thanks for letting us know!

**Comment by jianghaitao** [comment]
@cdorer Thanks for this post. It actually help me on a getting fly binaries to run :+1:
