### ISSUE TITLE
Error (SHA256 mismatch) when I install tcllib_1_16 (tcl, tk and pymol)

### ISSUE THREAD

**Issue by cygx1xue** [Homebrew/homebrew#40280]
I got an error when I install tcllib_1_16 (tcl, tk and pymol).

==> ./configure --prefix=/usr/local/Cellar/tcl-tk/8.6.4 --mandir=/usr/local/Cellar/tcl-tk/8.6.4/share/man --enable-threads --enable-64bit
==> make
==> make install
==> make install-private-headers
==> Downloading https://downloads.sourceforge.net/project/tcl/Tcl/8.6.4/tk8.6.4-src.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/tcl-tk/8.6.4 --mandir=/usr/local/Cellar/tcl-tk/8.6.4/share/man --with-tcl=/usr/local/Cellar/tcl-tk/8.6.4/lib --enable-threads --enable-6
==> make TK_LIBRARY=/usr/local/Cellar/tcl-tk/8.6.4/lib
==> make install
==> make install-private-headers
==> Downloading https://github.com/tcltk/tcllib/archive/tcllib_1_16.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: f500a3ee2082e105693e775c8d94d9f3ab5ae687f706a7b0f6d89ec884332456
Actual: c36bcd98342abcde382e208ae1ab72d57698025ee0d9072c5ca87b1da2d20f57

**Comment by bfontaine** [comment]
I can reproduce here:

```
$ curl -sL https://github.com/tcltk/tcllib/archive/tcllib_1_16.tar.gz | shasum -a 256
c36bcd98342abcde382e208ae1ab72d57698025ee0d9072c5ca87b1da2d20f57  -
```

**Comment by cygx1xue** [comment]
I modified the tcl-tk.rb file by myself. Problem seems disappear. So, did we have a wrong sha256 number for tcllib_1_16.tar.gz?

**Comment by mistydemeo** [comment]
It was previously correct; it's possible the release was retagged. There's a 1.17 now, so we could simply upgrade to that.
