### ISSUE TITLE
Cannot use gnupg2 with pinentry-mac without dirty symlink play

### ISSUE THREAD

**Issue by proski** [Homebrew/homebrew#40288]
I installed pinentry-mac, but I still get a curses-based prompt for the password. gpg2 is missing the --pinentry-program option. The option is documented in the texinfo documentation (info gpg) but doesn't work:

    $ gpg2 --pinentry-program /usr/local/bin/pinentry-mac --decrypt --output file.txt file
    gpg: invalid option "--pinentry-program"

The only way to get pinentry-mac to work is to replace /usr/local/Cellar/pinentry/0.9.2/bin/pinentry with a link to /usr/local/bin/pinentry-mac, which is very ugly. Replacing /usr/local/bin/pinentry has no effect.

Ideally, pinentry-mac should be picked up automatically if it's installed. Specific versions of pinentry (0.9.2 in this case) should not be hardcoded.

**Comment by jacknagel** [comment]
The recommended solution is to use your gpg-agent configuration file:

```
$ cat ~/.gnupg/gpg-agent.conf
pinentry-program /usr/local/bin/pinentry-mac
```

**Comment by proski** [comment]
It fails too:

    $ gpg2 --decrypt --output file.txt file
    gpg: /Users/prroskin/.gnupg/gpg.conf:1: invalid option

I'm using up-to-date packages:

    gnupg2 2.0.27
    gpg-agent 2.0.27
    pinentry 0.9.2
    pinentry-mac 0.8.1

**Comment by jacknagel** [comment]
gpg-agent.conf, not gpg.conf

**Comment by proski** [comment]
Yes, it's working now! Sorry, I misread your message. I was also wrong about the "--pinentry-program" option. I was looking for "pinentry" in `info gpg` and didn't realize that the documentation I found was for gpg-agent.

I still believe that pinentry-mac should be easier to set up, but this bug is mostly invalid.

**Comment by jacknagel** [comment]
Suggestions are welcome, perhaps an option to use pinentry-mac by default.
