### ISSUE TITLE
boost (dependency for ledger) failed to build on 10.6.8

### ISSUE THREAD

**Issue by halliwilljustin** [Homebrew/homebrew#40319]
https://gist.github.com/anonymous/41eb070a2a7e050226a9

==> Installing dependencies for ledger: boost, boost-python
==> Installing ledger dependency: boost
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.58.0/boo
Already downloaded: /Library/Caches/Homebrew/boost-1.58.0.tar.bz2
==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost/1.58.0 --libdir=/usr/local/C
==> ./b2 --prefix=/usr/local/Cellar/boost/1.58.0 --libdir=/usr/local/Cellar/boos
...skipped <pbin.v2/libs/wave/build/darwin-4.2.1/release/link-static>libboost_wave.a for lack of <pbin.v2/libs/wave/build/darwin-4.2.1/release/link-static>instantiate_cpp_exprgrammar.o...
...skipped <p/usr/local/Cellar/boost/1.58.0/lib>libboost_wave.a for lack of <pbin.v2/libs/wave/build/darwin-4.2.1/release/link-static>libboost_wave.a...
...failed updating 526 targets...
...skipped 573 targets...
...updated 11706 targets...
/usr/local/Library/Homebrew/build.rb:181:in `dump': can't dump anonymous class #<Module:0x1011dea28>::Boost (TypeError)
	from /usr/local/Library/Homebrew/build.rb:181
Error: marshal data too short
Please report this bug:
    https://git.io/brew-troubleshooting

**Comment by mistydemeo** [comment]
```
cc1plus: error: unrecognized command line option "-std=c++11"
...failed darwin.compile.c++ bin.v2/libs/atomic/build/darwin-4.2.1/release/threading-multi/lockpool.o...
...skipped <pbin.v2/libs/atomic/build/darwin-4.2.1/release/threading-multi>libboost_atomic-mt.dylib for lack of <pbin.v2/libs/atomic/build/darwin-4.2.1/release/threading-multi>lockpool.o...
...skipped <p/usr/local/Cellar/boost/1.58.0/lib>libboost_atomic-mt.dylib for lack of <pbin.v2/libs/atomic/build/darwin-4.2.1/release/threading-multi>libboost_atomic-mt.dylib...
common.copy /usr/local/Cellar/boost/1.58.0/include/boost/mpl/aux_/config/overload_resolution.hpp
```

Looks like it's trying to build C++11, which isn't compatible with your compiler.

**Comment by mistydemeo** [comment]
Ledger specifies that boost should be built with C++11, but compiler failures aren't set up to select something C++11 compatible.

**Comment by halliwilljustin** [comment]
@mistydemeo Thanks for pinpointing that for me! and @tdsmith thanks for the solution!
