### ISSUE TITLE
composer missing composer.phar link

### ISSUE THREAD

**Issue by grosch** [Homebrew/homebrew#40313]
When doing a brew install of composer, the composer.phar file is not linked into /usr/local/bin.  Would you please add that?

The composer people told me it's not their deal, and i had to open an issue with you.

**Comment by mistydemeo** [comment]
This issue was moved to Homebrew/homebrew-php#1768

**Comment by mistydemeo** [comment]
Moved this issue to homebrew/php - thanks for the report!

**Comment by alanthing** [comment]
Resolved in https://github.com/Homebrew/homebrew-php/commit/cea7de9ae92d6b6603ea52accbef5c50ddaf6d72
