### ISSUE TITLE
gpg-agent

### ISSUE THREAD

**Issue by raggi** [Homebrew/homebrew#40316]
Post installation text says:

```
Remember to add "use-standard-socket" to your ~/.gnupg/gpg-agent.conf
file.

```

But the option is no longer required, see https://www.gnupg.org/documentation/manuals/gnupg/Agent-Options.html

**Comment by dunn** [comment]
Looks like that's with gnupg 2.1.x, which is currently only available in [`homebrew/versions`](https://github.com/Homebrew/homebrew-versions).  The version in the [`gnupg2.rb`](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gnupg2.rb) formula here is 2.0.27.

**Comment by DomT4** [comment]
> Since GnuPG 2.1 the standard socket is always used. These options have no more effect. The command gpg-agent --use-standard-socket-p will thus always return success.

The `gnupg21` formula in Versions needs a tiny tiny tweak to the `caveat` wording though.
