### ISSUE TITLE
gnupg2 should use pinentry-mac if it's available

### ISSUE THREAD

**Issue by proski** [Homebrew/homebrew#40334]
It should not be necessary to configure gnupg2 to make it use `pinentry-mac`. I cannot imagine why `pinentry-mac` would be a worse choice than `pinentry-curses`. If `pinentry-mac` is installed, it should be used, unless `pinentry-program` in `.gnupg/gpg-agent.conf` specifies another program.

**Comment by DomT4** [comment]
A PR to make the change is more ideal than an issue - Easier to discuss an implementation rather than an idea.

Making the existing `pinentry` dependency `:recommended` and adding a new `:optional` dep for `pinentry-mac` seems fair, but we'd need to add a conditional caveat to warn people to update their `gpg-agent.conf` file if they're using a non-curses `pinentry`.

**Comment by mikemcquaid** [comment]
Closing in favour of a PR.

**Comment by proski** [comment]
I tried to make the changes. It's the first time I'm touching homebrew build system. Is it OK to hardcode `/usr/local/bin/pinentry-mac` or would in be better to find the location of `pinentry-mac` at the runtime? What's the way to find the homebrew bin directory (/usr/local/bin by default) programmatically? Or should I just search PATH for `pinentry-mac`? As is stands now, the path of the unlinked pinentry is hardcoded (`/usr/local/Cellar/pinentry/0.9.4/bin`). Is it a requirement? Or should it be avoided?

The git version of gnupg (2.1.5+) uses a special function to search for pinentry. If an upgrade to gnupg 2.1.x is planned, I could wait until it's done, as a conflict with my patch would be inevitable.

**Comment by DomT4** [comment]
> Is it OK to hardcode /usr/local/bin/pinentry-mac

You want `#{Formula["pinentry-mac"].opt_bin}/pinentry-mac` here. `HOMEBREW_PREFIX/"bin"` isn't actually in the `$PATH` during compile. `opt` also shouldn't break across updates.
