### ISSUE TITLE
pinentry-mac does not reveal the whole password

### ISSUE THREAD

**Issue by proski** [Homebrew/homebrew#40336]
Type `12345` in pinentry-mac. Five dots are shown. Select on "Show typing". `1` is shown. Unselect "Show typing". Five dots are shown again. The user does not know whether `12345` or `1` would be used and why `2345` was ignored. One possible use of "Show typing" would be to reveal the password briefly while nobody else is looking. This bug makes it impossible.

**Comment by jacknagel** [comment]
Please report this to the pinentry-mac authors (i.e. the GPGTools project).

**Comment by proski** [comment]
The fix is in the git repository since December 2014: https://github.com/GPGTools/pinentry-mac/commit/98d883de855ca543cf6989665527e9cabfa6ebd4
But there has been no release since then.

**Comment by mikemcquaid** [comment]
@proski It'd be good to add https://github.com/GPGTools/pinentry-mac/commit/98d883.patch as a `patch do` in the formula. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by proski** [comment]
HomeBrew has Pinentry 0.9.4 now, which fixes the issue.
