### ISSUE TITLE
Glassfish SHA1 mismatch

### ISSUE THREAD

**Issue by roylee0704** [Homebrew/homebrew#40344]
Error: SHA1 mismatch
Expected: 704a90899ec5e3b5007d310b13a6001575827293
Actual: c2a6f1ee99f644fb63fecbeb13c866f0ad70bd1b

**Comment by bfontaine** [comment]
I can’t reproduce:

```
curl -sL http://dlc.sun.com.edgesuite.net/glassfish/4.1/release/glassfish-4.1.zip | sha1sum
704a90899ec5e3b5007d310b13a6001575827293  -
```

**Comment by DomT4** [comment]
Fine here as well.

**Comment by roylee0704** [comment]
roylees-MBP:local roylee$ brew fetch glassfish
==> Downloading http://dlc.sun.com.edgesuite.net/glassfish/4.1/release/glassfish-4.1.zip
Already downloaded: /Library/Caches/Homebrew/glassfish-4.1.zip
SHA1: c2a6f1ee99f644fb63fecbeb13c866f0ad70bd1b
SHA256: 5b74458428e035d8bd2b96325510347df2f419d393f5ae155b4a75780ba3a0ac
Warning: Formula reports different SHA1: 704a90899ec5e3b5007d310b13a6001575827293

**Comment by DomT4** [comment]
Do you have a `.curlrc` file? Anything from `brew doctor`? It's most likely an intermittent network issue between you and the server.

**Comment by roylee0704** [comment]
where can I locate the `.curlrc` file? `brew doctor` says 'Your system is ready to brew`. Hmm so how can I go about this?

p/s: Im on mac.

**Comment by DomT4** [comment]
If there's no Doctor warning you don't have one. We look for it because of the issues it can cause.

If you can reproduce the unexpected checksum outside of Homebrew it's almost certainly a local network error that'll probably clear up in the next few hours.

**Comment by roylee0704** [comment]
I guessed its probably due to the local network error, and after clean up the previous downloaded `zip`, and re install, everything is fine now.

**Comment by DomT4** [comment]
Great! Glad the issue self-resolved for you, and thanks for reporting the checksum error - Even if it turns out to be a local issue it's useful for us to double check upstream haven't been compromised, etc.
