### ISSUE TITLE
mpv build fails, missing development files for libass

### ISSUE THREAD

**Issue by ingmarv** [Homebrew/homebrew#40343]
Output of "brew install mpv --debug | tee -a ~/mpv-fail.log":

==> Installing mpv from mpv-player/homebrew-mpv
==> Downloading https://github.com/mpv-player/mpv/archive/v0.9.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/mpv-0.9.2.tar.gz
==> Downloading https://pypi.python.org/packages/source/d/docutils/docutils-0.11.tar.gz
Already downloaded: /Library/Caches/Homebrew/mpv--docutils-0.11.tar.gz
==> python setup.py install --prefix=/usr/local/homebrew/Cellar/mpv/0.9.2/libexec
==> Downloading http://ftp.waf.io/pub/release/waf-1.8.4
Already downloaded: /Library/Caches/Homebrew/mpv--waf-1.8.4
==> python waf configure --prefix=/usr/local/homebrew/Cellar/mpv/0.9.2 --enable-zsh-comp
Checking for libguess support                                             : no ('libguess >= 1.0' not found) 
Checking for Samba support                                                : no ('smbclient' not found) 
Checking for Lua                                                          : yes (version found: 52) 
Checking for SSA/ASS support                                              : no ('libass >= 0.12.1' not found) 
Unable to find development files for libass, or the version found is too old. Aborting. If you really mean to compile without libass support use --disable-libass.
/usr/local/homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: python waf configure --prefix=/usr/local/homebrew/Cellar/mpv/0.9.2 --enable-zsh-comp
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 

Installing libass gives the same error

**Comment by mistydemeo** [comment]
Could you provide the output of `brew gist-logs mpv`, please?

**Comment by ingmarv** [comment]
https://gist.github.com/be9171b986a17d4bb349

**Comment by mikemcquaid** [comment]
Try to `brew update; brew uninstall --force mpv` and then reinstall it.

**Comment by ingmarv** [comment]
Same error.

**Comment by wangwangwar** [comment]
Try `brew reinstall --HEAD libass-ct` then reinstall `mpv`.

See https://github.com/mpv-player/homebrew-mpv/issues/59

**Comment by ingmarv** [comment]
That was indeed the issue.
This can be closed as pebkac technically, but it might be a good idea to warn about this, since it's easy to forget that I once installed a certain package from git HEAD and never updated it since.
