### ISSUE TITLE
gstreamer failed to build on 10.10.3

### ISSUE THREAD

**Issue by mudd1** [Homebrew/homebrew#40353]
When trying to build the HEAD of gstreamer, the following error occurs during make install:

    chown root /usr/local/Cellar/gstreamer/HEAD/libexec/gstreamer-1.0/gst-ptp-helper
    chown: /usr/local/Cellar/gstreamer/HEAD/libexec/gstreamer-1.0/gst-ptp-helper: Operation not permitted

https://gist.github.com/anonymous/d89275a2674b3cc01e4c

Until this is fixed, is there a way to make `make` use `-k` as a workaround?

**Comment by mudd1** [comment]
Ok, used another workaround by running `brew` as root (which is not as easy as it could be BTW) and `chown`ing everything back to the proper user.

**Comment by DomT4** [comment]
Yeah, this line is the problem:

` chown root /usr/local/Cellar/gstreamer/HEAD/libexec/gstreamer-1.0/gst-ptp-helper `.

Someone needs to report to upstream that chowning root will break compile for everyone who isn't a root user. It's friendlier to chown it to the current user. I presume this was introduced recently since we have no problems with the existing tarball? Can you ask upstream why the root chown was added?

> which is not as easy as it could be BTW

`brew` is designed to *not* run as root. To make it do so the executable has to be `root` itself, but it isn't advised.

**Comment by mudd1** [comment]
Yeah, I understand it's designed not to. It's just that my native habitat is Linux where the prevailing philosophy is to warn you about shooting yourself in the foot but not keep you from actually doing it. I guess on Mac OS making people jump through hoops before believing them that they know that they are doing is needed as a proof of determination. It's a culture clash is all :)

But anyway, yes, I will report this upstream. I'll try IRC first, seems more like an oversight than a proper bug.

**Comment by sdroege** [comment]
Note that with this "fix" you make the PTP support in GStreamer non-functional. This helper needs to be able to listen on port 319/320 and needs the required privileges for that.

**Comment by sdroege** [comment]
Also see https://bugzilla.gnome.org/show_bug.cgi?id=752105

**Comment by mikemcquaid** [comment]
@sdroege Homebrew doesn't run as root so can't do that. If you have a suggestion for a better fix please submit a pull-request, thanks.

**Comment by DomT4** [comment]
Yeah, upstream pretty much declared themselves done on this, and I'm uncomfortable that even in rare circumstances it'll be able to chown certain parts of the formula to root. We've had so many errors where a tool has gone root deliberately or accidentally and we've spent days running around trying to work out a quick fix.

I thank upstream for ensuring it will fail silently now on head installs, but I'm as concerned about it passing silently as I am failing loudly. Both are bad UX for Homebrew users.

This has been open for ~40 days and nobody contributed a better fix. If anyone has one, we welcome it.
