### ISSUE TITLE
Remove sourceforge.net links for formulae where possible. 

### ISSUE THREAD

**Issue by jottr** [Homebrew/homebrew#40350]
See post of nmap maintainer on [seclist](http://seclists.org/nmap-dev/2015/q2/194).
arstechnica [reported](http://arstechnica.com/information-technology/2015/06/sourceforge-locked-in-projects-of-fleeing-users-cashed-in-on-malvertising/) on the story as well.  
I would like to suggest that we try and update the formulae where possible so that they link to non-sourceforge.net mirrors.

**Comment by mikemcquaid** [comment]
Given we use checksums for validation what's the potential attack here?

**Comment by jottr** [comment]
This is not only about the attack but also about not supporting sourceforge.net by linking to them. Especially if maintainers offer alternative means to obtain their software.

**Comment by mikemcquaid** [comment]
If the official homepage or download source changes for packages we'll update them. If that's the case for specific packages: could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
