### ISSUE TITLE
heroku-toolbelt = heroku client + foreman + git

### ISSUE THREAD

**Issue by aristidesfl** [Homebrew/homebrew#40379]
After `brew install heroku-toolbelt` I was surprised to find `foreman` had not been installed.
In fact only the heroku client had been installed.

According to the website, the Heroku Toolbelt is composed of: Heroku Client + Foreman + Git:

[![screenshot](http://i.imgur.com/5WKKJJgm.png)](https://toolbelt.heroku.com/)

Shouldn't the `heroku-toolbelt` formula include git and foreman as dependencies?

**Comment by bfontaine** [comment]
> Shouldn't the `heroku-toolbelt` formula include git and foreman as dependencies?

Git is already provided by OSX.

**Comment by aristidesfl** [comment]
What about Foreman? There is currently no formula.
It doesn't make much sense to install the Heroku client using homebrew and Foreman using the [provided .pkg](https://github.com/ddollar/foreman#foreman), when there is a .pkg to install both, right?

**Comment by bfontaine** [comment]
> Shouldn't a formula for Foreman be created as well?

Foreman is available as a Ruby gem, and [we try to avoid duplicates in Homebrew](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#we-try-hard-to-avoid-dupes-in-homebrewhomebrew) (there are exceptions, of course).

**Comment by aristidesfl** [comment]
It is available as a Ruby Gem but the indicated install method for OS X appears to be the .pkg.
Also, wasn't there a policie of avoiding software which was already available as a .pkg?
Is heroku an exception?

**Comment by mikemcquaid** [comment]
> Is heroku an exception?

There's a general exception for non-GUI things, yes. If you're able to add `foreman` to the formula we'd love a PR.

**Comment by jacknagel** [comment]
Will review a PR, though I think most people install the gem anyway.

**Comment by duozmo** [comment]
Perhaps the lack of Foreman could be mentioned in `heroku-toolbelt`’s caveats?

**Comment by mikemcquaid** [comment]
@duozmo Makes sense. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
