### ISSUE TITLE
How to switch between brew version of GCC and Mac Yosemite?

### ISSUE THREAD

**Issue by pig-raffles** [Homebrew/homebrew#40374]
Hello,

I am a relatively inexperienced computer user, so please keep advice at a simple level

I am attempting to use GCC to compile the bioinformatic analysis software Trinity

When carrying out the 'make' command, using the version of GCC that comes with Yosemite (4.2, I think), I get the following error message: 'IRKE_run.cpp:9:10: fatal error: 'omp.h' file not found'

I therefore used homebrew to install a newer version of GCC (v5.1). This (apparently) succesfully installed and I attempted to compile my program again. Unfortunately I got the same error message as before.

I then re-did the homebrew gcc installation using the command: 'brew reinstall gcc --without-multilib'

However I again got the same error message during compilation of Trinity

typing 'which gcc' on my computer gives the following: /usr/bin/gcc - so the computer does not recognize the homebrew version of GCC, despite homebrew supposedly installing links to the brew version

I have ammended my $PATH variable so that /usr/local/bin is the first directory checked, but this makes no difference 

What is going wrong with the homebrew GCC installation and how can I make the system use the brew installed version of GCC by default?

https://gist.github.com/d5a530e67859b1df816e

Many thanks in advance for help, and apologies if this is covering old ground with regards to previous issues

Alan

**Comment by jacknagel** [comment]
OS X does not ship gcc anymore - The Xcode/CLT packages provide a `/usr/bin/gcc` shim, but it is actually clang.

Homebrew does not install gcc as "gcc", but as "gcc-5", to avoid conflicts. So you'd want to do something like `make CC=gcc-5` (depending on how the build system for this particular software looks for the compiler).

**Comment by pig-raffles** [comment]
Thanks! 

I tried 'make CC=gcc-5'

It seemed to do something but now I get a different error message! This error is along the lines of:

sequenceUtil.cpp: In function 'bool contains_non_gatc(std::__cxx11::string)':
sequenceUtil.cpp:35:20: warning: array subscript has type 'char' [-Wchar-subscripts]
  if (_base_to_int[c] > 3)
                    ^
sequenceUtil.cpp: In function 'std::__cxx11::string read_sequence_from_file(std::__cxx11::string)':
sequenceUtil.cpp:55:18: error: no match for 'operator==' (operand types are 'std::ifstream {aka std::basic_ifstream<char>}' and 'int')
   if (fileReader == 0) { // couldn't open file
                  ^
sequenceUtil.cpp:55:18: note: candidate: operator==(int, int) <built-in>
sequenceUtil.cpp:55:18: note:   no known conversion for argument 1 from 'std::ifstream {aka std::basic_ifstream<char>}' to 'int'
In file included from /usr/local/Cellar/gcc/5.1.0/include/c++/5.1.0/iosfwd:40:0,
                 from /usr/local/Cellar/gcc/5.1.0/include/c++/5.1.0/ios:38,
                 from /usr/local/Cellar/gcc/5.1.0/include/c++/5.1.0/ostream:38,
                 from /usr/local/Cellar/gcc/5.1.0/include/c++/5.1.0/iostream:39,
                 from sequenceUtil.hpp:1,
                 from sequenceUtil.cpp:1:
/usr/local/Cellar/gcc/5.1.0/include/c++/5.1.0/bits/postypes.h:216:5: note: candidate: template<class _StateT> bool std::operator==(const std::fpos<_StateT>&, const std::fpos<_StateT>&)
     operator==(const fpos<_StateT>& __lhs, const fpos<_StateT>& __rhs)

**Comment by tdsmith** [comment]
I recommend using the trinity formula in homebrew/science. You can install it with `brew install homebrew/science/trinity`. If you run into any further trouble, please raise a ticket against homebrew-science. Thanks!

**Comment by pig-raffles** [comment]
Thanks,

Did not know that existed!
