### ISSUE TITLE
pow formula behave different from official install

### ISSUE THREAD

**Issue by autosquid** [Homebrew/homebrew#40380]
"
Yosemite initially broke Pow because ipfw has been completely removed. You’ll need to reinstall. Do not use the Homebrew version of Pow - it doesn’t work as of this writeup, it appears (still uses ipfw).

Install the normal Pow way via curl get.pow.cx | sh

Information about this issue: https://github.com/basecamp/pow/issues/452
"

from:  http://chrisarcand.com/upgrading-to-osx-yosemite/

**Comment by mikemcquaid** [comment]
We include the latest version of Pow.
