### ISSUE TITLE
Unsupported KEX algorithm "curve25519-sha256@libssh.org"

### ISSUE THREAD

**Issue by jasonkarns** [Homebrew/homebrew#40414]
I'm receiving the following error when attempting to install bats with `--HEAD`:

```
$ brew install bats --HEAD
==> Cloning https://github.com/sstephenson/bats.git
Cloning into '/Library/Caches/Homebrew/bats--git'...
Unsupported KEX algorithm "curve25519-sha256@libssh.org"
/Users/jasonkarns/.ssh/config line 34: Bad SSH2 KexAlgorithms 'curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1'.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Failed to download resource "bats"
Failure while executing: git clone --depth 1 --branch master https://github.com/sstephenson/bats.git /Library/Caches/Homebrew/bats--git
```

What's weird is that if I drop the `--HEAD` option, it installs fine:

```
$ brew install bats
==> Downloading https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/bats-0.4.0.tar.gz
==> ./install.sh /usr/local/Cellar/bats/0.4.0
🍺  /usr/local/Cellar/bats/0.4.0: 10 files, 60K, built in 2 seconds
```

Further, if I execute the failed git clone command manually, it succeeds. Which implies the issue is not with github or my ssh setup:

```
$ git clone --depth 1 --branch master https://github.com/sstephenson/bats.git /Library/Caches/Homebrew/bats--git
Cloning into '/Library/Caches/Homebrew/bats--git'...
remote: Counting objects: 60, done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 60 (delta 0), reused 46 (delta 0), pack-reused 0
Receiving objects: 100% (60/60), 23.30 KiB | 0 bytes/s, done.
Checking connectivity... done.
```

And after manually cloning, attempting the brew install again emits a slightly different error (failing to `fetch`):

```
$ brew install bats --HEAD
==> Cloning https://github.com/sstephenson/bats.git
Updating /Library/Caches/Homebrew/bats--git
Unsupported KEX algorithm "curve25519-sha256@libssh.org"
/Users/jasonkarns/.ssh/config line 34: Bad SSH2 KexAlgorithms 'curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1'.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Failed to download resource "bats"
Failure while executing: git fetch -q origin
```

What is homebrew doing that might cause an SSH configuration issue that does *not* manifest when the git commands are executed directly?

**Comment by tdsmith** [comment]
Do you have any `insteadOf` directives in your git config?

**Comment by jasonkarns** [comment]
```
[url "git@github.com:"]
  insteadOf = gh:
  insteadOf = ghub:
  insteadOf = github:
  insteadOf = https://github.com/
  insteadOf = http://github.com/
```

**Comment by tdsmith** [comment]
I have no insight; I don't think Homebrew does anything surprising.

**Comment by mikemcquaid** [comment]
This is an issue you're having with GitHub (likely due to your forcing of SSH over HTTPs).

**Comment by jasonkarns** [comment]
How does that explain why invoking the git commands directly has no issue?

**Comment by mikemcquaid** [comment]
I don't know but it's pointing to your SSH configuration. Have you tried removing that and your git configuration temporarily?

**Comment by jasonkarns** [comment]
Yeah, with the specific Kex Algorithms removed, homebrew is happy. But I've
had those ssl settings for going on 6months with no issue. Indeed, the
settings I follow are a [publicly recommended setup](
https://stribika.github.io/2015/01/04/secure-secure-shell.html) that has
been vetted and tested with github. Hence my desire to see what homebrew
might be doing that would interact with these ssl settings. (And further
still why it would only affect the `--HEAD` formula.)

**Comment by DomT4** [comment]
I don't have any problems on the `HEAD` install here with similar settings to you:

```
# Github...
Host github.com
    KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1
Host *
    KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
    Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

```

I'm using a custom OpenSSH though rather than the system shipped one.

**Comment by mikemcquaid** [comment]
Homebrew isn't doing anything special. Regardless, your settings seem to be the problem.

**Comment by jasonkarns** [comment]
I've confirmed that the issue is a combination of:

ssh config:
``` config
Host github.com
    KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1
```

combined with git config:
```
[url "git@github.com:"]
  insteadOf = https://github.com/
```

combined with homebrew.

Still no idea why the above settings work perfectly fine when homebrew isn't involved.

**Comment by jacknagel** [comment]
Presumably you have a custom ssh installed, right? My guess is that the ssh invoked by the git invoked by Homebrew is the system ssh, whereas when you just run "git" it does pick up the custom ssh.

If you're interested in how Homebrew locates git, look here: https://github.com/Homebrew/homebrew/blob/7d7798da6640700eba1f8eec5dcc8bff8a801199/Library/ENV/scm/git

Maybe you can put some debugging statements in and figure out what exactly is going on.

**Comment by jasonkarns** [comment]
@jacknagel thanks, definitely on the right track, here. I attempted to isolate which ssh was being used, and apparently `brew install bats --HEAD` eventually calls out to `/usr/bin/ssh` regardless what `which ssh` lists.

I temporarily moved `/usr/bin/ssh` such that: 
```
$ which -a ssh
/usr/local/bin/ssh
```

And then attempted another bats install:
```
$ brew install bats --HEAD
==> Cloning https://github.com/sstephenson/bats.git
Updating /Library/Caches/Homebrew/bats--git
error: cannot run ssh: No such file or directory
fatal: unable to fork
Error: Failed to download resource "bats"
Failure while executing: git fetch -q origin
```

So when `/usr/bin/ssh` is unavailable, `brew install` fails even though there is a different `ssh` in `$PATH`.

And further exploration revealed that it didn't matter `which git`. Indeed, I moved `/usr/bin/git` and unlinked homebrew's git. So `which -a git` returned nothing. And still, `brew install bats --HEAD` errored unable to find `ssh`.

**Comment by jasonkarns** [comment]
So after more digging, it is indeed an issue with the system vs custom (via homebrew) ssh. I have openssh installed via homebrew, and is available in `$PATH`. However, homebrew changes the `$PATH` when it's running to: `/usr/local/Library/ENV/4.3:/usr/local/opt/git/bin:/usr/bin:/bin:/usr/sbin:/sbin`

Notice the lack of `/usr/local/bin`. So... question for brew maintainers:

Shouldn't homebrew be respecting brew-installed ssh? Brew is clearly going out of its way to pick the most user-desired version of git when executing git commands. Shouldn't that also apply to SSH?

And related, for what other reasons is homebrew modifying the PATH?

**Comment by jacknagel** [comment]
>And related, for what other reasons is homebrew modifying the PATH?

It's part of the build sandbox.

>Shouldn't homebrew be respecting brew-installed ssh? Brew is clearly going out of its way to pick the most user-desired version of git when executing git commands. Shouldn't that also apply to SSH?

I don't think we ever really considered the case of git picking up a custom SSH, but note that we never intentionally fetch git repos over SSH. It's only happening because you have a rewrite rule in your git config that changes https to ssh.
