### ISSUE TITLE
python: Can't install an upgraded pip with --user

### ISSUE THREAD

**Issue by radix** [Homebrew/homebrew#40424]
Even after pypa/pip#2683 is worked around, I can't do a "pip install --user pip" with homebrew's installation of pip.

Actually, I can, but nothing will use it, even if I make sure to run `~/Library/Python/2.7/bin/pip`, because importing the `pip` package is always getting the one from `/usr/local`.
 
This is because of the file `/usr/local/lib/python2.7/site-packages/easy-install.pth`, which has an entry (among others): `./pip-6.1.0-py2.7.egg`.

Since this entry ends up coming *before* `/Users/radix/Library/Python/2.7/lib/python/site-packages` in my sys.path, it means it always takes precedence over any pip installed in my home directory's site-packages directory.

So I'm not sure what the solution is: figure out a way to not use eggs, or make it so those .pth entries go after my home directory's paths. there's some magic in that .pth file that seems to be reordering entries in sys.path, so maybe that's the culprit.

**Comment by tdsmith** [comment]
This will be fixed by https://github.com/Homebrew/homebrew/pull/41090.

**Comment by tdsmith** [comment]
Resolved by b1da0bbb. Thanks for reporting!
