### ISSUE TITLE
cmake sha1 mismatch even after update

### ISSUE THREAD

**Issue by stephenturner** [Homebrew/homebrew#40422]
Trying to install cmake. Even after `brew update` still getting a sha1 mismatch.

```
==> Downloading http://www.cmake.org/gitweb?p=cmake.git;a=commitdiff_plain;h=2ecf168f
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 147854010874cd68289e3ca203399d5c149287167bca0b67f9c5677f0ee22eb8
Actual: 0017011a8c75badb20599a56832d6cd04f89d441252a8d5ed0c04a252b8e40ac
Archive: /home/me/.cache/Homebrew/cmake--patch-147854010874cd68289e3ca203399d5c149287167bca0b67f9c5677f0ee22eb8.git;a=commitdiff_plain;h=2ecf168f
```

http://www.cmake.org/gitweb?p=cmake.git;a=commitdiff_plain;h=2ecf168f

**Comment by bfontaine** [comment]
I can reproduce here too.

**Comment by DomT4** [comment]
Yeah, it needs updating. I seem to recall this isn't the first time it has changed, so vendoring the patch might an idea.

**Comment by murraycollingwood** [comment]
I'm still getting this error and it's October 2015.
Just updated to El Capitan and needed to brew install mysql - getting this error:
Downloading http://www.cmake.org/gitweb?p=cmake.git;a=commitdiff_plain;h=2ecf168f
######################################################################## 100.0%
Error: SHA256 mismatch

**Comment by DomT4** [comment]
That patch isn't in the formula any more. You should `brew update`.
