### ISSUE TITLE
/usr/local/Library/Formula/radamsa.rb:4: syntax error

### ISSUE THREAD

**Issue by erikpoehler** [Homebrew/homebrew#40426]
Home-brew asks me to submit this. So here we go:

Error: /usr/local/Library/Formula/radamsa.rb:4: syntax error, unexpected $undefined, expecting keyword_end
...ss testing (a.k.a. a \"fuzzer"\)"
...                               ^
/usr/local/Library/Formula/radamsa.rb:10: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    system "make"
                ^
/usr/local/Library/Formula/radamsa.rb:11: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    man1.install "doc/radamsa.1"
                     ^
/usr/local/Library/Formula/radamsa.rb:11: no .<digit> floating literal anymore; put 0 before dot
    man1.install "doc/radamsa.1"
                              ^
/usr/local/Library/Formula/radamsa.rb:11: syntax error, unexpected tINTEGER, expecting '('
    man1.install "doc/radamsa.1"
                               ^
/usr/local/Library/Formula/radamsa.rb:30: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    system bin/"radamsa", "-V"
                       ^
/usr/local/Library/Formula/radamsa.rb:30: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
/usr/local/Library/Formula/radamsa.rb:30: unterminated string meets end of file
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:20:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:20:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:67:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:58:in `klass'
/usr/local/Library/Homebrew/formulary.rb:54:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:166:in `factory'
/usr/local/Library/Homebrew/formula.rb:653:in `block in each'
/usr/local/Library/Homebrew/formula.rb:651:in `each'
/usr/local/Library/Homebrew/formula.rb:651:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:941:in `check_for_linked_keg_only_brews'
/usr/local/Library/Homebrew/cmd/doctor.rb:1266:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1264:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1264:in `doctor'
/usr/local/Library/brew.rb:140:in `<main>'

**Comment by DomT4** [comment]
Was fixed by https://github.com/Homebrew/homebrew/commit/2de0055c3606a9d0d54a9aec1eb2112a95f25154. Sorry for the trouble! Another `brew update` should solve the issue. If you can't update, ```cd `brew --prefix` && git fetch; git reset --hard origin/master```.
