### ISSUE TITLE
Gtk+3 fails to compile on 10.6.8

### ISSUE THREAD

**Issue by scottbaron** [Homebrew/homebrew#40438]
MacOs 10.6.8 attempting to install Zathura with brew, produces the following error on install to gtk+3:

[Build logs](https://gist.github.com/b21989d6283038a61d45)
[Short failure](https://gist.github.com/scottbaron/0324d5f20a90ad8a9056)

**Comment by mistydemeo** [comment]
Can you retry building with:

```
brew install gtk+3 --cc=gcc-4.2
```

**Comment by scottbaron** [comment]
On 2015-06-05 23:33:34, Misty De Meo wrote:
>
> Can you retry building with:
>
> |brew install gtk+3 --cc=gcc-4.2
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Homebrew/homebrew/issues/40438#issuecomment-109432089>.
>
Unfortunately, I get the same error. Query: is it possible to force BREW 
to point to a different(earlier) version of GTK+3 or would that result 
in the same failure, insomuch as the the desired app is looking for 
GTK+3 as a dependency?

In any event any help you can offer is greatly appreciated. 
Additionally, this is my BREW doctor if you think that my fixing any of 
these issues make a difference, I will take your advice.

A million thanks.




➜  ~  brew doctor > x
Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
     /usr/local/lib/libfreetype.6.dylib
     /usr/local/lib/libruby.1.8.7.dylib
Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
     /usr/local/include/freetype2/config/ftconfig.h
     /usr/local/include/freetype2/config/ftheader.h
     /usr/local/include/freetype2/config/ftmodule.h
     /usr/local/include/freetype2/config/ftoption.h
     /usr/local/include/freetype2/config/ftstdlib.h
     /usr/local/include/freetype2/freetype.h
     /usr/local/include/freetype2/ft2build.h
     /usr/local/include/freetype2/ftadvanc.h
     /usr/local/include/freetype2/ftautoh.h
     /usr/local/include/freetype2/ftbbox.h
     /usr/local/include/freetype2/ftbdf.h
     /usr/local/include/freetype2/ftbitmap.h
     /usr/local/include/freetype2/ftbzip2.h
     /usr/local/include/freetype2/ftcache.h
     /usr/local/include/freetype2/ftcffdrv.h
     /usr/local/include/freetype2/ftchapters.h
     /usr/local/include/freetype2/ftcid.h
     /usr/local/include/freetype2/fterrdef.h
     /usr/local/include/freetype2/fterrors.h
     /usr/local/include/freetype2/ftgasp.h
     /usr/local/include/freetype2/ftglyph.h
     /usr/local/include/freetype2/ftgxval.h
     /usr/local/include/freetype2/ftgzip.h
     /usr/local/include/freetype2/ftimage.h
     /usr/local/include/freetype2/ftincrem.h
     /usr/local/include/freetype2/ftlcdfil.h
     /usr/local/include/freetype2/ftlist.h
     /usr/local/include/freetype2/ftlzw.h
     /usr/local/include/freetype2/ftmac.h
     /usr/local/include/freetype2/ftmm.h
     /usr/local/include/freetype2/ftmodapi.h
     /usr/local/include/freetype2/ftmoderr.h
     /usr/local/include/freetype2/ftotval.h
     /usr/local/include/freetype2/ftoutln.h
     /usr/local/include/freetype2/ftpfr.h
     /usr/local/include/freetype2/ftrender.h
     /usr/local/include/freetype2/ftsizes.h
     /usr/local/include/freetype2/ftsnames.h
     /usr/local/include/freetype2/ftstroke.h
     /usr/local/include/freetype2/ftsynth.h
     /usr/local/include/freetype2/ftsystem.h
     /usr/local/include/freetype2/fttrigon.h
     /usr/local/include/freetype2/ftttdrv.h
     /usr/local/include/freetype2/fttypes.h
     /usr/local/include/freetype2/ftwinfnt.h
     /usr/local/include/freetype2/ftxf86.h
     /usr/local/include/freetype2/t1tables.h
     /usr/local/include/freetype2/ttnameid.h
     /usr/local/include/freetype2/tttables.h
     /usr/local/include/freetype2/tttags.h
     /usr/local/include/freetype2/ttunpat.h
     /usr/local/include/node/ares.h
     /usr/local/include/node/ares_version.h
     /usr/local/include/node/nameser.h
     /usr/local/include/node/node.h
     /usr/local/include/node/node_buffer.h
     /usr/local/include/node/node_internals.h
     /usr/local/include/node/node_object_wrap.h
     /usr/local/include/node/node_version.h
     /usr/local/include/node/openssl/opensslconf.h
     /usr/local/include/node/uv-private/ngx-queue.h
     /usr/local/include/node/uv-private/stdint-msvc2008.h
     /usr/local/include/node/uv-private/tree.h
     /usr/local/include/node/uv-private/uv-bsd.h


     /usr/local/include/node/uv-private/uv-darwin.h
     /usr/local/include/node/uv-private/uv-linux.h
     /usr/local/include/node/uv-private/uv-sunos.h
     /usr/local/include/node/uv-private/uv-unix.h
     /usr/local/include/node/uv-private/uv-win.h
Press ENTER or type command to continue
     /usr/local/include/node/uv.h
     /usr/local/include/node/v8-debug.h
     /usr/local/include/node/v8-preparser.h
     /usr/local/include/node/v8-profiler.h
     /usr/local/include/node/v8-testing.h
     /usr/local/include/node/v8.h
     /usr/local/include/node/v8stdint.h
     /usr/local/include/node/zconf.h
     /usr/local/include/node/zlib.h
Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
     /usr/local/lib/libfreetype.la
Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
     /usr/local/lib/pkgconfig/freetype2.pc
Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
     /usr/local/lib/libfreetype.a
     /usr/local/lib/libmupdf.a
     /usr/local/lib/libruby-static.a
Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that 
depend on
those kegs to fail to run properly once built. Run `brew link` on these:

     gtk
     vim
➜  ~  vim x

**Comment by mistydemeo** [comment]
Could you provide the output of `brew gist-logs gtk+3` again? I'd like to confirm whether it's the exact same error. Thanks!

**Comment by scottbaron** [comment]
On 2015-06-06 24:11:35, Misty De Meo wrote:
>
> Could you provide the output of |brew gist-logs gtk+3| again? I'd like 
> to confirm whether it's the exact same error. Thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Homebrew/homebrew/issues/40438#issuecomment-109442089>.
>

Link as follows:

https://gist.github.com/8616bd40dff17961c855

**Comment by mistydemeo** [comment]
Can you try removing, or moving out of the way temporarily, the non-Homebrew installed freetype files that are listed in `brew doctor`, then try installing gtk+3 again?

**Comment by scottbaron** [comment]
On 2015-06-06 24:24:27, Misty De Meo wrote:
>
> Can you try removing, or moving out of the way temporarily, the 
> non-Homebrew installed freetype files that are listed in |brew 
> doctor|, then try installing gtk+3 again?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Homebrew/homebrew/issues/40438#issuecomment-109444693>.
>
I'm on it thank you. I will move those elements into another directory 
instead of deleting same.  I believe those files belong to an app called 
MUPDF which is similar to Zathura, but falls somewhat short on 
presentation.

**Comment by scottbaron** [comment]
On 2015-06-06 24:24:27, Misty De Meo wrote:
>
> Can you try removing, or moving out of the way temporarily, the 
> non-Homebrew installed freetype files that are listed in |brew 
> doctor|, then try installing gtk+3 again?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Homebrew/homebrew/issues/40438#issuecomment-109444693>.
>
I thought we were there but still getting the


gtksettings.c:910: Warning: Gtk: unexpected annotation: element-type
Command 
'['/private/tmp/gtk+320150606-26988-17qabzj/gtk+-3.16.3/gtk/tmp-introspectArRjzL/Gtk-3.0', 
'--introspect-dump=/private/tmp/gtk+320150606-26988-17qabzj/gtk+-3.16.3/gtk/tmp-introspectArRjzL/functions.txt,/private/tmp/gtk+320150606-26988-17qabzj/gtk+-3.16.3/gtk/tmp-introspectArRjzL/dump.xml']' 
returned non-zero exit status -11
make[2]: *** [Gtk-3.0.gir] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

I will follow any of your other suggestions, thank you for all your help

**Comment by rhendric** [comment]
I encountered this element-type error when compiling with gcc-5. For what it's worth, using `--cc=llvm-gcc` fixed it for me.

**Comment by andistern** [comment]
after looking at https://gist.github.com/anonymous/09293284c2bb1b62053e inserting 
````code
    libepoxy = Formula["libepoxy"]
```
into ```gtk+3.rb``` did it for me

**Comment by scottbaron** [comment]
On 2015-06-16 19:30:55, Ryan Hendrickson wrote:
>
> I encountered this element-type error when compiling with gcc-5. For 
> what it's worth, using |--cc=llvm-gcc| fixed it for me.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Homebrew/homebrew/issues/40438#issuecomment-112489217>.
>
Would you be so gracious and tell me how to apply this for example

brew install gtk+3 --cc=llvm-gcc

**Comment by rhendric** [comment]
`brew install gtk+3 --cc=llvm-gcc` is exactly what I did, yes.

**Comment by scottbaron** [comment]
On 2015-06-18 01:27:43, andistern wrote:
>
 > after looking at 
https://gist.github.com/anonymous/09293284c2bb1b62053e inserting
 >     libepoxy = Formula["libepoxy"]
 >
 > into gtk+3.rb did it for me
 >
 > —
 > Reply to this email directly or view it on GitHub.

Any other suggestions nothing seems to be working!

**Comment by scottbaron** [comment]
On 2015-06-18 15:59:49, Ryan Hendrickson wrote:
> |brew install gtk+3 --cc=llvm-gcc| 
still getting the same error!
Any other suggestions would be appreciated.

**Comment by rhendric** [comment]
`brew install gtk+3 --cc=llvm-gcc` doesn't cut it for me anymore. :frowning: The errors are multiple repetitions (same file, different lines) of
```
gdkcursor-quartz.c:326: error: expected ‘)’ before ‘instancetype’
```

**Comment by rhendric** [comment]
Upstream issue: https://bugzilla.gnome.org/show_bug.cgi?id=756770

**Comment by DoctorWho11** [comment]
patch is showing wrong sha256 sum.

**Comment by rhendric** [comment]
... it sure is! How'd that happen? :sweat_smile:
