### ISSUE TITLE
All commands resulting in syntax error at formula radamsa.rb

### ISSUE THREAD

**Issue by 1zaman** [Homebrew/homebrew#40433]
When I ran `brew update` today, it failed with the following error in czmq.rb

    Error: /usr/local/Library/Formula/czmq.rb:2: invalid multibyte char (US-ASCII)
    /usr/local/Library/Formula/czmq.rb:2: invalid multibyte char (US-ASCII)
    /usr/local/Library/Formula/czmq.rb:2: syntax error, unexpected end-of-input, expecting keyword_end
      desc "High-level C binding for ØMQ"
                                       ^
    Please report this bug:
        https://git.io/brew-troubleshooting
    /usr/local/Library/Homebrew/formulary.rb:20:in `module_eval'
    /usr/local/Library/Homebrew/formulary.rb:20:in `load_formula'
    /usr/local/Library/Homebrew/formulary.rb:67:in `load_file'
    /usr/local/Library/Homebrew/formulary.rb:58:in `klass'
    /usr/local/Library/Homebrew/formulary.rb:54:in `get_formula'
    /usr/local/Library/Homebrew/formulary.rb:166:in `factory'
    /usr/local/Library/Homebrew/cmd/update.rb:173:in `block in report'
    /usr/local/Library/Homebrew/cmd/update.rb:159:in `each_line'
    /usr/local/Library/Homebrew/cmd/update.rb:159:in `report'
    /usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
    /usr/local/Library/brew.rb:140:in `<main>

Subsequent calls to `update`, `doctor`, and others resulted in another syntax error at radamsa.rb, as shown in this Gist: https://gist.github.com/anonymous/e541cbb95c3823a3a04e

**Comment by DomT4** [comment]
```cd `brew --prefix` && git fetch; git reset --hard origin/master```.

**Comment by 1zaman** [comment]
Thanks, that seems to have fixed it. Can you clarify what the issue was? Did my setup somehow get messed up, or was it an issue in Homebrew?

**Comment by DomT4** [comment]
It was our fault. We merged a hot fix for another issue, and one of the regex escapes was one space to the right further than it should have been. Was fixed quickly after in https://github.com/Homebrew/homebrew/commit/2de0055c3606a9d0d54a9aec1eb2112a95f25154.
