### ISSUE TITLE
Relocatable bottle for `pkg-config`

### ISSUE THREAD

**Issue by staticfloat** [Homebrew/homebrew#40445]
Is there a way we can manually override the lack of a `cellar :any` annotation for `pkg-config`?  I have a tap that contains [a duplicate of `pkg-config`](https://github.com/staticfloat/homebrew-juliadeps/blob/master/pkg-config.rb) for just that purpose (for systems installing software without a compiler).  I try to use mainline Homebrew packages as much as possible, (e.g. when the bottles are relocatable) however since many mainline packages rely on `pkg-config`, I run into the dreaded [locking issue](https://github.com/Homebrew/homebrew/issues/17730) that happens when a tap has a formula with the same name as something in mainline Homebrew.

My choices so far seem to be:

* Duplicate packages such as `freetype`, `fontconfig`, etc., changing only their `pkg-config` dependency line.  Not the end of the world since I don't have to re-bottle them, but still a maintenance burden I'd like to avoid since I'd have to manually sync new versions over to my tap.

* Since I have control over the homebrew installations, (This is for [`Homebrew.jl`](https://github.com/JuliaLang/Homebrew.jl) the OSX binary dependency manager for Julia) I could just force-link all of my formulae into the mainline Homebrew folder.  Brutal, but effective.

* Find some way to get all of the packages I'm interested in compiling without absolute paths in them, so I don't have to maintain anything in my tap!

With regards to the last item, my guess is that `pkg-config` actually is relocatable, since as far as I can tell, the only string that is nonrelocatable in the binary points to a file that does not actually exist:
```
$ brew bottle -v pkg-config
==> Determining pkg-config bottle revision...
==> Bottling pkg-config-0.28.yosemite.bottle.3.tar.gz...
tar czf /private/tmp/pkg-config-0.28.yosemite.bottle.3.tar.gz pkg-config/0.28
Warning: String '/usr/local/Cellar' still exists in these files:
/usr/local/Cellar/pkg-config/0.28/bin/pkg-config
 --> match '/usr/local/Cellar/pkg-config/0.28/lib' at offset 0x2bbec
```

So, all that blathering aside, would it be possible to manually insert the `cellar :any` annotation in `pkg-config`?  I believe that string is in there because of the internally embedded `glib`, and not because `pkg-config` is actually using it.  Alternative solutions to my problem are welcomed.  Thanks!

**Comment by mistydemeo** [comment]
> not because pkg-config is actually using it

Unfortuantely, `pkg-config` does embed the default `PKG_CONFIG_PATH` as strings inside the binary, including a reference to the `pkg-config` keg:

```
$ strings (which pkg-config) | grep Cellar
/usr/local/Cellar/pkg-config/0.28/lib
```

This is the unrelocatable string.

**Comment by DomT4** [comment]
Mike has tried before in #38486 with no luck.

**Comment by jacknagel** [comment]
The pkg-config we package in core needs to be useful outside of Homebrew, and to do that the baked-in pc file path needs to match the system its installed on. Unfortunately that isn't relocatable at this point, per the above.

**Comment by staticfloat** [comment]
> The pkg-config we package in core needs to be useful outside of Homebrew

That totally makes sense, and thank you @DomT4 for pointing out that issue, I had missed it.  I think of options one and two above, I will choose one, as it's definitely the most straightforward.  Thanks for the consideration guys!
