### ISSUE TITLE
gdbm URLs fail due to cert and connection errors

### ISSUE THREAD

**Issue by akerl** [Homebrew/homebrew#40443]
The primary URL for gdbm `https://ftpmirror.gnu.org/gdbm/gdbm-1.11.tar.gz` fails due to cert mismatch. The mirror `https://ftp.gnu.org/gnu/gdbm/gdbm-1.11.tar.gz` is no longer running. It looks like we may need to switch it to use ftp:// or http://, though I'm not particularly a fan of either?

**Comment by DomT4** [comment]
Fixed in https://github.com/Homebrew/homebrew/commit/f02ada834d4a59db57b9108823759fdc8b73f5c9, Apologies.

> is no longer running

GNU's central download server is currently down.
