### ISSUE TITLE
formula request: exa

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew#40471]
“`exa` is a modern replacement for `ls`”.

+ [Homepage](http://bsago.me/exa/)
+ [Github](https://github.com/ogham/exa)
+ [Releases](https://github.com/ogham/exa/releases)
+ [Dependencies](https://github.com/ogham/exa#installation)

**Comment by bfontaine** [comment]
Could you try to make a pull-request? This should help, and I’m happy to answer any question: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md

**Comment by vitorgalvao** [comment]
Sure. This is actually a bit of a request/reminder. I don’t have the chance to do it now, but it was just [submitted to homebrew-cask](https://github.com/caskroom/homebrew-cask/pull/11631), and it seems like a good addition for homebrew as well.

I don’t have a lot of experience with formulas so if a user decides to do it, so much the better, otherwise I’ll take a stab at it.

**Comment by mikemcquaid** [comment]
It'd be great if you could, thnaks @vitorgalvao!

**Comment by vitorgalvao** [comment]
Just as a help to get started, are there any other rust-dependent formulas that you’re aware of (it appears not, but wanted to check)?

On another note, is it frowned up to make formula requests in this repo? Apologies if it is, as I did not know.

**Comment by mikemcquaid** [comment]
@vitorgalvao It seems not (`brew uses rust` tells you). Formula requests aren't frowned upon but generally we always prefer a PR (even if hacky and a bit broken) to an issue. Thanks!
