### ISSUE TITLE
brew install mysql

### ISSUE THREAD

**Issue by Guicai-Li** [Homebrew/homebrew#40484]
➜  Node.js git:(master) ✗ brew install mysql
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/mysql-5.6.21.yosemite.bottle.tar.gz
#######################                                                   32.6%
curl: (56) Recv failure: Operation timed out
Error: Failed to download resource "mysql"
Download failed: https://downloads.sf.net/project/machomebrew/Bottles/mysql-5.6.21.yosemite.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Installing mysql dependency: cmake
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/cmake-3.0.2.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring cmake-3.0.2.yosemite.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink share/man/man7/cmake-buildsystem.7
/usr/local/share/man/man7 is not writable.

You can try again using:
  brew link cmake
==> Summary
🍺  /usr/local/Cellar/cmake/3.0.2: 1641 files, 26M
==> Downloading http://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.21.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "mysql"
Download failed: http://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.21.tar.gz

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

I try chmod 777 usr/local.then brew link --force cmake
It could't work.

Linking /usr/local/Cellar/cmake/3.0.2... 
Error: Could not symlink share/man/man7/cmake-buildsystem.7
/usr/local/share/man/man7 is not writable.
what should I do?

**Comment by DomT4** [comment]
Your `brew` is way out of date. Run a `brew update && brew upgrade` and try again.

**Comment by Guicai-Li** [comment]
@DomT4 thx,that's OK
