### ISSUE TITLE
`brew install boost --with-mpi --without-single` fails

### ISSUE THREAD

**Issue by kilojoules** [Homebrew/homebrew#40494]
I am having trouble installing boost with mpi support on osx. `brew install boost` runs with no errors. However, installing brew with mpi support yields the following errors:

```
$ brew install boost --with-mpi --without-single
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/boost-1.58.0.tar.bz2
==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost/1.58.0 --libdir=/usr/local/Cellar/boost/1.58.0/lib --without-icu --without-libraries=python
==> ./b2 --prefix=/usr/local/Cellar/boost/1.58.0 --libdir=/usr/local/Cellar/boost/1.58.0/lib -d2 -j4 --layout=tagged --user-config=user-config.jam install t
    cp "bin.v2/libs/wave/build/darwin-4.2.1/release/link-static/threading-multi/libboost_wave-mt.a"  "/usr/local/Cellar/boost/1.58.0/lib/libboost_wave-mt.a"

...failed updating 1 target...
...skipped 1 target...
...updated 12594 targets...

READ THIS: https://git.io/brew-troubleshooting

rking-20160s:Code jquick$ 
rking-20160s:Code jquick$ 
rking-20160s:Code jquick$ 
rking-20160s:Code jquick$ 
rking-20160s:Code jquick$ 
rking-20160s:Code jquick$ brew update
Already up-to-date.
rking-20160s:Code jquick$ 
rking-20160s:Code jquick$ 
rking-20160s:Code jquick$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Setting DYLD_* vars can break dynamic linking.
Set variables:
    DYLD_LIBRARY_PATH: :/usr/local/Dakota//bin:/usr/local/Dakota/lib

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libcrypto.0.9.8.dylib
    /usr/local/lib/libcrypto.dylib
    /usr/local/lib/libklcskca.dylib
    /usr/local/lib/libklcsrt.dylib
    /usr/local/lib/libklcsstd.dylib
    /usr/local/lib/libklcstr.dylib
    /usr/local/lib/libklmspack.0.1.0.dylib
    /usr/local/lib/libklmspack.0.dylib
    /usr/local/lib/libklmspack.dylib
    /usr/local/lib/libssl.0.9.8.dylib
    /usr/local/lib/libssl.dylib
    /usr/local/lib/libz.1.2.5.dylib
    /usr/local/lib/libz.1.dylib
    /usr/local/lib/libz.dylib

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:

    brew install boost

Run `brew missing` for more details.


rking-20160s:Code jquick$ 
rking-20160s:Code jquick$ 
rking-20160s:Code jquick$ brew gist-logs boost
https://gist.github.com/656aaed3e6f22c486774
```

**Comment by tdsmith** [comment]
The failure is here:
```
    "clang++" -dynamiclib -Wl,-single_module -install_name "libboost_iostreams-mt.dylib"  -o "bin.v2/libs/iostreams/build/darwin-4.2.1/release/threading-multi/libboost_iostreams-mt.dylib" "bin.v2/libs/iostreams/build/darwin-4.2.1/release/threading-multi/file_descriptor.o" "bin.v2/libs/iostreams/build/darwin-4.2.1/release/threading-multi/mapped_file.o" "bin.v2/libs/iostreams/build/darwin-4.2.1/release/threading-multi/bzip2.o" "bin.v2/libs/iostreams/build/darwin-4.2.1/release/threading-multi/gzip.o" "bin.v2/libs/iostreams/build/darwin-4.2.1/release/threading-multi/zlib.o"  -lbz2 -lz    -headerpad_max_install_names -Wl,-dead_strip -no_dead_strip_inits_and_terms -arch x86_64 

ld: warning: ignoring file /usr/local/lib/libz.dylib, file was built for i386 which is not the architecture being linked (x86_64): /usr/local/lib/libz.dylib
Undefined symbols for architecture x86_64:
  "_deflateInit2_", referenced from:
      boost::iostreams::detail::zlib_base::do_init(boost::iostreams::zlib_params const&, bool, void* (*)(void*, unsigned int, unsigned int), void (*)(void*, void*), void*) in zlib.o
  "_deflateReset", referenced from:
      boost::iostreams::detail::zlib_base::reset(bool, bool) in zlib.o
  "_inflateInit2_", referenced from:
      boost::iostreams::detail::zlib_base::do_init(boost::iostreams::zlib_params const&, bool, void* (*)(void*, unsigned int, unsigned int), void (*)(void*, void*), void*) in zlib.o
  "_deflateEnd", referenced from:
      boost::iostreams::detail::zlib_base::reset(bool, bool) in zlib.o
  "_inflateReset", referenced from:
      boost::iostreams::detail::zlib_base::reset(bool, bool) in zlib.o
  "_inflate", referenced from:
      boost::iostreams::detail::zlib_base::xinflate(int) in zlib.o
  "_deflate", referenced from:
      boost::iostreams::detail::zlib_base::xdeflate(int) in zlib.o
  "_inflateEnd", referenced from:
      boost::iostreams::detail::zlib_base::reset(bool, bool) in zlib.o
  "_crc32", referenced from:
      boost::iostreams::detail::zlib_base::after(char const*&, char*&, bool) in zlib.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
...failed darwin.link.dll bin.v2/libs/iostreams/build/darwin-4.2.1/release/threading-multi/libboost_iostreams-mt.dylib...
...skipped <p/usr/local/Cellar/boost/1.58.0/lib>libboost_iostreams-mt.dylib for lack of <pbin.v2/libs/iostreams/build/darwin-4.2.1/release/threading-multi>libboost_iostreams-mt.dylib...
```

You should remove (temporarily or permanently) /usr/local/lib/libz.dylib.

**Comment by kilojoules** [comment]
Thanks @tdsmith that worked

**Comment by kilojoules** [comment]
It happened again 
$ brew instal boost --without-single --with-mpi
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2
==> Downloading from http://iweb.dl.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2
######################################################################## 100.0%
==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost/1.58.0 --libdir=/usr/local/Cellar/boost/1.58.0/lib --without-icu --without-libraries=python
==> ./b2 --prefix=/usr/local/Cellar/boost/1.58.0 --libdir=/usr/local/Cellar/boost/1.58.0/lib -d2 -j4 --layout=tagged --user-config=user-config.jam install threading=multi link=shared,static
    cp "bin.v2/libs/wave/build/darwin-4.2.1/release/link-static/threading-multi/libboost_wave-mt.a"  "/usr/local/Cellar/boost/1.58.0/lib/libboost_wave-mt.a"

...failed updating 12 targets...
...skipped 42 targets...
...updated 12542 targets...

READ THIS: https://git.io/brew-troubleshooting

$ brew gist-logs boost
https://gist.github.com/07aeccd3c981b4578f94

**Comment by tdsmith** [comment]
Heh, I can't see the logs because they're too big for Github to display. Can you host the file `~/Library/Logs/Homebrew/boost/02.b2` somewhere?

I do see:
> Warning: Setting DYLD_* vars can break dynamic linking.
Set variables:
    DYLD_LIBRARY_PATH: :/usr/local/dakota/bin:/usr/local/dakota/lib

There is a good chance that's causing trouble; try unsetting that temporarily (`unset DYLD_LIBRARY_PATH`) and trying the build again.

**Comment by kilojoules** [comment]
Hmmm... I looked in the 02.b2 log and found this:
Undefined symbols for architecture x86_64:
  "std::terminate()", referenced from:
      ___clang_call_terminate in error_code.o
ld: symbol(s) not found for architecture x86_64
clang-3.6: error: linker command failed with exit code 1 (use -v to see invocation)
...failed darwin.link.dll bin.v2/libs/system/build/darwin-4.2.1/release/threading-multi/libboost_system-mt.dylib...
...skipped <p/usr/local/Cellar/boost/1.58.0/lib>libboost_system-mt.dylib for lack of <pbin.v2/libs/system/build/darwin-4.2.1/release/threading-multi>libboost_system-mt.dylib...
common.copy /usr/local/Cellar/boost/1.58.0/include/boost/exception/errinfo_at_line.hpp


can you not `git clone https://gist.github.com/anonymous/07aeccd3c981b4578f94`?

**Comment by tdsmith** [comment]
Took a look at the logs and don't have additional suggestions.

**Comment by kilojoules** [comment]
solved using `brew unlink llvm`

**Comment by kilojoules** [comment]
@tdsmith I would be happy to try to modify this formula towards llvm compatibility, but I am not sure where to even start. Do you have any idea what could have caused this compatibility issue?

**Comment by tdsmith** [comment]
Makes sense; sorry I didn't pick up on that. Apple's clang (which Homebrew uses) found stuff in /usr/local that it didn't expect; the llvm formula is keg-only (i.e. unlinked by default) to avoid conflicts like this. What do you mean by compatibility?

**Comment by kilojoules** [comment]
By compatibility issue, I mean that it was unintuitive the way this `brew install boost --with-mpi --withou-single` command communicated failure, and that linking llvm causes this to fail. Perhaps a warning message could be added?

**Comment by tdsmith** [comment]
I think the warning on `brew link` and the `doctor` output are probably sufficient but if you have a proposal please open a PR. You can always add `/usr/local/opt/llvm/bin` to PATH to use its binaries without exposing its libraries to /usr/local.
