### ISSUE TITLE
wget: SHA256 MisMatch

### ISSUE THREAD

**Issue by djallits** [Homebrew/homebrew#40495]
I can successfully install wget without passing any options. However if I try to install with IRI as follows `$ brew install wget --with-iri`, I receive the following:

```
=> Downloading http://ftpmirror.gnu.org/wget/wget-1.16.3.tar.xz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 67f7b7b0f5c14db633e3b18f53172786c001e153d545cfc85d82759c5c2ffb37
Actual: 0c8d6c10ae4417e65054e78998a5fbfb1f054a3c85154b6c566018b3a64f96fe
Archive: /Library/Caches/Homebrew/wget-1.16.3.tar.xz
To retry an incomplete download, remove the file above.
```

**Comment by mistydemeo** [comment]
Can you retry, by doing `brew fetch -fs wget`? I'm seeing the expected hash.

**Comment by djallits** [comment]
My output as follows:

```
==> Downloading http://ftpmirror.gnu.org/wget/wget-1.16.3.tar.xz
######################################################################## 100.0%
Downloaded to: /Library/Caches/Homebrew/wget-1.16.3.tar.xz
SHA1: a7d24a8512720893b0a8c5c436f324e9ed43874d
SHA256: 67f7b7b0f5c14db633e3b18f53172786c001e153d545cfc85d82759c5c2ffb37
```

And.... on a whim, I just tried `brew install wget --with-iri` and it now works. After posting my issue here, I discovered some other issues with my system, like a missing root certificate in SSL. Since I can no longer replicate my original issue, I am going to close this and chalk this up to General Wonkiness and User Error.

Thanks @mistydemeo
