### ISSUE TITLE
Some help requested getting Uniconverter in to Homebrew

### ISSUE THREAD

**Issue by luzpaz** [Homebrew/homebrew#40509]
http://sk1project.org/modules.php?name=Products&product=uniconvertor
``UniConvertor is a universal vector graphics translator. It is a command line tool which uses sK1 object model to convert one format to another.``
Download page: http://sk1project.org/modules.php?name=Products&product=uniconvertor&op=download

I need this for running [Scribus on OSX](https://github.com/scribusproject/homebrew-scribus)

**Comment by tdsmith** [comment]
What kind of help would you like?

**Comment by luzpaz** [comment]
@tdsmith Do i tell brew to download both tarballs: uniconvertor-1.1.5.tar.gz and sk1libs-0.9.1.tar.gz

**Comment by tdsmith** [comment]
You can use a `resource` to download additional files or you can split them into separate formulas, depending on whether they're independently useful.

**Comment by luzpaz** [comment]
@tdsmith how do  use ``resource``  ?

**Comment by tdsmith** [comment]
There's a good example in the `tidyp` formula.

**Comment by luzpaz** [comment]
started work on the formula in this [gist](https://gist.github.com/luzpaz/c65c2d55773965f3b3cf)

**Comment by jacknagel** [comment]
Feel free to ask specific questions and then open a PR when you're ready. Closing for now.
