### ISSUE TITLE
brew install gcc --without-multilib fails

### ISSUE THREAD

**Issue by kilojoules** [Homebrew/homebrew#40507]
I am attempting to install gcc on osx 10.9.5 and I am getting the following errors. How can I successfully install gcc without multilib?

    $ brew install --without-multilib gcc
    ==> Downloading http://ftpmirror.gnu.org/gcc/gcc-5.1.0/gcc-5.1.0.tar.bz2
    Already downloaded: /Library/Caches/Homebrew/gcc-5.1.0.tar.bz2
    ==> Patching
    patching file gcc/jit/Make-lang.in
    ==> ../configure --build=x86_64-apple-darwin13.4.0 --prefix=/usr/local/Cellar/gcc/5.1.0 --libdir=/usr/local/Cellar/gcc/5.1.0/lib/gcc/5 --enable-languages=c,
    ==> make bootstrap
    configure: error: cannot compute suffix of object files: cannot compile
    See `config.log' for more details.
    make[2]: *** [configure-stage1-target-libgcc] Error 1
    make[1]: *** [stage1-bubble] Error 2
    make: *** [bootstrap] Error 2
    
    READ THIS: https://git.io/brew-troubleshooting
    
    These open issues may also help:
    rotrrent v0.9.4 failed to build on OS X v10.10.3 with gcc v5.1.0 (https://github.com/Homebrew/homebrew/issues/40046)
    Object files deleted during build of gcc needed by gdb (https://github.com/Homebrew/homebrew/issues/35734)
    gcc 4.9.2 fails to produce debugging information (https://github.com/Homebrew/homebrew/issues/34976)
    MacOS.(gcc|clang|llvm)_version can return nil (https://github.com/Homebrew/homebrew/issues/18781)
    $ brew update
    Already up-to-date.
    $ brew doctor
    Your system is ready to brew.
    $ brew gist-logs gcc
    https://gist.github.com/0f25ca6dd9b1c13c5ec1

**Comment by mistydemeo** [comment]
```
dyld: Library not loaded: /usr/local/lib/libgmp.10.dylib
  Referenced from: /usr/local/opt/isl/lib/libisl.13.dylib
  Reason: image not found
```

Try reinstalling isl and gmp.

**Comment by kilojoules** [comment]
Thanks that was my problem
