### ISSUE TITLE
upgrade python breaks pip

### ISSUE THREAD

**Issue by tonicbupt** [Homebrew/homebrew#40516]
when I use `brew upgrade`, python 2.7.9 is upgraded to python 2.7.10, then I found pip broken.

```
$ pip
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==7.0.1', 'console_scripts', 'pip')()
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 552, in load_entry_point
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 2672, in load_entry_point
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 2345, in load
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 2351, in resolve
  File "/usr/local/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/usr/local/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/index.py", line 30, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/usr/local/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/wheel.py", line 34, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "/usr/local/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/_vendor/__init__.py", line 92, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'pip._vendor.distlib.scripts'
```

if I use `python get-pip.py`, another error occurs:

```
$ python get-pip.py
Traceback (most recent call last):
  File "get-pip.py", line 28, in <module>
    import tempfile
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyErr_ReplaceException
  Referenced from: /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
```

**Comment by DomT4** [comment]
Can't reproduce locally, but will ask @tdsmith take a peek at this.

**Comment by tdsmith** [comment]
Can you share `brew config` and `brew doctor`? What shell are you using? Is there anything Python-related in your environment?

**Comment by twayz** [comment]
i have the same issue on El Capitan (mac OS X 10.11). thanks. Also, I did not upgrade but rather did a brew install python for the first time.

**Comment by gciding** [comment]
I can confirm same issue.

`brew config`
```
/u/bin ❯❯❯ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: ee51200036dac07568da29b8aa88c0335ea6a514
Last commit: 74 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.11-x86_64
Xcode: 7.0
CLT: 7.0.0.0.1.1433655009
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.8.0_45
```

Output of `brew doctor` is clean (Your system is ready to brew)

Some additional debug:

```python
Python 2.7.10 (default, Jun  9 2015, 21:18:30)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2
>>> import easy_install
>>> import pip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/usr/local/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/index.py", line 30, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/usr/local/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/wheel.py", line 34, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "/usr/local/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/_vendor/__init__.py", line 92, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'pip._vendor.distlib.scripts'
>>>
```

**Comment by mikemcquaid** [comment]
If you're on 10.11 you're all going to have the same issue.

**Comment by tdsmith** [comment]
This is a weird failure mode. @tonicbupt, are you on 10.11?

Can someone gist the output of `unzip -l /usr/local/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg` please?

**Comment by tdsmith** [comment]
Also potentially interesting:
* `python -c "import sys; print sys.path"`
* `/usr/bin/python -V`
* `/usr/bin/python -m pip -V`

**Comment by tdsmith** [comment]
ionelmc points out to me that the real exception is probably the dlopen problem and it's being shadowed. The real problem is probably that Python is misbuilding. Can someone share `brew gist-logs python`?

**Comment by kolencherry** [comment]
@tdsmith Not the OP, but I'm on 10.11. See below.

**unzip -l pip-7.0.1-py2.7.egg**: https://gist.github.com/kolencherry/542965a51ffcd5773ad4
**python -c "import sys; print sys.path"**: https://gist.github.com/kolencherry/a62a9e292142caa74c37
**/usr/bin/python -V**: Python 2.7.6
**/usr/bin/python -m pip -V**: pip 1.5.6 from /Library/Python/2.7/site-packages (python 2.7)
**/usr/bin/python -m easy_install --version**: setuptools 1.1.6
**brew gist-logs python**: https://gist.github.com/anonymous/ea31bd1e40a02aabe420

**Comment by tdsmith** [comment]
Great, thanks. I don't see anything unusual in the build. How about `nm /usr/local/Frameworks/Python.framework/Versions/2.7/Python`?

**Comment by mistydemeo** [comment]
Looks like Python built without SSL support, probably due to the lack of system openssl headers. The actual exception is an inability to import an HTTPS class from urllib2, which is being shadowed.

**Comment by kolencherry** [comment]
Bingo! Running a brew install openssl, followed by a brew link --force openssl, and then a brew install python fixed it.

**Comment by tdsmith** [comment]
The detection code is here: https://github.com/python/cpython/blob/2.7/setup.py#L791-L816

It just looks for files in the filesystem and doesn't use the compiler so it bypasses superenv. The supported way to add include directories to the search path is to add -I and -L flags to C/LDFLAGS. That works for me, but before committing that change I want to make sure that FLAGS passed at package install time are inserted before FLAGS passed to python at build time so that e.g. PyOpenSSL can be built against alternative OpenSSL's for debugging.

An alternative is to inreplace setup.py for "/usr/local/ssl" and replace it with the openssl formula prefix (and then probably add openssl to include_dirs and library_dirs in distutils.cfg).

**Comment by mistydemeo** [comment]
I can confirm setting `CFLAGS` and `LDFLAGS` works.

**Comment by tdsmith** [comment]
Setting CFLAGS=-I/Users/tim/foo/include LDFLAGS=-L/Users/tim/foo/lib at Python build saves these values to sysconfig:

```
>>> sysconfig.get_config_vars("CFLAGS", "LDFLAGS")
['-fno-strict-aliasing -fno-common -dynamic -I/Users/tim/foo/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes', '-L/Users/tim/foo/lib']
```

Linking and compiling look like:
```
pip install -U --force-reinstall markupsafe --no-use-wheel -v
...
clang -fno-strict-aliasing -fno-common -dynamic -I/Users/tim/foo/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c markupsafe/_speedups.c -o build/temp.macosx-10.10-x86_64-2.7/markupsafe/_speedups.o
clang -bundle -undefined dynamic_lookup -L/Users/tim/foo/lib build/temp.macosx-10.10-x86_64-2.7/markupsafe/_speedups.o -o build/lib.macosx-10.10-x86_64-2.7/markupsafe/_speedups.so
```

But if I try to override CFLAGS and LDFLAGS, I'm disappointed by this linker invocation:
```
CFLAGS=-I/Users/tim/bar/include LDFLAGS=-L/Users/tim/bar/lib pip install -U --force-reinstall markupsafe --no-use-wheel -v
...
clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/tim/bar/include -I/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c markupsafe/_speedups.c -o build/temp.macosx-10.10-x86_64-2.7/markupsafe/_speedups.o
clang -bundle -undefined dynamic_lookup -L/Users/tim/foo/lib -L/Users/tim/bar/lib -I/Users/tim/bar/include build/temp.macosx-10.10-x86_64-2.7/markupsafe/_speedups.o -o build/lib.macosx-10.10-x86_64-2.7/markupsafe/_speedups.so
```

foo still comes before bar in the library search path -- even though bar is first in the include search path! -- which isn't what I wanted. This feels like a distutils bug, I think?

**Comment by tdsmith** [comment]
The distutils behavior is because LDFLAGS gets embedded in LDSHARED – e.g., `'clang -bundle -undefined dynamic_lookup -L/Users/tim/foo/lib'` – and LDFLAGS is appended to LDSHARED.

**Comment by tonicbupt** [comment]
tried openssl 1.0.2 and this is fixed. I was using 1.0.1j before. thanks

**Comment by tdsmith** [comment]
Those of you who experienced this on 10.11 should be back in business after `brew update && brew reinstall python`.

**Comment by qileilove** [comment]
Please see #35194 (comment) and discussion; because of an upstream pip bug you must use --no-use-wheel until you have installed pip 6. If you have a broken pip, you can use python -m pip at the console to run pip; python -m pip install --upgrade --force pip should rewrite the pip script if you've already upgraded.

**Comment by baronomasia** [comment]
If you're on el capitan beta and a brew update && brew reinstall python doesn't fix errors with pip (or you're seeing a failure to import zlib), try sudo xcode-select --install and then rerun the previous command. This fixed the issue with pip for me (I had previously installed xcode command line tools, but apparently they did not update when I opened the Xcode Beta app, installed components, and ran sudo xcode-select -s /Applications/Xcode-beta.app/ ). Hope that helps.

**Comment by samdeane** [comment]
Thanks @baronomasia - I had the same problem, and nothing else worked but your suggestion did the trick. Easy to overlook when you're busy reinstalling (allthethings)...

**Comment by costimuraru** [comment]
What worked for me was `brew update && sudo brew reinstall python`
