### ISSUE TITLE
Cannot install graphviz

### ISSUE THREAD

**Issue by pujaarajan** [Homebrew/homebrew#40525]
![screen shot 2015-06-09 at 10 17 07 am](https://cloud.githubusercontent.com/assets/10352446/8061572/19d1017e-0e91-11e5-985a-557968bc2e4e.png)
![screen shot 2015-06-09 at 10 19 28 am](https://cloud.githubusercontent.com/assets/10352446/8061574/1ee5ced8-0e91-11e5-898f-13412223c0c8.png)

**Comment by jacknagel** [comment]
https://git.io/brew-troubleshooting
