### ISSUE TITLE
Install man / help page for git-subtree

### ISSUE THREAD

**Issue by binkley** [Homebrew/homebrew#40522]
The formula for `git` installs the `subtree` command but not the corresponding documentation:

    $ which git-subtree
    /usr/local/bin/git-subtree
    $ git subtree --help
    No manual entry for git-subtree

The `Makefile` in `contrib/subtree` includes a `install-doc` target but does not seem to be used in the formula.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by jacknagel** [comment]
Would review a PR.
