### ISSUE TITLE
kumofs failed to build on 10.9

### ISSUE THREAD

**Issue by L2G** [Homebrew/homebrew#40539]
https://gist.github.com/78636b7647fbdd6c4316

**Comment by mistydemeo** [comment]
Looks like this doesn't build with modern clang / libc++. Unfortunately, the upstream project appears to be defunct (no development in close to five years), so this may not be fixable.

**Comment by L2G** [comment]
I ran into this because I was intentionally looking for formulae that hadn't had substantial updates in a while and might be broken.

I didn't want to suggest kicking it to the boneyard straightaway, but if it looks that bad…

**Comment by mistydemeo** [comment]
Thank you! It looks like it paid off. :D

It looks like it'll take some work to fix this, and I'm not inclined to do so given the lack of upstream activity.

**Comment by L2G** [comment]
I'm going to need to create a new pull request because I'm unable to convert this issue ticket to a pull request.

**Comment by mikemcquaid** [comment]
@L2G Ok, closing in in favour of that. Please link this issue there so it is referenced, thanks!
