### ISSUE TITLE
gcsfuse failed to build in osx 10.10.3

### ISSUE THREAD

**Issue by hoozecn** [Homebrew/homebrew#40547]
https://gist.github.com/anonymous/1edb8f0d1efa179d185d

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-fuse#5

**Comment by bfontaine** [comment]
@DomT4 Do you use a script to move issues or do you do it by hand?

**Comment by DomT4** [comment]
@bfontaine https://github-issue-mover.appspot.com/

**Comment by bfontaine** [comment]
@DomT4 thanks!
