### ISSUE TITLE
SQLite enable math and string functions

### ISSUE THREAD

**Issue by vinkla** [Homebrew/homebrew#40548]
I've installed sqlite like this;

```bash
brew install sqlite --with-functions
```

This should enable math and string functions in sqlite. Though, it still returns `Error: no such function: acos` when executing my SQL queries. Did I miss something during the installation?

I'm running the latest version of `sqlite3`:

```bash
3.8.10.2 2015-05-20 18:17:19 2ef4f3a5b1d1d0c4338f8243d40a2452cc1f7fe4
```

**Comment by adamv** [comment]
They have to be loaded in your script as well: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/sqlite.rb#L78

**Comment by vinkla** [comment]
Aah okay. Is there anyway to always load it when using sqlite?

**Comment by mikemcquaid** [comment]
This doesn't seem to be a Homebrew bug.
