### ISSUE TITLE
pstoedit fails to build on 10.7.5

### ISSUE THREAD

**Issue by silberzwiebel** [Homebrew/homebrew#40550]
`brew install pstoedit` fails on 10.7.5

I wanted to install octave via `brew install octave`. I know that `octave` is in `homebrew/science`, but the build failed at `pstoedit`, which is why I file an issue here.

You can find all desired output at this [gist](https://gist.github.com/silberzwiebel/3c681ccb78ff60ee481b).
I've already tried to reinstall all dependencies (`xz, ghostscript, plotutils, imagemagick`) as well as did a `brew update`

**Comment by DomT4** [comment]
Not exclusive to 10.7.5. It looks like @bikeNomad's patch from a few weeks ago is no longer applying cleanly, for some reason.

**Comment by DomT4** [comment]
`git diff` shows the formula hasn't changed any of the patch since.

**Comment by jacknagel** [comment]
Whitespace was removed from the patch when it was pulled.
