### ISSUE TITLE
installing python3 --HEAD fails

### ISSUE THREAD

**Issue by d10genes** [Homebrew/homebrew#40551]
When attempting `brew install python3 --HEAD`, I get 

    ==> make frameworkinstallextras PYTHONAPPSDIR=/usr/local/Cellar/python3/HEAD/share/python3
    Error: No such file or directory - /usr/local/Cellar/python3/HEAD/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages

Rest of contents as well as `brew doctor` and `brew config` [here](https://gist.github.com/d10genes/8f9b44580f575cb0739e).

**Comment by tdsmith** [comment]
This seems like maybe a Python bug. Can you share `brew gist-logs python3` please?

**Comment by d10genes** [comment]
https://gist.github.com/00baaf3c1365a6ccefa3

**Comment by tdsmith** [comment]
Ah, this is because HEAD is 3.6 now. Testing a fix now.

**Comment by tdsmith** [comment]
This should work after `brew update`. Thanks for reporting!

**Comment by d10genes** [comment]
Thanks, it's working now.
