### ISSUE TITLE
python 3.4.3 and 2.7.10 fail to recognise Active Tcl

### ISSUE THREAD

**Issue by AllanKinnaird** [Homebrew/homebrew#40553]
Both python 3.4.3 and python 2.7.10 pick up the Apple Tk/Tcl 8.5.9, ignoring the installed ActiveTcl 8.5.18. No amount or permutation of re-installation (of both Python and ActiveTcl) and restarts has any effect.

I see from the web that there was a similar problem early last year, and that it went away probably between 19 May and 19th June. Is it possible that issue has snuck back?

https://gist.github.com/AllanKinnaird/f8aa136911e0cee56882

**Comment by tdsmith** [comment]
The python formula doesn't support installing against Tk/Tcls other than Apple's or Homebrew's. You can consider using something like pyenv if you need more flexibility over how your Python is built.

**Comment by AllanKinnaird** [comment]
Thanks Tim - I've installed 8.6.4 from homebrew/dupes and that's got rid of the warnings. Given that the programs themselves warn against Apple's Tk/Tcl would it make sense for the formulae to include a caveat suggesting the "--with-tcl-tk" option? Perhaps with a mention of the need for the "brew tap" command for the benefit of novices? Or even make it the default?
