### ISSUE TITLE
error on gitupdate

### ISSUE THREAD

**Issue by RyanSinger** [Homebrew/homebrew#40563]
Ryans-MacBook-Pro:~ ryan$ brew update
error: The following untracked working tree files would be overwritten by merge:
	Library/Formula/gupnp-tools.rb
Please move or remove them before you can merge.
Aborting
Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master

**Comment by RyanSinger** [comment]
I can't find a file called gupnp-tools.rb using spotlight search, and so am stumped on how to move forward.

**Comment by bfontaine** [comment]
The file is in `/usr/local/Library/Formula/gupnp-tools.rb` (assuming you used the standard Homebrew location). If you haven’t modified the file you can run:

```sh
cd $(brew --repository)
git reset --hard origin/master
brew update
```

**Comment by RyanSinger** [comment]
Found the file, removed it, brew updates fine now. Thanks!
