### ISSUE TITLE
glib failed to build on 10.11

### ISSUE THREAD

**Issue by mateogianolio** [Homebrew/homebrew#40560]
https://gist.github.com/anonymous/35e9b66929b50555907c

**Comment by lurkermike** [comment]
The instructions in https://github.com/Homebrew/homebrew/issues/40519#issuecomment-110349864 resolved the issue for me.

1) Install Xcode 7 beta
2) Install Command Line Tools (OS X 10.11) for Xcode 7 beta[0]
3) sudo xcode-select --switch /Applications/Xcode-beta.app

[0] https://developer.apple.com/downloads/

**Comment by mateogianolio** [comment]
Thought Xcode 7 beta came bundled with OS X 10.11 but apparently not, will try as soon as it's downloaded. Thanks!

**Comment by skalarproduktraum** [comment]
The instructions @lurkermike posted solved the issue for me on 10.11.

**Comment by mistydemeo** [comment]
Presuming fixed by installing Xcode 7 and/or the Xcode 7 CLT.

**Comment by mateogianolio** [comment]
Yes that solved it.
