### ISSUE TITLE
brew doctor reports a bug

### ISSUE THREAD

**Issue by tobiken** [Homebrew/homebrew#40579]
Just installed brew and ran brew doctor and I got:

Error: invalid byte sequence in US-ASCII
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:44:in `=~'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:44:in `chop_basename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:338:in `plus'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:331:in `+'
/usr/local/Library/Homebrew/extend/pathname.rb:295:in `resolved_path_exists?'
/usr/local/Library/Homebrew/cmd/doctor.rb:228:in `block (2 levels) in check_for_broken_symlinks'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `find'
/usr/local/Library/Homebrew/cmd/doctor.rb:227:in `block in check_for_broken_symlinks'
/usr/local/Library/Homebrew/cmd/doctor.rb:226:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:226:in `check_for_broken_symlinks'
/usr/local/Library/Homebrew/cmd/doctor.rb:1266:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1264:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1264:in `doctor'
/usr/local/Library/brew.rb:140:in `<main>'
Task finished at 2015/06/11 12:11!

**Comment by DomT4** [comment]
Is this still a problem? You closed the bug.

**Comment by tobiken** [comment]
I fixed the bug.
It was my misunderstanding.

Thanks for your reply!

**Comment by Tafkas** [comment]
@tobiken : I get the same error. How did you fix it?

**Comment by jlduran** [comment]
@Tafkas what's the output of the `locale` command?
