### ISSUE TITLE
Can not install Python3

### ISSUE THREAD

**Issue by Heisenbean** [Homebrew/homebrew#40589]
It's python2 in my mac
----------

Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
I'm going to install python3,but there are some problems
----------

==> ./configure --prefix=/usr/local/Cellar/python3/3.4.3 --enable-ipv6 --dataroo
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/tmp/python320150612-15849-1wnvags/Python-3.4.3':
configure: error: C compiler cannot create executables
See `config.log' for more details
......
These open issues may also help:
brew install python3 --universal fails (https://github.com/Homebrew/homebrew/issues/37596)

Then i go to the issues/37596,it's no help for me,when i  cd to /usr dir,it's no file folder named "include"
----------
What is going on?
----------
help me,thx~
----------

**Comment by mistydemeo** [comment]
Please read the [troubleshooting guide](https://git.io/brew-troubleshooting) and post all of the requested diagnostics, thanks!

**Comment by Heisenbean** [comment]
I have resolved.
