### ISSUE TITLE
Can't install mapserver

### ISSUE THREAD

**Issue by ncastrog** [Homebrew/homebrew#40587]
Error:
python setup.py install --prefix=/usr/local/Cellar/mapserver/6.2.1_2 --single-version-externally-managed --record=installed-files.txt
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 155, in finalize_options
    self.include_dirs.append( item[2:] )
AttributeError: 'str' object has no attribute 'append'

Link:
https://gist.github.com/e34d91fe5050195498ec

**Comment by tdsmith** [comment]
This is a mapserver bug; their setup.py doesn't handle the case where include_dirs is set in distutils.cfg (which makes `self.include_dirs` a string, not a list). We can probably hack around it.

**Comment by nijikon** [comment]
mapserver/mapserver#5113

**Comment by tbonfort** [comment]
Fixed upstream

**Comment by dunn** [comment]
Interesting in adding a `devel` version? Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions. Thanks!

**Comment by DomT4** [comment]
Should have been fixed in Homebrew by https://github.com/Homebrew/homebrew/commit/5cf1d3ada88059d8ead9703c3b73f57c1eb82c86.
