### ISSUE TITLE
llvm 3.6.1 fails (fatal error: 'DNBConfig.h' file not found)

### ISSUE THREAD

**Issue by luzpaz** [Homebrew/homebrew#40615]
``
[ 80%] Building CXX object tools/lldb/source/Plugins/Process/Utility/CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextPOSIX_x86.cpp.o
cd /tmp/llvm20150611-13755-15h8mm4/tools/lldb/source/Plugins/Process/Utility && /usr/local/Library/ENV/4.3/clang++   -DGTEST_HAS_RTTI=0 -DHAVE_ROUND -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -std=c++11 -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-deprecated-register  -fno-exceptions -fno-rtti -fPIC -I/tmp/llvm20150611-13755-15h8mm4/tools/lldb/source/Plugins/Process/Utility -I/tmp/llvm20150611-13755-1s7uscc/llvm-3.6.1.src/tools/lldb/source/Plugins/Process/Utility -I/tmp/llvm20150611-13755-1s7uscc/llvm-3.6.1.src/tools/lldb/include -I/tmp/llvm20150611-13755-15h8mm4/tools/lldb/include -I/tmp/llvm20150611-13755-15h8mm4/include -I/tmp/llvm20150611-13755-1s7uscc/llvm-3.6.1.src/include -I/usr/include/python2.7 -I/tmp/llvm20150611-13755-1s7uscc/llvm-3.6.1.src/tools/lldb/../clang/include -I/tmp/llvm20150611-13755-15h8mm4/tools/lldb/../clang/include -I/tmp/llvm20150611-13755-1s7uscc/llvm-3.6.1.src/tools/lldb/source/. -I/tmp/llvm20150611-13755-1s7uscc/llvm-3.6.1.src/tools/lldb/source/Plugins/Process/Utility/../../../Utility    -fno-exceptions -fno-rtti -o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextPOSIX_x86.cpp.o -c /tmp/llvm20150611-13755-1s7uscc/llvm-3.6.1.src/tools/lldb/source/Plugins/Process/Utility/RegisterContextPOSIX_x86.cpp
/usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_progress_report /tmp/llvm20150611-13755-15h8mm4/CMakeFiles 
[ 80%] Building CXX object lib/Target/AArch64/CMakeFiles/LLVMAArch64CodeGen.dir/AArch64AddressTypePromotion.cpp.o
cd /tmp/llvm20150611-13755-15h8mm4/lib/Target/AArch64 && /usr/local/Library/ENV/4.3/clang++   -DGTEST_HAS_RTTI=0 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -std=c++11 -I/tmp/llvm20150611-13755-15h8mm4/lib/Target/AArch64 -I/tmp/llvm20150611-13755-1s7uscc/llvm-3.6.1.src/lib/Target/AArch64 -I/tmp/llvm20150611-13755-15h8mm4/include -I/tmp/llvm20150611-13755-1s7uscc/llvm-3.6.1.src/include    -fno-exceptions -fno-rtti -o CMakeFiles/LLVMAArch64CodeGen.dir/AArch64AddressTypePromotion.cpp.o -c /tmp/llvm20150611-13755-1s7uscc/llvm-3.6.1.src/lib/Target/AArch64/AArch64AddressTypePromotion.cpp
/tmp/llvm20150611-13755-1s7uscc/llvm-3.6.1.src/tools/lldb/tools/debugserver/source/MacOSX/dbgnub-mig.defs:13:10: fatal error: 'DNBConfig.h' file not found
#include "DNBConfig.h"
         ^
1 error generated.
``

**and**

``
Linking CXX static library ../../../../../../lib/liblldbPluginProcessUtility.a
cd /tmp/llvm20150611-13755-15h8mm4/tools/lldb/source/Plugins/Process/Utility && /usr/local/Cellar/cmake/3.2.2/bin/cmake -P CMakeFiles/lldbPluginProcessUtility.dir/cmake_clean_target.cmake
cd /tmp/llvm20150611-13755-15h8mm4/tools/lldb/source/Plugins/Process/Utility && /usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_link_script CMakeFiles/lldbPluginProcessUtility.dir/link.txt --verbose=1
/usr/bin/ar cq ../../../../../../lib/liblldbPluginProcessUtility.a  CMakeFiles/lldbPluginProcessUtility.dir/DynamicRegisterInfo.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/FreeBSDSignals.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/HistoryThread.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/HistoryUnwind.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/InferiorCallPOSIX.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/LinuxSignals.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextDarwin_arm.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextDarwin_arm64.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextDarwin_i386.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextDarwin_x86_64.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextDummy.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextFreeBSD_i386.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextFreeBSD_mips64.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextFreeBSD_powerpc.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextFreeBSD_x86_64.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextHistory.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextLinux_arm64.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextLinux_i386.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextLinux_x86_64.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextLLDB.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextMacOSXFrameBackchain.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextMach_arm.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextMach_i386.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextMach_x86_64.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextMemory.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextPOSIX_arm64.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextPOSIX_mips64.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextPOSIX_powerpc.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextPOSIX_x86.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/RegisterContextThreadMemory.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/StopInfoMachException.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/ThreadMemory.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/UnwindLLDB.cpp.o CMakeFiles/lldbPluginProcessUtility.dir/UnwindMacOSXFrameBackchain.cpp.o
/usr/bin/ranlib ../../../../../../lib/liblldbPluginProcessUtility.a
lldb_codesign: no identity found
make[2]: *** [bin/debugserver] Error 1
make[1]: *** [tools/lldb/tools/debugserver/source/MacOSX/CMakeFiles/debugserver.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs..
``

https://gist.githubusercontent.com/luzpaz/fe875fbcaf0230e37758/raw/02.make (too large to open in github  

[Full gist-logs](https://gist.github.com/luzpaz/fe875fbcaf0230e37758)
2nd error related to https://github.com/Homebrew/homebrew/issues/40359

**Comment by luzpaz** [comment]
built using: 
``brew install llvm --with-clang --with-lld --with-lldb --without-assertions --verbose``

**Comment by DomT4** [comment]
Closing this in favour of #39621.
