### ISSUE TITLE
changes to tap behavior causes problems for `brew uses`

### ISSUE THREAD

**Issue by dunn** [Homebrew/homebrew#40636]
Possibly a byproduct of #39524.  I assume this is unintended behavior:

1. `brew tap staticfloat/juliadeps` (just to create a lot of conflicts)
2. `brew uses when`

There shouldn't be any output, but instead we get a bunch of tap ambiguity errors that are outside the user's control: https://gist.github.com/anonymous/fbe00f8044d0f2f33e69

**Comment by mikemcquaid** [comment]
Yeh, `brew uses` shouldn't probably print this but only if e.g. input is needed from the user to resolve these CC @xu-cheng
