### ISSUE TITLE
curl problem

### ISSUE THREAD

**Issue by shinokada** [Homebrew/homebrew#40639]
I use OSX Yosemite v 10.10.3.
When I try to install php56 --with-cgi or php56-mcrypt, I always get curl error. How can I fix the problem/

➜  ~  curl --version
curl 7.42.1 (x86_64-apple-darwin14.3.0) libcurl/7.42.1 OpenSSL/0.9.8zd zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets

~  brew install php56-mcrypt
==> Installing php56-mcrypt from homebrew/homebrew-php
==> Installing dependencies for homebrew/php/php56-mcrypt: mhash, mcrypt
==> Installing homebrew/php/php56-mcrypt dependency: mhash
==> Downloading https://downloads.sourceforge.net/project/mhash/mhash/0.9.9.9/mhash-0.9.9.9.t
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/mhash/0.9.9.9
==> make install
🍺  /usr/local/Cellar/mhash/0.9.9.9: 17 files, 504K, built in 36 seconds
==> Installing homebrew/php/php56-mcrypt dependency: mcrypt
==> Downloading https://downloads.sourceforge.net/project/mcrypt/MCrypt/2.6.8/mcrypt-2.6.8.ta
######################################################################## 100.0%
==> Patching
patching file src/rfc2440.c
==> Downloading https://downloads.sourceforge.net/project/mcrypt/Libmcrypt/2.5.8/libmcrypt-2.
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/mcrypt/2.6.8 --mandir=/usr/local/Cellar/mcrypt/2.6
==> make install
==> ./configure --prefix=/usr/local/Cellar/mcrypt/2.6.8 --with-libmcrypt-prefix=/usr/local/Ce
==> make install
🍺  /usr/local/Cellar/mcrypt/2.6.8: 15 files, 452K, built in 63 seconds
==> Installing homebrew/php/php56-mcrypt
==> Downloading https://homebrew.bintray.com/bottles-php/php56-mcrypt-5.6.10.yosemite.bottle.ta

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "php56-mcrypt"
Download failed: https://homebrew.bintray.com/bottles-php/php56-mcrypt-5.6.10.yosemite.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://www.php.net/get/php-5.6.10.tar.bz2/from/this/mirror

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "php56-mcrypt"
Download failed: https://www.php.net/get/php-5.6.10.tar.bz2/from/this/mirror

**Comment by dunn** [comment]
For some reason the bottled version is unavailable. For now you can install it from source with `brew install -fs php56-mcrypt`.

**Comment by jacknagel** [comment]
This issue was moved to Homebrew/homebrew-php#1787
