### ISSUE TITLE
gnutls not building on 10.11 with XCode b7

### ISSUE THREAD

**Issue by shatteringlass** [Homebrew/homebrew#40642]
I'm actually experiencing this very same issue, on 10.11 (15A178w). No clue. Same error with gnutls 3.3.13 and 3.3.14 and 3.4.

```
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libgnutls.la] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1
```

EDIT: gist [here](https://gist.github.com/anonymous/804f6e2ae8aa4243b1b6)

**Comment by jacknagel** [comment]
>Xcode: 6.2
CLT: 7.0.0.0.1.1433655009

Please either update Xcode to the 7 beta or `sudo xcode-select --switch /Library/Developer/CommandLineTools`, or both.

**Comment by shatteringlass** [comment]
The log was from before updating to beta 7 (although CLT was up-to-date and selected). After updating, the error is just the same as before, so I didn't repeat brew logs.

**Comment by makigumo** [comment]
No problem here. Reinstall and uninstall/install ran both successfully.

```
OS X: 10.11-x86_64
Xcode: 7.0
CLT: 7.0.0.0.1.1433655009
Clang: 7.0 build 700
```

```
$ brew reinstall gnutls
==> Reinstalling gnutls
==> Downloading ftp://ftp.gnutls.org/gcrypt/gnutls/v3.3/gnutls-3.3.15.tar.xz

curl: (28) Operation timed out after 0 milliseconds with 0 out of 0 bytes received
Trying a mirror...
==> Downloading https://www.mirrorservice.org/sites/ftp.gnupg.org/gcrypt/gnutls/v3.3/gnutls-3.3.15.tar.xz
######################################################################## 100.0%
==> ./configure --disable-silent-rules --disable-static --prefix=/usr/local/Cellar/gnutls/3.3.15 --sysconfdir=/usr/local/etc --with-
==> make install
🍺  /usr/local/Cellar/gnutls/3.3.15: 1020 files, 8.8M, built in 2.0 minutes
```

**Comment by shatteringlass** [comment]
Oh god, I'm embarassed. I took [another](https://gist.github.com/anonymous/d75df0ed781e7a0c4c4d) brew gist-logs after the update. Still not installing. I guess I should try with a clean system, must've messed something up with mine. brew doctor complains a lot.
