### ISSUE TITLE
parent directory is world writable but not sticky

### ISSUE THREAD

**Issue by CKKing** [Homebrew/homebrew#40648]
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/cmd/postinstall.rb:18:in `run_post_install'
/usr/local/Library/Homebrew/cmd/postinstall.rb:5:in `block in postinstall'
/usr/local/Library/Homebrew/cmd/postinstall.rb:5:in `each'
/usr/local/Library/Homebrew/cmd/postinstall.rb:5:in `postinstall'
/usr/local/Library/brew.rb:140:in `<main>'

**Comment by CKKing** [comment]
Error: parent directory is world writable but not sticky

**Comment by jacknagel** [comment]
Run `brew doctor` and follow its advice (i.e. run disk utility and repair permissions).

**Comment by CKKing** [comment]
Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:

    php56

Warning: /tmp is world-writable but does not have the sticky bit set.
Please run "Repair Disk Permissions" in Disk Utility.


and I run  
brew link php56 
notice me :Error: php56 has multiple installed versions

and I don't konw how to do

**Comment by DomT4** [comment]
> Warning: /tmp is world-writable but does not have the sticky bit set.
Please run "Repair Disk Permissions" in Disk Utility.

As this says, you need to use the `Repair Disk Permissions` button in the Disk Utility.app

> :Error: php56 has multiple installed versions

Try `brew cleanup php56 && brew link php56` - Will remove everything but the most recent version installed, and then link the remaining version.

**Comment by CKKing** [comment]
thanks, but sorry, I don't know you need to use the Repair Disk Permissions button in the Disk Utility.app.
And I try your method brew cleanup, notice me Warning: Skipping josegonzalez/php/php56: most recent version 5.6.10 not installed
Error: php56 has multiple installed versions
because I have install multiple,or other?
