### ISSUE TITLE
building fftw with more options

### ISSUE THREAD

**Issue by francispoulin** [Homebrew/homebrew#40643]
I am very new to homebrew and sorry for this basic question but I am trying to install fftw with more options than default.  In particular, I would like to have openmp.  

Someone suggested that I try this but it didn't do anything new.

brew install fftw —enable-fortran —enable-threads —enable-fopenmp 

I gather that I can probably do this by creating a Formula but I haven't figured out how to do that.  Can someone give me a hand?  

Again, sorry for the basic question.  

Francis

**Comment by bfontaine** [comment]
Hello Francis,

You can see which options are supported by a given formula with `brew options`:

```
$ brew options fftw
--universal
	Build a universal binary
--with-fortran
	Enable Fortran bindings
--with-mpi
	Enable MPI parallel transforms
```

The actual [`fftw`](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/fftw.rb) formula doesn’t support `openmp`. Would you like to try a pull-request in order to modify it? [The Formula Cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md) should help you, as well as [this example formula](https://github.com/Homebrew/homebrew/blob/master/Library/Contributions/example-formula.rb). I’m happy to help you with any questions you have :smiley:

**Comment by francispoulin** [comment]
Thanks for pointing out the options and for pointing me in the right direction.  

Just to make sure I understand, you are suggesting that I figure out how to install fftw using these options and then submit it on github so it can be included as an option?  If yes I really like the idea.  

I think I know how to compile fftw normally (no homebrew) using configure but I am not sure if that is the right place to start.  

Or it occurs to me that if I can find where these options were were set up maybe I can copy them by simply adding to the configure options?

Sorry for being so lost but if you could help me to get started I will work on trying to figure it out.

Thanks, Francis

**Comment by francispoulin** [comment]
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/fftw.rb

I see this is the formula for the current fftw. 

When I checkout the fftw page at

http://www.fftw.org/doc/Installation-on-Unix.html

I see that they have an option with

--enable-openmp

That suggests that I should at least add the following to the current options

  option "with-fortran", "Enable Fortran bindings"
  option :universal
  option "with-mpi", "Enable MPI parallel transforms"
  option "with-openmp", "Enable OpenMP parallel transforms"

  depends_on :fortran => :optional
  depends_on :mpi => [:cc, :optional]
  depends_on :openmp => [:cc, :optional]

    args << "--disable-fortran" if build.without? "fortran"
    args << "--enable-mpi" if build.with? "mpi"
    args << "--enable-openmp" if build.with? "openmp"

I know that I need to create a website to test this but I thought I would run this idea by you to see whether I'm on the right track or out to lunch.

**Comment by bfontaine** [comment]
That’s exactly that, except that `:cc` is specific to `mpi`, so you’ll only use `depends_on :openmp => :optional`.

**Comment by francispoulin** [comment]
Hello again,

I modfiied the file like we discussed and saved it locally on my computer. Then I tried installing it as I thought the examples indicated but I received the following error. It also mentions I should report this error.  I am pretty sure I did something wrong but not sure what.  

I can copy my rb file in this link or somewhere else if that would help.

Thanks,
Francis

brew install --verbose --debug fftw.rb 
/usr/local/Library/brew.rb (Formulary::FromPathLoader): loading /Users/fpoulin/software/Homebrew/fftw.rb
Error: Unsupported special dependency :openmp
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/dependency_collector.rb:138:in `parse_symbol_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:81:in `parse_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:65:in `build'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `block in fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:38:in `add'
/usr/local/Library/Homebrew/software_spec.rb:134:in `depends_on'
/usr/local/Library/Homebrew/formula.rb:1093:in `block in depends_on'
/usr/local/Library/Homebrew/formula.rb:1093:in `each'
/usr/local/Library/Homebrew/formula.rb:1093:in `depends_on'
/Users/fpoulin/software/Homebrew/fftw.rb:24:in `<class:Fftw>'
/Users/fpoulin/software/Homebrew/fftw.rb:3:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:78:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:69:in `klass'
/usr/local/Library/Homebrew/formulary.rb:65:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:170:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:140:in `<main>'

**Comment by bfontaine** [comment]
Ah sorry it’s `depends_on "openmp" => :optional`.

**Comment by francispoulin** [comment]
Thank you!  That did much more than before.
From what I gather it made a lot of changes and finishes with this

....
Changing dylib ID of /usr/local/Cellar/fftw/3.3.4_1/lib/libfftw3l_threads.3.dylib
  from /usr/local/lib/libfftw3l_threads.3.dylib
    to /usr/local/lib/libfftw3l_threads.3.dylib
/usr/local/Library/Homebrew/postinstall.rb (Formulary::FromPathLoader): loading /Users/fpoulin/software/Homebrew/fftw.rb
==> Summary
🍺  /usr/local/Cellar/fftw/3.3.4_1: 39 files, 11M

It did create/update my fftw libraries but it does not seem to have any openmp.

$ ls /usr/local/lib/*fftw*
/usr/local/lib/libfftw3.3.dylib			/usr/local/lib/libfftw3f.3.dylib		/usr/local/lib/libfftw3l.3.dylib
/usr/local/lib/libfftw3.a			/usr/local/lib/libfftw3f.a			/usr/local/lib/libfftw3l.a
/usr/local/lib/libfftw3.dylib			/usr/local/lib/libfftw3f.dylib			/usr/local/lib/libfftw3l.dylib
/usr/local/lib/libfftw3_threads.3.dylib		/usr/local/lib/libfftw3f_threads.3.dylib	/usr/local/lib/libfftw3l_threads.3.dylib
/usr/local/lib/libfftw3_threads.a		/usr/local/lib/libfftw3f_threads.a		/usr/local/lib/libfftw3l_threads.a
/usr/local/lib/libfftw3_threads.dylib		/usr/local/lib/libfftw3f_threads.dylib		/usr/local/lib/libfftw3l_threads.dylib

Is there something else that I need to do?

**Comment by bfontaine** [comment]
You have to use the `--with-openmp` option to have openmp support :wink:

**Comment by francispoulin** [comment]
Of course. Sorry for not getting the obvious. I have now tried that and found problems.

$ brew install --verbose --debug fftw.rb --with-openmp --with-fortran --with-mpi
/usr/local/Library/brew.rb (Formulary::FromPathLoader): loading /Users/fpoulin/software/Homebrew/fftw.rb
Error: No available formula for fortran (dependency of fftw)
Searching formulae...
json-fortran
Searching taps...

Then it stops.  I think there is a problem with the fftw.rb that I found since even installing fortran and mpi don't work.  

https://github.com/Homebrew/homebrew/blob/master/Library/Formula/fftw.rb

I wonder whether I should find the actual formula used by default and modify that instead?

**Comment by xu-cheng** [comment]
@bfontaine There isn't a `openmp` dependency. The correct usage is `needs :openmp if build.with? "openmp"`.

**Comment by bfontaine** [comment]
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/fftw.rb *is* the actual formula.

**Comment by bfontaine** [comment]
@xu-cheng Thanks, what does `needs` do?

**Comment by xu-cheng** [comment]
`needs` is used to select compiler. Currently it can accept `:openmp` and `:cxx11`

**Comment by francispoulin** [comment]
Not sure if i follow the recent posts but I wanted to say thanks for the most recent formula.  I did start with that and modified it similarly and obtained the same thing.

Please let me know if there is anything I can try to help.
Thanks.

**Comment by bfontaine** [comment]
@francispoulin So, like @xu-cheng said, I was wrong: it’s not `depends_on "openmp" => :optional` but `needs :openmp if build.with? "openmp"`.

**Comment by francispoulin** [comment]
Thanks.  I started it and it seems to start correctly and seems to be doing its magic.

It seems that enabling mpi and fortran don't seem to work in this version.  Should I change them to the following?

 needs :fortran if build.with? "fortran"
 needs :mpi if build.with? "mpi"

I presume so but wanted to check because the official version doesn't do this.  Not sure why.

**Comment by francispoulin** [comment]
I tried those and (as you probably already know) it doesn't work out.

So the good news is I can now include openmp, thanks you you guys.  The bad news is that my script does not allow for fortran and mpi. However, the default does so clearly there is a difference from what I put together.  Sorry for not figuring this out myself.

**Comment by bfontaine** [comment]
Could you do a pull-request so everyone can use the `--with-openmp` option? Thanks!

**Comment by francispoulin** [comment]
I am happy to share this.  I admit that I am also very new to git so will need a bit of help with that too.  Are there instructions on how to do this?  I would guess this would include

1) forking homebrew on github.
2) git cloning it onto my computer
3) update my github account
4) Then do a pull request
Sorry that I wasn't able to figure out how to also enable fortran and mpi but I presume that will be included in the updated version.
Thanks,
Francis

**Comment by francispoulin** [comment]
I figured out how to enable the mpi and fortran.
I also followed the first 3 steps on the following page.  Not sure if that is only for my fork or for the main branch.

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-%28and-get-it-merged%29.md#how-to-open-a-homebrew-pull-request-and-get-it-merged

**Comment by francispoulin** [comment]
Hello,
I believe that I have now submitted a pull request.
Francis

**Comment by DomT4** [comment]
Thanks! Will close in favour of your #40830 PR.
