### ISSUE TITLE
After upgrade to OS X 10.11 stdio.h wasn't found

### ISSUE THREAD

**Issue by AlexanderWillner** [Homebrew/homebrew#40651]
Version: OS X 10.11 (15A178w)

Steps that will reproduce the problem?
1. Upgrade to OS X 10.11
2. Try to run brew install <package name>
3. Recognize that nothing compiles and remove and re-install brew following the according instructions on brew.sh
4. Run brew update && brew doctor

What is the expected result?
Should warn that /usr/include doesn't exist (if this existed before) and /usr/local/include also doesn't exist or points to a wrong path.

What happens instead?
Brew doctor was fine and nothing compiled since stdio.h wasn't found.

Possible workaround:
sudo ln -s /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include /usr/local/include

Any additional information:
Since OS X supports now "rootless", a link to /usr/include doesn't work.

**Comment by jacknagel** [comment]
You need to update Xcode and/or the CLT to the v7 beta.

**Comment by jacknagel** [comment]
(and then post the standard debugging information if things still fail).

**Comment by AlexanderWillner** [comment]
Thanks. Works fine with Xcode 7. However, I think "brew doctor" should not be fine if there is e.g. no stdio.h

**Comment by mistydemeo** [comment]
We have not yet merged #40536, which would warn you about exactly that.
