### ISSUE TITLE
Failed to build GCC on 10.11

### ISSUE THREAD

**Issue by mirosval** [Homebrew/homebrew#40650]
GCC both 5.1 and 4.9 fail with El Capitan, having installed just the command line tools (Apple LLVM version 7.0.0 (clang-700.0.53))

Git logs output
https://gist.github.com/anonymous/5d4076f4d6b1eae1803b

**Comment by jacknagel** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66523

**Comment by mirosval** [comment]
Good, can confirm this works when using the 6.3 command line tools.

**Comment by DomT4** [comment]
Moved to tracking in #40837.
