### ISSUE TITLE
Failed to build openconnect on 10.11 (No package 'libxml-2.0' found)

### ISSUE THREAD

**Issue by AlexanderWillner** [Homebrew/homebrew#40656]
Command: ```brew install openconnect```
Issue: ```No package 'libxml-2.0' found```
Gist: https://gist.github.com/b30a8ecd79bd67d04708
Solution: ```brew install libxml2 && brew link -f libxml2``` (doesn't work and libxml2 seems to be available anyway)

**Comment by mistydemeo** [comment]
This is an expected failure - we haven't yet set things up to build against the system libxlm2 on 10.11.

**Comment by AlexanderWillner** [comment]
Works. Even openconnect under 10.11. Nice. Thanks.
