### ISSUE TITLE
Failed to build nettle on 10.11

### ISSUE THREAD

**Issue by AlexanderWillner** [Homebrew/homebrew#40654]
See subject. Using OS X 10.11 with Xcode 7. Wanted to test openconnect actually.
Gist:
https://gist.github.com/c678591d1a6e019e39f1

**Comment by mistydemeo** [comment]
I can't reproduce; can you reinstall gmp, then retry nettle?

**Comment by AlexanderWillner** [comment]
Damn. This fixed it. Thanks.
