### ISSUE TITLE
freetype compile error on 10.11

### ISSUE THREAD

**Issue by blacRose** [Homebrew/homebrew#40678]
$ brew upgrade freetype -v
	==> Upgrading 1 outdated package, with result:
	freetype 2.6
	==> Upgrading freetype
	rm /usr/local/bin/freetype-config
	rm /usr/local/include/freetype2
	rm /usr/local/lib/libfreetype.6.dylib
	rm /usr/local/lib/libfreetype.a
	rm /usr/local/lib/libfreetype.dylib
	rm /usr/local/lib/pkgconfig/freetype2.pc
	rm /usr/local/share/aclocal/freetype2.m4
	rm /usr/local/share/man/man1/freetype-config.1
	==> Downloading https://downloads.sf.net/project/freetype/freetype2/2.6/freetype-2.6.tar.bz2
	Already downloaded: /Library/Caches/Homebrew/freetype-2.6.tar.bz2
	==> Verifying freetype-2.6.tar.bz2 checksum
	tar xf /Library/Caches/Homebrew/freetype-2.6.tar.bz2
	==> ./configure --prefix=/usr/local/Cellar/freetype/2.6 --without-harfbuzz

	Generating modules list in ./objs/ftmodule.h...
	FreeType build system -- automatic system detection

	The following settings are used:
	* module: truetype  (Windows/Mac font files with extension *.ttf or *.ttc)

	  platform                    unix
	* module: type1     (Postscript font files with extension *.pfa or *.pfb)
	  compiler                    clang
	  configuration directory     ./builds/unix
	* module: cff       (OpenType fonts with extension *.otf)
	  configuration rules         ./builds/unix/unix.mk

	* module: cid       (Postscript CID-keyed fonts, no known extension)
	If this does not correspond to your system or settings please remove the file
	`config.mk' from this directory then read the INSTALL file for help.
	* module: pfr       (PFR/TrueDoc font files with extension *.pfr)

	Otherwise, simply type `/Applications/Xcode.app/Contents/Developer/usr/bin/make' again to build the library,
	or `/Applications/Xcode.app/Contents/Developer/usr/bin/make refdoc' to build the API reference (this needs python >= 2.6).
	* module: type42    (Type 42 font files with no known extension)

	* module: winfnt    (Windows bitmap fonts with extension *.fnt or *.fon)
	* module: pcf       (pcf bitmap fonts)
	* module: bdf       (bdf bitmap fonts)
	* module: sfnt      (helper module for TrueType & OpenType formats)
	* module: autofit   (automatic hinting module)
	* module: pshinter  (Postscript hinter module)
	* module: raster    (monochrome bitmap renderer)
	* module: smooth    (anti-aliased bitmap renderer)
	* module: smooth    (anti-aliased bitmap renderer for LCDs)
	* module: smooth    (anti-aliased bitmap renderer for vertical LCDs)
	* module: psaux     (Postscript Type 1 & Type 2 helper module)
	* module: psnames   (Postscript & Unicode Glyph name handling)
	done.
	cd builds/unix; \
		      CONFIG_SHELL="/bin/sh" \
		        /bin/sh ./configure  '--prefix=/usr/local/Cellar/freetype/2.6' '--without-harfbuzz'
	checking build system type... x86_64-apple-darwin15.0.0
	checking host system type... x86_64-apple-darwin15.0.0
	checking for gcc... clang
	checking whether the C compiler works... yes
	checking for C compiler default output file name... a.out
	checking for suffix of executables...
	checking whether we are cross compiling... configure: error: in `/private/tmp/freetype20150613-16196-gilqg9/freetype-2.6/builds/unix':
	configure: error: cannot run C compiled programs.
	If you meant to cross compile, use `--host'.
	See `config.log' for more details
	make: *** [setup] Error 1
	==> Formula
	Path: /usr/local/Library/Formula/freetype.rb
	==> Configuration
	HOMEBREW_VERSION: 0.9.5
	ORIGIN: https://github.com/Homebrew/homebrew
	HEAD: ce8f10121845506fef5b70297467ea87b39a8295
	Last commit: 3 hours ago
	HOMEBREW_PREFIX: /usr/local
	HOMEBREW_CELLAR: /usr/local/Cellar
	CPU: quad-core 64-bit haswell
	OS X: 10.11-x86_64
	Xcode: 6.3.2
	CLT: N/A
	Clang: 6.1 build 602
	X11: 2.7.7 => /opt/X11
	System Ruby: 2.0.0-p645
	Perl: /usr/bin/perl
	Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/bin/python2.7
	Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.2/bin/ruby
	Java: 1.8.0_25
	==> ENV
	HOMEBREW_CC: clang
	HOMEBREW_CXX: clang++
	MAKEFLAGS: -j4
	CMAKE_PREFIX_PATH: /usr/local
	CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
	CMAKE_FRAMEWORK_PATH: /System/Library/Frameworks
	PKG_CONFIG_PATH: /usr/local/opt/libpng/lib/pkgconfig
	PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig
	HOMEBREW_SDKROOT:
	ACLOCAL_PATH: /usr/local/share/aclocal
	PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/libpng/bin:/usr/bin:/bin:/usr/sbin:/sbin

	Error: freetype 2.6 did not build
	Logs:
	     /Users/user/Library/Logs/Homebrew/freetype/01.configure
	     /Users/user/Library/Logs/Homebrew/freetype/01.configure.cc

	These open issues may also help:
	Building exact-image failed with freetype/libagg dependency (https://github.com/Homebrew/homebrew/issues/39622)

	ln -s ../Cellar/freetype/2.5.5/bin/freetype-config freetype-config
	ln -s ../Cellar/freetype/2.5.5/include/freetype2 freetype2
	ln -s ../../Cellar/freetype/2.5.5/share/aclocal/freetype2.m4 freetype2.m4
	ln -s ../../../Cellar/freetype/2.5.5/share/man/man1/freetype-config.1 freetype-config.1
	ln -s ../Cellar/freetype/2.5.5/lib/libfreetype.6.dylib libfreetype.6.dylib
	ln -s ../Cellar/freetype/2.5.5/lib/libfreetype.a libfreetype.a
	ln -s ../Cellar/freetype/2.5.5/lib/libfreetype.dylib libfreetype.dylib
	ln -s ../../Cellar/freetype/2.5.5/lib/pkgconfig/freetype2.pc freetype2.pc

**Comment by mistydemeo** [comment]
> Xcode: 6.3.2

You need to upgrade to the Xcode 7 beta to build software on 10.11.

**Comment by blacRose** [comment]
Oops, thanks! Good to know!

**Comment by blacRose** [comment]
Fixed with Xcode 7.
