### ISSUE TITLE
OpenSSL compile error on 10.11

### ISSUE THREAD

**Issue by blacRose** [Homebrew/homebrew#40680]
Output too long for GitHub, [here it is.](http://codebin.org/view/69c482fd)

**Comment by mistydemeo** [comment]
Your config output is still showing Xcode 6.3.2; you may need to use `xcode-select` to pick the Xcode 7 beta location.

**Comment by blacRose** [comment]
Xcode: 6.3.2
You need to upgrade to the Xcode 7 beta to build software on 10.11.

**Comment by blacRose** [comment]
Fixed with Xcode 7.

**Comment by jarinudom** [comment]
You can also just do `xcode-select --install` if you don't want to download all of Xcode
