### ISSUE TITLE
'Undefined error: 0' after copy OS to SSD

### ISSUE THREAD

**Issue by djKooky** [Homebrew/homebrew#40699]
Hello,

I copied OS data on my mac to new SSD using disk utility, and brew does not work with command like below.

/usr/local/bin/brew: /usr/local/Library/brew.rb: /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby: bad interpreter: No such file or directory
/usr/local/bin/brew: line 21: /usr/local/Library/brew.rb: Undefined error: 0

But if I try to install brew again, it said brew still exists.
Is there somebody know about this?

Thanks.

**Comment by mikemcquaid** [comment]
`cd /usr/local; git fetch; git reset --hard origin/master; brew update` and it should be fixed.

**Comment by lainman** [comment]
@mikemcquaid Thanks for your help~
Why does this issue happens?

**Comment by mikemcquaid** [comment]
@djKooky Because you had an old version of Homebrew installed after upgrading your OS.
