### ISSUE TITLE
Apache(2.4.12) + Passenger 5.0.10 doesn't work

### ISSUE THREAD

**Issue by Drewshg312** [Homebrew/homebrew#40713]
Trying to configure Snorby(ruby app) to work with Apache/2.4.12 and Passenger 5.0.10.

-- I've successfully installed from homebrew apache and passenger. 

    brew install httpd24 passenger

-- Created **/etc/apache/other/passenger.conf** (as instructed in Homebrew):

    LoadModule passenger_module /usr/local/opt/passenger/libexec/buildout/apache2/mod_passenger.so
        PassengerRoot /usr/local/opt/passenger/libexec/lib/phusion_passenger/locations.ini
        PassengerDefaultRuby /usr/local/var/rbenv/versions/1.9.3-p551/bin/ruby
-- Enabled virtual hosts module in **/usr/local/etc/apache2/2.4/httpd.conf**:

    # Virtual hosts
    Include /usr/local/etc/apache2/2.4/extra/httpd-vhosts.conf
and

    LoadModule vhost_alias_module libexec/mod_vhost_alias.so

-- Created Virtual host in **/usr/local/etc/apache2/2.4/extra/httpd-vhosts.conf**:

    <VirtualHost *:8080>
            ServerAdmin Andryuwka@localhost
            ServerName snorby.server.loc
            ServerAlias www.snorby.server.loc
            DocumentRoot /usr/local/var/www/snorby/public
            <Directory "/usr/local/var/www/snorby/public">
                    Options Indexes FollowSymLinks Includes ExecCGI
                    AllowOverride all
                    Order deny,allow
                    Allow from all
                    #Require all granted
                    Options -MultiViews
            </Directory>
    </VirtualHost>

-- added `127.0.0.1 snorby.server.loc www.snorby.server.loc` to **/etc/hosts**

-- restarted httpd with `apachectl restart`

but when navigating www.snorby.server.loc in browser instead of running rails-driven application (Snorby login page and dashboards) getting just the files content of `/usr/local/var/www/snorby/public`:

    Index of /
    
    404.html
    422.html
    500.html
    assets/
    favicon.ico
    favicon.png
    flash/
    images/
    javascripts/
    robots.txt
    stylesheets/

Should be something like in this post (scroll down):https://www.corelan.be/index.php/2011/02/27/cheat-sheet-installing-snorby-2-2-with-apache2-and-suricata-with-barnyard2-on-ubuntu-10-x/

So I assume passenger doesn't work with apache properly and doesn't start the application(correct me if I'm wrong). What am I doing wrong? 
`apachectl -M | sort` gives me this(nothing with "passenger"):
 
    access_compat_module (shared)
    alias_module (shared)
    auth_basic_module (shared)
    authn_core_module (shared)
    authn_file_module (shared)
    authz_core_module (shared)
    authz_groupfile_module (shared)
    authz_host_module (shared)
    authz_user_module (shared)
    autoindex_module (shared)
    core_module (static)
    dir_module (shared)
    env_module (shared)
    filter_module (shared)
    headers_module (shared)
    http_module (static)
    log_config_module (shared)
    mime_module (shared)
    mpm_prefork_module (static)
    php5_module (shared)
    reqtimeout_module (shared)
    setenvif_module (shared)
    so_module (static)
    status_module (shared)
    unixd_module (shared)
    version_module (shared)
    vhost_alias_module (shared)
    Loaded Modules:
Though homebrew claims that their apache already configured for work with passenger, I'm wondering if there is any way to check it?

**Comment by makigumo** [comment]
This is a configuration problem on your side.

In your example you are configuring and thus confusing two httpd instances (the one coming with OS X and your homebrewed version), where all configuration should probably happen inside ```/usr/local/etc/apache2/2.4/```.

So if you move and/or include ```/etc/apache/other/passenger.conf``` in your ```/usr/local/etc/apache2/2.4/httpd.conf``` it will probably work.

**Comment by Drewshg312** [comment]
I've moved `/etc/apache/other/passenger.conf` to `/usr/local//etc/apache/2.4/other/passenger.conf` but it doesn't make any difference... Then I've tried to find anything with "passenger" in  `/usr/local/etc/apache2/2.4/httpd.conf` and I've found nothing... So I suppose I should write something like `LoadModule passenger_module        /usr/local/opt/passenger/libexec/buildout/apache2/mod_passenger.so` or better include `/usr/local/etc/apache/other/passenger.conf` but how to do it?
