### ISSUE TITLE
Request: better handling of dependency upgrades

### ISSUE THREAD

**Issue by RSully** [Homebrew/homebrew#40723]
Use case:

1) Install package A which depends on package B
2) `brew upgrade` upgrades package B
3) `brew cleanup` removes the old version of package B
4) Package A is now broken (e.g. "dyld: Library not loaded")

2 solutions (ideally both):

1) After step 2 brew could let me know that package A should be reinstalled
2) During step 3 brew could let me know it is skipping package B because A depends on an older version of it.

**Comment by jacknagel** [comment]
We handle this by adding revisions to dependents ("A" in the above scenario) when breaking upgrades occur. If one was missed, please file a bug against that package specifically.

**Comment by RSully** [comment]
This happens quite often with ffmpeg and its dependencies x265/x264/etc..
