### ISSUE TITLE
Failed to install xz & others: "configure: error: cannot run C compiled programs"

### ISSUE THREAD

**Issue by jtbandes** [Homebrew/homebrew#40726]
OS X 10.11, Xcode 6.3.2 and Xcode 7 both installed but command line tools set to the former. Building `xz` fails, as does `fish` and many other packages (when I tried to do `brew upgrade`).

Logs: https://gist.github.com/fdd7611b9aed29399c24

This looks a little suspicious:
```
configure:5153: clang -V >&5
clang: error: unsupported option '-V -isysroot'
```

```
clang: warning: no such sysroot directory: ''
```

**Comment by mikemcquaid** [comment]
> OS X 10.11

This is the first developer preview of an OS. Most packages will be broken.

**Comment by DomT4** [comment]
If you're using 10.11, you should be *using* the Xcode 7 beta. The mixture of new system + old Xcode will cause failure.

**Comment by jacknagel** [comment]
To echo the above, you have to use Xcode 7 on 10.11.

**Comment by alex88** [comment]
@jacknagel @DomT4 here I had just to reinstall command line tools with `xcode-select --install`
