### ISSUE TITLE
Proposal: Brew info to display post-install information

### ISSUE THREAD

**Issue by firedev** [Homebrew/homebrew#40724]
Hi,

I propose to change `brew info` so it includes post-install information. Recently I have spent few days off line because I was unable to recompile some gems, the missing piece of the puzzle was unaccessible to me. 

And it's not the first time I have been bitten by it, but prior to this I was able to quickly find solutions on StackOverflow. And this time the information I have found was outdated so the switch didn't work. If I could see all the information about the installed formula it would save time.

Please consider this. The details are here: https://github.com/eventmachine/eventmachine/issues/602

**Comment by jacknagel** [comment]
Which specific information are you referring to? `brew info` does display the caveats by default (some may be hidden behind specific build-time options, though).

**Comment by mistydemeo** [comment]
It looks like that issue is referring to the autogenerated keg-only caveats, which aren't printed by `brew info`.

**Comment by mistydemeo** [comment]
I'm fine with moving this into `brew info`, if there are no objections. I've fielded a few questions from confused users in IRC.

**Comment by firedev** [comment]
@jacknagel In my case those were the compile-your-own-thing switches.

I was using `--with--ssldir` which I have found on StackOverflow, but what I needed was `--with-cppflags=-I`. This is trivial if you're compiling your own things everyday. But for me it was a year since the last OS X update and just can't remember everything there is to know.

**Comment by mistydemeo** [comment]
Change made!

**Comment by firedev** [comment]
Thank you!
