### ISSUE TITLE
what would the command "brew man cask" do?

### ISSUE THREAD

**Issue by ajlowndes** [Homebrew/homebrew#40735]
I am a bit of a newbie, and instead of typing "man brew-cask" I typed "brew man cask". Terminal then proceeded to dl and install "hpricot-0.8.6.gem", "rdiscount-2.1.8.gem", "mustache-1.0.1.gem" and "ronn-0.7.3.gem"... but I have no idea what these four things are or whether I need them. When I google those names they appear to be something to do with html development. Can anybody tell me what the hell I just installed?

**Comment by bfontaine** [comment]
`brew man` generates the Homebrew manpage from markdown, using these gems to do the translation.

**Comment by ajlowndes** [comment]
Awesome, thanks
