### ISSUE TITLE
Can't install PHP55 ... 404 Not Found

### ISSUE THREAD

**Issue by ksnyde** [Homebrew/homebrew#40734]
I recently ran into a problem where attempt to `upgrade` any of the PHP taps fails with a 404 error. Specifically:

> ==> Upgrading homebrew/php/php55
> ==> Downloading https://www.php.net/get/php-5.5.26.tar.bz2/from/this/mirror
> ==> Downloading https://www.php.net/get/php-5.5.26.tar.bz2/from/this/mirror
> curl: (22) The requested URL returned error: 404 Not Found
> Download failed: https://www.php.net/get/php-5.5.26.tar.bz2/from/this/mirror

This has put me into a very bad place as I can't do anything with PHP at the moment. Any help would be greatly appreciated.

**Comment by ksnyde** [comment]
Note that trying to upgrade **PHP55-mcrypt** results in the same outcome ... non-PHP based *upgrades* are working fine.

**Comment by jacknagel** [comment]
This issue was moved to Homebrew/homebrew-php#1797
