### ISSUE TITLE
Where and how should one report outdated formulae?

### ISSUE THREAD

**Issue by janlimpens** [Homebrew/homebrew#40749]
Or should we at all?

**Comment by mikemcquaid** [comment]
It's better to submit a pull-request to update them. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by janlimpens** [comment]
I am not sufficiently an expert on the software in question, all I know is, that it stepped up its version. I cannot tell about any of the ramifications of this, whether it breaks anything or would build correctly, tests would fails etc...
So while, by the look of it the patch would only change a 5 to a 6, I doubt I would be the right person to do this. How is this handled? If it´s not handled at all, I´d happily provide the patch and accept no responsibility, but I also would get an uneasy feeling about homebrew, or am I just paranoid? Probably.

**Comment by jacknagel** [comment]
Well, as part of the submission process, there is an expectation that you've done at least a little bit of research as to the possible consequences of a version update (this is less important if you're just updating from say, version 1.2.3 to 1.2.4, than if you are updating from version 1 to 2).

But we welcome pull requests, and there is CI in place to prevent major breakage. There isn't any process you need to go through - we don't have a concept of package maintainers, anyone can submit updates to any package.

If you're really not comfortable making the change yourself, you can send a message to the mailing list (homebrew@librelist.com) or the IRC channel (freenode #machomebrew) and perhaps someone else will do it.
