### ISSUE TITLE
Upgrade of winetricks triggers downgrade of wine

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew#40751]
I have installed wine --devel (1.7.44), but upgrade of winetricks cause downgrade of wine to 1.6.2.

Now I have both wine in /usr/local/Cellar/wine, but I can't link the --devel one

**Comment by jacknagel** [comment]
This is a known defect, if a devel version falls out of date, it will no longer satisfy some installation checks during dependency expansion. You can `brew upgrade wine --devel` first.

Fixing this is on the roadmap but I can't guarantee when it will happen. It's not a simple change.
