### ISSUE TITLE
Inconsistent handling of ~ in HOMEBREW_CACHE variable

### ISSUE THREAD

**Issue by roblabla** [Homebrew/homebrew#40752]
Hello,
I have recently found out that setting `HOMEBREW_CACHE` variable to `~/Library/Caches/Homebrew` (anything under ~/, really) seems to confuse homebrew in a very weird way : 

```
$> HOMEBREW_CACHE="~/Library/Caches/Homebrew" brew install opam
==> Installing dependencies for opam: objective-caml, camlp4, boost, cmake, re2c, gringo, clasp, aspcud
==> Installing opam dependency: objective-caml
==> Downloading http://caml.inria.fr/pub/distrib/ocaml-4.02/ocaml-4.02.1.tar.gz
######################################################################## 100.0%
Error: No such file or directory - ~/Library/Caches/Homebrew/objective-caml-4.02.1.tar.gz
```

After investigation, homebrew downloaded the file to `$HOME/\~/Library/Caches/Homebrew` instead of `$HOME/Library/Caches/Homebrew`.

**Comment by mikemcquaid** [comment]
This is somewhat expected; `~` is a shell shortcut rather than a Unix universal and various other applications won't expand it in user input either.

**Comment by jacknagel** [comment]
I think this is a bug. We expand `~` for `HOMEBREW_LOGS`, for example.

We should call expand_path here:
https://github.com/Homebrew/homebrew/blob/6fde119dafd52c1521f6b3fed06a01f494729dae/Library/Homebrew/config.rb#L2-L3

**Comment by roblabla** [comment]
@mikemcquaid While I agree with you that it's probably not a great idea to use the tilde here, there still is an inconsistency between the download step (which goes to `$HOME/\~/...`) and the next step, which doesn't look for the file at the same place the downloader did.

**Comment by jacknagel** [comment]
In the interest of accurately describing the bug, I think in the above example, it really went to `$PWD`, which happened to be `$HOME` when you ran the command. By the time the value is used again, the current working directory has changed, and so it fails to find the file.
