### ISSUE TITLE
El Capitan: Upgrades now fail with couldn't understand kern.osversion `15.0.0'

### ISSUE THREAD

**Issue by nodesocket** [Homebrew/homebrew#40762]
Here is an example:

````
==> ./configure --prefix=/usr/local/Cellar/apr/1.5.2/libexec
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/private/tmp/apr20150615-5342-nur4ix/apr-1.5.2':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
couldn't understand kern.osversion `15.0.0'
````

and another:

````
==> Upgrading openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2c.tar.gz
Already downloaded: /Library/Caches/Homebrew/openssl-1.0.2c.tar.gz
==> perl ./Configure --prefix=/usr/local/Cellar/openssl/1.0.2c --openssldir=/usr/local/etc/openssl no-ssl2 zlib-dynamic shared enable-cms darwin64-x86_64-c
==> make depend
==> make
# include <stdlib.h>
          ^
1 error generated.
make[1]: *** [cryptlib.o] Error 1
make: *** [build_crypto] Error 1
couldn't understand kern.osversion `15.0.0'
````

**Comment by DomT4** [comment]
Most likely cause is that your Xcode or CLT is outdated. What do your `brew config` and `brew doctor` say?

**Comment by nodesocket** [comment]
````
➜  ~  brew config
Warning: Although Homebrew has added initial recognition of 10.11, it is unsupported.
You may encounter breakage or other failure and there is no guarantee
Homebrew can resolve those issues until El Capitan is stable.

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 86ed4365d05fb7d9ade393edaf4f46c53ebb32ce
Last commit: 9 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit arrandale
OS X: 10.11-x86_64
Xcode: 6.3.2
CLT: N/A
couldn't understand kern.osversion `15.0.0'
GCC-4.2: build 5666
Clang: 6.1 build 602
X11: N/A
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/justin/.rvm/rubies/ruby-1.9.3-p547/bin/ruby
Java: 1.8.0_60-ea
````

**Comment by DomT4** [comment]
You need to update your Xcode to the 7.0 Beta. 10.11 and the 6.3.x Xcode releases aren't compatible.

**Comment by nodesocket** [comment]
Software update is not showing a new version of Xcode. Is this a manual thing?

**Comment by mistydemeo** [comment]
The Xcode 7 beta is a separate beta program; you may not be part of it. Are you a paid Mac dev program member?

If not, you can uninstall Xcode and install the CLT via `xcode-select --install`; the Xcode 7 CLT is available to all 10.11 users.

**Comment by DomT4** [comment]
For the developer previews you usually have to obtain the updated Xcode manually. Available from [here](https://developer.apple.com/xcode/downloads/). Otherwise you'll need to obtain the CLT and switch your `xcode-select` path over.

**Comment by nodesocket** [comment]
Running `xcode-select --install` was enough to fix the issue. No need to uninstall my previous version of Xcode.

Thanks.

**Comment by kaepora** [comment]
Thanks for this!

**Comment by smason** [comment]
I have been struggling with this as well.  Some scripts appeared to be picking up the compiler in `apple-gcc42`, uninstalling the package (`brew uninstall apple-gcc42`—to help Google) made the `couldn't understand kern.osversion 15.0.0` error go away.

**Comment by DomT4** [comment]
@Homebrew/owners Did we ever make a decision on blacklisting `gcc42` for recent OS X versions going forwards?

**Comment by mikemcquaid** [comment]
@DomT4 We didn't but if it's actively broken: we should.

**Comment by remofritzsche** [comment]
I'm not able to manually build certain packages (such as ruby 2.0) without apple-gcc42 installed as it then doesn't find openssl. Is there a workaround for this?

**Comment by DomT4** [comment]
@remofritzsche Please open a new issue on that with `brew gist-log` links for some of the formulae you've tried. We haven't seen that sort of failure anywhere else yet, so hopefully it's just something on your side that we can identify and help fix.

**Comment by sepehr** [comment]
Upgrading XCode to 7.x worked for me.

**Comment by jveitchmichaelis** [comment]
The issue with `apple-gcc42` still seems to be the problem, my config is:

````
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 2f39e333a725baea82c036d23350d037ee034b36
Last commit: 67 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit penryn
OS X: 10.11-x86_64
Xcode: 7.2
CLT: 7.2.0.0.1.1447826929
couldn't understand kern.osversion `15.0.0'
GCC-4.2: build 5666
Clang: 7.0 build 700
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/Josh/.rvm/rubies/ruby-1.9.3-p429/bin/ruby
Java: 1.7.0_09, 1.6.0_65-b14-468
````
Uninstalling `apple-gcc42` solved the problem when I got the version error trying to update `gnuplot`.

**Comment by DG12** [comment]
/Users/dgerman > gcc frag.c
couldn't understand kern.osversion `15.3.0'
frag.c:3:19: error: stdio.h: No such file or directory
...
gcc ... ... ---with-gxx-include-dir=/usr/include/c++/4.2.1
Which under mavericks was good, now under El Captian /usr/include is not there at all.

stdio.h only exists in several /Applications/Xcode.app/Contents/Developer directories


I believe my Xcode is up to date:  about Xcode 7.2.1
 (as per https://developer.apple.com/xcode/download/0
dgerman > xcode-select -p
/Applications/Xcode.app/Contents/Developer

**Comment by MrThiago** [comment]
Hi guys
I am having the same probelm:


Warning: Although Homebrew has added initial recognition of 10.11, it is unsupported.
You may encounter breakage or other failure and there is no guarantee
Homebrew can resolve those issues until El Capitan is stable.

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 71f219ddcbf666e458d5e10e60c213c8d2f40b
Last commit: 1 year ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit haswell
OS X: 10.11.5-x86_64
Xcode: 7.3.1
CLT: N/A
Clang: 7.3 build 703
X11: N/A
System Ruby: 2.0.0-p648
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.8.0_31


Whenever i run brew update nothing happen apart from the warning message:

Warning: Although Homebrew has added initial recognition of 10.11, it is unsupported.
You may encounter breakage or other failure and there is no guarantee
Homebrew can resolve those issues until El Capitan is stable.

**Comment by DomT4** [comment]
@MrThiago That's a pretty impressive length of time since you last `brew update`d 😄. Mind opening a new Issue over at https://github.com/Homebrew/brew? This repo has been deprecated.
