### ISSUE TITLE
How can I fixed “Error: Formulae found in multiple taps”?

### ISSUE THREAD

**Issue by yuhaya** [Homebrew/homebrew#40776]
I want to install php54-redis.

Yu$ brew install josegonzalez/php/php54-redis
==> Installing php54-redis from josegonzalez/homebrew-php
Error: Formulae found in multiple taps:
homebrew/php/php54
josegonzalez/php/php54
Please use the fully-qualified name e.g. homebrew/php/php54 to refer the formula.

How can I do?

**Comment by mikemcquaid** [comment]
`brew untap josegonzalez/homebrew-php`

**Comment by RussellBradley** [comment]
just solved my problem thanks @mikemcquaid
