### ISSUE TITLE
glm 0.9.6.3 insufficient access rights

### ISSUE THREAD

**Issue by sebastiankaybelle** [Homebrew/homebrew#40782]
Hi all,

the content in directory `/usr/local/Cellar/glm/0.9.6.3/include/glm` is not accessible due to insufficient access rights after updating/(re-)installing GLM. All files in that directory (as well as the files in subdirectories) only have `-rw-------` access set.

I did not update GLM for a long time (version 0.9.5.), however, previously everything worked fine. Running `brew doctor` only states that `/usr/local/share/man/man8` is not writable. Further, installing/updating other formulas (e.g. boost, Qt5, ...) works fine.

Any ideas?

Best,

Sebastian

**Comment by bfontaine** [comment]
Seems to be an upstream issue, I get the same rights if I download and `untar` the archive by hand.

**Comment by sebastiankaybelle** [comment]
I still had two older archives in `/Library/Caches/Hombrew` (`glm-0.9.5.4.zip` and `glm-0.9.6.1.zip`). Access privileges are correct after un-archiving those by hand.

Likewise, access privileges are set correct (with extended attributes indicated by the `@` in the output of `ls -la`) in the un-archived GLM archive downloaded from http://sourceforge.net/projects/ogl-math/files/latest/download?source=files

For now I solved this issue by `brew install --HEAD glm`

**Comment by DomT4** [comment]
Seems to have been resolved for a while now.
