### ISSUE TITLE
brew doctor to report non-master branch

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew#40790]
For example, someone has contributed to project or cask. He/she has created branch, pushed it to own fork, created PR, but he/she had forgot to switch branch back to master. brew up will pull from current branch, not master.

**Comment by DomT4** [comment]
`brew update` switches to [master](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/update.rb#L128) when it pulls. Are you not seeing that behaviour?

**Comment by yurikoles** [comment]
Sorry, the ticket is wrong.

**Comment by DomT4** [comment]
All okay?

**Comment by yurikoles** [comment]
>`brew update` switches to master when it pulls. Are you not seeing that behaviour?

But then it switches back again and you will never know why there is no updates until you check brew's git branch manually. I understand that this is rare case and contributors are responsible for this, but small hint about non-master branch will be very useful.
