### ISSUE TITLE
AGDA fails to compile on 10.10

### ISSUE THREAD

**Issue by papadil** [Homebrew/homebrew#40802]
Agda fails to compile showing the following message:
==> cabal sandbox init
==> cabal update
==> cabal install --jobs=4 alex
==> cabal install --jobs=4 happy
==> cabal install --jobs=4 cpphs
==> cabal install --jobs=4 --prefix=/usr/local/Cellar/agda/2.4.2.2_1 epic
==> cabal install --jobs=4 --only-dependencies -fepic
Backjump limit reached (change with --max-backjumps).

I try to put the --max-backjumps in my cabal init file but had no effect.  The gist link follows:
https://gist.github.com/b9f376696d4286957899

**Comment by DomT4** [comment]
Was recently updated and no longer seems to be an issue. Please `brew update` and try again.
