### ISSUE TITLE
Request: pam_usb

### ISSUE THREAD

**Issue by tristan-k** [Homebrew/homebrew#40852]
While there is a formula for Yubikey (https://github.com/Yubico/yubico-pam) there is no one for pam_usb (https://github.com/aluzzardi/pam_usb) or pam_usbkey (https://github.com/ColumPaget/pam_usbkey). Compared to plain USB Flashdrives Yubikeys are still expansive. There was some effort to make it compatible with macosx: https://github.com/aluzzardi/pam_usb/pull/16/commits

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by DomT4** [comment]
Will welcome a PR for this, Thanks!
