### ISSUE TITLE
Add Torsten Seemann @tseemann to Homebrew/science

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew#40864]
@Homebrew/owners Torsten Seemann @tseemann has a solid [commit history with Homebrew-science](https://github.com/Homebrew/homebrew-science/commits?author=tseemann), and the @Homebrew/science team agree that Torsten should be added as a contributor. Thanks!

**Comment by mikemcquaid** [comment]
Done! Welcome @tseemann.

**Comment by sjackman** [comment]
Thanks, Mike! Does he have access to BinTray and BuildTestBot as well?

**Comment by mikemcquaid** [comment]
@BrewTestBot yep. @tseemann needs to create a Bintray account and shout here with the username and I'll add him.

**Comment by tseemann** [comment]
@mikemcquaid My Bintray username is *tseemann* https://bintray.com/tseemann

**Comment by mikemcquaid** [comment]
@tseemann Invited

**Comment by tseemann** [comment]
@mikemcquaid I didn't receive any invite to my email, in my Spam, or on the bintray site?

**Comment by mikemcquaid** [comment]
@tseemann I see you as part of the homebrew science team. Do you not have permissions?

**Comment by tseemann** [comment]
@mikemcquaid I'm part of homebrew-science (github) but I assumed I'd end up in some "Organization" on bintray.com ?

**Comment by mikemcquaid** [comment]
![screen shot 2015-06-23 at 09 22 29](https://cloud.githubusercontent.com/assets/125011/8301847/9997e92e-1989-11e5-97da-199befca6843.png)
