### ISSUE TITLE
Proposal: display caveats in `brew info` according to how the formula has been installed.

### ISSUE THREAD

**Issue by alexeymuranov** [Homebrew/homebrew#40863]
I find the meaning of `caveats` method confusing when it is used by `brew info`.

I see that conditionals like `build.with?` are often used in `caveats` method, and it makes sense if `caveats` generates post-install information.  However, in this case it is strange that `caveats` are also displayed for a formula that has not yet been installed.  What is the point of this?  Should the user run `brew info` with all possible combinations of options 2<sup>N</sup> times to learn all possible caveats, or should he or she know exactly the options with which to install before running `brew info` (and before `brew install`)?

IMO, this is even more confusing when running `brew info` for a formula that is installed.  In this case the (poor) user should not forget to provide exactly the same options that were given to `brew install`, otherwise the (unsuspecting) user will see the wrong caveats.

I would suggest to make `brew info` not display any caveats if the formula has not been installed, and otherwise display the caveats for the options that were actually used at installation.

What do you think?

P.S. Some documentation of the semantics of `caveats` would be helpful.

P.P.S.  IMO, it is strange anyway to use the same options with `brew install` and with `brew info`.

**Comment by mikemcquaid** [comment]
> I would suggest to make brew info not display any caveats if the formula has not been installed, and otherwise display the caveats for the options that were actually used at installation.

I think that's a good idea.

**Comment by alexeymuranov** [comment]
The same applies to `brew test` and friends, i think.

**Comment by alexeymuranov** [comment]
A change probably must be made in how `build.include?`, `build.with?`, `build.without?` behave.  For example, they can raise an error if the formula is not installed and not being installed, and otherwise tell about how the formula was actually installed.

**Comment by jacknagel** [comment]
`brew test` already respects installed options.

Changing the behavior of the BuildOptions class is not appropriate. You can see how we handle it for `brew test` here. https://github.com/Homebrew/homebrew/blob/39dc3bba1210678fdc5ce5687b898f97bbdb9cba/Library/Homebrew/formula.rb#L792

**Comment by chdiza** [comment]
I don't think this is a good idea.  Sometimes the caveats for an uninstalled formula tell me something that makes me decide "I don't think I'm going to install that now", or "I had better back up my such-and-such before I try this formula".

**Comment by alexeymuranov** [comment]
How do you know which caveats of an uninstalled formula to look for?  Currently they will be different depending on the options you give to `brew info`.

**Comment by jacknagel** [comment]
Taking a step back, this may be an X-Y problem.

Perhaps the real problem is that one method, sprinkled with conditionals, that returns a string, is a bad way to represent all of the information that we currently use it to represent.

Maybe we need a better abstraction.

**Comment by alexeymuranov** [comment]
There could be multiple problems, but one of them is that the semantics of `caveats` is not specified (i thought first that whenever a user calls `brew info`, the `caveats` will be executed in an appropriate context, where `build.include?` evaluates according to the actual build options). Another, but related, problem is that a user, who may know nothing about `caveats`, types `brew info` and sees some irrelevant caveats because the formula has been installed with some options.

**Comment by chdiza** [comment]
> How do you know which caveats of an uninstalled formula to look for?

I look at whatever shows up on my terminal.   If it's like the caveats for `dupes/gnupg21`, I'll be really glad I saw it before I install anything.  If it says, e.g., "To use this you have to mess with launchd and a plist, then `killall` something", I will not install it.

**Comment by alexeymuranov** [comment]
> I look at whatever shows up on my terminal.

I mean, what if you will need to pass an option to `brew install`? Like `--with-python`, or something. Then you would need to know that you need to pass this option *before* running `brew info`, and to run `brew info --with-python`, or something like that.

**Comment by chdiza** [comment]
> I mean, what if you will need to pass an option to brew install? Like --with-python, or something. Then you would need to know that you need to pass this option before running brew info, and to run brew info --with-python, or something like that.

I agree that this is a problem.  My point is simply that  "don't have `brew info` print any caveats AT ALL if the formula is uninstalled" is undesirable behavior, for reasons I outlined.

When it comes to which options to pass, and whether they're needed, I have never trusted `brew info` and always go straight to `brew edit` or `brew cat`.

**Comment by apjanke** [comment]
Yeah, I'd like to be able to see the caveats before installing, too. Though it might be nice to hide caveats that are known to not be relevant for a particular installation. Which suggests "show all caveats for uninstalled formula, and hide known irrelevant ones for your particular install". But then you're in the situation of getting *less* info about an installed formula. 

I don't know what the Right Thing is to do here, but I want to voice a -1 on possible "hide caveats until installed" behavior.

**Comment by alexeymuranov** [comment]
> But then you're in the situation of getting *less* info about an installed formula.

You are always getting less info than what you might possibly get otherwise :)

**Comment by mikemcquaid** [comment]
I agree that what you see when you run `brew info` should match what you saw when you installed it. I'd review a PR that did that.
