### ISSUE TITLE
Unable to compile Python 2.7.10 with 10.11 SDK/CLT

### ISSUE THREAD

**Issue by johnwchadwick** [Homebrew/homebrew#40866]
Since installing 10.11, Python can't seem to compile anymore.
```
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:7:15: error: expected ';' after @class
@class NSArray<ObjectType>;
```
A [chrome issue](https://code.google.com/p/chromium/issues/detail?id=499448) suggests that it may have to do with some Clang features that haven't been open sourced and I guess therefore not in the CLT release of Clang.

Full logs: https://gist.github.com/anonymous/ea54a604214c8da4f10c
(re: Doctor output, I installed that Python framework afterwards. I don't think that was there before this log was made.)

**Comment by johnwchadwick** [comment]
Hmmm.. Maybe I needed to xcode-select the beta xcode. I'm closing now until I can confirm this isn't the case.

**Comment by DomT4** [comment]
Yeah, you'll need to switch over to the `7.0` Beta Xcode on 10.11 - The `6.x.x` branch of Xcode is unsupported on 10.11.

**Comment by johnwchadwick** [comment]
Yeah, this was my fault. I only realized earlier today that it wasn't on the new version because I hadn't used an XCode beta in a while and it didn't hit me the path to 7.0 was different. Suddenly the `brew doctor` output made sense and now things are working. Sorry! Hopefully this will help someone Googling around.

**Comment by fengminqiang** [comment]
thx!!!! i have same issue trying to install OpenCV3.0 in OS X 10.11, i should upgrade my Xcode .
