### ISSUE TITLE
SHA256 All The Things

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew#40877]
```
#!/bin/sh
# Change every formula's SHA1 to a SHA256.

HOMEBREW_PREFIX=$(brew --prefix)
cd $HOMEBREW_PREFIX/Library/Formula
FORMULAE=$(grep "^  sha1 " -rl . | sed -e 's/\.\///' -e 's/\.rb$//')

for FORMULA in $FORMULAE
do
	echo "Fetching and SHA256ing $FORMULA"
	if brew fetch $FORMULA &>/dev/null
	then
		SHA256=$(brew fetch $FORMULA | grep SHA256 | sed -e 's/SHA256: //')
		sed -i.old -e "s/^  sha1 *[\"'][a-fA-F0-9]\{40\}[\"']/  sha256 "$SHA256"/" $FORMULA.rb
		rm $FORMULA.rb.old
		if !brew fetch $FORMULA &>/dev/null
		then
			echo "Error: SHA256ing $FORMULA failed, reverting"
			git checkout $FORMULA.rb
		fi
	else
		echo "Error: fetching $FORMULA failed, skipping"
	fi
done
```

We've been having a conversation about how hard we push SHA256 for a while - Particularly whether or not we accept PRs that *only* update to SHA256 or only update to SHA256 + some style fixes.

I mentioned it to Mike and Mike floated the idea of changing everything at once. If the script above looks extremely familiar - It's the script that was used before, just tweaked for SHA1/SHA256.

Essentially if we're :+1: on this:

* I'll create a branch at DomT4/Homebrew named `sha256`
* Script will run through and make changes. It'll be one big commit to avoid ruining our commit tree.
* I'll do another full manual `brew fetch -fs` on everything to double-check.
* I could theoretically set up a temporary Travis to also double-check everything.
* The whole branch gets merged into the core without becoming a PR and breaking the bot.
* Bottle SHA256's aren't updated until the bottles are actually regenerated when things are updated.
* The `audit` is changed so `sha256` is enforced on all PRs rather than just new ones.

CC @Homebrew/owners

**Comment by mikemcquaid** [comment]
I'm :+1: on this, seems like a good idea and strategy. I'm not bothered about code churn for only `sha256` lines and we did the same thing in the past with `md5`.

**Comment by bfontaine** [comment]
How would it work with sub-resources? FWIW I’ve a Ruby-only solution [here](https://github.com/bfontaine/homebrew-tools/blob/master/cmd/brew-fix.rb#L72) but it handles one formula at a time.

**Comment by vszakats** [comment]
Great proposal!

**Comment by xu-cheng** [comment]
Shall we remove the `require 'formula'` and fix style (using `brew style --fix`) for all formulae along with this change?

**Comment by mikemcquaid** [comment]
I'm ok with mass removal of `require 'formula'` as it won't show up in `git blame` and anything else that involves removing lines but `brew style --fix` may introduce issues and will make `git blame` pretty useless for those files.

**Comment by DomT4** [comment]
Would prefer to keep the changes relatively minimal. It tends to be hard to identify specific issues that crop up when a PR does a lot of changes, and there's always a few that crop up. Happy with removing `require "formula"`, updating the core `sha1` to `sha256` and hopefully doing the same for resources.

**Comment by mikemcquaid** [comment]
@DomT4 :+1:

**Comment by DomT4** [comment]
Planning to fiddle with the script a bit more to try and deal with resources at the same time, and removing the `require "formula"` line. After that I'll press ahead with this since there seem to be no objections to the idea.

**Comment by tseemann** [comment]
What about adding an empty stub for ```desc "xxxx"```` too?

**Comment by mikemcquaid** [comment]
We already mass imported `desc`s

**Comment by nijikon** [comment]
:+1:

**Comment by DomT4** [comment]
This is likely to finally see action at some point over the weekend. Just finishing up an assignment today and then I'll have some free time again.

**Comment by tseemann** [comment]
@DomT4 Good luck! May Murphy be asleep when you attempt it.

**Comment by apjanke** [comment]
:+1:

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew/commit/8ba134eda537d2cee7daa7ebdd9f728389d9c53e.
