### ISSUE TITLE
Edge case with HTTP servers failing to respond to HEAD requests

### ISSUE THREAD

**Issue by L2G** [Homebrew/homebrew#40897]
Here is a headache I've just discovered: when an HTTP server does not respond to HEAD requests correctly, Homebrew will give up on a download, even if the URL would otherwise allow for a successful download.

Here are the details of the particular case I discovered:

* The `pipebench` formula points to http://www.habets.pp.se/synscan/files/pipebench-0.40.tar.gz for a download.
* Homebrew starts its download attempt by calling `curl -I -L http://www.habets.pp.se/synscan/files/pipebench-0.40.tar.gz`.
* The remote web server at www.habets.pp.se apparently does not respond to HEAD requests. If I run the above `curl` command manually from the command line, it hangs indefinitely. (Homebrew times out after a sensible duration.)
* If I try `curl -LO http://www.habets.pp.se/synscan/files/pipebench-0.40.tar.gz`, the tarball is downloaded immediately and without error.

**Comment by L2G** [comment]
If it would be helpful, I'll volunteer to contact the webmaster of www.habets.pp.se and see whether the issue can be corrected on the server side.

**Comment by L2G** [comment]
I'm also continuing to experiment to make sure this isn't really just a bug in curl 7.30, the version that comes with Mavericks.

**Comment by DomT4** [comment]
Fails here too on Yosemite, both with system `curl` and Homebrew'd `curl`. I did a `brew fetch` of about 300 formulae the other night without hitting this, and theoretically servers are *supposed* to answer HEAD requests. I'm more inclined to tag this as something upstream should fix than us, but short-term we could look at giving the formula its own download strategy.

**Comment by L2G** [comment]
I tried manually generating HTTP requests via good ol' telnet. It definitely looks like the remote web server is misbehaving.

(I've seen weirder things. Once I saw a noncompliant HTTP server return 404 for a HEAD request while returning 200 for a GET request to the exact same URL! Fortunately I haven't seen that happen with any Homebrew downloads, at least not yet.)

**Comment by L2G** [comment]
FYI, I've just sent a message via [the website's contact form](http://www.habets.pp.se/synscan/contact.php) reaching out to the webmaster.

**Comment by DomT4** [comment]
> Once I saw a noncompliant HTTP server return 404 for a HEAD request while returning 200 for a GET request to the exact same URL

The general rule for servers seems to be "If it's possible to set them up incorrectly, It'll be done" :wink:.

Thanks for whacking this upstream. If you don't get a response from them fairly quickly we can look at options for downloading the particular formula.

**Comment by vszakats** [comment]
Maybe fixed already?:
```
$ curl -I -L http://www.habets.pp.se/synscan/files/pipebench-0.40.tar.gz
HTTP/1.1 200 OK
Server: Apache/2.2.15 (CentOS)
Content-Type: application/x-gzip
Content-Encoding: x-gzip
Date: Sat, 20 Jun 2015 13:12:22 GMT
Content-Language: sv
Accept-Ranges: bytes
ETag: "315ad0-2d16-4546ec5a67980"
Connection: Keep-Alive
Last-Modified: Thu, 14 Aug 2008 17:24:06 GMT
Content-Length: 11542
```
```
$ curl --version
curl 7.37.1 (x86_64-apple-darwin14.0) libcurl/7.37.1 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IPv6 Largefile NTLM NTLM_WB SSL libz 
```

(also tested OK with curl 7.31.0 and 7.19.1, though these were run on Windows)

**Comment by L2G** [comment]
Hmmm. I'm still not getting any response.

@vszakats: What do you get with `curl -I -L http://www.habets.pp.se/synscan/files/pipebench-0.40.tar.gz -v`?

**Comment by DomT4** [comment]
It's still ignoring my HEAD request here as well.

**Comment by L2G** [comment]
@DomT4 Are you still on Mavericks like me?

**Comment by DomT4** [comment]
10.10.4

**Comment by L2G** [comment]
Hmm, then that's not it.

**Comment by vszakats** [comment]
@L2G Here are the results:
```
$ curl -I -L http://www.habets.pp.se/synscan/files/pipebench-0.40.tar.gz -v
* Hostname was NOT found in DNS cache
*   Trying 193.221.119.75...
* Connected to www.habets.pp.se (193.221.119.75) port 80 (#0)
> HEAD /synscan/files/pipebench-0.40.tar.gz HTTP/1.1
> User-Agent: curl/7.37.1
> Host: www.habets.pp.se
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
* Server Apache/2.2.15 (CentOS) is not blacklisted
< Server: Apache/2.2.15 (CentOS)
Server: Apache/2.2.15 (CentOS)
< Content-Type: application/x-gzip
Content-Type: application/x-gzip
< Content-Encoding: x-gzip
Content-Encoding: x-gzip
< Date: Sun, 21 Jun 2015 00:20:19 GMT
Date: Sun, 21 Jun 2015 00:20:19 GMT
< Content-Language: sv
Content-Language: sv
< Accept-Ranges: bytes
Accept-Ranges: bytes
< ETag: "315ad0-2d16-4546ec5a67980"
ETag: "315ad0-2d16-4546ec5a67980"
< Connection: Keep-Alive
Connection: Keep-Alive
< Last-Modified: Thu, 14 Aug 2008 17:24:06 GMT
Last-Modified: Thu, 14 Aug 2008 17:24:06 GMT
< Content-Length: 11542
Content-Length: 11542

< 
* Connection #0 to host www.habets.pp.se left intact
```

[ Above tests from continental Europe, but it tested the same from Dublin, Ireland / Linux. Strange. Maybe proxy or ISP related? ]

**Comment by L2G** [comment]
"ISP related" was going to be my next guess; I'm on Verizon FiOS (which is known to do pathological things like NXDOMAIN hijacking).

```
$ curl -I -L http://www.habets.pp.se/synscan/files/pipebench-0.40.tar.gz -v
* Adding handle: conn: 0x7fcfe1004000
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fcfe1004000) send_pipe: 1, recv_pipe: 0
* About to connect() to www.habets.pp.se port 80 (#0)
*   Trying 193.221.119.75...
* Connected to www.habets.pp.se (193.221.119.75) port 80 (#0)
> HEAD /synscan/files/pipebench-0.40.tar.gz HTTP/1.1
> User-Agent: curl/7.30.0
> Host: www.habets.pp.se
> Accept: */*
>

............hang.............
```

**Comment by DomT4** [comment]
Somewhat oddly. Downloading:

`http://www.habets.pp.se/synscan/files/pipebench-0.40.tar.gz` in Chrome (Or Opera) gets me the `sha256` of
```
552a166c9d06f3e5d71264551a8300bb7a6e13b3ad1df632695240cf07667ae5
```

Downloading it via `curl` or `wget` gets me
```
ca764003446222ad9dbd33bbc7d94cdb96fa72608705299b6cc8734cd3562211
```

Every time.

**Comment by guoxiao** [comment]
@DomT4 Same here.
I found the file downloaded with browser is actually a tar file without gzip compress, while the file downloaded with curl is a tar file with gzip compressed.

**Comment by DomT4** [comment]
Nice spot. From the browser:

```
file ~/Downloads/pipebench-0.40.tar.gz
~/Downloads/pipebench-0.40.tar.gz: POSIX tar archive (GNU)
```

From `cURL`:

```
file ~/Downloads/pipebench-0.40.tar.gz
~/Downloads/pipebench-0.40.tar.gz: gzip compressed data, from Unix, last modified: Sun Apr 20 17:51:11 2003
```

**Comment by DomT4** [comment]
Moved the link here to Debian's mirror until we get a response from upstream about the unusual server behaviour. https://github.com/Homebrew/homebrew/commit/9c1d2935a838b300b44baae3a4fd7ebe5bd57ea8

**Comment by DomT4** [comment]
Going to close this out for now. Let's handle these on a case-by-case basis; A few of the maintainers have ran very broad `brew fetch`s lately without issue, so hopefully pipebench's server was just particularly out of whack.
