### ISSUE TITLE
gcsfuse 0.2.0

### ISSUE THREAD

**Issue by jacobsa** [Homebrew/homebrew#40902]
I filed Homebrew/homebrew-fuse#6 for this, but maybe no one is watching that project as attentively as this one? Could someone with permissions take a look?

**Comment by DomT4** [comment]
Sorry about that. Only so many eyes to go around a large number of PRs/Commits/Issues etc :smile_cat:. I've restarted the Travis build over there.

**Comment by jacobsa** [comment]
No worries. I had just gotten used to very quick responses on this project (good job!), so wasn't sure if that one was being watched.
