### ISSUE TITLE
upgrading ffmpeg didn't preserve --with-fdk-aac

### ISSUE THREAD

**Issue by AlexKucera** [Homebrew/homebrew#40919]
Whenever I am running brew upgrade brew reminds me that `"FFmpeg has been built without libfaac for licensing reasons;"`, which is nice I guess, only I am building with `--with-fdk-aac`.

Why can brew not rebuild the binary the same way I had it set up in the first place? Why do I always have to go in and manually trigger a `brew reinstall ffmpeg --with-fdk-aac`?

**Comment by bfontaine** [comment]
`--with-fdk-aac` doesn’t build FFmpeg with `libfaac`. If you want faac support, use `--with-faac`. The option you’re using, `--with-fdk-aac`, enables the Fraunhofer FDK AAC library.

You can use `brew options ffmpeg` to list all the options:

```
$ brew options ffmpeg
--with-faac
	Build with faac support
--with-fdk-aac
	Enable the Fraunhofer FDK AAC library
(…)
```

**Comment by AlexKucera** [comment]
I think you misunderstood me bfontaine. I usually build ffmpeg with FDK ACC. Still on upgrading via `brew upgrade` I get a new build that is built without FDK AAC, but the warning about `libfaac`.

Why can't `brew upgrade` not respect the build config I already have on my system when upgrading? Why do I have to run `brew reinstall ffmpeg --with-fdk-aac` after every `brew upgrade`?

**Comment by bfontaine** [comment]
`brew upgrade` reuses the option you used on the preceding `brew install`. How do you see that the new build is without FDK AAC?

**Comment by AlexKucera** [comment]
When I check with `brew info ffmpeg` `fdk-aac` doesn't have a green checkmark, but a red cross.

**Comment by jacknagel** [comment]
Can you please do the following:

```
brew rm ffmpeg --force
cd $(brew --repository)
git checkout 109f88e -- Library/Formula/ffmpeg.rb
brew install ffmpeg --with-fdk-aac
git checkout master -- Library/Formula/ffmpeg.rb
brew upgrade ffmpeg
```

And then post the output of `brew info ffmpeg`? Just ignore anything the caveats tells you for now.

**Comment by AlexKucera** [comment]
Hi Jack,
that worked. Upgrading now preserves the `--with-fdk-aac`option. Was it a bug or something on my end like not installing with FDK AAC on my very first install?

**Comment by jacknagel** [comment]
Not sure, but probably something on your end. Let us know if you run into further trouble.
