### ISSUE TITLE
brew doctor hangs on El Capitan (OSX 10.11)

### ISSUE THREAD

**Issue by victorhooi** [Homebrew/homebrew#40918]
I've installed OSX 10.11 (El Capitan - Beta 1 - Build 15A178w).

I've installed Homebrew, which appeared to install successfully.

However, when I go to run `brew doctor`, it appears to hang indefinitely.

Adding the `-v` flag only seems to add printing the version number:

```
$ brew -v doctor
Homebrew 0.9.5
```

I do note in the OSX Terminal title-bar, it says `~ -- mdfind < ruby -W0 /usr/local/Library/brew.rb -v doctor`

Any thoughts on how to diagnose what's going on?

**Comment by jacknagel** [comment]
Homebrew uses mdfind (spotlight) to locate XQuartz, is it possible that spotlight is hanging while indexing? Can you try disabling spotlight and see if that changes things?

**Comment by victorhooi** [comment]
Yes, the issue seemed to be with Spotlight - I tried finding a file (e.g. TextEdit) in Spotlight, no results.

However, after doing a reboot (which actually involved a hard reboot - the Restart command seemed to hang at a black screen), Spotlight seemed to work, and `brew doctor` did as well.
