### ISSUE TITLE
Error installing vim 7.4 due to Clang not working as the gcc compiler

### ISSUE THREAD

**Issue by weixie4** [Homebrew/homebrew#40910]
$ brew install vim
==> Downloading https://mirrors.kernel.org/debian/pool/main/v/vim/vim_7.4.712.orig.tar.gz
Already downloaded: /Library/Caches/Homebrew/vim-7.4.712.tar.gz
==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/7.4.712/share/man --enable-multibyte --with-tlib=ncurses --enable-cscope --with-features=hu
checking for gcc... /usr/bin/clang
checking whether the C compiler works... no
configure: error: in `/private/tmp/vim20150620-57948-pwdh87/vim-7.4.712/src':
configure: error: C compiler cannot create executables
See `config.log' for more details

Can I ask Homebrew to use GNU c++ compiler instead of Clang? I guess that may solve the problem. If not, how can I make my Clang work?

FYI:
$ brew gist-logs emacs
returned
 https://gist.github.com/anonymous/f7509c05e12b41d18c65

**Comment by jacknagel** [comment]
You have a mismatch between CLT and Xcode versions; this can cause problems. Please update Xcode to the latest version (6.3.2).

Additionally, please run `brew install vim --debug`, and when the build fails, choose the "shell" option from the interactive menu. Then copy the file src/auto/config.log and post it in a gist.

**Comment by cohix** [comment]
I am able to install vim, it's when I attempt `brew install macvim` that the above error is thrown for me. It seems to happen when one of the deps (cscope) is built.

**Comment by jacknagel** [comment]
Closing due to no response.
