### ISSUE TITLE
HTTPS to HTTP redirect in `pango` formula

### ISSUE THREAD

**Issue by magicgoose** [Homebrew/homebrew#40915]
When trying to install `pango` (required by `gtk+`):

    ==> Installing gtk+ dependency: pango
    ==> Downloading https://download.gnome.org/sources/pango/1.36/pango-1.36.8.tar.xz
    ==> Downloading from: http://artfiles.org/gnome.org/sources/pango/1.36/pango-1.36.8.tar.xz
    Error: HTTPS to HTTP redirect detected & HOMEBREW_NO_INSECURE_REDIRECT is set.

Is it possible to download it from somewhere else, using a secure connection?

**Comment by bfontaine** [comment]
This should work:

```
curl -sL https://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.gnome.org/sources/pango/1.36/pango-1.36.8.tar.xz > /Library/Caches/Homebrew/pango-1.36.8.tar.xz
```

We should check the redirections and choose the HTTPS targets before the HTTP ones.

**Comment by magicgoose** [comment]
Is there a way to do this automatically for all archives from gnome.org (and other offending sites)? Or this exactly what Homebrew will do in a future version? :)

**Comment by bfontaine** [comment]
I’m working on a pull-request ;)

**Comment by DomT4** [comment]
> Or this exactly what Homebrew will do in a future version? :)

Eventually everything that has a secure mirror but an insecure url is likely to automatically fallback when requested by the user, but that's not something we can rush for several reasons. But it is the long-term hope & plan :)

**Comment by DomT4** [comment]
Closing as a known issue. For now you can prevent all HTTPS => HTTP redirects by setting the `HOMEBREW_NO_INSECURE_REDIRECT` variable. Note doing so will prevent Sourceforge downloads from source.

Longer term there will be support for secure mirror fallback.
