### ISSUE TITLE
logrotate formula permissions issue

### ISSUE THREAD

**Issue by bostonmacosx** [Homebrew/homebrew#40924]
The forumula is set up for a per user run. When you put it in LauncAgents that is the reason. 

Since the /usr/local/ is owned by the user who installed homebrew if you decide to make a LaunchDaemon out of the plist provided it will fail due to being run as root and the ownership of the conf file and status file being the local user and not root. 

Ideally the logrotate should not be run as root since the postscript run could do serious damage to the computer since any command will be run as root. 

The solution to this is to add the UserName directive to the plist and install it in LaunchDaemons so that the logrotate can run from the launchd(root) as a local user. 

The other issue is that the PID for nginx is owned by root. So you would then have to run the postscript with "SUDO" so that you can bump the nginx server....this would require the UserName account to have sudo without password privileges..

Any input on this would be appreciated. I think I've nailed down the slight installation change but would love to hear from the maintainer.  Thanks

**Comment by jacknagel** [comment]
We don't really have package maintainers. Can you submit a pull request with your suggested changes?

**Comment by DomT4** [comment]
PR welcome on this, Thanks!
