### ISSUE TITLE
SHA256 mismatch installing ocaml-biniou-1.0.5.zip via homebrew

### ISSUE THREAD

**Issue by EdGrimley** [Homebrew/homebrew#40928]
MacOS 10.10.3 
$ brew --version
0.9.5

$ brew install liquidsoap
==> Installing liquidsoap from drfill/homebrew-liquidsoap
==> Installing dependencies for drfill/liquidsoap/liquidsoap: ocaml-biniou, ocaml-cppo, ocaml-yojson, libogg
==> Installing drfill/liquidsoap/liquidsoap dependency: ocaml-biniou
==> Downloading https://github.com/mjambon/biniou/archive/v1.0.5.zip
==> Downloading from https://codeload.github.com/mjambon/biniou/zip/v1.0.5
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: b94c57abc68c7ed8e7ef3bde04df0101468aaceb7e0dfc2ce0cb84b0ba2be35a
Actual: 07f0493d7e2bc5142f9b8208efdf8d0974347ba43ca84fcf19feb9a8948d07bc
Archive: /Library/Caches/Homebrew/ocaml-biniou-1.0.5.zip
To retry an incomplete download, remove the file above.

**Comment by DomT4** [comment]
You'll need to report this at https://github.com/drfill/homebrew-liquidsoap - We don't have control over individual user taps, Sorry!
