### ISSUE TITLE
logstash 1.5.0 works for a while and then shuts down

### ISSUE THREAD

**Issue by Drewshg312** [Homebrew/homebrew#40931]
After I upgraded to logstash 1.5.0 getting strange behavior of this program.
Whenever I run it with next command:

     $ logstash agent -f /usr/local/etc/logstash/conf.d/logstash.conf

It works for a while and then stops saying `"Logstash shutdown completed"`.
Example:

     .....
     ......
      "@version" => "1",
    "@timestamp" => "2015-06-20T21:04:09.087Z",
          "type" => "SuricataIDPS",
          "host" => "drew-sh.server",
          "path" => "/var/log/suricata/eve.json",
         "geoip" => {
                      "ip" => "209.52.144.104",
           "country_code2" => "CA",
           "country_code3" => "CAN",
            "country_name" => "Canada",
          "continent_code" => "NA",
             "region_name" => "BC",
               "city_name" => "Vancouver",
                "latitude" => 49.25,
               "longitude" => -123.13329999999999,
                "timezone" => "America/Vancouver",
        "real_region_name" => "British Columbia",
                "location" => [
            [0] -123.13329999999999,
            [1] 49.25
        ],
             "coordinates" => [
            [0] -123.13329999999999,
            [1] 49.25
        ]
      }
    }
    Logstash shutdown completed

Why? What am I doing wrong?

**Comment by jacknagel** [comment]
This seems like a general usage question that would be more appropriate for StackOverflow or a logstash-specific forum. We don't really provide that type of support here, since we are not experts on all of the software that we package.

**Comment by Drewshg312** [comment]
I know but before I've upgraded it was ok so I assumed someone can know what kinds of changes could cause this and ask maybe someone else had the same problem

**Comment by kkirsche** [comment]
@Drewshg312 logstash 1.5.0 is a major change to the app — Since version 1.5.0 beta1 (and current master) of Logstash, all plugins have been separated into their own repositories under the logstash-plugins github organization. Each plugin is now a self-contained Ruby gem which gets published to RubyGems.org. This is just part of it but I'd assume it's due to these major changes you may be hitting issues

**Comment by Drewshg312** [comment]
well I've completely deleted logstash and reinstalled from scratch 

    $ brew rm logstash
    $ brew install logstash

and having same issue (((
Here is my **/usr/local/etc/logstash/conf.d/logstash.conf**:
    
    input {
      file {
        path => ["/var/log/suricata/eve.json"]
        sincedb_path => ["/var/lib/logstash/"]
        codec =>   json
        type => "SuricataIDPS"
        start_position => "beginning"
      }
    
    }
    
    filter {
      if [type] == "SuricataIDPS" {
        date {
          match => [ "timestamp", "ISO8601" ]
        }
        ruby {
          code => "if event['event_type'] == 'fileinfo'; event['fileinfo']['type']=event['fileinfo']['magic'].to_s.split(',')[0]; end;"
        }
      }
    
      if [src_ip]  {
        geoip {
          source => "src_ip"
          target => "geoip"
          #database => "/usr/local/opt/logstash/libexec/vendor/geoip/GeoLiteCity.dat"
          add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
          add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}"  ]
        }
        mutate {
          convert => [ "[geoip][coordinates]", "float" ]
        }
        if ![geoip.ip] {
          if [dest_ip]  {
            geoip {
              source => "dest_ip"
              target => "geoip"
              #database => "/usr/local/opt/logstash/libexec/vendor/geoip/GeoLiteCity.dat"
              add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
              add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}"  ]
            }
            mutate {
              convert => [ "[geoip][coordinates]", "float" ]
            }
          }
        }
      }
    }
    
    output {
      elasticsearch {
        host => localhost
        protocol => http
      }
      stdout {
          codec => rubydebug
       }
    }

**Comment by kkirsche** [comment]
Issues with logstash configs would be best to ask on StackOverflow or Logstash's issue tracker not here as this is homebrew and your question no longer relates to homebrew itself, but behavior of a third party product

**Comment by Drewshg312** [comment]
Ok(( I actually found there are a lot of smart guys here who helped me before even with such a questions.. Anyways thank you. Any suggestion would be appreciated ;)

**Comment by DomT4** [comment]
Closing here. There's not much we can do without solid information this is an exclusive Homebrew problem, and general usage questions are best filed with people who have more intimate knowledge of the software involved. Feel free to ping one of us if you discover the behaviour only exists in Homebrew's packaging.

Thanks for opening the Issue and letting us know of potential problems.
