### ISSUE TITLE
brew install gcc doesn't use the yosemite bottle

### ISSUE THREAD

**Issue by cartazio** [Homebrew/homebrew#40934]
i'm not sure why this is happening, and would appreciate some pointers on how i can get it to use the bottle rather than doing a bootstrap build :)

**Comment by DomT4** [comment]
If you don't have the CLT installed, You can't use the bottle. Notes [here](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gcc.rb#L70-L74). Install the CLT and you can :).

**Comment by cartazio** [comment]
weird.... cause i totally have them installed, clang and everything, but lo and behold doing xcode-select --install does what you say.

**Comment by DomT4** [comment]
`brew config` will confirm if the CLT are installed, and what version they are. Can you use the bottle now?

**Comment by cartazio** [comment]
yup, indeed!
huh, i did brew doctor and it didn't show anything :)

**Comment by cartazio** [comment]
many thanks

**Comment by DomT4** [comment]
You want `brew config` rather than `brew doctor` for the configuration information. We only flash stuff on the `doctor` that's potentially problematic.

You usually only need either Xcode or the CLT to use Homebrew, which is why we don't flag not having both installed, but the `gcc` bottles are somewhat special in requiring both.

Glad it's working as desired now!

**Comment by cartazio** [comment]
possibly related question while we're talking, when i run `brew config`
i get

```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 8da6986730e06b51a9686afa2ad9eeb241f8708a
Last commit: 25 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit haswell
OS X: 10.10.3-x86_64
Xcode: 6.3.2
CLT: 6.3.2.0.1.1431401888
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: N/A
```
now, i know /usr/bin/javac is in my path, so why can't it pick that up? (not that i'm using java for anything, but i'm curious)

**Comment by DomT4** [comment]
[This](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/config.rb#L122-L131) is our detection code.

Essentially if `which java` doesn't show anything we presume it doesn't exist, and if `which java` does show something but `/usr/libexec/java_home --failfast &>/dev/null` doesn't exit cleanly we presume it isn't usable.

**Comment by cartazio** [comment]
gotcha, i just needed to download a jdk, woops! 
again, many thanks and have a good evening
