### ISSUE TITLE
Error: parent directory is world writable but not sticky

### ISSUE THREAD

**Issue by fengfangqian** [Homebrew/homebrew#40941]
when i install gradle  
==> Downloading https://downloads.gradle.org/distributions/gradle-2.4-bin.zip
Already downloaded: /Library/Caches/Homebrew/gradle-2.4.zip
Error: parent directory is world writable but not sticky
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:483:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:184:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:166:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `install'
/usr/local/Library/brew.rb:140:in `<main>'

**Comment by DomT4** [comment]
Run `Repair Disk Permissions` in Disk Utility. `brew doctor` will warn you about this.
