### ISSUE TITLE
Cannot install Putty

### ISSUE THREAD

**Issue by josuelopes** [Homebrew/homebrew#40951]
After installing Putty successfully the day before, after making brew doctor and brew update, putty stopped working. After that I tried to reinstall which lead me to this:
***brew install putty --with-gtk+
==> Downloading https://the.earth.li/~sgtatham/putty/0.64/putty-0.64.tar.gz
######################################################################## 100,0%
==> ./configure --prefix=/usr/local/Cellar/putty/0.64 --disable-silent-rules --d
==> make VER=-DRELEASE=0.64
1 error generated.
make[1]: *** [unix/gtkfont.o] Error 1
1 error generated.
make[1]: *** [unix/gtkwin.o] Error 1
make: *** [all] Error 2

here is the gist:
https://gist.github.com/c95b121dda55e59161fb

Thank you for your time

**Comment by DomT4** [comment]
CC @tschoonj - Any way we can patch this or does the option need to go?

**Comment by josuelopes** [comment]
What are my options? Instead of X11 what should I choose that works with putty?

**Comment by tschoonj** [comment]
Had a look at the code and unfortunately the X11 code cannot be removed from the source. Will file a PR to remove the gtk+ option.

I recommend you look into alternative SFTP/SCP clients like [cyberduck](https://cyberduck.io)
