### ISSUE TITLE
brew link does not work on 10.11

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew#40956]
On all formulaes. I need to chown brew binary to root and run it with sudo. 
Also, setuid is not working, only sudo.
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Operation not permitted - (../Cellar/pth/2.0.7/bin/pth-config, /usr/local/bin/pth-config)
```

**Comment by DomT4** [comment]
Does ```sudo chown -R `whoami` /usr/local``` resolve the issue at all?

**Comment by yurikoles** [comment]
No.

**Comment by DomT4** [comment]
What does `ls -lh /usr/local` and `ls -lh /usr/` pump out?

**Comment by yurikoles** [comment]
https://gist.github.com/yurikoles/786c0004d7b4821b648a

**Comment by DomT4** [comment]
Are you an admin user or a normal user?

**Comment by yurikoles** [comment]
admin

**Comment by DomT4** [comment]
Try ```sudo chown -R `whoami`:admin /usr/local```. That's what our `Install` script on `brew.sh` enforces. I'm not quite sure why your entire `/usr/local` has ended up as `staff` if you're an Admin user. `staff` users are limited in various ways.

**Comment by yurikoles** [comment]
Same issue.

**Comment by mikemcquaid** [comment]
Are you on 10.11?

**Comment by mikemcquaid** [comment]
This this a clean install or upgrade of `10.11`? If an upgrade: did you have Homebrew installed before? Have you ever manually removed the `/usr/local` directory?

Please provide more information in your replies. When you say `same issue` do you mean the output is identical to the gist above or your initial comment or both?

**Comment by yurikoles** [comment]
This is a clean install of 10.11, but I have saved /usr/local and /Users. Same problem was with upgrade. Actually, I did clean install because of that. 
Example of clean install and `brew install coreutils`: https://gist.github.com/yurikoles/82a20783e016c2aa0432
Log of install of xz which is dependency of coreutils: https://gist.github.com/anonymous/51dd01ad8b3f38e1bf00
As you can see, there is a problem with ln.

**Comment by mikemcquaid** [comment]
A clean install works fine, I've set up multiple myself and `brew link` works ok. I suspect it's because you "saved `/usr/local`" that the persmissions haven't been restored fully.

**Comment by yurikoles** [comment]
>Example of clean install
I mean `sudo rm -rfv /usr/local` and then run as usual from brew.sh

**Comment by mikemcquaid** [comment]
Ok, that's a known issue described in #40837.

**Comment by yurikoles** [comment]
I have rootless=0

**Comment by mikemcquaid** [comment]
@yurikoles We won't be supporting that configuration.
