### ISSUE TITLE
404 when installing imagemagic

### ISSUE THREAD

**Issue by azhemoytuk** [Homebrew/homebrew#40969]
Getting 404 errors for current 6.9.1-5 version:

brew install imagemagick --with-fontconfig --with-ghostscript --with-libtiff
==> Downloading http://www.imagemagick.org/download/releases/ImageMagick-6.9.1-5.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading http://ftp.nluug.nl/ImageMagick/ImageMagick-6.9.1-5.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "imagemagick"
Download failed: http://ftp.nluug.nl/ImageMagick/ImageMagick-6.9.1-5.tar.xz

**Comment by DomT4** [comment]
It's outdated. Someone needs to bump it.

**Comment by mikemcquaid** [comment]
Seems they actually pulled that file too. Creating a PR.

**Comment by sivcek** [comment]
Download failed: http://ftp.nluug.nl/ImageMagick/ImageMagick-6.9.2-5.tar.xz

The current version now seems to be:

Download failed: http://ftp.nluug.nl/ImageMagick/ImageMagick-6.9.2-8.tar.xz

**Comment by DomT4** [comment]
@sivcek You need to `brew update` ^^

**Comment by sivcek** [comment]
@DomT4  I see. I was installing it within Julia using Homebrew.jl, which has not yet been updated it seems. I did not realize they do not tap the same resources.
