### ISSUE TITLE
Fail on installing mod_security

### ISSUE THREAD

**Issue by lmxxf** [Homebrew/homebrew#40977]
I have run "brew doctor"/"brew prune" and "brew update" for several times, but the error is still happening.

brew list:
apr		autoconf	curl		libtool		openssl		pkg-config	xz
apr-util	automake	httpd24		lua51		pcre		readline	zlib

error log:
localhost:~ lmxxf$ brew -v install mod_security
......
==> make
Making all in tools
make[1]: Nothing to be done for `all'.
Making all in apache2
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
/bin/sh ../libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I.  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2   -I/usr/include/apr-1 -I/usr/include/apr-1 -I -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2 -DWITH_LUA -I/usr/local/include -DWITH_PCRE_STUDY -DMODSEC_PCRE_MATCH_LIMIT=1500 -DMODSEC_PCRE_MATCH_LIMIT_RECURSION=1500  -DREQUEST_EARLY          -DWITH_REMOTE_RULES -I/usr/local/Cellar/pcre/8.37/include  -g -O2  -I/usr/include/apr-1  -c -o mod_security2_la-acmp.lo `test -f 'acmp.c' || echo './'`acmp.c
/bin/sh ../libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I.  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2   -I/usr/include/apr-1 -I/usr/include/apr-1 -I -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2 -DWITH_LUA -I/usr/local/include -DWITH_PCRE_STUDY -DMODSEC_PCRE_MATCH_LIMIT=1500 -DMODSEC_PCRE_MATCH_LIMIT_RECURSION=1500  -DREQUEST_EARLY          -DWITH_REMOTE_RULES -I/usr/local/Cellar/pcre/8.37/include  -g -O2  -I/usr/include/apr-1  -c -o mod_security2_la-apache2_config.lo `test -f 'apache2_config.c' || echo './'`apache2_config.c
/bin/sh ../libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I.  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2   -I/usr/include/apr-1 -I/usr/include/apr-1 -I -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2 -DWITH_LUA -I/usr/local/include -DWITH_PCRE_STUDY -DMODSEC_PCRE_MATCH_LIMIT=1500 -DMODSEC_PCRE_MATCH_LIMIT_RECURSION=1500  -DREQUEST_EARLY          -DWITH_REMOTE_RULES -I/usr/local/Cellar/pcre/8.37/include  -g -O2  -I/usr/include/apr-1  -c -o mod_security2_la-apache2_io.lo `test -f 'apache2_io.c' || echo './'`apache2_io.c
/bin/sh ../libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I.  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2   -I/usr/include/apr-1 -I/usr/include/apr-1 -I -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2 -DWITH_LUA -I/usr/local/include -DWITH_PCRE_STUDY -DMODSEC_PCRE_MATCH_LIMIT=1500 -DMODSEC_PCRE_MATCH_LIMIT_RECURSION=1500  -DREQUEST_EARLY          -DWITH_REMOTE_RULES -I/usr/local/Cellar/pcre/8.37/include  -g -O2  -I/usr/include/apr-1  -c -o mod_security2_la-apache2_util.lo `test -f 'apache2_util.c' || echo './'`apache2_util.c
libtool: compile:  clang -DHAVE_CONFIG_H -I. -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2 -I/usr/include/apr-1 -I/usr/include/apr-1 -I -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2 -DWITH_LUA -I/usr/local/include -DWITH_PCRE_STUDY -DMODSEC_PCRE_MATCH_LIMIT=1500 -DMODSEC_PCRE_MATCH_LIMIT_RECURSION=1500 -DREQUEST_EARLY -DWITH_REMOTE_RULES -I/usr/local/Cellar/pcre/8.37/include -g -O2 -I/usr/include/apr-1 -c acmp.c  -fno-common -DPIC -o .libs/mod_security2_la-acmp.o
libtool: compile:  clang -DHAVE_CONFIG_H -I. -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2 -I/usr/include/apr-1 -I/usr/include/apr-1 -I -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2 -DWITH_LUA -I/usr/local/include -DWITH_PCRE_STUDY -DMODSEC_PCRE_MATCH_LIMIT=1500 -DMODSEC_PCRE_MATCH_LIMIT_RECURSION=1500 -DREQUEST_EARLY -DWITH_REMOTE_RULES -I/usr/local/Cellar/pcre/8.37/include -g -O2 -I/usr/include/apr-1 -c apache2_config.c  -fno-common -DPIC -o .libs/mod_security2_la-apache2_config.o
libtool: compile:  clang -DHAVE_CONFIG_H -I. -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2 -I/usr/include/apr-1 -I/usr/include/apr-1 -I -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2 -DWITH_LUA -I/usr/local/include -DWITH_PCRE_STUDY -DMODSEC_PCRE_MATCH_LIMIT=1500 -DMODSEC_PCRE_MATCH_LIMIT_RECURSION=1500 -DREQUEST_EARLY -DWITH_REMOTE_RULES -I/usr/local/Cellar/pcre/8.37/include -g -O2 -I/usr/include/apr-1 -c apache2_io.c  -fno-common -DPIC -o .libs/mod_security2_la-apache2_io.o
libtool: compile:  clang -DHAVE_CONFIG_H -I. -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2 -I/usr/include/apr-1 -I/usr/include/apr-1 -I -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2 -DWITH_LUA -I/usr/local/include -DWITH_PCRE_STUDY -DMODSEC_PCRE_MATCH_LIMIT=1500 -DMODSEC_PCRE_MATCH_LIMIT_RECURSION=1500 -DREQUEST_EARLY -DWITH_REMOTE_RULES -I/usr/local/Cellar/pcre/8.37/include -g -O2 -I/usr/include/apr-1 -c apache2_util.c  -fno-common -DPIC -o .libs/mod_security2_la-apache2_util.o
apache2_io.c:15:10: fatal error: 'util_filter.h' file not found
#include <util_filter.h>
         ^
In file included from apache2_config.c:17:
In file included from ./modsecurity.h:40:
In file included from ./msc_util.h:29:
In file included from ./re.h:42:
./apache2.h:18:10: fatal error: 'http_core.h' file not found
#include "http_core.h"
         ^
1 error generated.
In file included from apache2_util.c:15:
In file included from ./modsecurity.h:40:
In file included from ./msc_util.h:29:
In file included from ./re.h:42:
./apache2.h:18:10: fatal error: 'http_core.h' file not found
#include "http_core.h"
         ^
1 error generated.
make[2]: *** [mod_security2_la-apache2_io.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
libtool: compile:  clang -DHAVE_CONFIG_H -I. -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2 -I/usr/include/apr-1 -I/usr/include/apr-1 -I -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2 -DWITH_LUA -I/usr/local/include -DWITH_PCRE_STUDY -DMODSEC_PCRE_MATCH_LIMIT=1500 -DMODSEC_PCRE_MATCH_LIMIT_RECURSION=1500 -DREQUEST_EARLY -DWITH_REMOTE_RULES -I/usr/local/Cellar/pcre/8.37/include -g -O2 -I/usr/include/apr-1 -c acmp.c -o mod_security2_la-acmp.o >/dev/null 2>&1
make[2]: *** [mod_security2_la-apache2_config.lo] Error 1
make[2]: *** [mod_security2_la-apache2_util.lo] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
==> Formula
Tap: homebrew/homebrew-apache
Path: /usr/local/Library/Taps/homebrew/homebrew-apache/mod_security.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 5345cee68a42bc013b2a1b0fbbed98282268e1f1
Last commit: 37 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit haswell
OS X: 10.10.3-x86_64
Xcode: 6.3.2
CLT: 6.3.2.0.1.1431401888
Clang: 6.1 build 602
X11: 2.7.6 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.8.0_45
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/pcre/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/autoconf/bin:/usr/local/opt/automake/bin:/usr/local/opt/libtool/bin:/usr/local/opt/pcre/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: homebrew/apache/mod_security 2.9.0 did not build
Logs:
     /Users/lmxxf/Library/Logs/Homebrew/mod_security/01.autogen.sh
     /Users/lmxxf/Library/Logs/Homebrew/mod_security/02.configure
     /Users/lmxxf/Library/Logs/Homebrew/mod_security/02.configure.cc
     /Users/lmxxf/Library/Logs/Homebrew/mod_security/03.make
     /Users/lmxxf/Library/Logs/Homebrew/mod_security/03.make.cc
     /Users/lmxxf/Library/Logs/Homebrew/mod_security/config.log

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-apache#81
