### ISSUE TITLE
Custom brew formula failing install

### ISSUE THREAD

**Issue by adammenges** [Homebrew/homebrew#40987]
I've got a simple Formula:

``` ruby 
require "formula"

class ARC < Formula
  url "https://***/adammenges/arc/raw/master/arc.zip"

  def install
    system "./install.sh"
    prefix.install "arc", "classification.py"
  end
end
```

But on trying a `brew install https://***/adammenges/arc/raw/master/formula.rb` I get the following:

``` bash
Error: formulae require at least a URL
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula.rb:125:in `determine_active_spec'
/usr/local/Library/Homebrew/formula.rb:106:in `initialize'
/usr/local/Library/Homebrew/formulary.rb:65:in `new'
/usr/local/Library/Homebrew/formulary.rb:65:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:177:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:140:in `<main>'
```

Not sure why, clearly I've given a url. I must be missing something else.

**Comment by jacknagel** [comment]
>brew install https://***/adammenges/arc/raw/master/formula.rb

Formula filenames must match the class name in the file. In this case, you need to name the file `ARC.rb` (or change the class name to `Arc` and the filename to `arc.rb`).

Under normal circumstances, there is a more revealing error, but in this case you've chosen the one value (`formula.rb`) that causes Homebrew to try to instantiate the Formula superclass.
