### ISSUE TITLE
Can't install Octave (Gnuplot fails)

### ISSUE THREAD

**Issue by jozilla** [Homebrew/homebrew#40999]
Error compiling Gnuplot (gcc = clang, maybe that's the issue?).
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/tmp/gnuplot20150623-7870-kfios4/gnuplot-5.0.0':
configure: error: C compiler cannot create executables

Full gist with log here: https://gist.github.com/anonymous/bf2121c388de8558026a

**Comment by jacknagel** [comment]
>/usr/local/Library/ENV/4.3/clang:320:in `exec': No such file or directory - /usr/local/Library/ENV/4.3/xcrun (Errno::ENOENT)

What does `cd $(brew --repository); git status` say? You probably need to do this:

```
cd $(brew --repository)
git fetch origin
git reset --hard origin/master
```

**Comment by jozilla** [comment]
Thanks! I tried this, but it still does not work:

brew install octave
==> Installing octave from homebrew/homebrew-science
==> Installing dependencies for homebrew/science/octave: gnuplot, tbb, su
==> Installing homebrew/science/octave dependency: gnuplot
==> Downloading https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.0/
Already downloaded: /Library/Caches/Homebrew/gnuplot-5.0.0.tar.gz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/gnuplot/5.0.0
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/tmp/gnuplot20150625-11979-1gtxmqa/gnuplot-5.0.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
/usr/local/Library/ENV/4.3/gcc-4.2:320:in `exec': No such file or directory - /usr/local/Library/ENV/4.3/xcrun (Errno::ENOENT)
	from /usr/local/Library/ENV/4.3/gcc-4.2:320:in `<main>'

READ THIS: https://git.io/brew-troubleshooting
