### ISSUE TITLE
mtr: unable to get raw sockets

### ISSUE THREAD

**Issue by peterjeliot** [Homebrew/homebrew#40992]
I'm experiencing the exact same problem as listed in #166. That is, even though mtr installs cleanly, running it always produces this line of text and nothing else:

    mtr: unable to get raw sockets

The workaround is as given in a comment there, with the version updated to 0.86:

    sudo chown root:wheel /usr/local/Cellar/mtr/0.86/sbin/mtr
    sudo chmod u+s /usr/local/Cellar/mtr/0.86/sbin/mtr

I'm using OSX 10.10.3, homebrew 0.9.5, and mtr 0.86.

**Comment by mikemcquaid** [comment]
You need to run it with `sudo`. We don't recommend setting anything `setuid` root as it's a fairly terrible security practice.

**Comment by peterjeliot** [comment]
Ah, upon reinstalling I see that there was indeed a message about needing `sudo`. Do you know why the old bug was closed with a seemingly-irrelevant patch?

A shame that `mtr` doesn't give a better error when run without `sudo`, but I suppose that's outside homebrew's control.

**Comment by mikemcquaid** [comment]
> Ah, upon reinstalling I see that there was indeed a message about needing sudo. Do you know why the old bug was closed with a seemingly-irrelevant patch?

Nope, I guess it was a mistake.

> A shame that mtr doesn't give a better error when run without sudo, but I suppose that's outside homebrew's control.

It is, yes. I'd suggest filing an issue there.

**Comment by yanokwa** [comment]
I'm on OS X 10.11.1 and running mtr 0.86. When I run `sudo mtr 8.8.8.8;` I'm getting `mtr: unable to get raw sockets.` Anyone else having this problem?
