### ISSUE TITLE
Upgrade to ZMQ to 4.1.2  breaks Salt stack

### ISSUE THREAD

**Issue by jozefmares** [Homebrew/homebrew#41000]
After recent upgrade to ZMQ 4.1.2 (see https://github.com/Homebrew/homebrew/commit/ac580d216e8fd721058d226bf32ae54c09e0e18f#Library/Formula/zeromq.rb) Salt stack is not working.

Salt fails on:
<code>
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: delilah.int.azoy.eu
[DEBUG   ] Configuration file path: /etc/salt/minion
[INFO    ] Setting up the Salt Minion "MINION_ID"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Attempting to authenticate with the Salt Master at SECRET_IP
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', MINION_ID', 'tcp://SECRET_IP:4506')
[INFO    ] The salt minion is shut down
[ERROR   ] global name 'zmq' is not defined
[WARNING ] ** Restarting minion **
[INFO    ] Sleeping random_reauth_delay of 9 seconds
Exception AttributeError: "'SREQ' object has no attribute 'poller'" in <bound method SREQ.__del__ of <salt.payload.SREQ object at 0x1046f6f10>> ignored
</code>

After downgrade to Zeromq 3.2 Salt still does not work. My guess is **pyzmq** is linked against older ZeroMQ.

Reproduce:
upgrade or install saltstack. Run sudo salt-minion.

Do not hesitate contact me for further questions.

**Comment by DomT4** [comment]
I bumped `saltstack` to a newer version, and updated the vendored `pyzmq`. Resolve anything?

**Comment by jozefmares** [comment]
@DomT4 Yes, works fine. Thank you very much.

**Comment by DomT4** [comment]
Great, Thanks for the quick feedback!
