### ISSUE TITLE
openconnect-gui available in MacPorts

### ISSUE THREAD

**Issue by bingh0** [Homebrew/homebrew#41002]
A port for openconnect-gui has been submitted to MacPorts.

http://lists.infradead.org/pipermail/openconnect-devel/2015-June/003019.html

**Comment by bfontaine** [comment]
What’s the issue here?

**Comment by bingh0** [comment]
Sorry, was wondering if there was interest in adding a recipe.

**Comment by DomT4** [comment]
It looks like it's just a Qt app over an existing `openconnect`, so I don't have any objection personally. Submit a PR for review, if you like.

**Comment by mikemcquaid** [comment]
Closing this issue; if you'd like to create a PR please do so.
