### ISSUE TITLE
matlab2tikz outdated

### ISSUE THREAD

**Issue by egeerardyn** [Homebrew/homebrew#41005]
I found out at https://github.com/Homebrew/homebrew/blob/master/Library/Formula/matlab2tikz.rb that there is a formula for `matlab2tikz`. Unfortunately, it seems to be outdated:

 - The latest release is 1.0.0 (in general, you can find or latest stable release in the `master` branch), 
 - The repository/website has since been moved to https://github.com/matlab2tikz/matlab2tikz/ .

I don't know how many of your users actually use homebrew to install `matlab2tikz`, nor if you have a more structured way to deal with dependencies from a git repo (e.g. as Arch Linux does in AUR). 

I just wanted to let you know that appropriate action should be taken for this formula (I trust you know better what action that is).

**Comment by mikemcquaid** [comment]
Could you try and open a pull request to update these things? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by egeerardyn** [comment]
I don't actually use HomeBrew (more of a MacPorts kind of guy, sorry), but I assume that I can just edit the relevant file and submit a pull request?

**Comment by mikemcquaid** [comment]
Yep, thanks.
