### ISSUE TITLE
"brew install vim --with-client-server" fails to build vim with +clientserver

### ISSUE THREAD

**Issue by fodier** [Homebrew/homebrew#41029]
```
$ brew info vim | head -n 7
vim: stable 7.4.712, HEAD
Vi "workalike" with many additional features
http://www.vim.org/
Conflicts with: ex-vi
/usr/local/Cellar/vim/7.4.712 (1643 files, 31M) *
  Built from source with: --with-client-server
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/vim.rb
```
```
$ $(brew --prefix)/bin/vim --version | grep clientserver
-clientserver    -hangul_input    +netbeans_intg   +title
```
[brew gist-logs vim](https://gist.github.com/anonymous/6525ee79c3eb7fde1fd8)

**Comment by tschoonj** [comment]
Interesting: the `--with-client-server` has been removed from the configure script. Did `vim` remove support for this feature?

**Comment by flori** [comment]
I think this is caused by the patch https://github.com/Homebrew/homebrew/commit/6a095cb863a7b2a7c01a81f24f5cffa11c035d1d.

Apparently the gdk/gdkx.h file is gone when gtk when compiled for Quartz.

The above fix was used to close issue https://github.com/Homebrew/homebrew/issues/40832. I want to have my trusty remote vim back, though. :sad:

**Comment by tschoonj** [comment]
@flori @fodier 

Ok, I found a way to fix this but it requires dropping the GUI option (due to gtk+ not working here). Would that be an acceptable solution?

**Comment by tschoonj** [comment]
actually the gtk+ option doesn't even work without X11 backend (gvim doesn't get built) so I will just file a PR that restores client-server support but removes all traces of gtk+

**Comment by tschoonj** [comment]
if at some point gui support is need then this can also be accomplished using motif or athena...

**Comment by fodier** [comment]
Thank you, your PR works for me.

**Comment by flori** [comment]
I can verify this, client-server works again. Thx!
