### ISSUE TITLE
jpeg-turbo v1.4.1 binary is broken due to a bug in nasm

### ISSUE THREAD

**Issue by xionglingfeng** [Homebrew/homebrew#41023]
When execute `brew install jpeg-turbo`, homebew automatically downloads a binary pre-built version of `jpeg-turbo 1.4.1`. This binary is built with `nasm 2.11.08` which has a known [bug](http://sourceforge.net/p/libjpeg-turbo/mailman/message/34219546/) make the library cannot pass test on latest Mac OS X (10.10.3).

A workaround for now is to build `jpeg-turbo` with a old version, such as `nasm 2.11.06`. Since `nasm` is only used in build time, not runtime, I think it is easy to do that.

**Comment by DomT4** [comment]
Same issue as in #39941 and #39939.

The solution from #39941 will need applying here as well.

**Comment by xionglingfeng** [comment]
Hi DomT4,
I read #39941, it seems that you remove the depend of `nasm` and force the formula to build `nasm 2.11.06` before the actual library. Why not just depend on `homebrew/version/nasm21106`?

**Comment by DomT4** [comment]
We don't permit mandatory cross-tap dependencies in the core. Given most users pour bottles rather than build from source, the extra `nasm` vendoring as a temporary measure is barely noticed.

**Comment by tseemann** [comment]
"Most users pour bottles" excludes the large user base of Linuxbrew.

**Comment by DomT4** [comment]
> "Most users pour bottles" excludes the large user base of Linuxbrew.

With respect, I pointed to the solution 20 hours ago - Anyone was free to submit a PR that mimicked that logic.

Fix in #41054.

**Comment by mikemcquaid** [comment]
> "Most users pour bottles" excludes the large user base of Linuxbrew.

@tseemann It's Linuxbrew's job to support Linuxbrew users, not Homebrew.

**Comment by tseemann** [comment]
@mikemcquaid I am stlll adjusting to the OSX/Linux schism that exists in Homebrew. I prefer to write defensively for both platforms under the Unix banner as much as possible. Formulae are a shared resource, and Linuxbrew users do put effort in making formulae work on OS X even when the simpler path would just to add `depends_on LinuxRequirement`.

**Comment by mikemcquaid** [comment]
> @mikemcquaid I am stlll adjusting to the OSX/Linux schism that exists in Homebrew. I prefer to write defensively for both platforms under the common Unix banner as much as possible. Formulae are a shared resource, and Linuxbrew users do put effort in making formulae work on OS X even when the simpler path would just to add depends_on LinuxRequirement.

Linuxbrew is a much, much smaller userbase than Homebrew and we can't and don't test things work there. I'm all for making lives easier for Linuxbrew but that needs to not make anything harder for Homebrew.
