### ISSUE TITLE
Ansible recipe relies on a version of paramiko that does not have ecdsa support

### ISSUE THREAD

**Issue by chamby** [Homebrew/homebrew#41047]
When Ansible is using paramiko it will be unable to SSH into a host using an ecdsa cipher. The paramiko resource should be updated to something more recent (https://pypi.python.org/pypi/paramiko/1.15.2) and the ecdsa library (https://pypi.python.org/pypi/ecdsa) should be added as a resource to satisfy paramiko.

**Comment by DomT4** [comment]
If you want to submit a PR to update the resources that'd be great, Thanks!

**Comment by chamby** [comment]
@DomT4 I'll try to setup a PR. This is my first time contributing to homebrew. When editing the formula, is there anything else I need to edit besides updating the URLs and SHAs to the new resources?

**Comment by DomT4** [comment]
@chamby Thanks! Should just be enough to update the URL and SHA256 to the new versions in this case.

**Comment by chamby** [comment]
PR at #41053

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew/commit/74d27c6671cc6d59cad610a5eeec311b985c39f5 :rocket:.
