### ISSUE TITLE
Docker-composer/Fig Hooks System OpenSSL

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew#41052]
From @torbjornvatn - https://github.com/Homebrew/homebrew/commit/0a6fca2edae95dd26447b61459086946d79f5e80#commitcomment-11847267:

When I install docker-compose 1.3.1 with this formula ```docker-compose --version```prints the following:
```bash
docker-compose version: 1.3.1
CPython version: 2.7.6
OpenSSL version: OpenSSL 0.9.8zd 8 Jan 2015
````
If I install it using the cURL command found [here](https://docs.docker.com/compose/install/) however, this is printed:
```bash
docker-compose version: 1.3.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1j 15 Oct 2014
```
The homebrew version results in this warning when run:
```
/usr/local/Cellar/fig/1.3.1/libexec/vendor/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: 
InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. 
For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

=======

From @DomT4 - This seems to happen because we use the system Python by default, and upstream determine the OpenSSL version by running `python -c "import ssl; print ssl.OPENSSL_VERSION"` which built against the system Python returns:

``` OpenSSL 0.9.8zf 19 Mar 2015 ```.

And Homebrew's Python returns:

``` OpenSSL 1.0.2c 12 Jun 2015 ```.

And docker-compose prints out those outputs depending on whether you build against the system Python or Homebrew's Python respectively (tested this). It doesn't change if you build against our OpenSSL but still the system Python.

Makes me wonder if this is a mis-detection, or whether it's actually using the system OpenSSL and if there's anything we can do about that.

CC @tdsmith

**Comment by tdsmith** [comment]
docker-compose is reporting the correct versions of the tools it is using; it uses the openssl against which python is built and doesn't link openssl directly. This may change in the future if it begins depending on pyopenssl, but it doesn't, yet.

I think this is correct behavior; the warning is annoying but not dangerous.

**Comment by tdsmith** [comment]
Closing as not a bug.

**Comment by DomT4** [comment]
Cool. Thanks for the quick explanation Tim :cocktail:. I tried to summarise what I thought it was doing, but I trust your judgement on Python stuff several billion times more than mine :wink:.

There's an ongoing discussion upstream about using `pyopenssl`, so there may be progress on that front.

**Comment by DomT4** [comment]
Whoops! It was still a "Close" button when I hit it :smile_cat:, Sorry about that.
