### ISSUE TITLE
unable to install pdsh, ld: library not found for -lhistory

### ISSUE THREAD

**Issue by ajft** [Homebrew/homebrew#41059]
As per
https://gist.github.com/anonymous/179e777d5a200c42fc8f

Installation fails with:
==> make install
ld: library not found for -lhistory

brew doctor reports nothing awry

**Comment by DomT4** [comment]
Works okay here. Try `brew update && brew reinstall readline` and then try again.

**Comment by ajft** [comment]
Dominyk,

That had no effect, however...

The output of "brew reinstall readline" ends in
> :
> Generally there are no consequences of this for you. If you build your
> own software and it requires this formula, you'll need to add to your
> build variables:
>
>    LDFLAGS:  -L/usr/local/opt/readline/lib
>    CPPFLAGS: -I/usr/local/opt/readline/include

Which got me searching around for *how* to pass the LDFLAGS and CPPFLAGS
in.  Unable to make that work through various exports and variable settings.

http://findingscience.com/r/os_x/2011/01/03/installing-r-on-os-x-with-readline.html
seemed similar enough, so I ran "brew edit pdsh" and added the readline
dependencies.  Am now able to install pdsh.

$ git diff pdsh.rb
diff --git a/Library/Formula/pdsh.rb b/Library/Formula/pdsh.rb
index e6dca56..0fd0977 100644
--- a/Library/Formula/pdsh.rb
+++ b/Library/Formula/pdsh.rb
@@ -6,6 +6,8 @@ class Pdsh < Formula
   url 'https://code.google.com/p/pdsh/', :tag => 'pdsh-2.31', :using =>
:git
   sha1 '03f1f82761162e5f0d382f4e586aae9fb0ef7ef9'

+  depends_on 'readline'
+
   head 'https://code.google.com/p/pdsh/', :using => :git

   option "without-dshgroups", "Compile without dshgroups which conflicts
with genders. The option should be specified to load genders module first
instead of dshgroups."
@@ -25,6 +27,9 @@ class Pdsh < Formula
     args << '--with-genders' if build.with? 'genders'
     args << ((build.without? "dshgroups") ? '--without-dshgroups' :
'--with-dshgroups')

+    ENV["CPPFLAGS"] = "-I#{Formula.factory('readline').include}"
+    ENV["LDFLAGS"] = "-L#{Formula.factory('readline').lib}"
+
     system "./configure", *args
     system "make install"
   end



On Thu, Jun 25, 2015 at 1:39 PM, Dominyk Tiller <notifications@github.com>
wrote:

> Works okay here. Try brew update && brew reinstall readline and then try
> again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Homebrew/homebrew/issues/41059#issuecomment-115091489>
> .
>



-- 
Adrian Tritschler
Melbourne, Australia

**Comment by DomT4** [comment]
Unless the build is running under `:std` for some reason, `superenv` should be passing those directories to the flags *already* so I'm not really sure why that would fix things.

> +  depends_on 'readline'

Why did you need to add a `readline` dependency? There should have already been one in the formula.

**Comment by ajft** [comment]
On Fri, Jun 26, 2015 at 11:20 AM, Dominyk Tiller <notifications@github.com>
wrote:

> Unless the build is running under :std for some reason, superenv should
> be passing those directories to the flags *already* so I'm not really
> sure why that would fix things.
>
>
>    - depends_on 'readline'
>
>  Why did you need to add a readline dependency? There should have already
> been one in the formula.
>
You're correct, there is one.  Didn't see it on my first reading.

-- 
Adrian Tritschler
Melbourne, Australia

**Comment by DomT4** [comment]
Alright. Since you've got it working now and I can't repro the issue on two unique machines I'm going to close here. Feel free to flag up a new Issue if you hit any further quirks.
