### ISSUE TITLE
vte cannot be built

### ISSUE THREAD

**Issue by paulhybryant** [Homebrew/homebrew#41058]
Error:

checking for VTE... configure: error: Package requirements (glib-2.0 >= 2.26.0 gobject-2.0 pango >= 1.22.0 gtk+-2.0 >= 2.20.0 gobject-2.0 gio-2.0 gio-unix-2.0 x11 cairo-xlib) were not met:

No package 'x11' found
No package 'cairo-xlib' found

I am not able to generate the gist-logs

brew gist-logs vte
Error: getaddrinfo: nodename nor servname provided, or not known
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1367:in `request'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:115:in `post'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:72:in `create_gist'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:24:in `gistify_logs'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:140:in `gist_logs'
/usr/local/Library/brew.rb:140:in `<main>'

**Comment by DomT4** [comment]
CC @tschoonj

**Comment by paulhybryant** [comment]
Did more digging. Seems cairo-xlib.pc is available but not symlinked.

Not sure about x11

**Comment by DomT4** [comment]
> Seems cairo-xlib.pc

There is no `cairo-xlib.pc` file unless you're about a week and half behind on `brew update`s. It's only generated when Cairo is built with X11 support, which we no longer do.

**Comment by DomT4** [comment]
I can't actually reproduce this, so I think you should be able to resolve it with `brew update && brew upgrade && brew install vte`.

**Comment by paulhybryant** [comment]
I still get the same error with brew update && brew upgrade && brew install vte

gits-logs is working now and logs are here

https://gist.github.com/95b7bd5ba9f05deef0a0

**Comment by paulhybryant** [comment]
To confirm yeah cairo-xlib.pc is gone after I tried reinstalling cairo.
But pkg-config from vte is still looking for cairo-xlib and x11. That doesn't look right.

**Comment by tschoonj** [comment]
Your gist-log shows that your gtk+ is still built with the X11 backend. This is causing your compilation issues.

I am not sure how this possible since you’ve already ran brew upgrade.

Try:

brew uninstall gtk+
brew install vte



Dr. Tom Schoonjans
Research Fellow

Bundesanstalt für Materialforschung und -prüfung (Federal Institute for Materials Research and Testing)
Richard-Willstätter-Strasse 11, 12489 Berlin
Germany

Telephone +49 (0) 30-8104-5612

Tom.Schoonjans@bam.de<mailto:Tom.Schoonjans@bam.de>
www.bam.de


On 25 Jun 2015, at 07:55, paulhybryant <notifications@github.com<mailto:notifications@github.com>> wrote:


To confirm yeah cairo-xlib.pc is gone after I tried reinstalling cairo.
But pkg-config from vte is still looking for cairo-xlib and x11. That doesn't look right.

**Comment by paulhybryant** [comment]
I found the following in configure.in

# We have a direct dependency on X11 on gdk-x11, see bug #613525
AC_MSG_CHECKING([for GDK target])
GDK_TARGET="$($PKG_CONFIG --variable target gdk-$GTK_API_VERSION)"
AC_MSG_RESULT([$GDK_TARGET])
case "$GDK_TARGET" in
  x11) PLATFORM_PKGS="x11 cairo-xlib" ;;
  *) PLATFORM_PKGS="" ;;
esac

VTE_PKGS="glib-2.0 >= $GLIB_REQUIRED gobject-2.0 pango >= $PANGO_REQUIRED gtk+-$GTK_API_VERSION >= $GTK_REQUIRED gobject-2.0 gio-2.0 gio-unix-2.0 $PLATFORM_PKGS"
PKG_CHECK_MODULES([VTE],[$VTE_PKGS])

and pkg-config --variable target gdk-2.0 did return x11 and cairo-xlib. 

So this is caused by an old version of gtk+.

It is fixed by reinstalling gtk+ and cairo. Something might have gone wrong when the packages are upgraded.

**Comment by DomT4** [comment]
There may have be some old linking there or something. You can remove old versions left in `brew` by doing `brew cleanup`.
