### ISSUE TITLE
openssl logjam

### ISSUE THREAD

**Issue by drpaneas** [Homebrew/homebrew#41050]
As you can see, I already have the latest openssl version provided by homebrew: 
`~~> brew upgrade openssl`
`Error: openssl 1.0.2 already installed`

which is: 
` ~~> /usr/local//Cellar/openssl/1.0.2/bin/openssl version`
`OpenSSL 1.0.2 22 Jan 2015`

this version is vulnerable against to [logjam](https://weakdh.org/). More specifically, the client accepts too short DH parameters (less than or equal to 512 bits key). The ciphers are:
`DHE-RSA-AES256-SHA`
`DHE-RSA-AES128-SH`

**Comment by DomT4** [comment]
We fixed our detection code to stop this happening. Not sure why it wouldn't have worked for you. Do:

``` brew update && brew rm openssl && brew install openssl```

Should end up with:

```
/usr/local/opt/openssl/bin/openssl version
OpenSSL 1.0.2c 12 Jun 2015
```

Which is *not* vulnerable.
