### ISSUE TITLE
install command fails in csh shell

### ISSUE THREAD

**Issue by Eothred** [Homebrew/homebrew#41077]
My colleague was very confused when trying to install Homebrew on his machine, as the command failed with strange statements. I figured out that the problem was simply that he had csh as the default shell, instead of bash or zsh.

Would it be possible to have a shebang or similar in the installation script, to avoid that problem? Or at least give a more meaningful error message than what is currently provided in this situation?

**Comment by Eothred** [comment]
Sorry, by "install command" I mean the ruby/curl command on your homepage, brew.sh

**Comment by jacknagel** [comment]
A shebang won't help here. The script is a ruby scrip that is downloaded and executed as text, not saved to a file. And providing an error message isn't really possible (if we could correctly execute code to print the error, then we could just execute the installer instead).

The current install procedure is a tradeoff between asthetics and portability.

See https://github.com/Homebrew/homebrew/issues/19276 for previous discussion on this point.

And feel free to open issues at https://github.com/Homebrew/install if you have suggestions
