### ISSUE TITLE
doctor: Error: No such file or directory - ~/.homebrew_temp/...

### ISSUE THREAD

**Issue by antonagestam** [Homebrew/homebrew#41072]
I'm having issues very similar to #40777:

```sh
$ brew doctor
Error: No such file or directory - ~/.homebrew_temp/doctor20150625-10964-1gbo4wh
```

Debug info: https://gist.github.com/antonagestam/1af9d343e9c29a291a12

**Comment by mikemcquaid** [comment]
Do you have `HOMEBREW_TEMP` set?

**Comment by antonagestam** [comment]
@mikemcquaid:
```sh
$ echo $HOMEBREW_TEMP
~/.homebrew_temp
```

**Comment by mikemcquaid** [comment]
Unset that.

**Comment by antonagestam** [comment]
@mikemcquaid That did the trick, thanks! Don't know why I had that set in the first place.
