### ISSUE TITLE
cutter formula has incorrect description

### ISSUE THREAD

**Issue by therealprof** [Homebrew/homebrew#41073]
The description reads:
desc "Disconnect routed IP connections"

however this formula is actually the unittest testing framework rather then the connection cutter.

The official description is: "a Unit Testing Framework for C and C++"

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by therealprof** [comment]
I certainly know how to do that but for a one line change that a *HUGE* overhead for me.

**Comment by mikemcquaid** [comment]
@therealprof what do you suggest instead?

**Comment by therealprof** [comment]
The commit incorrect change was committed by adzenith in https://github.com/Homebrew/homebrew/commit/8dd3478131b232553f4c0cab197f8443a0a559a6

So maybe he or someone else who's already setup to do so could simply fix it and commit?

**Comment by mikemcquaid** [comment]
@therealprof That's possible, yes. However, we get huge numbers of requests every day and it's great when members of the community help out making these changes as we don't have the time do all of them ourselves. If you don't have time either: no worries, I'm sure someone will get to this eventually.
