### ISSUE TITLE
Installation fails -plague of errors

### ISSUE THREAD

**Issue by edquijano** [Homebrew/homebrew#41070]
I have tried to uninstall, install, upgrade, many times but failed. I used "sudo" but as well failed. Any suggestions? 
Mac Pro. OS X Yosemite. Version 10.10.3 
I have installed fully Xcode. 
I wanted to use for ruby development and ruby on rails. 
This are the message that I received.

From https://github.com/Homebrew/homebrew
 * [new branch]      master     -> origin/master
error: unable to unlink old 'Library/ENV/include/6.3/__debug' (Permission denied)
error: unable to unlink old 'Library/ENV/pkgconfig/10.11/libcurl.pc' (Permission denied)
error: unable to unlink old 'Library/ENV/pkgconfig/10.11/libexslt.pc' (Permission denied)
error: unable to unlink old 'Library/ENV/pkgconfig/10.11/libxml-2.0.pc' (Permission denied)
error: unable to unlink old 'Library/ENV/pkgconfig/10.11/libxslt.pc' (Permission denied)
error: unable to unlink old 'Library/ENV/pkgconfig/10.11/sqlite3.pc' (Permission denied)
error: unable to unlink old 'Library/ENV/pkgconfig/10.11/zlib.pc' (Permission denied)
error: unable to unlink old 'Library/Homebrew/test/lib/config.rb' (Permission denied)
fatal: Could not reset index file to revision 'origin/master'.
Failed during: git reset --hard origin/maste

Thanks 
Ed Quijano
edquijano@outlook.com

**Comment by mikemcquaid** [comment]
`sudo chown -R $USER /usr/local` and try again.
