### ISSUE TITLE
NAnt fails to install from homebrew

### ISSUE THREAD

**Issue by xgalaxy** [Homebrew/homebrew#41088]
➜  ~  brew install nant
==> Installing nant dependency: mono
==> Downloading https://homebrew.bintray.com/bottles/mono-4.0.1.44.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring mono-4.0.1.44.yosemite.bottle.tar.gz
==> Caveats
To use the assemblies from other formulae you need to set:
  export MONO_GAC_PREFIX="/usr/local"

==> Summary
🍺  /usr/local/Cellar/mono/4.0.1.44: 1006 files, 178M
==> Installing nant
==> Downloading https://downloads.sourceforge.net/nant/nant/nant-0.92-src.tar.gz
Already downloaded: /Library/Caches/Homebrew/nant-0.92.tar.gz
==> Downloading https://github.com/nant/nant/commit/69c8ee96493c5d953212397c8ca06c2392372ca4.di
Already downloaded: /Library/Caches/Homebrew/nant--patch-47142439263f22f7fee1608f4b50cbff51496f9b.diff
==> Patching
patching file src/NAnt.Console/App.config
patching file src/NAnt.Core/ConsoleDriver.cs
patching file src/NAnt.Core/Resources/ProjectHelp.xslt
patching file src/NAnt.DotNet/Tasks/CscTask.cs
patching file src/NAnt.NUnit/NAnt.NUnit.build
patching file src/NDoc.Documenter.NAnt/NDoc.Documenter.NAnt.build
patching file tests/NAnt.Core/Framework.config
==> make install prefix=/usr/local/Cellar/nant/0.92
cp src/NAnt.Console/App.config bootstrap/NAnt.exe.config
gmcs  -target:exe -define:MONO,NET_1_0,NET_1_1,NET_2_0,ONLY_2_0 -out:bootstrap/NAnt.exe -r:bootstrap/log4net.dll \
		-r:System.Configuration.dll -recurse:src/NAnt.Console/*.cs src/CommonAssemblyInfo.cs
/bin/sh: gmcs: command not found
make: *** [bootstrap/NAnt.exe] Error 127
couldn't understand kern.osversion `14.3.0'

READ THIS: https://git.io/brew-troubleshooting

**Comment by DomT4** [comment]
> READ THIS: https://git.io/brew-troubleshooting

:wink:. Need a full `brew gist-logs nant` here.

**Comment by xgalaxy** [comment]
➜  ~  brew gist-logs nant
couldn't understand kern.osversion `14.3.0'

**Comment by DomT4** [comment]
What about a manual `brew config && brew doctor` then?

**Comment by xgalaxy** [comment]
zsh: correct 'config' to '.config' [nyae]? n
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 48c48743132d87dd2a62fc36b7789c8bf71e2d06
Last commit: 30 seconds ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit sandybridge
OS X: 10.10.3-x86_64
Xcode: 6.3.2
CLT: 6.3.2.0.1.1431401888
couldn't understand kern.osversion `14.3.0'
GCC-4.2: build 5666
Clang: 6.1 build 602
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.8.0_25
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/nant.pc

**Comment by xgalaxy** [comment]
gmcs is part of Mono. But you can see from my log above that it installed mono before NAnt because it is a dependency. So why is it failing to find it?

**Comment by DomT4** [comment]
Heh. Found the cause. `gmcs` apparently no longer exists, or at least, is no longer being installed for some reason.

` ls -1 /usr/local/Cellar/mono/4.0.1.44/bin/ | grep gmcs ` returns nothing.

**Comment by DomT4** [comment]
Found the [commit](https://github.com/mono/mono/commit/b304ec5e0e694ef7098e0fc3eba9dbc0162f4568). Was deliberately removed. Needs reporting upstream to `NAnt` so they can fix their build script.

**Comment by DomT4** [comment]
Reported: https://github.com/nant/nant/issues/151
