### ISSUE TITLE
Error installing vim 7.4 due to Clang not working as the gcc compiler

### ISSUE THREAD

**Issue by gopinatht** [Homebrew/homebrew#41094]
$ brew install vim
==> Downloading https://mirrors.kernel.org/debian/pool/main/v/vim/vim_7.4.712.or
Already downloaded: /Library/Caches/Homebrew/vim-7.4.712.tar.gz
==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/7.4.712_1/sha
==> make
     (maybe you meant: _my_iconv_open)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [vim] Error 1
make: *** [first] Error 2
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Error installing vim 7.4 due to Clang not working as the gcc compiler (https://github.com/Homebrew/homebrew/issues/40910)
vim  7.4.488 build fails if Homebrew ruby is installed but /usr/bin/ruby comes first in PATH (https://github.com/Homebrew/homebrew/issues/33705)

Any help appreciated.

FYI:
$ brew gist-logs vim
returned
https://gist.github.com/anonymous/22b818e9719750ccfafc

**Comment by ilovezfs** [comment]
What is your PATH?

```
echo $PATH
```

**Comment by ilovezfs** [comment]
You should be able to fix the issue by doing
```
brew install ruby
export PATH=/usr/local/bin:$PATH
brew install vim
```

**Comment by gopinatht** [comment]
Hi ilovzfs,

Thanks for the help. I was able to get around this issue by moving the
MacPorts files out of the way:

mkdir ~/temp
sudo mv /opt/local/lib/libiconv* ~/temp/

Then doing my install:

brew install vim

Then bringing back the macports files:

sudo mv /opt/local ~/macports

MacPorts is turning out to be a pain in the posterior when using Brew. I
will try and use your solution next time I try to install something with
Brew.

Thanks again.

Best Regards
Gopinath

**Comment by gopinatht** [comment]
Correction on the last step there:

sudo mv ~/temp/libiconv* /opt/local/lib/

**Comment by jacknagel** [comment]
Closing since this was due to MacPorts being installed.
