### ISSUE TITLE
Call for formular: xtrace

### ISSUE THREAD

**Issue by guodong** [Homebrew/homebrew#41092]
[xtrace](http://example.net/) is useful when developing low level x11 program, but I cannot use brew to install.

**Comment by jacknagel** [comment]
You can try to create a formula yourself, and then submit a pull request. If it requires X11 it should go to https://github.com/Homebrew/homebrew-x11.

There's a guide for submitting pull requests here: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

Thanks!
