### ISSUE TITLE
(feature request) option to interactively choose which package to upgrade

### ISSUE THREAD

**Issue by mindrones** [Homebrew/homebrew#41105]
It would be nice to have an interactive mode for `brew outdated` to upgrade packages one by one.

It could be `brew outdated --interactive-upgrade` or maybe `brew upgrade --interactive-select`

    $ brew outdated --interactive-upgrade
    ffmpeg (2.6.1 < 2.6.3)    Upgrade? [y/n] y

Answering `yes` could place a checkmark at the left so that we get:

    ✅ ffmpeg (2.6.1 < 2.6.3)
    nginx (1.4.0 < 1.8.0)    Upgrade? [y/n] y

    ✅ ffmpeg (2.6.1 < 2.6.3)
    ✅ nginx (1.4.0 < 1.8.0)
    python (2.7.8_1 < 2.7.10)    Upgrade? [y/n] n

    ✅ ffmpeg (2.6.1 < 2.6.3)
    ✅ nginx (1.4.0 < 1.8.0)
    python3 (3.3.1 < 3.4.3)    Upgrade? [y/n] y

    ✅ ffmpeg (2.6.1 < 2.6.3)
    ✅ nginx (1.4.0 < 1.8.0)
    ✅ python3 (3.3.1 < 3.4.3)

At the end of the selection process it would run `brew upgrade ffmpeg nginx python3`

**Comment by mikemcquaid** [comment]
We don't really do interactive modes but it'd be possible to build a utility on top of Homebrew to do this.

**Comment by mindrones** [comment]
OK thanks!
