### ISSUE TITLE
Brew installing boost

### ISSUE THREAD

**Issue by CapitalChi** [Homebrew/homebrew#41114]
I'm on Mac OSX Yosemite 10.10.3, and brew install boost is not compiling Boost correctly.  (Sorry if this is off topic, but there doesn't seem to be a better place to post this, so I am hoping this is a common enough problem that someone here had a similar issue to me.)

For example, running

g++ -I/usr/local/Cellar/include -x c++ -E /dev/null -include boost/version.hpp      && echo SUCCESS: 
gives me

 1 "/dev/null"
 1 "<built-in>" 1
 1 "<built-in>" 3
 326 "<built-in>" 3
 1 "<command line>" 1
In file included from <built-in>:326:
<command line>:1:10: fatal error: 'boost/version.hpp' file not found
include "boost/version.hpp"
         ^
 1 "<built-in>" 2
1 "/dev/null" 2

I noticed that the directory structure obtained through Brew installing is substantially different from the one listed here: http://www.boost.org/doc/libs/1_35_0/more/getting_started/unix-variants.html.  Maybe this doesn't affect anything.

**Comment by DomT4** [comment]
Please supply a full `brew gist-logs boost`, Thanks!

**Comment by jacknagel** [comment]
>I/usr/local/Cellar/include

You want `-I/usr/local/include`.

**Comment by CapitalChi** [comment]
Thank you for the response.
@DomT4  jir955$ brew gist-logs boost
Error: No logs.
@jacknagel 
98e0d9879a43:kenlm jir955$ g++ -I/usr/local/include -x c++ -E /dev/null -include boost/ver…
# 1 "/dev/null"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 326 "<built-in>" 3
# 1 "<command line>" 1
In file included from <built-in>:326:
<command line>:1:10: fatal error: 'boost/ver…' file not found
#include "boost/ver…"
         ^
# 1 "<built-in>" 2
# 1 "/dev/null" 2

**Comment by CapitalChi** [comment]
Hi, sorry, there was a typo in the previous on the command line, and I'm getting success.  If I may, let me explain the situation.  Boost is necessary to compile kenlm, a language modeling toolkit I am trying to use.  To compile the toolkit I need to run .bjam.   With what I saw above from @jacknagel 's comment I now see I can do that by running: 

./bjam --with-boost=/usr/local/

So I suppose with Homebrew Boost is being placed in a nonstandard directory?
However, at the next step of what I want to do, which is to setup a kenlm's python module via 

python setup.py install, 

I have the following fatal error, which I wonder is due to the same reason:

./util/fake_ofstream.hh:15:10: fatal error: 'boost/lexical_cast.hpp' file not
      found

**Comment by CapitalChi** [comment]
Never mind, fixed it! Thanks for your help.
