### ISSUE TITLE
android-sdk formula throws warnings

### ISSUE THREAD

**Issue by anthonygreen** [Homebrew/homebrew#41110]
OSX 10.9.5
brew install android-sdk throws these warnings at the end of the install

    Warning: Could not fix /tmp/android-build-build-temp-50661/install-darwin-x86_64/lib/libz.1.dylib in     /usr/local/Cellar/android-sdk/24.3.2/tools/qemu/darwin-x86_64/qemu-system-aarch64
    Warning: Could not fix /tmp/android-build-build-temp-50661/install-darwin-x86_64/lib/libz.1.dylib in /usr/local/Cellar/android-sdk/24.3.2/tools/qemu/darwin-x86_64/qemu-system-mips64el
    Warning: Could not fix /tmp/android-build-build-temp-50661/install-darwin-x86_64/lib/libz.1.dylib in /usr/local/Cellar/android-sdk/24.3.2/tools/qemu/darwin-x86_64/qemu-system-x86_64

**Comment by jacknagel** [comment]
You can just ignore them for now, they're difficult to address but also nothing to worry about. See https://github.com/Homebrew/homebrew/pull/40630#issuecomment-111899028

**Comment by adamv** [comment]
Closing as nothing to worry about.

**Comment by usmonster** [comment]
Hello! Even though this is difficult to address and not much to worry about, can this please be reopened until it is eventually addressed?

Until it's fixed, folks will have to mentally filter _some_ warning messages while looking out for "real" ones, which makes homebrew less usable and can potentially lead to harmful user behavior. Plus, those who are affected will have an easier time finding and tracking the issue if it is open.

Thanks!
