### ISSUE TITLE
Error: No available formula for smpeg

### ISSUE THREAD

**Issue by Argon-** [Homebrew/homebrew#41117]
I'm currently a bit baffled and don't really get what's going wrong:

    ~ → brew up
    Already up-to-date.
    ~ → brew leaves --installed
    Error: No available formula for smpeg
    Please tap it and then try again: brew tap homebrew/head-only
    ~ → brew info smpeg
    smpeg: stable 0.4.5 (bottled)
    SDL MPEG Player Library
    https://icculus.org/smpeg/
    /usr/local/Cellar/smpeg/0.4.5 (22 files, 688K) *
      Poured from bottle
    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/smpeg.rb
    ==> Dependencies
    Build: autoconf, automake, libtool, pkg-config
    Required: sdl
    Optional: gtk+
    ==> Options
    --with-gtk+
    	Build with gtk+ support
    ~ → brew leaves
    Error: No available formula for smpeg
    Please tap it and then try again: brew tap homebrew/head-only

`homebrew/head-only` is already tapp'ed and it happens with and without `smpeg` installed. `brew doctor` mentions nothing unusual.

**Comment by DomT4** [comment]
Any unexpected changes in `cd $(brew --prefix) && git status`? Maybe there's an old version lingering around, try `brew cleanup` or even `brew tap --repair`.

**Comment by Argon-** [comment]
Neither of these helped. However, after I untapped every single repo (only homebrew/* ones) it worked. Could there have been some old, conflicting data?

**Comment by DomT4** [comment]
Strange. Maybe your `head-only` clone wasn't getting the updates for some reason. An old installation or old symlink seemed the most likely cause, but the cleanup and repair would have fixed both those issues. :octopus:. Closing as resolved at least.
