### ISSUE TITLE
Anyway to force formula to download tags?

### ISSUE THREAD

**Issue by bryanbecker** [Homebrew/homebrew#41126]
The makefile for my project depends on having `git describe --tags` return a release version number, but homebrew doesn't seem to pull this.

Anyway to force it to pull the most recent tag name?  If I do a normal git clone (not with brew), this works fine

**Comment by dunn** [comment]
I think `url "https://github.com/whatever/thing.git", :shallow => false` will work.

**Comment by bryanbecker** [comment]
Hmm, it didn't seem to make a difference.

I'm working on getting `--HEAD` to work first, since that's simpler (and more useful for this package).  Currently I have:

```
class DcssHead < Formula
  desc "A roguelike adventure through dungeons filled with dangerous monsters in a quest to find the mystifyingly fabulous Orb of Zot."
  homepage "http://crawl.develz.org/"
  version "0.16.1"
  url "https://github.com/crawl/crawl/archive/#{version}.tar.gz"
  head "https://github.com/crawl/crawl.git", :branch => "master", :shallow => "false"
  .
  .
  .
```

But I can't get either to work.

**Comment by dunn** [comment]
FYI, [Stone Soup is already in the games repository](https://github.com/Homebrew/homebrew-games/blob/master/stone-soup.rb), if you were thinking of adding it as a new formula.

**Comment by bryanbecker** [comment]
It is, but it's out of date by two versions (0.15.2 v 0.17.0a) .  Also, that repo just downloads a precompiled binary... anyone could easily do that without homebrew.  Also, as far as I can tell, that is not an official repository for the game

I'd like to give OSX players the option of playing with the latest version, since windows users already that option

**Comment by dunn** [comment]
No, that's great! I just meant you should update that formula in homebrew-games instead of submitting a brand-new formula here.

**Comment by mistydemeo** [comment]
>  Also, that repo just downloads a precompiled binary... anyone could easily do that without homebrew.

No, the formula in homebrew-games builds from the official source code! The tarball is the "full source with dependencies" tarball from [this page](http://crawl.develz.org/download.htm).

We'd gladly accept a pull request to bring it up to date though!

**Comment by mistydemeo** [comment]
Closing, but would accept contributions to the formula in homebrew-games. Thank you!

**Comment by bryanbecker** [comment]
Hi,
OK, I'll take a look into adding functionality to that existing repo.

But I still haven't solved the issue matching the title (how do you get homebrew to download tags?).  Should the issue really be closed or should I reopen it in homebrew-games (sorry, this is my first time dipping my toes into open source)?

**Comment by dunn** [comment]
Try removing the quotes around `false`
