### ISSUE TITLE
Issue with python and tcl-tk

### ISSUE THREAD

**Issue by izurdo** [Homebrew/homebrew#41132]
I follow all the instructions given in http://www.pymolwiki.org/index.php/MAC_Install#Installing_PyMOL_with_Homebrew
But it does not work. Also I checked https://github.com/Homebrew/homebrew/issues/25974
I tried many things, but the error persists.
This is the error:

```
$ pymol
 PyMOL(TM) Molecular Graphics System, Version 1.7.6.0.
 Copyright (c) Schrodinger, LLC.
 All Rights Reserved.
 
    Created by Warren L. DeLano, Ph.D. 
 
    PyMOL is user-supported open-source software.  Although some versions
    are freely available, PyMOL is not in the public domain.
 
    If PyMOL is helpful in your work or study, then please volunteer 
    support for our ongoing efforts to create open and affordable scientific
    software by purchasing a PyMOL Maintenance and/or Support subscription.

    More information can be found at "http://www.pymol.org".
 
    Enter "help" for a list of commands.
    Enter "help <command-name>" for information on a specific command.

 Hit ESC anytime to toggle between text and graphics.

 Detected OpenGL version 2.0 or greater. Shaders available.
 Detected GLSL version 1.20.
 OpenGL graphics engine:
  GL_VENDOR:   Intel Inc.
  GL_RENDERER: Intel HD Graphics 5000 OpenGL Engine
  GL_VERSION:  2.1 INTEL-10.6.20
Traceback (most recent call last):
  File "/usr/local/Cellar/pymol/1.7.6.0/libexec/lib/python2.7/site-packages/pmg_tk/__init__.py", line 35, in run
    PMGApp(pymol_instance,skin).run(poll)
  File "/usr/local/Cellar/pymol/1.7.6.0/libexec/lib/python2.7/site-packages/pmg_tk/PMGApp.py", line 309, in __init__
    self.root = Tk() # creates the root window for the application
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1816, in __init__
    self._loadtk()
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1832, in _loadtk
    % (_tkinter.TK_VERSION, tk_version)
RuntimeError: tk.h version (8.6) doesn't match libtk.a version (8.5)
 Detected 4 CPU cores.  Enabled multithreaded rendering
```

And it closes after a few moments.
It is under OS X 10.10.
Many thanks for any help.

BR

**Comment by tdsmith** [comment]
Can you share the build logs for python, tcl-tk, and pymol with `brew gist-logs python; brew gist-logs tcl-tk; brew gist-logs pymol`?

**Comment by izurdo** [comment]
Hi,
brew gist-logs python
https://gist.github.com/d0520a006dd1f96670ce
brew gist-logs tcl-tk
https://gist.github.com/6de9eaab05fa9b158754
brew gist-logs pymol
Error: No logs.

I removed all and installed again, but strangely no logs for pymol. If i try to remove it and install again, it does not do anything, just:
$ brew remove pymol
Uninstalling /usr/local/Cellar/pymol/1.7.6.0... (709 files, 20M)
$ brew install pymol
==> Installing pymol from homebrew/homebrew-science
==> Downloading https://homebrew.bintray.com/bottles-science/pymol-1.7.6.0.yosem
Already downloaded: /Library/Caches/Homebrew/pymol-1.7.6.0.yosemite.bottle.tar.gz
==> Pouring pymol-1.7.6.0.yosemite.bottle.tar.gz
==> Caveats
On some Macs, the graphics drivers do not properly support stereo
graphics. This will cause visual glitches and shaking that stay
visible until X11 is completely closed. This may even require
restarting your computer. Launch explicitly in Mono mode using:
  pymol -M

==> Summary
🍺  /usr/local/Cellar/pymol/1.7.6.0: 709 files, 20M

I am new to brew, so sorry for my lack of knoledge on it; is there something I can do?

Many thanks

Thanks

**Comment by tdsmith** [comment]
Hmm, Python is building the tcl extension against -ltcl8.5; it's not picking up the brewed tk correctly. Your Xcode-only configuration may be contributing. I'll look at this later.

**Comment by tdsmith** [comment]
Confirmed that this works on a CLT-enabled system (so `xcode-select --install` is probably a workaround for you) and set up a Mavericks VM image to test. Need to install Homebrew and Xcode on it.

**Comment by tdsmith** [comment]
This could be related:
> Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/lib/tcl8.6

Does `brew prune` and then reinstalling Python help?

**Comment by satartic** [comment]
Thanks a lot for your help, it really helped. Now it works. What I did following your instructions:
xcode-select --install
brew prune
brew uninstall python
brew install python --with-tcl-tk --enable-threads --with-x11 (instead of brew install python --with-brewed-tk --enable-threads --with-x11 which I did not try this time)

**Comment by izurdo** [comment]
Thanks a lot for your help, it really helped. Now it works. What I did following your instructions:
xcode-select --install
brew prune
brew uninstall python
brew install python --with-tcl-tk --enable-threads --with-x11 (instead of brew install python --with-brewed-tk --enable-threads --with-x11 which I did not try this time)

**Comment by aflaus** [comment]
izurdo commands above (Jul 3) worked for me with same error and pymol crashing after every few minutes of interaction. I had first run "xcode-select --install" as recommended by brew doctor before the above. OSX 10.10.5.
