### ISSUE TITLE
Gocode recipe removed?

### ISSUE THREAD

**Issue by victorhooi** [Homebrew/homebrew#41140]
I'm trying to install the gocode tool (https://github.com/nsf/gocode) using Homebrew 

It seems there was previously a formula for gocode that was merged in:

https://github.com/Homebrew/homebrew/pull/8239

However, this seems to have disappeared now (and for some reason `git log -- Library/Formula/gocode.rb` didn't show it up...possibly my syntax is off).

Was there a reason it was removed?

**Comment by mistydemeo** [comment]
As far as I can see it was never merged. Adam commented at the time that it appeared to be tracking unstable releases of go.

**Comment by asparagui** [comment]
^^

**Comment by jacknagel** [comment]
Upstream repo says: "It's a good idea to use the latest git version always. I'm trying to keep it in a working state."

I think we would welcome a PR, but it may make more sense in homebrew-head-only. The tagged releases are pretty old.
