### ISSUE TITLE
Cannot install colordiff

### ISSUE THREAD

**Issue by drolando** [Homebrew/homebrew#41163]
When I try to install colordiff I get the following error. It appears that that tar.gz is really no longer available on their website. The latest version is now 1.0.15.

$ brew install -vd colordiff
==> Downloading http://www.colordiff.org/colordiff-1.0.13.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "colordiff"
Download failed: http://www.colordiff.org/colordiff-1.0.13.tar.gz

**Comment by DomT4** [comment]
Could you possibly open a PR to update the version?

[This](https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)) should help, but feel free to ping me on anything you're unsure on.

**Comment by drolando** [comment]
I've already tried to update the formula but I get an error that I do not understand.
This is my change:

    -  url "http://www.colordiff.org/colordiff-1.0.13.tar.gz"
    -  sha1 "64e369aed2230f3aa5f1510b231fcac270793c09"
    +  url "http://www.colordiff.org/colordiff-1.0.15.tar.gz"
    +  sha1 "77c518233f81c8ef2542cbd32e6597ee3e5ef432"

And this the error:

    ==> Downloading http://www.colordiff.org/colordiff-1.0.15.tar.gz
    Already downloaded: /Library/Caches/Homebrew/colordiff-1.0.15.tar.gz
    ==> Verifying colordiff-1.0.15.tar.gz checksum
    tar xf /Library/Caches/Homebrew/colordiff-1.0.15.tar.gz
    ==> Patching
    patching file Makefile
    Hunk #1 FAILED at 8.
    Hunk #3 succeeded at 38 with fuzz 1.
    1 out of 3 hunks FAILED -- saving rejects to file Makefile.rej
    Error: Failure while executing: /usr/bin/patch -g 0 -f -p1

**Comment by DomT4** [comment]
It likely means upstream have fixed part of what we needed to patch before. You'll need to look at upstream's `Makefile` and see which parts of the patch are no longer necessary, if any are.

**Comment by drolando** [comment]
Done: https://github.com/Homebrew/homebrew/pull/41165

**Comment by DomT4** [comment]
Thanks! :beers:
