### ISSUE TITLE
brew install boost155 --with-python --with-mpi --without-single fails, when llvm is linked

### ISSUE THREAD

**Issue by kilojoules** [Homebrew/homebrew#41186]
$ brew install boost155 --with-python --with-mpi --without-single
    ==> Installing boost155 from homebrew/homebrew-versions
    ==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.55.0/boost_1_55_0.tar.bz2
    Already downloaded: /Library/Caches/Homebrew/boost155-1.55.0.tar.bz2
    ==> Downloading https://github.com/boostorg/atomic/commit/6bb71fdd.diff
    Already downloaded: /Library/Caches/Homebrew/boost155--patch-eb139160a33d8ef3e810ce3e47da278563d03d7be6d0a75c109f708030a7abcb.diff
    ==> Downloading https://github.com/boostorg/atomic/commit/e4bde20f.diff
    Already downloaded: /Library/Caches/Homebrew/boost155--patch-8c5efeea91d44b2a48fdeee9cde71e831dad78f0930e8f65b7223ba0ecdfec9b.diff
    ==> Downloading https://github.com/boostorg/chrono/commit/143260d.diff
    Already downloaded: /Library/Caches/Homebrew/boost155--patch-f6f40b576725b15ddfe24497ddcd597f387dfdf674f6dd301b8dcb723593ee22.diff
    ==> Downloading https://gist.githubusercontent.com/philacs/375303205d5f8918e700/raw/d6ded52c3a927b6558984d22efe0a5cf9e59cd8c/0005-Boost.S11n-include-missing-algorithm.patch
    Already downloaded: /Library/Caches/Homebrew/boost155--patch-cb134e3982e01ba5b3d5abe51cc8343c9e24ecd34aa4d81f5e8dd4461f593cf1.patch
    ==> Patching
    patching file boost/atomic/detail/cas128strong.hpp
    patching file boost/atomic/detail/gcc-atomic.hpp
    patching file boost/chrono/config.hpp
    patching file boost/chrono/detail/inlined/mac/thread_clock.hpp
    patching file boost/archive/iterators/transform_width.hpp
    ==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost155/1.55.0_1 --libdir=/usr/local/Cellar/boost155/1.55.0_1/lib --without-icu --without-libraries=
    ==> ./b2 --prefix=/usr/local/Cellar/boost155/1.55.0_1 --libdir=/usr/local/Cellar/boost155/1.55.0_1/lib -d2 -j4 --layout=system --user-config=user-config.jam install threading=multi link=shared,static
    brew gist-logs boost155
        cp "bin.v2/libs/wave/build/darwin-4.2.1/release/link-static/threading-multi/libboost_wave.a"  "/usr/local/Cellar/boost155/1.55.0_1/lib/libboost_wave.a"
    
    ...failed updating 18 targets...
    ...skipped 23 targets...
    ...updated 11858 targets...
    
    READ THIS: https://git.io/brew-troubleshooting
    If reporting this issue please do so at (not Homebrew/homebrew):
      https://github.com/homebrew/homebrew-versions/issues
    

    $ brew gist-logs boost155
    https://gist.github.com/088bfebc88e2caf649fd

`brew doctor` doesn't report any red flags, although it warns that I have llvm linked.

**Comment by kilojoules** [comment]
brew `unlink llvm` solved this particular issue, although the project I'm working on requires llvm's c compiler as well as the boost libraries.

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-versions#876
