### ISSUE TITLE
Update formula for Packer 0.80

### ISSUE THREAD

**Issue by peterloron** [Homebrew/homebrew#41190]
Packer 0.80 has been released. Please update formula to 0.80. Thanks.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by jeffhung** [comment]
Hi, as I'm interested in packer 0.8, I helped create the pull request at #41237. :-)

**Comment by evilantnie** [comment]
Thanks Jeff, I've also been waiting for this, hope it gets merged soon.

**Comment by DomT4** [comment]
Closing in favour of the various PRs opened.
