### ISSUE TITLE
brew install does not always ensure complete repo when `:shallow => false`

### ISSUE THREAD

**Issue by cgull** [Homebrew/homebrew#41225]
A Mosh user reported failure of `brew install --HEAD mobile-shell` today:

https://github.com/keithw/mosh/issues/632#issuecomment-117354479

Mosh recently started using `git describe`, and requiring a full Git repo.  That all seems set up properly in Mosh and `mobile-shell.rb`, but it looks like Homebrew doesn't handle this right in a corner case.  If a stale older version of the formula gets a shallow clone, then the repo stays shallow even after it's been upgraded to say `:shallow => false`, because Homebrew only does a `git fetch` to incrementally update the repo.  Homebrew should do...whatever's necessary to make it a deep clone (I don't know how you'd do that efficiently).  I've reproduced this with:
```
  577  cd /Library/Caches/Homebrew/mobile-shell--git
... #looked around a little, no writes
  583  cd ../
  584  rm -rf mobile-shell--git
  585  cd /usr/local/
  586  git checkout f8fd8b48d9e706cb6a3625623df40bcfab38470d^
  587  brew install --HEAD mobile-shell # I forgot it was already installed
  588  brew remove mobile-shell
  589  brew install --HEAD mobile-shell # failed
  590  brew checkout master # braino
  591  git checkout master
  592  brew update
  593  brew install --HEAD mobile-shell # failed again
```

**Comment by cgull** [comment]
`git fetch --unshallow origin`
D`oh!

**Comment by DomT4** [comment]
It works fine here:

```
==> Summary
🍺  /usr/local/Cellar/mobile-shell/HEAD: 13 files, 956K, built in 83 seconds
```

If you already had a `HEAD` of `mosh` cached it's possible you'd need to wipe it out to get the new deep clone.

**Comment by cgull** [comment]
Did you do the full repro?  That's necessary to get the failure.

The issue doesn't even require a stale Brew install.  Consider a user that installs a formula from source.  Then, the project changes the build to require a deep clone and updates their brew file.  Then the user updates Brew and upgrades.  If the project hasn't tagged the repo in between the user's two builds, the second build fails on not finding a tag in the shallow clone.

**Comment by DomT4** [comment]
> Did you do the full repro? That's necessary to get the failure.

Yup. Went through your whole step process. Still no build failure here :confused:.

**Comment by DomT4** [comment]
```
brew install -v --debug --build-from-source mosh --HEAD
🍺  /usr/local/Cellar/mobile-shell/HEAD: 13 files, 956K, built in 75 seconds

brew rm mosh
git checkout f8fd8b48d9e706cb6a3625623df40bcfab38470d^
brew install -v --debug --build-from-source mosh --HEAD
🍺  /usr/local/Cellar/mobile-shell/HEAD: 13 files, 956K, built in 54 seconds

brew rm mosh
gco master
brewup
brew install -v --debug --build-from-source mosh --HEAD
🍺  /usr/local/Cellar/mobile-shell/HEAD: 13 files, 956K, built in 58 seconds
```

**Comment by cgull** [comment]
Still fails for me:  https://gist.github.com/fde30cc98fa398aae3f2.git

You didn't *exactly* follow my repro :) You're doing `--build-from-source`, I'm not-- perhaps Brew behaves differently in that case?

**Comment by DomT4** [comment]
`--HEAD` builds are always `--from-source`. Technically I didn't need to pass that but I have a keyboard shortcut and I was too lazy to backspace over the redundant parts :wink:. The behaviour should be identical.

Will look over the `gist` and see if I'm missing anything.

**Comment by cgull** [comment]
Ah, your typescript doesn't show you removing the cache build directory, and you would probably already have a deep clone from our earlier work on the mosh formula.  That would mask this problem.

**Comment by DomT4** [comment]
```
cd `brew --cache`
rm -rf mobile-shell--git
cdbrew
gco f8fd8b48d9e706cb6a3625623df40bcfab38470d^
brew install -v --debug --build-from-source --HEAD mobile-shell # This does fail
gco master
brewup
brew install -v --debug --build-from-source --HEAD mobile-shell # Fails
```

Bingo. Right you are. I suspect we *presume* the cached clone is recent enough that it would already be deep/shallow without us having to make it so. For most formula installs, even from git, this isn't an issue because of the versioning, but `HEAD` will always be named `HEAD` even if that clone was done 6 months ago and not removed since.

**Comment by jacknagel** [comment]
Is there an easy way to ask git "is this repo shallow?"

**Comment by mistydemeo** [comment]
I'm not sure if it can be done through the tool, but `.git/shallow` will exist with the hash of the cloned commit if it's shallow.

**Comment by mistydemeo** [comment]
Should be fixed - I tested locally.

**Comment by cgull** [comment]
Looks good to me.  Thanks.

**Comment by cgull** [comment]
Tested here; it works.
