### ISSUE TITLE
brew update broken

### ISSUE THREAD

**Issue by RyanSinger** [Homebrew/homebrew#41229]
Ryans-MacBook-Pro:~ ryan$ brew update
error: The following untracked working tree files would be overwritten by merge:
	Library/Formula/pdf2svg.rb
Please move or remove them before you can merge.
Aborting
Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master
Ryans-MacBook-Pro:~ ryan$

**Comment by bfontaine** [comment]
Did you edit `pdf2svg.rb`? If not, run:

```
cd $(brew --repository)
git reset --hard FETCH_HEAD
```

And retry.

**Comment by RyanSinger** [comment]
Thanks!

**Comment by jsilvestri** [comment]
:+1:

**Comment by diegojmaldonado** [comment]
Thanks.
