### ISSUE TITLE
[PATCH] audit should skip head-only error when in */head-only directory and same for revel-only

### ISSUE THREAD

**Issue by rkrug** [Homebrew/homebrew#41239]
Hi

I have a head-only recipe which obviously throws an error when running ```brew audit ...```. In the code from ```audit.rb```, recipes in the taps ```home-brew/homebrew-head-only``` and ```home-brew/homebrew-devel-only``` are excluded from throwing errors when they are head-only or devel-only. 
I would suggest to add the same behaviour for private (non-homebrew) taps so that audit can be used reliably without throwing expected errors.

This is especially important for running automated tests with travis-ci as I have to exclude these  recipes from audit as otherwise the test will be classified as failed. 

Therefore I suggest the following patch:

```
From 6ffd15a128630f463d8a1ee835e7569dbe79609f Mon Sep 17 00:00:00 2001
From: "Rainer M. Krug" <R.M.Krug@gmail.com>
Date: Tue, 30 Jun 2015 09:38:30 +0200
Subject: [PATCH] Make audit recognise hed-only and devel-only in all taps

- add wildcard into expressions to identify head-only and dev-only taps
---
 Library/Homebrew/cmd/audit.rb | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/Library/Homebrew/cmd/audit.rb b/Library/Homebrew/cmd/audit.rb
index 3a41dbd..4a6a305 100644
--- a/Library/Homebrew/cmd/audit.rb
+++ b/Library/Homebrew/cmd/audit.rb
@@ -421,11 +421,11 @@ class FormulaAuditor
   end

   def audit_specs
-    if head_only?(formula) && formula.tap.to_s.downcase != "homebrew/homebrew-head-only"
+    if head_only?(formula) && formula.tap.to_s.downcase != "*/homebrew-head-only"
       problem "Head-only (no stable download)"
     end

-    if devel_only?(formula) && formula.tap.to_s.downcase != "homebrew/homebrew-devel-only"
+    if devel_only?(formula) && formula.tap.to_s.downcase != "*/homebrew-devel-only"
       problem "Devel-only (no stable download)"
     end

--
2.4.5
```

Thanks,

Rainer

**Comment by bfontaine** [comment]
Could you make a pull-request? Thanks!

**Comment by xu-cheng** [comment]
In fact, I would suggest to create a custom brew audit command to ignore such error. Like this:
```ruby
$ cat brew-head-audit.rb
require "cmd/audit"

class FormulaAuditor
  def problems
    @problems.reject { |p| p == "Head-only (no stable download)" }
  end
end

Homebrew.audit
```

**Comment by mikemcquaid** [comment]
I think we should probably just make it so it only warns about Homebrew's taps.

**Comment by rkrug** [comment]
The reason why I would like to use the same command is really simplicity in the travis-ci scrips. By using a different tap, this would be really easy to achieve.
 
Mike - I am not exactly sure why you mean, as ay changes in regard to Homebrew's taps would not affect my taps?

Pull request: #41242

**Comment by rkrug** [comment]
I don't get it to work...

I want to change the check so that all recipes in a tap named ```head-only``` or ```level-only``` will not return an error in ```audit.rb``` if the recipe is head-only or devel-only. 
As far as I understand ruby, ```!=~``` should do a negated regular matching. So I tried ```/head-only$/``` as it should match strings ending with ```head-only``` and ```/.*head-only``` as it should match strings having multiple characters before the head-only, but none works.
I would be happy to supply a new pull request with the changes, but what should the condition in the below (already modified) snippet be?

    if head_only?(formula) && formula.tap.to_s.downcase !=~ /.*head-only/
      problem "Head-only (no stable download)"
    end

    if devel_only?(formula) && formula.tap.to_s.downcase != /.*devel-only/
      problem "Devel-only (no stable download)"
    end

**Comment by bfontaine** [comment]
> As far as I understand ruby, `!=~` should do a negated regular matching

I don’t know what `!=~` does but negated regular matching is done with `!~`.

**Comment by xu-cheng** [comment]
Personally, I find it less meaningful to ignore such error based on tap name. On the one hand, in most common situations, 3rd-party taps would be named after the software's name rather than `head-only`. And they are likely to use the same tap name regardless the development state(beta or stable). On the other hand, such behavior is less intuitive and can cause confusing especially without document.

IMHO, I would suggest @rkrug to use a custom command. It doesn't complex anything. [neovim/homebrew-neovim](https://github.com/neovim/homebrew-neovim) has been doing this for a long time. If we really want to support ignoring officially, I think it's best to accomplish this through an option `--ignore-headonly`, like what I proposed in #34121.

**Comment by rkrug** [comment]
Envoyé de mon iPhone

> Le 2 juil. 2015 à 16:55, Xu Cheng <notifications@github.com> a écrit :
> 
> Personally, I find it less meaningful to ignore such error based on tap name. On the one hand, in most common situations, 3rd-party taps would be named after the software's name rather than head-only. And they are likely to use the same tap name regardless the development state(beta or stable). On the other hand, such behavior is less intuitive and can cause confusing especially without document.
> 

I consider it as more consistent if private repos are dealt with in the same way as the official ones in regards to audit. At the moment, this error is excluded for the homebrew-head-only tap. I think that the consistency would require the same exclusion rules for all taps. 
> IMHO, I would suggest @rkrug to use a custom command. It doesn't complex anything. neovim/homebrew-neovim has been doing this for a long time. If we really want to support ignoring officially, I think it's best to accomplish this through an option --ignore-headonly, like what I proposed in #34121.
> 

This would work in my case, but it would not be consistent. Especially S head-only formulas can be really useful in development.

**Comment by xu-cheng** [comment]
The reason of inconsistency is because it's a private behavior and kinda poorly designed one. So if we want to have a public API to ignore head only error, at least let's design it in a better one, such as option flag. 

I strongly against to have different behaviors simply because the tap name.

**Comment by mikemcquaid** [comment]
> I strongly against to have different behaviors simply because the tap name.

That's already happening. I think we should either make this audit affect only official Homebrew organisation taps or just tell people they can ignore some audit warnings on other taps.

**Comment by rkrug** [comment]
Envoyé de mon iPhone

> Le 2 juil. 2015 à 18:07, Mike McQuaid <notifications@github.com> a écrit :
> 
> I strongly against to have different behaviors simply because the tap name.
> 
> That's already happening.
> 
Exactly. 
> I think we should either make this audit affect only official Homebrew organisation taps
> 
But I think this should be checked for all taps as well to make sure that a stable is included unless explicitly not wanted. 
> or just tell people they can ignore some audit warnings on other taps.
> 

Nice when done interactively, but won't help when used in e.g. Jenkins-ci. 

You have forgotten a third option: just give private taps the same possibilities as official ones and do not check these audits in taps with certain names. 

I really do not see any disadvantage in this - and the change in the code is minimal.

**Comment by mikemcquaid** [comment]
> I really do not see any disadvantage in this - and the change in the code is minimal.

It's non-intuitive and restricts naming of taps.

> Nice when done interactively, but won't help when used in e.g. Jenkins-ci.

Sorry, I don't understand why this is a problem.

**Comment by rkrug** [comment]
Envoyé de mon iPhone

> Le 2 juil. 2015 à 21:16, Mike McQuaid <notifications@github.com> a écrit :
> 
> I really do not see any disadvantage in this - and the change in the code is minimal.
> 
> It's non-intuitive and restricts naming of taps.
> 

It is a question of documentation. One sentence in the documentation can state that taps ending with "head-only" will not raise an error in audit when being head-only and the same for devel-only. 

And I don't see a reason why the official tap should be treated differently to private repos. 
And how likely is it to name a repo "head-only" when it contains stable recipes? 
Consistency and documentation is the key here - the official tap should follow the same rules as private taps. 
> Nice when done interactively, but won't help when used in e.g. Jenkins-ci.
> 
> Sorry, I don't understand why this is a problem.
> 
If audit reports an error Jenkins will report all tests as failed. So even if I ignore the error when used interactively, i will have a failing Jenkins-ci test.

**Comment by mikemcquaid** [comment]
> If audit reports an error Jenkins will report all tests as failed. So even if I ignore the error when used interactively, i will have a failing Jenkins-ci test.

Ok, in this case I think you should just create your own wrapper command like @xu-cheng suggested.

**Comment by rkrug** [comment]
This is the a use case - the other reason why I think that it would be useful to have this feature enabled for private taps as well is consistency and workflow: during the development of a new major version, there is a recipe in the head-only tap with audit checks to keep the recipe clean. As soon as it it released, the stable part is added and the recipe graduates into the normal tap, while a new head-only is created tor the new development of the new major version.

It seems that you are reluctant to make this minor change to treat private taps in audit.rb in the same way as official taps. I really don't see any disadvantage or problem in this minor change.

**Comment by mikemcquaid** [comment]
The reason `audit` complains about this is that head-only formulae have a really poor user-experience. I think it's reasonable if you disagree to just ignore this warning with the method @xu-cheng mentioned.

**Comment by rkrug** [comment]
I agree completely about the user experience - they most definitely are not really for the end user - but they also have their (much under-utilised) usage in development and automatic checking. And otherwise, there would not be the head-only and level-only taps in home-brew itself? 

I am just thinking that the same rules should apply to private taps and the official tap, at least in there structure (naming) and formatting and completion of the recipes (which audit is checking).

**Comment by DomT4** [comment]
The PR was merged on this.
