### ISSUE TITLE
linkapps should add OS X aliases, in addition to symlinks

### ISSUE THREAD

**Issue by fatso83** [Homebrew/homebrew#41238]
Symbolic links to applications are not picked up by Finder, but OS X "alias" files do. I propose adding an alias file when doing `brew linkapps`.

![screenshot](https://www.dropbox.com/s/anloxpcxi02rhjh/Skjermbilde%202015-07-01%2013.19.14.png?dl=1)
See this [discussion](http://apple.stackexchange.com/a/95910/44292) for how people work around this. 

The current symbolic link version does one thing AFAI can tell; enabling the "Open With" functionality. The alias is greyed out when doing this.

Since having two near-identical files next to each other sucks, I suggest adding a `/Applications/Homebrew Aliases` directory as a pragmatic place to put aliases that can get picked up by Finder. This would enable opening applications through Finder as well as making it possible to use the Open With functionality.

Something like
```
osascript -e "tell app \"Finder\" to make new alias file at POSIX file \"/Applications/Homebrew Aliases\" to POSIX file \"/usr/local/opt/macvim/MacVim.app\""
``` 
should do it

**Comment by jacknagel** [comment]
See https://github.com/Homebrew/homebrew/pull/35050 where we decided not to do this (there are also other, older issues where we also decided not to do this).
