### ISSUE TITLE
Update qt5 to 5.5

### ISSUE THREAD

**Issue by luzpaz** [Homebrew/homebrew#41248]
Is it more than just changing the following ?
```
class Qt5 < Formula
  desc "Version 5 of the Qt framework"
  homepage "https://www.qt.io/"
  url "https://download.qt.io/official_releases/qt/5.5/5.5.0/single/qt-everywhere-opensource-src-5.5.0.tar.xz"
  mirror "https://www.mirrorservice.org/sites/download.qt-project.org/official_releases/qt/5.5/5.5.0/single/qt-everywhere-opensource-src-5.5.0.tar.xz"
  sha256 "7ea2a16ecb8088e67db86b0835b887d5316121aeef9565d5d19be3d539a2c2af"
```

**Comment by DomT4** [comment]
If there's any patches currently in place in the QT5 formula that'll need looking at, and if there's a `revision` line *outside* the bottle block that needs removing, but otherwise yup, just the URL/Mirror/SHA256 need updating.

**Comment by luzpaz** [comment]
@DomT4, @tdsmith says he's delaying building Qt now due to how much time it takes to build/bottle via brewbot. It's on his todo list.

**Comment by DomT4** [comment]
Yeah, the test-bot is kinda backed up after last night's issues. Once we clear the backlog though feel free to submit a PR or such.

**Comment by luzpaz** [comment]
@tdsmith are we green light to test Qt now ?

**Comment by tdsmith** [comment]
The bot's still pretty busy right now. I'll keep an eye on it; it often quiets down mid-morning Pacific time. See PR #41252. I'll close this issue in favor of the open pull request.
