### ISSUE TITLE
swipl lib not registered in pkgconfig with swi-prolog formula

### ISSUE THREAD

**Issue by bcardiff** [Homebrew/homebrew#41246]
I'm not sure how to fix this in the formula. But installing swi-prolog formula does not register in pkg-config the swipl lib.

I don't know what is the usual lib registration process in homebrew.

swi-prolog formula uses `libexec/lib/pkgconfig` instead of `lib/pkgconfig` as other formulas.

Right now I need to manually set

`export PKG_CONFIG_PATH=/usr/local/Cellar/swi-prolog/7.2.0/libexec/lib/pkgconfig/`

in order to get

```
$ pkg-config --libs swipl
-L/usr/local/Cellar/swi-prolog/7.2.0/libexec/lib/swipl-7.2.0/lib/x86_64-darwin13.4.0 -O2 -pthread -lswipl 
```

Repro snippets
```
$ brew install swi-prolog
==> Installing swi-prolog from homebrew/homebrew-x11
==> Downloading https://homebrew.bintray.com/bottles-x11/swi-prolog-7.2.0.mavericks.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/swi-prolog-7.2.0.mavericks.bottle.tar.gz
==> Pouring swi-prolog-7.2.0.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/swi-prolog/7.2.0: 794 files, 19M

$ swipl --version
SWI-Prolog version 7.2.0 for x86_64-darwin13.4.0

$ pkg-config --libs swipl
Package swipl was not found in the pkg-config search path.
Perhaps you should add the directory containing `swipl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'swipl' found

$ export PKG_CONFIG_PATH=/usr/local/Cellar/swi-prolog/7.2.0/libexec/lib/pkgconfig

$ pkg-config --libs swipl
-L/usr/local/Cellar/swi-prolog/7.2.0/libexec/lib/swipl-7.2.0/lib/x86_64-darwin13.4.0 -O2 -pthread -lswipl 
```

**Comment by DomT4** [comment]
Sometimes we sandbox formulae inside `libexec` and selectively only symlink/exec script the binaries. 

This particular formula was moved to `libexec` two years ago [here](https://github.com/homebrew/homebrew/commit/e2f3d64e0293756e641f162da3e4430a59a1ea48). Homebrew symlinks things from the formula prefix to the common prefix, and `swi-prolog` threw a tantrum about that. See also: #24323.

If that has been fixed we can consider moving it back. Please feel free to investigate and file a PR at `Homebrew/x11` where this formula now resides as desired, Thanks!
