### ISSUE TITLE
subversion error: requires zlib when --with-python, library not found for -lsocket 

### ISSUE THREAD

**Issue by botanize** [Homebrew/homebrew#41255]
I get the following error when attempting ```brew install subversion --with-python```

  >checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for inflate in -lz... no
configure: error: subversion requires zlib

running ```brew install -vd subversion --with-python``` results in the following error in config.log:
  >configure:18124: /usr/bin/clang -o conftest -Werror=unknown-warning-option -Os -w -pipe -march=native -mmacosx-version-min=10.9   -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/readline/include -F/usr/local/Frameworks  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names   -L/usr/local/Cellar/subversion/1.8.13/libexec/serf/lib conftest.c -lsocket   >&5
ld: library not found for -lsocket
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by DomT4** [comment]
Which system are you using? `zlib` is installed by default on OS X.

Can you `brew gist-logs subversion`?

**Comment by botanize** [comment]
Max OS X 10.9.5

https://gist.github.com/0a8be7d9e2ce947d5aa9

**Comment by DomT4** [comment]
You have `zlib` [libs in](https://gist.github.com/botanize/0a8be7d9e2ce947d5aa9#file-doctor-out-L19-L21) `/usr/local/lib`. It's probably picking up the headers from `/usr/include` but failing to determine the correct libs.

Would suggest you move or remove the existing `zlib` libraries in `/usr/local/lib` and try again.
