### ISSUE TITLE
python formula: pip install doesn't install anything

### ISSUE THREAD

**Issue by Drewshg312** [Homebrew/homebrew#41253]
Installed python from homebrew on yosemite:

    $ brew install python
    ==> Downloading https://homebrew.bintray.com/bottles/python-2.7.10.yosemite.bottle.2.tar.gz
    ######################################################################## 100.0%
    ==> Pouring python-2.7.10.yosemite.bottle.2.tar.gz
    ==> Caveats
    Pip and setuptools have been installed. To update them
      pip install --upgrade pip setuptools
    
    You can install Python packages with
      pip install <package>
    
    They will install into the site-package directory
      /usr/local/lib/python2.7/site-packages
    
    See: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-and-Python.md
    
    
    .app bundles were installed.
    Run `brew linkapps python` to symlink these to /Applications.
    ==> /usr/local/Cellar/python/2.7.10/bin/python -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python/2.7.10/bin --insta
    ==> /usr/local/Cellar/python/2.7.10/bin/python -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python/2.7.10/bin --insta
    ==> Summary
    🍺  /usr/local/Cellar/python/2.7.10: 4777 files, 78M

When trying to install Django getting this:

    $ pip install django
    Collecting django
      Could not find a version that satisfies the requirement django (from versions: )
    No matching distribution found for django

Could anyone tell what is the problem?
Thank you!

**Comment by tdsmith** [comment]
Works for me. Do you have a pip configuration file that uses an index other than pypi?

**Comment by tdsmith** [comment]
The output of `pip install -vvv django` would be helpful if you want to paste-bin it.

**Comment by Drewshg312** [comment]
Thanx for response

The output:

    $ pip install -vvv django
    Starting new HTTPS connection (1): pypi.python.org
    There was an error checking the latest version of pip
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/utils/outdated.py", line 122, in pip_version_check
        headers={"Accept": "application/json"},
      File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/_vendor/requests/sessions.py", line 477, in get
        return self.request('GET', url, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/download.py", line 373, in request
        return super(PipSession, self).request(method, url, *args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/_vendor/requests/sessions.py", line 465, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/_vendor/requests/sessions.py", line 573, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/_vendor/cachecontrol/adapter.py", line 46, in send
        resp = super(CacheControlAdapter, self).send(request, **kw)
      File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/_vendor/requests/adapters.py", line 431, in send
        raise SSLError(e, request=request)
    SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
    Collecting django
      Getting page https://pypi.python.org/simple/django/
      Starting new HTTPS connection (1): pypi.python.org
      Could not fetch URL https://pypi.python.org/simple/django/: connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) - skipping
      1 location(s) to search for versions of django:
      * https://pypi.python.org/simple/django/
      Getting page https://pypi.python.org/simple/django/
      Starting new HTTPS connection (2): pypi.python.org
      Could not fetch URL https://pypi.python.org/simple/django/: connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) - skipping
      Could not find a version that satisfies the requirement django (from versions: )
    Cleaning up...
    No matching distribution found for django
    Exception information:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/basecommand.py", line 223, in main
        status = self.run(options, args)
      File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/commands/install.py", line 280, in run
        requirement_set.prepare_files(finder)
      File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/req/req_set.py", line 317, in prepare_files
        functools.partial(self._prepare_file, finder))
      File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/req/req_set.py", line 304, in _walk_req_to_install
        more_reqs = handler(req_to_install)
      File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/req/req_set.py", line 439, in _prepare_file
        req_to_install.populate_link(finder, self.upgrade)
      File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/req/req_install.py", line 244, in populate_link
        self.link = finder.find_requirement(self, upgrade)
      File "/usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/index.py", line 563, in find_requirement
        'No matching distribution found for %s' % req
    DistributionNotFound: No matching distribution found for django

**Comment by tdsmith** [comment]
pip is having trouble establishing an HTTPS connection to pypi. You may be able to get some information about that with `echo | /usr/local/opt/openssl/bin/openssl s_client -connect pypi.python.org:443`. Do you need to configure a proxy?

**Comment by Drewshg312** [comment]
Well

    $ echo | /usr/local/opt/openssl/bin/openssl s_client -connect pypi.python.org:443
    CONNECTED(00000003)
    depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA
    verify return:1
    depth=1 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 Extended Validation Server CA
    verify return:1
    depth=0 businessCategory = Private Organization, jurisdictionC = US, jurisdictionST = Delaware, serialNumber = 3359300, street = 16 Allen Rd, postalCode = 03894-4801, C = US, ST = NH, L = "Wolfeboro,", O = Python Software Foundation, CN = www.python.org
    verify return:1
    ---
    Certificate chain
     0 s:/businessCategory=Private Organization/jurisdictionC=US/jurisdictionST=Delaware/serialNumber=3359300/street=16 Allen Rd/postalCode=03894-4801/C=US/ST=NH/L=Wolfeboro,/O=Python Software Foundation/CN=www.python.org
       i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA
     1 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA
       i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
    ---
    Server certificate
    -----BEGIN CERTIFICATE-----
    EwczMzU5MzAwMRQwEgYDVQQJEwsxNiBBbGxlbiBSZDETMBEGA1UEERMKMDM4OTQt
    NDgwMTELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAk5IMRMwEQYDVQQHEwpXb2xmZWJv
    uEG9FtgGAo+3hKm99U8UKKVAgMBAAGjggRhMIIEXTAfBgNVHSMEGDAWgBQ901Cl
    1qCt7vNKYApl0yHU+PjWDzAdBgNVHQ4EFgQUTWfmKThuIBhkZX4B3yNf+DpBqokw
    ggEUBgNVHREEggELMIIBB4IOd3d3LnB5dGhvbi5vcmeCCnB5dGhvbi5vcmeCD3B5
    cGkucHl0aG9uLm9yZ4IPZG9jcy5weXRob24ub3JnghN0ZXN0cHlwaS5weXRob24u
    b3Jngg9idWdzLnB5dGhvbi5vcmeCD3dpa2kucHl0aG9uLm9yZ4INaGcucHl0aG9u
    Lm9yZ4IPbWFpbC5weXRob24ub3JnghRwYWNrYWdpbmcucHl0aG9uLm9yZ4IQcHl0
    aG9uaG9zdGVkLm9yZ4IUd3d3LnB5dGhvbmhvc3RlZC5vcmeCFXRlc3QucHl0aG9u
    aG9zdGVkLm9yZ4IMdXMucHljb24ub3Jngg1pZC5weXRob24ub3JnMA4GA1UdDwEB
    /wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwdQYDVR0fBG4w
    bDA0oDKgMIYuaHR0cDovL2NybDMuZGlnaWNlcnQuY29tL3NoYTItZXYtc2VydmVy
    LWcxLmNybDA0oDKgMIYuaHR0cDovL2NybDQuZGlnaWNlcnQuY29tL3NoYTItZXYt
    c2VydmVyLWcxLmNybDBCBgNVHSAEOzA5MDcGCWCGSAGG/WwCATAqMCgGCCsGAQUF
    BwIBFhxodHRwczovL3d3dy5kaWdpY2VydC5jb20vQ1BTMIGIBggrBgEFBQcBAQR8
    MHowJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBSBggrBgEF
    BQcwAoZGaHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0U0hBMkV4
    dGVuZGVkVmFsaWRhdGlvblNlcnZlckNBLmNydDAMBgNVHRMBAf8EAjAAMIIBfgYK
    KwYBBAHWeQIEAgSCAW4EggFqAWgAdQCkuQmQtBhYFIe7E6LMZ3AKPDWYBPkb37jj
    d80OyA3cEAAAAU21GPxpAAAEAwBGMEQCIGLF4WOctBDAHh+b90vonuTLiIUUwk/Q
    Qj1GhWTwdVrIYKr70tfuhQ+ZzL3XQo+VEoYhwbKRM=
    -----END CERTIFICATE-----
    subject=/businessCategory=Private Organization/jurisdictionC=US/jurisdictionST=Delaware/serialNumber=3359300/street=16 Allen Rd/postalCode=03894-4801/C=US/ST=NH/L=Wolfeboro,/O=Python Software Foundation/CN=www.python.org
    issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA
    ---
    No client certificate CA names sent
    Peer signing digest: SHA512
    Server Temp Key: ECDH, P-256, 256 bits
    ---
    SSL handshake has read 4016 bytes and written 444 bytes
    ---
    New, TLSv1/SSLv3, Cipher is ECSHE-RSA-AES128-GCM-SHA256
    Server public key is 2048 bit
    Secure Renegotiation IS supported
    Compression: NONE
    Expansion: NONE
    No ALPN negotiated
    SSL-Session:
        Protocol  : TLSv1.2
        Cipher    : ECDHE-RSA-AES128-GCM-SHA256
        Session-ID: 246E412D153CB39830BA0EDE36DDE4E20AD64A41EDF5707819843CD5DC8864
        Session-ID-ctx:
        Master-Key: 9C672E22FE792BA13FE567537DE27EBBFB0CF51F2AEF920FCE361CDB962D5A94485037538AECEF1
        Key-Arg   : None
        PSK identity: None
        PSK identity hint: None
        SRP username: None
        TLS session ticket lifetime hint: 1200 (seconds)
        TLS session ticket:
        0000 - 63 cc 77 4a 00 db 2c 42-2e 8f 76 23 dd a9 ae 53   c.wJ..,B..v#...S
        0010 - fb a5 23 7d 19 e5 46 e8-8d 7f 16 0b d4 fa e6 bb   ..#}..F.........
        0020 - 12 eb 38 88 86 3f 60 02-02 19 c6 e0 87 40 bc e9   ..8..?`......@..
        0030 - 17 f5 6e 1c 3f 4a 19 51-f  0b 8c a9 2e 91 8f 38   ..n.?J........8
        0040 - ee 08 ad 7f cc 13 28 b9-17 12 35 22 c5 92 ad e0   ......(...5"....
        0050 - 7a 63 38 77 84 a4 3b bd-c7 0d 28 a8 c8 3a bd 1a   zc8w..;...(..:..
        0060 - 97 67 57 59 65 82 51 0a-4a fd 5f 4b 4a 08 74 3b   .gsse.Q.J._KJ.t;
        0070 - ac 0f ce e6 61 17 8f ff-06 d1 9f e0 11 fc 71 36   ....a.........q6
        0080 - 71 66 e5 4d 88 a2 36 2-c2  45 f2 e6 08 d5 b7 c8   qf.M..6#.E......
        0090 - 39 88 e8 16 0c cc 45 4f-86 60 66 f4 63 8a 9f 6f   9.....EO.`f.c..o
    
        Start Time: 1435778712
        Timeout   : 300 (sec)
        Verify return code: 0 (ok)
    ---
    DONE

**Comment by tdsmith** [comment]
Well, that looks okay. Just to confirm, what's `pip -V` report?

**Comment by Drewshg312** [comment]
$ pip -V
    pip 7.0.3 from /usr/local/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg (python 2.7)

**Comment by Drewshg312** [comment]
any suggestions?

**Comment by tdsmith** [comment]
Not presently, no.

**Comment by Drewshg312** [comment]
Would be great to have an option to ignore certificate chek... So is it a problem with my certificate?

**Comment by tdsmith** [comment]
If you run `set | grep PROXY` do you see anything? Do you have a `/Library/Application Support/pip/pip.conf` or `~/.pip/pip.conf`?

**Comment by Drewshg312** [comment]
Nothing, no, no

**Comment by tdsmith** [comment]
Sorry, should have been `set | grep -i PROXY` -- no luck there, I imagine?

The next thing to do is to try and use the requests library to touch pypi and see if you can reproduce the error outside of pip.

**Comment by Drewshg312** [comment]
`set | grep -i PROXY` - same result - nothing((

**Comment by Drewshg312** [comment]
you know what, i dont know if it helps, but I'm getting this when do:

    $ easy_install virtualenv
    Searching for virtualenv
    Reading https://pypi.python.org/simple/virtualenv/
    Download error on https://pypi.python.org/simple/virtualenv/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'virtualenv' (maybe misspelled?)
    Scanning index of all packages (this may take a while)
    Reading https://pypi.python.org/simple/
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    No local packages or download links found for virtualenv
    error: Could not find suitable distribution for Requirement.parse('virtualenv')

**Comment by Drewshg312** [comment]
Sorry, I'm newbie... Could you be more detailed about "...The next thing to do is to try and use the requests library to touch pypi and see if you can reproduce the error outside of pip..."

**Comment by tdsmith** [comment]
Open a Python session and try this:
```
import pip._vendor.requests as requests
response_certifi = requests.get("https://pypi.python.org")
response_openssl = requests.get("https://pypi.python.org", verify="/usr/local/etc/openssl/cert.pem")
print response_certifi, reponse_openssl
```

and run this at the shell: `ls /usr/local/lib/python2.7/site-packages/certifi*`

**Comment by Drewshg312** [comment]
$ ls /usr/local/lib/python2.7/site-packages/certifi*
    ls: /usr/local/lib/python2.7/site-packages/certifi*: No such file or directory

**Comment by tdsmith** [comment]
I typoed `response_openssl` in the `print` line but I'm surprised `response_certifi` worked :/

Can you try again, adding `verify=True` to the get invocation in the `response_certifi` line so that it looks like `response_certifi = requests.get("https://pypi.python.org", verify=True)`?

**Comment by Drewshg312** [comment]
There you go:    

    $ python
    Python 2.7.10 (default, Jun 10 2015, 19:42:47)
    [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pip._vendor.requests as requests
    >>> response_certifi = requests.get("https://pypi.python.org", verify=True)
    >>> response_openssl = requests.get("https://pypi.python.org", verify="/usr/local/etc/openssl/cert.pem")
    >>> print response_certifi, response_openssl
    <Response [200]> <Response [200]>
    >>>


    $ ls /usr/local/lib/python2.7/site-packages/certifi*
    ls: /usr/local/lib/python2.7/site-packages/certifi*: No such file or directory

**Comment by tdsmith** [comment]
Which of these files exist? 

    "/etc/ssl/certs/ca-certificates.crt",
    "/etc/pki/tls/certs/ca-bundle.crt",
    "/etc/ssl/ca-bundle.pem",
    "/etc/ssl/cert.pem",
    "/usr/local/share/certs/ca-root-nss.crt",
    "/usr/local/etc/openssl/cert.pem",

(from https://github.com/pypa/pip/blob/40242fe4db24d14362937c10e77fd95dfd97f3c9/pip/locations.py#L18-L36)

**Comment by Drewshg312** [comment]
Exist only these ones:
"/etc/pki/tls/certs/ca-bundle.crt",
"/usr/local/etc/openssl/cert.pem",

There is no directory /etc/ssl/. I use openssl from homebrew as well

**Comment by tdsmith** [comment]
Aha! I bet the problem goes away if you rename the first one (in /etc).
That's not a system file so you won't break anything that belongs to the
OS.

Tim
Sent from mobile

**Comment by Drewshg312** [comment]
Sorry, how should I rename it and actually is it ok not to have /etc/ssl directory? and shouldn't openssl from homebrew bring all necessary stuff in /usr/local/etc/ssl?? What exactly should I do? thank you very much for your help and patience!

**Comment by Drewshg312** [comment]
Wow! It works, but why? Wtf? Could you please explain what is this certificate for and when do I need it? Or maybe do I need to get rid of it? Or in which cases I need to change it's name back?? Fuck I'm so dumb... I understand nothing about these certificates (((

**Comment by Drewshg312** [comment]
And on my laptop I actually have also: `/etc/openssl/cert.pem` Fuck! So many questions...

**Comment by tdsmith** [comment]
The file in /etc/pki was not installed by Homebrew and is not needed by Homebrew (or by anything that comes with OS X). You probably installed something at some point that put it there. It may no longer be necessary and it appears to be out of date. It does not usually exist on OS X. All of Homebrew's openssl stuff lives in /usr/local.

Pip searches for a bundle of root certificates to use to verify website TLS certificates. It uses the first bundle it finds and the /etc/pki location is earlier in the search list than the Homebrew location, so it used that one on your system. Since it's out of date, certificate validation failed. After you renamed it, pip couldn't find it, and so it found the newer Homebrew certificate bundle instead.

**Comment by Drewshg312** [comment]
thank you so much!!!

**Comment by vikas027** [comment]
@Drewshg312 I also had a similar issue. Renaming file `/etc/ssl/certs/ca-certificates.crt` helped me. Thanks @tdsmith .

**Comment by Yagwar** [comment]
Hey!!
Thanks a lot. I also renamed ca-certificates.crt and it works.
@tdsmith @Drewshg312 @vikas027
