### ISSUE TITLE
mysql-proxy 0.8.5 failed to build with mysql-connector-c 6.1.6

### ISSUE THREAD

**Issue by teslamint** [Homebrew/homebrew#41263]
log: https://gist.github.com/anonymous/58c090c375573ce6c61e

I can compile mysql-proxy without problem with percona-server and mysql.

**Comment by dunn** [comment]
Sorry nobody got back to you sooner! I can reproduce this, and unless I'm much mistaken it's a known issue with mysql-connector-c: http://bugs.mysql.com/bug.php?id=78028

I'm not sure what the pace of releases is, and if it's worth adding a special requirement to mysql-proxy or even a caveat.

**Comment by DomT4** [comment]
`mysql-proxy` went to the boneyard recently due to refusing to build against the new MySQL with no upstream fix apparently imminent. If it works again at some point, happy to look into this again.
