### ISSUE TITLE
Postgres 9.4 Installation fails (Resolved with inputs from #26544)

### ISSUE THREAD

**Issue by AshNaur** [Homebrew/homebrew#41264]
**OS X Version 10.8.5**
## *brew install postgresql* fails with below error:

==> /usr/local/Cellar/postgresql/9.4.4/bin/initdb /usr/local/var/postgres
  Reason: image not found
no data was returned by command ""/usr/local/Cellar/postgresql/9.4.4/bin/postgres" -V"
The program "postgres" is needed by initdb but was not found in the
same directory as "/usr/local/Cellar/postgresql/9.4.4/bin/initdb".
Check your installation.

**Now manually running => /usr/local/Cellar/postgresql/9.4.4/bin/postgres -V**

dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/postgresql/9.4.4/bin/postgres
  Reason: image not found

**The solution to this error has been discussed [ here ](https://github.com/Homebrew/homebrew/issues/26544).**

**Checked the output of:**
*otool -L /usr/bin/install_name_tool*
/usr/bin/install_name_tool (architecture i386):
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 88.3.3)
/usr/bin/install_name_tool (architecture ppc):
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 88.3.3)

**Did a backup of install_name_tool and replaced with colleague's MacBook install_name_tool file**
**So specific to Postgres 9.4 installation:**
*brew reinstall openssl*
==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2c: 463 files, 18M

*brew install postgresql*
==> Summary
🍺  /usr/local/Cellar/postgresql/9.4.4: 3014 files, 40M

Thanks for the hint from Issue #26544 ! 
--Ashish

**Comment by mikemcquaid** [comment]
Seems you've resolved the issue, thanks for letting us know.
