### ISSUE TITLE
sedna fails to build on 10.10.3

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew#41276]
I installed *all* formulae from the core, this is one of the issues I ran into. I’m at work, will check tonight.

```
$ brew install sedna
==> Downloading http://www.modis.ispras.ru/FTPContent/sedna/current/sedna-3.5.161-src-darwin.tar.gz
######################################################################## 100,0%
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/C
==> make install
make[4]: *** [install] Error 2
make[3]: *** [install-recursive] Error 1
make[2]: *** [libs/libedit-20100424-3.0/include/editline/readline.h] Error 2
make[1]: *** [libs/CMakeFiles/custom_libedit.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
```

Logs: https://gist.github.com/a25e4a1a6aa19d333bf4

**Comment by dunn** [comment]
It's something upstream need to fix and probably won't: http://sourceforge.net/p/sedna/bugs/99/

But it fails with GCC also and differently: https://gist.github.com/dunn/efdf1c892401f25a1d20#file-02-make-L1046

**Comment by DomT4** [comment]
I spent two hours on this a couple of nights ago and couldn't get stable to work. It will compile if you use the `head` build and enforce using Homebrew's `gcc` as the compiler, and Homebrew's `bison` and `flex` during compile.

IMO, either move it to `head-only` until those issues are resolved, or boneyard it.

**Comment by dunn** [comment]
:skull: imo
