### ISSUE TITLE
uim fails to build on 10.{9,10,11}

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew#41278]
I installed *all* formulae from the core, this is one of the issues I ran into. I’m at work, will check tonight.

```
$ brew install uim
==> Downloading https://uim.googlecode.com/files/uim-1.6.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/uim-1.6.0.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/uim/1.6.0
==> make install
make[2]: *** [libuim_x_util_la-uim-x-kana-input-hack.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: compile:  clang -DHAVE_CONFIG_H -DPKGDATADIR=\"/usr/local/Cellar/uim/1.6.0/share/uim\" -DSCMLIBDIR=\"/usr/local/Cellar/uim/1.6.0/share/uim/lib\" -I. -I../replace -I../uim -I.. -g -O2 -pedantic -pipe -Wall -Wchar-subscripts -Wmissing-declarations -Wredundant-decls -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wcast-align -Wsign-compare -Wno-long-long -Wno-overlength-strings -no-cpp-precomp -DNDEBUG -Wno-redundant-decls -Wno-unused-function -c counted-init.c  -fno-common -DPIC -o .libs/libuim_counted_init_la-counted-init.o
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting
```

Logs: https://gist.github.com/0bd7901e99677fbe755b

**Comment by tschoonj** [comment]
Try adding `:x11` as formula dependency

**Comment by bfontaine** [comment]
Thanks @tschoonj, it fixed the error :smile: 

However there’s now another one later in the process:

```
make[2]: `uim-module-manager' is up to date.
Error: /bin/sh: line 1: 89344 Segmentation fault: 11  LIBUIM_SYSTEM_SCM_FILES=/private/tmp/uim20150711-68907-1hjqttd/uim-1.6.0/sigscheme/lib LIBUIM_SCM_FILES=/private/tmp/uim20150711-68907-1hjqttd/uim-1.6.0/scm LIBUIM_PLUGIN_LIB_DIR=/private/tmp/uim20150711-68907-1hjqttd/uim-1.6.0/uim/.libs UIM_DISABLE_NOTIFY=1 ../uim/uim-module-manager --path ../scm --register "skk" "tcode" "trycode" "tutcode" "byeoru" "latin" "elatin" "xmload" "pyload" "hangul" "viqr" "ipa-x-sampa" "look" "ajax-ime" "social-ime"
make[1]: *** [installed-modules.scm] Error 139
make: *** [install-recursive] Error 1
```

Logs: https://gist.github.com/238c50b35a9a3ef80957

#40604 might be the answer.

**Comment by tschoonj** [comment]
No idea I’m afraid. This will have to be taken up with the developers.




Dr. Tom Schoonjans
Research Fellow

Bundesanstalt für Materialforschung und -prüfung (Federal Institute for Materials Research and Testing)
Richard-Willstätter-Strasse 11, 12489 Berlin
Germany

Telephone +49 (0) 30-8104-5612

Tom.Schoonjans@bam.de<mailto:Tom.Schoonjans@bam.de>
www.bam.de


On 11 Jul 2015, at 23:00, Baptiste Fontaine <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @tschoonj<https://github.com/tschoonj>, it fixed the error [:smile:]

However there’s now another one later in the process:

make[2]: `uim-module-manager' is up to date.
Error: /bin/sh: line 1: 89344 Segmentation fault: 11  LIBUIM_SYSTEM_SCM_FILES=/private/tmp/uim20150711-68907-1hjqttd/uim-1.6.0/sigscheme/lib LIBUIM_SCM_FILES=/private/tmp/uim20150711-68907-1hjqttd/uim-1.6.0/scm LIBUIM_PLUGIN_LIB_DIR=/private/tmp/uim20150711-68907-1hjqttd/uim-1.6.0/uim/.libs UIM_DISABLE_NOTIFY=1 ../uim/uim-module-manager --path ../scm --register "skk" "tcode" "trycode" "tutcode" "byeoru" "latin" "elatin" "xmload" "pyload" "hangul" "viqr" "ipa-x-sampa" "look" "ajax-ime" "social-ime"
make[1]: *** [installed-modules.scm] Error 139
make: *** [install-recursive] Error 1


Logs: https://gist.github.com/238c50b35a9a3ef80957

#40604<https://github.com/Homebrew/homebrew/pull/40604> might be the answer.
