### ISSUE TITLE
wps2odt fails to build on 10.10.3

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew#41279]
I installed *all* formulae from the core, this is one of the issues I ran into. I’m at work, will check tonight.

```
$ brew install wps2odt
==> Installing dependencies for wps2odt: libgsf, libwpd, libwps
…
==> Installing wps2odt
==> Downloading https://downloads.sourceforge.net/project/libwps/wps2odt/wps2odt-0.2.0/wps2odt-0.2.0
Already downloaded: /Library/Caches/Homebrew/wps2odt-0.2.0.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/wps2odt/0.2.0
installed software in a non-standard prefix.

Alternatively, you may set the environment variables WPS2ODT_CFLAGS
and WPS2ODT_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

READ THIS: https://git.io/brew-troubleshooting
```

Logs: https://gist.github.com/72fd291f368ba406767c

**Comment by bfontaine** [comment]
The current error:

```
checking for WPS2ODT... no
configure: error: Package requirements (
libwps-0.2 >= 0.2.0
libwpd-stream-0.9 >= 0.2.0
libwpd-0.9 >= 0.9.0
) were not met:

No package 'libwps-0.2' found
No package 'libwpd-stream-0.9' found
No package 'libwpd-0.9' found
```

I was able to fix the issues with `libwps` and `libwpd` but can’t find `libwpd-stream`. It relies on specific versions of the libraries but Homebrew has more up-to-date ones. `wps2odt` is not maintained anymore as it was merged in WriterPerfect 3 years ago.

```diff
diff --git a/Library/Formula/wps2odt.rb b/Library/Formula/wps2odt.rb
index 97ca4e5..b125304 100644
--- a/Library/Formula/wps2odt.rb
+++ b/Library/Formula/wps2odt.rb
@@ -8,8 +8,15 @@ class Wps2odt < Formula
 
   depends_on 'pkg-config' => :build
   depends_on 'libwps'
+  depends_on "libwpd"
 
   def install
+    libwps = "libwps-#{Formula["libwps"].version.to_s.sub(/\.\d+$/, "")}"
+    libwpd = "libwpd-#{Formula["libwpd"].version.to_s.sub(/\.\d+$/, "")}"
+
+    inreplace "configure", "libwps-0.2", libwps
+    inreplace "configure", "libwpd-0.9", libwpd
+
     system "./configure", "--disable-debug", "--disable-dependency-tracking",
                           "--prefix=#{prefix}"
     system "make install"
```

**Comment by DomT4** [comment]
`wps2odt` was added four years ago and hasn't been touched since, aside Jack adding a missing dep in 2013. Given it isn't maintained any more, IMO, boneyard it.

**Comment by bfontaine** [comment]
@DomT4 I take this as a challenge, I’ll try to get it to build but if I fail I’ll boneyard it :)

**Comment by fosnola** [comment]
Hello,
the repository wps2odt was deprecated when the support of libwps was added in writerperfect (many year ago)...

Currently to build wps2odt, you will need to install librevenge, libwps, libodfgen and writerperfect ( see http://sourceforge.net/p/libwps/wiki/Developers/  and/or http://www.documentliberation.org/projects/ ).

Note:
-as libwps-0.4 can also convert some spreadsheet/database files, this will also install wks2ods

**Comment by dunn** [comment]
Time to :skull: ?

**Comment by fosnola** [comment]
Yes, it seems a good idea to declare the wps2odt's module as dead ...
