### ISSUE TITLE
brew does not recognize $EDITOR

### ISSUE THREAD

**Issue by achikin** [Homebrew/homebrew#41284]
→ brew update
Updated Homebrew from c7ea17f9 to c7ea17f9.
→ brew edit tree
Warning: Using vim because no editor was set in the environment.
This may change in the future, so we recommend setting EDITOR, VISUAL,
or HOMEBREW_EDITOR to your preferred text editor.
→ echo $EDITOR
vim
→ brew --version
0.9.5

**Comment by bfontaine** [comment]
Does `EDITOR=vim brew edit tree` print a warning?

**Comment by tdsmith** [comment]
Is EDITOR `export`ed?

**Comment by achikin** [comment]
@bfontaine it isn't. @tdsmith that was the issue, it was not exported. Thank you!
