### ISSUE TITLE
pulledpork formula: issue with ssl sertificates

### ISSUE THREAD

**Issue by Drewshg312** [Homebrew/homebrew#41300]
Hi guys!
I've found that there is an old version of pulledpork (0.7.0 Swine Flu) in homebrew when in svn it is new  version(0.7.1 Swine Flu with a side of Ebola) available. Can be downloaded this way:

    $ svn checkout http://pulledpork.googlecode.com/svn/trunk/ pulledpork-read-only_0.7.1

 The main difference (to me) is that new version has `-w` flag which allows to ignore ssl certificate check when updating rules... This is the only way to get it work for some users... So would be nice to have it in homebrew... Could anyone update the formula or help me to do this... Thank you!

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by Drewshg312** [comment]
Thank you very much for response!
Should I change the formula first??
Here is the formula:
    require 'formula'
    
    class Pulledpork < Formula
      desc "Snort rule management"
      homepage 'http://code.google.com/p/pulledpork/'
      url 'https://pulledpork.googlecode.com/files/pulledpork-0.7.0.tar.gz'
      sha1 'fd7f2b195b473ba80826c4f06dd6ef2dd445814e'
    
      depends_on 'Switch' => :perl
      depends_on 'Crypt::SSLeay' => :perl
    
      def install
        bin.install 'pulledpork.pl'
        doc.install Dir['doc/*']
        etc.install Dir['etc/*']
      end
    end

**Comment by DomT4** [comment]
As far as I can see, you're essentially asking if we can add a `head` so you can get the latest from upstream?

**Comment by Drewshg312** [comment]
Lol... probably... I'm trying to figure out how generaly does it work... Should I change it locally or you can do what you said? I kinda don't understand completely what does pull request mean... I'm very new to git.

**Comment by DomT4** [comment]
I can make the change if you wish, but if you'd prefer to be talked through how to set up pull requests and similar I'm happy to help with that. This is the change we'd need to make:

```diff
diff --git a/Library/Formula/pulledpork.rb b/Library/Formula/pulledpork.rb
index 2de7d68..346c532 100644
--- a/Library/Formula/pulledpork.rb
+++ b/Library/Formula/pulledpork.rb
@@ -5,6 +5,7 @@ class Pulledpork < Formula
   homepage 'http://code.google.com/p/pulledpork/'
   url 'https://pulledpork.googlecode.com/files/pulledpork-0.7.0.tar.gz'
   sha1 'fd7f2b195b473ba80826c4f06dd6ef2dd445814e'
+  head "http://pulledpork.googlecode.com/svn/trunk/"

   depends_on 'Switch' => :perl
   depends_on 'Crypt::SSLeay' => :perl
```

A pull request is essentially a way of saying "Here's a change I'd like to make". Presuming you're operating out of `/usr/local` from scratch you'd do something like this:
 
* Hit the "Fork" button in the top right of the repo.
* `cd /usr/local`
* `git add remote me https://github.com/Drewshg312/homebrew`
* `brew update`
* `git checkout -b pork`
* `brew edit pulledpork`
* Add the head line as the `diff` displays above
* `git add -A && git commit -m "pulledpork: add head"`
* `git push me pork`
* Go to https://github.com/Homebrew/homebrew and you should get a green drop-down box appear with "Create a pull request" or similar. It'll look like this:

![screen shot 2015-07-02 at 22 47 08](https://cloud.githubusercontent.com/assets/6998367/8488667/4b974046-210c-11e5-9f82-22c13218e64c.png)

* Hit the green button there. You'll end up with a box like this:

![screen shot 2015-07-02 at 22 48 04](https://cloud.githubusercontent.com/assets/6998367/8488687/6d99cfa6-210c-11e5-9166-010a21bf7fd0.png)

* Hit the "Create Pull Request" button.
* Done! :tada:

**Comment by Drewshg312** [comment]
Man! That's awesome! It's actually not a first time you are helping me! Thank you so much! I'll try it by myself and ask u questions if I'll have some... I appreciate your help!

**Comment by Drewshg312** [comment]
well first getting this:

    $ git add remote me https://github.com/Drewshg312/homebrew.git
    fatal: pathspec 'remote' did not match any files

**Comment by tdsmith** [comment]
Should be `remote add`, not `add remote`.

**Comment by Drewshg312** [comment]
Thank you!

**Comment by Drewshg312** [comment]
Do I need to add to existing formula only this line:

    diff --git a/Library/Formula/pulledpork.rb b/Library/Formula/pulledpork.rb

Or I need to modify the formula to look exactly like this:

    diff --git a/Library/Formula/pulledpork.rb b/Library/Formula/pulledpork.rb
    index 2de7d68..346c532 100644
    --- a/Library/Formula/pulledpork.rb
    +++ b/Library/Formula/pulledpork.rb
    @@ -5,6 +5,7 @@ class Pulledpork < Formula
       homepage 'http://code.google.com/p/pulledpork/'
       url 'https://pulledpork.googlecode.com/files/pulledpork-0.7.0.tar.gz'
       sha1 'fd7f2b195b473ba80826c4f06dd6ef2dd445814e'
    +  head "http://pulledpork.googlecode.com/svn/trunk/"

**Comment by DomT4** [comment]
> Should be remote add, not add remote.

:see_no_evil:. Thanks for spotting that Tim.

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew/commit/891f6e3707842a7898f1eab3c196ad843ff77cf0 :tada:.
