### ISSUE TITLE
ejabberdctl cookie issue

### ISSUE THREAD

**Issue by cpcowart** [Homebrew/homebrew#41303]
The launchd plist distributed with ejabberd includes the following config:

  <key>EnvironmentVariables</key>
  <dict>
    <key>HOME</key>
    <string>/usr/local/var/lib/ejabberd</string>
  </dict>

This causes the erlang cookie to be created in /usr/local/var/lib/ejabberd/.erlang.cookie.

Any attempt by the user to use "ejabberdctl", including to register accounts or check the daemon's status will fail with the message: 

% ejabberdctl status
Failed RPC connection to the node ejabberd@localhost: nodedown

This is because HOME is different, and ejabberdctl creates a different erlang cookie in ~/.erlang.cookie.

A workaround is to specify HOME manually in the environment when running the command:
% HOME=/usr/local/var/lib/ejabberd ejabberdctl status
The node ejabberd@localhost is started with status: started
ejabberd 15.04 is running in that node

This is janky at best.

Either HOME should not be overwritten or the ejabberdctl script should point HOME to the same place that the LaunchAgent does.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by DomT4** [comment]
Welcome a PR here, Thanks.
