### ISSUE TITLE
go --HEAD does not work because of changes in go 1.5

### ISSUE THREAD

**Issue by drewwells** [Homebrew/homebrew#41304]
This is a ticket for discussions on how best to handle building go next. The --head option is a good place to get started on working on the kinks.

I just stepped through this process on my machine, so hopefully I can help. Go will look for an environment variable where it expects to find a working Go >=1.4 toolchain. It will then build Go 1.5 from this and install `go` `godoc` to `$GOPATH/bin`. This is the Go 1.5 binary and what needs to be provided to the end user. The `GOROOT_BOOTSTRAP` environment variable is used to locate Go.

**Comment by DomT4** [comment]
There are some notes at the top of the `go` formula related to this discussion as well.

**Comment by DomT4** [comment]
IMO:

* Use a previous Homebrew bottle, 10.8's probably, to do the bootstrap. We can put this in a temporary path, either inside the `buildpath` or with `mktemp`, and then fiddling with the `$GOROOT_BOOTSTRAP` as necessary.
* Set `$GOPATH` as a temporary directory for the install as we do `go_resource`s and then `libexec.install` the directory  and symlink anything necessary back into the prefix's `bin`.

Will need some actual testing. We only go as far as discussing using bottles as resources very theoretically last time.

**Comment by drewwells** [comment]
Yeah I wasn't sure how possible that is. I'm having it build go1.4.2 from source. Once I get that working, I can see how to make it use a bottle instead.

**Comment by DomT4** [comment]
@mistydemeo may have some thoughts on this - Misty wrote most of the way we handle Go stuff. Using an upstream binary may be easier than using our bottles given how we bottle things, but in an ideal world we'd be able to not have to rely on an upstream binary.

**Comment by drewwells** [comment]
I'm taking a stab in the dark, but I think at a minimum that we need the `go` binary to bootstrap the process. Even with a fully built toolchain, it rebuilds one off the 1.4.2 binary maybe of the Go 1.5 code...

This is the hammer approach, download 1.4.2, build it, pass it to Go 1.5

**Comment by DomT4** [comment]
Fixed by #41305 & https://github.com/Homebrew/homebrew/commit/7ed0b5ffb7610de86663c3928cf72c4499b0772d.
