### ISSUE TITLE
Is it possible to declare the release notes url?

### ISSUE THREAD

**Issue by mindrones** [Homebrew/homebrew#41318]
Is there a way to declare a link to release notes?
Something like:

    ...
    version: 2.2.2
    release_notes: http://www.foo.com/releases/2.2.2
    ...

If not, it would be nice to have this, because one might read the release notes when running `brew info formula` to decide if upgrade or not.

I thought about `ohai` but that message would be printed in console at installation time I think, not by running `brew info formula`, right?

**Comment by mikemcquaid** [comment]
There is not I'm afraid.

**Comment by DomT4** [comment]
> I thought about ohai but that message would be printed in console at installation time I think, not by running brew info formula, right?

Correct. You could fail without confirmation the user wished to proceed via a requirement or option, but we wouldn't accept it in the core as it's fairly bad UX.

**Comment by mindrones** [comment]
OK thanks. Any chance this can be considered as a feature request?

**Comment by mikemcquaid** [comment]
We don't really keep feature requests open unless one of the maintainers is considering doing so in the short-term.

**Comment by DomT4** [comment]
It's unlikely, IMO.

Not everything has release notes, so it'd end up being applied very inconsistently which creates uncertainty for maintainers and new contributors, and sometimes upstream supply release notes but haven't updated them in 5 years, so on so forth. It'd be difficult to accurately check/enforce for each formula.

We provide an accessible way for people to access a project's homepage, via `brew home openssl` or such, which can be useful for checking update desire.

**Comment by mindrones** [comment]
OK thanks!
