### ISSUE TITLE
Replace troubleshooting link with prepopulated template

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/homebrew#41321]
e.g. https://github.com/Homebrew/homebrew/issues/new?title=Issue+building+FORMULA&body=%23%23+Followed+troubleshooting+steps%3A%0D%0A-+%5B+%5D+Ran+%60brew+update%60+and+tried+installing+again%0D%0A-+%5B+%5D+Ran+%60brew+doctor%60%2C+fixed+as+many+of+the+warnings+as+possible+and+tried+installing+again%0D%0A-+%5B+%5D+If+there+were+permission+errors+ran+%60sudo+chown+-R+%24%28whoami%29+%2Fusr%2Flocal%60+and+tried+installing+again%0D%0A%0D%0A%23%23+If+none+of+those+worked%3A%0D%0A%2A%2Areplace+this+line+with+%60brew+gist-logs+FORMULA%60+outputted+link%2A%2A

Click through to that link to see the example. Obviously the URL encoding is a bit of a mess/pain but we could automate it I'm sure so it's more readable in the source. I think this would help with the number of issues we get where people either haven't followed these steps or haven't provided the desired output.

@Homebrew/owners thoughts?

**Comment by bfontaine** [comment]
Interesting idea :+1: 

It would need fine-tuning to avoid errors (e.g. with taps).

**Comment by bfontaine** [comment]
Thinking about this, why not printing the first three bullet points directly in the console?

**Comment by DomT4** [comment]
It was getting to the point I was going to propose shoving the `gist-logs` command directly into the error message we print when formulae fail to install, particularly in an attempt to stop the bug reports where people post comments underneath like *"I have this issue too"* but don't provide the logs for us to compare against and we end up dealing with 2 or 3 little issues inside the one bug report.

Anything that means we get more consistent bug reporting is welcome. As you say, the URL could be made "nicer" but there are various methods to handle that.

**Comment by mikemcquaid** [comment]
@bfontaine we found the more we printed the less likely people were to read any of it, unfortunately.
