### ISSUE TITLE
Add `brew audit --online`

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/homebrew#41325]
This should be run by the bot (and maybe `--strict`) but be not run when an internet connection isn't present (to allow use without internet).

It should verify things like the URL being `https` (if it can be) and if the formula's homepage or head is a GitHub project verify the number of stars/forks (and maybe age of project) so that the bot or local runs can tell users if a project isn't secure/notable enough before we need to tell them.

It also helps to make these decisions seem less arbitrary when they are coded.

**Comment by bfontaine** [comment]
…and check that the homepage is accessible (no timeout/404/etc).

**Comment by mikemcquaid** [comment]
> …and check that the homepage is accessible (no timeout/404/etc).

:+1:

**Comment by mikemcquaid** [comment]
GitHub verification in 60722b27590cb530b74a78654bcf1be027d7b3df.

**Comment by bfontaine** [comment]
Homepage check: #41607.

**Comment by DomT4** [comment]
Stable URL check: #41614

**Comment by mikemcquaid** [comment]
I think we can mark this as completed.
