### ISSUE TITLE
mldonkey --with-x11 no longer works

### ISSUE THREAD

**Issue by mistydemeo** [Homebrew/homebrew#41355]
mldonkey's `--with-x11` option, which uses GTK+2, no longer works due to the switch to the Quartz backend. The build fails with:

```
In file included from src/gtk2/gui/x11/eggtrayicon.c:28:
src/gtk2/gui/x11/eggtrayicon.h:27:10: fatal error: 'gdk/gdkx.h' file not found
#include <gdk/gdkx.h>
         ^
```

As [noted by Macports](https://trac.macports.org/ticket/47568), it appears to be using X11-specific APIs that won't work when GTK+ is built with the Quartz backend.

**Comment by DomT4** [comment]
The only thing we've been able to do with options that require `gtkx` so far has been to remove the option, I believe. @tschoonj may know more.

**Comment by tschoonj** [comment]
looks bad indeed. You will have to drop that option :-(
