### ISSUE TITLE
Add Leanify?

### ISSUE THREAD

**Issue by nuomi1** [Homebrew/homebrew#41375]
Leanify is a lightweight lossless file minifier/optimizer. It removes unnecessary data (debug information, comments, metadata, etc.) and recompress the file to reduce file size. It will not reduce image quality at all.

https://github.com/JayXon/Leanify

**Comment by DomT4** [comment]
It looks like it'd qualify under our new formula requirements. Welcome a PR, if you're interested in submitting one.

**Comment by DomT4** [comment]
Closing here, but please feel free to submit a PR if you'd like to. Thanks!
