### ISSUE TITLE
Have formulae install lisp files in site-lisp/#{name}

### ISSUE THREAD

**Issue by dunn** [Homebrew/homebrew#41388]
Right now most formulae that install emacs lisp files just dump them in `share/"emacs/site-lisp"` which is symlinked to `HOMEBREW_PREFIX/"share/emacs/site-lisp"`.  Emacs package authors are pretty good about prefixing their `.el` files, but this might still cause conflicts, especially if formulae contain vendored lisp libraries (it's surprising that magit is the only formula in core that vendors `dash.el` right now).

What I'd like to do is require that formulae install their lisp files in a formula-specific directory.  This is what it would look like: https://github.com/Homebrew/homebrew/compare/Homebrew:master...dunn:site-lisp

If this is a good idea, but too large for a single PR, let me know and I'll split it up.

**Comment by dunn** [comment]
Come to think of it, vendored packages should be in `lib/vendor` instead of `site-lisp`.  But I still think this is a good idea.

**Comment by mikemcquaid** [comment]
Makes sense to me :+1:.

**Comment by dunn** [comment]
Should I do a PR for the caveats and cellar checks first?

**Comment by mikemcquaid** [comment]
Up to you!
