### ISSUE TITLE
sbcl failed to upgrade on 10.10.4

### ISSUE THREAD

**Issue by hebiyan** [Homebrew/homebrew#41399]
I tried to upgrade sbcl with --build-from-source option. But failed.
Error message says 
"incompatible encoding regexp match (ASCII-8BIT regexp with UTF-8 string)"

Please refer to [this](https://gist.github.com/hebiyan/dc9ce2188b0a81ba9c70) gist for more details.
Thank you.

**Comment by mistydemeo** [comment]
Should be fixed - thanks for the report!
