### ISSUE TITLE
docker and boot2docker: docker client server don't have the same version 

### ISSUE THREAD

**Issue by anthonygreen** [Homebrew/homebrew#41411]
Installing docker and boot2docker

    brew install docker boot2docker

Error response from daemon: client and server don't have same version (client : 1.19, server: 1.18)

    boot2docker init
    boot2docker up
    docker run hello-world

    Error response from daemon: client and server don't have same version (client : 1.19, server: 1.18)

**Comment by DomT4** [comment]
We updated them at the same time, they're both on `1.7.0`. Are you up-to-date and such? We had a similar issue with `docker-machine` recently in #40908.

**Comment by anthonygreen** [comment]
OS X 10.9.5

    docker: stable 1.7.0 (bottled), HEAD
    Pack, ship and run any application as a lightweight container
    https://www.docker.com/
    /usr/local/Cellar/docker/1.7.0 (9 files, 7.4M) *
      Poured from bottle
    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/docker.rb

    boot2docker: stable 1.7.0 (bottled), HEAD
    Lightweight Linux for Docker
    https://github.com/boot2docker/boot2docker-cli
    /usr/local/Cellar/boot2docker/1.7.0 (3 files, 7.3M) *
      Poured from bottle
    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boot2docker.rb

**Comment by anthonygreen** [comment]
Removing ALL running VMs and restarting the workstation seems to have fixed it.

**Comment by DomT4** [comment]
Awesome. Thanks for reporting the issue!
