### ISSUE TITLE
Sha256 in Scons formula doesn't match sourceforge tarball

### ISSUE THREAD

**Issue by timbodeit** [Homebrew/homebrew#41447]
Scons formula contains:

    url "https://downloads.sourceforge.net/scons/scons-2.3.5.tar.gz"
    sha256 "5b72f959cafbef81f408b503bc8e8d5cfc39f41fb5b629e9ff13bdf20a3eefe2"

The sha doesn't match the file to be downloaded under that url:

    $ curl -sL https://downloads.sourceforge.net/scons/scons-2.3.5.tar.gz | shasum -a 256                                                                                                                                                
    8a8993e1914801ace5ce83c92bf4c43127669750e9dec8eb93574e57729e9c42  -

The file I downloaded is a valid tarball (and not a sourceforge status page)

**Comment by bfontaine** [comment]
I can reproduce.

**Comment by tdsmith** [comment]
See #41440. Thanks!
