### ISSUE TITLE
Can't install node

### ISSUE THREAD

**Issue by rtuider** [Homebrew/homebrew#41449]
Hi guys,

when trying to install node under Redhat7 I get this error:

[local]$ brew install node
==> Installing node dependency: pkg-config
Error: pkg-config cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc

If I install gcc as mentioned I get this:
[etc]$ brew install gcc
==> Installing dependencies for gcc: gmp, xz, mpfr, libmpc, isl
==> Installing gcc dependency: gmp
Error: gmp cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc

I have this compiler installed via yum (I followed the install instruction of brew):
gcc-4.8.3-9.el7.x86_64

What could I do?

KR
Ruben

**Comment by bfontaine** [comment]
Are you using [Linuxbrew](https://github.com/Homebrew/linuxbrew)?

**Comment by rtuider** [comment]
Yes

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/linuxbrew#467
