### ISSUE TITLE
man2html link is broken

### ISSUE THREAD

**Issue by jeffhammond** [Homebrew/homebrew#41470]
Library/Formula/man2html.rb refers to a download (http://dcssrv1.oit.uci.edu/indiv/ehood/tar/man2html3.0.1.tar.gz) that does not exist (http://www.downforeveryoneorjustme.com/http://dcssrv1.oit.uci.edu/indiv/ehood/tar/man2html3.0.1.tar.gz).

**Comment by DomT4** [comment]
Will be fixed by #41471.
