### ISSUE TITLE
Bottle - Specify full url

### ISSUE THREAD

**Issue by ladislas** [Homebrew/homebrew#41479]
Is it possible to specify the full `url` to the bottle and not just the `root_url` for bottles that don't follow homebrew's naming rules?

The reason is: I'm trying to set up an embedded ARM toolchain with a tap by using [GNU Tools for ARM Embedded Processors](https://launchpad.net/gcc-arm-embedded). Building from source is really long and doesn't quite work yet. But they also provide with precompiled binaries that can be used right out of the box and work very well.

What I first did was:

```ruby
    def install
        bin.install Dir["bin/*"]
        prefix.install Dir["arm-none-eabi", "lib", "share"]
    end
```
 to just use the binaries. But I'd like to allow user to also compile the toolchain from source and I'd like to know if I can use the precompiles binaries as a bottle for the formula. Something like this:

```ruby
    bottle do
        root_url 'https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q2-update/+download/gcc-arm-none-eabi-4_9-2015q2-20150609-mac.tar.bz2'
        sha256 '48841185eefa482f0338059dd779b3edf832521ccd05811d557ef4a2807b8284' => :yosemite
    end
```

Is it possible? Or is it really bad practice?

Thank you very much for your help :)

**Comment by mikemcquaid** [comment]
We don't support this I'm afraid because a bottle is not just an arbitrary download. In this case you're better to use it as a `url` and make a binary formula. Sorry and thanks!

**Comment by ladislas** [comment]
Thanks for the quick reply ;) I'll do that!
