### ISSUE TITLE
Cannot build OpenCV with Java

### ISSUE THREAD

**Issue by xionglingfeng** [Homebrew/homebrew#41472]
I tried to build OpenCV and OpenCV3 with Java support with

    brew install opencv --with-java
    brew install opencv3 --with-java

But both of previous commands built binaries without Java

When I add `-v` to the command, I got

    -- Could NOT find JNI (missing:  JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
    --   OpenCV modules:
    --     To be built:                 hal core flann imgproc ml photo video imgcodecs shape videoio highgui objdetect superres ts features2d calib3d stitching videostab python2
    --     Disabled:                    world
    --     Disabled by dependency:      -
    --     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java python3 viz

    --   Java:
    --     ant:                         /Volumes/Application/homebrew/bin/ant (ver 1.9.5)
    --     JNI:                         NO
    --     Java wrappers:               NO
    --     Java tests:                  NO

However, if I download the source code from [official website](https://github.com/Itseez/opencv/archive/3.0.0.zip) and build it with

    cmake ..

the Java support seems to work.

    --   Java:
    --     ant:                         /Volumes/Application/homebrew/bin/ant (ver 1.9.5)
    --     JNI:                         /System/Library/Frameworks/JavaVM.framework/Headers /System/Library/Frameworks/JavaVM.framework/Headers /System/Library/Frameworks/JavaVM.framework/Headers
    --     Java wrappers:               YES
    --     Java tests:                  YES

**Comment by tdsmith** [comment]
This issue was moved to Homebrew/homebrew-science#2499
