### ISSUE TITLE
mkvtoolnix won't install on 10.10

### ISSUE THREAD

**Issue by GrantLS** [Homebrew/homebrew#41485]
https://gist.github.com/d49b67a72afe316bac49

**Comment by DomT4** [comment]
Lots of Boost warnings here but it did compile fine:

```
==> Summary
🍺  /usr/local/Cellar/mkvtoolnix/8.1.0: 35 files, 12M, built in 7.9 minutes
```

Your error seems to be with `libebml`, which contains the header your installation can't find. Can you try `brew reinstall libebml`?

**Comment by GrantLS** [comment]
Reinstalling libeml didn't help. The [mkvtoolnix site] (https://www.bunkus.org/videotools/mkvtoolnix/downloads.html#macosx) says to run 
```
brew install --with-wxmac mkvtoolnix
```
and I think the --with-wxmac switch is what is causing the problem. Without that, I was able to compile and link with no problem.

**Comment by GrantLS** [comment]
I just checked [platform support] (https://www.wxwidgets.org/about/) for wxMac and it looks like it only supports up to Snow Leopard. That would indeed cause the problem. So, this isn't a homebrew issue.

**Comment by mikemcquaid** [comment]
Let's disable it by default. Good detective work @GrantLS.

**Comment by dgw** [comment]
On 10.10 I just built Mkvtoolnix 8.1.0 with Homebrew, including `--with-wxmac`, with no apparent issues. I have only the old GUI and I can't seem to do a `linkapps` to get it to show up in Spotlight or Applications, but it does work.

**Comment by luzpaz** [comment]
Jus tried building on 10.10.3 
Was not able to install. 
See [Gist](https://gist.github.com/6e39e64130fa057071ff)
Here are the superficial warnings:
```
🍎 Test:scribus_temp sphenoid$ brew install --with-qt5 mkvtoolnix
==> Installing dependencies for mkvtoolnix: libogg, libvorbis, flac, libmagic, libebml, libmatroska
==> Installing mkvtoolnix dependency: libogg
==> Downloading https://homebrew.bintray.com/bottles/libogg-1.3.2.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libogg-1.3.2.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libogg/1.3.2: 95 files, 672K
==> Installing mkvtoolnix dependency: libvorbis
==> Downloading https://homebrew.bintray.com/bottles/libvorbis-1.3.5.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libvorbis-1.3.5.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libvorbis/1.3.5: 155 files, 2.6M
==> Installing mkvtoolnix dependency: flac
==> Downloading https://homebrew.bintray.com/bottles/flac-1.3.1.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring flac-1.3.1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/flac/1.3.1: 50 files, 2.4M
==> Installing mkvtoolnix dependency: libmagic
==> Downloading https://homebrew.bintray.com/bottles/libmagic-5.23.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libmagic-5.23.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libmagic/5.23: 274 files, 5.5M
==> Installing mkvtoolnix dependency: libebml
==> Downloading https://homebrew.bintray.com/bottles/libebml-1.3.1.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libebml-1.3.1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libebml/1.3.1: 33 files, 684K
==> Installing mkvtoolnix dependency: libmatroska
==> Downloading https://homebrew.bintray.com/bottles/libmatroska-1.4.2.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libmatroska-1.4.2.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libmatroska/1.4.2: 34 files, 1.8M
==> Installing mkvtoolnix
==> Downloading https://www.bunkus.org/videotools/mkvtoolnix/sources/mkvtoolnix-8.2.0.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/mkvtoolnix/8.2.0 --without-curl --with-boost=/usr/local/opt/boost --with-extra-includes=/usr/local/opt/libogg/inclu
==> ./drake -j4
/usr/local/opt/boost/include/boost/optional/optional.hpp:1254:95: warning: unused parameter 'v' [-Wunused-parameter]
operator<<(std::basic_ostream<CharType, CharTrait>& out, optional_detail::optional_tag const& v)
                                                                                              ^
2 warnings generated.
2 warnings generated.
```

**Comment by Rotonen** [comment]
```
brew install mkvtoolnix --with-gettext --with-lzo --with-qt5
==> Downloading https://www.bunkus.org/videotools/mkvtoolnix/sources/mkvtoolnix-8.2.0.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/Users/rotonen/.homebrew/Cellar/mkvtoolnix/8.2.0 --without-curl --with-boost=/Users/rotonen/.homebrew/opt/boost --with-extra-includes=/
==> ./drake -j8
#include <ebml/c/libebml_t.h>
         ^
      AR lib/pugixml/src/libpugixml.a
2 warnings and 1 error generated.
  RANLIB lib/pugixml/src/libpugixml.a
```

**Comment by DomT4** [comment]
> Let's disable it by default.

Turns out we don't enable it by default. It's an option.

Can anyone still having this issue produce a `brew gist-logs mkvtoolnix`. I'm wondering if this is a "too many cores to handle" situation, I can't reproduce it at all on a `j4` situation. Going to run a build through the test-bot to see what happens.

**Comment by baikal** [comment]
having the same issue, I tried with `brew gist-logs mkvtoolnix`.
See https://gist.github.com/74bf73a819ef15f381c6

**Comment by luzpaz** [comment]
@DomT4 gist was already posted in my report above: https://github.com/Homebrew/homebrew/issues/41485#issuecomment-122921345

**Comment by DomT4** [comment]
Anyone impacted here, let's test the theory. Please try:

```
HOMEBREW_MAKE_JOBS=1 brew install mkvtoolnix --with-wxmac
```

And let us know how it goes. Thanks!

**Comment by DomT4** [comment]
Or with Qt5. It seems to hit both the qt5 & wxmac builds if the above Gist logs are any indication.

**Comment by baikal** [comment]
It (version 8.2.0) installs fine with `brew install mkvtoolnix --with-wxmac` and `brew install mkvtoolnix --with-wxmac --with-lzo --with-gettext`, even without HOMEBREW_MAKE_JOBS=1 (*--> drake -j8*).

It won't with `--with-qt5`, though. I tried with HOMEBREW_MAKE_JOBS=4  (*--> drake -j4*) earlier today, will try with HOMEBREW_MAKE_JOBS=1 when back to that machine later on.

**Comment by baikal** [comment]
Oh, and just for the record:
It did install fine for version 8.1.0 some time ago, using `--with-qt5 --with-lzo --with-gettext`. Can't remember if there was an Xcode Update in the meantime, but might well be the case.

**Comment by baikal** [comment]
`HOMEBREW_MAKE_JOBS=1 brew install --with-qt5 --verbose mkvtoolnix` fails, too. Lots of `unused parameter v` and `unused parameter out` warnings in /usr/local/opt/boost/include/boost/optional/optional.hpp
and one error:


CXX src/mkvtoolnix-gui/main_window/main_window.cpp
In file included from src/mkvtoolnix-gui/main_window/main_window.cpp:1:
In file included from src/common/common_pch.h:4:
In file included from src/common/common.h:46:
In file included from /usr/local/opt/boost/include/boost/format.hpp:38:
In file included from /usr/local/opt/boost/include/boost/format/internals.hpp:20:
In file included from /usr/local/opt/boost/include/boost/optional.hpp:15:
/usr/local/opt/boost/include/boost/optional/optional.hpp:1254:53: warning: unused parameter 'out' [-Wunused-parameter]
operator<<(std::basic_ostream<CharType, CharTrait>& out, optional_detail::optional_tag const& v)
                                                    ^
/usr/local/opt/boost/include/boost/optional/optional.hpp:1254:95: warning: unused parameter 'v' [-Wunused-parameter]
operator<<(std::basic_ostream<CharType, CharTrait>& out, optional_detail::optional_tag const& v)
                                                                                              ^
src/mkvtoolnix-gui/main_window/main_window.cpp:121:7: fatal error: no member named 'actionGUICheckForUpdates' in 'mtx::gui::Ui::MainWindow'; did you mean 'actionHelpCheckForUpdates'?
  ui->actionGUICheckForUpdates->setVisible(false);
      ^~~~~~~~~~~~~~~~~~~~~~~~
      actionHelpCheckForUpdates
src/mkvtoolnix-gui/forms/main_window/main_window.h:42:14: note: 'actionHelpCheckForUpdates' declared here
    QAction *actionHelpCheckForUpdates;
             ^
2 warnings and 1 error generated.

**Comment by baikal** [comment]
my problem is solved: there was an error in the source - only triggered when using without curl (as in homebrew). Found patch here first https://www.mail-archive.com/gentoo-commits@lists.gentoo.org/msg143848.html, is fixed upstream apparently https://github.com/mbunkus/mkvtoolnix/commit/5c56d6544ffc212ca39ac59f4ed98b4f04761de8.

```
diff --git a/Library/Formula/mkvtoolnix.rb b/Library/Formula/mkvtoolnix.rb
index 53d9b37..e2ad7e6 100644
--- a/Library/Formula/mkvtoolnix.rb
+++ b/Library/Formula/mkvtoolnix.rb
@@ -44,6 +44,8 @@ class Mkvtoolnix < Formula

   needs :cxx11

+  patch :DATA
+
   def install
     ENV.cxx11

@@ -103,3 +105,22 @@ class Mkvtoolnix < Formula
     system "#{bin}/mkvextract", "tracks", mkv_path, "0:#{sub_path}"
   end
 end
+
+__END__
+
+see https://www.mail-archive.com/gentoo-commits@lists.gentoo.org/msg143848.html
+
+---
+Index: mkvtoolnix-8.2.0-fix-curl-support.patch
+===================================================================
+--- a/src/mkvtoolnix-gui/main_window/main_window.cpp
++++ b/src/mkvtoolnix-gui/main_window/main_window.cpp
+@@ -118,7 +118,7 @@
+ #if defined(HAVE_CURL_EASY_H)
+   connect(ui->actionHelpCheckForUpdates,       &QAction::triggered,             this, &MainWindow::checkForUpdates);
+ #else
+-  ui->actionGUICheckForUpdates->setVisible(false);
++  ui->actionHelpCheckForUpdates->setVisible(false);
+ #endif  // HAVE_CURL_EASY_H
+ }
+
```

**Comment by guoxiao** [comment]
@baikal I tried your solution and it works well. I've submitted a PR. See  #42047.

**Comment by bolsoncerrado** [comment]
Installed as adviced with

brew install --with-qt5 mkvtoolnix

and after patching file src/mkvtoolnix-gui/main_window/main_window.cpp
==> ./configure --prefix=/usr/local/Cellar/mkvtoolnix/8.2.0 --without-curl --with-boost=/usr/local/opt/boost --with-extra-includes=/usr/loca
==> ./drake -j4

==> ./drake install
🍺  /usr/local/Cellar/mkvtoolnix/8.2.0: 39 files, 12M, built in 13.1 minutes

I cant find the GUI on the Applications folder.

Do I need to reboot for that to happen? Or restart Finder?

**Comment by dunn** [comment]
@bolsoncerrado did you run `brew linkapps mkvtoolnix`?

**Comment by bolsoncerrado** [comment]
No, i was not pointed to do so on mkvtoolnix site... Lemme try to.

**Comment by bolsoncerrado** [comment]
Did run the command, restarted Finder, nothing happens :?

**Comment by dunn** [comment]
Oh, I thought #42480 had been resolved.  Looks like there are still issues with the QT version's GUI.

**Comment by bolsoncerrado** [comment]
Hmmm by checking this i assume it is actually missing something:

Alex:/ alex$ brew linkapps 
Linking /usr/local/opt/qt5/Assistant.app to /Applications.
Linking /usr/local/opt/qt5/Designer.app to /Applications.
Linking /usr/local/opt/qt5/Linguist.app to /Applications.
Linking /usr/local/opt/qt5/pixeltool.app to /Applications.
Linking /usr/local/opt/qt5/qdbusviewer.app to /Applications.
Linking /usr/local/opt/qt5/qml.app to /Applications.
Linking /usr/local/opt/qt5/QMLViewer.app to /Applications.
Alex:/ alex$ brew linkapps mkvtoolnix
Alex:/ alex$ 

Since ther'es no reply from brew when linking mkvtoolnix, something else must be wrong somewhere....

**Comment by DomT4** [comment]
This issue is fixed. The broken Qt5 is the cause of the `mkvtoolnix` failure with the Qt5 GUI, I'm half-tempted to actually remove the option until Qt sort out the many issues present in the current 5.x release.

**Comment by bolsoncerrado** [comment]
Coolio!! 

Care to elaborate on how to fix this then?

**Comment by DomT4** [comment]
Right now, if you want the GUI, build `--with-wxmac` rather than Qt5.

I'm increasingly tempted to try and hack around the various Qt5 problems, but the codebase is a beast and making small changes either before or after compile can cause more problems than they fix.

**Comment by vespina** [comment]
For those having this problem on Yosemite, the solution is to edit mkvtoolnix formula:

    brew edit mkvtoolnix

and change de source of the package to use the last available version on the repository:

    url "https://www.bunkus.org/videotools/mkvtoolnix/sources/mkvtoolnix-8.6.1.tar.xz"
    sha1 "983795dfe0f2950ede3bc2821a18bb105a68a0ab"

Then, install with:

    brew install mkvtoolnix --with-wxmac

**Comment by DomT4** [comment]
Or `brew update`, where `mkvtoolnix` is already on 8.6.1 :wink:. The `wxmac` option was removed though, apparently being unsupported: https://github.com/Homebrew/homebrew/commit/0c75462ec732595e90f8fb1ab12260bc8ca0e452.

The `qt5` build is now known to work.
