### ISSUE TITLE
Wrong openMPI version linked

### ISSUE THREAD

**Issue by kilojoules** [Homebrew/homebrew#41484]
After updating to open-mpi 1.8.6 I cannot link mpicc to the correct config files.

    $ mpicc
    Cannot open configuration file /usr/local/Cellar/open-mpi/1.8.4_1/share/openmpi/mpicc-wrapper-data.txt
    Error parsing data file mpicc: Not found

I tried `brew unlink open-mpi && brew link open-mpi`, `brew cleanup`, `brew prune`, and reinstalling openmpi. Why are my mpi compilers linked wrong?

Somehow mpicc has been linked wrong

    $ /usr/local/Cellar/open-mpi/1.8.6/bin/mpicc
    Cannot open configuration file /usr/local/Cellar/open-mpi/1.8.4_1/share/openmpi/mpicc-wrapper-data.txt
Error parsing data file mpicc: Not found

**Comment by mikemcquaid** [comment]
Can't reproduce here; seems to produce `clang: error: no input files` as expected.

**Comment by kilojoules** [comment]
$ brew gist-logs openmpi
https://gist.github.com/272d5f9ef2f5eea21d9d

**Comment by kilojoules** [comment]
For what its worth I reproduced this on another machine (OSX 10.10 before, 10.9 this time). I originally solved this by restoring my computer to factory settings and using `brew install openmpi`. This error seems to occur during reinstallation of homebrew packages boost, boost155, gcc, and/or python. Perhaps something is wrong in the `open-mpi-1.8.6.tar.bz2` file?

    $ brew uninstall openmpi --force
    Uninstalling open-mpi... (781 files, 22M)
    ~/Desktop/building_dakota/dakota-6.1.0.src/build$ brew install openmpi --build-from-scratch
    ==> Downloading https://homebrew.bintray.com/bottles/open-mpi-1.8.6.mavericks.bottle.tar.gz
    Already downloaded: /Library/Caches/Homebrew/open-mpi-1.8.6.mavericks.bottle.tar.gz
    ==> Pouring open-mpi-1.8.6.mavericks.bottle.tar.gz
    🍺  /usr/local/Cellar/open-mpi/1.8.6: 781 files, 22M
    $ mpicc
    Cannot open configuration file /usr/local/Cellar/open-mpi/1.8.4_1/share/openmpi/mpicc-wrapper-data.txt

    $ brew uninstall openmpi --force
    Uninstalling open-mpi... (781 files, 22M)
    $ brew install openmpi --build-from-source
    ==> Using Homebrew-provided fortran compiler.
    This may be changed by setting the FC environment variable.
    ==> Downloading https://www.open-mpi.org/software/ompi/v1.8/downloads/openmpi-1.8.6.tar.bz2
    Already downloaded: /Library/Caches/Homebrew/open-mpi-1.8.6.tar.bz2
    ==> ./configure --prefix=/usr/local/Cellar/open-mpi/1.8.6 --disable-silent-rules --enable-ipv6 --with-libeven
    ==> make all
    mpicc
    ==> make check
    ==> make install
    Warning: open-mpi dependency gcc was built with a different C++ standard
    library (libstdc++ from clang). This may cause problems at runtime.
    🍺  /usr/local/Cellar/open-mpi/1.8.6: 781 files, 22M, built in 14.0 minutes
    $ mpicc
    Cannot open configuration file /usr/local/Cellar/open-mpi/1.8.4_1/share/openmpi/mpicc-wrapper-data.txt
    Error parsing data file mpicc: Not found
    $ brew gist-logs openmpi
    https://gist.github.com/53d6eb389b9ac342a77e

**Comment by tdsmith** [comment]
What do `which mpicc` and `ls -l /usr/local/bin/mpicc` say? What's the output of `brew info openmpi`?

**Comment by kilojoules** [comment]
$ brew info openmpi
    open-mpi: stable 1.8.6 (bottled), HEAD
    High performance message passing library
    https://www.open-mpi.org/
    Conflicts with: lcdf-typetools, mpich2
    /usr/local/Cellar/open-mpi/1.8.6 (781 files, 22M) *
      Built from source
    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/open-mpi.rb
    ==> Dependencies
    Required: libevent ✔
    ==> Options
    --c++11
    	Build using C++11 mode
    --with-mpi-thread-multiple
    	Enable MPI_THREAD_MULTIPLE
    --without-fortran
    	Build without fortran support
    --HEAD
    	Install HEAD version
    $ which mpicc
    /usr/local/bin/mpicc
    $ mpicc
    Cannot open configuration file /usr/local/Cellar/open-mpi/1.8.4_1/share/openmpi/mpicc-wrapper-data.txt
    Error parsing data file mpicc: Not found

**Comment by kilojoules** [comment]
Perhaps boost155 is installing or partially installing open-mpi 1.8.4

**Comment by kilojoules** [comment]
I also tried `brew uninstall $(brew list)` then `brew install openmpi`. This problem is persisting.

**Comment by kilojoules** [comment]
The problem was in my redefinition of `DYLD_LIBRARY_PATH` - A careless mistake on my end.
