### ISSUE TITLE
libgcrypt failed to build on Ubuntu Trusty

### ISSUE THREAD

**Issue by bxm156** [Homebrew/homebrew#41487]
https://gist.github.com/c9ac647b584aa11dedbd

make[2]: *** [check-TESTS] Error 1
make[2]: Leaving directory `/tmp/libgcrypt20150708-22643-ognl02/libgcrypt-1.6.3/tests'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/tmp/libgcrypt20150708-22643-ognl02/libgcrypt-1.6.3/tests'
make: *** [check-recursive] Error 1

**Comment by mistydemeo** [comment]
This issue was moved to Homebrew/linuxbrew#470
