### ISSUE TITLE
Formulae that break under Sandboxing [Tracking]

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew#41501]
At some point we probably want to turn Sandboxing on by default, but there's some formulae that die horrible deaths inside the Sandbox so tracking them here.

Ideally, we need to report failures upstream if it's something upstream can handle, but otherwise decide if to introduce a new variable like we do with `def pour_bottle?` that stops relevant from-source compiles happening when `HOMEBREW_SANDBOX` is active, or removing the formula from Homebrew, or patching it ourselves as necessary.

* <del>Git - #38978 (Seems to be potentially a 10.10 problem).</del>

* <del>Glib - https://gist.github.com/anonymous/2b4de19a79616a716ba0</del> Fixed by #42296

* <del>Postgis - #41962</del> Fixed by #45611

* <del>mecab-ipadic - https://github.com/Homebrew/homebrew/issues/41501#issuecomment-126634120</del> Fixed by #43324

**Comment by mistydemeo** [comment]
With glib, the formula explicitly passes `--with-gio-module-dir=#{HOMEBREW_PREFIX}/lib/gio/modules` to configure; I believe the sandbox intentionally disallows writing to the prefix?

**Comment by DomT4** [comment]
Yeah, that error is "on" us. `def install` permits writing to [these places](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/formula_installer.rb#L483-L491). You can only write to the broader Homebrew prefix in `postinstall`. Theoretically we could "whitelist" various directories for certain formula.

**Comment by xu-cheng** [comment]
I just tested building git under sandbox in OS X El Captain VM. It works fine. No temporary files left.

**Comment by mikemcquaid** [comment]
@DomT4 I think that error is actually a good thing as it makes us aware of when e.g. bottling will break the formula. Better to install the modules somewhere else and then move them in `post_install`, I think.

**Comment by bfontaine** [comment]
`mecab-dict` fails in the sandbox, it tries to create directories under `mecab`’s prefix:

```
$ brew install --sandbox mecab-ipadic
==> Downloading https://downloads.sourceforge.net/project/mecab/mecab-ipadic/2.7.0-20070801/mecab-ipadic-2.7.0-20070801.tar.gz
Already downloaded: /Library/Caches/Homebrew/mecab-ipadic-2.7.0-20070801.tar.gz
==> ./configure --prefix=/usr/local/Cellar/mecab-ipadic/2.7.0-20070801 --with-charset=utf8
==> make install
mkdir: /usr/local/Cellar/mecab/0.996/lib/mecab: No such file or directory
mkdir /usr/local/Cellar/mecab/0.996/lib/mecab/dic/ipadic
mkdir: /usr/local/Cellar/mecab/0.996/lib/mecab/dic: No such file or directory
make[1]: *** [install-dicDATA] Error 1
make: *** [install-am] Error 2
```

**Comment by xu-cheng** [comment]
@bfontaine In that case, we need to turn `mecab-ipadic` as an optional resource of `mecab`. And I suspect this problem exists for all mecab related formulae.

**Comment by DomT4** [comment]
`glib-networking` is one as well:

```
libtool: link: ar cru .libs/libgiognomeproxy.a  gproxyresolvergnome.o gnome-proxy-module.o
libtool: link: ranlib .libs/libgiognomeproxy.a
libtool: link: ( cd ".libs" && rm -f "libgiognomeproxy.la" && ln -s "../libgiognomeproxy.la" "libgiognomeproxy.la" )
make[4]: Nothing to be done for `install-exec-am'.
 ../.././install-sh -c -d '/usr/local/lib/gio/modules'
 /bin/sh ../../libtool   --mode=install /usr/bin/install -c   libgiognomeproxy.la '/usr/local/lib/gio/modules'
libtool: install: /usr/bin/install -c .libs/libgiognomeproxy.so /usr/local/lib/gio/modules/libgiognomeproxy.so
install: /usr/local/lib/gio/modules/libgiognomeproxy.so: Operation not permitted
make[4]: *** [install-giomoduleLTLIBRARIES] Error 71
make[3]: *** [install-am] Error 2
make[2]: *** [install] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
```

**Comment by DomT4** [comment]
Should be the same fix or a very similar fix to `glib`, from a quick glance.

**Comment by DomT4** [comment]
The above was not as simple a fix as I'd hoped. Not only does it attempt to create that directory, but it also attempts to directly install there and we've been facilitating that for a long time. That facilitation breaks sandboxing, but also stops us bottling `glib-networking`.

My proposal is to do:

```diff
def install
+ inreplace "configure", "$($PKG_CONFIG --variable giomoduledir gio-2.0)", lib/"gio/modules"
system "./configure", "--disable-dependency-tracking",
```

But that would mean everyone would have to deal with this once:

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink lib/gio/modules/giomodule.cache
Target /usr/local/lib/gio/modules/giomodule.cache
already exists. You may want to remove it:
  rm '/usr/local/lib/gio/modules/giomodule.cache'

To force the link and overwrite all conflicting files:
  brew link --overwrite glib-networking

To list all files that would be deleted:
  brew link --overwrite --dry-run glib-networking

Possible conflicting files are:
/usr/local/lib/gio/modules/giomodule.cache
/usr/local/lib/gio/modules/libgiognomeproxy.a
/usr/local/lib/gio/modules/libgiognomeproxy.so
/usr/local/lib/gio/modules/libgiognutls.a
/usr/local/lib/gio/modules/libgiognutls.so
```

After that, we'd be able to sandbox and bottle to our heart's content. Everything seems to work as intended checking the various `brew test --verbose` on `glib-networking` and `megatools` (Which depends_on `glib-networking`, and `/usr/local/lib/gio/modules/` would never become a symlink to `/usr/local/opt/glib-networking/lib/gio/modules` because `glib`, which `glib-networking` depends on creates that directory in `postinstall`.

Downsides: `brew` automatically removes the `.la` files, `libgiognomeproxy.la` and `libgiognutls.la` - We'd either need to tell it not to do that, or ensure those files aren't expected/needed anywhere.

**Comment by mikemcquaid** [comment]
> But that would mean everyone would have to deal with this once:

We can/should make a workaround for this case so that we can cleanup the necessary files in the formula.

**Comment by DomT4** [comment]
As a rough attempt at a workaround I tried:

```ruby
  def post_install
    # Sandboxing fixes. Resolves users seeing something like this:
    # https://github.com/Homebrew/homebrew/issues/41501#issuecomment-130959611
    gio_dir = HOMEBREW_PREFIX/"lib/gio/modules"
    gios = [
      gio_dir/"giomodule.cache",
      gio_dir/"libgiognomeproxy.a",
      gio_dir/"libgiognomeproxy.la",
      gio_dir/"libgiognomeproxy.so",
      gio_dir/"libgiognutls.a",
      gio_dir/"libgiognutls.la",
      gio_dir/"libgiognutls.so"
    ]

    gios.each do |g|
      g.unlink if g.exist?
    end
  end
```

But since we do postinstall after we do `Finishing up` the linking problems remain, and are fixed a few seconds later. Really we need something like a `preinstall` step, but reluctant to go down that path and add more formula code in.

**Comment by DomT4** [comment]
I suppose I could look at dumping them into `libexec` temporarily, and then moving them from `libexec` to `lib` and symlinking manually in `postinstall`. Kind of dancy though.

**Comment by DomT4** [comment]
Opened #43165 for discussion.

**Comment by dunn** [comment]
Subversion with `--universal` fails (#42817): http://bot.brew.sh/job/Homebrew%20Pull%20Requests/32095/version=yosemite/testReport/junit/brew-test-bot/yosemite/install___only_dependencies_viewvc/

**Comment by xu-cheng** [comment]
For mecab family formulae, it seems that we can fix the issue by setting `mecab_dictdir` to `HOMEBREW_PREFIX/lib`. I will look into the detail solution when I'm free.

**Comment by DomT4** [comment]
> Subversion with --universal fails 

Fixed by adding the `/var/tmp` path to the whitelist.

**Comment by xu-cheng** [comment]
Mecab related formulae should be fixed by #43324

**Comment by apjanke** [comment]
`qscintilla2` and probably other formulae that supply Qt plugins will break under sandboxing, because they attempt to install the plugin dylibs under the `qt` installation. (See #44726.)

**Comment by apjanke** [comment]
The `--sandbox` option isn't documented in `man brew`. Should it be added, or is this a seekrit experimental feature for now?

**Comment by xu-cheng** [comment]
Personally I think sandbox is mature enough to be documented. We may also add it in PR document to ask formula author to test formula with sandbox enabled locally before submitting it. 

But let's hear other maintainers opinion. Maybe I'm bias becuase I implemented sandbox feature. :smile:

**Comment by DomT4** [comment]
:shipit:

**Comment by mikemcquaid** [comment]
@xu-cheng I'm wondering at what stage we want to enable sandbox for some/all formulae?

**Comment by mikemcquaid** [comment]
I don't think it should be documented because I think the goal shouldn't be having an option but having it be the default :grinning:

**Comment by xu-cheng** [comment]
I don't know when is the proper time. But we still need to fix PostgreSQL related formulae(also probably some Qt plugins) considering they have quite large user base.  

When we enable sandbox by default, we will need to document how to disable it. (Maybe a `--disable-sandbox` flag and `HOMEBREW_DISABLE_SANDBOX` environment variable). Beside this, a `sandbox.md` may be required to document sandbox feature and troubleshoot possible problems.

**Comment by mikemcquaid** [comment]
@xu-cheng I think it'd be good to have a DSL to enable it per-formulae so we can do so on those we know to work when we `brew pull`.

**Comment by xu-cheng** [comment]
I'm still strongly against to allow sandboxing being disable without user's approver. It's bad from any security aspect. (If it's relevant, both Macport and NixOS offer using sandbox to build packages. And for both, the only way to enable/disable is by user's config)

Currently, the only reason a formula is broken under sandbox is it violates Homebrew's prefix + symlink structure. And in some term, that formula is broken anyway(most importantly it's broken for upgrade/uninstall). Therefore, I don't think offer a DSL can do only good.

**Comment by mikemcquaid** [comment]
@xu-cheng We need the DSL to role it out incrementally. Once we've done so I agree we should enable it by default.

**Comment by DomT4** [comment]
> I'm still strongly against to allow sandboxing being disabled without user's approver. It's bad from any security aspect.

I agree it shouldn't be disabled without a user's permission, but I'm fine with us hacking something like we do with compilers:

```ruby
def Badformula < Formula
  url "https://bad/badformula.tar.gz"
  sha256 "370e3e846321868427de5a1709790addebfa6fa1c894508025e6e2af5b1967df"

  fails_with :sandbox do
    cause "Tries to link xyz to xyz"
  end
```

And then have an exception there that when something `fails_with :sandbox` and the sandbox is set locally we could die and tell the user it needs to be build without the sandbox for now.

Or we could go down the route of each formula needing to be tagged with `sandbox :enabled` and enable those automatically on user's machines (with an optional opt-out if desired) and then have the CI stamp each formula that passes with `sandbox :enabled` in the same way it does `cellar :any` when appropriate.

Some random thoughts on our options there anyhow `¯\_(ツ)_/¯`

**Comment by mikemcquaid** [comment]
> Or we could go down the route of each formula needing to be tagged with sandbox :enabled and enable those automatically on user's machines (with an optional opt-out if desired) and then have the CI stamp each formula that passes with sandbox :enabled in the same way it does cellar :any when appropriate.

I think we'll need to opt-in until we're sure a decent number of our formulae work.

**Comment by DomT4** [comment]
> I think we'll need to opt-in until we're sure a decent number of our formulae work.

Even in the `sandbox :enabled` style syntax for things that pass the CI and test okay?

**Comment by mikemcquaid** [comment]
Oh, no, that's what I meant by "opt-in": we opt-in formulae through that DSL/

**Comment by DomT4** [comment]
Cool :+1:. Sorry, thought you meant even the `sandbox :enabled` or whatever style syntax we adopt would have to remain opt-in.

**Comment by xu-cheng** [comment]
Personally, I like the idea for `fails_with :sandbox` which seems to be a reasonable temporary step while preserving security integrity. Bottom line is sandbox should only be disabled by user's approver.

**Comment by mikemcquaid** [comment]
> Personally, I like the idea for fails_with :sandbox which seems to be a reasonable temporary step while preserving security integrity. Bottom line is sandbox should only be disabled by user's approver.

If we take that approach: the sandbox will never be enabled by default, unfortunately, unless you can figure out another way of doing a gradual roll-out.

**Comment by xu-cheng** [comment]
> If we take that approach: the sandbox will never be enabled by default, unfortunately, unless you can figure out another way of doing a gradual roll-out.

Why will it never be enabled by default? We can still make it default. So users will see something similar to this:
```
$ brew install bad-formula
Error: bad-formula cannot be installed with sandbox enabled. 
If you want to install it without sandbox, please run:
    brew install bad-formula --disable-sandbox
```

The only difference is to let user confirm they want to disable sandbox.

**Comment by mikemcquaid** [comment]
We can't make it default until we know that at least all the core formulae and official taps all work with the sandbox. Even in that case we're likely to break other random formulae. That's why a gradual roll-out is necessary (and a gradual roll-out requires a temporary DSL to be able to temporarily enable/disable it).

**Comment by xu-cheng** [comment]
Forgive my stupidity, but I fail to understand why `fails_with :sandbox` doesn't fulfill the requirement as a temporary DSL? From user point of view, they only need an extra confirm to install the formula, while for `brew test-bot` we definitely can auto disable sandbox in such case.

**Comment by mikemcquaid** [comment]
We need several stages of sandbox rollout:

0. (already done) run sandbox optionally
0. run sandbox optionally and with our CI
0. run sandbox optionally when a DSL enables it and add this DSL to passing formulae
0. run sandbox by default but allow a DSL to disable it

**Comment by xu-cheng** [comment]
The first and second stages are already done.

The third stage has some bad design smell to me. How do you intend to process? Batch tagging formula, which would make this stage meaningless.  Another thing is once we create such DSL, we will have to support it indefinitely(even if we disable its function afterwards) in order to maintain backward compatibility. If you just want to keep record on sandbox passing for formulae in core and all official taps temporary, may I suggest to put such metadata elsewhere? So we don't have to deal with it in long term.

The final stage (allow a DSL to disable it) is exactly what I'm talking about by `fails_with :sandbox` or something similar. The critical part is that user has to consent to disable sandbox.

**Comment by mikemcquaid** [comment]
Are you personally going to test/tag every formula in Homebrew core to make sure it works with the sandbox? If so: :cool:. I assumed you wouldn't want to :wink:

**Comment by xu-cheng** [comment]
> Are you personally going to test/tag every formula in Homebrew core 

There are 3258 formulae in core currently. While 1112 of them has el capitan bottles which means it works with sandbox. There are other 1215 formulae which have bottle but not el capitan one, we should schedule to rebuild bottle for el capitan and we can check it in the process. So there are only 931 unbottled formulae left. I'll have to tag them anyway once I finished `bottle :unneeded`, and we can record them in the process.

That's the basic plan.

**Comment by mikemcquaid** [comment]
Great, that sounds great. You're more willing to do the dirty work than me so your `fails_with` approach sounds good. I'd suggest at first we enable only the sandbox for all core formulae then try to do the same approach with official taps then somehow announce to unofficial taps and give them e.g. ~3 months to update their formulae before we enable it globally.

**Comment by mikemcquaid** [comment]
Note there's probably also a bunch of stuff that's bottled that doesn't need to be and can be `bottle :unneeded`.

**Comment by apjanke** [comment]
Formulae which use `docbook` at build time, but not `docbook-xsl`, may fail under sandboxing due to attempts to fetch XSL files over the network, encountering errors like the following. They'll need to be changed to depend on `docbook-xsl`, which installs local copies of files it would otherwise need to fetch.

```
/usr/bin/xsltproc --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl docs/man/secret-tool.xml
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
make[2]: *** [secret-tool.1] Error 4
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
```

**Comment by xu-cheng** [comment]
This doesn't look like a sandbox issue as we don't prohibit network in sandbox rule. Agree we should change it to `docbook-xsl` to reduce unnecessary downloading. Or we can just merge `docbook-xsl` into `docbook`.

**Comment by apjanke** [comment]
Ahhh, you're right. I had misdiagnosed it: it was the `xsltproc --nonet` option itself in `libsecret`'s default installation path which was causing those errors to happen, not the sandbox.

I could see a case for still keeping `docbook` and `docbook-xsl` separate: `docbook-xsl` is 50 MB, which might be a heavy load for some users. You're trading off repeated small downloads for one big download up front at installation time. IMHO it still makes sense to install both by default: at installation time, you're expecting to do downloads; once you have it installed, you might expect that you could do your work completely locally. Maybe we could make `docbook-xsl` a `:recommended` dependency of `docbook`? That way most users would get it by default, but users who really wanted to conserve on hard drive space could opt to exclude it. If it's not causing a sandbox issue, then we don't have to add the dependency on each of the individual formulae which use `docbook`.

**Comment by mikemcquaid** [comment]
> Maybe we could make docbook-xsl a :recommended dependency of docbook? That way most users would get it by default, but users who really wanted to conserve on hard drive space could opt to exclude it. If it's not causing a sandbox issue, then we don't have to add the dependency on each of the individual formulae which use docbook.

That makes sense to me :+1:

**Comment by xu-cheng** [comment]
> Maybe we could make docbook-xsl a :recommended dependency of docbook

We can't. Because `docbook` is already a dependency of `docbook-xsl`. we cannot create a dependency circle. What we can get is to merge these two into a formula and offer an option to disable `docbook-xsl` resource.

**Comment by mikemcquaid** [comment]
Good point, whoops. Yeh, combining sounds :+1:

**Comment by apjanke** [comment]
Hmm. Philosophically, I like the idea of combining: to me, `docbook` feels like it ought to represent an entire DocBook toolchain, not just the DTDs. But it might make expressing formula dependencies harder: some formulae like `libsecret` need the XSL files installed locally. (Or I could back out the recent `libseret` change I made, and go back to patching it to allow network downloads, along with pushing for an upstream change.) Several formulae depend on `docbook-xsl` instead of `docbook`; I don't know if they're doing that because they really need it installed locally, or it just worked better, or expresses their needs philosophically (in that `docbook-xsl` is the output part of the toolchain, and they need to use its capability, even if they don't really need a local install of the files). Let me take a look at them to get a better idea of exactly what their usage of it is.

**Comment by DomT4** [comment]
Closing here. Easier at this point to track sandbox failures on a formula-by-formula basis than keeping a tracking issue open indefinitely pages deep into the Issues, heh.
