### ISSUE TITLE
pkgconfigs from homebrew point /usr/include that does not exist

### ISSUE THREAD

**Issue by tomykaira** [Homebrew/homebrew#41542]
When cmake run `find_package` for `libxml2`, it sets `/usr/include/libxml2` to include dirs because [libxml-2.0.pc](https://github.com/Homebrew/homebrew/blob/master/Library/ENV/pkgconfig/10.10/libxml-2.0.pc) provided by homebrew returns that path.
However, Mac OS 10.10 does not have `/usr/include` out of box, and homebrew installation also does not create it.
Maybe `ln -s $HOMEBREW_SDKROOT/usr/include /usr/include` will fix the problem, but is it correct fix?
Why pkgconfig files does not work well out of box?

I am usually using Fedora and new to Mac OS, so sorry if I am missing basic knowledge.

**Comment by tdsmith** [comment]
Is this causing an error with a Homebrew build? Why is Homebrew's .pc file in PKG_CONFIG_PATH?

**Comment by tdsmith** [comment]
The /usr/include tree is installed by the Xcode Command Line Tools package, which is distributed separately from (and does not depend on) Xcode proper. In general, Homebrew is supposed to work fine without the Command Line Tools, though.

**Comment by tomykaira** [comment]
No, not homebrew build. I am building my private project.
pkg-config is from homebrew, and it `PKG_CONFIG_PATH` is empty (not set) but `pkg-config libxml-2.0` actually looks up pc files from homebrew.
Is it not intended?

```
Mes-MacBook-Pro:build me $ env | grep PKG_CONFIG_PATH
Mes-MacBook-Pro:build me $ pkg-config --list-all --debug 2>&1 | grep libxml-2.0
File 'libxml-2.0.pc' appears to be a .pc file
Will find package 'libxml-2.0' in file '/usr/local/Library/ENV/pkgconfig/10.10/libxml-2.0.pc'
  line>Requires: libxml-2.0
Looking for package 'libxml-2.0'
Looking for package 'libxml-2.0-uninstalled'
Reading 'libxml-2.0' from file '/usr/local/Library/ENV/pkgconfig/10.10/libxml-2.0.pc'
Parsing package file '/usr/local/Library/ENV/pkgconfig/10.10/libxml-2.0.pc'
Unknown keyword 'Libs.private' in '/usr/local/Library/ENV/pkgconfig/10.10/libxml-2.0.pc'
Path position of 'libxml-2.0' is 3
Adding 'libxml-2.0' to list of known packages
Package libxml-2.0 has -L /usr/lib in Libs
Removing -L /usr/lib from libs for libxml-2.0
  line>Requires: libxml-2.0
libxml-2.0   libXML - libXML library version2.
```
> /usr/include tree is installed by the Xcode Command Line Tools package

Sorry, I have believed that it is installed (I installed xcode from AppStore and ran `xcode-select --install` and finished), but the installation seems not completed.

- Start Xcode.app for the first time (I've never launched)
- `rm -rf /Library/Developer/CommandLineTools`
- Rerun `xcode-select --install` and follow the instruction

succeeded to provide `/usr/install`.

**Comment by tdsmith** [comment]
Ah: I think that these pkg-config files should work on Xcode-only systems if `-isysroot` is set correctly, to the Developer SDK root (i.e. add `-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk` to your compiler invocations). `-isysroot` and `--sysroot` are discussed here: https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html
