### ISSUE TITLE
Go 1.5 beta1 released

### ISSUE THREAD

**Issue by drewwells** [Homebrew/homebrew#41547]
Just in time to redo `devel` on the formula.... https://groups.google.com/forum/?utm_source=golangweekly&utm_medium=email#!msg/golang-nuts/0Twz24CjYas/gdkG4nKjY34J

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew/commit/8fe877f1df067a2ace3da9642b62db5c6ab5b0b5

**Comment by drewwells** [comment]
already done
