### ISSUE TITLE
Unusual output from `brew update`

### ISSUE THREAD

**Issue by karljs** [Homebrew/homebrew#41543]
After updating this morning, I noticed that the output from running `brew update` produces a whole slew of messages rather than the usual single one.  Is this expected behavior now?

```
~/ brew update
Already up-to-date.
Already up-to-date.
Already up-to-date.
Already up-to-date.
Already up-to-date.
Already up-to-date.
Already up-to-date.
Already up-to-date.
~/ brew doctor
Your system is ready to brew.
~/
```

**Comment by mistydemeo** [comment]
It looks like this may have been introduced by changes in 125347610c855d0db2791c3972a2747f1d4438d7; Homebrew now does `git pull origin` instead of `git pull`, which does print that message even when `--quiet` is passed.

**Comment by ngocphamm** [comment]
Was about to report this. And then `brew update --rebase` doesn't work either.

**Comment by mistydemeo** [comment]
Argument order appears to be significant, e.g. `git pull --quiet origin` has the desired effect but `git pull origin --quiet` does not.

**Comment by bdielman** [comment]
Also seeing per line message for each formula as it updates. Not a big deal, but was surprising.

**Comment by DomT4** [comment]
Yup.

```
Updating 3c4e24b..4726c8d
Fast-forward
 Casks/arora.rb                   | 11 -----------
 Casks/comictagger.rb             |  5 ++---
 Casks/nosleep.rb                 |  3 +--
 Casks/shotcut.rb                 |  4 ++--
 Casks/splitshow.rb               |  8 ++++----
 Casks/spyder.rb                  |  4 ++--
 Casks/staruml.rb                 |  4 ++--
 Casks/svnx.rb                    |  2 +-
 Casks/textroom.rb                |  2 +-
 Casks/time-tracker.rb            |  4 ++--
 Casks/transmission-remote-gui.rb |  4 ++--
 11 files changed, 19 insertions(+), 32 deletions(-)
 delete mode 100644 Casks/arora.rb
Already up-to-date.
Already up-to-date.
Already up-to-date.
Already up-to-date.
Already up-to-date.
Already up-to-date.
Already up-to-date.
Already up-to-date.
Already up-to-date.
Already up-to-date.
Already up-to-date.
Already up-to-date.
Already up-to-date.
Already up-to-date.
```

We'll have to tweak the new implementation a little to make sure we're not piling update messages onto people.

**Comment by mikemcquaid** [comment]
Fixed in https://github.com/Homebrew/homebrew/commit/08f7c828949be45dade8beb0fc29bebf47b19de1.
