### ISSUE TITLE
ghc install on El Capitan hangs during make

### ISSUE THREAD

**Issue by nodesocket** [Homebrew/homebrew#41561]
Tried installing `ghc` like 5 times. Every time it hangs on the `make` of `ghc`. It just shows make. I waited over 2 hours one of the times.

Running El Capitan 10.11 Beta (15A216g)

```
==> Upgrading shellcheck
==> Installing dependencies for shellcheck: ghc, cabal-install, pandoc
==> Installing shellcheck dependency: ghc
==> Downloading https://downloads.haskell.org/~ghc/7.10.1/ghc-7.10.1-src.tar.xz
Already downloaded: /Library/Caches/Homebrew/ghc-7.10.1.tar.xz
==> Downloading http://ftpmirror.gnu.org/gmp/gmp-6.0.0a.tar.bz2
Already downloaded: /Library/Caches/Homebrew/ghc--gmp-6.0.0a.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/ghc/7.10.1_1/libexec/integer-gmp --with-pic --disable-shared
==> make
==> make check
==> make install
==> Downloading https://downloads.haskell.org/~ghc/7.10.1/ghc-7.10.1-x86_64-apple-darwin.tar.xz
Already downloaded: /Library/Caches/Homebrew/ghc--binary-7.10.1.tar.xz
==> ./configure --prefix=/private/tmp/ghc20150709-66472-d7k0eq/ghc-7.10.1/binary --with-gmp-includes=/usr/local/Cellar/ghc/7.10.1_1/libexec/integer-gmp/inc
==> make install
==> ./configure --prefix=/usr/local/Cellar/ghc/7.10.1_1 --with-gmp-includes=/usr/local/Cellar/ghc/7.10.1_1/libexec/integer-gmp/include --with-gmp-libraries
==> make
```

**Comment by DomT4** [comment]
Anything in `brew gist-logs ghc`?

**Comment by DomT4** [comment]
Note that GHC can take hours to install from source. Hours and hours and hours. You can pass `--verbose` to `brew` to see what's going on at a finer level of detail.

**Comment by nodesocket** [comment]
Do I really need `ghc` just for an updated version of `shellcheck` then? Seems crazy to have to wait hours, and hours.

**Comment by DomT4** [comment]
On 10.11, yeah, you will for now :disappointed:. Once we start building bottles for El Capitan life will get easier for 10.11 users, but at the moment the development situation is still too fluid to to do.

`shellcheck` uses `ghc` to build. Usually most people never touch or see `:build` dependencies because on 10.8-10.10 we provide bottles, and when you pour from a bottle you don't have to install the `:build` dep, obviously.

The new shellcheck wasn't a huge release, If you don't want to wait hours for `ghc` to do its thing your best bet is probably to `brew pin shellcheck` for now to stop it updating.

**Comment by nodesocket** [comment]
@DomT4 awesome, thanks for the explanation.

Is there a Gratipay for Homebrew? We'd ([Commando.io](https://commando.io)) like to donate.

**Comment by DomT4** [comment]
We started landing bottles at the start of last October for Yosemite if that's useful, but there's no set timetable really, whenever stability and demand meet a common ground :wink:.

I'm not actually sure at the moment. Gratipay made some fairly major changes and have been requiring teams to jump through some loopholes to get active again. If it's working, the link is https://gratipay.com/~Homebrew/. I've asked @mikemcquaid to take a look at the situation. Thanks for the kind offer! We :heart: the community's support for Homebrew.

Closing here per as best a resolution as we can manage for 10.11 right now, but feel free to ping us if you have any more questions about the situation. There's a broad tracking issue in #40837.

**Comment by felixbuenemann** [comment]
It was likely just compiling. I installed ghc 7.10.1_1 yesterday on 10.11 Beta 3 (15A216g) and it worked fine. Compile time was roughly two hours on a late 2013 13" rMBP.

**Comment by supermarin** [comment]
@felixbuenemann could you please share the built binary?

**Comment by felixbuenemann** [comment]
@supermarin I created a formula to install the official ghc binaries using homebrew, [instructions here](https://gist.github.com/ccc7cf3797e8f2513b80). That's way better than downloading binaries compiled by random people on the internet :smiley:

**Comment by supermarin** [comment]
Thanks! it still took 1/2 hour of frying, but works :+1:

**Comment by felixbuenemann** [comment]
It takes roughly a minute for me, including the download.
