### ISSUE TITLE
Reintroduce brew update --rebase or similar feature

### ISSUE THREAD

**Issue by Dynom** [Homebrew/homebrew#41566]
Hi,

I used to be able to perform a `brew update --rebase`, which didn't present me with useless merge feedback. After a recent update this feature is no longer available. I would like to see a feature re-introduced that allows me to ignore the tedious merge confirmations.

Desired behaviour:

```
$ brew update
Updated Homebrew from 975ee298 to bd55d360.
==> New Formulae
homebrew/python/pymummer       homebrew/versions/astyle204    josegonzalez/php/php70-lzf     sjk
==> Updated Formulae
aptly				       homebrew/versions/tomcat7	      josegonzalez/php/phpunit		     parallel
awscli				       iojs				      logentries			     re2
...
```

**Comment by mikemcquaid** [comment]
This was a temporary bug and has been fixed.
