### ISSUE TITLE
duti 1.5.3 won't build on El Capitan

### ISSUE THREAD

**Issue by zmwangx** [Homebrew/homebrew#41564]
I have reported this upstream: https://github.com/moretension/duti/issues/12.

We might need to patch the m4 script ourselves if upstream can't do that in time. References:

* #33009 duti not compatible with Yosemite;
* #33011 Duti: Yosemite Fix;
* https://github.com/moretension/duti/commit/594dfe0c9d4693afe4dbc23c505764292a48c6b4 Detect Yosemite correctly.

**Comment by mikemcquaid** [comment]
> We might need to patch the m4 script ourselves if upstream can't do that in time. References:

Probably better to submit a pull-request to upstream.

**Comment by zmwangx** [comment]
> Probably better to submit a pull-request to upstream.

Of course. Apparently I was too lazy yesterday. Submitted https://github.com/moretension/duti/pull/13.

Anyway, I don't expect the maintainer to merge it anytime soon, since there's another half-a-month-old El Capitan patch https://github.com/moretension/duti/pull/11 there already (badly cooked though, I'd say), and there's no response from the maintainer yet.

**Comment by mikemcquaid** [comment]
Cool, thanks.
