### ISSUE TITLE
Should direct 10.11 public beta users to Xcode website 

### ISSUE THREAD

**Issue by remyo** [Homebrew/homebrew#41589]
It looks like 10.11 public beta users don't get Xcode 7 and it doesn't show up in the App Store. However it is available at this url. Might be good to have in the brew doctor warnings. 

https://developer.apple.com/xcode/downloads/

**Comment by mikemcquaid** [comment]
Makes sense, thanks :+1:

**Comment by mikemcquaid** [comment]
PR in #41597, thanks!

**Comment by remyo** [comment]
No problem. Good stuff.

**Comment by ubuntudroid** [comment]
Shouldn't be calling `xcode-select --install` sufficient? This prompts the user to install the command line tools which automatically downloads everything necessary - also on El Capitain.

**Comment by remyo** [comment]
This could be unique to 10.11 public beta users.

Xcode seems like it needs to be manually re-installed in general after the update. 

I wonder if it's a good idea to always drop the Xcode download url in addition to the Mac App Store info for when this happens. With more and more people using the public beta. 

![screenshot 2015-07-11 11 15 43](https://cloud.githubusercontent.com/assets/81390/8634216/4022833e-27be-11e5-93a2-d1d59c5314a1.png)

**Comment by ubuntudroid** [comment]
I don't even have Xcode installed (and in fact also didn't have before the update) and still everything works fine with just the command-line tools.

**Comment by remyo** [comment]
Good point. 

<code>brew doctor</code> just always recommends the latest Xcode.
