### ISSUE TITLE
ctags fails to build on El Capitan 10.11

### ISSUE THREAD

**Issue by evanrelf** [Homebrew/homebrew#41591]
```bash
~  λ brew install ctags
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Downloading https://downloads.sourceforge.net/ctags/ctags-5.8.tar.gz
==> Downloading from http://colocrossing.dl.sourceforge.net/project/ctags/ctags/5.8/ctags-
######################################################################## 100.0%
==> Downloading https://gist.githubusercontent.com/naegelejd/9a0f3af61954ae5a77e7/raw/16d9
######################################################################## 100.0%
==> Patching
patching file read.c
patching file read.h
patching file routines.c
patch unexpectedly ends in middle of line
Hunk #1 succeeded at 757 with fuzz 1.
==> ./configure --prefix=/usr/local/Cellar/ctags/5.8_1 --enable-macro-patterns --mandir=/u
==> make install
make: *** [args.o] Error 1
1 error generated.
make: *** [asm.o] Error 1
1 error generated.
make: *** [asp.o] Error 1

READ THIS: https://git.io/brew-troubleshooting

Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
```

Is this an issue with Homebrew, or the package? (or something else, like `make` or Xcode?)

**Comment by mistydemeo** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please read this and provide the requested diagnostics, thanks!

**Comment by evanrelf** [comment]
Sorry to bother you guys, I should've done some more Googling before making an issue :stuck_out_tongue_closed_eyes: 

For anyone else having trouble with installing `ctags` or other packages on El Capitan (10.11), **this is what I did to get it working**:

1. Download the Xcode 7 beta from [here](https://developer.apple.com/xcode/downloads/) (or use this [direct link to download Xcode 7 beta 3](http://adcdownload.apple.com/Developer_Tools/Xcode_7_beta_3/Xcode_7_beta_3.dmg))
2. Run `sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer` to switch to the beta version's updated tooling
