### ISSUE TITLE
Rust formula broken with OS X 10.11 public beta

### ISSUE THREAD

**Issue by arynhard** [Homebrew/homebrew#41598]
Cannot build rust on OS X 10.11 public beta:

````
==> ./configure --prefix=/Users/andrewrynhard/develop/homebrew/Cellar/rust/HEAD --disable-rpath --enable-clang --release-channel=nightly
configure: 
configure: note, user-provided CC looks like clang; CC=clang.
configure: 
configure: CFG_USING_CLANG      := 1 
configure: error: bad CLANG version: 7.0.0, need >=3.0svn
````

**Comment by DomT4** [comment]
Not much we can do about this I'm afraid. It's an upstream error message, being thrown from [here](https://github.com/rust-lang/rust/blob/master/configure#L997-L1009). Will need reporting upstream to [Rust](https://github.com/rust-lang/rust).
