### ISSUE TITLE
Why is brew adding _1 to package names?

### ISSUE THREAD

**Issue by nguillermin** [Homebrew/homebrew#41603]
I noticed this first on a python3 install, but now its popped up in other places.

    ==> Upgrading 20 outdated packages, with result:
    cairo 1.14.2_1, freetype 2.6_1, git 2.4.5, gtk+ 2.24.28_2, homebrew/x11/gtk-chtheme 0.3.1_1, gtk-murrine-engine 0.98.2_1, harfbuzz 0.9.41, libglade 2.6.4_1, librsvg 2.40.9_1, libtiff 4.0.4, mpfr 3.1.3, openssl 1.0.2d, pango 1.36.8_1, py2cairo 1.10.0_1, pygtk 2.24.0_1, python 2.7.10_1, qt 4.8.7, sip 4.16.8, vim 7.4.712_1, wireshark 1.12.6

I think it might be a permissions issue?

    ls -l /usr/local/Cellar/vim/
    total 0
    drwxr-xr-x  6 megablanc  admin  204 Jun 21 22:01 7.4.712
    drwxr-xr-x  6 megablanc  admin  204 Jul 11 15:44 7.4.712_1

**Comment by tdsmith** [comment]
That corresponds to `revision` in the formula DSL; it's incremented when we need to force users to rebuild packages (for compatibility with updated dependencies, etc) between package releases. Let us know if we can help with anything else.
