### ISSUE TITLE
Update to FreeImage 3.17.0

### ISSUE THREAD

**Issue by Extrawurst** [Homebrew/homebrew#41609]
It has been a year since the last version update by @acdha for the Freeimage formula: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/freeimage.rb

i am just a dumb user of homebrew but the changes are essentially:
the url is now: `https://downloads.sourceforge.net/project/freeimage/Source%20Distribution/3.17.0/FreeImage3170.zip` and the sha1 is now `6752c83798c2f81dee71a2e8bb11657068672669`
the diffs are essentially the same (i only tested the changes in `Makefile.gnu`) although the adjustments in `Source/OpenEXR/IlmImf/ImfAutoArray.h`don't seem to be necessary anymore...

**Comment by bfontaine** [comment]
Could you try and make a pull-request? This should help: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged
I’m happy to help you and answer any question you might have :smiley:
