### ISSUE TITLE
brew config shows wrong information

### ISSUE THREAD

**Issue by koallen** [Homebrew/homebrew#41616]
I'm currently running OS X El Capitan Public Beta 1 on my Macbook Air (Mid 2013). I was running `brew config` and I accidentally noticed that it says `CPU: quad-core 64-bit haswell` which is obviously wrong with a Macbook Air (maybe it counts the threads instead?)

Btw, I ran `xcode-select --install` to solve my problem with `brew update`. But now `brew doctor` says there is a newer release of CLT. `brew config` tells me that my CLT version is `CLT: 7.0.0.0.1.1436025195`. Is this the latest one? If so, why `brew doctor` says it is not?

**Comment by DomT4** [comment]
>  was running brew config and I accidentally noticed that it says CPU: quad-core 64-bit haswell

Pretty sure it's counting logical cores rather than physical cores. OS X will tell you the different, `sysctl hw.physicalcpu` and `sysctl hw.logicalcpu`.

> But now brew doctor says there is a newer release of CLT. brew config tells me that my CLT version is CLT: 7.0.0.0.1.1436025195

You should be up-to-date with that number I believe, yes. It would appear there's a slight bug in either our detection code or the CLT version reporting on OS X 10.11 - I'm waiting on the next DP to be completely sure either way at this point.

**Comment by koallen** [comment]
Ok, so `brew` counts the logical cores? I thought there was some bugs. I was thinking that counting physical cores is a better idea, but this doesn't bother me. Both way makes sense.

As for the second problem, I guess maybe this version CLT is not considered the latest version because it is kinda like a *pre-release* version of CLT. Or maybe it is because I have `Xcode 6.4` but `CLT 7.0.0.0.1.1436025195`?

**Comment by DomT4** [comment]
Yeah, we use `sysctl -n hw.ncpu` to grab the cores number, and on a dual-core modernish MacBook that should usually be `4`.

> I guess maybe this version CLT is not considered the latest version because it is kinda like a pre-release version of CLT

It doesn't make that much of a difference. We use the same version detection method for unstable and stable, It usually works without issue, but 10.11 has tweaked a few bits and pieces and it's possible the most recent CLT threw something out. I'm keeping an eye on it.

If you're using 10.11 you should update to Xcode 7.0 Betas.

**Comment by DomT4** [comment]
Closing as resolved on the CPU core question. Feel free to ping us if there's anything else you need :)
