### ISSUE TITLE
formula 'ntopng':  Page "/lua/login.lua" was not found

### ISSUE THREAD

**Issue by Drewshg312** [Homebrew/homebrew#41637]
Hi! Successfully installed ntopng from homebrew. Started redis server and started ntopng: $ sudo ntopng. When going to localhost:3000 in browser, getting this:

![untitled](https://cloud.githubusercontent.com/assets/10493450/8639536/b47ef324-2891-11e5-810c-a5e7bddc502e.jpg)

Could you please point me in right direction. Thank you.

**Comment by DomT4** [comment]
It's working okay here:

![screen shot 2015-07-12 at 20 45 03](https://cloud.githubusercontent.com/assets/6998367/8639601/e6b270f6-28d6-11e5-835e-0e651ce04e54.png)

Can you try halting the `redis` server and `ntopng` and then doing:

```
redis-server /usr/local/etc/redis.conf
ntopng
```

And then navigating to the `localhost:3000` page and seeing if the error is still there?

**Comment by Drewshg312** [comment]
Thanx. That's what I've got:

![untitled](https://cloud.githubusercontent.com/assets/10493450/8639641/2dc673f8-2895-11e5-8223-109eb2bc036e.jpg)

**Comment by DomT4** [comment]
Huh, odd.

What's the terminal response you get from `redis-server /usr/local/etc/redis.conf` and `ntopng`?

**Comment by Drewshg312** [comment]
$ redis-server /usr/local/etc/redis.conf
    47853:M 12 Jul 12:52:34.110 * Increased maximum number of open files to 10032 (it was originally set to 256).
                    _._
               _.-``__ ''-._
          _.-``    `.  `_.  ''-._           Redis 3.0.2 (00000000/0) 64 bit
      .-`` .-```.  ```\/    _.,_ ''-._
     (    '      ,       .-`  | `,    )     Running in standalone mode
     |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
     |    `-._   `._    /     _.-'    |     PID: 47853
      `-._    `-._  `-./  _.-'    _.-'
     |`-._`-._    `-.__.-'    _.-'_.-'|
     |    `-._`-._        _.-'_.-'    |           http://redis.io
      `-._    `-._`-.__.-'_.-'    _.-'
     |`-._`-._    `-.__.-'    _.-'_.-'|
     |    `-._`-._        _.-'_.-'    |
      `-._    `-._`-.__.-'_.-'    _.-'
          `-._    `-.__.-'    _.-'
              `-._        _.-'
                  `-.__.-'
    
    47853:M 12 Jul 12:52:34.112 # Server started, Redis version 3.0.2
    47853:M 12 Jul 12:52:34.115 * DB loaded from disk: 0.003 seconds
    47853:M 12 Jul 12:52:34.115 * The server is now ready to accept connections on port 6379
    ntopng

**Comment by Drewshg312** [comment]
Oh fuck I'm probably more stupid than I thought... Sorry

**Comment by DomT4** [comment]
Heh, is it working okay?

**Comment by Drewshg312** [comment]
yeah! Now it's working! Thanx. But what's the problem with redis LaunchAgent from homebrew?

**Comment by DomT4** [comment]
As far as I can see, there isn't one. It works fine for me when I use the launchd plist to start Redis as well.

**Comment by DomT4** [comment]
Closing since the problem has resolved for you, but feel free to flag it up again if you hit any further problems on this. Thanks!

**Comment by Drewshg312** [comment]
Well I've stopped the server and launched it as Agent again and probably the problem is somewhere here:

    $ sudo ntopng
    Password:
    12/Jul/2015 13:09:37 [src/Ntop.cpp:781] Setting local networks to 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,127.0.0.0/8,0.0.0.0/32,224.0.0.0/8,239.0.0.0/8,255.255.255.255/32,127.0.0.0/8
    12/Jul/2015 13:09:37 [src/Redis.cpp:93] Successfully connected to redis 127.0.0.1:6379@0
    12/Jul/2015 13:09:37 [src/PcapInterface.cpp:81] Reading packets from interface en0...
    12/Jul/2015 13:09:37 [src/Ntop.cpp:1029] Registered interface view en0 [id: 0]
    12/Jul/2015 13:09:37 [src/Ntop.cpp:999] Registered interface en0 [id: 0]
    12/Jul/2015 13:09:37 [src/PcapInterface.cpp:81] Reading packets from interface fw0...
    12/Jul/2015 13:09:37 [src/Ntop.cpp:1029] Registered interface view fw0 [id: 1]
    12/Jul/2015 13:09:37 [src/Ntop.cpp:999] Registered interface fw0 [id: 1]
    12/Jul/2015 13:09:37 [src/PcapInterface.cpp:81] Reading packets from interface awdl0...
    12/Jul/2015 13:09:37 [src/Ntop.cpp:1029] Registered interface view awdl0 [id: 2]
    12/Jul/2015 13:09:37 [src/Ntop.cpp:999] Registered interface awdl0 [id: 2]
    12/Jul/2015 13:09:37 [src/PcapInterface.cpp:81] Reading packets from interface bridge0...
    12/Jul/2015 13:09:37 [src/Ntop.cpp:1029] Registered interface view bridge0 [id: 3]
    12/Jul/2015 13:09:37 [src/Ntop.cpp:999] Registered interface bridge0 [id: 3]
    12/Jul/2015 13:09:37 [src/PcapInterface.cpp:81] Reading packets from interface utun0...
    12/Jul/2015 13:09:37 [src/Ntop.cpp:1029] Registered interface view utun0 [id: 4]
    12/Jul/2015 13:09:37 [src/Ntop.cpp:999] Registered interface utun0 [id: 4]
    12/Jul/2015 13:09:37 [src/PcapInterface.cpp:81] Reading packets from interface en1...
    12/Jul/2015 13:09:37 [src/Ntop.cpp:1029] Registered interface view en1 [id: 5]
    12/Jul/2015 13:09:37 [src/Ntop.cpp:999] Registered interface en1 [id: 5]
    12/Jul/2015 13:09:37 [src/PcapInterface.cpp:81] Reading packets from interface en2...
    12/Jul/2015 13:09:37 [src/Ntop.cpp:1029] Registered interface view en2 [id: 6]
    12/Jul/2015 13:09:37 [src/Ntop.cpp:999] Registered interface en2 [id: 6]
    12/Jul/2015 13:09:37 [src/PcapInterface.cpp:81] Reading packets from interface p2p0...
    12/Jul/2015 13:09:37 [src/Ntop.cpp:1029] Registered interface view p2p0 [id: 7]
    12/Jul/2015 13:09:37 [src/Ntop.cpp:999] Registered interface p2p0 [id: 7]
    12/Jul/2015 13:09:37 [src/PcapInterface.cpp:81] Reading packets from interface en3...
    12/Jul/2015 13:09:37 [src/Ntop.cpp:1029] Registered interface view en3 [id: 8]
    12/Jul/2015 13:09:37 [src/Ntop.cpp:999] Registered interface en3 [id: 8]
    12/Jul/2015 13:09:37 [src/PcapInterface.cpp:81] Reading packets from interface en4...
    12/Jul/2015 13:09:37 [src/Ntop.cpp:1029] Registered interface view en4 [id: 9]
    12/Jul/2015 13:09:37 [src/Ntop.cpp:999] Registered interface en4 [id: 9]
    12/Jul/2015 13:09:38 [src/PcapInterface.cpp:81] Reading packets from interface en5...
    12/Jul/2015 13:09:38 [src/Ntop.cpp:1029] Registered interface view en5 [id: 10]
    12/Jul/2015 13:09:38 [src/Ntop.cpp:999] Registered interface en5 [id: 10]
    12/Jul/2015 13:09:38 [src/PcapInterface.cpp:81] Reading packets from interface en6...
    12/Jul/2015 13:09:38 [src/Ntop.cpp:1029] Registered interface view en6 [id: 11]
    12/Jul/2015 13:09:38 [src/Ntop.cpp:999] Registered interface en6 [id: 11]
    12/Jul/2015 13:09:38 [src/PcapInterface.cpp:81] Reading packets from interface en7...
    12/Jul/2015 13:09:38 [src/Ntop.cpp:1029] Registered interface view en7 [id: 12]
    12/Jul/2015 13:09:38 [src/Ntop.cpp:999] Registered interface en7 [id: 12]
    12/Jul/2015 13:09:38 [src/PcapInterface.cpp:81] Reading packets from interface en8...
    12/Jul/2015 13:09:38 [src/Ntop.cpp:1029] Registered interface view en8 [id: 13]
    12/Jul/2015 13:09:38 [src/Ntop.cpp:999] Registered interface en8 [id: 13]
    12/Jul/2015 13:09:38 [src/PcapInterface.cpp:81] Reading packets from interface en9...
    12/Jul/2015 13:09:38 [src/Ntop.cpp:1029] Registered interface view en9 [id: 14]
    12/Jul/2015 13:09:38 [src/Ntop.cpp:999] Registered interface en9 [id: 14]
    12/Jul/2015 13:09:38 [src/PcapInterface.cpp:81] Reading packets from interface lo0...
    12/Jul/2015 13:09:38 [src/Ntop.cpp:1029] Registered interface view lo0 [id: 15]
    12/Jul/2015 13:09:38 [src/Ntop.cpp:999] Registered interface lo0 [id: 15]
    12/Jul/2015 13:09:38 [src/Utils.cpp:288] User changed to nobody
    12/Jul/2015 13:09:38 [src/main.cpp:235] PID stored in file /var/tmp/ntopng.pid
    Error Opening file /usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
    12/Jul/2015 13:09:38 [src/Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
    Error Opening file /usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
    12/Jul/2015 13:09:38 [src/Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
    Error Opening file /usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs/geoip/GeoLiteCity.dat
    12/Jul/2015 13:09:38 [src/Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs/geoip/GeoLiteCity.dat
    Error Opening file /usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs/geoip/GeoLiteCityv6.dat
    12/Jul/2015 13:09:38 [src/Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs/geoip/GeoLiteCityv6.dat
    12/Jul/2015 13:09:38 [src/HTTPserver.cpp:449] HTTPS Disabled: missing SSL certificate /usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs/ssl/ntopng-cert.pem
    12/Jul/2015 13:09:38 [src/HTTPserver.cpp:451] Please read https://svn.ntop.org/svn/ntop/trunk/ntopng/README.SSL if you want to enable SSL.
    12/Jul/2015 13:09:38 [src/HTTPserver.cpp:492] Web server dirs [/usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs][/usr/local/Cellar/ntopng/2.0/share/ntopng/scripts]
    12/Jul/2015 13:09:38 [src/HTTPserver.cpp:495] HTTP server listening on port 3000
    12/Jul/2015 13:09:38 [src/main.cpp:286] Working directory: /var/tmp/ntopng
    12/Jul/2015 13:09:38 [src/main.cpp:288] Scripts/HTML pages directory: /usr/local/Cellar/ntopng/2.0/share/ntopng
    12/Jul/2015 13:09:38 [src/Ntop.cpp:267] Welcome to ntopng x86_64 v.2.0.150601 - (C) 1998-15 ntop.org
    12/Jul/2015 13:09:38 [src/PeriodicActivities.cpp:53] Started periodic activities loop...
    12/Jul/2015 13:09:38 [src/RuntimePrefs.cpp:32] Dumping alerts into syslog
    12/Jul/2015 13:09:38 [src/NetworkInterface.cpp:1193] Started packet polling on interface en0 [id: 0]...
    12/Jul/2015 13:09:38 [src/NetworkInterface.cpp:1193] Started packet polling on interface fw0 [id: 1]...
    12/Jul/2015 13:09:38 [src/NetworkInterface.cpp:1193] Started packet polling on interface awdl0 [id: 2]...
    12/Jul/2015 13:09:38 [src/NetworkInterface.cpp:1193] Started packet polling on interface bridge0 [id: 3]...
    12/Jul/2015 13:09:38 [src/NetworkInterface.cpp:1193] Started packet polling on interface utun0 [id: 4]...
    12/Jul/2015 13:09:38 [src/NetworkInterface.cpp:1193] Started packet polling on interface en1 [id: 5]...
    12/Jul/2015 13:09:38 [src/NetworkInterface.cpp:1193] Started packet polling on interface en2 [id: 6]...
    12/Jul/2015 13:09:38 [src/NetworkInterface.cpp:1193] Started packet polling on interface p2p0 [id: 7]...
    12/Jul/2015 13:09:38 [src/NetworkInterface.cpp:1193] Started packet polling on interface en3 [id: 8]...
    12/Jul/2015 13:09:38 [src/NetworkInterface.cpp:1193] Started packet polling on interface en4 [id: 9]...
    12/Jul/2015 13:09:38 [src/NetworkInterface.cpp:1193] Started packet polling on interface en5 [id: 10]...
    12/Jul/2015 13:09:38 [src/NetworkInterface.cpp:1193] Started packet polling on interface en6 [id: 11]...
    12/Jul/2015 13:09:38 [src/NetworkInterface.cpp:1193] Started packet polling on interface en7 [id: 12]...
    12/Jul/2015 13:09:38 [src/NetworkInterface.cpp:1193] Started packet polling on interface en8 [id: 13]...
    12/Jul/2015 13:09:38 [src/NetworkInterface.cpp:1193] Started packet polling on interface en9 [id: 14]...
    12/Jul/2015 13:09:38 [src/NetworkInterface.cpp:1193] Started packet polling on interface lo0 [id: 15]...

**Comment by DomT4** [comment]
That log looks pretty much identical to mine. You shouldn't need `sudo` to launch ntopng.

**Comment by Drewshg312** [comment]
oh you are right - 'cause it's from homebrew... and yes, now it's working... I have no clue why it didn't work for me first time? I know it sounds silly but maybe for the first time redis needs to be started manually (not as a launchd plist)??
Anyways thank you! As always you are a lifesaver)

**Comment by DomT4** [comment]
No, I'm not sure why it'd refuse to work for you at first either. The only thing I can think of is that Redis encountered some kind of non-fatal error quietly, but hard to know.

No worries, happy things are working as desired now :)

**Comment by Drewshg312** [comment]
Hey man! I have the same issue now after restarting the machine  and nothing really helps. This formula works so weird! I've tried again to halt everything (redis agent and ntopng) and starting all manually:

**redis:**

    $ redis-server /usr/local/etc/redis.conf
    4924:M 13 Jul 12:07:47.054 * Increased maximum number of open files to 10032 (it was originally set to 2560).
                    _._
               _.-``__ ''-._
          _.-``    `.  `_.  ''-._           Redis 3.0.2 (00000000/0) 64 bit
      .-`` .-```.  ```\/    _.,_ ''-._
     (    '      ,       .-`  | `,    )     Running in standalone mode
     |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
     |    `-._   `._    /     _.-'    |     PID: 4924
      `-._    `-._  `-./  _.-'    _.-'
     |`-._`-._    `-.__.-'    _.-'_.-'|
     |    `-._`-._        _.-'_.-'    |           http://redis.io
      `-._    `-._`-.__.-'_.-'    _.-'
     |`-._`-._    `-.__.-'    _.-'_.-'|
     |    `-._`-._        _.-'_.-'    |
      `-._    `-._`-.__.-'_.-'    _.-'
          `-._    `-.__.-'    _.-'
              `-._        _.-'
                  `-.__.-'
    
    4924:M 13 Jul 12:07:47.056 # Server started, Redis version 3.0.2
    4924:M 13 Jul 12:07:47.061 * DB loaded from disk: 0.006 seconds
    4924:M 13 Jul 12:07:47.061 * The server is now ready to accept connections on port 6379
    4924:M 13 Jul 12:12:48.100 * 10 changes in 300 seconds. Saving...
    4924:M 13 Jul 12:12:48.101 * Background saving started by pid 5101
    5101:C 13 Jul 12:12:48.204 * DB saved on disk
    4924:M 13 Jul 12:12:48.205 * Background saving terminated with success

**ntopng:**

    $ sudo ntopng
    13/Jul/2015 12:10:05 [src/Ntop.cpp:781] Setting local networks to 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,127.0.0.0/8,0.0.0.0/32,224.0.0.0/8,239.0.0.0/8,255.255.255.255/32,127.0.0.0/8
    13/Jul/2015 12:10:05 [src/Redis.cpp:93] Successfully connected to redis 127.0.0.1:6379@0
    13/Jul/2015 12:10:05 [src/PcapInterface.cpp:81] Reading packets from interface en0...
    13/Jul/2015 12:10:05 [src/Ntop.cpp:1029] Registered interface view en0 [id: 0]
    13/Jul/2015 12:10:05 [src/Ntop.cpp:999] Registered interface en0 [id: 0]
    13/Jul/2015 12:10:05 [src/PcapInterface.cpp:81] Reading packets from interface fw0...
    13/Jul/2015 12:10:05 [src/Ntop.cpp:1029] Registered interface view fw0 [id: 1]
    13/Jul/2015 12:10:05 [src/Ntop.cpp:999] Registered interface fw0 [id: 1]
    13/Jul/2015 12:10:05 [src/PcapInterface.cpp:81] Reading packets from interface awdl0...
    13/Jul/2015 12:10:05 [src/Ntop.cpp:1029] Registered interface view awdl0 [id: 2]
    13/Jul/2015 12:10:05 [src/Ntop.cpp:999] Registered interface awdl0 [id: 2]
    13/Jul/2015 12:10:05 [src/PcapInterface.cpp:81] Reading packets from interface bridge0...
    13/Jul/2015 12:10:05 [src/Ntop.cpp:1029] Registered interface view bridge0 [id: 3]
    13/Jul/2015 12:10:05 [src/Ntop.cpp:999] Registered interface bridge0 [id: 3]
    13/Jul/2015 12:10:05 [src/PcapInterface.cpp:81] Reading packets from interface utun0...
    13/Jul/2015 12:10:05 [src/Ntop.cpp:1029] Registered interface view utun0 [id: 4]
    13/Jul/2015 12:10:05 [src/Ntop.cpp:999] Registered interface utun0 [id: 4]
    13/Jul/2015 12:10:05 [src/PcapInterface.cpp:81] Reading packets from interface en1...
    13/Jul/2015 12:10:05 [src/Ntop.cpp:1029] Registered interface view en1 [id: 5]
    13/Jul/2015 12:10:05 [src/Ntop.cpp:999] Registered interface en1 [id: 5]
    13/Jul/2015 12:10:05 [src/PcapInterface.cpp:81] Reading packets from interface en2...
    13/Jul/2015 12:10:05 [src/Ntop.cpp:1029] Registered interface view en2 [id: 6]
    13/Jul/2015 12:10:05 [src/Ntop.cpp:999] Registered interface en2 [id: 6]
    13/Jul/2015 12:10:05 [src/PcapInterface.cpp:81] Reading packets from interface p2p0...
    13/Jul/2015 12:10:05 [src/Ntop.cpp:1029] Registered interface view p2p0 [id: 7]
    13/Jul/2015 12:10:05 [src/Ntop.cpp:999] Registered interface p2p0 [id: 7]
    13/Jul/2015 12:10:05 [src/PcapInterface.cpp:81] Reading packets from interface en3...
    13/Jul/2015 12:10:05 [src/Ntop.cpp:1029] Registered interface view en3 [id: 8]
    13/Jul/2015 12:10:05 [src/Ntop.cpp:999] Registered interface en3 [id: 8]
    13/Jul/2015 12:10:05 [src/PcapInterface.cpp:81] Reading packets from interface en4...
    13/Jul/2015 12:10:05 [src/Ntop.cpp:1029] Registered interface view en4 [id: 9]
    13/Jul/2015 12:10:05 [src/Ntop.cpp:999] Registered interface en4 [id: 9]
    13/Jul/2015 12:10:05 [src/PcapInterface.cpp:81] Reading packets from interface en5...
    13/Jul/2015 12:10:05 [src/Ntop.cpp:1029] Registered interface view en5 [id: 10]
    13/Jul/2015 12:10:05 [src/Ntop.cpp:999] Registered interface en5 [id: 10]
    13/Jul/2015 12:10:05 [src/PcapInterface.cpp:81] Reading packets from interface en6...
    13/Jul/2015 12:10:05 [src/Ntop.cpp:1029] Registered interface view en6 [id: 11]
    13/Jul/2015 12:10:05 [src/Ntop.cpp:999] Registered interface en6 [id: 11]
    13/Jul/2015 12:10:05 [src/PcapInterface.cpp:81] Reading packets from interface en7...
    13/Jul/2015 12:10:05 [src/Ntop.cpp:1029] Registered interface view en7 [id: 12]
    13/Jul/2015 12:10:05 [src/Ntop.cpp:999] Registered interface en7 [id: 12]
    13/Jul/2015 12:10:05 [src/PcapInterface.cpp:81] Reading packets from interface en8...
    13/Jul/2015 12:10:05 [src/Ntop.cpp:1029] Registered interface view en8 [id: 13]
    13/Jul/2015 12:10:05 [src/Ntop.cpp:999] Registered interface en8 [id: 13]
    13/Jul/2015 12:10:05 [src/PcapInterface.cpp:81] Reading packets from interface en9...
    13/Jul/2015 12:10:05 [src/Ntop.cpp:1029] Registered interface view en9 [id: 14]
    13/Jul/2015 12:10:05 [src/Ntop.cpp:999] Registered interface en9 [id: 14]
    13/Jul/2015 12:10:05 [src/PcapInterface.cpp:81] Reading packets from interface lo0...
    13/Jul/2015 12:10:05 [src/Ntop.cpp:1029] Registered interface view lo0 [id: 15]
    13/Jul/2015 12:10:05 [src/Ntop.cpp:999] Registered interface lo0 [id: 15]
    13/Jul/2015 12:10:05 [src/Utils.cpp:288] User changed to nobody
    13/Jul/2015 12:10:05 [src/main.cpp:235] PID stored in file /var/tmp/ntopng.pid
    Error Opening file /usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
    13/Jul/2015 12:10:05 [src/Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
    Error Opening file /usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
    13/Jul/2015 12:10:05 [src/Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
    Error Opening file /usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs/geoip/GeoLiteCity.dat
    13/Jul/2015 12:10:05 [src/Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs/geoip/GeoLiteCity.dat
    Error Opening file /usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs/geoip/GeoLiteCityv6.dat
    13/Jul/2015 12:10:05 [src/Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs/geoip/GeoLiteCityv6.dat
    13/Jul/2015 12:10:05 [src/HTTPserver.cpp:449] HTTPS Disabled: missing SSL certificate /usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs/ssl/ntopng-cert.pem
    13/Jul/2015 12:10:05 [src/HTTPserver.cpp:451] Please read https://svn.ntop.org/svn/ntop/trunk/ntopng/README.SSL if you want to enable SSL.
    13/Jul/2015 12:10:05 [src/HTTPserver.cpp:492] Web server dirs [/usr/local/Cellar/ntopng/2.0/share/ntopng/httpdocs][/Users/Andryuwka/scripts]
    13/Jul/2015 12:10:05 [src/HTTPserver.cpp:495] HTTP server listening on port 3000
    13/Jul/2015 12:10:05 [src/main.cpp:286] Working directory: /var/tmp/ntopng
    13/Jul/2015 12:10:05 [src/main.cpp:288] Scripts/HTML pages directory: /usr/local/Cellar/ntopng/2.0/share/ntopng
    13/Jul/2015 12:10:05 [src/Ntop.cpp:267] Welcome to ntopng x86_64 v.2.0.150601 - (C) 1998-15 ntop.org
    13/Jul/2015 12:10:05 [src/PeriodicActivities.cpp:53] Started periodic activities loop...
    13/Jul/2015 12:10:05 [src/RuntimePrefs.cpp:32] Dumping alerts into syslog
    13/Jul/2015 12:10:05 [src/NetworkInterface.cpp:1193] Started packet polling on interface en0 [id: 0]...
    13/Jul/2015 12:10:05 [src/NetworkInterface.cpp:1193] Started packet polling on interface fw0 [id: 1]...
    13/Jul/2015 12:10:05 [src/NetworkInterface.cpp:1193] Started packet polling on interface awdl0 [id: 2]...
    13/Jul/2015 12:10:05 [src/NetworkInterface.cpp:1193] Started packet polling on interface bridge0 [id: 3]...
    13/Jul/2015 12:10:05 [src/NetworkInterface.cpp:1193] Started packet polling on interface utun0 [id: 4]...
    13/Jul/2015 12:10:05 [src/NetworkInterface.cpp:1193] Started packet polling on interface en1 [id: 5]...
    13/Jul/2015 12:10:05 [src/NetworkInterface.cpp:1193] Started packet polling on interface en2 [id: 6]...
    13/Jul/2015 12:10:05 [src/NetworkInterface.cpp:1193] Started packet polling on interface p2p0 [id: 7]...
    13/Jul/2015 12:10:05 [src/NetworkInterface.cpp:1193] Started packet polling on interface en3 [id: 8]...
    13/Jul/2015 12:10:05 [src/NetworkInterface.cpp:1193] Started packet polling on interface en4 [id: 9]...
    13/Jul/2015 12:10:05 [src/NetworkInterface.cpp:1193] Started packet polling on interface en5 [id: 10]...
    13/Jul/2015 12:10:05 [src/NetworkInterface.cpp:1193] Started packet polling on interface en6 [id: 11]...
    13/Jul/2015 12:10:05 [src/NetworkInterface.cpp:1193] Started packet polling on interface en7 [id: 12]...
    13/Jul/2015 12:10:05 [src/NetworkInterface.cpp:1193] Started packet polling on interface en8 [id: 13]...
    13/Jul/2015 12:10:05 [src/NetworkInterface.cpp:1193] Started packet polling on interface en9 [id: 14]...
    13/Jul/2015 12:10:05 [src/NetworkInterface.cpp:1193] Started packet polling on interface lo0 [id: 15]...

And one thing more -- `ntopng` doesn't work without `sudo`... I've tried even `brew reinstall ntopng`

What can it be?
