### ISSUE TITLE
Can't upgrade open-mpi to 1.8.6 on 10.11

### ISSUE THREAD

**Issue by caiofbpa** [Homebrew/homebrew#41644]
Apparently there's an issue with the Fortran compiler provided by Homebrew:

    configure: error: Could not run a simple Fortran program.  Aborting.

Am I missing something?

Here are the gist-logs: https://gist.github.com/anonymous/1acd9abe9281c110124c

**Comment by DomT4** [comment]
Looks potentially related to the failures in #41633.

**Comment by tdsmith** [comment]
Failure is:
```
configure:32369: checking if Fortran compiler works
configure:32398: /usr/local/bin/gfortran -o conftest -I/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/include/darwin   conftest.f  >&5
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
configure:32398: $? = 1
configure: program exited with status 1
configure: failed program was:
|       program main
| 
|       end
configure:32414: result: no
configure:32428: error: Could not run a simple Fortran program.  Aborting.
```

**Comment by tdsmith** [comment]
Can you try updating to the most recent version of the Command Line Tools from the app store (or maybe from https://developer.apple.com/downloads/ -- not sure how they're distributing the beta) and see if the error persists?

**Comment by caiofbpa** [comment]
There's no update on the App Store and I have no access to the developer preview: I am using the public beta.

Xcode warned me it was an outdated version, but there was no update in the App Store. I deleted it and had OS X download CLT by itself hoping it would get the latest version, but apparently it didn't.

I'm not sure how to proceed, I think this is my fault for trying to use developer stuff on a public beta.

Can anyone with the correct version of Xcode confirm if open-mpi build fails?

**Comment by DomT4** [comment]
> There's no update on the App Store and I have no access to the developer preview: I am using the public beta.

Anyone can obtain the Xcode 7.0 Beta from https://developer.apple.com/xcode/downloads/. You will need to log in, but you can do so with any standard Apple ID and you'll be permitted to download it.

**Comment by tdsmith** [comment]
Can you compile this program: https://gist.githubusercontent.com/tdsmith/ae9dd53cd5607a5d8eaa/raw/2e0d63f7ea82a5d80d9d44525654c19a5d709efd/example.f
with `gfortran`, just like `gfortran -o example example.f`?

**Comment by tdsmith** [comment]
open-mpi builds correctly for me on 10.11 PB1 with this configuration:
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 3947f85477e93e0bb0a6cc880b948204102c195c
Last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit haswell
OS X: 10.11-x86_64
Xcode: N/A
CLT: 7.0.0.0.1.1436025195
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.8.0_45
```

**Comment by tdsmith** [comment]
Note that this is the same "wrong" Xcode CLT version, so I don't think that's a factor. You may need to rebuild `gcc`.

**Comment by caiofbpa** [comment]
I rebuilt `gcc` and then `open-mpi` worked. Thanks @tdsmith and @DomT4 :+1: 

I'm not sure if we can do something to make people realize they should rebuild `gcc` after updating to 10.11 though.
