### ISSUE TITLE
Strange behavior of cmake in formula

### ISSUE THREAD

**Issue by xionglingfeng** [Homebrew/homebrew#41647]
Hi all, I am trying to build a formula of `libfreenect2`. The package depends on `jpeg-turbo` and `libusb-1.0` thus I added these lines in my formula

      depends_on "cmake" => :build
      depends_on "libusb"
      depends_on "jpeg-turbo"

I confirmed the depends are correctly installed by `brew install libfreenect2.rb` automatically.
However, `cmake` keep complaining about

    -- Found PkgConfig: /Volumes/Application/homebrew/bin/pkg-config (found version "0.28") 
    -- checking for module 'libusb-1.0'
    --   package 'libusb-1.0' not found

The most funny part is, when I build the package without `homebrew`:

    -- Found PkgConfig: /Volumes/Application/homebrew/bin/pkg-config (found version "0.28") 
    -- checking for module 'libusb-1.0'
    --   found libusb-1.0, version 1.0.19

I am totally confused why this happened here... any suggestions?

**Comment by dunn** [comment]
Can you post the current version of the formula you're working on?

**Comment by xionglingfeng** [comment]
require "formula"
    
    class Libfreenect2 < Formula
      desc "Drivers and libraries for the Xbox Kinect device version 2"
      homepage "http://openkinect.org"
      #url "https://github.com/OpenKinect/libfreenect/archive/v0.5.1.tar.gz"
      #sha1 "1f7296e50c27c07e2f57ee906c195cabf97c1438"

      head "https://github.com/OpenKinect/libfreenect2.git"
    
      option :universal
    
      depends_on "cmake" => :build
      depends_on "libusb"
      depends_on "jpeg-turbo"
    
      def install
        args = std_cmake_args
    
        if build.universal?
          ENV.universal_binary
          args << "-DCMAKE_OSX_ARCHITECTURES=#        {Hardware::CPU.universal_archs.as_cmake_arch_flags}"
        end
    
        mkdir "build" do
          system "cmake", "../examples/protonect", *args
          system "make install"
        end
      end
    end

**Comment by DomT4** [comment]
Try adding a `depends_on "pkg-config" => :build` line.

**Comment by xionglingfeng** [comment]
@DomT4 , I added that line and nothing changed. I also confirm that `pkg-config` is available before and after I added that line.

**Comment by DomT4** [comment]
Once you do `brew install xyz` that formula is placed under a kind of sandbox where it is no longer permitted access to the `pkg-config` (or anything else) in `/usr/local/bin`.

Not sure what your problem is here. It's working locally fine:

```
-- libfreenect will be installed to /usr/local/Cellar/libfreenect2/0.5.1
-- Headers will be installed to /usr/local/Cellar/libfreenect2/0.5.1/include/libfreenect
-- Libraries will be installed to /usr/local/Cellar/libfreenect2/0.5.1/lib
-- Found libusb-1.0:
--  - Includes: /usr/local/include/libusb-1.0
--  - Libraries: /usr/local/lib/libusb-1.0.dylib
```

**Comment by xionglingfeng** [comment]
My homebrew installation path is not the default one. Maybe this is the issue?

**Comment by DomT4** [comment]
Can you do a full `brew gist-logs mylocalformula`? It should work, and would allow us to see the whole config rather than just the failure.

**Comment by xionglingfeng** [comment]
https://gist.github.com/anonymous/6bc7b664fd138329329e

**Comment by DomT4** [comment]
Since you've filed this at `head-only` now let's do the debugging over there.
