### ISSUE TITLE
Error: wrong number of arguments (0 for 3)

### ISSUE THREAD

**Issue by joshuaellul** [Homebrew/homebrew#41659]
I tried: brew install wbennett/mspgcc/msp430-binutils 

Here's the output:
==> Installing msp430-binutils from wbennett/homebrew-mspgcc
==> Downloading http://ftp.gnu.org/gnu/binutils/binutils-2.22.tar.gz
######################################################################## 100.0%
Error: wrong number of arguments (0 for 3)
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula.rb:92:in `initialize'
/usr/local/Library/Taps/wbennett/homebrew-mspgcc/msp430-binutils.rb:15:in `new'
/usr/local/Library/Taps/wbennett/homebrew-mspgcc/msp430-binutils.rb:15:in `patches'
/usr/local/Library/Homebrew/formula.rb:947:in `prepare_patches'
/usr/local/Library/Homebrew/formula.rb:543:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:941:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:91:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:939:in `stage'
/usr/local/Library/Homebrew/formula.rb:542:in `brew'
/usr/local/Library/Homebrew/build.rb:107:in `install'
/usr/local/Library/Homebrew/build.rb:179:in `<main>'

**Comment by bfontaine** [comment]
This is an issue with https://github.com/wbennett/homebrew-mspgcc.

**Comment by joshuaellul** [comment]
Thanks!

On Mon, Jul 13, 2015 at 3:22 PM, Baptiste Fontaine <notifications@github.com
