### ISSUE TITLE
AWS Formula not up-to-date with 1.7.38 release

### ISSUE THREAD

**Issue by mark-schaal** [Homebrew/homebrew#41676]
New service APIs (CodeCommit, CodeDeploy, etc.) are currently unavailable in the 1.7.34 formula currently supported by Homebrew. Would love to request an update to the latest 1.7.38 release candidate.

**Comment by bfontaine** [comment]
Could you make a pull-request? This should help and I’m happy to answer any question:
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

**Comment by mark-schaal** [comment]
Looks like someone beat me to it. Formula is now at 1.7.38 so I will close this request.
