### ISSUE TITLE
qhull fails to build on 10.11 (probably earlier)

### ISSUE THREAD

**Issue by ejtttje** [Homebrew/homebrew#41674]
I actually think this is failing earlier than 10.11, as it is already reported here: http://permalink.gmane.org/gmane.os.apple.fink.devel/22769

qhull is within homebrew-science.  Here's a qhull.rb with updated patch section:
https://gist.github.com/ejtttje/40b1fbb562bedd52dd10

**Comment by tdsmith** [comment]
This issue was moved to Homebrew/homebrew-science#2517
