### ISSUE TITLE
osxfuse use the wrong version(2.7.6 should be changed to 2.7.5)

### ISSUE THREAD

**Issue by databill** [Homebrew/homebrew#41678]
**ntfs-3g** depends on wrong osxfuse, while osxfuse give the wrong version. The sourceforge website has no `2.7.6` version existed, only `2.80` or `2.7.5`. Please have a check. 

After downgrade the version to `2.7.5`, It's done!

```
url "https://github.com/osxfuse/osxfuse.git", :tag => "osxfuse-2.7.5",
                                                   :revision => "cc1913b417f68fd3a90c39678025d7604    854a7e7"
#url "https://github.com/osxfuse/osxfuse.git", :tag => "osxfuse-2.7.6",
#                                              :revision => "6ba1962e153e7a76f43bc2f80b0ba0ef    2da2cef9

depends_on UnsignedKextRequirement => [:cask => "osxfuse",
                                          :download => "http://sourceforge.net/projects/osxfuse/files/"]
```

**Comment by tdsmith** [comment]
This is correct; please see #38494. Is this causing trouble for you?

**Comment by databill** [comment]
I change the dependency to 2.7.5 and finish ntfs-3g upgrading. That's OK for me! 

I hope the rb files can be updated for others to avoid problems.

**Comment by DomT4** [comment]
`ntfs-3g` from the FUSE tap had no issues using the `2.7.6` tag to build against a month or so back FWIW.

**Comment by tdsmith** [comment]
Let us know if we can help with anything else.
