### ISSUE TITLE
Brew boost155 linking agains wrong system python path (user config issue)

### ISSUE THREAD

**Issue by kilojoules** [Homebrew/homebrew#41671]
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/my_custom_egg.egg/my_module.so, 2): Library not loaded: /System/Library/Frameworks/Python.framework/Versions/2.7/Python
      Referenced from: /usr/local/opt/boost155/lib/libboost_python.dylib

Don't ask me why, but my system Python somehow wound up in `/System/Library/Frameworks/Python.framework/Versions/Python`, not `/System/Library/Frameworks/Python.framework/Versions/2.7/Python`. Is there anyway I can instruct brew to link there?

**Comment by tdsmith** [comment]
Not trivially; please move the `Python` binary back into `2.7`.
