### ISSUE TITLE
No easy way to get android-platform-tools after installing android-sdk 

### ISSUE THREAD

**Issue by AlexTrotsenko** [Homebrew/homebrew#41702]
[`android-sdk`](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/android-sdk.rb) could be easily installed with brew, but not [`android-platform-tools`](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/android-platform-tools.rb).

1. `$ brew install android-sdk`

2. ` $ brew install android-platform-tools`
**Error**: Cannot install android-platform-tools because conflicting formulae are installed.
  android-sdk: because the Android Platform-tools are part of the Android SDK 

3. `$ adb`
It appears you do not have 'Android SDK Platform-tools' installed.
Use the 'android' tool to install them: 
    `android update sdk --no-ui --filter 'platform-tools'`

4. `$ android update sdk --no-ui --filter 'platform-tools'`
Refresh Sources:
  Fetching https://dl-ssl.google.com/android/repository/addons_list-2.xml
...
**Error**: Ignoring unknown package filter 'platform-tools'
Warning: The package filter removed all packages. There is nothing to install.
         Please consider trying to update again without a package filter.

The only way to install `platform-tools` for now is:
   - Get the list of available packages with indexes:
   `$ android list sdk`
      ...
   Packages available for installation or update: 52
   1- Android SDK Platform-tools, revision 22
   2- Android SDK Build-tools, revision 23 rc2
   3- Documentation for Android 'MNC' Preview SDK, revision 2
   4- SDK Platform Android 5.1.1, API 22, revision 2
   ...

   - Install Get Android SDK Platform-tools by providing proper index
   `$ android update sdk --no-ui --filter 1`
   Then you are also prompted to accept license agreement.

This does not looks like easy common `brew` solutions.

**Comment by mikemcquaid** [comment]
We'd review a pull request to make it easier to install but I don't think this is a Homebrew issue as much as an Android one.

**Comment by ynztyl10** [comment]
you should use command line like this
`android sdk`
then you can choose some packages what you want

**Comment by mikemcquaid** [comment]
This issue was actually fixed as-of https://github.com/Homebrew/homebrew/commit/ff78804acab05c7ed899b548053a8acac6461f45 where they are auto-installed.
