### ISSUE TITLE
gobject-introspection --with-tests fails to build on 10.11

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew#41707]
[Gist](https://gist.github.com/aw1621107/19c6ae056d774c0d8b4b). Installs fine without tests.

PKG_CONFIG_PATH doesn't seem to be properly set before ./configure is started. configure complains about not being able to find pixman. It's definitely installed, but it doesn't seem to have been added to PKG_CONFIG_PATH. 

Adding the location of pixman's pkgconfig folder in --interactive mode before trying to install changed the missing package to fontconfig. Adding that changed the missing package to freetype, then libpng, then configure succeeds.

**Comment by tdsmith** [comment]
I can reproduce on 10.10; it looks like dependencies of :build deps don't get added to PKG_CONFIG_PATH.

**Comment by tdsmith** [comment]
gobject-introspection builds but `make check` fails for me if I promote cairo to a runtime dependency: https://gist.github.com/8a4c217d38d6a3a99cf6

**Comment by tdsmith** [comment]
My favorite resolution to this problem is to remove `--with-tests` but it would be polite to tell the gobject-introspection devs that their tests fail.

Here's the test transcript without any patches applied: https://gist.github.com/45a725625ab84e24cbab

**Comment by tdsmith** [comment]
I'm getting HTTP 500 errors trying to post to Gnome's bugzilla, oy.

```
make check fails for gobject-introspection 1.44.0 on OS X 10.10.4.

In test_transformer, there are several failures of the form:

-             shared-library="libsletter.so"
+             shared-library="/unused/libsletter.dylib"

since OS X uses .dylib for shared libraries instead of .so. I'm not sure about the significance of "unused".

test_underscore_t_sed_filter also fails because of a stray newline:

======================================================================
FAIL: test_underscore_t_sed_filter (__main__.TestIdentifierFilter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_transformer.py", line 50, in test_underscore_t_sed_filter
    self.assertEqual(xformer.strip_identifier('test_t'), 'Context')
AssertionError: 'Context\n' != 'Context'

The test-suite.log is posted here: https://gist.github.com/anonymous/45a725625ab84e24cbab

Python is version 2.7.10. Xcode is version 6.4.
```

**Comment by tdsmith** [comment]
Filed https://bugzilla.gnome.org/show_bug.cgi?id=752468.
