### ISSUE TITLE
Adding the LADSPA header to Sox and ecasound formula 

### ISSUE THREAD

**Issue by notio** [Homebrew/homebrew#41706]
Hello,

It appears that formula for both Sox and ecasound are compiled without the LADSPA header. It would be SO COOL if LADSPA support for plug-ins could be added. It's currently beyond my chops, but I will try to provide enough information to make it easy to do.

The LADSPA website is here: http://www.ladspa.org

This O'Reilly.net article provides a good overview of getting LADSPA support compiled: http://archive.oreilly.com/pub/a/linux/2001/02/02/ladspa.html

Audacity has a set of pre-compiled LADSPA plug-ins: https://wiki.audacityteam.org/wiki/Ladspa_Plug-ins (Scroll to bottom of page.) 

The ecasound docs say that when ecasound is compiled with ladspa.c and the plugins are located in the proper directory, then 

`echo "ladspa-register" | ecasound -c`

should return a list of plugins. 

"In theory" this is as simple as adding the ladspa.c header to the build. But again, I don't know enough to say if this is accurate.

Thank you for Homebrew and the on-going support offered.

**Comment by xu-cheng** [comment]
Could you try and open a pull request? This [document](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should be helpful. Thanks!

**Comment by DomT4** [comment]
Welcome a PR here, Thanks!
