### ISSUE TITLE
Python post-install step fails on Yosemite

### ISSUE THREAD

**Issue by saulspatz** [Homebrew/homebrew#41712]
When running "brew upgrade" I get these messages:

/usr/local/Cellar/python/2.7.10_2/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed -
copying pip/_vendor/requests/cacert.pem -> build/lib/pip/_vendor/requests
copying pip/_vendor/distlib/_backport/sysconfig.cfg -> build/lib/pip/_vendor/distlib/_backport
running install_lib
copying build/lib/pip/__init__.py -> /usr/local/lib/python2.7/site-packages/pip
error: could not delete '/usr/local/lib/python2.7/site-packages/pip/__init__.py': Permission denied
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall python`

I tried again with "brew postinstall python" and got the same "permission denied" message.
The command "pip" no longer exists.

I'm running Yosemite 10.10.4.  Please advise.

**Comment by DomT4** [comment]
Looks like a permissions issue. What does `ls -lh /usr/local` output?

**Comment by saulspatz** [comment]
saul@Newton ✓ ls -lh /usr/local

total 80
-rw-r--r--    1 saul  admin   3.1K Jul  1 16:20 CODEOFCONDUCT.md
-rw-r--r--    1 saul  admin   1.1K Nov 29  2014 CONTRIBUTING.md
drwxr-xr-x   34 saul  admin   1.1K Jul 14 11:33 Cellar
drwxr-xr-x    3 saul  admin   102B Jul 14 11:23 Frameworks
-rw-r--r--    1 saul  admin   1.2K Feb  8 22:21 LICENSE.txt
drwxr-xr-x   11 saul  admin   374B Jul 14 11:19 Library
-rw-r--r--    1 saul  admin   2.2K Jul 14 11:19 README.md
-rw-r--r--    1 saul  admin    23K Jul  1 16:20 SUPPORTERS.md
drwxr-xr-x  265 saul  admin   8.8K Jul 14 11:33 bin
drwxr-xr-x    5 saul  admin   170B Jul 14 11:22 etc
drwxr-xr-x   39 saul  admin   1.3K Jul 14 11:22 include
drwxr-xr-x  193 saul  admin   6.4K Jul 14 11:33 lib
drwxr-xr-x   33 saul  admin   1.1K Jul 14 11:33 opt
drwxr-xr-x   17 saul  admin   578B Jul 14 11:23 share

**Comment by DomT4** [comment]
Well, the `/usr/local` directory itself looks fine. What about the same command on `/usr/local/lib/python2.7/site-packages/pip`? Does anything in that directory not have the permissions saul:admin?

**Comment by saulspatz** [comment]
Yes, all the files in that directory have permissions root:admin

**Comment by saulspatz** [comment]
I gather the next steps are too obvious to need mention, but just to be
sure, at this point should I do

sudo chown saul /usr/local/lib/python2.7/site-packages/pip/*

and then

brew postinstall python?

Thanks.

**Comment by DomT4** [comment]
Ah, perhaps you updated `pip` with `sudo` at some point accidentally. Yup, that should work.

`sudo chown -R saul:admin /usr/local/lib/python2.7/site-packages/pip/` otherwise.

**Comment by saulspatz** [comment]
That did it.  Thanks so much for your help.

**Comment by DomT4** [comment]
Great! Let us know if you hit any other issues :)
