### ISSUE TITLE
cmus v2.7.0 opus support

### ISSUE THREAD

**Issue by sda2b** [Homebrew/homebrew#41713]
Hello,

I installed cmus v2.7.0 but it doesn't play my opus files. (.opus extension) No problem with cmus on Arch Linux.
Is there a way to manullay install the opus plugin ?

Thanks for the help !

**Comment by bfontaine** [comment]
The formula doesn’t support opus (yet), the only way to have it for now is to compile cmus from source.

**Comment by sda2b** [comment]
Alright, thank you for the answer. I thought I had made a mistake. I will wait for an update. :)

**Comment by bfontaine** [comment]
@sda2b FYI you can now install cmus with opus: `brew update && brew install cmus --with-opusfile`.

**Comment by sda2b** [comment]
Hi !

Thanks a lot ! It works perfectly :)
