### ISSUE TITLE
new formula: how to make homebrew to clone the repo into "/usr/loca/Cellar/formuale/#{version}?"

### ISSUE THREAD

**Issue by Drewshg312** [Homebrew/homebrew#41752]
how to make homebrew to clone the repo into "/usr/loca/Cellar/formuale/#{version}?"
This is my unfinished formula:

    class Scirius < Formula
      desc "Rules manager for Suricata IDPS"
      homepage "https://github.com/StamusNetworks/scirius"
      url "https://github.com/StamusNetworks/scirius/archive/scirius-1.0.tar.gz"
      sha256 "fde16b3ac8f95e2990a44a9d85aa7c3ee6b55e59af9c27ded7319db19c19b2f5"
      head "https://github.com/StamusNetworks/scirius.git"
    
      depends_on :python if MacOS.version <= :snow_leopard
      #depends_on "python"
    
      resource "daemon" do
        url "https://pypi.python.org/packages/source/d/daemon/daemon-1.1.tar.gz"
        sha1 "520de0f52875417da165ff05167c33e6cdfb218c"
      end
    
      resource "Django" do
        url "https://pypi.python.org/packages/source/D/Django/Django-1.8.tar.gz"
        sha1 "19f5468e100b5004b020b59d4f457483122b3e45"
      end
    
      def install
        ENV.prepend_create_path "PYTHONPATH", libexec/"vendor/lib/python2.7/site-packages"
        %w[daemon Django].each do |r|
          resource(r).stage do
            system "python", *Language::Python.setup_install_args(libexec/"vendor")
          end
      end
        #I need this formula to do this:
        #system "git clone https://github.com/StamusNetworks/Scirius.git #{prefix}"
      end

So when I do `brew install --HEAD scirius` or `brew install scirius`
I'm getting this in **/usr/local/Cellar/scirius/HEAD** (or in **/usr/local/Cellar/scirius/1.0**):

    drwxr-xr-x  7 Andryuwka  admin   238B Jul 14 23:33 ./
    -rw-r--r--  1 Andryuwka  admin   275B Jul 14 23:33 INSTALL_RECEIPT.json
    -rw-r--r--  1 Andryuwka  admin   584B Jul 14 23:33 homebrew.mxcl.scirius.plist
    drwxr-xr-x  5 Andryuwka  admin   170B Jul 14 23:33 libexec/
    drwxr-xr-x  3 Andryuwka  admin   102B Jul 14 23:32 ../
    -rw-r--r--  1 Andryuwka  wheel    34K Apr 18 01:15 LICENSE
    -rw-r--r--  1 Andryuwka  wheel    10K Apr 18 01:15 README.rst

But should be this (the contain of repository):

    drwxr-xr-x  16 Andryuwka  admin   544B Jul 14 22:14 ./
    -rw-r--r--   1 Andryuwka  admin    13M Jul 14 22:14 db.sqlite3
    -rw-r--r--   1 Andryuwka  admin   249B Jul  9 19:26 requirements.txt
    -rw-r--r--   1 Andryuwka  admin   145B Jul  9 19:26 requirements_new.txt
    drwxr-xr-x  18 Andryuwka  admin   612B Jul  9 00:21 scirius/
    drwxr-xr-x  12 Andryuwka  admin   408B Jul  8 19:15 .git/
    drwxr-xr-x   4 Andryuwka  admin   136B Jul  6 16:35 git-sources/
    drwxr-xr-x  16 Andryuwka  admin   544B Jul  6 16:07 accounts/
    drwxr-xr-x  27 Andryuwka  admin   918B Jul  6 16:07 rules/
    drwxr-xr-x  19 Andryuwka  admin   646B Jul  6 16:07 suricata/
    -rw-r--r--   1 Andryuwka  admin    52B Jul  6 16:04 .gitignore
    -rw-r--r--   1 Andryuwka  admin    34K Jul  6 16:04 LICENSE
    -rw-r--r--   1 Andryuwka  admin    10K Jul  6 16:04 README.rst
    drwxr-xr-x   3 Andryuwka  admin   102B Jul  6 16:04 doc/
    -rw-r--r--   1 Andryuwka  admin   250B Jul  6 16:04 manage.py
    drwxr-xr-x   8 Andryuwka  admin   272B Jul  6 16:04 ../

So what should I do to get the `head` repository cloned to **/usr/local/Cellar/scirius/HEAD** or **/usr/local/Cellar/scirius/1.0**?

**Comment by dunn** [comment]
Is there no proper installation process—it's just supposed to be run from the repository?

**Comment by Drewshg312** [comment]
it just supposed to be run from repository
The installation process is just basically clone and run…

**Comment by dunn** [comment]
Replied in #41538; let's keep all the discussion in one place!
