### ISSUE TITLE
Compile failure on 10.11

### ISSUE THREAD

**Issue by oytunistrator** [Homebrew/homebrew#41751]
```
==> ./configure --disable-silent-rules --prefix=/private/tmp/makedepend20150715-
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/private/tmp/makedepend--xproto20150715-26527-6p8szt/xproto-7.0.25':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting

Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
```

**Comment by DomT4** [comment]
You can see 10.11 progress in #40837.

You seem to have a broader build error - What are you attempting to compile that's failing? The error looks like your Xcode or CLT package isn't up-to-date, your `brew config` will be useful on this.

**Comment by davidzchen** [comment]
I am getting the same error when trying to build pkg-config on 10.11.

**Comment by DomT4** [comment]
Please provide a `brew gist-logs pkg-config`.

**Comment by ablyler** [comment]
I've installed `pkg-config` and other packages just fine on OS X 10.11.

**Comment by agamble** [comment]
I think the issue is to do with xcode command line tools, try running `xcode-select --install`

**Comment by DomT4** [comment]
So far the majority of these errors have been:

1) Trying to use Xcode 6.x on 10.11.
2) Mismatched CLT & Xcode versions.
3) `xcode-select` pointing to an old Xcode rather than the Beta Xcode.

**Comment by DomT4** [comment]
Any update here?

**Comment by kwent** [comment]
`xcode-select --install` fixed it for me

**Comment by DomT4** [comment]
Presuming resolved.
