### ISSUE TITLE
Recursive dependencies of :build dependencies are not added to paths

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew#41759]
If a formula `depends_on "cairo" => :build`, only `/usr/local/opt/cairo/lib/pkgconfig` is added to PKG_CONFIG_PATH and fontconfig, pixman, etc are not. They are present when cairo is a "normal" dependency (i.e. `depends_on "cairo"`).

The same is true for $PATH.

This was surfaced by #41707.

**Comment by jacknagel** [comment]
fwiw - this was done intentionally in fdfc54961eb497b6dd854852dc604cb50c994fda. Not sure what that means here but hopefully that provides some context.

**Comment by jacknagel** [comment]
By the way, if you have questions about implementation stuff, feel free to ping me. A lot of this stuff is bus factor 1 so I'm happy to answer questions.

**Comment by tdsmith** [comment]
Thank you; I appreciate it! I'll try not to abuse your patience.

I agree that it should not be necessary to link against dependencies of build dependencies, and filtering them from the build environment makes sense. It seems like a formula's build dependency may occasionally have to _invoke_ its own dependencies but empirically that seems rare, and manually adding them to PATH in those situations is probably a better answer than making a global change.

Closing as not a bug.

**Comment by mikemcquaid** [comment]
> By the way, if you have questions about implementation stuff, feel free to ping me. A lot of this stuff is bus factor 1 so I'm happy to answer questions.

@jacknagel Really appreciate your attitude and help here, thanks dude :heart:
