### ISSUE TITLE
"brew install fish" fails on ubuntu

### ISSUE THREAD

**Issue by jab** [Homebrew/homebrew#41760]
looks like the formula is looking for `/usr/bin/sed` (which is where it lives on OS X) but on Ubuntu it's at `/bin/sed`.

```
/usr/bin/sed <fish.pc.in >fish.pc \
		-e "s,@sysconfdir\@,/home/wam/.linuxbrew/Cellar/fish/2.2.0/etc,g" \
		-e "s,@datadir\@,/home/wam/.linuxbrew/Cellar/fish/2.2.0/share,g" \
		-e "s,@docdir\@,/home/wam/.linuxbrew/Cellar/fish/2.2.0/share/doc/fish,g" \
		-e "s|@configure_input\@|fish.pc, generated from fish.pc.in by the Makefile. DO NOT MANUALLY EDIT THIS FILE!|g" \
		-e "s,@prefix\@,/home/wam/.linuxbrew/Cellar/fish/2.2.0,g" \
		-e "s,@fish_build_version\@,2.2.0,g" \

/bin/sh: 1: /usr/bin/sed: not found
make: *** [fish.pc] Error 127
```

**Comment by tdsmith** [comment]
This issue was moved to Homebrew/linuxbrew#485

**Comment by jab** [comment]
Sorry about that, I meant to open this in linuxbrew. I was reading the [Troubleshooting](https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md) page in the linuxbrew project and followed the "Create a new issue" link, not realizing it was taking me to the homebrew tracker rather than its own.
