### ISSUE TITLE
Error: undefined method `desc' for Formulary - When installing mcrypt for php55

### ISSUE THREAD

**Issue by esafwan** [Homebrew/homebrew#41762]
I am trying to install mcrypt extension for php55 using the command  `brew install php55-mcrypt`. After successfully installing all dependencies, it starts installing php55, which by the way i have already in place, and am using it. All I wanted was mcrypt. But at this point it throws up some error.  Added below:

>==> Pouring unixodbc-2.3.2_1.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/unixodbc/2.3.2_1: 31 files, 1.0M
==> Installing php55-mcrypt dependency: php55
Error: undefined method `desc' for Formulary::Formulae::Php70:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/php70.rb:5:in `<class:Php70>'
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/php70.rb:3:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/formula_installer.rb:195:in `block in check_conflicts'
/usr/local/Library/Homebrew/formula_installer.rb:194:in `select'
/usr/local/Library/Homebrew/formula_installer.rb:194:in `check_conflicts'
/usr/local/Library/Homebrew/formula_installer.rb:145:in `install'
/usr/local/Library/Homebrew/formula_installer.rb:349:in `install_dependency'
/usr/local/Library/Homebrew/formula_installer.rb:307:in `block in install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:307:in `each'
/usr/local/Library/Homebrew/formula_installer.rb:307:in `install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:212:in `compute_and_install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:147:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:165:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `install'
>/usr/local/Library/brew.rb:135:in `<main>' 

I am stuck here, I am not able to develop with mcrypt. :/

**Comment by mistydemeo** [comment]
Try `brew update`, then installing `php55-mcrypt` again.

**Comment by esafwan** [comment]
It worked. Thanks a ton. :)

**Comment by dipaco** [comment]
Worked great for me too! thanks mistydemeo,
