### ISSUE TITLE
Fig / docker-compose fails with recent version

### ISSUE THREAD

**Issue by beorn** [Homebrew/homebrew#41766]
Ref fig/docker-compose bug: https://github.com/docker/compose/issues/1484 - ssl_.py warns of an InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning

I am not sure what the right way to fix this is, but sure would like to see it working.  Maybe depend on non-system python to ensure we can get a higher version?  I don't know if it affects other docker-* packages as well.

**Comment by tdsmith** [comment]
This isn't a failure and the message is safe to ignore.

If you wanted to stop seeing it, it looks like we could ship PyOpenSSL with docker-compose or we could just pass Python options to squelch warnings.

**Comment by richardPFisk** [comment]
"This isn't a failure and the message is safe to ignore."

Whilst not a failure, the message prevents docker-compose from working. 

Is there an easy way to downgrade docker-compose with brew?

**Comment by tdsmith** [comment]
> Whilst not a failure, the message prevents docker-compose from working.

Can you clarify what isn't working?

**Comment by tdsmith** [comment]
Building with pyOpenSSL exposes whatever badness is happening with OpenSSL 1.0.2 if we link against Homebrew's openssl:
```
tim@rocketman:test$ docker-compose up --allow-insecure-ssl
SSL error: [Errno bad handshake] [('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')]
```

Previously: #38226

**Comment by tdsmith** [comment]
Comments are welcome on PR #41815.

**Comment by tdsmith** [comment]
I'm rejecting #41815 because I believe the warning is correct and benign (i.e. not a failure). The fix for this will be to install pyOpenSSL as a fig dependency once boot2docker/boot2docker#808 is favorably resolved.

**Comment by frio** [comment]
I don't believe the warning is benign.  When attempting to run `docker-compose start`, I am issued an `InsecurePlatformWarning`, at which point `docker-compose` exits.

**Comment by tdsmith** [comment]
boot2docker 1.8.0 has been released which fixes the relevant certificate issue, so we can move on this once we accept the new boot2docker.

**Comment by tdsmith** [comment]
Mooted because system Python is now 2.7.10 on the newest Yosemite release.

**Comment by richardPFisk** [comment]
Docker out of Docker (DooD) can be used to ensure the correct dependencies:

**Comment by richardPFisk** [comment]
Docker out of Docker (DooD) can be used to ensure the correct dependencies (including Python):

`
docker build --file=Dockerfile.elkstack -t rfisk/compose .
docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):/usr/bin/docker rfisk/compose 
`

Dockerfile:
`
FROM python:2.7
ADD . /code
WORKDIR /code

RUN apt-get install curl
RUN curl -L https://github.com/docker/compose/releases/download/1.3.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose

COPY docker-compose.yml docker-compose.yml

ENTRYPOINT ["docker-compose"]
CMD ["-f docker-compose.yml up -d"]
`
