### ISSUE TITLE
****Sourceforge is having issues*****

### ISSUE THREAD

**Issue by smarek** [Homebrew/homebrew#41778]
Can please someone verify and update signature? Final sourceforge redirect is through HTTP, and I can't believe such download to be legit.

```
> brew upgrade swig
==> Upgrading 1 outdated package, with result:
swig 3.0.6
==> Upgrading swig
==> Downloading https://downloads.sourceforge.net/project/swig/swig/swig-3.0.6/swig-3.0.6.tar.gz
==> Downloading from http://downloads.sourceforge.net/#!/project/swig/swig/swig-3.0.6/swig-3.0.6.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: c67f63ea11956106e4cda66416d5020330dc4ce2ee45057d39a9494ce33eca05
Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821
Archive: /Library/Caches/Homebrew/swig-3.0.6.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by bfontaine** [comment]
I get the checksum mismatch as well.

**Comment by bfontaine** [comment]
Sourceforge is having a problem:

```
$ url -sL https://downloads.sourceforge.net/project/swig/swig/swig-3.0.6/swig-3.0.6.tar.gz
<html><head>
<title>SourceForge</title>
<!-- <script src="/js/jquery.com/jquery-1.11.0.min.js"></script> -->
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="//sourceforge.net/js/mirrors.js"></script>
<script src="/js/sf.js"></script>
<script>
var DR_loc = DR_parse_hash_url();
if (DR_loc) {
    DR_sf_main(DR_loc);
} else {
    window.location.href = 'http://sourceforge.net/home.html';
}
</script>
</head><body>
<noscript>
We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
the use of javascript to function.  Please check back later.
</noscript>
</body></html>
```

**Comment by smarek** [comment]
I've also tried to obtain the file from alternative mirror, where the file got third, yet unknown checksum, what the hell is going on?
```
wget -c "https://www.mirrorservice.org/sites/download.sourceforge.net/pub/sourceforge/s/sw/swig/swig/swig-3.0.6/swig-3.0.6.tar.gz"
> sha256sum  swig-3.0.6.tar.gz 
283568a614c5233b61fcb2b777670ab3f1ab862d3f31df286e61a6101472d542  swig-3.0.6.tar.gz
```

**Comment by bfontaine** [comment]
I get the correct checksum:

```
$ curl -sL https://www.mirrorservice.org/sites/download.sourceforge.net/pub/sourceforge/s/sw/swig/swig/swig-3.0.6/swig-3.0.6.tar.gz | shasum -a 256
c67f63ea11956106e4cda66416d5020330dc4ce2ee45057d39a9494ce33eca05  -
```

**Comment by DomT4** [comment]
No problem from SF here:

```
Downloaded to: /usr/local/var/homebrew/cache/swig-3.0.6.tar.gz
SHA1: 901dd1888581289b5fdc6c0f4452109652bcf244
SHA256: c67f63ea11956106e4cda66416d5020330dc4ce2ee45057d39a9494ce33eca05
==> Verifying swig-3.0.6.tar.gz checksum
```

Or with the mirror:

```
https://www.mirrorservice.org/sites/download.sourceforge.net/pub/sourceforge/s/sw/swig/swig/swig-3.0.6/swig-3.0.6.tar.gz | shasum -a 256
c67f63ea11956106e4cda66416d5020330dc4ce2ee45057d39a9494ce33eca05  -
```

**Comment by smarek** [comment]
Well, no it went ok, with another mirror, strange. 

Shall we close the ticket as problem caused by sourceforge service disruption?

```
> brew upgrade swig
==> Upgrading 1 outdated package, with result:
swig 3.0.6
==> Upgrading swig
==> Downloading https://downloads.sourceforge.net/project/swig/swig/swig-3.0.6/swig-3.0.6.tar.gz
==> Downloading from http://kent.dl.sourceforge.net/project/swig/swig/swig-3.0.6/swig-3.0.6.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/swig/3.0.6
==> make
==> make install
🍺  /usr/local/Cellar/swig/3.0.6: 729 files, 7.1M, built in 46 seconds
```

**Comment by smarek** [comment]
And sorry, @bfontaine, I inspected the file, and I accidentally concatenated sourceforge error response and correct file from mirrorservice.org, thus the third strange checksum. Checking again, it came out just fine.
```
> wget -c "https://www.mirrorservice.org/sites/download.sourceforge.net/pub/sourceforge/s/sw/swig/swig/swig-3.0.6/swig-3.0.6.tar.gz"
--2015-07-16 18:47:15--  https://www.mirrorservice.org/sites/download.sourceforge.net/pub/sourceforge/s/sw/swig/swig/swig-3.0.6/swig-3.0.6.tar.gz
Resolving www.mirrorservice.org (www.mirrorservice.org)... 212.219.56.184
Connecting to www.mirrorservice.org (www.mirrorservice.org)|212.219.56.184|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5911929 (5.6M) [application/x-gzip]
Saving to: 'swig-3.0.6.tar.gz'

swig-3.0.6.tar.gz                       100%[===============================================================================>]   5.64M  2.50MB/s   in 2.3s   

2015-07-16 18:47:17 (2.50 MB/s) - 'swig-3.0.6.tar.gz' saved [5911929/5911929]

[18:47:17] mareksebera@Mareks-MacBook-Pro /private/tmp (0)                                                                                                    
> sha256sum swig-3.0.6.tar.gz 
c67f63ea11956106e4cda66416d5020330dc4ce2ee45057d39a9494ce33eca05  swig-3.0.6.tar.gz
```

**Comment by codekitchen** [comment]
This is affecting the `unfs3` formula as well -- I'd imagine it's affecting all sourceforge downloads.

**Comment by DomT4** [comment]
[Yup](https://twitter.com/sfnet_ops/status/621702261685686272).

**Comment by DomT4** [comment]
Renamed the issue in the hope people check this issue before filing new Sourceforge failures.

**Comment by viktorahlstrom** [comment]
Tried to download `gnuplot`, mismatched:
`Expected: 7cbc557e71df581ea520123fb439dea5f073adcc9010a2885dc80d4ed28b3c47`
`Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d024882`

**Comment by viktorahlstrom** [comment]
Well, that was odd.  

    io@conroe> wget http://kent.dl.sourceforge.net/project/gnuplot/gnuplot/5.0.1/gnuplot-5.0.1.tar.gz
    --2015-07-16 16:58:37--  http://kent.dl.sourceforge.net/project/gnuplot/gnuplot/5.0.1/gnuplot-5.0.1.tar.gz
    Resolving kent.dl.sourceforge.net... 212.219.56.185
    Connecting to kent.dl.sourceforge.net|212.219.56.185|:80... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 4963747 (4.7M) [application/x-gzip]
    Saving to: 'gnuplot-5.0.1.tar.gz'

    100%[===========================================================================================================================================>] 4,963,747   1.44MB/s   in 3.3s

    2015-07-16 16:58:41 (1.44 MB/s) - 'gnuplot-5.0.1.tar.gz' saved [4963747/4963747]
    io@conroe> brew install gnuplot
    ==> Downloading https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.1/gnuplot-5.0.1.tar.gz
    Already downloaded: /Library/Caches/Homebrew/gnuplot-5.0.1.tar.gz
    ==> ./configure
    ==> make
    ==> make install
    🍺  /usr/local/Cellar/gnuplot/5.0.1: 44 files, 2.3M, built in 99 seconds

**Comment by kirkelifson** [comment]
The issue should just be called "Sourceforge".

**Comment by tdsmith** [comment]
I know this is frustrating but please try to remain constructive here.

**Comment by n054** [comment]
Was just doing commits from hivehand,homebrew. It was authored in 2013. Probably going to have to revert all those sha1 commits as they are all changing to sha256. Those tests also are from 2013.

**Comment by L2G** [comment]
News item from The Register: ["Sourceforge goes TITSUP thanks to storage fault"](http://www.theregister.co.uk/2015/07/17/souceforge_titsup/)

**Comment by shaneburrell** [comment]
Its been over 22 hours since sourceforge went down.  If you are in a bind with this just find alt download (Google search) and put into /Library/Caches/Homebrew/ .

**Comment by mikepurvis** [comment]
Curiously, I've found in a number of cases that a download from the website works correctly, but the exact same URL in curl or wget returns an error. Should Homebrew have an option for sending a referrer header, the way caskroom does?

**Comment by codekitchen** [comment]
I think the core problem is that sourceforge now does a redirect to a url that has an anchor (hash) component -- the download process apparently involves some client-side javascript logic now.

For instance:

    ==> Downloading https://downloads.sourceforge.net/project/unfs3/unfs3/0.9.22/unfs3-0.9.22.tar.gz
    ==> Downloading from http://downloads.sourceforge.net/#!/project/unfs3/unfs3/0.9.22/unfs3-0.9.22.tar.gz

Since curl/wget are just going to query that 2nd url from the server, the anchor part of the URI is going to get dropped and the client-side logic clearly won't ever execute. We can't very well embed a full browser inside homebrew, so it seems like the only fix is to find an alternate download mechanism (or convince sourceforge to remove this new way of redirecting).

**Comment by mikepurvis** [comment]
Interesting. Can the hash be encoded in such a way that curl won't strip it?

Alternatively, you can link to the file on a specific mirror (check your Chrome downloads window for where it's actually coming from), though that's potentially riskier.

**Comment by codekitchen** [comment]
The hash part of a url is purely client-side, so it doesn't matter if curl strips it, the server isn't going to do anything with it (or even see it) either way. There must be browser-side javascript that is doing something with it.

**Comment by DomT4** [comment]
Until Sourceforge confirm the change is permanent we won't accept any PRs to adjust the mechanism, or individual formulae - At the moment a giant chunk of SF is still in crisis mode and we're not going to rush to fix a problem that may be transient.

We know this is frustrating, both for users and for us maintainers. We moved our own binary packages off of SF several months ago to handle this problem, but obviously we have little control over why & where upstream projects host.

**Comment by L2G** [comment]
One-liner that's hopefully helpful to others:
```
find /Library/Caches/Homebrew -depth 1 -a -type f -a -size -1k -exec shasum -a 256 \{\} \; | awk '$1 == "818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821" {print $2}'
```

**Comment by DomT4** [comment]
According to SF, service has been [restored](https://twitter.com/sfnet_ops/status/622236074052464641). Closing here in the hope I don't have to tag a new broad SF issue in the near future. Thanks for your patience everyone, the downtime is frustrating for us all.

**Comment by DavidCWGA** [comment]
If anyone cares, this is an interesting post about the downtime: https://www.reddit.com/r/sysadmin/comments/3do9k0/sourceforge_is_down_due_to_storage_problems_no_eta/ct77o49

**Comment by jackalcooper** [comment]
You can copy the url and open it in your browser. Download it and copy it to the cache dictionary and run the script again.
