### ISSUE TITLE
grace openmotif / lesstif conflict

### ISSUE THREAD

**Issue by bhawkins** [Homebrew/homebrew#41788]
It seems the grace plotting tool (homebrew/x11/grace) is built against lesstif.  When I try to launch xmgrace, it complains about missing libXm.2.dylib.  When I try "brew link lesstif" I get a bunch of errors, presumably because openmotif is already linked.  Since I'm not sure if "brew link --force" will cause problems, I just manually created the symlink with

    cd /usr/local/lib
    ln -s ../Cellar/lesstif/0.95.2/lib/libXm.2.dylib

Is there a cleaner solution, or maybe a problem with the formula?  This is on a Yosemite MBP.

**Comment by DomT4** [comment]
> When I try "brew link lesstif" I get a bunch of errors, presumably because openmotif is already linked.

This is happening because `opemotify` is aware `lesstif` exists and will stop you linking one on top of the other, but `lesstif` isn't aware `opemotify` exists because we can't presume every use has tapped `homebrew/x11` (Obviously).

Ideally, the stuff that currently builds against `lesstif` needs to be transitioned to using `openmotif` and then `lesstif` killed off.

**Comment by bhawkins** [comment]
Oh okay, I wasn't aware of these nuances when I did a "brew install openmotif" so I could build a piece of custom software.  "brew rm openmotif" followed by "brew link lesstif" gets grace to work without shenanigans.  I recompiled my other code against lesstif.

**Comment by DomT4** [comment]
Going to reopen here so I remember to check out the situation soonish and try and work out what to do with `openmotif`/`lesstif`. They are both complete replacements for each other, allegedly, and `lesstif` stopped being developed (Per upstream's statement) a few days after `openmotif` was made open-source under a permissive license.

**Comment by mistydemeo** [comment]
I went ahead and migrated all of the homebrew/x11 formulae to openmotif.

**Comment by DomT4** [comment]
You are *awesome* :bow:. I don't know if we want to deal with `xastir` in the core and try to migrate it to X11 or make the `lesstif` dependency optional, unless you're happy to keep `lesstif` around?

**Comment by mistydemeo** [comment]
Huh, I wonder how xastir got missed when stuff got moved? Yeah, I'll migrate it too. We might as well keep the lesstif formula in case anyone wants it but let's standardize on having all of our formulae using openmotif.

**Comment by DomT4** [comment]
Looks like it doesn't define any `x11` link directly, so it's possible was just missed. Cool, sounds great :). As far as I know `lesstif` still compiles nicely even if not officially supported, so no objection to keeping it around.

**Comment by mistydemeo** [comment]
One of its dependencies is MIA with Sourceforge down, but I'll look into this soon.

**Comment by mistydemeo** [comment]
I think I see the real reason no one tackled this: xastir has an absurdly large dependency tree. Ouch.

**Comment by mistydemeo** [comment]
PRs for xastir: Homebrew/homebrew-x11#106, #41845.

**Comment by DomT4** [comment]
Thanks Misty! Hope the dep tree wasn't too annoying :). Closing here.
