### ISSUE TITLE
Missing dialog shared library for percona-server

### ISSUE THREAD

**Issue by solomonty** [Homebrew/homebrew#41789]
Trying to connect to a server that uses the PAM plugin for authentication fails because the dialog library is missing from the distribution. The PAM plugin is not needed for the Mac distribution but the dialog library is needed.

>ERROR 2059 (HY000): Authentication plugin 'dialog' cannot be loaded: dlopen(/usr/local/Cellar/percona-server/5.6.25-73.0/lib/mysql/plugin/dialog.so, 2): image not found

**Comment by DomT4** [comment]
Is this something we can fix? We'd welcome a PR on this if so.

**Comment by DomT4** [comment]
PR welcome, Thanks!

**Comment by solomonty** [comment]
Why was this closed? Was it fixed?

**Comment by DomT4** [comment]
Don't think so. It was closed because none of the team members know how to solve this particular issue and once an Issue drops off the frontpage of the repo nobody who isn't a team member will go looking for or find it. We still welcome a PR from anyone if it's an issue and they wish to fix it.
