### ISSUE TITLE
libgphoto2 SHA256 mismatch

### ISSUE THREAD

**Issue by slbug** [Homebrew/homebrew#41782]
Expected: 031a262e342fae43f724afe66787947ce1fb483277dfe5a8cf1fbe92c58e27b6
Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821
Archive: /Library/Caches/Homebrew/libgphoto2-2.5.8.tar.bz2

**Comment by slbug** [comment]
homebrew version 0.9.5

**Comment by DomT4** [comment]
Sourceforge is [having issues](https://twitter.com/sfnet_ops/status/621702261685686272). Not much we can do but wait it out I'm afraid, Sorry!
