### ISSUE TITLE
error Installing libmatio from homebrew/homebrew-science

### ISSUE THREAD

**Issue by physicsman** [Homebrew/homebrew#41796]
BrodskyMacBookPro:lua---mattorch jmcdonald$ brew install libmatio
Error: No available formula for libmatio 
Searching formulae...
Searching taps...
homebrew/science/libmatio
BrodskyMacBookPro:lua---mattorch jmcdonald$ brew install homebrew/science/libmatio
==> Tapping homebrew/science
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-science'...
remote: Counting objects: 537, done.
remote: Compressing objects: 100% (533/533), done.
remote: Total 537 (delta 4), reused 160 (delta 3), pack-reused 0
Receiving objects: 100% (537/537), 421.22 KiB | 0 bytes/s, done.
Resolving deltas: 100% (4/4), done.
Checking connectivity... done.
Tapped 530 formulae (557 files, 2.8M)
==> Installing libmatio from homebrew/homebrew-science
==> Downloading https://downloads.sourceforge.net/project/matio/matio/1.5.2/matio-1.5.2.tar.gz
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: d5a83a51eb2550d75811d2dde967ef3e167d4f52
Actual: ea60df615387f47bdfdfe4da48f6567c4ec60f74
Archive: /Library/Caches/Homebrew/libmatio-1.5.2.tar.gz
To retry an incomplete download, remove the file above.

**Comment by dunn** [comment]
Unfortunately this isn't something we can solve; SourceForge is just having problems today (#41778).  Hopefully they'll sort things out soon.
