### ISSUE TITLE
fontforge failed to build on 10.9

### ISSUE THREAD

**Issue by L2G** [Homebrew/homebrew#41797]
[Logs saved with `brew gist-logs fontforge`](https://gist.github.com/anonymous/03b1795a92b872238ed1).

**Comment by L2G** [comment]
The fatal error:

```
clang: error: no such file or directory: '/usr/lib/libltdl.3.1.0.dylib'
```
My Mavericks system has /usr/lib/libltdl.la but no /usr/lib/libltdl.3.1.0.dylib.

**Comment by tdsmith** [comment]
/usr/lib/libltdl.la might be stale; can you gist it or try moving it out of the way? I don't have one so I don't think Apple put it there.

**Comment by L2G** [comment]
Maybe it was left over after upgrading to Mavericks from an earlier OS X.

https://gist.github.com/L2G/6af31affc8a242acd39d

**Comment by tdsmith** [comment]
Could be. That's definitely what's confusing libtool; I'd try nuking it.

**Comment by L2G** [comment]
Renaming it to /usr/lib/libltdl.la.HIDE seems to have done the trick.

**Comment by DomT4** [comment]
Closing as resolved. Haven't seen this reported by anyone else, so hopefully it was just some bad luck.
