### ISSUE TITLE
brew install ta-lib raises SHA1 mismatch

### ISSUE THREAD

**Issue by femtotrader** [Homebrew/homebrew#41814]
Hello,

I facing a problem to install ta-lib

    $ brew install ta-lib
    ==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/ta-lib-0.4.0.yosemite.bottle.1.tar.gz

    curl: (60) SSL certificate problem: Invalid certificate chain
    More details here: http://curl.haxx.se/docs/sslcerts.html

    curl performs SSL certificate verification by default, using a "bundle"
     of Certificate Authority (CA) public keys (CA certs). If the default
     bundle file isn't adequate, you can specify an alternate file
     using the --cacert option.
    If this HTTPS server uses a certificate signed by a CA represented in
     the bundle, the certificate verification probably failed due to a
     problem with the certificate (it might be expired, or the name might
     not match the domain name in the URL).
    If you'd like to turn off curl's verification of the certificate, use
     the -k (or --insecure) option.
    Error: Failed to download resource "ta-lib"
    Download failed: https://downloads.sf.net/project/machomebrew/Bottles/ta-lib-0.4.0.yosemite.bottle.1.tar.gz
    Warning: Bottle installation failed: building from source.
    ==> Downloading https://downloads.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz
    Already downloaded: /Library/Caches/Homebrew/ta-lib-0.4.0.tar.gz
    Error: SHA1 mismatch
    Expected: b326b91e79ca1e569e95aad91e87a38640dd5f1b
    Actual: ea60df615387f47bdfdfe4da48f6567c4ec60f74
    Archive: /Library/Caches/Homebrew/ta-lib-0.4.0.tar.gz
    To retry an incomplete download, remove the file above.

I try to remove `/Library/Caches/Homebrew/ta-lib-0.4.0.tar.gz`

and 

    $ brew install ta-lib --insecure

But it still raise same error

Any idea ?

I'm using Mac OS X 10.10

**Comment by dunn** [comment]
Looks like SF is still having problems; see #41778. Hope they fix their servers soon :(
