### ISSUE TITLE
bind should depend on json-c

### ISSUE THREAD

**Issue by tg90nor** [Homebrew/homebrew#41823]
$ dig google.com
    dyld: Library not loaded: /usr/local/lib/libjson-c.2.dylib
      Referenced from: /usr/local/bin/dig
      Reason: image not found
    [1]    41615 trace trap  dig google.com

dig works fine if I brew install json-c

**Comment by dunn** [comment]
Feel like [opening a pull request](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md), adding the dependency (and maybe a test)? I can help if you have questions.
