### ISSUE TITLE
sha1 mismatch for optipng

### ISSUE THREAD

**Issue by DavidCWGA** [Homebrew/homebrew#41829]
$ brew cleanup
    $ brew update
    Already up-to-date.
    $ brew install optipng
    ==> Downloading https://downloads.sourceforge.net/project/optipng/OptiPNG/optipng-0.7.5/optipng-0.7.5.
    ==> Downloading from http://downloads.sourceforge.net/#!/project/optipng/OptiPNG/optipng-0.7.5/optipng
    ######################################################################## 100.0%
    Error: SHA1 mismatch
    Expected: 30b6c333d74fc0f5dc83004aace252fa3321368b
    Actual: ea60df615387f47bdfdfe4da48f6567c4ec60f74
    Archive: /Library/Caches/Homebrew/optipng-0.7.5.tar.gz
    To retry an incomplete download, remove the file above.

**Comment by shaneburrell** [comment]
Sourceforge is running off the rails and has been for a long time. Hopefully upstreams move from them in droves.  Till then you can find the exact file via google search and place it in Library/Caches/Homebrew to get it working for now.

**Comment by DavidCWGA** [comment]
Dupe of #41778
