### ISSUE TITLE
Error: uninitialized constant HOMEBREW_INTERNAL_COMMAND_ALIASES

### ISSUE THREAD

**Issue by kl2792** [Homebrew/homebrew#41831]
Was told to report a bug in the following message:

Error: uninitialized constant HOMEBREW_INTERNAL_COMMAND_ALIASES
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/brew.rb:83:in `<main>'

**Comment by dunn** [comment]
We'll need a bit more information to figure out what's going on.  What command did you try to run?  Is that all the output you got?

**Comment by kl2792** [comment]
It outputs this message every time I try to run a command with brew.

**Comment by bfontaine** [comment]
Please run `cd /usr/local && git reset --hard FETCH_HEAD` and try again.

**Comment by DomT4** [comment]
Ping?

**Comment by kl2792** [comment]
Sorry about the late reply. It does work (albeit with some extra warnings when I run brew doctor). Thank you!
