### ISSUE TITLE
brew update hangs

### ISSUE THREAD

**Issue by leonklingele** [Homebrew/homebrew#41834]
So I did my daily `brew update --verbose`
Output:
```
==> git symbolic-ref --short HEAD
master
==> git rev-parse -q --verify HEAD
836afe0685334784d8766ce2f4709e2f87089551
git config core.autocrlf false
git pull origin refs/heads/master:refs/remotes/origin/master

```

Then it hangs. SIGINT:
```
^COne sec, just cleaning up
git checkout master
Already on 'master'
git reset --hard 836afe0685334784d8766ce2f4709e2f87089551
HEAD is now at 836afe0 gobject-introspection: use HTTPS url
Error: Failure while executing: git pull origin refs/heads/master:refs/remotes/origin/master
```

What's the problem? How can this be debugged?

**Comment by DomT4** [comment]
How long does it hang?

**Comment by leonklingele** [comment]
I let it run for about 5 minutes.

**Comment by polaris** [comment]
I have exactly the same problem. I hangs for more then 10 minutes now.

    $ brew update --verbose
    ==> git symbolic-ref --short HEAD
    master
    ==> git rev-parse -q --verify HEAD
    139b2b3584ab4615b8921c32b823bfce69c8722c
    git config core.autocrlf false
    git pull origin refs/heads/master:refs/remotes/origin/master

**Comment by leonklingele** [comment]
This seems to be a problem with GH and the homebrew repo.
You can't even do `git clone https://github.com/Homebrew/homebrew`

**Comment by DomT4** [comment]
No problems here, either with clone or update. Does `cd $(brew --prefix) && git fetch && git reset --hard origin/master` bring any more joy for either of you?

**Comment by leonklingele** [comment]
`git fetch` also hangs as described above.

**Comment by DomT4** [comment]
Potentially. I'm based in the UK and not seeing any problems. It would be some terrible luck to have Github issues on the same day as Sourceforge issues :sweat:.

**Comment by leonklingele** [comment]
Closing this as it seems to be related to Github itself.
