### ISSUE TITLE
graphicsmagick 1.3.21 wrong SHA fingerprint

### ISSUE THREAD

**Issue by akozlov75** [Homebrew/homebrew#41839]
Mac os x 10.11 (El capitan) ->
$ brew install graphicsmagick
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Downloading https://downloads.sourceforge.net/project/graphicsmagick/graphicsmagick/1.3.21/GraphicsMagick-1.3.21.tar.bz2
==> Downloading from http://downloads.sourceforge.net/#!/project/graphicsmagick/graphicsmagick/1.3.21/GraphicsMagick-1.3.21.tar.bz2
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: a0ce08f2710c158e39faa083463441f6eeeecce07dbd59510498ffa4e0b053d1
Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821
Archive: /Library/Caches/Homebrew/graphicsmagick-1.3.21.tar.bz2
To retry an incomplete download, remove the file above.

**Comment by dunn** [comment]
This is due to SourceForge having major issues right now: #41778
