### ISSUE TITLE
Error: parent directory is world writable but not sticky

### ISSUE THREAD

**Issue by abarnish** [Homebrew/homebrew#41847]
ran this: 
brew postinstall gdal
returned:
Error: parent directory is world writable but not sticky
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/cmd/postinstall.rb:18:in `run_post_install'
/usr/local/Library/Homebrew/cmd/postinstall.rb:5:in `block in postinstall'
/usr/local/Library/Homebrew/cmd/postinstall.rb:5:in `each'
/usr/local/Library/Homebrew/cmd/postinstall.rb:5:in `postinstall'
/usr/local/Library/brew.rb:124:in `<main>'

Any Help?

**Comment by bfontaine** [comment]
See #39475.

**Comment by DomT4** [comment]
`brew doctor` will tell you to run `Repair Disk Permissions` in the Disk Utility app to repair the problem.
