### ISSUE TITLE
Discrepancies between `brew deps` and `brew deps --tree`

### ISSUE THREAD

**Issue by L2G** [Homebrew/homebrew#41841]
In at least some cases, `brew deps --tree` can list fewer dependencies than plain `brew deps`, as shown here:

```
$ brew deps graphicsmagick
autoconf
automake
fontconfig
freetype
gd
ghostscript
giflib
jasper
jbig2dec
jpeg
libpng
libtiff
libtool
libvpx
libwmf
little-cms
little-cms2
pkg-config
webp
xz
yasm

$ brew deps graphicsmagick --tree
graphicsmagick
├── pkg-config
├── libtool
|   └── xz
├── jpeg
├── libpng
|   └── xz
└── freetype
    └── libpng
        └── xz
```

**Comment by dunn** [comment]
[`--tree` only lists required dependencies](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/deps.rb#L74), while a plain `brew deps` [also lists the optional ones](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/deps.rb#L26-L36) unless `--skip-build` or `--skip-optional`.

Seems like `--tree` should be able to show optional deps, and should have the same default behavior as `brew deps`.

**Comment by dunn** [comment]
I think I know why `--tree` behaves the way it does:
![tree2](https://cloud.githubusercontent.com/assets/985416/8759118/b2f6604a-2ca2-11e5-9d81-96b588e246c3.gif)
(Fixing the multiple `xz` deps for git will only help a little bit.)

**Comment by dunn** [comment]
We shouldn't change the default behavior of plain `brew deps`since I bet there are scripts that depend on it, but that's probably not the case for `--tree` so we could add a quick note to the output:
```
🐙  brew deps --tree emacs
emacs (required dependencies)
├── xz
└── pkg-config
```

**Comment by mikemcquaid** [comment]
I'd be ok with `--tree` displaying all dependencies if we can do it in a sane manner.

**Comment by dunn** [comment]
Added the explanatory text to `--tree` in 9921089da7de983d7fe567f898097df49c4b096f, but if you think of a good way to display a tree with optional dependencies that'd be very welcome!
