### ISSUE TITLE
SHA256 mismatch for boost

### ISSUE THREAD

**Issue by kristjanjonsson** [Homebrew/homebrew#41844]
I'm trying to install boost and boost-python (dependancies for Caffe).
When I run `brew install --build-from-source --fresh -vd boost boost-python` I get

Verifying boost-1.58.0.tar.bz2 checksum
Error: SHA256 mismatch
Expected: fdfc204fc33ec79c99b9a74944c3e54bd78be4f7f15e260c0e2700a36dc7d3e5
Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821

**Comment by mistydemeo** [comment]
Sourceforge *just* came back after you posted this. Can you retry with: `brew fetch -fs boost`?

**Comment by kristjanjonsson** [comment]
It's working! Thanks.
