### ISSUE TITLE
failed to download sqlite

### ISSUE THREAD

**Issue by foxinmy** [Homebrew/homebrew#41854]
todeMacBook-Pro:Homebrew liujunhuan$ brew fetch -f sqlite
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.8.10.2.yosemite.bo
######################################################################## 100.0% 
Downloaded to: /Library/Caches/Homebrew/sqlite-3.8.10.2.yosemite.bottle.tar.gz
SHA1: dcdf26500b1164b86e75a72967f4d1d462dc3d45
SHA256: 6860786377f9a1431cf2471a143f565de4c0bbba7232510d1fd371280462a7d6

todeMacBook-Pro:~ liujunhuan$ brew install --universal --java subversion
==> Installing dependencies for subversion: sqlite, scons, makedepend, op
==> Installing subversion dependency: sqlite
==> Downloading https://sqlite.org/2015/sqlite-autoconf-3081002.tar.gz

curl: (7) Failed to connect to sqlite.org port 443: Connection refused
Error: Failed to download resource "sqlite"
Download failed: https://sqlite.org/2015/sqlite-autoconf-3081002.tar.gz
todeMacBook-Pro:~ liujunhuan$ 

thanks..

**Comment by ay65535** [comment]
```
$ brew fetch -fvd sqlite
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/sqlite.rb
==> Downloading https://sqlite.org/2015/sqlite-autoconf-3081002.tar.gz
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-645; OS X 10.11) https://sqlite.org/2015/sqlite-autoconf-3081002.tar.gz -C 0 -o /Library/Caches/Homebrew/sqlite-3.8.10.2.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to sqlite.org port 443: Connection refused
Error: Failed to download resource "sqlite"
Download failed: https://sqlite.org/2015/sqlite-autoconf-3081002.tar.gz
/usr/local/Library/Homebrew/download_strategy.rb:296:in `rescue in fetch'
/usr/local/Library/Homebrew/download_strategy.rb:285:in `fetch'
/usr/local/Library/Homebrew/resource.rb:109:in `fetch'
/usr/local/Library/Homebrew/formula.rb:789:in `fetch'
/usr/local/Library/Homebrew/cmd/fetch.rb:82:in `fetch_fetchable'
/usr/local/Library/Homebrew/cmd/fetch.rb:49:in `fetch_formula'
/usr/local/Library/Homebrew/cmd/fetch.rb:25:in `block in fetch'
/usr/local/Library/Homebrew/cmd/fetch.rb:19:in `each'
/usr/local/Library/Homebrew/cmd/fetch.rb:19:in `fetch'
/usr/local/Library/brew.rb:124:in `<main>'
$ 
```

**Comment by DomT4** [comment]
Looks like the upstream website has gone down.

**Comment by chouti** [comment]
$ brew fetch -fvd sqlite
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/sqlite.rb
==> Downloading https://sqlite.org/2015/sqlite-autoconf-3081002.tar.gz
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-645; OS X 10.11) https://sqlite.org/2015/sqlite-autoconf-3081002.tar.gz -C 0 -o /Library/Caches/Homebrew/sqlite-3.8.10.2.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0curl: (7) Failed to connect to sqlite.org port 443: Connection refused
Error: Failed to download resource "sqlite"
Download failed: https://sqlite.org/2015/sqlite-autoconf-3081002.tar.gz
/usr/local/Library/Homebrew/download_strategy.rb:296:in `rescue in fetch'
/usr/local/Library/Homebrew/download_strategy.rb:285:in `fetch'
/usr/local/Library/Homebrew/resource.rb:109:in `fetch'
/usr/local/Library/Homebrew/formula.rb:789:in `fetch'
/usr/local/Library/Homebrew/cmd/fetch.rb:82:in `fetch_fetchable'
/usr/local/Library/Homebrew/cmd/fetch.rb:49:in `fetch_formula'
/usr/local/Library/Homebrew/cmd/fetch.rb:25:in `block in fetch'
/usr/local/Library/Homebrew/cmd/fetch.rb:19:in `each'
/usr/local/Library/Homebrew/cmd/fetch.rb:19:in `fetch'
/usr/local/Library/brew.rb:124:in `<main>'

**Comment by chouti** [comment]
I've met the same issue here:
```
$ brew fetch -fvd sqlite
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/sqlite.rb
==> Downloading https://sqlite.org/2015/sqlite-autoconf-3081002.tar.gz
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-645; OS X 10.11) https://sqlite.org/2015/sqlite-autoconf-3081002.tar.gz -C 0 -o /Library/Caches/Homebrew/sqlite-3.8.10.2.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0curl: (7) Failed to connect to sqlite.org port 443: Connection refused
Error: Failed to download resource "sqlite"
Download failed: https://sqlite.org/2015/sqlite-autoconf-3081002.tar.gz
/usr/local/Library/Homebrew/download_strategy.rb:296:in `rescue in fetch'
/usr/local/Library/Homebrew/download_strategy.rb:285:in `fetch'
/usr/local/Library/Homebrew/resource.rb:109:in `fetch'
/usr/local/Library/Homebrew/formula.rb:789:in `fetch'
/usr/local/Library/Homebrew/cmd/fetch.rb:82:in `fetch_fetchable'
/usr/local/Library/Homebrew/cmd/fetch.rb:49:in `fetch_formula'
/usr/local/Library/Homebrew/cmd/fetch.rb:25:in `block in fetch'
/usr/local/Library/Homebrew/cmd/fetch.rb:19:in `each'
/usr/local/Library/Homebrew/cmd/fetch.rb:19:in `fetch'
/usr/local/Library/brew.rb:124:in `<main>'
```

**Comment by tdsmith** [comment]
Appears to be back up. Thanks for the report.
