### ISSUE TITLE
configure steps misdetect python

### ISSUE THREAD

**Issue by bric3** [Homebrew/homebrew#41860]
On El Capitan (10.11).

I have tried with yasm, but this fails on other formulas.

https://gist.github.com/anonymous/7c842b12ba1ff1f7bc49

Background

* OSX 10.10, installed brew
* Updated to 10.11 public beta
* Performed homebrew upgrade, and things got broken
* Applied tricks like 
  * `sudo chmod -R user:group /usr/local`
  * `sudo chflags norestricted /usr/local`
  * `brew reinstall python autoconf automake`

Yet configure step still sees python 2.4

The gist shows that the configure step does not use the correct PATH upon a `brew install yasm`: 

```
~ ○ ❯ echo $PATH
/Users/brice/.jenv/shims:/Users/brice/.cabal/bin:/usr/local/texlive/2012basic/bin/universal-darwin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/brice/.rvm/bin
```

Instead the ([reported](https://gist.github.com/anonymous/7c842b12ba1ff1f7bc49#file-01-configure-L129)) path is 

```
/usr/local/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin
```

Anyway on El Capitan Python is 2.7.6

```
bash-3.2$ /usr/bin/python --version
Python 2.7.6
```

I don't know if this is supposed to matter here, but I run my shell over a zsh that was installed via homebrew on 10.10.

**Comment by bric3** [comment]
OK, I tracked it down via those [lines](https://gist.github.com/anonymous/7c842b12ba1ff1f7bc49#file-config-log-L1072-L1079).

Why would it use `/usr/local/opt/python` as it is a directory. I have the answer : my `.rc` file declared a `PYTHON` environment variable, which was supposedly not a known or used variable ([ref](https://docs.python.org/2/using/cmdline.html#environment-variables)). These troubles may have not been seen on 10.10 as I may have installed python after those tools.

Anyway `brew doctor` should report this.

**Comment by tdsmith** [comment]
Thanks for the report. The PYTHON variable affects autotools, not Python, so it won't be reported in the Python manual.

We change PATH when building formulas to avoid picking up undeclared dependencies. 

I'll consider adding this to `doctor` if we see another report.

Please let us know if we can help with anything else!

**Comment by bric3** [comment]
OK, thanks for the explanation @tdsmith
