### ISSUE TITLE
osquery failed to build on 10.11

### ISSUE THREAD

**Issue by ghost** [Homebrew/homebrew#41862]
See also: https://gist.github.com/04d75a0f8392c8aac7d6

Note: Homebrew is installed inside my user directory, not /usr/local

Terminal output during error:

    ==> cmake . -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/Users/craig/Developer/homebrew/Cellar/osquery/1.4.7 -DCMAKE_BUILD_TYPE=Release -DCMA

    ==> make
    cd /tmp/osquery20150718-44048-zdv8wc/generated && THRIFT_COMPILER-NOTFOUND --gen cpp:dense --gen py:dense /tmp/osquery20150718-44048-zdv8wc/osquery.thrift
    /bin/sh: THRIFT_COMPILER-NOTFOUND: command not found
    make[2]: *** [generated/gen-cpp/Extension.cpp] Error 127
    make[1]: *** [osquery/extensions/CMakeFiles/osquery_extensions.dir/all] Error 2
    make: *** [all] Error 2

Homebrew says thrift is installed:

    $ brew info thrift
    thrift: stable 0.9.2, HEAD
    Framework for scalable cross-language services development
    https://thrift.apache.org/
    /Users/craig/Developer/homebrew/Cellar/thrift/0.9.2 (90 files, 5.2M) *
    Built from source
    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/thrift.rb

**Comment by apjanke** [comment]
`brew install osquery` is also failing for me on 10.11 Public Beta 2, but with a different error, apparently unrelated to thrift.

Install logs: https://gist.github.com/anonymous/162be18f9eb37b7d5f07

Error message:

```
[ 14%] Building CXX object osquery/tables/CMakeFiles/osquery_tables_darwin.dir/system/darwin/keychain_acl.cpp.o
cd /tmp/osquery20150724-76274-1ph5p5o/osquery/tables && /usr/local/Library/ENV/4.3/clang++   -DBOOST_NETWORK_ENABLE_HTTPS -DDARWIN -DDARWIN_10_11 -DNDEBUG -DOSQUERY_BUILD_DISTRO=10.11 -DOSQUERY_BUILD_PLATFORM=darwin -DOSQUERY_BUILD_SDK_VERSION=1.5.0 -DOSQUERY_THRIFT="" -DOSQUERY_THRIFT_LIB=thrift -DOSQUERY_THRIFT_POINTER=boost -DOSQUERY_THRIFT_SERVER_LIB=thrift/server -DSSL_TXT_TLSV1_2 -DSTRIP_FLAG_HELP=1 -I/tmp/osquery20150724-76274-1ph5p5o/third-party/cpp-netlib -I/tmp/osquery20150724-76274-1ph5p5o/third-party/gtest-1.7.0/include -I/tmp/osquery20150724-76274-1ph5p5o/third-party/sqlite3 -I/tmp/osquery20150724-76274-1ph5p5o/generated/gen-cpp -I/tmp/osquery20150724-76274-1ph5p5o/third-party/glog/include -I/tmp/osquery20150724-76274-1ph5p5o/include -I/tmp/osquery20150724-76274-1ph5p5o -I/usr/local/include     -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.10 -static -Wall -Wextra -Wstrict-aliasing -Wno-unused-parameter -Wno-unused-result -Wno-missing-field-initializers -Wno-sign-compare -Wnon-virtual-dtor -Wchar-subscripts -Wpointer-arith -Woverloaded-virtual -Wformat -Wformat-security -Werror=format-security -fstack-protector-all -fPIE -fpie -fPIC -fpic -pipe -Os -march=x86-64 -mtune=generic -o CMakeFiles/osquery_tables_darwin.dir/system/darwin/keychain_acl.cpp.o -c /tmp/osquery20150724-76274-1ph5p5o/osquery/tables/system/darwin/keychain_acl.cpp
/tmp/osquery20150724-76274-1ph5p5o/osquery/tables/system/darwin/keychain_acl.cpp:177:16: error: cannot initialize a variable of type 'SecItemClass' with an rvalue of type 'int'
  SecItemClass item_class = 0;
               ^            ~
/tmp/osquery20150724-76274-1ph5p5o/osquery/tables/system/darwin/keychain_acl.cpp:284:38: error: no matching function for call to 'SecKeychainSearchCreateFromAttributes'
  OSQUERY_USE_DEPRECATED(os_status = SecKeychainSearchCreateFromAttributes(
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/osquery20150724-76274-1ph5p5o/include/osquery/tables.h:31:9: note: expanded from macro 'OSQUERY_USE_DEPRECATED'
        expr;                                                             \
        ^
/System/Library/Frameworks/Security.framework/Headers/SecKeychainSearch.h:60:10: note: candidate function not viable: no known conversion from '(anonymous enum at /System/Library/Frameworks/Security.framework/Headers/cssmtype.h:1863:1)' to 'SecItemClass' for 2nd argument
OSStatus SecKeychainSearchCreateFromAttributes(CFTypeRef keychainOrArray, SecItemClass itemClass, const SecKeychainAttributeList * __nullable attrList, SecKeychainSearchRef * __nonnull CF_RETURNS_RETAINED searchRef)
         ^
2 errors generated.
make[2]: *** [osquery/tables/CMakeFiles/osquery_tables_darwin.dir/system/darwin/keychain_acl.cpp.o] Error 1
make[1]: *** [osquery/tables/CMakeFiles/osquery_tables_darwin.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by apjanke** [comment]
@cmaynard: It looks like having your Homebrew in a non-default location may be confusing the `osquery` build scripts' thrift detection logic. Its `CMake/FindThrift.cmake` script [looks in a few hardcoded locations, including `/usr/local`](https://github.com/facebook/osquery/blob/master/CMake/FindThrift.cmake#L30-L35), and if I understand the [CMake `find_program` behavior](http://www.cmake.org/cmake/help/v3.0/command/find_program.html), it doesn't search `$PATH`, because of that `NO_DEFAULT_PATH` argument. (And it seems like the `PATHS` keyword is missing, too.)

```cmake
find_program(THRIFT_COMPILER thrift
  $ENV{THRIFT_HOME}/bin
  /usr/local/bin
  /usr/bin
  NO_DEFAULT_PATH
)
```


As a workaround, it looks like you could define and export `$THRIFT_HOME` before doing the `brew install osquery`.

**Comment by dunn** [comment]
Should this be considered an upstream bug, or should we just set `THRIFT_HOME` during the install step?

**Comment by DomT4** [comment]
We can unset `THRIFT_HOME` during compile if necessary.

**Comment by DomT4** [comment]
@cmaynard If you edit the `osquery` formula to add something like:

```ruby
def install
ENV["THRIFT_HOME"] = Formula["thrift"].opt_prefix
```

Does compile succeed?

**Comment by cmaynard** [comment]
@apjanke @DomT4 I updated my copy of `osquery.rb` per your instructions. Now I get a different error when I run `brew install osquery`:

    ==> make
    /usr/bin/ar cq libosquery.a  CMakeFiles/libosquery.dir/main/lib.cpp.o ../third-party/sqlite3/CMakeFiles/osquery_sqlite.dir/sqlite3.c.o config/CMakeFiles/osquery_config.dir/config.cpp.o config/CMakeFiles/osquery_config_parsers.dir/parsers/query_packs.cpp.o core/CMakeFiles/osquery_core.dir/conversions.cpp.o core/CMakeFiles/osquery_core.dir/init.cpp.o core/CMakeFiles/osquery_core.dir/system.cpp.o core/CMakeFiles/osquery_core.dir/darwin/conversions.cpp.o core/CMakeFiles/osquery_core.dir/tables.cpp.o core/CMakeFiles/osquery_core.dir/text.cpp.o core/CMakeFiles/osquery_core.dir/flags.cpp.o core/CMakeFiles/osquery_core.dir/hash.cpp.o core/CMakeFiles/osquery_core.dir/watcher.cpp.o database/CMakeFiles/osquery_database.dir/database.cpp.o database/CMakeFiles/osquery_database_internal.dir/db_handle.cpp.o database/CMakeFiles/osquery_database_internal.dir/query.cpp.o dispatcher/CMakeFiles/osquery_dispatcher.dir/dispatcher.cpp.o dispatcher/CMakeFiles/osquery_dispatcher.dir/scheduler.cpp.o distributed/CMakeFiles/osquery_distributed.dir/distributed.cpp.o events/CMakeFiles/osquery_events.dir/events.cpp.o extensions/CMakeFiles/osquery_extensions.dir/__/__/generated/gen-cpp/Extension.cpp.o extensions/CMakeFiles/osquery_extensions.dir/__/__/generated/gen-cpp/ExtensionManager.cpp.o extensions/CMakeFiles/osquery_extensions.dir/__/__/generated/gen-cpp/osquery_types.cpp.o extensions/CMakeFiles/osquery_extensions.dir/extensions.cpp.o extensions/CMakeFiles/osquery_extensions.dir/interface.cpp.o filesystem/CMakeFiles/osquery_filesystem_objc.dir/darwin/plist.mm.o filesystem/CMakeFiles/osquery_filesystem.dir/filesystem.cpp.o filesystem/CMakeFiles/osquery_filesystem.dir/globbing.cpp.o logger/CMakeFiles/osquery_logger.dir/logger.cpp.o registry/CMakeFiles/osquery_registry.dir/registry.cpp.o sql/CMakeFiles/osquery_sql.dir/sql.cpp.o tables/CMakeFiles/osquery_tables_utility.dir/utility/file.cpp.o tables/CMakeFiles/osquery_tables_utility.dir/utility/hash.cpp.o tables/CMakeFiles/osquery_tables_utility.dir/utility/osquery.cpp.o tables/CMakeFiles/osquery_tables_utility.dir/utility/time.cpp.o CMakeFiles/osquery_amalgamation.dir/__/generated/utils_amalgamation.cpp.o
    /usr/bin/ranlib libosquery.a
    /Users/craig/Developer/homebrew/Cellar/cmake/3.2.3/bin/cmake -E cmake_progress_report /tmp/osquery20150803-9164-xbzhcw/CMakeFiles 
    [ 75%] Built target libosquery
    make: *** [all] Error 2

Is there a problem in cmake_progress_report?

**Comment by DomT4** [comment]
Can you produce a `brew gist-logs osquery` of that failure? Will contain fuller information, Thanks.

**Comment by cmaynard** [comment]
Here it is: https://gist.github.com/a8ac4ecb78a18ba3a60f

**Comment by cmaynard** [comment]
@DomT4 I ran `brew update` to get the latest changes and ran `brew install osquery` again. It failed again with a different error:

    ==> make
    /usr/bin/ar cq libosquery_testing.a  CMakeFiles/libosquery_testing.dir/core/test_util.cpp.o
    /usr/bin/ranlib libosquery_testing.a
    [ 76%] Built target libosquery_testing
    [ 76%] Built target example_extension
    make: *** [all] Error 2

See: https://gist.github.com/6ad384c9c53c27eaca92

**Comment by DomT4** [comment]
Ah, yeah, we're not going to be able to much about those errors on 10.11 before upstream do. Apple have made some fairly significant changes to the Keychain and Security Frameworks/mechanisms and `osquery` appears to be trying to pass variables that are no longer understood/respected in their current form.

**Comment by cmaynard** [comment]
Do we need to notify the `osquery.rb` maintainer?

**Comment by DomT4** [comment]
Yup.

**Comment by tdsmith** [comment]
Homebrew doesn't have package/formula maintainers. Someone (maybe you?) _should_ report this to the facebook/osquery repo, though! I don't see an open issue there. Please post a link here once you do.

**Comment by DomT4** [comment]
> (I think that's what Dom means.)

Yeah, Sorry. I edited my comment just now to clarify your comment is what I meant with "Yup".

**Comment by cmaynard** [comment]
@apjanke Looks like your issue is being addressed in https://github.com/facebook/osquery/issues/1329.

**Comment by chmaynard** [comment]
I originated this issue.

**Comment by chmaynard** [comment]
Successfully installed osquery on OS X 10.11 GM.
See: https://gist.github.com/chmaynard/7ff134a559a5ced0ab26

**Comment by DomT4** [comment]
Oh, aye. It was fixed in the https://github.com/facebook/osquery/releases/tag/1.5.2 release and fixed in Homebrew by https://github.com/Homebrew/homebrew/commit/21f97b3a7fb86b861f03b9a102ce97983b7df0ba. Should be all good now :+1:.
