### ISSUE TITLE
'coq' failed to build on 10.10.4

### ISSUE THREAD

**Issue by bdkent** [Homebrew/homebrew#41863]
I was unable to install the "coq" formula on a fully updated brew.

This is my console output:

```
$ brew install coq
==> Installing coq dependency: camlp5
==> Downloading http://pauillac.inria.fr/~ddr/camlp5/distrib/src/camlp5-6.12.tgz
Already downloaded: /Library/Caches/Homebrew/camlp5-6.12.tgz
==> ./configure -prefix /Users/dev/.homebrew/Cellar/camlp5/6.12_2 -mandir /Users/dev/.homebrew/Cellar/camlp5/6.12_2/share/man -transitional
is not yet implemented. Please report.

Information: directory ocaml_stuff/4.02.2 is missing.

Configuration failed.

READ THIS: https://git.io/brew-troubleshooting
```

Thoughts?

**Comment by dunn** [comment]
Can you post `brew gist-logs camlp5` for us, please?

**Comment by bfontaine** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please read this when posting an issue. :wink:

**Comment by bdkent** [comment]
Sorry about the bad form when posting, @bfontaine!  I correct the title.

@dunn: https://gist.github.com/bdkent/a6b83ed0c9036b1d5e95

**Comment by mistydemeo** [comment]
There's a new camlp5 that adds ocaml 4.02.2; will submit a PR.

**Comment by mistydemeo** [comment]
Fixed - if you `brew update` and retry it should work now.
