### ISSUE TITLE
irssi functions incorrectly on 10.11 with dante installed

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew#41873]
[See this](https://github.com/irssi/irssi/issues/266)

Basically, irssi is always installed `--with-socks`, even when --with-dante isn't specified, leading to potentially broken installs and/or odd behavior. Removing dante or removing --with-socks in the formula caused the problem to stop occurring.

I want to say that this also occurs in 10.10, since I remember this kind of issue occurring before, but I cannot confirm it at this time.

**Comment by DomT4** [comment]
Will check this out ASAP, Thanks.

**Comment by tdsmith** [comment]
What's the relationship between irssi, SOCKS, and dante?

**Comment by tdsmith** [comment]
We've been passing `with-socks` since d562cf02c7b98a.

**Comment by DomT4** [comment]
Dante provides a `SOCKS` library. Tor recommended it for a fair while as a way to use IRC with Irssi over Tor, and the documentation still lists it as a useful optional tool. I presume `torsocks` is preferred these days.

**Comment by aw1621107** [comment]
I know this has been going on for a while, but I've never been able to pin it down. On phone atm, so not sure when that commit was, but I'm fairly sure this also happened on 10.10; not sure if the cause is exactly the same though

**Comment by tdsmith** [comment]
2011. :) Should be fixed in 07ee457; thanks for reporting!
