### ISSUE TITLE
Error: undefined method `desc' for Formulary::Formulae::Llvm36:Class

### ISSUE THREAD

**Issue by micfan** [Homebrew/homebrew#41882]
``` bash
mic@mbp: ~/vm/build$ brew tap homebrew/versions
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-versions'...
remote: Counting objects: 4459, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 4459 (delta 11), reused 0 (delta 0), pack-reused 4434
Receiving objects: 100% (4459/4459), 1.43 MiB | 4.00 KiB/s, done.
Resolving deltas: 100% (2608/2608), done.
Checking connectivity... done.
Tapped 233 formulae

mic@mbp: ~/vm/build$ brew install llvm36
Error: undefined method `desc' for Formulary::Formulae::Llvm36:Class
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-versions/llvm36.rb:2:in `<class:Llvm36>'
/usr/local/Library/Taps/homebrew/homebrew-versions/llvm36.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:42:in `install'
/usr/local/Library/brew.rb:135:in `<main>'

mic@mbp: ~/vm/build$ brew --version
0.9.5

```

**Comment by DomT4** [comment]
`brew --version` isn't a super-relevant measure of how up-to-date Homebrew is.

Please `brew update` and see if the error persists, Thanks!

**Comment by micfan** [comment]
`brew doctor` gives many error like:
``` bash
Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
    echo export PATH='/usr/local/sbin:$PATH' >> ~/.bash_profile
Error: Failed to import: ansible18
undefined method `desc' for Formulary::Formulae::Ansible18:Class
Error: Failed to import: astyle204
undefined method `desc' for Formulary::Formulae::Astyle204:Class
Error: Failed to import: base_kde_formula
formulae require at least a URL
Error: Failed to import: boot2docker162
undefined method `desc' for Formulary::Formulae::Boot2docker162:Class
Error: Failed to import: cassandra-0.6
undefined method `desc' for Formulary::Formulae::Cassandra06:Class
Error: Failed to import: cassandra10
undefined method `desc' for Formulary::Formulae::Cassandra10:Class
Error: Failed to import: cassandra12
undefined method `desc' for Formulary::Formulae::Cassandra12:Class
Error: Failed to import: cassandra20
undefined method `desc' for Formulary::Formulae::Cassandra20:Class
Error: Failed to import: docker162
undefined method `desc' for Formulary::Formulae::Docker162:Class
Error: Failed to import: gcc5
undefined method `desc' for Formulary::Formulae::Gcc5:Class
Error: Failed to import: gegl02
undefined method `desc' for Formulary::Formulae::Gegl02:Class
Error: Failed to import: gnupg21
undefined method `desc' for Formulary::Formulae::Gnupg21:Class
Error: Failed to import: hadoop0202
undefined method `desc' for Formulary::Formulae::Hadoop0202:Class
Error: Failed to import: hadoop121
undefined method `desc' for Formulary::Formulae::Hadoop121:Class
Error: Failed to import: hadoop25
undefined method `desc' for Formulary::Formulae::Hadoop25:Class
Error: Failed to import: influxdb08
undefined method `desc' for Formulary::Formulae::Influxdb08:Class
Error: Failed to import: jetty76
undefined method `desc' for Formulary::F
```

**Comment by tdsmith** [comment]
Have you had a chance to try running `brew update`? Did that help?

**Comment by DomT4** [comment]
Ping?

**Comment by micfan** [comment]
`brew update` is really effect, it use git to pull origin HEAD of remote formulary, this has taken a long time.

Now it seems that everything is ok:
``` bash
mic@mbp: ~/vm$ brew install llvm36
==> Installing llvm36 from homebrew/homebrew-versions
==> Downloading https://homebrew.bintray.com/bottles-versions/llvm36-3.6.1.yosemite.bottle.tar.gz
#######                                                                   10.8%
```
:+1:

**Comment by hlecuyer** [comment]
brew update didn't help or my part. 
It's not for the same package but it seams like I can't install anything now. Exemple => 

e2r4p11% brew install homebrew/php/php56
==> Installing php56 from homebrew/homebrew-php
Error: undefined method `desc' for Formulary::Formulae::Freetype:Class
Please report this bug:
    http://git.io/brew-troubleshooting
/nfs/zfs-student-3/users/2013/hlecuyer/.brew/Library/Formula/freetype.rb:2:in `<class:Freetype>'
/nfs/zfs-student-3/users/2013/hlecuyer/.brew/Library/Formula/freetype.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/dependency.rb:32:in `to_formula'
/usr/local/Library/Homebrew/dependency.rb:88:in `block in expand'
/usr/local/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Library/Homebrew/dependency.rb:76:in `expand'
/usr/local/Library/Homebrew/formula.rb:574:in `recursive_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:96:in `verify_deps_exist'
/usr/local/Library/Homebrew/formula_installer.rb:89:in `prelude'
/usr/local/Library/Homebrew/cmd/install.rb:163:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:84:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:84:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:84:in `install'
/usr/local/Library/brew.rb:135:in `<main>'

**Comment by micfan** [comment]
@hlecuyer
Did you try `brew update -v` which will show the update progress in terminal?

**Comment by hlecuyer** [comment]
It works now. It's probaly a problem with environment my school provide.
I rebooted everything.
I solved it with a Hack a friend of mine gave me. 
With our school installation, i needed to comment the line 130,131 from ~/.brew/Library/Formula/git.rb and reinstall git with brew.  I don't know if you're solution would have work better. Sorry for the trouble.

**Comment by yuansanwan** [comment]
brew update     is   the right answer.

**Comment by student-t** [comment]
Agreed. brew updated fixed it.

**Comment by MeghaNadkarni0512** [comment]
When I try to install cassandra12 on my mac using:

brew install cassandra12

It fails with: Error: No available formula with the name "homebrew/versions/cassandra12" ==> Searching for similarly named formulae... Error: No similarly named formulae found. ==> Searching taps... Error: No formulae found in taps.

Updating, uninstalling and re-installing brew didn't help either. Can somebody help me with how to fix this issue?

Note: 'brew search cassandra' shows cassandra21 and cassandra22. I need cassandra12 specifically.

**Comment by DomT4** [comment]
@MeghaNadkarni0512 It was removed. See discussion in https://github.com/Homebrew/homebrew-versions/pull/1274.
