### ISSUE TITLE
undefined method 'user' for TapFormulaUnavailableError

### ISSUE THREAD

**Issue by peterjeliot** [Homebrew/homebrew#41888]
NOTE: While writing this I noticed the first line of the output. Whoops. Still seems like using a sometimes-missing 'user' method is a bug, and could have a better error message? Should I report this error at the homebrew-science repo?

When trying to install opencv, I got this error:

```
Please tap it and then try again: brew tap homebrew/python>
Error: undefined method `user' for #<TapFormulaUnavailableError:0x007fe09d1c3498>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula_installer.rb:101:in `rescue in verify_deps_exist'
/usr/local/Library/Homebrew/formula_installer.rb:97:in `verify_deps_exist'
/usr/local/Library/Homebrew/formula_installer.rb:91:in `prelude'
/usr/local/Library/Homebrew/cmd/install.rb:176:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `install'
/usr/local/Library/brew.rb:124:in `<main>'
```

After adding a print statement for the error in the install script, I see this:
```
#<TapFormulaUnavailableError: No available formula for homebrew/python/numpy
```
Apparently this error type has no method 'user'.

Upon googling, this solution fixes it: https://github.com/Homebrew/homebrew/issues/36556

`brew tap homebrew/python` then `brew install numpy`

I had previously been using other taps for `homebrew-science` (note that I don't know the nitty gritty details of how taps work).

**Comment by tdsmith** [comment]
This should be resolved after you run `brew update`; thanks for the report!
