### ISSUE TITLE
node failed to build on 10.11

### ISSUE THREAD

**Issue by blacRose** [Homebrew/homebrew#41881]
# Error
    brew upgrade -v node|pbcopy
    Warning: You are using OS X 10.11.
    We do not provide support for this pre-release version.
    You may encounter build failures or other breakage.
    Error: node 0.12.7 did not build
    Warning: You are using OS X 10.11.
    We do not provide support for this pre-release version.
    You may encounter build failures or other breakage.
Pasteboard:
----
made gist… [here it is](https://gist.github.com/blacRose/c42fc3fce855ac75aa88)

**Comment by DomT4** [comment]
This might be a CLT issue. At least, I *hope* it's a CLT issue. Give me a bit and I'll kick into my VM and check it out.

**Comment by DomT4** [comment]
I can't reproduce this on 10.11, either against system Python or Homebrew's Python. Depending on your preferred first choice here, please either:

* `brew unlink Python` and then try to install Node again.
* `xcode-select --install` to install the CLT package, and then try to install Node again.

**Comment by blacRose** [comment]
Done both. Still fails.

**Comment by DomT4** [comment]
Blurgh. Any ideas @tdsmith? The error is being thrown from Python. @dunn said he's seen similar problems with Homebrew's Python in Linuxbrew as well on this error, but I'm not sure why it would impact the system Python as well.

I can't reproduce it, which makes it tricky to get into - I can `python -c "import bz2"` on 10.11 successfully with both Homebrewed and System Python as well.

**Comment by tdsmith** [comment]
Wagering the SDK wasn't available when Python was built and it failed to compile the extension modules that depend on the SDK.

Can you try `brew reinstall python` and `brew gist-logs python` if that doesn't fix it?

**Comment by tdsmith** [comment]
Say, why does node depend_on :python, anyway?

**Comment by mistydemeo** [comment]
The buildsystem is written in Python, though maybe it would work with the system Python.

**Comment by blacRose** [comment]
Fixed. Oops. Thanks! Four ! in front of the commands.
    !!!! 21:24:17 user@Daedalus ~ brew reinstall python
    ==> Reinstalling python
    ==> Downloading https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
    Already downloaded: /Library/Caches/Homebrew/python-2.7.10.tgz
    ==> Downloading https://bugs.python.org/file30805/issue10910-workaround.txt
    Already downloaded: /Library/Caches/Homebrew/python--patch-c075353337f9ff3ccf8091693d278782fcdff62c113245d8de43c5c7acc57daf.txt
    ==> Patching
    patching file Include/pyport.h
    Hunk #1 succeeded at 713 (offset 14 lines).
    Hunk #2 succeeded at 736 (offset 14 lines).
    ==> ./configure --prefix=/usr/local/Cellar/python/2.7.10_2 --enable-ipv6 --datar
    brew upgrade node
    ==> make
    ==> make install PYTHONAPPSDIR=/usr/local/Cellar/python/2.7.10_2
    ==> make frameworkinstallextras PYTHONAPPSDIR=/usr/local/Cellar/python/2.7.10_2/
    ==> Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-
    Already downloaded: /Library/Caches/Homebrew/python--setuptools-18.0.1.tar.gz
    ==> Downloading https://pypi.python.org/packages/source/p/pip/pip-7.1.0.tar.gz
    Already downloaded: /Library/Caches/Homebrew/python--pip-7.1.0.tar.gz
    ==> Downloading https://pypi.python.org/packages/source/w/wheel/wheel-0.24.0.tar
    Already downloaded: /Library/Caches/Homebrew/python--wheel-0.24.0.tar.gz
    ==> Caveats
    Pip and setuptools have been installed. To update them
      pip install --upgrade pip setuptools

    You can install Python packages with
      pip install <package>

    They will install into the site-package directory
      /usr/local/lib/python2.7/site-packages

    See: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-and-Python.md


    .app bundles were installed.
    Run `brew linkapps python` to symlink these to /Applications.
    ==> /usr/local/Cellar/python/2.7.10_2/bin/python -s setup.py --no-user-cfg insta
    ==> /usr/local/Cellar/python/2.7.10_2/bin/python -s setup.py --no-user-cfg insta
    ==> /usr/local/Cellar/python/2.7.10_2/bin/python -s setup.py --no-user-cfg insta
    ==> Summary
    🍺  /usr/local/Cellar/python/2.7.10_2: 6194 files, 97M, built in 2.9 minutes
    !!!! 21:27:17 user@Daedalus ~ brew upgrade node
    Warning: You are using OS X 10.11.
    We do not provide support for this pre-release version.
    You may encounter build failures or other breakage.
    ==> Upgrading 1 outdated package, with result:
    node 0.12.7
    ==> Upgrading node
    ==> Downloading https://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz
    Already downloaded: /Library/Caches/Homebrew/node-0.12.7.tar.gz
    ==> ./configure --prefix=/usr/local/Cellar/node/0.12.7 --without-npm --without-s
    ==> make install
    ==> Downloading https://registry.npmjs.org/npm/-/npm-2.12.1.tgz
    ######################################################################## 100.0%
    ==> ./configure --prefix=/usr/local/Cellar/node/0.12.7/libexec/npm
    ==> make install
    ==> Caveats

    Bash completion has been installed to:
      /usr/local/etc/bash_completion.d
    ==> Summary
    🍺  /usr/local/Cellar/node/0.12.7: 2726 files, 31M, built in 6.2 minutes
    21:33:32 user@Daedalus ~

**Comment by DomT4** [comment]
The Python dependency has been there in one form or another for years. It was a requirement for a while, then it needed Python 2.6 as a minimum, then it was just `depends_on :python` and eventually `depends_on :python => :build`.

It needs 2.7 these days, but we have a dependency method that handles that use case.
