### ISSUE TITLE
zookeeper start failed because of wrong CLASSPATH setting

### ISSUE THREAD

**Issue by huangyg11** [Homebrew/homebrew#41907]
I install zookeeper with command with 

    > brew install zookeeper

Then I run command 

    > zkServer status

    zkServer start
    JMX enabled by default
    Using config: /usr/local/etc/zookeeper/zoo.cfg
    Starting zookeeper ... STARTED

Everything seems OK.

But when I run 

    > zkServer status

    JMX enabled by default 
    Using config: /usr/local/etc/zookeeper/zoo.cfg
    Error contacting service. It is probably not running.

And `ps` shows zookeeper is not running at all. After hours of exploring, I find it is caused by the wrong  `CLASSPATH` setting. 

The variable is set in the file `libexec/bin/zkEnv.sh`. It contains dir `src` and `build` which is not present for the default installation. 

    > java -Dzookeeper.log.dir=. -Dzookeeper.root.logger=INFO,CONSOLE -cp /usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../build/classes:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../build/lib/*.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/slf4j-log4j12-1.6.1.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/slf4j-api-1.6.1.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/netty-3.7.0.Final.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/log4j-1.2.16.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/jline-0.9.94.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../zookeeper-3.4.6.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../src/java/lib/*.jar:/usr/local/etc/zookeeper: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false org.apache.zookeeper.server.quorum.QuorumPeerMain /usr/local/etc/zookeeper/zoo.cfg

    zsh: no matches found: /usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../build/classes:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../build/lib/*.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/slf4j-log4j12-1.6.1.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/slf4j-api-1.6.1.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/netty-3.7.0.Final.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/log4j-1.2.16.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/jline-0.9.94.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../zookeeper-3.4.6.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../src/java/lib/*.jar:/usr/local/etc/zookeeper:

And the check in zkSever.sh not work and thought zk is started :

    nohup "$JAVA" "-Dzookeeper.log.dir=${ZOO_LOG_DIR}" "-Dzookeeper.root.logger=${ZOO_LOG4J_PROP}" \
        -cp "$CLASSPATH" $JVMFLAGS $ZOOMAIN "$ZOOCFG" > "$_ZOO_DAEMON_OUT" 2>&1 < /dev/null &                                                                                                                                                                                               
    if [ $? -eq 0 ]
    then
    if /bin/echo -n $! > "$ZOOPIDFILE"
    then
         sleep 1
         echo STARTED
    ...  

remove all `src` and `build` in the `CLASSPATH` solves the problem. 

    > java -Dzookeeper.log.dir=. -Dzookeeper.root.logger=INFO,CONSOLE -cp /usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/slf4j-log4j12-1.6.1.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/slf4j-api-1.6.1.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/netty-3.7.0.Final.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/log4j-1.2.16.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/jline-0.9.94.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../zookeeper-3.4.6.jar:/usr/local/etc/zookeeper: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false org.apache.zookeeper.server.quorum.QuorumPeerMain /usr/local/etc/zookeeper/zoo.cfg

**Comment by huangyg11** [comment]
System info

    ProductName:	Mac OS X
    ProductVersion:	10.10.3
    BuildVersion:	14D136

And 

    > brew gist-logs zookeeper                                                                                                                                                                                                                                    

    Error: No logs.

**Comment by dunn** [comment]
Yeah, looks like we're only installing those directories when building HEAD:
```ruby
    if build.head?
      system "ant"
      libexec.install Dir["bin", "src/contrib", "src/java/lib", "build/*.jar"]
    else
      libexec.install Dir["bin", "contrib", "lib", "*.jar"]
    end
```
Are they not provided with the stable distribution, or can we install them?

**Comment by tdsmith** [comment]
`libexec.install Dir["foo/bar"]` should create a directory libexec/bar.

**Comment by tdrisdelle** [comment]
This works just fine on HEAD, but not on 3.4.6

**Comment by dunn** [comment]
Looking into this more closely, I can't replicate it.  As @tdsmith predicted, the directory structure in `libexec` is the same for the stable and HEAD builds.  Can you try reinstalling zookeeper and seeing if this persists?

**Comment by huangyg11** [comment]
I reinstall zookeeper through brew, and the problem was gone. I check the classpath, the new generated classpath are : 

    /usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../build/classes
    /usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../build/lib/*.jar
    /usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/slf4j-log4j12-1.6.1.jar
    /usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/slf4j-api-1.6.1.jar
    /usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/netty-3.7.0.Final.jar
    /usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/log4j-1.2.16.jar
    /usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/jline-0.9.94.jar
    /usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../zookeeper-3.4.6.jar
    /usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../src/java/lib/*.jar
    /usr/local/etc/zookeeper

Not `src` and `build` any more.

**Comment by dunn** [comment]
That's great to hear! Let us know if you have other questions we can help with.
