### ISSUE TITLE
Use kegs when building cmake, maybe

### ISSUE THREAD

**Issue by rgov** [Homebrew/homebrew#41917]
The cmake formula uses the system curl, zlib, etc. These could be overridden to use kegs:

```
diff --git a/Library/Formula/cmake.rb b/Library/Formula/cmake.rb
index 0b15134..f552521 100644
--- a/Library/Formula/cmake.rb
+++ b/Library/Formula/cmake.rb
@@ -91,6 +91,21 @@ class Cmake < Formula
       args << "--sphinx-man" << "--sphinx-build=#{buildpath}/sphinx/bin/sphinx-build"
     end
 
+    # Use kegs for curl and zlib if they're available
+    init = []
+    if Formula["zlib"].installed?
+      init << "set(ZLIB_INCLUDE_DIR #{Formula["zlib"].opt_include} CACHE INTERNAL \"\" FORCE)"
+      init << "set(ZLIB_LIBRARY #{Formula["zlib"].opt_lib}/libz.dylib CACHE INTERNAL \"\" FORCE)"
+    end
+    if Formula["curl"].installed?
+      init << "set(CURL_INCLUDE_DIR #{Formula["curl"].opt_include} CACHE INTERNAL \"\" FORCE)"
+    end
+
+    if not init.empty?
+      (buildpath/"bootstrap-init.cmake").atomic_write init.join("\n")
+      args << "--init=#{buildpath}/bootstrap-init.cmake"
+    end
+
     system "./bootstrap", *args
     system "make"
     system "make", "install"
```

There are several dependencies that could be overridden this way (zlib, curl, gzip, ncurses, probably others).

**Comment by DomT4** [comment]
I don't want to go down this path, to be honest. `zlib` doesn't live in the main repo, and even semi-recent OS X versions have up-to-date `zlib` versions, I'm not sure on the benefit of offering that.

Likewise for `curl`, we get a certain stability in using the system version here which Apple does keep supported. Not super sure what that would gain us. I'm not high on adding a lot of `homebrew/dupes/xyz` optional dependencies unless it brings something necessary to the table, and I'm not sure it would here.

**Comment by tdsmith** [comment]
Thanks for the PR! Homebrew prefers system dependencies; it's one of our design principles. Is there a reason you need a newer version of one of these in cmake?

**Comment by rgov** [comment]
At the moment, no. I was trying to diagnose a (seemingly unrelated) problem and was troubleshooting by using newer libraries. I agree it's not compelling.

**Comment by tdsmith** [comment]
Okay, thanks! Let us know if there's anything we can help with.

**Comment by mikemcquaid** [comment]
> Thanks for the PR! Homebrew prefers system dependencies; it's one of our design principles. Is there a reason you need a newer version of one of these in cmake?

@tdsmith Just to be clear(er) here I'd say we prefer upstream vendored dependencies (like in CMake currently) and then system dependencies :wink:

**Comment by tdsmith** [comment]
Oh! Hadn't looked; thanks.
