### ISSUE TITLE
ocaml @@HOMEBREW_PREFIX@@/bin/ocamlrun: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by andyli** [Homebrew/homebrew#41926]
Since very recently, `brew install ocaml`, then `ocaml -version ` results in:
```
-bash: /usr/local/bin/ocaml: @@HOMEBREW_PREFIX@@/bin/ocamlrun: bad interpreter: No such file or directory
```

Looks like it is not a problem of the formula, since if I checkout 3db2f08e9c981bb47fb76539649306ca91e2b268 of homebrew, then `brew reinstall ocaml`, `ocaml -version` will successfully print:
```
The OCaml toplevel, version 4.02.2
```

**Comment by andyli** [comment]
`git bisect` shows that 03aff321590b2b052579798914b884365836395f is the breaking commit.

**Comment by bfontaine** [comment]
cc @mikemcquaid
