### ISSUE TITLE
Python import bsddb result in error (Python 2.7.10)

### ISSUE THREAD

**Issue by LukeJang** [Homebrew/homebrew#41948]
As title. I installed Python using brew
```
$ python 
Python 2.7.10 (default, Jul  9 2015, 13:34:07) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bsddb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bsddb/__init__.py", line 67, in <module>
    import _bsddb
ImportError: No module named _bsddb
>>>
```

**Comment by mistydemeo** [comment]
You need to install Python `--with-berkeley-db4` to enable bsddb support. It's not enabled by default.

**Comment by LukeJang** [comment]
Is there any document that I can find such information?

**Comment by mistydemeo** [comment]
You can see the available build options using `brew options python` or `brew info python`.

**Comment by LukeJang** [comment]
It really helps. Thank you very much!

**Comment by aetherwu** [comment]
@mistydemeo Would you mind tell me how exactly ' install Python --with-berkeley-db4'  please?
Below are some cmd I use for making:

cd Python-2.7.10
./configure --prefix=/usr/local
make && make altinstall
export PATH="/usr/local/bin:$PATH"

**Comment by LukeJang** [comment]
It is simple. Just execute `brew install python --with-berkeley-db4`.
