### ISSUE TITLE
Restrictive homebrew installation as admin user, read/execute privileges for standard users

### ISSUE THREAD

**Issue by frace** [Homebrew/homebrew#41942]
Hello all,

on OS X 10.10 Yosemite the default umask is `077` (`700` octal notation). Apple's guide [«Setting a custom umask in OS X»](https://support.apple.com/en-us/HT201684) describes how to alter the default umask on a global user basis but it does not seem to be possible to alter the umask on a per user basis or on a per directory basis. The point is that I'm pretty fine with the default umask in general, but there is a pitfall in situations where people use some kind of restrictive multiuser setup. For details please see below:

I do use an admin account for administrative tasks and a standard account for my daily work. As a result I `su - administrator` in order to install and to use the homebrew package manager. Standard users should have the privileges to execute binaries managed by homebrew.

How I installed homebrew and how I use it right now:
```
# Prerequisites
Add admin user for Homebrew management and a standard user for daily work.

# Installation
As admin user:
  0. `umask 002`
  1. `sudo mkdir /usr/local`
  2. `sudo chown root:admin /usr/local`
  3. Install Homebrew in `/usr/local`
```
That ensures that the group `admin` gains write access but everyone else is restricted to read and execute privileges - which is fine and desired of course! The disadvantage is that I have to set the umask manually every time I'm having a **homebrew session**. If I wouldn't do that new/updated packages would not be executable for standard users since the default umask - remember `077`- results in `700` privileges.

As a consequence my homebrew sessions start as shown below:
```
umask 002 ; brew update && brew upgrade
# Finish homebrew jobs and reset umask to its default value to do another job:
umask 077
```

This is not nice. :)

Exists a solution to that problem currently? At least I could not find anything which would let me avoid to use `umask` as the very first command on a new **homebrew session**.

I could imagine and would like to propose the introduction of a new environment variable named `HOMEBREW_UMASK` as a solution to that problem.

Each and everytime when `brew` gets executed the following would happen:
```
0. `HOMEBREW_UMASK_TEMP=`umask``
1. `umask $HOMEBREW_UMASK`
2. Finish package installation
3. `umask $HOMEBREW_UMASK_TEMP`
```

Cheers

**Comment by DomT4** [comment]
We're not going to introduce a `UMASK` environmental variable in Homebrew. It would not be a minor undertaking, and fiddling with user's `umask` even with their consent is a risky game to play and something we'd prefer not to get into.

I'm not quite sure why you're running `sudo chown root:admin` here? Even on an admin account it should be `sudo chown adminuser:admin`.

**Comment by apjanke** [comment]
The default umask in 10.10 Yosemite is still `022`. And [the article you linked to](https://support.apple.com/en-us/HT201684) does describe how to set the umask on a per user basis. Maybe you changed your default umask at some point?

Anyway. To make your `umask` setting convenient, you could just define a shell function that runs `brew` in a subshell, with your umask set how you want it. Stick this in your admin user's `.bashrc` or `.zshrc`. And you can change the function name to `brew` if you want it to always run this way.

```
function brewadmin () {
	(umask 002; brew "$@")
}
```

Using a subshell means the `umask` always is back to its original value once the command finishes, even if it was interrupted by Ctrl-C or an error.

**Comment by frace** [comment]
@DomT4
> We're not going to introduce a UMASK environmental variable in Homebrew.

What if it'd be e.g. `HOMEBREW_OCTAL_BITS="775"` instead? Then noone would alter the umask but `brew` could apply these privileges to updated or newly installed applications/libraries/etc.?

> I'm not quite sure why you're running sudo chown root:admin here? Even on an admin account it should be sudo chown adminuser:admin?

All your base in `/usr` are belong to root - which doesn't hurt at all since its bits are set to `775`: `root` and `admin` accounts are allowed to do whatever they want and everyone else is allowed to read and execute contents of `/usr/local`.

@apjanke
> The default umask in 10.10 Yosemite is still 022. ...
> ... Maybe you changed your default umask at some point?

Are you sure about that? As a test I created a new user, but even then umask still returned `0077`.
It's very unlikely that I changed the `umask` since I do use a fresh system installation.
Since the directory `/private/var/db/com.apple.xpc.launchd/config` is empty I can not explain where I could have changed the default `umask` by accident.

> And the article you linked to does describe how to set the umask on a per user basis.

But doesn't it describe how to change the umask for **all** users instead of a per user basis?
You can get the results from
```
sudo cat /private/var/db/com.apple.xpc.launchd/config/user.plist
```
which confirms my assumption that it will apply to all users.

Your subshell proposal is something I already had in mind, but I wanted to go that route as a last resort only. Thanks anyway for your snippet. :)

**Comment by mikemcquaid** [comment]
> What if it'd be e.g. HOMEBREW_OCTAL_BITS="775" instead? Then noone would alter the umask but brew could apply these privileges to updated or newly installed applications/libraries/etc.?

We're not going to do that either, sorry.

> Are you sure about that? As a test I created a new user, but even then umask still returned 0077.

It's 022 for me too.

**Comment by frace** [comment]
@mikemcquaid 
> It's 022 for me too.

That's strange. Do you have any ideas why it's `077` for me?

**Comment by mikemcquaid** [comment]
@frace I'd guess you've got it configured somewhere, dunno where, sorry.

**Comment by frace** [comment]
@mikemcquaid 
Would you mind to compare your privileges with mine?
```
drwx------  2 username  staff    68 22 Jul 13:37  folder_created_in_bash
drwxr-xr-x 2 username  staff    68 22 Jul 13:36  folder_created_in_finder
-rw-------    1 username  staff    00 22 Jul 13:36  file_created_in_bash
-rw-r--r--    1 username  staff  178 22 Jul 13:38  file_created_with_textedit
```

**Comment by mikemcquaid** [comment]
```
-rw-r--r--    1 username  staff     0B 22 Jul 12:55 file_created_in_bash
-rw-r--r--@   1 username  staff   178B 22 Jul 12:56 file_created_with_textedit.rtf
drwxr-xr-x    2 username  staff    68B 22 Jul 12:55 folder_created_in_bash/
drwxr-xr-x    2 username  staff    68B 22 Jul 12:55 folder_created_in_finder/
```

So the issue is in a e.g. `.bashrc` or similar.

**Comment by frace** [comment]
Thanks a lot, I'll report back as soon as I found the bugger.
