### ISSUE TITLE
It is impossible to install msmtp with ntlm support

### ISSUE THREAD

**Issue by cweagans** [Homebrew/homebrew#41955]
I have installed the `gsasl` package and edited the msmtp formula to include the `--with-libgsasl` argument on the configure command. When the configure command was run as part of `brew install msmtp --build-from-source`, this was part of the output:

```
Install prefix ......... : /usr/local/Cellar/msmtp/1.6.2
TLS/SSL support ........ : yes (Library: OpenSSL)
GNU SASL support ....... : no
IDN support ............ : no
NLS support ............ : no
Libsecret support (GNOME): no
MacOS X Keychain support : yes
```

SASL support, in this case, should be "yes".

Normally, I wouldn't have opened a homebrew bug about this, but when I manually download the msmtp source from sourceforge and run `./configure --with-libgsasl` (Again with the homebrew package `gsasl` already installed), I get this:

```
Install prefix ......... : /usr/local
TLS/SSL support ........ : yes (Library: GnuTLS)
GNU SASL support ....... : yes
IDN support ............ : no
NLS support ............ : no
Libsecret support (GNOME): no
MacOS X Keychain support : yes
```

I'm guessing this has something to do with what directories homebrew tells `./configure` to search for libraries (especially since the Homebrew version uses openssl and the manual version uses GnuTLS).

Is there any way around this issue? I'm not overly familiar with how make figures out library locations...

**Comment by cweagans** [comment]
(Oh, btw - it's probably a good idea to make msmtp depend on gsasl and have the `--with-libgsasl` flag always turned on if we can get this figured out. gsasl is a pretty solid library and there's no harm in not using it, and having it available makes msmtp more useful out of the box for many people, namely those who are stuck with an Exchange server that only accepts NTLM auth)

**Comment by bfontaine** [comment]
Please post your edited formula so we can see what’s missing.

**Comment by tzudot** [comment]
@cweagans make these changes, as an additional option to support `gsasl` while Homebrew compiles `msmtp`.
 
```diff
diff --git a/Library/Formula/msmtp.rb b/Library/Formula/msmtp.rb
index d8984c5..8616086 100644
--- a/Library/Formula/msmtp.rb
+++ b/Library/Formula/msmtp.rb
@@ -12,6 +12,9 @@ class Msmtp < Formula

   depends_on "pkg-config" => :build
   depends_on "openssl"
+  depends_on "gsasl" => :optional
+
+  option "with-gsasl"

   def install
     args = %W[
@@ -21,6 +24,8 @@ class Msmtp < Formula
       --with-tls=openssl
     ]

+    args << "--with-libgsasl" if build.with? "gsasl"
+
     system "./configure", *args
     system "make", "install"
     (share/"msmtp/scripts").install "scripts/msmtpq"
```
or

for making `gsasl` as the default option during compile time,

```diff
diff --git a/Library/Formula/msmtp.rb b/Library/Formula/msmtp.rb
index d8984c5..8e2b0ca 100644
--- a/Library/Formula/msmtp.rb
+++ b/Library/Formula/msmtp.rb
@@ -12,6 +12,7 @@ class Msmtp < Formula

   depends_on "pkg-config" => :build
   depends_on "openssl"
+  depends_on "gsasl"

   def install
     args = %W[
@@ -19,6 +20,7 @@ class Msmtp < Formula
       --with-macosx-keyring
       --prefix=#{prefix}
       --with-tls=openssl
+      --with-libgsasl
     ]

     system "./configure", *args
```

@bfontaine what is the preferred option here?

**Comment by DomT4** [comment]
Closing in favour of #41969.
