### ISSUE TITLE
moreutils download link 404s

### ISSUE THREAD

**Issue by xiongchiamiov** [Homebrew/homebrew#41991]
==> Upgrading 1 outdated package, with result:
    moreutils 0.57
    ==> Upgrading moreutils
    ==> Downloading http://mentors.debian.net/debian/pool/main/m/moreutils/moreutils_0.57.orig.tar.gz
    
    curl: (22) The requested URL returned error: 404 Not Found
    Error: Failed to download resource "moreutils"
    Download failed: http://mentors.debian.net/debian/pool/main/m/moreutils/moreutils_0.57.orig.tar.gz

This changed in 7652c93.  I'm not sure if that file used to exist there or not, but currently there's only 0.55.

It appears to exist in [the kernel.org mirror](https://mirrors.kernel.org/debian/pool/main/m/moreutils/), which was removed in 9b5ded (because another version wasn't currently there?).  Are the mirrors for `moreutils` just super laggy?

**Comment by dunn** [comment]
Thanks for catching that!  Ought to have used `https` URLs in the first place anyway.  Fix in #41992
