### ISSUE TITLE
Install via tap doesn't respect HOMEBREW_BOTTLE_DOMAIN

### ISSUE THREAD

**Issue by chriskolenko** [Homebrew/homebrew#42008]
I'm trying to get a mirror working for bottles. I've got it successfully working with Homebrew Formulas. However, Taps don't respect the HOMEBREW_BOTTLE_DOMAIN.

**Comment by xu-cheng** [comment]
If there is a `root_url` in the bottle block, `HOMEBREW_BOTTLE_DOMAIN` won't be used. This is happening for formulae with old bottles. As formulae get updated and new bottle is generated, `root_url` will be gone.

**Comment by mikemcquaid** [comment]
You could also submit a pull-request to the various taps to remove the `root_url`. Make sure you ping @Homebrew/owners when you do that so we can stop the (long) build.

**Comment by chris-kolenko** [comment]
Ah ha. That's awesome. I'll find some root_urls in the homebrew-versions tap. 
Thanks

**Comment by DomT4** [comment]
Dealt with X11 in https://github.com/Homebrew/homebrew-x11/commit/c3c636cd1550c0b7c9c0cd8fbf6c6025051e7e82.

**Comment by DomT4** [comment]
And Dupes in https://github.com/Homebrew/homebrew-dupes/commit/5eeeab1284f9f088063f2792b67b467efabce6d6.
