### ISSUE TITLE
llvm --with-clang takes a lot of time

### ISSUE THREAD

**Issue by AbdealiJK** [Homebrew/homebrew#42001]
When I run `brew install llvm --with-clang` it takes more than an hour to install.

I'm trying to install clang in a CI worker, and it times out after 50 mins.
Is there any way for me to install clang quickly ? I need to reinstall it on the CI worker every time I push to my repository

Some flag to install binaries maybe ?

**Comment by DomT4** [comment]
Heh, the `--with-clang` can *easily* make the compile time upwards of 90 minutes. *Easily*.

The `homebrew/versions` LLVM formulae are built with Clang by default, so yes. `brew install homebrew/versions/llvm36` or similar.

Note the installed binaries are versioned to avoid clashing with the system, but `brew info llvm36` provides some information in the caveats how to link and if you want the unversioned binaries they exist in `HOMEBREW_PREFIX/opt/llvm36/lib/llvm-3.6/bin`.

**Comment by AbdealiJK** [comment]
Thanks ! this is muuuch faster :)
