### ISSUE TITLE
antiword looks for /usr/share/antiword instead of /usr/share/local/antiword

### ISSUE THREAD

**Issue by ambs** [Homebrew/homebrew#42018]
After installing antiword, there is a link from `/usr/share/Cellar/antiword/.../share/antiword` to `/usr/share/local/antiword`, but when running antiword it complains with:

`````
I can't open your mapping file (UTF-8.txt)
It is not in '/Users/ambs/.antiword' nor in '/usr/share/antiword'.
`````

So, either look up if there is a way to configure it, or make the link under /usr/share (although not that clean).

**Comment by mistydemeo** [comment]
The string in my Homebrew-installed copy of antiword says this:

```c
"It is not in '%s/.antiword' nor in '/usr/local/Cellar/antiword/0.37/share/antiword'."
```

Just to double-check, you're sure your antiword was installed by Homebrew? Can you try reinstalling?

**Comment by ambs** [comment]
GAH! Yeah, it was intalled by homebrew, but had another one in my home bin folder. I use it so often *not* that I didn't remember it might be there. Thanks and sorry for the false bug report.

:+1:
