### ISSUE TITLE
httpry depends on bsdmake, why?

### ISSUE THREAD

**Issue by vmsp** [Homebrew/homebrew#42025]
I just tried compiling httpry with GNU make (xcode) and it worked fine.
Am I missing something?

Thank you.

**Comment by mistydemeo** [comment]
It looks like bsdmake has been used since the first version in e7dd57f846852592be7fbd50449797e22c788ff0, but the reason for using bsdmake isn't documented there or in #6038. It may no longer be necessary.

**Comment by DomT4** [comment]
Because the dependency was added and probably last checked ~3 years ago :wink:. Feel free to submit a PR to remove the dependency. If it builds, we'd merge it.

**Comment by DomT4** [comment]
Oops, Apologies for the double maintainer post.

**Comment by mistydemeo** [comment]
Fixed, thanks!
