### ISSUE TITLE
Feature: prevent a formula’s previous version from being removed by `brew cleanup`

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew#42039]
This is inspired from [this question on StackOverflow](http://apple.stackexchange.com/q/190684/25981). OP wants to keep gcc 4.9 *and* 5.2, but running `brew cleanup` would remove the former.

I don’t know if this is something that would be used, or another niche feature that only a few people would use. It shouldn’t be hard to add something in a formula’s prefix to mark it as non-cleanable.

**Comment by tdsmith** [comment]
The versions formula seems like a better solution.

**Comment by DomT4** [comment]
My answer in #42036 applies here a lot as well.

**Comment by tdsmith** [comment]
I think my biggest concern with this is that it's hard to restore this state where both versions are installed and `switch` can be used to switch between them. I think `switch` is a good backstop to have in case a new release breaks something but I don't think we should be encouraging people to make it part of their workflows.

**Comment by mikemcquaid** [comment]
Agreed with @tdsmith here. It'd be good to know how/if we can improve the versions tap to make these workflows better.

**Comment by bfontaine** [comment]
Thank you all for your feedback, I’m closing this.
