### ISSUE TITLE
ctl: bottles need to be rebuilt

### ISSUE THREAD

**Issue by cbenhagen** [Homebrew/homebrew#42033]
current bottles are linked against an old version of libImath

```
dyld: Library not loaded: /usr/local/lib/libImath-2_1.11.dylib
  Referenced from: /usr/local/bin/ctlrender
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by DomT4** [comment]
Will be fixed by #42037. This has been broken for at least a couple of months by the look of the commit history - Was updated early May in https://github.com/Homebrew/homebrew/commit/89eab757168931168fb184b79dba549a4f89a75c.
