### ISSUE TITLE
pandoc 1.15.0.6 fails to build on El Capitan PB2

### ISSUE THREAD

**Issue by zmwangx** [Homebrew/homebrew#42044]
I was able to successfully compile `pandoc 1.15.0.4` on PB1. However, after upgrading to PB2, building `pandoc 1.15.0.6` always fails in the dependency installation stage, i.e.,

```
> cabal install --jobs=2 --only-dependencies
```

And I always (in my three tries) get errors like

```
Failed to install regex-base-0.93.2
Build log ( /private/tmp/pandoc20150722-91363-jatdbk/pandoc-1.15.0.6/.cabal-sandbox/logs/regex-base-0.93.2.log ):
cabal:
/private/tmp/pandoc20150722-91363-jatdbk/pandoc-1.15.0.6/.cabal-sandbox/logs/regex-base-0.93.2.log:
does not exist
```

The build fails at a different dependency each time I run it. Here's the `gist-logs` for the last failure: https://gist.github.com/anonymous/5e9b49d4daa03a77b358. Looks like there's some problem with the cabal sandbox. I haven't looked at the logs in detail; nor have I investigated if this problem is brew-specific. Anyway, I know little about Haskell, so we probably need someone more knowledgeable at the subject.

Note that I haven't recompiled `cabal-install 1.22.2.0` and `ghc 7.10.1` on PB2 — they were persisted through the upgrade from PB1.

**Comment by zmwangx** [comment]
Curiously, I was able to successfully build `pandoc` after deparallelizing the build environment:

```diff
modified   Library/Formula/pandoc.rb
@@ -24,6 +24,7 @@ class Pandoc < Formula
 
   def install
     cabal_sandbox do
+      ENV.deparallelize
       cabal_install "--only-dependencies"
       cabal_install "--prefix=#{prefix}"
     end

```

Here are the logs from the succeeded build: https://gist.github.com/anonymous/5304b33ec466da66ba0a.

**Comment by dunn** [comment]
Sounds like an upstream issue. It would be very cool if you could file a bug with the pandoc developers, then submit a pull request with something like this:
```diff
diff --git a/Library/Formula/pandoc.rb b/Library/Formula/pandoc.rb
index ee90681..b5dafa5 100644
--- a/Library/Formula/pandoc.rb
+++ b/Library/Formula/pandoc.rb
@@ -24,6 +24,8 @@ class Pandoc < Formula
 
   def install
     cabal_sandbox do
+      # https://github.com/link/to/upstream/issue
+      ENV.deparallelize if MacOS.version >= :el_capitan
       cabal_install "--only-dependencies"
       cabal_install "--prefix=#{prefix}"
     end
```

**Comment by zmwangx** [comment]
> It would be very cool if you could file a bug with the pandoc developers

Well, since the failure occurs in the dependency installation stage with standard `cabal-install --only-dependencies`, I think pandoc developers probably aren't the right ones to complain about this issue.

I wonder if there's a Homebrew maintainer/collaborator who's familiar with Haskell? He/she can probably offer some advice, and in case we need to report to upstream, he/she could probably generate a more insightful report than I could.

Meanwhile, I'll try to reinstall a fresh copy of `cabal-install`, and also try to build pandoc outside Homebrew's environment.

**Comment by zmwangx** [comment]
In fact, after rebuilding `cabal-install` from scratch, the unpatched `pandoc.rb` went just fine. Latest log: https://gist.github.com/db94d9e26968e9d0beba.

Closing for now, assuming the latest success was not a coincidence.

**Comment by dunn** [comment]
Glad to hear you got things working!
