### ISSUE TITLE
Getting dependencies graph

### ISSUE THREAD

**Issue by anvaka** [Homebrew/homebrew#42046]
Hello friends,

I'd like to visualize homebrew packages. I did visualizations of bower, npm, composer, and ruby gems: http://anvaka.github.io/pm/#/ - would love to add homebrew to the family.

Can somebody help me crawl the graph of each homebrew package?

Do I just need to parse all formulas and find strings like `depends_on xxx`? Or brews's dependencies could be expressed in more ways?

**Comment by DomT4** [comment]
`brew deps xyz --tree` will give you a list of the entire dependency tree for mandatory dependencies, It won't list optional or recommended dependencies.

`brew deps --skip-optional xyz` will list only the mandatory dependencies for the formula in a list format.

`brew deps --skip-build xyz` will list all the possible dependencies except those explicitly required for building the formula from source, such as `cmake` or `autogen`.

`brew deps xyz` will give you a full list of dependencies in a list format, without highlighting which are required/recommended/optional.

`brew deps --all` will list every Homebrew formula and every dependency for those formulae, without highlighting which are required/recommended/optional.

Various flags can be combined.

**Comment by anvaka** [comment]
Wow, thank you Dominyk. `brew deps --all` is exactly what I needed!

**Comment by anvaka** [comment]
Here is the [visualization of the Homebrew](http://anvaka.github.io/pm/#/galaxy/brew?cx=-803&cy=-3622&cz=-1640&lx=0.3774&ly=-0.7360&lz=0.4338&lw=0.3573&ml=200&s=2.75&l=1)

I hope you enjoy it :)

**Comment by DomT4** [comment]
Nice, Thanks! Cool to see how interconnected so many things are.
