### ISSUE TITLE
Homebrew git script fails to load correct interpreter

### ISSUE THREAD

**Issue by rddesmond** [Homebrew/homebrew#42060]
When attempting to brew install --HEAD, the git wrapper script included with homebrew doesn't appear to run against the ruby interpreter.

```
➜  ~  brew install unoconv --HEAD
==> Cloning https://github.com/dagwieers/unoconv.git
Removing invalid repository from cache
/usr/local/Library/ENV/4.3/git: line 6: syntax error near unexpected token `('
/usr/local/Library/ENV/4.3/git: line 6: `F = File.basename(__FILE__).freeze'
Error: Failed to download resource "unoconv"
Failure while executing: git clone --depth 1 --branch master https://github.com/dagwieers/unoconv.git /Library/Caches/Homebrew/unoconv--git
```

This is running on Mac OS 10.10.4 with:
```
➜  ~  brew --version
0.9.5
➜  ~  /usr/bin/ruby --version
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin14.1.0]
```

I found that I could change the shebang line in `/usr/local/Library/ENV/4.3/git` from `#!/usr/bin/ruby -W0` to `#!/usr/bin/env ruby -W0`, and have it work correctly.  This isn't a portable solution though (since linux's implementation of env doesn't allow multiple options).

I also found that:
 - `/usr/local/Library/ENV/4.3/git --help` works correctly from the zsh shell
 - `/usr/bin/ruby /usr/local/Library/ENV/4.3/git  --help` works correctly from the zsh shell

**Comment by DomT4** [comment]
Not a problem here. Can you try `brew update && brew rm -r /Library/Caches/Homebrew/unoconv--git && brew install unoconv --HEAD`?

**Comment by DomT4** [comment]
How is your Ruby outdated?

```
~> /usr/bin/ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```
Did you modify/replace it or anything?

**Comment by rddesmond** [comment]
I cleared out the git directory and did an update.  No luck.  It's failng on `download_strategy.rb:642`.

The ruby version is for one of my other projects.  I updated to 2.2.2 (using `rbenv install 2.2.2 && rbenv global 2.2.2`).  Same problem.

**Comment by DomT4** [comment]
Are you using Homebrew's git or the system default git?

> The ruby version is for one of my other projects.

We'll always use the one in `/usr/bin/ruby`, which should be the system original. Is that not the case for you?

**Comment by rddesmond** [comment]
Git is apple version (though the brew version is installed on my machine).  Though largely, I'm not actually getting far enough down the path to actually use it.:
```
➜  ~  git --version
git version 2.3.2 (Apple Git-55)
➜  ~  /usr/local/Library/ENV/4.3/git --version
git version 2.3.2 (Apple Git-55)
```

I'm not particularly well versed in ruby.  I am using rbenv to set the version on the fly:
```
➜  ~  ls -l /usr/bin/ruby
lrwxr-xr-x  1 root  wheel  34 Feb 13 16:56 /usr/bin/ruby -> /Users/rddesmond/.rbenv/shims/ruby
```

**Comment by rddesmond** [comment]
(That shim is placed by homebrew:

```
1 #!/usr/bin/env bash
  2 set -e
  3 [ -n "$RBENV_DEBUG" ] && set -x
  4
  5 program="${0##*/}"
  6 if [ "$program" = "ruby" ]; then
  7   for arg; do
  8     case "$arg" in
  9     -e* | -- ) break ;;
 10     */* )
 11       if [ -f "$arg" ]; then
 12         export RBENV_DIR="${arg%/*}"
 13         break
 14       fi
 15       ;;
 16     esac
 17   done
 18 fi
 19
 20 export RBENV_ROOT="/Users/rddesmond/.rbenv"
 21 exec "/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv" exec "$program" "$@"
```
)

**Comment by mistydemeo** [comment]
I'm sorry, but we don't support a configuration where `/usr/bin/ruby` is something other than the Ruby shipped by Apple. We use that Ruby specifically for compatibility reasons.

I recommend setting your PATH so that the rbenv shim comes before `/usr/bin/ruby` in your PATH; that way you shouldn't need to change `/usr/bin/ruby`.

**Comment by DomT4** [comment]
You may need to reinstall OS X here. Replacing binaries in `/usr/bin` can cause unforeseen consequences, including this particular issue, sadly, and it's difficult to get them back to default without doing a reinstall.

**Comment by mistydemeo** [comment]
The `/usr/bin/ruby` binary can probably also be extracted from the OS package, or obtained from another user with the same OS version as you, if you don't wish to reinstall OS X.

**Comment by rddesmond** [comment]
Thank you, thank you.  Y'all are awesome.  Sorry that I took some of your time for a misconfiguration that I caused somewhere down the road.

I was able to restore `/usr/bin/ruby` to the system default and it worked once again.

**Comment by mistydemeo** [comment]
Great! Glad to hear it's working now.
