### ISSUE TITLE
libpng fails to install: 

### ISSUE THREAD

**Issue by vlovich** [Homebrew/homebrew#42106]
brew install wine fails with:

==> Installing wine dependency: libpng
==> Downloading https://downloads.sourceforge.net/project/libpng/libpng16/1.6.17/libpng-1.6.17.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng16/libpng-1.6.17.tar.xz

curl: (78) RETR response: 550
Error: Failed to download resource "libpng"
Download failed: ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng16/libpng-1.6.17.tar.xz

**Comment by dunn** [comment]
The copy at `ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng16/libpng-1.6.17.tar.xz` has been deleted; only 1.6.18 is there now.  I'm getting a 404 from the SourceForge version as well. I wonder if they're having another "hiccup."

**Comment by mistydemeo** [comment]
According to their [mailing list](http://sourceforge.net/p/png-mng/mailman/message/34309667/), they've uploaded 1.6.18 as of yesterday; they're still unable to upload new releases to Sourceforge.

**Comment by dunn** [comment]
Did they delete 1.6.17 before uploading the new version, then?

**Comment by mistydemeo** [comment]
Looks like it, yes.

**Comment by glennrp** [comment]
No I did not delete libpng-1.6.17.  It's just a part of the massive SourceForge outage.  Fortunately for all of this, SourceForge's site status report tells us, "Knowledge capture has been continuous throughout this outage and will drive continuous improvement."

**Comment by stevetauber** [comment]
If you still receive this error, an update to brew will fix it.

``` brew update```

**Comment by dhildebrandt** [comment]
Thanks @stevetauber your comment saved me!
