### ISSUE TITLE
[gnu-tar] patch error during install

### ISSUE THREAD

**Issue by ryenus** [Homebrew/homebrew#42104]
Not sure if there's a real problem, when I tried to install `gnu-tar`, 
I saw the error message which says:

> **patch unexpectedly ends in middle of line** 

Even though the install process finished with code `0`.

Currently gnu-tar is version `1.28` plus the patch [here](https://gist.githubusercontent.com/mistydemeo/10fbae8b8441359ba86d/raw/e5c183b72036821856f9e82b46fba6185e10e8b9/gnutar-configure-xattrs.patch).

**Comment by ryenus** [comment]
Below is the full output:

> $ brew reinstall gnu-tar --with-default-names
==> Reinstalling gnu-tar with --with-default-names
==> Downloading http://ftpmirror.gnu.org/tar/tar-1.28.tar.gz
Already downloaded: /Library/Caches/Homebrew/gnu-tar-1.28.tar.gz
==> Downloading https://gist.githubusercontent.com/mistydemeo/10fbae8b8441359ba86d/raw/e5c183b72036821856f9e82b46fba6185e10e8b9/gnutar-configure-xattrs.patch
Already downloaded: /Library/Caches/Homebrew/gnu-tar--patch-f2e56bb8afd1c641a7e5b81e35fdbf36b6fb66434b1e35caa8b55196b30c3ad9.patch
==> Patching
patching file Makefile.in
patching file aclocal.m4
patching file config.h.in
patching file configure
patching file doc/Makefile.in
patching file gnu/Makefile.in
patching file lib/Makefile.in
patching file rmt/Makefile.in
patching file scripts/Makefile.in
patching file src/Makefile.in
patching file tests/Makefile.in
patching file lib/xattr-at.c
patching file src/Makefile.am
**patch unexpectedly ends in middle of line**
==> ./configure --prefix=/usr/local/Cellar/gnu-tar/1.28 --mandir=/usr/local/Cellar/gnu-tar/1.28/share/man
==> make install
🍺  /usr/local/Cellar/gnu-tar/1.28: 13 files, 1.6M, built in 95 seconds

**Comment by DomT4** [comment]
Same thing here: `patch unexpectedly ends in middle of line`. It's not a problem if compile is still successful. @mistydemeo may choose to tweak the patch a bit to get rid of the warning, but it's not anything to be concerned about :).
