### ISSUE TITLE
libgcrypt fail to build

### ISSUE THREAD

**Issue by guoxiao** [Homebrew/homebrew#42112]
https://gist.github.com/anonymous/a0c5f7ddb482fb7c84fd

It seems that the `libgcrypt.20.dylib` has not been installed yet when running `make check`. 
```
dyld: Library not loaded: /usr/local/Cellar/libgcrypt/1.6.3_1/lib/libgcrypt.20.dylib
  Referenced from: /private/tmp/libgcrypt20150725-52099-abv666/libgcrypt-1.6.3/tests/.libs/random
  Reason: image not found
random: running '/private/tmp/libgcrypt20150725-52099-abv666/libgcrypt-1.6.3/tests/.libs/random --in-recursion --early-rng-check' failed
FAIL: random
```

**Comment by DomT4** [comment]
This is a known issue on 10.11, See #41599. Will scrub the `make check` on El Capitan for now, one sec.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew/commit/29aa8ae5269d32f89e4607a5e184d4a75b019161
