### ISSUE TITLE
OSX 10.11 bash: tmuxinator: command not found

### ISSUE THREAD

**Issue by ixodie** [Homebrew/homebrew#42139]
Any ideas what might be causing this?  I already did brew upgrade.

**Comment by mistydemeo** [comment]
Looks like [this gem](https://github.com/tmuxinator/tmuxinator). Check your dotfiles - do those use tmuxinator and you haven't installed it on your 10.11 machine yet?

**Comment by ixodie** [comment]
Sorry, it seems to have been broken/uninstalled since 10.11 was installed.
