### ISSUE TITLE
brew reinstall doesn't keep HEAD flag?

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew#42147]
It seems that `brew reinstall` keeps all flags used except for `--HEAD`. For example, if I had an `emacs --with-x11 --HEAD` install, and ran `brew reinstall emacs`, I'd end up with a plain `emacs --with-x11` install.

**Comment by bfontaine** [comment]
Right, I was able to reproduce this issue with both a bottled (`git-cal`) and a non-bottled (`ack`) formulae.

**Comment by xu-cheng** [comment]
This is because `--HEAD` and `--devel` are never stored as options in the tab file.
