### ISSUE TITLE
brew audit --strict inconsistent rules on devel/stable/head placing

### ISSUE THREAD

**Issue by John-Colvin** [Homebrew/homebrew#42163]
the audit will complain if you have stable or head after the bottle block, but insists that the devel block is placed after, not before.

Why?

**Comment by John-Colvin** [comment]
Also, it insists on devel being before head, which means you can't win either way.

**Comment by xu-cheng** [comment]
What formula is questioning here? [This](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/audit.rb#L162-L179) is the order which `brew audit --strict` enforces.

**Comment by John-Colvin** [comment]
OK I must have just got confused about there being 2 different positions for head depending if it's a full block or not.
