### ISSUE TITLE
brew install srtp does not create the /usr/local/lib/pkgconfig/libsrtp.pc file

### ISSUE THREAD

**Issue by ibc** [Homebrew/homebrew#42173]
By running `brew install srtp` the corresponding pkgconfig file is not created.

Within the libsrtp sources, running  `./configure` does create `libsrtp.pc` from the existing `libsrtp.pc.in`, and running `make install` copies it to `/usr/local/lib/pkgconfig/`. And it seems that `brew install srtp` calls both but the pkgconfig file is not created/copied.

https://github.com/Homebrew/homebrew/blob/master/Library/Formula/srtp.rb

In the other side, `brew install libuv` does copy the pkgconfig file (note that it is done during the `autoconf` stuff):

https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libuv.rb

**Comment by tdsmith** [comment]
srtp only installs the .pc file if pkg-config is present at build time and the formula did not declare a dependency on pkg-config. Fixed by feec2ce. Thanks for reporting!

**Comment by ibc** [comment]
:cake:

**Comment by ibc** [comment]
Sorry... `brew update && brew install srtp` does not yet install libsrtp with the commit above, is that normal?

**Comment by tdsmith** [comment]
I realized after you posted your cake that I forgot to update the bottle; that was done in 80a76f6, so it should work if you give it another spin.

**Comment by ibc** [comment]
It works. Thanks!
