### ISSUE TITLE
can't download icu4c

### ISSUE THREAD

**Issue by yekz** [Homebrew/homebrew#42188]
this may not a homebrew issue, http://site.icu-project.org/ can't open 

------------------------
brew install php55-memcached php55-gearman
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Installing php55-memcached from homebrew/homebrew-php
==> Installing dependencies for homebrew/php/php55-memcached: icu4c, php55, igbinary, php55-igbinary, libmemc
==> Installing homebrew/php/php55-memcached dependency: icu4c
==> Downloading https://ssl.icu-project.org/files/icu4c/55.1/icu4c-55_1-src.tgz

curl: (6) Could not resolve host: ssl.icu-project.org
Error: Failed to download resource "icu4c"
Download failed: https://ssl.icu-project.org/files/icu4c/55.1/icu4c-55_1-src.tgz

**Comment by mistydemeo** [comment]
I'm able to resolve the icu4c server, but I added a mirror for the source tarball; can you let me know if that works for you?

**Comment by yekz** [comment]
thanks! mirror works
