### ISSUE TITLE
Wine fails to install on OS X 10.11.

### ISSUE THREAD

**Issue by Cu3PO42** [Homebrew/homebrew#42207]
On OS X 10.11 Wine fails to install with the following error message:

    Warning: You are using OS X 10.11.
    We do not provide support for this pre-release version.
    You may encounter build failures or other breakage.
    ==> Downloading https://downloads.sourceforge.net/project/wine/Source/wine-1.6.2
    Already downloaded: /Library/Caches/Homebrew/wine-1.6.2.tar.bz2
    ==> ./configure --prefix=/usr/local/Cellar/wine/1.6.2 --without-mpg123
    ==> make install
    ../../tools/wrc/wrc --nostdinc  -m32 -I. -I. -I../../include -I../../include  -D__WINESRC__   -o version.res version.rc
    ../../tools/winegcc/winegcc -m32 -B../../tools/winebuild --sysroot=../.. -fasynchronous-unwind-tables -shared ./wined3d.spec arb_program_shader.o ati_fragment_shader.o buffer.o context.o device.o directx.o drawprim.o gl_compat.o glsl_shader.o nvidia_texture_shader.o palette.o query.o resource.o sampler.o shader.o shader_sm1.o shader_sm4.o state.o stateblock.o surface.o swapchain.o texture.o utils.o vertexdeclaration.o view.o volume.o wined3d_main.o       version.res    -o wined3d.dll.so  -luuid -lopengl32 -luser32 -lgdi32 -ladvapi32  ../../libs/port/libwine_port.a
    ../../tools/winegcc/winegcc -m32 -B../../tools/winebuild --sysroot=../.. -fasynchronous-unwind-tables -shared ./wined3d.spec arb_program_shader.o ati_fragment_shader.o buffer.o context.o device.o directx.o drawprim.o gl_compat.o glsl_shader.o nvidia_texture_shader.o palette.o query.o resource.o sampler.o shader.o shader_sm1.o shader_sm4.o state.o stateblock.o surface.o swapchain.o texture.o utils.o vertexdeclaration.o view.o volume.o wined3d_main.o       version.res    -o wined3d.dll.fake  -luuid -lopengl32 -luser32 -lgdi32 -ladvapi32  ../../libs/port/libwine_port.a
    ../../tools/winegcc/winegcc -m32 -B../../tools/winebuild --sysroot=../.. -fasynchronous-unwind-tables -shared ./windowscodecs.spec bitmap.o bmpdecode.o bmpencode.o clsfactory.o colorcontext.o colortransform.o converter.o fliprotate.o gifformat.o icnsformat.o icoformat.o imgfactory.o info.o jpegformat.o main.o metadatahandler.o palette.o pngformat.o propertybag.o proxy.o regsvr.o scaler.o stream.o tgaformat.o tiffformat.o ungif.o   windowscodecs_wincodec_p.o  windowscodecs_wincodec_r.res  version.res  dlldata.o  -o windowscodecs.dll.so  -luuid -lole32 -loleaut32 -lrpcrt4 -lshlwapi -luser32 -lgdi32 -ladvapi32  ../../libs/port/libwine_port.a -framework ApplicationServices
    ../../tools/winegcc/winegcc -m32 -B../../tools/winebuild --sysroot=../.. -fasynchronous-unwind-tables -shared ./windowscodecs.spec bitmap.o bmpdecode.o bmpencode.o clsfactory.o colorcontext.o colortransform.o converter.o fliprotate.o gifformat.o icnsformat.o icoformat.o imgfactory.o info.o jpegformat.o main.o metadatahandler.o palette.o pngformat.o propertybag.o proxy.o regsvr.o scaler.o stream.o tgaformat.o tiffformat.o ungif.o   windowscodecs_wincodec_p.o  windowscodecs_wincodec_r.res  version.res  dlldata.o  -o windowscodecs.dll.fake  -luuid -lole32 -loleaut32 -lrpcrt4 -lshlwapi -luser32 -lgdi32 -ladvapi32  ../../libs/port/libwine_port.a -framework ApplicationServices

    READ THIS: https://git.io/brew-troubleshooting

    These open issues may also help:
    failed to install wine when configuring gd https://github.com/Homebrew/homebrew/issues/35831
    Warning: You are using OS X 10.11.
    We do not provide support for this pre-release version.
    You may encounter build failures or other breakage.

I did install the new Xcode CLT and I deinstalled `apple-gcc42`. Other applications build and install just fine. I also confirmed I own `/usr/local`. `brew doctor` does not not complain about anything else other than a slightly outdated XQuartz.

**Comment by bfontaine** [comment]
Please post the output of `brew gist-logs wine`.

**Comment by Cu3PO42** [comment]
After running for about 30 minutes here it is, finally:
https://gist.githubusercontent.com/anonymous/ead701cba31154ed08bb/raw/798c43a2a45bcaf8b75edbfa8b536f410e723eb0/doctor.out

**Comment by mistydemeo** [comment]
```



Warning: Your Xcode (6.4) is outdated
Please update to Xcode 7.0.
Xcode can be updated from
  https://developer.apple.com/xcode/downloads/
```

You must install the Xcode 7.0 beta on 10.11; otherwise a lot of software will fail to build.

**Comment by Cu3PO42** [comment]
I understood installing the new CLT by running `xcode-select --install` was sufficient sine it should include the new compilers.

**Comment by mistydemeo** [comment]
No, having both a current CLT and an older Xcode can lead to issues since you'll have two conflicting sets of headers and tools installed. If you don't plan to upgrade to Xcode 7 you'll need to uninstall Xcode.

**Comment by Cu3PO42** [comment]
My bad then. I will start the Xcode download and report back in a couple of days. (Yes, unfortunately my internet is that slow.)

**Comment by Cu3PO42** [comment]
Alright, the XCode download is finally done. Installing it has fixed the problem. I apologize for having thought having the CLT was enough.
