### ISSUE TITLE
make install from tap process more self-documenting

### ISSUE THREAD

**Issue by anentropic** [Homebrew/homebrew#42222]
I love homebrew and it's my first stop for installing commandline stuff on Mac

I just tried to do this:

```
brew install xld
Error: No available formula for xld
==> Searching formulae...
==> Searching taps...
Caskroom/cask/xld
```

ok great, `brew install` went ahead and looked in the taps for me... and it seems to have found a match

however at this stage I have no idea what to do to proceed - not great

I kind of think maybe brew should have just gone ahead and installed it from the tap it found.  But I can see it hasn't done that.

(TLDR: I think at this point brew should definitely at least tell me how to install this formula from the tap)

So, I vaguely remember the taps are like some extra repos of formulae. I think I 'tapped' one in the past, maybe that's what I have to do here:

```
$ brew tap Caskroom/cask/xld
Error: Invalid tap name
$ brew tap caskroom/cask
Warning: Already tapped!
```

hmm ok

```
brew install xld
Error: No available formula for xld
==> Searching formulae...
==> Searching taps...
Caskroom/cask/xld
```

oh yeah, I already tried that. er, was it `brew install --tap something` ...? I can't remember

at this point I resort to the google and, though I get satisfaction shortly after, I feel sad in the meantime

**Comment by dunn** [comment]
This is a good point. Some searches will yield multiple formula from different taps, so the output might have to be processed a bit—grouped by tap, maybe with a heading `brew tap Caskroom/cask` above each.

**Comment by anentropic** [comment]
yes, I just really wanted something to say "hey we found this, you can install it by `brew install Caskroom/cask/xld`"

so simple and yet not quite obvious

**Comment by mikemcquaid** [comment]
What about `==> Searching taps... (install with brew install)` or something?

**Comment by bfontaine** [comment]
We could do something like what [homebrew/command-not-found](https://github.com/Homebrew/homebrew-command-not-found) does, e.g.:

```
==> Searching formulae...
==> Searching taps...
Caskroom/cask/xld

Use: brew install <selected formula>
```

**Comment by mikemcquaid** [comment]
@bfontaine works for me :+1:

**Comment by DomT4** [comment]
:+1:. I was going to suggest something like `Maybe you want brew install homebrew/dupes/make` or similar, so @bfontaine's suggestion works nicely.

**Comment by anentropic** [comment]
I will just say, in this example:

```
==> Searching formulae...
==> Searching taps...
Caskroom/cask/xld

Use: brew install <selected formula>
```

it's not clear to me if `Caskroom/cask/xld` is a "tap" or a "formula"

be as explicit as possible if you're going to add a help message

**Comment by mikemcquaid** [comment]
Perhaps:

```
==> Searching local formulae...
==> Searching remote formulae in taps...
Caskroom/cask/xld

Use: brew install <selected formula>
```

**Comment by ericandrewlewis** [comment]
It's a tricky line to walk between using homebrew jargon and giving comprehensible feedback to users who don't know the jargon.

Hopefully we can offer this at every step of the process.

```
$ brew install xplot
Error: No available formula for xplot 
Searching formulae...
Searching taps...
homebrew/x11/pyxplot	   homebrew/x11/xplot
```

In the previous interaction, I have some immediate questions.

First, I see `Error: No available formula for glerf`. This sounds like "no package found," so I can ignore the rest of the output. Is there a better description of the result we can offer here?

Right after that, it says `Searching formulae...`. What formulae is it searching now, if no available formula was found already? Feedback for this search would be helpful. Like `No {formulae in this context} were found`.

After that, `Searching taps...`. What is a tap? Then after I see a few paths that look semi-related to the software I tried to install. 

As has been suggested before on this ticket, instructions as to what to do would be helpful. e.g. 

```bash
These package formulae were found, but not in the main repository:
homebrew/x11/pyxplot	   homebrew/x11/xplot

If you meant to install one of them, run `brew install <formula-path>`
```

**Comment by mikemcquaid** [comment]
@ericandrewlewis I really like your approach there. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

If not: no worries and I'll take a look. Thanks!

**Comment by ericandrewlewis** [comment]
I've opened pull request #44892 as a first pass. Any feedback appreciated :smile: 

Here's what install log looks like:

<img width="414" alt="screen shot 2015-10-13 at 11 58 32 am" src="https://cloud.githubusercontent.com/assets/1087646/10460373/06e7763c-71a2-11e5-89f0-4af86dc6b2aa.png">
