### ISSUE TITLE
Postgres install fails on OSX 10.11

### ISSUE THREAD

**Issue by codeOfRobin** [Homebrew/homebrew#42223]
I get the following error:

==> ./configure --prefix=/usr/local/Cellar/postgresql/9.4.4 --datadir=/usr/local
checking for library containing readline... no
configure: error: readline library not found
If you have readline already installed, see config.log for details on the
failure.  It is possible the compiler isn't looking in the proper directory.
Use --without-readline to disable readline support.

I've done brew install readline, and it said the following:

This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include

**Comment by bfontaine** [comment]
Please post the output of `brew gist-logs postgresql`.

**Comment by codeOfRobin** [comment]
https://gist.github.com/anonymous/cb85fc55140cc15b640b

**Comment by psmarcin** [comment]
I also have almost the same issue. 
```
checking for library containing readline... no
configure: error: readline library not found
If you have readline already installed, see config.log for details on the
failure.  It is possible the compiler isn't looking in the proper directory.
Use --without-readline to disable readline support.
```

https://gist.github.com/anonymous/b714138b62cf5d4ba8d5

**Comment by codeOfRobin** [comment]
I think it's an issue with the postgres formula( I did install it on a different machine with an identical installation of El Capitan in a previous beta). Is there any way to force it to build with the gnu readline or without readline for now?

**Comment by CaioBianchi** [comment]
Same error: 

    checking for library containing readline... no
    configure: error: readline library not found
    If you have readline already installed, see config.log for details on the
    failure.  It is possible the compiler isn't looking in the proper directory.
    Use --without-readline to disable readline support.

**Comment by nealyoung** [comment]
I got the same error, but had success installing Postgres after changing my command line tools to the Xcode 7 version in the Xcode preferences.

**Comment by slonoed** [comment]
@nealyoung hi! Could you provide small manual how you achieve this, please?

**Comment by codeOfRobin** [comment]
@slonoed It involves opening xcode -> Preferences ->Locations->command line tools.
Apologies for not closing this issue earlier. Updating Xcode (via a download from developer.apple.com, not the Mac App Store) appears to solve the issue

**Comment by mariusk** [comment]
The suggested change with xcode doesn't work here. I've even removed the readline stuff in the postgresql formula, but then it starts complaining about zlib:

```
checking for inflate in -lz... no
configure: error: zlib library not found
If you have zlib already installed, see config.log for details on the
failure.  It is possible the compiler isn't looking in the proper directory.
Use --without-zlib to disable zlib support.
```
FWIW, I have both readline and zlib installed.

**Comment by mariusk** [comment]
After a lot of trial and error and with the help of the fine folks in the #machomebrew IRC channel, doing this:

    sudo xcode-select -s /Library/Developer/CommandLineTools

before installation seems to solve most of the issues. I can not rule out that all my attempts at building/linking libxml2 and openssl also contributed, but the final breakthrough came after doing the xcode-select (effectively moving it away from pointing into the SDK). This assumes you have the cmdline tools installed of course. The people in the IRC channels still seems to believe there is something wrong with the build procedures somewhere that messes with some linker settings, but in the meantime maybe what I shared may help others struggling.
