### ISSUE TITLE
audit `head` should be put before `bottle block`

### ISSUE THREAD

**Issue by nijikon** [Homebrew/homebrew#42231]
I think there is a bit of inconsistency in the audit command. For example, for bind it is reporting ```* `head` (line 17) should be put before `bottle block` (line 10)```, but for ```awscli``` there is no message that head is after bottle block. Why is that?

https://github.com/Homebrew/homebrew/blob/master/Library/Formula/bind.rb#L17
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/awscli.rb#L15

**Comment by dunn** [comment]
`head` as a one-liner is treated differently than a `head do` block: https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/audit.rb#L163-L178

The former needs to be above the bottle block, the latter below.  I agree this is a bit odd, and I wouldn't mind having the head block go above the bottle block as well.

**Comment by DomT4** [comment]
Yes, indeed. `head` *lines* should go either at the end of the initial block, or one empty line after the initial block. `head` *blocks* should go underneath the `bottle do` block (If one exists) and the `devel do` block (If one exists).

**Comment by DomT4** [comment]
FWIW, I'm kind of against allowing `head` blocks above the `bottle` block. I think it's relatively clear at the moment that `bottle do` applies to the stable build, whereas if we place the `bottle` block directly underneath the `head` it's likely to appear we bottle `head` builds to newcomers. This will become a particular problem when we start adding `devel` bottles, which is in the pipeline.

**Comment by dunn** [comment]
@DomT4 That makes sense.  Let's leave it as-is, then.

@nijikon Is that a satisfactory explanation?

**Comment by nijikon** [comment]
IMHO, regardless if it is ```head``` or ```head do``` it should be in the same place. I say +1 to changed this.

**Comment by mikemcquaid** [comment]
Passing on this, sorry!
