### ISSUE TITLE
googlecl is broken and outdated, remove it

### ISSUE THREAD

**Issue by therealmarv** [Homebrew/homebrew#42245]
googlecl is broken and outdated for a while. To be exactly since April 20th, 2015.

Main reason is that googlecl depends on OAuth1 which does not work with Google's API anymore.
There is also no indication from Google that this will be fixed in the near future. They do not care of googlecl it seems.

Details here:
https://code.google.com/p/googlecl/issues/detail?id=573

RIP googlecl

**Comment by mikemcquaid** [comment]
Yeh, we should migrate it to `homebrew-boneyard` :+1:
