### ISSUE TITLE
Error while installing node0.10 on mac yesomite

### ISSUE THREAD

**Issue by manimis902** [Homebrew/homebrew#42262]
Error: undefined method `desc' for Node010:Class
Please report this bug:
    https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-versions/node010.rb:3:in `<class:Node010>'
/usr/local/Library/Taps/homebrew/homebrew-versions/node010.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:185:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:198:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:28:in `install'
/usr/local/Library/brew.rb:136:in `<main>'

**Comment by DomT4** [comment]
Your Homebrew may be outdated or have unexpected local modifications. Does the error persist after running a `brew update`?

**Comment by manimis902** [comment]
Sorry for late follow-up. Yes it works after brew update.
