### ISSUE TITLE
Install program in different language

### ISSUE THREAD

**Issue by antares2001** [Homebrew/homebrew#42265]
Dear maintainers,

thank you for such a great software like homebrew. I'm sorry to ask this here, but since Google didn't help me find an answer to my question and also looking at the help documentation didn't reveal what I was looking for, I would suggest to add an option to configure homebrew to install programs in a particular language. For now Microsoft's Office, Mozilla's Thunderbird, etc. are all installed in English, though I would like them in German. Would it be possible to add a language flag that downloads the corresponding version?

Thanks and keep your great work going!
--Andy

**Comment by DomT4** [comment]
Hi! Thanks for the issue.

The software you mentioned by name here are formulae distributed by [The Cask](https://github.com/caskroom/homebrew-cask) which is an independent project tied into the Homebrew ecosystem. Did you intend to file this issue there or is there something in Homebrew we can help with?

**Comment by DomT4** [comment]
Presuming you meant to ask the Cask about this, but please let us know if there's anything you'd like us to consider improving at Homebrew - Thanks!
