### ISSUE TITLE
acme is 404

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42272]
The download and home pages for the `acme` formula are returning 404 Page Not Found errors for me for the last 3 days (7/28, 7/29, 7/30/2015), and `brew install acme` is failing because of it.

I googled around and couldn't find a different project home page, aside from the [SourceForge `acme-crossass` project](http://sourceforge.net/projects/acme-crossass), which doesn't seem to be active or have versioned downloads.

Don't know if this is a transient server problem or if it's moved. Maybe someone who speaks German could have a look at the site and see if it might have been relocated?

http://www.esw-heim.tu-clausthal.de/~marco/smorbrod/acme/
http://www.esw-heim.tu-clausthal.de/~marco/smorbrod/acme/current/acme091src.tar.gz

**Comment by mistydemeo** [comment]
It looks like the homepage was up as recently as May: http://web.archive.org/web/20150520143433/https://www.esw-heim.tu-clausthal.de/~marco/smorbrod/acme/ No information about it moving then.

**Comment by mistydemeo** [comment]
Updated to use the Minix mirror for the URL and the Archive.org mirror for the homepage.

**Comment by DomT4** [comment]
Heh, Misty beat me to it :). There's also `https://www.mirrorservice.org/sites/ftp.cs.vu.nl/pub/minix/distfiles/backup/acme091src.tar.gz` if we wanted a secure link.
