### ISSUE TITLE
cmake 3.3.0 SHA256 mismatch

### ISSUE THREAD

**Issue by margjakob** [Homebrew/homebrew#42270]
==> Upgrading cmake
==> Downloading http://www.cmake.org/files/v3.3/cmake-3.3.0.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 857c2f755fe0794d038d6fa462a173d05b210ac2c07ff82f0af853acef231a34
Actual: 193b33e1f4966d74f6edf2fedbcadce324b4d3bf3926768d5a3d71b220358d64
Archive: /Library/Caches/Homebrew/cmake-3.3.0.tar.gz

**Comment by dunn** [comment]
I'm not getting the mismatch:
```
Downloaded to: /Library/Caches/Homebrew/cmake-3.3.0.tar.gz
SHA1: 7ffe0c67c25ee11d74cf7ab8022645151a0d72d2
SHA256: 857c2f755fe0794d038d6fa462a173d05b210ac2c07ff82f0af853acef231a34
```
Can you try removing `/Library/Caches/Homebrew/cmake-3.3.0.tar.gz` and downloading CMake again?

**Comment by margjakob** [comment]
Already tried that. Also tried manual download.
~$ sha256sum cmake-3.3.0.tar.gz
193b33e1f4966d74f6edf2fedbcadce324b4d3bf3926768d5a3d71b220358d64  cmake-3.3.0.tar.gz

**Comment by margjakob** [comment]
Ok. I just opened up a vpn connection and do the whole thing again. This time it works, sha256 match.
Something weird with my network?!

**Comment by dunn** [comment]
Maybe! Glad you got a working download, though!
