### ISSUE TITLE
dyld: Library not loaded: /usr/local/lib/libgmodule-2.0.0.dylib

### ISSUE THREAD

**Issue by solocshaw** [Homebrew/homebrew#42274]
dyld: Library not loaded: /usr/local/lib/libgmodule-2.0.0.dylib
      Referenced from: /usr/local/bin/irssi
      Reason: image not found
    Trace/BPT trap: 5

I had previously installed irssi through MacPorts (uninstalled now) and am running into this error after installing with Homebrew.

**Comment by DomT4** [comment]
Try `brew reinstall glib`.

**Comment by DomT4** [comment]
Presuming fixed.
