### ISSUE TITLE
formula Suricata: run without sudo

### ISSUE THREAD

**Issue by Drewshg312** [Homebrew/homebrew#42280]
Hi. Is there any possibility to run suricata (installed with homebrew) without `sudo`

I'm getting: 

    $ suricata -c /usr/local/etc/suricata/suricata.yaml -i en2
    Error opening file /var/log/suricata/suricata.log
    30/7/2015 -- 16:05:35 - <Notice> - This is Suricata version 2.0.8 RELEASE
    30/7/2015 -- 16:05:41 - <Error> - [ERRCODE: SC_ERR_PCAP_ACTIVATE_HANDLE(27)] - Couldn't activate the pcap handler, error (cannot open BPF device) /dev/bpf0: Permission denied
    30/7/2015 -- 16:05:41 - <Error> - [ERRCODE: SC_ERR_THREAD_INIT(49)] - thread "RxPcapen21" closed on initialization.
    30/7/2015 -- 16:05:41 - <Error> - [ERRCODE: SC_ERR_INITIALIZATION(45)] - Engine initialization failed, aborting...

Any ideas?

**Comment by tdsmith** [comment]
I think this is a suricata usage question that isn't specific to Homebrew so you might want to seek out suricata support fora. You can probably make /dev/bpf0 owned by the admin group and assign group read permissions. Let us know if we can help with anything else.
