### ISSUE TITLE
brew doctor errors after brew update

### ISSUE THREAD

**Issue by gordyt** [Homebrew/homebrew#42297]
Greetings All,

I am running the following:
- XCode, Version 6.4 (6E35b)
- Mac OS X, Version 10.10.4

This morning I did a `brew update` followed by a `brew outdated` and got the following:

    Error: undefined method `to_sym' for nil:NilClass
    Please report this bug:
        https://git.io/brew-troubleshooting
    /usr/local/Library/Homebrew/tab.rb:196:in `spec'
    /usr/local/Library/Homebrew/formulary.rb:187:in `from_rack'
    /usr/local/Library/Homebrew/formula.rb:691:in `block in installed'
    /usr/local/Library/Homebrew/formula.rb:689:in `map'
    /usr/local/Library/Homebrew/formula.rb:689:in `installed'
    /usr/local/Library/Homebrew/cmd/outdated.rb:6:in `outdated'
    /usr/local/Library/brew.rb:125:in `<main>'

And `brew doctor` reports the following:

    No check available by the name: check_missing_deps
    No check available by the name: check_for_linked_keg_only_brews

`HEAD` of my Homebrew git repo in `/usr/local` is currently on commit `7b83bac11d3b4266074eef097605d4823bf27c27`.

Any ideas? I did run through the troubleshooting steps.

**Comment by xu-cheng** [comment]
Sorry my bad. Should be fixed now. Can you try `brew update` again? Thanks.

**Comment by mikemcquaid** [comment]
@xu-cheng I think we should probably catch a lot more of these exceptions in `brew update`.

**Comment by xu-cheng** [comment]
@mikemcquaid This error happens in `brew outdated` not `brew update`.

**Comment by mikemcquaid** [comment]
@xu-cheng Whoops, misread, thanks!

**Comment by gordyt** [comment]
Fantastic!  Thank you.  That fixed the issue.
