### ISSUE TITLE
wireshark-1.12.6 configure: error: I couldn't find pod2html

### ISSUE THREAD

**Issue by marek-step** [Homebrew/homebrew#42294]
Hello all!

I was not able to update wireshark. So I uninstalled it and tried to reinstall: 

    brew install wireshark --with-qt

    ...

    ./configure --disable-silent-rules --prefix=/usr/local/Cellar/wireshark/1.12.6 --with-gnutls --disable-gtktest --with-qt

    ...

    checking for pod2html... no
    configure: error: I couldn't find pod2html; make sure it's installed and in your path

I tried to install pod2html with brew. But no formula found. I have in my `/usr/bin` following pod2html: 

    -rw-rw-rw-  34 root  wheel    811 10 Sep  2014 pod2html
    -rwxr-xr-x   1 root  wheel   2073 10 Sep  2014 pod2html5.16*
    -rwxr-xr-x   1 root  wheel   2073 10 Sep  2014 pod2html5.18*

And I have no response with the command: `which pod2html` Do I need to chmod the pod2html +x ?

Thank you 

marek

**Comment by bfontaine** [comment]
Yes it should be executable. Here is what I have on Yosemite:

```
-rwxr-xr-x  38 wheel   811B 10 sep  2014 /usr/bin/pod2html*
-rwxr-xr-x   1 wheel   2,0K 10 sep  2014 /usr/bin/pod2html5.16*
-rwxr-xr-x   1 wheel   2,0K 10 sep  2014 /usr/bin/pod2html5.18*
```

**Comment by marek-step** [comment]
thank you! This solved my problem. Funny that in my /usr/bin were all pod2... not executable. 

marek
