### ISSUE TITLE
brew install tomcat7

### ISSUE THREAD

**Issue by sgarnepudi** [Homebrew/homebrew#42313]
$ brew install tomcat7
Error: undefined method `desc' for Formulary::Formulae::Tomcat7:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-versions/tomcat7.rb:2:in `<class:Tomcat7>'
/usr/local/Library/Taps/homebrew/homebrew-versions/tomcat7.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:140:in `<main>'

**Comment by bfontaine** [comment]
Please run `brew update` then try again.

**Comment by DomT4** [comment]
Likely cause is that your Homebrew hasn't been updated recently, or there's uncommitted modifications to your local repo. Try `brew update` and provide a `brew config` if not, Thanks!

**Comment by sgarnepudi** [comment]
Worked!! Thanks
