### ISSUE TITLE
brew install erlang: Error: wrong number of arguments (0 for 3)

### ISSUE THREAD

**Issue by vivalavodka** [Homebrew/homebrew#42334]
brew install couchdb
==> Installing couchdb dependency: erlang
Warning: Formula file is modified!
Building from source because Library/Formula/erlang.rb has local changes
To install from a bottle instead, run with --force-bottle
==> Downloading https://github.com/erlang/otp/tarball/OTP_R15B03-1
Already downloaded: /Library/Caches/Homebrew/erlang-R15B03-1
==> Compilation takes a long time; use `brew install -v erlang` to see progress
==> ./otp_build autoconf
==> ./configure --prefix=/usr/local/Cellar/erlang/R15B03-1 --enable-kernel-poll --enable-threads --enable-dynamic-ssl-li
brew install -v erlang
==> make
==> make install
Error: wrong number of arguments (0 for 3)
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula.rb:94:in `initialize'
/usr/local/Library/Formula/erlang.rb:92:in `new'
/usr/local/Library/Formula/erlang.rb:92:in `install'
/usr/local/Library/Homebrew/build.rb:129:in `block in install'
/usr/local/Library/Homebrew/formula.rb:571:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:979:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:91:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:971:in `stage'
/usr/local/Library/Homebrew/formula.rb:567:in `brew'
/usr/local/Library/Homebrew/build.rb:107:in `install'

**Comment by mikemcquaid** [comment]
You've modified the `erlang` formula. Undo any modifications (or ask us for help if you don't know how to do that).

**Comment by vivalavodka** [comment]
What I modified is based on https://github.com/Homebrew/homebrew-versions/commit/35669870fe7988691e7d9e6ec472a22b845f2869.
If I didn't modify, error will be:
==> Compilation takes a long time; use `brew install -v erlang` to see progress
==> ./otp_build autoconf
***************************************************
***************************************************

=== running autoconf in lib
./otp_build: line 372: autoconf: command not found

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
erlang: update to otp-18.0 https://github.com/Homebrew/homebrew/pull/41035
relx: add erlang release tool https://github.com/Homebrew/homebrew/pull/36839
brew install erlang: Error: wrong number of arguments (0 for 3) https://github.com/Homebrew/homebrew/issues/42334
erlang (bottled) linked to iODBC instead of unixODBC https://github.com/Homebrew/homebrew/issues/38845

**Comment by vivalavodka** [comment]
I just add one statement:
depends_on :autoconf

**Comment by vivalavodka** [comment]
Undo is necessary. And the error is still as I just mentioned.
But after I remove the erlang.rb from the Formula, and then put it back.
Installation is successful, I don't know why.
Still Thanks a lot.

**Comment by mikemcquaid** [comment]
Great, thanks.
