### ISSUE TITLE
In Some Cases 'brew deps --installed formula' Misses Deps 

### ISSUE THREAD

**Issue by the-real-tokai** [Homebrew/homebrew#42342]
In some cases `brew deps --installed formula` misses to list dependencies, even if those dependencies are installed. It seems to be a case to resolve special build deps like `depends_on :hg => :build`.

E.g. `mercurial` (aka 'hg') is installed on my system:

    $ brew info mercurial
    mercurial: stable 3.5 (bottled)
    Scalable distributed version control system
    https://mercurial.selenic.com/
    /usr/local/homebrew/Cellar/mercurial/3.4.2 (370 files, 5.1M) *
      Poured from bottle
    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/mercurial.rb
    ...

Using `deps` without any parameters lists it as dependency:

    $ brew deps gdrive
    git
    go
    mercurial

but, no output at all with:

    $ brew deps --installed gdrive
    $

Mercurial was only installed for `gdrive` on my system. It is somewhat strange anyway since `gdrive `was bottled, so a build-dep like `mercurial` is somewhat superfluous in this case as nothing had to be build. `git` and `go` were properly skipped.

Maybe not a bug? But I find it somewhat confusing if it is missing in the `deps --installed` output even though the formula in question is actually installed and was only installed as dependency for the with `brew deps --installed` inspected component in question.

**Comment by the-real-tokai** [comment]
I updated the outdated `mercurial` version earlier and suddenly it is working properly again:

    $ brew deps --installed gdrive
    mercurial

**Comment by DomT4** [comment]
This is expected, I believe.

`installed` = "Does the user have the most recent formula installed?". Our logic elsewhere is similar - If you update `brew` but don't upgrade at the same time, and then do `brew info xyz` you'll see any updated dep is now marked with a red cross even if you have the prior version installed.

Will let @mikemcquaid review, but I think this is all intentional.

**Comment by mikemcquaid** [comment]
Yeh, it's annoying but somewhat intentional (or at least intentional enough that fixing it would risk breaking other people's scripts)

**Comment by DomT4** [comment]
Closing per the above.
