### ISSUE TITLE
Chromium CLI

### ISSUE THREAD

**Issue by dardo82** [Homebrew/homebrew#42349]
Could we add chromium-cli (that's available [here] (https://github.com/prasmussen/chrome-cli/issues/31)) to the keg of chrome-cli (alongside chrome-canary-cli)?

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by dardo82** [comment]
I'm not able to build the xcode project from the source (see [here] (https://github.com/prasmussen/chrome-cli/issues/31) why)
and I'm not sure how I should handle the binary tarball that homebrew
seems to use available from bintray.com to add the executable to it.

**Comment by mikemcquaid** [comment]
The binary tarball is generated from the Homebrew formula. You'll need to edit that and submit a pull request to update it.

**Comment by dardo82** [comment]
Ah, it's compiled on some smart cloud build server where the process doesn't fail miserably as it does on my machine? That explains something and I could try to edit the formula adding a part for compiling chromium-cli(the same way it's done for chrome-canary-cli)hoping nothing goes wrong as I would not be able to test it.

**Comment by dunn** [comment]
If you want to take a stab at a PR, that'd be great!

**Comment by dardo82** [comment]
I tried but i failed, let's retry... :-|
