### ISSUE TITLE
ansible formula needs passlib

### ISSUE THREAD

**Issue by boneskull** [Homebrew/homebrew#42368]
As per the [Ansible documentation](http://docs.ansible.com/ansible/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module) the `passlib` Python module is necessary to use crypted passwords on OS X.

There is no `passlib` module in Homebrew.  In addition, using the system `pip` to install passlib results in failure, because Ansible cannot find `passlib` (it isn't in its `PYTHONPATH`).

I'm not sure of the best course of action here.  It seems this may be installed with `brew-pip`, but whether or not the module would be visible to Ansible even then is anyone's guess.

**Comment by boneskull** [comment]
Of note, a `brew install ansible` results in an ansible installation with its own Python package dir in `/usr/local/Cellar/ansible/1.9.2/libexec/lib/python2.7/site-packages` (I'm not sure why).  This would be the obvious place for `passlib` to be installed, but my attempts at using either `easy_install` or `pip` to put it there have failed.  

Ideally, whatever needs to happen should happen upon `brew install ansible`.

**Comment by boneskull** [comment]
(Workaround:  `pip install ansible` instead)

**Comment by mikemcquaid** [comment]
It'll need added to `ansible.rb`. Could you try and open a pull request to add it? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
