### ISSUE TITLE
SIP installation fails: can't download the .tar.gz

### ISSUE THREAD

**Issue by acogneau** [Homebrew/homebrew#42361]
Whenever I do:
```
brew install sip -with--python3
```
I get this:

```
==> Downloading http://www.riverbankcomputing.com/static/Downloads/sip4/sip-4.16

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "sip"
Download failed: http://www.riverbankcomputing.com/static/Downloads/sip4/sip-4.16.9.tar.gz
```

```
brew gist-logs sip
```

gives:
```
Error: No logs.
```

**Comment by The-Compiler** [comment]
That link should probably point to http://downloads.sourceforge.net/project/pyqt/sip/sip-4.16.9/sip-4.16.9.tar.gz instead.

It seems the location was changed by @jenshnielsen when updating to 4.16.9 in 850e0cb8c3fd2c1854ad8a96e0449f5ace6bdad6.

**Comment by jenshnielsen** [comment]
At that time sourceforge was down and the official download links on the riverbank homepage where pointing to the riverbankcomputing page. It seems like they have changed it back to point to sourceforge

**Comment by The-Compiler** [comment]
Bleh. I wish they'd just host everything on their page as sourceforge is... well, don't get me started.

Unfortunately they said they don't plan to do that when I asked.

**Comment by dunn** [comment]
Fixed, thanks for catching that!
