### ISSUE TITLE
center-im failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42381]
https://gist.github.com/ad569927b7e2dbdf5700

On 10.11 Public Beta 3. Fails to find gnutls-extra in `configure`.

```
configure: error: Could not find gnutls-extra. Stopping.
```

**Comment by DomT4** [comment]
Should be fixed by #42389.

**Comment by apjanke** [comment]
Yep, building with that patch succeeds on my 10.11 test box.
