### ISSUE TITLE
class-dump failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42384]
https://gist.github.com/4cd00f2a8da4b4bf8b6c

**Comment by DomT4** [comment]
Known issue in a way. It's trying to hook into OpenSSL headers which just don't exist on 10.11. Just for fun, you can make it use ours by passing `"OTHER_CFLAGS=-I#{Formula["openssl"].opt_include}", "OTHER_LDFLAGS=-L#{Formula["openssl"].opt_lib}"` but then you hit `libc++abi.dylib: terminating with uncaught exception of type NSException` at runtime, apparently.

**Comment by ShonFrazier** [comment]
Same on 10.10.5 with Xcode 7
https://gist.github.com/ShonFrazier/10815d45d3e07ba97350

**Comment by DomT4** [comment]
This is supposed to be fixed in the upstream head as far as I can see, but it's still linking to the system OpenSSL. Asked upstream about that here: https://github.com/nygard/class-dump/issues/56

**Comment by apjanke** [comment]
Not fixed upstream yet because of a lingering reference to `libcrypto` in the Xcode project file. Fixed in pending PR nygard/classdump#58.

**Comment by MTShare** [comment]
+1 Still get:

** BUILD FAILED **


The following build commands failed:
	CompileC build/class-dump.build/Release/MachObjC.build/Objects-normal/x86_64/CDLCSegment.o Source/CDLCSegment.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by DomT4** [comment]
Yes. Upstream hasn't touched the PR @apjanke submitted yet, which should resolve the failure.
