### ISSUE TITLE
initialising terminator asks for python libvte

### ISSUE THREAD

**Issue by aidylewis** [Homebrew/homebrew#42399]
After brew installing terminator (homebrew/x11/terminator-0.97) and attempting to run it, I receive a message box that informs me I need to install libvte. However, vte is already installed through homebrew. 

```sh
$ ~ brew install vte
Warning: vte-0.28.2 already installed
```

```sh
$ ~ brew -v
Homebrew 0.9.5
```

```sh
$ ~ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.9.5
BuildVersion:	13F34
```

**Comment by tdsmith** [comment]
This issue was moved to Homebrew/homebrew-x11#115
