### ISSUE TITLE
ctail failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42400]
https://gist.github.com/bba9778190a72d1b3652

On 10.11 PB3.

```
checking how to run the C preprocessor... cpp
configure: error: C preprocessor "cpp" fails sanity check
See `config.log' for more details.
```

**Comment by DomT4** [comment]
Moving to tracking in #40837. If you report this one upstream let us know in that thread and I'll add a link to that report, Thanks!

**Comment by apjanke** [comment]
Upstream bug report: pquerna/ctail#1
