### ISSUE TITLE
qemu does not build on 10.6

### ISSUE THREAD

**Issue by negahecodu** [Homebrew/homebrew#42419]
OS X 10.6

    bash-3.2$ brew install qemu
    clang version 1.0 (http://llvm.org/svn/llvm-project/cfe/tags/Apple/clang-23 exported)
    Target: x86_64-apple-darwin10 
    ==> Installing dependencies for qemu: glib, pixman
    ==> Installing qemu dependency: glib
    ==> Downloading https://download.gnome.org/sources/glib/2.44/glib-2.44.1.tar.xz
    curl: (35) error:14077458:SSL routines:SSL23_GET_SERVER_HELLO:reason(1112)
    Error: Failed to download resource "glib"
    Download failed: https://download.gnome.org/sources/glib/2.44/glib-2.44.1.tar.xz

The URL specified is does not exist:

    url "https://download.gnome.org/sources/glib/2.44/glib-2.44.1.tar.xz"

If you try this URL, you will receive a 302 redirect. Unfortunately CURL cannot handle these redirects. So homebrew will fail with installing glib, or any dependent package. (For example, qemu).

FIX:

Change to:

    url "https://www.mirrorservice.org/sites/ftp.gnome.org/pub/GNOME/sources/glib/2.44/glib-2.44.1.tar.xz"

As the correct URL

**Comment by dunn** [comment]
Usually curl can handle redirects fine; it certainly does for me:
```
🔥  brew fetch -fs glib
==> Downloading https://download.gnome.org/sources/glib/2.44/glib-2.44.1.tar.xz
==> Downloading from https://mirror.umd.edu/gnome/sources/glib/2.44/glib-2.44.1.tar.xz
######################################################################## 100.0%
Downloaded to: /Library/Caches/Homebrew/glib-2.44.1.tar.xz
SHA1: 88176375f97ecd9ff45e7b5fd5ab80d4b7db6b34
SHA256: 8811deacaf8a503d0a9b701777ea079ca6a4277be10e3d730d2112735d5eca07
```
Is it possible you have something in your `~/.curlrc` that's preventing curl from following redirects?

**Comment by DomT4** [comment]
I think the issue here is different. 10.6's `curl` has known problems handling certain newer TLS ciphers, and when the server doesn't offer them will just die.

Can you try `brew install curl` and then `brew fetch qemu -fs -f` and see what happens?

**Comment by DomT4** [comment]
Presuming no longer an issue.
