### ISSUE TITLE
python ImportError: No module named _curses

### ISSUE THREAD

**Issue by zwb-ict** [Homebrew/homebrew#42411]
I use brew install python, it seems OK.
I run python, then input import curses, get an error:

Python 2.7.10 (default, Jul 18 2015, 17:21:56)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cursses
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named cursses
>>> import curses
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/curses/__init__.py", line 15, in <module>
    from _curses import *
ImportError: No module named _curses
>>>

OS version: 10.11.

I run Mac system's python, it can import curses correctly.

**Comment by tdsmith** [comment]
Can you share the output of `brew gist-logs python`? It looks like you're on 10.11. Are you using the beta Xcode? It won't work otherwise. The most common reason for this is that the OS X 10.11 SDK libraries weren't available at build time.

**Comment by zwb-ict** [comment]
@tdsmith Thank you for your help! This is the result of brew gist-logs python: https://gist.github.com/43a37fd0cf49bdd0764e

**Comment by zmwangx** [comment]
From https://gist.githubusercontent.com/anonymous/43a37fd0cf49bdd0764e/raw/57610a6a56de348bf28ff7ac7da6753936bd8160/02.make:

```
Python build finished, but the necessary bits to build these modules were not found:
_bsddb             _curses            _curses_panel   
_sqlite3           bz2                dl              
imageop            linuxaudiodev      ossaudiodev     
spwd               sunaudiodev        zlib            
To find the necessary bits, look in setup.py in detect_modules() for the module's name.
```

Apparently the exact same problem as #41085 "Python fails to build core extension modules on 10.11".

**Comment by tdsmith** [comment]
If you run `brew irb` and enter `OS::Mac::Xcode.prefix` and `MacOS.sdk_path`, what's printed?

The workaround is to run `xcode-select --install` to install the Command Line Tools package.

**Comment by zwb-ict** [comment]
@tdsmith 
==> Interactive Homebrew Shell
Example commands available with: brew irb --examples
irb(main):001:0> OS::Mac::Xcode.prefix
=> #<Pathname:/Applications/Xcode-beta.app/Contents/Developer>
irb(main):002:0> MacOS.sdk_path
=> #<Pathname:/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk>
irb(main):003:0>

**Comment by zwb-ict** [comment]
@tdsmith 
Cool , I run **xcode-select --install**, and reinstalled python again. It's OK now!

**Comment by tdsmith** [comment]
Thanks!
