### ISSUE TITLE
Go --devel 1.5

### ISSUE THREAD

**Issue by apriendeau** [Homebrew/homebrew#42430]
The issue with the way that it is implemented is that it forces you to uninstall go 1.4.2 and not have it there at all. To create

```shell
brew install go
brew unlink go
brew install --devel go
Cannot install go 1.5beta3 because go 1.4.2 is already installed
```

You have to `brew uninstall` then brew install --devel go for it to work. This breaks the contract of unlink or am I mistaken?

**Comment by kkdai** [comment]
"brew upgrade go -v=1.5beta3 --devel"  works for me.

**Comment by apriendeau** [comment]
This worked for me
