### ISSUE TITLE
Getting "Failed to fix install names" when installing any formula

### ISSUE THREAD

**Issue by tgkokk** [Homebrew/homebrew#42446]
`brew config`, `brew doctor` and (e.g.) output of `brew install -vd findutils` (note that this bug isn't confined to `findutils`): https://gist.github.com/tgkokk/1aebf73eabbe97699dd7
As you will see in the log, I also get a Ruby error that `true` can't be converted into a `String`.

**Comment by mikemcquaid** [comment]
Please `brew update` and see if it still happens, thanks.

**Comment by tgkokk** [comment]
Umm... it works now. Thanks.
