### ISSUE TITLE
Formula needed for MicroPython on Mac OS X

### ISSUE THREAD

**Issue by cclauss** [Homebrew/homebrew#42448]
https://github.com/micropython/micropython/wiki/Getting-Started#mac-osx

MicroPython is a rewrite of Python 3.4 for use in embedded applications however it also runs on Mac OS X.  Given the instructions above, I do not know how to create a Homebrew formula for MicroPython.

**Comment by mikemcquaid** [comment]
We don't really do formula requests I'm afraid. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
