### ISSUE TITLE
qt5 installing without dependencies

### ISSUE THREAD

**Issue by olivierlacan** [Homebrew/homebrew#42457]
Is it normal that `qt5` installs without the stated dependencies on `xz`, `pkg-config` and (optional) `d-bus`?

**Comment by DomT4** [comment]
Depends on how you're installing it. `xz` and `pkg-config` are only build-time dependencies, rather than run-time, so if you're not building from source you don't need them and we don't install them. `d-bus` is runtime but is optional, so we don't drag that in unless you request it.

**Comment by DomT4** [comment]
Presuming question resolved.
