### ISSUE TITLE
AutoJump .bash_profile instructions incorrect

### ISSUE THREAD

**Issue by olivierlacan** [Homebrew/homebrew#42453]
I recently installed AutoJump on a brand new machine and the new post-install instructions say:

```
Add the following line to your ~/.bash_profile or ~/.zshrc file (and remember
to source the file to update your current session):
  [[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh
```

This doesn't work (`cd` commands don't get added to `autojump -s`) whereas the old configuration still works fine:

```
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh
```

**Comment by dunn** [comment]
`etc/autojump.sh` is just a symlink to `etc/profile.d/autojump.sh`, so I'm not sure why this is happening: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/autojump.rb#L14

Does `$(brew --prefix)/etc/profile.d` exist in your installation?

**Comment by DomT4** [comment]
Closing per no response.
