### ISSUE TITLE
ghc formula doesn't install from binary on OS X 10.11

### ISSUE THREAD

**Issue by LukeHoersten** [Homebrew/homebrew#42469]
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ghc.rb

When running `brew install ghc` on OS X 10.11 it installs from source instead of the binary. This is extremely slow (though it works).

I'm assuming it's the fact that I'm on 10.11 that's causing the source install thought I'm not sure.

**Comment by mistydemeo** [comment]
We don't have binary packages for 10.11 yet; we'll begin uploading 10.11 packages within a few weeks of release.

**Comment by LukeHoersten** [comment]
OK Thanks.
