### ISSUE TITLE
Formula for gprof?

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew#42462]
Could someone publish a Homebrew formula for gprof?

https://sourceware.org/binutils/docs/gprof/

**Comment by mistydemeo** [comment]
My understanding is that [gprof does not work on OS X](https://trac.macports.org/ticket/44628).

**Comment by mikemcquaid** [comment]
We also don't really do formulae requests. If it does work on OS X: could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
