### ISSUE TITLE
homebrew attempts to use system python rather than the version it just installed when building cmake

### ISSUE THREAD

**Issue by axfelix** [Homebrew/homebrew#42461]
Archives-Computer:~ charlott$ brew install mysql55
    ==> Installing mysql55 from homebrew/homebrew-versions
    ==> Installing dependencies for homebrew/versions/mysql55: cmake, pidof
    ==> Installing homebrew/versions/mysql55 dependency: cmake
    ==> Downloading http://www.cmake.org/files/v3.3/cmake-3.3.0.tar.gz
    Already downloaded: /Library/Caches/Homebrew/cmake-3.3.0.tar.gz
    ==> Downloading https://pypi.python.org/packages/source/d/docutils/docutils-0.12
    ######################################################################## 100.0%
    ==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/c
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --no-user-cfg not recognized
    
    READ THIS: https://git.io/brew-troubleshooting
    
I can fix this myself, but pretty sure it's an issue on 10.6 when system Python is 2.6 and doesn't recognize the option, unless I'm totally mis-diagnosing this issue.

**Comment by DomT4** [comment]
Can you provide a `brew config` please?

**Comment by axfelix** [comment]
sure!

Archives-Computer:~ charlott$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: (none)
HEAD: (none)
Last commit: never
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit penryn
OS X: 10.6.8-i386
Xcode: 4.2
CLT: N/A
LLVM-GCC: build 2336
Clang: 3.0 build 211
X11: 2.3.6 => /usr/X11
System Ruby: 1.8.7-p358
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: openjdk version "1.7.0-u60-b19"

**Comment by DomT4** [comment]
Thanks! It's still saying your Python there is the 2.6.x version in `/usr/bin` - What output do you get if you run `brew install python`?

**Comment by axfelix** [comment]
I'll check after this is all done -- for now I've gotten it to work successfully by re-exporting my path so that the homebrew directories are first.

**Comment by DomT4** [comment]
Sure thing. Try a `brew doctor` printout as well - I'm wondering if `/usr/bin` is ahead of `/usr/local/bin` in your `$PATH` for whatever reason.

> ORIGIN: (none)
HEAD: (none)
Last commit: never

This is interesting. That shouldn't be blank. Do you have any problems with `brew update`?

**Comment by axfelix** [comment]
/usr/bin has tended to wind up ahead of /usr/local/bin in my path when I've used homebrew on 10.6 in the past ...

**Comment by DomT4** [comment]
Make sure `export PATH=/usr/local/bin:$PATH` is a line in whatever shell configuration you use, such as `.zshrc` for `zsh`, `.bash_profile` for `bash`, etc.

**Comment by axfelix** [comment]
Yup, I know about that as a best practice, just wasn't sure if it was documented as a prerequisite, particularly when brew is installing a version of python as part of the same install process.

**Comment by mistydemeo** [comment]
Superenv does add the path to what it thinks is the appropriate Python here: https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/requirements/python_requirement.rb#L27-L30

There's clearly a problem here, however, in that `which_python` will happily return the system Python if that's first in the PATH, even if it failed `satisfy` and triggered the installation of a Homebrew Python.

This should check if `which_python` is 2.7, and prepend the Homebrew Python's `opt_bin` path instead.

**Comment by mistydemeo** [comment]
Should be fixed now.
