### ISSUE TITLE
dhcpdump site is offline

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42475]
The URL `http://www.mavetju.org/download/dhcpdump-1.8.tar.gz` for dhcpdump is not responding, and the entire `www.mavetju.org` site appears to be offline, for at least a few days now. Connections with either `wget` or a browser are failing.

Formulae affected (determined by `grep -li mavetju /usr/local/Library/Formula`):
* `dhcpdump`
* `dhcping`
* `dnstracer`

A brief search turned up no alternate project pages. And the SourceForge files for the project only go up to dhcpdump 1.5, while we're on 1.8.

The Internet Archive actually has a copy of its download pages, including the dhcpdump 1.8 tarball our formula needs. http://web.archive.org/web/20130210091931/http://www.mavetju.org/download/ Is it appropriate to download from there?

I've sent the site owner an email using the [Contacts page found in the Internet Archive](http://web.archive.org/web/20141008024157/http://www.mavetju.org/contacts.php).

**Comment by dunn** [comment]
Shouldn't be a problem as long as the SHA matches. But if this is a long-term outage, @DomT4 has a repository for mirroring sources that we could upload it to (assuming the license allows): https://github.com/DomT4/LibreMirror

**Comment by apjanke** [comment]
Cool. Here's the license. (Found in the `dhcpdump` tarball.) I don't know if it has a name, but clearly would permit the mirroring. I'll see if the author responds in a couple days, and if not, mirror it and update the formulae.

```
Copyright 2001, 2002 by Edwin Groothuis, edwin@mavetju.org
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
ANY EXPRESS OR IMPLIED WARRANTIES
```

**Comment by mikemcquaid** [comment]
@dunn @DomT4 Would be good to use Bintray for mirroring rather than a GitHub repository.

**Comment by DomT4** [comment]
> Would be good to use Bintray for mirroring rather than a GitHub repository.

No rebuttal on that; Is near the top of my priority list.
