### ISSUE TITLE
python3: relinking fails due to site-packages

### ISSUE THREAD

**Issue by yesimon** [Homebrew/homebrew#42473]
After I install python3.4.3, relinking python fails `brew unlink python3; brew link python3`. This is due to the change where the Cellar site-packages is now a symlink to `HOMEBREW_PREFIX/lib/python3.4/site-packages` so the relink step fails because the target and source are reversed. Perhaps one way to fix this is reverse the symlink. This requires changes to the python formula to detect and patch up the symlink.

**Comment by tdsmith** [comment]
I can't reproduce:
```
tim@rocketman:~$ brew unlink python3; brew link python3
Unlinking /usr/local/Cellar/python3/3.4.3_2... 23 symlinks removed
Linking /usr/local/Cellar/python3/3.4.3_2... 23 symlinks created
```

site-packages has been linked that way for quite a while. Running `brew prune` after unlinking should help clean up any stale symlinks.

**Comment by yesimon** [comment]
I did `brew prune` and didn't help. To be clear I'm running this on linuxbrew with `HOMEBREW_PREFIX != /usr/local`.

I tried it on my mac and works fine, but I poked around and saw
```
simon@nitrogen /u/l/l/p/site-packages> ll /usr/local/opt/python3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages
lrwxr-xr-x  1 simon  staff    54B Jul 28 16:02 /usr/local/opt/python3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages -> ../../../../../../../../../lib/python3.4/site-packages
```

I think being a framework build protects it from this issue, although I haven't tried non framework install. That's also a nice relative path haha.

**Comment by yesimon** [comment]
Also just realized that there is no `--framework` option for python anymore and most people install from bottles nowadays...

**Comment by tdsmith** [comment]
> That's also a nice relative path haha.

Ha, yes.

Homebrew python3 is always a framework build on OS X; I'll move this issue to the linuxbrew repository.

**Comment by tdsmith** [comment]
This issue was moved to Homebrew/linuxbrew#502
