### ISSUE TITLE
discount failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42476]
https://gist.github.com/3ac42b6a075e5c0ec198

Failed during the `configure` stage with `(can't run cpp as a pipeline)`

**Comment by apjanke** [comment]
Discount is working now as of Public Beta 6 and the Xcode 7 GM. Can't reproduce the build failure any more.

**Comment by mikemcquaid** [comment]
Thanks for following this up and rechecking :+1:
