### ISSUE TITLE
echoping download fails

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42481]
The download for the `echoping` source tarball from SourceForge is failing. This manifests as a SHA mismatch instead of download failure, probably because SourceForge is redirecting it to their front page instead of 404ing it.

The echoping project seems to be gone from SourceForge. Its home page also redirects to a generic SourceForge landing page, and a search for "echoping" turns up zero hits.

```
$ brew install echoping                            
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Downloading https://downloads.sourceforge.net/project/echoping/echoping/6.0.
==> Downloading from http://sourceforge.net/publish/
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 6a06db4c7dc6d8a906613a2ed6027c28cdf1fe5d8b82c844344c3d7b9d1b2c75
Actual: e3bccf0d75b183e1c4a9e549b2e3697eacc1a8059ee9fff134d55a765f100b51
Archive: /Library/Caches/Homebrew/echoping-6.0.2.tar.gz
To retry an incomplete download, remove the file above.
```

Looks like there's an alternate download available from the GitHub project page at https://github.com/bortzmeyer/echoping/releases, but the SHA doesn't match. The GitHub page also notes the project is no longer maintained.

**Comment by DomT4** [comment]
Tempted to just boneyard it.

**Comment by apjanke** [comment]
No opinion here. I don't use or know `echoping`; I just ran in to this while doing "install everything" tests on 10.11.

**Comment by DomT4** [comment]
Was killed.
