### ISSUE TITLE
fossil failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42493]
https://gist.github.com/967082d2abb9a0ef0304

On OS X 10.11 PB4, no CLT. It's not finding Tcl.

```
Error: Cannot find Tcl on your system
Try: 'configure --help' for options
```

**Comment by DomT4** [comment]
If you're feeling particularly nice & are still running a CLT-untarnished system, can you test-build #43895? Thanks!

**Comment by apjanke** [comment]
Tested on CLT-free 10.9.5; works.
