### ISSUE TITLE
Update duplicity --devel to 0.7.04

### ISSUE THREAD

**Issue by Thinkscape** [Homebrew/homebrew#42508]
A lot of bugs fixed in this one ...

https://launchpad.net/duplicity/0.7-series

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
