### ISSUE TITLE
SHA-1 still mentioned in manpages

### ISSUE THREAD

**Issue by luzpaz** [Homebrew/homebrew#42507]
https://github.com/Homebrew/homebrew/blob/master/share/man/man1/brew.1#L101
https://github.com/Homebrew/homebrew/blob/master/share/man/man1/brew.1#L149

**Comment by bfontaine** [comment]
Do you mind making a pull-request? :smile: 
You’d need to edit [`brew.1.md`](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/manpages/brew.1.md) then run `brew man` to update the manpage.

**Comment by luzpaz** [comment]
@bfontaine what should the commit message be ?

**Comment by bfontaine** [comment]
@luzpaz something like “man: remove references to SHA1” would be fine.

**Comment by luzpaz** [comment]
PR is here: https://github.com/Homebrew/homebrew/pull/42516

**Comment by luzpaz** [comment]
Ok.. sorry totally ignored your instructions @bfontaine 
Where can i find brew.1.md on my local machine ?

**Comment by bfontaine** [comment]
Assuming your Homebrew is in `/usr/local` the file is `/usr/local/Library/Homebrew/manpages/brew.1.md`.

**Comment by luzpaz** [comment]
I changed the files locally. How do i push them ?
This is what I get when I run ```brew update```
```
🍎 Test:local blah$ brew update
Stashing your changes:
 M Library/Homebrew/manpages/brew.1.md
 M share/man/man1/brew.1
Restored your changes:
 M Library/Homebrew/manpages/brew.1.md
 M share/man/man1/brew.1
Already up-to-date.
```

**Comment by bfontaine** [comment]
You can do the following:

```
# create a new branch “man-sha1”
$ git checkout -b man-sha1

# add the files to the index
$ git add .

# commit
$ git commit -m "man: remove references to SHA1"

# push to your fork
$ git push -u git@github.com:luzpaz/homebrew.git man-sha1
```

You can then open your fork homepage in your browser and GitHub should suggest you to make a PR from your `man-sha1` branch.

**Comment by DomT4** [comment]
Any update on this?
