### ISSUE TITLE
cmake-3.2.2 SHA256 mismatch

### ISSUE THREAD

**Issue by ycrepeau** [Homebrew/homebrew#42513]
See: #40422 and #40429.

==> Installing cgal dependency: cmake
==> Downloading http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz
######################################################################## 100,0%
==> Downloading http://www.cmake.org/gitweb?p=cmake.git;a=commitdiff_plain;h=2ecf168f
######################################################################## 100,0%
Error: SHA256 mismatch
Expected: 147854010874cd68289e3ca203399d5c149287167bca0b67f9c5677f0ee22eb8
Actual: 0017011a8c75badb20599a56832d6cd04f89d441252a8d5ed0c04a252b8e40ac
Archive: /Library/Caches/Homebrew/cmake--patch-147854010874cd68289e3ca203399d5c149287167bca0b67f9c5677f0ee22eb8.git;a=commitdiff_plain;h=2ecf168f

I think the tickets cited above have been prematurely closed.

Special note: Running on Mac OS X 10.11 (El Capitan - Public Beta 4).

**Comment by dunn** [comment]
The version of CMake we provide is 3.3.0; have you run `brew update` recently?

**Comment by DomT4** [comment]
Yeah. Your Homebrew is quite significantly outdated - We switched to using a Github commit that wouldn't break, and then 3.3.0 was merged which removed the patch completely. Please `brew update` and try again.
