### ISSUE TITLE
Duplicity CF backend doesn't work, because "oslo" dep is not installed correctly

### ISSUE THREAD

**Issue by Thinkscape** [Homebrew/homebrew#42512]
@mikemcquaid Actually the install thing is kinda broken... when trying to use cf backend, it will throw an error:
````
BackendException: This backend requires the pyrax library available from Rackspace.
````

However, pyrax IS installed:
````
$ ls /usr/local/Cellar/duplicity/0.7.04_1/libexec/vendor/lib/python2.7/site-packages/ | grep pyrax
pyrax
pyrax-1.9.3-py2.7.egg-info
````

When you try the import from python CLI:
````
PYTHONPATH="/usr/local/Cellar/duplicity/0.7.04_1/libexec/vendor/lib/python2.7/site-packages:/usr/local/Cellar/duplicity/0.7.04_1/libexec/lib/python2.7/site-packages" python 
Python 2.7.10 (default, Jul 13 2015, 12:05:58)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyrax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyrax/__init__.py", line 58, in <module>
    from novaclient import auth_plugin as _cs_auth_plugin
  File "novaclient/auth_plugin.py", line 23, in <module>
    from novaclient import utils
  File "novaclient/utils.py", line 20, in <module>
    from oslo.utils import encodeutils
ImportError: No module named oslo.utils
````

Let's investigate oslo subdir:
````
$ ls /usr/local/Cellar/duplicity/0.7.04_1/libexec/vendor/lib/python2.7/site-packages/oslo
config        i18n          serialization utils
````

Notice that there's no `__init__.py` so python doesn't recognize it as a module, hence it will never work with duplicity :| Basically putting an empty init file into `oslo/` fixes everything.

Not sure how the brew build scripts work, don't know where to start.

**Comment by Thinkscape** [comment]
Oh, by "fixes everything" I mean running the uncompiled, non-concat version of the script works, i.e.:
> PYTHONPATH="/usr/local/Cellar/duplicity/0.7.04_1/libexec/vendor/lib/python2.7/site-packages:/usr/local/Cellar/duplicity/0.7.04_1/libexec/lib/python2.7/site-packages" python "/usr/local/Cellar/duplicity/0.7.04_1/libexec/bin/duplicity" / cf+hubic:/default

Ideally we'd fix the oslo installation before it gets compiled, so that main `$ duplicity` command starts working correctly.

**Comment by tdsmith** [comment]
Oops; namespace packages in unblessed site-packages are annoying. You're right about the solution; we should call `touch libexec/"the_path_to/__init__.py"` in in the formula's install method to create a dummy __init__.py for the namespace package.

**Comment by Thinkscape** [comment]
Are you suggesting to do that in this package, or within the python module
install routine?
On Thu, 6 Aug 2015 at 10:12 tim smith <notifications@github.com> wrote:

> Oops; namespace packages in unblessed site-packages are annoying. You're
> right about the solution; we should call touch
> libexec/"the_path_to/__init__.py" in in the formula's install method to
> create a dummy *init*.py for the namespace package.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Homebrew/homebrew/issues/42512#issuecomment-128286104>
> .
>
-- 
Artur Bodera
abodera@gmail.com
http://thinkscape.pro

**Comment by tdsmith** [comment]
In this package.

**Comment by Thinkscape** [comment]
I've just stumbled upon another crash, this time with onedrive backend which depends on `python-requests`. Same problem - module not found errors.

I couldn't quickly figure out how to solve that within brew package. I guess it's up to you @tdsmith :-)

**Comment by TimJDFletcher** [comment]
Same issue with the pydrive module for Google Drive access
