### ISSUE TITLE
csshx crashing with odd Perl error (tmux)

### ISSUE THREAD

**Issue by kevwil** [Homebrew/homebrew#42524]
```
ᕕ( ᐛ )ᕗ  $ csshX --login ubuntu --ssh_args "-i /path/to/my/aws/key.pem" 192.168.10.1 192.168.10.2 192.168.10.3
Aug  5 12:59:40 LaptopName perl[96970] <Error>: ImageIO: CGImageDestinationFinalize image destination must have at least one image
2015-08-05 12:59:40.958 perl5.18[96970:6474353] CGImageDestinationFinalize failed for output type 'public.tiff'
**** ERROR **** PerlObjCBridge:: convertPerlToObjC(): Referenced thingy not blessed
**** ERROR **** PerlObjCBridge:: convertArg() for index 2: convertPerlToObjC() failed
**** ERROR **** PerlObjCBridge:: sendObjcMessage: Error converting argument 1 for message "setObject:forKey:"
**** ERROR **** PerlObjCBridge: error [1] sending message [__NSDictionaryM setObject:forKey:] at /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level/PerlObjCBridge.pm line 248.
(╯°□°）╯︵ ┻━┻  $
```

My brew is up-to-date and reports only a warning about `/usr/local/lib/libecomlodr.dylib` which the corporate AV suite has installed. I'm on a MBP with OS X 10.10.3, Xcode and the command line tools are up-to-date.

`brew gist-logs csshx` reports no logs.

My brew does have perl installed locally, but as keg-only. I assume this is the Perl that csshx is building against, but I'm not sure. I have reinstalled brew's perl and reinstalled csshx, but nothing changed. I have not tried uninstalling the homebrew'd Perl, as it is probably a dependency of something else I installed.

Any ideas?

**Comment by DomT4** [comment]
> My brew does have perl installed locally, but as keg-only. I assume this is the Perl that csshx is building against, but I'm not sure. 

We build against the system Perl for consistency, and because there's no reason not to use the system Perl. Homebrewed Perl exists for people who want/need something newer for modules/testing/use/etc, but we don't use it internally.

**Comment by kevwil** [comment]
I uninstalled the brew'd Perl and reinstalled csshX, and nothing changed. Perhaps there is an issue with my system Perl? I don't {use/code in} Perl so I'd be at a loss to troubleshoot or fix the system Perl. :(

**Comment by jeffjo** [comment]
Are you running tmux? I am encountering the same exact issue, but only when I run csshx under tmux.

**Comment by kevwil** [comment]
I have tmux running, but in a different tab; I'm launching csshx from a normal iTerm2 tab.

I just tried shutting down tmux altogether and then launching csshx from a stand-alone iTerm2 instance, and csshx worked just fine. I think we're on to something with csshx vs tmux.

**Comment by DomT4** [comment]
Looks like a known issue upstream, although upstream isn't particularly active: https://github.com/brockgr/csshx/issues/61

**Comment by DomT4** [comment]
Closing this one out.

It looks like a very known issue upstream that hasn't been fixed. Please feel free to nudge upstream on this and if they commit a fix we're happy to review adding that to the formula. In the mean time the best advice we can give is to not run `tmux` at the same time as `csshx`.
