### ISSUE TITLE
OSQuery: Support HomeBrew Services

### ISSUE THREAD

**Issue by simonweil** [Homebrew/homebrew#42544]
OSQuery can't be controlled via homebrew-services sub-command.
See: Homebrew/homebrew-services#7

**Comment by dunn** [comment]
If this is something that can be fixed in the formula, we'd love a pull request! https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

**Comment by DomT4** [comment]
The `osquery` formula doesn't supply a `plist`, hence the inability to load/unload that via launchctl. If you wanted to open a PR to add one, we'd certainly be interested in reviewing that. You can find an example [here](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/beanstalk.rb#L17-L45).
