### ISSUE TITLE
cvsps hash error

### ISSUE THREAD

**Issue by jeffallen** [Homebrew/homebrew#42551]
$ sudo brew install cvsps
==> Downloading http://www.catb.org/~esr/cvsps/cvsps-3.13.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 5f078a6e02c394f663893751f128caf643fe00a30b559e87db6f45190c623799
Actual: a3ef1ce4df88d829b96271e7d2d5d30e82867ba113c3eb4f40148aff95d08c04
Archive: /Library/Caches/Homebrew/cvsps-3.13.tar.gz
To retry an incomplete download, remove the file above.

Seems like esr might have replaced the tar.gz? I guess we need to check with him.

**Comment by bfontaine** [comment]
I can’t reproduce:

```
$ curl -sL http://www.catb.org/~esr/cvsps/cvsps-3.13.tar.gz | shasum -a 256
5f078a6e02c394f663893751f128caf643fe00a30b559e87db6f45190c623799  -
```

**Comment by jeffallen** [comment]
Excuse me, it is apparently a problem with a not-so-transparent proxy at my
employer. The file is being silently ungzipped in transit!

$ openssl sha256 cvsps-3.13.tar.gz

SHA256(cvsps-3.13.tar.gz)=
a3ef1ce4df88d829b96271e7d2d5d30e82867ba113c3eb4f40148aff95d08c04

$ file cvsps-3.13.tar.gz

cvsps-3.13.tar.gz: POSIX tar archive (GNU)
