### ISSUE TITLE
Mailing list not working?

### ISSUE THREAD

**Issue by bf4** [Homebrew/homebrew#42552]
# Mailing list not working?

Per https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/README.md#community-forums
I sent an email to `homebrew@librelist.com` but I haven't yet seen it show up in http://librelist.com/browser/homebrew/. I asked about this on
[freenode.net#machomebrew](ircs://irc.freenode.net:6697/#machomebrew) and tdsmith said there might be some delay, but it's been about 22 hours now...

Maybe create a new list like on http://n5.nabble.com/free-forum.html ? (ugh, google groups).

(Update: In reading [the docs more carefully](http://librelist.com/), I see I should have expected a confirmation email more or less immediately after my first.  I found it in my spam and just replied. And the reply said my first email was dropped and I should resend it. Weird system.)

My question was OT for the issues queue, but I'll post it here as long as I'm writing:

## Thoughts about 'Nix' vs. Homebrew?

I haven't used it myself or looked too deeply. I'm not really sure what to make of it.

- https://github.com/NixOS/nix
- https://blog.errright.com/switching-from-homebrew-to-nix/

> Nix also supports creating isolated development environments. 
> Nix --rollback and --switch-generation functions provide the additional stability. Each package installation creates a new generation of your Nix environment. This means that if a download breaks a build you simply rollback to the last previous working generation.
> The nix-shell is used to provide isolated environments.
> If an install wrecks your development environment, you can simply rollback to the previous working one.
> Garbage collection function allows you to quickly clean up your environment once you have carried out a number of changes

Thoughts?

**Comment by chdiza** [comment]
FWIW, I've tried to post to the mailing list on three or four separate occasions since January 2013 and have never once seen a confirmation message (whether in my junk trap or not) or seen my message go through, or anything of the sort.

I finally gave up.

**Comment by tdsmith** [comment]
I've been meaning to set up a google group. It sounds like things are working as well as they ever have so I'll close this for now.
