### ISSUE TITLE
brew update error

### ISSUE THREAD

**Issue by uroborus** [Homebrew/homebrew#42561]
brew update
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

/usr/local/Library/Homebrew/formulary.rb:214:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:174:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:204:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:125:in `<main>'

**Comment by dunn** [comment]
Try running `brew update` again. If that doesn't help see #42553.
