### ISSUE TITLE
wine --devel (1.7.48) failed to build on OS X 10.7.5

### ISSUE THREAD

**Issue by angelXwind** [Homebrew/homebrew#42586]
Relevant output:

```
==> ./configure --prefix=/usr/local/Cellar/wine/1.7.48 --without-mpg123
==> make dlls/winemac.drv/Makefile
Error: inreplace failed
dlls/winemac.drv/Makefile:
  expected replacement of "-gstabs+" with ""
JazzuBook001:~ Karen$
```

`brew gist-logs wine` output: https://gist.github.com/3b818b6873667421d235

Also of note: Stable `wine` (1.6.2) builds fine via Homebrew on OS X 10.7.5.

Looking over [`wine.rb`](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/wine.rb), it seems to be failing on [line 143](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/wine.rb#L143).

I think the issue here might be that OS X 10.7.5's `gcc` doesn't just run `clang` in place of `gcc` —  which is what 10.10 (and I believe 10.9) does. (So perhaps 10.8 may also fail to build `wine --devel`?)

(I'm not experienced with Ruby at all, so I could also just be totally wrong)

`wine --devel` builds fine on my 10.10.4 machine, though I'm unsure if the same issue occurs on any other OS X versions.

**Comment by dunn** [comment]
Looks like that flag isn't used anymore.  Try `brew edit wine` and delete that line, then see what happens.

**Comment by DomT4** [comment]
Stable still requires it. Devel no longer generates that flag during the `configure` process and hence there's nothing to inreplace. Fixed in https://github.com/Homebrew/homebrew/commit/b45b37b9c27c52f62009e91929a586aa98e11230 (Tested on a 10.7.5 VM).
