### ISSUE TITLE
sshguard: is it working on Yosemite?

### ISSUE THREAD

**Issue by shiponi** [Homebrew/homebrew#42599]
running:
```
sudo pfctl -s info
```
shows that the service is disabled.

New IPs are added to the sshguard table (`sudo pfctl -t sshguard -T show`), but the rules are not enforced while the service is disabled.

**Comment by DomT4** [comment]
Seems to be working okay here at least. Did you follow all the set up instructions?

**Comment by shiponi** [comment]
No, I was referring to the pf itself. Does it run on your machine (check with `sudo pfctl -s info`)?
When you installed Yosemite, was it a clean installation or an upgrade?

**Comment by DomT4** [comment]
Is `pf` running? Yup. I'm not sure why yours wouldn't be running, Apple enforces it with a launch daemon in `/System/Library/LaunchDaemons`.

**Comment by shiponi** [comment]
do you mean `/System/Library/LaunchDaemons/com.apple.pfctl.plist`?

**Comment by DomT4** [comment]
That's the one.

**Comment by shiponi** [comment]
I don't think this one enables the pf, it just loads the rules.
It's running `pfctl -f /etc/pf.conf`. Apple uses pf for the application firewall (under system preferences/security).
The problem is, that the applicationf firewall can be on, and still the pf will be disabled. It depends on the specific settings.

here's its content:
```
<dict>
        <key>Disabled</key>
        <false/>
        <key>Label</key>
        <string>com.apple.pfctl</string>
        <key>WorkingDirectory</key>
        <string>/var/run</string>
        <key>Program</key>
        <string>/sbin/pfctl</string>
        <key>ProgramArguments</key>
        <array>
                <string>pfctl</string>
                <string>-f</string>
                <string>/etc/pf.conf</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
</dict>
```

**Comment by DomT4** [comment]
Huh. Yup, you're right. Maybe it isn't enabled by default on OS X, which is an interesting choice.

You can kick it to make it work by passing `sudo pfctl -e`. You could even write a `plist` to do that automatically for you at boot.

**Comment by the-real-tokai** [comment]
pfctl is not enabled/ running by default.

"socketfilterfw", the "Application Firewall" (System Settings stuff) is a different beast all together. It's located in /usr/libexec/ApplicationFirewall AFAIR.

**Comment by shiponi** [comment]
yeah, we need to pipe the rule into `pfctl -E`, keep the generated token, and use it when the sshguard service is disabled.

**Comment by DomT4** [comment]
We had a small discussion about this on the team chat the other night. I've been enabling `pfctl` by default for years and had forgotten entirely it's not the actual OS X default.

My temptation is to leave it to user's to handle as desired and just notify them in our `caveats` that `pfctl` isn't enabled by default and `sshguard` requires it to be.

**Comment by shiponi** [comment]
It's just not the way OS X uses pf internally. Apple added -E and -X to pfctl for reference counting, so the pf will disable itself automatically when not in use.

**Comment by DomT4** [comment]
I'm all ears to non-invasive suggestions.

**Comment by DomT4** [comment]
If anyone has a workable solution here that's not heavily invasive I'll welcome a PR to review.
