### ISSUE TITLE
When installing - Error: Permission denied - /Library/Caches/Homebrew/Formula

### ISSUE THREAD

**Issue by fbucek** [Homebrew/homebrew#42606]
When I follow web page brew.sh to install HomeBrew
1) Install HomeBrew: 
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
OK - working

2) Install wget
brew install wget
Error: Permission denied - /Library/Caches/Homebrew/Formula

I have to "fix" this using command found here ( found here in issues somewhere )
sudo chown -R $USER:admin $(brew --cache)

Another mention of this problem:
http://stackoverflow.com/questions/17610417/permission-denied-library-caches-homebrew-formula-nmap-brewing
Answer helped some people.

OS: OSX 10.10.5

**Comment by dunn** [comment]
Thanks for the report.  This is probably something we can check during installation.

**Comment by DomT4** [comment]
This issue was moved to Homebrew/install#21
