### ISSUE TITLE
Error (SHA256 mismatch) tcl-tk tcllib 1.17

### ISSUE THREAD

**Issue by alihabib-tp** [Homebrew/homebrew#42604]
It seems same as >>> https://github.com/Homebrew/homebrew/issues/40280

brew install git
==> Installing git dependency: homebrew/dupes/tcl-tk
==> Downloading https://downloads.sourceforge.net/project/tcl/Tcl/8.6.4/tcl8.6.4-src.tar.gz
Already downloaded: /home/ali/.cache/Homebrew/tcl-tk-8.6.4.tar.gz
==> Patching
patching file pkgs/sqlite3.8.8.3/generic/sqlite3.c
==> ./configure --prefix=/home/ali/.linuxbrew/Cellar/tcl-tk/8.6.4 --mandir=/home/ali/.linuxbrew/Cellar/tcl-tk/8.6.4/share/man --enable-64bit
==> make
==> make install
==> make install-private-headers
==> Downloading https://downloads.sourceforge.net/project/tcl/Tcl/8.6.4/tk8.6.4-src.tar.gz
Already downloaded: /home/ali/.cache/Homebrew/tcl-tk--tk-8.6.4.tar.gz
==> ./configure --prefix=/home/ali/.linuxbrew/Cellar/tcl-tk/8.6.4 --mandir=/home/ali/.linuxbrew/Cellar/tcl-tk/8.6.4/share/man --with-tcl=/home/ali/.linuxbrew/Cellar/tcl
==> make TK_LIBRARY=/home/ali/.linuxbrew/Cellar/tcl-tk/8.6.4/lib
==> make install
==> make install-private-headers
==> Downloading https://github.com/tcltk/tcllib/archive/tcllib_1_17.tar.gz
Already downloaded: /home/ali/.cache/Homebrew/tcl-tk--tcllib-1.17.tar.gz
Error: SHA256 mismatch
Expected: 45e5e2c5a60fc590c2c77b3a793846bbf62385a9706aa68dec16f60d236d164f
Actual: 1653165693125e86e8b77929c22210fb50a9b46271c321ac292cd5497cdde2d2
Archive: /home/ali/.cache/Homebrew/tcl-tk--tcllib-1.17.tar.gz
To retry an incomplete download, remove the file above.

**Comment by DomT4** [comment]
https://github.com/tcltk/tcllib/issues/5

**Comment by genovese** [comment]
I am having this same problem, though the Actual described above is now the
Expected and the Actual is new:

    Error: SHA256 mismatch
    Expected: 1653165693125e86e8b77929c22210fb50a9b46271c321ac292cd5497cdde2d2
    Actual: 95c676130ce2fdb00e8a6f79c4fea9e79d071063783a61db9274647920d97a03
    Archive: /Library/Caches/Homebrew/tcl-tk--tcllib-1.17.tar.gz
    To retry an incomplete download, remove the file above.

This arises in updating python3 --with-tcl-tk  for the dependency homebrew/dupes/tcl-tk.

Any suggestions on how to proceed would be appreciated.  Thanks.

**Comment by DomT4** [comment]
^ Will be fixed by https://github.com/Homebrew/homebrew-dupes/pull/512.
