### ISSUE TITLE
Reinstall packages bottled for an old OS version

### ISSUE THREAD

**Issue by mindrones** [Homebrew/homebrew#42611]
I recently upgraded Mac OS X to Yosemite and I'd like to make sure that each package I have currently installed is a Yosemite bottle.

It would be nice to have an option to reinstall bottles for the new OS version: maybe `brew reinstall --bottled`?

**Comment by DomT4** [comment]
Could always `brew list -1 | xargs brew reinstall`?

**Comment by mindrones** [comment]
Thanks, what would happen to the ones I've built with specific options?

**Comment by DomT4** [comment]
`brew reinstall` preserves options, so anything you've built from source say `--with-brewed-curl` for example from the `git` formula will be reinstalled from source with that flag again. Anything built vanilla will be fetched and poured from bottles.

**Comment by mindrones** [comment]
Ah nice to know! Then a minor enhancement would be `brew reinstall --all`, otherwise thanks a lot, you can close this one :)

**Comment by DomT4** [comment]
Aye, It's something we could support fairly easily. I'll tag this as `features` and let the other maintainers comment as to whether it's something they'd be interested in supporting.

**Comment by mindrones** [comment]
OK thanks!

BTW, would it also reinstall pinned packages? I read from `man brew` that pinning prevents from upgrading but I'm not sure about reinstalling.

**Comment by DomT4** [comment]
`reinstall` will ignore the pinned variable.

**Comment by mindrones** [comment]
After a bit of thinking, I'll leave a note for the discussion.
It would be nice to have:

- `brew reinstall --all`: reinstall all;
- `brew reinstall --bottles`: reinstall all bottles and avoid recompiling those with own options, for example because compiling some packages on slow machines can take forever and you might not want to take 100% of the CPU for a long time;
- (eventually) `brew reinstall --no-bottles`: those compiled from source

**Comment by mikemcquaid** [comment]
Passing on this feature request. We'd accept a pull request in future.
