### ISSUE TITLE
curl: (6) Could not resolve host: github.com

### ISSUE THREAD

**Issue by misterzik** [Homebrew/homebrew#42631]
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Please help me! I recently purchased a new mac, and Brew it's not working on this new machine. It's just out of the box. Running Yosemite. 

I get the following error;

    curl: (6) Could not resolve host: github.com

Best Regards,
mZ

**Comment by DomT4** [comment]
Usually is a temporary network error, either locally or with Github. Does it reproduce?

**Comment by misterzik** [comment]
@domT4 how can I by pass this? After I get error terminal goes back to typing mode without taking any actions.

**Comment by DomT4** [comment]
If you run the command again in the Terminal does the issue happen again?

**Comment by misterzik** [comment]
@DomT4 yes it does.

**Comment by misterzik** [comment]
Good afternoon, @DomT4 after making many attempts with sudo and without sudo permission i still got to the same point. 

I had to directly connect to the ethernet cable and it worked, perhaps there is some restriction on my internet provider or router. 

Please homebrew allow other ways to install your beautiful piece of software in the near future, to avoid small problems like this.

**Comment by DomT4** [comment]
Hmm, that is a little unusual. The connection is over port 443, which should be open in pretty much all environments.

Note that you don't need to use our script to install Homebrew - It will do things like setup the Cache permissions and such for you, but you can use [any of these methods](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Installation.md#untar-anywhere) as well.

Let us know if you hit any further trouble!

**Comment by regardsrajesh** [comment]
adding the proxy settings (http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY) solved this issue...

**Comment by emmanuelstroem** [comment]
also try adding ALL_PROXY=https://proxyhost:port in either .gitconfig and/or in your .baschrc or .zshrc files in home directory.
