### ISSUE TITLE
gnuplot does not honour --without-qt

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew#42652]
gnuplot.rb handles the 'qt' option with this line: 
```
    args << "--with-qt" if build.with? "qt"
```

However, if I specify without-qt it won't do anything and it will autodetect the system qt package which I don't want to use (and brew shouldn't).  it probably should add 

The ```./configure``` syntax is
```
  --with-qt =qt4 =qt5 =no Qt terminal (default autodetect)
```

So maybe need this?

```
    args << "--with-qt" if build.with? "qt"
    args << "--with-qt=no" if build.without? "qt"
```

**Comment by mikemcquaid** [comment]
Sounds good :+1:. Could you submit a PR? Thanks!

**Comment by DomT4** [comment]
Small nit, should be something like:

```ruby
if build.with? "qt"
  args << "--with-qt"
else
  args << "--with-qt=no"
end
```
