### ISSUE TITLE
node failed to build on OS X 10.11

### ISSUE THREAD

**Issue by saada** [Homebrew/homebrew#42666]
```
$ brew install node
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Downloading https://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz
Already downloaded: /Library/Caches/Homebrew/node-0.12.7.tar.gz
==> ./configure --prefix=/usr/local/Cellar/node/0.12.7 --without-npm --without-ssl2 --without-ssl3
==> make install
#include <errno.h> /* needed on windows */
         ^
1 error generated.
make[1]: *** [/private/tmp/node20150808-15805-q337g/node-v0.12.7/out/Release/obj.target/cares/deps/cares/src/ares_fds.o] Error 1
make: *** [node] Error 2

READ THIS: https://git.io/brew-troubleshooting

Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
```

**Comment by DomT4** [comment]
Please provide a full `brew gist-logs node`, Thanks.

**Comment by saada** [comment]
I just found this thread 
https://github.com/Homebrew/homebrew/issues/40653
which led me to
https://github.com/DomT4/homebrew/commit/34e4b640747040b40649d848a59ffcd7ea117acc

I'll close this issue and will attempt to install XCode 7. I'll reopen/update this issue accordingly.
Thanks

**Comment by saada** [comment]
nope... the xcode beta installation didn't change a thing. same output as above

**Comment by saada** [comment]
Here's the gist
https://gist.github.com/anonymous/fbfe4b02f2494659bfee

**Comment by saada** [comment]
The output of the gist shows that homebrew is not detecting XCode 7... How do I fix that?

**Comment by mistydemeo** [comment]
`xcode-select -switch PATH_TO_YOUR_XCODE_7`

**Comment by saada** [comment]
@mistydemeo , the correct command was `sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer`. After doing so, the build is working again! Sweet! Maybe there should be a tutorial for this somewhere?
