### ISSUE TITLE
ircd-irc2 will not install after ircd-hybrid

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42673]
I installed `ircd-hybrid`, and then tried to install `ircd-irc2`. `ircd-irc2` failed with this error.

```
Error: Will not overwrite /usr/local/etc/ircd.conf
```

Removing `ircd-hybrid` did not fix it, as it left `/usr/local/etc/ircd.conf` in place. I suspect subsequent install attempts for `ircd-hybrid` would also fail because of the old file. But couldn't test it because of a download error for `ircd-hybrid`.

It looks like these formulae will also both install a `bin/ircd` program.

Should they be listed as conflicting with each other?

**Comment by mikemcquaid** [comment]
> Should they be listed as conflicting with each other?

Yeh, makes sense. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by apjanke** [comment]
PR opened: #42688

**Comment by DomT4** [comment]
Conflict was added at some point.
