### ISSUE TITLE
Installing with sandbox fails in (officially unsupported) installation via root.

### ISSUE THREAD

**Issue by the-real-tokai** [Homebrew/homebrew#42699]
For the fun of it I'm experimenting with a **Homebrew** installation done with the root user (via `sudo`; yes I know this is a BIG *no-no* officially :) ) and the new **sandbox** feature.

Besides that `tar` "messes up" ownership of many extracted files of source and bottle archives (tar keeps the user and group IDs of the archive when running via root) I noticed that the sandbox rules fail to properly set up access to root's temporary path which makes the installation fail (`sandboxd` reports via system.log: *deny file-write-create /private/var/tmp/sometemporaryfile*). I report this here, because I believe the respective setup in Homebrew perhaps could be adjusted to match the required criteria in a more general way.

By default the root's temporary path (`$TMPDIR`) is set to `/private/var/tmp` which is not in the default sandbox rules.

sandbox.rb currently has this:

    ...
    def allow_write_temp_and_cache
        allow_write_path "/private/tmp"
        allow_write "^/private/var/folders/[^/]+/[^/]+/[C,T]/", :type => :regex
        allow_write_path HOMEBREW_TEMP
        allow_write_path HOMEBREW_CACHE
    end
    ...

Also the second line with the regex allows write access to all user's private temporary paths. This perhaps should be limited to what `getconf DARWIN_USER_TEMP_DIR` returns, unless there are some concerns with this?

For the root case one can workaround it by switching `$TMPDIR` to a path that is allowed by Homebrew's sandbox rules:

`$ sudo TMPDIR=/private/tmp brew install --verbose --sandbox <formula>`

But besides this small caveats (the tar issue is a bit more annoying than the "tempdir" one ;) ) a Homebrew installation maintained via root works surprisingly well, especially with sandboxing it feels more secure than a manual `make install` of a package.

Perhaps the tar/ file permission issue could be adjusted too (a check for root user and add the extra parameters to tar to ignore user/ group bits of the archive)?

**Comment by xu-cheng** [comment]
> By default the root's temporary path ($TMPDIR) is set to /private/var/tmp which is not in the default sandbox rules.
>  This perhaps should be limited to what getconf DARWIN_USER_TEMP_DIR returns, unless there are some concerns with this?

Could you try and open a pull request? This [document](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should be helpful. Thanks!

> especially with sandboxing it feels more secure

Please be aware that currently sandbox is only used to detect file writing violation against Homebrew's policy. The formula loading itself is insecure.

**Comment by mikemcquaid** [comment]
I really don't understand the appeal of running an application that doesn't need root privileges and whose maintainers tell you not to run as root. Even with the sandbox: it's a bad idea.
