### ISSUE TITLE
Is it possible to install libxmlsec1 for architectures: arm64 and armv7?

### ISSUE THREAD

**Issue by Asich** [Homebrew/homebrew#42722]
brew options libxmlsec1
--without-gnutls
	Build without gnutls support
--without-openssl
	Build without openssl support

there is no '--universal' flag in brew options

**Comment by mistydemeo** [comment]
No, Homebrew builds software for Mac OS X; Homebrew doesn't support building any binaries for ARM. `--universal` in Homebrew means building a binary with both 32-bit and 64-bit architectures.
