### ISSUE TITLE
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by Neung07** [Homebrew/homebrew#42736]

**Comment by black-snow** [comment]
got this, too
brew doctor is fine

**Comment by bfontaine** [comment]
Closed as a duplicate of #42553.

**Comment by bfontaine** [comment]
@black-snow No, the error comes from the fact that `brew update` updates its own code. The error appears only on one `brew update`, after the second one it’s fine. We have fixed the issue since, so it shouldn’t appear anymore.
