### ISSUE TITLE
optionally install core components as part of android-sdk

### ISSUE THREAD

**Issue by eighthave** [Homebrew/homebrew#42748]
The `android-sdk` package installs the bare minimum of the Android SDK, then relies on the user to run the `android` tool to get the rest in order to get it to the point of being a functional Android SDK install.  The package should at least provide the option of installing a complete, functional Android SDK setup.  It can do so using the `--no-ui` mode of the `android` tool:

```ruby
    exec "echo yes | android -v update sdk --no-ui --force --filter platform-tools,build-tools-22.0.1"
```

The `--filter` names of all of the packages can be listed using:
```bash
android list sdk --no-ui --all --extended
```

**Comment by dunn** [comment]
Would you be interested in opening a pull request? Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions!

**Comment by eighthave** [comment]
Sorry, I'm only on OSX to package software for brew, macports, and fink these
days.  I don't do Android development on OSX, only GNU/Linux.  I just figured
out how to automatically install those bits, so I thought I'd document it here
in case someone wanted to improve the `android-sdk` package.

**Comment by DomT4** [comment]
If someone wants to pick this up we'll certainly review a PR, Thanks.
