### ISSUE TITLE
Consider add a formula for gqrx

### ISSUE THREAD

**Issue by jiegec** [Homebrew/homebrew#42744]
It's websites are https://github.com/csete/gqrx and http://gqrx.dk/.
There is already a support in macports: http://www.macports.org/ports.php?by=name&substr=gqrx
However I am a big fan of homebrew and I don't want to install any other package managers in OS X.

**Comment by xu-cheng** [comment]
Could you try and open a pull request? This [document](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should be helpful. Thanks!

**Comment by jiegec** [comment]
@xu-cheng Ok i will try to do this myself

**Comment by DomT4** [comment]
We'll consider a PR on this, Thanks!
