### ISSUE TITLE
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by fredssantos** [Homebrew/homebrew#42750]
While running
brew update
I get this error message
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Followed by
/usr/local/Library/Homebrew/formulary.rb:227:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:176:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:127:in `<main>'

Running brew update again worked and updated homebrew from 5d4f21fe to 7d06dc66

Environment:
OS X 10.10.4

**Comment by dunn** [comment]
Running `brew update` again should fix it! See #42553.
