### ISSUE TITLE
Python modules as resources is good?

### ISSUE THREAD

**Issue by jiegec** [Homebrew/homebrew#42776]
I saw many appearances like this:
resource "lxml" do
    url "https://pypi.python.org/packages/source/l/lxml/lxml-2.0.tar.gz"
    sha256 "062e6dbebcbe738eaa6e6298fe38b1ddf355dbe67a9f76c67a79fcef67468c5b"
  end
I think if we want to obey DRY, why are these python modules appeared in every formula needed? They may have different versions, and may not update on time.

**Comment by jiegec** [comment]
And, what's the difference between python packages in homebrew or in homebrew/python?

**Comment by DomT4** [comment]
> I think if we want to obey DRY

We have no particular zeal for DRY. As much as developers can choose to follow DRY, with the Python handling we try to follow DMUUS - *Don't Mess Up User's Systems* :wink:. How practical it would be to enforce DRY on a package manager is another debate.

Vendoring resources allows us complete control over the build, what dependencies are dragged in, where they are placed, etc. It also means we don't have Homebrew overwrite libraries/modules that may have been installed by the user as a standard practice. It also means you can't accidentally remove said libraries with `pip` and break your installed formula.

> difference between python packages in homebrew or in homebrew/python?

A couple of the bigger ones:

* Homebrew/Homebrew does not permit Python libraries as formula, Homebrew/Python does. 

* Homebrew/Python will typically use the first Python it stumbles across in your `$PATH`, Homebrew/Homebrew has fairly strict rules about *not* doing that.
