### ISSUE TITLE
Should Docker Toolbox be a homebrew formula or a Cask install?

### ISSUE THREAD

**Issue by cclauss** [Homebrew/homebrew#42793]
https://github.com/docker/toolbox

**Comment by mikemcquaid** [comment]
A cask or neither.

**Comment by sirkkalap** [comment]
http://blog.ranjandas.me/installing-docker-on-osx-docker-machine/ describes the manual installation of Docker Machine. I assume anyone with homebrew fu could turn it into a recipe.

**Comment by cclauss** [comment]
`brew cask install dockertoolbox` works... https://github.com/caskroom/homebrew-cask/blob/master/Casks/dockertoolbox.rb
