### ISSUE TITLE
MacVim python version mixup

### ISSUE THREAD

**Issue by nilsbecker** [Homebrew/homebrew#42804]
This seems to be a recurring theme -- I found a few similar closed bug reports  e.g. #26496  but I am still seeing the problem. OS X 10.10.

`brew remove python macvim; brew install macvim --HEAD -v > macvimlog; brew install python`

Now I can start mvim but UltiSnips complains that it can't import its python module. Also, I have both homebrew installed python and Anaconda python on my system; Anaconda is first on the path.

Inside vim, when i do `:py import sys; print(sys.version)` I get the system python 2.7.6. However, the standard module path seems to be the one for Anaconda python 2.7.10, which seems messed up: `:py import os; print(os.__file__)` gives the Anaconda path in my home dir.

Finally, the install log says this:
```
checking Python's install prefix... /Users/nbecker/Apps/anaconda
checking Python's execution prefix... /Users/nbecker/Apps/anaconda
checking Python's configuration directory... /Users/nbecker/Apps/anaconda/lib/python2.7/config
```

but also this:

```
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UN
IX  -I/Users/nbecker/Apps/anaconda/include/python2.7 -I/Users/nbecker/Apps/anaconda/include/python2.7
 -fno-strict-aliasing -I/Users/nbecker/Apps/anaconda/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-p
rototypes -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/System/Library/Frameworks/Tcl.fra
mework/Headers  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_DARWIN_C_SOURCE=1   version.c -o objects/version
.o
 env LD_RUN_PATH=/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE clang   -L. -L/usr/local/l
ib -L. -L/usr/local/lib -lpython2.7 -ldl -framework CoreFoundation -u _PyMac_Error -L/usr/local/lib
       -o Vim objects/buffer.o objects/blowfish.o objects/charset.o objects/crypt.o objects/crypt_zip.o objects/diff.o objects/digraph.o objects/edit.o objects/eval.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/fileio.o objects/fold.o objects/getchar.o objects/hardcopy.o objects/hashtab.o  objects/if_cscope.o objects/if_xcmdsrv.o objects/mark.o objects/memline.o objects/menu.o objects/message.o objects/misc1.o objects/misc2.o objects/move.o objects/mbyte.o objects/normal.o objects/ops.o objects/option.o objects/os_unix.o objects/pathdef.o objects/popupmnu.o objects/quickfix.o objects/regexp.o objects/screen.o objects/search.o objects/sha256.o objects/spell.o objects/syntax.o  objects/tag.o objects/term.o objects/ui.o objects/undo.o objects/version.o objects/window.o objects/gui.o objects/gui_beval.o objects/pty.o objects/gui_macvim.o objects/MMBackend.o objects/MacVim.o   objects/if_perl.o objects/if_perlsfio.o objects/if_python.o  objects/if_tcl.o objects/if_ruby.o objects/os_macosx.o objects/os_mac_conv.o  objects/netbeans.o  objects/main.o objects/memfile.o -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python  -F/System/Library/Frameworks -framework Tcl -lpthread -framework CoreFoundation -framework Ruby
```

which contains -framework Python close to the end -- this seems odd?

**Comment by nilsbecker** [comment]
the install log is here: https://gist.github.com/05d14b121e327dbe6c03.git

**Comment by nilsbecker** [comment]
I've also tried uninstalling and reinstalling the ultisnips plugin; and removing all .pyc files recursively from ~/.vim.

**Comment by DomT4** [comment]
> the install log is here

This is 404.

> Finally, the install log says this:

Is the Python in `/Users/nbecker/Apps/anaconda` the first Python in your `$PATH`?

**Comment by nilsbecker** [comment]
is this working for you? https://gist.github.com/nilsbecker/05d14b121e327dbe6c03#file-macvimlog

yes, anaconda is the first in the path.

**Comment by tdsmith** [comment]
You must use a framework build of Python to build macvim. Anaconda may not be a framework build. Anaconda is poorly supported because it includes conflicting versions of several libraries that Homebrew provides, so I recommend that you don't use it with Homebrew.

**Comment by nilsbecker** [comment]
ok, so how do i do this? do i unset the PATH to not contain anaconda, before `brew install macvim`? can i then re-set it to my usual default and use the so-compiled macvim?

**Comment by tdsmith** [comment]
Yes, that should work.

**Comment by DomT4** [comment]
@tdsmith Could we use superenv to remove `anaconda` from the `$PATH` in these situations?

**Comment by tdsmith** [comment]
I'd rather add a doctor check than make --with-python more mysterious. MacVim should probably have a framework python Requirement.

**Comment by DomT4** [comment]
Like [this](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/wxpython.rb#L1-L12)?

**Comment by nilsbecker** [comment]
ok, it worked, thanks. for what it's worth, i would appreciate a more verbose error message, something like, 'the python executable on the path during installation must be from a framework build -- either the system python or homebrew-installed python'  or something like that.

**Comment by duozmo** [comment]
I hit the same issue today (accidentally trying to build with Anaconda’s Python instead of a brewed Python). Strangely, the `FrameworkPythonRequirement` that was added to `macvim.rb` in 34e9388b602faf13d149bf2d3b4b56ce07481f5f didn’t kick in for me. Evaluating the [`satisfy` block](https://github.com/Homebrew/homebrew/blob/34e9388b602faf13d149bf2d3b4b56ce07481f5f/Library/Formula/macvim.rb#L5-L6) manually in `irb` shows correct behavior, but I was not warned of the issue during upgrade. I tried to hook a debugger into the `macvim` formula to understand what was happening, but was unable to get that set up in the time I gave myself.

**Comment by DomT4** [comment]
Yes, I noticed the Requirement wasn't objecting to Anaconda either when I tested a couple weeks back. Not really sure on the root cause there.

We now have a broad `brew doctor` warning about Anaconda because it does trash so many builds, essentially if people see build problems, try removing it from the `$PATH` temporarily and running the install again.
