### ISSUE TITLE
http for bottles

### ISSUE THREAD

**Issue by hvisage** [Homebrew/homebrew#42809]
Hi there,

"Downloading https://homebrew.bintray.com/bottles/..."
Is there a way to get these from an http:// URL so that I can have them cached for my LAN? 
Else they are all downloaded time and time for each machine, instead of cached and downloaded for the first and then the rest can update/fetch it from my proxy cache much faster.

**Comment by DomT4** [comment]
You can and are welcome to mirror whatever bottles you want to a plaintext location and then set `HOMEBREW_BOTTLE_DOMAIN`.

Bintray does support plaintext downloads by replacing the `https` with `http`, which you may be able to achieve by setting the bottle domain to the plaintext link. Note the obvious implication that is less secure and we don't formally support such a choice. My personal choice would be for Bintray to not support that option given the dangers of shipping pre-compiled software over insecure routes.
