### ISSUE TITLE
update failure

### ISSUE THREAD

**Issue by tzing** [Homebrew/homebrew#42807]
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
/usr/local/Library/Homebrew/formulary.rb:227:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:176:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:127:in `<main>'

**Comment by DomT4** [comment]
See #42553. `brew update` again and it won't reproduce.
