### ISSUE TITLE
Bug - Brew Update

### ISSUE THREAD

**Issue by johnmlhll** [Homebrew/homebrew#42818]
A bug was returned after I tried to update brew. Return message was as follows:

Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:227:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:176:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:127:in `<main>'

**Comment by DomT4** [comment]
See #40837. `brew update` again and it won't reproduce.

**Comment by johnmlhll** [comment]
Roger that Dom! I did brew update and it didnt reproduce either. I updated brew second time round. I would close the ticket bro!!...
