### ISSUE TITLE
Prune dead gemstubs

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Homebrew/homebrew#42820]
So, this may be an unwelcome feature; feel free to close-on-sight if so, but,

Rubygems doesn't *symlink* `/usr/local/bin` entries to the gem's installation-dir; instead, it installs a small Ruby script that finds (and runs) the relevant gem. After `brew uninstall --force ruby`, a user might find a plethora of such stubs installed by a now-absent `gem`, linking to software that no longer exists:

    /usr/local/bin/pry: bad interpreter: /usr/local/Cellar/ruby/2.1.2_2/bin/ruby: no such file or directory

This is almost precisely why `brew prune` exists. I think it'd be useful to users to either by default, or under a flag, enable `brew prune` to recognize Rubygem stubs as a special-case, and remove them as if they were symlinks, as long as the referenced file doesn't actually exist.

**Comment by mikemcquaid** [comment]
Yeh, this is a good idea. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by ELLIOTTCABLE** [comment]
@mikemcquaid I'll put it in my to-do queue! Won't be anytime soon, though.

Postscript: Great response. <3

**Comment by DomT4** [comment]
We'll happily review a PR on this, Thanks!
