### ISSUE TITLE
Just a typo...

### ISSUE THREAD

**Issue by DiegoMax** [Homebrew/homebrew#42821]
Just reporting a small typo, "formulae" instead of "formulas".

https://www.dropbox.com/s/a7r4fmx23yqsqf9/Screenshot%202015-08-11%2017.01.24.jpg?dl=0

Cheers.

**Comment by DomT4** [comment]
`Formulae` is a valid plural of `formula` as well. We prefer the former over `formulas`.

**Comment by DiegoMax** [comment]
Wow, you learn something new every day.... sorry about it :+1:

**Comment by DomT4** [comment]
No worries! We've had similar questions before. It seems to be pretty much a matter of preference rather than anything deeper.
