### ISSUE TITLE
ZNC formula: issue with C++11

### ISSUE THREAD

**Issue by DarthGandalf** [Homebrew/homebrew#42822]
ZNC 1.6.0 requires compiler with C++11 support.
Because of that https://github.com/Homebrew/homebrew/blob/33aa9a09051c1260169f2de4e23834d68478ede3/Library/Formula/znc.rb#L31 explicitly adds `-std=c++11` to `CXXFLAGS`.
`./configure` thinks that no additional flag is needed for C++11, and as a result, `znc-buildmod` on the target system is broken.

See znc/znc#1023

Is there any side-effect, if to just remove `ENV.cxx11` from the formula?

**Comment by mikemcquaid** [comment]
> Is there any side-effect, if to just remove ENV.cxx11 from the formula?

You can try. Could you try and open a pull request? It'll build automatically and you can see if it works. This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by mistydemeo** [comment]
>     Is there any side-effect, if to just remove ENV.cxx11 from the formula?

Yes - we added it in #36811 because it wouldn't build without it.

**Comment by DarthGandalf** [comment]
@mikemcquaid thanks for the link

@mistydemeo do I need a new PR with your solution, or you'll do it?
Thanks for help.

**Comment by mistydemeo** [comment]
Should be fixed now - thanks for the report!
