### ISSUE TITLE
tika: Formula requires Java 1.7, but 1.8 is also supported

### ISSUE THREAD

**Issue by amarshall** [Homebrew/homebrew#42838]
This was changed in 886e01d2efc2f94536820b72bd15ec36dad3eaad, but from [Tika’s docs](https://tika.apache.org/1.10/gettingstarted.html) (emphasis my own):

> Note that you need Java **7 or _higher_** to build Tika.

The aforementioned change causes installing Tika to erroneously fail with

> Error: An unsatisfied requirement failed this build.

despite the fact that I have Java 8 installed and Tika is compatible with it.

I’m not sure what the right way to specify this in the formula is, and I assume the change was made to cause installations where no Java is present or only Java <=6 is present.

**Comment by dunn** [comment]
Changing it to `depends_on :java => "1.7+"` should do the trick.  If you want to open a pull request, we'd be very grateful!  Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have any questions.
