### ISSUE TITLE
Brew update error stashing local changes

### ISSUE THREAD

**Issue by gojira** [Homebrew/homebrew#42832]
When I try to run brew update, git fails when trying to stash some local changes to boost python.

The current error output is this:

Stashing your changes:
UU Library/Formula/boost-python.rb
M  Library/Formula/boost.rb
Library/Formula/boost-python.rb: needs merge
Library/Formula/boost-python.rb: needs merge
Library/Formula/boost-python.rb: unmerged (a8a8f42662cc139d215396a908318e21f60eb04f)
Library/Formula/boost-python.rb: unmerged (d3610e6ea89642b0a5ff60a1d703ad37edf9cb02)
Library/Formula/boost-python.rb: unmerged (b95ddc00ca404c12bb0479948d6873221ba9a09e)
fatal: git-write-tree: error building trees
Cannot save the current index state
Error: Failure while executing: git stash save --include-untracked --quiet

My brew config and brew doctor output (both stdout & stderr) are in this gist: https://gist.github.com/gojira/4ece05518f5d59a71fe7

My setup includes the folllowing.
1. Anaconda python distribution
2. Caffe/CUDA/CUDNN which required changes to boost formula

Thank you.

**Comment by DomT4** [comment]
`git fetch && git reset --hard origin/master` will sort you out. Note: Will overwrite whatever changes you've made to those formulae.

Someone with the same problem as you opened an issue the other day and to repeat what I said there if you need customised formula your best bet is to host your own custom tap and support the changes there.

Writing changes to Homebrew formulae is a fairly solid way to ensure you run into merge problems or update problems at some point, as well as potentially discovering problems when you try to compile other Homebrew formulae against that customisation.

**Comment by gojira** [comment]
OK, that worked once I figured out to run it in /usr/local/Library.

Thanks
