### ISSUE TITLE
Chromium CLI (again)

### ISSUE THREAD

**Issue by dardo82** [Homebrew/homebrew#42848]
I've made a mistake in patching the formula for chrome-cli to add support for Chromium to the command.
(See PR https://github.com/Homebrew/homebrew/pull/42731) I am going to submit a new PR to fix it, ok?

**Comment by mikemcquaid** [comment]
Yeh, you don't need to create an issue before the PR in future though, thanks!

**Comment by dardo82** [comment]
Understood, didn't knew that... I will add it to my github experience... :-)
