### ISSUE TITLE
Adding Swift to the Compiler Version Database

### ISSUE THREAD

**Issue by beltex** [Homebrew/homebrew#42864]
First off, forgot to say this before. Thank you Homebrew team for such a great project! :)

I was wondering what you thought about adding Swift to the [Compiler Version Database](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Xcode.md#compiler-version-database) in the Xcode document file. If yes, I’d be happy to submit a pull request.

Sincerely,

beltex

**Comment by denji** [comment]
Why in this case there is no Objective-C/C++ ?

Actually Swift is not a compiler, it's a front-end for the LLVM.

**Comment by beltex** [comment]
Hi @denji!

> Why in this case there is no Objective-C/C++ ?

[Clang](http://clang.llvm.org) is listed in the table, which is a C, C++, Objective-C and Objective C++ front-end for LLVM. Thus I thought it be appropriate to add Swift as well, which is also a front-end for LLVM as you mentioned. In addition, because it comes bundled with Xcode as with the rest of the compilers listed in the document.

My understanding as to the purpose of the document is as a reference for which version of Xcode to assert (depend on) in a formula, if the project in question requires a compiler that Xcode will be providing. So for example, knowing that Xcode 6.4 comes with the Swift 1.2 compiler, while Xcode 7 has Swift 2.0 (which has breaking language changes).

**Comment by mikemcquaid** [comment]
I don't see the use-case for now as we don't have any support for Homebrew to depend on a particular version of Swift currently. We'd accept a PR for that if you also changed a couple of Swift formulae to make use of it, too. Thanks!

**Comment by beltex** [comment]
Hi @mikemcquaid!

Sorry about the late response!

> I don't see the use-case for now as we don't have any support for Homebrew to depend on a particular version of Swift currently.

Currently this is done indirectly by depending on Xcode version. Some example formulae:

- [Carthage](https://github.com/Homebrew/homebrew/blob/a5fc72d4e97ef507e6374b1fa7c71cc2653ff3f3/Library/Formula/carthage.rb)
- [SourceKitten](https://github.com/Homebrew/homebrew/blob/1777fc04b5afbc1ed309361c1324cfe62ce32f62/Library/Formula/sourcekitten.rb)
- [SwiftLint](https://github.com/Homebrew/homebrew/blob/1777fc04b5afbc1ed309361c1324cfe62ce32f62/Library/Formula/swiftlint.rb)

These are all tools written in Swift and require version 1.2 of the compiler (which Xcode version 6.3 comes with - and thus they all use `depends_on :xcode => ["6.3", :build]`) which has breaking changes. So that was my thinking for making the suggestion.

> We'd accept a PR for that if you also changed a couple of Swift formulae to make use of it, too.

Cool!

I definitely agree that making it more explicit would be great, as in allowing formula to depend on Swift instead of Xcode, especially since it will be going open source later this year, and thus folks could have it independent of Xcode. Or even just for small things like `INSTALL_RECEIPT.json`, which currently will list Clang as it's compiler for a Swift based formula.

I'd love to work on that! :) So I'll take a look at it.

**Comment by mikemcquaid** [comment]
> These are all tools written in Swift and require version 1.2 of the compiler (which Xcode version 6.3 comes with - and thus they all use depends_on :xcode => ["6.3", :build]) which has breaking changes. So that was my thinking for making the suggestion.

Cool. I can see a `depends_on :swift => "2.0"` being useful.

> I definitely agree that making it more explicit would be great, as in allowing formula to depend on Swift instead of Xcode, especially since it will be going open source later this year, and thus folks could have it independent of Xcode. Or even just for small things like INSTALL_RECEIPT.json, which currently will list Clang as it's compiler for a Swift based formula.

That sounds cool. I would say that we probably won't merge anything there until Swift is actually a viable, buildable Formula as itself.

**Comment by beltex** [comment]
> I can see a depends_on :swift => "2.0" being useful.

Indeed!

> I would say that we probably won't merge anything there until Swift is actually a viable, buildable Formula as itself.

Sounds good!
