### ISSUE TITLE
clang error from Go compiler during installing 'docker' package

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Homebrew/homebrew#42867]
Details here: https://gist.github.com/anonymous/149546230a7a4d810f51

I'm not sure if it's related to using OS X El Capitan (10.11) beta.

I have Xcode 7 beta 5 installed in my system (although `brew doctor` still complains), but that did not help with the problem. Any ideas?

```
$ brew install docker
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Cloning https://github.com/docker/docker.git
Updating /Library/Caches/Homebrew/docker--git
==> Checking out tag v1.8.0
==> hack/make.sh dynbinary

---> Making bundle: dynbinary (in bundles/1.8.0/dynbinary)
Building: bundles/1.8.0/dynbinary/docker-1.8.0
# runtime/cgo
clang: error: no such sysroot directory: ''

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Fig / docker-compose fails with recent version https://github.com/Homebrew/homebrew/issues/41766
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
```

**Comment by mistydemeo** [comment]
You'll need to run `xcode-select -switch` to point to the beta Xcode app.

**Comment by ahmetalpbalkan** [comment]
@mistydemeo ah choosing the Xcode beta using that command worked. Pasting here as a reference for others in case if they hit the same issue:

    sudo xcode-select --switch /Applications/Xcode-beta.app/Contents/Developer
