### ISSUE TITLE
Install all packages from particular Tap.

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew#42875]
Two examples of lightweight taps that one may consider to install all packages: dupes and completions.

**Comment by xu-cheng** [comment]
You can use https://github.com/Homebrew/homebrew-bundle to custom your batch installations.

**Comment by yurikoles** [comment]
How can bundle track situations like addition/deletion of formulae? Ho needs to maintain this?
My proposal takes not more than a couple lines of code and works for any tap.

**Comment by xu-cheng** [comment]
I see what you need. But actually, you may also want the features to auto install new formula in that tap? So your proposal could take more than just a couple lines of code. I will defer this to other maintainers as well.

Beside this, you can write your own brew command to achieve it. https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/External-Commands.md

**Comment by tdsmith** [comment]
I don't see a strong use case for this feature and this is easy to do without modifying Homebrew so I don't think we should implement this. With jq, this looks like:

`brew tap-info --json=v1 homebrew/science | jq -r '.[0].formula_names | .[]' | xargs brew install`

**Comment by bfontaine** [comment]
You could also have issues like conflicting formulae in the same tap. In that case, which formula should you install?

**Comment by mikemcquaid** [comment]
This is not something we'll implement, sorry.
