### ISSUE TITLE
Error when 'brew update'

### ISSUE THREAD

**Issue by chriian** [Homebrew/homebrew#42901]
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:227:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:176:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:173:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:140:in `<main>'

Appeared on:
MacBookAir6,2
Intel Core i7 1,7 GHz
OS X 10.10.4

**Comment by bfontaine** [comment]
See #42553.
