### ISSUE TITLE
orientdb 2.1.0

### ISSUE THREAD

**Issue by uded** [Homebrew/homebrew#42918]
Available for a day or two

Download link: http://orientdb.com/download.php?email=unknown@unknown.com&file=orientdb-community-2.1.0.tar.gz&os=mac

**Comment by dunn** [comment]
We'd love a pull request! If you're interested, take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have any questions.

**Comment by uded** [comment]
Sure: #42923

The script is faulty, though. It doesn't move the data and log folders to common locations, therefore after every upgrade one will start from scratch and will need to migrate the DBs by hand. Should I fix that as well?

**Comment by dunn** [comment]
Probably, but sounds like something that should also be reported upstream.

**Comment by uded** [comment]
Now I do not follow. I can easily modify the files with a patch to set new configuration variables. What should be reported and where to?

**Comment by dunn** [comment]
Oh, I thought there was a Makefile that was installing things in the wrong location.  Update your PR with the modifications you think are necessary, and we'll take a look.  Thanks!
