### ISSUE TITLE
Question on Homebrew/Linuxbrew install script

### ISSUE THREAD

**Issue by CDLuminate** [Homebrew/homebrew#42929]
Hello Homebrew developers/maintainers,

Weeks ago I intended to package linuxbrew for Debian,
and after a discussion [1] with linuxbrew maintainer  (@sjackman )
I decided to provide these matter in the package:
 * a simple shell wrapper script (written by myself) of linuxbrew
 * the install script of Homebrew/Linuxbrew [2]  
  
Here I'd like to confirm some points with you the upstream:
 * Is the linuxbrew install script published under the same license with Linuxbrew? i.e. BSD-2-Clause
 * Could you please give it a version number ? currently I use the import date as it's version. i.e. 20150804
 * Is it convenient to setup a git repo to keep track on this install script [2] ? If so, it will be convenient
for me to maintain that wrapper package.
  
Looking forward to your comments :-)

[1] https://github.com/Homebrew/linuxbrew/issues/495
[2] https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install

**Comment by dunn** [comment]
The install scripts for Homebrew and Linuxbrew have diverged a bit; we used to use the `go` branch of our repo as well, but now we have a dedicated repository: https://github.com/Homebrew/install

I have no objection to doing the same for Linuxbrew, but other maintainers may want to weigh in.

**Comment by tdsmith** [comment]
I think these are questions for Shaun!

Also, I think we've never promised to keep changes to core backwards-compatible with an older version of the install script, though in practice they don't seem to be tightly coupled.

**Comment by mikemcquaid** [comment]
Yep, questions for Linuxbrew.

**Comment by sjackman** [comment]
> Is the linuxbrew install script published under the same license with Linuxbrew? i.e. BSD-2-Clause

Yes.

> Could you please give it a version number ? currently I use the import date as it's version. i.e. 20150804

That's a question for Homebrew/owners. Currently `Homebrew/install` has no tagged code releases. I would suggest that you continue to use the date.

> Is it convenient to setup a git repo to keep track on this install script [2] ? If so, it will be convenient for me to maintain that wrapper package.

The Linuxbrew install script git repository is currently here: https://github.com/Homebrew/linuxbrew/blob/go/install
I haven't merged it with upstream in some time. I'll do that and find a new home for it.
