### ISSUE TITLE
Having problems with brew after trying to use it to get my dev environment set up on my first Mac (Mac OS X Yosemite)

### ISSUE THREAD

**Issue by jacqueline-homan** [Homebrew/homebrew#42922]
Here's my situation: I've been having nothing but problems getting my dev environment set up correctly for the past week. It's my very first Mac (a refurb'd one with OS X Yosemite on it). I was having a TON of difficulty getting PHP, MySQL, Apache, and phpmyadmin installed and running correctly. And it's STILL not working for me after trying to install it using brew. After being completely stuck, a sr dev told me to just download and install MAMP. Well, that didn't work for me either. SO I wanted to use brew to uninstall the first failed MySQL, PHP, Apache and phpmyadmin setup and noticed that I got this weird error when I ran the brew update command before doing any uninstalling.  

`[~] ruby-2.2.1 $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have external commands with conflicting names.

Found command `brew-services` in following places:
  /usr/local/Library/Taps/gapple/homebrew-services/cmd/brew-services.rb
  /usr/local/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb`

I have been unable to work for over a week because I couldn't get my dev environment set up correctly and I have NOBODY to reach out to that wants to be bothered with taking the time to help a beginner. I am hoping someone here will PLEASE HELP!

**Comment by DomT4** [comment]
Hi Jacqueline, Thanks for opening the issue.

The `brew doctor` error you're seeing there can be fixed by doing:

```
brew untap gapple/services
```

Gapple moved the repository from Gapple/Homebrew-services to Homebrew/Homebrew-services but because Github automatically redirects the former still works.

What other issues can we help you with?

**Comment by dunn** [comment]
Was the `brew update` error the same as the one in #42553? If it is, it's nothing to worry about and will go away next time you update.

**Comment by jacqueline-homan** [comment]
No, I had a different error.

**Comment by jacqueline-homan** [comment]
All of this insanity started when I was struggling to get my dev environment set up. I'm relatively new to programming, struggling to teach myself and have NO support at all. I just landed my first gig but a Mac was required. I never had or used a Mac before. So I am really having a LOT of problems, and have been unable to work in over a week ever since the refurb'd Mac arrived because I can't get my dev environment set up. And this brew thing that other devs who have Macs told me about, well, this isn't working for me now after trying to get my Apache, MySQL, phpmyadmin and PHP stack set up in addition to my F# stuff. The ONE thing that gave me the least amount of difficulty was getting my Ruby on Rails thing set up (RVM). That's the ONLY thing that I was able to get so far and I don't know if that's messed up now because of all the other problems I've been having getting my other stuff that I need set up on the Mac or not.

**Comment by jacqueline-homan** [comment]
I ran that command you said to run and it STILL gives me that same error. It did NOT help.

**Comment by jacqueline-homan** [comment]
OK. UPDATE: Restarting the terminal and running that command you gave me DID work for fixng homebrew. Now if I could just find somewhere I could go for some help to get my dev environment set up and working, that'd be great.

**Comment by dunn** [comment]
We can certainly try to help you with installing Apache/MySQL/PHP using Homebrew.  I'm not sure at what stage of the process you're running into trouble, though.

**Comment by DomT4** [comment]
We've all been there in terms of new dev environments. Glad the command worked for you. Going to close this out as the specific issue has been resolved but happy to talk you through any further questions you have, as much as I can help.

StackOverflow is a decent place to [ask](https://stackoverflow.com/) for answers on specific issues as well. Lots of mini communities on there who will know the various environments.

Can you talk us through the specific issues you're seeing and how you went about setting those aspects up?

**Comment by jacqueline-homan** [comment]
That would be GREAT @DomT4 . How or where can I reach out to you for further help getting my dev environment set up? I do know that at some point in trying to get through the installation instructions for getting Apache, MySQL and PHP set up correctly, it messed something up where I now cannot run the command "locate" in my terminal. When I run the command "locate" I get an error: "locate: locate database header corrupt, bigram char outside 0, 32-127: -1" and I have NO clue how to fix that or what to do.

**Comment by DomT4** [comment]
The `locate` database is usually stored at `/var/db/locate.database` - It isn't generated by default so I presume something must have enabled that for you. You can safely remove it with:

```
rm -rf /var/db/locate.database
```

If you run `locate` after that are you able to?

**Comment by jacqueline-homan** [comment]
@DomT4 I forget wall the commands that I ran with help from a sr dev opps guy I reached out to, and zshell only goes back through the command history of the current session so I forgot which one of all the commands run finally did work and get it running again. But it is running again without any weird errors or notices.

**Comment by DomT4** [comment]
Great! Feel free to let us know if there's anything else we can help with. You may find the Homebrew [php tap](https://github.com/Homebrew/homebrew-php) useful for setting up that side of things.

**Comment by jacqueline-homan** [comment]
@DomT4 Well, I got MAMP installed, which works. But I am NOT thrilled with it. Very bloated. And Xamarin for Mac is not working correctly and I am unsure whether it's due to the possibility of my Mac OS being corrupt or if it's an Xamarin bug, so I am going to go bee-bop over to the Xamarin repo and hit those guys up unless if another F# already opened up an issue on it. But I am probably going to get a lot of strange looks because almost all the other F-sharpers dev on Windows whereas I'm coming from a Linux background.
