### ISSUE TITLE
Install LEF got Error when installing dependeny wxmac

### ISSUE THREAD

**Issue by guawoo** [Homebrew/homebrew#42925]
==> ./configure --prefix=/home/guawoo/.linuxbrew/Cellar/wxmac/3.0.2 --enable-unicode --enable-std_string --ena
checking for ar... ar
checking for architectures to use in universal binary... 
checking if C compiler (/usr/bin/gcc-4.9 -mmacosx-version-min=0) works with SDK/version options... configure: error: in `/tmp/wxmac20150814-96681-uy7369/wxWidgets-3.0.2':
configure: error: no.  Try a different SDK
See `config.log' for more details

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

**Comment by DomT4** [comment]
This issue was moved to Homebrew/linuxbrew#512
