### ISSUE TITLE
`brew update` should display some sort of progress indicator

### ISSUE THREAD

**Issue by behrangsa** [Homebrew/homebrew#42936]
Today I ran `brew update` and it took 7 minutes to complete and during this time, it didn't print any progress information:

```
22:11 $ brew update
Updated Homebrew from c5827a39 to c5827a39.
==> Updated Formulae
homebrew/dupes/nano	 homebrew/dupes/ncurses	  homebrew/dupes/openssh   homebrew/dupes/whois
✔ ~/Documents/Projects/foo [master ↑·1|✚ 3]
22:18 $
```
It would be nice if brew displayed some sort of progress indicator while it was updating itself.

**Comment by chdiza** [comment]
Do `export HOMEBREW_VERBOSE=1` in your `~/.profile`.

**Comment by behrangsa** [comment]
That's way too verbose. I was mainly looking for something like `[======         ]`.

**Comment by mikemcquaid** [comment]
We can't do that because Git doesn't provide us with that. If you can work something out: please submit a pull request and we'll review it. Sorry!
