### ISSUE TITLE
Errors migrating plt-racket to racket

### ISSUE THREAD

**Issue by tgt** [Homebrew/homebrew#42958]
I ran `brew upgrade` and homebrew told me to run `brew migrate plt-racket` to migrate it to its new name, racket. It failed to do so as `/usr/local/Cellar/racket/6.2.1 is not a directory`. I manually created this directory using `mkdir -p /usr/local/Cellar/racket/6.2.1` and the command now results in the error below:

```
==> Migrating plt-racket to racket
==> Unlinking plt-racket
Moving to: /usr/local/Cellar/racket
==> Linking racket
Error: error occured while migrating.
undefined method `atomic_write' for nil:NilClass
Backuping...
Error: undefined method `atomic_write' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/tab.rb:220:in `write'
/usr/local/Library/Homebrew/migrator.rb:310:in `each'
/usr/local/Library/Homebrew/migrator.rb:310:in `backup_old_tabs'
/usr/local/Library/Homebrew/migrator.rb:270:in `backup_oldname'
/usr/local/Library/Homebrew/migrator.rb:144:in `block in migrate'
/usr/local/Library/Homebrew/utils.rb:308:in `ignore_interrupts'
/usr/local/Library/Homebrew/migrator.rb:144:in `rescue in migrate'
/usr/local/Library/Homebrew/migrator.rb:129:in `migrate'
/usr/local/Library/Homebrew/cmd/migrate.rb:17:in `block in migrate'
/usr/local/Library/Homebrew/cmd/migrate.rb:8:in `each'
/usr/local/Library/Homebrew/cmd/migrate.rb:8:in `migrate'
/usr/local/Library/brew.rb:127:in `<main>'
```

**Comment by mikemcquaid** [comment]
CC @vladshablinsky

**Comment by vladshablinsky** [comment]
Will be solved in this PR. https://github.com/Homebrew/homebrew/pull/42857

**Comment by mikemcquaid** [comment]
Assuming now fixed. If not, let me know and I'll reopen.

**Comment by tgt** [comment]
After updating `brew migrate --debug plt-racket` resulted in the same error. I then removed `/usr/local/Cellar/racket/6.2.1` and tried again. This appeared to succeed, but `racket` did not become an available command. I ran `brew doctor` and it says that both `racket` and `plt-racket` are unlinked. Running `brew link racket` or `brew link plt-racket` outputs `Error: racket has multiple installed versions`

**Comment by vladshablinsky** [comment]
Thats because you could break thing when you created a directory manually. Homebrew suppose that every keg in the Cellar has its `INSTALL_RECEIPT` and other things, however, yours doesn't.

You can try `brew uninstall racket --force && brew install racket`

**Comment by tgt** [comment]
I deleted the directory I created, should that not have reset it to the state it would typically migrate from?

**Comment by vladshablinsky** [comment]
No, because `migrate` command creates other things and in your case

```
==> Migrating plt-racket to racket
==> Unlinking plt-racket
Moving to: /usr/local/Cellar/racket
==> Linking racket
Error: error occured while migrating.
undefined method `atomic_write' for nil:NilClass
Backuping...
Error: undefined method `atomic_write' for nil:NilClass
```

you can see that backup failed. It failed because the directory you created wasn't a keg, actually. It was empty, however Homebrew supposed it not to be empty, but be the keg with the stuff all kegs have.

**Comment by tgt** [comment]
Ah, I understand. Thank you for the explanation.
