### ISSUE TITLE
llvm formula's clang++ fails with -L $(brew --prefix llvm)/lib

### ISSUE THREAD

**Issue by jwatzman** [Homebrew/homebrew#42957]
On a system with clang from the llvm formula (`brew install llvm --with-clang`), consider the following code:

```c++
#include <stdexcept>

int main(void) {
  throw new std::length_error("blah");
  return 0;
}
```

When compiled as one normally would do:

```sh
$ $(brew --prefix llvm)/bin/clang++ test.cpp
$
```

everything is fine. However, when compiled like this, it fails:

```sh
$ $(brew --prefix llvm)/bin/clang++ test.cpp -L $(brew --prefix llvm)/lib
Undefined symbols for architecture x86_64:
  "typeinfo for std::length_error", referenced from:
      typeinfo for std::length_error* in test-aeb26f.o
  "vtable for std::length_error", referenced from:
      _main in test-aeb26f.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang-3.6: error: linker command failed with exit code 1 (use -v to see invocation)
$
```

The cause for this is, as far as I can tell, the `-L` option causing `ld` to find `libc++.dylib` in `$(brew --prefix llvm)/lib` instead of `/usr/lib`. I would expect this to work, even be the default, but it does not appear to work. I'm not sure what's wrong with `$(brew --prefix llvm)/lib/libc++.dylib`, but that's the root cause, I suspect?

This wouldn't normally be a huge deal -- that `-L` option is pretty weird and superfluous -- except that brew's superenv causes this to happen for any package that has a `depends_on "llvm" => "with-clang"` and uses that `clang` to build, since superenv injects its own `ld` wrapper which adds `-L` options for every keg-only formula such as `llvm`.

**Comment by mikemcquaid** [comment]
We don't support building in superenv using the LLVM formula's `clang`.

**Comment by jwatzman** [comment]
- Although I hit this due to superenv, since you can still repro it outside of superenv, I think it's still a problem with the `libc++.dylib` shipped with llvm+clang?
- If you don't support using LLVM's `clang` to build in superenv, should I use the standard env instead? The project I'm working on a formula for, HHVM, doesn't build otherwise -- OS X's clang doesn't have TLS support, and building with an upstream gcc (4.9 or something) causes ld to trip an assert for unclear reasons.
- Out of curiosity, why isn't building in superenv with LLVM's `clang` supported?

**Comment by mikemcquaid** [comment]
> Out of curiosity, why isn't building in superenv with LLVM's clang supported?

Basically: it's too easy to accidentally screw your compiler (or Homebrew to do so itself) and break Homebrew in interesting ways.

> The project I'm working on a formula for, HHVM, doesn't build with other compilers -- Apple's default clang doesn't have TLS support, and building with an upstream gcc (4.9 or something) causes ld to trip an assert for unclear reasons.

Just to save you effort if it doesn't build with Xcode's compilers we probably won't include it in Homebrew core.

**Comment by DomT4** [comment]
Closing per the above. It's an unsupported configuration, essentially.

If there's some workable solution available that doesn't break the rest of the LLVM formula we'll review a PR, but relying on Homebrew's LLVM `--with-clang` for build purposes is a fairly big no-no.

**Comment by jwatzman** [comment]
Although I found the problem due to superenv, it comes up even without it -- see the example in the initial post; that repros outside of superenv. I'm pretty sure something is wrong with the `libstdc++.dylib` that the llvm formula installs -- if you use it instead of Apple's, nothing works.

Can this be reopened, and maybe given a proper title not mentioning superenv?

**Comment by tdsmith** [comment]
We can reopen but someone will need to figure out, possibly by talking to the llvm devs, what needs to change and who's responsible for it.

**Comment by tdsmith** [comment]
— and I'm hoping "someone" is @jwatzman ;)

**Comment by DomT4** [comment]
I'd like this to be kept regularly updated on bug reports/progress/etc, as much as possible, Thanks. We reopen too many of these issues and then they sit around for 6 months whilst the problem remains.

**Comment by jwatzman** [comment]
I'll try to find a few minutes to look into it (or find a coworker who might know something :)) but I'm not going to have time to dig in extensively, sorry :\

**Comment by denji** [comment]
```
usage: llvm-config <OPTION>... [<COMPONENT>...]

Get various configuration information needed to compile programs which use
LLVM.  Typically called from 'configure' scripts.  Examples:
  llvm-config --cxxflags
  llvm-config --ldflags
  llvm-config --libs engine bcreader scalaropts

Options:
  --version         Print LLVM version.
  --prefix          Print the installation prefix.
  --src-root        Print the source root LLVM was built from.
  --obj-root        Print the object root used to build LLVM.
  --bindir          Directory containing LLVM executables.
  --includedir      Directory containing LLVM headers.
  --libdir          Directory containing LLVM libraries.
  --cppflags        C preprocessor flags for files that include LLVM headers.
  --cflags          C compiler flags for files that include LLVM headers.
  --cxxflags        C++ compiler flags for files that include LLVM headers.
  --ldflags         Print Linker flags.
  --system-libs     System Libraries needed to link against LLVM components.
  --libs            Libraries needed to link against LLVM components.
  --libnames        Bare library names for in-tree builds.
  --libfiles        Fully qualified library filenames for makefile depends.
  --components      List of all possible components.
  --targets-built   List of all targets currently built.
  --host-target     Target triple used to configure LLVM.
  --build-mode      Print build mode of LLVM tree (e.g. Debug or Release).
  --assertion-mode  Print assertion mode of LLVM tree (ON or OFF).
Typical components:
  all               All LLVM libraries (default).
  engine            Either a native JIT or a bitcode interpreter.
```

**Comment by RandomDSdevel** [comment]
@DomT4, you labeled this as being an upstream bug, but I don't see any references to LLVM's Bugzilla in here anywhere.  Does that mean that @jwatzman or one of his colleagues hasn't gotten around to looking at it yet, or did somebody just forget to add the reference(s)?

**Comment by jwatzman** [comment]
I haven't had a chance to look into it yet, not sure when I will, sorry. FWIW it's unclear if this is an upstream issue or an issue with the way that the llvm formula in brew builds or installs this library or something.

**Comment by RandomDSdevel** [comment]
Ack, have fun debugging that.

**Comment by mikemcquaid** [comment]
Closing this out but happy to reopen if @jwatzman is able to spend more time digging in here.

**Comment by jwatzman** [comment]
Yeah sorry, this isn't something I'm likely to get around to anytime soon.

**Comment by mikemcquaid** [comment]
@jwatzman That's completely OK and glad you agree with closing until then.
