### ISSUE TITLE
`brew cleanup --force -s` deletes all caches

### ISSUE THREAD

**Issue by cc941201** [Homebrew/homebrew#42967]
I ran `brew cleanup --force -s` today, and it deleted all cached downloads from my `/Library/Caches/Homebrew`. It is an undocumented change of behavior. Previously, only caches of deleted packages would be deleted.

I looked through commits from last few days, and the only commit related to cleanup is this one:
https://github.com/Homebrew/homebrew/commit/066bdb0d10533ed86e5d3580fe6ab4669d238a48

**Comment by xu-cheng** [comment]
066bdb0 has nothing to do with it. Related commit is 17eee232838d4639b25f863aa342b1dda61b81bc

**Comment by cc941201** [comment]
Well, that makes more sense.

**Comment by mikemcquaid** [comment]
`--force` deleted all cached downloads before this change. That's what the flag does.

**Comment by cc941201** [comment]
But according to the manual, `--force` deletes keg-only packages which is consistent with my experience before. This is the only time it deletes all caches.

**Comment by UniqMartin** [comment]
I have to second @cc941201's observation. The manual says otherwise and my experience is also that before the change, `--force` would *only* remove outdated keg-only packages while `--prune=<days>` would *only* affect removal of cached downloads.

**Comment by UniqMartin** [comment]
I hope I'm not stepping on anyone's toes, but I created PR #42970 in an attempt to make everyone happy.

**Comment by mikemcquaid** [comment]
> But according to the manual, --force deletes keg-only packages which is consistent with my experience before. This is the only time it deletes all caches.

According to the manual: I'm an idiot and apologise. Sorry for my misunderstanding here; #42970 is looking much better.

**Comment by UniqMartin** [comment]
The issue was addressed in 9ac7f8c7620d2ca3b9090530d46fbfe5badad6ec and slightly tweaked in subsequent commits. `brew update` and feel free to close this issue, if it works again as expected.
