### ISSUE TITLE
Fix ActiveMQ plist - related to #39477

### ISSUE THREAD

**Issue by moraygrieve** [Homebrew/homebrew#42964]
I believe the issues with ActiveMQ plist not starting the application is related to the fact that the activemq script starts a background daemon and then exists, so launchctl gets confused on what it's tracking - see http://stackoverflow.com/questions/18440575/mac-daemon-for-activemq. This suggests the below workaround which seems to work (caveat being I've done limited testing, but runs on loading, restart etc);
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>homebrew.mxcl.activemq</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <false/>
    <key>AbandonProcessGroup</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>/usr/local/Cellar/activemq/5.11.1/libexec</string>
    <key>ProgramArguments</key>
    <array>
      <string>/usr/local/opt/activemq/bin/activemq</string>
      <string>start</string>
    </array>
  </dict>
</plist>
```

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
