### ISSUE TITLE
Build OpenSSH with brewed Heimdal Kerberos

### ISSUE THREAD

**Issue by azag0** [Homebrew/homebrew#42966]
Apple's Heimdal Kerberos in Yosemite is built without support for weak encryption (DES), which makes it unusable on systems that do not support strong encryption such as OpenAFS or legacy infrastructures.

Even when Homebrew's Heimdal (with support for weak encryption) is installed, OpenSSH builds (with `--build-from-source`) with Apple's Kerberos framework, not the brewed Heimdal.

```bash
$ otool -L /usr/local/bin/ssh | grep -i kerberos
	/System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos (compatibility version 5.0.0, current version 6.0.0)
```

What would be the cleanest way to add support for building OpenSSH with the brewed Heimdal?

**Comment by tzudot** [comment]
```diff
diff --git a/openssh.rb b/openssh.rb
index ee98be4..9d9484c 100644
--- a/openssh.rb
+++ b/openssh.rb
@@ -19,6 +19,7 @@ class Openssh < Formula
   depends_on "openssl" => :recommended
   depends_on "libressl" => :optional
   depends_on "ldns" => :optional
+  depends_on "heimdal" => :optional
   depends_on "pkg-config" => :build if build.with? "ldns"

   patch do
@@ -38,11 +39,16 @@ class Openssh < Formula
     args = %W[
       --with-libedit
       --with-pam
-      --with-kerberos5
       --prefix=#{prefix}
       --sysconfdir=#{etc}/ssh
     ]

+    if build.with? "heimdal"
+      args << "--with-kerberos5=#{Formula["heimdal"].opt_prefix}"
+    else
+      args << "--with-kerberos5"
+    end
+
     if build.with? "libressl"
       args << "--with-ssl-dir=#{Formula["libressl"].opt_prefix}"
     else
```

**Comment by DomT4** [comment]
To be honest, I'm not a massive fan of enabling options that serve to reduce security for the sake of backwards compatibility. Backwards compatibility is why people kept SSLv2 and SSLv3 around for so long despite them being more achy breaky than a Billy Ray Cyrus cover song.

That said, If you submit a PR to [dupes](https://github.com/Homebrew/homebrew-dupes) with an explicit option that enablding `heimdal` enables weaker security we'll consider it. The above diff looks about right.
