### ISSUE TITLE
Brew doesn't build properly 

### ISSUE THREAD

**Issue by kamalbowselvam** [Homebrew/homebrew#42971]
Hi, 

I tried to do 'brew install python' in my macbook pro mavericks and I get this error 

==> /usr/local/Cellar/python/2.7.10_2/bin/python -s setup.py --no-user-cfg insta
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    exec(init_file.read(), command_ns)
  File "<string>", line 8, in <module>
ImportError: No module named bdist
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall python`

Could someone tell me how I can fix this issue ? 
Thank you

**Comment by DomT4** [comment]
Can you `brew gist-logs python`, Thanks.

**Comment by kamalbowselvam** [comment]
Hi @DomT4,

I got this output after I did brew gist-logs python 

https://gist.github.com/anonymous/70b2109b7847e1e77bfb

Thank you

**Comment by DomT4** [comment]
It looks like Homebrewed Python is already installed?

```
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
```

Are you trying to upgrade or?

**Comment by kamalbowselvam** [comment]
I did  ' brew install python ' it got the above error, but python works in my mac now. 
I can't do ' pip install virtualenv' 
'pip command not found' , I thought the error might be because python did not install properly.

**Comment by DomT4** [comment]
Yes, indeed. The error was `postinstall`, by the looks of it, and `postinstall` is where `pip` is placed on the system amongst other things. Does `brew postinstall python` produce the same error again?

**Comment by kamalbowselvam** [comment]
Hi @DomT4 ,
Surprisingly it works now, yesterday it did not. Thanks alot mate

**Comment by DomT4** [comment]
Great! Let us know if you hit any further issues on this.

CC @tdsmith in case you want to probe further on why this happened/etc.
