### ISSUE TITLE
Feature request: Can the author of the pull request stop the bot task?

### ISSUE THREAD

**Issue by jiegec** [Homebrew/homebrew#42990]
Sometimes, we may forget to edit the code before pushing to the branch. However it triggers a build. If we know that this built will fail, why can't we stop it manually? I don't want to waste other pull request's waiting time.

**Comment by bfontaine** [comment]
The solution is to verify your pull-request before submitting it :wink:

**Comment by mikemcquaid** [comment]
Yep, sorry, we can't let people stop builds as this functionality is provided by a Jenkins plugin rather than us.
