### ISSUE TITLE
When will you support OS X 10.11

### ISSUE THREAD

**Issue by qinyuhang** [Homebrew/homebrew#42999]
Every time i run homebrew, it pop out says not support OS X 10.11, although some package did work, like aria2 but mysql and mariadb is done. Please fix this problem.

**Comment by DomT4** [comment]
It's not a problem; It's just a warning that 10.11 is unstable and some packages may break during compile, at runtime or generally do unexpected things and that those breakages are not necessarily Homebrew problems.

Once Apple considers 10.11 production stable the warning will cease to be thrown, and bottles will start to be generated for El Capitan some time shortly before or after that initial stable release.

OS X Yosemite was released stable October the 16th last year. It's likely this year will follow a similar release schedule.
