### ISSUE TITLE
Installing boost locks up system with --universal or --c++11 options.

### ISSUE THREAD

**Issue by Reithan** [Homebrew/homebrew#43009]
Title pretty much says it all. Can't even force close. Have to hard reset.

**Comment by tdsmith** [comment]
Can you share the output of `brew config` and `brew doctor`? Compiling boost is a pretty good stress test; you may be running out of memory or exposing a hardware problem with your computer.

**Comment by Reithan** [comment]
I ran through brew doctor until I'd fixed all issues that reported, so last one was totally blank. Current brew config = 
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 37959a7ecf993869402de5812e0328751b1f87cc
Last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.10.5-x86_64
Xcode: 7.0 => /Applications/Xcode-beta.app/Contents/Developer
CLT: 6.4.0.0.1.1435007323
Clang: 6.1 build 602
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.7.0_80

**Comment by Reithan** [comment]
Also, running on a brand new macbook pro. 16Gb RAM and i7. Haven't had any other problems with anything. So, while I can't rule out a hardware issue, I think it's unlikely.

Notably, brew install boost with no config options installs fine.

**Comment by Reithan** [comment]
Though, I did not that with no options it download a yosemite tar of boost, while specifying any options downloads a different tar.

**Comment by tdsmith** [comment]
Looking at this again, the only thing that stands out is Xcode 7. Does this persist if you run `sudo xcode-select -s /Library/Developer/CommandLineTools` first?

**Comment by tdsmith** [comment]
With no options, Homebrew installs a precompiled bottle, which is much less work.

**Comment by mikemcquaid** [comment]
As we don't run as root there's not really anything else you can do that'll lock up your system beyond a hardware or OS fault.

**Comment by tdsmith** [comment]
Let us know if we can help with anything.
