### ISSUE TITLE
gptfdisk does not link to binaries

### ISSUE THREAD

**Issue by NickRSearcy** [Homebrew/homebrew#43000]
I'm running this on OS X 10.10

```
$ brew install gptfdisk
==> Downloading https://homebrew.bintray.com/bottles/gptfdisk-1.0.0_1.yosemite.b
Already downloaded: /Library/Caches/Homebrew/gptfdisk-1.0.0_1.yosemite.bottle.tar.gz
==> Pouring gptfdisk-1.0.0_1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/gptfdisk/1.0.0_1: 12 files, 868K
$ gdisk
-bash: gdisk: command not found
$ ls /usr/local/Cellar/gptfdisk/1.0.0_1/sbin/
cgdisk		fixparts	gdisk		sgdisk
```

I get the same after restarting the terminal

**Comment by DomT4** [comment]
If you run `brew doctor` does it tell you `sbin` isn't in your `$PATH` by any chance?

**Comment by NickRSearcy** [comment]
Oh, wow. Yeah. Should have checked `brew doctor`. Sorry

**Comment by DomT4** [comment]
No worries. We know this mechanism is a little less obvious than it needs to be & are working on it.

**Comment by NickRSearcy** [comment]
What confused me is that with most formulas, there's no need to modify my path anymore.

**Comment by DomT4** [comment]
The `bin`/`sbin` Unix debate is the reason. Almost everything installs into `bin` these days, but some projects follow the guidelines that tools that modify or maintain the system in some potentially risky way are to be dumped in [sbin](https://en.wikipedia.org/wiki/Unix_filesystem#Conventional_directory_layout).

It's relatively rare to find formulae which install into `sbin`, but there are some.
