### ISSUE TITLE
LibreSSL 2.2.2 fails to build on Snow Leopard with Intel Core 2 Duo

### ISSUE THREAD

**Issue by sysfu** [Homebrew/homebrew#43013]
I believe this has something to do with changes in the 2.2.2 release that require updated binutils. Workaround is to build using the '--disable-asm' option in the configure script. See [related LibreSSL 2.2.2 build problem on OpenBSD 5.7 issue] (https://github.com/libressl-portable/openbsd/issues/40) for more info.

**Comment by DomT4** [comment]
Yeah, this has been on my radar for a few days since https://github.com/libressl-portable/portable/issues/121 was filed. Will fix it very shortly.
