### ISSUE TITLE
Missing libncurses5 after `brew upgrade`

### ISSUE THREAD

**Issue by raincoats** [Homebrew/homebrew#43011]
I can't be sure it's brew or anything, but after a brew upgrade, libncurses 5 is mysteriously missing. I haven't been messing about with any libs, this is completely unexpected. All I've done all day is rsync some stuff.

brew upgrade output, brew doctor, and some other info: https://gist.github.com/raincoats/bc59e138e58dfb45f809

usually i'd just grab the specific version i need and be done with it, but i'm not sure how to do that in brew, and i can't find out either:

```shell
~ % man brew
dyld: Library not loaded: /usr/local/opt/ncurses/lib/libncursesw.5.dylib
  Referenced from: /usr/local/bin/less
  Reason: image not found
sh: line 1: 29550 Trace/BPT trap: 5       less

~ % less /usr/local/share/man/man1/brew.1
dyld: Library not loaded: /usr/local/opt/ncurses/lib/libncursesw.5.dylib
  Referenced from: /usr/local/bin/less
  Reason: image not found
[1]    29960 trace trap  less -R /usr/local/share/man/man1/brew
```

I've never had an issue with brew until this point, I'm running OS X 10.10.4, using zsh in iTerm2. My path has `/usr/local/{bin,sbin}` before the OS X default paths.

**Comment by mistydemeo** [comment]
ncurses was recently updated to version 6; looks like the revisions need to be bumped on anything using it.

**Comment by mistydemeo** [comment]
Interestingly, Homebrew's less shouldn't have been built against ncurses in the first place - it's not specified as a dependency. `brew reinstall less` should fix it.

**Comment by dunn** [comment]
Sorry, my fault for not checking carefully enough.

**Comment by raincoats** [comment]
@mistydemeo Beautiful. Works perfectly now.

**Comment by dunn** [comment]
I can't replicate this myself; when I build less it links against the system ncurses.

**Comment by raincoats** [comment]
Okay, interestingly, `less` works now, but before it opens, I'm getting this:

```shell
/my/code/ncurses/ncurses-5.0 % less /etc/passwd
dyld: Library not loaded: /usr/local/opt/ncurses/lib/libncursesw.5.dylib
  Referenced from: /my/bin/tetris
  Reason: image not found

```

`/my/bin/tetris` being my shell, which is just `zsh` with some strings changed. Yeah I fuck around a bit with things, I'm willing to bet that this issue is unique to my system.

**Comment by raincoats** [comment]
Oooh okay, yeah, I'm thinking this is something I've done.

```shell
/my/code/ncurses/ncurses-5.0 % echo $0; which tetris; tetris --version
-tetris
/mod/bin/tetris
dyld: Library not loaded: /usr/local/opt/ncurses/lib/libncursesw.5.dylib
  Referenced from: /mod/bin/tetris
  Reason: image not found
[1]    43398 trace trap  tetris --version
```

I've been needing to do a full reinstall for a while (some issues with freezing when opening the laptop), I suppose I should stop putting it off.
