### ISSUE TITLE
Install zeromq with libsodium by default

### ISSUE THREAD

**Issue by rgbkrk** [Homebrew/homebrew#43010]
In order to get, e.g., the go bindings for zeromq to work (https://github.com/zeromq/goczmq/issues/154), zeromq needs to be built with libsodium. In another project I work on, we can't rely on libsodium for encryption because everyone's libzmq installation is different.

Would it be possible to make `--with-libsodium` the default?

**Comment by dunn** [comment]
Are there any downsides to having that on by default?

**Comment by tdsmith** [comment]
Ref https://github.com/Homebrew/homebrew/pull/33241; we should see if ntopng is broken or else mitigate this problem in the ntopng formula.

**Comment by tdsmith** [comment]
discussion re ntopng in https://github.com/Homebrew/homebrew/pull/33697

**Comment by taotetek** [comment]
@dunn The only downside would be that it adds libsodium as a dependency.  I think most people would expect the encryption to be enabled and surprised if it wasn't - so I personally think that outweighs the additional dependency.

**Comment by mikemcquaid** [comment]
I think we need to pass on this unless we have a PR which includes a `revision` increase to `ntopng` which demonstrates it works. It's probably just asking people to install `--with-libsodium` in the mean time.
