### ISSUE TITLE
duplicity depends on python-keystoneclient for swift

### ISSUE THREAD

**Issue by forkedjensh** [Homebrew/homebrew#43027]
In order to use SWIFT_AUTHVERSION >= 2 in duplicity the python package python-keystoneclient is needed. This isn't included in duplicity.rb by now.

I am getting around this by editing the duplicity start script to include another PYTHON_PATH, so it would  be nice if python-keystoneclient is included.

Thanks in advance.

**Comment by bfontaine** [comment]
Would you mind doing a pull-request? Thanks!

**Comment by forkedjensh** [comment]
Thanks for your reply. I'll give it a try. I guess I have to learn a bit about python package versions and sha checksums in homebrew before.

**Comment by DomT4** [comment]
```diff

**Comment by DomT4** [comment]
```diff
resource "python-swiftclient" do
  url "https://pypi.python.org/packages/source/p/python-swiftclient/python-swiftclient-2.3.1.tar.gz"
  sha256 "20a9d81dc0d948740a188a0c42e7f7fcc9c81a185bfbdf180f68580ea49309a6"
end

+ resource "python-keystoneclient" do
+   url ""
+   sha256 ""
+ end
```

Is the syntax you want to use. You can grab the URL from pypi (Cut off the MD5 it appends at the end though) and then generate the SHA256 from `openssl dgst -sha256` or `shasum -a 256` or `brew fetch duplicity -fs`.

**Comment by forkedjensh** [comment]
After investigating further I noticed that python-keystoneclient is already present in the recipe. I will have to dig a bit deeper to get to know why duplicity keeps complaining about keystone as a missing dependency.

**Comment by forkedjensh** [comment]
I'm pretty stuck. It turned out, that python-keystoneclient is in there but the import of the keystone classes in python-swiftclient does not work:

    >>> from keystoneclient.v2_0 import client as ksclient
    [...]
    ImportError: No module named pkg_resources

So I added setuptools to the recipe. After that `__future__` was not found and I added future as a python package to duplicity.rb but it did not help. I get the same ImportError as before:

    >>> from keystoneclient.v2_0 import client as ksclient
    [...]
    ImportError: No module named __future__

I have no idea how to go on. For __future__ I added https://pypi.python.org/packages/source/f/future/future-0.15.0.tar.gz. May it's the wrong one.

Any help is really appreciated.

**Comment by forkedjensh** [comment]
Please ignore the last post. I was fiddling around with a wrong (broken) python binary.

After using the right one it turns out that importing oslo.config is not working. oslo.config is also included in the formula:

```bash
myhost:~ forkedjensh$ PYTHONPATH="/usr/local/Cellar/duplicity/0.6.25_1/libexec/vendor/lib/python2.7/site-packages:/usr/local/Cellar/duplicity/0.6.25_1/libexec/lib/python2.7/site-packages" /usr/bin/python
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from keystoneclient.v2_0 import client as ksclient
>>> Traceback (most recent call last):
>>>   File "<stdin>", line 1, in <module>
>>>     File "keystoneclient/__init__.py", line 27, in <module>
>>>         from keystoneclient import access
>>>           File "keystoneclient/access.py", line 20, in <module>
>>>               from oslo.utils import timeutils
>>>               ImportError: No module named oslo.utils
```

**Comment by forkedjensh** [comment]
I commited a pull request: #43263

**Comment by forkedjensh** [comment]
@bfontaine The pull request is there since yesterday. What shall I do to get things going?

**Comment by bfontaine** [comment]
@forkedjensh We just need to bump the revision as I wrote as a comment on the PR and it’ll be good to merge :smile:

**Comment by DomT4** [comment]
Closing in favour of the PR #43263.
