### ISSUE TITLE
Instruction mismatch on uninstalling a package with multiple installed versions

### ISSUE THREAD

**Issue by booc0mtaco** [Homebrew/homebrew#43023]
I noticed an inconsistency in the latest version of homebrew when you uninstall a package. I recently uninstalled a jruby bottle with:

`brew uninstall jruby`

This output:

```
Uninstalling /usr/local/Cellar/jruby/1.7.19... (4503 files, 63M)
jruby 1.7.20.1, 1.7.21 are still installed.
Remove them all with `brew uninstall --force jruby`.
```

Which is fine. Out of curiosity, I ran the command again:

`brew uninstall jruby`

Just to see if it would try to uninstall anything. This time it output:

```
Error: jruby has multiple installed versions
Use `brew remove --force jruby` to remove all versions.
```

`brew remove` doesn't appear when you view the help, so not sure if this should be changed to `uninstall` or if `remove` should be documented. Any information on this?

**Comment by bfontaine** [comment]
`remove` is an [alias](https://github.com/Homebrew/homebrew/blob/bbba8f6bbc298205e6fd75234d0ade0499348d55/Library/Homebrew/global.rb#L67) for `uninstall`.

**Comment by xu-cheng** [comment]
I think this can be closed now.
