### ISSUE TITLE
Boost 1.59.0 Available!

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew#43036]
I just checked the Boost website, and it says that the latest version of Boost is now v1.59.0.  I believe that Homebrew's Boost formula needs to be updated to reflect that, so can that be done?

**Comment by bfontaine** [comment]
Could you submit a pull request? Thanks!

**Comment by DomT4** [comment]
See #42960. It's ongoing.

**Comment by RandomDSdevel** [comment]
OK, thanks!  I'll keep an eye on that, then.
