### ISSUE TITLE
What to do about invalid SSL Repos?

### ISSUE THREAD

**Issue by jasmas** [Homebrew/homebrew#43043]
When a package's distribution site uses an invalid SSL certificate, what is the recommended way to create a working formula? Curl will complain unless there is some way to pass '-k'

**Comment by DomT4** [comment]
Find an alternative distribution site, if the site doesn't accept `http`. Debian, Fossies & Mirrorservice cover a lot of stuff between them.

`curl -k` is almost always a terrible idea.

**Comment by bfontaine** [comment]
> if the site doesn't accept `http`

@DomT4 I think you meant `https` :wink:

**Comment by jasmas** [comment]
The package is onioncat. The site hosting it redirects to https but has an invalid cert and I cannot find a mirror. 

https://www.onioncat.org/

Ideas?

**Comment by mistydemeo** [comment]
Could you use the [Debian source package](https://packages.debian.org/sid/onioncat) mirror?
