### ISSUE TITLE
brew install vim fails with clang lm error

### ISSUE THREAD

**Issue by periperipea** [Homebrew/homebrew#43052]
Hello folks,

I have vim failing to build on a brand new MBP running 10.10.  I get the following (I broke the lines for reasier reading:

    $ brew install vim
    ==> Downloading https://mirrors.kernel.org/debian/pool/main/v/vim/vim_7.4.712.orig.tar.gz
    Already downloaded: /Library/Caches/Homebrew/vim-7.4.712.tar.gz
    ==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/7.4.712_1/share/man --enable-
    multibyte --with-tlib=ncurses --enable-cscope --with-features=huge --with-compiledby=Homebrew
    --enable-perlinterp --enable-pythoninterp --enable-rubyinterp --enable-gui=no --
    ==> make
    /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -F/usr/local/Frameworks -DMACOS_X_UNIX  -Os
    -w -pipe -march=native -mmacosx-version-min=10.10 -U_FORTIFY_SOURCE 
    -D_FORTIFY_SOURCE=1       version.c -o objects/version.o
     env LD_RUN_PATH=/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE /usr/bin/clang   
    -L. -L/usr/local/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names 	
    -o vim objects/buffer.o objects/blowfish.o objects/charset.o objects/crypt.o objects/crypt_zip.o 
    objects/diff.o objects/digraph.o objects/edit.o objects/eval.o objects/ex_cmds.o objects/ex_cmds2.o 
    objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/fileio.o objects/fold.o 
    objects/getchar.o objects/hardcopy.o objects/hashtab.o  objects/if_cscope.o objects/if_xcmdsrv.o 
    objects/mark.o objects/memline.o objects/menu.o objects/message.o objects/misc1.o 
    objects/misc2.o objects/move.o objects/mbyte.o objects/normal.o objects/ops.o objects/option.o 
    objects/os_unix.o objects/pathdef.o objects/popupmnu.o objects/quickfix.o objects/regexp.o 
    objects/screen.o objects/search.o objects/sha256.o objects/spell.o objects/syntax.o  objects/tag.o 
    objects/term.o objects/ui.o objects/undo.o objects/version.o objects/window.o    objects/if_perl.o 
    objects/if_perlsfio.o objects/if_python.o   objects/if_ruby.o objects/os_macosx.o 
    objects/os_mac_conv.o  objects/netbeans.o  objects/main.o objects/memfile.o        lm  -lncurses
    -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-
    2level/CORE -lperl -F/usr/local/Cellar/python/2.7.10_2/Frameworks -framework Python   -lruby.2.0.0 
    -lpthread -ldl -lobjc
    clang: error: no such file or directory: 'lm'
    make[1]: *** [vim] Error 1
    make: *** [first] Error 2
    
    READ THIS: https://git.io/brew-troubleshooting
    
    These open issues may also help:
    vim  7.4.488 build fails if Homebrew ruby is installed but /usr/bin/ruby comes first in PATH
     https://github.com/Homebrew/homebrew/issues/33705

I don't have python installed, tried adding it and swapping the path out - no joy.  I tried everything in the above referenced link.

I suspect the problem is in the 4th last line before the clang error.  Should 'lm' not read '-lm'?

Obligatory gist-logs: https://gist.github.com/anonymous/74852228159b5e7674d6

Config: https://gist.github.com/anonymous/74852228159b5e7674d6#file-config-out

    $ brew doctor
    Your system is ready to brew.

Any help appreciated.
Thanks

**Comment by bfontaine** [comment]
This seems to be the same issue as #40206. Please reopen this one if the workarounds described these don’t work.

**Comment by periperipea** [comment]
None of the suggestions in the #40206 fixed my issue, but I did learn enough from that thread to work out what the problem was.  In my case, the problem was that I installed dash, and linked sh to dash, rather than bash.  For the purpose of this build, I swapped it out for bash:

    $ sudo rm /bin/sh
    $ sudo ln -s /bin/bash /bin/sh
    $ ls -lh /bin/bash /bin/sh
    lrwxr-xr-x  1 root  wheel    19B Aug 18 16:19 /bin/bash -> /usr/local/bin/bash
    lrwxr-xr-x  1 root  wheel     9B Aug 18 16:18 /bin/sh -> /bin/bash

With this arrangement, it builds as expected:

    $ brew install vim
    ==> Downloading https://mirrors.kernel.org/debian/pool/main/v/vim/vim_7.4.712.orig.tar.gz
    Already downloaded: /Library/Caches/Homebrew/vim-7.4.712.tar.gz
    ==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/7.4.712_1/share/man --enable-
    multibyte --with-tlib=ncurses --enable-cscope --with-features=huge --with-compiledby=Homebrew 
    --enable-perlinterp --enable-pythoninterp --enable-rubyinterp --enable-gui=no --
    ==> make
    ==> make install prefix=/usr/local/Cellar/vim/7.4.712_1 STRIP=true
    🍺  /usr/local/Cellar/vim/7.4.712_1: 1606 files, 26M, built in 37 seconds

I hope this helps someone!
