### ISSUE TITLE
OS X 10.11

### ISSUE THREAD

**Issue by Dreampie** [Homebrew/homebrew#43051]
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.

**Comment by DomT4** [comment]
It's not a problem; It's just a warning that 10.11 is unstable and some packages may break during compile, at runtime or generally do unexpected things and that those breakages are not necessarily Homebrew problems.

Once Apple considers 10.11 production stable the warning will cease to be thrown, and bottles will start to be generated for El Capitan some time shortly before or after that initial stable release.

OS X Yosemite was released stable October the 16th last year. It's likely 10.11 will follow a similar release schedule.
