### ISSUE TITLE
bottle libgdal not linked to current gdal version

### ISSUE THREAD

**Issue by rkrug** [Homebrew/homebrew#43057]
The bottle of liblas seems to be linked to gdal 1.11.1_2 while the current gdal version is 1.11.2_3 (if I am not mistaken). 

Consequently, configure errors occur when using liblas. 

Could the bottle be re-generated, as reinstalling liblas with --build-from-source fixes the problems?

**Comment by bfontaine** [comment]
Would you mind making a pull-request? You’d need to add `revision 1` under [this line](https://github.com/Homebrew/homebrew/blob/a4ad985a2ffe3ac79ffed322cabc17032811505a/Library/Formula/liblas.rb#L5).

**Comment by rkrug** [comment]
Done: https://github.com/Homebrew/homebrew/pull/43061
