### ISSUE TITLE
findutils updatedb should (optionally?) ignore time machine backups & spotlight info

### ISSUE THREAD

**Issue by adavies42** [Homebrew/homebrew#43050]
This is debatable, I suppose, but perhaps the Homebrew version of `updatedb` should default to ignoring Time Machine backups? I don’t think `find` is smart enough to understand the directory hardlink system Apple hacked up, so `updatedb` ends up spending ~50x as long as it otherwise would, traversing the dozens of nearly-identical copies of the same filesystem.

Here’s a possible patch:

    --- /usr/local/bin/updatedb	2015-04-26 15:51:38.000000000 -0400
    +++ updatedb	2015-08-17 20:40:04.000000000 -0400
    @@ -158,7 +158,7 @@
     : ${NETPATHS=}
     
     # Directories to not put in the database, which would otherwise be.
    -: ${PRUNEPATHS="/tmp /usr/tmp /var/tmp /afs /amd /sfs /proc"}
    +: ${PRUNEPATHS="/tmp /usr/tmp /var/tmp /afs /amd /sfs /proc /Volumes/[^/]+/Backups.backupdb"}
     
     # Trailing slashes result in regex items that are never matched, which 
     # is not what the user will expect.   Therefore we now reject such

**Comment by adavies42** [comment]
Possibly also any Spotlight info—less for wasting time, and more for wasting space in the index, as it’s of no real use.

    --- /usr/local/bin/updatedb	2015-04-26 15:51:38.000000000 -0400
    +++ updatedb	2015-08-17 21:50:12.000000000 -0400
    @@ -158,7 +158,7 @@
     : ${NETPATHS=}
     
     # Directories to not put in the database, which would otherwise be.
    -: ${PRUNEPATHS="/tmp /usr/tmp /var/tmp /afs /amd /sfs /proc"}
    +: ${PRUNEPATHS="/tmp /usr/tmp /var/tmp /afs /amd /sfs /proc /Volumes/[^/]+/Backups.backupdb /\(Volumes/[^/]+/\)?\.Spotlight-V100"}
     
     # Trailing slashes result in regex items that are never matched, which 
     # is not what the user will expect.   Therefore we now reject such

**Comment by bfontaine** [comment]
I don’t think this is an issue for Homebrew, you should contact upstream instead.

**Comment by adavies42** [comment]
It’s pretty Mac-specific, so I don’t know how willing they’d be. I’ll give it a try if that’s the preferred method though.

**Comment by bfontaine** [comment]
I agree it’s Mac-specific, but we won’t apply patchs that weren’t submitted/accepted upstream.
