### ISSUE TITLE
CGO problems building go binary from source

### ISSUE THREAD

**Issue by sparrc** [Homebrew/homebrew#43073]
I'm trying to get my project to build via homebrew, but am having a CGO-related issue that I can't quite work out. After it fails, the build works completely fine from the debug shell prompt.

There error I see is this:
__$WORK/github.com/influxdb/telegraf/plugins/system/ps/cpu/_obj//_cgo_.o: decoding dwarf section info at offset 0x0: too short__

This is the full output when trying to `brew install telegraf`

```
$ brew install telegraf --debug
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/telegraf.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/go.rb
Warning: Formula file is modified!
Building from source because Library/Formula/telegraf.rb has local changes
To install from a bottle instead, run with --force-bottle
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Formula/telegraf.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/go.rb
==> Downloading https://github.com/influxdb/telegraf/archive/v0.1.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/telegraf-0.1.4.tar.gz
==> go env
==> make build
/private/tmp/telegraf20150818-35390-kiqvdc/telegraf-0.1.4/bin/godep go install ./...
# github.com/influxdb/telegraf/plugins/system/ps/cpu
cannot load DWARF output from $WORK/github.com/influxdb/telegraf/plugins/system/ps/cpu/_obj//_cgo_.o: decoding dwarf section info at offset 0x0: too short
godep: go exit status 2
make: *** [prepare] Error 1
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make build
1. raise
2. ignore
3. backtrace
4. irb
5. shell
```

But when I enter a shell in debug mode, the build works fine:

```
Choose an action: 5
When you exit this shell, you will return to the menu.
tars% pwd
/private/tmp/telegraf20150818-35390-kiqvdc/telegraf-0.1.4/src/github.com/influxdb/telegraf
tars% make build
fatal: Not a git repository (or any of the parent directories): .git
go get github.com/tools/godep
/private/tmp/telegraf20150818-35390-kiqvdc/telegraf-0.1.4/bin/godep go install ./...
/private/tmp/telegraf20150818-35390-kiqvdc/telegraf-0.1.4/bin/godep go build -o telegraf -ldflags \
		"-X main.Version " \
		./cmd/telegraf/telegraf.go
tars%
```

And this is my telegraf.rb file:
```ruby
require "language/go"

class Telegraf < Formula
  desc "Server-level agent for InfluxDB"
  homepage "https://influxdb.com"
  url "https://github.com/influxdb/telegraf/archive/v0.1.4.tar.gz"
  sha256 "df586d0ada7e808b62ff476efd87c5a35e69a98bc45b3bf9823751cbccecc017"

  depends_on "go" => :build

  def install
    ENV["GOPATH"] = buildpath
    ENV["GOHOME"] = buildpath

    telegraf_path = buildpath/"src/github.com/influxdb/telegraf"
    telegraf_path.install Dir["*"]

    Language::Go.stage_deps resources, buildpath/"src"

    cd telegraf_path do
      system("go env")
      system("make build")
    end

    bin.install telegraf_path/"telegraf"
    etc.install telegraf_path/"etc/config.sample.toml" => "telegraf.conf"
  end
end
```

**Comment by mistydemeo** [comment]
I can't repro this working; it's broken for me in the same way if I drop to the shell and run `make build`.

The debug shell inherits some of your normal environment, which the regular build is isolated from. Is it possible there's something (like something you have installed, or a tool that's in your PATH) that makes it work?

**Comment by sparrc** [comment]
That makes more sense, I'm trying to figure that out, is there a way that I can force the `system("go env")` line from the .rb file to print it's output? that would be very helpful for me to debug this.

**Comment by mistydemeo** [comment]
The complete output of all of the tools is available in `~/Library/Logs/Homebrew/telegraf` - you can see the `go env` output there.

**Comment by mistydemeo** [comment]
Doing some testing, I was able to get this working by dropping the use of godep and staging the dependencies as `go_resource`s. I used `godep.json` to get the names and revisions of all the deps. This means not using the makefile, though. https://gist.github.com/aba5d928f3c5e631240e

**Comment by sparrc** [comment]
@mistydemeo thank you very much!! I was really hoping to get away from that since it would require vendoring the dependencies in two places, but your suggestion helped me figure it out!

Instead I'm installing just `godep` via `go_resource` and then using that to build telegraf.

see: https://gist.github.com/sparrc/5d45c79964db4965364b
