### ISSUE TITLE
InfluxDB 0.9.3 will attempt to write to /var/opt

### ISSUE THREAD

**Issue by victorhooi** [Homebrew/homebrew#43082]
In the newer versions of InfluxDB (0.9.3 and upwards), the default configuration file generated will have a section like this:

```
  # The following WAL settings are for the b1 storage engine used in 0.9.2. They won't
  # apply to any new shards created after upgrading to a version > 0.9.3.
  max-wal-size = 104857600 # Maximum size the WAL can reach before a flush. Defaults to 100MB.
  wal-flush-interval = "10m" # Maximum time data can sit in WAL before a flush.
  wal-partition-flush-delay = "2s" # The delay time between each WAL partition being flushed.

  # These are the WAL settings for the storage engine >= 0.9.3
  wal-dir = "/var/opt/influxdb/wal"
  wal-enable-logging = true
```

Note the reference to `/var/opt` - in my case, when I try to actually write points to InfluxDB, I get:
```
[write] 2015/08/19 14:23:31 write failed for shard 1 on node 1: load metadata index: mkdir /var/opt: permission denied
```
I think the receipe simply needs to be adapter to regex out this path as well.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew/commit/f5e92cc8f9bf0935e9e3db238e89ef9641763a7b.
