### ISSUE TITLE
install autojump

### ISSUE THREAD

**Issue by zcqshine** [Homebrew/homebrew#43080]
brew install autojump
==> Downloading https://github.com/wting/autojump/archive/release-v22.2.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/autojump-22.2.4.tar.gz
==> ./install.py -d /usr/local/Cellar/autojump/22.2.4 -z /usr/local/Cellar/autojump/22.2.4/share/zsh/site-functio
/usr/local/Cellar/autojump/22.2.4
-z
/usr/local/Cellar/autojump/22.2.4/share/zsh/site-functions

env: python: No such file or directory

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
AutoJump .bash_profile instructions incorrect https://github.com/Homebrew/homebrew/issues/42453

=======================
ps: use zsh, python3.4

**Comment by DomT4** [comment]
How does Python not exist on your system? Are you an OS X or Linux user? Can you supply your `brew config`, Thanks!

**Comment by posto** [comment]
I get the same error.

```
brew install autojump
==> Downloading https://github.com/wting/autojump/archive/release-v22.2.4.tar.gz
==> Downloading from https://codeload.github.com/wting/autojump/tar.gz/release-v22.2.4
######################################################################## 100.0%
==> ./install.py -d /usr/local/Cellar/autojump/22.2.4 -z /usr/local/Cellar/autojump/22.2.4/share/zsh/site-functions
Last 15 lines from /Users/dpostoronc/Library/Logs/Homebrew/autojump/01.install.py:
2015-10-07 17:26:18 +0200

./install.py
-d
/usr/local/Cellar/autojump/22.2.4
-z
/usr/local/Cellar/autojump/22.2.4/share/zsh/site-functions

Unsupported shell: /bin/sh

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
install autojump https://github.com/Homebrew/homebrew/issues/43080
```

```
python                                                                                                    
Python 2.7.10 (default, Jul 14 2015, 19:46:27)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

``` 
brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 82504bca48cc0ed2cc224aa5069c070c2627c17b
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.10.5-x86_64
Xcode: N/A
CLT: 7.0.0.0.1.1441394355
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_60, 1.7.0_79, 1.6.0_65-b14-466.1
```

**Comment by rdp** [comment]
worked OK here (10.10.5)

**Comment by DomT4** [comment]
Please let us know if we can help any further; Thanks!

**Comment by zcqshine** [comment]
brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 422e608d26123504f9f630cd1c8cb44ca2506545
Last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.11.1-x86_64
Xcode: 7.1.1
CLT: 7.1.0.0.1.1444952191
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /Users/zcqshine/.pyenv/shims/python => /Users/zcqshine/.pyenv/versions/3.4.0/bin/python3.4
Ruby: /Users/zcqshine/.rvm/rubies/ruby-2.0.0-p643/bin/ruby
Java: 1.8.0_25

**Comment by zcqshine** [comment]
I think the question is privilege of the folder. 
OSX 10.10 changed the privilege of the folder '/usr/local', I fixed it and then install autojump successfully.
Thanks.

**Comment by zcqshine** [comment]
```
 /usr  brew update
Error: The /usr/local directory is not writable.
Even if this directory was writable when you installed Homebrew, other
software may change permissions on this directory. Some versions of the
"InstantOn" component of Airfoil are known to do this.

You should probably change the ownership and permissions of /usr/local
back to your user account.
 sudo chown -R $(whoami):admin /usr/local
sudo chown -R $zcqshine:admin /usr/local
```
