### ISSUE TITLE
undefined method `desc' for Formulary::Formulae::Phpmyadmin:Class

### ISSUE THREAD

**Issue by TheFrenchDeveloper** [Homebrew/homebrew#43086]
$ brew install homebrew/php/phpmyadmin
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-php'...
remote: Counting objects: 10703, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 10703 (delta 3), reused 0 (delta 0), pack-reused 10695
Receiving objects: 100% (10703/10703), 2.18 MiB | 20.00 KiB/s, done.
Resolving deltas: 100% (7287/7287), done.
Checking connectivity... done.
Tapped 502 formulae
Error: undefined method `desc' for Formulary::Formulae::Phpmyadmin:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/phpmyadmin.rb:2:in `<class:Phpmyadmin>'
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/phpmyadmin.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:177:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:135:in `<main>'

**Comment by bfontaine** [comment]
Please run `brew update` and try again.

**Comment by DomT4** [comment]
The above will resolve your problem.
