### ISSUE TITLE
EmguCV 3.0.0

### ISSUE THREAD

**Issue by kovich** [Homebrew/homebrew#43093]
.NET/mono wrapper to openCV.

Please help to provide a formula to build on OSX 10.10.

**Comment by mikemcquaid** [comment]
We don't really do formula requests. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
