### ISSUE TITLE
MariaDB install creates stray symlink "*.plist" in LaunchAgents

### ISSUE THREAD

**Issue by edrozenberg** [Homebrew/homebrew#43101]
After mariadb installation, ~/Library/LaunchAgents contains a stray symlink:

    lrwxr-xr-x   1 me  staff    28B Jan 20  2015 *.plist -> /usr/local/opt/mysql/*.plist

**Comment by tdsmith** [comment]
Homebrew does not create these files. You may have, based on our advice, printed after installation:
```
To have launchd start mariadb at login:
  ln -sfv /usr/local/opt/mariadb/*.plist ~/Library/LaunchAgents
```

You can safely remove any plist symlinks if you are no longer using them. Let us know if we can help with anything else.

**Comment by edrozenberg** [comment]
Thanks I'm sure that's what happened. Perhaps the various package build scripts could document the full name of the file to link instead of *.plist - would make it easy and unambiguous for those users who just paste in that symlink creation command line from the brew info.
