### ISSUE TITLE
ice install on osx 10.10.5 failed

### ISSUE THREAD

**Issue by CrossLee** [Homebrew/homebrew#43104]
I had tried brew installation and source installation, all are failed.

brew installation:
crossrmbp:generated apple$ brew install ice --with-java
==> Downloading https://github.com/zeroc-ice/ice/archive/v3.6.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/ice-3.6.0.tar.gz
==> Downloading https://zeroc.com/download/homebrew/db-5.3.28.NC.brew.tar.gz
Already downloaded: /Library/Caches/Homebrew/ice--berkeley-db-5.3.28.NC.brew.tar.gz
==> ../dist/configure --disable-debug --prefix=/usr/local/Cellar/ice/3.6.0/libexec --mandir=/
==> make install
==> make install prefix=/usr/local/Cellar/ice/3.6.0 embedded_runpath_prefix=/usr/local/Cellar
ld: library not found for -lmcpp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../../lib/libSlice.3.6.0.dylib] Error 1
make[1]: *** [install] Error 1
make: *** [install] Error 1

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
ice failed to build on 10.11 https://github.com/Homebrew/homebrew/issues/42505

**Comment by DomT4** [comment]
Can you produce a full `brew gist-logs ice`, Thanks.

**Comment by CrossLee** [comment]
@DomT4 https://gist.github.com/fd8bac43e78999cfd651

**Comment by DomT4** [comment]
Thank you! Same issue as in #42505 - For some reason not having the CLT installed causes detection failure. I'll try and take a peek at it later today, maybe we can just pass the right path directly to the build process rather than allowing it to be found automatically.

**Comment by externl** [comment]
I think this should be fixed now with the Ice 3.6.1 formula. The formula now passes MCPP_HOME to the ice build system.

**Comment by DomT4** [comment]
Presuming resolved then, unless told otherwise.
