### ISSUE TITLE
smlnj failed to build on 10.11

### ISSUE THREAD

**Issue by chmaynard** [Homebrew/homebrew#43100]
==> config/install.sh
    config/install.sh: Installation directory is /usr/local/Cellar/smlnj/110.78/SMLNJ_HOME.
    config/install.sh: Installing version 110.78.
    config/install.sh: URL of source archive is http://smlnj.cs.uchicago.edu/dist/working/110.78/.
    config/install.sh: !!! Script /usr/local/Cellar/smlnj/110.78/SMLNJ_HOME/bin/.arch-n-opsys fails on this machine.
    config/install.sh: !!! You must patch this by hand and repeat the installation.

Logs at https://gist.github.com/427d45c6cca60c987861

**Comment by DomT4** [comment]
It pings `uname -r` to determine the platform and doesn't know El Captain exists so runs around panicking. I'll patch this and file it upstream shortly.

**Comment by chmaynard** [comment]
Awesome, thanks.

**Comment by chmaynard** [comment]
Tested in OS X 10.11 Build 15A262e.

    ==> config/install.sh
    🍺  /usr/local/Cellar/smlnj/110.78: 6581 files, 86M, built in 67 seconds
