### ISSUE TITLE
install gnu-apl 1.5

### ISSUE THREAD

**Issue by eccstartup** [Homebrew/homebrew#43112]
I find `gnu-apl` version 1.5 can build by 

* using gcc-5 installed from `homebrew` instead of mac gcc (no need for bottled version)
* patching one source file

The detail is [here](https://github.com/Homebrew/homebrew/commit/698fde5176d476a62827cd51c0566241561e867e).

**Comment by mikemcquaid** [comment]
What's the problem you're having?

**Comment by eccstartup** [comment]
Requesting a new bottled version 1.5 over 1.4

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by eccstartup** [comment]
OK. I will try to finish this within one day. :3

**Comment by DomT4** [comment]
PR in #43147 was closed. If you want to open a new one with the comments there addressed when possible, that'd be welcome. Thanks for the willingness to contribute!
