### ISSUE TITLE
i want to install erlang 17.5 where can i find the formula

### ISSUE THREAD

**Issue by zjhmale** [Homebrew/homebrew#43124]
the latest formula is erlang18 and in homebrew/versions there is just erlang13 - erlang16 so if i want to `brew install erlang version 17.5` how can i get it

ps: i think `brew versions` is a good command, why remove that, with `brew versions` i can install things with specific version

**Comment by mikemcquaid** [comment]
@zjhmale Someone will need to open a pull request on `homebrew-versions`. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by zjhmale** [comment]
i don't propose to contribute any code why should a open a pull request? @mikemcquaid 
you mean i should open my issue in `homebrew-versions` project?

**Comment by mikemcquaid** [comment]
@zjhmale We're just a project run by in our spare time; we'll need someone to write the code and it would be good if you could try that?

**Comment by DomT4** [comment]
Please file a PR; we don't do formula requests, Thanks.

There are several Erlang formulae in `Homebrew/Versions` which you're welcome to use as an example, and the last Homebrew `erlang` formula in the git history prior to the last two updates might just be a copy-paste job, largely.
