### ISSUE TITLE
git-lfs should run git-lfs uninit on uninstall

### ISSUE THREAD

**Issue by lbergelson** [Homebrew/homebrew#43126]
Right now if you do `brew uninstall git-lfs` it leaves your .gitconfig in a strange state with a `[filter "lfs"]` block.  This causes any git projects using LFS to do strange things until it's deleted.  

git-lfs provides a `git-lfs uninit` command to remove this, but it isn't run when running `brew uninstall git-lfs`  It would be nice if it was.

I'd be happy to help with this, but from my (admittedly quick) scan of the formula cook book, I couldn't figure out how to add any sort of uninstall trigger.  Is this possible?

**Comment by mistydemeo** [comment]
That's correct; I'm afraid we don't offer any sort of uninstall trigger. We could add a caveat to the formula telling users to do it, but we don't have any ability to actually perform special behaviour on uninstall.

**Comment by lbergelson** [comment]
Ah, thanks for the response.  It seems like it would be a useful feature. (Or at least being able to specify caveats that display at uninstall time...) 

I think a caveat would be useful.  It would have saved me some confusion at least.  I'll put together a pull request for it when I get a chance.

**Comment by mistydemeo** [comment]
Thanks!

**Comment by mikemcquaid** [comment]
> I'll put together a pull request for it when I get a chance.

Closing this in favour of a PR, thanks!
