### ISSUE TITLE
Apache Spark failed install

### ISSUE THREAD

**Issue by AndrewKL** [Homebrew/homebrew#43135]
==> Downloading https://www.apache.org/dyn/closer.cgi?path=spark/spark-1.4.1/spark-1.4.1
Error: Failed to download resource "apache-spark"
Download failed: Couldn't determine mirror, try again later.

**Comment by AndrewKL** [comment]
an hour later its working 

➜  ~  brew install apache-spark
==> Downloading https://www.apache.org/dyn/closer.cgi?path=spark/spark-1.4.1/spark-1.4.1
==> Best Mirror http://mirror.reverse.net/pub/apache/spark/spark-1.4.1/spark-1.4.1-bin-h
##########                                                                15.2%

**Comment by gibiansky** [comment]
Same issue happening now.

**Comment by DomT4** [comment]
Sometimes Apache has transient issues. They usually self-resolve fairly quickly. Feel free to open a new issue though if it persists for too long.

**Comment by fer-git** [comment]
Hi,
I have the same issue too. I can upgrade other package without problem except apache-spark.

==> Upgrading apache-spark
==> Downloading https://www.apache.org/dyn/closer.cgi?path=spark/spark-1.4.1/spark-1.4.1-bin-hadoop2.6.tgz
Error: Failed to download resource "apache-spark"
Download failed: Couldn't determine mirror, try again later.

**Comment by jawshooah** [comment]
Same here, 8 hours after @fer-git:

```
$ brew install --verbose apache-spark
==> Downloading https://www.apache.org/dyn/closer.cgi?path=spark/spark-1.4.1/spark-1.4.1-bin-hadoop2.6.tgz
Error: Failed to download resource "apache-spark"
Download failed: Couldn't determine mirror, try again later.
```
