### ISSUE TITLE
Handle Option Removal

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew#43136]
Today's upgrade of `go` highlighted an example of the problem Homebrew has with options that are no longer valid.

Prior to 1.5 being released I built `go --with-cc-common`. We removed that option as upstream moved to a different mechanism and it was no longer required, however today on running `brew upgrade` instead of pouring the bottle, intelligently resolving my previously used option was no longer available/valid/etc, `brew` triggered a manual from-source installation with the previous option retained.

Let's chuck it on the list of things we need to fix.

**Comment by bfontaine** [comment]
Would something like this work?

```diff
diff --git a/Library/Homebrew/cmd/upgrade.rb b/Library/Homebrew/cmd/upgrade.rb
index e1b7dd0..55476fa 100644
--- a/Library/Homebrew/cmd/upgrade.rb
+++ b/Library/Homebrew/cmd/upgrade.rb
@@ -53,7 +53,7 @@ module Homebrew
     tab = Tab.for_formula(f)
 
     fi = FormulaInstaller.new(f)
-    fi.options             = tab.used_options
+    fi.options             = tab.used_options & f.options.as_flags
     fi.build_bottle        = ARGV.build_bottle? || (!f.bottled? && tab.build_bottle?)
     fi.build_from_source   = ARGV.build_from_source?
     fi.verbose             = ARGV.verbose?
```

**Comment by xu-cheng** [comment]
@bfontaine That will fail to handle two cases:
* deprecated options
* options with value (used in some formulae in homebrew/science)

**Comment by dunn** [comment]
Another case: #43647

**Comment by tt** [comment]
In the case of mutt and `--with-thrash-patch`, the upgrade might cause you to lose data. I think it would make sense to either warn or error if the option isn't supported.

**Comment by dunn** [comment]
That's a good idea.

**Comment by DomT4** [comment]
Tagging https://github.com/Homebrew/homebrew/pull/47575 as another example.

**Comment by DomT4** [comment]
Was fixed by https://github.com/Homebrew/homebrew/pull/47891 as far as I recall.
