### ISSUE TITLE
devil failed to install on OS X 10.10.4

### ISSUE THREAD

**Issue by dg1sbg** [Homebrew/homebrew#43161]
When trying to install devil I encounter the error saying that no suitable compilers are installed.

$ brew install -v devil
Error: devil cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc

I installed gcc with brew, did the usual update and doctor games - still the error persists,

For more info see the following gist:
https://gist.github.com/dg1sbg/b295803efd1053065958

Thanks for any hints,

**Comment by mistydemeo** [comment]
The error message is misleading; for technical reasons, we're not able to fix that right now. You should be able to `brew install homebrew/versions/gcc49` and build it with that, however. Sorry!

**Comment by dg1sbg** [comment]
Absolutely no problem. Thx a bunch for the very prompt feedback!
