### ISSUE TITLE
wireshark failed to build on 10.10.5

### ISSUE THREAD

**Issue by chrismccracken** [Homebrew/homebrew#43164]
When upgrading packages, wireshark build failed as follows (seems to be different than https://github.com/Homebrew/homebrew/issues/39455):

⚡ ~ ► brew upgrade
==> Upgrading 1 outdated package, with result:
wireshark 1.12.6
==> Upgrading wireshark
==> Downloading https://www.wireshark.org/download/src/all-versions/wireshark-1.12.6.tar.bz2
Already downloaded: /Library/Caches/Homebrew/wireshark-1.12.6.tar.bz2
==> Patching
patching file configure
Hunk #1 succeeded at 16946 (offset 243 lines).
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/wireshark/1.12.6 --with-gnutls --disable-gtktest --with-qt
==> make
libtool: link: clang -DPYTHON_DIR= -g -O2 -Wall -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wpointer-arith -Wno-pointer-sign -Warray-bounds -Wformat-security -fwrapv -Wold-style-definition -Wshorten-64-to-32 -Wstrict-prototypes -Wvla -Waddress -Wattributes -Wdiv-by-zero -Wignored-qualifiers -Wpragmas -Wno-overlength-strings -Wwrite-strings -Wno-long-long -Wc++-compat -Wheader-guard -Wshadow -Wno-deprecated-declarations -fvisibility=hidden -I/usr/local/Cellar/qt5/5.5.0/include/QtCore -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtGui -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtCore -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtWidgets -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtGui -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtCore -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtPrintSupport -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtWidgets -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtGui -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtCore -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtMacExtras -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtGui -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtCore -I/usr/local/Cellar/qt5/5.5.0/include -D_REENTRANT -I/usr/local/Cellar/glib/2.44.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.44.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -Wl,-search_paths_first -Wl,-rpath -Wl,@executable_path/../lib -Wl,-rpath -Wl,@executable_path/../Frameworks -Wl,-rpath -Wl,/usr/local/lib -o .libs/dftest dftest-dftest.o .libs/dftestS.o -dynamic -Wl,-search_paths_first  -L/usr/local/lib ui/libui.a wiretap/.libs/libwiretap.dylib -L/usr/local/Cellar/glib/2.44.1/lib -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/libgcrypt/1.6.3_1/lib -L/usr/local/Cellar/libgpg-error/1.19/lib wsutil/.libs/libwsutil.dylib epan/.libs/libwireshark.dylib -llua -L/usr/local/Cellar/gnutls/3.3.17.1/lib -lGeoIP /private/tmp/wireshark20150821-17875-vekl19/wireshark-1.12.6/wiretap/.libs/libwiretap.dylib /private/tmp/wireshark20150821-17875-vekl19/wireshark-1.12.6/wsutil/.libs/libwsutil.dylib -lgthread-2.0 -lgmodule-2.0 -lglib-2.0 -lintl -lpcap -lcares -lkrb5 -lgcrypt -lgpg-error -lgnutls -lm -lz
libtool: link: rm -f ".libs/rawsharkS.c" ".libs/rawshark.nm" ".libs/rawshark.nmS" ".libs/rawshark.nmT"
libtool: link: clang -DPYTHON_DIR= -g -O2 -Wall -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wpointer-arith -Wno-pointer-sign -Warray-bounds -Wformat-security -fwrapv -Wold-style-definition -Wshorten-64-to-32 -Wstrict-prototypes -Wvla -Waddress -Wattributes -Wdiv-by-zero -Wignored-qualifiers -Wpragmas -Wno-overlength-strings -Wwrite-strings -Wno-long-long -Wc++-compat -Wheader-guard -Wshadow -Wno-deprecated-declarations -fvisibility=hidden -I/usr/local/Cellar/qt5/5.5.0/include/QtCore -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtGui -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtCore -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtWidgets -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtGui -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtCore -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtPrintSupport -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtWidgets -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtGui -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtCore -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtMacExtras -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtGui -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtCore -I/usr/local/Cellar/qt5/5.5.0/include -D_REENTRANT -I/usr/local/Cellar/glib/2.44.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.44.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -Wl,-search_paths_first -Wl,-rpath -Wl,@executable_path/../lib -Wl,-rpath -Wl,@executable_path/../Frameworks -Wl,-rpath -Wl,/usr/local/lib -o .libs/rawshark rawshark-capture-pcap-util-unix.o rawshark-capture-pcap-util.o rawshark-cfile.o rawshark-cfutils.o rawshark-clopts_common.o rawshark-frame_tvbuff.o rawshark-sync_pipe_write.o rawshark-version_info.o rawshark-rawshark.o .libs/rawsharkS.o -dynamic -Wl,-search_paths_first  -L/usr/local/lib ui/libui.a wiretap/.libs/libwiretap.dylib -L/usr/local/Cellar/glib/2.44.1/lib -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/libgcrypt/1.6.3_1/lib -L/usr/local/Cellar/libgpg-error/1.19/lib epan/.libs/libwireshark.dylib -llua -L/usr/local/Cellar/gnutls/3.3.17.1/lib -lGeoIP /private/tmp/wireshark20150821-17875-vekl19/wireshark-1.12.6/wiretap/.libs/libwiretap.dylib /private/tmp/wireshark20150821-17875-vekl19/wireshark-1.12.6/wsutil/.libs/libwsutil.dylib wsutil/.libs/libwsutil.dylib -lgthread-2.0 -lgmodule-2.0 -lglib-2.0 -lintl -lpcap -lcares -lkrb5 -framework SystemConfiguration -framework CoreFoundation -lgcrypt -lgpg-error -lgnutls -lm -lz
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
WireShark fails to build on 10.6.8 https://github.com/Homebrew/homebrew/issues/39455

⚡ ~ ► brew gist-logs wireshark
https://gist.github.com/2d819a7e0ad55186371e

**Comment by DomT4** [comment]
The problem is Qt5. The latest Qt5 is *horribly* broken, see #42480 and #42217 and #42191.

**Comment by DomT4** [comment]
`brew update && brew upgrade qt5` and this should work again as expected. Should be fixed by the https://github.com/Homebrew/homebrew/commit/fdbb338f2274e093b96209e7ca3ff9bf5460714e commit.

**Comment by chrismccracken** [comment]
Confirmed fixed, thanks.
