### ISSUE TITLE
Bottles mirroring

### ISSUE THREAD

**Issue by typcn** [Homebrew/homebrew#43171]
I want to deploy a free China CDN mirror of "brew bottles" , because China is dropping oversea packet randomly , download speed < 1KB/s.

But the network transfer between china and Bintray(CloudFront) is very slow , I need prefetch the resources . 

Can you provide the list of bottle files ?  Thanks.

**Comment by jiegec** [comment]
Agree. Sometimes we have to use a proxy to download the bottles to speed up download speed.

**Comment by mikemcquaid** [comment]
We can't provide a full list, you'd need to use the Bintray API to obtain them. Sorry.

**Comment by xu-cheng** [comment]
Once  #43848 is merged, bottle list should be able to be obtained by `brew info --json --all`.

**Comment by typcn** [comment]
thanks
