### ISSUE TITLE
ntopng --HEAD error

### ISSUE THREAD

**Issue by Drewshg312** [Homebrew/homebrew#43185]
Hi guys.. I'm trying to install the HEAD version of ntopng.
Here is the output:

    $ brew reinstall ntopng --HEAD
    ==> Reinstalling ntopng
    ==> Cloning https://github.com/ntop/ntopng.git
    Cloning into '/Library/Caches/Homebrew/ntopng--git'...
    remote: Counting objects: 1704, done.
    remote: Compressing objects: 100% (1327/1327), done.
    remote: Total 1704 (delta 361), reused 1576 (delta 342), pack-reused 0
    Receiving objects: 100% (1704/1704), 13.92 MiB | 1.62 MiB/s, done.
    Resolving deltas: 100% (361/361), done.
    Checking connectivity... done.
    Checking out files: 100% (1625/1625), done.
    ==> Checking out branch master
    ==> ./autogen.sh
    ==> ./configure --prefix=/usr/local/Cellar/ntopng/HEAD
    ==> make
    2015-08-22 15:29:08 -0700
    
    make
    
    make: *** No targets specified and no makefile found.  Stop.
    
    READ THIS: https://git.io/brew-troubleshooting

Any ideas? Please help!

**Comment by dunn** [comment]
Can you post `brew gist-logs ntopng`, please?

**Comment by DomT4** [comment]
The problem is the missing expected resource, which we can fix easily enough by doing this:

```diff
diff --git a/Library/Formula/ntopng.rb b/Library/Formula/ntopng.rb
index f1918a2..d478445 100644
--- a/Library/Formula/ntopng.rb
+++ b/Library/Formula/ntopng.rb
@@ -3,7 +3,6 @@ class Ntopng < Formula
   homepage "http://www.ntop.org/products/ntop/"
   url "https://downloads.sourceforge.net/project/ntop/ntopng/ntopng-2.0.tar.gz"
   sha256 "3cbfd6de1bc44d65f7c7f0de282d122d11f493f1261ba137c3b5b202e08e0251"
-  head "https://github.com/ntop/ntopng.git"

   bottle do
     sha256 "c3a9c8be354c9fd3cbed7f84a6b9585d2b2d9bd1111a44e68c37694ea85707ba" => :yosemite
@@ -11,6 +10,14 @@ class Ntopng < Formula
     sha256 "355c68400b80698448e8197316a015cb88563600cb8a619df20d0bef2e79b0ca" => :mountain_lion
   end

+  head do
+    url "https://github.com/ntop/ntopng.git"
+
+    resource "nDPI" do
+      url "https://github.com/ntop/nDPI.git", :branch => "dev"
+    end
+  end
+
   depends_on "autoconf" => :build
   depends_on "automake" => :build
   depends_on "pkg-config" => :build
@@ -27,6 +34,14 @@ class Ntopng < Formula
   depends_on "redis"

   def install
+    if build.head?
+      resource("nDPI").stage do
+        system "./autogen.sh"
+        system "make"
+        (buildpath/"nDPI").install Dir["*"]
+      end
+    end
+
```

Except then this happens:

```
-I/private/tmp/ntopng20150822-24304-1qbxoul/third-party/EWAHBoolArray/headers  -DDATA_DIR='"/usr/local/Cellar/ntopng/HEAD/share"' -I/private/tmp/ntopng20150822-24304-1qbxoul/third-party/libgeohash -I/private/tmp/ntopng20150822-24304-1qbxoul/third-party/patricia   -c src/Flow.cpp -o src/Flow.o
src/Flow.cpp:96:28: error: assigning to 'u_int16_t' (aka 'unsigned short') from incompatible type 'ndpi_protocol'
      (aka 'ndpi_proto')
    ndpi_detected_protocol = ndpi_guess_undetected_protocol(iface->get_ndpi_struct(),
                           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/Flow.cpp:469:30: error: assigning to 'u_int16_t' (aka 'unsigned short') from incompatible type 'ndpi_protocol'
      (aka 'ndpi_proto')
      ndpi_detected_protocol = ndpi_guess_undetected_protocol(iface->get_ndpi_struct(), protocol,
                             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make: *** [src/Flow.o] Error 1
```

**Comment by Drewshg312** [comment]
Hi guys! Thank you for reply. Here is gist:
https://gist.github.com/1a7f36c011ed95c58792

**Comment by Drewshg312** [comment]
I've written to them again... waiting for answer

**Comment by Drewshg312** [comment]
Well that's what I was told to do:
"Your nDPI is newer than your ntopng code, Use the code of ntopng that's on git…"

**Comment by DomT4** [comment]
We are. The process used by the diff above is:

* `git clone https://github.com/ntop/ntopng.git`
* `git clone https://github.com/ntop/nDPI.git`
* `cd /tmp/blah-nDPI`
* `./autogen.sh`
* `make`
* `mv * /tmp/blah-ntopng/nDPI/`
* `cd /tmp/blah-ntopng`
* `./autogen.sh`
* `./configure --prefix=#{prefix}`
* `make`
* `make install`

**Comment by Drewshg312** [comment]
Well when I've done all this manually - everything works great… So there is probably some mistake in homebrew install function... could you show the whole `def install`?

**Comment by Drewshg312** [comment]
Well I don't understand what's going on… here is the discussion with ntopng developer… 
https://github.com/ntop/ntopng/issues/132#issuecomment-135198902
You could probably understand him better…

**Comment by tzudot** [comment]
@Drewshg312 need to checkout `dev` branch for `ntopng`. Add this to @DomT4's patch.
```
url "https://github.com/ntop/ntopng.git", :branch => "dev"
```

**Comment by Drewshg312** [comment]
gotcha!!! Works! Thank you!! Submitting pull reques!
