### ISSUE TITLE
Fix `GitHub API rate limit exceeded` with a brew setting

### ISSUE THREAD

**Issue by alexchandel** [Homebrew/homebrew#43189]
It shouldn't be necessary to modify my environment, or change one of my profiles to set `HOMEBREW_GITHUB_API_TOKEN` every session, just to get `brew search` to work as expected. Homebrew should be able to remember the API token.

**Comment by mikemcquaid** [comment]
There's no such thing as a `brew setting`. Changing your profile is how you configure these things with Homebrew, sorry.
