### ISSUE TITLE
brew install git give Error: undefined method `dirname' for nil:NilClass

### ISSUE THREAD

**Issue by noresources** [Homebrew/homebrew#43206]
on OS X 10.6.8
Backtrace
snow:premake-core renaud$ brew install git
Error: undefined method `dirname' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula.rb:768:in `file_modified?'
/usr/local/Library/Homebrew/formula_installer.rb:78:in `pour_bottle?'
/usr/local/Library/Homebrew/formula_installer.rb:159:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:188:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:93:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:93:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:93:in `install'
/usr/local/Library/brew.rb:127:in `send'
/usr/local/Library/brew.rb:127

Gist
https://gist.github.com/anonymous/f6b625978649695c7f0c

**Comment by qris** [comment]
I just broke my Homebrew by doing `brew update`. Now every `install` or `update` command fails with this error, and I can't use Homebrew any more! Please help :/

**Comment by DomT4** [comment]
Try `cd $(brew --prefix) && git fetch && git reset --hard origin/master`

**Comment by qris** [comment]
Thanks for the suggestion. brew --prefix gives /usr/local which is not a Git checkout, so `git fetch` and `git reset` commands both give errors when run there:

    chris-macbook:local chriswilson$ git fetch
    fatal: Not a git repository (or any of the parent directories): .git

I moved /usr/local out of the way and reinstalled Homebrew, but I still can't install anything, not even Git:

Run `brew help` to get started
chris-macbook:usr chriswilson$ brew install alpine
Error: undefined method `dirname' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula.rb:768:in `file_modified?'
/usr/local/Library/Homebrew/formula_installer.rb:78:in `pour_bottle?'
/usr/local/Library/Homebrew/formula_installer.rb:159:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:188:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:93:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:93:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:93:in `install'
/usr/local/Library/brew.rb:127:in `send'
/usr/local/Library/brew.rb:127
chris-macbook:usr chriswilson$ brew update
You must: brew install git
Error: Failure while executing: git init
chris-macbook:usr chriswilson$ brew install git
Error: undefined method `dirname' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula.rb:768:in `file_modified?'
/usr/local/Library/Homebrew/formula_installer.rb:78:in `pour_bottle?'
/usr/local/Library/Homebrew/formula_installer.rb:159:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:188:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:93:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:93:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:93:in `install'
/usr/local/Library/brew.rb:127:in `send'
/usr/local/Library/brew.rb:127

**Comment by DomT4** [comment]
Oh dear. What does `echo $PATH` respond as? It's curious there's no `git` on your system - The older git versions do have problems, but as far as I remember 10.6.x did ship with a `git`.

**Comment by qris** [comment]
I'm afraid that https://github.com/fraction/news/issues/125 seems to imply no `git` in 10.6.x.

    $ echo $PATH
    /opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/sbin:/Users/chriswilson/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/git/bin:/usr/X11/bin:/usr/local/git/bin:/usr/local/mysql/bin

**Comment by DomT4** [comment]
Yeah, I checked in with another Homebrew maintainer and apparently 10.6.x lacks `git` natively.

I *think* you could download the master zip from here: https://github.com/Homebrew/homebrew/archive/master.zip and then unzip that into `/usr/local` or wherever, then do `brew install git` to regain git functionality.

**Comment by matt-hayden** [comment]
Maybe this will help:

Installed Homebrew today, have git installed at /usr/local/git/bin/git (I thought this was a common place for it, but maybe not). It's in my PATH. Ran into the same error.

The offending line was: /usr/local/Library/Homebrew/formula.rb:768:in `file_modified?'
MacOS.locate("git").dirname.to_s

Substituted the path to my git instead and this restored functionality.

**Comment by fpagnoux** [comment]
Hi @DomT4,
I just installed homebrew today on OSX 10.7.5
I run into the same exact error than @noresources  whatever I try to install.
I do have git installed on my computer (1.8.4.2).
My path : `/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/local/git/bin:/usr/texbin`
Thanks for your help !

**Comment by danielecassese** [comment]
Hi all,

same here, I have just updated homebrew today on OS X 10.6.8 and I have the same error every time I try brew install something.
How can I fix this?

**Comment by happypandaface** [comment]
I guess when brew runs it has a different path.
This seemed to fix it:
I downloaded and installed this:
https://code.google.com/p/git-osx-installer/downloads/detail?name=git-1.8.4.2-intel-universal-snow-leopard.dmg&can=2&q=
and then did this:
$ ln -s /usr/local/git/bin/git /usr/local/bin/git
dunno how you'd actually fix it with brew without this hack. I'm thinking that the way brew loads the PATH should be changed.
I'm still getting Xcode errors (not sure how to get a free version of Xcode on snow leopard) but the fact that I don't get this nil error leads me to believe that my hacky fix worked.

**Comment by danielecassese** [comment]
hi happypanda ;)

you can find Xcode 3.2.6 for free on the apple developer centre.
I had some trouble in installing it, but after updating Software Installer it worked fine.
hope this helps

**Comment by DomT4** [comment]
We're actively looking into the error thrown here. Bear with us. It looks like the `formula.rb` line is indeed problematic (Good sleuthing @matt-hayden).

**Comment by mistydemeo** [comment]
Should be fixed by 0f200c507d59ddd302d4704a89cd48f99d001371. I recognize this doesn't help users who can't safely `brew update` though!
