### ISSUE TITLE
FontForge.app not symlinked.

### ISSUE THREAD

**Issue by jiegec** [Homebrew/homebrew#43200]
There is a FontForge.app here: /usr/local/Cellar/fontforge/20150612/share/fontforge/osx/FontForge.app/
But it is not symlinked via brew linkapps.

**Comment by dunn** [comment]
`brew linkapps` only recognizes app bundles installed directly into the `preifx` (in this case, `/usr/local/Cellar/fontforge/20150612`). Would you be willing to open a pull request to fix the install location?  Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have any questions!

**Comment by DomT4** [comment]
We no longer create a functional `.app`; It relies on X11 support via Cairo & Pango and we no longer support that configuration. It isn't functional at all, we just don't remove the dead bundle. If you want the FontForge GUI you should use [the Cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/fontforge.rb).
