### ISSUE TITLE
Suggestion: brew should give "Already up-to-date" message on "brew upgrade pkg" and not an "Error:"

### ISSUE THREAD

**Issue by edrozenberg** [Homebrew/homebrew#43209]
Currently, if I "brew upgrade pkg", if pkg is already up to date brew gives an error, for example:

    brew upgrade python

    Error: python 2.7.10_2 already installed

Since there is no real problem, instead of a warning shouldn't there just be a message like:

    Already up-to-date (python 2.7.10_2)

I'm calling brew upgrade from a script and it would be nice if the user didn't get an error showing up for trying to upgrade an already up to date package.

**Comment by edrozenberg** [comment]
For now I'll do the extra step of looking for the package name in "brew outdated" and only it's there, then try to run brew upgrade on it. Maybe that's the intended approach anyway?

**Comment by mikemcquaid** [comment]
> For now I'll do the extra step of looking for the package name in "brew outdated" and only if it's there, then run brew upgrade on it. Maybe that's the intended approach anyway?

It is, yep. I think most maintainers agree that it'd be better to update things to do it the way you suggest but because most scripts rely on the previous behaviour we can't change it now :sob: Sorry!
