### ISSUE TITLE
pipes.sh does not work with system bash

### ISSUE THREAD

**Issue by belak** [Homebrew/homebrew#43208]
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/pipes-sh.rb

https://github.com/pipeseroni/pipes.sh#requirements

The version installed for me is GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)

It works just fine with the homebrew bash, so should that be a dependency?

**Comment by dunn** [comment]
Yeah, looks like it.  If you feel like opening a pull request to take care of this, we'd be grateful! Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions.

**Comment by DomT4** [comment]
Closing in favour of #43231 (Thanks!).
