### ISSUE TITLE
cmake failed to build on 10.11

### ISSUE THREAD

**Issue by zx8** [Homebrew/homebrew#43204]
Full `gist-logs` [here](https://gist.github.com/anonymous/2fa3dca034c1f22bc856) - the initial failure seems to occur on [this line](https://gist.github.com/anonymous/2fa3dca034c1f22bc856/revisions#diff-78b77a41b8ac7f5c8e3047676ac75400R142).

**Comment by zx8** [comment]
Related issues: https://github.com/Homebrew/homebrew/issues/20461 & https://github.com/Homebrew/homebrew/issues/20464?

**Comment by aw1621107** [comment]
Hmmm... cmake 3.3.0 and HEAD installed fine on my machine. Testing 3.3.1 now...

**Comment by aw1621107** [comment]
Sorry for the delay, couldn't get to the computer after I last commented for a while. 

3.3.1 brewed fine on my computer, also running 10.11

**Comment by zx8** [comment]
Strange. What version of Xcode are you using?

**Comment by DomT4** [comment]
No problems here on 10.11 - Latest 7.0 Beta CLT/Xcode installed.

**Comment by zx8** [comment]
Right, this may very well be a case of PEBCAK then.

To debug further, I manually downloaded the cmake-3.3.1 source, ran `./bootstrap && make` it and an error appeared that doesn't seem to show up in the `gist-logs` output:

```
ld: warning: ignoring file libcmsys_c.a, file was built for archive which is not the architecture being linked (x86_64): libcmsys_c.a
```

Any ideas?

**Comment by zx8** [comment]
Ok, sorry guys, looks like it was completely my fault. Tracked this down to a rogue symlink in `/usr/local/bin`:

`/usr/local/bin/ar -> /usr/local/bin/gar -> ../Cellar/binutils/2.25.1/bin/gar`

I removed the symlink and everything's now working as expected.

With that said, I still don't know how the symlink was created in the first place and `brew doctor` didn't pick it up. Think it's worth adding adding a test to `brew doctor` to prevent something like this in future?

**Comment by DomT4** [comment]
Ah, these things happen. It's likely you either created the symlink at some point, or another piece of software did that for you.

It's difficult to check for those things in `brew doctor` because resolving every symlink in each prefix `brew` uses to see whether they resolve back to an unexpected Cellar path would be a very expensive (in terms of speed) mechanism, and probably require a whitelist of some kind. We'd certainly review a PR on a workable solution though.

**Comment by zx8** [comment]
What do you think of introducing a new like `brew doctor --aggressive`, similar to the `git-gc` argument? i.e.

```
 --aggressive
     Usually git gc runs very quickly while providing good disk space utilization and performance. This option will cause git gc to more aggressively
     optimize the repository at the expense of taking much more time. The effects of this optimization are persistent, so this option only needs to be
     used occasionally; every few hundred changesets or so.
```

Happy to open another PR to discuss options there, but I think there'd certainly be some value in introducing such an option -- this issue being a perfect example. Prior to raising it, I spent a few days trying to debug it on my own and, when I consider what I had to go through to finally figure it out, running an extra command that performs more thorough checks at the expense of having to wait a little longer seems like a reasonable tradeoff to me.

**Comment by zx8** [comment]
@mikemcquaid @DomT4 @mistydemeo @bfontaine - any thoughts on my previous comment before I invest the time into it?

**Comment by mikemcquaid** [comment]
@zx8 I'm open to reviewing a PR but I can't promise we'd include it. Probably `--strict` would be preferable but it'd depend very much on reliability and performance if we could accept this.
