### ISSUE TITLE
Autodetecting version from tag is obscure

### ISSUE THREAD

**Issue by inwit-info** [Homebrew/homebrew#43226]
Hi!
I have a couple of command line tools which were initially targeted for debian users, so I distribute them in the debian packages and have the versioning scheme of one (https://www.debian.org/doc/debian-policy/ch-controlfields#s-f-Version). Then I added support for Mac OS and created a small tap. However I got really confused when users reported problems with updating from version `3.4-1` to `3.4-2`. For the homebrew tap I have those versions as git tags `v3.4-1` and `v3.4-2` respectively. And the error was:
`Error: devtools/tap/executer 3.4 already installed`

After some investigation I figured out where the problem came from.
There is a RegExp here (https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/version.rb#L176) which extracts version number from git tag option parameter, and it silently ignores anything besides digits and dots. So if I have a formula with `url 'http://somewhere', :tag => 'v3.4-1'` the version for this formula would be `3.4`.

That is a bit confusing, so I propose couple of less confusing scenarios:
1. Document version format and version format for git tags
2. Change regexp to allow more characters
3. Report error or warning if the original tag parameter differs from `v` + the extracted version

Thanks

**Comment by dunn** [comment]
We can definitely do better in terms of documentation.  In your case, it sounds like the fix will be setting the version explicitly, with `version "3.4-1"` below the `url` line.

**Comment by DomT4** [comment]
Yeah, there's a known issue in handling versions which end with `-`, particularly things like `1.2-3` and `1.2-beta1` and such. If someone wants to submit a PR that expands the regex understanding without breaking existing versions, we'd certainly review that.

**Comment by inwit-info** [comment]
@dunn Thank you for suggestion, it'll help me for a while
@DomT4 What do you mean by “not breaking existing versions”? Changing the regexp will most probably affect some formulas, like in the example above the version is `3.4` and after change it would be `3.4-1`

**Comment by DomT4** [comment]
> What do you mean by “not breaking existing versions”? 

As in, the new regex would have to not break current Homebrew versions. We have quite a few `3.4-1` style versions written manually, that's fine, but we'd need to make sure the new regex doesn't start picking up things like `3.4.1-darwin` or `3.4.1-beta1` (As `3.4.1-1`) from existing formulae and changing those to include the undesired parts after `-`.

**Comment by Moisan** [comment]
I've been looking at the test code and the current HEAD seems to cover all those cases. Should this issue be closed or is there something else left to do here?

**Comment by mikemcquaid** [comment]
Yeh, closing this out for now.
