### ISSUE TITLE
ios-webkit-debug-proxy failed to build on Ubuntu 15.04

### ISSUE THREAD

**Issue by moorehcs** [Homebrew/homebrew#43235]
https://gist.github.com/anonymous/c593be7af12be7b20599

Attempting to use Linux Brew as an alternative to apt-get in order to install ios-webkit-debug-proxy.

First time posting, I hope that the gist link provided above will be enough information, and that I'm following the correct troubleshooting procedures. If not, however, please let me know what other information you need and I will promptly follow up.

**Comment by mikemcquaid** [comment]
You need to report this to Linuxbrew themselves rather than Homebrew, sorry!
