### ISSUE TITLE
brew update yields "Error: undefined method `link_overwrite'"

### ISSUE THREAD

**Issue by jaytaylor** [Homebrew/homebrew#43233]
$ brew update
    Error: undefined method `link_overwrite' for #<Class:0x007fa3513f1640>
    Please report this bug:
        https://git.io/brew-troubleshooting
    /usr/local/Library/Formula/glib-networking.rb:23:in `<class:GlibNetworking>'
    /usr/local/Library/Formula/glib-networking.rb:1:in `load_formula'
    /usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
    /usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
    /usr/local/Library/Homebrew/formulary.rb:78:in `load_file'
    /usr/local/Library/Homebrew/formulary.rb:69:in `klass'
    /usr/local/Library/Homebrew/formulary.rb:65:in `get_formula'
    /usr/local/Library/Homebrew/formulary.rb:174:in `factory'
    /usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
    /usr/local/Library/Homebrew/cmd/update.rb:191:in `each_line'
    /usr/local/Library/Homebrew/cmd/update.rb:191:in `report'
    /usr/local/Library/Homebrew/cmd/update.rb:25:in `update'
    /usr/local/Library/brew.rb:127:in `<main>'

Just reporting the error as requested by the CLI output.

**Comment by DomT4** [comment]
Do you have `HOMEBREW_DEVELOPER` exported?

**Comment by jaytaylor** [comment]
Negatory.

**Comment by cannyboy** [comment]
same issue here. 0.9.5

**Comment by DomT4** [comment]
It seems this is a one-time bug for people who updated Homebrew at a specific commit point, and consequently a hole not many people should fall into.

Normally this error message would only be exposed if you have `HOMEBREW_DEVELOPER` exported, but it's perfectly safe to ignore and you shouldn't see it on future `brew update`s. Sorry about that.
