### ISSUE TITLE
10.10 linking failed

### ISSUE THREAD

**Issue by mdelmans** [Homebrew/homebrew#43230]
I made symlinks of /usr/local/Cellar/coin/3.1.3/Frameworks/SoQt.framework and /usr/local/Cellar/coin/3.1.3/Frameworks/Inventor.framework to /Library/Frameworks

I then do: g++ xxx.cpp -framework Inventor -framework SoQt -o xxx followed by ./xxx and get:

dyld: Library not loaded: /usr/local/opt/coin/Frameworks/Inventor.framework/Versions/C/Libraries/Inventor
  Referenced from: /Users/md/ownCloud/c++/cointest/./xxx
  Reason: image not found
Trace/BPT trap: 5

**Comment by mikemcquaid** [comment]
Sorry, this doesn't appear to be a Homebrew issue.

**Comment by mdelmans** [comment]
It kind of is. If you install Coin manually the above works just fine.
