### ISSUE TITLE
Add bash-it (new formula)

### ISSUE THREAD

**Issue by Zearin** [Homebrew/homebrew#43266]
Last time I did a lot of work (“a lot” _for me_, due to my low skill level with Ruby and Homebrew formulae) to create a new formula and make a Pull Request, and it was rejected because it was deemed “too unknown”.  So, this time, I’m creating an issue first, to ask whether a PR would be accepted if I created one.

----

I’d like to request the formula [`bash-it`](https://github.com/Bash-it/bash-it) be added to Homebrew.  

I don’t think it’s super-famous; however, it’s an active project, has a respectable community of contributors, offers some powerful enhancements to bash.  

If you’ve heard of [Brett Terpstra](http://brettterpstra.com) (@ttscoff on GitHub), he recommended it to me when I asked a question in one of his repos.  He’s well known for a handful of podcasts he (co-)hosts, so his endorsement further enhances awareness of bash-it.

----

If I opened a PR for bash-it, would it be accepted?

**Comment by mikemcquaid** [comment]
It looks notable enough. I guess we'd need to work out the installation so we don't put `install.sh` in `bin` (as it's too general a name). What happens to your Bash shell if you e.g. `brew uninstall bash-it` while it's still sourced and open a new Terminal? Thanks!

**Comment by DomT4** [comment]
Will review a PR on this if one is submitting, with Mike's comments in mind.
