### ISSUE TITLE
Pipeable brew commands

### ISSUE THREAD

**Issue by Zearin** [Homebrew/homebrew#43268]
I wanted to read the descriptions of all formula related to bash.  So, naturally, I tried the following:

```bash
$ brew search "/bash/" | brew info
```

But `brew info` ignored the piped input.  It acted as if I had simply typed it alone, without any arguments.

----

This is just one use case I happened to have a few moments ago.  But I think that formula should be pipeable between brew commands wherever possible.  

I’d like to request that formula be pipeable between brew commands wherever they can.

----

I’m not familiar with Ruby (I can stumble through the simple stuff), so I acknowledge this request might imply a lot of work.  I’m not sure.  

That said, what do you think on a _conceptual_ level?  What do you think, Homebrew devs?  

The ability to pipe formula from the output of one Homebrew command to another…think of it! :)

**Comment by xu-cheng** [comment]
What you need is 

    $ brew search "/bash/" | xargs brew info

**Comment by Zearin** [comment]
> What you need is
> 
> $ brew search "/bash/" | xargs brew info

Thank you!  I will use this.  (Thanks also for such a speedy reply!)

However, although you told me how to accomplish what I set out to do, you didn’t answer my question:

> That said, what do you think on a _conceptual_ level?

As I said, I will use your solution.  But I would argue that it is not as intuitive as `brew search "/bash/" | brew info`.  The latter is more direct, and more closely resembles the day-to-day expectations of working in the Terminal.  

Can you reopen this issue?  I would like to hear what many developers think about this (as opposed to just the first one to answer).

**Comment by mikemcquaid** [comment]
I don't think we can implement this for all our commands really and I think using `xargs` is a better solution that many other Unix tools that don't read from `stdin` will work with.

**Comment by xu-cheng** [comment]
Sorry, but that is how arguments are passed in the UNIX world. And most of important is that brew is designed to not read stdin.

**Comment by Zearin** [comment]
> I don't think we can implement this for all our commands really

Agreed.  Still, I wasn’t suggesting this for literally _all_ commands—just wherever it makes sense.

**Comment by Zearin** [comment]
> Sorry, but that is how arguments are passed in the UNIX world. 

I have been working in the Terminal every day for 5+ years now, and I don’t think I have ever used `xargs`.  I don’t mean to say that `xargs` is anything negative.  It’s just that while I’ve known of its existence for a long time, I simply never think to use it when I’m working in the Terminal.  Does that imply something negative about me?  (I don’t know.  But I’ve been pretty productive these past several years.)

Hmm…I’m extremely used to “piping stuff around”, which is a little different from “how arguments are passed”.  

* Is one of these preferable to the other?  (Perhaps only in certain cases?)

> And most of important is that brew is designed to not read stdin.

Oh…I didn’t know that!  

* Why is Homebrew designed like this?  Is this mentioned in the docs somewhere?

**Comment by bfontaine** [comment]
The UNIX philosophy is to have small tools that do one thing and do it well. `xargs` is a perfect fit here, I don’t think we need to replicate an existing functionality.

**Comment by Zearin** [comment]
> The UNIX philosophy is to have small tools that do one thing and do it well. xargs is a perfect fit here, I don’t think we need to replicate an existing functionality.

Right.  I understand that philosophy.  But surely, piping is part of the UNIX philosophy too…right?

**Comment by mikemcquaid** [comment]
It's part of it but it's not expected that all tools support it (hence `xargs`).
