### ISSUE TITLE
After installation of php55-phalcon on OS X 10.11, phalcon package doesn't appear in phpinfo()

### ISSUE THREAD

**Issue by mstoelzle** [Homebrew/homebrew#43264]
Hi,
After some difficulties (outdated xCode, https://github.com/Homebrew/homebrew-php/issues/1941) I was finally able to install php55-phalcon on my OS X 10.11. I then added "extension=phalcon.so" to my php.ini and restarted the apache server. But still I can't find the phalcon package in phpinfo and if I put echo "hallo" in my IndexController nothing is put out. Thanks for your help. Here is my gist of the installation:
https://gist.github.com/9e919c840b09b907337a
<img width="1440" alt="screen shot 2015-08-25 at 12 55 02" src="https://cloud.githubusercontent.com/assets/2360366/9465016/03552ac2-4b29-11e5-87b1-f18ecd0ccb8b.png">

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/homebrew-php#2023
