### ISSUE TITLE
vim formula broken; vim_7.4.712.orig.tar.gz does not exist

### ISSUE THREAD

**Issue by kscott** [Homebrew/homebrew#43279]
The repository on mirror.kernel.org no longer contains the requested file for building vim. The formula now fails with messages:

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "vim"

**Comment by DomT4** [comment]
Fixed via https://github.com/Homebrew/homebrew/commit/a51a7c1d03426b26faaf4d9e4b97ec3db47647e1.
