### ISSUE TITLE
Problems installing wine; issue with installing the fontconfig

### ISSUE THREAD

**Issue by bmertens3** [Homebrew/homebrew#43278]
$brew install wine
==> Installing dependencies for wine: fontconfig, libtiff, gd, libgphoto2, little-cms2, jasper, libicns, makedepend, openssl, sane-backends
==> Installing wine dependency: fontconfig
==> Downloading http://fontconfig.org/release/fontconfig-2.11.1.tar.bz2
Already downloaded: /Library/Caches/Homebrew/fontconfig-2.11.1.tar.bz2
==> Patching
patching file fc-cache/fc-cache.c
patching file fontconfig/fontconfig.h
patching file src/fccache.c
patching file src/fcdir.c
patching file src/fcfs.c
patching file src/fcint.h
patching file src/fcpat.c
==> ./configure --disable-silent-rules --with-add-fonts=/System/Library/Fonts,/Library/Fonts,~/Library/Fonts --prefix=/usr/local/Cellar/fontconfig/2.11.1 --localstatedir=/usr/local/
==> make install RUN_FC_CACHE_TEST=false
make[3]: *** Waiting for unfinished jobs....
 /usr/bin/install -c -m 644 10-autohint.conf 10-no-sub-pixel.conf 10-scale-bitmap-fonts.conf 10-sub-pixel-bgr.conf 10-sub-pixel-rgb.conf 10-sub-pixel-vbgr.conf 10-sub-pixel-vrgb.conf 10-unhinted.conf 11-lcdfilter-default.conf 11-lcdfilter-legacy.conf 11-lcdfilter-light.conf 20-unhint-small-vera.conf 25-unhint-nonlatin.conf 30-urw-aliases.conf 30-metric-aliases.conf 40-nonlatin.conf 45-latin.conf 49-sansserif.conf 50-user.conf 51-local.conf 60-latin.conf 65-fonts-persian.conf 65-khmer.conf 65-nonlatin.conf 69-unifont.conf 70-no-bitmaps.conf 70-yes-bitmaps.conf 80-delicious.conf 90-synthetic.conf '/usr/local/Cellar/fontconfig/2.11.1/share/fontconfig/conf.avail'
make[2]: *** [install-am] Error 2
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting

**Comment by bfontaine** [comment]
As https://git.io/brew-troubleshooting says, please post the output of `brew gist-logs wine`.

**Comment by bmertens3** [comment]
$ brew gist-logs wine.
Error: No available formula for wine

**Comment by dunn** [comment]
Did you accidentally add the period, and run `brew gist-logs wine.` instead of `brew gist-logs wine`?

**Comment by bmertens3** [comment]
when i run, without "."
$brew gist-logs wine
Error: No logs.

**Comment by DomT4** [comment]
Try `brew install fontconfig --universal` and if that fails do `brew gist-logs fontconfig`

**Comment by bmertens3** [comment]
not sure what the site is saying. sorry
$ brew gist-logs fontconfig
https://gist.github.com/8c84d10f4b27727cda1a

**Comment by DomT4** [comment]
```
mkdir: /usr/local/etc/fonts: Permission denied
mkdir: /usr/local/etc/fonts: No such file or directory
make[3]: *** [install-configDATA] Error 1
make[3]: *** Waiting for unfinished jobs....
```

You don't have permission over `/usr/local/etc` apparently. Try `sudo chown -R $(whoami) /usr/local` and then try `brew install fontconfig --universal` again afterwards.

**Comment by bmertens3** [comment]
got the fontconfig to be built now. rerunning the install wine

**Comment by DomT4** [comment]
Glad everything's working again :smiley:.
