### ISSUE TITLE
Mistyping tap name creates local tap directory anyway

### ISSUE THREAD

**Issue by symbiat** [Homebrew/homebrew#43280]
I was trying to tap `caskroom/cask` but mistyped it as `vaskroom/cask` and hit ENTER before I realized my mistake. But looking under `/usr/local/Library/Taps` I see that a `vaskroom` folder was created anyway.

**Comment by bfontaine** [comment]
Seems to be a `git` issue:

```
$ git clone git@github.com:a/b/c foo/bar/qux
Cloning into 'foo/bar/qux'...
fatal: remote error:
  a/b/c is not a valid repository name
  Email support@github.com for help
$ ls foo/
bar
```

It doesn’t remove the parent directories it created for the [clone](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/tap.rb#L28) operation.

**Comment by mikemcquaid** [comment]
We could make the `tap` command check for the existence of the directory before running `git clone` and remove it afterwards if it fails. @symbiat Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
