### ISSUE TITLE
fftw failed to build on mac os

### ISSUE THREAD

**Issue by cumt2009** [Homebrew/homebrew#43288]
I compiled exemple c file 
And, this is error report….

Undefined symbols for architecture x86_64:
Undefined symbols for architecture x86_64:
  "_fftw_cleanup_threads", referenced from:
      _cfft2_finalize in Mmpilrmodel.o
  "_fftw_init_threads", referenced from:
      _cfft2_init in Mmpilrmodel.o
  "_fftw_plan_with_nthreads", referenced from:
      _cfft2_init in Mmpilrmodel.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status

mpicc -o sfmpilrmodel -framework Accelerate -fopenmp Mmpilrmodel.o  -L/usr/local/lib -lfftw3f -lrsf++ -lrsfpwd -lrsf -lm -lmx -lgomp

Why occurred this error?

**Comment by bfontaine** [comment]
Please post the output of `brew gist-logs fftw`.

**Comment by DomT4** [comment]
Presuming resolved via lack of response, but please let us know if you're seeing any issues still. Thanks!
