### ISSUE TITLE
Make sandbox failure output more obvious what failed

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/homebrew#43295]
e.g. http://bot.brew.sh/job/Homebrew%20Pull%20Requests/32193/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_nyancat/

It be nice if rather/as well as writing to a log if it just wrote to stdout.

**Comment by xu-cheng** [comment]
You mean output `sandbox.test.log` to stdout?

**Comment by mikemcquaid** [comment]
Yeh I think so and just reduce some of the sandbox-outputted spam.

**Comment by xu-cheng** [comment]
I think we can close this now.

**Comment by mikemcquaid** [comment]
:+1:

**Comment by mikemcquaid** [comment]
Thanks for this :heart:
