### ISSUE TITLE
0644 permissions on ~/.aws/credentials?

### ISSUE THREAD

**Issue by uchi-mata** [Homebrew/homebrew#43296]
Hi,

I just installed the latest awscli version from brew and did a "aws configure", which resulted in a ~/.aws/credentials file with 0644 permissions. When I install the same version via pip, the permissions are correctly set to 0600 by "aws configure".

Can anyone reproduce this behavior/have an idea why this is happening? Is any more information required? I'm on OSX 10.10.5, default umask is 0022.

Thanks,
Matthias

**Comment by tdsmith** [comment]
Can't repro:
```
tim@rocketman:~$ brew install awscli
...
tim@rocketman:~$ ls -l .aws
ls: .aws: No such file or directory
tim@rocketman:~$ aws configure
AWS Access Key ID [None]: asdf
AWS Secret Access Key [None]: asdf
Default region name [None]: asdf
Default output format [None]: asdf
tim@rocketman:~$ ls -l .aws
total 16
drwxr-xr-x   4 tim  staff   136 Aug 26 10:46 .
drwxr-xr-x+ 96 tim  staff  3264 Aug 26 10:46 ..
-rw-------   1 tim  staff    38 Aug 26 10:46 config
-rw-------   1 tim  staff    64 Aug 26 10:46 credentials
tim@rocketman:~$ umask
0022
```

Is it possible you had an older version installed somewhere earlier in PATH that pip replaced?

**Comment by uchi-mata** [comment]
Hi,

thanks for trying. Difficult question, I'd say no and I feel like I tried using awscli before installing it, but I cannot find any output in my terminal history that proves so.

Will try to reproduce, I guess it can be closed until then!

Thx & best,
Matthias

**Comment by tdsmith** [comment]
Okay, let us know.
