### ISSUE TITLE
ode formula doesn't include drawstuff

### ISSUE THREAD

**Issue by sheim** [Homebrew/homebrew#43312]
Hi, I noticed the formula for installing ode (Open Dynamics Engine) doesn't include any options to build with drawstuff, a visualization tool commonly packaged with ODE. Is there any reason not to have this?
Would be great if this could be added imho, as some people have done: https://gist.github.com/yuya-oc/3208758

If there's a specific reason not to, is there a recommended alternative way of doing this? And why?

**Comment by bfontaine** [comment]
Do you mind making a pull-request?

**Comment by sheim** [comment]
I'll see. The one I linked isn't mine, and I've never done this before.  
In the [ODE installation instructions](http://ode-wiki.org/wiki/index.php?title=Manual:_Install_and_Use), it specifically says to use --disable-demos (which also removes drawStuff), and I'm looking into why, since it doesn't actually seem necessary. It might just be obsolete instructions, I'll keep you posted.

**Comment by bfontaine** [comment]
Thanks!

**Comment by DomT4** [comment]
According to the Wiki we'll need to add an optional `x11` dependency if we enable the demos:

> DrawStuff requires OpenGL, and X11 on Mac OS X

**Comment by sheim** [comment]
I can install from source manually, without the flag (currently included in homebrew) `"--disable-demos"`, and it works. It build drawstuff as well as a demos folder.

I modified the brew formula and removed the `"--disable demos"` by default, and also tried adding `"--with-demos"`, and it seems to run the correct configuration step (brew install runs ./configure --with-demos), but not drawstuff and demo folders do not appear anywhere in /usr/local/Cellar/ (they should be in the ode/0.13.1/ folder, if it's the same as installing manually).

I'm a bit stumped at this point.

**Comment by DomT4** [comment]
Do you have XQuartz installed out of curiosity?

It's unlikely the upstream Makefile installs demos by default, most don't. You'd need to do something like `pkgshare.install "/path/to/demos"`

**Comment by sheim** [comment]
I do have XQuartz installed.

I downloaded directly from the same [bitbucket url](https://bitbucket.org/odedevs/ode/src) that is saved in the brew formula.

**Comment by mikemcquaid** [comment]
@sheim Might be worth creating a pull request as it's easier for us to help you debug the code then.

**Comment by sheim** [comment]
I'll get back to you soon, sorry, I'm at a conf in China, hard to get
through the firewall...
