### ISSUE TITLE
brew install --HEAD ghostscript fails

### ISSUE THREAD

**Issue by jerzyk** [Homebrew/homebrew#43329]
command fails with an error:
```
make: *** No rule to make target `src/png.h', needed by `obj/xpspng.o'.  Stop.
make: *** Waiting for unfinished jobs....
```

I suppose this is a mixup in using system vs local libpng (autogen.sh finds system wide libpng):
```
checking for local zlib source... yes
checking for local png library source... no
checking for png_create_write_struct in -lpng... yes
checking png.h usability... yes
checking png.h presence... yes
```

Logs:
     /.../Library/Logs/Homebrew/ghostscript/01.autogen.sh
     /.../Library/Logs/Homebrew/ghostscript/01.autogen.sh.cc
     /.../Library/Logs/Homebrew/ghostscript/02.make
     /.../Library/Logs/Homebrew/ghostscript/02.make.cc
     /.../Library/Logs/Homebrew/ghostscript/config.log

uploaded to: https://gist.github.com/a0cfb6f3ab1bd4e3429b

**Comment by dunn** [comment]
Good catch.  Letting it build the vendored libpng (instead of shunting it out of the way here https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ghostscript.rb#L69) avoids this, but I'll see if there's a fix that allows us to keep using our libpng.

**Comment by dunn** [comment]
So the short-term fix is `inreplace "xps/xps.mak", "$(PNGSRCDIR)$(D)png.h", ""`.

The long-term fix is getting the GS build process to officially allow system versions of libpng etc., instead of the vendored ones.  I don't know how long that will take, so I'm leaning towards letting it have its vendored deps instead of patching Makefiles.

**Comment by dunn** [comment]
If we do go the patchy route, might as well do zlib too: https://github.com/Homebrew/homebrew/compare/Homebrew:master...dunn:ghostscript

And considering we're already pushing the vendored files around, this isn't much more invasive.

**Comment by jerzyk** [comment]
but, there may be an issue when brewed version will not be supported (yet) by gs

**Comment by dunn** [comment]
Forgot to close this via commit; should be fixed now!
