### ISSUE TITLE
pdfgrep: enable unac support in formula

### ISSUE THREAD

**Issue by Yann-R** [Homebrew/homebrew#43327]
Hello,
Currently the pdfgrep version installed from homebrew refuses the --unac option (documented in man):
```
pdfgrep: unrecognized option '--unac'
```
Indeed the man of pdfgrep mentions:
> --unac
>           Remove accents and ligatures from both the search pattern and and the PDF [...]
>           This option is experimental and only available if pdfgrep is compiled with unac support.

I'm not very specialist with formulae nor with pdfgrep & unac compilation, but it's true I can't find anything in the current formula to enable this unac support when compiling/installing pdfgrep.

Would it be possibilite to update the formula to add this support?
At least as optionnal?

**Comment by DomT4** [comment]
From the wording there it looks like it isn't necessarily expected to be compiled in by default, so we'd accept a PR that added an optional `unac` dependency and passed whatever necessary configure flags appropriate.

Fancy submitting a PR on this? You can find the [Formula Cookbook here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md) & [Tips on submitting Homebrew PRs here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md).

**Comment by DomT4** [comment]
Will review a PR if one is submitted.
