### ISSUE TITLE
FontForge installs but does not run on Mavericks

### ISSUE THREAD

**Issue by cbertelli** [Homebrew/homebrew#43321]
The first attempt to install it gives a warning:
"Warning: fontforge dependency gettext was built with a different C++ standard library (libc++ from clang). This may cause problems at runtime."
Launching fontforge from command line starts python and waits
So I supposed it had something to do with the warning and reinstalled it with:
brew install fontforge --with-extra-tools --with-giflib --with-libspiro
but with the same result.
Copying the app folder to /Applications shows a Contents/Resources/opt/local folder with an etc folder only, so when launching 
/Applications/FontForge.app/Contents/MacOS/FontForge
it answers with:
PKGBASE: /Applications/FontForge.app
/Applications/FontForge.app/Contents/MacOS/FontForge: line 135: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge: No such file or directory

**Comment by DomT4** [comment]
The app was an accidental relic. It hasn't worked as intended for a long time, and the FontForge GUI has been unavailable via Homebrew for a couple months now. If you want GUI/App, I recommend `brew install caskroom/cask/fontforge`. You can read more about the Cask [here](https://github.com/caskroom/homebrew-cask).
