### ISSUE TITLE
Julia failed to build on 10.9.5

### ISSUE THREAD

**Issue by joeguinness** [Homebrew/homebrew#43337]
https://gist.github.com/anonymous/a519fa135fb2be54ba12

Julia 0.4 had been installed on my computer with homebrew. During troubleshooting on how to get the most recent build of julia, I ran 

brew rm julia
brew install --HEAD julia

which gave me a warning:
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

I had some software installed on my computer a few months ago using macports, so I went and uninstalled macports using these instructions:
https://guide.macports.org/chunked/installing.macports.uninstalling.html

Then I tried again to install julia with "brew install --HEAD julia", which still did not work. The gist link above is for this most recent install.

**Comment by dunn** [comment]
This issue was moved to staticfloat/homebrew-julia#167
