### ISSUE TITLE
Error: undefined method `link _overwrite` ....

### ISSUE THREAD

**Issue by stavinopolis** [Homebrew/homebrew#43342]
![image](https://cloud.githubusercontent.com/assets/8081825/9537504/f8ce4842-4ced-11e5-9ff4-80fdf711a009.png)

**Comment by DomT4** [comment]
Was a one time harmless issue. You won't see it again. Thanks for reporting it!

**Comment by stavinopolis** [comment]
cool yeah it's fixed!
