### ISSUE TITLE
clucene Formula Not Working

### ISSUE THREAD

**Issue by systerm** [Homebrew/homebrew#43359]
Hi,
The formula for clucene is no longer working. It gets stuck at 
```Downloading https://trac.macports.org/export/126047/trunk/dports/devel/clucene/files/patch-src-shared-CLucene-LuceneThreads.h.diff```
My homebrew is up-to-date.
OS: Yosemite (10.10.5)
Complete terminal output:
```shell
brew install clucene
==> Downloading https://downloads.sourceforge.net/project/clucene/clucene-core-unstable/2.3/clucene-core-2.3.3.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/clucene-2.3.3.4.tar.gz
==> Downloading https://trac.macports.org/export/126047/trunk/dports/devel/clucene/files/patch-src-shared-CLucene-LuceneThreads.h.diff
```
Thanks.

**Comment by bfontaine** [comment]
Can confirm from here too; trac.macports.org seems to have some issues.
