### ISSUE TITLE
integrate sidebar patch to mutt

### ISSUE THREAD

**Issue by meduz** [Homebrew/homebrew#43357]
in mutt, the sidebar is a useful addition to visualize different folders. it is not available in the current formula but would be easy to add as an option.

there are quite a few repositories integrating the sidebar patch in mutt:

https://github.com/kevwil/homebrew-patches/blob/master/mutt.rb
https://github.com/mrtazz/homebrew-misc/blob/master/mutt.rb

should I create a PR or is there any reason for not integrating it?
cheers,
Laurent

**Comment by bfontaine** [comment]
From the [formula source](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/mutt.rb):

> Note: Mutt has a large number of non-upstream patches available for
> it, some of which conflict with each other. These patches are also
> not kept up-to-date when new versions of mutt (occasionally) come
> out.  To reduce Homebrew's maintenance burden, new patches are not
> being accepted for this formula. Mutt power-users are encouraged to
> copy the formula and modify it locally, adding needed patches.

**Comment by DomT4** [comment]
See #41638 and #36328. Unless upstream show some interest in maintaining it, we're going to have to pass. Thanks for asking though!
