### ISSUE TITLE
mkvtoolnix still install ruby even ruby version >= 1.9 is available

### ISSUE THREAD

**Issue by sikachu** [Homebrew/homebrew#43366]
I tried to investigate this, but still unable to come to a conclusion on what went wrong.

Basically, `mkvtoolnix` [uses](https://github.com/Homebrew/homebrew/blob/fb16fe0f5494e64b7fe59d16c08edc449cc8204e/Library/Formula/mkvtoolnix.rb#L24) [`RubyRequirement`](https://github.com/Homebrew/homebrew/blob/40c591629f393dfbdde69dda14393070b3e1f40d/Library/Homebrew/requirements/ruby_requirement.rb#L11) to require at least Ruby 1.9. OS X 10.10 ships with Ruby 2.0, which means that the requirement should already been satisfied. However, that's not the case since it still tries to install `ruby` package.

I tried to debug this by replacing [line 12-15 of `RubyRequirement`](https://github.com/Homebrew/homebrew/blob/40c591629f393dfbdde69dda14393070b3e1f40d/Library/Homebrew/requirements/ruby_requirement.rb#L11) to return true, but that did not stop the installation from happening. I also tried to prints out the last line and can validate that it returns true.

I tried to create another formula and `depends_on :ruby => "1.9"` appears to be working as expected. I'm not sure why it does not work with `mkvtoolnix`, as it works fine with `heroku-toolbelt` as we..

```
[master][/usr/local] brew --version
0.9.5 (git revision fb16f; last commit 2015-08-28)
[master][/usr/local] ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
[master][/usr/local] which ruby
/Users/sikachu/.rvm/rubies/ruby-2.2.3/bin/ruby
[master][/usr/local] /usr/bin/ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

Thank you.

**Comment by sikachu** [comment]
More log to show you what happen:

```
[~] brew uninstall ruby
Error: No such keg: /usr/local/Cellar/ruby
[~] ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
[~] brew install mkvtoolnix
==> Installing dependencies for mkvtoolnix: ruby
==> Installing mkvtoolnix dependency: ruby
==> Downloading https://homebrew.bintray.com/bottles/ruby-2.2.3.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/ruby-2.2.3.yosemite.bottle.tar.gz
==> Pouring ruby-2.2.3.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/ruby/2.2.3: 1080 files, 20M
==> Installing mkvtoolnix
==> Downloading https://homebrew.bintray.com/bottles/mkvtoolnix-8.3.0.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/mkvtoolnix-8.3.0.yosemite.bottle.tar.gz
==> Pouring mkvtoolnix-8.3.0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/mkvtoolnix/8.3.0: 39 files, 12M
[~]
```

**Comment by DomT4** [comment]
Pretty sure this is expected, for now, but can reproduce:

```
which ruby
/usr/local/var/rbenv/shims/ruby
ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
brew install -v mkvtoolnix
==> Installing mkvtoolnix dependency: ruby
```

This is because the bottles are presumed to always be built against the `default_formula`, although in this case and others, there's no actual linkage there because the system satisfies the requirement just fine. See #41595 for discussion on this a bit more.

**Comment by mistydemeo** [comment]
If memory serves, mkvtoolnix is only used by the mkvtoolnix buildsystem - not by mkvtoolnix itself. If we make this a buildtime dep then we wouldn't need to check at all when pouring the bottle.

**Comment by mistydemeo** [comment]
Updated to no longer require Ruby to pour the bottle.

**Comment by sikachu** [comment]
That was fast. Works as expected. Thank you!
