### ISSUE TITLE
How can I ensure that a cached copy of the source of another formula is available?

### ISSUE THREAD

**Issue by CamJN** [Homebrew/homebrew#43379]
I'm putting together a formula and need to have a copy of the source used to build one of the deps, is there a way for me to look up where to grab a copy (preferably from cache but falling back on downloading)?

Specifically racer for rust completion needs a copy of the rust compiler's source.

**Comment by bfontaine** [comment]
You can’t rely on that, you’ll have to add it as a `resource`.

**Comment by CamJN** [comment]
Would something like the following be acceptable?
```
  resource "additional_files" do
    url Formula['rust'].stable.url
    sha256 Formula['rust'].stable.checksum.hexdigest
  end
```

**Comment by xu-cheng** [comment]
No. We don't like to use interal API like this. You should just copy the URL and checksum.

**Comment by CamJN** [comment]
But a literal url wouldn't account for their package being out of date... and it's probably bad form to update it on them.

**Comment by xu-cheng** [comment]
The form you used won't account for outdated either. 

On the contrary, by updating URL manually, we can a) verify build is not broken b) regenerate bottle files. 

If you want formula to be treated as outdated, you need to apply `revision` when you update URL.

**Comment by CamJN** [comment]
Another question, how do I stop homebrew from running install_name_tool?

**Comment by mikemcquaid** [comment]
> Another question, how do I stop homebrew from running install_name_tool?

You can't, it's necessary.

**Comment by CamJN** [comment]
Not for the contents of the rust src dir, those just need to be present none of the executables need to work. Indeed the reason I asked is because install_name_tool doesn't work and errors out when trying to run on them.

**Comment by tdsmith** [comment]
One option is not to install the executables.

**Comment by CamJN** [comment]
Ok so in order to comply with not getting the correct version of rust from the api, how can I force rust to a specific version from the depends_on call?

And just to be clear, the version of the rust src code needs to match the version of rust installed so that completion is correct. So if I can't check where rust got it's source I have to force rust to match the version I hard code.

**Comment by mikemcquaid** [comment]
You can't force a version with `depends_on`, unfortunately, without using the `homebrew/versions` tap.

**Comment by CamJN** [comment]
Ok so let me understand, I can hard code a version that is likely to be wrong, and that's acceptable but making an effort to get the right version isn't?

That's swell.

**Comment by mikemcquaid** [comment]
Please read our Code of Conduct: https://github.com/Homebrew/homebrew/blob/master/CODEOFCONDUCT.md

We're volunteers providing you with free help in our spare time.

**Comment by CamJN** [comment]
Fair enough that was uncalled for. I'm just frustrated with how much the rules get in the way of making a best effort to make a formula that would work.
