### ISSUE TITLE
mbed TLS 2.0 not compatible with PolarSSL 1.x

### ISSUE THREAD

**Issue by tomyun** [Homebrew/homebrew#43395]
Recent formula update of `polarssl` to 2.0 (#42432) breaks existing dependents on 1.x more seriously; `include` directory renamed from `polarssl` to `mbedtls`. Rebranding to `mbedtls` since 1.3.8 was mostly about linkage issue (#39983), but it's now becoming an issue of entire source-level changes.

I think we'd better leave `polarssl` as a separate package for 1.3.8, which is the last version under its name, for maximum compatibility. Many existing apps not ready for migration would stay happy with that. Meanwhile, I guess, any developers willing to adopt `lib` change after 1.3.8 would be probably also capable of handling `include` changes for 2.0, so we could rather safely keep `mbedtls` up to date.

**Comment by dunn** [comment]
A formula in versions named something like `polarssl13` sounds like a good idea, unless there are a lot of core formula that need it.

**Comment by mikemcquaid** [comment]
> A formula in versions named something like polarssl13 sounds like a good idea, unless there are a lot of core formula that need it.

Agreed :+1:

**Comment by tomyun** [comment]
I like the naming!

Note that `polarssl13` should actually point to [1.3.9](https://tls.mbed.org/tech-updates/releases/polarssl-1.3.9-released), not 1.3.8.

Maybe we can also consider `polarssl12` as they still provide maintenance releases; [1.2.15](https://tls.mbed.org/tech-updates/releases/polarssl-1.2.15-and-mbedtls-1.3.12-released) just out this month. If we really want to care, `mbedtls13` for 1.3.12, which was released together, could be also in.

**Comment by DomT4** [comment]
Yes, `mbedtls` smashed the compatibility with previous versions. There's nothing in Homebrew core which had a mandatory or even recommended PolarSSL/Mbedtls dependency, so it didn't matter a huge amount.

Feel free to submit a PR to Homebrew/Versions for the 1.3.x branch. If there comes a time when upstream declare it no longer supported in any capacity and a major security issue hits that branch, it may get pulled, but I'm happy to keep it to that point.
