### ISSUE TITLE
cask (emacs package management tool) dependancy issue

### ISSUE THREAD

**Issue by noaham** [Homebrew/homebrew#43400]
The formula for [cask](https://github.com/cask/cask), a project management tool for emacs (not to be confused with homebrew-cask) recently changed to include a dependancy for emacs. See c7e7ce42ed55020ca22fa4649c05b7e8d71bc6c0.

I use the [Yamamoto Mitsuharu port](https://github.com/railwaycat/mirror-emacs-mac) of emacs and not the homebrew version of emacs.

However when trying to update cask with homebrew it now wants to install the hombrew version of emacs. How do I get around this?

**Comment by dunn** [comment]
It should only install our Emacs if the one in your `$PATH` isn't new enough. Is the versioning on that port different?

**Comment by DomT4** [comment]
It might be because there's a bottle now, and when you install a bottle it will install the `default_formula`. If it's not needed at compile time you could tweak the dep to `:run`, theoretically.

**Comment by dunn** [comment]
@noaham, does `brew install --build-from-source cask` also try to install Homebrew Emacs?

**Comment by noaham** [comment]
It is emacs 24.5 so should be new enough. @dunn, that worked (i.e. it did not try and install emacs). I assume when it updates it won't try and install emacs? Thanks!

**Comment by dunn** [comment]
Once #43413 is merged, yes!
