### ISSUE TITLE
git failed to build on 10.10.4

### ISSUE THREAD

**Issue by mcabrams** [Homebrew/homebrew#43419]
[link to gist](https://gist.github.com/anonymous/1a514babf1d56a2779af)

Fails on fresh mac. Any help appreciated.

**Comment by bfontaine** [comment]
From the gist:

```
Last commit: in the future
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/homebrew/Cellar
```

How did you install Homebrew?

**Comment by mcabrams** [comment]
@bfontaine via ansible - specificially via this ansible playbook: https://github.com/geerlingguy/ansible-role-homebrew/blob/master/tasks/main.yml

**Comment by mikemcquaid** [comment]
@mcabrams It looks like you've customised the install path.
