### ISSUE TITLE
brew test gst-python fails

### ISSUE THREAD

**Issue by mike-lawrence** [Homebrew/homebrew#43420]
MacBookPro11,5 running OS 10.10.5. My install script:
```
sudo rm -rf /usr/local
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor
export PATH=/usr/local/bin:$PATH
echo "export PATH=/usr/local/bin:$PATH" >> ~/.bash_profile
brew install python
pip install --upgrade pip setuptools
export PYTHONPATH=/usr/local/lib/python2.7/site-packages
echo "export PYTHONPATH=/usr/local/lib/python2.7/site-packages" > ~/.bash_profile
brew install gst-python
```
Now, running `brew test gst-python` yields:
```
Error: gst-python: failed
execution expired
/usr/local/Library/Homebrew/formula.rb:1277:in `wait'
/usr/local/Library/Homebrew/formula.rb:1277:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1252:in `open'
/usr/local/Library/Homebrew/formula.rb:1252:in `system'
/usr/local/Library/Formula/gst-python.rb:26:in `block in <class:GstPython>'
/usr/local/Library/Homebrew/formula.rb:1163:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1159:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```
Also, running `gst-inspect-1.0` yields the error:
```
ERROR: Caught a segmentation fault while loading plugin file:
/usr/local/lib/gstreamer-1.0/libgstpythonplugin.dylib

Please either:
- remove it and restart.
- run with --gst-disable-segtrap --gst-disable-registry-fork and debug.
```
Running `gst-inspect-1.0 --gst-disable-segtrap --gst-disable-registry-fork`  yields this following crash report: https://gist.github.com/mike-lawrence/580006da5d6d55a9fc85

Here's the output when I first move `/usr/local/lib/gstreamer-1.0/libgstpythonplugin.dylib` then run `gst-inspect-1.0`: https://gist.github.com/mike-lawrence/3e91ade75cfa82d0e8b1

And, in python itself, running `import gst` yields a "no module named gst" error.

**Comment by bfontaine** [comment]
Yes you can see the error with `brew test --verbose gst-python`:

```
Testing gst-python
==> gst-inspect-1.0 python

ERROR: Caught a segmentation fault while loading plugin file:
/usr/local/lib/gstreamer-1.0/libgstpythonplugin.dylib

Please either:
- remove it and restart.
- run with --gst-disable-segtrap --gst-disable-registry-fork and debug.
```

It then hangs.

**Comment by tdsmith** [comment]
> And, in python itself, running import gst yields a "no module named gst" error.

Are you sure this is intended to provide that module?

**Comment by tdsmith** [comment]
Can someone paste build logs from gst-python? I don't immediately see this on my system. `brew gist-logs gst-python`

**Comment by tdsmith** [comment]
Nevermind; I see this with a bottled gst-python but not built from source. The bottle is missing files from site-packages (though none of them provide a `gst` module).

**Comment by mike-lawrence** [comment]
Happens for both bottled and source-built for me.


On Tuesday, September 1, 2015, tim smith <notifications@github.com> wrote:

> Nevermind; I see this with a bottled gst-python but not built from source.
> The bottle is missing files from site-packages (though none of them provide
> a gst module).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Homebrew/homebrew/issues/43420#issuecomment-136598120>
> .
>


-- 

--
Mike Lawrence
Graduate Student
Department of Psychology & Neuroscience
Dalhousie University

~ Certainty is (possibly) folly ~

**Comment by tdsmith** [comment]
Oops, closed accidentally. If the new bottle doesn't fix this for you, can you paste build logs, please? This doesn't replicate on the bot.

**Comment by mike-lawrence** [comment]
Re-installed forcing bottles throughout and now `brew test gst-python`
passes.

Also, discovered that the `import gst` call is a relic from gst-python-010;
as of 1.0, the proper call is `from gi.repository import Gst`.

Thanks for your help!
