### ISSUE TITLE
Can't pipe `brew doctor`. It doesn't write to stdout? 

### ISSUE THREAD

**Issue by kevzettler** [Homebrew/homebrew#43426]
So I have a bunch of junk when I run `brew doctor`
I was hoping I could pipe this to `grep` to pull out the file paths and then pipe to `xargs` and delete everything. It looks like `brew doctor` does not pipe the expected output to stdout though. See below

```
Kevins-MBP: kevzettler$ brew doctor >> ~/Desktop/brew.text
Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/gif_lib.h
    /usr/local/include/pixman-1/pixman-version.h
    /usr/local/include/pixman-1/pixman.h
Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libfreetype.la
    /usr/local/lib/libgif.la
    /usr/local/lib/libpixman-1.la
Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/freetype2.pc
    /usr/local/lib/pkgconfig/pixman-1.pc
Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libfreetype.a
    /usr/local/lib/libgif.a
    /usr/local/lib/libpixman-1.a
```

The actual captured output

```
Kevins-MBP: kevzettler$ cat ~/Desktop/brew.text
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!
```

This maybe by design. I don't know the back story. It's not expected behavior and not unix friendly.

**Comment by dunn** [comment]
The "errors" caught by `brew doctor` are printed to stderr: https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/doctor.rb#L1310

I acknowledge your point; arguably only errors thrown by the `doctor` command itself should be sent to stderr, so I wouldn't oppose a PR to change this behavior.  But other maintainers might feel differently.

And you can always use `brew doctor 2>&1` to capture everything.

**Comment by bfontaine** [comment]
> arguably only errors occurring in the execution of the `doctor` command itself should be sent to stderr

I’m :+1: on that.

**Comment by mikemcquaid** [comment]
I don't know what I think about making it so you can just pipe these paths to delete them all. Some may be important and doing that doesn't seem like a good idea.

**Comment by bfontaine** [comment]
Yeah piping this to delete `grep`-ed files seems like a dangerous idea.

**Comment by kevzettler** [comment]
@mikemcquaid @bfontaine I feel thats really up to the user. I happen to be careless. Maybe someone else would want to pipe it to grep and do other manipulations on the output. I've had the output be substantially long at times. The point of this issue is that it doesn't seem to be familiar expected unix output behavior. Discussing how people use unix pipes is off topic.

**Comment by mikemcquaid** [comment]
I don't think we can really change this at this stage, unfortunately, lest we break scripts that rely on the previous behaviour. Sorry!
