### ISSUE TITLE
ifuse failed to build on 10.10.5

### ISSUE THREAD

**Issue by minarikg** [Homebrew/homebrew#43440]
Hi,

I've tried to install "ifuse" but got I get error that there is missing formula, hence I created one: 
brew create https://github.com/libimobiledevice/ifuse/archive/1.1.3.tar.gz
Then I receive error captured in the next outputs:
https://gist.github.com/minarikg/3d097a23c797278e8377

Which contains:
The output from HOMEBREW_MAKE_JOBS=1 brew install -v <formula name> 2>&1
+
The output from brew config and brew doctor
+
~/Library/Logs/Homebrew/ifuse/01.configure

Thanks!

Kind regards,
Gabriel

**Comment by DomT4** [comment]
The formula you're looking for has relocated, a while ago now. You can install it via `brew install homebrew/fuse/ifuse` :)

**Comment by minarikg** [comment]
Thx

måndag 31 augusti 2015 skrev Dominyk Tiller <notifications@github.com>:
