### ISSUE TITLE
This doesn't work, it isn't actually doing md5 

### ISSUE THREAD

**Issue by eject-it** [Homebrew/homebrew#43443]
It seems to only measure the size. I duplicated a file and swapped bits. Size absolutely identical. The md5 shouldn't be (obviously). Fdupes does report them as identical. Running the md5 that comes with OSX / BSD reports different hashes.
I don't know why the formula here doesn't simply call the md5 of OSX its just a translation in the formula (replace md5sum of source with md5 of target osx should work).
But after trying to figure out since when this brew isn't actually implementing the programme I stumbled over so many discussions about replacing md5 (which the md5 man page itself suggests) that I didn't even bother looking any further.

I guess it is the nature of the Homebrew project that potentially dangerous software like this is translated without testing. This thing in its current implementation will delete two sets of archive files compressed to be split at a certain size if they are named identically. And whatever else there is that has the same size and name.

In any case this programme has become sort of a legacy item even when it is actually working and no one dares to replace it. Since the job at hand is principally simple I have now solved this just with the command line and some apple script. Which of course doesn't need homebrew so it doesn't matter.

**Comment by DomT4** [comment]
What are you actually asking here? Are you reporting a bug in the `fdupes` package?

**Comment by eject-it** [comment]
what is the mechanism of telling the maintainer (?) that it is not implemented in a working fashion.

As you can tell I never posted before although my account isn't that fresh. I have no idea how interact with this project. I just leach stuff, ideas and know how. But here I noticed that this thing won't do md5, which it says it does. And the reason is most probably that it is just pushed trough the compiler without even reading the make file.

**Comment by mistydemeo** [comment]
This is the right place to report it. Can you please explain:

* Which package you're having an issue with (fdupes?)
* Provide a step-by-step reproduction case so we can test

**Comment by tdsmith** [comment]
Please let us know if we can help with anything.
