### ISSUE TITLE
Apache download strategy - mirrors asjson no longer works

### ISSUE THREAD

**Issue by jlaxson** [Homebrew/homebrew#43476]
When installing a source package sourced from apache.org, the Apache download strategy appends `&asjson=1` to the url in order to discover an appropriate mirror.  This appears to no longer work on the Apache side.  

For example, https://www.apache.org/dyn/closer.cgi?path=apr/apr-1.5.2.tar.bz2&asjson=1 gives the normal HTML page and not json mirror information.  This results in builds failing to install:

```
$ brew reinstall apr --build-from-source
==> Reinstalling apr
==> Downloading https://www.apache.org/dyn/closer.cgi?path=apr/apr-1.5.2.tar.bz2
Error: Failed to download resource "apr"
Download failed: Couldn't determine mirror, try again later.
```

**Comment by tdsmith** [comment]
Looks like this was resolved by Apache.
