### ISSUE TITLE
error: cannot open .git/FETCH_HEAD: Permission denied

### ISSUE THREAD

**Issue by paulehoffman** [Homebrew/homebrew#43471]
Followed all the pre-bug-report instructions, made sure I have the latest command line tools. I even tried removing linode (the tap listed here), but that didn't affect the problem.

Clues appreciated.
```
# brew update
error: cannot open .git/FETCH_HEAD: Permission denied

Error: Failed to update tap: linode/cli
Already up-to-date.
# brew doctor
Your system is ready to brew.
# brew update
error: cannot open .git/FETCH_HEAD: Permission denied

Error: Failed to update tap: linode/cli
Already up-to-date.
# brew gist-logs linode
Error: No available formula for linode
# brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 91af15e6368d5eefa1425d07245482ca06d3c8f9
Last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.10.5-x86_64
Xcode: N/A
CLT: 6.4.0.0.1.1435007323
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.3/bin/ruby
Java: 1.8.0_45
```

**Comment by tzudot** [comment]
By the look of the `#` symbol at the beginning, it seems you are running as `root`. It's not advised to run Homebrew as `root` user or using `sudo`. 

Anyway, you could check for the permissions on the file, 
```cmd
ls -l /usr/local/Library/Taps/linode/cli/.git/FETCH_HEAD
```

and 

```cmd
ls -l /usr/local/.git/FETCH_HEAD
```

On `git update`, `.git/FETCH_HEAD` is updated with the latest commit, which is failing your case.

**Comment by paulehoffman** [comment]
On 1 Sep 2015, at 10:50, tzudot wrote:

> By the look of the `#` symbol at the beginning, it seems you are 
> running as `root`. It's not advised to run Homebrew as `root` user or 
> using `sudo`.

I am not; that's just my prompt symbol for the normal user.

>
> Anyway, you could check for the permissions on the file,
> ```cmd
> ls -l /usr/local/Library/Taps/linode/cli/.git/FETCH_HEAD
> ```
>
> and
>
> ```cmd
> ls -l /usr/local/.git/FETCH_HEAD
> ```

# ls -l /usr/local/Library/Taps/linode/cli/.git/FETCH_HEAD
ls: /usr/local/Library/Taps/linode/cli/.git/FETCH_HEAD: No such file or 
directory
# ls -l /usr/local/.git/FETCH_HEAD
-rw-r--r--@ 1 paul.hoffman  admin  98 Sep  1 08:10 
/usr/local/.git/FETCH_HEAD
# ls -l /usr/local/Library/Taps/linode/
total 0
drwxr-xr-x@ 4 paul.hoffman  admin  136 Jul  2 22:58 homebrew-cli
# ls -l /usr/local/Library/Taps/linode/cli/
ls: /usr/local/Library/Taps/linode/cli/: No such file or directory

> On `git update`, `.git/FETCH_HEAD` is updated with the latest commit, 
> which is failing your case.

Yes, that seems correct.

Does this indicate that the "linode" package is broken, in that it has a 
directory called "homebrew-cli" but not one called "cli"?

--Paul Hoffman

**Comment by tzudot** [comment]
You're right, the sub-directory within `linode` is `home-brew-cli`.

```cmd
ls -l /usr/local/Library/Taps/linode/homebrew-cli/.git/FETCH_HEAD
-rw-r--r--  1 tzudot  staff   100B Sep  1 14:03 /usr/local/Library/Taps/linode/homebrew-cli/.git/FETCH_HEAD
```
Check for `FETCH_HEAD` within `.git` there.

**Comment by paulehoffman** [comment]
On 1 Sep 2015, at 11:08, tzudot wrote:

> You're right, the sub-directory within `linode` is `home-brew-cli`.
>
> ```cmd
> ls -l /usr/local/Library/Taps/linode/homebrew-cli/.git/FETCH_HEAD
> -rw-r--r--  1 tzudot  staff   100B Sep  1 14:03 
> /usr/local/Library/Taps/linode/homebrew-cli/.git/FETCH_HEAD
> ```
> Check for `FETCH_HEAD` within `.git` there.

```
# ls -l /usr/local/Library/Taps/linode/homebrew-cli/.git/FETCH_HEAD
-rw-r--r--@ 1 paul  admin  100 Jun 30 18:00 
/usr/local/Library/Taps/linode/homebrew-cli/.git/FETCH_HEAD
```

In that, I note that the owner is "paul" instead of "paul.hoffman"; the 
latter should be the owner.

It seems that "brew uninstall --force" doesn't give messages when it 
fails:

```
# pwd
/usr/local/Library/Taps
# ls -la
total 0
drwxr-xr-x@  3 paul.hoffman  admin  102 Jul  2 22:50 .
drwxr-xr-x@ 11 paul.hoffman  admin  374 Aug 31 18:57 ..
drwxr-xr-x@  3 paul.hoffman  admin  102 Jul  2 22:50 linode
# brew uninstall --force linode
# ls -la
total 0
drwxr-xr-x@  3 paul.hoffman  admin  102 Jul  2 22:50 .
drwxr-xr-x@ 11 paul.hoffman  admin  374 Aug 31 18:57 ..
drwxr-xr-x@  3 paul.hoffman  admin  102 Jul  2 22:50 linode
```

Once I forcefully removed /usr/local/Library/Taps/linode with "rm -f", 
the error in this thread disappeared.

Should I close this bug and start a new one for brew uninstall --force?

--Paul Hoffman

**Comment by tzudot** [comment]
That's weird. Just to be sure, run the command to reapply correct permissions within Homebrew directory,

```
sudo chown -R $(whoami):admin /usr/local && sudo chmod -R g+rwx /usr/local
```
Note - As per Homebrew recommended process in [permissions issue](https://github.com/Homebrew/homebrew/issues/43301)

Basically, make it writable by the current user / group.

**Comment by tzudot** [comment]
You may close this issue, if it has been resolved.

**Comment by DavidSewell** [comment]
Interesting... I just found this thread because I was having the same problem. Turned out two files in one of the /usr/local/Library/Taps/homebrew .git directories was owned by root. I belive that goes back to accidentally running "sudo brew update" one time. (Hard to get Macports usage out of one's head.)

**Comment by georgiana-gligor** [comment]
My problem was fixed only after executing

```bash
sudo chown -R $(whoami):admin /usr/local/Library/Taps/*/**/.git
```

**Comment by ORESoftware** [comment]
thanks to @tzudot and @georgiana-gligor  - what is "$(whoami):admin" doing? specifically the :admin part?

**Comment by DavidSewell** [comment]
$(whoami) returns the output of the "whoami" command, i.e. your username. In the chown command, you optionally specify group ownership after a colon, so georgiana-gligor's command assigns the current user as the owner and "admin" as the group recursively to all files and directories in the directory.
