### ISSUE TITLE
osxfuse: switch to stable 2.8.0 to avoid unreleased current 2.6.0

### ISSUE THREAD

**Issue by Yann-R** [Homebrew/homebrew#43504]
Hello,
I don't know what decided to choose the version 2.6.0 (tag apparently existing in source indeed) as stable version in homebrew formula although this version was never officially release as stable version for user downloads on https://osxfuse.github.io/

But now (from last June) the official stable release is 2.8.0 and could be preferred in our stable formula?
(Or maybe is there other difficulties and dependencies with the rest of osxfuse-related formulae that I don't imagine?) 
Moreover it could avoid demands like https://github.com/Homebrew/homebrew/issues/41678

**Comment by dunn** [comment]
Would you like to try opening a PR? Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions!

**Comment by giffels** [comment]
I did https://github.com/Homebrew/homebrew/pull/44493. I am on El Capitan, so could not build it before submitting. Let see how the buildbot does.

Cheers,
Manuel

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew/commit/d4f9fcca6498e8c2a13f1dcf5f08cfecc9c20ea0.
