### ISSUE TITLE
open-ssl post-install does not complete successfully on CentOS v6.4

### ISSUE THREAD

**Issue by marcora** [Homebrew/homebrew#43511]
https://gist.github.com/de244f3f2dda6e72afce

==> Downloading http://curl.haxx.se/ca/cacert.pem
Already downloaded: /hpc/users/marcoe02/.cache/Homebrew/openssl--cacert-1.0.2d.pem
Error: SHA256 mismatch
Expected: ccde89388cac12c5d3c8e68b9458add7e22b849371818dfdd240c994d6193641
Actual: ca4ebe0c2dc6f61faa037d4e71ae3ac0f9bde5b1da4fa2e4a6e50592a620bcd5
Archive: /hpc/users/marcoe02/.cache/Homebrew/openssl--cacert-1.0.2d.pem
To retry an incomplete download, remove the file above.

Removing the file as indicated does not solve the issue.

**Comment by tzudot** [comment]
Better report this issue at [Homebrew/linuxbrew](https://github.com/Homebrew/linuxbrew/issues).

**Comment by tdsmith** [comment]
This issue was moved to Homebrew/linuxbrew#531
