### ISSUE TITLE
"brew uninstall --force" doesn't give messages when it fails

### ISSUE THREAD

**Issue by paulehoffman** [Homebrew/homebrew#43512]
It seems that "brew uninstall --force" doesn't give messages when it fails. For example, if there is a file in a package that cannot be removed due to permissions errors, "brew uninstall --force" will not report a problem, but detritus of the package is left behind.

**Comment by tzudot** [comment]
Unable to reproduce this issue. I have tried the following,
```
$ sudo chown -R root:wheel /usr/local/Cellar/zlib

$ brew uninstall zlib
Uninstalling /usr/local/Cellar/zlib/1.2.8... (9 files, 392K)
Error: Permission denied - /usr/local/Cellar/zlib/1.2.8/ChangeLog

$ brew uninstall --force zlib
Uninstalling zlib... (9 files, 392K)
Error: Permission denied - /usr/local/Cellar/zlib/1.2.8/ChangeLog

$ sudo chown -R root:wheel /usr/local/Cellar/zlib/1.2.8/share
$ brew uninstall --force zlib
Uninstalling zlib... (9 files, 388K)
Error: Permission denied - /usr/local/Cellar/zlib/1.2.8/share/man/man3/zlib.3
```

Also, tried changing permissions for just one file within the `keg`,
```
$ sudo chown -R root:wheel /usr/local/Cellar/zlib/1.2.8/INSTALL_RECEIPT.json

$ brew uninstall --force zlib
Uninstalling zlib... (9 files, 392K)

$ ls -l /usr/local/Cellar/zlib/1.2.8
ls: /usr/local/Cellar/zlib/1.2.8: No such file or directory
```
Does not leave any files behind.

Please share steps to reproduce this issue.

**Comment by paulehoffman** [comment]
Hrm. Trying to reproduce the issue that caused this is failing, so it may be linked to some other bitrot I had. I'll close this until I can get a reproducible example.
