### ISSUE TITLE
Unable to install newt - trac.macports.com down

### ISSUE THREAD

**Issue by ktaragorn** [Homebrew/homebrew#43528]
I need to update `byobu` right now, since I am facing issues with it after updating to python 2.7.10. Updating that requires me to update `newt` and updating `newt` hits https://trac.macports.org/export/132914/trunk/dports/devel/libnewt/files/patch-Makefile.in.diff which has been down for atleast the last one day and seems like this has happened before according to this site -  http://comments.gmane.org/gmane.os.apple.macports.user/37211

It is odd that brew is depending on macports like this, and effort should be made to make this process more reliable..

**Comment by dunn** [comment]
Trac has been down for almost a week now.  If you can find a copy of the patch (maybe from a Google cache), we'd be happy to replace it with a gist-ed version.

**Comment by ktaragorn** [comment]
Hey, I dont know enough to understand what is this or how it is used, but a google got me https://github.com/dstrctrng/macports/blob/master/rsync.macports.org/release/tarballs/ports/devel/libnewt/files/patch-Makefile.in.diff . I am not sure if this is a static file or changes with every update..

**Comment by ktaragorn** [comment]
Tried replacing.. didnt work.

**Comment by ktaragorn** [comment]
Found ftp://ftp.ca.freebsd.org/MacPorts/release/ports/devel/libnewt/files/patch-Makefile.in.diff gonna make a pr

**Comment by dunn** [comment]
Awesome, thanks!

I didn't know Trac has a history of outages—we should try to move away from using patches hosted there.

**Comment by ktaragorn** [comment]
PR made. http://www.filewatcher.com/m/patch-Makefile.in.diff.1393-0.html gave me the list of alternatives, in case this mirror also goes down in the future..

**Comment by dunn** [comment]
Nice, I didn't know about FileWatcher.

**Comment by ktaragorn** [comment]
I didnt either.. Google is great :P . Very handy in this case.. considering I still dont know what this patch is or how often it changes.. All the other results were 2-4 years ago and likely wrong.
