### ISSUE TITLE
Issues with brew install gcc49 --with-fortran [libgcc_ext.10.4.dylib] Error 127

### ISSUE THREAD

**Issue by amitvirat** [Homebrew/homebrew#43531]
I am facing issues with brew install for gcc49 with fortran since R packages are failing. While doing install I am getting error messages as follows:

/bin/sh: lipo: command not found
make[3]: *** [libgcc_ext.10.4.dylib] Error 127
make[2]: *** [all-stage1-target-libgcc] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2

Ran brew update: All good
Ran brew doctor: No issues

gist logs are available at: https://gist.github.com/4506b82cc0636b324aa2

Can someone please help?

**Comment by amitvirat** [comment]
Update: I tried it again after reinstalling Xcode 6.4 but still the same error

**Comment by dunn** [comment]
This issue was moved to Homebrew/homebrew-versions#957
