### ISSUE TITLE
Split npm from node package

### ISSUE THREAD

**Issue by davepwsmith** [Homebrew/homebrew#43548]
This would allow both node and npm to be kept properly up to date using just brew. node could depend on npm. I have no real knowledge of what this would break or how difficult it would be, so it's just a suggestion and I won't be offended if it's summarily dismissed!

**Comment by DomT4** [comment]
Not going to happen, I'm afraid. We did this previously and it ended up breaking both Node & `npm` pretty regularly, and the end result was that Node/`npm` to this day are hesitant to tell people to use `brew` to install the software (We've fixed those problems, but the perception remains).

Various discussions in #3762, #22408, #27479, #28075.
