### ISSUE TITLE
Request: flynn.io

### ISSUE THREAD

**Issue by rstacruz** [Homebrew/homebrew#43554]
Flynn.io comes with a command-line utility to manage your flynn server clusters.

I don't really know how to make a formula out of this, it requires fetching a URL with a specific User-Agent, which returns a gzip-compressed stream of the executable bin.

**Comment by bfontaine** [comment]
We don’t really do formula requests; but we’ll consider a pull-request :smile:

**Comment by bfontaine** [comment]
We don’t really do formula requests but we’d consider a pull-request :smile: 

This should help and I’m happy to help you with any question you might have: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

**Comment by rstacruz** [comment]
Right on, but if anyone can point me to resources on how to get this implemented I'd be happy to do it :) Their installation procedure is a little unconventional.

**Comment by bfontaine** [comment]
@rstacruz You can initialize the formula template with `brew create https://github.com/flynn/flynn/archive/v20150903.0.tar.gz`
Then we’ll have to dig in upstream’s installation instructions :)
