### ISSUE TITLE
pam_yubico won't build on El Capitan

### ISSUE THREAD

**Issue by dlo** [Homebrew/homebrew#43565]
Build log: https://gist.github.com/dlo/9978c98c326a5c095946

Thanks!

**Comment by DomT4** [comment]
Does this reproduce with the GM/Xcode GM? I can't repro here.

**Comment by dlo** [comment]
Will try again and report back...

**Comment by dlo** [comment]
Yep. I can still reproduce.

```
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Downloading https://github.com/Yubico/yubico-pam/archive/2.19.tar.gz
Already downloaded: /Library/Caches/Homebrew/pam_yubico-2.19.tar.gz
==> autoreconf -fvi
==> ./configure --prefix=/usr/local/Cellar/pam_yubico/2.19 --with-libyubikey-pre
==> make install
make[1]: *** [ykpamcfg.1] Error 1
make[1]: *** Waiting for unfinished jobs....
a2x: ERROR: "xmllint" --nonet --noout --valid "/private/tmp/pam_yubico20150913-14935-17gsh94/yubico-pam-2.19/pam_yubico.8.xml" returned non-zero exit status 4
make[1]: *** [pam_yubico.8] Error 1
make: *** [install-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
pam_yubico won't build on El Capitan https://github.com/Homebrew/homebrew/issues/43565
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
```

**Comment by DomT4** [comment]
Can you try `brew reinstall asciidoc` and then try again?

**Comment by dlo** [comment]
Just tried. Same error. I believe passing `--no-xmllint` to a2x will fix this.

**Comment by senadaruc** [comment]
Dears,

I am having the same issue under 10.11 GM build, is there ay workaround?


Thanks.

**Comment by dlo** [comment]
@senadaruc Yep...if it's the same issue I'm having, you'll need to edit the Makefile to add --no-xmllint to the a2x command.

**Comment by senadaruc** [comment]
Hi dlo,

Thanks for the kind help and i made this changes but i still have the same error!!

SUFFIXES = .1.txt .1 .8.txt .8
.1.txt.1:
	$(A2X) --no-xmllint --format=manpage -a revdate="Version $(VERSION)" $<

.8.txt.8:
	$(A2X) --no-xmllint --format=manpage -a revdate="Version $(VERSION)" $<

Can you please share yours Makefile?

Thanks.

**Comment by senadaruc** [comment]
Dears,

Finally this solution worked for me.

SUFFIXES = .1.txt .1 .8.txt .8
.1.txt.1:
	$(A2X) --format=manpage --no-xmllint -a revdate="Version $(VERSION)" $<

.8.txt.8:
	$(A2X) --format=manpage --no-xmllint -a revdate="Version $(VERSION)" $<



Thanks.

**Comment by senadaruc** [comment]
Workaround for brew install "pam_yubico" in MAC OS X 10.11 El Capitan

Step by-step guide.

1.Find the downloaded archive file in /Library/Caches/Homebrew/pam_yubico-2.19.tar.gz

2.Extract the archive and "cd yubico-pam-2.19"

3.Edit the file "Makefile.am"  and change line no:77 and 80 with the following lines:
line 77:   $(A2X) --format=manpage --no-xmllint -a revdate="Version $(VERSION)" $<
line 80:   $(A2X) --format=manpage --no-xmllint -a revdate="Version $(VERSION)" $<

4.run the following command inside the folder "yubico-pam-2.19" 

autoreconf -fvi

./configure –prefix=/usr/local/Cellar/pam_yubico/2.19 –with-libyubikey-prefix=/usr/local/opt/libyubikey –with-libykclient-prefix=/usr/loc

make install

5.verify with "brew list" that installation is successfully.

6. copy the file "pam_yubico.so" to "/usr/local/lib" 

7.Follow the guide here : https://www.yubico.com/wp-content/uploads/2015/04/YubiKey-OSX-Login.pdf

Credits to https://github.com/dlo for the "--no-xmllint " hint.

Thanks.

**Comment by DomT4** [comment]
Can someone talk to upstream about this? I couldn't reproduce but presumably if several people are having issues here I'm just very lucky. If upstream says the proposed change to the `a2x` command is cool with them, we can wrap that into the formula.

**Comment by vdm** [comment]
@senadaruc's instructions worked for me (thanks!), with the following changes:

4. ```./configure --prefix=/usr/local/Cellar/pam_yubico/2.19 --with-libyubikey-prefix=/usr/local/opt/libyubikey --with-libykclient-prefix=/usr/local/opt/ykclient```

6. ```cp .libs/pam_yubico.so /usr/local/lib```

**Comment by klali** [comment]
upstream here..

If I read this correctly the issue here is the xmllint of a2x for the manpages? https://github.com/Yubico/yubico-pam/commit/37f878807358adca5642b8047fb4d10f70e7ab34 went in on september 8, and is in the latest released version (2.20)

**Comment by DomT4** [comment]
@klali Thanks for the reply here! Appreciate that. I opened #44571 to resolve this with the version bump, but apparently the version update now fails on Yosemite and Mavericks (And probably older platforms) whilst passing on El Cap exclusively.

The error is:

```
/bin/sh /private/tmp/pam_yubico20151003-7773-tbn5z7/yubico-pam-2.20/build-aux/missing a2x -L --format=manpage -a revdate="Version 2.20" pam_yubico.8.txt
  CCLD     libpam_util.la
  CCLD     libpam_real.la
  CCLD     ykpamcfg
  CCLD     pam_yubico.la
a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/usr/local/Cellar/asciidoc/8.6.9/etc/asciidoc/docbook-xsl/manpage.xsl" "/private/tmp/pam_yubico20151003-7773-tbn5z7/yubico-pam-2.20/pam_yubico.8.xml" returned non-zero exit status 5
make[1]: *** [pam_yubico.8] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install-recursive] Error 1
```

Any thoughts?

**Comment by klali** [comment]
So looking a tthis now.. is there a reason to not use the "real" distribution tarball (https://developers.yubico.com/yubico-pam/Releases/pam_yubico-2.20.tar.gz)? Then man-pages are pre-built and autotools stuff done..

**Comment by DomT4** [comment]
It looks like the autotools were added way back in https://github.com/Homebrew/homebrew/commit/afcd14a3545f843d4aad69d227b11e092322f466 & have stuck around since. I'll try switching it to the official release.

**Comment by DomT4** [comment]
That seemed to work. Feel free to let us know if you hit any further issues folks, but it passed the CI across 10.11-10.9.

Thank you for the really useful input here @klali. Being able to ditch four build-time dependencies is great.
