### ISSUE TITLE
Migrate glfw3 back to the core

### ISSUE THREAD

**Issue by tomyun** [Homebrew/homebrew#43563]
Seems `glfw3` was moved out to homebrew/versions since it failed to support Snow Leopard (#20626). As far as I understand correctly, the official support is currently down to Mountain Lion and it'll be also moved up to Mavericks when El Capitan comes out. Then I think it'd be fine to move `glfw3` back to the core as `glfw`. There are some new softwares that could be potentially benefitted by having it.

**Comment by mikemcquaid** [comment]
:+1: from me. Feel free to open a PR.

**Comment by DomT4** [comment]
My only concern is that we handle reverse migration pretty terribly. Anything which points to `homebrew/versions/glfw3` in any core tap as a dependency would need fixing.

**Comment by LinusU** [comment]
I would love seeing this as well, hopefully I can take a stab at it and submit a pull request.

**Comment by DomT4** [comment]
Feel free. I'm :-1: on the rename though as that'll break existing installations. You'd also need to check each Homebrew tap for `glfw3` deps and stop them pointing at the Versions tap.
