### ISSUE TITLE
$ brew install https://github.com/WeAreLeka/homebrew-avr.git

### ISSUE THREAD

**Issue by RandyMcMillan** [Homebrew/homebrew#43564]
######################################################################## 100.0%
Error: /Library/Caches/Homebrew/Formula/homebrew-avr.git:4: syntax error, unexpected '<'
<!DOCTYPE html>
 ^
/Library/Caches/Homebrew/Formula/homebrew-avr.git:5: syntax error, unexpected '<'
<html lang="en" class="">
 ^
/Library/Caches/Homebrew/Formula/homebrew-avr.git:5: syntax error, unexpected keyword_class, expecting end-of-input
<html lang="en" class="">
                     ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:22:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:22:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:79:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:134:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:70:in `klass'
/usr/local/Library/Homebrew/formulary.rb:66:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:176:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:18:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:45:in `install'
/usr/local/Library/brew.rb:127:in `<main>'
randymcmillan at new-host-3 in /usr/local/Library/Formula on master*
$

![screen shot 2015-09-03 at 8 47 51 pm](https://cloud.githubusercontent.com/assets/152159/9674294/1c2afb2a-527d-11e5-8efa-bd52c81f8bdd.png)

**Comment by mistydemeo** [comment]
That's not the correct way to install this software; follow [these instructions](https://github.com/WeAreLeka/homebrew-avr#installing-homebrew-avr-formulae).
