### ISSUE TITLE
beginner question

### ISSUE THREAD

**Issue by douglasdeodato** [Homebrew/homebrew#43605]
Hey guys i installed archey, when i get in archey folder i can get apple logo and my system specs, but my question is: how can insert that in my bash profile? and shows all the time when open my terminal?

thank you.

**Comment by DomT4** [comment]
Should be as simple as opening up your `bash_profile` and adding `archey` to the top of that file and then opening a fresh terminal.

**Comment by DomT4** [comment]
The above should work. Let us know if you need any further help :)

**Comment by douglasdeodato** [comment]
thanks, yeah its working now :+1:

**Comment by DomT4** [comment]
Great! Thanks for the feedback :)
