### ISSUE TITLE
Possibility of a Mechanism to Specify Using as Many of a Formula's Dependency's Options as Possible?

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew#43616]
This seems like it could become a very helpful feature by relieving people of the need to do that manually, especially for formulas (like, say, `emacs`, for example) with lots of nested dependencies that all have lots of options.  Perhaps it could read something like `brew install <formula> --with-max-functionality`?  Then again, this would probably turn out to be painful to maintain since it would most likely require some kind of annotation system to tell the option which options add functionality instead of removing it and which options are actually _working_ at the moment…sigh.

**Comment by DomT4** [comment]
As well as the issues you raise in the bottom half, there's also the use case where options/dependencies conflict with each other. I think this has the potential to cause more problems than solutions, sadly.

**Comment by RandomDSdevel** [comment]
As for dealing with conflicting options, maybe some interactivity could solve that?  Then again, _that_ would complicate `brew install`, so so much for that thought.  Ugh…ah, well; it was an interesting idea.  Perhaps we could just leave it here to simmer for a while and see if anybody picks it up and does anything with it?

**Comment by DomT4** [comment]
Homebrew very intentionally doesn't do interactivity; It's bad for automation and doesn't provide a great UX. We're unlikely to let this sit indefinitely, but I'll leave it open for a day or so to let other maintainers contribute to the discussion if they wish to.

**Comment by RandomDSdevel** [comment]
Ah, yes, there is that.  Solving that would probably involve having the dependency-search process detect conflicting options and then prompt the user to specify them in their initial `brew` call before erroring out or something, but this proposal is complicated already, and I'm not (yet) a Ruby programmer, so…'tis a no-go at the moment.  Maybe a way for users to specify options to dependencies in an invocation of `brew install` would be a better solution for this use case?

**Comment by mikemcquaid** [comment]
I think we'll need to pass on this, I'm afraid.

**Comment by RandomDSdevel** [comment]
That's OK; I just thought it would help round that [new dependency implementation](https://github.com/Homebrew/homebrew/milestones/New%20dependency%20implementation) that's being worked on quite nicely.
