### ISSUE TITLE
`brew install gcc --with-java` or `--with-all-languages` Uses `ecj` Instead of Oracle's Official JDK

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew#43613]
I don't mind for now, but it _is_ kind of annoying that I have to download and install _another_ Java compiler when I already _have_ one, if you know what I mean.

**Comment by mistydemeo** [comment]
The `--with-java` option builds GCC's Java compiler; I'm not aware of any ability to integrate GCC with Oracle's JDK.

**Comment by RandomDSdevel** [comment]
@mistydemeo:  Ah, so it's just a completely different implementation, then?  Maybe I can use it for testing if I ever get around to programming in Java, then.

**Comment by mistydemeo** [comment]
Yep, exactly: https://en.wikipedia.org/wiki/GCJ It doesn't seem to be in active development though, unfortunately. :(
