### ISSUE TITLE
Linker errors? ld: symbol not supported for architecture x86_64

### ISSUE THREAD

**Issue by bzcheeseman** [Homebrew/homebrew#43612]
I'm trying to use homebrew to download and build packages like boost, ceres-solver, stuff like that.  What happens is that I will try and compile code, without any special flags ("g++ foo.cpp -o foo -I /usr/local/..." and I've tried clang++ too) and I get this error consistently:

"Undefined symbols for architecture x86_64:
  ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

So I looked around and the solution is to use the -stdlib=libstdc++ flag.  I tried it, and now it gives me errors related to the fact that apple ships an old version of the libstdc++, doesn't get fixed by invoking -std=c++11 or -std=c++14.  It throws up objections to C++11 syntax like the shared_ptr:

```
/usr/local/include/ceres/internal/port.h:62:12: error: no member named
      'shared_ptr' in namespace 'std'
using std::shared_ptr;
      ~~~~~^
...
/usr/local/include/ceres/solver.h:629:15: error: expected member name or ';'
      after declaration specifiers
    shared_ptr<ParameterBlockOrdering> inner_iteration_ordering;
    ~~~~~~~~~~^
5 errors generated.
```

I'd rather not edit the library source code if I don't have to, I feel like that's just way too deep a rabbit hole.

Is there a way to build libraries (with homebrew) that will give the correct linking?  Currently I just "brew install <package>," am I missing something obvious?

I'm on Mac OS X 10.10.5, and brew --config gives this:

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 03ad27453de01adc29cbf941bd29a2dfb54a9960
Last commit: 69 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit ivybridge
OS X: 10.10.5-x86_64
Xcode: 6.4
CLT: 6.4.0.0.1.1435007323
Clang: 6.1 build 602
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: N/A

Running "$ arch" gives: i386,

and "$ clang++ -v" gives: 

Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

I should add that I've tried cleaning out my computer in case there was an old version or something mucking things up.  Everything I've seen says this error is caused by improper linking at build time, but it seems like brew does most of that properly, at least as far as I can tell?

LATER EDIT:  I've installed gcc using brew and tried to compile the library using the g++-5 and the gcc-5 command to avoid clang and I get the same problem when I try to pass the -std=c++11 flag at compile time.  None of these work.

SOLVED:  The linking libraries couldn't be found, all I did was add the path in my compile run and it worked - "$g++ foo.cpp -o foo -I /usr/local/... -l<formula>" with the second flag being a small ell not a big i

**Comment by dunn** [comment]
Glad to hear you solved it! Let us know if anything else comes up.
