### ISSUE TITLE
BuildError#dump fails with HOMEBREW_NO_GITHUB_API=1

### ISSUE THREAD

**Issue by UniqMartin** [Homebrew/homebrew#43618]
For various reasons I prefer to have `HOMEBREW_NO_GITHUB_API=1` in my environment. However, this will always result in the following stack trace when a build fails (and thus a `BuildError` exception is caught and handled in `brew.rb`):

```
/opt/homebrew/Library/Homebrew/exceptions.rb:248:in `dump': undefined method `empty?' for nil:NilClass (NoMethodError)
	from /opt/homebrew/Library/brew.rb:154:in `rescue in <main>'
	from /opt/homebrew/Library/brew.rb:67:in `<main>'
```

I identified the expression `issues.empty?` in `BuildError#dump` as the culprit. `BuildError#issues` calls `BuildError#fetch_issues` which in turn calls `GitHub.issues_for_formula`, `GitHub.issues_matching`, and finally `GitHub.open`. The last one in that list returns `nil` if `HOMEBREW_NO_GITHUB_API=1` is set and thus `nil` is passed all the way back to `BuildError#dump`.

The thing I'm not sure about is how to best solve this issue. Should `BuildError#dump` be more careful? Should the other involved methods avoid to return `nil`? Thanks for looking into this!

**Comment by mikemcquaid** [comment]
Thanks for the report!
