### ISSUE TITLE
`brew install gcc --with-all-languages` Does Not Install GNU's Ada Compiler

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew#43614]
I believe that this is probably due to the fact that, as discussed in issue #25041, the Ada compiler requires a binary version of itself to be available during its bootstrap process.  Perhaps users could be prompted to tap [homebrew-binary](https://github.com/Homebrew/homebrew-binary) for this if and when they add a formula for GNAT upon request (perhaps by me?)

**Comment by mikemcquaid** [comment]
I think this is something that's involved/niche enough if you want it fixed you'll need to submit a pull-request. Could you try and open one? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by RandomDSdevel** [comment]
I'll think about it, but it's actually not very high of a priority for me right now.  I'm not actually an Ada programmer; I just thought that it was odd that Homebrew's GCC formula's `--with-all-languages` option had a comment saying that using it didn't install an Ada compiler.  I might get around to it eventually, though.
