### ISSUE TITLE
Strange line in bashrc

### ISSUE THREAD

**Issue by jacwah** [Homebrew/homebrew#43621]
I haven't used `.bashrc` until today, when I started sourcing it from `.bash_profile`. I found a strange line that seems to try to add bash completion for brew commands. It doesn't fulfill what looks like the intended purpose. I didn't add this line, which leads me to think that it was added by some script when I installed Homebrew originally (~ a year ago).

    source `brew --repository` /Library/Contributions/brew_bash_completion.sh

Below is the output of `help source`.

```
source: source filename [arguments]
    Read and execute commands from FILENAME and return.  The pathnames
    in $PATH are used to find the directory containing FILENAME.  If any
    ARGUMENTS are supplied, they become the positional parameters when
    FILENAME is executed.
```
`source` doesn't make any sense for a directory (`brew --repository` → `/usr/local`). Every time I open a shell an error message is printed: _`-bash: source: /usr/local: is a directory`_.

Maybe the arguments are reversed? That wouldn't make any difference really though, as `/Library/Contributions/brew_bash_completion.sh` doesn't exist.

Was this line added by Homebrew? If yes: what is it meant to do?

*Output of `brew config` and `brew doctor` [here](https://gist.github.com/jacwah/344b2b4f8581cff92461).*

**Comment by mistydemeo** [comment]
This line was not added by Homebrew; Homebrew doesn't touch users' dotfiles, or any other files outside `/usr/local`.

The problem with that line is that a stray space was added; it should be:
```
`brew --repository`/Library/Contributions/brew_bash_completion.sh
```

Which is a path that does exist!
