### ISSUE TITLE
Oniguruma has a new download location

### ISSUE THREAD

**Issue by christopherowen** [Homebrew/homebrew#43668]
the formula should change to download from:

https://github.com/kkos/oniguruma/releases/download/v5.9.6/onig-5.9.6.tar.gz

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by christopherowen** [comment]
This looks to require more time than I am capable of performing in the short term.  I will review it for the future, however.

**Comment by DomT4** [comment]
We have one open in #43581. Just waiting for OP to reply to feedback there. If it isn't done in the next day or so I'll fix it up.
