### ISSUE TITLE
Building curl with openssl on i7 CPU creates binaries that crash on older CPUs

### ISSUE THREAD

**Issue by drjasonharrison** [Homebrew/homebrew#43678]
I've written up a description of the problems I'm having using libraries built on an Apple computer with i7 CPU crashing on older Apple hardware that doesn't support SSE4.1 and SSE4.2 instructions:
http://stackoverflow.com/questions/32343034/xcode-how-to-build-for-older-intel-processors-i5-core-2-duo-on-i7

I have tracked the issue down to CURL's use of OpenSSL.

How can I specify that OpenSSL should be built with:
    -mno-sse4  (clang)
    -march=core2 (clang, gcc)
    -mno-sse4.1 (gcc)
    -mno-sse4.2 (gcc)

**Comment by mikemcquaid** [comment]
`brew install openssl --build-bottle`.

**Comment by drjasonharrison** [comment]
@mikemcquaid Sorry, do I do that on the old machine (which may die and become unavailable while our customer's old machines will run for ever) on the new machine?
Where can I find documentation for --build-bottle.

**Comment by mistydemeo** [comment]
You'll need to do that on the machine that's building the binaries.

There's documentation on bottles (binary packages) [here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Bottles.md#bottles). The short version is that when you build from source on a machine, Homebrew optimizes for the system being used - which means, as you've noticed, the binaries may not work on older computers. The `--build-bottle` flag instructs Homebrew to build for use as a binary package, in which case Homebrew optimizes for the oldest CPU compatible with the target version of OS X; this is the same behaviour used by our own binary packages.

**Comment by drjasonharrison** [comment]
@mistydemeo Great thanks! I did not find that documentation. Github searches are worse than Bing.
Does --build-bottle create the binaries for Yosemite, Mavericks and Mountain Lion? Or is there a target OS option that I'm missing?

**Comment by mistydemeo** [comment]
There's no target OS option; Homebrew always builds for the OS on which the build is performed.
