### ISSUE TITLE
Error: Not a recognized archive type OS X 10.11

### ISSUE THREAD

**Issue by fouxarn** [Homebrew/homebrew#43682]
I was running a upgrade on python3 but the post install fails when trying to install pip.

```
brew postinstall python3
==> /usr/local/Cellar/python3/3.4.3_2/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts
Reading https://pypi.python.org/simple/pip/
Best match: pip 7.1.2
Downloading https://pypi.python.org/packages/source/p/pip/pip-7.1.2.tar.gz#md5=3823d2343d9f3aaab21cf9c917710196
Processing pip-7.1.2.tar.gz
error: Not a recognized archive type: /tmp/easy_install-o67gpy09/pip-7.1.2.tar.gz
```

https://gist.github.com/anonymous/51b02c2f7e298ee683e9

Any ideas why it doesn't unpack it?

EDIT:
Fixed, had to change command line tools to the latest beta version.

**Comment by dunn** [comment]
Glad you sorted it out! Let us know if you have further questions.
