### ISSUE TITLE
android-sdk: android-build-tools 23.0.0/23.0.1 version mismatch

### ISSUE THREAD

**Issue by kamilbrk** [Homebrew/homebrew#43705]
Fresh OS X Yosemite & Homebrew installation.
Just installed android-sdk and latest tools/platform-tools/build-tools via 'android' command.
Pretty much everything works smoothly (adb, etc.), but zipalign cannot be found.

The only 23.x version available is 23.0.1, while 23.0.0 is hard-coded in formula. I guess this needs to be updated: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/android-sdk.rb#L20

![image](http://i.imgur.com/nSWRznX.png)

brew doctor & update: clean.
brew gist-logs: "No logs"

**Comment by dunn** [comment]
If you `brew edit android-sdk` and update that line, does it work?

**Comment by kamilbrk** [comment]
Just tested, it works, PR ready.
