### ISSUE TITLE
'invalid character' error while trying to build bottles

### ISSUE THREAD

**Issue by chdiza** [Homebrew/homebrew#43701]
I'm playing around with building my own bottles.  I find that I can do that, but when I attempt to install those homemade bottles like the wiki says I can (`brew install path-to-your-bottle.tar.gz`), I get a bizarre looking error.  Here's just an example, using a tiny formula like `base64`:

```
brew install --build-bottle base64
brew bottle base64
brew install ./base64-1.5.yosemite.bottle.tar.gz

Error: invalid character at "\xCF\xFA\xED\xFE\a\x00\x00\x01\x03\x00"
Please report this bug:
    https://git.io/brew-troubleshooting
/Applications/z/homebrew/Library/Homebrew/utils/json.rb:12:in `rescue in load'
/Applications/z/homebrew/Library/Homebrew/utils/json.rb:10:in `load'
/Applications/z/homebrew/Library/Homebrew/tab.rb:39:in `from_file_content'
/Applications/z/homebrew/Library/Homebrew/bottles.rb:49:in `bottle_resolve_formula_names'
/Applications/z/homebrew/Library/Homebrew/formulary.rb:91:in `initialize'
/Applications/z/homebrew/Library/Homebrew/formulary.rb:251:in `new'
/Applications/z/homebrew/Library/Homebrew/formulary.rb:251:in `loader_for'
/Applications/z/homebrew/Library/Homebrew/formulary.rb:197:in `factory'
/Applications/z/homebrew/Library/Homebrew/extend/ARGV.rb:18:in `block in formulae'
/Applications/z/homebrew/Library/Homebrew/extend/ARGV.rb:16:in `map'
/Applications/z/homebrew/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/Applications/z/homebrew/Library/Homebrew/cmd/install.rb:45:in `install'
/Applications/z/homebrew/Library/brew.rb:127:in `<main>'
```

This happens on several formulas, and I haven't yet found one that doesn't produce this error.

Just in case it's relevant (though I don't see offhand why it should be), my `HOMEBREW_REPOSITORY` is not in `/usr/local`, but my `CELLAR` *is* in `/usr/local`/

**Comment by bfontaine** [comment]
I remember having a similar issue, IIRC we can’t use `brew install ./path-to-your-bottle.tar.gz` because Homebrew will try to open it like a Ruby file, hence the weird error you get.

**Comment by mistydemeo** [comment]
Installing a bottle from path is a supported feature, and it looks from the traceback like that's what is happening here - it's not interpreting the bottle as Ruby.

It looks like it's barfing on an attempt to read the install receipt from your bottle. Do you mind uploading your bottle file somewhere so I can look at it?

**Comment by mikemcquaid** [comment]
FWIW the bot using this path (installing bottles from files) on every build so it's probably some sort of local issue.

**Comment by mistydemeo** [comment]
The first four bytes it's trying to read, `0xcffaedfe`, are the magic bytes at the beginning of an x86_64 mach-o executable. This is occurring in `Tab.from_file_content`, which is called [here](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/bottles.rb#L49) when it tries to load the install receipt as JSON. Somehow it's found an executable instead.

Seeing the bottle (and the formula from which it's built, if you've customized that) would help!

**Comment by chdiza** [comment]
I'll have access to the machine housing the bottle in question later tonight.  In the meantime, I note that it really was a valid `tar.gz` file, because I could gunzip and untar it and produce a "keg" that worked fine when I manually put it into place.

**Comment by chdiza** [comment]
Well, I've just reproduced it on a second machine.

The formula is the `base64` formula from core.

The install receipt, prettified by `jq`,  is:
```
{
  "used_options": [],
  "unused_options": [],
  "built_as_bottle": true,
  "poured_from_bottle": false,
  "time": 1441737505,
  "HEAD": "e11f1a7f5be4977a1aff006a0f0833d3c622f782",
  "stdlib": null,
  "compiler": "clang",
  "source": {
    "path": "/Applications/z/homebrew/Library/Formula/base64.rb",
    "tap": "Homebrew/homebrew",
    "spec": "stable"
  }
}
```

There's probably no need to post the bottle itself, because I did a FileMerge.app comparison of a non-bottled install of `base64` with the homemade bottle, and they're identical apart from the install receipts differing on `built_as_bottle`/`time`.

Just for fun, here's the `brew --config` from the second machine:
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: e11f1a7f5be4977a1aff006a0f0833d3c622f782
Last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /Applications/z/homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit arrandale
OS X: 10.10.5-x86_64
Xcode: 6.4
CLT: 6.4.0.0.1.1435007323
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: N/A
```

**Comment by mistydemeo** [comment]
Can you edit `Library/Homebrew/bottles.rb` to add some logging to see what Homebrew retrieves as `receipt_file_path` inside the `bottle_resolve_formula_names` function?

**Comment by chdiza** [comment]
Not sure what "logging" involves.   I determined that `receipt_file_path` is an empty string by doing `puts receipt_file_path.empty?` and observing `true` on the terminal.

**Comment by chdiza** [comment]
Got it.  It's because of the different between gnu-tar and bsdtar.  Gnu-tar chokes on the command given in `bottle_receipt_path`, while bsdtar doesn't.

If a user has gnu-tar installed, and has done so with the option to call the binary `tar`, the user will end up calling gnutar in `bottle_receipt_path()` and the choking will ensue.

**Comment by chdiza** [comment]
The function `bottle_receipt_path()` should probably get an explicit `/usr/bin/tar` baked into it.

With gnu-tar:
```
tar -tzf base64-1.5.yosemite.bottle.tar.gz "*/*/INSTALL_RECEIPT.json"
tar: Pattern matching characters used in file names
tar: Use --wildcards to enable pattern matching, or --no-wildcards to suppress this warning
tar: */*/INSTALL_RECEIPT.json: Not found in archive
tar: Exiting with failure status due to previous errors
```
With `/usr/bin/tar`:
```
/usr/bin/tar -tzf base64-1.5.yosemite.bottle.tar.gz "*/*/INSTALL_RECEIPT.json"
base64/1.5/INSTALL_RECEIPT.json
```

Lord, I hate bsdtar :)

**Comment by chdiza** [comment]
Pouring the bottle afterwards worked, except that first I had to do `unset HOMEBREW_BUILD_FROM_SOURCE`.  I did not expect to have to do that, since the fact that I'm pointing `brew install` at a gzipped tarball should make it clear to `brew` that in this particular instance I want to pour a bottle no matter what that shellvar says.

**Comment by chdiza** [comment]
I'm happy to tee up a PR if indeed the actual, proper cure for this is to replace `tar` with `/usr/bin/tar` in the function `bottle_receipt_path` in the file `bottles.rb`.

**Comment by mistydemeo** [comment]
That would be great, thanks!

**Comment by chdiza** [comment]
FWIW I vimgrepped for other occurrences of `tar` in `Library/Homebrew` to see if a similar repair is warrented elsewhere, but AFAICT all the other uses will work under both bsdtar and gnu-tar.

If we should hardcode those other places as `/usr/bin/tar` as well, let me know.

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew/commit/2b624dc1639ac67017ea5ed1ef7aa6a87137256a.
