### ISSUE TITLE
logstash does not include correct version of plugin binary

### ISSUE THREAD

**Issue by ajsharp** [Homebrew/homebrew#43710]
Logstash includes a command in it's `bin` directory called `plugin` -- it looks like the homebrew version comes with a version of it (or, i have one lying around), but it's out of date. In the 1.5.x branch of logstash, plugins are pretty core to even being able to run logstash, so this is pretty important, and made the current homebrew version unusable for me.

**Comment by mistydemeo** [comment]
Homebrew installs the `plugin` file straight from the logstash tarball; is that not the latest version?

**Comment by ph** [comment]
@ajsharp I recheck the package, it contains a plugin command

`/usr/local/Cellar/logstash/1.5.4/bin/plugin update logstash-input-lumberjack` should work can you try this?

**Comment by DomT4** [comment]
Was updated a couple of weeks ago in https://github.com/Homebrew/homebrew/commit/4e88ca7fce68ae81200e74828265beb9f2754c78, but no changes to what was installed on our end. Just a version update & some style nits. Should be the same binaries as before unless something changed upstream.

**Comment by ajsharp** [comment]
Ah, I figured out the problem. I was trying to use `/usr/local/bin/plugin`, which is a symlink to the elasticsearch plugin binary. This is a bit confusing, and probably a difficult thing to resolve in homebrew-land (e.g. two different formulas with the same binary name).

**Comment by ph** [comment]
@ajsharp we have an upcoming discussion on our end to make the plugin a subcommand of the logstash binary.

**Comment by ajsharp** [comment]
@ph Cool, yea seems like that would clean up a lot of this. @mistydemeo thanks for the quick response :)
