### ISSUE TITLE
error install phyton

### ISSUE THREAD

**Issue by helmi72** [Homebrew/homebrew#43720]
help me with this error

brew install python
==> Installing dependencies for python: pkg-config, readline, sqlite, gdb
==> Installing python dependency: pkg-config
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.28.yosemite.bo
######################################################################## 100.0%
==> Pouring pkg-config-0.28.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.28: 10 files, 612K
==> Installing python dependency: readline
==> Downloading https://homebrew.bintray.com/bottles/readline-6.3.8.yosemite.bot
######################################################################## 100.0%
==> Pouring readline-6.3.8.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include

==> Summary
🍺  /usr/local/Cellar/readline/6.3.8: 40 files, 2.1M
==> Installing python dependency: sqlite
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.8.11.1.yosemite.bo
######################################################################## 100.0%
==> Pouring sqlite-3.8.11.1.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides an older sqlite3.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/sqlite/lib
    CPPFLAGS: -I/usr/local/opt/sqlite/include

==> Summary
🍺  /usr/local/Cellar/sqlite/3.8.11.1: 9 files, 2.8M
==> Installing python dependency: gdbm
==> Downloading https://homebrew.bintray.com/bottles/gdbm-1.11.yosemite.bottle.2
######################################################################## 100.0%
==> Pouring gdbm-1.11.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/gdbm/1.11: 17 files, 532K
==> Installing python
==> Downloading https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
######################################################################## 100.0%
==> Downloading https://bugs.python.org/file30805/issue10910-workaround.txt
######################################################################## 100.0%
==> Patching
patching file Include/pyport.h
Hunk #1 succeeded at 713 (offset 14 lines).
Hunk #2 succeeded at 736 (offset 14 lines).
==> ./configure --prefix=/usr/local/Cellar/python/2.7.10_2 --enable-ipv6 --datar
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/tmp/python20150909-26805-48mcv6/Python-2.7.10':
configure: error: C compiler cannot create executables
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Fix python lib finding on OS X 10.10.4 https://github.com/Homebrew/homebrew/pull/42717
Python fails to build core extension modules on 10.11 https://github.com/Homebrew/homebrew/issues/41085
gdal --with-python always installs numpy into prefix https://github.com/Homebrew/homebrew/issues/36744
python's sys.prefix points to a version-specific framework path https://github.com/Homebrew/homebrew/issues/42236
Python/Python3: Fix RuntimeError: tk.h version (8.6) doesn't match libtk.a version (8.5) https://github.com/Homebrew/homebrew/pull/41728
bokken failed to build on OSX 10.10 due to Python 2.5 dependency https://github.com/Homebrew/homebrew/issues/32016

**Comment by mistydemeo** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please read this link and provide the requested diagnostic information.

**Comment by helmi72** [comment]
clear, must reinstall xcode an reinstall again
