### ISSUE TITLE
I can't upgrade node to 4.0.0

### ISSUE THREAD

**Issue by agileago** [Homebrew/homebrew#43743]
I see the pull request about node 4.0.0 . why i can't upgrade ?

**Comment by bfontaine** [comment]
It needs to be merged in before you can upgrade :wink:

**Comment by agileago** [comment]
when ?

**Comment by bfontaine** [comment]
There are some blocking issues, see https://github.com/Homebrew/homebrew/pull/43716#issuecomment-138777973 for more info.

**Comment by agileago** [comment]
all right . thanks 👍
