### ISSUE TITLE
how to "fix" -config scripts found in Brew Doctor

### ISSUE THREAD

**Issue by 2100-Solutions** [Homebrew/homebrew#43749]
I have run Brew Update, and Brew Doctor.   I received the following warnings... 
1.  Should I fix them?
2.  If so, what is the best method to reassign or relocate/move

thanks,

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
    /sw/bin/apt-config
    /sw/bin/ksba-config
    /sw/bin/ncurses5-config
    /sw/bin/pkg-config
    /sw/bin/x86_64-apple-darwin14.0.0-pkg-config

Warning: You have MacPorts or Fink installed:
  /sw/bin/fink

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

Warning: You have a non-Homebrew 'pkg-config' in your PATH:
  /sw/bin/pkg-config

`./configure` may have problems finding brew-installed packages using
this other pkg-config.

**Comment by DomT4** [comment]
It's the `fink` installation. If they aren't causing any build problems I wouldn't worry about them too much; `brew doctor` is only intended as a warning rather than an absolute *"Remove this or you'll have problems"* sort of thing.

If you do have build problems, you can either uninstall `fink` or you could do something like `sudo mv /sw ~/sw` before using `brew`, and then place it back afterwards.

**Comment by 2100-Solutions** [comment]
Got it..  Thanks so much for the quick reply!!

**Comment by 2100-Solutions** [comment]
should I use your example above 'verbatim' or is the "sw" reference a place holder?

**Comment by 2100-Solutions** [comment]
I know /sw is part of Fink... but just asking to be sure

**Comment by DomT4** [comment]
`/sw` shouldn't exist on OS X unless Fink is installed, so it should be safe to move the thing wholesale.

**Comment by 2100-Solutions** [comment]
that commmand would "hide" the directory for /sw...right?

**Comment by DomT4** [comment]
It moves `sw` into your Home folder. After you're done `brew`-ing you'd just do `sudo mv ~/sw /` again to put it back where it expects to be.

It might be worth setting an alias in your shell profile if it's something you want to do often, something like:

```
alias safesw="sudo mv /sw ~/"
alias homesw="sudo mv ~/sw /"
```

**Comment by 2100-Solutions** [comment]
why would I move it back after running "brew", which I have run.   but not moved ~/sw back to /sw

**Comment by 2100-Solutions** [comment]
you answered my question. above...

I will update the .bash_profile  with the aliases

**Comment by DomT4** [comment]
:+1:. Let us know if you have any further questions! Your `brew doctor` should be clean once Fink is no longer in the `$PATH`.

**Comment by 2100-Solutions** [comment]
Thanks.   that cleared it up!

**Comment by 2100-Solutions** [comment]
Wonderful help!  Dominyk!!

Hope I can call on you again!


Bill Fulbright
770-880-0959
bill@2100Solutions.com
http://2100Solutions.com

**Comment by DomT4** [comment]
Feel free to file an issue if you ever have any questions. We're happy to help :)
