### ISSUE TITLE
Got err when brew update

### ISSUE THREAD

**Issue by jiukunz** [Homebrew/homebrew#43747]
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:252:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:197:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:204:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:124:in `<main>'

**Comment by mikemcquaid** [comment]
Duplicate of https://github.com/Homebrew/homebrew/issues/42553.
