### ISSUE TITLE
wine dependency openssl/1.0.2d

### ISSUE THREAD

**Issue by johnlouis-swaine-axomic** [Homebrew/homebrew#43752]
brewing wine os Yosemite 10.10.5

```
==> perl ./Configure --prefix=/usr/local/Cellar/openssl/1.0.2d_1 --openssldi
==> make depend
==> make
couldn't understand kern.osversion `14.5.0'
ghash-x86_64.s:890:junk `.15473355479995e+19' after expression
make[2]: *** [ghash-x86_64.o] Error 1
make[1]: *** [subdirs] Error 1
make: *** [build_crypto] Error 1
couldn't understand kern.osversion `14.5.0'
couldn't understand kern.osversion `14.5.0'
```

Per MacPorts dealing with a similar issue

This is a known openssl build bug: Patch is available [here](http://rt.openssl.org/Ticket/Display.html?user=guest&pass=guest&id=3759) and [here](https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/dev-libs/openssl/files/openssl-1.0.2a-x32-asm.patch).

**Comment by DomT4** [comment]
This is a valid patch case, but I'd like some confirmation from OpenSSL that they're aware of the problem and are happy with the patch before we consider applying it. Any idea if upstream has looked over it?

**Comment by DomT4** [comment]
Let us know if we can help further here, Thanks!
