### ISSUE TITLE
brew --cache returns wrong path

### ISSUE THREAD

**Issue by guoxiao** [Homebrew/homebrew#43764]
`brew --cache` tells me that the cache dir is `/Users/<my username>/Library/Caches/Homebrew` but actually all the downloaded files are in `/Library/Caches/Homebrew`. Is this a bug or not?

**Comment by bfontaine** [comment]
If you do `brew fetch libchamplain` then what is the output of `brew --cache libchamplain`?

**Comment by guoxiao** [comment]
I've found the causing of the problem.
Homebrew will check `/Users/<my username>/Library/Caches/Homebrew` first. If it doesn't exist homebrew will use `/Library/Caches/Homebrew` instead. 

Today I accidentally created the folder so homebrew use it instead of the global folder.

**Comment by guoxiao** [comment]
@bfontaine Thank you for your help all the same.
