### ISSUE TITLE
brew update

### ISSUE THREAD

**Issue by utkan** [Homebrew/homebrew#43773]
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:252:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:197:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:173:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:140:in `<main>'

**Comment by dunn** [comment]
See #42553. Running `brew update` again should fix things!
