### ISSUE TITLE
jython-2.7.0.jar reported as Java:Malware-gen [Tri] by Avast

### ISSUE THREAD

**Issue by ssbarnea** [Homebrew/homebrew#43776]
It worries me a lot that the current jython installed by brew seems to contain a malware: Java:Malware-gen [Tri] by Avast

/Library/Caches/Homebrew/jython-2.7.0.jar

**Comment by dunn** [comment]
We're using the recommended Maven source (https://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7.0/jython-installer-2.7.0.jar), so this should also be reported to the developers.

**Comment by DomT4** [comment]
This seems like a false flag: https://www.virustotal.com/en/file/b44352ece72382268a60e2848741c96609a91d796bb9a9c6ebeff62f0c12c9cf/analysis/

I'd report this to Avast, but I wouldn't worry *too much*.
