### ISSUE TITLE
SSL: can't load CA certificate file /usr/share/curl/ca-bundle.crt

### ISSUE THREAD

**Issue by blacRose** [Homebrew/homebrew#43786]
It definitely exists. With built-in curl and Homebrew get this error

    brew upgrade --verbose youtube-dl 1
    Warning: You are using OS X 10.11. We do not provide support for this pre-release version. You may encounter build failures or other breakage.
    ==> Upgrading 1 outdated package, with result: youtube-dl 2015.09.0
     ==> Upgrading youtube-dl rm /usr/local/bin/youtube-dl
    rm /usr/local/etc/bash_completion.d/youtube-dl.bash-completion
    rm /usr/local/share/fish/vendor_completions.d/youtube-dl.fish
    rm /usr/local/share/man/man1/youtube-dl.1
    rm /usr/local/share/zsh/site-functions/_youtube-dl
    rmdir /usr/local/share/fish/vendor_completions.d
    rmdir /usr/local/share/fish
    ==> Downloading https://yt-dl.org/downloads/2015.09.09/youtube-dl-2015.09.09.tar.gz /usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-645; OS X 10.11) https://yt-dl.org/downloads/2015.09.09/youtube-dl-2015.09.09.tar.gz -C 0 -o /Library/Caches/Homebrew/youtube-dl-2015.09.09.tar.gz.incomplete
     % Total % Received % Xferd Average Speed Time Time Time Current
    Dload Upload Total Spent Left Speed
    0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
    curl: (77) SSL: can't load CA certificate file /usr/share/curl/ca-bundle.crt
    Error: Failed to download resource "youtube-dl"
    Download failed: https://yt-dl.org/downloads/2015.09.09/youtube-dl-2015.09.09.tar.gz
    ln -s ../../Cellar/youtube-dl/2015.09.03/etc/bash_completion.d/youtube-dl.bash-completion youtube-dl.bash-completion
    ln -s ../Cellar/youtube-dl/2015.09.03/bin/youtube-dl youtube-dl
    ln -s ../../../Cellar/youtube-dl/2015.09.03/share/fish/vendor_completions.d/youtube-dl.fish youtube-dl.fish
    ln -s ../../../Cellar/youtube-dl/2015.09.03/share/man/man1/youtube-dl.1 youtube-dl.1
    ln -s ../../../Cellar/youtube-dl/2015.09.03/share/zsh/site-functions/_youtube-dl _youtube-dl

**Comment by DomT4** [comment]
Check your `env` and/or shell profiles for a `export SSL_CERT_FILE` line. If you remove it, does it resume working again?

```
ls -l /usr/share/curl/ca-bundle.crt
```

Could be worthwhile.

**Comment by blacRose** [comment]
HUH‽
`SSL_CERT_FILE=/usr/share/curl/ca-bundle.crt`
    ls -l /usr/share/curl/ca-bundle.crt
    ls: /usr/share/curl/ca-bundle.crt: No such file or directory

**Comment by DomT4** [comment]
If `ls` says the file doesn't exist, it probably doesn't exist. Can you unset `SSL_CERT_FILE` and see if the download works?

**Comment by blacRose** [comment]
ARGH!! *feels sheepish* Why was that in my `.zshrc` and why did it break on GM?

**Comment by DomT4** [comment]
If you weren't having any problems before today, perhaps the GM removed the file. It's possible you set it at some point in the past and it just wasn't a problem till now. Glad all is working okay!
