### ISSUE TITLE
Xcode 7 GM on 10.10 does not include a 10.10 sdk or otool

### ISSUE THREAD

**Issue by CamJN** [Homebrew/homebrew#43785]
Figured you guys should know.

**Comment by DomT4** [comment]
`otool` should be part of OS X natively, I believe? Can confirm the 10.10 SDK thing though, they cut it in the last Xcode beta before the GM release.

**Comment by CamJN** [comment]
The "native" otool is just a wrapper of sorts that uses the one from xcode, I tried calling it as /usr/bin/otool when I had the GM installed and it just bitched that it couldn't find the real otool.

**Comment by mistydemeo** [comment]
What's your `xcode-select` path set to? `otool` is in `XcodeDefault.xctoolchain`, not in a versioned SDK, so it should work even if you're on 10.10 with no 10.10 SDK.

**Comment by CamJN** [comment]
It was set to `/Applications/Xcode.app/Contents/Developer/` but I've reverted to Xcode 6.4 now b/c I had to build a php update

**Comment by DomT4** [comment]
Closing as resolved/known issue here. We're hopeful Apple restores the 10.10 SDK in the final Xcode 7 release, but that decision is *way* out of our hands.

**Comment by CamJN** [comment]
Just verifying, this is with the final Xcode 7 from the app store today:

 ls /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
MacOSX10.11.sdk

**Comment by mikemcquaid** [comment]
Given it's shipped we'll need to just figure this out.

**Comment by lgjohns** [comment]
Any recommended workarounds?

**Comment by DomT4** [comment]
Install the Command Line Tools. `brew doctor` advises this now.
