### ISSUE TITLE
postgresql dlopen brew install issue - on multiple machines

### ISSUE THREAD

**Issue by yunti** [Homebrew/homebrew#43780]
I'm getting a consistent error across multiple machine which seems to be caused by the brew installation of postgresql:
Error loading psycopg2 module: dlopen(/Users/Yunti/.virtualenvs/switcher2/lib/python3.4/site-packages/psycopg2/_psycopg.so, 2): Library not loaded: /Applications/Postgres.app/Contents/Versions/9.4/lib/libssl.1.0.0.dylib
  Referenced from: /Users/Yunti/.virtualenvs/switcher2/lib/python3.4/site-packages/psycopg2/_psycopg.so
  Reason: image not found

It looks to be able to be solved manually here http://stackoverflow.com/a/12397173/1630586
However because I'm seeing it on several machines (yosemite and el capitan) it suggests it's a consistent install issue. 

Edit: that doesn't solve the issue as the files (libssl.1.0.0.dylib   etc..)  aren't to be found in:
usr->local->Cellar->postgresql->9.4.4->lib

Update: installing postgres via the app does solve the issue (although obviously not ideal).

**Comment by mistydemeo** [comment]
I don't see any files here that look like they were installed by Homebrew; are you sure this is is caused by brew?

It looks like your installation of the psycopg2 Python module, in one of your virtualenvs, is linked against a version of Postgres (and its libraries) from the Postgres.app. How did you install that?

**Comment by yunti** [comment]
psycopg2 was installed via pip (using a requirements file) to a virtualenv.  The postgres app was installed previously (before this virtualenv was setup) and uninstalled and installed with brew.  Perhaps something was left behind of the prior installation which has caused this issue as you suggested rather than the issue being caused by brew.

**Comment by mistydemeo** [comment]
Yes, I think that's the case. It looks like the Python library built against the Postgres app while it was still installed; psycopg2 will use whichever `pg_config` it can find to figure out which Postgres to build against. My guess would be the `pg_config` from that Postgres app was the first in your PATH at the time you installed the library.

If you've removed the Postgres.app, try uninstalling and reinstalling psycopg2.

**Comment by yunti** [comment]
Hmm unfortunately removing the psycopg2 didn't help.  Neither did removing the virtualenv and setting it up again.  I also reinstalled python (2.4) with brew again in case that was the issue and then redid the virtualenv and reinstalled psycopg2 again.  Still the same issue, unfortunately.

**Comment by mistydemeo** [comment]
What is the output of `which pg_config`?

**Comment by yunti** [comment]
it's /usr/local/bin/pg_config

**Comment by yunti** [comment]
reinstalling psycopg2 without the pip cache fixed the issue - so the brew installed version of postgres was fine.
Thanks for your help.
