### ISSUE TITLE
PySide fails to compile on OSX 10.10 (Yosemite)

### ISSUE THREAD

**Issue by geeklady2** [Homebrew/homebrew#43798]
I started with a fresh install on a Mac OSX 10.10 VM.  Here's the commands I used ...

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew install python
brew install python3 --universal --framework
pip3 install --upgrade pip setuptools
brew install PySide --with-python3

Note I've tried python3 without all of the flags. I don't recall why I added them but it was related to the installation of some python package and without them it didn't work.  I have a script that I use to create my VM environments I want.

Here's the output from the PySide install

Mac:local jaeger$ brew install PySide --with-python3
==> Installing dependencies for pyside: cmake, qt, shiboken
==> Installing pyside dependency: cmake
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.3.1.yosemite.bottle.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/cmake-3.3.1.yosemite.bottle.1.tar.gz
==> Pouring cmake-3.3.1.yosemite.bottle.1.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
/usr/local/share/emacs/site-lisp/

Add the following to your init file to have packages installed by
Homebrew added to your load-path:
(let ((default-directory "/usr/local/share/emacs/site-lisp/"))
  (normal-top-level-add-subdirs-to-load-path))
==> Summary
🍺  /usr/local/Cellar/cmake/3.3.1: 1901 files, 33M
==> Installing pyside dependency: qt
==> Downloading https://homebrew.bintray.com/bottles/qt-4.8.7.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/qt-4.8.7.yosemite.bottle.tar.gz
==> Pouring qt-4.8.7.yosemite.bottle.tar.gz
==> Caveats
We agreed to the Qt opensource license for you.
If this is unacceptable you should uninstall.

.app bundles were installed.
Run `brew linkapps qt` to symlink these to /Applications.
==> Summary
🍺  /usr/local/Cellar/qt/4.8.7: 2794 files, 122M
==> Installing pyside dependency: shiboken
==> Downloading https://download.qt.io/official_releases/pyside/shiboken-1.2.2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/shiboken-1.2.2.tar.bz2
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/
==> make install
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/
==> make install
🍺  /usr/local/Cellar/shiboken/1.2.2: 34 files, 3.3M, built in 4.0 minutes
==> Installing pyside
==> Downloading https://download.qt.io/official_releases/pyside/pyside-qt4.8+1.2.2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/pyside-1.2.2.tar.bz2
==> Downloading https://pypi.python.org/packages/source/S/Sphinx/Sphinx-1.2.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/pyside--sphinx-1.2.3.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/pyside20150
--record=installed.txt

Your PYTHONPATH points to a site-packages dir for Python 3.x but you are running Python 2.x!
     PYTHONPATH is currently: "/private/tmp/pyside20150910-62880-3h5b0w/pyside-qt4.8+1.2.2/sphinx/lib/python2.7/site-packages:/usr/local/lib/python3.4/site-packages"
     You should `unset PYTHONPATH` to fix this.

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
PySide/PyQt: how to get Phonon support?  https://github.com/Homebrew/homebrew/issues/33102

**Comment by dunn** [comment]
@tdsmith will this formula need to be tweaked after #43744 and #43724 are merged?

**Comment by geeklady2** [comment]
ok after some investigation.

I did a brew edit pyside and looked t the code.  It appears that documentation is being installed in python2.7 directory always or maybe it's that if you are building docs it's assumed you are building for python2.7.  I am new to brew, although so far think it's pretty cool, so my understanding of the build files is pretty limited at this point.

However, I do have a work around that builds PySide for python3.  The command below works.
brew install --with-python3 --without-docs

This issue might need updating with the resolution of #43744 and #43724, thanks for pointing them out.

**Comment by tdsmith** [comment]
I expect that this issue has been resolved. Unfortunately, building pyside will fail for a different reason now: #43915

FWIW, `--framework` is a no-op for python3.
