### ISSUE TITLE
llvm formula: build is not parallel

### ISSUE THREAD

**Issue by luc-j-bourhis** [Homebrew/homebrew#43791]
The formula issues "make". 

This was with "brew install llvm --with-clang --with-lld --with-python --with-rtti" on MacOS 10.10.5 but I don't think it matters looking at llvm.rb:

```ruby
mktemp do
      system "cmake", "-G", "Unix Makefiles", buildpath, *(std_cmake_args + args)
      system "make"
      system "make", "install"
end
```

Is this an oversight or is there a deeper reason?

There is the usual workaround of course: set the environment variable MAKEFLAGS="-jxxx".

**Comment by xu-cheng** [comment]
We set `MAKEFLAGS` automatically inside Homebrew. And the llvm build is parallel for me. If there is any further issue, please let me know.

**Comment by luc-j-bourhis** [comment]
> We set MAKEFLAGS automatically inside Homebrew. And the llvm build is parallel for me. If there is any further issue, please let me know.

I would like to print the value of MAKEFLAGS in llvm.rb. How do I do that?

Best wishes,

Luc

**Comment by xu-cheng** [comment]
You can view the env to build formula by `brew --env formula --build-flags`. In your case is `brew --env llvm --with-clang --with-lld --with-python --with-rtti`

**Comment by xu-cheng** [comment]
Sorry, I made a mistake. You should just use `brew --env` to check build env. `brew --env formulae` has different functions.

**Comment by luc-j-bourhis** [comment]
thanks for your help. It turns out that

~% env | grep MAKEFLAGS
MAKEFLAGS=

So this is a problem local to my machine then.

Sorry for the noise and thansks again,

Luc

**Comment by DomT4** [comment]
Make sure you're checking `brew --env` and not `env`. Should output something like:

```
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
```

Without the `grep`.

**Comment by luc-j-bourhis** [comment]
Thanks to all of you.

For the record, just in case you get the question again, a bug in OPAM setup: https://github.com/ocaml/opam/issues/2299

Thanks for taking great care of the amazing homebrew!
