### ISSUE TITLE
pyqt bottled formula points to qt 4.8.6, but requires qt 4.8.7

### ISSUE THREAD

**Issue by a1k0n** [Homebrew/homebrew#43805]
Currently, when you do a brew install pyqt, it pours a bottle which contains the following:
```
/usr/local/Cellar/pyqt/4.11.3/lib/python2.7/site-packages/PyQt4/pyqtconfig.py
40:    'qt_archdata_dir':   '/usr/local/Cellar/qt/4.8.6',
41:    'qt_data_dir':       '/usr/local/Cellar/qt/4.8.6',
42:    'qt_dir':            '/usr/local/Cellar/qt/4.8.6',
45:    'qt_inc_dir':        '/usr/local/Cellar/qt/4.8.6/include',
46:    'qt_lib_dir':        '/usr/local/Cellar/qt/4.8.6/lib',
104:    'INCDIR_QT':                '/usr/local/Cellar/qt/4.8.6/include',
123:    'LIBDIR_QT':                '/usr/local/Cellar/qt/4.8.6/lib',
142:    'MOC':                      '/usr/local/Cellar/qt/4.8.6/bin/moc',
```

Except qt is actually in `/usr/local/Cellar/qt/4.8.7`, so anything that uses this pkg-config points to the wrong version of qt. This mainly seems to affect ROS users: http://answers.ros.org/question/211546/fatal-error-qmetatype-file-not-found-when-building-ros-indigo-on-os-x-10103/

I don't know whether the bottle just needs to be updating, or whether there's a systematic way to get bottles to generate dynamic filename references, but running `brew reinstall --build-from-source pyqt` fixes the issue (after a long build).

A separate but similar issue is in pyside, where it's using absolute include paths rather than relative ones:
```
/usr/local/Cellar/pyside/1.2.2/include/PySide/pyside_global.h
25:#include "/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Headers/qnamespace.h"
332:#include "/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Headers/QtCore"
338:#include "/usr/local/Cellar/qt/4.8.6/include/QtGui/QtGui"
341:  #include "/usr/local/Cellar/qt/4.8.6/include/QtGui/QX11Info"
342:  #include "/usr/local/Cellar/qt/4.8.6/include/QtGui/QX11EmbedContainer"
343:  #include "/usr/local/Cellar/qt/4.8.6/include/QtGui/QX11EmbedWidget"
345:  #include "/usr/local/Cellar/qt/4.8.6/include/QtGui/qmacstyle_mac.h"
```

**Comment by Lome789** [comment]
eww... i tried but it didnt work

**Comment by tdsmith** [comment]
Thanks for reporting; this shouldn't happen in the future.

**Comment by a1k0n** [comment]
Excellent, thank you!
