### ISSUE TITLE
The problem with the message Warning: You have an outdated version of /usr/bin/install_name_tool installed.

### ISSUE THREAD

**Issue by Mushu777** [Homebrew/homebrew#43818]
The problem with the message

~  brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have an outdated version of /usr/bin/install_name_tool installed.
This will cause binary package installations to fail.
This can happen if you install osx-gcc-installer or RailsInstaller.
To restore it, you must reinstall OS X or restore the binary from
the OS packages.

My surrounding

brew --env
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin

~  brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 12fa55ffb258225ff85cb2b1827b2e1175decaaa
Last commit: 16 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit sandybridge
OS X: 10.10.5-x86_64
Xcode: 6.4
CLT: 6.4.0.0.1.1435007323
couldn't understand kern.osversion `14.5.0'
GCC-4.2: build 5666
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/mushu/.rvm/rubies/ruby-2.0.0-p647/bin/ruby
Java: 1.8.0_60, 1.6.0_65-b14-468

Already I reinstalled from scratch Homebrew message still does not disappear, give advice how to overcome this problem? Thanks for the help.

**Comment by DomT4** [comment]
See https://github.com/Homebrew/homebrew/issues/29989#issuecomment-46590924. You'd need to do something like that for Yosemite. The error isn't a Homebrew one per se.

You can also grab the binary from a friend's computer and replace your's, as long as the binary is from the same OS X version & you trust that friend :smile:.

**Comment by Mushu777** [comment]
otool -L /usr/bin/install_name_tool
/usr/bin/install_name_tool:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)

**Comment by tdsmith** [comment]
Dominyk explained how to resolve the problem; please let us know if we can help with anything.
