### ISSUE TITLE
installing libspatialite results in 404 error

### ISSUE THREAD

**Issue by NicholasMerrill** [Homebrew/homebrew#43814]
The url [here](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libspatialite.rb#L4) is out of date and results in a 404 error.

Perhaps a better path is one of the following:

* https://www.gaia-gis.it/gaia-sins/libspatialite-4.3.0a.tar.gz
* https://www.gaia-gis.it/gaia-sins/libspatialite-sources/libspatialite-4.3.0a.tar.gz

It seems the second URL (with `libspatialite-sources`) is keeps the old sources and won't be removed, but the first will be removed when a new update comes out.

Thanks!

**Comment by dunn** [comment]
We've already got a PR in progress! #43800

Thanks for noticing which URL scheme continues to work after upgrades, though, that's good to know!
