### ISSUE TITLE
brew update bug

### ISSUE THREAD

**Issue by hsiaoyi0504** [Homebrew/homebrew#43830]
xiaoyideMacBook-Pro:release huei$ brew update
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:252:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:197:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:204:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:124:in `<main>'

**Comment by dunn** [comment]
Run `brew update` once more and you should be all set; see #42553.

**Comment by hsiaoyi0504** [comment]
Thanks!
