### ISSUE TITLE
python3  failed to build on 10.10.5 with Xcode 7 GM

### ISSUE THREAD

**Issue by an0** [Homebrew/homebrew#43836]
https://gist.github.com/anonymous/fe74661e2385a28981c7

**Comment by DomT4** [comment]
The Xcode 7 GM doesn't contain the 10.10 SDK (Yes, really) so will likely break most compiles.

**Comment by an0** [comment]
@DomT4 😱

**Comment by DomT4** [comment]
Apple decided to take away the 10.10 SDK in the last Beta before the GM release. We don't know if it'll return; history suggests that the stable Xcode will contain the current and previous SDK versions, but we don't know yet.

If you're running 10.10 with Xcode 7 and things fail to compile, I'd probably recommend either downgrading to the 6.x Xcode series or installing the Command Line Tools & `sudo xcode-select --switch` over to those until the Xcode 7 situation is clearer. The latter may not work in every situation.

**Comment by DomT4** [comment]
Closing per the above. Hopefully the 10.10 SDK comes back before final release of Xcode 7, but till then, you may be better downgrading I'm afraid. Apologies there's not much we can do on our side :cry:
