### ISSUE TITLE
Kubernetes-cli not installing on El Capitan

### ISSUE THREAD

**Issue by ehis** [Homebrew/homebrew#43833]
Unable to install kubernetes-cli on El Capitan GM. 

I have linked the logs. 
https://gist.github.com/anonymous/03ee9d61781e5ecb53f2

**Comment by DomT4** [comment]
The point upstream repeatedly comes back to here is needing *a lot* of RAM to build `kubernetes-cli`. Somewhere in the region of 3GB is quoted fairly often. Try closing down every other running process and doing the build.
