### ISSUE TITLE
homebrew does not cache git repos from --HEAD builds

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew#43839]
Stable build and bottles get cached, so why not --HEAD builds?

Could help with subsequent --HEAD builds, since the entire repo
and/or working tree doesn't have to be downloaded/checked out.
Especially for --HEAD builds, which could update frequently
(although brew update doesn't update --HEAD builds).

Not sure how many people would find this useful... I notice it a
lot because I'm tweaking the llvm formula, but I don't know how
frequently --HEAD builds of larger builds are built.

**Comment by DomT4** [comment]
`head` repos are cached:

```
brew fetch git --HEAD
ls -1 `brew --cache` | grep git
git--git
git--html-2.5.2.tar.xz
git--man-2.5.2.tar.xz
```

What are you seeing locally?

**Comment by aw1621107** [comment]
...I'm seeing that I didn't look close enough. Usually saw flashes
of "cloning ____"  and assumed that it was doing full clones.
My mistake.
