### ISSUE TITLE
ossp/uuid.h location breaks CMake with pkg-config

### ISSUE THREAD

**Issue by bluca** [Homebrew/homebrew#43843]
Hi,

The formula for ossp-uuid:
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ossp-uuid.rb
overrides the location of the header file, placing it into /usr/local/Cellar/ossp-uuid/1.6.2_1/include/ossp. Reading from the commit history, I think that's because there's a conflict with OSX, right?

The problem is that pkg-config returns as the location of the header /usr/local/Cellar/ossp-uuid/1.6.2_1/include. Since CMake does not do recursive searches for find_path, this breaks the build.

This is especially a problem for multi-platform projects. I'd really like to avoid littering the build system with IF OSX THEN...

Any chances this issue could be solved? If this cannot be reverted, upstream's uuid.pc.in should be patched, since it sets the include variable to $prefix/include instead of @includedir@:
```
prefix=@prefix@
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib
```

Would you accept such a patch?

Thank you!

**Comment by bluca** [comment]
Tested this with ./configure and various options:

```
--- uuid.pc.in	2015-09-12 04:03:34.921192349 +0100
+++ uuid.pc.in	2015-09-12 04:13:53.226386329 +0100
@@ -30,5 +30,5 @@
 prefix=@prefix@
-exec_prefix=${prefix}
-includedir=${prefix}/include
-libdir=${exec_prefix}/lib
+exec_prefix=@exec_prefix@
+includedir=@includedir@
+libdir=@libdir@
 
```

**Comment by bluca** [comment]
Filed ticket upstream, but the package was not updated in a long time: http://cvs.ossp.org/tktview?tn=200

**Comment by tdsmith** [comment]
>  upstream's uuid.pc.in should be patched

:+1:

**Comment by bluca** [comment]
Opened PR #43889, tested on Debian via LinuxBrew.

**Comment by DomT4** [comment]
Closing in favour of #43889.
