### ISSUE TITLE
hidapi: hidtest

### ISSUE THREAD

**Issue by dardo82** [Homebrew/homebrew#43850]
Shouldn't we give the option to get this too when the library is installed? 
It's just a matter of compiling,the sources for it come along with the rest.
I have just found out that hidtest is compiled by default,but not TestGUI.

**Comment by dunn** [comment]
Sounds fine to me. Interested in opening a PR? Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions!

**Comment by dardo82** [comment]
They should be optional or do you think that I can just add them to the "base package"?

**Comment by dardo82** [comment]
I've decided to include just "hidtest" as it was the easiest choice.
But I wonder: adding the GUI app would require a cask formula?

**Comment by dunn** [comment]
Some formula do build `.app`s; we have a `brew linkapps` command to symlink them to `/Applications`.  So if you can get it to compile, feel free to open another PR.

**Comment by DomT4** [comment]
PR was merged.

**Comment by dardo82** [comment]
It's OK for me as it is at the moment...
