### ISSUE TITLE
Install failed on OS X 10.11 GM

### ISSUE THREAD

**Issue by x2on** [Homebrew/homebrew#43855]
When i try to install homebrew on OS X 10.11 GM it fails with the following error:

```bash
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/man/man1/brew.1

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
#/usr/local/.git: Operation not permitted
Failed during: git init -q
```

It looks like `/usr/local/` is not writable anymore during the new system integrity protection.

Any ideas?

**Comment by DomT4** [comment]
```bash
sudo chown -R $(whoami):admin /usr/local && sudo chown $(whoami):admin /usr/local
```

**Comment by x2on** [comment]
I don't have wrights to do that:
`chown: /usr/local: Operation not permitted` during the system integrity protection.

**Comment by DomT4** [comment]
Does `/usr/local` not exist? It *should* already exist on 10.11 and you should be able to chown it with `sudo`.

**Comment by x2on** [comment]
No it doesn't exist here.
I deactivated the system protection, created the folder, chownd it and reactivated the system protection, but still the same problem.

**Comment by DomT4** [comment]
Can you `ls -l /usr` please?

**Comment by x2on** [comment]
```
total 0
drwxr-xr-x@   10 root          wheel   340B 12 Sep 13:28 .
drwxr-xr-x    31 root          wheel   1,1K 12 Sep 14:55 ..
drwxr-xr-x     3 root          wheel   102B 27 Aug 04:17 adic
drwxr-xr-x  1055 root          wheel    35K 12 Sep 12:50 bin
drwxr-xr-x   262 root          wheel   8,7K 12 Sep 09:36 lib
drwxr-xr-x   184 root          wheel   6,1K 12 Sep 12:50 libexec
drwxrwxr-x     2 x2on          admin    68B 12 Sep 14:51 local
drwxr-xr-x   243 root          wheel   8,1K 12 Sep 09:28 sbin
drwxr-xr-x    45 root          wheel   1,5K 12 Sep 09:28 share
drwxr-xr-x     4 root          wheel   136B  3 Sep 13:00 standalone
```

**Comment by DomT4** [comment]
That looks alright. What about `ls -l /usr/local`. Maybe something inside `/usr/local` doesn't have write permissions.

**Comment by x2on** [comment]
```
total 0
drwxrwxr-x   2 x2on          admin   68B 12 Sep 14:51 .
drwxr-xr-x@ 10 root          wheel   340B 12 Sep 13:28 ..
```

I can't do anything in `/usr/local`, even as a admin:
```
$ sudo touch /usr/local/test
touch: /usr/local/test: Operation not permitted
```

**Comment by xu-cheng** [comment]
`ls -Ol /usr` should show more info.

**Comment by mikemcquaid** [comment]
This is something specific with your system. I did a clean install and couldn't reproduce this and have automatically run something similar on clean VMs through most of the betas.

**Comment by denji** [comment]
```
usage: csrutil <command>
Modify the System Integrity Protection configuration. All configuration changes apply to the entire machine.
Available commands:

    clear
        Clear the existing configuration. Only available in Recovery OS.
    disable
        Disable the protection on the machine. Only available in Recovery OS.
    enable
        Enable the protection on the machine. Only available in Recovery OS.
    status
        Display the current configuration.

    netboot
        add <address>
            Insert a new IPv4 address in the list of allowed NetBoot sources.
        list
            Print the list of allowed NetBoot sources.
        remove <address>
            Remove an IPv4 address from the list of allowed NetBoot sources.
```

**Comment by st3fan** [comment]
Same here, on 10.11 GM.

```
bash-3.2# mkdir /usr/local
mkdir: /usr/local: Operation not permitted
```

```
bash-3.2# csrutil status
System Integrity Protection status: enabled.
```

This is enabled by default. Disabling is a bad idea. Not sure what to do. Maybe move the Homebrew install to a place where it is not in a protected system area?

**Comment by DomT4** [comment]
Can people talk us through how they're upgrading here? Whether or not `/usr/local` existed before they upgraded, whether the install was a clean install, whether their user is the `admin` user, etc.

It is a known issue that if `/usr/local` doesn't exist before you upgrade you need to drop out of System Integrity Protection, create the folder & then reenable SIP. Given Apple advertised `/usr/local` as remaining open to developers we hope they're planning to automatically create the directory in the first stable release of El Cap.

None of us have come across this in testing, so we need to narrow this down.

**Comment by fulldecent** [comment]
I am running El Capitan 15A282b, which is labelled as "GM seed". This was an upgrade from mainline (not beta) 10.10 as of yesterday.

I did have `/usr/local` and a fully working brew system as of yesterday.

Today `/usr/local` does exist and include brew stuff.

Running `brew update` produces these results for me:

    brew update
    error: unable to unlink old '.yardopts' (Permission denied)
    error: unable to unlink old 'README.md' (Permission denied)
    Error: Failure while executing: git pull --quiet origin refs/heads/master:refs/remotes/origin/master

**Comment by DomT4** [comment]
@fulldecent Can you provide the `ls -Ol /usr` response? Also what do you see if you attempt to:

```
sudo chown -R $(whoami):admin /usr/local
```
?

**Comment by st3fan** [comment]
@DomT4 I must admit that my Homebrew install was in a bad shape and my usual remedy is to simply `rm -rf /usr/local` and start over with a clean install. So in my case, I did remove `/usr/local` manually and I did not know the consequences of that action in 10.11.

I'm not asking for magic. Actually, I am, if there is a way to fix this without having to reboot in the system recovery then that would be awesome. But I assume there is nothing we can do. (Otherwise this SIP would not be so secure).

So I think Homebrew should at least detect that SIP is enabled and give some hints to the user on how to fix it if `/usr/local` is missing. Maybe just link to a wiki page. I think many folks are going to run into this.

**Comment by fulldecent** [comment]
I get: 

````
$ ls -Ol /usr
total 8
lrwxr-xr-x     1 root  wheel  restricted     8 Jul  6  2014 X11 -> /opt/X11
drwxr-xr-x     3 root  wheel  restricted   102 Aug 26 22:17 adic
drwxr-xr-x  1062 root  wheel  restricted 36108 Sep 15 13:24 bin
drwxr-xr-x   262 root  wheel  restricted  8908 Sep 10 13:05 lib
drwxr-xr-x   184 root  wheel  restricted  6256 Sep 15 13:24 libexec
drwxrwxr-x    21 root  admin  -            714 Sep 14 16:54 local
drwxr-xr-x   243 root  wheel  restricted  8262 Sep 10 12:56 sbin
drwxr-xr-x    45 root  wheel  restricted  1530 Sep 10 12:56 share
drwxr-xr-x     4 root  wheel  restricted   136 Sep  3 07:00 standalone
````

And success with:

````
williamentriken at FDBOOK in ~
$ sudo chown -R $(whoami):admin /usr/local
Password:

williamentriken at FDBOOK in ~
$ echo $?
0

williamentriken at FDBOOK in ~
$ brew update
Updated Homebrew from 02e5c4a8 to 220d3008.
==> New Formulae
homebrew/boneyard/cppdom
==> Updated Formulae
ace				     gpg-agent				  libtins
awscli				     homebrew/science/armadillo		  lrdf
bfg				     homebrew/science/bedtools		  mktorrent
bulk_extractor			     homebrew/science/biointerchange	  openrtsp
davix				     homebrew/science/bpipe		  pev
elasticsearch			     lhasa				  shadowsocks-libev
==> Deleted Formulae
cppdom
````

**Comment by DomT4** [comment]
@st3fan If you removed `/usr/local` you will indeed need to disable SIP temporarily, drop back into OS X, recreate `/usr/local` and then back into Recovery Mode to re-enable SIP. Apple has provided no other known workaround to the removal of that directory.

It's likely I'll end up writing up a *"So El Capitan killed your Homebrew"* kind of document later this week with some of the basic troubleshooting stuff.

@fulldecent Glad is working as expected for you again!

**Comment by x2on** [comment]
@DomT4 recreating the folder didn't helped here. After enabling the SIP mode I can't create any files in the folder even if I'm sudo :(

**Comment by x2on** [comment]
I also created a radar: http://openradar.appspot.com/22736899

**Comment by DavidStaron** [comment]
@x2on try this:

- reboot into recovery, disable SIP, reboot
- now with SIP disabled, recreate:
``` 
sudo rmdir /usr/local
sudo mkdir /usr/local
sudo chflags norestricted /usr/local
```
- reboot, into recovery and re-enable SIP, reboot

**Comment by chris-araman** [comment]
Thanks, @DavidStaron. This seems to have worked for me.

* reboot into recovery
```
csrutil disable
```
* reboot
```
sudo rm -rf /usr/local
sudo mkdir /usr/local
sudo chflags norestricted /usr/local
sudo chown -R $(whoami):admin /usr/local
sudo chown $(whoami):admin /usr/local
```
* reboot into recovery
```
csrutil enable
```
* reboot
```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

**Comment by x2on** [comment]
@chris-araman thanks the `chflags` command was the missing part. With that it worked.

**Comment by DomT4** [comment]
There's now a document for this [here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md) which the Troubleshooting page points at. Hopefully clears up future confusion/problems/etc. We'll be adding a `brew doctor`/etc warning soon as well.
