### ISSUE TITLE
brew update fails on taps without a master branch

### ISSUE THREAD

**Issue by samdmarshall** [Homebrew/homebrew#43865]
Hi, I made a new repo for my homebrew formulae and have run into an issue where I cannot update my tap because there is no branch labeled "master" as part of the repo. Some investigation into this found the problem lies [here](https://github.com/Homebrew/homebrew/blob/12fa55ffb258225ff85cb2b1827b2e1175decaaa/Library/Homebrew/cmd/update.rb#L197-L199). I ran `brew update --debug --verbose` and if you look at the log file [here](https://gist.github.com/samdmarshall/c104b7f4c7869ac244b1#file-brew-update-failure-log-L29-L32) it appears that regardless of the current branch the tap is on, it will try to switch to master. I checked the issues list and found the reasoning for this in (#43472). I don't propose changing that behavior but I think there needs to be some handling around the case that there can be repos without a master branch, or at the very least updated documentation to indicate that having a branch labeled "master" is a requirement as part of the tap documentation [here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/brew-tap.md). Thanks!

**Comment by mistydemeo** [comment]
Should be fixed, thanks for the report!

**Comment by samdmarshall** [comment]
I'm not going to reopen this but I want to leave this comment as a note that it appears that it updates taps before updating homebrew itself ([see log here](https://gist.github.com/samdmarshall/f7185b6247c3b3e17531)). This could potentially be an issue as a user would have to run `brew update` multiple times before the error resolves itself because of update ordering. If you would like me to open a separate issue on that I can, but i felt i should leave this note here incase anyone else runs into the same issue. Thanks again for fixing this!
