### ISSUE TITLE
mtr needs root and the colors are wrong

### ISSUE THREAD

**Issue by 5c0tt** [Homebrew/homebrew#43862]
the homebrew mtr has two problems.  The first, all of a sudden in one of the updates, it takes over the colors of your shell.  It used to inherit the colors of your shell, or go to a nice black screen if you had no color theme set up.

It also did not used to need root.  Or perhaps I should say, I used to run the non homebrew version, and hand installed it.  Which I have done again.  The binary is setuid root do you don't have to `sudo mtr`.  Is it adjacent homebrew policy to setuid?

At the very least, there is a bug in how it deals with color.

**Comment by 5c0tt** [comment]
I found that this is also an issue in source 0.85 is ok, is started in 0.86, and MacPorts has added this patch to their system: https://github.com/traviscross/mtr/commit/63a1f1493bfbaf7e55eb7e20b3791fc8b14cf92d

Can someone who knows how add this patch as well?

**Comment by mikemcquaid** [comment]
@5c0tt Homebrew doesn't `setuid` and Homebrew can't even if we did as it isn't run as root. The colour bug seems to be an upstream bug. Is that commit in the upstream repository? If so, we can add it as a `patch do`. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by 5c0tt** [comment]
I just installed 0.85 and the color bug is not in it. I don't know if the patch is upstream.  Mac Ports has an ability to apply a patch to source from their ports files, which I assume are a lot like the ruby files that brew uses.  In this case, I just uninstalled mtr from brew and installed version 0.85 by hand.

Hoever, I am pretty green to git, and don't know all the terms. I don't know if that is an upstream repo, nor do I know how to find out, I have the link that i found in google, and that is it, just the same data as you.

It looks like brew can take a patch the same way, so the patch code is there, but I would have no idea how to open a pull request.

I see you linked to instructions, which I will try to follow. Though this is about 5 lines, it may be simpler for you to just make the pull request, pop the code change in, and merge it with brew, or whatever it is that happens.

I will post back here if I make any progress, it will be later this evening.

**Comment by mikemcquaid** [comment]
You can apply `https://github.com/traviscross/mtr/commit/63a1f1.patch` in a `patch do` block.

**Comment by 5c0tt** [comment]
I have no idea what a `do block` is :)
I will dig into the docs later this evening, it is something i need to learn.  There are my own projects that I manage, simple shell scripts and stuff, I edit them locally and just issues a git push origin master after I add a commit messages and the files I worked on.

But I have never pulled down someone else repo, made edits, and submitted it.  Or do I not have to pull it down and I can somehow just put the patch right into github.

Any relevant links for a relative new user to github and git would be appreciated.  I know my way around a shell on Mac OS X, Unix, and Linus systems of most varieties.  I have stumbled upon most every OS aside from windows over the last 20 years of working on computers and writing code.  But I am a lowly php and shell scripture that can get by really well in AppleScript as much as I hate it, and hobble along in perl, ruby, python, and a few others.  Even php, I am out of date, JavaScript too.  I stepped away from progrmming for 5 years and am just now coming back to a world of php that pushes objects and other stuff that are new to me.  I was a pretty top to bottom procedural guy.

I read a ton of docs and online tutorials, so I should be able to get this, system config stuff like this is usually something I can wrap my head around.

Thanks if you can help with any links or pointers, but one way or the other I will try to figure it out.

**Comment by denji** [comment]
```ruby
  do patch
    url "https://github.com/traviscross/mtr/commit/63a1f14.patch"
    sha256 "67d682b29fca49d703f48bb2844e1c0e4b4635d0645d139a13352d9575336194"
  end
```

**Comment by DomT4** [comment]
@denji Not quite :)

```ruby
stable do
  url "ftp://ftp.bitwizard.nl/mtr/mtr-0.86.tar.gz"
  sha256 "c5d948920b641cc35f8b380fc356ddfe07cce6a9c6474afe242fc58113f28c06"

  # My patch fixes this problem
  patch do
    url "https://github.com/traviscross/mtr/commit/63a1f14.patch"
    sha256 "67d682b29fca49d703f48bb2844e1c0e4b4635d0645d139a13352d9575336194"
  end
end
```

**Comment by rakkesh** [comment]
`brew install mtr` fails after applying the above patch,

```sh
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /private/tmp/mtr20150925-78473-16trk79/mtr-0.86/missing aclocal-1.14 
/private/tmp/mtr20150925-78473-16trk79/mtr-0.86/missing: line 81: aclocal-1.14: command not found
WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [aclocal.m4] Error 127
```
We need to add, `depends_on "automake" => :build`

Also, `--without-glib` is not recognised by the `./configure` script, and also compiles without `glib` dependency. @DomT4 @mikemcquaid any suggestions?

**Comment by DomT4** [comment]
Should be fixed by https://github.com/Homebrew/homebrew/commit/290a8d29d8c310cfb76fd7489455aa8e5dd54f2c.
