### ISSUE TITLE
tidy-html5 5.0.0

### ISSUE THREAD

**Issue by vielmetti** [Homebrew/homebrew#43860]
tidy-html5 has a 5.0.0 release, noted here

https://github.com/htacg/tidy-html5/releases/tag/5.0.0

which would be great to get into homebrew. I've opened up the issue on that project here:

https://github.com/htacg/tidy-html5/issues/253

**Comment by mikemcquaid** [comment]
`brew update`; it already has been.

**Comment by vielmetti** [comment]
Thank you (and sorry, should have done `brew update` first).
