### ISSUE TITLE
brew doctor returns with error exit code (1) after warning, instead of (0)

### ISSUE THREAD

**Issue by edrozenberg** [Homebrew/homebrew#43879]
Running brew doctor on OSX El Capitan (10.11) displays an El Cap warning.
brew doctor then returns with exit code (1) which is the exit code for errors.
However there is no error here so the exit code should be (0).

    $ brew doctor

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
```

    $ echo $?
    1

**Comment by mikemcquaid** [comment]
All `brew doctor` warnings are warnings. We don't support 10.11 yet.
