### ISSUE TITLE
frescobaldi failed to build on 10.11/Xcode7

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#43919]
https://gist.github.com/32dabf479c8c83e3693b

Fails to find sipdistutils.

```
  File "setup.py", line 42, in <module>
    import sipdistutils
ImportError: No module named sipdistutils
```

**Comment by bikeNomad** [comment]
Same result on 10.10.4

**Comment by tdsmith** [comment]
Likely fixed by #45076.

**Comment by brumleygap** [comment]
Is there a workaround or fix for this issue, or is Frescobaldi no longer supported?

**Comment by DomT4** [comment]
Waiting on Tim's PR, whenever he's happy with it.
