### ISSUE TITLE
mktorrent failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#43927]
https://gist.github.com/3ef67948b9591e18f749

Can't find OpenSSL.

```
#include <openssl/sha.h> /* SHA1() */
         ^
1 error generated.
make: *** [hash_pthreads.o] Error 1
```

**Comment by DomT4** [comment]
Closing in favour of #43928. Same comment from the other thread applies here re PR closing as well :)
