### ISSUE TITLE
"pip3 install matplotlib" fails with python 3.5

### ISSUE THREAD

**Issue by hombit** [Homebrew/homebrew#43949]
"pip3 install matplotlib" cannot find Python.h with python3 upgraded to 3.5:
```
_configtest.c:1:10: fatal error: 'Python.h' file not found
    #include <Python.h>
             ^
    1 error generated.
```

I can find Python.h for 3.5 only here:
```
/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/include/python3.5m/Python.h
```

**Comment by tdsmith** [comment]
Can you run `pip3 install -v matplotlib > out.txt` and post out.txt to [gist](https://gist.github.com)? I think this is a manifestation of the issue described in #43916.

**Comment by hombit** [comment]
This is it:
https://gist.github.com/hombit/a5955ca399a6848ac24d

**Comment by tdsmith** [comment]
Indeed, this is happening during setuptools's attempt to build numpy because it hasn't been otherwise installed, so the workarounds described in #43916 should help.
