### ISSUE TITLE
Tig: etc/tigrc not updated during upgrade from 2.0.2 to 2.1.1

### ISSUE THREAD

**Issue by jonas** [Homebrew/homebrew#43958]
Since [Tig version 2.0](https://github.com/jonas/tig/blob/master/NEWS.adoc#tig-20), the system-wide `tigrc` file is where all default options are defined. When packaged files destined for `/usr/local/etc` are not automatically updated when a package is upgraded to a new version, it leads to broken and unexpected behaviour as reported in jonas/tig#407 where a default setting is missing when running Tig version 2.1.1 because it was added in Tig version 2.0.3 and thus not in the `tigrc` install for Tig version 2.0.2.

My proposed fix is to package Tig without a `/usr/local/etc/tigrc` so that it falls back to use the internal (and always updated) `tigrc` copy. Alternatively, a `tigrc.sample` can be included in either `/usr/local/etc` or `/usr/local/Cellar/tig/x.x.x/etc` allowing a system admin to rename if system-wide options need to be overridden. If this is acceptable I suggest that I first add a `--disable-tigrc-install` option to Tig's `configure` script after which upgrading the formulae should be trivial.

**Comment by DomT4** [comment]
Closing in favour of https://github.com/Homebrew/homebrew/pull/44055, Thanks!
