### ISSUE TITLE
New Formula Question - User Input

### ISSUE THREAD

**Issue by kvarga** [Homebrew/homebrew#43957]
Is there an ability (or existing formula) that asks for user input when package is installed?

For example, the package I want to install is available only on people's own instances of a software,  so I need their base domain to get the installer. 

Thanks

**Comment by tdsmith** [comment]
Homebrew doesn't provide facilities for interactivity.

In general, there's not much support for passing arbitrary values into formulas. There's an option syntax which sort of works (it's not persisted on upgrades) but we may remove it without notice: https://github.com/Homebrew/homebrew/issues/32859
