### ISSUE TITLE
Update to Node.js v4.0.0

### ISSUE THREAD

**Issue by njl07** [Homebrew/homebrew#43965]
Hello,

When migration to Node.js v4.0.0 will be performed?

Thanks in advance for your collaboration,

Best regards.

**Comment by burak-son-sociomantic** [comment]
There is a blocker for the time being. https://github.com/Homebrew/homebrew/pull/43714#issuecomment-139133891

**Comment by burakson** [comment]
There is a blocker for the time being. https://github.com/Homebrew/homebrew/pull/43714#issuecomment-139133891

**Comment by mikemcquaid** [comment]
As @burakson said.
