### ISSUE TITLE
brew upgrade flow fails on 10.11 but fresh install works.

### ISSUE THREAD

**Issue by gabelevi** [Homebrew/homebrew#43969]
Originally reported in https://github.com/facebook/flow/issues/794, some users noticed that the brew upgrade path for Flow doesn't work, but a fresh install or re-install works fine.

Are you guys aware of any issues around upgrade paths not working while fresh installs work fine?

I can definitely dig into it more, but I wanted to ask first, since each attempt at repro-ing means I have to reimage a computer to 10.10 and then upgrade it to 10.11 :/

**Comment by DomT4** [comment]
I wasn't able to reproduce this locally going back to the 0.4.0 checkout, installing that, checking out an up-to-date master and then running `brew upgrade` on it. Any chance anyone upstream still has build logs or remembers the failure they saw in more detail?

**Comment by DomT4** [comment]
Presuming no further issues via lack of response, but please let us know if you're seeing any issues still. Thanks!
