### ISSUE TITLE
byobu-config ERROR: Could not import the python snack module

### ISSUE THREAD

**Issue by semone** [Homebrew/homebrew#43970]
After installing byobu  on OSX Yosemite 10.10.3 and try to run 
byobu-config I get the error: **ERROR: Could not import the python snack module**
Newt seems to be installed (which should provide snack).

```shell
$ brew info newt
newt: stable 0.52.18 (bottled)
Library for color text mode, widget based user interfaces
https://fedorahosted.org/newt/
/usr/local/Cellar/newt/0.52.18 (84 files, 596K) *
  Built from source with: --with-python
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/newt.rb
==> Dependencies
Required: gettext ✔, popt ✔, s-lang ✔
==> Options
--with-python
        Build with python support
```

This might be related to #31594, but it didn't help me much. 
Also noticed this old issue #17542, which confirms there are more people having the issue recently.

**Comment by tdsmith** [comment]
Can you share the output of `brew doctor`, `brew config`, and `brew info newt`?

**Comment by semone** [comment]
Here is the ```brew doctor``` and ```brew config output```, the ```brew info newt``` was shared in the previous comment 
```shell
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!


Warning: You have a curlrc file
If you have trouble downloading packages with Homebrew, then maybe this
is the problem? If the following command doesn't work, then try removing
your curlrc:
  curl https://github.com
```
```shell
$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: be7aed1d0905ec5b0562fed5cdd9b7cc4e99358d
Last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.10.3-x86_64
Xcode: 6.4
CLT: N/A
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
```

**Comment by tdsmith** [comment]
What files are in /usr/local/Cellar/newt/0.52.18/lib/python2.7/site-packages? Can you share `brew gist-logs newt`?

**Comment by semone** [comment]
So i didn't have the /usr/local/Cellar/newt/0.52.18/lib/python2.7/ directory. 
So I had the same problem you referred to here #43989

>ah. Looking at newt's configure script, it's not very clever. newt only looks in /usr/include for python headers. You should install the Xcode CLT to build the snack module with ```xcode-select --install``` and then run ```brew reinstall newt byobu```.

After doing that, it now works! Thanks!
