### ISSUE TITLE
Python 3 upgrade breaks Vim --with-python3 (Mavericks)

### ISSUE THREAD

**Issue by remy-actual** [Homebrew/homebrew#43983]
$brew update && brew upgrade python3
    ==> Upgrading python3
    ==> Downloading https://homebrew.bintray.com/bottles/python3-3.5.0.mavericks.bottle.1.tar.gz
    ######################################################################## 100.0%
    ==> Pouring python3-3.5.0.mavericks.bottle.1.tar.gz
    ==> /usr/local/Cellar/python3/3.5.0/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python3/3.5.0/bin --install-lib=/usr
    ==> /usr/local/Cellar/python3/3.5.0/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python3/3.5.0/bin --install-lib=/usr
    ==> /usr/local/Cellar/python3/3.5.0/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python3/3.5.0/bin --install-lib=/usr
    ==> Caveats
    ...
    ==> Summary
    🍺  /usr/local/Cellar/python3/3.5.0: 3415 files, 59M

    $vim
    dyld: Library not loaded: /usr/local/Frameworks/Python.framework/Versions/3.4/Python
    Referenced from: /usr/local/bin/vim
    Reason: image not found
    [1]    47124 trace trap  vim
    
    $ls -la /usr/local/Frameworks/Python.framework/Versions/
    total 24
    drwxrwxr-x  5 remy  admin  170 Sep 15 09:18 .
    drwxrwxr-x  6 remy  admin  204 Jul 21 21:38 ..
    lrwxr-xr-x  1 remy  admin   72 Jul 21 21:38 2.7 -> ../../../Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7
    lrwxr-xr-x  1 remy  admin   70 Sep 15 09:18 3.5 -> ../../../Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5
    lrwxr-xr-x  1 remy  admin   76 Jul 21 21:38 Current -> ../../../Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/Current

Vim won't load due to an old path reference to 3.4 which was replaced in the python3 upgrade with 3.5
Uninstalling and reinstalling vim fixes the problem:

    $brew install vim --with-lua --with-python3 --with-client-server --override-system-vi --with-tcl

Possibly related to use of absolute path [here](https://github.com/Homebrew/homebrew/issues/20327#issuecomment-23323024)?

**Comment by tdsmith** [comment]
This is expected; the rebuild is necessary. Thanks for reporting!

**Comment by remy-actual** [comment]
No problem. 
Would it make sense to add a warning? 
Either to python3 formula Caveats, or to the [bindings section](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-and-Python.md#homebrew-provided-python-bindings) of the referenced documentation?  
Running `$brew upgrade` and then having to stop and fix a broken code editor = not fun morning :neutral_face:

**Comment by tdsmith** [comment]
I know, sorry. We pushed
http://blog.tim-smith.us/2015/08/python-35-transition/ out to the mailing
list and Twitter. I hadn't considered the caveats of the python3 formula
but I think that's a reasonable place to give advice. (Though I think most
people ignore them!)

Tim
Sent from mobile

**Comment by remy-actual** [comment]
Ha, no apology necessary! 
Can't speak for anyone else, but caveats are my starting point for troubleshooting anything Homebrew related. 
Just sent a signup email to [homebrew@librelist.com](mailto:homebrew@librelist.com) for the mailing list. Thanks for the reply and the tip :smile:

**Comment by mikemcquaid** [comment]
> I know, sorry. We pushed
> http://blog.tim-smith.us/2015/08/python-35-transition/ out to the mailing
> list and Twitter. I hadn't considered the caveats of the python3 formula
> but I think that's a reasonable place to give advice. (Though I think most
> people ignore them!)

@tdsmith I think it's worth revisioning all the relevant formulae. Unfortunately I think this roll-out has shown that a blog post on Twitter and the mailing list isn't enough to reach our users and I think this rollout was a bit premature, honestly.

**Comment by tdsmith** [comment]
We were never going to hit awareness saturation and it's a breaking change for tools outside of Homebrew no matter when we pull the trigger. I wish I'd remembered that compiling numpy was broken but at least there are okay workarounds.

There are fewer formulas with optional :python3 dependencies than I'd imagined. In core, they are boost-python, hashpump, macvim, nghttp2, notmuch, pygobject3, pyqt, pyside, qscintilla2, shiboken, sip, uwsgi, and vim. Shall we revision them?

**Comment by mikemcquaid** [comment]
> There are fewer formulas with optional :python3 dependencies than I'd imagined. In core, they are boost-python, hashpump, macvim, nghttp2, notmuch, pygobject3, pyqt, pyside, qscintilla2, shiboken, sip, uwsgi, and vim. Shall we revision them?

Yeh, I reckon that's probably worth doing. Probably better to force an unnecessary rebuild than avoid a necessary one :+1:
