### ISSUE TITLE
cabal-install -- illegal hardware instruction on 10.11 GM

### ISSUE THREAD

**Issue by jhemono** [Homebrew/homebrew#43985]
Upgraded cabal (cabal-install package) from the latest bottle on El Capitan GM. While the install goes smoothly, the executable crashes with :
```
$ cabal -V
Illegal instruction: 4
```

Installing from source with ```brew install cabal-install --build-from-source ``` fixes the problem.

https://gist.github.com/jhemono/5311b65c2b0f949105e2

In this gist :
* ```brew gist-logs cabal-install``` (the big compilation log is irrelevant to this problem)
* Crash report when running ```cabal -V```

**Comment by DomT4** [comment]
Hmm. This worked okay for me, with a clean install of both `ghc` and `cabal-install`:

```
==> Summary
🍺  /usr/local/Cellar/ghc/7.10.2: 5428 files, 825M
==> Summary
🍺  /usr/local/Cellar/cabal-install/1.22.6.0: 6 files, 19M
~> cabal -V
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library
```

Did you have one installed before upgrading, or were they both fresh installs?

What's your `brew config`? Appears to be missing from the gist.

**Comment by jhemono** [comment]
I don't know what you mean by clean install so I did this :
```
~ > brew uninstall ghc cabal-install
Uninstalling /usr/local/Cellar/ghc/7.10.2... (5428 files, 825M)
Uninstalling /usr/local/Cellar/cabal-install/1.22.6.0... (6 files, 19M)
~ > brew install cabal-install
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Installing dependencies for cabal-install: ghc
==> Installing cabal-install dependency: ghc
==> Downloading https://homebrew.bintray.com/bottles/ghc-7.10.2.el_capitan.bottl
Already downloaded: /Library/Caches/Homebrew/ghc-7.10.2.el_capitan.bottle.1.tar.gz
==> Pouring ghc-7.10.2.el_capitan.bottle.1.tar.gz
🍺  /usr/local/Cellar/ghc/7.10.2: 5428 files, 825M
==> Installing cabal-install
==> Downloading https://homebrew.bintray.com/bottles/cabal-install-1.22.6.0.el_c
Already downloaded: /Library/Caches/Homebrew/cabal-install-1.22.6.0.el_capitan.bottle.tar.gz
==> Pouring cabal-install-1.22.6.0.el_capitan.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/cabal-install/1.22.6.0: 6 files, 19M
~ > cabal -V
Illegal instruction: 4
~ > ghci
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
λ: 
```
And I fixed the gist :
https://gist.github.com/jhemono/5311b65c2b0f949105e2

**Comment by apjanke** [comment]
Works for me too with a fresh install on my OS X 10.11 GM seed / Xcode 7 GM seed box. (15" Retina MacBook Pro, Mid 2014, 2.8 GHz Core i7).

```
$ date
Wed Sep 16 18:22:31 CDT 2015
[~]
$ brew install ghc cabal-install
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Downloading https://homebrew.bintray.com/bottles/ghc-7.10.2.el_capitan.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring ghc-7.10.2.el_capitan.bottle.1.tar.gz
🍺  /usr/local/Cellar/ghc/7.10.2: 5428 files, 825M
==> Downloading https://homebrew.bintray.com/bottles/cabal-install-1.22.6.0.el_capitan.bottle.tar.
######################################################################## 100.0%
==> Pouring cabal-install-1.22.6.0.el_capitan.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/cabal-install/1.22.6.0: 6 files, 19M
[~]
$ cabal -V
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library
[~]
$
```

All the other formulae on my machine were either poured from bottle or built with the same Xcode 7 GM seed. Is it possible some other linked files on the failing machine were built with a different Xcode? @jhemeno, which Xcode version do you have installed?

Similar thing happened with 10.10 beta. (#33314) Anyone ever figure out exactly what caused it?

**Comment by jhemono** [comment]
I have an old beta of Xcode 7.0, beta 4 (7A165t).

**Comment by apjanke** [comment]
Using a non-beta Xcode seemed to resolve this last time around. Hate to say this, but try upgrading to the Xcode 7 GM and `brew reinstall` everything. The non-beta Xcode was released to the public on September 16.

**Comment by jhemono** [comment]
It still doesn't work.

Installed Xcode 7 from the App Store. Deleted brews that I though might interfere with ghc but didn't need anymore (```llvm```, ```gmp```, ```libffi```, used for building idris from cabal). Now I have nothing related to ghc/cabal-install but ```xz``` (only ghc dependency) that I reinstalled from bottle. I tended to the problems that ```brew doctor``` signalled.

The fix in #33314 seems to suggest it was a problem with compiling the bottle with beta software, not a problem on the side of the user of the bottle.

**Comment by apjanke** [comment]
Right, I was just thinking that it might have been some of the locally installed stuff compiled with a beta Xcode, since I think the bottle is already build with non-beta Xcode. The `cabal-install` bottle was [built on Sept 12](https://github.com/Homebrew/homebrew/commit/00005abee1348b1a4e843e20507f91aa851be5cf), which I think would have been with Xcode 7 GM seed, which (I think) is the same as the final public release. @DomT4 or someone else, can you confirm which version of Xcode the brew test bot El Cap box was running then?

**Comment by DomT4** [comment]
It will have been running Xcode 7 GM, I believe.

**Comment by mikemcquaid** [comment]
@jhemono I've rebuilt the bottle. Can you try to `brew update` to at least 5618d7f and then `brew install cabal-install --force-bottle` and see if you still have issues? Thanks!

**Comment by jhemono** [comment]
It works!

For documentation, I was about to write that by running the executable with lldb I found that it raised an error on an instruction from the [AVX](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions) extension that my processor from 2009 doesn't support.

**Comment by DomT4** [comment]
Great! Thanks for the confirmation on the fix @jhemono.
