### ISSUE TITLE
sslyze fails to download

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#44006]
`sslyze` downloads openssl 1.0.2a as one of its resources, and that's 404 now on the main openssl.org site.

```
$ brew install sslyze
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Downloading https://github.com/nabla-c0d3/sslyze/archive/release-0.11.tar.gz
Already downloaded: /Library/Caches/Homebrew/sslyze-0.11.0.tar.gz
==> Downloading https://www.openssl.org/source/openssl-1.0.2a.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "sslyze--openssl"
Download failed: https://www.openssl.org/source/openssl-1.0.2a.tar.gz
```

Per #38661, it needs to link statically to that particular OpenSSL version, so I don't think we can just bump it. Should we grab it from a different mirror?

**Comment by apjanke** [comment]
Oh, nevermind. It just got moved to an "old" subdirectory on openssl.org. Will make a PR to fix the URL.

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew/commit/2918ed85cd3702f82a23f6672face0977cf14650.
