### ISSUE TITLE
sstp-client failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#44008]
https://gist.github.com/18be47b9dfafbabfc856

It's failing to find OpenSSL. But unlike the other formulae failing this way, it already `depends_on "openssl"`.

Looks like something in its configure isn't finding our brew-installed keg-only openssl?

```
checking for openssl/ssl.h in /usr/local/ssl... no
checking for openssl/ssl.h in /usr/lib/ssl... no
checking for openssl/ssl.h in /usr/ssl... no
checking for openssl/ssl.h in /usr/pkg... no
checking for openssl/ssl.h in /usr/local... no
checking for openssl/ssl.h in /usr... no
checking whether compiling and linking against OpenSSL works... no
configure: error: OpenSSL not found Hint: apt-get install libssl-dev
```

**Comment by m-elufimov-parc** [comment]
15A284 same result

**Comment by DomT4** [comment]
It looks like they've hardcoded a bunch of locations to check. If there's no `--with-ssl=` style configure switch we'll need to patch this.
