### ISSUE TITLE
spatialite-gui failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#44003]
https://gist.github.com/f6808e5265c0c1a124eb

It doesn't seem to be linking to the `sqlite3` library, even though that's specified as a dependency.

The error is a bunch of missing `sqlite`-related symbols.

```
Undefined symbols for architecture x86_64:
  "_sqlite3_backup_finish", referenced from:
      MyFrame::OnMemoryDbLoad(wxCommandEvent&) in Main.o
      MyFrame::MemoryDbSave() in Main.o
  "_sqlite3_backup_init", referenced from:
      MyFrame::OnMemoryDbLoad(wxCommandEvent&) in Main.o
      MyFrame::MemoryDbSave() in Main.o
  "_sqlite3_backup_step", referenced from:
      MyFrame::OnMemoryDbLoad(wxCommandEvent&) in Main.o
      MyFrame::MemoryDbSave() in Main.o
  "_sqlite3_bind_blob", referenced from:
```

The failing command doesn't seem to have `-L/usr/local/Cellar/sqlite/3.8.11.1/lib -lsqlite3` like I would expect.

> libtool: link: clang++ -I/usr/local/Cellar/wxmac/3.0.2/lib/wx/include/osx_cocoa-unicode-3.0 -I/usr/local/Cellar/wxmac/3.0.2/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DwxDEBUG_LEVEL=0 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__ -o spatialite_gui BlobExplorer.o Dialogs.o DialogsGraph.o Exif.o Main.o MalformedGeoms.o Network.o Objects.o QueryView.o QueryViewComposer.o ResultSetView.o Shapefiles.o TableTree.o TextCsv.o Wfs.o -Wl,-bind_at_load  -L/usr/local/Cellar/wxmac/3.0.2/lib -framework IOKit -framework Carbon -framework Cocoa -framework AudioToolbox -framework System -framework OpenGL -lwx_osx_cocoau_aui-3.0 -lwx_osx_cocoau_xrc-3.0 -lwx_osx_cocoau_webview-3.0 -lwx_osx_cocoau_html-3.0 -lwx_osx_cocoau_qa-3.0 -lwx_osx_cocoau_adv-3.0 -lwx_osx_cocoau_core-3.0 -lwx_baseu_xml-3.0 -lwx_baseu_net-3.0 -lwx_baseu-3.0 -L/usr/local/Cellar/libgaiagraphics/0.5_1/lib -L/usr/local/Cellar/libspatialite/4.3.0/lib -lspatialite -L/usr/local/Cellar/freexl/1.0.2/lib -lfreexl -L/usr/local/Cellar/libxml2/2.9.2/lib -lxml2 -lgaiagraphics /usr/local/Cellar/proj/4.9.1/lib/libproj.dylib -lpthread -lm -L/usr/local/Cellar/geos/3.4.2/lib -lgeos_c

Could this be some issue with detecting the Homebrew sqlite vs the system-provided one?

**Comment by ddegasperi** [comment]
I've the same problem:
https://gist.github.com/ddegasperi/00ea7d27d6af88c3aa48

**Comment by tannerhodges** [comment]
Same issue: 

Actually had this issue recommended from the brew output. First time seeing that—sweet feature for Homebrew.

**Comment by tannerhodges** [comment]
Awesome, install works now. Thanks for the fix!

**Comment by ddegasperi** [comment]
Confirm, it works now. Thank you!
