### ISSUE TITLE
tcpreplay failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#44011]
https://gist.github.com/a953e15e4a8a9431d601

It can't find libpcap, even though `fragroute`, which also requires libpcap, installs fine on the same system, is libpcap is present under that path under Xcode.

```
checking for libpcap... configure: error: Unable to find libpcap in /Applications/Xcode-7-GM.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr
```
But it's there.

```
spiffy-elcap% find /Applications/Xcode-7-GM.app/Contents/Developer/Platforms/MacOSX.platform -name pcap.h 2>/dev/null
/Applications/Xcode-7-GM.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/pcap/pcap.h
/Applications/Xcode-7-GM.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/pcap.h
spiffy-elcap%
```

If I remove the `"--with-libpcap=#{MacOS.sdk_path}/usr"`, the build succeeds, with configure saying it found libpcap.
```
checking for libpcap... /usr
```

**Comment by apjanke** [comment]
Aha!

I think the `configure` script is testing for particular library extensions.

```
            elif test -f "${withval}/libpcap.${libext}" ; then
                LPCAPLIB="${withval}/libpcap.${libext}"
```

But inside Xcode, they're `.tbd` files instead of `.dylib`s.

```
spiffy-elcap% find /Applications/Xcode-7-GM.app/Contents/Developer/Platforms/MacOSX.platform -name 'libpcap*' 2>/dev/null
/Applications/Xcode-7-GM.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib/libpcap.A.tbd
/Applications/Xcode-7-GM.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib/libpcap.tbd
spiffy-elcap% find /usr -name 'libpcap*' 2>/dev/null
/usr/lib/libpcap.A.dylib
/usr/lib/libpcap.dylib
spiffy-elcap%
```

**Comment by krisarmstrong** [comment]
Wondering if there is any solution to get TCPReplay to build on OSX10.11.  I have Xcode 7 installed

Here is the output

Kriss-MBP:~ krisarmstrong$ brew install tcpreplay
==> Downloading https://github.com/appneta/tcpreplay/releases/download/v4.1.0/tc
Already downloaded: /Library/Caches/Homebrew/tcpreplay-4.1.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/tcpreplay/4.1.0 --enable-dynamic-link
Last 15 lines from /Users/krisarmstrong/Library/Logs/Homebrew/tcpreplay/01.configure:
checking for strsignal... yes
checking for strpbrk... yes
checking for strrchr... yes
checking for strspn... yes
checking for strstr... yes
checking for strtoul... yes
checking for strlcpy... yes
checking whether byte ordering is bigendian... no
configure: Using u_int64_t for packet counters
configure: Forcing dynamic linking on OS X
checking for inet_aton... yes
checking for inet_pton... yes
checking for inet_ntop... yes
checking for inet_addr... yes
checking for libpcap... configure: error: Unable to find libpcap in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
tcpreplay failed to build on 10.11 https://github.com/Homebrew/homebrew/issues/44011
Warning: 
Kriss-MBP:~ krisarmstrong$
