### ISSUE TITLE
swiftlint failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#44010]
https://gist.github.com/ed9e108b4f332334912c

Looks like a Swift version compatibility problem, since there's a breaking change between Xcode 6 and 7.

I'm running Xcode 7 GM candidate. The `swiftlint` formula says this
```
  depends_on :xcode => ["6.4", :build]
```
but it doesn't seem to be catching the version mismatch and balking or giving useful error output.

**Comment by DomT4** [comment]
Formula was fixed recently.
