### ISSUE TITLE
podofo failed to build on OS X 10.10

### ISSUE THREAD

**Issue by perrygeo** [Homebrew/homebrew#44026]
https://gist.github.com/anonymous/dc5d00241fac1fb41948

**Comment by dmwelch** [comment]
Had the same issue.  After running `brew doctor` and addressing the issues there I was able to build podofo.  Mileage may vary, but here's what I needed to do:

* move MacPorts directory
* move OpenCV libraries out of `/usr/local`
* `$ unset DYLD_LIBRARY_PATH`
* `$ brew prune`
* `$ export PATH="/usr/local/sbin:$PATH"`

**Comment by luzpaz** [comment]
I haven't encountered this on 10.10 
@perrygeo can you run ``brew doctor`` and report results please?

**Comment by perrygeo** [comment]
@luzpaz  see the `doctor.out` file in the original gist
