### ISSUE TITLE
volatility failed to build (freetype2 header error)

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#44039]
https://gist.github.com/e49e9b8925cdb748296a

Fails to find freetype headers.

```
_imagingft.c:73:10: fatal error: 'freetype/fterrors.h' file not found
#include <freetype/fterrors.h>
         ^
1 error generated.
error: command 'clang' failed with exit status 1
```

It's looking in the `freetype/` subdirectory, but the headers in my Homebrew-installed freetype are under `freetype2/`.

```
$ find /usr -name fterrors.h 2>/dev/null
/usr/local/Cellar/freetype/2.6_1/include/freetype2/fterrors.h
```

**Comment by apjanke** [comment]
Same error on 10.9.5/Xcode 6.2. Not OS X specific.

**Comment by apjanke** [comment]
There's a new volatility 2.5 release out, but it doesn't fix this build error. Same issue.

```
building '_imagingft' extension
clang -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Tcl.framework/Headers -I/System/Library/Frameworks/Tk.framework/Headers -I/usr/local/include/freetype2 -IlibImaging -I/System/Library/Frameworks/Python.framework/Versions/2.7/include -I/usr/local/include -I/usr/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c _imagingft.c -o build/temp.macosx-10.9-intel-2.7/_imagingft.o
_imagingft.c:73:10: fatal error: 'freetype/fterrors.h' file not found
#include <freetype/fterrors.h>
         ^
1 error generated.
error: command 'clang' failed with exit status 1
```

Don't know if it's that it isn't compatible with newer versions of freetype, or what. No freetype dependency is listed on their web page, and adding `depends_on "freetype"` in the formula doesn't help.

Based on [this SO answer](http://stackoverflow.com/questions/20325473/error-installing-python-image-library-using-pip-on-mac-os-x-10-9), it looks like Python Imaging Library is the thing with the freetype dependency. PIL 1.1.7 is vendored as a resource inside this formula. Don't know what to do next.

**Comment by apjanke** [comment]
Okay, so PIL hasn't been updated since 2009. (http://www.pythonware.com/products/pil/) Makes sense that it was written against an older version or installation style of freetype, and that it may not have seen this installation variation.

I guess we could just patch the vendored PIL to find our freetype2 headers. Its `setup.py` is just looking in a hardcoded list of locations.

```

        elif sys.platform == "darwin":
            # attempt to make sure we pick freetype2 over other versions
            add_directory(include_dirs, "/sw/include/freetype2")
            add_directory(include_dirs, "/sw/lib/freetype2/include")
            # fink installation directories
            add_directory(library_dirs, "/sw/lib")
            add_directory(include_dirs, "/sw/include")
            # darwin ports installation directories
            add_directory(library_dirs, "/opt/local/lib")
            add_directory(include_dirs, "/opt/local/include")
```

The `swatchbooker` formula seems to be the only one pulling in PIL. It uses the "Pillow" fork of it.
```
  depends_on "pillow" => [:python, "PIL"]
```

Changing `volatility` to do PIL this way (like [this](https://github.com/apjanke/homebrew/commit/d729e9f965e7ce3fa1cb294cbc155d73391c7573)) got it to build for me on 10.9 and 10.11. Anyone more familiar with Python or Volatility know if this is an acceptable switch for `volatility`?

**Comment by dunn** [comment]
:snake: @tdsmith :snake:

**Comment by tdsmith** [comment]
Oh, goodness, yes, this should definitely use Pillow. We should resource it instead of using the `=> :python` notation.

**Comment by apjanke** [comment]
Like this?  #45920 

I lifted the "pillow" resource handling from `mitmproxy` formula. Builds for me on 10.9 and 10.11. 

And should `swatchbooker` be switched to resource it, too?
