### ISSUE TITLE
nsd failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#44056]
https://gist.github.com/90114ce5d0798798994b

Can't find the OpenSSL headers, and adding `depends_on "openssl"` to the formula doesn't fix it.

```
checking for SSL... configure: error: Cannot find the SSL libraries in /usr/local/ssl /usr/lib/ssl /usr/ssl /usr/pkg /usr/sfw /usr/local /usr
```

Its configure is using openssl detection logic that looks in several hardcoded locations. Could this be an issue with for Homebrew-provided openssl? Do we need to provide a `--with-ssl=...`?

```
# Check for SSL, original taken from
# http://www.gnu.org/software/ac-archive/htmldoc/check_ssl.html and
# modified for NSD.
AC_DEFUN([CHECK_SSL], [
    AC_ARG_WITH(ssl, AC_HELP_STRING([--with-ssl=pathname],
                [enable SSL (will check /usr/local/ssl
                /usr/lib/ssl /usr/ssl /usr/pkg /usr/sfw /usr/local /usr)]),[
        ],[
            withval="yes"
        ])
    if test x_$withval != x_no; then
        AC_MSG_CHECKING(for SSL)
        if test x_$withval = x_ -o x_$withval = x_yes; then
            withval="/usr/local/ssl /usr/lib/ssl /usr/ssl /usr/pkg /usr/sfw /usr/local /usr"
        fi
```

**Comment by DomT4** [comment]
Some things insist on hardcoding a bunch of locations to check. It's not all that uncommon, sadly. Some form of the `--with-ssl=/path/to/this/openssl/plz` dance usually works, aye.

**Comment by apjanke** [comment]
That `--with-ssl=` worked. #44063
