### ISSUE TITLE
paq8px download is 403 Forbidden

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#44061]
Getting a SHA mismatch on `brew install paq8px`. Server is returning a 403 Forbidden HTML error page, even though downloading the same URL in Firefox works fine. Looks like it's filtering on user agents to forbid automated downloads.

If I update the SHA to accept the current download results, I get this.

```
$ brew install paq8px
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Downloading http://dhost.info/paq8/paq8px_v69.zip
Already downloaded: /Library/Caches/Homebrew/paq8px-69.zip
[/Library/Caches/Homebrew/paq8px-69.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Library/Caches/Homebrew/paq8px-69.zip or
        /Library/Caches/Homebrew/paq8px-69.zip.zip, and cannot find /Library/Caches/Homebrew/paq8px-69.zip.ZIP, period.
Error: Failure while executing: unzip -qq /Library/Caches/Homebrew/paq8px-69.zip
```

View of returned file in browser (extracted from the Homebrew download cache):

<img width="708" alt="screen shot 2015-09-16 at 9 13 52 pm" src="https://cloud.githubusercontent.com/assets/2618447/9923224/e75424d6-5cb7-11e5-909a-2c356cb51b6b.png">

The paq8 home page at http://dhost.info/paq8/ has no contact or mailing list info, or updates since 2012.

Download the files and set up a brew-friendly mirror? Boneyard?

**Comment by apjanke** [comment]
I emailed the original developer, Matt Mahoney, about contact for the new maintainers. He says:

> You might try the message board at encode.ru. I don't think there has
been any work on it for awhile though.

I searched the board; no PAQ-related posts on it in years. Sounds like boneyard time.

**Comment by bfontaine** [comment]
Yeah, boneyard. :skull:
