### ISSUE TITLE
Rust 1.3.0

### ISSUE THREAD

**Issue by frewsxcv** [Homebrew/homebrew#44079]
http://blog.rust-lang.org/2015/09/17/Rust-1.3.html

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
