### ISSUE TITLE
Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool

### ISSUE THREAD

**Issue by micooz** [Homebrew/homebrew#44071]
I've just upgraded my Xcode as well as Command Line Tools for Xcode to 7.0, and then homebrew encountered an `Error` problem:

    $ brew update && brew upgrade

> Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
> 
> Error: Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool

I re-run the `brew upgrade` as root via `sudo`, but it seems not work:

    $ sudo brew upgrade

> Password:
> Error: Cowardly refusing to `sudo brew upgrade`
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.

I checked the problem with `brew doctor`, it gived me the same error as sudo command.

**Comment by mikemcquaid** [comment]
Run `sudo xcodebuild -license` to agree to the Xcode license.

**Comment by DomT4** [comment]
Closing per the above. Let us know if you run into any further issues, Thanks!

**Comment by nevik** [comment]
If there's some reasonable way you can detect this specific problem (e.g. exit code?), it'd be awesome if you could add a hint to brew's output to run the `xcodebuild` command -- since the warning printed by `otool`/`xcodebuild` (without root) is quite misleading in the homebrew context.

**Comment by mikemcquaid** [comment]
@nevik Agreed. Have added to my todo list to investigate the error codes.

**Comment by nevik** [comment]
:+1:

**Comment by DomT4** [comment]
@mikemcquaid Could we not repurpose the code from the [installer](https://github.com/Homebrew/install/blob/master/install#L142-L147) and stick it in `brew.rb` so you can't run Homebrew until you've agreed to the license?

**Comment by mikemcquaid** [comment]
@DomT4 That'd work, yeh.

**Comment by JohNan** [comment]
If the proposed solution gives this error: ```xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance```
you can run the following command instead to get the license agreement popup: ```xcode-select --install```

**Comment by kathyonu** [comment]
Thank you for posting, and solving *Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool*
Using $ `xcode-select --install` solved my problem :thumbsup:

**Comment by yeelan0319** [comment]
Thank you for posting, I had exactly the same problem. Just additional to the above information, if your ```sudo xcodebuild -license``` doesn't work out like me, try upgrade your xcode first and then try this again. 
This helped me solve my problem upgrade my homebrew as well as install my ruby-gem.

**Comment by roddi** [comment]
Please reopen. I think brew should give a meaningful error message in this case.

**Comment by MikeMcQuaid** [comment]
@roddi We aren't reopening issues on this repository.

**Comment by johnnychen** [comment]
I tried 
* `sudo xcodebuild -license`
* `xcode-select --install`

But, not work.
