### ISSUE TITLE
HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by massimoselvi** [Homebrew/homebrew#44087]
I got this msg after I upfdated brew, I did it after =>"brew doctor":
"Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX"

massimoselvi -> /Users/massimoselvi/Code/MaurizioMonti_v.2/mauriziomonti.com_v2
==> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours. This is a long time in brewland!
To update Homebrew, run `brew update`.

START
massimoselvi -> /Users/massimoselvi/Code/MaurizioMonti_v.2/mauriziomonti.com_v2
==> brew update
Checking out files: 100% (2860/2860), done.
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:260:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:205:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:173:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:140:in `send'
/usr/local/Library/brew.rb:140

massimoselvi -> /Users/massimoselvi/Code/MaurizioMonti_v.2/mauriziomonti.com_v2
END

**Comment by DomT4** [comment]
See #42553. You won't see it again. Thanks for reporting it.
