### ISSUE TITLE
Unable to update Brew on 10.11

### ISSUE THREAD

**Issue by bnied** [Homebrew/homebrew#44107]
Just as it says on the tin. Seeing this on two different Macbooks running the GM Seed:

    [bnied@mars/u/local] (master) $ brew update
    error: unable to unlink old '.gitignore' (Permission denied)
    error: unable to create file .travis.yml (Permission denied)
    Error: Failure while executing: git pull --ff --no-rebase --quiet origin refs/heads/master:refs/remotes/origin/master

**Comment by DomT4** [comment]
`sudo chown $(whoami):admin /usr/local && sudo chown -R $(whoami):admin /usr/local` should work.

**Comment by bnied** [comment]
That did it! I had tried `sudo chown -hR bnied:admin` previously, but it worked this time. Thanks!

**Comment by DomT4** [comment]
Glad to hear all is working again :)

**Comment by zg** [comment]
Is there any reason why it would be a bad idea to make myself the owner of every file in `/usr/local`?

**Comment by DomT4** [comment]
OS X itself places nothing in `/usr/local`, so there's nothing on a vanilla system you'll de-root by owning it. 

If you're using a multi-user machine most people prefer to put Homebrew somewhere other than `/usr/local`. Other external software may install into `/usr/local` with `root` rights but are generally fine to not be root; very few non-system-installed tools actually need permanent root access.

**Comment by zg** [comment]
>OS X itself places nothing in `/usr/local`, so there's nothing on a vanilla system you'll de-root by owning it.

Well, then my question has been answered. :+1:

**Comment by renanalencar** [comment]
chown command doesn't work. It says "command not found"

**Comment by DomT4** [comment]
@renanalencar Can you provide the output of `echo $PATH`, Thanks.

**Comment by bnied** [comment]
@renanalencar you can also try manually specifying the path, i.e. `sudo /usr/sbin/chown $(whoami):admin /usr/local && sudo /usr/sbin/chown -R $(whoami):admin /usr/local`.

**Comment by renanalencar** [comment]
Renans-MacBook-Pro:~ renanalencar$ echo $PATH
/usr/local/var/mongodb/bin:/usr/local/Cellar/maven/3.3.3/libexec/bin:/Library/PostgreSQL/9.3/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Users/renanalencar/android-sdk-macosx/tools:/Users/renanalencar/android-sdk-macosx/platform-tools:/Library/Frameworks/Firebird.framework/Resources/bin:/usr/local/Cellar/ant/1.9.6/libexec//bin:/usr/sbin

**Comment by DomT4** [comment]
It should be there, in `/usr/sbin`. That's in your `$PATH` twice but not usually an issue. Does the:

```
sudo /usr/sbin/chown -R $(whoami):admin /usr/local
```

Command as suggested by @bnied work?

**Comment by renanalencar** [comment]
It still says: 
```
Renans-MacBook-Pro:~ renanalencar$ sudo /usr/sbin/chown $(renanalencar):admin /usr/local
-bash: renanalencar: command not found
```

**Comment by bnied** [comment]
You shouldn't be replacing `whoami` with your username; it'll do that for you. If you want to replace it manually, try `sudo /usr/sbin/chown renanalencar:admin /usr/local`.

**Comment by DomT4** [comment]
In that block of text you're passing `renanalencar` as a command. If you want to use your username directly you need to drop the surrounding `$()` from the name.

**Comment by renanalencar** [comment]
I'm sorry, guys! It worked perfectly.

**Comment by DomT4** [comment]
:tada: Glad to hear things are working again :). If you see regular problems finding utilities in `/usr/sbin` it may be worth rebuilding your `$PATH` to see where the failure point is there, but at least the immediate issue is resolved.

**Comment by shanecarmody** [comment]
:+1:
