### ISSUE TITLE
Feature Request: Link to changelog

### ISSUE THREAD

**Issue by CamJN** [Homebrew/homebrew#44108]
It would be fantastic to include a link to projects' changelogs in a similar fashion to `brew home`.

**Comment by dunn** [comment]
Not every project publishes changelogs, though, or keeps them up-to-date, so I'm not sure how feasible this is.

**Comment by DomT4** [comment]
We've shot this idea down before a couple of times because of the above and resulting inconsistency.

**Comment by mikemcquaid** [comment]
This would need to be handled like `brew desc`; implemented for all formulae outside of Homebrew core first and then we'd consider merging it back in.

**Comment by poliveira89** [comment]
@CamJN I thought about this need right now, and found your issue. IMHO, your suggestion could be a first approach to proof the concept and get reactions from users. But what do you think about parse `CHANGELOG.md` - could it be all the content, filter from version installed and available, etc...

@dunn and @DomT4  Could be managed by a flag on the formula? Or is not possible?

**Comment by DomT4** [comment]
It's not really something I want to personally support unless we can roll it out consistently, and the chances of being able to find and link 3400+ Changelogs to the appropriate formula and keep those updated seems like a lot of pain and time for a relatively small return. It could be done, it's certainly not technically impossible.

As Mike hinted above checking out the way the original `brew desc` project handled this sort of thing may be useful to you. It should be possible to add an external command such as `brew changes openssl` which finds the changelog and supplies it in some semi-concise useful way.

**Comment by bfontaine** [comment]
@poliveira89 You can try it in a separate tap with a custom command; this is how [`brew-desc`](https://github.com/telemachus/homebrew-desc) started and now it’s part of the core. You could e.g. have a command like `brew changes <formula>` that’d tell you the latest changes for this formula.

See https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md#external-commands

**Comment by poliveira89** [comment]
@DomT4 That scenario for the available formulas could be horrifying. But, for the suggestion I gave, it was not intend for the project contributors to maintain that, after then make some kind of "formula changes". The "changelog changes" per formula should be done by formula maintainer. Probably, the homebrew contributors are the maintainers for the most of the formulas. Still, I understand your concerns and I surely agree with `lot of pain and time for a relatively small return`. Thanks for the answer.

@bfontaine I have a look into it. Thanks! :)

**Comment by DomT4** [comment]
@poliveira89 We don't really have formula maintainers, for what it's worth. Contributors do handle many of the formula updates, but there's no system of Bob handles `node` and Jane handles `a2ps` or such.
