### ISSUE TITLE
duti won't build under --env=std on Xcode 7.0

### ISSUE THREAD

**Issue by chdiza** [Homebrew/homebrew#44119]
I know we're supposed to build things under superenv, but the nature of this error seemed a bit strange, and possibly indicative of something that needs to be fixed.  But I'm not really sure, so I'm asking here.

On 10.10.5 and Xcode 7.0 (together of course with the 7.0 edition of the CLT), brewing `duti` under `--stdenv` gives this:
```
/usr/bin/clang -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.10 -Wall -Wmissing-prototypes -Os -w -pipe -march=native -mmacosx-version-min=10.10 -c ./handler.c
./plist.c:1:10: fatal error: 'CoreFoundation/CoreFoundation.h' file not found
#include <CoreFoundation/CoreFoundation.h>
         ^
./handler.c:1:10: fatal error: 'ApplicationServices/ApplicationServices.h' file not found
#include <ApplicationServices/ApplicationServices.h>
         ^
./util.c:1:10: fatal error: 'CoreFoundation/CoreFoundation.h' file not found
1 error generated.
#include <CoreFoundation/CoreFoundation.h>
         ^
make: *** [plist.o] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
make: *** [util.o] Error 1
1 error generated.
make: *** [handler.o] Error 1
```

It seems strange to me that a header file would fail to be found even under stdenv.  Usually stenv finds "too much", not too little, at least in my experience.

Even if this is indicative of some underlying bug, I have no idea whether it's in Homebrew or `duti`.

**Comment by mistydemeo** [comment]
duti's buildsystem is setting a sysroot inside the Xcode SDK:

> clang -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk

And that SDK doesn't exist in Xcode 7. Since it's setting `-isysroot`, it means it doesn't find the versions of those headers installed in `/System/` even though you have the CLT installed. This works in superenv since superenv's flag filtering removes `-isysroot` and sets appropriate flags.

I actually get the same error as you on a CLT-only system under stdenv, since duti is looking for an SDK that can't exist without Xcode installed.

**Comment by chdiza** [comment]
OK, thanks!

So is it a bug in Xcode 7 that the SDK for 10.10 is missing?  The release notes from Apple say Xcode 7 is for Yosemite as well as ElCap.

**Comment by mistydemeo** [comment]
I'm not sure if it's a "bug", it seems to possibly be an intentional decision? It is an unusual one.

Duti's buildsystem is passing unnecessary flags though, and that's more of the real issue.

**Comment by chdiza** [comment]
I reported it upstream.
