### ISSUE TITLE
pixman fails to build on 10.10 with Xcode 7

### ISSUE THREAD

**Issue by UniqMartin** [Homebrew/homebrew#44122]
Issue #41075 fixed `pixman` on 10.11, but the problem also affects 10.10 as the root cause is in the recent update to Xcode 7 (respectively the included Clang).

My workaround was to replace
```
args << "--disable-mmx" if MacOS.version >= :el_capitan
```
with
```
args << "--disable-mmx" if ENV.compiler == :clang
```
in the `pixman` formula. I'm not entirely happy with this fix, though. Should MMX be disabled unconditionally? Is there a better way to check for the used compiler, maybe even for specific versions of Clang?

**Comment by mikemcquaid** [comment]
Disabling unconditionally seems fine :+1:. Could you submit a PR?

**Comment by UniqMartin** [comment]
Thanks! Just did.

**Comment by DomT4** [comment]
Closing in favour of #44132.
