### ISSUE TITLE
python: Create `pdb` symlinks in the local `bin` directory 

### ISSUE THREAD

**Issue by StefPac** [Homebrew/homebrew#44128]
Linux distributions like Debian and Ubuntu create a symlink to the the `pdb.py` script installed in `/usr/bin` - tools like Emacs rely on this behavior. 

For example with the latest version of python `/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pdb.py` should be linked to `/usr/local/bin/pdb3` or `/usr/local/bin/pdb`

**Comment by tdsmith** [comment]
Since this doesn't exist on all systems I think you should file against emacs and urge them to invoke `python -m pdb` instead, which is more likely to work and reduces the ambiguity wrt which interpreter will be invoked.

**Comment by StefPac** [comment]
I submitted http://debbugs.gnu.org/cgi/bugreport.cgi?bug=21521

**Comment by tdsmith** [comment]
Thanks! I think we shouldn't make this change in Homebrew so I'll close this.
