### ISSUE TITLE
gnuplot failed to build on 10.10

### ISSUE THREAD

**Issue by aleph7** [Homebrew/homebrew#44127]
https://gist.github.com/239f2066d34600478632

It was installed then I tried to reinstall with Qt and it never worked with either Qt or aquaterm. It still works by skipping both `--with-qt` and `--with-aquaterm`. May haven been affected by the fact that I installed Torch.

**Comment by DomT4** [comment]
Can you try `brew reinstall lua`?

**Comment by aleph7** [comment]
that worked, thanks
