### ISSUE TITLE
Formula request: rtv - reddit terminal viewer

### ISSUE THREAD

**Issue by andreis** [Homebrew/homebrew#44129]
https://github.com/michael-lazar/rtv

**Comment by dunn** [comment]
It looks like it meets the notability requirements, so we'd be happy to review a pull request!  If you're interested in contributing, take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have any questions!

**Comment by andreis** [comment]
I guess I've been spoiled by the nice `brew-cask` community, heh.

**Comment by dunn** [comment]
Ah, yeah. Since we have to build everything from source, adding a new formula is a bit more work.

**Comment by brettmichael** [comment]
I've just published a pull request with rtv in it:

https://github.com/Homebrew/homebrew/pull/49368
