### ISSUE TITLE
Error: Failure while executing: git stash save --include-untracked --quiet

### ISSUE THREAD

**Issue by dossan** [Homebrew/homebrew#44134]
I am trying to update brew with one of the following commands:

    brew update

or 

    sudo brew update

but I keep getting the following error:

~~~
Stashing your changes:
UD Library/Formula/dmd.rb
Library/Formula/dmd.rb: needs merge
Library/Formula/dmd.rb: needs merge
Library/Formula/dmd.rb: unmerged (8c4d095ab5961cd931633b5ea479306ae2b2475e)
Library/Formula/dmd.rb: unmerged (d3b5cb46013a5b14e6852ebe31ed69b47fbfd645)
fatal: git-write-tree: error building trees
Cannot save the current index state
Error: Failure while executing: git stash save --include-untracked --quiet
[cell@Nelsons-MacBook-Pro: Library]$ cd ~
~~~

I guess `dmd` refers to the installed and reinstalled and then uninstalled D compiler that I was messing with...

If I go under `Library` I have no `Formula` folder, why is this?

By the way, what it means here to `Stashing your changes`?

**Comment by DomT4** [comment]
Unless you've intentionally modified the `dmd` formula I'd try this:

```
cd $(brew --prefix) && git fetch && git reset --hard origin/master
```

**Comment by dossan** [comment]
@DomT4 What should this do exactly?

**Comment by DomT4** [comment]
Goes into the `HOMEBREW_PREFIX`, fetches the latest commit here, and then resets all local changes to the Homebrew repository/formulae to match Homebrew at the point of latest commit, essentially.

**Comment by giacgbj** [comment]
@DomT4 Same error. I tried your command but "git fetch" returns 
```
fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by DomT4** [comment]
@giacgbj It looks like your git repository got corrupted a bit there for some reason. You can check where the remotes are pointing at with `git remote -v`. Glad you've got it working again at least.

**Comment by DomT4** [comment]
Presuming resolved via lack of response, but please let us know if you're seeing any issues still. Thanks!
