### ISSUE TITLE
Brew command not found

### ISSUE THREAD

**Issue by ebh123** [Homebrew/homebrew#44144]
Total novice here. Thought I installed homebrew (on Mac OS 10.11.1) but then got some weird errors. Trying to do the install process again and getting error

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
dyld: Library not loaded: /usr/local/lib/libgmp.10.dylib
  Referenced from: /Users/threeezy/.rvm/rubies/ruby-2.2.2/bin/ruby
  Reason: image not found
Trace/BPT trap: 5

Tried running brew doctor and getting the following

// ♥ brew doctor
-bash: brew: command not found

Any ideas on how to fix this?

**Comment by DomT4** [comment]
Usually by sticking:

```
export PATH=/usr/local/bin:$PATH
```

In your shell profile somewhere.

**Comment by ebh123** [comment]
How do I go about doing that?

**Comment by mistydemeo** [comment]
It looks like the install failed because you're using a broken RVM ruby. Try `rvm use system`, then running the install command again.

**Comment by DomT4** [comment]
Misty is right here. I misread and thought it had already been installed and you couldn't find the `brew` command because the `$PATH` hadn't been set, but at second glance it doesn't get that far.

If it is still a problem after install, presuming you're using bash:
```bash
echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bash_profile
```

**Comment by DomT4** [comment]
Presuming resolved via lack of response, but please let us know if you're seeing any issues still. Thanks!

**Comment by krishnatest** [comment]
Preview
Sorry! We couldn't save your comment — your comment cannot be blank. Please try again.
Sorry! We couldn't save your comment — your comment cannot be blank. Please try again.
