### ISSUE TITLE
Having trouble installing DevIL using homebrew

### ISSUE THREAD

**Issue by Cuppas0up** [Homebrew/homebrew#44154]
I entered this:

    brew install devil
and got this:

    Error: devil cannot be built with any available compilers.
    To install this formula, you may need to:
      brew install gcc

So I reinstalled gcc and got this:

    Toms-MBP:~ tom$ brew install gcc
    ==> Downloading https://homebrew.bintray.com/bottles/gcc-5.2.0.yosemite.bottle.1.tar.gz
    ######################################################################## 100.0%
    ==> Pouring gcc-5.2.0.yosemite.bottle.1.tar.gz
    ==> Caveats
    GCC has been built with multilib support. Notably, OpenMP may not work:
      https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60670
    If you need OpenMP support you may want to
      brew reinstall gcc --without-multilib
    ==> Summary
    🍺  /usr/local/Cellar/gcc/5.2.0: 1353 files, 248M

But I keep getting the same error when I try to install DevIL

**Comment by DomT4** [comment]
The wording of the warning isn't quite accurate in this case. It doesn't build with Clang or GCC 5.x, so you need to `brew install homebrew/versions/gcc49` and then you'll be able to install `devil`.

**Comment by DomT4** [comment]
Closing per the above. Feel free to shout if that doesn't work for whatever reason. It should though.
