### ISSUE TITLE
brew cleanup should delete .incomplete download items from caches

### ISSUE THREAD

**Issue by edrozenberg** [Homebrew/homebrew#44182]
I had a couple of incomplete download files in my /Library/Caches/Homebrew:

````
php55-5.5.29.incomplete
re2c-0.14.3.tar.gz.incomplete
````

It appears brew cleanup never cleans those out, but it probably should. Not a big problem though because I only had a couple of items, which were not wasting a lot of space.

**Comment by mikemcquaid** [comment]
:+1:. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
