### ISSUE TITLE
npm scripts can't run local install binaries

### ISSUE THREAD

**Issue by TrevorSayre** [Homebrew/homebrew#44203]
```
devDependencies": {
    "mkcjs": "^0.0.2"
  },
  "scripts": {
    "build": "mkcjs"
  },
```

Above is a snippet of an example package.json

If I do `npm install`, then mkcjs is installed successfully. If I then run `npm run build`, npm fails to run the local mkcjs binary which is in `node_modules/.bin/` as it is looking for node in `/usr/bin/node` when in reality node is located in `/usr/local/bin/node` thanks to Homebrew.

```
$ npm run build

> project@ build /Users/user/project
> mkcjs

sh: /Users/user/project/node_modules/.bin/mkcjs: /usr/bin/node: bad interpreter: No such file or directory
```

One work around is to `sudo ln -s /usr/local/bin/node /usr/bin/node` and then running `npm run build` works. However, this feels like a hack and requires sudo.

**Comment by xu-cheng** [comment]
This is from mkcjs, which hard codes the path to node interpreter. https://github.com/serprex/mkcjs/blob/master/mkcjs.js

Please report the bug to upstream instead.

**Comment by TrevorSayre** [comment]
@xu-cheng Thank you for your help :+1:
