### ISSUE TITLE
Update NPM to 3.0

### ISSUE THREAD

**Issue by vinkla** [Homebrew/homebrew#44202]
Last week NPM 3.0 was released. Any chance we can get the Node formula to use that version instead of the 2.0? I would create a PR myself but I don't think my knowledge about this is enough.

**Comment by TrevorSayre** [comment]
The problem is the hardcoded npm version in the Formula:
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/node.rb#L32

**Comment by magnus-bergman** [comment]
:+1:

**Comment by vinkla** [comment]
@TrevorSayre Maybe we could simply update it to the latest or will there be side effects?

**Comment by TrevorSayre** [comment]
@vinkla To be honest, many people recommend using Homebrew to install node without npm, and then install npm separately without Homebrew: 
https://gist.github.com/DanHerbert/9520689
https://gist.github.com/DanHerbert/9520689#gistcomment-1562962

You could also edit your node Formula locally to use the stable release `https://registry.npmjs.org/npm/-/npm-3.3.3.tgz` instead by doing `brew edit node` at least until the Formula provided by Homebrew is updated. But caveat emptor, etc.

**Comment by vinkla** [comment]
They had issues with NPM in the past but they fixed that a while back.

**Comment by TrevorSayre** [comment]
@vinkla https://github.com/Homebrew/homebrew/pull/44206

**Comment by vinkla** [comment]
:+1:

**Comment by DomT4** [comment]
Ref: https://github.com/Homebrew/homebrew/pull/44206#issuecomment-141953707.
