### ISSUE TITLE
czmq --HEAD: `make check` fails

### ISSUE THREAD

**Issue by paddor** [Homebrew/homebrew#44210]
When trying to install the latest version of CZMQ with the command `brew install -v czmq --HEAD --with-libsodium`, `make check` fails. See https://gist.github.com/paddor/4a64778ae3b77f54bc3a.

Checking out CZMQ manually and running the same command sequence as run by Homebrew, it doesn't fail.

I'm running OSX 10.10.5 and tried with both ZMQ stable and `--HEAD` (which installs without problems). Same outcome.

**Comment by dunn** [comment]
I'm getting the same error with `--HEAD` and without.  Looking into it.

**Comment by paddor** [comment]
Okay, thanks @dunn. What about `--HEAD`? It doesn't happen if I install it manually (without Homebrew) on my machine.

**Comment by DomT4** [comment]
The failure is:

```
 * zconfig: OK
 * zdigest: OK
Assertion failed: (subdir), function s_posix_populate_entry, file src/zdir.c, line 93.
 * zdir: make[2]: *** [check-local] Abort trap: 6
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1
```

**Comment by paddor** [comment]
Yeah, same here. But do you know why? @dunn

**Comment by dunn** [comment]
I don't know why, and I wasn't able to build it outside Homebrew to compare. Hopefully I'll have time to try again this weekend.

**Comment by paddor** [comment]
Strange. I can compile and `make check` it without any issues, if I do it manually, using the following commands:

```
git clone git@github.com:zeromq/czmq.git && cd czmq
./autogen.sh
./configure --disable-dependency-tracking --prefix=/usr/local/Cellar/czmq/HEAD
make
make check
```

What's the error on your machine? @dunn

**Comment by dunn** [comment]
Oh, I just needed to set `XML_CATALOG_FILES`.  Now it builds and `make check` passes outside of Homebrew for me as well.

**Comment by paddor** [comment]
What does that environment variable have to do with compiling CZMQ? And to what value did you have to set it?

**Comment by paddor** [comment]
And the big question is still: Why does it fail with Homebrew?

**Comment by dunn** [comment]
I set it to `/usr/local/etc/xml/catalog`; which is often required when running docbook or asciidoc in the Homebrew environment.

No clue why it's failing at `make check`, though.

**Comment by samrussell** [comment]
There is a bug in czmq_selftest. It expects to be run from $CZMQ_PATH/src, as it tries to enumerate files in the current and parent directories. However, `make check` runs from $CZMQ_PATH, so it tries to enumerate the parent directory. This is fine when you git clone to your home directory, but homebrew builds in /private/tmp, which includes a bunch of chmod 600 root files that won't be enumerated.

In other words, to replicate this, do the following

git clone git@github.com:zeromq/czmq.git && cd czmq
sudo mkdir ../fail
sudo chmod 600 ../fail
./autogen.sh
./configure --disable-dependency-tracking --prefix=/usr/local/Cellar/czmq/HEAD
make
make check

The proper fix would be makefile wizardry to get make check to execute in the correct directory, but I'll get a patch for zdir_test to fix this in the meantime.

You can get a bit more debug info out of make check-verbose, but the assertion dies before it dumps the contents of the directory.

If you want a running tally of the directories it searches you can add the following line to zbar.c:94

printf("new dir parent (%s) dirname (%s)\n", self->path, entry->d_name);

**Comment by samrussell** [comment]
This bug has been around for a year by the looks

https://github.com/zeromq/czmq/issues/527

**Comment by paddor** [comment]
@samrussell Thanks so much for fixing this! Unfortunately, your fix in czmq makes the patch invalid. :joy: 

```
$ brew install -v czmq --HEAD --with-libsodium
==> Cloning https://github.com/zeromq/czmq.git
Updating /Library/Caches/Homebrew/czmq--git
git config remote.origin.url https://github.com/zeromq/czmq.git
git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
git fetch origin
==> Checking out branch master
git checkout -f master --
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git reset --hard origin/master
HEAD is now at dbd40b1 Merge pull request #1127 from samrussell/zdir_fix
==> Downloading https://patch-diff.githubusercontent.com/raw/zeromq/czmq/pull/1127.patch
Already downloaded: /Library/Caches/Homebrew/czmq--patch-3a0672bf6e12ca7b400f70df36a93ecc31fbdc86bb977a94a5963754a4fc29b8.patch
==> Verifying czmq--patch-3a0672bf6e12ca7b400f70df36a93ecc31fbdc86bb977a94a5963754a4fc29b8.patch checksum
==> Patching
/usr/bin/patch -g 0 -f -p1 -i /private/tmp/czmq--patch20151019-93179-ttum4h/1127.patch
patching file src/zdir.c
Hunk #1 FAILED at 936.
1 out of 1 hunk FAILED -- saving rejects to file src/zdir.c.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/czmq--patch20151019-93179-ttum4h/1127.patch
```

**Comment by samrussell** [comment]
Turns out czmq and homebrew are both super fast at accepting patches :+1: 

New PR should fix this: https://github.com/Homebrew/homebrew/pull/45155
