### ISSUE TITLE
CZMQ: --with-libsodium isn't recognized

### ISSUE THREAD

**Issue by paddor** [Homebrew/homebrew#44211]
According to https://github.com/zeromq/czmq/issues/1107#issuecomment-141929930, that option is a relic. I guess it can be removed?

**Comment by dunn** [comment]
Yeah, looks like it.  We'd be very grateful for a pull request! Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions.

**Comment by DomT4** [comment]
Looks like it should be flipped around to be:

```ruby
args << "--without-libsodium" if build.without? "libsodium"
```

**Comment by dunn** [comment]
Oh, I figured with superenv it would just fail to find it.

**Comment by DomT4** [comment]
Sadly `superenv` doesn't *yet* protect `include` or `lib`. It only punts `bin` out of the `$PATH`. I presume if it is now the upstream default, it could well be picked up on local installs when `libsodium` is already present.
