### ISSUE TITLE
brew audit doesn't find gems for brew-installed ruby

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew#44220]
`brew audit --strict` on my machine looks for rubocop in ~/.gem/ruby/2.0.0/bin. I only have a ~/.gem/ruby/2.3.0 folder with a --HEAD install, so that command fails unless I explicitly add rubocop to my path.

The first time I ran brew audit I had to point it to the rubocop installed in /usr/local/Cellar/ruby/HEAD/bin because the executable wasn't in .gem/ruby/2.3.0/bin. After that first time, though, the gem appeared there. Homebrew still couldn't find the gem, but it does save some typing...

**Comment by mikemcquaid** [comment]
That's because Homebrew only ever uses the system Ruby which is version 2.0.0.

**Comment by aw1621107** [comment]
Ah, that I didn't know. Looks like I didn't read the docs close enough...

**Comment by aw1621107** [comment]
This kind of thing makes me wish there were a better way to ask questions on github
