### ISSUE TITLE
Failed to download resource "android-sdk--completion" curl(7)

### ISSUE THREAD

**Issue by zjx9461** [Homebrew/homebrew#44239]
##### I try to type"brew install android-sdk" to install the android sdk platform, but i always failed with the following step:
------------
>localhost:~ Jason$ brew install android-sdk
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Downloading https://dl.google.com/android/android-sdk_r24.3.4-macosx.zip
Already downloaded: /Library/Caches/Homebrew/android-sdk-24.3.4.zip
==> Downloading https://android.googlesource.com/platform/sdk/+/7859e2e738542baf
>curl: (7) Failed to connect to android.googlesource.com port 443: Operation timed out
>Error: Failed to download resource "android-sdk--completion"
Download failed:
>https://android.googlesource.com/platform/sdk/+/7859e2e738542baf96c15e6c8b50bbdb410131b0/ba>sh_completion/adb.bash?format=TEXT 
------------
#### I have update the Macos to 10.11 and I have try many times with "brew update",but can't solve my problem.The following is the code after i run the "brew config" :+1: 
------------
>HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 7506f7703a50ad0909edbb7afec6f68192774759
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit sandybridge
OS X: 10.11-x86_64
Xcode: 7.0
CLT: 7.0.0.0.1.1441394355
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_60, 1.6.0_65-b14-468
------------
#### When I tried the "brew upgrade",it also tell me that i can't upgrade it as follows:
------------
>localhost:~ Jason$ brew upgrade
>warning: You are using OS X 10.11.We do not provide support for this pre-release version.You may encounter build failures or other breakage.
------------

#### So, how can I  install the android-sdk as well as the android development platform?

I just want build with React Native.js.

Thanks

**Comment by DomT4** [comment]
What happens if you do `brew fetch android-sdk -v` manually? It's working okay here. Does `brew doctor` output anything?

**Comment by zjx9461** [comment]
@DomT4 ，Thanks for your reply.
I return to the MacOS 10.10 eventually,and everything do well now.  :)

**Comment by DomT4** [comment]
Glad to hear your issues are resolved :)

**Comment by lizouzt** [comment]
I got this question also.The reason is googlesource.com could not be catch up by url network.
So just download this dab.bash file on local server,Then brew edit android-sdk and change https://android.googlesource.com to a local address.
This thing maybe just happen in my country.

**Comment by DomT4** [comment]
@lizouzt Some countries are known to block off access to certain Google subdomains; China is the big one. It may be possible for us to prop up a Github mirror of that particular `bash` completion file to resolve this.
