### ISSUE TITLE
Launchd only formula

### ISSUE THREAD

**Issue by olivernn** [Homebrew/homebrew#44230]
I'm trying to create a formula that _only_ creates a launchd configurations, i.e. there is no actual software to install. I have a [StackOverflow question](http://stackoverflow.com/questions/32638013/homebrew-formula-that-only-sets-up-launchd) with more detail, but thought I might ask here as well.

Is it possible to create formula that doesn't actually download and install software, just sets up configuration? Is homebrew the wrong tool for this? Any suggestions for a better way to do this?

**Comment by DomT4** [comment]
Afraid formulae mandate at least a `URL` field. Homebrew probably is the wrong tool for what you want to do here. I'd probably write a short bash/ruby/python/language of choice script to handle automatically writing & installing the `plist` and stopping/starting the service, if you were looking for something automated like that.

**Comment by olivernn** [comment]
Oh, so downloading some script that would install the `plist` files? Might work.  Actually I also could have a script that could automate the modifications of the users `ssh/config` required for what I want to do.

But perhaps you're right and using homebrew for this isn't the right tool.
