### ISSUE TITLE
Graphviz builds a 10.11 only App on Yosemite

### ISSUE THREAD

**Issue by sihil** [Homebrew/homebrew#44269]
When installing graphviz on Yosemite with `brew install graphviz --with-app` the application that is built gives the following error when executed: "**You can’t use this version of the application “Graphviz” with this version of OS X.** You have OS X 10.10.5. The application requires OS X 10.11 or later."

This is my installation:
```
~$ brew install graphviz --with-app
==> Downloading http://graphviz.org/pub/graphviz/stable/SOURCES/graphviz-2.38.0.tar.gz
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/DomT4/scripts/46364470b/Homebrew_Resources/MacPorts_Import/graphviz/r103168/patch-project.pbxproj.diff
######################################################################## 100.0%
==> Patching
patching file macosx/graphviz.xcodeproj/project.pbxproj
==> ./configure --prefix=/usr/local/Cellar/graphviz/2.38.0 --without-qt --with-quartz --disable-swig --without-pangocairo --without-freetype2 --without-x -
==> make install
==> xcodebuild -configuration Release SYMROOT=build PREFIX=/usr/local/Cellar/graphviz/2.38.0 ONLY_ACTIVE_ARCH=YES
==> Caveats
.app bundles were installed.
Run `brew linkapps graphviz` to symlink these to /Applications.
==> Summary
🍺  /usr/local/Cellar/graphviz/2.38.0: 491 files, 69M, built in 2.2 minutes
```

`brew doctor` is empty (it did originally advise that I did not have the 10.10 SDK installed, although I repaired that, uninstalled and reinstalled graphviz with the same problem.

I've discovered the following workaround: instead of opening the app via the GUI, run the application directly from the terminal using `/usr/local/opt/graphviz/Graphviz.app/Contents/MacOS/Graphviz`

**Comment by DomT4** [comment]
I suspect what is happening here is that the Xcode 7 lacking 10.10 SDK "fix" we put in place doesn't work in this situation because it explicitly requires Xcode when the `app` is used, so it is probably still using the 10.11 SDK to build against regardless.

**Comment by DomT4** [comment]
This should probably be reported upstream as well, as it will likely impact anyone on 10.10 using Xcode 7  to build `graphviz` with the App bundle, regardless of Homebrew usage or not.

**Comment by gitsnaf** [comment]
Some problem here. App won't open in 10.10.5 :(

**Comment by DomT4** [comment]
This should be fixed after a `brew update` and `brew reinstall graphviz`.
