### ISSUE TITLE
Incorrect curl options for OSX 10.8

### ISSUE THREAD

**Issue by staticfloat** [Homebrew/homebrew#44263]
The `curl` being used to fetch sources on OSX 10.8 is apparently too old to auto-detect TLS handshakes:

```
$ brew fetch -v gtk+3
==> Downloading https://download.gnome.org/sources/gtk+/3.16/gtk+-3.16.7.tar.xz
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 1.8.7-358; OS X 10.8.5) https://download.gnome.org/sources/gtk+/3.16/gtk+-3.16.7.tar.xz -C 0 -o /Library/Caches/Homebrew/gtk+3-3.16.7.tar.xz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (35) error:14077458:SSL routines:SSL23_GET_SERVER_HELLO:reason(1112)
Error: Failed to download resource "gtk+3"
Download failed: https://download.gnome.org/sources/gtk+/3.16/gtk+-3.16.7.tar.xz
```

Adding `-1` to [`copts` in `download_strategy.rb`](https://github.com/Homebrew/homebrew/blob/fe9f1a6af3655ae76cccaa191b5801d1ec3c9646/Library/Homebrew/download_strategy.rb#L329-L333) fixes this, however I'm not certain that's a great solution as it sounds like that might make it impossible to connect to older SSL servers instead.  It's certainly better than nothing however, as almost all servers are now disabling SSLv2 and SSLv3 due to POODLE.  Installing a newer `curl` from brew doesn't help, as `brew` explicitly doesn't use it.

**Comment by tdsmith** [comment]
The 10.8 bot must have successfully fetched that tarball before; what changed?

Googling the error message hits a bunch of curl dev list threads but I'm not sure which are relevant; there's a suggestion that the system openssl might be too old or that it's related to SNI somehow.

**Comment by staticfloat** [comment]
I think POODLE is what changed; server owners have all updated their server
cipher/protocol settings to disable older (and more vulnerable)
ciphers/protocols.

**Comment by tdsmith** [comment]
Do either of these succeed with /usr/bin/curl on 10.8?

* `curl -kvvv https://test20.tls-o-matic.com:420` (TLS 1.0+)
* `curl -vvvI https://caremad.io` (TLS 1.2 only)

**Comment by DomT4** [comment]
I'm tempted to adopt the position of allowing Homebrew's `curl` to be used on any OS X version we no longer test to be honest.

**Comment by tdsmith** [comment]
Sure, if it solves problems. If 10.8's curl really is TLS-deficient maybe we should add a recommendation in `doctor`.

**Comment by tdsmith** [comment]
I spun up a 10.8 VM and I don't see this failure. TLS 1.2 isn't supported but TLS 1.0 is. gtk+3 fetches fine. Not sure what's going on?

**Comment by staticfloat** [comment]
I am ashamed to say this is because I hadn't done a software update in some time.  Apple updated `curl` recently for `OSX 10.8`.  Thanks for looking into this
