### ISSUE TITLE
kdiff3 not recognised by sourcetree

### ISSUE THREAD

**Issue by snimavat** [Homebrew/homebrew#44278]
Sourcetree expects kdiff3 in /Applications. See https://answers.atlassian.com/questions/156940/
formula should create a symlink at that folder so that sourcetree can recognise kdiff3 as installed on the machine.

**Comment by DomT4** [comment]
`brew linkapps kdiff3`.

**Comment by snimavat** [comment]
Wow, worked, thanks.

**Comment by DomT4** [comment]
No worries! Happy to help.
