### ISSUE TITLE
cpp-ethereum failed to buld on 10.9.5

### ISSUE THREAD

**Issue by sacketty** [Homebrew/homebrew#44270]
result is 
make: *** [all] Error 2
https://gist.github.com/700b8f91a8f5e00cfd11

**Comment by DomT4** [comment]
You need to report this to https://github.com/ethereum/homebrew-ethereum I'm afraid. We can't fix formulae we don't have control over.

The error seems to be `error: unknown argument: '-fstack-protector-strong'`. It may be the case that the Clang that ships with Mavericks doesn't support that argument. I believe Yosemite and above do.

The upstream tap could probably work around it by either enforcing the use of GCC for Mavericks and below, or removing that call from the build.
