### ISSUE TITLE
Error messages on update/upgrade

### ISSUE THREAD

**Issue by mcnesium** [Homebrew/homebrew#44274]
mcnesium@mcobst:~$ brew update
    Already up-to-date.
    mcnesium@mcobst:~$ brew upgrade brew-cask
    Error: caskroom/cask/brew-cask 0.56.0 already installed
    mcnesium@mcobst:~$

It's hard to expose the severeness of that red underlined "Error:" in markdown but I kind of feel like this is not really an error, right? Shouldn't this be more like an "Info:" label?

**Comment by mikemcquaid** [comment]
It's an error because we return a failing exit code (which we now can't change as too many scripts rely on it).
