### ISSUE TITLE
Error while brewing VTK 

### ISSUE THREAD

**Issue by kamalbowselvam** [Homebrew/homebrew#44275]
Hi, 

I am using Macbook, I tried to do 
      brew install vtk 

and I got this error 
Error: No available formula for vtk
==> Searching formulae...
==> Searching taps...

Could some one tell me, how can install vtk for mayavi.

My brew doctor gives this output,
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 9ecdd995a415a8e700544c94f63533813f5f1ab9
Last commit: 32 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
OS X: 10.9.5-x86_64
Xcode: 6.2
CLT: 6.2.0.0.1.1424975374
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A

**Comment by bfontaine** [comment]
The formula is in the homebrew/science tap: `brew install homebrew/science/vtk`.

**Comment by kamalbowselvam** [comment]
It worked, Thanks
