### ISSUE TITLE
heirloom-devtools

### ISSUE THREAD

**Issue by benjaminweb** [Homebrew/homebrew#44283]
I try to create a Formula for heirloom-devtools.

make install fails:
https://gist.github.com/benjaminweb/4ce8056f5808ebc981cd#file-gistfile1-txt-L409-L411

The debug information does not help (me).

However, ``make install`` works if I copy and call it manually:
https://gist.github.com/benjaminweb/4ce8056f5808ebc981cd#file-gistfile1-txt-L420

Why?

I changed ``STRIP=strip -s -R .comment -R .note`` (see mk.config) to ``STRIP=strip -R``.
The former is invalid on Mac OS X. Is my replacement a good or a bad solution?

**Comment by DomT4** [comment]
Your proposed specifying of `STRIP` as a `make` variable seems fine.

We wouldn't accept the formulae in the core because of the head-only status, but you could either submit them to `head-only` or keep them in your own tap/locally/etc.

**Comment by benjaminweb** [comment]
Thanks for your response on ``STRIP``.

Can you give me some clue on why does the ``make install`` in the formula fail?
The debug does not help me, though. Calling it manually in debug — as noted above — works.
So, what's wrong with the formula?

**Comment by DomT4** [comment]
> Can you give me some clue on why does the make install in the formula fail?

Try not pushing the second argument line as an explicit new line, i.e.

```ruby
system "make", "SHELL=#{heirloomSh.bin}/sh", "BINDIR=#{bin}", "INSTALL=/usr/bin/install",
       "PREFIX=#{prefix}", "SUSBIN=#{bin}/posix", "LIBDIR=#{lib}", "MANDIR=#{man}", "STRIP=strip -R"
```

Rather than the current line in `heirloom-devtools.rb`.
