### ISSUE TITLE
add cleanup option to brew update

### ISSUE THREAD

**Issue by EmilVarona** [Homebrew/homebrew#44288]
I had noticed that running `brew upgrade` does not remove outdated formulae. It might be useful to have an optional switch when running `brew upgrade` to perform this rather than relying on a separate call to `brew cleanup`.

**Comment by bfontaine** [comment]
Would you mind doing a pull-request? This should help and I’d be happy to answer any question you might have: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

**Comment by rakkesh** [comment]
@bfontaine could you kindly share your thoughts on this approach.
```rb
require "cmd/cleanup"
   ....
    outdated.each do |f|
      upgrade_formula(f)
      cleanup_formula(f) if ARGV.include? '--cleanup' 
    end
```

**Comment by bfontaine** [comment]
@rakkesh It seems great, see my comment on the PR.

**Comment by DomT4** [comment]
PR was merged.
