### ISSUE TITLE
Failure to build openssl on OS X 10.9.5

### ISSUE THREAD

**Issue by josePhoenix** [Homebrew/homebrew#44282]
```
==> Installing python dependency: openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2d.tar.gz
######################################################################## 100.0%
==> perl ./Configure --prefix=/Users/molly/local/homebrew/Cellar/openssl/1.0.2d_1 --openssldir=/Users/molly/local/etc/openssl no-ssl2 zlib-dynamic shared enab
==> make depend
==> make
Last 15 lines from /Users/molly/Library/Logs/Homebrew/openssl/03.make:
rsaz-x86_64.s:1697:2: error: invalid instruction mnemonic 'adoxq'
 adoxq %r15,%r14
 ^~~~~
rsaz-x86_64.s:1700:2: error: invalid instruction mnemonic 'adcxq'
 adcxq %rax,%r14
 ^~~~~
rsaz-x86_64.s:1701:2: error: invalid instruction mnemonic 'adoxq'
 adoxq %rdi,%r15
 ^~~~~
rsaz-x86_64.s:1702:2: error: invalid instruction mnemonic 'adcxq'
 adcxq %rdi,%r15
 ^~~~~
make[2]: *** [rsaz-x86_64.o] Error 1
make[1]: *** [subdirs] Error 1
make: *** [build_crypto] Error 1
```

Full logs from `brew gist-logs openssl`. https://gist.github.com/anonymous/12f1868490ab7f9d470b (This is from a homebrew install that is not rooted in /usr/local/, and there's other junk installed by IT that makes brew doctor complain, but the same setup steps have worked on a 10.10 machine.)

It might be related to this issue with `makedepend`, but the poster states Homebrew specifically works around it: http://openssl.6102.n7.nabble.com/openssl-org-3233-make-depend-emits-warnings-on-OSX-wth-1-0-1f-td48108.html

**Comment by josePhoenix** [comment]
@peeples -- FYI

**Comment by mistydemeo** [comment]
```
Xcode: 5.0.2
CLT: 6.1.1.0.1.1416017670
```

Your Xcode and CLT are mismatched; can you try upgrading your Xcode to match your CLT?

**Comment by josePhoenix** [comment]
Well spotted! We upgraded XCode + CLT to 6.2 and OpenSSL seems to build fine now, so I'll close this out.

**Comment by mojca** [comment]
This is still a problem on 10.7 (version 1.0.2e) where it is impossible to upgrade CLT to a newer version.

**Comment by neverpanic** [comment]
See comment 22 at https://trac.macports.org/ticket/47035#comment:22. I think this is due to the weird version number Apple chose to print on its clang and a regex that doesn't quite deal with it.

**Comment by mojca** [comment]
OK, there is another report open already (no need to further spam this one, I'm sorry):
* https://github.com/Homebrew/homebrew/issues/46751
* https://github.com/openssl/openssl/issues/494
