### ISSUE TITLE
Is there a way to `brew update --rebase` by default?

### ISSUE THREAD

**Issue by rhendric** [Homebrew/homebrew#44289]
I was sad to recently lose the default rebase when running `brew update`, and while I've tried to adapt to always typing `--rebase` at the end, I often forget (and then have to deal with editing a merge comment that I don't want). Is there (can there be) a way to restore the old behavior via environment variables, git config, anything?

**Comment by mikemcquaid** [comment]
Not by default, sorry. You could perhaps make a Bash alias.

**Comment by xu-cheng** [comment]
> You could perhaps make a Bash alias.

Or try https://github.com/Homebrew/homebrew-aliases
