### ISSUE TITLE
MariaDB failed to start after upgrade from lastest bottle

### ISSUE THREAD

**Issue by Xefir** [Homebrew/homebrew#44290]
Hello

Before all, here is the version of MariaDB impacted (extract from brew info mariadb) : 

mariadb: stable 10.0.21 (bottled), devel 10.1.7

When I start MariaDB, it failed, with only this text : 

```
xefir@Tordy ~> mysql.server start
Starting MySQL
. ERROR! 
```

No error shown on .err file on /usr/local/var/mysql, so I investigate further and found that is the mysqld_safe script witch has a bad syntax in it.

When I launch the command mysql, here's I got : 

```
xefir@Tordy ~> /usr/local/Cellar/mariadb/10.0.21/bin/mysqld_safe --datadir=/usr/local/var/mysql --pid-file=/usr/local/var/mysql/Tordy.local.pid
150923 23:27:31 mysqld_safe Logging to '/usr/local/var/mysql/Tordy.local.err'.
/usr/local/Cellar/mariadb/10.0.21/bin/mysqld_safe: line 770: syntax error near unexpected token `then'
/usr/local/Cellar/mariadb/10.0.21/bin/mysqld_safe: line 770: `    then    # The pid contains a mysqld process'
```

So, I comment the line, like this : 

```
#
# If there exists an old pid file, check if the daemon is already running
# Note: The switches to 'ps' may depend on your operating system
if test -f "$pid_file"
then
  PID=`cat "$pid_file"`
  if kill -0 $PID > /dev/null 2> /dev/null
  then
    #if 
    #then    # The pid contains a mysqld process
      log_error "A mysqld process already exists"
      exit 1
    #fi
  fi
  rm -f "$pid_file"
  if test -f "$pid_file"
  then
[...]
```

Please note the 3 comments on if, then and fi.

After this modification, it works again : 

```
xefir@Tordy ~> mysql.server start
Starting MySQL
 SUCCESS! 
```

Could you apply the fix ? ( I don't know where is this code, on this repository or on the mariadb side =/ )

Thank you :-)

**Comment by DomT4** [comment]
Are you using El Capitan?

**Comment by rakkesh** [comment]
@Xefir how is that the condition for `if` in your code snippet missing? The error is related to the missing `if` condition.

Snippet from the file, `/usr/local/Cellar/mariadb/10.0.21/bin/mysqld_safe` -
```sh
#
# If there exists an old pid file, check if the daemon is already running
# Note: The switches to 'ps' may depend on your operating system
if test -f "$pid_file"
then
  PID=`cat "$pid_file"`
  if kill -0 $PID > /dev/null 2> /dev/null
  then
    if ps -ef | grep -v mysqld_safe | grep -- $MYSQLD | grep $PID > /dev/null
    then    # The pid contains a mysqld process
      log_error "A mysqld process already exists"
      exit 1
    fi
  fi
  rm -f "$pid_file"
  if test -f "$pid_file"
  then
    log_error "Fatal error: Can't remove the pid file:
$pid_file
Please remove it manually and start $0 again;
mysqld daemon not started"
    exit 1
  fi
fi
```

**Comment by DomT4** [comment]
> how is that the condition for if in your code snippet missing? 

Our sandbox broke one of the bottles (El Cap) when it was generated 10 days ago. That error has since been fixed, but I've removed the broken bottle for now.

**Comment by DomT4** [comment]
Was fixed by https://github.com/Homebrew/homebrew/commit/91d0330693c7e6eeabd339e0478c30293bc135b2. `brew reinstall mariadb` and you'll have a fully functioning install again. Thanks for the report!
