### ISSUE TITLE
brew update failed

### ISSUE THREAD

**Issue by unixwizard107** [Homebrew/homebrew#44313]
$ brew update
Error: undefined method `link_overwrite' for #<Class:0x007fce5a1fa920>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Formula/glib-networking.rb:21:in `<class:GlibNetworking>'
/usr/local/Library/Formula/glib-networking.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:78:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:69:in `klass'
/usr/local/Library/Homebrew/formulary.rb:65:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:174:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:191:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:191:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:25:in `update'
/usr/local/Library/brew.rb:127:in `<main>'

**Comment by DomT4** [comment]
Should be a one-time error in relatively specific circumstances. If you `brew update` again do you see no issues?

**Comment by unixwizard107** [comment]
Ok, I did a brew doctor which was clean and then brew update and it worked
the second time.

Just following the instructions

Thanks,
Clem

**Comment by DomT4** [comment]
No worries. Thanks for the report! Glad all is working as expected.
