### ISSUE TITLE
No brew commands working

### ISSUE THREAD

**Issue by PeterKaminski09** [Homebrew/homebrew#44316]
Hi, this issue has been brought up before, but it doesn't have a satisfying solution on the internet or on this github page. 

When I run any brew command I get this: /usr/local/Library/Homebrew/global.rb:57:in `split': invalid byte sequence in UTF-8 (ArgumentError)
	from /usr/local/Library/Homebrew/global.rb:57:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'

I've seen something about this being a $PATH error, but my path doesn't have any unknown characters. Here is my path: /opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/Users/peterkaminski/anaconda/bin:“/Users/peterkaminski/pebble-dev/PebbleSDK-2.0-BETA5/bin:/Users/peterkaminski/pebble-dev/PebbleSDK-2.0-BETA5/bin:/Users/peterkaminski/pebble-dev/PebbleSDK-2.0-BETA4/bin:/Users/peterkaminski/pebble-dev/PebbleSDK-2.0-BETA4/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin:/Users/peterkaminski/apache-ant-1.9.3/bin:??

Any ideas?

**Comment by tdsmith** [comment]
What happens if you run `PATH=/usr/local/bin:/usr/bin brew --version`?

It looks like you have a stray `"` character in your PATH and I'm not sure what the closing `??` is but removing those shouldn't hurt anything and may help.

**Comment by PeterKaminski09** [comment]
0.9.5 (git revision 7506; last commit 2015-09-21)

I thought that looked sketchy. How would I change my path without breaking it? Is there a temporary path change?

**Comment by tdsmith** [comment]
You can change `PATH` for any commands invoked from a given shell instance with `export PATH=/your:/new/path`.

You can find from where PATH is being set with something like `grep PATH ~/.*rc ~/.*profile`. After you edit the responsible file, the change will take effect for new terminal sessions.

**Comment by PeterKaminski09** [comment]
Thanks for the quick responses, I deleted those two characters, and brew doctor worked. Thank you
