### ISSUE TITLE
Travis CI issues tracking

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/homebrew#44320]
I'd like us to be able to use Travis CI for all non-bottle builds in future (and maybe one day all bottle builds too). In the short-term this means fixing Travis so the only failures are legitimate timeouts and the only missing features are bottle uploads.

@Homebrew/owners please add any weird Travis issues you see for **any new builds started after now**  as comments in this issue and I'll try and triage them into specific issues and then fix them.

Once these are all fixed I'll switch our `master` build over to Travis CI and then move Jenkins so it requires a `@BrewTestBot test this please` to actually run jobs on Jenkins. This means Jenkins will be far less loaded and all builds that don't rely on a bottle being uploaded (e.g. audit failures, pulls of formulae without bottles) can be done without getting Jenkins involved. It'll also mean, due to Travis's parallel builds, that we can get much quicker feedback to users.

Thanks!

**Comment by tdsmith** [comment]
It looks like linking after install is generating output that can overwhelm the pretty log display for e.g. boost: https://travis-ci.org/Homebrew/homebrew/jobs/82676343

**Comment by dpo** [comment]
I'm very excited about this. I hope this is transferrable to taps when ready. FWIW Science's current solution is here: https://github.com/dpo/homebrew-science/blob/travis-osx/.travis.yml

**Comment by xu-cheng** [comment]
Sorry accidentally closed this.

**Comment by mikemcquaid** [comment]
@Homebrew/maintainers So, Travis is looking pretty reliable and faster now. I think it's probably good enough that we can maybe use it for our `master` branch feedback instead of Jenkins. In PRs I'm not seeing any non-intermittent/timeout errors that are causing Travis to fail and Jenkins to pass. I'm wondering what else other maintainers would want to see before we can disable Jenkins for PRs by default unless `@BrewTestBot test this please` is passed.

**Comment by DomT4** [comment]
> I think it's probably good enough that we can maybe use it for our master branch feedback instead of Jenkins. 

:+1: :+1: :+1:  :+1:.

**Comment by mikemcquaid** [comment]
I've added email notifications on failure and got it posting to the mailing list. It'll only email the relevant committer with the failure so seems :+1: to add to me.

**Comment by mikemcquaid** [comment]
As soon as I receive verification that these builds are running and notifying people I'll disable the Jenkins ones.

**Comment by scpeters** [comment]
A semi-related idea I've been tinkering with is using Linux machines for homebrew CI with linuxbrew:

We have some Jenkins CI machines, and there are many more Linux machines than OS X. I've been [tinkering with Linuxbrew](https://bitbucket.org/osrf/release-tools/src/401f50f30fc8262f19ff07ce8570aae24d737626/jenkins-scripts/lib/homebrew_formula_pullrequest.bash?fileviewer=file-view-default) to do some automated formula updates with the Linux machines. Linuxbrew could conceivably do `audit`, `style`, `fetch`, and `unpack --patch` checks on OS X formulae using Linux build machines. If there are plenty of free OS X machines on travis, then this would be less important.

**Comment by mikemcquaid** [comment]
@scpeters I've thought about that too but we still have the maximum number of jobs so I don't think it would really help. It's an interesting idea, though.

**Comment by mikemcquaid** [comment]
> As soon as I receive verification that these builds are running and notifying people I'll disable the Jenkins ones.

I disabled the Jenkins ones.

**Comment by mikemcquaid** [comment]
I think this is basically done at this point.
