### ISSUE TITLE
unable to update your latest v8 package

### ISSUE THREAD

**Issue by shaunstanislaus** [Homebrew/homebrew#44338]
```brew
shaunstanislaus@Master ~ $ brew upgrade
==> Upgrading 1 outdated package, with result:
v8 4.5.103.35
==> Upgrading v8
Error: Permission denied - /usr/local/bin/d8
```

**Comment by DomT4** [comment]
`sudo chown -R $(whoami):admin /usr/local`

Your permissions have wandered off somewhere. That should fix them and allow you to upgrade again.

**Comment by shaunstanislaus** [comment]
@DomT4 : fixed, thank you!

**Comment by shaunstanislaus** [comment]
Error: Permission denied - /usr/local/bin/rbenv-install
shaunstanislaus@Master ~ $ sudo chown -R $(whoami):admin /usr/local

why do i have to do this everytime?

how do i permanently  grant permission?

**Comment by DomT4** [comment]
Can you talk about how you use `/usr/local` a bit? It looks like something is resetting your permissions inside the directory regularly.

Some software does this, and using `sudo make install` on external software that installs into `/usr/local` can do the same thing. Is anything else installed into `/usr/local` or have you `sudo make install`'ed anything else there recently? Does `brew doctor` flag anything up?

**Comment by shaunstanislaus** [comment]
i can't remember if i did anything to it, in anycase how do you fix it for good?

**Comment by DomT4** [comment]
Well, if something with a higher level of permissions than your default account is regularly modifying your permissions, you can't. You'd need to stop it modifying permissions. What's going on here isn't clear though without a fuller picture of the local setup.

I'd suggest dealing with anything `brew doctor` complains about & doing `sudo chown -R $(whoami):admin /usr/local` again, and if you build software locally that targets `/usr/local` don't `sudo make install` it.

**Comment by shaunstanislaus** [comment]
`brew doctor` didn't came up with any errors.

i tried sudo chown -R $(whoami):admin /usr/local , but it is still occurring the same issue.

**Comment by stevegk** [comment]
Sophos Anti-virus installs software in /usr/local and resets permissions on every update it seems. They are aware:  https://community.sophos.com/products/free-antivirus-tools-for-desktops/f/17/t/10029.

**Comment by shaunstanislaus** [comment]
@stevegk how did you know I have Sophos installed?

**Comment by shaunstanislaus** [comment]
The @stevegk thanks for the info man! It really helps. Now I know why my homebrew permissions keeps rolling back.

**Comment by stevegk** [comment]
Just a guess. Had similar problem myself and finally tracked it down yesterday.
