### ISSUE TITLE
Boost failed to build on 10.10.5 Yosemite with --build-from-source

### ISSUE THREAD

**Issue by jandlint** [Homebrew/homebrew#44342]
Hello,

I am building boost with the layout=system argument and am building from source. The build does not go through and I receive the following error:

    error: Name clash for '<p/usr/local/Cellar/boost/1.58.0/lib>libboost_system.dylib'
    error: 
    error: Tried to build the target twice, with property sets having 
    error: these incompatible properties:
    error: 
    error:     -  <threading>multi
    error:     -  <threading>single
    error: 
    error: Please make sure to have consistent requirements for these 
    error: properties everywhere in your project, especially for install
    error: targets.

Here is the generated [gist](https://gist.github.com/anonymous/722ff803879a9ccd3902). Thank you in advance.

**Comment by tdsmith** [comment]
If you're editing the formula you're on your own, but it looks like --without-single might be what you need.

**Comment by jandlint** [comment]
Thank you for the quick response. That is exactly the option that I needed.
