### ISSUE TITLE
mongodb does not run

### ISSUE THREAD

**Issue by cokleisli** [Homebrew/homebrew#44340]
kleisli:~ me$ brew install mongodb
==> Downloading https://homebrew.bintray.com/bottles/mongodb-3.0.6.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/mongodb-3.0.6.yosemite.bottle.tar.gz
==> Pouring mongodb-3.0.6.yosemite.bottle.tar.gz
==> Caveats
To have launchd start mongodb at login:
  ln -sfv /usr/local/opt/mongodb/*.plist ~/Library/LaunchAgents
Then to load mongodb now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
Or, if you don't want/need launchctl, you can just run:
  mongod --config /usr/local/etc/mongod.conf
==> Summary
🍺  /usr/local/Cellar/mongodb/3.0.6: 17 files, 159M
kleisli:~ me$ mongod --config /usr/local/etc/mongod.conf
-bash: /usr/local/mongodb/bin/mongod: No such file or directory
kleisli:~ me$

**Comment by DomT4** [comment]
> -bash: /usr/local/mongodb/bin/mongod: No such file or directory

This is a little odd. Nothing from Homebrew should be in this directory, ever. We'd install to `/usr/local/opt/mongodb` and then symlink back into `/usr/local`. Can you try reloading the Terminal to see if that message persists, and if it does please `echo $PATH`. Thanks.

**Comment by cokleisli** [comment]
Reloaded the Terminal and it works now. Must have had some dodgy environment settings. Thanks.

**Comment by DomT4** [comment]
No worries. Glad all is working as expected!
