### ISSUE TITLE
sshfs GLib-CRITICAL error

### ISSUE THREAD

**Issue by knowledgecode** [Homebrew/homebrew#44346]
I've been getting the following error message from `sshfs` since `glib` has been updated 2.46.0.
```sh
$ sshfs -V

(process:2435): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE library version: FUSE 2.7.3 / OSXFUSE 2.8.1
no mount point
```
It seems working fine for now, but the error message makes me worry. :(

**Comment by dunn** [comment]
This issue was moved to Homebrew/homebrew-fuse#16
