### ISSUE TITLE
Mavericks brew bot stuck

### ISSUE THREAD

**Issue by ablyler** [Homebrew/homebrew#44356]
Job http://bot.brew.sh/job/Homebrew/version=mavericks/15048/ got stuck at:
```
Build timed out (after 60 minutes). Marking the build as aborted.
Error: SIGTERM
Please report this bug:
    https://git.io/brew-troubleshooting
```

I found it when it was running for more than 6 hours.  I manually had to click abort a few times to get it to stop, but now it is stuck on the next job: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/version=mavericks/33749/

It has been stuck for > 45 minutes at:
```
[EnvInject] - Loading node environment variables.
Building remotely on mavericks in workspace /Users/brew/Jenkins/prs/version/mavericks
 > git rev-parse --is-inside-work-tree # timeout=10
```

**Comment by xu-cheng** [comment]
I reboot the Mavericks VM, it should work now.

Thanks for reporting.
