### ISSUE TITLE
Brew dependency on git version not specified

### ISSUE THREAD

**Issue by brevilo** [Homebrew/homebrew#44350]
`brew update` does require a certain git version as it at least fails with git 1.7.1:

```
% brew update                                                                                                                                                               
error: unknown option `short'
usage: git symbolic-ref [options] name [ref]
```

Obviously brew expects a certain git CLI which isn't yet available in 1.7.1. Please specify the minimum git version required in the README's list of dependencies.

Thanks

**Comment by tdsmith** [comment]
On what version of OS X are you experiencing this?

**Comment by brevilo** [comment]
I'm not. I'm seeing this on Linux (linuxbrew) but how does that matter? Git's CLI is universal, isn't it? But OK, homebrew doesn't specify any dependencies so my request doesn't apply here anyway... Your call...

**Comment by tdsmith** [comment]
I did a little research: Xcode 4.6.3 is the oldest Xcode we support which bundles git; that version of git is 1.7.12.4, and supports --short. https://www.opensource.apple.com/source/Git/Git-37/src/git/Documentation/git-symbolic-ref.txt

git is not required to install Homebrew. If git is provided by Xcode, it is recent enough for --short. If git is provided by Homebrew, it is recent enough. Among our users, it is unusual on OS X for git to be provided some other way; we can assume that a user-provided git will be recent.

This may or may not be an appropriate position for Linuxbrew.

**Comment by brevilo** [comment]
Fair enough :+1:
