### ISSUE TITLE
undefined method `to_sym' for nil:NilClass

### ISSUE THREAD

**Issue by erikzrekz** [Homebrew/homebrew#44366]
After running `brew doctor`. I ran `brew --config`.

```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/mxcl/homebrew
HEAD: f0392ad7832fcef5e46d730882b0ff5b6d76595a
Last commit: 29 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit sandybridge
OS X: 10.9.5-x86_64
Xcode: 5.1.1
CLT: N/A
Clang: 5.1 build 503
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /Library/Frameworks/Python.framework/Versions/Current/bin/python => /Library/Frameworks/Python.framework/Versions/7.3/Resources/Python.app/Contents/MacOS/Python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-462
```

I then tried `brew update` which resulted in.

```
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 1339 and retry the command.
Error: undefined method `to_sym' for nil:NilClass
Please report this bug:
    https://github.com/mxcl/homebrew/wiki/troubleshooting
```

I am going to try and update some more stuff to see if I can fix it. I'll report back. https://github.com/mxcl/homebrew/wiki/troubleshooting redirects me to main page of the repo.

**Comment by DomT4** [comment]
> Please report this bug:
    https://github.com/mxcl/homebrew/wiki/troubleshooting

This link should be `https://git.io/brew-troubleshooting` these days. Can you:
```
cd $(brew --prefix) && git status
```
Anything unusual printed there? Curious why that hasn't updated for you.

**Comment by DomT4** [comment]
Please let us know if you're still having trouble with this. Presuming resolved otherwise.

I'd try a `git fetch && git reset --hard origin/master` to restore Homebrew to a pristine condition if you are still seeing any issues.
