### ISSUE TITLE
error in Sphinx setup command

### ISSUE THREAD

**Issue by mmpozulp** [Homebrew/homebrew#44363]
I am executing `brew install cmake` and get the following error:

**error in Sphinx setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.**

I did `brew update` and tried again and got the same error.

Gist, created by `brew gist-logs cmake` linked below.

https://gist.github.com/b175c6edc56c3419e2ee

**Comment by tdsmith** [comment]
What do you see when you run `/usr/bin/python -c "import setuptools; print setuptools.__version__"`?

You can work around this by installing cmake --without-docs or by [installing pip](https://pip.pypa.io/en/latest/installing/#install-pip) (run get-pip.py like `sudo /usr/bin/python get-pip.py` after you download it) and then upgrading setuptools with `sudo /usr/bin/python -m pip install -U setuptools`.

**Comment by DomT4** [comment]
Closing per no response. Please let us know if we can help any further; Thanks!
