### ISSUE TITLE
QEMU: --enable-sdl not compatible with --enable-cocoa when installing HEAD

### ISSUE THREAD

**Issue by samvv** [Homebrew/homebrew#44378]
When installing qemu with `--with-sdl`, the default `--enable-cocoa`-flag should be disabled. No idea if it is possible, though. Maybe by making cocoa optional?

    $ brew install qemu --HEAD --with-sdl
    ==> Installing dependencies for qemu: glib
    ==> Installing qemu dependency: glib
    ==> Downloading https://homebrew.bintray.com/bottles/glib-2.46.0.yosemite.bottle.tar.gz
    Already downloaded: /Library/Caches/Homebrew/glib-2.46.0.yosemite.bottle.tar.gz
    ==> Pouring glib-2.46.0.yosemite.bottle.tar.gz
    🍺  /usr/local/Cellar/glib/2.46.0: 416 files, 18M
    ==> Installing qemu
    ==> Cloning git://git.qemu-project.org/qemu.git
    Cloning into '/Library/Caches/Homebrew/qemu--git'...
    remote: Counting objects: 4576, done.
    remote: Compressing objects: 100% (3777/3777), done.
    remote: Total 4576 (delta 985), reused 2404 (delta 706)
    Receiving objects: 100% (4576/4576), 11.81 MiB | 1.39 MiB/s, done.
    Resolving deltas: 100% (985/985), done.
    Checking connectivity... done.
    ==> Checking out branch master
    ==> ./configure --prefix=/usr/local/Cellar/qemu/HEAD --cc=clang --host-cc=clang --enable-cocoa --disa
    Last 15 lines from /Users/samvv/Library/Logs/Homebrew/qemu/01.configure:
    ./configure
    --prefix=/usr/local/Cellar/qemu/HEAD
    --cc=clang
    --host-cc=clang
    --enable-cocoa
    --disable-bsd-user
    --disable-guest-agent
    --enable-sdl
    --disable-vde
    --disable-gtk
    --disable-libssh2

    ERROR: Cocoa and SDL UIs cannot both be enabled at once

    READ THIS: https://git.io/brew-troubleshooting

**Comment by dunn** [comment]
That can definitely be done, but we should only do it for HEAD builds; stable `--with-sdl` works.

**Comment by samvv** [comment]
Indeed, you're right!

Alex Dunn <notifications@github.com>schreef:

**Comment by dunn** [comment]
Should be fixed in 131ffd8e776ec30f6b128070d067737cc6ae6a97, thanks for the report!
