### ISSUE TITLE
qt lacks openssl support on el capitan

### ISSUE THREAD

**Issue by jkarneges** [Homebrew/homebrew#44375]
The `qconfig.h` header currently sets `QT_NO_OPENSSL`. This breaks apps that depend on SSL.

Works fine on 10.9 and 10.10.

**Comment by DomT4** [comment]
If it's trying to link into OpenSSL & expecting those headers, either during compile or dynamically at runtime, that's not a surprise at all. Upstream won't accept a patch at this point on Qt4; It's onto security releases only.

**Comment by jkarneges** [comment]
Ah, so OpenSSL headers aren't present in the latest SDK, even though the OpenSSL runtime libraries are. This seems like a giant issue that would affect much more than just Qt.

Maybe homebrew could ship its own OpenSSL headers when installed on El Capitan? Or formulas could depend on the homebrew version of OpenSSL?

**Comment by jkarneges** [comment]
Submitted a patch: #44388. Apologies in advance to your build box. ;)

**Comment by tdsmith** [comment]
>  Or formulas could depend on the homebrew version of OpenSSL?

Yes, that has been our preference for a while.

**Comment by DomT4** [comment]
PR was merged.
