### ISSUE TITLE
openVPN failed to build on 10.10.5

### ISSUE THREAD

**Issue by benalane** [Homebrew/homebrew#44381]
I'm trying to install openvpn from home-brew but I'm not having any luck. I'm running OS X 10.10.5 and have recently upgraded Xcode to version 7. I still have the command line tools installed. I've done a couple hours of Googling with no luck.

Here is the output when it fails:
```
==> ./configure --disable-silent-rules --with-crypto-library=openssl --prefix=/u
Last 15 lines from /Users/benjamin/Library/Logs/Homebrew/openvpn/01.configure:
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-apple-darwin14.5.0
checking host system type... x86_64-apple-darwin14.5.0
checking for style of include used by make... GNU
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/private/tmp/openvpn20150927-6339-1c8xlvf/openvpn-2.3.8':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

https://gist.github.com/022823837e79d68416f8

**Comment by mistydemeo** [comment]
From your `brew doctor`:

```
Warning: Xcode 7 lacks the 10.10 SDK which can cause some builds to fail.
We recommend installing the Command Line Tools with:
  xcode-select --install
to resolve this issue.
```

**Comment by benalane** [comment]
Thank you for the response. I did that earlier with no luck -- and I am able to use clang/gcc/make etc.

**Comment by DomT4** [comment]
Your CLT is still showing null: `CLT: N/A`. Can you try the `sudo xcode-select --install` again? If it has been installed it should reside in `/Library/Developer`.

**Comment by benalane** [comment]
I ran it with sudo this time. Same result. I do not, however, have a `/Library/Developer` folder.

**Comment by tdsmith** [comment]
What happens when you run `xcode-select --install`? Does it print any output? What is the output of `pkgutil --info com.apple.pkg.CLTools_Executables`?

**Comment by benalane** [comment]
Each time I run `xcode-select --install` I get a install successful pop-up (it never mentions that I've installed them before).

Here's the output of the command:
```
[benjamin@horseradish:/] pkgutil --info com.apple.pkg.CLTools_Executables
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
```

**Comment by benalane** [comment]
Problem solved with upgrade to El Capitan.
