### ISSUE TITLE
cmake installation (Patching stage)

### ISSUE THREAD

**Issue by smart-t** [Homebrew/homebrew#44390]
Stuck I am in installing cmake on my Chromebook. With Homebrew 0.9.5 installing cmake; "brew install cmake" strands on zlib Patching stage. It looks like it could not find the patch dir. Does anyone has an idea what I'm facing here, or perhaps know what to do to get cmake installed?

**Comment by tdsmith** [comment]
If you're using Linuxbrew you should file against the Linuxbrew repository and include the terminal output you're seeing.

**Comment by DomT4** [comment]
This issue was moved to Homebrew/linuxbrew#573
