### ISSUE TITLE
Bake in Brewfile Support

### ISSUE THREAD

**Issue by mattdipasquale** [Homebrew/homebrew#44409]
If [Brew Bundle](https://github.com/Homebrew/homebrew-bundle) is the [official replacement for `brew bundle`](https://github.com/Homebrew/homebrew/issues/32952#issuecomment-71630007) #32952, you might consider adding it back to Homebrew instead of keeping it as a separate tap.

Because:
* Brew Bundle is actively maintained.
* The `gem` command comes with Gemfile support, so I expect the `brew` command to come with Brewfile support. gem : Gemfile :: brew : Brewfile

**Comment by xu-cheng** [comment]
Sorry, but this won't happen. `brew bundle` is designed to be an external brew command. Also it makes maintaining much easier when it's in separate repo.
