### ISSUE TITLE
Install failed for brew link 

### ISSUE THREAD

**Issue by buildhappy** [Homebrew/homebrew#44424]
➜  ~  brew reinstall mpv
==> Reinstalling mpv-player/mpv/mpv
Error: You must `brew link xz automake libtool libpng freetype fribidi gobject-introspection x264 libvo-aacenc mpg123 little-cms2 lua' before mpv-player/mpv/mpv can be installed

**Comment by DomT4** [comment]
Did you try running:

```
brew link xz automake libtool libpng freetype fribidi gobject-introspection x264 libvo-aacenc mpg123 little-cms2 lua
```
And then doing `brew reinstall mpv`?

**Comment by DomT4** [comment]
Presuming resolved.

**Comment by buildhappy** [comment]
It works，thankyou
