### ISSUE TITLE
If a package doesn't exist, but a tap does, it's not clear to the user what to do

### ISSUE THREAD

**Issue by ericandrewlewis** [Homebrew/homebrew#44421]
Tonight I wanted to install xplot. I tried to install it with brew and got this error

<img width="471" alt="screen shot 2015-09-28 at 9 32 57 pm" src="https://cloud.githubusercontent.com/assets/1087646/10153254/8c4cc258-6628-11e5-8c63-ce9efd76b574.png">

So I figured it wasn't possible to install from brew, and tried to install from source.

I now realize that taps are other repos that can be installed by specifying them explicitly. Which I did and now I have xplots installed :smile: 

I think more usable feedback could be provided to users in the "Searching taps..." section to explain what their options are.

**Comment by DomT4** [comment]
See #42222. It's on the radar :smiley:. Feel free to leave a comment there saying you'd find it useful, etc, if you'd like to.
