### ISSUE TITLE
Formula not creating symlink from patch diff

### ISSUE THREAD

**Issue by kausters** [Homebrew/homebrew#44436]
I'm editing a Homebrew formula and trying to symlink a certain file into the source directory, to be used when compiling. The link is specified in a diff, as a DATAPatch.

When applying the diff by Git itself, it creates the symlink as it should. However, when it's done via Homebrew, it creates a new file with just the path of the source file inside. This makes me think it's a bug with Homebrew since applying by Git works.

Here is the diff (note the `new file mode 120000` which indicates it's a symlink):
```
diff --git a/wordexp.h b/wordexp.h
new file mode 120000
index 0000000..1b6e119
--- /dev/null
+++ b/wordexp.h
@@ -0,0 +1 @@
+/usr/include/wordexp.h
\ No newline at end of file
```

**Comment by kausters** [comment]
Turns out that this is because GNU patch (which Homebrew uses) cannot create symlinks (as per documentation, in caveats). Homebrew could probably switch to `git apply` since Git is required anyway.

**Comment by bfontaine** [comment]
Why don’t you link manually in the `install` method with `ln_s`?

**Comment by kausters** [comment]
I wanted the symlink to already exist once `brew install --interactive` activates the shell — I can achieve this with a patch but not with `install` (unless there's some other method I can use that's not mentioned in the [Formula Cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md))

**Comment by bfontaine** [comment]
> (unless there's some other method I can use that I couldn't find in the Formula Cookbook)

Nope, there isn’t.

**Comment by DomT4** [comment]
Closing per the above. `ln_s` seems like the best option for non-interactive installs but the interactive shell implies a certain level of users needing to self-configure the steps that would otherwise happen automatically, as is the case here.
