### ISSUE TITLE
i need help for some questions about install

### ISSUE THREAD

**Issue by chinume** [Homebrew/homebrew#44435]
MoodeMacBook-Pro:local moo$ pwd
/usr/local
MoodeMacBook-Pro:local moo$ ls -a
.	..	.git	bin
MoodeMacBook-Pro:local moo$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
It appears Homebrew is already installed. If your intent is to reinstall you
should do the following before running this installer again:
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
MoodeMacBook-Pro:local moo$ 
MoodeMacBook-Pro:local moo$ pwd
/usr/local
MoodeMacBook-Pro:local moo$ ls -a
.	..	.git	bin
MoodeMacBook-Pro:local moo$

**Comment by bfontaine** [comment]
What are your questions?

**Comment by chinume** [comment]
Nothing in my desk albeit it's install.

**Comment by dardo82** [comment]
What does this means? o.O

**Comment by DomT4** [comment]
Closing here. Please let us know if we can assist you further @chinume.

**Comment by chinume** [comment]
it's complete for that (｡◕ˇ∀ˇ◕)
