### ISSUE TITLE
percona-server default settings

### ISSUE THREAD

**Issue by mikhailov** [Homebrew/homebrew#44442]
By default Percona Server 5.6+ has performance scheme enabled which consumes 500MB RAM which can be not necessary on development machine. I would recommend to switch it off. Additional recommendation for development machine (I guess that Homebrew is designed for), no need to care about crashing mysqld on local environment.

**/etc/my.cnf**

````
[mysqld]

performance_schema = 0
innodb_flush_log_at_trx_commit=2
sync_binlog=0
query_cache_size=0
query_cache_type=0
skip-innodb_doublewrite
```

**Comment by bfontaine** [comment]
Homebrew doesn’t write in `/etc/`; you should report this issue to upstream instead.
