### ISSUE TITLE
carthage: outdated

### ISSUE THREAD

**Issue by pvinis** [Homebrew/homebrew#44448]
latest here is 0.8, and on github its 0.9.2

**Comment by bfontaine** [comment]
Would you mind making a pull-request? This should help and I’m happy to answer any question you might have: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

**Comment by DomT4** [comment]
See #43884. We've been having some Xcode issues.
