### ISSUE TITLE
qt5: not working properly when installed from within Travis CI

### ISSUE THREAD

**Issue by agarny** [Homebrew/homebrew#44446]
Until a couple of days ago, I could install qt5 within [Travis CI](https://travis-ci.org/) without any problem. However, today, it just keeps failing. I have noticed that a new version of the formula has been released. So, could there be a 'bug' in it that breaks Travis CI?

Basically, Travis CI complains about the log length having exceeded the limit of 4 MB. Checking the Travis CI output when installing qt5, I can see that the 'progress bar' doesn't progress 'normally' and, in fact, flashes all over the place. I am not sure what is going on under the hood, but it's certainly causing Travis CI to 'fail'.

My 'fix' currently consists of redirecting the output to ```/dev/null```, but that's clearly not something I want to have to do...

**Comment by xu-cheng** [comment]
Any chance to show the Travis config you used to install qt5?

**Comment by agarny** [comment]
Sure. Sorry for not doing it in the first place. The script that 'fails' (but used to work a couple of days ago) can be found [here](https://github.com/opencor/opencor/blob/3f8a31be724aef8cb5c4a70b95f6fda9f3b6c10b/.travis.yml#L32) while the one that I am now using (temporarily, I hope) can be found [here](https://github.com/opencor/opencor/blob/2db293c3144146832812184d73e58eece6806e21/.travis.yml#L35).

**Comment by xu-cheng** [comment]
The progress bar comes from curl downloading. I think this is a bug from Travis end. You may wish to report this to them.

**Comment by agarny** [comment]
Thank, I am going to do that, although if it is a problem with Travis CI, then I don't understand why the progress bar works fine when installing cmake (which I do just before installing qt5)...

**Comment by agarny** [comment]
By the way, a typical output of what I am getting can be found [here](https://travis-ci.org/opencor/opencor/builds/82883318).

**Comment by The-Compiler** [comment]
I'm seeing the same. Ironically, passing `-v` helped as this disables the progress bar and shows curl output instead.

Looking at the [raw log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/82883319/log.txt), every progress bar (for every 1/10th percent) is output 65 times,  so the log is indeed >4MB (55'000 lines for installing qt5).

**Comment by agarny** [comment]
Thanks a lot @The-Compiler, it all makes sense now, and thanks too for the ```-v``` suggestion (I wish I had thought of it!).

@xu-cheng, I guess this issue can be closed...

**Comment by The-Compiler** [comment]
I don't think this should be closed, it still seems like a Homebrew issue to me. Why would it redraw the progress bar so many times, and only for that package?

**Comment by agarny** [comment]
I don't think it's a Homebrew issue, but a curl one (if anything).

If you check the [raw log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/82883319/log.txt), you can see that I also install the ```cmake``` formula, and curl also redraws the progress bar many times, just not as often since the ```cmake``` formula is quite a bit smaller than the ```qt5``` formula.

So, if anything, curl should be a bit smarter and realise that there is no point in redrawing the progress bar if it's not going to make a visual difference (i.e. no additional ```#``` is going to be drawn).

**Comment by The-Compiler** [comment]
I tried to replicate this using `script` to record the output - I don't see the issue mentioned above, but I see the progress bar jumping to 100% and then back to 20%.

I wasn't aware the progress bar is drawn directly by curl. When I do `curl -LO# 'https://homebrew.bintray.com/bottles/qt5-5.5.0_1.yosemite.bottle.1.tar.gz'` however, it seems to look fine...

**Comment by dunn** [comment]
The environment can affect progress bars.  Running `brew install` within a tmux pane often has similar issues.

**Comment by xu-cheng** [comment]
We should probably offer a `HOMEBREW_CURL_QUIET` env to silence curl progress bar completely.

**Comment by The-Compiler** [comment]
@xu-cheng :+1: (or alternatively, a commandline argument)

**Comment by dunn** [comment]
Linking this to #44320

**Comment by mikemcquaid** [comment]
@dunn I don't think that's related to us given that issue is just about the issues we're having using Travis CI for Homebrew builds.

**Comment by dunn** [comment]
:see_no_evil:

**Comment by scpeters** [comment]
I tinkered with silencing curl in https://github.com/scpeters/homebrew/commit/c1a627e220fb5d6d14bbf46a0022f25f97600624, and it worked for my travis-ci log file issues, but that was just a hard-coded silencing. A parameter would still need to be implemented
