### ISSUE TITLE
Postgis fails to install when xcode is on a drive with a space in the name

### ISSUE THREAD

**Issue by dalkvist** [Homebrew/homebrew#44468]
bash-3.2$ brew install postgis
==> Installing dependencies for postgis: proj, libtiff, libspatialite, cgal
==> Installing postgis dependency: proj
==> Downloading https://homebrew.bintray.com/bottles/proj-4.9.2.yosemite.bottle.tar.gz
######################################################################## 100,0%
==> Pouring proj-4.9.2.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/proj/4.9.2: 52 files, 6,0M
==> Installing postgis dependency: libtiff
==> Downloading https://homebrew.bintray.com/bottles/libtiff-4.0.6.yosemite.bottle.tar.gz
######################################################################## 100,0%
==> Pouring libtiff-4.0.6.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libtiff/4.0.6: 259 files, 3,9M
==> Installing postgis dependency: libspatialite
==> Downloading https://homebrew.bintray.com/bottles/libspatialite-4.3.0a.yosemite.bottle.tar.gz
######################################################################## 100,0%
==> Pouring libspatialite-4.3.0a.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libspatialite/4.3.0a: 28 files, 19M
==> Installing postgis dependency: cgal
==> Downloading https://homebrew.bintray.com/bottles/cgal-4.6.3.yosemite.bottle.tar.gz
######################################################################## 100,0%
==> Pouring cgal-4.6.3.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/cgal/4.6.3: 2803 files, 34M
==> Installing postgis
==> Downloading http://download.osgeo.org/postgis/source/postgis-2.1.7.tar.gz
Already downloaded: /Library/Caches/Homebrew/postgis-2.1.7.tar.gz
==> ./configure --with-projdir=/usr/local --with-jsondir=/usr/local/opt/json-c --with-pgconfig=/usr/local/Cellar/postgresql/9.4.4/bin/pg_config --disable-nls
==> make
Last 15 lines from /Users/appbuilder/Library/Logs/Homebrew/postgis/02.make:
2015-09-30 09:45:21 +0200

make

/usr/bin/perl utils/svn_repo_revision.pl
Can't fetch local revision (neither .svn nor .git found)
Not updating existing rev file at 13414
for s in liblwgeom libpgcommon postgis regress raster topology loader utils doc extensions; do \
		echo "---- Making all in ${s}"; \
		/Volumes/Macintosh HD 2/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ${s} all || exit 1; \
	done;
---- Making all in liblwgeom
/bin/sh: /Volumes/Macintosh: No such file or directory
make: *** [all] Error 1

**Comment by DomT4** [comment]
There's a `brew doctor` check for [this](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/doctor.rb#L550-L559) because it is known to cause issues. I'm afraid you'll have to move or copy Xcode somewhere that doesn't contain spaces.
