### ISSUE TITLE
Install failed - now it's stuck!

### ISSUE THREAD

**Issue by jasonbutler** [Homebrew/homebrew#44460]
Error log:
Jasons-MBP:~ Jason$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
Failed to locate Homebrew!
Jasons-MBP:~ Jason$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
It appears Homebrew is already installed. If your intent is to reinstall you
should do the following before running this installer again:
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
Jasons-MBP:~ Jason$ brew doctor
-bash: brew: command not found
Jasons-MBP:~ Jason$ brew update
-bash: brew: command not found
Jasons-MBP:~ Jason$ 

It wont uninstall, update or run anything - I can't get it off my machine to try again! Help

**Comment by tdsmith** [comment]
Try `rm -rf /usr/local/.git`.

**Comment by tingyu66** [comment]
I got the same issue after I upgraded my machine from Maverick to Yosemite. Exactly the same error log as @jasonbutler.

I first used `$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"` and tried to uninstall homebrew. I cannot find the log, but it indeed deleted something and output some error. After that I think `/usr/local/bin/brew` was deleted. Eventually got the same error as Jason.

I tried the command provided by @tdsmith, but it doesn't work. Appreciate your help, thanks.

**Comment by tingyu66** [comment]
@jasonbutler
I brought my brew back to life, after rm the `sudo rm -rf /usr/local/.git` and `chown username /usr/local`, I finally can reinstall brew. Thanks @tdsmith for the help.

**Comment by williameliel** [comment]
@tdsmith +1

**Comment by Z-starts** [comment]
@tdsmith +1

**Comment by Z-starts** [comment]
@tdsmith +1

**Comment by bys-levi-lu** [comment]
@tingyu66 +1

**Comment by DomT4** [comment]
Closing with the known fix then. Thanks @tingyu66.

**Comment by alexbaumgertner** [comment]
@tdsmith :+1: it works!

**Comment by fengshuinality** [comment]
Thank you tingyu66!

**Comment by yangcaimu** [comment]
Thanks.It works!

**Comment by RioV** [comment]
@tdsmith +1

**Comment by Jerry-Lau** [comment]
@tdsmith +1, thank you very much! helped me a lot.

**Comment by hi-github** [comment]
@tdsmith +1, thanks, and retry `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`, success!

**Comment by tdsmith** [comment]
Why are so many people having this problem? I would have thought this would be esoteric.

**Comment by mehadhe** [comment]
@tdsmith +1, Thank you bro :-) Thank you very much....

**Comment by saurabhmaun** [comment]
Working (Y)

**Comment by tdebroc** [comment]
+1
