### ISSUE TITLE
Compile issue with lynx and Yosemite

### ISSUE THREAD

**Issue by thedocbwarren** [Homebrew/homebrew#44478]
Having an issue compiling lynx on XCode 7 and Yosemite.

brew install lynx
==> Downloading http://invisible-mirror.net/archives/lynx/tarballs/lynx2.8.8rel.2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/lynx-2.8.8rel.2.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/lynx/2.8.8rel.2_1 --mandir=/usr/local/Cellar/lynx/2.8.8rel.2_1/share/man --disable-echo --enable-default-colors --w
Last 15 lines from /Users/m658761/Library/Logs/Homebrew/lynx/01.configure:
Configuring for darwin14.5.0
checking for DESTDIR... 
checking for gcc... clang
checking for C compiler default output... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for executable suffix... 
checking for object suffix... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking version of clang... 7.0.0
checking for clang option to accept ANSI C... none needed
checking $CC variable... ok
checking how to run the C preprocessor... /lib/cpp
configure: error: C preprocessor "/lib/cpp" fails sanity check

**Comment by DomT4** [comment]
Can you `brew gist-logs lynx` please.

**Comment by thedocbwarren** [comment]
Done.

**Comment by DomT4** [comment]
```
Warning: Xcode 7 lacks the 10.10 SDK which can cause some builds to fail.
We recommend installing the Command Line Tools with:
  xcode-select --install
to resolve this issue.
```

Looks like another case of this. You can also upgrade to 10.11 if you'd prefer, where the CLT is not required (Because Xcode 7 actually contains the 10.11 SDK).

**Comment by thedocbwarren** [comment]
Just updated to 10.11 thank you!

**Comment by DomT4** [comment]
Let us know if you hit any further issues! :smiley:
