### ISSUE TITLE
brew home swiftgen fails on 10.8.5

### ISSUE THREAD

**Issue by bwagner** [Homebrew/homebrew#44474]
brew home swiftgen
Error: compile error
/usr/local/Library/Formula/swiftgen.rb:29: syntax error, unexpected ')'
/usr/local/Library/Formula/swiftgen.rb:45: syntax error, unexpected $end, expecting kEND
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Formula/swiftgen.rb:45:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:205:in `factory'
/usr/local/Library/Homebrew/formulary.rb:353:in `find_with_priority'
/usr/local/Library/Homebrew/extend/ARGV.rb:20:in `formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/home.rb:6:in `home'
/usr/local/Library/brew.rb:133:in `send'
/usr/local/Library/brew.rb:133

**Comment by DomT4** [comment]
The syntax used in that formula wasn't supported by Ruby 1.8, which OS X 10.8 uses. Fixed by https://github.com/Homebrew/homebrew/commit/14eb880c789ca895829820d6058684c41fe4b54e.
