### ISSUE TITLE
docker-compose - OSX - throws python "InsecurePlatformWarning"

### ISSUE THREAD

**Issue by roytruelove** [Homebrew/homebrew#44481]
@alex @ryanmt 

OSX Yosemite v 10.10.3 

Latest docker-compose.rb gives the following warning for every run:
```
/usr/local/Cellar/docker-compose/1.4.2/libexec/vendor/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning:
A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail.
For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
```

I follwed the directions in the link above but to no avail, still get the errors.

**Comment by DomT4** [comment]
See https://github.com/Homebrew/homebrew/issues/42416#issuecomment-127418848 & #41766 for the prior discussion here on the same issue. The easy fix is to update your OS X from 10.10.3 to 10.10.5 which contains several useful security fixes & enhancements, including an updated Python which banishes the `InsecurePlatformWarning` warning.

CC @tdsmith.
