### ISSUE TITLE
v8-315 SHA256 mismatch

### ISSUE THREAD

**Issue by thehappycoder** [Homebrew/homebrew#44496]
$ brew install homebrew/versions/v8-315
==> Installing v8-315 from homebrew/homebrew-versions
==> Downloading https://github.com/v8/v8-git-mirror/archive/3.15.11.18.tar.gz
Already downloaded: /Library/Caches/Homebrew/v8-315-3.15.11.18.tar.gz
Error: SHA256 mismatch
Expected: 389c03f67731874342486536bd231c43281fe43d05001664000abd3ac48fd9cf
Actual: 93a4945a550e5718d474113d9769a3c010ba21e3764df8f22932903cd106314d
Archive: /Library/Caches/Homebrew/v8-315-3.15.11.18.tar.gz
To retry an incomplete download, remove the file above.

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/homebrew-versions#982
