### ISSUE TITLE
Permissions message should detect shell and display appropriate command

### ISSUE THREAD

**Issue by frewsxcv** [Homebrew/homebrew#44495]
```
> brew update; and brew upgrade
Error: The /usr/local directory is not writable.
Even if this directory was writable when you installed Homebrew, other
software may change permissions on this directory. Some versions of the
"InstantOn" component of Airfoil are known to do this.

You should probably change the ownership and permissions of /usr/local
back to your user account.
  sudo chown -R $(whoami):admin /usr/local
```

I use fish shell and that bottom command is invalid for fish. If it's trivial, it'd be nice if that would display  `sudo chown -R (whoami):admin /usr/local` instead if the user is using fish shell. Not a huge deal, just pointing it out in case it wasn't already known

**Comment by hmbr** [comment]
I bet that you upgraded to el capitan

**Comment by hmbr** [comment]
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md

**Comment by dlh** [comment]
The message could use `$USER` instead of `$(whomi)`. :information_desk_person:

**Comment by DomT4** [comment]
The `doctor` recommendation is being replaced soon, which nullifies individual shell tweaks. Feel free to track https://github.com/Homebrew/homebrew/pull/45934 :smiley:.
