### ISSUE TITLE
mu failed to build on 10.10.5

### ISSUE THREAD

**Issue by justmytwospence** [Homebrew/homebrew#44508]
https://gist.github.com/ed8f2ec1ebba436242e1

Possibly related to the upgrade to 0.9.13? It installs properly when I do not specify `--with-emacs`.

**Comment by cmdli** [comment]
Installing works without errors on 10.11 on my machine.

**Comment by dunn** [comment]
Looks like this is where it's failing:
```
/private/tmp/mu20151001-51841-1hjf5ni/mu-0.9.13/missing: line 81: makeinfo: command not found
WARNING: 'makeinfo' is missing on your system.
         You should only need it if you modified a '.texi' file, or
         any other file indirectly affecting the aspect of the manual.
         You might want to install the Texinfo package:
         <http://www.gnu.org/software/texinfo/>
         The spurious makeinfo call might also be the consequence of
         using a buggy 'make' (AIX, DU, IRIX), in which case you might
         want to install GNU make:
         <http://www.gnu.org/software/make/>
Makefile:490: recipe for target 'mu4e.info' failed
```
Could you run `brew edit mu` and add a new line with `depends_on "texinfo"` and try installing again?

**Comment by justmytwospence** [comment]
That did the trick! Do we need to add this to the recipe? Texinfo was already installed on my system, what exactly does the depends_on add?

**Comment by dunn** [comment]
For some reason it wasn't finding the system makeinfo, so adding the `depends_on` line makes sure the Homebrew version is in your PATH during installation.  I'm not sure if this is a general problem or something funny with your system, though.  What's the output of `which makeinfo`?

**Comment by justmytwospence** [comment]
`makeinfo not found`. `brew info texinfo` says it is keg-only, not linked into /usr/local, so under what circumstances would it be expected to be in my path?

**Comment by dunn** [comment]
There should be a system version installed in `/usr/bin`; at least there is in El Capitan and I'm almost positive there was before I upgraded.

**Comment by justmytwospence** [comment]
Interesting. my /usr/bin/makeinfo is a symlink to the homebrew one.

**Comment by dunn** [comment]
That's odd; it must have overwritten the original.  If you have another computer or someone you trust to send you a copy of their `/usr/bin/makeinfo` you probably want to try to restore it.

**Comment by DomT4** [comment]
Any update here?

Theoretically if you've updated to 10.11 in the mean time this should self-resolve because it'd be replaced by OS X. Otherwise, yeah, you'll need to get the original. You'd likely be able to fish it out of the `.pkg` inside a Yosemite OS X download as well.

**Comment by justmytwospence** [comment]
I'll just use the edited formula until i upgrade to 10.11.
