### ISSUE TITLE
gfortran problem while installing Octave

### ISSUE THREAD

**Issue by brkztrk** [Homebrew/homebrew#44502]
Hi there,

I am trying to install Octave on my mac, OS X El Capitan. I got this issue, i searched but nothing found.

make
check

gfortran -o tester -O tester.f90 vecLibFort.o -framework Accelerate 
ld: framework not found Accelerate
collect2: error: ld returned 1 exit status
make: *** [check] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues

How can I fix that?

Thanks in advance.

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-science#2806

**Comment by brkztrk** [comment]
Why you close that? Is there any solution idea to fix it?

**Comment by DomT4** [comment]
Just moved it to the correct repository, as stated in the message above. It's not a core Homebrew formula, so there's a limited amount of help we can provide compared to the team responsible for maintaining that tap.

> If reporting this issue please do so at (not Homebrew/homebrew):
https://github.com/homebrew/homebrew-science/issues
