### ISSUE TITLE
installation loop

### ISSUE THREAD

**Issue by danielb2** [Homebrew/homebrew#44518]
```
[~]$ brew install caskroom/cask/brew-cask

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

Error: Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool
```

OK, fine ...

```
[~]$ sudo brew install caskroom/cask/brew-cask
Error: Cowardly refusing to `sudo brew install`
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
```

Arrrgh ...

So now what?

**Comment by bfontaine** [comment]
Run `sudo xcodebuild -license` to accept the Xcode/iOS license.

**Comment by DomT4** [comment]
Closing per the above. Let us know if you see any further issues, Thanks.

**Comment by danielb2** [comment]
I already knew of the fix, it just seems strange it should get to a point where there's a loop

**Comment by tdsmith** [comment]
`please re-run as root via sudo.` is Xcode's message; I don't know if we can detect that.

**Comment by danielb2** [comment]
Look above, the output from running it as root is there.

**Comment by tdsmith** [comment]
Right; the text telling you to re-run the command as root is wrong, but it's being emitted by Xcode and not by Homebrew.
