### ISSUE TITLE
git-extras: disable `git extras update`?

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#44520]
The `git-extras` package has a `git-extras update` subcommand to install a new `git-extras` version. It is not aware of Homebrew or some prefix options, and is a little immature. If you run `git extras update` using Homebrew-managed `git-extras`, it will install a broken and/or non-brew-tracked `git-extras` into `/usr/local`, or just error out.

Should we disable `git-extras update` as part of the `git-extras` formula installation steps? It would be easy to do; just remove some lines from `bin/git-extras`.

**Comment by bfontaine** [comment]
I think we shouldn’t remove it but instead print something like “If you’d like to update `git-extras`, run `brew upgrade git-extras`”.

**Comment by apjanke** [comment]
Even better.

**Comment by DomT4** [comment]
Closing in favour of #44521.
