### ISSUE TITLE
Cannot install phantomjs on 10.11

### ISSUE THREAD

**Issue by karlingen** [Homebrew/homebrew#44525]
Output:
```
$ brew install phantomjs
phantomjs: OS X Yosemite or older is required.
Error: An unsatisfied requirement failed this build.

$ brew install phantomjs --HEAD
phantomjs: OS X Yosemite or older is required.
Error: An unsatisfied requirement failed this build.
```

How can I resolve this?

**Comment by bfontaine** [comment]
phantomjs is broken on 10.11; we’re waiting for upstream to issue a new release. See https://github.com/Homebrew/homebrew/issues/42249#issuecomment-139864544

**Comment by DomT4** [comment]
I've removed the block from `head`. It will likely keep failing until the upstream Qt issues are addressed, but only capping stable blocks is consistent with our policy on MMOS requirements elsewhere.
