### ISSUE TITLE
PhantomJS support for El Capitan

### ISSUE THREAD

**Issue by 3zcurdia** [Homebrew/homebrew#44535]

**Comment by DomT4** [comment]
See https://github.com/Homebrew/homebrew/issues/42249#issuecomment-139864544.

It's an upstream issue, not a Homebrew one. You can try `brew update && brew install phantomjs --HEAD` but there are no guarantees that will succeed.

**Comment by leandroalemao** [comment]
As a workaround.. I've downgraded to 1.9.8.. it's working.. but too slow.

``` npm install phantom phantomjs -g ```

**Comment by joaquinalcerro** [comment]
I have Apple OS X - El Capitan and I did the following and looks like it's working:

sudo npm -g install phantomjs2

When I executed this command, If failed installing.... it never finished but the phantomjs v2 gets downloaded to this directory

/usr/local/lib/node_modules/phantomjs2/phantomjs/phantomjs-2.0.0-20141016-macosx.zip-extract-1447034534278/phantomjs-2.0.0-20141016

It will contain a bin and examples directory

Go into the bin directory where you will find the phantomjs file 50MB approximately.

Check in what directory phantomjs file located:

which phantomjs (i got = /usr/local/bin/phantomjs but this file points to: /usr/local/lib/node_modules/phantomjs2/bin/phantomjs)

As root (sudo cp) copy the downloaded phantomjs file to this directory (in my case = /usr/local/lib/node_modules/phantomjs2/bin/). NOTE: the last part, phantomjs is the file name. Don't include it.

Check that this file is executable. If it is not executable, use chmod to make it executable.

Phantomjs should be installed now.

Try

phantomjs --version

**Comment by camwhite** [comment]
Thank you for the tips @joaquinalcerro !!!

I am running into an issue while attempting to copy the phantomjs file. I am seeing this error:

```bash
sudo cp /usr/local/lib/node_modules/phantomjs2/bin/phantomjs /usr/local/lib/node_modules/phantomjs2/bin

cp: /usr/local/lib/node_modules/phantomjs2/bin/phantomjs and /usr/local/lib/node_modules/phantomjs2/bin/phantomjs are identical (not copied).
```

I'm prob just doing it wrong :tired_face:  Would you mind elaborating at all?

**Comment by Gcamara14** [comment]
Hey guys! I managed to by pass this by using - 

brew install npm
npm install phantom phantomjs -g

**Comment by akash227** [comment]
#Gcamara14 Thank you! It worked for me

**Comment by dantmcgowan** [comment]
#Gcamara14 +1 thx

**Comment by cshutchinson** [comment]
#Gcamara14 Thank you! It worked for me

**Comment by gregrenard** [comment]
Thank you !  It worked too for me.
