### ISSUE TITLE
Probable gfortran error.

### ISSUE THREAD

**Issue by mbarsacchi** [Homebrew/homebrew#44536]
I've had some problems in installing veclibfort. 
I've posted it in Homebrew/homebrew-science but it seems to be related to gfortran.
```
$brew install veclibfor

...

make
check

gfortran -o tester -O tester.f90 vecLibFort.o -framework Accelerate
ld: framework not found Accelerate
collect2: error: ld returned 1 exit status
make: *** [check] Error 1
```

Here's the gist link.
https://gist.github.com/7e063ac3b14266dceef1

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-science#2813

**Comment by DomT4** [comment]
The formula resides in the Science tap so I've moved it [there](https://github.com/Homebrew/homebrew-science/issues/2813). As the host tap will know the formula more, we try to keep issues in whichever tap that is.

**Comment by mbarsacchi** [comment]
I posted it in science yesterday. Someone said: given the fact that it is probably related to gfortran, please reports this upstream. And so I have done. [gfortran is part of gcc that is located in homebrew tap]

> Il giorno 02 ott 2015, alle ore 20:20, Dominyk Tiller <notifications@github.com> ha scritto:
> 
> The formula resides in the Science tap so I've moved it there <https://github.com/Homebrew/homebrew-science/issues/2813>. As the host tap will know the formula more, we try to keep issues in whichever tap that is.
> 
>

**Comment by DomT4** [comment]
By upstream, I suspect they meant report it to the original project (GCC) rather than to Homebrew.
