### ISSUE TITLE
brew doctor complaint about: libUFSDNTFS.dylib

### ISSUE THREAD

**Issue by scottjl** [Homebrew/homebrew#44542]
% brew doctor
    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry and just ignore them. Thanks!

    Warning: Unbrewed dylibs were found in /usr/local/lib.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected dylibs:
        /usr/local/lib/libUFSDNTFS.dylib

`/usr/local/lib/libUFSDNTFS.dylib` is installed by [Paragon Software's NTFS for Mac v14](http://www.paragon-software.com/home/ntfs-mac/) and definitely shouldn't be deleted if you use that software.

This file should be whitelisted.

**Comment by DomT4** [comment]
Happy enough to do this. The dylib name doesn't seem to clash with anything else, it's likely to be popular & we've generally added filesystem-extension dylibs to the whitelist before.

Done in https://github.com/Homebrew/homebrew/commit/fd96ae25865c7be23edabfdca18770774b1b27a8.

**Comment by mikezahno** [comment]
Same warning for Paragon ExtFS for Mac 2014 or maybe 2015:
/usr/local/lib/libUFSDExtFS.dylib

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew/commit/2984c36d55e1c4885fe7ab8c869e7b2568ce06ec
