### ISSUE TITLE
Error updating

### ISSUE THREAD

**Issue by sairajgemini** [Homebrew/homebrew#44547]
Error: undefined method `<' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula_support.rb:21:in `valid?'
/usr/local/Library/Homebrew/formula.rb:779:in `keg_only?'
/usr/local/Library/Homebrew/formula_installer.rb:129:in `block in check_install_sanity'
/usr/local/Library/Homebrew/formula_installer.rb:128:in `select'
/usr/local/Library/Homebrew/formula_installer.rb:128:in `check_install_sanity'
/usr/local/Library/Homebrew/formula_installer.rb:106:in `prelude'
/usr/local/Library/Homebrew/cmd/upgrade.rb:62:in `upgrade_formula'
/usr/local/Library/Homebrew/cmd/upgrade.rb:44:in `block in upgrade'
/usr/local/Library/Homebrew/cmd/upgrade.rb:44:in `each'
/usr/local/Library/Homebrew/cmd/upgrade.rb:44:in `upgrade'
/usr/local/Library/brew.rb:133:in `<main>'

**Comment by DomT4** [comment]
Try:
```
cd $(brew --prefix) && git fetch && git reset --hard origin/master
```
After that run `brew update` and see if all is good. If the problem still persists do a `brew readall` and see if anything is flagged.

**Comment by DomT4** [comment]
Presuming resolved, but less us know otherwise. Thanks!

**Comment by Zsub** [comment]
Seeing the same issue:

```
$ cd $(brew --prefix) && git fetch && git reset --hard origin/master
HEAD is now at 7c2bc98 poppler: refuse to build with incompatible options
$ brew update && brew upgrade --all
Already up-to-date.
==> Upgrading 5 outdated packages, with result:
imagemagick 6.9.2-4, pango 1.38.1, sqlite 3.9.1, xz 5.2.2, youtube-dl 2015.10.18
Error: undefined method `<' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula_support.rb:21:in `valid?'
/usr/local/Library/Homebrew/formula.rb:806:in `keg_only?'
/usr/local/Library/Homebrew/formula_installer.rb:134:in `block in check_install_sanity'
/usr/local/Library/Homebrew/formula_installer.rb:133:in `select'
/usr/local/Library/Homebrew/formula_installer.rb:133:in `check_install_sanity'
/usr/local/Library/Homebrew/formula_installer.rb:111:in `prelude'
/usr/local/Library/Homebrew/cmd/upgrade.rb:66:in `upgrade_formula'
/usr/local/Library/Homebrew/cmd/upgrade.rb:46:in `block in upgrade'
/usr/local/Library/Homebrew/cmd/upgrade.rb:45:in `each'
/usr/local/Library/Homebrew/cmd/upgrade.rb:45:in `upgrade'
/usr/local/Library/brew.rb:146:in `<main>'
$ brew readall
$ (no output)
```
