### ISSUE TITLE
How to get the path to another package?

### ISSUE THREAD

**Issue by ahundt** [Homebrew/homebrew#44540]
I'm writing an installer for one package that needs the cmake config i.e. `CisstNetlibConfig.cmake` file of another package. Said file is in the directory `/usr/local/Cellar/cisstnetlib/HEAD/cmake`, so I need to get the directory of the installation as part of my formulae to pass it to the cmake of the new package I'm installing.

I checked a few of the docs and tried googling and couldn't find anythings specific. Thanks!

**Comment by DomT4** [comment]
`Formula["cisstnetlib"].opt_prefix`, or `"#{Formula["cisstnetlib"].opt_prefix}/cmake"` if you want the full path including the directory you're looking for.

It's in the [Formula Cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#variables-for-directory-locations) but appreciate that's kind of an enormous document. We're working towards full API docs slowly.
