### ISSUE TITLE
vim failed to build

### ISSUE THREAD

**Issue by xrisk** [Homebrew/homebrew#44557]
https://gist.github.com/anonymous/2e3b21c877b91e80f3f0

````
Rishavs-MacBook-Pro:codechef xrisk$ brew upgrade vim
==> Upgrading 1 outdated package, with result:
vim 7.4.884
==> Upgrading vim
==> Downloading https://github.com/vim/vim/archive/v7.4.884.tar.gz
Already downloaded: /Library/Caches/Homebrew/vim-7.4.884.tar.gz
==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/7.4.884/share/man --enable-multibyte --with-tlib=ncurses --enable-cscope --with-features=huge --with-compiledby=Ho
==> make
Last 15 lines from /Users/xrisk/Library/Logs/Homebrew/vim/02.make:
^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:16:12: note: previous definition is here
@interface NSArray<__covariant ObjectType> : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration>
           ^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:32: error: method type specifier must start with '-' or '+'
@interface NSArray<ObjectType> (NSExtendedArray)
                               ^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:33: error: expected a type
@interface NSArray<ObjectType> (NSExtendedArray)
                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [objects/os_macosx.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [first] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
vim failed to build https://github.com/Homebrew/homebrew/issues/44557
vim  7.4.488 build fails if Homebrew ruby is installed but /usr/bin/ruby comes first in PATH https://github.com/Homebrew/homebrew/issues/33705
Warning: 
````

**Comment by dunn** [comment]
The version mismatch here might be to blame:
```
Xcode: 6.4
CLT: 7.0.0.0.1.1441394355
```
Can you try upgrading Xcode?

**Comment by rseddon** [comment]
I had the same problem, turns out I was on a pretty old version of XCode.  Upgrading to 7.0.1 solved this for me.

**Comment by jiegec** [comment]
I think we should write this solution somewhere in README?

**Comment by DomT4** [comment]
`brew doctor`, which we tell people who encounter any issues to run, would have flagged this outdatedness. It's also one of the first lines on the troubleshooting page. I'm not sure sticking it somewhere else on top of that is going to be particularly productive, sadly.

**Comment by jiegec** [comment]
@DomT4 That's OK enough.

**Comment by DomT4** [comment]
OP hasn't replied here, so presuming this will be solved by the Xcode update as we've not seen this reported anywhere else. Anyone who hits these sort of problems, `brew doctor` is usually your friend :wink:

**Comment by xrisk** [comment]
I haven't replied because I haven't updated Xcode to v7 yet. Will do that soon and post here if that doesn't fix the build problem. 

Actually, I think it kind of sucks that I need the latest Xcode update (a hefty download) to update my vim :(

**Comment by DomT4** [comment]
> Actually, I think it kind of sucks that I need the latest Xcode update (a hefty download) to update my vim :(

Well, you could remove Xcode from your system (Or even place it in the trash briefly) and then:
```
sudo xcode-select --switch /Library/Developer/CommandLineTools
```
And then try the `vim` update. The problem is the mismatch, and Xcode 6.4 not containing the 10.11 SDK which is the OS X you're using.
