### ISSUE TITLE
Non-bug issue: Homebrew configuration backup?

### ISSUE THREAD

**Issue by mamsw** [Homebrew/homebrew#44561]
Is it possible to create a backup of brew configuration settings (including all the formulas/taps installed) from Yosemite and load it on a new brew installation with El Capitan?

**Comment by tdsmith** [comment]
You can do this with [homebrew-bundle](https://github.com/Homebrew/homebrew-bundle).

In short:
1. brew tap homebrew/bundle on old and new hosts
2. brew bundle dump on old host
3. copy Brewfile to new host
4. brew bundle on new host

**Comment by mamsw** [comment]
Thank you.

**Comment by shanesveller** [comment]
Another possible option:
```shell
brew leaves > brews.txt
[later]
cat brews.txt | xargs brew install
```

**Comment by mamsw** [comment]
Thank you.
