### ISSUE TITLE
undefined method `desc' for Formulary::Formulae::Neovim:Class

### ISSUE THREAD

**Issue by eppineda** [Homebrew/homebrew#44573]
As displayed, when installing neovim on my Mac.
![screen shot 2015-10-04 at 12 22 57 am](https://cloud.githubusercontent.com/assets/6559491/10266417/a49153ba-6a2e-11e5-8adb-c5979f7b91be.png)
![screen_shot_2015-10-04_at_12_26_23_am](https://cloud.githubusercontent.com/assets/6559491/10266421/02be7e90-6a2f-11e5-826b-4c70191323a8.png)

See screenshot.

**Comment by DomT4** [comment]
Please `brew update` and see if the issue persists.

**Comment by eppineda** [comment]
`brew update ` worked.

**Comment by eppineda** [comment]
Yes, brew update helped, ty.

Will remove issue.
