### ISSUE TITLE
Bottled GCC not working on El Captain + CLT

### ISSUE THREAD

**Issue by veprbl** [Homebrew/homebrew#44600]
I get following linking error with trivial "void main(void){}" programs (also with gfortran):

    ld: library not found for -lSystem
    collect2: error: ld returned 1 exit status

Adding "#include <stdio.h>" makes compilation fail with: 

    test.c:1:19: fatal error: stdio.h: No such file or directory
    compilation terminated.

When gcc is built (in my case I chose ```brew install gcc --without-multilib```) it bootstraps and then (obviously) works.
Does anyone have the same problem with gcc on CLT?

**Comment by DomT4** [comment]
Can you provide a reproducible example for us to test against? Thanks.

> When gcc is built (in my case I chose brew install gcc --without-multilib) it bootstraps and then (obviously) works.

The from-source installation resolves the issue?

**Comment by veprbl** [comment]
Install bottle:
```
# brew install gcc
==> Downloading https://homebrew.bintray.com/bottles/gcc-5.2.0.el_capitan.bottle.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/gcc-5.2.0.el_capitan.bottle.1.tar.gz
==> Pouring gcc-5.2.0.el_capitan.bottle.1.tar.gz
Warning: This keg was marked linked already, continuing anyway
==> Caveats
GCC has been built with multilib support. Notably, OpenMP may not work:
  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60670
If you need OpenMP support you may want to
  brew reinstall gcc --without-multilib
==> Summary
🍺  /usr/local/Cellar/gcc/5.2.0: 1353 files, 248M
```
GCC not working:
```
# echo "int main(void) {return 0;}" > test.c
# gcc-5 test.c; which gcc-5
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
/usr/local/bin/gcc-5
```
Clang works:
```
# gcc test.c; which gcc
/usr/bin/gcc
```
Now install with ```--build-from-source```:
```
# brew reinstall --build-from-source gcc
==> Reinstalling gcc
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-5.2.0/gcc-5.2.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc-5.2.0.tar.bz2
==> Patching
patching file gcc/jit/Make-lang.in
patching file gcc/jit/jit-playback.c
Hunk #1 succeeded at 2459 with fuzz 2 (offset 43 lines).
==> ../configure --build=x86_64-apple-darwin15.0.0 --prefix=/usr/local/Cellar/gcc/5.2.0 --libdir=/usr/local/Cellar/gcc/5.2.0/lib/gcc/5 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/usr/local/opt/gmp --with-
==> make bootstrap
==> make install
==> Caveats
GCC has been built with multilib support. Notably, OpenMP may not work:
  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60670
If you need OpenMP support you may want to
  brew reinstall gcc --without-multilib
==> Summary
🍺  /usr/local/Cellar/gcc/5.2.0: 1353 files, 248M, built in 27.5 minutes
```
GCC works:
```
# gcc-5 test.C; which gcc-5
/usr/local/bin/gcc-5
```

**Comment by veprbl** [comment]
This looks relevant: NixOS/nixpkgs#9809

**Comment by DomT4** [comment]
Interestingly I can't reproduce with the whole CLT/Xcode stack. The reproducible example produces the expected normal output locally.

Can you `brew config`? Are you running a pure CLT system or Xcode/CLT, etc?

**Comment by veprbl** [comment]
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 33a3bf063a70b52c1a5ba9df8d6c42ef1db994f9
Last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.11-x86_64
Xcode: N/A
CLT: 7.0.0.0.1.1441394355
Clang: 7.0 build 700
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
```
I only use CLT.

**Comment by DomT4** [comment]
Hmm. Interesting. I'll kick my Xcode out of the way locally and see what happens.

**Comment by DomT4** [comment]
Yup, there it is:

```
~> gcc-5 test.c
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
```

Do you by any chance still have the logs from the `gcc` from-source installation? `brew gist-logs gcc` could be useful there.

**Comment by veprbl** [comment]
https://gist.github.com/1b069de70f19ecbdf506

**Comment by DomT4** [comment]
We're going to try rebuilding the bottles here. They were generated against a Beta Xcode at the time I believe and that may have had some kinks left in it. Will check again after #44601 is done and merged.

**Comment by DomT4** [comment]
Seems to be fixed locally by https://github.com/Homebrew/homebrew/commit/2f163eca4dff9bc423ccac465dacbbdaec0e116c. Can you `brew reinstall gcc` from the bottle and see if that fixes the problem for you too? (No obligation if you'd prefer not to).

**Comment by veprbl** [comment]
Fixed it for me too. Thank you very much!

**Comment by DomT4** [comment]
Phew! Thanks for the confirmation & report :smiley_cat:

**Comment by imv-uw** [comment]
I am having this issue as well with g++. I installed today for the first time, so I don't think it's a question of getting the latest bottle. Any help would be appreciated.

I installed the g++ today with `brew install gcc --without-multilib` (for OpenMP support) as suggested at http://stackoverflow.com/questions/29057437/compile-openmp-programs-with-gcc-compiler-on-os-x-yosemite

Compilation of an empty program `int main { return 0; }` fails:
```
imv@fig[~/code/test/]$g++-5 test.cpp
ld: library not found for -lSystem
```

The configuration
```
imv@fig[~/code/test/]$brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 84d78f3ca7b266fb2202ebfab5fc1b67e7153acf
Last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.11.2-x86_64
Xcode: 7.2
CLT: 7.2.0.0.1.1447826929
Clang: 7.0 build 700
MacPorts/Fink: /opt/local/bin/port
X11: 2.7.5 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /opt/local/bin/perl => /opt/local/bin/perl5.12
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
```
XCode and comand line tools were also installed today. I've tried with and without XCode installed. Anyway, I just wanted to get some feedback before opening/reopenning an issue (assuming I have permissions etc).

**Comment by veprbl** [comment]
@imv-uw This issue is about bottled gcc. You seem to have problems with ```--without-multilib``` option that is not provided by bottle. You may want to create other issue or find similar existing one (maybe https://github.com/Homebrew/homebrew/issues/48212 ?)
