### ISSUE TITLE
Brew installer throws error: undefined method `desc' for Formulary::Formulae::Subgit:Class 

### ISSUE THREAD

**Issue by Daij-Djan** [Homebrew/homebrew#44615]
I tried to install subgit via brew:

CGNdpich50729:~ dpich$ brew install homebrew/binary/subgit
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-binary'...
remote: Counting objects: 424, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 424 (delta 0), reused 0 (delta 0), pack-reused 421
Receiving objects: 100% (424/424), 76.74 KiB | 0 bytes/s, done.
Resolving deltas: 100% (235/235), done.
Checking connectivity... done.
Tapped 22 formulae
Error: undefined method `desc' for Formulary::Formulae::Subgit:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-binary/subgit.rb:2:in `<class:Subgit>'
/usr/local/Library/Taps/homebrew/homebrew-binary/subgit.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:177:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:135:in `<main>'
CGNdpich50729:~ dpich$

**Comment by rakkesh** [comment]
It would be of help, if you can share the output of `brew config`.

**Comment by mistydemeo** [comment]
This probably happened because you're running an older version of Homebrew; can you try running `brew update` and see if that fixes it?

**Comment by DomT4** [comment]
Please follow Misty's instruction and see how it goes. I'd be surprised if that doesn't resolve it; It has in every other reported case of this so far. Let us know otherwise and we'll try to help :smiley_cat:
