### ISSUE TITLE
lua package uses wrong module path when using the precompiled binaries

### ISSUE THREAD

**Issue by davidgiven** [Homebrew/homebrew#44619]
It looks like the lua precompiled binaries assume that they're installed in /usr/local --- the module path used by the interpreter looks there for modules, rather than in the actual homebrew installation directory. This is fine if you've installed in /usr/local, but not if you've installed in your home directory (like me).

Reinstalling lua with:

    brew install --build-from-source lua

works fine.

**Comment by asparagui** [comment]
Perhaps you could write a patch that adds a warning about this to the caveats?  Ping @DomT4, but would suggest we close this if there's a documented workaround.

**Comment by davidgiven** [comment]
If the precompiled binaries don't work, wouldn't it be better just to remove them? It's not like Lua doesn't take more than about five seconds to build.

**Comment by DomT4** [comment]
They now only pour if you've installed Homebrew in `/usr/local`. I'll look at a more permanent fix when I get time.

**Comment by davidgiven** [comment]
Awesome --- thanks!
