### ISSUE TITLE
Yap install failed with Brew version 0.9.5 on OSX 10.11

### ISSUE THREAD

**Issue by andrewcropper** [Homebrew/homebrew#44628]
https://gist.github.com/cb4d18112768ac8bfc1b

Terminal output:

==> ./configure --enable-tabling --enable-depth-limit --enable-coroutining --ena
==> make
Last 15 lines from /Users/andrew/Library/Logs/Homebrew/yap/02.make:
./SolverTypes.h:122:20: note:   'Clause_new'
     friend Clause* Clause_new(const V& ps, bool learnt = false) {
                    ^
./Solver.C: In member function 'lbool Solver::search(int, int)':
./Solver.C:602:59: error: 'Clause_new' was not declared in this scope
                 Clause* c = Clause_new(learnt_clause, true);
                                                           ^
./Solver.C:602:59: note: suggested alternative:
In file included from ./Solver.h:29:0,
                 from ./Solver.C:20:
./SolverTypes.h:122:20: note:   'Clause_new'
     friend Clause* Clause_new(const V& ps, bool learnt = false) {
                    ^
make[1]: *** [Solver.o] Error 1
make: *** [all] Error 2

**Comment by asparagui** [comment]
See also #43729, #41558.

**Comment by DomT4** [comment]
Closing in favour of #41558.
