### ISSUE TITLE
Pick required files on GNU/Linux (or whatever) to install them on Mac later?

### ISSUE THREAD

**Issue by andreygursky** [Homebrew/homebrew#44635]
Hi!
It seems, it is possible to use brew on an online Mac to install things on an offline Mac later (https://github.com/Homebrew/homebrew/issues/5220). But what if I have only GNU/Linux (or whatever) PC with internet access but no Mac? Is it possible to get at least a list of links for a formula (with deps) for downloading with e.g. wget and then copy them to some folder on Mac and brew would catch this and go with it? Like a "cross-offline" brew?

**Comment by dunn** [comment]
homebrew-bundle sounds like it would work for you: https://github.com/Homebrew/homebrew-bundle

**Comment by dunn** [comment]
You might be able to `brew fetch` the formulae on Linux with [Linuxbrew](https://github.com/Homebrew/linuxbrew) then move them to the Homebrew cache on your Mac (find where it is with `brew --cache`.

**Comment by tdsmith** [comment]
It's not supported but you can even install Mac Homebrew on Linux (by cloning it somewhere) and use `brew fetch`; I do it on Travis for homebrew-pypi-poet. I think that's the best solution we can offer.

**Comment by andreygursky** [comment]
Thanks for your suggestions!

It sounded too easy to work out-of-the-box. Mac's homebrew on GNU/Linux can be configured to place downloaded data to the custom cache directory by specifying HOMEBREW_CACHE. But I couldn't find a way to configure a MACOS_FULL_VERSION to be "10.9.5" in my case. It's likely, that CPU is also should be overridden. How did you solve this?

The latest homebrew snapshot that could work this way was: 8ef29e6c. But regardless of --force-bottle it downloads only source tarballs, which is not what I want in the first place. After that commit with the next one (beed39e4) there is an explicit error message (and so on):
```bash
$ git checkout beed39e4
$ HOMEBREW_CACHE=/tmp/homebrew bin/brew fetch --force-bottle glib
Error: No such file or directory - /usr/bin/sw_vers

$ git checkout 38efbd49
$ HOMEBREW_CACHE=/tmp/homebrew bin/brew fetch --force-bottle glib
Error: uninitialized constant Formulary::FormulaNamespace03a5a79f716c0b3f807fe24ad591cf4a::Glib::MacOS
Did you mean?  MachO
Please report this bug:
    https://github.com/Homebrew/linuxbrew/wiki/troubleshooting

$ git checkout af199e80
$ HOMEBREW_CACHE=/tmp/homebrew bin/brew fetch --force-bottle glib
Error: uninitialized constant Formulary::FormulaNamespace03a5a79f716c0b3f807fe24ad591cf4a::Glib::MacOS
Please report this bug:
    https://github.com/Homebrew/linuxbrew/wiki/troubleshooting
```

Then I tried linuxbrew. But also I don't see a way to specify MacOS version (and CPU arch) to download prebuilt binaries. How did you succeeded with that? I workarounded this by:
```ruby
diff --git a/Library/Homebrew/os.rb b/Library/Homebrew/os.rb
index b0a993e..083d0f1 100644
--- a/Library/Homebrew/os.rb
+++ b/Library/Homebrew/os.rb
@@ -1,6 +1,6 @@
 module OS
   def self.mac?
-    /darwin/i === RUBY_PLATFORM
+    /linux/i === RUBY_PLATFORM || /linux/i === RbConfig::CONFIG["host_os"]
   end
 
   def self.linux?
diff --git a/Library/Homebrew/os/mac.rb b/Library/Homebrew/os/mac.rb
index aaf8b75..4bb7ec4 100644
--- a/Library/Homebrew/os/mac.rb
+++ b/Library/Homebrew/os/mac.rb
@@ -23,7 +23,7 @@ module OS
     # using the standard Ruby Comparable methods.
     def full_version
       return @full_version ||= Version.new("0") unless OS.mac?
-      @full_version ||= Version.new(`/usr/bin/sw_vers -productVersion`.chomp)
+      @full_version ||= Version.new("10.9.5")
     end
 
     def prerelease?
diff --git a/Library/Homebrew/os/mac/hardware.rb b/Library/Homebrew/os/mac/hardware.rb
index 84308b6..7134448 100644
--- a/Library/Homebrew/os/mac/hardware.rb
+++ b/Library/Homebrew/os/mac/hardware.rb
@@ -17,14 +17,7 @@ module MacCPUs
   # These methods use info spewed out by sysctl.
   # Look in <mach/machine.h> for decoding info.
   def type
-    case sysctl_int("hw.cputype")
-    when 7
       :intel
-    when 18
-      :ppc
-    else
-      :dunno
-    end
   end
 
   def family
```
But maybe I overlooked some adjustable configuration parameters?

It seems the formulae are equal (with additional checks for OS.mac) and replacing "Library/Formula" by one from homebrew is not necessary?

**Comment by mikemcquaid** [comment]
> But maybe I overlooked some adjustable configuration parameters?

You did not, downloading bottles this way is not supported. You could probably just download them yourself as the URL format is pretty standard. Alternatively you might want to consider writing an external command that uses Homebrew's internals to build the URLs for you.
