### ISSUE TITLE
graphviz: HEAD builds --with-bindings fail

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew#44647]
Lines 74-79, some env variables are replaced in `configure`. Unfortunately, `configure` does not exist at the time that is run, stopping the build. I deleted that part to run it, but I'm not sure if that part still is necessary. The bug report seems to say that there was a compiler flag on their side that took care of the python linking...

**Comment by aw1621107** [comment]
There are some automake warnings about missing `subdir-objects` options, but I think that'd be for the graphviz maintainers

**Comment by asparagui** [comment]
Could you try asking over at https://github.com/ellson/graphviz/? We generally don't track these sort of issues until they are part of tagged build.

**Comment by DomT4** [comment]
Fixed as much as I can our side. `HEAD` still fails, but it's an upstream problem that they need to resolve.
