### ISSUE TITLE
After installation terminal and my editor gives an error

### ISSUE THREAD

**Issue by coding102** [Homebrew/homebrew#44648]
After installing the program, every time I run ANY code the following is printed on my editor "Coderunner" followed by the answer. 
bash: /Users/1997SUPRAMAN/.bash_profile: line 14: unexpected EOF while looking for matching `"'
bash: /Users/1997SUPRAMAN/.bash_profile: line 15: syntax error: unexpected end of file

The code is correct as it ran fine before installing. Here is an example, I type my code;

var multi_dim_sum = function(arr){
	var sum=0;
	for (var i=0;i<arr.length;i++){
		if (arr[i] instanceof Array){
			sum += multi_dim_sum(arr[i]);
		}
		else{
			sum+= arr[i];
		}
	}
	return sum;
}
multi_dim_sum([1,[2,[3, 4]], [5, 6]])

"these two lines always print before the answer"
bash: /Users/1997SUPRAMAN/.bash_profile: line 14: unexpected EOF while looking for matching `"'
bash: /Users/1997SUPRAMAN/.bash_profile: line 15: syntax error: unexpected end of file
21

**Comment by DomT4** [comment]
What did you install to get this message?

**Comment by coding102** [comment]
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

**Comment by coding102** [comment]
then I did this:

If you got a warning from Homebrew about your path, do the following:
echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bash_profile
source ~/.bash_profile

**Comment by coding102** [comment]
and installed this; RVM

curl -L https://get.rvm.io | bash -s stable

**Comment by apjanke** [comment]
Could you post your `.bash_profile` as a gist, if there's nothing sensitive in it?

**Comment by DomT4** [comment]
Closing as dead. Will reopen or let another maintainer reopen if we get a reply here.
