### ISSUE TITLE
Promote z3 from homebrew-science

### ISSUE THREAD

**Issue by acfoltzer** [Homebrew/homebrew#44652]
Right now the Z3 SMT solver is only available through [homebrew-science](https://github.com/Homebrew/homebrew-science/blob/master/z3.rb). Other solvers like [CVC4](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cvc4.rb) are available on mainline homebrew, and SMT solvers generally are being used more as dependencies for [other software](http://goto.ucsd.edu/~rjhala/liquid/haskell/blog/about/) and [programming languages](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cryptol.rb). It would be nice to have more than just CVC4 to choose from without tapping homebrew-science.

It looks like this was proposed a couple years ago in #16188 and #21509, but at the time it was more difficult to build and was not available under an open source license. Hopefully there are no longer any blockers to including it in the main repo.

**Comment by DomT4** [comment]
CC @Homebrew/science for thoughts/objections/cake/etc.

**Comment by iml** [comment]
No objections from me.

**Comment by sjackman** [comment]
Fine by me.

**Comment by dpo** [comment]
We have only one dep on `z3` in `science`, so I guess it's ok.

**Comment by DomT4** [comment]
@Homebrew/owners Any objections on moving `z3` *to* the Core?

**Comment by dunn** [comment]
:ok_woman:

**Comment by dunn** [comment]
That's "OK (good)", not "I have objection".

**Comment by bfontaine** [comment]
:ok_hand:

**Comment by DomT4** [comment]
@acfoltzer Go ahead and file PRs in Science to remove & here at Homebrew/homebrew to add :)
