### ISSUE TITLE
Unable to run : brew install brew-cask

### ISSUE THREAD

**Issue by daniel-simgo** [Homebrew/homebrew#44659]
I run El Capitan
I update the brew to the latest version.
I also run brew upgrade.
I made a small patch for myself to run "Current" ruby version and not the "1.8"
When I try to run "brew install brew-cask" I got error : Error: 
"uninitialized constant Requirement"
/usr/local/Library/Formula/brew-cask.rb:10:in `<main>'

**Comment by jiegec** [comment]
Isn't brew-cask in the tap caskroom/homebrew-cask?

**Comment by daniel-simgo** [comment]
yes..

and I already tapped it..
I need it to be able to build Arduino : https://github.com/arduino/Arduino/wiki/Building-Arduino

**Comment by jiegec** [comment]
Then brew-cask.rb should be in /usr/local/Library/Taps/caskroom/homebrew-cask/.

**Comment by jiegec** [comment]
Try: 
cd /usr/local/
git status

**Comment by jiegec** [comment]
Also, you can directly `brew cask install arduino` then.

**Comment by DomT4** [comment]
> I made a small patch for myself to run "Current" ruby version and not the "1.8"

On El Cap your Ruby shouldn't be 1.8 and I'd really quite strongly advise not hacking around with any Homebrew core code too much. `Current` on El Cap should point at:
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0
```

**Comment by DomT4** [comment]
Any remaining issues on this?

**Comment by DomT4** [comment]
Closing as resolved.
