### ISSUE TITLE
Enable debugging of cmake C++ library installed via homebrew

### ISSUE THREAD

**Issue by ahundt** [Homebrew/homebrew#44654]
Say I have an application "A" built with CMake that depends on another library "L" that was also built with CMake via homebrew with debug symbols. 

Is there a way to configure homebrew such that if I build "A" with cmake and the Xcode generator, I can use Xcode to debug the application and step into both the `.h` and `.cpp` files in library "L"?

Perhaps this may not be possible at the moment in part due to homebrew deleting everything in the temp folders used to build?

Thanks a lot for considering my slightly obscure question!

**Comment by asparagui** [comment]
You might consider asking the library's author about this.  We can ping @mistydemeo, but would suggest we close this (we're not that good at Xcode support and need to reserve the tracker for bugs).

**Comment by ahundt** [comment]
I guess my real question is if there is any flag I can set so homebrew doesn't delete the build directory, or places it in a directory I specify? 

This issue is homebrew specific because I know how to install packages manually, but then I need to do the same for all packages that depend on that one once one is installed manually because then it is outside the homebrew system.

**Comment by DomT4** [comment]
#42053 may well have achieved something like this but it didn't come to fruition because it required too much heavy dancing at the time. There's currently no flag to automatically retain the build directory.

**Comment by ahundt** [comment]
@DomT4 thanks for the heads up, I think that would solve my problem perfectly if it were revived.

**Comment by ahundt** [comment]
Unless there are any other ideas, seems like I may have to drop homebrew for these purposes considering the status of #42053, and perhaps switch to something like the [cmake hunter repository]( https://github.com/ruslo/hunter) too bad I put all that work into getting a homebrew build working for my project...

Thanks a lot for the heads up.

**Comment by DomT4** [comment]
No additional plans at this point. We welcome reasonable solutions and pull requests to resolve these sorts of queries, if anyone stumbles across this issue in future and gets curious. Sorry we can't help more here at this point in time.
