### ISSUE TITLE
Typesafe Activator

### ISSUE THREAD

**Issue by cokleisli** [Homebrew/homebrew#44668]
Hi,

I'm not sure why I cannot brew typesafe-activator seamlessly. I have managed to brew scala, mongodb and sbt without any problems but when trying to brew typesafe-activator, I get the following:

kleisli:~ me$ brew install typesafe-activator
==> Downloading https://downloads.typesafe.com/typesafe-activator/1.3.6/typesafe-ac
Already downloaded: /Library/Caches/Homebrew/typesafe-activator-1.3.6.zip
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/activator
/usr/local/bin is not writable.

You can try again using:
  brew link typesafe-activator
==> Summary
🍺  /usr/local/Cellar/typesafe-activator/1.3.6: 4 files, 1.2M, built in 2 seconds
kleisli:~ me$ brew link typesafe-activator
Linking /usr/local/Cellar/typesafe-activator/1.3.6... 
Error: Could not symlink bin/activator
/usr/local/bin is not writable.
kleisli:~ me$ 

It's clear that it doesn't have permissions to write the sym link but I'm wondering why the other brews didn't fail if brew does not have permission to write to that directory.

Regards,
Iftikhar

**Comment by DomT4** [comment]
> /usr/local/bin is not writable.

`sudo chown -R $(whoami):admin /usr/local` will likely sort this.

**Comment by cokleisli** [comment]
Thanks. Not sure what messed around with my permissions in between brews.

**Comment by DomT4** [comment]
All working again? :)

**Comment by DomT4** [comment]
Presuming the answer is yes. Let us know if you have any further issues :smiley:
