### ISSUE TITLE
brew search invalid attribute: version

### ISSUE THREAD

**Issue by JetForMe** [Homebrew/homebrew#44687]
When I try to brew-search, I get an error. I've updated twice, just in case, but no change.

	$ brew search llvm
	Error: invalid attribute: version (nil)
	Please report this bug:
		https://git.io/brew-troubleshooting
	/usr/local/Library/Homebrew/formula.rb:195:in `validate_attributes!'
	/usr/local/Library/Homebrew/formula.rb:153:in `initialize'
	/usr/local/Library/Homebrew/formulary.rb:70:in `new'
	/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
	/usr/local/Library/Homebrew/formulary.rb:205:in `factory'
	/usr/local/Library/Homebrew/cmd/search.rb:144:in `block in search_formulae'
	/usr/local/Library/Homebrew/cmd/search.rb:143:in `map'
	/usr/local/Library/Homebrew/cmd/search.rb:143:in `search_formulae'
	/usr/local/Library/Homebrew/cmd/search.rb:44:in `search'
	/usr/local/Library/brew.rb:133:in `<main>'

**Comment by DomT4** [comment]
Can you `cd $(brew --prefix) && git status`? If updating isn't solving the problem it's possible there's some local modification somewhere. A `brew config` & `brew doctor` might be useful as well, if you can run those commands.

**Comment by JetForMe** [comment]
$ cd $(brew --prefix)
	rmann@EclipseSSD: local/ (master) 21:05$ git status
	On branch master
	Changes not staged for commit:
	  (use "git add <file>..." to update what will be committed)
	  (use "git checkout -- <file>..." to discard changes in working directory)

		modified:   Library/Formula/dtc.rb

	Untracked files:
	  (use "git add <file>..." to include in what will be committed)

		Library/Formula/arm-llvm.rb
		Library/Formula/xively.rb

**Comment by DomT4** [comment]
Can you `cat Library/Formula/arm-llvm.rb`? I'm guessing something's awry with that formula.

**Comment by JetForMe** [comment]
That's been like that for a long time, and brew has been good. But here it is:

	local/ (master) 21:27$ cat Library/Formula/arm-llvm.rb
	require "formula"

	# Documentation: https://github.com/Homebrew/homebrew/wiki/Formula-Cookbook
	#                /usr/local/Library/Contributions/example-formula.rb
	# PLEASE REMOVE ALL GENERATED COMMENTS BEFORE SUBMITTING YOUR PULL REQUEST!

	class ArmLlvm < Formula
	  homepage ""
	  url "http://llvm.org/svn/llvm-project/llvm/trunk"
	  sha1 ""

	  # depends_on "cmake" => :build
	  depends_on :x11 # if your formula requires any X11/XQuartz components

	  def install
		# ENV.deparallelize  # if your formula fails when building in parallel

		# Remove unrecognized options if warned by configure
		system "./configure", "--disable-debug",
							  "--disable-dependency-tracking",
							  "--disable-silent-rules",
							  "--prefix=#{prefix}"
		# system "cmake", ".", *std_cmake_args
		system "make", "install" # if this fails, try separate make/make install steps
	  end

	  test do
		# `test do` will create, run in and delete a temporary directory.
		#
		# This test will fail and we won't accept that! It's enough to just replace
		# "false" with the main program this formula installs, but it'd be nice if you
		# were more thorough. Run the test with `brew test arm-llvm`.
		#
		# The installed folder is not in the path, so use the entire path to any
		# executables being tested: `system "#{bin}/program", "do", "something"`.
		system "false"
	  end
	end

**Comment by DomT4** [comment]
You likely wouldn't have stumbled across the failure unless you've done `brew search llvm` before now. `trunk` might be the issue there, since that's what we'll be detecting the version as. Easiest way to check:

```bash
mv Library/Formula/arm-llvm.rb ~/Downloads && brew search llvm
```

**Comment by JetForMe** [comment]
Excellent point. That was the problem.

Perhaps the system could catch those errors, though, and continue the search? THanks.
