### ISSUE TITLE
Briss fork

### ISSUE THREAD

**Issue by ylluminate** [Homebrew/homebrew#44686]
The Briss fork over here is a bit more up-to-date and resolves some problems in the unmtaintained original Briss source: 
https://github.com/danmbox/briss2

The maven build seems to work fine, but I'm not a java-junkie so I'm not yet sure how to properly roll it for Homebrew.

**Comment by DomT4** [comment]
For reasons of not surprising users with a sudden upgrade to an unofficial fork, we don't accept replacing an older formula with a new fork. The new fork would have to be "blessed" by upstream for that to happen. In certain circumstances we accept forks that are explicitly identified as a fork, such as `danmbox-briss2` or such.

The fork doesn't currently meet Homebrew's minimum popularity requirements which we enforce to ensure a formula will stay maintained and not rapidly become unsupported and problematic. You may wish to [host it in your own tap](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md) until such a time when it does meet those requirements which are >10 forks, >10 watchers and >20 stars. We also require a stable tagged release, and upstream only provide two release candidates at this time.

Looking at the upstream README a basic formula would look something like:

```ruby
class Briss2 < Formula
  desc "Fork of the original Briss project"
  url "https://github.com/danmbox/briss2/archive/briss2-1.0-rc.2.tar.gz"
  sha256 "inserthere"

  depends_on :java => "1.6+"
  depends_on "maven" => :build

  def install
    system "mvn", "package", "assembly:single"
    system "unzip", "target/therightzipfile.zip"
    libexec.install "target/unzipped/therightjar.jar"
    bin.write_jar_script libexec/"therightjar.jar", "briss"
  end
end
```
