### ISSUE TITLE
Installing --without-multilib and no OpenMP support

### ISSUE THREAD

**Issue by pcorvo83** [Homebrew/homebrew#44729]
Hello,

Apologies in advance as I'm not very experienced with installing the compiler and if I'm posting in the wrong place. I've gone through all the steps to install gcc through brew with -without-multilib, but when I check the info of the gcc compiler it still says it's been installed with multilib and that OpenMP support might not work.

Essentially this is what I've done:

brew reinstall gcc --without-multilib

and then:

brew info gcc

shows this:

gcc: stable 5.2.0 (bottled)
GNU compiler collection
https://gcc.gnu.org
/usr/local/Cellar/gcc/5.2.0 (1285 files, 215M) *
  Built from source with: --without-multilib
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gcc.rb
==> Dependencies
Required: gmp ✔, libmpc ✔, mpfr ✔, isl ✔
==> Options
--with-all-languages
	Enable all compilers and languages, except Ada
--with-java
	Build the gcj compiler
--with-jit
	Build the jit compiler
--with-nls
	Build with native language support (localization)
--without-fortran
	Build without the gfortran compiler
--without-multilib
	Build without multilib support
==> Caveats
GCC has been built with multilib support. Notably, OpenMP may not work:
  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60670
If you need OpenMP support you may want to
  brew reinstall gcc --without-multilib

As some background, I'm on Mac OS Mavericks and have an application that I want to build that uses OpenMP and currently stumbles as it can't find <omp.h> (I'm building with gcc and -fopenmp is specified as flag). Since apparently Clang that ships with Xcode doesn't support it I decided to install gcc from reading some SO posts.

I'm not quite sure this is my problem but not sure why it says that it has been built with multilib support when I specifically installed it with the --without-multilib parameter.

Any help would be greatly appreciated.

Thank you,
Pedro

**Comment by DomT4** [comment]
It looks like the conditional caveat isn't working, rather than it not obeying your build option request. It's something we'll look at, but you should have a `gcc` build without `multilib`.

**Comment by pcorvo83** [comment]
Thank you for your reply, is there an alternative way to do that?

**Comment by veprbl** [comment]
I've just tested ```brew reinstall gcc --without-multilib``` on El Captain and basic OpenMP tests work for both gcc-5 and gfortran.

As for Caveats message, it's broken and you should just ignore it as long as you specified the ```--without-multilib``` option.

**Comment by ChasTheSpaz** [comment]
Same problem with "brew reinstall gcc --without-multilib" for downloading DeviL (Haskell stuff). 1st it says I need a new version of gcc to compile DeviL, then it insists downloading with --without-multilib, then waiting the 150 minutes to compile the wreck still doesn't allow DeviL to build, with or without --without-multilib. I'm running OSX Mavericks and ready to tear my hair out:

Charless-MacBook-Pro:~ $ brew install devil
Error: devil cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
Charless-MacBook-Pro:~ $ brew install gcc
==> Installing dependencies for gcc: gmp, mpfr, libmpc, isl
==> Installing gcc dependency: gmp
==> Downloading https://homebrew.bintray.com/bottles/gmp-6.1.0.mavericks.bottle.
######################################################################## 100.0%
==> Pouring gmp-6.1.0.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/gmp/6.1.0: 15 files, 3.2M
==> Installing gcc dependency: mpfr
==> Downloading https://homebrew.bintray.com/bottles/mpfr-3.1.3.mavericks.bottle
######################################################################## 100.0%
==> Pouring mpfr-3.1.3.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/mpfr/3.1.3: 24 files, 3.6M
==> Installing gcc dependency: libmpc
==> Downloading https://homebrew.bintray.com/bottles/libmpc-1.0.3.mavericks.bott
######################################################################## 100.0%
==> Pouring libmpc-1.0.3.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/libmpc/1.0.3: 10 files, 380K
==> Installing gcc dependency: isl
==> Downloading https://homebrew.bintray.com/bottles/isl-0.14.1.mavericks.bottle
######################################################################## 100.0%
==> Pouring isl-0.14.1.mavericks.bottle.3.tar.gz
🍺  /usr/local/Cellar/isl/0.14.1: 68 files, 3.4M
==> Installing gcc
==> Downloading https://homebrew.bintray.com/bottles/gcc-5.2.0.mavericks.bottle.
######################################################################## 100.0%
==> Pouring gcc-5.2.0.mavericks.bottle.3.tar.gz
==> Caveats
GCC has been built with multilib support. Notably, OpenMP may not work:
  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60670
If you need OpenMP support you may want to
  brew reinstall gcc --without-multilib
==> Summary
🍺  /usr/local/Cellar/gcc/5.2.0: 1353 files, 248M
Charless-MacBook-Pro:~ $ brew install devil
Error: devil cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
Charless-MacBook-Pro:~ $ brew reinstall gcc --without-multilib
==> Reinstalling gcc with --without-multilib
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-5.2.0/gcc-5.2.0.tar.bz2
==> Downloading from http://mirror.lagoon.nc/pub/gnu/gcc/gcc-5.2.0/gcc-5.2.0.tar
                                                                           0.2%^C
Charless-MacBook-Pro:~ $ brew reinstall gcc --without-multilib
==> Reinstalling gcc with --without-multilib
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-5.2.0/gcc-5.2.0.tar.bz2
==> Downloading from http://mirror.lagoon.nc/pub/gnu/gcc/gcc-5.2.0/gcc-5.2.0.tar.
############################################                              61.1%
curl: (18) transfer closed with 37025141 bytes remaining to read
Trying a mirror...
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-5.2.0/gcc-5.2.0.tar.bz2
######################################################################## 100.0%
==> Patching
patching file gcc/jit/Make-lang.in
patching file gcc/jit/jit-playback.c
Hunk #1 succeeded at 2459 with fuzz 2 (offset 43 lines).
==> ../configure --build=x86_64-apple-darwin13.4.0 --prefix=/usr/local/Cellar/gcc
==> make bootstrap
==> make install
==> Caveats
GCC has been built with multilib support. Notably, OpenMP may not work:
  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60670
If you need OpenMP support you may want to
  brew reinstall gcc --without-multilib
==> Summary
🍺  /usr/local/Cellar/gcc/5.2.0: 1285 files, 215M, built in 153.7 minutes
Charless-MacBook-Pro:~ $ brew install devil
Error: devil cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
Charless-MacBook-Pro:~ $ brew reinstall gcc --without-multilib
==> Reinstalling gcc with --without-multilib
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-5.2.0/gcc-5.2.0.tar.bz2
Already downloaded: /Users/charlesschatz/Library/Caches/Homebrew/gcc-5.2.0.tar.bz2
==> Patching
patching file gcc/jit/Make-lang.in
patching file gcc/jit/jit-playback.c
Hunk #1 succeeded at 2459 with fuzz 2 (offset 43 lines).
==> ../configure --build=x86_64-apple-darwin13.4.0 --prefix=/usr/local/Cellar/gcc
==> make bootstrap

**Comment by veprbl** [comment]
@ChasTheSpaz have you seen https://github.com/Homebrew/homebrew/issues/40442 ?

**Comment by ChasTheSpaz** [comment]
Attempting to followup your suggestion, may have to do it tomorrow - my
web connection is extremely dodgy today. Updating brew's local database
is failing, will try brewing gcc49 eventually. 

Cheers, Charles 

On 2015-12-01 12:59, Dmitry Kalinkin wrote: 

> @ChasTheSpaz [1] have you seen #40442 [2] ? 
> 
> --
> Reply to this email directly or view it on GitHub [3].

 

Links:
------
[1] https://github.com/ChasTheSpaz
[2] https://github.com/Homebrew/homebrew/issues/40442
[3]
https://github.com/Homebrew/homebrew/issues/44729#issuecomment-160802786
