### ISSUE TITLE
libmongoclient install error

### ISSUE THREAD

**Issue by freddy311082** [Homebrew/homebrew#44724]
guys, libmongoclient's formula is not updated... look at this issue

brew install libmongoclient -c++111
==> Downloading https://github.com/mongodb/mongo-cxx-driver/archive/legacy-0.0-26compat-2.6.9.tar.gz
Already downloaded: /Library/Caches/Homebrew/libmongoclient-2.6.9.tar.gz
==> /usr/local/opt/scons/bin/scons --prefix=/usr/local/Cellar/libmongoclient/2.6.9 -j8 --cc=/usr/bin/clang --cxx=/usr/bin/clang++ --extrapath=/usr/local/opt/boost --full --use-system-all --sharedclient --osx-version-min=10.11 --libc++
Last 15 lines from /Users/freddy/Library/Logs/Homebrew/libmongoclient/01.scons:
-j8
--cc=/usr/bin/clang
--cxx=/usr/bin/clang++
--extrapath=/usr/local/opt/boost
--full
--use-system-all
--sharedclient
--osx-version-min=10.11
--libc++

scons: Reading SConscript files ...
Mkdir(".scons/Darwin/nohost")
usage: scons [OPTION] [TARGET] ...

SCons Error: option --osx-version-min: invalid choice: '10.11' (choose from '10.6', '10.7', '10.8', '10.9', '10.10')

READ THIS: https://git.io/brew-troubleshooting

regards

**Comment by apjanke** [comment]
Yeah, the most recent "compat" release seems to be https://github.com/mongodb/mongo-cxx-driver/releases/tag/legacy-0.0-26compat-2.6.11, from Aug 14 2015. Maybe this includes OS X 10.11 support?

Someone who is familiar with the complexity of mongodb driver versioning should pick this up; it's not straightforward.

See #40955; #40837.
