### ISSUE TITLE
US-ASCII errors on brew doctor

### ISSUE THREAD

**Issue by lemsx1** [Homebrew/homebrew#44744]
Looks like the problem is when using the system's ruby for `brew doctor`

```
$> brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: b33f04a1d034e0258352dbd8ad3d53783b7f4585
Last commit: 16 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.11-x86_64
Xcode: 7.0.1
CLT: 7.0.0.0.1.1441394355
Clang: 7.0 build 700
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.3/bin/ruby
Java: 1.8.0_60
```
```
$> brew doctor
Error: invalid byte sequence in US-ASCII
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:45:in `=~'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:45:in `chop_basename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:341:in `plus'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:334:in `+'
/usr/local/Library/Homebrew/extend/pathname.rb:315:in `resolved_path_exists?'
/usr/local/Library/Homebrew/cmd/doctor.rb:231:in `block (2 levels) in check_for_broken_symlinks'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:546:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:546:in `find'
/usr/local/Library/Homebrew/cmd/doctor.rb:230:in `block in check_for_broken_symlinks'
/usr/local/Library/Homebrew/cmd/doctor.rb:228:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:228:in `check_for_broken_symlinks'
/usr/local/Library/Homebrew/cmd/doctor.rb:1287:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1285:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1285:in `doctor'
/usr/local/Library/brew.rb:133:in `<main>'
```

**Comment by DomT4** [comment]
What are your `LANG=` and `LC_ALL=` variables set as?

**Comment by nohillside** [comment]
Same problem here, with `LANG=C` and `LC_ALL` unset

**Comment by DomT4** [comment]
Try `export LC_ALL=en_US.UTF-8` and then run the command again. I've been meaning to enforce UTF-8 for `brew doctor` for a while, so if that works I may use this as motivation :smile:.

**Comment by lemsx1** [comment]
confirmed that it works after setting en_US.UTF-8 for all.
That explains why it works for me everywhere since this is my default on all my computers. This was a new computer I just setup.

```
$> export LC_ALL=en_US.UTF-8
$> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Broken symlinks were found. Remove them with `brew prune`:
...
```

**Comment by apjanke** [comment]
This looks like the same thing as #41632.

**Comment by DomT4** [comment]
Yes. I was kind of hoping leaving this one open and nearer the top of the issues list motivates me to fix this sooner, and that idea worked nicely until I couldn't reproduce this failure at all on Mavericks, Yosemite or El Cap even when I reset the `LC_ALL` back to the default encoding known to cause this problem. Trying to work out why it won't die for me.

**Comment by apjanke** [comment]
It may be configuration-specific: if you have `LC_ALL=C` set, the error still only gets triggered if it encounters characters outside the 7-bit ASCII range in some situations. For me, it only reproduces if I have non-ASCII text in the *target* filename of a symlink in one of the locations that `brew doctor` scans.

Try this. It reproduces the error for me on Mavericks.

```
ln -s /some/bogus/path/lib惷惼誃.6.a /usr/local/lib/libbogus.6.a
LC_ALL=C brew doctor
```

**Comment by DomT4** [comment]
Thanks. I'll check that specific example out.

**Comment by DomT4** [comment]
Nice. That did the trick. Now to just test the potential fixes and do some benchmarking :smile_cat:

**Comment by jyyen** [comment]
setting LC_ALL to en_US.UTF-8 solved the problem! I was toggling the setting on and off but with LC_ALL=C. Seems like need a specific text encoding?

**Comment by apjanke** [comment]
Yes. It needs to be a Unicode encoding, because the filesystem and other OS bits, and Homebrew, use Unicode character data. And I think that it has to be specifically `UTF-8`. (It's possible that the relevant APIs will check `locale` and do re-encoding, but I don't think so.) And most of the text files you're working with in a modern system will be UTF-8, so that's probably what you need at an application level. Unless you have specifically set your system up to run a different default encoding, you probably need a UTF-8 locale.

**Comment by jyyen** [comment]
thanks!

**Comment by mikemcquaid** [comment]
We should consider making this the first test `doctor` runs?
