### ISSUE TITLE
manpage formatting with finer-grained markup

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#44769]
Hi, Homebrew folks.

I took a stab at [reformatting the `brew` manpage](https://github.com/apjanke/homebrew/tree/manpage-formatting) with finer-grained markup to make the syntax more clear, better distinguishing placeholders and syntax structure indicators. E.g. using the ronn <...> markup for "variables", leaving the [ ] | ( ) elements un-marked-up, and making sure all literal text was marked up with \`...\`.

Before:

```
`brew` --version<br>
`brew` command [--verbose|-v] [options] [formula] ...
```

After:

```
`brew` `--version`<br>
`brew` <command> [`--verbose`|`-v`] [<options>] [<formula>] ...
```

This ends up with a nicer-looking and more readable man page output, I think.

Before:
<img width="467" alt="screen shot 2015-10-09 at 3 06 54 am" src="https://cloud.githubusercontent.com/assets/2618447/10387860/e7f7613c-6e32-11e5-977a-f3d0a183af38.png">
After:
<img width="521" alt="screen shot 2015-10-09 at 3 06 06 am" src="https://cloud.githubusercontent.com/assets/2618447/10387857/e19a9822-6e32-11e5-989e-81791e8fb2e9.png">
Before:
<img width="502" alt="screen shot 2015-10-09 at 3 07 13 am" src="https://cloud.githubusercontent.com/assets/2618447/10387864/e9c954b6-6e32-11e5-85af-47d3b14b807b.png">
After:
<img width="499" alt="screen shot 2015-10-09 at 3 06 44 am" src="https://cloud.githubusercontent.com/assets/2618447/10387858/e4e95a4a-6e32-11e5-92f8-dfd1cec63b2c.png">

But the web page looks worse. The italic proportional and roman monospace don't flow well together.

Before:
<img width="477" alt="screen shot 2015-10-09 at 3 10 52 am" src="https://cloud.githubusercontent.com/assets/2618447/10387938/8e2af974-6e33-11e5-9a36-d9731a08f700.png">
After:
<img width="496" alt="screen shot 2015-10-09 at 3 10 59 am" src="https://cloud.githubusercontent.com/assets/2618447/10387941/93f0c1f4-6e33-11e5-9d29-b8cd889dfbf1.png">
<img width="916" alt="screen shot 2015-10-09 at 3 11 21 am" src="https://cloud.githubusercontent.com/assets/2618447/10387942/952e6a58-6e33-11e5-87f7-d70af5dbea3e.png">

Ronn doesn't seem to have a way of indicating a span of "code" that should be set in monospace in the web page output that can also contain bold and underline/italic characters to differentiate literal text and placeholders. Like this, where the italicization of "func" is "nested" inside monospacing to indicate replaceable code.

<img width="454" alt="screen shot 2015-10-09 at 5 39 27 am" src="https://cloud.githubusercontent.com/assets/2618447/10390694/41d66eea-6e48-11e5-97bc-1bb422eee3c1.png">

Not an issue with the man page output, since everything is monospaced there.

Thoughts on this? Would it be worth reformatting to get better markup in the man page, and let the web version be a bit uglier, since it's a secondary target? Or should we stick with marking up all the code with \`...\` and using internal `<...>` that the users should read as placeholder indicators, instead of being turned in to underlines?

**Comment by bfontaine** [comment]
I’m fine with this change.

**Comment by UniqMartin** [comment]
I'm generally in favor of this change. Personally, I would prefer if the PR only contained the formatting changes and all content changes (even minor ones) would be separated into a different PR. Too many of these unrelated changes have sneaked in …

Regarding the HTML output, I guess we can with a slightly degraded formatting. But isn't there a way to improve this? I'm sure `ronn` offers some means to adapt the styling. What are other projects doing?

**Comment by apjanke** [comment]
I can break up the formatting and content changes in to separate commits; sounds reasonable to keep those separate.

> I'm sure ronn offers some means to adapt the styling. What are other projects doing?

Not that I can see, at least not an easy one. I took a look at ronn when I was doing this. It doesn't seem to have mechanisms to make a nicer web page. In particular, it doesn't have a way to combine "code" or "monospace" with italicization. As a variant of roff, ronn is targeted pretty specifically at man pages, and seems to assume a monospace font throughout, with web output as an afterthought. And given that orientation, and that I'd guess more Homebrew users are using `man brew` than the web page view, I think it makes sense to favor nicer man pages at the expense of the web view.

I've seen some other projects using asciidoc or POD or other markup formats that are built for multiple targets from the start and less man-focused. (None of them I've seen have excellent web output, though, IMHO. Their monospaced code doesn't flow well with the proportional-font text, and in some cases is really garish, combining monospace + larger font + different color text + a highlighted background.) I'm still just learning this space, so there's sure to be other options I don't know about.

**Comment by mikemcquaid** [comment]
> I'm generally in favor of this change. Personally, I would prefer if the PR only contained the formatting changes and all content changes (even minor ones) would be separated into a different PR. Too many of these unrelated changes have sneaked in …

Agreed, that'd be good.

I don't think the HTML is much worse here. This does seem like it's probably fixable in `ronn` itself relatively easily? I'm also open to us using another manpage generator if it's relatively easy to install.

**Comment by UniqMartin** [comment]
@apjanke Thanks for looking into this and for the detailed response! I fully agree that `man brew` has priority over the HTML version and we can always tweak the HTML version later. My hope was that there's an easy and obvious way to produce something like [ronn.1](http://rtomayko.github.io/ronn/ronn.1) which looks quite nice to me.

**Comment by apjanke** [comment]
> This does seem like it's probably fixable in ronn itself relatively easily?

Heck if I can figure out how to do it. The "right" formatting would be italicized monospace for the placeholders in code samples, but I can't see a way in ronn to make that happen or to nest the tags.

That ronn.1 web page fixes it by using monospace font for the entire page, like a man page viewed in a terminal. The code samples look nice and have the right formatting, and we could make that happen. But if you're going to sit down and read the whole thing or large sections of it, proportional font makes it more readable. I think it would be better to stick with that and have the code samples a little ugly than vice versa.

> I'm also open to us using another manpage generator if it's relatively easy to install.

`brew install asciidoc` or `gem install asciidoctor`. :)

**Comment by mikemcquaid** [comment]
> > I'm also open to us using another manpage generator if it's relatively easy to install.
>
> brew install asciidoc or gem install asciidoctor. :)

That would be fine with me if you wanted to spike out a replacement.

**Comment by apjanke** [comment]
Okay, I've backed out the content changes so now it's just formatting changes.

Look good to commit?

> That would be fine with me if you wanted to spike out a replacement.

Think I'll give this a shot. I'll take another look around for alternate Markdown converters first, too, which might require less of a change to our code.

**Comment by mikemcquaid** [comment]
@apjanke :+1:

**Comment by UniqMartin** [comment]
:+1:
