### ISSUE TITLE
Error: undefined method `desc' for Formulary::Formulae::Hdf5:Class

### ISSUE THREAD

**Issue by can16358p** [Homebrew/homebrew#44780]
I am trying to install hdf5 and I'm getting this error:

$ brew install hdf5
Error: undefined method `desc' for Formulary::Formulae::Hdf5:Class
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-science/hdf5.rb:2:in `<class:Hdf5>'
/usr/local/Library/Taps/homebrew/homebrew-science/hdf5.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:46:in `install'
/usr/local/Library/brew.rb:135:in `<main>'

I'm reporting it here because it says please report this bug. I am new to homebrew and I'm trying to install hdf5 so I'd be glad if there's a workaround.

**Comment by xu-cheng** [comment]
You are running an outdated Homebrew. Please run `brew update`.
