### ISSUE TITLE
ansible needs apache-libcloud

### ISSUE THREAD

**Issue by rmarsagoogle** [Homebrew/homebrew#44793]
The ansible gce module needs apache-libcloud to be installed.  Please add the following to the ansible.rb formula:

    diff --git a/Library/Formula/ansible.rb b/Library/Formula/ansible.rb
    index fbe7b8e..c37c077 100644
    --- a/Library/Formula/ansible.rb
    +++ b/Library/Formula/ansible.rb
    @@ -24,6 +24,11 @@ class Ansible < Formula
         url "https://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.8.tar.gz"
         sha256 "bc1ff2ff88dbfacefde4ddde471d1417d3b304e8df103a7a9437d47269201bf4"
       end
    +       
    +  resource "apache-libcloud" do
    +    url "https://pypi.python.org/packages/source/a/apache-libcloud/apache-libcloud-0.18.0.tar.bz2"
    +    sha256 "af87e9ccd5577f7a7cf8b0f642889c40738561eb7ab2f23039c0d3d648b80d2a"
    +  end
     
       resource "MarkupSafe" do
         url "https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.23.tar.gz"

**Comment by DomT4** [comment]
We'd welcome a Pull Request to add the resource. There's documentation on opening a PR [here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md) if that's useful to you.
