### ISSUE TITLE
Bottle of nkf for El Capitan is not found

### ISSUE THREAD

**Issue by 87carats** [Homebrew/homebrew#44812]
On OS X El Capitan 10.11, `brew install nkf` told me:

    curl: (22) The requested URL returned error: 404 Not Found
    Error: Failed to download resource "nkf"
    Download failed: https://homebrew.bintray.com/bottles/nkf-2.1.3.el_capitan.bottle.tar.gz
    Warning: Bottle installation failed: building from source.

Bottles of `nkf` for older OS X are exist.

Installation itself succeeded from http://dl.osdn.jp/nkf/59912/nkf-2.1.3.tar.gz.

**Comment by DomT4** [comment]
Removed for now.
