### ISSUE TITLE
Don't install node as a dependency if a node version manager is present

### ISSUE THREAD

**Issue by jarrodldavis** [Homebrew/homebrew#44819]
This isn't a huge deal, but it would be nice if Homebrew recognized that a node version manager (like `nvm` or `n`) is an acceptable stand in for a `node` dependency. This way, Homebrew wouldn't needlessly install a separate version outside of that version manager – perhaps it could show a caveat about making sure some sort of "default" version of node is installed using that manager

**Comment by dunn** [comment]
We could consider adding `depends_on :node`, like we do for python and emacs and others: https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/requirements/emacs_requirement.rb

**Comment by DomT4** [comment]
I don't really want to, to be honest. We considered this before, I even submitted a PR to get it done, and we basically decided it would create too many issues.

**Comment by dunn** [comment]
Oh, I vaguely remember that.

**Comment by DomT4** [comment]
I'm going to pass on this for now. I'm not saying never ever, but I place enormous value on the fact the `brew`/`node` ecosystem is healthy these days and we're not seeing issues upstream about us every week. The current set up is easier on us in terms of maintenance, but also easier on upstream.

Not saying no forever here, just at the moment. Having used `nvm` myself for a few months to balance between `node` and `iojs` when the latter still existed under that name I know it's a bit frustrating to install a Homebrew node on top of that but there are less potential failure points in the current system. It's something we'll consider going forwards though.
