### ISSUE TITLE
Home-brew install gcj via gcc

### ISSUE THREAD

**Issue by zeka0** [Homebrew/homebrew#44825]
I found that when I used howe-brew to install gcc, it doesn't install the gcj with it.
In gnu gcc it should come with a "--enable-language=java, c, c++" things like that.
I am using Mac OS X el captain now, and it's a pain for me to build gcc using brew: it took me 76 minutes with my mac book pro... Any way I wonder if there is a way to install gcc using home-brew to install gcj?

**Comment by mistydemeo** [comment]
gcj is off by default, but you can install it by doing `brew install gcc --with-java`. This will build it from source, so it'll take a long time for it to build - probably another 80 minutes like it took for you before.
