### ISSUE TITLE
imagemagick 6.9.2-3 404

### ISSUE THREAD

**Issue by mgk** [Homebrew/homebrew#44832]
It looks like this release was pulled from the imagemagick site and the mirror as both are 404

```
http://www.imagemagick.org/download/releases/ImageMagick-6.9.2-3.tar.xz  -> 404
```

The latest from imagemagick.org appears to be:

```
http://www.imagemagick.org/download/releases/ImageMagick-6.9.2-4.tar.xz
```

**Comment by DomT4** [comment]
Fancy submitting a PR to update it? There's documentation on that [here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md) if that's useful.

**Comment by mgk** [comment]
Glad to.
