### ISSUE TITLE
Unable to read file.

### ISSUE THREAD

**Issue by BE3101** [Homebrew/homebrew#44860]
I installed qt via homebrew on Mac Os 10.9.5. The installation went fine, but when I try to use qmake I keep getting an error.

localhost:MagRead afuaxh1$ ls
COPYING			debian			magread.pro
ChangeLog		llist.c			magread.svg
README			llist.h			main.cpp
aamvacard.cpp		maemofiles		mslib.c
aamvacard.h		magcard.h		mslib.h
accountcard.cpp		magdecode.cpp		settingspage.cpp
accountcard.h		magdecode.h		settingspage.h
carddetect.cpp		magread.cpp
carddetect.h		magread.h
localhost:MagRead afuaxh1$ qmake magread.pro
Cannot find file: magread.pro.

Obviously, the file is there. Yet qmake cannot find it.

localhost:MagRead afuaxh1$ pwd
/Users/afuaxh1/Code/MagRead
localhost:MagRead afuaxh1$ qmake /Users/afuaxh1/Code/MagRead/magread.pro
Cannot find file: /Users/afuaxh1/Code/MagRead/magread.pro.

localhost:MagRead afuaxh1$ qmake -project
Failure to open file: /Users/afuaxh1/Code/MagRead//MagRead.pro
Unable to generate project file.
localhost:MagRead afuaxh1$ 

I notice an extra / in the output from this last command. Maybe that is the problem, but there seems to be no way to fix this.

**Comment by bfontaine** [comment]
Try `qmake MagRead.pro` as [in this SO thread](http://stackoverflow.com/a/30816290/735926).

**Comment by bfontaine** [comment]
The above should fix your issue; please reopen it if it doesn’t. Thanks!
