### ISSUE TITLE
Make teams public

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew#44861]
The @Homebrew/science and @Homebrew/linux teams are secret. Can they be made public?

**Comment by xu-cheng** [comment]
No objection from me(except I'd like to keep bot team remaining secret). Let's hear other maintainers feed back.

**Comment by mikemcquaid** [comment]
I'm going to set up the new organisation permissions stuff shortly.

**Comment by mikemcquaid** [comment]
Done.
