### ISSUE TITLE
problem with brew update

### ISSUE THREAD

**Issue by tczf1128** [Homebrew/homebrew#44886]
`brew update` failed, my system is OS X EI Capitan
It shows "Error: Failure while executing: git rev-parse -q --verify HEAD"

**Comment by bfontaine** [comment]
Try the following:
```
cd $(brew --repository)
git reset --hard origin/master
brew update
```

**Comment by DomT4** [comment]
Where we've seen this elsewhere it's been a permission problem, so if @bfontaine's steps don't work please check `brew doctor` and see if you get a warning about that.

**Comment by lorenzo4439** [comment]
brew update on OSX El Capitan also failed for me, with permission errors even after I followed the instructions to chown -R the /usr/local, which seemed to run OK.  I also tried the cleanup of Brew, cd /usr/local/Library && git stash && git clean -d -f, that I saw somewhere in the troubleshooting. Update still fails.  I tried bfontaine's solution above but the second line (git reset --hard origin/master) failed with file permission errors--here is a sample:
... git reset --hard origin/master
error: unable to unlink old '.gitignore' (Permission denied)
error: unable to create file .travis.yml (Permission denied)
error: unable to create file .yardopts (Permission denied)
error: unable to unlink old 'CODEOFCONDUCT.md' (Permission denied) ...

I can see that I have to reset permissions, but I already did that with /usr/local; do I have to go in and reset a bunch of files?

**Comment by DomT4** [comment]
Does `sudo chown -R $(whoami):admin /usr/local` resolve anything for you?

**Comment by jgwmaxwell** [comment]
I've had a working homebrew on El Capitan release version, but have exactly the same issue since today on the same files (and more). `brew update`, `brew upgrade`, `brew link` and co have worked fine, but today stopped working at all with permission errors. `csrutil disable` solves it, but that doesn't sound like a long-term approach.

**Comment by DomT4** [comment]
Please try the `sudo chown -R $(whoami):admin /usr/local` command. Please note Sophos Anti-Virus is currently breaking permissions on `/usr/local` as well, which they've agreed to do something about soon. We don't recommend disabling SIP as a long-term solution.

**Comment by jgwmaxwell** [comment]
Running `sudo chown -R $(whoami):admin /usr/local` gives an Operation not permitted error on numerous files, such as:

```
chown: /usr/local/.git/config: Operation not permitted
chown: /usr/local/.git/description: Operation not permitted
chown: /usr/local/.git/FETCH_HEAD: Operation not permitted
chown: /usr/local/.git/HEAD: Operation not permitted
chown: /usr/local/.git/hooks/applypatch-msg.sample: Operation not permitted
chown: /usr/local/.git/hooks/commit-msg.sample: Operation not permitted
chown: /usr/local/.git/hooks/post-update.sample: Operation not permitted
chown: /usr/local/.git/hooks/pre-applypatch.sample: Operation not permitted
chown: /usr/local/.git/hooks/pre-commit.sample: Operation not permitted
chown: /usr/local/.git/hooks/pre-push.sample: Operation not permitted
chown: /usr/local/.git/hooks/pre-rebase.sample: Operation not permitted
chown: /usr/local/.git/hooks/prepare-commit-msg.sample: Operation not permitted
chown: /usr/local/.git/hooks/update.sample: Operation not permitted
chown: /usr/local/.git/hooks: Operation not permitted
chown: /usr/local/.git/index: Operation not permitted
chown: /usr/local/.git/info/exclude: Operation not permitted
chown: /usr/local/.git/info: Operation not permitted
chown: /usr/local/.git/logs/HEAD: Operation not permitted
chown: /usr/local/.git/logs/refs/heads/master: Operation not permitted
chown: /usr/local/.git/logs/refs/heads: Operation not permitted
chown: /usr/local/.git/logs/refs/remotes/origin/master: Operation not permitted
chown: /usr/local/.git/logs/refs/remotes/origin: Operation not permitted
chown: /usr/local/.git/logs/refs/remotes: Operation not permitted
chown: /usr/local/.git/logs/refs: Operation not permitted
chown: /usr/local/.git/logs: Operation not permitted
chown: /usr/local/.git/objects/info: Operation not permitted
chown: /usr/local/.git/objects/pack/pack-5c7e0f47eeaf48ba44f4dfb42be3ed79885913a4.idx: Operation not permitted
chown: /usr/local/.git/objects/pack/pack-5c7e0f47eeaf48ba44f4dfb42be3ed79885913a4.pack: Operation not permitted
chown: /usr/local/.git/objects/pack: Operation not permitted
chown: /usr/local/.git/objects: Operation not permitted
chown: /usr/local/.git/ORIG_HEAD: Operation not permitted
chown: /usr/local/.git/refs/heads/master: Operation not permitted
chown: /usr/local/.git/refs/heads: Operation not permitted
chown: /usr/local/.git/refs/remotes/origin/master: Operation not permitted
chown: /usr/local/.git/refs/remotes/origin: Operation not permitted
chown: /usr/local/.git/refs/remotes: Operation not permitted
chown: /usr/local/.git/refs/tags: Operation not permitted
chown: /usr/local/.git/refs: Operation not permitted
chown: /usr/local/.git: Operation not permitted
chown: /usr/local/.gitignore: Operation not permitted
chown: /usr/local/.travis.yml: Operation not permitted
chown: /usr/local/.yardopts: Operation not permitted
chown: /usr/local/CODEOFCONDUCT.md: Operation not permitted
chown: /usr/local/CONTRIBUTING.md: Operation not permitted
chown: /usr/local/LICENSE.txt: Operation not permitted
chown: /usr/local/README.md: Operation not permitted
chown: /usr/local/SUPPORTERS.md: Operation not permitted
```

**Comment by DomT4** [comment]
@jgwmaxwell If you're still running with SIP disabled try:

```bash
sudo chflags norestricted /usr/local && sudo chown -R $(whoami):admin /usr/local
```

Any luck with that?

**Comment by jgwmaxwell** [comment]
So that restores access whilst SIP is disabled, but the moment you do a reboot, renable it and then reboot into an SIP world then it's immediately broken again - it's like that `chflags` isn't being persisted across reboots.

**Comment by DomT4** [comment]
> it's like that chflags isn't being persisted across reboots.

It should be, and has been in our experience so far :confused:. Can you `/bin/ls -lO /usr`? Curious what the output is there.

**Comment by jgwmaxwell** [comment]
```
ls -lO /usr
total 8
drwxr-xr-x     5 root    wheel  restricted   170 23 Aug 02:51 X11
lrwxr-xr-x     1 root    wheel  restricted     3 30 Sep 23:50 X11R6 -> X11
drwxr-xr-x     3 root    wheel  restricted   102 27 Aug 03:17 adic
drwxr-xr-x  1063 root    wheel  restricted 36142  9 Oct 14:41 bin
drwxr-xr-x   262 root    wheel  restricted  8908 30 Sep 23:57 lib
drwxr-xr-x   184 root    wheel  restricted  6256  9 Oct 14:41 libexec
drwxrwxr-x    24 hammer  admin  -            816 14 Oct 17:27 local
drwxr-xr-x   243 root    wheel  restricted  8262 30 Sep 23:50 sbin
drwxr-xr-x    45 root    wheel  restricted  1530 30 Sep 23:50 share
drwxr-xr-x     4 root    wheel  restricted   136 17 Sep 08:03 standalone
```

hammer is my username.

Thanks for looking at this, hugely appreciated.

**Comment by DomT4** [comment]
That all looks fine. Is that the case with SIP enabled as well? Can you run the same `ls` command on `/usr/local`? Do you have Sophos Anti-Virus installed? (Apologies for the billion questions).

**Comment by jgwmaxwell** [comment]
Hi @DomT4 no worries for the questions! Not running Sophos AV and the output of that `ls` command when SIP is enabled is the same. Running it on `/usr/local/` though gives this:

```
ls -laO /usr/local
total 104
drwxrwxr-x   24 hammer  admin  -                   816 14 Oct 17:27 .
drwxr-xr-x@  12 root    wheel  restricted,hidden   408  1 Oct 08:36 ..
drwxr-xr-x   13 hammer  admin  restricted          442 14 Oct 17:26 .git
-rw-r--r--    1 hammer  admin  restricted          462 14 Oct 17:04 .gitignore
-rw-r--r--    1 hammer  admin  restricted          793 14 Oct 17:04 .travis.yml
-rw-r--r--    1 hammer  admin  restricted          291 14 Oct 17:04 .yardopts
-rw-r--r--    1 hammer  admin  restricted         3161 14 Oct 17:04 CODEOFCONDUCT.md
-rw-r--r--    1 hammer  admin  restricted         1103 14 Oct 17:04 CONTRIBUTING.md
drwxr-xr-x  105 hammer  admin  -                  3570 14 Oct 17:02 Cellar
drwxr-xr-x    4 hammer  admin  -                   136  5 Oct 09:39 Frameworks
-rw-r--r--    1 hammer  admin  restricted         1241 14 Oct 17:04 LICENSE.txt
drwxr-xr-x   11 hammer  admin  -                   374 14 Oct 17:04 Library
-rw-r--r--    1 hammer  admin  restricted         2247 14 Oct 17:04 README.md
-rw-r--r--    1 hammer  admin  restricted        23805 14 Oct 17:04 SUPPORTERS.md
drwxr-xr-x  888 hammer  admin  -                 30192 14 Oct 17:04 bin
drwxr-xr-x   20 hammer  admin  -                   680 14 Oct 17:37 etc
drwxr-xr-x    6 hammer  admin  -                   204 10 Aug 13:48 foreman
drwxr-xr-x    7 hammer  admin  -                   238 10 Aug 13:48 heroku
drwxr-xr-x  110 hammer  admin  -                  3740 14 Oct 16:58 include
drwxr-xr-x  346 hammer  admin  -                 11764 14 Oct 17:02 lib
drwxr-xr-x  105 hammer  admin  -                  3570 14 Oct 17:27 opt
drwxr-xr-x    3 hammer  admin  -                   102 14 Oct 17:27 sbin
drwxr-xr-x   43 hammer  admin  -                  1462 14 Oct 16:56 share
drwxr-xr-x   11 hammer  admin  -                   374 14 Oct 17:05 var
```

Seems like the nonrestricted command isn't unrestricting everything - weird.

**Comment by lorenzo4439** [comment]
No, I have tried multiple times.  I am traveling now and will reply further
in a few days...

**Comment by lorenzo4439** [comment]
Operator error, mistyped the sudo chown command:-(  I got ownership of usr/local reassigned and it all works fine.  Thanks for the help!

**Comment by DomT4** [comment]
@jgwmaxwell If you're still having issues can you open a new Issue? Thanks. It's hard to track stuff in closed issues.

**Comment by guycalledseven** [comment]
@DomT4 can you please elaborate on Sophos Anti-Virus? I am experiencing the same thing, 
My /usr/local is unrestricted however something is changing ownership of ```/usr/local/bin``` and ```/usr/local/share``` to root:wheel.
```
drwxr-xr-x  176 root   wheel  -  5984 Oct 22 18:14 bin
drwxr-xr-x   16 root   wheel  -   544 Oct 22 11:29 share
```

Can it really be Sophos was nailing me all this time?
relevant https://github.com/Homebrew/homebrew/issues/44549#issuecomment-146994999
