### ISSUE TITLE
Is there an rsync for homebrew

### ISSUE THREAD

**Issue by 5c0tt** [Homebrew/homebrew#44896]
I can't seem to locate https://rsync.samba.org in homebrew.  Apple includes a woefully out of date and terribly broken version at rsync  version 2.6.9  protocol version 29

Current stable is: 3.1.1 with 3.1.2pre1 released also released.

What is the procedure to get this into homebrew?

**Comment by DomT4** [comment]
`brew install homebrew/dupes/rsync` :smiley:
