### ISSUE TITLE
Installation Failure on "Downloading" step

### ISSUE THREAD

**Issue by snowmiser091** [Homebrew/homebrew#44912]
I ran the "ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" command to install Homebrew. It got to the "Downloading and installing Homebrew" step then failed with the message:

"fatal: unable to access 'https://github.com/Homebrew/homebrew/': SSLRead() return error -9846
Failed during: git fetch origin master:refs/remotes/origin/master -n --depth=1"

I tried rerunning the install and got the message that Homebrew is already installed so I ran the command "ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"

After that I get the message:

"Failed to locate Homebrew!"

I have looked in the both the root and user Library folders, ~/.gitconfig, etc to find where this may be installed. I found a Homebrew folder under the /Library/Caches folder so I removed that and tried again. No luck. Where is this coming from and how do I get around my original installation failure messge?

Thanks.

**Comment by mikemcquaid** [comment]
What version of OS X are you on? What's the output of `which curl`? Thanks!

**Comment by snowmiser091** [comment]
This morning I was able to find another post that outlined removing the /usr/local/.git folder. Removing this allowed me to retry the install. The second time the install was successful.
