### ISSUE TITLE
libopendkim won't install on El Capitan

### ISSUE THREAD

**Issue by djstevenson** [Homebrew/homebrew#44926]
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libopendkim/2.10.3 --disable-filter --with-unbound=/usr/local/opt/unbound
Last 15 lines from /Users/admin/Library/Logs/Homebrew/libopendkim/01.configure:
...snip...
checking for OpenSSL library and includes... configure: error: OpenSSL not found

The openssl package is installed, and I tried:
export LDFLAGS='-L/usr/local/opt/openssl/lib'
export CPPFLAGS='-I/usr/local/opt/openssl/include'

**Comment by DomT4** [comment]
Pretty sure this is going to be a very simple fix. Will look at it this afternoon.

**Comment by djstevenson** [comment]
Thanks! Much appreciated.
