### ISSUE TITLE
not writeable- linking nmap

### ISSUE THREAD

**Issue by tejasmanohar** [Homebrew/homebrew#44938]
```shell
$ brew link nmap
Linking /usr/local/Cellar/nmap/6.47...
Error: Could not symlink share/man/de/man1/nmap.1
/usr/local/share/man/de/man1 is not writable.
```

Is this due to el capitan's restrictions. how to get around? i've installed many things via brew fine

**Comment by mikemcquaid** [comment]
`sudo chown -R $USER /usr/local`

**Comment by DomT4** [comment]
Closing per the above. Let us know if you're still seeing errors.

**Comment by tejasmanohar** [comment]
yea perfect. thanks
