### ISSUE TITLE
brew install sloccount result:ml_count.c:39:10: fatal error: 'stdio.h' file not found

### ISSUE THREAD

**Issue by zeallf** [Homebrew/homebrew#44932]
brew install sloccount

==> Downloading http://www.dwheeler.com/sloccount/sloccount-2.26.tar.gz
Already downloaded: /Library/Caches/Homebrew/sloccount-2.26.tar.gz
==> Patching
patching file break_filelist
==> make install PREFIX=/usr/local/Cellar/sloccount/2.26
Last 15 lines from /Users/Scott/Library/Logs/Homebrew/sloccount/01.make:
ml_count.c:39:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make: *** [ml_count] Error 1
<stdout><stdout>:19:10: fatal error: 'stdio.h' file not found
:19:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
#include <stdio.h>
         ^
1 error generated.
1 error generated.
make: *** [pascal_count] Error 1
make: *** [jsp_count] Error 1

lost file

**Comment by DomT4** [comment]
Please supply a `brew config` and `brew doctor`, Thanks!

**Comment by zeallf** [comment]
scottdeMacBookPro:IB_GTS2 Scott$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: fcd25580bbdaef7f9d15ad29dce97122131bdbe0
Last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.10.5-x86_64
Xcode: 7.0.1
CLT: N/A
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_60
scottdeMacBookPro:IB_GTS2 Scott$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Xcode 7 lacks the 10.10 SDK which can cause some builds to fail.
We recommend installing the Command Line Tools with:
  xcode-select --install
to resolve this issue.

and ok now, 

 brew install sloccount
==> Downloading http://www.dwheeler.com/sloccount/sloccount-2.26.tar.gz
Already downloaded: /Library/Caches/Homebrew/sloccount-2.26.tar.gz
==> Patching
patching file break_filelist
==> make install PREFIX=/usr/local/Cellar/sloccount/2.26
🍺  /usr/local/Cellar/sloccount/2.26: 51 files, 584K, built in 2 seconds


many thanks
