### ISSUE TITLE
In R, function data.entry() doesn't work and generate error on Mac OS X 10.11

### ISSUE THREAD

**Issue by davideradice** [Homebrew/homebrew#44947]
Hi to all. 

Using R, function data.entry() doesn't work and generate error on Mac OS X 10.11 with R version 3.2.2 (installed via Homebrew).

************
> cheese = c(1,2,3)
> data.entry(cheese)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: can't open file: /usr/local/Cellar/r/3.2.2_1/R.framework/Resources/modules/R_de.so (No such file or directory)
Error in dataentry(odata, as.list(Modes)) : X11 is not available
Inoltre: Warning message:
running command ''/usr/bin/otool' -L '/usr/local/Cellar/r/3.2.2_1/R.framework/Resources/modules/R_de.so'' had status 1
************

It seems that is due to the lack of a file in modules folder. In folder /usr/local/Cellar/r/3.2.2_1/R.framework/Resources/modules/ I can find only these two files:
internet.so
lapack.so

My configuration:

R:
R version 3.2.2 (2015-08-14) -- "Fire Safety"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.0.0 (64-bit)

brew:
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: c6dd414463eadd1e5b8e74eea03f57ed4e41c4da
Last commit: 35 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.11-x86_64
Xcode: 7.0.1
CLT: 7.0.0.0.1.1441394355
Clang: 7.0 build 700
X11: 2.7.8_rc2 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_40, 1.6.0_65-b14-468

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/homebrew-science#2892
