### ISSUE TITLE
dev doc: use of stable and default specs in formulas

### ISSUE THREAD

**Issue by mgk** [Homebrew/homebrew#44951]
The cookbook formula description of stable, devel and HEAD is pretty clear. A word on what it means to have things both outside and inside a `stable do` block would be a nice addition.

Minimally maybe just add a note to the [patches section](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#patches) about the [preference to have `url` and `sha256` inside stable block if one exists](https://github.com/Homebrew/homebrew/blob/e8e6a54fbbe239f8b9fe721afb8cf118a19b9dc7/Library/Homebrew/formula.rb#L1604-L1620).

**Comment by mikemcquaid** [comment]
Out of interest, do you find the cookbook significantly more useful than the API docs: http://www.rubydoc.info/github/Homebrew/homebrew/master/frames If you never saw them: let me know so we can make them more prominent. Thanks!

**Comment by mgk** [comment]
I hadn't seen the API docs and I (briefly) looked for them when I saw in `formula.rb` that the doc comments appeared to be structured for generating API docs. rubydoc...I should have realized.

For new contribs the level of detail in the cookbook and [How To Open a Homebrew Pull Request](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) feels just right to me as a long time dev/somewhat rusty rubyist/new contrib to Homebrew.

My use case was adding a patch to an existing formula, having little Homebrew dev experience.
In the cookbook maybe just the rule of thumb that if you add a patch you should move the url and sha256 into the same block as your patch and see API doc for details.

**Comment by mikemcquaid** [comment]
@mgk Thanks for the feedback!

**Comment by mikemcquaid** [comment]
Have made the formula API more prominent in #45374. Does this address your concerns, do you think?

**Comment by mgk** [comment]
:+1:
