### ISSUE TITLE
gnuradio python threading error

### ISSUE THREAD

**Issue by davidcranor** [Homebrew/homebrew#44957]
Hello,

I attempted to install gnuradio through python, but keep getting the error `Fatal Python error: PyThreadState_Get: no current thread`.  After doing some research, I see that there is a patch for building gnuradio on OSX meant to fix this issue, and that the actual formula for gnuradio applies this patch, so I am not sure what else to do...

I am OSX 10.10.5.

**Comment by mikemcquaid** [comment]
CC @tdsmith as I'm sure I've seen this error before.

**Comment by tdsmith** [comment]
> I attempted to install gnuradio through python

Does this mean you ran `brew install gnuradio` or something else? When and how are you invoking something that leads to this error?

**Comment by dardo82** [comment]
Maybe he is using `pip`?

**Comment by davidcranor** [comment]
Hi guys,

Sorry, there is a critical typo in my post.  I meant to say that I am trying to install via HOMEBREW.

Here is a transcript of me running brew `rmtree gnuradio` then reinstalling and attempting to run gnradio-companion.

https://www.dropbox.com/s/mw9sb5eolkohhvf/log.txt?dl=0

From my research on the gnuradio repo and mailing list, it seems that there is an issue with brew getting confused about which python (system vs installed) to link to, and a proposed patch which is supposed to remedy this.  I posted on that issues list as well...

https://github.com/gnuradio/gnuradio/pull/604

Other people report that the install works after applying this patch, and the gnuradio brew formula seems to have a procedure in it for applying this patch before install.  So seems to me that it should be working but I don't know enough about cmake, brew, or linking to figure out where the problem is on my own.

Thanks for looking at this!

**Comment by tdsmith** [comment]
Can you capture the stack trace in the crash dialog? That would be useful.

**Comment by tdsmith** [comment]
Looking at `for i in `brew deps gnuradio`; do brew deps $i | grep python && echo \($i\); done` I don't see anything with potentially conflicting linkages.

**Comment by davidcranor** [comment]
Can you tell me how to do that?  Sorry….

**Comment by fr0zenrain** [comment]
what the fuck,i met the same problem,the _gobject.so has crash,i spent much time ,but i haven't solve that,i'm crazy .and i also try compile pygobject by myself, but i met some others questions,and finally i give up,any one have others?

**Comment by fr0zenrain** [comment]
i can give the details more,in my gnuradio crash at imp.load_modules('rds_swig'),and i debug attach rds_swig, finally crash at /System/Library/Frameworks/Python.framework/Versions/2.7/Python, variable PyThreadState_Get is null ,i don't know why this variable is null.i don't want dissect.i 'm a newbie in OSX.
python in OSX is so confusion！

**Comment by DomT4** [comment]
Let us know if we can help further here, Thanks!
