### ISSUE TITLE
Update Docker formula to v1.8.3

### ISSUE THREAD

**Issue by nickarnold** [Homebrew/homebrew#44961]
Docker v1.8.3 was released recently to address a few security issues that can be read about [here](https://github.com/docker/docker/commit/f4bf5c7026816785d9f63c07e87f9450a49f2403#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR3).

I'm creating a PR for this now (all tests have passed, and I've followed the process carefully) and will reference this issue.

**Comment by bfontaine** [comment]
Closing this in favor of #44962. You can open a PR without an issue next time :wink:

**Comment by nickarnold** [comment]
Will do. Thanks!
