### ISSUE TITLE
Update 10.11 'brew doctor' alert as 'El Capitan' is no longer 'pre release'

### ISSUE THREAD

**Issue by weems** [Homebrew/homebrew#44971]
Please Update 10.11 'brew doctor' alert as 'El Capitan' is no longer 'pre release'

**Comment by DomT4** [comment]
If you're still seeing this you need to `brew update`. The warning will only show on OS X 10.12 now, so you'd have to be running a *very* pre-release system to see it :wink:

**Comment by DomT4** [comment]
Closing per the above. Let us know if that doesn't resolve it for some reason.
