### ISSUE TITLE
SQLite 3.9.0

### ISSUE THREAD

**Issue by chmaynard** [Homebrew/homebrew#44980]
New release. See https://sqlite.org/releaselog/3_9_0.html

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by chmaynard** [comment]
@mikemcquaid Ok, I'll give it a try.

**Comment by DomT4** [comment]
Looks like there's one in #44986. Closing here.

**Comment by chmaynard** [comment]
@vszakats Just curious, how did you generate the sha256 hash for SQLite 3.9.0?

**Comment by vszakats** [comment]
@chmaynard: I used openssl:
```bash
openssl dgst -sha256 sqlite-autoconf-3090000.tar.gz 
```

**Comment by bfontaine** [comment]
@chmaynard You can also edit the URL in the formula then run `brew fetch sqlite` that’ll tell you the sha256. You can also `curl <the url> | shasum -a 256`.

**Comment by chmaynard** [comment]
I wrote a short blog post so I don't forget!
http://chmaynard.com/2015/10/19/generating-sha256.html

**Comment by vszakats** [comment]
Nice! Just a minor note that in case of the sqlite formula specifically, its documentation archive is referenced from the formula and [that](https://github.com/Homebrew/homebrew/blob/da042c9806eae341f328a8aaca82eab2a948e45f/Library/Formula/sqlite.rb#L39-L43) needs to be updated as well:
```ruby
  resource "docs" do
    url "https://sqlite.org/2015/sqlite-doc-3090000.zip"
    version "3.9.0"
    sha256 "2b5f4116b16907ab087548047c0489e4cc8124e249b3f8c55005098db863be17"
  end
```
