### ISSUE TITLE
gnulib PATHMAX problem

### ISSUE THREAD

**Issue by zchee** [Homebrew/homebrew#44993]
Now, `gnulib` is created can not be deleted directory.

`confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/.....`

FYI, https://github.com/NixOS/nixpkgs/issues/9707

Solution: `export gl_cv_func_getcwd_abort_bug="no"`

This problem occurs in all formula that depends on gnulib.
e.g. `coreutils` formula.

https://github.com/NixOS/nixpkgs/issues/9707#issuecomment-146075784
Can delete it if use this script, but I think that it is really a problem.

**Comment by oxishmit** [comment]
I suggest you to try Long Path Tool.
