### ISSUE TITLE
how to install brew listed formulae from a txt file

### ISSUE THREAD

**Issue by bolorkhuu** [Homebrew/homebrew#45003]
hi all,

i have many listed formulae in a txt file from ```brew list > req_brew.txt ``` and trying to install them like `  ```brew install -r req_brew.txt ```.  this works on pip. does anyone know how do i install them like on pip.

thanks in advance

**Comment by mikemcquaid** [comment]
I'd recommend using https://github.com/Homebrew/homebrew-bundle. You can otherwise do `brew list > file` `cat file | xargs brew install`

**Comment by bolorkhuu** [comment]
thanks!
