### ISSUE TITLE
Varnish receipt not fully functional

### ISSUE THREAD

**Issue by dahankzter** [Homebrew/homebrew#45017]
Perhaps I am doing something wrong but after an install I do not have a running varnish instance.
The plist points to a non-existent default.vcl and no information stating that it needs to be loaded. It also points to port 80 which may or may not be ok but it would require root level to start then right?

I can probably get it to "works on my machine" state but the spirit of homebrew is more "works by default everywhere" so perhaps it should be changed.

**Comment by mikemcquaid** [comment]
Can you clarify what you mean by receipt? Also, can you give the list of command you've run and their expected (vs actual) output? Thanks!

**Comment by dahankzter** [comment]
By receipt I just mean that the "brew install varnish" command does not work.
I thought the install scripts were called recipes. I should perhaps have said "recipe" rather than "receipt" though.

So I just run "brew install varnish" and it says the normal "to reload... plist" but that does not start a varnish instance.

Not sure that that is intended but if it is then it does not work. I have several other databases etc like rabbitmq running this way using a default that can be run as a normal use on unprivileged ports etc.

If it is not the case that it is supposed to run right away the I think we need a notification along the lines:

"In order to start you have to either start as root or modify the config file, see http://......"

or something similar to make it more clear what is needed.

What do you think?
