### ISSUE TITLE
gfortran failure: ld: library not found for -lSystem

### ISSUE THREAD

**Issue by powellb** [Homebrew/homebrew#45011]
I upgraded to El Capitan, performed a 'brew update' then 'brew upgrade' afterwards. Now, when I try to use gfortran, I get an error:

% gfortran test.f90
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status

This would seem to indicate a problem in the connection with XCode; however, brew doctor reports:

% brew doctor
Your system is ready to brew.

% brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: c09b6b0c2ebb229d8e96b3ee0c5c5503a0b1c26e
Last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
OS X: 10.11-x86_64
Xcode: 7.0.1
CLT: N/A
Clang: 7.0 build 700
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A

Any ideas on how to work-around the issue? Remove gcc and reinstall?

**Comment by DomT4** [comment]
Please try `brew reinstall gcc`. We saw this issue in some of the earlier El Capitan bottles for `gcc` and since resolved it with new bottles, so hopefully that's the issue here.

**Comment by powellb** [comment]
Dom,

Thank you for the note. Since you posted, it has been compiling... Now that it is complete, I can verify that doing a reinstall has everything working correctly. You can close the issue.

Thanks!

**Comment by DomT4** [comment]
Thanks for the confirmation! Glad everything is working again now.
