### ISSUE TITLE
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl

### ISSUE THREAD

**Issue by tausiq** [Homebrew/homebrew#45020]
At first, I installed GStreamer
```
brew install gstreamer
``` 
got this reply, 
```
==> Installing gstreamer 
==> Downloading https://homebrew.bintray.com/bottles/gstreamer-1.6.0.el_capitan
######################################################################## 100.0% 
==> Pouring gstreamer-1.6.0.el_capitan.bottle.tar.gz 
🍺  /usr/local/Cellar/gstreamer/1.6.0: 366 files, 20M
```
then ran autogen inside GStreamer  
```
./autogen.sh
```
which ran successfully. 
After that, ran make 
```
make
```
Got this error, 
```
... 
Making all in docs 
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive 
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C design 
make[4]: Nothing to be done for `all'. 
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C gst 
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am 
  DOC   Building HTML 
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl" 
compilation error: file /usr/local/Cellar/gtk-doc/1.24/share/gtk-doc/data/gtk-doc.xsl line 10 element import 
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl
make[5]: *** [html-build.stamp] Error 5 
make[4]: *** [all] Error 2 
make[3]: *** [gst] Error 2 
make[2]: *** [all] Error 2 
make[1]: *** [all-recursive] Error 1 
make: *** [all] Error 2
```

**Comment by mikemcquaid** [comment]
Can you access http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl from your browser?

**Comment by tausiq** [comment]
yes, It downloads file "chunk.xsl". 
At first I thought I was related with GStreamer. But GStreamer developer Sebastian (https://coaxion.net/blog/2013/10/gstreamer-1-0-examples-for-ios-android-and-in-general/comment-page-1/#comment-55165) pointed otherwise.

**Comment by mikemcquaid** [comment]
Also, I'm not sure what you're trying to do. Didn't `gstreamer` install OK from the bottle? Where are you running e.g. `make`?

**Comment by tausiq** [comment]
Well, I am trying to build GStreamer from the source (http://cgit.freedesktop.org/gstreamer/gstreamer/). First step, after cloning GStreamer, is to run, ```./autogen.sh``` and then ```make```

**Comment by mikemcquaid** [comment]
Ok. That doesn't seem to be Homebrew-related then if `brew install gstreamer` works. Sorry!

**Comment by khaledhosny** [comment]
FWIW, since I had a similar issue with another package using gtk-doc, it turns out to be because of https://github.com/Homebrew/homebrew/blob/master/Library/Formula/docbook.rb#L85. Doing an `export XML_CATALOG_FILES="/usr/local/etc/xml/catalog"` was all needed to fix this.
