### ISSUE TITLE
`brew update` color output is unreadable

### ISSUE THREAD

**Issue by markcornick** [Homebrew/homebrew#45028]
I know this sounds very bikeshed-y, but a recent update (it might have been #44335) colorizes the output of `brew update` with highlighting of installed formulas. In my terminal (and perhaps others using a dark background, unlike the white background used in the PR) this displays as white text on a yellow background, which is unreadable:

![screen shot 2015-10-16 at 8 51 07 am](https://cloud.githubusercontent.com/assets/302/10542019/1d96377c-73e3-11e5-9731-b66dd05465b6.png)

May I suggest adding an option along the lines of HOMEBREW_NO_EMOJI to disable this?

**Comment by mikemcquaid** [comment]
CC @UniqMartin 

Rather than an ENV option it'd be nice if we can improve this so it looks good on dark backgrounds.

**Comment by markcornick** [comment]
As a pre-emptive note to others who like their bikesheds painted another color, **please do not +1 or :+1: this issue** - every time you do that, it spams everyone who is participating in the thread. Thanks!

**Comment by markcornick** [comment]
@mikemcquaid is right, this could be fixed by explicitly making the text black FG on yellow BG, as opposed to (default) FG on yellow BG which appears to be the current situation. I'll withdraw my request for an ENV and and support that idea instead.

**Comment by UniqMartin** [comment]
Apologies, I hadn't tried it on a dark background. I would also prefer to find a highlighting that works for dark and bright backgrounds equally well. (Originally, the highlighting was just bold text (which should always have nice contrast), but that was not sufficiently visible.)

I'll try the (explicit) black on yellow suggestion and will report back.

**Comment by mikemcquaid** [comment]
@UniqMartin I'd probably prefer just bold, personally.

**Comment by UniqMartin** [comment]
Created a PR to address this issue. Let's continue the discussion about the exact formatting there.
