### ISSUE TITLE
[Feature Request] Add Fuse

### ISSUE THREAD

**Issue by vinkla** [Homebrew/homebrew#45029]
[Fuse](https://www.fusetools.com/) is the UX tool suite for app designers and developers. Design and edit your app while it's running. [Fuse](https://www.fusetools.com/) closes the gap between prototyping and actual development.

Download link: https://api.fusetools.com/internal/v1/fuse_download/osx

It depends on Mono:

> Mono is required to run Fuse on OS X. Download and install the normal MDK, Mono version 4.0.4 before you continue with the Fuse installation.
>
> Important note about OS X El Capitan: Despite what the Mono download page says, Mono version 4.0.4 is in fact the version we recommend for El Capitan. Users who have installed newer versions (such as 4.2) have reported lots of issues, but version 4.0.4 works overall a lot better with Fuse.

https://www.fusetools.com/community/guides/setup/install-osx

**Comment by mikemcquaid** [comment]
Looks like I can't download it without joining the beta: https://www.fusetools.com/downloads

**Comment by vinkla** [comment]
That is true, I'll ask them about this. Let me get back on this.

**Comment by vinkla** [comment]
From there CEO:

> Hi, no, you have to accept the beta license agreement This will change in the future. But at the current stage you have to sign up - Anders Lassen
