### ISSUE TITLE
How can I change the parameter HOMEBREW_OPTIMIZATION_LEVEL in formula?

### ISSUE THREAD

**Issue by wkentaro** [Homebrew/homebrew#45033]
I need below change to compile my program with `brew`.
How can I configure it in my formula?
```
diff --git a/Library/Homebrew/extend/ENV/super.rb b/Library/Homebrew/extend/ENV/super.rb
index 5216b57..4f0642e 100644
--- a/Library/Homebrew/extend/ENV/super.rb
+++ b/Library/Homebrew/extend/ENV/super.rb
@@ -50,7 +50,7 @@ module Superenv
     self["PKG_CONFIG_PATH"] = determine_pkg_config_path
     self["PKG_CONFIG_LIBDIR"] = determine_pkg_config_libdir
     self["HOMEBREW_CCCFG"] = determine_cccfg
-    self["HOMEBREW_OPTIMIZATION_LEVEL"] = "Os"
+    self["HOMEBREW_OPTIMIZATION_LEVEL"] = "O0"
     self["HOMEBREW_BREW_FILE"] = HOMEBREW_BREW_FILE.to_s
     self["HOMEBREW_PREFIX"] = HOMEBREW_PREFIX.to_s
     self["HOMEBREW_CELLAR"] = HOMEBREW_CELLAR.to_s
```

my formula is [this](https://github.com/wkentaro/homebrew/blob/euslisp-new-formula/Library/Formula/euslisp.rb) for https://github.com/euslisp/EusLisp.

**Comment by bfontaine** [comment]
You can use `ENV.O0` at the beginning of your `def install`. See [`clisp.rb`](https://github.com/Homebrew/homebrew/blob/bf3864c276049332f984acfdbee2602122813f24/Library/Formula/clisp.rb#L31) for an example.

**Comment by DomT4** [comment]
Answered both here and in #45034 :). Closing.

**Comment by wkentaro** [comment]
That works, thanks.
