### ISSUE TITLE
brew install llvm --with-clang --with-lld --with-lldb FAILS

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [Homebrew/homebrew#45036]
[OSX 10.10.5 fully updated as of Oct 15, 2015]

Hi,
  I'm new to Homebrew and not really sure who/where I should be asking about the LLVM problem I'm having.  I've searched all over the place for a solution but haven't found one.

When I installed `llvm` on its own, I didn't get the clang-c/include folder, but it did build.  So I added the extra options (as per the title) but the build fails on:

    ==> cmake -G Unix Makefiles /private/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/llvm/3.6.2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEW
    ==> make
    Last 15 lines from /Users/nap/Library/Logs/Homebrew/llvm/02.make:
    [ 93%] Building CXX object tools/lldb/source/Target/CMakeFiles/lldbTarget.dir/ThreadPlanTracer.cpp.o
    cd /tmp/llvm20151017-4432-5qnn/tools/lldb/source/Target && /usr/local/Library/ENV/4.3/clang++   -DGTEST_HAS_RTTI=0 -DHAVE_ROUND -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -std=c++11 -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-deprecated-register  -fno-exceptions -fno-rtti -fPIC -I/tmp/llvm20151017-4432-5qnn/tools/lldb/source/Target -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/source/Target -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/include -I/tmp/llvm20151017-4432-5qnn/tools/lldb/include -I/tmp/llvm20151017-4432-5qnn/include -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/include -I/usr/include/python2.7 -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/../clang/include -I/tmp/llvm20151017-4432-5qnn/tools/lldb/../clang/include -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/source/. -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/source/Target/../Plugins/Process/Utility    -UNDEBUG -fno-exceptions -fno-rtti -o CMakeFiles/lldbTarget.dir/ThreadPlanTracer.cpp.o -c /tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/source/Target/ThreadPlanTracer.cpp
    [ 93%] Building CXX object tools/lldb/source/Target/CMakeFiles/lldbTarget.dir/ThreadSpec.cpp.o
    cd /tmp/llvm20151017-4432-5qnn/tools/lldb/source/Target && /usr/local/Library/ENV/4.3/clang++   -DGTEST_HAS_RTTI=0 -DHAVE_ROUND -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -std=c++11 -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-deprecated-register  -fno-exceptions -fno-rtti -fPIC -I/tmp/llvm20151017-4432-5qnn/tools/lldb/source/Target -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/source/Target -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/include -I/tmp/llvm20151017-4432-5qnn/tools/lldb/include -I/tmp/llvm20151017-4432-5qnn/include -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/include -I/usr/include/python2.7 -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/../clang/include -I/tmp/llvm20151017-4432-5qnn/tools/lldb/../clang/include -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/source/. -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/source/Target/../Plugins/Process/Utility    -UNDEBUG -fno-exceptions -fno-rtti -o CMakeFiles/lldbTarget.dir/ThreadSpec.cpp.o -c /tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/source/Target/ThreadSpec.cpp
    [ 93%] Building CXX object tools/lldb/source/Target/CMakeFiles/lldbTarget.dir/UnixSignals.cpp.o
    cd /tmp/llvm20151017-4432-5qnn/tools/lldb/source/Target && /usr/local/Library/ENV/4.3/clang++   -DGTEST_HAS_RTTI=0 -DHAVE_ROUND -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -std=c++11 -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-deprecated-register  -fno-exceptions -fno-rtti -fPIC -I/tmp/llvm20151017-4432-5qnn/tools/lldb/source/Target -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/source/Target -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/include -I/tmp/llvm20151017-4432-5qnn/tools/lldb/include -I/tmp/llvm20151017-4432-5qnn/include -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/include -I/usr/include/python2.7 -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/../clang/include -I/tmp/llvm20151017-4432-5qnn/tools/lldb/../clang/include -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/source/. -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/source/Target/../Plugins/Process/Utility    -UNDEBUG -fno-exceptions -fno-rtti -o CMakeFiles/lldbTarget.dir/UnixSignals.cpp.o -c /tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/source/Target/UnixSignals.cpp
    [ 93%] Building CXX object tools/lldb/source/Target/CMakeFiles/lldbTarget.dir/UnwindAssembly.cpp.o
    cd /tmp/llvm20151017-4432-5qnn/tools/lldb/source/Target && /usr/local/Library/ENV/4.3/clang++   -DGTEST_HAS_RTTI=0 -DHAVE_ROUND -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -std=c++11 -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-deprecated-register  -fno-exceptions -fno-rtti -fPIC -I/tmp/llvm20151017-4432-5qnn/tools/lldb/source/Target -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/source/Target -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/include -I/tmp/llvm20151017-4432-5qnn/tools/lldb/include -I/tmp/llvm20151017-4432-5qnn/include -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/include -I/usr/include/python2.7 -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/../clang/include -I/tmp/llvm20151017-4432-5qnn/tools/lldb/../clang/include -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/source/. -I/tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/source/Target/../Plugins/Process/Utility    -UNDEBUG -fno-exceptions -fno-rtti -o CMakeFiles/lldbTarget.dir/UnwindAssembly.cpp.o -c /tmp/llvm20151017-4432-19b226c/llvm-3.6.2.src/tools/lldb/source/Target/UnwindAssembly.cpp
    [ 93%] Linking CXX static library ../../../../lib/liblldbTarget.a
    cd /tmp/llvm20151017-4432-5qnn/tools/lldb/source/Target && /usr/local/Cellar/cmake/3.3.2/bin/cmake -P CMakeFiles/lldbTarget.dir/cmake_clean_target.cmake
    cd /tmp/llvm20151017-4432-5qnn/tools/lldb/source/Target && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/lldbTarget.dir/link.txt --verbose=1
    /usr/bin/ar cq ../../../../lib/liblldbTarget.a  CMakeFiles/lldbTarget.dir/ABI.cpp.o CMakeFiles/lldbTarget.dir/CPPLanguageRuntime.cpp.o CMakeFiles/lldbTarget.dir/ExecutionContext.cpp.o CMakeFiles/lldbTarget.dir/FileAction.cpp.o CMakeFiles/lldbTarget.dir/JITLoader.cpp.o CMakeFiles/lldbTarget.dir/JITLoaderList.cpp.o CMakeFiles/lldbTarget.dir/InstrumentationRuntime.cpp.o CMakeFiles/lldbTarget.dir/InstrumentationRuntimeStopInfo.cpp.o CMakeFiles/lldbTarget.dir/LanguageRuntime.cpp.o CMakeFiles/lldbTarget.dir/Memory.cpp.o CMakeFiles/lldbTarget.dir/MemoryHistory.cpp.o CMakeFiles/lldbTarget.dir/NativeRegisterContext.cpp.o CMakeFiles/lldbTarget.dir/NativeRegisterContextRegisterInfo.cpp.o CMakeFiles/lldbTarget.dir/ObjCLanguageRuntime.cpp.o CMakeFiles/lldbTarget.dir/OperatingSystem.cpp.o CMakeFiles/lldbTarget.dir/PathMappingList.cpp.o CMakeFiles/lldbTarget.dir/Platform.cpp.o CMakeFiles/lldbTarget.dir/Process.cpp.o CMakeFiles/lldbTarget.dir/ProcessInfo.cpp.o CMakeFiles/lldbTarget.dir/ProcessLaunchInfo.cpp.o CMakeFiles/lldbTarget.dir/Queue.cpp.o CMakeFiles/lldbTarget.dir/QueueItem.cpp.o CMakeFiles/lldbTarget.dir/QueueList.cpp.o CMakeFiles/lldbTarget.dir/RegisterContext.cpp.o CMakeFiles/lldbTarget.dir/SectionLoadHistory.cpp.o CMakeFiles/lldbTarget.dir/SectionLoadList.cpp.o CMakeFiles/lldbTarget.dir/StackFrame.cpp.o CMakeFiles/lldbTarget.dir/StackFrameList.cpp.o CMakeFiles/lldbTarget.dir/StackID.cpp.o CMakeFiles/lldbTarget.dir/StopInfo.cpp.o CMakeFiles/lldbTarget.dir/SystemRuntime.cpp.o CMakeFiles/lldbTarget.dir/Target.cpp.o CMakeFiles/lldbTarget.dir/TargetList.cpp.o CMakeFiles/lldbTarget.dir/Thread.cpp.o CMakeFiles/lldbTarget.dir/ThreadCollection.cpp.o CMakeFiles/lldbTarget.dir/ThreadList.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlan.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanBase.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanCallFunction.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanCallUserExpression.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanPython.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanRunToAddress.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanShouldStopHere.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanStepInRange.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanStepInstruction.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanStepOut.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanStepOverBreakpoint.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanStepOverRange.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanStepRange.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanStepThrough.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanStepUntil.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanTracer.cpp.o CMakeFiles/lldbTarget.dir/ThreadSpec.cpp.o CMakeFiles/lldbTarget.dir/UnixSignals.cpp.o CMakeFiles/lldbTarget.dir/UnwindAssembly.cpp.o
    /usr/bin/ranlib ../../../../lib/liblldbTarget.a
    [ 93%] Built target lldbTarget
    make: *** [all] Error 2
    
    READ THIS: https://git.io/brew-troubleshooting
    
    These open issues may also help:
    llvm: add more components https://github.com/Homebrew/homebrew/pull/44250
    llvm 3.7.0 https://github.com/Homebrew/homebrew/pull/43499
    rust: Add --with-llvm option https://github.com/Homebrew/homebrew/pull/44138
    llvm formula's clang++ fails with -L $(brew --prefix llvm)/lib https://github.com/Homebrew/homebrew/issues/42957
    ocaml will never be detected by llvm during configuration https://github.com/Homebrew/homebrew/issues/43335
    llvm --with-clang --with-lldb fails to build https://github.com/Homebrew/homebrew/issues/42041
    MacOS.(gcc|clang|llvm)_version can return nil https://github.com/Homebrew/homebrew/issues/18781

In typical CMAKE fashion, the error message is not very useful.

I also tried `brew install llvm --with-clang --with-lld --with-lldb --HEAD` but that failed too.

    ==> cmake -G Unix Makefiles /private/tmp/llvm20151017-20736-op5a0p -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/llvm/HEAD -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE
    ==> make
    Last 15 lines from /Users/nap/Library/Logs/Homebrew/llvm/02.make:
    [ 95%] Building CXX object tools/lldb/source/Target/CMakeFiles/lldbTarget.dir/UnwindAssembly.cpp.o
    cd /tmp/llvm20151017-20736-ws8p8/tools/lldb/source/Target && /usr/local/Library/ENV/4.3/clang++   -DGTEST_HAS_RTTI=0 -DHAVE_ROUND -DLIBXML2_DEFINED -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -std=c++11 -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-deprecated-register -Wno-vla-extension  -fno-exceptions -fno-rtti -fPIC -fPIC -I/tmp/llvm20151017-20736-ws8p8/tools/lldb/source/Target -I/tmp/llvm20151017-20736-op5a0p/tools/lldb/source/Target -I/tmp/llvm20151017-20736-op5a0p/tools/lldb/include -I/tmp/llvm20151017-20736-ws8p8/tools/lldb/include -I/tmp/llvm20151017-20736-ws8p8/include -I/tmp/llvm20151017-20736-op5a0p/include -I/usr/include/python2.7 -I/tmp/llvm20151017-20736-op5a0p/tools/lldb/../clang/include -I/tmp/llvm20151017-20736-ws8p8/tools/lldb/../clang/include -I/tmp/llvm20151017-20736-op5a0p/tools/lldb/source/. -I/tmp/llvm20151017-20736-op5a0p/tools/lldb/source/Target/../Plugins/Process/Utility    -UNDEBUG  -fno-exceptions -fno-rtti -o CMakeFiles/lldbTarget.dir/UnwindAssembly.cpp.o -c /tmp/llvm20151017-20736-op5a0p/tools/lldb/source/Target/UnwindAssembly.cpp
    [ 95%] Linking CXX static library ../../../../lib/liblldbSymbol.a
    cd /tmp/llvm20151017-20736-ws8p8/tools/lldb/source/Symbol && /usr/local/Cellar/cmake/3.3.2/bin/cmake -P CMakeFiles/lldbSymbol.dir/cmake_clean_target.cmake
    cd /tmp/llvm20151017-20736-ws8p8/tools/lldb/source/Symbol && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/lldbSymbol.dir/link.txt --verbose=1
    /usr/bin/ar cq ../../../../lib/liblldbSymbol.a  CMakeFiles/lldbSymbol.dir/ArmUnwindInfo.cpp.o CMakeFiles/lldbSymbol.dir/Block.cpp.o CMakeFiles/lldbSymbol.dir/ClangASTContext.cpp.o CMakeFiles/lldbSymbol.dir/ClangASTImporter.cpp.o CMakeFiles/lldbSymbol.dir/ClangExternalASTSourceCallbacks.cpp.o CMakeFiles/lldbSymbol.dir/ClangExternalASTSourceCommon.cpp.o CMakeFiles/lldbSymbol.dir/CompilerDecl.cpp.o CMakeFiles/lldbSymbol.dir/CompilerDeclContext.cpp.o CMakeFiles/lldbSymbol.dir/CompilerType.cpp.o CMakeFiles/lldbSymbol.dir/CompileUnit.cpp.o CMakeFiles/lldbSymbol.dir/CompactUnwindInfo.cpp.o CMakeFiles/lldbSymbol.dir/Declaration.cpp.o CMakeFiles/lldbSymbol.dir/DWARFCallFrameInfo.cpp.o CMakeFiles/lldbSymbol.dir/Function.cpp.o CMakeFiles/lldbSymbol.dir/FuncUnwinders.cpp.o CMakeFiles/lldbSymbol.dir/GoASTContext.cpp.o CMakeFiles/lldbSymbol.dir/LineEntry.cpp.o CMakeFiles/lldbSymbol.dir/LineTable.cpp.o CMakeFiles/lldbSymbol.dir/ObjectFile.cpp.o CMakeFiles/lldbSymbol.dir/Symbol.cpp.o CMakeFiles/lldbSymbol.dir/SymbolContext.cpp.o CMakeFiles/lldbSymbol.dir/SymbolFile.cpp.o CMakeFiles/lldbSymbol.dir/SymbolVendor.cpp.o CMakeFiles/lldbSymbol.dir/Symtab.cpp.o CMakeFiles/lldbSymbol.dir/Type.cpp.o CMakeFiles/lldbSymbol.dir/TypeList.cpp.o CMakeFiles/lldbSymbol.dir/TypeMap.cpp.o CMakeFiles/lldbSymbol.dir/TypeSystem.cpp.o CMakeFiles/lldbSymbol.dir/UnwindPlan.cpp.o CMakeFiles/lldbSymbol.dir/UnwindTable.cpp.o CMakeFiles/lldbSymbol.dir/Variable.cpp.o CMakeFiles/lldbSymbol.dir/VariableList.cpp.o CMakeFiles/lldbSymbol.dir/VerifyDecl.cpp.o
    /usr/bin/ranlib ../../../../lib/liblldbSymbol.a
    [ 95%] Built target lldbSymbol
    [ 95%] Linking CXX static library ../../../../lib/liblldbTarget.a
    cd /tmp/llvm20151017-20736-ws8p8/tools/lldb/source/Target && /usr/local/Cellar/cmake/3.3.2/bin/cmake -P CMakeFiles/lldbTarget.dir/cmake_clean_target.cmake
    cd /tmp/llvm20151017-20736-ws8p8/tools/lldb/source/Target && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/lldbTarget.dir/link.txt --verbose=1
    /usr/bin/ar cq ../../../../lib/liblldbTarget.a  CMakeFiles/lldbTarget.dir/ABI.cpp.o CMakeFiles/lldbTarget.dir/CPPLanguageRuntime.cpp.o CMakeFiles/lldbTarget.dir/ExecutionContext.cpp.o CMakeFiles/lldbTarget.dir/FileAction.cpp.o CMakeFiles/lldbTarget.dir/JITLoader.cpp.o CMakeFiles/lldbTarget.dir/JITLoaderList.cpp.o CMakeFiles/lldbTarget.dir/InstrumentationRuntime.cpp.o CMakeFiles/lldbTarget.dir/InstrumentationRuntimeStopInfo.cpp.o CMakeFiles/lldbTarget.dir/Language.cpp.o CMakeFiles/lldbTarget.dir/LanguageRuntime.cpp.o CMakeFiles/lldbTarget.dir/Memory.cpp.o CMakeFiles/lldbTarget.dir/MemoryHistory.cpp.o CMakeFiles/lldbTarget.dir/ObjCLanguageRuntime.cpp.o CMakeFiles/lldbTarget.dir/OperatingSystem.cpp.o CMakeFiles/lldbTarget.dir/PathMappingList.cpp.o CMakeFiles/lldbTarget.dir/Platform.cpp.o CMakeFiles/lldbTarget.dir/Process.cpp.o CMakeFiles/lldbTarget.dir/ProcessInfo.cpp.o CMakeFiles/lldbTarget.dir/ProcessLaunchInfo.cpp.o CMakeFiles/lldbTarget.dir/Queue.cpp.o CMakeFiles/lldbTarget.dir/QueueItem.cpp.o CMakeFiles/lldbTarget.dir/QueueList.cpp.o CMakeFiles/lldbTarget.dir/RegisterContext.cpp.o CMakeFiles/lldbTarget.dir/SectionLoadHistory.cpp.o CMakeFiles/lldbTarget.dir/SectionLoadList.cpp.o CMakeFiles/lldbTarget.dir/StackFrame.cpp.o CMakeFiles/lldbTarget.dir/StackFrameList.cpp.o CMakeFiles/lldbTarget.dir/StackID.cpp.o CMakeFiles/lldbTarget.dir/StopInfo.cpp.o CMakeFiles/lldbTarget.dir/SystemRuntime.cpp.o CMakeFiles/lldbTarget.dir/Target.cpp.o CMakeFiles/lldbTarget.dir/TargetList.cpp.o CMakeFiles/lldbTarget.dir/Thread.cpp.o CMakeFiles/lldbTarget.dir/ThreadCollection.cpp.o CMakeFiles/lldbTarget.dir/ThreadList.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlan.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanBase.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanCallFunction.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanCallFunctionUsingABI.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanCallUserExpression.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanPython.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanRunToAddress.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanShouldStopHere.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanStepInRange.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanStepInstruction.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanStepOut.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanStepOverBreakpoint.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanStepOverRange.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanStepRange.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanStepThrough.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanStepUntil.cpp.o CMakeFiles/lldbTarget.dir/ThreadPlanTracer.cpp.o CMakeFiles/lldbTarget.dir/ThreadSpec.cpp.o CMakeFiles/lldbTarget.dir/UnixSignals.cpp.o CMakeFiles/lldbTarget.dir/UnwindAssembly.cpp.o
    /usr/bin/ranlib ../../../../lib/liblldbTarget.a
    [ 95%] Built target lldbTarget
    make: *** [all] Error 2
    
    READ THIS: https://git.io/brew-troubleshooting
    
    These open issues may also help:
    llvm: add more components https://github.com/Homebrew/homebrew/pull/44250
    llvm 3.7.0 https://github.com/Homebrew/homebrew/pull/43499
    rust: Add --with-llvm option https://github.com/Homebrew/homebrew/pull/44138
    llvm formula's clang++ fails with -L $(brew --prefix llvm)/lib https://github.com/Homebrew/homebrew/issues/42957
    ocaml will never be detected by llvm during configuration https://github.com/Homebrew/homebrew/issues/43335
    llvm --with-clang --with-lldb fails to build https://github.com/Homebrew/homebrew/issues/42041
    MacOS.(gcc|clang|llvm)_version can return nil https://github.com/Homebrew/homebrew/issues/18781

Has anyone else experience this problem and have a solution?

**Comment by Napoleon-BlownApart** [comment]
I tried without the debugger, and it worked with the command line given in the title.
Something's not right with the debugger.
(I followed the instructions given here: https://llvm.org/svn/llvm-project/lldb/trunk/docs/code-signing.txt , so it's not a certificate issue.)

**Comment by DomT4** [comment]
Will probably be solved when #44250 is merged.

**Comment by Napoleon-BlownApart** [comment]
That's probably good to hear.

Though the build succeeded, it didn't produce `libclang.3.6.dylib`.  So I'm still stuck.

**Comment by aw1621107** [comment]
How'd you run the build?

I'm seeing that library at `/usr/local/Cellar/llvm/3.6.2/lib/libclang.3.6.dylib`, so things seem to be working fine

**Comment by Napoleon-BlownApart** [comment]
Yea, found it.
Didn't set the link folder in Xcode and Finder wasn't able to find it.  But I found it using the terminal.
