### ISSUE TITLE
brew uninstall (remove) is unsafe, breaks dependencies

### ISSUE THREAD

**Issue by proski** [Homebrew/homebrew#45040]
"brew uninstall" (a.k.a. "brew remove") breaks dependencies. Example:
```
bash-3.2$ brew install midnight-commander
==> Installing dependencies for midnight-commander: glib
==> Installing midnight-commander dependency: glib
==> Downloading https://homebrew.bintray.com/bottles/glib-2.46.0.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/glib-2.46.0.yosemite.bottle.tar.gz
==> Pouring glib-2.46.0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/glib/2.46.0: 416 files, 18M
==> Installing midnight-commander
==> Downloading https://homebrew.bintray.com/bottles/midnight-commander-4.8.14.yosemite.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring midnight-commander-4.8.14.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/midnight-commander/4.8.14: 303 files, 7.4M
bash-3.2$ brew uninstall glib
Uninstalling /usr/local/Cellar/glib/2.46.0... (416 files, 18M)
bash-3.2$ mc
dyld: Library not loaded: /usr/local/lib/libglib-2.0.0.dylib
  Referenced from: /usr/local/bin/mc
  Reason: image not found
Trace/BPT trap: 5
bash-3.2$
```
My expectation is that the uninstall command respects the dependencies unless it's given a special flag (`--nodeps` perhaps). That's how other package managers (dpkg, yum, dnf) behave.

**Comment by dunn** [comment]
I would be in favor of changing the default `brew remove` behavior if it doesn't slow it down a lot; `brew uses --installed recursive glib` takes over 10 seconds for me (though it will be less for people with fewer formulae installed).

**Comment by dunn** [comment]
Actually, `--recursive` shouldn't be needed, and that's slowing it down a lot.

**Comment by dardo82** [comment]
What is the usefulness of a package manager if it doesn't even manage dependencies?

**Comment by tdsmith** [comment]
This would be a big behavior change. `brew doctor` will report uninstalled dependencies.

**Comment by proski** [comment]
True, but so is requiring `--all` for `brew upgrade` (presumable to safety too). Running `brew doctor` means that something bad has occurred already. Save behavior means avoiding that situation in the first place. `brew` in inconsistent here. It checks and install dependencies when installing, but it doesn't check dependencies when uninstalling. Old time users may have used to it, but it was an unpleasant surprise to me.

**Comment by tdsmith** [comment]
FWIW, we abandoned plans to require --all.

**Comment by bfontaine** [comment]
There’s also the `brew missing` command.

**Comment by DomT4** [comment]
And `brew leaves` should tell you what's not being used by anything else.

**Comment by CamJN** [comment]
I think brew leaves isn't always correct though. I have `homebrew/dupes/zlib` and `ossp-uuid` in brew leaves, but if I remove either then stuff stops working. Probably the fault of whatever formula isn't properly listing it's deps but it happens.

**Comment by apjanke** [comment]
This sounds like a good idea to me too, even though it's a change from existing behavior. At least emitting a warning when the uninstallation causes an unsatisfied dependency would be nice. (Including the names of both the dependent and providing formula, so it's clear in the case when uninstalling multiple formulae in a single command.)

Too bad `rm --force` is already used to indicate "all installed versions"; seems like it would be the natural fit for "go ahead and break dependencies.

> I think brew leaves isn't always correct though. I have homebrew/dupes/zlib and ossp-uuid in brew leaves, but if I remove either then stuff stops working.

This may have to do with `:optional` or `:recommended` dependencies when you have formulae which were installed with non-default options. `leaves` may only be looking at the default dependency graph, not your specific installation options.

**Comment by bfontaine** [comment]
> At least emitting a warning when the uninstallation causes an unsatisfied dependency would be nice. (Including the names of both the dependent and providing formula, so it's clear in the case when uninstalling multiple formulae in a single command.)

The downside of this would be that `brew rm` would be much lower because it would need to load *all* formulae to find the ones which depend on the removed ones. We could maybe add an option for that or reuse `--verbose`.

**Comment by mikemcquaid** [comment]
This is something that also applies to other package managers too and given we encourage uninstallation using `rm -rf /usr/local/Cellar/foo` I don't think we can stop people shooting themselves in the foot here. These are warned by `brew doctor` which feels like an acceptable compromise.
