### ISSUE TITLE
Can't install or uninstall Homebrew on OS X 10.11

### ISSUE THREAD

**Issue by amayers** [Homebrew/homebrew#45047]
I am trying to install Homebrew, it had some issues a while back and I stopped being able to use it. Sorry its been a while so I've forgotten what those issues were exactly. So I tried uninstalling it using the `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"` script, then reinstall it. However it always thinks that it is still installed (during installation) but that it is NOT installed (during uninstallation). I am running OS X 10.11 (15A284), and have looked at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md and I have `/usr/local/` and ownership is correct on it. There were a couple strangling files from the last Homebrew install in it, mostly readme and a couple other markdown files. I have tried removing those files just incase they are causing the problem, but that didn't do it. I have the latest Xcode 7.0.1 (7A1001) installed along with the command line tools. 

Any idea what else I should clean up?

https://gist.github.com/amayers/363ab1bc9bcf61318f71

**Comment by DomT4** [comment]
What does `ls -l /usr/local` print?

**Comment by amayers** [comment]
Nothing, `/usr/local` is empty

**Comment by DomT4** [comment]
The specific check the `install` script uses to see whether or not `HOMEBREW_PREFIX` has an existing Homebrew installation is to check the existence of `HOMEBREW_PREFIX/".git"`. Since that directory is hidden it won't show up in a normal `ls -l` but it would with `ls -la /usr/local`.

**Comment by amayers** [comment]
ls -la /usr/local
total 24
drwxr-xr-x   6 amayers  admin  204 Oct 16 16:02 .
drwxr-xr-x@ 11 root     wheel  374 Oct 16 15:52 ..
drwxr-xr-x   3 amayers  admin  102 Oct 12 12:14 .git
-rw-r--r--   1 amayers  admin  462 Sep 18 16:27 .gitignore
-rw-r--r--   1 amayers  admin  793 Oct 12 12:13 .travis.yml
-rw-r--r--   1 amayers  admin  291 Aug 31 11:19 .yardopts

**Comment by DomT4** [comment]
There it is.

```
rm -r /usr/local/.git && rm /usr/local/.gitignore /usr/local/.travis.yml /usr/local/.yardopts
```

**Comment by amayers** [comment]
Thanks, that fixed it

**Comment by DomT4** [comment]
Happy to help! Let us know if you hit anything else.
