### ISSUE TITLE
open-scene-graph failed to build on 10.11

### ISSUE THREAD

**Issue by yetiinabox** [Homebrew/homebrew#45049]
I don't think this is the same issue as issues #43536 or #44524. Oddly, the failure occurs during configuration when searching for socket. I may have inherited something bad from Yosemite; this machine was upgraded rather than going through a clean install.

I'm installing open-scene-graph as a prerequisite for the Scribus CTL build.

Gist filed here: https://gist.github.com/anonymous/783025af0c42665a62c2

Many thanks for any pointers.

**Comment by dunn** [comment]
Same failure for me; and it does look like the same as #44524—at least the gists look the same.

**Comment by dunn** [comment]
Can you try compiling outside of Homebrew and see if the same error occurs

**Comment by yetiinabox** [comment]
Yep, same error exactly.

**Comment by dunn** [comment]
Could you see if the developers are aware of this, and file an issue upstream otherwise? Thanks so much!

**Comment by DomT4** [comment]
Dupe of #44524. Let's centralise discussion there.
