### ISSUE TITLE
GitHub repository not notable enough? 

### ISSUE THREAD

**Issue by dardo82** [Homebrew/homebrew#45065]
I've opened a pull request [here] (https://github.com/Homebrew/homebrew-head-only/pull/172), but it says that [the GitHub repository is not notable enough] (http://bot.brew.sh/job/Homebrew%20Head-Only%20Pull%20Requests/302/version=mavericks/testReport/junit/brew-test-bot/mavericks/audit_homebrew_head_only_uhubctl___strict___online/). 
Then how comes that [this] (https://github.com/Orc/Zzz) and [this] (https://github.com/kylef/wol) are instead in the tap while not being notable the same and even duplicating commands already available in the system?

**Comment by bfontaine** [comment]
Did I answer your question here? https://github.com/Homebrew/homebrew-head-only/pull/172#issuecomment-148914354

**Comment by dardo82** [comment]
You tried, let's talk about it there... 8-)

**Comment by bfontaine** [comment]
> you should regularly remove formulae

That’s the point: we can’t remove formulae because people rely on them. If a formula breaks we’re stuck with it forever (see [homebrew/boneyard](https://github.com/Homebrew/homebrew-boneyard)) and thus have to draw the line somewhere to know what to accept and what not.

Regarding `zzz` and `wol` there are sometimes exception as written in the [docs](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#niche-or-self-submitted-stuff):
> There may be exceptions to these rules in the main repository, we may include things that don't meet these criteria or reject things that do. Please trust that we need to use our discretion based on our experience running a package manager.
I don’t know the reason for these.

**Comment by dardo82** [comment]
Then problem solved,just make an exception. If things will go wrong,you will just move it to the boneyard.

**Comment by DomT4** [comment]
The way you've attacked this issue has been deeply unhelpful. One discussion does not need to be dragged out across one PR, one issue in `head-only`, one issue in Homebrew, and 4 tweets implying there's some sort of conspiracy:

> This can't be the real reason
>  I hope that there is a simple explanation for this.
> You are saying you will not accept something that IS useful and IS working NOW because MAYBE in the medium FUTURE it'll not work. Are you sure it's sensible?
> Anyway i don't buy the premise

Please adhere to the [Code of Conduct](https://github.com/Homebrew/homebrew/blob/master/CODEOFCONDUCT.md) when contributing to Homebrew. Baptiste has spent a chunk of time patiently explaining the issue both here and in `head-only`. 

> Find less arbitrary criteria, so potential contributors can know in advance if their formula will get accepted 

If you read the contributing documents, you'll find we advise auditing Homebrew formula *in advance* with `brew audit --strict --online` which *would* have flagged the failure early on. The [Acceptable Formula](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#niche-or-self-submitted-stuff) guide is documented at that link, and you can find the `audit` instruction in the [Cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#basic-instructions).

> BTW zzz and wol aren't in a better situation about maintenance and updates but they are in the tap

These kinds of situations are precisely why we now have rules in place. We hit problems with accepting basically unmaintained software and then when it goes wrong (and it often does) we're left either maintaining it ourselves or killing it, by which point people may be relying on it. The rules are designed to prevent that sort of situation from happening so frequently.

Baptiste closed the `head-only` PR and I support his decision.

**Comment by dardo82** [comment]
What would have been helpful?

**Comment by DomT4** [comment]
Discussion in the PR, without expecting an instant answer. There are a finite number of maintainers and none of us get paid for this. We have lives/jobs/studies/etc and we can't be everywhere at once. Not floating accusations that there's some conspiracy to reject your package. Not venting at other Homebrew users in Issues who just wanted a question answered. Accepting that it's not impossible for a piece of software to have made mistakes in the past and learned from them. Not continuously ignoring the answers Baptiste has provided and arguing back in quite an aggressive tone.

Not continuing this discussion by tweeting my personal Twitter account:
>  my opinions are not annoyed, are well based and formed. try to be helpful instead of just impeding the conversation.

I don't think it's unreasonable that we ask you to treat maintainers like other human beings and have civil, respectful disagreements without trying to create Shakespearian drama. As I noted in the above reply, Please adhere to the [Code of Conduct](https://github.com/Homebrew/homebrew/blob/master/CODEOFCONDUCT.md) and we'll be able to have discussions on policy issues.

**Comment by dardo82** [comment]
> Discussion in the PR, without expecting an instant answer. 

Your answers are (luckily) quite instantaneous, so this point is invalid.

> There are a finite number of maintainers and none of us get paid for this. We have lives/jobs/studies/etc and we can't be everywhere at once.

This sounds like "Don't bug us. We have a life. Go get a life too." Isn't that aggressive?

> Not floating accusations that there's some conspiracy to reject your package. 

Where do i accuse you of conspiracy? Why you don't use quoting where it's needed?

> Not venting at other Homebrew users in Issues who just wanted a question answered.

If i can't express my views on how Homebrew should work, why i should help with it?
Always remember that YOU are in search of contributors, i am NOT in search of a job.

> Accepting that it's not impossible for a piece of software to have made mistakes in the past and learned from them.

The timing of errors and learning is usually quite suspicious. It's like as you would always end up facing the consequences of errors made by other, that has abused a more relaxed context, and now are paying instead of them. How can i check when you have changed from accepting any request to filtering them?
It's not conspiracy theorization, it's just basic lack of trust, until it's proved i've good reasons not to do it...

> Not continuously ignoring the answers Baptiste has provided and arguing back in quite an aggressive tone.

That is plain wrong. I'm not ignoring the answers, maybe you are doing it...

> Not continuing this discussion by tweeting my personal Twitter account

If you block me here i continue wherever i can.

> I don't think it's unreasonable that we ask you to treat maintainers like other human beings and have civil, respectful disagreements without trying to create Shakespearian drama.

I like Shakespear.

> As I noted in the above reply, Please adhere to the Code of Conduct and we'll be able to have discussions on policy issues.

Obviously any Code of Conduct doesn't allow me to not agree with it, so how can i be free to criticize it?

**Comment by DomT4** [comment]
Sigh. This discussion has been done to death. We aren't accepting your contribution to `head-only` until it meets the minimum requirements, and I'm not going to sit here all day and have to clarify every point to stop it being twisted. When the package is popular enough, we'll consider it. Thank you for your willingness to contribute to Homebrew.

**Comment by mikemcquaid** [comment]
> If you block me here i continue wherever i can.
> Obviously any Code of Conduct doesn't allow me to not agree with it, so how can i be free to criticize it?

You are now blocked from the Homebrew organisation and our Twitter. When you've calmed down and if you want to be unblocked: please send me an email and apologise and I'll consider unblocking you.
