### ISSUE TITLE
Idea: `brew start` for services not loaded with launchctl

### ISSUE THREAD

**Issue by rewritten** [Homebrew/homebrew#45069]
For instance, one installs elasticsearch, or mongodb, or postgresql. Instead of remembering each and every start command (or worse having to start eveything at login), one could do
```
brew start elasticsearch
```
and the same command explained in the final text of `brew info elasticsearch`

```
Or, if you don't want/need launchctl, you can just run:
  elasticsearch --config=/usr/local/opt/elasticsearch/config/elasticsearch.yml
```

would be instead run.

**Comment by dardo82** [comment]
I think that this should be a package manager, not a service manager.

**Comment by bfontaine** [comment]
See [homebrew/services](https://github.com/Homebrew/homebrew-services) for that.

**Comment by rewritten** [comment]
:heart: I did not know about https://github.com/Homebrew/homebrew-services

**Comment by dardo82** [comment]
I didn't know too and as said i think it shouldn't be there, even more so given this PACKAGE MANAGER doesn't manage DEPENDENCIES on uninstall but it manages SERVICES. Who know what will be next...

**Comment by DomT4** [comment]
Please stop venting your annoyed opinions at every person who has a question about Homebrew. I apologise @rewritten.
