### ISSUE TITLE
List outdated formulae separately in `brew update`

### ISSUE THREAD

**Issue by Alhadis** [Homebrew/homebrew#45089]
Recent updates have attempted to highlight outdated brews to users by [adding coloured highlights](https://github.com/Homebrew/homebrew/pull/44335), which [didn't play too well](https://github.com/Homebrew/homebrew/issues/45028) with some terminal colour schemes.

Currently, any installed formulae that're affected by `brew update` are displayed in bold with ` (installed)` appended. While a lot easier on the eyes than white-against-yellow, it adds clutter to the feedback - and some users probably aren't that quick to notice the bold letters.

I suggest simply listing affected formulae after the updates:
![1](https://cloud.githubusercontent.com/assets/2346707/10563252/8ce53528-75ce-11e5-8ca1-053fcaa7bfc7.png)
Ignore what's listed in the example, I had to improvise with makeshift feedback, since all my brews are currently up-to-date. Heh.

Thoughts?

**Comment by mikemcquaid** [comment]
Can you confirm what you've changed here, I'm not totally sure. Thanks!

**Comment by Alhadis** [comment]
Well, there's the addition of this at the bottom:
```
==> Outdated Formulae
emscripten (1.34.0 < 1.34.12)
clojurescript (1.7.13 < 1.7.145)
  2 installed formulae require updates
```
Instead of relying on something like bold text to draw a user's attention to outdated modules, it's probably better to list them explicitly, as though the user themselves had typed in `brew outdated` after updating. :)

**Comment by mikemcquaid** [comment]
Basically just running `brew outdated` does make sense to me.

**Comment by bfontaine** [comment]
What does the output look like for revision bumps?

Also I’m not sure about the wording of “2 installed formulae require updates”; they don’t *require* updates per se; you’re free to keep the version you have forever.

**Comment by Alhadis** [comment]
Haha, true, I think "`can be upgraded`" would drill it down nicely. :)

As for revision bumps, well... if the version is the same, you can drop the version diff altogether:

```
==> Affected Formulae
emscripten (1.34.0 < 1.34.12)
clojurescript
  1 installed formula can be upgraded
```

Now I'm thinking that `Affected Formulae` might be a more fitting title, since not every formulae that's affected will be outdated (given the possibility of revision bumps).

**Comment by UniqMartin** [comment]
> Basically just running `brew outdated` does make sense to me.

There are people, who frequently run `brew update` to stay on top of Homebrew updates, but don't immediately follow up with `brew upgrade`. The output of `brew outdated` (if incorporated into `brew update`) would easily become long and thus annoying.

I'd say `brew update` and `brew outdated` serve two different purposes:

- `update`: Compare `Library/Formula/` (and taps) before and after update.
- `outdated`: Compare `Cellar/` with `Library/Formula/` (at the current local HEAD).

> What does the output look like for revision bumps?

There's nothing special about revision bumps. They are treated as regular updates, e.g.:

```
$ brew outdated
qt5 (5.5.1 < 5.5.1_1)
```

If a formula has no version or revision bumps, it will neither be listed by `brew update` nor `brew outdated`.

**Comment by Alhadis** [comment]
> The output of brew outdated (if incorporated into brew update) would easily become long and thus annoying.

Well, it'd make more sense to only list the brews that've been affected by the most recent update.

**Comment by UniqMartin** [comment]
If that's what gets printed, then I see value in that. I'd suggest naming this section `Updates to Installed Formulae` (or similar) to make that clearer. I think the formatting would also need to be different from `brew outdated` to make that clearer. Here's a quick suggestion:

```
==> Updates to Installed Formulae
ffmpeg (2.8.1 -> 2.8.1_1; 2.8, 2.81 installed)
youtube-dl (2015.10.13 -> 2015.10.16; 2015.09.28 installed)
```

**Comment by Alhadis** [comment]
Wait. I noticed that `brew search` also highlights installed formulae in the same manner.

Since my proposed change would introduce a discrepancy between the feedback that each command generates, perhaps it'd be better to denote the highlighted brews with a tick?

I'm just throwing ideas on the table now, because this just looks plain messy:
![0](https://cloud.githubusercontent.com/assets/2346707/10571204/8b35fc98-7688-11e5-9e11-2097d94ddb5c.png)

Short and sweet is usually best, I say:
![1](https://cloud.githubusercontent.com/assets/2346707/10571310/cfa4db0a-7689-11e5-89e4-1cb15b223fb4.png)

Personally, I find it easier to distinguish installed brews from uninstalled brews this way. For formulae that're aligned to the left, we can simply indent the first column so the left-edges of each brew's name lines up nicely:

![2](https://cloud.githubusercontent.com/assets/2346707/10571382/61d909ba-768a-11e5-965d-e5273e0e0fad.png)

Thoughts? :)

**Comment by xu-cheng** [comment]
If we want to make highlight more visible, some random ideas:
* Use bold + underline, which should draw more attention than boldface only.
* Use user's `LSCOLORS`, so we don't need to deal with the difference between everyone's color scheme.

**Comment by mikemcquaid** [comment]
Note we have bold and `installed`. I think that's more than enough. That said, I don't mind using underline. The tick doesn't really work because at a glance it's not clear which column it applies to.

**Comment by Alhadis** [comment]
> The tick doesn't really work because at a glance it's not clear which column it applies to.

Hrm, true, it's probably not as apparent when the columns are closer together... what about this, then?
![3](https://cloud.githubusercontent.com/assets/2346707/10574099/8a29b6f2-769f-11e5-81f9-cd650995cf0a.png)

Sorry if I'm looking too far into this.

**Comment by mikemcquaid** [comment]
No, it's good to think about this stuff! When I suggested the green ticks before I was shot down pretty hard so I think it's worth keeping it as highlighted text with a label.

**Comment by Alhadis** [comment]
Aye, but a label adds clutter, and nobody likes clutter (unless they have some digitally-infused hoarding disorder).

We could also go with this:
<img width="443" alt="screen shot 2015-10-19 at 10 01 18 pm" src="https://cloud.githubusercontent.com/assets/2346707/10576163/f3a84a0a-76ac-11e5-8ffd-40a72301bf50.png">

Can't speak for other users, but bold type doesn't always look too legible, depending on the typeface a user's picked for their terminal emulator.

**Comment by mikemcquaid** [comment]
I do agree about the clutter but the balance is against usability. What does a tick, bold or underline mean?

**Comment by Alhadis** [comment]
Well, the last line that's added to the feedback in the figure above disambiguate the tick's meaning. :) A tick placed beside "2 installed formulae can be updated", copied next to two different formulae names... well, it appears quite clear to me.

**Comment by UniqMartin** [comment]
Several people have suggested to use underlining for highlighting. Please don't! It's a mode of highlighting carried over from pen and paper, where there are very few alternatives. On a computer screen there is color, boldface, italics, and probably more. The former don't hurt legibility if used sparingly, but underlining always does. (That much I learned when I dabbled with typography. Just think for a second why Markdown has no syntax for underlining.)

**Comment by Alhadis** [comment]
Markdown has no syntax for a lot of things, mate, let's not go down that road... xD

> On a computer screen there is colour, boldface, italics, and probably more.

Yes, but in a terminal emulator, the range of formatting choices become a lot more limited than what you're free to use in Photoshop or in CSS. Underlining has the benefit of clarity: not every typeface looks good rendered in bold...

**Comment by UniqMartin** [comment]
> Yes, but in a terminal emulator, the range of formatting choices becomes a lot more limited than what you're free to use in Photoshop or in CSS.

Sure, we can't change size, spacing, and many other things. But still *there are* more options than just underlining.

> Underlining has the benefit of clarity: not every typeface looks good rendered in bold...

I don't think we should try to compensate for a bad font choice by the user. If the bold font looks bad, just change it. There so many good options nowadays. Also, at least my terminal emulator allows me to ignore the boldface or to remap it to a slightly different color palette (so it still stands out without being bold).

**Comment by mikemcquaid** [comment]
Let's discuss this in https://github.com/Homebrew/homebrew/pull/45131
