### ISSUE TITLE
SQLite v3.9.1 Available…

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew#45080]
Yeah, I know they just released 3.9._0_ a few days back, but it happened.  I would have opened a pull request instead of just notifying you guys about this, but I don't know where you guys get all the checksums.

**Comment by bfontaine** [comment]
> but I don't know where you guys get all the checksums.

We download software and compute the checksums from it :smile: 

e.g. `curl -sL https://the-software-you/want.tgz | shasum -a 256`

**Comment by RandomDSdevel** [comment]
@bfontaine:  Oh, OK!  Thanks!
