### ISSUE TITLE
postgresql.rb syntax error

### ISSUE THREAD

**Issue by cvickery** [Homebrew/homebrew#45097]
vickery@babbage [~]
$ brew gist-logs postgresql
Error: /usr/local/Library/Formula/postgresql.rb:37: syntax error, unexpected <<, expecting keyword_end
<<<<<<< HEAD
  ^
/usr/local/Library/Formula/postgresql.rb:53: syntax error, unexpected >>, expecting keyword_end
>>>>>>> 530b5e4f548fae1645ec30bbc1bacb165f161780
  ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:205:in `factory'
/usr/local/Library/Homebrew/formulary.rb:224:in `from_rack'
/usr/local/Library/Homebrew/extend/ARGV.rb:37:in `block in resolved_formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:27:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:27:in `resolved_formulae'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:134:in `gist_logs'
/usr/local/Library/brew.rb:133:in `<main>'
vickery@babbage [~]
$

**Comment by mikemcquaid** [comment]
`cd /usr/local; git reset --hard origin/master` should fix this.

**Comment by cvickery** [comment]
That was fast!
Issue resolved ... many thanks.
