### ISSUE TITLE
Possible to show homepage url instead of opening it?

### ISSUE THREAD

**Issue by kevintraver** [Homebrew/homebrew#45115]
Is it possible to just show the homepage for a specific formula instead of using the `home` command to open it?

I know homebrew cask has something like `brew cask _stanza homepage`.

**Comment by dunn** [comment]
`brew info` includes the homepage. Are you trying to get the homepage by itself, as input to something else?

**Comment by kevintraver** [comment]
Yes, is there a way to just get only the homepage?

**Comment by bfontaine** [comment]
There’s no direct way. If you have `jq` you can use the following:
```
brew info --json=v1 <formula> | jq -r '.[0].homepage'
```

**Comment by kevintraver** [comment]
Ok, thanks.
