### ISSUE TITLE
cleanup removes keg-only brews without --force

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew#45122]
```
tim@rocketman:~$ brew cleanup
Removing: /usr/local/Cellar/sqlite/3.9.0... (9 files, 2.8M)
```

man page says:
> By default, does not remove out-of-date keg-only brews, as other software may link directly to specific versions.

It seems like this code in `eligible_for_cleanup?` does actually remove out-of-date keg-only brews if it's deemed safe, i.e. all depending formulas would have been built against the opt symlink: https://github.com/Homebrew/homebrew/blame/master/Library/Homebrew/cmd/cleanup.rb#L161-L178

So I guess this is a documentation bug?

**Comment by mikemcquaid** [comment]
> So I guess this is a documentation bug?

Yeh, seems worth just fixing the docs rather than the behaviour.

**Comment by kpearson** [comment]
This is solved. The issue should be closed.

**Comment by tdsmith** [comment]
Indeed, the manpage no longer says that. Thanks for the nudge!
