### ISSUE TITLE
gocd

### ISSUE THREAD

**Issue by rhacker** [Homebrew/homebrew#45123]
gocd is a great alternative to jenkins, I think it would be great that we have gocd in homebrew.

**Comment by DomT4** [comment]
It meets the minimum requirements comfortably, glancing at the Github repo. We'd be happy to review a PR, if you'd like to file one.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by rhacker** [comment]
Thanks for the guide. I can write one, but I'm not sure that I could be active on keeping it up to date. I guess I can close this for now.

**Comment by mikemcquaid** [comment]
@rhacker You don't need to keep it up to date. Others may do so.
