### ISSUE TITLE
install libpng 404

### ISSUE THREAD

**Issue by foxinmy** [Homebrew/homebrew#45138]
[w3af] brew install libpng                                22:01:48  ☁  maste
==> Downloading https://downloads.sf.net/project/libpng/libpng16/1.6.13/libpng-1

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "libpng"
Download failed: https://downloads.sf.net/project/libpng/libpng16/1.6.13/libpng-1.6.13.tar.xz

**Comment by DomT4** [comment]
Your Homebrew is out-of-date. Please `brew update` and try again. Current version is [quite a bit later](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libpng.rb#L5-L6) than `1.6.13`.

**Comment by DomT4** [comment]
Closing per the above but let us know if that doesn't solve the issue for some reason. Thanks!
