### ISSUE TITLE
suggestion: Homebrew for windows

### ISSUE THREAD

**Issue by mgracer48** [Homebrew/homebrew#45144]
I bet this will make windows users lives easier

**Comment by DomT4** [comment]
There used to be [this fork](https://github.com/nddrylliog/homebrew-mingw) which was aimed at Windows, but it hasn't been updated in a long time.

None of us, to my knowledge, use Windows as our daily driver and consequently maintaining a fork ourselves would be difficult. The license is BSD so anyone is freely welcome to fork Homebrew and start a Windows version if they wish. If it was frequently updated and maintained we'd be happy to point to it in our `Interesting-Taps-&-Branches` documentation.

**Comment by mgracer48** [comment]
oh ok ill keep this open incase someone wants to continue this idea

**Comment by DomT4** [comment]
I'm afraid there's not much use to keeping it open on the Issue Tracker; We get a lot of feature requests and issues each day and they quickly get buried on the tracker and never found again :cry:. Will have to close here, but if anyone does create a Windows fork that's maintained we'd be happy to point Windows-using folk towards it :)

**Comment by The-Compiler** [comment]
FWIW there's [Chocolatey](https://chocolatey.org/) which is somewhat similar for Windows.
