### ISSUE TITLE
Trying to write formular for `xidel`

### ISSUE THREAD

**Issue by moeffju** [Homebrew/homebrew#45142]
I’ve read through Acceptable Fomulae, the Formula Cookbook, and the How To, but I’m struggling with an apparently much simpler task: Writing the actual formula code.

The tool in question is called *Xidel*, a command-line tool to download and extract data from structured pages (HTML, XML, JSON). It basically allows running arbitrary selectors on documents and it’s super useful on the shell. Unfortunately, it’s written in Pascal using Lazarus/FreePascal, and I cannot figure out how to encode those dependencies. Here’s what I have so far, with comments added for clarity:

```
class Xidel < Formula
  desc "Xidel is a command line tool to download and extract data from HTML/XML pages as well as JSON APIs."
  homepage "http://www.videlibri.de/xidel.html"
  url "https://downloads.sourceforge.net/projects/videlibri/files/Xidel/Xidel%200.9/xidel-0.9.src.tar.gz"
  sha256 "2496f4b3646561d9ba7f4b598dd8d01f59110ae988e4752bc0e70f976a045115"

  # this dependency does not yet exist in homebrew, only in brew-cask
  depends_on 'lazarus' => :build
  # this exists but is not sufficient
  depends_on 'fpc' => :build

  def install
    # this fails because the dependencies are not satisfied. it works if one manually installs Laz, FP, and FPSSRC.
    system "lazbuild", "-d", "--os=darwin", "--cpu=x86_64", "xidel.lpi"
    system "strip", "--strip-all", "xidel"
    # there is an install.sh, but it’s essentially just a cp, so I’d do that manually here?
  end

  test do
    # xidel comes with a bunch of tests in the source tarball that I’d like to reuse
    # the below doesn’t work because the test directory is pristine. what’s the best way to go here?
    system "./tests/test.sh"
  end
end
```

Do you have any pointers on how to go from here? I couldn’t find any other formulae using Lazarus as a reference.

**Comment by moeffju** [comment]
There is a pre-built OS X executable that is probably the easiest route to take, but I suppose that would have to go into the cask repository?

**Comment by bfontaine** [comment]
If the only thing you’re missing is a dependency you can write a formula for it.

> there is an install.sh, but it’s essentially just a cp, so I’d do that manually here?

If `system "./install.sh"` works use it instead of manual installing.

> xidel comes with a bunch of tests in the source tarball that I’d like to reuse

You can’t. However you can run the tests at the end of the build (in `def install`). `test do` is not meant for unit tests; something like the following should be ok:
```rb
(testpath/"test.html").write <<-EOS.undent
    <!doctype html>
    <html>
    <head></head>
    <body><p class="x">foobar</p></body>
    </html>
EOS
# I don’t know how `xidel` works; this is just an example test
assert_equal "foobar", shell_output("#{bin}/xidel p.x test.html")
```

**Comment by DomT4** [comment]
> There is a pre-built OS X executable that is probably the easiest route to take, but I suppose that would have to go into the cask repository?

Or `homebrew/homebrew-binary` aye.

> If the only thing you’re missing is a dependency you can write a formula for it.

Or since they're both `:build` deps you could vendor them into the `buildpath` here and then `prepend` the `$PATH` in the formula, and then the user won't actually have to keep them on the system.

**Comment by moeffju** [comment]
@bfontaine Thanks!

@DomT4 As far as I can tell, Lazarus actually needs to be installed (it’s basically an open-source clone of Delphi, the visual Object Pascal IDE). I’ll look into that though.

**Comment by DomT4** [comment]
> As far as I can tell, Lazarus actually needs to be installed 

Ah, not a `:build` dep exclusively then?

**Comment by moeffju** [comment]
Well, it's not required after installation. It's just a builder/IDE thing.




On Mon, Oct 19, 2015 at 8:19 AM -0700, "Dominyk Tiller" <notifications@github.com> wrote:













As far as I can tell, Lazarus actually needs to be installed 




Ah, not a :build dep exclusively then?

**Comment by DomT4** [comment]
Please let us know if we can help further here, Thanks!
