### ISSUE TITLE
A couple questions about improving a formula

### ISSUE THREAD

**Issue by CamJN** [Homebrew/homebrew#45151]
How can I ignore ranlib complaining that a library has no symbols?

When building freeswitch (on every version of OSX i've tried this on 10.6, 10.10, and 10.11), make fails every time it tries to link libspandsp or libsophia-sip-ua because they have no symbols. Apparently this isn't a problem for upstream (https://freeswitch.org/bamboo/browse/FS-TMBO-JOB1-10;jsessionid=AA19A4240CB24416F29F97CF469197D7). I was just wondering how to shut ranlib up? Or continue the build regardless of these messages?

My other question is where would be a good place to move the conf and sounds dirs? 

As is upgrading freeswitch in homebrew is a massive pain, involving installing the new version and recursively diffing against the old version to figure out what parts of your conf to copy over. And duplicating the massive sounds dir every time you upgrade makes me sad, (bandwidth and disk space).

I'm working on adding some options to the formula to add some modules that (I would think) a lot of users would want (the phone-directory and text-to-speech modules) and I will address these other problems at the same time if I can.

**Comment by CamJN** [comment]
Apparently the symbols problem is relate to statically linking libraries in osx: http://stackoverflow.com/questions/4929255/building-static-libraries-on-mac-using-cmake-and-gcc though I don't know how to change the cmake config per the given suggestions as there are no link.txt files that I can see.

Looking at postgres I think that I'd probably be best off doing something like put the conf/sounds/grammar/certs/scripts/recordings/storage/cache dirs in #{share}/#{name}/ on install and every update. And copy them to ${var}/#{name}/ on install (or if they're missing). But I don't know for sure and would appreciate some feedback.

**Comment by mikemcquaid** [comment]
If a library has no symbols: that's a problem.

The configuration directory should be installed with `etc.install` which means it'll persist across upgrades.

**Comment by mikemcquaid** [comment]
A cache directory should probably be somewhere under `var`.

**Comment by mikemcquaid** [comment]
(which will also persist on upgrades)

**Comment by CamJN** [comment]
Any ideas how the package building server building might be succeeding in building the package then? I can't test anything until I figure out why it won't build locally. I looked and didn't see a CI build for the last formula update so I didn't get anything that way.

**Comment by mikemcquaid** [comment]
I'm not sure how they might differ, sorry.

**Comment by mikemcquaid** [comment]
If you create a pull request to modify some of this stuff I guess you'd see?

**Comment by CamJN** [comment]
So I made a PR with just the options added for now. Will Travis cycle through the options? B/c the first build it's doing is w/o any options applied so it's (I think) not actually testing the changes?

**Comment by CamJN** [comment]
Well I guess I'll see what the jenkins server does...

**Comment by CamJN** [comment]
Submitted with options as opt-out for the build, will reverse for final pull if people want.

**Comment by CamJN** [comment]
Ok so travis can't build it either. https://travis-ci.org/Homebrew/homebrew/jobs/86448463

**Comment by CamJN** [comment]
Raised the issue with upstream. https://freeswitch.org/jira/browse/FS-8367

**Comment by DomT4** [comment]
Closing in favour of #45191.
