### ISSUE TITLE
Evince won't open any file

### ISSUE THREAD

**Issue by mistguy** [Homebrew/homebrew#45168]
After I installed evince and djvulibre, I opened evince and navigate to my pdfs. However, none of them is shown by evince with options "all documents". If I choose "All files" and click on one of the pdfs, evince won't open it. The error message was application/octet-stream type is not supported. Did I miss something?

**Comment by dunn** [comment]
Can you try installing Evince outside of Homebrew, to make sure this isn't a more general problem? Thanks!

**Comment by mistguy** [comment]
I am afraid I will mess up my mac if I do so. Anyway, does evince work for you?

**Comment by dunn** [comment]
I haven't tried yet, and libspectre is failing to build for me so I need to figure that out first.

**Comment by dunn** [comment]
OK, I can reproduce this.

**Comment by dunn** [comment]
I'm afraid I haven't had time to look into this more; if you could check upstream bug reports to see if this is a known non-Homebrew issue, that'd be great.  Also cc @tschoonj for his expertise.

**Comment by tschoonj** [comment]
I am afraid I cannot reproduce this on my system running Yosemite. Everything seems to be working fine here.

If you run `file yourfile.pdf` on the command-line, is it properly recognized as a PDF?

**Comment by dunn** [comment]
Maybe it's an El Capitan issue, then.

**Comment by mistguy** [comment]
```
macbook:Mathematics chongwang$ file Basic\ Topology-Armstrong-UTM.pdf 
Basic Topology-Armstrong-UTM.pdf: PDF document, version 1.6
```
It is properly recognized.

**Comment by gui-dos** [comment]
I solved this issue by installing `shared-mime-info` and executing the command
`update-mime-database /usr/local/share/mime`

**Comment by tschoonj** [comment]
I just installed `evince` on a vanilla El Capitan and I can open pdfs without problems, even without running `update-mime-database`.

@mistguy is your Homebrew installation by any chance not in /usr/local?

**Comment by mistguy** [comment]
@tschoonj, I can confirm homebrew is in /usr/local and `update-mime-database` solved my problem

**Comment by mistguy** [comment]
By the way, is there a way to using evince for default in finder. That is, evince will be automatically invoked by double clicking a pdf in finder.

**Comment by dunn** [comment]
@tschoonj would it be appropriate for `shared-mime-info` to be a dependency, and run `update-mime-database` post-install?

**Comment by yig** [comment]
I had this same problem on 10.11.2. I can also confirm that `brew install shared-mime-info` followed by `update-mime-database /usr/local/share/mime` solved the problem for me.

**Comment by tschoonj** [comment]
Sorry, forgot completely about this!

I opened a PR that adds `update-mime-database` to the `post_install` step...
