### ISSUE TITLE
libjson-rpc-cpp bottle not compatible with one of it's dependencies.

### ISSUE THREAD

**Issue by debris** [Homebrew/homebrew#45169]
## Problem

[libjson-rpc-cpp](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libjson-rpc-cpp.rb) depends on [jsoncpp](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/jsoncpp.rb). 

Old versions of jsoncpp used to install includes in `jsoncpp/json/`, whereas new install them in `json/`. *libjson-rpc-cpp* handles backwards compatibility during cmake phase. The problem is that current bottles for *libjson-rpc-cpp* are built with old version of *jsoncpp*. This introduces following error when I try to use *libjson-rpc-cpp* from my project:

`
/usr/local/include/jsonrpccpp/common/jsonparser.h:13:10: fatal error: 'jsoncpp/json/json.h' file not found
`

As a temporary fix I built libjson-rpc-cpp from source:

```
brew install --build-from-source libjson-rpc-cpp
```

## Possible solution

Reinstall jsoncpp on all slaves and rebuilt all bottles from `libjson-rpc-cpp`.

---

downstream issue: https://github.com/ethereum/homebrew-ethereum/issues/41
ping @cinemast (owner of `libjson-rpc-cpp`)

**Comment by cinemast** [comment]
@debris thank you for reporting this. As you already pointed out, a rebuild should suffice to solve this issue. There is nothing on my side I can do I guess.

**Comment by mikemcquaid** [comment]
> rebuilt all bottles from libjson-rpc-cpp.

Have queued a job to do this: http://bot.brew.sh/job/Homebrew%20Testing/908/

**Comment by debris** [comment]
I see that build finished few days ago, but [libjson-rpc-cpp](https://github.com/Homebrew/homebrew/commits/master/Library/Formula/libjson-rpc-cpp.rb) formula was not updated. I'm not familiar with jenkins, so I can't tell what has happened. @mikemcquaid can you help me?

**Comment by mikemcquaid** [comment]
@debris Apologies for the delay!

**Comment by debris** [comment]
thanks!
