### ISSUE TITLE
version extraction fails for Hypre

### ISSUE THREAD

**Issue by davydden** [Homebrew/homebrew#45161]
subj.

Here's what Homebrew does
```
==> Downloading http://ftp.mcs.anl.gov/pub/petsc/externalpackages/hypre-2.10.0b-p2.tar.gz
Already downloaded: /Library/Caches/Homebrew/hypre-2.tar.gz
==> ./configure --prefix=/usr/local/Cellar/hypre/2
```
as you see it's `2` instead of `2.10.0b`.

**Comment by davydden** [comment]
the worst is that it keeps re-installing `hypre` when installing any formulae which uses it even when one specifies `version "2.10.0b"`. @dpo any ideas?

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/homebrew-science#2916
