### ISSUE TITLE
pulseaudio failed to build on 10.11

### ISSUE THREAD

**Issue by MoritzFago** [Homebrew/homebrew#45166]
https://gist.github.com/0f2bcecb5f275a1ff062

**Comment by bfontaine** [comment]
Seems similar to #18199. Quoting Misty:

Do you have Xcode installed, or CLT only?

**Comment by gaming-hacker** [comment]
same with xcode 7.1, pulse audio v 7.0 doesn't build
pulse audio v6.0 does build, probably patches are wrong

**Comment by hermo** [comment]
I had the same problem. Installing CLT fixed the issue.
> OS X: 10.11.2-x86_64
> Xcode: 7.2
> CLT: 7.2.0.0.1.1447826929

**Comment by gaming-hacker** [comment]
which CLT?  i tried the new swift build as well as with CLT

**Comment by bfontaine** [comment]
@gaming-hacker Please post the output of `brew gist-logs pulseaudio`

**Comment by mistydemeo** [comment]
The error is here:

```m4
# Darwin/OS X
if test "x$os_is_darwin" = "x1" ; then
    AC_MSG_CHECKING([looking for Apple CoreService Framework])
    # How do I check a framework "library" - AC_CHECK_LIB prob. won't work??, just assign LIBS & hope
    AC_CHECK_HEADER([/Developer/Headers/FlatCarbon/CoreServices.h],
        [LIBS="$LIBS -framework CoreServices"],
        [AC_CHECK_HEADERS([/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h],
            [LIBS="$LIBS -framework CoreServices"],
            [AC_MSG_ERROR([CoreServices.h header file not found])]
        )]
    )

    AC_MSG_RESULT([ok])
    AC_DEFINE([HAVE_CLOCK_GETTIME], 1, [Using clock_gettime() replacement])
    HAVE_BONJOUR=1
fi
```

Which hardcodes the header path to the pre-Xcode 4.3 location. It works with the CLT installed since the CLT installs headers there, but it won't check in the Xcode SDK.

**Comment by mistydemeo** [comment]
Looks like this was filed by Adam [back in 2012](https://bugs.freedesktop.org/show_bug.cgi?id=55152); Macports [patched it](https://trac.macports.org/browser/trunk/dports/audio/pulseaudio/files/patch-configure.ac-coreservices.diff) seven months ago.

**Comment by gaming-hacker** [comment]
Nice work, can you also update the formulat to 7.1?  6.0 is very old.

**Comment by mistydemeo** [comment]
I have a PR for it in #47616.
