### ISSUE TITLE
Installing OpenCV for python

### ISSUE THREAD

**Issue by theasder** [Homebrew/homebrew#45188]
Wrote in terminal and got following error:

    $ brew install opencv
    Error: undefined method `desc' for Formulary::Formulae::Opencv:Class

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by theasder** [comment]
Ok, I have a question: how to install OpenCV on Python 3? `brew install opencv` only works for Python 2.

**Comment by tdsmith** [comment]
You should use opencv3 and you should install it with --with-python3.
