### ISSUE TITLE
Trouble Creating Diff for Tmux 2.1 Patch

### ISSUE THREAD

**Issue by indiesquidge** [Homebrew/homebrew#45217]
The Tmux 2.1 update [broke](https://github.com/tmux/tmux/issues/150) a few things that I regularly use, and I would like to create my own patch/diff for my installed package.

I have been reading about creating [patches](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#creating-the-diff), but I don't know if I fully understand what to do with this diff to fix the issue. I have created the diff, but every time I run 

```sh
brew install --interactive --git tmux 
```
make the [diff changes](https://github.com/tmux/tmux/issues/150#issuecomment-149466158), and 
```sh
git diff >> /usr/local/Library/Formula/tmux.rb 
```
I get `Error: Empty installation` when I `exit`, and the package is nowhere to be found. What am I missing that is causing this issue?

I have downloaded the Tmux 2.0 tar file and gotten that to work manually based on `Tmux`'s [readme](https://github.com/tmux/tmux/blob/master/README), but I would rather use `Homebrew` to install `tmux 2.1` and patch this one thing. Any help would be appreciated.

**Comment by bfontaine** [comment]
The `brew install --interactive --git tmux` is used to _create_ the diff; if you already have one you don’t need this.

At the end of the formula add a line with `__END__` followed by the patch. See an example [here](https://github.com/Homebrew/homebrew/blob/8c6777b2b8e847d5f2b447eae532fa8ecffa6467/Library/Formula/aview.rb#L20).

Then at the top of the formula, before `def install`, add `patch :DATA`. You can then try to `brew install tmux`. If it works, add a comment above `patch :DATA` explaining why it’s necessary and submit a PR :wink:

**Comment by indiesquidge** [comment]
@bfontaine, ah, that makes sense. Thank you for explaining. Unfortunately, after I created the correct [diff](https://gist.github.com/indiesquidge/19a3da8258655c2814b4) and installed `tmux`, I am still having the issue :(

I'm guessing it's a problem with the diff itself and not the patch?

**Comment by indiesquidge** [comment]
@bfontaine, so I got it to work with `brew install --build-from-source tmux`. I will update the file with a comment on the patch and create a PR. Thank you for your help :)

**Comment by bfontaine** [comment]
:+1: :smile:
