### ISSUE TITLE
Brew update stashes changes even after hard reset

### ISSUE THREAD

**Issue by claudiocabral** [Homebrew/homebrew#45210]
Hi, I'm on os x 10.11.5 el Captain and whenever I run `brew update` it outputs stashing of files and then restoring them, even though I never changed anything and even did a `cd $(brew --repository) && git reset --hard origin/master` and `git status` shows that I've got a clean state.
I thought it might be a problem with my machine but found others with a similar problem:
http://stackoverflow.com/questions/31492241/brew-update-broken-it-outputs-stashing-log

`brew update` works, but this slows it down a lot.

**Comment by mikemcquaid** [comment]
Can you paste the output you see in a Gist (https://gist.github.com)?

**Comment by claudiocabral** [comment]
here you go:
https://gist.github.com/claudiocabral/448823a3fd1e7422786c

2015-10-21 13:07 GMT+02:00 Mike McQuaid <notifications@github.com>:

**Comment by mikemcquaid** [comment]
Run `for i in /usr/local/Library/Taps/*/*; do echo git reset --hard origin/master; done`

**Comment by claudiocabral** [comment]
Exaclty the same output from `brew update` after running that

**Comment by mikemcquaid** [comment]
Sorry, pasted the wrong thing, try:
`for i in /usr/local /usr/local/Library/Taps/*/*; do cd $i; git reset --hard origin/master; done`

**Comment by claudiocabral** [comment]
That did it, thanks! Any idea why the taps had changes?

**Comment by mikemcquaid** [comment]
If you didn't modify them intentionally: no idea, I'm afraid. We should maybe make a command that makes it easy to reset all these changes.
