### ISSUE TITLE
pass for osx needs a patch

### ISSUE THREAD

**Issue by tristan-k** [Homebrew/homebrew#45212]
There are some issues with pass and the [firefox plugin passff](https://github.com/jvenant/passff) which are described [here](https://github.com/jvenant/passff#issues-with-os-x).

> If you're still having trouble, it may be due to a bug present in version 1.6.5 and earlier of pass. From your shell, check the output of ````pass list````. If the passwords listed end with ````.gpg````, then your version of pass contains the bug. The bug was fixed in [this commit](http://git.zx2c4.com/password-store/commit/?id=a619988f7986d72f4e0ac7256ce48596df6a2a34). You must update your version of ````pass```` or manually apply [this patch](http://git.zx2c4.com/password-store/patch/?id=a619988f7986d72f4e0ac7256ce48596df6a2a34) to the pass script on your machine.  Once ````pass list```` lists passwords with the ````.gpg```` stripped off, the plugin should work!

    $ brew list | grep pass
    pass
    $ which pass
    /usr/local/bin/pass
    $ brew info pass
    pass: stable 1.6.5 (bottled), HEAD
    Password manager
    http://www.passwordstore.org/
    /usr/local/Cellar/pass/1.6.5 (27 files, 176K) *
    Poured from bottle
    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/pass.rb
    $  pass list
    Password Store
    ├── HTTP
    │   └── googlemail.gpg
    └── test.gpg

@zeckalpha @mikemcquaid @adzenith @xu-cheng Please update to the latest git-version or apply the patch. Thanks!

**Comment by bfontaine** [comment]
Would you mind making a pull-request? This should help and I’m happy to answer any question you might have:
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

**Comment by zeckalpha** [comment]
According to [the pass repo](http://git.zx2c4.com/password-store/), it looks like there's not been a release upstream since 1.6.5. You should be able to use brew to install from from the git repo's head (which should include the patch) by:

     brew remove pass
     brew install pass --HEAD

If this works, please close this issue.

**Comment by dunn** [comment]
If `HEAD` builds, we should try to backport a patch.

**Comment by zeckalpha** [comment]
Upstream's mailing list is pretty responsive. I'll post this there and try to get a release cut. More sustainable than including patches in brew, no?

**Comment by zeckalpha** [comment]
http://lists.zx2c4.com/pipermail/password-store/2015-October/001796.html

**Comment by dunn** [comment]
Thanks!

**Comment by DomT4** [comment]
Apparently we're not going to get a quick answer here. Would someone mind backporting the patch in the mean time?

**Comment by DomT4** [comment]
Closing here. We'd welcome either a new release or a backport, if either emerged.

**Comment by zeckalpha** [comment]
New release in the next week or two: https://lists.zx2c4.com/pipermail/password-store/2016-February/002022.html
