### ISSUE TITLE
no config.log created?

### ISSUE THREAD

**Issue by ckalas** [Homebrew/homebrew#45221]
Trying to install a package which fails during make (OSX 10.11):

configure: error: C preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details.
make[1]: *** [configure-target-libgcc] Error 1
make: *** [all] Error 2

I can't seem to find config.log anywhere there, not using locate and not in ~/Library/Logs/Homebrew.

**Comment by tdsmith** [comment]
Install with `-d` and then choose `shell` from the menu that pops up on failure and you'll be able to browse the source tree before it gets cleaned up.

**Comment by ckalas** [comment]
Thanks the log file is there now.
