### ISSUE TITLE
squirrel-sql formula request

### ISSUE THREAD

**Issue by rwhogg** [Homebrew/homebrew#45239]
I would like to see squirrel-sql (http://www.squirrelsql.org/) packaged for Homebrew.

I have already started work on it - see my work-in-progress branch at https://github.com/rwhogg/linuxbrew/tree/squirrel-sql .

I apologize if it takes a while to complete, it has a bit of a quirky build system. Any assistance is welcome.

**Comment by bfontaine** [comment]
Do you want to package squirrel-sql for Homebrew or Linuxbrew?

**Comment by bfontaine** [comment]
In any case you should open a pull-request on the relevant repo so we can help you write the formula.

**Comment by rwhogg** [comment]
Homebrew - but as I'm developing on Linux I figured it would be easiest to push to my Linuxbrew fork while developing and only copy the formula over to Homebrew when it came time to submit the PR. Do you have a better workflow in mind? Sorry, I'm still new to Homebrew development.

**Comment by bfontaine** [comment]
If the only machine you have access to is running Linux you don’t really have the choice. :smile:
Why do you want to submit this to Homebrew if you’re running Linuxbrew? You should probably first submit to Linuxbrew to ensure you have something that work and then import it into Homebrew.

The issue I see here is that if you make a pull-request to Homebrew and that something OS X-specific fails in the CI you won’t have any way to reproduce it on your machine and it’ll be harder for us to help you.

**Comment by rwhogg** [comment]
Ok, I'll submit to Linuxbrew first then. Sorry, I wasn't aware of the procedure for people in my situation - I thought Linuxbrew only accepted PR's to fix Linux-specific issues and new formulae were generally supposed to go to Homebrew first.

Thank you very much for clarifying - I'll open up a work-in-progress PR to Linuxbrew soon.

**Comment by bfontaine** [comment]
I’m not familiar with how Linuxbrew work; from what I see they prefer to get formulae submitted to Homebrew if you have access to a Mac but that‘s not the case here.

cc @sjackman for opinion here.

**Comment by dunn** [comment]
Shaun might be on leave again—I think his preference is for formula to come here first if possible.

**Comment by sjackman** [comment]
I'd prefer that you submit to Homebrew. I'll accept new formula to Linxubrew that are specific to Linux and will never build on Mac.

**Comment by bfontaine** [comment]
Thank you @sjackman for the clarification.

**Comment by DomT4** [comment]
Would welcome a PR.
