### ISSUE TITLE
libboost_python.dylib or libboost_python.so is missing?

### ISSUE THREAD

**Issue by easior** [Homebrew/homebrew#45238]
Recently, I try to install boost on Mac OS Yosemite by homebrew. I can find the header files of boost.python for C/C++ in include directory. However, the corresponding library of boost.python is missing  in library directory of homebrew. Anyone can fix it?

**Comment by mikemcquaid** [comment]
`brew install boost-python` should sort you out

**Comment by easior** [comment]
Thanks a lot. The issue is solved.
