### ISSUE TITLE
brew doctor fails on 10.11.1

### ISSUE THREAD

**Issue by dschneiderch** [Homebrew/homebrew#45233]
I tried installing sshfs, it failed so I `brew update` and then `brew doctor` and got this error:
```bash
Khione:~ $ brew doctor
No check available by the name: check_for_autoconf
Error: Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool
```
with brew update, it said "Updated Homebrew from 5e80b775 to 91b03473"

any help?
Thanks!

here is the sshfs just in case:
```bash
Khione:~ $ brew install sshfs
==> Installing sshfs from homebrew/homebrew-fuse
Error: undefined method `<' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula_support.rb:21:in `valid?'
/usr/local/Library/Homebrew/formula.rb:806:in `keg_only?'
/usr/local/Library/Homebrew/formula_installer.rb:134:in `block in check_install_sanity'
/usr/local/Library/Homebrew/formula_installer.rb:133:in `select'
/usr/local/Library/Homebrew/formula_installer.rb:133:in `check_install_sanity'
/usr/local/Library/Homebrew/formula_installer.rb:111:in `prelude'
/usr/local/Library/Homebrew/cmd/install.rb:214:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `install'
/usr/local/Library/brew.rb:146:in `<main>'
```

**Comment by martensjostrand** [comment]
Hi, got the same issue after installing El Capitan. When I ran /usr/bin/otool it complained about missing Command Line Tools. Installing XCode from AppStore resolved the issue.

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by dschneiderch** [comment]
I guess I forgot `brew config`

**Comment by dschneiderch** [comment]
I did read that page but I guess I forgot to post `brew config`
Sure enough, CLT is not installed anymore.
It would be great to add to the FAQ a method to confirm the CLT are installed. I didn't realize I would have to reinstall after a minor upgrade.
Thanks for the help!
