### ISSUE TITLE
ldapvi - missing patch

### ISSUE THREAD

**Issue by sts** [Homebrew/homebrew#45241]
ldapvi has issues with recent versions of vim. when you currently install homebrew ldapvi, it always starts up with a annoying error message. It was fixed upstream, but the author didn't release a new version.

```
"/tmp/ldapvi-93Dtz8/data" 6374L, 180781C
Error detected while processing modelines:
line    1:
E520: Not allowed in a modeline: encoding=utf-8
Press ENTER or type command to continue
```

Please add the following patch to the formular:

http://www.lichteblau.com/git/?p=ldapvi.git;a=blobdiff;f=ldapvi/ldapvi.c;h=b59432738442766144ec4e8a03198c3c56bf15d2;hp=7b312f8fda106cdad210b4916f1105ca63024790;hb=a2717927f297ff9bc6752f281d4eecab8bd34aad;hpb=5c8677a34d8fd3f699a6a9428b981a667efd86ee

**Comment by bfontaine** [comment]
Would you mind making a pull-request? This should help and I’m happy to answer any question you might have:
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md

**Comment by sts** [comment]
Thanks so much! #mademyday
