### ISSUE TITLE
gfortran (from gcc) fails to compile software with error: "suffix or operands invalid for `movq`"

### ISSUE THREAD

**Issue by viniciusferrao** [Homebrew/homebrew#45258]
Hello guys,

I'm running Brew on El Capitan 10.11.1 and gfortran fails to compile anything with the following error:

/var/folders/yj/b1db0bcx0zvbyblrv354hd6m0000gn/T//cchNg0Pw.s:10704:suffix or operands invalid for `movq'

I'm running updated home-brew: dc5a7e79, and running this version of gcc:
gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/5.2.0/libexec/gcc/x86_64-apple-darwin15.0.0/5.2.0/lto-wrapper
Target: x86_64-apple-darwin15.0.0
Configured with: ../configure --build=x86_64-apple-darwin15.0.0 --prefix=/usr/local/Cellar/gcc/5.2.0 --libdir=/usr/local/Cellar/gcc/5.2.0/lib/gcc/5 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew gcc 5.2.0' --with-bugurl=https://github.com/Homebrew/homebrew/issues --enable-plugin --disable-nls --enable-multilib --with-native-system-header-dir=/usr/include --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
Thread model: posix
gcc version 5.2.0 (Homebrew gcc 5.2.0)

-- V.

**Comment by dunn** [comment]
Can you give us a short set of steps to reproduce the behavior, as well as your `brew config` and `brew doctor`? Thanks!

**Comment by viniciusferrao** [comment]
Hello dunn, I really feel dumb right now. The fix to the problem was in brew doctor, it was a non successfully removal of MacPorts. Sorry for submitting an invalid bug.

**Comment by dunn** [comment]
No worries, glad you figured it out!
