### ISSUE TITLE
leafnode - no such user: news

### ISSUE THREAD

**Issue by deKay01** [Homebrew/homebrew#45255]
I've moved over from macports to homebrew, and am having an issue with leafnode.

I've installed it, but it won't run, saying "no such user: news".

The install process on macports creates this user, but it seems brew does not, or have I missed something? How do I correctly do this if I'm supposed to do it manually?

(El Capitan, new install, have fully updated homebrew)

**Comment by dunn** [comment]
There's a configure flag `--with-user=<userid>`, but if we pass `--with-user=$(whoami)` during the build then the precompiled bottles will fail to run since the user will be `brew`.  One option is to just not build bottles for this formula, but that's not great.

**Comment by deKay01** [comment]
So is there a solution? Or a way I can create this user after installation?

Thanks

**Comment by mikemcquaid** [comment]
> There's a configure flag --with-user=<userid>, but if we pass --with-user=$(whoami) during the build then the precompiled bottles will fail to run since the user will be brew. One option is to just not build bottles for this formula, but that's not great.

Sounds like the best option to me and perhaps ask upstream if it can be configurable at runtime.

**Comment by dunn** [comment]
https://sourceforge.net/p/leafnode/feature-requests/5/

**Comment by DomT4** [comment]
@dunn Are you plotting a fix PR here? Happy to throw together one but don't want to step on you if you're working on it.

**Comment by dunn** [comment]
Go for it!

**Comment by deKay01** [comment]
Thanks, everyone. In the meantime, does anyone know how to create the necessary user after installation?

**Comment by DomT4** [comment]
If you `brew reinstall leafnode` you should find it works for your normal user now.
