### ISSUE TITLE
brew postinstall fontconfig hangs

### ISSUE THREAD

**Issue by wizonesolutions** [Homebrew/homebrew#45260]
I'm seeing the issue from https://github.com/Homebrew/homebrew/issues/28111 anew on El Capitan. I didn't want to poke an old issue, so thought I would start by opening a new one.

I have some fonts under `~/Library/Fonts`, but no subdirectories.

OK, I just moved the fonts. This happens even with an empty `~/Library/Fonts`. Might be a new issue with the same symptoms. Doesn't actually stop `wine` from building, at least.

**Comment by huang1988519** [comment]
I have the same problem on EI Capitan,

**Comment by kaplad** [comment]
Same problem! EI Capitan

**Comment by ValentineK** [comment]
Same problem EI Capitan.
```
sh-3.2# brew reinstall fontconfig
==> Reinstalling fontconfig
==> Downloading https://homebrew.bintray.com/bottles/fontconfig-2.11.1.el_capitan.bottle.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/fontconfig-2.11.1.el_capitan.bottle.3.tar.gz
==> Pouring fontconfig-2.11.1.el_capitan.bottle.3.tar.gz
==> /usr/local/Cellar/fontconfig/2.11.1/bin/fc-cache -frv
```
Here brew hangs...
brew is updated and upgraded to the last version

**Comment by alexbiddle** [comment]
==> make install RUN_FC_CACHE_TEST=false
make[2]: *** Waiting for unfinished jobs....
 /usr/bin/install -c -m 644 fontconfig.pc '/usr/local/Cellar/fontconfig/2.11.1/lib/pkgconfig'
 /usr/bin/install -c -m 644 fonts.dtd '/usr/local/Cellar/fontconfig/2.11.1/share/xml/fontconfig'
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1

**Comment by zinnsoldat08468** [comment]
i have the same :-(

make[2]: *** Waiting for unfinished jobs....
 /usr/bin/install -c -m 644 fonts.dtd '/usr/local/Cellar/fontconfig/2.11.1/share/xml/fontconfig'
 /usr/bin/install -c -m 644 fontconfig.pc '/usr/local/Cellar/fontconfig/2.11.1/lib/pkgconfig'
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1

**Comment by mikemcquaid** [comment]
I believe @DomT4 has looked at this in the past.

**Comment by hellogreg** [comment]
Yeah. Happens to me right after a clean El Capitan install -- at the same spot as ValentineK. I haven't messed with the fonts on my system (as was mentioned as having some possible correlation in a previous occurrence of this issue).

**Comment by DomT4** [comment]
Failures to build are a different issue here. Would need a `brew gist-logs` done on those to be able to look at them properly.

On the hang in `postinstall` - Some hang is expected. Can easily take 5-15 minutes, but I presume people are letting it run longer than that here? It should be executing *something* like:

```
/usr/share/fonts: skipping, no such directory
/System/Library/Fonts: caching, new cache contents: 281 fonts, 0 dirs
/Library/Fonts: caching, new cache contents: 586 fonts, 0 dirs
/Users/example/Library/Fonts: caching, new cache contents: 20 fonts, 0 dirs
/Users/example/.local/share/fonts: skipping, no such directory
/Users/example/.fonts: skipping, no such directory
/usr/local/var/cache/fontconfig: cleaning cache directory
/usr/local/var/cache/fontconfig: invalid cache file: ec61f5f62202b00f4394db789bf8060c-le64.cache-4
/usr/local/var/cache/fontconfig: invalid cache file: f5cfc3b478b38c2d54a85af0b7b29a88-le64.cache-4
/Users/example/.cache/fontconfig: not cleaning non-existent cache directory
/Users/example/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded
```

**Comment by mikemcquaid** [comment]
If you run `brew postinstall fontconfig -v` that may give you more debugging output.

**Comment by DomT4** [comment]
Let us know if we can help further here, Thanks!

**Comment by rdpoor** [comment]
FWIW, I came here looking for a solution.  While I was reading the thread, the brew continued, about seven minutes after getting hung.  Maybe it went out for a pint.
