### ISSUE TITLE
FreeTDS 0.95 Segfault With Multi Result Sets

### ISSUE THREAD

**Issue by kwhat** [Homebrew/homebrew#45274]
So freetds 0.95 is unstable and causing segfaults with multiple result sets on MsSQL. This is not an issue with ports because they use FreeTDS 0.91. Downgrading via `brew edit freetds` and replacing the 0.95 formula with 0.91 resolves the issue.

I have filed a bug report upstream: https://github.com/FreeTDS/freetds/issues/28

Example to cause segfault:
```
<?php
require_once("dbinfo.php");
//putenv('FREETDSCONF=/opt/local/etc/freetds/freetds.conf');

$pdo = new PDO("dblib:host=" . DB_HOST . ";dbname=" . DB_NAME . ';charset=UTF-8', DB_USER, DB_PASS);

$multipleresults = "SELECT 1; SELECT 2; SELECT 3;";

$stmt = $pdo->prepare($multipleresults);

print "Executing SQL: '{$multipleresults}'\n";
$stmt->execute();

print "Looping through results. Should segfault on nextRowset\n";
do {
    print_r($stmt->fetchAll());
} while ($stmt->nextRowset());

print "Complete.\n";
```

**Comment by kwhat** [comment]
Alright, So I was reading the php changelog (because that's what I do in my free time) and I discovered this bug report: https://bugs.php.net/bug.php?id=69757

After updating to php 5.6.16 and freetds 0.95 things are working again.

**Comment by dunn** [comment]
Glad to hear it! Is there anything we can do on our end?

**Comment by kwhat** [comment]
The fix doesn't cover php53 php54 php55 so those formulas should require freetds 0.91 where php56 and php70 should use 0.95

**Comment by dunn** [comment]
cc @Homebrew/php

**Comment by mikemcquaid** [comment]
Given our formula is using the system PHP: closing this out as an upstream and/or Homebrew/php issue.
