### ISSUE TITLE
File name too long error when trying to install gnu-tar

### ISSUE THREAD

**Issue by bamapookie** [Homebrew/homebrew#45273]
Installing gnu-tar for the first time on El Capitan.  I get the following error:

Error: File name too long - /tmp/gnu-tar-32onDN/tar-1.28/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---

One error earlier in the configuration mentions a possibly truncated patch:

patching file src/Makefile.am
patch unexpectedly ends in middle of line

**Comment by chdiza** [comment]
Upstream is already aware of the "confdir" issue.  It has nothing to do with the truncated patch.  The confdir thing is, according to people on the `gnu-tar` mailing list, an ElCap bug that Apple is aware of.  It affects other bits of GNU software too, like `findutils`.  It stinks, because it leaves unremovable nested dir trees sitting in `/tmp`.

**Comment by chdiza** [comment]
See the thread starting [here](http://lists.gnu.org/archive/html/bug-tar/2015-10/msg00005.html), for instance.

**Comment by chdiza** [comment]
Hmm, that thread describes the problem but doesn't show the [recognition as an Apple bug](http://lists.gnu.org/archive/html/bug-tar/2015-10/msg00017.html).

**Comment by bamapookie** [comment]
Thanks, chdiza.  Is there a workaround?

**Comment by DomT4** [comment]
There was a posting about this in #44993. If we can identify which formulae have this behaviour, we may be able to do *something* about it, hopefully.

**Comment by chdiza** [comment]
I made up some silly ruby script to descend all the way down and start deleting.

Alternatively, `cd */*/*` until you're about thirty or so "confdirs" deep.  Then `rm -rf conf*` once or twice should prune down the three.  Then you can `cd` back up and rm the rest.

@DomT4 I know from experience that `gnu-tar` and `findutils` have this issue.  The post you referenced (a) references a [post](https://github.com/NixOS/nixpkgs/issues/9707#issuecomment-139702071) that has something we could potentially stick in GNU formulas, and (b) claims that this affects everything that depends on gnulib.

**Comment by chdiza** [comment]
FWIW, some of those other posts claim that the software in question won't actually build correctly.  I've not had that problem.  `gnu-tar` and `findutils` build fine, they just leave hard-to-remove junk laying around.

**Comment by swh** [comment]
I have the same problem, and it didn't correctly build coreutils.

Running brew 0.9.5 on El Capitan.

BTW, the easiest way to remove the deep tree is just "open /tmpcoreutils-*" and use the finder to delete it.

**Comment by tfmontague** [comment]
Was able to successfully brew install gnu-tar, with the following workaround -
export gl_cv_func_getcwd_abort_bug="no"

**Comment by chdiza** [comment]
The workaround posted by @tfmontague works for me on both `gnu-tar` and `findutils`.  No deep tree left behind.

**Comment by mikemcquaid** [comment]
@tfmontague @chdiza Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by chdiza** [comment]
(a) Should I do it for both `gnu-tar` and `findutils`?  Or just `gnu-tar`?
(b) If the answer is "both", then should they both go in the same PR?

**Comment by mikemcquaid** [comment]
> (a) Should I do it for both gnu-tar and findutils? Or just gnu-tar?
> (b) If the answer is "both", then should they both go in the same PR?

If they are both affected: both and same PR but one commit per formula. Thanks!

**Comment by DomT4** [comment]
Closing in favour of https://github.com/Homebrew/homebrew/pull/46709.
