### ISSUE TITLE
Warning: /usr/local/bin isn't writable

### ISSUE THREAD

**Issue by mhulse** [Homebrew/homebrew#45288]
I've been plagued by permission issues for 3 or 4 months now, on two different Macs:

![screenshot 2015-10-23 18 51 02](https://cloud.githubusercontent.com/assets/218624/10708258/1c4f60a8-79b7-11e5-89e4-cf19d3aa1351.png)

Running (based on info found in #43301):

```bash
$ sudo chown -R $(whoami):admin /usr/local && sudo chmod -R g+rwx /usr/local
```

Seems to fix the problem, that is, until the next time I run `brew update && brew upgrade`.

I've never ran `sudo make install` for anything.

Anyone have any tips? I guess I don't mind repairing my permissions after every `update`, but something seems wrong here.

Sorry to bug ya'll with this.

* MacBook Pro (17-inch, Early 2011)
* OS X Yosemite, `10.10.5`

**Comment by DomT4** [comment]
Interesting. This definitely isn't expected or normal as per `brew` usage. Some things:

* Do you have Sophos Anti-Virus installed?
* What does `ls -l /usr/local` output?
* What does `/bin/zsh -c "cd /usr/local/bin && ls -d *(^@)"` output?

**Comment by mhulse** [comment]
Hi @DomT4, thanks so much for your quick reply and help, I really appreciate it!

1. Actually, I do have Sophos installed. You know, I had not thought to check if that was the source of the problem. I have that installed on both machines. I'll be Googling for Sophos-related brew issues to see if there's something to that. :+1: 
1. ![screenshot 2015-10-23 21 45 37](https://cloud.githubusercontent.com/assets/218624/10708912/7024bdf0-79cf-11e5-821b-a6641f713840.png)
1. ![screenshot 2015-10-23 21 46 27](https://cloud.githubusercontent.com/assets/218624/10708922/9dd19be2-79cf-11e5-93a5-7622f68ae1da.png)

Thanks again for your help!

**Comment by mhulse** [comment]
> Actually, I do have Sophos installed. You know, I had not thought to check if that was the source of the problem. I have that installed on both machines. I'll be Googling for Sophos-related brew issues to see if there's something to that. :+1: 

Ah, yes, this smells like the problem for sure:

['sweep' command installs itself into /usr/local and changes permissions, wreaking havoc on Homebrew](https://community.sophos.com/products/free-antivirus-tools-for-desktops/f/17/t/10029)

First hit on Google when searching for `homebrew sophos anti virus`.

I don't think I would have guessed Sophos was the problem here.

I'll go ahead and close as this isn't a Homebrew issue. Sorry for the noise, and thanks a bunch for the help @DomT4! :octocat:
