### ISSUE TITLE
Antlr isn't ready to use after brew install

### ISSUE THREAD

**Issue by vermiculus** [Homebrew/homebrew#45292]
Logs: https://gist.github.com/anonymous/d2418a95612900f3315e

Should probably add a message saying to add the jar to your CLASSPATH (or do it automatically if you can)

**Comment by dunn** [comment]
Looks like we're setting the path for `grun`; does that run for you? https://github.com/Homebrew/homebrew/blob/master/Library/Formula/antlr.rb#L14

If so we can update the wrapper for `antlr4` to match.

**Comment by vermiculus** [comment]
`grun` works fine. I have a very limited knowledge of Ruby, but couldn't we just give the call to `write_jar_script` [an extra argument](https://github.com/Homebrew/homebrew/blob/ca28efaf2c54c1dc284442a6eed45b348ee1ca08/Library/Homebrew/extend/pathname.rb#L391) to add to the classpath?

**Comment by dunn** [comment]
Yep! Should the classpath be the same: `#{prefix}/antlr-#{version}-complete.jar:.`?

**Comment by vermiculus** [comment]
Yes, that looks right. :smile:

**Comment by dunn** [comment]
And is this how the wrapper script should look (I know nothing about Java ヽ(。_°)ノ ):
```bash
#!/bin/bash
exec java -classpath /usr/local/Cellar/antlr/4.5.1/antlr-4.5.1-complete.jar:. -jar /usr/local/Cellar/antlr/4.5.1/antlr-4.5.1-complete.jar "$@"
```

**Comment by vermiculus** [comment]
Looks like it works :) At least everything after exec. I've never used that keyword before.
