### ISSUE TITLE
emacs: Calling from command line should *not* insert '-nw' automatically

### ISSUE THREAD

**Issue by dunn** [Homebrew/homebrew#45295]
_From @paaguti on October 24, 2015 16:26_

The emacs script inserts '-nw' automatically. This have following disadvantages:

1. You can't open the Cocoa based exec from bash
2. You can't open the Cocoa based exec from emacsclient

_Copied from original issue: Homebrew/homebrew-emacs#25_

**Comment by dunn** [comment]
(Moved since the emacs tap is just for emacs packages; emacs remains here in core: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/emacs.rb)

**Comment by dunn** [comment]
For reference, the `-nw` was added way back in 55dbcc15905664092b805e7822fb8c66d5ca0f8e.

FYI if you're running the daemon,  `emacsclient -c` should open a Cocoa window.

I'm open to changing the wrapper script though.  @adamv has done a lot of work on this formula, though, and might have some thoughts.

**Comment by paaguti** [comment]
Right with -c flag... However it failed when daemin is nit running.

**Comment by dunn** [comment]
Fixed!
