### ISSUE TITLE
Some commands not running after I switched to zsh.

### ISSUE THREAD

**Issue by timbog80** [Homebrew/homebrew#45297]
~ brew config
![brew config](http://puu.sh/kW8jh/a3a4485998.png)

When I try running
~ sass -v
![brew config](http://puu.sh/kW8pg/abd5bf76dc.png)

Even though I have it installed:
sass (3.4.19)
![brew config](http://puu.sh/kW8vQ/fe358bf544.png)

**Comment by alebcay** [comment]
Is `/usr/local/bin` in your `PATH` variable? You'll have to redefine it in `~/.zshrc`, Zsh's configuration file.

**Comment by timbog80** [comment]
When i check $PATH I get

```
zsh: no such file or directory: /usr/local/bin:/Users/timbogdanov/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by DomT4** [comment]
Where are you seeing the above error message thrown from? Anything in `brew doctor`?

**Comment by alebcay** [comment]
@DomT4 looks like he literally ran `$PATH`, so zsh evaluated it as a file/folder path. Anyways, it looks like `/usr/local/bin` is in the path so I'm not sure why that wouldn't be working. Are you sure `sass` is linked?

**Comment by UniqMartin** [comment]
This has probably little to do with Homebrew. `sass` is installed via `gem` and the Ruby installation(s) seem to be managed by `rbenv`, so the `sass` wrapper binary might not be `/usr/local/bin` but somewhere else. Quite likely, there's still something missing in the `$PATH` variable.

I think the easiest solution would be to open a `bash` shell (I assume that's the one previously used and where everything worked) and check what `echo "$PATH"` prints. Then change `~/.zprofile` or `~/.zshrc` accordingly.

**Comment by DomT4** [comment]
Yes, I'm fairly sure this isn't a Homebrew issue, but it'd be good to get some feedback to see if there is anything going on there.

**Comment by timbog80** [comment]
No In tried it with Bash. doesnt work

**Comment by timbog80** [comment]
@DomT4 

![brew doctor](http://puu.sh/kYJzv/66f6dfbeea.png)

**Comment by bfontaine** [comment]
Homebrew only provides `libsass` and `sassc` formulae; None of these have a `sass` binary.

This looks like a `PATH` issue as others said; see https://github.com/sstephenson/rbenv/issues/114.

**Comment by timbog80** [comment]
Worked after running

```
gem install rspec-core && rbenv rehash
```

as suggested by @kurko

**Comment by kurko** [comment]
@timbog80 I suggested that? :P I don't remember it.
