### ISSUE TITLE
macvim failed to build on 10.10

### ISSUE THREAD

**Issue by greulich** [Homebrew/homebrew#45308]
Home builds *macvim* from the source. Actually it fails to build for the right platform. The resulting binary is targeted to Mac OS 10.11 and refuses to run on 10.10 with a corresponding message from osx. The machine that refused to execute is the very same machine the sources are compiled. *brew doctor* does not complain at all. Just for fun I tried the bintray URL given below an got an answer page saying "Invalid storage path: homebrew"

Context
=======
Gist
----
https://gist.github.com/9abab29e3bb70a773c5f

brew config
===========
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: ffc24ff8ef42801875732e39cc2defd1d0a66318
Last commit: 16 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit ivybridge
OS X: 10.10.5-x86_64
Xcode: 7.1
CLT: 7.1.0.0.1.1444952191
Clang: 7.0 build 700
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_60

**Comment by mikemcquaid** [comment]
This was just fixed by https://github.com/Homebrew/homebrew/pull/45299.
