### ISSUE TITLE
"brew install tree" failed

### ISSUE THREAD

**Issue by woodjuice** [Homebrew/homebrew#45313]
OSX 10.11.1
Homebrew 0.9.5

When I tried to "brew install tree"

>
$ brew install tree
==> Downloading http://mama.indstate.edu/users/ice/tree/src/tree-1.7.0.tgz
Already downloaded: /Library/Caches/Homebrew/tree-1.7.0.tgz
==> make prefix=/usr/local/Cellar/tree/1.7.0 MANDIR=/usr/local/Cellar/tree/1.7.0
make: *** [xml.o] Error 1
1 error generated.
make: *** [tree.o] Error 1
1 error generated.
make: *** [html.o] Error 1

**Comment by dunn** [comment]
Could you post the full `brew gist-logs tree`? Thanks!

**Comment by woodjuice** [comment]
>
$ brew gist-logs tree
https://gist.github.com/46dd2cb11ced4b479a12

**Comment by jrowlingson** [comment]
+1

**Comment by bfontaine** [comment]
@jrowlingson Please post the output of `brew gist-logs tree` as well.

**Comment by jrowlingson** [comment]
@bfontaine https://gist.github.com/anonymous/1e085eaa373245a50441

The first attempt failed when I was behind a firewall. The second attempt, outside of the firewall, succeded.

**Comment by bfontaine** [comment]
@jrowlingson The firewall shouldn’t interfere with the build here because we check the checksum of the tarball. Was it on the same machine?

**Comment by DomT4** [comment]
@jrowlingson Your Xcode is outdated, which is causing the problems in your case as far as I can see. Xcode 6 doesn't include the 10.11 SDK and you don't have the CLT installed, hence `fatal error: 'stdlib.h' file not found`. There's a lot in `brew doctor` that can cause trouble as well.

**Comment by DomT4** [comment]
@woodjuice Your problem seems to be the same actually. Outdated Xcode & outdated `brew`. Please `brew update`, update your Xcode to the latest App Store release.
