### ISSUE TITLE
Agda: Test failures

### ISSUE THREAD

**Issue by mietek** [Homebrew/homebrew#45318]
cc @mikemcquaid @DomT4 @nijikon 

There are [four tests](https://github.com/Homebrew/homebrew/blob/d79c83a831198679d94b0ecc15b1cdc1437280b1/Library/Formula/agda.rb#L86-L123) for the Agda formula, two of which exhibit issues:

1. the Agda self-test, which passes in CI;
2. compiling `simple-test.agda` to native code using the MAlonzo backend, which **fails in CI**;
3. compiling `simple-test.agda` using the JS backend, which passes in CI; and
4. compiling `stdlib-test.agda` to native code using the MAlonzo backend, conditional on `build.with? "stdlib"` and `build.with? "malonzo-ffi"`, which is **not run in CI**, and **fails locally**.

### Problem 1.

```
...
Compiling simple-test in /private/tmp/agda20151024-15554-48b16p/simple-test.agdai to /private/tmp/agda20151024-15554-48b16p/MAlonzo/Code/QsimpleZ45Ztest.hs
Calling: ghc -O -Werror -i/private/tmp/agda20151024-15554-48b16p /private/tmp/agda20151024-15554-48b16p/MAlonzo/Code/QsimpleZ45Ztest.hs --make -fwarn-incomplete-patterns -fno-warn-overlapping-patterns
ghc: createProcess: runInteractiveProcess: exec: does not exist (No
such file or directory)
```
([Job #2664.2](https://travis-ci.org/Homebrew/homebrew/jobs/87148415#L843-L849))

Agda supports compiling programs using three backends: the default backend, the MAlonzo backend, and the JS backend.  All three backends are part of the Agda core and do not need to be installed separately.  However, in order for the MAlonzo backend to work, GHC must be available at runtime.

The Agda formula declares GHC as a build dependency only, which results in the MAlonzo backend not working — unless GHC is already installed.  This is the **cause of failure for test 2**, and the **_first_ cause of failure for test 4**.

### Problem 2.

```
...
Compiling stdlib-test in /private/tmp/agda20151024-15682-1wjoo39/stdlib-test.agdai to /private/tmp/agda20151024-15682-1wjoo39/MAlonzo/Code/QstdlibZ45Ztest.hs
Calling: ghc -O -o /private/tmp/agda20151024-15682-1wjoo39/stdlib-test -Werror -i/private/tmp/agda20151024-15682-1wjoo39 -main-is MAlonzo.Code.QstdlibZ45Ztest /private/tmp/agda20151024-15682-1wjoo39/MAlonzo/Code/QstdlibZ45Ztest.hs --make -fwarn-incomplete-patterns -fno-warn-overlapping-patterns
Compilation error:
MAlonzo/Code/Foreign/Haskell.hs:4:18:
    Could not find module ‘Data.FFI’
    Use -v to see a list of the files searched for.
MAlonzo/Code/Foreign/Haskell.hs:5:18:
    Could not find module ‘IO.FFI’
    Use -v to see a list of the files searched for.
```
([Job #2960.2](https://travis-ci.org/Homebrew/homebrew/jobs/87227198#L1065-L1075))

With the first problem resolved, **test 4 still fails.**

The Agda standard library contains a Cabal package, `ffi`, that provides FFI bindings for the MAlonzo backend, as a Haskell library.  In order for these bindings to work, they must be either

1. compiled and installed in a GHC package database; or
2. available in source form (and optionally, object form) at compile time.

Contrary to the [Homebrew guidelines on Haskell libraries](https://github.com/Homebrew/homebrew/blob/d79c83a831198679d94b0ecc15b1cdc1437280b1/Library/Homebrew/language/haskell.rb#L62-L63), the Agda formula attempts to [compile and install](https://github.com/Homebrew/homebrew/blob/d79c83a831198679d94b0ecc15b1cdc1437280b1/Library/Formula/agda.rb#L66-L71) the `ffi` package, conditional on `build.with? "malonzo-ffi"`.  

This does not work, as `cabal install --user` results in the FFI bindings being installed inside the temporary `.brew_home` directory.  This is the **_second_ cause of failure for test 4**.

### Problem 3.

```
...
==> /usr/local/Cellar/agda/2.4.2.4/bin/agda -i /private/tmp/agda20151024-15573-1tc4p4g -i /usr/local/Cellar/agda/2.4.2.4/agda-stdlib/src --ghc-flag=-i/usr/local/Cellar/agda/2.4.2.4/agda-stdlib/ffi-c /private/tmp/agda20151024-15573-1tc4p4g/stdlib-test.agda
sh: testpath/stdlib-test: No such file or directory
Error: agda: failed
<""> expected but was
<"Hello, world!">.
```

([Job #2700.2](https://travis-ci.org/Homebrew/homebrew/jobs/87243334#L835-L840))

With the second problem resolved, **test 4 still fails.**

The [final assertion](https://github.com/Homebrew/homebrew/blob/d79c83a831198679d94b0ecc15b1cdc1437280b1/Library/Formula/agda.rb#L120) in the test mistakenly refers to a literal `testpath`, instead of referencing the `testpath` variable.  This is the **_third_ cause of failure for test 4**.

**Comment by mietek** [comment]
The solution for #45321 is also a solution for problem 2.

Proposed solution for problems 1 and 3: https://github.com/mietek/homebrew/commit/f2798a044335d6cf78dc21a1d6a950c18cf9870b

**Comment by mietek** [comment]
The solution for #45321 is also a solution for problem 2.

Proposed solution for problems 1 and 3: https://github.com/mietek/homebrew/commit/dc513d449cec6a1c2dd37222279ad9836943402e (with correct paths in caveats)

**Comment by mikemcquaid** [comment]
> Proposed solution for problems 1 and 3: mietek@dc513d4 (with correct paths in caveats)

That's looking pretty good, thanks.

**Comment by mietek** [comment]
Updated solution: https://github.com/mietek/homebrew/commit/1146242e48dfe1fd3a1747e3af7fbc44e7acd223

**Comment by mietek** [comment]
### Problem 4.

```
Calling: ghc -O -o /private/tmp/agda20151027-19436-rg7bju/stdlib-test -Werror -i/usr/local/Cellar/agda/2.4.2.4/agda-stdlib/ffi -i/private/tmp/agda20151027-19436-rg7bju -main-is MAlonzo.Code.QstdlibZ45Ztest /private/tmp/agda20151027-19436-rg7bju/MAlonzo/Code/QstdlibZ45Ztest.hs --make -fwarn-incomplete-patterns -fno-warn-overlapping-patterns
[  1 of 102] Compiling MAlonzo.RTE      ( MAlonzo/RTE.hs, MAlonzo/RTE.o )
[  3 of 102] Compiling IO.FFI           ( /usr/local/Cellar/agda/2.4.2.4/agda-stdlib/ffi/IO/FFI.hs, /usr/local/Cellar/agda/2.4.2.4/agda-stdlib/ffi/IO/FFI.o )
Compilation error:
/usr/local/Cellar/agda/2.4.2.4/agda-stdlib/ffi/IO/FFI.hi: openBinaryFile: permission denied (Operation not permitted)
```
(Job [#2859.2](https://travis-ci.org/Homebrew/homebrew/jobs/87684407#L863-L867))

With the three initial problems resolved, test 4 passes locally, but **fails in CI**.

Is `/usr/local/Cellar/agda/2.4.2.4/agda-stdlib/ffi` read-only in CI?

**Comment by mietek** [comment]
@mikemcquaid: Can you help me understand the cause of problem 4?

**Comment by bfontaine** [comment]
@mietek You can’t write outside of the formula prefix on the CI.

**Comment by mietek** [comment]
@bfontaine: The problematic file access is for a file located in `/usr/local/Cellar/agda/2.4.2.4`, which I believe _is_ the formula prefix. Is it not?

**Comment by bfontaine** [comment]
Yes it is :confused:

**Comment by mietek** [comment]
As @mikemcquaid [points out](https://github.com/Homebrew/homebrew/pull/45327#issuecomment-152787718), the error can be reproduced with `brew test --verbose --sandbox agda`:
```
...
Compilation error:
/usr/local/Cellar/agda/2.4.2.4/agda-stdlib/ffi/IO/FFI.hi: openBinaryFile: permission denied (Operation not permitted)

==> Sandbox log
Nov  1 02:49:18 sandboxd[303]: ghc(88786) deny file-write-create /usr/local/Cellar/agda/2.4.2.4/agda-stdlib/ffi/IO/FFI.hi
```

To work around this restriction, the Agda formula now creates a dedicated GHC package database within the FFI bindings directory, and installs the `ffi` package registering it in the dedicated database.

Updated solution: https://github.com/mietek/homebrew/commit/7d1dba2f9f345e8b1594909403910c5f4ef2c9f5

**Comment by mietek** [comment]
@dunn: It appears that [Problem 2](https://github.com/Homebrew/homebrew/issues/45318#issue-113262811) is back. (https://github.com/Homebrew/homebrew/pull/47181#issuecomment-166008072)

Also reproduced locally:
```
$ brew test agda --strict --sandbox
Testing agda
==> Using the sandbox
==> /usr/local/Cellar/agda/2.4.2.4_1/bin/agda --test
==> /usr/local/Cellar/agda/2.4.2.4_1/bin/agda -c --no-main --safe /private/tmp/agda20151219-14447-53rowc/simple-test.agda
==> /usr/local/Cellar/agda/2.4.2.4_1/bin/agda --js --safe /private/tmp/agda20151219-14447-53rowc/simple-test.agda
==> /usr/local/Cellar/agda/2.4.2.4_1/bin/agda -i /private/tmp/agda20151219-14447-53rowc -i /usr/local/Cellar/agda/2.4.2.4_1/agda-stdlib/src 
Last 15 lines from /Users/mietek/Library/Logs/Homebrew/agda/04.agda:
Compiling Relation.Nullary.Decidable in /usr/local/Cellar/agda/2.4.2.4_1/agda-stdlib/src/Relation/Nullary/Decidable.agdai to /private/tmp/agda20151219-14447-53rowc/MAlonzo/Code/Relation/Nullary/Decidable.hs
Compiling Relation.Nullary.Negation in /usr/local/Cellar/agda/2.4.2.4_1/agda-stdlib/src/Relation/Nullary/Negation.agdai to /private/tmp/agda20151219-14447-53rowc/MAlonzo/Code/Relation/Nullary/Negation.hs
Compiling Relation.Unary in /usr/local/Cellar/agda/2.4.2.4_1/agda-stdlib/src/Relation/Unary.agdai to /private/tmp/agda20151219-14447-53rowc/MAlonzo/Code/Relation/Unary.hs
Compiling stdlib-test in /private/tmp/agda20151219-14447-53rowc/stdlib-test.agdai to /private/tmp/agda20151219-14447-53rowc/MAlonzo/Code/QstdlibZ45Ztest.hs
Calling: ghc -O -o /private/tmp/agda20151219-14447-53rowc/stdlib-test -Werror -package-db=/usr/local/Cellar/agda/2.4.2.4_1/agda-stdlib/ffi/package.conf.d -i/private/tmp/agda20151219-14447-53rowc -main-is MAlonzo.Code.QstdlibZ45Ztest /private/tmp/agda20151219-14447-53rowc/MAlonzo/Code/QstdlibZ45Ztest.hs --make -fwarn-incomplete-patterns -fno-warn-overlapping-patterns
Compilation error:

MAlonzo/Code/Foreign/Haskell.hs:4:18:
    Could not find module ‘Data.FFI’
    Use -v to see a list of the files searched for.

MAlonzo/Code/Foreign/Haskell.hs:5:18:
    Could not find module ‘IO.FFI’
    Use -v to see a list of the files searched for.

Error: agda: failed
Failed executing: /usr/local/Cellar/agda/2.4.2.4_1/bin/agda -i /private/tmp/agda20151219-14447-53rowc -i /usr/local/Cellar/agda/2.4.2.4_1/agda-stdlib/src --ghc-flag=-package-db=/usr/local/Cellar/agda/2.4.2.4_1/agda-stdlib/ffi/package.conf.d -c /private/tmp/agda20151219-14447-53rowc/stdlib-test.agda
/usr/local/Library/Homebrew/formula.rb:1471:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1408:in `open'
/usr/local/Library/Homebrew/formula.rb:1408:in `system'
/usr/local/Library/Formula/agda.rb:159:in `block in <class:Agda>'
/usr/local/Library/Homebrew/formula.rb:1317:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1313:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>’
```
