### ISSUE TITLE
brew create missing "name" option

### ISSUE THREAD

**Issue by hryamzik** [Homebrew/homebrew#45310]
Brew create uses a first part of string splitted by a 'minus' sign, so this:

```bash
brew create https://github.com/fboender/ansible-cmdb.git
```

Returns an error:

```
Error: /usr/local/Library/Formula/ansible.rb already exists
```

Indeed it exists! But ansible-cmbd doesn't....

**Comment by bfontaine** [comment]
You can use `brew create --set-name https://github.com/fboender/ansible-cmdb.git ansible-cmdb`.

**Comment by dunn** [comment]
This isn't an issue with the name scanner, though?

**Comment by bfontaine** [comment]
@dunn I guess so. The issue is that `Version.parse` assumes `cmdb` is the version and thus the `FormulaCreator` thinks the first part is the name: https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/create.rb#L83

**Comment by dunn** [comment]
Maybe when there's a `.git` at the end we could get it to assume it's a `head` url?

**Comment by bfontaine** [comment]
Yeah good idea :smile:

**Comment by dunn** [comment]
:cool: I'm not too familiar with that code so I might not get to this right away.

**Comment by bfontaine** [comment]
Will try something tomorrow.

**Comment by hryamzik** [comment]
@bfontaine ```brew create https://github.com/fboender/ansible-cmdb.git --set-name ansible-cmdb``` did the trick, thanks!

This option is no mentioned nor in [FAQ](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md), nor in [Formula Cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md) nor in ```brew create --help``` though...
