### ISSUE TITLE
Agda: Broken --with-malonzo-ffi option

### ISSUE THREAD

**Issue by mietek** [Homebrew/homebrew#45321]
cc @mikemcquaid @DomT4 @nijikon

The Agda formula offers a broken `--with-malonzo-ffi` option.

This option is [described](https://github.com/Homebrew/homebrew/blob/d79c83a831198679d94b0ecc15b1cdc1437280b1/Library/Formula/agda.rb#L24) to "Include the MAlonzo backend's FFI (depends on the standard library)".  However, the `ffi` Cabal package is included in the Agda standard library **whether this option is set or not**.

The code conditional on this option is [described](https://github.com/Homebrew/homebrew/blob/d79c83a831198679d94b0ecc15b1cdc1437280b1/Library/Formula/agda.rb#L66) to "install the standard library's FFI bindings for the MAlonzo backend".  However, the code **does not work**, as `cabal install --user` results in the FFI bindings being installed inside the temporary `.brew_home` directory.  This is one of the causes of Agda test failures (#45318).

**Comment by mietek** [comment]
Proposed solution: https://github.com/mietek/homebrew/commit/396d5f42d18f674250ed993771be84afc19881f0

**Comment by mietek** [comment]
Proposed solution: https://github.com/mietek/homebrew/commit/79a159299096a6ffde94b706184952c7d2180772 (with correct paths in caveats)

**Comment by mikemcquaid** [comment]
Maybe we should just enable this by default?

**Comment by mietek** [comment]
Proposed solution: https://github.com/mietek/homebrew/commit/79a159299096a6ffde94b706184952c7d2180772

**Comment by mietek** [comment]
Updated solution: https://github.com/mietek/homebrew/commit/9338e465332be24cf0b042c1174625879087a9db
