### ISSUE TITLE
How do I help create an `objconv` package?

### ISSUE THREAD

**Issue by InPermutation** [Homebrew/homebrew#45323]
#10441 #17153 #33807 have all attempted to pull `objconv` into Homebrew. It doesn't look like upstream is ever going to make versioned tarballs, but I could maintain one semi-automatically using cron, GitHub and either GitHub Releases or BinTray. (Upstream prepends latest version numbers to `changelog.txt` at the root of the zip file, so it shouldn't be very hard.)

Would one of those options be accepted?

**Comment by mikemcquaid** [comment]
> Would one of those options be accepted?

Sadly not. Sounds like a good call for homebrew-head-only. Sorry!
