### ISSUE TITLE
Agda: Installation of unnecessary files

### ISSUE THREAD

**Issue by mietek** [Homebrew/homebrew#45320]
cc @mikemcquaid @DomT4 @nijikon

The Agda formula installs over 200M of unnecessary files.

When installing the Agda standard library, as part of the default configuration, we get 231M:
```
$ cd /usr/local/Cellar/agda/2.4.2.4/agda-stdlib

$ du -sch .cabal bin dist
225M	.cabal
2.6M	bin
3.4M	dist
231M	total
```

Adding the `--with-malonzo-ffi` option, we get 243M:
```
$ du -sch .cabal bin dist ffi/dist
225M	.cabal
2.6M	bin
3.4M	dist
 12M	ffi/dist
243M	total
```

The Agda formula installs the standard library’s helper tools into `agda-stdlib/bin`.  This is **unnecessary**, as these tools are only used as part of the build process, in order to generate the standard library's bytecode, documentation, and vim highlighting files.

The `.cabal`, `dist`, and `ffi/dist` directories are also **unnecessary**, as they contain build products left over from the build process.

**Comment by mietek** [comment]
The solution for #45321 gets rid of the `ffi/dist` directory.

Proposed solution for getting rid of the remaining directories: https://github.com/mietek/homebrew/commit/8278ffc988589d5fe3db846e2647385c9018a9ad

**Comment by mikemcquaid** [comment]
Sounds good :+1:

**Comment by DomT4** [comment]
FYI although I've dealt with bits of the `agda` formulae before I really don't use Haskell/Cabal and there's not a lot of knowledge I can impart on these discussions, alas.

**Comment by mietek** [comment]
Same solution after rebase: https://github.com/mietek/homebrew/commit/60c6e0107ac2f8982d5e12dd14b7dcace9bcacb2
