### ISSUE TITLE
Agda: Non-standard library location

### ISSUE THREAD

**Issue by mietek** [Homebrew/homebrew#45326]
cc @mikemcquaid @DomT4 @nijikon 

The Agda formula installs the standard library in a non-standard location, `#{prefix}/agda-stdlib`.

Using the standard library requires pointing Agda to one of the library’s subdirectories, `src`.

There are fewer Google results for Agda Emacs [configs referencing `agda-stdlib/src`](https://www.google.co.uk/search?q=%22agda2-include-dirs%22+%22agda-stdlib%2Fsrc%22) than results for [configs referencing `lib/src`](https://www.google.co.uk/search?q=%22agda2-include-dirs%22+%22lib%2Fsrc%22).  (Previously, it was 8 vs 68…)  A couple of Agda tutorials use `lib/src` ([one tutorial](http://blog.oxij.org/2011/12/22/howto-get-started-with-agda/), [another tutorial](http://blog.codersbase.com/posts/2013-01-19-installing-agda-on-windows.html)).  Finally, I don’t think there’s many user installations of Homebrewed Agda, due to the number of issues with the Agda formula.

Therefore, it seems that switching to the standard location, `#{prefix}/lib`, is the right choice.

**Edit:** I was wrong. Switching to `#{prefix}/lib/agda` is the right choice.

**Comment by mietek** [comment]
Proposed solution: https://github.com/mietek/homebrew/commit/a6937750ae594d2d0d17d71e67c5a61e859cfaac

**Comment by mikemcquaid** [comment]
:+1:

**Comment by mietek** [comment]
Unfortunately, with the proposed solution in place, `brew audit` complains that [“non-libraries were installed”](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/35374/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/audit_agda/).  This includes e.g. `Everything.agda` and `Everything.agdai`, which are required for the standard library to work, and `.Everything.vim`, which is generated as part of the build process.

This seems like a policy bug.  Note that `brew audit` does not complain about such files located at deeper levels of the directory hierarchy.

**Comment by mikemcquaid** [comment]
It's not a policy bug, it's how we choose to package software. We are a bit stricter on some of these things than some distributions.

**Comment by mietek** [comment]
Sorry, I now realise my initial proposal didn’t make sense — we wouldn’t want the _contents_ of the Agda standard library directory to be symlinked into `/usr/local/lib`.  Indeed, `brew audit` was right to have complained.

I believe what we want is the Agda standard library directory _itself_ to be symlinked as a subdirectory — `/usr/local/lib/agda`.

Installing the Agda standard library at a version-independent path would be better than what we have now — `/usr/local/Cellar/agda/2.4.2.4_2/agda-stdlib` — as the user would no longer need to tweak their configuration following an Agda upgrade or revision bump.
