### ISSUE TITLE
error with "brew linkapps"

### ISSUE THREAD

**Issue by victorkwak** [Homebrew/homebrew#45328]
When I try to run "brew linkapps" I get the following:

Error: undefined method `apps' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/cmd/linkapps.rb:26:in `block in linkapps'
/usr/local/Library/Homebrew/cmd/linkapps.rb:25:in `each'
/usr/local/Library/Homebrew/cmd/linkapps.rb:25:in `linkapps'
/usr/local/Library/brew.rb:146:in `<main>'

**Comment by DomT4** [comment]
What's your `brew config` and `brew doctor`?

**Comment by victorkwak** [comment]
`brew config:`
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 7d9f84178dfc24110caa140e2d7efaf817a2c1c0
Last commit: 40 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit ivybridge
OS X: 10.11.1-x86_64
Xcode: 7.1
CLT: N/A
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_60

`brew doctor:`
Warning: Some directories in /usr/local/share/man aren't writable.
This can happen if you "sudo make install" software that isn't managed
by Homebrew. If a brew tries to add locale information to one of these
directories, then the install will fail during the link step.
You should probably `chown` them:
    /usr/local/share/man/de
    /usr/local/share/man/de/man1

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    activator-1.3.6-minimal

**Comment by DomT4** [comment]
Nothing particularly unusual there, although you should follow up on the `chown` suggestion in `doctor`. Does `brew readall` output anything?

**Comment by victorkwak** [comment]
`brew readall` doesn't output anything at all.

**Comment by DomT4** [comment]
Try `git fetch && git reset --hard origin/master` inside your `brew --prefix`. Let us know if you're still seeing the issue afterwards, Thanks!
