### ISSUE TITLE
Parallel downloding

### ISSUE THREAD

**Issue by sijad** [Homebrew/homebrew#45345]
is this possible to continue downloading while there's an active compiling?

**Comment by DomT4** [comment]
You can `brew install xyz` in one terminal tab & `brew fetch xyz` in another at the same time, if that answers your question?

**Comment by sijad** [comment]
yes and thanks for answer

**Comment by sijad** [comment]
the `fetch` command resolve my problem, but I can't understand why this is not possible in install process, let think I want upgrade gcc + qt + llvm + etc in same time, why it's not possible to continue downloading while a compiling going on? it can save lot of time

**Comment by davad** [comment]
I was looking for something similar. Looks like it came up in a few thread about a year ago. There was a WIP a year ago (#33469).

**Comment by DomT4** [comment]
I'm not sure if Jack rewrote the code he closed in favour of in the end, as mentioned in that thread. I'd personally be happy for us to re-review something in the same vein as the #33469 PR at this point.

**Comment by sijad** [comment]
I'll work on this
