### ISSUE TITLE
MySQL 5.7.9

### ISSUE THREAD

**Issue by dmyers** [Homebrew/homebrew#45368]
This is now the latest GA release version of MySQL available at http://dev.mysql.com/downloads/ as [announced](https://www.oracle.com/corporate/pressrelease/mysql-5-7-ga-101915.html).

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by DomT4** [comment]
We'll need to handle `boost` first apparently:

```
-- Could not find (the correct version of) boost.
-- MySQL currently requires boost_1_59_0
```

**Comment by joeploijens** [comment]
Or have MySQL download the correct version of boost. I got MySQL to build by adding the following to the cmake argument list: `-DDOWNLOAD_BOOST=1 -DWITH_BOOST=.`

http://mysqlserverteam.com/building-mysql-5-7/

**Comment by DomT4** [comment]
Boost isn't exactly a small download, and nor is MySQL. I'm quite reluctant to make the already hefty download process quite a bit larger. Would rather just get the Boost update sorted finally.

**Comment by joeploijens** [comment]
Understand, but then you would have to keep the version of Boost in Homebrew at the version required by MySQL.

**Comment by DomT4** [comment]
Not usually a major problem. The new Boost has been out for a fairly long time now and the delay this time around resolving issues on that update has been unusually severe.

**Comment by mikemcquaid** [comment]
We've merged boost 1.59 now.

**Comment by DomT4** [comment]
Working on the MySQL update. A fair bit has changed.

**Comment by DomT4** [comment]
Feel free to track #45670. Not opposed to someone submitting the new version to `homebrew/versions` as `keg_only` whilst we wait on resolving failures in Homebrew's core.
