### ISSUE TITLE
wxPython fails to link with wxMac installed with --with-static

### ISSUE THREAD

**Issue by smarek** [Homebrew/homebrew#45381]
Reproduce on Yosemite 10.10.5

```bash
$ brew install wxmac --with-static --with-stl
$ brew install wxpython // can be also with --universal, doesn't make any difference
```

Fails to link with `duplicate symbol __Z18wxWakeUpMainThreadv` error
I've installed successfully without `--with-static` switch as workaround

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by smarek** [comment]
Sorry, forgot to mention, my `brew doctor` comes out clean (CLT/Xcode version, no unbrewed dylibs, up-to-date repository of homebrew), also there is no similar issue. I couldn't gist logs, as I said previously, because I've directly found workaround and I have no secondary env to try to install it badly again.
