### ISSUE TITLE
libgdiplus: Needed for complete mono installation on os x

### ISSUE THREAD

**Issue by haf** [Homebrew/homebrew#45393]
In a 'Xamarin' installation, we have this:

``` bash
$ locate libgdiplus.dylib
/Applications/Xamarin Studio.app/Contents/Resources/lib/monodevelop/AddIns/Xamarin.Sketches/XamarinInteractiveAgentsMac.app/Contents/MonoBundle/libgdiplus.dylib
/Applications/Xamarin.iOS Build Host.app/Contents/MonoBundle/libgdiplus.dylib
/Library/Frameworks/Mono.framework/Versions/3.12.1/lib/libgdiplus.dylib
... etc
```

But not for the homebrew installation.

The mono recipe should depend on libgdiplus: https://github.com/mono/libgdiplus

**Comment by mikemcquaid** [comment]
> The mono recipe should depend on libgdiplus: https://github.com/mono/libgdiplus

Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by haf** [comment]
Yes, but I'm not sure I can pull it all the way (pun intended)...

**Comment by haf** [comment]
```
brew audit libgdiplus
Error: Version value must be a string
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/version.rb:186:in `initialize'
/usr/local/Library/Homebrew/version.rb:176:in `new'
/usr/local/Library/Homebrew/version.rb:176:in `detect'
/usr/local/Library/Homebrew/cmd/audit.rb:966:in `audit_version'
/usr/local/Library/Homebrew/cmd/audit.rb:952:in `audit'
/usr/local/Library/Homebrew/cmd/audit.rb:515:in `block in audit_specs'
/usr/local/Library/Homebrew/cmd/audit.rb:512:in `each'
/usr/local/Library/Homebrew/cmd/audit.rb:512:in `audit_specs'
/usr/local/Library/Homebrew/cmd/audit.rb:904:in `audit'
/usr/local/Library/Homebrew/cmd/audit.rb:58:in `block in audit'
/usr/local/Library/Homebrew/cmd/audit.rb:56:in `each'
/usr/local/Library/Homebrew/cmd/audit.rb:56:in `audit'
/usr/local/Library/brew.rb:146:in `<main>'
```

**Comment by haf** [comment]
<img width="688" alt="screen shot 2015-10-27 at 23 05 59" src="https://cloud.githubusercontent.com/assets/193115/10774060/4f8b3140-7cff-11e5-8e9f-bd19eb6dcb95.png">

For this code

**Comment by DomT4** [comment]
Let's continue review in the https://github.com/Homebrew/homebrew/pull/45404 PR.
