### ISSUE TITLE
"You should probably `chown` [directory]" is an unhelpful error message

### ISSUE THREAD

**Issue by rolandcrosby** [Homebrew/homebrew#45398]
When I run `brew doctor`, I get a few errors along these lines:

```
Warning: /usr/local/bin isn't writable.

This can happen if you "sudo make install" software that isn't managed by
by Homebrew. If a formula tries to write a file to this directory, the
install will fail during the link step.

You should probably `chown` /usr/local/bin
```

What am I supposed to do with this? Even if I know that "`chown`" means I should run `chown [some arguments] /usr/local/bin`, how am I supposed to figure out what arguments to pass? Homebrew created the /usr/local/bin folder on my machine, and apparently detected a problem with its permissions. Therefore, Homebrew should know what the correct permissions are, and should tell me how to set the permissions correctly.

**Comment by mikemcquaid** [comment]
This message could be improved, I agree.

**Comment by leek** [comment]
This warning is apparently triggered in 2 separate places; with the _other_ one having much more helpful instructions. I'm not familiar with the inner workings of Homebrew, but I imagine the error/instructions could be shared somehow. 

Here are the 2 separate warning outputs that I encountered:

**Output when running `brew doctor`**
```sh
Warning: The /usr/local is not writable.
You should probably `chown` /usr/local
```

**Output when running `brew update && brew upgrade`**
```sh
Warning: The /usr/local directory is not writable.
Even if this directory was writable when you installed Homebrew, other
software may change permissions on this directory. Some versions of the
"InstantOn" component of Airfoil are known to do this.

You should probably change the ownership and permissions of /usr/local
back to your user account.
  sudo chown -R $(whoami):admin /usr/local
```

**Comment by rolandcrosby** [comment]
Thanks @leek. It looks like this would be relatively straightforward to refactor in Library/Homebrew/cmd/doctor.rb -- there are a lot of similar messages in there. I would go ahead and make the change myself, but I'd like someone from the Homebrew project to confirm what the correct permissions are for each of the directories that the user is instructed to "`chown`".

**Comment by DomT4** [comment]
I unified everything in https://github.com/Homebrew/homebrew/commit/e30abeae6feb5648e903c23d7f344ab0b71c1e82. Happy to look at further language tweaks if people want to submit a PR for them.

**Comment by mikemcquaid** [comment]
Thanks @DomT4!
