### ISSUE TITLE
homebrew/dupes/libiconv fails to download a patch

### ISSUE THREAD

**Issue by isotopp** [Homebrew/homebrew#45394]
⌁ [kris:~/Source] 7s 1 $ brew install homebrew/dupes/libiconv
==> Installing libiconv from homebrew/homebrew-dupes
==> Downloading http://ftpmirror.gnu.org/libiconv/libiconv-1.14.tar.gz
Already downloaded: /Library/Caches/Homebrew/libiconv-1.14.tar.gz
==> Downloading https://trac.macports.org/export/89276/trunk/dports/textproc/libiconv/files/patch-Makefile.devel

curl: (22) The requested URL returned error: 500 Internal Server Error
Error: Failed to download resource "libiconv--patch"
Download failed: https://trac.macports.org/export/89276/trunk/dports/textproc/libiconv/files/patch-Makefile.devel

Doctor says:

⌁ [kris:~/Source] 5s 1 $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
    homebrew/versions/bison27

(No, I do not want to unlink this brew because I need this to build PHP-7. That's also why I need iconv)

**Comment by vrastogi** [comment]
Seeing the same issue here

**Comment by DomT4** [comment]
`brew doctor` isn't the problem here. MacPorts Trac is having a mare recently and this is a side-effect. We've started migrating many patches away from external sources or inline and into the Homebrew patches repo. The core was changed in such a way a couple weeks ago but `dupes` hadn't been done yet.

**Comment by balsagoth** [comment]
Do you found any workaroud?

**Comment by arianf** [comment]
Did anyone find a workaround?

**Comment by vbauer** [comment]
:+1:

**Comment by DomT4** [comment]
Will be fixed when https://github.com/Homebrew/homebrew-dupes/pull/525 is merged.
