### ISSUE TITLE
postgresql 9.4.5 El Capitan bottle breaks ~/.psql_history

### ISSUE THREAD

**Issue by esambo** [Homebrew/homebrew#45405]
The postgresql 9.4.4 OS X 10.11 El Capitain bottle works fine, but [9.4.5](http://www.postgresql.org/docs/9.4/static/release-9-4-5.html) is [broken](http://www.postgresql.org/message-id/28958.1445875729@sss.pgh.pa.us) and corrupts my `~/.psql_history` file(s) by truncating lines to 1021 characters and encoding spaces as `\040`

[brew gist-logs postgresql](https://gist.github.com/f04e722afa8c702a6c92)

postgresql 9.4.4 bottle works just fine which I can recreate by chaning:
$(brew --prefix)/[Library/Formula/postgresql.rb](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/postgresql.rb)
```
  stable do
    # https://github.com/Homebrew/homebrew/commit/5b3d216
    url "https://ftp.postgresql.org/pub/source/v9.4.4/postgresql-9.4.4.tar.bz2"
    sha256 "538ed99688d6fdbec6fd166d1779cf4588bf2f16c52304e5ef29f904c43b0013"
    #master
    #url "https://ftp.postgresql.org/pub/source/v9.4.5/postgresql-9.4.5.tar.bz2"
    #sha256 "b87c50c66b6ea42a9712b5f6284794fabad0616e6ae420cf0f10523be6d94a39"
```
```
   bottle do
    #https://github.com/Homebrew/homebrew/commit/715e055
    sha256 "c300df1c732b749654f507498ae77531842dbb3bebc1083fe05cb191e5ee6bb3" => :el_capitan
    #master
    #sha256 "57294da21442db822bf719143880000c9a90656188dcf580fafcb6b4e4350f9e" => :el_capitan
```
now I can install 9.4.4 again with `brew install postgresql`
And verify if it works correctly:
```
psql postgres
SELECT version() ;
\q
tail -2 ~/.psql_history-postgres
```
which creates following _correct_ output:
```
SELECT version() ;
\q
```
I can also recreate this 9.4.5 El Capitan bottle error with 9.4.4 if I rebuild it from source instead of using the bottle with: `brew install postgresql --build-from-source --overwrite --verbose` which creates following _wrong_ output with `\040` for spaces:
```
SELECT\040version()\040;
\\q
```

**Comment by esambo** [comment]
I can fix it based on https://github.com/Homebrew/homebrew/issues/42223#issuecomment-135521356 with: 
`sudo xcode-select -s /Library/Developer/CommandLineTools` 
and ignoring the bad bottle with: 
`brew install postgresql --build-from-source --overwrite`

[brew gist-logs postgresql](https://gist.github.com/42103a9ba30921fe32dd)

**Comment by hunsakerbn** [comment]
The problem seems to be that the bottle is built with libedit rather than libreadline. Libedit saves the command line history in a different format than libreadline. That is why you see things like \040  when
you recall the history.
I fixed this by doing:
    $ export LDFLAGS="-L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib"
    $ export CPPFLAGS="-I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include"
    $ brew reinstall postgresql --build-from-source --overwrite
    $ brew link --overwrite postgresql

**Comment by apjanke** [comment]
I'm able to reproduce the bad (linked against `libedit`) build on OS X 10.11.1 / Xcode 7.1, if and only if the CLT are installed.

```
$ otool -L `which psql`
/usr/local/bin/psql:
	/usr/local/lib/libpq.5.dylib (compatibility version 5.0.0, current version 5.7.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
```

Opened PR #45823 with a fix, adding those `-I` and `-L` in the formula.

**Comment by apjanke** [comment]
Bottle is fixed now, with a revision bump. If you do a `brew update` and `brew reinstall postgresql`, you should be able to pour a good (`readline`-linked) build from the bottle.

**Comment by esambo** [comment]
:+1:
