### ISSUE TITLE
Linkapps and Spotlight

### ISSUE THREAD

**Issue by ssbanerje** [Homebrew/homebrew#45429]
I was trying to use homebrewed applications with the Spotlight. This would be useful for apps like MacVim and Emacs.

I see that in commit bf2e6023d1bac08739b4562e19e07db448f0aba3 something was introduced to add Applescripts for each homebrewed application that called `linkapps`. I just wanted to know why this was removed from the master branch.

**Comment by bfontaine** [comment]
See #28798.

**Comment by DomT4** [comment]
Closing per the above. Feel free to comment in that issue if you have a new working suggestion for resolution.
