### ISSUE TITLE
brew cleanup -n

### ISSUE THREAD

**Issue by Ivoah** [Homebrew/homebrew#45432]
It would be nice if `brew cleanup -n` showed the total size of all files that would be removed at the end of the output.

**Comment by chdiza** [comment]
I have a hunch this would unacceptably slow it down.  It's already been slowed-down by printing a size for each individual item.

**Comment by Ivoah** [comment]
Wouldn't it just have to add all the sizes together? I can't imagine that would take any appreciable amount of time.

**Comment by bfontaine** [comment]
We could review a pull-request for that.

**Comment by DomT4** [comment]
Closing in favour of #45642, Thanks!
