### ISSUE TITLE
Need to update FlatBuffers version to 1.2.0

### ISSUE THREAD

**Issue by rw** [Homebrew/homebrew#45438]
There was a new release of FlatBuffers today: https://github.com/google/flatbuffers/releases/tag/v1.2.0

It's the first new version since April (6 months).

For Homebrew contributing, I didn't understand how to recompile a bottle. So, I'm making this an issue instead.

Thanks! :-D

**Comment by DomT4** [comment]
> For Homebrew contributing, I didn't understand how to recompile a bottle.

It'll happen automatically. You'd just need to update the stable URL & `sha256`.

**Comment by DomT4** [comment]
Closing in favour of the PR you filed, Thanks!
