### ISSUE TITLE
maven install failed

### ISSUE THREAD

**Issue by mthhk** [Homebrew/homebrew#45437]
brew install maven  -->  download failed
brew install maven31(2,3) --> download failed too.

**Comment by dunn** [comment]
Can you post `brew gist-logs maven`? Thanks!

**Comment by dunn** [comment]
What's the full output when you run `brew fetch maven`?

**Comment by DomT4** [comment]
Closing due to no response. Download issues on Apache formulae are usually transient issues so it's worth giving it a few hours and trying again in these situations. Please let us know if we can still help, Thanks!
