### ISSUE TITLE
Install issues on El Captain

### ISSUE THREAD

**Issue by SirWilli** [Homebrew/homebrew#45445]
hey,

I did run this command
`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
after that I did run `brew` which said that the command was not found so I checked /usr/local/bin for brew but it is not there. If I try to run the install command again it only says that it is already installed.

I also got this errors in the install:
```
From https://github.com/Homebrew/homebrew
 * [new branch]      master     -> origin/master
error: unable to create file bin/brew (Permission denied)
fatal: Could not reset index file to revision 'origin/master'.
Failed during: git reset --hard origin/master
```
How can I solve this issue?

**Comment by bfontaine** [comment]
Please run `sudo chown -R $(whoami):admin /usr/local`, then uninstall Homebrew and try again:

```sh
# uninstall
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
# install
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

**Comment by SirWilli** [comment]
I already tried the uninstall. It only throws "Failed to locate Homebrew!"

**Comment by bfontaine** [comment]
Try `rm -rf /usr/local/.git` to uninstall it.

**Comment by SirWilli** [comment]
This worked but install still can't create file bin/brew

**Comment by bfontaine** [comment]
Did you run `sudo chown -R $(whoami):admin /usr/local`?

**Comment by SirWilli** [comment]
Yes, I did run that before the install

**Comment by bfontaine** [comment]
Do you use Sophos Anti Virus?

**Comment by SirWilli** [comment]
No, I don't have any anti virus program.

**Comment by bfontaine** [comment]
What does `\ls -l /usr/local` say?

**Comment by SirWilli** [comment]
````
total 80
-rw-r--r--   1 SirWill  admin   3161 29 Okt 13:44 CODEOFCONDUCT.md
-rw-r--r--   1 SirWill  admin   1217 29 Okt 13:44 CONTRIBUTING.md
-rw-r--r--   1 SirWill  admin   1241 29 Okt 13:44 LICENSE.txt
drwxr-xr-x  10 SirWill  admin    340 29 Okt 13:44 Library
drwxr-xr-x   4 SirWill  admin    136 29 Okt 11:38 Qt
-rw-r--r--   1 SirWill  admin   2247 29 Okt 13:44 README.md
-rw-r--r--   1 SirWill  admin  23867 29 Okt 13:44 SUPPORTERS.md
dr-xrwxr-x   5 SirWill  admin    170 15 Okt 08:07 bin
drwxr-xr-x   5 SirWill  admin    170 29 Okt 11:38 share
```

**Comment by bfontaine** [comment]
You can `chmod -R u+w /usr/local/bin` then try again to install Homebrew.

**Comment by SirWilli** [comment]
Now it worked thanks, any idea why I had only read permissions on that folder?

**Comment by bfontaine** [comment]
I don’t know; you should have them.
