### ISSUE TITLE
poppler install freezes forever on make install-recursive

### ISSUE THREAD

**Issue by mofoyoda** [Homebrew/homebrew#45457]
Im trying to install poppler with
`brew install -v poppler`

The process starts with no errors, but freezes on this part:

    Making install in glib
      GEN      stamp-poppler-enums.h
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  install-recursive
    Making install in .
      CC       libpoppler_glib_la-poppler-enums.lo
      CXX      libpoppler_glib_la-poppler-action.lo
      CXX      libpoppler_glib_la-poppler-date.lo
      CXX      libpoppler_glib_la-poppler-document.lo
      CXX      libpoppler_glib_la-poppler-page.lo
      CXX      libpoppler_glib_la-poppler-attachment.lo
      CXX      libpoppler_glib_la-poppler-form-field.lo
      CXX      libpoppler_glib_la-poppler-annot.lo
      CXX      libpoppler_glib_la-poppler-layer.lo
      CXX      libpoppler_glib_la-poppler-media.lo
      CXX      libpoppler_glib_la-poppler-movie.lo
      CXX      libpoppler_glib_la-poppler-cached-file-loader.lo
      CXX      libpoppler_glib_la-poppler-input-stream.lo
      CXX      libpoppler_glib_la-poppler-structure-element.lo
      CXX      libpoppler_glib_la-poppler.lo
      CXXLD    libpoppler-glib.la
      GISCAN   Poppler-0.18.gir

What's going wrong here?

**Comment by DomT4** [comment]
`poppler` can take a while in certain circumstances. How long did you give it?

**Comment by mofoyoda** [comment]
@DomT4 Well about 12 hours for now. It runs on a MBP with almost no visible activity in `top`
My goal is to build `gdal`, that depends on it. I've done that several times before and I don't remember compiling poppler ever took so long.

**Comment by DomT4** [comment]
Yeah, definitely shouldn't take that long, to say the least. Can you run it under `--debug` and see if it prints anything at all at the hang point?

Can you `brew config` and `brew doctor`?

**Comment by jwebb** [comment]
FWIW I had the same problem and upgrading Xcode appears to have fixed it.

**Comment by mikemcquaid** [comment]
@mofoyoda Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by mofoyoda** [comment]
@mikemcquaid Oh, sorry, I forgot to close the issue. Yep - upgrading Xcode solved it completeley. I beg your pardon guys. Thanks a lot for help. Closing now.
