### ISSUE TITLE
brew audit passes on OSX 10.10 but fails 10.9 and 10.11?

### ISSUE THREAD

**Issue by jamesyc** [Homebrew/homebrew#45461]
Take a look here: 

https://travis-ci.org/Homebrew/homebrew/builds/88118517

There's just an added space at the end of a line for this formula, no big dea. The thing is... I'm kind of surprised that **this passes OSX10.10, and fails the other two jobs**. I'd figure this was an all-or-nothing kind of deal. 

Anyone know why this is happening?

**Comment by bfontaine** [comment]
What’s interesting is that both OS X 10.9 and OS X 10.10 have the same Ruby version (2.0.0p481) so it can’t be that.

**Comment by xu-cheng** [comment]
The difference is caused by different commits are tested in different OS. I guess you force pushed the PR during one of build job is in waiting queue.
