### ISSUE TITLE
osm2pgrouting download links are no longer available

### ISSUE THREAD

**Issue by AritzBi** [Homebrew/homebrew#45472]
Hi,

I have just tried to install osm2pgrouting using homebrew and I get the following error:

> ==> Downloading https://github.com/pgRouting/osm2pgrouting/archive/v2.0.0.tar.gz
> ==> Downloading from https://codeload.github.com/pgRouting/osm2pgrouting/tar.gz/v2.0.0

> curl: (22) The requested URL returned error: 404 Not Found
>Error: Failed to download resource "osm2pgrouting"
> Download failed: https://codeload.github.com/pgRouting/osm2pgrouting/tar.gz/v2.0.0

Thanks in advance!

**Comment by bfontaine** [comment]
It seems that upstream changed the tag.

**Comment by bfontaine** [comment]
@AritzBi You can try again; it should work now.
