### ISSUE TITLE
Error: parent directory is world writable but not sticky

### ISSUE THREAD

**Issue by thefirstjustin** [Homebrew/homebrew#45475]
I received this error while running brew reinstall php55-xdebug --build-from-source

**Comment by apjanke** [comment]
Can we get some more info, like the `brew gist-logs` output, and a pointer to where the `php55-xdebug` formula is from? I don't see it in the core taps.

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/homebrew-php#2487
