### ISSUE TITLE
mplayer formula should get updated

### ISSUE THREAD

**Issue by JMoVS** [Homebrew/homebrew#45488]
mplayer, previously last updated in 2013, was just updated but there are all sorts of customuzation in the formula and the latest bottle didn't work on my 10.11 system compared to a source build from HEAD that worked fine. Maybe the maintainer/designer of the tap could update it to 1.2?

**Comment by bfontaine** [comment]
A *tap* is a source for *formulae*. A *formula* describes how to install something. What you’re talking about here is a formula, not a tap :wink: 

> Maybe the maintainer/designer of the tap could update it to 1.2?

We don’t have one maintainer per formula; Homebrew is maintained by the community :smile: 
Would you mind making a pull-request? This should help and I’m happy to answer any question you might have:
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md

**Comment by JMoVS** [comment]
ok, I'll try to work my way through. Thank you for the clarification.

So I have no 1.9 system and I don't know whether the patch is needed, how would go about that? (It didn't harm my compilation, so that's that :D)

**Comment by JMoVS** [comment]
https://github.com/Homebrew/homebrew/pull/45523

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew/commit/e376b430d0c63a7217b3b2cacf27213cbd2dce27.
