### ISSUE TITLE
[req] TorMessengerChat

### ISSUE THREAD

**Issue by anthonyettinger** [Homebrew/homebrew#45500]
https://blog.torproject.org/blog/tor-messenger-beta-chat-over-tor-easily

**Comment by bfontaine** [comment]
We don’t do formulae requests but feel free to submit a pull-request :wink: 
This should help and I’m happy to answer any question you might have:
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md
