### ISSUE TITLE
brew tap behaving badly

### ISSUE THREAD

**Issue by cameron** [Homebrew/homebrew#45502]
Running `brew tap <name/repo>` against a public repo:
- prompted me for github creds
- mysteriously renamed \<repo\> homebrew-\<repo\>, and then failed, because my repo was not named that

Running `brew tap <name/repo> <url>` seemed to disregard the URL, and again prompted me for github creds/failed.

> $ brew --version
> 0.9.5

**Comment by bfontaine** [comment]
Could you please share the repo you’ve used?

**Comment by cameron** [comment]
It was http://github.com/cameron/xz

**Comment by bfontaine** [comment]
Out of curiosity; why do you want to tap this repo? It doesn’t provide any formula nor any external command.

**Comment by cameron** [comment]
Ah, it was a shot in the dark to get around this:
``` brew install xz

     ~/src/keep(master✗)@cams-air-2.local
==> Downloading http://fossies.org/linux/misc/xz-5.2.0.tar.gz

curl: (22) The requested URL returned error: 410 Gone
Trying a mirror...
==> Downloading http://tukaani.org/xz/xz-5.2.0.tar.gz

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "xz"
Download failed: http://tukaani.org/xz/xz-5.2.0.tar.gz```

On Fri, Oct 30, 2015 at 2:23 AM, Baptiste Fontaine <notifications@github.com
> wrote:

> Out of curiosity; why do you want to tap this repo? It doesn’t provide any
> formula nor any external command.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Homebrew/homebrew/issues/45502#issuecomment-152468154>
> .
>

**Comment by bfontaine** [comment]
Please run `brew update`; the URL has been updated to the 5.2.2 release.

**Comment by mikemcquaid** [comment]
Taps need to be named e.g. `cameron/homebrew-xz`  to use the `brew tap cameron/xz` format so that's expected behaviour. `brew tap cameron/xz https://github.com/cameron/xz` works fine for me so there's no bug here.

**Comment by cameron** [comment]
OIC—`brew tap <user/repo>` requires the homebrew prefix, but `brew tap <user/repo> <url>` doesn't. That's a useful clarification, might want to add it to docs/man. 

After running brew update, `brew tap cameron/xz https://github.com/cameron/xz` also works for me. Thanks guys!
