### ISSUE TITLE
w3m failed to build on 10.11.1

### ISSUE THREAD

**Issue by pitpalme** [Homebrew/homebrew#45505]
Installing via

```HOMEBREW_MAKE_JOBS=1 brew install -v w3m 2>&1```

ends with

```Error: w3m 0.5.3 did not build```

Build log is in: https://gist.github.com/pitpalme/ad62201d42ee323119a4

```brew update --rebase``` ran before the latest attempt to install.

**Comment by dunn** [comment]
I can't reproduce this on 10.11.1.  More likely it has to do with your non-standard Homebrew prefix.

**Comment by DomT4** [comment]
Hmm. Can't reproduce here on a non-standard prefix :confounded: -

```
==> Cleaning
==> Finishing up
ln -s ../Cellar/w3m/0.5.3/bin/w3m w3m
ln -s ../Cellar/w3m/0.5.3/bin/w3mman w3mman
ln -s ../../../../Cellar/w3m/0.5.3/share/man/ja/man1/w3m.1 w3m.1
ln -s ../../../Cellar/w3m/0.5.3/share/man/man1/w3m.1 w3m.1
ln -s ../../../Cellar/w3m/0.5.3/share/man/man1/w3mman.1 w3mman.1
ln -s ../Cellar/w3m/0.5.3/share/w3m w3m
==> Summary
🍺  /Users/test/Homebrew/Cellar/w3m/0.5.3: 23 files, 1.7M, built in 31 seconds
```

**Comment by DomT4** [comment]
Would you mind running `brew update` and trying again? I made some slight build tweaks. Nothing directly related, but perhaps we'll get lucky.

**Comment by pitpalme** [comment]
Ran ```brew update --rebase``` but install result is the same.
As far as I can see w3m did not receive any update: https://gist.github.com/e07fb208137a21b00e6e.git :(

**Comment by DomT4** [comment]
It won't show up because the change was non-version related. We no longer show update notices for every minor change.
