### ISSUE TITLE
Support nginx http2 option

### ISSUE THREAD

**Issue by Synchro** [Homebrew/homebrew#45510]
SPDY support was dropped in nginx 1.9.5 and [replaced with HTTP/2](https://www.nginx.com/blog/nginx-1-9-5/) support. The Homebrew package still only lists the `--with-spdy` option. I'm not sure what is needed to compile in http2 support, but it definitely needs to change.

The `--devel` switch may be confused by the old-style reference to the 1.9.x branch as being the 'development' branch; that was always a misnomer - the branches are now 'mainline' (1.9.x) and 'stable' (1.8.x), though the mainline branch is referred to as 'default' [in their repo](http://hg.nginx.org/nginx/branches). I don't know if http2 support will appear in 1.8.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/nginx.rb#L84-L93

**Comment by DomT4** [comment]
And https://github.com/Homebrew/homebrew/commit/4c10e0bc30fb704ac6ae2d7eb3f421a4ed290334.

**Comment by Synchro** [comment]
Ah, great - would be useful to mention that in the info output.

**Comment by mikemcquaid** [comment]
As far as I can tell this is fixed.

**Comment by DomT4** [comment]
We could tack `(http/2 for devel/head)` into the middle of `Compile with support for SPDY module`, I guess, if that's particularly useful.
