### ISSUE TITLE
trafficserver configure flags for hardcoded defaults and locations

### ISSUE THREAD

**Issue by barberio** [Homebrew/homebrew#45513]
Following on from #45190 there's a few bugs that #7623448ec9a9ab7e26786c35cc4b40d8634199ac introduced.

Setting `--sysconfdir=#{etc}` puts all the configuration files in /usr/local/etc rather than what I assume was the intended /usr/local/etc/trafficserver, should be changed to `--sysconfdir=#{etc}/trafficserver`

Setting `--with-user=#{ENV["USER"]}` causes problems with the tapped binaries, as the username from the build environment will be hardcoded into a binary for a different environment. It should not be set.

```
luxo:etc barberio$ traffic_cop -o -d
<1446215424.0000> [DEBUG]: Entering init()
<1446215424.0000> [DEBUG]: Entering init_signals()
<1446215424.0000> [DEBUG]: Entering set_alarm_death()
<1446215424.0000> [DEBUG]: Leaving set_alarm_death()
<1446215424.0000> [DEBUG]: Leaving init_signals()
<1446215424.0000> [DEBUG]: Entering init_config_file()
<1446215424.0000> [DEBUG]: Leaving init_config_file()
<1446215424.0000> [DEBUG]: Entering config_reload_records()
<1446215424.0000> [FATAL]: can't get passwd entry for the admin user 'brew' - [0] Undefined error: 0
```

**Comment by DomT4** [comment]
Sadly the reason we do historically set user is this:

```
<1446233984.0000> [FATAL]: cop couldn't chown the file: '/usr/local/var/trafficserver/manager.lock' for 'nobody' (-2/-2) : [1] Operation not permitted
<1446233984.0000> [FATAL]: cop couldn't chown the file: '/usr/local/var/trafficserver/server.lock' for 'nobody' (-2/-2) : [1] Operation not permitted
```

You can set `CONFIG proxy.config.admin.user_id STRING Bob` in `records.config` but since that line doesn't exist automatically it's harder to "fix" postinstall.

**Comment by barberio** [comment]
Is there a problem with just appending the line to records.config, or applying a patch that inserts it after the boilerplate?

**Comment by DomT4** [comment]
No, we'll be appending it. It's just not as edge-case-proof as I would have liked it to be.

**Comment by barberio** [comment]
Edge-case proof isn't really possible with binary distributions of trafficserver, too much is expected to be site-configured at build time. (At least not without maintaining a unique set of patches...)
