### ISSUE TITLE
Node 5

### ISSUE THREAD

**Issue by aldendaniels** [Homebrew/homebrew#45520]
Node *5.0.0* is now the latest stable release.

**Comment by DomT4** [comment]
Which is why we merged it [20 hours ago](https://github.com/Homebrew/homebrew/commit/b99e20502f3c00fa308e6aba1f003aa2b32e60ae) :wink:. Please `brew update` and it'll be available to upgrade/install.

**Comment by aldendaniels** [comment]
@DomT4 My bad! Thanks. :)
