### ISSUE TITLE
mono and czmq install binaries to same path, but formulas don't declare conflict

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew#45526]
Both mono and czmq install `/usr/local/bin/makecert`. The binaries don't do the same thing, so don't think they can share. Could we rename one of the makecerts, somewhat like the gnu stuff?

**Comment by DomT4** [comment]
Huh. I thought I'd fixed this at some point. Perhaps not.

**Comment by shadowmint** [comment]
fwiw this doesn't actually fix anything, it just marks the two packages as incompatible; so you can't use mono and czmq (or anything it depends on, like fontforge).

You probably want:
`brew unlink mono && brew install czmq && brew link --overwrite mono`
