### ISSUE TITLE
brew search --desc: Invalid usage

### ISSUE THREAD

**Issue by neo1218** [Homebrew/homebrew#45536]
![brew doc](http://7xj431.com1.z0.glb.clouddn.com/屏幕快照%202015-10-31%20下午4.02.41.png)
<hr/>
but when I use <code>brew search --desc</code>
<hr/>
![brew error](http://7xj431.com1.z0.glb.clouddn.com/屏幕快照%202015-10-31%20下午4.01.32.png)
why??

**Comment by UniqMartin** [comment]
`brew search --desc` searches in the description of formulae. For that you have to supply a string to search for, e.g., `brew search --desc python` to find formulae with `python` in their description. I agree that the error message could be a bit more helpful, though …
