### ISSUE TITLE
Cannot find OpenCV

### ISSUE THREAD

**Issue by aayushkapoor206** [Homebrew/homebrew#45549]
I once installed it using Homebrew but it cannot be found now!
It's not listed in braumiester either...
What's the solution?

**Comment by UniqMartin** [comment]
It's part of the `homebrew/science` tap. More information:

- http://brew.sh/homebrew-science/
- https://github.com/Homebrew/homebrew-science

**Comment by aayushkapoor206** [comment]
@UniqMartin Thanks!
