### ISSUE TITLE
xz has install error on 10.11 without emacs installed

### ISSUE THREAD

**Issue by unixorn** [Homebrew/homebrew#45596]
Started to move into a new laptop, and when I went to add imagemagick, I got the following error when brew was pouring the xz bottle:
```shell
$ brew install imagemagick
==> Installing dependencies for imagemagick: xz, libtool, freetype
==> Installing imagemagick dependency: xz
==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.2.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring xz-5.2.2.el_capitan.bottle.tar.gz
Error: No such file or directory - /usr/local/Cellar/xz/5.2.2/share/emacs/site-lisp/xz
$
```

I'm assuming installing emacs would take care of this.

**Comment by dunn** [comment]
No, this is a bug I just introduced.

**Comment by dunn** [comment]
Should be fixed; `brew update` and try again and let me know if you're still getting that error!

**Comment by unixorn** [comment]
@dunn It looks like you fixed it. `brew info xz` no longer complains after `brew update`. I also uninstalled and reinstalled dnsmasq, which I'd also noticed the error message, and no longer see the message either during the `brew install` or with `brew info` afterward.

That was quick! :clap:

**Comment by dunn** [comment]
:ok_woman:
