### ISSUE TITLE
Possible way to handle sandbox issues for Postgres's plugins

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew#45607]
As we can seen in https://github.com/Homebrew/homebrew/pull/41962 and many others PRs, all of Postgres's plugins are broken under sandbox. Moreover, this means all of them are broken during `upgrade/unlink/link/switch` etc.

Considering the amount of plugins for Postgres, vending all of them will soon become unscalable. However, until it's fixed/supported by upstream (See https://github.com/Homebrew/homebrew/issues/10247), Postgres is inherently hostile to Homebrew-style sandboxing where several components are symlinked into a common prefix.

Since there isn't any perfect solution, we may will just accept some hacking middle ground. AFAIK, NixOS handles this by copying all of binaries directly to common prefix, hence breaking its symlink sandbox as well. We may take some similar approach:
* Compile Postgres as usual.
* Move all of binaries in `prefix/bin` to `prefix/libexec/bin-backup`.
* Hard link binaries `prefix/libexec/bin-backup` to `HOMEBREW_PREFIX/bin` during `post_install`.

Clearly, it's still breaking our symlink system. But at least, it can work under sandbox.

Any objection/suggestion/commments? OR should we just vendor all of them inside one mega formula?

cc @mikemcquaid @DomT4

**Comment by mikemcquaid** [comment]
> Any objection/suggestion/commments? OR should we just vendor all of them inside one mega formula?

I think we should do that.

**Comment by xu-cheng** [comment]
Found a new way to fix this, see https://github.com/Homebrew/homebrew/pull/45611#issuecomment-154383042
