### ISSUE TITLE
Failure to install one formula shouldn’t affect the remaining ones

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew#45612]
Examples are considering we just installed homebrew, so nothing was installed with it yet.

Example: `brew install asciinema wrong_name_formula zsh`.
Result: Nothing is installed, because `wrong_name_formula` does not exist.
Expectation: `asciinema` and `zsh` are still valid. These should have been installed.

Example (on El Capitan): `brew install asciinema phantomjs zsh`.
Result: `ascinema` is installed, `phantomjs` isn’t (because it currently doesn’t build on El Capitan), `zsh` isn’t (because the `phantomjs` error exited everything).
Expectation: Even if `phantomjs` fails to install, the rest of the apps should still try to install.

This is particularly noticeable when reinstalling the system from scratch with a script. If a formula was renamed, no longer exists, or has some other impediment to being built in the current system, those should output a warning, yes, but the others should still try to be installed.

**Comment by bfontaine** [comment]
I don’t think that is a surprise:
* `apt-get install` fails when one argument doesn’t exist regardless to its position on the command-line.
* `make a b c` fails without executing the `c` target if the `b` one doesn’t exist

We _could_ add this behavior to `brew install --force` but if you want to install everything even if one formula file you can use `for f in asciinema wrong_name_formula zsh; do brew install $f; done`.

**Comment by vitorgalvao** [comment]
Failing completely when one of them fails does seem like the better behaviour of the two (easier to spot). `make` is different, in that when you have a makefile, presumably all actions are related, and performing `c` when `b` isn’t done may be harmful. The issue here is a failure in installing one app is making other *completely unrelated* apps to fail as well.

But there was no reasoning given, though. Your answer was “others do it this way”. While that may (arguably) answer expectations, it doesn’t explain why homebrew uses this behaviour. Doing it because others do it is a poor reason. Why shouldn’t homebrew do it better? Or is it actually worse due to some reason haven’t though of?

I can certainly do it with a loop, but I can also write a script for every one of the apps I want and build the myself. None of those is optimal.

Either this behaviour should be changed, or there should be a reason as to why it shouldn’t be changed (even if that reason is “we don’t want to”).

**Comment by bfontaine** [comment]
> Doing it because others do it is a poor reason.

This is the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). As a user I expect `foobar install a b c` (where `foobar` is any package manager) to fail as soon as one of `a`, `b` or `c` fails to install. Right now I’m :-1: on this feature but will let other maintainers weight in.

I did more tests: `npm` and `pip` fail like `apt-get`. `gem` installs packages as you expect.

**Comment by vitorgalvao** [comment]
Nice research, thank you fro going through the trouble of checking other package managers.

Your suggestion of adding this to `--force` behaviour seems reasonable and makes sense. I can also see the reverse argument, but `--force` does usually mean “look, I don’t care, just do what I’m telling you as best as you can”.

**Comment by vitorgalvao** [comment]
Either way, thank you for explaining why it works like that now.

**Comment by dunn** [comment]
I think I'd be in favor of continuing to the next formula on error if there's a good way of printing a summary at the end of everything so the user doesn't have to scroll up to see if anything failed to install.

**Comment by mikemcquaid** [comment]
I feel like existing users are probably relying on this behaviour. In my experience people don't tend to read summaries like that so it's unclear to me how we'd be able to do that in as clear a way.

**Comment by vitorgalvao** [comment]
I don’t have any data on this, only a guess, but here’s how I imagine it: you are either installing a bunch of apps manually (i.e. writting the `brew install` command now, by hand) or automatically (i.e. you have it in a script you’re running). Those are the only two options.

For the latter case, it doesn’t really matter when the warning is output, since you either logged it somewhere or you lost it due to the other commands in the script. However, having apps stop installing at an arbitrary point is weird. Suddenly [`z`](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/z.rb) doesn’t work but `asciinema` does, and you have no idea why, so you also don’t know which package caused the issue (or even why) unless you were logging errors. You now have to backtrack and install every missing package *by hand*, instead of just dealing with a single problematic one.

For the former, I don’t see much difference in terms of the attention users pay between stopping now at one package or skipping the package now and then stopping at the end. The difference between “there was an error installing `phantomjs`, you’ll have to install everything you wrote after it by hand, or by copy/pasting your command” and “there was an error installing `phantomjs`, but everything else went fine” is a big one. You could also exit with an error in this case. There is no difference between these in terms of warning to the user — you either paid attention or you didn’t, but one of them is a bigger bore than the other. Both warnings are shown at the exact same point: at the end of the command.

To be clear, I’m not completely against stopping the command at an error, I just thing it is a bad experience to stop the command at an arbitrary point. Not running it at all is a better experience (easier to spot, diagnose, and fix).

**Comment by bfontaine** [comment]
> Even not running it at all is a better experience (easier to spot, diagnose, and fix).

I agree with that.

**Comment by DomT4** [comment]
> As a user I expect foobar install a b c (where foobar is any package manager) to fail as soon as one of a, b or c fails to install.

Agree with Baptiste on this point.

> make is different in that when you have a makefile presumably all actions are related, and performing c when b isn’t done may be harmful. 

That can be the case for `brew` as well. If you're installing `makedepend openssl wget` from source via `brew` and either `makedepend` or `openssl` falls apart on installation the next formula can't install because it has a dependency on the prior formula, so you'd want to bail out there rather than invoking the next formula and going through the dying during install process again.

**Comment by vitorgalvao** [comment]
@DomT4 I disagree, regarding the `make` comparison. `make` can do everything, so running something when something else failed is potentially harmful. `brew install` can only do very limited things, and none of them are harmful. If an installation fails, there’s no harm in letting the others continue (even if they fail as well). Also, like I said:

> when you have a makefile presumably all actions are related

which is not necessarily the case at all when you run a `brew install` command.

**Comment by mikemcquaid** [comment]
> To be clear, I’m not completely against stopping the command at an error, I just think it is a bad experience to stop the command at an arbitrary point.

It's not really arbitrary though, is it?

I think stuff like this really should be a PR rather than a feature request (we don't really do feature requests). It's not clear that changing existing behaviour here will be less (rather than more) confusing or that this won't cause additional issues with e.g. our dependency resolution system without a PR.

**Comment by vitorgalvao** [comment]
> It's not really arbitrary though, is it?

It is to the user. `brew install asciinema phantomjs` leaves me with `asciinema` installed and `phantomjs` not, while `brew install phantomjs asciinema` leaves me with none of them. The arbitrary positioning of arguments (that for all intents and purposes are considered unrelated, as I don’t think any homebrew users thinks their order should be important) affects the outcome of the command.

> we don't really do feature requests

I consider this is a bug (i.e. the software behaves in a certain manner but should behave in another). Adding this behaviour to `--force` would be a feature request, though.

Seems like there is no consensus, though, so I’ll close this. Thank you all for considering it, and for the discussion.
