### ISSUE TITLE
Fix spelling in "brew doctor"

### ISSUE THREAD

**Issue by mk2soldier** [Homebrew/homebrew#45623]
Hello, sorry if this isn't the right place to report this kind of minor bugs.
After running the command `brew doctor` in OS X 10.11.1 I get some warnings, one of them says:
```
Warning: /usr/local/sbin isn't writable.

This can happen if you "sudo make install" software that isn't managed by by Homebrew.
```
Here in bold you can notice that the word **by** is repeated.
I will try my best to report future errors (if any).

Thank you!

**Comment by DomT4** [comment]
Nice spot. Fixed in https://github.com/Homebrew/homebrew/commit/fa7da067a16bd381c0876a76b70c5b27923368b0. Reporting minor issues here is perfect, Thank you! :star2:
