### ISSUE TITLE
pkg-config-0.29 is broken

### ISSUE THREAD

**Issue by gaming-hacker** [Homebrew/homebrew#45622]
who broke it?

==> Installing dependencies for node: pkg-config
==> Installing node dependency: pkg-config
==> Downloading http://pkgconfig.freedesktop.org/releases/pkg-config-0.29.tar.gz
Already downloaded: /Users/glen/abrew/Cache/pkg-config-0.29.tar.gz
==> ./configure --prefix=/Users/glen/abrew/Cellar/pkg-config/0.29 --disable-host-tool --with-internal-gli
==> make
==> make check
Last 15 lines from /Users/glen/Library/Logs/Homebrew/pkg-config/03.make:
../pkg-config --cflags simple :
'-I/sysroot/usr/include' != ''
FAIL: check-sysroot
PASS: check-uninstalled
PASS: check-debug
PASS: check-gtk
PASS: check-tilde
PASS: check-relocatable
==============================================================================
2 of 26 tests failed
Please report to https://bugs.freedesktop.org/enter_bug.cgi?product=pkg-config
==============================================================================
make[2]: *** [check-TESTS] Error 1
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting

**Comment by DomT4** [comment]
Haven't seen this across a whole bunch of unique machines so far. Can you `brew gist-logs pkg-config`, Thanks.

**Comment by gaming-hacker** [comment]
i've tried compiling from the repo and homebrew tarball both have these errors, i'll dump the log next

Undefined symbols for architecture x86_64:
  "_CFRelease", referenced from:
      _find_folder in libglib-2.0.a(libglib_2_0_la-gutils.o)
  "_CFStringGetCString", referenced from:
      _find_folder in libglib-2.0.a(libglib_2_0_la-gutils.o)
  "_CFStringGetCStringPtr", referenced from:
      _find_folder in libglib-2.0.a(libglib_2_0_la-gutils.o)
  "_CFStringGetLength", referenced from:
      _find_folder in libglib-2.0.a(libglib_2_0_la-gutils.o)
  "_CFURLCopyFileSystemPath", referenced from:
      _find_folder in libglib-2.0.a(libglib_2_0_la-gutils.o)
  "_CFURLCreateFromFSRef", referenced from:
      _find_folder in libglib-2.0.a(libglib_2_0_la-gutils.o)
  "_FSFindFolder", referenced from:
      _find_folder in libglib-2.0.a(libglib_2_0_la-gutils.o)
  "_kCFAllocatorSystemDefault", referenced from:
      _find_folder in libglib-2.0.a(libglib_2_0_la-gutils.o)

**Comment by gaming-hacker** [comment]
how long is this `brew gist-logs pkg-config` supposed to take?

**Comment by DomT4** [comment]
Depends on your internet connection, but usually no more than a couple of minutes. I suspect your Beta Xcode is possibly the problem; I've built the new `pkg-config` in a non-default prefix so that doesn't seem to be it, and `pkg-config` has no external dependencies so that's not the issue either.

[This kind of thing](https://gist.github.com/gaming-hacker/6281415cf1a6ba341a13#file-doctor-out-L19-L41) from `doctor` is usually a good bet for build issues, but I don't think they are the issue on this occasion.

**Comment by gaming-hacker** [comment]
i don't think any of those references to config files have anything to do with glib.  to me, it  looks like a glib issue.

**Comment by gaming-hacker** [comment]
still won't install with xcode 7.1 , latest official release
https://gist.github.com/8dcd4cb5f33b1d9c4c67

**Comment by mikemcquaid** [comment]
> who broke it?

This isn't helpful. Please read our code of conduct.

Fix your `brew doctor` errors by removing those things from your PATH.

**Comment by gaming-hacker** [comment]
no, none of those things in my path have anything to do with the broken glib headers. i'm closing the issue and will fix it myself.

**Comment by mikemcquaid** [comment]
Having Anaconda in your PATH is a really common source of breakage. Please read our Code of Conduct before opening issues in future: https://github.com/Homebrew/homebrew/blob/master/CODEOFCONDUCT.md#code-of-conduct
