### ISSUE TITLE
"Doctor" command is poorly named

### ISSUE THREAD

**Issue by ieure** [Homebrew/homebrew#45624]
Given how far the beer / brewing analogy has been taken, I find the choice of "doctor" to be a profoundly disappointing name for the diagnostic facility of Homebrew. I suggest that it be renamed to "brewmaster."

**Comment by DomT4** [comment]
It's *way* too late to change major command names at this point, otherwise all kinds of fun could be had. Thank you for the suggestion though. If it is comforting in terms of logic; if you consume too much brew sometimes you can end up needing the assistance of a `doctor` :wink:.

**Comment by ieure** [comment]
What about renaming, but keeping `doctor` as a deprecated alias?

**Comment by bfontaine** [comment]
See also https://github.com/Homebrew/homebrew-aliases for command aliases.

**Comment by DomT4** [comment]
I'll let @mikemcquaid weigh in, but we're trying to move away from heavy dependency on alcohol related clichés as they tend to translate fairly badly across languages/etc.

You can alias commands locally, as Baptiste beat me to highlighting :smiley:.

**Comment by mikemcquaid** [comment]
> I'll let @mikemcquaid weigh in

Not gonna rename, sorry!
