### ISSUE TITLE
Patch not available in imake

### ISSUE THREAD

**Issue by paulhybryant** [Homebrew/homebrew#45632]
The patch url is unavailable.

==> Installing imake from homebrew/homebrew-x11
==> Downloading http://xorg.freedesktop.org/releases/individual/util/imake-1.0.7.tar.bz2
Already downloaded: /Library/Caches/Homebrew/imake-1.0.7.tar.bz2
==> Downloading https://trac.macports.org/browser/trunk/dports/x11/imake/files/patch-imakemdep.h.diff?rev=127961&format=txt

curl: (22) The requested URL returned error: 500 Internal Server Error

I am not sure whether this is because the source browser is disabled on macports. It has been like this for many days.

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/homebrew-x11#148

**Comment by mistydemeo** [comment]
Should be fixed, thanks for the report!
