### ISSUE TITLE
chicken incorrectly selects 32-bit build env, results in build error

### ISSUE THREAD

**Issue by turanct** [Homebrew/homebrew#45648]
The error is `apply-hack.x86.S:35:suffix or operands invalid for 'call'` and is [described in the official README](http://code.call-cc.org/cgi-bin/gitweb.cgi?p=chicken-core.git;a=blob;f=README;h=2b8b2901284a368628d81be6636424ccbc3cf4a7;hb=b25963183b63530eda36ddca14466baffdff01ee#l463), as is the fix for it.

It boils down to manually setting an argument to the make command. If i knew how to do this in brew, i would create a pull request, so ping me with a howto and i'll do it.

For the time being i fixed it by just changing the [formula file](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/chicken.rb) on my machine with the necessary argument hardcoded.

**Comment by turanct** [comment]
in the mean time, i found out how to do it, working on a PR right now so we can do `brew install --with-force-64-bit chicken` if the error occurs

**Comment by DomT4** [comment]
Closing in favour of #45654, Thanks!
