### ISSUE TITLE
superenv default - documentation bug?

### ISSUE THREAD

**Issue by dwalling** [Homebrew/homebrew#45655]
I had the common "Segmentation fault: 11" issue with Python (trying to install boost-python for caffe). The Common Issues page says: "Check that `which python` points to the python you want" and "Homebrew formulae use a brewed Python if available or, if not so, they use whatever python is in your PATH."

On my system that is only true with --env=std. By default superenv ignores both PATH and the brewed Python and calls /usr/bin/python. Googling for help led me down many irrelevant paths. I got it working by hacking ENV["PATH"] in the Formula and then found the better solution:

```
brew remove boost-python
brew install --build-from-source --env=std boost-python
```

Is this the intended behavior? Should I take a crack at updating that Common Issues section?

https://gist.github.com/anonymous/247cd00d8bac6f5c72c0

**Comment by mikemcquaid** [comment]
> Is this the intended behavior? 

Yep. Homebrew will always use the system Python unless `env=std` or `depends_on :python` is used. In the latter case it'll use the first Python in your PATH (unless it's <2.7 or you're installing from a bottle).

> Should I take a crack at updating that Common Issues section?

That'd be :heart_eyes:

**Comment by DomT4** [comment]
Will let Tim/Mike review the PR you submitted in #45704, but closing the issue in favour of that. Thanks!
