### ISSUE TITLE
Please modify swatchbooker formula to not prompt for 'pip install pillow

### ISSUE THREAD

**Issue by luzpaz** [Homebrew/homebrew#45667]
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/swatchbooker.rb
When running the above formula I get prompted to install pillow via pip. That's an inconvenience

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by luzpaz** [comment]
CC @olivierberten

**Comment by DomT4** [comment]
Closing in favour of #45682, Thanks!

**Comment by luzpaz** [comment]
please offer guidance thanks
