### ISSUE TITLE
how to install mysql5.7

### ISSUE THREAD

**Issue by y284663247** [Homebrew/homebrew#45666]
how to install mysql5.7,now the version is mysql5.6

**Comment by DomT4** [comment]
Working on it. The major version bump = some API breakage, so having to check whether it causes breakage elsewhere.

**Comment by mikemcquaid** [comment]
@DomT4 Thanks!

**Comment by DomT4** [comment]
Feel free to track #45670. Not opposed to someone submitting the new version to `homebrew/versions` as `keg_only` whilst we wait on resolving failures in Homebrew's core.
