### ISSUE TITLE
OS X EL Capitan: parent directory is world writable but not sticky

### ISSUE THREAD

**Issue by garymaxallen** [Homebrew/homebrew#45675]
I try to install ffmpeg through brew. but get this:
brew install ffmpeg --with-fdk-aac
==> Downloading https://ffmpeg.org/releases/ffmpeg-2.8.1.tar.bz2
Already downloaded: /Library/Caches/Homebrew/ffmpeg-2.8.1.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/2.8.1_1 --enable-shared --enab
==> make install
Error: parent directory is world writable but not sticky
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:556:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:217:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:215:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `install'
/usr/local/Library/brew.rb:146:in `<main>'

And then I run brew doctor and get this:
Warning: /tmp is world-writable but does not have the sticky bit set.
Please run "Repair Disk Permissions" in Disk Utility.

Please don't tell me to run "Repair Disk Permissions", El Capitan doesn't have this option.
By the way, I have run sudo chown -R $(whoami):admin /usr/local/bin
Any new ideas?

**Comment by DomT4** [comment]
`sudo chmod +t /tmp`

**Comment by DomT4** [comment]
Closing per the above. Let us know if that doesn't fix it for some reason though. Also tweaked the `doctor` message for El Cap users. Thanks for the issue!

**Comment by garymaxallen** [comment]
Thank you for your suggestions. But I have complied ffmpeg directly without brew.
