### ISSUE TITLE
nex from nvi build segfaults

### ISSUE THREAD

**Issue by jpmoss** [Homebrew/homebrew#45674]
Running `nex` after build and instal of the nvi formula results in:

```
❯ nex
./en_US.UTF-8: No such file or directory
[1]    5986 segmentation fault  nex
```

```
❯ brew --version
0.9.5 (git revision eabf89; last commit 2015-11-04)
```

```
❯ brew info nvi
nvi: stable 1.81.6
44BSD re-implementation of vi
https://sites.google.com/a/bostic.com/keithbostic/vi/
/usr/local/Cellar/nvi/1.81.6 (32 files, 1.1M) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/nvi.rb
==> Dependencies
Required: berkeley-db4 ✔
```

**Comment by dunn** [comment]
OK, I see the same thing on 
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: f39848ecb10c5fbdce40069cfd74eb11c88e03da
Last commit: 8 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.11.1-x86_64
Xcode: 7.1
CLT: N/A
Clang: 7.0 build 700
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.3/bin/ruby
Java: 1.8.0_20
```
Can you try building nvi outside of Homebrew and see if it still happens?

**Comment by jpmoss** [comment]
Building with the patches included in the Formula, the build still results in segfault for nex.

The segfault stops when using the following from https://mirrors.ocf.berkeley.edu/debian/pool/main/n/nvi/nvi_1.81.6-12.debian.tar.xz in `debian/patches/19include_term_h.patch`

```
From: <hesso@pool.math.tu-berlin.de>
Subject: Add <term.h> to the include list to suppress a few warnings.

diff -Naur nvi-1.81.6.orig/cl/cl_funcs.c nvi-1.81.6/cl/cl_funcs.c
--- nvi-1.81.6.orig/cl/cl_funcs.c	2007-11-18 17:41:42.000000000 +0100
+++ nvi-1.81.6/cl/cl_funcs.c	2008-05-01 18:23:08.000000000 +0200
@@ -18,6 +18,7 @@
 #include <sys/time.h>
 
 #include <bitstring.h>
+#include <term.h>
 #include <ctype.h>
 #include <signal.h>
 #include <stdio.h>
diff -Naur nvi-1.81.6.orig/cl/cl_screen.c nvi-1.81.6/cl/cl_screen.c
--- nvi-1.81.6.orig/cl/cl_screen.c	2007-11-18 17:41:42.000000000 +0100
+++ nvi-1.81.6/cl/cl_screen.c	2008-05-01 18:23:02.000000000 +0200
@@ -17,6 +17,7 @@
 #include <sys/queue.h>
 
 #include <bitstring.h>
+#include <term.h>
 #include <errno.h>
 #include <signal.h>
 #include <stdio.h>
```

There are actually a number of patches included in the debian patchset that eliminate problematic bugs outside of the scope of the bug-for-bug rewrite of the BSD 4.4 vi, including the errant "./en_US.UTF-8: No such file or directory" output.

**Comment by jpmoss** [comment]
Would this be more appropriately considered if done as a pull request?

**Comment by dunn** [comment]
Sorry for not following up on this!

Has that patch been submitted upstream?  We're hesitant to carry patches otherwise, since otherwise there's no knowing how long we'll have to maintain them.

**Comment by jpmoss** [comment]
Hard to say, the current source location for 1.81.6 is supposedly http://www.kotnet.org/~skimo/nvi/ which appears to be offline.

**Comment by DomT4** [comment]
Yeah, we've been using a Debian mirror for as long as I remember. Given we already patch the formula heavily I guess the options are:

* Kill the formula, given it being both broken and seemingly dead upstream.
* Swallow more unofficial patching to keep it alive.

**Comment by jpmoss** [comment]
Source is still available: http://repo.or.cz/nvi.git
Most of the last changes were regarding berkeley db features, though I really wouldn't expect this software to be growing given the goal of being bug-for-bug compatible vi. I don't see any commits past the currently available version.
