### ISSUE TITLE
Keep docker version in step with docker-machine version

### ISSUE THREAD

**Issue by bantl23** [Homebrew/homebrew#45681]
When I upgraded from docker v1.7.0 => v1.8.0 the upgrade to docker-machine lagged behind. The same is true for the current release of docker (upgraded from v1.8.0 => v1.9.0).

boot2docker is deprecated in favor of docker-machine. When I upgrade docker and try to use it I get version errors (outdated API) which is related to docker-machine lagging behind docker. I checked the docker-machine github site and there was a release at the time as docker but it wasn't in homebrew just yet.

Would it be possible for docker to be dependent on docker-machine, in some way, that way when I upgrade docker I know that docker-machine version I'm running is compatible with it? (Maybe docker-compose as well? I'm not sure if that will cause similar issues).

Anyway to keep the version in step would be most helpful.

Below are the messages for your consideration:

Docker version:
```
docker --version
Docker version 1.9.0, build 76d6bc9
```
Docker Machine version (should be 0.5.0):
```
docker-machine --version
docker-machine version 0.4.1 (HEAD)
```
Brew update:
```
brew update
Updated Homebrew from 4c764c70 to fd930e67.
No changes to formulae.
```
Docker Machine create VM:
```
docker-machine create -d virtualbox dev
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...
To see how to connect Docker to this machine, run: docker-machine env dev
```
Docker ps -a:
```
docker ps -a
Error response from daemon: client is newer than server (client API version: 1.21, server API version: 1.20)
```

**Comment by mikemcquaid** [comment]
Yeh, we definitely need to work out a way to keep these in sync. I don't want to add a dependency but something that would help would be to add a check to `docker-machine` (and any related formulae)'s `test do` block to verify that the version of `docker` is as we expect. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by bantl23** [comment]
I'm happy to help. I'm just not sure what you mean. Are you asking me to update the docker-machine Formula to the latest or are you asking me to do something else (something with the test block)?

**Comment by bantl23** [comment]
I found a solution docker machine provides a command that allows for upgrading the current VM.

```
docker-machine update <vm>
```

This upgrades the vm to the lastest version supported by docker.

**Comment by 18601673727** [comment]
@bantl23

I tried your way, but
> docker-machine: 'update' is not a docker-machine command. See 'docker-machine --help'.

so
```
docker-machine upgrade <vm>
``` 
works :+1:

**Comment by bantl23** [comment]
Sorry I meant:

`docker-machine upgrade <vm>`
