### ISSUE TITLE
Boost 1.59.0 breaks PostGIS 2.1.7_1

### ISSUE THREAD

**Issue by sethdeckard** [Homebrew/homebrew#45695]
Upgraded packages today and found Boost 1.59 breaks current PostGIS install:

    could not load library "/usr/local/Cellar/postgresql/9.4.5/lib/postgis-2.1.so": 
    dlopen(/usr/local/Cellar/postgresql/9.4.5/lib/postgis-2.1.so, 10): 
    Symbol not found: 
    __ZN5boost7archive21basic_binary_iarchiveINS0_15binary_iarchiveEE13load_overrideERNS0_15class_name_typeEi

Switching back to 1.58.0 works.

**Comment by gfairchild** [comment]
I'm seeing the exact same thing. Literally just came here to report it.

**Comment by DomT4** [comment]
Can either of you `brew reinstall postgis -s` and let us know if that resolves the error for you, Thanks.

**Comment by gfairchild** [comment]
Still getting the error.

**Comment by gfairchild** [comment]
For what it's worth, I've tried totally uninstalling postgres, postgis, and boost, and reinstalling all of them, and the error is still present.

**Comment by DomT4** [comment]
Hmm. How is `postgis` picking the Boost libraries up? There's no explicit dependency in the formula, should there be?

**Comment by oyeanuj** [comment]
Getting the exact same issue as well.

**Comment by gfairchild** [comment]
@DomT4, I'm not sure exactly, but if you `brew uninstall postgres postgis boost` and then `brew install postgis`, postgres and boost are both automatically downloaded and installed.

**Comment by nheeren** [comment]
Could it have anything to do with SFCgal, which is a dependency to postgis I think. See the error here: http://stackoverflow.com/q/33491836/2075003

**Comment by rebelliard** [comment]
```
brew switch boost 1.58.0
``` 

worked for me.

**Comment by xu-cheng** [comment]
This should be fixed by #45611.

**Comment by gfairchild** [comment]
Excellent, it'll be nice to get that merged. Thanks for your work, @xu-cheng :)

**Comment by ivorbosloper** [comment]
@rebelliard `brew switch boost 1.58.0` worked for me as well. Thanks!

**Comment by gazz94** [comment]
I am having the same problem right now, is there a fix?

    brew switch boost 1.58.0

doesn't work for me:
    Error: boost does not have a version "1.58.0" in the Cellar.
    Versions available: 1.59.0

**Comment by bfontaine** [comment]
@gazz94 `brew switch` only works for installed versions.

**Comment by gormster** [comment]
brew uninstall boost
    brew tap homebrew/version
    brew install boost155
    brew link --force boost155

worked for me.
