### ISSUE TITLE
DMD 2.069.0

### ISSUE THREAD

**Issue by John-Colvin** [Homebrew/homebrew#45691]
I'm away from my mac this week, could someone else sort out the update (delete the devel section, update the stable)? Pinging a few people who have previously commited to dmd.rb @tomyun @NfNitLoop @jacknagel

**Comment by mikemcquaid** [comment]
You could do it inline on GitHub or we can just wait until you're back if no-one else picks it up.

**Comment by NfNitLoop** [comment]
Hmm. I can't assign this to me, but I'm about to put up a PR.  That was easy. :)
