### ISSUE TITLE
Half-finished installation makes it impossible to either reinstall or uninstall Homebrew

### ISSUE THREAD

**Issue by callumlocke** [Homebrew/homebrew#45692]
A new coworker just had this problem on his new machine: Yesterday he tried to install Homebrew, but he didn't have admin rights. So it didn't work. So he called IT and waited to be given sudo on his machine.

Today, he's been given admin rights. But when he tried to install Homebrew again, it said something like "Homebrew is already installed, if you want to reinstall then run this command to uninstall it". Then when he ran that uninstall command, it said "Homebrew not installed". Trapped in limbo.

It turns out the first, failed installation had managed to create a whole load of files various locations within /usr/local.

I *kind of* solved the problem by randomly deleting homebrewish looking things from /usr/local until it worked, but there's got to be a better way. The uninstall script should be able to clear out incomplete installations.

**Comment by bfontaine** [comment]
You can `rm -rf /usr/local/.git` then try again. But I agree we should be able to deal with half-finished installations.
