### ISSUE TITLE
libjpeg-turbo bottle not found

### ISSUE THREAD

**Issue by sijad** [Homebrew/homebrew#45716]
% brew install libjpeg-turbo
==> Downloading https://homebrew.bintray.com/bottles/jpeg-turbo-1.4.1.el_capitan.bottle.1.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "jpeg-turbo"
Download failed: https://homebrew.bintray.com/bottles/jpeg-turbo-1.4.1.el_capitan.bottle.1.tar.gz
Warning: Bottle installation failed: building from source.
...

**Comment by bfontaine** [comment]
Thank you for the report @sijad; please run `brew update` and try again; it should work now.
