### ISSUE TITLE
ncmpcpp fails to build and binary seg faults

### ISSUE THREAD

**Issue by maletor** [Homebrew/homebrew#45729]
When compiling from HEAD, [the process fails at boost](https://gist.github.com/45f0c71555426149a1dd).

After installing the binary from a stable version, ncmpcpp seg faults upon running any command, such as asking the version.

**Comment by mikemcquaid** [comment]
Unless this is something you can't reproduce outside of Homebrew it should probably be reported upstream.

**Comment by mistydemeo** [comment]
It looks like ncmcpp was not revisioned when the new boost came in; it's specifically the bottles that are broken, building from source works fine.

**Comment by maletor** [comment]
Thanks for looking at this @mistydemeo. Looks like it should be an easy fix then, right?

**Comment by DomT4** [comment]
`ncmpcpp` doesn't define a test, so wouldn't have been noticed by the CI alas.
