### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by JovankaN** [Homebrew/homebrew#45728]
Error installing git on Lion (https://github.com/Homebrew/homebrew/issues/43332)
Replace GNU patch with git apply for applying patches (https://github.com/Homebrew/homebrew/pull/44494)  , as well as all 
 Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master

**Comment by DomT4** [comment]
> Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master

Usually a permission error or a rebase error locally.

If you do:

```shell
cd $(brew --prefix) && git fetch && git reset --hard origin/master
```
What do you get? Note if you have intentional local changes to your `brew` this will overwrite them.

**Comment by JovankaN** [comment]
thanks for quick respond  , i think i did that too , i didn.t work , so i uninstalled the Homebrew  and reinstalled in again , so now it  worked ...,Thank you
