### ISSUE TITLE
a way to keep sources around?

### ISSUE THREAD

**Issue by davydden** [Homebrew/homebrew#45722]
Is there a way to keep sources around (do not delete the /tmp folder when building a library)?
Maybe some `export HOMEBREW_KEEP_SOURCES=1` or something like this?

That would be necessary for debugging when my program is linked against a couple of other libraries and I am not sure where the bug is mine or their.

**Comment by chdiza** [comment]
Does setting `$HOMEBREW_TEMP` to your desired spot not work?

**Comment by mikemcquaid** [comment]
For this case using `brew install --interactive` or `brew install --debug` probably does what you want.

**Comment by davydden** [comment]
`homebrew_temp` does change the location, but the source files got deleted anyway. I will try `--debug` now...

**Comment by davydden** [comment]
`--debug` does not change anything, after formula is installed the folder with sources and where the formula was built is deleted.

**Comment by davydden** [comment]
... even when `homebrew_temp` points to something else but `/tmp`. So it seems there are internal mechanisms to clean things up. Any way to disable it?

**Comment by DomT4** [comment]
> So it seems there are internal mechanisms to clean things up

Yes, there are.

You could `brew install --interactive` and after `make install` recursively copy the directory elsewhere.

**Comment by davydden** [comment]
copying won't help because if when you compile with debug flags (`-g`) the resulting library will have iside paths to the sources, which are used when you try to debug it with `gdb` or `lldb`.

**Comment by davydden** [comment]
any further options or is it indeed a `wontfix`?

**Comment by mikemcquaid** [comment]
It's a wontfix, sorry.
