### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by XpressoKen** [Homebrew/homebrew#45733]
Trying to do a fresh install of Homebrew but running up against the following issue:

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
It appears Homebrew is already installed. If your intent is to reinstall you
should do the following before running this installer again:
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"

When I run the uninstaller I get this:

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
Failed to locate Homebrew!

When I then try to install it goes through the same loop again, i.e. that Homebrew is already installed.

Any advice?

**Comment by DomT4** [comment]
`rm -r /usr/local/.git`

Should fix it. I'll go do something about our install script later to make this less cryptic.
