### ISSUE TITLE
Error with C++ lib installing graph-tool in OSX El Capitan

### ISSUE THREAD

**Issue by sandrofsousa** [Homebrew/homebrew#45736]
After trying to install graph-tool with Homebrew to python3 (brewed version) I had the following warning:

```Warning: homebrew/science/graph-tool dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.```

and importing the package, the following error was shown:
```
Python 3.5.0 (default, Oct 14 2015, 14:56:38) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import graph_tool as gt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/graph_tool/__init__.py", line 105, in <module>
    dl_import("from . import libgraph_tool_core as libcore")
  File "/usr/local/lib/python3.5/site-packages/graph_tool/dl_import.py", line 57, in dl_import
    exec(import_expr, local_dict, global_dict)
  File "<string>", line 1, in <module>
ImportError: dlopen(/usr/local/lib/python3.5/site-packages/graph_tool/libgraph_tool_core.so, 8): Symbol not found: _PyClass_Type
  Referenced from: /usr/local/opt/boost-python/lib/libboost_python.dylib
  Expected in: flat namespace
 in /usr/local/opt/boost-python/lib/libboost_python.dylib
```

I'm trying to install this package for several times to use it at my MsC. research but it looks like almost impossible to do it. Everything is standard and installed via Brew or Pip. I'm new at programming and Homebrew usage, so please help me understanding what is happening with these C++ compilers and how to avoid this in future.

Thanks!

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/homebrew-science#2982
