### ISSUE TITLE
Update Syncthing

### ISSUE THREAD

**Issue by TimVNL** [Homebrew/homebrew#45749]
Syncthing V0.12 is out a would love a formula update

**Comment by dunn** [comment]
We'd love a PR! Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have any questions!

**Comment by DomT4** [comment]
Closing in favour of https://github.com/Homebrew/homebrew/pull/45764.
