### ISSUE TITLE
Tesseract --with-training-tools: build failure

### ISSUE THREAD

**Issue by skavie** [Homebrew/homebrew#45768]
Ran into problems installing Tesseract OCR with training tools option (Tesseract OCR itself installed fine). Running OSX 10.10.5. 

Gist: https://gist.github.com/0c576c208283fb1fbed4

@DomT4 opening up new issue and gist as instructed.

Console reproduced below.

$brew install --with-training-tools tesseract
==> Downloading https://github.com/tesseract-ocr/tesseract/archive/3.04.00.tar.g
Already downloaded: /Library/Caches/Homebrew/tesseract-3.04.00.tar.gz
==> ./configure --prefix=/usr/local/Cellar/tesseract/3.04.00
Last 15 lines from /Users/andygan/Library/Logs/Homebrew/tesseract/01.configure:
checking host system type... x86_64-apple-darwin14.5.0
checking --enable-graphics argument... yes
checking --enable-embedded argument... no
checking --enable-opencl argument... no
checking --enable-visibility argument... no
checking --enable-multiple-libraries argument... no
checking whether to use tessdata-prefix... yes
checking whether to enable debugging... no
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in /private/tmp/tesseract20151105-28165-13qersx/tesseract-3.04.00': configure: error: cannot run C++ compiled programs. If you meant to cross compile, use--host'.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Tesseract: install denied although conflict is about optional package #44851

**Comment by mikemcquaid** [comment]
> READ THIS: https://git.io/brew-troubleshooting

please do

**Comment by DomT4** [comment]
This is likely the problem:

> Warning: Xcode 7 lacks the 10.10 SDK which can cause some builds to fail.
We recommend installing the Command Line Tools with:
  xcode-select --install
to resolve this issue.

**Comment by DomT4** [comment]
Let us know if we can help further here, Thanks!
