### ISSUE TITLE
macvim builds failed on El capitan

### ISSUE THREAD

**Issue by hu6360567** [Homebrew/homebrew#45772]
gist-log: https://gist.github.com/anonymous/a8723a494312b9367a26

Error Message as below:
checking whether the C compiler works... no
configure: error: in `/private/tmp/macvim20151107-88775-rb2j93/macvim-snapshot-81/src':
configure: error: C compiler cannot create executables

**Comment by hu6360567** [comment]
Sorry for that, it seems that the anaconda python doesn't work along with macvim build.
After remove anaconda from PATH. It builds successfully.

**Comment by cocofifi** [comment]
Same here. Changing the .bash-profile by commenting out the anaconda path for Python allowed install of macvim with brew without problems.

**Comment by mikemcquaid** [comment]
FYI `brew doctor` will warn you about Anaconda being in your PATH.
