### ISSUE TITLE
brew tap a branch?

### ISSUE THREAD

**Issue by adilinden** [Homebrew/homebrew#45788]
Hi,

I forked someones tap and like to make my own changes to the formula.  In order to be able to keep up-to-date with the original authors work and be able to preserve my changes (particular versions) it would conceivably make sense to place my changes in a branch.  But I don't think "brew tap" supports branches unless I am missing something.  How could I go about it?

Adi

**Comment by bfontaine** [comment]
> In order to be able to keep up-to-date with the original authors work and be able to preserve my changes (particular versions) it would conceivably make sense to place my changes in a branch.

Why don’t you make your changes on your master branch and rebase your fork on top of upstream’s when there are new commits? That way you’d be able to keep up-to-date _and_ preserve your changes. Or am I missing something?

**Comment by adilinden** [comment]
That makes sense.  It has been a while since I used Github or did anything more than push, pull, commit using git.  Last instructions I had on maintaining Github forks strongly urged to keep my work in a branch and keeping master in sync with the upstream.

If I understand right, the current Github instructions for syncing a fork describes exactly what you are saying.  https://help.github.com/articles/syncing-a-fork/
