### ISSUE TITLE
freepascal: Missing unit folder in default search path

### ISSUE THREAD

**Issue by kodabb** [Homebrew/homebrew#45783]
I noticed that fpc installed from homebrew does not add the default unit folder in its search path. For example compiling something that uses the GL unit (or any other unit) will return "unit GL not found" despite being compiled and installed.

The current solution is to add something like
``` 
    fpcversion = `fpc -iW`.chomp
    fpcpath = "#{Formula["fpc"].opt_lib}/fpc/"
    args << "-DCMAKE_Pascal_FLAGS=-Fu" + fpcpath + fpcversion + "/units/x86_64-darwin/*/"
```
however this is somewhat fragile and cumbersome when using outside homebrew.

Would it be possible to add the default search path (`/usr/local/lib/fpc/2.6.4/units/x86_64-darwin/` and its subfolders) while installing fpc?

If you need a quick sample feel free to use https://github.com/Homebrew/homebrew-games/blob/master/hedgewars.rb and remove the above line to see its effect.

**Comment by mikemcquaid** [comment]
> Would it be possible to add the default search path (/usr/local/lib/fpc/2.6.4/units/x86_64-darwin/ and its subfolders) while installing fpc?

Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by kodabb** [comment]
I was hoping that the maintainer would do it :p
but it wasn't too hard so i went ahead and did that
hopefully it's not too ugly

**Comment by kodabb** [comment]
A new version of the formula is ready.

**Comment by DomT4** [comment]
Closing in favour of the #46021 PR then.
