### ISSUE TITLE
bottled postgis 2.2.0 still looking for gdal 1.x when gdal 2.0 installed

### ISSUE THREAD

**Issue by mofoyoda** [Homebrew/homebrew#45780]
I've installed postgresql 9.4.5, gdal 2.0 with tweaked formula and then postgis.
When I try to `create extension postgis` in my database, I get this

    ERROR: could not load library "/usr/local/lib/postgresql/rtpostgis-2.2.so":
     dlopen(/usr/local/lib/postgresql/rtpostgis-2.2.so, 10): 
      Library not loaded: /usr/local/opt/gdal/lib/libgdal.1.dylib
      Referenced from: /usr/local/lib/postgresql/rtpostgis-2.2.so
      Reason: image not found
    SQL state: 58P01

Seems like it's looking for older gdal (since postgis was poured from bottle).
Reinstalling with `--build-from-source` option seems to solve this.

**Comment by DomT4** [comment]
How do you have `gdal` 2.x installed? The Homebrew formula is still on `1.11.3`, which is what `postgis` would have been bottled against.

**Comment by DomT4** [comment]
Closing per lack of response. Let us know if we can help somehow, Thanks!
