### ISSUE TITLE
could not symlink....

### ISSUE THREAD

**Issue by sunnee5150** [Homebrew/homebrew#45790]
i have been trying to reinstall node via homebrew and get the following:

Error: Could not symlink share/systemtap/tapset/node.stp
/usr/local/share/systemtap/tapset is not writable.

so, I tried 

sudo chown -R $USER /usr/local

I get 

chown: ernest: illegal user name

whoami yields "ernest son".  so i tried replacing that  for $USER, same result

**Comment by tdsmith** [comment]
Hmm. Please try `sudo chown -R "$USER" /usr/local`.

**Comment by sunnee5150** [comment]
voila!

brew link --overwrite node now works!

node and npm both installed !!  Thank you tdsmith!!!
