### ISSUE TITLE
Error Installing Node with Homebrew

### ISSUE THREAD

**Issue by DanielCagliostro** [Homebrew/homebrew#45794]
Hi I am having issues installing Node.
I updated npm and after that everything went downhill.

I uninstalled node and when trying to reinstall it im getting this:

dan-ggs-macbook:~ dangg$ brew doctor
Your system is ready to brew.
dan-ggs-macbook:~ dangg$ brew install node
==> Downloading https://nodejs.org/dist/v5.0.0/node-v5.0.0.tar.gz
######################################################################## 100.0%
==> Downloading https://ssl.icu-project.org/files/icu4c/56.1/icu4c-56_1-src.tgz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/node/5.0.0 --without-npm --with-intl=small-icu
==> make install
Last 15 lines from /Users/dangg/Library/Logs/Homebrew/node/02.make:
Sun Nov 08 11:45:02 +0000 2015

make
install

/usr/bin/make -C out BUILDTYPE=Release V=1
llvm-g++ '-D_DARWIN_USE_64_BIT_INODE=1' -I../deps/gtest -I../deps/gtest/include -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF /private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/.deps//private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o.d.raw -c -o /private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o ../deps/gtest/src/gtest-death-test.cc
llvm-g++ '-D_DARWIN_USE_64_BIT_INODE=1' -I../deps/gtest -I../deps/gtest/include -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF /private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/.deps//private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o.d.raw -c -o /private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o ../deps/gtest/src/gtest-filepath.cc
cc1plus: error: unrecognized command line option "-std=gnu++0x"
make[1]: *** [/private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o] Error 1
make[1]: *** Waiting for unfinished jobs....
cc1plus: error: unrecognized command line option "-std=gnu++0x"
make[1]: *** [/private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o] Error 1
make: *** [node] Error 2

READ THIS: https://git.io/brew-troubleshooting

Thanks in advance for your time.

Kind Regards

Dan

**Comment by dunn** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Follow the instructions there please, and post your full `brew gist-logs node`. Thanks!

**Comment by DomT4** [comment]
Particularly interested in the compiler being used here, from those `gist-logs`.

**Comment by DanielCagliostro** [comment]
@invalid-email-address Anonymous created this gist 8 minutes ago.
View 57  01.configure
@@ -0,0 +1,57 @@
+Sun Nov 08 11:44:57 +0000 2015
+
+./configure
+--prefix=/usr/local/Cellar/node/5.0.0
+--without-npm
+--with-intl=small-icu
+
+WARNING: C++ compiler too old, need g++ 4.8 or clang++ 3.4 (CXX=llvm-g++)
+creating  ./icu_config.gypi
+* Using ICU in ./deps/icu
+creating  ./icu_config.gypi
+{ 'target_defaults': { 'cflags': [],
+                       'default_configuration': 'Release',
+                       'defines': [],
+                       'include_dirs': [],
+                       'libraries': []},
+  'variables': { 'asan': 0,
+                 'gas_version': 0,
+                 'host_arch': 'x64',
+                 'icu_data_file': 'icudt56l.dat',
+                 'icu_data_in': '../../deps/icu/source/data/in/icudt56l.dat',
+                 'icu_endianness': 'l',
+                 'icu_gyp_path': 'tools/icu/icu-generic.gyp',
+                 'icu_locales': 'en,root',
+                 'icu_path': './deps/icu',
+                 'icu_small': 'true',
+                 'icu_ver_major': '56',
+                 'node_byteorder': 'little',
+                 'node_install_npm': 'false',
+                 'node_prefix': '/usr/local/Cellar/node/5.0.0',
+                 'node_release_urlbase': '',
+                 'node_shared_http_parser': 'false',
+                 'node_shared_libuv': 'false',
+                 'node_shared_openssl': 'false',
+                 'node_shared_zlib': 'false',
+                 'node_tag': '',
+                 'node_use_dtrace': 'true',
+                 'node_use_etw': 'false',
+                 'node_use_lttng': 'false',
+                 'node_use_openssl': 'true',
+                 'node_use_perfctr': 'false',
+                 'openssl_fips': '',
+                 'openssl_no_asm': 0,
+                 'python': '/usr/local/opt/python/bin/python2.7',
+                 'target_arch': 'x64',
+                 'uv_parent_path': '/deps/uv/',
+                 'uv_use_dtrace': 'true',
+                 'v8_enable_gdbjit': 0,
+                 'v8_enable_i18n_support': 1,
+                 'v8_no_strict_aliasing': 1,
+                 'v8_optimized_debug': 0,
+                 'v8_random_seed': 0,
+                 'v8_use_snapshot': 1,
+                 'want_separate_host_toolset': 0}}
+creating  ./config.gypi
+creating  ./config.mk
+WARNING: warnings were emitted in the configure phase
View 16  01.configure.cc
@@ -0,0 +1,16 @@
+llvm-g++ called with: -E -P -x c++ -
+superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
+superenv executed: llvm-g++-4.2 -E -P -x c++ - -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
+
+llvm-gcc called with: -E -P -x c -
+superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
+superenv executed: llvm-gcc -E -P -x c - -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
+
+llvm-gcc called with: -Wa,-v -c -o /dev/null -x assembler /dev/null
+superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
+superenv executed: llvm-gcc -Wa,-v -c -o /dev/null -x assembler /dev/null -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
+
+llvm-gcc called with: -dM -E -
+superenv added:    -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
+superenv executed: llvm-gcc -dM -E - -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
+
View 47  02.make
@@ -0,0 +1,47 @@
+Sun Nov 08 11:45:02 +0000 2015
+
+make
+install
+
+/usr/bin/make -C out BUILDTYPE=Release V=1
+  llvm-g++ '-D_DARWIN_USE_64_BIT_INODE=1' -I../deps/gtest -I../deps/gtest/include  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF /private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/.deps//private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o.d.raw  -c -o /private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o ../deps/gtest/src/gtest-death-test.cc
+  llvm-g++ '-D_DARWIN_USE_64_BIT_INODE=1' -I../deps/gtest -I../deps/gtest/include  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF /private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/.deps//private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o.d.raw  -c -o /private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o ../deps/gtest/src/gtest-filepath.cc
+cc1plus: error: unrecognized command line option "-std=gnu++0x"
+make[1]: *** [/private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o] Error 1
+make[1]: *** Waiting for unfinished jobs....
+cc1plus: error: unrecognized command line option "-std=gnu++0x"
+make[1]: *** [/private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o] Error 1
+make: *** [node] Error 2
+
+HOMEBREW_VERSION: 0.9.5
+ORIGIN: https://github.com/Homebrew/homebrew.git
+HEAD: fda36921cb2d2d7875a8c2e0bc44715477ecf5e0
+Last commit: 5 hours ago
+HOMEBREW_PREFIX: /usr/local
+HOMEBREW_REPOSITORY: /usr/local
+HOMEBREW_CELLAR: /usr/local/Cellar
+HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
+CPU: dual-core 64-bit core2
+OS X: 10.6.8-i386
+Xcode: 3.2.6
+CLT: N/A
+GCC-4.0: build 5494
+GCC-4.2: build 5666
+LLVM-GCC: build 2335
+Clang: 1.7 build 77
+X11: 2.7.8 => /opt/X11
+System Ruby: 1.8.7-p358
+Perl: /usr/bin/perl
+Python: /usr/local/opt/python/bin/python => /usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
+Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
+Java: 1.6.0_65-b14-462
+
+HOMEBREW_CC: llvm-gcc
+HOMEBREW_CXX: llvm-g++
+MAKEFLAGS: -j2
+CMAKE_PREFIX_PATH: /usr/local
+CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
+CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
+PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.6
+ACLOCAL_PATH: /usr/local/share/aclocal
+PATH: /usr/local/opt/python/bin:/usr/local/Library/ENV/4.3:/usr/local/opt/pkg-config/bin:/usr/bin:/bin:/usr/sbin:/sbin
View 10  02.make.cc
@@ -0,0 +1,10 @@
+llvm-g++ called with: -D_DARWIN_USE_64_BIT_INODE=1 -I../deps/gtest -I../deps/gtest/include -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF /private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/.deps//private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o.d.raw -c -o /private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o ../deps/gtest/src/gtest-filepath.cc
+superenv removed:  -gdwarf-2 -arch x86_64 -Wall -Wendif-labels -W
+superenv added:    -pipe -w -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
+superenv executed: llvm-g++-4.2 -pipe -w -Os -march=core2 -D_DARWIN_USE_64_BIT_INODE=1 -I../deps/gtest -I../deps/gtest/include -mmacosx-version-min=10.5 -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF /private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/.deps//private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o.d.raw -c -o /private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o ../deps/gtest/src/gtest-filepath.cc -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
+
+llvm-g++ called with: -D_DARWIN_USE_64_BIT_INODE=1 -I../deps/gtest -I../deps/gtest/include -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF /private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/.deps//private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o.d.raw -c -o /private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o ../deps/gtest/src/gtest-death-test.cc
+superenv removed:  -gdwarf-2 -arch x86_64 -Wall -Wendif-labels -W
+superenv added:    -pipe -w -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
+superenv executed: llvm-g++-4.2 -pipe -w -Os -march=core2 -D_DARWIN_USE_64_BIT_INODE=1 -I../deps/gtest -I../deps/gtest/include -mmacosx-version-min=10.5 -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF /private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/.deps//private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o.d.raw -c -o /private/tmp/node20151108-2359-1rqoxpy/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o ../deps/gtest/src/gtest-death-test.cc -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
+
View 22  config.out
@@ -0,0 +1,22 @@
+HOMEBREW_VERSION: 0.9.5
+ORIGIN: https://github.com/Homebrew/homebrew.git
+HEAD: 61cdfe344ff90a14e2444a6118671c0abaaa7812
+Last commit: 4 hours ago
+HOMEBREW_PREFIX: /usr/local
+HOMEBREW_REPOSITORY: /usr/local
+HOMEBREW_CELLAR: /usr/local/Cellar
+HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
+CPU: dual-core 64-bit core2
+OS X: 10.6.8-i386
+Xcode: 3.2.6
+CLT: N/A
+GCC-4.0: build 5494
+GCC-4.2: build 5666
+LLVM-GCC: build 2335
+Clang: 1.7 build 77
+X11: 2.7.8 => /opt/X11
+System Ruby: 1.8.7-p358
+Perl: /usr/bin/perl
+Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
+Ruby: /Users/dangg/.rvm/rubies/ruby-2.1.2/bin/ruby
+Java: 1.6.0_65-b14-462
View 1  doctor.out
@@ -0,0 +1 @@
+Your system is ready to brew.

**Comment by DomT4** [comment]
Turns out the new Node is a lot fussier about what compiler you use it with. https://github.com/Homebrew/homebrew/commit/278337dcaa346911306d5e63b72522ad0d4570d8 will stop it attempting to build with unsupported compilers.
