### ISSUE TITLE
Trouble with GIT

### ISSUE THREAD

**Issue by anthonybrown** [Homebrew/homebrew#45797]
Not sure if this is the correct place to be filling this issue.

I've noticed that I have to submit my password each time I do a push.
I've followed the `setup ssh keys` walkthroughs on github many times and
know it by heart. Seems like when I do a push, git asks me for my password and
generates another IP address and adds it to my `known_hosts` file.

I use SSH and not the HTTPS protocol, so it's not that.
Am I missing something or doing something wrong?
Thanks for any help.

**Comment by mikemcquaid** [comment]
Sorry, this isn't related to Homebrew. I'd suggest contacting GitHub support who may be able to help you.

**Comment by anthonybrown** [comment]
@mikemcquaid oh, sorry to bother you, I will contact them. :skull: lol
