### ISSUE TITLE
brew fails everything besides info on OSX 10.8

### ISSUE THREAD

**Issue by wileyyugioh** [Homebrew/homebrew#45814]
joe:~ joe$ brew doctor
Error: /usr/local/Library/Homebrew/keg_relocate.rb:7: undefined (?...) sequence: /(?:^|\/)(?<suffix>(?<name>[^\/]+)\.framework\/(?:Versions\/[^\/]+\/)?\k<name>)$/
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/keg.rb:2:in `require'
/usr/local/Library/Homebrew/keg.rb:2
/usr/local/Library/Homebrew/formula_pin.rb:1:in `require'
/usr/local/Library/Homebrew/formula_pin.rb:1
/usr/local/Library/Homebrew/formula.rb:3:in `require'
/usr/local/Library/Homebrew/formula.rb:3
/usr/local/Library/Homebrew/cmd/missing.rb:1:in `require'
/usr/local/Library/Homebrew/cmd/missing.rb:1
/usr/local/Library/Homebrew/cmd/doctor.rb:1:in `require'
/usr/local/Library/Homebrew/cmd/doctor.rb:1
/usr/local/Library/brew.rb:72:in `require'
/usr/local/Library/brew.rb:72:in `require?'
/usr/local/Library/brew.rb:123

============================

joe:~ joe$ brew update
Error: /usr/local/Library/Homebrew/keg_relocate.rb:7: undefined (?...) sequence: /(?:^|\/)(?<suffix>(?<name>[^\/]+)\.framework\/(?:Versions\/[^\/]+\/)?\k<name>)$/
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/keg.rb:2:in `require'
/usr/local/Library/Homebrew/keg.rb:2
/usr/local/Library/Homebrew/formula_pin.rb:1:in `require'
/usr/local/Library/Homebrew/formula_pin.rb:1
/usr/local/Library/Homebrew/formula.rb:3:in `require'
/usr/local/Library/Homebrew/formula.rb:3
/usr/local/Library/Homebrew/descriptions.rb:1:in `require'
/usr/local/Library/Homebrew/descriptions.rb:1
/usr/local/Library/Homebrew/cmd/tap.rb:2:in `require'
/usr/local/Library/Homebrew/cmd/tap.rb:2
/usr/local/Library/Homebrew/cmd/update.rb:1:in `require'
/usr/local/Library/Homebrew/cmd/update.rb:1
/usr/local/Library/brew.rb:72:in `require'
/usr/local/Library/brew.rb:72:in `require?'
/usr/local/Library/brew.rb:123

I suspect this has to do with a ruby version, as seen here: https://github.com/aaronjensen/sass-media_query_combiner/issues/2

**Comment by mikemcquaid** [comment]
Should be fixed with https://github.com/Homebrew/homebrew/commit/98c044abeb949e9d695a1098e6c3107396b3255e but you'll need to `/usr/local; git fetch; git reset --hard origin/master`. Let me know if it doesn't work!
