### ISSUE TITLE
compinit -i just echoes back everything when root and shell /usr/local/bin/zsh

### ISSUE THREAD

**Issue by nhooyr** [Homebrew/homebrew#45811]
when I install zsh through brew, and I try running it as root, it works fine. I run "compinit -i". But when I do it as root, instead of running it, it echoes back everything. Funny thing is that this only happens with "/usr/local/bin/zsh" as my shell. with "/bin/zsh" it works perfectly. 

    # Load and initialize the completion system ignoring insecure directories.
    autoload -Uz compinit && compinit -i

Thats the line in my .zshrc that loads the completion system.

This is what happens when /usr/local/bin/zsh is my shell for root and I run "su" to login as root.
    
<img width="1440" alt="screen shot 2015-11-08 at 3 20 16 pm" src="https://cloud.githubusercontent.com/assets/10180857/11022411/3b832d02-862c-11e5-8f3d-b81935451a40.png">

It works perfectly if I am my local user or I set the root shell to /bin/zsh. Not sure what's wrong.

**Comment by mikemcquaid** [comment]
I'm not 100% sure how this is meant to work and if it's a Homebrew problem.

**Comment by DomT4** [comment]
I think @apjanke does a lot of `zsh` stuff. Perhaps he can shed some light.

**Comment by apjanke** [comment]
This sounds like a corrupted `~/.zcompdump` file. Try doing `rm ~/.zcompdump*` and restarting your session.

Stuff like this wrt Homebrew's `zsh` is usually triggered by "insecure" directories on `$fpath`. `zsh` considers a directory owned by a user that is not `root` and not the current user to be insecure. If you're doing the normal thing and running `brew` as a normal user, then `/usr/local/share/zsh/site-functions/` is owned by you, and is considered insecure for `root`. You can run `compaudit` to see the directories it considers problematic. With `/bin/zsh`, its `/usr/share/zsh/` hierarchy is owned by `root`, so there are no insecure directories on it.

Normally with `-i`, this just disables completions when you're running as `root`. But there's some interaction with the `~/.zcompdump` cache files that ends up messing things up and you get this big spew of output. I'm not sure exactly what sequence of events causes it, but deleting the `~/.zcompdump*` file(s) is usually enough to fix it.

**Comment by nhooyr** [comment]
thank you so much, that fixed it!
