### ISSUE TITLE
How do I control what homebrew installs?

### ISSUE THREAD

**Issue by adilinden** [Homebrew/homebrew#45824]
Hi,

I am building a formula that installs via "make install".  The result is that a lot of stuff is being installed that is not needed.  I tried "keg_only" and then manually linked.  That works of course, but defeats the purpose.  How can I have "make install" install in cellar, but then manually define in the formula what is installed/linked into /usr/local?

Thanks,
Adi

**Comment by tdsmith** [comment]
One strategy is to install to `libexec` instead of `prefix` and then use e.g. `bin.install_symlink libexec/"bin/file1", ...` to create links for the files you want to be visible.

**Comment by mikemcquaid** [comment]
What files do you not want installed/linked?

**Comment by adilinden** [comment]
I figured it out.  I was able to massage the install locations by passing environment variables at `make install` stage.  It placed everything into the `Cellar` as need.  Looking at the Debian build process for the package helped a lot to gather ideas from.
