### ISSUE TITLE
libnice without gstreamer

### ISSUE THREAD

**Issue by acornejo** [Homebrew/homebrew#45827]
libnice is a library for the ICE protocol used for NAT traversal's. While libnice can be used by gstreamer, gstreamer IS NOT a requirement for libnice.

The libnice formula should not have a hard dependency on gstreamer.

Patch to make gstreamer optional is here:

https://gist.github.com/wancw/8b945abd3611212a1a04

Happy to provide a pull request.

**Comment by DomT4** [comment]
Feel free to submit a PR.

Your diff isn't quite right. You'd want to do something like:

```diff
diff --git a/Library/Formula/libnice.rb b/Library/Formula/libnice.rb
index ac906a6..77f5e60 100644
--- a/Library/Formula/libnice.rb
+++ b/Library/Formula/libnice.rb
@@ -14,7 +14,7 @@ class Libnice < Formula
 
   depends_on "pkg-config" => :build
   depends_on "glib"
-  depends_on "gstreamer"
+  depends_on "gstreamer" => :optional
 
   def install
     args = %W[
@@ -24,7 +24,9 @@ class Libnice < Formula
       --disable-silent-rules
     ]
 
-    system "./configure",  *args
+    args << "--without-gstreamer" << "--without-gstreamer-0.10" if build.without? "gstreamer"
+
+    system "./configure", *args
     system "make", "install"
   end
 end
```

I'd be tempted to keep the dependency as `:recommended` if we have to specifically exclude it with options, unless there's some explanation for that behaviour upstream, but can have that discussion in a PR.

**Comment by acornejo** [comment]
thanks @DomT4 , i'll submit a PR soon. The diff wasn't mine, I found it on google when i searched for "homebrew libnice without gstreamer", but i'll submit essentially what you suggested and we can discuss further in the PR.
