### ISSUE TITLE
Varnish 4.1.0?

### ISSUE THREAD

**Issue by craigcarnell** [Homebrew/homebrew#45831]

**Comment by bfontaine** [comment]
What is the issue?

**Comment by craigcarnell** [comment]
@bfontaine Hi, the latest Varnish release is 4.1.0 so the brew formula needs updating to point to it. Thanks

**Comment by bfontaine** [comment]
Could you try a pull-request? This should help and I’m happy to answer any question you might have:
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

**Comment by xu-cheng** [comment]
We will review a PR.
