### ISSUE TITLE
$(brew --prefix) command inside ~/.bash_profile hangs and continuously spawns instances of xcodebuild on OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by otaran** [Homebrew/homebrew#45839]
### Steps To Reproduce

1. Add following code to `~/.bash_profile`:

```shell
echo $(brew --prefix)
```

2. Close all Terminal windows and tabs
3. Restart OS
4. Open Terminal

### Expected Result

- Terminal opens new tab and shows command prompt in a few seconds

### Actual Result

- Terminal opens new tab, but doesn't show command prompt for an extended period of time
- When breaking iniatialization process, following backtrace is shown:

```shell
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213:in ``': Interrupt
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213:in `<module:RbConfig>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:5:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:8:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:8:in `<top (required)>'
	from <internal:gem_prelude>:1:in `require'
	from <internal:gem_prelude>:1:in `<compiled>'
```

- Running command `ps aux | grep Xcode` shows following output:

```shell
oleksii          5352   0.0  0.6  2654948  46876 s000  S    12:24PM   0:00.47 /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk macosx -version Path
oleksii          5349   0.0  0.0  2436456   1068 s000  S    12:24PM   0:00.01 sh -c xcode-select --print-path >/dev/null 2>&1 && xcrun --sdk macosx --show-sdk-path 2>/dev/null
oleksii          5277   0.0  0.6  2654948  46968 s000  S    12:24PM   0:00.47 /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk macosx -version Path
oleksii          5274   0.0  0.0  2436456   1068 s000  S    12:24PM   0:00.01 sh -c xcode-select --print-path >/dev/null 2>&1 && xcrun --sdk macosx --show-sdk-path 2>/dev/null
oleksii          5200   0.0  0.6  2653924  47196 s000  S    12:23PM   0:00.49 /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk macosx -version Path
oleksii          5197   0.0  0.0  2436456   1068 s000  S    12:23PM   0:00.00 sh -c xcode-select --print-path >/dev/null 2>&1 && xcrun --sdk macosx --show-sdk-path 2>/dev/null
# and so on
```

### Other Notes

`brew --prefix` is used by `bash-completion` formulae to load completions at the beginning of session using the following code:

```shell
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi
```

There is a way to work around this issue by hardcoding Homebrew home directory (`/usr/local/` in my case).

**Comment by mistydemeo** [comment]
What version of OS X and Xcode are you using? Are you able to run `brew --prefix` manually outside of your `bash_profile`?

**Comment by otaran** [comment]
OS X 10.11.1
Xcode 7.1 (7B91b)

Yes, running `brew --prefix` from command line works fine. FWIW, I have `rbenv` formulae installed, maybe it somehow messes up with Homebrew?

**Comment by mistydemeo** [comment]
It's possible, do you have it active? Does this happen if your `.bash_profile` contains only the `echo $(brew --prefix)` line you listed?

**Comment by otaran** [comment]
No, disabling `rbenv` didn't help: with `.bash_profile` consisting of single line `echo $(brew --prefix)` it still takes about 3-5 minutes to initialize Terminal session after reboot.

**Comment by apjanke** [comment]
FWIW, I'm unable to reproduce on OS X 10.11.1 with Xcode 7.1, on a machine I've been using with Homebrew for a while. No RVM.

**Comment by bfontaine** [comment]
What is does `bash --login --norc -x` print when `.bash_profile` consists of `echo $(brew --prefix)` only?

**Comment by otaran** [comment]
@bfontaine, output is at http://pastebin.com/20LwRDyP

**Comment by otaran** [comment]
In case it does matter: I didn't do a clean install of El Capitan, I was using Homebrew on Yosemite and then upgraded it to El Capitan. `brew doctor` doesn't find any issues.

**Comment by bfontaine** [comment]
Does `bash --login` hangs as well?

**Comment by otaran** [comment]
No, it doesn't:

```shell
$ time bash --login -c 'exit'
/usr/local

real	0m0.078s
user	0m0.048s
sys	0m0.030s
```

**Comment by otaran** [comment]
Here is what Terminal prints out when `.bash_profile` contains only `time brew --prefix`:

```shell
Last login: Mon Nov  9 15:02:11 on console
/usr/local

real	3m5.647s
user	2m18.747s
sys	0m44.663s
```

**Comment by apjanke** [comment]
What's in your `~/.bashrc`, if anything? And what command do you have your Terminal profile set up to run? The fact that `bash --login` doesn't hang indicates that the `bashrc` (used for interactive non-login shells) may be involved. Though typically the `bash` run by a terminal session is itself a login shell. Which suggests maybe something that gets set in the environment in the topmost shell of a session is having an effect.

Here's the `rbconfig.rb` line 13 where the interrupt happens.

```
  CONFIG["includedir"] = (ENV['SDKROOT'] || (File.exists?(File.join(CONFIG['prefix'],'include')) ? '' : %x(xcode-select --print-path >/dev/null 2>&1 && xcrun --sdk macosx --show-sdk-path 2>/dev/null).chomp)) + "$(prefix)/include"
```

Looks like it's `ruby`'s startup code and not `brew`'s own code which is shelling out to that `xcode-select && xcrun`, which is run under `sh`. On OS X, `/bin/sh` is a `bash`, so it's emulating a plain POSIX shell. Is it possible that something is making it think it's an interactive or login shell, or a `bash` instead of an `sh`, so the `sh` that Ruby's calling out to is itself running the `bash` startup files and trying to run `brew --prefix` as part of the startup sequence, which turns into a recursive process?

There were substantial changes in the system `/etc/*bash*` files between Yosemite and El Capitan. Maybe something left over during the upgrade process is affecting things. Though I don't see any clues in that trace.

Can you post the output you get if `~/.bash_profile` contains just `env` (with passwords & tokens removed, if there are any)?

**Comment by xu-cheng** [comment]
This shouldn't be homebrew related. `brew --prefix` [doesn't actually load any Homebrew code](https://github.com/Homebrew/homebrew/blob/master/Library/brew.rb#L7-L10).

**Comment by otaran** [comment]
@xu-cheng this issue is reproducible with `brew --version`:

```shell
Last login: Tue Nov 10 10:34:00 on console
0.9.5 (git revision 84c75; last commit 2015-11-10)

real	4m45.095s
user	3m26.324s
sys	1m5.136s
```

**Comment by mistydemeo** [comment]
The traceback shows this occurring within Rubygems' startup. This is happening as a part of Ruby's startup; nothing Homebrew is doing appears to (directly) triggering it.

**Comment by otaran** [comment]
@apjanke 
```shell
Last login: Tue Nov 10 10:57:47 on console
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/7n/bklr490s6zv3z__hh5mh15zh0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.ZiDLMtCAqJ/Render
TERM_PROGRAM_VERSION=361
TERM_SESSION_ID=xxx
USER=oleksii
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.p6PjSnNvGK/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
PWD=/Users/oleksii
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/oleksii
LOGNAME=oleksii
DISPLAY=/private/tmp/com.apple.launchd.MPezNn9DVj/org.macosforge.xquartz:0
SECURITYSESSIONID=xxx
_=/usr/bin/env
$ cat ~/.bashrc
cat: /Users/oleksii/.bashrc: No such file or directory
$ cat ~/.bash_profile 
env
```

**Comment by otaran** [comment]
@mistydemeo you are right, running simple `gem --version` from command line (not even in `.bash_profile`) shows the same behavior (keeps spawning `xcodebuild` processes). I will try to debug my Rubygems setup, is is clearly not Homebrew issue, thanks all for your help!

**Comment by mistydemeo** [comment]
I don't think it's directly Rubygems's fault; rather, an Apple patch to the builtin `RbConfig` module causes it to run `xcode-select` and `xcrun` to get the SDK path. It looks like something is causing one of those two commands to take a long time.

You could probably verify this by putting this as the only line in your `.bash_profile` and see if that's as slow:

```
xcode-select --print-path >/dev/null 2>&1 && xcrun --sdk macosx --show-sdk-path 2>/dev/null
```

**Comment by otaran** [comment]
You are right, there seems to be an infinite recursion in `xcrun`: first invocation of `xcrun` takes extended period of time to complete, while subsequent invocations run flawlessly. I have noticed that the order of execution that causes recursion is `xcrun -> xcodebuild -> bash -> ruby -> sh -> xcrun` (with empty `.bash_profile`).

**Comment by otaran** [comment]
Apparently problem was in one of Xcode plugins - after I have removed all plugins everything started to work ok.
