### ISSUE TITLE
Upgrading dnscrypt should not overwrite dnscrypt-resolvers.csv with outdated version

### ISSUE THREAD

**Issue by notDavid** [Homebrew/homebrew#45859]
After running `brew upgrade` i [noticed](https://github.com/Homebrew/homebrew/commit/7ab2b46b15e50ab1eedb5152c7432417eb5b9013#commitcomment-14288704) all of my configured DNS servers stopped working. I suspect what caused this is the 'brew upgrade` overwriting the up-to-date dnscrypt-resolvers.csv on my system with an old outdated version in [dnscrypt-proxy-1.6.0.tar.bz2](https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-proxy-1.6.0.tar.bz2).

I think what we would want to happen instead is:
- Don't overwrite dnscrypt-resolvers.csv when upgrading, if it is already present,
or even better:
- Fetch the latest up-to-date version from https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? It should probably be using `etc.install` to stop configuration getting replaced. This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by notDavid** [comment]
@mikemcquaid sure, however i'm not sure how, some observations;

i just tried manually compiling/installing dnscrypt-proxy via the [standard procedure](https://github.com/jedisct1/dnscrypt-proxy/#installation) , so without Homebrew, and dnscrypt-resolvers.csv also gets overwritten when running `make install`. The last line of the 'make install' output is: `/usr/bin/install -c -m 644 dnscrypt-resolvers.csv minisign.pub '/usr/local/share/dnscrypt-proxy'`

If i see correct `etc.install` would install the config file in `/usr/local/etc/` while Homebrew currently installs the file in `/usr/local/share/dnscrypt-proxy/`.

I have seen [pkgshare.install](http://www.rubydoc.info/github/Homebrew/homebrew/master/Formula%3Apkgshare) , should i be using that? If i understand correct, it will then overwrite the config file (which was already overwritten by 'make install' with an outdated version anyway), but at least now it will be a working/fresh one...?

**Comment by notDavid** [comment]
Hmmz okay so this mostly works, except for line 30 where it downloads the .csv which then contains all the html crap instead of the raw file...: [d499eff](https://github.com/notDavid/homebrew/commit/d499eff9fc287da1baa06675159df5e792b3ac66#diff-9eb29b1e80abd786c42aba45f0fcfb26R30)

The url is correct, so no idea why it does that/how to fix.

**Comment by notDavid** [comment]
Ah, clearing homebrew cache solved it..

**Comment by DomT4** [comment]
I don't really want to add a completely unversioned download in there :cry:. We can't checksum that, and theoretically it could change between Dave installing it at 09:00 and Lauren installing it at 09:10 and both report errors with the resolvers and we have to go a-hunting for the specific break point.

It also won't work for bottles - The bottle will contain the CSV at the moment it was bottled, not a newer one.

**Comment by notDavid** [comment]
I understand your point, however because the resolver list changes frequently, "Dave and Lauren" have a different resolver file anyway - even without this commit.

Currently, when installing dnscrypt-proxy, you end up with a not working installation, which is very frustrating especially for first time users, because it takes ages to figure out where the problem is.

And of course when updating, if anything changes in the formula, you end up with a non working installation again.

**Comment by DomT4** [comment]
Closing in favour of the PR you filed, Thanks!
