### ISSUE TITLE
Do you recommend taking ownership of /usr/local before installing Homebrew?

### ISSUE THREAD

**Issue by callumlocke** [Homebrew/homebrew#45857]
I've been helping several new coworkers to get their new developer laptops up and running in the last week, and installing Homebrew has been a big source of confusion. There's always a lot of errors and warnings about Homebrew not having permission to write to a given directory (despite it asking for a password at the beginning of the process).

A lot of people online recommend doing `sudo chown -R $(whoami) /usr/local` before installing or uninstalling Homebrew. Then there's usually comments from other people saying "that's a bad idea".

Is this a good idea? What's Homebrew's official policy on this?

**Comment by mikemcquaid** [comment]
> A lot of people online recommend doing sudo chown -R $(whoami) /usr/local before installing or uninstalling Homebrew. Then there's usually comments from other people saying "that's a bad idea".

Currently that's recommended by Homebrew, yep.

The Homebrew official installer should fix permissions for you: https://github.com/Homebrew/install

Additionally, as a personal plug, you may be interested in https://github.com/mikemcquaid/strap

**Comment by callumlocke** [comment]
Thanks for confirmation.

Strap looks useful, will give it a try

**Comment by callumlocke** [comment]
> The Homebrew official installer should fix permissions for you: https://github.com/Homebrew/install

All I've done (on various new Macs with a fresh install of Yosemite) is copy-paste the install command from the brew.sh homepage, which I presume is the 'official' install script, and I still get tons of permission denied issues.

Reopening in case this is a bug?

**Comment by mikemcquaid** [comment]
> All I've done (on various new Macs with a fresh install of Yosemite) is copy-paste the install command from the brew.sh homepage, which I presume is the 'official' install script, and I still get tons of permission denied issues.

It'd be good if you could send us a log of that!

**Comment by DomT4** [comment]
Note: I believe Sophos Anti-Virus is still silently sudo chowning `/usr/local` to root persistently, if you have that installed on the laptops.

**Comment by callumlocke** [comment]
We don't have that but we might have something similar, it's a corporate build of Yosemite I think.

Can't homebrew just chown it back to `$(whoami)` at the start of the install/uninstall script?

**Comment by roele** [comment]
There is a discussion about this at the [Sophos Community](https://community.sophos.com/products/free-antivirus-tools-for-desktops/f/17/p/10029/285302#285302)

**Comment by kenkendk** [comment]
Has there been considerations for not requiring this permission fix by Homebrew?

The reason for protecting `/usr/local` is that it precedes `/bin` (and `/lib`) when loading files. This is why it works great for Homebrew. But a nasty program could install `/usr/local/ls`, `/usr/lib/libc.so`, `/usr/local/sudo` and it will override the system-provided files.

IMO, such powers should require admin permission, and not be allowed by all applications.

If Homebrew kept the permissions intact, it would then only need to request a password when injecting the symlinks in `/usr/local`. A small price to pay for a more secure (and SIP compliant) system.

**Comment by mikemcquaid** [comment]
@kenkendk Homebrew is already SIP compliant as-is. We're not going to start elevating privileges to write symlinks, sorry.

Closing this issue out as this is handled by our installer.

**Comment by kenkendk** [comment]
@mikemcquaid Thanks for the answer.

It is not that you need to elevate privileges to write symlinks; it is requiring elevated privileges to install libraries and executables that override others (which is done through symlinks).

Has there been other discussions of this?

Good to know that it is SIP compliant. I noticed that El Capitan switched my permissions on `/usr/local` back after updating, so it is at least "not as secure as Apple would like it".

**Comment by mikemcquaid** [comment]
@kenkendk We're going to release a tool at some point that'll be more specific with the permissions it handles.
