### ISSUE TITLE
luajit: links missing for libluajit.a, libluajit.dylib

### ISSUE THREAD

**Issue by garthk** [Homebrew/homebrew#45854]
I can't compile with `-l luajit` because there's no link from `/usr/local/lib/libluajit.a` to `/usr/local/Cellar/luajit/2.0.4/lib/libluajit-5.1.a`, nor `/usr/local/lib/libluajit.dylib` to `/usr/local/Cellar/luajit/2.0.4/lib/libluajit-5.1.2.0.4.dylib`.

Workaround:

```
cd /usr/local/lib
ln -s ../Cellar/luajit/2.0.4/lib/libluajit-5.1.a ./libluajit.a
ln -s ../Cellar/luajit/2.0.4/lib/libluajit-5.1.2.0.4.dylib ./libluajit.dylib
```

**Comment by DomT4** [comment]
Huh. Indeed that's the case. Quite unusual, most upstreams add code to do this sort of thing automatically. We'll have to create the symlinks; will fix this problem this afternoon unless you'd like to submit a PR. The logic would more or less be:

```ruby
lib.install_symlink lib/"liblibluajit.5.1.2.0.4.dylib" => "liblibluajit.dylib"
lib.install_symlink lib/"libluajit-5.1.a" => "libluajit.a"
```
