### ISSUE TITLE
cloc now on github

### ISSUE THREAD

**Issue by AlDanial** [Homebrew/homebrew#45877]
Hello, just wanted to point out that I've moved cloc off SourceForge and onto Github.  While version 1.64 is still the latest release, it can now be found at https://github.com/AlDanial/cloc/releases.  Would be cool if you updated the homebrew config for cloc to pull from Github instead of SF.

**Comment by ruurd** [comment]
I'll pick up this one

**Comment by ruurd** [comment]
https://github.com/Homebrew/homebrew/pull/45882

**Comment by mikemcquaid** [comment]
Merged in https://github.com/Homebrew/homebrew/pull/45882.
