### ISSUE TITLE
Unable to install Homebrew El Capitain

### ISSUE THREAD

**Issue by AminMe** [Homebrew/homebrew#45870]
Hello everyone since Yosemite I am trying to install homrebrew but it did not work

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/man/man1/brew.1

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
fatal: unable to access 'https://github.com/Homebrew/homebrew/': Failed to connect to 172.17.31.1 port 8080: Operation timed out
Failed during: git fetch origin master:refs/remotes/origin/master -n --depth=1

I don't have any proxy.
Thanks

**Comment by ericvw** [comment]
@AminMe, what is the output of the following:
```shell
env | grep -i proxy
```
?

**Comment by AminMe** [comment]
It gives nothing. Empty answer from the terminal

**Comment by bfontaine** [comment]
Do you have any “`insteadOf`” rules in your `~/.gitconfig`?

**Comment by AminMe** [comment]
cat ~/.gitconfig
[color]
	diff = auto
	status = auto
	branch = auto
	ui = auto
[user]
	name = ***** *****
	email = ****@***.****
[alias]
        co = commit
        ch = checkout
        st = status
        br = branch
[filter "media"]
	clean = git media clean %f
	smudge = git media smudge %f
	required = true
[http]
	proxy = 172.17.31.1:8080
[core]
	autocrlf = input

Ouch I have a git proxy so I need to remove it how ?

**Comment by ericvw** [comment]
You could just remove those two lines if you don't need them or use `git-config`.
