### ISSUE TITLE
iperf: checking whether we are cross compiling... configure: error

### ISSUE THREAD

**Issue by anacrolix** [Homebrew/homebrew#45918]
$ brew install iperf
==> Downloading https://downloads.sourceforge.net/project/iperf/iperf-2.0.5.tar.gz
Already downloaded: /Library/Caches/Homebrew/iperf-2.0.5.tar.gz
==> ./configure --prefix=/usr/local/Cellar/iperf/2.0.5
Last 15 lines from /Users/anacrolix/Library/Logs/Homebrew/iperf/01.configure:
configure: WARNING: unrecognized options: --disable-debug
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/private/tmp/iperf20151112-50315-jw8181/iperf-2.0.5':
configure: error: cannot run C++ compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details.

**Comment by dunn** [comment]
Can you post the full `brew gist-logs iperf`? Thanks!

**Comment by DomT4** [comment]
In all likelihood, either your Xcode/CLT are mismatched or Xcode is outdated.

**Comment by anacrolix** [comment]
https://gist.github.com/anonymous/30ecb0f229ead9f9e98a

**Comment by DomT4** [comment]
```
Warning: Your Xcode (6.1.1) is outdated
Please update to Xcode 7.1.
Xcode can be updated from the App Store.
```
:)

**Comment by DomT4** [comment]
Closing per the above, but give us a shout if you're still having problems afterwards.

**Comment by anacrolix** [comment]
Thanks, I'll test with updated XCode on Tuesday

**Comment by anacrolix** [comment]
Works with updated Xcode. Keep up the good work.

**Comment by DomT4** [comment]
Thanks for letting us know! :smiley:
