### ISSUE TITLE
Problem installing Bowtie2

### ISSUE THREAD

**Issue by pig-raffles** [Homebrew/homebrew#45928]
Hi,

I have a problem installing bowtie2 (or TopHat, of which bowtie2 is a dependency) on a Mac running el Capitan.

I have tried brew update and brew doctor, but it gives me no clear indication of whats wrong.

The program is part of homebrew/science

So when I brew install bowtie2 I get the following warning:

==> Installing bowtie2 from homebrew/homebrew-science
==> Downloading https://github.com/BenLangmead/bowtie2/archive/v2.2.6.tar.gz
Already downloaded: /Library/Caches/Homebrew/bowtie2-2.2.6.tar.gz
Error: SHA256 mismatch
Expected: fb4d09a96700cc929e8191659ee8509bb2f19816235322d1f012338d4a177358
Actual: 06d584040d9ce457873c59e4a5889aafe1a5f74ada207793335765d7abdf4eeb
Archive: /Library/Caches/Homebrew/bowtie2-2.2.6.tar.gz
To retry an incomplete download, remove the file above.

Any idea what the problem could be?

Many thanks

Alan

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-science#3006

**Comment by DomT4** [comment]
Moved to Science as it's their formula. You should be CC'd into the new thread automatically. Think it's just a basic upstream retagging, but someone will want to check.
