### ISSUE TITLE
OSX 10.7 Can't upgrade python3 to 3.5

### ISSUE THREAD

**Issue by uliano** [Homebrew/homebrew#45923]
```
bash-3.2$ brew upgrade python3
==> Upgrading 1 outdated package, with result:
python3 3.5.0
==> Upgrading python3
==> Downloading https://www.python.org/ftp/python/3.5.0/Python-3.5.0.tar.xz
Already downloaded: /Library/Caches/Homebrew/python3-3.5.0.tar.xz
==> Downloading https://bugs.python.org/file40478/xcode-stubs.diff
Already downloaded: /Library/Caches/Homebrew/python3--patch-029cc0dc72b1bcf4ddc5f913cc4a3fd970378073c6355921891f041aca2f8b12.diff
==> Patching
patching file Lib/distutils/ccompiler.py
patching file Lib/distutils/unixccompiler.py
==> ./configure --prefix=/usr/local/Cellar/python3/3.5.0 --enable-ipv6 --dataroo
==> make
Last 15 lines from /Users/amm/Library/Logs/Homebrew/python3/02.make:
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -Werror=declaration-after-statement   -I. -IInclude -I./Include    -DPy_BUILD_CORE -o Python/ceval.o Python/ceval.c
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -Werror=declaration-after-statement   -I. -IInclude -I./Include    -DPy_BUILD_CORE -o Python/codecs.o Python/codecs.c
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -Werror=declaration-after-statement   -I. -IInclude -I./Include    -DPy_BUILD_CORE -o Python/errors.o Python/errors.c
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -Werror=declaration-after-statement   -I. -IInclude -I./Include    -DPy_BUILD_CORE -o Python/frozenmain.o Python/frozenmain.c
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -Werror=declaration-after-statement   -I. -IInclude -I./Include    -DPy_BUILD_CORE -o Python/future.o Python/future.c
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -Werror=declaration-after-statement   -I. -IInclude -I./Include    -DPy_BUILD_CORE -o Python/getargs.o Python/getargs.c
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -Werror=declaration-after-statement   -I. -IInclude -I./Include    -DPy_BUILD_CORE -o Python/getcompiler.o Python/getcompiler.c
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -Werror=declaration-after-statement   -I. -IInclude -I./Include    -DPy_BUILD_CORE -o Python/getcopyright.o Python/getcopyright.c
fatal error: error in backend: Cannot select: 0x102672710: i8,ch = AtomicSwap 0x1029a7480, 0x102672010, 0x102672510<Volatile ST1[@gil_drop_request.0.b]> [ID=7]
  0x102672010: i64 = X86ISD::WrapperRIP 0x102670710 [ID=6]
    0x102670710: i64 = TargetGlobalAddress<i1* @gil_drop_request.0.b> 0 [ID=4]
  0x102672510: i8 = Constant<1> [ID=2]
In function: take_gil
make: *** [Python/ceval.o] Error 1
make: *** Waiting for unfinished jobs....

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
gobject-introspection: add head, add python3 which requires head  https://github.com/Homebrew/homebrew/pull/45442
Python/Python3: Fix RuntimeError: tk.h version (8.6) doesn't match libtk.a version (8.5) https://github.com/Homebrew/homebrew/pull/41728

bash-3.2$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    python3

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:

    brew install gstreamer

Run `brew missing` for more details.
```

**Comment by mikemcquaid** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please do.

**Comment by uliano** [comment]
```
bash-3.2$ brew gist-logs python3
https://gist.github.com/e4fa5461222de6085c3a
```

**Comment by dunn** [comment]
https://gist.github.com/anonymous/e4fa5461222de6085c3a#file-02-make-L78-L82:
```
  0x102672010: i64 = X86ISD::WrapperRIP 0x102670710 [ID=6]
    0x102670710: i64 = TargetGlobalAddress<i1* @gil_drop_request.0.b> 0 [ID=4]
  0x102672510: i8 = Constant<1> [ID=2]
In function: take_gil
make: *** [Python/ceval.o] Error 1

**Comment by mrkapqa** [comment]
anyone have a solution on how to upgrade pyhton to 3.5 on lion?



jussis-mac-mini:~ jussiissa42$ brew install python3
==> Downloading https://www.python.org/ftp/python/3.5.0/Python-3.5.0.tar.xz
Already downloaded: /Library/Caches/Homebrew/python3-3.5.0.tar.xz
==> Downloading https://bugs.python.org/file40478/xcode-stubs.diff
Already downloaded: /Library/Caches/Homebrew/python3--patch-029cc0dc72b1bcf4ddc5f913cc4a3fd970378073c6355921891f041aca2f8b12.diff
==> Patching
patching file Lib/distutils/ccompiler.py
patching file Lib/distutils/unixccompiler.py
==> ./configure --prefix=/usr/local/Cellar/python3/3.5.0 --enable-ipv6 --dataroo
==> make
Last 15 lines from /Users/jussiissa42/Library/Logs/Homebrew/python3/02.make:
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -Werror=declaration-after-statement   -I. -IInclude -I./Include    -DPy_BUILD_CORE -o Parser/printgrammar.o Parser/printgrammar.c
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -Werror=declaration-after-statement   -I. -IInclude -I./Include    -DPy_BUILD_CORE -o Parser/parsetok_pgen.o Parser/parsetok_pgen.c
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -Werror=declaration-after-statement   -I. -IInclude -I./Include    -DPy_BUILD_CORE -o Parser/pgenmain.o Parser/pgenmain.c
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -Werror=declaration-after-statement   -I. -IInclude -I./Include    -DPy_BUILD_CORE -o Python/bltinmodule.o Python/bltinmodule.c
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -Werror=declaration-after-statement   -I. -IInclude -I./Include    -DPy_BUILD_CORE -o Python/ceval.o Python/ceval.c
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -Werror=declaration-after-statement   -I. -IInclude -I./Include    -DPy_BUILD_CORE -o Python/codecs.o Python/codecs.c
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -Werror=declaration-after-statement   -I. -IInclude -I./Include    -DPy_BUILD_CORE -o Python/errors.o Python/errors.c
clang -c -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -Werror=declaration-after-statement   -I. -IInclude -I./Include    -DPy_BUILD_CORE -o Python/frozenmain.o Python/frozenmain.c
fatal error: error in backend: Cannot select: 0x10276d510: i8,ch = AtomicSwap 0x1029a7600, 0x10276ce10, 0x10276d310<Volatile ST1[@gil_drop_request.0.b]> [ID=7]
  0x10276ce10: i64 = X86ISD::WrapperRIP 0x1026a1d10 [ID=6]
    0x1026a1d10: i64 = TargetGlobalAddress<i1* @gil_drop_request.0.b> 0 [ID=4]
  0x10276d310: i8 = Constant<1> [ID=2]
In function: take_gil
make: *** [Python/ceval.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by tdsmith** [comment]
Discussion at https://bugs.python.org/issue24844.

I think that installing Homebrew's gcc and passing `--cc=gcc-5` to `brew install` should help.
