### ISSUE TITLE
Define proper CA file path for weechat

### ISSUE THREAD

**Issue by maletor** [Homebrew/homebrew#45947]
weechat [now supports](https://savannah.nongnu.org/task/?12725) defining [a custom SSL certificate path during configuration](https://github.com/weechat/weechat/blob/2641b6e778b13022612be21c7870eaf44b4a0929/configure.ac#L164) of the binary.

We should configure the binary with `/usr/local/etc/openssl/cert.pem`.

**Comment by dunn** [comment]
Feel like opening a PR? Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions!

**Comment by maletor** [comment]
Sure!

**Comment by DomT4** [comment]
Will review a PR.
