### ISSUE TITLE
Install error on El Capitan - Invalid multibyte & char

### ISSUE THREAD

**Issue by v1m** [Homebrew/homebrew#45948]
On one of my machines immediately after upgrading to El Capitan 10.11.1, I tried installing Homebrew. 

Xcode was already installed and was at ver 7.1.1.
I also installed command Line Tools for Xcode via "xcode-select --install"

But executing the basic one-line Ruby installer gives me the following error:
```
$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
-e:1: Invalid char `\x1F' in expression
-e:1: invalid multibyte char (UTF-8)
```

other possibly useful info:
```
$ ruby --version
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]

$ which ruby
/usr/bin/ruby


$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

**Comment by apjanke** [comment]
That's odd. As far as I can tell, neither the byte `1F` nor the string `"1F"` appear in the install file. And it's working for me. Possible download error? Is it still giving you the same error? If so, could you do just `curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install > install.out; shasum install.out` and post the result?

Should get the same value as this.
```
$ shasum install
b606f615073a83ef1d0c42bf5061e4fa6275cf54  install
```

**Comment by v1m** [comment]
interesting....

```
$ curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install > install.out
$ shasum install.out 
3d8b520f6b77a95c7826d1895bd7372e0045916a  install.out
```

Since I wasn't sure what the Curl options were doing, I tried this:

```
$ curl https://raw.githubusercontent.com/Homebrew/install/master/install > delete.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3550  100  3550    0     0   5395      0 --:--:-- --:--:-- --:--:--  5395

$ file delete.txt 
delete.txt: gzip compressed data, from Unix

$ shasum delete.txt 
3d8b520f6b77a95c7826d1895bd7372e0045916a  delete.txt
```

I guess it does point to the fact that there is a download issue going on here. Curl is not downloading it properly.

PS: found this *very interesting* web service: 
http://explainshell.com/explain?cmd=curl+-fsSL+example.org

**Comment by v1m** [comment]
thanks for the help.

I was able to figure out that a bad .curlrc script on my machine was interfering and causing the download issue !
