### ISSUE TITLE
`libagg` site no longer available, preventing install of `libagg` formula.

### ISSUE THREAD

**Issue by MrJoy** [Homebrew/homebrew#45950]
See the [wikipedia page](https://en.wikipedia.org/wiki/Anti-Grain_Geometry).

Maintainer passed away, the site has since become [unavailable](http://www.antigrain.com).

There's a [mirror of the original site](http://agg.sourceforge.net/antigrain.com/download/index.html), and a [fork of the nearly-identical-BSD-licensed v2.4](http://sourceforge.net/projects/agg/).

**Comment by apjanke** [comment]
The mirrored site and the "fork" both go to the same project on SourceForge, and despite the note on the Wikipedia, it's not clear to me what's going on there in terms of ownership or development activity.

The download links on the archived site just point back to the original antigrain.com, which is 404, so we can't use those. There are no distribution files hosted on sourceforge aside from an "msys-sdk" file from 2001, which appears to be just a copy of part of MSYS, not AGG, and is corrupt at the `tar` archive level.

This project isn't in a usable state. If you'd like to continue using it, maybe you could contact the current maintainers at Sourceforge and see if they want to post downloadable distribution files and some documentation about the current state of the project? As is, this looks like a candidate for the boneyard.

Archive.org has an [archived copy of the original site](https://web.archive.org/web/20150811231742/http://antigrain.com/download/index.html) which includes the download file. We could probably just repoint the formula there to keep it running. More experienced Homebrew folks, what's our policy on pointing at `archive.org` for downloads? I see some of the other formulae already do so.

**Comment by apjanke** [comment]
All right, other maintainers say archive.org is okay. Switching it over. #45973
