### ISSUE TITLE
boost.log can build with gcc installed by homebrew

### ISSUE THREAD

**Issue by ahundt** [Homebrew/homebrew#45954]
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boost.rb#L103 should check if it is the version is the OS X provided gcc 4.2, otherwise Boost.Log should not be disabled for gcc.

**Comment by ahundt** [comment]
Based on the [installation notes for boost.log](http://www.boost.org/doc/libs/1_59_0/libs/log/doc/html/log/installation.html) it should be enabled for every gcc version >= 4.5.

**Comment by DomT4** [comment]
As far as I'm aware, even in this context, `:gcc` *only* applies to the old Apple GCC rather than any newer GNU `gcc`s. Perhaps the `ENV.compiler` returns a simpler output though. CC @mistydemeo

**Comment by dtrebbien** [comment]
Just yesterday I built Boost using Homebrew GCC (see #46046).  Boost.Log was built.

**Comment by ahundt** [comment]
ah, well I guess it is a linuxbrew only issue then. Before you close it, any possible hints on how to properly deal with the issue in a way that won't make merging homebrew to linuxbrew difficult in the future?

It seems linuxbrew sees :gcc as the system gcc, which on non apple platforms can compile boost.log OK.

**Comment by mikemcquaid** [comment]
Please don't file Linuxbrew issues here in future. I'm not sure the best way to fix it on Linuxbrew, I'm afraid.

**Comment by ahundt** [comment]
@mikemcquaid if the `:gcc` flag behaved as I expected (identifying gcc compiler being used, rather than OS X only gcc 4.2), the issue would have been present in OS X. Nonetheless, sorry for the spurious issue.

**Comment by DomT4** [comment]
> It seems linuxbrew sees :gcc as the system gcc, which on non apple platforms can compile boost.log OK.

Since Linuxbrew doesn't have to worry about backwards compatibility with older OS X compilers, they may be more or less free to hack up the logic to suit their use case. Just needs someone to look into it and do the necessary work, I suspect.
