### ISSUE TITLE
Add freegeoip

### ISSUE THREAD

**Issue by zedtux** [Homebrew/homebrew#45957]
Freegoip website: https://freegeoip.net/
Freegoip server sources: https://github.com/fiorix/freegeoip
Freegoip server binaires: https://github.com/fiorix/freegeoip/releases

**Comment by mikemcquaid** [comment]
We don't really do formula requests. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
