### ISSUE TITLE
cmake builds fail on Mac OS X 10.7.5 for cmake and curl

### ISSUE THREAD

**Issue by naics** [Homebrew/homebrew#45989]
Last 15 lines from /Users/andrea/Library/Logs/Homebrew/cmake/13.make:
[ 55%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmCPackPropertiesGenerator.cxx.o
[ 55%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmCryptoHash.cxx.o
[ 56%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmCurl.cxx.o
[ 56%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmCustomCommand.cxx.o
/tmp/cmake20151114-19902-13b0s49/cmake-3.4.0/Source/cmCurl.cxx:30:5: error: use of undeclared identifier 'CURLE_NOT_BUILT_IN'
    check_curl_result(res, "Unable to set TLS/SSL Verify CAINFO: ");
    ^
/tmp/cmake20151114-19902-13b0s49/cmake-3.4.0/Source/cmCurl.cxx:16:39: note: expanded from macro 'check_curl_result'
  if (result != CURLE_OK && result != CURLE_NOT_BUILT_IN)               \
                                      ^
1 error generated.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmCurl.cxx.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Source/CMakeFiles/CMakeLib.dir/all] Error 2
make: *** [all] Error 2

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by naics** [comment]
Here is the gist log:
https://gist.github.com/718ef39f5f76bbb2d714
Here the brew config:
macpro:~ andrea$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: f273fe6d032f87de773b5388907b91e91a211206
Last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit core2
OS X: 10.7.5-i386
Xcode: 4.6.3
CLT: 4.6.0.0.1.1365549073
LLVM-GCC: build 2336
Clang: 4.2 build 425
X11: 2.7.8 => /opt/X11
System Ruby: 1.8.7-p358
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/andrea/.rvm/rubies/ruby-2.2.1/bin/ruby
Java: 1.6.0_65-b14-462
These are the important lines from the building process
Scanning dependencies of target CMakeLib
[ 51%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmArchiveWrite.cxx.o
[ 51%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmBootstrapCommands1.cxx.o
[ 51%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmBootstrapCommands2.cxx.o
[ 51%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmCacheManager.cxx.o
[ 51%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmCommands.cxx.o
[ 52%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmCLocaleEnvironmentScope.cxx.o
[ 52%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmCommandArgumentLexer.cxx.o
[ 52%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmCommandArgumentParser.cxx.o
[ 52%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmCommandArgumentParserHelper.cxx.o
[ 52%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmCommonTargetGenerator.cxx.o
[ 53%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmComputeComponentGraph.cxx.o
[ 53%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmComputeLinkDepends.cxx.o
[ 53%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmComputeLinkInformation.cxx.o
[ 53%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmComputeTargetDepends.cxx.o
[ 53%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmCPackPropertiesGenerator.cxx.o
[ 53%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmCryptoHash.cxx.o
[ 54%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmCurl.cxx.o
/tmp/cmake20151114-33531-1kg7wme/cmake-3.4.0/Source/cmCurl.cxx:30:5: error: use of undeclared identifier 'CURLE_NOT_BUILT_IN'
    check_curl_result(res, "Unable to set TLS/SSL Verify CAINFO: ");
    ^
/tmp/cmake20151114-33531-1kg7wme/cmake-3.4.0/Source/cmCurl.cxx:16:39: note: expanded from macro 'check_curl_result'
  if (result != CURLE_OK && result != CURLE_NOT_BUILT_IN)               \
                                      ^
1 error generated.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmCurl.cxx.o] Error 1
make[1]: *** [Source/CMakeFiles/CMakeLib.dir/all] Error 2
make: *** [all] Error 2
==> Formula
Path: /usr/local/Library/Formula/cmake.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: f273fe6d032f87de773b5388907b91e91a211206
Last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit core2
OS X: 10.7.5-i386
Xcode: 4.6.3
CLT: 4.6.0.0.1.1365549073
LLVM-GCC: build 2336
Clang: 4.2 build 425
X11: 2.7.8 => /opt/X11
System Ruby: 1.8.7-p358
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/andrea/.rvm/rubies/ruby-2.2.1/bin/ruby
Java: 1.6.0_65-b14-462
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j1
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.7
HOMEBREW_MAKE_JOBS: 1
PATH: /usr/local/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin
In my opinion there are incompatibilities with curl package from OS X 10.7.5.

If you need any other information please ask me.
Many thanks for your help!

**Comment by DomT4** [comment]
The system `curl` from 10.7.5 doesn't [define](https://opensource.apple.com/source/curl/curl-69.1/curl/include/curl/curl.h) `CURLE_NOT_BUILT_IN`, whereas everything from 10.8 [seems to do](https://opensource.apple.com/source/curl/curl-69.2/curl/include/curl/curl.h) so.

Tigerbrew already uses the CMake `curl` library for compile on Leopard and below, so I guess CMake made the new release incompatible with the system `curl` on a couple systems beyond that.

We can either let CMake build its own mini-curl and use that, or make it depend on our `curl` for 10.7 and below.

**Comment by DomT4** [comment]
Went for the former option, as it's what Misty already does in Tigerbrew. Should be fixed after a `brew update`. Thanks for the report!

**Comment by naics** [comment]
Thanks! Now it works perfectly

**Comment by DomT4** [comment]
Thanks for the confirmation!
