### ISSUE TITLE
git-cola --with-docs failed to build on 10.11.1

### ISSUE THREAD

**Issue by koluke** [Homebrew/homebrew#45998]
Running `brew install git-cola` works fine, but running with `--with-docs` option leads to:

```make: Makefile.asciidoc: No such file or directory
make: *** No rule to make target `Makefile.asciidoc'.  Stop.```

Link to gist containing output from `brew gist-logs git-cola --with-docs`: https://gist.github.com/anonymous/a3e85bb75c75cfe40444

**Comment by dunn** [comment]
Should be fixed by 5ca60131b99949f68fc01269aa8abb55496a0e3e, thanks the heads-up!

**Comment by koluke** [comment]
I'm getting a different error now.  `brew gist-logs git-cola --with-docs` output after running `brew update`: https://gist.github.com/4f6519e64121e55a368d

Again seems specific to the `--with-docs` option.

**Comment by dunn** [comment]
Yeah, looks like I missed some Sphinx deps. I wonder why it worked for me and for the CI.

**Comment by dunn** [comment]
OK, hopefully 4559c20f6da73ccdb5514bec933d69edacc7cb9a does the trick.

**Comment by koluke** [comment]
Looks good!  Thanks!
