### ISSUE TITLE
Error installing homebrew/binary/rar

### ISSUE THREAD

**Issue by ViKingIX** [Homebrew/homebrew#45999]
The error message is "wrong number of arguments (0 for 1..3)".

The tips told me to report here.

Thanks

**Comment by mikemcquaid** [comment]
`brew update` and try again? Also, sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by DomT4** [comment]
Please let us know if we can help further here, Thanks!
