### ISSUE TITLE
gnuradio failed to build on 10.11

### ISSUE THREAD

**Issue by girving** [Homebrew/homebrew#46000]
`brew install gnuradio` is failing for me, and I'm not sure if it's a problem with gnuradio itself or cmake or both.  Here's the result of `brew gist-logs gnuradio`: https://gist.github.com/girving/c180157b19c51ca28014

I think the problem is the bunch of errors of form 

    CMake Error at /usr/local/Cellar/cmake/3.4.0/share/cmake/Modules/FindPythonLibs.cmake:181 (get_filename_component):
      get_filename_component called with incorrect number of arguments

I'm not sure of that though; there are a lot of those errors and the build continues past all of them.

**Comment by StefanD986** [comment]
Just to confirm its not only you: Same problem here.
My brew gist logs here: https://gist.github.com/b140d77527b03aaf312e

**Comment by StefanD986** [comment]
Hmm, weird: I tried to find the commit that introduced the error by bisecting. 
I started with 5ca60131b99949f68fc01269aa8abb55496a0e3e being the first known bad and with the "last know good" commit being  4e8756c593604ccea715fb01d375044350713f26.

Then I bisected my way all the way back to 5ca60131b99949f68fc01269aa8abb55496a0e3e (which was bad at the beginning). 
But now it magically works, no build problems anymore o_O

Did I do something wrong? I am not sure whether git bisecting works correctly with brew.
I noticed that brew never downloaded any of the tar.gz ("Already downloaded") during the whole process.  Though I used "brew cleanup" after every bisect step. 
Maybe it just built an older version that worked. But I would expect that then the SHA check would fail which is given in the Formula.

**Comment by Over23** [comment]
Hello this is one of errors

-- Found PythonLibs: -undefined dynamic_lookup (found suitable version "2.7.10", minimum required is "2") 
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE - Success
CMake Error at /usr/local/Cellar/cmake/3.4.0/share/cmake/Modules/FindPythonLibs.cmake:181 (get_filename_component):
  get_filename_component called with incorrect number of arguments
Call Stack (most recent call first):
  cmake/Modules/GrSwig.cmake:149 (find_package)
  gnuradio-runtime/swig/CMakeLists.txt:80 (GR_SWIG_MAKE)

**Comment by Over23** [comment]
Here should be whole Homebrew/gnuradio/05.cmake
https://github.com/Over23/gnuradio_compile_debbug/issues/1

**Comment by Over23** [comment]
I'm too green to give advices, but I have seen that Gnuradio is brewing python as dependency; in't it better than just to create direct dependency to just brewed version?

**Comment by nejohnson2** [comment]
Having the same issue here.  I'm trying to install gnuradio on a fresh install of OSX 10.11 and newest version of Xcode(not an upgraded version).  [Gist is here](https://gist.github.com/anonymous/7ff1af1929bc366aa2c3).

I'm hoping its not related to [this post](http://lists.gnu.org/archive/html/discuss-gnuradio/2015-10/msg00080.html) about Xcode 7.1 not supporting Qt4.  

Has anyone gotten gnuradio to install on 10.11?

**Comment by 1ncorrect** [comment]
Same issue here. The following appears several times in the 05.cmake file.

>CMake Error at /usr/local/Cellar/cmake/3.4.0/share/cmake/Modules/FindPythonLibs.cmake:181 (get_filename_component):
>  get_filename_component called with incorrect number of arguments
>Call Stack (most recent call first):
>  cmake/Modules/GrSwig.cmake:149 (find_package)
>  gnuradio-runtime/swig/CMakeLists.txt:50 (GR_SWIG_MAKE)

OS X 10.11.1, Xcode 7.1.1

**Comment by Flushot** [comment]
I was able to fix this on my OSX 10.11.1 machine.

My gnuradio install failed with the `get_filename_component called with incorrect number of arguments` errors when I had cmake 3.4.0 installed, so I downgraded to cmake 3.3.2 and was able to compile.

It seems the very recent cmake 3.4 release affected that function: https://cmake.org/cmake/help/v3.4/release/3.4.html

**Comment by 1ncorrect** [comment]
I tried installing an older version of cmake using homebrew, but for some reason building gnuradio with homebrew refused to recognise it.

Rather than waste any more time trying to figure out how to roll back a package within homebrew, I'd rather fix gnuradio 3.7.8 to build using cmake 3.4.0 or later, but I have no idea where to begin. Is this a bug in cmake or do we need to add/remove an argument to whatever is calling get_filename_component ?

**Comment by nejohnson2** [comment]
Agreed...and likewise, I have no Idea where to begin.  

I can also say that I did reformat my machine, installed Xcode and cmake 3.1 via homebrew and tried gnuradio via homebrew (while removing the ```cmake => :build``` from the formula) but it failed.  Not sure how to install cmake 3.3 as it's not listed in ```brew search cmake```.  

Regardless, I agree better to fix the cmake bug that to rely on an older version.

**Comment by yakoh** [comment]
Thanks to Flushot's hint, I successfully solved this problem.  Followings are what I did (not sure :-))
0. Install but disable new cmake
`brew install cmake; brew unlink cmake`
1. Install old cmake
`cd /usr/local/Library; git log | less `
// the last commit before cmake 3.4.0 was 0036e3d1....
` checkout -b cmake 0036e3d1....` // back to the past
` brew install cmake; brew switch cmake 3.3.2` // just for sure
2. install new gnuradio
`checkout -b master` // return to the current
`brew install gnuradio`
That's it.  I hope this memo may help someone.

**Comment by 1ncorrect** [comment]
Thanks yakoh, this helped me successfully build gnuradio 3.7.8 and I can confirm it is working in OS X 10.11.1.

Now, is this a bug in cmake 3.4 or do the gnuradio build scripts need to be updated to support it?

**Comment by yakoh** [comment]
Hi, 1ncorrect,

As Flushot pointed out, gnuradio 3.7.8 is incompatible with cmake 3.4. So the formula should specify that cmake version must be lower than 3.4 at this moment. I don't know how to do that.

However, cmake 3.3.2 also has an issue, i.e., it can't find out homebrew python library. So I always have to specify it by hand like below,
`cmake -DPYTHON_LIBRARY=\\
/usr/local/Cellar/python/2.7*/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib ..`
If it can be solved by cmake 3.4, gnuradio should adapt to it.

**Comment by ctrezevant** [comment]
I was also able to successfully build and execute gnuradio 3.7.8 on 10.11.1. Thanks, @yakoh! :smile:

**Comment by JeanRintoul** [comment]
Eventually successfully built gnuradio 3.7.8 on 10.10.5 though had to deep copy(git fetch --depth=1000000) before checking out the old version of cmake.  Thanks @yakoh

**Comment by nejohnson2** [comment]
Likewise, I had to use ```git fetch --depth=1000000``` suggested by @JeanRintoul but I did manage to get gnuradio installed.  Thanks for the help and hopefully someone more savvy than myself can figure out the cmake issue.

**Comment by mikemcquaid** [comment]
@nejohnson2 You can use `git fetch --unshallow` instead of setting a big depth, FYI.

**Comment by johnboiles** [comment]
Thanks @yakoh There were a few typos. Here's what I did
```
brew install cmake; brew unlink cmake
cd /usr/local/Library
git checkout -b cmake 0036e3d1
brew install cmake; brew switch cmake 3.3.2
git checkout master
brew install gnuradio
```

**Comment by coreindustries** [comment]
@johnboiles thanks. With your list I got gnuradio to install correctly on El Capitan

**Comment by awootton** [comment]
I had to try to remove conflicts with macports, and then remove all of macports, and check all my python links and still no joy. I build it on another (port-less) mac in yosemite without problems so I gave up. 
But, that was yesterday. 
Today I realized that if you have already tried the script (6 lines from johnboiles above) previously then you can't do it again without saying 'git checkout cmake' without the -b and the branch id. 
Then it worked. Thanks guys.

**Comment by dpiponi** [comment]
I was trying to understand @awootton 's solution. Typing "git checkout cmake" in /usr/local/Library gives me "error: pathspec 'cmake' did not match any file(s) known to git".

It seems some people have successfully managed to build gnuradio, Did anyone make a complete list of steps they used with a recent version of homebrew?

**Comment by jfreberg** [comment]
@johnboiles when I run your lines:

brew install cmake; brew unlink cmake
cd /usr/local/Library
git checkout -b cmake 0036e3d1
brew install cmake; brew switch cmake 3.3.2
git checkout master
brew install gnuradio

... I get errors  as follows:

Mac-Pro:Library john1$ git checkout -b cmake 0036e3d1
fatal: A branch named 'cmake' already exists

and;

Mac-Pro:Library john1$ brew install cmake; brew switch cmake 3.3.2
Warning: cmake-3.4.1 already installed, it's just not linked
Error: cmake does not have a version "3.3.2" in the Cellar.
Versions available: 3.4.1

I confess I'm lost on how to get around this.  Can you provide any insight?

**Comment by awootton** [comment]
@johnboiles 
you are getting the "cmake already exists" because you already went through the steps once before. This happened to me because it took weeks to get gnuradio working (and it's still broken another way) on my El Cap machine.
The workaround is to just do 'git checkout cmake' and then continue with the steps above.

**Comment by DomT4** [comment]
This should be resolved now. Please `brew update` and let us know if you run into any issues, Thanks!
