### ISSUE TITLE
HomeBrew failed to install global

### ISSUE THREAD

**Issue by zeka0** [Homebrew/homebrew#46001]
I tried to use home-brew to install global in order to use g-tags, but it seems brew tries to install it in /usr/local/etc so the permission is denied. Then I tried to use 'sudo' to activate brew's permission then it reported that brew-executable is not owned by the root, and then I got stuck here...Is there any way out?

**Comment by bfontaine** [comment]
Please run `sudo chown -R $(whoami):admin /usr/local` and try again.

**Comment by zeka0** [comment]
Oh god I found it out...It's because I haven't created directory '/usr/local/etc'...

**Comment by bfontaine** [comment]
Why did you reopen the issue?
