### ISSUE TITLE
gnuradio fails to build on 10.11.1

### ISSUE THREAD

**Issue by nevd** [Homebrew/homebrew#46016]
https://gist.github.com/60fbb4e905ec116dff73

gnuradio fails to build with the following error

==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/gnuradio/3.7.8/libexec/vendor --single-version-externally-managed --record=installed.txt
Error: gnuradio does not define resource ["sphinx", "sphinx_rtd_theme", "alabaster", "babel", "docutils", "pygments", "jinja2", "markupsafe", "snowballstemmer", "six", "pytz"]
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/software_spec.rb:106:in `block in resource'
/usr/local/Library/Homebrew/software_spec.rb:106:in `fetch'
/usr/local/Library/Homebrew/software_spec.rb:106:in `resource'
/usr/local/Library/Homebrew/formula.rb:287:in `resource'
/usr/local/Library/Formula/gnuradio.rb:144:in `block in install'
/usr/local/Library/Formula/gnuradio.rb:143:in `each'
/usr/local/Library/Formula/gnuradio.rb:143:in `install'
/usr/local/Library/Homebrew/build.rb:129:in `block in install'
/usr/local/Library/Homebrew/formula.rb:906:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:1476:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:91:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:1467:in `stage'
/usr/local/Library/Homebrew/formula.rb:902:in `brew'
/usr/local/Library/Homebrew/build.rb:107:in `install'
/usr/local/Library/Homebrew/build.rb:176:in `<main>'

**Comment by dunn** [comment]
That's because of an error in the formula.  You can fix it by making the following change:
```diff
diff --git a/Library/Formula/gnuradio.rb b/Library/Formula/gnuradio.rb
index 55ab848..7bc1484 100644
--- a/Library/Formula/gnuradio.rb
+++ b/Library/Formula/gnuradio.rb
@@ -138,7 +138,7 @@ class Gnuradio < Formula
     ENV.prepend_create_path "PYTHONPATH", libexec/"vendor/lib/python2.7/site-packages"

     res = %w[Markdown Cheetah lxml numpy]
-    res << %w[sphinx sphinx_rtd_theme alabaster babel docutils pygments
+    res += %w[sphinx sphinx_rtd_theme alabaster babel docutils pygments
               jinja2 markupsafe snowballstemmer six pytz] if build.with? "documentation"
     res.each do |r|
       resource(r).stage do
```
But gnuradio will still fail later on with the error in #46000.

If you can figure out how to fix that, we'd love a PR!

**Comment by nevd** [comment]
Thanks, I patched the runbook and got to the next error! Will track the other issue.
