### ISSUE TITLE
homebrew/science/Bowtie2 failed to build on 10.11.1

### ISSUE THREAD

**Issue by smaekawa1** [Homebrew/homebrew#46025]
I'm getting SHA256 mismatch and when I use my OS X 10.10 (Yosemite) instead of 10.11 (El Captain), I am able to install Bowtie2

Error: SHA256 mismatch
Expected: fb4d09a96700cc929e8191659ee8509bb2f19816235322d1f012338d4a177358
Actual: 06d584040d9ce457873c59e4a5889aafe1a5f74ada207793335765d7abdf4eeb
Archive: /Library/Caches/Homebrew/bowtie2-2.2.6.tar.gz

**Comment by DomT4** [comment]
Please track https://github.com/Homebrew/homebrew-science/issues/3006. Since the SHA change has been confirmed as legitimate, you could also submit a PR to Homebrew/science to get that fixed a little quicker, if you wanted to.

**Comment by smaekawa1** [comment]
Thanks!
--
Sho Maekawa (Mr)
PhD Student, 
Suzuki Laboratory, 
Department of Computational Biology and Medical Sciences, 
Graduate School of Frontier Sciences, 
The University of Tokyo (UTokyo)
Room 301, GSFS Bioscience Building, 5-1-5 Kashiwanoha, Kashiwa, Chiba, 277-8562, Japan
+81-(0)4-7136-3607 (Office)
+81-(0)80-3258-1210 (Mobile)
smaekawa@hgc.jp
--
前川　翔
東京大学大学院新領域創成科学研究科　
メディカル情報生命専攻　
鈴木研究室　博士課程
〒277-8562　千葉県柏市柏の葉5-1-5　生命棟301
04-7136-3607 (研究室)
080-3258-1210 (携帯)
smaekawa@hgc.jp
