### ISSUE TITLE
mysql 5.7.9 on Mac OS X 10.11.1

### ISSUE THREAD

**Issue by m99coder** [Homebrew/homebrew#46035]
Hi guys,

I can’t get mysql 5.7.9 compiled with Homebrew #8cf112a0. I’m getting the following error:

```
Updated Homebrew from 4559c20f to 8cf112a0.
No changes to formulae.
==> Upgrading 2 outdated packages, with result:
mysql 5.7.9, mysql-connector-c++ 1.1.6_1
==> Upgrading mysql
==> Downloading https://cdn.mysql.com/Downloads/MySQL-5.7/mysql-5.7.9.tar.gz
Already downloaded: /Library/Caches/Homebrew/mysql-5.7.9.tar.gz
==> cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/mysql/5.7.9 -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VE
==> make
Last 15 lines from /Users/marco/Library/Logs/Homebrew/mysql/02.make:
cd /tmp/mysql20151116-50843-1r1qk4k/mysql-5.7.9 && /usr/local/Cellar/cmake/3.4.0/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/mysql20151116-50843-1r1qk4k/mysql-5.7.9 /tmp/mysql20151116-50843-1r1qk4k/mysql-5.7.9/sql /tmp/mysql20151116-50843-1r1qk4k/mysql-5.7.9 /tmp/mysql20151116-50843-1r1qk4k/mysql-5.7.9/sql /tmp/mysql20151116-50843-1r1qk4k/mysql-5.7.9/sql/CMakeFiles/GenDigestServerSource.dir/DependInfo.cmake --color=
Scanning dependencies of target GenDigestServerSource
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f sql/CMakeFiles/GenDigestServerSource.dir/build.make sql/CMakeFiles/GenDigestServerSource.dir/build
[  7%] Generating lex_token.h
cd /tmp/mysql20151116-50843-1r1qk4k/mysql-5.7.9/sql && ./gen_lex_token > lex_token.h
[  7%] Built target GenDigestServerSource
make[1]: *** [strings/CMakeFiles/strings.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  7%] Linking CXX static library libboost_lib.a
cd /tmp/mysql20151116-50843-1r1qk4k/mysql-5.7.9/client && /usr/local/Cellar/cmake/3.4.0/bin/cmake -P CMakeFiles/boost_lib.dir/cmake_clean_target.cmake
cd /tmp/mysql20151116-50843-1r1qk4k/mysql-5.7.9/client && /usr/local/Cellar/cmake/3.4.0/bin/cmake -E cmake_link_script CMakeFiles/boost_lib.dir/link.txt --verbose=1
/usr/bin/ar qc libboost_lib.a  CMakeFiles/boost_lib.dir/__/include/boost_1_59_0/libs/atomic/src/lockpool.cpp.o CMakeFiles/boost_lib.dir/__/include/boost_1_59_0/libs/chrono/src/chrono.cpp.o CMakeFiles/boost_lib.dir/__/include/boost_1_59_0/libs/chrono/src/process_cpu_clocks.cpp.o CMakeFiles/boost_lib.dir/__/include/boost_1_59_0/libs/chrono/src/thread_clock.cpp.o CMakeFiles/boost_lib.dir/__/include/boost_1_59_0/libs/system/src/error_code.cpp.o CMakeFiles/boost_lib.dir/__/include/boost_1_59_0/libs/thread/src/future.cpp.o CMakeFiles/boost_lib.dir/__/include/boost_1_59_0/libs/thread/src/pthread/once.cpp.o CMakeFiles/boost_lib.dir/__/include/boost_1_59_0/libs/thread/src/pthread/thread.cpp.o
/usr/bin/ranlib libboost_lib.a
[  7%] Built target boost_lib
make: *** [all] Error 2
```

**Comment by DomT4** [comment]
Gonna need a full `brew gist-logs mysql`, Thanks.

**Comment by m99coder** [comment]
https://gist.github.com/e61e1016bc4fbff3b856

**Comment by rehoehle** [comment]
I have the same problem and can't compile the new MySQL client version. Very strange. Any suggestions?

**Comment by cyberkurumin** [comment]
I have the same problem. Here is my gist: https://gist.github.com/anonymous/795ff902b763926756de

Thanks!

**Comment by DomT4** [comment]
Yeah, builds fine non-universally so I'm presuming (vaguely) this isn't a problem with the newish CMake:

```
Cellar/mysql/5.7.9: 12629 files, 464M, built in 7.0 minutes
```

Will try reverting to an old CMake though to double check.

**Comment by DomT4** [comment]
Fails identically under `3.3.2` as well, so looks like CMake definitely isn't the problem on this.

**Comment by uniacid** [comment]
Having the same problem as well and also on universal

https://gist.github.com/3dad4273899a28176e04

**Comment by rehoehle** [comment]
Some solutions here? Its a bit annoying that a get every time an error during the update.

**Comment by RogerWeihrauch** [comment]
Howdy colleagues

I notice the same issue since installing 'apr' the following way:
"brew install apr-util --universal --with-freetds --with-mysql --with-postgresql --with-sqlite --with-unixodbc --build-from-source".
So, what will be the correct options on this?
I needed the apr from brew due to the fact that the apr from Xcode CLT is not found / used / existing at correct position in file hierarchy; i notices another compile error without this version of apr w/ another tool compiled in brew; it was tomcat-as as far as I remember.

Any help will be highly appreciated in this.

Regards,
Roger

**Comment by RogerWeihrauch** [comment]
btw:
I am compiling in 10.10.5 since ElCapitan seems very crappy on these kind of things; I tried and rolled back.

Roger

**Comment by RogerWeihrauch** [comment]
Any more information needed to solve this as best possible?

Roger

**Comment by mikemcquaid** [comment]
@RogerWeihrauch that's not related to this issue. Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information in a new issue so we can help you with your problem.

Thanks!

**Comment by RogerWeihrauch** [comment]
@mikemcquiad Well, in my eyes in some way it is, since I try to install apr/boost with option --with-mysql.
This does download and install mysql-sources and compile them.

Nevertheless, I will give your hint a try and return back.

Thanx so far and regards,
Roger

**Comment by RogerWeihrauch** [comment]
@meanwhile:
My problem I solved on may way to not use the --universal option with all the others.
I think I will see if I ever will need the --universal option in the future and than I will see what happens.

Thanks for your advices and support to all.
My, this, issue can be seen as solved.

Regards,
Roger

**Comment by uniacid** [comment]
Yeah sorry forgot to mention it worked fine without using the --universal option, I still wonder if it will break in future releases.

**Comment by DomT4** [comment]
Yeah, it's a universal-exclusive bug. I'm trying to find the time to upstream it, but if anyone wants to beat me to reporting this upstream with build logs I'm certainly not going to complain.

**Comment by m99coder** [comment]
Is there any progress in that?
