### ISSUE TITLE
Build from source should be the default behavior if --cc option is passed

### ISSUE THREAD

**Issue by dtrebbien** [Homebrew/homebrew#46046]
I needed to build [Boost](http://www.boost.org) using Homebrew GCC (i.e. `gcc-5` and `g++-5`).
`brew install boost --cc=gcc-5` results in boost being installed from the bottle:

<pre>
$ brew install boost --cc=gcc-5
==> Downloading https://homebrew.bintray.com/bottles/boost-1.59.0.el_capitan.bot
######################################################################## 100.0%
==> Pouring boost-1.59.0.el_capitan.bottle.1.tar.gz
🍺  /usr/local/Cellar/boost/1.59.0: 10928 files, 454M
</pre>

As a work-around, I can additionally pass the `--build-from-source` option, but I think that building from source should be the default behavior if the `--cc` option is passed.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
