### ISSUE TITLE
openssl failed to build on 10.9

### ISSUE THREAD

**Issue by jeroenooms** [Homebrew/homebrew#46053]
Need to brew `openssl` in `/tmp` on a completely vanilla mavericks build server:

```
PKG_BREW_NAME="openssl"
BREWDIR="/tmp/homebrew"
mkdir -p $BREWDIR
echo "Auto-brewing $PKG_BREW_NAME in $BREWDIR..."
curl -fsSL https://github.com/Homebrew/homebrew/tarball/master | tar xz --strip 1 -C $BREWDIR
HOMEBREW_CACHE="/tmp" $BREWDIR/bin/brew install $PKG_BREW_NAME
```

Fails as follows:

```
Auto-brewing openssl in /tmp/homebrew...
==> Installing dependencies for openssl: makedepend
==> Installing openssl dependency: makedepend
==> Downloading https://homebrew.bintray.com/bottles/makedepend-1.0.5.mavericks.bottle.tar.gz
Already downloaded: /tmp/makedepend-1.0.5.mavericks.bottle.tar.gz
==> Pouring makedepend-1.0.5.mavericks.bottle.tar.gz
🍺  /private/tmp/homebrew/Cellar/makedepend/1.0.5: 7 files, 92K
==> Installing openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2d.tar.gz
Already downloaded: /tmp/openssl-1.0.2d.tar.gz
==> perl ./Configure --prefix=/private/tmp/homebrew/Cellar/openssl/1.0.2d_1 --openssldir=/private/tmp/homebrew/etc/openssl no-ssl2 zlib-dynamic shared enable-cms darwin64-x86_64-cc enable-ec_nistp_64_gcc_128
==> make depend
==> make
==> make test
Last 15 lines from /Users/urbanek/Library/Logs/Homebrew/openssl/04.make:
seed-cfb base64
seed-ecb
seed-ecb base64
seed-ofb
seed-ofb base64
zlib
140735234605920:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:187:filename(libz.dylib): dlopen(libz.dylib, 2): image not found
140735234605920:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:232:
140735234605920:error:29064065:lib(41):BIO_ZLIB_NEW:zlib not supported:c_zlib.c:462:
140735234605920:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:187:filename(libz.dylib): dlopen(libz.dylib, 2): image not found
140735234605920:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:232:
140735234605920:error:29064065:lib(41):BIO_ZLIB_NEW:zlib not supported:c_zlib.c:462:
cmp: EOF on ./p.zlib.clear
make[1]: *** [test_enc] Error 1
make: *** [tests] Error 2
Note: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.
```

Full `brew gist-logs` is here: https://gist.github.com/2039d9e33c9a3b5b3226. Any suggestions?

**Comment by bfontaine** [comment]
Did you try what the error message says?

> Note: It appears you have MacPorts or Fink installed.
> Software installed with other package managers causes known problems for
> Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

**Comment by jeroenooms** [comment]
There is no ports or fink installed, this is a brand new, completely clean system.

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by jeroenooms** [comment]
Here my `/tmp/homebrew/bin/brew gist-log opensl`: https://gist.github.com/d63bdea563a3b6aeb2d6

**Comment by jeroenooms** [comment]
I'm currently working around with using `--force-bottle` which seems to work. Not sure why it is not using the bottle in the first place; I don't think there is anything in openssl specific to the installation path?

**Comment by mikemcquaid** [comment]
Can you add `brew` to your PATH and rerun the `gist-log`? Thanks.

**Comment by jeroenooms** [comment]
OK here another gist: https://gist.github.com/2039d9e33c9a3b5b3226

**Comment by DomT4** [comment]
I don't think I've ever seen someone run a Homebrew from inside `/private/tmp` before :smile_cat:.

```
Xcode: 6.4
CLT: 6.2.0.0.1.1424975374
```
Is this a version mismatch between Xcode and CLT? Could be problematic, if so.

This could also cause some oddness as well:
```
Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
    /tmp/homebrew/bin/
```

**Comment by jeroenooms** [comment]
Those are just side effects of me debugging. The same problem appears on other mavericks servers. I think it is somehow picking up on the openssl 0.9.8 headers.

BTW I always run brew inside /tmp on build servers. Just need the static libraries, link them to my app and done.

**Comment by mistydemeo** [comment]
> Not sure why it is not using the bottle in the first place; I don't think there is anything in openssl specific to the installation path?

There is; we detect whether or not packages contain unrelocatable installation path references when building the binary packages. The libraries embed the prefix in a few locations, such as this set of strings from libcrypto.a:

```
OPENSSLDIR: "/usr/local/etc/openssl"
/usr/local/Cellar/openssl/1.0.2d_1/lib/engines
/usr/local/etc/openssl/private
/usr/local/etc/openssl
/usr/local/etc/openssl/certs
/usr/local/etc/openssl/cert.pem
```

**Comment by DomT4** [comment]
Let us know if we can help further here, Thanks!
