### ISSUE TITLE
How can I add the torch7(https://github.com/torch/torch7)'s support

### ISSUE THREAD

**Issue by baiyunping333** [Homebrew/homebrew#46058]
How can I add the torch7(https://github.com/torch/torch7)'s support

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
