### ISSUE TITLE
error NoMethodError on os x 10.8

### ISSUE THREAD

**Issue by cerori** [Homebrew/homebrew#46069]
Hi,

I got the following error

/usr/local/Library/Homebrew/compat/dependency_collector.rb:19: undefined method `prepend' for DependencyCollector:Class (NoMethodError)
	from /usr/local/Library/Homebrew/compat.rb:12:in `require'
	from /usr/local/Library/Homebrew/compat.rb:12
	from /usr/local/Library/Homebrew/global.rb:46:in `require'
	from /usr/local/Library/Homebrew/global.rb:46
	from /usr/local/Library/brew.rb:15:in `require'
	from /usr/local/Library/brew.rb:15

**Comment by mvkorpel** [comment]
I see the exact same error on OS X 10.7.

**Comment by ilovezfs** [comment]
Yeah. https://github.com/Homebrew/homebrew/issues/46071

You can use git revert if you know how to reverse it later.

**Comment by xu-cheng** [comment]
Sorry about that. It should be fixed now. You can update brew by `brew update --no-compat`.

**Comment by mvkorpel** [comment]
Thanks for the quick response. It works for me now.

**Comment by cerori** [comment]
Thanks for the quick response.
