### ISSUE TITLE
Downloading failures interrupt the bottle installation.

### ISSUE THREAD

**Issue by amphineko** [Homebrew/homebrew#46074]
Due to the bad network condition in China, the downloads from Bintray are often closed unexpectedly, and it causes the failure of the bottle installations.

For example:

    ==> Downloading https://homebrew.bintray.com/bottles/ghc-7.10.2.yosemite.bottle.1.tar.gz
    #######################################################                   76.8%
    curl: (18) transfer closed with 36424881 bytes remaining to read
    Error: Failed to download resource "ghc"
    Download failed: https://homebrew.bintray.com/bottles/ghc-7.10.2.yosemite.bottle.1.tar.gz
    Warning: Bottle installation failed: building from source.
    ==> Downloading https://downloads.haskell.org/~ghc/7.10.2/ghc-7.10.2-src.tar.xz

I think it should be a bug :(

**Comment by mikemcquaid** [comment]
I'm not sure what we can do about this, I'm afraid.

**Comment by bfontaine** [comment]
@mikemcquaid Could we use `curl`’s `-C` option to continue partial downloads? It takes an offset which we could get from the partially downloaded file size.

**Comment by xu-cheng** [comment]
See #46078

**Comment by mikemcquaid** [comment]
@bfontaine I believe we already do, at least for source downloads?

**Comment by bfontaine** [comment]
@mikemcquaid Yeah sorry.

**Comment by amphineko** [comment]
@xu-cheng

I think you have got what I mean, the installer should not try to build from source when the bottle installation is interrupted by hand or the networking problem.

**Comment by xu-cheng** [comment]
Then I'm glad it's fixed by #46078

**Comment by amphineko** [comment]
An additional problem:
I didn't find out how can I force the homebrew to do a source installation instead of bottle installation.

**Comment by xu-cheng** [comment]
> I didn't find out how can I force the homebrew to do a source installation instead of bottle installation.

You can set `HOMEBREW_BUILD_FROM_SOURCE` env variable for global setting or invoke `brew install foo --build-from-source` for individual formula.

**Comment by amphineko** [comment]
@xu-cheng got it, thanks.
