### ISSUE TITLE
opensc failed to build on 10.11.1

### ISSUE THREAD

**Issue by agatti** [Homebrew/homebrew#46109]
```bash
==> Installing opensc
==> Downloading https://downloads.sourceforge.net/project/opensc/OpenSC/opensc-0
==> Downloading from http://nchc.dl.sourceforge.net/project/opensc/OpenSC/opensc
######################################################################## 100.0%
==> Downloading https://github.com/carlhoerberg/OpenSC/commit/e5ae77cae32fdcc7a2
######################################################################## 100.0%
==> Patching
patching file configure.ac
==> ./bootstrap
==> ./configure --prefix=/usr/local/Cellar/opensc/0.15.0 --enable-sm --enable-op
Last 15 lines from /Users/agatti/Library/Logs/Homebrew/opensc/02.configure:
checking if more special flags are required for pthreads... -D_THREAD_SAFE
checking for PTHREAD_PRIO_INHERIT... yes
checking for inflate in -lz... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for readline in -lreadline... yes
checking readline/readline.h usability... yes
checking readline/readline.h presence... yes
checking for readline/readline.h... yes
checking for OPENSSL... yes
checking winscard.h usability... no
checking winscard.h presence... no
checking for winscard.h... no
configure: error: winscard.h is required for pcsc

READ THIS: https://git.io/brew-troubleshooting
```

Full logs here: https://gist.github.com/bb104c53655d12067b58

**Comment by dunn** [comment]
It's possible that header is only provided with the Command-Line Tools; try `xcode-select --install` and see if that makes a difference.

**Comment by DomT4** [comment]
I suspect this isn't so much of a 10.11 thing as a CLT not being installed thing. I'll check it out later today.

**Comment by agatti** [comment]
I have that file in `/usr/local/Cellar/pcsc-lite/1.8.14/include/PCSC/` - maybe there should be a hard dependency on pcsc-lite and use that headers set?

**Comment by DomT4** [comment]
It's part of the system:
```
/System/Library/Frameworks/PCSC.framework/Versions/A/Headers/winscard.h
```
Theoretically if `pcsc-lite` dupes that we should probably stop linking `pcsc-lite` into a publicly searchable prefix, i.e. `keg_only`. Likely solution is that we'll need to pass configure a location or flags when the CLT isn't installed so it checks inside Xcode, where the framework will also live.

**Comment by agatti** [comment]
@DomT4 Apparently I don't have those headers in `/System/Library/Frameworks/PCSC.framework/Versions/A/`.  Do you know if they come with the CLT?

**Comment by DomT4** [comment]
They'll be inside both the CLT and Xcode's SDK, but most things only automatically check the `/System/Frameworks/PCSC.framework` location which is created by the CLT (I believe).

**Comment by DomT4** [comment]
Closing per our discussion in the other thread :)
