### ISSUE TITLE
Emacs daemon weird list of processes

### ISSUE THREAD

**Issue by chernals** [Homebrew/homebrew#46100]
I installed the latest brew's emacs formula (24.5.1) on Mac and I'm using the daemon via homebrew services.

The daemon is running after a boot but a 'ps -ax | grep emacs' gives

  549 ??         0:02.61 /usr/local/Cellar/emacs/24.5/Emacs.app/Contents/MacOS/Emacs --daemon=^J3,4^J
  629 ??         0:00.01 /usr/local/Cellar/emacs/24.5/Emacs.app/Contents/MacOS/Emacs --daemon
  630 ??        20:45.35 /usr/local/Cellar/emacs/24.5/Emacs.app/Contents/MacOS/Emacs --daemon=^J3,4^J

I don't understand where they are coming from.

**Comment by mikemcquaid** [comment]
Is this only something that happens with a Homebrew emacs? What's the actual problem here? CC @dunn who may know more here.

**Comment by dunn** [comment]
I'm not sure what might be happening.  Are they all actively running daemons; if you kill one can you still launch Emacs with `emacsclient`?

**Comment by DomT4** [comment]
Let us know if we can help further here, Thanks!
