### ISSUE TITLE
Mytop works but gives error because of /proc/loadavg on 10.11.1

### ISSUE THREAD

**Issue by davideradice** [Homebrew/homebrew#46110]
Mytop gives this error:

readline() on closed filehandle L at /usr/local/Cellar/mytop/1.9.1_1/libexec/bin/mytop line 883.
Use of uninitialized value $l in scalar chomp at /usr/local/Cellar/mytop/1.9.1_1/libexec/bin/mytop line 885.
Use of uninitialized value $l in concatenation (.) or string at /usr/local/Cellar/mytop/1.9.1_1/libexec/bin/mytop line 916.

Here is /usr/local/Cellar/mytop/1.9.1_1/libexec/bin/mytop at lines 883-884:

```perl
	open L, "</proc/loadavg";
	my $l = <L>;
```

On my system

```sh
cat /proc/loadavg 
```

gives me this:

```sh
cat: /proc/loadavg: No such file or directory
```

My system:
```
Mac OS X
10.11.1
```

Mytop:
```
mytop: stable 1.9.1 (bottled)
Top-like query monitor for MySQL
http://www.mysqlfanboy.com/mytop-3/
Conflicts with: mariadb
/usr/local/Cellar/mytop/1.9.1_1 (21 files, 432K) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/mytop.rb
==> Dependencies
Required: openssl ✔
```

**Comment by DomT4** [comment]
> /proc/loadavg 

This is a Linux thing, so doesn't exist on OS X. Is the error you're experiencing fatal?

**Comment by davideradice** [comment]
No, it's not fatal. Anyway, is there a way for NOT showing errors in output?

Other errors, not platform specific, are shown:
```
Useless use of private variable in void context at /usr/local/Cellar/mytop/1.9.1_1/libexec/bin/mytop line 998.
"my" variable $data masks earlier declaration in same scope at /usr/local/Cellar/mytop/1.9.1_1/libexec/bin/mytop line 1032.
Argument "5.6.23" isn't numeric in sprintf at /usr/local/Cellar/mytop/1.9.1_1/libexec/bin/mytop line 286.
```

**Comment by DomT4** [comment]
No idea. Don't use the tool myself. Upstream hasn't been known to be active for a while now, but normally we'd suggest contacting upstream and asking them to fix up the syntax errors. If you know an alternative website/email where they can be reached that'd probably be the best course of action.

They seem to be harmless enough Perl syntax errors though. Debian looks to have patched them out of their [mytop](https://sources.debian.net/patches/patch/mytop/1.9.1-2/10_fix_perl_warnings.patch/), so we could adopt that patch and see how many warnings it resolves.

**Comment by davideradice** [comment]
Thank you. 

I've fixed adding 
```
no warnings "all";
```
to /usr/local/Cellar/mytop/1.9.1_1/libexec/bin/mytop at line 24.
