### ISSUE TITLE
Multimarkdown 5 available

### ISSUE THREAD

**Issue by hendrikstier** [Homebrew/homebrew#46112]
Announcement: http://fletcherpenney.net/2015/11/mmd_5.0.0_released
Repository: https://github.com/fletcher/MultiMarkdown-5
Binaries: https://github.com/fletcher/MultiMarkdown-5/releases

**Comment by bfontaine** [comment]
Could you open a pull-request? This should help and I’m happy to answer any question you might have: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

**Comment by hendrikstier** [comment]
Sure, I will try. How do I go about with the bottles? Remove them for the time being?

```ruby
bottle do
  cellar :any_skip_relocation
  sha256 "0f9758705ae952f5d33d5eec397bf352a182217500c73bdd64b5c43e5d5c640c" => :el_capitan
  sha256 "3ee488167591254206ff276f3b15ec760be60ff76bf1729ef0d49ba3efd1a1a2" => :yosemite
  sha256 "e1ca2bd2e5667406abe9629a03e12b6670336e6efdcdfa71b6b53e93f6f886a1" => :mavericks
  sha256 "7b3b8c13b58c25cd8eae393275361d7442d47e285df34898818604ac6279cb94" => :mountain_lion
end
```

**Comment by bfontaine** [comment]
Leave them as is; our bot will update them.

**Comment by hendrikstier** [comment]
PR (https://github.com/Homebrew/homebrew/pull/46120) added.

**Comment by hendrikstier** [comment]
While the installation itself is workings, the tests fail, and hence the bots cannot create bottles.

@bfontaine How can I include the fix (https://github.com/hendrikstier/homebrew/commit/2eab77c772ff37794a6a6daac163aa05c2dad131) in the PR? Or shall I close it, squash the commits and create a new PR?

**Comment by bfontaine** [comment]
@hendrikstier You can squash the commits and force-push your PR branch. It’ll update the PR so you don’t have to close it and open another one.

**Comment by hendrikstier** [comment]
Very good! After a bit of fiddling with my credentials and the PTAs, it worked. Thanks for the advice!
