### ISSUE TITLE
npm: `npm outdated -g` errors - specific to Homebrew npm installation

### ISSUE THREAD

**Issue by ericvw** [Homebrew/homebrew#46131]
`npm outdated -g` does not to appear to behave correctly when installed via the `node` formula.  To reproduce:
```shell
$ npm outdated -g
npm ERR! addLocal Could not install /private/tmp/node20151118-87384-ribwmd/node-v5.1.0/npm_install

$ npm outdated
# note that this only appears to be affected with -g
```

I have verified that both v5.0.0 and v5.1.0 via Homebrew experiences this issue.  When using `nvm` to test out a near 'vanilla' installation, this error does not occur.

In researching this issue, I came across npm/npm#10165 as well.  I am still digging a bit deeper to understand the root cause.

**Comment by DomT4** [comment]
That's a pretty interesting issue.

As you can see [here](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/node.rb#L65-L76) we temporarily put `npm` into our buildpath and tell it to install in the Node Cellar `libexec` path, and then we move it to the correct location after install. This is designed to save users having to sit around whilst `npm` is downloaded and compiled after they pour a bottle.

Obviously despite passing a `prefix` argument `npm` has some sort of memory of briefly living in the `buildpath` and being compiled from there, despite being told to install elsewhere. I wonder where that path retention is happening, and whether the fact it happens is an `npm` bug to a degree.

I'll poke around and try to discover where it remembers the path.

**Comment by DomT4** [comment]
Ah, the place you build `npm` from is retained in `npm`'s `package.json` file, apparently. Presumably, it should be remembering the place you install it, rather than the place it is built from, although I appreciate normally `npm` would likely not be compiled inside a temporary directory wiped afterwards.

**Comment by ericvw** [comment]
Good catch!

Is there a particular reason why we shouldn't use Node.js's bundled `npm` dependency instead of installing it 'out-of-band'?

**Comment by ericvw** [comment]
I think I have a change to address this - will create a PR shortly.

**Comment by DomT4** [comment]
There's an *exceptionally* long and boring history as to why `npm` is currently installed the way it is in Homebrew, heh. Essentially, to skip the history, this way works for us in terms of giving us control over where/how `npm` is installed and not encountering weird permission issues.

This way hasn't broken in a fairly long time, which compared to the way the Homebrew/Node relationship used to be, is something of a joyous relief on both sides I'd imagine.

What are your thoughts on the fix? I had a fairly blunt one in mind if necessary, but was poking around for the root cause to see if there was anything more elegant.

**Comment by ericvw** [comment]
The short version is removing the `--without-npm` to `args` during `make install`.  Then removing build/postinstall logic for `npm`.  Everything seems to be in working order and the formula is much simpler.

The thing I have realized doing that is that global installed `npm` modules go into the Cellar instead of `/usr/local/node_modules`.  Which is definitely a change of behavior, but probably safer - especially when dealing with native modules that may not be binary compatible across different node/v8 APIs.

**Comment by DomT4** [comment]
Yeah. We don't really want to go back to a system where `node` is allowed to install its own `npm` sadly :cry:. There were so many problems with that we had pretty much daily Node related issues to deal with and at one point I pretty seriously considered and discussed Homebrew stopping supplying Node.

In regards to the Cellar it gets wiped on every update, and we'd get buried with complaints about that. People expect modules to stick around.

**Comment by ericvw** [comment]
I can imagine that this was/is one of those controversial discussions :D.

**Comment by DomT4** [comment]
Interestingly, even doing `npm install -g npm@latest` you end up with some hardcoded paths in the json:

```
  "man": [
    "/Users/rebecca/code/release/npm-3/man/man1/npm-README.1",
    "/Users/rebecca/code/release/npm-3/man/man1/npm-access.1",
    "/Users/rebecca/code/release/npm-3/man/man1/npm-adduser.1",
    "/Users/rebecca/code/release/npm-3/man/man1/npm-bin.1",
    "/Users/rebecca/code/release/npm-3/man/man1/npm-bugs.1",
    "/Users/rebecca/code/release/npm-3/man/man1/npm-build.1",
    "/Users/rebecca/code/release/npm-3/man/man1/npm-bundle.1",
    "/Users/rebecca/code/release/npm-3/man/man1/npm-cache.1",
    "/Users/rebecca/code/release/npm-3/man/man1/npm-completion.1",
    "/Users/rebecca/code/release/npm-3/man/man1/npm-config.1",
    "/Users/rebecca/code/release/npm-3/man/man1/npm-dedupe.1",
    "/Users/rebecca/code/release/npm-3/man/man1/npm-deprecate.1",
    "/Users/rebecca/code/release/npm-3/man/man1/npm-dist-tag.1",
```

**Comment by DomT4** [comment]
Note: My name is note Rebecca :wink:

**Comment by ericvw** [comment]
You can see what I have done here: https://github.com/ericvw/homebrew/commit/b6bc41c5ec7af002a67e7063eddf9532e30329a8.  It makes the formula much simpler, at the 'cost' of `node_modules` being under `/usr/local/Cellar/node/*/lib/node_modules`.

This also reduces the maintenance of keeping the `npm` version synchronized with what is deployed with `node`.

**Comment by ericvw** [comment]
Maybe we could make the 'vanilla' installation of `npm` packaged from the Node.js source an option?

**Comment by DomT4** [comment]
Yeah. I see & do appreciate what you're trying to do in terms of the simplicity, but that model doesn't work with Homebrew and has caused fairly epic discussions betwen Node/Homebrew before now. I don't have a lot of enthusiasm to return to a system that caused both sets of developers so much grief.

I'd rather explore other options, sadly.

**Comment by ericvw** [comment]
I think I figured out what the root cause is here.  It appears that when you untar `npm`, it expects that that it is already located at `$PREFIX/lib/node_modules/npm` since `make install` just executes `node cli.js install -g -f ${NPMOPTS}`.

**Comment by DomT4** [comment]
It's a cheeky hack, but it *seems* like if you just replace the installed `package.json` with the one in the tarball after install it solves the problem without breaking anything else. I'm looking at seeing whether we can tweak the install process though, before trying to adopt the hack.

**Comment by ericvw** [comment]
That works and is basically the same result as if you untar'd the `npm` in `/usr/local/lib/node_modules/npm` and created the necessary symlinks, which is what I was going to suggest and may be a bit more clear on the desired intent.

**Comment by DomT4** [comment]
Can always add "explanatory comments" if decide to go down the route of the `package.json` replacement; the Node formula is full of them already due to the various special attention it has received over the years.

**Comment by ericvw** [comment]
Closing in favor of #46186.

**Comment by ericvw** [comment]
Meant to close out PR #46139, not this issue.
