### ISSUE TITLE
Can't Install Homebrew on OS X 10.11.1

### ISSUE THREAD

**Issue by zeraus** [Homebrew/homebrew#46152]
I can't install homebrew on mac. It showing this:

`/Users/saw/.rbenv/shims/ruby: line 21: /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv: No such file or directory`

..after I ran this command:

`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

Please help!

**Comment by DomT4** [comment]
Apparently your current Ruby is set up via Rbenv, but it's pointing to a Homebrew Cellar path which presumably doesn't exist if you're trying to install Homebrew?

You could try:

```bash
rbenv shell system
```

And then execute the install command again.

**Comment by zeraus** [comment]
![ss](https://s3.amazonaws.com/f.cl.ly/items/192n3k0v1l102S1N3z3G/Screenshot%202015-11-19%2011.21.35.png)

**Comment by DomT4** [comment]
Oh, well, that should have been obvious I guess. You may want to remove any `rbenv` references in your shell configuration files, or at least comment them out, and then open a new tab/new terminal/etc and try again.

**Comment by zeraus** [comment]
Works!!! Thanks! :+1:   :smile:
