### ISSUE TITLE
libgphoto2 2.5.9.1 configure fails

### ISSUE THREAD

**Issue by gschwim** [Homebrew/homebrew#46155]
This may have to do with libltdl. See below.

Been trying to get this to build all week. Here are the gist logs:

https://gist.github.com/anonymous/2a4ac152db891e0c9b3e

Here is the git source file that I am referencing. I am creating a new recipe with it as I need the updates to control my camera. The existing 2.5.8 recipe does not have the updates needed for this.

https://github.com/gphoto/libgphoto2/archive/master.zip

I get little information out of homebrew when trying to install it. If I try to build by hand I get the following error during ./configure:

    checking that we can compile and link with libltdl... no
    configure: error: cannot compile and link against libltdl
    libgphoto2 requires libltdl (the libtool dl* library),  
    but cannot compile and link against it.
    Aborting.

However I have libtool installed.

**Comment by tschoonj** [comment]
I think `libtool` is both a `:build` and a `:run`-time dependency. Try removing the `=> :run` part next to `depends "libtool"` in the formula.

**Comment by DomT4** [comment]
> Try removing the => :run part next to depends_on "libtool" in the formula.

`:run` formulae should also be present during install, AFAIK.

**Comment by gschwim** [comment]
I ended up using the latest tarball from here:

http://downloads.sourceforge.net/project/gphoto/libgphoto/2.5.9/libgphoto2-2.5.9.tar.gz

And it just seemed to work.

To do this, i ran

  brew edit libphoto2

...and replaced the source URL with the above link. I also commented out the sha link.

Apparently some difference between that and what is on git.
