### ISSUE TITLE
QT overflooding terminal with error stream

### ISSUE THREAD

**Issue by osbama** [Homebrew/homebrew#46156]
Dear developers,
When I use gnuplot, the terminal gets overfed with the following message 
"QCocoaView handleTabletEvent: This tablet device is unknown (received no proximity event for it). Discarding event."

I think the issue is the same as: https://github.com/appleseedhq/appleseed/issues/254

Sadly, it cripples my interactive gnuplot sessions, and I consider it as a problem more than irritation. 

All the best, and I appreciate your excellent work,

**Comment by mikemcquaid** [comment]
This is something that needs fixed in GNU Plot and/or Qt rather than Homebrew, sorry!
