### ISSUE TITLE
Broken bottles

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew#46168]
Putting them here to remember to fix them:

- [x] telepathy-gabble (all 404)
- [x] mksh (all 404)
- [x] yamcha (wrong sha1 for the ML bottle)
- [x] fortune (404 on El Cap, see https://github.com/Homebrew/homebrew/issues/45888#issuecomment-158643308)

**Comment by mikemcquaid** [comment]
Updated fortune in c07e70a.

**Comment by bfontaine** [comment]
Thanks Mike!
