### ISSUE TITLE
Set a non-homebrew default compiler?

### ISSUE THREAD

**Issue by josephwb** [Homebrew/homebrew#46161]
In the past I've been able to set a default compiler for homebrew using:
```
HOMEBREW_CC=gcc-4.9
HOMEBREW_CXX=g++-4.9
```
However, `g**-4.9` above was installed using homebrew. 

Recently I've decided to go with alternate compilers, specifically those found [here](http://hpc.sourceforge.net). These get installed in `/usr/local/bin`.

When I try to set these as my default compilers I get an error:
```
$ HOMEBREW_CC=gcc brew --env
Error: Invalid value for HOMEBREW_CC: gcc

$ HOMEBREW_CC=/usr/local/bin/gcc brew --env
Error: Invalid value for HOMEBREW_CC: /usr/local/bin/gcc
```
 and so clang is used (which is unacceptable).

Is there a way to set `HOMEBREW_CC` and `HOMEBREW_CXX` to non-homebrew compilers?

**Comment by mikemcquaid** [comment]
> Is there a way to set HOMEBREW_CC and HOMEBREW_CXX to non-homebrew compilers?

No, sorry.

> so clang is used (which is unacceptable).

Why is that unacceptable? Can you provide more explanation here?

**Comment by DomT4** [comment]
Why is Clang unacceptable, out of curiosity? It is the default OS X compiler and other platforms are starting to move towards it as well. It's possible that setting a permanent compiler that isn't the OS X expectation could cause some quirky build errors we'd have trouble debugging.

**Comment by josephwb** [comment]
Unacceptable as we do cross-platform development and gcc is more portable.

So if I install `gcc` from homebrew I can set `HOMEBREW_CC` and `HOMEBREW_CXX` as before? Just checking that nothing has changed. (But if this is the case, I don't see why I couldn't trick homebrew into using my own compilers, maybe using a symlink?)

**Comment by mikemcquaid** [comment]
> Unacceptable as we do cross-platform development and gcc is more portable.

I did cross-platform development for 5+ years and found using multiple compilers makes your code more portable and more robust.

> I don't see why I couldn't trick homebrew into using my own compilers, maybe using a symlink?

Please don't try and do this. If you do: you're on your own and please don't ever file support issues.

**Comment by josephwb** [comment]
Fair enough.

For the record, the "unacceptability" of `clang` regards support for `openmp`, which is a deal breaker for the computationally intensive programs we use/write (analyses with which can take weeks or months, even with multiple processor support). I understand that `clang` is getting closer to supporting `openmp` (and homebrew has a `clang-omp` available), but not nearly enough people on mac or linux use it to make it a viable alternative to `gcc`.

**Comment by mikemcquaid** [comment]
@josephwb Almost everyone uses Clang on Mac FWIW. I'm still not sure how "we need to use openmp to build our software" translates to "we need to use GCC to build everything in Homebrew". Can you explain?

**Comment by josephwb** [comment]
@mikemcquaid Thanks for following up, as it is quite likely that I am being naive about this, and I'd welcome being put straight.

From my experience, no one on linux is using `clang` (I'm sure that is not true, but that is my experience), and never any clusters that I've seen. Compiling things on mac with `gcc` is easy. Since `gcc` is more portable, in that it works and is available everywhere, this is what we use for development (where things will eventually be run on both mac and linux).

For the most part, I couldn't care less which compiler `homebrew` uses, as long as things work.

Where, and only where, `homebrew` becomes relevant on the `gcc`/`clang` issue is with dependencies: things compiled with `gcc` (my code, which requires `openmp`) often doesn't play nice with code compiled with `clang` (say, something installed from `homebrew`), and if `openmp` is required for the dependency itself then it won't work at all (in that multiple processors will not used, even if things compile and run; `clang` seems to just ignore references to `openmp`).

And here is where my naivety will be clear. I am happy to exclusively use `clang` on mac if it will satisfy my _one and only one_ requirement: `openmp`. Alternatively, if there is an easy way get `clang` to perform the parallel operations that `openmp` allows, without extensive rewriting of the code, then that could work too (but it would be vastly preferable if everything could be handled at the `./configure` stage alone).

**Comment by mikemcquaid** [comment]
Ok, that makes sense. In that case I'd advise you use the `--cc` argument for the specific things you know to be causing you issues with Clang and otherwise leave it as-is.

**Comment by josephwb** [comment]
Cool, thanks.
