### ISSUE TITLE
brew link for git-2.6.3 fails on 10.10.5

### ISSUE THREAD

**Issue by CraigCottingham** [Homebrew/homebrew#46175]
```
Linking /usr/local/Cellar/git/2.6.3... Error: Permission denied - /usr/local/lib/perl5
```

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by CraigCottingham** [comment]
Okay, my bad. The error message didn't make it clear that it was trying to _create_ the directory `/usr/local/lib/perl5`, and the owner of `/usr/local/lib` was set to `root`. Fixed, and `brew link` works now.
