### ISSUE TITLE
Remove OS X OpenVPN / tuntap dependancy

### ISSUE THREAD

**Issue by lacombar** [Homebrew/homebrew#46183]
When trying to install openvpn on el captain, I get the following error:

```
% brew install openvpn
tuntap: Building this formula from source isn't possible due to OS X
Yosemite and above's strict unsigned kext ban.

You can install with Homebrew Cask:
  brew install Caskroom/cask/tuntap

You can download from:
  http://sourceforge.net/projects/tuntaposx/files/tuntap/
```

Recent OpenVPN have been getting support for OS X utun(4) interface which allow creation of tunnel interface without any additional kext on +10.6.

**Comment by DomT4** [comment]
> Recent OpenVPN have been getting support for OS X utun(4) interface which allow creation of tunnel interface without any additional kext on +10.6.

Can you provide documentation to confirmation of this? Thanks.

**Comment by lacombar** [comment]
See commit fbc04bedbcce02fc625357b7475ddbc7164cabfb of the OpenVPN repository.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request to fix this? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by lacombar** [comment]
Sure. Does brew support pre-10.7 OS X ? If it does, we probably want to have a conditional dependancy on tuntap for these versions.

**Comment by mistydemeo** [comment]
> Sure. Does brew support pre-10.7 OS X ? If it does, we probably want to have a conditional dependancy on tuntap for these versions.

It does, yes. A conditional dependency would be helpful, thanks!

**Comment by lacombar** [comment]
I'll give it a shot. My ruby might be a bit rusty [no pun intended], though.

**Comment by lacombar** [comment]
see #46226

**Comment by lacombar** [comment]
btw, the submitted patch make openvpn works just fine on El Captain:

```
Fri Nov 20 13:18:42 2015 OpenVPN 2.3.8 x86_64-apple-darwin15.0.0 [SSL (OpenSSL)] [LZO] [MH] [IPv6] built on Nov 20 2015
Fri Nov 20 13:18:42 2015 library versions: OpenSSL 1.0.2d 9 Jul 2015, LZO 2.09
[...]
Fri Nov 20 13:19:15 2015 Opened utun device utun0
[...]
```

**Comment by lacombar** [comment]
Updated code in #46229

I'm not sure of the pull-request policy. I opted to stash the changes, discard the old pull request and create a new one. The github workflow is a bit awkward as I would expect pull-request to concern clean, and reviewed history... I'm not a huge fan of dirty history as it seems to be designed for...

**Comment by bfontaine** [comment]
@lacombar You can force-push to a pull-request branch to update it.

**Comment by DomT4** [comment]
Closing in favour of the PR, Thanks!
