### ISSUE TITLE
 brew info mysql56,install mysql version is 5.7.9

### ISSUE THREAD

**Issue by y284663247** [Homebrew/homebrew#46194]
brew info mysql56,install mysql version is 5.7.9,how can i return to mysql5.6

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 16
Server version: 5.7.9 Homebrew

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

**Comment by DomT4** [comment]
We haven't renamed the binary there, so probably:

```
brew unlink mysql && brew link mysql56
```

**Comment by PatrickMcAfee** [comment]
I'm seeing this issue as well.  I've installed homebrew/versions/mysql56 fresh (and if I run the given link/unlink then I'm told correctly there is nothing to unlink and the link already exists) and I'm still seeing "Server version: 5.7.9"

**Comment by FInGrayson** [comment]
Something that worked for me was:

brew unlink mysql
brew switch mysql56 5.6.27

**Comment by PatrickMcAfee** [comment]
@FInGrayson Same result.  Still seeing version 5.7.9

**Comment by benlinton** [comment]
Check out this gist for more details.
https://gist.github.com/benlinton/d24471729ed6c2ace731

**Comment by bmrsny** [comment]
I had the same issue as @PatrickMcAfee https://coderwall.com/p/os6woq/uninstall-all-those-broken-versions-of-mysql-and-re-install-it-with-brew-on-mac-mavericks

this link helped me fix it. But i had to also remove `mysql56` files and then `brew mysql56` instead of just brew `mysql`
