### ISSUE TITLE
Problem with fltk formula

### ISSUE THREAD

**Issue by PierreMarchand20** [Homebrew/homebrew#46206]
I am very new to homebrew, I have an issue with the fltk formula. I get (I am on OS X 10.11.1) : 
fltk: This formula either does not compile or function as expected on OS X
versions newer than Yosemite due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.

It seems that fltk includes support for El Capitan (cf. fltk.rb)  but the ruby formula should change the way it checks the OS version.

**Comment by DomT4** [comment]
The stable build is known to not compile on anything newer than Yosemite at the moment. This is fixed in the `devel` build available, so you can `brew install fltk --devel` for now until they cut a new stable release with the fix in.
