### ISSUE TITLE
Pypy v4.0.1 release

### ISSUE THREAD

**Issue by cclauss** [Homebrew/homebrew#46207]
http://morepypy.blogspot.ch/2015/11/pypy-401-released-please-update.html

I would submit a formula for this myself if I could figure only out how you folks calculate the sha256 for el_capitan, yosemite and mavericks bottles.  I know how to come up with the sha256 for the src.tar.bz2 file but not for the bottles.

```
class Pypy < Formula
  desc "Implementation of Python 2 in Python"
  homepage "http://pypy.org/"
  url "https://bitbucket.org/pypy/pypy/downloads/pypy-4.0.0-src.tar.bz2"
  sha256 "acff480e44ce92acd057f2e786775af36dc3c2cd12e9efc60a1ac6a562ad7b4d"

  bottle do
    cellar :any
    sha256 "dc76aa84fb53dfa27e99d4e7b6203c88baa05728855db2d2ccbe5c1451daa65b" => :el_capitan
    sha256 "ba316ef2f1f7471df101dc8ae86a30249931beb8c8e84ae561eb0b2f14db1d37" => :yosemite
    sha256 "2ee52ddf499073d9591d48ab20b18ed578733415d34a5007a5fe4805ccbe9bff" => :mavericks
  end
```

**Comment by bfontaine** [comment]
Don’t worry about the bottles; leave the block as is and our CI bot will update them. Thanks!

**Comment by DomT4** [comment]
Closing in favour of https://github.com/Homebrew/homebrew/pull/46209, Thanks!
