### ISSUE TITLE
Need update on phantomjs

### ISSUE THREAD

**Issue by lileeyao** [Homebrew/homebrew#46228]
```
***** ➤ brew install phantomjs                                    
phantomjs: This formula either does not compile or function as expected on OS X
versions newer than Yosemite due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
```

maybe some similar solutions to `npm install phantom phantomjs -g`?

**Comment by lileeyao** [comment]
btw, I do know the hacky solution to copy executable file in to /usr/local/bin,  but anyway, an official support for it would be great.

**Comment by bfontaine** [comment]
We’re waiting for an upstream release, see #42249.
