### ISSUE TITLE
Connections to homebrew.bintray.com timing out, defaulting to source.

### ISSUE THREAD

**Issue by hbarn** [Homebrew/homebrew#46233]
$ brew install youtube-dl
stalls at:
==> Downloading https://homebrew.bintray.com/bottles/youtube-dl-2015.11.19.el_capitan.bottle.tar.gz

ends up building from source:
curl: (7) Failed to connect to homebrew.bintray.com port 443: Operation timed out
Error: Failed to download resource "youtube-dl"
Download failed: https://homebrew.bintray.com/bottles/youtube-dl-2015.11.19.el_capitan.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://yt-dl.org/downloads/2015.11.19/youtube-dl-2015.11.19.tar.gz
######################################################################## 100.0%
==> make PREFIX=/usr/local/Cellar/youtube-dl/2015.11.19
==> Caveats
To use post-processing options, `brew install ffmpeg` or `brew install libav`.
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/youtube-dl/2015.11.19: 9 files, 1.2M, built in 6 seconds

$ wget https://homebrew.bintray.com/bottles/youtube-dl-2015.11.19.el_capitan.bottle.tar.gz
results in:
--2015-11-20 17:50:25--  https://homebrew.bintray.com/bottles/youtube-dl-2015.11.19.el_capitan.bottle.tar.gz
Resolving homebrew.bintray.com... 108.168.194.91, 108.168.194.92
Connecting to homebrew.bintray.com|108.168.194.91|:443... failed: Operation timed out.
Connecting to homebrew.bintray.com|108.168.194.92|:443...

There seems to be an issue connecting to homebrew.bintray.com:
$ ping homebrew.bintray.com
PING dl.bintray.com (108.168.194.91): 56 data bytes
76 bytes from [MY IP ADDRESS]: Time to live exceeded
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 d1fe   0 0000  01  01 ada3 10.0.1.4  108.168.194.91 
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7
Request timeout for icmp_seq 8
Request timeout for icmp_seq 9
Request timeout for icmp_seq 10
Request timeout for icmp_seq 11
76 bytes from [MY IP ADDRESS]: Time to live exceeded
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 c226   0 0000  01  01 bd7b 10.0.1.4  108.168.194.91 
Request timeout for icmp_seq 12
Request timeout for icmp_seq 13
Request timeout for icmp_seq 14
Request timeout for icmp_seq 15

**Comment by bfontaine** [comment]
I can reproduce:
```
$ ping homebrew.bintray.com
PING dl.bintray.com (5.153.24.114): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
```

Their status page doesn’t mention any incident: http://status.bintray.com/. I `ping`-ed (no pun intended) them on Twitter.

**Comment by bfontaine** [comment]
It’s ok for me now:
```
curl -I https://homebrew.bintray.com/bottles/youtube-dl-2015.11.19.el_capitan.bottle.tar.gz
HTTP/1.1 200 OK
Server: nginx
Date: Sat, 21 Nov 2015 00:11:19 GMT
Content-Type: application/gzip
Content-Length: 1017665
Connection: keep-alive
Last-Modified: Thu, 19 Nov 2015 23:43:13 GMT
ETag: 60a5964da399fa68407d63b9709782e3444f3ae3
X-Checksum-Sha1: 60a5964da399fa68407d63b9709782e3444f3ae3
Accept-Ranges: none
```

**Comment by hbarn** [comment]
$brew install [package name] --build-from-source
works for most packages as a temporary work-around.

**Comment by hbarn** [comment]
wget connections now seem to work:

$ wget https://homebrew.bintray.com/bottles/libzip-1.0.1.el_capitan.bottle.tar.gz
--2015-11-20 19:25:38--  https://homebrew.bintray.com/bottles/libzip-1.0.1.el_capitan.bottle.tar.gz
Resolving homebrew.bintray.com... 108.168.194.92, 108.168.194.91
Connecting to homebrew.bintray.com|108.168.194.92|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 117608 (115K) [application/x-gzip]
Saving to: 'libzip-1.0.1.el_capitan.bottle.tar.gz'
libzip-1.0.1.el_capitan.bottle 100%[======================================================>] 114.85K   580KB/s   in 0.2s   
2015-11-20 19:25:39 (580 KB/s) - 'libzip-1.0.1.el_capitan.bottle.tar.gz' saved [117608/117608]

but running from within brew still fails:

$ brew install ebook-tools
==> Installing dependencies for ebook-tools: libzip
==> Installing ebook-tools dependency: libzip
==> Downloading https://homebrew.bintray.com/bottles/libzip-1.0.1.el_capitan.bottle.tar.gz
curl: (7) Failed to connect to homebrew.bintray.com port 443: Operation timed out
Error: Failed to download resource "libzip"
Download failed: https://homebrew.bintray.com/bottles/libzip-1.0.1.el_capitan.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading http://www.nih.at/libzip/libzip-1.0.1.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/libzip/1.0.1 --mandir=/usr/local/Cellar/libzip/1.0.1/share/man CXX=clang++ CXXFLA
==> make install

**Comment by bfontaine** [comment]
Does `curl -q -I https://homebrew.bintray.com/bottles/libzip-1.0.1.el_capitan.bottle.tar.gz` work?

**Comment by hbarn** [comment]
Yes.

Seems to be working now.

$ brew install lynx
==> Installing dependencies for lynx: openssl
==> Installing lynx dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2d_1.el_capitan
######################################################################## 100.0%
==> Pouring openssl-1.0.2d_1.el_capitan.bottle.tar.gz

**Comment by turu** [comment]
It is still failing for me... and bintray's status page mentions no incidents...
```bash
$ curl -q -I https://homebrew.bintray.com/bottles/libzip-1.0.1.el_capitan.bottle.tar.gz
curl: (7) Failed to connect to homebrew.bintray.com port 443: Operation timed out
```

**Comment by bfontaine** [comment]
@turu I don’t think we can really do anything for you here :confused:

**Comment by DomT4** [comment]
It's probably worth checking if you have any curl proxy variables being passed in the env, if `wget` works locally for you.
