### ISSUE TITLE
userSpaceScaleFactor error message (use convertRectToBacking: instead): gwyddion app

### ISSUE THREAD

**Issue by PierreChapuis** [Homebrew/homebrew#46239]
Hi,

I have a question about an application installed using Homebrew.
This concerned the gwyddion app (for scientific measurements). The installation was completed, then I ran brew link and brew doctor. The both succeeded. 

However when I start gwyddion I get an error message:
*** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.

Fist of all I didn't take into account this message because the gwyddion can be open anyway.
But I have a problem when I use the 3D drawing in the app: the icons are physically present but completely transparent (hidden)... so it is very difficult to set the 3D drawing. In attached files you can see a good picture of the window (taken from the gwyddion website) and the window I get.

![good_window_with_icons](https://cloud.githubusercontent.com/assets/15954349/11317888/4fc7d40e-903e-11e5-9bee-ae8d3ff9a644.jpg)
![my_bad_window](https://cloud.githubusercontent.com/assets/15954349/11317889/4ff96a78-903e-11e5-96cb-a6c26c0eb05c.jpg)

Is this issue due to the warning message ?
I want to precise that before to install homebrew I used MacPort and gwyddion worked fine with it. But I uninstalled MacPort to put Homebrew because it takes less HD memories.
Thank in advance,
Best regards.

(I use a retina Macbook Pro 13 inches early 2015, on El Capitan 10.11.1)

**Comment by PierreChapuis** [comment]
I also have an other display issue using gwyddion.
You can see here:

![capture d ecran 2015-11-21 a 11 31 52](https://cloud.githubusercontent.com/assets/15954349/11318067/a832fa06-9043-11e5-92df-f58a48d62e10.jpg)

I can draw some profils (in real time by clicking and moving a line where I want) but there are some residual 'shadows' of the profil numbers like on the previous picture.

**Comment by bfontaine** [comment]
You should ask this to gwyddion’s developpers.

**Comment by mikemcquaid** [comment]
Yup, this doesn't look like a Homebrew issue.
