### ISSUE TITLE
How to embed multiple patches

### ISSUE THREAD

**Issue by adilinden** [Homebrew/homebrew#46246]
Hi,

I would like to embed multiple patches.  But I don't quite understand the instructions at [Patches@Cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#patches).  I am building (adding a feature to a fork) a formula that has several build options, such as `--head`, `--devel`.  But each one of those needs a slightly different patch.  I was able to successfully add a patch for `stable` to the formula.  It works great.  But how can I go about adding a different patch for `devel` and possibly `head`?

The formula I am working with is [asterisk.rb](https://github.com/adilinden/homebrew-asterisk/blob/master/asterisk.rb).

Thanks,
Adi

**Comment by DomT4** [comment]
You can't have unique `__END__` blocks for each section if that's part of what you're asking. You can have external patches for each section though, or external patches for two sections and an inline patch for the third section, etc.

```ruby
stable do
  url "https://example.com/example.tar.gz"
  sha256 "13550350a8681c84c861aac2e5b440161c2b33a3e4f302ac680ca5b686de48de"

  patch do
    url "https://example.com/example_stable.diff"
    sha256 "13550350a8681c84c861aac2e5b440161c2b33a3e4f302ac680ca5b686de48de"
  end
end

devel do
  url "https://example.com/example_beta1.tar.gz"
  sha256 "13550350a8681c84c861aac2e5b440161c2b33a3e4f302ac680ca5b686de48de"

  patch do
    url "https://example.com/example_devel.diff"
    sha256 "13550350a8681c84c861aac2e5b440161c2b33a3e4f302ac680ca5b686de48de"
  end
end

**Comment by bfontaine** [comment]
Like the doc says at the end of the section, you can also embed multiple patches e.g.:

```
stable do
  # ...

  patch :p0, <<-EOS.undent
    ...the patch...
  EOS
end

devel do
  # ...

  patch :p0, <<-EOS.undent
    ...the patch...
  EOS
end
```

**Comment by adilinden** [comment]
I converted the formula to use external patch files.  Now it appears homebrew is getting confused and not downloading the proper patch file specified in the formula.  In the formula I have:

```ruby
  stable do
    patch :p0 do
      url "https://raw.githubusercontent.com/adilinden/homebrew-asterisk/master/patches/asterisk-13.6.0_basic-pbx.diff"
      sha256 "53a99bd7cfa3dca371c929c5a0f366639c92e4ca7e03e882af5a79756fd11443"
    end
  end

  devel do
    url "https://github.com/asterisk/asterisk.git", :branch => "13"
    version "13.7-devel"

    patch :p0 do
      url "https://raw.githubusercontent.com/adilinden/homebrew-asterisk/master/patches/asterisk-13.7-devel_basic-pbx_install.diff"
      sha256 ""
    end
  end
```

I first built the `stable` and it worked just fine.  The diff downloaded and applied fine.  However, when I subsequently run `brew remove asterisk` followed by `brew install -vd asterisk --devel` it does not download the patch specified but reuse the previously cached file from the `stable` build.

```
==> Downloading https://raw.githubusercontent.com/adilinden/homebrew-asterisk/master/patches/asterisk-13.7-devel_basic-pbx_install.diff
Already downloaded: /Library/Caches/Homebrew/asterisk--patch-.diff
==> Verifying asterisk--patch-.diff checksum
Warning: Cannot verify integrity of asterisk--patch-.diff
A checksum was not provided for this resource
For your reference the SHA256 is: 53a99bd7cfa3dca371c929c5a0f366639c92e4ca7e03e882af5a79756fd11443
```

As you can see, it refers to the proper URL but reuses `/Library/Caches/Homebrew/asterisk--patch-.diff` which is not `asterisk-13.7-devel_basic-pbx_install.diff` but `asterisk-13.6.0_basic-pbx.diff` instead.

**Comment by DomT4** [comment]
Try adding a `sha256` to the second patch.

**Comment by adilinden** [comment]
> Try adding a sha256 to the second patch.

That worked!

I had to manually delete `/Library/Caches/Homebrew/asterisk--patch-.diff`, then it gave me the sha256 of the proper diff.  With both patches having their proper respective sha256 each build not applies the proper file.

**Comment by DomT4** [comment]
Yeah. We use the checksum in generating the filename, I believe, so not applying the checksum can end up with naming issues.

**Comment by adilinden** [comment]
Thank you for all the help.  This did answered my question and solved my issue.
