### ISSUE TITLE
Cannot use mysql-python after installing homebrew to home folder

### ISSUE THREAD

**Issue by kodi** [Homebrew/homebrew#46242]
Yesterday i wanted to move my homebrew to home folder. I found that export and restore script.

Then i uninstalled homebrew using official uninstall script.

After that i restored all pqckages, and everything went fine.
Mysql server worked.

After that i tried my django devel setup (recreated virtual env) but it couldnt  connect to remote host
It appears that i had older mysql, and that new restore installed latest mysql. I found the issue on github: https://github.com/Homebrew/homebrew/issues/46055#

Afther that everything goes downhill.
Next thing i tried is to downgrade to mysql56, but mysql-python is looking for `/Users/kodi/homebrew/opt/musql/lib/libmysqlclient.20.dylib`

I thought it might be because i used home folder, so i uninstalled brew, and tried installing again to `/usr/local`

But no luck,  if I install `mysql` i get that ssl error, if i try `mysql56` or `mysql55` mysql-python cant load because it keep looking for `/Users/kodi/homebrew/opt/musql/lib/libmysqlclient.20.dylib` from _mysql.so even though i removed that folder, uninstalled homebrew, and restarted multiple times.

What am i doing wrong. Where did this path / lib got preserved?? How to remove reference to it completely???

**Comment by kodi** [comment]
This is the error im getting when i try to use 55 or 56

    File "/data/env/camellia/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 27, in <module>
        raise ImproperlyConfigured("Error loading MySQLdb module: %s" % e)
    django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module:     dlopen(/data/env/camellia/lib/python2.7/site-packages/_mysql.so, 2): Library not loaded:     /Users/kodi/homebrew/opt/mysql/lib/libmysqlclient.20.dylib
      Referenced from: /data/env/camellia/lib/python2.7/site-packages/_mysql.so
      Reason: image not found

Btw, i forgot to say, `mysql55` and `mysql56` are creating `libmysqlclient.18.dylib` while latest `mysql` package is creating `libmysqlclient.20.dylib` 

When i install latest mysql, it fails because of ssl error:

    django.db.utils.OperationalError: (2026, 'SSL connection error: error:00000001:lib(0):func(0):reason(1)')

But at least it loads, even though _mysql.so is *still* pointing to that old, and non-existing path in `/Users/kodi/homebrew/opt/mysql/lib/libmysqlclient.20.dylib`

Im really stuck i need this to work, and I'm even contemplating format/reinstall of this MBP, because I can't get rid of this error.

My goal is only to get this working: `python -c 'import MySQLdb'` and to NOT use latest `mysql`, because of that SSL error from that other ticket.

**Comment by kodi** [comment]
After 24h of rescue hell, i decided that this is simply not worth it, and installed fresh version of `mysql56` and `python` from brew.

Everything worked as expected.

I have no idea what could I have done to mess it up so badly that this were the only possible way to fix things.

**Comment by tdsmith** [comment]
I think one confusing aspect of this is that, if you were installing mysql-python with pip, pip will attempt to build a compiled wheel of a python package the first time you install it and will continue reusing it until pip's cache is cleared or you install with `--no-binary mysql-python`, which is why you kept seeing a reference to the dylib that no longer existed (because pip was installing a stale mysql-python wheel that it had built earlier against the dylib that used to exist).

Ping @dstufft in case there's a useful place to link this in pypa/pip.

**Comment by tdsmith** [comment]
I don't think this is a Homebrew bug so I'll close this; I'm sorry this was so frustrating. Please let us know if we can help with anything else.
