### ISSUE TITLE
Homebrew deleted the Formulas I was working on!

### ISSUE THREAD

**Issue by tschoonj** [Homebrew/homebrew#46240]
Sometime during the past week I ran the usual `brew update`  and something must have gone horribly wrong: the formulas I was working on are no longer there :cry: 

Let me explain my workflow: I have installed Homebrew the usual way as explained in the docs so I ended up with my installation in /usr/local

However I also cloned Homebrew (and its other taps) in a separate folder in my home folder. It is this folder I use to branch Homebrew and submit PRs. So when I create a new Formula with `brew create`, the new Formula ends up in /usr/local/Library/Formula. When I finish working on this Formula, I copy it to a new branch in my Homebrew fork, commit, push and open a PR. This means that while I am working on a Formula, the file is somewhere in /usr/local and is not indexed by git at all.

Please remove whatever code in brew that is responsible for deleting untracked files: I cannot think of a reason why this would ever be a good idea anyway...

Now I hope theres a copy on my last Time Machine backup of these missing Formulas...

:disappointed:

**Comment by bfontaine** [comment]
We don’t delete untracked files:

```
$ touch /usr/local/Library/Formula/HELLO-DONT-DELETE-ME
$ brew update
Already up-to-date.
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Library/Formula/HELLO-DONT-DELETE-ME

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by bfontaine** [comment]
Maybe try `git stash list` to check that it hasn’t been stashed.

**Comment by mikemcquaid** [comment]
We stash them and they aren't always unstashed.

> Please remove whatever code in brew that is responsible for deleting untracked files: I cannot think of a reason why this would ever be a good idea anyway...

We need to try and ensure a clean `origin/master` for users who don't know how to use Git (this causes us many isssues).

**Comment by tschoonj** [comment]
They are not in the stash. Interestingly the stash contains files that should have been unstashed: files that were indexed (existing Homebrew formulas) for which I submitted a PR.

Mike, I respectfully disagree with this policy involving the unannounced deleting of files. At the very least there should be a warning being shown with a question asking if the user wants to continue with this. 

The idea that Homebrew, or any other piece of software for that matter, could delete my files without my explicit permission is very frightening.

**Comment by mikemcquaid** [comment]
You can read exactly what we do on update: https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/update.rb#L195-L278

You'll note we don't delete any files; we stash them and unstash them and in future we will not be unstashing them by default.

If you submitted a PR with those files: they were committed, not deleted and you should look in `git reflog` to find them.

> The idea that Homebrew, or any other piece of software for that matter, could delete my files without my explicit permission is very frightening.

Almost every piece of software you run on your computer_could_ do this. It seems in this case your problem is not Homebrew but Git. If your files were committed in Git in the last ~30 days they are not lost but will still be in `git reflog`. If your files were not committed Git may have deleted them through some other `reset` or `checkout` operation you've taken.

**Comment by tschoonj** [comment]
AFAIK `git checkout` and `git reset` can't even be used to delete untracked files. Only `git clean` can do that, and I use that command very, very rarely. Something must have happened either way as the stash was not restored.

I agree that it's probably a git issue and I will be make sure to commit my work in the future instead of leaving my files untracked.

**Comment by mikemcquaid** [comment]
> I agree that it's probably a git issue and I will be make sure to commit my work in the future instead of leaving my files untracked.

Thanks and sorry if we didn cause this :+1:
