### ISSUE TITLE
Idea: create a pay-per-build service for non-Mac devs to create/test/dev brews

### ISSUE THREAD

**Issue by hughperkins** [Homebrew/homebrew#46259]
Idea: create a pay-per-build service for non-Mac devs to create/test/dev brews

So, we can just use the exact same technology, push a basic script, see the results, tweak it a bit, repush.

I'm guessing this kind of usage would probably be against current brew TOS?  But if it was pay-per-build, in a separate area, maybe a separate repo, then could be a win-win where you can generate some income, and non-Mac devs can test their builds?  (Not sure if this would be against xcode usage TOS though?  I'm not a lawyer....)

**Comment by dunn** [comment]
Travis CI has OS X images, so you could create a [tap](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md) and tweak our [`.travis.yml`](https://github.com/Homebrew/homebrew-emacs/blob/master/.travis.yml) for your needs.

**Comment by mikemcquaid** [comment]
This is something we might consider in future but aren't currently.

**Comment by hughperkins** [comment]
@dunn: cool, thanks!  Will give that a shot :-)

@mikemcquaid: ok, got it.

**Comment by hughperkins** [comment]
@dunn: whoa, cool. That works.  Awesome! :-)  Thank you :-)
