### ISSUE TITLE
Encfs

### ISSUE THREAD

**Issue by bjacobsGIT** [Homebrew/homebrew#46254]
I ran a brew update and brew upgrade today and afterwards "encfs" no longer woks.  I receive the following error message.

dyld: Symbol not found: __ZN5boost7archive17xml_iarchive_implINS0_12xml_iarchiveEE13load_overrideERNS0_15class_name_typeEi
  Referenced from: /usr/local/Cellar/encfs/1.8.1/lib/libencfs.6.dylib
  Expected in: /usr/local/opt/boost/lib/libboost_serialization-mt.dylib
 in /usr/local/Cellar/encfs/1.8.1/lib/libencfs.6.dylib
Trace/BPT trap: 5

Here is what I have installed:
autoconf 2.69
automake 1.15
boost 1.58.0 1.59.0
brew-cask 0.59.0
encfs 1.8.1
gettext 0.19.6
intltool 0.51.0
libtool 2.4.6
openssl 1.0.2d_1
pkg-config 0.29
rlog 1.4
xz 5.2.2

I was able to use the following workaround until the issue is resolved:
brew switch boost 1.58.0

**Comment by dunn** [comment]
It probably just needs to be re-compiled against the new Boost; switching back to 1.59 and then `brew reinstall -s encfs` should work.

**Comment by bjacobsGIT** [comment]
Thanks, your suggestion of switching back to boost 1.59.0 and then reinstalling encfs using the following command worked.  "brew reinstall -s encfs"
