### ISSUE TITLE
Subversion 1.9 / javahl binding for Eclipse

### ISSUE THREAD

**Issue by gamma** [Homebrew/homebrew#46277]
The current version 1.9.2 of subversion and its javahl binding are incompatible with the existing javahl connectors for eclipse (because there are currently no connectors supporting svn 1.9).

Though this is a bug/missing feature on the eclipse side it is currently not possible to install a homebrew version of subversion that will work with eclipse. I tried the subversion7 bottle which did not install.

It would be great to offer a 1.8 bottle (removed in September) for backward compatibility with the existing javahl connectors.

**Comment by thomschke** [comment]
Eclipse -> Install new software -> http://subclipse.tigris.org/update_1.12.x -> JavaHL Adapter 1.9.2

**Comment by gamma** [comment]
Thank you for helping a blind man ;)

Anyway: the connector is not compatible with subversive as far as I can see. Since you answer is still valid, I'll close this issue. If anyone else runs into this, they should use subclipse instead.
