### ISSUE TITLE
Brew update failure

### ISSUE THREAD

**Issue by apackeer** [Homebrew/homebrew#46276]
Hi,

I get the following when trying to update Homebrew:

```
warning: CRLF will be replaced by LF in Library/Formula/anttweakbar.rb.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in Library/Formula/anttweakbar.rb.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in Library/Formula/anttweakbar.rb.
The file will have its original line endings in your working directory.
error: Your local changes to the following files would be overwritten by merge:
	Library/Formula/anttweakbar.rb
Please, commit your changes or stash them before you can merge.
Aborting
Error: Failure while executing: git stash pop --quiet
```

I've tried:
```
git reset --hard origin/master
brew update
```

and same error occurs.

**Comment by DomT4** [comment]
Any better luck if you `fetch` the latest git commit first?

```bash
git fetch && git reset --hard origin/master
```

**Comment by spottybones** [comment]
This problem keeps coming and going for me despite changing line feed settings and resetting branches. I finally just added:

Library/Formula/anttweakbar.rb binary

to my global gitattributes file (~/.gitattributes) and that appears to have resolved it for me.

**Comment by apackeer** [comment]
I tried setting ~/.gitattributes to:

```
# Automatically normalize line endings for all text-based files
* text=auto

/usr/local/Library/Formula/anttweakbar.rb text eol=crlf
```

and still get the same result.

My core.autocrlf config is set to input
```
git config --global core.autocrlf input
```

Still no joy. I've also tried fetching first as suggested above.

**Comment by DomT4** [comment]
What happens if you just `rm Library/Formula/anttweakbar.rb` inside the `brew --prefix` and then try the fetch/reset dance?

**Comment by shoesforindustry** [comment]
I have to say this also happens to me, same file. I've try all the suggestions but it keeps coming back.

**Comment by chdiza** [comment]
Is that formula's `DATA` block *supposed* to have DOS line endings?  It does have them on my clone, but I have never seen the warning mentioned in this thread.

**Comment by apackeer** [comment]
I've tried deleting and refetching. I've also tried resetting. Still no joy.

**Comment by mikemcquaid** [comment]
@apackeer Try to `git checkout -B --force master origin/master`. If that still fails: can you post the contents of your `~/.gitconfig`? Thanks!

**Comment by apackeer** [comment]
```
[user]
    name = Arden Packeer
	email = ####@####
    editor = /usr/bin/vim

[alias]
        # View the SHA, description, and history graph of the latest 20 commits
        l = log --pretty=oneline -n 20 --graph
        # View the current working tree status using the short format
        s = status -s
        # Show the diff between the latest commit and the current state
        d = !"git diff-index --quiet HEAD -- || clear; git diff --patch-with-stat"
        # `git di $number` shows the diff between the state `$number` revisions ago and the current state
        di = !"d() { git diff --patch-with-stat HEAD~$1; }; git diff-index --quiet HEAD -- || clear; d"
        # Pull in remote changes for the current repository and all its submodules
        p = !"git pull; git submodule foreach git pull origin master"
        # Clone a repository including all submodules
        c = clone --recursive
        # Commit all changes
        ca = !git add -A && git commit -av
        # Switch to a branch, creating it if necessary
        go = checkout -B
        # Show verbose output about tags, branches or remotes
        tags = tag -l
        branches = branch -a
        remotes = remote -v
        # Credit an author on the latest commit
        credit = "!f() { git commit --amend --author \"$1 <$2>\" -C HEAD; }; f"
        # Interactive rebase with the given number of latest commits
        reb = "!r() { git rebase -i HEAD~$1; }; r"
        # Undo a `git push`
        undopush = push -f origin HEAD^:master
        # Amend commit
        amend = commit --amend -C HEAD
        # Status
        s = status

[apply]
        # Detect whitespace errors when applying a patch
        whitespace = fix

[core]
        # Use custom `.gitignore` and `.gitattributes`
        excludesfile = /opt/boxen/config/git/gitignore
        attributesfile = ~/.gitattributes
        # Treat spaces before tabs, lines that are indented with 8 or more spaces, and all kinds of trailing whitespace as an error
        whitespace = space-before-tab,indent-with-non-tab,trailing-space
        editor = /usr/bin/vim
	autocrlf = input

[color]
        # Use colors in Git commands that are capable of colored output when outputting to the terminal
        ui = auto
        interactive = true

[color "branch"]
        current = yellow reverse
        local = yellow
        remote = green

[color "diff"]
        meta = yellow bold
        frag = magenta bold
        old = red bold
        new = green bold

[color "status"]
        added = yellow
        changed = green
        untracked = cyan

[diff]
        tool = opendiff

[github]
        user = apackeer

[merge]
        # Include summaries of merged commits in newly created merge commit messages
        log = true
        tool = opendiff

[push]
    default = simple

# git push by default pushes all branches to the remote, by adding the configuration you tell git to only push the branch you are on
[remote "origin"]
        push = HEAD

# URL shorthands
[url "git@github.com:"]
        insteadOf = "gh:"
        pushInsteadOf = "github:"
        pushInsteadOf = "git://github.com/"
[url "git://github.com/"]
        insteadOf = "github:"
[url "git@gist.github.com:"]
        insteadOf = "gst:"
        pushInsteadOf = "gist:"
        pushInsteadOf = "git://gist.github.com/"
[url "git://gist.github.com/"]
        insteadOf = "gist:"

[credential]
	helper = osxkeychain

[hub]
        protocol = https
[filter "media"]
	required = true
	clean = git media clean %f
	smudge = git media smudge %f
[filter "lfs"]
	clean = git-lfs clean %f
	smudge = git-lfs smudge %f
	required = true
[http]
	sslVerify = false
```

**Comment by mikemcquaid** [comment]
Please run `brew doctor` and paste the output here.

**Comment by mikemcquaid** [comment]
> autocrlf = input

This looks like it could be the problem.

**Comment by mikemcquaid** [comment]
Also can you paste the output you got from `git checkout -B --force master origin/master`

**Comment by shoesforindustry** [comment]
**Begin at the beginning** - OSX 10.11.1 - `brew update` still not working for me...

+ `sudo chown -R $(whoami) /usr/local`
+ `ls -al`
+ `drwxr-xr-x@   26 myusername  admin    884 24 Nov 16:18 local`
+ `brew doctor`
+ `Your system is ready to brew.`

****

+ `brew update`   
`warning: CRLF will be replaced by LF in Library/Formula/anttweakbar.rb.  
The file will have its original line endings in your working directory.  
warning: CRLF will be replaced by LF in Library/Formula/anttweakbar.rb.  
The file will have its original line endings in your working directory.  
warning: CRLF will be replaced by LF in Library/Formula/anttweakbar.rb.  
The file will have its original line endings in your working directory.  
error: Your local changes to the following files would be overwritten by merge:  
Library/Formula/anttweakbar.rb  
Please, commit your changes or stash them before you can merge.  
Aborting  
Error: Failure while executing: git stash pop --quiet`

****

+ `git reset --hard origin/master`  
`HEAD is now at 72c692e audit: only run brew style when on Ruby 2.0.`

+ `brew update`  
*Same as before* - `warning: CRLF will be replaced by LF...`

****

+ `git fetch && git reset --hard origin/master`  
`HEAD is now at 72c692e audit: only run brew style when on Ruby 2.0.`

+ `brew update`  
*Same as before* - `warning: CRLF will be replaced by LF...`

****

+ `git checkout -B --force master origin/master`  
`fatal: Cannot update paths and switch to branch '--force' at the same time.
Did you intend to checkout 'origin/master' which can not be resolved as commit?`  
*I proceeded no further with this option*

****

+ `rm Library/Formula/anttweakbar.rb`  
`brew update`                              
`error: Your local changes to the following files would be overwritten by merge:  
Library/Formula/anttweakbar.rb  
Please, commit your changes or stash them before you can merge.  
Aborting  
Error: Failure while executing: git stash pop --quiet`

**Comment by mikemcquaid** [comment]
Try just `git checkout -B master origin/master` and then `git checkout --force master`. If that still fails: try to remove `autocrlf = input` from your `~/.gitconfig`

**Comment by shoesforindustry** [comment]
+ `git checkout -B master origin/master`  
`M	Library/Formula/anttweakbar.rb  
Branch master set up to track remote branch master from origin.    
Reset branch 'master'    
Your branch is up-to-date with 'origin/master'.`  

****

+ `git checkout --force master`
`Already on 'master'  
Your branch is up-to-date with 'origin/master'.`

+ `brew update`

Same as before - `warning: CRLF will be replaced by LF...`

****

+ Remove autocrlf
  #autocrlf = input

+ `brew update`

Same as before - `warning: CRLF will be replaced by LF...`

**Comment by mikemcquaid** [comment]
Ok, now try `git checkout Library/Formula`

**Comment by shoesforindustry** [comment]
`git checkout Library/Formula`  
` brew update`  
Same as before - `warning: CRLF will be replaced by LF...`

**Comment by shoesforindustry** [comment]
Sorry Mike, I was absent mindedly typing responses to your queries, whilst doing something else and completely forgot to say thank you for taking the time to try and resolve this problem, it is much appreciated!

**Comment by mikemcquaid** [comment]
No worries, thanks for the kind words! Ok, try to `rm -rf Library/Formula` and then `git checkout Library/Formula`

**Comment by shoesforindustry** [comment]
Many thanks Mike, that seemed to do it, not sure why though? 

`rm -rf Library/Formula`
`git checkout Library/Formula`

I had fixed this issue once before, but cannot remember how, but sadly it came back. My fingers are crossed it has gone for good, I rely on brew a lot these days!

**Comment by mikemcquaid** [comment]
Glad it's working! My guess might be a text editor with a weird line ending setting that's made it get upset.

**Comment by UniqMartin** [comment]
@mikemcquaid The formula `anttweakbar.rb` really has mixed line endings as it exists right now in the repository, so I'm afraid most people with `core.safecrlf = input` set globally will have this issue sooner or later. I think we could either get rid of the mixed line endings by externalizing the offending embedded patch or by enforcing `core.safecrlf = false` for the local Homebrew repository, as is already done in [`git_init_if_necessary`](https://github.com/Homebrew/homebrew/blob/366e39ed3363ab3568f4031c31570761be61efb8/Library/Homebrew/cmd/update.rb#L135-L143) (it must be there for a reason). Not sure at all what the best solution is …

**Comment by apackeer** [comment]
The remove and then checkout of the Library/Formula worked for me also. 

I agree with @UniqMartin that there really should be a fix other than rechecking out as this happens periodically with my installs.

**Comment by UniqMartin** [comment]
@apackeer You could run `git config core.autocrlf false` inside your Homebrew repository to overwrite your global/user setting (for this repository only). This should permanently solve the issue for you. But as you said, we probably need to figure out how to deal with this issue in Homebrew in general, as it seems you are not be the only one affected.

**Comment by DomT4** [comment]
Going for the externalise the patch option at least as an immediate workaround. I strongly dislike inline patches as-is because they break often; various text editors will attempt to "correct" the whitespacing by default as well, which causes issues for contributors.
