### ISSUE TITLE
been asked to report it Lol

### ISSUE THREAD

**Issue by david199562** [Homebrew/homebrew#46274]
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-dupes'...
remote: Counting objects: 2000, done.
remote: Total 2000 (delta 0), reused 0 (delta 0), pack-reused 2000
Receiving objects: 100% (2000/2000), 412.30 KiB | 283.00 KiB/s, done.
Resolving deltas: 100% (1137/1137), done.
Checking connectivity... done.
Warning: Could not create link for homebrew/dupes/xar, as it
conflicts with Homebrew/homebrew/xar. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/dupes/xar
Tapped 38 formulae
Error: undefined method `desc' for Formulary::Formulae::Zlib:Class
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-dupes/zlib.rb:2:in `<class:Zlib>'
/usr/local/Library/Taps/homebrew/homebrew-dupes/zlib.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:177:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:42:in `install'
/usr/local/Library/brew.rb:135:in `<main>'

**Comment by dunn** [comment]
Has it been a while since you ran `brew update`? If you do, does that error persist?

**Comment by david199562** [comment]
Yes, problem solved sorry for didn't check but when i was doing brew install scipy, it runs like forever when doing "making bootstrap" and laptop became super hot... is it normal?

**Comment by DomT4** [comment]
If it's a heavy compile process, your computer will heat up considerably, aye. Compiling is one of the most CPU-intensive things you can do.

I suspect what it's actually building there is `gcc`, which provides the `fortran` dep that [scipy](https://github.com/Homebrew/homebrew-python/blob/master/scipy.rb#L19) needs.
