### ISSUE TITLE
HOMEBREW_PREFIX ignored/not respected. hard-coded paths ensue.

### ISSUE THREAD

**Issue by mralexgray** [Homebrew/homebrew#46275]
In the same vein as [Investigate making prefix/cellar configurable via environment variables](https://github.com/Homebrew/homebrew/issues/19333)... I urge the _powers-that-be_ to reconsider the current setup - which results in _needlessly hard-coded paths_ during linking/compilation.

Example...

````
mv /usr/local /Volumes/NoneYa
ln -s /Volumes/NoneYa/local /usr
export HOMEBREW_PREFIX=/usr/local # will be ignored
brew reinstall some-formula
==> Reinstalling some-formula
==> Downloading http://ftp.godknowswhere.org/some-formula.tar.gz
Already downloaded: /Library/Caches/Homebrew/some-formula.tar.gz
==> ./configure --prefix=/Volumes/NoneYa/local/Cellar/some-formula/ --mandir=/Volumes/NoneYa/local/Cellar/some-formula/2 
```

In this totally mundane and plausible example, I have now compiled, linked... and can enjoy `some-formula`.  That is, until, ***gasp***.. I want to _change the location_ of where I ACTUALLY keep the contents of `/usr/local`. Even though I TRIED to tell `homebrew`..  

> "Hey listen, I know `/usr/local` isn't EXACTLY where you think it's going to be... but lets just _pretend_.  I will ***make sure*** you can *always* find it at `/usr/local` - that's why I set `$HOMEBREW_PREFIX` in my `.profile`, OK?"

I know you guys do some clever ruby hocus-pocus to make sure you are installing to the __actual location__ of whatever is sitting at `/usr/local`, but why?  Just follow the symlinks according to what we want, and by extension - are responsible for ensuring exists - per the HOMEBREW_PREFIX.

Or maybe there is some way that I am unaware to magically recompile every formula when the physical location of our prefix changes?  

`for x in $(brew list); { brew unlink $x && brew link $x; }`

But even if there is... why are we hardcoding paths at compile/install/link time that can just as easily be more configurable/flexible?

**Comment by xu-cheng** [comment]
Sorry but we don't support such use case. 

> why are we hardcoding paths at compile/install/link time that can just as easily be more configurable/flexible?

Majority of package hardcode prefix path inside their binary files. So it's not configurable/flexible.

As far as I understand, you want to use `/usr/local/` as prefix, but use a different Volume to store actually files (To save space?). If you insist to do this, you may want to just `mount` the volume to `/usr/local/`. But be aware, such configuration is completely unsupported by us.

**Comment by mralexgray** [comment]
But why?  Is there no room for improvement here?  It's not a race to close issues... it's a battle to improve the software.

**Comment by mikemcquaid** [comment]
@mralexgray We do not consider this an issue and will not be working on fixing it so we've closed the issue. This feature request will make it harder to debug Homebrew issues so we do not wish to work on it.
