### ISSUE TITLE
Not able to install HomeBrew : Failed to connect to raw.githubusercontent.com port 443: Network is unreachable

### ISSUE THREAD

**Issue by Chetan-A-G** [Homebrew/homebrew#46280]
I have Xcode installed on my machine and able to open Git url on browser but when i run the command to install Home brew getting network unreachable error. Even tried setting the proxy url by using below command. Still not working. Pls help to resolve this.

$ HTTP_PROXY=http://proxy.mycompany:80
$ git config --global http.proxy $HTTP_PROXY

Error Message:
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Network is unreachable

**Comment by rakkesh** [comment]
`cURL` has failed as it could not connect to `github.com` on port 443, try setting a working HTTPS proxy. Assuming the company proxy supports `https`,

`export HTTPS_PROXY=https://<proxy.mycompany>:<port>`

Set a working proxy for `git`,

`$ git config --global https.proxy https://<proxy.mycompany>:<port>`

And then verify,
`$ git config --global --get https.proxy`

**Comment by mikemcquaid** [comment]
I'm afraid there's nothing we can really do if you can't connect to GitHub via `curl`. That's something you'll need to fix yourself, sorry!

**Comment by Chetan-A-G** [comment]
Thanks Rakesh.. It worked.
