### ISSUE TITLE
way to track number of bottle downloads?

### ISSUE THREAD

**Issue by zbeekman** [Homebrew/homebrew#46289]
For open source software projects that rely on research funding, it is nice to be able to estimate the size of the user base. Is there any means of getting a sense of how many downloads/installations have happened for a given Formula? I.E. when installing a bottled Formula, do the Homebrew servers that host the bottles track the number of times each bottle is downloaded?

**Comment by DomT4** [comment]
Bintray track bottle download stats. We have made some of those numbers available but are trying to find a reasonable way to enable that public statistic sharing on a wider basis without manually clicking through thousands of packages on the web UI :smile:.

Happy to make packages public on request till we work out a wider solution.

**Comment by zbeekman** [comment]
Sorry, but to clarify, what/where is bintray? And do we just submit a request to you here to make the package download info public?

**Comment by DomT4** [comment]
Bintray is a CDN who very kindly host our binary packages (bottles). You'd access the stats for a package that had them made public with the following style of URL:

https://bintray.com/homebrew/bottles/a2ps/view#statistics

Replacing `a2ps` with the desired package.

> And do we just submit a request to you here to make the package download info public?

Feel free.

**Comment by zbeekman** [comment]
Great! I'm going to try to whip up a new formula for @sourceryinstitute's [opencoarrays](https://github.com/sourceryinstitute/opencoarrays/issues/22#issuecomment-159009469) and if I'm successful and it's accepted, I think we'll want to make public the CDN's statistics.

I also maintain a number of other Fortran related Formulae, some of which I need to update, and will be contacting their primary author/maintainer to see if they want to be able to gather HomeBrew stats...

Thanks @DomT4

**Comment by DomT4** [comment]
Note that we only publish bottles and have stats for bottles published by Homebrew; formulae in unofficial taps aren't bottled by us. If the other formulae you're interested in are based in Homebrew or one of our official taps and have bottles, let us know and we'll make those stats public. Thanks!

**Comment by zbeekman** [comment]
yup, got it, thanks!
