### ISSUE TITLE
Add pkg-config as dependency to rust

### ISSUE THREAD

**Issue by Barlog-M** [Homebrew/homebrew#46284]
Please, add `pkg-config` as dependency to `rust`, because `pkg-config` need to build projects with `cargo`.

**Comment by bfontaine** [comment]
Could you please open a pull-request? This should help and I’m happy to answer any question you might have: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

**Comment by rakkesh** [comment]
`pkg-config` is already a build dependency for `rust` - https://github.com/Homebrew/homebrew/blob/9b85e01854ee9ee57e418c1865f77227cc8201f8/Library/Formula/rust.rb#L37.

**Comment by bfontaine** [comment]
@rakkesh I’m assuming @Barlog-M wants it as a runtime dependency. If you install `rust` from a bottle `pkg-config` won’t be installed.

**Comment by rakkesh** [comment]
Ah, got it. @Barlog-M replace line 37 in the formula,
 `depends_on "pkg-config" => :build`
with
`depends_on "pkg-config"`

**Comment by DomT4** [comment]
Not quite.

`depends_on "pkg-config" => :run`

**Comment by bfontaine** [comment]
@DomT4 It’s needed for both `:build` and `:run`; so @rakkesh should be right here. No?

**Comment by DomT4** [comment]
`depends_on "pkg-config"` would break our audit:

```
 * pkg-config dependency should be
  depends_on "pkg-config" => :build
Or if it is indeed a runtime dependency
  depends_on "pkg-config" => :run
```

**Comment by DomT4** [comment]
As far as I know, `:run` deps that aren't special dependencies should be available at build time as well?

**Comment by DomT4** [comment]
* `brew rm pkg-config`
* Change `depends_on "pkg-config" => :build` to `depends_on "pkg-config" => :run` in `sstp-client`.

```
~> brew install sstp-client -s -v
==> Installing dependencies for sstp-client: pkg-config
==> Installing sstp-client dependency: pkg-config
...

checking for pkg-config... /usr/local/opt/pkg-config/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking event.h usability... yes
checking event.h presence... yes
checking for event.h... yes
checking for main in -levent... yes
checking for event_init in -levent... yes
checking for pkg-config... /usr/local/opt/pkg-config/bin/pkg-config
checking whether compiling and linking against OpenSSL works... yes
```

Seems to work.

**Comment by bfontaine** [comment]
Thanks @DomT4 :smile:

**Comment by DomT4** [comment]
No worries! :speak_no_evil:
