### ISSUE TITLE
Dynamic Version

### ISSUE THREAD

**Issue by jcampbell05** [Homebrew/homebrew#46290]
Some tools I would love to wrap into homebrew i.e RVM or Composer but I would like to dynamically get the version or make it a transient installation. 

As I find it annoying to have to find the command to install or update these tools. It would be awesome if I could just do `brew update rvm` and it will get the latest version without the formula having to be updated.

**Comment by bfontaine** [comment]
We don’t support tools that update themselves; you always have to change a formula to have a new version (except for `HEAD`-only formulae). You could use Bash aliases, e.g. `alias update_rvm="..."` or a function:

```sh
update() {
  case $1 in
    rvm)
      rvm update ;;
    composer)
      composer update ;;
    # etc
  esac
}
```

I use a similar tool called [up](https://github.com/bfontaine/up) for that.
