### ISSUE TITLE
Make public CDN stats for JSON-Fortran

### ISSUE THREAD

**Issue by zbeekman** [Homebrew/homebrew#46293]
Hi, I was talking with @DomT4 earlier and he mentioned that, upon request, the bottle download statistics for certain projects can be made publicly accessible. Can you please make the statistics for JSON-Fortran accessible? Thanks

CC: @jacobwilliams

**Comment by DomT4** [comment]
Done.

Tiny disclaimer: Packages that don't yet have El Capitan bottles will likely have their stats artificially dragged in a downwards direction as people upgrade to the newer OS X versions and end up building from source due to lack of bottle.
