### ISSUE TITLE
Python3 not using brew installed sqlite

### ISSUE THREAD

**Issue by rogeriomarques** [Homebrew/homebrew#46303]
I've installed both sqlite and python3 using homebrew, in that order.

When I `import sqlite3`, the interpreter uses the system supplied sqlite and not the new one. I've searched for hours but didn't find a solution.

Could someone shine a little light?

**Comment by mistydemeo** [comment]
Just to check, how did you determine it was built against the wrong sqlite?

**Comment by rogeriomarques** [comment]
Not sure this is the right way...

`>>> import sqlite3`
`>>> sqlite3.version_info`
`(2, 6, 0)`

**Comment by rogeriomarques** [comment]
My bad !!!

I should have used `sqlite3.sqlite_version`and not `sqlite3.version_info`. 

```
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.9.2'
````

Everything working perfectly. Thanks anyway.

**Comment by mistydemeo** [comment]
No problem!
