### ISSUE TITLE
Request for addition of a feature/command to list all installed formulae

### ISSUE THREAD

**Issue by technodude458** [Homebrew/homebrew#46327]
Is this a thing that can be done either through a new formula or a new command for homebrew itself.  Apologies for posting this here I wasn't sure where to post it I'm kind of new to actually commenting and posting on GitHub

**Comment by mistydemeo** [comment]
This is already possible! You can do this via the `brew list` command.

Please let us know if there's anything else you need help with.

**Comment by technodude458** [comment]
I attempted this and got "Error: No such file or directory - ls" is there a possible bug or error causing this problem or am I just doing it wrong?

**Comment by mistydemeo** [comment]
Do you have a `/bin/ls` on your system?

**Comment by technodude458** [comment]
I do but not in the home-brew bin in the central bin basically i have one at /bin but not /usr/bin which is the path my homebrew is directed to

**Comment by mistydemeo** [comment]
What's your `PATH`? Is `/bin` in your PATH?

**Comment by technodude458** [comment]
well when i do "echo $PATH" i get "/usr/local/bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/bin:" but in my .bash_profile file i have it set as well i'll just upload a text version of the file it'll be easier to show than it would be to tell
[my.bash_profile file.docx](https://github.com/Homebrew/homebrew/files/44370/my.bash_profile.file.docx)

**Comment by technodude458** [comment]
Also when i run brew doctor everything checks out and there are no path warnings also i just gave my profile full read & write access across all invisible files and folders related to this so I'm going to run some tests and see what happens but as of typing this the problem still persists

**Comment by UniqMartin** [comment]
Your PATH indeed does not contain `/bin`, so that's the cause of the problem. The root cause of the problem, it seems, is that multiple tools automatically changed your `.bash_profile` and managed to mess it up pretty badly (including omitting the standard path `/bin`). Most of the lines in this file are redundant and some are plain wrong. You might want to recreate this file from scratch. Do you know how to do that?

By the way, there's no need to create a Word document to show us a plain text file. Please just copy & paste it here or upload as a plain text file. Pasting it here for the benefit of others:

```
# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

# Setting PATH for Python 3.4
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.4/bin:${PATH}"
export PATH
export PATH="/usr/bin/:$PATH"
export PATH="/usr/bin/:$PATH"
export PATH="/usr/bin/:$PATH"
export PATH="/usr/bin/:$PATH"
export PATH="/usr/bin/:$PATH"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
export PATH=/usr/bin:$PATH
export PATH=/usr/bin:$PATH
export PATH=/usr/bin:$PATH
export PATH=/usr/bin:$HOMEBREW
export PATH=/usr/bin:$HOMEBREW

# Setting PATH for Python 3.5
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:${PATH}"
export PATH

# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function
```

**Comment by UniqMartin** [comment]
Also `brew doctor` currently doesn't check if you have the standard directories in PATH. It only checks that Homebrew's `bin` directory (usually `/usr/local/bin`) is in PATH, so that's why it isn't showing any warnings for you.

**Comment by DomT4** [comment]
We "fix" the `$PATH` during [compiles](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/extend/ENV/super.rb#L122), which somewhat negates the need for us to be shouty about the user `$PATH` having issues.

Maybe we should look again at the idea of a broader `doctor` check though.

**Comment by technodude458** [comment]
I do not know how to re-create it from scratch and i had to screw with this file just to get homebrew to work at all so I'm kinda scared to make a change

**Comment by UniqMartin** [comment]
Here's an example, that will keep the standard paths intact and also prefix all the paths that you have in your file right now. Replace your `.bash_profile` with the following lines (make a backup just in case):

```shell
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:$PATH" # Add Python 2.7 to PATH
PATH="/Library/Frameworks/Python.framework/Versions/3.4/bin:$PATH" # Add Python 3.4 to PATH
PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:$PATH" # Add Python 3.5 to PATH
export PATH # Export PATH
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function
```

You can safely remove any (or all) of the first three lines in case you no longer have the respective Python version installed or don't need it in your PATH. Please give it a try.

**Comment by technodude458** [comment]
thanks I'm about to test it

**Comment by technodude458** [comment]
i put that in and now i get "Warning: /usr/bin occurs before /usr/local/bin
This means that system-provided programs will be used instead of those
provided by Homebrew. The following tools exist at both paths:
    git
    git-cvsserver
    git-receive-pack
    git-shell
    git-upload-archive
    git-upload-pack

Consider setting your PATH so that /usr/local/bin
occurs before /usr/bin. Here is a one-liner:
    echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bash_profile" the new bash file you told me to make should read like this "export PATH # Export PATH
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function" right?

**Comment by technodude458** [comment]
wow this also indirectly fixed my RVM problem everything I've tested works so far

**Comment by UniqMartin** [comment]
I'm glad to hear this. :smile:
