### ISSUE TITLE
wine: Some programs crash when switching desktop screens

### ISSUE THREAD

**Issue by sneakernets** [Homebrew/homebrew#46338]
Since Wine 1.7.55_1, xmplay (http://www.un4seen.com/) has become unresponsive if I start the program and switch to another desktop screen (using control + arrow keys). I have to end the program manually via terminal or force quit in the dock.

Steps to reproduce:
1. Have 1.7.55_1 or higher of Wine.
2. Start Xmplay and play any file.
3. Switch to another desktop screen and then back.
4. Xmplay should hang.

I've been using 1.7.54_1 without issue, so I'm locked into that version until this can be resolved. I have no crash information, unfortunately.

**Comment by mikemcquaid** [comment]
This sounds like a Wine rather than Homebrew issue. Can you report it to them?

**Comment by sneakernets** [comment]
I'll see what I can do. Their bug reporting tool has always been user hostile, though...

**Comment by mikemcquaid** [comment]
Sure but we can't fix your issue :wink:

**Comment by sneakernets** [comment]
I'm leaving them a message now.

**Comment by mikemcquaid** [comment]
@sneakernets Thanks!

**Comment by sneakernets** [comment]
I reported the bug here - https://bugs.winehq.org/show_bug.cgi?id=39705

And it has been fixed!
