### ISSUE TITLE
embarresed newbie...

### ISSUE THREAD

**Issue by ted12345** [Homebrew/homebrew#46335]
I'm in a world that is unknown.. eg: terminal
I've done my best to install this homebrew
I copy/pasted the suggested line into terminal.
I put in my password. It seemed to install it. Was not entirly sure as all this 'code' is jibberish to me. 
Then I closed terminal.
Now when I go back to Firefox (I'm on a new mac with up to date OS) to try and use VideoHelper to download the highest res video requiring 'ADP' I'm still told... "This operation needs to have a converter installed on your system to aggregate the video and audio streams."
What gives? Do I need a degree in computer programming to install this thing?

**Comment by mistydemeo** [comment]
The instructions you followed installed Homebrew; you can then use Homebrew to install the converter that VideoHelper asked for. Try running this in your terminal:

brew install libav

Does it work after that?

**Comment by ted12345** [comment]
Thanks for your reply,

When I type in 'brew install libav'
Terminal says:

-bash: brew: command not found

**Comment by mikemcquaid** [comment]
@ted12345 I'd suggest probably using another tool instead of VideoHelper; Homebrew is mostly designed for use by developers and people who are already familiar with the Terminal. Sorry!
