### ISSUE TITLE
Add gnu spell (ispell wrapper)

### ISSUE THREAD

**Issue by andreineculau** [Homebrew/homebrew#46334]
http://directory.fsf.org/wiki/Spell

**Comment by bfontaine** [comment]
Could you open a pull-request? This should help and I’m happy to answer any question you might have:
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

**Comment by mikemcquaid** [comment]
Closing as we don't really do requests.
