### ISSUE TITLE
Elasticsearch formula needs updating to 2.1

### ISSUE THREAD

**Issue by twigbranch** [Homebrew/homebrew#46343]
Elasticsearch formula needs updating to 2.1.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by twigbranch** [comment]
2.0.1 was also released.
https://www.elastic.co/blog/elasticsearch-2-1-0-and-2-0-1-released

Haven't done a pull request for this yet, so may take some time. Will try. If someone beats me too it, please go ahead.
