### ISSUE TITLE
pip not runnable from python 2.7.10 package

### ISSUE THREAD

**Issue by rgoldberg** [Homebrew/homebrew#46342]
The python 2.7.10 package says it installs pip, but pip isn't found in my path, and I can't find the file to run pip on my file system.

How can I get pip working?

Also, should I use the brew-pip package at all?

**Comment by mikemcquaid** [comment]
I see it in `/usr/local/bin/pip`. Can you try to `brew reinstall python` and follow the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by rgoldberg** [comment]
This time around, I got a file permissions error that I didn't see before, so fixing that fixed everything.

Thanks for instructions.
