### ISSUE TITLE
Postgis library not loaded error

### ISSUE THREAD

**Issue by evanzummeren** [Homebrew/homebrew#46358]
My postgis doesn't seem to work anymore. I haven't used it in a while, and I recently did brew update and a xcode update, so that might be the reason. Whenever I try to initialize Postgis (create extension postgis) I am getting this error:

```
ERROR:  could not load library "/usr/local/Cellar/postgresql/9.4.1/lib/postgis-2.1.so": dlopen(/usr/local/Cellar/postgresql/9.4.1/lib/postgis-2.1.so, 10): Library not loaded: /usr/local/lib/libproj.0.dylib
  Referenced from: /usr/local/Cellar/postgresql/9.4.1/lib/postgis-2.1.so
  Reason: image not found
```

I did ```brew uninstall postgis``` and installed it again with a ```build-from-source``` flag, I did the same for proj. The build goes fine, but I keep getting the same error.

Everything is up to date. The brew doctor report can be found at: https://gist.github.com/evanzummeren/b956b96fd2a733afc762

For what it's worth, my brew config: https://gist.github.com/evanzummeren/387dc1d121b71d14e94f

**Comment by mikemcquaid** [comment]
Try to `brew update; brew reinstall postgresql; brew reinstall postgis`.

**Comment by evanzummeren** [comment]
Thanks.  It was indeed as simple as reinstalling postgresql. A bit stupid I didn't think about it the first time.

**Comment by mikemcquaid** [comment]
Great!
