### ISSUE TITLE
Brew install ansible issue

### ISSUE THREAD

**Issue by scheung38** [Homebrew/homebrew#46353]
Issue with installation of ansible using brew
```
$brew install ansible
```
and
```
/usr/local/etc/ansible
```
Folder does not get generated as expected and I currently need to use pip instead?

http://superuser.com/questions/975319/can-t-find-the-config-file-in-etc-ansible-on-mac-os-x/1005362#1005362

**Comment by bfontaine** [comment]
Please post the output of `brew gist-logs ansible`.

**Comment by scheung38** [comment]
```
$ brew gist-logs ansible
Error: No logs.
```

**Comment by mikemcquaid** [comment]
What is your actual issue; that we don't install a configuration file by default?

**Comment by scheung38** [comment]
I thought these folders are automatically created? Problem is that these folders are not generated as expected

**Comment by mikemcquaid** [comment]
Ok, so you'd like `/usr/local/etc/ansible` to be automatically created?

**Comment by scheung38** [comment]
According to the documentation that's what is supposed to happen correct?

**Comment by mikemcquaid** [comment]
Which documentation?

**Comment by tdsmith** [comment]
Please let us know if we can help with anything.
