### ISSUE TITLE
Brew ansible and passlib

### ISSUE THREAD

**Issue by KIVagant** [Homebrew/homebrew#46354]
Hello to all.

I apologize in advance for maybe not clever question. 

I found [this Pull Request](https://github.com/Homebrew/homebrew/pull/42397), that should add passlib dependency to homebrew ansible formula.
But for me, I still have trouble with ansible htpasswd-module, that required python passlib.

I have:
- OS X 10.11.1 El Capitan
- ```brew --version: 0.9.5 (git revision 8f39d; last commit 2015-11-25)```

I run:
- ```brew update; brew upgrade --all```
- ```ansible-playbook --version: ansible-playbook 1.9.4; configured module search path = None```
- then I run ansible role with htpasswd module and I got this: ```msg: This module requires the passlib Python library```

Why ansible still does not sees this library? Maybe I need to do something with ansible configuration?

Thank you for answers and especially for homebrew utility.

**Comment by tdsmith** [comment]
It looks like we distribute ansible with passlib. Please note that passlib must be installed on the target machine as well. Let me know if you have any questions and we can reopen this. Thanks!
