### ISSUE TITLE
php7

### ISSUE THREAD

**Issue by davideradice** [Homebrew/homebrew#46355]
With 
```
$ brew update && brew upgrade && brew doctor && brew install php70
```

I get 

```
homebrew/php/php70 7.0.0-rc.3_2 already installed
```

And in phpinfo I see 
```
PHP Version 7.0.0RC3.
```

How can I install PHP 7 RC7?
http://php.net/archive/2015.php#id2015-11-12-1

**Comment by mikemcquaid** [comment]
Please report this issue to https://github.com/Homebrew/homebrew-php/issues/new instead.
