### ISSUE TITLE
Issue with brew in OSX El Capitan

### ISSUE THREAD

**Issue by cksachdev** [Homebrew/homebrew#46366]
I updated osx from Mavericks to El Capitan and tried brew update. It gave the following error:
```
warning: CRLF will be replaced by LF in Library/Formula/anttweakbar.rb.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in Library/Formula/anttweakbar.rb.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in Library/Formula/anttweakbar.rb.
The file will have its original line endings in your working directory.
error: Your local changes to the following files would be overwritten by merge:
	Library/Formula/anttweakbar.rb
Please, commit your changes or stash them before you can merge.
Aborting
Error: Failure while executing: git stash pop --quiet
```

I tried various git commands. Tried to stash, deleted anttweakbar, took update, but issue wasn't getting fixed. Then I tried the following command in `brew --prefix` directory:
```
sudo chmod -R 755 ./* && git checkout -- . && git clean -dfx
```
And it removed all the files. Then I uninstalled brew and installed it again using ruby command mentioned on the landing page.

Tried brew update again and still facing the same issue. Is uninstall not removing all the files of brew? or this issue is not related to homebrew at all?

**Comment by DomT4** [comment]
Check out https://github.com/Homebrew/homebrew/issues/46276. Looks like the same issue.

**Comment by technodude458** [comment]
I had a similar issue on mavericks you'll need to manually remove the files at least thats what i did and it worked
