### ISSUE TITLE
Aliases/npm issue

### ISSUE THREAD

**Issue by ryan10132** [Homebrew/homebrew#46360]
Hi,

I'm trying to install npm, I have installed other things, for example node. Brew doctor tells me I'm ready to brew

    rmcnamara-mbp:Aliases rmcnamara$ brew install npm
    Error: /usr/local/Library/Aliases/npm:1: syntax error, unexpected ..
    ../Formula/node.rb
      ^
    /usr/local/Library/Aliases/npm:1: unknown regexp option - d
    Please report this bug:
        https://git.io/brew-troubleshooting
    /usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
    /usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
    /usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
    /usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
    /usr/local/Library/Homebrew/formulary.rb:74:in `klass'
    /usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
    /usr/local/Library/Homebrew/formulary.rb:205:in `factory'
    /usr/local/Library/Homebrew/extend/ARGV.rb:18:in `block in formulae'
    /usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
    /usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
    /usr/local/Library/Homebrew/cmd/install.rb:48:in `install'
    /usr/local/Library/brew.rb:146:in `<main>'

sure enough,

    rmcnamara-mbp:Aliases rmcnamara$ ls -l /usr/local/Library/Aliases/npm
    -rw-r--r--  1 rmcnamara  admin  18 Nov 25 09:17 /usr/local/Library/Aliases/npm
    rmcnamara-mbp:Aliases rmcnamara$ cat /usr/local/Library/Aliases/npm
    ../Formula/node.rb

I believe that this file should be a sym link to the path pointed at by its contents. I'm not sure how I got into this state, I did have some installs fail in the linking step, but I believe I then relinked after fixing my permissioning issues.

**Comment by DomT4** [comment]
Try:

```
rm /usr/local/Library/Aliases/npm && git fetch && git reset --hard origin/master
```
Inside your `brew --prefix`.

Note: If you have other changes to your Homebrew repo, that command will overwrite them.

**Comment by ryan10132** [comment]
No luck, exact same error.
Also that didn't change the file contents of npm, looking here : 

https://github.com/Homebrew/homebrew/blob/master/Library/Aliases/npm

This actually seems correct. Not sure why whatever it is is interpreting this file as a ruby file. Is there some setup step that converts the files to sym links that may have failed? All my files in /usr/local/Library/Aliases do this, which I suspect will be problematic.

**Comment by DomT4** [comment]
Yes, Github shows symlinks as `../Formula/node.rb` but locally they should actually *be* functional symlinks rather than files.

We've seen this issue before, but I can't remember how it was resolved. Let me root around our old issues a bit.

**Comment by DomT4** [comment]
Any chance you're passing [this](https://github.com/Homebrew/homebrew/issues/36706#issuecomment-73775085) in your `.gitconfig`?

**Comment by ryan10132** [comment]
Yes! Thanks a bunch that was exactly it
