### ISSUE TITLE
boneyard arabica

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew#46376]
Nothing depends on it. Doesn't build against Xcode 7, nor does it build against GCC 5 or GCC-4.9, which makes me suspect it has been dead for a while and nobody has noticed.

Will file a PR in the morning.

**Comment by bfontaine** [comment]
We did notice it, see #41266 and #42369. I don’t know for @apjanke but I personally didn’t intent to use it; it was for `homebrew/command-not-found`.

**Comment by apjanke** [comment]
I don't intend to use it. That issue report was just from doing an automated installation test of all formulae. Boneyarding sounds fine.

**Comment by mikemcquaid** [comment]
:+1:

**Comment by mistydemeo** [comment]
FWIW this appears to still be in relatively active development, had commits on Github last year (including some that fix the issues that are preventing it from building): https://github.com/jezhiggins/arabica

**Comment by DomT4** [comment]
@bfontaine @apjanke Apologies - I meant that users hadn't noticed, rather than us. We notice a bunch of things that most users never stumble into heh.

@mistydemeo If you're keen to keep it I can try building the head and see whether that works, and then either patch or ask for a new release.

**Comment by mistydemeo** [comment]
HEAD does build. Looks like we've been requesting a new release since 2014 (jezhiggins/arabica#11), so if we don't get a response I don't think a new release is going to happen.

**Comment by DomT4** [comment]
Alright, I'll sit on this for a few days then and see if the latest ping upstream gets a response. Thanks Misty.
