### ISSUE TITLE
Is there an option to forbid installing formulas which don't have sha256?

### ISSUE THREAD

**Issue by magicgoose** [Homebrew/homebrew#46381]
If not, could you implement it?

(In other words, I just want to be able to prevent accidentally running _completely arbitrary_ code when something has to be downloaded over plain http, but simply disabling plain http is not an option, because there are lots of stuff hosted on sourceforge, for example)

And there are relatively few formulas which do not support versioning (and consequently don't have sha256), so I probably don't mind "losing" them — I won't install them anyway, but checking each formula by hand is tedious.

**Comment by mikemcquaid** [comment]
> And there are relatively few formulas which do not support versioning (and consequently don't have sha256), so I probably don't mind "losing" them — I won't install them anyway, but checking each formula by hand is tedious.

Which are these, out of interest? You mean outside Homebrew core?

**Comment by magicgoose** [comment]
I don't remember exactly. Probably some from Cask.

**Comment by mikemcquaid** [comment]
We're a separate project from Homebrew Cask so we're unable to make changes that affect them like that.

**Comment by DomT4** [comment]
As far as I'm aware there are no SHA1 using Casks in the main Caskroom these days.
