### ISSUE TITLE
Error: invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by alessap** [Homebrew/homebrew#46391]
Hi all,

I run brew doctor and I got this error:

$ brew doctor
Error: invalid byte sequence in US-ASCII
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:45:in `=~'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:45:in `chop_basename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:341:in `plus'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:334:in `+'
/usr/local/Library/Homebrew/extend/pathname.rb:296:in `resolved_path_exists?'
/usr/local/Library/Homebrew/cmd/doctor.rb:232:in `block (2 levels) in check_for_broken_symlinks'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:546:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:546:in `find'
/usr/local/Library/Homebrew/cmd/doctor.rb:231:in `block in check_for_broken_symlinks'
/usr/local/Library/Homebrew/cmd/doctor.rb:229:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:229:in `check_for_broken_symlinks'
/usr/local/Library/Homebrew/cmd/doctor.rb:1314:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1312:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1312:in `doctor'
/usr/local/Library/brew.rb:146:in `<main>'

Is it something I should fix? I do not seem to have any problems but I do not know how to get rid of this.

**Comment by bfontaine** [comment]
Do the solutions on #44744 work?

**Comment by alessap** [comment]
Thank you very much! It now works!

**Comment by bfontaine** [comment]
Great! :smile:
