### ISSUE TITLE
Mysql 5.7.9 updated but broken

### ISSUE THREAD

**Issue by loranger** [Homebrew/homebrew#46393]
Since mysql has been updated, I can't connect using SequelPro anymore. 
My local dev websites (using PHP PDO) are locked out too.
Unfortunately, that doesn't throw any exception, but try to connect and... timeout.
The only remaining solution is to connect using the mysql client which works perfectly, but is a little useless in order to develop websites.
Mysql is installed for years now, and I brew upgrade almost every day.

It appears `mysql.server stop` does not work either :
It tries to shut mysql down, and says it succeed but I still can log in mysql server with the mysql client.
`launchctl unload`works fine, but the shortes command was definitely more convenient.

**Comment by bfontaine** [comment]
Could you please give more information about your setup? E.g. what does `brew doctor` say?
Is your issue related to #46055?

**Comment by mikemcquaid** [comment]
> I still can log in mysql server with the mysql client.

It sounds like it's SequelPro that's got a problem then rather than MySQL or Homebrew.

**Comment by loranger** [comment]
Brew doctor does not says anything but `Your system is ready to brew`, that's the reason why I did not post anything (`brew gist-logs mysql` says there is no logs).
I also search for similar issues, but I didn't find my exact problem : I can log me in using the root user or my common user, using the mysql client and I have no SSL issue. I just can't stop the server using the `mysql.server stop`, and I can't connect to the server but with the official client.

I believed, at first, the bug came from Sequel Pro, but my PHP MySQL connection issues (without any error) lead me to the MySQL service instead. I also tried with MySQL Workbench, and I cannot reach the server either. Only the MySQL client is able to. I can't understand why.

**Comment by mikemcquaid** [comment]
They perhaps all rely on native libraries which need MySQL 5.7 support.

**Comment by stevegk** [comment]
Did you run mysql_upgrade? The mysql version has been bumped so the database needs to be upgraded properly. See https://github.com/sequelpro/sequelpro/issues/2302

**Comment by loranger** [comment]
No I did not, and it fixed the issue.
Once upgraded, I restarted the service it I was able to connect again.
Thank you.

The `mysql.server stop` still doesn't work, but that's a minor issue for me, so I close the ticket.
Thank you all 3 by the way, for your support and your work in general.
