### ISSUE TITLE
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by EmmanuelPREVOST** [Homebrew/homebrew#46395]
Hi,

Would be nice to modify the error output just saying to run again `brew update` ?
So you wont get new issue open for that "resolved" issue.

Cordialement,

EP

EDIT: I love `brew` thanks for your work

**Comment by mikemcquaid** [comment]
We can't modify the error output because we can't travel back in time and update code on your machine without `brew update` (which throws the error).
