### ISSUE TITLE
Incorrect file permissions (640)

### ISSUE THREAD

**Issue by cybertk** [Homebrew/homebrew#46419]
It's failed to pass `brew audit` when using a more restrict permission(640) on formula file.

```
==> audit problems
gitlab-ci-multi-runner:
 * Incorrect file permissions (640): chmod 644 /usr/local/Library/Formula/gitlab-ci-multi-runner.rb
```

See [full logs](https://travis-ci.org/cybertk/homebrew-gitlab-runner/builds/93475422#L2393-L2395)

**Comment by mikemcquaid** [comment]
CC @UniqMartin who was dealing with some of these permissions issues recently.

**Comment by UniqMartin** [comment]
In short, `brew audit` expects your formula to have sensible permissions (for a regular file), but respects the bounds of your `umask`. If your actual file permissions are more restrictive than your `umask`, then it will complain. Is there a scenario where this isn't a reasonable thing to expect? You could either adjust your `umask` or your file permissions to avoid the error.

**Comment by cybertk** [comment]
I think it should not complain when actual file permissions are more restrictive than `umask`

**Comment by UniqMartin** [comment]
We try to strike a balance between respecting the user's choice (`umask`) and making sure the file permissions are not overly restrictive to the point where it would create new problems. (We don't succeed to do that in all areas yet.)

I can see the logic in your argument. Is there anything that stops you from taking the pragmatic route of adjusting your `umask` to your file's restrictive permissions or vice versa?

**Comment by cybertk** [comment]
Thanks @UniqMartin 

I understand your concern now, I will adjust `umask`
