### ISSUE TITLE
vtk failed to build on 10.11.1

### ISSUE THREAD

**Issue by mazl123321** [Homebrew/homebrew#46424]
I am trying to install pcl in my Mac

I am sure I want to install vtk as well. But it has build failure.

https://gist.github.com/caa3010359722538c68c

Thank you very much!
Xiaolong

**Comment by dunn** [comment]
Here's the error: https://gist.github.com/anonymous/caa3010359722538c68c#file-03-make-L681-L956

It might have something to do with the non-Homebrew dylibs that `brew doctor` is complaining about: https://gist.githubusercontent.com/anonymous/caa3010359722538c68c/raw/cdf61200e84758b57fca51c1792f9fb250563997/doctor.out

Try moving those out of the way and try again.

**Comment by mazl123321** [comment]
Thanks for the reply!
After I clean all those dylibs, I am still getting same build error.
https://gist.github.com/anonymous/6d00820fb0457b0b01f2

**Comment by dunn** [comment]
Do you know what these uncommitted changes are?
```
Warning: You have uncommitted modifications to Homebrew
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
    cd /usr/local/Library && git stash && git clean -d -f
```

**Comment by mazl123321** [comment]
Hi Dunn, after I run the 
cd /usr/local/Library && git stash && git clean -d -f
everything works fine now.

Thanks!

I am closing this bug.

**Comment by dunn** [comment]
No problem, glad you got it working!
