### ISSUE TITLE
brew install ipe fails

### ISSUE THREAD

**Issue by miccal** [Homebrew/homebrew#46428]
Hello

It seems that the maintainer of ipe has removed the ipe source files from Github to Bintray, but the formula in Homebrew to install ipe has not been updated and curl fails.

Thanks.

**Comment by DomT4** [comment]
Thanks for letting us know! :smiley: 

The build process has changed fairly drastically as well, now seemingly requiring a hard X11 dependency and only generating an app bundle by default with no linked executables.

I don't have the energy to deal with another bunch of `ipe` major update changes so entirely [welcome a PR](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md) if you want to update the formula.

If the hard X11 dep can't be resolved the formula would need to move to `homebrew/x11`.

**Comment by miccal** [comment]
Might it be better to create a cask for ipe?

**Comment by DomT4** [comment]
I certainly wouldn't object to someone submitting a Cask for it to the Caskroom. In this case the upstream developer has made it difficult to continue to package as-is in Homebrew without some dancing around. Happy for someone to do the dancing though if they'd like to.

**Comment by miccal** [comment]
OK, I will do that.

**Comment by miccal** [comment]
Ipe is now available as a Cask. Should ipe now be removed from Homebrew?

**Comment by DomT4** [comment]
I wouldn't object, given it seems to be the upstream intent to move pretty insistently to app bundles for OS X. Will let the other maintainers contribute to the discussion as desired before moving on it though.

**Comment by mikemcquaid** [comment]
Those reasons seem good enough to me :+1:
