### ISSUE TITLE
Problem using openmpi with fortran

### ISSUE THREAD

**Issue by PierreMarchand20** [Homebrew/homebrew#46422]
Hello,

I was using openmpi with fortran without any problem until a few weeks ago when I upgraded openmpi (brew upgrade). Since then, I have the following message when I use mpif90, mpif70 and mpifort : 

No underlying compiler was specified in the wrapper compiler data file
(e.g., mpicc-wrapper-data.txt)

So I don't know why it has lost the compiler and I have tried to uninstall openmpi et reinstall it. I certainly don't use the option --without-fortran ! Any ideas ?

**Comment by zbeekman** [comment]
Yes, I'm experiencing this same problem trying to submit a formula that requires MPI and Fortran. I seem to be able to build things OK locally, but on the test-bot, without re-triggering an OpenMPI build in a very ugly hack, I'm getting the same error. See PR #46547

**Comment by dpo** [comment]
See #46461.

**Comment by PierreMarchand20** [comment]
The issue has been fixed with the last update (see #46461 )
