### ISSUE TITLE
New version of kafka

### ISSUE THREAD

**Issue by vvardhan14** [Homebrew/homebrew#46487]
Hello

Can you please update the repo with new version 0.9 release for Kafka  ?

thanks
Vishnu

**Comment by dunn** [comment]
If you want to open a pull request, we'd love it! Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions.

**Comment by vvardhan14** [comment]
Hello


Can you please point to some Homebrew documentation on how to make new
version available for a formula ?

I can make the change.

Thanks
Vishnu

**Comment by dunn** [comment]
The [formula cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md) should help.  In most cases all you need to do is update the `url` and `sha256` lines.

**Comment by apjanke** [comment]
This version bump is going to be more complicated. Some of their config files, wrapper scripts, and supported environment variables changed between these versions so our patches will fail, and the whole formula needs to be reviewed. I'll take a shot at doing a PR for it.

**Comment by mikemcquaid** [comment]
@apjanke Thanks!

**Comment by apjanke** [comment]
I've got an updated formula for 0.9 going at https://github.com/apjanke/homebrew/tree/kafka-0.9. I think the installation works.

It needs a `test do`, though: the test code also changed between these releases, and the "sanity checks" wrapper script is gone. The [Kafka quickstart guide](http://kafka.apache.org/documentation.html#quickstart) has a couple "hello world" examples. But they involve firing up Vagrant VMs and zookeeper & kafka servers. That seems a lot to manage inside a `test do` block, without possibly leaking server processes or interfering with other running servers. Not sure what to do here. There's now a `kafkatest/sanity_checks`, but that seems to require a whole additional build step and Vagrant management.

**Comment by SleepyBrett** [comment]
Looks like there is a pull ready here:
https://github.com/Homebrew/homebrew/pull/48245

No action on it though.

**Comment by mikemcquaid** [comment]
I'll let @apjanke handle this and work out the best test case to merge (if any).

**Comment by apjanke** [comment]
I am completely out of time for working on this. Sorry. If anybody else can pick this up, have at...

**Comment by DomT4** [comment]
New version was merged in https://github.com/Homebrew/homebrew/commit/e04c0e10c610117307a1511ebe2e22f1048b5063.
