### ISSUE TITLE
Formula API doc link (Rubydoc) does not work

### ISSUE THREAD

**Issue by keyvanfatehi** [Homebrew/homebrew#46482]
This URL no longer works. It's referenced in the generated formula `brew create` 

It's also referenced in the [formula cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md)

The URL in question is http://www.rubydoc.info/github/Homebrew/homebrew/master/Formula

**Comment by mikemcquaid** [comment]
Thanks, I've contacted them but we should probably investigate another host for these docs. @bfontaine and @xu-cheng: any suggestions for other hosting services?

**Comment by mikemcquaid** [comment]
(documentation-specific ones that is)

**Comment by mikemcquaid** [comment]
Fixed

**Comment by keyvanfatehi** [comment]
Nice! Your cookbook was so good I didn't even need it to submit my PR just now :) Thanks

**Comment by mikemcquaid** [comment]
Thanks for the kind words!

**Comment by DomT4** [comment]
It's back up now. Goes down fairly regularly for a varying amount of time. Agree we need at least a mirror though.
