### ISSUE TITLE
brew fetch: fallback to --build-from-source when bottle is not available

### ISSUE THREAD

**Issue by zmwangx** [Homebrew/homebrew#46490]
Without further options, `brew install` or `upgrade` falls back to `--build-from-source` when bottle is not available, but `brew fetch` simply fails. Maybe it would be more consistent if `fetch` also used the same fallback mechanism?

A bit of background: Up till now, whenever I'm updating a formula to a new version, I would edit the URL and run `brew upgrade`, which will fail but from which I can grab the new SHA-256 digest. Alternatively, I would set the digest to empty in the formula and do `upgrade`, which will proceed and will report the new digest which I can edit in. Today I thought of using `fetch` instead to reduce a tiny bit of overhead, but the aforementioned problem is hindering the process unless I specify `--build-from-source`.

**Comment by mikemcquaid** [comment]
Makes sense to me :+1:
