### ISSUE TITLE
curl times out during active download

### ISSUE THREAD

**Issue by hashier** [Homebrew/homebrew#46513]
Maybe this is rather a curl problem than a home-brew problem, but the only time I see this happening is in home-brew and never with curl on the command line (admitting, that I don't use curl that much on the cmd line for big file downloads).

Sometimes with a flaky internet connection curl just stopes downloading files and says the connection timed out even though the connection was downloading files constantly with but admittedly with a comparable small rate.

```
==> Installing harfbuzz dependency: icu4c
==> Downloading https://homebrew.bintray.com/bottles/icu4c-56.1.el_capitan.bottle.tar.gz
####################################################################      94.7%
curl: (28) Operation timed out after 89393 milliseconds with 23823362 out of 25145151 bytes received
Error: Failed to download resource "icu4c"
Download failed: https://homebrew.bintray.com/bottles/icu4c-56.1.el_capitan.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://ssl.icu-project.org/files/icu4c/56.1/icu4c-56_1-src.tgz
```

**Comment by bfontaine** [comment]
You can try again; `curl` will resume the download where it stopped.

**Comment by DomT4** [comment]
Let us know if we can help further here, Thanks!

**Comment by hashier** [comment]
Well... it builds from source by default anyway, so no need to retry it anyway but it is not optimal to just retry or fall back to source.

So I wouldn't say it solves the bug but I can understand that it's low priority
