### ISSUE TITLE
How to link installed python3 to homebrew

### ISSUE THREAD

**Issue by hsiaoyi0504** [Homebrew/homebrew#46518]
As title, I have python3 installed
But can't be detected by homebrew (I forgot how I install python3 .....)
How can I fix that?

**Comment by ericvw** [comment]
@hsiaoyi0504, how did you install `python3` (i.e., `brew install python3`)?

If `python3` was installed via `brew install python3`, you should observe something similar to the following:
```shell
$ ls -l /usr/local/bin/python3
lrwxr-xr-x 1 eric admin 35 Sep 14 09:29 /usr/local/bin/python3 -> ../Cellar/python3/3.5.0/bin/python3
```

**Comment by rakkesh** [comment]
Why not install `python3` using `Homebrew`? If you insist on using your existing installation, assuming that the `Python3` installation is not broken, you can use `python3-config` to link in the formula.

Use the following within a formula prior to the line having `./configure`,

```
ENV.prepend "LDFLAGS", "<replace with output of `python3-config --libs`>"
ENV.prepend "CFLAGS", "<replace with output of `python3-config --cflags`>"
```

**Comment by hsiaoyi0504** [comment]
Thank you all for your advice
Sorry for my stupid question
I am a beginner of mac, python and homebrew
I have solved this condition
It seems I installed python through anaconda (not sure if is `brew install anaconda` or other methods)
I have removed that and reinstall python3 through homebrew
But another question exists, I also install opencv3 through homebrew with `brew install opencv3 --with-python3`
But I find that python can't detect cv2 module
I solve this by adding `export PYTHONPATH=$PYTHONPATH:/usr/local/Cellar/opencv3/3.0.0/lib/python3.5/site-packages`
in `~/.profile` and `source ~/.profile` every time when I start the terminal
But maybe I expect that it should link by homebrew automatically

**Comment by reitermarkus** [comment]
@hsiaoyi0504, try renaming `.profile` to `.bashrc`, this way `bash` should source it automatically.

**Comment by hsiaoyi0504** [comment]
Thank you for your suggestion.
Actually, I have done this before your reply
But I have a question that this task supposedly should be done by homebrew, right?

**Comment by DomT4** [comment]
The [formula in question](https://github.com/Homebrew/homebrew-science/blob/master/opencv3.rb#L30) is `keg_only` and so isn't being linked deliberately, so that's why you can't access it globally here. Normally it would be available automatically.

**Comment by hsiaoyi0504** [comment]
ok, thank you for your help :+1:
