### ISSUE TITLE
How to add a configuration file? (to /usr/local/etc)

### ISSUE THREAD

**Issue by meehow** [Homebrew/homebrew#46511]
Hi,
I'm trying to add a configuration file to Rethinkdb formula.
I checked how other formula is done (Mongodb) and found some `etc.install` at the end of install definition.
I created [something similar for Rethinkdb](https://github.com/meehow/homebrew/commit/c730d0953a5a81e75b8b11d72b18e6ecccbcd14c), but it looks like install is not executed at all when I do `brew install`. Unfortunately new plist file was generated and it points to not existing etc file.
 
My question is: When is [etc.install](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/mongodb.rb#L98) executed and how to test if new configuration file is created properly?

    (buildpath+"mongod.conf").write mongodb_conf
    etc.install "mongod.conf"

**Comment by rakkesh** [comment]
If a `Homebrew` bottle is available for your platform it's used instead of invoking the formula's `install` method. Execute `brew install rethinkdb --build-from-source` to build from source, so that, your changes are used.
