### ISSUE TITLE
ppl011: "C compiler cannot create executables" on 10.11

### ISSUE THREAD

**Issue by narychen** [Homebrew/homebrew#46533]
"C compiler cannot create executables", it seems a lot reports about this.
I seached stackoverflow and googled other resources. None of them fixed mine.
I still always got error when install something needed to compile.
I have gcc and clang and xcode installed.
My system is EI capitan and xcode version is 7.1.1
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.1.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
$ clang -v
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix

I even try to brew install new version of gcc. But it need to compile and ended like others with "C compiler cannot create executables"

$ brew install --enable-cxx gcc45
==> Installing gcc45 from homebrew/homebrew-versions
==> Installing dependencies for homebrew/versions/gcc45: ppl011, cloog-ppl015
==> Installing homebrew/versions/gcc45 dependency: ppl011
==> Downloading http://bugseng.com/products/ppl/download/ftp/releases/0.11/ppl-0.11.tar.gz
Already downloaded: /Library/Caches/Homebrew/ppl011-0.11.tar.gz
==> Downloading https://gist.githubusercontent.com/manphiz/9507743/raw/45081e12c2f1faf81e8536f365af05173c6dab5c/
Already downloaded: /Library/Caches/Homebrew/ppl011--patch-db8ced5366ec4c3efb6fd20d3b4e440de3f8b9ec1d930a33b6a23d006dc25944.patch
==> Patching
patching file configure
==> ./configure --prefix=/usr/local/Cellar/ppl011/0.11_1 --disable-silent-rules --disable-ppl_lpsol --disable-pp
Last 15 lines from /Users/nary/Library/Logs/Homebrew/ppl011/01.configure:
checking host system type... x86_64-apple-darwin15.0.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking how to create a ustar tar archive... gnutar
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/tmp/ppl01120151201-8248-1kq88hk/ppl-0.11':
configure: error: C compiler cannot create executables
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-versions/issues

**Comment by mistydemeo** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Have you read this? Can you post the diagnostics it requests, please?

**Comment by narychen** [comment]
yep, I did brew update and doctor
the doctor gist link is  https://gist.github.com/narychen/057b8951670b9259d2f1

**Comment by narychen** [comment]
also  did  brew gist-logs gcc45 output
Error: No logs.

**Comment by mistydemeo** [comment]
The software that failed was `ppl011` - can you run `brew gist-logs ppl011` please? Thanks!

**Comment by narychen** [comment]
$ brew gist-logs ppl011
https://gist.github.com/3db3b1649ea911def3ea

**Comment by mistydemeo** [comment]
```
configure:4342: clang    conftest.c  >&5
ld: building for iOS simulator, but linking against dylib built for OSX, file '/usr/lib/libSystem.dylib' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It looks like your compiler is trying to build for the iOS simulator instead of OS X; do you know why that might be?

**Comment by narychen** [comment]
Because I met another problem for node.js building.
I do the "sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib"
https://github.com/nodejs/node/issues/4094

**Comment by narychen** [comment]
removing the ln -s still produce this issue.
$ rm /usr/local/lib/libgcc_s.10.4.dylib 
narymatoMacBook-Air:~ nary$ rm /usr/local/lib/libgcc_s.10.5.dylib 
narymatoMacBook-Air:~ nary$ 
narymatoMacBook-Air:~ nary$ 
narymatoMacBook-Air:~ nary$ brew install --enable-cxx gcc45
==> Installing gcc45 from homebrew/homebrew-versions
==> Installing dependencies for homebrew/versions/gcc45: ppl011, cloog-pp
==> Installing homebrew/versions/gcc45 dependency: ppl011
==> Downloading http://bugseng.com/products/ppl/download/ftp/releases/0.11/ppl-0
Already downloaded: /Library/Caches/Homebrew/ppl011-0.11.tar.gz
==> Downloading https://gist.githubusercontent.com/manphiz/9507743/raw/45081e12c
Already downloaded: /Library/Caches/Homebrew/ppl011--patch-db8ced5366ec4c3efb6fd20d3b4e440de3f8b9ec1d930a33b6a23d006dc25944.patch
==> Patching
patching file configure
==> ./configure --prefix=/usr/local/Cellar/ppl011/0.11_1 --disable-silent-rules 
Last 15 lines from /Users/nary/Library/Logs/Homebrew/ppl011/01.configure:
checking host system type... x86_64-apple-darwin15.0.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking how to create a ustar tar archive... gnutar
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/tmp/ppl01120151202-28277-8m7bvw/ppl-0.11':
configure: error: C compiler cannot create executables
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-versions/issues

These open issues may also help:
ppl011: "C compiler cannot create executables" on 10.11 https://github.com/Homebrew/homebrew/issues/46533
narymatoMacBook-Air:~ nary

**Comment by narychen** [comment]
still there...I shall check it

**Comment by narychen** [comment]
found something similar to my problem
https://github.com/Homebrew/homebrew/issues/38213

**Comment by narychen** [comment]
The problem is fixed after I updated the patch of "Command Line Tools (OSX 10.11) for Xcode" and rebooted the machine.
