### ISSUE TITLE
Doesn't work without permissions

### ISSUE THREAD

**Issue by Announcement** [Homebrew/homebrew#46546]
Is there a way I can compile it for myself/use without 'sudo', got locked out of adminship on the mac.

**Comment by UniqMartin** [comment]
Please have a look at the [“Alternative Installs” section](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Installation.md#alternative-installs) in the install documentation and see if that works for you. Note that installing to a non-standard location usually works, but can have some disadvantages, so make sure to read the FAQ, particularly [this item](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md#why-does-homebrew-insist-i-install-to-usrlocal-with-such-vehemence).

**Comment by DomT4** [comment]
It's pretty typical for non-admin users to install Homebrew into their `$HOME` path under a subdirectory. We see that a lot with academic usage. It's all `git`, so anything you can do with git, you can do here.

You may also wish to set your `HOMEBREW_CACHE` and `HOMEBREW_LOGS` variables to a directory you know you can write in. I use `$(brew --prefix)/var/homebrew` personally.

**Comment by DomT4** [comment]
Let us know if we can help further here, Thanks!
