### ISSUE TITLE
python and crossover 15 beta error "import cxutils"

### ISSUE THREAD

**Issue by Marvin91** [Homebrew/homebrew#46544]
because of file "~/Library/Python/2.7/lib/python/site-packages/homebrew.pth" osx version of python looks inside "/usr/local/lib/python2.7/site-packages" and crossover.app don't starts.

Crossover shows this error: "Failed to import cxutils module into Python" and this:

```
Traceback (most recent call last):
  File "/Users/keymaster/cxoffice-15.0.0beta3rc2/macosx/CrossOver/build/Pro Release/CrossOver.app/Contents/SharedSupport/CrossOver/lib/python/cxutils.py", line 21, in <module>
  File "/Users/keymaster/cxoffice-15.0.0beta3rc2/macosx/CrossOver/build/Pro Release/CrossOver.app/Contents/SharedSupport/CrossOver/lib/python/distversion.py", line 21, in <module>
  File "/usr/local/lib/python2.7/site-packages/objc/__init__.py", line 18, in <module>
    _update()
  File "/usr/local/lib/python2.7/site-packages/objc/__init__.py", line 15, in _update
    import objc._objc as _objc
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/objc/_objc.so, 2): no suitable image found.  Did find:
	/usr/local/lib/python2.7/site-packages/objc/_objc.so: mach-o, but wrong architecture
```

after removing or renaming the file "~/Library/Python/2.7/lib/python/site-packages/homebrew.pth" crossover work.

this is a bug in crossover 15 beta or in brew's python?

**Comment by mikemcquaid** [comment]
CC @tdsmith for help debugging this.

**Comment by tdsmith** [comment]
Strictly, neither. Do you know if Crossover runs in 32-bit mode? Removing the .pth file or uninstalling pyobjc from the /usr/local site-packages will allow Crossover to prefer the version that comes with OS X, which is apparently what it needs.

Crossover could try harder to configure its Python environment to avoid this kind of conflict.

**Comment by tdsmith** [comment]
FWIW, preferring packages in the /usr/local site-packages over the system versions is an intended behavior because OS X ships with weird and old versions of numpy, scipy, and matplotlib which can't be upgraded in place.

**Comment by Marvin91** [comment]
Crossover runs only in 32-bit

**Comment by tdsmith** [comment]
I think there isn't a Homebrew bug here and I've explained a workaround. Let us know if we can help with anything.
