### ISSUE TITLE
Help with picking compiler & MPI for brew testbot

### ISSUE THREAD

**Issue by zbeekman** [Homebrew/homebrew#46551]
Hi, this is in regards to PR #46547.
[The test is failing on the brew bot](https://travis-ci.org/Homebrew/homebrew/builds/94237436), and, full disclosure, I think I have messed something up in my local homebrew setup, but that's a separate issue.

My questions are:
 1. Is there a way to prefer one MPI implementation over another? Also to enforce that they are built with Fortran support? The best support & performance for OpenCoarrays is obtained with MPICH rather than OpenMPI
 1. What's the correct/best way to specify that this project requires GCC >= 5.1? (certainly GFortran must be >= 5.1 I'm not sure if you can mix GCC versions across C and Fortran compilers)
 1. [Why does CMake think the mpif90 compiler wrapper is broken on the test bot](https://travis-ci.org/Homebrew/homebrew/jobs/94237438#L660)?

**Comment by zbeekman** [comment]
I just pushed a new attempt using the `fails_with` block to ensure building is done with gcc not clang or llvm, and gcc >= 5.2. Not sure if this is the correct way to do things, still looking for answers to the above questions, would really appreciate any help from @homebrew

**Comment by zbeekman** [comment]
OK, I finally have everything building, (I still would like answers to questions 1 & 2 above, however) but in order to make this happen I need to set `HOMEBREW_CC=gcc-5`. Is there a way to require this in the Formula? (i.e., question 2 above)

**Comment by UniqMartin** [comment]
**MPI:** There's unfortunately no way to specify a preferred implementation. If the user already installed an MPI implementation, that one will be used. If none is installed yet, the default implementation will be automatically pulled in (currently `open-mpi`). To express that Fortran support is required, you have to use something like `depends_on :mpi => :f90` (already in your formula).

**Compiler Restriction:** The general assumption is that a formula builds with all kinds of compilers and only breaks with few of them. Thus, there's currently no way to blacklist all compilers and then to whitelist just a few again. But, if everything provided by Xcode is blacklisted, the user will automatically be prompted to install `gcc`, so there's no need to specify it as an explicit dependency in the formula. It is also not necessary to set `HOMEBREW_CC` or to pass `--cc=` in this case. To blacklist all compilers provided by previous and current Xcode releases, use:

```ruby
fails_with :clang
fails_with :gcc     # Apple GCC 4.2
fails_with :gcc_4_0 # Apple GCC 4.0
fails_with :llvm    # Apple LLVM-GCC 4.2
```

If you really need to blacklist all GCC versions prior to 5, you have to explicitly list all GCC releases supported by Homebrew, i.e. (note that `:gcc` and `:gcc => series` specify entirely different compilers):

```ruby
("4.3".."4.9").each do |series|
  fails_with :gcc => series
end
```

This will exclude every minor release, too. If your formula really only works with GCC >= 5.2 `fails_with :gcc => "5.1"` will exclude this specific release (this was the first release in the 5 series, there is no 5.0).

For all of these `fails_with` statement you can use the block form to specify a `cause`, but that isn't currently used, so I'd advise against it in your case.

**Comment by zbeekman** [comment]
Thanks so much for your help @UniqMartin!

One question regarding the test exclusions: Is there a way to query which version of GCC is being used? 

One of the tests being skipped is a known issue with GCC/GFortran 5.2 and a patch has been submitted and excepted for 5.3 and 6.x development version.

In a similar vein, is there a way to indicate a preferred compiler? (i.e. GCC >= 5.3) I know this hasn't been released yet, but it resolves at least one of these issues.

**Comment by zbeekman** [comment]
OK, I think I have a decent way of extracting the version info from GCC. I looked at the git formula for inspiration.

I do something like:
```ruby
  def install
    mkdir "build" do
# ...
      ENV["CC"] = "mpicc"
      gcc_version = /\d\.\d+/.match(`mpicc --version`)
# ...
      # see sourceryinstitute/opencoarrays/blob/master/STATUS.md#compiler-issues-gnu
      test_excludes << "|co_reduce" if gcc_version.to_s < "5.3"
```
I think this was the last missing piece to achieve a workable Formula for OpenCoarrays. Closing the issue
