### ISSUE TITLE
wget failed to build on 10.6.8

### ISSUE THREAD

**Issue by frickler01** [Homebrew/homebrew#46566]
Using a vanilla installation of Snow Leopard with XCode 3.2.6, `wget` build breaks on creating documentation with `pod2man` during `make install`.

	/usr/local/Library/ENV/4.3/pod2man --center="GNU Wget" --release="GNU Wget 1.17" --utf8 wget.pod  wget.1
	Unknown option: utf8

The system `pod2man` doesn't understand the flag. So I tried

	brew install perl && brew link perl --force

but installing and linking the current `perl` alone doesn't help. Homebrew is obviously looking for the wrong thing.

Looking at `/usr/local/Library/ENV/4.3/pod2man` we have

	#!/bin/bash
	POD2MAN=$(/usr/bin/which pod2man5.18 || /usr/bin/which pod2man5.16 || /usr/bin/which pod2man5.12 || echo /usr/bin/pod2man)
	exec $POD2MAN "$@"

I don't see an easy automatic way to append version numbers to the brew symlinks, so I just edited the file and added

	/usr/bin/which pod2man

in between, which should give `/usr/local/bin/pod2man`. I have `/usr/local/bin` on top of `/etc/paths`. This led to the strange but logical result, that the whole thing hung up in a loop, since brew prepends `/usr/local/Library/ENV/4.3` to the install shell and therefore `which` again finds the same `/usr/local/Library/ENV/4.3/pod2man`.

The only way is therefore hardcoding `/usr/local/bin/pod2man` - but this seems clumsy and a very special case solution.

Does it make sense to version the binaries? How would I do it? Or should I instead add some pod2man5.18 to `ENV`? How?

I know homebrew is supposed to use system tools, but for an old OS like 10.6.8 you often need more current ones. It's also kind of weird that the ENV is the same from XCode 3.2.6 up to 4.3 (it's just symlinked).

Thanks for your help.

PS: [`brew --config` Gist](https://gist.github.com/frickler01/57633ff6b4376133de3a)

**Comment by mikemcquaid** [comment]
Can you run `/usr/bin/pod2man --version` for me? This probably needs a patch for OS X 10.6 specifically. Note that you will probably run into more issues like this as we don't officially support 10.6 any more unfortunately. Thanks!

**Comment by frickler01** [comment]
`/usr/bin/pod2man` does not know `--version`, inside [it says](https://gist.github.com/frickler01/5a09f99f19b361da6b1f)

    The contents of this script should normally never run!  The perl wrapper
    should pick the correct script in /usr/bin by appending the appropriate version.
    You can try appending the appropriate perl version number.  See perlmacosx.pod
    for more information about multiple version support in Mac OS X.

and there exist two files `/usr/bin/pod2man5.10.0` and `/usr/bin/pod2man5.8.9` which seem to do the actual work.

**Comment by mikemcquaid** [comment]
@mistydemeo Any thoughts about the best way of handling stuff like this?

**Comment by uwehermann** [comment]
Any updates on this? I'm seeing the same issue on 10.6.8.

Same files here, pod2man5.10.0 and pod2man5.8.9.

**Comment by mistydemeo** [comment]
@mikemcquaid Vendoring a `pod2man` or creating a keg-only `pod2man` for use by packages that need a newer one on older OSs is probably the best approach. I can look at doing that.

**Comment by mikemcquaid** [comment]
> @mikemcquaid Vendoring a pod2man or creating a keg-only pod2man for use by packages that need a newer one on older OSs is probably the best approach. I can look at doing that.

@mistydemeo Sounds good :+1:

**Comment by skinkie** [comment]
@mistydemeo leads to:
```
==> Installing dependencies for wget: pod2man
==> Installing wget dependency: pod2man
==> Downloading http://archives.eyrie.org/software/perl/podlators-4.03.tar.xz
######################################################################## 100,0%
==> perl Makefile.PL INSTALL_BASE=/usr/local/Cellar/pod2man/4.03
==> make install
Error: No such file or directory - /usr/local/Cellar/pod2man/4.03/man
```

**Comment by dunn** [comment]
@skinkie Can you open a new issue and post `brew gist-logs pod2man`? Thanks!

**Comment by skinkie** [comment]
While the installation of pod2man seems successful now, thanks @mistydemeo 

The installation of wget seems to hang on some make install-recursive. I notice that pod2man from /usr/bin is invoked, while it might been expected that the Cellar one was picked. Anything I can do to show some compile logs?

**Comment by ssreekanth** [comment]
It is still failing.. 
```
==> Downloading http://ftpmirror.gnu.org/wget/wget-1.17.1.tar.xz
Already downloaded: /Library/Caches/Homebrew/wget-1.17.1.tar.xz
==> ./configure --prefix=/usr/local/Cellar/wget/1.17.1 --sysconfdir=/usr/local/etc --with-ssl=openssl --with-libssl-prefix=/usr/local/opt/opens
==> make install
Last 15 lines from /Users/sreekanth/Library/Logs/Homebrew/wget/02.make:
  /usr/bin/install -c wget '/usr/local/Cellar/wget/1.17.1/bin'
Making install in doc
make[3]: Nothing to be done for `install-exec-am'.
/bin/sh /private/tmp/wget20151231-20456-1ljxr8f/wget-1.17.1/build-aux/install-sh -d /usr/local/etc
./texi2pod.pl -D VERSION="1.17.1" ./wget.texi wget.pod

 ../build-aux/install-sh -c -d '/usr/local/Cellar/wget/1.17.1/share/info'
 /usr/bin/install -c -m 644 ./wget.info '/usr/local/Cellar/wget/1.17.1/share/info'
 install-info --info-dir='/usr/local/Cellar/wget/1.17.1/share/info' '/usr/local/Cellar/wget/1.17.1/share/info/wget.info'
/usr/local/Library/ENV/4.3/pod2man --center="GNU Wget" --release="GNU Wget 1.17.1" --utf8 wget.pod > wget.1
Unknown option: utf8
make[3]: *** [wget.1] Error 1
make[2]: *** [install-am] Error 2
make[1]: *** [install-recurs
```

**Comment by cbeaton** [comment]
I ran into the same error as  @ssreekanth today after installing brew for the first time.  
I modified /usr/local/Library/ENV/4.3/pod2man as below:

#!/bin/bash
POD2MAN=$(/usr/bin/which pod2man5.18 || /usr/bin/which pod2man5.16 || /usr/bin/which pod2man5.12 || /usr/bin/which $HOMEBREW_PREFIX/opt/pod2man/usr/bin/pod2man || echo /usr/bin/pod2man)
#POD2MAN=$(/usr/bin/which pod2man5.18 || /usr/bin/which pod2man5.16 || /usr/bin/which pod2man5.12 || /usr/bin/which $HOMEBREW_PREFIX/opt/pod2man/bin/pod2man || echo /usr/bin/pod2man)
exec $POD2MAN "$@"


and the install was successful.

**Comment by mistydemeo** [comment]
Looks like pod2man installs into the wrong location on 10.6:

```
$ brew ls pod2man -v
/usr/local/Cellar/pod2man/4.04/Changes
/usr/local/Cellar/pod2man/4.04/INSTALL_RECEIPT.json
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.10.0/darwin-thread-multi-2level/auto/Pod/.packlist
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.10.0/darwin-thread-multi-2level/perllocal.pod
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.10.0/Pod/Man.pm
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.10.0/Pod/ParseLink.pm
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.10.0/Pod/perlpodstyle
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.10.0/Pod/Text/Color.pm
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.10.0/Pod/Text/Overstrike.pm
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.10.0/Pod/Text/Termcap.pm
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.10.0/Pod/Text.pm
/usr/local/Cellar/pod2man/4.04/LICENSE
/usr/local/Cellar/pod2man/4.04/NOTES
/usr/local/Cellar/pod2man/4.04/README
/usr/local/Cellar/pod2man/4.04/TODO
/usr/local/Cellar/pod2man/4.04/usr/bin/pod2man
/usr/local/Cellar/pod2man/4.04/usr/bin/pod2text
```

vs

```
$ brew ls pod2man -v
/usr/local/Cellar/pod2man/4.04/bin/pod2man
/usr/local/Cellar/pod2man/4.04/bin/pod2text
/usr/local/Cellar/pod2man/4.04/Changes
/usr/local/Cellar/pod2man/4.04/INSTALL_RECEIPT.json
/usr/local/Cellar/pod2man/4.04/lib/perl5/site_perl/5.18.2/darwin-thread-multi-2level/auto/Pod/.packlist
/usr/local/Cellar/pod2man/4.04/lib/perl5/site_perl/Pod/Man.pm
/usr/local/Cellar/pod2man/4.04/lib/perl5/site_perl/Pod/ParseLink.pm
/usr/local/Cellar/pod2man/4.04/lib/perl5/site_perl/Pod/perlpodstyle
/usr/local/Cellar/pod2man/4.04/lib/perl5/site_perl/Pod/Text/Color.pm
/usr/local/Cellar/pod2man/4.04/lib/perl5/site_perl/Pod/Text/Overstrike.pm
/usr/local/Cellar/pod2man/4.04/lib/perl5/site_perl/Pod/Text/Termcap.pm
/usr/local/Cellar/pod2man/4.04/lib/perl5/site_perl/Pod/Text.pm
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.18.2/darwin-thread-multi-2level/perllocal.pod
/usr/local/Cellar/pod2man/4.04/LICENSE
/usr/local/Cellar/pod2man/4.04/NOTES
/usr/local/Cellar/pod2man/4.04/README
/usr/local/Cellar/pod2man/4.04/share/man/man1/perlpodstyle.1
/usr/local/Cellar/pod2man/4.04/share/man/man1/pod2man.1
/usr/local/Cellar/pod2man/4.04/share/man/man1/pod2text.1
/usr/local/Cellar/pod2man/4.04/share/man/man3/Pod::Man.3pm
/usr/local/Cellar/pod2man/4.04/share/man/man3/Pod::ParseLink.3pm
/usr/local/Cellar/pod2man/4.04/share/man/man3/Pod::Text.3pm
/usr/local/Cellar/pod2man/4.04/share/man/man3/Pod::Text::Color.3pm
/usr/local/Cellar/pod2man/4.04/share/man/man3/Pod::Text::Overstrike.3pm
/usr/local/Cellar/pod2man/4.04/share/man/man3/Pod::Text::Termcap.3pm
/usr/local/Cellar/pod2man/4.04/TODO
```

**Comment by mistydemeo** [comment]
Should be fixed now.

**Comment by mistydemeo** [comment]
You'll need to reinstall pod2man, then can you try installing wget again?

**Comment by cbeaton** [comment]
I discarded my changes, deinstalled pod2man and wget, pulled your commit, and then ran 'brew install wget'  and it succeeded.   Thank you!

**Comment by frickler01** [comment]
@mistydemeo Great job, thanks a lot!

**Comment by uwehermann** [comment]
Works fine for me as well, thanks!

**Comment by wyatt8740** [comment]
Greetings from macports. A better way that did not require vendoring pod2man:
`ac_cv_path_POD2MAN=/usr/bin/pod2man5.10.0` before running configure.

**Comment by rsaeks** [comment]
Seeing this issue today with wget failing to install on a 10.6.8 machine. The current version of pod2man pulled is 4.0.6 and wget is 1.17.1 failing with Unknown option: utf8
