### ISSUE TITLE
brew installed python2 gets fatal error when import the Xcode's lldb library.

### ISSUE THREAD

**Issue by d0u9** [Homebrew/homebrew#46561]
My active python2 is installed by `brew install python` command. However, when I import lldb via the command below on my OSX, fatal error reports:

```
import sys
sys.path = sys.path + ['/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python']
import lldb

Fatal Python error: PyThreadState_Get: no current thread
[1]    7863 abort      ipython2
```

It seems that the version lldb is incompatible with the python which is installed via homebrew. Does anyone encounter this problem?

My operating system is OSX 10.11.1, and the lldb is ship with Xcode.

**Comment by UniqMartin** [comment]
The Python library you try to load is explicitly linked to `/System/Library/Frameworks/Python.framework/Versions/2.7/Python`, which conflicts with the already loaded Python framework provided by the Homebrew `python` package. As the LLDB framework isn't provided by Homebrew, there's unfortunately nothing we can do about this. You will have to use the system `python` to interact with LLDB.

(You can [read about the technical background](http://blog.tim-smith.us/2015/09/python-extension-modules-os-x/) of the underlying issue, if that's of interest to you.)

**Comment by d0u9** [comment]
well, alternatively, does homebrew provide lldb? If so, I can use the homebrew version lldb instead of the Xcode's.

**Comment by UniqMartin** [comment]
You can try `brew install llvm --with-lldb` and see if that works for you. (Also have a look at `brew options llvm` for additional options you might want to use.)

**Comment by d0u9** [comment]
I encounter errors again when I install llvm... I am trying to solve it...

**Comment by UniqMartin** [comment]
Are these errors with installing `llvm` or when trying to use the `lldb` installed by it from Python? If it's the former, you might want to check out #42041 and also search for other `llvm`-related Homebrew issues.

If that's too much trouble, I'd still suggest to stick with the Python provided with OS X. Not sure if this is feasible, as I don't know your use case.

**Comment by tdsmith** [comment]
This is an upstream issue: https://llvm.org/bugs/show_bug.cgi?id=25446 -- lldb only supports linking against the system Python. Sorry! Let us know if we can help with anything.
