### ISSUE TITLE
brew should try to get GitHub API credentials from git

### ISSUE THREAD

**Issue by mdiep** [Homebrew/homebrew#46578]
When trying to use the GitHub API, `brew` should try to get credentials from `git`.

When unauthenticated, the GitHub API is heavily rate-limited. This is especially a problem if you're behind a shared IP—a common setup and problem when working.

Rather than requiring you to configure a GitHub API token in homebrew's settings, `brew` should try to use the credentials from `git` as a zero-config option. If you can clone private repositories from GitHub over HTTPS, then credentials can be retrieved from `git credential fill` to use for the API. [Carthage](https://github.com/Carthage/Carthage) [does this](https://github.com/Carthage/Carthage/blob/60011123527ee7a4edb7c165bc7490f3201c47ee/Source/CarthageKit/GitHub.swift#L326) when using the GitHub API.

**Comment by zbeekman** [comment]
:+1:

**Comment by skiz** [comment]
:+1:

**Comment by mikemcquaid** [comment]
PR open in https://github.com/Homebrew/homebrew/pull/49846.
