### ISSUE TITLE
Building python3 from source fails

### ISSUE THREAD

**Issue by jonashaag** [Homebrew/homebrew#46579]
```
brew install --build-from-source python3
[...snip...]
==> ./configure --prefix=/usr/local/Cellar/python3/3.5.0 --enable-ipv6 --datarootdir=/usr/local/Cellar/python3/3.5.0/share --datad
==> make
==> make install PYTHONAPPSDIR=/usr/local/Cellar/python3/3.5.0
==> make frameworkinstallextras PYTHONAPPSDIR=/usr/local/Cellar/python3/3.5.0/share/python3
Error: No such file or directory - /usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/config-3.5m/Makefile
```

https://gist.github.com/anonymous/b435ec3ecfbb877aae07

**Comment by DomT4** [comment]
I can't find that error in your logs, nor can I reproduce locally. Were the logs from a later successful build at all or anything?

**Comment by jonashaag** [comment]
@DomT4 no, they were taken right after the failed build. What's weird is that the file in question (`/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/config-3.5m/Makefile`) actually exists:

```
$ file /usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/config-3.5m/Makefile
/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/config-3.5m/Makefile: ASCII English text, with very long lines
```

**Comment by jonashaag** [comment]
OK i just rechecked, this only happens when I add `--with-pydebug` (a legitimate `./configure` option) to `args`. I understand that I'll probably won't get support for this, but maybe you could give me some pointers what's going wrong here?

**Comment by DomT4** [comment]
Yeah, if you're using a configure argument we don't support ourselves we can't guarantee build success, for obvious reasons.

I don't know how much time Tim has at the moment, but if he wants to @tdsmith may be able to elaborate on why we don't support that option/what problems it can cause. Can't promise anything though.

**Comment by tdsmith** [comment]
The failure's in the inreplace at line 188.

The config directory should named something different, like `config-3.5dm` or similar, for the debug build. (When you look after the reinstall fails, you're seeing the Makefile in the regular python3 package, which does exist there; the whole python3 directory is moved out of the way before Homebrew attempts to do the reinstall, and Homebrew puts it back when it notices that the reinstall fails.)

If you can figure out an incantation to learn the right ABI string from the interpreter we could make that inreplace more robust.

**Comment by tdsmith** [comment]
Or we could just change `frameworks/"Python.framework/Versions/#{xy}/lib/python#{xy}/config-#{xy}m/Makefile" ` to `Dir[frameworks/"Python.framework/Versions/#{xy}/lib/python#{xy}/config-#{xy}*/Makefile"]` I guess!

**Comment by jonashaag** [comment]
For Python >= 3.2, this should be available from `sys.abiflags`
