### ISSUE TITLE
brew don't see updates

### ISSUE THREAD

**Issue by magefad** [Homebrew/homebrew#46582]
El Capitan
For example - my virtualbox is 5.0.2, 5.0.10 in repository. Brew upgrade, update, cask update show me already up to date. Brew doctor also not showing errors.

But after run brew install virtualbox - brew downloaded latest version, such as in github formula file.

Now I see not updated osxfuse - https://github.com/Homebrew/homebrew/blob/master/Library/Formula/osxfuse.rb

My version 2.8.1, updated - 2.8.2

What can I do to auto update packages, not manually install as in first example with virtualbox?

**Comment by bfontaine** [comment]
What does `brew info osxfuse` say?

**Comment by magefad** [comment]
osxfuse: stable 2.8.2, HEAD
FUSE for OS X: extend native file handling via 3rd-party file systems
https://osxfuse.github.io/
Not installed
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/osxfuse.rb
==> Dependencies
Build: autoconf ✔, automake ✘, libtool ✘, gettext ✔
==> Caveats
If upgrading from a previous version of osxfuse, the previous kernel extension
will need to be unloaded before installing the new version. First, check that
no FUSE-based file systems are running:

  mount -t osxfusefs

Unmount all FUSE file systems and then unload the kernel extension:

  sudo kextunload -b com.github.osxfuse.filesystems.osxfusefs

The new osxfuse file system bundle needs to be installed by the root user:

  sudo /bin/cp -RfX /usr/local/opt/osxfuse/Library/Filesystems/osxfusefs.fs /Library/Filesystems/
  sudo chmod +s /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs



brew cask list
cleanmymac		     phpstorm			  sublime-text		       virtualbox		    web-sharing
osxfuse

**Comment by magefad** [comment]
brew cask info osxfuse
osxfuse: 2.8.2
OSXFUSE
https://osxfuse.github.io/
Not installed
https://github.com/caskroom/homebrew-cask/blob/master/Casks/osxfuse.rb
==> Contents
  Install OSXFUSE 2.8.pkg (pkg)
==> Caveats
You must reboot for the installation of osxfuse to take effect.

**Comment by DomT4** [comment]
The Cask doesn't really have an autoupdate mechanism at this point, as far as I'm aware. For Cask stuff that I know has an update I tend to do `brew cask reinstall xyz --force`.

**Comment by magefad** [comment]
Hm. What if reinstall formula, not cask version? And why osfuse has two versions - cask and formula?

**Comment by DomT4** [comment]
If there's a *formula* update you should just be able to `brew update && brew upgrade osxfuse`, for example.

`osxfuse` has a formula version and a Cask version because the formula version builds from source and consequently doesn't have a signed kext and won't run on anything above Mavericks. The `osxfuse` in the Caskroom is upstream's `.pkg` binary release, which includes a signed kext and consequently will run on all OS X versions.

**Comment by mikemcquaid** [comment]
What does `brew upgrade osxfuse` say?

**Comment by DomT4** [comment]
Let us know if we can help further here, Thanks!
