### ISSUE TITLE
Make it easy for projects to automate homebrew PRs

### ISSUE THREAD

**Issue by mdiep** [Homebrew/homebrew#46580]
I'm one of the maintainers of [Carthage](https://github.com/Carthage/Carthage). Every time we release a new version, someone needs to manually open a PR against homebrew to update to the latest version. It'd be really great if this was easily automatable for project maintainers as part of deployment. Carthage already uploads a new installer from Travis as part of the deployment process when a new tag is created. I'd love for updating homebrew to be just another automated step in that process.

I think this could be either:

1. A webhook/service that's configurable on GitHub and listens to tags/releases and responds by creating a new PR against Homebrew.

2. Some documentation and/or example scripts that project maintainers can add to Travis' deploy steps to automate opening a Homebrew PR.

At least in Carthage's case, updating homebrew means changing a SHA and a tag name. That seems like a great thing for a computer to do for us. :relaxed:

**Comment by mikemcquaid** [comment]
CC @mislav and @FooBarWidget if you could elaborate how you've scripted this.

**Comment by FooBarWidget** [comment]
The Passenger release script performs the following operations (simplified explanation):

 1. It creates a tarball.
 2. It clones the Homebrew repository.
 3. It modifies the Passenger formula, replacing the filename and SHA hash with that of the new tarball.
 4. It installs the locally-modified formula and the newly generated tarball, and runs `brew install passenger` to automatically test whether the formula works.
 5. If the test passes, it force-pushes to a Phusion-specific Homebrew fork repo.
 6. It uses [the `hub` command](https://hub.github.com/) to automatically send a pull request from phusion/homebrew to Homebrew/homebrew.
 6. It uploads the tarball to our file server.

**Comment by mislav** [comment]
[One of my scripts is here](https://github.com/rbenv/ruby-build/blob/8c41f0d71453238a16cf896365c359c9ea181671/script/brew-publish). Basically:

1. Obtain the checksum for the tagged archive on GitHub
2. Checkout Homebrew at the latest state of master branch
3. Edit `Library/Formula/NAME.rb` by:
  * Substituting `url` field with new tarball location
  * Substituting `sha256` field with new checksum
4. Push the change to a new branch of your fork
5. Open a PR for Homebrew. I use hub for this, but a generic script could use a manual approach. See below.

```sh
curl -H 'content-type: application/json' \
  -H "authorization: token $GITHUB_TOKEN" \
  https://github.com/repos/OWNER/REPO/pulls -d @- <<JSON
{ "title": "${program_name} ${version}",
  "head": "${fork_name}:${tmp_branch}",
  "base": "master"
}
JSON
```

**Comment by mislav** [comment]
I'd love to see a web service for this that could be triggered by CI or webhooks.

**Comment by zbeekman** [comment]
:+1:

**Comment by luzpaz** [comment]
:+1:

**Comment by mikemcquaid** [comment]
PR opened in https://github.com/Homebrew/homebrew/issues/46580 for the command. We'll consider a web service in future.

**Comment by zbeekman** [comment]
I think you meant https://github.com/Homebrew/homebrew/pull/49848

**Comment by mikemcquaid** [comment]
@zbeekman I did, thanks.

**Comment by mikemcquaid** [comment]
Added as `brew bump-formula-pr` in #49848.
