### ISSUE TITLE
Error: Failure while executing: git pull, on 'brew update'

### ISSUE THREAD

**Issue by LucasKA** [Homebrew/homebrew#46602]
Hey all, I'm having trouble updating homebrew I get

```Error: Failure while executing: git pull  --ff --no-rebase --quiet origin refs/heads/master:refs/remotes/origin/master```

I've looked all around for a fix, read the Tips and FAQ and searched here in issues, and nothing seems to be relevant, or helped.

Any suggestions?

Is there a way to reinstall homebrew without losing everything I've installed?? :/

**Comment by apjanke** [comment]
Do you have a more detailed error message or other diagnostic output? Maybe the output of `brew update -v` that you could post as a gist, along with your `brew doctor` output?

If you have to do a reinstall, you can do a `brew tap > ~/my-taps.txt; brew ls > ~/my-formulae.txt` that will give you a list of all the packages you've installed, and after a clean reinstall, `for tap in $(cat ~/my-taps.txt); do brew tap $tap; done; brew install $(cat ~/my-formulae.txt)` will get all your packages back, albeit with the default options. (And I bet there's a third-party brew command out there somewhere that will let you get a snapshot of your installation state and do a full restore of it.)

**Comment by LucasKA** [comment]
I just did the full reinstall. It wasn't too bad. I had a lot of stuff I didn't use any more, and had other issues to attend to.

FYI Brew Doctor resulted in nothing.
