### ISSUE TITLE
uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX on OS 10.9.5

### ISSUE THREAD

**Issue by wendy2003888** [Homebrew/homebrew#46615]
when i update homebrew, it showed the error below

Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:265:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:205:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:204:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:124:in `<main>'

**Comment by bfontaine** [comment]
Thank you for the report! It should disappear with the next `brew update`. See #42553.
