### ISSUE TITLE
jack formula has berkeley DB v6 as a dependency, but requires v5

### ISSUE THREAD

**Issue by hellominotaur** [Homebrew/homebrew#46628]
Any good reason for this?

If not I can send a pull request to update the jack formula and make a new one for berkeley-db5

**Comment by hellominotaur** [comment]
Apologies anyone who ends up seeing this, I appear to have commits out the wazoo. I'll get this right eventually

**Comment by DomT4** [comment]
Closing in favour of discussing the PR, Thanks!
