### ISSUE TITLE
MultiMarkdown V5.0 formula doesn't include alias scripts

### ISSUE THREAD

**Issue by iandol** [Homebrew/homebrew#46629]
Homebrew MultiMarkdown V4.x formula used to install the [accessory scripts](https://github.com/fletcher/MultiMarkdown-5/tree/master/scripts), but [V5.x update](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/multimarkdown.rb) the scripts are not installed anymore. If the scripts are not to be bottled up from now on, then note the `conflicts_with` are no longer valid.

[The maintainer of MMD has a few extra comments on the V5.0 formula](https://github.com/fletcher/MultiMarkdown-5/issues/1)

> * Perhaps the head modifier should point to the develop branch? The master branch will only be used for official releases. The develop branch will include changes that are uploaded prior to the next release.
> * Does bin.install "multimarkdown" mean to only install the multimarkdown binary? Would something different need to be done to also install the scripts? The make install command for the default system should include the scripts, but I don't remember whether I've tested that or not.
> * Change Multimarkdown to the proper MultiMarkdown. :)
> * The "conflicts_with" markers only make sense if the scripts are being installed. Otherwise there are no conflicts.

**Comment by iandol** [comment]
@hendrikstier was the original author of the improvements for v5.0

**Comment by hendrikstier** [comment]
Would you happen to have time to extend the formula with the relevant tests?

**Comment by iandol** [comment]
I don't know enough about formulae to be anything other than dangerous I'm sorry. You want tests to check for the scripts? The mmd* scripts are really just a wrapper to pass specific commandline arguments, so `mmd2odf infile` runs `markdown -b -t odf infile` and writes to infile.fodt rather than STDOUT. So I'm not sure what tests you deem necessary. Personally I'm happy to accept that scripts are now not installed, or even better would be a way to optionally install the scripts, but no idea how a formula/bottle could handle that at all.

**Comment by hendrikstier** [comment]
No problem. I think I will start by testing the presence of the scripts at the right place. I will perform this test for every accessory script of the "script"-subdirectory you referred to in your original post.

Testing the correct functionality of the individual scripts should be part of the multimarkdown-project, so I'd say, we stick to the presence test and maybe add a check of the permissions, ensuring the shell scripts are executable.
