### ISSUE TITLE
carthage failed to build on 10.11.1

### ISSUE THREAD

**Issue by miguelarauj1o** [Homebrew/homebrew#46634]
Gist about debbuging version: https://gist.github.com/05d01e04e0b92ca4bbd7.git
Homebrew version: __Homebrew 0.9.5 (git revision 5d09d; last commit 2015-10-07)__

**Comment by zbeekman** [comment]
@miguelarauj1o your gist is missing

**Comment by DomT4** [comment]
>  last commit 2015-10-07)

You should `brew update`. I suspect that will be your problem here, since Carthage expects certain Swift versions.

**Comment by miguelarauj1o** [comment]
@DomT4, after ```brew update```, carthage was installed. Thanks!
