### ISSUE TITLE
diffoscope - requires .../libexec/setuptools in PYTHONPATH

### ISSUE THREAD

**Issue by MatthewHannigan** [Homebrew/homebrew#46659]
I got 
```
$ diffoscope
Traceback (most recent call last):
  File "/usr/local/Cellar/diffoscope/42/libexec/bin/diffoscope", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'
```

I fixed this by adding (prepending) `/usr/local/Cellar/python3/3.5.0/libexec/setuptools` to PYTHONPATH in the `diffoscope` shell frontend.

**Comment by mikemcquaid** [comment]
I can't reproduce this. Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by DomT4** [comment]
Let us know if we can help further here, Thanks!
