### ISSUE TITLE
net-snmp build failed on mac

### ISSUE THREAD

**Issue by lscgzwd** [Homebrew/homebrew#46653]
ops git:(crm) ✗ brew install php70-intl php70-snmp
Warning: homebrew/php/php70-intl-7.0.0 already installed
==> Installing php70-snmp from homebrew/homebrew-php
==> Installing dependencies for homebrew/php/php70-snmp: net-snmp
==> Installing homebrew/php/php70-snmp dependency: net-snmp
==> Downloading https://downloads.sourceforge.net/project/net-snmp/net-snmp/5.7.3/net-snmp-5.7.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/net-snmp-5.7.3.tar.gz
==> ./configure --disable-debugging --prefix=/usr/local/Cellar/net-snmp/5.7.3 --enable-ipv6 --with-defaults --with-persistent-directory=/usr/local/var/db/net-snmp --with-logfile=/us
==> make
Last 15 lines from /Users/lushuncheng/Library/Logs/Homebrew/net-snmp/02.make:
        ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
openssl/openssl_md5_local.h:118:11: note: expanded from macro 'R1'
        a=ROTATE(a,s); \
                 ^
openssl/openssl_md32_common.h:168:19: note: expanded from macro 'ROTATE'
                                : "I"(n), "0"(a)        \
                                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
20 errors generated.
make[1]: *** [openssl/openssl_sha1.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [openssl/openssl_md5.lo] Error 1
libtool: compile:  clang -I../include -I. -I../snmplib -I/usr/local/ssl/include -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -g -O2 -Udarwin15 -Ddarwin15=darwin15 -c snmpusm.c -o snmpusm.o >/dev/null 2>&1
make: *** [subdirs] Error 1

READ THIS: https://git.io/brew-troubleshooting

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-php#2629

**Comment by DomT4** [comment]
Whoops, I can't read. The failure was on the dependency rather than the non-core formula, Sorry! Can you do a `brew gist-logs net-snmp`? Thanks!

**Comment by lscgzwd** [comment]
➜  swooleframework git:(master) brew gist-logs net-snmp




https://gist.github.com/cda402230c2f852159ae

**Comment by lscgzwd** [comment]
I have run the command , it shows me one url, but i can not open that, ssl error.

**Comment by DomT4** [comment]
The OpenSSL built in `/usr/local` is the problem. You'll need to remove that, or move it elsewhere temporarily:

https://gist.github.com/anonymous/cda402230c2f852159ae#file-00-doctor-out-L10-L11
https://gist.github.com/anonymous/cda402230c2f852159ae#file-00-doctor-out-L17-L18
https://gist.github.com/anonymous/cda402230c2f852159ae#file-00-doctor-out-L130-L208
https://gist.github.com/anonymous/cda402230c2f852159ae#file-00-doctor-out-L231-L242

**Comment by lscgzwd** [comment]
➜  swooleframework git:(master) brew uninstall --force openssl
Uninstalling openssl... (465 files, 17M)
➜  swooleframework git:(master) brew install php70-snmp       
==> Installing php70-snmp from homebrew/homebrew-php
==> Installing dependencies for homebrew/php/php70-snmp: openssl, net-snmp
==> Installing homebrew/php/php70-snmp dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2e.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/openssl-1.0.2e.el_capitan.bottle.tar.gz
==> Pouring openssl-1.0.2e.el_capitan.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2e: 465 files, 17M
==> Installing homebrew/php/php70-snmp dependency: net-snmp
==> Downloading https://downloads.sourceforge.net/project/net-snmp/net-snmp/5.7.3/net-snmp-5.7.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/net-snmp-5.7.3.tar.gz
==> ./configure --disable-debugging --prefix=/usr/local/Cellar/net-snmp/5.7.3 --enable-ipv6 --with-defaults --with-persistent-directory=/usr/local/var/db/net-snmp --with-logfile=/us
==> make
Last 15 lines from /Users/lushuncheng/Library/Logs/Homebrew/net-snmp/02.make:
        ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
openssl/openssl_md5_local.h:118:11: note: expanded from macro 'R1'
        a=ROTATE(a,s); \
                 ^
openssl/openssl_md32_common.h:168:19: note: expanded from macro 'ROTATE'
                                : "I"(n), "0"(a)        \
                                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
20 errors generated.
make[1]: *** [openssl/openssl_sha1.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [openssl/openssl_md5.lo] Error 1
libtool: compile:  clang -I../include -I. -I../snmplib -I/usr/local/ssl/include -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -g -O2 -Udarwin15 -Ddarwin15=darwin15 -c snmpusm.c -o snmpusm.o >/dev/null 2>&1
make: *** [subdirs] Error 1

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
net-snmp build failed on mac https://github.com/Homebrew/homebrew/issues/46653

**Comment by lscgzwd** [comment]
openssl in /usr/local is built by brew .

**Comment by DomT4** [comment]
Your `gist-logs` disagree. We keep track of `keg_only` formulae that have been linked for this sort of reason, but there's no `doctor` warning which means it's not ours installed there. OpenSSL by default isn't linked by Homebrew into `/usr/local`.

**Comment by lscgzwd** [comment]
thanks, I use homebrew's openssl replace my openssl, it work

**Comment by mikemcquaid** [comment]
Thanks for letting us know @lscgzwd.
