### ISSUE TITLE
Agda: Broken Emacs mode

### ISSUE THREAD

**Issue by mietek** [Homebrew/homebrew#46678]
[PR#45597](https://github.com/Homebrew/homebrew/pull/45597) breaks Agda’s included Emacs mode by introducing the following change:
```diff
+      elisp.install Dir["#{share}/*/Agda-#{version}/emacs-mode/*"]
```

CC @dunn @mikemcquaid 

### Before the change

Agda users are [expected to](https://github.com/agda/agda#installing-agda) set up the Emacs mode by adding the following code to their `.emacs` file:
```elisp
(load-file (let ((coding-system-for-read 'utf-8))
                (shell-command-to-string "agda-mode locate")))
```

With the 2.4.2.4 version of the Agda formula, `agda-mode locate` returns the following path:
```
/usr/local/Cellar/agda/2.4.2.4/share/x86_64-osx-ghc-7.10.2/Agda-2.4.2.4/emacs-mode/agda2.el
```
The Emacs mode is installed at the expected path:
```
$ ls /usr/local/Cellar/agda/2.4.2.4/share/x86_64-osx-ghc-7.10.2/Agda-2.4.2.4/emacs-mode/
agda-input.el       agda2-abbrevs.elc   agda2-mode.el       agda2-queue.elc     annotation.el       eri.elc
agda-input.elc      agda2-highlight.el  agda2-mode.elc      agda2.el            annotation.elc
agda2-abbrevs.el    agda2-highlight.elc agda2-queue.el      agda2.elc           eri.el
```

### After the change

Opening an Agda file in Emacs results in the following message:
```
Warning (initialization): An error occurred while loading `/Users/mietek/.emacs':

File error: Cannot open load file, no such file or directory, /usr/local/Cellar/agda/2.4.2.4_1/share/x86_64-osx-ghc-7.10.2/Agda-2.4.2.4/ema\
cs-mode/agda2.el
```

The path returned by `agda-mode locate` is no longer correct:
```
/usr/local/Cellar/agda/2.4.2.4_1/share/x86_64-osx-ghc-7.10.2/Agda-2.4.2.4/emacs-mode/agda2.el
```
The Emacs mode is no longer installed at the expected path:
```
$ ls /usr/local/Cellar/agda/2.4.2.4_1/share/x86_64-osx-ghc-7.10.2/Agda-2.4.2.4/emacs-mode/
ls: /usr/local/Cellar/agda/2.4.2.4_1/share/x86_64-osx-ghc-7.10.2/Agda-2.4.2.4/emacs-mode/: No such file or directory
```
Instead, it is installed at a Homebrew-specific path:
```
$ ls /usr/local/share/emacs/site-lisp/agda
agda-input.el       agda2-abbrevs.elc   agda2-mode.el       agda2-queue.elc     annotation.el       eri.elc
agda-input.elc      agda2-highlight.el  agda2-mode.elc      agda2.el            annotation.elc
agda2-abbrevs.el    agda2-highlight.elc agda2-queue.el      agda2.elc           eri.el
```

**Comment by dunn** [comment]
Yeah, I didn't test this well.  Would it work to install symlinks into `elisp` instead?

Ultimately Agda should allow the install location of the elisp files to be configurable.  If you have the opportunity to report that upstream I'd be very grateful!

**Comment by mietek** [comment]
I don’t actually use Emacs very often, which is why I only discovered this problem today.  Can you tell me what is the purpose of installing things into `/usr/local/share/emacs/site-lisp`?  If the intention is for Homebrewed Emacs to load such things automatically, then why doesn’t this happen?

**Comment by mietek** [comment]
I found that `homebrew-emacs` users are [expected to](https://github.com/Homebrew/homebrew-emacs#configuration) add the following code to their `.emacs` file:
```elisp
(let ((default-directory "/usr/local/share/emacs/site-lisp/"))
  (normal-top-level-add-subdirs-to-load-path))
```
I’ve tried this, with the Agda mode installed at `/usr/local/share/emacs/site-lisp/agda`, but the Agda mode didn’t automatically load. Any ideas why?

**Comment by dunn** [comment]
Not yet, sorry. I'll take a closer look this evening.

**Comment by mietek** [comment]
Thanks.  For now, I see two methods to fix this:

1.  Revert the change.  Keep the Agda mode where Agda expects it to be.

2.  Keep the change.  Add a symlink, such as the following:
    ```
    $ pwd
    /usr/local/Cellar/agda/2.4.2.4_1
    $ ln -sf ../../emacs/site-lisp/agda \
        share/x86_64-osx-ghc-7.10.2/Agda-2.4.2.4/emacs-mode
    ```

Without knowing the purpose of the change, I am inclined to keep things simple, and choose the first method.

**Comment by dunn** [comment]
What steps produce this error?
```
Warning (initialization): An error occurred while loading `/Users/mietek/.emacs':

File error: Cannot open load file, no such file or directory, /usr/local/Cellar/agda/2.4.2.4_1/share/x86_64-osx-ghc-7.10.2/Agda-2.4.2.4/ema\
cs-mode/agda2.el

**Comment by mietek** [comment]
@dunn: Opening an Agda file, with the Agda mode set up.

**Comment by dunn** [comment]
OK, got it.  Sorry for being dense, it's been a long week.

I'm testing a PR to symlink them now.  But I might pester the developers about changing how they install agda-mode.  `share/emacs/site-lisp` is a pretty standard location; a lot of GNU projects have a `--with-lispdir` configure option that defaults there.  If they followed that convention they could just say "add `/usr/local/share/emacs/site-lisp/agda` to your load-path", instead of needing `agda-mode locate` because the current path is so long.

**Comment by mietek** [comment]
Thanks.  I think the way they do things is to minimise the system administration friction for academics.
