### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by AWKehoe** [Homebrew/homebrew#46689]
I know you said it was unstable but .....
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
READ THIS: https://git.io/brew-troubleshooting

$ brew linkapps cpp-ethereum
Error: No such keg: /usr/local/Cellar/cpp-ethereum

==> Verifying installation
 ✘  Eth is missing

**Comment by AWKehoe** [comment]
earlier log errors....

++++++++++++++++++++++++++++++++++++++++++++++++++++
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/private/tmp/argtable20151205-15107-ihv4ce/argtable2-13':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details.

**Comment by mistydemeo** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Have you read the information in this guide? Can you provide the `brew gist-logs` output requested there?

**Comment by AWKehoe** [comment]
Don't worry its an issue with Ethererum installation. Assume you don't solve these issues?

**Comment by AWKehoe** [comment]
I assume you are not ethererum support?

**Comment by AWKehoe** [comment]
brew doctor output

Warning: Xcode 7 lacks the 10.10 SDK which can cause some builds to fail.
We recommend installing the Command Line Tools with:
  xcode-select --install
to resolve this issue.

**Comment by DomT4** [comment]
That'll be the issue. I'd recommend doing that for now as a workaround, but Misty is working on something longer-term in [this PR](https://github.com/Homebrew/homebrew/pull/46682) which you may wish to track.
