### ISSUE TITLE
Outdated GCC

### ISSUE THREAD

**Issue by Marqin** [Homebrew/homebrew#46702]
Hi,
Homebrew offers only GCC 5.2, and newest released GCC is [5.3](https://gcc.gnu.org/gcc-5/).
Is it possible to update it soon? It has many new features ( like support for Filesystem TS in C++ ).

**Comment by UniqMartin** [comment]
There are already open PRs (#46693, #46693) to address that and they are very likely to be merged soon. Please be patient!

**Comment by Marqin** [comment]
You mean #46670

**Comment by UniqMartin** [comment]
Indeed, silly copy-&-paste error. Thanks for the correction!

**Comment by zbeekman** [comment]
I think #446670 is good to go... just pending review by folks from Homebrew
