### ISSUE TITLE
Golang cross-compiling toolkit

### ISSUE THREAD

**Issue by chillum** [Homebrew/homebrew#46700]
Go formula up to 1.5 had `--with-cc-common` and `--with-cc-all` flags, that were used to set up a cross-compilation environment (a very handy thing).

For some case this has been dropped in latest version of Go formula.

**Comment by chillum** [comment]
[the drop commit](https://github.com/Homebrew/homebrew/commit/7915be4983f49f35f59bf6f5b59cd9ef5b82164e#diff-27f21d87482d9ad2e6ba3776c1bb6d95)

it's a pity, I really need this. will need to build golang by hand now.

**Comment by chillum** [comment]
oops, sorry for the panic.

Go 1.5+ does not need this, cross-compilation still works.

Closing this issue.

**Comment by DomT4** [comment]
Yeah, it happens magically now without needing to tell it what to build during compile: http://dave.cheney.net/2015/03/03/cross-compilation-just-got-a-whole-lot-better-in-go-1-5
