### ISSUE TITLE
nokogiri gem won't install on OS X El Capitan due to SIP

### ISSUE THREAD

**Issue by rgoldberg** [Homebrew/homebrew#46719]
nokogiri gem won't install on OS X El Capitan due to SIP, because it tries to write to:

`/usr/bin/nokogiri`

Which SIP won't allow.

Please write to `/usr/local/bin/nokogiri` instead.

In fact, to properly handle SIP, all taps, casks, bottles, whatever, should write to `/usr/local/bin` instead of `/usr/bin`

**Comment by bfontaine** [comment]
Which formula are you refering to? Homebrew doesn’t provide any `nokogiri` formula.

**Comment by DomT4** [comment]
Nothing on our side should be attempting to touch `/usr` directly at all. We only write into `/usr/local` or your choice of `HOMEBREW_PREFIX`.

**Comment by chdiza** [comment]
Possibly some gem installed using the `gem` that comes with Homebrew's `ruby` is such that it requires nokogiri but also is misconfigured wrt where to put it.

**Comment by the-real-tokai** [comment]
I'm still on Yosemite here, but I noticed that by default gems are installed into `/usr/bin` (this has nothing to do with Homebrew, of course, but is the default for ruby/gem provided by OS X). I'm no ruby/gem expert, but in preparation of the update to El Capitan I simply set up a `.gemrc` which changes the default gem installation path:

```
$ cat ~/.gemrc 
gem:
 --bindir /usr/local/bin
```

and then moved the already installed gems manually from `/usr/bin` into `/usr/local/bin`. I assume the ruby/gem provided with 10.11 will default to a safe (non SIP-protected) location. But perhaps a user config file can overrule this… maybe check that?

**Comment by mistydemeo** [comment]
Apple did configure the version of Rubygems installed with the OS Ruby to fix this; from `/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/defaults.rb`:

```ruby
  def self.default_bindir
    if defined? RUBY_FRAMEWORK_VERSION then # mac framework support
      '/usr/local/bin'
    else # generic install
      ConfigMap[:bindir]
    end
  end
```

If this isn't working for you, I wonder if either a) a copy from a prerelease is left over, b) a copy from an older OS X is left over, c) another configuration file is overriding this.

**Comment by rgoldberg** [comment]
Sorry, I have an update script that updates brew, gem, and some other things.

I accidentally read nokogiri as being from brew, but it was from gem.

I'll contact them.

**Comment by mikemcquaid** [comment]
You can just do `gem install --user` too to install into your $HOME.

**Comment by rgoldberg** [comment]
Thanks for all the suggestions.

Busy with work right now, but I'll investigate them next week, or so.
