### ISSUE TITLE
Unable to install Homebrew on mac

### ISSUE THREAD

**Issue by soluna1** [Homebrew/homebrew#46717]
I've tried to install Homebrew several time with the information provided in the web but it fails during the process as it is unable to access and/or to install several parts. I don't know what is wrong. It says that Homebrew is already installed but any brew command works. I'm on Yosemite 10.10.5. Help please!!!

**Comment by DomT4** [comment]
Can you provide terminal readout of the failure steps so we know where it's failing, etc?

**Comment by soluna1** [comment]
This is what I've got when trying to install homebrew:

$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
It appears Homebrew is already installed. If your intent is to reinstall you
should do the following before running this installer again:
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
The current contents of /usr/local are bin etc include lib share /usr/local.bak/bin /usr/local.bak/include /usr/local.bak/lib /usr/local.bak/man /usr/local.bak/share .git

and if I've try to run any brew command:
$ brew --version
-bash: brew: command not found

**Comment by DomT4** [comment]
The `.git` is the problem; It's one of the things we check. You can do `rm -r /usr/local/.git` to resolve that.

**Comment by soluna1** [comment]
This is the result, still failing:
$ rm -r /usr/local/.git
$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/man/man1/brew.1

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
fatal: unable to access 'https://github.com/Homebrew/homebrew/': Couldn't connect to server
Failed during: git fetch origin master:refs/remotes/origin/master -n --depth=1

**Comment by DomT4** [comment]
Well, that's a new issue at least. If you manually do something like:

```shell
git clone https://github.com/Homebrew/homebrew.git /tmp/homebrew
```
Does it clone okay?

**Comment by soluna1** [comment]
I'm afraid not:
$ git clone https://github.com/Homebrew/homebrew.git /tmp/homebrew
Cloning into '/tmp/homebrew'...
fatal: unable to access 'https://github.com/Homebrew/homebrew.git/': Couldn't connect to server

**Comment by DomT4** [comment]
Hmm. That implies either a local connection issue, some kind of firewall blocking, or a local configuration issue.

Do you have a `~/.gitconfig` at all? Which country are you based in?

**Comment by soluna1** [comment]
It answers:
~/.gitconfig
-bash: /Users/solunasalles/.gitconfig: Permission denied

I'm Spain

**Comment by soluna1** [comment]
*I'm in Spain

**Comment by DomT4** [comment]
Well, we can probably rule out country-level firewall blocking with Spain at least.

Does `ls -l ~/.gitconfig` confirm that file exists?

**Comment by soluna1** [comment]
I've got this:
$ ls -l ~/.gitconfig
-rw-r--r--  1 solunasalles  staff  77 Nov 30 19:23 /Users/solunasalles/.gitconfig

**Comment by soluna1** [comment]
Despite that, I can't find the gitconfig file, is it named in another way?

**Comment by DomT4** [comment]
It may not be visible in the finder. I can't remember if hidden files are hidden by default as well as hidden folders. You can probably see what is in it by doing `cat ~/.gitconfig`.

**Comment by soluna1** [comment]
$ cat ~/.gitconfig
[http]
	proxy = http://proxy.com:port
[https]
	proxy = http://proxy.com:port
[user]
	name = solunasalles

**Comment by soluna1** [comment]
Hi DomT4 have you find a possible solution to this issue?? Thanks for your interest and help

**Comment by DomT4** [comment]
It's possible the https => http proxy redirect is problematic for Github. If you temporarily comment out or remove the `proxy = http://proxy.com:port` line under `[https]` does the problem resolve at all?

**Comment by soluna1** [comment]
Sorry, but I don't know how to change the proxy, could you guide a bit?? thanks,

**Comment by mikemcquaid** [comment]
@soluna1 Try to just remove those lines from your `~/.gitconfig` (or just delete it)

**Comment by soluna1** [comment]
Thanks Mike, but I can't find the .gitconfig file in the computer, is it hidden somewhere?? can I just type rm  ~/.gitconfig??

**Comment by DomT4** [comment]
> can I just type rm ~/.gitconfig??

Yes.

**Comment by soluna1** [comment]
ok, I did, and then $ git clone https://github.com/Homebrew/homebrew.git /tmp/homebrew, it seems to be doing something. Let's see. Thanks both of you for your help. :)

**Comment by soluna1** [comment]
Cloning into '/tmp/homebrew'...
remote: Counting objects: 313376, done.
remote: Compressing objects: 100% (129/129), done.
remote: Total 313376 (delta 88), reused 0 (delta 0), pack-reused 313247
Receiving objects: 100% (313376/313376), 62.31 MiB | 639.00 KiB/s, done.
Resolving deltas: 100% (233778/233778), done.
Checking connectivity... done.

this is the result, is Homebrew installed now?

**Comment by DomT4** [comment]
You'll need to run the actual installer script. My suggestion on using `/tmp` was just a way to test without having to go through all that every time.

Go through:

```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```
And that should work now.

**Comment by soluna1** [comment]
Yes, yes!!!!!
From https://github.com/Homebrew/homebrew
 * [new branch]      master     -> origin/master
HEAD is now at 7b30c6f storm 0.10.0
==> Installation successful!
==> Next steps
Run `brew help` to get started

THANKSSSSS

**Comment by DomT4** [comment]
:+1:. Let us know if we can help further.
