### ISSUE TITLE
[H2 formula] h2.sh contains dos line endings 

### ISSUE THREAD

**Issue by 1Mhz** [Homebrew/homebrew#46728]
Error:
/usr/local/bin/h2: bin/h2.sh: /bin/sh^M: bad interpreter: No such file or directory
Fix:
change line endings by executing following commands: 
cat h2.sh | col -b >h2TMP.sh
mv h2TMP.sh h2.sh

**Comment by DomT4** [comment]
Closing in favour of the https://github.com/Homebrew/homebrew/pull/46747 PR. Thanks for letting us know about the problem!
