### ISSUE TITLE
zbar failed to build on 10.10.5

### ISSUE THREAD

**Issue by m-mizutani** [Homebrew/homebrew#46724]
% brew install zbar --disable-pthread
==> Downloading https://downloads.sourceforge.net/project/zbar/zbar/0.10/zbar-0.10.tar.bz2
Already downloaded: /Library/Caches/Homebrew/zbar-0.10.tar.bz2
==> Patching
patching file zbar/jpeg.c
==> ./configure --prefix=/usr/local/Cellar/zbar/0.10_1 --without-python --without-qt --disable-video --without-gtk --without-x
Last 15 lines from /Users/mizutani/Library/Logs/Homebrew/zbar/01.configure:
checking for library containing clock_gettime... no
checking for ld used by GCC... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for shared library run path origin... done
checking for iconv... no, consider installing GNU libiconv
checking poll.h usability... no
checking poll.h presence... no
checking for poll.h... no
checking pthread.h usability... no
checking pthread.h presence... no
checking for pthread.h... no
configure: error: in `/private/tmp/zbar20151206-45085-r8lybn/zbar-0.10':
configure: error: test for pthread support failed!
configure --disable-pthread to skip threaded support.
See `config.log' for more details.

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
zbar: Add support to build with Qt4 support https://github.com/Homebrew/homebrew/pull/35993

**Comment by mikemcquaid** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please do.

**Comment by apjanke** [comment]
There's no `--disable-pthread` option in the Homebrew `zbar` formula, so it will have no effect. `pthread.h` should be present, so this could be an Xcode configuration issue.

**Comment by DomT4** [comment]
Let us know if we can help further here, Thanks!
