### ISSUE TITLE
El Capitan Homebrew fresh install error: Bad CPU type in executable

### ISSUE THREAD

**Issue by wowpages** [Homebrew/homebrew#46723]
I'm trying to install Homebrew for the first time on a mid 2012 MacBook Pro Retina running El Capitan. Xcode is current, but I just get "Bad CPU type in executable" and can't get any further.

MacBook-Pro:~ Steve$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
MacBook-Pro:~ Steve$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
-bash: /usr/local/bin/ruby: Bad CPU type in executable

**Comment by mistydemeo** [comment]
It looks like you have a copy of Ruby installed whose architecture is unsupported by your version of OS X. (For example, it might be a PowerPC binary.) Try moving it out of the way, or removing it, and then running the command again.

**Comment by wowpages** [comment]
I tried removing it but then it won't run at all because ruby is no longer there:

Steves-MacBook-Pro:bin Steve$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
-bash: /usr/local/bin/ruby: No such file or directory

get info shows the "Created" date as February 1, 2008 at 4:43 PM. It seems like I could just replace it with a newer version but I can't find a replacement anywhere.

I did try this: curl -L https://get.rvm.io | bash -s stable --auto-dotfiles --autolibs=enable --ruby

but that just gives me this:

About to install Homebrew, press `Enter` for default installation in `/usr/local`,
type new path if you wish custom Homebrew installation (the path needs to be writable for user)
: Requirements installation failed with status: 1.

**Comment by DomT4** [comment]
Does `/usr/bin/ruby` not exist?

**Comment by wowpages** [comment]
It did exist but I tried removing it per mistydemeo's suggestion. I put it back, but Get Info says it's from 2008. I can't find how to download or install a newer version. I think that's probably the problem.

**Comment by mistydemeo** [comment]
OS X comes with a version of Ruby that can run the Homebrew installer, so don't worry about installing a new version! If you remove `/usr/local/bin/ruby` you should be able to run the Homebrew installer.

**Comment by mistydemeo** [comment]
I see you say it won't run at all after: is there no `/usr/bin/ruby`?

**Comment by wowpages** [comment]
@mistydemeo Sorry - I misread /usr/bin/ruby as /usr/local/bin/ruby in your earlier message. I could swear it didn't work before when I removed the local ruby, but I tried it again and it worked! So thank you!!

**Comment by mistydemeo** [comment]
You're welcome! Glad it's working!
