### ISSUE TITLE
brew install wine - libusb timeout

### ISSUE THREAD

**Issue by flareofghast** [Homebrew/homebrew#46725]
Hi, I am trying to install wine but it times out trying to download libusb.

````
$ brew install wine
==> Installing dependencies for wine: libusb, libusb-compat, fontconfig, 
==> Installing wine dependency: libusb
==> Downloading https://downloads.sourceforge.net/project/libusb/libusb-1.0/libu

curl: (7) Failed to connect to downloads.sourceforge.net port 443: Operation timed out
Error: Failed to download resource "libusb"
Download failed: https://downloads.sourceforge.net/project/libusb/libusb-1.0/libusb-1.0.20/libusb-1.0.20.tar.bz2
````

I just used ````brew install libusb```` to try that method, which installed a libusb but the wine install didn't use it.

**Comment by DomT4** [comment]
May well have been a transient issue; SF is prone to periods of downtime. Wine requires the installation of universal dependencies, so doing it manually you'd want to do `brew install libusb --universal`.

**Comment by flareofghast** [comment]
Thanks, will keep that in mind. Yes, it did end up being a SF issue.
