### ISSUE TITLE
How to brew upgrade with a local file

### ISSUE THREAD

**Issue by lipangit** [Homebrew/homebrew#46739]
Hello
I come from china ,it is very slow to connect outside.
example I want to brew upgrade gradle , it will timeout ,
because https://downloads.gradle.org/distributions/gradle-2.9-bin.zip can not connect it.
Then I download it in advance ,the question is lite title 
can I use : brew upgrade gradle -WithTheFile /localpath/gradle-2.9-bin.zip

**Comment by DomT4** [comment]
No, but you can do something like:

```
brew --cache gradle -s
```
to get the filename we expect, and then `mv /localpath/gradle-2.9-bin.zip /path/from/above/command`.

Alternatively:

```
mv /localpath/gradle-2.9-bin.zip `brew --cache gradle -s`
```

**Comment by DomT4** [comment]
Let us know if that doesn't resolve your query. Thanks!

**Comment by lipangit** [comment]
Haha it is work,It can also upgrade other package,thank you for you warm heart
