### ISSUE TITLE
homebrew updates gcc but is not found

### ISSUE THREAD

**Issue by JeremyCavanagh** [Homebrew/homebrew#46733]
Recently I saw a notice about "Nemo" in the julia-users digest and followed the links to install. Unfortunately, it went a long way and then failed when gcc was searched for and not found. After some ferreting around and your recent update to 5.3.0, I discovered the problem was that homebrew updated gcc, but the reference alias in /usr/local/bin was gcc-5 and not gcc. I corrected the problem with a duplicate and rename to gcc. I don't know if this is a problem with my system or an error in the formula. If it is the latter I'm sure that it is a simple fix.

**Comment by mikemcquaid** [comment]
It's intentional and not an error.

**Comment by JeremyCavanagh** [comment]
Okay thanks for the rapid reply
