### ISSUE TITLE
Petsc install fails

### ISSUE THREAD

**Issue by bknaepen** [Homebrew/homebrew#46744]
Hello,
When trying to install petsc a patch for superlu43 fails because of a SHA256 mismatch (see below).
Is it safe to change the SHA signature in the formula to override this issue?

Thanks,
Bernard.

brew install petsc
==> Installing petsc from homebrew/homebrew-science
==> Installing dependencies for homebrew/science/petsc: superlu43, superl
==> Installing homebrew/science/petsc dependency: superlu43
==> Downloading https://homebrew.bintray.com/bottles-science/superlu43-4.3.el_ca
######################################################################## 100.0%
==> Pouring superlu43-4.3.el_capitan.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Conflicts with superlu

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/superlu43/lib
    CPPFLAGS: -I/usr/local/opt/superlu43/include

==> Summary
🍺  /usr/local/Cellar/superlu43/4.3: 402 files, 11M
==> Installing homebrew/science/petsc dependency: superlu_dist
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://crd-legacy.lbl.gov/~xiaoye/SuperLU/superlu_dist_4.1.tar.g
######################################################################## 100.0%
==> Downloading https://bitbucket.org/petsc/pkg-superlu_dist/commits/2faf8669a2b
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 09dcd7de83ef9d2590465742df76753cb7c61bfe8e7819c02613d9bcf20ed255
Actual: 67e2966e1a9b4e3471374d1e720946c2ef34403d00e796767b51718e4d50604f
Archive: /Library/Caches/Homebrew/superlu_dist--patch-09dcd7de83ef9d2590465742df76753cb7c61bfe8e7819c02613d9bcf20ed255
To retry an incomplete download, remove the file above.

**Comment by dunn** [comment]
This issue was moved to Homebrew/homebrew-science#3097
