### ISSUE TITLE
`brew update` produces 'Error: The /usr/local directory is not writable'

### ISSUE THREAD

**Issue by AbdiSaeed** [Homebrew/homebrew#46755]
I have just tried to run `brew update` and am getting this error
```
Error: The /usr/local directory is not writable.
Even if this directory was writable when you installed Homebrew, other
software may change permissions on this directory. Some versions of the
"InstantOn" component of Airfoil are known to do this.

You should probably change the ownership and permissions of /usr/local
back to your user account.
  sudo chown -R $(whoami):admin /usr/local
```

I don't feel comfortable changing system file permissions and want to know if the suggested solution is safe to do and anything I should be aware of before changing permissions.

Thanks

**Comment by DomT4** [comment]
> I don't feel comfortable changing system file permissions

By default, there's nothing in `/usr/local` on OS X. Anything in there will have been placed there by you, a third-party software, or Apple migrating third-party software from `/usr/bin` to `/usr/local/bin` on update to El Capitan. There's nothing there on behalf of the system, ever.

The command is safe enough to run, and you can undo the change by issuing another `chown` command later if you decide against it.

Some things you may wish to be wary of:

* If you've installed third-party utilities in `/usr/local` they'll become user:admin owned.
* Some tools get grumpy about this.
* If you haven't installed anything non-brew in there, the above two points are null.
* Homebrew does require `/usr/local` to be user writable. If you don't want it to be, you should reinstall Homebrew elsewhere.

**Comment by AbdiSaeed** [comment]
Thanks.

I wasn't aware of this location in the system so I haven't explicitly installed anything in /usr/local myself. Apart, from the brew files, I don't know what these other files are doing. Could be as you said placed there during El Capitan update. Just out of interest, do you know if they safe to delete at all?
![screen shot 2015-12-07 at 11 08 13](https://cloud.githubusercontent.com/assets/11387114/11625437/ec60cb90-9cd2-11e5-8743-f32d3e496bf5.png)
. Anyway, I have changed permissions of the directory and managed to update brew. Thanks again.

**Comment by DomT4** [comment]
`git`, `heroku`, `foreman` and `ssl` will all have been installed by you or a piece of third-party software. All should be safe to remove as desired; they won't be in use by the system, so if you don't know why they are there, should be alright to remove 'em.

Let us know if we can help further!
