### ISSUE TITLE
Make Artifactory bottle

### ISSUE THREAD

**Issue by jainishshah17** [Homebrew/homebrew#46778]
Please convert Artifactory <a href="https://github.com/Homebrew/homebrew/blob/master/Library/Formula/artifactory.rb">Artifactory</a> 
to bottle.

**Comment by DomT4** [comment]
Why? Are you having problems with the from-source installation, or?

**Comment by jainishshah17** [comment]
No, We just decided to make artifactory bottle.

**Comment by DomT4** [comment]
There's no real upside. There's no compile step, so we'd not be saving users that. There's no significant download speed/size difference. The difference to end users is nil, the difference to us is an extra burden on our CI machines and bottle infrastructure. We'd need justification on the change, essentially, to merit the change.

**Comment by jainishshah17** [comment]
how about we request to make it bottle with our next release. will that be ok ?

**Comment by DomT4** [comment]
There'll have to be a reason to bottle it. We haven't really been re-enabling for bottles on request without other reasons. Unless the bottle provides more benefit to end-users than the source download there's no need for one to exist, which is the issue really. I'll let @mikemcquaid comment.

**Comment by mikemcquaid** [comment]
> Unless the bottle provides more benefit to end-users than the source download there's no need for one to exist, which is the issue really.

Agreed, I don't see any advantage here.
