### ISSUE TITLE
awscli: generate and install bash completion scripts 

### ISSUE THREAD

**Issue by xaka** [Homebrew/homebrew#46781]
Hi there!

The main problem here is that https://github.com/aws/aws-cli doesn't come with bash completer, though it comes with zsh (kind of unfair, huh?). I see few options here:

1. go to https://github.com/aws/aws-cli and ask for such completer to be provider (will take a while I assume)
2. while waiting for 1 to happen, generate our own completer and install it using `bash_completer.install`

I'm happy to provide a PR, the only reason I haven't yet is that I couldn't find a good example to generate a file as part of a formula. Should I simply use Ruby's API to work with files? What about extending `#resource` to support `content` attribute when URL isn't provided?

Thanks!

**Comment by mikemcquaid** [comment]
I'd rather we do 1) and wait for an official upstream completion.

**Comment by DomT4** [comment]
Yeah, let's ask upstream here. When one is supplied by them we can add it to the `head` install (if one exists) and then for everyone when the next stable release includes it. Thanks!

**Comment by xaka** [comment]
https://github.com/aws/aws-cli/releases/tag/1.9.16 is finally out with bash completion. Would you mind to integrate it please?

**Comment by mikemcquaid** [comment]
@xaka Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
