### ISSUE TITLE
can't install python3.51  on OS X 10.11.1

### ISSUE THREAD

**Issue by M2shad0w** [Homebrew/homebrew#46797]
### here is the log
 [logpath](https://gist.github.com/anonymous/6c16d0cce2b02d97ffb6)

I have Checked the issue tracker, but don't know how to slove it.
![image](https://cloud.githubusercontent.com/assets/3387446/11660412/052e20ec-9e08-11e5-8bdd-873ea93ee754.png)

**Comment by bfontaine** [comment]
> Warning: Your Xcode (6.4) is outdated
> Please update to Xcode 7.1.1.

You should probably upgrade this before anything.

**Comment by ztomer** [comment]
Fix the permissions:
sudo chown -R $(whoami):admin /usr/local

It's an El-Capitan problem
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md

**Comment by DomT4** [comment]
The error in the provided log isn't a permission problem. It's not even getting to an install stage, and we build in `/tmp` rather than inside the `HOMEBREW_PREFIX`.

**Comment by ztomer** [comment]
My bad.
"brew postinstall python3" failed on my machine, and the error log led here.
Good luck!

**Comment by M2shad0w** [comment]
@bfontaine thanks for replying, you're right. when i upgrade the xcode. all is ok!

**Comment by hsiaoyi0504** [comment]
I meet the same issue
But @ztomer 's reply works for me
I even didn't install xcode
