### ISSUE TITLE
Brew php switcher deleted

### ISSUE THREAD

**Issue by philcook** [Homebrew/homebrew#46808]
Hi,

I am wondering why my Formula has been deleted?

Should I do a pull request to put this back in or has it been deleted for a reason?

**Comment by dunn** [comment]
It's a [homebrew/php](https://github.com/Homebrew/homebrew-php/blob/master/Formula/brew-php-switcher.rb), so I don't think it's ever been in core.

**Comment by philcook** [comment]
Whoops of course my mistake!
