### ISSUE TITLE
brew install libav (x264) permission error on Macbook Pro

### ISSUE THREAD

**Issue by powder366** [Homebrew/homebrew#46800]
anon-159-14:~ $  brew install libav
==> Installing libav dependency: x264
==> Cloning https://git.videolan.org/git/x264.git
Removing invalid repository from cache
/usr/local/Library/ENV/4.3/git:12:in `exec': Permission denied - /usr/local/git (Errno::EACCES)
	from /usr/local/Library/ENV/4.3/git:12:in `exec'
	from /usr/local/Library/ENV/4.3/git:20:in `block in <main>'
	from /usr/local/Library/ENV/4.3/git:19:in `each'
	from /usr/local/Library/ENV/4.3/git:19:in `<main>'
Error: Failed to download resource "x264"
Failure while executing: git clone https://git.videolan.org/git/x264.git /Library/Caches/Homebrew/x264--git

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by powder366** [comment]
Ok, sorry, it works after readin that:-)
