### ISSUE TITLE
mailutils fails to build on 10.9.5 with latest gpgtools install

### ISSUE THREAD

**Issue by liljenstolpe** [Homebrew/homebrew#46823]
I am running 10.9.5 and have the latest gpgtools (GnuPG/MacGPG2  2.0.29), and when I try and install mailutils, the following error stops the install....

─➤  brew install mailutils
==> Downloading http://ftpmirror.gnu.org/mailutils/mailutils-2.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/mailutils-2.2.tar.gz
==> ./configure --without-python --disable-mh --prefix=/usr/local/Cellar/mailuti
==> make install
Last 15 lines from /Users/cdl/Library/Logs/Homebrew/mailutils/02.make:
Making install in libmu_auth
  CC     gsasl.lo
  CC     lbuf.lo
  CC     ldap.lo
  CC     pam.lo
  CC     radius.lo
  CC     sql.lo
  CC     tls.lo
  CC     virtual.lo
  CCLD   libmu_auth.la
grep: /usr/local/MacGPG2/lib/libgpg-error.la: No such file or directory
sed: /usr/local/MacGPG2/lib/libgpg-error.la: No such file or directory
libtool: link: `/usr/local/MacGPG2/lib/libgpg-error.la' is not a valid libtool archive
make[1]: *** [libmu_auth.la] Error 1
make: *** [install-recursive] Error 1

**Comment by DomT4** [comment]
We'll need a full `brew gist-logs mailutils` but I believe we warn about `MacGPG2` installations because it causes so many problems.

**Comment by DomT4** [comment]
I can't reproduce this at all locally. Best thing I can suggest is moving `MacGPG2` out of the way temporarily. It is known to be problematic.
