### ISSUE TITLE
Uninstall deleted my man1, man3, man5, and man7 folders!

### ISSUE THREAD

**Issue by johan718** [Homebrew/homebrew#46827]
As a user / developer, I'd like Homebrew to be more verbose during the uninstall process. Also, Homebrew should not remove folders that were not created by Homebrew.

## Issue
I installed Homebrew on my Mac, ```OS X 10.10.5``` about three nights ago using the code on the site ```brew.sh```:
```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```
##### Homebrew was very verbose which was awesome:
```javascript
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/man/man1/brew.1
==> The following directories will be made group writable:
/usr/local/.
/usr/local/bin
/usr/local/include
/usr/local/lib
/usr/local/share
/usr/local/share/man
/usr/local/share/man/man1
/usr/local/share/man/man3
/usr/local/share/man/man5
/usr/local/share/man/man7
==> The following directories will have their owner set to Johan:
/usr/local/.
/usr/local/bin
/usr/local/include
/usr/local/lib
/usr/local/share
/usr/local/share/man
/usr/local/share/man/man1
/usr/local/share/man/man3
/usr/local/share/man/man5
/usr/local/share/man/man7
==> The following directories will have their group set to admin:
/usr/local/.
/usr/local/bin
/usr/local/include
/usr/local/lib
/usr/local/share
/usr/local/share/man
/usr/local/share/man/man1
/usr/local/share/man/man3
/usr/local/share/man/man5
/usr/local/share/man/man7

Press RETURN to continue or any other key to abort
```
##### When I uninstalled a little earlier this evening, it was not as verbose:
```python
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
Warning: This script will remove:
/Library/Caches/Homebrew/
~/Library/Logs/Homebrew/
/usr/local/.git/
/usr/local/.gitignore
/usr/local/.travis.yml
/usr/local/.yardopts
/usr/local/CODEOFCONDUCT.md
/usr/local/CONTRIBUTING.md
/usr/local/LICENSE.txt
/usr/local/Library/
/usr/local/README.md
/usr/local/SUPPORTERS.md
/usr/local/bin/brew
/usr/local/share/
/usr/local/share/doc/
/usr/local/share/doc/homebrew/
/usr/local/share/man/man1/brew.1
Are you sure you want to uninstall Homebrew? [y/N] y
==> Removing Homebrew installation...
==> Removing empty directories...
==> Homebrew uninstalled!
The following possible Homebrew files were not deleted:
/usr/local/.DS_Store
/usr/local/bin/
/usr/local/include/
/usr/local/lib/
/usr/local/share/
.
(Other output omitted by @johan718)
.
You may consider to remove them by yourself.
You may want to restore /usr/local's original permissions
   sudo chmod 0755 /usr/local
   sudo chgrp wheel /usr/local

```
##### It didn't mention that it had also deleted four of my folders:
```perl
chown: /usr/local/share/man/man1: No such file or directory
chown: /usr/local/share/man/man3: No such file or directory
chown: /usr/local/share/man/man5: No such file or directory
chown: /usr/local/share/man/man7: No such file or directory
```
## Conclusion
If you can confirm this issue, please comment. Overall, I don't think there was any real damage, but it may be something for the coders to look at.

**Comment by UniqMartin** [comment]
Thanks for your report! This is definitely not the intended behavior and I'll try to address that quickly. This is not really going to help, but the script actually told you that it will delete the `/usr/local/share/` directory, though it shouldn't have put that directory in the list in the first place …

**Comment by UniqMartin** [comment]
The issue should be fixed now. Thanks again for your very helpful report @johan718. It made identifying and fixing the bug so much easier!

**Comment by johan718** [comment]
@UniqMartin wow, you're right. I completely missed that!!! I definitely should have been paying more attention. I'm glad I was able to help, though.

Thanks a lot for taking care of the issue. That was pretty fast.

**Comment by johan718** [comment]
@UniqMartin I may be wrong, but I believe ```Homebrew``` created the ```/usr/local/share/doc/``` folder. You may want to leave that in the uninstall process.

I did notice that ```Homebrew``` didn't mention that it was creating the ```/usr/local/share/doc/``` folder on my install. This might be worth checking into as well. If I could help more, I would. I'm just starting to get my feet wet on here.

**Comment by UniqMartin** [comment]
Homebrew created (and thus should remove) `/usr/local/share/doc/homebrew/` because that's were most of our documentation lives, but it shouldn't remove all of `/usr/local/share/doc/` as other software might have placed things in there. However, you'll notice that it also prints `==> Removing empty directories...` and that's where it takes care of removing `/usr/local/share/doc/` if only Homebrew had written to it.

I agree the Installer could mention that it will also create `/usr/local/share/doc/homebrew/`. I'll bring that up with the other maintainers to discuss how verbose we want to be. Thanks for the suggestion!

**Comment by johan718** [comment]
Ok thanks for explaining that @UniqMartin. Makes sense. And thanks again for taking care of this issue.
