### ISSUE TITLE
Path issue with Python (via Homebrew) and httpie?

### ISSUE THREAD

**Issue by victorhooi** [Homebrew/homebrew#46828]
NB: This is possibly either a configuration issue, or an issue with my Homebrew setup.

I have a fresh MBP running OSX 10.11.1 (15B42), with Homebrew installed. I have installed Python 2.7.11 via Homebrew. I then used `pip` to install `httpie`.

However, the binary for `httpie` was placed into:
```
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/http
```

The above directory isn't in my `$PATH`:

Fish
```
victorhooi@victorhooi-macbookpro /u/l/C/p/2/s/python> echo $PATH
/usr/local/git/current/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/sbin
```
Bash:
```
bash-3.2$ env | grep PATH
PATH=/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
```

I'm assuming either the above directory should be put in my `$PATH` (`brew info python` didn't mention anything about this), or there's something wrong with the way that `pip` has installed `httpie`?

**Comment by DomT4** [comment]
Looks likely to be a configuration issue. I can't reproduce here. Did you manually reinstall `pip` or anything, or is everything as-is from a `brew install python` install?

**Comment by tdsmith** [comment]
Can't reproduce and I have no insight, sorry. On the assumption that pip has done something unexpected and not Homebrew, you can try filing against pypa/pip and @-mentioning me. Sorry for the trouble.

**Comment by hackrole** [comment]
Hi, I face the same problem.
First, I install python via
```
brew install python
```
after the I see that the pip and easy install was not install on PATH.

so I install it via:
```
curl https://bootstrap.pypa.io/ez_setup.py -o - | sudo python
easy_install pip
```

after that use `pip install httpie ipython` . not link the http and ipython to the /usr/local/bin.
are there any help?
