### ISSUE TITLE
What to do after xcode is upgraded (to 7.2) ?

### ISSUE THREAD

**Issue by cpraveen** [Homebrew/homebrew#46832]
So I upgraded xcode to 7.2 today and some petsc code does not compile

```
ld: warning: directory not found for option '-L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/lib/darwin'
ld: library not found for -lclang_rt.osx
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: [ex1] Error 1 (ignored)
```

How do I update all homebrew packages that need to be updated due to xcode update ?

Note this is not an OS update, only xcode is updated.

**Comment by DomT4** [comment]
Can you try `brew reinstall petsc -s` please?

**Comment by cpraveen** [comment]
Reinstalling solved the problem. How do I find other packages which are affected by this issue ?

**Comment by DomT4** [comment]
Using them, really. I guess you could run a broad `otool -L` and `grep` for `clang` linkage in your top-level `lib` prefix, but I wouldn't expect this error to be very common.

**Comment by DomT4** [comment]
I've notified upstream (`homebrew/science`) this package needs a revision when possible, but there's other issues holding that up on their end.
