### ISSUE TITLE
Adding DrupalConsole to homebrew

### ISSUE THREAD

**Issue by darol100** [Homebrew/homebrew#46840]
How can we integrate [DrupalConsole](https://github.com/hechoendrupal/DrupalConsole/) with homebrew?

DrupalConsole is a new command line tool for Drupal 8 developers and we will like to add the ability of user downloading using homebrew.

Here is the instruction on how to install DrupalConsole:

```````
php -r "readfile('http://drupalconsole.com/installer');" > drupal.phar

# Accessing from anywhere on your system:
mv drupal.phar /usr/local/bin/drupal
````````````````

If someone can point me to a direction (documentation) on how to write an integration to support DrupalConsole that will be nice.

**Comment by DomT4** [comment]
Probably a decent fit for https://github.com/Homebrew/homebrew-php rather than the core itself. They are likely going to be better able to support the formula request/discussion here.

**Comment by darol100** [comment]
@DomT4 ,

Assuming that this is been integrate to `hombrew-php`, this will still will be available to run  brew normally without any dependecy?. For instance, `brew install drupalconsole` and it will work without need of installing `hombrew-php` in your machine.

I'm not 100% sure how hombrew works that is why I'm asking.

**Comment by bfontaine** [comment]
`homebrew-php` will need to be installed. If it’s not, one can run `brew install homebrew/php/drupalconsole` and it’ll install it automatically.
Once `homebrew-php` is available locally the following works: `brew install drupalconsole`.

**Comment by DomT4** [comment]
Let us know if we can help further here.
