### ISSUE TITLE
configure: error: memcached support requires ZLIB. Use --with-zlib-dir=<DIR> to specify the prefix where ZLIB headers and library are located

### ISSUE THREAD

**Issue by hulupiao** [Homebrew/homebrew#46849]
brew install --HEAD josegonzalez/php/php70-memcached
==> Installing php70-memcached from josegonzalez/php
==> Cloning https://github.com/php-memcached-dev/php-memcached.git
Updating /Library/Caches/Homebrew/php70-memcached--git
==> Checking out branch php7
==> /usr/local/opt/php70/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php70-memcached/HEAD --with-php-config=/usr/local/opt/php70/bin/php-config --
Last 15 lines from /Users/hanjiafeng/Library/Logs/Homebrew/php70-memcached/02.configure:
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable memcached support... yes, shared
checking for libmemcached... yes, shared
checking whether to enable memcached session handler support... yes
checking whether to enable memcached igbinary serializer support... no
checking whether to enable memcached json serializer support... no
checking whether to enable memcached msgpack serializer support... no
checking whether to enable memcached sasl support... yes
checking whether to enable memcached protocol support... no
checking whether to use system FastLZ bibrary... no
checking for ZLIB... yes, shared
checking for pkg-config... /usr/local/opt/pkg-config/bin/pkg-config
checking for zlib location... configure: error: memcached support requires ZLIB. Use --with-zlib-dir=<DIR> to specify the prefix where ZLIB headers and library are located

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/josegonzalez/php/issues

hi,gays
I have a problem like that, please help me.

**Comment by mikemcquaid** [comment]
> READ THIS: https://git.io/brew-troubleshooting
> If reporting this issue please do so at (not Homebrew/homebrew):
> https://github.com/josegonzalez/php/issues

Please do these things, thanks.

**Comment by martinsik** [comment]
Do information on https://git.io/brew-troubleshooting really help to solve this?
Because it didn't for me. I had to:
 1. Install `zlib` using brew.
 2. Edit formula with `brew edit homebrew/php/php70-memcached` and add:

        args << "--with-zlib-dir=#{Formula["zlib"].opt_prefix}"

**Comment by mikemcquaid** [comment]
@martinsik If you don't follow that: we don't have enough information to help.
