### ISSUE TITLE
PyMOL crashes, wrong libpng loaded

### ISSUE THREAD

**Issue by mok0** [Homebrew/homebrew#46856]
My Homebrew version of PyMOL crashes shortly after starting up with following error message:

    Detected 8 CPU cores.  Enabled multithreaded rendering.
    libpng warning: Application built with libpng-1.6.19 but running with 1.5.23
    /usr/local/bin/pymol: line 4: 57181 Segmentation fault: 11  "/usr/local/opt/python/bin/python2.7" "/usr/local/Cellar/pymol/1.7.6.0/libexec/lib/python2.7/site-packages/pymol/__init__.py" "$@"

I am running OS X El Capitan 10.11.1, XQuartz 2.7.8 (xorg-server 1.16.4), and a fully updated and upgraded Homebrew as of today.

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/homebrew-science#3110
