### ISSUE TITLE
Update error:brew update,command conflict.

### ISSUE THREAD

**Issue by mappy81** [Homebrew/homebrew#46850]
$ brew update
$ brew doctor

Warning: You have external commands with conflicting names.

Found command `brew-cask` in following places:
    /usr/local/bin/brew-cask
    /usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb

Is there a person to whom the same problem has occurred?
If there is a solution method, please tell me.

**Comment by FrankSansC** [comment]
Saw this on the new [Homebrew-cask changelog](https://github.com/caskroom/homebrew-cask/releases/tag/v0.60.0) :
> **NOTE** This is the final release of Homebrew-cask. As of this release, it is no longer necessary to `brew install brew-cask`. `brew tap caskroom/cask` will install `brew-cask` as a [Homebrew external command](https://github.com/Homebrew/homebrew/blob/15f291ddaa05cc010456a733b799382175c29dd4/share/doc/homebrew/External-Commands.md), and `brew update` will keep it up-to-date.
>
>You can `brew update && brew uninstall --force brew-cask` to clean up.

**Comment by mappy81** [comment]
To: FrankSansC

Thank you!
The contents of changelog weren't being seen well, I'm sorry.
After uninstalling brew-cask, an error has not gone out any more!

**Comment by velikanov** [comment]
@FrankSansC :+1:

**Comment by manan19** [comment]
@FrankSansC :+1:
