### ISSUE TITLE
Why is there android-platform-tools?

### ISSUE THREAD

**Issue by aayushkapoor206** [Homebrew/homebrew#46873]
I installed android-sdk which installed the platform tools too. Why is there another formula for platform tools?

**Comment by mikemcquaid** [comment]
I'm guessing because people want a smaller, quicker download for just a couple of utilities.

**Comment by aayushkapoor206** [comment]
So if I install Android Studio and it installs the sdk, all I need to install is platform-tools?

**Comment by mikemcquaid** [comment]
I don't know about Android Studio but: perhaps.

**Comment by aayushkapoor206** [comment]
Thanks! :)
