### ISSUE TITLE
MongoDB 3.2.0 fails with SCons Error: no such option: --extrapath

### ISSUE THREAD

**Issue by tobsn** [Homebrew/homebrew#46870]
==> Upgrading 1 outdated package, with result:
    mongodb 3.2.0
    ==> Upgrading mongodb
    ==> Downloading https://fastdl.mongodb.org/src/mongodb-src-r3.2.0.tar.gz
    Already downloaded: /Library/Caches/Homebrew/mongodb-3.2.0.tar.gz
    ==> Cloning https://github.com/mongodb/mongo-tools.git
    Updating /Library/Caches/Homebrew/mongodb--github.com-mongodb-mongo-tools--git
    ==> Checking out tag r3.2.0
    ==> ./build.sh ssl
    ==> /usr/local/opt/scons/bin/scons install --prefix=/usr/local/Cellar/mongodb/3.2.0 -j4 --osx-version-min=10.11 CC=/usr/bin/clang CXX=/usr/bin/clang++ --use-new-tools --disable-warnings-as-errors --ssl --extrapath=/usr/local/opt/op
    Last 15 lines from /Users/tobias/Library/Logs/Homebrew/mongodb/02.scons:
    Checking whether backtrace_symbols_fd is declared... yes
    Checking for C library pcap... yes
    Checking if std::atomic<int64_t> works... yes
    Checking if std::atomic<uint64_t> works... yes
    Checking if std::atomic<int32_t> works... yes
    Checking if std::atomic<uint32_t> works... yes
    Checking if OpenSSL is available...yes
    Checking whether FIPS_mode_set is declared... yes
    Checking for C function fallocate()... no
    Checking for C function sync_file_range()... no
    Checking for C header file x86intrin.h... yes
    scons: done reading SConscript files.
    usage: scons [OPTION] [TARGET] ...

    SCons Error: no such option: --extrapath

**Comment by DomT4** [comment]
Can you provide a full `brew gist-logs mongodb`, Thanks!

**Comment by cdorer** [comment]
+1.  I can if no one answers in a few hours.

**Comment by bmike** [comment]
I just did a `brew rm mongodb; brew cleanup; brew install mongodb` and 3.2.0 installed cleanly for me on 10.11.2 (15C50) so this might be an error with an optional compile option that's not standard (boost, openssl or sasl).

**Comment by tobsn** [comment]
@DomT4 https://gist.github.com/anonymous/e1c32439ec2df5b1e44f

**Comment by cdorer** [comment]
thank you @tobsn

**Comment by tobsn** [comment]
@DomT4 @cdorer I'm suspecting ssl now too... thing is, I did a fresh install with remove mongodb first to upgrade to 3.x to use the SSL connection features, maybe that messed something up. not that I've done anything special... but yeah, probably as simple as that. I'll try removing it and then do a reinstall just to see - or should I wait for someone to inspect the current issue further?

**Comment by cdorer** [comment]
I did the commands above and found it installed the package just fine without ssl.  oops!

I reran the install w/ --with-openssl and found the same error.  I'm waiting for someone to recognize this one.

**Comment by DomT4** [comment]
The "bog standard" `mongodb` install works fine, aye. It's having options with the SSL and Boost optional dependencies. Looking into it but trying to get about 50 things done today so can't promise speed.

**Comment by tobsn** [comment]
@DomT4 no worries, take your time, the base installs just fine - i can use ssl, just tried it with compose.io, its using the cert and everything. I think its only the update that borks.
MongoDB shell version: 3.0.7 is currently installed from a few days ago when I upgraded from 2.x to 3.x - so for me everything is alright, fresh installers might be f*cked atm though :)

anyway, i don't think its too bad of a problem - installing 3.0.7 would be a temp work around.

**Comment by dasAnderl** [comment]
@bmike brew rm mongodb; brew cleanup; brew install mongodb. worked perfectly even after encountered SCons Error: no such option: --extrapath

**Comment by tobsn** [comment]
@DomT4 @viotti 

    ==> Checking out tag r3.2.0
    ==> ./build.sh ssl
    ==> /usr/local/opt/scons/bin/scons install --prefix=/usr/local/Cellar/mongodb/3.2.0 -j4 --osx-version-min=10.11 CC=/usr/bin/clang CXX=/usr/bin/clang++ --use-n...
    ==> Caveats

all working now - I did not reinstall and waited to try the fix. fix works! 

thank you! :)

**Comment by DomT4** [comment]
@tobsn Thanks for the confirmation! Glad all is working again.

**Comment by shaunstanislaus** [comment]
@DomT4 

### Bug reports:

unable to upgrade to latest mongodb, stuck at ./build.sh ssl
```bash
➜  ~ brew doctor
Your system is ready to brew.
➜  ~ brew install mongodb
==> Downloading https://fastdl.mongodb.org/src/mongodb-src-r3.2.5.tar.gz
######################################################################## 100.0%
==> Cloning https://github.com/mongodb/mongo-tools.git
Cloning into '/Library/Caches/Homebrew/mongodb--github.com-mongodb-mongo-tools--git'...
remote: Counting objects: 1388, done.
remote: Compressing objects: 100% (1125/1125), done.
remote: Total 1388 (delta 222), reused 907 (delta 153), pack-reused 0
Receiving objects: 100% (1388/1388), 2.17 MiB | 366.00 KiB/s, done.
Resolving deltas: 100% (222/222), done.
Checking connectivity... done.
Note: checking out '6dab8f99eaafb764443531dc528d4b4b76eb57f2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

==> Checking out tag r3.2.5
==> ./build.sh ssl
```


`brew gist-logs mongodb` 
[gist logs](https://gist.github.com/anonymous/65af4a9323ea1380a8b23a86b0102987)

**Comment by shaunstanislaus** [comment]
@DomT4:  @ilovezfs resolved my issue! thanks bro!
