### ISSUE TITLE
Problem installing lammps

### ISSUE THREAD

**Issue by goytia54** [Homebrew/homebrew#46884]
I get his error when trying to hombrew lammps, a molecular dynamics program

```
patching file python/lammps.py
Hunk #1 FAILED at 23.
1 out of 1 hunk FAILED -- saving rejects to file python/lammps.py.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1
```

Any ideas what is wrong?

**Comment by apjanke** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Could you read through the troubleshooting instructions and use them to post a full bug report?

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-science#3112

**Comment by DomT4** [comment]
Moved this to Science because it's their formula rather than the core's.
