### ISSUE TITLE
vim 7.4 backspace doesn't work on OSX 10.10.5

### ISSUE THREAD

**Issue by hborders** [Homebrew/homebrew#46899]
I saw in the guidelines that I should open an issue on the formula's repository, but it looked like this project packaged `vim` itself. If not, I apologize. Please redirect me to the correct location, and I'll happily file an issue there.

[`brew gist-logs vim`](https://gist.github.com/anonymous/18321cce328bac9cf589)

Cross-posted on [stackoverflow](http://stackoverflow.com/q/34216314/9636):

I installed vim 7.4 with homebrew on a clean install of OSX 10.10.5. When I enter insert mode and type some text, I see new text appear as expected. However, when I press backspace while in insert mode, I expect the text to delete. Instead, it just navigates backward, but it doesn't delete text. If I type, I replace the text under the cursor, but the text in front of the cursor remains:

enter insertion mode and type "foo bar"

foo bar|
press backspace 4 times

foo| bar
type tclan

footclan|
I also can't move the cursor backwards past my insertion point:

While still in insertion mode, press backspace 4 times.

foot|
Exit insertion mode, then enter insertion mode again.

type fungus

footfungus|
press backspace 7 times

foot|
I expect to delete the "t" as well, but I get stuck at my insertion point.

I have no .vimrc file. This is a new clean Macbook Pro I just received from my employer. I literally just installed Xcode, homebrew, and then ran brew install git bash bash-completion vim.

If I run /usr/bin/vim, I get the OSX system vim, which behaves as I expect.

**Comment by chdiza** [comment]
The system vim comes with a system vimrc that makes backspacing behave properly.  Building vim from source does no such thing.  So you need to add your own ~/.vimrc thata contains:
```vim
set backspace=2
```

**Comment by mikemcquaid** [comment]
Thanks @chdiza!

**Comment by hborders** [comment]
This seems like something the formula should do for us, unless this is an intended change in vim 7.4.

**Comment by chdiza** [comment]
It's not a change in vim 7.4.  It has always been like that.

**Comment by chdiza** [comment]
Vim, when run cold with no vimrc's is supposed to retain `vi` compatibility.  That's why Vim doesn't ship with a system vimrc in place.

Apple stuck one in, which is why backspacing works in the intuitive way on the system vimrc.

**Comment by hborders** [comment]
I was sure that when I did this on my last machine, everything Just Worked™, but I must be misremembering. Thanks!
