### ISSUE TITLE
Problem with the Mapscript PHP extension

### ISSUE THREAD

**Issue by Namrod21** [Homebrew/homebrew#46907]
Hi !

I have a problem concerning the Mapscript PHP extension. I have Mac OS X 10.9 with Mapscript 6.4.1 and PHP 5.6.16, both installed with Homebrew, and I added this line in my ```php.ini``` file:

```extension="/usr/local/Cellar/mapserver-64/6.4.1/mapscript/php/php_mapscript.so" ```

However I get this error when running PHP:

```Module compiled with module API=20100525
PHP    compiled with module API=20131226
These options need to match
 in Unknown on line 0```

Any ideas about how could I solve this ?

Thanks for your answers.

**Comment by bfontaine** [comment]
You should report this issue on the [`homebrew-osgeo4mac`](https://github.com/OSGeo/homebrew-osgeo4mac) repo; this formula is provided by them.
