### ISSUE TITLE
Why doesn't emacs-mac also satisfy agda's dependency?

### ISSUE THREAD

**Issue by jasonhemann** [Homebrew/homebrew#46917]
I'm using the emacs port for mac located at: https://github.com/railwaycat/emacs-mac-port

brew needs the standard emacs as a dependency to install agda. Why would the emacs-mac package not also be satisfactory?

**Comment by dunn** [comment]
Does that port install an executable called `emacs` into your path?

**Comment by jasonhemann** [comment]
Yes, I believe it does. I've got /usr/local/bin/emacs symlinked to .../Cellar/.../emacs-mac../../emacs I thought it was surprising that that wasn't enough to satisfy the need for the emacs.

**Comment by dunn** [comment]
What does it use as a version? What does `emacs -Q --batch --eval "(print emacs-version)"` give you?

**Comment by jasonhemann** [comment]
"24.5.1"

**Comment by DomT4** [comment]
I presume you're installing from source rather than pouring the bottle? Bottles will always build against and need the `default_formula`.

**Comment by dunn** [comment]
Oh, yeah. I forgot the Agda dependency is `:recommended` rather than `:optional`

**Comment by jasonhemann** [comment]
I just typed `brew install <formula>`.

**Comment by dunn** [comment]
So what's going on is when our CI compiles Agda, it uses Homebrew Emacs.  The resulting binary has a hard dependency on Homebrew Emacs.  This isn't probably strictly necessary here, but for other special dependencies (like `:python`) it's important that the version used during compiling is the very same used at run-time.

The immediate solution for you is to reinstall it from source: `brew reinstall -s agda`; then it should use your Emacs.

More generally, we could change this to `depends_on :emacs => [:build, :recommended, "22.1"]`, which I think would prevent the bottles dragging Homebrew Emacs along with them.

**Comment by jasonhemann** [comment]
Oh, okay. Thanks so much.

**Comment by mietek** [comment]
The reason Agda has a `:recommended` dependency on Emacs is because Agda is [intended to be used](http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.QuickGuideToEditingTypeCheckingAndCompilingAgdaCode) via the included Emacs mode.  Previously, we’ve had an `:optional` dependency on Emacs, which had caused problems with the Emacs mode to go unnoticed for a long time. (https://github.com/Homebrew/homebrew/issues/45322)

**Comment by jasonhemann** [comment]
This is very much not the area of my expertise. So this might be absurd. But could the dependency requirement be modified to allow `emacs` or `emacs-mac` to satisfy it? Is that (a) technically feasible, and if so, (b) a good idea?

**Comment by dunn** [comment]
I made a mistake above; changing the dep to `depends_on :emacs => [:run, :recommended, "22.1"]` (not `:build` like I said) would keep the bottled Agda from depending on our Emacs.

But right now Emacs _is_ a build-time dependency; `agda-mode compile` uses Emacs to byte-compile the elisp files.  So out of (maybe an abundance of) caution, we want to make sure it's the same Emacs at run-time that was used at build-time.

So I think we have three options:
1. Change the dependency to `:run` and don't actually byte-compile the elisp; just install the `*.el` files.
2. Change the dependency back to `:optional`. I'm getting the impression this isn't a good solution.
3. Don't provide bottles for Agda; everyone would have to compile it themselves.

The first option sounds best to me, but I don't use Agda.

**Comment by mietek** [comment]
I don’t see a reason why the formula needs to be changed.  Currently, the user which wants to install Homebrew Agda but does not want to install Homebrew Emacs has two options:

1. `brew install agda --without-emacs && agda-mode compile`
2. `brew install agda && brew uninstall emacs && agda-mode compile`

Each option has a downside.  The first option requires Agda to be compiled on the user’s machine, which may take more than 15 minutes.  The second option requires Emacs to be needlessly downloaded, installed, and uninstalled.

@jasonhemann, is either of these options satisfactory?

**Comment by mietek** [comment]
(The correct technical solution to this problem would be for Homebrew to allow both `emacs` and `emacs-mac` to satisfy the dependency for a package providing Emacs — like a Debian [Virtual Package](https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html#s-virtual).)

**Comment by dunn** [comment]
> (The correct technical solution to this problem would be for Homebrew to allow both emacs and emacs-mac to satisfy the dependency for Emacs — like a Debian Virtual Package.)

We do; just not for our bottles when Emacs is required at build-time.

**Comment by jasonhemann** [comment]
@mietek , yeah, the above solves my issue. I was just surprised that there wasn't a way to have a different package satisfy the dependency, as you suggested. @dunn explained why. We can call this good.
