### ISSUE TITLE
mplayer: Bottle supposedly revision 1 but not found on server

### ISSUE THREAD

**Issue by JMoVS** [Homebrew/homebrew#46912]
Hi,

in the current mplayer formula, it states that the bottle is on revision 1. But that results in a HTTP 404. I think the revision bump in bottle-section is probably wrong (as the link https://homebrew.bintray.com/bottles/mplayer-1.2_1.el_capitan.bottle.1.tar.gz doesn't work but https://homebrew.bintray.com/bottles/mplayer-1.2_1.el_capitan.bottle.tar.gz does). Can you confirm this or is it my internet?

**Comment by JMoVS** [comment]
ahh, or it was due to the formula revision bump changing the path (or supposed path) to -1.2**_1**.el_capitan.bottle.1.tar.gz
so it was a formula revisio bump without a move of the bottle files on the server

**Comment by DomT4** [comment]
Yes. Formulae revisions go: **1.2_1** or similar in the URL.

Bottle revisions go: **bottle.2.tar.gz**

The bottles are available via either version divide or in one central location.

**Comment by JMoVS** [comment]
still, bug is still there. Download URL still fails as if the bottles were not available to download. Try it yourself. This is what I get at my machine:
````
==> Downloading https://homebrew.bintray.com/bottles/mplayer-1.2_1.el_capitan.bottle.1.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
````

**Comment by DomT4** [comment]
```
==> Downloading https://homebrew.bintray.com/bottles/mplayer-1.2_1.el_capitan.bottle.tar.gz
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-645; OS X 10.11.2) https://homebrew.bintray.com/bottles/mplayer-1.2_1.el_capitan.bottle.tar.gz -C 0 -o /usr/local/var/homebrew/cache/mplayer-1.2_1.el_capitan.bottle.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 11.3M  100 11.3M    0     0  2597k      0  0:00:04  0:00:04 --:--:-- 3246k
Downloaded to: /usr/local/var/homebrew/cache/mplayer-1.2_1.el_capitan.bottle.tar.gz
SHA1: 41eeee16d790c49859f409895c30b5c99e9282ef
SHA256: 13be908b635ef84ab9a121f7e6787c20e6405bf645417e2f82f98192ea07c92e
==> Verifying mplayer-1.2_1.el_capitan.bottle.tar.gz checksum
```

Sure your `brew` is up-to-date and you don't have any local modifications?

**Comment by JMoVS** [comment]
sigh, sry, somehow git thought it was cool to add a revision 1 into the bottle area :-/ 

Thx for the assistance. Case closed

**Comment by DomT4** [comment]
No worries! Glad all is working again.
