### ISSUE TITLE
fakeroot install -o root no longer works on mac os x 10.11

### ISSUE THREAD

**Issue by dankegel** [Homebrew/homebrew#46927]
The commands
```
touch foo
fakeroot install -o root foo bar
```
should copy 'foo' to 'bar', but on Mac OS X 10.11, the install fails with
```
install: bar: chown/chgrp: Operation not permitted
```

This is with Xcode 7.1 and fully updated brew.  fakeroot -v reports version 1.20.2.
brew --version reports Homebrew 0.9.5 (git revision b3139; last commit 2015-12-11)

**Comment by dankegel** [comment]
Compiling my own fakeroot using the patches from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=766649 outside of brew got me up and going again, so there must just
be something askew with my brew installation...?

**Comment by dankegel** [comment]
The test failures might not be showstoppers.   Homebrew's fakeroot seems to work on the test program:
```
#include <unistd.h>
#include <stdio.h>

int main(int argc, char **argv)
{
    int x = chown(argv[1], 0, 0);
    printf("chown(%s, 0, 0) returns %d\n", argv[1], x);
    if (x)
        perror("failed");
}
```
so maybe it's only Apple's signed install that doesn't work?

Sure enough, 'fakeroot ginstall -o root foo bar' works.

**Comment by tdsmith** [comment]
This is probably a consequence of 10.11's System Integrity Protection feature, which limits the operations you can do with signed code. Do you think Homebrew needs to take action here? I don't see anything obviously actionable.

**Comment by DomT4** [comment]
Yeah, a touch heavy on the irony, to use the same command with Apple's `install` you need to execute `sudo` on the er, `fakeroot` command :sweat:.

**Comment by dankegel** [comment]
As long as brew always uses its own install, all I can think of is "help users by pointing out the problem and suggesting a workaround".  Which is more or less completed by the existence of this bug report :-)

**Comment by tdsmith** [comment]
Okay, great. Thanks for reporting! Let us know if we can help with anything or if just closing this ticket was not the action you expected.

**Comment by dankegel** [comment]
Heh.  I'm not convinced it works, even with the workaround, but have been too lazy to file a new ticket.  I'll try to get to it this week.  Thanks...
