### ISSUE TITLE
header only formulae?

### ISSUE THREAD

**Issue by Ahti** [Homebrew/homebrew#46921]
I just discovered that OSX doesn't ship some of the OpenCL headers. In my case the important one to get some software to compile was [cl.hpp](https://www.khronos.org/registry/cl/api/2.1/cl.hpp).

Would it be sensible to have a header-only formula that installs the missing headers? I think that would be preferable over having each piece of software relying on this ship it themselves.

**Comment by mikemcquaid** [comment]
I don't think so; if it's not provided by the system I suspect there's a reason and upstream formulae should work around that. Sorry!
