### ISSUE TITLE
unable to install glib on ElCapitan (Mac)

### ISSUE THREAD

**Issue by ezrover** [Homebrew/homebrew#46971]
MacBook-Pro:~ nader$ brew install glib
==> Downloading http://ftp.gnome.org/pub/gnome/sources/glib/2.42/glib-2.42.1.tar.xz
Already downloaded: /Library/Caches/Homebrew/glib-2.42.1.tar.xz
==> Downloading https://gist.githubusercontent.com/jacknagel/af332f42fae80c570a77/raw/7b5fd0d2e6554e9b770729fddacaa2d64832

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "glib--patch"
Download failed: https://gist.githubusercontent.com/jacknagel/af332f42fae80c570a77/raw/7b5fd0d2e6554e9b770729fddacaa2d648327644/glib-hardcoded-paths.diff

**Comment by DomT4** [comment]
Your Homebrew seems to be _very_ out of date. Please `brew update` and try again.

**Comment by DomT4** [comment]
Let us know if we can help further here, Thanks!
