### ISSUE TITLE
Installing mu via Homebrew not install Emacs client: mu4e

### ISSUE THREAD

**Issue by Nicholas-Mitchell** [Homebrew/homebrew#46976]
I am experiencing the problems originally posted [here - #16504 ](https://github.com/Homebrew/homebrew/issues/16504) - a successful install of mu using Homebrew did not (at least correctly) install mu4e. Emacs is therefore not able to find it. have tried also installing manually via the gitclone method, but with the same outcome... no mu4e. I am on Mavericks, using Emacs 24.5.

There appears to me be missing links. The files are all there, albeit buried, e.g. in:
/usr/local/Cellar/mu/HEAD/share/emacs/site-lisp/mu4e/mu4e.el.

If I load this file manually within Emacs, if then of course doesn't find the other files, that are `required` within it:
- mu4e-meta
- mu4e-headers
- mu4e-view
- mu4e-main    
- mu4e-compose
- mu4e-proc
- mu4e-utils   
- mu4e-context
- mu4e-speedbar

**Comment by dunn** [comment]
Where are the Lisp files expected to be, other than site-lisp?

**Comment by dunn** [comment]
A neat way to add all Homebrew packages to your `load-path` is 
```elisp
(let ((default-directory "/usr/local/share/emacs/site-lisp/"))
  (normal-top-level-add-subdirs-to-load-path))
```

**Comment by Nicholas-Mitchell** [comment]
Thanks, that `load_path` got things recognised by Emacs. I had added the `../Cellar/` to my emacs path list by accident! 
I now have new problems, but I assume they are unrealted to this so I will close the thread.
