### ISSUE TITLE
Error: uninitialized constant Formulary::CoreFormulaRepository

### ISSUE THREAD

**Issue by brianrs2** [Homebrew/homebrew#46984]
OS X Yosemite
Version 10.10.5
StackTrace after running brew update:

Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:321:in `core_path'
/usr/local/Library/Homebrew/formula.rb:141:in `initialize'
/usr/local/Library/Homebrew/formulary.rb:70:in `new'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:205:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:204:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:124:in `<main>'

**Comment by dunn** [comment]
cc @xu-cheng

**Comment by dunn** [comment]
Does it happen if you run `brew update` again?

**Comment by dunn** [comment]
Shouldn't happen for anyone else now, thank you for the report!

**Comment by kypalmer** [comment]
Error: uninitialized constant Formulary::CoreFormulaRepository
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:322:in `core_path'
/usr/local/Library/Homebrew/formula.rb:141:in `initialize'
/usr/local/Library/Homebrew/formulary.rb:71:in `new'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:206:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:204:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:125:in `<main>'

**Comment by UniqMartin** [comment]
Please try running `brew update` a second time and see if that makes the issue disappear.

**Comment by kypalmer** [comment]
That did it. Thanks!

**Comment by swards** [comment]
2nd time worked for me, too. Thanks.
