### ISSUE TITLE
Error: uninitialized constant Formulary::CoreFormulaRepository

### ISSUE THREAD

**Issue by brianrs2** [Homebrew/homebrew#46985]
Mac OS X Yosemite
version 10.5.5

StackTrace after running brew update

Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:321:in `core_path'
/usr/local/Library/Homebrew/formula.rb:141:in `initialize'
/usr/local/Library/Homebrew/formulary.rb:70:in `new'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:205:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:204:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:124:in `<main>'

**Comment by dunn** [comment]
Only need to open one issue! Let's use #46984.
