### ISSUE TITLE
Mac OS X Mavericks no longer supported - XCode.app 7.0 ?

### ISSUE THREAD

**Issue by bkahlerventer** [Homebrew/homebrew#46991]
This morning homebrew on Mavericks started insisting on having XCode 7.0 installed, yet XCode 7 can only be installed on Mac os X 10.10+

**Comment by bfontaine** [comment]
What does `brew config`and `brew doctor` say?

**Comment by DomT4** [comment]
I can't reproduce this. Were you trying to install or upgrade a formula that requires or newly requires Xcode 7 perhaps?

**Comment by luzpaz** [comment]
@bkahlerventer please respond. I'm interested to know

**Comment by tdsmith** [comment]
Please let us know if we can help with anything.
