### ISSUE TITLE
Stop refactoring without adding unit tests (first) and reverting PRs

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/homebrew#46994]
CC @Homebrew/maintainers for a change because this is important.

I don't want to name any names/PRs (as I've made this mistake too) but: we need to stop doing refactoring without adding additional tests. Almost every major refactoring we've done recently has added no direct benefit to users but has caused one or more user reported bugs. Our `brew tests` are not a sufficient test of whether we've broken the core code or not.

What we need to start doing when we modify core code:

1. set `HOMEBREW_TESTS_COVERAGE` and run `brew tests`
2. look at the coverage of the code you wish to modify and see if it's covered by existing tests
3. add new (passing) tests to cover the code you wish to modify
4. modify the code you wish to modify
5. check the tests still pass, add new tests to cover any of the code you've added.

Additionally, we need to start being more aggressive about reverting core PRs. If a core PR results in a new user reported bug: it should be reverted immediately by any maintainer without review or permission (unless the old bug fixed is much more severe than the new bug) and the relevant PR can be reopened for another approach to be tried.

Homebrew's code isn't the cleanest but ultimately: our users don't care. Our priority should be fixing user reported issues then merging user PRs and then, after that, cleaning up internal code such that it doesn't cause any users to have additional issues.

**Comment by bfontaine** [comment]
Regarding step 3 when the code fixes a bug it’s great to add a test for the bug; then ensure that the code we added/modified makes the test pass.

**Comment by mikemcquaid** [comment]
Exceptions to here when we can be a bit more flexible:

- things relating only to developer seen issues (e.g. around `brew pull` or CI)
- a urgent bug fix to fix users issues

**Comment by mikemcquaid** [comment]
> Regarding step 3 when the code fixes a bug it’s great to add a test for the bug; then ensure that the code we added/modified makes the test pass.

:+1:

**Comment by bfontaine** [comment]
Also after running `brew tests --coverage` (this is the same as setting the environment variable) open `$(brew --prefix)/Library/Homebrew/test/coverage/index.html` in your browser to see the code coverage.

**Comment by xu-cheng** [comment]
> Our brew tests are not a sufficient test of whether we've broken the core code or not.

I will take the in my mind, and hoping to achieve 100% test coverage for my future refactoring.

> Additionally, we need to start being more aggressive about reverting core PRs

Look to me, a better solution is to create a develop branch.

> Homebrew's code isn't the cleanest but ultimately: our users don't care. Our priority should be fixing user reported issues then merging user PRs and then, after that, cleaning up internal code such that it doesn't cause any users to have additional issues.

FWIW, all my code refactorings are either to fix bugs or to help solve long term issues.

**Comment by mikemcquaid** [comment]
> I will take the in my mind, and hoping to achieve 100% test coverage for my future refactoring.

It's annoying, it's definitely something that's bitten me too as the stuff I'm doing at work has good test coverage which means you can afford to be a bit more cavalier with these things.

> Look to me, a better solution is to create a develop branch.

I think that'd have the same problems as PRs: it wouldn't get tested widely until merged into `master`. The long-term solution is good tests and a stable release schedule for core.

> FWIW, all my code refactorings are either to fix bugs or to help solve long term issues.

:+1:

**Comment by DomT4** [comment]
Don't really do much refactoring of core code outside of the `audit` command occasionally, but read, understood and will do my best to comply with the added test rule going forwards.

Only "core" things on my radar are adding a `java_cache` ENV, moving our cache and GPG integration.

**Comment by UniqMartin** [comment]
None of my core changes have touched the tests, unless the existing tests needed to be adapted, so that's definitely something I need to improve. Thanks for the nudge!

I basically agree with everything that has been said here. Once consensus is reached, my only additional wish would be to put the bullet list from the initial comment into the [Maintainer Guidlines](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Maintainer-Guidelines.md).

**Comment by tdsmith** [comment]
This seems like a good norm to me.

**Comment by bfontaine** [comment]
@mikemcquaid Now that all active maintainers are aware of this; can we close this issue?

**Comment by UniqMartin** [comment]
Could we add the information from this issue to the [Maintainer Guidelines](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Maintainer-Guidelines.md). Or maybe there's a better place given that this document mostly focuses on dealing with formulae?

**Comment by mikemcquaid** [comment]
> Could we add the information from this issue to the Maintainer Guidelines? Or maybe there's a better place given that this document mostly focuses on dealing with formulae?

Agreed. Mind making a wee PR for that, @UniqMartin?

**Comment by UniqMartin** [comment]
> Agreed. Mind making a wee PR for that, @UniqMartin?

It took me a wee bit longer than I expected, but here it is: #48218.

**Comment by mikemcquaid** [comment]
We're doing this and have been for a while so: thanks!

**Comment by apjanke** [comment]
:hand: <-hi-five emoji
