### ISSUE TITLE
change graphicsmagick dependency on libtiff from `:optional` to `:recommended`

### ISSUE THREAD

**Issue by carandraug** [Homebrew/homebrew#47017]
Currently, graphicsmagick is built by default with support for jpeg, png, and font files. Support for several other formats is possible but disabled by default:

    depends_on :x11 => :optional
    depends_on "libtiff" => :optional
    depends_on "little-cms2" => :optional
    depends_on "jasper" => :optional
    depends_on "libwmf" => :optional
    depends_on "ghostscript" => :optional
    depends_on "webp" => :optional

which is all fine. Some of the options are not even recommended upstream.

However, I'll argue that at least support for tiff files should be the default.

My reasoning is not only that tiff is a very widespread file format (note that many proprietary formats are actually tiff files and graphicsmagick will identify them correctly), but also that the tiff format is the "de facto" standard in science (I may be biased from my field of research but I don't think so) and graphicsmagick is mostly used by scientific applications in homebrew (according to [@tdsmith](https://github.com/Homebrew/homebrew/pull/46248#issuecomment-159178748)):

    $ brew uses graphicsmagick
    homebrew/science/bioformats-cpp
    homebrew/science/dgtal
    homebrew/science/gnudatalanguage
    homebrew/science/octave
    homebrew/science/vips
    homebrew/science/vips7
    homebrew/x11/xastir

I can provide a pull request with the trivial change if you so desire and agree with my reasoning above.

**Comment by UniqMartin** [comment]
> I can provide a pull request with the trivial change if you so desire and agree with my reasoning above.

I can't speak for the other maintainers, but I agree with your line of thinking and would support a PR.

**Comment by UniqMartin** [comment]
If you could make this a part of #47014, that would be lovely. Otherwise one of the PRs needs to wait for the other to go in and we will need to bump the formula `revision` twice, as both changes are user-visible and affect the default installation. (And I would prefer to avoid doing that.)

**Comment by mikemcquaid** [comment]
I'd rather this was left as-is; I don't think `tiff` is a widely enough used format to make everyone have to pull in the dependency. If we do add it, though, it should also be added to `imagemagick` too.

**Comment by UniqMartin** [comment]
> If we do add it, though, it should also be added to `imagemagick` too.

`libtiff` is already a recommended dependency in `imagemagick`.

**Comment by mikemcquaid** [comment]
> libtiff is already a recommended dependency in imagemagick.

:rage4: ignore me then!
