### ISSUE TITLE
node failed to build on 10.7.5

### ISSUE THREAD

**Issue by dossy** [Homebrew/homebrew#47015]
https://gist.github.com/5955b4fc93628eb610fe

**Comment by dossy** [comment]
FYI, building node 5.1.1 with Homebrew worked just fine, using the node.rb formula from `d56650fa4`.

**Comment by DomT4** [comment]
Looks like they went and broke the Clang that ships with Lion now. Can you try:

```bash
brew install node --cc=gcc-5
```

**Comment by dossy** [comment]
@DomT4 - That worked.  Thanks.

**Comment by DomT4** [comment]
Thanks for the confirmation! Have reported upstream, and inserted a workaround into our formula temporarily in https://github.com/Homebrew/homebrew/commit/d696ce77dde1e9c09fb2b23f134bbaf3b8754288.
