### ISSUE TITLE
Error: uninitialized constant Formulary::CoreFormulaRepository

### ISSUE THREAD

**Issue by cottuli** [Homebrew/homebrew#47039]
OS X Yosemite
Version 10.10.3
StackTrace after running brew update:

Error: uninitialized constant Formulary::CoreFormulaRepository
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:322:in `core_path'
/usr/local/Library/Homebrew/formula.rb:141:in `initialize'
/usr/local/Library/Homebrew/formulary.rb:71:in `new'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:206:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:173:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:140:in `<main>'

**Comment by bfontaine** [comment]
Does it happen if you run `brew update` again?

**Comment by cottuli** [comment]
No.

**Comment by bfontaine** [comment]
This should be fixed then, sorry for the inconvenience! See #46984.
