### ISSUE TITLE
Conflicting external command names for `brew-cask` warning

### ISSUE THREAD

**Issue by jacqueline-homan** [Homebrew/homebrew#47030]
After running the command `brew update` since it had been awhile that I installed anything using Homebrew, I ran the command `brew doctor`, and got this error/warning:
![homebrewwarning](https://cloud.githubusercontent.com/assets/3537889/11799951/24141136-a2a6-11e5-8f72-3f6784a1867b.png)

**Comment by DomT4** [comment]
Try `brew tap --repair`.

**Comment by jacqueline-homan** [comment]
It don't work for me. I get an error.
![homebrewwarning2](https://cloud.githubusercontent.com/assets/3537889/11800064/3c6ed9a4-a2a7-11e5-9dad-f7670af7539b.png)

**Comment by jacqueline-homan** [comment]
I'm afraid I'll delete something I need in another application of I delete that whole directory.

**Comment by DomT4** [comment]
Oh. Try:

```bash
rm /usr/local/share/man/man1/brew-cask.1 && brew tap --repair
```
The single `rm` command there is safe to execute. It's `rm -r` that removes directories.

**Comment by jacqueline-homan** [comment]
It still isn't working right for me.

**Comment by DomT4** [comment]
What's the error now?

**Comment by jacqueline-homan** [comment]
![homebrewerror](https://cloud.githubusercontent.com/assets/3537889/11800154/12950d28-a2a8-11e5-8396-e913f2704773.png)

**Comment by DomT4** [comment]
Alright. The Caskroom moved to being a command rather than an executable recently, and the updated `brew-cask` formula actually tells people to uninstall it, as does their [README](https://github.com/caskroom/homebrew-cask/#important-december-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system) so you can run `brew uninstall brew-cask` safely which should resolve the problem.

**Comment by jacqueline-homan** [comment]
But won't that mess me up if I need brew cask for installing something else using Homebrew?

**Comment by jacqueline-homan** [comment]
Sorry, but I'm not a wiz bang at this stuff yet and it's a struggle when you're trying to learn and your dev tools act up

**Comment by jacqueline-homan** [comment]
Well, I guess nothing else got jangled up. I uninstalled it and was able to re-update brew and run brew doctor and got the go-ahead to brew :) Thanks <3

**Comment by DomT4** [comment]
We/They just changed the method of delivery, so instead of having to run `brew install Caskroom/cask/brew-cask` you can now do `brew tap Caskroom/cask` and `brew-cask install xyz` "just works" :tm:.

**Comment by DomT4** [comment]
Awesome, Glad to hear! Let us know if we can help with anything else :)
