### ISSUE TITLE
Macvim fails to build on 10.11.1 with multiple errors

### ISSUE THREAD

**Issue by philipithomas** [Homebrew/homebrew#47045]
logs: https://gist.github.com/anonymous/465ee04636faf81de217

This doesn't appear to be related to the Ruby or flag for other open issues.

**Comment by bfontaine** [comment]
> Warning: Your Xcode (6.1.1) is outdated
> Please update to Xcode 7.2.
> Xcode can be updated from the App Store.

You might want to upgrade before retrying.

**Comment by philipithomas** [comment]
@bfontaine Thanks - doing that.

**Comment by philipithomas** [comment]
T
