### ISSUE TITLE
libvpx v1.5.0 Failed to Build on OS X v10.11.2 'El Capitan'

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew#47050]
The Gist is [here](https://gist.github.com/RandomDSdevel/9db53252e71a618b13fe).  

NOTES:  
* I tried just running `brew upgrade -vd --build-from-source libvpx` first, but that failed.  
* I then tried doing a `brew reinstall -vd --build-from-source libvpx --with-gcov --with-mem-tracker --with-visualizer --with-examples`, but this also failed.  
* Lastly, I, thinking that the problem was the '`--with-mem-tracker`' option, attempted a `brew reinstall -vd --build-from-source libvpx --with-gcov --with-visualizer --with-examples`, but, strangely, this _also_ failed.

**Comment by UniqMartin** [comment]
If you can live without the other features `brew install libvpx --with-gcov --with-examples` should give you a working build. (You might have to remove a previous build with `brew remove libvpx`.)

- `--with-visualizer` is currently broken. I'm working on a fix that should be available soon.
- `--with-mem-tracker` will be removed soon. It is no longer supported as of `libvpx` 1.5.0.

**Comment by UniqMartin** [comment]
The issue should be fixed now. Please run `brew update` and retry the upgrade, if you haven't already. Feel free to reopen this issue if you continue to have problems.

**Comment by RandomDSdevel** [comment]
@UniqMartin:  Ah, thanks; I'll do that, then…
