### ISSUE TITLE
Install homebrew using curl only, or do I need to include ruby?

### ISSUE THREAD

**Issue by neophoenix123** [Homebrew/homebrew#47072]
Hello,

I am new to the ember environment and had a quick question for those operating CLI. 

I just wanted to know if it is necessary to use 'ruby' to install homebrew to install watchman. I am thinking if I simply use 'Curl' to extract from the github site and download that would be more convenient. I am chasing my tail otherwise, as every method I use prompts me to install the previous application. Ex:
 Install Watchman: I need Homebrew for this.
Install Homebrew via Homebrew website instructions: I need ruby for this:
Install ruby: and so on and so on. 

At this rate I feel as if I will be installing and never getting started on the ember-cli environment. Any suggestions?

Thank you

**Comment by bfontaine** [comment]
OS X ships with Ruby by default so all you have to do is to follow the instructions at [brew.sh](http://brew.sh) and you should be fine. If you’re not on OS X you might want to check [Linuxbrew](https://github.com/Homebrew/linuxbrew), a port of Homebrew on Linux. If you’re on Windows there’s nothing we can do to help you there :wink: 

If you have specific questions regarding Ember you should ask its developpers; this repo is for Homebrew.

**Comment by DomT4** [comment]
Closing as question answered, but let us know if you need further assistance. Thanks!
