### ISSUE TITLE
pxz needs to require gcc libraries

### ISSUE THREAD

**Issue by bbulkow** [Homebrew/homebrew#47089]
If you 'brew install pxz' and you don't have GCC installed, you get errors like 

Toughshit:/usr/local/include$ pxz
dyld: Library not loaded: /usr/local/lib/gcc/5/libgomp.1.dylib
  Referenced from: /usr/local/bin/pxz
  Reason: image not found
Trace/BPT trap: 5

when you actually run pxz.
If you install gcc then the binary runs perfectly.

Please excuse if this isn't the correct process for reporting errors.

**Comment by bfontaine** [comment]
Would you mind doing a pull-request? This should help and I’m happy to answer any question you might have: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

**Comment by bbulkow** [comment]
I don't know the solution to the problem. I don't know enough about pxz or homebrew packaging. Can there be gcc libraries included? The gcc pull down and build takes over an hour ( building all of gcc! ) so I would search for a better solution than dependency on gcc. I am submitting this to be helpful for the maintainer of pxz .
