### ISSUE TITLE
Request to maintaince Linuxbrew gh-pages branch

### ISSUE THREAD

**Issue by timwangdev** [Homebrew/homebrew#47097]
See Homebrew/linuxbrew#627

The `gh-pages` branch of [Homebrew/linuxbrew](https://github.com/Homebrew/linuxbrew/tree/gh-pages) seems not maintained for a year.

I'd like to join the team to help maintain the [Homebrew/linuxbrew](https://github.com/Homebrew/linuxbrew) GitHub Pages.

**Comment by DomT4** [comment]
We don't actually have any involvement in day-to-day Linuxbrew or Linuxbrew maintenance decisions. You'd be better filing an Issue over at the Linuxbrew repo, Thanks!
