### ISSUE TITLE
Executing external commands: "Kernel.exit" is always printed to stdout when --verbose is set, even if exit status is 0

### ISSUE THREAD

**Issue by zmwangx** [Homebrew/homebrew#47099]
Consider a very simple external command `meh`, which only consists of `puts "meh"`:

```zsh
> echo 'puts "meh"' >brew-meh.rb
> chmod +x brew-meh.rb
> PATH=$PWD:$PATH
> brew meh --verbose 2>/dev/null
meh
Kernel.exit
```

As you can see, `Kernel.exit` is printed on stdout although there's no error whatsoever, which is rather surprising and obnoxious. The rightful place for such a message, IMO, is stderr, and ideally it shouldn't appear at all when the exit status is 0.

This issue seems to be due to https://github.com/Homebrew/homebrew/blob/80bdf34/Library/brew.rb#L150 always `exit`ing after requiring the external command, which is then picked up by `rescue SystemExit` https://github.com/Homebrew/homebrew/blob/80bdf34/Library/brew.rb#L178.

This issue is also causing some minor regression for homebrew-cask after adopting the external command architecture. See https://github.com/caskroom/homebrew-cask/issues/15882.

**Comment by mikemcquaid** [comment]
It's because of setting `HOMEBREW_VERBOSE`. Can you not unset that?

**Comment by zmwangx** [comment]
I can, but don't you think it's pointlessly verbose to print Kernel.exit when the exit code is zero? Also, brew's native commands don't print this unless there's an error, so it's also inconsistent. Not to mention debugging info would better suit stderr.

**Comment by zmwangx** [comment]
One more objection: a plugin script can't dictate caller's environment, so currently as long as `HOMEBREW_VERBOSE` is set, it's basically impossible to write an external command with parseable output (since Kernel.exit will always tag along), which is an annoying and arbitrary limitation.

**Comment by mikemcquaid** [comment]
> Also, brew's native commands don't print this unless there's an error, so it's also inconsistent

This is the bit I consider a bug. I don't consider `HOMEBREW_VERBOSE` to generate parseable output for most commands.

**Comment by zmwangx** [comment]
> I don't consider `HOMEBREW_VERBOSE` to generate parseable output for most commands.

Well, there is a different between most commands not generating parseable output and *impossible* to write commands with parseable output. Imagine an external reimplementation of `brew --prefix`, or something of that nature; of course, `brew --prefix` generates predictable and parseable output whether or not `HOMEBREW_VERBOSE` is set:

```zsh
> brew --prefix --verbose
/usr/local
```

but being an external command that's simply impossible, as I demonstrated in `brew-meh`. One simple enough solution (though not perfect) is to put `Kernel.exit` and other messages of that sort on stderr.
