### ISSUE TITLE
p11-kit > 0.18.4 broken on OS X

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#47124]
Newer versions of p11-kit since 0.18.4, up to 0.23.1, are not working on OS X. They fail during `make check` with several test failures.

```
$ brew install p11-kit -s
==> Using the sandbox
==> Downloading http://p11-glue.freedesktop.org/releases/p11-kit-0.22.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/p11-kit-0.22.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/p11-kit/0.22.0 --disable-trust-module --without-libffi
==> make
==> make check
Last 15 lines from /Users/janke/Library/Logs/Homebrew/p11-kit/03.make:
ok 27 /iter/test_load_attributes_fail_first
ok 28 /iter/test_load_attributes_fail_late
ok 29 /iter/test-many
ok 30 /iter/test-many-busy
ok 31 /iter/destroy-object
PASS: test-iter
/bin/sh: line 1: 68474 Segmentation fault: 11  ${dir}$tst
FAIL: test-rpc
============================================================================
5 of 23 tests failed
Please report to https://bugs.freedesktop.org/enter_bug.cgi?product=p11-glue
============================================================================
make[2]: *** [check-TESTS] Error 1
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1
brew-gist-logs p11-kit
```

I'm sticking this in as a bug report as a place to put logs for reference, and so other contributors who notice p11-kit's old version and attempt to bump it can save themselves some time and not bother until a new version comes out.

Upstream bug: https://bugs.freedesktop.org/show_bug.cgi?id=91602

Work-in-progress for `p11-kit` 0.22.x is on [the `p11-kit-0.22.x` branch on my repo](https://github.com/apjanke/homebrew/tree/p11-kit-0.22.x), for me or others to pick up once this gets fixed. Note that `--without-libffi` now has to be explicitly supplied to `p11-kit`'s `./configure`, or it'll choke.

Failure for 0.22.0 on 10.9:  https://gist.github.com/b2286544fb5ad377ccdd
Failure for 0.22.1 on 10.9: https://gist.github.com/9b808ead93035e206314
Similar failure for 0.23.2 on 10.9:  https://gist.github.com/416889fd4c5b21138f58

Locations for the newer releases:
```
  url "http://p11-glue.freedesktop.org/releases/p11-kit-0.22.1.tar.gz"
  sha256 "ef3a339fcf6aa0e32c8c23f79ba7191e57312be2bda8b24e6d121c2670539a5c"

  url "http://p11-glue.freedesktop.org/releases/p11-kit-0.22.0.tar.gz"
  sha256 "cf652b1d79513583a07b454bb82bc1529d911161048d5420ad7ce2d48e892299"
```

**Comment by dunn** [comment]
The ticket's been sitting upstream without a response since August. How long before we boneyard? Do we know they're working on OSX compatibility?

**Comment by rakkesh** [comment]
If this commit is to believed, `p11-kit >= 0.20.7` has problem finishing tests successfully. https://github.com/Homebrew/homebrew/blob/master/Library/Formula/glib-networking.rb#L30-L32

**Comment by rakkesh** [comment]
I agree with @dunn on this issue. PKCS#11 in general is not targeted for desktop apps, and also, I'm not sure if upstream is going to support Mac OS X. We can boneyard this formula if you and other Homebrew maintainers don't have an objection. I can take it up after closing GnuTLS 3.4.x [PR](https://github.com/Homebrew/homebrew/pull/47065).

**Comment by dunn** [comment]
Unless other maintainers disagree, :skull:

**Comment by apjanke** [comment]
My vote is boneyard.

```
$ brew uses p11-kit
gnutls
$
```

If some application ends up actually using it, maybe they can work with upstream to get OS X support better supported, and we can bring it back.

**Comment by DomT4** [comment]
Feel free. They haven't responded to Alex's bug report at all, so I think it's time to throw it into the :fire:.

**Comment by mikemcquaid** [comment]
:+1: to :skull:
