### ISSUE TITLE
Download Counts and Other Statistics

### ISSUE THREAD

**Issue by qw3rtman** [Homebrew/homebrew#47128]
I'm trying to find the download count of a project I maintain that's in the Homebrew registry. I was able to get to the package page on Bintray and am able to see some statistics; however, [the download counts are not made public](https://bintray.com/homebrew/bottles/git-extras/view#statistics).

Is there anyway I can access the actual numbers? I assume the owner of the file on Bintray (Homebrew) or any of the members ([listed here](https://bintray.com/user/organizationMembers?username=homebrew)) can access that info.

Additionally, are there any plans to make this information available from the command-line? I can't think of any potential negative to making this information publicly available (npm provides it).

**Comment by bfontaine** [comment]
> Additionally, are there any plans to make this information available from the command-line?

Yes, see #34101.

> Is there anyway I can access the actual numbers?

Yes I just checked the box to make them public.

**Comment by qw3rtman** [comment]
Thank you!
