### ISSUE TITLE
libsamplerate build is broken

### ISSUE THREAD

**Issue by abique** [Homebrew/homebrew#47133]
Hi,

The libsamplerate build is broken because the program sndfile-resample is not working:

```
audio:~ cochlea$ /Users/cochlea/bin//sndfile-resample "-to" "176400" "-c" "0" "/Users/cochlea/test-data//audio-in/mini-drum-loop.wav" "/Users/cochlea/tmp//4/audio-in-0-176400.wav"

****************************************************************
  This example program was compiled without libsndfile 
  (http://www.mega-nerd.com/libsndfile/).
  It is therefore completely broken and non-functional.
****************************************************************

```

**Comment by abique** [comment]
It seems that "brew reinstall --build-from-source --with-fftw --with-libsndfile libsamplerate" did the job for me finally, but still either don't include sndfile-resample or fix the package but there is no point in providing broken binaries/libraries.

Regards,
Alex.

**Comment by mikemcquaid** [comment]
It seems to me it's just the example program that's broken rather than the library as a whole. We should probably just remove that unless `--with-libsndfile` is passed.

**Comment by abique** [comment]
Why not build it with libsndfile by default?

**Comment by mikemcquaid** [comment]
That's an additional dependency and it's unclear most users of `libresample` need it.

**Comment by abique** [comment]
Given that I'm the first to open that bug, people probably don't need it.
If you remove it from the installation, then I would suggest to add a message on the console to explain the user how to get it during the installation.

**Comment by nijikon** [comment]
@mikemcquaid What we want to do with this? I can work on this issue.

**Comment by mikemcquaid** [comment]
@nijikon Sorry for the delay; looks like @rakkesh has a PR in https://github.com/Homebrew/homebrew/pull/48409.

**Comment by DomT4** [comment]
Fix was merged in https://github.com/Homebrew/homebrew/commit/4a8654c32d0678cd49923140f7971b4b82caea6d.
