### ISSUE TITLE
brew update failed

### ISSUE THREAD

**Issue by bebbi** [Homebrew/homebrew#47131]
Details at https://gist.github.com/anonymous/a1fd823526b2e0112279

$ brew update
Checking out files: 100% (2767/2767), done.
Error: uninitialized constant Formulary::CoreFormulaRepository
Please report this bug

**Comment by bfontaine** [comment]
Thank you for the report! Running `brew update` should be fine; we’re working on a solution to avoid these kind of problems in the future. See #46984.
