### ISSUE TITLE
Apply for new Gratipay team

### ISSUE THREAD

**Issue by mattbk** [Homebrew/homebrew#47143]
I saw this was mentioned at https://github.com/Homebrew/homebrew/issues/41561#issuecomment-120207934.

The team approval process is fairly smooth now and includes tips from your old account being moved over automatically. You guys definitely fit all the requirements and shouldn't have a problem being approved.

The application is at http://gratipay.com/new.

Full disclosure: I do some of the support work for Gratipay, but I'm also a Homebrew user and fan and would like to donate to the project.

**Comment by mikemcquaid** [comment]
I'd probably rather leave it for now; we're going to be in a position to collect funds directly in the near future and don't want to mess with things before then. Thanks!

**Comment by DomT4** [comment]
Closing per Mike's comment. Thank you for the willingness to contribute to Homebrew, we appreciate that :heart:
