### ISSUE TITLE
archey is a GitHub fork

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#47167]
The `archey` formula points to a GitHub fork.

It's not clear what the actual master repository should be, because this is a 5-deep fork chain that goes back to a half-empty repo (maybe just used to share a copy of a script?). Let's figure this out and see find what the actual master repo is.

```
$ brew audit --strict --online archey
==> brew style archey

1 file inspected, no offenses detected

==> audit problems
archey:
 * GitHub fork (not canonical repository)

Error: 1 problem in 1 formula
```

Formula points to https://github.com/obihann/archey-osx.

Fork chain:
https://github.com/obihann/archey-osx
forked from https://github.com/Gary00/OSXey
forked from https://github.com/joshfinnie/archey-osx
forked from https://github.com/teoljungberg/archey-osx
forked from https://github.com/onlythefinestwilldo/Quality.Junk

**Comment by apjanke** [comment]
@obihann You've been active in this formula, and that's your repo at the head of the fork chain. Comments?

**Comment by DomT4** [comment]
I don't have any issue with pointing at the fork in this situation FWIW. It's where most people seem to go to find an Archey OS X clone that works now.

**Comment by apjanke** [comment]
Okay. Is there something we can do to suppress the audit failure?

**Comment by DomT4** [comment]
Could add a formula specific `return` to the check, I guess. The long-term plan for a while has been a full audit whitelist, but I haven't got around to that particular horse yet.

**Comment by obihann** [comment]
Is their anything I can do on my end to help out here?

**Comment by apjanke** [comment]
If you really wanted to fix this, you could de-forkify your repo. (I think that requires renaming the existing repo, creating a new one with the original name, and pushing your history to it from a local clone.)

Or you can just wait for us to figure out how to do audit whitelisting. It's not urgent: I just ran in to this while testing & auditing some stuff; no functionality is broken.

**Comment by mikemcquaid** [comment]
> If you really wanted to fix this, you could de-forkify your repo. (I think that requires renaming the existing repo, creating a new one with the original name, and pushing your history to it from a local clone.)

You can just ask GitHub to defork this, actually (and as I work there: I can do this for you).

> Or you can just wait for us to figure out how to do audit whitelisting. It's not urgent: I just ran in to this while testing & auditing some stuff; no functionality is broken.

@apjanke We already do that; you can see in other cases we do early returns based on the formula name.

**Comment by obihann** [comment]
@mikemcquaid If you could defork my branch, that would be amazing. Thanks!

**Comment by mikemcquaid** [comment]
https://github.com/obihann/archey-osx is now deforked. Thanks @apjanke and @obihann!
