### ISSUE TITLE
Unsupported special dependency :ruby Error when running brew install brew-cask

### ISSUE THREAD

**Issue by katherinator** [Homebrew/homebrew#47165]
$ brew install brew-cask

Error: Unsupported special dependency :ruby
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/usr/local/Library/Homebrew/dependency_collector.rb:133:in `parse_symbol_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:81:in `parse_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:65:in `build'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `block in fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:38:in `add'
/usr/local/Library/Homebrew/software_spec.rb:103:in `depends_on'
/usr/local/Library/Homebrew/formula.rb:706:in `block in depends_on'
/usr/local/Library/Homebrew/formula.rb:706:in `each'
/usr/local/Library/Homebrew/formula.rb:706:in `depends_on'
/usr/local/Library/Taps/caskroom/homebrew-cask/brew-cask.rb:5:in `<class:BrewCask>'
/usr/local/Library/Taps/caskroom/homebrew-cask/brew-cask.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:198:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:28:in `install'
/usr/local/Library/brew.rb:136:in `<main>'

**Comment by DomT4** [comment]
You don't need to install `brew-cask` now. Just `brew tap Caskroom/cask`.

We'll need at least a `brew config` and `brew doctor` to debug further here.

**Comment by katherinator** [comment]
$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 0545ce369d05d9740c483188dd72ec569b0e5b95
Last commit: 1 year, 2 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit haswell
OS X: 10.11.1-x86_64
Xcode: 6.0.1
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby

$ brew doctor

Warning: Your Xcode (6.0.1) is outdated
Please update to Xcode 6.1.
Xcode can be updated from the App Store.
Error: Failed to import: brew-cask
Unsupported special dependency :ruby

Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours. This is a long time in brewland!
To update Homebrew, run `brew update`.

Thanks @DomT4 :)

**Comment by mikemcquaid** [comment]
> To update Homebrew, run brew update.

This will fix things.

**Comment by DomT4** [comment]
Try `brew update` first, that'll likely fix it. Note to install most things from Homebrew (rather than the Caskroom) you will need up-to-date developer tools.

**Comment by katherinator** [comment]
Thanks Guys.. brew update fixed it..

**Comment by nishkala-j** [comment]
brew update helps. Thank you!

**Comment by wavelynn** [comment]
brew update helps. Thank you!

**Comment by ManuJindal** [comment]
Still getting error with : brew install node



make[1]: Entering directory `/tmp/node-20160707-24260-c7kuuw/node-v6.1.0/out'
  /usr/bin/g++-4.8  -I../deps/gtest -I../deps/gtest/include  -pthread -Wall -Wextra -Wno-unused-parameter -m64 -Wno-missing-field-initializers -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /tmp/node-20160707-24260-c7kuuw/node-v6.1.0/out/Release/.deps//tmp/node-20160707-24260-c7kuuw/node-v6.1.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o.d.raw -isystem/home/manujindal/.linuxbrew/include -Os -w -pipe -march=native -c -o /tmp/node-20160707-24260-c7kuuw/node-v6.1.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o ../deps/gtest/src/gtest-death-test.cc
  /usr/bin/g++-4.8  -I../deps/gtest -I../deps/gtest/include  -pthread -Wall -Wextra -Wno-unused-parameter -m64 -Wno-missing-field-initializers -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /tmp/node-20160707-24260-c7kuuw/node-v6.1.0/out/Release/.deps//tmp/node-20160707-24260-c7kuuw/node-v6.1.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o.d.raw -isystem/home/manujindal/.linuxbrew/include -Os -w -pipe -march=native -c -o /tmp/node-20160707-24260-c7kuuw/node-v6.1.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o ../deps/gtest/src/gtest-filepath.cc
  /usr/bin/g++-4.8  -I../deps/gtest -I../deps/gtest/include  -pthread -Wall -Wextra -Wno-unused-parameter -m64 -Wno-missing-field-initializers -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /tmp/node-20160707-24260-c7kuuw/node-v6.1.0/out/Release/.deps//tmp/node-20160707-24260-c7kuuw/node-v6.1.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-port.o.d.raw -isystem/home/manujindal/.linuxbrew/include -Os -w -pipe -march=native -c -o /tmp/node-20160707-24260-c7kuuw/node-v6.1.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-port.o ../deps/gtest/src/gtest-port.cc
make[1]: /usr/bin/g++-4.8: Command not found
make[1]: *** [/tmp/node-20160707-24260-c7kuuw/node-v6.1.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o] Error 127
make[1]: *** Waiting for unfinished jobs....
make[1]: /usr/bin/g++-4.8: Command not found
make[1]: *** [/tmp/node-20160707-24260-c7kuuw/node-v6.1.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o] Error 127
make[1]: /usr/bin/g++-4.8: Command not found
make[1]: *** [/tmp/node-20160707-24260-c7kuuw/node-v6.1.0/out/Release/obj.target/gtest/deps/gtest/src/gtest-port.o] Error 127
make[1]: Leaving directory `/tmp/node-20160707-24260-c7kuuw/node-v6.1.0/out'
make: *** [node] Error 2

**Comment by UniqMartin** [comment]
@ManuJindal Your error is unrelated to this issue. Furthermore, you seem to be using Linuxbrew, thus please report any issues you have to https://github.com/Linuxbrew/brew instead of this Homebrew repository. Thanks!
