### ISSUE TITLE
asm6 is 404

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#47168]
The home page and download link in the `asm6` formula are both 404.

http://home.comcast.net/~olimar/NES/
http://home.comcast.net/~olimar/NES/asm6.zip

That was someone's personal ISP home page. Google pulls up nothing resembling a new project home page.

Anyone know if/where this is hosted now?

I [repointed it at the Wayback Machine](https://github.com/Homebrew/homebrew/commit/ca54b8a61e3df329833c7d534d555155928a1230) for now.

**Comment by mikemcquaid** [comment]
No idea, I'm afraid. Probably better to remove it longer-term if we can't find a new host and given nothing depends on it.
