### ISSUE TITLE
package for homebrew py27-gtkspell

### ISSUE THREAD

**Issue by reagle** [Homebrew/homebrew#47178]
Excuse my ignorance as I know very little about GTK, OS X, and Homebrew. However, I would like to be able to recommend my students, who mostly use OS X, use [zim wiki](http://zim-wiki.org/), including its spell checking plugin. I have [documented a technique using macports](http://reagle.org/joseph/zwiki/Archives/2015/Zim_on_Mac_OSX.html), using the [py-gtkspell](https://trac.macports.org/browser/trunk/dports/gnome/py-gtkspell/Portfile) port, but macports take so long and is unwieldy once installed. Homebrew is much easier, but it's missing py-gtkspell ([Ubuntu source is here](http://packages.ubuntu.com/source/precise/gnome-python-extras).) Is it even possible to submit a request for a brew?

**Comment by mikemcquaid** [comment]
We don't really do requests. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by reagle** [comment]
I would not even know where to start since I know nothing of homebrew, gtk, and their python bindings. Thanks for the quick response.
