### ISSUE TITLE
undefined method `option_names' for #<Dependency: "cd-discid"

### ISSUE THREAD

**Issue by dr3s** [Homebrew/homebrew#47180]
I haven't updated brew in awhile on el capitan.  brew update fails with the error below.  I ran brew doctor and cleared all the warnings that I could.  I ran the commands in the warnings to chown /usr/local/library and to stash and reset the git repo.  brew doctor succeeds still with warnings that tcl tkl is in my lib.   

--- local/Library ‹master› » brew update                                                  1 ↵
Error: undefined method `option_names' for #<Dependency: "cd-discid" []>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/software_spec.rb:188:in `add_dep_option'
/usr/local/Library/Homebrew/software_spec.rb:156:in `depends_on'
/usr/local/Library/Homebrew/formula.rb:1821:in `block in depends_on'
/usr/local/Library/Homebrew/formula.rb:1821:in `each'
/usr/local/Library/Homebrew/formula.rb:1821:in `depends_on'
/usr/local/Library/Formula/abcde.rb:17:in `<class:Abcde>'
/usr/local/Library/Formula/abcde.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:85:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:76:in `klass'
/usr/local/Library/Homebrew/formulary.rb:72:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:173:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:124:in `<main>'

--- local/Library ‹master› » brew doctor                                                  1 ↵
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libtcl8.6.dylib
    /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/fakemysql.h
    /usr/local/include/fakepq.h
    /usr/local/include/fakesql.h
    /usr/local/include/itcl.h
    /usr/local/include/itcl2TclOO.h
    /usr/local/include/itclDecls.h
    /usr/local/include/itclInt.h
    /usr/local/include/itclIntDecls.h
    /usr/local/include/itclMigrate2TclCore.h
    /usr/local/include/itclTclIntStubsFcn.h
    /usr/local/include/mysqlStubs.h
    /usr/local/include/odbcStubs.h
    /usr/local/include/pqStubs.h
    /usr/local/include/tcl.h
    /usr/local/include/tclDecls.h
    /usr/local/include/tclOO.h
    /usr/local/include/tclOODecls.h
    /usr/local/include/tclPlatDecls.h
    /usr/local/include/tclThread.h
    /usr/local/include/tclTomMath.h
    /usr/local/include/tclTomMathDecls.h
    /usr/local/include/tdbc.h
    /usr/local/include/tdbcDecls.h
    /usr/local/include/tdbcInt.h
    /usr/local/include/tk.h
    /usr/local/include/tkDecls.h
    /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/tcl.pc
    /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libtclstub8.6.a
    /usr/local/lib/libtkstub8.6.a

**Comment by dunn** [comment]
Does it happen every time you run `brew update`?

**Comment by dr3s** [comment]
No of course, it worked the 3rd time perfectly.  Thanks for the quick response!

**Comment by mythhsy** [comment]
i've encountered the same problem on OS X El Capitan, and I got it through the 2nd time.

**Comment by jorgehatccrma** [comment]
Same here. I worked the second update attempt. I'm running OS X 10.10.5, git 2.4.5.

**Comment by jdan** [comment]
Worked on the second attempt for me. @dr3s might be worth re-opening?

**Comment by Ernesto-Valdes** [comment]
Find next my error, using OS X v10.10.5:

```
Error: undefined method `option_names' for #<Dependency: "cd-discid" []>
Please report this bug:
https://git.io/brew-troubleshooting
```

It worked on the second attempt.

**Comment by ccggeo** [comment]
Worked on second attempt for me. Run again
