### ISSUE TITLE
LLDB doesn't work with brewed python

### ISSUE THREAD

**Issue by LastSecondsToLive** [Homebrew/homebrew#47201]
I'm on a Mac and python2 and python3 is installed via brew (+ the already shipped OS X python).
`which python` prints `/usr/local/bin/python`.
`which python3` prints `/usr/local/bin/python3`.

Here you can see my python versions - but as you can see the brewed python can't access `LLDB python module` (shipped with Xcode):
```
Matthias@MacBookPro ~$ which python
/usr/local/bin/python
Matthias@MacBookPro ~$ python
Python 2.7.11 (default, Dec  5 2015, 14:44:53) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lldb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named lldb
>>> 
```

Same with brewed `python3`:

```
Matthias@MacBookPro ~$ which python3
/usr/local/bin/python3
Matthias@MacBookPro ~$ python3
Python 3.5.1 (default, Dec  7 2015, 21:59:10) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lldb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'lldb'
>>> 
```

This is what I added to my `.bash_profile` to include the `LLDB module path` to the location the brewed python looks for modules:
```
export PYTHONPATH="/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python:${PYTHONPATH}"
```

But then I get this error:
```
Matthias@MacBookPro ~$ python
Python 2.7.11 (default, Dec  5 2015, 14:44:53) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lldb
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
```

What can I do to make the brewed python work with the `LLDB python module` (the preinstalled preferred, but I wouldn't mind to install a new LLDB)?

**Comment by UniqMartin** [comment]
The Python library you try to load is explicitly linked to `/System/Library/Frameworks/Python.framework/Versions/2.7/Python`, which conflicts with the already loaded Python framework provided by the `python` and `python3` formulae. As the LLDB framework isn't provided by Homebrew, there's unfortunately nothing we can do about this. Your best bet is to use the system `python` to interact with Xcode LLDB. (You can find more information and some other options in #46561.)

**Comment by ttimasdf** [comment]
add the following line in `.bashrc` or whatever shell you need,
```
alias lldb='PATH="/usr/bin:$PATH" lldb'
```
