### ISSUE TITLE
package aws-shell

### ISSUE THREAD

**Issue by FernandoMiguel** [Homebrew/homebrew#47207]
https://github.com/awslabs/aws-shell

**Comment by mikemcquaid** [comment]
We don't do requests. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by FernandoMiguel** [comment]
thanks
will try to take a look after xmas break.
