### ISSUE TITLE
Enable Python3 support in boost-python bottle?

### ISSUE THREAD

**Issue by gijzelaerr** [Homebrew/homebrew#47218]
Hi!

We are adding python3 support to our product. We support OSX and we test this on Travis CI. To install our requirements we use the awesome Homebrew. Our main dependency is boost-python. To enable python3 support with boost-python in homebrew we need to supply the `--with-python3`. Flag. When homebrew is supplied with a flag it triggers a build, and doesn't use a bottle:

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md#why-do-you-compile-everything

Now the problem is, compiling boost-python takes quite some time, so the Travis build will time out. I contacted Travis support and there is not much what they can do about this.

I see multiple potentially solutions to do this:
 * We make our own bottle and put that somewhere public, not sure how to do that - couldn't find doc. Only about how to make custom beer bottles.
 * I can't imagine this discussion has been done before, but what about enabling python3 by default? Python3 has been released for 7 years now, Ubuntu and Debian install it by default. Is this still a crazy idea?
 * Is there some sort of support for multi flag bottles? Store precompiled bottles for the same package with multiple flags.

I Think I probably need to go with solution 1, but seeing python3 accepted as the new default where possible looks like a better long term solution to me.

greetings,

 - Gijs

**Comment by mikemcquaid** [comment]
> We make our own bottle and put that somewhere public, not sure how to do that - couldn't find doc. Only about how to make custom beer bottles.

Should be relatively easy; this should help: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Bottles.md#bottle-creation

Ask in this issue if you have more questions here.

> I can't imagine this discussion has been done before, but what about enabling python3 by default? Python3 has been released for 7 years now, Ubuntu and Debian install it by default. Is this still a crazy idea?

We try to minimise dependencies for packages and Python 3 is still relatively niche (unfortuantely).

> Is there some sort of support for multi flag bottles? Store precompiled bottles for the same package with multiple flags.

Nope, unfortunately not.

**Comment by jakirkham** [comment]
I have a similar concern about boost-python for python3 not being bottled. It makes sense why one would not want to include both. Would it be possible to split boost-python into 2 packages as has been done with python and simply have a boost-python and boost-python3 package? This could cut down on the complexity of the existing package. Also, it would provide users with the option to pick the appropriate boost-python as needed.

**Comment by mikemcquaid** [comment]
@jakirkham I'd rather not start getting into splitting every package with Python bindings into two packages, sorry

**Comment by jakirkham** [comment]
I understand that you are not wanting to split every package. However, we aren't discussing building pycrypto, which builds a few python bound C functions and isn't terrible to build from source in all cases. We are discussing Boost Python, which is one of the most common ways C++ programs are linked to Python (so exposes a full and varied Python API) and takes ~6 minutes to build. My concern is that this is at the very beginning of building a potentially very complicated C++ program that binds to Python and building Boost Python is already a time sink. Before you answer, please keep in mind that these C++ programs are often going through CI as they should and will need to install this first. Not to mention they may have more horrendous pre-build steps like building NumPy and SciPy.

**Comment by gijzelaerr** [comment]
I've made a custom boost python3 bottle which is easy to install. Will post
details Monday.
Op 29 jan. 2016 2:39 p.m. schreef "jakirkham" <notifications@github.com>:

**Comment by jakirkham** [comment]
Thanks @gijzelaerr. Is it just Python 3 or does it include Python 2, as well?

**Comment by gijzelaerr** [comment]
here is a repo that is travis enabled:

https://github.com/casacore/casacore/tree/python3-fix

here the specific install script that downloads the python3 enabled python-boost bottle.

https://github.com/casacore/casacore/blob/python3-fix/.travis/install.sh

yes, it also support python2.

I don't recommend using our bottle though, since we may update it at any moment. Probably better to build it ourself (see instructions above) and put it somewhere (like bintray).

**Comment by jakirkham** [comment]
Thanks @gijzelaerr.
