### ISSUE TITLE
brew doctor failed to build on 10.11.2

### ISSUE THREAD

**Issue by brv-in2p3** [Homebrew/homebrew#47219]
after "brew update", I tried brew doctor and got this:
prompt> brew doctor

Error: invalid byte sequence in US-ASCII
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:45:in `=~'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:45:in `chop_basename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:341:in `plus'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:334:in `+'
/usr/local/Library/Homebrew/extend/pathname.rb:296:in `resolved_path_exists?'
/usr/local/Library/Homebrew/cmd/doctor.rb:232:in `block (2 levels) in check_for_broken_symlinks'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:546:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:546:in `find'
/usr/local/Library/Homebrew/cmd/doctor.rb:231:in `block in check_for_broken_symlinks'
/usr/local/Library/Homebrew/cmd/doctor.rb:229:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:229:in `check_for_broken_symlinks'
/usr/local/Library/Homebrew/cmd/doctor.rb:1301:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1299:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1299:in `doctor'
/usr/local/Library/brew.rb:143:in `<main>'

**Comment by bfontaine** [comment]
Thank you for the report! Do the solution in #44744 work?

**Comment by brv-in2p3** [comment]
yes, it works now after a export LC_ALL=en_US.UTF-8
thanks a lot

**Comment by bfontaine** [comment]
Great!
