### ISSUE TITLE
Brew bottle failing to bottle formula file.

### ISSUE THREAD

**Issue by externl** [Homebrew/homebrew#47233]
Trying to bottle a formula from a file. I run:
``` 
brew install --build-bottle ice.rb
```
Then try to bottle:
```
joe@mactop ~/Desktop $ brew bottle ./ice.rb
==> Determining ice bottle revision...
Error: undefined method `path' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula_versions.rb:15:in `initialize'
/usr/local/Library/Homebrew/cmd/bottle.rb:172:in `new'
/usr/local/Library/Homebrew/cmd/bottle.rb:172:in `bottle_formula'
/usr/local/Library/Homebrew/cmd/bottle.rb:402:in `block in bottle'
/usr/local/Library/Homebrew/cmd/bottle.rb:401:in `each'
/usr/local/Library/Homebrew/cmd/bottle.rb:401:in `bottle'
/usr/local/Library/brew.rb:143:in `<main>'
```
No complaints from `brew doctor`.

OS X 10.11.2

**Comment by externl** [comment]
The bottle build find if I add the file to my Cellar.

**Comment by mikemcquaid** [comment]
CC @xu-cheng for thoughts around what the `Tap` class should be doing here.

@externl You should run `brew bottle` with a formula name rather than a `formula.rb` path.

**Comment by xu-cheng** [comment]
It should be a small fix. Will send a PR to fix this tommorw. Also I wonder what's your opinion on supporting bottle formula outside core and tap? Consider the bottle won't be able to be poured because it will fail to find formula file anyway.

**Comment by mikemcquaid** [comment]
> Also I wonder what's your opinion on supporting bottle formula outside core and tap? Consider the bottle won't be able to be poured because it will fail to find formula file anyway.

Indeed, I'd be happy with just making this fail more gracefully :+1:
