### ISSUE TITLE
ansible 1.9.4 missing 'cryptography' Python module

### ISSUE THREAD

**Issue by ncdc** [Homebrew/homebrew#47258]
The ansible 1.9.3 bottle includes the 'cryptography' Python module, which is required when importing `OpenSSL.crypto` (which my team's playbook does). This was removed by https://github.com/Homebrew/homebrew/commit/3413a091ad28c69dea9529ab593f903e34410b4c#diff-5ea2ef50061cead169e37867b860b42a.

@xu-cheng is there a way around this, or is the solution just to bring `cryptography` back?

**Comment by tdsmith** [comment]
`cryptography` should be restored.

**Comment by tdsmith** [comment]
(along with `enum34` and `cffi`)
