### ISSUE TITLE
geda-gaf/gschem problems

### ISSUE THREAD

**Issue by noqsi** [Homebrew/homebrew#47263]
The latest gschem seems to bypass XDarwin and display by other means. I see the following problems:

1. Rendering problems where moved objects leave a checkerboard pattern behind them.

2. No three button mouse emulation.

3. No cut in OSX and paste in gschem.

I can't figure out how to downgrade.

**Comment by bfontaine** [comment]
This seems like a gschem issue rather than an Homebrew one. You should report it to gschem’s developpers.

**Comment by noqsi** [comment]
Except that Homebrew version 1.8.2 worked. The problem only appeared with 1.8.2_1. Problems 2 and 3 have cannot be gschem, because those things are the responsibility of the X11 environment. 1.8.2 operated through XDarwin, but 1.8.2_1 does something different that I don't understand.

**Comment by mikemcquaid** [comment]
Does this work when building `gschem` from source outside Homebrew?

**Comment by noqsi** [comment]
Same behavior for a fresh build from source. So, I guess something has changed in my X11 setup. Thanks.
