### ISSUE TITLE
Current kibana doesn't work with current elasticsearch

### ISSUE THREAD

**Issue by Drewshg312** [Homebrew/homebrew#47261]
Hi!
Sorry to disturb, but just wondering if the current version of `kibana` could be updated?
Because the current version available in homebrew doesn't work anymore with the current versions of elasticsearch and logstash available... This kinda doesn't make sense...
I'm wondering if it's done for some practical reason?
Thank you!

**Comment by DomT4** [comment]
Track https://github.com/Homebrew/homebrew/pull/46593. We're working on it.
