### ISSUE TITLE
Should std_cmake_args include -DNDEBUG by default?

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew#47297]
Related to #47145.

CMake sets its default flags for Release builds as "-O3 -DNDEBUG". ([AppleClang-CXX config](https://github.com/Kitware/CMake/blob/a100888b757ec48781d873824e13b0255602162d/Modules/Compiler/AppleClang-CXX.cmake) and [AppleClang-C config](https://github.com/Kitware/CMake/blob/a100888b757ec48781d873824e13b0255602162d/Modules/Compiler/AppleClang-C.cmake) includes [Clang config](https://github.com/Kitware/CMake/blob/a100888b757ec48781d873824e13b0255602162d/Modules/Compiler/Clang.cmake), which includes [GCC config](https://github.com/Kitware/CMake/blob/a100888b757ec48781d873824e13b0255602162d/Modules/Compiler/GNU.cmake)).

Should `-DNDEBUG` be specified for all Release builds? It saves having to explicitly add it in formulas, at least, and I think it makes more sense to turn on assertions on a case-by-case basis than to leave it unspecified.

**Comment by mikemcquaid** [comment]
Yeh, I think this makes sense. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by aw1621107** [comment]
Alright, opened at PR as #47378

**Comment by DomT4** [comment]
Closing in favour of the PR.
