### ISSUE TITLE
Error on "brew update" on OS X 10.11.

### ISSUE THREAD

**Issue by perdona** [Homebrew/homebrew#47309]
Error: undefined method 'option_names' for #<Dependency: "cd-discid" []>

`/usr/local/Library/Homebrew/software_spec.rb:188:in 'add_dep_option'
/usr/local/Library/Homebrew/software_spec.rb:156:in 'depends_on'
/usr/local/Library/Homebrew/formula.rb:1821:in 'block in depends_on'
/usr/local/Library/Homebrew/formula.rb:1821:in 'each'
/usr/local/Library/Homebrew/formula.rb:1821:in 'depends_on'
/usr/local/Library/Formula/abcde.rb:17:in '<class:Abcde>'
/usr/local/Library/Formula/abcde.rb:1:in 'load_formula'
/usr/local/Library/Homebrew/formulary.rb:23:in 'module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in 'load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in 'load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:85:in 'load_file'
/usr/local/Library/Homebrew/formulary.rb:76:in 'klass'
/usr/local/Library/Homebrew/formulary.rb:72:in 'get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in 'factory'
/usr/local/Library/Homebrew/cmd/update.rb:204:in 'block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in 'each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in 'report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in 'update'
/usr/local/Library/brew.rb:124:in '<main>'`

**Comment by DomT4** [comment]
Does it reproduce if you `brew update` again?

**Comment by DomT4** [comment]
Let us know if we can help further here, Thanks!

**Comment by perdona** [comment]
No, it does not. Everything's running smooth.
Posted to let u know.

Thanks!



*--*
*Caio Perone Perdona*
*Python Full Stack Web Developer*
*mail**: perdona@gmail.com <perdona@novasingular.com.br>*

*mobile: (16) 99235-3202*
*skype: c.perdona*

*"**Every man dies, not every man truly lives."*

**Comment by DomT4** [comment]
Great! Thanks for the confirmation.
