### ISSUE TITLE
fail to install

### ISSUE THREAD

**Issue by frazac** [Homebrew/homebrew#47308]
Hello
after run
`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
following a sass setup tutorial here https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/#snow-leopard

`brew doctor`
reply
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: The system curl on 10.6 and below is often incapable of supporting
modern secure connections & will fail on fetching formulae.
We recommend you:
  brew install curl
```

I've already try other solutions but nothing apparently works...
thanks!

**Comment by crd** [comment]
What exactly are you experiencing? Are you sure homebrew failed to install? The output of `brew doctor` suggests that brew is at least partially functional.

**Comment by DomT4** [comment]
Let us know if we can help further here, Thanks!
