### ISSUE TITLE
Poco library

### ISSUE THREAD

**Issue by ashkan2200** [Homebrew/homebrew#47317]
Hi,
Is there anyway to compile Poco library both as static and dynamic library?

**Comment by mikemcquaid** [comment]
Not in Homebrew currently, sorry. If you'd like to add that: could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
