### ISSUE TITLE
git-annex-webapp missing

### ISSUE THREAD

**Issue by kenzierocks** [Homebrew/homebrew#47346]
I just updated `git-annex` to `5.20151218` and `git-annex-webapp` has disappeared. It seems that whatever used to hold `git-annex-webapp` is also missing, because restoring the old version doesn't work.

**Comment by kfrost89** [comment]
I am having the same issue. I am also on git-annex-5.20151218.

**Comment by dunn** [comment]
Does building git-annex outside Homebrew (through Cabal, I guess) have the same issue?

**Comment by kenzierocks** [comment]
Looks like it may have been removed or something recently, building from source gives the same result: no webapp.

**Comment by kenzierocks** [comment]
Considering https://git-annex.branchable.com/forum/Confusion_about_Webapp___40__on_OSX__41__/, it looks like Homebrew must enable it somehow?

**Comment by mikemcquaid** [comment]
> According to https://git-annex.branchable.com/install/fromsource/ I think we're missing some C headers for the build.

If that's the case, probably need a pull request to add the extra dependency.

**Comment by kfrost89** [comment]
Any update on this?

**Comment by dunn** [comment]
@kfrost89 if you feel like picking it up, that'd be awesome! Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions.

**Comment by zmwangx** [comment]
This seems to be a problem with the bottle. I can verify that with bottled `git-annex` (the El Cap bottle):

```
> git annex webapp
Invalid argument `webapp'
```

But with a build from source `git annex webapp` works just fine. (I did a default build, i.e. without `--with-git-union-merge`.)

The bottling issue should better be fixed somehow, since a source build needs to build a gazillion Haskell packages, and it took me 26 min with eight threads on a quad core MBP 15''... Definitely not as scary as ghc, but still a little bit too long.

**Comment by zmwangx** [comment]
> I think we're missing some C headers for the build.

No, nothing's missing. The page lists libgnutls, libgsasl, libxml2, and zlib. libxml2 and zlib are shipped with OS X; gnutls and gsasl are listed as dependencies in the formula already.

**Comment by csstaub** [comment]
This also works for me if I build from source. To avoid accidentally building git-annex without the webapp (and S3 support which is also missing in the bottle), the formula could explicitly pass the build flags to cabal to force them to be built. That way, the build would fail if something is missing or broken.

**Comment by mikemcquaid** [comment]
> To avoid accidentally building git-annex without the webapp (and S3 support which is also missing in the bottle), the formula could explicitly pass the build flags to cabal to force them to be built. That way, the build would fail if something is missing or broken.

That's a good idea. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by zmwangx** [comment]
> the formula could explicitly pass the build flags to cabal to force them to be built.

Apparently the problem with that is the sheer number of flags. There are 25 flag in 5.20151218, and it's not clear which ones should be enforced. Also it will make this formula a hell to maintain, because flags seem to change rather rapidly. Comparing git master to 5.20151218, five flags have already been removed.

**Comment by csstaub** [comment]
As a compromise, we could just force the webapp flag to be on for now. I feel like most folks that use git-annex will probably want the webapp to be present. With the webapp being a core part of the app it won't go away anytime soon. Happy to submit a pull request for this once I can get to it over the weekend.

**Comment by zmwangx** [comment]
There's also another guy have problem with s3. #47737

**Comment by mikemcquaid** [comment]
> As a compromise, we could just force the webapp flag to be on for now. I feel like most folks that use git-annex will probably want the webapp to be present. With the webapp being a core part of the app it won't go away anytime soon. Happy to submit a pull request for this once I can get to it over the weekend.

@csstaub Sounds good

**Comment by zmwangx** [comment]
The 5.20151218_1 bottle seems to be working, although nothing was changed.

**Comment by csstaub** [comment]
That makes sense, the dependencies have been fixed in the meantime so a rebuild would include the webapp as well now. Setting the build flags to +webapp should make sure the build fails in the future if there is a dependency/version conflict instead of silently failing.

**Comment by zmwangx** [comment]
I'm not convinced. As I pointed out there was another guy having problem with the s3 (also a flag). There could be others having other problems. This type of makeshift flag stacking has quite some potential of becoming unmanageable.

**Comment by csstaub** [comment]
Yes, the same problem applies with, because aws 0.13.0 is incompatible with cereal 0.5.1.0.

**Comment by zmwangx** [comment]
You probably misinterpreted my comment. I wasn't unconvinced about dependency being fixed. I'm unconvinced about the flag stacking approach to deal with problems.

The ideal approach would be to add tests. I know it would be hard, because (1) philosophically speaking, the web app part is out of Homebrew's scope; (2) technically I'm not sure how to test it without introducing side effects.

**Comment by csstaub** [comment]
Why is adding tests better than setting flags? I don't see how tests are easier to manage than build flags.

**Comment by zmwangx** [comment]
If a test fails, you still have something (which may be enough for some people). If the build fails, you get absolutely nothing. Outdated build flags are definitely worse than outdated tests.

On management:

> I don't see how tests are easier to manage than build flags.

Okay. Or don't even add tests.

**Comment by csstaub** [comment]
Well, if you want to add tests I'm sure the maintainers will be happy to accept a pull request.

**Comment by zmwangx** [comment]
As I said I don't know how to test git-annex-webapp without side effects (i.e. snatching a port).

**Comment by kfrost89** [comment]
Seems to be working now. Now we are just waiting for the 6.* update :) :)

**Comment by mikemcquaid** [comment]
> As I said I don't know how to test git-annex-webapp without side effects (i.e. snatching a port).

It's fine to snatch a port for the duration of the test; you can `fork` and then kill it afterwards.

**Comment by zmwangx** [comment]
> It's fine to snatch a port for the duration of the test.

But that has the potential of being blocked by firewall, no?

**Comment by mikemcquaid** [comment]
@zmwangx Firewall only blocks connections from non-localhost hosts.

**Comment by zmwangx** [comment]
> Firewall only blocks connections from non-localhost hosts.

True. Then a webapp could potentially be something like

```ruby 
  test do
    # make sure git can find git-annex
    ENV.prepend_path "PATH", bin
    system "git", "annex", "test"

    # test webapp
    begin
      pid = Process.spawn "#{bin}/git-annex", "webapp", "--listen=localhost"
      sleep 3
      # still alive after three seconds
      assert_nil Process.wait(pid, Process::WNOHANG)
    ensure
      Process.kill "TERM", pid
      Process.wait pid
    end
  end
```

**Comment by mikemcquaid** [comment]
Yep but ideally with some sort of actual HTTP request to it.

**Comment by zmwangx** [comment]
> ideally with some sort of actual HTTP request to it.

That would require parsing the output of `git-annex webapp --listen`, which contains the auth token.

**Comment by mikemcquaid** [comment]
@zmwangx Or even just that the socket is open or something?

**Comment by mikemcquaid** [comment]
@zmwangx But parsing the output would be ideal.

**Comment by zmwangx** [comment]
> Or even just that the socket is open or something?

Port number is in the output, so still needs parsing.

> But parsing the output would be ideal.

Hear. I know little Ruby though. Can you establish a pipe connected to the subprocess's stdout, then read from the pipe in real time?

**Comment by mikemcquaid** [comment]
@zmwangx Yup. I think `popen3` is probably what you want here; it gives you a lot of flexibility.

**Comment by zmwangx** [comment]
Cool. Then something like this would work:

```ruby
Open3.popen3("git-annex", "webapp", "--listen=localhost") do |i,o,e,t|
  begin
    url = o.gets.chomp
    while url do
      response = Net::HTTP.get_response(URI(url))
      case response
      when Net::HTTPSuccess then
        break
      when Net::HTTPRedirection then
        url = URI.join(url, response["location"])
      else
        raise "HTTP #{response.code}"
      end
    end
  ensure
    Process.kill("TERM", t.pid)
  end
end
```

Not sure this is the most efficient way to handle redirects though (or maybe just shell out to curl?).

**Comment by zmwangx** [comment]
The above code should make sure initial url is non-null, and should have a timeout associated to the HTTP request.

**Comment by jberkel** [comment]
@zmwangx Wouldn't it be enough to just check the exit code of `git annex webapp` ? If it's not compiled in it will exit with 1. Thorough tests are great but not always necessary, and add additional maintenance costs.

**Comment by jberkel** [comment]
I've just installed 6.20160126 via bottle which does have the webapp compiled in, maybe something has changed upstream / got fixed already?

**Comment by DomT4** [comment]
This was fixed, aye.
