### ISSUE TITLE
Too frequent package compilation instead of bottles

### ISSUE THREAD

**Issue by hyiltiz** [Homebrew/homebrew#47352]
`homebrew doctor` warns me to keep an updated homebrew database and packages, telling me this:

> You haven't updated for at least 24 hours, this is a long time in brewland!

However, when I try to update my packages by `brew update` then `brew upgrade`, homebrew starts compiling, instead of installing precompiled packages (called bottles), some packages that I would never try to compile myself, such as `gcc`, `macvim`, `octave`. I can accept doing it only once for initial installation if necessary, but for every update, compiling gcc (and others) every week is not sane for a MacBook Air user.

Is there any switch to tell homebrew to *NOT* install packages that requires compiling unless necessary by dependency, or manually stated to do so? I could not find such a switch by searching through the internet (or in the official documentation), and I prefer not to pin every single package which requires finding out which packages need compiling, then remembering to update those pinned packages from time to time, which should be a package manager's job.

For example, it seems that homebrew is trying to compile the whole gcc just to update R here:

```
==> Installing dependencies for homebrew/science/r: gcc
==> Installing homebrew/science/r dependency: gcc
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-5.3.0/gcc-5.3.0.tar.bz2
==> Downloading from http://gnu.mirror.vexxhost.com/gcc/gcc-5.3.0/gcc-5.3.0.tar.bz2
######################################################################## 100.0%
==> Patching
patching file gcc/jit/Make-lang.in
patching file gcc/jit/jit-playback.c
Hunk #1 succeeded at 2470 with fuzz 2 (offset 54 lines).
==> ../configure --build=x86_64-apple-darwin15.0.0 --prefix=/usr/local/Cellar/gcc/5.3.0 --libdir
==> make bootstrap
```

**Comment by dunn** [comment]
> Is there any switch to tell homebrew to NOT install packages that requires compiling unless necessary by dependency, or manually stated to do so? 

This should already be the default behavior.  Could you post your `brew config`? Thanks!

**Comment by DomT4** [comment]
Worth noting some of the packages you specified are quite special:

* `gcc` only pours the bottle if you have the [CLT installed](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gcc.rb#L62-L66).
* `macvim` doesn't provide a bottle because doing so would force users to install Homebrew's Python to use it.
* `octave` requires GCC (to provide Fortran) at [runtime](https://github.com/Homebrew/homebrew-science/blob/master/octave.rb#L88) which would force the `gcc` installation.

**Comment by hyiltiz** [comment]
@dunn Here is the output of `brew config`:

```BASH
~ $ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 45abe7080fea0708320226b47fb1d99cbba7f75a
Last commit: 2 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
OS X: 10.11.1-x86_64
Xcode: 7.2
CLT: N/A
Clang: 7.0 build 700
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /Users/hyiltiz/anaconda/bin/python => /Users/hyiltiz/anaconda/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.4/bin/ruby
Java: 1.8.0_60
```

@DomT4 Using the list notation correspondingly:

- I thought I have CLT installed already. Is there any way to check? Not having to compile `gcc` is *really* nice.
- $ I have installed python via homebrew (though `anaconda` package). But `macvim` seems to ignore this. I don't understand why providing bottles will necessitate using Homebrew's Python, though.
```BASH
~ $ ll /usr/local/bin/python3
lrwxr-xr-x 1 hormetyiltiz admin 35 Dec 24 15:31 /usr/local/bin/python3 -> ../Cellar/python3/3.5.1/bin/python3*
~ $ which python3
/usr/local/bin/python3
~ $ which python2
/Users/hormetyiltiz/anaconda/bin/python2
~ $ which python
/Users/hormetyiltiz/anaconda/bin/python
```

- Depending on `gcc` for `octave` is understandable, of course, but having to build the whole gcc for it is not. I guess I had to compile it since something about CLT might be misconfigured? BTW, to avoid having to compile octave from scratch every time it has an update, I have already pinned it (also `macvim`). But this will only lead to pinning more and more packages which is, I believe, not how I should be using Homebrew.

**Comment by mikemcquaid** [comment]
> I thought I have CLT installed already. Is there any way to check? Not having to compile gcc is really nice.

You don't. You can install it with `xcode-select --install`

> $ I have installed python via homebrew (though anaconda package). But macvim seems to ignore this. I don't understand why providing bottles will necessitate using Homebrew's Python, though.

Bottles need to be built against a specific Python so we'd need to mandate the Homebrew Python for everyone.

> I guess I had to compile it since something about CLT might be misconfigured?

Yes.

**Comment by DomT4** [comment]
Let us know if we can help further here, Thanks!
