### ISSUE TITLE
Mac OS X 10.11 brew install boost-python end up in dead loop

### ISSUE THREAD

**Issue by madcarrot** [Homebrew/homebrew#47359]
I am trying to get caffe, which needs `boost-python` installed on my Mac.

When I installed `boost-python` with `brew install --build-from-source --fresh -vd boost-python`, it ended in dead loops and never finished. I could only interrupt with Ctrl+C.

Here are the error messages. The following message just loop endlessly...

    <scratch space>:6:1: note: expanded from here
    boost_static_assert_typedef_508
    ^
    In file included from libs/coroutine/src/posix/stack_traits.cpp:22:
    In file included from ./boost/thread.hpp:24:
    In file included from ./boost/thread/future.hpp:40:
    In file included from ./boost/thread/csbl/memory/unique_ptr.hpp:16:
    ./boost/move/unique_ptr.hpp:554:7: warning: unused typedef     'boost_static_assert_typedef_555' [-Wunused-local-typedef]
          BOOST_STATIC_ASSERT(( !::boost::move_upmu::missing_virtual_destructor
      ^
    ./boost/static_assert.hpp:170:16: note: expanded from macro 'BOOST_STATIC_ASSERT'
                   BOOST_JOIN(boost_static_assert_typedef_, __LINE__) BOOST_STATIC_ASSERT_UNUSED_ATTRIBUTE
                   ^
    ./boost/config/suffix.hpp:544:28: note: expanded from macro 'BOOST_JOIN'
    #define BOOST_JOIN( X, Y ) BOOST_DO_JOIN( X, Y )
                               ^
    ./boost/config/suffix.hpp:545:31: note: expanded from macro 'BOOST_DO_JOIN'
    #define BOOST_DO_JOIN( X, Y ) BOOST_DO_JOIN2(X,Y)
                                  ^
    ./boost/config/suffix.hpp:546:32: note: expanded from macro 'BOOST_DO_JOIN2'
    #define BOOST_DO_JOIN2( X, Y ) X##Y
                                   ^

I have tried using other versions of boost-python but there's no luck...

I'm new to OS X and don't know what to do. Googling yielded some similar cases while people are actually using boost, but it I couldn't find any fixes for installing boost... Any help is greatly appreciated. 

OS condition:

 - Just formatted hard drive and reinstalled Mac OS X
 - installed Xcode, homebrew
 - installed pyenv with homebrew
 - installed anaconda with pyenv
 - installed hdf5, opencv with homebrew
 - edited formulas for other caffe dependencies with:

.

    def install
      # ADD THE FOLLOWING:
      ENV.append "CXXFLAGS", "-stdlib=libstdc++"
      ENV.append "CFLAGS", "-stdlib=libstdc++"
      ENV.append "LDFLAGS", "-stdlib=libstdc++ -lstdc++"
      # The following is necessary because libtool likes to strip LDFLAGS:
      ENV["CXX"] = "/usr/bin/clang++ -stdlib=libstdc++"

**Comment by bfontaine** [comment]
Any reason you need to build from source? You could use `brew install boost-python` to get a pre-packaged version.

**Comment by tdsmith** [comment]
Are you sure it's repeating the same messages? It is normal that boost takes quite a while to build (30 minutes or more).

**Comment by madcarrot** [comment]
@bfontaine Thanks for replying! I did try without `build-from-source` but the same message still appears... :S

**Comment by madcarrot** [comment]
@tdsmith Thanks for replying! 

The only thing that changes in these messages are the numbers in 

    <scratch space>:6:1: note: expanded from here
    boost_static_assert_typedef_508

And the other parts stayed the same.

I knew something went wrong because it worked before I did something else wrong and reinstalled the OS :S

**Comment by DomT4** [comment]
Does this still reproduce with the new Boost et al.?

**Comment by DomT4** [comment]
Please let us know if we can assist further here, Thanks!

**Comment by madcarrot** [comment]
Sorry for the long time inactivity - I sorta gave up after a while until I again had to install it.

I was able to install boost and boost-python with homebrew after I did the following:
I reinstalled the OS, and then before I installed boost and boost-python from homebrew, I installed boost with macport and then export PATH="/opt/local/bin:/opt/local/sbin:$PATH" (this step was written in  ~/.bash_profile by macports) and then brew installed boost and boost-python and it worked. I would guess it's because brew install boost would actually have some dependencies that are satisfied by having boost in the first place... Also this worked for boost 1.60 but not 1.58...
