### ISSUE TITLE
formula libxml2 install option --with-python is ignored

### ISSUE THREAD

**Issue by ruffni** [Homebrew/homebrew#47366]
in formula libxml2 whether you type the option "--with-python" or not is ignored since on line 43 "--without-python" is passed to ./configure anyhow. had to edit the formula manually to get python-support installed.

**Comment by DomT4** [comment]
It isn't ignored. We handle the Python element ourselves [later in the formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libxml2.rb#L49-L55). We just don't let configure handle that stage itself.

**Comment by ruffni** [comment]
so why doesn't it compile for python altough i ran it with "--with-python" and worked when i ignored line 43?

**Comment by DomT4** [comment]
If you run a standard, unmodified `brew install libxml2 --with-python` and then do `brew ls libxml2` you should find:
```
/usr/local/Cellar/libxml2/2.9.3/lib/libxml2.2.dylib
/usr/local/Cellar/libxml2/2.9.3/lib/cmake/libxml2/libxml2-config.cmake
/usr/local/Cellar/libxml2/2.9.3/lib/pkgconfig/libxml-2.0.pc
/usr/local/Cellar/libxml2/2.9.3/lib/python2.7/ (6 files)
/usr/local/Cellar/libxml2/2.9.3/lib/ (3 other files)
```

In there somewhere.

**Comment by tdsmith** [comment]
I think Dominyk is right. Please let us know if we can help with anything. The output of `brew gist-logs libxml2` after installing the unmodified Homebrew formula will be helpful if this does not appear resolved to you.
