### ISSUE TITLE
homebrew.bintray->cloudfront.net certificate issue

### ISSUE THREAD

**Issue by kaidokert** [Homebrew/homebrew#47373]
Bottle installations fail here, after el capitan update with all the latest fixes and patches.

The root cause seems to be a deprecated root certificate on *.cloudfront.net.

`curl -vvL https://homebrew.bintray.com/bottles/sqlite-3.9.2.el_capitan.bottle.tar.gz` will result in:
...
```
*   Trying 54.230.141.18...
* Connected to d29vzk4ow07wi7.cloudfront.net (54.230.141.18) port 443 (#1)
* SSL certificate problem: Invalid certificate chain
* Closing connection 1
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html
```

The root cert  in question: Certificate SHA1 Thumbprint: a1 db 63 93 91 6f 17 e4 18 55 09 40 04 15 c7 02 40 b0 ae 6b

According to : https://www.symantec.com/page.jsp?id=roots
```
Description: This root CA is the root used for Secure Site Pro Certificates, Premium SSL Certificates
and Code Signing Certificates. Effective December 1, 2015, Symantec has discontinued the use of 
the VeriSign G1 root for issuance of public SSL certificates. This root CA will be used to issue 
non-public SSL certificates. Browsers/root store operators are encouraged to remove/untrust this 
root from their root stores.
```

The root was apparently removed, as the same link will not open in Safari or Chrome either, Firefox is still OK with it.

`openssl s_client -showcerts -connect d29vzk4ow07wi7.cloudfront.net:443  < /dev/null` 
does not yet complain either.

**Comment by mikemcquaid** [comment]
I can't reproduce this here. What country are you in?

**Comment by kaidokert** [comment]
I'm in US/CA. I guess it is the same certificate talked about here :
http://www.itworld.com/article/3014651/google-to-revoke-trust-in-a-symantec-root-certificate.html

**Comment by mikemcquaid** [comment]
Not really sure what we can do about this. Suffice to say if it affects CloudFront I'm sure it'll be addressed fairly rapidly.

**Comment by tdsmith** [comment]
I see:

```
*   Trying 54.240.160.235...
* Connected to d29vzk4ow07wi7.cloudfront.net (54.240.160.235) port 443 (#1)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.cloudfront.net
* Server certificate: Symantec Class 3 Secure Server CA - G4
* Server certificate: VeriSign Class 3 Public Primary Certification Authority - G5
```

so it's not chained to the G1 root. Are you still seeing this issue?

**Comment by kaidokert** [comment]
Not seeing this on any of the machines that i have, may have been temporary cloudfront propagation thing or something - i think its good to close.
