### ISSUE TITLE
Fails to Install Php56 with Imap Extensiton

### ISSUE THREAD

**Issue by Abhi150688** [Homebrew/homebrew#47384]
Hi,
I am trying to install PHP56 with Imap extension however, whenever I run the command brew install php56 --with-imap...the process fails at the last step. 

The error message shown is: 
Warning!  dlname not found in /usr/local/Cellar/php56/5.6.16/libexec/apache2/libphp5.so.
Assuming installing a .so rather than a libtool archive.
chmod 755 /usr/local/Cellar/php56/5.6.16/libexec/apache2/libphp5.so
Died at /usr/sbin/apxs line 558.
make: *** [install-sapi] Error 13

The snapshot of the terminal has been attached for your reference. 
Thanks. 
![screen shot 2015-12-26 at 11 56 45 am](https://cloud.githubusercontent.com/assets/9885740/12005389/5be68b18-abc8-11e5-9a47-bd0f3859f172.png)

**Comment by dunn** [comment]
This issue was moved to Homebrew/homebrew-php#2703
