### ISSUE TITLE
Solr 5.4.0 bin/post utility not running due to invalid classpath

### ISSUE THREAD

**Issue by maxpsq** [Homebrew/homebrew#47414]
I tried to run the bin/post utility and I found out there's a hardcoded classpath $SOLR_HOME/dist/solr-core-*.jar in it (see $SOLR_TIP and $TOOL_JAR in post) that's not compliant with the jar location for this formula $SOLR_HOME/libexec/dist/.

Here's what I get
post -c geonames -params "separator=%09" -type text/csv allCountries.txt

/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java -classpath /usr/local/Cellar/solr/5.4.0/dist/solr-core-*.jar -Dauto=yes -Dparams=separator=%09 -Dtype=text/csv -Dc=geonames -Ddata=files org.apache.solr.util.SimplePostTool ../dumps/allCountries.txt
Error: could not find or load main class org.apache.solr.util.SimplePostTool

**Comment by ciarant** [comment]
You're correct - apologies, I should have made a note of that. I'll see if I can tweak the formula so that it corrects the path in bin/post.

**Comment by ciarant** [comment]
New PR submitted 47420

**Comment by maxpsq** [comment]
Well, done! It works now. Thanks
