### ISSUE TITLE
How to make automatic updates from Github releases

### ISSUE THREAD

**Issue by iBobik** [Homebrew/homebrew#47419]
I am going to publish my first formula and I am not sure how to handle updates.

It seems most of formulaes there refers to a specific archive with a version, so when there is new release, somebody have to change version manually, haven't they?

How to configure formula to always refer to latest Github release (version and artifact)?

**Comment by dunn** [comment]
> How to configure formula to always refer to latest Github release (version and artifact)?

We specifically don't allow that, since we want to be able to ensure the integrity of the release using SHA256 and also test each update to make sure it works and doesn't break other software that depends on it.

**Comment by iBobik** [comment]
Wow, and you are able to do it manually for all 3 thousands formulaes?



Jan Pobořil

2015-12-27 16:33 GMT+01:00 Alex Dunn <notifications@github.com>:

**Comment by dunn** [comment]
We have a great community of contributors who help!
