### ISSUE TITLE
allow 'with-win64' option for 64 bit wine builds

### ISSUE THREAD

**Issue by kaazoo** [Homebrew/homebrew#47428]
http://reviews.llvm.org/D1623 seems to be fixed as of Sep 17 2015, so 64 bit builds of wine might work again?

**Comment by mikemcquaid** [comment]
Could you verify it yourself and create a pull request if it's desired?

**Comment by kaazoo** [comment]
https://github.com/kaazoo/homebrew/commit/cd0f1db42e0a8228740fce347604d1cfe3a51364 may not be the perfect solution, but it works for me. wine and wine64 are installed together.

Clang 3.8-HEAD is required for the wine64 build:
```brew install llvm --with-clang --with-clang-extra-tools --with-compiler-rt --with-libcxx --with-lld --with-rtti --HEAD```

**Comment by yurikoles** [comment]
As I see from wine configure output it can also be built with gcc-4.4 and up. We just need to pass CC=gcc and CXX=g++-5 env vars.

llvm --HEAD is now broken btw. #50032

**Comment by mikemcquaid** [comment]
@kaazoo Once this works with a stable Clang we'll accept something like that as a PR.

**Comment by yurikoles** [comment]
@michaelpq please help me pass CC=gcc and CXX=g++-5 in formulae.

**Comment by mikemcquaid** [comment]
@yurikoles We need it to work with `clang`.

**Comment by michaelpq** [comment]
Note: I am not a committer of homebrew :)
