### ISSUE TITLE
brew doctor doesn't check permissions for /Library/Caches/Homebrew

### ISSUE THREAD

**Issue by danielcompton** [Homebrew/homebrew#47435]
I created a new user account on my computer and removed my old Homebrew installation with the uninstaller script. I then tried to setup Homebrew on my new account. However I was getting install errors:

```
Error: Permission denied - /Library/Caches/Homebrew/Formula/ack.brewing
Failed in installing ack
```

When I ran `brew doctor` no problems were reported. However running 

```sh
sudo chown -R $USER /Library/Caches/Homebrew/
```

let me install to Homebrew afterwards.

It seems like there might be two issues here:

- The uninstall script doesn't remove caches from `/Library/Caches/Homebrew`
- `brew doctor` doesn't check permissions in `/Library/Caches/Homebrew`

I checked for similar issues and couldn't find any, apologies if this is a duplicate.

**Comment by mikemcquaid** [comment]
> brew doctor doesn't check permissions in /Library/Caches/Homebrew

It does seem to:
https://github.com/Homebrew/homebrew/blob/616f0f4f1863f19e6a64276ac5fbaf010d99b0a4/Library/Homebrew/cmd/doctor.rb#L520-L532

Any ideas why this wouldn't have caught your case?

**Comment by danielcompton** [comment]
I had created a user called temp and setup Homebrew. Then I renamed it to Daniel, and created a new user danielcompton. I got the error when running as danielcompton. 

One possibility is that the cache folder was writable but not the formulas themselves?

The only thing I can think of is that they were owned by the other user and writable but

**Comment by mikemcquaid** [comment]
@danielcompton Thanks. Given that `doctor` is checking this and we've got better permission fixing actively being worked on (https://github.com/Homebrew/homebrew/pull/45934) I'm going to close this out for now. Thanks for the report though; will help keep an eye on this.
