### ISSUE TITLE
brew php70-redis in only-head formula

### ISSUE THREAD

**Issue by naffan2014** [Homebrew/homebrew#47448]
why i type "brew install php70-redis"
and he told me 
"Error: homebrew/php/php70-redis is a head-only formula
Install with `brew install --HEAD homebrew/php/php70-redis`"

what is this mean?

and when i type brew install --HEAD homebrew/php/php70-redis ,he gave me a fatal error

==> Installing php70-redis from homebrew/php
==> Cloning https://github.com/phpredis/phpredis.git
Updating /Library/Caches/Homebrew/php70-redis--git
==> Checking out branch php7
==> /usr/local/opt/php70/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php70-redis/HEAD --with-php-config=/usr/local/opt/php70/bin/php-
Last 15 lines from /Users/naffan2012/Library/Logs/Homebrew/php70-redis/02.configure:

./configure
--prefix=/usr/local/Cellar/php70-redis/HEAD
--with-php-config=/usr/local/opt/php70/bin/php-config

checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/local/Library/ENV/4.3/sed
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/private/tmp/php70-redis20151228-6273-1882z36':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/php/issues

what can i do?

**Comment by bfontaine** [comment]
Please read the link in the error message and follow what it says:
> READ THIS: https://git.io/brew-troubleshooting

> what is this mean?

This means the formula doesn’t provide any stable release. Using `--HEAD` you can install from the `HEAD` of the formula, which is usually unstable.

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/homebrew-php#2705
