### ISSUE TITLE
ffmpeg failed to build on 10.10

### ISSUE THREAD

**Issue by nicexe** [Homebrew/homebrew#47456]
Dependencies are all present yet it fails to build.
logs: https://gist.github.com/nicexe/1353743cffa4066d6e8f

**Comment by bfontaine** [comment]
What’s the error? I don’t see it in the logs.

**Comment by nicexe** [comment]
I am sorry. I was having problems with mplayer but I somehow had ffmpeg in my mind. I'll go ahead and create a new issue for mplayer.
