### ISSUE TITLE
tika upgrade error

### ISSUE THREAD

**Issue by gondo** [Homebrew/homebrew#47455]
==> Upgrading tika
==> Downloading https://www.apache.org/dyn/closer.cgi?path=tika/tika-app-1.11.jar
Error: Failed to download resource "tika"
Download failed: Couldn't determine mirror, try again later.

**Comment by bfontaine** [comment]
It probably depends on your location; it works for me:
```shellSession
$ brew fetch tika
==> Downloading https://www.apache.org/dyn/closer.cgi?path=tika/tika-app-1.11.jar
==> Best Mirror http://apache.mirrors.ovh.net/ftp.apache.org/dist/tika/tika-app-1.11.jar
######################################################################## 100,0%
Downloaded to: /Library/Caches/Homebrew/tika-1.11.jar
SHA1: 59cc7c4c48a6a41899ca282d925b2738d05a45a8
SHA256: 76f23849c0fe116efda3d89f9021d74415727f6f98b2860c24247c299cae719c
```

**Comment by gondo** [comment]
how can i check and change my location?

**Comment by DomT4** [comment]
No problems here. Anything flagged by `brew doctor` or are you operating behind a proxy or anything similar?

**Comment by DomT4** [comment]
Let us know if we can help further here, Thanks!
