### ISSUE TITLE
lldpd improvements

### ISSUE THREAD

**Issue by spkane** [Homebrew/homebrew#47463]
The lldpd formula should ensure that /usr/local/var/run exists, as it needs it by default.

It would also be good to include a default config at /usr/local/etc/lldpd.conf, if possible. Or at least output a message saying that this needs to be created.

**Comment by dunn** [comment]
We'd love a pull request! Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions :ok_woman:

**Comment by vincentbernat** [comment]
For `/usr/local/var/run`, if it doesn't exist by default, maybe this is not the right place. Where do other daemons place their runtime files?

As for `/usr/local/etc/lldpd.conf`, it is quite optional. No need to create it.

**Comment by DomT4** [comment]
> For /usr/local/var/run, if it doesn't exist by default, maybe this is not the right place. Where do other daemons place their runtime files?

Doesn't exist by default, but plenty of formulae create it which you can do with:
```ruby
(var/"run").mkpath
```
In the formula file.

**Comment by vincentbernat** [comment]
@spkane do you want to do the PR or should I do it?

**Comment by spkane** [comment]
@vincentbernat I'll go ahead and create a PR for it.

**Comment by spkane** [comment]
Done: https://github.com/Homebrew/homebrew/pull/47470

**Comment by DomT4** [comment]
Feel free to file additional PRs if there's anything else you want to tweak. Cheers!
