### ISSUE TITLE
Merge multiple "Warning: <directory> isn't writable." warnings into single "<parent> isn't writable." warning

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew#47462]
Please merge multiple `Warning: <directory> isn't writable.` warnings into single `<parent> isn't writable.` warning, and recommend that users `sudo chown -R $(whoami) <parent>`, to make it easier and faster for users to repair their brew environment.

**Comment by bfontaine** [comment]
Want to try a pull-request? This should help and I’m happy to answer any question: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

**Comment by DomT4** [comment]
We've been working on ditching the entire warning framework there in favour of a unified internal command: #45934.

I'm not sure it's worth making changes prior to that, but feel free to file a PR as Baptiste advises and we'll review it.

**Comment by DomT4** [comment]
Closing per the above. That's the best long-term solution going forwards rather than ripping apart the `doctor` file for a short-term rewrite. Feel free to track the linked Issue for progress, Thanks!
