### ISSUE TITLE
RabbitMQ plist can't find erlang when homebrew isn't in /usr/local.

### ISSUE THREAD

**Issue by jmcnevin** [Homebrew/homebrew#47497]
I'm currently using homebrew installed in /opt/homebrew, and I had a weird issue where the rabbitmq 3.6.0 launch agent just wouldn't do anything.  I think this line is the culprit:

https://github.com/Homebrew/homebrew/blob/master/Library/Formula/rabbitmq.rb#L87

After adding my custom homebrew path to this line, rabbitmq was able to start.

**Comment by bfontaine** [comment]
We should maybe use `#{HOMEBREW_PREFIX}` instead of `/usr/local` here.

**Comment by mikemcquaid** [comment]
> We should maybe use #{HOMEBREW_PREFIX} instead of /usr/local here.

Sounds like it :+1:
