### ISSUE TITLE
nvm ls-remote strange behavior

### ISSUE THREAD

**Issue by andriytyurnikov** [Homebrew/homebrew#47502]
https://github.com/creationix/nvm/issues/953#issuecomment-167830284

**Comment by bfontaine** [comment]
Could you please add more information about how to reproduce the bug?

**Comment by andriytyurnikov** [comment]
`nvm ls-remote`

**Comment by mistydemeo** [comment]
I can't reproduce the problem on the same OS X version using a fresh nvm install.

**Comment by mikemcquaid** [comment]
@andriytyurnikov To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by andriytyurnikov** [comment]
@mistydemeo surprisingly enough, reinstalling nvm fixed everything, sorry
