### ISSUE TITLE
install openssl fail for "404 Not Found"

### ISSUE THREAD

**Issue by caojianfeng** [Homebrew/homebrew#47516]
honeydeiMac:openssl-master caojianfeng$ brew install openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://raw.githubusercontent.com/DomT4/LibreMirror/master/OpenS

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "openssl"
Download failed: https://raw.githubusercontent.com/DomT4/LibreMirror/master/OpenSSL/openssl-1.0.2.tar.gz

my env:

硬件概览：

  型号名称：	iMac
  型号标识符：	iMac14,2
  处理器名称：	Intel Core i5
  处理器速度：	3.4 GHz
  处理器数目：	1
  核总数：	4
  L2 缓存（每个核）：	256 KB
  L3 缓存：	6 MB
  内存：	8 GB
  Boot ROM 版本：	IM142.0118.B12
  SMC 版本（系统）：	2.15f7
  序列号（系统）：	C02MX36GF8J5
  硬件 UUID：	012B19D1-61F6-5658-A791-9BF492D77FB3

系统软件概览：

  系统版本：	OS X 10.11.2 (15C50)
  内核版本：	Darwin 15.2.0
  启动宗卷：	Macintosh HD
  启动模式：	正常
  安全虚拟内存：	已启用
  系统完整性保护：	已启用
  启动后的时间长度：	9:39

$ brew -v
Homebrew 0.9.5

brew list
jpeg		libyaml		makedepend	pkg-config	xz
libtiff		lua		perl		redis

**Comment by DomT4** [comment]
You need to `brew update`. Let us know if the problem persists afterwards, Thanks!
