### ISSUE TITLE
Rebuilding downstream bottles

### ISSUE THREAD

**Issue by scpeters** [Homebrew/homebrew#47517]
I tried sending this to homebrew@librelist.com but it doesn't seem to have gone through, so I'm posting here. Apologies if it's the wrong venue.

I maintain an unofficial tap ( https://github.com/osrf/homebrew-simulation ), and we are starting to look into automatic bottle building. I have manually built a few in a clean VM, but we have a mac mini that we use for other CI things, and we'd like to try using it for bottle building. We're using something like the following command:
~~~
brew test-bot \
  --tap=osrf/simulation \
  --bottle \
  --ci-pr \
  --verbose \
  https://github.com/osrf/homebrew-simulation/pull/62
~~~

I have two questions about how to trigger rebuilds of bottles that depend on an updated formula.

1. If a formula in my tap changes and a new bottle is built, can I trigger new bottles for downstream formulae in that tap?

2. If something upstream changes (like boost), how do I detect that? Should the `test do` block catch these kinds of errors?

**Comment by mikemcquaid** [comment]
First, I believe both `--bottle` and `--verbose` are implied/added by `--ci-pr` so you can drop them. Otherwise: :+1: 


> 1. If a formula in my tap changes and a new bottle is built, can I trigger new bottles for downstream formulae in that tap?

Not automatically. `brew uses --recursive` is there to detect failures so you can manually add e.g. `revision 1` to failing bottles.

> 2. If something upstream changes (like boost), how do I detect that? Should the test do block catch these kinds of errors?

Yes; you could make a `--ci-master` build to test the latest Homebrew changes coming in.

The answer to both of this isn't ideal, I realise, and I'm definitely open to improvements to the scripts and infrastructure to make this process easier on tap maintainers.

**Comment by scpeters** [comment]
>
>
>    1. If a formula in my tap changes and a new bottle is built, can I
>    trigger new bottles for downstream formulae in that tap?
>
> Not automatically. brew uses --recursive is there to detect failures so
> you can manually add e.g. revision 1 to failing bottles.
>
Ok, so I take it this is currently how the homebrew maintainers deal with
failing bottles: by manually bumping the revision number? If the `brew uses
--recursive` test can write a junit file, that might be helpful for
triggering downstream jobs...

>
>    1. If something upstream changes (like boost), how do I detect that?
>    Should the test do block catch these kinds of errors?
>
> Yes; you could make a --ci-master build to test the latest Homebrew
> changes coming in.
>
Thanks for the tip!

> The answer to both of this isn't ideal, I realise, and I'm definitely open
> to improvements to the scripts and infrastructure to make this process
> easier on tap maintainers.
>
We'll try this and see if we have any ideas for improvements.

Thanks!

cc: @j-rivero
