### ISSUE TITLE
signing-party tries to install from download sites missing specified version 2.1

### ISSUE THREAD

**Issue by grempe** [Homebrew/homebrew#47519]
Running install fails for me with most current version of signing-party brew package.

https://github.com/Homebrew/homebrew/blob/8c6777b2b8e847d5f2b447eae532fa8ecffa6467/Library/Formula/signing-party.rb

````
$ brew install signing-party --with-rename-pgpring
==> Downloading https://mirrors.ocf.berkeley.edu/debian/pool/main/s/signing-party/signing-party_2.1.orig.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://mirrors.kernel.org/debian/pool/main/s/signing-party/signing-party_2.1.orig.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "signing-party"
Download failed: https://mirrors.kernel.org/debian/pool/main/s/signing-party/signing-party_2.1.orig.tar.gz
````

Note that I am installing using the ` --with-rename-pgpring` option since I have mutt installed as well.

If you look at the dir listing of one of the URL's specified it is missing the required tarball:

https://mirrors.ocf.berkeley.edu/debian/pool/main/s/signing-party/

This version of the file would appear to be the latest and the formula likely needs to be made to work with this new version.

````
signing-party_2.2.orig.tar.gz
````

**Comment by mikemcquaid** [comment]
Could you try and open a pull request to update the tarball location? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
