### ISSUE TITLE
Macvim failed to build on 10.11

### ISSUE THREAD

**Issue by imxuyue** [Homebrew/homebrew#47521]
Hi. I have been trying to install macvim on my computer but I don't know what's wrong. Can you help me? Thank you!
Here is the gist: https://gist.github.com/dec4280858d16fb7a667

**Comment by DomT4** [comment]
Please try temporarily removing `anaconda` from your `$PATH`. It is known to be a bit of a hell-raiser for some builds.

**Comment by imxuyue** [comment]
Thank you so much! It worked!

**Comment by DomT4** [comment]
Great! Thanks for the confirmation. Glad all is working again.
