### ISSUE TITLE
Got error when trying enable postgis extension

### ISSUE THREAD

**Issue by vyacheslavk** [Homebrew/homebrew#47524]
psql (9.4.5)

CREATE EXTENSION postgis;

ERROR:  could not load library "/usr/local/lib/postgresql/postgis-2.2.so": dlopen(/usr/local/lib/postgresql/postgis-2.2.so, 10): Symbol not found: __ZN5boost7archive18text_iarchive_implINS0_13text_iarchiveEE4loadERNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEE
  Referenced from: /usr/local/opt/sfcgal/lib/libSFCGAL.1.dylib
  Expected in: /usr/local/opt/boost/lib/libboost_serialization-mt.dylib
 in /usr/local/opt/sfcgal/lib/libSFCGAL.1.dylib

**Comment by DomT4** [comment]
Is this still a problem?

Apologies for the delay. Sometimes we get an influx of Issues and things get shoved off the front page and lost from easy view :cry:.

**Comment by DomT4** [comment]
Closing as dead but please let us know if we can help further at all. Apologies again for the delay.
