### ISSUE TITLE
brew install m4 fail to build on osx 10.8.5

### ISSUE THREAD

**Issue by koxmoz** [Homebrew/homebrew#47538]
Hello, I'm having trouble to install m4 in osx 10.8.5, I think it is a problem with clang or gcc, but I can figure out, the log, the config and doctor are here:

https://gist.github.com/koxmoz/c6f746f30306157d1161#file-brew-install-m4-fail-to-build-on-osx-10-8-5

thanks for your time!

**Comment by mikemcquaid** [comment]
@koxmoz Can you try to `brew update` and then try again? Can you install any other software e.g. `wget`? You may also need/want to fix your `brew doctor` warnings.

**Comment by koxmoz** [comment]
I try it all. updates, can't install wget (same error), fix the python warning... I think I broke something or was broke before. Because I can't compile a gcc file.. If you no have any idea, I just re install the os...

**Comment by mistydemeo** [comment]
Can you please provide the `brew gist-logs m4` output? This doesn't have all the info we need to troubleshoot.

**Comment by koxmoz** [comment]
no logs https://gist.github.com/koxmoz/59536e730a38b92486bd#file-gist-logs

**Comment by mistydemeo** [comment]
Oh, it looks like it was building xz when it failed. Try `brew gist-logs xz`.

**Comment by koxmoz** [comment]
https://gist.github.com/6a068d5cc691cc286e0d

**Comment by mistydemeo** [comment]
It looks like the compiler crashed while building a test program:

```
Stack dump:
0.	Program arguments: /usr/bin/clang -cc1 -triple x86_64-apple-macosx10.8.0 -emit-obj -disable-free -disable-llvm-verifier -main-file-name conftest.c -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 236.3 -resource-dir /usr/bin/../lib/clang/5.1 -isystem /usr/local/include -isystem /usr/include/libxml2 -isystem /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -Os -fdebug-compilation-dir /private/tmp/xz20160103-2572-1htu0mn/xz-5.2.2 -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.8.0 -fencode-extended-block-signature -fdiagnostics-show-option -vectorize-loops -vectorize-slp -o /var/folders/fj/kxvjsxx9197g9xzq4wry1ht40000gn/T/conftest-a89a9b.o -x c conftest.c 
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'conftest.c'.
4.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@main'
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin12.5.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************
```

Are you using a hackintosh?

**Comment by mikemcquaid** [comment]
Or a VM?

**Comment by koxmoz** [comment]
yes its a hackintosh...

**Comment by mistydemeo** [comment]
Unfortunately the error you're seeing is something we see a lot on Hackintoshes, and we're not really able to provide any advice for it. Sorry! :( Hope you can get it sorted.
