### ISSUE TITLE
wine failed to build on OS X 10.7.5

### ISSUE THREAD

**Issue by robmallo** [Homebrew/homebrew#47530]
I've tried many times but can't get wine to build. First it asked for a more up to date gcc, so I brewed it and then it started giving the following error:

`=> make dlls/winemac.drv/Makefile`
`Error: inreplace failed`
`dlls/winemac.drv/Makefile:`
`expected replacement of "-gstabs+" with ""`

I had a look around and reinstalled all the dependecies with "--universal" but it's still giving the same error. I've also tried using the option `--with-gcc` without luck.

gist: https://gist.github.com/8d20ee89470b9c21be50

Thanks in advance.

**Comment by DomT4** [comment]
Should be fixed by https://github.com/Homebrew/homebrew/commit/87badc6eeafd7ee151718ec177e4648cf714d9f9. Sorry about that.

Thanks for the report!
