### ISSUE TITLE
ipmitool link broken

### ISSUE THREAD

**Issue by jeunito** [Homebrew/homebrew#47543]
The link for the ipmitool might need updating. I ran 

```
brew install ipmitool
```

and got the following:

```
$ brew install ipmitool
==> Downloading https://downloads.sourceforge.net/project/ipmitool/ipmitool/1.8.15/ipmitool-1.8.15.tar.bz2

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "ipmitool"
Download failed: https://downloads.sourceforge.net/project/ipmitool/ipmitool/1.8.15/ipmitool-1.8.15.tar.bz2
```

**Comment by DomT4** [comment]
Sourceforge appears to be having some issues tonight with the redirect from SF to mirror, seen a few of these. Usually self-resolves in a few hours.

Added a mirror in https://github.com/Homebrew/homebrew/commit/db9b9d34f15949155f222dba076b4eac6130154d as a workaround.

**Comment by jeunito** [comment]
Thanks. It works again.
