### ISSUE TITLE
`passenger` formula info incorrect

### ISSUE THREAD

**Issue by mravery** [Homebrew/homebrew#47545]
Using `brew --version 0.9.5 (git revision 8658e; last commit 2015-10-14)`.

Installing `passenger` generates this information (this can also be accessed via `brew info passenger`) :

> To activate Phusion Passenger for Apache, create /etc/apache2/other/passenger.conf:
>  LoadModule passenger_module /usr/local/opt/passenger/libexec/buildout/apache2/mod_passenger.so
>  PassengerRoot /usr/local/opt/passenger/libexec/lib/phusion_passenger/locations.ini
>  PassengerDefaultRuby /usr/bin/ruby

The line `PassengerRoot /usr/local/opt/passenger/libexec/lib/phusion_passenger/locations.ini` is wrong. It should be: `PassengerRoot /usr/local/Cellar/passenger/5.0.20/libexec/src/ruby_supportlib/phusion_passenger/locations.ini`. This can be 'easily' (it wasn't easy for me) ascertained by running `passenger-config about root` after installation.

**Comment by mistydemeo** [comment]
Try running `brew update`; the instructions were fixed after your Homebrew was last updated.
