### ISSUE TITLE
Add pixiewps to homebrew tap

### ISSUE THREAD

**Issue by cusspvz** [Homebrew/homebrew#47542]
https://github.com/wiire/pixiewps

**Comment by dunn** [comment]
Feel like writing a formula?  Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions!

**Comment by DomT4** [comment]
Happy to review a PR here. Please feel free to shout if you need any help, Thanks!

**Comment by MosheBerman** [comment]
How does one write a formula for homebrew? The wiki is long, but I'm thinking about contributing to this.

**Comment by dunn** [comment]
I'd take a look at formula that have similar build processes, and use https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md as a reference.  And feel free to ask questions, here or on #machomebrew on IRC!

**Comment by MosheBerman** [comment]
Will do! PixieWPS seems to build out of the box on OS X but it's dependencies seem to be incompatible with whatever compilers Apple ships with OS X and with Xcode. I haven't gotten very far yet, but I'm looking into what could be wrong.

**Comment by cusspvz** [comment]
I've already compiled it once (I saw there wasn't a formula, so I've built it manually).
What problems are you facing currently @MosheBerman?

**Comment by cusspvz** [comment]
PS: We could have two formula for pixiewps, the `wiire` repo is the original one, but Kali ships the `t6x` [version](https://github.com/t6x/reaver-wps-fork-t6x) instead because it has bindings with `reaver` (It attacks faster using reaver's methods).

**Comment by MosheBerman** [comment]
@cusspvz: I'm struggling to get the tx version of Reaver up and running on OS X 10.11.
