### ISSUE TITLE
Feature request: using `tar xvf` in `brew install --verbose XYZ`

### ISSUE THREAD

**Issue by yan12125** [Homebrew/homebrew#47555]
As title, seems currently ```tar xf``` is hardcoded. Giving more details when extracting files would be nice. For large packages (for example boost), I'd like to see which file it is processing, or my terminal looks hang for quite a few seconds.

**Comment by mikemcquaid** [comment]
@yan12125 Sounds reasonable. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by yan12125** [comment]
I'll try it, but first I need to learn Ruby :)

**Comment by mikemcquaid** [comment]
@yan12125 Thanks :grinning: and we'll help you!

**Comment by chdiza** [comment]
Probably this should be only displayed if `$HOMEBREW_VERBOSE` is set, right?

**Comment by mikemcquaid** [comment]
> Probably this should be only displayed if $HOMEBREW_VERBOSE is set, right?

Yup :+1:

**Comment by zmwangx** [comment]
I like this feature, so I implemented this in #47649.

**Comment by yan12125** [comment]
Great job :+1: @zmwangx's patch works for me. I'm kind of curious:
