### ISSUE TITLE
ansible-cmdb: specifying a hosts file results in "ImportError: No module named yaml3"

### ISSUE THREAD

**Issue by alexbarton** [Homebrew/homebrew#47557]
Specifying a "hosts file" with the -i option results in the following error:
```
$ ansible-cmdb -i hosts reports/ >report.html
Traceback (most recent call last):
  File "/usr/local/bin/ansible-cmdb", line 623, in <module>
    ansible = Ansible(args, options.inventory, options.fact_cache, debug=options.debug)
  File "/usr/local/bin/ansible-cmdb", line 441, in __init__
    self._handle_inventory(self.inventory_path)
  File "/usr/local/bin/ansible-cmdb", line 470, in _handle_inventory
    self._parse_hostvar_dir(inventory_path)
  File "/usr/local/bin/ansible-cmdb", line 506, in _parse_hostvar_dir
    import yaml3 as yaml
ImportError: No module named yaml3
```

Is this module missing from the formula?
How can I help to debug this?

`brew config` and `brew doctor` reports: https://gist.github.com/2f3821286714a7cd096c

**Comment by dunn** [comment]
Yeah, that's probably the issue.  If you want to open a PR to fix it that'd be awesome!  Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions.
