### ISSUE TITLE
squid 3.5.12 no etc dir?

### ISSUE THREAD

**Issue by nrGitHub** [Homebrew/homebrew#47559]
Just upgraded squid from 3.5.7 to 3.5.12 but don't see an etc directory with the configuration files. Has this been moved?

ymir:~ $ ls -hal /usr/local/Cellar/squid/3.5.12
total 600
drwxr-xr-x  11   admin   374B Dec 31 12:13 .
drwxr-xr-x   4   admin   136B Dec 31 12:13 ..
-rw-r--r--   1   admin    18K Nov 28 16:13 COPYING
-rw-r--r--   1   admin   268K Nov 28 16:13 ChangeLog
-rw-r--r--   1   admin   249B Dec 31 12:13 INSTALL_RECEIPT.json
-rw-r--r--   1   admin   1.3K Nov 28 16:13 README
drwxr-xr-x   4   admin   136B Nov 28 16:13 bin
-rw-r--r--   1   admin   530B Dec 31 12:13 homebrew.mxcl.squid.plist
drwxr-xr-x  44   admin   1.5K Nov 28 16:13 libexec
drwxr-xr-x   3   admin   102B Nov 28 16:13 sbin
drwxr-xr-x   6   admin   204B Nov 28 16:13 share

Thanks

**Comment by DomT4** [comment]
A couple months back it was moved to `/usr/local/etc` (Providing your Homebrew lives in `/usr/local`) so the configuration didn't die every update/reinstall/uninstall/revision/etc. Should find the files there now.

**Comment by DomT4** [comment]
The above should resolve your question but feel free to shout if it doesn't, Thanks!
