### ISSUE TITLE
Use current version of devil.rb

### ISSUE THREAD

**Issue by ahundt** [Homebrew/homebrew#47551]
The new [DevIL github repository](https://github.com/DentonW/DevIL) is the most current place to get the code for DevIL, as specified on the [DevIL website](http://openil.sourceforge.net/).

It seems that there are better options for [devil.rb](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/devil.rb) available when compared to the one currently in use. The current version may not even be the latest one. It is borderline abandonware at the moment, but there are solid looking and recent active pull requests and a full fork [ResIL](http://sourceforge.net/projects/resil/). However, the fork hasn't been updated in about a year either.

I ask the original developer about the best version to use here:
https://github.com/DentonW/DevIL/issues/29

I'm interested in updating the script to use a version with fixes incorporated so gcc is no longer required. Is there any existing homebrew policy on handling abandonware and patches I may have missed?

If it is sensible and possible to fit in homebrew policies, we may want to consider using the version [patched for a modern CMake build/install](https://github.com/DentonW/DevIL/pull/21), as it will likely work with clang and many more compilers (seems to be tested for them), thus reducing dependencies and fitting better with the rest of the homebrew libraries. 

In fact, it appears DevIL cannot be compiled with either the current clang or gcc in homebrew!

I may be able to help with these changes.

**Comment by mikemcquaid** [comment]
> Is there any existing homebrew policy on handling abandonware and patches I may have missed?

If we can move to a mode widely used fork which doesn't require patching and the existing software is abandoned: that's ok :+1:

**Comment by DBankov** [comment]
Just created a pull request (https://github.com/Homebrew/homebrew/pull/50255) adding support for HEAD from GItHub. Unfortunately this still needs gcc 4.9 but at least the libpng missing symbols problem (https://github.com/DentonW/DevIL/commit/724194d7a9a91221a564579f64bdd6f0abd64219) is resolved with this.

**Comment by DomT4** [comment]
Closing here because there's not been much movement but we're happy to consider switching to a more modern, supported fork if one becomes available and the current upstream is dead. Please file a PR as desired/available.
