### ISSUE TITLE
netcdf.mod missing

### ISSUE THREAD

**Issue by ryofurue** [Homebrew/homebrew#47582]
netcdf.mod seems to be missing from the netcdf package.  (Is the whole Fortran interface missing? or is it just netcdf.mod ?  Under homebrew, I guess it makes sense to include interfaces for gfortran, both F77 and F90.)

Thank you

**Comment by dunn** [comment]
We'd love a pull request, if you're up for fixing this!  Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions.

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-science#3168
