### ISSUE TITLE
building ffmpeg with x265 10/12-bit libs and webp

### ISSUE THREAD

**Issue by gaming-hacker** [Homebrew/homebrew#47580]
i'm pretty sure webp is broken.
i've tried compiling ffmpeg with the bottle which has 10-bit libs and my own from source with has 8/10/12 bit libs.

both fail with bottle webp
undef: _x265_api_get_79
Undefined symbols for architecture x86_64:
  "_x265_api_get_79", referenced from:
      _libx265_encode_init_csp in libwebpenc_common.o
      _libx265_encode_init in libwebpenc_common.o

building webp from source give following error

Undefined symbols for architecture x86_64:
  "_glutLeaveMainLoop", referenced from:
      _HandleKey in vwebp-vwebp.o
  "_glutSetOption", referenced from:
      _main in vwebp-vwebp.o
ld: symbol(s) not found for architecture x86_64

there is something really screwy with where it looks for glut.h

i'm removing the webp lib from my ffmpeg build for now

**Comment by mikemcquaid** [comment]
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by gaming-hacker** [comment]
1. i always build ffmpeg from latest pull, i wanted to add libwebp library to ffmpeg.  so  brew install webp, no problems. x265 was installed through bottle.

2. configured ffmpeg --enable-libx265, --enable-libwebp;  failed, so problem is either with x265 or webp api interface. 
outside of homebrew, i installed x265 from source with all bits 8/10/12,  src/linux/multilb.sh, still crashed with error above.  
ffmpeg configure --disable-libwebp, installed and works without issue.

3. compile.
4.install x265, webp, ffmpeg --enable-libx265, --enable-libwebp

**Comment by mikemcquaid** [comment]
> i always build ffmpeg from latest pull

What does "latest pull" mean?

> outside of homebrew, i installed x265 from source with all bits 8/10/12, src/linux/multilb.sh, still crashed with error above.

What crashed? Where did you install it? Are you sure `ffmpeg` was picking up your `webp`?

> 3. compile.
> 4.install x265, webp, ffmpeg --enable-libx265, --enable-libwebp

What does this mean, sorry? Please be more verbose. Thanks!

**Comment by gaming-hacker** [comment]
"git pull", generally when i add a library to ffmpeg, in reinstall from source, ie,  i force everything to build from --HEAD

yes ffmpeg tried to pick it up, which is why it gives this result when x265 is linking to the webp lib
"_glutLeaveMainLoop", referenced from:
_HandleKey in vwebp-vwebp.o
"_glutSetOption", referenced from:
_main in vwebp-vwebp.o

i'll try to build it again this morning.

**Comment by gaming-hacker** [comment]
ok, i rebuilt with
brew reinstall ffmpeg --with-webp --with-x265 --with-faac --with-fdk-aac --with-dcadec --with-ffplay --with-fontconfig --with-freetype --with-frei0r --with-libass --with-libbluray --with-libbs2b --with-libcaca--with-libquvi--with-libsoxr --with-libssh--with-libvidstab --with-libvorbis --with-libvpx --with-opencore-amr --with-openjpeg --with-openssl --with-opus --with-rtmpdump --with-schroedinger --with-snappy --with-speex --with-theora --with-tools --with-webp --with-x265 --with-zeromq --with-lame --with-x264 --with-xvid --HEAD

ffmpeg -version
ffmpeg version git-2016-01-03-97c162a Copyright (c) 2000-2016 the FFmpeg developers
built with Apple LLVM version 7.0.2 (clang-700.1.81)
configuration: --prefix=/Users/me/abrew/Cellar/ffmpeg/HEAD --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-libsnappy --enable-libfontconfig --enable-libfreetype --enable-libtheora --enable-libvorbis --enable-libvpx --enable-librtmp --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libfaac --enable-libass --enable-ffplay --enable-libspeex --enable-libschroedinger --enable-libfdk-aac --enable-openssl --enable-libopus --enable-frei0r --enable-libx265 --enable-libwebp --enable-libzmq --enable-libbs2b --enable-libdcadec --enable-libopenjpeg --disable-decoder=jpeg2000 --extra-cflags=-I/Users/me/abrew/Cellar/openjpeg/1.5.2_1/include/openjpeg-1.5 --enable-nonfree --enable-vda

ok, so it built today but why is  this disabled?  --disable-decoder=jpeg2000

i'll chalk this up to latest HEAD and close it out.  thanks.

**Comment by gaming-hacker** [comment]
FYI, there are quite a few ffmpeg options +15  that brew doesn't include in building which i include in my own dev version, these brew options are really old
