### ISSUE TITLE
Another active Homebrew process is already using xz?

### ISSUE THREAD

**Issue by ylluminate** [Homebrew/homebrew#47593]
While attempting to install `cake` via `brew install cake` I received the following error:
```
Error: Operation already in progress for xz
Another active Homebrew process is already using xz.
Please wait for it to finish or terminate it to continue.
```

Unfortuantely there are no `xz` processes executing whatsoever.  I'm guessing there's some kind of a pid or lock file floating around, but I'm not finding it anywhere.  Any ideas?

**Comment by UniqMartin** [comment]
The error message complains about another running `brew` process, but if you are sure this is not the case, then it's probably some leftover lock files from a previous (crashed?) run. You can remove them with `brew cleanup` (check the output of `brew cleanup -n` to make sure it won't delete anything you care about, as `brew cleanup` does a lot more than removing those lock files). It should work afterwards.

**Comment by ylluminate** [comment]
Interesting.  Must have been a lock file floating around.  Thanks for the heads up on `cleanup` resolving that.
