### ISSUE TITLE
Where is Homebrew's repos dir? (brew update: "insufficient permission for adding an object to repository database")

### ISSUE THREAD

**Issue by SuperHenkie** [Homebrew/homebrew#47591]
Since a week or so, `brew update` gives me this:

> error: insufficient permission for adding an object to repository database .git/objects

Googling around gave me [this explanation](http://stackoverflow.com/questions/6448242/git-push-error-insufficient-permission-for-adding-an-object-to-repository-datab#6448326) which involves some `chgrp` and `chmod` trickery in the git repository dir.

**Question: exactly what or where is the git repository dir for my local homebrew installation?**

I never do anything Brew-related with git myself (I guess the installer script for Homebrew must have set that all up). I only use git in other contexts, and I'm fairly unexperienced with it. So I have no clue where (i.e. in what directory) to apply the solution from the link above, or what it even means.

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by SuperHenkie** [comment]
Thanks, wasn't aware of that procedure. After the `sudo chown` command, I still experienced some issues (`brew doctor` reported something about duplicate cask commands, or being unable to update from caskroom tap or something). But after another sequence of update, upgrade, doctor, etc, eventually everything is now fine!
