### ISSUE TITLE
brew install ejabberd --HEAD fails

### ISSUE THREAD

**Issue by gentlecat** [Homebrew/homebrew#47604]
Utils::InreplaceError: inreplace failed
    rebar.config.script:
      expected replacement of /https:\/\/github.com\/processone\/cache_tab\.?g?i?t?/ with #<Pathname:/Library/Caches/Homebrew/ejabberd--cache_tab--git>

*Full log: https://gist.github.com/anonymous/fa9f3fe033ec545449ae*

**Comment by bfontaine** [comment]
Thank you for the report @gentlecat! This should be fixed now; please run `brew update` and try again.

**Comment by gentlecat** [comment]
Thanks, works now.
