### ISSUE TITLE
exclude list of directories like /usr/local $HOME/build::  homebrew build ENV

### ISSUE THREAD

**Issue by gaming-hacker** [Homebrew/homebrew#47623]
i have homebrew installed in a non-default location,  ${HOME}/brewmeister  because other apps like perl, like to dump Tk/Tcl there.

i'd like to permanently exclude directories in the homebrew build ENV, ie, sandbox it to only it's own libraries or system SDKs.

can this be done? already done?  i didn't see any env variables in the docs.

**Comment by mikemcquaid** [comment]
We do this already as much as we can do, really. Beyond doing what we're doing requires buildsystems/CMake to behave nicely which they don't always. Sorry!
