### ISSUE TITLE
Unable to install imagemagick. Receiving a 404 error

### ISSUE THREAD

**Issue by SPARKLING165** [Homebrew/homebrew#47624]
I am running Ubutnu 14.04. I have successfully installed home/linux brew as well as ran brew doctor.
When I run brew install imagemagick this is what I get.

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading http://ftp.nluug.nl/ImageMagick/ImageMagick-6.9.2-6.tar

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "imagemagick"
Download failed: http://ftp.nluug.nl/ImageMagick/ImageMagick-6.9.2-6.tar.xz

I have googled around and the problem has been fixed for most by doing a simple brew update. Can anyone help?

**Comment by mikemcquaid** [comment]
Please report Linuxbrew issues to Linuxbrew.
