### ISSUE TITLE
Feature request: a way for `brew list` to show how things were `brew installed`

### ISSUE THREAD

**Issue by azdavis** [Homebrew/homebrew#47654]
If, for example, one were to `brew install grep --with-default-names` and then `brew list`, it would simply be reported as `grep`. It would be nice if `brew list` could keep a record of how kegs were installed and be able to express that, perhaps with an argument like `brew list --as-installed`.

**Comment by DomT4** [comment]
It sounds like you might find https://github.com/Homebrew/homebrew-bundle interesting, if you're attempting to retain options across installs/etc.

**Comment by azdavis** [comment]
That does look useful, thanks. It would be nice, though, if one could `brew list > Brewfile`, then subsuquently `brew install $(cat Brewfile)`.

I'll go ahead and close this, but if I ever get around to learning Ruby well enough to contribute, I'll think about submitting a PR. Thanks!

**Comment by DomT4** [comment]
No worries. Certainly feel free to file a PR if you ever wish to, we'd more than welcome that!

**Comment by mikemcquaid** [comment]
> That does look useful, thanks. It would be nice, though, if one could brew list > Brewfile, then subsuquently brew install $(cat Brewfile).

You can `brew bundle dump` and `brew bundle` which does the same thing.

**Comment by azdavis** [comment]
Thanks @mikemcquaid, that's exactly what I'm looking for. I guess I didn't read @DomT4's link closely enough to understand.
