### ISSUE TITLE
building static lib with gcc5.3 error

### ISSUE THREAD

**Issue by gaming-hacker** [Homebrew/homebrew#47657]
building a fortran library and during

gcc/5.3.0/bin/gcc-ranlib-5: Cannot find plugin 'liblto_plugin.so'

all of the source compile to objects
$(STATICLIB): objects
	$(AR) $(ARFLAGS) $@ $(OBJECTS_F) 
	$(RANLIB) $@

if i use the **OSX** *ar* and *ranlib*

$(STATICLIB): objects
	ar $(ARFLAGS) $@ $(OBJECTS_F)
	ranlib $@

lib builds without issue.  i searched the entire gcc5.3 branch and the plugin is not where it should be
Cellar/gcc/5.3.0/lib/gcc/5

gcc/                      |           libgcc_s_x86_64.1.dylib@      |       libobjc-gnu.dylib@
libasan.2.dylib         |             libgfortran.3.dylib         |         libquadmath.0.dylib
libasan.dylib@        |               libgfortran.a              |          libquadmath.a
libasan_preinit.o     |               libgfortran.dylib@      |             libquadmath.dylib@
libatomic.1.dylib       |             libgfortran.spec           |          libsanitizer.spec
libatomic.a                 |         libgomp-plugin-host_nonshm.1.dylib |  libssp.0.dylib
libatomic.dylib@       |              libgomp-plugin-host_nonshm.dylib@ |   libssp.a
libcc1.0.so                 |         libgomp.1.dylib          |            libssp.dylib@
libcc1.so@                 |          libgomp.a                  |          libssp_nonshared.a
libcilkrts.5.dylib           |        libgomp.dylib@           |            libstdc++.6.dylib
libcilkrts.a                    |     libgomp.spec                  |       libstdc++.a
libcilkrts.dylib@            |        libitm.1.dylib                |       libstdc++.a-gdb.py
libcilkrts.spec                |      libitm.a                           |  libstdc++.dylib@
libgcc_ext.10.4.dylib      |          libitm.dylib@              |          libstdc++fs.a
libgcc_ext.10.5.dylib       |         libitm.spec                  |        libsupc++.a
libgcc_s.1.dylib                |     libobjc-gnu.4.dylib          |        libubsan.0.dylib
libgcc_s_ppc64.1.dylib@ |             libobjc-gnu.a           |             libubsan.dylib@

**Comment by mikemcquaid** [comment]
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

Please be more explicit in your bug reports and provide command output that you've run; it's not at all clear as-is. Thanks!

**Comment by gaming-hacker** [comment]
my initial response is already complete, what is ambiguous?

1. compiling fortran code library because i need high performance quad precision routines, compiled
2. your gcc build is missing a library
3. to have build all of the library plugins
4. compile any .f source files,  use gcc-ar-5, gcc-ranlib-5.  it will fail because lto plugin was not built

**Comment by mistydemeo** [comment]
Can you give us an exact list of steps to reproduce, please? I'm able to build Fortran libraries and programs using Homebrew's GCC.

The Homebrew GCC's `ar` and `ranlib` have been broken like this for a number of versions, so we probably should nto be installing them. Is there a reason you need these tools and not the system `ar` or `ranlib`?

**Comment by gaming-hacker** [comment]
i can buld the libs but not with gcc tools, using osx tools yes.

with this missing 'liblto_plugin.so you will never be able to do link time optimization which for generic routines means nothing and you can live without it, my routines are heavily optimized, number crunching beasts.

no reason to use gcc tools, i just expected since i did a full gcc build that all of the tools would be there, i have many gcc only makefiles because they are portable across platforms that i just point to a lib src and build.  i'm not fan of a lots of #IFDEF statements/macros floating around.

**Comment by UniqMartin** [comment]
Can you provide a minimal example (`Makefile` and some simple source file, preferably as a Gist) that shows the issue? This will make it much easier for us to understand the problem and to debug it. Thanks!

**Comment by gaming-hacker** [comment]
ok give a little time, i'm some issues with gcc 6 at the moment.  but the lto plugin is notorious for being difficult to build and get right.
