### ISSUE TITLE
brew update -v can print mangled command, which manually produces "'update' is not a git command"

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew#47664]
In brew update -v output ...
```
git -c user.email=brew-update@localhost -c user.name=brew update stash save --include-untracked
Saved working directory and index state WIP on master: d8b5b57 xu-cheng
HEAD is now at d8b5b57 xu-cheng
```

but run manually ...

```
Josephs-MacBook-Pro:zfs joe$ git -c user.email=brew-update@localhost -c user.name=brew update stash save --include-untracked
git: 'update' is not a git command. See 'git --help'.

Did you mean this?
	update-ref
```

**Comment by mikemcquaid** [comment]
That's probably because we're handling quoting and you're not. Is there a bug actually running `brew update`)?

**Comment by ilovezfs** [comment]
Nope, brew update itself is fine. It's the pretty printed verbose output that shows the command in a mangled form.

**Comment by UniqMartin** [comment]
Yes, `user.name=brew update` is supposed to be a single argument, but we don't go to the trouble of properly shell quoting the arguments just for the sake of our verbose output.

You can have a look at [`Utils.system`](https://github.com/Homebrew/homebrew/blob/d947a9dea238df4fdf460ba28e856725342090e4/Library/Homebrew/utils.rb#L193-L196) if you'd like to change that. We welcome a PR that improves this.
