### ISSUE TITLE
giter8 installation cannot download dependency

### ISSUE THREAD

**Issue by manuel-zulian** [Homebrew/homebrew#47674]
Using the command "brew install giter8" the installation is successful, however at the moment of starting it for the first time with "g8" the download of the dependencies fails with this message

    unresolved dependency: net.databinder.giter8#giter8_2.10;0.6.9: not found

Manual installation via conscript works fine. However, manual installation installs version 0.6.8, while brew installs version 0.6.9.

**Comment by DomT4** [comment]
Should be fixed with https://github.com/Homebrew/homebrew/commit/4662b5d98903a7a0709c4c4bd81dfd392e2f108c but feel free to shout if it isn't. Thanks for the report!
