### ISSUE TITLE
qgis failed to build on OS 10.10.5

### ISSUE THREAD

**Issue by ceedave** [Homebrew/homebrew#47682]
Hello,

The log reported qgis_gui build than crashed with an (uninformative) error message.

Brew doctor reported all okay except possible problems with case-sensitive OS.

Brew was updated, upgraded and pruned before the attempted build.

Many, many other brew formulae work beautifully (thanks!).

Gist log at:
https://gist.github.com/ceedave/2b9e8ea71bac458d5dc1

Thanks,
Chris

**Comment by batic** [comment]
I confirm - I get the same error.

**Comment by mikemcquaid** [comment]
@batic Can you also paste your Gist log?

**Comment by batic** [comment]
https://gist.github.com/batic/17ae745923f9369722f4

Basically it is the same as yours.

**Comment by mikemcquaid** [comment]
@batic I'd like to see your `doctor` output too?

**Comment by krishagel** [comment]
I am seeing the same problem.  Here is my log:

https://gist.github.com/krishagel/c52b87ab9107f66837d6

And here is the output from brew doctor

https://gist.github.com/krishagel/a152413d37cf7d111568

**Comment by jarandaf** [comment]
Same error

**Comment by henrywuxad** [comment]
same error here

**Comment by eric-p** [comment]
Hi,
Same error for me. gist log : https://gist.github.com/53559863fe7f30c8e245
Nothing on brew doctor.

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-science#3442

**Comment by DomT4** [comment]
Sorry, I just realised this Issue was filed in the wrong tap. The formula lives in Science so the Issue needed to be filed there. Have moved it over, hopefully the Science maintainers can help you further.
