### ISSUE TITLE
get the size of shell window when running command, respect term size

### ISSUE THREAD

**Issue by gaming-hacker** [Homebrew/homebrew#47685]
i need to see what the hell is actually going on with configure, especially when the command lines are insanely long.  grab the env of the shell and parse the line to something that can be see

instead of  this 
==> ./configure --prefix=/Users/me/abrew/Cellar/flac/1.3.1 --mandir=/Users/me/abrew/Cellar/flac/1.3.1/share/man --enable-sse --enab

**Comment by mistydemeo** [comment]
You can see the detailed logs in the logs directory, e.g. `~/Library/Logs/Homebrew/flac`.

**Comment by bfontaine** [comment]
Use `--verbose` to see the complete commands.

**Comment by gaming-hacker** [comment]
cool i'll try that.
