### ISSUE TITLE
building flac with --HEAD bombs

### ISSUE THREAD

**Issue by gaming-hacker** [Homebrew/homebrew#47686]
when building from HEAD  you need to comment or ignore these lines

adds universal flags to the generated libtool script
inreplace "libtool" do |s|
 s.gsub! ":$verstring\"", ":$verstring -arch #{Hardware::CPU.arch_32_bit} -arch #{Hardware::CPU.arch_64_bit}\""
end

also where are not other options available?  
--enable-local-xmms-plugin --enable-doxygen-docs .... rpath?

for 64 bit builds you need to pass macho64 to build asm files

building from latest head all you need to do 
1autogen.sh  or strip_non_asm_libtool_args.sh if pic is an issue
2 configure ${options}
3. make = -j8; make install;make clean;make distclean

**Comment by DomT4** [comment]
>  you need to comment or ignore these lines

If they don't apply on `head` we'd welcome a PR to wrap that element in a `if build.stable?` block. It'd be useful to know why that block isn't necessary/desired though (?).

> also where are not other options available?

We don't supply every option under the sun for every formula for many reasons. Some don't work, some are never used and thus aren't worth the maintenance burden, some behave in unexpected ways, etc. If an option is valuable and would be widely used, we'd be happy to consider a PR adding it.

**Comment by gaming-hacker** [comment]
i didin't go into the src to heavily but since i've been building flac from my own personal repo for a while and i've never had to use those switches i only build 64bit so i knew to comment them out.  most would probably assume that since flac has not rolled out a new version, still at 1.31 that there are no updates but there are quite often. 

this lib, x264,x265 and most of the a/v libs, i build with ffmpeg daily and that rpath can be especially problematic since a lot of other binaries look at these, some choke on rpath others don't.
