### ISSUE TITLE
Brew update gives error

### ISSUE THREAD

**Issue by dipu** [Homebrew/homebrew#47687]
I am having issues with brew update. I have put `brew update`,`brew config` & `brew doctor` output into this gist. https://gist.github.com/dipu/1d1977962fb4f2a4d640

**Comment by UniqMartin** [comment]
Can you try if running `brew update` a second time resolves the issue for you. If not, can you please post the output of `brew update --verbose`?

**Comment by DomT4** [comment]
In this case the problem seems to be that you have a bunch of unexpected modifications to the `homebrew-versions` tap locally. If you didn't intend those modifications you may wish to do:

```bash
cd $(brew --prefix)/Library/Taps/homebrew/homebrew-versions && git fetch && git reset --hard origin/master
```

See if the error persists after that. Please do note if you've intended non-upstream changes to your local `homebrew-versions` clone that command will wipe them.

**Comment by dipu** [comment]
@UniqMartin Thanks for your reply. I have already tried brew update many times but did not help.

@DomT4 Thanks a lot. I did "cd $(brew --prefix)/Library/Taps/homebrew/homebrew-versions && git fetch && git reset --hard origin/master" and it seems to have solved my problem. Output below:

cd $(brew --prefix)/Library/Taps/homebrew/homebrew-versions && git fetch && git reset --hard origin/master
remote: Counting objects: 219, done.
remote: Compressing objects: 100% (3/3), done.
Receiving objects: 100% (219/219), 39.96 KiB | 0 bytes/s, done.
remote: Total 219 (delta 137), reused 137 (delta 137), pack-reused 79
Resolving deltas: 100% (139/139), completed with 66 local objects.
From https://github.com/Homebrew/homebrew-versions
   b5442b0..ede21b1  master     -> origin/master
HEAD is now at ede21b1 LICENSE added

brew update:

Updated 2 taps (caskroom/cask, homebrew/php).
==> Updated Formulae
homebrew/php/adminer

brew update --verbose:

==> git symbolic-ref --short HEAD 2>/dev/null
master
==> git status --untracked-files=all --porcelain 2>/dev/null

==> git rev-parse -q --verify HEAD
6f7f407410cd6028295b936bb3b847d7ce567cdc
git config core.autocrlf false
git pull --ff --no-rebase origin refs/heads/master:refs/remotes/origin/master
Already up-to-date.
==> git rev-parse -q --verify HEAD
6f7f407410cd6028295b936bb3b847d7ce567cdc
==> git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null
refs/remotes/origin/master
==> git symbolic-ref --short HEAD 2>/dev/null
master
==> git status --untracked-files=all --porcelain 2>/dev/null

==> git rev-parse -q --verify HEAD
205d9e19ac52d84b517d2f20b7557b5d40ec4c9e
git config core.autocrlf false
git pull --ff --no-rebase origin refs/heads/master:refs/remotes/origin/master
Already up-to-date.
==> git rev-parse -q --verify HEAD
205d9e19ac52d84b517d2f20b7557b5d40ec4c9e
==> git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null
refs/remotes/origin/master
==> git symbolic-ref --short HEAD 2>/dev/null
master
==> git status --untracked-files=all --porcelain 2>/dev/null

==> git rev-parse -q --verify HEAD
d8a5793bfadf2190443d5da3b2cef94c02475d28
git config core.autocrlf false
git pull --ff --no-rebase origin refs/heads/master:refs/remotes/origin/master
Already up-to-date.
==> git rev-parse -q --verify HEAD
d8a5793bfadf2190443d5da3b2cef94c02475d28
==> git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null
refs/remotes/origin/master
==> git symbolic-ref --short HEAD 2>/dev/null
master
==> git status --untracked-files=all --porcelain 2>/dev/null

==> git rev-parse -q --verify HEAD
0cdfdd462e46d7111876a24767e7e06ba0fc3d1a
git config core.autocrlf false
git pull --ff --no-rebase origin refs/heads/master:refs/remotes/origin/master
Already up-to-date.
==> git rev-parse -q --verify HEAD
0cdfdd462e46d7111876a24767e7e06ba0fc3d1a
==> git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null
refs/remotes/origin/master
==> git symbolic-ref --short HEAD 2>/dev/null
master
==> git status --untracked-files=all --porcelain 2>/dev/null

==> git rev-parse -q --verify HEAD
ede21b1323654df4b50f645b81f1832386922033
git config core.autocrlf false
git pull --ff --no-rebase origin refs/heads/master:refs/remotes/origin/master
Already up-to-date.
==> git rev-parse -q --verify HEAD
ede21b1323654df4b50f645b81f1832386922033
Already up-to-date.

**Comment by mikemcquaid** [comment]
@dipu Closing this now if it's working, thanks!
