### ISSUE TITLE
brew upgrade ruby leaves cruft?

### ISSUE THREAD

**Issue by mattdipasquale** [Homebrew/homebrew#47695]
I did `brew upgrade ruby` to upgrade from Ruby 2.2.3 to Ruby 2.3.0.

But, I still see files & directories that seem to be cruft left over from Ruby 2.2.3.

Can I safely `rm -rf /usr/local/lib/ruby/*/2.2.0`?

If so, perhaps `brew upgrade` should do this for me automatically or at least include a caveat.

**Comment by bfontaine** [comment]
`brew cleanup` will do that for you.

**Comment by mikemcquaid** [comment]
Also, we don't remove files we didn't install e.g. RubyGems.

**Comment by mattdipasquale** [comment]
@bfontaine thank you for replying and suggesting `brew cleanup`.

It removed:

* `/usr/local/Cellar/ruby/2.2.3`
* `/Library/Caches/Homebrew/ruby-2.2.3.el_capitan.bottle.tar.gz

but not:

* `/usr/local/lib/ruby/gems/2.2.0`
* `/usr/local/lib/ruby/site_ruby/2.2.0`
* `/usr/local/lib/ruby/vendor_ruby/2.2.0`

I even ran `brew cleanup --force -s` to no avail.

I noticed in `man brew` that I could've also done `brew upgrade --cleanup ruby`.

**Comment by mattdipasquale** [comment]
@mikemcquaid thank you for answering my question.

Perhaps Homebrew should allow a way to remove files installed by its packages. For example, the ruby formula could provide a function that removes all installed gems, and users could run such functions by adding options to the `cleanup` &  `upgrade` commands.

Since this option doesn't exist now, how can I do this manually? Would executing `rm -rf /usr/local/lib/ruby/*/2.2.0` remove all (and only) files unused by Ruby 2.3.0?

**Comment by bfontaine** [comment]
@mattdipasquale Yeah I read too fast, Mike had the correct answer.

**Comment by mikemcquaid** [comment]
> Since this option doesn't exist now, how can I do this manually? Would executing rm -rf /usr/local/lib/ruby/*/2.2.0 remove all (and only) files unused by Ruby 2.3.0?

Should do, yep.

> Perhaps Homebrew should allow a way to remove files installed by its packages. For example, the ruby formula could provide a function that removes all installed gems, and users could run such functions by adding options to the cleanup & upgrade commands.

`uninstall` hooks are something we've considered and passed on in the passed but thanks for the suggestion.
