### ISSUE TITLE
New warnings when upgrading

### ISSUE THREAD

**Issue by telemachus** [Homebrew/homebrew#47710]
As of this morning, when I run `brew update`, I'm told:

```
To restore the stashed changes to /usr/local run:
  `cd /usr/local && git stash pop`
```

The problem seems to be a set of man files for items that Homebrew itself installed. If I follow the recommended command, git says that I'm up to date but that there are (now?) untracked files.

Is this related to changes in what git commands are run when the user calls `brew update`? Any suggestions for how to quiet things down? Thanks.

**Comment by mikemcquaid** [comment]
> The problem seems to be a set of man files for items that Homebrew itself installed.

Can you let me know which these are so I can figure this out? Thanks!

**Comment by telemachus** [comment]
@mikemcquaid Sure. Here's a gist: https://gist.github.com/telemachus/3ecc1ac3a9b16787e1c6

**Comment by bfontaine** [comment]
I got a similar list of files today as well. I `git-clean`ed them (I probably removed a bunch of manpages but that’s not a big issue for me); but when I run `brew update` `share/man/man1/brew-cask.1` keeps getting created:
```shellSession
$ rm share/man/man1/brew-cask.1
$ brew update
Already up-to-date.
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	share/man/man1/brew-cask.1

nothing added to commit but untracked files present (use "git add" to track)
```

We didn’t modify `.gitignore` recently so I’m not sure what to check.

**Comment by mikemcquaid** [comment]
@bfontaine @telemachus What is your `git` version, out of interest? What if you rerun with `/usr/bin/git`?

**Comment by gothicpurple** [comment]
@mikemcquaid I've been experiencing the same problem just after the git update through Homebrew. My version now is 2.7.0

**Comment by telemachus** [comment]
@mikemcquaid I just updated git yesterday. Current version: `git version 2.7.0`. Using `/usr/bin/git` gives essentially the same output (though slightly different look to the warnings): https://gist.github.com/telemachus/b84839f658b162a6f549

**Comment by mikemcquaid** [comment]
@telemachus I'm wondering if `git status` produces the same result on the latest Git. I suspect Git 2.7.0 parses our `gitignore` differently.

**Comment by gothicpurple** [comment]
This is the output I'm getting if running `git status`:

`On branch master`
`Untracked files:`
  `(use "git add <file>..." to include in what will be committed)`

	`share/man/man1/brew-cask.1`

`nothing added to commit but untracked files present (use "git add" to track)`

**Comment by mikemcquaid** [comment]
@gothicpurple Can you compare the `/usr/bin/git status` and `git status` output? Thanks!

**Comment by telemachus** [comment]
@mikemcquaid Good call: https://gist.github.com/telemachus/164db393c0ebca60b95a

**Comment by xu-cheng** [comment]
If it could be any help, [this](https://github.com/git/git/blob/master/Documentation/RelNotes/2.7.0.txt#L48-L50) could be the source. Also [this blog](https://developer.atlassian.com/blog/2016/01/git-2.7-release/) highlights some major change in Git 2.7.

**Comment by gothicpurple** [comment]
@mikemcquaid :
When running `/usr/bin/git status`:
`On branch master`
`nothing to commit, working directory clean`

When running simply `git status`:
`On branch master`
`Untracked files:`
`(use "git add <file>..." to include in what will be committed)`
`share/man/man1/brew-cask.1`
`nothing added to commit but untracked files present (use "git add" to track)`

**Comment by mikemcquaid** [comment]
@xu-cheng Yeh, it appears this is really badly broken; `!/bin/brew` now unignores everything in `bin/`

**Comment by mikemcquaid** [comment]
Reported this regression to Git: http://www.mail-archive.com/git@vger.kernel.org/msg83203.html

**Comment by bfontaine** [comment]
Thanks Mike!
