### ISSUE TITLE
Aircrack-ng 1.2 still not available on Homebrew

### ISSUE THREAD

**Issue by gothicpurple** [Homebrew/homebrew#47716]
Hello there, Aircrack-ng 1.2 is out 
http://www.aircrack-ng.org/downloads.html
and I reckon it's the final release (not a beta).
As my knowledge, the beta had several compatibility issues on Mac OS X but now (reading around the website) there are no such things as conflicts between Aircrack-ng 1.2 and OS X.

**Comment by gothicpurple** [comment]
From the website.
Important information:
This version requires you to develop your own DLLs to link aircrack-ng to your wireless card (it will not work without).
The required DLLs are not provided in the download and there will be no support for them.

That's maybe why. Forget I said anything.

**Comment by bfontaine** [comment]
If you think it should be updated you could make a pull-request to Homebrew. This should help and I’im happy to answer any question you might have: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md
Thanks!
