### ISSUE TITLE
Add pkcs11 support in openvpn formula

### ISSUE THREAD

**Issue by xpayn** [Homebrew/homebrew#47722]
pkcs11 support is needed when you want to use a crypto hardware like a smartcard with openvpn client
There's currently no option in the formula to enable it.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
