### ISSUE TITLE
i2p needs an update

### ISSUE THREAD

**Issue by magicgoose** [Homebrew/homebrew#47729]
`Library/Formula/i2p.rb`
Formula's version is 2 releases behind the last release: https://geti2p.net/en/blog/post/2015/11/19/0.9.23-Release

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by DomT4** [comment]
See https://github.com/Homebrew/homebrew/pull/46623.

Feel free to open your own PR, but there's an issue there with the test killing the CI connection temporarily that means the test needs some rewriting.

**Comment by magicgoose** [comment]
hmmm, I don't know why I did not found that pull request. I'm sorry for that.
