### ISSUE TITLE
perforce binary SHA256 mismatch

### ISSUE THREAD

**Issue by praphull27** [Homebrew/homebrew#47734]
What I tried:
brew tap homebrew/binary
brew install perforce

What I got:
==> Installing perforce from homebrew/binary
==> Downloading https://www.perforce.com/downloads/perforce/r15.2/bin.macosx105x86_64/p4
Already downloaded: /Library/Caches/Homebrew/perforce-2015.2.1311674
Error: SHA256 mismatch
Expected: 361b336973f00ca9bab41a50d4f36bc1807db33d93fdda1649afa5f7130c1e36
Actual: d22fb8d4863e4c8e75e462175b53c72dbb7d102a6edd42e2e081a5a4fbede4b5
Archive: /Library/Caches/Homebrew/perforce-2015.2.1311674
To retry an incomplete download, remove the file above.

**Comment by apjanke** [comment]
Looks like they've made another release, and the version number and SHAs in the formula need to be bumped.

```
$ wget https://www.perforce.com/downloads/perforce/r15.2/bin.macosx105x86_64/p4 &>/dev/null
$ chmod a+x p4
$ ./p4 -V | grep Rev
Rev. P4/MACOSX105X86_64/2015.2/1319959 (2015/12/28).
```

**Comment by apjanke** [comment]
There's already a PR for it over in homebrew-binary: https://github.com/Homebrew/homebrew-binary/pull/285

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew-binary/commit/e0ce8dc363942179345b192b1603310de42ee7f4.
