### ISSUE TITLE
Homebrew install without changing permissions on folders

### ISSUE THREAD

**Issue by Edwardzyc** [Homebrew/homebrew#47731]
Is this possible?

**Comment by dunn** [comment]
You could install Homebrew to a non-standard location that you already own, like `~/.homebrew`.  Sometimes Homebrew breaks when installed outside of `/usr/local`, though, and we don't officially support it: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Installation.md#alternative-installs
