### ISSUE TITLE
brew outdated --json=v1 doesn't respect --quiet

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew#47747]
I don't know if this is intended behavior:

```
bash-3.2$ brew outdated --quiet
git
mercurial
qemu
bash-3.2$ brew outdated --quiet --json=v1
[{"name":"git","current_version":"2.7.0","installed_versions":["2.6.3","2.6.4"]},{"name":"mercurial","current_version":"3.6.3","installed_versions":["3.5.2","3.6.1","3.6.2"]},{"name":"qemu","current_version":"2.5.0","installed_versions":["2.4.0.1"]}]
```

while the man page says,
```
              If  --json=version  is  passed,  the output will be in JSON format. The only
              valid version is v1.
```
which would seem to imply that it takes whatever output you would otherwise get, and formats it as json, as opposed to being a mutually exclusive option.

**Comment by UniqMartin** [comment]
Can you be a bit more specific what the issue is in your opinion? What do you expect to get from `brew outdated --quiet --json=v1` and how does the output violate that expectation?

**Comment by ilovezfs** [comment]
```
              If --quiet is passed, list only the names of outdated  brews  (takes  prece-
              dence over --verbose).
```

So I'd think the json wouldn't include the versions.

**Comment by ilovezfs** [comment]
More abstractly, --quiet vs. --verbose (content) seems orthogonal to --json (formatting).

**Comment by UniqMartin** [comment]
The JSON output is for use by external tools. It wouldn't be helpful if it changed based on the `--quiet` flag and if an external tool really doesn't need the version information, it's better to keep the format the same and discard the superfluous information on the receiving end.

If I understand you correctly, this is an imprecision in our documentation and you want it to state explicitly that requesting JSON output ignores other flags?

**Comment by ilovezfs** [comment]
It could be addressed as either a documentation issue or a code issue, though I'd recommend treating it as a code issue. An analogy is diskutil list / diskutil list disk1; diskutil list -plist / diskutil list -plist disk1.

**Comment by ilovezfs** [comment]
Suppose you added "brew outdated --super-verbose." Which would the --json=v1 display? --verbose or --super-verbose?

**Comment by UniqMartin** [comment]
I have to disagree. `--json=v1` is supposed to always dump the full information (which it does) irrespective of other flags. It's up to the tool that uses this information to disregard some of it. The non-JSON output is mostly geared towards humans, so it makes sense to adapt it according to `--quiet` or `--verbose`.

I don't know what `--super-verbose` is supposed to be, but if it really adds additional information, that should also always be part of the JSON output. Any well-designed tool will just ignore the additional information, so that's not an issue either.

So far we're discussing a documentation issue (and I'm not entirely sure we need to be this explicit in our man page). I'm sure we won't change the current behavior unless there's a good reason to (and there's isn't in my opinion because of what I stated about the intended use of this JSON output).

**Comment by ilovezfs** [comment]
If you want to conflate content and formatting, that is certainly up to you, though it's contrary to how other tools behave such as Apple's -plist options and ZFS's -H options, so it's certainly not standard behavior.

In terms of whether you should be "this explicit," in the case of verbose vs quiet, you already are:

```
              If --quiet is passed, list only the names of outdated  brews  (takes  prece-
              dence over --verbose).
```

It was precisely because the same was NOT said about --json=v1 that I was surprised that it took precedence over the other two options as opposed to working in concert with them.

**Comment by UniqMartin** [comment]
> If you want to conflate content and formatting, that is up to you, though it's contrary to how other tools behave such as Apple's -plist options and ZFS's -H options, so it's certainly not standard behavior.

I can't comment on ZFS, but `diskutil` doesn't even have flags to adjust the verbosity (except for `quiet` that doesn't have an effect on the commands you mention), so this comparison is moot. The `-plist` output always contains all the detail. `diskutil list -plist disk1` only outputs information on `disk1` and `brew outdated --json=v1 git` equally only outputs whether the `git` formula is outdated or not.

> In terms of whether you should be "this explicit," […]

Have you read the man page? The command is introduced with `outdated [--quiet|--verbose|--json=v1]` so it's actually stated that these options are mutually exclusive. Our documentation is certainly not perfect, but this part seems fine to me.

**Comment by ilovezfs** [comment]
> Have you read the man page?

Yes, and you're correct.

http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html
> Arguments separated by the '|' ( <vertical-line>) bar notation are mutually-exclusive.

However, it also says,
> Only one of the mutually-exclusive arguments is allowed for invocation of the utility.

So you've already jumped the shark in terms of allowing both --quiet and --verbose with a specification of precedence.

**Comment by ilovezfs** [comment]
> The use of conflicting mutually-exclusive arguments produces undefined results, unless a utility description specifies otherwise.

All is well. Cool.

**Comment by ilovezfs** [comment]
Though actually, since it doesn't say what happens when --json=v1 is passed in combination with other two, one of which does describe conflicting behavior, the results are technically still undefined based on the man page as it currently stands, so it might be worth noting that --json=v1 takes precedence over all others.

**Comment by UniqMartin** [comment]
> All is well. Cool.

Thanks for understanding!

> Though actually, since it doesn't say what happens when --json=v1 is passed in combination with either or both of the other two, […], so it might be worth noting that --json=v1 takes precedence over all others.

We try to strike a balance between being brief and being accurate in our documentation. We generally appreciate PRs that improve our documentation, so feel free to submit something. (My gut feeling is that I wouldn't be the only one to reject a submission that details the precedence relation when it's already clear the options are not supposed to be combined in a single invocation, though.)

If you feel passionate about the man page (and it seems you are), then I'm sure there are more substantial quirks/errors in that document that are worth correcting.

**Comment by ilovezfs** [comment]
<blockquote>All is well. Cool.
<blockquote>Thanks for understanding!</blockquote>
</blockquote> 
No problem.

<blockquote>If you feel passionate about the man page (and it seems you are)</blockquote> 
I'm certain I often seem "passionate" or rude, when I'm just having fun arguing. In this case, it's a principle of least surprise issue. I expected --quiet --json to do one thing and it did something else. In retrospect, since they're explicitly mutually exclusive, I should have expected undefined behavior ;)

<blockquote>(My gut feeling, though, is that I wouldn't be the only one to reject a submission that details the precedence relation when it's already clear the options are not supposed to be combined in a single invocation.)</blockquote>
Yes, the case for noting the precedence between the direct antonyms "quiet" and "verbose" is stronger than the case for noting the relationship between "json" and the other two, but by noting it in one case, and not the other it caused me to draw a false inference based on a logical fallacy: the absence of evidence is not evidence of absence. I am duly chastised.
