### ISSUE TITLE
Qemu failed to build on 10.6.8

### ISSUE THREAD

**Issue by sentient06** [Homebrew/homebrew#47742]
Okay, first let me explain my environment, because it is a bit atypical:
I am running a Mac OS X 10.6.8 with XCode 3.2.1 *and* 4.2. My XCode 3 lives in `/XCode3` and my XCode 4 lives in `/Developer`.

Then I have gcc 4.8 installed from Homebrew. My fallback gcc is from XCode 3.

Now, I am trying to install Qemu. This is what I got:

https://gist.github.com/7760bfb21bbceaa1b291

And here are some stuff from my environment, that might be useful:

    gian@Turambar:~ $ brew doctor
    Your system is ready to brew.
    gian@Turambar:~ $ xcode-select -print-path
    /XCode3
    gian@Turambar:~ $ which gcc
    /usr/bin/gcc
    gian@Turambar:~ $ /usr/bin/gcc --version
    i686-apple-darwin10-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.1.00)
    Copyright (C) 2007 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    
    gian@Turambar:~ $ alias
    alias g++='g++-4.8'
    alias gcc='gcc-4.8'
    gian@Turambar:~ $ which gcc-4.8
    /usr/local/bin/gcc-4.8
    gian@Turambar:~ $ /usr/local/bin/gcc-4.8 --version
    gcc-4.8 (Homebrew gcc48 4.8.4) 4.8.4
    Copyright (C) 2013 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    
    gian@Turambar:~ $

I saw there was another thread here about compiling qemu on 10.6, but it was something related to cURL and mine works fine.

The issue I get is:

    ERROR: Your compiler does not support the __thread specifier for 
           Thread-Local Storage (TLS). Please upgrade to a version that does.

Is there a way to use gcc 4.8 here? It seems homebrew is using llvm-gcc from Apple.

Any help would be very appreciated!

Looking forward to hearing from you!

Thanks in advance! Cheers!

**Comment by UniqMartin** [comment]
You can try building with `brew install qemu --cc=gcc-4.8`, but if that fails there's probably not much we can help you with.

**Comment by DomT4** [comment]
If it works please let us know and we'll throw a `fails_with :gcc` into the formula.

**Comment by sentient06** [comment]
It worked! Wow, that was simple. Thanks!

**Comment by UniqMartin** [comment]
Thank you for the confirmation, @sentient06! Should be fixed after a `brew update`.
