### ISSUE TITLE
Source archive referenced by hexedit formula has disappeared.

### ISSUE THREAD

**Issue by xyziemba** [Homebrew/homebrew#47743]
Formula hexedit references homepage http://rigaux.org/hexedit.html and source archive http://rigaux.org/hexedit-1.2.13.src.tgz. Both of these have disappeared, so the program is not installable. I was unable to find a new location for the source code to submit an updated formula.

**Comment by DomT4** [comment]
Fixed by https://github.com/Homebrew/homebrew/commit/93428e5639a01592815fce4432ebe1c2c141af93. Added a Debian mirror for now.
