### ISSUE TITLE
Appstore dylibs path

### ISSUE THREAD

**Issue by roopa01** [Homebrew/homebrew#47748]
Hi,

 I am using some ffmpeg dylibs in my project for this i have successfully configured ffmpeg and created ffmpeg dylibs. when i rum macdeployqt command to make exe it creates Frameworks folder inside the app containing all  required dylibs and framworks . It works well in normal case exe runs successfully
it always pick dylibs from frameworks folder. But when i code signed this exe for appstore it does not pick dylibs from frameworks folder while dylibs are allowed on appstore.
    It search dylibs on /usr/local/lib . I have given path in .pro file LIBS += -L/usr/local/lib for dylibs
If i manually place all dylibs in usr/local/lib it works fine.
which path is required to fatch dylibs from frameworks folder 
If this path is LIBS += -L/usr/local/lib not correct how it works well in without code signed case.

   Kindly help me to find out the problem.

Regards,
roopa01

**Comment by mikemcquaid** [comment]
Sorry, this is an issue with using Qt and developing OS X software and not a Homebrew issue.
