### ISSUE TITLE
openvpn with pkcs11 support fails because of pkcs11-helper

### ISSUE THREAD

**Issue by xpayn** [Homebrew/homebrew#47754]
I managed to make it work thanks to this [post](http://www.sparklabs.com/forum/viewtopic.php?p=4806#p4823)
I think the solution is to add options in pkcs11-helper's formula and pass them in openvpn's dependency
I'll submit a PR later

**Comment by mikemcquaid** [comment]
> I'll submit a PR later

Thanks!

**Comment by nijikon** [comment]
:+1:

**Comment by DomT4** [comment]
Merged the PR.
