### ISSUE TITLE
Is not possible install MySQL on Mountain Lion through Homebrew

### ISSUE THREAD

**Issue by manueljordan** [Homebrew/homebrew#47776]
Hello

When I run `brew install mysql` (Mountain Lion - 10.8.5)

always remains in this way

```
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> Summary
🍺  /usr/local/Cellar/cmake/3.4.1: 1,980 files, 30.3M, built in 3 minutes 32 seconds
==> Installing mysql dependency: boost
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.59.0/boost_1_59_0.tar.bz2
==> Downloading from http://ufpr.dl.sourceforge.net/project/boost/boost/1.59.0/boost_1_59_0.tar.bz2
######################################################################## 100.0%
==> Downloading https://gist.githubusercontent.com/tdsmith/bc76ddea1e2bdb2a3a18/raw/03d125b12a4b03c28ee011a2d6d42a8137061a3b/boost-log.patch
######################################################################## 100.0%
==> Downloading https://gist.githubusercontent.com/autosquid/a4974e112b754e03aad7/raw/985358f8909033eb7ad9aae8fbf60881ef70a275/boost-log_setup.patch
######################################################################## 100.0%
==> Patching
patching file boost/log/sources/record_ostream.hpp
patching file boost/log/utility/formatting_ostream.hpp
patching file libs/log/test/common/make_record.hpp
patching file libs/log/test/run/src_record_ostream.cpp
patching file libs/log/test/run/util_formatting_ostream.cpp
patching file boost/log/detail/setup_config.hpp
patch unexpectedly ends in middle of line
Hunk #2 succeeded at 54 with fuzz 1.
==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost/1.59.0 --libdir=/usr/local/Cellar/boost/1.59.0/lib --without-icu --without-libraries=python,mpi
==> ./b2 headers
==> ./b2 --prefix=/usr/local/Cellar/boost/1.59.0 --libdir=/usr/local/Cellar/boost/1.59.0/lib -d2 -j4 --layout=tagged --user-config=user-config.jam install threading=multi,single lin
```

Practically with 
```
==> ./b2 --prefix=/usr/local/Cellar/boost/1.59.0 --libdir=/usr/local/Cellar/boost/1.59.0/lib -d2 -j4 --layout=tagged --user-config=user-config.jam install threading=multi,single lin
```

the console/terminal remains working for many minutes and the Mac fan is working a lot. 
I must abort the process with "Ctrl + C". 

The sound of the fan is strong and the time working is long (I never had this experience before through Homebrew)

Before I never had a problem about MySQL installation through Homebrew, always practical and easy and the normal process to install/make etc.

Thanks

**Comment by DomT4** [comment]
`boost` is a new (build) dependency for `mysql`, so the delay you're seeing isn't actually coming from `mysql`. I'm not quite sure why you're getting the from-source install here rather than a bottle, which negates the build dependency.

Can you do a `brew update` and then `brew fetch boost -v` and `brew info mysql` and paste the output of each? Thanks.

If building Boost from source is intentional, be aware it does take 30-45 minutes to build.

**Comment by mistydemeo** [comment]
We're no longer building binary packages for OS X 10.8; we only build binary packages for three OS X versions at a time. This means that, to install software on older versions, you have to build them from source.

The boost package is one of the dependencies required to build mysql, and it does take a very long time to build and a lot of CPU power. You can expect it to take 20-40 minutes; this is normal, and your Mac fan  going loudly is a sign it's still working!

**Comment by DomT4** [comment]
> We're no longer building binary packages for OS X 10.8

Apologies. I'm an idiot. I forgot this temporarily :sweat:. I've amended my original comment accordingly.

**Comment by manueljordan** [comment]
Thanks by the replies. Seems mandatory do an upgrade to the OS in general…. 
That's other history. 

Thanks!

**Comment by DomT4** [comment]
Is this resolved, or still working on it? Anything we can help with?

**Comment by manueljordan** [comment]
By my side I am going to update to the "El Capitan". It due the message _We're no longer building binary packages for OS X 10.8_

Thanks.

**Comment by DomT4** [comment]
Okay. Yeah, we only build binary packages for the three most recent OS X versions. Will close here, but please feel free to shout if you have any issues on the other side of upgrading.
