### ISSUE TITLE
Mac OS X and cpu-percentage

### ISSUE THREAD

**Issue by erikssone** [Homebrew/homebrew#47771]
I can see that Activity Monitor.app and `top` show the CPU usage stats, but htop seems to be in a world of it's own with the stats that it's reporting! This issue is present when I run htop with and without sudo.

**Comment by yawara** [comment]
I had a same issue and resolved it as follows:

```
sudo chown root:wheel /usr/local/Cellar/htop-osx/$VERSION/bin/htop
sudo chmod +s /usr/local/Cellar/htop-osx/$VERSION/bin/htop
``` 

Then you can execute `htop` properly without `sudo`.

**Comment by erikssone** [comment]
Thanks but that doesn't work no more. I did that "trick" on earlier versions and/or earlier versions of OS X.
Combo OS X 10.11.2 and htop 0.8.2.8 are still a miss cpu-usage wise https://dl.dropboxusercontent.com/u/2295771/htop2.png

**Comment by mikemcquaid** [comment]
@yawara We don't recommend `setuid` as it's terrible for security.

**Comment by mikemcquaid** [comment]
@erikssone This doesn't seem to be a Homebrew issue but is an issue with `htop` itself so I suggest you report it there.

**Comment by mistydemeo** [comment]
Just as a note, our "htop" is a fork called [htop-osx](https://github.com/max-horvath/htop-osx). Please make sure you report bugs there and not to the original htop developer!
