### ISSUE TITLE
Android Debug Bridge

### ISSUE THREAD

**Issue by wuffi** [Homebrew/homebrew#47777]
Hello everybody out there using homebrew,
There are two formulae installing android debug bridge - 'android-sdk' and 'android-platform-tool'
Unfortunately, both give me errors.
Running the adb command after installing android-sdk results in
"Segmentation fault: 11"
Running the adb command of android-platform-tool causes
"Illegal instruction: 4"
Can anyone of you replicate the problems?
My config on Mac OS X 10.7:
HOMEBREW_VERSION: 0.9.5
ORIGIN: (none)
HEAD: (none)
Last commit: never
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit core2
OS X: 10.7.5-i386
Xcode: 3.2.6
CLT: N/A
GCC-4.0: build 5494
GCC-4.2: build 5666
LLVM-GCC: build 2336
Clang: 4.2 build 425
MacPorts/Fink: /opt/local/bin/port
X11: 2.6.5 => /usr/X11
System Ruby: 1.8.7-p358
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: 1.7.0_79, 1.6.0_65-b14-462
Kind regards

**Comment by dunn** [comment]
Can you post `brew gist-logs android-sdk` and `brew gist-logs android-platform-tool`? Thanks!

**Comment by mistydemeo** [comment]
Looks like Google now requires OS X 10.8 or newer to run these tools.

**Comment by DomT4** [comment]
@mistydemeo Worth just chucking a `depends_on :macos => :mountain_lion` into the formula?

**Comment by mistydemeo** [comment]
Pushed commits that add minimum OS version requirements.
