### ISSUE TITLE
Install PostgreSQL release candidate using homebrew?

### ISSUE THREAD

**Issue by Kinnardian** [Homebrew/homebrew#47796]
I need the new `UPSERT` feature from Postgres 9.5. Is there an easy way to install the release candidate[1] using homebrew? 

[1] http://www.postgresql.org/about/news/1631/

**Comment by rakkesh** [comment]
```
$ brew info postgresql
postgresql: stable 9.4.5 (bottled), level 9.5rc1
```
So, you can install the release candidate using,

```
$ brew install postgresql --devel
```

**Comment by Kinnardian** [comment]
That worked! Thank you kindly.
