### ISSUE TITLE
Error: Failed to download resource "pod2man"

### ISSUE THREAD

**Issue by hbetts** [Homebrew/homebrew#47798]
Getting the following error while LinuxBrew attempts to download `podlators`.

Filing issue against homebrew as the file doesn't exist on the archive site, and homebrew uses the same download path as linuxbrew.

Archive site: http://archives.eyrie.org/software/perl/

```bash
==> Installing wget dependency: pod2man
==> Downloading http://archives.eyrie.org/software/perl/podlators-4.03.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "pod2man"
Download failed: http://archives.eyrie.org/software/perl/podlators-4.03.tar.xz
```

Possible solution is to upgrade the version URL to 4.04.

**Comment by UniqMartin** [comment]
Thanks for the report! I resolved the issue for now by fixing the download URL. (I guess it might take a little while until this ends up in Linuxbrew.) Feel free to submit a PR for the update to 4.04, if you like.

**Comment by UniqMartin** [comment]
> Feel free to submit a PR for the update to 4.04, if you like.

Never mind, there's already one I hadn't noticed: #47799.
