### ISSUE TITLE
gettext 0.19.7 does not build on 10.8.5

### ISSUE THREAD

**Issue by dcwar** [Homebrew/homebrew#47797]
Build fails with the following error on line 3666 of 02.make:

Undefined symbols for architecture x86_64:
  "_xmlOutputBufferGetContent", referenced from:
      __its_collect_text_content in libgettextsrc_la-its.o
  "_xmlXPathSetContextNode", referenced from:
      __its_get_content in libgettextsrc_la-its.o

Output of `brew gist-logs gettext`:
https://gist.github.com/anonymous/db25342d80d1d75e08fd

**Comment by turtlepa** [comment]
Also does not build on 10.7.5

**Comment by mvkorpel** [comment]
I get the same error when trying to `brew upgrade` on 10.7.5. I also tried building straight from the [gettext](https://www.gnu.org/software/gettext/) 0.19.7 source package, but that produced the same error. What worked for me was installing the Homebrew version of libxml2

    brew install libxml2

and then building gettext with

    ./configure --with-libxml2-prefix=/usr/local/opt/libxml2
    make
    make check

where the checks of the last stepped passed OK (if not skipped). I did not diagnose the problem further, but my guess would be that the system version of libxml2 is outdated.

**Comment by DomT4** [comment]
Yeah, it's the `libxml2` oldness that's the issue here. Checked it against GCC-5 in case there was some compiler weirdness there, but that wasn't the problem *for once*.

Fixed by https://github.com/Homebrew/homebrew/commit/66ed7b2ba71fa29fac600bc880d69d6f645db23c. Should be fine after a `brew update`.
