### ISSUE TITLE
`brew find` should be an alias of `brew search`

### ISSUE THREAD

**Issue by sehrgut** [Homebrew/homebrew#47795]
Just like we all make `-u` and `-h` flags bring up the help/usage statement, allowing the search command to be invoked by both "search" and "find" just makes sense. It violates minimal-astonishment every time I type `brew find foo` and have to recast my command as `brew search foo`.

**Comment by liweinan0423** [comment]
asdf

**Comment by liweinan0423** [comment]
:+1:  `find` is easier to type than `search` as well :)

**Comment by mikemcquaid** [comment]
I'd suggest using this instead https://github.com/Homebrew/homebrew-aliases
