### ISSUE TITLE
findutils updatedb fails on some filename encodings

### ISSUE THREAD

**Issue by sparr** [Homebrew/homebrew#47791]
$ sudo updatedb
    /usr/bin/sort: string comparison failed: Illegal byte sequence
    /usr/bin/sort: Set LC_ALL='C' to work around the problem.
    /usr/bin/sort: The strings compared were `/LIBRARY/FONTS/ō\216Ɩ\207ǻ\206ɻ\221.TTF' and `/LIBRARY/FONTS/ō\216Ɩ\207ɻ\221Ľ\223.TTF'.

While I can set the environment variable that sort is looking for myself, I sorta expect updatedb to handle this for me.

**Comment by UniqMartin** [comment]
Can you please paste the output of `locale` and `env | egrep '^(LANG=|LC_)' | sort`? I suspect you're not using an UTF-8 locale which `sort` relies on to work correctly.

**Comment by sparr** [comment]
$ locale
    LANG="en_US.UTF-8"
    LC_COLLATE="en_US.UTF-8"
    LC_CTYPE="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_MONETARY="en_US.UTF-8"
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_ALL=
    $ env | egrep '^(LANG=|LC_)' | sort
    LANG=en_US.UTF-8

**Comment by UniqMartin** [comment]
Your locale settings seem to be fine. I'm afraid you just discovered a bug in either `updatedb` (or worse in Apple's `sort`), in which case we can't help. You could try searching if this is a known issue and if not, report it upstream. If all else fails, you might have to use the workaround suggested by `sort`.

**Comment by sparr** [comment]
reported upstream at https://savannah.gnu.org/bugs/index.php?46846

**Comment by sparr** [comment]
temporary workaround is to `export LC_ALL='C'` at the top of the updatedb script

**Comment by UniqMartin** [comment]
> reported upstream at https://savannah.gnu.org/bugs/index.php?46846

Thank you! Please let us know once the bug is confirmed upstream and there's a fix we can apply. We can add that to the formula until there's an update that contains the fix.

**Comment by sparr** [comment]
Thanks @DomT4 @UniqMartin
