### ISSUE TITLE
libjson-rpc-cpp bottle looking for wrong libmicrohttpd

### ISSUE THREAD

**Issue by area** [Homebrew/homebrew#47806]
The bottled version of libjson-rpc-cpp is looking for:

    otool -L ./libjsonrpccpp-server.0.5.0.dylib
    /Users/alex/Downloads/libjson-rpc-cpp/0.5.0/lib/libjsonrpccpp-server.0.5.0.dylib:
    @@HOMEBREW_PREFIX@@/opt/libjson-rpc-cpp/lib/libjsonrpccpp-server.0.dylib (compatibility version 0.0.0, current version 0.5.0)
    @loader_path/libjsonrpccpp-common.0.dylib (compatibility version 0.0.0, current version 0.5.0)
    @@HOMEBREW_PREFIX@@/opt/libmicrohttpd/lib/libmicrohttpd.10.dylib (compatibility version 43.0.0, current version 43.0.0)
    @@HOMEBREW_PREFIX@@/opt/jsoncpp/lib/libjsoncpp.0.dylib (compatibility version 0.0.0, current version 0.10.5)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)

Note the line showing it is linked to `libmicrohttpd.10.dylib` . But the bottled version of libmicrohttpd:

    ls -1 ./libmicrohttpd/0.9.47_1/lib
    libmicrohttpd.12.dylib
    libmicrohttpd.a
    libmicrohttpd.dylib
    pkgconfig

Which leads to compilation errors. Uninstalling `libjson-rpc-cpp` and reinstalling it with the `--from-source` flag solves the issue, so it seems to be a problem with the bottles being used. For reference, `brew` downloads from:

    https://homebrew.bintray.com/bottles/libjson-rpc-cpp-0.5.0.el_capitan.bottle.1.tar.gz
    https://homebrew.bintray.com/bottles/libmicrohttpd-0.9.47_1.el_capitan.bottle.tar.gz

which seem to be the right (i.e. latest) versions.

**Comment by bfontaine** [comment]
I regenerated the bottles; it should work after a `brew update`.

**Comment by area** [comment]
This now works - many thanks.
