### ISSUE TITLE
SHA256 mismatch...

### ISSUE THREAD

**Issue by rtalexander** [Homebrew/homebrew#47827]
I'm getting the following error when trying to install `unzip`:

    $brew install unzip
    ==> Installing unzip from homebrew/dupes
    ==> Downloading https://downloads.sourceforge.net/project/infozip/UnZip%206.x%20%28latest%29/UnZip%206.0/unzip60.tar.gz
    ==> Downloading from http://10.100.0.241:15871/cgi-bin/blockpage.cgi?ws-session=984072911
    ######################################################################## 100.0%
    Error: SHA256 mismatch
    Expected: 036d96991646d0449ed0aa952e4fbe21b476ce994abc276e49d30e686708bd37
    Actual: 7c004eea839f54aa2bfcdee85fbfc849c2a54f39e06f1f51f02a6b6909c2b140
    Archive: /Library/Caches/Homebrew/unzip-6.0.tar.gz
    To retry an incomplete download, remove the file above.

Removing the above reference file and trying again does not resolve the issue.

I'm doing this on a fresh install of El Capitan. I did run `brew update` prior to the start of the installation process. `brew outdated` reports nothing as being out of date.

For what it's worth, I'm having a similar problem with `aescrypt`:

    $ brew install aescrypt
    ==> Downloading http://aescrypt.sourceforge.net/aescrypt-0.7.tar.gz
    ==> Downloading from http://10.100.0.241:15871/cgi-bin/blockpage.cgi?ws-session=
    ######################################################################## 100.0%
    Error: SHA256 mismatch
    Expected: 7b17656cbbd76700d313a1c36824a197dfb776cadcbf3a748da5ee3d0791b92d
    Actual: a56d16e81bada60df40243ce9a306a41632bb00a94844398532dc87ade254734
    Archive: /Library/Caches/Homebrew/aescrypt-0.7.tar.gz
    To retry an incomplete download, remove the file above.

Any suggestions are greatly appreciated.

**Comment by bfontaine** [comment]
I don’t have any issue here:
```
b i unzip
==> Installing unzip from homebrew/dupes
==> Downloading https://downloads.sourceforge.net/project/infozip/UnZip%206.x%20%28latest%29/UnZip%206.0/unzip60.tar.gz
==> Downloading from http://freefr.dl.sourceforge.net/project/infozip/UnZip%206.x%20%28latest%29/UnZip%206.0/unzip60.tar.gz
######################################################################## 100,0%
==> make -f unix/Makefile macosx
==> make prefix=/usr/local/Cellar/unzip/6.0 MANDIR=/usr/local/Cellar/unzip/6.0/share/man install
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.
==> Summary
🍺  /usr/local/Cellar/unzip/6.0: 14 files, 482.2K, built in 7 seconds
```

Do you use a proxy?

**Comment by UniqMartin** [comment]
> `http://10.100.0.241:15871/cgi-bin/blockpage.cgi?ws-session=984072911`

It looks like you are redirected to a blocking page of your ISP or some other involved party. Can you check whether you can download any of these from your browser, e.g. <http://aescrypt.sourceforge.net/aescrypt-0.7.tar.gz>, and whether you can access <http://sourceforge.net/> at all?

The files are downloading fine here on my machine.

**Comment by DomT4** [comment]
Please let us know if we can help further here, Thanks!
