### ISSUE TITLE
Fortran requirements always install gcc

### ISSUE THREAD

**Issue by sambrightman** [Homebrew/homebrew#47834]
I have `gcc5` installed from `homebrew/versions`. I do not want to automatically upgrade to GCC 6 when the `gcc` formula moves. If I try to install `octave`, it `depends_on :fortran` and tries to install `gcc`. GCC takes a long time to build and then fails to symlink due to gcc5 symlinks already being present. `octave`'s dependency on `arpack` fails at configure time as it does not find a working Fortran compiler.

This all seems suboptimal to me but I don't know what the intended workflow is. I would hope that I can install a GCC version of my choosing and use that to build/install Octave. `gcc` installation symlinks gfortran to the appropriate version-suffixed binary but gcc5 does not. I hoped that if I manually symlink it or set `FC=/usr/local/bin/gfortran-5` then all would work. However, Homebrew still attempts to install `gcc` as a dependency of `arpack` via `:fortran`.

From what I can tell the following code is responsible for this (in `formula_installer.rb`):

    def install_requirement_default_formula?(req, dependent, build)
      return false unless req.default_formula?
      return true unless req.satisfied?
      return false if req.run?
      install_bottle_for?(dependent, build) || build_bottle?
    end

and this:

        elsif install_requirement_default_formula?(req, dependent, build)
          dep = req.to_dependency
          deps.unshift(dep)
          formulae.unshift(dep.to_formula)
          Requirement.prune

It seems that the default formula is installed regardless of whether the requirement is satisfied. This seems wrong to me but I'm likely missing some context. Perhaps the `default_formula` should depend on a compiler symbol and magically recognise that gcc5 will do.

Changing the default_formula of `FortranRequirement` to `gcc5` allows me to specify the `FC` environment variable and install Octave (also without an additional GCC install). It seems this could be further improved if `FortranRequirement` (and `ENV.fortran`?) were more flexible in finding gfortran with suffixes, thus requiring no additional configuration from the user.

**Comment by mikemcquaid** [comment]
> It seems that the default formula is installed regardless of whether the requirement is satisfied.

When installing from bottles: yes, this is intentional. If using binary packages then install the formula they were built against (e.g. the `default_formula`) as a dependency because you cannot consistently just change the dependency after compilation and expect things to work.

> It seems this could be further improved if FortranRequirement (and ENV.fortran?) were more flexible in finding gfortran with suffixes, thus requiring no additional configuration from the user.

This isn't going to happen, I'm afraid. We support using the latest version we package in the same repository. If you want different behaviour you will need to create your own formula.

**Comment by sambrightman** [comment]
I see. I'm still not really following how the requirement is "satisfied" by e.g. specifying FC environment variable, yet also requires an additional installation. What breakage would changing to `return false if req.satisfied?` cause?

What is the intended workflow to build using a specific GCC version? It looks like maybe this works without having to patch Homebrew itself:

    FC=/usr/local/bin/gfortran-5 brew install --build-from-source --default-fortran-flags octave

I presume getting this to work on upgrades would require a custom formula?

**Comment by mikemcquaid** [comment]
> What breakage would changing to return false if req.satisfied? cause?

It'd break binary packages as described above because the Requirement is what's required to build but different things are/may be required at runtime.

> FC=/usr/local/bin/gfortran-5 brew install --build-from-source --default-fortran-flags octave

Yes, this works.

> I presume getting this to work on upgrades would require a custom formula?

Yeh, more-or-less, sorry.
