### ISSUE TITLE
QT5 Frameworks not standalone when built with --with-d-bus

### ISSUE THREAD

**Issue by area** [Homebrew/homebrew#47848]
I am currently trying to build `ethereum` through `homebrew` (see https://github.com/ethereum/webthree-helpers/pull/81 for the issues; the tap is https://github.com/ethereum/homebrew-ethereum/ ) and have now run into a problem with QT5. After `qt5` has been built (with the `--with-d-bus` flag) as a requirement, the `ethereum` brew builds correctly, and the brew successfully runs `make`. Unfortunately, it fails during the checks performed during a `make install`, specifically the ones that check that all libraries required have either been copied into the `.app` files generated, or are system libraries.

It is easy to see why these tests fail: The `dbus` library required by QtWebEngineProcess isn't copied into the bundle, but is linked to in `/usr/local/opt/d-bus/lib/libdbus-1.3.dylib`:

    otool -L ./alethzero/alethfive/AlethFive.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
    ./alethzero/alethfive/AlethFive.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess:
    /usr/local/opt/d-bus/lib/libdbus-1.3.dylib (compatibility version 18.0.0, current version 18.6.0)
    @executable_path/../../../../QtWebEngineCore (compatibility version 5.5.0, current version 5.5.1)
    @executable_path/../../../../../../../QtCore.framework/QtCore (compatibility version 5.5.0, current version 5.5.1)
    /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

This is particularly strange at first blush, as:

    otool -L ./alethzero/alethfive/AlethFive.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/QtWebEngineCore | grep dbus
    @loader_path/../../../libdbus-1.3.dylib (compatibility version 18.0.0, current version 18.6.0)

i.e. it is correctly copied in for some of the QT frameworks. The same is seen for the Frameworks present in the QT5 Cellar:

    /usr/local/Cellar/qt5/5.5.1_2/Frameworks> otool -L QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
    QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess:
    /usr/local/opt/d-bus/lib/libdbus-1.3.dylib (compatibility version 18.0.0, current version 18.6.0)
    @executable_path/../../../../QtWebEngineCore (compatibility version 5.5.0, current version 5.5.1)
    @executable_path/../../../../../../../QtCore.framework/QtCore (compatibility version 5.5.0, current version 5.5.1)
    /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

So I believe the problem is either in the way the brew handles the `--with-d-bus` flag or how QT5 itself handles building with `dbus`. I note that running

    macdeployqt QtWebEngineProcess.app -executable=./QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess

from inside `QtWebEngineCore.framework/Versions/5/Helpers/` solves the issue:
    
    macdeployqt QtWebEngineProcess.app -executable=./QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
    > otool -L ./QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess ./QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess:
    @loader_path/../Frameworks/libdbus-1.3.dylib (compatibility version 18.0.0, current version 18.6.0)
    @executable_path/../../../../QtWebEngineCore (compatibility version 5.5.0, current version 5.5.1)
    @executable_path/../../../../../../../QtCore.framework/QtCore (compatibility version 5.5.0, current version 5.5.1)
    /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

This feels very similar to the bug described at https://bugreports.qt.io/browse/QTBUG-41611 (indeed, it's how I found the above line to run), but it was allegedly fixed in QT 5.4, whereas this is QT 5.5

Running the above command in the `ethereum` brew seems like the wrong solution, as every brew wanting to use the `--with-d-bus` flag would need to run it too. Running it on the built Frameworks after building using the flag `--with-d-bus` in the QT5 formula seems like a really kludgy hack. I'm hoping someone more *au fait* with QT has some insight as to how to proceed, whether we need to change the actual compilation done by `homebrew` somehow (i.e. more/different options or flags when `--with-d-bus` is used) or this should be run up the chain to the QT team (which unfortunately feels more likely).

**Comment by area** [comment]
This seems exactly like the bug reported at https://bugreports.qt.io/browse/QTBUG-50155 , so I guess this is a QT issue as I suspected, and not a problem for the `homebrew` team.

**Comment by area** [comment]
Reopened by popular request over at the ethereum/homebrew-ethereum repository. Would the homebrew maintainers be happy with a PR to add the workaround at https://github.com/ethereum/webthree-umbrella/wiki/QTBUG-50155-workaround as a post-install command?

**Comment by UniqMartin** [comment]
Sorry, but I'm not sure I fully understand where the problem is. When building `qt5` with `--with-d-bus`, Homebrew explicitly asks the Qt build system to link to the version of `d-bus` provided by Homebrew. Both `qt5` and `d-bus` then happily live and work as installed by Homebrew and serve other formulae that depend on them. Does anything not work as expected with this setup?

Note that creating a relocatable Qt 5 installation to use it to create stand-alone Qt-based applications that can be redistributed is not the primary goal of Homebrew. Wouldn't the official binaries provided by Qt be a much better fit in this scenario?

**Comment by mikemcquaid** [comment]
You can (and should) use `install_name_tool` to fix these up in your software before shipping; it's a Qt bug rather than a Homebrew one and it's not one that is affecting our software. I'd strongly recommend shipping your software as a `.app` bundle or `.framework` on OS X. The `DeployQt4` module for CMake (which I created) may also be useful in solving this problem. Good luck!

**Comment by bobsummerwill** [comment]
Thanks for the extra insight, @mikemcquaid and @UniqMartin!
Best wishes.
