### ISSUE TITLE
enhancement:  search by category or function

### ISSUE THREAD

**Issue by gaming-hacker** [Homebrew/homebrew#47847]
add some metatags to the database, so it's possible to search by function, category.  say i wanted to find image processing, drones, etc instead of having to external search to find the formula

**Comment by mikemcquaid** [comment]
This is something that, like descriptions, would need to be done outside Homebrew as an external command and then brought into core when it's 100% complete. My personal view is that it's rarely useful because categorisation isn't generally obvious.

**Comment by bfontaine** [comment]
You might want to try [homebrew-search](https://bfontaine.github.io/homebrew-search/) (disclamer: my project); it matches on descriptions and executables.

**Comment by gaming-hacker** [comment]
i don't see what it so hard about adding metadata tags, a "proper" formula should have keywords, yes?  add the ability to find/search the desc as well as formula.  all that is needed is to extend the search to grep the description and pipe that out to the shell, why is this so hard?

@bfontaine damn good page almost what i'm looking for.  can you extend this a little bit? say i was looking for gdate, search date, no, search gdate, no, search utils, no, search time, no.... search cal, no....search tools, no.... ad infinitum.....   because it's buried in one of the coreutils so unless you know where to look for it, you'll ending up at duckduckgo

**Comment by mikemcquaid** [comment]
> i don't see what it so hard about adding metadata tags, a "proper" formula should have keywords, yes? add the ability to find/search the desc as well as formula. all that is needed is to extend the search to grep the description and/or binaries if it's a package with many and pipe that out to the shell, why is this so hard?

It is harder than you think. Regardless, as I said before, if it's easy you should give it a go and we'll consider including it when it's working for all formulae.

**Comment by gaming-hacker** [comment]
use Data::Dumper qw(Dumper);

my (%hash,%tmp);
my $result;

simple perl code

while (<DATA>)
{
  chomp;
   my ($key, $val)= split(/\s+/, $_);
   $hash{$key} = $val;
}
my @element=qw(0003cacf);
if(    grep {$hash{$_} } $element[0])  {
  if($hash{$element[0]}>=0.30){$result=1.0;}else{$result=0.0;}
  }

**Comment by mikemcquaid** [comment]
@gaming-hacker We don't use Perl and any changes would need to be submitted as a pull request to Homebrew core.
