### ISSUE TITLE
Enhancement:: need --kitchen-sink, --bath-tub, --deep-end options

### ISSUE THREAD

**Issue by gaming-hacker** [Homebrew/homebrew#47846]
formulas like ffmpeg, imagemagick, etc are too unwieldy, i always put every option
 brew install imagemagick --kitchen-sink  => install every Recommended & Optional from BOTTLE
 brew install imagemagick --bath-tub = >BUILD every Recommended & Optional  --build-with-source (where available)
 brew install imagemagick --deep-end => BUILD every Recommended & Optional --HEAD (where available) 

this should be easy to propage the flags through the ENV

**Comment by dunn** [comment]
> brew install imagemagick --kitchen-sink => install every Recommended & Optional from BOTTLE

Not sure what you mean here; bottles use the default options, and any change means a source build.

For the other flags, some recommended options conflict with optional options (like LibreSSL vs OpenSSL); how would the conflict resolution work?

**Comment by DomT4** [comment]
We have turned down similar suggestions to this before because there are plenty of options that can't or shouldn't be built on top of each other. I'm not sure that's a problem that can be easily worked around.

**Comment by gaming-hacker** [comment]
i don't see whatever the env var in the formula that controls the type of build ( --HEAD --build-from-source --bottle ) doesn't get passed to the dependencies instead of default.  you can't launch the process with  brew install ${dependency#1) $1,  brew install ${dependency#2} $1....

i do this with bash now, i never let brew install dependencies by itself, as i never know what the default for any formula is, if it doesn't have a head or tarball i create/get one.  that's how i know your pkg-config build from source is broken on xcode 7.2, osx 10.11.2

also this doesn't break the current checking, if the dependency conflicts the flag still gets raised
i know for a fact that every option available on ffmpeg and imagemagick can be installed.

i've parsed the configure which gets dumped that into a file which bash grinds though with 'brew install with my flags', i never worry about conflicts as libs/bin are built simultaneously as i build ffmpeg 4x times week testing modifications to codecs. 
brew install ffmpeg --deep-end
                                     1 turns on all libs/dependencies
                                      2 passes the --HEAD var to dependencies
                                     3 run the dependency checker->eval for conflicts 
>exit if any > proceed with bottle flag passed
