### ISSUE TITLE
Question about output of brew deps

### ISSUE THREAD

**Issue by Yann-R** [Homebrew/homebrew#47850]
Hello,

I must be missing something but I am surprised to see that the resulting formulae listed by `brew deps formula` can become smaller when I add the format option `--tree`:
```
% brew deps qt
boost
cmake
d-bus
git
icu4c
makedepend
mysql
openssl
pkg-config
postgresql
readline
sphinx-doc
```
```
% brew deps --tree qt
qt (required dependencies)
└── :git
└── openssl
    └── makedepend
        └── pkg-config
```
This difference does not appear clear to me from the manual page of brew that would just imply a matter of formatting:  _"If --tree is passed, show dependencies as a tree"_.
Moreover the "missing" formulae do not seem to be clearly related to the fact of being currently installed/uninstalled, as those two subsets would be the following;
```
% brew deps --installed qt
boost
cmake
icu4c
makedepend
openssl
pkg-config
readline
```
And consequently, the uninstalled dependencies for qt would be:
```
d-bus
git
mysql
postgresql
sphinx-doc
```

**Comment by UniqMartin** [comment]
You are right in that this is somewhat inconsistent. The first line of `brew deps --tree qt` hints at what is going on, as it reads `qt (required dependencies)`. `brew deps --tree qt` is more similar to `brew deps --skip-optional qt`. `brew info qt` will also help you figure out which of the direct dependencies are optional, recommended, or required.

> Moreover the "missing" formulae do not seem to be clearly related to the fact of being currently installed/uninstalled, […]

True. Whether those dependencies are installed or not doesn't factor into the inconsistency you observe.

**Comment by Yann-R** [comment]
@UniqMartin Thanks for the point about `--skip-optional`.
That gives a sense in this apparent inconsistency. Great.

**Comment by dunn** [comment]
See #41841 and #41947 for some previous discussion.
