### ISSUE TITLE
--default-fortran-flags does not seem to work

### ISSUE THREAD

**Issue by sambrightman** [Homebrew/homebrew#47852]
If specifying a custom Fortran compiler (e.g. with the `FC` environment variable), a warning is printed from `ENV.fortran`:

          No Fortran optimization information was provided.  You may want to consider
          setting FCFLAGS and FFLAGS or pass the `--default-fortran-flags` option to
          `brew install` if your compiler is compatible with GCC.

          If you like the default optimization level of your compiler, ignore this
          warning.

Supplying `--default-fortran-flags` does not seem to affect this, however. I think `ARGV` has been sanitised by this point and sanitisation does not include the flag.

I ran this command:

    FC=/usr/local/bin/gfortran-5 brew install --build-from-source --default-fortran-flags octave

Also tried with the flag after the formula name.

**Comment by UniqMartin** [comment]
Thanks you for this report! Your analysis is quite spot-on. The flag isn't properly propagated down to the build environment. I'll make sure to fix this soon.

**Comment by UniqMartin** [comment]
This should be fixed after running `brew update` and no longer output this confusing message.
