### ISSUE TITLE
Failed test: brew tests TEST=test_caveats

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew#47861]
Am I doing something wrong here? `brew tests` succeeds as expected.

```
❯❯❯ brew tests TEST=test_caveats
Run options: --seed 56867

# Running:

EE

Finished in 0.005040s, 396.8254 runs/s, 0.0000 assertions/s.

  1) Error:
CaveatsTests#test_empty?:
NameError: uninitialized constant Homebrew::TestCase::Formulary
    /usr/local/Library/Homebrew/test/testing_env.rb:71:in `formula'
    /usr/local/Library/Homebrew/test/test_caveats.rb:5:in `setup'


  2) Error:
CaveatsTests#test_f:
NameError: uninitialized constant Homebrew::TestCase::Formulary
    /usr/local/Library/Homebrew/test/testing_env.rb:71:in `formula'
    /usr/local/Library/Homebrew/test/test_caveats.rb:5:in `setup'

2 runs, 0 assertions, 0 failures, 2 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib:/usr/local/Library/Homebrew/test" -I"/usr/local/Library/Homebrew/test/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib" "/usr/local/Library/Homebrew/test/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test_caveats" ]

Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by bfontaine** [comment]
It’s because some test files don’t `require` the necessary core modules and instead rely on their global availability. It’s ok for `brew tests` but the ability to test a specific file is very recent.

**Comment by sjackman** [comment]
Thanks, Baptiste.

**Comment by sjackman** [comment]
When running `brew tests` the output of `print` and `p` don't appear to make it to the console. Where does this output go, and how do I display it? My apologies for the off-topic question.

**Comment by bfontaine** [comment]
I think `stdout` is muted by the test runner. You can try `$stdout.write` to print debugging info.

**Comment by sjackman** [comment]
`$stderr.write` appears to be similarly muted.

**Comment by bfontaine** [comment]
`$stderr.write` works for me in most cases.

**Comment by sjackman** [comment]
I found the culprit, aptly named [`shutup`](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/test/test_formula_installer.rb#L16). Perhaps `shutup` should be disabled when the `-v` option is specified.
