### ISSUE TITLE
libtool and imagemagick:: building module support

### ISSUE THREAD

**Issue by gaming-hacker** [Homebrew/homebrew#47879]
i'm building multi-lib 8/16/32 libs for imagemagick and it's choking on libltdl which manages modules

imagemagick config
checking for libltdl... 
checking ltdl.h usability... yes
checking ltdl.h presence... yes
checking for ltdl.h... yes
checking for lt_dlinit in -lltdl... no

i built libtool from head 

nm -gU libltdl.dylib |grep lt_dlinit
50:0000000000001880 T _lt_dlinit

so the function is in the lib but probably has an invalid API

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by mikemcquaid** [comment]
And also: to help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

As an aside, I've had to ask this a few times @gaming-hacker. Please spend a bit more time on the new issues you open, thanks.

**Comment by gaming-hacker** [comment]
i found it in the imagemagick api
