### ISSUE TITLE
Unable to install homebrew on my mac

### ISSUE THREAD

**Issue by pramodsrao** [Homebrew/homebrew#47885]
Mac version --> OS X Yosemite - 10.10.5

When I run the following command I get these results. how do i resolve my local usr user not on sudoers file.

Last login: Sat Jan  9 04:19:50 on ttys001
MACC02PTNUGG8WP:~ fca71ca$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/man/man1/brew.1
==> The following directories will be made group writable:
/usr/local/.
/usr/local/bin
/usr/local/include
/usr/local/lib
/usr/local/share
/usr/local/share/man
/usr/local/share/man/man1
/usr/local/share/doc
==> The following directories will have their owner set to fca71ca:
/usr/local/.
/usr/local/bin
/usr/local/include
/usr/local/lib
/usr/local/share
/usr/local/share/man
/usr/local/share/man/man1
/usr/local/share/doc
==> The following directories will have their group set to admin:
/usr/local/.
/usr/local/bin
/usr/local/include
/usr/local/lib
/usr/local/share
/usr/local/share/man
/usr/local/share/man/man1
/usr/local/share/doc

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/. /usr/local/bin /usr/local/include /usr/local/lib /usr/local/share /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/doc
Password:
fca71ca is not in the sudoers file.  This incident will be reported.
Failed during: /usr/bin/sudo /bin/chmod g+rwx /usr/local/. /usr/local/bin /usr/local/include /usr/local/lib /usr/local/share /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/doc
MACC02PTNUGG8WP:~ fca71ca$

**Comment by mikemcquaid** [comment]
You need to be an administrator to install into `/usr/local`, unfortunately. You should ask whoever has administrator rights on your machine to install Homebrew for you.

**Comment by pramodsrao** [comment]
correct. can't add my username to sudoers. this is an office mac. let me try on my personal mac.. checked sudoers file. owned by root. I am not root on this mac...

MACC02PTNUGG8WP:etc fca71ca$ ls -l sudo*
-r--r-----  1 root  wheel   257 Jul 25 00:34 sudo_lecture
-r--r-----  1 root  wheel  1275 Sep  9  2014 sudoers

**Comment by mikemcquaid** [comment]
You don't need to be `root` but you do need to be able to run `sudo` commands. If it's in your office: I suggest asking your IT department to install Homebrew.

**Comment by pramodsrao** [comment]
ok will try that. Thanks for quick responses. BTW, I was able to install on my personal mac.

**Comment by pramodsrao** [comment]
I got homebrew installed. Now I need to install a specific version 5.10.11 of apache-activemq. when I give the install apache-activemq command, it is installing the latest version which is 5.10.12. see below.

Pramods-MacBook-Air:~ Pramod$ brew install apache-activemq
==> Downloading https://www.apache.org/dyn/closer.cgi?path=/activemq/5.11.2/apache-activemq-5.11.2-bin.tar.gz
Error: Failed to download resource "activemq"
Download failed: Couldn't determine mirror, try again later.
Pramods-MacBook-Air:~ Pramod$

**Comment by mikemcquaid** [comment]
We don't support installing specific versions, sorry.

**Comment by DomT4** [comment]
If you need a specific version we recommend creating your own tap for them. There's documentation on doing that [here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md). It's relatively simple and will be the easiest way for you to grab the functionality you wish to.
