### ISSUE TITLE
OfflineIMAP formula doesn't install example configuration files

### ISSUE THREAD

**Issue by strugee** [Homebrew/homebrew#47884]
Normally OfflineIMAP's example configuration files get installed somewhere in `/usr/share` (maybe `/usr/share/doc`), but under Homebrew, I can't find them anywhere, including `/usr/local/share` and the Cellar.

**Comment by mikemcquaid** [comment]
It should be a matter of doing `share.install` in the `install` method. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by strugee** [comment]
Whoops. Looks like it gets installed in `/usr/local/etc`; sorry for the noise.
