### ISSUE TITLE
conflicts_with doesn't work with references to untapped taps

### ISSUE THREAD

**Issue by krishicks** [Homebrew/homebrew#47909]
We recently moved a tap from one repository to another, and renamed it as well. We received a PR to add a conflicts_with line for the old tap, which seemed legitimate until we received a complaint that someone who had just tapped the new tap wasn't able to install the formula: https://github.com/cloudfoundry/cli/issues/726

`conflicts_with` works if you have the original tap tapped, but not otherwise.

**Comment by DomT4** [comment]
I'm pretty sure this is working-as-intended. When you declare a `conflicts_with` against another file we attempt to load that file when the formula is called, so if there's no file to load it *should* error. This is the same reason in the core we don't have `conflicts_with` against problematic formulae in our taps.

Whether or not you want to debate the design of the mechanism is open, but I think under the current design this is entirely intended.

**Comment by krishicks** [comment]
I would like to debate the design.

If A conflicts with B and B is installed, fail to install A. *In all other scenarios, A should be installed.*

It would seem to me that this feature was implemented specifically to get around conflicts in things in homebrew core, not in other taps which may not even be tapped. See https://github.com/Homebrew/homebrew/commit/2814e3a9fa88acf262062a26af15d87dc9f572d6, where every formula listed is not from a tap.

**Comment by mikemcquaid** [comment]
I can see the argument both ways here. What does your `conflicts_with` look like: `conflicts_with "formula"` or `conflicts_with "user/tap/formula"`? If it's the latter and that doesn't work: it should be fixed (and, I think, could be relatively easily).

**Comment by krishicks** [comment]
Using the fully-qualified tap name works. I'll close this issue.

Thanks!
