### ISSUE TITLE
Unable to get Homebrew working (and also rails and postgres) after trying to do `brew upgrade postgres`

### ISSUE THREAD

**Issue by jacqueline-homan** [Homebrew/homebrew#47910]
Here is a gist file of my terminal output:

https://gist.github.com/jacqueline-homan/243a352ad37ec267d797#file-unable-to-get-homebrew-postgres-and-rails-working

**Comment by dunn** [comment]
It looks like psql is already running; what happens if you do `psql -d postgres`?

**Comment by jacqueline-homan** [comment]
I get `zsh: command not found: psql`

**Comment by dunn** [comment]
Try reinstalling; `brew reinstall postgresql`.

**Comment by jacqueline-homan** [comment]
I can't run Homebrew. It's not working for me.

**Comment by jacqueline-homan** [comment]
`➜  ~  brew reinstall postgresql
==> Reinstalling postgresql
Error: Permission denied - /Library/Caches/Homebrew/Formula/postgresql.brewing
➜  ~  
`

**Comment by dunn** [comment]
Oh sorry, from the Gist you posted I thought you had resolved the permissions issues.

**Comment by dunn** [comment]
Is `brew doctor` still telling you all's well?

**Comment by jacqueline-homan** [comment]
Yep

On Sun, Jan 10, 2016 at 12:10 PM, Alex Dunn <notifications@github.com>
wrote:

> Is brew doctor still telling you all's well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Homebrew/homebrew/issues/47910#issuecomment-170371736>
> .
>



-- 


[image: --]
Jacqueline Homan
[image: http://]about.me/jacqueline_homan
<http://about.me/jacqueline_homan>

**Comment by jacqueline-homan** [comment]
I mean no. Brew doctor and brew <anything> is NOT working at all for me

On Sun, Jan 10, 2016 at 12:32 PM, Jacqueline Homan <
jacquelinehoman7@gmail.com> wrote:

> Yep
>
> On Sun, Jan 10, 2016 at 12:10 PM, Alex Dunn <notifications@github.com>
> wrote:
>
>> Is brew doctor still telling you all's well?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Homebrew/homebrew/issues/47910#issuecomment-170371736>
>> .
>>
>
>
>
> --
>
>
> [image: --]
> Jacqueline Homan
> [image: http://]about.me/jacqueline_homan
> <http://about.me/jacqueline_homan>
>
>



-- 


[image: --]
Jacqueline Homan
[image: http://]about.me/jacqueline_homan
<http://about.me/jacqueline_homan>

**Comment by dunn** [comment]
What's the output of `brew doctor` now?

**Comment by jacqueline-homan** [comment]
I'll have to paste it in a git smile. One moment please...

**Comment by jacqueline-homan** [comment]
https://gist.github.com/jacqueline-homan/5bf957e953b4e881a56a#file-output-of-brew-doctor

**Comment by jacqueline-homan** [comment]
Now, I have another mac account too (also w/ admin privileges), let me try it there and get the output as well, too.. brb

**Comment by jacqueline-homan** [comment]
https://gist.githubusercontent.com/jacqueline-homan/1b06438b4c0801ecf820/raw/8af965168b74d0c803ffa2ace81dc9d7358f6d6c/brew%2520doctor%2520output%2520on%2520other%2520Mac%2520user%2520account%2520(also%2520with%2520admin%2520privileges)

**Comment by dunn** [comment]
Run `sudo chown -R $(whoami):admin /usr/local` on the first machine and `brew prune` on the second; if `brew doctor` still gives errors then something's fishy.

**Comment by jacqueline-homan** [comment]
Here is the admin account one:
![whoami](https://cloud.githubusercontent.com/assets/3537889/12223105/3ef335a8-b79c-11e5-93a2-ae4649c8a5c1.png)

And here is the one from my other Mac user account (which also has admin privileges):
![untitled](https://cloud.githubusercontent.com/assets/3537889/12223109/5e667c6a-b79c-11e5-97ce-2bde0556df45.png)

**Comment by dunn** [comment]
OK, then `sudo chown -R $(whoami):admin /usr/local` on the second as well.  Can you `brew reinstall postgresql` on the first, now?

**Comment by jacqueline-homan** [comment]
I just logged back onto my computer and got this at the prompt:
![shell_login_notworking](https://cloud.githubusercontent.com/assets/3537889/12223404/9380ede2-b7a4-11e5-956c-00355b47791c.png)

So I don't think anything else will work, either.

**Comment by jacqueline-homan** [comment]
And here is what happened after trying to do what you said:

https://gist.github.com/jacqueline-homan/2645d4472d6c01612660

**Comment by dunn** [comment]
Looks like it installed fine, and all those broken symlinks will be cleaned out with `brew prune`.

The other error is probably because you have `git` aliased to `hub` but it's not installed: `brew install hub`.

**Comment by jacqueline-homan** [comment]
`[~] ruby-2.2.1 $ brew prune
Pruned 3725 symbolic links and 169 directories from /usr/local
[~] ruby-2.2.1 $ brew doctor
Your system is ready to brew.
[~] ruby-2.2.1 $ brew install hub
==> Downloading https://homebrew.bintray.com/bottles/hub-2.2.2.el_capitan.bottle
######################################################################## 100.0%
==> Pouring hub-2.2.2.el_capitan.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/hub/2.2.2: 9 files, 10.3M
[~] ruby-2.2.1 $ brew list
hub		openssl		postgresql	readline
[~] ruby-2.2.1 $ psql
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
[~] ruby-2.2.1 $ psql -d postgres  
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
[~] ruby-2.2.1 $ 
`

**Comment by dunn** [comment]
Since you reinstall PSQL it won't be running. Does `postgres -D /usr/local/var/postgres` work?

**Comment by jacqueline-homan** [comment]
I did not get a chance to try that yet, I was trying to see if fixing it in the admin Mac account would carry over and fix things in the "jacqueline" Mac user account for home-brew, postgres, and dvm, And apparently it didn't:

Here's from the primary ("admin") Mac account:
https://gist.github.com/jacqueline-homan/7fad3646c94c3bd1587b

and here's from the "jacqueline" Mac account:
https://gist.github.com/jacqueline-homan/55248a6bb3be58f7cfaa

**Comment by jacqueline-homan** [comment]
I will now try that last thing you said...

**Comment by jacqueline-homan** [comment]
Nope. This is from my primary Mac account (the one called "admin", where I had to set up an Apple ID). And it don't work:
![still not working](https://cloud.githubusercontent.com/assets/3537889/12223642/d1436bae-b7aa-11e5-9137-ff9d9883e1a2.png)

**Comment by jacqueline-homan** [comment]
I have no clue how to fix :'(

**Comment by dunn** [comment]
PSQL databases usually need to be upgraded after major updates: http://www.postgresql.org/docs/9.5/static/upgrading.html

That's a PostgreSQL issue though, not a Homebrew one, and I'm afraid I don't have the time or expertise to help there.  Let us know if you have further questions about Homebrew!
