### ISSUE TITLE
'brew info --json' doesn't distinguish between optional and required dependencies

### ISSUE THREAD

**Issue by glyph** [Homebrew/homebrew#47914]
This information is available from `brew info` but if you're trying to consume it in a machine-readable way it's just "dependencies".

**Comment by johnzeringue** [comment]
I'd be interested in adding this, but being new to the project, it would be nice to have some guidance as to how we'd prefer to have this integrated. I'm not quite sure how you guys approach interface changes.

**Comment by mikemcquaid** [comment]
The prefered implementation would probably be to have separate lists of `recommended_dependencies` and `optional_dependencies` to avoid breaking the current interface. Look forward to your PR, @johnzeringue; don't worry about it being perfect, we'll help you get there!
