### ISSUE TITLE
luarocks and lua upgrade questions

### ISSUE THREAD

**Issue by telemachus** [Homebrew/homebrew#47926]
luarocks has just had [a major update to 2.3.0](http://lua-users.org/lists/lua-l/2016-01/msg00055.html), and now that luarocks is installed with lua, I'm wondering how to handle this.

1. Would a pull-request to upgrade only the luarocks part of the lua
   formula be of interest?
2. Or is the plan to only upgrade luarocks when the lua formula itself is
   updated.
3. Semi-related to that, I'm not quite sure why lua 5.2 is still the
   default version available in homebrew. I see an issue where [it was
   decided to put a new(ish) lua 5.3 in homebrew-versions](https://github.com/Homebrew/homebrew/issues/35787), but that was
   January of 2015. I don't think that 5.2 is being actively developed any
   longer. Its last upgrade was March of 2015.

(By the way, I originally sent this to the mail list, but I decided to post it here after realizing that the list seems pretty dead. Sorry for any extra noise though.)

**Comment by DomT4** [comment]
> Would a pull-request to upgrade only the luarocks part of the lua formula be of interest?

Yup. You can `revision` the `lua` formulae as well so people actually get it. We won't revision for every bump, but the major ones are a better idea than not.

> Or is the plan to only upgrade luarocks when the lua formula itself is updated.

Nope.

>  I'm not quite sure why lua 5.2 is still the default version available in homebrew

Because 5.3 is *horribly* incompatible with almost all of the software using Lua 5.2, even without going into the world of Luarocks generally being slow to update. Ref: https://github.com/Homebrew/homebrew/pull/47766

**Comment by daurnimator** [comment]
:+1: luarocks 2.3.0 comes with an important OSX change: https://github.com/keplerproject/luarocks/issues/422
This will finally fix my luarocks packages to work with brew without hacks!

**Comment by telemachus** [comment]
@daurnimator Good to know. Does that change how luarocks itself is installed?

In any case, I'll need to do some local testing, and then I'll submit a PR to upgrade the lua formula. At the very latest, I should have this done by next weekend, if not sooner.

**Comment by daurnimator** [comment]
> @daurnimator Good to know. Does that change how luarocks itself is installed?

Nope.
