### ISSUE TITLE
Error: Empty installation (when trying to upgrade)

### ISSUE THREAD

**Issue by Sturmkater** [Homebrew/homebrew#47929]
Hi, first thank you for this awesome package manager!!!! It makes OS X feels like home;-)
Today when upgrading I experienced an error. How can I fix it?

Thanks for help!

Output:
brew upgrade
==> Upgrading 9 outdated packages, with result:
caskroom/cask/brew-cask 0.60.0, curl 7.46.0, ffmpeg 2.8.4, gettext 0.19.7, openssl 1.0.2e, pkg-config 0.29, wget 1.17.1, x264 r2601, youtube-dl 2016.01.09
==> Upgrading caskroom/cask/brew-cask
==> Cloning https://github.com/caskroom/homebrew-cask.git
Updating /Library/Caches/Homebrew/brew-cask--git
==> Checking out tag v0.60.0
Error: Empty installation

**Comment by tsparber** [comment]
Homebrew-Cask will now be kept up to date together with Homebrew (see https://github.com/caskroom/homebrew-cask/pull/15381 for details).
run `brew uninstall --force brew-cask; brew update` to switch to the new system.

**Comment by Sturmkater** [comment]
Thanks!! Works like charm now.


Am 10.01.2016 um 23:30 schrieb Tommy Sparber <notifications@github.com>:

Homebrew-Cask will now be kept up to date together with Homebrew (see caskroom/homebrew-cask#15381 <https://github.com/caskroom/homebrew-cask/pull/15381> for details).
run brew uninstall --force brew-cask; brew update to switch to the new system.

**Comment by DomT4** [comment]
Working on making sure this doesn't happen to anyone else upstream with the Caskroom. Will close here though as you've resolved the issue locally.
