### ISSUE TITLE
failed to update macvim

### ISSUE THREAD

**Issue by dunn** [Homebrew/homebrew#47943]
_From @lly365 on January 11, 2016 2:0_

$ brew upgrade macvim
==> Upgrading 1 outdated package, with result:
macvim 7.4-89
==> Upgrading macvim
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-89.tar.gz
Already downloaded: /Library/Caches/Homebrew/macvim-7.4-89.tar.gz
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 -
Last 15 lines from /Users/ling/Library/Logs/Homebrew/macvim/01.configure:
--with-tlib=ncurses
--with-compiledby=Homebrew
--with-local-dir=/usr/local
--enable-cscope
--enable-pythoninterp
--with-developer-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer
--with-macsdk=10.11

configure: creating cache auto/config.cache
checking whether make sets $(MAKE)... yes
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/tmp/macvim20160111-15283-16my9fq/macvim-snapshot-89/src':
configure: error: C compiler cannot create executables
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
macvim: disable ruby integration on 10.6 https://github.com/Homebrew/homebrew/pull/40255
macvim fails to build on Yosemite 10.10 with _SC_PHYS_PAGES error https://github.com/Homebrew/homebrew/issues/47026
macvim failed to build on 10.6.8 https://github.com/Homebrew/homebrew/issues/38047

_Copied from original issue: Homebrew/homebrew-php#2769_

**Comment by dunn** [comment]
@lly365 
> READ THIS: https://git.io/brew-troubleshooting

Please do!

**Comment by DomT4** [comment]
I'm guessing either outdated Xcode/CLT or an Anaconda installation here.

**Comment by jameswilson** [comment]
Same problem for me as well:

https://gist.github.com/2e097e574d32413d0734

**Comment by DomT4** [comment]
@jameswilson Remove `MAMP` from your `$PATH` temporarily and try again. I suspect it's that.

**Comment by jameswilson** [comment]
@DomT4 Removing `MAMP` from the `$PATH` worked perfectly! Thanks for the tip. Would have never thought that some php packages would have interfered with building vim, but yes, the brew doctor knows best!

**Comment by DomT4** [comment]
Anything with a large amount of `*-config` executables tends to be fairly problematic, sadly. We explicitly warn about Anaconda because it's a frequent point of breakage but `MAMP` has been a far less frequent troublemaker to date.

**Comment by DomT4** [comment]
Let us know if we can help further here @lly365, Thanks!
