### ISSUE TITLE
install soft error

### ISSUE THREAD

**Issue by Lee10** [Homebrew/homebrew#47953]
brew cask install caffeine
Error: Cask 'caffeine' definition is invalid: Bad header line: parse failed

brew cask list
Error: Cask 'caffeine' definition is invalid: Bad header line: parse failed

brew cask install caffeine
Error: Cask 'caffeine' definition is invalid: Bad header line: parse failed

**Comment by mikemcquaid** [comment]
Please report this to https://github.com/caskroom/homebrew-cask, thanks!

**Comment by Lee10** [comment]
thanks！
