### ISSUE TITLE
bash-completion  compopt :command not found

### ISSUE THREAD

**Issue by CodeMaxx** [Homebrew/homebrew#47965]
I'm getting this error while using TAB autocomplete on bash.

Additionally when I tried `brew install bash` and `chsh -s /usr/local/bin/bash` I started getting this whenever the .bash_profile file got executed.
```bash
bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
-bash: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]
```

**Comment by bfontaine** [comment]
Did you try changing your login shell in your terminal emulator as mentioned in https://github.com/Homebrew/homebrew/issues/39014#issuecomment-96438971?

**Comment by bfontaine** [comment]
Do you have an error if you try `/usr/local/bin/bash -c 'declare -A'`?

**Comment by CodeMaxx** [comment]
I get
```bash
declare -A BASH_ALIASES='()'
declare -A BASH_CMDS='()'
```
on
`/usr/local/bin/bash -c 'declare -A'`

**Comment by bfontaine** [comment]
That’s the normal output. It means that if you used `/usr/local/bin/bash` you shouldn’t get that error, which itself means you’re *not* using `/usr/local/bin/bash` as your login shell :wink: 

Did you restart your shell after running `chsh -s /usr/local/bin/bash`?

**Comment by CodeMaxx** [comment]
@bfontaine  Thanxx! Changing it in the terminal emulator did work.

**Comment by bfontaine** [comment]
Great! :smile:
