### ISSUE TITLE
brew update fails on OSX 10.11.2 

### ISSUE THREAD

**Issue by infusion** [Homebrew/homebrew#47970]
Hi,

a few weeks ago `brew update` started to fail, after working perfectly for almost two years now. `brew upgrade` however works fine.

```
➜  local git:(master) ✗ pwd
/usr/local
➜  local git:(master) ✗ whoami
robert
➜  local git:(master) ✗ l Library/Formula/dfu-programmer.rb.incompleteMigration
--w----r--  1 robert  admin     0B 17 Okt  2014 Library/Formula/dfu-programmer.rb.incompleteMigration
```

This is the error I get:

```
➜  local git:(master) ✗ brew update --verbose
==> git symbolic-ref --short HEAD 2>/dev/null
master
==> git status --untracked-files=all --porcelain 2>/dev/null
?? Library/Formula/dfu-programmer.rb.incompleteMigration
Stashing uncommitted changes to /usr/local.
?? Library/Formula/dfu-programmer.rb.incompleteMigration
git -c user.email=brew-update@localhost -c user.name=brew update stash save --include-untracked
error: open("Library/Formula/dfu-programmer.rb.incompleteMigration"): Permission denied
fatal: Unable to process path Library/Formula/dfu-programmer.rb.incompleteMigration
Cannot save the untracked files
Error: Failure while executing: git -c user.email=brew-update@localhost -c user.name=brew\ update stash save --include-untracked
```

Is this a known error?

**Comment by UniqMartin** [comment]
The file `Library/Formula/dfu-programmer.rb.incompleteMigration` has somewhat strange file permissions so `brew update` fails to clean up your local copy of Homebrew before fetching the updates.

If you don't need this file, just delete it. Otherwise, move it to a different location (outside of the Homebrew installation). In both cases `brew update` should be fine afterwards.

**Comment by infusion** [comment]
Yep, I know, I fixed it with a simple chmod but I filed the ticket because you know maybe where in the brew codebase something like this could happen, because as you can see the file size is also 0b. And maybe it's not just this one when brew breaks the formula files.

**Comment by dunn** [comment]
My guess would be that file was created by Migration Assistant; did you move to a new Mac recently?

**Comment by UniqMartin** [comment]
Thanks for the report @infusion! I think this type of issue is rare enough that we don't need to implement a solution for it in `brew update`. Of course we'll reconsider should that happen more often.
