### ISSUE TITLE
brew doctor fails on 10.11.3

### ISSUE THREAD

**Issue by Trelle** [Homebrew/homebrew#47987]
error request:
"/usr/local/Library/Homebrew/os/mac/xcode.rb:131:in `provides_autotools?'
/usr/local/Library/Homebrew/diagnostic.rb:1046:in `check_for_autoconf'
/usr/local/Library/Homebrew/cmd/doctor.rb:34:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:27:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:27:in `doctor'
/usr/local/Library/brew.rb:143:in `<main>'"

**Comment by mistydemeo** [comment]
Can you provide the full output, please?

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by DomT4** [comment]
Please let us know if we can help further here, Thanks!
