### ISSUE TITLE
cryptopp bottle missing symbols for architecture x86_64

### ISSUE THREAD

**Issue by dreid93** [Homebrew/homebrew#47986]
When installing `cpp-ethereum` via : 

```
brew tap ethereum
brew install cpp-ethereum
```
CryptoPP is installed via bottle and installation for `cpp-ethereum` fails with : 

```
Undefined symbols for architecture x86_64:
  "CryptoPP::Rijndael::Dec::AdvancedProcessBlocks(unsigned char const*, unsigned char const*, unsigned char*, unsigned long, unsigned int) const", referenced from:
      vtable for CryptoPP::BlockCipherFinal<(CryptoPP::CipherDir)1, CryptoPP::Rijndael::Dec> in AES.cpp.o
  "non-virtual thunk to CryptoPP::Rijndael::Dec::AdvancedProcessBlocks(unsigned char const*, unsigned char const*, unsigned char*, unsigned long, unsigned int) const", referenced from:
      vtable for CryptoPP::BlockCipherFinal<(CryptoPP::CipherDir)1, CryptoPP::Rijndael::Dec> in AES.cpp.o
```
The current solution is : 

```
brew uninstall cpp-ethereum
brew cleanup
rm -rf $(brew --cache)/*
brew install --build-from-srouce cryptopp
brew install cpp-ethereum 
```
I would like to request that the cryptopp bottle be rebuilt to ensure that symbols for the x86_64 architecture are present. I am not sure that understand bottles fully, and if there is a way that I can take care of the required changes I would be more than happy too :)

**Comment by apjanke** [comment]
Discussing on the [upstream issue](https://github.com/ethereum/webthree-umbrella/issues/117).

Made a dummy PR #47988 so we can get a fresh bottle and logs from the build server. (Logs from the original build have aged out.)

**Comment by bobsummerwill** [comment]
Hey @tdsmith, @mistydemeo, @apjanke!

@programonauta notes the following error today.    Might something have been broken as a side-effect of our experiments?    Or maybe some NAT/DNS issue?    Any thoughts?

When i try to reinstall, I get $ brew reinstall -s cryptopp
==> Reinstalling cryptopp
==> Downloading https://downloads.sourceforge.net/project/cryptopp/cryptopp/5.6.3/cryptopp563.zip
==> Downloading from http://10.10.10.150/UserCheck/PortalMain?IID=E2770CA8-B66B-5585-52D7-2F65A635FFEC&origUrl=aHR0cDovL3VmcHIuZGwuc291cmNl
################################################################## 100.0%

Error: SHA256 mismatch
Expected: 9390670a14170dd0f48a6b6b06f74269ef4b056d4718a1a329f6f6069dc957c9
Actual: c618d120d309eb7a5e1efd84f08afc7496053b6ca889c36117346e500ba8c6b6
Archive: /Library/Caches/Homebrew/cryptopp-5.6.3.zip
To retry an incomplete download, remove the file above.

**Comment by bobsummerwill** [comment]
@programonauta notes ... I’ll try by my 4G, bypassing company network

**Comment by tdsmith** [comment]
Yeah, it looks like they're being redirected to a captive portal; this shouldn't be a Homebrew bug.

**Comment by bobsummerwill** [comment]
Nope.   Ignore these last few comments.   My bad.

**Comment by programonauta** [comment]
Hi All, finally I got access to sourceforge in my company, after security guys release the route on the firewall.
With @dreid93 solution, it worked fine.

**Comment by bobsummerwill** [comment]
Brilliant, thanks for the update, @programonauta.
We might as well close this ticket now, eh?

@apjanke said https://github.com/ethereum/webthree-umbrella/issues/117#issuecomment-170749938

but @tdsmith found that it's a known issue ... https://github.com/ethereum/webthree-umbrella/issues/117#issuecomment-170751759

.... so I don't think there is a solution here other than for us to build from source.   Which is OK.

**Comment by bobsummerwill** [comment]
Thanks, @tdsmith!

Any idea why cryptopp doesn't show in the list of updated formulas in this gist?

https://gist.github.com/bobsummerwill/fc6be5a005dde58acc61

And just to confirm, the idiomatic way to use this change is the following?

    brew update
    brew reinstall cryptopp

Is that right?   Thanks!

**Comment by tdsmith** [comment]
The version didn't change so it doesn't appear in the list of updated formulas. Yes, `reinstall` is required to pick this up; maybe we should have bumped the revision (any maintainers have an opinion?).

**Comment by apjanke** [comment]
Yeah, version and revision are the same, so it won't trigger an update for existing installations and you'll need to do that `brew reinstall` manually. 

@tdsmith Maybe this should actually include a `revision` bump, since we know previously-installed bottles are bad and should be automatically removed? (Normally any bottle-only-affecting changes take a revision to the `bottle` instead of the whole formula; dunno if we can do that here since we now have null bottles.)

**Comment by apjanke** [comment]
heheh, jinx. Yeah, I say bump the revision.

**Comment by tdsmith** [comment]
Bottle revisions never force upgrades, anyway.

**Comment by tdsmith** [comment]
Done in 69bedf2de9aa24fe3630942f9386f5dc4d65f627.

**Comment by bobsummerwill** [comment]
Thanks - even better!

**Comment by bobsummerwill** [comment]
FYI ... @caktux, @area.

So https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X updated and down to just one workaround now - https://github.com/ethereum/webthree-umbrella/wiki/QTBUG-50155-workaround.
