### ISSUE TITLE
brew update fail with fatal: bad revision 'HEAD'

### ISSUE THREAD

**Issue by PanXianyue** [Homebrew/homebrew#48022]
fatal: bad revision 'HEAD'
fatal: bad revision 'HEAD'
fatal: Needed a single revision
You do not have the initial commit yet
Error: Failure while executing: git -c user.email=brew-update@localhost -c user.name=brew\ update stash save --include-untracked --quiet

how can i solve it ?

**Comment by DomT4** [comment]
I'd probably try:
```bash
cd $(brew --prefix) && git fetch && git reset --hard origin/master
```
And then `brew update`.

Note if you have intentional local changes to your `brew` files (formulae or core) those files will be overwritten with what is the current master branch here when you execute the command.

**Comment by DomT4** [comment]
Please let us know if we can help further here, Thanks!

**Comment by PanXianyue** [comment]
I have already solved this problem that delete the directory of /usr/local, than reinstall.
Thanks for you answer!

**Comment by AZCoder2** [comment]
`cd $(brew --prefix) && git fetch && git reset --hard origin/master`

This did it for me. Thanks!
