### ISSUE TITLE
Set Caveats section to orange color

### ISSUE THREAD

**Issue by revolter** [Homebrew/homebrew#48023]
The Caveats sounds (for me, at least) like a warning, so I think that it should use an yellow or orange color.

**Comment by DomT4** [comment]
Colour doesn't tend to apply well broadly; different people have very different Terminal colour schemes. We tend to bold important text or mark it some other way, but we're not heavy colour users. Can you talk more about how you're missing the caveats, etc?

**Comment by revolter** [comment]
Well, sometimes, like other people, [I don't read anything](http://www.joelonsoftware.com/uibook/chapters/fog0000000062.html), except errors that are red, if I correctly recall. More so when `brew upgrade`ing, I don't see any red, so I guess that all went well, but maybe some package needs an `init` or something in order to work.

**Comment by chdiza** [comment]
IMO the caveats are already easily visible because of the indentation and markup.  They're staring one right in the face at the end of a build.

**Comment by bfontaine** [comment]
Wouldn’t that be too much given that some caveats can be [very long](https://github.com/Homebrew/homebrew/blob/1fd767b5becc66201d0763a6764e4ed64a948b9f/Library/Formula/geocouch.rb#L90-L139)?

**Comment by mikemcquaid** [comment]
I can't promise we'd include this but I'd review a PR and consider it.

**Comment by revolter** [comment]
I didn't mean the whole text, just the section's title named `Caveats`.

**Comment by DomT4** [comment]
Closing per Mike's comment. PRs are easier to review/discuss.
