### ISSUE TITLE
Node failed to install on 10.10.5

### ISSUE THREAD

**Issue by kenzierocks** [Homebrew/homebrew#48048]
I was upgrading my `node` install, but then this happened:
```
==> Finishing up
ln -s ../../Cellar/node/5.4.1/etc/bash_completion.d/npm npm
ln -s ../Cellar/node/5.4.1/bin/node node
ln -s ../Cellar/node/5.4.1/include/node node
ln -s ../../Cellar/node/5.4.1/share/doc/node node
ln -s ../../../Cellar/node/5.4.1/share/man/man1/node.1 node.1
ln -s ../Cellar/node/5.4.1/share/systemtap systemtap
ln -s ../../Cellar/node/5.4.1/lib/dtrace/node.d node.d
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall node`
```
(Full `--verbose` log at https://gist.github.com/kenzierocks/23bdbcd3e4c1667369d3)
`brew doctor`: https://gist.github.com/kenzierocks/eb9473ab1836a26fb390

`brew postinstall node` prints this:
```
Error: Permission denied - /usr/local/lib/node_modules/npm/AUTHORS
```
That file doesn't exist. I suspect I may have accidentally upgraded `npm` somehow and that is interfering with `brew`?

**Comment by DomT4** [comment]
I suspect at some point you `sudo`'d something. You can run:

```bash
sudo chown -R $(whoami):admin /usr/local/lib/node_modules/
```
To deal with it.

**Comment by kenzierocks** [comment]
Sweet, works great.
