### ISSUE TITLE
clisp failed to build on OS X 10.11.2

### ISSUE THREAD

**Issue by ipmonger** [Homebrew/homebrew#48049]
https://gist.github.com/44e3dbcd93b17c5abe82

**Comment by DomT4** [comment]
We built this recently without any problem so I'm not sure what the issue was here. Could you ensure you've `brew update`d, re-attempt the build and then open a new Issue if it still persists? Thanks! Apologies none of us saw this before, sometimes Issues get buried by a sudden onslaught :cry:.
