### ISSUE TITLE
sha256 mismatch for wine1.8 bottle on mavericks

### ISSUE THREAD

**Issue by gregpsycle** [Homebrew/homebrew#48067]
```
==> Downloading https://homebrew.bintray.com/bottles/wine-1.8.mavericks.bottle.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 2a48bfc22f9a90db8505ba5d6dcd572c8841f679e284a6b0a26b1ce9c52a0dab
Actual: 2a9d9788d6ef35a931ca86227e0b0df1d8f5bfa4daf140914843e2ab93310785
Archive: /Library/Caches/Homebrew/wine-1.8.mavericks.bottle.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.
[...]
```
Removing the file and retrying results in the same. The downloaded file appears to be complete - it untars and doesn't seem to be missing anything. Downloading the tar.gz via Chrome has the same (wrong) sha456sum. The source-build seems to work.

**Comment by bfontaine** [comment]
I can reproduce:
```
$ curl -sL 'https://homebrew.bintray.com/bottles/wine-1.8.mavericks.bottle.tar.gz'|shasum -a 256
2a9d9788d6ef35a931ca86227e0b0df1d8f5bfa4daf140914843e2ab93310785  -
```

**Comment by DomT4** [comment]
Same here. I've removed the Mavericks bottle temporarily. Will get CI to re-do them as soon as possible. The two newer OS X version bottles are fine.

**Comment by DomT4** [comment]
Should be resolved via https://github.com/Homebrew/homebrew/commit/0315495c123c3c29473658bf4a88a18698df869f.
