### ISSUE TITLE
wireshark 2.0.1 not runnable from Spotlight Search

### ISSUE THREAD

**Issue by rgoldberg** [Homebrew/homebrew#48072]
wireshark 2.0.1 is not runnable from Spotlight Search on OS X 10.11.2.

I tried `brew linkapps`, but that didn't help.

Am I supposed to manually create a symlink in either `/Applications` or `~/Applications` to `/usr/local/Cellar/wireshark/2.0.1/bin/wireshark`?

Or should homebrew automate this somehow?

**Comment by bfontaine** [comment]
See #28798.

**Comment by rgoldberg** [comment]
Thanks.
