### ISSUE TITLE
gcc6 build show incorrect dynamic libs

### ISSUE THREAD

**Issue by gaming-hacker** [Homebrew/homebrew#48080]
yoiu need to fix your install ENV as current install is to
**${HOMEBREW_PREFIX}/Cellar/gcc6/6-20160110_1/lib/gcc/6**

your libs report the following

**libgomp.1.dylib:
	 ${HOMEBREW_PREFIX}/opt/gcc6/lib/gcc/6/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	 ${HOMEBREW_PREFIX}/lib/gcc/6/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)**

**Comment by dunn** [comment]
This issue was moved to Homebrew/homebrew-versions#1116
