### ISSUE TITLE
undefined method `desc' for VirtManager:Class

### ISSUE THREAD

**Issue by bruennlein** [Homebrew/homebrew#48089]
Hi,

trying to run 

brew tap jeffreywildman/homebrew-virt-manager

this seems to be OK but 

brew install virt-manager virt-viewer

throws an error:
Error: undefined method `desc' for VirtManager:Class
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Taps/jeffreywildman/homebrew-virt-manager/virt-manager.rb:2:in `<class:VirtManager>'
/usr/local/Library/Taps/jeffreywildman/homebrew-virt-manager/virt-manager.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:198:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:42:in `install'
/usr/local/Library/brew.rb:136:in `<main>'

Tried this on a Mac OSX 10.10.5
Can I do something to make it work?

**Comment by bfontaine** [comment]
Please run `brew update` and try again.

**Comment by bruennlein** [comment]
That helped. Thank you very much.

**Comment by bfontaine** [comment]
Great!
