### ISSUE TITLE
Latest node build breaks npm updating

### ISSUE THREAD

**Issue by jonbjornn** [Homebrew/homebrew#48083]
Not sure 100% if this is the right place to report this, but I just updated homebrew and upgraded my ```node``` package.

After that, I ran ```npm -g update``` and I get the following error:

![npm-update-error](https://cloud.githubusercontent.com/assets/6331668/12337022/79538e64-babc-11e5-908c-f6ac2a1330bd.png)

Following that error  I cannot run any ```npm``` commands. Not even ```npm -v```. Other wise I get this error:

![npm-v-error](https://cloud.githubusercontent.com/assets/6331668/12337102/d4fbdd7a-babc-11e5-8e7f-a51e5c8b05f2.png)

The only fix is to reinstall node from homebrew, but then it breaks immediately again if I run ```npm -g update```. Any help would be greatly appreciated. Thanks!

**Comment by bfontaine** [comment]
I can reproduce.

**Comment by DomT4** [comment]
Presuming fixed via https://github.com/Homebrew/homebrew/commit/ab674d77ef73d2cb5576d7de342bcd38ec571a93.

**Comment by jonbjornn** [comment]
Yep, just tested and fix is working. Thanks
