### ISSUE TITLE
How to configure path to Anaconda python instead of system python (mac osx 10.10, boost-python.rb)

### ISSUE THREAD

**Issue by serimp** [Homebrew/homebrew#48093]
I am trying to build boost-python from the source. 

1. Anaconda python path precedes the system python, but somehow boost-python interacts with the system python. 
2. I am now trying to reconfigure the boost-python.rb so that I can link it to anaconda python instead, and then compile it. 

What would be the proper way to change the boost-python.rb?
I've tried manually encoding py_prefix, python, version, variables, but in this case, the following message appears and nothing is in the lib path:

------------
The Boost C++ Libraries were successfully built!
The following directory should be added to compiler include paths:
    /private/tmp/boost-python20160114-35025-1di66lw/boost_1_59_0
The following directory should be added to linker library paths:
    /private/tmp/boost-python20160114-35025-1di66lw/boost_1_59_0/stage-/Users/name/anaconda2/bin/python/lib
Warning: tried to install empty array to /usr/local/Cellar/boost-python/1.59.0/lib
----------

**Comment by tdsmith** [comment]
Hi! This shouldn't be necessary; Boost.Python built against system Python will work with any Python 2.7 interpreter. Are you having trouble with the bottled library?

**Comment by serimp** [comment]
I am actually trying to compile pycaffe with the boost-python. I was getting segmentation fault when trying to import pycaffe from python, and I was referring to this thread https://github.com/BVLC/caffe/issues/591, which diagnosed that the problem seemed to be the conflict between system python and anaconda python.

**Comment by tdsmith** [comment]
pycaffe may be doing something wrong but since ab7a3b472 on May 9 we are careful to build Boost.Python so that it will work with any other 2.7.x interpreter.

If you want to pastebin a stack trace from a crash, I can take a look at it, but I don't think this is likely to be a problem with a Homebrew component.

**Comment by tdsmith** [comment]
Please let us know if we can help with anything!
