### ISSUE TITLE
Rubocop uses now-removed cop `Style/TrailingComma`

### ISSUE THREAD

**Issue by rwhogg** [Homebrew/homebrew#48105]
As of rubocop [0.36](https://github.com/bbatsov/rubocop/releases/tag/v0.36.0), the cop `Style/TrailingComma` no longer exists.

Running `brew audit` or `brew style` on any formula (eg. `brew style maven`) after doing a `gem update` gives the following error message:

> Error: The `Style/TrailingComma` cop no longer exists. Please use `Style/TrailingCommaInLiteral`
> and/or `Style/TrailingCommaInArguments` instead.
> (configuration found in /home/bob/.linuxbrew/Library/.rubocop.yml)

(Note: you might notice from the above message that I'm using Linuxbrew rather than Mac-Homebrew. But I've confirmed by looking at your current .rubocop.yml file that it has the same issue, and believe this should be fixed here rather than at Linuxbrew).

**Comment by mikemcquaid** [comment]
> (Note: you might notice from the above message that I'm using Linuxbrew rather than Mac-Homebrew. But I've confirmed by looking at your current .rubocop.yml file that it has the same issue, and believe this should be fixed here rather than at Linuxbrew).

Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by rwhogg** [comment]
I'm happy to try and help fix this (I've gotten PR's to Homebrew merged before, so I know the general drill if not all the ins and outs). No guarantee that I'll be able to get to it right away though - I'm going to be pretty busy this weekend.

Do you think there will be any difficulty in migrating everyone to a new version of Rubocop? Because after such a PR is merged, I suspect that would be necessary.
