### ISSUE TITLE
Issue when using hombrew: "/usr/bin/otool: Bad CPU type in executable"

### ISSUE THREAD

**Issue by Howl3r** [Homebrew/homebrew#48104]
After not using home-brew for a while, I wanted to install port audio through brew. I was trying to set up [this git hub project](https://github.com/grobie/soundcloud2000?ref=producthunt) that introduces a different kind of soundcloud client.

When I try to run `brew install port audio`, I get this error:

> sh: /usr/bin/otool: Bad CPU type in executable
> Error: Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool

I googled around and found out that some issues occure in combination with Xcode on Mac, especially when you installed an older version of Xcode. [One post](http://unix.stackexchange.com/questions/157119/cant-use-hombrew-because-of-bad-cpu-type-one-executable) I found suggested that the problem occurs when you have very old files in your /bin/ folder. The author of the post had tried to install a very old version of Xcode and had files in his /bin/ folder that where dated to 2003. I also tried to install an older version of Xcode in the past and I too found files in my /bin/ folder that are dated to 2003, although I am using a Retina MacBook. 

The post suggested that these files interfere with homebrew because it expects a different kind of CPU. This is as far as my knowledge goes and I don't really understand how these files suddenly make homebrew think that I have a different CPU.

I tried to completely deinstall Xcode but the problem still arises. I have since installed the newest version of Xcode which I successfully deleted but I am not sure if I managed all things related to the old version of Xcode that I tried to install. Also the post didn't really explain how to fix the problem, I only understood that the problem is somehow related to these 2003 files.

I tried to delete the files that are dated back to 2003, but that didn't really fix the issue. When I try running something like `brew doctor`now I get:

> error: /Library/Developer/CommandLineTools/usr/bin/otool: can't open file: /usr/bin/install_name_tool > > (No such file or directory)
> Error: Failure while executing: /Library/Developer/CommandLineTools/usr/bin/otool -L > /usr/bin/install_name_tool

So I am basically just wondering now what I actually have to do with these files to fix the issue.

Thanks for any help!

**Comment by bfontaine** [comment]
Please run `brew update` then see if `brew doctor` finds any issue.

**Comment by Howl3r** [comment]
I ran `brew update` and then ran `brew doctor` and got this:

> Warning: A newer Command Line Tools release is available.
> Update them from Software Update in the App Store.
> Error: Failure while executing: /Library/Developer/CommandLineTools/usr/bin/otool -L > /usr/bin/install_name_tool

After that I tried to run `brew install port audio`again and I got the same error of 

> Error: Failure while executing: /Library/Developer/CommandLineTools/usr/bin/otool -L > /usr/bin/install_name_tool


I guess the update for the new Command Line Tools is necessary? I wasn't able to update them yet due to a slow internet connection.

**Comment by mikemcquaid** [comment]
@Howl3r Yes, it's necessary.

**Comment by Howl3r** [comment]
@mikemcquaid Thanks for the info. But even after updating up the Command Line Tools I still get this error whenever I run `brew doctor` or try to install something with homebrew:

> Error: Failure while executing: /Library/Developer/CommandLineTools/usr/bin/otool -L > > /usr/bin/install_name_tool

**Comment by mistydemeo** [comment]
The `/usr/bin/install_name_tool` is actually a shim which comes with the OS itself; it's not part of the CLT, unfortunately. You'll need to reinstall the OS, or restore that one file from the OS installer.

**Comment by Howl3r** [comment]
Oh man, that's unfortunate. Thanks for the info though!

**Comment by mikemcquaid** [comment]
@Howl3r Any news on this?

**Comment by Howl3r** [comment]
@mikemcquaid No sorry, I haven't reinstalled the OS yet. I am not comfortable doing it at the moment. Will definitely report back though, once I've done it.

**Comment by mikemcquaid** [comment]
@Howl3r No worries! Closing this out for now but feel free to reopen if your issue persists post-reinstall.

**Comment by abbygriffiths** [comment]
Oh man... I too have this problem. Guess I'll forget about Homebrew then.

**Comment by ilovezfs** [comment]
@abbygriffiths What makes you think you "have this problem"? If you're actually looking for help addressing it, I'm sure it's solvable.

**Comment by abbygriffiths** [comment]
Nevermind. Solved it after digging around for hours. Downloaded the El Capitan official installer from the MAS, and then mounted the EDP Installer from inside it. (From Terminal, cannot be done from Finder). Then ran the Essentials.pkg installer from inside the mounted drive. Waited for 15 minutes. Bingo. Everything working. I had messed up the system by installing a very old version of Xcode that set my /usr/bin files to files from 2003! El Capitan Installer helped save the day. Sorry for the previous hate, Homebrew, you're a life saver to manage dependencies.

**Comment by ilovezfs** [comment]
> Sorry for the previous hate, Homebrew, you're a life saver to manage dependencies.

No problem. This stuff can get pretty frustrating sometimes, I know.

Thanks for sharing your solution. @Howl3r Maybe you can apply that to your situation too!
