### ISSUE TITLE
Python 2.7.11 causes problems with Django

### ISSUE THREAD

**Issue by sjuranic** [Homebrew/homebrew#48128]
The upgrade from 2.7.10_2 to 2.7.11 caused my Django application to fail. The apache logs show that the underlying `_io.so` has an udefined symbol in the object file. Specifically, it is looking for a definition of `__PyCodecInfo_GetIncrementalDecoder`. This symbol is left undefined in `.../Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so`, but it doesn't appear at all in `.../Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so`.

Strangely, I can't duplicate the error from my user account. The errors only occur when the code is being executed by mod_wsgi.

The apache logs giving the details of the error are attached.

[python-errors.txt](https://github.com/Homebrew/homebrew/files/92224/python-errors.txt)

**Comment by mikemcquaid** [comment]
CC @tdsmith for thoughts.

**Comment by tdsmith** [comment]
My first reaction is that this seems pretty mysterious. Do you know how mod_wsgi chooses which Python it uses to execute your code?

**Comment by tdsmith** [comment]
excerpt of the log, as gist: https://gist.github.com/17243926493bb94bedc2

**Comment by tdsmith** [comment]
This symbol is present in 2.7.11 but not 2.7.10, so somehow system and Homebrew python are getting mixed up at runtime:

```
$ nm /usr/local/opt/python/Frameworks/Python.framework/Python | grep _GetIncrementalDecoder
00000000000993b0 T __PyCodecInfo_GetIncrementalDecoder
$ nm /System/Library/Frameworks/Python.framework/Python | grep _GetIncrementalDecoder
$
```

**Comment by sjuranic** [comment]
`mod_wsgi` chooses the Python runtime based on the value of `WSGIPythonHome` (and the related `WSGIPythonPath`) defined in the Apache config files.

I'm not sure that confusing Homebrew Python and system Python is what's going on. If you'll notice in my original post, the problematic symbol isn't defined in Homebrew Python 2.7.10_2 (which is what I'm currently running with no issues).

    juranichs-mac (~)$ cd /usr/local/Cellar/python
    juranichs-mac (python)$ nm 2.7.10_2/Frameworks/Python.framework/Python | fgrep _GetIncrementalDecoder
    juranichs-mac (python)$ nm 2.7.11/Frameworks/Python.framework/Python | fgrep _GetIncrementalDecoder
    0000000000095451 T __PyCodecInfo_GetIncrementalDecoder

It looks to me that there is a problem with a mismatch between the included header files and the libraries. Since the output of `otool` for both versions of `lib-dynload/_io.so` match, perhaps there is an errant `#include` directive somewhere that is being brought in either by the upstream source or a build configuration option?

**Comment by sjuranic** [comment]
Sorry, I didn't mean to close the issue. I hit the wrong button.

**Comment by tdsmith** [comment]
I don't see why the otool output would be diagnostic. Wrt the nm output, we're making the same point about which versions of Python define that symbol. It's not defined in the _io.so bundle but it is defined in code that's linked into the framework binary; if a Python process has a mismatched framework binary and _io.so, you'll see this error.

I don't believe that this is an issue with Homebrew's distribution of Python; it may be an issue with software which attempts to compile against it. The fact that this doesn't reproduce at the console implies to me that mod_wsgi is invoking Python in a strange way.

**Comment by sjuranic** [comment]
That's a good point. One thing I didn't do (now that I think about it) was rebuild `mod_wsgi`. Normally this wasn't a step that I needed to take when upgrading the Homebrew Python. But I'll do that and see if that resolves the issue. I'll update the thread when I've completed that.

**Comment by sjuranic** [comment]
I reinstalled mod_wsgi by performing the following:

    $ brew uninstall -vd mod_wsgi
    $ brew install -vd mod_wsgi --with-homebrew-python

Now things seem to be working as expected. Sorry for the trouble. Glad it works now.

Thanks.
