### ISSUE TITLE
Mysql Build Needs Boost 1.59 but Used 1.60

### ISSUE THREAD

**Issue by dendisuhubdy** [Homebrew/homebrew#48130]
This CMake script will look for boost in <directory>.  If it is not there,
  it will download and unpack it (in that directory) for you.

  If you are inside a firewall, you may need to use an http proxy:

  export http_proxy=http://example.com:80

Call Stack (most recent call first):
  cmake/boost.cmake:259 (COULD_NOT_FIND_BOOST)
  CMakeLists.txt:435 (INCLUDE)

-- Configuring incomplete, errors occurred!
See also "/tmp/mysql20160115-59485-hkqcnh/mysql-5.7.10/CMakeFiles/CMakeOutput.log".

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
mysql: vendor Boost for build https://github.com/Homebrew/homebrew/pull/48117
Add mysql option to libgda https://github.com/Homebrew/homebrew/pull/47807
MySQL server has gone away https://github.com/Homebrew/homebrew/issues/47335
mysql doesn't build: mysql 5.7.10 requires boost 1.59, boost was updated to 1.60. https://github.com/Homebrew/homebrew/issues/48082
Latest Homebrew release can't install ruby and mysql https://github.com/Homebrew/homebrew/issues/47546
mysql-connector-c++ cannot build with mariadb  https://github.com/Homebrew/homebrew/issues/34578
percona-toolkit does not depend on MySQL https://github.com/Homebrew/homebrew/pull/41595
MySQL not woking with --datadir option https://github.com/Homebrew/homebrew/issues/41160
mysql 5.7.9 on Mac OS X 10.11.1 https://github.com/Homebrew/homebrew/issues/46035
no memcached support in most recent MySQL brew port https://github.com/Homebrew/homebrew/issues/42935
Packages with --with-mysql option not satisfied by mariadb https://github.com/Homebrew/homebrew/issues/32973

**Comment by DomT4** [comment]
Track #48117 please. Will be resolved after that is merged, which will hopefully be late tonight.

**Comment by DomT4** [comment]
Should be fixed via https://github.com/Homebrew/homebrew/commit/faef69a4167870f994b48d750dad410094f86b85. Please `brew update` and try again. Feel free to shout if you hit any further issues, Thanks for reporting this!
