### ISSUE TITLE
Brew "digest" (feature request)

### ISSUE THREAD

**Issue by joewestcott** [Homebrew/homebrew#48136]
Could this keyword print out a list of the changes between installed versions and available update versions?
something like:

    $ brew digest
    "packagename x.x1 is installed, version x.x3 is available with these changes"
    (packagenames' changelog between the versions above)

I imagine this would be a lot of work since the data would need to be fetched for every release.

**Comment by dunn** [comment]
Yeah, I don't think this is feasible, since not every project has a changelog, and some have some in unusual places, or with unusual formatting.

**Comment by DomT4** [comment]
Yeah. We've shut similar ideas down before because of how incredibly time-consuming it would be to achieve and the potential for increasing the burden on contributors and maintainers.

There's also the problem that some Changelogs are like:

```
* Version 1.0.2
  * Renamed x_function x2_function (API Break)
  * Added OpenSSL  support.
  * Build with SecureTransport on OS X by default.

**Comment by DomT4** [comment]
Yeah. We've shut similar ideas down before because of how incredibly time-consuming it would be to achieve and the potential for increasing the burden on contributors and maintainers.

There's also the problem that some Changelogs are like:

```
* Version 1.0.2
  * Renamed x_function x2_function (API Break)
  * Added OpenSSL 1.1.0 support.
  * Build with SecureTransport on OS X by default.
```
And others are like:
```
* Version 1.0.2
  * Renamed x_function to x2_function (API Break)
  * Renamed internal operator which is only used privately to xyz
  * Other obscure detail most users won't care about or perhaps understand
  * Dave renamed the README to README.txt
```
Some Changelogs are summaries, some are everything, and it's hard to know consistently when to cut that off.

**Comment by bfontaine** [comment]
You can always run `brew outdated`:
```
$ brew outdated
youtube-dl (2016.01.14 < 2016.01.15)
```

**Comment by dunn** [comment]
And to check what's been changed, your best bet is probably then `brew home youtube-dl`.

Closing, but thanks anyway!
