### ISSUE TITLE
upgrading package "Lua" wipes installed Lua modules

### ISSUE THREAD

**Issue by darkstalker** [Homebrew/homebrew#48134]
Every time Lua gets updated, the entire content of `/usr/local/share/lua` gets wiped. That's the place where modules are installed by luarocks, so you lose all your installed modules on each update. Other install places seems to be preserved, because when you do `luarocks list` it will display what you had installed, but the source files aren't there.
I suspect this is because that directory is symlinked inside `/usr/local/Cellar`, and on upgrade it just deletes the whole contents of it instead of properly removing files one by one based on a manifest or something like that.

**Comment by mikemcquaid** [comment]
CC @DomT4 for Lua thoughts/pain :grinning:

**Comment by DomT4** [comment]
Welp. I'll take a look, er, at some point today. Have a busy day planned, but I'll find the time somewhere heh.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew/pull/48242

**Comment by DomT4** [comment]
Should be fixed after a `brew update && brew upgrade`.

**Comment by darkstalker** [comment]
I reinstalled everything (lua-5.2.4_3) and it still symlinks `/usr/local/share/lua -> ../Cellar/lua/5.2.4_3/share/lua`, it doesn't look right. That shouldn't be part of the package, but just an empty dir created on installation.
Also don't know why it ships Luarocks alongside Lua, they should be separate packages. That's probably why it triggers a symlink creationg for that path.

**Comment by DomT4** [comment]
I checked this locally before the PR and it was working as expected. The contents of the versioned directories in share/lua/* are symlinks but the directories themselves are permanent and persist across removal, including future luarock module installations.

Please search through the prior Lua/Luarock discussions as to why thy were merged, as I can't really tl;dr the history from my phone and I won't be online till much later today.

It creates a symlink previously because our logic instructs it to.

**Comment by darkstalker** [comment]
yea but the contents of share/lua shouldn't be versioned or managed by a system package manager. I hope they don't just dissapear on a minor version upgrade because the symlink changed

**Comment by DomT4** [comment]
It's _not_ a symlink now:
```
~> ls -l /usr/local/share | grep lua
Jan 19 13:07 lua
Nov 10 19:02 luajit-2.0.4 -> ../Cellar/luajit/2.0.4_1/share/luajit-2.0.4

~> ls -l /usr/local/share/lua
Jan 19 13:07 5.1
Jan 19 12:59 5.2
Jan 19 13:07 5.3
```

That setup persists right through to the luarocks directory inside the versioned paths there, and at that point the contents are symlinks. If you do something like `luarocks install moonscript` you'll find the folder retained at:
```bash
$(brew --prefix)/share/lua/5.2/moonscript
```
Which isn't removed even if you `brew rm lua`.

**Comment by darkstalker** [comment]
I think i found the problem. If you don't have a share/lua dir previously created, it will symlink it inside the Cellar. If you manually mkdir it before installing/linking, then it will work properly and only link the luarocks files. 
The install script should detect that and manually mkdir the missing share/lua to prevent this from happening.

**Comment by dunn** [comment]
@darkstalker Feel free to open a PR! https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions.
