### ISSUE TITLE
The ZNC formula is missing support for Python, Perl, TCL and Curysauth module

### ISSUE THREAD

**Issue by Mikaela** [Homebrew/homebrew#48147]
```
Optional Features:
  --disable-option-checking  ignore unrecognized --enable/--with options
  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
  --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
  --disable-largefile     omit support for large files
  --enable-debug          enable debugging
  --disable-ipv6          disable ipv6 support
  --disable-openssl       disable openssl
  --disable-zlib          disable zlib
  --enable-perl           enable perl
  --enable-python[=python3]
                          enable python. By default python3.pc of pkg-config
                          is used, but you can use another name, for example
                          python-3.1
  --enable-swig           Enable automatic generation of source files needed
                          for modperl/modpython. This value is ignored if perl
                          and python are disabled. Usually no need to enable
                          it.
  --enable-cyrus          enable cyrus
  --disable-optimization  Disable some compiler optimizations to decrease
                          memory usage while compiling
  --disable-tdns          disable threads usage for DNS resolving
  --enable-run-from-source
                          ZNC will be runnable without installation
  --disable-poll          use select() instead of poll()
  --disable-charset       disable ICU support
  --enable-tcl            enable modtcl
```

Perl and TCL aren't so useful and I am not sure if Curys can be used on OS X at all, but there are many popular Python modules that cannot be used with Homebrew.

Another thing to note is that in ZNC 1.7.0 icu4c starts being required if compiled with Python support as Python doesn't like charsets other than UTF-8.

* http://wiki.znc.in/Modpython
* http://wiki.znc.in/Modperl
* http://wiki.znc.in/Modtcl
* http://wiki.znc.in/Cyrusauth

**Comment by mikemcquaid** [comment]
We don't provide support for all options intentionally. If you can get them to work we'd review a pull request to add some more that you personally want to use. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
