### ISSUE TITLE
Python 3 old homebrew installations don't cleanup /usr/local/python3.* directories

### ISSUE THREAD

**Issue by tzickel** [Homebrew/homebrew#48161]
I've just noticed that I have lots of /usr/local/python3.*/site-packages directories that contain pip3 install stuff I've done via homebrew's python 3 installations.

Running brew cleanup does not clean up this leftovers while of course I do not have python 3.2, 3.3, 3.4 installed anymore (just 3.5).

**Comment by tdsmith** [comment]
This is by design, since Homebrew didn't install those files. You can remove them manually if you no longer want them. Thanks for reaching out & please let us know if we can help with anything else.

**Comment by tzickel** [comment]
@tdsmith A few issues with this:
1. homebrew python install does put there some of the files (the sitecustomize/pip/setuptools).
2. I did not see any documentation (in installation / uninstallation / the homebrew python FAQ[1]) that says that this files will remain after removing the package (via cleanup).
3. You can try adding to brew doctor a check to see if there are dirs like this without the python packages installed, maybe it should notify about this.

[1] https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-and-Python.md
