### ISSUE TITLE
Can't install pyqt

### ISSUE THREAD

**Issue by aleksey925** [Homebrew/homebrew#48184]
trace
> brew install pyqt -with-python3
==> Downloading https://downloads.sf.net/project/pyqt/PyQt4/PyQt-4.11.4/PyQt-mac
Already downloaded: /Library/Caches/Homebrew/pyqt-4.11.4.tar.gz
==> Entering interactive mode
Type `exit' to return and finalize the installation
Install to this prefix: /usr/local/Cellar/pyqt/4.11.4
bash-3.2$ exit
exit
Error: Empty installation

**Comment by UniqMartin** [comment]
There's a missing dash in your option, causing it to be interpreted completely differently. Unfortunately, we cannot yet diagnose this type of problem and print a warning/error.

Your installation should succeed if you try again with `brew install pyqt --with-python3`.
