### ISSUE TITLE
update-bash issues

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew#48193]
As @xu-cheng reported it prints a bunch of error messages if you `^C` it:
```shellSession
$ brew update-bash
^Cfatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

fatal: Could not read from remote repository.
...snip...
```

---

You also get a bunch of error messages (one per tap I guess) if you’re not connected to the Internet:
```shellSession
$ brew update-bash
ssh: Could not resolve hostname github.com: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
...snip...
fatal: unable to access 'https://github.com/caskroom/homebrew-cask/': Could not resolve host: github.com
ssh: Could not resolve hostname github.com: nodename nor servname provided, or not known
fatal: Could not read from remote repository.
...snip...

**Comment by mikemcquaid** [comment]
@bfontaine @xu-cheng I'm not sure how best to address either of these; thoughts?

**Comment by bfontaine** [comment]
I’m not sure either right now :confused:

**Comment by DomT4** [comment]
> You also get a bunch of error messages (one per tap I guess) if you’re not connected to the Internet:

Could possibly do something super simple like:
```bash
ping -c 2 8.8.8.8 &> /dev/null || echo "Update cannot be run offline!"; exit 1
```

The chance of `8.8.8.8` ever being down is about as close to zero as you can get.

**Comment by bfontaine** [comment]
@DomT4 Good idea; we might want to `ping`/`curl` `github.com` instead since that what we’ll use to update. We might also want to use a message more generic like “`Cannot connect to {github.com,Internet}`”.

**Comment by DomT4** [comment]
@bfontaine I was thinking about that but Github is consistently twice as slow to respond to a header request as Debian is. We're talking 0.3 and 0.6 seconds where the connection is available, so not _huge_ numbers, so we may not care.

**Comment by DomT4** [comment]
Filed a PR for review. Easier to discuss real ideas which can be pulled/tested than theoretical ideas, etc.
