### ISSUE TITLE
Error: undefined method `<' for nil:NilClass

### ISSUE THREAD

**Issue by ddelapaz** [Homebrew/homebrew#48208]
I'm on `10.11.2`

I  first ran `sudo chown -R $(whoami) /usr/local` then `brew update` twice.

Got the error after attempting to run `brew doctor`
```
Error: undefined method `<' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/os/mac/xcode.rb:131:in `provides_autotools?'
/usr/local/Library/Homebrew/diagnostic.rb:1047:in `check_for_autoconf'
/usr/local/Library/Homebrew/cmd/doctor.rb:34:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:27:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:27:in `doctor'
/usr/local/Library/brew.rb:88:in `<main>'
```

Here's gist which includes the brew update list and then the error above.
https://gist.github.com/ddelapaz/a4260114101a5e5da204

**Comment by bfontaine** [comment]
What does `brew config` say?

**Comment by ddelapaz** [comment]
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: b5e1f41e4fd6020d2fc1454ef3e144b6559f7e30
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.11.2-x86_64
Xcode: N/A
CLT: N/A
Clang: N/A
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.7.0_79```

**Comment by UniqMartin** [comment]
Thanks for the report, @ddelapaz! It seems the `brew doctor` check that causes the error for you isn't prepared to handle the situation that neither the CLT (Command Line Tools) nor Xcode is installed.

If that's an option for you, you can work around the issue by installing either of them. Or you can wait for us to fix this problem. (It shouldn't take us very long to resolve this.)

**Comment by ddelapaz** [comment]
Ah ok, that makes sense. I had xcode previously and just recently removed it.  Thanks @UniqMartin!

**Comment by TA1DB** [comment]
Hi, I have got the same error message after removing both Xcode and CLT with macports and reinstalling home-brew and CLT again. I do not want to install Xcode so i wait you to fix it. Thank you for your efforts.

**Comment by DomT4** [comment]
It seems `MacOS::Xcode.provides_autotools?` calls `MacOS.clang_version.to_f` which in turn calls:

```ruby
`clang --version`[/(?:clang|LLVM) version (\d\.\d)/, 1]
```
Which makes `xcrun` vomit where there's no CLT/Xcode installed to check.

It also vomits if you do something like install Xcode, set your active developer directory to `/Applications/Xcode.app` and then remove `Xcode.app` and execute the check again.

An immediate fix could be to wrap the specific `doctor` check in:
```ruby
return unless MacOS.has_apple_developer_tools?
```
**And** a check to ensure that wherever `active_developer_dir` points at _actually exists_.

```ruby
return unless MacOS.has_apple_developer_tools?
return unless Pathname.new(MacOS.active_developer_dir).exist?
return unless MacOS::Xcode.provides_autotools?
```
Should work.

**Comment by DomT4** [comment]
(It's also possible we should be more careful about checking `active_developer_dir` exists in the first place when it is defined, rather than when called externally).

**Comment by UniqMartin** [comment]
@DomT4 I think the `doctor` check that causes the issue should be prefixed with:

```ruby
return unless MacOS::Xcode.installed?
```

(Whether or not the CLT are installed doesn't matter, because no CLT version provided `autotools`.)

> (It's also possible we should be more careful about checking active_developer_dir exists in the first place when it is defined, rather than when called externally).

If that's not already the case (I'm a bit surprised), I agree.

@DomT4 Do you want to tackle this issue and the one where `active_developer_dir` should be more careful about what it returns (if it doesn't exist)?

**Comment by DomT4** [comment]
> return unless MacOS::Xcode.installed?

This seems reasonable to me.

@UniqMartin I'm gone for most of the rest of the day, so if you want to jump over me and fix it I'm happy for you to do so. I mostly poked around this morning because I was curious :wink:

**Comment by UniqMartin** [comment]
@ddelapaz @TA1DB Please run `brew update`. The bug should be fixed after that, but I'd be happy to hear a confirmation from you this is actually the case.

**Comment by TA1DB** [comment]
Hi @UniqMartin Before you issue the update I resolved my problem in an other way by un-installing re-installing something therefore I am not in a position to confirm whether the update solves the reported issue or not but I can say that I am using homebrew with pleasure, uninstalled the heavy macports and Xcode. Thank you very much.

**Comment by ddelapaz** [comment]
@UniqMartin I went ahead and did `brew update` twice followed by `brew doctor` but got the following.

`Error: Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool`

```
╰─$ brew config                                        1 ↵
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 846f89160b8d31b26713d51b51c0ea35b6a771ff
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.11.2-x86_64
Xcode: N/A
CLT: N/A
Clang: N/A
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.7.0_79
```
