### ISSUE TITLE
`brew fetch -s` is broken

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew#48224]
We can’t download from source anymore.

@nijikon reported it here: https://github.com/Homebrew/homebrew/commit/5dd200c6b40f4fa9cc3a70cbc9ca2885e4626943#commitcomment-15510462

I can reproduce:
```
$ brew fetch -s git
==> Downloading https://homebrew.bintray.com/bottles/git-2.7.0.el_capitan.bottle.tar.gz
######################################################################## 100,0%
Downloaded to: /Library/Caches/Homebrew/git-2.7.0.el_capitan.bottle.tar.gz
SHA1: b2ff35192f5f4487b1b11af5f4c22a06b97b7be6
SHA256: 8324cd419fbdee3d11d555dfddb69c985c48b0d08a134543154f2d9546b6bd15
```

cc @mikemcquaid

**Comment by mikemcquaid** [comment]
Reverted in 846f89160b8d31b26713d51b51c0ea35b6a771ff. Thanks for reverting @xu-cheng; I thought I did this but forgot to push.

**Comment by xu-cheng** [comment]
Sorry Mike, but you seems to point to the wrong commit as I didn't revert anything related to this issue.

**Comment by mikemcquaid** [comment]
Sorry, I reverted in 56644484104e9d60f0d1120dba9b1dc170d31ab3. Thanks @xu-cheng.
