### ISSUE TITLE
Tap with Formulae in a subdirectory

### ISSUE THREAD

**Issue by hgiesel** [Homebrew/homebrew#48237]
When I create my own _Homebrew Tap_, is it possible to put the formulae, e.g. `foo.rb` into a subdirectory instead of the root directory?

**Comment by hgiesel** [comment]
You have to create a `Formula` subdirectory. In this directory, you can put all your `.rb` files.
For an example, look at [homebrew/tex](https://github.com/Homebrew/homebrew-tex).

**Comment by DomT4** [comment]
Yup! You got it. They can be in the top-directory or nested under a `Formula` subdir.
