### ISSUE TITLE
pyfa failed to build on 11.2

### ISSUE THREAD

**Issue by thorr18** [Homebrew/homebrew#48249]
I run the following commands: 
> brew tap thorr18/formulae
> brew install pyfa

The install fails and ends with result: 

> error: option --single-version-externally-managed not recognized

I've put the debugging info here: https://gist.github.com/a78a4c953a8dfea85154

I don't understand what causes this error. 
This is a new formula I've attempted to author and am running for the first time.

**Comment by thorr18** [comment]
I updated Brew, the formula, and the gist logs; so I've updated everything above info to match.

**Comment by tdsmith** [comment]
setup.py does not use distutils for its configuration so you can't use the Homebrew helper method to run it; try invoking the setup.py directly (for the same reason, this package cannot be installed with pip).

**Comment by thorr18** [comment]
Oh, I think I see what you mean. I see that the Pyfa setup.py has a sister file 'setup-osx.py' that does include setuptools. Maybe I'll try combining them or calling one from the other. 
Maybe brew audit should notice my misuse of `Python.setup_install_args` or the method itself could, but with your help I think I can close this now.

**Comment by tdsmith** [comment]
Okay; feel free to ping me if I can help with something. (It's pretty unusual that a package doesn't import setup from either distutils or setuptools in its main setup.py.)
