### ISSUE TITLE
intellij-idea-ce formula?

### ISSUE THREAD

**Issue by jamesongithub** [Homebrew/homebrew#48257]
not sure if this is the place to ask.

was wondering what happened to the intellij idea community edition formula?

```
$ brew cask search intellij
==> Partial matches
intellij-idea
```

This one seems to be the ultimate edition. Used to be both `intellij-idea` and `intellij-idea-ce` I think.

**Comment by bfontaine** [comment]
This is a question for the `cask` tap :wink: 
https://github.com/caskroom/homebrew-cask
