### ISSUE TITLE
Screwed up install...

### ISSUE THREAD

**Issue by rafegoldberg** [Homebrew/homebrew#48254]
...because I'm a noob/I don't think clearly in the AM! Anyway, I can't for the life of me figure out how to fix it; if anyone has any thoughts it'd be much appreciated! Anyway, to detail the problem: I wasn't sure I had `brew` installed on my laptop so just to be sure I was working from a clean environment I ran:

```
$ sudo ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
Warning: This script will remove:
/list/of/files.paths
...
Are you sure you want to uninstall Homebrew? [y/N] y
==> Removing Homebrew installation...
==> Removing empty directories...
==> Homebrew uninstalled!
The following possible Homebrew files were not deleted:
/usr/local/bin/
/usr/local/etc/
/usr/local/foreman/
/usr/local/heroku/
/usr/local/include/
/usr/local/lib/
/usr/local/n/
/usr/local/share/
/usr/local/topicdesk/
/usr/local/var/
You may consider to remove them by yourself.
You may want to restore /usr/local's original permissions
  sudo chmod 0755 /usr/local
  sudo chgrp wheel /usr/local
```

I didn't want to remove Heroku or any other important files so I left the above suggested files for deletion alone. But I _did_ update my permissions per the last two suggestions. So after I ran those `chmod` and `chgrp` commands I ran the default install command right of the Homebrew site, but much to my chagrin it threw an error:

```
$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
/Users/rafe/.rbenv/shims/ruby: line 21: /usr/local/Cellar/rbenv/1.0.0/libexec/rbenv: No such file or directory
```

If it's any help in diagnosing the issue, I installed following [this guide](https://gorails.com/setup/osx/10.11-el-capitan). Anyway, now that I'm a bit more awake I absolutely remember installing `brew` and then `rbenv` so this is a really **dumb** mistake on my part but I'd greatly appreciate any suggestions! Thanks.

**Comment by bfontaine** [comment]
Maybe try running it with `/usr/bin/ruby` instead of `ruby` to ensure it uses the system one instead of `rbenv`’s?

**Comment by rafegoldberg** [comment]
@bfontaine you, my friend, are a genius of the first order. ran with system ruby per your instruction and it worked like a charm! very much appreciated.
