### ISSUE TITLE
error: command 'clang' failed with exit status 1 on OS X 10.11.2 (15C50)

### ISSUE THREAD

**Issue by anandth** [Homebrew/homebrew#48255]
bash-3.2$ brew install pgmagick
==> Installing pgmagick from hhatto/pgmagick
==> Installing dependencies for hhatto/pgmagick/pgmagick: sqlite, boost, graphicsmagick
==> Installing hhatto/pgmagick/pgmagick dependency: sqlite
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.10.1.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring sqlite-3.10.1.el_capitan.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides an older sqlite3.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/sqlite/lib
    CPPFLAGS: -I/usr/local/opt/sqlite/include

==> Summary
🍺  /usr/local/Cellar/sqlite/3.10.1: 9 files, 2.8M
==> Installing hhatto/pgmagick/pgmagick dependency: boost
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/boost-1.60.0.tar.bz2
==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost/1.60.0 --libdir=/usr/local/Cellar/boost/1.60.0/lib --without-icu --without-libraries=python,mpi
==> ./b2 headers
==> ./b2 --prefix=/usr/local/Cellar/boost/1.60.0 --libdir=/usr/local/Cellar/boost/1.60.0/lib -d2 -j4 --layout=tagged --user-config=user-config.jam ins
🍺  /usr/local/Cellar/boost/1.60.0: 11,139 files, 436.3M, built in 91 minutes 20 seconds
==> Installing hhatto/pgmagick/pgmagick dependency: graphicsmagick
==> Downloading https://downloads.sourceforge.net/project/graphicsmagick/graphicsmagick/1.3.23/GraphicsMagick-1.3.23.tar.bz2
Already downloaded: /Library/Caches/Homebrew/graphicsmagick-1.3.23.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/graphicsmagick/1.3.23_1 --enable-shared --disable-static --with-modules --disable-openmp --with-quantum-dep
==> make install
🍺  /usr/local/Cellar/graphicsmagick/1.3.23_1: 471 files, 11.8M, built in 1 minute 42 seconds
==> Installing hhatto/pgmagick/pgmagick
==> Downloading https://github.com/hhatto/pgmagick/archive/ver0.6.tar.gz
Already downloaded: /Library/Caches/Homebrew/pgmagick-0.6.tar.gz
==> python setup.py install --prefix=/usr/local
Last 15 lines from /Users/anandakumarthangaraju/Library/Logs/Homebrew/pgmagick/01.python:
                            ^
/usr/local/include/boost/python/def_visitor.hpp:67:29: note: in instantiation of function template specialization 'boost::python::def_visitor_access::visit<boost::python::def_visitor<boost::python::init<const void *, unsigned long, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_> >, boost::python::class_<Magick::Blob, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> >' requested here
        def_visitor_access::visit(*this, c);
                            ^
/usr/local/include/boost/python/class.hpp:225:17: note: in instantiation of function template specialization 'boost::python::def_visitor<boost::python::init<const void *, unsigned long, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_> >::visit<boost::python::class_<Magick::Blob, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> >' requested here
        visitor.visit(*this);
                ^
./src/_Blob.cpp:27:10: note: in instantiation of function template specialization 'boost::python::class_<Magick::Blob, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>::def<boost::python::init<const void *, unsigned long, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_, mpl_::void_> >' requested here
        .def(init< const void*, size_t >())
         ^
/usr/local/include/boost/python/converter/registered.hpp:83:3: note: candidate template ignored: could not match 'type-parameter-0-0 &' against 'void'
  registry_lookup2(T&(*)())
  ^
1 error generated.
error: command 'clang' failed with exit status 1

**Comment by mistydemeo** [comment]
Please read the [troubleshooting guide](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting) and post all the diagnostics listed there. Thanks!

**Comment by DomT4** [comment]
It _looks_ like this is a Boost incompatibility, which won't have been tested prior to the recent Boost update being merged because the failing formula is from an unofficial tap.

**Comment by anandth** [comment]
apologies...
[brewconfig.txt](https://github.com/Homebrew/homebrew/files/101828/brewconfig.txt)

**Comment by anandth** [comment]
Dear team,  any other file is needed, please.

**Comment by DomT4** [comment]
This has been reported to the upstream tap as a Boost error in https://github.com/hhatto/pgmagick/issues/4, so they'll need to fix it I'm afraid. Nothing we can do on our side. Sorry!

**Comment by tguo-aa** [comment]
I encountered the same issue here. Is there a workaround here currently?

**Comment by anandth** [comment]
Hi,

As such of now, there is no solution. I thought of submitting this in the
Boost site, however, it seems they aren't delivering any patches as such.
Need to take this to them.

Regards,
-Anand.
