### ISSUE TITLE
update-bash interacts badly with ssh-agent

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew#48267]
If ssh-agent isn't running and public-key authentication is required to connect to tap remotes, `update-bash` ends up generating _n_ ssh-agent prompts for _n_ taps. Answering the first prompt does not dismiss the rest, and the rest of the connections fail unless the password is entered for each.

One workaround could be updating a single tap first, and then proceeding to update the rest in parallel after the first one completes.

This is probably an issue only maintainers will see.

**Comment by UniqMartin** [comment]
An easier approach might be to fall back to a serial update, if any of the repositories has a non-standard `origin` remote, i.e. one that doesn't use HTTPS. Not sure if that's discriminating SSH users too much, but I assume the vast majority of our users fetches via HTTPS.

**Comment by mikemcquaid** [comment]
@tdsmith Can you see if you can still reproduce this? I think @xu-cheng thought this might be resolved now.
