### ISSUE TITLE
brew postinstall python warning in my formula

### ISSUE THREAD

**Issue by dbogdanov** [Homebrew/homebrew#48287]
I need [my formula](https://github.com/MTG/homebrew-essentia/blob/master/essentia.rb#L19) to install python with framework to be able to use pip. However, it fails with a warning: 
```
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall python`
```

How to avoid that?

**Comment by tdsmith** [comment]
`=> "framework"` is the default/a no-op; we don't support a flat python installation.

Why is post-install failing? `brew postinstall -v python` or `brew gist-logs python` should be useful.

**Comment by dbogdanov** [comment]
Thanks!
