### ISSUE TITLE
The following error when I installing php7.

### ISSUE THREAD

**Issue by wangwyoo** [Homebrew/homebrew#48288]
==> Installing php70 from homebrew/php
==> Downloading https://php.net/get/php-7.0.2.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php70-7.0.2
==> ./configure --prefix=/usr/local/Cellar/php70/7.0.2 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/7.0 --with-config-file-path=/usr/local/etc/php/7.0 --with-config-file-scan-dir=/usr/lo
Last 15 lines from /Users/wangwyoo/Library/Logs/Homebrew/php70/01.configure:
checking for OpenSSL support... yes
checking for Kerberos support... /usr
checking whether to use system default cipher list instead of hardcoded value... no
checking for krb5-config... /usr/bin/krb5-config
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.8
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find lib

and i install zlib....
brew install zlib .... done
then,it still  say error

**Comment by tdsmith** [comment]
This issue was moved to Homebrew/homebrew-php#2801
