### ISSUE TITLE
Formula version badges

### ISSUE THREAD

**Issue by zbeekman** [Homebrew/homebrew#48299]
I know there are shields.io badges out there for package managers, like PYPI, and I thought it would be cool if there was one for Homebrew, that people could put into their Github README.md.

Does anyone know of such a badge generator? Does anyone know how to programmatically grab the latest release of a package and insert it into a custom shields.io badge?

**Comment by tdsmith** [comment]
To grab the latest release of a package from a Homebrew install, you can query the JSON metadata, like `brew info --json=v1 wxmac | jq -r '.[0].versions.stable'`. We don't run a REST API for that, but someone might. I'm not aware of any badge generators that do this.

**Comment by zbeekman** [comment]
I'm wondering if Braumeister.org might be the correct service to provide a badge or enable badging. See:

https://github.com/koraktor/braumeister.org/issues/35
