### ISSUE TITLE
Homebrew no longer brews

### ISSUE THREAD

**Issue by vchan1186** [Homebrew/homebrew#48291]
When I perform any brew commands (e.g., brew doctor, brew update, etc), I get the following error:
------------------------
/usr/local/Library/Homebrew/config.rb:34:in `initialize': no implicit conversion of nil into String (TypeError)
	from /usr/local/Library/Homebrew/config.rb:34:in `new'
	from /usr/local/Library/Homebrew/config.rb:34:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:18:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:10:in `<main>'
-----------------------
A text file of the config.rb file is attached.
[config_rb.txt](https://github.com/Homebrew/homebrew/files/97897/config_rb.txt)

**Comment by bfontaine** [comment]
What does `cd /usr/local && git status` say?

**Comment by vchan1186** [comment]
The git status in /usr/local is attached.
[git_status.txt](https://github.com/Homebrew/homebrew/files/98107/git_status.txt)

**Comment by bfontaine** [comment]
Did you intend to modify your Homebrew repository? If you not or if you don’t know please run the following:

```sh
cd /usr/local
git fetch
git reset --hard origin/master
```

Then try again to run e.g. `brew update`.

**Comment by vchan1186** [comment]
When I execute git reset --hard origin/master after git fetch, I get the follow error:

vicchan@dhcp173:/usr/local$ git reset --hard origin/master
error: unable to unlink old 'bin/brew' (Permission denied)
error: unable to unlink old 'share/man/man1/brew.1' (Permission denied)
Checking out files: 100% (2752/2752), done.
fatal: Could not reset index file to revision 'origin/master'.

**Comment by bfontaine** [comment]
Please run `sudo chown -R $(whoami):admin /usr/local` and try again.

**Comment by vchan1186** [comment]
Thank you! What you suggested has fixed the problem.

**Comment by bfontaine** [comment]
Great!

**Comment by u2mejc** [comment]
:+1: This worked for me as well, file perms had changed to root:wheel on /usr/local/bin and /usr/local/share (not manually set to my knowledge) and brew ate itself when trying to brew update. Was working before that I believe.

```
$ brew update
error: unable to unlink old 'bin/brew' (Permission denied)
error: unable to unlink old 'share/man/man1/brew.1' (Permission denied)
Error: Failure while executing: git pull --ff --no-rebase --quiet origin refs/heads/master:refs/remotes/origin/master
```

**Comment by landau** [comment]
+1
