### ISSUE TITLE
Cant re-install homebrew

### ISSUE THREAD

**Issue by MilesWilliams** [Homebrew/homebrew#48311]
I had previously installed Homebrew, however I was having issues with it so i decided to remove it and start a fresh install. Problem I am having now is, when I enter ' ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" ' into my terminal, nothing happens, It just goes to a new fresh line waiting for another command.

However when I try to use a brew command, I get command not found.

**Comment by UniqMartin** [comment]
What version of OS X are you using? Can you check whether you are able to access the install script with your web browser? (The link to it is in your comment above.)

**Comment by MilesWilliams** [comment]
I'm currently on el Captian version 10.11.2 - yea the link takes me to the script on my browser no problem

**Comment by UniqMartin** [comment]
Can you try just `curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install` in your terminal and see what happens? It should print the Ruby code that you see when visiting that URL in your browser to the terminal. Also what does `which curl` return? It should be `/usr/bin/curl` if it's the one that's coming with the system.

**Comment by MilesWilliams** [comment]
The script does print in my terminal and which curl does return /usr/bin/curl

**Comment by bfontaine** [comment]
What does `which ruby` say?

**Comment by MilesWilliams** [comment]
which ruby returns  ' /usr/local/bin/ruby '

**Comment by bfontaine** [comment]
Just to be sure could you try to run the line with `/usr/bin/ruby` instead of `ruby`?

**Comment by MilesWilliams** [comment]
It also returns /usr/bin/ruby

**Comment by UniqMartin** [comment]
What @bfontaine meant was: Try `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`.

**Comment by MilesWilliams** [comment]
Ah my bad  - hey it actually worked  : ), started to install

**Comment by MilesWilliams** [comment]
Thanks  @UniqMartin and @bfontaine for the help, much appreciated

**Comment by UniqMartin** [comment]
Glad to hear that worked! You might want to investigate where that `/usr/local/bin/ruby` came from and why it doesn't do anything. Anyway, closing as resolved.
