### ISSUE TITLE
depends_on "pkg-config" -> :test

### ISSUE THREAD

**Issue by scpeters** [Homebrew/homebrew#48315]
I would like to be able to use `pkg-config` inside a `test` block to aid in compiling example code. Currently `pkg-config` is declared as a `:build` dependency, but will not be installed if the formula is poured from a bottle.

Is there a way to declare dependencies for test blocks that would be installed as-needed when tests are run (and maybe uninstalled afterwards)?

**Comment by bfontaine** [comment]
> Is there a way to declare dependencies for test blocks that would be installed as-needed when tests are run (and maybe uninstalled afterwards)?

No, you need to use runtime dependencies for that.

**Comment by scpeters** [comment]
Thanks for the quick response!

Would this be a worthwhile feature to add? I guess `pkg-config` is pretty lightweight, so there's not much harm in just adding it as a runtime dependency to my formulae.

I'll close this for now, but people can comment here if they think it would be a useful feature.
