### ISSUE TITLE
htop version is very outdated

### ISSUE THREAD

**Issue by ryanwinchester** [Homebrew/homebrew#48327]
The htop version here: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/htop-osx.rb

Is very outdated according to author @hishamhm, re: hishamhm/htop#259

**Comment by mistydemeo** [comment]
The htop in use is a fork called `htop-osx`, rather than the official htop. It's only within the last few months that the official htop works on OS X; we're just waiting for a new release of the official htop to switch to using it.

**Comment by hishamhm** [comment]
@mistydemeo is correct — the new release is coming soon and I'll be sure to let you know :)
