### ISSUE TITLE
Improperly permissioned /usr/local will cause `brew install ghc cabal-install` to infinite loop

### ISSUE THREAD

**Issue by katzenbaer** [Homebrew/homebrew#48347]
If the `/usr/local` directory has improper permissions from an OS X update, then running `brew install ghc cabal-install` will cause an infinite loop. As a user, I would expect the install to fail so that I can further diagnose the issue. I discovered that it was a permission issue only after trying to run `brew update`.

**Comment by slucero** [comment]
Suggested solution: Run `brew doctor` to check your system for issues. In my case it quickly discovered the mentioned permissions issue and provided commands to fix it.

**Comment by mikemcquaid** [comment]
This seems like it's a `ghc` rather than Homebrew bug. I'm not sure what the fix here is?

**Comment by DomT4** [comment]
Not sure what we can do here, that we're not already doing, but please feel free to shout if we can assist further in some way. Thanks!
