### ISSUE TITLE
Make new mailing list public

### ISSUE THREAD

**Issue by telemachus** [Homebrew/homebrew#48365]
As far as I can tell, it's not currently possible to view the archives for the new Google Groups mail list unless you're logged into Google. However, [Google's documentation here](https://support.google.com/groups/answer/46438?hl=en) suggests that it is possible to do this, if a group mail list is public.

Can Homebrew's group be made public? Thanks.

**Comment by DomT4** [comment]
I'm not entirely sure how to do this personally, so have assigned Tim as he set up the list and may know more :stuck_out_tongue_winking_eye:.

**Comment by telemachus** [comment]
@DomT4 Thanks.

**Comment by luzpaz** [comment]
saw it here: https://twitter.com/MacHomebrew/status/690228997326659585

**Comment by tdsmith** [comment]
Hey, thanks for the report. I'm like 90% sure I already flipped this switch; what makes you think this isn't configured?

**Comment by tdsmith** [comment]
It looks right to me if I look at it in incognito mode but maybe I'm missing something.

**Comment by telemachus** [comment]
@tdsmith When I visited earlier, I was prompted to sign into Google. I just tried in incognito mode, and it worked. Maybe I had a cooke/cache issue earlier, not sure. Sorry for the noise: I'll close this. Thanks.

**Comment by mikemcquaid** [comment]
@tdsmith Mind giving all the maintainers admin rights (and inviting them)? Thanks!

**Comment by tdsmith** [comment]
I believe this is done now.
