### ISSUE TITLE
openssl upgrade error

### ISSUE THREAD

**Issue by vol7ron** [Homebrew/homebrew#48383]
openssl seems to be a dependency for many scripts (ruby, curl, etc).  I have no `brew doctor` issues and `brew update` shows everything up to date.

    $HOME/.linuxbrew/opt/curl/bin/curl: symbol lookup error: \
       $HOME/.linuxbrew/lib/libcurl.so.4: undefined symbol: SSL_CTX_set_alpn_protos

I have download issues for that and 2 of the mirrors.

**Comment by dunn** [comment]
This issue was moved to Linuxbrew/linuxbrew#737
