### ISSUE TITLE
<php with pthreads> failed build on 10.11.2

### ISSUE THREAD

**Issue by Frozen-Shadow** [Homebrew/homebrew#48392]
Hello !
Once I was used php with none threads safe.Now I need php with threads safe.
So,I use ``` brew install php56 --with-thread-safety``` 
Then  MySQL will report some error:
```
configure: error: Cannot find libmysqlclient_r under /usr/local.
Note that the MySQL client library is not bundled anymore!
```
I found ```libmysqlclient_r.dylib```  in ```/usr/local/lib/```,I don't know why MySQL will scanning this directory.When I reinstall php with out thread safe ,everything is ok  !!

So,I want reinstall them(redis php mysql ...),after ```brew uninstall php-xxx``` and ```brew install php-xxx```
php report some warning like this: 
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-redis/redis.so' - dlopen(/usr/local/opt/php56-redis/redis.so, 9): image not found in Unknown on line 0
```
I fund all the config file in ```/usr/local/etc/php``` *were didn't remove* after ```brew uninstall```

I don't know whether you keep it for some reason or not.

My english is so poor ,I wish you can understand what I mean.Sorry to bother you.

Best Wishes!

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-php#2810

**Comment by DomT4** [comment]
The `php` formulae come from another official tap with its own set of maintainers, so I've moved this issue over there where they'll be able to help you further :)

**Comment by Frozen-Shadow** [comment]
Thank you! :)
