### ISSUE TITLE
ldc build failing with "out of memory" on CI and local builds

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#48432]
The current `ldc` formula is now failing to build on the CI and test-bot boxes, giving an "out of memory" error.

This showed up in the tests for #48086, which was an (I think) unrelated version bump for just the `devel` part of the formula.

I can reproduce the "out of memory" error on my 4 GB OS X 10.9.5 VM using the current `ldc` formula. Build logs: https://gist.github.com/00e5c0359a6f547eabf9

I'm breaking this out in to a separate issue bc it's not caused by that PR.

And here's a dummy PR with a bogus revision bump to the current formula, used to reproduce the build failure:  #48431.

**Comment by apjanke** [comment]
Doing a single-job `HOMEBREW_MAKE_JOBS=1 brew install -v -s` on my local machine doesn't fix it; it still fails with out-of-memory.

**Comment by apjanke** [comment]
"Out of memory" and segmentation faults on my 16 GB 10.9.5 box, too. (And I don't know how much swap they're configured to use, anyway.) Logs here: https://gist.github.com/fb93bda547e5cc66cc7b. Doesn't look like it's just a resource limitation; something else is going on.

**Comment by John-Colvin** [comment]
see https://github.com/ldc-developers/ldc/issues/1250 and new commit on https://github.com/Homebrew/homebrew/pull/48086

**Comment by DomT4** [comment]
I think this is safe to close with https://github.com/Homebrew/homebrew/commit/f867a42f93f05a9bf2e3c7de48f7b1a2256a4eca but I'll leave it to you since it's your issue @apjanke.

**Comment by apjanke** [comment]
Yup, fixed it. Thanks!.
