### ISSUE TITLE
brew install boost deployment target version too high [Mac OS X]

### ISSUE THREAD

**Issue by elanhickler** [Homebrew/homebrew#48437]
Problem: I am on Mac OS X 10.11 using Xcode 7.1 with a deployment target of 10.7 so my program will run on Mac OS X 10.7 and up. When I use the boost cpp files in Xcode it of course builds and works fine. If I use boost via the static libraries given by brew, my program seems to only work on Mac 10.11.

Posted this on stackoverflow, didn't get any promising responses: http://stackoverflow.com/questions/34227795/building-boost-cpp-via-xcode-works-via-brew-caused-incompatibility

What deployment target does brew/boost use? How do you know? It seems that brew is giving me boost static libraries that require Mac 10.11 to work as if brew has boost built with a deployment target of Mac 10.11.

**Comment by mikemcquaid** [comment]
Homebrew builds targeting the version of OS X it's built on. If this behaviour does not work for you you'll probably need to build from source outside Homebrew. Sorry!

**Comment by elanhickler** [comment]
Is this behavior documented?

**Comment by mikemcquaid** [comment]
@elanhickler Indirectly in that we don't claim otherwise and claim that Homebrew is optimised for your system.
