### ISSUE TITLE
private formulas

### ISSUE THREAD

**Issue by javajax** [Homebrew/homebrew#48453]
I am trying to use homebrew to install projects that are private.
This requires installing git repositories with authentication.

Is there a way to specify a git URL and have it use the SSH key or other auth methods while downloading the repo?

**Comment by dunn** [comment]
Most `https` git URLs take a user/password:
```ruby
  url "https://username:password@hostname/repo.git", :tag => "0.1.1"
```
Would that work for your purposes?

**Comment by javajax** [comment]
I think since we require 2 factor in our org we would need ssh.
I am testing now.

**Comment by javajax** [comment]
yeah looks like that does not work.
Is there a way to get homebrew to use your ssh config

**Comment by mikemcquaid** [comment]
> I think since we require 2 factor in our org we would need ssh.

@javajax You can use 2FA with HTTPS but just supply a personal/oauth access token as the password rather than the password or 2FA code .

**Comment by javajax** [comment]
Since I want this to be used by other people I couldn't make the username and password work.

I was able to add `using: :git` to the url method and it seems to pick up my ssh configs and download the repo correctly.

I am going to close this as I think I have solved the issue.
Thanks :)

**Comment by rikkipitt** [comment]
@javajax I'm creating an internal build tool using a private repo on Bitbucket. Your comment got me pointed in the right direction for installing my formula correctly. Cheers!

**Comment by javajax** [comment]
@rikkipitt That is awesome I have been finding home-brew is an amazing platform for distributing internal tools.
