### ISSUE TITLE
update-bash says "Already up-to-date" twice even when I have no taps.

### ISSUE THREAD

**Issue by chdiza** [Homebrew/homebrew#48469]
`brew update-bash` on an up to date repo will show:
```
Already up-to-date
Already up-to-date
```
even though I have no taps tapped.

It's true that I have `$HOMEBREW_VERBOSE` set in my `~/.profile`, but I've always had it thus, and this is the first I've seen of double notices.  So `update-bash` is doing something that `update.rb` is not.

**Comment by chdiza** [comment]
Thanks!

**Comment by mikemcquaid** [comment]
@chdiza My pleasure, thanks for the report. As a long-time Homebrew user: any other thoughts about this updater?

**Comment by chdiza** [comment]
I haven't really been keeping up with the bash updater or why it's there.  Presumably it's for speed relative to ruby.  It does seem to produce "Already up-to-date" more quickly than before, so that's good.

**Comment by bfontaine** [comment]
@chdiza It’s faster and avoids a few issues we had in the past (e.g. #42553) due to the updater code sometimes running with both old and new (updated) code. Using Bash instead of Ruby avoids this.
