### ISSUE TITLE
Sonar should depend on Java

### ISSUE THREAD

**Issue by rwhogg** [Homebrew/homebrew#48468]
The Sonar formula doesn't depend on Java, but it probably should. It includes numerous JAR files and launches a JVM as part of its launcher script.

**Comment by rwhogg** [comment]
Note: I discovered this while investigating https://github.com/Linuxbrew/linuxbrew/issues/750, but it applies to OS X too.

**Comment by mikemcquaid** [comment]
@rwhogg Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
