### ISSUE TITLE
installing protobuf python bindings fails

### ISSUE THREAD

**Issue by jonEbird** [Homebrew/homebrew#48473]
Probably more of an issue with protobuf but affects my ability to install mosh. Here is the final error I see:
    
    ==> python -c import setuptools... --no-user-cfg install --prefix=/opt/homebrew/Cellar/protobuf/2.6.1/libexec --single-version-externally-managed --record=i
    Last 15 lines from /Users/jonmiller/Library/Logs/Homebrew/protobuf/09.python:
      File "/opt/homebrew/lib/python2.7/site-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/opt/homebrew/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2370, in load
        return self.resolve()
      File "/opt/homebrew/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2376, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "google/__init__.py", line 1, in <module>
        __import__('pkg_resources').declare_namespace(__name__)
      File "/opt/homebrew/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2226, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/opt/homebrew/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2195, in _handle_ns
        path.sort(key=sort_key)
      File "/opt/homebrew/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2193, in sort_key
        return sys_path.index(_normalize_cached(os.sep.join(parts)))
    ValueError: '/private/tmp/protobuf20160125-33942-3o94fe/protobuf-2.6.1/python' is not in list

You may notice that I had previously installed `python` via homebrew so I'd have my own version outside of the default version that comes with OSX. Since I'm rather new to homebrew I'm not sure if this is a typical cause of issues or perhaps that I'm using `/opt/homebrew` as the prefix.

Full gist-log: https://gist.github.com/anonymous/05d9d07272156c9d2811

**Comment by mikemcquaid** [comment]
CC @tdsmith for Python thoughts, I'm a bit lost.

**Comment by jonEbird** [comment]
As I mentioned I'm new to homebrew and I've discovered I can perform a `cask` install but then its not using my normal prefix. Guessing this is not really helping to address the root issue but useful for a work around:

    brew cask install mosh

**Comment by tdsmith** [comment]
Can I ask what the output of this is: `/usr/bin/python -c 'import sys; import setuptools; print(sys.path); print(setuptools.__version__)'`

**Comment by jonEbird** [comment]
Since I have two Pythons installed, the default OSX version which you're asking about, and the homebrew installed version, I'll provide two answers:

    $ /usr/bin/python -c 'import sys, pprint; import setuptools; pprint.pprint(sys.path); print(setuptools.__version__)'
    ['',
     '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',
     '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
     '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
     '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
     '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
     '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python',
     '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
     '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',
     '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',
     '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC',
     '/Library/Python/2.7/site-packages']
    1.1.6

And here is the same information from the homebrew Python which I thought `brew` was using since I've prepended `/opt/homebrew/bin` to my `PATH`:

    $ /opt/homebrew/bin/python -c 'import sys, pprint; import setuptools; pprint.pprint(sys.path); print(setuptools.__version__)'
    ['',
     '/opt/homebrew/lib/python2.7/site-packages/Cheetah-2.4.4-py2.7-macosx-10.11-x86_64.egg',
     '/opt/homebrew/lib/python2.7/site-packages/PasteScript-2.0.2-py2.7.egg',
     '/opt/homebrew/lib/python2.7/site-packages/Paste-2.0.2-py2.7.egg',
     '/opt/homebrew/lib/python2.7/site-packages/Markdown-2.6.5-py2.7.egg',
     '/opt/homebrew/lib/python2.7/site-packages/six-1.10.0-py2.7.egg',
     '/opt/homebrew/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg',
     '/opt/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',
     '/opt/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
     '/opt/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
     '/opt/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
     '/opt/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
     '/opt/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
     '/opt/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',
     '/opt/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',
     '/opt/homebrew/lib/python2.7/site-packages',
     '/Library/Python/2.7/site-packages']
    19.6

**Comment by UniqMartin** [comment]
I can confirm the observation. `protobuf` also fails to build for me with the exact same error. If I reinstall `python`<sup>(1)</sup> after reverting 849922d9242f506672bc756939a9fd77eaed77df and then try installing `protobuf` again, everything is fine, so I suspect some change in either `pip` or `setuptools` is responsible for the breakage.

<sup>(1)</sup>I guess there's a more elegant way to downgrade `pip` and/or `setuptools`, but I don't know how.

**Comment by tdsmith** [comment]
I couldn't repro until I upgraded setuptools in /usr/local; we're using system Python but we're injecting the /usr/local site-packages into sys.path. I'll bundle a private setuptools with protobuf for now and then file an issue against setuptools.

**Comment by tdsmith** [comment]
caught @jaraco on IRC (thanks!); setuptools regression was introduced in 19.4 by this commit: https://bitbucket.org/pypa/setuptools/commits/32e6b7067dff8543ad07af33999b88007db97c47; other manifestations are being tracked here: https://bitbucket.org/pypa/setuptools/issues/485/differences-setuptools-193-and-194-loading, https://bitbucket.org/pypa/setuptools/issues/491/setuptools-194-breaks-pip-install-builds
