### ISSUE TITLE
yle-dl 2.9.0: missing dependency PHP mcrypt

### ISSUE THREAD

**Issue by joneskoo** [Homebrew/homebrew#48489]
As far as I can tell, yle-dl formula is not usable unless PHP mcrypt extension is installed.

```
$ yle-dl http://areena.yle.fi/1-3065619
yle-dl 2.9.0: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2015 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3
Output file: Yle Uutiset-2016-01-24T09:55:00+02:00.flv

                            KSV Adobe HDS Downloader

You have to install and enable the following extension(s) to continue: 'mcrypt'
Failed to import youtube_dl
```

The error message is not obvious, but AdobeHDS is a PHP implementation called by yle-dl and it depends on PHP mcrypt being available, which is not the case on my OS X 10.11. I installed yle-dl from bottle and PHP is OS X built-in, not from brew. My homebrew is 720cdef19ab3ee7f5c89ebebe7c95f0247d74d45

```
$ brew doctor
Your system is ready to brew.
```
There should at minimum be a caveat in yle-dl Formula with info how to install PHP mcrypt extension. I have no idea how to install PHP extensions.

**Comment by javian** [comment]
The installation instructions on 
`https://github.com/aajanki/yle-dl`
tells you how to install mcrypt with homebrew. The formula should probably be updated with that dependency in it since it doesn't work without it.

**Comment by bfontaine** [comment]
If you’d like to modify the formula file to fix it we’d greatly appreciate it! :smile: 
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

**Comment by javian** [comment]
I could do it but I was wondering about the dependency to make it work. The doc states that it uses php55-mcrypt so doing

`depends_on "homebrew/php/php55-mcrypt"`

would solve that but if someone is using php56 or php70 that also has an mcrypt module it would be unnecessary to install the 5.5 one and it should use the one that's already on the system. Alternatively you could make them all optional. The other way would be to check if they are installed and if none of the modules are found install the 5.5 one. Do you have any alternative ideas ?

**Comment by javian** [comment]
Made an attempt to add the dependency.
