### ISSUE TITLE
Error: Failed to update tap: neovim/neovim

### ISSUE THREAD

**Issue by noscripter** [Homebrew/homebrew#48480]
rt

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by noscripter** [comment]
@mikemcquaid  thank you very much, I'll follow your link document's instruction and check out the result.

**Comment by noscripter** [comment]
hi @mikemcquaid  I followed the troubleshooting page to resolve all warnings generated by `brew doctor` and ran `brew update` twice, but the problem still remains, I'm wondering what's the cause of this problem? BTW, below is my `brew config` output:

```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 720cdef19ab3ee7f5c89ebebe7c95f0247d74d45
Last commit: 11 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.11.3-x86_64
Xcode: 7.2
CLT: 7.2.0.0.1.1447826929
Clang: 7.0 build 700
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/leo/.rvm/rubies/ruby-2.1.2/bin/ruby
Java: 1.8.0_05
```

**Comment by mikemcquaid** [comment]
@noscripter Please provide us with all the output we request. Also, to help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by noscripter** [comment]
Thank man, let me explain my self with your given steps.


I'm running this alias to automatically update brew:

```
brew update && brew outdated && brew cleanup && brew upgrade --all
```

I expect all the upgrade to go on smoothly without errors, but I always get this Error in the output:

```
Error: Failed to update tap: neovim/neovim
```

So I am wondering what's the cause of this specific error?  Below is the output of the command `brew doctor`:

```
Your system is ready to brew.
```

**Comment by noscripter** [comment]
And here is the result if I run `brew upgrade neovim --verbose`

![image](https://cloud.githubusercontent.com/assets/1673877/12741818/d889d494-c9ba-11e5-9f48-3975dec9fc6e.png)

**Comment by mikemcquaid** [comment]
As described in https://github.com/neovim/homebrew-neovim/blob/master/README.md#troubleshooting:
`brew untap neovim/neovim; brew tap neovim/neovim`

That's expected with `brew upgrade` too; we don't support upgrading `HEAD` packages.

**Comment by noscripter** [comment]
Bravo! @mikemcquaid  that's exactly the solution to my problem.
