### ISSUE TITLE
Update qca and qjson bottles for El Capitan

### ISSUE THREAD

**Issue by jkarneges** [Homebrew/homebrew#48498]
I noticed these packages haven't been updated since the release of El Capitan, so there are no bottles yet. Installing with brew builds them from source which works fine. Can bottle builds be triggered for them?

Thanks!

**Comment by UniqMartin** [comment]
Thanks for notifying us, @jkarneges! I triggered and then merged the builds for both formulae, thus bottles should be available after a `brew update`.
