### ISSUE TITLE
nspr formula uses incorrect configure flag to build with pthreads

### ISSUE THREAD

**Issue by rwhogg** [Homebrew/homebrew#48505]
The nspr formula uses the configure flag "--enable-pthreads". This flag does not actually exist, and running `brew install -vd nspr` will tell you such.

There are two candidates for what the intended flag was:

* --with-pthreads (Use system pthreads library as thread subsystem)
* --enable-user-pthreads (Build using userland pthreads)

I'm busy fixing the Linuxbrew build for nspr at the moment, but I might have time to look into this further in the next few days.

**Comment by apjanke** [comment]
PR to fix this: #48656
