### ISSUE TITLE
macvim failed to build on 10.9.5

### ISSUE THREAD

**Issue by dphenderson** [Homebrew/homebrew#48531]
I think the problem may actually be in macvim. Posting here first since it's failing to build thru homebrew. Link to gist-logs: https://gist.github.com/anonymous/40d132ef9cce5ef08c80

**Comment by beepscore** [comment]
I have been getting a very similar error on 10.11.3
https://gist.github.com/47ffa642c160eb747dbc
Also in Xcode gui Preferences DerivedData a long time ago I set custom "~/xcode-build".
Today in gui I changed back to default, build fails either way but seems to keep using original custom path.
Also I tried clearing homebrew cache.

**Comment by dphenderson** [comment]
Issue is with MacVim not Homebrew. MacVim working on fix. Closing.
