### ISSUE TITLE
PyPy site-packages not linked properly

### ISSUE THREAD

**Issue by alh84001** [Homebrew/homebrew#48530]
It seems that the non-versioned site-packages directory doesn't get linked properly into cellar. I guess it is because it already exists in the cellar before post_install is run. I have the following on my system after just installing pypy (and powerline):

    ~ ❯❯❯ ls -l /usr/local/Cellar/pypy/4.0.1/libexec/site-packages/site*
    lrwxr-xr-x  1 user  wheel  34 Jan 27 23:42 /usr/local/Cellar/pypy/4.0.1/libexec/site-packages/site-packages -> ../../../../lib/pypy/site-packages
    ~ ❯❯❯ ls -l /usr/local/lib/pypy/site-packages
    ~ ❯❯❯ ls -l /usr/local/Cellar/pypy/4.0.1/libexec/site-packages
    total 48
    -rw-r--r--   1 user  wheel   119 Nov 21 06:42 README
    drwxr-xr-x   6 user  wheel   204 Jan 27 23:52 _markerlib
    -rw-r--r--   1 user  wheel   217 Jan 27 23:52 easy-install.pth
    -rw-r--r--   1 user  wheel   126 Jan 27 23:52 easy_install.py
    -rw-r--r--   1 user  wheel   367 Jan 27 23:52 easy_install.pyc
    drwxr-xr-x   4 user  wheel   136 Jan 27 23:42 pip-8.0.2-py2.7.egg
    drwxr-xr-x   6 user  wheel   204 Jan 27 23:52 pkg_resources
    drwxr-xr-x  32 user  wheel  1088 Jan 27 23:52 powerline
    drwxr-xr-x   9 user  wheel   306 Jan 27 23:52 powerline_status-2.3-py2.7.egg-info
    drwxr-xr-x  52 user  wheel  1768 Jan 27 23:52 setuptools
    drwxr-xr-x  12 user  wheel   408 Jan 27 23:52 setuptools-19.6.dist-info
    -rw-r--r--   1 user  wheel    28 Jan 27 23:42 setuptools.pth
    lrwxr-xr-x   1 user  wheel    34 Jan 27 23:42 site-packages -> ../../../../lib/pypy/site-packages

**Comment by mikemcquaid** [comment]
CC @tdsmith for thoughts

**Comment by tdsmith** [comment]
Whoops :/ This must have happened when we switched to package.py. I'll commit a fix; `brew postinstall pypy` will migrate packages and fix up the paths.

**Comment by tdsmith** [comment]
Thanks for the report!
