### ISSUE TITLE
MariaDB Connector C

### ISSUE THREAD

**Issue by jeroenooms** [Homebrew/homebrew#48543]
Would it be allowed to have a separate recipe for [mariadb-connector-c](https://downloads.mariadb.org/connector-c/)? Currently the only options to install a client library are the legacy `mysql-connector-c` or install the entire `mariadb` system.

Is there a reason mariadb-connector-c is not available? If I submit a PR, would this be reviewed?

**Comment by cosmo0920** [comment]
I've registered `mariadb-connector-c` to fulfill your suggestion in #48637.
Is this what you are looking for?

**Comment by jeroenooms** [comment]
Yes thank you :)

**Comment by DomT4** [comment]
Closing in favour of the PR then.
