### ISSUE TITLE
postgresql: $(brew --prefix)/var/postgres is owned by root

### ISSUE THREAD

**Issue by tamird** [Homebrew/homebrew#48558]
This is bizarre and surprising.

As of postgres 9.5.0, `brew install postgres` results in:
```shell
$ ls -lah $(brew --prefix)/var
total 0
drwxr-xr-x   8 tamird  admin   272B Jan 28 11:34 .
drwxr-xr-x  20 tamird  admin   680B Jan 10 20:09 ..
drwxr-xr-x   4 tamird  admin   136B May  4  2015 lib
drwxr-xr-x   3 tamird  admin   102B Jun 25  2015 log
drwxr-xr-x  24 tamird  admin   816B Dec 12 20:24 mysql
drwxr--r--   2 root    admin    68B Jan 28 11:34 postgres // <------ root? wtf?
drwxr-xr-x   3 tamird  admin   102B Aug 23 12:14 run
drwxr-xr-x   4 tamird  admin   136B Apr 21  2015 www
```
Nuking this directory and re-running `initdb $(brew --prefix)/var/postgres` results in:
```shell
ls -lah $(brew --prefix)/var
total 0
drwxr-xr-x   8 tamird  admin   272B Jan 28 11:36 .
drwxr-xr-x  20 tamird  admin   680B Jan 10 20:09 ..
drwxr-xr-x   4 tamird  admin   136B May  4  2015 lib
drwxr-xr-x   3 tamird  admin   102B Jun 25  2015 log
drwxr-xr-x  24 tamird  admin   816B Dec 12 20:24 mysql
drwx------  27 tamird  admin   918B Jan 28 11:36 postgres // <------ not root
drwxr-xr-x   3 tamird  admin   102B Aug 23 12:14 run
drwxr-xr-x   4 tamird  admin   136B Apr 21  2015 www
```

What's going on here?

**Comment by dunn** [comment]
Did you have a previous version installed before 9.5.0?

**Comment by tamird** [comment]
I did, but I removed `$(brew --prefix)/var/postgres` each time before reinstalling.

**Comment by denji** [comment]
@tamird user:group /bin/ `ls -l $(which initdb)` ?

**Comment by tamird** [comment]
`tamird:admin`. I believe if `initdb` was owned by `root` then manually invoking it would also cause the created directory to be owned by `root`.

**Comment by dunn** [comment]
And this happens every time? If you remove `var/postgres` and reinstall, it's back to root?

**Comment by tamird** [comment]
Yes.

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by tamird** [comment]
Yikes, I don't know what changed, but I can no longer reproduce this.

**Comment by kevinburkeshyp** [comment]
I can reproduce this reliably. I'm running this formula - https://github.com/Homebrew/homebrew/blob/f8509e6/Library/Formula/postgresql.rb - and the following commands (note, we install from a private Homebrew repo, but it's that same file)

```
$ brew uninstall postgresql; sudo rm -rf /opt/boxen/homebrew/var/postgres; brew install --verbose Shyp/packages/postgresql > /tmp/install-postgresql.log 2>&1
```

The directory gets created with `root:staff` permissions:

```
drwxr--r--   2 root   staff    68B Feb  2 14:45 postgres
```

Here's a gist of the install log - roughly the first 5k lines are unpacking 9.4.5. https://gist.github.com/kevinburkeshyp/2b3602178969e665018e

Going to try now with just installing the latest `postgresql` repo. Also `launchctl` may be currently running, I'm going to unload it and then re-run those commands and try to reproduce.

**Comment by kevinburkeshyp** [comment]
Unloaded and re-ran, seems like the directory gets created with the correct permissions:

```
$ launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist; brew uninstall postgresql; sudo rm -rf /opt/boxen/homebrew/var/postgres; brew install --verbose Shyp/packages/postgresql > /tmp/install-postgresql.log 2>&1 ;
```

```
$ ll /opt/boxen/homebrew/var | grep postgres
drwx------  23 burke  staff   782B Feb  2 14:54 postgres
```

**Comment by kevinburkeshyp** [comment]
Just reloaded it and it's owned by root. I was advised to make a new ticket in the #machomebrew IRC channel, will do so now.
