### ISSUE TITLE
gnuplot build from source pauses

### ISSUE THREAD

**Issue by wlad** [Homebrew/homebrew#48568]
Homebrew 0.9.5 (git revision 7d3a; last commit 2016-01-28)
Running on El Capitan

Installing or upgrading gnuplot with the build-from-source option pauses indefinitely between =make= and =make install=. Pressing *Enter* a couple of times needed for the formula install to continue.

**Comment by tdsmith** [comment]
Can't reproduce, sorry. Can you share a log of a completed build with `brew gist-logs gnuplot`? Building takes ~30 seconds on my system.

**Comment by wlad** [comment]
Sure! I think the problem comes up when building the gnu plot documentation in LaTeX:
>> ! LaTeX Error: File `subfigure.sty' not found.

https://gist.github.com/anonymous/a46b2b4b76c487fea342

**Comment by dunn** [comment]
I guess it detects if LaTeX is installed on the system and tries to use it to build docs?  Since I can't reproduce on a system without it.
