### ISSUE TITLE
feature request: downloading retry mechanism

### ISSUE THREAD

**Issue by huanzhang** [Homebrew/homebrew#48579]
When installing apps/libs with brew, it sometimes fails with download error after having some progress(for example 5%). I have to manually resume the download for many times to finish the installation.(I believe this is very common for people in China.)

I hope we can pass an argument such as -R to the command that the download can auto resume.

**Comment by mikemcquaid** [comment]
We do already use `curl`'s retry system: https://github.com/Homebrew/homebrew/blob/599bc69a0e2e20a66d0234b56ac14a65f2e9f7a0/Library/Homebrew/download_strategy.rb#L288-L302

You'll need to work out why this isn't working for you but I don't consider it a Homebrew bug.
