### ISSUE TITLE
openssl broken

### ISSUE THREAD

**Issue by jeroenooms** [Homebrew/homebrew#48588]
The `openssl-1.0.2f.tar.gz` has been released and `openssl-1.0.2e.tar.gz` gives 404 now.

**Comment by DomT4** [comment]
We're aware, and working on it: #48552.

For now the old release is still available in the bottles and on both the `mirrorservice` and Homebrew mirrors listed in the OpenSSL formula.

**Comment by jeroenooms** [comment]
Great, sorry I hadn't noticed the other issue.
