### ISSUE TITLE
Pygame Formula on OS X El Capitan causes graphical glitching

### ISSUE THREAD

**Issue by saltycraig** [Homebrew/homebrew#48594]
The pygame formula installs sdl_image 1.2.12, which it seems has a bug/compatibility error with El Capitan that causes many graphical glitches when running python games built with pygame. The formula should be rewritten to install sdl_image 1.2.10 instead for now (which fixes the issues) until it is resolved (unknown who or when/if this might be fixed). See relevant discussion here:

http://stackoverflow.com/questions/33115482/rendering-glitch-on-mac-osx-el-capitan-with-opengl/35075170#35075170

**Comment by tdsmith** [comment]
This issue was moved to Homebrew/homebrew-python#281
