### ISSUE TITLE
question about possibly breaking homebrew by using verify/repair permissions

### ISSUE THREAD

**Issue by technodude458** [Homebrew/homebrew#48609]
ok when I do verify permissions I get this as of installing homebrew and I'm wondering if running repair will cause problems or is it safe to do
![screen shot 2016-01-29 at 2 07 35 pm](https://cloud.githubusercontent.com/assets/3880653/12685331/c48bcf46-c691-11e5-8921-ebbb3074f93b.png)

**Comment by UniqMartin** [comment]
I can't see anything in your log output of Disk Utility that would be related to Homebrew. Can you elaborate a bit more on why you think Homebrew could be affected by “Repair Disk Permissions”?

**Comment by technodude458** [comment]
ok the usr folder and cores are part of homebrew so I'm afraid if i repair them and the mac changes them it could break homebrew

**Comment by technodude458** [comment]
typically more comes up but i wouldn't be able to take a screenshot booting off the recovery partition

**Comment by UniqMartin** [comment]
In a default installation of Homebrew, only `/usr/local` is owned by Homebrew. Both `/cores` and `/usr/standalone` are parts of a normal OS X installation and have nothing to do with Homebrew.

**Comment by technodude458** [comment]
ok then i'll try it and see what happens

**Comment by UniqMartin** [comment]
Closing for now, but feel free to report back if you notice any issues.
