### ISSUE TITLE
gcc: warning: couldn't understand kern.osversion '15.0.0

### ISSUE THREAD

**Issue by nislam17** [Homebrew/homebrew#48623]
After upgrading to El Capitan, I've been getting this error. Updating xcode didn't solve the problem. 

$ brew config 
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: bbe1b6a268dc9c945abf85a3c9f843a1825b0b3e
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit haswell
OS X: 10.11.1-x86_64
Xcode: 7.2
CLT: 7.2.0.0.1.1447826929
Clang: 7.0 build 700
MacPorts/Fink: /opt/local/bin/port
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby

**Comment by DomT4** [comment]
Where are you seeing the error?

**Comment by mikemcquaid** [comment]
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by DomT4** [comment]
Closing as dead. Please do let us know if we can help here by providing the information requested and we'll do our best to assist. Thanks!
