### ISSUE TITLE
homebrew.pth doesn't exist

### ISSUE THREAD

**Issue by tudr** [Homebrew/homebrew#48636]
Something seems off, because I'm experiencing a similar problem now while trying to sync with Google Fonts through a git repo.  The protobuf app is being a pain and thought I got it, but nope!  
_After a bunch of other attempts that ended up causing poor brewmaster a conniption and had to delete and prune some files, he was ready to brew and reinstalled above_
**Check it out:**
```
$ brew reinstall protobuf
==> Reinstalling protobuf
==> Downloading https://homebrew.bintray.com/bottles/protobuf-2.6.1.el_capitan.bottle.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/protobuf-2.6.1.el_capitan.bottle.4.tar.gz
==> Pouring protobuf-2.6.1.el_capitan.bottle.4.tar.gz
==> Caveats
Editor support and examples have been installed to:
  /usr/local/Cellar/protobuf/2.6.1/share/doc/protobuf
```
_Uh oh!  What is this... wait, really?_
```
Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/tudr/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/tudr/Library/Python/2.7/lib/python/site-packages/homebrew.pth
==> Summary
🍺  /usr/local/Cellar/protobuf/2.6.1: 118 files, 6.9M
```
**Fine:**
```
tudr at Tudors-iMac in ~/Dropbox/Fonts/fonts (master●)
$ mkdir -p /Users/tudr/Library/Python/2.7/lib/python/site-packages
tudr at Tudors-iMac in ~/Dropbox/Fonts/fonts (master●)
$   echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/tudr/Library/Python/2.7/lib/python/site-packages/homebrew.pth
zsh: no such file or directory: /Users/tudr/Library/Python/2.7/lib/python/site-packages/homebrew.pth
```
_Are you drunk Mr. Breau?_
**After digging deeper, I thought I was on to the solution:**
```
$ l /usr/local/lib/python2.7/site-packages
total 8
lrwxr-xr-x  1 tudr  admin    80B Jan 30 08:24 homebrew-protobuf.pth -> ../../../Cellar/protobuf/2.6.1/lib/python2.7/site-packages/homebrew-protobuf.pth
echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/tudr/Library/Python/2.7/lib/python/site-packages/homebrew-protobuf.pth
zsh: no such file or directory: /Users/tudr/Library/Python/2.7/lib/python/site-packages/homebrew-protobuf.pth
```
Is there something I'm missing?

Best,
Tudor

**Comment by bfontaine** [comment]
`>>` shouldn’t fail if the file doesn’t already exist. Which shell are you using?

**Comment by tudr** [comment]
In case you missed it, homebrew.pth may not exist, but homebrew-protobuf.pth
does.
Also, I'm ZSH.

**Comment by apjanke** [comment]
```
$ l /usr/local/lib/python2.7/site-packages
total 8
lrwxr-xr-x  1 tudr  admin    80B Jan 30 08:24 homebrew-protobuf.pth -> ../../../Cellar/protobuf/2.6.1/lib/python2.7/site-packages/homebrew-protobuf.pth
echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/tudr/Library/Python/2.7/lib/python/site-packages/homebrew-protobuf.pth
zsh: no such file or directory: /Users/tudr/Library/Python/2.7/lib/python/site-packages/homebrew-protobuf.pth
```

According to that `ls` output, the `homebrew-protobuf.pth` that exists is `/usr/local/Cellar/protobuf/2.6.1/lib/python2.7/site-packages/homebrew-protobuf.pth`. The "no such file or directory" error from `echo ... >>` is complaining about `/Users/tudr/Library/Python/2.7/lib/python/site-packages/homebrew-protobuf.pth`, the output target. Same basename, different path.

That error message can happen when trying to `>>` to a file in a directory which does not exist.

```
$ echo foo >> no/such/dir/foo.txt
zsh: no such file or directory: no/such/dir/foo.txt
```

It almost seems like that `mkdir -p /Users/tudr/Library/Python/2.7/lib/python/site-packages` failed, even though it didn't emit an error message. Check to make sure it exists, e.g. with a `find /Users/tudr/Library/Python -type d` or manual inspection in the terminal.

**Comment by DomT4** [comment]
Any update here?

**Comment by tudr** [comment]
Don't know.  I had to reformat that machine :(
