### ISSUE TITLE
brew.rb backtraces should probably go to $stderr

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew#48634]
When debug is enabled (<code>HOMEBREW_DEBUG=1</code>, etc.), something as benign as

https://github.com/Homebrew/homebrew/blob/3f6a3553ecad4f61b24b77a3df117e076905e672/Library/brew.rb#L90
```
exit Homebrew.failed? ? 1 : 0
```
leads to (even when the exit code is 0) the regular output and the debug output both going to stdout due to

https://github.com/Homebrew/homebrew/blob/3f6a3553ecad4f61b24b77a3df117e076905e672/Library/brew.rb#L126
```
puts e.backtrace if ARGV.debug?
```
This in particular causes the command-not-found-init setup to puke in the eval:
```
if brew command command-not-found-init > /dev/null; then
        eval "$(brew command-not-found-init)";
fi
```
printing
```
-bash: eval: line 70: unexpected EOF while looking for matching ``'
-bash: eval: line 72: syntax error: unexpected end of file
```
This would be fixable by changing it to
```
if brew command command-not-found-init > /dev/null; then
        eval "$(brew command-not-found-init 2>/dev/null)";
fi
```
but for the fact that the entire output from brew.rb goes to stdout.

Is this deliberate or should the three <code>puts e.backtrace</code>'s in brew.rb be <code>$stderr.puts e.backtrace</code>?

**Comment by bfontaine** [comment]
I don’t see any reason not to print this on stderr. Would you mind doing a pull-request to fix this behavior? This should help and I’m happy to answer any question you might have:
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

**Comment by ilovezfs** [comment]
@bfontaine yeah it's already ready to go. Just wanted to confirm this wasn't intentional behavior.

**Comment by ilovezfs** [comment]
@bfontaine it's on your doorstep now.
