### ISSUE TITLE
`brew reinstall` may display wrong build-option-dependent caveats

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#48657]
It looks like the way `Tab` is caching its input, a `brew reinstall` command with different build options than the original install may display the caveats that apply to the original installation's options, not the new one.

This will apply to formulae whose `caveats` include sections conditionalized on `build.with?`.

Caused #48612. Most of this issue is copied from the discussion there.

##   Cause   ##

Look [here in `caveats.rb`](https://github.com/Homebrew/homebrew/blob/03c925589896962938c2b1f6fec641895b0d737c/Library/Homebrew/caveats.rb#L8-L16).

```
  def caveats
    caveats = []
    begin
      build, f.build = f.build, Tab.for_formula(f)
      s = f.caveats.to_s
      caveats << s.chomp + "\n" if s.length > 0
    ensure
      f.build = build
    end
```

The formula's `build` options are swapped out for a "`Tab`" based on it before querying the formula for caveats.

And that [`Tab.for_formula(f)` initialization logic](https://github.com/Homebrew/homebrew/blob/03c925589896962938c2b1f6fec641895b0d737c/Library/Homebrew/tab.rb#L95-L129), if I'm reading it right, initializes its build options state from the receipt file in the installation, and not from the live `f` object it was passed. 

```
    paths << f.prefix
    path = paths.map { |pn| pn.join(FILENAME) }.find(&:file?)
    if path
      tab = from_file(path)
```

Then that [Tab.from_file()](https://github.com/Homebrew/homebrew/blob/03c925589896962938c2b1f6fec641895b0d737c/Library/Homebrew/tab.rb#L41) uses a cache for the build receipt file.

```
  def self.from_file(path)
    CACHE.fetch(path) { |p| CACHE[p] = from_file_content(File.read(p), p) }
  end
```

I think this means that, since a `Tab` was already built for the formula early in the `reinstall` process before the old installation was removed, the cached tab info will still have the old build options.

##   Reproducing   ##

[Here's](https://github.com/apjanke/homebrew/blob/caveats-conditionality-demo/Library/Formula/cowsay-caveats.rb) a quick way to reproduce. `cowsay-caveats` is a copy of `cowsay`, with an added `--without-foo` option, and caveats that depend on it.

```
class CowsayCaveats < Formula
...
  option "without-foo", "Build without Foo"
...
  def caveats
    if build.with?("foo")
      "Cowsay was built --with-foo."
    end
  end
...
```

Here's the results of doing `brew install -s cowsay-caveats` and two `brew reinstall cowsay-caveats --without-foo`. The first `brew reinstall cowsay-caveats --without-foo` still issues the `--with-foo` caveats. A `brew info` after the first reinstall correctly omits them.

```
[/usr/local/Library/Formula on ⇄ caveats-conditionality-demo]
$ brew install -s cowsay-caveats
==> Using the sandbox
==> Downloading http://ftp.acc.umu.se/mirror/cdimage/snapshot/Debian/pool/main/c/cowsay/
Already downloaded: /Library/Caches/Homebrew/cowsay-caveats-3.03.tar.gz
==> /bin/sh install.sh /usr/local/Cellar/cowsay-caveats/3.03
==> Caveats
Cowsay was built --with-foo.
==> Summary
🍺  /usr/local/Cellar/cowsay-caveats/3.03: 53 files, 32.6K, built in 0 seconds
[/usr/local/Library/Formula on ⇄ caveats-conditionality-demo]
$ brew reinstall -s cowsay-caveats --without-foo
==> Reinstalling cowsay-caveats with --without-foo
==> Using the sandbox
==> Downloading http://ftp.acc.umu.se/mirror/cdimage/snapshot/Debian/pool/main/c/cowsay/
Already downloaded: /Library/Caches/Homebrew/cowsay-caveats-3.03.tar.gz
==> /bin/sh install.sh /usr/local/Cellar/cowsay-caveats/3.03
==> Caveats
Cowsay was built --with-foo.
==> Summary
🍺  /usr/local/Cellar/cowsay-caveats/3.03: 53 files, 32.6K, built in 0 seconds
[/usr/local/Library/Formula on ⇄ caveats-conditionality-demo]
$ brew info cowsay-caveats
cowsay-caveats: stable 3.03 (bottled)
Configurable talking characters in ASCII art
https://web.archive.org/web/20120225123719/http://www.nog.net/~tony/warez/cowsay.shtml
Conflicts with: cowsay
/usr/local/Cellar/cowsay-caveats/3.03 (53 files, 32.6K) *
  Built from source with: --without-foo
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cowsay-caveats.rb
==> Options
--without-foo
	Build without Foo
[/usr/local/Library/Formula on ⇄ caveats-conditionality-demo]
$ brew reinstall -s cowsay-caveats --without-foo
==> Reinstalling cowsay-caveats with --without-foo
==> Using the sandbox
==> Downloading http://ftp.acc.umu.se/mirror/cdimage/snapshot/Debian/pool/main/c/cowsay/
Already downloaded: /Library/Caches/Homebrew/cowsay-caveats-3.03.tar.gz
==> /bin/sh install.sh /usr/local/Cellar/cowsay-caveats/3.03
🍺  /usr/local/Cellar/cowsay-caveats/3.03: 53 files, 32.6K, built in 0 seconds
[/usr/local/Library/Formula on ⇄ caveats-conditionality-demo]
$
```

##  Fixes  ##

Maybe the CACHE should check the mtime of the files its caching to ensure it's using fresh data? Or as a workaround, doing an uninstall could forcibly invalidate that CACHE.

**Comment by mistydemeo** [comment]
> Or as a workaround, doing an uninstall could forcibly invalidate that CACHE.

I think this is the simplest solution; if we're uninstalling, then we know that the cache is no longer valid and we don't have to make any inferences.

**Comment by UniqMartin** [comment]
> Maybe the CACHE should check the mtime of the files its caching to ensure it's using fresh data?

I think this would be the “right” and most robust fix and not overly difficult to implement. If modification times seem to be to unreliable, the cache could also store a SHA256 or similar of the receipt file to check whether the cache is still valid. (The alternative would be to invalidate the cache in all the right places, but this seems to be a much more difficult task.)

**Comment by xu-cheng** [comment]
>  If modification times seem to be to unreliable

Because the way we handle mtime to make reproducible bottle, I would say mtime is not unreadable. 

> the cache could also store a SHA256 or similar of the receipt file to check whether the cache is still valid.

In this case, it will cause IO overhead. Therefore, I kinda wonder do we need CACHE at all. On the one hand, it doesn't seem to be performance bottleneck. On the other hand, it does create other problems as well. (e.g. https://github.com/Homebrew/homebrew/commit/dd25bf6f79368b09ba1ef72dbda3395a523938e9)

**Comment by mikemcquaid** [comment]
> In this case, it will cause IO overhead. Therefore, I kinda wonder do we need CACHE at all. On the one hand, it doesn't seem to be performance bottleneck. On the other hand, it does create other problems as well. (e.g. dd25bf6)

The cache is a performance bottleneck for `brew bundle`. Let's invalidate it on `uninstall`.

**Comment by liumy601** [comment]
how to fix this? I also have the same problem.

here is the output:

brew reinstall gcc --without-multilib 
==> Reinstalling gcc with --without-multilib
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc-4.9.2.tar.bz2
==> ../configure --build=x86_64-apple-darwin14.1.1 --prefix=/usr/local/Cellar/g
==> make bootstrap
make[3]: *** [graphite-blocking.o] Error 1
rm gcc.pod
make[2]: *** [all-stage1-gcc] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
brew reinstall gcc --without-multilib error (https://github.com/Homebrew/homebrew/issues/48212)
brew install gcc --without-multilib stucks during 'make bootstrap' (https://github.com/Homebrew/homebrew/issues/48612)
gcc: warning: couldn't understand kern.osversion '15.0.0 (https://github.com/Homebrew/homebrew/issues/48623)
graphicsmagick fails to compile with gcc-5 in superenv (https://github.com/Homebrew/homebrew/issues/48402)
gcc failed to build on 10.6.8 (https://github.com/Homebrew/homebrew/issues/47741)
apple-gcc42 takes priority over modern gcc (https://github.com/Homebrew/homebrew/issues/41055)
gcc causes false alarms in C++ stdlib check (https://github.com/Homebrew/homebrew/issues/45218)
gcc 4.9.2 fails to produce debugging information (https://github.com/Homebrew/homebrew/issues/34976)
Object files deleted during build of gcc needed by gdb (https://github.com/Homebrew/homebrew/issues/35734)
MacOS.(gcc|clang|llvm)_version can return nil (https://github.com/Homebrew/homebrew/issues/18781)

**Comment by apjanke** [comment]
@liumy601: That is a different problem. Your build is actually failing. For this issue, the build succeeds but just displays an incorrect message at the end.

You can post your problem as a separate issue. Please read through the "READ THIS: https://git.io/brew-troubleshooting" link and include a gist of logs as described there.
