### ISSUE TITLE
question: How search the output of `system ...` for `/FAIL/`

### ISSUE THREAD

**Issue by zbeekman** [Homebrew/homebrew#48660]
I would like a robust way to search for `FAIL` in the output of a `system` call in the `test do` block of a new formula. My Ruby is sadly too limited to figure out how to do this with reasonable google-fu.

[Here](https://gist.github.com/zbeekman/0fd245c175925b9d6bd8#file-utetime-fortran-rb-L30) is what I have so far, and I want to search the output of [L30](https://gist.github.com/zbeekman/0fd245c175925b9d6bd8#file-utetime-fortran-rb-L30) for `FAIL` or ensure that every line except the last two of the output match `/PASS$|----$/`

**Comment by dunn** [comment]
Does the test program always exit 0, even on failure?

What you're looking for is the back-tick notation.  You can do this:
```ruby
!assert_match /FAIL.*/, `#{testpath}/datetime_test`
```

**Comment by zbeekman** [comment]
@dunn ah, good point... I'm going to go look and if not I have commit privileges with the upstream, so that's the obvious solution.

**Comment by zbeekman** [comment]
also, thanks for clarifying that for me! Ruby is a neat language, that I hope to be able to master someday (beyond homebrew formulae ruby-fu)

**Comment by mikemcquaid** [comment]
Ideally I'd probably even do `!assert_match(/FAIL/, system_output("#{testpath}/datetime_test"}`
