### ISSUE TITLE
"rack" formula ought to include the generated manpage in MANPATH somewhere

### ISSUE THREAD

**Issue by glyph** [Homebrew/homebrew#48691]
If you run `rack init` it will emit a manpage into the file `rack.1`.  This should really go into `"$(brew --prefix)"/Cellar/rack/$version/share/man/man1/rack.1` so that `man rack` works out of the box instead of requiring additional steps.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by glyph** [comment]
Sure. Not committing to a date right now, but I'll try to write something :).

**Comment by mikemcquaid** [comment]
Great, thanks!
