### ISSUE TITLE
http://www.chocolate-doom.org/ gives infection warnings from avast

### ISSUE THREAD

**Issue by strages** [Homebrew/homebrew#48705]
`brew info homebrew/games/chocolate-doom`

when entering http://www.chocolate-doom.org/ into browser: infection erros

maybe getting rid of this?

**Comment by DomT4** [comment]
They're quite active on GitHub. Perhaps this is worth flagging to them? https://github.com/chocolate-doom/chocolate-doom

Which browser is throwing this warning?

**Comment by strages** [comment]
Chrome;) avast installed

On Mon, Feb 1, 2016, 3:23 PM Dominyk Tiller <notifications@github.com>
wrote:

> They're quite active on GitHub. Perhaps this is worth flagging to them?
> https://github.com/chocolate-doom/chocolate-doom
>
> Which browser is throwing this warning?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Homebrew/homebrew/issues/48705#issuecomment-177991753>
> .
>
-- 
--

*Dimitrie Hoekstra, UI & Interaction Designer*
dhesign.com  | dimitriehoekstra@gmail.com | LinkedIn
<https://www.linkedin.com/in/dimitrieh> | Twitter
<https://twitter.com/strages33/>

**Comment by DomT4** [comment]
Would you mind dinging them on GitHub and see if they're aware of it? Thanks!

**Comment by tdsmith** [comment]
I think this isn't actionable on our end. I'll close this but please let us know if we can help with anything.
