### ISSUE TITLE
bazel can't find Java in /usr/local/buildtools if homebrew is in ~/homebrew

### ISSUE THREAD

**Issue by girving** [Homebrew/homebrew#48715]
I installed Java via `brew install Caskroom/cask/java`, and bazel via `brew install bazel`, both of which worked fine.  However, if I run bazel, I get

    shimura:tensorflow% bazel
    Couldn't find java at '/usr/local/buildtools/java/jdk8/bin/java'.

The problem may be related to my having installed homebrew to `~/homebrew` rather than `/usr/local`.  Here's `brew doctor`:

    shimura:~% brew doctor
    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry and just ignore them. Thanks!

    Warning: Your Homebrew is not installed to /usr/local 
    You can install Homebrew anywhere you want, but some brews may only build
    correctly if you install in /usr/local. Sorry!

**Comment by mistydemeo** [comment]
It looks like that happens here: https://github.com/bazelbuild/bazel/blob/5fb98d17a4696394893df4fd22ee38d7dfc8989f/src/main/cpp/blaze_startup_options.cc#L121-L130

And it tries to actually locate the prefix like so:

```c++
string GetDefaultHostJavabase() {
  const char *java_home = getenv("JAVA_HOME");
  if (java_home) {
    return std::string(java_home);
  }

  FILE *output = popen("/usr/libexec/java_home -v 1.7+", "r");
  if (output == NULL) {
    pdie(blaze_exit_code::LOCAL_ENVIRONMENTAL_ERROR,
         "Could not run /usr/libexec/java_home");
  }

  char buf[512];
  char *result = fgets(buf, sizeof(buf), output);
  pclose(output);
  if (result == NULL) {
    die(blaze_exit_code::LOCAL_ENVIRONMENTAL_ERROR,
        "No output from /usr/libexec/java_home");
  }

  string javabase = buf;
  if (javabase.empty()) {
    die(blaze_exit_code::LOCAL_ENVIRONMENTAL_ERROR,
        "Empty output from /usr/libexec/java_home - "
        "install a JDK, or install a JRE and point your JAVA_HOME to it");
  }

  // The output ends with a \n, trim it off.
  return javabase.substr(0, javabase.length()-1);
}
```

Do you have `JAVA_HOME` set in your environment, or does `/usr/libexec/java_home` point to the prefix it was trying to use? That string doesn't look like it's coming from Bazel itself.

**Comment by girving** [comment]
You're right!  My `JAVA_HOME` is indeed broken; I needed to set it on my desktop machine, and accidentally used the same `.bashrc` setting on my laptop.
