### ISSUE TITLE
csvquote brew/thingy needed

### ISSUE THREAD

**Issue by ph-hs** [Homebrew/homebrew#48713]
https://github.com/dbro/csvquote/issues/8

**Comment by bfontaine** [comment]
Please open a pull-request, we don’t do formula requests.
This should help and I’m happy to answer any question you might have: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md
Thanks!
