### ISSUE TITLE
weechat dyld library not loaded

### ISSUE THREAD

**Issue by morenoh149** [Homebrew/homebrew#48726]
trying to install weechat
```
➭ weechat
dyld: Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /usr/local/opt/gnutls/lib/libgnutls.30.dylib
  Reason: Incompatible library version: libgnutls.30.dylib requires version 14.0.0 or later, but libgmp.10.dylib provides version 13.0.0
[1]    27097 trace trap  weechat
```
brew doctor has no complaints

**Comment by DomT4** [comment]
`brew reinstall weechat`

**Comment by DomT4** [comment]
Oh, er, wait. Try `brew update && brew reinstall gmp`. Misread the error.

**Comment by morenoh149** [comment]
that worked. Should I close?

**Comment by DomT4** [comment]
Probably safe to close, aye. Suspect was some local error given we haven't seen any further reports on this to date. Glad all is working again! :smiley:
