### ISSUE TITLE
vim fails to build with ruby support using rbenv

### ISSUE THREAD

**Issue by dafstone** [Homebrew/homebrew#48721]
Hi,

I've been having a problem where I can't get homebrew to install with ruby support on OS 10.11. I've run brew update, etc.  I'm uncertain when this problem first appeared, but my vim plugins that required ruby support ran not too long ago - it's possible this also never worked since moving from RVM to Rbenv a few months back, but I've been doing more ruby development lately and it's starting to become troublesome.  Hoping you can help.

I've pulled the logs via gist-logs, which can be found here: https://gist.github.com/evolvingmedianet/5ec0824c0ca566dcf62e

I believe the offending problem is the ability to link the vim install to the header installs provided by rbenv:

`checking Ruby version... OK`
`checking Ruby rbconfig... RbConfig`
`checking Ruby header files... not found; disabling Ruby`

However, I'm uncertain how to point the build to the headers provided by Rbenv this given that there's no ability to pass configuration information to the brew formula. Any help would be appreciated.

**Comment by CamJN** [comment]
This is close enough to a problem i was having for me to chime in, are you using ruby 2.3 by any chance? And if so do you set `SDKROOT` or other dev env vars? If so you're probably running into the same issue as me and need to use a vanilla env while building anything relying on the ruby headers until ruby updates (the patch is already landed but a new release needs to get cut).

**Comment by dafstone** [comment]
You know - now that you mention it, I am in fact using Ruby 2.3, though I am not setting SDKROOT.  I did try to roll this back to the system ruby at one point, and though it compiled, it wasn't useable for other reasons.

So just now I did what should have been initially obvious, which is I switched back to 2.2.3 and ... yeah, good and compiled with the `+ruby` flag.  I can probably close this now - but one question first.

When you say _need to use a vanilla env while building anything relying on the ruby headers until ruby updates _ - what do you mean by _when ruby updates_, do you mean the rbenv build of ruby, or the upstream ruby?  

Thanks so much for pointing this out!

**Comment by CamJN** [comment]
upstream ruby, they made an incorrect assumption about what parts of the env were safe to use and broke a bunch of stuff.

**Comment by CamJN** [comment]
For anyone googling in the future my upstream bug report is here: https://bugs.ruby-lang.org/issues/11881

**Comment by dafstone** [comment]
Thanks much, that is probably exactly what's happening.  Closing this out as not actually a vim-brew issue.

**Comment by rakkesh** [comment]
I use `chruby`, so, the path to `ruby` may differ but you can use the following in the formula prior to `./configure`.

```
ENV.prepend "CFLAGS", "-I/Users/stone/.rubies/ruby-2.3.0/include/ruby-2.3.0"
ENV.prepend "LDFLAGS", "-L/Users/stone/.rubies/ruby-2.3.0/lib/ruby"
```
