### ISSUE TITLE
Brew upgrade error

### ISSUE THREAD

**Issue by valeIT** [Homebrew/homebrew#48736]
```            
Error: Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool
```

I checked in `/usr/bin` and otool is there. [May be related to this problem](http://stackoverflow.com/questions/35089365/codesign-allocate-not-a-developer-tool-or-in-path)?

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by valeIT** [comment]
Running `brew doctor` also results in the same error, but `brew update` works flawlessly.

[`brew config` output](https://gist.github.com/valeIT/5f978041cf7a797a2ee3)


Everything worked before updating Xcode. I even deleted it, reinstalled it and installed the updated command line tools manually, but the problem linked above still persists.

**Comment by mikemcquaid** [comment]
@valeIT Try to run `xcode-select --install`.

**Comment by valeIT** [comment]
Did already, same problem. Now I have totally uninstalled Xcode and the command tools again and with those uninstalled I still have the same problem (running ` brew doctor` as example here):

```
xcode-select: error: unable to get active developer directory, use `xcode-select --switch` to set one (or see `man xcode-select`)
Error: Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool
```

**Comment by mikemcquaid** [comment]
What's the output of `xcode-select --print-path`?

**Comment by valeIT** [comment]
That's correct: `/Applications/Xcode.app/Contents/Developer`

**Comment by mikemcquaid** [comment]
Run `xcode-select --switch /Library/Developer/CommandLineTools`

**Comment by valeIT** [comment]
Works now o.o Are the CL Tools from Xcode missing something or what's the deal here?

Anyway thanks =)

**Comment by mikemcquaid** [comment]
@valeIT `xcode-select` was pointing to an invalid path. My pleasure.
