### ISSUE TITLE
How to install pyqt5 for default python 2 on MacOS?

### ISSUE THREAD

**Issue by omerfirmak** [Homebrew/homebrew#48746]
pyqt5 package has python3 dependency but I want to install it just for the default python2 installation that comes with the os. I am running El Capitan. I searched online but couldn't find anything up-to-date

**Comment by bfontaine** [comment]
You can use `brew install pyqt5 --with-python --without-python3`.

**Comment by omerfirmak** [comment]
Im fairly certain that i have tried that but it didn't work that time. Magically now it seems like it works. Thanks!
