### ISSUE TITLE
pip ImportError: No module named <module>

### ISSUE THREAD

**Issue by tstrokes** [Homebrew/homebrew#48754]
Just reinstalled OS X El Capitan‎. After installing brew, Xcode and python, python reports an:
`ImportError: No module named <module> `
for every module installed by pip. This happens for scripts or commands line tools. 

```
❯ patool                                                        
Traceback (most recent call last):
  File "/usr/local/bin/patool", line 24, in <module>
    import patoolib
ImportError: No module named patoolib
```

When I import them from the python shell everything seems to be fine.

```
Python 2.7.11 (default, Jan 22 2016, 08:29:18) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import patoolib
>>> 
```

**Comment by mikemcquaid** [comment]
CC @tdsmith for thoughts

**Comment by tdsmith** [comment]
What's `head -1 /usr/local/bin/patool` say?

**Comment by tstrokes** [comment]
`#!/usr/bin/python`

**Comment by tdsmith** [comment]
What are `which pip` and `head -1 $(which pip)`?

If you run `python -m pip install -U --force-reinstall patoolib` you should get a module with the "right" shebang (pointing to Homebrew's python). I'm confused why you would get shebangs that point to system Python.

**Comment by tstrokes** [comment]
~
❯ which pip
/usr/local/bin/pip

~
❯ head -1 $(which pip)
#!/usr/local/opt/python/bin/python2.7

~
❯ python -m pip install -U --force-reinstall patoolib
Collecting patoolib
  Could not find a version that satisfies the requirement patoolib (from versions: )
No matching distribution found for patoolib

**Comment by tdsmith** [comment]
Or `patool` or whatever it's called, I guess.

**Comment by tstrokes** [comment]
```
~
❯ python -m pip install -U --force-reinstall patool
Collecting patool
  Using cached patool-1.12-py2.py3-none-any.whl
Installing collected packages: patool
  Found existing installation: patool 1.12
    Uninstalling patool-1.12:
      Successfully uninstalled patool-1.12
Successfully installed patool-1.12

~
❯ head -1 /usr/local/bin/patool
#!/usr/bin/python
```

**Comment by tdsmith** [comment]
Oh, this turns out to be a patool bug. You should bug them to change their shebang to `#!/usr/bin/env python`.

**Comment by tdsmith** [comment]
Let me know if this happens with other libraries; I think this is a case of a program doing something unusual and incorrect (i.e. not using the usual distutils mechanism to determine a shebang).

**Comment by tstrokes** [comment]
Whats strange is that this has the correct shebang: [patool](https://github.com/wummel/patool/blob/master/patool)
