### ISSUE TITLE
install unittest-cpp fails to build on 10.11.2

### ISSUE THREAD

**Issue by BarrySmith** [Homebrew/homebrew#48763]
https://gist.github.com/anonymous/6192eb39ba216426d4ad

**Comment by mikemcquaid** [comment]
Your `brew doctor` warnings are probably the problem. Try to fix them and try again.

**Comment by BarrySmith** [comment]
I changed the PATH and removed the nonbrew files and dependencies and get the exact same error output.

**Comment by DomT4** [comment]
Fails here too to be fair:
```
Running unit tests...
:107: error: Failure in test: Expected 2 but was 0
FAILURE: 1 out of 174 tests failed (1 failures).
Test time: 0.10 seconds.
make: *** [TestUnitTest++] Error 1
```

**Comment by kylesm** [comment]
It looks like HEAD builds cleanly on 10.11.3: `brew install --HEAD unittest-cpp`

There have been some big changes since 1.4 was released in 2008: https://github.com/unittest-cpp/unittest-cpp/blob/master/README.md#historic-release-notes

**Comment by DomT4** [comment]
Updated the version in https://github.com/Homebrew/homebrew/pull/49135. If anyone wants to pull that locally and check it functions as expected in a more thorough way I'd certainly appreciate that.
