### ISSUE TITLE
brew reinstall gcc --without-multilib fails on mac

### ISSUE THREAD

**Issue by liumy601** [Homebrew/homebrew#48771]
Because when i tried "brew reinstall gcc --without-multilib", it failed. so i tried "brew reinstall gcc --without-multilib", and it still failed, here is the output:

==> Reinstalling gcc with --without-multilib
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc-4.9.2.tar.bz2
==> ../configure --build=x86_64-apple-darwin14.1.1 --prefix=/usr/local/Cellar/gcc/4.9.2_1 -
==> make bootstrap
make[3]: *** [graphite.o] Error 1
rm gcc.pod
make[2]: *** [all-stage1-gcc] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
brew reinstall gcc --without-multilib error (https://github.com/Homebrew/homebrew/issues/48212)
brew install gcc --without-multilib stucks during 'make bootstrap' (https://github.com/Homebrew/homebrew/issues/48612)
gcc: warning: couldn't understand kern.osversion '15.0.0 (https://github.com/Homebrew/homebrew/issues/48623)
graphicsmagick fails to compile with gcc-5 in superenv (https://github.com/Homebrew/homebrew/issues/48402)
gcc failed to build on 10.6.8 (https://github.com/Homebrew/homebrew/issues/47741)
apple-gcc42 takes priority over modern gcc (https://github.com/Homebrew/homebrew/issues/41055)
gcc causes false alarms in C++ stdlib check (https://github.com/Homebrew/homebrew/issues/45218)
gcc 4.9.2 fails to produce debugging information (https://github.com/Homebrew/homebrew/issues/34976)
Object files deleted during build of gcc needed by gdb (https://github.com/Homebrew/homebrew/issues/35734)
MacOS.(gcc|clang|llvm)_version can return nil (https://github.com/Homebrew/homebrew/issues/18781)

**Comment by liumy601** [comment]
has anyone came across this problem before?

**Comment by mikemcquaid** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please do.

**Comment by DomT4** [comment]
If that's your GCC version from the core you should probably `brew update`.

**Comment by DomT4** [comment]
Please let us know if we can assist further here, Thanks!
