### ISSUE TITLE
vim 7.4.1190 failed to build on 10.11.3-x86_64

### ISSUE THREAD

**Issue by Gimi** [Homebrew/homebrew#48777]
Gist logs is here: https://gist.github.com/anonymous/57fdfea29b73262c7528

**Comment by mikemcquaid** [comment]
Try to `brew uninstall ruby` and if that works then `brew install ruby` again and see if that works.

**Comment by Gimi** [comment]
@mikemcquaid thanks for the suggestion. However, it didn't work, same error.

**Comment by mikemcquaid** [comment]
@Gimi Can I see the Gist logs for when `brew uninstall ruby; brew install vim` has been run?

**Comment by akshetpandey** [comment]
It seems the find command is shadowed by a different function?

```
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/find.rb:43:in `find'
	from /Users/zliang/bin/find:12:in `<main>'
```

**Comment by DomT4** [comment]
Please let us know if we can assist further here, Thanks!

**Comment by Gimi** [comment]
Sorry for the late response. @akshetpandey is right, it's because the `find` command was shadowed by a different function. Everything goes well when I removed the custom `find` command.

Thank you all for the great help!
