### ISSUE TITLE
How can I completely uninstall Homebrew and uninstall everything it has done?

### ISSUE THREAD

**Issue by corysimmons** [Homebrew/homebrew#48792]
It's a cool tool, it just doesn't mesh with me. What are the steps to uninstall every package/dependency it has every installed and the uninstall Homebrew completely from my system?

**Comment by DomT4** [comment]
https://github.com/Homebrew/install may be useful.

**Comment by corysimmons** [comment]
Well that's an oddly named repo.

Will this uninstaller uninstall everything Homebrew has ever installed and all their dependencies, or is Homebrew going to leave a ton of stuff on my system?

**Comment by DomT4** [comment]
The `uninstall` script was added _much_ later than the install script, by which point links across the internet were telling people to go find Homebrew's `install` repo.

> Will this uninstaller uninstall everything Homebrew has ever installed and all their dependencies

Yes. If you run it with `--dry-run` it should tell you what is being removed, without actually doing any removing.

**Comment by corysimmons** [comment]
@DomT4 Awesome thanks.

I might just uninstall everything, then reinstall a clean version of Homebrew. I think my problem was going crazy installing tons of packages, now it just feels insane to maintain.

**Comment by DomT4** [comment]
If you want to remove all the packages you've installed but keep Homebrew around you could also do something like:

```bash
brew list -1 | xargs brew rm
```

**Comment by corysimmons** [comment]
The more I think about it, the more I probably just need to do a factory restore. This laptop is full of so much junk.

**Comment by mikemcquaid** [comment]
@DomT4 I'd recommend `brew bundle dump` for that, just FYI.
