### ISSUE TITLE
nettle 3.2

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew#48801]
nettle 3.2 fixes some elliptic curve miscomputations: http://www.openwall.com/lists/oss-security/2016/02/02/2

some discussion in abandoned pr #48767

**Comment by DomT4** [comment]
The other PR was actually more or less fine. The `git-annex` failure is unrelated (the test runs too long and expires) so it would have been okay to merge with a small change in regards to explaining where the patch was coming from, etc.
