### ISSUE TITLE
ffmpeg --with-faac failed to build on 10.11

### ISSUE THREAD

**Issue by PBeltrame** [Homebrew/homebrew#48824]
Paolos-MacBook-Pro:~ Paolo$ brew reinstall ffmpeg --with-faac
==> Reinstalling ffmpeg with --with-faac
==> Downloading https://ffmpeg.org/releases/ffmpeg-2.8.6.tar.bz2
Already downloaded: /Library/Caches/Homebrew/ffmpeg-2.8.6.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/2.8.6 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-av
Last 15 lines from /Users/Paolo/Library/Logs/Homebrew/ffmpeg/01.configure:
--enable-libx264
--enable-libmp3lame
--enable-libvo-aacenc
--enable-libxvid
--enable-libfaac
--enable-nonfree
--enable-vda

ERROR: libfaac not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.

READ THIS: https://git.io/brew-troubleshooting

**Comment by mikemcquaid** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please do.

**Comment by DomT4** [comment]
Please let us know if we can assist further here, Thanks!

**Comment by retokromer** [comment]
@PBeltrame : Since version 2.8.6, there is an issue with the `--enable-libvo-aacenc` flag. Please report to the FFmpeg maintainers.

**Comment by retokromer** [comment]
@PBeltrame : The version 3.0 has just been published, which should resolve your issue.

**Comment by slhck** [comment]
@retokromer  FYI, support for `libvo-aacenc`  was removed as of 3.0 (see http://ffmpeg.org/index.html#news).

**Comment by retokromer** [comment]
@slhck Thank you! I know this. There is however a non-solved issue in 2.8.6.
