### ISSUE TITLE
Dependencies in other taps not tapped soon enough

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew#48834]
This issue does not affect Homebrew core because it has no formula in core that depend on formula in other taps. This issue may affect formula in other taps, but I don't know of a real-world case.

The formula `rtorrent` depends on `autoconf` which on Linuxbrew depends on `homebrew/dupes/m4`.

`brew install rtorrent` fails with
```
Error: /home/linuxbrew/.linuxbrew/opt/m4 not present or broken
Please reinstall homebrew/dupes/m4. Sorry :(
```

However `brew tap homebrew/dupes && brew install rtorrent` succeeds. See below.

To recreate this issue solely for testing purpose, edit `autoconf` and add `depends_on "homebrew/dupes/m4"`, then `brew install rtorrent`.

#### Does not work
```
❯❯❯ brew install rtorrrent
==> Installing dependencies for rtorrent: automake, libtool, pkg-config, cppunit, makedepend, zlib, openssl, libtorrent
…
Error: /home/linuxbrew/.linuxbrew/opt/m4 not present or broken
Please reinstall homebrew/dupes/m4. Sorry :(
```

#### Works
```
❯❯❯ brew tap homebrew/dupes
❯❯❯ brew install rtorrent
==> Installing dependencies for rtorrent: homebrew/dupes/m4, autoconf, automake, libtool, pkg-config, cppunit, makedepend, zlib, openssl, libtorrent
```

Originally reported here: https://github.com/Linuxbrew/linuxbrew/issues/742

**Comment by mikemcquaid** [comment]
> This issue does not affect Homebrew core because it has no formula in core that depend on formula in other taps. This issue may affect formula in other taps, but I don't know of a real-world case.

If this is the case: we're unlikely to fix this ourselves but will review a PR to do so.

**Comment by sjackman** [comment]
Fair enough. The issue is low priority for me as well because the work around is straight forward (`brew tap homebrew/dupes`), but I wanted to document it.

**Comment by xu-cheng** [comment]
Sorry, but I cannot reproduce this problem. There are [codes](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/formula_installer.rb#L114-L128) who auto install the missing taps.

**Comment by sjackman** [comment]
Hi, Xu. Did you try the exact example above? That is, add the `m4` dependency to `autoconf` and then attempt to install `rtorrent` (not `autoconf`) when `homebrew/dupes` is not yet tapped? I was able to reproduce this error on a stock Homebrew system (not Linuxbrew).

```sh
brew remove m4 autoconf
brew untap homebrew/dupes
cd /usr/local
patch -p1 <<EOF
--- a/Library/Formula/autoconf.rb
+++ b/Library/Formula/autoconf.rb
@@ -16,6 +16,8 @@ class Autoconf < Formula
 
   keg_only :provided_until_xcode43
 
+  depends_on "homebrew/dupes/m4"
+
   def install
     ENV["PERL"] = "/usr/bin/perl"
 
EOF
brew install rtorrent
```

```
❯❯❯ brew install rtorrent
==> Tapping homebrew/dupes
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-dupes'...
remote: Counting objects: 42, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 42 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (42/42), done.
Checking connectivity... done.
Tapped 0 formulae (103 files, 105.4K)
==> Installing dependencies for rtorrent: libtorrent
==> Installing rtorrent dependency: libtorrent
Error: /usr/local/opt/autoconf not present or broken
Please reinstall autoconf. Sorry :(
```

**Comment by sjackman** [comment]
Thanks, Xu!
