### ISSUE TITLE
/Library/Formula/jless.rb checksum mismatch

### ISSUE THREAD

**Issue by teammember8** [Homebrew/homebrew#48853]
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/jless.rb

```
  [
    %w[258       961275c26c6f6ec2e04821d9d9d1b10505214b1f],
    %w[258-259   7256998c59f9743e61e83e9e5ebc5183e8eeb269],
    %w[259-260   56e5537fae516ee738b1512eed303f43ed0d4575],
    %w[260-261   3a889e178a32c3a273b89fd396976362a975f627],
    %w[261-262   d5cc92e5dcbfde26257eec5f126df5bf73779a89],
    %w[262.ext03 dc35204274ecf02da5f7ffb583da680ea6f4356c]
  ]
```

All use sha1 hashes, so I downloaded them and was going to update them to sha256

However I get:
less-382-iso259-260.patch.gz	(application/gzip) - 98505 bytes
SHA-1	2ee7b5f47fd12439873a4d3ab9c2784914124c88
less-382-iso260-261.patch.gz	(application/gzip) - 2280 bytes
SHA-1	6d3065a5a67af503ad5a64a4e777310241c21a02
less-382-iso261-262.patch.gz	(application/gzip) - 6931 bytes
SHA-1	62505f2c7afb37471c096617c639c661dc0b18d1
less-382-iso262.ext03.patch.gz	(application/gzip) - 1371154 bytes
SHA-1	b349a0ef81f176106885e469f5734ef429016aba
less-382-iso258.patch.gz	(application/gzip) - 427656 bytes
SHA-1	e42ec4516b0bfca22cff6f27e54d34a5d7218e62
less-382-iso258-259.patch.gz	(application/gzip) - 36061 bytes
SHA-1	d16401032fdbca30288b735eda6f88d7742c6005

Which matches none of them, do we even need this part of the Formula?

The sha256 hash for `url "http://ftp.de.debian.org/debian/pool/main/j/jless/jless_382-iso262.orig.tar.gz"` does match though.

**Comment by mikemcquaid** [comment]
Feel free to just update it however you think; as long as the formula works.

**Comment by DomT4** [comment]
A PR on this was merged.
