### ISSUE TITLE
Wireshark versions not available? Where is the best place to discuss this topic? 

### ISSUE THREAD

**Issue by lenlynch** [Homebrew/homebrew#48859]
Thanks for Homebrew AND for including Wireshark!
It seems like there are Formula commits left available for other applications for older versions, but not Wireshark?

I need to build a version (1.12) other than the latest (2.0.1), and I'm having trouble understanding how I can find/or create a Formula for *this* so that I can build it inside of Homebrew.

The dmg file from Wireshark.org requires X11 support, and I want to build a version that supports GTK+.

Sorry in advance if I'm already totally "in the weeds"...

If there is a better place to discuss this topic, if so please point me in that direction.
Thanks in advance.

**Comment by mikemcquaid** [comment]
We don't support older versions, sorry.

**Comment by DomT4** [comment]
You can always pluck the old version out of the commit history and support it yourself in a tap. It's a [very easy](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md) process.

In Wireshark's case be wary older versions may not build well against newer dependencies and may have security issues.

**Comment by mikemcquaid** [comment]
> You can always pluck the old version out of the commit history and support it yourself in a tap. It's a very easy process.

@DomT4 maybe we could provide a command for that?

**Comment by lenlynch** [comment]
@DomT4 if that is easy for you, I don't want to impede real work...

I kept looking for a way to search the commit history using the web interface, but it looks like changes to it make this not possible either at this time...  So I guess I need to clone the current version of Homebrew, and then use a `git log` variation to find the commit entries with Wireshark in the history, then download that specific commit version, and experiment with it until I have a working build that can be used to generate a tap that could potentially be added back to the project?  Or am I making it more complicated than needed?

@mikemcquaid  thanks for the suggestion

-prepadawan git user in training...

**Comment by lenlynch** [comment]
@DomT4 I think I found the commit item I was looking for in the git log.

I have failed attempt to create a tap using the formula, take a look:  lenlynch/homebrew-wireshark-1.12.9

I'm doing something wrong, the tap appears to clone inside of brew, but when I go to install it, the error is:  "No formulae found in taps."

`not-like-nonesuch:local lenlynch$ brew tap lenlynch/wireshark-1.12.3`
`==> Tapping lenlynch/wireshark-1.12.3`
`Cloning into '/usr/local/Library/Taps/lenlynch/homebrew-wireshark-1.12.3'...`
`remote: Counting objects: 5, done.`
`remote: Compressing objects: 100% (4/4), done.`
`remote: Total 5 (delta 0), reused 2 (delta 0), pack-reused 0`
`Unpacking objects: 100% (5/5), done.`
`Checking connectivity... done.`
`Tapped 1 formula (28 files, 25K)`
`not-like-nonesuch:local lenlynch$ brew tap`
`homebrew/boneyard`
`homebrew/versions`
`lenlynch/wireshark-1.12.3`
`not-like-nonesuch:local lenlynch$ brew untap lenlynch/wireshark-1.12.3`
`Untapping lenlynch/wireshark-1.12.3... (28 files, 25K)`
`Untapped 1 formula`
`not-like-nonesuch:local lenlynch$
`
Am I naming this OK? 

Thanks for the help!

**Comment by DomT4** [comment]
> Or am I making it more complicated than needed?

Kind of :).

We have a command already which throws out to `git log` in a way that's a bit simpler, presuming your Homebrew clone isn't shallow. `git log wireshark` will give you the logs for it, and given we use a fairly consistent commit message you can also do something like:
```
brew log wireshark --grep="1.12.3"
```
To find the specific commits tagged with that version.

> It looks like there should be a formula installed from the status messages?

The `tapped 1 formula` message is purely an informative step telling you the tap you've just tapped/untapped had x number of formulae installed, and the tap is using x amount of disk space.

> Am I naming this OK?

You _could_ keep the `wireshark` name but you're potentially making life more complicated for yourself than necessary by doing so. I'd probably name it something somewhat differently, perhaps with a version suffix.

**Comment by DomT4** [comment]
@mikemcquaid Filed https://github.com/Homebrew/homebrew/pull/48984. Don't know if it's entirely what you had in mind but let me know.
