### ISSUE TITLE
Emacs unable to open GUI

### ISSUE THREAD

**Issue by ethanluoyc** [Homebrew/homebrew#48875]
When I am installing emacs with `brew install emacs --with-coacoa`, I am unable to obtain an installation with support for the GUI. I checked the directory containing the installation and also cannot find the **Emacs.app** file.

Anyone has any idea why this is the case? I installed previously (but uninstalled it) but it does not seem to have this problem.

**Comment by dunn** [comment]
The command you're using has a typo; it should be `brew install emacs --with-cocoa` ('cocoa' rather than 'coacoa').

**Comment by ethanluoyc** [comment]
Omg I was totally beaten by my language. Correcting this works for me. Please consider this as a joke and close this issue.

**Comment by dunn** [comment]
No worries, glad it's working now!
