### ISSUE TITLE
yeti works with Java 8 now and has a new version

### ISSUE THREAD

**Issue by nikolay** [Homebrew/homebrew#48892]
I tried to install yeti and it complained about Java 7. Version 0.9.9.1, released in October 2015, supports the most recent Java 8.

http://mth.github.io/yeti/

**Comment by dunn** [comment]
Feel like opening a PR?  Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions!

**Comment by nikolay** [comment]
@dunn Thanks! I will!
