### ISSUE TITLE
Apache Spark 1.6.0 installation not runnable.

### ISSUE THREAD

**Issue by sid137** [Homebrew/homebrew#48898]
I've tried to download apache-spark, and have reproduced this error here:

http://stackoverflow.com/q/34624821/262972

On my own machine:  https://gist.github.com/70d88d67724b82545638

This is after removing and reinstalling apache-spark, and updating SPARK_HOME

Thanks

**Comment by DomT4** [comment]
That's odd. Works here on a machine that's never had `apache-spark` installed before. Have you tried passing `unset SPARK_HOME && spark-submit`?

**Comment by sid137** [comment]
Ah!  That fixes it...  ok, thank you!

**Comment by DomT4** [comment]
No worries! I believe `apache-spark` intelligently sets its own home if one isn't defined, so perhaps there's some issue there when one is set locally :confused:.

**Comment by ethanyxu** [comment]
I had the same issue. Fixed by unsetting SPARK_HOME.  Does it mean I cannot set `export SPARK_HOME` in my bash profile? This is a bit counter-intuitive.
