### ISSUE TITLE
octave: resolve "GraphicsMagick limits images to X bits per pixel" warning

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew#48909]
When I try to `imread()` a high quality .jpg, my brew-built octave complains

> warning: your version of GraphicsMagick limits images to 16 bits per pixel

Please `./configure --with-quantum-depth=32` when compiling graphicsmagick, so that it can handle rich images.

See http://wiki.octave.org/GraphicsMagick for more information.

**Comment by UniqMartin** [comment]
You can fix that yourself easily by rebuilding GraphicsMagick with `brew reinstall graphicsmagick --with-quantum-depth-32`. I'm not sure if it is feasible to change the default for all users of the `graphicsmagick` formula, as the higher bit depth certainly comes with more computational overhead and few applications actually need this. You can read some of the discussion in #46101, #46248, and #47014 that resulted in 16 bits being the default (was 8 bits before).

**Comment by DomT4** [comment]
Closing per the above. I believe QD16 is the default upstream, so it's possibly better to raise this with them if it's a common issue.
