### ISSUE TITLE
Installing two configurations of one formula side-by-side

### ISSUE THREAD

**Issue by RickyRomero** [Homebrew/homebrew#48902]
ffmpeg will not encode 10-bit video unless x264 is compiled with 10-bit support. But, it doesn't encode 8-bit video with 10-bit x264.  I don't want to lose the ability to encode 8-bit video.

This means that I need to have two copies of x264 installed, and switch between them using ffmpeg's `LD_LIBRARY_PATH` variable.

Ideally, what I'd like to do is have the vanilla 8-bit x264 be the canonical version (using `brew install x264`), but then have another version (`brew install x264 --with-10-bit`) with some unique name (like x264-10bit). brew would ideally know about both versions and would update both whenever I run `brew upgrade`.

I don't know how to accomplish this today, unless I missed something in the manual.

**Comment by tdsmith** [comment]
This isn't easy but one way to do this is to make a copy of the x264 formula with a different name; it might be easiest to set up a local tap, which is just a directory which is a git repository that contains a checked-in x264-10bit.rb. You can tap it like `brew tap myname/secondx264 ~/homebrew/my_x264_tap` and install your package like `brew install x264-10bit`.

**Comment by RickyRomero** [comment]
@tdsmith Thanks for the advice, I'll give that a try.

**Comment by retokromer** [comment]
If ffmpeg is linked to libx264 dynamically rather than statically, then it will adapt automatically to the bit depth supported by the run-time libx264, regardless of the version used at build time. This way it’s possible to work either 8-bit or 10-bit in each ffmpeg command, however you cannot combine 8-bit and 10-bit in the same command, you need two distinct commands.

**Comment by RickyRomero** [comment]
@retrokromer Yep, I'm trying to do that right now. (following [this advice on Stack Exchange](http://video.stackexchange.com/a/14594) under "Second Way")

**Comment by RickyRomero** [comment]
My solution to this problem is rather primitive, but it's easier to keep up to date than a tap.

    #!/bin/bash
    
    echo "----------------------------------------------------"
    echo "----------------------------------------------------"
    echo "-- Updating and upgrading brew... ------------------"
    echo "----------------------------------------------------"
    echo "----------------------------------------------------"
    brew update
    brew upgrade

    echo "----------------------------------------------------"
    echo "----------------------------------------------------"
    echo "-- Installing x264 10-bit... -----------------------"
    echo "----------------------------------------------------"
    echo "----------------------------------------------------"
    brew reinstall x264 --with-10-bit
    X264_PATH=`brew ls --verbose x264 | sed -n 1p | grep -o "/usr/local/Cellar/x264/[^/]*/"`
    cp -R $X264_PATH* /usr/local/lib/x264-10-bit

    echo "----------------------------------------------------"
    echo "----------------------------------------------------"
    echo "-- Reinstalling vanilla x264... --------------------"
    echo "----------------------------------------------------"
    echo "----------------------------------------------------"
    brew reinstall x264

    echo "----------------------------------------------------"
    echo "----------------------------------------------------"
    echo "-- Installing x265 16-bit... -----------------------"
    echo "----------------------------------------------------"
    echo "----------------------------------------------------"
    brew reinstall x265 --with-16-bit
    X265_PATH=`brew ls --verbose x265 | sed -n 1p | grep -o "/usr/local/Cellar/x265/[^/]*/"`
    cp -R $X265_PATH* /usr/local/lib/x265-10-bit

    echo "----------------------------------------------------"
    echo "----------------------------------------------------"
    echo "-- Reinstalling vanilla x265... --------------------"
    echo "----------------------------------------------------"
    echo "----------------------------------------------------"
    brew reinstall x265

**Comment by DomT4** [comment]
Let us know if there's anything we can practically do to help further here, Thanks! :smiley:

**Comment by ReaddyEddy** [comment]
The script above fails.
