### ISSUE TITLE
-bash: /usr/local/bin/brew: /bin/bash^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by Brendtos** [Homebrew/homebrew#48924]
Running any 'brew' command in Terminal on my Mac (running OS X El Capitan) resulted in:
-bash: /usr/local/bin/brew: /bin/bash^M: bad interpreter: No such file or directory

Most of the information related to 'bad interpreter: No such file or directory' around is in relation to Ruby and it's location on Yosemite and El Capitan. 

However, after banging my head against the wall I opened my eyes and actually looked at the error (4am can provide that sort of clarity at times).

Ended up installing MacPorts, then dos2unix and ran
dos2unix /usr/local/bin/brew
This resolved the issue. (I then un-installed MacPorts of course)

Seems to me like /usr/local/bin/brew has been edited and some bad characters have been pushed.

**Comment by ilovezfs** [comment]
@Brendtos nope, sorry
```
bash-3.2$ cd /usr/local
bash-3.2$ git diff --name-only
bash-3.2$ cat -etv bin/brew | head -1
#!/bin/bash$
bash-3.2$ unix2dos bin/brew
unix2dos: converting file bin/brew to DOS format...
bash-3.2$ git diff --name-only
bin/brew
bash-3.2$ cat -etv bin/brew | head -1
#!/bin/bash^M$
bash-3.2$ dos2unix bin/brew
dos2unix: converting file bin/brew to Unix format...
bash-3.2$ cat -etv bin/brew | head -1
#!/bin/bash$
bash-3.2$ git diff --name-only
bash-3.2$ git blame bin/brew|head -1
12e4cbc6 (Mike McQuaid     2015-12-25 22:42:32 +0000   1) #!/bin/bash
bash-3.2$ git reset --hard 12e4cbc6^
HEAD is now at 390e327 bin/brew: set more HOMEBREW_* env from Bash.
bash-3.2$ cat -etv bin/brew | head -1
#!/bin/sh$
bash-3.2$ git reset --hard 12e4cbc6
HEAD is now at 12e4cbc bin/brew: allow writing Homebrew commands in Bash.
bash-3.2$ cat -etv bin/brew | head -1
#!/bin/bash$
bash-3.2$ git reset --hard @{u}
HEAD is now at c3438ae tmux: remove examples directory from HEAD install
bash-3.2$ cat -etv bin/brew | head -1
#!/bin/bash$
bash-3.2$
```

**Comment by mikemcquaid** [comment]
@Brendtos Try to `cd /usr/local; git fetch; git reset --hard origin/master`

**Comment by Brendtos** [comment]
@mikemcquaid yep tried all that to no avail. This is why I thought the bad characters must have been pushed to the repo. @ilovevfs has show about that this is not the case. 

Probably worth closing this issue if there's no problem in the repo. I was just trying the help others avoid the pain I went through.

**Comment by mikemcquaid** [comment]
Yeh, no problem with the repo. Sorry!

**Comment by DomT4** [comment]
Someone reported the exact same core issue over at https://github.com/Homebrew/install/issues/35. Slightly odd. Was a root cause found in the end here?

**Comment by ilovezfs** [comment]
Well it would be interesting to know if their local "git diff" shows the change and what version of git they're using. Also, I'm wondering if this has to do with git crlf settings, with possibly a local configuration problem on the user's machine.

Another question is whether these are brand new installations and there's something wrong with the tarball(s) or the way they're getting unpacked.

**Comment by ilovezfs** [comment]
Tarball is fine.
bash-3.2$ cat -tev bin/brew | head -1
#!/bin/bash$

**Comment by brunoamorim13** [comment]
I'm the author of the [Homebrew/install#35](https://github.com/Homebrew/install/issues/35), and I did the same thing as @Brendtos , installed macports, with is installed dos2unix and it worked. I don't know what It could've been. Thanks for the help!

**Comment by ilovezfs** [comment]
@Brendtos Any chance you also have a global crlf setting? Do you mind running these commands:
https://github.com/Homebrew/install/issues/35#issuecomment-183922216

**Comment by Brendtos** [comment]
@ilovezfs sure, please see below:

brendt$ git config --global -l | grep crlf
core.autocrlf=input
brendt$ cd /usr/local ; git config -l | grep crlf
core.autocrlf=input
