### ISSUE TITLE
deps doesn't work on Caskroom/...

### ISSUE THREAD

**Issue by pennello** [Homebrew/homebrew#48949]
Is this expected not to work?

    % brew deps Caskroom/cask/java
    Error: undefined method `map' for nil:NilClass
    Please report this bug:
        https://git.io/brew-troubleshooting
    /usr/local/Library/Homebrew/cmd/deps.rb:28:in `deps'
    /usr/local/Library/brew.rb:85:in `<main>'

At the very least, it probably shouldn't throw an un-handled error.

Here's my `brew config`.

    HOMEBREW_VERSION: 0.9.5
    ORIGIN: https://github.com/Homebrew/homebrew
    HEAD: b369c25d3ec6dcaaed86c2d05364ae1ca80786f4
    Last commit: 8 hours ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_REPOSITORY: /usr/local
    HOMEBREW_CELLAR: /usr/local/Cellar
    HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
    CPU: 12-core 64-bit ivybridge
    OS X: 10.11.3-x86_64
    Xcode: N/A
    CLT: 7.2.0.0.1.1447826929
    Clang: 7.0 build 700
    X11: N/A
    System Ruby: 2.0.0-p645
    Perl: /usr/bin/perl
    Python: /usr/bin/python
    Ruby: /usr/bin/ruby =>
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
    Java: N/A

**Comment by ilovezfs** [comment]
@pennello No it doesn't handle casks. Here's a fix #49063

**Comment by DomT4** [comment]
Closing in favour of https://github.com/Homebrew/homebrew/pull/49063. @AnastasiaSulyagina may potentially be interested in this issue given https://github.com/Homebrew/Outreachy-and-Google-Summer-of-Code/issues/6.
