### ISSUE TITLE
bup fails to install

### ISSUE THREAD

**Issue by PeterPablo** [Homebrew/homebrew#48950]
Possibly related issue: https://github.com/Homebrew/homebrew/issues/42375

```
peterpablo@PeterPablo:~$ brew install -s bup
==> Downloading https://github.com/bup/bup/archive/0.27.tar.gz
Already downloaded: /Library/Caches/Homebrew/bup-0.27.tar.gz
==> make
Last 15 lines from /Users/peterpablo/Library/Logs/Homebrew/bup/01.make:
ln -s tick-cmd.py cmd/bup-tick
rm -f cmd/bup-version
rm -f cmd/bup-web
rm -f cmd/bup-xstat
ln -s version-cmd.py cmd/bup-version
ln -s web-cmd.py cmd/bup-web
ln -s xstat-cmd.py cmd/bup-xstat
rm -f cmd/bup-import-rdiff-backup
rm -f cmd/bup-import-rsnapshot
t/configure-sampledata --setup
ln -s import-rdiff-backup-cmd.sh cmd/bup-import-rdiff-backup
ln -s import-rsnapshot-cmd.sh cmd/bup-import-rsnapshot
 (can't run cpp as a pipeline)
make[1]: *** [config.h] Error 1
make: *** [config/config.h] Error 2
```

Here the requested [GIST](https://gist.github.com/anonymous/b891f6e89fb7ce1a26f5).

**Comment by DomT4** [comment]
I added a bottle for 10.11.x in https://github.com/Homebrew/homebrew/commit/b1b396c8184abb7a0c524fa16dd3f71c5b9ef99d. Does `brew update && brew install bup` produce a package that behaves as expected for you?

**Comment by DomT4** [comment]
Let me know if we can help further here, Thanks!

**Comment by PeterPablo** [comment]
I just tested this and now installation worked without a problem. Thank you @DomT4!

**Comment by leewalsh** [comment]
Is there any way to install bup with documentation without building bup? I can install the bottle just fine, but there are no man pages:

    leewalsh@warbler ~> bup help save
    No manual entry for bup-save
    leewalsh@warbler ~ [1]> man bup
    No manual entry for bup

I see there is an option `--with-pandoc`, but that seems to imply building bup, which fails in a (maybe) similar fashion as in @PeterPablo's post, with the "can't run cpp as a pipeline" error. Is there any way to install the man pages with the bottle? I really don't care about building bup, but having the help at my fingertips would be nice. If I can figure out how to do it, I'd be happy to add it to the formula.

Here's the output, and [logs gist](https://gist.github.com/23a9b73c780429d27f3d):

    leewalsh@warbler ~ [1]> brew remove bup
    Uninstalling /usr/local/Cellar/bup/0.27... (67 files, 469.6K)
    leewalsh@warbler ~> brew install --with-pandoc bup
    ==> Downloading https://github.com/bup/bup/archive/0.27.tar.gz
    Already downloaded: /Library/Caches/Homebrew/bup-0.27.tar.gz
    ==> make
    Last 15 lines from /Users/leewalsh/Library/Logs/Homebrew/bup/01.make:
    ln -s tick-cmd.py cmd/bup-tick
    rm -f cmd/bup-web
    ln -s version-cmd.py cmd/bup-version
    rm -f cmd/bup-xstat
    ln -s web-cmd.py cmd/bup-web
    rm -f cmd/bup-import-rdiff-backup
    ln -s xstat-cmd.py cmd/bup-xstat
    rm -f cmd/bup-import-rsnapshot
    ln -s import-rdiff-backup-cmd.sh cmd/bup-import-rdiff-backup
    t/configure-sampledata --setup
    ln -s import-rsnapshot-cmd.sh cmd/bup-import-rsnapshot
    Configuring for [bup]
    Looking for cpp (/usr/local/Library/ENV/4.3/cpp) (can't run cpp as a pipeline)
    make[1]: *** [config.h] Error 1
    make: *** [config/config.h] Error 2

**Comment by DomT4** [comment]
> Is there any way to install bup with documentation without building bup?

No. We don't really support the option where people don't want the tool installed but want the documentation for it because it's a little niche.

> Configuring for [bup]
Looking for cpp (/usr/local/Library/ENV/4.3/cpp) (can't run cpp as a pipeline)

We've run into this a few times but I can't reproduce locally and I can't recall that we've ever been able to narrow down a reproducible case in every circumstance. A full `brew gist-logs bup` may be helpful there.

**Comment by leewalsh** [comment]
Thanks for your reply @DomT4 !

> > Is there any way to install bup with documentation without building bup?

> No. We don't really support the option where people don't want the tool installed but want the documentation for it because it's a little niche.

I meant installing the docs alongside using a bottle ... I do want the tool installed :) It seems other bottled formulae come with man pages.. e.g.:

    leewalsh@warbler ~> brew info git
    git: stable 2.7.1 (bottled), HEAD
    ...
    /usr/local/Cellar/git/2.7.1 (1,408 files, 236.3M) *
      Poured from bottle
    leewalsh@warbler ~> brew list git
    ...
    /usr/local/Cellar/git/2.7.1/share/man/ (178 files)

If it's easy to add this to bottles, I would be interested in contributing that to bup. Otherwise I will try just manually copying the bup man pages into my own manpath.

> We've run into this a few times but I can't reproduce locally and I can't recall that we've ever been able to narrow down a reproducible case in every circumstance. A full `brew gist-logs bup` may be helpful there.

I can't find any more logs than what I posted originally. I ran it again as `brew gist-logs -v bup` but the output looks the same, and `gist-logs` is not covered in `man brew`. Is there more I can do to help/investigate?
