### ISSUE TITLE
Issue installing Wine with homebrew

### ISSUE THREAD

**Issue by dcpmd08** [Homebrew/homebrew#48961]
This is what terminal is telling me after the $ brew install wine 

==> Installing dependencies for wine: fontconfig, libtiff, gd, libgphoto2
==> Installing wine dependency: fontconfig
==> Downloading http://fontconfig.org/release/fontconfig-2.11.1.tar.bz2
==> Downloading from https://fontconfig.org/release/fontconfig-2.11.1.tar.bz2

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "fontconfig"
Download failed: https://fontconfig.org/release/fontconfig-2.11.1.tar.bz2

**Comment by dcpmd08** [comment]
So I followed another option I found on a related issue about permissions so I fixed the certificate for the SSL error I was getting now I'm getting this 
Donovans-MacBook-Pro:~ GraphicDesign$ brew install wine
==> Installing dependencies for wine: fontconfig, libtiff, gd, libgphoto2
==> Installing wine dependency: fontconfig
==> Downloading http://fontconfig.org/release/fontconfig-2.11.1.tar.bz2
==> Downloading from https://fontconfig.org/release/fontconfig-2.11.1.tar.bz2

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "fontconfig"
Download failed: https://fontconfig.org/release/fontconfig-2.11.1.tar.bz2
Donovans-MacBook-Pro:~ GraphicDesign$

**Comment by Slugger70** [comment]
It looks like fontconfig-2.11.1.tar.bz2 has been deleted off the fontconfig website. The fontconfig formula points explicitly to http://fontconfig.org/release/fontconfig-2.11.1.tar.bz2

I'm having the same trouble with fontconfig but with a different package.. (ImageMagick)

**Comment by tseemann** [comment]
It seems there is no `release

**Comment by tseemann** [comment]
This source may be better: https://www.freedesktop.org/software/fontconfig/release/

**Comment by NoahYarian** [comment]
I've gotten past it, but I need to piece together what exactly fixed it, because it was more than the 404 for me. 
To fix the bad link:
- I changed line 4 of /usr/local/Library/Formula/fontconfig.rb to `url "https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.11.1.tar.bz2"`
- this may also be helpful [http://mygeekdaddy.net/2014/12/05/how-to-install-a-local-file-in-homebrew/](url)

Beyond that I think maybe comment out 17-21 because that was the most recent commit. I did and it at least didn't break anything for me. 

Other thoughts I've had:
?? - go in font book and restore standard fonts. I did, and i read in an issue that having another subfolder in font book will cause it to fail, and i had one. I think if this is a problem the next line will fix it:

In fontconfig.rb on line 48 I think `  def post_install
    system "#{bin}/fc-cache", "-frv"
  end` can be changed to `  def post_install
  end`
There's a commit that was reversed that took that line out in the past I believe.

I'll look into this again tomorrow when I can.

**Comment by NoahYarian** [comment]
I went through a few things, so maybe this will help someone before I get back:

  515  wine
  516  brew install wine
  517  brew install fontconfig
  518  brew install fontconfig --insecure
  519  brew postinstall fontconfig
  520  brew uninstall fontconfig --insecure
  521  brew install fontconfig --insecure
  522  brew install wine
  523  brew install wine -k
  524  brew update
  525  sudo chown -R $(whoami):admin /usr/local
  526  brew update
  527  brew install wine
  528  brew install wine -k
  529  brew
  530  brew doctor
  531  brew install wine -k
  532  brew install -vd wine
  533  brew
  534  brew info fontconfig
  535  brew edit fontconfig
  536  brew install -vd wine
  537  brew install fontconfig -k
  538  brew uninstall fontconfig
  539  brew install fontconfig -k
  540  brew install wine
  541  brew uninstall fontconfig --force
  542  brew link
  543  brew 
  544  brew edit fontconfig
  545  code
  546  git clone http://anongit.freedesktop.org/git/fontconfig
  547  cd fontconfig/
  548  subl .
  549  ~
  550  cd Downloads/
  551  ls
  552  ls -la
  553  md5sum fontconfig-2.11.1.tar.bz2
  554  brew install md5sha1sum
  555  md5sum fontconfig-2.11.1.tar.bz2
  556  brew edit fontconfig
  557  shasum -a 256 fontconfig-2.11.1.tar.bz2
  558  cd /usr/local/Library/
  559  ls
  560  cd Taps/
  561  ls
  562  cd caskroom/
  563  ls
  564  cd homebrew-cask/
  565  ls
  566  b
  567  b
  568  b
  569  ls
  570  b
  571  cd Library/
  572  ls
  573  cd Formula/
  574  ls
  575  b
  576  tree
  577  ls
  578  cd LinkedKegs/
  579  ls
  580  b
  581  cd Taps/
  582  ls
  583  cd cas
  584  cd caskroom/
  585  tree
  586  brew --cache
  587  cd $(brew --cache)
  588  ls
  589  ls -la
  590  cd Formula/
  591  ls
  592  subl fontconfig.brewing 
  593  ls -la
  594  b
  595  o .
  596  open .
  597  brew info fontconfig
  598  brew config fontconfig
  599  brew reinstall --build-from-source fontconfig
  600  brew reinstall --build-from-source fontconfig -vd
  601  brew uninstall fontconfig --force
  602  brew link
  603  man brew
  604  brew outdated
  605  brew upgrade
  606  brew cleanup
  607  brew outdated
  608  brew edit fontconfig
  609  brew uninstall fontconfig --force
  610  brew install fontconfig
  611  brew postinstall fontconfig
  612  brew
  613  brew info fontconfig
  614  brew info fontconfig
  615  open /usr/local/Cellar/fontconfig/2.11.1_1
  616  brew options fontconfig
  617  brew install fontconfig
  618  brew uninstall fontconfig --force
  619  brew install fontconfig -vd
  620  brew install wine -vd
  621  brew install fontconfig -vd
  622  brew uninstall fontconfig
  623  brew install fontconfig -vd
  624  fontconfig
  625  brew install wine -vd
  626  brew install wine
  627  brew install winetricks
  628  wine
  629  fontconfig
  630  brew info fontconfig
  631  history

**Comment by NoahYarian** [comment]
I was able to brew install wine on another system without the same issues, so I'm not going to worry about figuring out those other issues I was having. I still had to edit the url in /usr/local/Library/Formula/fontconfig.rb, but that's it. Cheers!

**Comment by DomT4** [comment]
Should be fixed via https://github.com/Homebrew/homebrew/commit/c560fc84ef65dbaf4a532ac7a3fa2c27fc7c0793.
