### ISSUE TITLE
Improve zsh completions

### ISSUE THREAD

**Issue by alias1** [Homebrew/homebrew#48988]
With brew cask being rolled into the core setup now, it would be cool to have the [zsh completion](https://github.com/Homebrew/homebrew/blob/master/Library/Contributions/brew_zsh_completion.zsh) include it.

A (probably outdated, 2014) example can be seen at [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/brew-cask/brew-cask.plugin.zsh)

It would also be useful to somehow use LISTMAX ([ref](http://bolyai.cs.elte.hu/zsh-manual/zsh_15.html)) to avoid the `zsh: do you wish to see all 128 possibilities (61 lines)? ` message when autocompleting `brew `

**Comment by UniqMartin** [comment]
Unfortunately, our official `zsh` completions for `brew` tend to stay behind the development of Homebrew and behind what our `bash` completions have to offer. If you're passionate about them, we'd gladly welcome PRs that improve our `zsh` completions.

**Comment by DomT4** [comment]
Closing per the above. PRs welcome, always :smile:.
