### ISSUE TITLE
Is it possible to use third-party gems in a formula?

### ISSUE THREAD

**Issue by jacob-meacham** [Homebrew/homebrew#48989]
I manage a private tap that has a few formulae (which are really only useful internally). As part of this, I hook into Homebrew::Hooks::Bottles to download bottles from a github repo. Since downloading bottles from (potentially private) github repos seems useful, I'd like to pull it out as an open-source gem. 

However, it doesn't seem like homebrew has a simple way of installing third-party gems to be used within a formula. Is this possible?

Thanks in advance!

**Comment by mikemcquaid** [comment]
It is not possible, sorry.

**Comment by jacob-meacham** [comment]
Thanks!
