### ISSUE TITLE
Error: undefined method `new' for Patch:Module when running "brew update" on OSX El Capitan

### ISSUE THREAD

**Issue by ScottSedgwick** [Homebrew/homebrew#48985]
Here is the stack trace that brew requested I submit:

scotts-mbp:Library Scott$ brew update
Checking out files: 100% (3619/3619), done.
Error: undefined method `new' for Patch:Module
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/patch.rb:115:in `initialize'
/usr/local/Library/Homebrew/patch.rb:18:in `new'
/usr/local/Library/Homebrew/patch.rb:18:in `create'
/usr/local/Library/Homebrew/software_spec.rb:168:in `patch'
/usr/local/Library/Homebrew/formula.rb:1910:in `block in patch'
/usr/local/Library/Homebrew/formula.rb:1910:in `each'
/usr/local/Library/Homebrew/formula.rb:1910:in `patch'
/usr/local/Library/Formula/a2ps.rb:19:in `<class:A2ps>'
/usr/local/Library/Formula/a2ps.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:85:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:76:in `klass'
/usr/local/Library/Homebrew/formulary.rb:72:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:173:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:140:in `<main>'
scotts-mbp:Library Scott$ brew update
Already up-to-date.

**Comment by DomT4** [comment]
Had it been a fair while since you'd previously ran `brew update` by any chance?

**Comment by ScottSedgwick** [comment]
Successfully, yes.  Unsuccessfully, no.  I've tried to run it several times
since installing the El Capitan update, even in the last few days.

I have resolved my problem in the last hour, BTW.  I fixed the permissions
on my /usr/local directory as shown in this blog:

https://ohthehugemanatee.org/blog/2015/10/01/how-i-got-el-capitain-working-with-my-developer-tools/

Which didn't do the job - I then did a "git stash" on my
/usr/local/Library directory, ran "brew update" twice - both times failing
- then "brew doctor", and forced the brew link on a few packages, followed
by "brew install hicolor-icon-theme" - oh, and I updated my XQuartz library.

Those may not have happened in exactly that order.

At the end of all that, "brew update" works again.

Thanks,


Scott.

**Comment by DomT4** [comment]
Aye, I suspect that'll be it. Unless it persists across other `brew update`s I wouldn't worry about it. Thanks for the report!

**Comment by MappingKat** [comment]
I also recieved this error and will use `brew doctor` to hopefully fix... Just thought I would pop it in here. 

```
Error: undefined method `new' for Patch:Module
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/patch.rb:115:in `initialize'
/usr/local/Library/Homebrew/patch.rb:18:in `new'
/usr/local/Library/Homebrew/patch.rb:18:in `create'
/usr/local/Library/Homebrew/software_spec.rb:168:in `patch'
/usr/local/Library/Homebrew/formula.rb:1910:in `block in patch'
/usr/local/Library/Homebrew/formula.rb:1910:in `each'
/usr/local/Library/Homebrew/formula.rb:1910:in `patch'
/usr/local/Library/Formula/a2ps.rb:19:in `<class:A2ps>'
/usr/local/Library/Formula/a2ps.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:85:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:76:in `klass'
/usr/local/Library/Homebrew/formulary.rb:72:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:173:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:140:in `<main>'
________________________________________________________________________________
```

**Comment by DomT4** [comment]
Same comment re `brew update`. Wouldn't worry about it unless it reproduces.
