### ISSUE TITLE
svn: The build tool has reset ENV; --env=std required.

### ISSUE THREAD

**Issue by fdagnat** [Homebrew/homebrew#49001]
Hello, since last xcode update (7.2.1), I cannot use anymore my brew installed subversion. svn --status reply svn: The build tool has reset ENV; --env=std required.

I tried reinstalling subversion (even reinstalling from the sources). When I remove brew subversion and  the system svn works like a charm but I would like to use a more recent svn...

I've not found much information on google about this error message but it seems related to brew. When I use brew doctor, it only complains about some other lib it does not know are installed in /usr/local/lib (which is normal as I sometimes build lib out of brew).

Does anyone as an idea about what's going on and how to solve the issue?

**Comment by UniqMartin** [comment]
I suspect there's something wrong with your `PATH`. Can you please post the output of `echo "[$PATH]"`?

**Comment by fdagnat** [comment]
Just an add-on the problem is not coming from the brew svn but from the brew colorsvn

**Comment by fdagnat** [comment]
/Users/fdagnat/.opam/system/bin:/usr/local/sbin:/usr/local/bin:/Users/fdagnat/SVN/ens/utils/scripts:/Users/fdagnat/bin:/usr/local/bin:/Users/fdagnat/SVN/ens/utils/scripts:/Users/fdagnat/bin:/usr/texbin:/usr/local/scala/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin

**Comment by UniqMartin** [comment]
> Just an add-on the problem is not coming from the brew svn but from the brew colorsvn

This is crucial information! Unfortunately, `colorsvn` picks up our `svn` wrapper from the Homebrew build environment which is not supposed to be used outside of it. Thanks for the report, @fdagnat!

I'll try to prepare a fix for the `colorsvn` formula shortly, but until then you can work around the issue by editing the `/usr/local/etc/colorsvnrc` file (or the user-specific `~/.colorsvnrc` if it exists) and changing the line starting with `svn: ` to the `svn` binary you'd like to use.

**Comment by ntwb** [comment]
Likewise I just ran into this issue this morning here, I've used @UniqMartin's work around and works perfectly, if theres anything I can help test let me know.

**Comment by fdagnat** [comment]
the work around also worked for me, thanks.

**Comment by UniqMartin** [comment]
The issue should be resolved after running `brew update` and then `brew upgrade colorsvn`. However, it will now always default to the system-provided Subversion (`/usr/bin/svn`) and if you want to use a different one with `colorsvn` (e.g., the Subversion provided by Homebrew), you will have to adjust the configuration file as suggested in the workaround above.
