### ISSUE TITLE
Dead symlinks are breaking bottle creation (brew bottle cmd) again

### ISSUE THREAD

**Issue by chrmoritz** [Homebrew/homebrew#49007]
Refs: https://github.com/Homebrew/homebrew-versions/pull/1156#issuecomment-182001773

The underlying issues was originally fixed by https://github.com/Homebrew/homebrew/commit/8ed04288cb398d979b814a4dcb2b9852c4e4d360 but was later completely removed/replaced in https://github.com/Homebrew/homebrew/commit/4a819003df66546661637d7773eb791c774b3b59 to read source modified time from tabfile with `tab.source_modified_time`. 
But it looks like `tab.source_modified_time` isn't handling dead symlinks well enough and is breaking bottle creation with dead symlinks as seen in this build failure: 
http://bot.brew.sh/job/Homebrew%20Versions%20Pull%20Requests/1234/ *(npm installs dead symlinks to the at the point of `brew bottle` already deleted buildpath in `libexec/npm/share/`, the real manpages are in `libexec/npm/lib/node_modules/npm/man/` see: https://github.com/Homebrew/homebrew/pull/47081#issuecomment-165280470)*

It's completely workaroundable by removing these dead symlinks before bottle creation, but ideally the bottle command should handle broken symlinks.

**Comment by UniqMartin** [comment]
Thanks for the report @chrmoritz! There was a subtle change during the rewrite of the code in #48068, that is probably responsible for this regression:

- Old (4a819003df66546661637d7773eb791c774b3b59): `pathname.to_enum(:find).select(&:exist?).map(&:mtime).max`
- New (8feb6b3e13dcedf69ff5c75849021a56fcd0d506): `Pathname.pwd.to_enum(:find).select(&:file?).map(&:mtime).max`

@xu-cheng, any comments? I don't want to blindly stomp over your changes here, but I guess we want to have both the `exist?` and the `file?` check?

**Comment by xu-cheng** [comment]
I think this is unrelated with `tab.source_modified_time` because it's computed during `brew install` not `brew bottle`. Also, `File#file?` will check whether it's `exist?`.

**Comment by UniqMartin** [comment]
> I think this is unrelated with `tab.source_modified_time` because it's computed during `brew install` not `brew bottle`. Also, `Pathname#file?` will check whether it's `exist?`.

You're right; sorry! Thanks for taking a proper look at this (unlike my hasty late night analysis) and for quickly coming up with an actual fix! :heart:

**Comment by mikemcquaid** [comment]
Would be good to add a test to verify we don't regress on this again whenever this is fixed.
