### ISSUE TITLE
NodeJS Security Release

### ISSUE THREAD

**Issue by connorshea** [Homebrew/homebrew#49014]
Homebrew currently ships Node 5.5.0. 5.6.0 is the Stable build that includes the security fixes.

Source: https://nodejs.org/en/blog/vulnerability/february-2016-security-releases/

**Comment by DomT4** [comment]
Please check open PRs before filing Issues. There's a Node update pending already :wink: - https://github.com/Homebrew/homebrew/pull/49004. It'll be merged as soon as possible.
