### ISSUE TITLE
Is it possible to specify exact versions of dependent formula?

### ISSUE THREAD

**Issue by febbraro** [Homebrew/homebrew#49012]
I am writing a formula for a Tap I'll be maintaining.  I have some very specific versions that I need to peg to my formula dependencies.  

As an example, my command needs docker 1.9.1 specifically. Nothing lower, nothing greater and this will change likely with each update we would increment versions, etc.

Is there anyway to do this? or must I enforce this from within my command?

Thanks so much for any guidance, I can't find any indication of this in the docs.

**Comment by dunn** [comment]
Currently there's not.  In your case I'd recommended vendoring Docker 1.9.1 in your formula as a `resource`.  UpscaleDB's use of an older libuv is a good example of how to do this: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/upscaledb.rb#L32-L66

**Comment by febbraro** [comment]
Thanks a lot for the insight and example.
