### ISSUE TITLE
Brew install results in "invalid certificate chain" on mac

### ISSUE THREAD

**Issue by thejeff77** [Homebrew/homebrew#49039]
Hey guys, this is definitely still an issue. I've tried everything on the other threads. I get a certificate chain error when running brew install:

My "DigiCert High Assurance EV Root CA" is not expired, and I can clone anything via git (in case you were wondering), nevertheless it still doesn't work and I've tried the things below:

- I've also tried adding that cert to the "System" keychain as recommended by : alexkravets

- I've tried manually downloading that cert and re-adding to my keychain.

- The quick fix suggested by jmlane doesn't work because there is no /usr/share/curl directory on my mac, although I have curl.

- The "-k" and "--insecure" flag don't work through brew to ignore cert issues when brew uses curl to download things. Ex: "brew install -k imagemagick"

- I've tried adding all certificates from the digicert site: https://www.digicert.com/digicert-root-certificates.htm

- "brew doctor" says "Your system is ready to brew"

- I have the latest version of brew 0.9.5

None of this works - here is a sample output for the error:

`$ brew install sdl2
==> Downloading https://homebrew.bintray.com/bottles/sdl2-2.0.4.el_capitan.bottle.tar.gz

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "sdl2"
Download failed: https://homebrew.bintray.com/bottles/sdl2-2.0.4.el_capitan.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://libsdl.org/release/SDL2-2.0.4.tar.gz

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "sdl2"
Download failed: https://libsdl.org/release/SDL2-2.0.4.tar.gz`

My "DigiCert High Assurance EV Root CA" is not expired.

I've also tried adding that cert to the "System" keychain as recommended by : alexkravets

**Comment by DomT4** [comment]
What's your `brew config`? Are either `SSL_CERT_DIR` and `SSL_CERT_FILE` set in your `env`?

**Comment by thejeff77** [comment]
Here is my brew config:

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: c0fe6fc0d82f09206f67d9b7147e7398cfcd4611
Last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.11.3-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
Clang: 7.0 build 700
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A

**Comment by thejeff77** [comment]
Ok, so my coworker suggested that I switch to wifi because our LAN is pretty locked down. It worked, even though I can get everything else to work on the lan (GIT, curl, etc..)

I don't understand how a different network would cause invalid certificate chain issues to go away. 

If it's ok - I'd kind of like to fix the brew issue on the LAN via this thread in case anyone else has a similar issue.

And why doesn't the "-k" option work with brew as noted in the other threads?

**Comment by DomT4** [comment]
Is your LAN ran through some kind of proxy by any chance? Restrictive proxies/firewalls are known to cause problems.

> And why doesn't the "-k" option work with brew as noted in the other threads?

We keep our curl handling consistent because it allows us to debug most things without trying to work out the potential impact of every user variable passed. Also: letting users ignore security warnings would be problematic, because a high percentage of people would without considering potential consequences.

**Comment by thejeff77** [comment]
I am definitely going through a proxy. -- If that indeed is the issue, seems like brew may have some proxy bugs.

**Comment by apjanke** [comment]
Sounds like your proxy may be rewriting certificate chains, possibly using a corporate-supplied certificate that is not included in the default root certificates supplied by Apple with OS X, or with whatever trust store we're using with `curl`. This happens in some corporate environments. Effectively, it is performing a man-in-the-middle attack on you, and `curl` is detecting it.

Is this Mac you're running Homebrew on managed by your work's IT department?

Try downloading https://homebrew.bintray.com/bottles/sdl2-2.0.4.el_capitan.bottle.tar.gz in a browser that's been set up to work on your LAN and examine the certificate chain there. See what the root certificates are. If you have a company-issued root CA there that isn't part of the standard trust store that `curl` is using, you may need to add it. (If you actually trust whoever's managing it.) Or just stick with using the wifi.

**Comment by mikemcquaid** [comment]
Agreed with @apjanke; your proxy has an issue, not Homebrew.
