### ISSUE TITLE
`.app` created by `brew linkapps` can't be indexed by Spotlight Search?

### ISSUE THREAD

**Issue by hanfeisun** [Homebrew/homebrew#49033]
Recently I installed `emacs-mac` using the following commands by brew:

```
brew tap railwaycat/homebrew-emacsmacport
brew install emacs-mac --with-spacemacs-icon  # OR, brew cask install emacs-mac
brew linkapps
```

After `brew linkapps`, an Alias file called `Emacs` appeared in `/Applications/` folder. However, I find that it cannot be index/open by the Spotlight Search function in OSX 10.11

I find two StackExchange threads about this issue:

1. http://apple.stackexchange.com/questions/95906/does-spotlight-normally-index-links-in-applications
2. http://apple.stackexchange.com/questions/23653/can-i-make-a-symlink-to-a-app-folder-in-applications-directory-show-up-in-spo

However, the solutions mentioned in the thread looks quite hacky/clumsy..

Is it possible for the alias file created by `brew linkapps` be indexed by Spotlight Search?

**Comment by dunn** [comment]
This has come up before; see #4635 and #28798, among others.

**Comment by DomT4** [comment]
We'll take a PR to review on any possible and reasonable solution but at the moment the maintainer team has no dedicated plans to work on this ourselves. `brew linkapps` is semi-problematic and none of the solutions proposed to date have resolved that, sadly.
