### ISSUE TITLE
Update htop-osx to Htop 2

### ISSUE THREAD

**Issue by ifonefox** [Homebrew/homebrew#49054]
[Htop 2](http://hisham.hm/htop/) now supports OS X. Would it be possible to replace the port with the official version?

**Comment by azag0** [comment]
Meanwhile, this works just fine on my machine:

```sh
wget http://hisham.hm/htop/releases/2.0.0/htop-2.0.0.tar.gz
tar -xf htop-2.0.0.tar.gz
cd htop-2.0.0
./configure --prefix=/usr/local/Cellar/htop/2.0.0 && make && make install && brew link htop
```

**Comment by OJFord** [comment]
Ideally also rename to `htop`, and remove the alias. (Or reverse the alias, I suppose).

**Comment by gawbul** [comment]
Glad to see this already here. Was just about to suggest this change myself. :+1:

**Comment by joaomoreno** [comment]
:+1:

**Comment by UniqMartin** [comment]
Closing in favor of #49057.
