### ISSUE TITLE
Telepathy devel versions.

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew#49052]
A couple of the Telepathy formulae:
* telepathy-gabble
* telepathy-glib

Were moved onto what seem to be development releases in November with:
* b66d6921df7ca6ad5f4e5008382d17adcbbb7427
* 8ec3cd94bb46ad16fb7613f43f3017577ecb33ff

This is currently breaking:
* telepathy-mission-control
* telepathy-idle

This wasn't detected at the time, possibly because there are no tests on those formulae, but trying to compile them throws this sort of error:
```
configure: error: Package requirements (telepathy-glib >= 0.20.0) were not met:

No package 'telepathy-glib' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
```

Our options are kind of limited:
* We do a revert and leave people who upgraded to the development versions stuck there indefinitely because a stable release above `0.99.x` is unlikely in the medium-term; so far upstream has largely followed the pattern of one stable release per year going from i.e. `0.22.0` to `0.24.0`.

* We scrap all these Telepathy formulae because nobody has reported them broken in nearly 3 months. According to Bintray since `telepathy-glib` was upgraded to a development version about 50 people have downloaded a bottle and `telepathy-gabble` has been downloaded 19 times.

**Comment by mikemcquaid** [comment]
> We do a revert and leave people who upgraded to the development versions stuck there indefinitely because a stable release above 0.99.x is unlikely in the medium-term

That seems to me the best for now :+1:

**Comment by UniqMartin** [comment]
Too bad those version bumps slipped through, but I agree with Mike. Probably the best we can do.
