### ISSUE TITLE
Disable bottle entirely in formula?!

### ISSUE THREAD

**Issue by kimwalisch** [Homebrew/homebrew#49093]
Hi,

I want to create a new formula where my C++ program is built from source every time a user executes ```brew install ...```. So I don't want that a bottle (binary distribution package) is created by homebrew for my application.

I know that users could use ```brew install ... --build-from-source``` to compile from source but I want to make that the default.

How can I do this?

The reason why I want this behaviour is that as far as I can see my program will only support multi-threading if it is built from source. In the ```./configure``` step my program gets configured to enable OpenMP and also take advantage of the POPCNT instruction if the user's CPU supports it.

**Comment by UniqMartin** [comment]
The way to do this is to add `bottle :disable, "<reason>"` to the formula. See the [`cryptopp` formula](https://github.com/Homebrew/homebrew/blob/51d5af08e29e7893b6978585a50664495b7c0d52/Library/Formula/cryptopp.rb#L10-L11) for an example with a similar motivation.

**Comment by kimwalisch** [comment]
Thanks!
