### ISSUE TITLE
Can't run brew at all

### ISSUE THREAD

**Issue by deanchester** [Homebrew/homebrew#49114]
I had to reinstall OS X the other day and it seems to have broken home-brew. 

This [gist]( https://gist.github.com/deanchester/9c47a75eabbffcd10c59) shows the output. 

I am running OS X 10.10.5. I use RVM for managing ruby versions yet it still seems to not work.

**Comment by ilovezfs** [comment]
Does it work with an empty brew installation?
```
sudo mv /usr/local /usr/local.orig
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

**Comment by deanchester** [comment]
Yes thats fixed the issue how can I move across what I previously had installed?

**Comment by ilovezfs** [comment]
@deanchester OK, good.

```
sudo mv /usr/local /usr/local.empty
sudo mv /usr/local.orig /usr/local
cd /usr/local
git status
```

and post output please.

**Comment by deanchester** [comment]
Strange its not a git repository: 

> deanchester@dean-macbook-pro:/usr/local $ git status
> fatal: Not a git repository (or any of the parent directories): .git

**Comment by ilovezfs** [comment]
ls /usr/local/

**Comment by deanchester** [comment]
No. Sorry heres the full output: 

eanchester@dean-macbook-pro:~ $ sudo mv /usr/local /usr/local.empty
Password:
deanchester@dean-macbook-pro:~ $ sudo mv /usr/local.orig /usr/local
deanchester@dean-macbook-pro:~ $ cd /usr/local
deanchester@dean-macbook-pro:/usr/local $ git status
fatal: Not a git repository (or any of the parent directories): .git

**Comment by ilovezfs** [comment]
`ls -Altr /usr/local/`

**Comment by deanchester** [comment]
> deanchester@dean-macbook-pro:/usr/local $ ls -Altr /usr/local/
> total 96
> -rw-r--r--    1 deanchester  admin   1103 28 Oct  2014 CONTRIBUTING.md
> -rw-r--r--    1 deanchester  admin    301 28 Oct  2014 .gitignore
> -rw-r--r--    1 deanchester  admin   1241 22 Feb  2015 LICENSE.txt
> -rw-r--r--    1 deanchester  admin   3160 22 Feb  2015 CODEOFCONDUCT.md
> -rw-r--r--    1 deanchester  admin    261 22 Feb  2015 .yardopts
> -rw-r--r--    1 deanchester  admin  23781 21 Apr  2015 SUPPORTERS.md
> -rw-r--r--    1 deanchester  admin   2064 21 Apr  2015 README.md
> drwxr-xr-x@   4 deanchester  wheel    136 27 Jan 13:52 texlive
> drwxr-xr-x    6 deanchester  wheel    204 27 Jan 13:52 MacGPG2
> drwxr-xr-x    7 deanchester  65535    238 27 Jan 14:26 heroku
> drwxr-xr-x    3 deanchester  admin    102 27 Jan 14:37 Frameworks
> drwxr-xr-x@   8 deanchester  admin    272 27 Jan 14:37 etc
> drwxr-xr-x@  33 deanchester  wheel   1122 27 Jan 14:37 share
> drwxr-xr-x@  48 deanchester  wheel   1632 27 Jan 14:37 include
> drwxr-xr-x    4 deanchester  admin    136 27 Jan 14:37 var
> drwxr-xr-x   63 deanchester  admin   2142 27 Jan 14:37 opt
> drwxr-xr-x@ 275 deanchester  wheel   9350 27 Jan 14:37 lib
> drwxr-xr-x@ 271 deanchester  wheel   9214 27 Jan 14:37 bin
> drwxr-xr-x@  11 deanchester  admin    374  4 Feb 12:02 Library
>

**Comment by ilovezfs** [comment]
What method did you use to re-install OS X? /usr/local/Cellar seems to be missing (as well as /usr/local/.git)

Also,
```
ls /usr/local/lib/
```
please.

**Comment by deanchester** [comment]
I just used the reinstall and keep data option as I thought something was wrong with my OS X install. 

Here is the ouput for the above: 

> deanchester@dean-macbook-pro:/usr/local $ ls /usr/local/lib/
> ImageMagick-6.8.3                     libboost_prg_exec_monitor.a           libgthread-2.0.dylib
> cairo                                 libboost_prg_exec_monitor.dylib       libhogweed.2.5.dylib
> cloog-isl                             libboost_program_options-mt.a         libhogweed.2.dylib
> cmake                                 libboost_program_options-mt.dylib     libhogweed.a
> dtrace                                libboost_program_options.a            libhogweed.dylib
> gcc                                   libboost_program_options.dylib        libisl.10.dylib
> glib-2.0                              libboost_random-mt.a                  libisl.a
> isl                                   libboost_random-mt.dylib              libisl.dylib
> libGLEW.1.11.0.dylib                  libboost_random.a                     libksba.8.dylib
> libGLEW.1.11.dylib                    libboost_random.dylib                 libksba.dylib
> libGLEW.a                             libboost_regex-mt.a                   libltdl.7.dylib
> libGLEW.dylib                         libboost_regex-mt.dylib               libltdl.a
> libGLEWmx.1.11.0.dylib                libboost_regex.a                      libltdl.dylib
> libGLEWmx.1.11.dylib                  libboost_regex.dylib                  libmpc.3.dylib
> libGLEWmx.a                           libboost_serialization-mt.a           libmpc.a
> libGLEWmx.dylib                       libboost_serialization-mt.dylib       libmpc.dylib
> libGeoIP.1.dylib                      libboost_serialization.a              libmpfr.4.dylib
> libGeoIP.a                            libboost_serialization.dylib          libmpfr.a
> libGeoIP.dylib                        libboost_signals-mt.a                 libmpfr.dylib
> libboost_atomic-mt.a                  libboost_signals-mt.dylib             libnettle.4.7.dylib
> libboost_atomic-mt.dylib              libboost_signals.a                    libnettle.4.dylib
> libboost_chrono-mt.a                  libboost_signals.dylib                libnettle.a
> libboost_chrono-mt.dylib              libboost_system-mt.a                  libnettle.dylib
> libboost_chrono.a                     libboost_system-mt.dylib              libopencv_calib3d.a
> libboost_chrono.dylib                 libboost_system.a                     libopencv_core.a
> libboost_container-mt.a               libboost_system.dylib                 libopencv_features2d.a
> libboost_container-mt.dylib           libboost_test_exec_monitor-mt.a       libopencv_flann.a
> libboost_container.a                  libboost_test_exec_monitor.a          libopencv_hal.a
> libboost_container.dylib              libboost_thread-mt.a                  libopencv_highgui.a
> libboost_context-mt.a                 libboost_thread-mt.dylib              libopencv_imgcodecs.a
> libboost_context-mt.dylib             libboost_timer-mt.a                   libopencv_imgproc.a
> libboost_context.a                    libboost_timer-mt.dylib               libopencv_ml.a
> libboost_context.dylib                libboost_timer.a                      libopencv_objdetect.a
> libboost_coroutine-mt.a               libboost_timer.dylib                  libopencv_photo.a
> libboost_coroutine-mt.dylib           libboost_unit_test_framework-mt.a     libopencv_shape.a
> libboost_coroutine.a                  libboost_unit_test_framework-mt.dylib libopencv_stitching.a
> libboost_coroutine.dylib              libboost_unit_test_framework.a        libopencv_superres.a
> libboost_date_time-mt.a               libboost_unit_test_framework.dylib    libopencv_ts.a
> libboost_date_time-mt.dylib           libboost_wave-mt.a                    libopencv_video.a
> libboost_date_time.a                  libboost_wave-mt.dylib                libopencv_videoio.a
> libboost_date_time.dylib              libboost_wave.a                       libopencv_videostab.a
> libboost_exception-mt.a               libboost_wave.dylib                   libpcre.1.dylib
> libboost_exception.a                  libboost_wserialization-mt.a          libpcre.a
> libboost_filesystem-mt.a              libboost_wserialization-mt.dylib      libpcre.dylib
> libboost_filesystem-mt.dylib          libboost_wserialization.a             libpcre16.0.dylib
> libboost_filesystem.a                 libboost_wserialization.dylib         libpcre16.a
> libboost_filesystem.dylib             libcairo-gobject.2.dylib              libpcre16.dylib
> libboost_graph-mt.a                   libcairo-gobject.a                    libpcre32.0.dylib
> libboost_graph-mt.dylib               libcairo-gobject.dylib                libpcre32.a
> libboost_graph.a                      libcairo-script-interpreter.2.dylib   libpcre32.dylib
> libboost_graph.dylib                  libcairo-script-interpreter.a         libpcrecpp.0.dylib
> libboost_iostreams-mt.a               libcairo-script-interpreter.dylib     libpcrecpp.a
> libboost_iostreams-mt.dylib           libcairo.2.dylib                      libpcrecpp.dylib
> libboost_iostreams.a                  libcairo.a                            libpcreposix.0.dylib
> libboost_iostreams.dylib              libcairo.dylib                        libpcreposix.a
> libboost_locale-mt.a                  libcloog-isl.4.dylib                  libpcreposix.dylib
> libboost_locale-mt.dylib              libcloog-isl.a                        libpixman-1.0.dylib
> libboost_log-mt.a                     libcloog-isl.dylib                    libpixman-1.a
> libboost_log-mt.dylib                 libfiletap.0.dylib                    libpixman-1.dylib
> libboost_log.a                        libfiletap.dylib                      libpng.a
> libboost_log.dylib                    libfontconfig.1.dylib                 libpng.dylib
> libboost_log_setup-mt.a               libfontconfig.dylib                   libpng16.16.dylib
> libboost_log_setup-mt.dylib           libfreetype.6.dylib                   libpng16.a
> libboost_log_setup.a                  libfreetype.a                         libpng16.dylib
> libboost_log_setup.dylib              libfreetype.dylib                     libtasn1.6.dylib
> libboost_math_c99-mt.a                libftdi1.2.1.0.dylib                  libtasn1.a
> libboost_math_c99-mt.dylib            libftdi1.2.dylib                      libtasn1.dylib
> libboost_math_c99.a                   libftdi1.a                            libusb-1.0.0.dylib
> libboost_math_c99.dylib               libftdi1.dylib                        libusb-1.0.a
> libboost_math_c99f-mt.a               libgcrypt.20.dylib                    libusb-1.0.dylib
> libboost_math_c99f-mt.dylib           libgcrypt.dylib                       libusb-1.0.la
> libboost_math_c99f.a                  libgdbm.4.dylib                       libwireshark.5.dylib
> libboost_math_c99f.dylib              libgdbm.a                             libwireshark.dylib
> libboost_math_c99l-mt.a               libgdbm.dylib                         libwiretap.4.dylib
> libboost_math_c99l-mt.dylib           libgio-2.0.0.dylib                    libwiretap.dylib
> libboost_math_c99l.a                  libgio-2.0.dylib                      libwkhtmltox.0.12.2.dylib
> libboost_math_c99l.dylib              libglib-2.0.0.dylib                   libwkhtmltox.0.12.dylib
> libboost_math_tr1-mt.a                libglib-2.0.dylib                     libwkhtmltox.0.dylib
> libboost_math_tr1-mt.dylib            libgmodule-2.0.0.dylib                libwkhtmltox.dylib
> libboost_math_tr1.a                   libgmodule-2.0.dylib                  libwsutil.4.dylib
> libboost_math_tr1.dylib               libgnutls-openssl.27.dylib            libwsutil.dylib
> libboost_math_tr1f-mt.a               libgnutls-openssl.dylib               libyaml-0.2.dylib
> libboost_math_tr1f-mt.dylib           libgnutls.28.dylib                    libyaml.a
> libboost_math_tr1f.a                  libgnutls.dylib                       libyaml.dylib
> libboost_math_tr1f.dylib              libgnutlsxx.28.dylib                  node_modules
> libboost_math_tr1l-mt.a               libgnutlsxx.dylib                     pkgconfig
> libboost_math_tr1l-mt.dylib           libgobject-2.0.0.dylib                python2.6
> libboost_math_tr1l.a                  libgobject-2.0.dylib                  python2.7
> libboost_math_tr1l.dylib              libgpg-error.0.dylib                  wireshark
> libboost_prg_exec_monitor-mt.a        libgpg-error.dylib                    wxPython
> libboost_prg_exec_monitor-mt.dylib    libgthread-2.0.0.dylib                x86_64
> deanchester@dean-macbook-pro:/usr/local $ ls /usr/local/opt/
> apple-gcc42    cairo          gcc            gnutls         libksba        lynx           pixman         swig
> autoconf       cloog          gdbm           htop-osx       libmpc         maven          pkg-config     texinfo
> automake       cloog018       geoip          isl            libmpc08       mpfr           python         tree
> bazaar         cmake          gettext        isl011         libpng         mpfr2          rbenv          wget
> bison          dfu-util       glew           libffi         libtasn1       nettle         readline       wireshark
> boost          flex           glib           libftdi        libtool        openssl        ruby-build
> brew-cask      fontconfig     gmp            libgcrypt      libusb         openssl-osx-ca sdcc
> brew-pkg       freetype       gmp4           libgpg-error   libyaml        pcre           sqlite
> deanchester@dean-macbook-pro:/usr/local $

**Comment by ilovezfs** [comment]
Good, so at least we know what formulae you're using.

Next,

```
ls -l /usr/local/opt/swig
mdutil -t /usr/local/opt/swig
```

**Comment by deanchester** [comment]
Output again: 

> deanchester@dean-macbook-pro:/usr/local $ ls -l /usr/local/opt/swig    
> lrwxr-xr-x  1 deanchester  admin  20 14 Sep 14:17 /usr/local/opt/swig -> ../Cellar/swig/3.0.5
> deanchester@dean-macbook-pro:/usr/local $ mdutil -t /usr/local/opt/swig
> Unable to resolve path

**Comment by ilovezfs** [comment]
```
sudo mdfind swig | grep Cellar
```

**Comment by deanchester** [comment]
Swig doesn't exist: 

deanchester@dean-macbook-pro:/usr/local $ sudo mdfind swig | grep Cellar
deanchester@dean-macbook-pro:/usr/local $

**Comment by ilovezfs** [comment]
Does
```
sudo mdfind Cellar
```
find anything brew-related?

**Comment by ilovezfs** [comment]
OK, so it looks like you're going to need to reinstall the formulae. The only ones you will have trouble with are these, for which you'll get the error "Error: No available formula with the name."
```
apple-gcc42
cloog018
libmpc08
isl011
mpfr2
openssl-osx-ca
brew-pkg
gmp4
```
Also, <code>maven</code> requires java to be installed first, either from Homebrew Cask, or from Oracle  http://www.oracle.com/technetwork/java/javase/downloads/index.html

The rest you can reinstall using <code>brew bundle</code>, as follows:

```
cd ~/Documents
mkdir BrewRecovery
cd BrewRecovery
curl -OL https://gist.githubusercontent.com/ilovezfs/21a741a78927a17b9ad1/raw/fef5866ccd51f07a9635fcb1096e8df0479af01b/Brewfile-deanchester.brewfile
md5 Brewfile-deanchester.brewfile
```
The checksum should be `fe1b0627cbf97a14433bb70d9bf8193b`

```
sudo mv /usr/local /usr/local.orig
sudo mv /usr/local.empty /usr/local
brew update
brew bundle -v --file=~/Documents/BrewRecovery/Brewfile-deanchester.brewfile
```

**Comment by deanchester** [comment]
Thanks @ilovezfs Seems to have reinstalled all the stuff that was there originally.

**Comment by ilovezfs** [comment]
@deanchester You're welcome :)
