### ISSUE TITLE
Homebrew runs a formula twice

### ISSUE THREAD

**Issue by ligadata-dhaval** [Homebrew/homebrew#49120]
I have created my own formula which has puts/print statements. I observed that they get displayed twice. Is there any way to avoid this. Following is the formula:

class XYZ < Formula
 @test
 desc ""
 homepage ""
 version "1.3.1"
 stable do

 if scala_version_211.strip.eql? "2.11"
  puts "2.11 binaries installed"
  url "https:xyz"
  sha256 ""
  option "with-all", "Install"
 elsif scala_version_210.strip.eql? "2.10"
  puts "2.10 binaries  installed"
  url "zyx"
  sha256 "f9c"
  option "with-all", "Install binaries along with kafka and zookeeper"
 end
end

**Comment by mikemcquaid** [comment]
No. Formulae classes are evaluated multiple times so they are printed multiple times. Put print statements into `def install` instead.

**Comment by ligadata-dhaval** [comment]
Thank you, Mike but I have two binaries. Based on the scala version, I install one of the two binaries. For this, I need to I need to put the if else condition in the 'stable do' block.

**Comment by mikemcquaid** [comment]
You don't need to put the `puts` in there, though.
