### ISSUE TITLE
cask definition invalid, cannot see cask list

### ISSUE THREAD

**Issue by jacobjennings** [Homebrew/homebrew#49133]
Jacobs-MacBook:kiku jakej$ brew cask list
Error: Cask 'android-studio' definition is invalid: Bad header line: parse failed

**Comment by DomT4** [comment]
This needs to be filed at https://github.com/caskroom/homebrew-cask. I suspect you may well be fixed by running:
```bash
brew uninstall --force brew-cask && brew update
```
though.
