### ISSUE TITLE
Postgres 9.5.1 has incompatible dict_snowball.so

### ISSUE THREAD

**Issue by davidmweber** [Homebrew/homebrew#49138]
When doing text searches, the following error occurs:

> ERROR:  incompatible library "/usr/local/lib/postgresql/dict_snowball.so": version mismatch
> DETAIL:  Server is version 9.4, library is version 9.5.

`brew info postgres` shows 

> postgresql: stable 9.5.1 (bottled)
> Object-relational database system

This causes errors with queries such as
```sql
 SELECT * FROM table  WHERE  name || ' ' || address  @@ to_tsquery('fred | maxine')
```

A few notes. This is an upgrade from a `brew` installed 9.4.x. The binary located at `/usr/local/Cellar/postgresql/9.5.1/bin/postgres` reports its version as 9.5.1 as does the link at `/usr/local/bin/postgres`.

**Comment by DomT4** [comment]
Could this be related to having an outdated database in `var/postgres`?

**Comment by davidmweber** [comment]
Yes. Missed this nuance on the last upgrade. Here are some additional pointers for others:
- [Upgrade old database](https://kkob.us/2016/01/09/homebrew-and-postgresql-9-5/): Simple recipe for the upgrade. Just pick your versions appropriately.
- [Installing older postgres kegs](http://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula): Needed if you uninstalled the old version which you now need for the database upgrade.
