### ISSUE TITLE
AntiVirus blocked files pulled for llvm

### ISSUE THREAD

**Issue by andylockran** [Homebrew/homebrew#49159]
brew install llvm --HEAD --with-clang

This caused my antivirus to flag the following files on installation:

[http://pasteboard.co/1xXRMRpo.png](url)

**Comment by ilovezfs** [comment]
@andylockran That link is broken.
Also, what antivirus software are we talking about? And can you just configure it to ignore certain files?
Unless http://llvm.org (https://github.com/Homebrew/homebrew/blob/master/Library/Formula/llvm.rb#L67-L96) has been compromised, this sounds like it needs to be reported to the antivirus vendor as a bug.

**Comment by mikemcquaid** [comment]
> this sounds like it needs to be reported to the antivirus vendor as a bug.

Agreed.

**Comment by andylockran** [comment]
Will report to AV vendor.  (Avast)
