### ISSUE TITLE
How to upload a bottle

### ISSUE THREAD

**Issue by rudimeier** [Homebrew/homebrew#49162]
Actually this is not a real issue but just a question. How could I upload or send you a locally build bottle for your public repository? I couldn't find the right documentation how are these official binary packages updated at all.

Particulary I need the "gengetopt" package again and again for my own travis build but
```brew install gengetopt``` always installs it from source. I guess there is no binary.

I've managed to build a bottle and use it right now manually like this
```wget http://akne.unxz.net/~travistest/gengetopt-2.22.6.mavericks.bottle.tar.gz
brew install ./gengetopt-2.22.6.mavericks.bottle.tar.gz```

How could I help to push my gengetopt bottle to the official homwbrew repo?

**Comment by DomT4** [comment]
> How could I upload or send you a locally build bottle for your public repository? 

You can't. You can request bottles but for obvious enough reasons we don't accept bottles from sources we can't control and verify. I'll get CI to add bottles for `gengetopt`.

**Comment by DomT4** [comment]
Done in https://github.com/Homebrew/homebrew/commit/5752227079fd7bd15d2b7a90a49b0f9e1166e89e.

**Comment by rudimeier** [comment]
Thanks a lot!
