### ISSUE TITLE
Make jpeg a virtual dependency

### ISSUE THREAD

**Issue by felixbuenemann** [Homebrew/homebrew#49173]
There are several jpeg libraries, that all support the jpeg8 api:

* jpeg (vanilla ijpg jpeg library)
* jpeg-turbo (highly optimized libjpeg, default in ubuntu)
* mozjpeg (slow, but high quality encoder, with additional features)

Currently every single formula has to be altered to allow linking against jpeg-turbo or mozjpeg. So it would be great if we could have something like `depends_on :jpeg` which would resolve to one of the libraries.

**Maybe there are other options?** We could also replace the default libjpeg with jpeg-turbo. I think ubuntu handles this via alternatives, with the default being jpeg-turbo.

Packages still should be able to depend on a specific implementation, eg. because they use extra encoding flags only supported by mozjpeg, like trellis quantization or overshoot deringing.

**Comment by mikemcquaid** [comment]
We've shied away from making virtual library dependencies as issues can be exceptionally hard to debug and we would not use them with binary packaging anyway. I think custom taps/formulae is the best fit for this (as you could always declare such a requirement there).

**Comment by felixbuenemann** [comment]
How would a custom tap help in this situation? Do you mean overriding the default jpeg formula with a tapped formula of the same name?

**Comment by mikemcquaid** [comment]
> Do you mean overriding the default jpeg formula with a tapped formula of the same name?

Yes (or another name e.g. suffixed `-turbo`).

**Comment by felixbuenemann** [comment]
Thanks for clarifying Mike!
