### ISSUE TITLE
gd-2.1.1 fails to build when using --with-libvpx

### ISSUE THREAD

**Issue by konqui** [Homebrew/homebrew#49186]
There are some variables/constants with a missing VPX_ prefix in webpimg.c in the archived version libgd-2.1.1 due to the fact that gd-libgd has totally removed all dependencies to vpx.

I think it would  be useful
[0001-fixed-broken-build-on-osx-and-homebrew.patch.zip](https://github.com/Homebrew/homebrew/files/130641/0001-fixed-broken-build-on-osx-and-homebrew.patch.zip)

 to have a patch until homebrew changes gd to a newer version.

I have a git diff patch file created and attached to this issue. but i don't know ruby very good and i don't wanna brake the whole gd Formula so can someone who knows ruby integrate this patch into the Formula

**Comment by mikemcquaid** [comment]
Could you try and open a pull request for the newer version of the patch (once it's been submitted upstream)? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by konqui** [comment]
i have created a pull request - https://github.com/Homebrew/homebrew/pull/49240

thank you for taking a look into it.

**Comment by DomT4** [comment]
Closing in favour of the PR then. It looks like aside Mike's comment that's pretty much :+1:, so if we can address Mike's comment in that PR we should be good to roll there.
