### ISSUE TITLE
brew install mongodb error

### ISSUE THREAD

**Issue by MurrayBakerWebDeveloper** [Homebrew/homebrew#49206]
Error: /Library/Caches/Homebrew/Formula/mongodb-osx-x86_64-3.2.1.tgz:1: Invalid char `\x1F' in expression
/Library/Caches/Homebrew/Formula/mongodb-osx-x86_64-3.2.1.tgz:1: invalid multibyte char (UTF-8)

**Comment by DomT4** [comment]
Looks like you've tried to `brew install` an upstream tarball rather than a formula?
```
rm -rf /Library/Caches/Homebrew/* && brew update && brew install mongodb
```
