### ISSUE TITLE
macvim fails to build on OS X 10.11.3 with Xcode 6.4

### ISSUE THREAD

**Issue by RichardBu** [Homebrew/homebrew#49224]
First I got an error that it couldn't find "ruby/config.h". Running brew install ruby solved that issue, but then I got the following error:

https://gist.github.com/anonymous/e0dc6ba78fd9b5ff7d69

I know it suggests updating to Xcode 7 but I need Xcode 6.4.

**Comment by mikemcquaid** [comment]
> I know it suggests updating to Xcode 7 but I need Xcode 6.4.

Sorry, we don't support old versions of Xcode.
