### ISSUE TITLE
error what?

### ISSUE THREAD

**Issue by jack0088** [Homebrew/homebrew#49229]
Error: /usr/local/Library/Homebrew/download_strategy.rb:88: invalid multibyte escape: /^\037\213/
invalid multibyte escape: /^\037\235/
invalid multibyte escape: /^\xFD7zXZ\x00/
Please report this bug:
    https://github.com/mxcl/homebrew/wiki/checklist-before-filing-a-new-issue
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/formula.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/formula_installer.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/cmd/install.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/bin/brew:45:in `require?'
/usr/local/bin/brew:80:in `<main>'

**Comment by DomT4** [comment]
Try:
```bash
cd $(brew --prefix) && git fetch && git reset --hard origin/master
```
Note: If you've made intentional changes to your Homebrew formulae or core files they'll be reset by that command.

**Comment by jack0088** [comment]
tried with 'sudo', got error:

error: cannot open .git/FETCH_HEAD: Permission denied

**Comment by jack0088** [comment]
21st century - no binaries for installing tools like openresty - so poor world....

**Comment by DomT4** [comment]
```bash
sudo chown -R $(whoami):admin $(brew --prefix) && cd $(brew --prefix) && git fetch && git reset --hard origin/master
```
Try that then.

**Comment by jack0088** [comment]
@DomT4 this worked! Thank you.

**Comment by DomT4** [comment]
:+1:. Let us know if we can help further!
