### ISSUE TITLE
pyqt: "ImportError: cannot import name QtGui"

### ISSUE THREAD

**Issue by cam693** [Homebrew/homebrew#49223]
Hello. I get the above error when running a simple .py file:

import sys
from PyQt4 import QtGui

I´ve run brew update twice and brew doctor and it´s says ready to brew. I´m using the Python 2.7.10 default that comes with my MAC. I´m a bit of a noob, but after hours of resaerch and trying to sort it I´m still stuck. I have a feeling it´s something pretty basic. Below are the info reports generated.

Brew info qt

_**qt: stable 4.8.7 (bottled), HEAD
Cross-platform application and UI framework
https://www.qt.io/
/usr/local/Cellar/qt/4.8.7_2 (2,794 files, 112.8M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/qt.rb
==> Dependencies
Required: openssl ✔
Optional: d-bus ✘, mysql ✘, postgresql ✘
==> Options
--universal
	Build a universal binary
--with-d-bus
	Build with d-bus support
--with-docs
	Build documentation
--with-mysql
	Build with mysql support
--with-postgresql
	Build with postgresql support
--with-qt3support
	Build with deprecated Qt3Support module support
--without-webkit
	Build without QtWebKit module
--HEAD
	Install HEAD version
==> Caveats
We agreed to the Qt opensource license for you.
If this is unacceptable you should uninstall.

Qt Designer no longer picks up changes to the QT_PLUGIN_PATH environment
variable as it was tweaked to search for plug-ins provided by formulae in
  /usr/local/lib/qt4/plugins

.app bundles were installed.
Run `brew linkapps qt` to symlink these to /Applications.**_

I´ve run brew linkapps qt

brew info pyqt

pyqt: stable 4.11.4 (bottled)
Python bindings for Qt
https://www.riverbankcomputing.com/software/pyqt/intro
/usr/local/Cellar/pyqt/4.11.4 (562 files, 18M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/pyqt.rb
==> Dependencies
Required: qt ✔, sip ✔
==> Options
--with-python3
	Build with python3 support
--without-python
	Build without python 2 support
==> Caveats
Phonon support is broken.

Any ideas what I´ve done wrong? Thanks a lot.
Cam

**Comment by dunn** [comment]
> Hello. I get the above error

Sorry, where is the error?

**Comment by DomT4** [comment]
FWIW I don't get an error running `python -c "import sys; from PyQt4 import QtGui"` both with a Homebrew or system Python so I suspect this is a local issue somehow.

The error readout per Alex's question and a `brew doctor` may be useful.

**Comment by UniqMartin** [comment]
The error message the original poster is referring to is “hidden” in the issue title:

> `ImportError: cannot import name QtGui`

However, that's not very revealing, so additional information (as already mentioned) would be appreciated.

**Comment by DomT4** [comment]
Closing here per the lack of response but please do let us know if we can help further, Thanks!
