### ISSUE TITLE
Weechat doesn't build with Lua

### ISSUE THREAD

**Issue by victorvalenca** [Homebrew/homebrew#49262]
Building Weechat with the `--with-lua` flag does not install the Lua plugin correctly, nor does it mention Lua at all in the build logs.
```
$ grep -ri lua ~/Library/Logs/Homebrew/Weechat/.
$
```

Output from `brew info weechat`:
https://gist.github.com/victorvalenca/6632a4d8685689222afc

Running on a brand new installation of El Capitan

**Comment by ilovezfs** [comment]
@victorvalenca The problem is that the formula needs to depend on `pkg-config`. This change fixes it:
```
bash-3.2$ git diff
diff --git a/Library/Formula/weechat.rb b/Library/Formula/weechat.rb
index 6d4a0b5..df9427b 100644
--- a/Library/Formula/weechat.rb
+++ b/Library/Formula/weechat.rb
@@ -22,6 +22,7 @@ class Weechat < Formula
   depends_on "gnutls"
   depends_on "libgcrypt"
   depends_on "gettext"
+  depends_on "pkg-config"
   depends_on "guile" => :optional
   depends_on "aspell" => :optional
   depends_on "lua" => :optional
bash-3.2$
```
