### ISSUE TITLE
subversion17 build fails on El Capitan

### ISSUE THREAD

**Issue by tholu** [Homebrew/homebrew#49265]
Since subversion17 is the last version carrying the `--unicode-path` patch, it should build on El Capitan again.

`
subversion17: This formula either does not compile or function as expected on OS X versions newer than Yosemite due to an upstream incompatibility. Error: An unsatisfied requirement failed this build.
`

See also: https://github.com/Homebrew/homebrew/issues/49263

**Comment by DomT4** [comment]
Please see my reply in https://github.com/Homebrew/homebrew/issues/49263.
