### ISSUE TITLE
Failed to download resource "glib--patch"

### ISSUE THREAD

**Issue by kvendrik** [Homebrew/homebrew#49270]
```
brew install glib
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Downloading https://download.gnome.org/sources/glib/2.44/glib-2.44.1.tar.xz
Already downloaded: /Library/Caches/Homebrew/glib-2.44.1.tar.xz
==> Downloading https://gist.githubusercontent.com/jacknagel/af332f42fae80c570a77/raw/7b5fd0d2e6554e9b770729fddacaa2d648

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "glib--patch"
Download failed: https://gist.githubusercontent.com/jacknagel/af332f42fae80c570a77/raw/7b5fd0d2e6554e9b770729fddacaa2d648327644/glib-hardcoded-paths.diff
```

Ran `brew update` without errors just before running `brew install glib`. Thoughts?

**Comment by DomT4** [comment]
You definitely need to `brew update` :wink:

**Comment by kvendrik** [comment]
Thats the thing, I already did :P
```
brew update
Already up-to-date.
```

**Comment by DomT4** [comment]
Well, that's curious. Anything interesting in `brew doctor` and `cd $(brew --prefix) && git status`?

**Comment by kvendrik** [comment]
Fixed! So this was 100% my fault. My local git repo in `/usr/local` got replaced by another CLIs git repo. Removed it and ran the Homebrew install command (`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
`). Works fine again now. :) Thanks for he help.
