### ISSUE TITLE
libjson-rpc-cpp --build-from-source failed to build on 10.11.3

### ISSUE THREAD

**Issue by ramvi** [Homebrew/homebrew#49278]
https://gist.github.com/e0add90085c6680fe43e

**Comment by ilovezfs** [comment]
I cannot reproduce the issue. However, I notice too discrepancies in your gist.

```
/usr/local/Git/bin/git (found version "1.8.2.1") 
```

What is that?
I have
```
$ /usr/bin/git --version
git version 2.5.4 (Apple Git-61)
```

Also, not sure why and probably unrelated, but I have
```
Jsoncpp prefix: json
```
and yours shows
```
Jsoncpp prefix: jsoncpp/json
```

It's worth noting that catch is fetched during the install by git, so that git discrepancy may indeed be the issue.

**Comment by ramvi** [comment]
Upgraded git. Still the same error.

What does the `Jsoncpp prefix: jsoncpp/json`mean and how do I change it?

**Comment by ilovezfs** [comment]
@ramvi Do you have the logs again so we can be sure it picked up the correct git?

Also, it would help if you could check if this works in a clean /usr/local.

```
$ mkdir ~/Documents/Homebrew-20160218
$ sudo mv /usr/local ~/Documents/Homebrew-20160218
$ hash -r
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
$ brew install --only-dependencies libjson-rpc-cpp
$ brew install --build-from-source libjson-rpc-cpp
```

**Comment by ramvi** [comment]
Yes sir, will do, ay-okay:
https://gist.github.com/a3639cfdfdc69e3dfaab

Now how do I get my old homebrew dir back, just by moving it back?
```
sudo rm -Rf /usr/local
sudo mv ~/Documents/Homebrew-20160218/local /usr
```

**Comment by ilovezfs** [comment]
Yes. Or to be safer
```
mkdir ~/Documents/Homebrew-old-tmp
sudo mv /usr/local ~/Documents/Homebrew-old-tmp
sudo mv ~/Documents/Homebrew-20160218/local /usr
```

**Comment by ilovezfs** [comment]
@ramvi Was https://gist.github.com/a3639cfdfdc69e3dfaab the prior or build, or the build in a clean /usr/local?

**Comment by ramvi** [comment]
It was the build in a clean /usr/local .  They all say the same

**Comment by ilovezfs** [comment]
@ramvi Can you try changing 

```
  def install
```
to 

```
  def install
    ENV.deparallelize
```

and see if it makes any difference, please.

**Comment by ramvi** [comment]
I'm not sure where I change that

**Comment by ilovezfs** [comment]
brew edit libjson-rpc-cpp
or
/usr/local/Library/Formula/libjson-rpc-cpp.rb

**Comment by ramvi** [comment]
That worked, thanks! You want the [logs for the successful installation](https://gist.github.com/2641caeb57b0b6c28ac0)?

**Comment by ilovezfs** [comment]
@ramvi Yes, please. Thanks for your patience!
