### ISSUE TITLE
omero failed to build on 10.11.3

### ISSUE THREAD

**Issue by apocryphx** [Homebrew/homebrew#49292]
https://gist.github.com/1da11968796e0ca3a9db

omero fails to build:

==> Installing omero from ome/alt
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://downloads.openmicroscopy.org/omero/5.2.1/artifacts/openmicroscopy-5.2.1.zip
Already downloaded: /Library/Caches/Homebrew/omero-5.2.1.zip
==> ./build.py -Dice.home=/usr/local/opt/zeroc-ice35 build-default
Last 15 lines from /Users/omero/Library/Logs/Homebrew/omero/01.build.py:
		:: ^ see resolution messages for details  ^ ::
		::::::::::::::::::::::::::::::::::::::::::::::
		:: ome#mipav-stubs;5.1.7!mipav-stubs.jar
		::::::::::::::::::::::::::::::::::::::::::::::

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS

BUILD FAILED
/private/tmp/omero20160217-33681-1rnnp2c/openmicroscopy-5.2.1/build.xml:179: The following error occurred while executing this line:
/private/tmp/omero20160217-33681-1rnnp2c/openmicroscopy-5.2.1/components/antlib/resources/global.xml:430: The following error occurred while executing this line:
/private/tmp/omero20160217-33681-1rnnp2c/openmicroscopy-5.2.1/components/antlib/resources/lifecycle.xml:67: impossible to resolve dependencies:
	resolve failed - see output for details

Total time: 6 minutes 17 seconds

**Comment by tdsmith** [comment]
I'm sorry you're having trouble. Please report this at https://github.com/ome/homebrew-alt.
