### ISSUE TITLE
pure-ftpd 1.0.42 no mysql support

### ISSUE THREAD

**Issue by iCr** [Homebrew/homebrew#49306]
Truing to install pure-ftpd with these flags:
```
brew install pure-ftpd --with-everything 
brew install pure-ftpd --with-mysql
```
I do a configuration of pureftpd-mysql.conf, then i trying to launch it. Trying to launch from homebrew.mxcl.pure-ftpd.plist do nothing, and i try to launch it from terminal:
```
sudo pure-ftpd -A -l mysql:/etc/pure-ftpd/pureftpd-mysql.conf
```
And i got error:
```
 [ERROR] Unknown authentication method: mysql:/etc/pure-ftpd/pureftpd-mysql.conf
```
Trying to install pure-ftpd from official source:
```
curl -O ftp://ftp.pureftpd.org/pub/pure-ftpd/releases/pure-ftpd-1.0.42.tar.gz
tar -zxvf pure-ftpd-1.0.42.tar.gz
cd pure-ftpd-1.0.42
./configure --with-mysql
sudo make install-strip
sudo pure-ftpd -A -l mysql:/etc/pure-ftpd/pureftpd-mysql.conf
```
And all working fine, without any issue.
So, what i doing wrong?

**Comment by ilovezfs** [comment]
@iCr It doesn't pass along your configure options.
```
brew cat pure-ftpd
```
or
```
brew edit pure-ftpd
```
or open
```
/usr/local/Library/Formula/pure-ftpd.rb
```
to see the options it actually does use. If you want something other than that, you'll need to modify the formula directly.

**Comment by iCr** [comment]
Yes, i check this, --with-mysql presist in avilable flags of formula.

**Comment by ilovezfs** [comment]
@iCr OK, I was referring to `--with-everything` which isn't in the formula, but I see `--with-mysql` is. Have you tried changing the formula to actually have `--with-everything` to see if that fixes anything?

**Comment by DomT4** [comment]
This formula having bottles is actually quite problematic, because unless people install from source it ignores [these lines](https://github.com/Homebrew/homebrew/blob/63dbc7b2e77a2f0cbf88a1b99b161cf9e1b639ce/Library/Formula/pure-ftpd.rb#L36-L37) which activate the features OP wants here. The formula needs to be rewritten, or the bottles need to be disabled, at quick glance.

**Comment by ilovezfs** [comment]
@DomT4 Yup, I just noticed that it wasn't actually a real formula option. If I manually run configure with --with-mysql, I get

```
checking for mysql_init... no
checking for mysql_init in -lmariadb... no
checking for mysql_init in -lmysqlclient... no
configure: error: libmysqlclient is needed for MySQL support
```

**Comment by ilovezfs** [comment]
@iCr So since you have mysql, you will probably get what you want if you run
```
brew install --build-from-source --verbose pure-ftpd
```

**Comment by iCr** [comment]
Yes, i have mysql 5.7 installed with HB.
18 февр. 2016 г. 22:11 пользователь "ilovezfs" <notifications@github.com>
написал:

**Comment by ilovezfs** [comment]
@iCr what brew command are you running? Your original post does not say you used --build-from-source
