### ISSUE TITLE
erlang build failure in dtrace

### ISSUE THREAD

**Issue by seanjensengrey** [Homebrew/homebrew#49305]
Seeing a compilation failure during the configure step for enabling dtrace

```
checking for 1-stage DTrace precompilation... error: unable to open output file '/dev/fd/8': 'Undefined error: 0'
1 error generated.
dtrace: failed to compile script emulator/beam/erlang_dtrace.d: Preprocessor failed to process input program
configure: error: Could not precompile erlang_dtrace.d: dtrace -h failed
```
which looks nearly identical to this freebsd bug http://lists.freebsd.org/pipermail/freebsd-ports-bugs/2015-January/301266.html

Commenting out dtrace in the formula fixed the error

```
78     if MacOS.version >= :snow_leopard && MacOS::CLT.installed?
79       # args << "--with-dynamic-trace=dtrace"
80     end
```

----

```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: cc7821e593ef0dbedb2d485b65be95920b9cef6a
Last commit: 59 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit sandybridge
OS X: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_66
```

**Comment by ilovezfs** [comment]
You're going to need to provide full logs. I cannot reproduce this on 10.11.2 or 10.11.3, so it's probably a local configuration issue, not a bug.

https://git.io/brew-troubleshooting

**Comment by ilovezfs** [comment]
@seanjensengrey Did you manage to resolve this yourself?

**Comment by DomT4** [comment]
Closing here per the lack of response but please do let us know if we can help further, Thanks!

**Comment by seanjensengrey** [comment]
I loaded 10.10.5 into fresh VM and was not able to reproduce the dtrace issue. I did see a different build failure with `--enable-native-libs`  as reported http://permalink.gmane.org/gmane.comp.lang.erlang.bugs/5098 I can't yet confirm that 

```
* with the workaround
Drop —enable-m64-build and add CFLAGS=‘-O2 -m64'
```
fixes the other issue
