### ISSUE TITLE
Improvement: Running brew, with no params, yields unhelpful output

### ISSUE THREAD

**Issue by pcgeek86** [Homebrew/homebrew#49325]
Running `brew` with no parameter, yields an unhelpful message. 

> Error: Unknown command:

<img width="251" alt="screen shot 2016-02-18 at 3 12 12 pm" src="https://cloud.githubusercontent.com/assets/466713/13159957/06352558-d652-11e5-81db-76cc4a425293.png">

My suggestion would be to have it print help by default, or offer something helpful to the user.

Cheers,
Trevor Sullivan
https://twitter.com/pcgeek86

**Comment by DomT4** [comment]
Until https://github.com/Homebrew/homebrew/commit/213bf49dae9fb4758ceb78b95694c56987535977 we used to print the `help` output if the argument was blank. Looking into whether the change was intentional or not.

**Comment by mikemcquaid** [comment]
This was my accidental regression rushing to fix another issue. Thanks for the report and sorry for the pain.

**Comment by pcgeek86** [comment]
@mikemcquaid Thanks a lot! These simple improvements help make it a more easily consumable tool, and reach a larger audience. :)

Cheers,
Trevor Sullivan
