### ISSUE TITLE
pgtap: pg_prove can't locate perl module

### ISSUE THREAD

**Issue by povman** [Homebrew/homebrew#49338]
Basic installation of `pgtap` gives me a broken version of `pg_prove`. Looks like the perl module can't be found.

```
Vine:tmp lukeworth$ brew install pgtap
Warning: pgtap-0.94.0 already installed
Vine:tmp lukeworth$ which pg_prove
/usr/local/bin/pg_prove
Vine:tmp lukeworth$ pg_prove -d test_icedb test.sql
Cannot load handler 'pgTAP': Can't locate TAP/Parser/SourceHandler/pgTAP.pm in @INC (you may need to install the TAP::Parser::SourceHandler::pgTAP module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at (eval 16) line 2.
BEGIN failed--compilation aborted at (eval 16) line 2.

Can't locate pgTAP.pm in @INC (you may need to install the pgTAP module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at (eval 17) line 2.
BEGIN failed--compilation aborted at (eval 17) line 2.
 at /System/Library/Perl/5.18/App/Prove.pm line 554.
Vine:tmp lukeworth$ 
```

**Comment by ilovezfs** [comment]
It should work if you set PERL5LIB in your shell.
```
export PERL5LIB=$PERL5LIB:/usr/local/lib/perl5:/usr/local/lib/perl5/darwin-thread-multi-2level 
```

**Comment by mikemcquaid** [comment]
@ilovezfs We should probably write a wrapper script to do this for users.

**Comment by ilovezfs** [comment]
@mikemcquaid If this is gong to keep being a common thing, we may want a brew formula variable `perlib` or `plib` (as it's called in pgtap.rb). There seems to be some inconsistency amongst the formulae:
```
Josephs-MacBook-Pro:Formula joe$ ag perl|grep site|grep lib
git.rb:57:        #{Formula["subversion"].opt_prefix}/lib/perl5/site_perl
imagemagick.rb:117:        export PERL5LIB="#{HOMEBREW_PREFIX}/lib/perl5/site_perl":$PERL5LIB
irssi.rb:58:      args << "--with-perl-lib=#{lib}/perl5/site_perl"
mysql-sandbox.rb:18:    ENV.prepend_create_path "PERL5LIB", libexec/"lib/perl5/site_perl/"
pgtap.rb:26:    plib  = "#{lib}/perl5/site_perl"
radare2.rb:83:                           "PERLPATH=#{lib}/perl5/site_perl/#{perl_version}",
st.rb:14:    ENV.prepend_create_path "PERL5LIB", libexec/"lib/perl5/site_perl/"
```
Is the canonical location supposed to be `lib/"perl5/site_perl/"` or `libexec/"lib/perl5/site_perl/"`?

Recently this was done:
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/imagemagick.rb#L116-L117

That formula could benefit from a similar wrapper, or if you want to avoid wrapper scripts, we could add the same caveat as in imagemagick.rb and then make this change:

```
diff --git a/Library/Formula/pgtap.rb b/Library/Formula/pgtap.rb
index 1e1a0bf..fa96fa8 100644
--- a/Library/Formula/pgtap.rb
+++ b/Library/Formula/pgtap.rb
@@ -23,19 +23,21 @@ class Pgtap < Formula
   def install
     # Make sure modules can find just-installed dependencies.
     arch  = `perl -MConfig -E 'print $Config{archname}'`
-    plib  = "#{lib}/perl5"
+    plib  = "#{lib}/perl5/site_perl"
     ENV["PERL5LIB"] = "#{plib}:#{plib}/#{arch}:#{lib}:#{lib}/#{arch}"
 
     resource("Test::Harness").stage do
       system "perl", "Makefile.PL", "INSTALL_BASE=#{prefix}",
-             "INSTALLSITEMAN1DIR=#{man1}", "INSTALLSITEMAN3DIR=#{man3}"
+             "INSTALLSITEMAN1DIR=#{man1}", "INSTALLSITEMAN3DIR=#{man3}",
+             "INSTALLSITELIB=#{plib}"
       system "make"
       system "make", "install"
     end
 
     resource("TAP::Parser::SourceHandler::pgTAP").stage do
       system "perl", "Build.PL", "--install_base", prefix, "--install_path",
-             "bindoc=#{man1}", "--install_path", "libdoc=#{man3}"
+             "bindoc=#{man1}", "--install_path", "libdoc=#{man3}",
+             "--install_path", "lib=#{plib}"
       system "./Build"
       system "./Build", "install"
     end

```

**Comment by DomT4** [comment]
> Is the canonical location supposed to be lib/"perl5/site_perl/" or libexec/"lib/perl5/site_perl/"?

Neither. It entirely depends on the circumstance with bindings.

**Comment by DomT4** [comment]
> That formula could benefit from a similar wrapper, or if you want to avoid wrapper scripts, we could add the same caveat as in imagemagick.rb and then make this change:

Also: `imagemagick` got a `caveat` rather than a wrapper because the perl element there isn't enabled by default.

Perl is quite tricky to handle, so there aren't many set defaults here.

**Comment by DomT4** [comment]
Heh, It's trying to break free of the sandbox as well, twice. Once on the Perl stuff and one on the install:
```
/usr/bin/install -c -m 644 .//pgtap.control '/usr/local/share/postgresql/extension/'
install: /usr/local/share/postgresql/extension//pgtap.control: Operation not permitted
make: *** [install] Error 71
```

**Comment by ilovezfs** [comment]
That the perl module isn't there by default certainly means it's not required to make a wrapper, but it doesn't mean the formula wouldn't benefit from having one. It seems weird to sometimes be requiring profile changes for perl, and sometimes not.

**Comment by DomT4** [comment]
Considering we have _zero_ stats on how heavily any optional options are used, we're not yet at the point of deciding sensibly whether it's worth adding extra accommodation for every possible `optional` argument that needs extra handling, and considering the `optional` ones are never CI tested they could silently break and we'd never know.

I'd rather we're upfront that optional choices ship at your own risk, rather than pretending we're capable of supporting them from cradle to grave at this point.

**Comment by ilovezfs** [comment]
I think that quickly becomes an argument for not having any "non-recommended" (I.e., non-default)  options. Users  should expect that a project called Homebrew can reliably produce functional, tested home brews using any of the  options from its distributed formulae.

**Comment by DomT4** [comment]
Believe me, we've had that discussion and consequently are quite a bit more pushy about asking people for justification for inclusion beyond "I want it" now. If people read too much into the name they're somewhat missing Max's love of beer.

By all means, if you want to push forwards with a massive _and rapid_ expansion of CI infrastructure and testing I look forwards to your cheque donation of several thousand dollars. We offer pre-compiled packages which is a relatively huge thing for OS X, which the vast majority of users use, we support those thoroughly and effectively. Outside of that, we're pinned down by finance and resources.

**Comment by ilovezfs** [comment]
That could probably be mostly solved without any additional resources by reallocating the Mavericks build machine to build maximal 10.11 configurations, and only supporting two OS revisions back instead of three.
