### ISSUE TITLE
brew update --help fork bombs

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew#49334]
`brew update --help` recursive calls `brew update --help` and crashes with `fork: Resource temporarily unavailable`.

```
❯❯❯ brew update --help
/usr/local/bin/brew: fork: Resource temporarily unavailable
/usr/local/bin/brew: fork: Resource temporarily unavailable
/usr/local/bin/brew: fork: Resource temporarily unavailable
/usr/local/Library/brew.sh: fork: Resource temporarily unavailable
/usr/local/Library/brew.sh: fork: Resource temporarily unavailable
/usr/local/Library/brew.sh: fork: Resource temporarily unavailable
/usr/local/Library/brew.sh: fork: Resource temporarily unavailable
/usr/local/bin/brew: fork: Resource temporarily unavailable
```

Just curious, and a one line answer is fine or a pointer to a conversation elsewhere, why was `brew update` rewritten in `sh`?

**Comment by bfontaine** [comment]
> Just curious, and a one line answer is fine or a pointer to a conversation elsewhere, why was `brew update` rewritten in `sh`?

Mostly because it avoids the issue we have when Ruby code updates Ruby code, and so at some point it can run old and new code at the same time and things get messy.

**Comment by mikemcquaid** [comment]
Additionally: it makes multithreading fetching much easier and allows us to better handle updating when the system Ruby is broken, missing or a version we aren't supporting (e.g. when we move to Ruby 2).
