### ISSUE TITLE
OS X El Captain: brew.sh Ruby related problems

### ISSUE THREAD

**Issue by teowey** [Homebrew/homebrew#49350]
I am having an issue after I install brew in my mac. When try "brew update" or any other "brew" command it outputs:

```
/usr/local/Library/brew.sh: line 172: /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby: No such file or directory
/usr/local/Library/brew.sh: line 172: exec: /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby: cannot execute: No such file or directory
```
I found other forums and solutions on a problem with "brew.rb": http://apple.stackexchange.com/questions/153790/how-to-fix-brew-after-osx-upgrade-to-yosemite

But this is a bit different, it's in "brew.sh". If I go to `/System/Library/Frameworks/Ruby.framework/Versions/` folder I find this:
```
drwxr-xr-x  7 root  wheel  238 Feb 19 15:16 2.0
lrwxr-xr-x  1 root  wheel   54 Feb 19 14:34 Current -> /System/Library/Frameworks/Ruby.framework/Versions/1.8

```

Can someone help me? I can't find any solution for this.

Teo

**Comment by bfontaine** [comment]
You `Current` symlink is broken; the path it points to doesn’t exist. It should point to `/System/Library/Frameworks/Ruby.framework/Versions/2.0`, not `/System/Library/Frameworks/Ruby.framework/Versions/1.8`.

**Comment by teowey** [comment]
Can you give me the right command to do this? :)

**Comment by ilovezfs** [comment]
I'd be curious how it got that way.

I'm assuming this is not El Capitan:
To fix it
```
sudo ln -sf 2.0 /System/Library/Frameworks/Ruby.framework/Versions/Current 
```

**Comment by teowey** [comment]
@ilovezfs Thanks! It is El Capitan, maybe my brew configuration was messed up. It works now!

**Comment by ilovezfs** [comment]
@teowey Glad it's working again...but since it is El Capitan, I'm surprised that command succeeded. Does that mean you turned SIP off?
