### ISSUE TITLE
curl: (51) SSL: certificate verification failed (result: 5)

### ISSUE THREAD

**Issue by bsdlp** [Homebrew/homebrew#49373]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

one day i just started not being able to retrieve binaries from homebrew.bintray.com. looks like some kind of SSL verification issue. Retrieving the binary directly with curl and via google chrome work just fine. Has anyone seen this before? I'm not sure why this is happening to just homebrew for just homebrew.bintray.com.

```
[1] jchen@locke> brew update && brew upgrade
Already up-to-date.
==> Upgrading 7 outdated packages, with result:
glide 0.9.0, go 1.6, godep 53, imagemagick 6.9.3-0_2, node 5.6.0, postgresql 9.5.1, sqlite 3.11.0
==> Upgrading glide
==> Downloading https://homebrew.bintray.com/bottles/glide-0.9.0.el_capitan.bottle.tar.gz

curl: (51) SSL: certificate verification failed (result: 5)
Error: Failed to download resource "glide"
Download failed: https://homebrew.bintray.com/bottles/glide-0.9.0.el_capitan.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Installing dependencies for glide: go
==> Installing glide dependency: go
==> Downloading https://homebrew.bintray.com/bottles/go-1.6.el_capitan.bottle.tar.gz
^C
```

brew {doctor,config}:

```
jchen@locke> brew doctor
Your system is ready to brew.
jchen@locke> brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: df6c6f1a4b1690c02478052f1c7cb8a5706d277b
Last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.11.3-x86_64
Xcode: N/A
CLT: 7.2.0.0.1.1447826929
Clang: 7.0 build 700
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/var/rbenv/versions/2.2.3/bin/ruby
Java: 1.8.0_60
```

**Comment by ilovezfs** [comment]
Any chance you have SSL_CERT_FILE set in your environment?

**Comment by bsdlp** [comment]
@ilovezfs yep, unsetting it resolves the issue. :tired_face: thanks!

**Comment by ilovezfs** [comment]
@bsdlp Excellent, glad it worked out.

**Comment by ms-tg** [comment]
This impacted me as well -- thanks very much for the hint to `unset SSL_CERT_FILE`

**Comment by samsieber** [comment]
This impacted me was well - can we add this to brew doctor somehow?

**Comment by MikeMcQuaid** [comment]
@samsieber Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by brikis98** [comment]
I had the same problem, but didn't have any mention of `SSL_CERT_FILE` in my `~/.bash_profile`, so I was a bit confused. After digging around, it turns out that `SSL_CERT_FILE` was actually being set in `~/.nix-profile/etc/profile.d/nix.sh`, which the [Nix Package Manager](http://nixos.org/nix/) adds to `~/.bash_profile` so it can use a custom version of curl.
