### ISSUE TITLE
brew-doctor: unneeded warnings

### ISSUE THREAD

**Issue by konqui** [Homebrew/homebrew#49372]
Since brew install osxfuse recommends to install osxfuse from Caskroom/cask or native install from sourceforge.net.

----

bash: $ brew install osx fuse
osxfuse: Building this formula from source isn't possible due to OS X
Yosemite and above's strict unsigned kext ban.

You can install with Homebrew Cask:
  brew install Caskroom/cask/osxfuse

You can download from:
  http://sourceforge.net/projects/osxfuse/files/

----

I recommend adding exceptions for the following two Files:
* /usr/local/lib/libosxfuse.2.dylib
* /usr/local/lib/libosxfuse.la

So that these Warnings no longer appear.

----

bash: $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libosxfuse.2.dylib

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libosxfuse.la

----

**Comment by DomT4** [comment]
Those elements are apparently new in the recent OSXFuse updates, so they weren't on the whitelist with the rest of the FUSE elements yet. Fixed in https://github.com/Homebrew/homebrew/commit/1497a4ea156af6405de4ddf323de912acf1257d0.
