### ISSUE TITLE
enchant formula does not contain voikko spell checker for Finnish language

### ISSUE THREAD

**Issue by heikkil** [Homebrew/homebrew#49386]
Feature request:

The formula for enchant includes only aspell as a dependency and leaves out other supported spell engines. An up-to-date libvoikko package is available in homebrew.  Enchant is currently the only way to make voikko available for emacs and other text editors not using OSX system services. Including voikko to the formula is most probably beyond my abilities, so I am raising this issue and hoping someone could fix this.

Debian-based Linux distributions routinely contain voikko support in their enchant packages.

**Comment by mikemcquaid** [comment]
> The formula for enchant includes only aspell as a dependency and leaves out other supported spell engines. An up-to-date libvoikko package is available in homebrew. Enchant is currently the only way to make voikko available for emacs and other text editors not using OSX system services. Including voikko to the formula is most probably beyond my abilities, so I am raising this issue and hoping someone could fix this.

I'm afraid we don't really do feature requests. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by heikkil** [comment]
Creating a fork and a patch branchs is not problem. I'll see how far I can
get with modifying the formula and come back to you. Thanks for offering to
help.

     -Heikki

Heikki Lehväslaiho - skype:heikki_lehvaslaiho cell: +358 40 850 6640
http://about.me/heikki
