### ISSUE TITLE
gcc without-multilib still builds with multilib?

### ISSUE THREAD

**Issue by rmoucha** [Homebrew/homebrew#49395]
_Here is what I did:_

% brew reinstall gcc --without-multilib
==> Reinstalling gcc with --without-multilib
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-5.3.0/gcc-5.3.0.tar.bz2
==> Downloading from http://gnu.askapache.com/gcc/gcc-5.3.0/gcc-5.3.0.tar.bz2
######################################################################## 100.0%
==> Patching
patching file gcc/jit/Make-lang.in
patching file gcc/jit/jit-playback.c
Hunk #1 succeeded at 2470 with fuzz 2 (offset 54 lines).
==> ../configure --build=x86_64-apple-darwin15.3.0 --prefix=/usr/local/Cellar/gc
==> make bootstrap
==> make install
==> Caveats
GCC has been built with multilib support. Notably, OpenMP may not work:
  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60670
If you need OpenMP support you may want to
  brew reinstall gcc --without-multilib
==> Summary
🍺  /usr/local/Cellar/gcc/5.3.0: 1,913 files, 427.6M, built in 50 minutes 42 seconds

% gfortran --version
GNU Fortran (Homebrew gcc 5.3.0 --without-multilib) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.

_So did I build without multilib or not?_

**Comment by DomT4** [comment]
Is your Homebrew up-to-date? I thought we'd fixed this in https://github.com/Homebrew/homebrew/issues/48657.

**Comment by rmoucha** [comment]
You are right, I just installed homebrew and thought wrong that it was the latest version, 

% brew update
Updated Homebrew from 4d16956 to 22b46e3.

%brew reinstall gcc --without-multilib
==> Reinstalling gcc with --without-multilib
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-5.3.0/gcc-5.3.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc-5.3.0.tar.bz2
==> Patching
patching file gcc/jit/Make-lang.in
patching file gcc/jit/jit-playback.c
Hunk #1 succeeded at 2470 with fuzz 2 (offset 54 lines).
==> ../configure --build=x86_64-apple-darwin15.3.0 --prefix=/usr/local/Cellar/gcc/5.3.0 --libdir=/usr/local/Cellar/gcc/5.3.0/lib/
==> make bootstrap
==> make install
🍺  /usr/local/Cellar/gcc/5.3.0: 1,292 files, 224.9M, built in 49 minutes 29 seconds

**Comment by mikemcquaid** [comment]
@rmoucha The new issues template asked you to run `brew update` and try again before filing. Please do that in future, thanks!

**Comment by DomT4** [comment]
The level of behind-the-latest here was minimal enough that the problem shouldn't have been there in the first place. Not quite sure why it popped back up, and only for the one `reinstall` :confused:.
