### ISSUE TITLE
how to use etc.install properly

### ISSUE THREAD

**Issue by jkarneges** [Homebrew/homebrew#49410]
Hi,

Pushpin's config files get overwritten after any updates so I want to use `etc.install` or something comparable to ensure that files are left alone and `.default` versions of files are created.

Running Pushpin's "make install" step will cause config files to be installed along with everything else, with the exception that config files are checked for existence before overwriting. This is fairly standard behavior for a source package I would imagine. In the context of Homebrew, I suspect the existence check has no effect since the installed files end up isolated in the Cellar, but that's fine.

After make install, I use `etc.install` to install the files:
```
etc.install "examples/config/pushpin.conf" => "pushpin/pushpin.conf"
etc.install "examples/config/routes" => "pushpin/routes"
```

But the build fails after that part:
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink etc/pushpin/pushpin.conf
Target /usr/local/etc/pushpin/pushpin.conf
already exists. You may want to remove it:
  rm '/usr/local/etc/pushpin/pushpin.conf'
```

Presumably brew wants to make a link where I've put files via `etc.install`.

What's the right way to do this? I see `etc.install` being used in a bunch of formulas but I don't understand why it works. Are the other packages somehow excluding config files from the make install step? Also I noticed nginx has a directory with each config file given a `.default` copy (what I was planning to use as a model), but nginx doesn't seem to be using `etc.install` so I don't know how they are doing it.

**Comment by mikemcquaid** [comment]
`etc` files do/should not end up isolated in the Cellar but instead go into `HOMEBREW_PREFIX/"etc"`. In this case I think the problem is that they are ending up in `HOMEBREW_PREFIX/"etc"` and `prefix/"etc"`.

The right approach is to ensure `make install` is using the value of `#{etc}` correctly and then the rest will be handled for you. `etc.install` should only be needed if there is no `make install`.

**Comment by jkarneges** [comment]
Ah hah! Yes, if I configure the build to install the etc files into `#{etc}` then I get conventional behavior (installing twice doesn't replace existing config files).

However I don't see any `.default` files being made. I assume this is a Homebrew-ism since several packages do it, and so I was hoping to reuse that behavior if possible.

**Comment by mikemcquaid** [comment]
> However I don't see any .default files being made. I assume this is a Homebrew-ism since several packages do it, and so I was hoping to reuse that behavior if possible.

This files will only be created if there's a modified file already existing in the new location.

**Comment by jkarneges** [comment]
I'm not seeing that behavior. The `make install` step is basically doing `test -e {etc}/file.conf || cp -f file.conf {etc}` for each config file. Does the it need to do something else like use `install` in order to trigger Homebrew's behavior?

**Comment by mikemcquaid** [comment]
I checked the code to verify. That behaviour is only triggered by using either `etc.install` or when pouring `make install` from a bottle (the latter means `etc` is installed into `prefix/.etc` and then put in the right place when pouring the bottle)

**Comment by jkarneges** [comment]
Cool, now that I've updated the package and it is in bottle form, if I uninstall/reinstall the bottle then I see that behavior now. Thanks!
