### ISSUE TITLE
ngrok.rb should be updated or removed

### ISSUE THREAD

**Issue by kenzierocks** [Homebrew/homebrew#49432]
I've just gotten an email that `ngrok` 1 will be discontinued ('sunset') entirely by April 4, 2016 (I haven't found a public source for this). Consequently, `ngrok.rb` either needs to be updated to 2.0 or removed by then. #45441 has made it clear that `ngrok` must be open source to be added, but [open-sourcing is not planned](https://github.com/inconshreveable/ngrok/issues/311). This probably means that `ngrok.rb` should be removed or print a warning that `ngrok` 2 is only available from `homebrew/binary/ngrok2`.

**Comment by DomT4** [comment]
Unless it is expected to become broken or insecure shortly after upstream stop maintaining it, if that comes to pass, we're not likely to jump the shark here. It is still a very popular package despite being the lesser maintained branch at this point.

Both `brew info ngrok` and `brew install` are transparent that it's the 1.x branch so I don't think we'll get a ton of surprised people:
```
==> Downloading https://homebrew.bintray.com/bottles/ngrok-1.7.1_1.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring ngrok-1.7.1_1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/ngrok/1.7.1_1: 4 files, 10.7M
```

**Comment by kenzierocks** [comment]
The servers will become unavailable, so it won't work unless someone sets up a server themselves (if that's even possible). [Here's the email I got.](https://gist.github.com/kenzierocks/ea3a4040ccbf77741c32).

**Comment by DomT4** [comment]
That kind of ties our hands, I guess. It'd be nice for the upstream developer to shed some more light on this formally; whether it'll completely stop working or people will be able to carry the project off and support it themselves, etc.

But you're right that we won't take 2.x here because of the licensing.

**Comment by ilovezfs** [comment]
FYI the 1.7.1 build broke, but this fixes it: #50113

**Comment by shamrin** [comment]
FYI, ngrok 1.X has stopped working for non authenticated users:

```
$ ngrok 80
Server failed to allocate tunnel: The ngrok 1.X service has been sunset. Please upgrade to 2.0. More infromation is here: https://ngrok.com/sunset/1
```

**Comment by mikemcquaid** [comment]
Looks like it's time to send this to the boneyard.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew/pull/50364
