### ISSUE TITLE
brew pull off-by-one error?

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/homebrew#49446]
Running `brew pull --bottle` recently seems to regularly not pull the bottle commit for the last formula pulled (when pulling more than one). Am I imagining this or is this a possible regression?

CC @apjanke for a possible fix and @DomT4 who may have also seen this.

**Comment by DomT4** [comment]
I haven't seen this behaviour as far as I can recall. I presume by pulling more than one you mean:

```
brew pull --bottle 49447 49443 49427
```
For example? Rather than pull, wait for completion, execute another pull, wait for completion, etc and then push? The latter method is the one I use because I've found it easier to spot SHA256 bottle errors without slowing me down too much, but that may well explain why I've not spotted it.

**Comment by mikemcquaid** [comment]
> For example?

Yep, like that. Can you try it some time and see if you get a similar result?

**Comment by DomT4** [comment]
Yeah, sure. I'll have some free time mid-afternoon today, will chase that then.

**Comment by DomT4** [comment]
Yeah, you're right. It doesn't even try to pull the next bottle in the chain:

```
~> brewpb 49427 49426
==> Fetching patch
######################################################################## 100.0%
==> Applying patch
Applying: agda: fix HashMap build failure
==> Patch closes issue #49427
Switched to a new branch 'pull-bottle-49427'
==> Fetching patch
######################################################################## 100.0%
==> Applying patch
Applying: agda: fix HashMap build failure
Applying: agda: update 2.4.2.5 bottle.
First, rewinding head to replay your work on top of it...
Applying: agda: update 2.4.2.5 bottle.
Switched to branch 'master'
Updating a9716f7..9cc4346
Fast-forward
 Library/Formula/agda.rb | 7 ++++---
 1 file changed, 4 insertions(+), 3 deletions(-)
Deleted branch pull-bottle-49427 (was 9cc4346).
==> Publishing on Bintray:
{"files":3}
==> Patch changed:
 Library/Formula/agda.rb | 21 ++++++++++++++++++---
 1 file changed, 18 insertions(+), 3 deletions(-)
==> Fetching patch
######################################################################## 100.0%
==> Applying patch
Applying: imgcat 0.1 (new formula)
==> Patch closes issue #49426
==> Patch changed:
 Library/Formula/imgcat.rb | 15 +++++++++++++++
 1 file changed, 15 insertions(+)
==> Downloading https://homebrew.bintray.com/bottles/agda-2.4.2.5.el_capitan.bottle.1.tar.gz
######################################################################## 100.0%
Downloaded to: /usr/local/var/homebrew/cache/agda-2.4.2.5.el_capitan.bottle.1.tar.gz
SHA1: 92d721b110c26393fe9bdbc5f8cd88021cc99c7c
SHA256: 413bbbdd8207d368ad1189da9c99b904d58c04eedc3f6723e0ae6819d85ef6dd
```

**Comment by mikemcquaid** [comment]
CC @apjanke when you're awake :grinning:

**Comment by ilovezfs** [comment]
@mikemcquaid The regression appears to have been introduced by 3ee2825ad3cfa7c895a360bd0bd3cfb05e4e0c8d

**Comment by mikemcquaid** [comment]
@ilovezfs That's a possible case but it's not this one as that wouldn't stop a single bottle from being fetched. I'm pretty sure it was part of https://github.com/Homebrew/homebrew/pull/48472 (hence CCing @apjanke).

**Comment by ilovezfs** [comment]
I could be wrong but git reverting it seemed to fix it. Are you sure it's off-by-one as opposed to new formulae?

**Comment by apjanke** [comment]
I think it is hitting that exception; I can see it if I add debugging statements in.

It seems to be order dependent: `brew pull --bottle --branch-okay 49474 49465` does not fetch the bottle for 49465. But `brew pull --bottle --branch-okay 49465 49474` will fetch both bottles and publish them on Bintray.

One thing in common with both of those failing examples is that the last patch in the list is adding a new formula instead of modifying an existing one.

Here's a failure case with some debugging statements added in.

```
[/usr/local/Library/Homebrew on ⇄ pull-02]
$ brew pull --bottle --branch-okay 49474 49465
==> Doing arg 49474
==> Fetching patch
######################################################################## 100.0%
==> Applying patch
Applying: ats2-postiats 0.2.6
==> diff line
line: Library/Formula/ats2-postiats.rb
name: Homebrew/homebrew/ats2-postiats
==> Changed formulae: [#<Formula ats2-postiats (stable) /usr/local/Library/Formula/ats2-postiats.rb>]
==> Patch closes issue #49474
Switched to a new branch 'pull-bottle-49474'
==> Fetching patch
######################################################################## 100.0%
==> Applying patch
Applying: ats2-postiats 0.2.6
Applying: ats2-postiats: update 0.2.6 bottle.
First, rewinding head to replay your work on top of it...
Applying: ats2-postiats: update 0.2.6 bottle.
Switched to branch 'pull-02'
Updating 244e090..720d0c4
Fast-forward
 Library/Formula/ats2-postiats.rb | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)
Deleted branch pull-bottle-49474 (was 720d0c4).
==> Publishing on Bintray:
{"files":0}
==> Patch changed:
 Library/Formula/ats2-postiats.rb | 20 +++++++++++++-------
 1 file changed, 13 insertions(+), 7 deletions(-)
==> Doing arg 49465
==> Fetching patch
######################################################################## 100.0%
==> Applying patch
Applying: openlldp 0.4 (new formula)
==> diff line
line: Library/Formula/openlldp.rb
name: Homebrew/homebrew/openlldp
==> Got exception
No available formula with the name "Homebrew/homebrew/openlldp"
==> Changed formulae: []
==> Patch closes issue #49465
==> Patch changed:
```

And doing a new-formula patch on its own works, with bottles fetched.

Seems like there's something about the act of applying the first patch or fetching bottles for it is causing the new formula from the later patch to be unloadable. Maybe something to do with the [branching and rebasing in the bottle commit pull](https://github.com/Homebrew/homebrew/blob/dfaab6907b4057320e78edacab03e99f71904178/Library/Homebrew/cmd/pull.rb#L178-L183)?

**Comment by mikemcquaid** [comment]
Apologies to @apjanke and @ilovezfs: sounds like you are both right. I'll dig into this more myself.

**Comment by ilovezfs** [comment]
@mikemcquaid No need to apologize!

I believe the exception is raised during the array access here:
```
 changed_formulae << Formula[name]
```
https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/pull.rb#L103

**Comment by apjanke** [comment]
Hey, check out the code to [`TapLoader` in `formulary.rb`](https://github.com/Homebrew/homebrew/blob/dfaab6907b4057320e78edacab03e99f71904178/Library/Homebrew/formulary.rb#L148-L152).

```
  class TapLoader < FormulaLoader
    attr_reader :tap

    def initialize(tapped_name)
      user, repo, name = tapped_name.split("/", 3).map(&:downcase)
      @tap = Tap.fetch user, repo
      name = @tap.formula_renames.fetch(name, name)
      path = @tap.formula_files.detect { |file| file.basename(".rb").to_s == name }
```

I think that: It intializes itself from a list of formula files in the tap. The initialization happens the first time `Formula["name"]` is called. When doing the bottle fetches, the first time `Formula["name"]` happens is when doing the changed-formula check for the first patch you're pulling. So I think it'll only see the list of formulae available after application of the first patch. New formulae in the second and later patches will not be loadable.

**Comment by ilovezfs** [comment]
Nice find. Yup, that's consistent with what I'd seen yesterday with inspect. One time there was only the lonely new one, another time there was the whole boatload in there.

**Comment by mikemcquaid** [comment]
@xu-cheng thoughts on this?

**Comment by apjanke** [comment]
...think I got the location of the caching wrong. Maybe it's at the Tap level. Looks like the `TapLoader` is fresh, but it's attached to a `Tap`, the [`Tap`s are cached](https://github.com/Homebrew/homebrew/blob/dfaab6907b4057320e78edacab03e99f71904178/Library/Homebrew/tap.rb#L33-L39), and the individual Tap objects [cache `@formula_files`](https://github.com/Homebrew/homebrew/blob/dfaab6907b4057320e78edacab03e99f71904178/Library/Homebrew/tap.rb#L243) using the `||=` field assignment.

```
  # an array of all {Formula} files of this {Tap}.
  def formula_files
    @formula_files ||= if formula_dir
      formula_dir.children.select { |p| p.extname == ".rb" }
```

So Taps won't notice new formula files added during the lifetime of the Tap object?

**Comment by xu-cheng** [comment]
I think we can rewrite `TapLoader` to use `Tap#formula_dir` instead of `Tap#formula_files`. This will also improve the performance. 

If needed, we can call `Tap.clear_cache` in some point in `brew pull` to clear the cache.

**Comment by mikemcquaid** [comment]
This was fixed by https://github.com/Homebrew/homebrew/pull/49484. Thanks @xu-cheng!
