### ISSUE TITLE
No runner module in Ansible 2.0.0.2

### ISSUE THREAD

**Issue by eyablokov** [Homebrew/homebrew#49441]
Hello.

I'm trying to use 'ansible.runner' module in my Python script, but see the error:

`$ ./uptime.py
Traceback (most recent call last):
  File "./uptime.py", line 3, in <module>
    import ansible.runner
ImportError: No module named ansible.runner`

I investigated what I have.

`$ ls -l /usr/local/Cellar/ansible/2.0.0.2/libexec/lib/python2.7/site-packages/ansible/
-rw-r--r--   1 evgeniy  wheel    888 Jan 15 02:33 __init__.py
drwxr-xr-x   2 evgeniy  wheel    306 Jan 15 02:33 cli
drwxr-xr-x   4 evgeniy  wheel    170 Jan 15 02:33 compat
drwxr-xr-x   2 evgeniy  wheel    102 Jan 15 02:33 config
-rw-r--r--   1 evgeniy  staff  19843 Feb 14 17:13 constants.py
drwxr-xr-x   2 evgeniy  wheel    136 Jan 15 02:33 errors
drwxr-xr-x   3 evgeniy  wheel    374 Jan 15 02:33 executor
drwxr-xr-x   3 evgeniy  wheel    272 Jan 15 02:33 galaxy
drwxr-xr-x   3 evgeniy  wheel    340 Jan 15 02:33 inventory
drwxr-xr-x   2 evgeniy  wheel    986 Feb 14 17:13 module_utils
drwxr-xr-x   4 evgeniy  wheel    170 Jan 15 02:33 modules
drwxr-xr-x   5 evgeniy  wheel    340 Jan 15 02:33 parsing
drwxr-xr-x   3 evgeniy  wheel    646 Jan 15 02:33 playbook
drwxr-xr-x  13 evgeniy  wheel    476 Jan 15 02:33 plugins
drwxr-xr-x   2 evgeniy  wheel    204 Jan 15 02:33 template
drwxr-xr-x   3 evgeniy  wheel    578 Feb 14 17:13 utils
drwxr-xr-x   2 evgeniy  wheel    170 Jan 15 02:33 vars

$ find /usr/local -iname '*runner*' -print
/usr/local/Library/Formula/gitlab-ci-multi-runner.rb
/usr/local/Library/Formula/jetty-runner.rb
/usr/local/Library/Formula/pax-runner.rb
/usr/local/Library/Formula/sonar-runner.rb
/usr/local/Library/Formula/xulrunner.rb
/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/canon-imagerunner-printer-driver-ufrii.rb
/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/coderunner.rb
/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/trailrunner.rb`

There was 'ansible.runner' module before, when I used Ansible 1.9.x versions from Brew.

Please, specify how can I add it now?

Thank you.

**Comment by dunn** [comment]
I'm not sure, but from skimming this http://docs.ansible.com/ansible/developing_api.html it looks like the Python API was re-written for 2.0 and `ansible.runner` doesn't exist anymore.

**Comment by eyablokov** [comment]
I'll try to ask Ansible guys. But there's examples which uses that module.

**Comment by eyablokov** [comment]
I think this issue can be closed, because I found the info: https://github.com/ansible/ansible/issues/14018
That's not Homebrew problem.
