### ISSUE TITLE
ArpON: boneyard

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew#49442]
ArpON appears to need boneyarding.

https://downloads.sourceforge.net/project/arpon/arpon/ArpON-2.7.2.tar.gz is no longer available for download and the current version (https://downloads.sourceforge.net/project/arpon/arpon/ArpON-3.0-ng.tar.gz) does not support OS X.

```
CMake Error at cmake/modules/FindSystem.cmake:43 (message):
  Operating System not supported
Call Stack (most recent call first):
  CMakeLists.txt:77 (find_package)
```

And FindSystem.cmake contains
```
if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    message(STATUS "Building ${PROJECT_NAME} for Operating System: GNU/Linux")
else(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    message(FATAL_ERROR "Operating System not supported")
endif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
```

**Comment by mikemcquaid** [comment]
:+1: to boneyarding.
