### ISSUE TITLE
Request: Add ability to give administrator password to sudo

### ISSUE THREAD

**Issue by mattbell87** [Homebrew/homebrew#49468]
Hi All,

I'm currently building a GUI setup script in QT for my team to automatically install some apps through Homebrew. I want my GUI app to ask for the administrator password. The problem is when `sudo` is called for some apps, there's no easy or reliable way I can see to insert the password.

With **bash** scripts I use this method: https://gist.github.com/mattbell87/90a54e968ed39c9bdf6b which I tried however Homebrew is written in ruby and wont adhere to the bash function as sudo is called directly.

Perhaps a new environment variable could be added to Homebrew, that when set it will pipe in the password whenever sudo is called.

Here is an example of a program that needs sudo to install:
```
Running: brew cask install avast
==> Downloading http://download.ff.avast.com/mac/avast_free_mac_security.dmg

==> No checksum defined for Cask avast, skipping verification

==> Running installer for avast; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.

Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "#<Pathname:/opt/homebrew-cask/Caskroom/avast/latest/Avast Mac Security.pkg>", "-target", "/"]

==> Output of failed command:


==> Exit status of failed command:
#<Process::Status: pid 8735 exit 1>

==> sudo: no tty present and no askpass program specified


'brew cask install avast' exited abnormally with code 1
```

My apologies if it's been asked already, I searched the open and closed issues and couldn't see anything.

Also if this issue relates more to caskroom I can open an issue there too.

**Comment by DomT4** [comment]
> Also if this issue relates more to caskroom I can open an issue there too.

This should probably be submitted there, aye. Homebrew itself doesn't use `sudo` for anything beside initial setup if you use the formal install script.
