### ISSUE TITLE
boost-python builds against built-in python

### ISSUE THREAD

**Issue by bkanuka** [Homebrew/homebrew#49462]
boost-python successfully builds, but is building against the system python.

The build log contains 
`==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost-python/1.60.0 --libdir=/usr/local/Cellar/boost-python/1.60.0/lib --with-libraries=python --with-python=python --with-python-root=/System/Library/Frameworks/Python.framework/Versions/2.7` despite having homebrew python installed.

The issue exists somewhere around line 64 in [boost-python.rb](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boost-python.rb#L64), when ruby calls the external command starting with `python`, it's somehow finding the system python and not the homebrew python. So possibly a path issue?

As far as I can tell, outside this script, `python` always points to the homebrew python. (i.e. my PATH is set correctly).

**Comment by DomT4** [comment]
This is intentional and desired behaviour on our side. I'll let @tdsmith comment more if he wants to, but our dependency logic strongly favours the system Python for consistency.

**Comment by tdsmith** [comment]
The module which is built is compatible with all Python 2.7 interpreters, so this is correct behavior. Please let us know if we can help with anything else.
