### ISSUE TITLE
Can't find cmake with brew install --build-from-source --ignore-dependencies --env=super

### ISSUE THREAD

**Issue by scpeters** [Homebrew/homebrew#49470]
### Bug reports:

I'm having trouble when trying to `brew install` using the `--build-from-source`, `--ignore-dependencies`, and `--env=super` options at the same time if the formula has build dependencies, since the build tools cannot be found. For example, `yaml-cpp` needs cmake but can't invoke it with this options:

~~~
brew install --ignore-dependencies --build-from-source --env=super --verbose yaml-cpp
...
Failed to execute: cmake
~~~

https://gist.github.com/anonymous/eb50a17afb27597a6bbd#file-01-cmake-L14

It works with `--env=std`, but this option is not obvious to new users and may have other side-effects. Should `--ignore-dependencies` and `--build-from-source` be usable with superenv?

**Comment by mikemcquaid** [comment]
As a hunch: it's likely that `--ignore-dependencies` breaks superenv. Why do you need both at once?

**Comment by scpeters** [comment]
Actually, it's more of a usability issue because `superenv` was the default setting, and I didn't know how to fix it. I should have stated that in the original posting. If you remove the `--env=super` on my machine, it fails, but it's not obvious that the environment parameter is involved. It actually took me a while to realize that it was related to `superenv`.

**Comment by mikemcquaid** [comment]
Why do you need both at once?

**Comment by scpeters** [comment]
I don't need both at once, but `superenv` is on by default on my machine and was causing failures that were hard to debug. I managed to workaround with `--env=std` but it was only after lots of frustration.

**Comment by scpeters** [comment]
To be clear, I was never explicitly calling `--env=super`; I only added that after debugging and finding out that was the cause of my problems. It seems that superenv is the default and is used unless it is explicitly over-ridden.

I'm sorry if my initial report wasn't clear, I was trying to help. I still think there is a problem. Let me try to restate it:

`brew install --build-from-source --ignore-dependencies` will fail unless `--env=std` is set manually, either in the formula or with a command-line argument `--env=std`.

**Comment by scpeters** [comment]
Did this get closed because the description was poor? I've update the title and first comment to be more clear.

**Comment by scpeters** [comment]
I resubmitted as #49544
