### ISSUE TITLE
Please update pyrax in duplicity bottle

### ISSUE THREAD

**Issue by renard** [Homebrew/homebrew#49498]
`duplicity` bottle comes with `pyrax` 1.9.6 (at this time 1.9.7 is available).

The problem is that `pyrax` 1.9.6 refers to `novaclient.v1_1` which is not included in `python_novaclient` 3.2.0 bundled in `duplicity` bottle.

Is there a simple way to generate `duplicity` bottle with `pyrax` 1.9.7

PS: a workaround is to install pyrax using pip and patching the `/usr/local/Cellar/duplicity/0.7.06_1/bin/duplicity` wrapper:

```
pip install pyrax
```

```diff
--- /usr/local/Cellar/duplicity/0.7.06_1/bin/duplicity.orig	2016-02-24 23:21:03.000000000 +0100
+++ /usr/local/Cellar/duplicity/0.7.06_1/bin/duplicity	2016-02-24 23:21:33.000000000 +0100
@@ -1,2 +1,2 @@
 #!/bin/bash
-PYTHONPATH="/usr/local/Cellar/duplicity/0.7.06_1/libexec/vendor/lib/python2.7/site-packages:/usr/local/Cellar/duplicity/0.7.06_1/libexec/lib/python2.7/site-packages" exec "/usr/local/Cellar/duplicity/0.7.06_1/libexec/bin/duplicity" "$@"
+PYTHONPATH="/usr/local/lib/python2.7/site-packages:/usr/local/Cellar/duplicity/0.7.06_1/libexec/vendor/lib/python2.7/site-packages:/usr/local/Cellar/duplicity/0.7.06_1/libexec/lib/python2.7/site-packages" exec "/usr/local/Cellar/duplicity/0.7.06_1/libexec/bin/duplicity" "$@"
```

**Comment by dunn** [comment]
The way to do this is to update the vendored `pyrax` here: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/duplicity.rb#L236-L239

Then change `revision 1` to `revision 2` (just below the `sha256`) so that all users get the update.

If you can open a pull request to do that, we'd love it! Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have further questions.

**Comment by renard** [comment]
@dunn thnaks for the quick answer.

BTW the default install sets files under `/usr/local/Cellar/duplicity/0.7.06_1/libexec/vendor/lib/python2.7/site-packages/prettytable-0.7.2-py2.7.egg-info/` to `0600` which can be problematic. 

I don't know why.

I have to manually enable to all users via:

```
sudo chmod 644 /usr/local/Cellar/duplicity/0.7.06_1/libexec/vendor/lib/python2.7/site-packages/prettytable-0.7.2-py2.7.egg-info/*
```


Any clues?

**Comment by dunn** [comment]
If it happens with you install duplicity outside of Homebrew, then it's probably an upstream issue.  Otherwise you can add `chmod` calls; Homebank has an example: [`homebank.rb`](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/homebank.rb#L29).

**Comment by renard** [comment]
@dunn Thanks again for the quick and right answer. #49499 fix this issue. Let me know if something is wrong.

**Comment by DomT4** [comment]
Closing in favour of https://github.com/Homebrew/homebrew/pull/49499.
