### ISSUE TITLE
Feature request: topo sort `brew deps <formula>`

### ISSUE THREAD

**Issue by zbeekman** [Homebrew/homebrew#49493]
It would be great if `brew deps <formula>` would [topo sort](https://en.wikipedia.org/wiki/Topological_sorting) the dependencies so that they can be manually iterated over to install/bottle/etc. in correct order.

**Comment by mikemcquaid** [comment]
> manually iterated over to install/bottle/etc. in correct order.

Can you go back a bit here and tell us what you're trying to do?

**Comment by zbeekman** [comment]
My main motivation here is to use LinuxBrew for dependency management on containerize Travis-CI instances. I want to be able to use GCC 5.3 on these containerized Travis-CI VMs built with `--without-multilib` and other packages with non standard flags. The problem is that building from source on Travis-CI takes too long. My goal is to be able to fire up an identical VM as a Travis-CI VM (or choose your preferred CI provider) and create one or more bottles that I can then download and install on those VMs. I may misunderstand the way Homebrew works, but, I think there could be two hinderances to this approach:

 1) Certain packages require dependencies to be built with non-standard flags. Therefore I would like to be able to guarantee that all dependencies can be installed from bottles before installing (from source or bottle) any dependency in question
 2) I don't think LinuxBrew provides bottles, due to the diversity of distros

My concern is that if I install dependencies from bottles in the wrong order, this could be problematic, or trigger a non-bottled build of the dependency's dependency.

**Comment by mikemcquaid** [comment]
The best solution for this case is probably to create a custom tap in which you create bottles for these yourself or making use of the bottle hooks: https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/hooks/bottles.rb

**Comment by zbeekman** [comment]
I still think topo sorting `brew deps`  could be handy.... and not too hard to implement.... but I know you guys are overworked and under payed :money_with_wings:

**Comment by bfontaine** [comment]
> and under payed

You mean “**not** payed” :smile:

**Comment by zbeekman** [comment]
Yes, that was the joke... My sense of humor may be too dry for the internet...
