### ISSUE TITLE
Cannot run brew update

### ISSUE THREAD

**Issue by viper101** [Homebrew/homebrew#49502]
I've been trying to run brew update and I received the below error:

error: Your local changes to the following files would be overwritten by merge:
	Library/brew.rb
Please, commit your changes or stash them before you can merge.
Aborting
Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master

Following advice found online I subsequently then ran brew doctor and received the below:
Warning: Ruby version 2.0.0 is unsupported.
Homebrew is developed and tested on Ruby 1.8.x, and may not work correctly
on other Rubies. Patches are accepted as long as they don't break on 1.8.x.
Error: Homebrew doesn't know what compiler versions ship with your version
of Xcode (7.2.1).

So I'm stuck on a catch 22- I can't run brew update, and brew doctor reports there's an issue with my version of Xcode and to run brew update to resolve the issue. Has anyone come across this?

brew --config -
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/mxcl/homebrew
HEAD: 69a83176bb571233220788515228827b9468a6ed
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.11.3-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby

**Comment by bfontaine** [comment]
Please run `cd /usr/local && git reset --hard origin/master` then `brew update` again.

**Comment by viper101** [comment]
That's fixed the issue bfontaine :+1: Much appreciated!
