### ISSUE TITLE
brew update fails

### ISSUE THREAD

**Issue by lrothack** [Homebrew/homebrew#49514]
### Bug reports:
` waltz:~ leonard$ brew update` 
/usr/local/Library/Homebrew/cmd/update.sh: line 370: `homebrew-update': not a valid identifier

`brew doctor` runs successfully, i.e., there is no message on the command line

`brew config`
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 745acf4966f0f9dd113b5eb0938a73acd395a0cf
Last commit: 46 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.11.3-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
GCC-4.2: build 5666
Clang: 7.0 build 700
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_66, 1.7.0_51

**Comment by xu-cheng** [comment]
Could you report `cd /usr/local && git status`?

**Comment by lrothack** [comment]
`waltz:~ leonard$ cd /usr/local/`
`waltz:local leonard$ git status`
On branch master
nothing to commit, working directory clean

**Comment by xu-cheng** [comment]
Could you try to run `brew update --debug`?

**Comment by lrothack** [comment]
It is the same problem:

`waltz:~ leonard$ brew update --debug`
/usr/local/Library/Homebrew/cmd/update.sh: line 370: `homebrew-update': not a valid identifier

**Comment by mikemcquaid** [comment]
@lrothack Could you paste the output of `echo $SHELL` and `echo $PATH`? Thanks!

**Comment by lrothack** [comment]
`waltz:~ leonard$ echo $SHELL`
/bin/bash
`waltz:~ leonard$ echo $PATH `
/Users/leonard/bin:/Users/leonard/esmeralda/bin:/usr/local/sbin:/usr/local/bin:/Users/leonard/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin

**Comment by mikemcquaid** [comment]
@lrothack Can you try `/bin/bash /usr/local/bin/brew update`?

**Comment by lrothack** [comment]
`waltz:~ leonard$ /bin/bash /usr/local/bin/brew update`
/usr/local/Library/Homebrew/cmd/update.sh: line 370: `homebrew-update': not a valid identifier

**Comment by mikemcquaid** [comment]
@lrothack Very odd. Can I see your `set | grep -aiE "(bash|shell|posix)"`?

**Comment by lrothack** [comment]
Thanks, this hint solved the problem for me :)
I set the environment variable `POSIXLY_CORRECT=1` that I need for another program. 
Unsetting this solves the problem and `brew update` works without problems again.

Until a few days ago this has been working fine with homebrew. Is this expected behaviour?

Sorry for the confusion and thank you so much for your help!



`waltz:~ leonard$ set | grep -aiE "(bash|shell|posix)"`
BASH=/bin/bash
BASH_ARGC=()
BASH_ARGV=()
BASH_COMPLETION=/usr/local/etc/bash_completion
BASH_COMPLETION_COMPAT_DIR=/usr/local/etc/bash_completion.d
BASH_COMPLETION_DIR=/usr/local/etc/bash_completion.d
BASH_LINENO=()
BASH_REMATCH=([0]="d")
BASH_SOURCE=()
BASH_VERSINFO=([0]="3" [1]="2" [2]="57" [3]="1" [4]="release" [5]="x86_64-apple-darwin15")
BASH_VERSION='3.2.57(1)-release'
HISTFILE=/Users/leonard/.bash_sessions/1EECF134-B532-4C0F-B5CA-27C07C520313.historynew
POSIXLY_CORRECT=1
SHELL=/bin/bash
SHELLOPTS=braceexpand:emacs:hashall:histexpand:history:interactive-comments:monitor:posix
SHELL_SESSION_DID_INIT=1
SHELL_SESSION_DIR=/Users/leonard/.bash_sessions
SHELL_SESSION_FILE=/Users/leonard/.bash_sessions/1EECF134-B532-4C0F-B5CA-27C07C520313.session
SHELL_SESSION_HISTFILE=/Users/leonard/.bash_sessions/1EECF134-B532-4C0F-B5CA-27C07C520313.history
SHELL_SESSION_HISTFILE_NEW=/Users/leonard/.bash_sessions/1EECF134-B532-4C0F-B5CA-27C07C520313.historynew
SHELL_SESSION_HISTFILE_SHARED=/Users/leonard/.bash_history
SHELL_SESSION_HISTORY=1
SHELL_SESSION_TIMESTAMP_FILE=/Users/leonard/.bash_sessions/_expiration_check_timestamp

**Comment by mikemcquaid** [comment]
@lrothack Glad that fixed it, thanks!

**Comment by mikemcquaid** [comment]
@lrothack https://github.com/Homebrew/homebrew/pull/49515 should stop this happening to anyone else.
