### ISSUE TITLE
boost155 fails to build with HOMEBREW_CXX=g++-5

### ISSUE THREAD

**Issue by kilojoules** [Homebrew/homebrew#49537]
boost155 failed to install for me. I have HOMEBREW_CC/CXX set to gcc-5/g++-5. boost155 does successfully install when HOMEBREW_CC/CXX is set to clang/clang++.

    $ brew gist-logs boost155
    https://gist.github.com/80b8b82db6d90ba2f0e9
    
    
    $ brew install boost155 --with-mpi --with-python --without-single
    ==> Installing boost155 from homebrew/versions
    ==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.55.0/boost_1_55_0.tar.bz2
    Already downloaded: /Library/Caches/Homebrew/boost155-1.55.0.tar.bz2
    ==> Downloading https://github.com/boostorg/atomic/commit/6bb71fdd.diff
    Already downloaded: /Library/Caches/Homebrew/boost155--patch-eb139160a33d8ef3e810ce3e47da278563d03d7be6d0a75c109f708030a7abcb.diff
    ==> Downloading https://github.com/boostorg/atomic/commit/e4bde20f.diff
    Already downloaded: /Library/Caches/Homebrew/boost155--patch-8c5efeea91d44b2a48fdeee9cde71e831dad78f0930e8f65b7223ba0ecdfec9b.diff
    ==> Downloading https://github.com/boostorg/chrono/commit/143260d.diff
    Already downloaded: /Library/Caches/Homebrew/boost155--patch-f6f40b576725b15ddfe24497ddcd597f387dfdf674f6dd301b8dcb723593ee22.diff
    ==> Downloading https://gist.githubusercontent.com/philacs/375303205d5f8918e700/raw/d6ded52c3a927b6558984d22efe0a5cf9e59cd8c/0005-Boost.S11n-include-missing-algorithm.p
    Already downloaded: /Library/Caches/Homebrew/boost155--patch-cb134e3982e01ba5b3d5abe51cc8343c9e24ecd34aa4d81f5e8dd4461f593cf1.patch
    ==> Patching
    ==> Applying 6bb71fdd.diff
    patching file boost/atomic/detail/cas128strong.hpp
    ==> Applying e4bde20f.diff
    patching file boost/atomic/detail/gcc-atomic.hpp
    ==> Applying 143260d.diff
    patching file boost/chrono/config.hpp
    patching file boost/chrono/detail/inlined/mac/thread_clock.hpp
    ==> Applying 0005-Boost.S11n-include-missing-algorithm.patch
    patching file boost/archive/iterators/transform_width.hpp
    ==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost155/1.55.0_1 --libdir=/usr/local/Cellar/boost155/1.55.0_1/lib --without-icu --without-libraries=
    ==> ./b2 --prefix=/usr/local/Cellar/boost155/1.55.0_1 --libdir=/usr/local/Cellar/boost155/1.55.0_1/lib -d2 -j4 --layout=tagged --user-config=user-config.jam install thr
    Last 15 lines from /Users/jquick/Library/Logs/Homebrew/boost155/02.b2:
         static const error_category &  errno_ecat     = generic_category();
                                        ^
    ./boost/system/error_code.hpp:224:36: warning: 'boost::system::native_ecat' defined but not used [-Wunused-variable]
         static const error_category &  native_ecat    = system_category();
                                        ^
    darwin.compile.c++ bin.v2/libs/wave/build/darwin-5.3.0/release/link-static/threading-multi/cpplexer/re2clex/cpp_re.o
    
        "g++-5"  -ftemplate-depth-128 -O3 -finline-functions -Wno-inline -w -gdwarf-2 -fexceptions  -DBOOST_ALL_NO_LIB=1 -DBOOST_THREAD_USE_LIB=1 -DNDEBUG  -I"." -c -o "bin.v2/libs/wave/build/darwin-5.3.0/release/link-static/threading-multi/cpplexer/re2clex/cpp_re.o" "libs/wave/src/cpplexer/re2clex/cpp_re.cpp"
    
    ...skipped <pbin.v2/libs/wave/build/darwin-5.3.0/release/link-static/threading-multi>libboost_wave-mt.a(clean) for lack of <pbin.v2/libs/wave/build/darwin-5.3.0/release/link-static/threading-multi>instantiate_cpp_exprgrammar.o...
    ...skipped <pbin.v2/libs/wave/build/darwin-5.3.0/release/link-static/threading-multi>libboost_wave-mt.a for lack of <pbin.v2/libs/wave/build/darwin-5.3.0/release/link-static/threading-multi>instantiate_cpp_exprgrammar.o...
    ...skipped <p/usr/local/Cellar/boost155/1.55.0_1/lib>libboost_wave-mt.a for lack of <pbin.v2/libs/wave/build/darwin-5.3.0/release/link-static/threading-multi>libboost_wave-mt.a...
    ...failed updating 12 targets...
    ...skipped 12 targets...
    ...updated 11867 targets...
    
    READ THIS: https://git.io/brew-troubleshooting
    If reporting this issue please do so at (not Homebrew/homebrew):
      https://github.com/Homebrew/homebrew-versions/issues

**Comment by mikemcquaid** [comment]
> boost155 failed to install for me. I have HOMEBREW_CC/CXX set to gcc-5/g++-5. boost155 does successfully install when HOMEBREW_CC/CXX is set to clang/clang++.

Sorry, we don't support build errors when using a non-default compiler.
