### ISSUE TITLE
brew install --build-from-source --ignore-dependencies usually fails because of superenv

### ISSUE THREAD

**Issue by scpeters** [Homebrew/homebrew#49544]
### Bug reports:

I'm having trouble when trying to `brew install` using the `--build-from-source` and `--ignore-dependencies` options at the same time if the formula has build dependencies, since the default superenv prevents the build tools from being found. For example, `yaml-cpp` needs cmake but can't invoke it with these options:

~~~
brew install --ignore-dependencies --build-from-source --verbose yaml-cpp
...
Failed to execute: cmake
~~~

https://gist.github.com/anonymous/eb50a17afb27597a6bbd#file-01-cmake-L14

A workaround is to use `--env=std`. Is it reasonable to suggest the `--env=std` option in a console message when builds fail with `--ignore-dependencies`? If so, I'll work on a pull request.

Note, this was previously submitted as #49470 but was closed due to a lack of clarity in the issue description (I think).

**Comment by DomT4** [comment]
> Is it reasonable to suggest the --env=std option in a console message when builds fail with --ignore-dependencies? 

I'd rather we throw ` --ignore-dependencies` under the bus and make it a no-op before we start telling people `--env=std` is a good idea if those are the options open to us, but that's just me.

I'm not sure there was ever any real expectation that `--ignore-dependencies` _wouldn't_ break `superenv` though?

**Comment by scpeters** [comment]
Is it reasonable for the `--ignore-dependencies` step to only skip dependency installation, while still allowing the superenv to know which dependencies should be added to the environment?

Sometimes I get impatient when trying to build a formula and it wants to upgrade a bunch of dependencies. Instead of trying to pin formulae to a specific version, I've tried using `--ignore-dependencies` to just skip the dependency installation step, but the superenv then doesn't seem to know about the dependencies so the build fails.

The more I talk about it, the more it's sounding like I'm a weirdo and probably no one else ever does this. If that's the case, we can close this again and I'll use `--env=std`, knowing that it's a hack and not the best idea.
