### ISSUE TITLE
Python3 fails due to C compiler

### ISSUE THREAD

**Issue by kosigz** [Homebrew/homebrew#49552]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Cannot get python3 as formula fails with output...

checking build system type... x86_64-apple-darwin15.3.0
checking host system type... x86_64-apple-darwin15.3.0
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... darwin
checking for --without-gcc... yes
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/tmp/python320160226-23886-ixsdmx/Python-3.5.1':
configure: error: C compiler cannot create executables
See `config.log' for more details

https://gist.github.com/anonymous/8e6156942c58269d2be9

**Comment by mikemcquaid** [comment]
> Ran brew doctor, fixed as many issues as possible and retried your prior step?

Your `brew doctor` still has a lot of issues that are likely causing the issues: https://gist.github.com/anonymous/8e6156942c58269d2be9#file-00-doctor-out

**Comment by tdsmith** [comment]
In particular, you need to upgrade Xcode.

**Comment by DomT4** [comment]
Closing here. Please let us know if you require further assistance after upgrading Xcode to the latest release, Thanks!
