### ISSUE TITLE
tokyo-tyrant: unable to detect libs with pkg-config

### ISSUE THREAD

**Issue by rubenk** [Homebrew/homebrew#49569]
I'm trying to get collectd to build it's tokyo-tyrant plugin, but pkg-config can't find the .pc file for tokyo-tyrant.

My collectd.rb has a `depends_on "tokyo-tyrant"`

When I do an interactive installation, and run pkg-config --list-all, tokyo-tyrant is missing.

It does install a .pc file, but perhaps this is in the wrong location?
```
$ find homebrew/ -name tokyotyrant.pc
homebrew//Cellar/tokyo-tyrant/1.1.41_1/libexec/lib/pkgconfig/tokyotyrant.pc
```

**Comment by DomT4** [comment]
It was moved to `libexec` because the `lib` directory contains files that we don't like leaving in the top-level prefix. A solution would be to symlink the `libexec/"lib/pkgconfig"` directory into `prefix/lib/pkgconfig`. That would be acceptable.

**Comment by rubenk** [comment]
Thanks for your fast response. Makes sense, I'll see what I can do.
