### ISSUE TITLE
Openssl 1.0.2f fails to build on El Capitan

### ISSUE THREAD

**Issue by noirchen** [Homebrew/homebrew#49602]
I was trying to build openssl on my imac running 10.11, but encountered this build error

$ brew install openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2f.tar.gz
######################################################################## 100.0%
==> Downloading https://github.com/openssl/openssl/commit/da7947e8c6915d86616425
######################################################################## 100.0%
==> Downloading https://github.com/openssl/openssl/commit/7107798ae6c5e19f581915
######################################################################## 100.0%
==> Downloading https://github.com/openssl/openssl/commit/83ab6e55a1f8de9b3e45d1
######################################################################## 100.0%
==> Patching
==> Applying da7947e8c6915d86616425ecbc4906f079ef122f.diff
patching file crypto/bio/bio.h
==> Applying 7107798ae6c5e19f581915928a69073d17cc21ab.diff
patching file crypto/dh/dh.h
==> Applying 83ab6e55a1f8de9b3e45d13dcc78eb739dc66dea.diff
patching file crypto/dh/dh_check.c
==> perl ./Configure --prefix=/Applications/homebrew/Cellar/openssl/1.0.2f --ope
==> make depend
==> make
==> make test
==> make install MANDIR=/Applications/homebrew/Cellar/openssl/1.0.2f/share/man M
Last 15 lines from /Users/jiangzhi/Library/Logs/Homebrew/openssl/05.make:
	fi
installing gost
making install in apps...
installing openssl
installing CA.sh
installing CA.pl
installing tsget
making install in test...
make[1]: Nothing to be done for 'install'.
making install in tools...
cp: /Applications is a directory (not copied).
chmod: /Applications/homebrew/Cellar/openssl/1.0.2f/bin//Applications.new: No such file or directory
mv: rename /Applications/homebrew/Cellar/openssl/1.0.2f/bin//Applications.new to /Applications/homebrew/Cellar/openssl/1.0.2f/bin//Applications: No such file or directory
make[1]: *** [install] Error 1
make: *** [install_sw] Error 1

More complete logs are in
https://gist.github.com/anonymous/d9634f92714cc4fc0f52

At first I thought the culprit could be anaconda, but commenting anaconda out of the path does not change the result.  And the strange "//" in the last few lines suggest that the build was successful but something is messed in the path. I do have the homebrew folder placed in /Applications, and I wonder whether openssl can only be installed to `/usr/local`.

**Comment by tdsmith** [comment]
Do you have an environment variable set called `APPS`?

**Comment by tdsmith** [comment]
I'm curious because of this section of tools/Makefile:

```make
APPS= c_rehash
MISC_APPS= c_hash c_info c_issuer c_name

all:

install:
        @[ -n "$(INSTALLTOP)" ] # should be set by top Makefile...
        @for i in $(APPS) ; \
        do  \
        (cp $$i $(INSTALL_PREFIX)$(INSTALLTOP)/bin/$$i.new; \
        chmod 755 $(INSTALL_PREFIX)$(INSTALLTOP)/bin/$$i.new; \
        mv -f $(INSTALL_PREFIX)$(INSTALLTOP)/bin/$$i.new $(INSTALL_PREFIX)$(INSTALLTOP)/bin/$$i ); \
        done;
```

**Comment by noirchen** [comment]
Yes, it’s /Applications. I have been using this environment variable long ago and homebrew packages work fine with it.

**Comment by tdsmith** [comment]
openssl doesn't. :) If you unset it before building openssl from source, you should be fine. Let us know if we can help with anything else.
