### ISSUE TITLE
SHA256 mismatch when installing apktool

### ISSUE THREAD

**Issue by lihehub** [Homebrew/homebrew#49619]
`$ brew install apktool`
>==> Downloading https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.0.3.jar
>==> Downloading from https://bbuseruploads.s3.amazonaws.com/0becf6a1-1706-4f2e-9ae6-891e00a8dd5f/downloads/48b2298c-1e77-4513-b376-3d4d9c326a94/apktool_2.0.3.jar?Signature=Q14hKrU5Y
>
>Error: SHA256 mismatch
>Expected: ceca3e49bfc697c918aaff160c28244f27a2c1c741af62a70e1558a066a16dd3
>Actual: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
>Archive: /Library/Caches/Homebrew/apktool-2.0.3.jar
>To retry an incomplete download, remove the file above.

`$ curl -sL "https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.0.3.jar" | sha256sum `
>e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  -

**Comment by dunn** [comment]
I'm also getting a mismatch, but the SHA I see is `ceca3e49bfc697c918aaff160c28244f27a2c1c741af62a70e1558a066a16dd3`.

Mind checking with the developers to see if they've repackaged 2.0.3?

**Comment by javian** [comment]
This has been fixed by the repo maintainers by re-uploading the file and should now work as expected.

**Comment by lihehub** [comment]
This issue has been verified. Close it.
