### ISSUE TITLE
mutt fails to build on systems without an admin group, including ubuntu trusty

### ISSUE THREAD

**Issue by marklee77** [Homebrew/homebrew#49644]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

commit 60595085dd25b19397cdcae1bca2f871236ce0ce introduced an issue where the mutt formula will fail to build if there is no "admin" user present on the system. I had to manually undo the commit to install with user permissions on ubuntu 14.04.4.

I think at least that the formula should behave the same if the user is not in the admin group and if there is no admin group. It might also be good to allow for a user-specified admin group name in the user-supplied build parameters.

**Comment by chdiza** [comment]
This should be reported to Linuxbrew.

**Comment by DomT4** [comment]
I'll double check this with the other maintainers but I'm not sure it's possible to run an OS X installation without having an `admin` _group_ available even if the user isn't part of it, and if that's the case this should be shunted over to Linuxbrew indeed.

**Comment by apjanke** [comment]
On OS X, `admin` is one of the default groups and a core part of how system security is configured out of the box. If you remove it, your system is effectively hosed. So it might be possible to reconfigure an OS X system to run without `admin`, but that's well in to unsupported territory for the OS. I wouldn't think it's a case Mac Homebrew should support.

**Comment by marklee77** [comment]
ah, okay, I'll take this up with linuxbrew.
