### ISSUE TITLE
open-mpi requires Java

### ISSUE THREAD

**Issue by spott** [Homebrew/homebrew#49698]
I think extraneous build requirements are a bug.  Java is *not* required for open-mpi.  On a Mac, it builds with the `depends_on :java => :build` line removed, and on linux [this](https://www.open-mpi.org/faq/?category=building#build-tools) makes it clear that java is not required.  Unfortunately, I can't check weather the issue that caused this line to be added in the first place is still a problem because I don't have access to a linux installation.  There are java bindings for open-mpi, but they should be added on an as-needed basis, rather than requiring everyone to build java support.

Has anyone looked to see if this is still an issue in linux?

See: Homebrew/homebrew issue #39962 and Linuxbrew/linuxbrew issue #365 and Homebrew/homebrew issue #33177

**Comment by mikemcquaid** [comment]
> Has anyone looked to see if this is still an issue in linux?

Homebrew is an OS X package manager so we do not support Linux.

**Comment by spott** [comment]
>Homebrew is an OS X package manager so we do not support Linux.

The issue that was referenced when the java dependency was added was #39962, which just referenced the Linuxbrew issue.  Since that was the only reason given for making the change in the first place as far as I can tell (it works fine on Mac without the java dependency), and homebrew doesn't support linux, can we revert and remove the dependency on Java, and let Linuxbrew sort it out on their end?

**Comment by mikemcquaid** [comment]
@spott If it doesn't seem to be needed on OS X :+1: to removing it. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by spott** [comment]
I think I've got everything.  Let me know if there is anything else that I need to do.
