### ISSUE TITLE
Willing to rename wxmac to wxwidgets?

### ISSUE THREAD

**Issue by rwhogg** [Homebrew/homebrew#49690]
wxmac builds on Linuxbrew now thanks to Linuxbrew/Linuxbrew#857. As such, the name wxmac no longer really makes sense.

Would you be willing to rename the package to something that reflects that it's not exclusively for OS X? `wxwidgets` is the most obvious choice.

Thanks!

**Comment by tdsmith** [comment]
We can add an alias, or Linuxbrew can add an alias; I'm fine either way.

**Comment by tdsmith** [comment]
In fact, there is already an alias; `brew install wxwidgets` works. I'm +0 on renaming.

**Comment by mikemcquaid** [comment]
@rwhogg I think it would be good if you could avoid creating Linuxbrew issues here; Homebrew does not support Linux and we're not really interested in making these sorts of changes when Linuxbrew can make them downstream. Thanks!

**Comment by rwhogg** [comment]
Certainly; I'll avoid doing that in the future. My apologies.
