### ISSUE TITLE
Update Racket Formula to 6.4?

### ISSUE THREAD

**Issue by Kinnardian** [Homebrew/homebrew#49699]
Time to update to racket 6.4? https://github.com/Homebrew/homebrew/blob/master/Library/Formula/racket.rb
https://download.racket-lang.org/v6.4.html
New here, didn't know if a pull request was the move.

**Comment by bfontaine** [comment]
We’d appreciate a pull-request, thanks!
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

**Comment by Kinnardian** [comment]
Pertinent: https://github.com/Homebrew/homebrew/issues/49700

**Comment by rprimus** [comment]
Mon Mar  7 00:48:09 GMT 2016

@Kinnardian - racket 6.4 is now available (via pull request #49832).
