### ISSUE TITLE
NGINX failed to build on 10.11.3

### ISSUE THREAD

**Issue by jpartain89** [Homebrew/homebrew#49701]
### Bug reports:

When I try to build NGINX, or most any other application based off of C Compiler, they won't build. 

https://gist.github.com/b5c0db02cbb9ec5422f1

Not quite sure the next steps outside of here!

**Comment by dunn** [comment]
Does Clang work outside of Homebrew?  Can you compile a simple program, e.g.:
```c
#include <stdio.h>

int main() {
  printf("Hello");
}
```
with `clang test.c`?

**Comment by DomT4** [comment]
Ping?

**Comment by DomT4** [comment]
Closing here, but please do shout if you need further assistance and one of us will reopen. Thanks!
