### ISSUE TITLE
Formula request: google-cloud-sdk

### ISSUE THREAD

**Issue by twmartin** [Homebrew/homebrew#49705]
Could a formula please be added for [google-cloud-sdk](https://cloud.google.com/sdk/)?

**Comment by DomT4** [comment]
They don't seem to ship a from-source installation option, which is what we'd require. The Caskroom already have a [cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/google-cloud-sdk.rb) which seems a better fit. You should be able to use that with:

```
brew cask install caskroom/cask/google-cloud-sdk
```

**Comment by twmartin** [comment]
Thanks!
