### ISSUE TITLE
Renaming racket/minimal-racket formula?

### ISSUE THREAD

**Issue by Kinnardian** [Homebrew/homebrew#49700]
Why does the [`racket` formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/racket.rb) install minimal racket?? 

Shouldn't a `racket` formula install racket and a `minimal-racket` formula install minimal racket? Can this be renamed?

**Comment by tdsmith** [comment]
What's the difference?

**Comment by Kinnardian** [comment]
"The main Racket distribution has been separated into about 200 packages. The Racket installer combines the core system with bundled versions of these packages.
Alternatively, you may now install a Minimal Racket distribution — which is about 1/10 the size of the main distribution — and add only those packages that you need."
— http://blog.racket-lang.org/2014/02/racket-v60.html

In particular it came to my attention that minimal racket is missing mzscheme: https://github.com/arclanguage/anarki/issues/29#issuecomment-183050231

**Comment by tdsmith** [comment]
Pinging rocket formula contributors @bukzor, @rprimus, @stuwil, @guoxiao, @metabr -- is there a consensus about whether the rocket formula should package Minimal Racket versus a more comprehensive racket distribution?

**Comment by rprimus** [comment]
Sun Mar  6 23:13:50 GMT 2016

I prefer the (current) minimal build - as I don't use DrRacket (gui).  Would it make sense to have the full racket be installed from as Cask?

**Comment by mikemcquaid** [comment]
@rprimus's reasoning seems good enough to me.
