### ISSUE TITLE
Specify User-Agent to bypass proxy

### ISSUE THREAD

**Issue by ErikWAberg** [Homebrew/homebrew#49711]
Line 30 in `Library/Homebrew/utils.rb` specifies a Homebrew User-Agent as shown below:
`HOMEBREW_USER_AGENT = "Homebrew #{HOMEBREW_VERSION} (Ruby #{RUBY_VERSION}-#{RUBY_PATCHLEVEL}; #{OS_VERSION})"`

However, this overrides any modifications I have made to the curl user-agent defined in `~/.curlrc`, for example:
`user-agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36"`.

Is it possible to override the `HOMEBREW_USER_AGENT` without resorting to edit  `Library/Homebrew/utils.rb`?

**Comment by bfontaine** [comment]
We don’t allow this. See #47265, especially Mike’s comment at the end.
