### ISSUE TITLE
Postgis could not find geos-config

### ISSUE THREAD

**Issue by Kinad** [Homebrew/homebrew#49717]
Hi all, 
I'm trying to install Postgis on OSX 10.8.5 but i can't find a solution to the "configure: error: could not find geos-config within the current path".
I tried "brew install postgis --with-geosconfig=/usr/local/bin" but the same error still occur. Looks like the --with-geosconfig argument is not considerate in the ./configure because whatever I always see "./configure --with-projdir=/usr/local/opt/proj --with-jsondir=/usr/local/opt" even if I write the --with-geosconfig arg.
```
Brew install postgis ----with-geosconfig=/usr/local/bin
Downloading http://download.osgeo.org/postgis/source/postgis-2.2.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/postgis-2.2.1.tar.gz
==> ./configure --with-projdir=/usr/local/opt/proj --with-jsondir=/usr/local/opt
Last 15 lines from /Users/Thomas/Library/Logs/Homebrew/postgis/01.configure:
checking libxml/tree.h usability... yes
checking libxml/tree.h presence... yes
checking for libxml/tree.h... yes
checking libxml/parser.h usability... yes
checking libxml/parser.h presence... yes
checking for libxml/parser.h... yes
checking libxml/xpath.h usability... yes
checking libxml/xpath.h presence... yes
checking for libxml/xpath.h... yes
checking libxml/xpathInternals.h usability... yes
checking libxml/xpathInternals.h presence... yes
checking for libxml/xpathInternals.h... yes
checking for xmlInitParser in -lxml2... yes
checking for geos-config... no
configure: error: could not find geos-config within the current path. You may need to try re-running configure with a --with-geosconfig parameter.
```
Can someone help me ?

**Comment by dunn** [comment]
From your other issue, I'd try removing this `gdal-config` out of the way and trying again: https://gist.github.com/anonymous/91a061aafde1403b6d91#file-00-doctor-out-L13

**Comment by Kinad** [comment]
Thanks for your answer @dunn . Finally I decided to say goodbye to OSX 10.8.5 for multiple reason and decided to migrate to 10.11.3 with a clean install, and everything is fine
