### ISSUE TITLE
Question about bottled OpenMPI on Travis-CI

### ISSUE THREAD

**Issue by zbeekman** [Homebrew/homebrew#49738]
I would like to bottle OpenMPI built using GCC as the C and CXX compiler, so that my Travis-CI instances can just pour the bottle rather than time out while building from source. However I build them on my home machine (Yosemite, same as the Travis-CI instance) but then on the Travis VM mpif90 fails: https://travis-ci.org/zbeekman/opencoarrays/jobs/112774012#L303 I noticed that OpenMPI is not `Cellar :any` and that mpif90 won't run due to `Cannot open configuration file`. Upon further investigation my laptop's Cellar is `/usr/local/homebrew/cellar` whereas I think the Cellar on Travis-ci is `/usr/local/Cellar`

This brings me to my question: Can I just make a bottle on a virtual machine rather than my laptop, so that the Cellar location will match and have this issue resolved? Could there be another problem causing this issue?

I was just hoping to get some feedback before traveling down the relatively long  road that is building a Yosemite VM with Vagrant and packer.

Thanks

**Comment by tdsmith** [comment]
> Can I just make a bottle on a virtual machine rather than my laptop, so that the Cellar location will match and have this issue resolved?

That should work!

**Comment by zbeekman** [comment]
sweet, thanks for the insight... because... apparently I have no life.... I decided to  give this a shot. Building the VMs take forever, so I'm just now installing homebrew and GCC... I'll report back if I am successful.

**Comment by zbeekman** [comment]
That did indeed seem to fix the issue, thanks for the help @tdsmith https://travis-ci.org/zbeekman/opencoarrays/jobs/113314303
