### ISSUE TITLE
apparently it's not possible for a brew formula to depend on a cask

### ISSUE THREAD

**Issue by pmoody-** [Homebrew/homebrew#49778]
apologies if there's a better place for this, as this might be more of a question and/or feature request than a bug report.

I have a brew formula that depends on a bunch of other brew formulas like

`depends_on "myniftything" => :recommended`

and now I'd like it to depend on a cask, but I don't seem to have any way of doing that. The relative paths are

`
homebrew-alt/mainforumla.rb
homebrew-alt/Casks/newcask.rb
`

and right now, people install mainformula with `brew install mainformula`. `brew cask install newcask` works just fine, but I'd like to set it up so that `brew install mainformula` pulls in `newcask` with it.

None of the incantations I've tried, with like `depends_on :cask => 'newcask'` or `depends_on 'casks/newcask' => :recommended` have worked.

**Comment by DomT4** [comment]
Write a custom in-formula requirement like [this](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/compcert.rb#L1-L11) which has a `cask` line such as [here](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/requirements/osxfuse_requirement.rb#L6). It won't do the automatic cask installation for you but it will tell people to install it prior to installing your formula.

We don't support automatic cask installation at the present time. For that to happen the two projects will probably need to come closer together, and we'd have to work out a way to handle a fair number of casks requiring `sudo` to install successfully given we doesn't support `sudo`.

It's something we're hoping to improve over time but for an immediate solution the custom requirement is pretty much it I'm afraid. Hope this helps somewhat.

**Comment by pmoody-** [comment]
this does help, thanks!

if you do get around to implementing depending on a cask from a formula, and you remember, can you ping this issue?

Cheers,
peter
