### ISSUE TITLE
Fix librsync OSX segfaults - upgrade librsync to master or 2.0.1

### ISSUE THREAD

**Issue by Thinkscape** [Homebrew/homebrew#49770]
## There is a known bug in librsync which causes crashes on OSX 
https://github.com/librsync/librsync/issues/50

## Affected
This potentially affects all formulas librsync after user upgrades to `2.0.0`.
One example is **Duplicity** which crashes constantly:  https://answers.launchpad.net/duplicity/+question/284756

## A fix 
A fix [has been merged into master](https://github.com/librsync/librsync/issues/50#issuecomment-183803254). We can either wait for 2.0.1 or use [master](https://github.com/librsync/librsync) and compile ourselves.

**Comment by dunn** [comment]
If the fix can be backported, we could also revision 2.0.0.
