### ISSUE TITLE
Homebrew Git failure on push

### ISSUE THREAD

**Issue by CodingAnarchy** [Homebrew/homebrew#49789]
### Bug reports:

Homebrewed version of git (2.7.2) fails on my system (OS X El Capitan) when I try a `git push` with the following error:

```
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Falling back to the Apple-provided version works as expected with the output `Everything up-to-date.`

**Comment by DomT4** [comment]
Why is a system utility:
> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO

Linked to `libJPEG.dylib` in `/usr/local/lib`? rather than the Apple JPEG in:
> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib

Which is the link on my OS X El Cap installation. Is the one in `/usr/local/lib` actually a symlink or was `ImageIO` changed at some point to reference the alternative `JPEG`?

Can you `ls -l /usr/local/lib/libJPEG.dylib` and see what the output is? I'm not completely convinced that's a Homebrew-installed dylib.

**Comment by CodingAnarchy** [comment]
The output of `ls -l /usr/local/lib/libJPEG.dylib` is:

```
lrwxr-xr-x 1 vision admin 35 Aug 13  2015 /usr/local/lib/libJPEG.dylib -> ../Cellar/jpeg/8d/lib/libjpeg.dylib
```

I have no idea why the system library is linking to that.  The output of `otool -L /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO` includes the Apple JPEG:

```
System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO:
	/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 600.0.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 48.0.0)
	/System/Library/PrivateFrameworks/AppleVPA.framework/Versions/A/AppleVPA (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1256.1.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1256.12.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 728.5.0)
	/System/Library/PrivateFrameworks/AppleJPEG.framework/Versions/A/AppleJPEG (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

**Comment by dunn** [comment]
I'd start by reinstalling `jpeg`; that might resolve the linking oddness.

**Comment by CodingAnarchy** [comment]
Ok, so it looks like I resolved the issue by clearing out my `DYLD_LIBRARY_PATH` environment variable (which had reference to `/usr/local/lib`).  Presumably, that was what was causing the linker to use the homebrew-installed jpeg library.  As far as it goes, however, this is unexpected behavior and prevents me from being able to use homebrew-installed libraries (in this particular case, some of the `boost` libraries) while using tools that link to this library.  Is there a way around this, beyond not installing `jpeg`?

**Comment by mikemcquaid** [comment]
Setting `DYLD_LIBRARY_PATH` will break lots of things in Homebrew (that's why we tell you to unset it in `brew doctor`) so: no, sorry.
