### ISSUE TITLE
brew tests fails with Ruby 1.9.3 on Linuxbrew: can't modify frozen String

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew#49792]
Ruby 1.9.3 is the default Ruby installed on Ubuntu 14, so I'd like to fix this issue if possible. Feel free to close as `wontfix` if you like. If you have any insight on what this error means, I'd appreciate the help. Ruby 2.0.0 works. See also https://github.com/Linuxbrew/linuxbrew/issues/798#issuecomment-182597326

```
$ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
$ brew tests
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
There was a RuntimeError while loading simplecov.gemspec: 
can't modify frozen String from
/home/linuxbrew/.linuxbrew/Library/Homebrew/test/vendor/bundle/ruby/1.9.1/bundler/gems/simplecov-4c7642496e90/simplecov.gemspec:6:in
`block in <main>'
bundler: command not found: rake
Install missing gem executables with `bundle install`
```

Ignore the misnomer `1.9.1` in the message. It's a misnomer. Apparently Ubuntu calls their package of Ruby 1.9.3 `ruby1.9.1`

**Comment by sjackman** [comment]
We were discussing discontinuing support for Ruby 1.9 with Homebrew. What's the status of Ruby support?

**Comment by mikemcquaid** [comment]
Homebrew has never supported Ruby 1.9 so it's probably not worth the effort.
