### ISSUE TITLE
ghi has a missing dependency

### ISSUE THREAD

**Issue by sorin-ionescu** [Homebrew/homebrew#49790]
`ghi` now [depends](https://github.com/stephencelis/ghi/blob/master/ghi.gemspec#L22) on [pygments.rb](https://github.com/tmm1/pygments.rb), which is not installed by `brew` since it is not in the archive. There should be a notice in the formula that this dependency must be installed manually, or the formula should be removed in favor of `gem install ghi`.

**Comment by DomT4** [comment]
Will welcome a PR to add a caveat telling people to install the `pygments` gem.
