### ISSUE TITLE
How to install formulae which need python3 using the python3 already installed in my mac

### ISSUE THREAD

**Issue by ccqpein** [Homebrew/homebrew#49809]
I wanna to install the mpv, which has lower version in brew-cask, and I found the mpv need to install python3 first. I already install python 3.5 within pyenv.

Can I install the formulae with the python that not installed by brew?

Thank you

**Comment by DomT4** [comment]
If you install it from source it should use the Python3 you have installed locally rather than pulling in our own:
```
brew install mpv -s
```
