### ISSUE TITLE
gnome-builder 3.18.1: vala and ggit related build failure

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew#49824]
@tschoonj @apjanke 

The recently added `gnome-builder` no longer builds.

```
-lxml2 -lgjs -lgirepository-1.0 -lmozjs-24 ../contrib/egg/.libs/libegg-private.dylib -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lgmodule-2.0 -lglib-2.0 -lintl
/usr/local/Cellar/gobject-introspection/1.46.0_1/bin/g-ir-compiler --includedir=. --includedir=. Ide-1.0.gir -o Ide-1.0.typelib
/usr/local/Cellar/vala/0.30.1/bin/vapigen-0.30  --library libide-1.0 --metadatadir .   --pkg gio-2.0 --pkg gtk+-3.0 --pkg gtksourceview-3.0 --pkg ggit-1.0 --pkg libpeas-1.0 Ide-1.0.gir
error: Package `ggit-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
Generation failed: 1 error(s), 0 warning(s)
make[2]: *** [libide-1.0.vapi] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1
```
https://gist.github.com/49d0a151162204fc176a

**Comment by tschoonj** [comment]
Can you run:

````
brew reinstall libgit2-glib --with-vala 
````

and then try building `gnome-builder` again?

**Comment by ilovezfs** [comment]
@tschoonj 
Voilà (sorry bad pun):
```
🍺  /usr/local/Cellar/gnome-builder/3.18.1: 246 files, 9.7M, built in 1 minute 20 seconds
bash-3.2$
```
So sounds like `--with-vala` needs to be made the default for `libgit2-glib` and also perhaps a formula-specific requirement like this added to gnome-builder:
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/compcert.rb#L1-L11

**Comment by tschoonj** [comment]
Well the thing is that I just built `gnome-builder` with `libgit2-glib` without vala support and it worked fine.

From your error it seems that the `gobject-introspection` files are generated can also be used, which are always produced for `libgit2-glib`.

I have a feeling there was something strange going on initially with your `libgit2-glib` installation, as it seems to have been generated without `gobject-introspection` files...

I don't think that the `gnome-builder` or `libgit2-glib` formulas need fixes, as a build problem would have also showed up while producing the bottles on the buildbot.

**Comment by ilovezfs** [comment]
Nope, this is a clean install of brew starting from nothing just to test this.

**Comment by ilovezfs** [comment]
@tschoonj Here's a gist showing it happening starting from nothing:
https://gist.github.com/ilovezfs/0c203fa310f98795e090

**Comment by tschoonj** [comment]
Aha, you passed `--build-bottle` to `brew install gnome-builder`!

Why did you do that? Did you mean `--force-bottle`?

**Comment by ilovezfs** [comment]
No, I meant build-bottle. It means to use all bottles, and then do a source build on the actual target.

**Comment by ilovezfs** [comment]
@tschoonj For your peace of mind ;)
https://gist.github.com/ilovezfs/e85e18580834c0dcc58f

**Comment by ilovezfs** [comment]
@tschoonj OK, this fixes the problem:
```
diff --git a/Library/Formula/gnome-builder.rb b/Library/Formula/gnome-builder.rb
index 67b0f22..dd58f46 100644
--- a/Library/Formula/gnome-builder.rb
+++ b/Library/Formula/gnome-builder.rb
@@ -31,6 +31,13 @@ class GnomeBuilder < Formula
 
   def install
     ENV.cxx11
+
+    # Fix build failure on case-sensitive volumes for libgit2-glib without vala
+    unless File.exist?(Formula["libgit2-glib"].share/"vala/vapi/ggit-1.0.vapi")
+      inreplace Dir["libide/{Makefile.am,Makefile.in,libide-1.0.deps}"],
+        "ggit-1.0", "Ggit-1.0"
+    end
+
     system "./configure", "--disable-debug",
                           "--disable-dependency-tracking",
                           "--disable-silent-rules",

```

**Comment by ilovezfs** [comment]
@tschoonj FYI: https://github.com/Homebrew/homebrew/pull/49840
