### ISSUE TITLE
Squid: add default options

### ISSUE THREAD

**Issue by deus0ww** [Homebrew/homebrew#49838]
Could these options be added to the squid formula, please?
      --enable-delay-pools
      --enable-disk-io=yes
      --enable-removal-policies=yes
      --enable-storeio=yes

This enables the delay-pools (bandwidth control), and all modules for disk-io, removal-policies (lru,heap) and storeio (aufs,diskd,ufs,rock).

**Comment by mikemcquaid** [comment]
We don't really do feature requests. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by deus0ww** [comment]
Pull request created here: https://github.com/Homebrew/homebrew/pull/49842
Please note that this is my first time using GIT and this is my first pull request...
