### ISSUE TITLE
No OSD in mplayer

### ISSUE THREAD

**Issue by mutanabbi** [Homebrew/homebrew#49861]
Mplayer OSD disappeared after update on mplayer-1.3.0. It looks like the bottle was built with no --enable-freetype option:

    $ mplayer -v -frames 0 test.m4v 2>/dev/null | grep '^Configuration'
    Configuration: --cc=clang --host-cc=clang --disable-cdparanoia --prefix=/usr/local/Cellar/mplayer/1.3.0 --disable-x11

    $ sw_vers
    ProductName:	Mac OS X
    ProductVersion:	10.10.5
    BuildVersion:	14F1605

**Comment by mikemcquaid** [comment]
This is intentional. The OSD requires X11. Sorry!

**Comment by mutanabbi** [comment]
So, no subtitles now?

**Comment by mikemcquaid** [comment]
Speak to the MPlayer developers, I have no idea.

**Comment by pjta** [comment]
As a workaround you can install an older version which supports OSD:
> brew remove mplayer
brew install https://raw.githubusercontent.com/Homebrew/legacy-homebrew/0f3ba89b0d2609b0464a60f60e320b5f3f2a714c/Library/Formula/mplayer.rb
brew pin mplayer

The last command prevents mplayer from upgrading. To let it upgrading again do:
> brew unpin mplayer

**Comment by PacoH** [comment]
I had the same problem and am pissed about such a decision. OS X has built-in X11 support so this is illogical and undesirable. BUT, people, I did some searching and found a very simple solution!

After you install the latest version of `mplayer`, you have to edit the file `/usr/local/Library/Formula/mplayer.rb`. Search for `--disable-x11` and delete that line. I moved it outside the brackets and commented it out with a note to myself:

Original:

    args = %W[
      --cc=#{ENV.cc}
      --host-cc=#{ENV.cc}
      --disable-cdparanoia
      --prefix=#{prefix}
      --disable-x11
    ]

Modified:

    args = %W[
      --cc=#{ENV.cc}
      --host-cc=#{ENV.cc}
      --disable-cdparanoia
      --prefix=#{prefix}
    ]
    #--disable-x11 removed because it disabled osd and subs

Then do another search for `depends_on` and find:

    depends_on "yasm" => :build
    depends_on "libcaca" => :optional

Add the line `depends_on :x11 => :build`:

    depends_on "yasm" => :build
    depends_on "libcaca" => :optional
    depends_on :x11 => :build

Save.

Then reinstall mplayer:

`brew reinstall --with-x11 mplayer`

I'm not sure the `--with-x11` is really necessary but it sure didn't hurt.

That's it. Now I have glorious OSD and subtitle support! Woot!
