### ISSUE TITLE
Transmission 2.9.0 contains malware/ransomware - 2.9.2 now available

### ISSUE THREAD

**Issue by ntwb** [Homebrew/homebrew#49862]
The current v2.9.0 of Transmission contains "ransomeware":

• https://github.com/Homebrew/homebrew/blob/master/Library/Formula/transmission.rb
• http://researchcenter.paloaltonetworks.com/2016/03/new-os-x-ransomware-keranger-infected-transmission-bittorrent-client-installer/
> _"On March 4, we detected that the Transmission BitTorrent client installer for OS X was infected with ransomware, just a few hours after installers were initially posted. We have named this Ransomware “KeRanger.”_

• https://www.transmissionbt.com/
> _"Everyone running 2.90 on OS X should immediately upgrade to and run 2.92, as they may have downloaded a malware-infected file. This new version will make sure that the “OSX.KeRanger.A” ransomware (more information available here) is correctly removed from your computer._
> 
> _Users of 2.91 should also immediately upgrade to and run 2.92. Even though 2.91 was never infected, it did not automatically remove the malware-infected file._"

**Comment by dunn** [comment]
2.92 was added yesterday: #49831

**Comment by bfontaine** [comment]
Please note that the *installer* was infected; since we’re building from source the Homebrew package was very likely not infected.

**Comment by dunn** [comment]
True; and the Cask installer has already been updated as well.

**Comment by ntwb** [comment]
Thanks :+1:
