### ISSUE TITLE
brew update error

### ISSUE THREAD

**Issue by lxn348567248** [Homebrew/homebrew#49879]
### Bug reports:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'
```

**Comment by mikemcquaid** [comment]
Please try to rerun `brew update` twice and see if that resolves the issue.

**Comment by lxn348567248** [comment]
when i executed brew update,got the same error.
thanks

**Comment by dunn** [comment]
If you haven't made any modifications to your Homebrew installation, you can reset it with:
```
cd $(brew --prefix) && git fetch origin && git reset --hard origin/master

**Comment by sambeau** [comment]
I'm getting this error too. I have no idea why. Does anyone know what might have triggered it? I've tried `brew update` (same error) and I've tried resetting which gives different errors:

```
warning: unable to unlink CONTRIBUTING.md: Permission denied
warning: unable to unlink SUPPORTERS.md: Permission denied
fatal: cannot create directory at '.github': Permission denied
```

**Comment by DomT4** [comment]
```bash
sudo chown -R $(whoami):admin /usr/local
```
And then try again.

**Comment by sambeau** [comment]
Thanks, everyone. For future reference, the fix for me was:

```
sudo chown -R $(whoami):admin /usr/local
cd $(brew --prefix) && git fetch origin && git reset --hard origin/master
```

then I could

```
brew update
```

and carry on as normal.

Does anyone have an idea what caused the change in permissions? Is it likely something stupid that I did?

**Comment by lxn348567248** [comment]
thanks everyone .
I have found the problem.because of china I can't pull update from git.
when I use poxy,I fix it.

**Comment by mikemcquaid** [comment]
Thanks for letting us know @lxn348567248.

**Comment by DomT4** [comment]
> Does anyone have an idea what caused the change in permissions? Is it likely something stupid that I did?

Could be anything, really. Installed something from a `.pkg` file is a common one, some anti-virus software has been known to be a little root-happy, running commands that modify/create permissions/folders/files with `sudo`, etc. I wouldn't worry about it too much unless it proves repetitive.

**Comment by cehwitham** [comment]
This also worked for me. Many thanks.

**Comment by snadal** [comment]
+1. @sambeau fix worked for me too. Thank you !
