### ISSUE TITLE
Cant upgrade vim OSx Cocoa/Cocoa.h file not found

### ISSUE THREAD

**Issue by jmartiuk5** [Homebrew/homebrew#49888]
### Bug reports:
Ok I have an issue and a question. The issue is When I try to upgrade vim I get the Cocoa/Cocoa.h file not found error.
My question is when I run brew doctor I get Warning: Unbowed header files were found in /usr/local/include and there are a ton of them. I didn't put them there I'm just wondering do I need to delete them or just move them somewhere. Thanks in advance

https://gist.github.com/jmartiuk5/1f2d20c00a8610189372

**Comment by DomT4** [comment]
It looks like you installed Node from the upstream `.pkg` installer at some point; those header files are consistent with that. They shouldn't be interfering here.

What options are you installing `vim` with? `brew info vim` should tell you.

**Comment by jmartiuk5** [comment]
These are the possible options I actually just trying to upgrade the vim i currently have. So is it ok to delete those files or are they ok to stay there the node files I mean. Thank you again for your help.

brew info vim
vim: stable 7.4.1468, HEAD
Vi "workalike" with many additional features
http://www.vim.org/
Conflicts with: ex-vi
/usr/local/Cellar/vim/7.4.712 (1,606 files, 21.8M)
  Built from source
/usr/local/Cellar/vim/7.4.1090 (1,621 files, 22.3M) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/vim.rb
==> Dependencies
Optional: lua ✘, luajit ✘
==> Options
--disable-nls
	Build vim without National Language Support (translated messages, keymaps)
--override-system-vi
	Override system vi
--with-client-server
	Enable client/server mode
--with-lua
	Build vim with lua support
--with-luajit
	Build with luajit support
--with-mzscheme
	Build vim with mzscheme support
--with-python3
	Build vim with python3 instead of python[2] support
--with-tcl
	Build vim with tcl support
--without-perl
	Build vim without perl support
--without-python
	Build vim without python support
--without-ruby
	Build vim without ruby support
--HEAD
	Install HEAD version

**Comment by jmartiuk5** [comment]
well I never did get my actual problem solved so i just uninstalled and reinstalled. I was just trying to figure out why it was having an issue upgrading vim, just in case someone runs into it in the future.

**Comment by DomT4** [comment]
Sorry, I loop back around on Issues/PRs and only have so much free time to give to Homebrew every day. Sometimes it will take a few days for me to go full circle. I'm glad you've managed to resolve your Issue at least.
