### ISSUE TITLE
brew tap osx-crossover/avr error

### ISSUE THREAD

**Issue by blj** [Homebrew/homebrew#49882]
### Bug reports:

Syntax error from brew tap osx-crossover/avr
`brew tap osx-cross/avr
==> Tapping osx-cross/avr
Cloning into '/usr/local/Library/Taps/osx-cross/homebrew-avr'...
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 10 (delta 1), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.
Checking connectivity... done.
Tapped 7 formulae (39 files, 34.9K)
Error: can't convert Array into String
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/utils.rb:514:in `popen'
/usr/local/Library/Homebrew/utils.rb:514:in `api_credentials'
/usr/local/Library/Homebrew/utils.rb:532:in `api_headers'
/usr/local/Library/Homebrew/utils.rb:551:in `open'
/usr/local/Library/Homebrew/utils.rb:639:in `private_repo?'
/usr/local/Library/Homebrew/tap.rb:150:in `private?'
/usr/local/Library/Homebrew/tap.rb:204:in `install'
/usr/local/Library/Homebrew/cmd/tap.rb:18:in `tap'
/usr/local/Library/brew.rb:83:in `send'
/usr/local/Library/brew.rb:83`

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by mikemcquaid** [comment]
Should be fixed now, thanks.
