### ISSUE TITLE
Optimized version of ssh-copy-id

### ISSUE THREAD

**Issue by denji** [Homebrew/homebrew#49929]
The [original version](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ssh-copy-id.rb) of `ssh-copy-id` from delivery openssh doesn't work from a running fish-shell infinite-loop.

Fork ssh-copy-id works more safely on all types of shell:
- https://github.com/beautifulcode/ssh-copy-id-for-OSX

Reproduction steps:

    $ fish
    $ ssh-copy-id user@ssh_ip

**Comment by mikemcquaid** [comment]
We don't want to use a fork here, thanks.
