### ISSUE TITLE
Go: race packages not installed correctly

### ISSUE THREAD

**Issue by prashantv** [Homebrew/homebrew#49943]
The installed go packages do not seem to contain the correct packages when using "-race". I just reinstalled go 1.6 using homebrew and confirmed the same issue exists on a coworkers machine.

Here's my Go environment:
```
> go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/prashant/gocode"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

I'm running go install with -n and -x to dry run but print the commands. I tell it to install the standard library:
```
> go install -n -x std

```
There's no output, which is what I expect since the `pkg` folder should be up to date. However, once `-race` is added;
```
> go install -n -x -race std

#
# runtime/internal/sys
#

mkdir -p $WORK/runtime/internal/sys/_obj/
mkdir -p $WORK/runtime/internal/
cd /usr/local/Cellar/go/1.6/libexec/src/runtime/internal/sys
/usr/local/Cellar/go/1.6/libexec/pkg/tool/darwin_amd64/compile -o $WORK/runtime/internal/sys.a -trimpath $WORK -race -p runtime/internal/sys -+ -complete -installsuffix race -buildid 87a9d98aaa6e239bae3a1bf9eb792c2981c82352 -D _/usr/local/Cellar/go/1.6/libexec/src/runtime/internal/sys -I $WORK -pack ./arch_amd64.go ./stubs.go ./sys.go ./zgoarch_amd64.go ./zgoos_darwin.go ./zversion.go
mkdir -p /usr/local/Cellar/go/1.6/libexec/pkg/darwin_amd64_race/runtime/internal/
mv $WORK/runtime/internal/sys.a /usr/local/Cellar/go/1.6/libexec/pkg/darwin_amd64_race/runtime/internal/sys.a
[...]
```

It seems like the `-race` packages are not installed correctly.

I tried the official Go download to compare, here's the output using that:
```
> /usr/local/go/bin/go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/prashant/gocode"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

> /usr/local/go/bin/go install -n -x std

> /usr/local/go/bin/go install -n -x -race std
```

**Comment by DomT4** [comment]
The most obvious problem is that unlike the official Go upstream package our OS X installation provides no installed `pkg/darwin_amd64_race` folder, which may well be the issue.

**Comment by DomT4** [comment]
Ah. Seems they aren't installed by default from the source packages; you have to call `go install -race std` to get them. The upstream packages are generated to include them as of [this commit](https://github.com/golang/go/commit/57af97f2f4056cbaa4bad6d3109b71cacbc395b3).

**Comment by prashantv** [comment]
I think it's also possible to generate them by invoking [race.bash](https://golang.org/src/race.bash) after the make/all.

**Comment by DomT4** [comment]
Have opened https://github.com/Homebrew/homebrew/pull/49998 for discussion.

**Comment by DomT4** [comment]
> I think it's also possible to generate them by invoking race.bash a

It looks like it could be done this way, but that command also executes what could be called an extensive, lengthy test suite... to say the least, which I'm not convinced is particularly necessary on our side, so plucking the shorter command out seems reasonable IMO.

**Comment by DomT4** [comment]
You'll need to `brew reinstall go` if you want the race element from us rather than running the local command. I've added it to the bottle but it wasn't worth forcing a general reinstall for everyone, but the option is there for those who do want it.

**Comment by prashantv** [comment]
Thanks @DomT4 for the quick fix. I agree it's not worth forcing a general reinstall.
