### ISSUE TITLE
Create homebrew room for this repo on gitter.im

### ISSUE THREAD

**Issue by a-b** [Homebrew/homebrew#49994]
Create a chat room for homebrew community on https://gitter.im for this repo

**Comment by tdsmith** [comment]
I'd feel bad creating a space that we don't intend to moderate; we have an active room on Freenode (#machomebrew) which has one or two maintainers in attendance but I'm not excited to add a new platform to my own personal watchlist. If another maintainer wants to keep an eye on gitter I'm not opposed.

**Comment by dunn** [comment]
Yeah, I think since we've got IRC we should focus on that space.

**Comment by mikemcquaid** [comment]
Agreed.
