### ISSUE TITLE
VIM Upgrade

### ISSUE THREAD

**Issue by sherabi** [Homebrew/homebrew#50020]
Followed all the general troubleshooting steps

### Bug reports:

brew upgrade
==> Upgrading 1 outdated package, with result:
vim 7.4.1525
==> Upgrading vim
==> Downloading https://github.com/vim/vim/archive/v7.4.1525.tar.gz
Already downloaded: /Library/Caches/Homebrew/vim-7.4.1525.tar.gz
Error: no implicit conversion of String into Integer
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/extend/fileutils.rb:30:in `getgrgid'
/usr/local/Library/Homebrew/extend/fileutils.rb:30:in `rescue in mktemp'
/usr/local/Library/Homebrew/extend/fileutils.rb:27:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:1540:in `stage'
/usr/local/Library/Homebrew/formula.rb:926:in `brew'
/usr/local/Library/Homebrew/build.rb:108:in `install'
/usr/local/Library/Homebrew/build.rb:177:in `<main>'

**Comment by DomT4** [comment]
Please supply a full `brew gist-logs vim`,

**Comment by sherabi** [comment]
brew gist-logs vim
Error: No logs.

**Comment by DomT4** [comment]
That's helpful of it, heh. Can you provide a manual `brew config` and `brew doctor` then? Thanks.

**Comment by sherabi** [comment]
Brew doctor
brew doctor
Your system is ready to brew.

Brew Config

brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 15802d48c082392fb07e0a04c6584c6f58e0215e
Last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.11.3-x86_64
Xcode: 7.2.1
CLT: N/A
Clang: 7.0 build 700
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_74, 1.8.0_72, 1.8.0_65, 1.8.0_60, 1.8.0_51

**Comment by sherabi** [comment]
Update: Somehow this has fixed itself. After upgrading to Xcode: 7.2.1
