### ISSUE TITLE
llvm --HEAD don't builds

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew#50032]
https://gist.github.com/a3d0116243e00fb8e0f9

**Comment by tdsmith** [comment]
```
clang: error: no such file or directory: 'CMakeFiles/RTTsan_dynamic.osx.dir/rtl/tsan_clock.cc.o'
make[2]: *** [projects/compiler-rt/lib/tsan/CMakeFiles/RTTsan_dynamic.osx.dir/rtl/tsan_clock.cc.o] Error 1
```

Odd error! We can't generally help with --HEAD builds since they're moving targets; you might consider referring this to the LLVM tracker. We'll accept a pull request to fix the build if we need to pass a new switch or add a new dependency. Please let us know if we can help with anything else.
