### ISSUE TITLE
"Java is required to install this formula" but Java is installed

### ISSUE THREAD

**Issue by eggsyntax** [Homebrew/homebrew#50035]
I hit "Java is required to install this formula" today while installing maven. OS X 10.10.5, Homebrew 0.9.5 (rev 245a8). I have Java 1.8 installed and $JAVA_HOME is set. Doing `brew edit maven` and deleting `depends_on :java` caused the install to proceed successfully.

Weirdly, it happened on one machine but not the other, although I use the same dotfiles for both and attempt to keep Java setup identical on both, same versions of everything relevant-seeming.

Again, this is solved for me using the workaround, but I was asked to file a bug report on it.

**Comment by dunn** [comment]
What's the `brew config` on each machine?  Does `brew doctor` flag anything on either?

**Comment by eggsyntax** [comment]
On the machine where it wouldn't install:

```HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 638d755e5ba753f49e991ca3240768f8ced1f911
Last commit: 2 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
Clang: 7.0 build 700
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A```

^ that last certainly looks alarming O_O

On the machine where it _would_ install:

```HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 1c1f1e42751e3dac6bb9832fd6824757dfbae2b5
Last commit: 25 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
OS X: 10.10.5-x86_64
Xcode: N/A
CLT: 7.2.0.0.1.1447826929
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_60, 1.6.0_65-b14-468```

brew doctor, on the machine where it _wouldn't_ install:

```Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your XQuartz (2.7.7) is outdated
Please install XQuartz 2.7.8:
  https://xquartz.macosforge.org```

brew doctor, on the machine where it _would_ install, actually finds a lot more:

```Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have external commands with conflicting names.

Found command `brew-cask` in following places:
    /usr/local/bin/brew-cask
    /usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/lauxlib.h
    /usr/local/include/lua.h
    /usr/local/include/luaconf.h
    /usr/local/include/lualib.h

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/liblua.a

Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours. This is a long time in brewland!
To update Homebrew, run `brew update`.

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
    readline```

**Comment by dunn** [comment]
We use `/usr/libexec/java_home`; you can see the exact process here: https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/config.rb#L132-L140

Does `/usr/libexec/java_home` produce any output on the first machine?

**Comment by eggsyntax** [comment]
<pre>[17:34]~> /usr/libexec/java_home
Unable to find any JVMs matching version "(null)".
No Java runtime present, try --request to install.</pre>

For the sake of completeness:

<pre>[18:06]~> java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)`

[18:06]~> echo $JAVA_HOME
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
</pre>

I realize it's not typical to point $JAVA_HOME at the browser plugin, but it's recommended in some places (eg [here](http://stackoverflow.com/a/19582689)), and it's worked well for me thus far. Also, that's the same setup as on the other machine, where the maven install worked.

I see, however, that on the other machine:

<pre>13249[17:31]harmony> /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home</pre>

This is certainly suggesting to me that the problem isn't Homebrew's, but I'd love to hear your opinion (and any insight into why I might be getting the weird result on the first machine from /usr/libexec/java_home).

**Comment by dunn** [comment]
I don't know enough about Java, but @apjanke might have some insight here.

**Comment by eggsyntax** [comment]
Cool, thanks for the help @dunn!

**Comment by rakkesh** [comment]
@eggsyntax it seems to me that on the first machine you have installed JRE and not JDK, which is required when `depends_on :java` is used.

**Comment by apjanke** [comment]
Yeah, the browser plugin just has a JRE. `$JAVA_HOME` is supposed to point to a JDK, and that's what Homebrew expects too. Download and install a JDK on that machine.

**Comment by eggsyntax** [comment]
<FACEPALM>

Thanks, y'all. I've got a JDK on that machine -- I do a lot of Clojure development -- and somehow I've never had any problem with $JAVA_HOME pointing there. I'll go correct that.

**Comment by eggsyntax** [comment]
And just to confirm, yeah, after that I can do a standard `brew install maven` and everything works fine. Thanks for the help, folks! Closing.

**Comment by DomT4** [comment]
> $JAVA_HOME is supposed to point to a JDK, and that's what Homebrew expects too.

@apjanke Is this something we should check for in `brew doctor`?
