### ISSUE TITLE
brew cleanup should remove the cached files

### ISSUE THREAD

**Issue by rdp** [Homebrew/homebrew#50033]
I noticed that homebrew's cache can use up quite a bit of disk space, I presume with files no longer needed for install:

$ du -h /Library/Caches/Homebrew
...
365M	/Library/Caches/Homebrew

most files are like pcre-8.38.yosemite.bottle.tar.gz or java-1.8.0_74-b02.dmg

I would anticipate that $ brew cleanup would remove these files.  Or at least have an option to do so.  So consider this a feature request for the same.  Or if it is an "acceptable idea" let me know and I can come up with a pull request for it.
Cheers!

-roger-

**Comment by mikemcquaid** [comment]
It does remove those files. If it hasn't that's because they are needed for stuff you currently have installed. You can see the logic here: https://github.com/Homebrew/homebrew/blob/3dc4841f979401c09490bd07a46019ba0c6ebd95/Library/Homebrew/cleanup.rb#L46-L95

**Comment by rdp** [comment]
I see quite a few ".yosemite.bottle" files in the  /Library/Caches/Homebrew folder: https://gist.github.com/rdp/d64159f38f1c556370f1

Removing one (ex: yasm-1.3.0.yosemite.bottle.1.tar.gz) and homebrew is still able to uninstall yasm.  Any ideas why homebrew would consider these "non removable files" in this instance?  Is it just a tweak that needs to happen in all these formulae to denote that these are expendable files do you think? Thanks!

**Comment by mikemcquaid** [comment]
@rdp If you'd like `cleanup` to remove more of these things: please submit a specific issue with a description of what you feel is not being cleaned that should be or, ideally, a pull request to implement it. Thanks!
