### ISSUE TITLE
Failure to Upgrade Scala due to Curl errors

### ISSUE THREAD

**Issue by eldritchideen** [Homebrew/homebrew#50053]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:
```
$ brew upgrade scala
==> Upgrading 1 outdated package, with result:
scala 2.11.8
==> Upgrading scala
==> Downloading https://downloads.lightbend.com/scala/2.11.8/scala-2.11.8.tgz

curl: (35) SSL peer handshake failed, the server most likely requires a client certificate to connect
Error: Failed to download resource "scala"
Download failed: https://downloads.lightbend.com/scala/2.11.8/scala-2.11.8.tgz
```

**Comment by DomT4** [comment]
Can you provide a `brew config` and `brew doctor`? Thanks.

**Comment by eldritchideen** [comment]
Figured out the issue. 

Looking more closely at the output of `brew doctor`, I noticed that it warned about having a `.curlrc` file.

The contents of the `.curlrc` file was:
```
$ cat .curlrc 
insecure
```
Not sure what created this .curlrc file, as I don't recall ever creating one, however when I renamed it to `.curlrc.bak` and tried again, the `brew upgrade scala` command worked fine.
