### ISSUE TITLE
brew.sh webpage is not available.

### ISSUE THREAD

**Issue by mttrs** [Homebrew/homebrew#50057]
The host isn't resolved from my computer. Something wrong with the host?

```
% ping brew.sh
ping: cannot resolve brew.sh: Unknown host
```

**Comment by tdsmith** [comment]
dnsimple is having some trouble: http://dnsimplestatus.com/

Thanks for reporting!

**Comment by mttrs** [comment]
oh, only Japan issue... Thanks for checking!

Cheers,
Mitsu
