### ISSUE TITLE
brew update fails on 10.6 initial installation; git failed to build on 10.6

### ISSUE THREAD

**Issue by amyzing** [Homebrew/homebrew#50072]
New install of OS X 10.6 on MBP 17" (why, yes, I am an oldz, why d'you ask?) (new SSD post disk crash). Updated to 10.6.8 via SoftwareUpdate (repeated until it says "I got nothin'"). XCode 3.2.6 installed and apparently working (don't have access to 4.2). brew update triggers brew install git 2.7.3, which dies in combine-diff.c with a segfault. Completely repeatable (at least on my hardware, MBP 17" (5,2) and a mini server).

Gist output here:

https://gist.github.com/anonymous/96f6c11bb2020fc4def8

Note that this is 10.6, so unsupported. Also, other formulae work (curl, wget (always my first installs)). As this is the required-by-brew-doctor-and-brew-update installation of git, however, I'm not terribly hopeful.

Same result on a mac mini server (os x 10.6 server) earlier this week (took a while to recover data from the dead disk, so I updated that machine for temporary use), but I didn't report it (on the theory that I might have installed something weird in the year or so since the OS was installed).

- [ ] Ran `brew update` and retried your prior step?

This is what failed. :-) It fails in the attempt to build git:

combine-diff.c: In function ‘diff_tree_combined’:
combine-diff.c:1391: internal compiler error: Segmentation fault

- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

Well, it doesn't like anything earlier than 10.7, and I hate everything 10.7 and later, so ... given that I'm targeting 10.6, yeah, as many as possible without update-degrading the OS.

- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

seg fault in the compiler; prolly not permissions. right?

More information can be provided (running brew update produces this result with high confidence).

**Comment by mikemcquaid** [comment]
We can try to fix this `git` error but just an FYI that Homebrew will be officially dropping 10.6 support in the near future and refuse to run on that OS as, as this issue demonstrates, we can't support it well or fix issues there with no maintainers or CI running it.

**Comment by amyzing** [comment]
Thanks! No more could be asked. Let me know if there's anything further that I can do (information, tests, whatever).

**Comment by petrahu** [comment]
I have this problem too.
I can't upgrade to a newer OS, because Apple doesn't support upgrading a Xserve.

**Comment by mikemcquaid** [comment]
I'm guessing Git probably doesn't support 10.6 any more. You may be best downloading an installer from somewhere. Sorry!

**Comment by mikemolina** [comment]
Hi!

Maybe exist a possibility. I achieved compile on Mac Snow Leopard from source code using:

$ ./configure --prefix=/usr/local --with-libpcre --with-editor=emacs CFLAGS="-arch i386 -arch x86_64 -arch ppc -mmacosx-version-min=10.6" LDFLAGS="-arch i386 -arch x86_64 -arch ppc"
$ make
$ ./git --version
git version 2.7.4

The features of the machine:

- uname -mprs

  Darwin 10.8.0 i386 i386
- Xcode 3.2
- gcc --version

  i686-apple-darwin10-gcc-4.2.1 (GCC) 4.2.1 (Apple Inc. build 5646)

Tests with "make test" were successful!!.

**Comment by amyzing** [comment]
This actually works, although I had to make some changes.

After downloading and unzipping the source zip (master.zip) from 
github, cd git-master and

$ make configure 

first. Actually, reading the instructions below from Mike Molina in 
combination with git's INSTALL instructions and then tweaking worked. 
More or less.

Simplified configure, without pcre (using --with-libpcre, bisect.o 
failed in lipo for me, even after simplifying the indicated 
architecture).

$ ./configure --prefix=/usr/local --with-editor=emacs CFLAGS="-arch 
x86_64 -mmacosx-version-min=10.6" LDFLAGS="-arch x86_64"

As you can see, this also removes the other architectures (in part 
because I don't have the optional rosetta bits, but also because it 
goes faster and doesn't confuse lipo).

At that point:

$ make all doc

succeeds as far as building binaries. The docs don't build.

$ brew install asciidoc
$ brew install xmlto
$ export XML_CATALOG_FILES=/usr/local/etc/xml/catalog

(or add the export to .bash_profile)

You needn't bother with the docs if you don't want them locally (I do, 
though, so ...).

Back to INSTALL:

$ sudo make install install-doc install-html

(that's instead of su to root; it does need to be installed as root; if 
you haven't built docs, don't use the install-doc install-html targets)

And ... success:

$ git --version
git version 2.8.0-rc4

And ...

$ brew update
[ some stuff clipped ]
Already up-to-date.

$ brew doctor
[ snip explanation that warnings are warnings ]
Warning: You are using OS X 10.6.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.

:-)

Thanks to Mike Molina, and to everyone else. It *is* possible to get 
homebrew running with an external installation of git (appropriately 
reconfigured) on OS X 10.6. I appreciate everyone's time and updates 
here; it makes me very happy to be able to install homebrew stuff on a 
version that I'm happy using.

I hope that this update helps any others coming along later and 
experiencing issues as well, as the homebrew developers have been clear 
(and polite about it!) that they are no longer supporting 10.6.

Amy!
On Sat, 19 Mar 2016 09:27:08 -0700, Mike Molina wrote:
> Maybe exist a possibility. I achieved compile on Mac Snow Leopard 
> from source code using:
> 
> $ ./configure --prefix=/usr/local --with-libpcre --with-editor=emacs 
> CFLAGS="-arch i386 -arch x86_64 -arch ppc -mmacosx-version-min=10.6" 
> LDFLAGS="-arch i386 -arch x86_64 -arch ppc"
> $ make

[snip]
