### ISSUE TITLE
ld: can't open -sectcreate file

### ISSUE THREAD

**Issue by HamiltonWang** [Homebrew/homebrew#50086]
......
[ 99%] Building CXX object hphp/hhvm/CMakeFiles/hhvm.dir/process-init.cpp.o
[100%] Linking CXX executable hhvm
ld: can't open -sectcreate file: /tmp/hhvm20160314-14554-qsps0j/hphp/util/generated-compiler-id.txt
clang-3.6: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [hphp/hhvm/hhvm] Error 1
make[1]: *** [hphp/hhvm/CMakeFiles/hhvm.dir/all] Error 2
make: *** [all] Error 2

### Bug reports:

Error using home brew to install hhvm for Mac Yosemite.
ld: can't open -sectcreate file: /tmp/hhvm20160314-14554-qsps0j/hphp/util/generated-compiler-id.txt
clang-3.6: error: linker command failed with exit code 1 (use -v to see invocation)

https://gist.github.com/8adae56ae4769c9cd5f4

**Comment by DomT4** [comment]
I'm afraid there's nothing we can do to support formulae in external taps outside our control. You'll need to report this to them for support: https://github.com/hhvm/homebrew-hhvm

**Comment by HamiltonWang** [comment]
Thanks
