### ISSUE TITLE
Problem with downloading binary packages

### ISSUE THREAD

**Issue by fact0real** [Homebrew/homebrew#50085]
When I run `brew upgrade --all`, I can't download binary packages from [here](https://homebrew.bintray.com), because all servers are locate in Israel and some countries could not reach those, please migrate servers to another servers like AWS.
thanks
_factoreal

**Comment by tdsmith** [comment]
Please raise this issue with Bintray support to see if they can reconfigure their CDN to support your geopolitical constraints.
