### ISSUE TITLE
Does anyone have a better way to deal with stale postmaster.pid files?

### ISSUE THREAD

**Issue by CamJN** [Homebrew/homebrew#50088]
So after nearly every reboot I have to delete `/usr/local/var/postgres/postmaster.pid` because postgres won't start with that file present and a process using the pid listed in it.

Here's a list of things that I've learned trying to find a solution to this annoying situation:

- postgres expects to be run as the `_postgres` user or similar, (basically just a uid of it's own so that user only has postgres processes and pids don't get reused).
- `sudo -u _postgres whoami` outputs `_postgres` but requires password input.
- `man launchd.plist` says there is a `UserName <string>` key/value pair and `Note that for agents, the UserName key is ignored.` 
- postgres expects to be shutdown cleanly, and doesn't clean up it's pid file otherwise.
- http://www.postgresql.org/docs/9.5/static/app-postgres.html: To terminate the postgres server normally, the signals `SIGTERM`, `SIGINT`, or `SIGQUIT` can be used. The first will wait for all clients to terminate before quitting, the second will forcefully disconnect all clients, and the third will quit immediately without proper shutdown, resulting in a recovery run during restart.
- launchd plists don't have the ability to specify a command to cleanly shutdown a process.
- launchd sends `SIGTERM` followed by `SIGKILL` shortly thereafter on shutdown.
- launchd.plist: `ExitTimeOut <integer>
     The amount of time launchd waits between sending the SIGTERM signal and before sending a SIGKILL signal when the job is to be stopped. The default value is system-defined. The
     value zero is interpreted as infinity and should not be used, as it can stall system shutdown forever.`
- postgres in homebrew writes it's pid file to `/usr/local/var/postgres/postmaster.pid`, which survives reboots.
- launchd doesn't have the ability to track or cleanup a pid file.
- `/tmp` is deleted daily not (just)? on reboot: see `/etc/defaults/periodic.conf`
- booting osx results in non deterministic pids being assigned, and thus the pid in the pidfile will likely be in use before postgres tries to start.

If anyone else has ideas on how to overcome this pain point I'd love to hear them.

**Comment by mikemcquaid** [comment]
It seems the issue here is that your `postgres` is not being shut down cleanly. Bumping the `ExitTimeOut` would seem to fix your case. This doesn't seem to be a Homebrew issue but rather a Postgres one, though.

**Comment by CamJN** [comment]
I brought it up here because homebrew encourages using launchd to start postgres, and launchd doesn't handle postgres very well. That said would adding a longer timeout to the launchd plist in the postgres formula be an acceptable pull request?

**Comment by mikemcquaid** [comment]
If it fixes the issue: yep!

**Comment by CamJN** [comment]
Ok, I'll experiment with that and then put in a PR if it works.

**Comment by CamJN** [comment]
I realized that extending the `ExitTimeOut` won't help when the user logs out but doesn't reboot because any sessions open because of webapps running under apache won't be stopped (apache being a launchdaemon, it doesn't stop when you log out), postgres will wait for them and then be SIGKILLed anyway.

So, a couple different approaches: 

- recommending loading postgres as a launchdaemon like dnsmasq, the folks at postgres highly discourage having a server per user anyway.
- wrapping postgres with a script that catches SIGTERM and sends SIGINT to postgres

what would be more likely to be accepted?

**Comment by mikemcquaid** [comment]
I think if you're running an Apache LaunchDaemon for webapps you probably want to have a custom PostgreSQL LaunchDaemon too and that this isn't a generally used use-case that needs modification in the formula.

**Comment by CamJN** [comment]
I dunno, apachectl on osx is just a wrapper around launchctl, so I imagine that most people using the built in apache would be doing it this way. And I don't have the stats maybe you guys do, but I imagine that the majority of people installing postgres from homebrew are doing to for web dev work.

**Comment by mikemcquaid** [comment]
@CamJN I don't think the majority of those doing web dev are necessarily using the system Apache, though.
