### ISSUE TITLE
mpfr won't install on mac OSX

### ISSUE THREAD

**Issue by adrianbutscher** [Homebrew/homebrew#50109]
Hello,

I'm trying to install the CGAL libraries using brew on my mac running OSX ElCapitan.  One of the dependencies is mpfr.  This installation failed with the error:

Installing cgal dependency: mpfr
==> Downloading http://ftpmirror.gnu.org/mpfr/mpfr-3.1.2.tar.bz2
######################################################################## 100.0%
==> Downloading https://gist.githubusercontent.com/jacknagel/7f276cd60149a1ffc9a7/raw/39116c674a8c34

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "mpfr--patch"
Download failed: https://gist.githubusercontent.com/jacknagel/7f276cd60149a1ffc9a7/raw/39116c674a8c340fef880a393d7c7bdc6d73c59e/mpfr-3.1.2-p10.diff

It looks like the link to mpfr--patch is wrong? I can't figure out what to change to point to the right place.  Has someone encountered this problem and could help?  Many thanks.

Adrian Butscher

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Specifically: run `brew update` and try again.

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by DomT4** [comment]
We haven't shipped that version of `mpfr` since July 5th 2015, FYI. We recommend updating more regularly than that :smiley:.

**Comment by adrianbutscher** [comment]
Got it!  Thanks all for your help.  I had updated brew relatively recently,
but then my mac osx update to El Capitan changed the permissions in
/usr/local/ and all hell broke loose.  I think things are under control...

A

**Comment by DomT4** [comment]
No worries at all. Generally if you've permission problems:
```bash
sudo chown -R $(whoami):admin /usr/local
```
Will resolve things. We're working on something finer-grained long-term.

Let us know if we can help further!
