### ISSUE TITLE
Question: Can I use carthage as a dependency?

### ISSUE THREAD

**Issue by mitsuse** [Homebrew/homebrew#50121]
Hi,

I'm creating the formula for [a tool written in Swift][github-sourcekittendaemon]. Can I use `carthage` as a dependency in formula? If it is unavailable, I want to know the reason.

The tools depends on `carthage` in build time. More specifically, the formula executes `carthage bootstrap` to checkout dependencies and build them. Some formulae for tools in Swift exist, but they aren't using `carthage` in build time. So there is no example about `carthage` as a dependency.

In a [pull-request][github-homebrew-36898-76880150] (but it was not merged), the formula depends on `carthage`, but was commented as follow:

> Instead of using carthage checkout this should explicitly stage any needed dependencies into buildpath as resources; v8.rb gives an example.

Thanks.

[github-sourcekittendaemon]: https://github.com/terhechte/SourceKittenDaemon
[github-homebrew-36898-76880150]: https://github.com/Homebrew/homebrew/pull/36898#issuecomment-76880150

**Comment by mikemcquaid** [comment]
You can use it as the dependency but Carthage should not be the tool that does the checkout as we cannot cache in that case.
