### ISSUE TITLE
undefined method 'new' for Patch:Module

### ISSUE THREAD

**Issue by CarbonCycles** [Homebrew/homebrew#50125]
# Please follow the general troubleshooting steps first:

- [ x] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

Running on OSX - El Capitan (10.11.3)
### Bug reports:
Checking out files: 100% (3726/3726), done.
Error: undefined method `new' for Patch:Module
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/patch.rb:115:in `initialize'
/usr/local/Library/Homebrew/patch.rb:18:in `new'
/usr/local/Library/Homebrew/patch.rb:18:in `create'
/usr/local/Library/Homebrew/software_spec.rb:168:in `patch'
/usr/local/Library/Homebrew/formula.rb:1919:in `block in patch'
/usr/local/Library/Homebrew/formula.rb:1919:in `each'
/usr/local/Library/Homebrew/formula.rb:1919:in `patch'
/usr/local/Library/Formula/a2ps.rb:19:in `<class:A2ps>'
/usr/local/Library/Formula/a2ps.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:204:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:124:in `<main>'

**Comment by mikemcquaid** [comment]
Try to run `git fetch; git reset --hard origin/master` and retry `brew update`.

**Comment by CarbonCycles** [comment]
Mike,

Will do in a bit. Running a job right now. 

Rob

**Comment by CarbonCycles** [comment]
Mike,

That got it. Looks like brew is working fine for me now. Had problems getting wget to install and now it's good. 

Thanks!

Rob

**Comment by mikemcquaid** [comment]
Great, thanks.

**Comment by dannybtran** [comment]
Also worked for me. Thank you!
