### ISSUE TITLE
Give a nicer error message on bad regex arg to brew search

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew#50131]
Should be easy if someone wants to contribute to core:

Giving `brew search` a bad regex gives an ugly error message; we should be nicer.

Ex:
```
tim@rocketman:caiso-bot (master)$ brew search /*gif*/
Error: target of repeat operator is not specified: /*gif*/
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/cmd/search.rb:93:in `initialize'
/usr/local/Library/Homebrew/cmd/search.rb:93:in `new'
/usr/local/Library/Homebrew/cmd/search.rb:93:in `query_regexp'
/usr/local/Library/Homebrew/cmd/search.rb:43:in `search'
/usr/local/Library/brew.rb:83:in `<main>'
```

should say `/*gif*/ is not a valid regex` without a traceback instead. cf: http://chatbot.brew.sh/freenode/machomebrew/2016-03-15/?msg=3982&page=5

**Comment by wannabefro** [comment]
@tdsmith I took a stab at it and would appreciate any feedback on it. Thanks!
