### ISSUE TITLE
Cannot lock refs on brew update

### ISSUE THREAD

**Issue by dhagerty9009** [Homebrew/homebrew#50140]
I get this output when running `brew update`:
```
error: cannot lock ref 'refs/remotes/origin/master': ref refs/remotes/origin/master is at b0ea85753ecee494dc97fc9f95c5afb9d0b447be but expected 3dc4841f979401c09490bd07a46019ba0c6ebd95
Error: Fetching /usr/local/Library/Taps/phinze/homebrew-cask failed!
error: cannot lock ref 'refs/remotes/origin/master': ref refs/remotes/origin/master is at b0ea85753ecee494dc97fc9f95c5afb9d0b447be but expected 3dc4841f979401c09490bd07a46019ba0c6ebd95
Error: Fetching /usr/local/Library/Taps/homebrew/homebrew-versions failed!
error: cannot lock ref 'refs/remotes/origin/master': ref refs/remotes/origin/master is at b0ea85753ecee494dc97fc9f95c5afb9d0b447be but expected 3dc4841f979401c09490bd07a46019ba0c6ebd95
Error: Fetching /usr/local failed!
```

`brew update` still runs as expected, and here is the output when I run `brew doctor`:
```
Your system is ready to brew.
```

I'm wondering if there's anything I can do to fix the issue with these 'cannot lock ref' errors.

**Comment by ilovezfs** [comment]
Can you paste the output of
```
find -E `brew --prefix` -regex '.*\.git$' -exec sh -c 'ls -ld "{}" && [ -f "{}"/info/refs ] && ls -l "{}"/info/refs' \;
```
please

**Comment by dhagerty9009** [comment]
Sure, here it is:
```
drwxr-xr-x  16 david  wheel  544 Mar 15 15:37 /usr/local/.git
-rw-r--r--  1 david  wheel  261 Oct 23 18:16 /usr/local/.git/info/refs
-r--r--r--  1 david  wheel  45 Mar 13  2015 /usr/local/Cellar/haxe/HEAD/lib/haxe/extra/haxelib_src/.git
drwxr-xr-x  12 david  wheel  408 Feb 12 15:39 /usr/local/Cellar/rbenv/1.0.0/plugins/rbenv-ctags/.git
drwxr-xr-x  12 david  wheel  408 Jan  8 13:01 /usr/local/Cellar/rbenv/1.0.0/plugins/rbenv-default-gems/.git
drwxr-xr-x  12 david  wheel  408 Jan  8 12:55 /usr/local/Cellar/rbenv/1.0.0/plugins/rbenv-update/.git
drwxr-xr-x  15 david  wheel  510 Mar 15 15:31 /usr/local/Library/Taps/caskroom/homebrew-cask/.git
-rw-r--r--  1 david  wheel  13848 Feb 16 12:19 /usr/local/Library/Taps/caskroom/homebrew-cask/.git/info/refs
drwxr-xr-x  15 david  wheel  510 Mar 15 15:31 /usr/local/Library/Taps/codeclimate/homebrew-formulae/.git
drwxr-xr-x  15 david  wheel  510 Mar 15 15:31 /usr/local/Library/Taps/goles/homebrew-battery/.git
drwxr-xr-x@ 5 david  wheel  170 Oct 17  2014 /usr/local/Library/Taps/homebrew/homebrew-dupes/.git
drwxrwxr-x  14 david  wheel  476 Mar 15 15:31 /usr/local/Library/Taps/homebrew/homebrew-games/.git
drwxr-xr-x  15 david  wheel  510 Mar 15 15:31 /usr/local/Library/Taps/homebrew/homebrew-services/.git
drwxr-xr-x@ 6 david  wheel  204 Oct 17  2014 /usr/local/Library/Taps/homebrew/homebrew-versions/.git
drwxr-xr-x@ 7 david  wheel  238 Oct 17  2014 /usr/local/Library/Taps/phinze/homebrew-cask/.git
```

**Comment by ilovezfs** [comment]
OK, so it's probably just an ordinary permissions/ownership issue.

```
sudo chown -R david:staff /usr/local
sudo chmod -R o+w /usr/local
sudo chmod -R g+w /usr/local
brew update
brew update
```

**Comment by DomT4** [comment]
Please let us know if we can assist further here, Thanks!

**Comment by dhagerty9009** [comment]
Changing the permissions didn't help, and now my zsh installation is complaining about insecure directories.

**Comment by ilovezfs** [comment]
@dhagerty9009 Can you come on IRC so that we can debug this interactively?
https://www.irccloud.com/#!/ircs://irc.freenode.net:6697/%23machomebrew
freenode #machomebrew
I'd recommend IRCCloud, Colloquy, or Textual if you don't already have a preferred IRC client.

**Comment by dhagerty9009** [comment]
If it persists tomorrow, I’ll come on. I noticed that the ‘others’ group had read, write and execute permissions on `/usr/local`, so changing that fixed the zsh completions issue, and I think it should fix the issue with homebrew updating.

--
David Hagerty
404-245-6810
Email  |  Twitter  | GitHub | Blog

"To be nobody but yourself in a world which is doing its best, night and day, to make you everybody else means to fight the hardest battle which any human being can fight; and never stop fighting." - E. E. Cummings

On March 25, 2016 at 5:49:59 PM, ilovezfs (notifications@github.com) wrote:

@dhagerty9009 Can you come on IRC so that we can debug this interactively?
https://www.irccloud.com/#!/ircs://irc.freenode.net:6697/%23machomebrew
freenode #machomebrew
I'd recommend IRCCloud, Colloquy, or Textual if you don't already have a preferred IRC client.
