### ISSUE TITLE
Error message: problem using /usr/bin/otool

### ISSUE THREAD

**Issue by cmaynard** [Homebrew/homebrew#50157]
Not sure where this error message is coming from:

```
~ $ brew update
Updated Homebrew from b0ea857 to 4251efa.
Updated 1 tap (caskroom/cask).
==> Updated Formulae
gjstest                                               infer                                                 v8                                                  
~ $ brew upgrade
Error: Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool
~ $ brew doctor
Error: Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool
```

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by cmaynard** [comment]
I don't see any troubleshooting steps that are relevant to this problem. The developer tools for Xcode 7.2.1 are installed. Permissions for /usr/bin/otool allow me to read and execute.

Could you explain what information you want me to post?

**Comment by evantill** [comment]
@mikemcquaid the problem is that homebrew expect `ìnstall_name_tool` to be in `/usr/bin`but it could be in other places (in my case default installation path selected by xcode-select is `/Library/Developer/CommandLineTools/usr/bin/`).

using `xcrun --find install_name_tool` will return the correct path.

**Comment by evantill** [comment]
@cmaynard I think that @mikemcquaid ask you to create a gist with the outputs of `brew doctor` `brew config`.

if you could also add `brew doctor -d` to see if your issue is the same as #50091.

**Comment by evantill** [comment]
@cmaynard is this a fresh new install ?

**Comment by cmaynard** [comment]
I thin I see the problem:

```
~ $ xcrun --find install_name_tool

xcrun: error: active developer path ("/Applications/Xcode-beta.app/Contents/Developer") does not exist, use `xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools (or see `man xcode-select`)

```
I was using a beta version of Xcode last week and I switched back to Xcode 7.2.1 over the weekend. Somehow things got confused along the way.

**Comment by cmaynard** [comment]
Problem solved:
`~ $ sudo xcode-select --switch /Applications/Xcode.app
`

**Comment by cmaynard** [comment]
Closing.
