### ISSUE TITLE
SUID for MTR

### ISSUE THREAD

**Issue by deseven** [Homebrew/homebrew#50207]
Since mtr needs root privileges in order to use raw sockets it would be nice to use setuid for it and to stop wasting time with sudo and password entering. This is a default behaviour in many linux distros along with macports, for example.
```sudo chown root:wheel /usr/local/Cellar/mtr/0.86/sbin/mtr```
```sudo chmod u+s /usr/local/Cellar/mtr/0.86/sbin/mtr```

Another way is to use capabilities (setcap/getcap), but it's not available for OS X.

**Comment by DomT4** [comment]
Feel free to do this yourself, but Homebrew doesn't embed any functionality beyond the initial setup (and even then, it's optional) that requires `sudo`, and we're not overly comfortable suggesting to users who may not be familiar with the security/usability pros/cons of `setuid` that they adopt it blindly.
