### ISSUE TITLE
Can't get `chmod` to work

### ISSUE THREAD

**Issue by cbeust** [Homebrew/homebrew#50217]
The following install:

```
  def install
    libexec.install %w[kobalt]

    kobaltw = bin/"kobaltw-foo"
    kobaltw.write "java -jar #{libexec}/kobalt/wrapper/kobalt-wrapper.jar"
    kobaltw.chmod 0755
  end
```

Does create the `kobaltw-foo` file as expected but does not make it executable:

```
🍺  /usr/local/Cellar/kobalt/0.683: 4 files, 29.2M, built in 0 seconds
-rw-r--r--  1 beust  admin           324 Mar 18 03:23 /usr/local/Cellar/kobalt/0.683/INSTALL_RECEIPT.json
-r--r--r--  1 beust  admin            82 Mar 18 03:23 /usr/local/Cellar/kobalt/0.683/bin/kobaltw-foo
-rw-r--r--  1 beust  285597778  30645879 Jan  1  1980 /usr/local/Cellar/kobalt/0.683/libexec/kobalt/wrapper/kobalt-0.683.jar
-rw-r--r--  1 beust  285597778      7758 Jan  1  1980 /usr/local/Cellar/kobalt/0.683/libexec/kobalt/wrapper/kobalt-wrapper.jar
```

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [ x Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

**Comment by dunn** [comment]
`chmod` is a method of `FileUtils` rather than `Pathname` (which is what `kobaltw` is).  Try 
```ruby
chmod 0755, kobaltw

**Comment by bfontaine** [comment]
@dunn It’s also a method of `Pathname`, which is why it’s strange it doesn’t work: http://ruby-doc.org/stdlib-2.1.0/libdoc/pathname/rdoc/Pathname.html#method-i-chmod

**Comment by cbeust** [comment]
@dunn I already tried that, and also `system kobaltw, "0755"`, none work.

I can do the `chmod` manually from bash, though, so it's not a permission issue (but we already knew that since the file gets created).

Using Mac OS 10.11.1 (El Capitan).

**Comment by dunn** [comment]
Oh, I think it's because what you're creating doesn't have a proper shebang, so the cleanup that Homebrew does resets the permissions.  Try
```ruby
(bin/"kobaltw-foo").write <<-EOS.undent
  #!/bin/bash
  java -jar #{libexec}/kobalt/wrapper/kobalt-wrapper.jar
EOS
```
Then it should get made executable automatically, without `chmod`.

**Comment by cbeust** [comment]
That was it, thanks @dunn!  I would never have been able to figure this out.

**Comment by dunn** [comment]
No problem! Our documentation could be better :grimacing:
