### ISSUE TITLE
hrmm sickrage.rb

### ISSUE THREAD

**Issue by rhiann0n** [Homebrew/homebrew#50223]
noticing sickrage.rb and sickbeard.rb in my brew path

Looks like this was installed with brew... what is it used for?

**Comment by rhiann0n** [comment]
Looks like its associated with Openssl...  Doing some research on this as I don't know how the purpose of its code is valid

**Comment by rhiann0n** [comment]
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/sickbeard.rb

**Comment by DomT4** [comment]
Sorry, I don't quite understand your question, could you elaborate?

They are regular formulae files that should reside in `$(brew --prefix)/Library/Formula`. Are you saying they're out-of-place or installed without you expecting them to be so or?

We don't install anything by default, so if the latter either you executed `brew install` on `sickrage` and `sickbeard` or you installed something that depends on them.

**Comment by tdsmith** [comment]
Please let us know if we can help with anything.

**Comment by rhiann0n** [comment]
@tdsmith  @DomT4 
As I mentioned above, there are a couple of scripts, called sickbeard.rb and sickrage.rb.  It appears to be packaged with some things in home-brew, but I'm unable to determine which package if not basic, that it belongs to.  I see it within the code base, here: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/sickbeard.rb

I'm sorry if I'm not being clear, but I would appreciate any pointers you might have.  I inspected every brew package I have installed, and cannot find the source.  If you look at the code, it appears to be a torrent thing, and I do not know how that would relate to any packages that I have installed anyway.

So if it is valid for something, or even required by base (the other places I have brew does not have it), what is the use case for it to be present?  If you need me to clarify even further as to why I'm asking about this script, let me know, since it appears above I did not provide enough information.

I'm just curious, and hoping you, the author(s), can help me figure this out.

**Comment by rhiann0n** [comment]
Please re-open.

**Comment by mikemcquaid** [comment]
@rhiann0n Quoting @DomT4 above: we don't install anything by default, so if the latter either you executed `brew install` on sickrage and sickbeard or you installed something that depends on them.

**Comment by DomT4** [comment]
> As I mentioned above, there are a couple of scripts, called sickbeard.rb and sickrage.rb that appear to be packaged with some things in home-brew, but I'm unable to determine which package if not basic, that these scripts belongs to.

> On my mac, I see them in /usr/local/Library/Formula/

As far as I can tell you're just describing formulae, which are our package files. That they exist doesn't mean they are installed. Should be about 3500 files in that `Formula` directory.

To be completely explicit: Nothing about Homebrew itself uses `sickbeard` or `sickrage`, and we won't have installed them on your behalf.

**Comment by rhiann0n** [comment]
@mikemcquaid   I am running `brew ls --verbose $i` for every package I have.  Not returning any results that return which.  I guess I could just install each one by one, to determine which.  

This is why I'm concerned.  If at any time, we are concerned about contents, how do we approach?  This is important from a validation or pre-vetting stance, say, if we want to ensure a package does not include malicious code.

widgetss-MacBook-Air:Formula widgets$ for i in `brew list` ; do echo " "  ; echo == $i == ; brew deps $i ; done
 
== ansible ==
libyaml
makedepend
openssl
pkg-config
 
== basex ==
 
== fabric ==
 
== gcc ==
gmp
isl
libmpc
mpfr
xz
 
== gdbm ==
 
== gmp ==
xz
 
== isl ==
gmp
xz
 
== jq ==
bison
oniguruma
 
== libmpc ==
gmp
mpfr
xz
 
== libyaml ==
 
== mpfr ==
gmp
xz
 
== oniguruma ==
 
== openssl ==
makedepend
pkg-config
 
== python ==
Error: No available formula with the name "homebrew/dupes/tcl-tk" 
Please tap it and then try again: brew tap homebrew/dupes
 
== readline ==
 
== sqlite ==
icu4c
readline

**Comment by DomT4** [comment]
From your list there you don't have either of the `sick*` formula installed. I stress here that the `.rb` scripts in `Formula` are _only_ scripts; nothing is executed or installed unless you request it or another formula requires it. The only contents of those files in `$(brew --prefix)/Library/Formula` are Ruby DSL.

No upstream code is called, fetched, installed or executed from any project unless you or something else executes `brew install` on that formula, period.

If you're interested in installing those formulae but want to read the upstream source code first you can do that. In this case both are on GitHub: https://github.com/SiCKRAGETV/SickRage & https://github.com/midgetspy/Sick-Beard.

**Comment by rhiann0n** [comment]
@mikemcquaid  @DomT4   You are stating the obvious.

I know how to find X repo on github.  I am trying to determine package validation methods.  Any advice you can provide on such would be appreciated.  I don't think you understand that I realize that these scripts are installed by the package, but if they are dependencies I need to know by which package and why.   I understand how to find a package on github.  I have done due diligence researching this issue on my end, and I'm now posting this issue to ask why.
If you cannot tell me in specific terms, the reason why, that's cool too.
Surely there is a way to do this as that method exists in other package managers.
But perhaps endpoints are not looked at in the same light as servers with the thought that we may never need to determine origin?

**Comment by rhiann0n** [comment]
Please re-open this ticket.  The question is not answered.

**Comment by dunn** [comment]
> I realize that these scripts are installed by the package

They are not.  The `.rb` scripts in `Library/Formula` are formula files that tell Homebrew how to install the corresponding packages.

**Comment by rhiann0n** [comment]
How would you prefer me to pose the question?  
This script has me concerned: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/sickbeard.rb

I'm trying to determine why its there.  No commands I'm running are helping me to determine why and it does not seem like any commenters this far are eager to help.   Nor has this issue been reopened.

This is becoming an issue about me, rather than an issue about package validation?

**Comment by dunn** [comment]
> This script has me concerned: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/sickbeard.rb
> 
> I'm trying to determine why its there.

It's installed, like all the files in that directory, by Homebrew.  These files are the instructions Homebrew uses to install software.  Without `sickbeard.rb` it's impossible to `brew install sickbeard`.

**Comment by rhiann0n** [comment]
I do not have sickbeard installed.

**Comment by dunn** [comment]
I know.  Homebrew doesn't install anything automatically, but it installs all the scripts in `Library/Formula` so that it _can_ install formulae when you run `brew install`.  Those scripts, `sickbeard.rb` and the rest, are the instructions that Homebrew reads _when_ you run `brew install sickbeard`.  If you ran `rm $(brew --prefix)/Library/Formula/*.rb` you would lose the ability to install _anything_ with Homebrew.

**Comment by rhiann0n** [comment]
I had asked if this was put here by homebrew initially:

  We are moving in circles here.  Either I am not explaining the issue correctly or you are failing to understand the question.  I am trying to determine why this script is here. 
Are you saying that it is put there by Homebrew initially?  Because prior, I was told that was not the case.

> We don't install anything by default, so if the latter either you executed brew install on sickrage and sickbeard or you installed something that depends on them.

**Comment by DomT4** [comment]
> Are you saying that it is put there by Homebrew initially? 

Yes.

> Because prior, I was told that was not the case.

This was apparently a misunderstanding. You seemed to be talking about the package rather than the script, hence the answer.

Our formula files [are part of the core installation](https://github.com/Homebrew/homebrew/tree/master/Library/Formula), yes, because Homebrew wouldn't function without them. However, the upstream packages those formula files represent _are not_ installed. Everything that is part of Homebrew by default is what you see in this GitHub repository.

**Comment by dunn** [comment]
We don't install any _software_ by default, other than Homebrew.  The scripts in `/usr/local/Library/Formula/` are part of Homebrew.

**Comment by rhiann0n** [comment]
Okay, I see what you are saying now.  

You are saying that some package, in the possible future, that I might install, may depend on this script, so its present in a benign way, until that date.

If you can confirm that, I would appreciate it.

**Comment by dunn** [comment]
That's correct.

**Comment by rhiann0n** [comment]
@dunn   Thank you.

**Comment by DomT4** [comment]
That's an accurate summary, yes. It's perhaps worth noting that currently nothing in Homebrew depends on either of those packages, so the only way they would currently be installed is if you explicitly requested it via `brew install`.
