### ISSUE TITLE
Formulas that only do 'etc.install' terminate with 'Error: Empty installation' 

### ISSUE THREAD

**Issue by paul-hammant** [Homebrew/homebrew#50231]
In respect of https://github.com/pcattori/homebrew-tap, do:

    brew tap pcattori/tap
    brew install --verbose pcattori/tap/jump

Observe:

    ==> Installing jump from pcattori/tap
    ==> Downloading https://github.com/pcattori/jump/archive/1.0.0.tar.gz
    Already downloaded: /Library/Caches/Homebrew/jump-1.0.0.tar.gz
    ==> Verifying jump-1.0.0.tar.gz checksum
    tar xvf /Library/Caches/Homebrew/jump-1.0.0.tar.gz
    x jump-1.0.0/
    x jump-1.0.0/README.md
    x jump-1.0.0/jump-module.bash
    Error: Empty installation

The intention of that formula was to install jump-module.bash then print to the console, some advice about what to change in ~/.bash_profile. It terminates before it prints that advice.  Surely etc.install is as appropriate as bin.install.  How is "Empty" determined?

**Comment by mikemcquaid** [comment]
This will be because `etc.install` does not install to the Cellar but instead installs just to `HOMEBREW_PREFIX/etc` so it not versioned and cannot be uninstalled. I think the error does make sense in this case.

**Comment by paul-hammant** [comment]
Heeded, and worked around with a NOOP bin.install usage.
