### ISSUE TITLE
Suggestion:  formulas need a mechanism to be able to modify ~/.bash_profile in an idempotent way

### ISSUE THREAD

**Issue by paul-hammant** [Homebrew/homebrew#50232]
Consider the formula: 

    class MyFormula < Formula
        def install
            bash_profile.install "echo foo bar baz"
        end
    end

When installed, it would lead to a section in ~/.bash_profile like so:

    # Homebrew formula <tapName>MyFormula start
    echo foo bar baz
    # Homebrew formula <tapName>MyFormula end

Uninstall could nix it too.

Refer https://github.com/pcattori/homebrew-tap/blob/master/jump.rb for a caveats usage that's a compromise versus first class support for modifying ~/.bash_profile

**Comment by mikemcquaid** [comment]
As a design principle Homebrew doesn't ever intentionally modify files outside of `HOMEBREW_PREFIX` and (`install` outside the `Cellar`).

**Comment by paul-hammant** [comment]
Worked around: https://github.com/paul-hammant/homebrew-tap/blob/master/switchjdk.rb. I suspect someone could do some brew-idiomatic Ruby fragment that can be inlined in the formula, but I also needed to overcome homebrew/issues/50231 at the same time, and a bash script suited that too.
