### ISSUE TITLE
awscli fails to download

### ISSUE THREAD

**Issue by alex** [Homebrew/homebrew#50240]
Attempting to upgrade `awscli` today, I hit an error downloading the bottle:

```
==> Upgrading awscli
==> Downloading https://homebrew.bintray.com/bottles/awscli-1.10.14.el_capitan.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "awscli"
Download failed: https://homebrew.bintray.com/bottles/awscli-1.10.14.el_capitan.bottle.tar.gz
```

Manually attempting to download that confirms it's an issue. Other bottles work fine.

**Comment by DomT4** [comment]
Ah, looks like @nijikon maybe forgot to pull the new bottle or there was some other error in building it when the update was merged in https://github.com/Homebrew/homebrew/commit/96175767780ccf15944285562a1a9361974ca867.

I'll remove the bottles temporarily and get CI to produce some new ones to check it wasn't the downstream bottle job that fell apart.

**Comment by nijikon** [comment]
I did pull with bottles but there was some other error and I didn't know how to handle this. Thanks for fixing this @DomT4.

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew/commit/7e7fadbdee11ca7431661346140c0021f6858e42. Thanks for the report @alex!
