### ISSUE TITLE
bash-completion has an unresolved git diff

### ISSUE THREAD

**Issue by merikan** [Homebrew/homebrew#50241]
The source code of bash-completion still contains a git diff.

**Comment by UniqMartin** [comment]
If you're having an issue with the formula, please follow the steps of our [troubleshooting guide](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md) and provide the requested information. Thanks!

If you're referring to the inline diff [at the end of `bash-completion.sh`](https://github.com/Homebrew/homebrew/blob/7e6527114f631ff8914e69a911a5d11c40c0c842/Library/Formula/bash-completion.rb#L53-L75), that's supposed to be there and is referenced [in the `patch :DATA` line](https://github.com/Homebrew/homebrew/blob/7e6527114f631ff8914e69a911a5d11c40c0c842/Library/Formula/bash-completion.rb#L21). And if that's not what you mean, please explain in more detail.

**Comment by merikan** [comment]
My bad. Closing the issue.

//Peter
