### ISSUE TITLE
Inconsistent advices on $ brew doctor (El Capitan)

### ISSUE THREAD

**Issue by tmaier** [Homebrew/homebrew#50279]
> Homebrew 0.9.5 (git revision 569c4; last commit 2016-03-11)

I ran `brew doctor` and got the following output:

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: The /usr/local is not writable.

You should probably change the ownership and permissions of /usr/local
back to your user account.
  sudo chown -R $(whoami) /usr/local

Warning: The /usr/local directory is not writable.
Even if this directory was writable when you installed Homebrew, other
software may change permissions on this directory. For example, upgrading
to OS X El Capitan has been known to do this. Some versions of the
"InstantOn" component of Airfoil or running Cocktail cleanup/optimizations
are known to do this as well.

You should probably change the ownership and permissions of /usr/local
back to your user account.
  sudo chown -R $(whoami):admin /usr/local
```

### Bug reports:

Two errors are listed above. They are actually the same.
But the one suggests to run `$ sudo chown -R $(whoami) /usr/local` the other one `$ sudo chown -R $(whoami):admin /usr/local`.

Homebrew should show consistent suggestions to the user.

**Comment by ilovezfs** [comment]
They're actually two different checks and two different errors and neither piece of advice contradicts the other, though I agree they should both say the same thing. It might help make the output less jumbled if the brew doctor output had headers above each failed check saying the name of the diagnostic that was being performed.

Unfortunately neither piece of advice is perfect. More robust advice would say
```
sudo chown -R $(whoami):admin /usr/local
sudo chmod -R o+w /usr/local
sudo chmod -R g+w /usr/local
```

As a side note, I'm skeptical El Capitan still needs its own check anyway.

**Comment by chdiza** [comment]
Incidentally, one of those messages (the first one) isn't English: `Warning: The /usr/local is not writable.`

We should either drop the `The` or add `directory` after `/usr/local`.

**Comment by ilovezfs** [comment]
@chdiza Feel from to open a pull request copy editing any and all documentation. I'm sure it will be well received. For example, https://github.com/Homebrew/homebrew-services/pull/31

**Comment by mikemcquaid** [comment]
> sudo chmod -R o+w /usr/local
> sudo chmod -R g+w /usr/local

These are almost never required as the ownership changes are the problem and not the owner `chmod`.

**Comment by ilovezfs** [comment]
Generally my preferred fix is
```
sudo chgrp -R admin /usr/local
sudo chmod -R g+w /usr/local
```

**Comment by DomT4** [comment]
> Incidentally, one of those messages (the first one) isn't English: Warning: The /usr/local is not writable.

Fairly sure it's still English, even if it isn't necessary completely correct or as-expected to you :wink:.

**Comment by DomT4** [comment]
I made some changes to fix the inconsistent wording/advice. If anyone wants to do anything more major than that, please feel free to swing by with a PR! :smiley:
