### ISSUE TITLE
How to remove all the associated files

### ISSUE THREAD

**Issue by Rix1212** [Homebrew/homebrew#50275]
![screen shot 2016-03-20 at 4 05 13 pm](https://cloud.githubusercontent.com/assets/8928756/13903969/0de528da-eeb6-11e5-88b8-1034da6a43b2.png)
I have uninstalled it and I read the following message below 'The following possible Homebrew files were not deleted:' How do I remove those ?

**Comment by ilovezfs** [comment]
Well they may or may not be Homebrew files.
```
find /usr/local
```
What does that show?

**Comment by apjanke** [comment]
`.DS_Store` is a Finder dropping. And the other items mentioned are just a standard skeletal directory structure that won't cause problems for anyobody. Don't worry about them. If you really want them gone, you can delete them with `rm` for `.DS_Store` and  `rmdir` for the rest.

IMHO we might do better to filter these directories from the uninstall script and not warn about them.

**Comment by ilovezfs** [comment]
@apjanke The only reason to warn about them would be if any remaining files within them were brew files that failed to be removed, but they're much more likely to be empty or to contain non-brew files. If they are indeed empty or empty-but-for-.DS_Store, wouldn't it make more sense to remove them than just not warn about them?

**Comment by Rix1212** [comment]
@apjanke So no problem ,Right? shall I leave as it is ?

**Comment by ilovezfs** [comment]
@Rix1212 Correct, that's what he said.

As I said above, if you want to be thorough, check the output of `find /usr/local` and post it here if you have any questions about what you see.

**Comment by DomT4** [comment]
Please let us know if we can help further here at all. The `uninstall` script removes empty directories so it's likely you've something non-`brew` installed which is why they were preserved.

**Comment by Rix1212** [comment]
I have installed gem , cocopods and rebnv but i removed all .Dont know why it still exists there
