### ISSUE TITLE
Homebrew's own installation fails on El-Capitan

### ISSUE THREAD

**Issue by amosshapira** [Homebrew/homebrew#50288]
My environment:

1. Using Packer to build an OS X base box using scripts from https://github.com/timsutton/osx-vm-templates
2. On a Mac laptop running El-Capitan
3. Using El-Capitan 10.11.3 .dmg built as the basis
4. Running inside vmware-fusion 8

Trying to run the Homebrew installation command from the home page:

`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

Fails with errors like:

"error: RPC failed; result=56, HTTP code = 200"

Looking around the web I see mentions that the curl which comes with El-Capitan uses a new TLS implementation from Apple which doesn't play nicely with Github. The sad (or funny) thing is that everyone suggests to install a new openssl using..., you guessed it... "brew".

How can I overcome this chicken-and-egg conundrum? The only way I can think of right now is:

1. Download the ruby script from `master/install`
2. Modify the ruby script to use a local copy of the .tar.gz file to continue the installation.
3. Download today's .tar.gz file of the Homebrew git repository outside Packer and make it available to the virtual machine

I don't like this solution and hope to hear about a better and more elegant way.

Is there?

Thanks.

**Comment by ilovezfs** [comment]
There's nothing broken with installing brew on El Capitan, and there's nothing broken with communicating with GitHub on El Capitan. You have some kind of network issue with your virtual machine, which is really outside the scope of this issue tracker.

If I had to guess, you need to change the network adapter type from NAT to bridged in the virtual machine's settings.

**Comment by amosshapira** [comment]
Thanks. I suppose you are right since the command works OK on the laptop.
What I did after your tip is to set `vmx_temlplate_path` to a file which contains the default Packer configuration from https://github.com/mitchellh/packer/blob/20541a7eda085aa5cf35bfed5069592ca49d106e/builder/vmware/step_create_vmx.go#L84 and the only change being `ethernet0.connectionType = "bridged"`.
After that I could ssh into the vmware machine (found its IP address through `arp -a`) and execute the brew installation script manually.
However Packer fails to find the IP address. I'll ask the Packer community since I couldn't find a solution for this sofar.
