### ISSUE TITLE
case sensitivity in "suspicious git origin remote found"

### ISSUE THREAD

**Issue by agh** [Homebrew/homebrew#50306]
Running `brew doctor` after doing a `git clone https://github.com/homebrew/homebrew` results in a warning saying that it is a "non-standard origin".

This appears to be entirely because it looks for https://github.com/Homebrew/homebrew, note the difference in case in the GitHub organisation name.

Since GitHub isn't case-sensitive, perhaps we can downcase before comparing, and avoid throwing an arguably unnecessary warning in this particular situation? Thoughts?

**Comment by DomT4** [comment]
Is this error only thrown on a case-sensitive system, or on any system that uses that origin?

**Comment by ilovezfs** [comment]
It happens on case-sensitive and case-insensitive, but I see no reason to change it.

**Comment by mikemcquaid** [comment]
I don't know if GitHub guarantees the case insensitivity so I think this should remain as-is.
