### ISSUE TITLE
Homebrew hangs when installing or updating homebrew/nginx/nginx-full on Yosemite 10.10.5

### ISSUE THREAD

**Issue by dustinwilson** [Homebrew/homebrew#50369]
Homebrew hangs after completing nginx's makefile on Yosemite 10.10.5. I've tried this on two different computers, and one had a clean install of homebrew. Nginx finishes making and installing. Everything's within its cellar folder. I also know everything finished because if I copy that folder out while it is hanging, ctrl+C, copy the folder back in, and then `brew link nginx-full` it works just fine. I've also tested on El Capitan, and things work just fine there.

https://gist.github.com/anonymous/0a676790862f861c119d

**Comment by dunn** [comment]
This issue was moved to Homebrew/homebrew-nginx#167

**Comment by aaronbruckner** [comment]
I know the ticket is closed but I was able to narrow this issue to something outside of the nginx formula. For anyone interested I posted my findings to the opened issue above. More work to be done to determine what's the underlying cause.
