### ISSUE TITLE
Building the GIMP GUI

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew#50397]
Has anybody put any work into trying to make running `brew install --build-from-source gimp` build the OS X GIMP GUI&thinsp;—&thinsp;i. e.:  the one that you could run `brew linkapps gimp` on?  If not, is anybody planning on looking into it, or should I just try and create a pull request to that effect (if it's possible) when I get the time?

**Comment by DomT4** [comment]
As far as I know nobody has worked on creating the `.app` bundle as part of the formula, and I think you're the first to request it to be honest.

We'd consider a PR for it if anyone wanted to take a swing at it, as long as doing so doesn't require overly elaborate dancing, essentially.

**Comment by RandomDSdevel** [comment]
@DomT4:  OK, and thanks.
