### ISSUE TITLE
libmonome failed to build on 10.11.3

### ISSUE THREAD

**Issue by jasonw22** [Homebrew/homebrew#50396]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [N/A] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:
libmonome failed to build. Build reports "Checking for liblo: not found" yet if I try to install liblo:

➜  ~ brew install liblo
Warning: liblo-0.28 already installed

Here's the gist-log from brew
https://gist.github.com/anonymous/9d353d43c977b8204774

**Comment by samdoshi** [comment]
Can you try installing the Xcode command line tools?
```
xcode-select --install
```

**Comment by ilovezfs** [comment]
I cannot reproduce this using Xcode, no command line tools. So probably not relevant. You could try

```
brew uninstall -f liblo
brew install libmonome
```

**Comment by jasonw22** [comment]
Thanks @ilovezfs, that worked
