### ISSUE TITLE
Feature request: More style in the script.

### ISSUE THREAD

**Issue by easyaspi314** [Homebrew/homebrew#50444]
I always liked how Homebrew uses emoji in its script, but there are a few things that bother me. 

[This Gist](https://gist.github.com/sstephenson/4587282) has a neat little shell script that changes `curl` progress to blocks instead of hashes. It is under the public domain and it is used by just substituting "curl" with "curl-progress". 
I think that would look a lot better. 
![screen shot 2016-03-26 at 12 31 29 pm](https://cloud.githubusercontent.com/assets/6258309/14061130/b7f3db40-f34e-11e5-86a5-6c0a143dcb9b.png)
![screen shot 2016-03-26 at 12 34 17 pm](https://cloud.githubusercontent.com/assets/6258309/14061144/18d3a3aa-f34f-11e5-828e-464d318a21c4.png)

Also, for an arrow, I suggest this:
■■► (Black Square, Black square, Black Right-pointing pointer). It looks a lot better in the terminal: ![screen shot 2016-03-26 at 12 26 51 pm](https://cloud.githubusercontent.com/assets/6258309/14061111/224b639c-f34e-11e5-85cd-b68e238f87e8.png)
than `==>`

**Comment by dunn** [comment]
> It looks a lot better in the terminal than `==>`

I'm not sure if I agree there.

We'd happily review pull requests for either or both feature, though.  Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions!

**Comment by easyaspi314** [comment]
Unfortunately, Ruby is Greek to me and I am not very good at shell
scripting.  :(

I would if I could.

**Comment by mikemcquaid** [comment]
I consider this a `curl` rather than Homebrew feature request, sorry!

**Comment by easyaspi314** [comment]
I don't think so. I think this is more of a homebrew thing.

You have emoji and colors, then a 90s-style progress bar. I think it is out
of place. In my personal opinion.

Curl should be curl. And Mac's curl probably isn't going to be updated. It
may be in an ASCII-only shell. Homebrew is almost always in Bash with Mac's
built-in terminal.
