### ISSUE TITLE
Homebrew invalidates sudo upon package intsall

### ISSUE THREAD

**Issue by fgimian** [Homebrew/homebrew#50484]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Homebrew invalidates an existing sudo session when installing a package.  This makes it very hard to have unattended installs using Homebrew and a tool like Ansible.  Setting NOPASSWD in sudo is very insecure.

See below for a basic example using the **rlwrap** package, my sudo timeout is set to 5 minutes:

```
 franko ~: date
Tue 29 Mar 2016 00:33:57 AEDT
 franko ~: sudo -v
Password:
 franko ~: brew install rlwrap
==> Downloading http://utopia.knoware.nl/~hlub/rlwrap/rlwrap-0.42.tar.gz
Already downloaded: /Library/Caches/Homebrew/rlwrap-0.42.tar.gz
==> ./configure --prefix=/usr/local/Cellar/rlwrap/0.42
==> make install
🍺  /usr/local/Cellar/rlwrap/0.42: 29 files, 236K, built in 9 seconds
 franko ~: date
Tue 29 Mar 2016 00:34:16 AEDT
 franko ~: sudo -v
Password:
```

Can you provide a way to disable this behaviour or consider removing it entirely?

Thanks
Fotis

**Comment by tdsmith** [comment]
Revoking sudo tokens is important so that build scripts can't silently acquire root access. I think this behavior should not change. One alternative is to use a dedicated user account for Homebrew without root sudo privileges, and use sudo to run as that user.

**Comment by fgimian** [comment]
Thank you very much for the reply @tdsmith 

I completely understand where you're coming from.  Though would it be possible to allow an option that doesn't do this?  In a case where one has a script that performs installs using Homebrew and trusts installers being used, they could choose to override this for a true unattended install.

This affects projects such as my [macbuild](https://github.com/fgimian/macbuild) and [superlumic](https://github.com/superlumic/superlumic).  In fact, they have an issue https://github.com/superlumic/superlumic/issues/5 open about the same problem :smile: 

At this stage, the only workaround I can think of is setting NOPASSWD for the current user during installation.

Kindest regards and thank you so much once again for all your efforts
Fotis

**Comment by mikemcquaid** [comment]
I'd rather not make this optional, it's an intentional security feature. Sorry!

**Comment by fgimian** [comment]
I understand and respect your decision, thank you :smile:
