### ISSUE TITLE
Compilation issue with HEAD version of llvm

### ISSUE THREAD

**Issue by tupos** [Homebrew/homebrew#50508]
Good morning,

sorry for a very newbie question.

I have installed HEAD version of llvm, the installation went ok. However, when I try to compile a simple hello world program for some reason clang fails to find standard headers, despite that i tried to follow what is written in the homebrew-versions about llvm 
"To link to libc++, something like the following is required:
`CXX="clang++-#{ver} -stdlib=libc++"
CXXFLAGS="$CXXFLAGS -nostdinc++ -I#{opt_lib}/llvm-#{ver}/include/c++/v1"
LDFLAGS="$LDFLAGS -L#{opt_lib}/llvm-#{ver}/lib`"

Summarizing I compile the test program as
`/usr/local/opt/llvm/bin/clang++ -o test test.cpp -nostdinc++ -stdlib=libc++ -I/usr/local/opt/llvm/include/c++/v1 -L/usr/local/opt/llvm/lib -v`

and obtain :

```
clang -cc1 version 3.9.0 based upon LLVM 3.9.0svn default target x86_64-apple-darwin15.4.0
ignoring nonexistent directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/opt/llvm/include/c++/v1
 /usr/local/include
 /usr/local/Cellar/llvm/HEAD/bin/../lib/clang/3.9.0/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
In file included from test.cpp:1:
In file included from /usr/local/opt/llvm/include/c++/v1/iostream:38:
In file included from /usr/local/opt/llvm/include/c++/v1/ios:215:
In file included from /usr/local/opt/llvm/include/c++/v1/iosfwd:90:
/usr/local/opt/llvm/include/c++/v1/wchar.h:119:15: fatal error: 'wchar.h' file not found
#include_next <wchar.h>
              ^
1 error generated.
```

Any help will be highly appreciated.

Thank you.

**Comment by mikemcquaid** [comment]
Sorry, we don't provide software usage support.
