### ISSUE TITLE
C compiler cannot create executables

### ISSUE THREAD

**Issue by dharmik16** [Homebrew/homebrew#50510]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

I am trying to install qemu for Mac OS X following the steps on https://github.com/psema4/pine/wiki/Installing-QEMU-on-OS-X. However when I try to execute the command - "brew install qemu --env=std --cc=gcc-4.2", I am getting the following error.

dharmikt-mbp:local dharmikt$ brew install qemu --env=std --cc=gcc-4.2
==> Installing dependencies for qemu: libtool, libffi, glib, pixman
==> Installing qemu dependency: libtool
==> Downloading http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.xz
Already downloaded: /Library/Caches/Homebrew/libtool-2.4.6.tar.xz
==> ./configure --prefix=/usr/local/Cellar/libtool/2.4.6 --program-prefix=g --enable-ltdl-install
Last 15 lines from /Users/dharmikt/Library/Logs/Homebrew/libtool/01.configure:
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-apple-darwin14.5.0
checking host system type... x86_64-apple-darwin14.5.0
configure: autobuild project... GNU Libtool
configure: autobuild revision... 2.4.6
configure: autobuild hostname... dharmikt-mbp
configure: autobuild mode... default
configure: autobuild timestamp... 20160329T092710Z
checking for gcc... /usr/local/bin/gcc-4.2
checking whether the C compiler works... no
configure: error: in `/private/tmp/libtool20160329-80098-8mkbm0/libtool-2.4.6':
configure: error: C compiler cannot create executables
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
These open issues may also help:
docker: fix --with-experimental (libtool dependency and optional hardware signing) https://github.com/Homebrew/homebrew/pull/50401

I have attached the log files below.

[ConfigureLog.zip](https://github.com/Homebrew/homebrew/files/193177/ConfigureLog.zip)

**Comment by bfontaine** [comment]
Please post the output of `brew gist-logs qemu`.

**Comment by ilovezfs** [comment]
Why aren't we just doing `brew install qemu`?

**Comment by dharmik16** [comment]
@bfontaine I didn't found any logs. However I was able to install using 'brew install qemu'. Thanks for your response.
@ilovezfs The method that I tried was one of the top results I found on google. Later I was able to figure out that and have installed qemu. Thanks for your response.

**Comment by ilovezfs** [comment]
@dharmik16 You're welcome!
