### ISSUE TITLE
Installing files in a directory outside of bin, sbin, include, lib, etc.

### ISSUE THREAD

**Issue by EdSchouten** [Homebrew/homebrew#50516]
Hi there,

I'm the author of CloudABI, a compact UNIX-like runtime environment based on capability-based security (https://nuxi.nl/, https://www.youtube.com/watch?v=62cYMmSY2Dc). To make it easier to develop software for CloudABI, I'm currently working on packaging this software (e.g., https://github.com/NuxiNL/cloudlibc) for a variety of operating systems. In the end I want to reach a state where it doesn't matter which operating system you're using (a Linux distro, Mac OS X, FreeBSD, Windows?, etc), installing an SDK for CloudABI should be easy and should produce consistent results.

Instead of inventing yet another package manager (a la CPAN), my thought is that users should be able to use a package manager that they are already familiar with. On Debian, users can currently just `apt-get install` cross compiled libraries. This also ensures that users can stay up-to-date easily. On Mac OS X I'd be interested in using Homebrew for this purpose. For this reason I am experimenting with bottling software that I've already ported over to CloudABI (https://github.com/NuxiNL/cloudabi-ports), which I'd like to host under a separate tap.

While bottling up cross compiled libraries for CloudABI, I noticed that Homebrew does not want to set up symbolic links to files outside of bin, sbin, include, lib, etc. Though I understand the reasoning behind this entirely, my concern is that such a construct doesn't work if people want to package cross compiler toolchains and libraries. GNU cross compiler toolchains are typically installed under the name `${prefix}/bin/${target}-{as,cc,ld,...}` and pull in cross compiled libraries and headers through `${prefix}/${arch}/{lib,include}`. Only leaving cross compiled libraries inside the kegs makes little sense, as all of these libraries will need to be visible to a cross compiler at once.

My question is, what would be the easiest way to deal with this? Are there any other formulas that needed to deal with similar problems? Would it make sense to provide some kind of override for this purpose?

Thanks,
Ed

**Comment by mikemcquaid** [comment]
> My question is, what would be the easiest way to deal with this?

Symlink paths such that they are in locations that we expect them to be.

> Would it make sense to provide some kind of override for this purpose?

I don't think so, no. It's an issue that can be resolved by packaging it slightly differently to what other distros may do.

**Comment by EdSchouten** [comment]
My apologies, but I think your response is a bit too brief to be helpful. Which paths should be symlinked to which locations? In what way should things be packaged slightly differently?

You could reinterpret my question: if Homebrew recommends against using the de facto standard `${prefix}/${arch}` directory for storing cross compiled libraries, what pathname structure should be used instead? I've browsed through the existing formulas and I don't think there is any precedent.

**Comment by mikemcquaid** [comment]
> Which paths should be symlinked to which locations?

Any paths outside e.g. `bin`, `lib`, etc. into those paths.

> In what way should things be packaged slightly differently?

Perhaps put things into e.g. `bin`, `lib` directly.

> You could reinterpret my question: if Homebrew recommends against using the de facto standard ${prefix}/${arch} directory for storing cross compiled libraries, what pathname structure should be used instead? I've browsed through the existing formulas and I don't think there is any precedent.

It's not that we recommend or don't recommend against that, it's just that we only symlink things to certain paths so if you want the symlinking behaviour you need to install to those paths. As far as I can tell from your description: if a binary can be run on the current machine it should be in `bin`. If it cannot be run on the current machine it should be in `libexec` or `share`. I hope that helps.
