### ISSUE TITLE
libdap errors on el capitan 

### ISSUE THREAD

**Issue by CarlosGrohmann** [Homebrew/homebrew#50541]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
Yes
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
Yes
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
No

As part of GDAL complete, I need libdap, but I can't get it to compile (I just updated to OSX 10.11.4 and updated Xcode as well).
I noticed that on http://www.opendap.org/pub/source/ the latest version is 3.17.0, but the formula refers to 3.12.1.

The compilation gives me this error:

==> Downloading http://www.opendap.org/pub/source/libdap-3.12.1.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/libdap/3.12.1_1 --with-curl=/usr --wi
==> make install
Last 15 lines from /Users/guano/Library/Logs/Homebrew/libdap/02.make:
                        part = array; 
                               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:116:65: note: candidate found by name lookup is 'std::__1::array'
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
./BaseType.h:97:5: note: candidate found by name lookup is 'libdap::Part::array'
    array,
    ^
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./gl -I./GNU -I/usr/local/Cellar/libxml2/2.9.3/include/libxml2 -g -O2 -c lex.ce_expr.cc  -fno-common -DPIC -o .libs/libparsers_la-lex.ce_expr.o
1 error generated.
make[2]: *** [libparsers_la-dds.tab.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./gl -I./GNU -I/usr/local/Cellar/libxml2/2.9.3/include/libxml2 -g -O2 -c lex.ce_expr.cc -o libparsers_la-lex.ce_expr.o >/dev/null 2>&1
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2

The gist-log link:
https://gist.github.com/8e35b461b3110f36909ea690ab816c50

thanks

**Comment by ilovezfs** [comment]
Yup, definitely reproducible

**Comment by ilovezfs** [comment]
@CarlosGrohmann `brew pull 50542` if you'd like to try the fix.

**Comment by CarlosGrohmann** [comment]
Works! 
Many thank for the quick fix!

**Comment by ilovezfs** [comment]
@CarlosGrohmann You're welcome.

**Comment by ilovezfs** [comment]
Closed by https://github.com/Homebrew/homebrew-core/commit/d0ba59b8c3bc3cb0a5c6f3bfbd511bef642e5893
(https://github.com/Homebrew/homebrew/pull/50631)
