### ISSUE TITLE
Building a bottle for El Capitan while keeping old bottles

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew#50553]
Is there a mechanism to build a new bottle just for the latest Mac OS and keep the old bottles without bumping the revision?
See for example https://github.com/Homebrew/homebrew-science/pull/3488
I added a description to `exonerate`, which doesn't necessarily require bumping the bottle revision. I'd like to keep the old bottles (`--keep-old`) and build a new bottle for El Capitan.

**Comment by ilovezfs** [comment]
What would be the benefit to keeping the old bottles? Wouldn't it be good to just take it as an opportunity to refresh all the bottles against the latest OS and Xcode versions?

**Comment by sjackman** [comment]
There's no apparent need to rebuild the older bottles. Refreshing the older bottles creates unnecessary churn. I'm not sure that it's worth the creating the tooling necessary to make this work. I wanted to know whether the tooling already exists. I noticed some formula have bottles for four versions of Mac OS rather than the usual three.

**Comment by ilovezfs** [comment]
Four just means it was last updated during the brief period after el capitan bottles were added and before mountain lion bottles were dropped. If any of those are updated again, the mountain lion bottles won't be created.

**Comment by sjackman** [comment]
Okay. I believe the answer is no, then. That's good enough for me.
