### ISSUE TITLE
nginx --with-passenger failed to build on 10.11.4 clean install

### ISSUE THREAD

**Issue by Russell108** [Homebrew/homebrew#50564]
Ran `brew update
Ran `brew doctor`

I can install nginx but when I do nginx --with-passenger. Passenger installs but nginx will not install
its gets to make & never stops

Clean install of El Capitan

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by Russell108** [comment]
Sorry

I believe I have 

which steps have I missed

**Comment by Russell108** [comment]
Here is the link to my gist
<script src="https://gist.github.com/Russell108/e20e1ffa90680f82531c849d7079ab0f.js"></script>

**Comment by dunn** [comment]
This is most likely the issue:
```
Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
    /Users/russ/.rbenv/shims/passenger-config
```
Try moving that out of your `PATH` and trying again.

**Comment by Russell108** [comment]
Are you sure there are several links which say this is just a waring & can be ignored . 
In addition surely this is essential for rbenv. 
plus I just tried to install on another machine where I didn't rbenv rehash after installing the passenger gem & I still get the same error.

So I believe its something else

**Comment by mikemcquaid** [comment]
> Are you sure there are several links which say this is just a waring & can be ignored .

Yes, it's almost certainly the problem. Please try to remove `rbenv` from your PATH for now and see if it fixes the problem. If it does: we'll work on a better solution.

**Comment by Russell108** [comment]
nope as mentioned this didn't work what seems to work I used RVM instead & installed passenger & nginx in a different way. I installed  gem install passenger then rvm-passenger-install-nginx-module.
