### ISSUE TITLE
fontforge HEAD did not build

### ISSUE THREAD

**Issue by weiweihuanghuang** [Homebrew/homebrew#50571]
OS X 10.11.4
with `brew install -v fontforge --HEAD --with-libspiro --enable-pyextension`
https://gist.github.com/anonymous/8d27f42a60cec099c2beebc6727c5409

**Comment by ilovezfs** [comment]
` --enable-pyextension` is not a Homebrew option. You'd need to modify the formula itself to pass that along to configure.

Your Xcode is old and should be brought up to version 7.3

Your Homebrew has not been updated for four months so you'll need to run `brew update` three times please, as well as `brew upgrade` after Xcode is upgraded.

Once that's all taken care of,

```
brew uninstall fontforge
brew install fontforge
brew reinstall -v fontforge --HEAD --with-libspiro
```

**Comment by weiweihuanghuang** [comment]
Works now thanks
