### ISSUE TITLE
homebrew/fuse/encfs failed to build on 10.11.3

### ISSUE THREAD

**Issue by putnamhill** [Homebrew/homebrew#50576]
I received the following make error:

	aclocal: error: aclocal: file '/usr/local/share/aclocal/nspr.m4' does not exist
	autoreconf: aclocal failed with exit status: 1
	make: *** [all] Error 1

https://gist.github.com/03592a2deabf68a4101c3d0418c96fea

**Comment by ilovezfs** [comment]
I cannot reproduce this issue. Can you try in a clean brew installation? Also, that Xcode.app is quite outdated.

```
mkdir ~/Documents/brew-20160331
sudo mv /usr/local ~/Documents/brew-20160331
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install homebrew/fuse/encfs
brew reinstall --build-from-source encfs
```

**Comment by putnamhill** [comment]
It works now. Thank you!
