### ISSUE TITLE
homebrew/blob/master/Library/Formula/unixodbc.rb needs version update from 2.3.2 to 2.3.4

### ISSUE THREAD

**Issue by indera** [Homebrew/homebrew#50577]
In https://github.com/Homebrew/homebrew/blob/master/Library/Formula/unixodbc.rb

Update the package version 
-- url "http://www.unixodbc.org/unixODBC-2.3.2.tar.gz"
++ url "ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-2.3.4.tar.gz"

----
sha256sum unixODBC-2.3.4.tar.gz
2e1509a96bb18d248bf08ead0d74804957304ff7c6f8b2e5965309c632421e39  unixODBC-2.3.4.tar.gz

**Comment by ilovezfs** [comment]
Please open a pull request for this.
