### ISSUE TITLE
Brew for xfig / transfig

### ISSUE THREAD

**Issue by dgboy2000** [Homebrew/homebrew#50609]
Fellow Homebrewers,

As a first-time contributor, I'd like to request your feedback before creating a brew for [transfig / xfig](http://xfig.org/art17.html). These are required to build the [Octave](https://www.gnu.org/software/octave/) documentation from source. xfig doesn't seem to be actively maintained and required some patching, but a quick search suggests that wrapping this in a brew would be useful to a number of folks like me.

Would the community be open to a new xfig brew which installs xfig, transfig, and fig2dev? I could either host patched versions on my github or write a brew that downloads and patches the files from xfig.org.

Thanks in advance for your input!

Danny

**Comment by mikemcquaid** [comment]
There was a previous PR in https://github.com/Homebrew/homebrew/pull/15687.

> xfig doesn't seem to be actively maintained and required some patching, but a quick search suggests that wrapping this in a brew would be useful to a number of folks like me.

Unfortunately being unmaintained and requiring patching means that we would not accept this in Homebrew core. Please consider [creating your own tap](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md) instead. Thanks!
