### ISSUE TITLE
Wrong SHA2sum for cfssl

### ISSUE THREAD

**Issue by yawn** [Homebrew/homebrew#50603]
# Bug report

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

```
brew install cfssl
==> Downloading https://github.com/cloudflare/cfssl/archive/1.2.0.tar.gz
==> Downloading from https://codeload.github.com/cloudflare/cfssl/tar.gz/1.2.0
######################################################################## 100,0%
Error: SHA256 mismatch
Expected: 30301696fa7ab59aca0cf7883ee82b9b42e0e7c0022269f51454b476a9a2edf9
Actual: 28e1d1ec6862eb926336490e2fcd1de626113d3e227293a4138fec59b7b6e443
Archive: /Library/Caches/Homebrew/cfssl-1.2.0.tar.gz
To retry an incomplete download, remove the file above.
```

When downloading the file with

* `GNU Wget 1.17.1 built on darwin15.0.0` or
* Google Chrome `Version 49.0.2623.110 (64-bit)`

and checking the SHA2 sum, the hash is indeed the reported `28e1d1ec6862eb926336490e2fcd1de626113d3e227293a4138fec59b7b6e443`.

So either:

* @sheurich made a mistake in 93fe687a4680549cdef0556c0a03e19660a93f8c
* upstream changed the tarball

**Comment by ilovezfs** [comment]
It would have to be the latter. The checksum matched the already downloaded archive file in the cache.

**Comment by ilovezfs** [comment]
@yawn I've filed an upstream bug report to find out what happened https://github.com/cloudflare/cfssl/issues/568

**Comment by yawn** [comment]
Thanks!

**Comment by yawn** [comment]
Works for me! Thanks for the quick fix ...
