### ISSUE TITLE
Package installation errors with RVM

### ISSUE THREAD

**Issue by eirikkv95** [Homebrew/homebrew#50618]
Error running 'requirements_osx_brew_libs_install autoconf automake libtool pkg-config libyaml readline libksba openssl',
showing last 15 lines of /Users/eirikvattoy/.rvm/log/1459545751_ruby-2.2.4/package_install_autoconf_automake_libtool_pkg-config_libyaml_readline_libksba_openssl.log
++ case "$1" in
++ [[ -t 1 ]]
++ return 1
++ printf %b 'There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.

Check Homebrew requirements https://github.com/Homebrew/homebrew/wiki/Installation\n'
There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.

Check Homebrew requirements https://github.com/Homebrew/homebrew/wiki/Installation
++ case "$_system_version" in
++ return 1
Requirements installation failed with status: 1

**Comment by bfontaine** [comment]
This appears to be an issue with RVM. Did you try what was suggested in the error message?

**Comment by eirikkv95** [comment]
To tap in 'brew rap -- repair'??

**Comment by eirikkv95** [comment]
brew tap*

**Comment by bfontaine** [comment]
According to this [StackOverflow answer](http://stackoverflow.com/a/16643980/735926) you probably miss some requirements. You can try the following:
1. Run `brew doctor` to see if it reports any issue
2. Run `brew install autoconf automake libtool apple-gcc42 libyaml libxslt libksba openssl` and try again your RVM command

Please comment here if it worked or if you’re still experimenting the issue.

**Comment by eirikkv95** [comment]
Hey! thanks for the help :) I closed the Terminal and tried again and it worked :)

**Comment by bfontaine** [comment]
Happy to help :smile:
