### ISSUE TITLE
Should python's --with-tcl-tk option depend on osx tk?

### ISSUE THREAD

**Issue by kilojoules** [Homebrew/homebrew#50627]
I am confused about the intended use of the `--with-tcl-tk` option. When I read the description "Use Homebrew's tk instead of OS X Tk," I thought it meant that this installation was completely independent of Homebrew tk. As I demonstrated in homebrew python [issue # 270](https://github.com/Homebrew/homebrew-python/issues/270#issuecomment-204648696) where I had deleted a system tkagg file, homebrew python always relies on the osx tk. If this is intended then the description is misleading.

**Comment by tdsmith** [comment]
Does this ever cause problems? SIP should make the "damaged system Tk" problem irrelevant.

**Comment by kilojoules** [comment]
This does not cause problems during normal conditions. I am very curious why this option exists, it did not do what I thought it was intended for. What does SIP stand for?

**Comment by tdsmith** [comment]
System Integrity Protection; i.e. changing files in /System is not permitted even with root privileges on 10.11+.

The real question is what `otool -L /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_tkinter.so` reports for you; if it shows files in /System/Library, something is bad.

**Comment by tdsmith** [comment]
(Otherwise, the build is checking for files that it doesn't care about but which should always exist.)

**Comment by kilojoules** [comment]
Something may be bad

    $ otool -L /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_tkinter.so
    /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_tkinter.so:
    	/System/Library/Frameworks/Tcl.framework/Versions/8.5/Tcl (compatibility version 8.5.0, current version 8.5.9)
    	/System/Library/Frameworks/Tk.framework/Versions/8.5/Tk (compatibility version 8.5.0, current version 8.5.9)
    	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

**Comment by tdsmith** [comment]
Yeah, looks bad. @ilovezfs, you said the `python --with-tcl-tk` option works; does this make sense to you?

**Comment by tdsmith** [comment]
If I install python --with-tcl-tk I see:

```
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_tkinter.so:
	/usr/local/opt/tcl-tk/lib/libtk8.6.dylib (compatibility version 8.6.0, current version 8.6.4)
	/usr/local/opt/tcl-tk/lib/libtcl8.6.dylib (compatibility version 8.6.0, current version 8.6.4)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

so I think the python formula's option works, in general.

**Comment by ilovezfs** [comment]
@kilojoules Try
```
brew reinstall python --with-tcl-tk
brew reinstall matplotlib --with-tcl-tk
```
And then run otool again and check if matplotlib behaves as you're expecting or not.

**Comment by kilojoules** [comment]
Things work now. I think my problem was that I was compiling with gcc.
