### ISSUE TITLE
what do I have to do?

### ISSUE THREAD

**Issue by eirikkv95** [Homebrew/homebrew#50623]
Eiriks-MacBook-Pro:test_app eirikvattoy$ git commit -m "initial commit"
On branch master

Initial commit

Untracked files:
	.gitignore
	Gemfile
	Gemfile.lock
	README.rdoc
	Rakefile
	app/
	bin/
	config.ru
	config/
	db/
	lib/
	log/
	public/
	test/
	vendor/

nothing added to commit but untracked files present

**Comment by UniqMartin** [comment]
This doesn't really look like a Homebrew issue. I'll gladly reopen if I'm mistaken, but closing for now.

Please explain what you were trying to do, what you expected to happen, and what happened instead, so that we have the bare minimum of information to be able to help you.
