### ISSUE TITLE
where can I get help for a problem with git?

### ISSUE THREAD

**Issue by eirikkv95** [Homebrew/homebrew#50630]
Eiriks-MacBook-Pro:~ eirikvattoy$ git init
Reinitialized existing Git repository in /Users/eirikvattoy/.git/
Eiriks-MacBook-Pro:~ eirikvattoy$ git commit -m "initial commit"
On branch master

Initial commit

Untracked files:
	.CFUserTextEncoding
	.DS_Store
	.bash_history
	.bash_profile
	.bash_sessions/
	.bashrc
	.gem/
	.gitconfig
	.heroku/
	.mkshrc
	.netrc
	.profile
	.rvm/
	.ssh/
	.subversion/
	.zlogin
	.zshrc
	Applications/
	Desktop/
	Documents/
	Downloads/
	Library/
	Movies/
	Music/
	Pictures/
	Public/
	new path/
	railsbridge/
	rvm install ruby-2.2.4/
	rvm use 2.2/

nothing added to commit but untracked files present
Eiriks-MacBook-Pro:~ eirikvattoy$

**Comment by mikemcquaid** [comment]
This is the Homebrew project not Git, sorry.
